### ISSUE TITLE
Is there a roadmap on porting this project to Mac OS X? BSD's ? 

### ISSUE THREAD

**Issue by harshavardhana** [spdk/spdk#1]
Should it be assumed that this will work out of the box.

**Comment by jimharris** [comment]
We do not have an official roadmap, but we would love to extend SPDK to additional operating systems.  We would welcome any contributions to help make that happen.

**Comment by jimharris** [comment]
Patches to support FreeBSD have now been committed.

Support on other operating systems will be predicated by DPDK support, which currently only includes Linux and FreeBSD.  There is a well defined API for extending support to environments other than DPDK - we are working on documentation to describe that in more detail for anyone interested.

Closing this issue, but will add a separate Enhancement issue for Mac OS X.

**Comment by harshavardhana** [comment]
Thanks
