### ISSUE TITLE
compressdev needs to check for invalid parms error on submission

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1000]
On submission to compressdev API we, by design, queue up and retry any that weren't accepted as that would mean 'busy'. An update on the DPDK side needs us to now check to make sure we didn't submit an invalid entry.  Previously it would have been accepted and we would have been informed of the error on completion.  this is a pretty rare case as our op construction code is pretty solid, still need to handle the case though.

**Comment by jimharris** [comment]
Congratulations @peluse.  You just submitted issue #1000!  Your award will be sent in the mail shortly.

**Comment by peluse** [comment]
A sharp stick in the eye maybe ;)

**Comment by jimharris** [comment]
Bug scrub: https://review.gerrithub.io/c/spdk/spdk/+/472465 was merged which fixes this issue.
