### ISSUE TITLE
nvmf: intermittent failure in reconnect test

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1005]
http://10.102.17.206/private_build/autotest-per-patch_47796.html
http://10.102.17.206/results/autotest-per-patch/builds/47796/archive/nvmf_phy_autotest/build.log

(the nvmf_phy_autotest failure - the opal one is a different issue)

Relevant portion of the log:

 00:43:30	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
 00:43:30	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
 00:43:30	# perfpid=1836983
 00:43:30	# sleep 5
 00:43:30	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/examples/nvme/reconnect/reconnect -q 32 -o 4096 -w randrw -M 50 -t 20 -c 0xF -r 'trtype:rdma adrfam:IPv4 traddr:192.168.100.8 trsvcid:4420'
Starting SPDK v19.10-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: reconnect --no-shconf -c 0xF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1836983 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
 00:43:35	# kill -9 1836950
 00:43:35	# sleep 2
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_ctrlr.c: 649:nvme_ctrlr_fail: *ERROR*: ctrlr 192.168.100.8 in failed state.
A controller has encountered a failure and is being reset.
nvme_ctrlr.c:1044:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
test/nvmf/host/target_disconnect.sh: line 41: 1836950 Killed                  $NVMF_APP $1
test/nvmf/host/target_disconnect.sh: line 41: 1836983 Segmentation fault      (core dumped) $rootdir/examples/nvme/reconnect/reconnect -q 32 -o 4096 -w randrw -M 50 -t 20 -c 0xF -r "trtype:$TEST_TRANSPORT adrfam:IPv4 traddr:$NVMF_FIRST_TARGET_IP trsvcid:$NVMF_PORT"
 00:43:37	# disconnect_init
 00:43:37	# nvmfappstart '-m 0xF0'
 00:43:37	# timing_enter start_nvmf_tgt
 00:43:37	# xtrace_disable
 00:43:37	# PREV_BASH_OPTS=ehxBE
 00:43:37	# set +x
 00:43:37	# xtrace_enable
 00:43:37	# nvmfpid=1836997
 00:43:37	# trap 'process_shm --id $NVMF_APP_SHM_ID; nvmftestfini; exit 1' SIGINT SIGTERM EXIT
 00:43:37	# ./app/nvmf_tgt/nvmf_tgt -i 0 -e 0xFFFF -m 0xF0
 00:43:37	# waitforlisten 1836997
 00:43:37	# '[' -z 1836997 ']'
 00:43:37	# local rpc_addr=/var/tmp/spdk.sock
 00:43:37	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 00:43:37	# xtrace_disable
 00:43:37	# PREV_BASH_OPTS=ehxBE
 00:43:37	# set +x

**Comment by jimharris** [comment]
External links (which I should have used to begin with):

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_47796.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47796/archive/nvmf_phy_autotest/index.html

**Comment by Seth5141** [comment]
Thanks for reporting this. I think I see the problem. I added an unprotected call to nvme_rdma_qpair_disconnect in nvme_rdma_qpair_process_completions.
I think what's happening is the disconnect that happens during reset is racing with the disconnect that happens in nvme_rdma_qpair_process_completions.
The calls to nvme_rdma_qpair_disconnect have historically been shielded with the ctrlr mutex. I think the most consistent way to fix this currently would be to add a higher level function that locks the ctrlr before calling nvme_transport_ctrlr_disconnect_io_qpair. Then I'll call that when we disconnect from the process_completions function on a non-admin qpair.

**Comment by Seth5141** [comment]
Fix here: https://review.gerrithub.io/c/spdk/spdk/+/472413

Also, I did a little more examination of the logs this morning and am now more confident that this issue is directly related to racing on disconnecting qpairs from multiple threads.

In the core dump, you can see in thread 6 and thread 2 that those two are both in the middle of calling nvme_rdma_qpair_disconnect on the same qpair at the time of disconnect.
While the actual segfault occurred on thread 1, it also occurred in nvme_rdma_qpair_disconnect and it was a segfault on one of the qpair members that gets marked as NULL only during a disconnect.

**Comment by Seth5141** [comment]
The change for this was merged. I'll close this for now, but will keep an eye out for it and reopen if it hits again.
