### ISSUE TITLE
Fedora30 fail on unittest_autotests

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1006]
## Expected Behavior

unittest_autotests should pass
## Current Behavior

unittest_autotests on Fedora30 fail on:
```
vmd.c:873:8: warning: Dereference of null pointer
                            new_dev->pcie_cap->express_cap_register.bit_field.slot_implemented) {
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

```
## Steps to Reproduce

1. Run unittest on Fedora30
## Context (Environment including OS version, SPDK version, etc.)

OS version: Fedora30
Kernel: 5.3.6-200.fc30.x86_64
SPDK: current master (commit eafc447ecf1ef75002977f0e3f8a4463f6c334b4)

**Comment by ksztyber** [comment]
This patch should fix the issue: https://review.gerrithub.io/c/spdk/spdk/+/472385

**Comment by wawryk** [comment]
it works, thanks
