### ISSUE TITLE
fio_plugin cannot work  with Intel VMD enabled

### ISSUE THREAD

**Issue by ufo19890607** [spdk/spdk#1008]
Hi guys,
I just wanna run fio_plugin in VMD mode, but EAL failed to parse NVME device. Below is my system settings:

OS: centos7.4
kernel version: 3.10.0-693.el7.x86_64
SPDK version: v19.10-pre
DPDK version: 19.11.0-rc0
fio version: 3.15

I'm sure I have made the right config according to the fio_plugin readme and the only difference is that I enable Intel VMD feature. And fio_plugin runs well when I disabled Intel VMD. 

Below are the results of fio_plugin with enabled VMD and disabled VMD:
[fio_plugin_error.txt](https://github.com/spdk/spdk/files/3775524/fio_plugin_error.txt)
[fio_plugin_result.txt](https://github.com/spdk/spdk/files/3775525/fio_plugin_result.txt)

**Comment by Comphix** [comment]
Thanks for reporting this.

Could you check whether you have enabled the below "enable_vmd" flag in the fio configuration?

struct spdk_fio_options {
	void	*pad;	/* off1 used in option descriptions may not be 0 */
	int	mem_size;
	int	shm_id;
	int	enable_sgl;
	int	sge_size;
	char	*hostnqn;
	int	pi_act;
	char	*pi_chk;
	int	md_per_io_size;
	int	apptag;
	int	apptag_mask;
	char	*digest_enable;
	int	enable_vmd;  <<<<<
};

**Comment by ufo19890607** [comment]
Hi, Comphix
fio_options->enable_vmd  is 0 when I print its value in spdk_fio_setup.
static int spdk_fio_setup(struct thread_data *td)
{
     ...
                if (fio_options->enable_vmd && spdk_vmd_init()) {
                        SPDK_ERRLOG("Failed to initialize VMD. Some NVMe devices can be unavailable.\n");
                }else {
                        SPDK_NOTICELOG("Initialize VMD successfully!fio_options->enable_vmd is %d\n", fio_options->enable_vmd);
                }
...
}

[root@TENCENT64 /home/ufo/kernel/test/fio_test]# LD_PRELOAD=/home/ufo/software/spdk-upstream/examples/nvme/fio_plugin/fio_plugin /home/ufo/software/fio-master/fio spdk_4krr 
testfile1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
...
fio-3.15
Starting 8 threads
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid207626 ]
EAL: No available hugepages reported in hugepages-2048kB
fio_plugin.c: 446:spdk_fio_setup: *NOTICE*: Initialize VMD successfully!fio_options->enable_vmd is 0
EAL: failed to parse device "pci:10000:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 554:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 627:spdk_nvme_probe: *ERROR*: Create probe context failed
fio_plugin.c: 497:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
testfile1: Laying out IO file (1 file / 2048000MiB)

**Comment by Comphix** [comment]
You can try to add below in the FIO configuration and have another try.

enable_vmd=1

Please let us know the result. Thanks, Gang

**Comment by optimistyzy** [comment]
@ufo19890607 Before running fio. Better to run the program under examples/nvme, such as examples/nvme/identify/identify  or examples/nvme/perf/perf to test whether you can identify the NVMe device through SPDK nvme driver under vmd mode. In the command line, you can add "-V" flag.

**Comment by ufo19890607** [comment]
Hi Ziye
You are right. NVME devices cannot be detected through SPDK driver under vmd.

[root@TENCENT64 /home/ufo/software/spdk-upstream/examples/nvme/identify]# ./identify -V
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid225954 ]
EAL: No available hugepages reported in hugepages-2048kB
No NVMe controllers found.

[root@TENCENT64 /home/ufo/software/spdk-upstream/examples/nvme/identify]# lspci |grep Non
10000:01:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:02:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:03:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:04:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
[root@TENCENT64 /home/ufo/software/spdk-upstream/examples/nvme/identify]# ./identify -r 10000:01:00:0
nvme.c: 883:spdk_nvme_transport_id_parse: *ERROR*: Unknown transport ID key '10000'
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid228149 ]
EAL: No available hugepages reported in hugepages-2048kB
No NVMe controllers found.

**Comment by ufo19890607** [comment]
> You can try to add below in the FIO configuration and have another try.
> 
> enable_vmd=1
> 
> Please let us know the result. Thanks, Gang

I've add 'enable_vmd=1' in configure of fio and rebuild it. 
root@TENCENT64 /home/ufo/kernel/test/fio_test]# LD_PRELOAD=/home/ufo/software/spdk-upstream/examples/nvme/fio_plugin/fio_plugin /home/ufo/software/fio-master/fio spdk_4krr 
testfile1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
...
fio-3.15
Starting 8 threads
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid228686 ]
EAL: No available hugepages reported in hugepages-2048kB
fio_plugin.c: 446:spdk_fio_setup: *NOTICE*: Initialize VMD successfully!fio_options->enable_vmd is 0
EAL: failed to parse device "pci:10000:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 554:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 627:spdk_nvme_probe: *ERROR*: Create probe context failed
fio_plugin.c: 497:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
testfile1: Laying out IO file (1 file / 2048000MiB)

**Comment by ufo19890607** [comment]
> @ufo19890607 Before running fio. Better to run the program under examples/nvme, such as examples/nvme/identify/identify or examples/nvme/perf/perf to test whether you can identify the NVMe device through SPDK nvme driver under vmd mode. In the command line, you can add "-V" flag.

[root@TENCENT64 /home/ufo/software/spdk-upstream/examples/nvme/identify]# ./identify -r 'trtype=PCIe traddr=10000:01:00.0'
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid5642 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: failed to parse device "pci:10000:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 554:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 670:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed

**Comment by wmalikow** [comment]
@ufo19890607 before you can use VMD in SPDK you need to add VMD devices to PCI_WHITELIST e. g. export PCI_WHITELIST="0000:5d:05.5 0000:d7:05.5". After that you need to call: sudo -E spdk/setup.h
To get address of NVMe behind VMD please use spdk/app/spdk_lspci/spdk_lspci - SPDK has different addressing schema than kernel lspci.

**Comment by ufo19890607** [comment]
@wmalikow 
1. disabled vmd
# ./spdk_lspci 
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid87554 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)

List of available PCI devices:
0000:3b:00.0 (8086 a54)
0000:3c:00.0 (8086 a54)
0000:86:00.0 (8086 a54)
0000:87:00.0 (8086 a54)

2. enabled vmd
# ./spdk_lspci 
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid16171 ]
EAL: No available hugepages reported in hugepages-2048kB

Lack of PCI devices available for SPDK!

List of available PCI devices:

**Comment by wmalikow** [comment]
@ufo19890607 could you please provide steps you are doing before call ./spdk_lspci in 
"enabled_vmd" case? (I'm assuming that you enable and disable vmd in BIOS)

**Comment by wmalikow** [comment]
Maybe I wasn't fully clear in previous comment - you need also set PCI_WHITELIST with VMD devices (from kernel lspci) and call "sudo -E spdk/setup.h" before you call ./spdk_lspci to get devices addresses **behind** VMD.

**Comment by ufo19890607** [comment]
@wmalikow All right. I got it.
1. compile dpdk
2. compile spdk
3. unbind kernel nvme driver and bind SPDK driver
cd <spdk_dir>/scripts
export PCI_WHITELIST="10000:01:00.0"
sh setup.sh
4. get NVME devices addresses
./spdk_lspci
[root]# ./spdk_lspci
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid34732 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)

List of available PCI devices:
10000:01:00.0 (8086 a54)

But fio_plugin still cannot run.

LD_PRELOAD=/home/ufo/software/spdk-upstream/examples/nvme/fio_plugin/fio_plugin /home/ufo/software/fio-master/fio spdk_4krr 
testfile1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
...
fio-3.15
Starting 8 threads
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid34520 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
fio_plugin.c: 446:spdk_fio_setup: *NOTICE*: Initialize VMD successfully!fio_options->enable_vmd is 0
EAL: failed to parse device "pci:10000:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 554:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 627:spdk_nvme_probe: *ERROR*: Create probe context failed
fio_plugin.c: 497:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed

**Comment by wmalikow** [comment]
ufo19890607 You should unbind **VMD** from kernel not a NVMe behind VMD e.g.
**5d:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)**

**Comment by ufo19890607** [comment]
> ufo19890607 You should unbind **VMD** from kernel not a NVMe behind VMD e.g.
> **5d:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)**

Could you please show the steps in detail?

**Comment by wmalikow** [comment]
I've just paste output from "lspci |grep 201d"

**Comment by ufo19890607** [comment]
@wmalikow 
[/home]# lspci |grep Non
10000:01:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:02:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:03:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:04:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54

so, traddr=10000:01:00.0. Am I right？

**Comment by wmalikow** [comment]
You are listing here devices behind VMD not **VMD itself** - could you please add your full lspci log?

**Comment by ufo19890607** [comment]
[lspci.log](https://github.com/spdk/spdk/files/3778038/lspci.log)

**Comment by wmalikow** [comment]
Please try this one:
PCI_WHITELIST="0000:3a:05.5"

**Comment by ufo19890607** [comment]
@wmalikow 
[root]# ./spdk_lspci 
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid35076 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)

List of available PCI devices:
3a0505:01:00.0 (8086 a54) (NVMe disk behind VMD) 
3a0505:03:00.0 (8086 a54) (NVMe disk behind VMD) 
3a0505:05:00.0 (8086 a54) (NVMe disk behind VMD) 
3a0505:07:00.0 (8086 a54) (NVMe disk behind VMD) 
0000:3a:05.5 (8086 201d) (VMD) 

I've tried to use all of addresses, but all failed.
./identify -r 'trtype=PCIe traddr=3a0505:01:00.0'
./identify -r 'trtype=PCIe traddr=3a0505:03:00.0'
./identify -r 'trtype=PCIe traddr=3a0505:05:00.0'
./identify -r 'trtype=PCIe traddr=3a0505:07:00.0'
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid36951 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
EAL: failed to parse device "pci:3a0505:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 554:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 670:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed

**Comment by wmalikow** [comment]
@ufo19890607 You need to add -V flag e. g. ./identify -r 'trtype=PCIe traddr=3a0505:01:00.0' -V

**Comment by ufo19890607** [comment]
> @ufo19890607 You need to add -V flag e. g. ./identify -r 'trtype=PCIe traddr=3a0505:01:00.0' -V

All right, thank you so much! The last question: How to set fio_options->enable_vmd ? I've add 'enable_vmd=1' in the configure of fio, but it does not work. So I just hack some code in fio_plugin.c.

**Comment by wmalikow** [comment]
You could refer to test/vmd/vmd.sh for fio example and test/vmd/config/config.fio for fio config.

**Comment by Comphix** [comment]
Assign to @wmalikow first. Thanks, Gang

**Comment by ufo19890607** [comment]
@wmalikow Thank you. I summarize all the steps for VMD enabled.
1. compile dpdk with EXTRA_CFLAGS=-fPIC
2. compile spdk with fio
3. set the whitelist for RAID bus controller
4. unbind kernel nvme driver and bind SPDK driver
5. invoke  spdk_lspci to get NVMe devices' addresses behind VMD.
6. make the spdk fio config referring to  test/vmd/config/config.fio

I really hope you update the fio_plugin README ASAP!  :）

**Comment by jimharris** [comment]
Hi @wmalikow - can you make sure these steps are added to our fio_plugin README?

I'm not sure about adding this step #1 to the README though.  We already build our DPDK submodule with -fPIC (see dpdkbuild/Makefile).  If someone wants to use their own version of DPDK, then -fPIC is required but we should note that in general for the fio_plugin - that step isn't specific to VMD.

**Comment by changpe1** [comment]
Hi @wmalikow for a short summary based on above conversation:
1.  we need add device to "PCI_WHITELIST" for the first step before running setup.sh
2.  we can only bind the VMD device to uio_generic_pci driver.
3.  we need to set "enable_vmd=1" in the fio configuration file.

Any other steps are required? If not I can add this to the fio README, more customers are asking for the test, it would be nice if you can add it. thanks.

**Comment by wmalikow** [comment]
Sure, I will add this to README.

**Comment by wmalikow** [comment]
@changpe1 - please refer to https://review.gerrithub.io/c/spdk/spdk/+/473526

**Comment by ufo19890607** [comment]
[SPDK FIO Plugin for VMD mode.pdf](https://github.com/spdk/spdk/files/4310166/SPDK.FIO.Plugin.for.VMD.mode.pdf)

Add a simple doc for fio_plugin under vmd mode
