### ISSUE TITLE
$testdir/startup/startup -t 1000000   per patch test failed on freebsd

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1010]
# Issue 
Starting SPDK v19.10-pre / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: startup -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 ]
EAL: WARNING! Base virtual address hint (0x100005000 != 0x80030a000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x10000b000 != 0x800338000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: WARNING! Base virtual address hint (0x15000c000 != 0x810000000) not respected!
EAL:    This may cause issues with mapping memory into secondary processes
EAL: TSC is not safe to use in SMP mode
EAL: TSC is not invariant
Too long time for initialization.
Initializing NVMe Controllers
Attaching to 0000:00:09.0
Attached to 0000:00:09.0
Initialization complete.
Time used:1002241.688     (us).
  05:38:36	# trap - ERR
  05:38:36	# print_backtrace
  05:38:36	# [[ ehxBE =~ e ]]
  05:38:36	# xtrace_disable
  05:38:36	# PREV_BASH_OPTS=ehxBE
  05:38:36	# set +x
========== Backtrace start: ==========

in test/nvme/nvme.sh:121 -> main()
     ...
   116 	timing_enter err_injection
   117 	$testdir/err_injection/err_injection
   118 	timing_exit err_injection
   119 	
   120 	timing_enter startup
=> 121 	$testdir/startup/startup -t 1000000
   122 	timing_exit startup
   123 	
   124 	timing_enter overhead
   125 	$testdir/overhead/overhead -s 4096 -t 1 -H
   126 	timing_exit overhead
     ...
Jenkins failure :
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47976/archive/freebsd_autotest/build.log

## Steps to Reproduce
per-patch test on Jenkins pool.

## Context (Environment including OS version, SPDK version, etc.)
commit efbcd259ac72f27fc88bea8e6f3bddb8d5acd405

**Comment by liang2yan** [comment]
the startup tool used a little more than 100ms in nvme_autotest and nvme_phy_autotest. But used more than 1s in freebsd_autotest. @jimharris , should we set a larger value for startup tool?

**Comment by jimharris** [comment]
Let's disable this test for FreeBSD.

**Comment by optimistyzy** [comment]
@jimharris @yidong0635  https://review.gerrithub.io/c/spdk/spdk/+/472669  A patch to disable the test.

**Comment by liang2yan** [comment]
@optimistyzy ,Sorry for the late reply. I already submitted patch to disable the test for FreeBSD.
https://review.gerrithub.io/c/spdk/spdk/+/472660

**Comment by optimistyzy** [comment]
@jimharris Please use liang's patch since he submitted early.

**Comment by yidong0635** [comment]
@jimharris @optimistyzy @liang2yan thanks , will close this issue after it be merged.
