### ISSUE TITLE
Recommendation about socket buffer size in iSCSI Target Getting Started Guide which gives negative effect on other applications

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1011]
Please use the issue tracker only for reporting suspected issues.

SPDK iSCSI Target Getting Started Guide recommends us to change /etc/sysctl.conf as follows:

        net.ipv4.tcp_rmem = 10000000 10000000 10000000
        net.ipv4.tcp_wmem = 10000000 10000000 10000000
        net.ipv4.tcp_mem = 10000000 10000000 10000000

This setting is global and give negative effects on other applications on the same OS.    Recently sendbuf size and recvbuf size have been set to 2MB automatically by socket.

Hence it looks that the above description is out of data and can be removed.

## Expected Behavior
SPDK should not change sensitive global parameters and should try to do local change.

## Current Behavior
The above change has given negative effects on other applications and system.

## Possible Solution
Remove the above description.
https://review.gerrithub.io/c/spdk/spdk.github.io/+/472511

**Comment by jimharris** [comment]
Bug scrub: closing this issue - there was a misunderstanding and the settings described apply to configuring the initiator, not the target
