### ISSUE TITLE
There is no UT for SPDK zone bdev library

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#1016]
## Expected Behavior
there is UT running in the CI for zone bdev library.
## Current Behavior
No UT for zone bdev library.
## Possible Solution
https://review.gerrithub.io/c/spdk/spdk/+/471600

## Steps to Reproduce
1. no UT codes in SPDK for zone library;
2. 
3.
4.

**Comment by yidong0635** [comment]
here : https://review.gerrithub.io/c/spdk/spdk/+/471600

**Comment by yidong0635** [comment]
waiting for +1.

**Comment by yidong0635** [comment]
patch merged.

**Comment by liang2yan** [comment]
close this issue since patch merged.
