### ISSUE TITLE
lvol intermittent failure - aio_bdev0 before and after test fails

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1017]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

See this error log:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48161/archive/lvol_autotest/build.log

More detailed info: 

```
ERROR: old and loaded lvol store is not the same
DIFF:
[{'uuid': '6b61a25a-e23f-4613-8a50-81f47f1e1ef6', 'name': 'lvs_test', 'base_bdev': 'aio_bdev0', 'total_data_clusters': 99, 'free_clusters': 54, 'block_size': 4096, 'cluster_size': 4194304}]
[]
ERROR: old and loaded lvol bdev list count is not equal
INFO: RPC COMMAND bdev_aio_delete
ERROR: RPC Command /usr/bin/python3 /var/jenkins/workspace/Lvol_tests/lvol_autotest/spdk/scripts/rpc.py bdev_aio_delete /var/jenkins/workspace/Lvol_tests/lvol_autotest/spdk/test/lvol/aio_bdev_0 execution failed:
Failed command output:
b'request:\n{\n  "method": "bdev_aio_delete",\n  "req_id": 1,\n  "name": "/var/jenkins/workspace/Lvol_tests/lvol_autotest/spdk/test/lvol/aio_bdev_0"\n}\nGot JSON-RPC error response\nresponse:\n{\n  "code": -19,\n  "message": "No such device"\n}\n'bdev.c:4109:spdk_bdev_init: *ERROR*: Bdev name:aio_bdev0 already exists
vhost: blobstore.c:2931: _spdk_bs_load_used_clusters_cpl: Assertion `ctx->mask->type == SPDK_MD_MASK_TYPE_USED_CLUSTERS' failed.
Traceback (most recent call last):
  File "/var/jenkins/workspace/Lvol_tests/lvol_autotest/spdk/scripts/rpc/client.py", line 40, in __init__
    self.sock.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
```

## Expected Behavior
The test should not fail.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48911.html

**Comment by jimharris** [comment]
Updating the title of this issue as well to make it easier for people to match it to intermittent failures.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49371.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49429.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49772.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50161.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50184.html

**Comment by optimistyzy** [comment]
@tomzawadzki  After I analyzed, it should be the issue of lvol. Before we see aio_bdev0 cannot create, we see:

"INFO: RPC COMMAND bdev_lvol_get_lvstores
ERROR: old and loaded lvol bdev list count is not equal"
It occurs the same situation. So could you assign this issue to lvol developer, which may be much better than assigning this issue to me.

**Comment by tomzawadzki** [comment]
Looking at the error:
```
ERROR: old and loaded lvol store is not the same
DIFF:
[{'uuid': '6b61a25a-e23f-4613-8a50-81f47f1e1ef6', 'name': 'lvs_test', 'base_bdev': 'aio_bdev0', 'total_data_clusters': 99, 'free_clusters': 54, 'block_size': 4096, 'cluster_size': 4194304}]
[]
ERROR: old and loaded lvol bdev list count is not equal
```
This looks like at least timing issue - lvs on aio_bdev0 have not finished loading by the time `bdev_lvol_get_lvstores` got called.
Meanwhile assert:
```
vhost: blobstore.c:2931: _spdk_bs_load_used_clusters_cpl: Assertion `ctx->mask->type == SPDK_MD_MASK_TYPE_USED_CLUSTERS' failed.
```
Was triggered in the middle of `bdev_aio_delete`.

Major changes to test scripts (python->bash rewrite) and blobstore improvements (including load/persist path) were done through out the months.
Logs from this issue are no longer available. It was reported last almost half year ago.

Due to the above closing this issue.
