### ISSUE TITLE
VPP autotest loses ssh connection in rpc_config.py

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1019]
This is intermittent failure on VPP job. When executing rpc_config.py test, the machine stops responding over VPP.
It is possible that this is general connectivity issue, or more likely the test themselves interact with network interface (Machine <-> Jenkins) that is not part of tests.

## Expected Behavior
Logs should be copied and available on AWS results.

## Current Behavior
When executing rpc_config.py with vpp variant, the logs stop. Either signifying failure or tests interrupting the connection between test machine and Jenkins.

## Steps to Reproduce
[vpp_issue.txt](https://github.com/spdk/spdk/files/3795028/vpp_issue.txt)
Above log is from Jenkins machine before SSH connection drops.
Making it impossible to copy build artifacts to AWS.
Link to build output on AWS (that is not much of use in this case):
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48440.html
## Context (Environment including OS version, SPDK version, etc.)

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49110.html

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49315.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49416.html

**Comment by jimharris** [comment]
This hasn't been seen for 2-3 weeks.  Logs indicate it's more like a CI related issue (similar to #1007) rather than VPP.
