### ISSUE TITLE
Deadlock in bdev remove during stress test?

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1020]
## Expected Behavior
I was hoping to get some help on further debugging an issue I'm seeing when stress testing a bedev removal. I'm not entirely sure that this is a SPDK issue, it may very well be something I'm doing. But maybe someone could provide some additional pointers what to look for.

I'm stress testing the following flow from 4 threads. Each thread runs a loop that does:
- Create a NVMF subsystem
- Create 2 bdevs to it (our own bdev)
- Add the 2 bdevs to the subsystem
- Delete the 2 bdevs (I'm not removing them from the subsystem but even if I do remove the namespaces before deleting the corresponding bdevs I'm hitting the issue).
- Delete the NVMF subsystem

Each of the above function is synchronous, which means I wait for the callback being called before advancing to the next step.
I have 4 threads that execute the above n times.

I'm not using the RPC calls. We are calling the spdk_bdev_register/unregister to add/remove a bdev and some of the functions from the NVMF subsystem (spdk_nvmf_subsystem_create etc).

We are not using reactors but our own threading env. I made sure to call the spdk_* functions on a "maintenance" spdk thread and invoke the actual functions via spdk_send_msg.

## Current Behavior
Now everything works fine most of the time but on our build server I sometimes see a deadlock in spdk_bdev_channel_destroy. The internal.mutex has already been taken by another thread and therefore deadlocks.

This is where the dead lock is happening
```
#0  0x00007f73e236589d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f73e235eb59 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x00007f73e382409a in spdk_bdev_channel_destroy (io_device=<optimized out>, ctx_buf=0x7f73cc0014c0) at bdev.c:2322
#3  0x00007f73e3c3d4a6 in _spdk_put_io_channel (arg=0x7f73cc001490) at /tmp/spdk/include/spdk/thread.h:478
#4  0x00007f73e3c3ce9d in _spdk_msg_queue_run_batch (max_msgs=<optimized out>, thread=0xf645c0) at thread.c:406
#5  spdk_thread_poll (thread=0xf645c0, max_msgs=<optimized out>, now=1957835811441932) at thread.c:462
...
5  spdk_thread_poll (thread=0xf645c0, max_msgs=<optimized out>, now=1957835811441932) at thread.c:462
462             msg_count = _spdk_msg_queue_run_batch(thread, max_msgs);
(gdb) p *thread
$6 = {io_channels = {tqh_first = 0xed8d30, tqh_last = 0x7f73cc001968}, tailq = {tqe_next = 0xf648c0, tqe_prev = 0xf642d0}, name = "spdk_nvmf_target_dp_thread_2", '\000' <repeats 228 times>,
  exit = false, cpumask = {str = '\000' <repeats 256 times>, cpus = '\377' <repeats 128 times>}, tsc_last = 1957835811421500, stats = {busy_tsc = 415780, idle_tsc = 155895838}, active_pollers = {
    tqh_first = 0xed8cc0, tqh_last = 0xed8cc0}, timer_pollers = {tqh_first = 0x0, tqh_last = 0xf64890}, messages = 0x2000018ffc00, msg_cache = {slh_first = 0x200002410d00}, msg_cache_count = 1023,
  ctx = 0xf648b8 "\001\003"}
(gdb) p *ch->bdev->internal.mutex
Attempt to take contents of a non-pointer value.
(gdb) p ch->bdev->internal.mutex
$7 = {__data = {__lock = 2, __count = 0, __owner = 14568, __nusers = 1, __kind = -1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
  __size = "\002\000\000\000\000\000\000\000\350\070\000\000\001\000\000\000\377\377\377\377", '\000' <repeats 19 times>, __align = 2}

(gdb) p *ch->bdev
$11 = {ctxt = 0x7f73bc0013f0, name = 0x7f73bc002d90 "38e0a89a-6085-42ec-9d83-fca539bcf7fd", aliases = {tqh_first = 0x0, tqh_last = 0x7f73bc001400}, product_name = 0x7f73e7df7bb0 "nvgrid vol",
  write_cache = 0, blocklen = 4096, blockcnt = 5, required_alignment = 0 '\000', split_on_optimal_io_boundary = false, optimal_io_boundary = 0, uuid = {u = {
      raw = "+\235\277\310\177\nB\230\236\334\327\070\363\235DM"}}, md_len = 0, md_interleave = false, dif_type = SPDK_DIF_DISABLE, dif_is_head_of_md = false, dif_check_flags = 0,
  module = 0x7f73e7dfd020 <nvgrid::bdev_vv_module_if>, fn_table = 0x7f73e7dfc360 <nvgrid::bdev_vv_fn_table>, internal = {qos = 0x0, qos_mod_in_progress = false, mutex = {__data = {__lock = 2,
        __count = 0, __owner = 14568, __nusers = 1, __kind = -1, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
      __size = "\002\000\000\000\000\000\000\000\350\070\000\000\001\000\000\000\377\377\377\377", '\000' <repeats 19 times>, __align = 2}, status = SPDK_BDEV_STATUS_REMOVING, claim_module = 0x0,
    unregister_cb = 0x7f73e7df3612 <nvgrid::<lambda(void*)>::<lambda(void*, int)>::_FUN(void *, int)>, unregister_ctx = 0x7ffc98545340, open_descs = {tqh_first = 0x0, tqh_last = 0x7f73bc0014c0}, link = {
      tqe_next = 0x7f73bc0015d0, tqe_prev = 0x7f73e3a2d090 <g_bdev_mgr+48>}, reset_in_progress = 0x0, qd_poller = 0x0, period = 0, temporary_queue_depth = 0, measured_queue_depth = 18446744073709551615,
    io_time = 0, weighted_io_time = 0, stat = {bytes_read = 0, num_read_ops = 0, bytes_written = 0, num_write_ops = 0, bytes_unmapped = 0, num_unmap_ops = 0, read_latency_ticks = 0,
      write_latency_ticks = 0, unmap_latency_ticks = 0, ticks_rate = 0}, histogram_enabled = false, histogram_in_progress = false}}
```
That thread is blocked and the owner thread of the mutex is 14568. Since the bdev.internal.status == SPDK_BDEV_STATUS_REMOVING, I assume that thread 14568 did claim the mutex via spdk_bdev_unregister/spdk_bdev_unregister_safe at some point.

 Here's the stack trace of 14568:
```
(gdb) t 3
[Switching to thread 3 (Thread 0x7f73dfacc700 (LWP 14568))]
#0  0x00007f73e174259b in sched_yield () from /lib64/libc.so.6
(gdb) p *tls_thread
$8 = {io_channels = {tqh_first = 0xed89a0, tqh_last = 0x7f73c8001968}, tailq = {tqe_next = 0xf645c0, tqe_prev = 0xf624a0}, name = "spdk_nvmf_target_dp_thread_1", '\000' <repeats 228 times>,
  exit = false, cpumask = {str = '\000' <repeats 256 times>, cpus = '\377' <repeats 128 times>}, tsc_last = 1958016140206381, stats = {busy_tsc = 436476, idle_tsc = 180485128667}, active_pollers = {
    tqh_first = 0xed8930, tqh_last = 0xed8930}, timer_pollers = {tqh_first = 0x0, tqh_last = 0xf64590}, messages = 0x2000019ffe00, msg_cache = {slh_first = 0x200002471480}, msg_cache_count = 1024,
  ctx = 0xf645b8 "\001\003"}
```
It's not doing anything at the moment.

I'm probably doing something wrong here but I was hoping to get some pointers where to look or how I possible could end up in a situation where the unregister is still in progress and spdk_bdev_channel_destroy is being called. 

I was also wondering how to correctly remove a subsystem that contain bdevs... Should I first remove the bdev and then the subsystem, or should I remove the namespace from the subsystem first and then the bdev followed by the subsystem?

## Context (Environment including OS version, SPDK version, etc.)
CentOS8, SPDK 19.07.1

**Comment by tomzawadzki** [comment]
[Bug scrub] @mhae Do you still need help with this issue ? Does it still occur ?

**Comment by mhae** [comment]
@tomzawadzki Let's close this for now. I still think it is an issue but I haven't had a chance to dig into further.
