### ISSUE TITLE
Intermittent error ./test/iscsi_tgt/filesystem/filesystem.sh

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1024]
# issue Link
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48520/archive/iscsi_autotest/build.log
hits at  ./test/iscsi_tgt/filesystem/filesystem.sh
 06:22:16	# local i=0
 06:22:16	# '[' '!' -e /dev/sdc1 ']'
 06:22:16	# '[' '!' -e /dev/sdc1 ']'
 06:22:16	# return 0
 06:22:16	# mount -o rw /dev/sdc1 /mnt/device
 06:22:16	# '[' -f /mnt/device/aaa ']'
 06:22:16	# echo 'File existed.'
File existed.
 06:22:16	# rm -rf /mnt/device/aaa
 06:22:16	# umount /mnt/device
 06:22:16	# for fstype in "ext4" "btrfs" "xfs"
 06:22:16	# '[' xfs == ext4 ']'
 06:22:16	# mkfs.xfs -f /dev/sdc1
**mkfs.xfs: cannot open /dev/sdc1: Device or resource busy**
  06:22:16	# trap - ERR
  06:22:16	# print_backtrace
  06:22:16	# [[ ehxBE =~ e ]]
  06:22:16	# xtrace_disable
  06:22:16	# PREV_BASH_OPTS=ehxBE
  06:22:16	# set +x
========== Backtrace start: ==========

in ./test/iscsi_tgt/filesystem/filesystem.sh:85 -> main()
     ...
   80  	for fstype in "ext4" "btrfs" "xfs"; do
   81  	
   82  		if [ "$fstype" == "ext4" ]; then
   83  			mkfs.${fstype} -F /dev/${dev}1
   84  		else
=> 85  			mkfs.${fstype} -f /dev/${dev}1
   86  		fi
   87  		mount /dev/${dev}1 /mnt/device
   88  		if [ $RUN_NIGHTLY -eq 1 ]; then
   89  			fio -filename=/mnt/device/test -direct=1 -iodepth 64 -thread=1 -invalidate=1 -rw=randwrite -ioengine=libaio -bs=4k \
   90  				-size=1024M -name=job0
     ...

========== Backtrace end ==========
  06:22:16	# xtrace_enable
  06:22:16	# return 0
 06:22:16	# remove_backends
 06:22:16	# echo 'INFO: Removing lvol bdev'
INFO: Removing lvol bdev
 06:22:16	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py bdev_lvol_delete lvs_0/lbd_0
**iscsi_tgt: bdev.c:4521: spdk_bdev_close: Assertion `desc->thread == spdk_get_thread()' failed.
Connection closed with partial response:**

  06:22:17	# trap - ERR
  06:22:17	# print_backtrace
  06:22:17	# [[ ehxBE =~ e ]]
  06:22:17	# xtrace_disable
  06:22:17	# PREV_BASH_OPTS=ehxBE
  06:22:17	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/test/common/autotest_common.sh:565 -> run_test()
 
in ./test/iscsi_tgt/iscsi_tgt.sh:34 -> main()
     ...
   29  		# calsoft doesn't handle TCP stream properly and fails decoding iSCSI
   30  		# requests when are divided by TCP segmentation. This is very common
   31  		# situation for VPP and causes that calsoft.sh never PASS.
   32  		run_test suite ./test/iscsi_tgt/calsoft/calsoft.sh
   33  	fi
=> 34  	run_test suite ./test/iscsi_tgt/filesystem/filesystem.sh

**Comment by shuhei-matsumoto** [comment]
Hi @yidong0635 Thank you for filing this issue. I posted a patch to fix this issue https://review.gerrithub.io/c/spdk/spdk/+/473002.

**Comment by jimharris** [comment]
Hi @shuhei-matsumoto - I think the failure originally stems from this part of the log:

06:22:16	# mkfs.xfs -f /dev/sdc1
mkfs.xfs: cannot open /dev/sdc1: Device or resource busy
06:22:16	# trap - ERR

This triggers the trap which calls remove_backends and deletes the lvol which causes the problem you're seeing.

So first, I think your patch is correct.  We should merge it.  But I see at least two other problems here:

1) The trap calls remove_backends *before* iscsicleanup.  This is opposite of the normal cleanup path.  This actually helps trigger the bug that you fixed here.  We should probably fix the trap in this script to call iscsicleanup before remove_backends.
2) Maybe we need a test that specifically removes lvols while the iscsi initiator is connected.  That obviously found one problem here - maybe it finds some more.
3) Why is /dev/sdc1 busy in the first place?  Is there a race condition between umount (line 135) and the next mkfs (line 85)?

**Comment by shuhei-matsumoto** [comment]
Thank you @jimharris for #1 I submitted a patch to fix ordering first. https://review.gerrithub.io/c/spdk/spdk/+/473156
For #2 LVOL hotplug + iSCSI target test is nice to have but I feel it will be better to fix the current hotplug issue first.
For #3, I will investigate this too.

**Comment by tomzawadzki** [comment]
Bug scrub: This failure has not occurred for some time. There were some hotplug related changes merged since and no new reports. Closing this one.
