### ISSUE TITLE
nvme: failed connection to discovery ctrlr results in segfault

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1029]
lib/nvme/nvme_fabric.c - nvme_fabric_ctrlr_scan() - commit a1ce725c0a

It tries to set state on the discovery_ctrlr->adminq before checking if the discovery_ctrlr is !NULL.

Patch will be up shortly. This needs to go into a 19.10.1.

**Comment by jimharris** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/473237

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48732.html

**Comment by Seth5141** [comment]
Thanks for the report @wawryk. It looks like this is another example of #1005. If you rebase, you won't hit it.

**Comment by Seth5141** [comment]
Test for connecting to a non-existent discovery controller. https://review.gerrithub.io/c/spdk/spdk/+/474153

**Comment by jimharris** [comment]
Patch was merged.
