### ISSUE TITLE
NvmeF RDMA avoid memory copy

### ISSUE THREAD

**Issue by PepperJo** [spdk/spdk#103]
To my understanding, in the current RDMA NVMeF implementation data operations require a copy (cf. `nvme_rdma_copy_mem` in https://github.com/spdk/spdk/blob/master/lib/nvme/nvme_rdma.c). My suggestion is to enhance the API with either:

1. Function to allocate memory with a specific controller -> memory is registered during allocation
2. Function to (de-)register already allocated memory with a specific controller
3. Register buffers on the fly in read/write functions and cache mrs

to allow buffers to be directly used on data operations.

**Comment by benlwalker** [comment]
You are correct for our NVMe-oF initiator. We're looking to fix this for our next release using a pre-registration scheme. Our NVMe-oF target already operates with no data copies - it's just the initiator that needs to change.

The first draft of the NVMe-oF initiator used strategy 3 above where we register the buffers on the fly. However, this is actually much slower than doing the memcpy into a pre-registered region (we benchmarked it).

**Comment by PepperJo** [comment]
Thanks for the quick answer. Great to hear you are working on it.
