### ISSUE TITLE
SPDK Nightly Testing Fails due to unable to find dpdk-2019_11_04.tar

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#1031]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Looks like our recent nightly testing all fails with same reason. Looking at below example:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/851/archive/RBD_autotest_nightly/build.log

13:26:20	$ ocf_tarball=ocf-2019_11_04.tar
 13:26:20	$ find . -iname 'spdk-*.tar* dpdk-*.tar* ipsec-*.tar* isal-*.tar*' -delete
 13:26:20	$ git archive 'HEAD^{tree}' --prefix=spdk-2019_11_04/ -o spdk-2019_11_04.tar
  13:26:20	$ mktemp -d
 13:26:20	$ tmpdir=/tmp/tmp.7wQEt9GwwX
 13:26:20	$ echo tmpdir=/tmp/tmp.7wQEt9GwwX
tmpdir=/tmp/tmp.7wQEt9GwwX
 13:26:20	$ tar -C /tmp/tmp.7wQEt9GwwX -xf spdk-2019_11_04.tar
 13:26:20	$ '[' -z '' ']'
 13:26:20	$ cd dpdk
 13:26:20	$ git archive 'HEAD^{tree}' --prefix=dpdk/ -o ../dpdk-2019_11_04.tar
 13:26:21	$ tar -C /tmp/tmp.7wQEt9GwwX/spdk-2019_11_04 -xf dpdk-2019_11_04.tar
tar: dpdk-2019_11_04.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Looks like the dpdk folder is not found. Do we have some configuration change?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomzawadzki** [comment]
Hi @Comphix, this is result of patch that was merged recently. I've submitted a revert for it, since it seemed like best course of actions. Please see following patch for more in-depth explanation:
https://review.gerrithub.io/c/spdk/spdk/+/473220

**Comment by Comphix** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/473220 has been merged. Close it issue first. Looking at the recent nightly testing, looks like other failures instead of this one.
