### ISSUE TITLE
vpp: iscsi_tgt intermittently segfaults when starting qos.sh test

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1034]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48738/archive/vpp_autotest/build.log

The backtrace doesn't show anything useful.

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48738.html

**Comment by jimharris** [comment]
This hasn't been seen again in three weeks.
