### ISSUE TITLE
(iscsi hotplug) task->pdu is NULL at spdk_iscsi_task_cpl in iSCSI target

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1036]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/48924/archive/iscsi_autotest/failed_test.log

This error may show my patch series on gerrithub have bugs but I add for now

**Comment by jimharris** [comment]
Hi Shuhei,

This appears due to iSCSI hot plug.  Should we track it in #1018 instead?  It's not clear to me yet that all of this intermittent iSCSI hot plug failures aren't due to the same underlying issue.

-Jim

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris 

Why I add this as a separate issue was that I found two bugs and a no-bug but should be fixed after seeing this issue. I added this from my iphone last night and so made you confused. Sorry for that.

I found that we had not expected that any secondary read I/O gets completion before primary read I/O gets completion for large read I/O split case. I'm not sure the bug is related with other hotplug issues we are observing yet, the bug should be fixed. I will submit three patches from now.

-Shuhei

**Comment by shuhei-matsumoto** [comment]
The issue is that when processing response PDU, we have expected iSCSI task holds request PDU and accessed it. However request PDU is not held in iSCSI task and freed immediately before submitting iSCSI task to SCSI layer. So this is not the issue only for hotplug. You couldn't get any information though.

**Comment by shuhei-matsumoto** [comment]
Sorry I was wrong. Ziye corrected me offline. I will read the log and code more.

**Comment by shuhei-matsumoto** [comment]
I was wrong. Ziye corrected me, so please forget the above comment. By the way, this was caused on iSCSI target + POSIX.

**Comment by shuhei-matsumoto** [comment]
I could verify https://review.gerrithub.io/c/spdk/spdk/+/473586 is the fix to the root cause.

I reproduced the LUN hotplug timeout issue very easily locally by re-enabling https://review.gerrithub.io/c/spdk/spdk/+/467212.

Due to the bug we had to defer notification LUN hotplug from SCSI layer to iSCSI layer as late as possible but there is no need to do now.

This idea is much owe to Ziye and I have more to do. So I will refine add patches with adding credit to Ziye.

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49191.html

**Comment by shuhei-matsumoto** [comment]
Sorry local tests were OK but it didn't work in test pool. I will continue investigation.

**Comment by jimharris** [comment]
Patches merged.
