### ISSUE TITLE
Unittest fail

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1037]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

unittest_autotests should pass

## Current Behavior

test fail:

```
vmd.c:747:29: warning: Access to field 'slot_control' results in a dereference of a null pointer (loaded from field 'pcie_cap')
        dev->cached_slot_control = dev->pcie_cap->slot_control;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
vmd.c:833:11: warning: Dereference of null pointer
                                      new_dev->pcie_cap->express_cap_register.bit_field.slot_implemented);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sys_sgci/spdk/include/spdk_internal/log.h:84:59: note: expanded from macro 'SPDK_DEBUGLOG'
                        spdk_log(SPDK_LOG_DEBUG, __FILE__, __LINE__, __func__, __VA_ARGS__);    \

```
## Steps to Reproduce

1. Run unittest_autotest on Fedora29

## Context (Environment including OS version, SPDK version, etc.)

OS: Fedora29
Kernel: 5.3.6-100.fc29.x86_64 
GCC: gcc version 8.3.1 20190223 (Red Hat 8.3.1-2) (GCC)
Last commit: 3ea70d336aaf73983274bd730c7f3198303ed5c6

**Comment by ksztyber** [comment]
I think one of the already merged patches should have fixed this. Could you check if it's still reproducible on af4e2a32778b44237520feb1a15bbf39a61562cf?

**Comment by wawryk** [comment]
It works, thanks.
