### ISSUE TITLE
Possible nvmf tgt issue in spdk 19.10

### ISSUE THREAD

**Issue by clicx** [spdk/spdk#1039]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior
work normally.

## Current Behavior
Happen issue when connecting:
/root/spdk/lib/nvmf/rdma.c:1032:spdk_nvmf_rdma_qpair_initialize: *ERROR*: rdma_create_qp failed: errno 22: Invalid argument
/root/spdk/lib/nvmf/rdma.c:3462:spdk_nvmf_rdma_poll_group_add: *ERROR*: Failed to initialize nvmf_rdma_qpair with qpair=0x16a5ba0

## Steps to Reproduce

1. upgrade to spdk 19.10 (19.07 no this issue)
2. create nvmf tgt with multiple subsystem (2), and use multiple cores (8)
3. use spdk perf to test, using multiple cores (core mask = 0xfff).
4.happen the above issue.

**Comment by karlatec** [comment]
Hey @clicx 
Can you post more details? How many hugepages do you have allocated?
Is this done on a loopback connection or are these two physical servers?

**Comment by clicx** [comment]
I set nr_hugepage to 40000
I'm using two physical servers with 2 RDMA NICs and several NVMes
The above is one of its behaviors, I will check more as well.

I was using 19.07 to test server throughput, but I can't get nvme raid0 to work, after upgrade to 19.10, I can get raid0 work, however I got new nvme/nvmf issues, here is more:
nvme_pcie.c:1053:nvme_pcie_qpair_construct: *ERROR*: alloc qpair_cmd failed
nvme_ctrlr.c: 363:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_create_io_qpair() failed
bdev_raid.c: 121:raid_bdev_create_cb: *ERROR*: Unable to create io channel for base bdev

And Core Dump after ctrl+c

**Comment by Comphix** [comment]
@clicx , from below error, looks like it is failed to create NVMe IO qpair

nvme_pcie.c:1053:nvme_pcie_qpair_construct: ERROR: alloc qpair_cmd failed
nvme_ctrlr.c: 363:spdk_nvme_ctrlr_alloc_io_qpair: ERROR: nvme_transport_ctrlr_create_io_qpair() failed

What type of NVMe SSDs are you using?

Also, could you try to assign 0xf or 0xff (<= 8 cores used for the nvmf_tgt) for the nvme perf and see what's the result?

create nvmf tgt with multiple subsystem (2), and use multiple cores (8) <<<<
use spdk perf to test, using multiple cores (core mask = 0xfff)  <<<<

Thanks, Gang

**Comment by clicx** [comment]
NVMe disk is P4610
There should be multiple issues, I still need more time to check all conditions, since I found some issues are randomly, a certain issue on NVMe are:
EAL:   using IOMMU type 1 (Type 1)
nvme_pcie.c: 484:nvme_pcie_ctrlr_map_cmb: *ERROR*: get registers failed
nvme_pcie.c: 853:nvme_pcie_ctrlr_construct: *ERROR*: get_cap() failed
nvme.c: 428:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:31:00.0
error in 4 (of 8) disks 
It should related to the iommu, if I disable iommu, will not happen this issue.

as for nvmf_tgt, now randomly crash on line 2608: TAILQ_INSERT_TAIL(&sgroup->queued, req, link); of function spdk_nvmf_request_exec
sgroup:{ns_info = 0x0, num_ns = 0, io_outstanding = 0, cb_fn = 0x0, cb_arg = 0x0, state = SPDK_NVMF_SUBSYSTEM_INACTIVE, queued = {tqh_first = 0x0, tqh_last = 0x0}}

I found the function is running in polling (no locking), while sgroup is touched from ctrlr, is it a reason?

**Comment by Comphix** [comment]
For this issue:

nvme_pcie.c: 484:nvme_pcie_ctrlr_map_cmb: ERROR: get registers failed
nvme_pcie.c: 853:nvme_pcie_ctrlr_construct: ERROR: get_cap() failed
nvme.c: 428:nvme_ctrlr_probe: ERROR: Failed to construct NVMe controller for SSD: 0000:31:00.0
error in 4 (of 8) disks
It should related to the iommu, if I disable iommu, will not happen this issue.

Looks like there are 8 P4610s here, is this error only happened on 0000:31:00.0 this SSD?

Also please file a new issue for the nvmf_tgt crash. It's better to only track one problem in one issue.

Thanks, Gang

**Comment by clicx** [comment]
Will fail 4 disks (total disks are 8), and those 4 disks are on same numa (31,32,33,34), while other 4 disks on another numa have no problem.
OK for nvmf_tgt issue.

**Comment by Comphix** [comment]
I've using the similar configuration (nvmf_tgt with 8 cores + 2 subsystems and perf with 0xFFF cores) with latest SPDK (master) code.

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.100.8:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MN SPDK_Controller1
  Namespace Malloc0
  Namespace Malloc1
  Namespace Nvme0n1

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode2
  Listen RDMA 192.168.100.8:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  MN SPDK_Controller2
  Namespace Malloc2
  Namespace Malloc3
  Namespace Nvme1n1

Two NVMe SSD used, looks like this issue is not seen.

Could you please give more detailed testing configuration here? 

Thanks, Gang

**Comment by clicx** [comment]
I was trying to setup raid0 by using 8 disks (same model), actually the first 4 disks can't used by spdk in anyway except disable iommu, just run the identity app:

./examples/nvme/identify/identify -r "trtype:PCIe traddr:0000:31:00.0"
Starting SPDK v20.01-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid34404 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)
nvme_pcie.c: 484:nvme_pcie_ctrlr_map_cmb: *ERROR*: get registers failed
nvme_pcie.c: 853:nvme_pcie_ctrlr_construct: *ERROR*: get_cap() failed
nvme.c: 428:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:31:00.0
EAL: Driver cannot attach the device (0000:31:00.0)
EAL: Failed to attach device on primary process
nvme.c: 561:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 677:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed

**Comment by optimistyzy** [comment]
@clicx For the identify usage.  If you turn on IOMMU. It means that for every NVMe disk you cannot identify? Or you can only identify the NVMe SSD in the same Numa node?

**Comment by optimistyzy** [comment]
In SPDK new code (a7b6702d6f5211099c7102b98db845d6965bcc33). When starting an SPDK app, we have to check:

#if defined(__x86_64__)
	/* DPDK by default guesses that it should be using iova-mode=va so that it can
	 * support running as an unprivileged user. However, some systems (especially
	 * virtual machines) don't have an IOMMU capable of handling the full virtual
	 * address space and DPDK doesn't currently catch that. Add a check in SPDK
	 * and force iova-mode=pa here. */
	if (spdk_get_iommu_width() < SPDK_IOMMU_VA_REQUIRED_WIDTH) {
		args = spdk_push_arg(args, &argcount, _sprintf_alloc("--iova-mode=pa"));
		if (args == NULL) {
			return -1;
		}
	}

And all the app starts with --iova-mode  choice.  It can be --iova-mode=pa or --iova-mode=va, which is related with IOMMU. So if IOMMU is on, it seems that --iova-mode parameter is not passed to dpdk. So I am doubt, if you temporarily modify the iommut code in ./lib/env_dpdk/init.c. And let it a pass --iova-mode=pa or --iova-mode=va, and see what will happen?

**Comment by jimharris** [comment]
Closing issue.  @clicx please reopen if you are able to try Ziye's suggestion and still see problems.
