### ISSUE TITLE
identify failed during hotplug running

### ISSUE THREAD

**Issue by uchida2016** [spdk/spdk#104]
identify sample program failed when I ran it during hotplug sample program running.

Error message:
nvme_pcie.c: 531:nvme_pcie_ctrlr_allocate_bars: ***ERROR*** nvme_pcicfg_map_bar failed with rc 0 or bar (nil)
nvme.c: 313:nvme_ctrlr_probe: ***ERROR*** Failed to construct NVMe controller
EAL: Error - exiting with code: 1
  Cause: Requested device 0000:05:00.0 cannot be used

How to reproduce:
1. Run hotplug
\# ./example/nvme/hotplug/hotplug -t 600

2. Remove a NVMe device
\# udevadm trigger -c remove -s uio /sys/devices/pci0000:00/0000:00:03.2/0000:05:00.0/uio/uio3

3. Add the removed NVMe device
\# udevadm trigger -c add -s uio /sys/devices/pci0000:00/0000:00:03.2/0000:05:00.0/uio/uio3

4. Just after step 3, run identify
\# ./example/identify/identify

I think this happens when the secondary process pick up an add event before the primary process.

**Comment by optimistyzy** [comment]
Hi @uchida2016,  NVMe hotplug for multiple processes cases are still in validation, we will check this usage cases.

**Comment by darsto** [comment]
@optimistyzy It's been 2 years. @optimistyzy could you give us an update? :)

Anyway, it looks like 2 applications are racing to attach an NVMe, in which case it'd be expected that one of those applications fails. I'm closing this issue.
