### ISSUE TITLE
Performance question: create lvol store command cost more than 5 senconds

### ISSUE THREAD

**Issue by shibingxun** [spdk/spdk#1040]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Current Behavior

When using rpc.py script to create a volume store, the "create lvol store" command need more than 5 seconds to give out the response. We tried several systems, the same behavior.  
The SPDK version we are using is v19.04.1. The older version as v18.01 seems much better.

## Steps to Reproduce

1. Initial the environment:
./setup.sh
./app/nvmf_tgt/nvmf_tgt -i 1 &
./rpc.py nvmf_create_transport -t RDMA -u 8192 -p4 -c 0

./rpc.py construct_nvme_bdev -b NVMe1 -t PCIe -a 0000:08:00.0
./rpc.py construct_nvme_bdev -b NVMe2 -t PCIe -a 0000:0d:00.0
./rpc.py construct_nvme_bdev -b NVMe3 -t PCIe -a 0000:12:00.0
./rpc.py construct_nvme_bdev -b NVMe4 -t PCIe -a 0000:17:00.0
2. Create RAID bdev
./rpc.py construct_raid_bdev -n raid_0 -r 0 -z 64  -b "NVMe2n1 NVMe1n1"
3. Create volume store   ---> It cost more than 5s to response
./rpc.py construct_lvol_store raid_0 lvs0

## Context (Environment including OS version, SPDK version, etc.)

SPDK version  v19.04.1

**Comment by tomzawadzki** [comment]
Hi @shibingxun When lvol store is being created some portion of time is spent on unmap of the space on device that will be used for storage of data. Time it takes to complete can possibly depend on device and its size. I believe this was the case with v18.01 too, so it should not have made any difference.

Unmap is default behavior when creating lvol store. This can be changed by adding `--clear-method none` argument to not perform any operation on data region of lvol store.
Just to narrow down what takes the time when issuing this command, can you please try if using this argument speeds up the RPC completion ?

**Comment by shibingxun** [comment]
@tomzawadzki  Hi Tomasz, thank you very much for your suggestion. With this parameter added, it's much better now.
Without the "--clear-method none" parameter, the time is nearly 5s:
[root@localhost scripts]# time ./rpc.py construct_lvol_store raid_1 lvs1
7471d2dc-f15e-4a3e-a06c-27bdf8128c24

real    0m4.681s
user    0m0.110s
sys     0m0.009s

After the parameter added,  the time is shortened to 1.7s:
[root@localhost scripts]# time ./rpc.py construct_lvol_store --clear-method none raid_1 lvs1
bf4dc129-457e-4802-a1b8-6d26404576d0

real    0m1.690s
user    0m0.102s
sys     0m0.019s

While for other commands, like destory volume store, command response  is much faster.

[root@localhost scripts]# time ./rpc.py destroy_lvol_store -l lvs1

real    0m0.125s
user    0m0.106s
sys     0m0.013s

[root@localhost scripts]# time ./rpc.py destroy_raid_bdev raid_1

real    0m0.126s
user    0m0.107s
sys     0m0.013s

**Comment by Comphix** [comment]
@shibingxun , is the 1.7s lvol creation acceptable although comparing to other operation, it still takes a little more time? Thanks, Gang

**Comment by shibingxun** [comment]
@Comphix  Hi Gang, this is much better.  We can accept this response time. Just one more question, is there any reason the "construct_lvol_store" command cost more time than other commands?

**Comment by jimharris** [comment]
Bug scrub: Closing this issue since questions were answered.  Please feel free to ask more questions on this thread though.
