### ISSUE TITLE
EAL:   Expecting 'PA' IOVA mode but current mode is 'VA', not initializing

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1042]
Upgrading to 19.10 is breaking my app that is using the vfio-pci driver and hotplug. I saw that this issue was reported on the DPDK issue site but it wasn't clear to me what the workaround/fix is.

```
Starting SPDK v19.10 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: sea-eagle-nvmf-target --no-shconf -c 0x03 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid25818 ]
EAL: VFIO support initialized
app.c: 639:spdk_app_start: *NOTICE*: Total cores available: 2
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
tcp.c: 537:spdk_nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
rpc.c: 122:spdk_jsonrpc_handler: *WARNING*: RPC method set_bdev_nvme_hotplug is deprecated.  Use bdev_nvme_set_hotplug instead.
rpc.c: 122:spdk_jsonrpc_handler: *WARNING*: RPC method nvmf_subsystem_create is deprecated.  Use nvmf_create_subsystem instead.
EAL:   Expecting 'PA' IOVA mode but current mode is 'VA', not initializing
EAL: Requested device 0000:00:0e.0 cannot be used
EAL:   Expecting 'PA' IOVA mode but current mode is 'VA', not initializing
...
```

Same result with the identify example app:
```
[vagrant@nvgrid-template spdk]$ sudo examples/nvme/identify/identify -r 'trtype:PCIe traddr:0000:00:0e.0'
Starting SPDK v19.10 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid26405 ]
EAL: VFIO support initialized
EAL:   Expecting 'PA' IOVA mode but current mode is 'VA', not initializing
EAL: Driver cannot attach the device (0000:00:0e.0)
EAL: Failed to attach device on primary process
nvme.c: 561:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 677:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed
```
## Steps to Reproduce
- Enable VFIO by echoing 1 to ``/sys/module/vfio/parameters/enable_unsafe_noiommu_mode``
- Use vfio-pci driver for NVMe device

**Note, hacking in ```--iova-mode=pa``` to the EAL command line avoids this issue but I don't know what the impact is and why we don't have an option on the SPDK command line to pass this in.**

## Context (Environment including OS version, SPDK version, etc.)
SPDK 19.10, CentOs8, VirtualBox with emulated NVMe drive.

**Comment by jimharris** [comment]
The short answer is that we didn't have a need for this command line option until now.  :-)

Note that https://github.com/spdk/spdk/issues/1012 is a different issue, but also drives the requirement for enabling this option from the command line.

We should probably also add some noimmu tests to our CI.

Adding "Bug Scrub" label so that we discuss at next meeting.

**Comment by mhae** [comment]
@jimharris , thanks. I actually was referring to https://www.mail-archive.com/dev@dpdk.org/msg139852.html (should have added this to the issue report). 

Note, we're using the vfio-pci driver since the uio driver is broken in CentOS8 as you have reported long time ago )-:

**Comment by Comphix** [comment]
For this, please check below article

https://software.intel.com/en-us/articles/memory-in-dpdk-part-2-deep-dive-into-iova

There are much description there about IOVA. Application could assign the iova-mode as the explicit parameter.

**Comment by jimharris** [comment]
Bug scrub: We can add some heuristics to SPDK to get this right for now.  Will also push patches to DPDK.  @benlwalker will drive this forward.

**Comment by jimharris** [comment]
Marking as 3rd party issue since this is a DPDK regression.

**Comment by tomzawadzki** [comment]
Bug scrub: @benlwalker Will create patch for spdk/dpdk to improve auto detection of the mode. Along with SPDK change to pass the option to DPDK init.

**Comment by benlwalker** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/475148

**Comment by tomzawadzki** [comment]
@benlwalker patches were merged ending in https://review.gerrithub.io/c/spdk/spdk/+/477362

@mhae Can you please verify this resolved your issue ?

**Comment by mhae** [comment]
Yes, the issue has been resolved. Actually one of the patches for 19.10.1 fixed it. But I just checked out master and didn't see any issues running the nvmf target app.
