### ISSUE TITLE
Intermitten failure: Build timeout but test not started

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1045]
Log to this failure:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49288/archive/centos7_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49288.html

**Comment by jimharris** [comment]
Bug scrub: this looks like a duplicate of #1007
