### ISSUE TITLE
Intermittent RBD tests failure - Partitioning /dev/loop200

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1046]
Log with this failure:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49272/archive/RBD_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49272.html

**Comment by optimistyzy** [comment]
I submitted a patch to address this issue: https://review.gerrithub.io/c/spdk/spdk/+/473910

**Comment by yidong0635** [comment]
@optimistyzy @pawelkax 
have two questions:
Can we remove "SPDK CI Jenkin +1" and try many times to check this patch?
What about adding "partprobe" after "parted -s" ? I'm not sure about this.

**Comment by optimistyzy** [comment]
@yidong0635 I think that  we can let the pool to test. And currently I do think that partprobe is needed.

**Comment by yidong0635** [comment]
@optimistyzy ,thanks, follow with you, I will do some manual tests too.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Donaim. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49849.html

**Comment by yidong0635** [comment]
@Donaim , form this log  , it need  to to rebase , it has been resolved for a long time I think.

**Comment by Donaim** [comment]
@yidong0635 ok, sorry for false positive then :) and thank you

**Comment by tomzawadzki** [comment]
Patch https://review.gerrithub.io/c/spdk/spdk/+/473910 is merged. This issue can be closed.
