### ISSUE TITLE
Intermittent NVMe-TCP autotest failure: Always timeout during some specific period of time.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1049]
I moved to this from https://github.com/spdk/spdk/issues/1047.

As long as I compared the log between success and failure and also checked the elapsed time, the NVMe-TCP auto test always takes close to 10 minutes, and very close to timeout.

We have to reduce the contents or reduce test duration or move some tests to nightly.

## Expected Behavior
The test should complete in less than 8 minutes.

## Current Behavior
This run needed 9 minutes and 45 seconds even for success case.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49429.html

This  run needed 10 minutes and resulted in success.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49438.html

This run almost finished but timeout was earlier.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49439.html

## Possible Solution
Reduce the number of tests or reduce duration of tests or move some tests to nightly.

## Steps to Reproduce
Test pool issue.

## Context (Environment including OS version, SPDK version, etc.)
Latest SPDK master.

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris I re-opened the issue as an new issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49445.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49446.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49448.html

**Comment by shuhei-matsumoto** [comment]
Other instances
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49452.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49451.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49450.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49449.html

But RBD_autotest and LVOL_autotest succeed even if they take more than 10 minutes, e.g. 11, 12 minutes.

What is the difference between NVMe-TCP autotest and RBD or LVOL auto tests?

@karlatec @Seth5141 
Will you help us by your knowledge and insight?

**Comment by shuhei-matsumoto** [comment]
Now everything is very fine, and NVMe-TCP autotest complets for about 8 minutes. So there is solid failure in NVMe-TCP autotest only during some period of time.
I glanced SPDK Jenkins test pool status but I couldn't find anything noticeable.

**Comment by optimistyzy** [comment]
@shuhei-matsumoto This is interesting..

**Comment by Seth5141** [comment]
@shuhei-matsumoto The timeout values for each one of the tests are individually configurable through the Jenkins UI. Perhaps we need to increase the timeout on the TCP test, or trim some of the fat there. One reason that the TCP tests take longer is that they are run from VMs that don't share the same NFS as teh other ones so they have to individually copy down the source.

**Comment by jimharris** [comment]
Bug scrub: The TCP autotest VMs are located in Chandler (rest are in Poland) - the git clone took much longer for these cases which seems due to some kind of intermittent network slowness in Chandler over this 1 hour time period.  Closing as this hasn't been seen since.
