### ISSUE TITLE
SPDK NvmeOF failed to connect to target nvme device 

### ISSUE THREAD

**Issue by joyantamishu** [spdk/spdk#1050]
Hello,

I have nvmeof set up in two machines. The target side (192.168.10.10) has Ubuntu 18.04 with kernel version 5.0.0, and initiator (192.168.11.9) has Ubuntu 16.04 with kernel version 4.10. At the target end, I created one nvme subsystem and add listener to it using SPDK rpc methods. The subsystem was created successfully as when I run nvme discover the initiator can identify the remote (target) nvme device. After connecting to the target nvme device, _nvme list_ command at the initiator side shows the following:

[nvme list]

> /dev/nvme0n1     Z77S11N8TY5T         KXG50ZNV256G NVMe TOSHIBA 256GB          1         256.06  GB / 256.06  GB    512   B +  0 B   AADA4102
> /dev/nvme1n1     SPDK00000000000001   SPDK_Controller1                         1         536.87  MB / 536.87  MB    512   B +  0 B   19.10

/dev/nvme1n1 is the target nvme device. But when I run scripts/setup.sh command, it says 

[scripts/setup.sh]

> _Active mountpoints on /dev/nvme0n1, so not binding PCI dev._

It's true that I have active mounting on /dev/nvme0n1, but I don't know, why SPDK doesn't try to bind with the /dev/nvme1n1, which is actually the target nvme device. I also run examples/nvme/identify/identify, and it shows 

[identify]

> _No NVMe controllers found._

As a part of troubleshooting I also run the SPDK perf program at the initiator side. And it shows me the following:
[perf]

> _sudo ./perf -q 128 -o 4096 -w randread -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.10.10 trsvcid:4420' -t 30_
> _EAL: No available hugepages reported in hugepages-1048576kB
> Initializing NVMe Controllers
> libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
> libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
> libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
> nvme_rdma.c: 807:nvme_rdma_qpair_connect: *ERROR*: rdma_create_event_channel() failed
> nvme_rdma.c:1485:nvme_rdma_ctrlr_construct: *ERROR*: failed to create admin qpair
> nvme.c: 551:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
> nvme.c: 624:spdk_nvme_probe: *ERROR*: Create probe context failed
> spdk_nvme_probe() failed for transport address '192.168.10.10'
> ./perf: errors occured_

I checked and found that there is no _/etc/libibverbs.d_ file inside _spdk/etc_ folder, that why the warning occurs. But, as it mentioned in the SPDK documentation, I configure SPDK with  _--with-rdma_ flag on both the target and initiator side, to make it compatible for the nvmeof. And the machine has _libibverbs-dev_ _librdmacm-dev_ installed beforehand. 

Any suggestions would be greatly appreciated, I have no clue whether I have missed anything.

## Context (Environment including OS version, SPDK version, etc.)
Target OS: Ubuntu 18.04, kernel version  5.0.0
Initiator OS: Ubuntu 16.04 kernel version 4.10
working on latest SPDK version.

**Comment by benlwalker** [comment]
/dev/nvme1n1 is not a physical NVMe device - it's a network device. `scripts/setup.sh` is designed to unbind physical devices from the kernel and prepare them for use by SPDK, but it doesn't do anything with network devices.

You must have previously configured your initiator system to use NVMe-oF to connect to the target using the kernel initiator. You likely did this using the `nvme` tool. You should undo that (disconnect) first. Then, you can use the SPDK initiator to connect by simply running one of the benchmark tools such as `perf` located in examples/nvme/perf, which you've already attempted.

I think the RDMA error you're getting is because you don't have libibverbs and rdmacm installed. These are different than libibverbs-dev - libibverbs is the runtime libraries and libibverbs-dev is the headers.

**Comment by joyantamishu** [comment]
Thanks Ben for your response. Yes, I will try the _nvme_ thing you mentioned.

I didn't get your last part. I run the command _lsmod |grep "rdma"_ to see the active rdma modules, and here's the output:

[lsmod |grep "rdma"]
> nvme_rdma              28672  0
> nvme_fabrics           20480  1 nvme_rdma
> rdma_ucm               28672  0
> rdma_cm                53248  2 nvme_rdma,rdma_ucm
> configfs               36864  2 rdma_cm
> iw_cm                  45056  1 rdma_cm
> ib_uverbs              65536  2 ib_ucm,rdma_ucm
> ib_cm                  49152  2 rdma_cm,ib_ucm
> ib_core               196608  9 ib_cm,rdma_cm,ib_umad,nvme_rdma,ib_uverbs,iw_cm,mlx5_ib,ib_ucm,rdma_ucm
> nvme_core              53248  6 nvme_fabrics,nvme_rdma,nvme

I see the _rdma_cm_ , which might belong to the rdmacm kernel module you mentioned. But I am not sure whether the _libibverbs_  module is active or not. Is there any way (e.g. linux command) to know about that?

**Comment by AlekseyMarchuk** [comment]
Hi,

Could you clarify if you are using OFED installation or in-box RDMA drivers? What is your NIC model? This warning means that you don't have user-space driver for your NIC, e.g libmlx5 if you use ConnectX. Could you check if this library exists in your system e.g. in /usr/lib or /usr/lib64?

**Comment by joyantamishu** [comment]
Hi Aleksey,

I am using Mellanox ConnectX-4 RDMA NICs, and I thought the driver is pre-installed in any kernel version >= 4.8. Please correct me if I am wrong. 

One thing, I didn't find libmlx5 in neither of /usr/lib or /usr/lib64 directory. That means you and Ben pointed out the absolute reason why it's not working. Could you please let me know possible way to install the user-space driver for the NIC, as I'm really having a hard time figuring out these devops stuff.

**Comment by joyantamishu** [comment]
Hi Aleksey and Ben, 

Thanks a lot for your suggestions. It seems like the user space library has been resolved. This is the way I come to know about that. I run the command:

> sudo ./perf -q 128 -o 4096 -w randread -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.10.10 trsvcid:4420' -t 30

And output is:

> Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
> [ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid30565 ]
> EAL: No free hugepages reported in hugepages-2048kB
> EAL: No available hugepages reported in hugepages-2048kB
> EAL: No available hugepages reported in hugepages-1048576kB
> EAL: FATAL: Cannot get hugepage information.
> EAL: Cannot get hugepage information.
> Failed to initialize DPDK
> Unable to initialize SPDK env
> ./perf: errors occured

new issue occurs:( Do you guys have any work around of this problem??

Once again thanks a lot for your help.

**Comment by benlwalker** [comment]
You don't have any hugepages allocated (you probably rrebooted). Run ./scripts/setup.sh again from SPDK.

**Comment by joyantamishu** [comment]
It works :+1: 

Thanks a lot Ben :)

**Comment by benlwalker** [comment]
No problem!
