### ISSUE TITLE
nvmf_phy_autotest build timeout

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1051]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49538.html
```
 18:17:55	$ make -j72 clean
Build timed out (after 10 minutes). Marking the build as failed.
Build was aborted
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49538.html

**Comment by jimharris** [comment]
Bug scrub:  log shows that it timed out before any tests really got started.  This may be somewhat related to #1007 which is more of an infrastructure error.  @Seth5141 is going to investigate some more.

**Comment by Seth5141** [comment]
@jimharris THis actually might be its own class of bugs. Maciej just posted another one where it fails right on make clean, and I saw an instance of this on the nvme_phy_autotest yesterday.

**Comment by Seth5141** [comment]
closing this and consolidating into #1059 which describes the behavior a little better.
