### ISSUE TITLE
Vhost failing on nightly raid tests.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1054]
## Current Behavior
The vhost nightly tests are failing when parsing a configuration file because that file contains a raid bdev definition where the raid level is an int instead of a string.

## Possible Solution
https://review.gerrithub.io/c/spdk/spdk/+/474145

## Context (Environment including OS version, SPDK version, etc.)
spdk19.10-pre fedora 29.

**Comment by shuhei-matsumoto** [comment]
Hi Seth,

Karol has posted the completely same patch https://review.gerrithub.io/c/spdk/spdk/+/473565 :-)

-Shuhei

**Comment by optimistyzy** [comment]
@Seth5141 The patch number of @karlatec is smaller than yours, let's use Karol's patch

**Comment by Seth5141** [comment]
@shuhei-matsumoto Thanks for pointing that out. I agree that we should use Karol's patch.

**Comment by Seth5141** [comment]
Karol's change was merged. Closing.
