### ISSUE TITLE
nvme_phy_autotest intermittent failure

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1058]
nvme_phy_autotest failed with message:

/var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/common/autotest_common.sh: line 384: kill: (1832902) - No such process
ERROR: process (pid: 1832902) is no longer running

Unfortunately there isn't any other line related to the error. Full log:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49698/archive/nvme_phy_autotest/failed_test.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49698.html

**Comment by jimharris** [comment]
This is a duplicate of #1025.  A patch for that bug (it was a test issue) was merged yesterday.
