### ISSUE TITLE
Jenkins test timeouts at 'make clean'

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1059]
RBD_autotest timeouted at 'make clean' command. Logs:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49835/archive/RBD_autotest/build.log

OS: Fedora 29

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49835.html

**Comment by Seth5141** [comment]
This has been observed on a few different tests over the last few days.
nvmf_phy_autotest
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49538.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49868.html

**Comment by jimharris** [comment]
This one isn't from make clean, but it's from the second (non-shared) normal build:

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50039.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50061.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50059.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50073.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50162.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50166.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50181.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50188.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50206.html

**Comment by Seth5141** [comment]
Closing this issue. After inspecting all instances of this issue, I have found that there are actually several classes of failures here. I've created new issues for those more specific signatures.
