### ISSUE TITLE
NVMF target creation failure

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#106]
After the recent changes in spdk I got this error while creating the NVMF target

app/nvmf_tgt/nvmf_tgt -c etc/spdk/nvmf.conf.in
Starting Intel(R) DPDK initialization ... 
[ DPDK EAL parameters: nvmf -c 1 -n 4 -m 2048 --master-lcore=0 --file-prefix=rte0 --proc-type=auto ]
EAL: Detected 32 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
done.
Occupied cpu core mask is 0x1
Occupied cpu socket mask is 0x1
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
Ioat Copy Engine Offload Enabled
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
Probing device 0000:81:00.0
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
Probing device 0000:82:00.0
Total cores available: 1
Reactor started on core 0 on socket 0
*** RDMA Transport Init ***
allocated subsystem nqn.2014-08.org.nvmexpress.discovery on lcore 0 on socket 0
allocated subsystem nqn.2016-06.io.spdk:cnode11_1 on lcore 0 on socket 0
*** NVMf Target Listening on 10.30.0.11 port 4420 ***
conf.c: 573:spdk_nvmf_parse_subsystem: ***ERROR*** Could not find NVMe controller for Subsystem1
nvmf_tgt.c: 336:spdk_nvmf_startup: ***ERROR*** spdk_nvmf_parse_conf() failed

Here is my  etc/spdk/nvmf.conf.in

[Global]

  LogFacility "local7"

[Rpc]
  Enable No
  Listen 127.0.0.1

[Malloc]
  NumberOfLuns 8
  LunSizeInMB 64

[Nvmf]
  MaxQueuesPerSession 16

  MaxQueueDepth 128

  AcceptorCore 8

  AcceptorPollRate 10000

[Nvme]
  ResetControllerOnTimeout Yes
  NvmeTimeoutValue 30
  AdminPollRate 100000

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode11_1
  Core 9
  Mode Direct
  Listen RDMA 10.30.0.11:4420
  NVMe 0000:81:00.0

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode11_2
  Core 10
  Mode Direct
  Listen RDMA 10.20.0.11:4420
  NVMe 0000:82:00.0

All the hello_world and perf and other examples works fine.

**Comment by bradleyyan183** [comment]
You can try to uncomment the nvme configuration part and try to run again.

2017年2月3日 18:01，"Aleksei" <notifications@github.com>写道：

**Comment by alekseymmm** [comment]
Yes. After I made 
`#[Nvme]`
`#ResetControllerOnTimeout Yes`
`#NvmeTimeoutValue 30`
`#AdminPollRate 100000`

The problem disappeared. Does it has any explanation? Should I always remove [NVME] section while using nvmf?

**Comment by benlwalker** [comment]
I have a patch that fixes this issue coming shortly.
