### ISSUE TITLE
Test timeout in make install

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1060]
## Current Behavior
A VM timed out during make install on the unittests. fedora_vm_10 which is hosted on WFP1

## Steps to Reproduce
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/49863/archive/unittest_autotests/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49863.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50165.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50164.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50303.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50451.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51125.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51123.html

**Comment by Seth5141** [comment]
This specific issue hasn't occurred in about two weeks, and having two issues (this one and #1072) with similar signatures is confusing. Closing this one in favor of #1072 since that one has a specific and traceable signature that we can work with.
