### ISSUE TITLE
SPDK NVME secondary segmentation fault

### ISSUE THREAD

**Issue by rdxavner** [spdk/spdk#1063]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Secondary should be able to probe any specific nvme device that the primary is attached to, at any time, without crashing 
## Current Behavior

See step to reproduce
## Steps to Reproduce
1. Setup:  More than one nvme pci devices assume addresses (0000:00:0b.0, 0000:00:0c.0, 0000:00:0d.0, 0000:00:0e.0)
2. two perf processes , one as primary and one as secondary
3. first process to run (as primary), probe and access all available nvme devices
      ./perf -q 1 -o 4096 -w randread -c 0x1 -t 360 -i 1
4. Second process to run (secondary), probe only two (more than one) of the devices:
./perf -r 'trtype:PCIe traddr:0000:00:0b.0' -r 'trtype:PCIe traddr:0000:00:0c.0' -q 8 -o 131072 -w write -c 0x10 -t 60 -i 1
Outcome:
The secondary crashes on segmentation fault
## Context (Environment including OS version, SPDK version, etc.)
SPDK V19.7
<!--- Providing context helps us come up with a solution that is most useful in the real world- ->

**Comment by jimharris** [comment]
Thanks @rdxavner.  Can you try https://review.gerrithub.io/c/spdk/spdk/+/475015?

**Comment by rdxavner** [comment]
Sure, but I'll be able to do so, beginning of next week. I'll update you

**Comment by rdxavner** [comment]
Hi Jim,
I checked the patch, and it works both with perf and with our application
as well.

Thanks,
Avner
