### ISSUE TITLE
vpp:  spdk_scsi_task_put: Assertion `task->ref > 0' failed.

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1064]
This intermittent failure occurs on ./test/iscsi_tgt/fio/fio.sh when testing with VPP backend.
Test step is when raid volume is removed during fio traffic.

## Steps to Reproduce
Occurs on autotest.sh with VPP backend
1. spdk/scripts/fio.py -p iscsi -i 1048576 -d 128 -t rw -r 10
2. spdk/scripts/rpc.py bdev_raid_delete raid0
3. Triggers ```iscsi_tgt: task.c:50: spdk_scsi_task_put: Assertion `task->ref > 0' failed.```

## Context (Environment including OS version, SPDK version, etc.)
Logs where failure occurs:
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49941.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49890.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50015.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50028.html

**Comment by shuhei-matsumoto** [comment]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50028.html occurred at the latest SPDK master. So I will investigate this issue. Thanks for posting and sorry for inconvenience.

**Comment by shuhei-matsumoto** [comment]
@tomzawadzki

I add a comment
Other logs looks the one before my recent patch series.
But the one you added at the last is the real issue.
So I'm investigating the issue.

+2 iSCSI patch series for refactoring will be no harm to investigate this issue.

Anyway thank you so much for filing this issue.

Thanks,
Shuhei

**Comment by shuhei-matsumoto** [comment]
Hi All,

I submitted three patches to fix this issue.
https://review.gerrithub.io/c/spdk/spdk/+/475042
https://review.gerrithub.io/c/spdk/spdk/+/475043/1
https://review.gerrithub.io/c/spdk/spdk/+/475044/1

The following behavior made investigation difficult :)

 TAILQ_REMOVE(&conn->active_r2t_tasks, primary, link);
 TAILQ_REMOVE(&conn->active_r2t_tasks, primary, link);
caused no error if the first call succeeded.

**Comment by Comphix** [comment]
Another instance https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50455/archive/vpp_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50512.html

**Comment by Seth5141** [comment]
This most recent log happened on the posix iscsi tests.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51163.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51354.html

**Comment by optimistyzy** [comment]
@shuhei-matsumoto I see that some of my patches and yours are merged? Should we close this issue?

**Comment by shuhei-matsumoto** [comment]
@optimistyzy Thanks for taking care of this issue. Let's wait for a few more days. Remaining patches are not merged yet. I think we can close the whole iSCSI issues after all patches (except refactoring) are merged and then no further issue is reported for a few days.

**Comment by jimharris** [comment]
This issue seems to be fixed now with the recent iSCSI hotplug patches.
