### ISSUE TITLE
Failed to limit the io read rate of NULL bdev by qos

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1065]
Almost close to upper bound. So sleep command may not be accurate.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50064.html

  02:26:19	# '[' BANDWIDTH = IOPS ']'
   02:26:19	# jq -r '.bdevs[0].bytes_read'
   02:26:19	# echo '{' '"tick_rate":' 2494202834, '"bdevs":' '[' '{' '"name":' '"Null_0",' '"bytes_read":' 79513059328, '"num_read_ops":' 19412361, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 13977897367902, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
  02:26:19	# io_result_after=79513059328
  02:26:19	# echo 2321612
 02:26:19	# qos_result=2321612
 02:26:19	# '[' BANDWIDTH = BANDWIDTH ']'
 02:26:19	# qos_limit=2097152
  02:26:19	# echo '2097152 0.9'
  02:26:19	# awk '{printf("%i",$1*$2)}'
 02:26:19	# lower_limit=1887436
  02:26:19	# echo '2097152 1.1'
  02:26:19	# awk '{printf("%i",$1*$2)}'
 02:26:19	# upper_limit=2306867
 02:26:19	# '[' 2321612 -lt 1887436 ']'
 02:26:19	# '[' 2321612 -gt 2306867 ']'
 02:26:19	# echo 'Failed to limit the io read rate of NULL bdev by qos'
Failed to limit the io read rate of NULL bdev by qos
 02:26:19	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_null_delete Null_0

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50092.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50155.html

**Comment by shuhei-matsumoto** [comment]
Is it allowed to add the raw value of spdk_get_ticks to bdev_get_iostat RPC and calculate the accurate time duration between two calls of bdev_get_iostat RPC by using tick_rate?

**Comment by shuhei-matsumoto** [comment]
I realized the idea by two patches https://review.gerrithub.io/c/spdk/spdk/+/475167 and https://review.gerrithub.io/c/spdk/spdk/+/475168/1.

**Comment by Comphix** [comment]
The possible reason is that sleep time is not that accurate enough to calculate the difference. For a short solution, let me still have a little wider range (0.85 ~ 1.15) currently it is (0.9 ~ 1.1).

**Comment by shuhei-matsumoto** [comment]
Hi @Comphix 

Thank you for your comment.
My patch is not based on the fact and so it will be wrong.
Will you share your possible reason with us?
We can rerun for now and it’s fine after you are ready.

-Shuhei

**Comment by Comphix** [comment]
A patch for the testing is added https://review.gerrithub.io/c/spdk/spdk/+/475229 so as to avoid the failures first. As described, the testing under limiting is only run few seconds (5 seconds) and this may relies on how accurate we calculate the limit. So in this case, expand from 0.9-1.1 to 0.85-1.15 first.

**Comment by Comphix** [comment]
The possible reason here is that I pick a very minimum limit of 2MB for 5 seconds and the variance could be amplified (like from one more IO in the size of 4K). I will take more look here.

**Comment by shuhei-matsumoto** [comment]
Thanks Gang. I got it but we may have seen only on FreeBSD. I hope that give any hint

**Comment by Comphix** [comment]
Thanks. I've changed my patch in another solution. Instead of having a fixed bandwdith limit, now it will use a measured bandwdith performance which could be more precise from the platform like mentioned the FreeBSD platform.

**Comment by jimharris** [comment]
We should go with Shuhei's patches.  I looked at the calculated IO rates on a few different test runs - on FreeBSD, we end up with quite a bit of deviation from expected.  But after Shuhei's patches, the actual IOPs rate with QoS enabled ends up almost exactly as expected.

**Comment by jimharris** [comment]
(All data here collected from first CI run of Shuhei's 475168 patch on FreeBSD VM.
Ticks calculation:
The script did a "sleep 5", but the ticks data from Shuhei's patch shows the following:

Before:
  "tick_rate": 2494199702,
  "ticks": 915819414002,
After:
  "tick_rate": 2494199702,
  "ticks": 928990110044,

(928990110044 - 915819414002) / 2494199702 = 5.28 seconds

So there is definitely some inaccuracy with the "sleep 5", and using the ticks helps (see below):

IOPs test:
 02:44:58	# qos_result=4194254
 02:44:58	# qos_limit=4194304

Bandwidth test:
 02:45:04	# qos_result=2097825
 02:45:04	# qos_limit=2097152

**Comment by shuhei-matsumoto** [comment]
Thank you @jimharris 

Delayed wakeup will get more IOs and current calculation will have larger IOPS or bandwidth. Timer management is complex and there may be some difference between Linux and BSD.

This is a off topic. I have BSD and FreeBSD book written by Kirk McKusick. I haven't read source code yet and book may not explain the cause. But your analysis gave me a motivation to access them again.

-Shuhei

**Comment by shuhei-matsumoto** [comment]
@Comphix 

As Jim said, could we go with my patches? This change shows current SPDK bdev QoS is nice :)

-Shuhei

**Comment by Comphix** [comment]
Thanks Shuhei, yes, I've added my "+1" for your two patches.

**Comment by Comphix** [comment]
For my patch (https://review.gerrithub.io/c/spdk/spdk/+/475229) to use the measured bandwidth performance for limiting (similar to measured IOPS performance for limiting), I will rebase that after your patches have been merged.

**Comment by Comphix** [comment]
Will keep this issue one more day. Thanks Shuhei's fix.

**Comment by Comphix** [comment]
close this one.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58639.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58637.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58636.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58652.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58656.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58660.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58672.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58675.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58673.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_78150.html

**Comment by jimharris** [comment]
I'm going to close this issue again.  This test log was reaped already, so cannot go back and check it.  I'm wondering if it was related to the more recent #2447 which will stay open.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_83259.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_126677.html
