### ISSUE TITLE
Keep getting "Process leaked file descriptors" failure for Jenkins autotest

### ISSUE THREAD

**Issue by jessehui** [spdk/spdk#1066]
`Process leaked file descriptors` errors are shown, including but not limited, on [blobfs autotest](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50079/archive/BlobFS_autotest/build.log), [nvme_phy atuotest](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50080/archive/nvme_phy_autotest/build.log), [vhost autotest](https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50078/archive/vhost_autotest/build.log).

```shell
05:03:11	# cp /var/jenkins/workspace/RBD_BlobFS_tests/BlobFS_autotest/spdk/app/spdk_tgt/spdk_tgt /var/jenkins/workspace/RBD_BlobFS_tests/BlobFS_autotest/spdk/../output
 05:03:11	# mv ./core.2393030 /var/jenkins/workspace/RBD_BlobFS_tests/BlobFS_autotest/spdk/../output
 05:03:11	# chmod a+r /var/jenkins/workspace/RBD_BlobFS_tests/BlobFS_autotest/spdk/../output/./core.2393030
 05:03:11	# ret=1
 05:03:11	# IFS=
 05:03:11	# read -r -d '' core
 05:03:11	# return 1
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Executing post build scripts.
[BlobFS_autotest] $ /bin/sh -xe /tmp/jenkins1671373838593363035.sh
```

## Steps to Reproduce

1.
2.
3.
4.

**Comment by benlwalker** [comment]
There's two bugs here. First, the Opal code is broken and crashes
the target with an assert when the test script attempts to do a revert on an
NVMe device.

The second problem is more serious. Throughout the test scripts, we use a bash function called
'killprocess' to shut down the target applications. However, killprocess succeeds even if the background target application crashed and is no longer present. That's how the broken Opal code made it in to the repository - it was crashing but the test just continued on. We'll need to make changes to killprocess such that in the cases where the shutdown was expecting the process to be running (i.e. success path in the test), then killprocess correctly fails if the background process is no longer present.

**Comment by jessehui** [comment]
We can disable opal test for now. https://review.gerrithub.io/c/spdk/spdk/+/475169

**Comment by Comphix** [comment]
also will take a detailed look at the "killprocess" issue.

**Comment by Comphix** [comment]
A small change first https://review.gerrithub.io/c/spdk/spdk/+/476127 to exit failure when the process is not there at the time of killing.

**Comment by Comphix** [comment]
For the original issue of "leaked file descriptors", will keep looking. New log here: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/51041/archive/nvmf_autotest/build.log with the above change.

**Comment by Comphix** [comment]
More changes updated to the original patch https://review.gerrithub.io/c/spdk/spdk/+/476127

**Comment by Comphix** [comment]
Rebased above patch for the fix.

**Comment by jimharris** [comment]
Bug scrub: Assigned patch to @jimharris for review.

**Comment by Comphix** [comment]
Change has been merged. Close this issue.
