### ISSUE TITLE
autotest slow emulated device access time

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1068]
When gathering list of test completions all non binary files in SPDK directory are searched for phrase "report_test_completion". This causes to go over all the files in repo recursively and if the files weren't accessed recently it takes much longer than needed. Probably is exposed more just after reboot of a VM after previous run fail.

This is just a single example of such occurrence. There can be more such cases throughout the scripts.

## Expected Behavior
Test finish in timely manner.

## Current Behavior
This grep takes over 3 minutes to complete.
```
 23:59:52	# create_test_list
 23:59:52	# grep -rshI --exclude=autotest_common.sh --exclude=/var/jenkins/workspace/Other/unittest_autotests/spdk/test/common/autotest_common.sh -e report_test_completion /var/jenkins/workspace/Other/unittest_autotests/spdk
 23:59:52	# sed 's/report_test_completion//g; s/[[:blank:]]//g; s/"//g;'
   00:03:34	# dirname /var/jenkins/workspace/Other/unittest_autotests/spdk/autotest.sh
```

Another instance is 

## Possible Solution
- Limit accessing files that do not need to be checked
- Improve access times to the emulated disk devices

## Context (Environment including OS version, SPDK version, etc.)
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50059.html

**Comment by tomzawadzki** [comment]
Patch addressing gathering test completions can be found here:
https://review.gerrithub.io/c/spdk/spdk/+/475083

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52229.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52269.html

**Comment by ksztyber** [comment]
I'm not 100% sure if the two instances I've reported are related to the slow disk access, but they certainly look so. Both of them timed out during the compilation, before any tests could be even started.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53150.html

**Comment by jimharris** [comment]
@Seth5141 - you've made a lot of changes to how we collect test completion results since the last time this failure was hit.  Have your changes eliminated the problem described by @tomzawadzki here?

**Comment by tomzawadzki** [comment]
The original reason for submission of this issue was not changed even after changes from @Seth5141.
Please see patches submitted once again to new review board:
[test: limit files scanned when searching for test completions](https://review.spdk.io/gerrit/c/spdk/spdk/+/1089/1 "test: limit files scanned when searching for test completions")
[test/common: do not double exclude autotest_common.sh](https://review.spdk.io/gerrit/c/spdk/spdk/+/1088/1 "test/common: do not double exclude autotest_common.sh")
[test/common: only scan .sh files for run_test](https://review.spdk.io/gerrit/c/spdk/spdk/+/1087/1 "test/common: only scan .sh files for run_test")
[[RFC]test/timing: just a test for how long the greps take](https://review.spdk.io/gerrit/c/spdk/spdk/+/1086/1 "[RFC]test/timing: just a test for how long the greps take")

Submitted along with timing test to gauge the difference. One part that affects the results is if the VM/machine was just rebooted.

**Comment by tomzawadzki** [comment]
After talking to @karlatec, one of limiting factors when accessing the SPDK repository in a VM was the NFS backing it. It has been since removed.

Using https://review.spdk.io/gerrit/c/spdk/spdk/+/1086/ greping all files in repo did not add considerable amount of time in current CI setup. Thus this issue is no longer relevant and will be closed.

Remaining patches for improving collection of test completions, will still go through the review process.
