### ISSUE TITLE
nvmf/tcp: intermittent hang in host/target_disconnect.sh test

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1069]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50146.html

Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 16:47:40	# xtrace_disable
 16:47:40	# PREV_BASH_OPTS=ehxBE
 16:47:40	# set +x
Starting SPDK v20.01-pre git sha1 f78cd57baa / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: nvmf -c 0xF0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 4
app.c: 543:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
app.c: 547:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
app.c: 549:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
 16:47:41	# xtrace_enable
 16:47:41	# ((  i == 0  ))
 16:47:41	# return 0
 16:47:41	# timing_exit start_nvmf_tgt
 16:47:41	# xtrace_disable
 16:47:41	# PREV_BASH_OPTS=ehxBE
 16:47:41	# set +x
 16:47:41	# xtrace_enable
 16:47:41	# /var/jenkins/workspace/NVMeOF_tests/nvmf_tcp_autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
Malloc0
 16:47:41	# /var/jenkins/workspace/NVMeOF_tests/nvmf_tcp_autotest/spdk/scripts/rpc.py nvmf_create_transport -t tcp -o
tcp.c: 538:spdk_nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
 16:47:41	# /var/jenkins/workspace/NVMeOF_tests/nvmf_tcp_autotest/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
nvmf_subsystem_create is deprecated, use nvmf_create_subsystem instead.
 16:47:41	# /var/jenkins/workspace/NVMeOF_tests/nvmf_tcp_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
 16:47:42	# /var/jenkins/workspace/NVMeOF_tests/nvmf_tcp_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420
tcp.c: 733:spdk_nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.1 port 4420 ***
 16:47:42	# wait 506785
Build timed out (after 12 minutes). Marking the build as failed.
Build was aborted
[PostBuildScript] - Executing post build scripts.
[nvmf_tcp_autotest] $ /bin/sh -xe /tmp/jenkins8454100601846550031.sh
+ set +x

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50250.html

**Comment by Seth5141** [comment]
This appears to have only hit on https://review.gerrithub.io/c/spdk/spdk/+/473282 That change should be merged, but it's a good clue to something going wrong in the tcp transport.

**Comment by tomzawadzki** [comment]
#1087 Both issues seem very related, even if the transport is different.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51870.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55528.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58633.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58638.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58646.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58647.html

**Comment by shuhei-matsumoto** [comment]
Sorry I should have written "false positive: 1169"

**Comment by jimharris** [comment]
Bug scrub: Closing this issue.  All reports since January 9 are not related to this issue and have been fixed separately.
