### ISSUE TITLE
failure to join client thread in rpc_client.sh test

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1070]
## Current Behavior
The rpc_client.sh test currently looked like this in my failed test.

~~~
 19:02:43	# xtrace_enable
 19:02:43	# test/rpc_client/rpc_client.sh
  19:02:43	# xtrace_enable
 19:02:43	# timing_enter rpc_client
 19:02:43	# xtrace_disable
 19:02:43	# PREV_BASH_OPTS=ehxBE
 19:02:43	# set +x
 19:02:43	# xtrace_enable
 19:02:43	# /var/jenkins/workspace/Other/event_autotest/spdk/test/rpc_client/rpc_client_test
failed to join client thread (rc: -1)
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: spdk_get_version
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: rpc_get_methods
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: hook_conn_close
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_null_params
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_method_runtime
rpc_client_test.c: 136:spdk_jsonrpc_client_check_rpc_method: *NOTICE*: test_method_startup
FAILED
~~~
## Context (Environment including OS version, SPDK version, etc.)
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50160/archive/event_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50160.html

**Comment by jimharris** [comment]
Related to issue #839.  That was fixed (or worked around) by patch acea7bbce.  This seems to be another instance of some threads getting swapped out during execution - in this case, we expect a thread to exit within one second but it timed out.  For #839 was fixed it by removing the sem_timedwait and just do the pthread_join - it doesn't really matter if the threads take 0.5 or 5 seconds to exit for this test.

**Comment by Seth5141** [comment]
@jimharris Thanks, that made writing a fix a lot easier. I have completely removed the semaphores where I can, and swapped out the other sem_timedwait call for a sem_wait call.
https://review.gerrithub.io/c/spdk/spdk/+/475166

**Comment by Seth5141** [comment]
Change has been merged.
