### ISSUE TITLE
Test times out in test/ocf/integrity/stats.sh because bdevperf fails to exit.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1071]
Latent failure observed during the nvme_phy_autotest job.

output:
~~~
START TEST SUITE /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/ocf/integrity/stats.sh
************************************
 00:35:15	# xtrace_enable
 00:35:15	# /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/ocf/integrity/stats.sh
  00:35:15	# xtrace_enable
 00:35:15	# bdevperf=/var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/bdev/bdevperf/bdevperf
 00:35:15	# rpc_py=/var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/scripts/rpc.py
 00:35:15	# bdev_perf_pid=1330362
 00:35:15	# waitforlisten 1330362
 00:35:15	# /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/bdev/bdevperf/bdevperf -c /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest/spdk/test/ocf/integrity/mallocs.conf -q 128 -o 4096 -w write -t 120 -r /var/tmp/spdk.sock
 00:35:15	# '[' -z 1330362 ']'
 00:35:15	# local rpc_addr=/var/tmp/spdk.sock
. . .
 00:35:18	# killprocess 1330362
 00:35:18	# '[' -z 1330362 ']'
 00:35:18	# kill -0 1330362
  00:35:18	# ps --no-headers -o comm= 1330362
 00:35:18	# '[' reactor_0 = sudo ']'
 00:35:18	# echo 'killing process with pid 1330362'
killing process with pid 1330362
 00:35:18	# kill 1330362
 00:35:18	# wait 1330362
Build timed out (after 10 minutes). Marking the build as failed.
Build was aborted
[PostBuildScript] - Executing post build scripts.
[nvme_phy_autotest] $ /bin/sh -xe /tmp/jenkins2847477288332553866.sh
~~~

## Possible Solution
This may be a test issue since I don't see why we have to run bdevperf for 120 seconds when just making sure the stats command works. I will look at the test organization a little.

## Context (Environment including OS version, SPDK version, etc.)
A couple of logs:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50181/archive/nvme_phy_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50061/archive/nvme_phy_autotest/build.log

**Comment by jimharris** [comment]
I agree it doesn't need to be 120 seconds.  But it is trying to killprocess right after it gets the stats.  I suspect even lowering this to something smaller may not fix the issue - if killprocess isn't working, the wait may never complete.

**Comment by Seth5141** [comment]
Yeah, I think that we could just run bdevperf for 5 - 10 seconds, and let it finish naturally. I don't think the purpose of this test was to determine if we could kill bdevperf with sigterm. We should only pass or fail here based on the return code of the RPC, not on anything else.
As an aside, it would probably be good to know why sigterm sometimes fails to kill bdevperf, but that, I feel, is outside the scope of fixing this latent failure.

**Comment by Seth5141** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/475313 - patch where I remove the call to killprocess from the test.

**Comment by jimharris** [comment]
Oh - I missed that this is all related to recently closed issue #1025 (since we split this new test out into a separate script).  This used to just run the write test for 4 seconds and collect stats, but we hit cases where bdevperf actually exited before we had a chance to get the stats.  I specifically asked @Donaim to run this for 120 seconds instead with a killprocess.

**Comment by Seth5141** [comment]
Ah haha. I see. OK, I will dig a little deeper then and see if there's not a reasonable explanation for why we sometimes fail to kill bdevperf.

**Comment by Seth5141** [comment]
Patch in the meantime to keep the latent failure away https://review.gerrithub.io/c/spdk/spdk/+/475315. Once that is merged, I'll take off the latent_failure tag, but leave the issue open for review later.

**Comment by jimharris** [comment]
Closing this issue - intermittent issue hasn't been seen in 3 months.
