### ISSUE TITLE
Autobuild.sh hanging during initial make clean *before any tests begin.*

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1072]
## Current Behavior
This specific class of failures occurs on both physical and virtual machines in the test pool before any testing begins during the autobuild phase of the job. The logs look like this:
~~~
 18:17:55	$ timing_enter make
 18:17:55	$ xtrace_disable
 18:17:55	$ PREV_BASH_OPTS=ehxBE
 18:17:55	$ set +x
 18:17:55	$ xtrace_enable
 18:17:55	$ make -j72 clean
Build timed out (after 10 minutes). Marking the build as failed.
Build was aborted
~~~

## Context (Environment including OS version, SPDK version, etc.)
This has been reported at least four times between 11/15/2019 and 11/20/2019
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49835.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49538.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_49868.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50166.html

## Possible Causes

I'm not really sure what is going on here, because the failure can happen on both physical and virtual machines so this is not a qemu/scheduling thing. I will have to do some more research to identify how that could happen.

**Comment by jimharris** [comment]
49835 dmesg shows a kernel seg fault.  That's the only one from above that was in a VM.  So this could be two different issues that show the same symptom?

**Comment by jimharris** [comment]
This build timed out - not during make clean, but it clearly shows something amiss since make -j4 clean took 3 minutes:

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50296.html

 22:04:11	$ make -j4 clean
 22:07:05	$ '[' 1 -eq 1 ']'
 22:07:05	$ /var/jenkins/workspace/Other_systems/ubuntu18_autotest/spdk/test/make/check_so_deps.sh
  22:07:05	$ xtrace_enable
 22:07:05	$ libdir=/var/jenkins/workspace/Other_systems/ubuntu18_autotest/spdk/build/lib
 22:07:05	$ libdeps_file=/var/jenkins/workspace/Other_systems/ubuntu18_autotest/spdk/mk/spdk.lib_deps.mk

check_so_deps.sh also takes 2 minutes.

  LINK test/unit/lib/ftl/ftl_wptr/ftl_wptr_ut
 22:10:43	$ xtrace_disable
 22:10:43	$ PREV_BASH_OPTS=ehxBE
 22:10:43	$ set +x
---------------------------------------------------------------------
There are still undefined symbols in the library ut_mock 
__real_calloc
__real_pthread_mutexattr_
<snip>
rte_vhost_set_vring_base
rte_vhost_vring_call
---------------------------------------------------------------------
 22:12:33	$ xtrace_enable
 22:12:33	$ report_test_completion shared_object_build

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51133.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51137.html

**Comment by jimharris** [comment]
(Moved from #1060)
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51123.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51684.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51884.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51880.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52114.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52306.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52433.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52437.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52135.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52588.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52641.html

**Comment by jimharris** [comment]
Here's another one that timing out, but during the initial build, not before the make clean.

I'm tempted to start a new issue for this, but posting this one here for now.

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52651.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52611.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52820.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52956.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53027.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53239.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53249.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53250.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53248.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53251.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53320.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53120.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53124.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53745.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53774.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53773.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53754.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53750.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53769.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53767.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53747.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53770.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53707.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53979.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54413.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54417.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54351.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54458.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54459.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54166.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54580.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54992.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55187.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55208.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55410.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55608.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57366.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57497.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3807.html

**Comment by karlatec** [comment]
This one is pretty old and I'm pretty sure that the root cause was related to NFS network.
Over the time I made some changes to how systems interacted with NFS network and for a couple of weeks now NFS network is no longer used.
I think this can be clsoed.
