### ISSUE TITLE
NVMl autotest timeout due to existing RPC socket

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#1076]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior
No Error

## Current Behavior
************************************
START TEST SUITE test/rpc_client/rpc_client.sh
************************************
 08:23:43	# xtrace_enable
 08:23:43	# test/rpc_client/rpc_client.sh
  08:23:43	# xtrace_enable
 08:23:43	# timing_enter rpc_client
 08:23:43	# xtrace_disable
 08:23:43	# PREV_BASH_OPTS=ehxBE
 08:23:43	# set +x
 08:23:43	# xtrace_enable
 08:23:43	# /var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/test/rpc_client/rpc_client_test
rpc.c: 173:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.
spdk_rpc_listen() failed: -1
Build timed out (after 15 minutes). Marking the build as failed.
Build was aborted

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50463/archive/nvml_autotest/build.log

**Comment by Comphix** [comment]
Looking at https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/50463/archive/nvml_autotest/build.log

Test start at 08:19:09	$ xtrace_enable
Error of RPC sock at:  08:23:43	# /var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/test/rpc_client/rpc_client_test
rpc.c: 173:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.

It is about 5 minutes while reporting:

spdk_rpc_listen() failed: -1
Build timed out (after 15 minutes). Marking the build as failed.
Build was aborted

It is due to that we keeping "spdk_rpc_listen" and do nothing due to spdk.sock in use and eventually time out?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50524.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_50576.html

**Comment by Comphix** [comment]
Raised a patch https://review.gerrithub.io/c/spdk/spdk/+/475946

**Comment by Comphix** [comment]
> Raised a patch https://review.gerrithub.io/c/spdk/spdk/+/475946

This one looks like not exactly fixing this issue.

Raised below one which is for the fix

https://review.gerrithub.io/c/spdk/spdk/+/476048

The problem is that in the error path, the semaphore is not increased so that another operation of wait_sem can never be successful and eventually it times out. This time out is not due to testing long time.

**Comment by Comphix** [comment]
Patch has been merged. Close this issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52775.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52770.html

**Comment by jimharris** [comment]
Hey Seth,

Neither of these two most recent reports seem due to the issue described here. Is it possible you accidentally posted the wrong issue number to Gerrit?
