### ISSUE TITLE
Wrong nvme discover command syntax in nvmf getting started doc

### ISSUE THREAD

**Issue by timork** [spdk/spdk#108]
nvme discovery -t rdma -s 192.168.100.8 -s 4420
the correct one:
nvme **discover** -t rdma **-a** 192.168.100.8 -s 4420

http://www.spdk.io/doc/nvmf_getting_started.html

**Comment by optimistyzy** [comment]
@timork  will fix it.

**Comment by dverkamp-intel** [comment]
Fixed in commit 86f80d2d70b4af29a9ac3d8843a7a56171f19e41 - thanks for the report!
