### ISSUE TITLE
Whole autotest fails on VM Fedora31

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1081]
See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Tests pass
## Current Behavior

Whole our test fails on: 
```
  CXX test/cpp_headers/iscsi_spec.o
In file included from /usr/src/fio/os/os.h:33,
                 from /usr/src/fio/thread_options.h:5,
                 from /usr/src/fio/fio.h:18,
                 from fio_plugin.c:50:
/usr/src/fio/os/os-linux.h:124:19: error: static declaration of ‘gettid’ follows non-static declaration
  124 | static inline int gettid(void)
      |                   ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from /home/sys_sgci/spdk/include/spdk/stdinc.h:75,
                 from fio_plugin.c:34:
/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make[3]: *** [/home/sys_sgci/spdk/mk/spdk.common.mk:374: fio_plugin.o] Error 1
  CC test/event/reactor/reactor.o
make[2]: *** [/home/sys_sgci/spdk/mk/spdk.subdirs.mk:44: fio_plugin] Error 2
make[1]: *** [/home/sys_sgci/spdk/mk/spdk.subdirs.mk:44: bdev] Error 2
make: *** [/home/sys_sgci/spdk/mk/spdk.subdirs.mk:44: examples] Error 2
make: *** Waiting for unfinished jobs....
```
## Steps to Reproduce

1. Take fedora31 vm
2. Run any of our CI autotest

## Context (Environment including OS version, SPDK version, etc.)

VM OS: Fedora 31
Kernel: 5.3.12-300.fc31.x86_64
gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
commit: 3ad192e3b5a3c4345d40a2e9ff4d8aedaf332064

**Comment by jimharris** [comment]
I think we need a newer version of fio.

https://bugs.launchpad.net/ubuntu-kernel-tests/+bug/1844548

**Comment by peluse** [comment]
In addition to updating the version also please update this doc: https://github.com/spdk/spdk/tree/master/examples/nvme/fio_plugin so it matches the one in the /examples/bdev/fio dir

**Comment by wawryk** [comment]
Change version to fio-3.15 resolved that issue.
Patch: https://review.gerrithub.io/c/spdk/spdk/+/476893
