### ISSUE TITLE
problem of "Vagrant Development Environment“

### ISSUE THREAD

**Issue by ywbgithub** [spdk/spdk#1082]
my host machine run centos7.6，and I follow the steps of ""Vagrant Development Environment"". when I execute command ""vagrant ssh''', I log on the virtual machine, and then I execute the command "" lspci | grep "Non-Volatile", there is non output.

how to fix it

**Comment by wawryk** [comment]
Do You add emulated disks to Your vm config ? 
Show us how you create vm.

**Comment by ywbgithub** [comment]
cd spdk/scripts/vagrant
./create_vbox.sh ubuntu18

**Comment by ywbgithub** [comment]
I have another machine run ubuntu18.04, after I create the virtual machine,and  then ""vagrant ssh''',. when I I execute the command "" lspci | grep "Non-Volatile", it is ok

**Comment by wawryk** [comment]
You should use -b option to use emulated nvme disk.
For example:
-b /var/lib/libvirt/images/nvme1.img,nvme,1 ubuntu18
Above option create You one emulated nvme disk with one namespace

For more please read help from create_vbox.sh file

**Comment by ywbgithub** [comment]
ok， I solved the problem when adding ""-b"" option

**Comment by optimistyzy** [comment]
@ywbgithub So let me close this issue. If you have another issue, you can create a new one.
