### ISSUE TITLE
nvmf: intermittent hang in host/target_disconnect.sh test

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1087]
Fail on test/nvmf/host/target_disconnect.sh --transport=rdma

[https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51277.html](https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51277.html)

nvme_rdma.c: 390:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 8)
nvme_rdma.c: 805:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1035:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_rdma.c:1666:nvme_rdma_ctrlr_construct: *ERROR*: failed to create admin qpair
nvme.c: 561:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 634:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '10.102.17.213'
/var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/examples/nvme/reconnect/reconnect: errors occured
Initializing NVMe Controllers
  15:36:20	# trap - ERR
  15:36:20	# print_backtrace
  15:36:20	# [[ hxBE =~ e ]]
  15:36:20	# return 0
 15:36:20	# '[' 1 '!=' 1 ']'
 15:36:20	# set -e
 15:36:20	# disconnect_init 10.102.17.213
 15:36:20	# nvmfappstart '-m 0xF0'
 15:36:20	# timing_enter start_nvmf_tgt
 15:36:20	# xtrace_disable
 15:36:20	# PREV_BASH_OPTS=ehxBE
 15:36:20	# set +x
 15:36:20	# xtrace_enable
 15:36:20	# nvmfpid=2404945
 15:36:20	# trap 'process_shm --id $NVMF_APP_SHM_ID; nvmftestfini; exit 1' SIGINT SIGTERM EXIT
 15:36:20	# ./app/nvmf_tgt/nvmf_tgt -i 0 -e 0xFFFF -m 0xF0
 15:36:20	# waitforlisten 2404945
 15:36:20	# '[' -z 2404945 ']'
 15:36:20	# local rpc_addr=/var/tmp/spdk.sock
 15:36:20	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 15:36:20	# xtrace_disable
 15:36:20	# PREV_BASH_OPTS=ehxBE
 15:36:20	# set +x
Starting SPDK v20.01-pre git sha1 e194d7dc7e / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: nvmf -c 0xF0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 4
app.c: 543:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
app.c: 547:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
app.c: 549:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
 15:36:21	# xtrace_enable
 15:36:21	# ((  i == 0  ))
 15:36:21	# return 0
 15:36:21	# timing_exit start_nvmf_tgt
 15:36:21	# xtrace_disable
 15:36:21	# PREV_BASH_OPTS=ehxBE
 15:36:21	# set +x
 15:36:21	# xtrace_enable
 15:36:21	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
Malloc0
 15:36:21	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py nvmf_create_transport -t rdma
 15:36:22	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
nvmf_subsystem_create is deprecated, use nvmf_create_subsystem instead.
 15:36:22	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
 15:36:22	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.102.17.213 -s 4420
 15:36:22	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/examples/nvme/reconnect/reconnect -q 32 -o 4096 -w randrw -M 50 -t 10 -c 0xF -r 'trtype:rdma adrfam:IPv4 traddr:10.102.17.213 trsvcid:4420'
 15:36:22	# reconnectpid=2404978
 15:36:22	# sleep 2
Starting SPDK v20.01-pre git sha1 e194d7dc7e / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: reconnect --no-shconf -c 0xF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid2404978 ]
EAL: No available hugepages reported in hugepages-1048576kB
 15:36:24	# kill -9 2404945
 15:36:24	# sleep 2
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.213 in failed state.
A controller has encountered a failure and is being reset.
nvme_ctrlr.c:1068:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_rdma.c: 390:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 802:nvme_rdma_connect: *NOTICE*: Received a stale connection notice during connection.
nvme_rdma.c:1035:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.213 in failed state.
Unable to reset the controller.
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_ctrlr.c:1068:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_rdma.c: 390:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 802:nvme_rdma_connect: *NOTICE*: Received a stale connection notice during connection.
nvme_rdma.c:1035:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.213 in failed state.
Unable to reset the controller.
test/nvmf/host/target_disconnect.sh: line 62: 2404945 Killed                  $NVMF_APP $1
 15:36:26	# disconnect_init 10.102.17.213
 15:36:26	# nvmfappstart '-m 0xF0'
 15:36:26	# timing_enter start_nvmf_tgt
 15:36:26	# xtrace_disable
 15:36:26	# PREV_BASH_OPTS=ehxBE
 15:36:26	# set +x
 15:36:26	# xtrace_enable
 15:36:26	# nvmfpid=2404990
 15:36:26	# trap 'process_shm --id $NVMF_APP_SHM_ID; nvmftestfini; exit 1' SIGINT SIGTERM EXIT
 15:36:26	# waitforlisten 2404990
 15:36:26	# '[' -z 2404990 ']'
 15:36:26	# local rpc_addr=/var/tmp/spdk.sock
 15:36:26	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 15:36:26	# xtrace_disable
 15:36:26	# PREV_BASH_OPTS=ehxBE
 15:36:26	# set +x
 15:36:26	# ./app/nvmf_tgt/nvmf_tgt -i 0 -e 0xFFFF -m 0xF0
Starting SPDK v20.01-pre git sha1 e194d7dc7e / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: nvmf -c 0xF0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 4
nvme_ctrlr.c:1068:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_rdma.c: 390:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 802:nvme_rdma_connect: *NOTICE*: Received a stale connection notice during connection.
nvme_rdma.c:1035:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.213 in failed state.
Unable to reset the controller.
app.c: 543:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
app.c: 547:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
app.c: 549:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
 15:36:27	# xtrace_enable
 15:36:27	# ((  i == 0  ))
 15:36:27	# return 0
 15:36:27	# timing_exit start_nvmf_tgt
 15:36:27	# xtrace_disable
 15:36:27	# PREV_BASH_OPTS=ehxBE
 15:36:27	# set +x
 15:36:27	# xtrace_enable
 15:36:27	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
nvme_ctrlr.c:2640:nvme_ctrlr_keep_alive: *ERROR*: Submitting Keep Alive failed
nvme_ctrlr.c:1068:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_rdma.c: 390:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 10)
nvme_rdma.c: 802:nvme_rdma_connect: *NOTICE*: Received a stale connection notice during connection.
nvme_rdma.c:1035:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c:1089:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
nvme_ctrlr.c: 673:nvme_ctrlr_fail: *ERROR*: ctrlr 10.102.17.213 in failed state.
Unable to reset the controller.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51277.html

**Comment by peluse** [comment]
bug scrub - check to make sure this is rebased recently as the test should not have run w/soft roce

**Comment by Seth5141** [comment]
Stupid mistake on my part. https://review.gerrithub.io/c/spdk/spdk/+/476648 will fix master so this never runs on soft-roce

**Comment by Seth5141** [comment]
change merged.
