### ISSUE TITLE
discover to spdk nvmf target from linux host fails

### ISSUE THREAD

**Issue by bharatpotnuri** [spdk/spdk#1089]
Hi,
TOT SPDK NVMF target discovery is failing due to keep alive timeout 'kato' of nvme command.
I am using TOT spdk and TOT nvmecli. BTW I am not sure if this is an nvmecli bug or spdk bug.
nvmecli is not allowing kato 0 during discover and spdk doesnt allow non zero kato for discover.

## Expected Behavior
[root@chittorgarh ~]# ./nvme discover -t rdma -a 10.0.2.2 -s 4420 -q nqn.2016-06.io.spdk:cnode1 -k0

Discovery Log Number of Records 1, Generation counter 3
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not required
portid:  0
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  10.0.2.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000

## Current Behavior
[root@chittorgarh nvmecli]# ./nvme discover -t rdma -a 10.0.2.2 -s 4420 -q nqn.2016-06.io.spdk:cnode1 -k0
Failed to write to /dev/nvme-fabrics: Input/output error

spdk target err logs:
ctrlr.c: 298:spdk_nvmf_ctrlr_create: *ERROR*: Discovery controller don't accept keep-alive timeout, 20000
ctrlr.c: 617:spdk_nvmf_ctrlr_connect: *ERROR*: spdk_nvmf_ctrlr_create() failed

## Possible Solution
Either spdk should alloc kato during discovery or nvmecli should pass kato as '0' if no kato argument is provided for discover.

## Steps to Reproduce
pull latest spdk and nvmecli
https://github.com/linux-nvme/nvme-cli

configure spdk target:
spdk/app/nvmf_tgt/nvmf_tgt -m 0xFFFF &
spdk/scripts/rpc.py nvmf_create_transport -t RDMA -u 131072 -p 4 -c 1024 -r
spdk/scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
spdk/scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.0.2.2 -s 4420

try discover from host:
nvme discover -t rdma -a 10.0.2.2 -s 4420 -q nqn.2016-06.io.spdk:cnode1 -k0

## Context (Environment including OS version, SPDK version, etc.)
kernel version: 5.4.0-rc8
nvme version: 1.9.132.gca9a
SPDK v20.01-pre git sha1 2389caa4f515

**Comment by glodfish-zg** [comment]
hi @bharatpotnuri. Could you try this with kernel target and see what happens.
From the spec 1.0a :
The Keep Alive command is reserved for Discovery controllers. A transport may specify a fixed Discovery controller activity timeout value (e.g., 2 minutes). 
I think it means the target doesn't want to accept the KATO in the discovery controller.

**Comment by bharatpotnuri** [comment]
It works fine with kernel target.
```
[root@chittorgarh ~]# nvme discover -t rdma -a 10.0.2.2 -s 4420 -q nqn.2016-06.io.spdk:cnode1 -k0
Discovery Log Number of Records 1, Generation counter 2
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified, sq flow control disable supported
portid:  1
trsvcid: 4420
subnqn:  nvme-ram0
traddr:  10.0.2.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
```

Havent gone through this much but recent chnages in target allows discovery kato.
```
commit 2d352df57bcd7fee800fa1aa7257e68bfca64d2b
Author: Sagi Grimberg <sagi@grimberg.me>
Date:   Fri Jul 12 11:02:09 2019 -0700

    nvme-fabrics: allow discovery subsystems accept a kato

    This modifies the behavior of discovery subsystems to accept
    a kato as a preparation to support discovery log change
    events. This also means that now every discovery controller
    will have a default kato value, and for non-persistent connections
    the host needs to pass in a zero kato value (keep_alive_tmo=0).

    Reviewed-by: Minwoo Im <minwoo.im.dev@gmail.com>
    Reviewed-by: James Smart <james.smart@broadcom.com>
    Reviewed-by: Hannes Reinecke <hare@suse.com>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: Chaitanya Kulkarni <chaitanya.kulkarni@wdc.com>
    Signed-off-by: Sagi Grimberg <sagi@grimberg.me>
```

**Comment by bharatpotnuri** [comment]
There are two issues here,
-> spdk target not accepting kato.
-> nvmecli `nvme` passes wrong kato value down to kernel host even zero as passed as argument.
I was unsure bug belongs to (spdk or nvmecli) so logged here.

**Comment by shuhei-matsumoto** [comment]
Hi @bharatpotnuri 

Does this patch work for you? https://review.gerrithub.io/c/spdk/spdk/+/476810.
This patch changes SPDK nvmf target to accept KATO for discovery controller.

**Comment by bharatpotnuri** [comment]
> 
> 
> Hi @bharatpotnuri
> 
> Does this patch work for you? https://review.gerrithub.io/c/spdk/spdk/+/476810.
> This patch changes SPDK nvmf target to accept KATO for discovery controller.

It may probably work but I am facing some issues with TOT code now, wierd thing is with the exact prvevious changeset spdk stopped working, I tried going back to v18.0, there there is no discover check for kato. Below is the failure I am seeing, Please let me know if I missed something here:
```
[root@mehrangarh spdk]# /home/spdk_nvme-cli/spdk/app/nvmf_tgt/nvmf_tgt -m 0xFF
Starting SPDK v20.01-pre git sha1 743292aa0f1a / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0xFF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid13472 ]
error allocating rte services array
EAL: FATAL: rte_service_init() failed
EAL: rte_service_init() failed
Failed to initialize DPDK
Unable to initialize SPDK env
```

**Comment by shuhei-matsumoto** [comment]
The above log shows your failure occurred at https://github.com/spdk/spdk/commit/743292aa0f1a73681184a20effb40b7509de2a04.
But this is unrelated.

Could you share from which commit the failure started to occur? That may be helpful for us.
(Please make clean to know the commit correctly.)

We need this SHA1 value.
  Starting SPDK v20.01-pre git sha1 743292aa0f1a / DPDK 19.08.0 initialization...

Oh, this SHA1 feature is really helpful, thank you @AlekseyMarchuk !
Then I hope you can boot SPDK normally.

**Comment by bharatpotnuri** [comment]
> The above log shows your failure occurred at [743292a](https://github.com/spdk/spdk/commit/743292aa0f1a73681184a20effb40b7509de2a04).
> But this is unrelated.
> 
> Could you share from which commit the failure started to occur? That may be helpful for us.
> (Please make clean to know the commit correctly.)
> 
> We need this SHA1 value.
> Starting SPDK v20.01-pre git sha1 [743292a](https://github.com/spdk/spdk/commit/743292aa0f1a73681184a20effb40b7509de2a04) / DPDK 19.08.0 initialization...
> 
> Oh, this SHA1 feature is really helpful, thank you @AlekseyMarchuk !
> Then I hope you can boot SPDK normally.

thanks for the suggestion @shuhei-matsumoto. Same `74329` used to work before. 
I just figured out that I rebooted my machine from 5.4 to 4.19 kernel that caused spdk failure. Now booting it back to 5.4, spdk works. didnt think of kernel as these are user space apps :( 
```
[root@mehrangarh ~]# /home/spdk_nvme-cli/spdk/app/nvmf_tgt/nvmf_tgt -m 0xFF
Starting SPDK v20.01-pre git sha1 743292aa0f1a / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0xFF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid12974 ]
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 8
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 2
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 3
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
```

**Comment by bharatpotnuri** [comment]
> Hi @bharatpotnuri
> 
> Does this patch work for you? https://review.gerrithub.io/c/spdk/spdk/+/476810.
> This patch changes SPDK nvmf target to accept KATO for discovery controller.

@shuhei-matsumoto patch works. Thanks.
```
[root@chittorgarh ~]# nvme discover -t rdma -a 10.0.2.2 -s 4420 -q nqn.2016-06.io.spdk:cnode1

Discovery Log Number of Records 1, Generation counter 3
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not required
portid:  0
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  10.0.2.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
```

**Comment by bharatpotnuri** [comment]
BTW, there is a bug in nvmecli, where it doesnt pass zero kato argument. raised an issue at nvme-cli.
https://github.com/linux-nvme/nvme-cli/issues/624

**Comment by shuhei-matsumoto** [comment]
Thank you for your great analysis including raising github issue, @bharatpotnuri 
Oh I didn't expect the kernel caused the difference, and good to know the patch worked.

The event that leads to the change may be different but SPDK may have to accept KATO for discovery controller as Linux kernel do.

Hi All, will you give any feedback on this?

**Comment by shuhei-matsumoto** [comment]
I updated the patch https://review.gerrithub.io/c/spdk/spdk/+/476810 and it is ready to review.

**Comment by glodfish-zg** [comment]
@shuhei-matsumoto. Hi shuhei. I think It's fine to accept the KATO for the discovery controller.

**Comment by shuhei-matsumoto** [comment]
Thank you so much @glodfish-zg 
I paste your patch https://review.gerrithub.io/c/spdk/spdk/+/478016 here.
Let's get review both.

**Comment by bharatpotnuri** [comment]
Thanks for the commit @shuhei-matsumoto.
closing out the issue
