### ISSUE TITLE
NVMe autotest intermittent failure: MMIO write caused illegal instruction exception

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1091]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51427.html

Program terminated with signal SIGILL, Illegal instruction.
#0  0x00000000005c6a45 in spdk_mmio_write_4 (addr=0x20100080100c, val=231) at /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/include/spdk/mmio.h:94
94		*addr = val;
[Current thread is 1 (Thread 0x7f122b2e7a40 (LWP 746610))]

**Comment by jimharris** [comment]
Hi Shuhei,

This issue is currently being tracked in #1053.  I'm going to close this issue but copy your comment to #1053.  I'm also going to update the title of that issue to include some additional details to help with future categorization of intermittent failures.

-Jim
