### ISSUE TITLE
VPP intermittent failure: framework_start_init failed

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1092]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51429.html

00:16:51	# xtrace_enable
 00:16:51	# ((  i == 0  ))
 00:16:51	# return 0
 00:16:51	# rpc_wait_pid=3147873
 00:16:51	# /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/scripts/rpc.py iscsi_set_options -o 30 -a 16
 00:16:51	# /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/scripts/rpc.py framework_wait_init
 00:16:52	# ps 3147873
    PID TTY      STAT   TIME COMMAND
3147873 ?        R      0:00 python3 /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/scripts/rpc.py framework_wait_init
 00:16:52	# /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/scripts/rpc.py framework_start_init
Connection closed with partial response:

Connection closed with partial response:

  00:16:52	# trap - ERR
  00:16:52	# print_backtrace
  00:16:52	# [[ ehxBE =~ e ]]
  00:16:52	# xtrace_disable
  00:16:52	# PREV_BASH_OPTS=ehxBE
  00:16:52	# set +x
========== Backtrace start: ==========

in ./test/iscsi_tgt/rpc_config/rpc_config.sh:42 -> main()
     ...
   37  	$rpc_py iscsi_set_options -o 30 -a 16
   38  	
   39  	# RPC framework_wait_init should be blocked, so its process must be existed
   40  	ps $rpc_wait_pid
   41  	
=> 42  	$rpc_py framework_start_init
   43  	echo "iscsi_tgt is listening. Running tests..."
   44  	
   45  	# RPC framework_wait_init should be already returned, so its process must be non-existed
   46  	! ps $rpc_wait_pid
   47  	
     ...

========== Backtrace end ==========
  00:16:52	# xtrace_enable
  00:16:52	# return 0
 00:16:52	# killprocess 3147866
 00:16:52	# '[' -z 3147866 ']'
 00:16:52	# kill -0 3147866
  00:16:52	# ps --no-headers -o comm= 3147866
 00:16:52	# '[' reactor_0 = sudo ']'
 00:16:52	# echo 'killing process with pid 3147866'
killing process with pid 3147866
 00:16:52	# kill 3147866
 00:16:52	# wait 3147866
/var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/test/common/autotest_common.sh: line 480: 3147866 Segmentation fault      (core dumped) $ISCSI_APP --wait-for-rpc
  00:16:52	# trap - ERR
  00:16:52	# print_backtrace
  00:16:52	# [[ ehxBE =~ e ]]
  00:16:52	# xtrace_disable
  00:16:52	# PREV_BASH_OPTS=ehxBE
  00:16:52	# set +x
========== Backtrace start: ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51862.html

**Comment by jimharris** [comment]
Bug scrub: assigned to @tomzawadzki 

Tomek - not sure there's a lot to go on with the two failures so far.  But could you take a look and see if anything pops out?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52620.html

**Comment by tomzawadzki** [comment]
The failure occurs when initializing shared memory with VPP process (`framework_start_init` RPC).
This calls `spdk_vpp_net_framework_init()`, which then crashes deep within `vl_socket_client_init_shm()` VPP lib call.

The logs are not that helpful in determining the reason. Brief look at the SPDK side (vpp sock and tests) didn't help with resolution. Will take a look what happens on VPP side to figure out if this is third-party issue and if there is anything SPDK can do to prevent it.

**Comment by jimharris** [comment]
Here's another instance:
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53028.html

I thought this output was interesting:

[ DPDK EAL parameters: iscsi --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid3084010 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 346:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
 19:00:01	# xtrace_enable
 19:00:01	# ((  i == 0  ))
 19:00:01	# return 0
 19:00:01	# /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/scripts/rpc.py iscsi_set_options -o 30 -a 16
 19:00:02	# /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/scripts/rpc.py framework_start_init
vpp.c:1430:spdk_vpp_net_framework_init: *NOTICE*: Enable VPP session
iscsi_tgt: jsonrpc_server_tcp.c:326: spdk_jsonrpc_server_conn_recv: Assertion `(size_t)offset <= conn->recv_len' failed.
Connection closed with partial response:


  19:00:02	# trap - ERR
  19:00:02	# print_backtrace
  

This makes me think there's some kind of stack/heap corruption in the vpp init process.

**Comment by jimharris** [comment]
vl_api_application_attach_reply_t_handler() looks suspect to me.  I ran a test path through CI, and it shows that mp->n_fds = 2.  So the local fds array is then also 2.  But we clearly access off the end of the array when calling svm_msg_q_set_consumer_eventfd().

But I don't see where we could be *writing* off the end of that array.  So I'm not convinced this is the problem.  I also didn't check if the SESSION_FD_F_MQ_EVENTFD flag is even set, so maybe this code path is never executed.

@tomzawadzki @tkulasek could one of you take a look?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53984.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54872.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57033.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58743.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60507.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3393.html

**Comment by optimistyzy** [comment]
It seems that this issue happens very often..

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9658.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_10078.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_13828.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_14842.html

**Comment by jimharris** [comment]
VPP has been deprecated.
