### ISSUE TITLE
how to read the source code of spdk

### ISSUE THREAD

**Issue by ywbgithub** [spdk/spdk#1093]
hello, everyone, is there any expert of spdk who can give  some suggestions on how to read the spdk source code. Thank you very much.

**Comment by jimharris** [comment]
Hi @ywbgithub,

A good way to learn parts of the SPDK source code is by stepping through code of one of the example applications in gdb.  You should configure SPDK with the --enable-debug flag which will turn off optimizations which will help with the code stepping.

A few example apps that I would recommend:
SPDK NVMe driver:  examples/nvme/hello_world
SPDK block (bdev) layer:  examples/bdev/hello_world
SPDK blobstore: examples/blob/hello_world

If there are other SPDK modules you are interested in, you can always reach out on Slack (find link on https://spdk.io/community/) for suggestions on learning the code and design.

I hope that this is helpful.  I'm going to close this issue, but please feel free to still respond on this issue if you have questions on any of the above.

Thanks,

-Jim
