### ISSUE TITLE
(1) Insert a pcie device that's class id is not "0x010802", (2) replace it with a nvme disk that pcie class id is "0x010802"  (3)the nvme disk cannot be recognition by spdk

### ISSUE THREAD

**Issue by cockroach1136** [spdk/spdk#1094]
Hello all,
    We do a experiment
(1)insert a invalid disk that PCIe class code is not "0x010802"
(2)remove it
(3)insert a disk that PCIe class code is "0x010802"
(4) This disk with class code "0x010802" is no longer recognized by spdk in this disk slot

   We expect the device with class code "0x010802" should be recognized always in this disk slot. 

We spend some time to investigate the hotplug flow in spdk, we found the insert procedure of spdk is
(1)in pci_scan_one function, add pci device to &rte_pci_bus.device_list (this list is sorted)
(2)in  rte_pci_probe_one_driver, using rte_pci_match function to check whether the device can be activated by "spdk_nvme" driver

We found the root cause of this bug is in experiment step 2, the invalid pcie class code disk is inserted, 
and add to  &rte_pci_bus.device_list
But after removing this disk, the dev structure is still in &rte_pci_bus.device_list 
So if we insert a disk with valid class id "0x010802", 
because the list inserting action  didn't modify the class code of existing dev in list, 
so the new inserted device will be skipped by rte_pci_probe_one_driver --> rte_pci_match function

We add the code as below marked by red color in function pci_scan_one.
The action of these codes is just to update the new class code to old, exist dev data structure in device_list.

![image](https://user-images.githubusercontent.com/29791158/70230312-046b6580-1793-11ea-9e9b-f3f5fbfddfb2.png)

We found the behavior is correct, the disk inserted later can be recognized.
So we just want to double confirm that our modification is correct or not ??
Or just a walk around solution??
Please give us advice.
Thank you so much

**Comment by jimharris** [comment]
This is a great test.  This modification looks correct.  Are you interested in creating a patch for this for our DPDK submodule, and working to get it into DPDK upstream?  We can help you with that process.

This is a DPDK issue but since there are SPDK impacts, we should leave this issue open at least until we have a fix in our DPDK submodule.

**Comment by cockroach1136** [comment]
Hello Harris,
   Thank you so much for your quick response.
    But I think my solution is not complete because in function rte_pci_match
   
![image](https://user-images.githubusercontent.com/29791158/70286339-ceb39480-1805-11ea-8bae-36fb87b44cb2.png)

   the function not only check "class_id" field but also check "vender_id", "device_id"... field
   so I must copy all other fileds to exist dev structure, not only class_id.
   But I think maybe the most correct solution is to remove dev structure in list when disk removed, and create a new dev structure when new disk insert. Because the inserting and removing flow is so complex, I cannot finger out when to remove the old dev structure is correct. 

   You mentioned creating a patch for this bug, Does the creating flow is described in this page ?
https://spdk.io/development/#contributing

   I will try it first.    I will consult you if I meet any problem.
Thank you so much

**Comment by jimharris** [comment]
HI @cockroach1136,

I agree.  The entire pci_dev.id structure needs to be copied.  I would suggest just doing this for now.  As you said, removing the dev structure completely might have unknown side effects.  Just copying the id structure for now would be good enough.

The patch contribution flow is described in the link you mentioned.  The only tricky part is that in this case, you will be pushing a patch to the spdk-19.08 branch of the spdk/dpdk repository, not the main spdk repository itself.  So you'd need to add the following to your git config file for the DPDK submodule (found in spdk/.git/modules/dpdk/config):

[remote "review"]
         url = ssh://jimharris@review.gerrithub.io:29418/spdk/dpdk
         push = HEAD:refs/for/spdk-19.08

I use ssh but you can replace that with https.

Or if you would prefer, you can attach a patch here, and someone else can handle getting it pushed to gerrithub.

-Jim

**Comment by cockroach1136** [comment]
Hello Sir,
    The procedure is a little complex for me...:). So please help me to update the patch.
The patch is as attached

diff --git a/drivers/bus/pci/linux/pci.c b/drivers/bus/pci/linux/pci.c

index 43debaa..5ef2e40 100644
--- a/drivers/bus/pci/linux/pci.c
+++ b/drivers/bus/pci/linux/pci.c
@@ -352,6 +352,7 @@
                                if (!rte_dev_is_probed(&dev2->device)) {
                                        dev2->kdrv = dev->kdrv;
                                        dev2->max_vfs = dev->max_vfs;
+                                       memcpy(&dev2->id, &dev->id,sizeof(dev2->id));
                                        pci_name_set(dev2);
                                        memmove(dev2->mem_resource,
                                                dev->mem_resource,

**Comment by jimharris** [comment]
OK.  I'm adding Bug Scrub tag to this issue and we will discuss at next week's meeting.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/dpdk/+/1380

We can close this issue once it's merged into our DPDK submodule.  I'll follow up to get it into DPDK upstream as well.

**Comment by tomzawadzki** [comment]
The patch in question has been merged to DPDK submodule (as well as newer v19.11.2 submodule) [here](https://review.spdk.io/gerrit/c/spdk/dpdk/+/2576).
