### ISSUE TITLE
in case scan for nvme ctrlr failed resources are not released

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1095]
spdk_nvme_probe_internal calls nvme_transport_ctrlr_scan
there might be some ctrlrs already constructed and put into init_ctrlrs list (by nvme_ctrlr_probe)
in case scan failed those ctrlr on init_ctrlrs list are not released.

## Expected Behavior
resources released

## Current Behavior
resources leaked, cannot fallback e.g. to direct connect

## Steps to Reproduce
Issue found by code inspection. I don't have test case to reproduce that.

## Context (Environment including OS version, SPDK version, etc.)
v19.10-rc1

**Comment by jimharris** [comment]
@changpe1 - could you take a look?  We should be able to create a unit test if there's a bug here.

**Comment by changpe1** [comment]
I will write a unit test to cover the following scenario:
There are two NVMe controllers in the host, the first one is attached to the init_ctrlrs list, and the second one return failed due to scan failure.

Is that the case described above?

**Comment by changpe1** [comment]
@jkalwas Patch has been merged, can you verify it fix the issue or not? Thanks.

**Comment by changpe1** [comment]
Closing this issue for now as patch has been merged.
