### ISSUE TITLE
Submitted IO will be NO callback when hot-remove disk in heavy IO situation

### ISSUE THREAD

**Issue by cockroach1136** [spdk/spdk#1097]
Hello Sir,    
   We test  hot remove disk in heavy IO situation, 
Sometimes the submitted IO will never call user callback function. 
In that case our application be stuck.  
After investigate the code, we found a strange place(our code is 19.04)

In function nvme_pcie_qpair_complete_tracker
Last part of this function tries to resend req in queued_req
Notice: the user callback didn't called for req in queue_req list in this time.
![image](https://user-images.githubusercontent.com/29791158/70311078-e281e980-184b-11ea-8f4b-b2c35c23beee.png)

There are no error handling for nvme_qpair_submit_request in these code.
In function nvme_qpair_submit_request,
If the disk is removed, the return value of nvme_qpair_submit_request may be  -ENXIO
![image](https://user-images.githubusercontent.com/29791158/70311209-2674ee80-184c-11ea-87de-9bb64ba5a508.png)

Because of no error handling for nvme_qpair_submit_request return -ENXIO,
The request will be discarded silently. The user callback for this req is not called forever.
That will make out application stuck.

I just check the current master branch of spdk , the code structure of this part is changed, But the problem seems still exist.

Please help us to check it.
Thank you so much.

**Comment by jimharris** [comment]
Thanks for the report.  This is a bug.  We will disposition in next bug scrub meeting.

**Comment by jimharris** [comment]
Bug scrub: Assigned to @changpe1

**Comment by jimharris** [comment]
Hi @cockroach1136 - can you confirm which version of SPDK you are using?

**Comment by changpe1** [comment]
@cockroach1136  I submitted a patch https://review.gerrithub.io/c/spdk/spdk/+/477754 to fix the issue you mentioned above.

**Comment by cockroach1136** [comment]
@changpe1 Thank you so much for your update:)

**Comment by changpe1** [comment]
Patch has been merged, I'm going to close this issue for now.
