### ISSUE TITLE
rocksdb timeouts during overwrite phase

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1099]
Job BlobFS_autotest time outs during `./test/blobfs/rocksdb/rocksdb.sh` when doing overwrite phase of the test.

```
Start overwrite test phase... 19:05:36	# /usr/bin/time taskset 0xFF /var/jenkins/workspace/RBD_BlobFS_tests/BlobFS_autotest/spdk/../rocksdb/db_bench --flagfile=overwrite_flags.txt
```
Example log:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/51547/archive/BlobFS_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_51547.html

**Comment by jimharris** [comment]
I'm wondering if this is related to one of the more general timeout issues we're having with CI.  If I look at the rocksdb log for this overwrite test, it seems to indicate that the test ran to completion (it prints out all of the stats at the end).  Of course it could also be that something hung during shutdown.

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/51547/archive/BlobFS_autotest/rocksdb/overwrite_db_bench.txt

**Comment by jimharris** [comment]
Bug scrub: assigned to @jimharris

**Comment by jimharris** [comment]
Bug scrub: @changpe1 hit this issue while debugging one of the other blobfs issues.  He fixed a deadlock condition with a try lock.  Closing this issue since we believe it's been fixed, and the original issue hasn't been seen for 2+ months.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_10486.html

**Comment by tomzawadzki** [comment]
Closing, as it has not been reported for 2 months now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_21475.html

**Comment by Donaim** [comment]
Reopening because still reproduces ^ (1 case found in 3 months, it seems)

**Comment by changpe1** [comment]
> Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_21475.html

There is no error log in overwrite test case, the overwrite test finished normally, let's keep it open for a while to see if can have more error information to help debugging.

**Comment by tomzawadzki** [comment]
No new reports for a month. Closing.
