### ISSUE TITLE
RPC method not found 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1100]
## Please use the issue tracker only for reporting suspected issues.
I met this kind of issues several times while using "./autotest.sh    autorun-spdk.conf "
this time it blocks at "bdev_crypto_create"
01:47:20       # [[ 0 -eq 0 ]]
 01:47:20       # local crypto_dirver=crypto_aesni_mb
 01:47:20       # tgt_rpc bdev_crypto_create MallocForCryptoBdev CryptoMallocBdev crypto_aesni_mb 0123456789123456
 01:47:20       # /root/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_crypto_create MallocForCryptoBdev CryptoMallocBdev crypto_aesni_mb 0123456789123456
request:
{
  "base_bdev_name": "MallocForCryptoBdev",
  "name": "CryptoMallocBdev",
  "crypto_pmd": "crypto_aesni_mb",
  "key": "0123456789123456",
  "method": "bdev_crypto_create",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"
}
  01:47:20      # on_error_exit tgt_rpc 34
  01:47:20      # set -x
  01:47:20      # set +e
  01:47:20      # print_backtrace
  01:47:20      # [[ hxBE =~ e ]]
  01:47:20      # return 0
  01:47:20      # trap - ERR
  01:47:20      # echo 'Error on tgt_rpc - 34'
Error on tgt_rpc - 34
  01:47:20      # json_config_test_fini
  01:47:20      # timing_enter json_config_test_fini
  01:47:20      # xtrace_disable
  01:47:20      # PREV_BASH_OPTS=hxBE
  01:47:20      # set +x
  01:47:20      # xtrace_enable
  01:47:20      # local ret=0
  01:47:20      # [[ -n '' ]]
  01:47:20      # [[ -n 316412 ]]
  01:47:20      # cleanup_bdev_subsystem_config
  01:47:20      # timing_enter cleanup_bdev_subsystem_config
  01:47:20      # xtrace_disable
  01:47:20      # PREV_BASH_OPTS=hxBE
  01:47:20      # set +x

## Current Behavior
autotest failed for "RPC Method not found"

## Steps to Reproduce
./autotest.sh ~/autorun-spdk.conf
## Context (Environment including OS version, SPDK version, etc.)
commit: bcfb51b1247ddbea47db12dd0319c65feb41052b
Linux fedora31.localdomain 5.3.11-300.fc31.x86_64 #1 SMP Tue Nov 12 19:08:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
maybe use other OS.

**Comment by yidong0635** [comment]
config:
# assign a value of 1 to all of the pertinent tests
SPDK_BUILD_DOC=1
SPDK_BUILD_SHARED_OBJECT=1
SPDK_RUN_CHECK_FORMAT=1
SPDK_RUN_SCANBUILD=1
SPDK_RUN_VALGRIND=1
SPDK_TEST_CRYPTO=1
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_ISCSI=1
SPDK_TEST_ISCSI_INITIATOR=1
SPDK_TEST_NVME=1
SPDK_TEST_NVME_CLI=1
SPDK_TEST_NVMF=1
SPDK_TEST_RBD=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_EVENT=1
SPDK_TEST_BLOBFS=1
SPDK_TEST_PMDK=1
SPDK_TEST_LVOL=1
SPDK_TEST_JSON=1
SPDK_TEST_OCF=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
# doesn't work on vm
SPDK_TEST_IOAT=0
# requires some extra configuration. see TEST_ENV_SETUP_README
SPDK_TEST_VHOST=0
SPDK_TEST_VHOST_INIT=0
# Not configured here
SPDK_RUN_INSTALLED_DPDK=0

**Comment by Comphix** [comment]
Will take a look at this issue.

**Comment by jimharris** [comment]
Thanks @Comphix.  Please work with @yidong0635 to create a smaller test case that reproduces this issue, and then add a more specific title for this issue.

**Comment by yidong0635** [comment]
@jimharris @Comphix , let me to check something firstly, I'm worried about to run "./autotest.sh ~/autorun-spdk.conf" directly is a wrong procedure. need to do "./autorun.sh ~/autorun-spdk.conf" instead.

**Comment by yidong0635** [comment]
I'm going to close this issue. For  code has not been compiled by case.

**Comment by yidong0635** [comment]
use “./autorun.sh ~/autorun-spdk.conf“ hits "bdev_rbd_create"
06:49:21       # /home/yidong/spdk/scripts/rpc.py iscsi_create_portal_group 1 10.0.0.1:3260
 06:49:21       # /home/yidong/spdk/scripts/rpc.py iscsi_create_initiator_group 2 ANY 10.0.0.2/32
  06:49:21      # /home/yidong/spdk/scripts/rpc.py bdev_rbd_create rbd foo 4096
   06:49:21     # trap - ERR
   06:49:21     # print_backtrace
   06:49:21     # [[ hxBE =~ e ]]
   06:49:21     # return 0
 06:49:21       # rbd_bdev='request:
{
  "pool_name": "rbd",
  "rbd_name": "foo",
  "block_size": 4096,
  "method": "bdev_rbd_create",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"
}'
  06:49:21      # trap - ERR
  06:49:21      # print_backtrace
  06:49:21      # [[ ehxBE =~ e ]]
  06:49:21      # xtrace_disable
  06:49:21      # PREV_BASH_OPTS=ehxBE
  06:49:21      # set +x
========== Backtrace start: ==========

in ./test/iscsi_tgt/rbd/rbd.sh:43 -> main()
     ...
   38
   39   timing_exit start_iscsi_tgt
   40
   41   $rpc_py iscsi_create_portal_group $PORTAL_TAG $TARGET_IP:$ISCSI_PORT
   42   $rpc_py iscsi_create_initiator_group $INITIATOR_TAG $INITIATOR_NAME $NETMASK
=> 43   rbd_bdev="$($rpc_py bdev_rbd_create $RBD_POOL $RBD_NAME 4096)"
   44   $rpc_py bdev_get_bdevs
   45   # "Ceph0:0" ==> use Ceph0 blockdev for LUN0
   46   # "1:2" ==> map PortalGroup1 to InitiatorGroup2
   47   # "64" ==> iSCSI queue depth 64
   48   # "-d" ==> disable CHAP authentication
     ...

**Comment by Comphix** [comment]
@yidong0635 , what's the content of "autorun-spdk.conf"? Is that in your first comment?

Also, are you saying that RPC method "bdev_rbd_create" is not found when running the iSCSI Target?

**Comment by yidong0635** [comment]
@Comphix  yes, this time it hits  Method "bdev_rbd_create" not found. I'm still struggling in judging
it's an operation failure or a real bug. But it's autotest.

**Comment by jimharris** [comment]
Is it possible it was built without rbd support?

**Comment by yidong0635** [comment]
it seems exporting some flags but building with that modules.

**Comment by yidong0635** [comment]
I can execute "./test/spdkcli/rbd.sh" successfully on fedora30, but autotest treats this failed to add " config_params+=' --with-rbd'
condition may not right:
if [ -d /usr/include/rbd ] &&  [ -d /usr/include/rados ] && [ $SPDK_TEST_RBD -eq 1 ];

**Comment by yidong0635** [comment]
fedor28 has these folders, but fedora30 and later doesn't have these folders , these may be integrated to somewhere.

**Comment by yidong0635** [comment]
make it clear , librbd and librados have not been installed. this  module has not been compiled, and 
./test/spdkcli/rbd.sh doesn't depend on this, but other tests which  need bdev_rbd_create rpc method depend on this.
and these tests' switch only use "$SPDK_TEST_RBD -eq 1"
that means it was not compiled but still to test it.

**Comment by yidong0635** [comment]
Close this issue, there are lots of dependencies to run cases. And some parts are not compiled if 
don't have include files, but test will continue. And I think the best method  is  let it stay the same as before, otherwise it makes test more complex. Through setting up the environments manually including installing packages.
