### ISSUE TITLE
Unable to start spdk service for NVMeoF with IPv6

### ISSUE THREAD

**Issue by govind-rathod1987** [spdk/spdk#1102]
Unable to start spdk service for NVMeoF with IPv6.

have configured using the nvmf.conf file and after starting the spdk nvmf_tgt service, i see the below error:
[root@localhost nvmf_tgt]# ./nvmf_tgt -c nvmf.conf
Starting SPDK v20.01-pre git sha1 bcfb51b / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid22769 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 344:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
conf.c: 136:spdk_nvmf_read_config_file_tgt_conf: *NOTICE*: The value of ConnectionScheduler is not configured,
we will use RoundRobin as the default scheduler
conf.c: 366:spdk_nvmf_parse_subsystem: *NOTICE*: Subsystem nqn.2016-06.io.spdk:cnode1: missing model number, will use default
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fd78'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fdb9'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fde9'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fdb2'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
conf.c: 366:spdk_nvmf_parse_subsystem: *NOTICE*: Subsystem nqn.2016-06.io.spdk:cnode2: missing model number, will use default
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fd78'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fdb9'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fde9'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
rdma.c:2704:spdk_nvmf_rdma_listen: *ERROR*: getaddrinfo failed: Name or service not known (-2)
nvmf.c: 570:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address 'fdb2'
conf.c: 239:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address

note: switching to IPv4 NW works fine without any issues.

I have attached my nvmf.conf file for reference
[NVMf Target Configuration File.docx](https://github.com/spdk/spdk/files/3939570/NVMf.Target.Configuration.File.docx)

**Comment by AlekseyMarchuk** [comment]
Hi,

Please try to put IPv6 address in `[]` e.g. `Listen RDMA [fd78:b41b:7e5c:ee9e::15]:4420`

**Comment by govind-rathod1987** [comment]
Thanks for your timely response.
It is working and will close the case.
