### ISSUE TITLE
can't run fio plugin with SPDK bdev

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1104]
We run fio plugin with SPDK bdev and got the following ERROR message :
```
Global: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk_bdev, iodepth=32
fio-3.3
Starting 1 thread
Starting SPDK v20.01-pre git sha1 2389caa4f / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid11829 ]
EAL: No available hugepages reported in hugepages-1048576kB
Cannot create lock on device /tmp/spdk_pci_lock_0000:02:00.0, probably process 5381 has claimed it
nvme_pcie.c: 817:nvme_pcie_ctrlr_construct: *ERROR*: could not claim device 0000:02:00.0 (Permission denied)
nvme.c: 428:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:02:00.0
EAL: Requested device 0000:02:00.0 cannot be used
bdev_nvme.c:1756:bdev_nvme_library_init: *ERROR*: NVMe SSD "0000:02:00.0" could not be found.
bdev_nvme.c:1757:bdev_nvme_library_init: *ERROR*: Check PCIe BDF and that it is attached to UIO/VFIO driver.
fio_plugin.c: 413:spdk_fio_setup: *ERROR*: Unable to find bdev with name Global.0.0


Run status group 0 (all jobs):
```
Our test procedures:
1. Setup SPDK
**./scripts/setup.sh**
2. Start the SPDK Target App in the background
**./app/spdk_tgt/spdk_tgt &**
3. Configure an NVMe bdev named Nvme0 using PCI device
**sudo ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:02:00.0**
4. check the bdev devices
```
[
  {
    "name": "Nvme0n1",
    "aliases": [],
    "product_name": "NVMe disk",
    "block_size": 512,
    "num_blocks": 2000409264,
    "uuid": "4ada39f8-ca0d-4897-9190-c9537a65105b",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": true,
      "nvme_io": true
    },
    "driver_specific": {
      "nvme": {
        "pci_address": "0000:02:00.0",
        "trid": {
          "trtype": "PCIe",
          "traddr": "0000:02:00.0"
        },
        "ctrlr_data": {
          "vendor_id": "0x1987",
          "model_number": "PCIe SSD",
          "serial_number": "2F5D079B1AAE00003816",
          "firmware_revision": "ECFM13.1",
          "oacs": {
            "security": 1,
            "format": 1,
            "firmware": 1,
            "ns_manage": 0
          }
        },
        "vs": {
          "nvme_version": "1.3"
        },
        "csts": {
          "rdy": 1,
          "cfs": 0
        },
        "ns_data": {
          "id": 1
        },
        "security": {
          "opal": false
        }
      }
    }
  }
]
```
5. modify bdev.conf and fio config files
bdev.conf.in
```
[Malloc] 
        NumberOfLuns 1
        LunSizeInMB 128 
[Nvme]
        TransportID "trtype:PCIe traddr:0000:02:00.0" NVMe0n1
        RetryCount 4
        TimeoutUsec 0
        AcctionOnTimeout None
        AdminPollRate 100000

```
fio config
```
[Global]
ioengine=/usr/src/spdk/examples/bdev/fio_plugin/fio_plugin
spdk_conf=/usr/src/spdk/examples/bdev/fio_plugin/bdev.conf.in
direct=1
rw=read
rwmixread=100
thread=1
norandommap=1
time_based=1
runtime=300
ramp_time=10
bs=128k
iodepth=32
numjobs=1
percentile_list=99:99.9:99.99:99.999:99.9999:100
```
6. run fio plugin with SPDK bdev
**fio config.fio**

please help to check which procedure is wrong, thanks!

## Context (Environment including OS version, SPDK version, etc.)

OS: ubuntu 19.04
Linux Kernel: 5.4
SPDK: 20.01
DPDK:19.08.0

**Comment by yidong0635** [comment]
please rm -f /tmp/spdk_pci_lock_0000:02:00.0

**Comment by ryderhsu0129** [comment]
> please rm -f /tmp/spdk_pci_lock_0000:02:00.0
Hi yidong,
thanks for your reply.
but no such file spdk_pci_lock_*** on folder /tmp.

**Comment by Comphix** [comment]
Cannot create lock on device /tmp/spdk_pci_lock_0000:02:00.0, probably process 5381 has claimed it

Is process 5381 still running?

ps -ef | grep -i 5381

**Comment by ryderhsu0129** [comment]
> Cannot create lock on device /tmp/spdk_pci_lock_0000:02:00.0, probably process 5381 has claimed it
> 
> Is process 5381 still running?
> 
> ps -ef | grep -i 5381

thanks for your reply.

process 5381 is SPDK target app spdk_tgt, it is still running.
if I close it(kill process) will unable to find bdev, the ERROR message as following:
```
Global: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk_bdev, iodepth=32
fio-3.3
Starting 1 thread
Starting SPDK v20.01-pre git sha1 2389caa4f / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid11380 ]
EAL: No available hugepages reported in hugepages-1048576kB
nvme_opal.c: 900:opal_discovery0_end: *ERROR*: Opal Not Supported.
fio_plugin.c: 413:spdk_fio_setup: *ERROR*: Unable to find bdev with name Global.0.0
```

**Comment by yidong0635** [comment]
please verify the bdev name: Global.0.0 . How this name comes from?

**Comment by ryderhsu0129** [comment]
> please verify the bdev name: Global.0.0 . How this name comes from?

thanks for your reply.

Global.0.0 comes from running fio plugin command line doesn't attach filename,
but if I attached filename same as rpc command creation,
(sudo ./scripts/rpc.py bdev_nvme_attach_controller -b **Nvme0** -t PCIe -a 0000:02:00.0)
then the ERROR message will change as following :
*ERROR*: Unable to find bdev with name **Nvme0**

**Comment by yidong0635** [comment]
you have already claimed  TransportID "trtype:PCIe traddr:0000:02:00.0" NVMe0n1 
and then do this again with "./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:02:00.0" (you can remove  whole line in config file)
and the name are inconsistency.  Nvme0 --> Nvme0n1  is different from NVMe0n1. 
you can use "./scripts/rpc.py get_bdevs" to check the created bdev name.
you can search from test code about rpc procedures .

**Comment by ryderhsu0129** [comment]
> you have already claimed TransportID "trtype:PCIe traddr:0000:02:00.0" NVMe0n1
> and then do this again with "./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:02:00.0" (you can remove whole line in config file)
> and the name are inconsistency. Nvme0 --> Nvme0n1 is different from NVMe0n1.
> you can use "./scripts/rpc.py get_bdevs" to check the created bdev name.
> you can search from test code about rpc procedures .

thanks for your reply.

I have used "./scripts/rpc.py bdev_get_bdevs" to check the created bdev name, 
and also remove the line with claimed TransportID on bdev.conf.in, 
and then I run fio plugin command with created bdev name, 
but ERROR message still indicates unable to find created bdev name.

**Comment by optimistyzy** [comment]
"nvme_pcie.c: 817:nvme_pcie_ctrlr_construct: *ERROR*: could not claim device 0000:02:00.0 (Permission denied)
nvme.c: 428:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:02:00.0"

@ryderhsu0129 What's the user privilege used by your for start the process? Can you make sure that you use the root account. 

And you need to run ./script/setup.py in spdk folder

**Comment by ryderhsu0129** [comment]
> "nvme_pcie.c: 817:nvme_pcie_ctrlr_construct: _ERROR_: could not claim device 0000:02:00.0 (Permission denied)
> nvme.c: 428:nvme_ctrlr_probe: _ERROR_: Failed to construct NVMe controller for SSD: 0000:02:00.0"
> 
> @ryderhsu0129 What's the user privilege used by your for start the process? Can you make sure that you use the root account.
> 
> And you need to run ./script/setup.py in spdk folder

Thanks for your reply.

I make sure that process run by root privilege,
and also run setup.sh before all operations.

**Comment by optimistyzy** [comment]
@ryderhsu0129 Can I ask another questions, can you run ./examples/nvme/identify/identify successfully?

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 Can I ask another questions, can you run ./examples/nvme/identify/identify successfully?

yes, it's work.

**Comment by jimharris** [comment]
Hi @ryderhsu0129,

I have a couple of questions:

1) Do you have the SPDK target running when you run the fio plugin?
2) Can you provide the command line you are using when running nvme/identify?

Thanks,

Jim

**Comment by ryderhsu0129** [comment]
> Hi @ryderhsu0129,
> 
> I have a couple of questions:
> 
> 1. Do you have the SPDK target running when you run the fio plugin?
> 2. Can you provide the command line you are using when running nvme/identify?
> 
> Thanks,
> 
> Jim

Hi Jim,

1. Do you mean SPDK target is NVMe SSD device?If so I have it when run the fio plugin.
2. the command line is ./example/nvme/identify/identify.
ps. If I run the command line after created bdev, error message indicates the same failed reason.
another situation will be normal.

**Comment by optimistyzy** [comment]
@ryderhsu0129 I think that for directly using nvme driver, it is ok. Could you run ./test/bdev/bdevperf/bdevperf and using the same bdev.conf.in, you used:

bdev.conf.in
[Malloc] 
        NumberOfLuns 1
        LunSizeInMB 128 
[Nvme]
        TransportID "trtype:PCIe traddr:0000:02:00.0" NVMe0n1
        RetryCount 4
        TimeoutUsec 0
        AcctionOnTimeout None
        AdminPollRate 100000

And run the following command: 

test/bdev/bdevperf/bdevperf -z -q 8 -o 4096 -w verify -t 10 -c bdev.conf.in 
To  see what happened.

**Comment by optimistyzy** [comment]
@ryderhsu0129 Another thing I found, as Jim stated. Currently you are running SPDK target with fio together to access the same NVMe SSD, though we support the multiple process mode. Do you want to do this test?  If you want to:
1 Use  FIO + SPDK plugin (NVMe/bdev) to test the local NVMe SSD. You do not need to start SPDK tgt.
2 If you want to use FIO + SPDK plugin to test remote NVMe-oF target. The configuration file of FIO bdev plugin should not be same with the target.
3 You just want to test multiple process mode. So you just start the SPDK tgt?  And use FIO + bdev plugin to access the same NVMe SSD.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 Another thing I found, as Jim stated. Currently you are running SPDK target with fio together to access the same NVMe SSD, though we support the multiple process mode. Do you want to do this test? If you want to:
> 1 Use FIO + SPDK plugin (NVMe/bdev) to test the local NVMe SSD. You do not need to start SPDK tgt.
> 2 If you want to use FIO + SPDK plugin to test remote NVMe-oF target. The configuration file of FIO bdev plugin should not be same with the target.
> 3 You just want to test multiple process mode. So you just start the SPDK tgt? And use FIO + bdev plugin to access the same NVMe SSD. According to my mind, if you you want to do this. You cannot run two processes both as the primary process if access the same NVMe SSD. You may need to change one progress into slave mode(e.g., fio + bdev plugin may run as the slave process)

thanks for your reply.
I think my way of thinking are confusing.

1. I just want to use fio + SPDK plugin to test local NVMe SSD, launched the SPDK tgt just want to run rpc.py to create bdev device for test.(looks like rpc command is only useful when SPDK tgt is executed).

As mentioned above, so I tried to run `fio config.fio '--filename=NVMe0n1'` directly with 
bdev.conf.in config :
```
[Malloc]
NumberOfLuns 1
LunSizeInMB 128
[Nvme]
TransportID "trtype:PCIe traddr:0000:02:00.0" NVMe0n1
RetryCount 4
TimeoutUsec 0
AcctionOnTimeout None
AdminPollRate 100000
```
but the error message still indicated that unable to find bdev with name NVMe0n1  

2. I run ./test/bdev/bdevperf/bdevperf and using the same bdev.conf.in,
got the following message:
```
 Starting SPDK v20.01-pre git sha1 bed4cdf6c / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid114281 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 346:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
nvme_opal.c: 900:opal_discovery0_end: *ERROR*: Opal Not Supported.
```

**Comment by optimistyzy** [comment]
@ryderhsu0129 "I just want to use fio + SPDK plugin to test local NVMe SSD, launched the SPDK tgt just want to run rpc.py to create bdev device for test.(looks like rpc command is only useful when SPDK tgt is executed)."
If you want to test this, please:
1 Do not run spdk_tgt, it is not needed.
2 you do not need any rpc.

You can directly run fio with SPDK bdev plugin.

**Comment by jimharris** [comment]
Hi @ryderhsu0129,

In your bdev configuration file, you should use "NVMe0" not "NVMe0n1".  NVMe0 is the name of the controller.  The bdev module will append "n1" for the bdev associated with namespace ID=1.

-Jim

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 "I just want to use fio + SPDK plugin to test local NVMe SSD, launched the SPDK tgt just want to run rpc.py to create bdev device for test.(looks like rpc command is only useful when SPDK tgt is executed)."
> If you want to test this, please:
> 1 Do not run spdk_tgt, it is not needed.
> 2 you do not need any rpc.
> 
> You can directly run fio with SPDK bdev plugin. You step from 1 to 4 is unnecessary.
> 
> LD_PRELOAD=spdk/examples/bdev/fio_plugin/fio_plugin fio fio.conf.
> 
> Fio.conf is the fio.conf you provide, and in fio.conf contains the bdev.conf.in, and you do not need use any step from 1 to 4, which is unnecessary.

@optimistyzy 

I run fio with SPDK bdev plugin directly, and replaced "NVMe0" to "NVMe0n1" in bdev.conf.in file, then specify the filename at end of command line, finally it's work, thanks for your help.

**Comment by ryderhsu0129** [comment]
> Hi @ryderhsu0129,
> 
> In your bdev configuration file, you should use "NVMe0" not "NVMe0n1". NVMe0 is the name of the controller. The bdev module will append "n1" for the bdev associated with namespace ID=1.
> 
> -Jim
@jimharris 

it's work, thanks for your help.

**Comment by jimharris** [comment]
Thanks for the update!
