### ISSUE TITLE
can't run perf with linux aio

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1106]
We run perf tool with linux aio got the following ERROR message:

```
Starting SPDK v20.01-pre git sha1 2389caa4f / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid3614 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
No valid NVMe controllers or AIO devices found
```
We have checked that /dev/nvme01n have been created, and then
our perception is that we can use this instruction directly but failed:
**./perf -w read -o 4096 -q 32 -t 300 -s 1024 /dev/nvme0n1**

please help to check which procedure is wrong, thanks!

ps. we can run perf with spdk nvme after execute setup.sh

**Comment by glodfish-zg** [comment]
Please try this patch: https://review.gerrithub.io/c/spdk/spdk/+/477449

**Comment by ryderhsu0129** [comment]
> Please try this patch: https://review.gerrithub.io/c/spdk/spdk/+/477449

thanks for your reply.
It's work now!
