### ISSUE TITLE
[nightly] test/bdev/blockdev.sh fails due to sgdisk not installed on test VMs

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1107]
test/bdev/blockdev.sh started failing in nightly test runs due to changes done in 5170ac8d83be3b404dc8c3285bf85f4aa5c31dd4.

Part of test configuration was changed to use GPT nvme bdevs instead of using a nvme bdev directly. Some of the VMs do not have sgdisk installed so gpt partition is not created, thus resulting in Nvme0n1p1 being not present.

Affected systems in CI:
- CentOS7 
- Ubuntu16 
- FreeBSD 

## Current Behavior
test/bdev/blockdev.sh tests fail @ $rootdir/examples/bdev/hello_world/hello_bdev -c $testdir/bdev.conf -b Nvme0n1p1 because Nvme0n1p1 is not created.

## Possible Solution
1. Add sgdisk as test dependency in test/common/config/vm_setup.sh
2.  Modify part_dev_by_gpt() to fail if sgdisk is not present in the system, as it would be a test dependency now. Fail if not present because we do not want to "mask" not run test cases.
3. Add if-branch for FreeBSD in part_dev_by_gpt, otherwise it won't do anything for FreeBSD systems.

## Steps to Reproduce
1. Download latest SPDK (7561d1b5c2e43cbd2f2542fb7fccb49fd8e12824 at the moment of creating this issue)
2. Remove or mask sgdisk in your system
3. Run blockdev.sh test in nightly mode:
```
sudo -E SPDK_TEST_RBD=0 RUN_NIGHTLY=1 test/bdev/blockdev.sh
```

## Context (Environment including OS version, SPDK version, etc.)
Linux ubuntu16_04 4.4.0-166-generic #195-Ubuntu
FreeBSD freebsd_vm 11.2-RELEASE-p9 FreeBSD 11.2-RELEASE-p9
Linux centos7_vm 3.10.0-957.10.1.el7.x86_64
SPDK 7561d1b5c2e43cbd2f2542fb7fccb49fd8e12824 

Related failures:
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_1136.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_1135.html

**Comment by tomzawadzki** [comment]
Besides the noted down solutions by @karlatec, one that is more immediate would be to move hello_bdev before the part_dev_by_gpt(). This would need to align with yet unmerged test changes, but could be worth considering.

@Seth5141 Can you please take a look ?

**Comment by Seth5141** [comment]
@tomzawadzki Possible fix at https://review.gerrithub.io/c/spdk/spdk/+/477611. This preserves the behavior of blockdev.sh where we weren't really requiring GPT in the past but allows us to report with more granularity whether we are running GPT tests. This gives us the best of both worlds. If the GPT tests weren't run, that will get reported in the supplemental logs. Just waiting for it to run through with the nightly flag set.

**Comment by Seth5141** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/477612 shows this working properly on the freebsd tests. You can go to https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/52438/archive/freebsd_autotest/build.log and look for START TEST CASE bdev_hello_world to see therelevant portion of the log.

**Comment by changpe1** [comment]
Patch has been merged, I'm going to close this issue for now.
