### ISSUE TITLE
failure in nvme_smartctl_cuse tests.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1111]
## Current Behavior
This failed on autotest-per-patch on an unrelated test.
Relevant log below
~~~
json.user_capacity.blocks = 5242880;
json.user_capacity.bytes = 21474836480;'
  00:18:21	# true
 00:18:21	# DIFF_SMART_JSON='json.local_time.asctime = "Sat Dec 14 00:18:06 2019 CET";
json.local_time.time_t = 1576279086;
json.nvme_smart_health_information_log.data_units_read = 36418867200;
json.nvme_smart_health_information_log.host_reads = 2861244;
json.nvme_smart_health_information_log.power_on_hours = 23;
json.power_on_time.hours = 23;'
  00:18:21	# grep -v 'json\.nvme_smart_health_information_log\.\|json\.local_time\.\|json\.temperature\.'
 00:18:21	# ERR_SMART_JSON='json.power_on_time.hours = 23;'
 00:18:21	# '[' -n 'json.power_on_time.hours = 23;' ']'
 00:18:21	# echo 'Wrong values for: json.power_on_time.hours = 23;'
Wrong values for: json.power_on_time.hours = 23;
 00:18:21	# return 1
test/nvme/spdk_smartctl_cuse.sh: line 57: return: can only `return' from a function or sourced script
  00:18:21	# trap - ERR
  00:18:21	# print_backtrace
  00:18:21	# [[ ehxBE =~ e ]]
  00:18:21	# xtrace_disable
  00:18:21	# '[' no '!=' yes ']'
  00:18:21	# PREV_BASH_OPTS=ehxBE
  00:18:21	# [[ ehxBE == *\x* ]]
  00:18:21	# XTRACE_DISABLED=yes
  00:18:21	# set +x
========== Backtrace start: ==========

in test/nvme/spdk_smartctl_cuse.sh:57 -> main()
     ...
   52  	# Mask values can change
   53  	ERR_SMART_JSON=$( grep -v "json\.nvme_smart_health_information_log\.\|json\.local_time\.\|json\.temperature\." <<< $DIFF_SMART_JSON || true )
   54  	
   55  	if [ -n "$ERR_SMART_JSON" ] ; then
   56  		echo "Wrong values for: $ERR_SMART_JSON"
=> 57  		return 1
   58  	fi
   59  	
   60  	CUSE_SMART_ERRLOG=$( ${SMARTCTL_CMD} -l error /dev/spdk/nvme0 )
   61  	if [ "$CUSE_SMART_ERRLOG" != "$KERNEL_SMART_ERRLOG" ]; then
   62  		echo "Wrong values in NVMe Error log"
     ...

========== Backtrace end ==========
~~~

## Possible Solution
Not sure yet, I haven't investigated that far.

## Steps to Reproduce
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/52757/archive/nvme_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52757.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52767.html

**Comment by yidong0635** [comment]
found that there are two scripts: whole file uses "return 1" , maybe should use  "exit 1".
spdk_nvme_cli_cuse.sh  and  spdk_smartctl_cuse.sh.

**Comment by yidong0635** [comment]
I just saw this issue was so obvious:
 _return: can only `return' from a function or sourced script_
so submit this patch : https://review.gerrithub.io/c/spdk/spdk/+/478014

**Comment by jimharris** [comment]
grep on line 53 also needs to ignore changes to json.power_on_time.hours - that is what caused the script to go down the path with the incorrect return

**Comment by yidong0635** [comment]
@jimharris  thanks ,  add json.power_on_time.hours to "grep -v". Hope that I got the ideas.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_52844.html

**Comment by jimharris** [comment]
Patch merged.
