### ISSUE TITLE
19.10 failed to connect nvmeof via softroce but 19.07 can

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1113]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

wayne@ubuntu:~/spdk1910/spdk/examples/nvme/perf$ sudo ./perf -q 1 -w read -o 4096 -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.10.129 trsvcid:4420'
Starting SPDK v19.10 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid89375 ]
EAL: No available hugepages reported in hugepages-1048576kB
Wayne Enter int: 1
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.10.129:4420: testnqn
Attached to NVMe over Fabrics controller at 192.168.10.129:4420: testnqn
Associating RDMA (addr:192.168.10.129 subnqn:testnqn) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
nvme_rdma.c: 769:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c: 999:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c: 364:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_create_io_qpair() failed
ERROR: spdk_nvme_ctrlr_alloc_io_qpair failed
ERROR: init_ns_worker_ctx() failed
========================================================
                                                                                          Latency(us)
Device Information                                   :       IOPS      MiB/s    Average        min        max
./perf: errors occured

but my old 19.07 code works fine as below. I see connect code has some change

wayne@ubuntu:~/spdk/examples/nvme/perf$ sudo ./perf -q 1 -w read -o 4096 -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.10.129 trsvcid:4420'
[sudo] password for wayne: 
Starting SPDK v19.07-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid89592 ]
EAL: No free hugepages reported in hugepages-1048576kB
Enter int: 1
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.10.129:4420: testnqn
Attached to NVMe over Fabrics controller at 192.168.10.129:4420: testnqn
Associating RDMA (addr:192.168.10.129 subnqn:testnqn) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                          Latency(us)
Device Information                                   :       IOPS      MiB/s    Average        min        max
RDMA (addr:192.168.10.129 subnqn:testnqn) from core 0:   10596.80      41.39      94.31      61.89   11921.14
========================================================
Total                                                :   10596.80      41.39      94.31      61.89   11921.14

## Expected Behavior
19.10 can works out with softroce's nvmeof target too.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by yidong0635** [comment]
I use VM fedora31 ,SoftRoce, and  with the latest code.   run tests without error.
`rxe_cfg start`
[root@fedora31 spdk]#` rxe_cfg status`
  Name  Link  Driver  Speed  NMTU  IPv4_addr  RDEV  RMTU
  eth0  yes   e1000          1500  10.0.2.15  rxe0  1024  (3)

```
./configure --with-rdma
./scripts/setup.sh
./test/nvmf/nvmf.sh --transport=rdma
```
[perf.txt](https://github.com/spdk/spdk/files/3972063/perf.txt)

**Comment by tomzawadzki** [comment]
[Bug scrub]: @gwnet Can you provide bit more details on the environment (OS/kernel/SoftRoce versions) ?

**Comment by gwnet** [comment]
I use Ubuntu 18.04 installed on VMware workstation 15. use softroce to configure kernel nvmeof target, then use spdk19.10 to connect it. failed. on the same machine, the 19.07pre version works fine can connect the same nvmeof kernel target

**Comment by yidong0635** [comment]
I will check this onUbuntu with kernel target.

**Comment by yidong0635** [comment]
Switch  branches between 19.10 and 19.07 :
./test/nvmf/host/perf.sh --transport=rdma. 
test without error on ubuntu 18.
maybe there're some dependencies needed. 
```
 /home/storage/yidong/spdk/examples/nvme/perf/perf -q 128 -o 262144 -w randrw -M 50 -t 2 -r 'trtype:rdma adrfam:IPv4 traddr:192.168.56.2 trsvcid:4420'
Starting SPDK v19.10 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid30888 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.56.2:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.56.2:4420: nqn.2016-06.io.spdk:cnode1
controller IO queue size 128 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
controller IO queue size 128 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
WARNING: Some requested NVMe devices were skipped
Associating RDMA (addr:192.168.56.2 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 0
Associating RDMA (addr:192.168.56.2 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                                           Latency(us)
Device Information                                                    :       IOPS      MiB/s    Average        min        max
RDMA (addr:192.168.56.2 subnqn:nqn.2016-06.io.spdk:cnode1) from core 0:    1630.00     407.50   79855.12   36178.13  117087.73
RDMA (addr:192.168.56.2 subnqn:nqn.2016-06.io.spdk:cnode1) from core 0:    1678.50     419.62   76233.58   10419.65  105065.05
========================================================
Total                                                                 :    3308.50     827.12   78017.80   10419.65  117087.73

 00:26:24       # sync
 00:26:24       # /home/storage/yidong/spdk/scripts/rpc.py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
 00:26:24       # '[' 0 -eq 1 ']'
 00:26:24       # trap - SIGINT SIGTERM EXIT
 00:26:24       # nvmftestfini
 00:26:24       # nvmfcleanup
 00:26:24       # sync
 00:26:24       # set +e
 00:26:24       # for i in {1..20}
 00:26:24       # modprobe -v -r nvme-rdma
rmmod nvme_rdma
rmmod nvme_fabrics
 00:26:24       # modprobe -v -r nvme-fabrics
 00:26:24       # set -e
 00:26:24       # return
 00:26:24       # killprocess 30825
 00:26:24       # '[' -z 30825 ']'
 00:26:24       # kill -0 30825
  00:26:24      # ps --no-headers -o comm= 30825
 00:26:24       # '[' reactor_0 = sudo ']'
 00:26:24       # echo 'killing process with pid 30825'
killing process with pid 30825
 00:26:24       # kill 30825
 00:26:24       # wait 30825
 00:26:27       # '[' '' == iso ']'
 00:26:27       # timing_exit perf
 00:26:27       # xtrace_disable
 00:26:27       # PREV_BASH_OPTS=ehxBE
 00:26:27       # set +x
 00:26:27       # xtrace_enable
```
you can use autotest which can solve the dependencies.

**Comment by benlwalker** [comment]
This probably isn't the root cause, but can you re-test using this patch? https://review.gerrithub.io/c/spdk/spdk/+/478638

**Comment by yidong0635** [comment]
@gwnet  Can you verify this on your side with Ben's patch? I verified this on my side, It's ok.

**Comment by jimharris** [comment]
[Bug scrub] We are not seeing any issues with softroce w/ 19.10 - it's being used extensively in the test pool.  @gwnet - please reopen or reply on this thread if you still see an issue.
