### ISSUE TITLE
build timeout due to connection timeout

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1114]
Submit  a new issue, I'm not sure if  it's the same as other one.
per-patch test failed as :
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/53119/archive/ubuntu16_autotest/build.log

 06:46:14	$ PREV_BASH_OPTS=
 06:46:14	$ xtrace_enable
sudo: unable to resolve host ubuntu16_04: Connection timed out
Build timed out (after 10 minutes). Marking the build as failed.
Build was aborted
[PostBuildScript] - Executing post build scripts.
[ubuntu16_autotest] $ /bin/sh -xe /tmp/jenkins9134077456684529813.sh

#### Context (Environment including OS version, SPDK version, etc.)
commit 82f60376ae5ae6145bf972c69992f694f54c50b8
ubuntu16

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53119.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54716.html

**Comment by jimharris** [comment]
Closing this issue.  This looks like it was a temporary problem with the ubuntu VM that hasn't been seen again.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58590.html
