### ISSUE TITLE
Socket was not freed when starting RPC client autotest

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1115]
https://d3uor3w1civ2bt.cloudfront.net/public_build/autotest-per-patch_455.html

**Comment by yidong0635** [comment]
rpc.c: 181:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.

**Comment by shuhei-matsumoto** [comment]
@yidong0635 and all

This was my mistake.  This error was from new CI.  Karol taught me on slack. Close this for now.

**Comment by shuhei-matsumoto** [comment]
Please close again if I'm wrong.
This error was observed in CI.
https://ci.spdk.io/results/autotest-per-patch/builds/5384/archive/ubuntu16-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5384.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5386.html

**Comment by optimistyzy** [comment]
@shuhei-matsumoto  Did not see this Intermittent issue more than 3 months in our CI pool, Let's close this issue and if the same issue happens, Let's open it again.
