### ISSUE TITLE
Autotest timeout on ubuntu 18

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1117]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53125.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53127.html

**Comment by shuhei-matsumoto** [comment]
Sorry, Jin's code base looks two days ago and is not the latest. Close for now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @changpe1. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_53146.html
