### ISSUE TITLE
Nvmf: Make session/connection information accessible through public API

### ISSUE THREAD

**Issue by PepperJo** [spdk/spdk#112]
I have not found a way to retrieve any information about connections on connect/disconnect callbacks for spdk_nvmf_create_subsystem. It would be nice If one could retrieve the host or if already connected, the session on the connect callback and on disconnect the session the connection belongs to respectively.

**Comment by dverkamp-intel** [comment]
Currently, the connect and disconnect callbacks from spdk_nvmf_create_subsystem() are just intended as hooks for the application to provide cross-thread message passing to lib/nvmf.  The application shouldn't need to know anything about the actual connection aside from which core is handling it; all of the connection information is encapsulated in the spdk_nvmf_conn structure inside the library.

That said, we can add new APIs to get information about the connections and sessions if the application wants to inspect more details about the connection to make a decision on which core to use.

**Comment by PepperJo** [comment]
I agree that the application does not necessarily need to know about the connections but it is a nice to have feature. Basically what I want to know in my target application for statistics and logging purposes is:

- Who connected? E.g. by letting spdk_nvmf_handle_connect return the spdk_nvmf_conn and provide a function to get this information
- Is there already a session this connection request belongs to? E.g. by querying the session via the spdk_nvmf_conn as above
- For disconnect functions to query the connection as above

Regards,
Jonas

**Comment by benlwalker** [comment]
The user is now notified via callback on each new connection, as of SPDK 18.01. If there are additional requests for information about the connections, please let us know via another issue. Thanks!

**Comment by PepperJo** [comment]
Great. This is sufficient for me. Thanks!
