### ISSUE TITLE
[fio plugin]How to specify the block size and I/O size correspondingly

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1120]
I want to run fio plugin with metadata, according to the instructions on this page
https://github.com/spdk/spdk/tree/master/examples/nvme/fio_plugin 

![image](https://user-images.githubusercontent.com/58720141/71161857-1a921f00-2285-11ea-90cf-92eb9ea7a227.png)

fio plugin can specify block size include metadata using field **bs**, but according to my understanding it was originally to specify the I/O size, how do I to specify the block size and I/O size correspondingly?
please help to clarify it, thanks!

**Comment by changpe1** [comment]
@ryderhsu0129 As the document says, the block size should include data and metadata size, but this is only for the DIF mode, if you formatted your drive with DIX mode, the block size should not include the metadata size.

DIF mode means extended LAB format, the metadata comes after the data, DIX means separate metadata buffer, the metadata is in a different data buffer.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 As the document says, the block size should include data and metadata size, but this is only for the DIF mode, if you formatted your drive with DIX mode, the block size should not include the metadata size.
> 
> DIF mode means extended LBA format, the metadata comes after the data, DIX means separate metadata buffer, the metadata is in a different data buffer.

@changpe1 
thanks for your reply.

We understand the block size definition of document says, but bs field uesd to specify the I/O size per I/O operation on general fio, if bs field used to specify block size on fio plugin, we want to know how do we specify the I/O size per operation.

**Comment by changpe1** [comment]
> > @ryderhsu0129 As the document says, the block size should include data and metadata size, but this is only for the DIF mode, if you formatted your drive with DIX mode, the block size should not include the metadata size.
> > DIF mode means extended LBA format, the metadata comes after the data, DIX means separate metadata buffer, the metadata is in a different data buffer.
> 
> @changpe1
> thanks for your reply.
> 
> We understand the block size definition of document says, but bs field uesd to specify the I/O size per I/O operation on general fio, if bs field used to specify block size on fio plugin, we want to know how do we specify the I/O size per operation.

If your drive was 512 + 8 format, for the I/O size if you want to test 4KiB, so the bs field should be 520 * 8.

**Comment by ryderhsu0129** [comment]
> > > @ryderhsu0129 As the document says, the block size should include data and metadata size, but this is only for the DIF mode, if you formatted your drive with DIX mode, the block size should not include the metadata size.
> > > DIF mode means extended LBA format, the metadata comes after the data, DIX means separate metadata buffer, the metadata is in a different data buffer.
> > 
> > 
> > @changpe1
> > thanks for your reply.
> > We understand the block size definition of document says, but bs field uesd to specify the I/O size per I/O operation on general fio, if bs field used to specify block size on fio plugin, we want to know how do we specify the I/O size per operation.
> 
> If your drive was 512 + 8 format, for the I/O size if you want to test 4KiB, so the bs field should be 520 * 8.

@changpe1 
thanks!
we want to confirm as you said, if we set bs field to 520*8, that is different with set bs to 4k?

**Comment by changpe1** [comment]
> > > > @ryderhsu0129 As the document says, the block size should include data and metadata size, but this is only for the DIF mode, if you formatted your drive with DIX mode, the block size should not include the metadata size.
> > > > DIF mode means extended LBA format, the metadata comes after the data, DIX means separate metadata buffer, the metadata is in a different data buffer.
> > > 
> > > 
> > > @changpe1
> > > thanks for your reply.
> > > We understand the block size definition of document says, but bs field uesd to specify the I/O size per I/O operation on general fio, if bs field used to specify block size on fio plugin, we want to know how do we specify the I/O size per operation.
> > 
> > 
> > If your drive was 512 + 8 format, for the I/O size if you want to test 4KiB, so the bs field should be 520 * 8.
> 
> @changpe1
> thanks!
> we want to confirm as you said, if we set bs field to 520*8, that is different with set bs to 4k?

Have a try, let me know if you get further issue.
