### ISSUE TITLE
can't run fio plugin with SPDK nvme on local NVMe SSD

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1121]
We want to run fio plugin with SPDK nvme on two local NVMe SSDs, 
one is formatted NTFS by ubuntu and run fio plugin successfully.
the other want to be used evaluate performance of protection information mechanism(metadata),
so we create specific namespace and formatted it to support protection information.
The following is our procedure:

```
1. nvme create-ns /dev/nvme0 -s 1562824368 -c 1562824368 -f 0x11 -d 0x01 -m 0
2. nvme attach-ns /dev/nvme0 -n 1 -c 0
3. nvme reset /dev/nvme0
4. nvme format /dev/nvme0n1 -l 1 -i 1 -p 0 -m 1
```

and then we can see nvme0n1 on /dev and  run general fio successfully,
but we got the error when run fio plugin on same SSD, the message is

```
Global: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=32
fio-3.3
Starting 1 thread
Starting SPDK v20.01-pre git sha1 bed4cdf6c / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4179 ]
EAL: No available hugepages reported in hugepages-1048576kB
nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
fio_plugin.c: 495:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
Global: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:953, func=total_file_size, error=Invalid argument


Run status group 0 (all jobs):
```

we have no idea that use same test environment but execution fails,
please help to check which procedure is wrong, thanks!

**Comment by changpe1** [comment]
@ryderhsu0129 what's your drive's model ? Can you run the examples/nvme/identify and parse the log message here for the failed drive.  Alexey reported that some drives reported that can support SGL feature but only for the I/O queues, and this definitely is a firmware bug, but we will have a workaround in SPDK, here is the patch https://review.gerrithub.io/c/spdk/spdk/+/478320, I'm not sure it's the same bug, but you can list your identify log first.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 what's your drive's model ? Can you run the examples/nvme/identify and parse the log message here for the failed drive. Alexey reported that some drives reported that can support SGL feature but only for the I/O queues, and this definitely is a firmware bug, but we will have a workaround in SPDK, here is the patch https://review.gerrithub.io/c/spdk/spdk/+/478320, I'm not sure it's the same bug, but you can list your identify log first.

@changpe1 
thanks for your reply.
our drive model is SAMSUNG MZWLL800HEHP-00003.
I run examples/nvme/identify and got similar error message :

```
nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
spdk_nvme_probe() failed
```

**Comment by changpe1** [comment]
> > @ryderhsu0129 what's your drive's model ? Can you run the examples/nvme/identify and parse the log message here for the failed drive. Alexey reported that some drives reported that can support SGL feature but only for the I/O queues, and this definitely is a firmware bug, but we will have a workaround in SPDK, here is the patch https://review.gerrithub.io/c/spdk/spdk/+/478320, I'm not sure it's the same bug, but you can list your identify log first.
> 
> @changpe1
> thanks for your reply.
> our drive model is SAMSUNG MZWLL800HEHP-00003.
> I run examples/nvme/identify and got similar error message :
> 
> ```
> nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
> nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
> nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
> nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
> nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
> spdk_nvme_probe() failed
> ```

Then the above patch can fix your issue, you can apply that patch for now. We will merge that patch soon.

**Comment by ryderhsu0129** [comment]
> > > @ryderhsu0129 what's your drive's model ? Can you run the examples/nvme/identify and parse the log message here for the failed drive. Alexey reported that some drives reported that can support SGL feature but only for the I/O queues, and this definitely is a firmware bug, but we will have a workaround in SPDK, here is the patch https://review.gerrithub.io/c/spdk/spdk/+/478320, I'm not sure it's the same bug, but you can list your identify log first.
> > 
> > 
> > @changpe1
> > thanks for your reply.
> > our drive model is SAMSUNG MZWLL800HEHP-00003.
> > I run examples/nvme/identify and got similar error message :
> > ```
> > nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
> > nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
> > nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
> > nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
> > nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
> > spdk_nvme_probe() failed
> > ```
> 
> Then the above patch can fix your issue, you can apply that patch for now. We will merge that patch soon.

@changpe1 

We used the patch but same error message still happened :

```
Starting SPDK v20.01-pre git sha1 bed4cdf6c / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid187156 ]
EAL: No available hugepages reported in hugepages-1048576kB
nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
fio_plugin.c: 495:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
Global: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:953, func=total_file_size, error=Invalid argument


Run status group 0 (all jobs):
```

**Comment by changpe1** [comment]
> > > > @ryderhsu0129 what's your drive's model ? Can you run the examples/nvme/identify and parse the log message here for the failed drive. Alexey reported that some drives reported that can support SGL feature but only for the I/O queues, and this definitely is a firmware bug, but we will have a workaround in SPDK, here is the patch https://review.gerrithub.io/c/spdk/spdk/+/478320, I'm not sure it's the same bug, but you can list your identify log first.
> > > 
> > > 
> > > @changpe1
> > > thanks for your reply.
> > > our drive model is SAMSUNG MZWLL800HEHP-00003.
> > > I run examples/nvme/identify and got similar error message :
> > > ```
> > > nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
> > > nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
> > > nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
> > > nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
> > > nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
> > > spdk_nvme_probe() failed
> > > ```
> > 
> > 
> > Then the above patch can fix your issue, you can apply that patch for now. We will merge that patch soon.
> 
> @changpe1
> 
> We used the patch but same error message still happened :
> 
> ```
> Starting SPDK v20.01-pre git sha1 bed4cdf6c / DPDK 19.08.0 initialization...
> [ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid187156 ]
> EAL: No available hugepages reported in hugepages-1048576kB
> nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
> nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
> nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
> nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
> nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
> fio_plugin.c: 495:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
> Global: you need to specify size=
> fio: pid=0, err=22/file:filesetup.c:953, func=total_file_size, error=Invalid argument
> 
> 
> Run status group 0 (all jobs):
> ```

Did you re-compile the fio as well as SPDK?

**Comment by ryderhsu0129** [comment]
> > > > > @ryderhsu0129 what's your drive's model ? Can you run the examples/nvme/identify and parse the log message here for the failed drive. Alexey reported that some drives reported that can support SGL feature but only for the I/O queues, and this definitely is a firmware bug, but we will have a workaround in SPDK, here is the patch https://review.gerrithub.io/c/spdk/spdk/+/478320, I'm not sure it's the same bug, but you can list your identify log first.
> > > > 
> > > > 
> > > > @changpe1
> > > > thanks for your reply.
> > > > our drive model is SAMSUNG MZWLL800HEHP-00003.
> > > > I run examples/nvme/identify and got similar error message :
> > > > ```
> > > > nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
> > > > nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
> > > > nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
> > > > nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
> > > > nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
> > > > spdk_nvme_probe() failed
> > > > ```
> > > 
> > > 
> > > Then the above patch can fix your issue, you can apply that patch for now. We will merge that patch soon.
> > 
> > 
> > @changpe1
> > We used the patch but same error message still happened :
> > ```
> > Starting SPDK v20.01-pre git sha1 bed4cdf6c / DPDK 19.08.0 initialization...
> > [ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid187156 ]
> > EAL: No available hugepages reported in hugepages-1048576kB
> > nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
> > nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
> > nvme_ctrlr.c:1302:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
> > nvme.c: 453:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:af:00.0
> > nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:af:00.0 in failed state.
> > fio_plugin.c: 495:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
> > Global: you need to specify size=
> > fio: pid=0, err=22/file:filesetup.c:953, func=total_file_size, error=Invalid argument
> > 
> > 
> > Run status group 0 (all jobs):
> > ```
> 
> Did you re-compile the fio as well as SPDK?

I have tried to clean build and re-compiled SPDK :
make clean
./configure
make

and check the nvme_pci.o is up-to-date.

**Comment by changpe1** [comment]
@ryderhsu0129 Can you run the examples/nvme/identify with that patch?

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 Can you run the examples/nvme/identify with that patch?

@changpe1 
We re-run `./configure --with-fio=/usr/src/fio` and re-compile, we can run fio plugin successfully,
can you help explain the reason?we have no ideal about this result.

**Comment by changpe1** [comment]
> > @ryderhsu0129 Can you run the examples/nvme/identify with that patch?
> 
> @changpe1
> We re-run `./configure --with-fio=/usr/src/fio` and re-compile, we can run fio plugin successfully,
> can you help explain the reason?we have no ideal about this result.

It's your drive's firmware bug, we have a workaround fix in SPDK.

**Comment by ryderhsu0129** [comment]
@changpe1 
We run fio plugin with the patch, but the report seems doesn't perform any I/O:

```
Global: (g=0): rw=read, bs=(R) 520B-520B, (W) 520B-520B, (T) 520B-520B, ioengine=spdk, iodepth=32
fio-3.3
Starting 1 thread
Starting SPDK v20.01-pre git sha1 bed4cdf6c / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4069 ]
EAL: No available hugepages reported in hugepages-1048576kB
PI type1 enabled with extended lba
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:191 nsid:1 lba:0 len:1
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:1 cid:191 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
Global: No I/O performed by spdk, perhaps try --debug=io option for details?
fio: pid=4105, err=14/file:ioengines.c:337, func=td_io_queue, error=Bad address

Global: (groupid=0, jobs=1): err=14 (file:ioengines.c:337, func=td_io_queue, error=Bad address): pid=4105: Fri Dec 20 15:43:10 2019
  cpu          : usr=0.00%, sys=0.00%, ctx=1, majf=1, minf=7
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=50.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=1,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):



```

our fio config file as follow, the bs field no matter what value we set, we will get the results above:

```
[Global]
ioengine=/usr/src/spdk/examples/nvme/fio_plugin/fio_plugin
direct=1
rw=read
rwmixread=100
thread=1
norandommap=1
time_based=1
runtime=300
ramp_time=10
bs=520*8
pi_act=0
pi_chk=GUARD
iodepth=32
numjobs=1
percentile_list=99:99.9:99.99:99.999:99.9999:100
```

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 Can you run the examples/nvme/identify with that patch?

we run examples/nvme/identify has some error in the beginning:

```
Entry: 253
Error Count:            0x327
Submission Queue Id:    0x0
Command Id:             0x3
Phase Bit:              0
Status Code:            0x1c
Status Code Type:       0x1
Do Not Retry:           0
Error Location:         0x0
LBA:                    0x0
Namespace:              0x1
Vendor Log Page:        0x0
-----------
Entry: 254
Error Count:            0x326
Submission Queue Id:    0x0
Command Id:             0x3
Phase Bit:              0
Status Code:            0x1c
Status Code Type:       0x1
Do Not Retry:           0
Error Location:         0x0
LBA:                    0x0
Namespace:              0x1
Vendor Log Page:        0x0
-----------
Entry: 255
Error Count:            0x325
Submission Queue Id:    0x0
Command Id:             0x3
Phase Bit:              0
Status Code:            0x1c
Status Code Type:       0x1
Do Not Retry:           0
Error Location:         0x0
LBA:                    0x0
Namespace:              0x1
Vendor Log Page:        0x0

Arbitration
===========
Arbitration Burst:           8

Power Management
================
Number of Power States:      1
Current Power State:         Power State #0
Power State #0:  Max Power:  25.00 W
Non-Operational Permissive Mode: Not Supported

Health Information
==================
Critical Warnings:
  Available Spare Space:     OK
  Temperature:               OK
  Device Reliability:        OK
  Read Only:                 No
  Volatile Memory Backup:    OK
Current Temperature:         313 Kelvin (40 Celsius)
Temperature Threshold:       351 Kelvin (78 Celsius)
Available Spare:             100%
Available Spare Threshold:   10%
Life Percentage Used:        0%
Data Units Read:             85302042
Data Units Written:          121330741
Host Read Commands:          1322080002
Host Write Commands:         1599817750
Controller Busy Time:        1724 minutes
Power Cycles:                4811
Power On Hours:              2036 hours
Unsafe Shutdowns:            187
Unrecoverable Media Errors:  498
Lifetime Error Log Entries:  1060
Warning Temperature Time:    810 minutes
Critical Temperature Time:   0 minutes
Temperature Sensor 1:        313 Kelvin (40 Celsius)
Temperature Sensor 2:        313 Kelvin (40 Celsius)
Temperature Sensor 3:        306 Kelvin (33 Celsius)

Number of Queues
================
Number of I/O Submission Queues:      128
Number of I/O Completion Queues:      128

Active Namespaces
=================
Namespace ID:1
Deallocate:                            Supported
Deallocated/Unwritten Error:           Not Supported
Deallocated Read Value:                Unknown
Deallocate in Write Zeroes:            Not Supported
Deallocated Guard Field:               0xFFFF
Flush:                                 Not Supported
Reservation:                           Supported
End-to-End Data Protection:            Supported
Protection Type:                       Type1
Protection Information Transferred as: Last 8 Bytes
Metadata Transferred as:               Extended Data LBA
Namespace Sharing Capabilities:        Private
Size (in LBAs):                        1562824368 (1490M)
Capacity (in LBAs):                    1562824368 (1490M)
Utilization (in LBAs):                 1562824368 (1490M)
NGUID:                                 334843304B5010970025385800000001
EUI64:                                 002538E581B00CD2
Thin Provisioning:                     Not Supported
Per-NS Atomic Units:                   No
NGUID/EUI64 Never Reused:              No
Number of LBA Formats:                 4
Current LBA Format:                    LBA Format #01
LBA Format #00: Data Size:   512  Metadata Size:     0
LBA Format #01: Data Size:   512  Metadata Size:     8
LBA Format #02: Data Size:  4096  Metadata Size:     0
LBA Format #03: Data Size:  4096  Metadata Size:     8
```

**Comment by AlekseyMarchuk** [comment]
Hi @ryderhsu0129 
I checked the commit mentioned by @changpe1, it works on my side with fio 3.9
Here is my fio config:

```
[Global]
ioengine=/spdk/examples/nvme/fio_plugin/fio_plugin
direct=1
rw=read
rwmixread=100
thread=1
norandommap=1
time_based=1
runtime=10
ramp_time=10
bs=4160
pi_act=0
pi_chk=GUARD
iodepth=32
percentile_list=99:99.9:99.99:99.999:99.9999:100
filename=trtype=PCIe traddr=0000.83.00.0 ns=1
numjobs=1
```

fio output with git `926c85bea (HEAD) nvme/pcie: Don't use contig SGL commands for admin qpair`:

```
Global: (g=0): rw=read, bs=(R) 4160B-4160B, (W) 4160B-4160B, (T) 4160B-4160B, ioengine=spdk, iodepth=32
fio-3.9
Starting 1 thread
Starting SPDK v20.01-pre git sha1 2d7523d07 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
PI type1 enabled with extended lba
Jobs: 1 (f=0): [f(1)][100.0%][r=1472KiB/s][r=362 IOPS][eta 00m:00s]
Global: (groupid=0, jobs=1): err= 0: pid=11453: Fri Dec 20 08:45:17 2019
   read: IOPS=153k, BW=608MiB/s (637MB/s)(6078MiB/10001msec)
    slat (nsec): min=297, max=13349, avg=370.14, stdev=75.79
    clat (usec): min=160, max=395, avg=208.19, stdev=20.08
     lat (usec): min=161, max=395, avg=208.56, stdev=20.08
    clat percentiles (usec):
     | 99.0000th=[  241], 99.9000th=[  260], 99.9900th=[  273],
     | 99.9990th=[  302], 99.9999th=[  383], 100.0000th=[  396]
   bw (  KiB/s): min=610374, max=623610, per=100.00%, avg=622312.11, stdev=2933.87, samples=19
   iops        : min=150246, max=153504, avg=153184.68, stdev=722.20, samples=19
  lat (usec)   : 250=99.60%, 500=0.40%
  cpu          : usr=100.03%, sys=0.00%, ctx=3, majf=0, minf=0
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=201.1%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.1%, 64=0.0%, >=64=0.0%
     issued rwts: total=1532013,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):
   READ: bw=608MiB/s (637MB/s), 608MiB/s-608MiB/s (637MB/s-637MB/s), io=6078MiB (6373MB), run=10001-10001msec
```
fio output with master `b9395621a (HEAD -> master) test/vhost: restore possibility to use custom Qemu binaries`:

```
Global: (g=0): rw=read, bs=(R) 4160B-4160B, (W) 4160B-4160B, (T) 4160B-4160B, ioengine=spdk, iodepth=32
fio-3.9
Starting 1 thread
Starting SPDK v20.01-pre git sha1 2d7523d07 / DPDK 19.08.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000002 cdw11:00000000
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0004 p:1 m:0 dnr:0
nvme_ctrlr.c:1307:nvme_ctrlr_identify_active_ns: *ERROR*: nvme_ctrlr_cmd_identify_active_ns_list failed!
nvme.c: 462:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:83:00.0
nvme_ctrlr.c: 678:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:83:00.0 in failed state.
fio_plugin.c: 495:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
Global: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:952, func=total_file_size, error=Invalid argument

```


I used disk SAMSUNG MZPLL1T6HAJQ-00005 which supports SGL and formatted as 512+8

Could you double check that you used the correct git commit?

**Comment by ryderhsu0129** [comment]
@changpe1 @AlekseyMarchuk 

I sync latest code from git and can run fio plugin with metadata,
thanks for your help.
