### ISSUE TITLE
I/O requests from the vhost with large bandwith will interfere that from the vhost with small one

### ISSUE THREAD

**Issue by ufo19890607** [spdk/spdk#1123]
Hi, guys

## Issue Description
Recently I found a competition issue that I/O requests from the vhost with large bandwith will interfere that from the vhost with small one. Reproducing this issue is really simply:
1. Startup the vhost_spdk and make sure one reactor thread will handle two vhosts I/O requests from a same socket.
2. Startup two vhosts  from a same socket and make sure each one has owned a single Intel NVMe SSD device.
3. Run fio with low write pressure on vhost1 and run fio with big write pressure on vhost2. Then we can see the IOPS from vhost1 will decrease extremely.

Below is the fio conf of two vhosts.
```
# small write pressure
[global]
ioengine=libaio
direct=1
thread=0
norandommap=1
randrepeat=0
group_reporting
log_avg_msec=1000
rw=randwrite
iomem_align=4096
bs=4k
numjobs=1
iodepth=1
group_reporting=1
time_based
runtime=60
size=2000G
[testfile1]
filename=/dev/vdb

# large write pressure
[global]
ioengine=libaio
direct=1
thread=0
norandommap=1
randrepeat=0
group_reporting
log_avg_msec=1000
rw=randwrite
iomem_align=4096
bs=64m
numjobs=16
iodepth=1
group_reporting=1
time_based
runtime=60
size=2000G
[testfile1]
filename=/dev/vdb
```

Below is the output of fio workload
1. Starup only one vhost and run fio with small write pressure
```
testfile1: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-44
096B, ioengine=libaio, iodepth=1
fio-3.15
Starting 1 process

fio: terminating on signal 2

testfile1: (groupid=0, jobs=1): err= 0: pid=11782: Thu Nov 21 20:00:42 2019
  write: IOPS=38.6k, BW=151MiB/s (158MB/s)(3353MiB/22226msec)
    slat (nsec): min=2126, max=17818, avg=2619.47, stdev=434.30
    clat (usec): min=5, max=667, avg=21.46, stdev= 4.69
     lat (usec): min=18, max=670, avg=24.48, stdev= 4.70
    clat percentiles (usec):
     | 60.000th=[   22], 65.000th=[   22], 70.000th=[   22], 75.000th=[   22],
     | 76.000th=[   22], 77.000th=[   22], 78.000th=[   22], 79.000th=[   22],
     | 80.000th=[   22], 85.000th=[   22], 90.000th=[   22], 95.000th=[   23],
     | 96.000th=[   23], 97.000th=[   24], 98.000th=[   26], 99.000th=[   28],
     | 99.500th=[   57], 99.900th=[   88], 99.990th=[  113], 99.995th=[  122]
```
2. Startup two vhosts with different fio conf workload
```
# low write pressure output
testfile1: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-44
096B, ioengine=libaio, iodepth=1
fio-3.15
Starting 1 process

testfile1: (groupid=0, jobs=1): err= 0: pid=5271: Fri Dec 20 17:32:00 2019
  write: IOPS=18, BW=72.6KiB/s (74.4kB/s)(2180KiB/30010msec)
    slat (nsec): min=2918, max=33671, avg=6797.92, stdev=3196.74
    clat (usec): min=1365, max=131664, avg=54941.95, stdev=26112.83
     lat (usec): min=1371, max=131674, avg=54949.07, stdev=26113.15
    clat percentiles (msec):
     | 60.000th=[   63], 65.000th=[   66], 70.000th=[   69], 75.000th=[   73],
     | 76.000th=[   74], 77.000th=[   74], 78.000th=[   75], 79.000th=[   77],
     | 80.000th=[   78], 85.000th=[   82], 90.000th=[   90], 95.000th=[  102],
     | 96.000th=[  104], 97.000th=[  107], 98.000th=[  108], 99.000th=[  112],
     | 99.500th=[  120], 99.900th=[  132], 99.990th=[  132], 99.995th=[  132]
```
```
#large write pressure output
testfile1: (g=0): rw=randwrite, bs=(R) 64.0MiB-64.0MiB, (W) 64.0MiB-64.0MiB, (T))
 64.0MiB-64.0MiB, ioengine=libaio, iodepth=1
...
fio-3.15
Starting 16 processes

testfile1: (groupid=0, jobs=16): err= 0: pid=6381: Thu Nov 21 18:02:12 2019
  write: IOPS=27, BW=1732MiB/s (1817MB/s)(102GiB/60328msec)
    slat (msec): min=9, max=1690, avg=485.91, stdev=498.33
    clat (msec): min=24, max=213, avg=103.51, stdev=30.84
     lat (msec): min=63, max=1823, avg=589.41, stdev=493.98
    clat percentiles (msec):
     | 60.000th=[  111], 65.000th=[  114], 70.000th=[  120], 75.000th=[  125],
     | 76.000th=[  125], 77.000th=[  127], 78.000th=[  128], 79.000th=[  129],
     | 80.000th=[  130], 85.000th=[  136], 90.000th=[  144], 95.000th=[  157],
     | 96.000th=[  161], 97.000th=[  163], 98.000th=[  167], 99.000th=[  174],
     | 99.500th=[  180], 99.900th=[  188], 99.990th=[  213], 99.995th=[  213]
```

From the results we can notice that I/O requests from the vhost with low write pressure will be affected by that from the other vhost.

## Issue Analysis
I checked the code(lib/nvme/nvme_ns_cmd.c) and found that I/O requests will be split into several parts if they are larger than 128KB. max_sector_kb is 512 by default if we use virtio driver in vhost .So if I set max_sector_kb to 128 in vhost, then this issue will disappear.  But I don't think spliting I/O requests is the root cause, because the time for splitting I/O requests can not reach miliseconds.

I checked the code and found `DEFAULT_IO_QUEUE_REQUESTS` is 512, which means that one reactor can just handle totally 512 I/O requests for all bdevs once. If I/O requests are more than 512 , then `_bdev_nvme_submit_request` will return `ENOMEM` and invoke `spdk_bdev_io_complete` with `SPDK_BDEV_IO_STATUS_NOMEM` to retry to submit this I/O requests, and this bdev_io will be inserted into the head of nomem_io queue. I think nomem_io queue is a per-thread struct and is shared by the two bdevs. So the I/O requests from the vhost with low write pressure will also be inserted into the nomem_io queue. What was worse is that they will be inserted into the tail of the queue. Therefore the completion latency will increase to 50~70ms.
```
static inline void 
_spdk_bdev_io_do_submit(struct spdk_bdev_channel *bdev_ch, struct spdk_bdev_io *bdev_io)
{
    struct spdk_bdev *bdev = bdev_io->bdev;
    struct spdk_io_channel *ch = bdev_ch->channel;
    struct spdk_bdev_shared_resource *shared_resource = bdev_ch->shared_resource;

    if (spdk_likely(TAILQ_EMPTY(&shared_resource->nomem_io))) {
        bdev_ch->io_outstanding++;
        shared_resource->io_outstanding++;
        bdev_io->internal.in_submit_request = true;
        bdev->fn_table->submit_request(ch, bdev_io);
        bdev_io->internal.in_submit_request = false;
    } else {
        TAILQ_INSERT_TAIL(&shared_resource->nomem_io, bdev_io, internal.link);
    }    
}
```

## Workround
1. set `max_sector_kb` to 128 in the vhost.
2. increase the value of `DEFAULT_IO_QUEUE_REQUESTS`.

I want to know if you have any other ideas to solve this I/O race issue between two vhosts. Thank you!

**Comment by optimistyzy** [comment]
Bdevs which are built on the same base bdev  will share the resource
channel, so the code design is correct from my mind. Only bdevs share the
same resource channel, will be put into the same no mem wait queue list,.

So properly I think you should be use two different sockets,  if you use
one socket, does it mean that even with two different nvme ssds, they are
under same vhost bdev and sharing the same resource channel?

在 2019年12月20日星期五，ufo19890607 <notifications@github.com> 写道：

**Comment by ufo19890607** [comment]
>So properly I think you should be use two different sockets,  if you use
one socket, does it mean that even with two different nvme ssds, they are
under same vhost bdev and sharing the same resource channel?

NVMe ssds are controlled by two different vhost bdevs but maybe sharing the same resource channel. Our host machine has 2 CPU socket, and each one contains 40 logical cores.  Each host machine will be mounted 4 NVMe ssds. Our lightweight virtual machine owns 16 vcpus and only one NVMe ssd，so one CPU socket can have 2 such vhosts. We need to make sure SPDK reactor use as little CPU cores as possible so that vhosts can own more CPU resource. So we make one reactor thread handle two vhosts' I/O requests from a same socket. 

We cannot move one vhost(low write pressure or high write pressure) to the other CPU socket, because other vhosts have owned the CPU cores of that socket.

**Comment by optimistyzy** [comment]
But one cpu core can handle multiple paths  e.g., vhost.0, vhost.1 and
others. So my question is that can you assign the devices under the
different path(vhost.x), to make sure that they are different vhost
controllers.
I think that you misunderstand my sockets(not the cpu sockets), but
different io socket path.

在 2019年12月22日星期日，ufo19890607 <notifications@github.com> 写道：

**Comment by optimistyzy** [comment]
And another choice is using the qos feature to limit the io on different
bdev.

在 2019年12月22日星期日，杨子夜 <optimistyzy@gmail.com> 写道：

**Comment by ufo19890607** [comment]
> So my question is that can you assign the devices under the
different path(vhost.x), to make sure that they are different vhost
controllers.

Do you mean that each bdev should be under a single path(vhost.x)? If so, then this approach is exactly what we are currently using. One vhost just has one bdev which represents a NVMe ssd, and there are 2 vhosts in one numa node. The vhost with large write pressure will interfere the other vhost in the same numa node.

**Comment by jimharris** [comment]
Hi @ufo19890607,

In your configuration, are you are attaching the same NVMe namespace to two different vhost controllers?

If you are sharing the namespace between two different controllers (via logical volumes for example), then bdev QoS would be the best method to avoid the situation you are describing.

-Jim

**Comment by changpe1** [comment]
@ufo19890607 Can you list your environment and configuration when the issue happened ? I'm confused too.

**Comment by ufo19890607** [comment]
Hi Jim

> In your configuration, are you are attaching the same NVMe namespace to two different vhost controllers?
> 
> If you are sharing the namespace between two different controllers (via logical volumes for example), then bdev QoS would be the best method to avoid the situation you are describing.
> 

I've told Ziye that each NVMe device has a unique bdev which is under a unique vhost controller. One vhost just has one bdev which owns only one NVMe device, and there are 2 vhosts in one numa node. The vhost with large write pressure will interfere the other vhost in the same numa node.

Thanks
- Wind

**Comment by ufo19890607** [comment]
> @ufo19890607 Can you list your environment and configuration when the issue happened ? I'm confused too.

Hi, changpe
The OS of the host machine is centos7.4, and kernel version is 3.10.0-693. Our hypervisor is KVM and we use virtio drivers. The spdk and dpdk is from upstream code. 

To be frankly, I think this issue has nothing to do with the test environment. You can reproduce this issue by the following steps:
- Create 2 vhosts on a same CPU socket, and each one has half of the logical CPU cores of this CPU socket. Each vhost has owned a NVMe device which has a unique bdev.
- Startup the vhost_spdk and make sure one reactor thread will handle two vhosts I/O requests from the same CPU socket.
- set vdb(NVMe bdev)'s max_sectors_kb to 512 in the two vhosts.
- Run fio with low write pressure on vhost1 and run fio with big write pressure on vhost2. 

Please refer to my fio config in "Issue Description".

**Comment by jimharris** [comment]
> Hi Jim
> 
> > In your configuration, are you are attaching the same NVMe namespace to two different vhost controllers?
> > If you are sharing the namespace between two different controllers (via logical volumes for example), then bdev QoS would be the best method to avoid the situation you are describing.
> 
> I've told Ziye that each NVMe device has a unique bdev which is under a unique vhost controller. One vhost just has one bdev which owns only one NVMe device, and there are 2 vhosts in one numa node. The vhost with large write pressure will interfere the other vhost in the same numa node.
> 
> Thanks
> 
> * Wind

Are these two namespaces from the same controller?

The two vhost controllers will only share a channel if they are associated with the same NVMe controller.

**Comment by ufo19890607** [comment]
No. They are from different vhost controllers.&nbsp;


Thx
Wind





------------------ Original ------------------

**Comment by ufo19890607** [comment]
> > Hi Jim
> > > In your configuration, are you are attaching the same NVMe namespace to two different vhost controllers?
> > > If you are sharing the namespace between two different controllers (via logical volumes for example), then bdev QoS would be the best method to avoid the situation you are describing.
> > 
> > 
> > I've told Ziye that each NVMe device has a unique bdev which is under a unique vhost controller. One vhost just has one bdev which owns only one NVMe device, and there are 2 vhosts in one numa node. The vhost with large write pressure will interfere the other vhost in the same numa node.
> > Thanks
> > 
> > * Wind
> 
> Are these two namespaces from the same controller?
> 
> The two vhost controllers will only share a channel if they are associated with the same NVMe controller.
 
No. They are from different vhost controllers.

Thx
Wind

**Comment by jimharris** [comment]
Hi @ufo19890607,

But the bdevs that you are attaching to the vhost controllers - are these two bdevs represented by nvme namespaces from separate nvme controllers?  Or are they namespaces from the same nvme controller?

If you could post the exact commands you are using to configure the bdevs and the vhost controllers, it might help reduce any confusion.

Note that a channel is only shared if the bdevs are associated with the same nvme controller.  The nomem io queue that you mentioned is not per-thread - it is per-shared-channel.

-Jim

**Comment by optimistyzy** [comment]
> Hi @ufo19890607,
> 
> But the bdevs that you are attaching to the vhost controllers - are these two bdevs represented by nvme namespaces from separate nvme controllers? Or are they namespaces from the same nvme controller?
> 
> If you could post the exact commands you are using to configure the bdevs and the vhost controllers, it might help reduce any confusion.
> 
> Note that a channel is only shared if the bdevs are associated with the same nvme controller. The nomem io queue that you mentioned is not per-thread - it is per-shared-channel.
> 
> -Jim

Hi Jim @jimharris ,

I agree with you. So I am very confused. I think that the @ufo19890607 may use the wrong channel as I discussed with Changpeng @changpe1

**Comment by optimistyzy** [comment]
@ufo19890607 Any update on this?

**Comment by ufo19890607** [comment]
> @ufo19890607 Any update on this?

I will try to reproduce this issue with spdk-19.10 version recently.

**Comment by changpe1** [comment]
I'm going to close this issue as I don't see similar issue in mater SPDK.  Please re-open it if you still need more investigation.

**Comment by ufo19890607** [comment]
@changpe1 @jimharris @optimistyzy 
Hi, guys.
Sorry for late replying.  This issue will happen only in the spdk version 18.04. IOPS for vhosts will become normal after applying a patch(bdev: create one module channel per io_device) for spdk.
```
commit 7ac765e66b8d59a5911815e7815a5855f5538064
Author: Dariusz Stojaczyk <dariuszx.stojaczyk@intel.com>
Date:   Fri May 4 09:58:01 2018 +0200

    bdev: create one module channel per io_device
    
    Bdev layer has been recently refactored to share
    internal module channels for *all* bdevs of the
    same bdev module. This makes us return ENOMEM for I/O
    of one bdev if another bdev of the same module (nvme, split, etc)
    is entirely saturated. This is not the behavior we want,
    as these bdevs may not have anything in common.
    
    This partially reverts commit
    e433001 (bdev: Put 3 types of channels in a hierarchy)
    
    Change-Id: Ice0570f92fcaffa6301a282c53eeec8215f354fe
    Reported-by: Ben Walker <benjamin.walker@intel.com>
    Signed-off-by: Dariusz Stojaczyk <dariuszx.stojaczyk@intel.com>
    Reviewed-on: https://review.gerrithub.io/409996
    Reviewed-by: Shuhei Matsumoto <shuhei.matsumoto.xt@hitachi.com>
    Reviewed-by: Jim Harris <james.r.harris@intel.com>
    Reviewed-by: Ben Walker <benjamin.walker@intel.com>
    Reviewed-by: Daniel Verkamp <daniel.verkamp@intel.com>
    Tested-by: SPDK Automated Test System <sys_sgsw@intel.com>
```

Thank you everyone :》
