### ISSUE TITLE
NVMeoF - Have ability to set timeout for port disconnects

### ISSUE THREAD

**Issue by mkotwani1** [spdk/spdk#1124]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

When running SPDK 19.07 with CX-5, it takes SPDK 15 seconds to get an event from the RDMA CM if I disable the local interface. It is after this timeout that SPDK starts failing operations. Making this timeout configurable allows an app to decide how long to wait for the link to come back up before starting to fail operations.

## Expected Behavior

Some apps might be OK with the 15 second timeout, but some apps would need a much shorter timeout than that. Making it configurable would be best.

## Current Behavior

The current behavior is it takes 15 seconds for the disconnect event to come up to SPDK with CX-5. It is only after getting this event that SPDK starts failing ops and marks the transport as down,

## Possible Solution

Provide the app a way to specify what timeout it would want to set.

## Steps to Reproduce

1.  SPDK 19.07 NVF target exposed on a CX-5 port, and another SPDK NVF initiator that talks to this port.
2. Disconnect/do an ifconfig down on the CX-5 port for the initiator.
3. It will take 15 seconds for SPDK instance on the initiator to see the disconnect event

## Context (Environment including OS version, SPDK version, etc.)

SPDK 19.07

**Comment by AlekseyMarchuk** [comment]
From the discussion of this problem in slack, we found 2 ways to reduce the timeout 
1. Use transport_retry_count parameter from the controller opts in rdma_connect(). This parameter is used during connection negotiation and later applied to qpair.
I checked how `retry_count` affects the real time of receiving "retry counter exceeded" error, rough results are below:
retry_count = 7, ~15 seconds
retry_count = 3, ~13 seconds
retry_count = 2, ~11 seconds
retry_count = 1, ~8 seconds

2. Use rdma_set_option() with RDMA_OPTION_ID_ACK_TIMEOUT id to specify timeout per cm_id. The value accepted by this function is used to calculate QP ACK timeout according to the formula 4.096 * 2^(ack_timeout) usec. However this function was merged to rdma-core in the beginning of this year and most likely it is not included in most linux distributions. It is part of MOFED starting from v4.7-1.0.0.1. Example of usage: https://github.com/linux-rdma/rdma-core/commit/69868fa75e57a450d0e71a0be239d483a271bd7a
If we accept this approach then we'll need to check that this functionality is presented in the system in `configure` and allow compilation, like it is done in NVMEoF RDMA target with `#ifdef SPDK_CONFIG_RDMA_SEND_WITH_INVAL`. We will also need to introduce a new configuration parameter to `spdk_nvme_ctrlr_opts` (something like `transport_timeout` - TBD)

ACK timeout value and time of receiving "retry counter exceeded" error with default retry_count:
3, ~4.5 sec
4, ~4.5 sec
5, ~4.5 sec
10, ~5 sec
20, ~17 sec

The combination of these 2 approaches will help to configure the desired timeout

**Comment by AlekseyMarchuk** [comment]
Another point for discussion is about proposed approach №1 - use transport_retry_count from controller opts structure. This value is defaulted to `4` while on RDMA initiator side we use value `7`. I don't think that using `4` by default will somehow affect stability, but I wanted to hear other opinions regarding this change.

**Comment by jimharris** [comment]
Hi @benlwalker @Seth5141 - do you have any thoughts on this proposal from Alexey?

**Comment by Seth5141** [comment]
@AlekseyMarchuk I think that #1 sounds perfectly reasonable. We'll just have to make sure that we do extra field validation when parsing that value for the RDMA transport since we also use it in PCIe as a generic 8 bit value and you can't exceed 7 in the RDMA transport.
I also agree that using the default of 4 shouldn't affect anything negatively. My only concern was with SRQ, but after refreshing myself I realized that all of those failures are governed by the RNR_RETRY value.

I am a little bit confused about the math for number 2. Shouldn't the time it takes to get a timeout event be calculated with the following formula?
4.096 * 2^(ack_timeout) * retry_count? and the units of the answer would be in microseconds right?
With that logic, for rnr_retry=4 and ack_timeout=3, shouldn't we get 
4.096 * 2^3 * 4 = 131.072 usec? I mean that calculated value seems really small, but I still don't understand how we end up with a number in the seconds.

I still totally agree that we should allow for both of those values to be modified by the user and think we should move forward.

**Comment by jimharris** [comment]
Bug scrub: approach seems reasonable, but there are some questions still from @Seth5141 on the math

**Comment by AlekseyMarchuk** [comment]
Hi @Seth5141 
I agree that the timeout you calculated looks very small. I tried to check how this value is used in IB driver, but this task turned out to be quite difficult. I'll ask someone from Mellanox driver developers for details and share the answer

**Comment by AlekseyMarchuk** [comment]
Hi @Seth5141 

I went deep in kernel IB modules and IB spec and found out that the actual time of retransmission is calculated using the following formula: `packet_life_time * 2 + 4.064 * 2 ^ ack_timeout us`.
However CMA kernel module uses some approximation to calculate `packet_life_time` - it is defaulted to 18 if ACK_TIMEOUT is not set or equals to  `ACK_TIMEOUT - 1`. Later `primary_path_timeout` is calculated using `device_ack_delay`  (defaulted to 16) and `packet_life_time`, here is an extract from cm code:
```
calculate: 4.096x2^ack_timeout = 4.096x2^ack_delay + 2x4.096x2^life_time
Because of how ack_timeout is stored, adding one doubles the timeout.
To avoid large timeouts, select the max(ack_delay, life_time + 1), and
increment it (round up) only if the other is within 50%.
```
I applied this math to estimate the expected timeout and got the following values:
```
ack_timeout	life_time	path_time	time_us
0		255		31		18446744065119617024 us
1		0		16		262144 us
2		1		16		262144 us
3		2		16		262144 us
4		3		16		262144 us
5		4		16		262144 us
6		5		16		262144 us
7		6		16		262144 us
8		7		16		262144 us
9		8		16		262144 us
10		9		16		262144 us
11		10		16		262144 us
12		11		16		262144 us
13		12		16		262144 us
14		13		16		262144 us
15		14		17		524288 us
16		15		17		524288 us
17		16		18		1048576 us
18		17		18		1048576 us
19		18		19		2097152 us
20		19		20		4194304 us
21		20		21		8388608 us
22		21		22		16777216 us
23		22		23		33554432 us
24		23		24		67108864 us
25		24		25		134217728 us
26		25		26		268435456 us
27		26		27		536870912 us
28		27		28		1073741824 us
29		28		29		2147483648 us
30		29		30		4294967296 us
```

The last column is the approximate lifetime of the packet. ACK_TIMEOUT = 0 means infinite timeout, used for debug purpose.

The results I receive in my experiments are more or less match the table above, but the measurement was very inaccurate I suppose the error is about 1 second. We also need to take into account the overhead introduced by SPDK, I think on "pure" verb application we could get more precise results. The only significant mismatch is that after ACK_TIMEOUT=20 I don't see a real increase of the timeout. I can't explain it, maybe it is driver limitation. I used retry_count = 4. Below are values of ACK_TIMEOUT and approximate time until I noticed an error on cq.
```
ack_timeout	cq error time
1-16		3,3 sec 
17		5 sec
18		10,5 sec
19 		14 sec
20		17 sec
>20		17-18 sec
```

As I wrote before, I asked for an explanation on the timeout math, but I still haven't found the right person who could explain it.

I prepared several patches to address both suggestions : https://review.gerrithub.io/c/spdk/spdk/+/482499

**Comment by AlekseyMarchuk** [comment]
Patch which adds transport ack timeout has been merged to master https://review.spdk.io/gerrit/c/spdk/spdk/+/503, I'm closing this issue
