### ISSUE TITLE
NVME RDMA initiator crashes during connection establishment

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1125]
I was trying to reproduce issue #1101 and observed unexpected crash of spdk_nvme_perf application

## Expected Behavior
Connection to the remote target established or errors handled without crash

## Current Behavior
spdk_nvme_perf application crashed, call stack is the following:

```
Program terminated with signal 11, Segmentation fault.
#0  0x00005609f2647ede in nvme_completion_poll_cb (arg=0x7fff075f9dd0, cpl=0x7fff075f9ea0) at nvme.c:96
96              status->done = true;

#0  0x00005609f2647ede in nvme_completion_poll_cb (arg=0x7fff075f9dd0, cpl=0x7fff075f9ea0) at nvme.c:96
#1  0x00005609f2659aee in nvme_complete_request (cb_fn=0x5609f2647eaa <nvme_completion_poll_cb>, cb_arg=0x7fff075f9dd0, qpair=0x5609f3a944f0, req=0x2000003e7200, cpl=0x7fff075f9ea0) at nvme_internal.h:993
#2  0x00005609f2659e9d in nvme_rdma_req_complete (req=0x2000003e7200, rsp=0x7fff075f9ea0) at nvme_rdma.c:242
#3  0x00005609f265e4a2 in nvme_rdma_qpair_abort_reqs (qpair=0x5609f3a944f0, dnr=1) at nvme_rdma.c:1839
#4  0x00005609f265d7c5 in nvme_rdma_qpair_destroy (qpair=0x5609f3a944f0) at nvme_rdma.c:1559
#5  0x00005609f265e017 in nvme_rdma_ctrlr_destruct (ctrlr=0x5609f3a91bd0) at nvme_rdma.c:1713
#6  0x00005609f264aca0 in nvme_transport_ctrlr_destruct (ctrlr=0x5609f3a91bd0) at nvme_transport.c:112
#7  0x00005609f263b8b4 in nvme_ctrlr_destruct (ctrlr=0x5609f3a91bd0) at nvme_ctrlr.c:2609
#8  0x00005609f2648b1e in nvme_ctrlr_poll_internal (ctrlr=0x5609f3a91bd0, probe_ctx=0x5609f396c820) at nvme.c:464
#9  0x00005609f264a4b1 in spdk_nvme_probe_poll_async (probe_ctx=0x5609f396c820) at nvme.c:1124
#10 0x00005609f2648d06 in nvme_init_controllers (probe_ctx=0x5609f396c820) at nvme.c:508
#11 0x00005609f2649226 in spdk_nvme_probe (trid=0x5609f3963db0, cb_ctx=0x5609f3963db0, probe_cb=0x5609f2631aa9 <probe_cb>, attach_cb=0x5609f2631b2c <attach_cb>, remove_cb=0x0) at nvme.c:655
#12 0x00005609f2631c8f in register_controllers () at perf.c:1930
#13 0x00005609f263209e in main (argc=13, argv=0x7fff075fa418) at perf.c:2085

```

## Possible Solution
From my analysis, the controller was trying to identify remote namespaces and pseudo call stack was the following:

```
nvme_ctrlr_process_init():
case NVME_CTRLR_STATE_IDENTIFY_ACTIVE_NS:
    rc = nvme_ctrlr_identify_active_ns(...) {
          [0]struct nvme_completion_poll_status	status;
          /* Function below submits a request to the admin qpair */
          [1]rc = nvme_ctrlr_cmd_identify(ctrlr, SPDK_NVME_IDENTIFY_ACTIVE_NS_LIST, 0, next_nsid,
						     &new_ns_list[1024 * i], sizeof(struct spdk_nvme_ns_list),
						     nvme_completion_poll_cb, &status);
       /* Some error happened on the transport layer or I occasionally killed the target, don't 
           remember exactly. Anyway, the submitted request is still queued on the admin qpair.
           This request has cb_fn nvme_completion_poll_cb and cb_arg pointing to status on the stack  */
       [2]if (spdk_nvme_wait_for_completion(ctrlr->adminq, &status)) {
           rc = -ENXIO;
           goto fail;
    }

    if (rc < 0) {
        nvme_ctrlr_destruct_namespaces(ctrlr);
    }
    nvme_ctrlr_set_state(ctrlr, NVME_CTRLR_STATE_IDENTIFY_NS,
				     ctrlr->opts.admin_timeout_ms);  
```

In `nvme_ctrlr_identify_active_ns` we submit a request [1] with cb_fn=nvme_completion_poll_cb and cb_arg=[0] - pointer to a local stack variable. In spdk_nvme_wait_for_completion [2] we a waiting for completion of this command. However transport failure may happen at this moment and we will exit `nvme_ctrlr_identify_active_ns` function while the request is still queued on the admin queue. The original call stack shows that when we start to destroy the controller and its admin qpair, we abort all queued requests and call cb_fn per request. That leads to access to a variable which is out of scope.

Possible solution would be:
1. make `struct nvme_completion_poll_status status` a member of `struct spdk_nvme_ctrlr`
2. point cb_arg to `&ctrlr->status`
3. Zerofy `ctrlr->status` before submitting a request

We need to fix all the places where nvme_completion_poll_cb is used with a pointer to a stack variable.

## Steps to Reproduce
Run spdk_nvme_perf application many, many times and try to simulate a network failure

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: 0edc874f8 test/nvme: fix wrong exit commands.
OS: Ubuntu 18.04.3 LTS
Kernel: 4.15.0-72-generic

**Comment by AlekseyMarchuk** [comment]
Implemented the proposed solution:
https://review.gerrithub.io/c/spdk/spdk/+/478805

**Comment by jimharris** [comment]
Bug scrub: patch looks like right approach - it does look like there was an even more basic bug in the current code, where status.done flag doesn't get explicitly cleared before submitting the command

**Comment by tomzawadzki** [comment]
Reworked solution now at https://review.gerrithub.io/c/spdk/spdk/+/481528
