### ISSUE TITLE
Does SPDK vhost-user block support reconnect or restart?

### ISSUE THREAD

**Issue by axiqia** [spdk/spdk#1127]
hi, folks!

Does SPDK vhost-user block support reconnect or restart? And is there any mechanism to deal with IO request consistency if it supports? 

For example, SPDK crash or need to restart for some reason. I didn't find any document about SPDK reconnect. 

> DPDK vhost-user acts as the client: Unlike the server mode, this mode doesn’t create the socket file;it just tries to connect to the server (which responses to create the file instead). When the DPDK vhost-user application restarts, DPDK vhost-user will try to connect to the server again. This is how the “reconnect” feature works. **When DPDK vhost-user restarts from an normal or abnormal exit (such as a crash), the client mode allows DPDK to establish the connection again. Note that QEMU version v2.7 or above is required for this reconnect feature.**

I only found  DPDK support reconnect [here](https://doc.dpdk.org/dts/test_plans/pvp_vhost_user_reconnect_test_plan.html)

Any reply will be appreciated!

**Comment by changpe1** [comment]
@axiqia I believe the patch here https://review.gerrithub.io/c/spdk/spdk/+/471235/7 can meet your requirement, we will enable this feature with SPDK 20.01 release.

**Comment by axiqia** [comment]
@changpe1  Thank you. Great job. Looking forward to this new feature.
