### ISSUE TITLE
an question about file "examples/bdev/hello_world/hello_bdev.c"

### ISSUE THREAD

**Issue by ywbgithub** [spdk/spdk#1128]
In the file ""examples/bdev/hello_world/hello_bdev.c"",  the function  hello_start() calls ""	hello_context->bdev_io_channel = spdk_bdev_get_io_channel(hello_context->bdev_desc)“”。 Is that only one struct spdk_io_channel  created ? Then is there only one io queue?

**Comment by optimistyzy** [comment]
@ywbgithub  Yes, get the IO channel on the current thread.  In real usage, if this function called second time on the same SPDK thread, it will reuse the same I/O channel.   Generally, IO channel can be thought as the mapping result from the pair  <io_device,  spdk thread>. It means the same io device can have its own channel on different SPDK threads, But the channel the io_device on the same thread should be same.

**Comment by optimistyzy** [comment]
@ywbgithub will close this issue. If there is any other question related this, you can re-open this issue.
