### ISSUE TITLE
Build timeouts on GP systems in CI

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1131]
On a patch unrelated to nvme: https://review.gerrithub.io/c/spdk/spdk/+/472209

**Comment by peluse** [comment]
also saw this on another patch earlier today at https://review.gerrithub.io/c/spdk/spdk/+/478384/12

**Comment by jimharris** [comment]
I'm seeing similar issues on other patches.  It's not always nvme_phy_autotest - it seems more specific to the GP* systems (both of these were GP17, I have one on GP16).  So I'm going to change the title on this to cover the broader case now that we have some more data.

**Comment by jimharris** [comment]
Looking at the internal Jenkins log for Paul's 478384 failure, we see this:

19:01:46   LINK test/app/bdev_svc/bdev_svc
19:01:46   LINK examples/bdev/fio_plugin/fio_plugin
19:01:49   LINK test/nvme/deallocated_value/deallocated_value
19:09:51 Build timed out (after 10 minutes). Marking the build as failed.
19:09:51 Build was aborted
19:09:51 [PostBuildScript] - Executing post build scripts.
19:09:51 [nvme_phy_autotest] $ /bin/sh -xe /tmp/jenkins4103454971541121994.sh
19:09:51 + set +x

So it seems like the system literally hung at this point.  I'm going to check this out for the other failures reported here.  If we can narrow this down to GP16 and GP17, maybe we have SSDs that need to be replaced or updated or something.

**Comment by jimharris** [comment]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55014.html

**Comment by jimharris** [comment]
This one was originally filed against #1072.  Moving it here instead.

Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54580.html

**Comment by jimharris** [comment]
Also originally from #1072 
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_54166.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55072.html

**Comment by jimharris** [comment]
(Moved from #1072)
Another instance of this failure. Reported by @Maciej-Szwed. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55187.html

**Comment by Seth5141** [comment]
> Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55072.html

Was this one on accident? It appears to be pointing to an ubuntu VM.

**Comment by jimharris** [comment]
> > Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55072.html
> 
> Was this one on accident? It appears to be pointing to an ubuntu VM.

Oops.  Should have been #1137.  I had too many issue numbers in my head.  :)

I'll fix it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60151.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60154.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4393.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_4657.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_4658.html

**Comment by karlatec** [comment]
@shuhei-matsumoto The timeout in your #4393 build was on CentOS VM, not GP system. And I think it should be fixed now as part of #1119 issue. The other fail (nvme-phy-autotest job) has something to do when testing nvme_cli vs Optane drive.

@glodfish-zg Timeouts in builds 4657 and 4658 did not occur on GP systems, but in nvmf-autotest which is run on Fedora VMs. This seems to be a separate issue

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @darsto. log: https://ci.spdk.io/public_build/autotest-per-patch_4665.html

**Comment by jimharris** [comment]
@karlatec @Seth5141 Seems like this issue hasn't appeared in almost 3 weeks.  Has anything changed with the GP systems that we can point to?  If so, I vote we close this issue.

**Comment by karlatec** [comment]
@jimharris just a question - what comments from spdkci did you delete?:) Were these unrelated failures, which were mistakenly put here?

> Has anything changed with the GP systems that we can point to?
Not on GP systems directly, but we switched the CI over this time. I do not recall any new configuration being done on physical systems.

**Comment by jimharris** [comment]
> @jimharris just a question - what comments from spdkci did you delete?:) Were these unrelated failures, which were mistakenly put here?

They were unrelated failures. 
> 
> > Has anything changed with the GP systems that we can point to?
> 
> Not on GP systems directly, but we switched the CI over this time. I do not recall any new configuration being done on physical systems.

Ok - thanks.  I guess we will keep this open for now and track it a bit longer.

**Comment by jimharris** [comment]
It's been another 3 weeks without reappearance.  Closing.
