### ISSUE TITLE
per-patch test failed due to run_test "nvme" test/nvme/nvme.sh

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1134]
log :https://d3uor3w1civ2bt.cloudfront.net/results/autotest-per-patch/builds/1548/archive/nvme-phy-autotest/build.log
```
Starting SPDK v20.01-pre git sha1 ba0c42eaac / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: stub -c 0xF -m 4096 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
Starting SPDK v20.01-pre git sha1 ba0c42eaac / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: reset -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 4
EAL: VFIO support initialized
nvme.c: 364:nvme_driver_init: *ERROR*: primary process is not started yet
nvme.c: 647:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed
Initializing NVMe Controllers
  07:47:26	# trap - ERR
  07:47:26	# print_backtrace
  07:47:26	# [[ ehxBE =~ e ]]
  07:47:26	# xtrace_disable
  07:47:26	# '[' no '!=' yes ']'
  07:47:26	# PREV_BASH_OPTS=ehxBE
  07:47:26	# [[ ehxBE == *\x* ]]
  07:47:26	# XTRACE_DISABLED=yes
  07:47:26	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:590 -> run_test()
     ...
   585 		timing_enter $test_name
   586 		echo "************************************"
   587 		echo "START TEST $test_name"
   588 		echo "************************************"
   589 		xtrace_restore
=> 590 		time "$@"
   591 		xtrace_disable
   592 		echo "************************************"
   593 		echo "END TEST $test_name"
   594 		echo "************************************"
   595 	
     ...
in test/nvme/nvme.sh:112 -> main()
```

**Comment by Comphix** [comment]
From the log, looks like the reset application is started as secondary process while does not find the memzone created by primary process.

Could this relate to some memory configuration?

Current user memlock limit: 16 MB

This is the maximum amount of memory you will be
able to use with DPDK and VFIO if run as current user.
To change this, please adjust limits.conf memlock limit for current user.

## WARNING: memlock limit is less than 64MB


 07:47:25	# start_stub '-s 4096 -i 0 -m 0xF'
 07:47:25	# echo 0
 07:47:25	# stubpid=859943
 07:47:25	# echo Waiting for stub to ready for secondary processes...
Waiting for stub to ready for secondary processes...
 07:47:25	# '[' -e /var/run/spdk_stub0 ']'
 07:47:25	# /var/jenkins/workspace/nvme-phy-autotest/spdk/test/app/stub/stub -s 4096 -i 0 -m 0xF
 07:47:25	# echo done.
done.
 07:47:25	# trap 'kill_stub -9; exit 1' SIGINT SIGTERM EXIT
 07:47:25	# run_test nvme_reset /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/reset/reset -q 64 -w write -s 4096 -t 5
 07:47:25	# '[' 10 -le 1 ']'
 07:47:25	# xtrace_disable
 07:47:25	# '[' '' '!=' yes ']'
 07:47:25	# PREV_BASH_OPTS=ehxBE
 07:47:25	# [[ ehxBE == *\x* ]]
 07:47:25	# XTRACE_DISABLED=yes
 07:47:25	# set +x
 07:47:25	# XTRACE_DISABLED=no
 07:47:25	# PREV_BASH_OPTS=
 07:47:25	# xtrace_enable
 07:47:25	# echo '************************************'
************************************
 07:47:25	# echo 'START TEST nvme_reset'
START TEST nvme_reset
 07:47:25	# echo '************************************'
************************************
 07:47:25	# [[ '' == *\x* ]]
 07:47:25	# /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/reset/reset -q 64 -w write -s 4096 -t 5
Starting SPDK v20.01-pre git sha1 ba0c42eaac / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: stub -c 0xF -m 4096 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
Starting SPDK v20.01-pre git sha1 ba0c42eaac / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: reset -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 4
EAL: VFIO support initialized
nvme.c: 364:nvme_driver_init: *ERROR*: primary process is not started yet
nvme.c: 647:spdk_nvme_probe: *ERROR*: Create probe context failed

**Comment by jimharris** [comment]
Starting SPDK v20.01-pre git sha1 ba0c42eaac / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: stub -c 0xF -m 4096 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
Starting SPDK v20.01-pre git sha1 ba0c42eaac / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: reset -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]

Note that reset core mask is 0x1 and stub core mask is 0xF.  This means both apps are using core 0.  We should have stub only run on core mask 0xE perhaps.

@yidong0635 - could you try a patch for this?

**Comment by yidong0635** [comment]
patch : https://review.gerrithub.io/c/spdk/spdk/+/479771.

**Comment by tomzawadzki** [comment]
Patch fixing this issue was merged https://review.gerrithub.io/c/spdk/spdk/+/479771.
