### ISSUE TITLE
QoS test fails on FreeBSD

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1136]
Several of these seen in the test pool - will post links shortly:

  18:59:01	# '[' IOPS = IOPS ']'
   18:59:01	# echo '{' '"tick_rate":' 2494212256, '"bdevs":' '[' '{' '"name":' '"Null_0",' '"bytes_read":' 104226033664, '"num_read_ops":' 25445802, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 7353991675588, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   18:59:01	# jq -r '.bdevs[0].num_read_ops'
  18:59:01	# io_result_after=25445802
  18:59:01	# echo 1053360
 18:59:01	# qos_result=1053360
 18:59:01	# '[' IOPS = BANDWIDTH ']'
  18:59:01	# echo '950000 0.9'
  18:59:01	# awk '{printf("%i",$1*$2)}'
 18:59:01	# lower_limit=855000
  18:59:01	# echo '950000 1.1'
  18:59:01	# awk '{printf("%i",$1*$2)}'
 18:59:01	# upper_limit=1045000
 18:59:01	# '[' 1053360 -lt 855000 ']'
 18:59:01	# '[' 1053360 -gt 1045000 ']'
 18:59:01	# echo 'Failed to limit the io read rate of NULL bdev by qos'
Failed to limit the io read rate of NULL bdev by qos
 18:59:01	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_null_delete Null_0

 Logical core: 1

 Null_0              :  426887.60 IO/s    1667.53 MB/s

 =====================================================

 Total               :  426887.60 IO/s    1667.53 MB/s
0
 18:59:01	# killprocess 70340
 18:59:01	# '[' -z 70340 ']'
 18:59:01	# kill -0 70340
  18:59:01	# ps --no-headers -o comm= 70340
ps: illegal option -- -
usage: ps [-aCcdefHhjlmrSTuvwXxZ] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-J jid[,jid...]] [-M core] [-N system]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
 18:59:01	# '[' '' = sudo ']'
 18:59:01	# echo 'killing process with pid 70340'
killing process with pid 70340
 18:59:01	# kill 70340

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55207.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55206.html

**Comment by Comphix** [comment]
Looking at this issue

**Comment by Comphix** [comment]
After reading three instances of failure, it looks like not using the latest SPDK code where we use ticks for more accuracy of calculation of per second IOPS or BW instead of using the fixed 5 seconds.

Logs as below where we add a new member for the bdev_get_iostat" API.

   08:42:33	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_get_iostat -b Null_1
  08:42:33	# io_result='{
  "tick_rate": 2494214208,
  "ticks": 1688562634076,  <<<<<<<<<
  "bdevs": [
    {
      "name": "Null_1",
      "bytes_read": 157333712896,
      "num_read_ops": 38411544,
      "bytes_written": 0,
      "num_write_ops": 0,
      "bytes_unmapped": 0,
      "num_unmap_ops": 0,
      "read_latency_ticks": 14329193421572,
      "write_latency_ticks": 0,
      "unmap_latency_ticks": 0
    }

Please rebase with latest code.

**Comment by Comphix** [comment]
Remain the open of this issue for a short time and will close it later.

**Comment by jimharris** [comment]
@Comphix is right.  Closing this issue.  I've put a note on the patch series that it needs to be rebased (last time it was rebased was mid November).

**Comment by shuhei-matsumoto** [comment]
Hi @Comphix

I saw this failure once on the patch series rebased on January 9th. So I reopen the issue and want you to take a look.
Will you take a look at the log?

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/55700/archive/freebsd_autotest/build.log

  01:21:38	# '[' BANDWIDTH = IOPS ']'
   01:21:38	# echo '{' '"tick_rate":' 2494212908, '"ticks":' 577268109916, '"bdevs":' '[' '{' '"name":' '"Null_1",' '"bytes_read":' 171792797696, '"num_read_ops":' 41941594, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 14734415150830, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   01:21:38	# jq -r '.bdevs[0].bytes_read'
  01:21:38	# io_result_after=171792797696
   01:21:38	# echo '{' '"tick_rate":' 2494212908, '"ticks":' 577268109916, '"bdevs":' '[' '{' '"name":' '"Null_1",' '"bytes_read":' 171792797696, '"num_read_ops":' 41941594, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 14734415150830, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   01:21:38	# jq -r .ticks
  01:21:38	# ticks_after=577268109916
  01:21:38	# '[' BANDWIDTH = IOPS ']'
  01:21:38	# io_result_diff=6107068
  01:21:38	# echo 967309
 01:21:38	# qos_result=967309
 01:21:38	# '[' BANDWIDTH = BANDWIDTH ']'
 01:21:38	# qos_limit=1144832
 01:21:38	# lower_limit=1030348
 01:21:38	# upper_limit=1259315
 01:21:38	# '[' 967309 -lt 1030348 ']'
 01:21:38	# echo 'Failed to limit the io read rate of NULL bdev by qos'
Failed to limit the io read rate of NULL bdev by qos
 01:21:38	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_null_delete Null_0
 01:21:38	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_null_delete Null_1


Besides, --no-headers is imvalid option of ps command for freebsd. So we will have to fix this separately.

  01:21:38	# ps --no-headers -o comm= 21419
ps: illegal option -- -
usage: ps [-aCcdefHhjlmrSTuvwXxZ] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-J jid[,jid...]] [-M core] [-N system]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
 01:21:38	# '[' '' = sudo ']'
 01:21:38	# echo 'killing process with pid 21419'
killing process with pid 21419
 01:21:38	# kill 21419
 01:21:38	# wait 21419
 01:21:38	# exit 1

Thanks,
Shuhei

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55700.html

**Comment by Comphix** [comment]
Looking at the log, it looks like the IO duration is 6.31 seconds while it is asked to sleep 5 seconds.

Previously we've calculated that it will be actually around 5.3 seconds. However here it is 1.3 second more.

Interesting, not sure where this additional 1 second come and make the bandwidth calculation lower than the expectation.

 01:21:31	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_get_iostat -b Null_1
  01:21:31	# io_result='{
  "tick_rate": 2494212908,
  "ticks": 561521006522,
  "bdevs": [
    {
      "name": "Null_1",
      "bytes_read": 165539160064,
      "num_read_ops": 40414827,
      "bytes_written": 0,
      "num_write_ops": 0,
      "bytes_unmapped": 0,
      "num_unmap_ops": 0,
      "read_latency_ticks": 10703978743532,
      "write_latency_ticks": 0,
      "unmap_latency_ticks": 0
    }
  ]
}'
  01:21:31	# '[' BANDWIDTH = IOPS ']'
   01:21:31	# echo '{' '"tick_rate":' 2494212908, '"ticks":' 561521006522, '"bdevs":' '[' '{' '"name":' '"Null_1",' '"bytes_read":' 165539160064, '"num_read_ops":' 40414827, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 10703978743532, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   01:21:31	# jq -r '.bdevs[0].bytes_read'
  01:21:31	# io_result_before=165539160064
   01:21:31	# echo '{' '"tick_rate":' 2494212908, '"ticks":' 561521006522, '"bdevs":' '[' '{' '"name":' '"Null_1",' '"bytes_read":' 165539160064, '"num_read_ops":' 40414827, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 10703978743532, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   01:21:31	# jq -r .tick_rate
  01:21:31	# tick_rate=2494212908
   01:21:31	# echo '{' '"tick_rate":' 2494212908, '"ticks":' 561521006522, '"bdevs":' '[' '{' '"name":' '"Null_1",' '"bytes_read":' 165539160064, '"num_read_ops":' 40414827, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 10703978743532, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   01:21:31	# jq -r .ticks
  01:21:31	# ticks_before=561521006522
  01:21:31	# sleep 5
   01:21:37	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_get_iostat -b Null_1
  01:21:38	# io_result='{
  "tick_rate": 2494212908,
  "ticks": 577268109916,
  "bdevs": [
    {
      "name": "Null_1",
      "bytes_read": 171792797696,
      "num_read_ops": 41941594,
      "bytes_written": 0,
      "num_write_ops": 0,
      "bytes_unmapped": 0,
      "num_unmap_ops": 0,
      "read_latency_ticks": 14734415150830,
      "write_latency_ticks": 0,
      "unmap_latency_ticks": 0
    }
  ]
}'
  01:21:38	# '[' BANDWIDTH = IOPS ']'
   01:21:38	# echo '{' '"tick_rate":' 2494212908, '"ticks":' 577268109916, '"bdevs":' '[' '{' '"name":' '"Null_1",' '"bytes_read":' 171792797696, '"num_read_ops":' 41941594, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 14734415150830, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   01:21:38	# jq -r '.bdevs[0].bytes_read'
  01:21:38	# io_result_after=171792797696
   01:21:38	# echo '{' '"tick_rate":' 2494212908, '"ticks":' 577268109916, '"bdevs":' '[' '{' '"name":' '"Null_1",' '"bytes_read":' 171792797696, '"num_read_ops":' 41941594, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 14734415150830, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   01:21:38	# jq -r .ticks
  01:21:38	# ticks_after=577268109916
  01:21:38	# '[' BANDWIDTH = IOPS ']'
  01:21:38	# io_result_diff=6107068
  01:21:38	# echo 967309
 01:21:38	# qos_result=967309
 01:21:38	# '[' BANDWIDTH = BANDWIDTH ']'
 01:21:38	# qos_limit=1144832
 01:21:38	# lower_limit=1030348
 01:21:38	# upper_limit=1259315
 01:21:38	# '[' 967309 -lt 1030348 ']'
 01:21:38	# echo 'Failed to limit the io read rate of NULL bdev by qos'
Failed to limit the io read rate of NULL bdev by qos

**Comment by Comphix** [comment]
Would like to monitor whether there are other similar failures.

Looking at one of the successful instance https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/56611/archive/freebsd_autotest/build.log,

It looks like the calculation is precise.

  18:54:15	# tick_rate=2494199934
   18:54:15	# echo '{' '"tick_rate":' 2494199934, '"ticks":' 1353493339048, '"bdevs":' '[' '{' '"name":' '"Null_0",' '"bytes_read":' 71972929536, '"num_read_ops":' 17571509, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 14484521049376, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   18:54:15	# jq -r .ticks
  18:54:15	# ticks_before=1353493339048
  18:54:15	# sleep 5
   18:54:21	# /var/jenkins/workspace/Other_systems/freebsd_autotest/spdk/scripts/rpc.py bdev_get_iostat -b Null_0
  18:54:21	# io_result='{
  "tick_rate": 2494199934,
  "ticks": 1367252788040,
  "bdevs": [
    {
      "name": "Null_0",
      "bytes_read": 71984492544,
      "num_read_ops": 17574332,
      "bytes_written": 0,
      "num_write_ops": 0,
      "bytes_unmapped": 0,
      "num_unmap_ops": 0,
      "read_latency_ticks": 17935505580836,
      "write_latency_ticks": 0,
      "unmap_latency_ticks": 0
    }
  ]
}'
  18:54:21	# '[' BANDWIDTH = IOPS ']'
   18:54:21	# echo '{' '"tick_rate":' 2494199934, '"ticks":' 1367252788040, '"bdevs":' '[' '{' '"name":' '"Null_0",' '"bytes_read":' 71984492544, '"num_read_ops":' 17574332, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 17935505580836, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
   18:54:21	# jq -r '.bdevs[0].bytes_read'
  18:54:21	# io_result_after=71984492544
   18:54:21	# jq -r .ticks
   18:54:21	# echo '{' '"tick_rate":' 2494199934, '"ticks":' 1367252788040, '"bdevs":' '[' '{' '"name":' '"Null_0",' '"bytes_read":' 71984492544, '"num_read_ops":' 17574332, '"bytes_written":' 0, '"num_write_ops":' 0, '"bytes_unmapped":' 0, '"num_unmap_ops":' 0, '"read_latency_ticks":' 17935505580836, '"write_latency_ticks":' 0, '"unmap_latency_ticks":' 0 '}' ']' '}'
  18:54:21	# ticks_after=1367252788040
  18:54:21	# '[' BANDWIDTH = IOPS ']'
  18:54:21	# io_result_diff=11292
  18:54:21	# echo 2046
 18:54:21	# qos_result=2046  <<<<<<
 18:54:21	# '[' BANDWIDTH = BANDWIDTH ']'
 18:54:21	# qos_limit=2048  <<<<<
 18:54:21	# lower_limit=1843
 18:54:21	# upper_limit=2252
 18:54:21	# '[' 2046 -lt 1843 ']'
 18:54:21	# '[' 2046 -gt 2252 ']'

The exact spent time is (1367252788040 - 1353493339048) / 2494199934 = 5.51 seconds

**Comment by Comphix** [comment]
Looking at the recent builds on FreeBSD for QoS, it looks like there is no this kind of error.

https://10.102.17.104:8080/job/Other_systems/job/freebsd_autotest/buildTimeTrend

Keep this in low priority and open for some time.

**Comment by Comphix** [comment]
Checked the recent QoS running on FreeBSD at https://10.102.17.104:8080/job/Other_systems/job/freebsd_autotest/buildTimeTrend

There are three recent failures which is not relating to QoS.

Would like to close this issue and if we see a new one. We could either file a new issue or reopen this one.

Thanks, Gang

**Comment by shuhei-matsumoto** [comment]
Hi Gang,

Ubuntu 18  failed to satisfy QoS limit once.
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58654.html

I file it here for just in case.

-Shuhei

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58654.html
