### ISSUE TITLE
VMs timing out due to extremely long build times

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1137]
This is happening on a lot of test runs.  A VM will fail somewhere random during the test due to hitting the max amount of time.  When you look at the time stamps, you'll see that the build itself is taking 8-10 minutes.

Links coming...

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55203.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55202.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55145.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55070.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55067.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55068.html

**Comment by jimharris** [comment]
(Moved from #1131)
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55072.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55414.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55429.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55065.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56415.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56428.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58546.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @darsto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59808.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60021.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4305.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4314.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_4535.html

**Comment by tomzawadzki** [comment]
Most of the recent logs display following message in dmesg.
```
[34277.341325] nfs: server 192.192.192.2 not responding, timed out
[34277.341523] nfs: server 192.192.192.2 not responding, still trying
```
This looks somewhat related as the time outs occur either in building at beginning of tests or at autopackage.
I know there are some changes coming in regards to getting rid of nfs, @karlatec can you give some update on that ?
Lets revisit this issue after the change.

**Comment by karlatec** [comment]
That's EXACTLY what I saw on CentOS VMs and you can see it in the report by Shuhei 4 days ago (I think that was before I disabled NFS on these VMs)

I can see the problem on Ubuntu18 VMs as well, so I think these are next in line to remove NFS.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_4851.html

**Comment by karlatec** [comment]
Long time since this issue was last seen. Closing.
