### ISSUE TITLE
iscsi filesystem test in CI: mkfs error Device or resource busy

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1141]
mkfs.xfs: cannot open /dev/sdb1: Device or resource busy

**Comment by tomzawadzki** [comment]
[Bug scrub] Paul please post a log so that MaciekW could help with resolving this. There were similar issues in vhost and nvmf that he has been fixing.

**Comment by peluse** [comment]
I must have messed up when I added the "false positive" to the review for this item, I can't find it anywhere.  Sorry.  If there are no others like this we should probably just close it

**Comment by jimharris** [comment]
Closing.  We can reopen if this pops up again and we can point to a failing build log.

**Comment by Donaim** [comment]
Look like another one of this: https://ci.spdk.io/results/autotest-spdk-19-10-vs-dpdk-master/builds/1245/archive/iscsi_autotest_nightly/build.log
So reopening

**Comment by tomzawadzki** [comment]
There are two parts to this issue:

1. `mkfs.xfs: cannot open /dev/sdb1: Device or resource busy` 
Which requires similar fix as that of #1024, basically retrying again. For more places than iSCSI tests actually.
2. `iscsi_tgt: bdev.c:4521: spdk_bdev_close: Assertion `desc->thread == spdk_get_thread()' failed.`
This one is similar to some of the patches resolving #1146, like here b3be320de4ececb82f168df4c5cc193ab0935615. This would require similar change to apply to lvols too.

**Comment by tomzawadzki** [comment]
> 1. `mkfs.xfs: cannot open /dev/sdb1: Device or resource busy`
>    Which requires similar fix as that of #1024, basically retrying again. For more places than iSCSI tests actually.

Patch submitted here:
https://review.spdk.io/gerrit/c/spdk/spdk/+/1178

**Comment by AlekseyMarchuk** [comment]
It seems to be fixed, should we close it?
