### ISSUE TITLE
nvmf_example_test failes: spdk_nvmf_subsystem_set_state: Assertion `actual_old_state == expected_old_state' failed.

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1143]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55724.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_55730.html

**Comment by Seth5141** [comment]
This is broken on master. You will have to rebase on this change which fixes the big. https://review.gerrithub.io/c/spdk/spdk/+/480007

**Comment by tomzawadzki** [comment]
Fix was merged - thanks @Seth5141 ! This issue is now fixed on master, please rebase if you see this error.
