### ISSUE TITLE
Freebsd don't support --no-headers option for ps command

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1145]
killprocess function caused the following error on freebsd.

> 01:21:38 # ps --no-headers -o comm= 21419
> ps: illegal option -- -
> usage: ps [-aCcdefHhjlmrSTuvwXxZ] [-O fmt | -o fmt] [-G gid[,gid...]]
> [-J jid[,jid...]] [-M core] [-N system]
> [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
> ps [-L]
> 01:21:38 # '[' '' = sudo ']'
> 01:21:38 # echo 'killing process with pid 21419'
> killing process with pid 21419
> 01:21:38 # kill 21419
> 01:21:38 # wait 21419
> 01:21:38 # exit 1

This issue was separated from https://github.com/spdk/spdk/issues/1136

We will have to consider different method to remove headers of ps output on freebsd.
https://stackoverflow.com/questions/11532188/how-to-get-rid-of-the-headers-in-a-ps-command-in-mac-os-x

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/970

**Comment by jimharris** [comment]
Patch was merged.
