### ISSUE TITLE
nvmf random failure

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1147]
On TP I got following error in test nvmf_example:
nvmf: subsystem.c:425: spdk_nvmf_subsystem_set_state: Assertion `actual_old_state == expected_old_state' failed.

Log to this error https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/55647/archive/nvmf_phy_autotest/build.log

**Comment by jimharris** [comment]
Please rebase from latest master. This issue has already been fixed.
