### ISSUE TITLE
SPDK reported error after killing spdk tgt if using SPDK VMD devices

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#1148]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior
No error out.

## Current Behavior
SPDK reported error:
Device 0000:d7:05.5 is still attached at shutdown!

## Possible Solution
The Device 0000:d7:05.5 is the vmd device. so I think we need to some shutdown codes in the vmd driver.

## Steps to Reproduce

1. enable vmd in the BIOS;
2. get current vmd devices:
$lspci|grep 201d
d7:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)
3. run setup.sh:
PCI_WHITELIST="0000:d7:05.5" ./scripts/setup.sh
4. run spdk tgt:
$./app/spdk_tgt/spdk_tgt --wait-for-rpc 
5. in another terminal, run rpc command to enable vmd:
./scripts/rpc.py enable_vmd
6. back to the original terminal, use ctrlr+c to kill the spdk target.

## Context (Environment including OS version, SPDK version, etc.)
SPDK COMMIT:241d04467dd79b5be05939e016c3de07e76f1664

**Comment by liang2yan** [comment]
@ksztyber , any comment about this issue?

**Comment by ksztyber** [comment]
@liang2yan yeah it does look like the VMD library doesn't detach the PCI devices it uses. I'll post a patch fixing this soon.

**Comment by ksztyber** [comment]
Here's the patch: https://review.gerrithub.io/c/spdk/spdk/+/482852.
