### ISSUE TITLE
spdk_tgt: " Assertion `thread->msg_cache_count == 0' failed" in nvme_autotest

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1149]
## Current Behavior
Hit an assert during shutdown of NVMe drive in FTL restore NVMe test

## Steps to Reproduce
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/56314/archive/nvme_autotest/build.log

## Context (Environment including OS version, SPDK version, etc.)
Test Pool, fedora_vm_5

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_56314.html

**Comment by tomzawadzki** [comment]
[Bug scrub] Lets keep look at the number of occurrences of this issue.

**Comment by wmalikow** [comment]
Could be potentially related with recent changes  in thread.c (merged yesterday):
https://review.gerrithub.io/c/spdk/spdk/+/478290/8
I will look closer to this issue.

**Comment by jimharris** [comment]
I just took a look at this patch again, and it doesn't touch the msg pool at all.  The critical_msg is handled completely independent of any actual msg object.

**Comment by mmkayPL** [comment]
The patch on which this failure occurred didn't have the critical message changes yet and I believe that this is the same issue as in #1105 . The FTL code is using regular spdk_thread_send_msg calls and if the test sent a kill signal to the app while the program is running in thread.c:716-719 with msg_cache_count = 1, then the assert would be hit.

**Comment by jimharris** [comment]
Oh - yeah that makes perfect sense. Good catch.
