### ISSUE TITLE
can't run fio plugin and got some error message

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1150]
I run fio plugin and got the following error message :
`illegal instruction (core dumped)`

but I can run original fio normally on the same PC.
I also tried to run fio plugin with another PC, and it's work.
It looks like this problem  is with specific PC,
Has anyone experienced this problem?please help to check it, thanks!

## Context (Environment including OS version, SPDK version, etc.)
fio-3.9
OS: ubuntu 19.04
Linux Kernel: 5.4
SPDK: 20.01
DPDK:19.08.0

**Comment by optimistyzy** [comment]
@ryderhsu0129 More details need to be provided, e.g., environment, how do you test it

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 More details need to be provided, e.g., environment, how do you test it
thanks for your reply.
I have added information.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 More details need to be provided, e.g., environment, how do you test it

@optimistyzy 
I search this error message and someone made the point that my CPU does not support the AVX instruction set, but application(SPDK fio plugin?) prebuilt binaries require the AVX instruction set extensions.
if so how can I fix this error and run fio flugin successfully?

**Comment by jiaqizho** [comment]
hi ruderhusu0129
do you compile spdk and fio_plugin by right steps? 
and can you provided more infomation about run fio_plugin. (include config file , command , before run what you do)?

**Comment by ryderhsu0129** [comment]
> hi ruderhusu0129
> do you compile spdk and fio_plugin by right steps?
> and can you provided more infomation about run fio_plugin. (include config file , command , before run what you do)?

hi @jiaqizho 
I compile spdk and fio_plugin by officially SPDK instructed steps, and it's can run normally on my PC.
and I installed my system disk(this means the SPDK environment is same) on anther PC, fio flugin can't run and just show the error message `illegal instruction (core dumped)`.

I only run /script/setup.sh to bind uio driver before running fio plugin, and my fio config file is as follows :
```
[Global]
ioengine=/usr/src/spdk/examples/nvme/fio_plugin/fio_plugin
direct=1
rw=write
rwmixwrite=100
thread=1
norandommap=1
time_based=1
runtime=60
ramp_time=10
bs=4160
pi_act=0
pi_chk=GUARD|REFTAG|APPTAG
iodepth=32
numjobs=1
percentile_list=99:99.9:99.99:99.999:99.9999:100
filename=trtype=PCIe traddr=0000.01.00.0 ns=1
```

**Comment by optimistyzy** [comment]
@ryderhsu0129 "I compile spdk and fio_plugin by officially SPDK instructed steps, and it's can run normally on my PC.
and I installed my system disk(this means the SPDK environment is same) on anther PC, fio flugin can't run and just show the error message illegal instruction (core dumped)."

I think that you need to rebuild on another machine. Since when building SPDK/DPDK, it will check the instructions on the platform. Then the two machines seems not having the same CPU instruction set.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 "I compile spdk and fio_plugin by officially SPDK instructed steps, and it's can run normally on my PC.
> and I installed my system disk(this means the SPDK environment is same) on anther PC, fio flugin can't run and just show the error message illegal instruction (core dumped)."
> 
> I think that you need to rebuild on another machine. Since when building SPDK/DPDK, it will check the instructions on the platform. Then the two machines seems not having the same CPU instruction set.

@optimistyzy 
I rebuild SPDK and fio on another machine, it's work to run fio plugin,
thanks for your suggestion.

**Comment by optimistyzy** [comment]
> > @ryderhsu0129 "I compile spdk and fio_plugin by officially SPDK instructed steps, and it's can run normally on my PC.
> > and I installed my system disk(this means the SPDK environment is same) on anther PC, fio flugin can't run and just show the error message illegal instruction (core dumped)."
> > I think that you need to rebuild on another machine. Since when building SPDK/DPDK, it will check the instructions on the platform. Then the two machines seems not having the same CPU instruction set.
> 
> @optimistyzy
> I rebuild SPDK and fio on another machine, it's work to run fio plugin,
> thanks for your suggestion.

Glad to see this this. Actually, if you want to run the binary build from one platform to another. You need better to use cross-platform compilation tool.  For DPDK, it is highly optimized and detect the CPU type and utilize optimized instruction if it can.

**Comment by sarvanireddy** [comment]
@optimistyzy ,
I am also facing the same issue as @ryderhsu0129 . can you please provide instructions and tools to use that can cross compile and create a fio binary to run across different platforms.

Thanks.
