### ISSUE TITLE
SPDK will crash when invoking apply_firmware RPC method

### ISSUE THREAD

**Issue by ufo19890607** [spdk/spdk#1151]
## Issue Description
SPDK will crash when I invoke apply_firmware RPC method without a right firmware file.

## Test Env
SPDK version: SPDK v19.10-pre
DPDK version: DPDK 19.11.0-rc0
OS: 		        centos7.4
vmd: 		enabled

## Reproducing Scenario
1. Start SPDK with the following commands
```
$ ./app/vhost/vhost -m 0x1000010 -s 2048 -S /var/run/spdk -c /usr/local/etc/spdk/vhost.conf
```
2. Invoke apply_firmware RPC
```
$ ./scripts/rpc.py apply_firmware xxxx 272869e5-3721-463e-9d5b-d7ab22f7fbf7-nvmen1
```

## Root Cause
I checked the callstack when spdk crashed, and found that the wild pointer was in the
spdk_json_decode_string func which had freed a char **s pointer. Actully, this pointer
is struct rpc_apply_firmware *req in the spdk_rpc_bdev_nvme_apply_firmware, and it will be passed into spdk_json_decode_object. I don't know why spdk_json_decode_string needs
to free this object.

I add some print info in this function, and call apply_firmware and get_bdevs RPC.
```
int
spdk_json_decode_string(const struct spdk_json_val *val, void *out)
{
        char **s = out;
        printf("out=%p\n", *s);
        free(*s);

        *s = spdk_json_strdup(val);

        if (*s) {
                return 0;
        } else {
                return -1; 
        }
}
```
```
get_bdevs
$ ./scripts/rpc.py get_bdevs -b 272869e5-3721-463e-9d5b-d7ab22f7fbf7-nvmen1
...

spdk output
...
rpc.c: 122:spdk_jsonrpc_handler: *WARNING*: RPC method get_bdevs is deprecated.  Use bdev_get_bdevs instead.
out=(nil)
...


apply_firmware
$ ./scripts/rpc.py apply_firmware xxxx 272869e5-3721-463e-9d5b-d7ab22f7fbf7-nvmen1

spdk output
rpc.c: 122:spdk_jsonrpc_handler: *WARNING*: RPC method apply_nvme_firmware is deprecated.  Use bdev_nvme_apply_firmware instead.
out=0x7f69e4d6d7c8
```

We can see void *out is NULL or a wild pointer, so I think we should not free in this func.

## Bug Solution
I think void *out is no use for spdk_json_decode_string, so it should be deleted.
```
int
spdk_json_decode_string(const struct spdk_json_val *val)
{
	char **s;
	
	*s = spdk_json_strdup(val);

	if (*s) {
		return 0;
	} else {
		return -1;
	}
}
```
Moreover, any funcs which calls this func should be modified, too.

[crash.txt](https://github.com/spdk/spdk/files/4058989/crash.txt)
[vhost.conf](https://github.com/spdk/spdk/files/4058990/vhost.txt)

**Comment by tomzawadzki** [comment]
[Bug scrub]: Besides fixing this issue some parts of this RPC need to be part of autotest.sh [not actually applying firmware to the controller]. As well as separate test outside of autotest.sh that would test this RPC with a VM and virtualized controller.

**Comment by tkulasek** [comment]
out points "char *field" in the "struct rpc_apply_firmware". In this particular call malloc is used for memory allocation and we cannot be sure it's zeroed. In other calls, which have no this issue calloc is used and *out == NULL, so free(*out) is ineffective.

I don't think we should remove "out" parameter, it will imply to rework also another decoders.

Instead malloc should be replaced with calloc and we should leave free() to make sure there's no memory leak when spdk_json_decode_string is called twice for the same field.

**Comment by tkulasek** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/483107

**Comment by peluse** [comment]
@benlwalker to review and decide whether to merge or not
