### ISSUE TITLE
bdev_ocssd: Received invalid zone starting LBA

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1152]
Failures occur on ftl_bdevperf test that runs on nightly jobs.

Issue started between commits 1437b25472597b928e117988420b52ce49e2afbb and 6c2747491d7840413caa393cc0f1be0c22b9e94b, most likely pointing to changes in series starting [here](https://review.gerrithub.io/c/spdk/spdk/+/479701/5).

```
 20:36:40	# /var/jenkins/workspace/NVMe_tests/nvme_autotest_nightly/spdk/scripts/rpc.py bdev_nvme_attach_controller -b nvme0 -a 0000:00:0d.0 -t pcie

 20:36:41	# /var/jenkins/workspace/NVMe_tests/nvme_autotest_nightly/spdk/scripts/rpc.py bdev_ocssd_create -c nvme0 -b nvme0n1
bdev_ocssd.c:1004:bdev_occsd_init_zone_cb: *ERROR*: Received invalid zone starting LBA: 2211840
request:
{
  "ctrlr_name": "nvme0",
  "bdev_name": "nvme0n1",
  "method": "bdev_ocssd_create",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -22,
  "message": "Invalid argument"
}
```

Link to nightly logs:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/1406/archive/nvme_autotest_nightly/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/1407/archive/nvme_autotest_nightly/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/1408/archive/nvme_autotest_nightly/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/1409/archive/nvme_autotest_nightly/index.html

## Context (Environment including OS version, SPDK version, etc.)
Nightly jobs on CI - nvme_autotest_nightly.

**Comment by tomzawadzki** [comment]
@wmalikow @ksztyber thanks for pointers offline !

Turns out that nightly machines are one QEMU commit back compared to per-patch ones.
@Seth5141 can you take a look at making sure that QEMU on nightly machines have latest spdk/qemu patch https://github.com/spdk/qemu/commit/575b52eccb83dae60e73df9548f7475d631f0bec ?

**Comment by Seth5141** [comment]
@tomzawadzki Done, thanks!

@wmalikow, @karlatec Who is responsible for updating the QEMU version for all of the hosts in Gdansk? If I include the IP address of the host in CHandler on the jenkins documentation, can that person also update the QEMU version on that machine? That will be more robust than having me manage them separately because I think changes like this either don't get forwarded to me, or get lost in my inbox (probably what is actually happening). If only one person does the updates, we can avoid mismatches like this in the future.

**Comment by tomzawadzki** [comment]
@Seth5141 Thanks ! Checking nightly results, it seems that this has been fixed.

As for the updates, we do them ad-hoc and manually since QEMU rarely gets patches on spdk/qemu.
@karlatec mentioned that this has been previously requesting that particular change, but might have been lost on the way. From now on, we will communicate QEMU changes and do it for both locations for CI.
