### ISSUE TITLE
Failed to bind NVMe to UIO under RHEL 8

### ISSUE THREAD

**Issue by igorkonopko** [spdk/spdk#1153]
When using RHEL 8.1 with official kernel from distribution (4.18.0-147.el8.x86_64) it is not possible to bind nvme devices to uio_pci_generic driver and due to that to use them within SPDK environment:

> [82734.333834] genirq: Threaded irq requested with handler=NULL and !ONESHOT for irq 113
> [82734.341761] uio_pci_generic: probe of 0000:18:00.0 failed with error -22

The issue was previously reported in SPDK bugzilla [here](https://github.com/spdk/spdk/issues/399) for vanilla kernel 4.18. Unfortunately the kernel used in RHEL 8 does not contain the proper [bugfix](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.18.y&id=a34e4f42055a7fe8e804fc9e71dfc1e324c657f1) backported.

Even that this issue is not directly caused by spdk code, it still makes impossible to use SPDK in such a configuration, so probably should be tracked here in order to find some solution/workaround, since RHEL is rather important distribution for the enterprise.

## Expected Behavior
NVMe devices can be used within SPDK environment when using RHEL 8 as OS.

## Current Behavior
NVMe devices are not visible within SPDK environment (since they are not bind to any pcie driver).

## Possible Solution
Manually applying the missing commit into the RHEL 8 uio module source code and rebuilding it solves the issue.

## Steps to Reproduce
1. Boot into RHEL 8.1 with official kernel
2. Run setup.sh script
3. Try to use any of the nvme devices within SPDK environment.

## Context (Environment including OS version, SPDK version, etc.)
RHEL 8.1 with official kernel 4.18.0-147.el8.x86_64 (I didn't test RHEL 8.0 kernel, but based on changelog the issue should occur there too).
SPDK changeset: 159703c9dc6f7ff6750c6a6a59c86a15e06b4390

**Comment by ak-gh** [comment]
Just for me to understand, is CentOS 8 also impacted?

Thanks,
Andrey

**Comment by igorkonopko** [comment]
I didn't run it on CentOS 8, but since the kernel is the same, it should be impacted too.

**Comment by ak-gh** [comment]
Thanks.

**Comment by jimharris** [comment]
Hi @igorkonopko,

Do you have VMD enabled on this system?

-Jim

**Comment by igorkonopko** [comment]
I have both NVMe drives directly attach and behind a VMD in that setup. Issue is related to directly attach NVMe (without VMD). It looks that it is also related to I/OAT DMA. I didn't test the drives behind the VMD.

**Comment by peluse** [comment]
Try this on CentoOS 8 @wawryk

**Comment by mhae** [comment]
We have the same issue on CentOS. It's the 4.18 kernel. It is fairly easy to fix the driver. I did it once.

**Comment by tomzawadzki** [comment]
[Bug scrub] This could worked around by using igb_uio. Unfortunately since this is third-party issue, not much can be done right now.
We can verify if CentOS 8.2 beta contains this fix and will post docs update for this information.

**Comment by Seth5141** [comment]
doc fix here: https://review.spdk.io/gerrit/c/spdk/spdk/+/814/1
