### ISSUE TITLE
set_compress_pmd method not found when running compress.sh

### ISSUE THREAD

**Issue by dnzlike** [spdk/spdk#1154]
I met this issue when I tried to run the compress test /test/compress/compress.sh
```
  16:31:29       # /root/spdk/scripts/rpc.py set_compress_pmd -p 1
request:
{
  "pmd": 1,
  "method": "set_compress_pmd",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"
}
  16:31:29      # trap - ERR
  16:31:29      # print_backtrace
  16:31:29      # [[ ehxBE =~ e ]]
  16:31:29      # xtrace_disable
  16:31:29      # '[' no '!=' yes ']'
  16:31:29      # PREV_BASH_OPTS=ehxBE
  16:31:29      # [[ ehxBE == *\x* ]]
  16:31:29      # XTRACE_DISABLED=yes
  16:31:29      # set +x
```
And then I started a spdk_tgt and tried to run `set_compress_pmd` and `bdev_compress_create`, but found out both methods are not found even in `rpc_get_methods`. I think it lacks some certain dependencies so I added `--with-reduce` to `./configure` (I think it has something to do with compress) but it remains no change. (Also tried several other parameters)
## Expected Behavior

./compress.sh successfully execute
## Current Behavior

```
request:
{
  "pmd": 1,
  "method": "set_compress_pmd",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"
}
```
## Possible Solution

Add some dependencies to current environment
## Steps to Reproduce

1. ./configure --with-reduce
2. make
3. ./test/compress/compress.sh

## Context (Environment including OS version, SPDK version, etc.)

CentOS Linux release 7.4.1708 (Core)
Linux version 3.10.0-693.17.1.el7.x86_64
SPDK v20.01-pre git sha1 6c27474

**Comment by jimharris** [comment]
@peluse - could you give @dnzlike some guidance here?  The RPCs are definitely in the code - it's certainly some kind of dependency issue on the submitter's end.

I also noticed just now that we didn't rename this "set_compress_pmd" method to match the other RPCs in that file that we recently renamed/deprecated.  Could you take a look at that too?

Thanks!

-Jim

**Comment by peluse** [comment]
yup, looking now...

**Comment by peluse** [comment]
1) @dnzlike  so I'm not sure why this is failing - I ran just now t on Ubuntu 18.01 w/master this works fine - as it should since the script you're running runs in CI all of the time including on CentOS 7.  Can you try doing a make clean first and re-running.  Maybe this time paste in the full output of every command and make sure you don't see this msg after running configure:
                echo --with-reduce requires libpmem.
                echo Please install then re-run this script.

2) @jimharris I suspect the RPC in question wasn't on the "list of things to rename" maybe because it didn't exist yet when the list was created.  I'll push a patch later to rename it to compress_set_pmd

**Comment by jimharris** [comment]
Yeah - totally agree on #2.  Either it didn't exist yet, or I may have just missed it in that list that I put together.

**Comment by peluse** [comment]
@dnzlike also note that this is a script designed to run in our CI system and expects a QAT device to be present, if you don't have one you'll get the error below which isn't what you're seeing - just letting you know.  If you want to run it in a machine without QAT just change that "set_compress_pmd -p 1" to "set_compress_pmd -p 0"

 16:03:58	# /home/peluse/spdk/scripts/rpc.py set_compress_pmd -p 1
 16:03:58	# /home/peluse/spdk/scripts/rpc.py bdev_compress_create -b lvs0/lv0 -p /tmp/pmem
vbdev_compress.c:1282:_set_pmd: *ERROR*: Requested PMD is not available.
vbdev_compress.c:1302:vbdev_init_reduce: *ERROR*: could not find required pmd

**Comment by dnzlike** [comment]
@peluse Thank you for your response. Sorry forgot to check this because of spring festival things. I did a make clean and re-run the configure and found a NOTICE which I didn't take a look. It's the nasm version didn't match. But now I encounter another question. I do have a QAT device on my server but when I run compress.sh it still shows
```
vbdev_compress.c:1282:_set_pmd: ERROR: Requested PMD is not available.
vbdev_compress.c:1302:vbdev_init_reduce: ERROR: could not find required pmd
```
Does it need any configure to recognize the QAT device?

**Comment by peluse** [comment]
@dnzlike no problem. As I mentioned before, this script requires QAT (it runs in our CI). You can make one small change though to make it work without QAT.  Just just change "set_compress_pmd -p 1" to "set_compress_pmd -p 0"

**Comment by dnzlike** [comment]
@peluse yes sir, I **have** a QAT card on my server, and it works well with other QAT examples. But when I run the above script, it still shows this problem. I need the QAT card to do some compress work, does it need any configure to recognize the QAT card? By the way, what does CI mean?

**Comment by peluse** [comment]
@dnzlike  CI means contiguous integration, its the system that performs tests on all code in the SPDK repo when patches are submitted. Try running /scripts/qat_setup.sh and let us know what that output looks like, this is a required step before using QAT with SPDK. Thanks

**Comment by dnzlike** [comment]
```
[root@qat-server-185 spdk]# ./configure --with-reduce --with-igb-uio-driver
Using default SPDK env in /root/spdk/lib/env_dpdk
Using default DPDK in /root/spdk/dpdk/build
Configuring ISA-L (logfile: /root/spdk/isa-l/spdk-isal.log)...done.
Creating mk/config.mk...done.
Creating mk/cc.flags.mk...done.
Type 'make' to build.
[root@qat-server-185 spdk]# make clean
[root@qat-server-185 spdk]# ./configure --with-reduce --with-igb-uio-driver
Using default SPDK env in /root/spdk/lib/env_dpdk
Using default DPDK in /root/spdk/dpdk/build
Configuring ISA-L (logfile: /root/spdk/isa-l/spdk-isal.log)...done.
Creating mk/config.mk...done.
Creating mk/cc.flags.mk...done.
Type 'make' to build.
[root@qat-server-185 spdk]# make -j

...

[root@qat-server-185 scripts]# ./qat_setup.sh
Restarting all devices.
Processing /etc/c6xx_dev0.conf
Processing /etc/c6xx_dev1.conf
Processing /etc/c6xx_dev2.conf
Checking status of all devices.
There is 3 QAT acceleration device(s) in the system:
 qat_dev0 - type: c6xx,  inst_id: 0,  node_id: 0,  bsf: 0000:07:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev1 - type: c6xx,  inst_id: 1,  node_id: 0,  bsf: 0000:09:00.0,  #accel: 5 #engines: 10 state: up
 qat_dev2 - type: c6xx,  inst_id: 2,  node_id: 0,  bsf: 0000:0b:00.0,  #accel: 5 #engines: 10 state: up
failed to start the qat service. Something may be wrong with your 01.org driver.
0000:07:00.0 set to 16 VFs
0000:09:00.0 set to 16 VFs
0000:0b:00.0 set to 16 VFs
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.0
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.1
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.2
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.3
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.4
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.5
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.6
unbinding driver c6xxvf from qat VF at BDF 0000:07:01.7
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.0
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.1
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.2
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.3
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.4
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.5
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.6
unbinding driver c6xxvf from qat VF at BDF 0000:07:02.7
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.0
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.1
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.2
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.3
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.4
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.5
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.6
unbinding driver c6xxvf from qat VF at BDF 0000:09:01.7
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.0
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.1
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.2
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.3
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.4
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.5
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.6
unbinding driver c6xxvf from qat VF at BDF 0000:09:02.7
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.0
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.1
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.2
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.3
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.4
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.5
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.6
unbinding driver c6xxvf from qat VF at BDF 0000:0b:01.7
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.0
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.1
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.2
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.3
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.4
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.5
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.6
unbinding driver c6xxvf from qat VF at BDF 0000:0b:02.7
ls: cannot access /sys/bus/pci/devices/0000:07:01.0/driver: No such file or directory
unable to bind the driver to the device at bdf 0000:07:01.0
Your kernel's uio_pci_generic module does not support binding to virtual functions.
It likely is missing Linux git commit ID acec09e67 which is needed to bind
uio_pci_generic to virtual functions which have no legacy interrupt vector.
Please rebuild spdk with --with-igb-uio-driver and re-run this script specifying the igb_uio driver.
```
@peluse  Noticing the last line, so I add the --with-igb-uio-driver and re make it.

**Comment by jimharris** [comment]
@dnzlike @peluse What are the next steps on this?  It looks like @dnzlike needs to run qat_setup.sh like this?

scripts/qat_setup.sh igb_uio

Is there anything else?

**Comment by peluse** [comment]
@dnzlike sorry I didn't see your update until just now. @jimharris yeah your suggestion looks right.  If that doesn't work I can help build from source as that's how I had to get it working on one of my dev systems.  QAT isn't the easiest thing to get setup (nothing to do with SPDK)

**Comment by dnzlike** [comment]
@peluse @jimharris Thanks for your generous help, It works with the command 
/qat_setup.sh igb_uio
please help close this issue
