### ISSUE TITLE
Spdk_lspci failed to detect Intel NVMe P4500 devices

### ISSUE THREAD

**Issue by ufo19890607** [spdk/spdk#1155]
Hi guys.
Recently I found a strange issue that Intel NVMe P4500 devices cannot be detected by spdk_lspci.

OS: centos7.4
kernel version: 3.10.0-693.el7.x86_64
SPDK version: v19.10-pre
commit: b422cee
DPDK version: 19.11.0-rc0
nvme: P4500
vmd: enabled
```
[root@kvm_9_27_142_108 ~]# lspci |grep Non
10000:01:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:02:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:03:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:04:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
[root@kvm_9_27_142_108 ~]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     PHLF8021001Y4P0IGN   INTEL SSDPE2KX040T7                      1           4.00  TB /   4.00  TB      4 KiB +  0 B   QDV10170
/dev/nvme1n1     PHLF802300QT4P0IGN   INTEL SSDPE2KX040T7                      1           4.00  TB /   4.00  TB      4 KiB +  0 B   QDV10150
/dev/nvme2n1     PHLF803000J84P0IGN   INTEL SSDPE2KX040T7                      1           4.00  TB /   4.00  TB      4 KiB +  0 B   QDV101D1
/dev/nvme3n1     PHLF802300E44P0IGN   INTEL SSDPE2KX040T7                      1           4.00  TB /   4.00  TB      4 KiB +  0 B   QDV101D1
```

I've exported PCI_WHITELIST to scripts/setup.sh, and below is the output of spdk_lspci
```
[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-upstream]# HUGEMEM=204800 scripts/setup.sh
10000:01:00.0 (8086 0a54): Skipping un-whitelisted NVMe controller at 10000:01:00.0
10000:02:00.0 (8086 0a54): Skipping un-whitelisted NVMe controller at 10000:02:00.0
10000:03:00.0 (8086 0a54): Skipping un-whitelisted NVMe controller at 10000:03:00.0
10000:04:00.0 (8086 0a54): Skipping un-whitelisted NVMe controller at 10000:04:00.0
...
0000:ae:05.5 (8086 201d): vmd -> vfio-pci
 VMD generic kdrv:  0000:ae:05.5 vfio-pci

[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-upstream]# ./app/spdk_lspci/spdk_lspci 
Starting SPDK v19.10-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid432785 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)

List of available PCI devices:
0000:ae:05.5 (8086 201d) (VMD) 
```

**Comment by Seth5141** [comment]
@ufo19890607 What is the value of $PCI_WHITELIST? It looks like setup.sh is intentionally skipping your drives because they aren't included in $PCI_WHITELIST. You can probably actually unset that variable entirely if you intend on using all of those drives with SPDK. The default behavior of that script is to bind all NVMe drives without an active mountpoint.

**Comment by liang2yan** [comment]
@ufo19890607 , can you try to run setup.sh reset and then run setup.sh again? If you have run setup.sh before inserting P4500. From your log, I think your codes doesn't support hotplug/hotremove.

**Comment by ufo19890607** [comment]
@Seth5141 @liang2yan 
```
[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-upstream/scripts]# cat setup.sh |head
#!/usr/bin/env bash

set -e

PCI_WHITELIST="0000:ae:05.5"
rootdir=$(readlink -f $(dirname $0))/..
source "$rootdir/scripts/common.sh"

[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-upstream/scripts]# lspci |grep RAID
0000:18:00.0 RAID bus controller: LSI Logic / Symbios Logic MegaRAID SAS-3 3108 [Invader] (rev 02)
0000:ae:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)
```

**Comment by ufo19890607** [comment]
I still cannot find NVMe devices

**Comment by liang2yan** [comment]
@ufo19890607 , so you have run "setup.sh reset" then "setup.sh" and still can't find the nvme ssd? If you run the "setup.sh reset" command, will the OS list the P4500 NVMe SSD?

**Comment by ufo19890607** [comment]
> @ufo19890607 , so you have run "setup.sh reset" then "setup.sh" and still can't find the nvme ssd? If you run the "setup.sh reset" command, will the nvme command list the P4500 NVMe SSD?

No, I reboot the host.  "setup.sh reset" cannnot reset NVMe ssd.

**Comment by ufo19890607** [comment]
[dmesg.txt](https://github.com/spdk/spdk/files/4086244/dmesg.txt)

I've updated the code from master branch, but spdk_lspci still cannot find NVMe p4500

**Comment by Seth5141** [comment]
Hi @ufo19890607 
The purpose of setup.sh is to unbind the appropriate pci devices from the nvme driver and bind them to vfio-pci or uio_pci_generic depending on whether your IOMMU is enabled.

By default, when you run sudo ./spdk/scripts/setup.sh, it will perform that action on all of your NVMe drives (or the ones that don't have active mountpoints). However, in your copy of setup.sh, you have explicitly set PCI_WHITELIST="0000:ae:05.5". The way setup.sh interprets this is that it will purposefully skip every single pci device except those specified by PCI_WHITELIST which in your case is just a RAID Bus controller. Since your NVMe devices were not ever bound to vfio-pci, SPDK will be unable to detect them.

You need to remove the SPDK_WHITELIST line from your setup.sh file so that your NVMe drives can bind to vfio_pci, then SPDK utilities will be able to detect them and report on their values.

Thanks,

Seth

**Comment by liang2yan** [comment]
@Seth5141 , ufo19890607 is using SPDK VMD driver for the nvme ssd. These nvme ssd are already configured under Intel RAID Bus controller. So I think the PCI_WHITELIST is not problem.

**Comment by ksztyber** [comment]
@ufo19890607 could you try using newer version of SPDK? (from
 ef8966fe93ae2221da1c480edabfaa305fe33989 onward)? There were a couple of fixes incorporated after the v19.10 release.

**Comment by ufo19890607** [comment]
> @ufo19890607 could you try using newer version of SPDK? (from
> [ef8966f](https://github.com/spdk/spdk/commit/ef8966fe93ae2221da1c480edabfaa305fe33989) onward)? There were a couple of fixes incorporated after the v19.10 release.

I've used the latest spdk version, but spdk_lspci still cannot detect P4500 devices if VMD is enabled. This issue will disappear only if VMD is disabled.

By the way, I found that nvme device will shutdown ubnormally when I run setup.sh
```
[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-master]# dmesg |grep shutdown
[ 6214.804155] nvme nvme3: Device shutdown costs 3636 milliseconds
[ 6219.069192] nvme nvme2: Device shutdown costs 3636 milliseconds
[ 6223.527573] nvme nvme1: Device shutdown costs 3838 milliseconds
[ 6228.035934] nvme nvme0: Device shutdown costs 3939 milliseconds
```

**Comment by ksztyber** [comment]
@ufo19890607 could you run `examples/vmd/lsvmd/lsvmd -d` and post the output here?

**Comment by ufo19890607** [comment]
@ksztyber
```
[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-master]# ./examples/vmd/lsvmd/lsvmd -d
Starting SPDK v20.01-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: lsvmd --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid19678 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)
vmd.c:1122:vmd_scan_pcibus: *INFO*: PCIe devices attached to VMD 0000:ae:05:5...
```

**Comment by ksztyber** [comment]
@ufo19890607 is that all? I'd expect there to be a lot more debug output...

**Comment by ufo19890607** [comment]
@ksztyber
Yes. I've attached all of the output information.

**Comment by ksztyber** [comment]
@ufo19890607 did you build the SPDK with debug info enabled (`./configure --enable-debug`)? If not, could you rebuild it with debug info and rerun the app?

**Comment by ufo19890607** [comment]
@ksztyber 
```
[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-master]# ./examples/vmd/lsvmd/lsvmd -d
Starting SPDK v20.01-pre / DPDK 19.11.0-rc0 initialization...
[ DPDK EAL parameters: lsvmd --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid323621 ]
EAL: No available hugepages reported in hugepages-2048kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)
vmd.c:1212:vmd_enum_cb: *DEBUG*: Found a VMD[ 0 ] at 0000:ae:05.5
vmd.c:1229:vmd_enum_cb: *DEBUG*: vmd config bar(0x14ff8000000) vaddr(0x204200000000) size(4000000)
vmd.c:1232:vmd_enum_cb: *DEBUG*: vmd mem bar(0xe8000000) vaddr(0x204204000000) size(4000000)
vmd.c:1235:vmd_enum_cb: *DEBUG*: vmd msix bar(0x14ffc000000) vaddr(0x204208000000) size(4000000)

vmd.c:1117:vmd_scan_pcibus: *DEBUG*: VMD scan found 0 devices
vmd.c:1118:vmd_scan_pcibus: *DEBUG*: VMD scan found 0 END DEVICES
vmd.c:1122:vmd_scan_pcibus: *INFO*: PCIe devices attached to VMD 0000:ae:05:5...
```

**Comment by wmalikow** [comment]
@ufo19890607 I was trying to reproduce this issue but it seems everything is working fine on my environment.

```
spdk: 3424def90a6797e6bc4e634e0e54aa93b33c0b82
kernel: 5.4.17
platform: Server Board S2600WF
I put four P4500 under VMD:

lspci |grep 201d
0000:ae:05.5 RAID bus controller: Intel Corporation Device 201d (rev 04)

lspci | grep Non
10000:03:00.0 Non-Volatile memory controller: Intel Corporation NVMe Datacenter SSD
10000:06:00.0 Non-Volatile memory controller: Intel Corporation NVMe Datacenter SSD 
10000:08:00.0 Non-Volatile memory controller: Intel Corporation NVMe Datacenter SSD 
10000:09:00.0 Non-Volatile memory controller: Intel Corporation NVMe Datacenter SSD 

sudo ./app/spdk_lspci/spdk_lspci 
Starting SPDK v20.04-pre git sha1 3424def90 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: spdk_lspci --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid2805 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)

List of available PCI devices:
ae0505:03:00.0 (8086 a54) (NVMe disk behind VMD) 
ae0505:09:00.0 (8086 a54) (NVMe disk behind VMD) 
ae0505:0d:00.0 (8086 a54) (NVMe disk behind VMD) 
ae0505:0f:00.0 (8086 a54) (NVMe disk behind VMD) 
```

To make progress on this issue we need to determine differences in our environments
- do you have any other devices connected to PCI switch under VMD?
- have you try this on different kernel versions?
- I see that in closed issue that you had reported some time ago - https://github.com/spdk/spdk/issues/1008#issuecomment-546819260  - you were able to detect NVMe drives under VMD - are you using same environment here?

**Comment by ufo19890607** [comment]
@wmalikow 
> do you have any other devices connected to PCI switch under VMD?
```
# lspci
...
10000:00:00.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port 1A (rev 04)
10000:00:01.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port 1B (rev 04)
10000:00:02.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port 1C (rev 04)
10000:00:03.0 PCI bridge: Intel Corporation Sky Lake-E PCI Express Root Port 1D (rev 04)
10000:01:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:02:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:03:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
10000:04:00.0 Non-Volatile memory controller: Intel Corporation Device 0a54
```
I've just connected NVMe devices to PCI switch under VMD.

> have you try this on different kernel versions?
We need to make sure everything is OK on centos7 rather than other upstream kernel.

> I see that in closed issue that you had reported some time ago - #1008 (comment) - you were able to detect NVMe drives under VMD - are you using same environment here?
Yes. The only difference is that I used P4510 NVMe devices in that case.

By the way, I found that nvme device will shutdown ubnormally when I run setup.sh. Is it normal?
```
[root@kvm_9_27_142_108 /home/ufo/spdk/spdk-master]# dmesg |grep shutdown
[ 6214.804155] nvme nvme3: Device shutdown costs 3636 milliseconds
[ 6219.069192] nvme nvme2: Device shutdown costs 3636 milliseconds
[ 6223.527573] nvme nvme1: Device shutdown costs 3838 milliseconds
[ 6228.035934] nvme nvme0: Device shutdown costs 3939 milliseconds
```

**Comment by wmalikow** [comment]
@ufo19890607 could you please check if this issue exist if you connect only one P4500 to PCI switch or if you connect it directly to CPU slot?

**Comment by wmalikow** [comment]
@ufo19890607 I've checked this issue on same kernel you are using: 3.10.0-693.el7.x86_64

In my environment I'm receiving  kernel panic during VMD unbinding from kernel:
 
```
#0 [ffff8824308b38f8] machine_kexec at ffffffff8105d77b
 #1 [ffff8824308b3958] __crash_kexec at ffffffff81108732
 #2 [ffff8824308b3a28] crash_kexec at ffffffff81108820
 #3 [ffff8824308b3a40] oops_end at ffffffff816b8778
 #4 [ffff8824308b3a68] no_context at ffffffff816a7c7a
 #5 [ffff8824308b3ab8] __bad_area_nosemaphore at ffffffff816a7d10
 #6 [ffff8824308b3b00] bad_area_nosemaphore at ffffffff816a7e7a
 #7 [ffff8824308b3b10] __do_page_fault at ffffffff816bb68e
 #8 [ffff8824308b3b70] do_page_fault at ffffffff816bb835
 #9 [ffff8824308b3ba0] page_fault at ffffffff816b7768
    [exception RIP: pcie_config_aspm_link+36]
    RIP: ffffffff8137ef74  RSP: ffff8824308b3c58  RFLAGS: 00010282
    RAX: 0000000000000000  RBX: 0000000000000000  RCX: 00000001002a0028
    RDX: ffffffff81abd340  RSI: 0000000000000000  RDI: ffff88161218fe00
    RBP: ffff8824308b3c90   R8: ffff88241abff380   R9: 00000001002a0028
    R10: 000000001abffb01  R11: ffffea00906aff80  R12: 0000000000000007
    R13: ffff88161218fe00  R14: ffff88161218fe00  R15: ffffffffffffffed
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
#10 [ffff8824308b3c98] pcie_config_aspm_path at ffffffff8137f091
#11 [ffff8824308b3cb8] pcie_aspm_exit_link_state at ffffffff8137ff56
#12 [ffff8824308b3ce0] pci_stop_bus_device at ffffffff8136a5db
#13 [ffff8824308b3d08] pci_stop_bus_device at ffffffff8136a5ab
#14 [ffff8824308b3d30] pci_stop_bus_device at ffffffff8136a5ab
#15 [ffff8824308b3d58] pci_stop_bus_device at ffffffff8136a5ab
#16 [ffff8824308b3d80] pci_stop_root_bus at ffffffff8136a793
#17 [ffff8824308b3da8] vmd_remove at ffffffff8156c696
#18 [ffff8824308b3dc8] pci_device_remove at ffffffff8137225e
#19 [ffff8824308b3df0] __device_release_driver at ffffffff814474a2
#20 [ffff8824308b3e10] device_release_driver at ffffffff81447533
#21 [ffff8824308b3e30] driver_unbind at ffffffff81445dcd
#22 [ffff8824308b3e70] drv_attr_store at ffffffff814452f7
#23 [ffff8824308b3e80] sysfs_write_file at ffffffff8128573b

```

I think that you could has also issue with kernel VMD driver unbind (you've noticed abnormal shutdown of nvme devices during setup.sh) and this could potential lead to that spdk driver is not able to enumerate those drives.

Potential workaround for this issue is blacklisting kernel VMD driver - I was able to detect both P4500 and P4100 with SDPK VMD driver when I done it. 
To blacklist builtin VMD driver you need to add "initcall_blacklist=vmd_drv_init" parameter to kernel cmdline.
