### ISSUE TITLE
nvmf tgt Coredump occured when runnning run_nvmf.py script

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#1156]
When checking the result of autotestspdk script , coredump occured and got the information of coredump.

## Expected Behavior
run successfully without coredump.

## Current Behavior
warning: the debug information found in "/usr/lib/debug/usr/lib64/libibverbs/libbnxt_re-rdmav22.so.debug" does not match "/usr/lib64/libibverbs/libbnxt_re-rdmav22.so" (CRC mismatch).

Missing separate debuginfo for /usr/lib64/libibverbs/libbnxt_re-rdmav22.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/56/feee1f0b43c4a2e3a55b4bd1e5e3de3474992b.debug
Core was generated by `/home/storage/autotestspdk/spdk/app/nvmf_tgt/nvmf_tgt -m 1'.
Program terminated with signal 6, Aborted.
#0  0x00007f1263885337 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
55        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0  0x00007f1263885337 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f1263886a28 in __GI_abort () at abort.c:90
#2  0x00007f12638c7e87 in __libc_message (do_abort=do_abort@entry=2,
    fmt=fmt@entry=0x7f12639da3b8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007f12638d0679 in malloc_printerr (ar_ptr=0x7f1263c16760 <main_arena>, ptr=<optimized out>,
    str=0x7f12639da4e0 "double free or corruption (!prev)", action=3) at malloc.c:4967
#4  _int_free (av=0x7f1263c16760 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3843
#5  0x0000000000452cdf in spdk_nvme_probe_poll_async (probe_ctx=0x31bf940) at nvme.c:1224
#6  0x000000000040e1fc in bdev_nvme_async_poll (arg=<optimized out>) at bdev_nvme.c:1526
#7  0x000000000049b1f9 in spdk_thread_poll (thread=0x2046740, max_msgs=max_msgs@entry=0, now=now@entry=10779614974370764)
    at thread.c:574
#8  0x0000000000496d08 in _spdk_reactor_run (arg=0x2046600) at reactor.c:337
#9  0x0000000000497539 in spdk_reactors_start () at reactor.c:426
#10 0x0000000000495cc3 in spdk_app_start (opts=opts@entry=0x7ffe9f2c5290, start_fn=start_fn@entry=0x40a9f0 <nvmf_tgt_started>,
    arg1=arg1@entry=0x0) at app.c:686
#11 0x00000000004081e7 in main (argc=3, argv=0x7ffe9f2c5438) at nvmf_main.c:75

## Steps to Reproduce
1. In target machine:
   cd /home/storage/autotestspdk 

2.using command:
   PYTHONPATH=$PYTOHNPATH:/home/storage/autotestspdk/spdk/scripts/ python3 scripts/perf/nvmf/run_nvmf.py /home/storage/autotestspdk/config.json
In the config.json file, three host machines are configured, and the fio config is as below:
  "fio": {
    "bs": ["4096"],
    "qd": [64],
    "rw": ["randrw"],
    "rwmixread": 50,
    "run_time": 7200,
    "ramp_time": 1,
    "run_num": 1,
    "num_jobs": 1
  }
 
## Context (Environment including OS version, SPDK version, etc.)
SPDK version : 5a04e473b22e6f6b65433d07c5a1668a0a404fa2
OS version : 5.4.8-1.el7.elrepo.x86_64

**Comment by changpe1** [comment]
It's should be a bug, I have a fix https://review.gerrithub.io/c/spdk/spdk/+/482215, can you help to verify it? Thanks.

**Comment by jimharris** [comment]
Marking as high priority bug.

But does this also indicate some kind of bug in the test script?  I'm trying to understand why we haven't seen this bug elsewhere.

**Comment by changpe1** [comment]
His environment has a bad drive, so it can trigger this bug, Liang already verified it with this patch, so we can close it now.
