### ISSUE TITLE
iscsi_tgt_bdev_io_wait failure

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1157]
Log: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/57360/archive/vpp_autotest/build.log

vpp.c: 396:session_disconnected_handler: *DEBUG*: Disconnect session 0xdff3d0 (1) handler
vpp.c: 873:spdk_vpp_sock_recv: *DEBUG*: Client 0xdff3d0(1) is disconnected.
vpp.c: 619:_spdk_vpp_session_disconnect: *DEBUG*: Session is already in disconnecting state 0xdff3d0 (1)
vpp.c: 226:_spdk_vpp_session_free: *DEBUG*: Free session 0xdff3d0 (1)
 17:50:48	# rm -f /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/test/iscsi_tgt/bdev_io_wait/bdev.conf
 17:50:48	# trap - SIGINT SIGTERM EXIT
 17:50:48	# killprocess 638812
 17:50:48	# '[' -z 638812 ']'
 17:50:48	# kill -0 638812
  17:50:48	# ps --no-headers -o comm= 638812
 17:50:48	# '[' reactor_1 = sudo ']'
 17:50:48	# echo 'killing process with pid 638812'
killing process with pid 638812
 17:50:48	# kill 638812
 17:50:48	# wait 638812
vpp.c: 651:_spdk_send_unbind_sock: *DEBUG*: Unbind session 0xdff2d0 (0) request
vpp.c: 477:session_unlisten_reply_handler: *DEBUG*: Unbind session 0xdff2d0 (0)
msg_handler_internal:432: no handler for msg id 579
vpp.c: 226:_spdk_vpp_session_free: *DEBUG*: Free session 0xdff2d0 (0)
vpp.c:1300:_spdk_vpp_application_detached: *NOTICE*: Application detached
/var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/test/common/autotest_common.sh: line 494: 638812 Segmentation fault      (core dumped) $ISCSI_APP -m 0x2 -p 1 -s 512 --wait-for-rpc
  17:50:58	# trap - ERR
  17:50:58	# print_backtrace
  17:50:58	# [[ ehxBE =~ e ]]
  17:50:58	# xtrace_disable
  17:50:58	# '[' no '!=' yes ']'
  17:50:58	# PREV_BASH_OPTS=ehxBE
  17:50:58	# [[ ehxBE == *\x* ]]
  17:50:58	# XTRACE_DISABLED=yes
  17:50:58	# set +x

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_57360.html

**Comment by optimistyzy** [comment]
Can we produce this issue, I see the latest error is 3 weeks ago?

**Comment by jimharris** [comment]
Closing this issue.  Was only seen with VPP, and not at all over the last 4 weeks.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_4292.html
