### ISSUE TITLE
[libvirt] Can't execute qemu instance with AppArmor around

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1158]
This is not really an issue with the actual SPDK framework, more with how its execution can be limited by some securityfss, like apparmor, hence the ticket to discuss if it's worth to do anything about it. :)

On systems which are managed by the AppArmor subsystem (e.g. Debian 10) the libvirtd daemon executes its libvirt-aa-helper to dynamically create an apparmor profile for each qemu instance. However, currently, the helper is not taking the <qemu:commandline> into the account and as a result the nvme disk image is not being included in the said profile - the emulator, when execed, fails with -EPERM while trying to access the image.

## Expected Behavior
QEMU emulator should be able to access nvme_disk.img without any issues to boot the vm.

## Current Behavior
QEMU emulator fails to boot the vm due to lack of permissions to access nvme_disk.img.

## Possible Solution
Skel of a potential mitigation: https://review.gerrithub.io/c/spdk/spdk/+/482088 - in short, it simply adds $nvme_disk path to main apparmor profile dedicated for libvirtd (`/etc/apparmor.d/abstractions/libvirt-qemu`). The easiest workaround would be to either disable apparmor entirely or the libvirtd's security driver.

## Steps to Reproduce
Just try to create a vm on a system confined by AppArmor (like Debian 10):

`./scripts/vagrant/create_vbox.sh -c -b /var/lib/libvirt/images/nvme.img -p libvirt -d fedora31`

It will fail right after libvirtd attempts to execute QEMU to bring the vm up since `/var/lib/libvirt/images/nvme.img` won't end up in the dynamically created `/etc/apparmor.d/libvirt/libvirt-uuid.files` for given vm (just note that the libvirt's aa helper will always (annoyingly)unlink the profile upon the failure).

## Context (Environment including OS version, SPDK version, etc.)
OS: Debian 10 (buster), 4.19.0-6-amd64
SPDK: v19.10-rc1 (9857ff60)

**Comment by peluse** [comment]
bug scrub: will review patch and decide based on its merits

**Comment by darsto** [comment]
I'm not sure what was the final verdict here. I'll just share my view.

I don't think we need to be apparmor-aware in this case. The easiest solution here is just `# apt purge apparmor`. If someone wants to use apparmor - let him go for it, but we dont have to.

**Comment by jimharris** [comment]
> I'm not sure what was the final verdict here. I'll just share my view.
> 
> I don't think we need to be apparmor-aware in this case. The easiest solution here is just `# apt purge apparmor`. If someone wants to use apparmor - let him go for it, but we dont have to.

+1
