### ISSUE TITLE
Docs slighty off for spdk_nvme_ctrlr_alloc_io_qpair

### ISSUE THREAD

**Issue by csm10495** [spdk/spdk#1160]
Docs for include/spdk/nvme.h are slightly off for spdk_nvme_ctrlr_alloc_io_qpair()

for the opts param it says returned by spdk_nvme_ctrlr_alloc_io_qpair(). I think it should be spdk_nvme_ctrlr_get_default_io_qpair_opts()

## Expected Behavior
Docstring fixed?

## Current Behavior
NA

## Possible Solution
NA

## Steps to Reproduce
NA

## Context (Environment including OS version, SPDK version, etc.)
Latest tip.

**Comment by peluse** [comment]
Hi Charlie! Would you be willing to submit a patch?

**Comment by csm10495** [comment]
Sure. Point me to a wiki :)

- Charlie Scott Machalow

**Comment by jimharris** [comment]
SPDK only accepts patches through GerritHub.

Let us know if you have any questions.  Or if you're not able to get GerritHub set up now, post something here and someone else can pick up the doc fix.

Thanks!

**Comment by peluse** [comment]
bug scrub: need some help? @csm10495

**Comment by csm10495** [comment]
I'm hoping to get to it soon, just haven't gotten around to it.

- Charlie Scott Machalow

**Comment by csm10495** [comment]
Alrighty. Opened https://review.gerrithub.io/c/spdk/spdk/+/483306. Hopefully I did it ok.

**Comment by peluse** [comment]
Looks good!
