### ISSUE TITLE
nvmf/tcp initiator: Assert sock->cb_cnt goes negative in spdk_sock_abort_requests()

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1164]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Test pool hit the assert in spdk_sock_abort_requests().
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58208/archive/nvmf_tcp_autotest/build.log

## Expected Behavior
No assert.

## Current Behavior
The above

## Possible Solution
None yet.

## Steps to Reproduce
NVMe-TCP autotest.

## Context (Environment including OS version, SPDK version, etc.)
Latest SPDK master.

**Comment by shuhei-matsumoto** [comment]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58078/archive/nvmf_tcp_autotest/build.log

Another case

**Comment by shuhei-matsumoto** [comment]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58114.html

Another case.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58313.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58358.html

**Comment by benlwalker** [comment]
Classifying these:

1. https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58208/archive/nvmf_tcp_autotest/build.log is an initiator assert.
2. https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58078/archive/nvmf_tcp_autotest/build.log is an initiator assert.
3. https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58114.html is an initiator assert.
4. https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58313.html is an iSCSI failure. Should have been issue #1169.
5. https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58358.html has three different failures. The iSCSI tests failed with issue #1169. One of the nvmf tests failed with issue #1165. And one failed with issue #1166.

Based on this, I'm going to drop the logs for 4 and 5 (different issues) and then rename this issue to describe the initiator-side assert. I suspect this is the bug fix, but it's going to take a lot of test runs to be confident in that: https://review.gerrithub.io/c/spdk/spdk/+/483148

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58666.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58842.html

**Comment by benlwalker** [comment]
This issue has not occured on any patches rebased on top of d0f4a51fd, so the fix must have worked. Closing this issue. If anyone sees it happen again on a patch that includes that fix, we'll re-open.
