### ISSUE TITLE
nvmf_bdevperf: bdevperf fails to reconnect (nvmf/rdma) after target killed and restarted

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#1165]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58310/archive/nvmf_autotest/build.log

Probably something with the async writev introduced to the nvmf initiator just recently.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58310.html

**Comment by AlekseyMarchuk** [comment]
I've met similar error https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58221.html so probably this is a common error

**Comment by peluse** [comment]
See Aleksey's link

**Comment by benlwalker** [comment]
The writev's failing aren't a problem. The real issue is that bdevperf fails to reconnect after the target is brought back up and bdevperf never exits.

**Comment by benlwalker** [comment]
Seth observed that this is only failing on softroce. We already skip other disconnect tests on softroce because it's known to be buggy. That's probably the solution here too.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58635.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58658.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58639.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58637.html
--

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58636.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58652.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58656.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58660.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58672.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58675.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58670.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58569.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58716.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @darsto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58732.html

**Comment by Seth5141** [comment]
Patch here: https://review.gerrithub.io/c/spdk/spdk/+/483300

**Comment by darsto** [comment]
This github issue is specific to an intermittent failure on CI and the workaround from Seth was merged, so I'm going to close this.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58970.html
