### ISSUE TITLE
blobstore.c _spdk_bs_allocate_cluster: ‘extent_page’ may be used uninitialized

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1167]
## Current Behavior
Error in blobstore.c
```
blobstore.c: In function ‘_spdk_bs_allocate_cluster’:
blobstore.c:173:33: error: ‘extent_page’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if (blob->use_extent_table && *extent_page == 0) {
                                 ^~~~~~~~~~~~
```

## Steps to Reproduce
1.  Only reproduces without --enable-debug and with --enable-werror
```
./configure --enable-werror 
```
2. make -j100

## Context (Environment including OS version, SPDK version, etc.)
SPDK 8818ace2f4d28ba1904a0903311e2f7df6542224
gcc version 8.3.1 20190223 (Red Hat 8.3.1-2) (GCC)

**Comment by tomzawadzki** [comment]
Sorry for that @karlatec.
This was fixed later in the series https://review.gerrithub.io/c/spdk/spdk/+/482893
Due to merging series in two parts, there was brief period where this failure occurred.

It should be fixed on master now.

**Comment by karlatec** [comment]
Ok will check it later

**Comment by karlatec** [comment]
Build again with ./configure --enable-werror using SPDK origin/master bba0f040cf421ef75c840f64d0eab55e39bc0081

No issue this time. Closing.
