### ISSUE TITLE
Review how (some) tests utilize tmp storage

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1168]
Some tests (e.g. in `./test/blobfs/blobfs.sh`) depend on data to be written out into a tmp storage prior their execution. In most cases this should be fine, however, in case a target path is located under a tmpfs|ramfs mount the actual size of said data may cause a high mem pressure (especially with some particular mount opts in use) on the host system (as in the mentioned example, `blobfs.sh` can put ~4GB into a pcache if tmpfs is used under `/tmp`). In the worst case scenario, this may force kernel into calling its oom killer causing a little bit of havoc around - imagine a scenario where `*.sh` is actually hit with SIGKILL by said killer and data is not cleared out at all (in case of tmpfs this may be fine if a big enough swap area is available but in case of ramfs, and really unfortunate circumstances, this may just kill the entire system).

Regardless of how unlikely the above scenarios can be, I think it would be nice to at least consider having some handlers in place for checking the availability of tmp storage before performing some extensive writes before the actual tests are run.

**Comment by jimharris** [comment]
Removing the bug label here.  Typically issues are either a bug or an enhancement, not both.

**Comment by mikeBashStuff** [comment]
Rough RFC with basic idea. Going to test it out this week to see if it's worth it - https://review.spdk.io/gerrit/c/spdk/spdk/+/1868

**Comment by darsto** [comment]
I agree putting 4GB into tmpfs doesn't sound right, but I don't think the above RFC is the right direction either - see comments inside. In various tests we use $testdir for temporary files. E.g. lvol tests put AIO backing files there. Could we use $testdir in blobfs tests as well?

**Comment by mikeBashStuff** [comment]
@darsto I guess that's one way to do it. On one hand, this sounds better as we keep files we create under our repo, but on the other, this can be a bit messy since not all the tests cleanup their stuff (or they fail to do so in case of a sudden crash or other bad weather) so if someone does something like `git add .; git commit --amend --no-edit` after running some tests, the actual contents of the commit may be a bit surprising. :D And if repo was cloned onto some limited storage then `$testdir` also won't work in this case very well.

That said, maybe utilizing `$testdir` as you mentioned (and single, defined tmpfs mount, if ever needed to shmem stuff) across all the tests we have + putting some info into README explaining that you need at least that big of a storage to run tests locally would be enough.

Would you like me to open a trello for that and close this issue? :)

**Comment by darsto** [comment]
This sounds promising. Sure, please open a trello.

**Comment by darsto** [comment]
Oh, I actually misread your comment and thought you're suggesting to add a single path outside of spdk directory for all tmp files. $testdir is fine too, but it does have those drawbacks you mentioned.

**Comment by mikeBashStuff** [comment]
@darsto It can serve as a fallback if needed. Will move it to trello, we can then discuss all the details there. :)

**Comment by mikeBashStuff** [comment]
https://trello.com/c/d84HgIRE/68-improve-how-the-tmp-storage-is-utilized-across-all-the-tests-ie-make-it-consistent

Closing this issue.
