### ISSUE TITLE
iSCSI target: sock->cb_fn is NULL at spdk_sock_group_impl_poll_count

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1169]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58467/archive/iscsi_autotest/build.log

During calsoft test suite, Error log is correct.

```
 03:02:52	# sleep 1
 03:02:53	# '[' '' ']'
 03:02:53	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/test/iscsi_tgt/calsoft/calsoft.py /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/../output
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=4
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=66)
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=66)
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(2) ignore (ExpCmdSN=3, MaxCmdSN=66)
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(3) ignore (ExpCmdSN=4, MaxCmdSN=66)
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=66)
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(3) ignore (ExpCmdSN=4, MaxCmdSN=67)
iscsi.c:4448:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
iscsi_tgt: sock.c:529: spdk_sock_group_impl_poll_count: Assertion `sock->cb_fn != NULL' failed.
```
## Expected Behavior
No error

## Current Behavior
Above

## Possible Solution
None

## Steps to Reproduce
CI iSCSI test pool

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58474.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58500.html

**Comment by shuhei-matsumoto** [comment]
This issue looks caused by conflict between asynchronous completion by sock layer and connection exit by iSCSI connection layer. I'm investigating the fix.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58508.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58512.html

**Comment by shuhei-matsumoto** [comment]
Hi @benlwalker 

The log says spdk_sock_group_impl_poll_count() gets input from closed socket because spdk_sock_group_remove_sock() removes socket from posix layer and clears it.

And I don't find anything in my patch series to update sock layer.

Is it likely that the recent improvement changed the behavior.

Thanks,
Shuhei

**Comment by shuhei-matsumoto** [comment]
The  patch https://github.com/spdk/spdk/commit/7ef33c86b824b912d8d487a86fccff31d76d93aa#diff-42a38a9dd6ad2de85bf35e2faf135182 changed the behavior of spdk_posix_sock_group_impl_poll() slightly. We conditionally copy the value to sock now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58634.html

**Comment by optimistyzy** [comment]
@shuhei-matsumoto  I think that you are right, it was related with zero copy patch (I just dropped the same info to you in slack). Due to Coronavirus, we will be back to office on Feb 10.

**Comment by optimistyzy** [comment]
May be related with spdk_posix_sock_group_impl_poll function -> _sock_check_zcopy, then this function call "spdk_sock_request_put", it will call user call back, then it may do some operations to close socket.

Then this statement  in spdk_posix_sock_group_impl_poll tries to put the event again, but the socket may be already handled.
		if (events[i].events & EPOLLIN) {
			socks[j++] = events[i].data.ptr;
		}

**Comment by optimistyzy** [comment]
@shuhei-matsumoto @benlwalker  https://review.gerrithub.io/c/spdk/spdk/+/483311  Not sure this patch can solve this issue since currently I did not have a test platform. By the way, Do we mujst 
 call "spdk_sock_close" in spdk_sock_request_put? Though some flags are used to check. Actually my question is that: If "spdk_sock_close" is called in "spdk_sock_request_put", can we make sure that this sock is removed from the corresponding sock group?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58588.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58628.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58633.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58638.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58646.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58647.html

**Comment by shuhei-matsumoto** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58673.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58679.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58678.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58688.html

**Comment by tomzawadzki** [comment]
@optimistyzy @shuhei-matsumoto 
Unfortunately the patch https://review.gerrithub.io/c/spdk/spdk/+/483311, still triggers the Calsoft failure. Please see attached log [build.log.txt](https://github.com/spdk/spdk/files/4133923/build.log.txt).

**Comment by shuhei-matsumoto** [comment]
Thank you so much Tomek. I saw the log and found the issue was not fixed

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58705.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58723.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58727.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58731.html

**Comment by optimistyzy** [comment]
> Thank you so much Tomek. I saw the log and found the issue was not fixed

@shuhei-matsumoto  I think that our direction is still a correct way, we may miss one part, that the upper layer actively remove the sock from the group, so we may also need this patch.

 https://review.gerrithub.io/c/spdk/spdk/+/483401

I may need refine this tomorrow.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58738.html

**Comment by tomzawadzki** [comment]
@optimistyzy Thank you for tackling the issue at such time !
After running patch https://review.gerrithub.io/c/spdk/spdk/+/483401 15 times over iscsi job - got hit by couple other failures but not once by Calsoft one. Looking good !

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58816.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58829.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58838.html
