### ISSUE TITLE
Blobstore: blob-state is not dirty at _spdk_blob_serialize

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1170]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58470/archive/nvmf_tcp_autotest/build.log

```
Starting SPDK v20.01-pre git sha1 e7a5bb85b0 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x18 -m 512 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid49051 ]
EAL: No available hugepages reported in hugepages-1048576kB
  03:31:59	# /var/jenkins/workspace/NVMeOF_tests/nvmf_tcp_autotest/spdk/scripts/rpc.py bdev_lvol_snapshot 8de264c8-6988-4f0a-8a45-82bc01e82189 MY_SNAPSHOT
nvmf_tgt: blobstore.c:1170: _spdk_blob_serialize: Assertion `blob->state == SPDK_BLOB_STATE_DIRTY' failed.
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
NVMe io qpair process completion error
NVMe io qpair process completion error
Initializing NVMe Controllers

```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58511.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58547.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58704.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58753.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58761.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58759.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58813.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58821.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58822.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58962.html

**Comment by shuhei-matsumoto** [comment]
https://d3uor3w1civ2bt.cloudfront.net/results/autotest-per-patch/builds/2924/archive/nvmf-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59000.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58990.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59065.html

**Comment by jimharris** [comment]
(Moved from #1181)
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59139.html

**Comment by jimharris** [comment]
(Moved from #1181)
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59151.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59888.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59835.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60164.html

**Comment by tomzawadzki** [comment]
The issue is related to multiple md syncs going on at the same time. As such it is related to #906.
Recent addition of Extent Table writing before serializing rest of metadata, exacerbates the issue.

Please see UT that reproduces this assert in simplest way: https://review.spdk.io/gerrit/c/spdk/spdk/+/775/
First jab at fixing it can be seen here: https://review.spdk.io/gerrit/c/spdk/spdk/+/776/

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60412.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60464.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60463.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3185.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3302.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3492.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3504.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3512.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3857.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://ci.spdk.io/public_build/autotest-per-patch_4012.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_4102.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4368.html
