### ISSUE TITLE
FTL: band->high_prio is zero in ftl_band_free_lba_map

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1171]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

The following assert was collected.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58485/archive/nvme_autotest/build.log

```
 05:43:10	# /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/scripts/rpc.py bdev_ocssd_create -c nvme0 -b nvme0n1
nvme0n1
 05:43:10	# /var/jenkins/workspace/NVMe_tests/nvme_autotest/spdk/scripts/rpc.py bdev_ftl_create -b ftl0 -d nvme0n1
ftl_core.c: 236:ftl_md_write_fail: *ERROR*: Metadata write failed @addr: (6144), status: -5
bdevperf: ftl_band.c:156: ftl_band_free_lba_map: Assertion `!band->high_prio' failed.
{

```

**Comment by wmalikow** [comment]
I have prepared fix proposal: https://review.gerrithub.io/c/spdk/spdk/+/483264

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58987.html
