### ISSUE TITLE
 NVMf autotest timeout 

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1172]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

15 minutes timeout for NVMf autotest was observed 6 times in a patch series.
The patch series is for thread library and I haven't find any relationship with this timeout yet.

Common signature is the timeout was observed in autotest;nvmf_rdma;host;nvmf_bdevperf;start_nvmf_tgt
One case was the second run of the test case.

Logs are
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58468.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58494/archive/nvmf_autotest/index.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58496/archive/nvmf_autotest/index.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58502/archive/nvmf_autotest/index.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58505/archive/nvmf_autotest/index.html
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58499/archive/nvmf_autotest/index.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58458.html

**Comment by benlwalker** [comment]
This is issue #1165. Closing this one and we'll report there.
