### ISSUE TITLE
Cannot start hello_bdev with json config

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1173]
1. Generate sample spdk json config. Save it to bdev.json.
2. Run ./examples/bdev/hello_world/hello_bdev --json bdev.json
3. Got output:
   hello_bdev.c: 278:main: *ERROR*: configfile must be specified using -c <conffile> e.g. -c bdev.conf

**Comment by darsto** [comment]
There's one condition in code that we can easily remove and this issue will be fixed.

But we should also update comments in hello_bdev.c. Considering this is a most basic SPDK test app, the comments should be very descriptive.

**Comment by darsto** [comment]
Fix: https://review.gerrithub.io/c/spdk/spdk/+/483386
