### ISSUE TITLE
SPDK should exit on RPC init failure

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1174]
To reproduce try to run:
  ./app/vhost/vhost -r ./app/vhost

Application should exit.

**Comment by pawelkax** [comment]
I would also like to report similar bug.
Application should exit when trying to start it with socket that is already in use.
To reproduce it:
1. ./app/vhost/vhost -r ./var/tmp/vhost_app.sock &
2. ./app/vhost/vhost -r ./var/tmp/vhost_app.sock

In point 2 application should exit.

**Comment by darsto** [comment]
SPDK is unable to start the RPC server, but in both cases it prints a nice and clear error message. [1]
Exiting on RPC failure could cause some problems now - even in our tests we may already depend on having e.g. multiple bdevperf instances started and not caring about RPC.

[1]
```
rpc.c: 181:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /tmp/spdk.sock in use. Specify another
rpc.c:  72:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at [...]
```

**Comment by pawelkax** [comment]
@darsto 
Shouldn't this two cases be handled in file lib/vhost/rte_vhost_compat.c?
Code I see starts with:
`if (stat(path, &file_stat) != -1) {`
I don't see these two vhost logs.

**Comment by darsto** [comment]
That code applies to vhost sockets -> the ones named after a vhost controller

-r command line parameter defines an RPC socket and is not related to vhost

**Comment by jimharris** [comment]
I agree with Darek that we probably shouldn't fail the application if we can't start RPC because there's already a different application listening for RPC on the same path.

But we could add a check whether that path even references a socket (i.e. using stat() and checking for S_IFSOCK).  In that case I think it would be appropriate to fail immediately.

Who wants to pick this one up?

**Comment by darsto** [comment]
I thought we already have that check. Maybe the error message could be made more clear.

Assigned myself.

**Comment by darsto** [comment]
I posted a log with this message in my first comment `rpc.c: 181:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /tmp/spdk.sock in use. Specify another` - it's already there. Looks like there's nothing else to be done.

```
$ ./app/spdk_tgt/spdk_tgt &
$ ./app/spdk_tgt/spdk_tgt
[2020-05-12 14:30:51.594801] rpc.c: 181:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.
[2020-05-12 14:30:51.594874] rpc.c:  72:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at /var/tmp/spdk.sock
