### ISSUE TITLE
apply_firmware RPC prevents closing bdev nvme library

### ISSUE THREAD

**Issue by tkulasek** [spdk/spdk#1176]
apply_firmware RPC call before bdev_nvme_detach_controller prevents clean closing of spdk_tgt with error "bdev_nvme.c:1881:bdev_nvme_library_fini: *ERROR*: Controller Nvme0 is still referenced, can't destroy it"

## Expected Behavior

1. All references to NVMe controller should be closed/removed.
2. spdk_tgt should cleanly exit receiving SIGTERM.

## Current Behavior

"rpc.py bdev_nvme_detach_controller Nvme0" success, but SIGTERM doesn't close spdk_tgt and hungs with error:
"bdev_nvme.c:1881:bdev_nvme_library_fini: *ERROR*: Controller Nvme0 is still referenced, can't destroy it"

## Steps to Reproduce

1. ./app/spdk_tgt/spdk_tgt -m 0x3 &
2. ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:00:09.0
3. ./scripts/rpc.py apply_firmware non_existing_file Nvme0n1
4. ./scripts/rpc.py bdev_nvme_detach_controller Nvme0
5. send SIGTERM to the spdk_tgt process

test triggering this issue: https://review.gerrithub.io/c/spdk/spdk/+/483216
log from CI: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58521.html

**Comment by tkulasek** [comment]
Reference to the io channel wasn't released in apply_firmware RPC: https://review.gerrithub.io/c/spdk/spdk/+/483704

**Comment by ufo19890607** [comment]
@tkulasek 
Hi tkulasek. I've add your fix patch(483107: bdev/nvme: fix crash when invoking apply_firmware RPC), and found that spdk_json_decode_string will still free a NULL pointer. I still think we should free a certain pointer outside this function, which is more easier to understand. 

At least, we can add a if statement.
```
int
spdk_json_decode_string(const struct spdk_json_val *val)
{
	char **s;
	
        if (*s)
             free(*s); 

	*s = spdk_json_strdup(val);
...
```
