### ISSUE TITLE
Build marked as failed with no errors in the log

### ISSUE THREAD

**Issue by Donaim** [spdk/spdk#1177]
Build # 981 failed unexpectedly with no errors in the logs on `spdk-master-vs-dpdk-19.11` job.
End of the log:
```
20:05:41  14:40:36	# xtrace_disable
20:05:41  14:40:36	# '[' no '!=' yes ']'
20:05:41  14:40:36	# PREV_BASH_OPTS=ehxBE
20:05:41  14:40:36	# [[ ehxBE == *\x* ]]
20:05:41  14:40:36	# XTRACE_DISABLED=yes
20:05:41  14:40:36	# set +x
20:05:41  14:40:36	# xtrace_enable
20:05:41  14:40:36	# timing_exit autotest
20:05:41  14:40:36	# xtrace_disable
20:05:41  14:40:36	# '[' no '!=' yes ']'
20:05:41  14:40:36	# PREV_BASH_OPTS=ehxBE
20:05:41  14:40:36	# [[ ehxBE == *\x* ]]
20:05:41  14:40:36	# XTRACE_DISABLED=yes
20:05:41  14:40:36	# set +x
20:05:41  14:40:36	# xtrace_enable
20:05:41  14:40:36	# chmod a+r /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest_nightly/spdk/../output/timing.txt
20:05:41  14:40:36	# trap - SIGINT SIGTERM EXIT
20:05:41  14:40:36	# process_core
20:05:41  14:40:36	# ret=0
20:05:41  14:40:36	# IFS=
20:05:41  14:40:36	# read -r -d '' core
20:05:41   14:40:36	# find . -type f '(' -name 'core\.?[0-9]*' -o -name '*.core' ')' -print0
20:05:41  14:40:36	# return 0
20:05:41  14:40:36	# hash lcov
20:05:41   14:40:36	# hostname
20:05:41  14:40:36	# lcov --rc lcov_branch_coverage=1 --rc lcov_function_coverage=1 --rc genhtml_branch_coverage=1 --rc genhtml_function_coverage=1 --rc genhtml_legend=1 --rc geninfo_all_blocks=1 --no-external -q -c -d /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest_nightly/spdk -t spdk-fedora-03 -o cov_test.info
20:05:41 geninfo: WARNING: invalid characters removed from testname!
20:05:50 geninfo: WARNING: gcov did not create any files for /var/jenkins/workspace/NVMe_tests/nvme_phy_autotest_nightly/spdk/lib/util/math.gcda!
20:05:50 Tests finished with errors. Please check the logs for more info.
20:05:50 Execution node will be rebooted.
20:05:51 Triggering a new build of reset-job-nightly
20:05:51 Finished: FAILURE
```

## Expected Behavior

Build with no errors succeedes

## Steps to Reproduce

Reproduced once on CI

## Context (Environment including OS version, SPDK version, etc.)
SPDK 967fa2d707
DPDK 19.11

**Comment by jimharris** [comment]
Bug scrub: @karlatec is doing some scrubbing in some of the nightly Jenkins jobs - assigning to him for now.  @karlatec - feel free to reassign if needed.  :-)

**Comment by karlatec** [comment]
We should probably keep this open and let Vitaliy re-evaluate the issue once he's back in the office.
This was reported before we switched CI to the new setup, so it might not be valid anymore.

**Comment by jimharris** [comment]
Assigning to @Donaim to reevaluate.

**Comment by Donaim** [comment]
I don't see replications on the new CI, but I also have not seen them when I originally submitted this issue (only a sigle case). So cannot tell whether it is invalid or just rare.

**Comment by jimharris** [comment]
Thanks @Donaim.

I'm going to close this issue.  I'm wondering if this was related to the post-processing detecting that some tests didn't get run - that doesn't show up clearly in the logs.  The failing case happened 4 weeks ago though so we can't go back and check it.
