### ISSUE TITLE
START TEST bdev_verify data miscompare w/Jenkins Community CI Label 

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1179]
Not sure what to make of this.  The patch itself is just some comment changes and the "regular" Jenkins passed fine but the Community Jenkins hit what looks like a real data miscompare using bdevperf. 

Patch: https://review.gerrithub.io/c/spdk/spdk/+/483528 

Fail Logs: https://d3uor3w1civ2bt.cloudfront.net/results/autotest-per-patch/builds/2848/archive/nvme-autotest/build.log

**Comment by tomzawadzki** [comment]
[Bug scrub] The Community Jenkins CI is an instance that we will be switching to soon. VM was temporarily run on system with spinning drive that was causing the issue. @karlatec Says the issue no longer shows up, so I'll be closing this issue.
