### ISSUE TITLE
When does lun->ref have more than 1?

### ISSUE THREAD

**Issue by uchida2016** [spdk/spdk#118]
I think spdk_scsi_lun_delete() should call spdk_scsi_lun_free_io_channel(). spdk_scsi_lun_free_io_channel() need to be called lun->ref times to free the io_channel. But I don't find the case where lun->ref becomes 2 or bigger.

**Comment by optimistyzy** [comment]
we found such issue reported by user，see issue#92

**Comment by uchida2016** [comment]
I see. The ref member is for the case that multiple connections access the same LUN.
