### ISSUE TITLE
test/nvmf/target/nvme_cli.sh: line 58: ./nvme: No such file or directory

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1180]
Hit this twice in CI today. 

Log: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/58943/archive/nvmf_phy_autotest/build.log

Patch (unrelated): https://review.gerrithub.io/c/spdk/spdk/+/483537

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58943.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58950.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58956.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58959.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58969.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58972.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58982.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58977.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://d3uor3w1civ2bt.cloudfront.net/public_build/autotest-per-patch_2924.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58967.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58980.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58974.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58989.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_58961.html

**Comment by tomzawadzki** [comment]
This looks like the GP1 (maybe more) is missing the nvme cli tool. @karlatec Can you please take a look ?

**Comment by karlatec** [comment]
@tomzawadzki nvme-cli is in place in the right directory. Problem is that it's not built! There's no ./nvme binary file to execute.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60441.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60445.html

**Comment by shuhei-matsumoto** [comment]
Slightly different signature but still related with nvme-cli.

EAL:   using IOMMU type 1 (Type 1)
 01:15:46	# '[' -e /var/run/spdk_stub0 ']'
 01:15:46	# [[ -e /proc/632920 ]]
 01:15:46	# sleep 1s
 01:15:47	# '[' -e /var/run/spdk_stub0 ']'
 01:15:47	# [[ -e /proc/632920 ]]
 01:15:47	# sleep 1s
 01:15:48	# '[' -e /var/run/spdk_stub0 ']'
 01:15:48	# [[ -e /proc/632920 ]]
 01:15:48	# sleep 1s
 01:15:49	# '[' -e /var/run/spdk_stub0 ']'
 01:15:49	# [[ -e /proc/632920 ]]
 01:15:49	# sleep 1s
 01:15:50	# '[' -e /var/run/spdk_stub0 ']'
 01:15:50	# [[ -e /proc/632920 ]]
 01:15:50	# sleep 1s
 01:15:51	# '[' -e /var/run/spdk_stub0 ']'
 01:15:51	# echo done.
done.
 01:15:51	# rm -f /home/sys_sgsw/nvme-cli/spdk
rm: cannot remove '/home/sys_sgsw/nvme-cli/spdk': Is a directory
  01:15:51	# trap - ERR
  01:15:51	# print_backtrace
  01:15:51	# [[ ehxBET =~ e ]]
  01:15:51	# args=("${BASH_ARGV[@]}")
  01:15:51	# local args
  01:15:51	# xtrace_disable
  01:15:51	# '[' '' '!=' yes ']'
  01:15:51	# PREV_BASH_OPTS=ehxBET
  01:15:51	# [[ ehxBET == *\x* ]]
  01:15:51	# XTRACE_DISABLED=yes
  01:15:51	# set +x
========== Backtrace start: ==========

in test/nvme/spdk_nvme_cli.sh:26 -> main([])

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/60462/archive/nvme_phy_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60504.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3636.html

**Comment by jimharris** [comment]
These last three failures are the same as issue #1213.  Closing this issue since the original problem has been fixed.
