### ISSUE TITLE
nvmf_lvol failure - assert error

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1181]
Occasionally, on TP when running nvmf_lvol test following error is displayed:
  17:20:42	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/rpc.py bdev_lvol_snapshot 3010c18d-d7d1-4611-8fec-7d56d54d880b MY_SNAPSHOT
nvmf_tgt: blobstore.c:1170: _spdk_blob_serialize: Assertion `blob->state == SPDK_BLOB_STATE_DIRTY' failed.

Sample log: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/59150/archive/nvmf_tcp_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59151.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59139.html

**Comment by jimharris** [comment]
This is a duplicate of #1170 

I'll move these failures instances to that issue.
