### ISSUE TITLE
20.01: spdk_nvmf_subsystem_destroy no longer removes all listeners

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1182]
This is a new issue with 20.01. I'm using the public API spdk_nvmf_subsystem_destroy to destroy a subsystem with all its listeners (e.g. TCP). The listeners are no longer removed. 

Looking at the RPC code for deleting a subsystem, it seems that `spdk_nvmf_subsystem_remove_all_listeners` is needed prior to calling the destroy function. However, `spdk_nvmf_subsystem_remove_all_listeners` is a private API.
```
static void
spdk_rpc_nvmf_subsystem_stopped(struct spdk_nvmf_subsystem *subsystem,
				void *cb_arg, int status)
{
	struct spdk_jsonrpc_request *request = cb_arg;
	struct spdk_json_write_ctx *w;

	spdk_nvmf_subsystem_remove_all_listeners(subsystem, true);
	spdk_nvmf_subsystem_destroy(subsystem);

	w = spdk_jsonrpc_begin_result(request);
	spdk_json_write_bool(w, true);
	spdk_jsonrpc_end_result(request, w);
}
```
Without removing all the listeners, I get the following failures when I re-create the same subsystem with the same listener again:
```
posix.c: 328:spdk_posix_sock_create: *ERROR*: bind() failed at port 4420, errno = 98
tcp.c: 647:spdk_nvmf_tcp_listen: *ERROR*: spdk_sock_listen(127.0.0.1, 4420) failed: Address already in use (98)
nvmf.c: 569:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address '127.0.0.1'
```

## Expected Behavior
The `spdk_nvmf_subsystem_destroy` should remove all items related to the subsystem including listeners. When I re-create the same subsystem/listener configuration it should succeed.

## Current Behavior
I can't re-create the same subsystem a second time after removing the first one with `spdk_nvmf_subsystem_destroy`.

## Possible Solution
Calling the private API `spdk_nvmf_subsystem_remove_all_listeners` prior does fix the issue. I haven't tried removing all listeners with the public API before the destroy ... maybe that would work too but is more hassle.

## Steps to Reproduce
Only reproducible when using spdk_nvmf_susbsytem API directly and not going through the RPC interface.

## Context (Environment including OS version, SPDK version, etc.)
Centos8, SPDK 20.01

**Comment by benlwalker** [comment]
This was intentional. See commit 2167c68d1. The listeners exist independently of the subsystems now.

Do you really need to remove the listeners in your use case? If you do, you can call spdk_nvmf_tgt_stop_listen() to destroy them. You are allowed to destroy/re-create subsystems without ever destroying the listener though.

**Comment by mhae** [comment]
So the proper approach now is to use spdk_nvmf_tgt_listen() to set up the listeners and then do the add_listener call on the subsystem to make the association? I can give that a try.

**Comment by benlwalker** [comment]
Yep - adding the listener to the subsystem is basically an access control operation now. They were unnecessarily coupled before.
