### ISSUE TITLE
modprobe -r uio_pci_generic failed because uio_pci_generic is in use.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1186]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/59946/archive/unittest_autotests/build.log

```
***********************************
END TEST unittest
************************************
 10:00:35	# xtrace_enable
 10:00:35	# '[' 0 -eq 1 ']'
 10:00:35	# timing_enter cleanup
 10:00:35	# xtrace_disable
 10:00:35	# '[' no '!=' yes ']'
 10:00:35	# PREV_BASH_OPTS=ehxBET
 10:00:35	# [[ ehxBET == *\x* ]]
 10:00:35	# XTRACE_DISABLED=yes
 10:00:35	# set +x
 10:00:35	# xtrace_enable
 10:00:35	# autotest_cleanup
 10:00:35	# /var/jenkins/workspace/Other/unittest_autotests/spdk/scripts/setup.sh reset
0000:00:09.0 (8086 5845): uio_pci_generic -> nvme
 10:00:35	# /var/jenkins/workspace/Other/unittest_autotests/spdk/scripts/setup.sh cleanup
ls: cannot access '/dev/shm/*': No such file or directory
Clean
  10:00:35	# uname -s
 10:00:35	# '[' Linux = Linux ']'
 10:00:35	# grep -q '#define SPDK_CONFIG_IGB_UIO_DRIVER 1' /var/jenkins/workspace/Other/unittest_autotests/spdk/include/spdk/config.h
 10:00:35	# modprobe -r uio_pci_generic
modprobe: FATAL: Module uio_pci_generic is in use.
  10:00:35	# trap - ERR
  10:00:35	# print_backtrace
  10:00:35	# [[ ehxBET =~ e ]]
  10:00:35	# args=("${BASH_ARGV[@]}")
  10:00:35	# local args
  10:00:35	# xtrace_disable
  10:00:35	# '[' no '!=' yes ']'
  10:00:35	# PREV_BASH_OPTS=ehxBET
  10:00:35	# [[ ehxBET == *\x* ]]
  10:00:35	# XTRACE_DISABLED=yes
  10:00:35	# set +x
========== Backtrace start: ==========


```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59951.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59949.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59948.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59980.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @darsto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59984.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59987.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59990.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59967.html

**Comment by jimharris** [comment]
All of these failures are on fedora_1G_vm_1.  Has that system been updated at all?  Or recently activated?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59999.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60008.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60003.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60001.html

**Comment by jimharris** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59996.html

(Posted this manually since this patch was updated with a new version after this failure)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_59993.html

**Comment by karlatec** [comment]
Please observe if this happens again today. If not then we can probably close the issue.

These fails happened at the same time when server hosting the VMs lost its DHCP IP address. With no IP address it was not possible to reboot the VMs after failed tests so there must have been some leftover process keeping uio_pci_generic busy and causing the problem reported here.

Last 12h logs for fedora_1G_vm_1 show only 3 failed tests and these are all legit unittest fails.

**Comment by jimharris** [comment]
Closing.  Based on explanation from @karlatec, I'm confident this was due to the VM losing it's DHCP IP address.  All of the failures were consistent with a failed VM that didn't reboot.
