### ISSUE TITLE
It's no longer possible to run SPDK w/ UIO devices with IOMMU enabled.

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#1188]
```
EAL:   Expecting 'PA' IOVA mode but current mode is 'VA', not initializing
EAL: Requested device 0000:83:00.0 cannot be used
```

I wanted to run w/ UIO for testing and development purposes, I guess I can't..?

I've read the commit history in spdk at I feel like we're reluctant to provide a `iova-mode=pa/va` option just like dpdk does and prefer automatic choice instead.

**Comment by jimharris** [comment]
Assigning to @benlwalker - can you get together with @darsto and bottom out on this?  Thanks.

**Comment by darsto** [comment]
Bug scrub: we agree on adding a command line param to force the iova mode.
Marking this as an enhancement.

**Comment by changpe1** [comment]
@darsto pinging, could you submit a patch to provide a parameter? Thanks.

**Comment by tomzawadzki** [comment]
Parameter `--iova-mode <pa/va>` was added in patch https://github.com/spdk/spdk/commit/eb76afe78b5c56281a8d0c987bb38b44186fd043.
This should be sufficient for this enhancement to be fulfilled.
