### ISSUE TITLE
--with-igb-uio-driver configure option doesn't work in isolation

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1189]
There are cases where someone may want to use the igb-uio driver, for example if uio_pci_generic is not available on their system.

But currently this option only works if you also specify --with-crypto or --with-reduce, since the original need for this igb_uio option came from QAT enablement.

The build system (i.e. dpdkbuild/Makefile) should support building the igb_uio driver even when crypto and reduce are not specified.

**Comment by Seth5141** [comment]
Sorry @tkulasek I know I'm not assigned to this one, but I ended up doing a fix for this as part of my docs change for #1153. Series here. https://review.spdk.io/gerrit/c/spdk/spdk/+/814/1

**Comment by tomzawadzki** [comment]
Patch fixing this issue was merged:
https://review.spdk.io/gerrit/c/spdk/spdk/+/792/3
