### ISSUE TITLE
configure silently fails with explicit dependencies

### ISSUE THREAD

**Issue by not7cd** [spdk/spdk#1193]
When using spdk as ExternalProject in CMake, certain errors can be ignored. It would be helpful if configure script could fail earlier.

## Expected Behavior
```
[root@daqdb-2 spdk]# ./configure --with-isal                                                                                                                              
Using default SPDK env in /home/user/daqdb/third-party/spdk/lib/env_dpdk
Using default DPDK in /home/user/daqdb/third-party/spdk/dpdk/build
Notice: ISA-L, compression & crypto auto-disabled due to nasm dependency.
These features require NASM version 2.13.03 or newer.  Please install
or upgrade then re-run this script.
Creating mk/config.mk...done.
Creating mk/cc.flags.mk...done.
Type 'make' to build.
[root@daqdb-2 spdk]# echo $?
1 
```

## Current Behavior
```
[root@daqdb-2 spdk]# ./configure --with-isal                                                                                                                              
Using default SPDK env in /home/user/daqdb/third-party/spdk/lib/env_dpdk
Using default DPDK in /home/user/daqdb/third-party/spdk/dpdk/build
Notice: ISA-L, compression & crypto auto-disabled due to nasm dependency.
These features require NASM version 2.13.03 or newer.  Please install
or upgrade then re-run this script.
Creating mk/config.mk...done.
Creating mk/cc.flags.mk...done.
Type 'make' to build.
[root@daqdb-2 spdk]# echo $?
0
```

## Possible Solution

When running `./configure` with specified dependency, it should return non-zero code when it can't be added to `mk/config.mk`

## Context (Environment including OS version, SPDK version, etc.)

https://github.com/daq-db/daqdb uses environment heavily patched by CernVM File System.

CentOS 7
spdk v19.07-39-ga2f6965

**Comment by tomzawadzki** [comment]
[Bug scrub] Since @tkulasek is working on configure changes to igb_uio, he can take on this one too. Please keep in mind looking at other places where explicit dependency is turned off.

**Comment by tkulasek** [comment]
Patch submitted: https://review.spdk.io/gerrit/c/spdk/spdk/+/971

**Comment by tomzawadzki** [comment]
Patch from @tkulasek  is now merged. The issue should be resolved.
