### ISSUE TITLE
Segfault running CI: START TEST iscsi_tgt_qos

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1199]
00:57:28	# ip netns exec spdk_iscsi_ns ./app/iscsi_tgt/iscsi_tgt -L sock_vpp
 00:57:28	# trap 'killprocess $pid; iscsitestfini $1 $2; exit 1' SIGINT SIGTERM EXIT
 00:57:28	# waitforlisten 1161344
 00:57:28	# '[' -z 1161344 ']'
 00:57:28	# local rpc_addr=/var/tmp/spdk.sock
 00:57:28	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 00:57:28	# xtrace_disable
 00:57:28	# '[' no '!=' yes ']'
 00:57:28	# PREV_BASH_OPTS=ehxBET
 00:57:28	# [[ ehxBET == *\x* ]]
 00:57:28	# XTRACE_DISABLED=yes
 00:57:28	# set +x
Starting SPDK v20.04-pre git sha1 2f708dba54 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: iscsi --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1161344 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
/var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/test/common/autotest_common.sh: line 404: 1161344 Segmentation fault      (core dumped) $ISCSI_APP
/var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk/test/common/autotest_common.sh: line 420: kill: (1161344) - No such process
ERROR: process (pid: 1161344) is no longer running

Full Log: https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/60457/archive/vpp_autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_60457.html

**Comment by jimharris** [comment]
Bug scrub: this dumped in VPP code - closing this issue since we're just in maintenance mode for now with VPP and not actively debugging VPP-related issues
