### ISSUE TITLE
JSON config test failed in the test pool

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1203]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/3235/archive/centos7-autotest/build.log

The following error was observed.

```
 08:57:42	# /var/jenkins/workspace/centos7-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_lvol_delete lvs_test/clone0
vbdev_lvol_rpc.c: 978:spdk_rpc_bdev_lvol_delete: *ERROR*: no bdev for provided name lvs_test/clone0
request:
{
  "name": "lvs_test/clone0",
  "req_id": 1,
  "method": "bdev_lvol_delete"
}
Got JSON-RPC error response
response:
{
  "message": "No such device",
  "code": -19
}
```

Nothing is investigated yet.

**Comment by pawelkax** [comment]
@shuhei-matsumoto I think that reason of this failure could be that tasting was not finished before deleting lvol bdev. @tomzawadzki What do you think?

**Comment by peluse** [comment]
This *might* be a fix.  Signature for the failure looks the same but I would have thought we'd see more than just a few intermittent.  https://review.spdk.io/gerrit/c/spdk/spdk/+/1008

**Comment by tomzawadzki** [comment]
No similar log has been posted for almost two months. If it appears again, lets re-open.
