### ISSUE TITLE
Test pool failed but no logs have not been generated.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1207]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3490.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3490.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3681.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_4045.html

**Comment by jimharris** [comment]
Assigning to @Seth5141

**Comment by changpe1** [comment]
It's same with #1177.

**Comment by karlatec** [comment]
It's not the same issue :)
@shuhei-matsumoto can you please see if this shows up in some of the latest test runs? I've made some changes to the CI and the way tests are retried in case of unexpected failures.

I've looked through most of the failed test runs listed on ci.spdk.io and I haven't found anything with "logs not generated"

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5050.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_5767.html

**Comment by tomzawadzki** [comment]
Bug scrub: No new reports have been posted since the changes mentioned by Karol month ago were done. Closing.

**Comment by Seth5141** [comment]
I saw this again this morning.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_7718.html

**Comment by karlatec** [comment]
Whoa... so in all cases of "logs not generated" there were multiple failures with `FATAL: java.io.IOException: Unexpected termination of the channel`. It's just that the number of retries was exceeded.
I see a long series of failed builds which caused a massive amounts of test nodes reboot. These builds also had test retries due to "Unexpected termination of the channel".

I didn't go through all of them, but if there's only this one you reported then it looks like Jenkins rules are working pretty well :P

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_7717.html

**Comment by tomzawadzki** [comment]
[Bug scrub] Jobs are configured to re-trigger 2 times and have not been seen for 12 days so far.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_9954.html
