### ISSUE TITLE
SPDK on  Samsung NVMe a802  Requested device 0000:05:00.0 cannot be used

### ISSUE THREAD

**Issue by SudarsunKannan** [spdk/spdk#121]
Hello,

I am trying to run SPDK on Samsung NVMe. After the boot, the /dev/nvme devices show up. Running the scripts/setup.sh script renames the device to /dev/vfio/vfio.  When running an example, I get the following error message. Can you suggest what might be the problem. I tried disabling intel_iommu off and on.

  $ sudo examples/nvme/hello_world/hello_world

EAL: Detected 16 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: No free hugepages reported in hugepages-1048576kB
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: Error - exiting with code: 1
  Cause: Requested device 0000:05:00.0 cannot be used

**Comment by SudarsunKannan** [comment]
Applying the patch from #105 solved the problem. Thanks!

**Comment by benlwalker** [comment]
Thanks for the report. We'll go ahead and get the patch from #105 merged.

**Comment by dverkamp-intel** [comment]
A variant of Ben's fix was merged as commit 08c69c9cc5a0d41209dc218d4198bb34fff51c63.
