### ISSUE TITLE
iscsi_tgt_rbd test: Ceph monitor data filesystem reached concerning levels of available storage space

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1212]
The following error was observed in the test pool.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/3887/archive/iscsi-autotest/build.log
```
+ ceph-run sh -c 'ulimit -n 16384 && ulimit -c unlimited && exec ceph-mon -c /var/tmp/ceph/ceph.conf -i a --keyring=/var/tmp/ceph/keyring --pid-file=/var/tmp/ceph/pid/root@WildcatPass4.pid --mon-data=/var/tmp/ceph/mon.a'
2020-02-18 08:43:27.226450 7f7152790180 -1 error: monitor data filesystem reached concerning levels of available storage space (available: 5% 5.52GiB)
you may adjust 'mon data avail crit' to a lower value to make this go away (default: 5%)

```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3887.html

**Comment by jimharris** [comment]
Failure was on WP4.  @karlatec - could you check if this system is running low on disk space?

**Comment by karlatec** [comment]
WP4 had 85% disk utilization with about ~15GB left. If I recall correctly then in Ceph tests we lay out some 10G file, so that's probably why it was complaining.

There was still some free space on the OS disk so I resized the partition. Let me know if the issue persists.

**Comment by jimharris** [comment]
Thanks @karlatec.  I'm going to close this issue.
