### ISSUE TITLE
freebsd-autotest is cloning rocksdb from gerrithub (not new gerrit instance)

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1214]
Raising for visibility. Happened only once so far, marking as intermittent for now.

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/3913/archive/freebsd-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_3913.html

**Comment by jimharris** [comment]
This was probably just an intermittent network issue.

But looking at the log, we're still cloning rocksdb from gerrithub - not the new SPDK instance.

So I'm keeping this bug open but renaming it.  @Seth5141 or @karlatec - can one of you take this?

**Comment by jimharris** [comment]
Bug scrub: @Seth5141 thinks this has already been fixed (to stop cloning from gerrithub).  Assigning to him and he'll check for sure tomorrow.

**Comment by Seth5141** [comment]
I confirmed that the autotest upstream job is configured to clone from review.spdk.io and just just merged a patch to fix an additional lagging reference to the old gerrit version.
