### ISSUE TITLE
NVMe discover failed with Input/output error for NVMe host with Kernel ver 5.3

### ISSUE THREAD

**Issue by govind-rathod1987** [spdk/spdk#1219]
NVMe discover failed with Input/output error a below:

linux-q9xz:~ # nvme discover -t rdma -a 100.100.20.32
Failed to write to /dev/nvme-fabrics: Input/output error
linux-q9xz:~ #

dmesg output is:
[ 5743.295642] nvme nvme9: Connect command failed, error wo/DNR bit: 6
[ 5743.296728] nvme nvme9: failed to connect queue: 0 ret=6

using latest 5.3 kernel:
linux-q9xz:~ # uname -r
5.5.3-195-default
linux-q9xz:~ #

loaded Inbox drivers:
linux-q9xz:~ # lsmod | grep nvme
nvme_rdma 36864 0
rdma_cm 73728 1 nvme_rdma
ib_core 372736 6 rdma_cm,nvme_rdma,iw_cm,ib_uverbs,mlx5_ib,ib_cm
nvmet_fc 32768 1 lpfc
nvmet 98304 1 nvmet_fc
configfs 53248 3 rdma_cm,nvmet
nvme_fc 45056 1 lpfc
nvme_fabrics 28672 2 nvme_fc,nvme_rdma
linux-q9xz:~ #

Note : it works with NVMe hosts with kernel ver 4.19 or 4.20 but not with NVMe host with kernel ver 5.3 on wards

**Comment by changpe1** [comment]
Can you also list the SPDK version and the debug messages when this issue happens?

**Comment by govind-rathod1987** [comment]
SPDK ver : 19.04
at host dmesg i see following error :
[600952.224056] nvme nvme16: Connect command failed, error wo/DNR bit: 6
[600952.225036] nvme nvme16: failed to connect queue: 0 ret=6

**Comment by changpe1** [comment]
Have you tried with latest SPDK version? I'm wondering there is some mismatch for the new kernel version.

**Comment by govind-rathod1987** [comment]
ok in that case i shall try updating my SPDK ad get back with my findings.
Thanks

**Comment by govind-rathod1987** [comment]
Hi it works after updating SPDK from 19.04 to 20.
i verified discover and connect form hosts running with kernel ver 4.19 and 5.5 version to my SPDK (ver 20) with kernel 4.19

**Comment by jimharris** [comment]
Thanks @govind-rathod1987.  Closing this issue.
