### ISSUE TITLE
Full stack hotplug support was dropped?

### ISSUE THREAD

**Issue by uchida2016** [spdk/spdk#122]
I noticed that full stack hotplug support is removed from the following release note.

https://github.com/spdk/spdk/wiki/Release-17.03

Will SPDK support it in the next release? I really expect it.

**Comment by optimistyzy** [comment]
@uchida2016 We are currently still working in this area and may happen in next release or later, it is not dropped.

**Comment by uchida2016** [comment]
Thanks. I'm happy to hear that. I hope it is available in next release.
