### ISSUE TITLE
io channel ref leak results in nvmf_tgt "hang"

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1220]
## Expected Behavior

- app shall be able to exit with ctrl + c or spdk_kill_instance SIGTERM
- it would be nice to have err reported
"thread %s still has active channel"

## Current Behavior

app doesn't exit

## Steps to Reproduce

e.g.
add spdk_nvmf_poll_group_create(transport->tgt);
in spdk_nvmf_tcp_listen

## Context (Environment including OS version, SPDK version, etc.)

issue shall be reproducible on master branch

**Comment by jimharris** [comment]
Hi @jkalwas,

If sounds like you're saying that if you add an extra spdk_nvmf_poll_group_create() call in spdk_nvmf_tcp_listen(), without any code to destroy that poll group, that the nvmf target won't exit.  If so, any further explanation on the need to add such a call to spdk_nvmf_tcp_listen() would be great.

If you could add specifics - including a patch - that would help assist with reproduction and understanding the intent behind filing this issue.

I don't think we should expect the target to exit gracefully when adding poll groups like this, but I'll defer further comment until we confirm the reproduction steps.

Thanks,

-Jim

**Comment by jkalwas** [comment]
Hi @jimharris 

https://review.spdk.io/gerrit/c/spdk/spdk/+/630/1/lib/nvmf/muser.c#2099

The fix is easy, we should prevent leaks. However, it can be not so obvious when new transport introduced with N k lines of new code - so it would be good to have at least warning/error during shutdown - I'm not sure if that is possible though.

Given reproduction example with tcp was the minimal one to reproduce the "hang".

Thanks,
Jacek

**Comment by Comphix** [comment]
> Hi @jimharris
> 
> https://review.spdk.io/gerrit/c/spdk/spdk/+/630/1/lib/nvmf/muser.c#2099
> 
> The fix is easy, we should prevent leaks. However, it can be not so obvious when new transport introduced with N k lines of new code - so it would be good to have at least warning/error during shutdown - I'm not sure if that is possible though.
> 
> Given reproduction example with tcp was the minimal one to reproduce the "hang".
> 
> Thanks,
> Jacek

Hi Jacek,

For this reproduction, it is based on the patch you mentioned above and with current TCP testing configuration? Could you give more information here about the reproduction like based on which SPDK commit, testing configuration, testing method and so on?

Thanks.

**Comment by jkalwas** [comment]
Hi Gang,

No, that was just an example patch when leak can occur and potentially this hang issue.
In the main thread I mentioned it shall be reproducible on master branch (but I haven't capture exact commit sha). I took top from the time I raised the issue and just modified lib/nvmf/tcp.c.

as for the minimal steps to reproduce
* checkout master
* modify tcp.c / rebuild
* run nvmf_tgt
* create tcp transport 
* create subsystem
* add listener
* kill (with sigterm)

Regards,
Jacek

**Comment by jimharris** [comment]
Bug scrub: in this case, there's not much the io channel code can do to try to communicate anything to the user - the problem here was a poll group was created and never deleted

Agree that when possible we should give hints to the user when we can't gracefully shut down, but in this case, it was just a bug in the code that needed to be fixed.
