### ISSUE TITLE
Different nvme name for cuse and kernel in nvme_cli_cuse test

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#1223]
During test nvme_cli_cuse got following error:
```
 07:44:45	# /usr/local/src/nvme-cli/nvme get-log /dev/spdk/nvme0 -i 1 -l 100
 07:44:47	# /usr/local/src/nvme-cli/nvme reset /dev/spdk/nvme0
nvme_ctrlr.c:1088:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
 07:44:48	# set -e
 07:44:48	# for i in {1..10}
 07:44:48	# '[' -f /var/jenkins/workspace/nvme-autotest/spdk/test/nvme/match_files/kernel.out.1 ']'
 07:44:48	# '[' -f /var/jenkins/workspace/nvme-autotest/spdk/test/nvme/match_files/cuse.out.1 ']'
 07:44:48	# diff --suppress-common-lines /var/jenkins/workspace/nvme-autotest/spdk/test/nvme/match_files/kernel.out.1 /var/jenkins/workspace/nvme-autotest/spdk/test/nvme/match_files/cuse.out.1
1c1
< nvme2n1: namespace-id:1
---
> nvme0n1: namespace-id:1
```

Log with this output: https://ci.spdk.io/results/autotest-per-patch/builds/4328/archive/nvme-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://ci.spdk.io/public_build/autotest-per-patch_4328.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://ci.spdk.io/public_build/autotest-per-patch_4333.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://ci.spdk.io/public_build/autotest-per-patch_4336.html

**Comment by tkulasek** [comment]
Patch with fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/981

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_4351.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4500.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4502.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4512.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_4400.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_4525.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_4385.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_4520.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_4526.html

**Comment by tkulasek** [comment]
It looks like patch with the fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/981 is already merged but I cannot find these changes on the current master.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_4541.html

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/981 is now merged.
If this failure occurs again, please make sure to rebase on master before re-opening.
