### ISSUE TITLE
nvme_cli_cuse fails while diffing KERNEL_OUT and CUSE_OUT

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1224]
Build log: https://ci.spdk.io/results/autotest-per-patch/builds/4355/archive/nvme-autotest/build.log

Failure occurs while comparing outputs from the very first get-ns-id commands.  Diff looks like so:

```
1c1
< nvme4n1: namespace-id:1
---
> nvme0n1: namespace-id:1
```

The problem is the name of the nvme device that's picked up from the sysfs - `setup.sh` picks up 3 nvme devices, starting from nvme4 (0000:00:09.0)  and this is the device that's used throughout the test. However, for the CUSE runs the name of the first registered device will be always nvme0 hence the discrepancy. 

The question is if ordering of the nvme devices, as seen by the kernel at the time of the test, is something that should be considered as abnormal circumstance (I guess yes, assuming that nvme0 become all of the sudden nvme4 during kernel's runtime). Since simple resetting|rescanning of the controller doesn't yield similar outcome, the only way I could force this scenario is by removing the controller from the entire pci bus, while its devices are actively used, and then adding it back:
```
[root@fedora31 spdk]# parted /dev/nvme0n1 -s -- unit s mklabel msdos mkpart primary 2048 -1
[root@fedora31 spdk]# mke2fs -text4 -b4096 -m0 /dev/nvme0n1p1
mke2fs 1.45.5 (07-Jan-2020)
Creating filesystem with 261888 4k blocks and 65536 inodes
Filesystem UUID: 8b55a855-1c49-452e-900c-e0ed4846f86b
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376

Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done
[root@fedora31 spdk]# mount /dev/nvme0n1p1 /mnt/device/
[root@fedora31 spdk]# echo 1 >/sys/class/nvme/nvme0/device/remove
[root@fedora31 spdk]# echo 1 >/sys/bus/pci/rescan
# nvme1 popped up, but oddly enough, the actual ns device is nvme0n2?
 [root@fedora31 spdk]# :/sys/class/nvme/nvme1/nvme0n2/
alignment_offset   dev                events             ext_range          inflight           nsid               queue/             ro                 stat               uevent
bdi/               device/            events_async       hidden             integrity/         nvme0n2p1/         range              size               subsystem/         wwid
capability         discard_alignment  events_poll_msecs  holders/           mq/                power/             removable          slaves/            trace/
# FUGLY HACK:
[root@fedora31 spdk]# ln -s nvme0n2 /dev/nvme1n1

# Now, the tests fails in a similar fashion since the nvme1 is picked up from sysfs:
1c1
< nvme1n1: namespace-id:1
---
> nvme0n1: namespace-id:1
```
I am not quite sure how to easily mitigate this from within the actual test script. Maybe linking to `/dev/spdk/nvme0n1` with kernel's name and providing that link to `nvme` would be enough?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_4355.html

**Comment by tkulasek** [comment]
This is the same issue as https://github.com/spdk/spdk/issues/1223, patch with fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/981
