### ISSUE TITLE
how to detect hot-inserted device dynamically

### ISSUE THREAD

**Issue by triplen21c** [spdk/spdk#1225]
Hello I am new with SPDK and I have probably a quite stupid question but so. I am implementing the ability to add devices dynamically. 

The devices already installed before running 'setup.sh' are well detected via 'spdk_nvme_probe'. 
However, newly inserted devices after running 'setup.sh' are not detected by spdk_nvme_probe. I am wondering the solution to detect the hot-insertion event and rebinding the driver. Since setup.sh takes a long time, is there a way to programmatically bind drivers only to newly detected devices instead of full running setup.sh?

Appreciate any thoughts.

**Comment by ak-gh** [comment]
You should enable nvme hotplug with the respective RPC.

Regards,
Andrey

**Comment by darsto** [comment]
If you look into setup.sh it basically rebinds each nvme pcie device to another kernel driver, either vfio-pci or uio_pci_generic. You could bind PCIe devices to those kernel drivers automatically on hotplug with linux  `udev` rules.

**Comment by ak-gh** [comment]
On Mon, Feb 24, 2020, 12:21 Darek Stojaczyk <notifications@github.com>
wrote:

> If you look into setup.sh it basically rebinds each nvme pcie device to
> another kernel driver, either vfio-pci or uio_pci_generic. You could bind
> PCIe devices to those kernel drivers automatically on hotplug with linux
> udev rules.
>
Darek,

does spdk provide an example of the udev rule to bind pcie device to
vfio_pci?

Thanks,
Andrey

**Comment by darsto** [comment]
Hey Andrey, no - I don't think so. `grep -R "udev"` doesn't return anything. It's kind of generic linux knowledge though. If you can google `udev bind` and find what you wanted I don't see a need to describe it in our docs.

**Comment by darsto** [comment]
We can continue this discussion here, but I'm going to close the github issue.

**Comment by triplen21c** [comment]
thanks all, helped a lot :)

**Comment by ShinJoonSeob** [comment]
> thanks all, helped a lot :)



> Hello I am new with SPDK and I have probably a quite stupid question but so. I am implementing the ability to add devices dynamically.
> 
> The devices already installed before running 'setup.sh' are well detected via 'spdk_nvme_probe'. However, newly inserted devices after running 'setup.sh' are not detected by spdk_nvme_probe. I am wondering the solution to detect the hot-insertion event and rebinding the driver. Since setup.sh takes a long time, is there a way to programmatically bind drivers only to newly detected devices instead of full running setup.sh?
> 
> Appreciate any thoughts.

are you still have this issues? I want the same thing as you. can you help for me? if you fixed it
