### ISSUE TITLE
SPDK nvme cli test failed with NVMf target

### ISSUE THREAD

**Issue by changpe1** [spdk/spdk#1228]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

./nvme discover -t rdma -a 192.168.100.8 -s 4420
Starting SPDK v20.04-pre git sha1 87eaec2df / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: nvme_cli --no-shconf -c 0x1 -m 512 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid157567 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
nvme.c: 598:spdk_nvme_probe_internal: *ERROR*: NVMe trtype 1 not available
nvme.c: 726:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed

## Context (Environment including OS version, SPDK version, etc.)

https://ci.spdk.io/public_build/autotest-per-patch_4444.html
https://ci.spdk.io/public_build/autotest-per-patch_4646.html
https://ci.spdk.io/public_build/autotest-per-patch_4499.html

**Comment by changpe1** [comment]
Here is the fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/1001

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_4543.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_4683.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_4674.html
