### ISSUE TITLE
VPP Process leaked file descriptors

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1229]
07:34:24	# cp ./app/iscsi_tgt/iscsi_tgt /var/jenkins/workspace/vpp-autotest/spdk/../output
 07:34:24	# mv ./core.3563945 /var/jenkins/workspace/vpp-autotest/spdk/../output
 07:34:25	# chmod a+r /var/jenkins/workspace/vpp-autotest/spdk/../output/./core.3563945
 07:34:25	# ret=1
 07:34:25	# IFS=
 07:34:25	# read -r -d '' core
 07:34:25	# return 1
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[vpp-autotest] $ /usr/bin/env bash /tmp/jenkins3568083104112302503.sh

## Steps to Reproduce

1.
2.
3.
4.

**Comment by glodfish-zg** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/4655/archive/vpp-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_4655.html

**Comment by karlatec** [comment]
This issue seems invalid.
The actual reason of fail is some random unrelated crash when running fio:
```
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
 07:34:24	# xtrace_enable
 07:34:24	# ((  i == 0  ))
 07:34:24	# return 0
 07:34:24	# /var/jenkins/workspace/vpp-autotest/spdk/scripts/rpc.py load_config
Connection closed with partial response:



./test/iscsi_tgt/fio/fio.sh: line 73: 3563945 Segmentation fault      (core dumped) $ISCSI_APP --wait-for-rpc
```

As for the "process leaked file descriptors" - this shows up when some process spawned as part of the test lives longer than the build itself. 
So in case there is a fail the build finishes with RC !=0. If there are some processes still running in the background (e.g. some SPDK app process) then this message will be displayed. It might suggest that "trap" routines in our scripts do not work 100% how they should.

**Comment by darsto** [comment]
```
Core was generated by `./app/iscsi_tgt/iscsi_tgt -L sock_vpp --wait-for-rpc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f016c9d4127 in ?? ()
[Current thread is 1 (LWP 3563945)]

Thread 2 (LWP 3563947):
#0  0x00007f016c9d9a27 in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 3563945):
#0  0x00007f016c9d4127 in ?? ()
No symbol table info available.
#1  0x0000000000c97f00 in ?? ()
No symbol table info available.
#2  0x00007fff9c4551c0 in ?? ()
No symbol table info available.
#3  0x0000000000000008 in ?? ()
No symbol table info available.
#4  0x0000000000000045 in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
```

That's a bummer. Looks like stack corruption. @glodfish-zg could you create another issue for the above? I'm going to close this one.
