### ISSUE TITLE
[RPC] framework_get_config doesn't yield all the crypto info 

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1231]
Consider the following setup:
```
[root@GrizzlyPass3 test]# ./app/spdk_tgt/spdk_tgt &
[1] 228126
[root@GrizzlyPass3 test]# Starting SPDK v20.04-pre git sha1 c0080ef55 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid228126 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 317:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
cryptodev_aesni_mb_create() line 1321: IPSec Multi-buffer library version used: 0.52.0


[root@GrizzlyPass3 test]# ./scripts/rpc.py <<-RPC
> bdev_malloc_create -b Malloc0 16 512
>                 bdev_malloc_create -b Malloc1 16 512
>                 bdev_crypto_create Malloc0 crypto_ram crypto_qat 0123456789123456
>                 bdev_crypto_create -c AES_XTS -k2 0123456789123456 Malloc1 crypto_ram3 crypto_qat 0123456789123456
> RPC
accel_engine.c: 181:accel_engine_create_cb: *NOTICE*: Acceleration framework using module: SOFTWARE
Malloc0
accel_engine.c: 181:accel_engine_create_cb: *NOTICE*: Acceleration framework using module: SOFTWARE
Malloc1
vbdev_crypto.c:1794:vbdev_crypto_claim: *NOTICE*: QAT in use: Required alignment set to 9
vbdev_crypto.c:1796:vbdev_crypto_claim: *NOTICE*: QAT using cipher: AES_CBC
accel_engine.c: 181:accel_engine_create_cb: *NOTICE*: Acceleration framework using module: SOFTWARE
crypto_ram
vbdev_crypto.c:1794:vbdev_crypto_claim: *NOTICE*: QAT in use: Required alignment set to 9
vbdev_crypto.c:1798:vbdev_crypto_claim: *NOTICE*: QAT using cipher: AES_XTS
accel_engine.c: 181:accel_engine_create_cb: *NOTICE*: Acceleration framework using module: SOFTWARE
crypto_ram3
```
Based on the above, for Malloc1 bdev, I would expect the subsystem to report the entire crypto setup including key2 and the cipher type. However, this is not the case:
```
[root@GrizzlyPass3 test]# ./scripts/rpc.py framework_get_config bdev
[
  {
    "method": "bdev_set_options",
    "params": {
      "bdev_io_pool_size": 65535,
      "bdev_io_cache_size": 256
    }
  },
  {
    "method": "bdev_crypto_create",
    "params": {
      "base_bdev_name": "Malloc0",
      "name": "crypto_ram",
      "crypto_pmd": "crypto_qat",
      "key": "0123456789123456"
    }
  },
  {
    "method": "bdev_crypto_create",
    "params": {
      "base_bdev_name": "Malloc1",
      "name": "crypto_ram3",
      "crypto_pmd": "crypto_qat",
      "key": "01234567891234560123456789123456" # <- Wut?
    }
  },
  {
    "method": "bdev_nvme_set_options",
    "params": {
      "action_on_timeout": "none",
      "timeout_us": 0,
      "retry_count": 4,
      "arbitration_burst": 0,
      "low_priority_weight": 0,
      "medium_priority_weight": 0,
      "high_priority_weight": 0,
      "nvme_adminq_poll_period_us": 1000000,
      "nvme_ioq_poll_period_us": 0,
      "io_queue_requests": 0,
      "delay_cmd_submit": true
    }
  },
  {
    "method": "bdev_nvme_set_hotplug",
    "params": {
      "period_us": 100000,
      "enable": false
    }
  },
  {
    "method": "bdev_malloc_create",
    "params": {
      "name": "Malloc0",
      "num_blocks": 32768,
      "block_size": 512,
      "uuid": "dd8cb845-c6d5-403e-ba05-6a38dbf3cfa6"
    }
  },
  {
    "method": "bdev_malloc_create",
    "params": {
      "name": "Malloc1",
      "num_blocks": 32768,
      "block_size": 512,
      "uuid": "da8a77de-2f30-48e6-9c32-0e400b66e874"
    }
  }
]
[root@GrizzlyPass3 test]#
```
Instead, `key2` and `cipher` is missing, and key, for some reason, consists of both: `${key}${key2}`. This, unless I am missing something obvious here, doesn't look correct. Due to the way how this config looks like it cannot be passed as `--json`  anymore (in this particular case because length of the key gets corrupted and for cipher, since missing, default would be used instead of `AES_XTS`).

From the look of it, this is not rpc.py's fault since it parses all the arguments in the proper manner, the data it gets in return seems to be off.

**Comment by peluse** [comment]
yeah, my mistake.  I forgot to add QTS info to the config dump when I added QTS.  For XTS, it's actually one long key but easier to input as two keys.  I'll fix it

**Comment by peluse** [comment]
@mikeBashStuff here is what should fix this stuff https://review.spdk.io/gerrit/c/spdk/spdk/+/1008 

I need to test it here shortly, I'll update when I do but feel free to try it out.  Thanks for reporting!

**Comment by peluse** [comment]
OK, don't test yet :)

**Comment by peluse** [comment]
Just updated, should work a little better:

   "method": "bdev_crypto_create",
    "params": {
      "base_bdev_name": "malloc2",
      "name": "2cry1",
      "crypto_pmd": "crypto_qat",
      "key": "1234567890123456",
      "key2": "1234567890123456",
      "cipher": "AES_XTS"
    }
  },
  {
    "method": "bdev_crypto_create",
    "params": {
      "base_bdev_name": "malloc1",
      "name": "cry1",
      "crypto_pmd": "crypto_aesni_mb",
      "key": "1234567890123456",
      "cipher": "AES_CBC"
    }
  },

**Comment by mikeBashStuff** [comment]
Just to note that it would be really nice if this got merged before the work covered under this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/530/24 (i.e. the entire relation chain) is done so we could keep using this particular call to create json config out if its output. :)

**Comment by peluse** [comment]
@mikeBashStuff sorry I was out Wed/Thu this week.  I can't control when it gets merged, just when it is ready :) It'll be ready shortly, there's a CI test failing still that I just started to debug.

**Comment by peluse** [comment]
You know though, you can always rebase your patch on top of mine and just keep working...

**Comment by mikeBashStuff** [comment]
@peluse Yep. :) There's no rush though, my comment was just to simply point out what work would benefit from this particular fix. :)

**Comment by peluse** [comment]
@mikeBashStuff OK cool.. It's passing CI now, please review/test/vote :)
https://review.spdk.io/gerrit/c/spdk/spdk/+/1008

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1008 is now merged, this should fix the issue.
