### ISSUE TITLE
vbdev_crypto segfault with 16 devices

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#1232]
I am running fio targetting crypto virtual bdevs. When I configure 16 crypto devices for AESNI, I get a segmentation fault during the initialization of the vbdev_crypto module. When I reduce the number of crypto vbdevs to 8 or less the test runs successfully.

## Expected Behavior
fio should run successfully.

## Current Behavior
fio exits with a segmentation fault error. gdb trace is provided below

Starting 4 threads
[New Thread 0x7fff976b9700 (LWP 81888)]
Starting SPDK v20.01 git sha1 5ffffe9d9 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid81770 ]
[New Thread 0x7fff97eba700 (LWP 81889)]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
cryptodev_aesni_mb_create() line 1321: IPSec Multi-buffer library version used: 0.52.0

vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1529:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!

Thread 115 "fio" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff976b9700 (LWP 81888)]
crypto_dev_poller (args=0x7fffc96f9980) at vbdev_crypto.c:558
558             uint8_t cdev_id = crypto_ch->device_qp->device->cdev_id;
(gdb) backtrace
#0  crypto_dev_poller (args=0x7fffc96f9980) at vbdev_crypto.c:558
#1  0x00007fffe7a58c39 in spdk_thread_poll (thread=0x7fffc800d490, max_msgs=max_msgs@entry=0, now=888636392902926, now@entry=0) at thread.c:531
#2  0x00007fffe79f4166 in spdk_fio_poll_thread (fio_thread=0x7fffc800d370) at fio_plugin.c:650
#3  spdk_init_thread_poll (arg=<optimized out>) at fio_plugin.c:298
#4  0x00007ffff68136db in start_thread (arg=0x7fff976b9700) at pthread_create.c:463
#5  0x00007ffff5d7088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) frame 0
#0  crypto_dev_poller (args=0x7fffc96f9980) at vbdev_crypto.c:558
558             uint8_t cdev_id = crypto_ch->device_qp->device->cdev_id;
(gdb) p *crypto_ch
$1 = {base_ch = 0x7fffc96f99d0, poller = 0x7fffc96f9c70, device_qp = 0x0, pending_cry_ios = {tqh_first = 0x0, tqh_last = 0x7fffc96f9998}, iter = 0x0, queued_cry_ops = {
    tqh_first = 0x0, tqh_last = 0x7fffc96f99b0}}

## Steps to Reproduce

1. Create an SPDK configuration file that has more than 8 crypto devices.
2. Create an fio configuration file that consumes the configuration file above using the bdev fio plugin. 
3. Run fio with the configuration file created in the previous step
4. You should see a seg fault

## Context (Environment including OS version, SPDK version, etc.)
SPDK 20.01

**Comment by peluse** [comment]
So AESNI only has 8 qp and we only ever init one instance as there was no reason to do more at the time.  Will think about adding a startup RPC to change this value

**Comment by peluse** [comment]
for bug scrub discussion: using more than one AESNI PMD will remove this limitation, it will add some complexity to the code.  Nothing crazy but wanted to get some thoughts on whether we think 8 bdevs is enough or should I go ahead and do an RPC to allow up to 8 or something to enable 64 bdevs with AESNI?  FYI QAT limit is 92 (I think, something like that)

**Comment by jimharris** [comment]
What's the cost or overhead of just enabling 64 by default instead of 8?

**Comment by peluse** [comment]
I'll have to see, I doubt its much though and now that I think about it the implementation wouldn't be that bad because I already have aesni qp on their own list and there's no load balancing needed as it makes no difference if I have one PMD supporting 8 threads or 8 PMDs supporting 8 (1 ea) from a perf perspective.  So it'll just be a matter of creating 8 of them with unique names.  Probably Fri...

**Comment by peluse** [comment]
OK, this should be easy.  The num q pairs is configurable.  I'll test it out now...

**Comment by peluse** [comment]
Fix is here: https://review.spdk.io/gerrit/c/spdk/spdk/+/1063

**Comment by peluse** [comment]
Fix confirmed by submitter
