### ISSUE TITLE
NVMe RDMA target failed to connect in NVMe-CLI test

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1236]
#https://ci.spdk.io/results/autotest-per-patch/builds/4759/archive/nvmf-phy-autotest/build.log

EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
nvme.c: 598:spdk_nvme_probe_internal: *ERROR*: NVMe trtype 1 not available
nvme.c: 726:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_4759.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_4779.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_4810.html

**Comment by jimharris** [comment]
Bug scrub: @changpe1 will take a look

**Comment by changpe1** [comment]
This issue is same with #1228 and it was fixed via commit 8d6f48fb, so I'm going to close this one.
