### ISSUE TITLE
fio_nvme $PLUGIN_DIR/mock_sgl_config.fio --filename="trtype=$TEST_TRANSPORT adrfam=IPv4  verify failed

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1237]
07:39:04	# fio_nvme /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/mock_sgl_config.fio '--filename=trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1'
 07:39:04	# local fio_dir=/usr/src/fio
 07:39:04	# local nvme_plugin=/var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/fio_plugin
  07:39:04	# grep libasan
  07:39:04	# awk '{print $3}'
  07:39:04	# ldd /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/fio_plugin
 07:39:04	# asan_lib=
 07:39:04	# LD_PRELOAD=' /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/fio_plugin'
 07:39:04	# /usr/src/fio/fio /var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/mock_sgl_config.fio '--filename=trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1'
test: (g=0): rw=randrw, bs=(R) 16.0KiB-16.0KiB, (W) 16.0KiB-16.0KiB, (T) 16.0KiB-16.0KiB, ioengine=spdk, iodepth=128
fio-3.15
Starting 1 thread
Starting SPDK v20.04-pre git sha1 f7d2e7192a / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid264323 ]
EAL: No available hugepages reported in hugepages-1048576kB
verify: bad header rand_seed 5525354256175058256, wanted 959627741899344 at file trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1 offset 11206656, length 16384 (requested block: offset=11206656, length=16384)
verify: bad header rand_seed 1859088540537858825, wanted 5525354256175058256 at file trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1 offset 42270720, length 16384 (requested block: offset=42270720, length=16384)
fio: pid=264327, err=84/file:io_u.c:2068, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

test: (groupid=0, jobs=1): err=84 (file:io_u.c:2068, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=264327: Thu Feb 27 07:39:05 2020
  read: IOPS=4385, BW=65.4MiB/s (68.5MB/s)(32.2MiB/493msec)
    slat (nsec): min=4661, max=74716, avg=5863.58, stdev=4672.03
    clat (usec): min=2290, max=21202, avg=11803.72, stdev=1483.58
     lat (usec): min=2303, max=21207, avg=11809.64, stdev=1482.70
    clat percentiles (usec):
     |  1.00th=[ 4359],  5.00th=[10945], 10.00th=[11469], 20.00th=[11731],
     | 30.00th=[11863], 40.00th=[11863], 50.00th=[11994], 60.00th=[11994],
     | 70.00th=[11994], 80.00th=[12125], 90.00th=[12256], 95.00th=[12387],
     | 99.00th=[16712], 99.50th=[18482], 99.90th=[21103], 99.95th=[21103],
     | 99.99th=[21103]
  write: IOPS=4356, BW=68.1MiB/s (71.4MB/s)(32.9MiB/483msec); 0 zone resets
    slat (usec): min=31, max=703, avg=37.46, stdev=25.11
    clat (usec): min=9152, max=20962, avg=11603.40, stdev=893.22
     lat (usec): min=9279, max=20994, avg=11640.87, stdev=893.32
    clat percentiles (usec):
     |  1.00th=[10028],  5.00th=[11076], 10.00th=[11207], 20.00th=[11338],
     | 30.00th=[11338], 40.00th=[11469], 50.00th=[11469], 60.00th=[11600],
     | 70.00th=[11600], 80.00th=[11731], 90.00th=[11863], 95.00th=[11863],
     | 99.00th=[16450], 99.50th=[19268], 99.90th=[20317], 99.95th=[20579],
     | 99.99th=[20841]
  lat (msec)   : 4=0.47%, 10=1.95%, 20=94.91%, 50=0.33%
  cpu          : usr=80.69%, sys=17.28%, ctx=2, majf=0, minf=52
  IO depths    : 1=0.1%, 2=0.1%, 4=0.2%, 8=0.4%, 16=0.8%, 32=1.5%, >=64=97.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=98.2%, 8=1.7%, 16=0.1%, 32=0.1%, 64=0.0%, >=64=0.1%
     issued rwts: total=2162,2104,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=65.4MiB/s (68.5MB/s), 65.4MiB/s-65.4MiB/s (68.5MB/s-68.5MB/s), io=32.2MiB (33.8MB), run=493-493msec
  WRITE: bw=68.1MiB/s (71.4MB/s), 68.1MiB/s-68.1MiB/s (71.4MB/s-71.4MB/s), io=32.9MiB (34.5MB), run=483-483msec
  07:39:06	# trap - ERR
  07:39:06	# print_backtrace
  07:39:06	# [[ ehxBET =~ e ]]
  07:39:06	# args=("${BASH_ARGV[@]}")
  07:39:06	# local args
  07:39:06	# xtrace_disable
  07:39:06	# '[' no '!=' yes ']'
  07:39:06	# PREV_BASH_OPTS=ehxBET
  07:39:06	# [[ ehxBET == *\x* ]]
  07:39:06	# XTRACE_DISABLED=yes
  07:39:06	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/nvmf-tcp-autotest/spdk/test/common/autotest_common.sh:964 -> fio_nvme(["/var/jenkins/workspace/nvmf-tcp-autotest/spdk/examples/nvme/fio_plugin/mock_sgl_config.fio"],["--filename=trtype=tcp adrfam=IPv4 traddr=127.0.0.1 trsvcid=4420 ns=1"])
     ...
   959 		local nvme_plugin="$rootdir/examples/nvme/fio_plugin/fio_plugin"
   960 	
   961 		# Preload AddressSanitizer library to fio if fio_plugin was compiled with it
   962 		asan_lib=$(ldd $nvme_plugin | grep libasan | awk '{print $3}')
   963 	
=> 964 		LD_PRELOAD="$asan_lib $nvme_plugin" "$fio_dir"/fio "$@"
   965 	}
   966 	
   967 	function get_lvs_free_mb()
   968 	{
   969 		local lvs_uuid=$1
     ...
in test/nvmf/host/fio.sh:41 -> main(["--transport=tcp"])
     ...
   36  	# Test fio_plugin as host with malloc backend
   37  	fio_nvme $PLUGIN_DIR/example_config.fio --filename="trtype=$TEST_TRANSPORT adrfam=IPv4 \
   38  	traddr=$NVMF_FIRST_TARGET_IP trsvcid=$NVMF_PORT ns=1"
   39  	
   40  	# second test mocking multiple SGL elements
=> 41  	fio_nvme $PLUGIN_DIR/mock_sgl_config.fio --filename="trtype=$TEST_TRANSPORT adrfam=IPv4 \
   42  	traddr=$NVMF_FIRST_TARGET_IP trsvcid=$NVMF_PORT ns=1"
   43  	$rpc_py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
   44  	
   45  	if [ $RUN_NIGHTLY -eq 1 ]; then
   46  		# Test fio_plugin as host with nvme lvol backend
     ...

========== Backtrace end ==========

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_4826.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_4963.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_4969.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_4976.html

**Comment by jimharris** [comment]
Bug scrub: @benlwalker says we need to confirm that everywhere we are doing fio verify, that we specify the verify_backlog parameter.  Assigning to @Comphix

**Comment by optimistyzy** [comment]
By coincidence, I investigated this issue due to another issue. Unfortunately, I cannot reproduce this issue on my local platform (with malloc device) with many times running with different fio version, e.g., fio 3.15  or 3.18. The verify_backlog usage specified by FIO sounds correct, see the following verify_backlog explanation by fio man:

 verify_backlog=int
              Fio will normally verify the written contents of a job that utilizes verify once that job has completed. In other words, everything is  written  then
              everything  is  read back and verified. You may want to verify continually instead for a variety of reasons. Fio stores the meta data associated with
              an I/O block in memory, so for large verify workloads, quite a bit of memory would be used up holding this meta data. If this option is enabled,  fio
              will write only N blocks before verifying these blocks.

**Comment by Seth5141** [comment]
I am closing this since we know the underlying issue is this fio bug with not reconstructing the random seed correctly.
