### ISSUE TITLE
Namespace bdevs not populated properly on ns manage raw command

### ISSUE THREAD

**Issue by tkulasek** [spdk/spdk#1238]
Using namespace manage feature to create and delete namespaces via "bdev_nvme_send_cmd" RPC is not populated on bdev nor nvme layer.

E.g. sending create-ns, attach-ns doesn't create new bdev for namespace even when created properly on the controller. Sending reset after these commands also have no impact.

## Expected Behavior
Creating or deleting namespaces via raw commands should be populated properly on bdev layer.

## Steps to Reproduce

1. Send create namespace raw command
2. Send attach namespace raw command
3. Check if namespace bdev was created
4. Send detach namespace raw command
5. Send delete namespace raw command
6. Check if namespace bdev was removed

This is a test which can be used to reproduce this issue:
https://review.spdk.io/gerrit/c/spdk/spdk/+/922/6/test/nvme/nvme_ns_manage.sh

This patch adds sending reset to the controller arter create/delete namespace:
https://review.spdk.io/gerrit/c/spdk/spdk/+/1005/1/test/nvme/nvme_ns_manage.sh

## Context (Environment including OS version, SPDK version, etc.)

Controller I'm using for test:
```
=====================================================     
NVMe Controller at 0000:84:00.0 [8086:0a54]               
=====================================================     
Controller Capabilities/Features                          
================================                          
Vendor ID:                             8086               
Subsystem Vendor ID:                   8086               
Serial Number:                         PHLJ916004901P0FGN 
Model Number:                          INTEL SSDPE2KX010T8
Firmware Version:                      VDV10170

Optional Asynchronous Events Supported
  Namespace Attribute Notices:         Not Supported
  Firmware Activation Notices:         Supported

Admin Command Set Attributes
============================
Namespace Management:                  Supported
Async Event Request Limit:             4

Commands Supported and Effects
==============================
Admin Commands
--------------
                  Set Features (09h): Supported NS-Cap-Change NS-Inventory-Change Ctrlr-Cap-Change Get Features (0Ah): Supported
    Asynchronous Event Request (0Ch): Supported
          Namespace Management (0Dh): Supported LBA-Change NS-Cap-Change Per-NS-Exclusive
          Namespace Attachment (15h): Supported Per-NS-Exclusive
```

**Comment by tomzawadzki** [comment]
`Namespace Attribute Notices:         Not Supported`
`Namespace Management:                  Supported`
NVMe 1.4 spec, 8.12 Namespace Management. Specifies that when Namespace Management is turned on, then controller _should_ support the Namespace Attribute Changed asynchronous event.

Bdev nvme module updates the bdevs only when it receives AER, so it would makes sense that additional bdevs do not appear when that type of AER event is not supported.

Have you tested that bdev nvme creation works when controller supports both ?
Easy way to do that is with NVMe-oF target/initiator.

**Comment by benlwalker** [comment]
Can you clarify what hardware is being tested here? Is this a physical NVMe SSD that does support namespace management but does not support namespace attribute notice AER?

In that case, I don't think there's anything we can do to fix this. The upper layer doesn't know the command being sent is a namespace management command, so it has no idea it needs to look for new namespaces without that AER.

**Comment by tkulasek** [comment]
@benlwalker Yes, this is phisical hardware supporting namespace management and doesn't support ns attribute notice AER.
This is also not handled by linux kernel. To made namespace management effective, using nvme-cli with kernel driver it is required to reset controller after adding or deleting namespace.

**Comment by tomzawadzki** [comment]
Devices that do not support AER notifications, require a reset for namespace changes to take effect. Same behavior can be seen in linux Kernel as tested by @tkulasek.
This issue can be closed, as it seem this is the intended behavior.
