### ISSUE TITLE
rpc_http_proxy.py will not accept a json RAID configuration

### ISSUE THREAD

**Issue by dacrespi** [spdk/spdk#1239]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Creating a raid vbdev via the proxy does not appear to work with SPDK v20.01.  We have been using it with SPDK v19.07 for awhile now.  We just are switching everything over to support the v20.01 and this issue came up.

## Expected Behavior
We issue this command:
curl -H "Content-Type:application/json/" -X POST http://172.88.1.161:5260/ -d '{"id" : 1, "method" : "bdev_raid_create", "params": { "name" : "32TestRaid", "base_bdevs" : ["Nvme32n1p0", "Nvme32n1p2"], "strip_size_kb" : 64, "raid_level" : 0}}' --user support:support --connect-timeout 30

And SPDK returns this message:
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"spdk_json_decode_object failed"}}

## Current Behavior
We would expect that the 2 volume raid set would have been created.  This use to work in v19.07.
Running this through a dry-run with rpc.py we get:
Request:
{
  "method": "bdev_raid_create",
  "params": {
    "name": "32TestRaid",
    "raid_level": "0",
    "base_bdevs": [
      "Nvme32n1p0",
      "Nvme32n1p2"
    ],
    "strip_size_kb": 64
  }
}
Which looks to be what we're using with the proxy.

## Steps to Reproduce
1. Just issue the command above to the proxy.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
v20.01-0-g5ffffe9d9

**Comment by jimharris** [comment]
@Maciej-Szwed - could you take a look?

**Comment by Maciej-Szwed** [comment]
sure

**Comment by Maciej-Szwed** [comment]
I found the root cause of your problem. In rpc.py you get "raid_level": "0", but in curl command you use "raid_level" : 0.
There should be "0" (with " around it).
Please confirm if that works on your side and we can close this issue.

**Comment by dacrespi** [comment]
Yes, that does indeed work!!  I didn't think we needed to quote around numbers, just strings.  Well, regardless it's good to go, thanks!  Closed.

**Comment by jimharris** [comment]
Yeah - normally numbers don't need to be quoted, but in this case the raid level is a string - either "0" or "raid0" are accepted.
