### ISSUE TITLE
Unable to run IOs using the fio plugin

### ISSUE THREAD

**Issue by shivapahwa** [spdk/spdk#124]
We were in the process of evaluating SPDK on one of our NVMe devices.  Was able to build the binaries for SPDK but not able to direct IOs to a particular device.

I am trying to look deeper to figure out the solution, but i thought it would be a good idea to ask the community as well.

Configuration details:
OS: CentOS (4.8.5)
SPDK: 16.12
DPDK: 16.11
Processor: Intel i7-5960X (VT-x supported)

After building and loading SPDK driver, I do not see any block devices. When i issue IO using the device node name 0000:0a:00.0/1 or just 0000:0a:00.0, test errors with invalid file name.  How should i initiate IOs to a specific device?

Job file:
[fio_test]
filename=0000:0a:00.0
rw=read
ioengine=./example/nvme/fio_plugin/fio_plugin
iodepth=8
bs=128k
nubjobs=1
offset=1000
size=1M

Am i missing something?

When i initiate IOs, without specifying the filename, the IOs seem to go through. I also see error "could not initialize dpdk" when i increase the number of threads. 

I read the documentation about only one thread being supported,  I was not able to figure out why so? Any leads on how i should approach to change that?

I was not able to find any documentation related to the above, can someone point me to it if there is any?

**Comment by dverkamp-intel** [comment]
The FIO filename needs to have periods separating the fields (unfortunately, FIO's filename syntax doesn't allow us to use colons as you would expect by convention), so your filename line should be `filename=0000.0a.00.0/1`.  This is mentioned in examples/nvme_plugin/README.md, but it is probably not explicit enough about needing periods rather than colons.

**Comment by shivapahwa** [comment]
Thanks for the quick response. Any idea why there is a limitation with FIO running a single thread?

**Comment by benlwalker** [comment]
We're in the process of lifting the restrictions on fio - it was just a design limitation. Since your original bug now appears to be resolved I'm closing this issue.
