### ISSUE TITLE
Invalid argument is passed to python script in nvmf_invalid test case

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1240]
https://ci.spdk.io/results/autotest-per-patch/builds/5013/archive/nvmf-autotest/build.log
```

   03:56:31	# echo '-w,0s+l%j";j]*GeMAsSFkUX:O1Jb7#u=5_[aH:#D'
  03:56:31	# /var/jenkins/workspace/nvmf-autotest/spdk/scripts/rpc.py nvmf_create_subsystem -d '-w,0s+l%j";j]*GeMAsSFkUX:O1Jb7#u=5_[aH:#D' nqn.2016-06.io.spdk:cnode21655
 03:56:31	# out='usage: rpc.py nvmf_create_subsystem [-h] [-t TGT_NAME] [-s SERIAL_NUMBER]
                                    [-d MODEL_NUMBER] [-a] [-m MAX_NAMESPACES]
                                    nqn
rpc.py nvmf_create_subsystem: error: argument -d/--model-number: expected one argument'
 03:56:31	# [[ usage: rpc.py nvmf_create_subsystem [-h] [-t TGT_NAME] [-s SERIAL_NUMBER]
                                    [-d MODEL_NUMBER] [-a] [-m MAX_NAMESPACES]
                                    nqn
rpc.py nvmf_create_subsystem: error: argument -d/--model-number: expected one argument == *\I\n\v\a\l\i\d\ \M\N* ]]
  03:56:31	# trap - ERR

```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5013.html

**Comment by mikeBashStuff** [comment]
Well, this is unfortunate - the problem in this case is that the random string starts with `-` at the very beginning. Should be easy to fix.

**Comment by mikeBashStuff** [comment]
Potential fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/1054

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_5074.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_5122.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_5124.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5166.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5318.html

**Comment by shuhei-matsumoto** [comment]
Thank you so much @mikeBashStuff The patch has been merged.
