### ISSUE TITLE
discover_bdevs() stuck in a loop during blockdev_rbd test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1243]
`ceph` got missing so the config that was passed to `bdev_svc` was not valid. This resulted in `discover_bdevs()` being stuck in its loop waiting for `/var/run/spdk_bdev0`.

https://ci.spdk.io/results/autotest-per-patch/builds/5070/archive/iscsi-autotest/build.log

Potential mitigation with the CI in mind so it doesn't have to wait for 15 minutes before it marks build as failed: https://review.spdk.io/gerrit/c/spdk/spdk/+/1026

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_5070.html

**Comment by darsto** [comment]
That's why discover_bdevs is evil and we need to get rid of it. It won't be necessary after we remove .ini configs from our test scripts. ;)

**Comment by darsto** [comment]
The workaround was merged, so closing. Let's continue getting rid of discover_bdevs()
