### ISSUE TITLE
db_bench compilation fails

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1244]
`make` failed when run from `rocksdb.sh` as part of the `rocksdb` run_test.

https://ci.spdk.io/results/autotest-per-patch/builds/5105/archive/BlobFS-autotest/build.log

CI went through some upgrades recently, maybe this one is related?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_5105.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_5126.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5179.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5183.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_5204.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_5206.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_5212.html

**Comment by karlatec** [comment]
Started after updating test systems to F30 gcc version 9.2.1

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @pawelkax. log: https://ci.spdk.io/public_build/autotest-per-patch_5235.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_5236.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_5240.html

**Comment by darsto** [comment]
workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/1082

**Comment by jimharris** [comment]
Bug scrub: @changpe1 says that even very latest RocksDB still shows this same issue.

Assigning to @darsto for now, mainly because he's already posted the workaround patch.  We will need to monitor RocksDB mainline as well to see when they fix this upstream.

**Comment by darsto** [comment]
Sorry, I'm unassigning myself

**Comment by jimharris** [comment]
Workaround patch was merged, so closing this issue.

**Comment by jimharris** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/6083/archive/BlobFS-autotest/build.log

**Comment by darsto** [comment]
The patch above simply wasn't rebased. Closing again ;)
