### ISSUE TITLE
error: unknown option `dissociate' - when trying to clone in CI

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1245]
Note this does not seem to be the same as issue #1242 although the symptom is similar.

Started by upstream project "autotest-per-patch" build number 5097
originally caused by:
 Started by user sys_sgci
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building remotely on centos7_vm_3 (Centos7_VM) in workspace /var/jenkins/workspace/centos7-autotest
Running Prebuild steps
[centos7-autotest] $ /usr/bin/env bash /tmp/jenkins2554685466663956003.sh
Pre-SCM step. Deleting whole workspace.
Success build forhudson.tasks.Shell@3edbcae7
provisioning config files...
copy managed file [copy_or_clone] to file:/var/jenkins/workspace/centos7-autotest/copy_or_clone.sh
[centos7-autotest] $ /usr/bin/env bash /tmp/jenkins5390286664039239260.sh
MANUAL, will clone
error: unknown option `dissociate'
usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

./copy_or_clone.sh: line 19: cd: spdk: No such file or directory
git version 1.8.3.1
error: could not lock config file .git/config: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git

**Comment by jimharris** [comment]
Looks like @karlatec has fixed this already, so I'll skip posting logs here for now.

@karlatec - you can close this once you're ready.

**Comment by karlatec** [comment]
@jimharris Yeah, this one is totally on me. I was trying to improve cloning when using local mirror repos, but apparently CentOS has an ancient 1.8 git version which does not support --dissociate option.
Already gave a comment in affected commits and retriggered them;)
