### ISSUE TITLE
"Too long time for initialization" in nvme_startup

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1247]
https://ci.spdk.io/results/autotest-per-patch/builds/5177/archive/ubuntu18-autotest/build.log

```
   23.852 -    23.955:   9EAL: Driver cannot detach the device (0000:00:09.0)
EAL: Failed to hotplug remove device on primary
8.4161%  (        3)
   23.955 -    24.058:   98.4317%  (        1)
   24.058 -    24.161:   98.4783%  (        3)
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_5177.html

**Comment by darsto** [comment]
This message is somewhat expected in multi-process detach. We fail to detach the device and DPDK prints this message, but also handles the failure gracefully.

The direct failure here is `Too long time for initialization.`. in nvme_startup test. I have no clue why.

**Comment by jimharris** [comment]
Bug scrub: @jimharris will take a look

**Comment by jimharris** [comment]
@shuhei-matsumoto - I don't think we've seen this again since you originally reported it in March.  Do you think we can close it?

**Comment by shuhei-matsumoto** [comment]
@jimharris @darsto I don't see this issue since I added too. So let me close this. Thanks for crawling the issues.
