### ISSUE TITLE
vpp-autotest compilation fails on gcc version 9.2.1

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1249]
This one started after upgrading the systems to F30 with gcc 9.2.1

https://ci.spdk.io/public_build/autotest-per-patch_5235.html
https://ci.spdk.io/public_build/autotest-per-patch_5230.html
https://ci.spdk.io/public_build/autotest-per-patch_5218.html

**Comment by tomzawadzki** [comment]
@wawryk Can you please confirm fix posted by @tkulasek https://review.spdk.io/gerrit/c/spdk/spdk/+/1084 ?

**Comment by darsto** [comment]
Fix merged and Karol has verified it works
