### ISSUE TITLE
nvmf tcp autotest: verify: bad header rand_seed

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1250]
See https://ci.spdk.io/results/autotest-per-patch/builds/5159/archive/nvmf-tcp-autotest/index.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_5159.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_5287.html

**Comment by Seth5141** [comment]
Hi @peluse,

This is a known issue with the version of FIO we are using. There is a workaround on our master for this. Please rebase your change on master to get it to pass the build pool.
