### ISSUE TITLE
autotest-nightly tests all failed and no links

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1254]
https://ci.spdk.io/public_build/autotest-nightly.html

## Current Behavior
Previous Build Summary
Date | Result
-- | --
03-March 23:30:00 | Test Failure
03-March 20:30:00 | Test Failure
03-March 17:30:00 | Test Failure
03-March 14:30:00 | Test Failure

## Possible Solution
Administrator could restore links first.

**Comment by wanghailiangx** [comment]
Autotest-nightly-failing is the same.
https://ci.spdk.io/public_build/autotest-nightly-failing.html

**Comment by jimharris** [comment]
Bug scrub: assigning to @karlatec

**Comment by karlatec** [comment]
FYI, if you need to access nightly results then they're still available despite links not being displayed on mentioned pages.

Go to https://ci.spdk.io/ and search for "autotest-nightly" or "autotest-nightly-failing". Links will be in the left side column.

**Comment by wanghailiangx** [comment]
@karlatec OK, thank you. But we can't see through that entrance --**Job results** in the right side column.

### Job results
*AUTOTEST-PER-PATCH
*AUTOTEST-NIGHTLY **(error link)**
*AUTOTEST-NIGHTLY-FAILING **(error link)**
*AUTOTEST-SPDK-MASTER-VS-DPDK-MASTER
*SPDK-GITHUB-IO

**Comment by karlatec** [comment]
Fixed. Nightly builds summary pages available:
https://ci.spdk.io/public_build/autotest-nightly.html

FYI:
- There's no nightly failing now. It has been removed from configuration.
- Summary pages for "vs-dpdk" builds are not available now, but will appear soon.

**Comment by tomzawadzki** [comment]
Can confirm that links are working on the ci.spdk.io site.

**Comment by karlatec** [comment]
FYI: commit which will make vs-dpdk builds public is already merged and I'll put it into production this week.
