### ISSUE TITLE
NVMF: Initiator connection fails when subsystem is paused

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1256]
The fabric connect fails when when the subsystem is paused. This is very problematic if a subsystem has a lot namespaces that are coming an going.

Here's the code in question that fails the connect:
```
spdk_nvmf_ctrlr_cmd_connect:
...
if ((subsystem->state == SPDK_NVMF_SUBSYSTEM_INACTIVE) ||
        (subsystem->state == SPDK_NVMF_SUBSYSTEM_PAUSING) ||
        (subsystem->state == SPDK_NVMF_SUBSYSTEM_PAUSED) ||
        (subsystem->state == SPDK_NVMF_SUBSYSTEM_DEACTIVATING)) {
        SPDK_ERRLOG("Subsystem '%s' is not ready\n", subsystem->subnqn);
        rsp->status.sct = SPDK_NVME_SCT_COMMAND_SPECIFIC;
        rsp->status.sc = SPDK_NVMF_FABRIC_SC_CONTROLLER_BUSY;
        return SPDK_NVMF_REQUEST_EXEC_STATUS_COMPLETE;
    }
...
```
Wouldn't it be better to queue the request for a while an retry?
I do see that the request is added to the outstanding list in nvmfrequest_exec. Couldn't we just re-queue the request for a while?
```
nvmf_request_exec:
...
/* Place the request on the outstanding list so we can keep track of it */
    TAILQ_INSERT_TAIL(&qpair->outstanding, req, link);
    if (spdk_unlikely(req->cmd->nvmf_cmd.opcode == SPDK_NVME_OPC_FABRIC)) {
        status = spdk_nvmf_ctrlr_process_fabrics_cmd(req);
    } else if (spdk_unlikely(spdk_nvmf_qpair_is_admin_queue(qpair))) {
        status = spdk_nvmf_ctrlr_process_admin_cmd(req);
    } else {
        status = spdk_nvmf_ctrlr_process_io_cmd(req);
    }
    if (status == SPDK_NVMF_REQUEST_EXEC_STATUS_COMPLETE) {
        spdk_nvmf_request_complete(req);
    }

```
## Expected Behavior

The connect should not fail when the subsystem is temporarily paused.

## Current Behavior

Connection fails when subsystem is paused.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.01, CentOS8

**Comment by jimharris** [comment]
Bug scrub: connect command needs to be queued, but we need to make sure there's a timeout on that queue (for cases where the subsystem is paused for a longer period of time)

We need some stress tests around this - something like:
1) thread or process constantly issuing RPCs to add and remove namespaces from subsystem
2) thread or process constantly connecting to subsystem (and confirming the connects do not fail)

**Comment by jimharris** [comment]
@liang2yan will develop the stress test to reproduce this problem.  We still need someone to take the development side of fixing the bug.

**Comment by AlekseyMarchuk** [comment]
@jimharris I'll prepare a fix, probably next week

**Comment by jimharris** [comment]
Thanks @AlekseyMarchuk!

**Comment by liang2yan** [comment]
I have written simple scripts to do some stress testing.
In target machine, I run following scripts:
```
for fgh in $(seq 1 50); do
        for ig in $(seq 0 49); do
        ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null${ig}
        #       sleep 1
        done

        for ig in $(seq 1 50); do
                ./scripts/rpc.py nvmf_subsystem_remove_ns nqn.2016-06.io.spdk:cnode1 $ig
        done
done
```
At the same time, in host machine, I run following script:
```
for gh in $(seq 1 100); do
nvme connect -n nqn.2016-06.io.spdk:cnode1  -t rdma -a 192.234.12.11 -s 4420
nvme disconnect -n nqn.2016-06.io.spdk:cnode1
done
```
The nvme command in host machine hung up at the first "nvme disconnect". Since subsystem is paused while adding and removing ns, so I think nvme hung up should be expected.

**Comment by AlekseyMarchuk** [comment]
I prepared a patch to queue connect command while subsystem is not active https://review.spdk.io/gerrit/c/spdk/spdk/+/1273
@jimharris you wrote about a timeout to prevent a long subsystem pause time. I didn't find easy way to implement it, will check possible solution next week. Could you take a look at the patch to confirm that the general approach is correct?

**Comment by jimharris** [comment]
The general approach looks good to me Alexey.

@liang2yan - could you create a test script that implements what you described above?  And then we should add it to Alexey's patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/1273

**Comment by liang2yan** [comment]
Yes, I am preparing a patch to run the test case.

**Comment by liang2yan** [comment]
I have submitted one patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1350 to reproduce this issue. I have used this patch to verify Alexey's patch, but also failed. So I am continuing to improve this patch and also alexey's patch.

**Comment by AlekseyMarchuk** [comment]
@liang2yan Could you clarify how it failed? Maybe you have logs?

**Comment by liang2yan** [comment]
@AlekseyMarchuk , I will run again and  get the log. But I am not sure the script does reproduce this issue in loopback mode. So I need to improve the script as mentioned.

**Comment by liang2yan** [comment]
@AlekseyMarchuk , please see attached file for the log which I got in two machines testing.
[1326.txt](https://github.com/spdk/spdk/files/4367394/1326.txt)

**Comment by AlekseyMarchuk** [comment]
@liang2yan I left a comment to your patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1350
