### ISSUE TITLE
function level reset and subsystem reset occurs drive drop

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1257]
We tried to do function level reset(FLR) by setting FLR bit to 1 to trigger the reset,
but we got some error message and drive drop occured, 
we already do same experiment on different SSD drive and still got the same results, 
the error message is as follows :

> nvme_ctrlr.c: 735:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
> nvme_pcie.c: 573:nvme_pcie_ctrlr_unmap_cmb: *ERROR*: get_cmbloc() failed
> nvme_pcie.c: 680:nvme_pcie_ctrlr_free_bars: *ERROR*: nvme_ctrlr_unmap_cmb failed with error code -5

The code we wrote to do FLR :

```
ret = spdk_pci_device_cfg_read8(dev, &pxdcap_reg, cap_pointer + 0x07);
		if (ret) {
			perror("failed to read pxdcap_reg\n");
			exit(1);
		}
		if (!(pxdcap_reg & 0x10)) {
			printf("doesn't support function level reset(FPR) capability\n");
			exit(1);
		} else {
			printf("support function level reset(FPR) capability\n");		
		}

		pxdc_reg &= ~(0x80);
		pxdc_reg |= 0x80;
		ret = spdk_pci_device_cfg_write8(dev, pxdc_reg, cap_pointer + 0x09);
		if (ret) {
			perror("failed to write pxdc_reg\n");
			exit(1);
		}
```

please help to check this issue, thanks!

**Comment by jimharris** [comment]
Bug scrub: @jimharris will take a look at what SPDK should do here.

We should also check PCI capability registers to confirm the SSD supports FLR (thanks Changing).

**Comment by ryderhsu0129** [comment]
> Bug scrub: @jimharris will take a look at what SPDK should do here.
> 
> We should also check PCI capability registers to confirm the SSD supports FLR (thanks Changing).
thanks for your reply.

the code I attached that already confirmed SSD supports FLR before setting FLR bit to trigger reset,
but drive drop still occurred, I don't understand why nvme_ctrlr_shutdown() is called after setting FLR bit, it seems to be the cause.

**Comment by ryderhsu0129** [comment]
We also tried to do subsystem reset(NSSR) by setting NSSRC bit to trigger the reset,
we got same error message and drive drop occurred,
the error message is same as above attached :

> nvme_ctrlr.c: 735:nvme_ctrlr_shutdown: ERROR: get_cc() failed
> nvme_pcie.c: 573:nvme_pcie_ctrlr_unmap_cmb: ERROR: get_cmbloc() failed
> nvme_pcie.c: 680:nvme_pcie_ctrlr_free_bars: ERROR: nvme_ctrlr_unmap_cmb failed with error code -5

attached the code we wrote to do NSSR:
```
	if (nvme_ctrlr_get_cap(g_controllers->ctrlr, &cap)) {
		perror("get cap failed\n");
		return 1;
	}

	if (!cap.bits.nssrs) {
		perror("doesn't support NVMe subsystem reset\n");
		return 1;
	}

	if (nvme_ctrlr_get_cc(g_controllers->ctrlr, &cc)) {
		perror("get cc failed\n");
		return 1;
	}

	if (nvme_ctrlr_set_nssr(g_controllers->ctrlr, SPDK_NVME_NSSR_VALUE)) {
		perror("set nssr failed\n");
		return 1;
	}

	return 0;
```
we used nvme-cli tool to do NSSR on same SSD drive is work.

**Comment by jimharris** [comment]
Hi @ryderhsu0129 - can you describe a few things:

1) what application are you running for your test?
2) where are you adding the code to do the FLR?
3) are you using uio_pci_generic or vfio-pci in your environment?
4) do you see any change in behavior if you call spdk_nvme_ctrlr_reset() immediately after doing the FLR or NSSR?

Thanks,

-Jim

**Comment by ryderhsu0129** [comment]
> Hi @ryderhsu0129 - can you describe a few things:
> 
> 1. what application are you running for your test?
> 2. where are you adding the code to do the FLR?
> 3. are you using uio_pci_generic or vfio-pci in your environment?
> 4. do you see any change in behavior if you call spdk_nvme_ctrlr_reset() immediately after doing the FLR or NSSR?
> 
> Thanks,
> 
> -Jim

Hi @jimharris 

> 1. what application are you running for your test?
> 2. where are you adding the code to do the FLR?
> 3. are you using uio_pci_generic or vfio-pci in your environment?
> 4. do you see any change in behavior if you call spdk_nvme_ctrlr_reset() immediately after doing the FLR or NSSR?

answer your question :
1.We modify spdk hello world example to do different reset test.
2.We do the FLR/NSSR after spdk_nvme_probe process completed.
3.uio_pci_generic
4.We have tried to call spdk_nvme_ctrlr_reset() immediately after doing the FLR or NSSR, but still occurred error.

We refer to linux driver that will rescan the device after doing reset, I think our SSD drive occurred
drop is because we didn't do rescan, If this is the case how do I do rescan on SPDK?

**Comment by ryderhsu0129** [comment]
We tried to re-call spdk_nvme_probe() to rescan SSD drive, but still occurred drive drop and get error message :

> nvme_ctrlr.c: 735:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
> nvme_pcie.c: 484:nvme_pcie_ctrlr_map_cmb: *ERROR*: get registers failed
> nvme_pcie.c: 856:nvme_pcie_ctrlr_construct: *ERROR*: get_cap() failed
> nvme.c: 464:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:02:00.0
> EAL: Requested device 0000:02:00.0 cannot be used
> EAL: Unknown driver type for 3d208930:03:56.0

**Comment by changpe1** [comment]
@ryderhsu0129 Did you try to call PCI rescan after doing NSSR, I'm wondering the SPDK hotplug monitor is triggered after NSSR.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 Did you try to call PCI rescan after doing NSSR, I'm wondering the SPDK hotplug monitor is triggered after NSSR.

hi @changpe1 
thanks for your reply.

You mentioned PCI rescan is to call spdk_nvme_probe()? If so we have tried to do it.
we don't know that re-call spdk_nvme_probe() whether is right time after doing FLR/NSSR, 
do you have suggestion about re-scan PCI procedure? such as when to call a function or call
which function.

**Comment by changpe1** [comment]
@ryderhsu0129 After NSSR, can you still see the PCI drive via lspci command?  You mentioned that the kernel driver can work with your requirement, I'm wondering the uio_pci_generic driver didn't have such steps, so you can try to unbind the NVMe drive from uio_pci_generic driver and bind it again to see any difference.

**Comment by ryderhsu0129** [comment]
@changpe1 

We still can see PCI drive via lspci command after NSSR, but can't see it on /dev/nvme*,
so we can't access SSD drive through SPDK application.

we unbind the NVMe drive from uio_pci_generic driver and do a hot reset via setpci command to config bridge control register,  PCI drive also occurred drop. 
and then we issue "echo 1 > /sys/bus/pci/devices/$PORT/dev_rescan", the PCI drive will appear again. but this command  is invalid after we do a FLR/NSSR on SPDK caused drive drop, 
we still can't see PCI drive on /dev/nvme*.

**Comment by ryderhsu0129** [comment]
We check the implementation method of FLR/NSSR on linux pci driver, 
they only write specific bit into corresponding register and no other operations.
for example, FLR is just to write 1 to bit 15 of PCIe device control register.
so we should no need to do rescan PCI devices.

We write specific bit into FLR/NSSR corresponding register and didn't get the error code on write operation. but the error message follows immediately :

> nvme_ctrlr.c: 735:nvme_ctrlr_shutdown: ERROR: get_cc() failed
> nvme_pcie.c: 573:nvme_pcie_ctrlr_unmap_cmb: ERROR: get_cmbloc() failed
> nvme_pcie.c: 680:nvme_pcie_ctrlr_free_bars: ERROR: nvme_ctrlr_unmap_cmb failed with error code -5

we don't know why the nvme_ctrlr_shutdown() is be call after sending the FLR/NSSR command,
and then SSD drive drop occurred.

**Comment by changpe1** [comment]
> We check the implementation method of FLR/NSSR on linux pci driver,
> they only write specific bit into corresponding register and no other operations.
> for example, FLR is just to write 1 to bit 15 of PCIe device control register.
> so we should no need to do rescan PCI devices.
> 
> We write specific bit into FLR/NSSR corresponding register and didn't get the error code on write operation. but the error message follows immediately :
> 
> > nvme_ctrlr.c: 735:nvme_ctrlr_shutdown: ERROR: get_cc() failed
> > nvme_pcie.c: 573:nvme_pcie_ctrlr_unmap_cmb: ERROR: get_cmbloc() failed
> > nvme_pcie.c: 680:nvme_pcie_ctrlr_free_bars: ERROR: nvme_ctrlr_unmap_cmb failed with error code -5
> 
> we don't know why the nvme_ctrlr_shutdown() is be call after sending the FLR/NSSR command,
> and then SSD drive drop occurred.

That's why I asked do you see the SPDK hotplug NVMe monitor work or not for this case, it will monitor uio_pci_generic uevents.

**Comment by ryderhsu0129** [comment]
> > We check the implementation method of FLR/NSSR on linux pci driver,
> > they only write specific bit into corresponding register and no other operations.
> > for example, FLR is just to write 1 to bit 15 of PCIe device control register.
> > so we should no need to do rescan PCI devices.
> > We write specific bit into FLR/NSSR corresponding register and didn't get the error code on write operation. but the error message follows immediately :
> > > nvme_ctrlr.c: 735:nvme_ctrlr_shutdown: ERROR: get_cc() failed
> > > nvme_pcie.c: 573:nvme_pcie_ctrlr_unmap_cmb: ERROR: get_cmbloc() failed
> > > nvme_pcie.c: 680:nvme_pcie_ctrlr_free_bars: ERROR: nvme_ctrlr_unmap_cmb failed with error code -5
> > 
> > 
> > we don't know why the nvme_ctrlr_shutdown() is be call after sending the FLR/NSSR command,
> > and then SSD drive drop occurred.
> 
> That's why I asked do you see the SPDK hotplug NVMe monitor work or not for this case, it will monitor uio_pci_generic uevents.

so the occurrence of error message(nvme_ctrlr_shutdown() is be called) is because SPDK hotplug NVMe monitor caused?If so how do we avoid it?

**Comment by ryderhsu0129** [comment]
We bind the NVMe drive to uio_pci_generic driver,
and then run hot reset procedure via shell command lines as follow,
the reset procedure is complete and SSD drive doesn't drop. 

but we run SPDK application like hello world example and inserted the same shell command lines,
the reset procedure is also complete but the SSD drive drop occurred immediately,
and error message is same as above attached,
how can we avoid this issue? please help to clarify it. thanks!

```
echo -e "\nRemoving $DEV"

CMD="echo 1 | sudo tee /sys/bus/pci/devices/$DEV/remove"
printf "> $CMD\n"
eval $CMD

echo -e "\nPerforming hot reset of port $PORT"

CMD="setpci -s $PORT BRIDGE_CONTROL"
printf "> $CMD\n"
BR_CTRL=$(eval $CMD)

echo "Bridge control: $BR_CTRL"

CMD="sudo setpci -s $PORT BRIDGE_CONTROL=$(printf "%04x" $((0x${BR_CTRL} | 0x40)))"
printf "> $CMD\n"
eval $CMD
sleep 0.01
CMD="sudo setpci -s $PORT BRIDGE_CONTROL=$BR_CTRL"
printf "> $CMD\n"
eval $CMD
sleep 0.5

echo -e "\nRescanning bus"

CMD="echo 1 | sudo tee /sys/bus/pci/devices/$PORT/rescan"
printf "> $CMD\n"
eval $CMD
```

**Comment by jimharris** [comment]
> We bind the NVMe drive to uio_pci_generic driver,
> and then run hot reset procedure via shell command lines as follow,
> the reset procedure is complete and SSD drive doesn't drop.

Hi @ryderhsu0129,

In this case, can you share how you confirm SSD drive doesn't drop?  Do you mean that you can still see the NVMe device in sysfs directory?

> 
> but we run SPDK application like hello world example and inserted the same shell command lines,
> the reset procedure is also complete but the SSD drive drop occurred immediately,
> and error message is same as above attached,
> how can we avoid this issue? please help to clarify it. thanks!

This looks like a different test than the original reported issue against FLR.  Doesn't echo 1 to devices/$DEV/remove simulate a PCI hot removal?  If so, then you would need to reprobe the device in your application.

> 
> ```
> echo -e "\nRemoving $DEV"
> 
> CMD="echo 1 | sudo tee /sys/bus/pci/devices/$DEV/remove"
> printf "> $CMD\n"
> eval $CMD
> 
> echo -e "\nPerforming hot reset of port $PORT"
> 
> CMD="setpci -s $PORT BRIDGE_CONTROL"
> printf "> $CMD\n"
> BR_CTRL=$(eval $CMD)
> 
> echo "Bridge control: $BR_CTRL"
> 
> CMD="sudo setpci -s $PORT BRIDGE_CONTROL=$(printf "%04x" $((0x${BR_CTRL} | 0x40)))"
> printf "> $CMD\n"
> eval $CMD
> sleep 0.01
> CMD="sudo setpci -s $PORT BRIDGE_CONTROL=$BR_CTRL"
> printf "> $CMD\n"
> eval $CMD
> sleep 0.5
> 
> echo -e "\nRescanning bus"
> 
> CMD="echo 1 | sudo tee /sys/bus/pci/devices/$PORT/rescan"
> printf "> $CMD\n"
> eval $CMD
> ```

**Comment by ryderhsu0129** [comment]
> > We bind the NVMe drive to uio_pci_generic driver,
> > and then run hot reset procedure via shell command lines as follow,
> > the reset procedure is complete and SSD drive doesn't drop.
> 
> Hi @ryderhsu0129,
> 

> In this case, can you share how you confirm SSD drive doesn't drop? Do you mean that you can still see the NVMe device in sysfs directory?

Hi @jimharris 
We run the original hello_world example successful, so SSD drive shouldn't drop. 
the error message will show the controller not found if SSD drive already dropped.
> 
> > but we run SPDK application like hello world example and inserted the same shell command lines,
> > the reset procedure is also complete but the SSD drive drop occurred immediately,
> > and error message is same as above attached,
> > how can we avoid this issue? please help to clarify it. thanks!
> 
> This looks like a different test than the original reported issue against FLR. Doesn't echo 1 to devices/$DEV/remove simulate a PCI hot removal? If so, then you would need to reprobe the device in your application.

the shell script simulate a hot reset procedure, we already confirm it's work by SSD firmware log.
SSD drive can be reprobe via last step "echo 1 >  /sys/bus/pci/devices/$PORT/rescan"

if we run script directly after binding uio_pci_generic driver, the SSD drive doesn't drop.
however, when we run same command lines on SPDK application, 
the hot reset procedure is complete but drive drop occurred immediately.
we also have tried to re-call spdk_nvme_probe() to reprobe drive but failed.

so we don't understand what mechanism on SPDK makes the result different(just like FLR/NSSR).
Do you have any suggestion for this issue?
thanks!
 
> 
> > ```
> > echo -e "\nRemoving $DEV"
> > 
> > CMD="echo 1 | sudo tee /sys/bus/pci/devices/$DEV/remove"
> > printf "> $CMD\n"
> > eval $CMD
> > 
> > echo -e "\nPerforming hot reset of port $PORT"
> > 
> > CMD="setpci -s $PORT BRIDGE_CONTROL"
> > printf "> $CMD\n"
> > BR_CTRL=$(eval $CMD)
> > 
> > echo "Bridge control: $BR_CTRL"
> > 
> > CMD="sudo setpci -s $PORT BRIDGE_CONTROL=$(printf "%04x" $((0x${BR_CTRL} | 0x40)))"
> > printf "> $CMD\n"
> > eval $CMD
> > sleep 0.01
> > CMD="sudo setpci -s $PORT BRIDGE_CONTROL=$BR_CTRL"
> > printf "> $CMD\n"
> > eval $CMD
> > sleep 0.5
> > 
> > echo -e "\nRescanning bus"
> > 
> > CMD="echo 1 | sudo tee /sys/bus/pci/devices/$PORT/rescan"
> > printf "> $CMD\n"
> > eval $CMD
> > ```

**Comment by changpe1** [comment]
@ryderhsu0129 I believe I get your issue now, the reason is that the hotplug monitor is disabled by default(which I think it's enabled by default previously).

Here is my steps:
1) app/nvmf_tgt/nvmf_tgt -L nvme
2) $rpc_py bdev_nvme_set_hotplug -e
3) $rpc_py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a b2:00.0
4) echo 1 >/sys/bus/pci/devices/0000:b2:00.0/remove
You can find that the controller is detached from SPDK after this action.
5) echo 1 >/sys/bus/pci/rescan
6) scripts/setup.sh
Then the detached the controller is adding back now.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 I believe I get your issue now, the reason is that the hotplug monitor is disabled by default(which I think it's enabled by default previously).
> 
> Here is my steps:
> 
> 1. app/nvmf_tgt/nvmf_tgt -L nvme
> 2. $rpc_py bdev_nvme_set_hotplug -e
> 3. $rpc_py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a b2:00.0
> 4. echo 1 >/sys/bus/pci/devices/0000:b2:00.0/remove
>    You can find that the controller is detached from SPDK after this action.
> 5. echo 1 >/sys/bus/pci/rescan
> 6. scripts/setup.sh
>    Then the detached the controller is adding back now.

@changpe1 
thanks for your reply.

so it seems the key step is to enable hotplug monitor, how should we open it on our application?
we inserted different reset test in nvme hello_world example,
we expect the controller can be add back after doing any reset.

**Comment by changpe1** [comment]
> > @ryderhsu0129 I believe I get your issue now, the reason is that the hotplug monitor is disabled by default(which I think it's enabled by default previously).
> > Here is my steps:
> > 
> > 1. app/nvmf_tgt/nvmf_tgt -L nvme
> > 2. $rpc_py bdev_nvme_set_hotplug -e
> > 3. $rpc_py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a b2:00.0
> > 4. echo 1 >/sys/bus/pci/devices/0000:b2:00.0/remove
> >    You can find that the controller is detached from SPDK after this action.
> > 5. echo 1 >/sys/bus/pci/rescan
> > 6. scripts/setup.sh
> >    Then the detached the controller is adding back now.
> 
> @changpe1
> thanks for your reply.
> 
> so it seems the key step is to enable hotplug monitor, how should we open it on our application?
> we inserted different reset test in nvme hello_world example,
> we expect the controller can be add back after doing any reset.

You can call spdk_nvme_probe() every a few microseconds, e.g. 1000 us to trigger the hotplug feature, or take modules/bdev/nvme/bdev_nvme.c bdev_nvme_hotplug() as an example.

**Comment by ryderhsu0129** [comment]
> > > @ryderhsu0129 I believe I get your issue now, the reason is that the hotplug monitor is disabled by default(which I think it's enabled by default previously).
> > > Here is my steps:
> > > 
> > > 1. app/nvmf_tgt/nvmf_tgt -L nvme
> > > 2. $rpc_py bdev_nvme_set_hotplug -e
> > > 3. $rpc_py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a b2:00.0
> > > 4. echo 1 >/sys/bus/pci/devices/0000:b2:00.0/remove
> > >    You can find that the controller is detached from SPDK after this action.
> > > 5. echo 1 >/sys/bus/pci/rescan
> > > 6. scripts/setup.sh
> > >    Then the detached the controller is adding back now.
> > 
> > 
> > @changpe1
> > thanks for your reply.
> > so it seems the key step is to enable hotplug monitor, how should we open it on our application?
> > we inserted different reset test in nvme hello_world example,
> > we expect the controller can be add back after doing any reset.
> 
> You can call spdk_nvme_probe() every a few microseconds, e.g. 1000 us to trigger the hotplug feature, or take modules/bdev/nvme/bdev_nvme.c bdev_nvme_hotplug() as an example.

@changpe1 

We did some experiments, and the updated results are as follows:

1. we did hot reset (attached script) without doing reprobe to trigger hotplug feature,
we found that driver will be automatically switched back to linux nvme and SSD drive doesn't drop.
Do you know why the driver switching happened?

2. we did FLR/NSSR(first post attached) with doing reprobe to trigger hotplug feature,
reprobe executed successfully(spdk_nvme_probe return 0) but SSD drive drop occurred,
even we switch back to linux nvme driver.

**Comment by changpe1** [comment]
From your description, I think the behavior is expected from my side, the SPDK application will not add the detached drive back automatically. For FLR case, I think there is a remove uevent is captured by SPDK, so SPDK will detach the drive first and then add it back later, what's your requirement? Is a controller reset can meet your requirement if you don't want a drive drop ?

**Comment by ryderhsu0129** [comment]
> From your description, I think the behavior is expected from my side, the SPDK application will not add the detached drive back automatically. For FLR case, I think there is a remove uevent is captured by SPDK, so SPDK will detach the drive first and then add it back later, what's your requirement? Is a controller reset can meet your requirement if you don't want a drive drop ?

@changpe1 

We hope the drive doesn't drop after doing various reset, so that we can continue to do other operations to drive, we have tried to do controller reset and it's work, but it seems FLR/NSSR will happen drive drop.
thanks for helping to clarify.

**Comment by jimharris** [comment]
Hi @ryderhsu0129,

Is there anything more needed on this issue?  If not, we can close it.

Thanks,

Jim

**Comment by ryderhsu0129** [comment]
OK, thanks for your help.
