### ISSUE TITLE
NVMe RDMA target failed to discover

### ISSUE THREAD

**Issue by wangzhhbj** [spdk/spdk#1258]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

use SPDK+NVMeOF to do some test, and target is run ok, but when I run 'nvem discover' command, I got this error.

## Expected Behavior

discover success

## Current Behavior

#nvme discover -t rdma -a 192.168.0.90 -s 4421
Failed to write to /dev/nvme-fabrics: Connection reset by peer

my nvmf_tgt shows some errors:Cannot allocate memory
#app/nvmf_tgt/nvmf_tgt -c /home/spdk-master/rdma.conf 
Starting SPDK v20.04-pre / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid28917 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 321:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
rdma.c:2752:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.0.90 port 4421 ***

rdma.c:1075:spdk_nvmf_rdma_qpair_initialize: *ERROR*: rdma_create_qp failed: errno 12: Cannot allocate memory
rdma.c:3568:spdk_nvmf_rdma_poll_group_add: *ERROR*: Failed to initialize nvmf_rdma_qpair with qpair=0x2d55b40
nvmf_tgt.c: 253:nvmf_tgt_poll_group_add: *ERROR*: Unable to add the qpair to a poll group.

## Steps to Reproduce
nvme discover -t rdma -a 192.168.0.90 -s 4421

## my rdma.conf
[AIO]
  AIO /dev/sdc AIO0

[Transport]
  Type RDMA

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode2
  Listen RDMA 192.168.0.90:4421
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  MN SPDK_Controller2
  Namespace AIO0

## Context (Environment including OS version, SPDK version, etc.)
SPDK:v20.04-pre
DPDK:19.11.0
target's sever : CentOS Linux release 8.0.1905 (Core) 
client: CentOS Linux release 8.0.1905 (Core) 
kernel:5.5.7-1.el8.elrepo.x86_64

please help to check this issue, thanks!

**Comment by changpe1** [comment]
@wangzhhbj I think this issue is related with your environment, the error log printed in target side shows there is an error:
rdma.c:1075:spdk_nvmf_rdma_qpair_initialize: ERROR: rdma_create_qp failed: errno 12: Cannot allocate memory

it means rdma_create_qp() returns an error.  Do you still see this issue after a reboot?

**Comment by yidong0635** [comment]
@wangzhhbj following your steps , with you conf , I can discover it successfully. 
 1. what kind of NIC are you using.  real physical NIC or SoftRoCE.
 2. please search the  issue history there're some issues about this kind of can't allocate memory which may help you to check some steps.(#696)
3. you can use rpc methods create target.

**Comment by wangzhhbj** [comment]
ALL：
I have found the cause of the problem,my CPU not support UIO.
think you.
