### ISSUE TITLE
iscsi_tgt_filesystem_btrfs test failed

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1259]
`iscsi_tgt` suddenly died after ` iscsiadm`'s logout:

```
11:53:46	# iscsiadm -m node --logout
Logging out of session [sid: 2, target: iqn.2016-06.io.spdk:Target1, portal: 10.0.0.1,3260]
Logout of [sid: 2, target: iqn.2016-06.io.spdk:Target1, portal: 10.0.0.1,3260] successful.
./test/iscsi_tgt/filesystem/filesystem.sh: line 78: 53048 Killed                  "${ISCSI_APP[@]}" -m $ISCSI_TEST_CORE_MASK --wait-for-rpc
 11:54:01	# waitforiscsidevices 0
 11:54:01	# local num=0
 11:54:01	# (( i=1 ))
 11:54:01	# (( i<=20 ))
  11:54:01	# iscsiadm -m session -P 3
  11:54:01	# grep -c 'Attached scsi disk sd[a-z]*'
iscsiadm: No active sessions.
  11:54:01	# true
 11:54:01	# n=0
 11:54:01	# '[' 0 -ne 0 ']'
 11:54:01	# return 0
 11:54:01	# iscsiadm -m node --login -p 10.0.0.1:3260
iscsiadm: Could not login to [iface: default, target: iqn.2016-06.io.spdk:Target1, portal: 10.0.0.1,3260].
iscsiadm: initiator reported error (8 - connection timed out)
iscsiadm: Could not log into all portals
```

https://ci.spdk.io/results/autotest-per-patch/builds/5620/archive/iscsi-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_5620.html

**Comment by optimistyzy** [comment]
It seems related with logical volume deletion:

INFO: Removing lvol bdev
 11:56:01	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py bdev_lvol_delete lvs_0/lbd_0
request:
{
  "name": "lvs_0/lbd_0",
  "method": "bdev_lvol_delete",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -19,
  "message": "No such device"
}

Hi @tomzawadzki  can you look at this issue?  Thanks.

**Comment by tomzawadzki** [comment]
@optimistyzy It does not look related to lvols. Part that you've posted is occurring on cleanup path. Original submission from @mikeBashStuff contains the first failure.

One part I'm unsure why would be occuring from the above log is:
```
 11:53:46	# iscsiadm -m node --logout
Logging out of session [sid: 2, target: iqn.2016-06.io.spdk:Target1, portal: 10.0.0.1,3260]
Logout of [sid: 2, target: iqn.2016-06.io.spdk:Target1, portal: 10.0.0.1,3260] successful.
./test/iscsi_tgt/filesystem/filesystem.sh: line 78: 53048 Killed                  "${ISCSI_APP[@]}" -m $ISCSI_TEST_CORE_MASK --wait-for-rpc
 11:54:01	# waitforiscsidevices 0
```

**Comment by jimharris** [comment]
Bug scrub: @tomzawadzki to take a further look

**Comment by optimistyzy** [comment]
Close this Intermittent issue, since it does not happen more than 2 months. If this issue happens again, Let's reopen it.
