### ISSUE TITLE
[FreeBSD] $OSTYPE contents differs depending on the $USER

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1260]
Leaving it here just for visibility. 
```
[sys_sgci@freebsd_vm ~]$ echo $OSTYPE
freebsd11.1
[sys_sgci@freebsd_vm ~]$ sudo -i
root@freebsd_vm:~ # bash
[root@freebsd_vm ~]# echo $OSTYPE
FreeBSD

```
This may affect `./configure` depending on if it's run as a root since all the bsd-related checks look for `freebsd*` string. uname calls seem to be consistent though.

**Comment by darsto** [comment]
@jimharris is there any better way to detect if we're on freebsd?

**Comment by jimharris** [comment]
Wow - that's really weird.  I have no explanation for that (but can confirm it happens with FreeBSD 12 as well).

I'd just suggest we use uname.  That's what we use in all of our other scripts.  configure is the only one that uses OSTYPE.

@mikeBashStuff - I'm going to assign this to you - could you throw together a patch?

**Comment by mikeBashStuff** [comment]
Potential fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/1230

**Comment by mikeBashStuff** [comment]
Fix merged, closing.
