### ISSUE TITLE
unable to perform any rpc calls in  SPDK v20.04-pre

### ISSUE THREAD

**Issue by govind-rathod1987** [spdk/spdk#1263]
unable to perform any rpc calls in  SPDK v20.04-pre version.
Note: I have modified rpc.py file to use python2 
i see error for any help command as well like below:

**[root@Rhel7u6_demo_Target2 scripts]# python rpc.py --help
  File "rpc.py", line 2319
    print("{} is deprecated, use {} instead.".format(name, deprecated_aliases[name]), file=sys.stderr)
                                                                                          ^
SyntaxError: invalid syntax**

**Comment by darsto** [comment]
> I have modified rpc.py file to use python2

This is not supported and won't work. Python 2 has almost reached EOL.

**Comment by jimharris** [comment]
HI @govind-rathod1987,

SPDK does not officially support Python 2.  There was someone on the SPDK mailing list a few months ago who was also interested in using Python 2, which would require making out-of-tree changes that you would need to maintain.  But it did seem like he was able to get it to work.  You can find that mailing list thread here:

https://lists.01.org/hyperkitty/list/spdk@lists.01.org/thread/BYSIHLEA7664QLKKVFTQRZNWRIKV4FNO/

Regards,

Jim

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/1219 removes the python2 references from spdk.spec.
