### ISSUE TITLE
iscsi-autotest: FIO: No job(s) defined

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#1264]
```
 12:45:41	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/fio.py -p iscsi -i 4096 -d 1 -t randrw -r 1 -v
Device paths:
[]
No job(s) defined
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @darsto. log: https://ci.spdk.io/public_build/autotest-per-patch_5758.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_5666.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_5902.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_5966.html

**Comment by jimharris** [comment]
Bug scrub: @jimharris to investigate further.  Possible that the login has not taken full effect before fio.py runs "iscsiadm session".  But not clear why this issue would only start appearing now.

**Comment by tkulasek** [comment]
This patch should solve this problem: https://review.spdk.io/gerrit/c/spdk/spdk/+/1251

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6508.html

**Comment by jimharris** [comment]
Thanks @tkulasek.  Patch has been merged.  Most recent failure did not have the fix that was posted.  Keeping open for now, will close this time next week if we don't see any more failures.

**Comment by tomzawadzki** [comment]
Looks like no more failures were reported since merging https://review.spdk.io/gerrit/c/spdk/spdk/+/1251.
