### ISSUE TITLE
“ccache: error: Failed to create temporary file for /home/sys_sgci/.ccache/tmp/bdev_zone_.stdout: No space left on device” on vhost_autotest

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1265]

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_5797.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_5795.html

**Comment by jimharris** [comment]
Bug scrub: Both cases happened on GP15 and very closely together.  @karlatec confirms we have a cron job to monitor disk space but maybe needs to run more often.

Closing this issue since no disk space failures seen on GP15 since.
