### ISSUE TITLE
CI: NVMF fio tests failing both TCP and RDMA

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1266]
This seems to be causing fio to fail:  16:55:59	# /var/jenkins/workspace/nvmf-tcp-autotest/spdk/scripts/fio.py -p nvmf -i 4096 -d 1 -t write -r 1 -v
Could not set block device queue depths. 

See https://review.spdk.io/gerrit/c/spdk/spdk/+/1180

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_5801.html

**Comment by jimharris** [comment]
Bug scrub: Version #2 of this patch had two identical failures on two different jobs (both related to bdevperf).  Strong suspicion this may not be CI-related, but rather the patch under test.  Subsequent changes to this patch did not produce any more failures.

Closing this issue - if we happen to see a similar failing signature again, we can reopen.
