### ISSUE TITLE
SPDK internal segfault but no application core dump is created to debug

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1268]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Even though we can this null pointer access at kernel dmesg, but our application did not crash with one core dump(we surely configure the dump, other crash can create dump).

But looks like this spdk’s internal null pointer is swallowed. Could you please help send correct guy for help check? We need debug the root cause, may it impact our code logic.

Mar 04 08:41:28 xxxxxx kernel: xxxxxxx[78405]: segfault at 0 ip 00007f54ebe61e60 sp 00007f54d17f9328 error 4 in libspdk_util.so.1.0[7f54ebe5f000+c000]

## Expected Behavior

we need know the way to know the root cause of this segment fault, we are afraid of the risk that may impact our code logic.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Comphix** [comment]
To make clear, the dump of the crash (NULL pointer) is not generated as expected?

Is this easy to reproduce for the NULL pointer access and also try below setting first.

./configure --enable-debug
make clean
make
echo 'core.%p' > /proc/sys/kernel/core_pattern

**Comment by AlekseyMarchuk** [comment]
Could you clarify your scenario? Did you simply run IO or use additional operations like start/stop of subsystems/listeners under traffic?

**Comment by gwnet** [comment]
I feel our dump configuration is well. it can create dump for any other application.
[  +0.100624] a.out[115016]: segfault at 0 ip 0000000000400cb9 sp 00007ffc0fa8d320 error 4 in a.out[400000+2000]
[  +0.027640] nvmet: creating controller 40 for subsystem nqn.2014-08.org.nvmexpress.discovery for NQN 2014-08.org.nvmexpress:uuid:61be1139-894a-4425-b6e5-013bf3b37ae7.

ogden-smoke:/var/log/cores # ls
a.out.11.core.gz

===but our spdk application, kernel can catch the segfault, but no crash dump for us to analysis==
our spdk application will create more than 100 QP to connect target nvme disks, the application will run IO, read, write, and handle the discover, connect and disconnect. 
what I am curious most is that why no core dump for us to analysis. kernel report SPDK one segfault. I feel, something must be wrong there. just need more information to debug.

**Comment by mikeBashStuff** [comment]
It would be really appreciated if you provided some details regarding the version of your system (distro, kernel, etc.) and the SPDK release you are using. Additionally, as core(5) states, there's plenty of scenarios in which a core file won't be written out by the kernel, thus please make sure your system environment adheres to all the requirements needed. 

The less common scenarios that I can think of and which might have caused this issue described below:
```
# No core with improper RLIMIT_CORE setup
root@debianMB[SPDK]:~/spdk_repo/spdk# echo 0 >/proc/sys/kernel/core_uses_pid
root@debianMB[SPDK]:~/spdk_repo/spdk# echo '%e.%u.MY_CORE' >/proc/sys/kernel/core_pattern
root@debianMB[SPDK]:~/spdk_repo/spdk#
# Checking RLIMIT_CORE and RLIMIT_FSIZE
root@debianMB[SPDK]:/spdk_project/spdk_repo/spdk# grep "file size" /proc/self/limits
Max file size             unlimited            unlimited            bytes
Max core file size        0                    unlimited            bytes # <- Core dump won't be generated if app doesn't change this particular ulimit on its own (by default it should).
# run the app, but tell it to not tweak the RLIMIT_CORE
root@debianMB[SPDK]:~/spdk_repo/spdk# ./app/iscsi_tgt/iscsi_tgt -d &>/dev/null &
[1] 2526224
root@debianMB[SPDK]:~/spdk_repo/spdk# readlink -f /proc/$(jobs -p)/cwd
/root/spdk_repo/spdk
root@debianMB[SPDK]:~/spdk_repo/spdk# kill -SEGV %
root@debianMB[SPDK]:~/spdk_repo/spdk#
[1]+  Segmentation fault      ./app/iscsi_tgt/iscsi_tgt -d &> /dev/null
root@debianMB[SPDK]:~/spdk_repo/spdk# find . -name '*MY_CORE'
# no core was generated
root@debianMB[SPDK]:~/spdk_repo/spdk#
This time, let the app to update the  RLIMIT_CORE
root@debianMB[SPDK]:~/spdk_repo/spdk# ./app/iscsi_tgt/iscsi_tgt  &>/dev/null &
[1] 2526262
root@debianMB[SPDK]:~/spdk_repo/spdk#
root@debianMB[SPDK]:~/spdk_repo/spdk# kill -SEGV %
root@debianMB[SPDK]:~/spdk_repo/spdk#
[1]+  Segmentation fault      (core dumped) ./app/iscsi_tgt/iscsi_tgt &> /dev/null
root@debianMB[SPDK]:~/spdk_repo/spdk# find . -name '*MY_CORE'
./reactor_0.0.MY_CORE
root@debianMB[SPDK]:~/spdk_repo/spdk#

# No core with suid exec not being dumpable
 root@debianMB[SPDK]:~/spdk_repo/spdk# echo 0 >/proc/sys/fs/suid_dumpable
root@debianMB[SPDK]:~/spdk_repo/spdk# setuidgid michal ./app/iscsi_tgt/iscsi_tgt &>/dev/null &
[1] 2527458
root@debianMB[SPDK]:~/spdk_repo/spdk# kill -SEGV %
root@debianMB[SPDK]:~/spdk_repo/spdk#
[1]+  Segmentation fault      setuidgid michal ./app/iscsi_tgt/iscsi_tgt &> /dev/null
root@debianMB[SPDK]:~/spdk_repo/spdk# find . -name '*MY_CORE'
./reactor_0.0.MY_CORE # <- no new core was generated
root@debianMB[SPDK]:~/spdk_repo/spdk#
# enable suid cores
root@debianMB[SPDK]:~/spdk_repo/spdk# echo 1 >/proc/sys/fs/suid_dumpable
root@debianMB[SPDK]:~/spdk_repo/spdk# setuidgid michal ./app/iscsi_tgt/iscsi_tgt &>/dev/null &
[1] 2527830
root@debianMB[SPDK]:~/spdk_repo/spdk# kill -SEGV %
root@debianMB[SPDK]:~/spdk_repo/spdk#
[1]+  Segmentation fault      (core dumped) setuidgid michal ./app/iscsi_tgt/iscsi_tgt &> /dev/null
root@debianMB[SPDK]:~/spdk_repo/spdk# find . -name '*MY_CORE'
./reactor_0.0.MY_CORE
./reactor_0.1000.MY_CORE # <- and now there it is
root@debianMB[SPDK]:~/spdk_repo/spdk#
```

With all that in mind,  to move this forward we really need to know more details about your testing environment .

**Comment by gwnet** [comment]
Thank you so much. last week, we got one dump successfully, it is our app issue. could you please keep this open for a while, just monitoring if there is new issue from our side?

**Comment by mikeBashStuff** [comment]
If there's no new updates I think it should be ok to proceed with closing this issue.

**Comment by tomzawadzki** [comment]
This looks to be resolved. @gwnet if there is anything else to be done here, please feel free to re-open.
