### ISSUE TITLE
Hung up when we try to create FTL bdev on non 4K block size zone bdev to bdev_ftl_create RPC

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1269]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

When we create FTL bdev on zone block bdev according to https://spdk.io/doc/ftl.html , if we pass non 4K block size zone bdev, SPDK application hungup because spdk_io_device_unregister() is called to not registered IO device.

## Expected Behavior

bdev_ftl_create RPC should fail immediately.

## Current Behavior

RPC client gets timeout after
```
ftl_init.c:1286:ftl_dev_init_base_bdev: *ERROR*: Unsupported block size (512)
ftl_init.c:1434:spdk_ftl_dev_init: *ERROR*: Unsupported underlying device
thread.c:1168:spdk_io_device_unregister: *ERROR*: io_device 0x7f0d7561f800 not found
```

## Possible Solution

https://review.spdk.io/gerrit/c/spdk/spdk/+/1194

## Steps to Reproduce

https://spdk.io/doc/ftl.html#ftl_zone_block but non 4K block size zone dev.

## Context (Environment including OS version, SPDK version, etc.)

Latest SPDK master.

**Comment by tomzawadzki** [comment]
@shuhei-matsumoto The fix you posted seems to get positive response from @wmalikow and @ksztyber.
If it fixes the issue, please close this issue after patch gets merged. Thank you for submitting the patch !

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1194 is now merged.
