### ISSUE TITLE
"Requested device XXX cannot be used" warning in device detach procedure may be misleading

### ISSUE THREAD

**Issue by freemandealer** [spdk/spdk#127]
I am a new user to spdk, I trapped in some confusing warnings recently. This one is about "Requested device XXX cannot be used" printed at the end of spdk/example/nvm/perf/perf execution. That seems to tell me: hey, your device doesn't work with spdk... yes, even though you've got the perf results, but you'd better not trust it!

After investigating the source code, I understand the last print of this warning appears when spdk releases resources after all work is done. So I suppose it should say something like "We finished using this device" instead. What do you think?

**Comment by optimistyzy** [comment]
Hi @freemandealer,  this is the warning message printed in DPDK, but it will not influence the real usage. We will have patches to fix this misleading message later.

**Comment by freemandealer** [comment]
Created a thread on the mailing list, see more comments by following the thread: https://lists.01.org/pipermail/spdk/2017-March/000384.html

**Comment by dverkamp-intel** [comment]
We have merged a patch which disables the DPDK call that causes this warning - see commit b7349216b909e071459f2196a7bad5b41b70b996.  The side effect is that re-probing a device without a specific PCI address after detaching from it is not possible (this will need a fix from the DPDK side to add an API to remove a driver without dropping the corresponding PCI device from the list).
