### ISSUE TITLE
SPDK NVMf initiator fails to connect if target does not support Get Features "Number of Queues"

### ISSUE THREAD

**Issue by EugeneKochetov** [spdk/spdk#1270]
Some targets do not support Get Features "Number of Queues" command and SPDK fails to connect to such targets. Linux kernel initiator connects to the same target without any issues.

NVMe specification in ch.7.6 "Controller Initialization" suggests to use only Set Features command and says nothing about Get Features. So, Get Feature "Number of Queues" step in SPDK controller initialization seems to be excessive. We have all required information after Set Features "Number of Queues" step.

## Expected Behavior

SPDK connects successfully to target that does not support Get Features "Number of Queues" command.

## Current Behavior

SPDK controller initialization fails on Get Features "Number of Queues" step

## Possible Solution

Remove Get Features "Number of Queues" step from controller initialization state machine and get all required information from response to Set Features "Number of Queues" command.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.01

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_6288.html

**Comment by AlekseyMarchuk** [comment]
> Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_6288.html

It should be #1248
