### ISSUE TITLE
when running containerized SPDK target (running as the primary process,), secondary process fails.

### ISSUE THREAD

**Issue by dacrespi** [spdk/spdk#1274]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Running spdk v20.01 in a container.  This is started as the primary process with shmID:42.  When attempting to use the identify app (also shmID 42) to check a device that has been added to spdk, the identify command fails.
identify -i 42 -r 'traddr:0000:1a:00.0' -p 4 -d 16384
Starting SPDK v20.01 git sha1 5ffffe9d9 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: identify -c 0x10 -n 1 -m 16384 --master-lcore=4 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk42 --proc-type=auto ]
EAL: Failed to hotplug add device
nvme.c: 606:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 726:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed

The syslog is mostly the same, but had the one additional line that doesn't show up on the screen, that the device isn't found.  This device has been added to the target.
Syslog Entries:
Mar 10 18:40:07 minnie identify[8654]: nvme.c: 606:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
Mar 10 18:40:07 minnie identify[8654]: nvme.c: 726:spdk_nvme_connect: *ERROR*: Create probe context failed
Mar 10 18:40:07 minnie f5f5f5365ced[3187]: EAL: Cannot find device (0000:1a:00.0)
Mar 10 18:40:07 minnie f5f5f5365ced[3187]: EAL: Failed to hotplug add device on primary

## Expected Behavior

secondary process should be able to run to completion when using containers.  

## Current Behavior

should work.  

## Possible Solution

Not quite sure yet... but it looks like something gets set in the container that isn't getting mapped to the host. I did try this on a bare-metal configuration and it worked okay.  Before I added the mapping of /var/tmp/dpdk/ to the container, the identify app would fully execute, but the results of running the app would destroy the target.  It became unresponsive and the container had to be killed and restarted in order to move forward again.  Now that /var/tmp/dpdk is mapped, the error above occurs and the target remains fine and happy.

## Steps to Reproduce

1.  Start the target app in a container. (/spdk/app/nvmf_tgt/nvmf_tgt -s 16384 -m 0xF0F0F0F0 -i 42 -g -c nvmf.conf).  

Note: that to get this far, a few other things have to be included when starting the container.
I found that I had to add /var/tmp in order to share the sock.  /dev so a few things, 
including hugepages and pci devices, could be shared.  And that /var/run/dpdk/ was 
needed for both processes (primary & secondary) to see the shmID and to share.

Docker config:
docker run  -d  \
        --net=host \
        --privileged \
        --ipc=shareable \
        --shm-size="32g" \
        --cap-add=IPC_LOCK \
        --device=/dev/infiniband/uverbs0 \
        --device=/dev/infiniband/rdma_cm  \
        -v /dev:/dev \
        -v /var/tmp:/var/tmp \
        -v /var/run/dpdk:/var/run/dpdk \
         $spdkToRun
    
2. configure the target with pci ssd devices

3. run the identify app. (identify -i 42 -r 'traddr:0000:1a:00.0' -p 4 -d 16384) either inside the container or host (same error occurs).  Using your own pci address, core and shmID.

## Context (Environment including OS version, SPDK version, etc.)
Container: Ubuntu v19.10, SPDK v20.01
Host: Ubuntu v18.04 LTS

**Comment by peluse** [comment]
Just to confirm that your container setup is working, were you able to run an SPDK app in a single container without issue?

**Comment by dacrespi** [comment]
Absolutely, been doing that for quite some time now.

Regards,
      David

(C) 714-476-2692

________________________________

**Comment by jimharris** [comment]
@peluse - would you have a chance to try to reproduce this?  if you can, we should be able to get to the bottom of this pretty quickly I think

**Comment by dong-liuliu** [comment]
hi, @dacrespi 
Previously, Paul did a great start for SPDK community on running SPDK inside container. Here is the SPDK in container document [link](https://spdk.io/doc/containers.html#spdk_in_docker).

Following Paul documented steps, I verified your situation but using `spdk_tgt` with two NVMe disk. `identify` run well on host.
Here is my docker cmd following your case:
```
docker run --privileged -d -v /dev/hugepages/:/dev/hugepages/ -v /dev/shm/:/dev/shm/  -v /var/run/dpdk:/var/run/dpdk  <image-tage and spdk-tgt cmd>
```

So can you have a try on spdk-tgt with this docker cmd on your platform?

**Comment by peluse** [comment]
@jimharris @dong-liuliu I'll get on it this week and let you know how it goes...

**Comment by dacrespi** [comment]
Hi, and thanks for the email.
I’ve seen the link you’ve send a number of times, it’s really not complete for what I’m doing.
The docker command you’ve shared is nearly identical to mine, with mine being just a bit more
open.  Have you tried using the secondary process successfully with containers?

Regards,
      David

**Comment by dacrespi** [comment]
@dong-liuliu just wondering how you do the setup of yours, with regards to the setup.sh command.  Are you doing it prior to starting the container or in the container?

**Comment by peluse** [comment]
@dong-liuliu I'm sure you've seen this but just in case https://spdk.io/doc/containers.html 

We've done very little work with containers but I tried both ways and they both worked, I'm not sure if it matters at some other level though.

**Comment by dacrespi** [comment]
I wouldn't think it would matter either, but I did have to open my volume to /dev rather than /dev/hugepages.

**Comment by dacrespi** [comment]
I don't know if it matters, but just thinking about what dong-liuliu said, he added two drives to the target.  I have 17 of 32 drives added to this target, and it's set up with 43 subsystems.  It could, perhaps, be something with size?  I'm going to down size it and see if it makes any difference.

**Comment by peluse** [comment]
@dacrespi that's interesting, did you get some sort of en error with -v /dev/hugepages? That might be a clue,.  @dong-liuliu are you saying that you reproduced and didn't have an issue?

**Comment by dacrespi** [comment]
well, it's been almost a year ago I did all that, but my memory was that without mapping /dev, the setup.sh could find the pci drives to move them... all the drives are in /dev.  If you think it's important, I can go back and change the volume mapping and retry.

**Comment by dacrespi** [comment]
well, I'm not sure what's going on that's different, but it all appears to be working this morning!??  Everything started new this morning, but kind of how each day starts.  I'm going to do a bit more experimenting to be sure, but if I can't determine what's different between today and all previous days, I'll go ahead and close this.

**Comment by dacrespi** [comment]
I don't have an explanation why it's working this morning :(  The only think I can think of is that I rebuilt everything yesterday while debugging with Jim.  I copied over the identify command and was using that one after that... but it was still failing then.  The version that was given were the same however.  So I'll close this now, and revisit it if it's rears its ugly head again.  Sorry for the fire drill!

**Comment by dong-liuliu** [comment]
>  @dong-liuliu are you saying that you reproduced and didn't have an issue?
I reproduced by running spdk_tgt in container, and run identify in host, and there is no issue.

**Comment by dacrespi** [comment]
yep that's what I was doing.  I've left the target sitting for a few hour can came back to it.  Now it's failing again.  I get this error (below) now, and sometimes the data is returned, and sometimes not.
I've not changed anything in the container.

sudo ./identify -r traddr:0000:1b:00.0 -p 4 -i 42
Starting SPDK v20.01 git sha1 5ffffe9d9 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: identify -c 0x10 -n 1 -m 0 --master-lcore=4 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk42 --proc-type=auto ]
nvme_ctrlr.c:2159:nvme_ctrlr_remove_inactive_proc: *ERROR*: process 24951 terminated unexpected
=====================================================
NVMe Controller at 0000:1b:00.0 [144d:a808]
=====================================================
Controller Capabilities/Features
================================
Vendor ID:                             144d
Subsystem Vendor ID:                   144d
Serial Number:                         S40PNE0K901203
Model Number:                          SAMSUNG MZ4LB3T8HALS-00003
Firmware Version:                      EGA80007
Recommended Arb Burst:                 2
IEEE OUI Identifier:                   38 25 00
Multi-path I/O
  May have multiple subsystem ports:   No
  May be connected to multiple hosts:  No
  Associated with SR-IOV VF:           No
Max Data Transfer Size:                2097152
Max Number of Namespaces:              1
Error Recovery Timeout:                Unlimited
NVMe Specification Version (VS):       1.2
NVMe Specification Version (Identify): 1.2
Maximum Queue Entries:                 16384
Contiguous Queues Required:            Yes
Arbitration Mechanisms Supported
  Weighted Round Robin:                Supported
  Vendor Specific:                     Not Supported
Reset Timeout:                         20000 ms
Doorbell Stride:                       4 bytes
NVM Subsystem Reset:                   Supported
Command Sets Supported
  NVM Command Set:                     Supported
Boot Partition:                        Not Supported
Memory Page Size Minimum:              4096 bytes
Memory Page Size Maximum:              4096 bytes
Optional Asynchronous Events Supported
  Namespace Attribute Notices:         Not Supported
  Firmware Activation Notices:         Not Supported
128-bit Host Identifier:               Not Supported

Controller Memory Buffer Support
================================
Supported:                             No

Admin Command Set Attributes
============================
Security Send/Receive:                 Supported
Format NVM:                            Supported
Firmware Activate/Download:            Supported
Namespace Management:                  Supported
Device Self-Test:                      Not Supported
Directives:                            Not Supported
NVMe-MI:                               Not Supported
Virtualization Management:             Not Supported
Doorbell Buffer Config:                Not Supported
Abort Command Limit:                   8
Async Event Request Limit:             4
Number of Firmware Slots:              3
Firmware Slot 1 Read-Only:             Yes
Firmware Update Granularity:           No Information Provided
Per-Namespace SMART Log:               Yes
Command Effects Log Page:              Supported
Get Log Page Extended Data:            Not Supported
Telemetry Log Pages:                   Not Supported
Error Log Page Entries Supported:      64
Keep Alive:                            Not Supported

NVM Command Set Attributes
==========================
Submission Queue Entry Size
  Max:                       64
  Min:                       64
Completion Queue Entry Size
  Max:                       16
  Min:                       16
Number of Namespaces:        1
Compare Command:             Supported
Write Uncorrectable Command: Supported
Dataset Management Command:  Supported
Write Zeroes Command:        Supported
Set Features Save Field:     Supported
Reservations:                Not Supported
Timestamp:                   Not Supported
Volatile Write Cache:        Not Present
Atomic Write Unit (Normal):  1024
Atomic Write Unit (PFail):   8
Atomic Compare & Write Unit: 1
Fused Compare & Write:       Not Supported
Scatter-Gather List
  SGL Command Set:           Not Supported
  SGL Keyed:                 Not Supported
  SGL Bit Bucket Descriptor: Not Supported
  SGL Metadata Pointer:      Not Supported
  Oversized SGL:             Not Supported
  SGL Metadata Address:      Not Supported
  SGL Offset:                Not Supported
  Transport SGL Data Block:  Not Supported
Replay Protected Memory Block:  Not Supported

Firmware Slot Information
=========================
Active slot:                 2
Slot 1 Firmware Revision:    EDA8100Q
Slot 2 Firmware Revision:    EGA80007

Commands Supported and Effects
==============================
Admin Commands
--------------
   Delete I/O Submission Queue (00h): Supported
   Create I/O Submission Queue (01h): Supported
                  Get Log Page (02h): Supported
   Delete I/O Completion Queue (04h): Supported
   Create I/O Completion Queue (05h): Supported
                      Identify (06h): Supported
                         Abort (08h): Supported
                  Set Features (09h): Supported
                  Get Features (0Ah): Supported
    Asynchronous Event Request (0Ch): Supported
          Namespace Management (0Dh): Supported NS-Cap-Change All-NS-Exclusive
               Firmware Commit (10h): Supported
       Firmware Image Download (11h): Supported
          Namespace Attachment (15h): Supported NS-Inventory-Change
                    Format NVM (80h): Supported LBA-Change All-NS-Exclusive
                 Security Send (81h): Supported LBA-Change All-NS-Exclusive
              Security Receive (82h): Supported Per-NS-Exclusive
I/O Commands
------------
                         Flush (00h): Supported Per-NS-Exclusive
                         Write (01h): Supported LBA-Change
                          Read (02h): Supported
           Write Uncorrectable (04h): Supported LBA-Change
                       Compare (05h): Supported
                  Write Zeroes (08h): Supported LBA-Change
            Dataset Management (09h): Supported LBA-Change Per-NS-Exclusive

Error Log
=========

Arbitration
===========
Arbitration Burst:           4
Low Priority Weight:         4
Medium Priority Weight:      4
High Priority Weight:        4

Power Management
================
Number of Power States:      1
Current Power State:         Power State #0
Power State #0:  Max Power:  13.00 W
Non-Operational Permissive Mode: Not Supported

Health Information
==================
Critical Warnings:
  Available Spare Space:     OK
  Temperature:               OK
  Device Reliability:        OK
  Read Only:                 No
  Volatile Memory Backup:    OK
Current Temperature:         307 Kelvin (34 Celsius)
Temperature Threshold:       347 Kelvin (74 Celsius)
Available Spare:             100%
Available Spare Threshold:   10%
Life Percentage Used:        0%
Data Units Read:             532213266
Data Units Written:          381177983
Host Read Commands:          54075333764
Host Write Commands:         33420010027
Controller Busy Time:        8349 minutes
Power Cycles:                320
Power On Hours:              5827 hours
Unsafe Shutdowns:            246
Unrecoverable Media Errors:  0
Lifetime Error Log Entries:  29
Warning Temperature Time:    0 minutes
Critical Temperature Time:   0 minutes
Temperature Sensor 1:        307 Kelvin (34 Celsius)
Temperature Sensor 2:        316 Kelvin (43 Celsius)
Temperature Sensor 3:        332 Kelvin (59 Celsius)

Number of Queues
================
Number of I/O Submission Queues:      32
Number of I/O Completion Queues:      32

Active Namespaces
=================
Namespace ID:1
Deallocate:                            Supported
Deallocated/Unwritten Error:           Not Supported
Deallocated Read Value:                Unknown
Deallocate in Write Zeroes:            Not Supported
Deallocated Guard Field:               0xFFFF
Flush:                                 Not Supported
Reservation:                           Not Supported
Namespace Sharing Capabilities:        Private
Size (in LBAs):                        7501476528 (7153M)
Capacity (in LBAs):                    7501476528 (7153M)
Utilization (in LBAs):                 2581484408 (2461M)
NGUID:                                 343050304B9012030025384500000001
Thin Provisioning:                     Not Supported
Per-NS Atomic Units:                   Yes
  Atomic Write Unit (Normal):          1024
  Atomic Write Unit (PFail):           8
  Atomic Boundary Size (Normal):       1023
  Atomic Boundary Size (PFail):        7
  Atomic Boundary Offset:              0
NGUID/EUI64 Never Reused:              No
Number of LBA Formats:                 2
Current LBA Format:                    LBA Format #00
LBA Format #00: Data Size:   512  Metadata Size:     0
LBA Format #01: Data Size:  4096  Metadata Size:     0

nvme_pcie.c:1166:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 36) is not found. Dropping the request.
nvme_pcie.c:1166:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 36) is not found. Dropping the request.
nvme_pcie.c:1166:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 36) is not found. Dropping the request.
nvme_pcie.c:1166:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 36) is not found. Dropping the request.
Segmentation fault

**Comment by dacrespi** [comment]
I was watching the syslog too, and notice these errors are now also showing up.  This is prior to running the identify command.
Mar 12 18:25:02 minnie 83889077068b[3187]: nvme_pcie.c:1192:nvme_pcie_qpair_complete_pending_admin_request: *ERROR*: the active process (pid 36) is not found for this controller.
Mar 12 18:25:06 minnie 83889077068b[3187]: message repeated 40 times: [ nvme_pcie.c:1192:nvme_pcie_qpair_complete_pending_admin_request: *ERROR*: the active process (pid 36) is not found for this controller.]

**Comment by dong-liuliu** [comment]
Not very sure about the real reason. But I guess maybe you met one potential issue for containerizing SPDK that I have mentioned in Slack.

**Comment by dong-liuliu** [comment]
> one potential issue for containerizing SPDK

Maybe it is PID number collision, but I'm not sure.

let me explain the PID number collision first:
If you run a primary spdk app like spdk_tgt in one container, and also run a secondary process like identify for many times in another container or host. Since the 2 containers have their own PID namespaces, so it is possible the primary app and the secondary app have a same PID number.
But spdk nvme internaly uses PID numbers as identification, then, problem appears...

**Comment by dong-liuliu** [comment]
why I'm not sure on this explanation, that, if you run `identify` app on host, then it has a very very very low possiblity that they have a same PID nubmer. Because the host already has many system processes that ocuppied small PID numbers.

**Comment by dong-liuliu** [comment]
HI, @dacrespi 

Recent weeks, I'm considering the container related SPDK requirement.
Could you tell me the main reason why you would like to run SPDK app inside container:
For easy deployment?  For easy application distribution? adapt to container/CloudNative env? or easy monitoring&operating?

**Comment by peluse** [comment]
@dong-liuliu not to get int he middle of some good questions for @dacrespi but can you clarify if you tested this exact scenario - target in one container and identify app in another? I had tried target in a container and some other box as initiator and it worked fine. I didn't try 2 containers but I'm curious about that use case @dacrespi if you can also explain that a bit more that would be great, I'm not sure I see why you'd want to do that (but I haven't thought about it a ton)?

**Comment by dacrespi** [comment]
just to be clear here, that's not what I'm currently doing.  The identify app is running on the host, and the target is in a container.  I will most likely want to also validate that scenario, as I can see it being useful, but not at this point.  
I'm seeing some weirdness with the container since moving to spdk v20.01, so I'm attempting to baseline again, to try to get some sanity back.  One of the things that I didn't notice until this morning (on reboot of the host), is that the container will no longer move the drives over to user space via the setup.sh script.  I get an error saying " No valid drivers found [vfio-pci, uio_pci_generic, igb_uio].".  I don't know what that's about, so there may be some additional things going on.  This all worked using v19.07... but at this point, I have no idea if it's spdk, dpdk or the container.  Restarting the container still causes the identify command to fail now.  I've not been able to run it without errors since yesterday morning.

**Comment by dacrespi** [comment]
a quick question (just occurred to me), are there any requirements for a particular version of the kernel with spdk v20.01?  Like above a particular version?

**Comment by dacrespi** [comment]
FYI - so it looks like the setup script is using commands that aren't in containers.  So without adding all the /sbin and /usr/sbin to the container, it can't run there.  This must have changed recently... so from now on, the setup.sh script will need to be called prior to starting the container.  This doesn't look to be related to the identify issue (so far anyway).

**Comment by dacrespi** [comment]
This morning, with the container sitting all weekend idling, running the identify app now produces the correct output.  The log shows only this output.
Mar 16 06:39:50 minnie 31de55620b7e[3216]: EAL: Failed to hotplug add device on primary
Mar 16 06:39:50 minnie 31de55620b7e[3216]: EAL: Driver cannot detach the device (0000:ba:00.0)
Mar 16 06:39:50 minnie 31de55620b7e[3216]: EAL: Failed to hotplug remove device on primary
Mar 16 06:39:50 minnie identify[17023]: EAL: Failed to hotplug remove device

puzzling!

**Comment by dacrespi** [comment]
When I left the system last night, it was running the identify command fine.  I was running FIO from a client machine, and looping on the identify command every 10 seconds.  100% success!
Comming back to the same this morning, with the container only sitting idle, the command now fails 100% of the time with this failure:
16851 Segmentation fault      sudo $home/bin/identify -r "traddr:$ssd" -p $CPUs -i $shmID > $tmpDir/$$.txt 2> /dev/null

And in my syslog:
Mar 18 07:40:03 minnie de3f253dca4f[3285]: EAL: Failed to hotplug add device on primary
Mar 18 07:40:03 minnie identify[16856]: nvme_ctrlr.c:2159:nvme_ctrlr_remove_inactive_proc: *ERROR*: process 24 terminated unexpected
Mar 18 07:40:03 minnie kernel: [56798.604898] identify[16856]: segfault at 55c0942d54e0 ip 000055c131306ee7 sp 00007ffea18d2768 error 4 in identify[55c1312e3000+f5000]
Mar 18 07:40:03 minnie de3f253dca4f[3285]: nvme_pcie.c:1192:nvme_pcie_qpair_complete_pending_admin_request: *ERROR*: the active process (pid 24) is not found for this controller.
(above lines repeated for each of the ssd's)
Mar 18 07:40:14 minnie de3f253dca4f[3285]: /targetStart.sh: line 37:    24 Segmentation fault      (core dumped) $spdk/app/nvmf_tgt/nvmf_tgt -s $NicMemory -m $NicCpu -i $ShmId -g

There must be something going on with the shared memory. Process 24 is the target process. This also, BTW, kills the container now.

**Comment by peluse** [comment]
@dacrespi checking in to see where things are at on this - sorry it seems have gone without a response for so long. It's good to tag people when you ask a question so it pops up for them.  Incidentally no there is no kernel version requirement for SPDK however if you want to run NVME-oF w/TCP you need that in your kernel but I don't think you're doing anything with that.

Anyway, let us know what's happening, if you still need help or if we should close this or what. Happy to keep trying to support your efforts though

**Comment by peluse** [comment]
@dacrespi is there anything else that you need on this or is it OK to close?
