### ISSUE TITLE
NVMF hits assert during nvmf_shutdown_tc2

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1280]
## Current Behavior

I observed this on one of my nvme_poll_group patches. I am still not 100% sure it's not related to my own patch series, but wanted to log it here just in case.

The assert is in bdevperf: nvme_transport.c:373: nvme_transport_admin_qpair_abort_aers: Assertion `transport != NULL' failed.

## Context (Environment including OS version, SPDK version, etc.)

https://ci.spdk.io/results/autotest-per-patch/builds/6513/archive/nvmf-phy-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6513.html

**Comment by yidong0635** [comment]
I hits this issue once:
#0  0x00000000004569d1 in nvme_transport_qpair_abort_reqs (qpair=0x2000477e4440, dnr=0) at nvme_transport.c:310
#1  0x0000000000000000 in ?? ()

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_10919.html

**Comment by tomzawadzki** [comment]
@Seth5141 any updates on this issue, should this be closed ?
Issue reported by @Maciej-Szwed does not look exactly like this one, so not sure of the relation.
