### ISSUE TITLE
FreeBSD built failed for can't find file nic_uio.ko 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1282]
# Issue：
https://ci.spdk.io/results/autotest-per-patch/builds/6538/archive/freebsd-autotest/build.log
 ```
03:28:15	# ./scripts/setup.sh
kldunload: can't find file nic_uio.ko
hw.nic_uio.bdfs="0:9:0"
hw.contigmem.num_buffers="8"
hw.contigmem.buffer_size="268435456"
kldload: an error occurred while loading the module. Please check dmesg(8) for more details.
  03:28:16	# trap - ERR
  03:28:16	# print_backtrace
  03:28:16	# [[ ehxBET =~ e ]]
  03:28:16	# args=("${BASH_ARGV[@]}")
  03:28:16	# local args
  03:28:16	# xtrace_disable
  03:28:16	# '[' no '!=' yes ']'
  03:28:16	# PREV_BASH_OPTS=ehxBET
  03:28:16	# [[ ehxBET == *\x* ]]
  03:28:16	# XTRACE_DISABLED=yes
  03:28:16	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/freebsd-autotest/spdk/autotest.sh:123 -> main(["/home/sys_sgci/autorun-spdk.conf"])
     ...
   118 	
   119 	timing_exit cleanup
   120 	
   121 	# set up huge pages
   122 	timing_enter afterboot
=> 123 	./scripts/setup.sh
```

**Comment by jimharris** [comment]
This seems like an issue we have after the VM has run too many tests in a row, memory becomes fragmented, and we aren't able to allocated the physically contiguous buffers any longer.

@karlatec @Seth5141 Do we reboot the FreeBSD VM between tests?  I recall us considering that option in the past but don't recall if we acted on it.  I'm also wondering if it's possible to copy /var/log/messages to the output?  That will contain any kernel messages when contigmem load fails.

**Comment by tomzawadzki** [comment]
Bug scrub: @karlatec FreeBSD should have been rebooting between builds, turns out after moving to new CI - it does not. Karol will take a look at this.
Along with adding /var/log/messages to the output.

**Comment by karlatec** [comment]
FYI: FreeBSD VMs are now set to reset after every test run. Let's wait a couple of days to see if the problem persists.
There might be some FreeBSD related issues from today because I made a mistake in the config:P

**Comment by karlatec** [comment]
No more occurrences for a couple of days. Plus I don't see any fail like that in current build history (~150 builds).
@yidong0635 @tomzawadzki Can we close the issue?

**Comment by yidong0635** [comment]
@karlatec ,@tomzawadzki , Thanks, I will close this one.
