### ISSUE TITLE
NVMF hits assert during nvmf_shutdown_tc3

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1285]
See https://ci.spdk.io/results/autotest-per-patch/builds/6603/archive/nvmf-phy-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_6603.html

**Comment by AlekseyMarchuk** [comment]
That was caused by my patch, I'll check it

**Comment by AlekseyMarchuk** [comment]
I'm sorry, that was my mistake. I completely forgot that WC will be generated for any WR in the case of error and I naively assumed that we could remove several checks. Preparing a fix for that

**Comment by AlekseyMarchuk** [comment]
I reverted part of the problematic patch https://review.spdk.io/gerrit/c/spdk/spdk/+/1334

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6695.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6693.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6696.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_6698.html

**Comment by jimharris** [comment]
Patch has been merged.  Let's give it until tomorrow before closing this issue though.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_6661.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_6773.html

**Comment by changpe1** [comment]
@mikeBashStuff Can you check the failure cases is rebased or not? thanks.

**Comment by peluse** [comment]
FYI mine passed

**Comment by Seth5141** [comment]
@AlekseyMarchuk's change has been merged, closing.

**Comment by shuhei-matsumoto** [comment]
Seth commented closing. So I push close button.
