### ISSUE TITLE
autobuild fails to remove /tmp/spdk

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1293]
https://ci.spdk.io/results/autotest-per-patch/builds/6997/archive/iscsi-autotest/build.log

```
 19:40:46	$ rm -rf /tmp/spdk
rm: cannot remove '/tmp/spdk': Operation not permitted
  19:40:46	$ trap - ERR
  19:40:46	$ print_backtrace
  19:40:46	$ [[ ehxBET =~ e ]]
  19:40:46	$ args=("${BASH_ARGV[@]}")
  19:40:46	$ local args
  19:40:46	$ xtrace_disable
  19:40:46	$ '[' '' '!=' yes ']'
  19:40:46	$ PREV_BASH_OPTS=ehxBET
  19:40:46	$ [[ ehxBET == *\x* ]]
  19:40:46	$ XTRACE_DISABLED=yes
  19:40:46	$ set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/iscsi-autotest/spdk/autobuild.sh:19 -> main(["/home/sys_sgci/autorun-spdk.conf"])
     ...
   14  	scanbuild="scan-build -o $out/scan-build-tmp --status-bugs"
   15  	
   16  	source "$1"
   17  	source "$rootdir/test/common/autotest_common.sh"
   18  	
=> 19  	rm -rf /tmp/spdk
   20  	mkdir /tmp/spdk
   21  	umask 022
   22  	cd $rootdir
   23  	
   24  	# Print some test system info out for the log
     ...

========== Backtrace end ==========
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_6997.html

**Comment by mikeBashStuff** [comment]
I haven't seen this issue since the last report. Most likely this was some hiccup caused by a solar flare, global warming or other nasty little thing that likes to suddenly tweak perm bits. To mitigate, I would suggest to use `mktemp` for the spdk's tmp workspace - that way potential issue with permissions will have a smaller chance of happening. Will try to submit something sensible to address that.

That said, this issue can be closed. New one can be submitted if this pops up again in the field.

**Comment by darsto** [comment]
Ah, this can happen if `sudo autotest.sh` fails and the machine doesn't get rebooted. Subsequently run autobuild.sh (always run without sudo) will fail to remove that file since it doesn't have permissions.

This is still a bug - but let's remove the intermittent failure label. There used to be a problem with our script for rebooting CI machines, but it's been fixed from what I remember.

**Comment by mikeBashStuff** [comment]
@darsto I may be missing something here, but `autotest.sh` doesn't touch `/tmp/spdk` in any way so how its execution affects `autobuild.sh`?

**Comment by darsto** [comment]
True. Either way this won't happen now. Thanks for the fix, closing
