### ISSUE TITLE
Missing fuse binary while running blobfs test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1298]
https://ci.spdk.io/results/autotest-per-patch/builds/7135/archive/BlobFS-autotest/build.log

This also raises an issue with a small inconsistency on how it's determined if FUSE is enabled or not. `autotest_common.sh` looks for two directories, `/usr/include/fuse3` and `/usr/local/include/fuse3`. If either of those doesn't exist it reports that FUSE is not enabled and doesn't pass `--with-fuse` to `./configure`. However, `./configure` needs two of these paths to not exist to say the fuse test won't be run. Latter is sensible, the former, not really - `autotest_common.sh` should be fine with one directory to be in place.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_7135.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_7141.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_7181.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_7204.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_7193.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_7222.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_7345.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_7384.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_7400.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_7407.html

**Comment by changpe1** [comment]
@mikeBashStuff Nice analysis, I changed the autotest_common.sh to be consistent with other places, https://review.spdk.io/gerrit/c/spdk/spdk/+/1404

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_7206.html

**Comment by mikeBashStuff** [comment]
@changpe1 Oh, I also pushed a fix for this https://review.spdk.io/gerrit/c/spdk/spdk/+/1395 - but yours already have +2 on it so let's go with that commit instead. :)

**Comment by changpe1** [comment]
> @changpe1 Oh, I also pushed a fix for this https://review.spdk.io/gerrit/c/spdk/spdk/+/1395 - but yours already have +2 on it so let's go with that commit instead. :)

My bad, I didn't notice the gerrit conflict.  Please assign the issue to yourself next time so that no body will look it again, :).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_7414.html

**Comment by dong-liuliu** [comment]
it was fixed by Changpeng and Mike.
https://review.spdk.io/gerrit/c/spdk/spdk/+/1404 and https://review.spdk.io/gerrit/c/spdk/spdk/+/1395

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_12512.html
