### ISSUE TITLE
iscsi_tgt_calsof fails on ttc_ffp_7_7_2

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1299]
Calsoft test case failed on a patch that is not related to it.

Please see for SPDK autotest.sh fail log:
https://ci.spdk.io/results/autotest-per-patch/builds/7136/archive/iscsi-autotest/build.log
Along with ttc_ffp_7_7_2:
 https://ci.spdk.io/results/autotest-per-patch/builds/7136/archive/iscsi-autotest/calsoft/tc_ffp_7_7_2.txt

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_7136.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_8050.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_9051.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9100.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_12391.html

**Comment by tomzawadzki** [comment]
Have not opened another GH issue, but similar failure occured on test `tc_ffp_7_5_1`. Please see:
https://ci.spdk.io/results/autotest-per-patch/builds/12391/archive/iscsi-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/12391/archive/iscsi-autotest/calsoft/tc_ffp_7_5_1.txt

**Comment by optimistyzy** [comment]
Close this calsoft intermittent issue since it was not reported for nearly one month. If there is same or similar issue reported again, Let's re-open it again.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_17799.html
