### ISSUE TITLE
SGL size of 512 -> failure

### ISSUE THREAD

**Issue by hlitz** [spdk/spdk#130]
My SSD uses 512B sectors but I cannot use SGLs with entries of 512B size, if I have more than 2 entries per SGL. If I use 4KB entries everything is fine. Is this a bug or known limitation

**Comment by dverkamp-intel** [comment]
This is a hardware limitation of NVMe devices that do not support native SGLs.  For NVMe 1.0 devices with only PRP list support, each entry of the PRP list must be 4 KiB aligned and 4 KiB in size (the first entry may be misaligned, and the last entry may be shorter than 4K).

You can see if your device supports the SGL feature using examples/nvme/identify - see the "Scatter-Gather List" section of the output.

**Comment by hlitz** [comment]
Can I use 4k SGLs but still do 512B sector reads or do I have to configure my device to 4K sectors as well.

**Comment by dverkamp-intel** [comment]
You can keep the device formatted with 512-byte sectors; the only requirement is that the memory regions you pass are 4K.  The specific rules are found in the NVMe specification, Memory Structures > Physical Region Page Entry and List.
