### ISSUE TITLE
It takes a long time for updating NVMe firemware 

### ISSUE THREAD

**Issue by ufo19890607** [spdk/spdk#1301]
Hi guys
We intend to upadate NVMe firmware through SPDK RPC(apply_firmware). I found that it will take about 5~10 minutes for the RPC to take effect. By contrast, it just takes 30 secs if I use nvme-cli in host environment. Is it normal?

SPDK version: v20.04-pre
host kernel version: 3.10.0-693
NVMe product: P4510
NVMe fw version: VDV10120

```
[root@kvm_9_171_47_135 /usr/local/services/AdamPlugins-1.0/host_virt_spdk]# ./scripts/rpc.py get_spdk_version
{u'fields': {u'commit': u'302f7aa', u'major': 20, u'suffix': u'-pre', u'minor': 4, u'patch': 0}, u'version': u'SPDK v20.04-pre git sha1 302f7aa'}
[root@kvm_9_171_47_135 /usr/local/services/AdamPlugins-1.0/host_virt_spdk]# ./scripts/rpc.py get_bdevs  |grep firmware_revision
          "firmware_revision": "VDV10120",
          "firmware_revision": "VDV10131",
          "firmware_revision": "VDV10131",
          "firmware_revision": "VDV10131",
[root@kvm_9_171_47_135 /usr/local/services/AdamPlugins-1.0/host_virt_spdk]# ./scripts/rpc.py apply_firmware /data/ufo/software/nvme_fw/P4510/VDV10131_VB1B0203_WFEM01A0_signed.bin  632f5018-0c5c-49b7-9aa9-aba41291c3d3-nvmen1
Timeout while waiting for response:

[root@kvm_9_171_47_135 /usr/local/services/AdamPlugins-1.0/host_virt_spdk]# ./scripts/rpc.py get_bdevs  |grep firmware_revision
          "firmware_revision": "VDV10120",
          "firmware_revision": "VDV10131",
          "firmware_revision": "VDV10131",
          "firmware_revision": "VDV10131",
..... 
5 minutes later
[root@kvm_9_171_47_135 /usr/local/services/AdamPlugins-1.0/host_virt_spdk]# ./scripts/rpc.py get_bdevs  |grep firmware_revision
          "firmware_revision": "VDV10131",
          "firmware_revision": "VDV10131",
          "firmware_revision": "VDV10131",
          "firmware_revision": "VDV10131",

```

**Comment by jimharris** [comment]
In module/bdev/nvme/bdev_nvme.rpc, could you change .nvme_adminq_poll_period_us to 10000 (10ms) instead of 1000000 (1s) and re-run your test?

We need to reduce this default value.  The default 1s was chosen a long time ago, but for cases like firmware download, 1s is much too infrequent.

**Comment by ufo19890607** [comment]
> In module/bdev/nvme/bdev_nvme.rpc, could you change .nvme_adminq_poll_period_us to 10000 (10ms) instead of 1000000 (1s) and re-run your test?
> 
> We need to reduce this default value. The default 1s was chosen a long time ago, but for cases like firmware download, 1s is much too infrequent.

Hi Jim
I've modified nvme_adminq_poll_period_us to 100000 us, and it just costs 36 secs. Below is patch
I've made. Thank you.

[0001-bdev-nvme-Reduce-the-long-time-for-apply_nvme_firmwa.zip](https://github.com/spdk/spdk/files/4375237/0001-bdev-nvme-Reduce-the-long-time-for-apply_nvme_firmwa.zip)

**Comment by tomzawadzki** [comment]
Hi @ufo19890607, looks like similar patch was merged today for the same reason as this issue.
https://review.spdk.io/gerrit/c/spdk/spdk/+/1393
This should help you.

Please remember that if you'd like to submit a patch, all contributions are welcome !
See https://spdk.io/development/ for how to submit patch on gerrit.

**Comment by ufo19890607** [comment]
> Hi @ufo19890607, looks like similar patch was merged today for the same reason as this issue.
> https://review.spdk.io/gerrit/c/spdk/spdk/+/1393
> This should help you.
> 
> Please remember that if you'd like to submit a patch, all contributions are welcome !
> See https://spdk.io/development/ for how to submit patch on gerrit.

Hi tomzawadzki
 I think 10ms is too frequent for spdk reactor, I've tested that if we set the period to 100ms, it just
takes 36 secs  to update the firmware, which is much more appropriate.
$ time ./scripts/rpc.py apply_firmware ./xxx_signed.bin
632f5018-0c5c-49b7-9aa9-aba41291c3d3-nvmen1
"firmware commit succeeded. Controller reset in progress."

real    0m36.209s
user    0m0.056s
sys     0m0.008s
