### ISSUE TITLE
slow sgl performance

### ISSUE THREAD

**Issue by hlitz** [spdk/spdk#131]
I am using 512B sectors and 4KB main memory pages. When I use regular reads, for 1-8 consecutive sectors (all within the same 4K aligned memory range) I get high IOPS (850K). When I use SGL reads (readv) I only get 850K for 1 sector reads and for 2 consecutive sectors (within a 4K page) I only get 500K. I don't understand why the SGL functions should be slower here. As I am using 4KB memory pages, I am using in all cases (1-8 sectors) only a single scatter/gather list entry.

**Comment by benlwalker** [comment]
Can you tell us which device you are using? Maybe dump the output of examples/nvme/identify here. Are you reading from a sector that was previously written with data prior to each test run?

**Comment by hlitz** [comment]
Hi 
its a Samsung PM1725 device. I actually found a much more severe issue. The data read from the device is always zero when using sgls although the address mapping in the sge_next_cb seems to be fine. I am on a SPDK commit from June 2016 and there seem to be some patches regarding sgls sinde then. Should I upgrade?
I am hesitant to upgrade because the spdk API has changed considerably (again). Is there a guide on how to port from nvme_impl.h to the env.h?
