### ISSUE TITLE
iscsiadm failed to login to the portal during the iscsi_tgt_filesystem test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1311]
https://ci.spdk.io/results/autotest-per-patch/builds/5620/archive/iscsi-autotest/build.log

Similar to https://github.com/spdk/spdk/issues/1259

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_7626.html

**Comment by tomzawadzki** [comment]
Bug scrub: @karlatec will check first if this is issue specific to that particular machine. If not, then reassign Jim.

**Comment by karlatec** [comment]
I see that this failure occurs only on a particular test node. And I think I saw this issue a long time ago.
I did:
```
sudo -n iscsiadm -m discoverydb -t sendtargets -p 127.0.0.1:3260 -o delete
sudo -n iscsiadm -m discoverydb -t sendtargets -p 127.0.0.2:3260 -o delete
sudo -n rm -rf /var/lib/iscsi/nodes/*
```

Let's see if that helps.

**Comment by karlatec** [comment]
So I did a couple of manual runs of iscsi autotest and all of them passed except for one, and it failed on GP15.
First iscsi test build after commands from previous comment was successful, but then the second one failed with the same reason as in the GH issue. Something may not be cleaned up properly.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_8108.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_8106.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_8111.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_8094.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_8101.html

**Comment by karlatec** [comment]
Ha, I was right that this issue was raised before: https://github.com/spdk/spdk/issues/779

**Comment by karlatec** [comment]
Proposed solution to avoid the issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/1539

I think this could be improved even more by investigating traps in iscsi_tgt tests. I have a feeling that they don't work quite properly, that's why there are leftover files after fails...

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_8092.html
