### ISSUE TITLE
iscsi_tgt_ip_migration fio doesn't find jobs

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1313]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Logging in to [iface: default, target: iqn.2016-06.io.spdk:target1, portal: 127.0.0.2,3260] (multiple)
Login to [iface: default, target: iqn.2016-06.io.spdk:target1, portal: 127.0.0.2,3260] successful.
 07:49:26	# fiopid=565248
 07:49:26	# sleep 5
 07:49:26	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/fio.py -p iscsi -i 4096 -d 32 -t randrw -r 10
Device paths:
[]
No job(s) defined

fio-3.15
/usr/local/bin/fio [options] [job options] <job file(s)>
  --debug=options	Enable debug logging. May be one/more of:
			process,file,io,mem,blktrace,verify,random,parse,
			diskutil,job,mutex,profile,time,net,rate,compress,
			steadystate,helperthread,zbd
  --parse-only		Parse options only, don't start any IO
  --merge-blktrace-only	Merge blktraces only, don't start any IO
  --output		Write output to file
  --bandwidth-log	Generate aggregate bandwidth logs
  --minimal		Minimal (terse) output
  --output-format=type	Output format (terse,json,json+,normal)
  --terse-version=type	Set terse version output format (default 3, or 2 or 4)
  --version		Print version info and exit
  --help		Print this page
  --cpuclock-test	Perform test/validation of CPU clock
  --crctest=[type]	Test speed of checksum functions
  --cmdhelp=cmd		Print command help, "all" for all of them
  --enghelp=engine	Print ioengine help, or list available ioengines
  --enghelp=engine,cmd	Print help for an ioengine cmd
  --showcmd		Turn a job file into command line options
  --eta=when		When ETA estimate should be printed
            		May be "always", "never" or "auto"
  --eta-newline=t	Force a new line for every 't' period passed
  --status-interval=t	Force full status dump every 't' period passed
  --readonly		Turn on safety read-only checks, preventing writes
  --section=name	Only run specified section in job file, multiple sections can be specified
  --alloc-size=kb	Set smalloc pool to this size in kb (def 16384)
  --warnings-fatal	Fio parser warnings are fatal
  --max-jobs=nr		Maximum number of threads/processes to support
  --server=args		Start a backend fio server
  --daemonize=pidfile	Background fio server, write pid to file
  --client=hostname	Talk to remote backend(s) fio server at hostname
  --remote-config=file	Tell fio server to load this local job file
  --idle-prof=option	Report cpu idleness on a system or percpu basis
			(option=system,percpu) or run unit work
			calibration only (option=calibrate)
  --inflate-log=log	Inflate and output compressed log
  --trigger-file=file	Execute trigger cmd when file exists
  --trigger-timeout=t	Execute trigger at this time
  --trigger=cmd		Set this command as local trigger
  --trigger-remote=cmd	Set this command as remote trigger
  --aux-path=path	Use this path for fio state generated files

Fio was written by Jens Axboe <axboe@kernel.dk>
FIO completed with code 1

 07:49:31	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk0.sock spdk_kill_instance SIGTERM
 07:49:32	# rpc_second_addr=/var/tmp/spdk1.sock
 07:49:32	# rpc_add_target_node /var/tmp/spdk1.sock
 07:49:32	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk1.sock net_interface_add_ip_address 1 127.0.0.2
 07:49:32	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk1.sock iscsi_create_portal_group 1 127.0.0.2:3260
 07:49:32	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk1.sock iscsi_create_target_node target1 target1_alias Malloc0:0 1:2 64 -d
 07:49:32	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk1.sock net_interface_delete_ip_address 1 127.0.0.2
 07:49:32	# wait 565248
  07:49:32	# trap - ERR
  07:49:32	# print_backtrace
  07:49:32	# [[ ehxBET =~ e ]]
  07:49:32	# args=("${BASH_ARGV[@]}")
  07:49:32	# local args
  07:49:32	# xtrace_disable
  07:49:32	# '[' no '!=' yes ']'
  07:49:32	# PREV_BASH_OPTS=ehxBET
  07:49:32	# [[ ehxBET == *\x* ]]
  07:49:32	# XTRACE_DISABLED=yes
  07:49:32	# set +x
========== Backtrace start: ==========

in ./test/iscsi_tgt/ip_migration/ip_migration.sh:123 -> main([])
     ...
   118 	$rpc_py -s $rpc_first_addr spdk_kill_instance SIGTERM
   119 	
   120 	rpc_second_addr="/var/tmp/spdk1.sock"
   121 	rpc_add_target_node $rpc_second_addr
   122 	
=> 123 	wait $fiopid
   124 	
   125 	trap - SIGINT SIGTERM EXIT
   126 	
   127 	iscsicleanup
   128 	
     ...

========== Backtrace end ==========
  07:49:32	# xtrace_enable
  07:49:32	# return 0
 07:49:32	# kill_all_iscsi_target
 07:49:32	# (( i = 0 ))
 07:49:32	# (( i < 2 ))
 07:49:32	# rpc_addr=/var/tmp/spdk0.sock
 07:49:32	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk0.sock spdk_kill_instance SIGTERM
Traceback (most recent call last):
  File "/var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc/client.py", line 51, in __init__
    self.sock.connect((addr, port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py", line 2422, in <module>
    args.client = rpc.client.JSONRPCClient(args.server_addr, args.port, args.timeout, log_level=getattr(logging, args.verbose.upper()))
  File "/var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc/client.py", line 56, in __init__
    "Error details: %s" % (addr, ex))
rpc.client.JSONRPCException: Error while connecting to /var/tmp/spdk0.sock
Error details: [Errno -2] Name or service not known
  07:49:32	# trap - ERR
  07:49:32	# print_backtrace
  07:49:32	# [[ ehxBET =~ e ]]
  07:49:32	# args=("${BASH_ARGV[@]}")
  07:49:32	# local args
  07:49:32	# xtrace_disable
  07:49:32	# '[' no '!=' yes ']'
  07:49:32	# PREV_BASH_OPTS=ehxBET
  07:49:32	# [[ ehxBET == *\x* ]]
  07:49:32	# XTRACE_DISABLED=yes
  07:49:32	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/iscsi-autotest/spdk/test/common/autotest_common.sh:694 -> run_test(["iscsi_tgt_ip_migration"],["./test/iscsi_tgt/ip_migration/ip_migration.sh"])
     ...
   689 		timing_enter $test_name
   690 		echo "************************************"
   691 		echo "START TEST $test_name"
   692 		echo "************************************"
   693 		xtrace_restore
=> 694 		time "$@"
   695 		xtrace_disable
   696 		echo "************************************"
   697 		echo "END TEST $test_name"
   698 		echo "************************************"
   699 		timing_exit $test_name
     ...
in ./test/iscsi_tgt/iscsi_tgt.sh:46 -> main(["posix"])
     ...
   41  	run_test "iscsi_tgt_qos" ./test/iscsi_tgt/qos/qos.sh
   42  	
   43  	# IP Migration tests do not support network namespaces,
   44  	# they can only be run on posix sockets.
   45  	if [ "$TEST_TYPE" == "posix" ]; then
=> 46  		run_test "iscsi_tgt_ip_migration" ./test/iscsi_tgt/ip_migration/ip_migration.sh
   47  	fi
   48  	run_test "iscsi_tgt_trace_record" ./test/iscsi_tgt/trace_record/trace_record.sh
   49  	
   50  	if [ $RUN_NIGHTLY -eq 1 ]; then
   51  		if [ $SPDK_TEST_PMDK -eq 1 ]; then
     ...

========== Backtrace end ==========
  07:49:32	# xtrace_enable
  07:49:32	# return 0

## Steps to Reproduce

1.
2.
3.
4.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_7766.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_9891.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_9922.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_10220.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_10474.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_10582.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_11261.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_11164.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_11294.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_11301.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_11567.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11413.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_11585.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_11589.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_11860.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11957.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11985.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11812.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_11988.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12046.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_12142.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12130.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_12290.html

**Comment by tomzawadzki** [comment]
[Bug scrub] This looks like two possible issues, 1) fio.py searches for iscsi targets to connect to and should fail if it does not find any 2) iscsi_tgt_ip_migration should make sure that targets are first available

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_12404.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_13181.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_13574.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_13659.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_13792.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_13764.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_13841.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_14548.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_14642.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_14975.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_15063.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_15256.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_15582.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_15586.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_15634.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_16116.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_16098.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_12690.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_16147.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_16678.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_17242.html

**Comment by optimistyzy** [comment]
After discussion with Shuhei, and he suggested that the following patch will help:

https://review.spdk.io/gerrit/c/spdk/spdk/+/2815

Let's review and merge this patch and see whether this issue will happen again for one week. 

@shuhei-matsumoto @jimharris @tomzawadzki @benlwalker @changpe1

**Comment by optimistyzy** [comment]
Close this issue, since two patches are merged: https://review.spdk.io/gerrit/c/spdk/spdk/+/2815  and https://review.spdk.io/gerrit/c/spdk/spdk/+/2801.  If same issues happen again, we can re-open it.
