### ISSUE TITLE
NVMe-oF TCP gets connection refused at nvmf_target_disconnect_tc2

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1318]
https://ci.spdk.io/results/autotest-per-patch/builds/7938/archive/nvmf-tcp-autotest/build.log

```
Starting SPDK v20.04-pre git sha1 7dcb9bb7f / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: reconnect --no-shconf -c 0xF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid779757 ]
EAL: No available hugepages reported in hugepages-1048576kB
 10:13:17	# kill -9 779726
 10:13:17	# sleep 2
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
nvme_qpair.c: 475:spdk_nvme_qpair_process_completions: *ERROR*: CQ error, abort requests after transport retry counter exceeded
posix.c: 446:spdk_posix_sock_create: *ERROR*: connect() failed, errno = 111
nvme_tcp.c:1519:nvme_tcp_ctrlr_connect_qpair: *ERROR*: sock connection error of tqpair=0x7f19c4000ba0 with addr=127.0.0.1, port=4420
qpair failed and we were unable to recover it.

```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_7938.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8535.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8762.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8827.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9315.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9681.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_10476.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_10472.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @liang2yan. log: https://ci.spdk.io/public_build/autotest-per-patch_10556.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_10689.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_10841.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11493.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11503.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11960.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11955.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11956.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_12054.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12068.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_12288.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12308.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12309.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12383.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_14075.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_14074.html

**Comment by optimistyzy** [comment]
Closes this issue since it is not reported more than 3 weeks. If the issue happens again, we can re-open it.
