### ISSUE TITLE
bdev_verify failed: thread bdevperf_reactor_0 still has active channel for io_device sw_accel_engine

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#1321]
************************************
START TEST bdev_verify
************************************
 00:04:46	# xtrace_enable
 00:04:46	# /var/jenkins/workspace/ubuntu18-autotest/spdk/test/bdev/bdevperf/bdevperf --json /var/jenkins/workspace/ubuntu18-autotest/spdk/test/bdev/bdev.conf -q 128 -o 4096 -w verify -t 5
Starting SPDK v20.04-pre git sha1 481fbadd3 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid798 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 362:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
cryptodev_aesni_mb_create() line 1321: IPSec Multi-buffer library version used: 0.52.0

vbdev_passthru.c: 755:bdev_passthru_create_disk: *NOTICE*: vbdev creation deferred pending base bdev arrival
vbdev_passthru.c: 645:vbdev_passthru_register: *NOTICE*: Match on Malloc3
vbdev_passthru.c: 688:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x615000002d80
vbdev_passthru.c: 700:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 715:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 728:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 729:vbdev_passthru_register: *NOTICE*: created pt_bdev for: TestPT
bdev_raid_rpc.c: 276:spdk_rpc_bdev_raid_create: *ERROR*: the rpc param strip_size is deprecated.
Running I/O for 5 seconds...
app.c: 716:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
thread.c: 358:spdk_thread_exit: *ERROR*: thread bdevperf_reactor_0 still has active channel for io_device sw_accel_engine
Buffer mismatch! Target: AIO0 Disk Offset: 4994
   First dword expected 0x20202020 got 0xeeeeeeee
Buffer mismatch! Target: AIO0 Disk Offset: 4996
   First dword expected 0x2c2c2c2c got 0xc3c3c3c3
Buffer mismatch! Target: AIO0 Disk Offset: 4998
   First dword expected 0x5f5f5f5f got 0xe2e2e2e2

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_8188.html

**Comment by shuhei-matsumoto** [comment]
Hi @benlwalker 

This is duplicated with https://github.com/spdk/spdk/issues/1288.
I have posted patches to fix this issue starting from https://review.spdk.io/gerrit/c/spdk/spdk/+/1390.
Will you review them when you can?

**Comment by changpe1** [comment]
Closing this issue.
