### ISSUE TITLE
SPDK does not support nvme self test command on intel 4510 disk

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1322]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Please check below yellow highlight. I run this on intel NVMe 4510 disk. Could you please help check root cause for me? If HW issue or SPDK issue?

Starting SPDK v20.04-pre git sha1 b8eaa9679 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid68788 ]
EAL: VFIO support initialized
get_feature(0x05) failed
=====================================================
NVMe Controller at 0000:be:00.0 [8086:0a54]
=====================================================
Controller Capabilities/Features
================================
Vendor ID:                             8086
Subsystem Vendor ID:                   1028
Serial Number:                         PHLJ9135008E4P0DGN
Model Number:                          Dell Express Flash NVMe P4510 4TB SFF
Firmware Version:                      VDV1DP21
Recommended Arb Burst:                 0
IEEE OUI Identifier:                   e4 d2 5c
Multi-path I/O
  May have multiple subsystem ports:   No
  May be connected to multiple hosts:  No
  Associated with SR-IOV VF:           No
Max Data Transfer Size:                131072
Max Number of Namespaces:              1
NVMe Specification Version (VS):       1.2
NVMe Specification Version (Identify): 1.2
Maximum Queue Entries:                 4096
Contiguous Queues Required:            Yes
Arbitration Mechanisms Supported
  Weighted Round Robin:                Supported
  Vendor Specific:                     Not Supported
Reset Timeout:                         60000 ms
Doorbell Stride:                       4 bytes
NVM Subsystem Reset:                   Not Supported
Command Sets Supported
  NVM Command Set:                     Supported
Boot Partition:                        Not Supported
Memory Page Size Minimum:              4096 bytes
Memory Page Size Maximum:              4096 bytes
Optional Asynchronous Events Supported
  Namespace Attribute Notices:         Not Supported
  Firmware Activation Notices:         Not Supported
128-bit Host Identifier:               Not Supported

Controller Memory Buffer Support
================================
Supported:                             No

Admin Command Set Attributes
============================
Security Send/Receive:                 Not Supported
Format NVM:                            Supported
Firmware Activate/Download:            Supported
Namespace Management:                  Supported
Device Self-Test:                      Not Supported
Directives:                            Not Supported
NVMe-MI:                               Not Supported
Virtualization Management:             Not Supported
Doorbell Buffer Config:                Not Supported
Abort Command Limit:                   4
Async Event Request Limit:             4
Number of Firmware Slots:              1
Firmware Slot 1 Read-Only:             No
Firmware Update Granularity:           No Information Provided
Per-Namespace SMART Log:               No
Command Effects Log Page:              Supported
Get Log Page Extended Data:            Supported
Telemetry Log Pages:                   Supported
Error Log Page Entries Supported:      64
Keep Alive:                            Not Supported

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
Hi @gwnet,

This is not an SPDK issue.  SPDK is only reporting what the SSD says it supports.  In this case, the SSD does not support device self-test.

-Jim

**Comment by gwnet** [comment]
@jimharris thank you so much, I review the code and SPDK fetch the NVMe drive oacs register to decide if the drive has the self test capability. thank you so much again. we are clear now.

**Comment by Comphix** [comment]
Close this issue.
