### ISSUE TITLE
qat_setup.sh failed to create VFs for all the QAT devices

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1327]
https://ci.spdk.io/results/autotest-per-patch/builds/8517/archive/vhost-autotest/build.log

`0000:85:00.0` and `0000:86:00.0` were reported by the kernel as busy during the attempt of adding VF devices on top of them.

https://ci.spdk.io/results/autotest-per-patch/builds/8517/archive/vhost-autotest/dmesg.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_8517.html

**Comment by changpe1** [comment]
[Bug Scrub] Could you take a look? Thanks.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9295.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9401.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_9572.html

**Comment by jimharris** [comment]
@karlatec @mikeBashStuff these both happened on GP4 - do you know if that system was updated?  failures haven't been seen on that system for a couple of weeks now

**Comment by karlatec** [comment]
Actually it might have been updated to 5.5.10 kernel about a week ago or so. This was done to keep systems consistent and as a request in #1315 issue. Had to re-install QAT driver too.
It seems we do not have a reproduction for over 2 weeks not, GP4 build history is all green so I guess we can close this issue.
