### ISSUE TITLE
bdev_verify test failed due to buffer mismatch 

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1329]
https://ci.spdk.io/results/autotest-per-patch/builds/8926/archive/ubuntu18-autotest/build.log

```
************************************
START TEST bdev_verify
************************************
 04:42:20	# xtrace_enable
 04:42:20	# /var/jenkins/workspace/ubuntu18-autotest/spdk/test/bdev/bdevperf/bdevperf --json /var/jenkins/workspace/ubuntu18-autotest/spdk/test/bdev/bdev.json -q 128 -o 4096 -w verify -t 5 -C -m 0x3
Starting SPDK v20.04-pre git sha1 d75ebba85 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x3 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid11965 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 2
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
cryptodev_aesni_mb_create() line 1321: IPSec Multi-buffer library version used: 0.52.0

vbdev_passthru.c: 755:bdev_passthru_create_disk: *NOTICE*: vbdev creation deferred pending base bdev arrival
vbdev_passthru.c: 645:vbdev_passthru_register: *NOTICE*: Match on Malloc3
vbdev_passthru.c: 688:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x615000002d80
vbdev_passthru.c: 700:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 715:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 728:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 729:vbdev_passthru_register: *NOTICE*: created pt_bdev for: TestPT
bdev_raid_rpc.c: 276:spdk_rpc_bdev_raid_create: *ERROR*: the rpc param strip_size is deprecated.
Running I/O for 5 seconds...
app.c: 716:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
Buffer mismatch! Target: AIO0 Disk Offset: 2500
   First dword expected 0x80808080 got 0x7d7d7d7d
Buffer mismatch! Target: AIO0 Disk Offset: 2502
   First dword expected 0xaaaaaaaa got 0x63636363
Buffer mismatch! Target: AIO0 Disk Offset: 2504
   First dword expected 0x59595959 got 0x7a7a7a7a
Buffer mismatch! Target: AIO0 Disk Offset: 2506
   First dword expected 0xa9a9a9a9 got 0xb5b5b5b5
Buffer mismatch! Target: AIO0 Disk Offset: 2508
   First dword expected 0x22222222 got 0x75757575
Buffer mismatch! Target: AIO0 Disk Offset: 2510
   First dword expected 0x84848484 got 0xfefefefe
Buffer mismatch! Target: AIO0 Disk Offset: 2512
   First dword expected 0x17171717 got 0xaaaaaaaa
Buffer mismatch! Target: AIO0 Disk Offset: 2514
   First dword expected 0x39393939 got 0xc2c2c2c2
Buffer mismatch! Target: AIO0 Disk Offset: 2516
   First dword expected 0xbbbbbbbb got 0x3e3e3e3e
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8926.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8945.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8944.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8972.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_8994.html

**Comment by peluse** [comment]
I'll investigate this weekend unless someone has time today

**Comment by shuhei-matsumoto** [comment]
Hi @peluse 

I  haven't found anything wrong yet. Others do not report this issue yet.  So my patches may be the cause. Anyway thank you Paul.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9104.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9115.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9121.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9118.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9169.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_9235.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9254.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9263.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9307.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9331.html

**Comment by tomzawadzki** [comment]
[Bug scrub] @Seth5141 noted that for most part this issue has been occurring pretty often on Ubuntu18 jobs.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9373.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9382.html

**Comment by peluse** [comment]
I've found 2 issues so far but can still repro with multi-core. I think single core is OK so submitted patch to run in CI while I debug that limits it, will see if any hit in the meantime. https://review.spdk.io/gerrit/c/spdk/spdk/+/1735

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_9416.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9432.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9418.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9421.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9427.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9430.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9436.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9447.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_9464.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9455.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9461.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9473.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9467.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9459.html

**Comment by shuhei-matsumoto** [comment]
The fix is here https://review.spdk.io/gerrit/c/spdk/spdk/+/1740

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_9490.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9602.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_9608.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_9604.html

**Comment by peluse** [comment]
I believe we have this fixed: https://review.spdk.io/gerrit/c/spdk/spdk/+/1736

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_9628.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_9451.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_9709.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_9666.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9646.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9667.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9687.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_9780.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_9645.html

**Comment by shuhei-matsumoto** [comment]
Thank you. The patch has been merged. Please rebase your patch onto the latest master, and reopen if reproduced even after rebase.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_9790.html

**Comment by shuhei-matsumoto** [comment]
> Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_9790.html

Hi @wawryk will you rebase on the latest master?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_9832.html
