### ISSUE TITLE
vpp: lots of TypeError during installation

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1335]
## Current Behavior
Error log:
[1/1308] Generating API header /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/bonding/bond.api.h
FAILED: vnet/bonding/bond.api.h
cd /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet && mkdir -p /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/bonding && /home/wanghailiang/spdk20200317_vpp/vpp/src/tools/vppapigen/vppapigen --includedir /home/wanghailiang/spdk20200317_vpp/vpp/src --input /home/wanghailiang/spdk20200317_vpp/vpp/src/vnet/bonding/bond.api --output /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/bonding/bond.api.h
TypeError: expected str, bytes or os.PathLike object, not Namespace
[2/1308] Generating API header /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/cop/cop.api.json
FAILED: vnet/cop/cop.api.json
cd /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet && mkdir -p /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/cop && /home/wanghailiang/spdk20200317_vpp/vpp/src/tools/vppapigen/vppapigen --includedir /home/wanghailiang/spdk20200317_vpp/vpp/src --input /home/wanghailiang/spdk20200317_vpp/vpp/src/vnet/cop/cop.api JSON --output /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/cop/cop.api.json
TypeError: string indices must be integers
[3/1308] Generating API header /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/cop/cop.api.h
FAILED: vnet/cop/cop.api.h
cd /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet && mkdir -p /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/cop && /home/wanghailiang/spdk20200317_vpp/vpp/src/tools/vppapigen/vppapigen --includedir /home/wanghailiang/spdk20200317_vpp/vpp/src --input /home/wanghailiang/spdk20200317_vpp/vpp/src/vnet/cop/cop.api --output /home/wanghailiang/spdk20200317_vpp/vpp/build-root/build-vpp_debug-native/vpp/vnet/cop/cop.api.h
TypeError: expected str, bytes or os.PathLike object, not Namespace
......
make[1]: *** [Makefile:695: vpp-build] Error 1
make[1]: Leaving directory '/home/wanghailiang/spdk20200317_vpp/vpp/build-root'
make: *** [Makefile:361: build] Error 2
make: Leaving directory '/home/wanghailiang/spdk20200317_vpp/vpp'

## Possible Solution
There may be some compilation errors that need to be resolved.

## Steps to Reproduce
1.git clone https://gerrit.fd.io/r/vpp && cd vpp
2.git checkout v19.04.2
3.copy vpp to spdk/
4.cd spdk
5.git -C ./vpp apply test/common/config/patch/vpp/fedora30-fix.patch
6.yes | make -C ./vpp install-dep  (passed)
7.make -C ./vpp build -j  (failed)

## Context (Environment including OS version, SPDK version, etc.)
OS Fedora30, kernel 5.0.9
SPDK commit 302f7aa6e4476e75fea622cc5729dd7aa859575b
VPP commit d95a226047437af47e046feb93ceba9204a37940

**Comment by karlatec** [comment]
@wanghailiangx did you run these steps manually or by script?
There's a test/common/config/vm_setup.sh script which you can use to install VPP on you system.
`test/common/config/vm_setup.sh -t "vpp"`

We run VPP on Fedora30 systems in the CI and I did some manual reinstalling myself, so I'm pretty sure it's OK...
Example CI system specs:
```
Fedora 30 5.5.10-100.fc30.x86_64
gcc 9.2.1 20190827
```

**Comment by karlatec** [comment]
@wanghailiangx did you run these steps manually or by script?
There's a test/common/config/vm_setup.sh script which you can use to install VPP on you system.
`test/common/config/vm_setup.sh -t "vpp"`

We run VPP on Fedora30 systems in the CI and I did some manual reinstalling myself, so I'm pretty sure it's OK...
Example CI system specs:
```
Fedora 30 5.5.10-100.fc30.x86_64
gcc 9.2.1 20190827
```

**Comment by karlatec** [comment]
@tkulasek perhaps you could also take a look at the failure?

**Comment by wanghailiangx** [comment]
@karlatec Thank you for your attention. I tried vm_setup.sh before, these below steps are from this script.  Manual execution is the same.
5.git -C ./vpp apply test/common/config/patch/vpp/fedora30-fix.patch
6.yes | make -C ./vpp install-dep
7.make -C ./vpp build -j

**Comment by karlatec** [comment]
Unassigning myself. These installation steps worked for me. Maybe @tkulasek can help.

**Comment by tkulasek** [comment]
@wanghailiangx what version of python are you using on your system?

**Comment by wanghailiangx** [comment]
@tkulasek My python version is 2.7.17.

**Comment by wanghailiangx** [comment]
@tkulasek 
# python --version
Python 2.7.17
# whereis python
python: /usr/bin/python3.7 /usr/bin/python3.7m /usr/bin/python /usr/bin/python2.7 /usr/bin/python3.7m-x86_64-config /usr/bin/python2.7-config /usr/bin/python3.7-config /usr/bin/python3.7m-config /usr/lib/python2.7 /usr/lib/python3.7 /usr/lib64/python2.7 /usr/lib64/python3.7 /usr/include/python3.7m /usr/include/python2.7 /usr/share/man/man1/python.1.gz

**Comment by jimharris** [comment]
VPP has been deprecated.
