### ISSUE TITLE
nvme-phy-autotest: build timed out

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1338]
No obvious issues

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_9902.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_9918.html

**Comment by peluse** [comment]
dup
