### ISSUE TITLE
vhost-autotest - qemu-img convert failure

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1339]
https://ci.spdk.io/results/autotest-per-patch/builds/9878/archive/vhost-autotest/build.log

```
 21:23:30	# qemu-img convert /home/sys_sgci/vhost_vm_image.qcow2 -O raw /dev/nbd0
qemu-img: /dev/nbd0: error while converting raw: Device is too small
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9911.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_9878.html

**Comment by Donaim** [comment]
Hi, this should be fixed now.
Error was due to experimental VM image on GP15 that was used for testing, but wasn't reverted when testing finished.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_9874.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_9892.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_9903.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_9901.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_9905.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_9890.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_9961.html
