### ISSUE TITLE
sock layer uses zero copy on loopback interfaces

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1340]
We currently try to use MSG_ZEROCOPY whenever possible.  But loopback doesn't really support zero copy.  We should detect if the fd is associated with an interface that has IFF_LOOPBACK set, and not use zero copy when it is set.

I was doing some ad hoc testing today and found this as a rather significant issue in some cases.  We use loopback in a large amount of our CI testing, so we should try to make use of the loopback interface as efficient as possible.

**Comment by optimistyzy** [comment]
I posted a patch to address this issue:  https://review.spdk.io/gerrit/c/spdk/spdk/+/2372

**Comment by optimistyzy** [comment]
Close this issue since the patch which tries to address this issue is merged.
