### ISSUE TITLE
Failed to add host to a subsystem

### ISSUE THREAD

**Issue by scarbrofair** [spdk/spdk#1342]
Cannot add a host to an susbsystem
## Expected Behavior

add host to the specified subsystem

## Current Behavior
[root@cssrv12 scripts]#  /opt/python3.6/bin/python3.6 ./rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000001
[root@cssrv12 scripts]# /opt/python3.6/bin/python3.6 ./rpc.py  get_nvmf_subsystems
[
  {
    "nqn": "nqn.2014-08.org.nvmexpress.discovery",
    "subtype": "Discovery",
    "listen_addresses": [],
    "allow_any_host": true,
    "hosts": []
  },
  {
    "nqn": "nqn.2016-06.io.spdk:cnode1",
    "subtype": "NVMe",
    "listen_addresses": [],
    "allow_any_host": true,
    "hosts": [],
    "serial_number": "SPDK00000000001",
    "model_number": "SPDK bdev Controller",
    "namespaces": []
  }
]
[root@cssrv12 scripts]#  /opt/python3.6/bin/python3.6 ./rpc.py nvmf_subsystem_add_host nqn.2016-06.io.spdk:cnode1 10.197.160.12
request:
{
  "method": "nvmf_subsystem_add_host",
  "req_id": 1,
  "nqn": "nqn.2016-06.io.spdk:cnode1",
  "host": "10.197.160.12"
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "Internal error"
}

## Possible Solution

find error messge from nvmf_tgt:
subsystem.c: 131:spdk_nvmf_valid_nqn: *ERROR*: Invalid NQN "10.197.160.12": NQN must begin with "nqn.".
some guys made a misstake on subsystem.c: 636 as following:

      if (!spdk_nvmf_valid_nqn(hostnqn)) {

which passed the wrong parameter to spdk_nvmf_valid_nqn. 
We need to pass the name of this subsystem to this function.
Just fix subsystem.c: 636 as following, can fix this bug:

      if (!spdk_nvmf_valid_nqn(subsystem->subnqn)) {

**Comment by yidong0635** [comment]
@scarbrofair  it seems mistaken of param pass through :
 rc = spdk_nvmf_subsystem_add_host(subsystem, ctx->nqn/ctx->host);

**Comment by jimharris** [comment]
HI @scarbrofair,

The code is working as intended.  It is checking that the hostnqn is valid.  In the case shown, it is passing an IP address, not an NQN.

-Jim

**Comment by scarbrofair** [comment]
> HI @scarbrofair,
> 
> The code is working as intended. It is checking that the hostnqn is valid. In the case shown, it is passing an IP address, not an NQN.
> 
> -Jim

So,  how to add an ip to subsystem

**Comment by yidong0635** [comment]
So we need to add host :
see etc/spdk/nvmf.conf.in( Host nqn.2016-06.io.spdk:init)
./scripts/rpc.py nvmf_subsystem_add_host nqn.2016-06.io.spdk:cnode1  nqn.2016-06.io.spdk:init
if add IP address as listener :
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t RDMA/TCP -a [IP address] -s 4420

**Comment by jimharris** [comment]
> > HI @scarbrofair,
> > The code is working as intended. It is checking that the hostnqn is valid. In the case shown, it is passing an IP address, not an NQN.
> > -Jim
> 
> So, how to add an ip to subsystem?

None currently.

@shuhei-matsumoto @benlwalker We support access by IP address in iSCSI.  Is there any reason we can't do it for NVMe over Fabrics as well?

**Comment by changpe1** [comment]
[Bug Scrub] It's should not an issue, let's keep it open for discussion.

**Comment by shuhei-matsumoto** [comment]
@jimharris 
If we take SPDK iSCSI target as an example, initiator group requires both host IQN and host IP address but we can set wildcard for both.

**Comment by shuhei-matsumoto** [comment]
Add another comment. For iSCSI, I think access control has been implementation specific but most products have very similar functionality. It is not defined by RFC specification. Unfortunately I don't know fibre channel SCSI, but probably it has been defined by specification.

**Comment by mhae** [comment]
What would be the purpose of using IP addresses, rather than the nqn? It's unclear to me why we would need this. For authentication purposes?
IP addresses can change, even static ones. Also, host nqn is currently used for access control, and more importantly, as an identifier for the session. Using an IP as an identifier would work if we ever support static session instead of dynamic session.
Coming back to my first question: I'd be really interested in the use case for using IP addresses.

**Comment by jimharris** [comment]
This does not look like something SPDK will implement.
