### ISSUE TITLE
DPDK failed to init with error "EAL: Cannot get a virtual area: Cannot allocate memory"

### ISSUE THREAD

**Issue by shravansundarraj** [spdk/spdk#1343]
DPDK Version :  20.02
GCC version :    4.9.1
Kernel version  : 3.14.39ltsi++
and compiled for 32-bit

### Huge pages created ad below:

echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
sudo sysctl -w vm.nr_hugepages=1024 
mkdir -p /mnt/huge_2mb
sudo mount -t hugetlbfs nodev /mnt/huge_2mb -o pagesize=2MB 

In my main function I am calling "rte_eal_init()" . My process does nothing other than this.
### Logs:
**Linux(debug)# sudo /tmp/dpdk.bin   
invoked main
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 0 on socket 0
EAL: Detected lcore 5 as core 1 on socket 0
EAL: Detected lcore 6 as core 2 on socket 0
EAL: Detected lcore 7 as core 3 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: rte_config_init type ::0
EAL: /var/run/dpdk/rte/config
EAL: Ask a virtual area of 0x4000 bytes 
EAL: mapaddr::0xf75a8000
EAL: Virtual area found at 0xf75a8000 (size = 0x4000)
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...vfio
EAL: Module /sys/module/vfio not found! error 2 (No such file or directory)
EAL: Probing VFIO support...0
EAL: VFIO modules not loaded, skipping VFIO support...
EAL: SHRRAJ rte_fbarray_init
EAL: Ask a virtual area of 0x2b000 bytes 
EAL: mapaddr::0xf657d000
EAL: Virtual area found at 0xf657d000 (size = 0x2b000)
EAL: Setting up physically contiguous memory...
EAL: Setting maximum number of open files to 10240
EAL: Attempting to preallocate 2048M on socket 0
EAL: Ask a virtual area of 0xc000 bytes
EAL: mapaddr::0xf6571000
EAL: Virtual area found at 0xf6571000 (size = 0xc000)
EAL: Memseg list allocated: 0x800kB at socket 0
EAL: Ask a virtual area of 0x80000000 bytes 
EAL: mapaddr::0xffffffff
EAL: Cannot get a virtual area: Cannot allocate memory**

**Comment by jimharris** [comment]
Hi @shravansundarraj,

It looks like you're only testing DPDK here - you may want to try the DPDK mailing list.

But also note that SPDK isn't testing 32-bit at all currently.  So for this issue, you'll likely get better support from DPDK than from those lurking on SPDK github.

This also means that once you get past this issue, you may run into others, if this is your first step towards building a 32-bit SPDK application.  If you run into such issues, please file new issues for anything SPDK specific.

Regards,

Jim

**Comment by shravansundarraj** [comment]
thanks for the update Jimharris

**Comment by changpe1** [comment]
Closing this issue for now, you can reopen it if related with SPDK. Thanks.
