### ISSUE TITLE
EAL: no supported IOMMU extensions found 

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1344]
Hello everyone, I loaded the Vfio driver on the machine, and the nvme disk was also taken over by vfio, but when I started the spdk, I was prompted: EAL: no supported IOMMU extensions found! EAL: VFIO support could not be initialized

spdk version:20.01

![image](https://user-images.githubusercontent.com/15990748/79193112-8f085380-7e5c-11ea-9730-a3d97669edb3.png)

![image](https://user-images.githubusercontent.com/15990748/79193135-97f92500-7e5c-11ea-9017-8201a68bf059.png)

/boot/grub2/grub.cfg
![image](https://user-images.githubusercontent.com/15990748/79193304-f0302700-7e5c-11ea-8231-1fb627187461.png)

I do not know if there is a problem with the configuration?

Thanks
  Su

**Comment by changpe1** [comment]
I guess this should related with your kernel vfio configuration, does the uio driver work for you?

**Comment by peluse** [comment]
Has vfio ever worked for you on this system?

**Comment by zlsh007** [comment]
@changpe1 , UIO can work, there may be a problem with the configuration of vfio, do you have any suggestions?
![image](https://user-images.githubusercontent.com/15990748/79522496-797a7000-808e-11ea-82de-165b8464eb94.png)

![image](https://user-images.githubusercontent.com/15990748/79522502-7d0df700-808e-11ea-8e41-ef734545515d.png)

![image](https://user-images.githubusercontent.com/15990748/79522539-944ce480-808e-11ea-8c17-d56f993edfa2.png)

**Comment by zlsh007** [comment]
@peluse  This machine is a new environment. At least I have not successfully used vfio on it. I wrote the BDF information of several disks in the /etc/spdk/spdk.conf configuration file, which will automatically initialize the nvme subsystem
