### ISSUE TITLE
[vfio-pci] setup.sh reported "current user memlock limit: 0 MB" 

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1346]
I am not quite sure how severe this is, but I have been seeing this warning whenever `setup.sh` picks up `virtio-pci` driver to use, e.g.: https://ci.spdk.io/results/autotest-per-patch/builds/10567/archive/nvme-phy-autotest/build.log - in this particular case, the `ocf_persistent_metadata` test failed, but this may be a red herring caused rather by https://github.com/spdk/spdk/issues/1320.

**Comment by jimharris** [comment]
Hi @mikeBashStuff,

I don't see the text in the title anywhere in the posted log.  Could you add some more details please?

Thanks,

-Jim

**Comment by mikeBashStuff** [comment]
@jimharris The actual warning comes from `setup.sh` and looks like this:

```
Current user memlock limit: 0 MB

This is the maximum amount of memory you will be
able to use with DPDK and VFIO if run as current user.
To change this, please adjust limits.conf memlock limit for current user.

## WARNING: memlock limit is less than 64MB
## DPDK with VFIO may not be able to initialize if run as current user.
```
I admit that the subject of the issue is a bit misleading, but it points at this: `Current user memlock limit: 0 MB` - the `ulimit` returns value in KB and it's then converted to MB. Since the actual value is not caught in the trace it may vary a bit, hence the point about it being < 1024. :) (but I guess it's simply set to 0).

**Comment by tomzawadzki** [comment]
[Bug scrub] This particular message from `setup.sh` triggers on all CI test runs with vfio. Information it displays is correct, but all the tests are still ran using the sudo/root rather than actual user this information relates to.
The messaging is not clear and should be more specific.

**Comment by tomzawadzki** [comment]
Patch fixing calling ulimit with proper user and messaging around it:
https://review.spdk.io/gerrit/c/spdk/spdk/+/1964

**Comment by jimharris** [comment]
Patch was merged.
