### ISSUE TITLE
json_config test failed to create crypto bdev

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1347]
https://ci.spdk.io/results/autotest-per-patch/builds/10577/archive/crypto-autotest/build.log

Issue at hand:

```
13:41:46	# /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_crypto_create MallocForCryptoBdev CryptoMallocBdev crypto_qat 0123456789123456
vbdev_crypto.c:1819:vbdev_crypto_claim: *NOTICE*: QAT in use: Required alignment set to 10
vbdev_crypto.c:1822:vbdev_crypto_claim: *NOTICE*: QAT using cipher: AES_CBC
vbdev_crypto.c:1888:vbdev_crypto_claim: *ERROR*: ERROR can't match crypto device driver to crypto vbdev!
request:
{
  "base_bdev_name": "MallocForCryptoBdev",
  "name": "CryptoMallocBdev",
  "crypto_pmd": "crypto_qat",
  "key": "0123456789123456",
  "cipher": "AES_CBC",
  "method": "bdev_crypto_create",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -22,
  "message": "Invalid argument"
}
```
Earlier on, it's seen that `qat_setup.sh` was not able to create VF devices since the `sriov*` interface was missing from sysfs:

```
./scripts/qat_setup.sh: line 44: /sys/bus/pci/drivers/c6xx/0000:85:00.0/sriov_numvfs: No such file or directory
cat: '/sys/bus/pci/drivers/c6xx/0000:85:00.0/sriov_numvfs': No such file or directory
0000:85:00.0 set to  VFs
./scripts/qat_setup.sh: line 44: /sys/bus/pci/drivers/c6xx/0000:86:00.0/sriov_numvfs: No such file or directory
cat: '/sys/bus/pci/drivers/c6xx/0000:86:00.0/sriov_numvfs': No such file or directory
0000:86:00.0 set to  VFs
./scripts/qat_setup.sh: line 44: /sys/bus/pci/drivers/c6xx/0000:87:00.0/sriov_numvfs: No such file or directory
cat: '/sys/bus/pci/drivers/c6xx/0000:87:00.0/sriov_numvfs': No such file or directory
```
SR-IOV not enabled in the bios maybe? Not 100% if it's related to the failing test though.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_10577.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_10606.html

**Comment by karlatec** [comment]
> https://ci.spdk.io/public_build/autotest-per-patch_10577.html

This could probably be my fault. Did some system updates as part of fixes for other GH issue and I forgot to rebuild the QAT driver.
I suppose it can be reported a couple of times more after today, but if there are no new occurences after weekend then this can be closed.

> https://ci.spdk.io/public_build/autotest-per-patch_10606.html

Doesn't look related.

**Comment by mikeBashStuff** [comment]
>Doesn't look related.

 Should be 1309. Had multiple different false positives at the same time so I messed up the issue id here. Sorry for that. :)

**Comment by peluse** [comment]
this usually means the QAT kernel driver isn't installed correctly

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @liang2yan. log: https://ci.spdk.io/public_build/autotest-per-patch_10565.html

**Comment by changpe1** [comment]
It's same with #1327, failed to create the VF should be the root cause.

**Comment by changpe1** [comment]
[Bug Scrub] @karlatec Could you take a look and maybe work with Paul to see any issue with QAT card.

**Comment by karlatec** [comment]
> It's same with #1327, failed to create the VF should be the root cause.

#1327 is related to crypto as well, true, but the fail happens at very different stage (driver initialization vs test fail). 

@liang2yan The fail you reported has a build number very close to the one @mikeBashStuff reported, so I suspect it was caused by the same mistake.

Please see my comment from yesterday
```
This could probably be my fault. Did some system updates as part of fixes for other GH issue and I forgot to rebuild the QAT driver.
```

**Comment by tomzawadzki** [comment]
As per @karlatec comments, this issue was caused by maintenance work on one of the machines. Since then tests already had a chance to run on it multiple times.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_29899.html

**Comment by tomzawadzki** [comment]
As per recent occurrence above, the issue does not seem to be related maintenance work from April.

**Comment by karlatec** [comment]
@wawryk this fail was on recently added supermicro system. Can you re-build the QAT driver on all of these systems?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_30061.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30091.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30100.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30103.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30104.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30105.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_30074.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30109.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30108.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_30096.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_30093.html

**Comment by karlatec** [comment]
Updated QAT driver on systems mentioned in recent failures, let's see if this is ok

**Comment by tomzawadzki** [comment]
[Bug scrub] Thanks @karlatec for updating the driver. @mikeBashStuff will take a look at changing `qat_setup.sh` to fail in case the driver is not recent (see log from original report).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_30448.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30458.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30464.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_31131.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_31641.html

**Comment by mikeBashStuff** [comment]
Ok, I had a closer inspection of the recent failures and they differ quite from the original issue. The current problem now occurs on systems where QAT controllers (and their VFs) are attached to NUMA node different than 0 - this is the case, for instance, on GP3. This is now more prominent due to 2b80955c097ace9ba27631846ee49758444dff56 since all the hugepages land, by default, on node0. Before that commit was merged, the previous failures were actually due to #1709 (and before those, the original issue was the main actor).

Since CRYPTO tests seem to be unique in the sense that we actually need memory spread on different nodes, here's the potential fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/5464 (this one assumes that default 8G, when spread across all existing nodes, will be enough for other tests which use single node) and here's am optional HACKy workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/5465

I actually wonder if maybe `qat_setup.sh` could allocate some small amount of hugepages which are needed for actual VFs (it seems that by the very default, each VF == ~7 hugepages, where hugepagesz == 2MB) to be present on given node.

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5464 was merged.
Meanwhile the second idea https://review.spdk.io/gerrit/c/spdk/spdk/+/5465 was abandoned.

@mikeBashStuff does the above resolve this issue from your perspective ?

**Comment by mikeBashStuff** [comment]
@tomzawadzki I think so, yes. This particular patch + https://review.spdk.io/gerrit/c/spdk/spdk/+/5451 + changes committed on the CI side should mitigate this particular issue and #1709. Haven't seen similar failures in the crypto job for some time now.

**Comment by tomzawadzki** [comment]
[Bug scrub] Leaving open up till the end of the week.

**Comment by mikeBashStuff** [comment]
Issue seems to be resolved, no failures has been reported for quite a while now. Closing.
