### ISSUE TITLE
[spdk/qemu] Compilation issues on latest systems

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1349]
## Current Behavior

Configure or compile spdk/qemu issues for branch `spdk-3.0.0` on latest systems.
Sorry for putting that here, but we don't have spdk/qemu bugtracker.

## Steps to Reproduce

1. Clone spdk/qemu
2. Checkout branch spdk-3.0.0
3. Try to configure:
```
[klateck@GrizzlyPass8 qemu-spdk]$ ./configure --target-list="x86_64-softmmu" --enable-kvm --enable-linux-aio --enable-numa

ERROR: configure test passed without -Werror but failed with -Werror.
       This is probably a bug in the configure script. The failing command
       will be at the bottom of config.log.
       You can run configure with --disable-werror to bypass this check.
```
configuration log output contains pretty generic errors, most of which at first glance look like not satisfied dependencies (see attached file). However `dnf builddep` reports all is ok for building qemu and qemu-system-x86 packages.

4. Configure again with --disable-werror. 

5. Try to build:
```
block/gluster.c: In function ‘qemu_gluster_co_pwrite_zeroes’:
block/gluster.c:986:52: warning: passing argument 4 of ‘glfs_zerofill_async’ from incompatible pointer type [-Wincompatible-pointer-types]
  986 |     ret = glfs_zerofill_async(s->fd, offset, size, gluster_finish_aiocb, &acb);
      |                                                    ^~~~~~~~~~~~~~~~~~~~
      |                                                    |                                                                                                                                                                        |                                                    void (*)(struct glfs_fd *, ssize_t,  void *) {aka void (*)(struct glfs_fd *, long int,  void *)}
In file included from block/gluster.c:12:
/usr/include/glusterfs/api/glfs.h:993:73: note: expected ‘glfs_io_cbk’ {aka ‘void (*)(struct glfs_fd *, long int,  struct glfs_stat *, struct glfs_stat *, void *)’} but argument is of type ‘void (*)(struct glfs_fd *, ssize
_t,  void *)’ {aka ‘void (*)(struct glfs_fd *, long int,  void *)’}
  993 | glfs_zerofill_async(glfs_fd_t *fd, off_t length, off_t len, glfs_io_cbk fn,
      |                                                             ~~~~~~~~~~~~^~
block/gluster.c: In function ‘qemu_gluster_do_truncate’:
block/gluster.c:1027:13: error: too few arguments to function ‘glfs_ftruncate’
 1027 |         if (glfs_ftruncate(fd, offset)) {
      |             ^~~~~~~~~~~~~~

(more errors in attached file)
```

## Context (Environment including OS version, SPDK version, etc.)
System: Fedora31, gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC), 5.4.14-200.fc31.x86_64
I'mm 99% sure that I also saw similar issues on a F30 system - will try to attach logs later.

## Possible Solution
Update spdk/qemu branch to some more recent qemu version? qemu-4.15 maybe?

## Attachments:
[F31-spdk-qemu-config.log](https://github.com/spdk/spdk/files/4481825/F31-spdk-qemu-config.log)
[F31-spdk-qemu-build.log](https://github.com/spdk/spdk/files/4481826/F31-spdk-qemu-build.log)

**Comment by changpe1** [comment]
Does the FTL test have dependency on the spdk/qemu version? If not, I think we can upgrade our spdk/qemu version to a newer one.

**Comment by changpe1** [comment]
[Bug Scrub] @tomzawadzki Could you take a look if we can upgrade the QEMU version ?

**Comment by darsto** [comment]
There are some custom OCSSD patches in our qemu-3.0.0 branch needed for the FTL tests. I believe won't need them after we get physical FTL-capable devices, but for now they're necessary to test FTL.

If possible, I would suggest leaving FTL tests at older QEMU and move to the new QEMU with everything else. That should be the easiest way.

**Comment by karlatec** [comment]
> I believe won't need them after we get physical FTL-capable devices, but for now they're necessary to test FTL.

That may take a while, so we will need to stick with VMs running emulated FTL-capable drives.

**Comment by tomzawadzki** [comment]
[Bug scrub] We will look into whats possible with regards to updating FTL patches on top of newer QEMU version.

**Comment by darsto** [comment]
@tomzawadzki any update? I see you assigned, but is it you working on this?

**Comment by darsto** [comment]
We could also create a separate jenkins job with older QEMU just for FTL, then not to bottleneck autotest-per-patch, we could move the FTL tests to nightly only. That's something to consider.

**Comment by tomzawadzki** [comment]
QEMU version is now updated to 5.0.0 and FTL patches were ported on top. All machines are now using it to host VMs for tests.

This issue should not longer be occurring.
