### ISSUE TITLE
NVMf: Initiator should not require DPDK PCI probing and memory mappings

### ISSUE THREAD

**Issue by PepperJo** [spdk/spdk#135]
An application that only uses the RDMA transport should not require DPDK to initialize PCI, i.e. there should be an option to let `spdk_env_init` pass `--no-pci` to DPDK. It should also not require DPDK to get virtual to physical memory mapping. This would also make it much easier to run a NVMf initiator as non-root.

Thanks,
Jonas

**Comment by optimistyzy** [comment]
@PepperJo We are working on this feature according to your request.

**Comment by optimistyzy** [comment]
I think that his issue can be closed.

**Comment by PepperJo** [comment]
Thanks. Let me close it.
