### ISSUE TITLE
[iscsi_tgt_ip_migration] json error with RPC net_interface_delete_ip_address

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1353]
02:22:15	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk0.sock net_interface_delete_ip_address 1 127.0.0.2
request:
{
  "ifc_index": 1,
  "ip_address": "127.0.0.2",
  "method": "net_interface_delete_ip_address",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "IP address 127.0.0.2 is not found in interface 1"
}
 02:22:15	# echo 'Ignore the failure as IP did not exist.'

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11045.html

**Comment by shuhei-matsumoto** [comment]
Hi Paul,

this looks duplicated with #1313. So close for now.
