### ISSUE TITLE
iSCSI target: segmentation fault at TAILQ_REMOVE(&conn->active_r2t_tasks) in del_connection_queued_task()

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1355]
iSCSI initiator tries to login again if the current connection is stacked. SPDK iSCSI target forces to the current connection (connection 1) to exit if an new connection (connection 2) is created by the same iSCSI initiator.

The connection 1 caused segmentation fault in the destruct path, at TAILQ_REMOVE(&conn->active_r2t_tasks) in del_connection_queued_task().

This issue has occurred only when multi CPU cores are assigned to the SPDK iSCSI target.

## Expected Behavior

The connection 1 is terminated and the connection 2 completes login.

## Current Behavior

```
(gdb) bt
#0  0x000000000235d88e in del_connection_queued_task (conn=conn@entry=0x7efd2ee04000, tailq=tailq@entry=0x7efd2ee051e8, lun=lun@entry=0x0, pdu=pdu@entry=0x0) at iscsi.c:2875
#1  0x000000000235da85 in spdk_clear_all_transfer_task (conn=conn@entry=0x7efd2ee04000, lun=lun@entry=0x0, pdu=pdu@entry=0x0) at iscsi.c:2923
#2  0x0000000002356e2d in _iscsi_conn_destruct (conn=0x7efd2ee04000) at conn.c:654
#3  0x0000000002356ed4 in _iscsi_conn_check_pending_tasks (arg=0x7efd2ee04000) at conn.c:683
#4  0x000000000234f461 in spdk_thread_poll (thread=0x143e5c00, max_msgs=max_msgs@entry=0, now=now@entry=335627412506217) at thread.c:574
#5  0x00000000023943bd in _spdk_reactor_run (arg=0x143dbd40) at reactor.c:337
#6  0x0000000001ff9783 in eal_thread_loop ()
#7  0x00007f0cc0b7a70a in start_thread () from /lib64/noelision/libpthread.so.0
#8  0x00007f0cbfe1802d in clone () from /lib64/libc.so.6
(gdb) info local
task = <optimized out>
task_tmp = 0x0
pdu_tmp = <optimized out>
head = 0x7efd2ee051e8

```
## Possible Solution

https://review.spdk.io/gerrit/c/spdk/spdk/+/1930

## Steps to Reproduce

1. I/Os on a connection is starved due to heavy workload.
2. Initiator tries to login again.
3. Target forces the current connection to exit by calling iscsi_drop_conns().
4. The connection starts to terminate. Then gets segmentation fault.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.01
Multiple CPU cores are allocated to the iSCSI target.

**Comment by optimistyzy** [comment]
@shuhei-matsumoto  We can close this issue since the patch you submitted is already merged.
