### ISSUE TITLE
[test/vmd] examples/identify issues with VMD

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1360]
First of all: sorry for quite general title but I wasn't sure how to phrase that. Feel free to change it.

I have problems with running nvme tests (test/nvme) with NVMe drives on PCI slots which are part of VMD configuration, but the VMD subsystem is not enabled when running the test. Reproduction steps will clarify.

## Current Behavior

Cannot use NVMe drives which are patr of VMD when they are bound to uio/vfio.

## Expected Behavior

examples/identify should work the same as in case of non-VMD NVMes?

## Steps to Reproduce

1. Have a VMD-enabled system and insert NVMes into VMD-enabled PCI lanes.
2. Run spdk/scripts/setup.sh, but without PCI_WHITELIST for VMD subsystem. The result should be similar to:
```
[sys_sgci@WolfPass4 spdk]$ sudo scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB      512 /    512
node1   1048576kB        0 /      0
node1      2048kB      512 /    512

NVMe devices
BDF             Vendor  Device  NUMA    Driver          Device name
0000:d8:00.0    8086    0a54    1       uio_pci_generic         -
0000:d9:00.0    8086    0a54    1       uio_pci_generic         -
10000:01:00.0   8086    0a54    0       uio_pci_generic         -
10000:02:00.0   8086    0a54    0       uio_pci_generic         -

I/OAT DMA
BDF             Vendor  Device  NUMA    Driver
0000:00:04.0    8086    2021    0       uio_pci_generic
0000:00:04.1    8086    2021    0       uio_pci_generic
0000:00:04.2    8086    2021    0       uio_pci_generic
0000:00:04.3    8086    2021    0       uio_pci_generic
0000:00:04.4    8086    2021    0       uio_pci_generic
0000:00:04.5    8086    2021    0       uio_pci_generic
0000:00:04.6    8086    2021    0       uio_pci_generic
0000:00:04.7    8086    2021    0       uio_pci_generic
0000:80:04.0    8086    2021    1       uio_pci_generic
0000:80:04.1    8086    2021    1       uio_pci_generic
0000:80:04.2    8086    2021    1       uio_pci_generic
0000:80:04.3    8086    2021    1       uio_pci_generic
0000:80:04.4    8086    2021    1       uio_pci_generic
0000:80:04.5    8086    2021    1       uio_pci_generic
0000:80:04.6    8086    2021    1       uio_pci_generic
0000:80:04.7    8086    2021    1       uio_pci_generic

virtio
BDF             Vendor  Device  NUMA    Driver          Device name
VMD
BDF             Numa Node       Driver Name
0000:5d:05.5    0               vmd
```

3. Try to run test/nvme/nvme.sh. It will fail on "identify" example.
```
[sys_sgci@WolfPass4 spdk]$ sudo examples/nvme/identify/identify -i 0 -r 'trtype:PCIe traddr:10000:01:00.0'
Starting SPDK v20.04-pre git sha1 9ba80de0d / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: identify -c 0x1 -n 1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: failed to parse device "pci:10000:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 606:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 726:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed
```

4. Interestingly - fio with nvme plugin works.
```
[sys_sgci@WolfPass4 spdk]$ sudo -E LD_PRELOAD=/home/sys_sgci/spdk/examples/nvme/fio_plugin/fio_plugin /usr/src/fio/fio /home/sys_sgci/spdk/test/vmd/config/config.fio --filename="trtype=PCIe traddr=10000.01.00.0 ns=1"
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
fio-3.3
Starting 1 thread
Starting SPDK v20.04-pre git sha1 9ba80de0d / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid3999 ]
EAL: No available hugepages reported in hugepages-1048576kB
Jobs: 1 (f=1): [f(1)][-.-%][r=451MiB/s,w=452MiB/s][r=115k,w=116k IOPS][eta 00m:00s]

[...]

Run status group 0 (all jobs):
   READ: bw=454MiB/s (476MB/s), 454MiB/s-454MiB/s (476MB/s-476MB/s), io=908MiB (952MB), run=2001-2001msec
  WRITE: bw=454MiB/s (476MB/s), 454MiB/s-454MiB/s (476MB/s-476MB/s), io=908MiB (952MB), run=2001-2001msec
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK 9ba80de0dd1ff42ae70fc9fea9d33f67be78d7ea
Fedora 30 5.5.10-100.fc30.x86_64 , gcc version 9.2.1 20190827
All disks are SSDPE2KX010T8 (p4510 1.0TB 2,5")

**Comment by karlatec** [comment]
I just tried the same steps but with VFIO instead.

There's a difference how disks are bound to userspace driver:
```
NVMe devices
BDF             Vendor  Device  NUMA    Driver          Device name
0000:d8:00.0    8086    0a54    1       vfio-pci                -
0000:d9:00.0    8086    0a54    1       vfio-pci                -
10000:01:00.0   8086    0a54    0       -               -
10000:02:00.0   8086    0a54    0       -               -
```
So NVMes on "VMD lanes" are not actually bound, so there's no surprise now in examples/idenfity not working in this case:
```
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL: failed to parse device "pci:10000:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 606:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 726:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed
```

fio-nvme doesn't work anymore:
```
[sys_sgci@WolfPass4 spdk]$ sudo -E LD_PRELOAD=/home/sys_sgci/spdk/examples/nvme/fio_plugin/fio_plugin /usr/src/fio/fio /home/sys_sgci/spdk/test/vmd/config/config.fio --filename="trtype=PCIe traddr=10000.01.00.0 ns=1"
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
fio-3.3
Starting 1 thread
Starting SPDK v20.04-pre git sha1 9ba80de0d / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid6558 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)
EAL: failed to parse device "pci:10000:01:00.0"
EAL: Failed to attach device on primary process
nvme.c: 606:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 683:spdk_nvme_probe: *ERROR*: Create probe context failed
fio_plugin.c: 473:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
test: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:953, func=total_file_size, error=Invalid argument
```

**Comment by tomzawadzki** [comment]
[Bug scrub] There can be two issues here. 1) with the tests scripts 2) with VMD driver.
@karlatec will follow up on this issue.

**Comment by karlatec** [comment]
Talked with Wojeciech about this.
First of all - this is supposed to use uio_pci_generic, so that leaves vfio-pci out of the picture.
Second - binding NVMe disks which belong to VMD controller is not 100% correct and should probably be not done. (Even though test/nvme/nvme.sh will pass if identify is run with -V option)

Overall I think scripts/setup.sh should ignore NVMe disks which are a part of VMD if we're not using PCI_WHITELIST to also bind the VMD controller at the same time. This would ensure that these disks are not accidentally used in other tests (like vhost or nvmf) where apps are not able to construct a NVMe bdev with these "long" emulated BDF adresses.

**Comment by darsto** [comment]
VMD with VFIO will not work because the VMD controller itself shares an IOMMU group with its downstream ports. In order to use VFIO on one device you need to bind all devices within the IOMMU group to VFIO. Binding the controller to VFIO makes all the "virtual" pci devices starting with 10000: disappear from the system, so the only way to use VMD with VFIO is the SPDK VMD driver.

It doesn't work VFIO/IOMMU groups because the system can't properly isolate DMA e.g. from one downstream device to the kernel-bound VMD controller, hence allowing data corruption. UIO doesn't check any of that and it should be able to use it this case, but apparently DPDK can't handle
5-character PCI domain:
`EAL: failed to parse device "pci:10000:01:00.0"`

Which is a bug, I might try to send a patch to DPDK. There's a few ways to attach a device in DPDK and apparently one is broken.

**Comment by karlatec** [comment]
@darsto yes, that's true, but there's a separate problem when using uio.
If you don't bind the VMD controller to UIO then you still can bind "10000:" nvmes to userspace indepentently. Which will make some of our tests fail, because apps can't deal with "10000:" BDFs.
In that case shouldn't we ignore these NVMe drives (in setup.sh for example) so that they don't affect the tests?

**Comment by darsto** [comment]
I would say no - trying to be smart in scripts often doesn't work out. I would let people bind everything and see the spdk apps fail afterwards. And CI has some hardcoded requirements for NVMe drives anyway.

**Comment by karlatec** [comment]
Well, that's a bit problematic for CI scaling then. This problem makes any test platform with VMD enabled almost exclusive for VMD tests.
You won't be able to run test/nvme or test/vhost because it will fail due to the problem I described in previous comment.

**Comment by darsto** [comment]
> Well, that's a bit problematic for CI scaling then.

True that. Hm.

> > And CI has some hardcoded requirements for NVMe drives anyway.
> 
> Uh... specifically? :P

Some tests require 1 NVMe, some require two. If you don't have enough you get a failure in the middle of a script because "Nvme1" just doesn't exist.

**Comment by karlatec** [comment]
> Some tests require 1 NVMe,

Well this  was a hard requirement from day 1, so I don't consired that a "CI hardcoded requirement".

> some require two

TBH I don't recall them. Any examples?

> True that. Hm.

I'll create a patch with "trying to be smart in scripts". Let's see how will that work :P

**Comment by jimharris** [comment]
If there are apps that can't handle 5 digit PCI domains, we need to fix those apps.  Can you provide specifics on which apps fail and why?

**Comment by karlatec** [comment]
Here's an attempt on "trying to be smart":) https://review.spdk.io/gerrit/c/spdk/spdk/+/2203

`identify` test fails, but can be eaisly fixed by an "if" and adding a -V option.
I'm pretty sure that I saw vhost failing on bdev_attach_controller.
I can look for the places in tests where this fails if you'd like me to.

**Comment by darsto** [comment]
> If there are apps that can't handle 5 digit PCI domains, we need to fix those apps. Can you provide specifics on which apps fail and why?

I just submitted one fix to DPDK: http://patches.dpdk.org/patch/70110/

There might be more bugs with 5-digit PCI domains, but I don't have any VMD to test it.

**Comment by tomzawadzki** [comment]
[Bug scrub] @darsto Can you please verify the status of the patch on DPDK and check if our submodule includes that ? If so, then this issue could be closed.

**Comment by jimharris** [comment]
@karlatec @tomzawadzki could someone there retest with latest master?  Patch from @darsto was merged in DPDK as commit 26cfc20fe back in May so was part of DPDK 20.05 release.  This is now part of our submodule.

**Comment by changpe1** [comment]
@ChengqiangMeng Hi chengqiang, can you retest this issue? I think this issue should be fixed for now, you can try bind NVMe devices to uio and vfio driver respectively.

**Comment by ChengqiangMeng** [comment]
@changpe1 Ok, I will retest it as soon as possible.

**Comment by ChengqiangMeng** [comment]
@changpe1 
Hi Changpeng,
  I successfully retested them with the latest version of the code when they are bound to uio/vfio, and I think the bug had been fixed.
When not using PCI_ALLOWED will not bind VMD to uio/vfio.

steps:
1. test identify:
    a. ` ./configure --with-fio=/usr/src/fio  && make -j`
    b. `PCI_ALLOWED="0000:17:05.5 0000:5d:05.5 0000:85:05.5  0000:ae:05.5 0000:d7:05.5" ./scripts/setup.sh`
    c. Test idetify:
```
[root@waikikibeach38 spdk]# ./build/examples/lsvmd
[2021-05-13 11:09:42.140695] Starting SPDK v21.07-pre git sha1 be6a01efb / DPDK 20.11.0 initialization...
[2021-05-13 11:09:42.140857] [ DPDK EAL parameters: [2021-05-13 11:09:42.140887] lsvmd [2021-05-13 11:09:42.140909] -- no-shconf [2021-05-13 11:09:42.140930] -c 0x1 [2021-05-13 11:09:42.140950] --log-level=lib.eal:6 [2021-05-13 11:09:42.140971] --log-level=lib.cryptodev:5 [2021-05-13 11:09:42.140993] --log-level=user1:6 [2021-05-13 11:09:42.141014] --base-virtaddr=0x200000000000 [2021-05-13 11:09:42.141034] --match-allocations [2021-05-13 11:09:42.141055] --file-prefix=spdk_pid519024 [2021-05-13 11:09:42.141076] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
5d0505:01:00.0
d70505:01:00.0
```
`./build/examples/identify -i 0 -r 'trtype:PCIe traddr:5d0505:01:00.0' -V`    Pass.

2.  Then test it with fio:
```
[root@waikikibeach38 spdk]# LD_PRELOAD=./build/fio/spdk_nvme /usr/src/fio/fio ./test/vmd/config/config.fio --filename="trtype=PCIe traddr=5d0505.01.00.0 ns=1"
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=128
fio-3.26-31-g5592
Starting 1 thread
[2021-05-13 11:02:44.597932] Starting SPDK v21.07-pre git sha1 be6a01efb / DPDK 20.11.0 initialization...
[2021-05-13 11:02:44.597983] [ DPDK EAL parameters: [2021-05-13 11:02:44.597994] fio [2021-05-13 11:02:44.598003] --no-shconf [2021-05-13 11:02:44.598011] -c 0x1 [2021-05-13 11:02:44.598020] -m 0 [2021-05-13 11:02:44.598027] --log-level=lib.eal:6 [2021-05-13 11:02:44.598035] --log-level=lib.cryptodev:5 [2021-05-13 11:02:44.598043] --log-level=user1:6 [2021-05-13 11:02:44.598051] --base-virtaddr=0x200000000000 [2021-05-13 11:02:44.598059] --match-allocations [2021-05-13 11:02:44.598067] --file-prefix=spdk_pid516409 [2021-05-13 11:02:44.598076] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
Jobs: 1 (f=0): [f(1)][-.-%][r=15.1MiB/s,w=14.7MiB/s][r=3864,w=3772 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=516516: Thu May 13 11:02:48 2021
  read: IOPS=108k, BW=422MiB/s (443MB/s)(845MiB/2001msec)
    slat (nsec): min=90, max=15748, avg=98.49, stdev=71.78
    clat (usec): min=56, max=4460, avg=723.82, stdev=235.77
     lat (usec): min=56, max=4460, avg=723.91, stdev=235.77
    clat percentiles (usec):
     |  1.00th=[  334],  5.00th=[  429], 10.00th=[  482], 20.00th=[  553],
     | 30.00th=[  603], 40.00th=[  660], 50.00th=[  709], 60.00th=[  758],
     | 70.00th=[  807], 80.00th=[  873], 90.00th=[  963], 95.00th=[ 1037],
     | 99.00th=[ 1401], 99.50th=[ 1942], 99.90th=[ 2966], 99.95th=[ 3261],
     | 99.99th=[ 3621]
   bw (  KiB/s): min=424136, max=432976, per=99.29%, avg=429330.67, stdev=4619.17, samples=3
   iops        : min=106034, max=108244, avg=107332.67, stdev=1154.79, samples=3
  write: IOPS=108k, BW=422MiB/s (443MB/s)(845MiB/2001msec); 0 zone resets
    slat (usec): min=6, max=1031, avg= 6.95, stdev= 2.36
    clat (usec): min=6, max=2167, avg=444.42, stdev=120.49
     lat (usec): min=13, max=2174, avg=451.37, stdev=120.45
    clat percentiles (usec):
     |  1.00th=[  194],  5.00th=[  262], 10.00th=[  297], 20.00th=[  343],
     | 30.00th=[  383], 40.00th=[  416], 50.00th=[  449], 60.00th=[  482],
     | 70.00th=[  510], 80.00th=[  537], 90.00th=[  578], 95.00th=[  611],
     | 99.00th=[  676], 99.50th=[  734], 99.90th=[ 1582], 99.95th=[ 1795],
     | 99.99th=[ 2024]
   bw (  KiB/s): min=422712, max=433080, per=99.37%, avg=429461.33, stdev=5850.18, samples=3
   iops        : min=105678, max=108270, avg=107365.33, stdev=1462.55, samples=3
  lat (usec)   : 10=0.01%, 20=0.01%, 50=0.01%, 100=0.05%, 250=2.02%
  lat (usec)   : 500=37.54%, 750=39.49%, 1000=17.30%
  lat (msec)   : 2=3.35%, 4=0.24%, 10=0.01%
  cpu          : usr=98.80%, sys=1.05%, ctx=2, majf=0, minf=17223
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=216298,216200,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128

Run status group 0 (all jobs):
   READ: bw=422MiB/s (443MB/s), 422MiB/s-422MiB/s (443MB/s-443MB/s), io=845MiB (886MB), run=2001-2001msec
  WRITE: bw=422MiB/s (443MB/s), 422MiB/s-422MiB/s (443MB/s-443MB/s), io=845MiB (886MB), run=2001-2001msec
```

**Comment by changpe1** [comment]
Thanks @ChengqiangMeng, closing this issue for now.
