### ISSUE TITLE
spdk_nvme_connect() - ctrlr_opts is not ABI friendly

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1364]
ctrlr_opts structure is supposed to support apps built against older versions of this structure to be linked with newer versions of the nvme library that may have extended ctrlr_opts

but spdk_nvme_connect() clearly just returns an error if the current size (sizeof(*opts)) does not match the caller's size (opts_size).

we need to add an opts_size to the ctrlr_opts to handle this case

please - whoever works on this bug, let's add some good unit tests

**Comment by optimistyzy** [comment]
@jimharris  I will  work on this, so if we add opt_size in the structure, I think that the parameter of opts_size should be removed. But if remove this parameter in this function, will cause ABI not compatiable.

**Comment by optimistyzy** [comment]
And also see the following two patches: 

 https://review.spdk.io/gerrit/c/spdk/spdk/+/1996
 https://review.spdk.io/gerrit/c/spdk/spdk/+/1992

It just removes the opts_size in spdk_nvme_ctrlr_get_default_opts and spdk_nvme_connect, but breaks the ABI.  But definitely, we can still keep this parameter.

**Comment by optimistyzy** [comment]
Close this issue, since the following patch is merged: https://review.spdk.io/gerrit/c/spdk/spdk/+/1998
