### ISSUE TITLE
[*] Build timed out without reaching 15 minute mark

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1365]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/11506/archive/iscsi-autotest/build.log

## Execution failed at
First timing in log:
```
00:55:41	$ xtrace_enable
```

Failure point:
```
 01:04:01	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py iscsi_create_portal_group 1 10.0.0.1:3260
Build timed out (after 15 minutes). Marking the build as failed.
Build was aborted
[PostBuildScript] - [INFO] Executing post build scripts.
[iscsi-autotest] $ /usr/bin/env bash /tmp/jenkins8111273161245568858.sh
 01:04:01	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py iscsi_create_initiator_group 2 ANY 10.0.0.2/32
```

**Comment by tomzawadzki** [comment]
@karlatec Is there a way to narrow down there the remaining test time went ? As in timing logs for things like git clone etc ?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_11491.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_11506.html

**Comment by jimharris** [comment]
Looking at the log in Jenkins, which also shows the timestamps for cloning, etc.:

13:44:32 Success build forhudson.tasks.Shell@4a492dd8
13:44:32 provisioning config files...
13:44:32 copy managed file [copy_or_clone] to file:/var/jenkins/workspace/iscsi-autotest/copy_or_clone.sh
13:44:32 [iscsi-autotest] $ /usr/bin/env bash /tmp/jenkins483427499330491817.sh
13:44:32 MANUAL, will clone
13:44:32 Cloning into '/var/jenkins/workspace/iscsi-autotest/spdk'...
13:44:36 warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
13:49:19 git version 2.21.1
13:49:26 warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
13:51:01 remote: Counting objects: 1           
remote: Counting objects: 49, done        
13:51:01 remote: Finding sources:   2% (1/34)           
remote: Finding sources:   5% (2/34)           

This indicates a 6+ minute delay between when we tried to start cloning, and then actually making progress.

This was from the 11506 failure.

**Comment by jimharris** [comment]
Similar for 11491:

12:14:26 Pre-SCM step. Deleting whole workspace.
12:14:27 Success build forhudson.tasks.Shell@4a492dd8
12:14:27 provisioning config files...
12:14:27 copy managed file [copy_or_clone] to file:/var/jenkins/workspace/iscsi-autotest/copy_or_clone.sh
12:14:27 [iscsi-autotest] $ /usr/bin/env bash /tmp/jenkins2798824265069264096.sh
12:14:27 MANUAL, will clone
12:14:27 Cloning into '/var/jenkins/workspace/iscsi-autotest/spdk'...
12:14:30 warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
12:16:31 git version 2.21.1
12:16:34 warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
12:17:51 remote: Counting objects: 1           
remote: Counting objects: 43           
remote: Counting objects: 69, done        
12:17:55 remote: Finding sources:   1% (1/52)           

The delay wasn't as long, but this still seems to have triggered the 15 minute timeout (the timer starts when Jenkins starts the job, not when Jenkins calls autotest.sh)

**Comment by jimharris** [comment]
Both of these failures were on GP_RED.  I checked iscsi_autotest on a different job which ran on GP2 - in that case, the delay was much shorter when cloning, and did not show anything about counting objects or finding sources on the remote.

Could this be a configuration problem on GP_RED?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_11646.html

**Comment by jimharris** [comment]
11646 was also on GP_RED.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_11659.html

**Comment by jimharris** [comment]
11659 was also on GP_RED.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_11730.html

**Comment by karlatec** [comment]
Updated local mirror repos on systems, so there should be less to fetch now. Let's see if that helps

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_13117.html

**Comment by changpe1** [comment]
> Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_13117.html

This failure is on GP1.

**Comment by optimistyzy** [comment]
Close this issue, because there is no same issue reported in about one month. If there is new report of such failure, Let's open it again.
