### ISSUE TITLE
NVMe-oF TCP failure (nvmf_shutdown_tc2)

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1366]
The test should  pass.

It fails. See this log: https://ci.spdk.io/results/autotest-per-patch/builds/11591/archive/nvmf-tcp-autotest/build.log

## Steps to Reproduce

1.
2.
3.
4.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_11591.html

**Comment by optimistyzy** [comment]
Maybe the issue is that I did not rebase my patch with the master. But I also see several patches executed before my patch also failed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_12146.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_12107.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_13790.html

**Comment by tomzawadzki** [comment]
The original failure was within `nvmf_shutdown_tc2` case. Last three reports are not within this test case, but different ones. Closing this issue since the logs are unrelated and if they were to be resolved, separate issue (more accurate) would need to be opened.
