### ISSUE TITLE
spdk_top - sorting issue with numeric values

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1367]
`SPDK: v20.01-rc1-932-g0b9b70d0f`

Two issues:

1) It's not clear what order is being used for sorting columns which hold numeric values. E.g., for `Core` column in `Threads` tab, sorting seem to be in ascending order:
```
0
0
1
1
...
```
However,  if sorting is switched to, e.g., `Active pollers`, which is also represented in numeric form, the output looks like so:
```
1
1
1
0
0
...
```
So this puts all the threads with > 0 active pollers at the top, which may be fine, but in context of sorting the actual values it's not really consistent.

2) Order of the rows is not updated when values change

If sort is done based on values which dynamically change during every poll, placement of the rows is not being adjusted. For instance, `Busy [us]` in the `Threads` tab:
```
reactor_2 79 
reactor_1 60
reactor_0 57
```
If `reactor_2`'s value goes below `reactor_1`s, these two rows remain at their old positions, instead of being moved:
```
reactor_1 61
reactor_2 50
reactor_0 40
```
That said, it doesn't seem that any sorting is applied for similar columns. This is how a single snapshot of ``Busy [us]` sorting looks like:
```
78
79
78
79
78 
79
78
78
76
60
60
60
61
60
61
59      
```
If there's any rule behind it, I can't see it. :)

**Comment by Maciej-Szwed** [comment]
Add 1. Sorting is done in a such way that more interesting data lands on top (more runs, longer time, first cores, etc)
Add 2. This is a bug - fix is here: https://review.spdk.io/gerrit/c/spdk/spdk/+/1999

**Comment by mikeBashStuff** [comment]
>Add 1. Sorting is done in a such way that more interesting data lands on top (more runs, longer time, first cores, etc)

I think it would be nice if this was mentioned in some way in the README then. :)

**Comment by jimharris** [comment]
The patch seems fine to me.  @mikeBashStuff - could you pull the patch and confirm it fixes the sorting as intended?

I think @mikeBashStuff was also suggesting a bit longer explanation in the README on how the sorting works, I wouldn't be opposed to that either.

**Comment by mikeBashStuff** [comment]
@jimharris Already done that - all seems to be working fine with the patch in place. :)
