### ISSUE TITLE
unittest failed without idxd_ut

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1369]
# Issue：
git submodule update --init
./configure  --with-ocf --without-isal
make  -j10
./test/unit/unittest.sh
"
 23:55:37       # /home/storage/spdk/test/unit/lib/idxd/idxd.c/idxd_ut
/home/storage/spdk/test/common/autotest_common.sh: line 758: /home/storage/spdk/test/unit/lib/idxd/idxd.c/idxd_ut: No such file or directory
  23:55:37      # trap - ERR
  23:55:37      # print_backtrace
  23:55:37      # [[ ehxBET =~ e ]]
  23:55:37      # args=("${BASH_ARGV[@]}")
  23:55:37      # local args
"
There should be a switch to control idxd in our test .
If add a switch, that may be need to change a lot including test pool.
our need to config the module =y as default for now?

**Comment by tomzawadzki** [comment]
Please see fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/2012
