### ISSUE TITLE
spdk can't find installed dpdk libraries (in lib64)

### ISSUE THREAD

**Issue by jlefley** [spdk/spdk#137]
After running ```make install ``` for dpdk on CentOS, the dpdk libraries are installed in ```/usr/local/lib64``` (standard CentOS/RHEL convention). ```lib/env_dpdk/env.mk``` has lib (without 64 suffix) hard coded and as a result calling make in an attempt to build SPDK fails:

```
$ make DPDK_DIR=/usr/local
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all'.
make[4]: *** No rule to make target `/usr/local/lib/librte_eal.so', needed by `bdevio'.  Stop.
make[3]: *** [bdevio] Error 2
make[2]: *** [bdev] Error 2
make[1]: *** [lib] Error 2
make: *** [test] Error 2
```

**Comment by dverkamp-intel** [comment]
DPDK_DIR should be pointed to the DPDK SDK directory, e.g. /usr/local/share/dpdk/x86_64-default-linuxapp-gcc in your case. Does this resolve your build problems?

We should probably have better documentation for DPDK_DIR - we can keep this issue open to track that.

**Comment by jlefley** [comment]
OK I looked back at how I installed DPDK and I specified ```--prefix=/usr/local``` and  ```---libdir=/usr/local/lib64``` to follow the CentOS convention when configuring DPDK. So I suppose this is non standard according to the SPDK build procedure, however it does follow Linux conventions.

Typically most libraries I build have support in their configure script for a ```libdir``` option that allows customization of the library installation target directory and then dependents might use a pkgconfig script to locate the libraries of a dependency.

This issue seems like an edge case given how most people seem to install SPDK and DPDK, so not a major problem - I can easily work around this for now.

Thanks

**Comment by benlwalker** [comment]
Until very recently, DPDK and SPDK were not packaged for distribution, so they generally weren't "installed" on a Linux distro. However, DPDK has changed considerably such that it is packaged on a number of distros and has all of the expected installation behaviors. SPDK now needs to do two things:

1) Support a "packaged" or "installed" DPDK instead of the one from the git repository. This means supporting all of the various configurable paths and pkconfig scripts, etc.
2) Add support for installing SPDK onto a system, with all of the associated configuration and packaging support that entails.

I'm going to flag this issue as an enhancement request to add all of this behavior and use it to track progress.

**Comment by yrashk** [comment]
I'm developing a Rust binding for SPDK and it's very valuable to be able to
build the package without requiring anything to be installed on the build
host.

Are you considering leaving that option open, so that my build script can
still fetch DPDK locally and link statically against it?

Thanks!

**Comment by benlwalker** [comment]
Absolutely - I often find myself modifying both SPDK and DPDK source, so it is critical to my workflow as well.

I'm a huge fan of Rust and I've been hoping that someone would write a binding and tie it into tokio. I considered doing it myself as a way to force myself to really learn Rust at a deeper level but I haven't yet had time. Keep us updated on your work.

**Comment by yrashk** [comment]
I will. It's already functional (NVMe probing, attaching, writing and
reading) but not complete API bindings wise. I'm hoping to publish the
first snapshot in the next few days or so.

At this layer I'm not tying it into Tokio; but I think it'll be doable

**Comment by yrashk** [comment]
Ben, I just published first draft of the Rust bindings. They are imperfect and incomplete but it's a start.

Here is the repo: https://github.com/PumpkinDB/rust-spdk

**Comment by dverkamp-intel** [comment]
I think the original bug here was just a misconfiguration - the DPDK path must be configured to point at the SDK directory, and the configure --help output clarifies that now (this didn't exist when the original issue was filed).

If any more fixes are required, please open a new issue.
