### ISSUE TITLE
[autobuild.sh] external_run_tc1 fails due to lack of hugepages

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1370]
## Current Behavior

I have a fresh OS installation (well, VM actually) which does not have any hugepage options set Grub options, so nothing is allocated at boot time.
Because of that autobuild.sh (run as part of autorun.sh script) fails at external_run_tc1 test which needs hugepages to run SPDK hello_bdev app.

## Expected Behavior

autobuild.sh should pass.

## Possible Solution

autobuild.sh now depends on hugepage allocation and does not run setup.sh This is done in autotest.sh which is run after autobuild.sh.
Couple possible solutions here:
a) move "external" tests from autobuild.sh to autotest.sh in order to execute them after setup.sh
b) call setup.sh in autobuild.sh
c) resolve by documentation - mention in getting_started.md and/or vm_setup.sh that system needs to be provision to allocate hugepages at boot time.

## Steps to Reproduce

1. Run spdk/autorun.sh with config:
```
SPDK_RUN_VALGRIND=1
SPDK_RUN_FUNCTIONAL_TEST=0
SPDK_TEST_AUTOBUILD=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_PMDK=1
SPDK_TEST_ISAL=1
SPDK_TEST_REDUCE=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_FTL=1
SPDK_TEST_OCF=1
SPDK_TEST_RAID5=1
SPDK_TEST_RBD=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK 55fe098f9d0c51bc2a02e85e6b256dcb7cb03636
FYI: this does not happen on CI VMs, because grub options for HP allocation are set

**Comment by karlatec** [comment]
@Seth5141 assigning to you so you can take a look. Feel free to re-assign to me and I can take care of the fix, just point me into a right direction based one of "Possible solutions" ;)

**Comment by Seth5141** [comment]
Hi Karol,

I think that I am going to add a call to setup.sh to the external test case. But if I recall correctly, there were problems with the whitelist parameter, so I may need to add a HUGEPAGES_ONLY parameter. Stay tuned for a couple of patches.

**Comment by Seth5141** [comment]
Actually @karlatec turns out we already have that. You can just set PCI_WHITELIST to a garbage value.

https://review.spdk.io/gerrit/c/spdk/spdk/+/2141

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/2141 is now merged.
