### ISSUE TITLE
identify EAL: Failed to hotplug remove device

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1372]
Hi：

SPDK v20.01
DPDK 19.11.0

./app/vhost/vhost -c /etc/spdk/spdk.conf -i 0 -s 1024
and ./examples/nvme/identify/identify -i 0

At the end of the identify cmd, the message is:
EAL: Failed to hotplug remove device

And the vhost app will print:
EAL: Driver cannot detach the device (0000:d9:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Driver cannot detach the device (0000:da:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Driver cannot detach the device (0000:db:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Driver cannot detach the device (0000:d8:00.0)
EAL: Failed to hotplug remove device on primary

![image](https://user-images.githubusercontent.com/15990748/80308058-6a6a8f00-87ff-11ea-9713-d0d4bf4994ce.png)
![image](https://user-images.githubusercontent.com/15990748/80308063-70607000-87ff-11ea-85ac-93c6730a2de5.png)

Is there any problem with the parameter setting? What is needed to support hotplug?

Thanks
      Su

**Comment by changpe1** [comment]
This only happens with multiple-process scenario, because the physical NVMe controller is hold by the primary process, so DPDK print this log, it doesn't have any other effect with normal usage, just an error log information.

**Comment by zlsh007** [comment]
Okay thank you！
