### ISSUE TITLE
[END TEST nvmf_identify_passthru] Failure description

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1374]
Looks like this is coming after the test as part of cleanup maybe?

Core was generated by `/var/jenkins/workspace/nvmf-tcp-autotest/spdk/test/bdev/bdevperf/bdevperf -r /v'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11946.html

**Comment by peluse** [comment]
Hmmm, this might just be in my patch series somewhere.... will see how a few re-tests go

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11949.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_11948.html

**Comment by peluse** [comment]
Comm meeting: looks like a dup of 1318
