### ISSUE TITLE
[iscsi-autotest] Build time out.

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1376]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/11964/archive/iscsi-autotest/build.log

## Execution failed at

Starting SPDK v20.04-pre git sha1 10d34d07c / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid34794 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
bdev_rbd.c: 757:spdk_bdev_rbd_create: *NOTICE*: Add Ceph0 rbd disk to lun
EAL: pthread_setaffinity_np failed
Build timed out (after 15 minutes). Marking the build as failed.
Build was aborted
[PostBuildScript] - [INFO] Executing post build scripts.
[iscsi-autotest] $ /usr/bin/env bash /tmp/jenkins8721630322795047996.sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_11964.html

**Comment by changpe1** [comment]
Same with issue #1365 , so closing this issue for now.
