### ISSUE TITLE
The parameter max_qpairs_per_ctrlr is misleading

### ISSUE THREAD

**Issue by liu-wenhua** [spdk/spdk#1378]
I have posted this issue in SPDK mailing list and was suggested by Ziye Yang to open a bug here.

When creating nvmf transport using command “rpc.py nvmf_create_transport”, there is a parameter max_qpairs_per_ctrlr. It means number of IO queues plus admin queue per controller. But when people talk about number of queues, usually it means number of IO queues. When someone creates nvmf transport, if he/she knows what max_qpairs_per_ctrlr mean and wants to have 8 IO queues, he/she will set this parameter to 9. If given 8, he/she will get only 7 IO queues.

In the worst case, if someone gives one to this parameter, he won’t get any IO queue !!!

## Possible Solution

I would suggest SPDK NVMF target changes the definition of this parameter and treat it as number of IO queues. Internally, SPDK should allow one extra qpair be created for admin queue.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomzawadzki** [comment]
[Bug scrub] The `max_qpairs_per_ctrlr` is confusing to the users, and should be deprecated in favor of `max_io_qpairs_per_ctrlr`.

**Comment by optimistyzy** [comment]
@liu-wenhua  https://review.spdk.io/gerrit/c/spdk/spdk/+/2714  Could you see this patch satisfy your requirements?  It let users to configure max io qpairs. Definitely, if users pass 0, we will only create 1 admin qpair.  
I checked the code, I will not suggest change  max_qpairs_per_ctrlr in our code, since it will break SPDK API.

**Comment by optimistyzy** [comment]
@liu-wenhua  Another patch is merged, please see this commit in the master:

 1551197db51aca1dc51ed866e5227f5c26927ed2
