### ISSUE TITLE
[./scripts/setup.sh fail] Caused by Memory fragmentation

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1382]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/12432/archive/unittest-autotest/build.log

## Execution failed at

00:09:20.330  0000:00:09.0 (8086 5845): Skipping un-whitelisted NVMe controller at 0000:00:09.0
00:09:20.336  0000:00:0c.0 (8086 5845): Skipping un-whitelisted NVMe controller at 0000:00:0c.0
00:09:20.341  0000:00:0d.0 (8086 5845): Skipping un-whitelisted NVMe controller at 0000:00:0d.0
00:09:20.463  0000:00:0e.0 (1d1d 1f1f): nvme -> pci-stub
00:09:21.430  0000:00:0b.0 (1af4 1001): Skipping un-whitelisted Virtio device at 0000:00:0b.0
00:09:21.451  0000:00:0a.0 (1af4 1004): Skipping un-whitelisted Virtio device at 0000:00:0a.0
00:09:21.549  
00:09:21.549  ## ERROR: requested 4096 hugepages but only 3827 could be allocated.
00:09:21.549  ## Memory might be heavily fragmented. Please try flushing the system cache, or reboot the machine.
00:09:21.550    07:05:01	# trap - ERR
00:09:21.551    07:05:01	# print_backtrace
00:09:21.551    07:05:01	# [[ ehxBET =~ e ]]
00:09:21.551    07:05:01	# args=("${BASH_ARGV[@]}")
00:09:21.552    07:05:01	# local args
00:09:21.552    07:05:01	# xtrace_disable
00:09:21.552    07:05:01	# '[' no '!=' yes ']'
00:09:21.553    07:05:01	# PREV_BASH_OPTS=ehxBET
00:09:21.553    07:05:01	# [[ ehxBET == *\x* ]]
00:09:21.553    07:05:01	# XTRACE_DISABLED=yes
00:09:21.553    07:05:01	# set +x
00:09:21.553  ========== Backtrace start: ==========
00:09:21.553  
00:09:21.566  in /var/jenkins/workspace/unittest-autotest/spdk/autotest.sh:100 -> main(["/home/sys_sgci/autorun-spdk.conf"])
00:09:21.566       ...
00:09:21.566     95  		# Now, bind blacklisted devices to pci-stub module. This will prevent
00:09:21.566     96  		# automatic grabbing these devices when we add device/vendor ID to
00:09:21.566     97  		# proper driver.
00:09:21.566     98  		if [[ -n "$PCI_BLACKLIST" ]]; then
00:09:21.566     99  			# shellcheck disable=SC2097,SC2098
00:09:21.566  => 100 			PCI_WHITELIST="$PCI_BLACKLIST" \
00:09:21.566     101 			PCI_BLACKLIST="" \
00:09:21.566     102 			DRIVER_OVERRIDE="pci-stub" \
00:09:21.566     103 				./scripts/setup.sh
00:09:21.566     104 	
00:09:21.566     105 			# Export our blacklist so it will take effect during next setup.sh
00:09:21.566       ...
00:09:21.567  
00:09:21.567  ========== Backtrace end ==========
00:09:21.567    07:05:01	# xtrace_enable
00:09:21.567    07:05:01	# return 0
00:09:21.568   07:05:01	# process_core
00:09:21.568   07:05:01	# ret=0
00:09:21.569   07:05:01	# IFS=
00:09:21.569   07:05:01	# read -r -d '' core
00:09:21.569    07:05:01	# find . -type f '(' -name 'core\.?[0-9]*' -o -name '*.core' ')' -print0
00:09:21.602   07:05:01	# return 0
00:09:21.602   07:05:01	# autotest_cleanup
00:09:21.603   07:05:01	# /var/jenkins/workspace/unittest-autotest/spdk/scripts/setup.sh reset
00:09:21.666  0000:00:09.0 (8086 5845): Already using the nvme driver
00:09:21.684  0000:00:0c.0 (8086 5845): Already using the nvme driver
00:09:21.704  0000:00:0d.0 (8086 5845): Already using the nvme driver
00:09:21.724  0000:00:0e.0 (1d1d 1f1f): pci-stub -> nvme
00:09:22.797  0000:00:0b.0 (1af4 1001): Already using the virtio-pci driver
00:09:22.836  0000:00:0a.0 (1af4 1004): Already using the virtio-pci driver
00:09:22.915   07:05:02	# /var/jenkins/workspace/unittest-autotest/spdk/scripts/setup.sh cleanup
00:09:22.949  ls: cannot access '/dev/shm/*': No such file or directory
00:09:22.954  Clean
00:09:22.956    07:05:02	# uname -s
00:09:22.959   07:05:02	# '[' Linux = Linux ']'
00:09:22.959   07:05:02	# grep -q '#define SPDK_CONFIG_IGB_UIO_DRIVER 1' /var/jenkins/workspace/unittest-autotest/spdk/include/spdk/config.h
00:09:22.962   07:05:02	# modprobe -r uio_pci_generic
00:09:22.987   07:05:02	# rm -rf /var/tmp/asan_suppression_file
00:09:22.990   07:05:02	# exit 1
00:09:33.007  Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
00:09:33.023  Build step 'Execute shell' marked build as failure
00:09:33.454  [PostBuildScript] - [INFO] Executing post build scripts.
00:09:33.463  [unittest-autotest] $ /usr/bin/env bash /tmp/jenkins4229057328203332337.sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_12432.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_12452.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_12457.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_12484.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_12537.html

**Comment by karlatec** [comment]
This might suggest some problem with VM host servers setup, or with the VMs themselves, but I don't recall any configuration change being done that would result in these kind of errors.
I'm even more certain of it considering that nightly tests are affected as well (https://ci.spdk.io/public_build/autotest-nightly_423.html) and I'm 200% sure that there was nothing done to nightly servers configuration.
Merging https://review.spdk.io/gerrit/c/spdk/spdk/+/2212/1 did not help.

**Comment by karlatec** [comment]
Last change which had something to do with allocating hugepages in tests was: https://review.spdk.io/gerrit/c/spdk/spdk/+/2141
@Seth5141 could this be related by any chance?

**Comment by Seth5141** [comment]
@karlatec I believe that change is what is causing the memory fragmentation issues on the guest machines. For some reason calling setup twice in the same run causes the second attempt to fail.

I have since added this change https://review.spdk.io/gerrit/c/spdk/spdk/+/2212/1 which attempts to clear the system caches before the second call to setup.sh which, I believe, has drastically reduced the number of occurrences of this failure. I have still seen it a couple of times since the change has been merged though.

I have a couple of theories. Hugepages must be automatically freed for reuse after a certain amount of time. That's why we don't have this problem on consecutive runs of the  build pool and it was only introduced when we started calling setup in both autobuild and autotest.

There is still a slight race condition between when we free the system caches and when we try to call setup.sh. It may be worthwhile to add an additional sleep there to fully fix this problem.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_12772.html

**Comment by darsto** [comment]
> For some reason calling setup twice in the same run causes the second attempt to fail.

I checked linux code and it doesn't touch any hugepages if the requested count is equal to the current hugepage count. Technically we should be able to allocate them once (on boot?) and never touch them again.

I pushed a fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/2374

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_13561.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_13602.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_13837.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_13849.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_14202.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_14211.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_14207.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_14217.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_14229.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_14249.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_14289.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_14288.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_14296.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_14292.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_14581.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_14918.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_14922.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_14920.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tkulasek. log: https://ci.spdk.io/public_build/autotest-per-patch_14906.html

**Comment by Khadem1** [comment]
rebooting the machine solved the problem at my end. 
![image](https://github.com/user-attachments/assets/bfdde72a-76f2-48e2-acd6-f22d4ada90f2)
