### ISSUE TITLE
Need SPDK CI Jenkins check older gcc version?

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1383]
I found there are lkey and rkey's warnings in compling nvme_rdma.c when gcc version is 4.8.5.

One of these warnings, such as:
```
/home/wanghailiang/spdk20200428/lib/nvme/nvme_rdma.c: In function ‘nvme_rdma_qpair_submit_request’:
/home/wanghailiang/spdk20200428/lib/nvme/nvme_rdma.c:1512:29: warning: ‘lkey’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  rdma_req->send_sgl[1].lkey = lkey;
                             ^
/home/wanghailiang/spdk20200428/lib/nvme/nvme_rdma.c:1480:11: note: ‘lkey’ was declared here
  uint32_t lkey;
           ^
```
I have raised a patch to remove this warning. Need SPDK CI Jenkins check older gcc version?

I compared some kinds of gcc/kernel, found only there is warning in gcc 4.8.5.

machine | waikikibeach51 | waikikibeach18 | waikikibeach56 | waikikibeach34
-- | -- | -- | -- | --
gcc version | 4.8.5 | 8.2.1 | 9.2.1 | 6.4.1
kernel version | 5.4.6 | 4.19.15 | 5.0.9 | 4.13.10
OS | CentOS Linux release   7.6.1810 | Fedora release 28 | Fedora release 30 | Fedora release 25
  |   |   |   |  
compile | lkey and rkey's   warning | OK | OK | OK

## Expected Behavior
There is no warning in all kinds of gcc version. (This is more idealized)

## Current Behavior
Gcc version 4.8.5 is missed in SPDK CI Jenkins.

## Possible Solution
Add some older gcc in SPDK CI Jenkins.

## Steps to Reproduce
1.cd spdk
2../configure --with-rdma --without-isal ( or other options)
3. make clean && make -j

## Context (Environment including OS version, SPDK version, etc.)
OS: CentOS   Linux release 7.6.1810
SPDK commit 01425928ed994e5cbecc0fa7425aa130d2b23597

**Comment by darsto** [comment]
Apparently we do have a CentOS 7.6 job with gcc 4.8.5 in CI, but it doesn't compile rdma.

Compiling everything on every configuration is a bit paranoid, but I think we might consider it for nightly. @wanghailiangx could you create a separate trello card for that?

**Comment by tomzawadzki** [comment]
For future readers, patch fixing this particular error was resolved in following patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/2197

**Comment by wanghailiangx** [comment]
@darsto Every time this warning appears on a physical machine with gcc version 4.8.5 and configure --with-rdma.
I noticed your mentioned machine(CentOS 7.6 job with gcc 4.8.5 in CI), we can see https://ci.spdk.io/results/autotest-nightly/builds/420/archive/centos7-nightly-autotest/build.log.
But I don't why it didn't report this waning. 
```
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
......
12:29:47	$ ./configure --enable-debug --enable-werror --enable-log-bt --with-rdma
......
 CC lib/nvme/nvme_rdma.o
```

@tomzawadzki Thank you for pasting that patch.

**Comment by changpe1** [comment]
@wanghailiangx As suggested by Darek, you can start another trello task to cover the RDMA compilation, I'm going to close this issue, as the patch was merged.
