### ISSUE TITLE
[rocksdb_insert] Failure on gzip

### ISSUE THREAD

**Issue by Donaim** [spdk/spdk#1384]
## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/12453/archive/BlobFS-autotest/build.log

## Execution failed at

```lisp
 10:34:56	# echo -n Start insert test phase...
Start insert test phase... 10:34:56	# taskset 0xFF /var/jenkins/workspace/BlobFS-autotest/spdk/../rocksdb/db_bench --flagfile=insert_flags.txt

real	0m53.587s
user	2m2.775s
sys	0m17.492s
  10:35:49	# grep /dev/shm insert_db_bench.txt
  10:35:49	# cut -f 6 -d ' '
 10:35:49	# DB_BENCH_FILE=Or
 10:35:49	# gzip Or
gzip: Or: No such file or directory
  10:35:49	# trap - ERR
  10:35:49	# print_backtrace
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Donaim. log: https://ci.spdk.io/public_build/autotest-per-patch_12453.html

**Comment by changpe1** [comment]
@Donaim I tried with your patch, actually I can reproduce this issue in my local environment, but without applying your patch, it works well for me.  I think this issue related with your patch, but I didn't find any exception with your patch.

**Comment by Donaim** [comment]
@changpe1 , yes, you are right, I investigated the root cause and it is really my patch that causes this bug. Issue is that in rocksdb test we grep logs, while my patch changes their format.
I will submit a fix today.
Closing issue because it will not reproduce without my patch
