### ISSUE TITLE
[RocksDB-SPDK] RocksDB-SPDK performs worse with large Memtable size

### ISSUE THREAD

**Issue by cighao** [spdk/spdk#1385]
After turning on`sync` , I got the worst performance when having bigger MemTable . The left figure uses a bigger Memtable size (1GB), while the right one uses the default Memtable size (64MB). If I set `sync=false`, these two configurations have similar results.
Thanks

![image](https://user-images.githubusercontent.com/10767282/81216133-16239400-8fe3-11ea-8056-6e824a0593c1.png)

**Comment by changpe1** [comment]
Did you try the same tests with kernel solution? I'm thinking this may not related with SPDK engine, maybe it's related with Rocksdb's implementation.

**Comment by cighao** [comment]
> Did you try the same tests with kernel solution? I'm thinking this may not related with SPDK engine, maybe it's related with Rocksdb's implementation.

I also test RocksDB with different memtable size. It has the similar results.

**Comment by Comphix** [comment]
After setting the "sync" to true, all writes will go to the disk, it looks like shall have similar impact to write unless there is some different handling in RocksDB.

Setting up a larger Memtable size, is for the potential better Read performance if hitting the data in Memtable?

Trying to understand these two parameters. Is this correct? @cighao 

-sync (Sync all writes to disk) type: bool default: false

**Comment by Comphix** [comment]
I've tried similar testing and configuration, for the "readseq" and "readrandom", with different Memtable size, looks like there is no obvious difference.

**Comment by cighao** [comment]
> I've tried similar testing and configuration, for the "readseq" and "readrandom", with different Memtable size, looks like there is no obvious difference.

Could you please try "fillrand"? I also compared rocksdb-spdk with vanilla rocksdb. I didn't see big difference between them when enable WAL and Fsync.

**Comment by Comphix** [comment]
"fillrandom" as documented in the issue? Yes, I've tried and I also seen the performance difference with different Memtable size. Question is that in which situation, you are going to use the 1G Memtable instead of the default 64M as it seems there is no difference for the read operations.

**Comment by cighao** [comment]
Because read operations don't need the Memtable, Memtable size has no impact on the read performance. I just tried the different Memtable sizes to see the performance difference and found that problem.  I'm very curious about why the Memtable size has such a big impact on write performance. 
I also test the read performance,  RocksDB-BlobFS is much slower than vanilla RocksDB. Is that because Linux can utilize the page cache, but BlobFS can't?

**Comment by optimistyzy** [comment]
> Because read operations don't need the Memtable, Memtable size has no impact on the read performance. I just tried the different Memtable sizes to see the performance difference and found that problem. I'm very curious about why the Memtable size has such a big impact on write performance.
> I also test the read performance, RocksDB-BlobFS is much slower than vanilla RocksDB. Is that because Linux can utilize the page cache, but BlobFS can't?

@cighao You are right for "BlobFS cannot use page cache". Blobfs is in user space, so definitely it cannot use page cache provided by kernel.

**Comment by jimharris** [comment]
BlobFS is behaving as expected here so closing this issue.  But @cighao please continue to ask questions on this thread as needed.  Thanks.
