### ISSUE TITLE
About the conflict between the identify tool and nvme_cuse

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1386]
Hi all
I tested based on the spdk V20.01 branch.
When I only test the identify tool, there is no problem, and it can return normally, but when I create a device through cuse, such as "./rpc.py bdev_nvme_cuse_register -n Nvme0", executing the identify tool again will cause a coredump problem, and I tested the first bdev_nvme_cuse_register and then bdev_nvme_cuse_unregister has no effect on identify. I tested the latest master code without this problem, I don’t know which patch fixes this problem.

1:./identify -i 0
![image](https://user-images.githubusercontent.com/15990748/81278260-03af6600-9088-11ea-802a-eff61426d93a.png)
![image](https://user-images.githubusercontent.com/15990748/81278279-09a54700-9088-11ea-91ac-0c30ec6cfbf3.png)

It seems that there is a lock. When gdb debugging identify does not exit, executing the ‘nvme smart-log /dev/spdk/nvme0’ command will also get stuck.
![image](https://user-images.githubusercontent.com/15990748/81278571-73255580-9088-11ea-952d-7992fd4994f3.png)

Does anyone know where is the problem?
Thanks！

**Comment by zlsh007** [comment]
To correct it, I repeatedly tested the master branch code, 2c0980de71e99e53ecd98c4ba2cb34486efcf53a, the same problem exists, 
1：./app/vhost/vhost -c /etc/spdk/spdk.conf -i 0 -s 1024
2：./scripts/rpc.py bdev_nvme_cuse_register -n Nvme0
3：./examples/nvme/identify/identify -i 0
will have the same problem

**Comment by Comphix** [comment]
@zlsh007 

For step 3, are you going to use identify tool to discover the Nvme0 device?

After executing the step 2, there will be the devices under /dev/spdk folder like below:

ll /dev/spdk/*
crw-------. 1 root root 509, 0 May  8 15:36 /dev/spdk/nvme0
crw-------. 1 root root 510, 0 May  8 15:36 /dev/spdk/nvme0n1

And now you can use nvme cli tool to access the device like below:
root@storage35:/spdk# nvme id-ctrl /dev/spdk/nvme0
NVME Identify Controller:
vid     : 0x8086
ssvid   : 0x8086
sn      : BTLJ72430ARH2P0BGN
mn      : INTEL SSDPE2KX020T8
fr      : VDV10110

**Comment by Comphix** [comment]
For below steps, if using (-i 0) for the multi process method, there is no need to register the cuse and just using step 1 and step 3, it shall be ok to access the same NVMe ctrlr which is already acquired by vhost application from the identify tool.

1：./app/vhost/vhost -c /etc/spdk/spdk.conf -i 0 -s 1024
2：./scripts/rpc.py bdev_nvme_cuse_register -n Nvme0
3：./examples/nvme/identify/identify -i 0

**Comment by zlsh007** [comment]
@Comphix Thank you for your reply. I want to use the identify tool to get some basic information of the disk, such as quantity, model, sn, firmware version, capacity, etc., and then use nvme smartlog to get the status information of the disk, such as life, serious failure, etc., although through Identify can also obtain similar information, but some are not convenient, I do n’t know where the two conflict

**Comment by zlsh007** [comment]
Can the nvme command obtain capacity information through the /dev/spdk/nvmex character device? I have not seen

**Comment by Comphix** [comment]
You can use below command id-ctrl and intel market-name to get the related information.

And the capacity is from below tnvmcap file which is in byte. Like below case, it is in about 2TB capacity.

Total NVM Capacity (TNVMCAP): This field indicates the total NVM capacity in the NVM subsystem.  The value is in bytes.



# nvme id-ctrl /dev/spdk/nvme0
NVME Identify Controller:
vid     : 0x8086
ssvid   : 0x8086
sn      : BTLJ72430ARH2P0BGN
mn      : INTEL SSDPE2KX020T8
fr      : VDV10110
rab     : 0
ieee    : 5cd2e4
cmic    : 0
mdts    : 5
cntlid  : 0
ver     : 10200
rtd3r   : 1e8480
rtd3e   : 2dc6c0
oaes    : 0
oacs    : 0x6
acl     : 3
aerl    : 3
frmw    : 0x2
lpa     : 0x2
elpe    : 63
npss    : 0
avscc   : 0
apsta   : 0
wctemp  : 343
cctemp  : 353
mtfa    : 0
hmpre   : 0
hmmin   : 0
tnvmcap : 2000398934016

# nvme intel market-name /dev/spdk/nvme0
Intel Marketing Name Log:
Intel(R) SSD DC P4500    Series

**Comment by Comphix** [comment]
The other way is to unregister the device before calling the identify tool.

2：./scripts/rpc.py bdev_nvme_cuse_unregister -n Nvme0

**Comment by Comphix** [comment]
For the problem itself, the 2nd identify process looks like accessing the NULL pointer from the qpair->transport field. As in the multi process sharing, this qpair is I/O qpair and allocated by the first process.

**Comment by zlsh007** [comment]
Got it, thanks for replying.
