### ISSUE TITLE
What limits the max spdk_cache

### ISSUE THREAD

**Issue by jasunliu** [spdk/spdk#1389]
rocksdb  db_bench
There is no error When I use the parameter  “--spdk_cache_size=2048” , but when I use "--spdk_cache_size=20480"  Create mempool failed

I've tested with "HUGEMEM=51200 scripts/setup.sh", still faild.

so what limits the spdk_cache_size？

ERROR MESSAGE:
Starting SPDK v20.01.2-pre git sha1 09377fc41 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: rocksdb --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid3277280 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 642:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 316:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
using bdev Nvme0n1
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
EAL: eal_memalloc_alloc_seg_bulk(): couldn't find suitable memseg_list
blobfs.c: 272:__initialize_cache: *ERROR*: Create mempool failed, you may increase the memory and try again
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
Received signal 11 (Segmentation fault)
#0   ./db_bench(+0x4b0eb8) [0x563ad2823eb8] ??	??:0

**Comment by changpe1** [comment]
DPDK will allocate continuous physical memory for mempool, for your case there are two workarounds that you may have a try:
1. Using 1GiB hugepages.
2. You can try with  --iova-mode=va mode with 2MiB hugepage.

**Comment by jasunliu** [comment]
> DPDK will allocate continuous physical memory for mempool, for your case there are two workarounds that you may have a try:
> 
>     1. Using 1GiB hugepages.
> 
>     2. You can try with  --iova-mode=va mode with 2MiB hugepage.
Thank you for your reply.
According to the link : https://spdk.io/doc/blobfs.html,   require at list 5GB of memory allocated for huge pages.   "Make sure you have at least 5GB of memory allocated for huge pages. By default, the SPDK setup.sh script only allocates 2GB. The following will allocate 5GB of huge page memory (in addition to binding the NVMe devices to uio/vfio)."
and my system hugepages:
AnonHugePages:     63488 kB
ShmemHugePages:        0 kB
HugePages_Total:    2560
HugePages_Free:     1354
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:         5242880 kB

how can i use  --iova-mode=va mode, I use rocksdb's db_bench test

**Comment by jasunliu** [comment]
Thanks , I added the hugepages , It is OK.
