### ISSUE TITLE
Use general c function "system"  in spdk code will cause nvmef malfunction

### ISSUE THREAD

**Issue by cockroach1136** [spdk/spdk#1392]
Recently we are trying the nvmeof function of spdk.
We use the procedures 
-----------------------------------------------------------------------------------------------------
1.scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -p 4 -c 0
2.scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
3.scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
4.scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
5.scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
----------------------------------------------------------------------------------------------------------
and we discovery in client

"nvme discover -t rdma -a 192.168.100.8 -s 4420" 

All works well.

But for the need of our application, we need add a "system("ls")" in "create_malloc_disk" function to get some information. 

After we add the "system("ls")" code  in "create_malloc_disk" function, the result of 
"nvme discover -t rdma -a 192.168.100.8 -s 4420"  is incorrect.
below is the result

----------------------------------------------------------------------------------------
[root@c3 ~]# nvme discover -t rdma -a 192.168.100.8 -s 4420 
Failed to write to /dev/nvme-fabrics: Input/output error

/var/log/messages from Client:
kernel: nvme nvme0: Connect command failed, error wo/DNR bit: 7
kernel: nvme nvme0: failed to connect queue: 0 ret=16391
------------------------------------------------------------------------------------------

It is very strange that why we add a " system("ls") " in  create_malloc_disk function that caused nvmef discovery malfunction. 
The code we add is shown in the picture attached below.
We had tried some other places to put the code, the result is still the same

![image](https://user-images.githubusercontent.com/29791158/81574368-4b135a80-93d8-11ea-91ed-8d2e208e1d41.png)

So does anyone can give me any hint to solve this problem??
Any suggestion is appreciated.
Thank you so much.

**Comment by Comphix** [comment]
May refer this page: https://linux.die.net/man/3/system

Description
system() executes a command specified in command by calling /bin/sh -c command, and returns after the command has been completed. During execution of the command, SIGCHLD will be blocked, and SIGINT and SIGQUIT will be ignored.

-----------
Can you try "/bin/sh -c ls" and check whether it works?

**Comment by changpe1** [comment]
@cockroach1136 Could you describe why you need a system call inside the function, I'm thinking maybe you have another method to do that.

**Comment by cockroach1136** [comment]
@Comphix 
Thank you so much for your advice. I will try it

@changpe1 
The reason why we need to use "system" function is that we need to execute a python script.
Of course, we can write a new c function to replace the python script.
But that is complicated.
The most convenient way is to use "system" to execute the python script directly.

Thank you again to both of you.

**Comment by jimharris** [comment]
How long does this Python command take to execute?  Note that until that system() call returns, that SPDK thread will not be able to do any work (including servicing incoming connections).

If you truly must execute a Python command like this, I'd suggest spawning a separate pthread, and call spdk_unaffinitze_thread() immediately in that new thread.  Otherwise your new thread will be pinned to the same core and you'll still have some problems.

**Comment by changpe1** [comment]
I'm going to close this issue now, we will not enable this in SPDK.
