### ISSUE TITLE
[free-bsd-autotest]  --enable-log-bt requires libunwind

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1394]
00:00:34.356  RDMA_OPTION_ID_ACK_TIMEOUT is not supported
00:00:34.371  --enable-log-bt requires libunwind.
00:00:34.371  Please install then re-run this script.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_13773.html

**Comment by AlekseyMarchuk** [comment]
This part of log "RDMA_OPTION_ID_ACK_TIMEOUT is not supported" is fine, it means that we don't use some functionality in NVMEoF RDMA initiator.
The real problem is 
```
00:00:34.371 --enable-log-bt requires libunwind.
00:00:34.371 Please install then re-run this script.
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_13758.html

**Comment by changpe1** [comment]
> This part of log "RDMA_OPTION_ID_ACK_TIMEOUT is not supported" is fine, it means that we don't use some functionality in NVMEoF RDMA initiator.
> The real problem is
> 
> ```
> 00:00:34.371 --enable-log-bt requires libunwind.
> 00:00:34.371 Please install then re-run this script.
> ```

Seth is working on this, we just used a new Freebsd VM.

**Comment by wawryk** [comment]
During install new packages there was update gcc to version 9.4, and this caused this issue. 
Back to gcc 9.3 in CI freebsd fix this issue.

**Comment by darsto** [comment]
BTW that backtrace doesn't work. I made a patch to remove the entire feature from SPDK: https://review.spdk.io/gerrit/c/spdk/spdk/+/2194

**Comment by Seth5141** [comment]
Once Darek's patch is merged, we can close this. Thanks @darsto

**Comment by Seth5141** [comment]
Darek's patch was merged.
