### ISSUE TITLE
code reports warning in log.c

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1395]
# Issue
log.c: In function ‘spdk_log’:
log.c:124:31: warning: ‘%06ld’ directive output may be truncated writing between 6 and 17 bytes into a region of size between 7 and 30 [-Wformat-truncation=]
  124 |  snprintf(buf, buf_size, "[%s.%06ld] ", date, usec);
      |                                                    ^~~~~
log.c:124:26: note: directive argument in the range [-9223372036854775, 9223372036854775]
  124 |  snprintf(buf, buf_size, "[%s.%06ld] ", date, usec);
      |                                                     ^~~~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /home/storage/spdk/include/spdk/stdinc.h:57,
                 from log.c:34:
/usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 11 and 45 bytes into a destination of size 32
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  LIB libspdk_ut_mock.a
  LIB libspdk_log.a

# Steps
./configure
make clean && make -j10

## Context (Environment including OS version, SPDK version, etc.)
OS: 5.6.8-100.fc30.x86_64
commit: 2187424ab2a1bbfe90866267d6bd674aa02342ed

**Comment by changpe1** [comment]
@yidong0635 could you take a look?

**Comment by yidong0635** [comment]
how about add -Wno-format-truncation?

**Comment by jimharris** [comment]
No, please let's not disable a warning for this.

Can we make the usec variable a uint32_t?  There's no need for it to be a long (which will be 64-bits).

**Comment by yidong0635** [comment]
Thanks @jimharris ,https://review.spdk.io/gerrit/c/spdk/spdk/+/2426.

**Comment by yidong0635** [comment]
the root cause is the timestamp buf is not enough in some case.
