### ISSUE TITLE
[FreeBSD] Different compilers are used for same feature tests

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1397]
```
SPDK: v20.04-rc1-166-gde11a5b2a
```

Background:

Currently, it's not possible to compile ref spdk via `vm_setup.sh` on `FreeBSD` as the compiler is not able to locate the `libunwind.*` files. The `libunwind` is looked up because  `install_reference_spdk()` calls `get_config_params()` to get the cmdline for the `./configure` which happens to include the `--enable-log-bt` option. The reason why it does that is because it uses hardcoded compiler (`gcc`) instead of `$CC` to run the test against `libunwind` which returns successfully. However, `./configure` also runs its own test for `libunwind`, but this time `$CC` is used, which defaults to clang (`cc`). It fails because `cc` is not looking up the `-I/usr/local/include`, `-L/usr/local/lib` paths by default as `gcc` does and where the actual `libunwind.*` files are stored on `FreeBSD`. 

The above issue can be easily fixed by adding the missing paths to `BUILD_CMD[]` in `./configure`, however, there is still the main issue where different compilers are being used to run the same test. 

So, the question is, which one should be actually used on the `FreeBSD`?

**Comment by mikeBashStuff** [comment]
Fix for the issue with locating libunwind files: https://review.spdk.io/gerrit/c/spdk/spdk/+/2434

**Comment by jimharris** [comment]
We should always default to clang on FreeBSD.

**Comment by mikeBashStuff** [comment]
Also, clang's issue with locating proper files is not limited to `libunwind`, this is just where `./configure` fails and exits. The same thing would  happen with other stuff, like rdma for instance.

**Comment by jimharris** [comment]
I don't think we support anything rdma-related on FreeBSD.

Could we just not use --enable-log-bt on FreeBSD at all?  Make it a Linux-only thing?  Our FreeBSD support is only best effort.  If someone comes along that really needs this to work on FreeBSD, it could be added later.

**Comment by mikeBashStuff** [comment]
@jimharris I guess we could just pass some limited options to `./configure` in case we run under FreeBSD instead of using everything `get_config_params()` returns. Currently, these are the args `./configure` gets on FreeBSD when stuff for ref spdk is being compiled:

```
--enable-debug
--enable-werror
--enable-log-bt
--with-rdma
--without-idxd
--with-fio=/usr/src/fio
--with-crypto
--with-ocf
--enable-ubsan
--enable-asan
--with-raid5
```
Is there anything on that list that should be definitely removed?

**Comment by jimharris** [comment]
I would only keep the following options:

enable-debug
enable-werror
without-idxd
with-fio
enable-ubsan
enable-asan

Reading rdma, crypto, ocf and raid5, we've been compiling them in, but I don't think we run any tests for those on FreeBSD.  Can you or someone there confirm?  If we're not testing them, I don't think we should configure for them.  If there comes a requirement later for FreeBSD support for one of these, we can add it again later.

**Comment by mikeBashStuff** [comment]
Hmmmm, I am not really able to compile spdk with this minimal set of options (testing on FreeBSD 11.3) :(. Getting this:
```
ld.lld: error: undefined symbol: spdk_scsi_nvme_translate
>>> referenced by bdev.c:4674 (/root/spdk_20_04/lib/bdev/bdev.c:4674)
>>>               bdev_ut.o:(spdk_bdev_io_get_scsi_status)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[6]: *** [/root/spdk_20_04/mk/spdk.unittest.mk:74: bdev_ut] Error 1
gmake[5]: *** [/root/spdk_20_04/mk/spdk.subdirs.mk:44: bdev.c] Error 2
gmake[4]: *** [/root/spdk_20_04/mk/spdk.subdirs.mk:44: mt] Error 2
gmake[3]: *** [/root/spdk_20_04/mk/spdk.subdirs.mk:44: bdev] Error 2
gmake[2]: *** [/root/spdk_20_04/mk/spdk.subdirs.mk:44: lib] Error 2
gmake[1]: *** [/root/spdk_20_04/mk/spdk.subdirs.mk:44: unit] Error 2
gmake: *** [/root/spdk_20_04/mk/spdk.subdirs.mk:44: test] Error 2
[root@freebsd ~/spdk_20_04]#
```

**Comment by darsto** [comment]
> ld.lld: error: undefined symbol: spdk_scsi_nvme_translate

spdk_scsi_nvme_translate() is a part of lib/bdev. Are you sure there aren't any earlier errors?

**Comment by mikeBashStuff** [comment]
@darsto Nope, I can't see anything else, just that one thing seems to be failing. Should I look for something specific though?

**Comment by jimharris** [comment]
There's no spdk_scsi_nvme_translate stub in test/unit/lib/bdev/mt/bdev.c/bdev_ut.c.  I can't explain why it links OK on gcc, but that's surely the culprit.

**Comment by karlatec** [comment]
We don't need a log bt for a reference build, so might as well just remove `--enable-log-bt` from `./configure` options I guess.

**Comment by mikeBashStuff** [comment]
OK, just to note, I actually managed to build spdk like so:
`--enable-debug --enable-werror --with-fio=/usr/src/fio --disable-unit-tests --without-isal`

I basically took that from how autotest-freebsd in the CI builds it.

**Comment by darsto** [comment]
JFYI backtrace logs were removed from SPDK https://review.spdk.io/gerrit/c/spdk/spdk/+/2194
