### ISSUE TITLE
[Iscsi] ./test/iscsi_tgt/calsoft/calsoft.sh test failed

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1399]
# Log 
https://ci.spdk.io/results/autotest-per-patch/builds/14170/archive/iscsi-autotest/build.log
00:01:54.362   05:28:50	# /var/jenkins/workspace/iscsi-autotest/spdk/scripts/rpc.py iscsi_create_target_node Target3 Target3_alias MyBdev:0 1:2 64 -g 1
00:01:54.528   05:28:51	# sleep 1
00:01:55.529   05:28:52	# '[' '' ']'
00:01:55.529   05:28:52	# /var/jenkins/workspace/iscsi-autotest/spdk/test/iscsi_tgt/calsoft/calsoft.py /var/jenkins/workspace/iscsi-autotest/spdk/../output
00:01:55.834  [2020-05-18 05:28:52.320178] iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=66)
00:01:55.834  [2020-05-18 05:28:52.320429] iscsi.c:4449:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
00:01:55.835  [2020-05-18 05:28:52.320618] iscsi.c:4438:iscsi_update_cmdsn: *ERROR*: CmdSN(0) ignore (ExpCmdSN=4, MaxCmdSN=66)
00:01:55.835  [2020-05-18 05:28:52.320683] iscsi.c:4449:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=4
00:01:55.835  [2020-05-18 05:28:52.320961] iscsi.c:4449:iscsi_update_cmdsn: *ERROR*: CmdSN(0) error ExpCmdSN=5
....
00:02:14.412     54  	else
00:02:14.412  => 55  		$calsoft_py "$output_dir"
00:02:14.412     56  		failed=$?
00:02:14.412     57  	fi
00:02:15.020  in ./test/iscsi_tgt/iscsi_tgt.sh:35 -> main(["posix"])
00:02:15.020       ...
00:02:15.020     30  	if [ "$TEST_TYPE" == "posix" ]; then
00:02:15.020     31  		# calsoft doesn't handle TCP stream properly and fails decoding iSCSI
00:02:15.020     32  		# requests when are divided by TCP segmentation. This is very common
00:02:15.020     33  		# situation for VPP and causes that calsoft.sh never PASS.
00:02:15.020     34  		if [[ -d /usr/local/calsoft ]]; then
00:02:15.020  => 35  			run_test "iscsi_tgt_calsoft" ./test/iscsi_tgt/calsoft/calsoft.sh
00:02:15.020     36  		else
00:02:15.020     37  			skip_run_test_with_warning "WARNING: Calsoft binaries not found, skipping test!"
00:02:15.020     38  		fi
00:02:15.020     39  	fi

## Context (Environment including OS version, SPDK version, etc.)

commit:e69375bff34ec748bf57dafd81cec3297d60040f

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_14170.html

**Comment by yidong0635** [comment]
dulicated of #1299 , close this one.
