### ISSUE TITLE
compile failed on SUSE 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1400]
# Issue
built failed on SUSE:
Build complete [x86_64-native-linuxapp-gcc]
  CC app/spdk_top/spdk_top.o
spdk_top.c:42:10: fatal error: panel.h: No such file or directory
 #include <panel.h>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [/home/storage/autotestspdk/spdk/mk/spdk.common.mk:367: spdk_top.o] Error 1
make[1]: *** [/home/storage/autotestspdk/spdk/mk/spdk.subdirs.mk:44: spdk_top] Error 2
make: *** [/home/storage/autotestspdk/spdk/mk/spdk.subdirs.mk:44: app] Error 2

# steps
./scripts/pkgdep.sh
zypper install ncurses*
./configure --with-rdma
make -j20

# Possible 
for SUSE
change to
+<ncurses/panel.h>
+<ncurses/menu.h>
-<panel.h>
-<menu.h>

**Comment by yidong0635** [comment]
@tomzawadzki 
I just found it not just to change file path, this may need to check this app running on some other systems.
sorry , this app is  distortion on SUSE  about font selection with background color, the may need the owner to take a look.

**Comment by yidong0635** [comment]
![image](https://user-images.githubusercontent.com/39082016/82528639-d07ed380-9b6b-11ea-8602-d450f6ecb9c3.png)

**Comment by yidong0635** [comment]
this is to fix compiling error on openSUSE.
https://review.spdk.io/gerrit/c/spdk/spdk/+/2638

**Comment by yidong0635** [comment]
font issue should be another issue on all other platform.

**Comment by changpe1** [comment]
Patch has been merged, closing this issue for now.
