### ISSUE TITLE
bdev   perf   test tool

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1401]
as nvme example folder, has one perf tool to test SPDK performance. I cannot find the same perf tool that can test bdev. 

could you please let me know if there is any solution for me to do perf test on bdev?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
Hi @gwnet,

There is an app called bdevperf in the test/bdev/bdevperf directory.

I'm going to close this issue, but please feel free to respond on this issue if you have further questions.

-Jim

**Comment by benlwalker** [comment]
I'm in the process of reorganizing where all of the applications output their binaries, and then I plan to "promote" both nvme/perf and bdevperf to officially supported tools instead of examples or test tools. That will make it less difficult to find in the future.

**Comment by gwnet** [comment]
thank you guys so much. :)

**Comment by gwnet** [comment]
I follow this link to create one OCF bdev, but how I test it with bdevperf tool? can anyone give me the detail guidance? https://open-cas.github.io/getting_started_spdk.html
