### ISSUE TITLE
test/nvmf/host/perf.sh --transport=rdma failed  

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1413]
run nvmf test locally, there are many errors, 
some times:
 16:01:24       # /home/yidong/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Nvme0n1
[2020-05-22 16:01:24.214550] nvmf_rpc.c: 964:nvmf_rpc_ns_paused: *ERROR*: No bdev with name Nvme0n1
request:
{
  "nqn": "nqn.2016-06.io.spdk:cnode1",
  "namespace": {
    "bdev_name": "Nvme0n1"
  },
  "method": "nvmf_subsystem_add_ns",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}
  16:01:24      # trap - ERR
  16:01:24      # print_backtrace
  16:01:24      # [[ ehxBE =~ e ]]
  16:01:24      # args=("${BASH_ARGV[@]}")
  16:01:24      # local args
  16:01:24      # xtrace_disable
  16:01:24      # '[' no '!=' yes ']'
  16:01:24      # PREV_BASH_OPTS=ehxBE
  16:01:24      # [[ ehxBE == *\x* ]]
  16:01:24      # XTRACE_DISABLED=yes
  16:01:24      # set +x
========== Backtrace start: ==========

on different machine:
this test failed on different machines , all kinds of error.
commit 13cc64fd5371f4c565b1d474537b61b153877bfb

**Comment by changpe1** [comment]
@yidong0635 Can you get the block device using 'bdev_get_bdevs' RPC when this error happened ?

**Comment by yidong0635** [comment]
@changpe1  ,  will take a time to double  check this. Our test environments are been reset. I ran this test on different machines last week,  and got different results:
1. some machine likes issue as above .
2. some machine hangs up .
 09:04:57       # /home/yidong/spdk/examples/nvme/perf/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r 'trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420'
Starting SPDK v20.07-pre git sha1 a9430856b / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid61794 ]
Initializing NVMe Controllers
[2020-05-25 09:04:58.784621] nvme_rdma.c: 967:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-05-25 09:04:58.784669] nvme_rdma.c:1198:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
^CTraceback (most recent call last):
  File "/home/yidong/spdk/scripts/rpc.py", line 2428, in <module>
    for input in sys.stdin:
KeyboardInterrupt
^C^C^C

3. some machine reports other issues.  And these are so abnormal.
I will try to make clear about these.

**Comment by yidong0635** [comment]
I haven't checked several machine.
for 1, no nvme device. It's not a bug on my side.
for 2, this may need to investigate .
others need to observe more.

**Comment by yidong0635** [comment]
I'm going to close this one, once I confirm the issue 2 is due to the code defect, I will submit a new one.
