### ISSUE TITLE
Lock-up during multiple, successive nvme hotplugs

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1416]
When a NVMe drive is removed/added multiple times in quick succession, the nvmf target locks up.
For example, I'm executing the following 2 steps in quick succession 5 times:
hot remove drive
hot add drive

There is only minimal delay between these steps (1-10ms).

Note: In my app, I'm listening to SPDK bdev_register event and call the RPC to add a newly found bdev to a specific NVMF subsystem.

After a couple runs, I observe the following log entries. The last entries repeat forever and the nvmf_tgt is locked up at that point:
```
2020-05-26 08:04:41,512 24037 E nvme_ctrlr.c:nvme_ctrlr_fail:768 ctrlr 0000:c0:00.0 in failed state.
2020-05-26 08:04:41,529 24037 E DPDK::0 EAL: Unexpected device scan at /sys/bus/pci/devices/0000:c0:00.0/driver!

// Here the bdev_nvme_hotplug loop found a new device but as part of the create_ctrlr which is called by bdev_nvme_hotplug the device is removed and creating the io queue pair fails.
2020-05-26 08:04:46,810 24037 E nvme_ctrlr.c:nvme_ctrlr_create_io_qpair:311 get_cc failed

// The error below is due to the fact that bdev_nvme_get_io_channel failed. The reason is the failure of bdev_nvme_create_cb return -1 due to the above error.
2020-05-26 08:04:46,810 24037 E nvmf.c:poll_group_update_subsystem:1065 Could not allocate I/O channel.
// We are still processing a hot remove and abort all the outstanding commands.
2020-05-26 08:04:46,846 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:22 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:22 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,846 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,846 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:21 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:21 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,846 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,846 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:20 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:20 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,846 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,846 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:19 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:19 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,846 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,846 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:18 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,846 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:18 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,847 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,847 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,847 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:17 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,847 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:17 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,847 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,847 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,847 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:16 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,847 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:16 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,847 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,847 24037 E nvme_pcie.c:nvme_pcie_qpair_abort_trackers:1427 aborting outstanding command
2020-05-26 08:04:46,847 24037 I nvme_qpair.c:nvme_admin_qpair_print_command:118 ASYNC EVENT REQUEST (0c) sqid:0 cid:15 nsid:0 cdw10:00000000 cdw11:00000000
2020-05-26 08:04:46,847 24037 I nvme_qpair.c:spdk_nvme_qpair_print_completion:306 ABORTED - BY REQUEST (00/07) sqid:0 cid:15 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
2020-05-26 08:04:46,847 24037 W bdev_nvme.c:aer_cb:1331 AER request execute failed
2020-05-26 08:04:46,847 24037 E nvme_ctrlr.c:nvme_ctrlr_fail:768 ctrlr 0000:c0:00.0 in failed state.
2020-05-26 08:04:46,864 24037 E DPDK::0 EAL: Unexpected device scan at /sys/bus/pci/devices/0000:c0:00.0/driver!

2020-05-26 08:04:46,880 24037 E subsystem.c:spdk_nvmf_ns_hot_remove:1033 Unable to pause subsystem to process namespace removal!

// The following messages repeat forever.
2020-05-26 08:04:46,946 24037 E nvme_ctrlr.c:nvme_ctrlr_fail:768 ctrlr 0000:c0:00.0 in failed state.
2020-05-26 08:04:46,964 24037 E DPDK::0 EAL: Unexpected device scan at /sys/bus/pci/devices/0000:c0:00.0/driver!
2020-05-26 08:04:47,047 24037 E nvme_ctrlr.c:nvme_ctrlr_fail:768 ctrlr 0000:c0:00.0 in failed state.
2020-05-26 08:04:47,065 24037 E DPDK::0 EAL: Unexpected device scan at /sys/bus/pci/devices/0000:c0:00.0/driver!
2020-05-26 08:04:47,147 24037 E nvme_ctrlr.c:nvme_ctrlr_fail:768 ctrlr 0000:c0:00.0 in failed state.
2020-05-26 08:04:47,165 24037 E DPDK::0 EAL: Unexpected device scan at /sys/bus/pci/devices/0000:c0:00.0/driver!
2020-05-26 08:04:47,247 24037 E nvme_ctrlr.c:nvme_ctrlr_fail:768 ctrlr 0000:c0:00.0 in failed state.
2020-05-26 08:04:47,265 24037 E DPDK::0 EAL: Unexpected device scan at /sys/bus/pci/devices/0000:c0:00.0/driver!

```

## Expected Behavior
The hotplug detection and the ctrlr creation should be somewhat resilient against spurious hotplug events (these events can happen if there are PCIe connection issues or someone removes/adds drives in quick succession).

## Steps to Reproduce
I can only repro this with real HW. I was wondering if we should simply fail the ctrlr if create_ctrlr() fails.

## Context (Environment including OS version, SPDK version, etc.)
CentOS8, 20.04, vfio-pci

**Comment by liang2yan** [comment]
@mhae , are you using vfio-pci or uio_pci_generic? I am trying to reproduce this issue in my environment.

**Comment by mhae** [comment]
Hi @liang2yan, it's vfio-pci. UIO is still broken in CentOS8. I'll try to work some more on this issue as well (I've been on it for a couple of days already). I'm not sure how easy it will be to repro in a VM setup vs real HW. Did my write up and error messages provide enough context?

**Comment by ak-gh** [comment]
On Thu, May 28, 2020, 01:45 Michael Haeuptle <notifications@github.com>
wrote:

> When a NVMe drive is removed/added multiple times in quick succession, the
> nvmf target locks up.
> For example, I'm executing the following 2 steps in quick succession 5
> times:
> hot remove drive
> hot add drive
>
> There is only minimal delay between these steps (1-10ms).
>
> Note: In my app, I'm listening to SPDK bdev_register event and call the
> RPC to add a newly found bdev to a specific NVMF subsystem.
>
> After a couple runs, I observe the following log entries. The last entries
> repeat forever and the nvmf_tgt is locked up at that point:
>

These repetitive messages come from vfio-pci since then expected user
callback is never fired. They are better disabled, makes things much easier
to debug.

Regards,
Andrey

**Comment by mhae** [comment]
@liang2yan , I made a little bit more progress today and I wanted to send you an update in case you come online soon.
I hope you had a chance follow the code based on the error messages. There are 1 or potentially 2 issues.
The major issue is that adding the bdev to a subsystem can fail. There is no way to propgate the failure in poll_group_update_subsystem back to the RPC. The RPC is left in a RESUMING state. I believe there are other instances where we leave subsystem RPCs in a bad state if there's an internal error. I'm currently trying to see if there is an easy way to at least propagate the error to the RPC caller.
The 2nd issue is the DPDK error messages. These may be a side effect us not getting rid of this zombie bdev. I could make another RPC to get rid of this namespace/bdev when the RPC to add a bdev to a subsystem fails. However, a better approach would be to get rid of the bdev altogether if the add namespace fails.
Again, I'm hoping that getting rid of the zombie bdev would solve the DPDK errors as well.

I was wondering if you could look adding proper error checking to the spdk_rpc_nvmf_subsystem_add_ns. I think we also need to ensure that a NVMF subsystem is always in a state where another RPC to it can succeed.

**Comment by mhae** [comment]
@liang2yan , so it seems that force the NVMF subsystem to ACTIVE, even if spdk_rpc_nvmf_subsystem_add_ns fails, then I don't get into the DPDK loop. So having the subsystem in a failed state is messing up the release of the PCIe device when we try to hot remove it.
I don't know what our stance is towards failed RPCs, but we can't leave them in a non-recoverable state.
This is what I did to make progress and I would appreciate your input.
```
nvmf_rpc.c:
tatic void
nvmf_rpc_ns_resumed(struct spdk_nvmf_subsystem *subsystem,
		    void *cb_arg, int status)
{
	struct nvmf_rpc_ns_ctx *ctx = cb_arg;
	struct spdk_jsonrpc_request *request = ctx->request;
	uint32_t nsid = ctx->ns_params.nsid;
	bool response_sent = ctx->response_sent;
	struct spdk_json_write_ctx *w;

	nvmf_rpc_ns_ctx_free(ctx);

	if (response_sent) {
		return;
	}

	// mhae
	printf("!!!!!!!!!! nvmf_rpc_ns_resumed: state=%d\n", subsystem->state);

	if (status) {
		spdk_jsonrpc_send_error_response(request, SPDK_JSONRPC_ERROR_INTERNAL_ERROR, "Internal error");
	} else {
		w = spdk_jsonrpc_begin_result(request);
		spdk_json_write_uint32(w, nsid);
		spdk_jsonrpc_end_result(request, w);
	}
}

subsystem.c
static void
subsystem_state_change_done(struct spdk_io_channel_iter *i, int status)
{
	struct subsystem_state_change_ctx *ctx = spdk_io_channel_iter_get_ctx(i);

	// if (status == 0) {
	// 	status = spdk_nvmf_subsystem_set_state(ctx->subsystem, ctx->requested_state);
	// 	if (status) {
	// 		status = -1;
	// 	}
	// }
	// mhae
	printf("!!! subsystem_state_change_done: status=%d, requested_state=%d\n", status, ctx->requested_state);
	int _s = spdk_nvmf_subsystem_set_state(ctx->subsystem, ctx->requested_state);
	printf("!!! subsystem_state_change_done: set_state returned: %d\n", _s);
	

	if (ctx->cb_fn) {
		ctx->cb_fn(ctx->subsystem, ctx->cb_arg, status);
	}
	free(ctx);
}
```

Now the return from the RPC would have to indicate the failed namespace id. So what I did is not correct. Maybe you have a better idea but I believe handling failed (NVMF subsystem) RPCs is a bigger discussion.

**Comment by liang2yan** [comment]
@mhae , I think I have reproduced this issue. The log is as below:
```
rdma.c:2471:spdk_nvmf_rdma_create: *NOTICE*: Adjusting the io unit size to fit the device's maximum I/O size. New I/O unit size 45056
rdma.c:2666:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.145.111.11 port 4420 ***
nvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:22 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:22 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:21 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:21 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:20 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:20 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:19 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:19 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_ctrlr.c: 768:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:d8:00.0 in failed state.
nvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:22 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:22 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:21 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:21 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:20 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:20 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_pcie.c:1427:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
nvme_qpair.c: 115:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) sqid:0 cid:19 nsid:0 cdw10:00000000 cdw11:00000000
nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:19 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
bdev_nvme.c:1331:aer_cb: *WARNING*: AER request execute failednvme_ctrlr.c: 768:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:5f:00.0 in failed state.
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:d8:00.0/driver!
subsystem.c:1033:spdk_nvmf_ns_hot_remove: *ERROR*: Unable to pause subsystem to process namespace removal!
nvme_ctrlr.c: 768:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:5f:00.0 in failed state.
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:5f:00.0/driver!
nvme_ctrlr.c: 768:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:5f:00.0 in failed state.
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:5f:00.0/driver!
nvme_ctrlr.c: 768:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:5f:00.0 in failed state.
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:5f:00.0/driver!
```

I will follow your suggestion to get some progress.

**Comment by mhae** [comment]
@liang2yan , sweet! I was wondering if we should just remove the namespace in the add namespace RPC when the namespace was only half created.

**Comment by mhae** [comment]
Hi @liang2yan , are you still looking into this bug?

**Comment by yidong0635** [comment]
@mhae: 
I can reproduce this locking up, 
and the log:
requested_state =SPDK_NVMF_SUBSYSTEM_PAUSED
requested_state =SPDK_NVMF_SUBSYSTEM_PAUSED
nvmf set state error
 (
        rc = nvmf_subsystem_set_state(subsystem, intermediate_state);
        if (rc) {
+               printf("nvmf set state error\r\n");
                free(ctx);
                return rc;
        }
)
[2020-06-05 22:54:30.944777] subsystem.c:1035:nvmf_ns_hot_remove: *ERROR*: Unable to pause subsystem to process namespace removal!
requested_state =SPDK_NVMF_SUBSYSTEM_ACTIVE
locking up

and will look further for this , I't hard to simulate on spdk debug mode.
Some issues can't be reproduced on debug mode usually.

**Comment by mhae** [comment]
Thanks, @yidong0635. Yep, tricky issue. I can easily reproduce it here and I'm happy to try your fix.

**Comment by yidong0635** [comment]
@mhae, this locking up doesn't related to above error about pausing failure.
To pause a pausing subsystem  causes this failure. I solved  the  pausing error, 
https://review.spdk.io/gerrit/c/spdk/spdk/+/2817
but there's still locking up. I prefer this is related to  vfio_pci driver.  
 Maybe there're still something not thinking about.

**Comment by mhae** [comment]
Hi @yidong0635, I'm not sure I follow. The issue is that adding the namespace fails which leaves the subsystem in a resuming state. When a hot remove event is being process it tries to remove the namespace but fails because the subsystem is in a non-active state and after that the device scan is blocked since this half created NVME ctrlr is in a weird state.
You probably can reproduce this by returning -ENOMEM in `poll_group_update_subsystem`:
```
} else if (ns != NULL && ch == NULL) {
			/* A namespace appeared but there is no channel yet */
			ns_changed = true;
			ch = spdk_bdev_get_io_channel(ns->desc);
			if (ch == NULL) {
				SPDK_ERRLOG("Could not allocate I/O channel.\n");
				return -ENOMEM;
			}
			ns_info->channel = ch;
		}
```
One approach would be to remove the namespace in subsysem_state_change_done which is called as part of adding the namespace. Another option would be to remove the namespace in the RPC handling code when we detect that there was an error adding the namespace (but that's certainly less elegant).

**Comment by tomzawadzki** [comment]
[Community meeting]: @Seth5141 Could you take a look at this particular issue ?

**Comment by mhae** [comment]
I uploaded a RFC change to illustrate a potential worarund: https://review.spdk.io/gerrit/c/spdk/spdk/+/2841

**Comment by yidong0635** [comment]
@mhae , I just using your changes before which is the same as your patch .
 I haven't using rpcs to hot-remove ,with hot-removing three nvmes manually . 
I use  nvmf tcp tranport.
```
./configure
make -jN
./app/nvmf_tgt/nvmf_tgt
```
```
#!/usr/bin/bash
ifconfig eno2 up
ifconfig eno2 192.168.35.11
cd /home/spdk
./scripts/setup.sh
./scripts/rpc.py bdev_nvme_set_hotplug -e
sleep 10
./scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s  SPDK00000000000001
./scripts/rpc.py nvmf_create_transport -t TCP -u 8192
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 HotInNvme0n1
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 HotInNvme1n1
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 HotInNvme2n1
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t TCP -a 192.168.35.11 -s 4420

```
then to hot-remove three nvmes manually .
And I will try to understand the last your comment.  if seth has time to double checking this is better.

**Comment by yidong0635** [comment]
@mhae I have change  according to your edit, your description is right :
`device scan is blocked since this half created NVME ctrlr is in a weird state`.
But I had added print as you said in poll_group_update_subsystem, it  , as I removed the locks in spdk_for_each_channel_continue, but all were the same.
I have the logs:
[log_ok.txt](https://github.com/spdk/spdk/files/4762970/log_ok.txt)
[lock_up.txt](https://github.com/spdk/spdk/files/4762971/lock_up.txt)
the differences are
scan failure log from DPDK can be kicked out, but lock-up doesn't have this. :
"EAL: eal_parse_sysfs_value(): cannot open sysfs value /sys/bus/pci/devices/0000:5f:00.0/vendor
EAL: Scan for (pci) bus failed.
EAL: eal_parse_sysfs_value(): cannot open sysfs value /sys/bus/pci/devices/0000:d9:00.0/vendor
EAL: Scan for (pci) bus failed.
^Crequested_state =0
"
and my test result  : bus is hold by "`rte_eal_alarm_cancel(detach_rte_cb, rte_dev);`"

**Comment by mhae** [comment]
Hi @yidong0635. thanks for verifying! From looking at your lock_up.txt trace, it seems that you hit the same conditions.
I'm not sure what the best way would be to fix this. That's why I submitted this defect. The problem is that we don't have enough context in `subsystem_state_change_done` to know what operation we are working on (e.g. add namespace). But we do have status that indicates that something went wrong.
I was wondering if we should shift the cleanup logic towards the caller, which would be the RPC in my case. The `nvmf_rpc.c:nvmf_rpc_ns_resumed` can use status and attempt to remove the half created namespace, and then return an internal error.
But the better approach would be to somehow cleanup in spdk_nvmf_subsystem_resume but we just don't have the context of what the previous operation was (i.e. spdk_nvmf_subsystem_add_ns). 
What are your thoughts?

**Comment by yidong0635** [comment]
link to #1275

**Comment by Seth5141** [comment]
Hi @mhae,

Sorry for the long delay on this one, I didn't realize I was assigned and was just pinged on it a couple of days ago. Also, I apologize for the long post. This one is a bit hard for me to wrap my head completely around.

I have read through all of the comments here, and I *think* I understand what is going on here, but I just want to make sure that I do. According to what I have read, this is the desired cycle:

1. hot-insert an NVMe drive.
2. call the rpc "rpc_nvmf_subsystem_add_ns"
3. Once that RPC returns, hot-remove the drive.
4. repeat.

However, the problem is that somewhere in step 2, we fail and then we hang during step 3. Is that correct?
I also have one clarifying question:
1. At what point in the RPC do we fail? Do you actually get a failure in spdk_nvmf_subsystem_add_ns, or do you not see a failure until nvmf_rpc_ns_resumed?

With that background in mind, I might have a couple of ideas:

If the answer to my clarifying question is that we actually get a failure response from spdk_nvmf_subsystem_add_ns, I think we need to find where we are leaving an unclean state and clean that up within the context of spdk_nvmf_subsystem_add_ns.

If the answer is that we don't see a failure until we call nvmf_rpc_ns_resumed (I think this is probably the case), then I think you are on the right track with trying to do some cleanup, but it will be a pretty complex fix. Failing in the middle of a subsystem state change is actually pretty messy (I am assuming some poll groups successfully resume and some don't).
Some of the poll groups have the new ns, some don't.
Some groups are in the active state, some are in the paused state.

I think you are on the right track with trying to walk back the subsystem addition and leave the subsystem in a consistent state, but I think I would go the opposite direction with the subsystem state.
I think the most appropriate thing to do would be to roll back the state change on the poll groups that successfully moved to the new state, and set the subsystem as a whole back to the original state. At that point, we can call the callback with a status value. That allows us to walk back the namespace addition and try one more time to resume the subsystem.
This way the only new information we need to add is the original state to "struct subsystem_state_change_ctx"

I see a couple potential problems with this strategy:
1. What if when we try to pause the poll groups again? This seems unlikely since the only reason that nvme_poll_group_pause_subsystem will fail is if the subsystem->id is out of range or doesn't de-reference to anything. Since these are internal APIs, I feel we can be pretty certain that's not going to happen.
2. What do we do if we try to resume the subsystem again after walking back the namespace addition and the resume operation fails? Well, I don't know. At this point, I think we are out of luck and the only option we have is to report back to the user that their subsystem is totally busted and they need to resort to other means to rescue it. I don't like this, but I can't think of anything else to do. It's technically no worse than what we are doing currently (actually slightly better because the poll group will report a paused state instead of the intermediate pausing state) and at least we will have tried to return the subsystem to a consistent state.

I will work on a patch to do what I described above. Please let me know what you think of it.

But the elephant still in the room is: why is the namespace addition/subsystem resume failing in the first place? I feel like this is the actual root of what's going wrong here.

**Comment by Seth5141** [comment]
Hi @mhae Here is my proposed solution to the problem. It's a little bit messy, but I think I got my main idea in code so that you could test it out. Please let me know what you think. https://review.spdk.io/gerrit/c/spdk/spdk/+/3437

**Comment by mhae** [comment]
Hey @Seth5141 , sorry I got stuck in some meetings. Before I go into the code review, let me give you some more details.

The scenario is where are drive gets hot removed/inserted in quick succession. We detect when a new drive is added and add it to a pre-configured subsystem. In other words, we have a lot of removes/adds happen to a subsystem. Now, when a drive is added to a subsystem via the RPC and remove while the code is in poll_group_update_subsystem, the poll_group_update_subsystem call can fail. This leaves the subsystem in a wedged state.
It is fine for the app to attempt a cleanup via the remove namespace RPC if it gets an error back.

I think you could repro this by setting return -1 in poll_group_update_subsystem.

I'll review your code shortly.

**Comment by jimharris** [comment]
Hi @mhae - is there anything more needed on this issue?

**Comment by mhae** [comment]
@jimharris Let's close this. Seth's changes fixes this issue and I have a workaround until I can pull in 20.10.
