### ISSUE TITLE
[nvmf-phy-autotest] spdk_nvmf_subsystem_add_ns error

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1425]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/16110/archive/nvmf-phy-autotest/build.log

## Execution failed at

00:04:38.564   10:04:36	# NVMF_SECOND_TARGET_IP=192.168.100.9
00:04:38.564   10:04:36	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_transport -t rdma -u 8192
00:04:38.965   10:04:37	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
00:04:39.186  Malloc0
00:04:39.196   10:04:37	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
00:04:39.396   10:04:37	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
00:04:39.597   10:04:37	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
00:04:39.784  [2020-06-02 10:04:37.861122] rdma.c:2659:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.8 port 4420 ***
00:04:39.797   10:04:37	# echo 'test case1: single bdev can'\''t be used in multiple subsystems'
00:04:39.797  test case1: single bdev can't be used in multiple subsystems
00:04:39.798   10:04:37	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode2 -a -s SPDK2
00:04:40.002   10:04:38	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode2 -t rdma -a 192.168.100.8 -s 4420
00:04:40.203   10:04:38	# nmic_status=0
00:04:40.203   10:04:38	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode2 Malloc0
**00:04:40.390  [2020-06-02 10:04:38.466945] bdev.c:5251:bdev_open: *ERROR*: Could not open Malloc0 - NVMe-oF Target module already claimed it**
00:04:40.390  [2020-06-02 10:04:38.466994] subsystem.c:1189:spdk_nvmf_subsystem_add_ns: *ERROR*: Subsystem nqn.2016-06.io.spdk:cnode2: bdev Malloc0 cannot be opened, error=-1
00:04:40.390  [2020-06-02 10:04:38.467007] nvmf_rpc.c: 986:nvmf_rpc_ns_paused: *ERROR*: Unable to add namespace
00:04:40.394  request:
00:04:40.394  {
00:04:40.394    "nqn": "nqn.2016-06.io.spdk:cnode2",
00:04:40.394    "namespace": {
00:04:40.394      "bdev_name": "Malloc0"
00:04:40.394    },
00:04:40.394    "method": "nvmf_subsystem_add_ns",
00:04:40.394    "req_id": 1
00:04:40.394  }
00:04:40.394  Got JSON-RPC error response
00:04:40.394  response:
00:04:40.394  {
00:04:40.394    "code": -32602,
00:04:40.394    "message": "Invalid parameters"
00:04:40.394  }
00:04:40.404   10:04:38	# nmic_status=1
00:04:40.404   10:04:38	# '[' 1 -eq 0 ']'
00:04:40.404   10:04:38	# echo ' Adding namespace failed - expected result.'
00:04:40.404   Adding namespace failed - expected result.
00:04:40.404   10:04:38	# echo 'test case2: host connect to nvmf target in multiple paths'
00:04:40.404  test case2: host connect to nvmf target in multiple paths
00:04:40.405   10:04:38	# '[' -n 192.168.100.9 ']'
00:04:40.405   10:04:38	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.9 -s 4420
00:04:40.591  [2020-06-02 10:04:38.667832] rdma.c:2659:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.9 port 4420 ***
00:04:40.604   10:04:38	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.8 -s 4420
00:04:41.737   10:04:39	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.9 -s 4420
00:04:41.754  Failed to write to /dev/nvme-fabrics: Invalid argument
00:04:41.755    10:04:39	# trap - ERR
00:04:41.755    10:04:39	# print_backtrace
00:04:41.755    10:04:39	# [[ ehxBET =~ e ]]
00:04:41.756    10:04:39	# args=("${BASH_ARGV[@]}")
00:04:41.756    10:04:39	# local args
00:04:41.756    10:04:39	# xtrace_disable
00:04:41.756    10:04:39	# '[' no '!=' yes ']'
00:04:41.757    10:04:39	# PREV_BASH_OPTS=ehxBET
00:04:41.757    10:04:39	# [[ ehxBET == *\x* ]]
00:04:41.757    10:04:39	# XTRACE_DISABLED=yes
00:04:41.757    10:04:39	# set +x
00:04:41.757  ========== Backtrace start: ==========
00:04:41.757  
00:04:41.763  in test/nvmf/target/nmic.sh:45 -> main(["--transport=rdma"])
00:04:41.764       ...
00:04:41.764     40  	echo "test case2: host connect to nvmf target in multiple paths"
00:04:41.764     41  	if [ -n "$NVMF_SECOND_TARGET_IP" ]; then
00:04:41.764     42  		$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_SECOND_TARGET_IP -s $NVMF_PORT
00:04:41.764     43  	
00:04:41.764     44  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:04:41.764  => 45  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_SECOND_TARGET_IP" -s "$NVMF_PORT"
00:04:41.764     46  	
00:04:41.764     47  		waitforserial "$NVMF_SERIAL"
00:04:41.764     48  	
00:04:41.764     49  		$rootdir/scripts/fio.py -p nvmf -i 4096 -d 1 -t write -r 1 -v
00:04:41.764     50  	fi
00:04:41.764       ...
00:04:41.764  
00:04:41.764  ========== Backtrace end ==========
00:04:41.764    10:04:39	# xtrace_enable
00:04:41.764    10:04:39	# return 0
00:04:41.765   10:04:39	# process_shm --id 0
00:04:41.765   10:04:39	# type=--id
00:04:41.765   10:04:39	# id=0
00:04:41.765   10:04:39	# '[' --id = --pid ']'
00:04:41.765   10:04:39	# '[' --id = --id ']'
00:04:41.765   10:04:39	# id=0
00:04:41.766    10:04:39	# find /dev/shm -name '*.0' -printf '%f\n'
00:04:41.767   10:04:39	# shm_files=nvmf_trace.0
00:04:41.767   10:04:39	# [[ -z nvmf_trace.0 ]]
00:04:41.767   10:04:39	# for n in $shm_files
00:04:41.768   10:04:39	# tar -C /dev/shm/ -cvzf /var/jenkins/workspace/nvmf-phy-autotest/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
00:04:41.772  nvmf_trace.0
00:04:42.789   10:04:40	# return 0
00:04:42.789   10:04:40	# nvmftestfini
00:04:42.789   10:04:40	# nvmfcleanup
00:04:42.789   10:04:40	# sync
00:04:42.798   10:04:40	# set +e
00:04:42.798   10:04:40	# for i in {1..20}
00:04:42.798   10:04:40	# modprobe -v -r nvme-rdma
00:04:42.800  rmmod nvme_rdma
00:04:45.836  rmmod nvme_fabrics
00:04:45.844   10:04:43	# modprobe -v -r nvme-fabrics
00:04:45.848   10:04:43	# set -e
00:04:45.848   10:04:43	# return 0
00:04:45.849   10:04:43	# '[' -n 60199 ']'
00:04:45.849   10:04:43	# killprocess 60199
00:04:45.849   10:04:43	# '[' -z 60199 ']'
00:04:45.849   10:04:43	# kill -0 60199
00:04:45.849    10:04:43	# uname
00:04:45.851   10:04:43	# '[' Linux = Linux ']'
00:04:45.852    10:04:43	# ps --no-headers -o comm= 60199
00:04:45.873   10:04:43	# process_name=reactor_0
00:04:45.873   10:04:43	# '[' reactor_0 = sudo ']'
00:04:45.873   10:04:43	# echo 'killing process with pid 60199'
00:04:45.873  killing process with pid 60199
00:04:45.873   10:04:43	# kill 60199
00:04:45.873   10:04:43	# wait 60199
00:04:46.242   10:04:44	# '[' '' == iso ']'
00:04:46.242   10:04:44	# exit 1
00:04:46.243    10:04:44	# trap - ERR
00:04:46.243    10:04:44	# print_backtrace
00:04:46.243    10:04:44	# [[ ehxBET =~ e ]]
00:04:46.243    10:04:44	# args=("${BASH_ARGV[@]}")
00:04:46.244    10:04:44	# local args
00:04:46.244    10:04:44	# xtrace_disable
00:04:46.244    10:04:44	# '[' no '!=' yes ']'
00:04:46.244    10:04:44	# PREV_BASH_OPTS=ehxBET
00:04:46.244    10:04:44	# [[ ehxBET == *\x* ]]
00:04:46.244    10:04:44	# XTRACE_DISABLED=yes
00:04:46.244    10:04:44	# set +x
00:04:46.244  ========== Backtrace start: ==========
00:04:46.244  
00:04:46.253  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:874 -> run_test(["nvmf_nmic"],["test/nvmf/target/nmic.sh"],["--transport=rdma"])
00:04:46.254       ...
00:04:46.254     869 		timing_enter $test_name
00:04:46.254     870 		echo "************************************"
00:04:46.254     871 		echo "START TEST $test_name"
00:04:46.254     872 		echo "************************************"
00:04:46.254     873 		xtrace_restore
00:04:46.254  => 874 		time "$@"
00:04:46.254     875 		xtrace_disable
00:04:46.254     876 		echo "************************************"
00:04:46.254     877 		echo "END TEST $test_name"
00:04:46.254     878 		echo "************************************"
00:04:46.254     879 		timing_exit $test_name
00:04:46.254       ...
00:04:46.257  in ./test/nvmf/nvmf.sh:37 -> main(["--transport=rdma"])
00:04:46.257       ...
00:04:46.257     32  		run_test "nvmf_fuzz" test/nvmf/target/fuzz.sh "${TEST_ARGS[@]}"
00:04:46.257     33  		run_test "nvmf_multiconnection" test/nvmf/target/multiconnection.sh "${TEST_ARGS[@]}"
00:04:46.257     34  		run_test "nvmf_initiator_timeout" test/nvmf/target/initiator_timeout.sh "${TEST_ARGS[@]}"
00:04:46.257     35  	fi
00:04:46.257     36  	
00:04:46.257  => 37  	run_test "nvmf_nmic" test/nvmf/target/nmic.sh "${TEST_ARGS[@]}"
00:04:46.257     38  	run_test "nvmf_rpc" test/nvmf/target/rpc.sh "${TEST_ARGS[@]}"
00:04:46.257     39  	run_test "nvmf_fio" test/nvmf/target/fio.sh "${TEST_ARGS[@]}"
00:04:46.257     40  	run_test "nvmf_shutdown" test/nvmf/target/shutdown.sh "${TEST_ARGS[@]}"
00:04:46.257     41  	run_test "nvmf_bdevio" test/nvmf/target/bdevio.sh "${TEST_ARGS[@]}"
00:04:46.257     42  	run_test "nvmf_invalid" test/nvmf/target/invalid.sh "${TEST_ARGS[@]}"
00:04:46.257       ...
00:04:46.257  
00:04:46.257  ========== Backtrace end ==========
00:04:46.258    10:04:44	# xtrace_enable
00:04:46.258    10:04:44	# return 0
00:04:46.258  
00:04:46.258  real	0m8.703s
00:04:46.258  user	0m35.589s
00:04:46.258  sys	0m0.907s
00:04:46.258   10:04:44	# exit 1
00:04:46.259    10:04:44	# trap - ERR
00:04:46.259    10:04:44	# print_backtrace
00:04:46.259    10:04:44	# [[ ehxBET =~ e ]]
00:04:46.259    10:04:44	# args=("${BASH_ARGV[@]}")
00:04:46.259    10:04:44	# local args
00:04:46.259    10:04:44	# xtrace_disable
00:04:46.260    10:04:44	# '[' no '!=' yes ']'
00:04:46.260    10:04:44	# PREV_BASH_OPTS=ehxBET
00:04:46.260    10:04:44	# [[ ehxBET == *\x* ]]
00:04:46.260    10:04:44	# XTRACE_DISABLED=yes
00:04:46.260    10:04:44	# set +x
00:04:46.260  ========== Backtrace start: ==========
00:04:46.260  
00:04:46.265  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:874 -> run_test(["nvmf_rdma"],["./test/nvmf/nvmf.sh"],["--transport=rdma"])
00:04:46.265       ...
00:04:46.265     869 		timing_enter $test_name
00:04:46.265     870 		echo "************************************"
00:04:46.265     871 		echo "START TEST $test_name"
00:04:46.265     872 		echo "************************************"
00:04:46.265     873 		xtrace_restore
00:04:46.265  => 874 		time "$@"
00:04:46.265     875 		xtrace_disable
00:04:46.265     876 		echo "************************************"
00:04:46.265     877 		echo "END TEST $test_name"
00:04:46.265     878 		echo "************************************"
00:04:46.265     879 		timing_exit $test_name
00:04:46.265       ...
00:04:46.270  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/autotest.sh:228 -> main(["/home/sys_sgci/autorun-spdk.conf"])
00:04:46.270       ...
00:04:46.270     223 	
00:04:46.270     224 		if [ $SPDK_TEST_NVMF -eq 1 ]; then
00:04:46.270     225 			# The NVMe-oF run test cases are split out like this so that the parser that compiles the
00:04:46.270     226 			# list of all tests can properly differentiate them. Please do not merge them into one line.
00:04:46.270     227 			if [ "$SPDK_TEST_NVMF_TRANSPORT" = "rdma" ]; then
00:04:46.270  => 228 				run_test "nvmf_rdma" ./test/nvmf/nvmf.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:04:46.270     229 				run_test "spdkcli_nvmf_rdma" ./test/spdkcli/nvmf.sh
00:04:46.270     230 			elif [ "$SPDK_TEST_NVMF_TRANSPORT" = "tcp" ]; then
00:04:46.270     231 				run_test "nvmf_tcp" ./test/nvmf/nvmf.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:04:46.270     232 				run_test "spdkcli_nvmf_tcp" ./test/spdkcli/nvmf.sh
00:04:46.270     233 				run_test "nvmf_identify_passthru" test/nvmf/target/identify_passthru.sh --transport=$SPDK_TEST_NVMF_TRANSPORT
00:04:46.270       ...
00:04:46.270  
00:04:46.270  ========== Backtrace end ==========
00:04:46.270    10:04:44	# xtrace_enable
00:04:46.270    10:04:44	# return 0
00:04:46.271  
00:04:46.271  real	3m1.075s
00:04:46.271  user	10m2.045s
00:04:46.271  sys	0m11.735s
00:04:46.271   10:04:44	# process_core
00:04:46.271   10:04:44	# ret=0
00:04:46.271   10:04:44	# IFS=
00:04:46.271   10:04:44	# read -r -d '' core
00:04:46.272    10:04:44	# find . -type f '(' -name 'core\.?[0-9]*' -o -name '*.core' ')' -print0
00:04:46.300   10:04:44	# return 0
00:04:46.300   10:04:44	# autotest_cleanup
00:04:46.300   10:04:44	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/setup.sh reset
00:04:46.426  0000:84:00.0 (8086 2701): vfio-pci -> nvme
00:04:46.477  0000:00:04.0 (8086 0e20): vfio-pci -> ioatdma
00:04:46.537  0000:80:04.0 (8086 0e20): vfio-pci -> ioatdma
00:04:46.596  0000:00:04.1 (8086 0e21): vfio-pci -> ioatdma
00:04:46.655  0000:80:04.1 (8086 0e21): vfio-pci -> ioatdma
00:04:46.716  0000:00:04.2 (8086 0e22): vfio-pci -> ioatdma
00:04:46.772  0000:80:04.2 (8086 0e22): vfio-pci -> ioatdma
00:04:46.830  0000:00:04.3 (8086 0e23): vfio-pci -> ioatdma
00:04:46.887  0000:80:04.3 (8086 0e23): vfio-pci -> ioatdma
00:04:46.945  0000:00:04.4 (8086 0e24): vfio-pci -> ioatdma
00:04:47.002  0000:80:04.4 (8086 0e24): vfio-pci -> ioatdma
00:04:47.061  0000:00:04.5 (8086 0e25): vfio-pci -> ioatdma
00:04:47.118  0000:80:04.5 (8086 0e25): vfio-pci -> ioatdma
00:04:47.177  0000:00:04.6 (8086 0e26): vfio-pci -> ioatdma
00:04:47.234  0000:80:04.6 (8086 0e26): vfio-pci -> ioatdma
00:04:47.293  0000:00:04.7 (8086 0e27): vfio-pci -> ioatdma
00:04:47.348  0000:80:04.7 (8086 0e27): vfio-pci -> ioatdma
00:04:47.496   10:04:45	# /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/setup.sh cleanup
00:04:48.900  Cleaning
00:04:48.902  Removing:    /run/dpdk/spdk0/config
00:04:48.906  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-0
00:04:48.908  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-1
00:04:48.911  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-2
00:04:48.913  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-3
00:04:48.916  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-0
00:04:48.918  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-1
00:04:48.920  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-2
00:04:48.923  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-3
00:04:48.926  Removing:    /run/dpdk/spdk0/fbarray_memzone
00:04:48.928  Removing:    /run/dpdk/spdk0/hugepage_info
00:04:48.930  Removing:    /run/dpdk/spdk0/mp_socket
00:04:48.933  Removing:    /run/dpdk/spdk1/config
00:04:48.935  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-0
00:04:48.938  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-1
00:04:48.940  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-2
00:04:48.942  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-3
00:04:48.945  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-1-0
00:04:48.947  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-1-1
00:04:48.950  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-1-2
00:04:48.952  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-1-3
00:04:48.955  Removing:    /run/dpdk/spdk1/fbarray_memzone
00:04:48.957  Removing:    /run/dpdk/spdk1/hugepage_info
00:04:48.959  Removing:    /run/dpdk/spdk1/mp_socket
00:04:48.962  Removing:    /run/dpdk/spdk2/config
00:04:48.964  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-0
00:04:48.967  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-1
00:04:48.969  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-2
00:04:48.972  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-0-3
00:04:48.974  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-1-0
00:04:48.976  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-1-1
00:04:48.979  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-1-2
00:04:48.981  Removing:    /run/dpdk/spdk2/fbarray_memseg-2048k-1-3
00:04:48.984  Removing:    /run/dpdk/spdk2/fbarray_memzone
00:04:48.986  Removing:    /run/dpdk/spdk2/hugepage_info
00:04:48.989  Removing:    /run/dpdk/spdk2/mp_socket
00:04:48.991  Removing:    /run/dpdk/spdk3/config
00:04:48.993  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-0
00:04:48.996  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-1
00:04:48.998  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-2
00:04:49.000  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-0-3
00:04:49.003  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-1-0
00:04:49.005  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-1-1
00:04:49.008  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-1-2
00:04:49.010  Removing:    /run/dpdk/spdk3/fbarray_memseg-2048k-1-3
00:04:49.013  Removing:    /run/dpdk/spdk3/fbarray_memzone
00:04:49.015  Removing:    /run/dpdk/spdk3/hugepage_info
00:04:49.017  Removing:    /run/dpdk/spdk3/mp_socket
00:04:49.020  Removing:    /run/dpdk/spdk4/config
00:04:49.022  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-0
00:04:49.025  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-1
00:04:49.027  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-2
00:04:49.030  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-0-3
00:04:49.032  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-1-0
00:04:49.034  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-1-1
00:04:49.037  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-1-2
00:04:49.039  Removing:    /run/dpdk/spdk4/fbarray_memseg-2048k-1-3
00:04:49.042  Removing:    /run/dpdk/spdk4/fbarray_memzone
00:04:49.044  Removing:    /run/dpdk/spdk4/hugepage_info
00:04:49.046  Removing:    /run/dpdk/spdk4/mp_socket
00:04:49.049  Removing:    /dev/shm/nvmf_trace.0
00:04:49.068  Removing:    /var/run/dpdk/spdk0
00:04:49.071  Removing:    /var/run/dpdk/spdk1
00:04:49.074  Removing:    /var/run/dpdk/spdk2
00:04:49.076  Removing:    /var/run/dpdk/spdk3
00:04:49.079  Removing:    /var/run/dpdk/spdk4
00:04:49.079  Clean
00:04:49.081    10:04:47	# uname -s
00:04:49.082   10:04:47	# '[' Linux = Linux ']'
00:04:49.082   10:04:47	# grep -q '#define SPDK_CONFIG_IGB_UIO_DRIVER 1' /var/jenkins/workspace/nvmf-phy-autotest/spdk/include/spdk/config.h
00:04:49.083   10:04:47	# modprobe -r uio_pci_generic
00:04:49.086   10:04:47	# rm -rf /var/tmp/asan_suppression_file
00:04:49.087   10:04:47	# exit 1
00:04:59.101  Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
00:04:59.115  Build step 'Execute shell' marked build as failure
00:04:59.215  [PostBuildScript] - [INFO] Executing post build scripts.
00:04:59.224  [nvmf-phy-autotest] $ /usr/bin/env bash /tmp/jenkins8291380541573937484.sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_16110.html

**Comment by AlekseyMarchuk** [comment]
Looks like a duplicate of #1297

**Comment by optimistyzy** [comment]
close this issue, and refer to #1297

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_19280.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_23355.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_81469.html
