### ISSUE TITLE
[Multiple Tests] Failure in libvirt when starting vagrant VM for test.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1429]
# Link to the failed CI build 
https://ci.spdk.io/public_build/autotest-per-patch_16753.html

## Execution failed at
00:00:37.159  There was an error talking to Libvirt. The error message is shown
00:00:37.159  below:
00:00:37.159  
00:00:37.159  Call to virDomainCreateWithFlags failed: internal error: qemu unexpectedly closed the monitor: 2020-06-03T22:51:12.332547Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48CH).vmx-invept-single-context [bit 41]
00:00:37.159  2020-06-03T22:51:12.332563Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48CH).vmx-invvpid-all-context [bit 42]
00:00:37.159  2020-06-03T22:51:12.332578Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48CH).vmx-invept-single-context-noglobals [bit 43]
00:00:37.159  2020-06-03T22:51:12.332595Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(480H).vmx-ins-outs [bit 54]
00:00:37.159  2020-06-03T22:51:12.332611Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(480H).vmx-true-ctls [bit 55]
00:00:37.159  2020-06-03T22:51:12.381093Z qemu-system-x86_64: -device nvme,drive=nvme-0,serial=12340: Failed to get "write" lock
00:00:37.159  Is another process using the image [/var/lib/libvirt/images/backends/ex4-nvme.img]

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_16755.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_16756.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_16759.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_16766.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_16767.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_16768.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_16770.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_16776.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_16748.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_16747.html

**Comment by karlatec** [comment]
This problem was caused by CI misconfiguration.
Accidentally Jenkins instance was restarted while tests were running  on the slave nodes. This resulted in some VMs left running on VH Hosts (test scripts did not finish or traps did not fire because Jenkins was restarted).
When new VM instances were started they failed on attaching to backing files which were being already used/locked by leftover VMs.
After removing these leftover VMs the issue did not happen again. Additionally a patch was created for CI, which in future would prevent any "leftover" VMs from blocking backing files.

@tomzawadzki ok to close?
