### ISSUE TITLE
SPDK OCF RPC looks like cannot change OCF cacheline size.

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1432]
## Expected Behavior
there is no option for us to change the OCF cacheline size.

intel@intel:~/wayne/spdk$ sudo scripts/rpc.py bdev_ocf_create --help
usage: rpc.py bdev_ocf_create [-h] name {wb,wt,pt,wa,wi,wo} cache_bdev_name core_bdev_name

positional arguments:
  name                 Name of resulting OCF bdev
  {wb,wt,pt,wa,wi,wo}  OCF cache mode
  cache_bdev_name      Name of underlying cache bdev
  core_bdev_name       Name of unerlying core bdev

optional arguments:
  -h, --help           show this help message and exit
intel@intel:~/wayne/spdk$ 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Comphix** [comment]
@Michal, please take a look for this request.

**Comment by Donaim** [comment]
There was a patch that added the required RPC: https://review.gerrithub.io/c/spdk/spdk/+/470359
But it has not been finished

**Comment by gwnet** [comment]
@Donaim may I know how it is going on now? can we close this issue now?

**Comment by changpe1** [comment]
> @Donaim may I know how it is going on now? can we close this issue now?

Vitaly has left Intel, go ahead to close this issue.

**Comment by gwnet** [comment]
close this for now. this is already in the enhancement roadmap.
