### ISSUE TITLE
Missing bdev in bdev_hello_world test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1433]
Spotted here: https://ci.spdk.io/results/autotest-per-patch/builds/17068/archive/nvme-phy-autotest/build.log

`hello_bdev` failed since `$hello_world_bdev` ended up being empty after a call to `bdev_get_bdevs`. So either the nvme dev was still claimed when the test was run, or it suddenly disappeared (0000:84:00.0 was initially detected by `setup.sh`)?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_17068.html

**Comment by shuhei-matsumoto** [comment]
Hi @mikeBashStuff 

Thank you but this will be same as #1435 . So let's close this for now.
