### ISSUE TITLE
[iscsi_tgt_bdev_io_wait] within vpp-autotest #15836

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1438]
00:07:35.434  [2020-06-13 22:38:02.900896] vpp.c:1440:vpp_application_detached: *NOTICE*: Application detached
00:08:01.105  /var/jenkins/workspace/vpp-autotest/spdk/test/common/autotest_common.sh: line 744: 387334 Segmentation fault      (core dumped) "${ISCSI_APP[@]}" -m 0x2 -p 1 -s 512 --wait-for-rpc

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_18227.html

**Comment by optimistyzy** [comment]
@peluse  VPP related test will be deprecated for 20.07 release. We can keep it open, but we may not focus to solve the issue.

**Comment by tomzawadzki** [comment]
That's right, patch to ignore skipping VPP test was merged today [here](https://review.spdk.io/gerrit/c/spdk/spdk/+/2771). 
Soon Jenkins won't run the VPP jobs at all. Currently waiting couple days, so that everyone has a chance to rebase on top of it.
