### ISSUE TITLE
Can't open uio device on Ubuntu16.10

### ISSUE THREAD

**Issue by brave-hannah** [spdk/spdk#144]
I am trying to run perf example on Ubuntu16.10 with Intel P3600 SSD. But when I execute the perf exe, I get this output like
_EAL: XXX
EAL: XXX
Could not open AIO device /dev/uio0: Invalid argument
./perff: errors occured_
I guess if something should be set on Ubuntu16.10 before run spdk ? Except running setup.sh.

**Comment by jimharris** [comment]
It looks like maybe /dev/uio0 was specified on the command line. Can you try running perf without that?

By default, perf will use the SPDK driver for all NVMe devices attached to uio/vfio. Specifying a device node on the command line is only needed to tell perf to use Linux AIO with an NVMe device attached to the kernel driver.  This feature allows perf to be used for SPDK v. Kernel performance comparisons.

On Apr 21, 2017, at 6:39 AM, brave-hannah <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to run perf example on Ubuntu16.10 with Intel P3600 SSD. But when I execute the perf exe, I get this output like
EAL: XXX
EAL: XXX
Could not open AIO device /dev/uio0: Invalid argument
./perff: errors occured
I guess if something should be set on Ubuntu16.10 before run spdk ? Except running setup.sh.

**Comment by brave-hannah** [comment]
Yes, you are right. 
I have misunderstood of the "help" content. The right thing is ---- Using the -r option to assign the PCIe card instead of inputing the uio device name at the end of command.

**Comment by benlwalker** [comment]
Glad you have this part sorted out. I'm going to close this issue.
