### ISSUE TITLE
[nvme_cli] Incorrect nvme-cli version installed on some CI machines

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1448]
Machine `GP14` contains incorrect nvme-cli version installed in `/home/sys_sgsw/nvme-cli/`. Possibly other machines too.

This [patch ](https://review.spdk.io/gerrit/c/spdk/spdk/+/2948/) can verify that among machines.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/18649/archive/nvme-phy-autotest/build.log

## Execution failed at
```
NVME_VERSION = 1.3.406.gcb30.dirty
...
00:03:40.051   14:21:48	# ./nvme id-ctrl 0000:84:00.0
00:03:40.053  0000:84:00.0: No such file or directory
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_18732.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_18741.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_18765.html

**Comment by tomzawadzki** [comment]
Turns out there are couple issues around nvme-cli:
1) Repo at the `${DEPENDENCY_DIR}/nvme-cli` got corrupted over time (incorrect `.git/index`, *.gcda or core dumps left over). @karlatec made sure that every machine now contained clean repository (thx!).
2) `NVME_VERSION = 1.3.406.gcb30.dirty` was judged by the `git describe` from tags in spdk/nvme-cli repo. Where the v1.6 tag was missing. This has been added to the repository now.
3) NVMe-oF tests depended on nvme-cli, but did not compile it itself. So the two out of three above comments referred to that. Patch has been submitted to resolve that [here](https://review.spdk.io/gerrit/c/spdk/spdk/+/2970/3).

Overall a series fixing the tests was [submitted](https://review.spdk.io/gerrit/q/topic:%22nvme-cli%22).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20009.html

**Comment by tomzawadzki** [comment]
[Series](https://review.spdk.io/gerrit/c/spdk/spdk/+/2836) was merged, this issue can be closed.
