### ISSUE TITLE
spdk_nvme_ctrlr_free_io_qpair may have deadlock issue

### ISSUE THREAD

**Issue by sqiu110** [spdk/spdk#1449]
spdk_nvme_ctrlr_free_io_qpair grab ctrlr->ctrlr_lock while calling nvme_transport_ctrlr_delete_io_qpair, while inside nvme_transport_ctrlr_delete_io_qpair it may submit request to adminq which also try to grab ctrlr->ctrlr_lock. 
As a result cause deadlock.

![image](https://user-images.githubusercontent.com/43693104/85214600-c1817180-b321-11ea-8016-6ed42034fc00.png)

should we release ctrlr->ctrlr_lock before calling nvme_transport_ctrlr_delete_io_qpair?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by AlekseyMarchuk** [comment]
Hi @sqiu110 

`ctrlr->ctrlr_lock` is a recursive mutex, that means that it can be locked multiple times by the same thread without deadlocks. Scenario that you described is a normal qpair destruction flow and it is well tested. Could you clarify your SPDK and OS versions?

**Comment by sqiu110** [comment]
Hi @AlekseyMarchuk 

Thanks for you kind response. We identified that there are two threads try to lock ctrlr->ctrlr_lock, this is probably the cause.
How do you think?

**Comment by AlekseyMarchuk** [comment]
@sqiu110 Yes, accessing controller structure from multiple threads can cause this issue.
Can you provide a call stack of both threads?

**Comment by tomzawadzki** [comment]
@sqiu110 Have you had a chance to gather more details on this issue and does it happen on latest SPDK ?

**Comment by tomzawadzki** [comment]
No update for last 5 months. @sqiu110 please re-open this issue if it occurs on latest SPDK.
