### ISSUE TITLE
spdk_nvme_connect API can not get namespace information or (struct spdk_nvme_ctrlr_data *cdata）（）

### ISSUE THREAD

**Issue by dashan8020** [spdk/spdk#1453]
## Expected Behavior
if spdk_nvme_connect  calling success, then get the namespace information or controller info successfully

## Current Behavior
spdk_nvme_connect  calling success, and can not get namespace info or cdata correctly.

after calling spdk_nvme_connect successfully,
I got the cdata via calling spdk_nvme_ctrlr_get_data(), but cdata is empty without valid content.
I got namespace id  = 0 via calling spdk_nvme_ctrlr_get_first_active_ns()
if I call spdk_nvme_probe(), above information is ok.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by optimistyzy** [comment]
@dashan8020 When you close this issue. Could update some reasons? Then others can also learn from it.
