### ISSUE TITLE
rocksdb-spdk test faild : nvme_pcie.c:1815:nvme_pcie_prp_list_append: *ERROR*: virt_addr 0x200025f8f1c1 not dword aligned

### ISSUE THREAD

**Issue by jasunliu** [spdk/spdk#1454]
cockroach rocksdb using spdk env, run tpcc test workload 6000 faild.
error  log:
nvme_pcie.c:1815:nvme_pcie_prp_list_append: *ERROR*: virt_addr 0x200025f8f1c1 not dword aligned
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:509 nsid:1 lba:265465865 len:1
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:1 cid:509 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
bdev_nvme.c:2411:bdev_nvme_writev: *ERROR*: writev failed: rc = -14

**Comment by changpe1** [comment]
@jasunliu could you provide the whole test script command line here, I think maybe it's SPDK bug, for most READ/WRITE cases, SPDK blobfs will use internal cache buffer, if the payload was from Rocksdb, I think it may hit this issue.

**Comment by jasunliu** [comment]
@changpe1  I modified Cockroachdb's rocksdb default env using SPDK env. The test steps are as follows:
1、sudo ./cockroach start --insecure --store=/data8/cockroach-data --max-sql-memory=.10 --cache=.10 --listen-addr=10.110.10.53:27555 --http-addr=10.110.10.53:8099 --background
2、sudo ./cockroach workload init tpcc --warehouses 6000 'postgresql://root@10.110.10.53:27555?sslmode=disable'

**Comment by tomzawadzki** [comment]
Description given by @jasunliu on modifying Cockroachdb cmd line does not look like an SPDK issue. If this indeed requires changes in SPDK, please feel free to re-open this issue.

**Comment by skypexu** [comment]
I think this is a spdk bug, because spdk document has nowhere said that virt address must be double world aligned

**Comment by changpe1** [comment]
> I think this is a spdk bug, because spdk document has nowhere said that virt address must be double world aligned

dword alignment is requirement by physical NVMe SSDs, if the data buffers are managed by your own application, you should follow the restrictions.

For more buffer alignment requirements, you may refer to your SSD specification and NVMe specification.
