### ISSUE TITLE
Whether SPDK supports Intel Optane SSD?

### ISSUE THREAD

**Issue by SuFredyTing** [spdk/spdk#146]
Hi guys, I would like to know whether our latest SPDK version supports Intel Optane SSD?  Thanks!

**Comment by optimistyzy** [comment]
Yes, latest SPDK supports Optane SSD.

**Comment by benlwalker** [comment]
The Intel Optane SSD DC P4800X is supported. Specifically, use commit b5b9410 or later. This commit is after the 17.03 release tag. I believe the final release version of P4800X works with the 17.03 release, but most people have a pre-release sample as of right now so you'll need the workaround in b5b9410 to make it initialize reliably.

**Comment by SuFredyTing** [comment]
Thanks for your answer.
