### ISSUE TITLE
If SPDK installed in custom location, links against libraries fail to find dependent libs

### ISSUE THREAD

**Issue by jolivier23** [spdk/spdk#1461]
I would like to be able to link with an spdk library and have it find it's dependencies automatically.   It can use DT_RUNPATH for this

-Wl,-rpath=/path/to/install -Wl,--enable-new-dtags

This adds the path to the RPATH in the library.   It may also be helpful to add $ORIGIN into the rpath for finding libraries at runtime even if the library is relocated.

Presently, without -rpath-link being set, the linker will not find the dependent libraries.   RUNPATH isn't legal in RPMS so it should be an option.

In DAOS, we have added a pass using the patchelf executable to set the rpath as we want it on the libraries we just built.   We would use LDFLAGS environment variable but setting $ORIGIN through that is almost impossible.

Currently, spdk adds no runpath to binaries and has no good option for adding it.   LDFLAGS is practically impossible to use when setting $ORIGIN

add an option to configure that will cause the build to add $ORIGIN:/path/to/install to the runpath

Build spdk to a prefix location and link against one of its shared libraries that depends on other libraries.

1. Build spdk with shared libraries in a custom location
2. gcc some_app.c -L/path/to/spdk/lib -lrte_bus_pci
3. This should fail to find a bunch of dependencies
4. With RPATH settings above, it works fine.

SPDK v20.01.1
Any platform though I used Fedora31

**Comment by Seth5141** [comment]
Hello @jolivier23 Thanks for the suggestion. I will look into adding that option for the current release (20.07). It seems like using -rpath will be a nice add-on for convenience. Thanks to the outline you gave in your issue, it should be pretty easy to plumb it through the Makefiles.

In the meantime, may I propose a workaround?

You can specify -rpath when you build your application to achieve the same effect. Here is an example from the shared object build of a hello_bdev application located in the test/external_code directory of SPDK.
~~~
$(CC) $(COMMON_CFLAGS) -Wl,-rpath=$(SPDK_LIB_DIR),--no-as-needed -o hello_bdev ./hello_bdev.c -lspdk_event_bdev \
	-lspdk_bdev -lspdk_bdev_malloc -lspdk_log -lspdk_thread -lspdk_util -lspdk_event -lspdk_env_dpdk -ldpdk
~~~

I'll push some changes to Gerrit this week and post a link here. I'd appreciate your review on them. Thanks!

**Comment by Seth5141** [comment]
Hi @jolivier23 Sorry about the lag time here, I have been getting pulled a lot of different ways lately. I did a quick patch adding the library dir in https://review.spdk.io/gerrit/c/spdk/spdk/+/3361. It concatenates DESTDIR and libdir ($prefix/lib) to come up with the install directory.

Please let me know if this works for your use case.

Thanks,

Seth

**Comment by jolivier23** [comment]
Hi Seth, that should work.  I'm out for a couple of days but will try next week.  In the meantime, I looked at the diff.   You might also want to add --Wl,--enable-new-dtags at least for older linkers as it changes the default to RUNPATH from RPATH.   This means that LD_LIBRARY_PATH will take precedence if set which is generally desired.  RPATH is deprecated but many systems still have it as the default though that is changing.

**Comment by jimharris** [comment]
Patch 3361 was merged a while back.  Closing this issue.  @jolivier23, if you still see any problems, please reopen.
