### ISSUE TITLE
[iscsi_tgt_filesystem] iscsiadm: Failed to query iSCSI sessions, error 1: BUG of libopeniscsiusr library

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1462]

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_19530.html

**Comment by optimistyzy** [comment]
@peluse The log said that it is bug of libopeniscsiusr library, we may firstly mark it as third party issue.

**Comment by tomzawadzki** [comment]
I would be hesitant to update the open-iscsi initiator outside of the usual packaged versions in distros. Thus suggest leaving it as is.

Noting down for posterity the probable fix:
[bug report](https://bugs.launchpad.net/os-brick/+bug/1814849) -> [supposed fix](https://github.com/open-iscsi/open-iscsi/commit/baa0cb45cfcf10a81283c191b0b236cd1a2f66ee)

**Comment by tomzawadzki** [comment]
[Bug scrub]: Let's leave it up for a week to report intermittent failures against. If no new reports show up, it will be closed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20262.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_21448.html
