### ISSUE TITLE
[confirm_abi_deps] SO name for libspdk_scsi.so changed without a change to abi. please revert that change.

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1463]
00:06:40.052  ************************************
00:06:40.052  START TEST confirm_abi_deps
00:06:40.052  ************************************
00:06:44.848  No corresponding object for libspdk_rdma.so in canonical directory. Skipping.
00:06:45.036  SO name for libspdk_scsi.so changed without a change to abi. please revert that change.
00:06:45.519  Processed 56 objects.
00:06:45.519  
00:06:45.519  real	0m5.466s
00:06:45.519  user	0m4.648s
00:06:45.519  sys	0m0.780s
00:06:45.519  ************************************
00:06:45.519  END TEST confirm_abi_deps
00:06:45.519  ************************************

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_19649.html

## Execution failed at

00:06:40.052  ************************************
00:06:40.052  START TEST confirm_abi_deps
00:06:40.052  ************************************
00:06:44.848  No corresponding object for libspdk_rdma.so in canonical directory. Skipping.
00:06:45.036  SO name for libspdk_scsi.so changed without a change to abi. please revert that change.
00:06:45.519  Processed 56 objects.
00:06:45.519  
00:06:45.519  real	0m5.466s
00:06:45.519  user	0m4.648s
00:06:45.519  sys	0m0.780s
00:06:45.519  ************************************
00:06:45.519  END TEST confirm_abi_deps
00:06:45.519  ************************************
00:06:45.554  ---------------------------------------------------------------------
00:08:20.895  Updated 1 path from the index
00:08:20.899  shared object test failed
00:08:20.900    14:50:37	$ trap - ERR
00:08:20.900    14:50:37	$ print_backtrace
00:08:20.900    14:50:37	$ [[ ehxBET =~ e ]]
00:08:20.900    14:50:37	$ args=("${BASH_ARGV[@]}")
00:08:20.901    14:50:37	$ local args
00:08:20.901    14:50:37	$ xtrace_disable
00:08:20.901    14:50:37	$ '[' no '!=' yes ']'
00:08:20.902    14:50:37	$ PREV_BASH_OPTS=ehxBET
00:08:20.902    14:50:37	$ [[ ehxBET == *\x* ]]
00:08:20.902    14:50:37	$ XTRACE_DISABLED=yes
00:08:20.902    14:50:37	$ set +x
00:08:20.902  ========== Backtrace start: ==========
00:08:20.902  
00:08:20.911  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:873 -> run_test(["autobuild_check_so_deps"],["/home/vagrant/spdk_repo/spdk/test/make/check_so_deps.sh"],["/home/vagrant/autorun-spdk.conf"])
00:08:20.911       ...
00:08:20.911     868 		timing_enter $test_name
00:08:20.911     869 		echo "************************************"
00:08:20.911     870 		echo "START TEST $test_name"
00:08:20.911     871 		echo "************************************"
00:08:20.911     872 		xtrace_restore
00:08:20.911  => 873 		time "$@"
00:08:20.911     874 		xtrace_disable
00:08:20.911     875 		echo "************************************"
00:08:20.911     876 		echo "END TEST $test_name"
00:08:20.911     877 		echo "************************************"
00:08:20.911     878 		timing_exit $test_name
00:08:20.911       ...
00:08:20.918  in /home/vagrant/spdk_repo/spdk/autobuild.sh:158 -> autobuild_test_suite(["/home/vagrant/autorun-spdk.conf"])
00:08:20.918       ...
00:08:20.918     153 		run_test "autobuild_check_format" ./scripts/check_format.sh
00:08:20.918     154 		run_test "autobuild_external_code" sudo -E $rootdir/test/external_code/test_make.sh $rootdir
00:08:20.918     155 		if [ "$SPDK_TEST_OCF" -eq 1 ]; then
00:08:20.918     156 			run_test "autobuild_ocf_precompile" ocf_precompile
00:08:20.918     157 		fi
00:08:20.918  => 158 		run_test "autobuild_check_so_deps" $rootdir/test/make/check_so_deps.sh $1
00:08:20.918     159 		run_test "scanbuild_make" scanbuild_make
00:08:20.918     160 		run_test "autobuild_generated_files_check" porcelain_check
00:08:20.918     161 		run_test "autobuild_header_dependency_check" header_dependency_check
00:08:20.918     162 		run_test "autobuild_make_install" $MAKE $MAKEFLAGS install DESTDIR="$SPDK_WORKSPACE" prefix=/usr
00:08:20.918     163 		run_test "autobuild_make_uninstall" test_make_uninstall
00:08:20.918       ...
00:08:20.923  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:873 -> run_test(["autobuild"],["autobuild_test_suite"],["/home/vagrant/autorun-spdk.conf"])
00:08:20.923       ...
00:08:20.923     868 		timing_enter $test_name
00:08:20.923     869 		echo "************************************"
00:08:20.923     870 		echo "START TEST $test_name"
00:08:20.923     871 		echo "************************************"
00:08:20.923     872 		xtrace_restore
00:08:20.923  => 873 		time "$@"
00:08:20.923     874 		xtrace_disable
00:08:20.923     875 		echo "************************************"
00:08:20.923     876 		echo "END TEST $test_name"
00:08:20.923     877 		echo "************************************"
00:08:20.923     878 		timing_exit $test_name
00:08:20.923       ...
00:08:20.928  in /home/vagrant/spdk_repo/spdk/autobuild.sh:180 -> main(["/home/vagrant/autorun-spdk.conf"])
00:08:20.928       ...
00:08:20.928     175 	if [ $SPDK_RUN_UBSAN -eq 1 ]; then
00:08:20.928     176 		run_test "ubsan" echo "using ubsan"
00:08:20.928     177 	fi
00:08:20.928     178 	
00:08:20.928     179 	if [ "$SPDK_TEST_AUTOBUILD" -eq 1 ]; then
00:08:20.928  => 180 		run_test "autobuild" autobuild_test_suite $1
00:08:20.928     181 	else
00:08:20.928     182 		if [ "$SPDK_TEST_OCF" -eq 1 ]; then
00:08:20.928     183 			run_test "autobuild_ocf_precompile" ocf_precompile
00:08:20.928     184 		fi
00:08:20.928     185 		run_test "make" $MAKE $MAKEFLAGS
00:08:20.928       ...
00:08:20.928  
00:08:20.928  ========== Backtrace end ==========

**Comment by AlekseyMarchuk** [comment]
@tomzawadzki  prepared a fix https://review.spdk.io/gerrit/c/spdk/spdk/+/3114

**Comment by changpe1** [comment]
OK, that's reason why I need to bump the version number without changing the public header file.

**Comment by changpe1** [comment]
Closing this issue now as the patch was merged.
