### ISSUE TITLE
docs:  block device user guide out of date / light on content

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1464]
From a slack conversation, community member trying to create a new bdeve module:

the two things that caused the most difficulty for me (as someone just starting out) were, first, this section in the linked doc:
Block device modules are located in subdirectories under lib/bdev today. It is not currently possible to place the code for a bdev module elsewhere, but updates to the build system could be made to enable this in the future. To create a module, add a new directory with a single C file and a Makefile. A great starting point is to copy the existing ‘null’ bdev module.
It looks like at some point the build system was updated, because new bdevs are implemented in separate directories under module/bdev/ now.
The second is integrating a new module into the build system, there are multiple places in the mk directory which need to be modified. I had to add my module to lists in mk/spdk.lib_deps.mk and mk/spdk.modules.mk in order for it to be registered properly.
The last point which caused me confusion is that there doesn’t appear to be a section which discusses how the JSON RPC config files are parsed. I spent quite a while looking for an example of a configuration to use, and google eventually led me to this comment on an issue in the git repo: https://github.com/spdk/spdk/issues/1404#issuecomment-633810483

**Comment by peluse** [comment]
be sure to include details on an out of tree bdev moduole

**Comment by jimharris** [comment]
Hi @mkenguva,

I know you posted some updates to the bdev user guide.  Can we close this issue now?  Or are there other sections that need updating by their respective owners?

Thanks,

Jim

**Comment by mkenguva** [comment]
I have updated regarding the above pointers and other updates. FTL and Zone block needs update from owners. This issue can be closed i believe. Apologize havent notified here.

**Comment by jimharris** [comment]
Thanks @mkenguva!
