### ISSUE TITLE
Build timeout during autotest_cleanup

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1465]
https://ci.spdk.io/results/autotest-per-patch/builds/19725/archive/iscsi-autotest/build.log - hit timeout during lcov run.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_19725.html

**Comment by tomzawadzki** [comment]
This is not a bug, it is directly related to the tested series.

Patch [2898](https://review.spdk.io/gerrit/c/spdk/spdk/+/2898/23) adds 3 minutes to every single job that runs functional tests:
```
autotest;lib;spdk_dd;spdk_dd_basic_rw 170
autotest;lib;spdk_dd;spdk_dd_posix;append 1
autotest;lib;spdk_dd;spdk_dd_posix;directory 1
autotest;lib;spdk_dd;spdk_dd_posix;nofollow 1
autotest;lib;spdk_dd;spdk_dd_posix;noatime 2
autotest;lib;spdk_dd;spdk_dd_posix;noctty 0
autotest;lib;spdk_dd;spdk_dd_posix;io 3
autotest;lib;spdk_dd;spdk_dd_posix 0
autotest;lib;spdk_dd 1
```

**Comment by mikeBashStuff** [comment]
@tomzawadzki For `spdk_dd_basic_rw` there's no much I can do about it except lowering the number of `spdk_dd` runs.
