### ISSUE TITLE
[nvmf_nvme_cli] libspdk_bdev_ocf.so.2.0 was not found

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1469]
./nvme: error while loading shared libraries: libspdk_bdev_ocf.so.2.0: cannot open shared object file: No such file or directory

The patch merged today is related with this issue?
https://github.com/spdk/spdk/commit/40d20acb72eeb1bdc6d44faf744f6c149e781dfd

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/20123/archive/nvmf-phy-autotest/build.log

## Execution failed at

```
00:03:04.810  ./nvme: error while loading shared libraries: libspdk_bdev_ocf.so.2.0: cannot open shared object file: No such file or directory
00:03:04.811    12:11:28	# trap - ERR
00:03:04.811    12:11:28	# print_backtrace
00:03:04.811    12:11:28	# [[ ehxBET =~ e ]]
00:03:04.812    12:11:28	# args=("${BASH_ARGV[@]}")
00:03:04.812    12:11:28	# local args
00:03:04.812    12:11:28	# xtrace_disable
00:03:04.812    12:11:28	# '[' no '!=' yes ']'
00:03:04.812    12:11:28	# PREV_BASH_OPTS=ehxBET
00:03:04.812    12:11:28	# [[ ehxBET == *\x* ]]
00:03:04.812    12:11:28	# XTRACE_DISABLED=yes
00:03:04.812    12:11:28	# set +x
00:03:04.813  ========== Backtrace start: ==========
00:03:04.813  
00:03:04.815  in test/nvmf/target/nvme_cli.sh:61 -> main(["--transport=rdma"])
00:03:04.815       ...
00:03:04.815  backtrace unavailable
00:03:04.815       ...
00:03:04.815  
00:03:04.815  ========== Backtrace end ==========

```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20120.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20123.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20115.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_20142.html

**Comment by tomzawadzki** [comment]
Hi @shuhei-matsumoto I think this might be related to the [patch ](https://github.com/spdk/spdk/commit/40d20acb72eeb1bdc6d44faf744f6c149e781dfd)you've linked and my series on [nvme-cli](https://review.spdk.io/gerrit/q/topic:%22nvme-cli%22+(status:open%20OR%20status:merged)) .

The series makes it so that nvme-cli repo is cleared between tests and nvmf tests compile the nvme-cli on their own (instead of depending on pre-existing binaries). Since the patches are in review, the CI ran and rebuilt the nvme-cli - meanwhile other patches still depended on old binaries.

I'll take a shot at seeing what's the issue with shared objects and nvme-cli.

**Comment by tomzawadzki** [comment]
After considering the options, the issue comes not from the series I've linked to.

The reason is that **nvmf** tests don't compile nvme-cli on their own. Build of nvme-cli remains from previous run of **nvme**-phys job. Meaning that patches with parents pointing to different points in time, cause failures between each other.

With that in mind the solution is [here](https://review.spdk.io/gerrit/c/spdk/spdk/+/2970/).

**Comment by shuhei-matsumoto** [comment]
Thank you @tomzawadzki !

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_20322.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20324.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20358.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20351.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20366.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20281.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20288.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20286.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20287.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_20355.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20375.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_20371.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_20380.html

**Comment by peluse** [comment]
@tomzawadzki FYI I have many patches that are consistently hitting this now - not sure intermittent  is an appropriate label :)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_20394.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_20350.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20428.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20384.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_20433.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20435.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_20449.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_20445.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_20456.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20458.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20454.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20534.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_20584.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_21071.html
