### ISSUE TITLE
NVMF targets in cluster

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#147]
I tried to run 12 nodes cluster with 2 NVME in each node. I created 2 nvmf targets on each node with this config

config:

[Global]
ReactorMask 0xFFFF
LogFacility "local7"

[Rpc]
Enable No
Listen 127.0.0.1

[Nvmf]
MaxQueuesPerSession 2
MaxQueueDepth 128
AcceptorPollRate 100000

[Subsystem1]
NQN nqn.2016-06.io.spdk.node1_1
Mode Direct
Core 0
Listen RDMA 10.30.0.1:4420
NVMe 0000:81:00.0

[Subsystem2]
NQN nqn.2016-06.io.spdk.node1_2
Mode Direct
Core 1
Listen RDMA 10.30.0.1:4421
NVMe 0000:82:00.0

after Successfully started 24 targets I began discovering them like this 
$ nvme discover  -t rdma -a 10.30.0.1 -s 4420

And the problem is that on some nodes discovering is finished with no errors , but on the other nodes I got "Failed to write to /dev/nvme-fabrics: connection reset by peer" .  Even though  ping to those nodes goes well.
In the /var/log/messages 
"
kernel: [ 2333.533120] nvme nvme0: Connect rejected, status 0.
kernel: [ 2333.533169] nvme nvme0: rdma_resolve_addr wait failed (-104).
"

All nodes have the same linux kernel 4.9.22 and Mellanox Ofed drivers . 
What possible problems do you see here? Are there any limits on the number of targets or connections?  Where could I investigate this problem?

Appreciate any ideas..

**Comment by dverkamp-intel** [comment]
If you are attempting to connect to the same subsystem on the same target more than once simultaneously, you will hit the limit you specified with "MaxQueuesPerSession 2" (you should see an error about "connection limit" on the target if this is the case).  MaxQueuesPerSession is the maximum number of connections for the RDMA transport, and each unique host will use up at least 2 connections (one admin queue and one I/O queue).  If you need to be able to connect to a target from more than one host at a time, you will need to increase MaxQueuesPerSession.

For additional information about what is happening on the target side, you can build with CONFIG_DEBUG=y and enable tracing (e.g. run `nvmf_tgt -t all` in addition to your normal configuration).

**Comment by dverkamp-intel** [comment]
Sorry, some of the above is incorrect - I misread the check for maximum connections.  The limit on connections is per session (host:target combination), not global to the subsystem, so connecting many separate sessions to the same target should still work with MaxQueuesPerSession2; each session will just be able to connect one I/O queue.

However, the tracing suggestion is still a good idea - you may be able to tell what is happening by enabling tracing to see if any obvious errors are occurring.

**Comment by alekseymmm** [comment]
I understand the meaning of MaxQueuesPerSession, but just for luck increased it to 32. Enabled debug and started target with additional logging:
app/nvmf_tgt/nvmf_tgt -c etc/spdk/nvmf.conf.in  -t all
...
[nvmf] nvmf.c:  68:spdk_nvmf_tgt_init: Max Queues Per Session: 32
[nvmf] nvmf.c:  69:spdk_nvmf_tgt_init: Max Queue Depth: 128
[nvmf] nvmf.c:  70:spdk_nvmf_tgt_init: Max In Capsule Data: 4096 bytes
[nvmf] nvmf.c:  71:spdk_nvmf_tgt_init: Max I/O Size: 131072 bytes
*** RDMA Transport Init ***
allocated subsystem nqn.2014-08.org.nvmexpress.discovery on lcore 0 on socket 0
allocated subsystem nqn.2016-06.io.spdk.raidix3_1 on lcore 0 on socket 0
[rdma] rdma.c:1177:spdk_nvmf_rdma_listen: For listen id 0x1b22d70 with context 0x1b25aa0, created completion channel 0x1b220d0
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
[nvme] nvme_ctrlr.c: 507:nvme_ctrlr_set_state: setting state to init (no timeout)
[nvme] nvme_ctrlr.c:1148:nvme_ctrlr_process_init: CC.EN = 1
[nvme] nvme_ctrlr.c:1162:nvme_ctrlr_process_init: Setting CC.EN = 0
[nvme] nvme_ctrlr.c: 511:nvme_ctrlr_set_state: setting state to disable and wait for CSTS.RDY = 0 (timeout 127500 ms)
[nvme] nvme_ctrlr.c:1208:nvme_ctrlr_process_init: CC.EN = 0 && CSTS.RDY = 0
[nvme] nvme_ctrlr.c: 511:nvme_ctrlr_set_state: setting state to enable controller by writing CC.EN = 1 (timeout 127500 ms)
[nvme] nvme_ctrlr.c:1220:nvme_ctrlr_process_init: Setting CC.EN = 1
[nvme] nvme_ctrlr.c: 511:nvme_ctrlr_set_state: setting state to wait for CSTS.RDY = 1 (timeout 127500 ms)
[nvme] nvme_ctrlr.c:1227:nvme_ctrlr_process_init: CC.EN = 1 && CSTS.RDY = 1 - controller is ready
[nvme] nvme_ctrlr.c: 607:nvme_ctrlr_identify: transport max_xfer_size 2072576
[nvme] nvme_ctrlr.c: 686:nvme_ctrlr_set_keep_alive_timeout: Controller KAS is 0 - not enabling Keep Alive
[nvme] nvme_ctrlr.c: 507:nvme_ctrlr_set_state: setting state to ready (no timeout)
Attaching NVMe device 0x7f33739bf780 at 0000:81:00.0 to subsystem nqn.2016-06.io.spdk.raidix3_1
Subsystem nqn.2016-06.io.spdk.raidix3_1 is configured to run on a CPU core 0 belonging to a different NUMA node than the associated NVMe device. This may result in reduced performance.
The NVMe device is on socket 1
The Subsystem is on socket 0
allocated subsystem nqn.2016-06.io.spdk.raidix3_2 on lcore 1 on socket 0
[rdma] rdma.c:1177:spdk_nvmf_rdma_listen: For listen id 0x1b58bf0 with context 0x1b25aa0, created completion channel 0x1b58860
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 1c58:3 spdk_nvme
[nvme] nvme_ctrlr.c: 507:nvme_ctrlr_set_state: setting state to init (no timeout)
[nvme] nvme_ctrlr.c:1148:nvme_ctrlr_process_init: CC.EN = 1
[nvme] nvme_ctrlr.c:1162:nvme_ctrlr_process_init: Setting CC.EN = 0
[nvme] nvme_ctrlr.c: 511:nvme_ctrlr_set_state: setting state to disable and wait for CSTS.RDY = 0 (timeout 127500 ms)
[nvme] nvme_ctrlr.c:1208:nvme_ctrlr_process_init: CC.EN = 0 && CSTS.RDY = 0
[nvme] nvme_ctrlr.c: 511:nvme_ctrlr_set_state: setting state to enable controller by writing CC.EN = 1 (timeout 127500 ms)
[nvme] nvme_ctrlr.c:1220:nvme_ctrlr_process_init: Setting CC.EN = 1
[nvme] nvme_ctrlr.c: 511:nvme_ctrlr_set_state: setting state to wait for CSTS.RDY = 1 (timeout 127500 ms)
[nvme] nvme_ctrlr.c:1227:nvme_ctrlr_process_init: CC.EN = 1 && CSTS.RDY = 1 - controller is ready
[nvme] nvme_ctrlr.c: 607:nvme_ctrlr_identify: transport max_xfer_size 2072576
[nvme] nvme_ctrlr.c: 686:nvme_ctrlr_set_keep_alive_timeout: Controller KAS is 0 - not enabling Keep Alive
[nvme] nvme_ctrlr.c: 507:nvme_ctrlr_set_state: setting state to ready (no timeout)
Attaching NVMe device 0x7f337396a680 at 0000:82:00.0 to subsystem nqn.2016-06.io.spdk.raidix3_2
Subsystem nqn.2016-06.io.spdk.raidix3_2 is configured to run on a CPU core 1 belonging to a different NUMA node than the associated NVMe device. This may result in reduced performance.
The NVMe device is on socket 1
The Subsystem is on socket 0
Acceptor running on core 0 on socket 0
*** NVMf Target Listening on 10.30.0.3 port 4420 ***
*** NVMf Target Listening on 10.30.0.3 port 4421 ***

Try connecting from some nodes. Everything is ok.  From the others it is still "Failed to write to /dev/nvme-fabrics: connection reset by peer" and no additional messages on the target side. 

On successful   discovering I got a lot of messages on the target side . Like this:
[rdma] rdma.c:1062:spdk_nvmf_rdma_acceptor_poll: Acceptor Event: RDMA_CM_EVENT_CONNECT_REQUEST
[rdma] rdma.c: 573:nvmf_rdma_connect: Connect Recv on fabric intf name mlx5_0, dev_name uverbs0
[rdma] rdma.c: 577:nvmf_rdma_connect: Listen Id was 0x1b22d70 with verbs 0x1b25aa0. ListenAddr: 0x1b25260
[rdma] rdma.c: 583:nvmf_rdma_connect: Calculating Queue Depth
[rdma] rdma.c: 588:nvmf_rdma_connect: Target Max Queue Depth: 128
[rdma] rdma.c: 593:nvmf_rdma_connect: Local NIC Max Send/Recv Queue Depth: 32768 Max Read/Write Queue Depth: 16
[rdma] rdma.c: 600:nvmf_rdma_connect: Host (Initiator) NIC Max Incoming RDMA R/W operations: 16 Max Outgoing RDMA R/W operations: 0
...
[rdma] rdma.c:1486:spdk_nvmf_rdma_poll: RDMA SEND Complete. Request: 0x1b66eb0 Connection: 0x1b58fb0 Outstanding I/O: 0
[rdma] rdma.c:1062:spdk_nvmf_rdma_acceptor_poll: Acceptor Event: RDMA_CM_EVENT_DISCONNECTED

They are look ok.

What is curious is that when I got "connection reset by peer" on some hosts then there are no messages  on the target side. It seems like they are rejected not by the target but by the kernel. It is really unclear why, because all the system have the same software and kernel.

Any ideas where to investigate?  May be it I should try it with the kernel 4.10 ? Or older version of Mellanox ofed driver (I use  4.0-2)?

**Comment by alekseymmm** [comment]
Sometimes  I got this log on the target side with enabled debugging^

[rdma] rdma.c:1062:spdk_nvmf_rdma_acceptor_poll: Acceptor Event: RDMA_CM_EVENT_CONNECT_REQUEST
[rdma] rdma.c: 573:nvmf_rdma_connect: Connect Recv on fabric intf name mlx5_0, dev_name uverbs0
[rdma] rdma.c: 577:nvmf_rdma_connect: Listen Id was 0x1b22d70 with verbs 0x1b25aa0. ListenAddr: 0x1b25260
[rdma] rdma.c: 583:nvmf_rdma_connect: Calculating Queue Depth
[rdma] rdma.c: 588:nvmf_rdma_connect: Target Max Queue Depth: 128
[rdma] rdma.c: 593:nvmf_rdma_connect: Local NIC Max Send/Recv Queue Depth: 32768 Max Read/Write Queue Depth: 16
[rdma] rdma.c: 600:nvmf_rdma_connect: Host (Initiator) NIC Max Incoming RDMA R/W operations: 16 Max Outgoing RDMA R/W operations: 0
[rdma] rdma.c: 609:nvmf_rdma_connect: Host Receive Queue Size: 32
[rdma] rdma.c: 610:nvmf_rdma_connect: Host Send Queue Size: 31
[rdma] rdma.c: 616:nvmf_rdma_connect: Final Negotiated Queue Depth: 32 R/W Depth: 16
[rdma] rdma.c: 320:spdk_nvmf_rdma_conn_create: New RDMA Connection: 0x1b594f0
[rdma] rdma.c: 353:spdk_nvmf_rdma_conn_create: Command Array: 0x7f33737c7000 Length: 800 LKey: 452a6
[rdma] rdma.c: 355:spdk_nvmf_rdma_conn_create: Completion Array: 0x7f33737c6000 Length: 200 LKey: 460b3
[rdma] rdma.c: 357:spdk_nvmf_rdma_conn_create: In Capsule Data Array: 0x7f33737a5000 Length: 20000 LKey: 27605
[rdma] rdma.c: 641:nvmf_rdma_connect: Sent back the accept
[rdma] rdma.c:1062:spdk_nvmf_rdma_acceptor_poll: Acceptor Event: RDMA_CM_EVENT_REJECTED
rdma.c:1085:spdk_nvmf_rdma_acceptor_poll: ***ERROR*** Unexpected Acceptor Event [8]
rdma.c:1473:spdk_nvmf_rdma_poll: ***ERROR*** CQ error on Connection 0x1b594f0, Request 0x28835024 (5): Work Request Flushed Error

**Comment by alekseymmm** [comment]
I also tried not just " nvme discover"  cmd but nvme connect-all and got this error message in /log/messages
[ 2462.259350] nvme nvme0: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 10.30.0.4:4420
[ 2462.283129] nvme nvme0: creating 31 I/O queues.
[ 2463.641342] nvme nvme0: Connect command failed, error wo/DNR bit: -16402
[ 2463.641346] nvme nvme0: failed to connect i/o queue: -18
[ 2464.401179] nvme nvme0: creating 31 I/O queues.
[ 2465.760081] nvme nvme0: Connect command failed, error wo/DNR bit: -16402
[ 2465.760084] nvme nvme0: failed to connect i/o queue: -18

Doest it make any sense ?

**Comment by benlwalker** [comment]
I think we'll need to start to narrow down where the problem is. The first thing I'd try is to use the Linux kernel target instead of SPDK. If you still hit the error, then it isn't SPDK at all. If you don't hit an error, then we know it is the SPDK target and not the kernel initiator.

**Comment by alekseymmm** [comment]
Yes I have the same issue with linux nvmf target (nvmetcli) and linux initiator.
"Failed to write to /dev/nvme-fabrics: Connection reset by peer" on some nodes.
Hence problem is not in spdk. But What could be wrong in this configuration?  May be the fact that each node has 2 NVME drives and each nvme consists of 6 namespaces ? May be it is too much?
Appreciate any ideas...

**Comment by alekseymmm** [comment]
After digging in kernel dynamic debug I found out that on the host side I got this 
nvme_rdma:1330: nvme nvme2: address resolved (0): status 0 id ffff882036833000
nvme_rdma:1330: nvme nvme2: route resolved  (2): status 0 id ffff882036833000
nvme_rdma:1330: nvme nvme2: rejected (8): status 28 id ffff882036833000
nvme nvme2: Connect rejected, status 0.
nvme nvme2: rdma_resolve_addr wait failed (-104).

so the problem comes from nvme-rdma module. Also I found that status 28 is IB_CM_REJ_CONSUMER_DEFINED. Unfortunately I have no idea what it means and what I can do to get rid of it.

**Comment by alekseymmm** [comment]
I found out the problem and could solve it. It was not in spdk  but in hvme-rdma host driver. Anyway, Thanks for support. Close bug as irrelevant

**Comment by ksubbiahx** [comment]
Hi alekseymmm,
I am also getting the error 'Failed to write to /dev/nvme-fabrics: Connection reset by peer' when I do nvme discover or nvme connect. What could be the issue and how to solve it?

**Comment by skaushal14** [comment]
Hi alekseymmm,
I am also facing same issue while running discover or connect: 
"Failed to write to /dev/nvme-fabrics: Connection reset by peer"
Please let me know how to resolve it.

**Comment by alekseymmm** [comment]
Hello @skaushal14 First make sure that the necessary drivers are loaded 
modprobe nvme_rdma  (on the host side)
modprobe nvmet_rdma (on the target side)

Regarding this problem, it has been almost a year ago so I am not 100% sure, but I believe that the steps that helped me was something  like this:
1.  Install latest Mellanox OFED drivers for your system
http://www.mellanox.com/page/products_dyn?product_family=26 (currently I use drivers version 4.3 for rhel7.5)
2. Install this drivers with support for my kernel since I use 4.x linux kernels 
./mlnxofedinstall --add-kernel-support --with-nvmf --skip-repo --force
3. Configure ipoib  and run 
/etc/init.d/openibd restart
4. Rebuild initramfs img so that your system start using mellanox nvme.ko , nvme_rdma.ko, nvme_fabric and other drivers.  
dracut -f  (on Centos like systems, not so sure about ubuntu)
5. reboot

After reboot  run 
modinfo nvme_rdma
to see that the filename field is something like this 
/lib/modules/4.11.6-1.el7.elrepo.x86_64/extra/mlnx-nvme/host/nvme-rdma.ko

You could notice that system use nvme_rdma .ko (and nvme_fabrics and others) from extra/mlnx-nvme not the standard kernel modules ( modinfo without ofed installed shows : filename:       /lib/modules/4.9.0-4-amd64/kernel/drivers/nvme/host/nvme-rdma.ko)

After these steps nvme discover and connect worked fine for me.
