### ISSUE TITLE
errors observed in case 48 SPDK perf processes access 1 single nvme target

### ISSUE THREAD

**Issue by sunmingbao** [spdk/spdk#1470]
## Current Behavior
errors observed in case 48 SPDK perf processes access 1 single nvme target.

## Steps to Reproduce

1. Deploy MOFED 4.7 or 4.9 on host-A.
2. setup a NVMe_OF target with 3 name-spaces on host-A.
3. Reserve 30720MB huge_page (use 2MB pages) memory for the test on host-A.
4. create a shell script launch_perf.sh on host-A with the following content:
[Note] traddr and trsvcid need to be replaced according to the actual setup.

`#!/bin/bash

cpu_mask=0

sync
echo 1 >/proc/sys/vm/drop_caches

for((i=1;i<=$1;i++)); do
cpu_mask=$((1<<${i}))
cpu_mask=$(echo "obase=16;${cpu_mask}"|bc)
cpu_mask="0x${cpu_mask}"
./perf -q 16 -P 3 -s 1024 -w randrw -t 100 -c $cpu_mask -o 11534336 -M 50 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.219.1 trsvcid:4424' &
done
`

5. execute the launch_perf.sh with the following command:

./launch_perf.sh 48 >/dev/null

Logs of one reproduction:
provo-rust:/home/admin/NVMe_OF_test # ./launch_perf.sh 48 >/dev/null
EAL: No available hugepages reported in hugepages-1048576kB
provo-rust:/home/admin/NVMe_OF_test # EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_ctrlr.c: 434:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: nvme_transport_ctrlr_connect_io_qpair() failed
EAL: No available hugepages reported in hugepages-1048576kB
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_rdma.c:1817:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
nvme_ctrlr.c: 797:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
nvme_qpair.c: 118:nvme_admin_qpair_print_command: *NOTICE*: ADMIN COMMAND (7f) sqid:0 cid:0 nsid:4 cdw10:00000000 cdw11:00000014
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 686:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '192.168.219.1'
./perf: errors occured
EAL: No available hugepages reported in hugepages-1048576kB
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_rdma.c: 438:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_CONNECT_ERROR (6) from CM event channel (status = -1)
nvme_rdma.c:1817:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
nvme_ctrlr.c: 797:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
nvme_qpair.c: 118:nvme_admin_qpair_print_command: *NOTICE*: ADMIN COMMAND (7f) sqid:0 cid:0 nsid:4 cdw10:00000000 cdw11:00000014
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 686:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '192.168.219.1'
./perf: errors occured
EAL: No available hugepages reported in hugepages-1048576kB
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_rdma.c:1817:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
nvme_ctrlr.c: 797:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
nvme_qpair.c: 118:nvme_admin_qpair_print_command: *NOTICE*: ADMIN COMMAND (7f) sqid:0 cid:0 nsid:4 cdw10:00000000 cdw11:00000014
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 686:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '192.168.219.1'
./perf: errors occured
EAL: No available hugepages reported in hugepages-1048576kB
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_rdma.c: 933:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c:1163:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
nvme_rdma.c:1817:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
nvme_ctrlr.c: 797:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
nvme_qpair.c: 118:nvme_admin_qpair_print_command: *NOTICE*: ADMIN COMMAND (7f) sqid:0 cid:0 nsid:4 cdw10:00000000 cdw11:00000014
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 686:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '192.168.219.1'
./perf: errors occured
nvme_rdma.c:1817:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
nvme_ctrlr.c: 797:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
nvme_qpair.c: 118:nvme_admin_qpair_print_command: *NOTICE*: ADMIN COMMAND (7f) sqid:0 cid:0 nsid:4 cdw10:00000000 cdw11:00000014
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 686:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '192.168.219.1'
./perf: errors occured

## Context (Environment including OS version, SPDK version, etc.)

provo-rust:~ # cat /etc/os-release 
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"
provo-rust:~ # 
provo-rust:~ # uname -a 
Linux provo-rust.west.isilon.com 4.12.14-95.48-default #1 SMP Thu Feb 27 07:40:02 UTC 2020 (ddfe57a) x86_64 x86_64 x86_64 GNU/Linux
provo-rust:~ # 
provo-rust:~ # ibv_devinfo 
hca_id:	mlx5_bond_0
	transport:			InfiniBand (0)
	fw_ver:				14.26.6000
	node_guid:			9803:9b03:0077:e622
	sys_image_guid:			9803:9b03:0077:e622
	vendor_id:			0x02c9
	vendor_part_id:			4117
	hw_ver:				0x0
	board_id:			DEL2810000034
	phys_port_cnt:			1
	Device ports:
		port:	1
			state:			PORT_ACTIVE (4)
			max_mtu:		4096 (5)
			active_mtu:		4096 (5)
			sm_lid:			0
			port_lid:		0
			port_lmc:		0x00
			link_layer:		Ethernet

provo-rust:~ #

**Comment by glodfish-zg** [comment]
Hi @sunmingbao. Does this issue occur when the number of cases is smaller? For example, the number is 24.

**Comment by yidong0635** [comment]
hi, please try "trsvcid:4420".

**Comment by tomzawadzki** [comment]
@sunmingbao Have you had a chance to try steps from @yidong0635 ?

**Comment by tomzawadzki** [comment]
No update for 3 months. @sunmingbao Please feel free to re-open this issue if you get a chance to try steps from @yidong0635 on latest SPDK.
