### ISSUE TITLE
Error while loading liburing.

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1471]
Log: 
```
00:01:46.512  ************************************
00:01:46.512  START TEST rpc
00:01:46.512  ************************************
00:01:46.513   11:44:06	# xtrace_enable
00:01:46.513   11:44:06	# test/rpc/rpc.sh
00:01:46.572  * Looking for test storage...
00:01:46.578  * Found test storage at /var/jenkins/workspace/iscsi-uring-autotest/spdk/test/rpc
00:01:46.578    11:44:06	# xtrace_enable
00:01:46.579   11:44:06	# spdk_pid=26778
00:01:46.579   11:44:06	# trap 'killprocess $spdk_pid; exit 1' SIGINT SIGTERM EXIT
00:01:46.579   11:44:06	# waitforlisten 26778
00:01:46.579   11:44:06	# /var/jenkins/workspace/iscsi-uring-autotest/spdk/build/bin/spdk_tgt
00:01:46.580   11:44:06	# '[' -z 26778 ']'
00:01:46.580   11:44:06	# local rpc_addr=/var/tmp/spdk.sock
00:01:46.580   11:44:06	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:01:46.580  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:01:46.580   11:44:06	# xtrace_disable
00:01:46.580   11:44:06	# '[' '' '!=' yes ']'
00:01:46.580   11:44:06	# PREV_BASH_OPTS=ehxBET
00:01:46.580   11:44:06	# [[ ehxBET == *\x* ]]
00:01:46.580   11:44:06	# XTRACE_DISABLED=yes
00:01:46.580   11:44:06	# set +x
00:01:46.590  /var/jenkins/workspace/iscsi-uring-autotest/spdk/build/bin/spdk_tgt: error while loading shared libraries: liburing.so.1: cannot open shared object file: No such file or directory
00:01:47.328  /var/jenkins/workspace/iscsi-uring-autotest/spdk/test/common/autotest_common.sh: line 635: kill: (26778) - No such process
00:01:47.328  ERROR: process (pid: 26778) is no longer running
00:01:47.329   11:44:07	# xtrace_enable
00:01:47.329   11:44:07	# (( i == 0 ))
00:01:47.329   11:44:07	# return 1
00:01:47.329    11:44:07	# trap - ERR
00:01:47.329    11:44:07	# print_backtrace
00:01:47.330    11:44:07	# [[ ehxBET =~ e ]]
00:01:47.330    11:44:07	# args=("${BASH_ARGV[@]}")
00:01:47.330    11:44:07	# local args
00:01:47.330    11:44:07	# xtrace_disable
00:01:47.330    11:44:07	# '[' no '!=' yes ']'
00:01:47.330    11:44:07	# PREV_BASH_OPTS=ehxBET
00:01:47.331    11:44:07	# [[ ehxBET == *\x* ]]
00:01:47.331    11:44:07	# XTRACE_DISABLED=yes
00:01:47.331    11:44:07	# set +x
00:01:47.331  ========== Backtrace start: ==========
00:01:47.331  
00:01:47.339  in test/rpc/rpc.sh:43 -> main([])
```

Link to full log: [https://ci.spdk.io/results/autotest-per-patch/builds/20317/archive/iscsi-uring-autotest/build.log](url)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_20317.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20328.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20451.html

**Comment by optimistyzy** [comment]
This patch may be helpful: https://review.spdk.io/gerrit/c/spdk/spdk/+/3231

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20605.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20646.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_20650.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20870.html

**Comment by optimistyzy** [comment]
Another patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/3261

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_20924.html

**Comment by optimistyzy** [comment]
@Seth5141  What's your option on this shared library issue?  Thanks.

**Comment by karlatec** [comment]
>  iscsi uring vg 

I think you're confusing some of the CI jobs. We don't have iSCSI uring tests running in Vagrant VM's at the moment, only on physical systems.

> could you check whether "/usr/lib" is in the default ld load path

Looks like it:
```
[sys_sgci@GrizzlyPass1 ~]$ uname -a
Linux GrizzlyPass1 5.5.10-100.fc30.x86_64 #1 SMP Wed Mar 18 14:34:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[sys_sgci@GrizzlyPass1 ~]$ ll /usr/lib/liburing.*
-rw-r--r-- 1 root root 84904 Jun  2 16:53 /usr/lib/liburing.a
lrwxrwxrwx 1 root root    17 Jun  2 16:53 /usr/lib/liburing.so -> liburing.so.1.0.6
lrwxrwxrwx 1 root root    17 Jun  2 16:53 /usr/lib/liburing.so.1 -> liburing.so.1.0.6
-rwxr-xr-x 1 root root 56256 Jun  2 16:53 /usr/lib/liburing.so.1.0.6
[sys_sgci@GrizzlyPass1 ~]$ ldconfig -v 2>/dev/null | grep -v ^$'\t'
/usr/lib64//bind9-export:
/usr/lib64/iscsi:
/usr/lib64/qt-3.3/lib:
/lib:
/lib64:
/lib/sse2: (hwcap: 0x0000000000000001)
/lib64/sse2: (hwcap: 0x0000000000000001)
/lib64/tls: (hwcap: 0x8000000000000000)
[sys_sgci@GrizzlyPass1 ~]$ ll /lib
lrwxrwxrwx 1 root root 7 Feb 11  2019 /lib -> usr/lib

[vagrant@fedora31 ~]$ uname -a
Linux fedora31.localdomain 5.6.11-200.fc31.x86_64 #1 SMP Wed May 6 19:10:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@fedora31 ~]$ ll /usr/lib/liburing.*
-rw-r--r--. 1 root root 84936 May 27 08:29 /usr/lib/liburing.a
lrwxrwxrwx. 1 root root    17 May 27 08:29 /usr/lib/liburing.so -> liburing.so.1.0.6
lrwxrwxrwx. 1 root root    17 May 27 08:29 /usr/lib/liburing.so.1 -> liburing.so.1.0.6
-rwxr-xr-x. 1 root root 56264 May 27 08:29 /usr/lib/liburing.so.1.0.6
[vagrant@fedora31 ~]$ ldconfig -v 2>/dev/null | grep -v ^$'\t'
/usr/lib64/iscsi:
/lib:
/lib64:
[vagrant@fedora31 ~]$ ll /lib
lrwxrwxrwx. 1 root root 7 Jul 25  2019 /lib -> usr/lib
```

**Comment by optimistyzy** [comment]
Hi  Karol, Thanks for your info, the iscsi uring job is running on physical machine with Fedora 30. So I am curious if uring is existing in the library path, while the SPDK iSCSI target can not load this some times.

By the way, My local os is also fedora 30. And if I did not update ldconfig, I cannot directly load liburing.so..

**Comment by optimistyzy** [comment]
@karlatec  Could you install liburing library into /lib64 (i.e., /usr/lib64). I checked my machine, if I directly install this library, it works.

**Comment by optimistyzy** [comment]
> This patch may be helpful: https://review.spdk.io/gerrit/c/spdk/spdk/+/3231

This patch does not help on this case, I guess pkg related patch will not execute in physical machines.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_21000.html

**Comment by karlatec** [comment]
Updated VMs and physical systems according to this patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/3261
Let's see if that helps

**Comment by optimistyzy** [comment]
Close this issue since the patch was merged  (https://review.spdk.io/gerrit/c/spdk/spdk/+/3261). If same issue happens again, we can reopen it.
