### ISSUE TITLE
[autobuild_check_format] naming conv error but function already within the map file

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1472]
Issue occurs on patch below
https://review.spdk.io/gerrit/c/spdk/spdk/+/3176
Seems that checker is complaining about function which is already added to nvme.map file.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/20335/archive/unittest-vg-autotest/build.log

## Execution failed at

00:02:48.539  Checking for proper function naming conventions... found naming convention errors.
00:02:48.591  function spdk_nvme_qpair_print_command starts with spdk_ which is reserved for public API functions.
00:02:48.591  Please add this function to its corresponding map file and a public header or remove the spdk_ prefix.

**Comment by Seth5141** [comment]
That's an issue with the naming convention script. Fix here. https://review.spdk.io/gerrit/c/spdk/spdk/+/3229

**Comment by tomzawadzki** [comment]
Fix from @Seth5141 has been merged https://review.spdk.io/gerrit/c/spdk/spdk/+/3229. Thanks !
