### ISSUE TITLE
[nvmf-tcp-uring-vg-autotest]Failure of running nvme perf again nvmf tcp target

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1473]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/20387/archive/nvmf-tcp-uring-vg-autotest/build.log

## Execution failed at

00:05:41.474   17:15:43	# /home/vagrant/spdk_repo/spdk/build/examples/perf -q 128 -o 262144 -w randrw -M 50 -t 2 -r 'trtype:tcp adrfam:IPv4 traddr:127.0.0.1 trsvcid:4420'
00:05:41.491  Starting SPDK v20.07-pre git sha1 2f1c0ee2e / DPDK 19.11.2 initialization...
00:05:41.491  [ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid39831 ]
00:05:41.496  EAL: No available hugepages reported in hugepages-1048576kB
00:05:42.127  [2020-07-03 17:15:44.537867] tcp.c:1666:nvmf_tcp_pdu_ch_handle: *ERROR*: PDU type=0x02, Expected ICReq header length 24, got 2 on tqpair=0x15590f0
00:05:42.129  [2020-07-03 17:15:44.539110] nvme_tcp.c: 774:nvme_tcp_pdu_ch_handle: *ERROR*: Unexpected PDU type 0x00
00:05:42.129  [2020-07-03 17:15:44.539263] nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
00:05:42.129  [2020-07-03 17:15:44.539260] tcp.c:1014:nvmf_tcp_qpair_set_recv_state: *ERROR*: The recv state of tqpair=0x15590f0 is same with the state(5) to be set
00:05:42.129  [2020-07-03 17:15:44.539282] nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
00:05:42.129  [2020-07-03 17:15:44.539293] nvme_qpair.c: 132:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:0 nsid:1 lba:130304 len:256
00:05:42.129  [2020-07-03 17:15:44.539304] nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
00:05:42.129  [2020-07-03 17:15:44.539313] nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
00:05:42.129  [2020-07-03 17:15:44.539320] nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
00:05:42.129  [2020-07-03 17:15:44.539328] nvme_qpair.c: 132:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:0 nsid:1 lba:121856 len:256
00:05:42.129  [2020-07-03 17:15:44.539337] nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
00:05:42.129  [2020-07-03 17:15:44.539345] nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
00:05:42.129  [2020-07-03 17:15:44.539352] nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
00:05:42.129  [2020-07-03 17:15:44.539360] nvme_qpair.c: 132:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:0 nsid:1 lba:122112 len:256
00:05:42.129  [2020-07-03 17:15:44.539368] nvme_qpair.c: 303:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:1 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
00:05:42.129  Read completed with error (sct=0, sc=7)
00:05:42.129  perf: nvme_internal.h:1054: nvme_free_request: Assertion `req->num_children == 0' failed.

**Comment by optimistyzy** [comment]
This issue does not happen in physical machine, but we need to track and solve this.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20404.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20406.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20412.html

**Comment by optimistyzy** [comment]
This patch may be the proper fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/3215

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20425.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20427.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_20446.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_20556.html
