### ISSUE TITLE
memory leaks when execute fuzz test

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#1482]
## Expected Behavior

No memory leaks while executing test: test/fuzz/autofuzz.sh --module=vhost --transport=all

## Current Behavior

Test failed with output about memory leaks.
Please found outputs in attachements:
[vhost_autofuzz_output1.txt](https://github.com/spdk/spdk/files/4890169/vhost_autofuzz_output1.txt)
[vhost_fuzz_tgt_output.txt](https://github.com/spdk/spdk/files/4890170/vhost_fuzz_tgt_output.txt)

## Possible Solution

Unknown

## Steps to Reproduce

1. Run test/fuzz/autofuzz.sh --module=vhost --transport=all
2. check vhost_autofuzz_output1.txt

## Context (Environment including OS version, SPDK version, etc.)
Both fedora31 and ubuntu 18.04
SPDK v20.07-pre git sha1 b1074c490
DPDK 19.11.2

**Comment by changpe1** [comment]
[Bug Scrub] @Donaim could you take a look ? thanks.

**Comment by Donaim** [comment]
Sure @changpe1 I will take a look this week

**Comment by darsto** [comment]
I see in the first log:

```
[2020-07-08 09:52:48.356258] vhost_user.c: 207:get_hugepage_file_info: *ERROR*: Exceed maximum of 8
[2020-07-08 09:52:48.366620] vhost_user.c: 239:prepare_vhost_memory_user: *ERROR*: Failed to prepare memory for vhost-user
Initial mem_map notify failed
```

This message could be a bit more clear, but it indicates you're trying to share more than 8 memory mappnigs over vhost-user, which is not possible (vhost protocol limitation). This can be fixed by either switching to 1GB hugepages or starting the vhost initiator with '--single-file-segments'. autofuzz.sh should probably have that flag.

**Comment by tomzawadzki** [comment]
Marking it as a [bug], since the test (or VM hosting the test) needs to be changed.

**Comment by xjjx** [comment]
I've tried to set HUGEMEM=1024 and added "-g" parameter to vhost. Unfortunately this didn't help much.
In logs there is information that at least "-g"  (single file segments) was used:

> [ DPDK EAL parameters: vhost --no-shconf -c 0x1 --single-file-segments --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid149635 ]

[vhost_autofuzz_output1.txt](https://github.com/spdk/spdk/files/4958397/vhost_autofuzz_output1.txt)
[vhost_fuzz_tgt_output.txt](https://github.com/spdk/spdk/files/4958398/vhost_fuzz_tgt_output.txt)

**Comment by changpe1** [comment]
> I've tried to set HUGEMEM=1024 and added "-g" parameter to vhost. Unfortunately this didn't help much.
> In logs there is information that at least "-g" (single file segments) was used:
> 
> > [ DPDK EAL parameters: vhost --no-shconf -c 0x1 --single-file-segments --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid149635 ]
> 
> [vhost_autofuzz_output1.txt](https://github.com/spdk/spdk/files/4958397/vhost_autofuzz_output1.txt)
> [vhost_fuzz_tgt_output.txt](https://github.com/spdk/spdk/files/4958398/vhost_fuzz_tgt_output.txt)

Put "-g" parameter in fuzz client can work for this issue, vhost target doesn't need -"g" parameter.
