### ISSUE TITLE
support ABI stability for spdk_app_opts

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1484]
This public struct defined should allow to provide ABI stability.

## Possible Solution

Follow the pattern for other public struct defined e.g. spdk_nvme_ctrlr_opts.

## Context (Environment including OS version, SPDK version, etc.)

spdk master (0bec3c3c647a492507f27696a647ff1aba2b3a1d)

**Comment by changpe1** [comment]
[Bug Scrub] it's not target for 20.07 release.

**Comment by optimistyzy** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/5330
