### ISSUE TITLE
support ABI stability for spdk_nvmf_transport_opts

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1485]
This public struct defined should allow to provide ABI stability.

## Possible Solution

Follow the pattern for other public struct defined e.g. spdk_nvme_ctrlr_opts.

## Context (Environment including OS version, SPDK version, etc.)

spdk master (0bec3c3c647a492507f27696a647ff1aba2b3a1d)

**Comment by changpe1** [comment]
[Bug Scrub]@mkenguva Jim will talk to you about the changes needed. Thanks.

**Comment by optimistyzy** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/5293

**Comment by optimistyzy** [comment]
Patch was merged, so close this issue.
