### ISSUE TITLE
Compile SPDK but not seeing "fio_plugin" binary generated in ./examples/nvme/fio_plugin/

### ISSUE THREAD

**Issue by dkuo1** [spdk/spdk#1489]
## Steps to Reproduce

1. git clone http://github.com/spdk/spdk
2. git submodule update --init
3. ./scripts/pkgdep.sh --all
4. ./configure  --with-fio=/root/fio/ --with-pmdk=/root/pmdk/ --with-rdma --with-vhost --with-virtio --with-rbd
5. make
6. check if binary show up in ./examples/nvme/fio_plugin/

**Comment by Comphix** [comment]
For latest code, the binaries are under <spdk folder>/build/fio/

**Comment by Comphix** [comment]
Here is the related commit: https://github.com/spdk/spdk/commit/c3b5ae0c60463f3d41fcd28c9371de80f52dbfa9

**Comment by optimistyzy** [comment]
I also posted in our mailing list about the binary change: https://lists.01.org/hyperkitty/list/spdk@lists.01.org/thread/Y4QUPNKJ7BA435W23NIMQIUV42AKTYOR/
