### ISSUE TITLE
[ocf_fio_modes] dd: error writing '/dev/nvme0n1': Operation not supported

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1494]

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_21227.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_21235.html

**Comment by mikeBashStuff** [comment]
This looks like a duplicate of #1456.

**Comment by tomzawadzki** [comment]
Duplicate of #1456

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_24661.html
