### ISSUE TITLE
[artifacts] Missing artifacts from builds

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1495]
Some of the builds are missing `build.log` file, while having at least some of the other artifact files.
Does not seem to be reproducible always (checked latest merged patch), but did occur on at least two builds below.
The file is missing on runs from failed and passed tests.

## Link to the failed CI build

[Build 21183](https://ci.spdk.io/public_build/autotest-per-patch_21183.html)
- [nvme-phy-autotest #18210](https://ci.spdk.io/results/autotest-per-patch/builds/21183/archive/nvme-phy-autotest/index.html)
- [BlobFS-autotest #18135](https://ci.spdk.io/results/autotest-per-patch/builds/21183/archive/BlobFS-autotest/index.html)
- [crypto-autotest #18112](https://ci.spdk.io/results/autotest-per-patch/builds/21183/archive/crypto-autotest/index.html)
- [nvme-phy-autotest #18210](https://ci.spdk.io/results/autotest-per-patch/builds/21183/archive/nvme-phy-autotest/index.html)
- others...

[Build 21223](https://ci.spdk.io/public_build/autotest-per-patch_21223.html)
- [iscsi-autotest #18144](https://ci.spdk.io/results/autotest-per-patch/builds/21223/archive/iscsi-autotest/index.html)
- [crypto-autotest #18145](https://ci.spdk.io/results/autotest-per-patch/builds/21223/archive/crypto-autotest/index.html)
- others...

## Execution failed at
Lack of `build.log`.

**Comment by tomzawadzki** [comment]
[Bug scrub] The build.log artifacts are present on Jenkins side for the two listed builds. @Seth5141 suggests adding better logging for artifact copying to AWS.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_21183.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_23393.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_24787.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_26172.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_28079.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_28419.html

**Comment by tomzawadzki** [comment]
On patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4632/2 in unittest job https://ci.spdk.io/results/autotest-per-patch/builds/27992/archive/unittest-vg-autotest/index.html following files are missing:
```
test_completions.txt
build_output.txt
result.txt
cov_base.info
udev.log
timing.txt
timing.svg
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_29010.html

**Comment by tomzawadzki** [comment]
[Bug scrub] @karlatec Let's add verification mechanism after moving artifacts to AWS to make sure all are present.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_29624.html

**Comment by tomzawadzki** [comment]
No recent reports of this issue for a month. Just checked 6 builds from ci.spdk.io, none had missing `build.log`. Closing.

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5514/
Log https://ci.spdk.io/results/autotest-per-patch/builds/31804/archive/nvme-phy-autotest/index.html
Files:
```
dmesg.log
all_tests.txt
udev.log
timing.txt
cov_base.info
test_completions.txt
result.txt
```
Missing build.log.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_33981.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_34456.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36264.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @floatious. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_37000.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_42588.html

**Comment by tomzawadzki** [comment]
[Bug scrub] Closing as it has not been reported for a month.
