### ISSUE TITLE
[nvme_cli_build] .git/index: index file smaller than expected

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1496]
nvme_cli_build part of tests fails with:

# git clean -dfx
fatal: .git/index: index file smaller than expected

in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:851 -> nvme_cli_build([])

Log:
https://10.102.17.111:8080/job/nvme-phy-autotest/18407/console

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_21431.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_21429.html

**Comment by Maciej-Szwed** [comment]
Seen only on GrizzlyPass14 server

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_21428.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_21439.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_21433.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_21441.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_21442.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_21506.html

**Comment by Seth5141** [comment]
Also saw this on GP12

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_21507.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_21515.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_21522.html

**Comment by karlatec** [comment]
Proposed fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/3415

However this only mitigates the issue. It does not address the root cause why .git/index get corrupted (currently I have no idea why:P, still looking for answers)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_21523.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_21508.html
