### ISSUE TITLE
[spdkcli_rbd]  rmdir: failed to remove '/var/run/dpdk/spdk0': Directory not empty

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1501]

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_21703.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_21769.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_21774.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_21772.html

**Comment by mikeBashStuff** [comment]
Please, disregard the above failures from me, I mistaken the issue id with #1502. :)

**Comment by changpe1** [comment]
00:10:34.202   19:42:12	# /home/vagrant/spdk_repo/spdk/scripts/setup.sh cleanup
00:10:35.054  Cleaning
00:10:35.059  Still open: /run/dpdk/spdk0/config
00:10:35.063  Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-0
00:10:35.066  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-0_41498
00:10:35.072  Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-1
00:10:35.075  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-1_41498
00:10:35.079  Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-2
00:10:35.082  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-2_41498
00:10:35.086  Still open: /run/dpdk/spdk0/fbarray_memseg-2048k-0-3
00:10:35.089  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-3_41498
00:10:35.093  Still open: /run/dpdk/spdk0/fbarray_memzone
00:10:35.095  Removing:    /run/dpdk/spdk0/hugepage_info
00:10:35.099  Removing:    /run/dpdk/spdk0/mp_socket
00:10:35.102  Removing:    /run/dpdk/spdk0/mp_socket_41498_12b49aa5666
00:10:35.106  Removing:    /run/dpdk/spdk1/config
00:10:35.109  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-0
00:10:35.113  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-1
00:10:35.116  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-2
00:10:35.119  Removing:    /run/dpdk/spdk1/fbarray_memseg-2048k-0-3
00:10:35.122  Removing:    /run/dpdk/spdk1/fbarray_memzone
00:10:35.125  Removing:    /run/dpdk/spdk1/hugepage_info
00:10:35.129  Removing:    /run/dpdk/spdk1/mp_socket
00:10:35.132  Removing:    /dev/shm/iscsi_trace.0
00:10:35.135  Removing:    /dev/shm/iscsi_trace.pid39071
00:10:35.140  Still open: /dev/shm/spdk_iscsi_conns.0
00:10:35.144  Removing:    /var/run/dpdk/spdk0
00:10:35.144  rmdir: failed to remove '/var/run/dpdk/spdk0': Directory not empty

**Comment by optimistyzy** [comment]
Do not see this issue for one month. Keep open this issue for another 1 week and if there is no similar issue, we can close this issue.

**Comment by tomzawadzki** [comment]
[Bug] Months of no instances is enough, closing.
