### ISSUE TITLE
some servers run perf  failed

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1505]
# Issue
```
/spdk/build/examples/perf -i 0 -q 32 -o 4096 -w randrw -M 50 -t 1 -r 'trtype:PCIe traddr:0000:60:00.0'
Starting SPDK v20.07-pre git sha1 e63eb0375 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
Initializing NVMe Controllers
EAL: Failed to hotplug add device on primary
Attached to NVMe Controller at 0000:60:00.0 [8086:0953]
Associating PCIE (0000:60:00.0) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                           Latency(us)
Device Information                     :       IOPS      MiB/s    Average        min        max
PCIE (0000:60:00.0) NSID 1 from core  0:  305306.00    1192.60     104.81       5.05   16334.67
========================================================
Total                                  :  305306.00    1192.60     104.81       5.05   16334.67

EAL: Driver cannot detach the device (0000:60:00.0)
EAL: Failed to hotplug remove device on primary
EAL: Failed to hotplug remove device
 06:25:56       # /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r 'trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420'
Starting SPDK v20.07-pre git sha1 e63eb0375 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid480425 ]
Initializing NVMe Controllers
[2020-07-22 06:25:58.335828] nvme_rdma.c:1103:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-07-22 06:25:58.335874] nvme_rdma.c:1334:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
^CTraceback (most recent call last):
  File "/home/spdk/scripts/rpc.py", line 2461, in <module>
    for input in sys.stdin:
KeyboardInterrupt
```

This can't killed by` ctrl+c`  or `kill -9  479404 `:
```
ps -ef |grep perf
root      479404       1  0 04:41 ?        00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      480036       1  0 04:55 ?        00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      480425       1  0 06:25 pts/3    00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      480446  479458  0 06:41 pts/0    00:00:00 grep --color=auto perf
```
:
and process can't be killed

ethtool -i enp216s0:
```
driver: mlx4_en
version: 4.0-0
firmware-version: 2.35.5100
expansion-rom-version:
bus-info: 0000:d8:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
```
ethtool enp216s0:
`Link detected: no`
## Steps to Reproduce
```
./configure --with-rdma 
make -j10
./test/nvmf/host/perf.sh  --transport=rdma

```
## Context (Environment including OS version, SPDK version, etc.)
OS: 5.0.16-100.fc28.x86_64
commit: e63eb0375d9c02aa18ffaf3287ce44714df565f3

**Comment by changpe1** [comment]
@yidong0635 could you also post the target log here? thanks.

**Comment by yidong0635** [comment]
@changpe1  I just run this :`./test/nvmf/host/perf.sh --transport=rdma` directly.
I'm clear that RDMA cable had been removed from the server, but it should not can't be killed.

**Comment by Comphix** [comment]
Seems that the below operation fails

ret = nvme_rdma_process_event(rqpair, rctrlr->cm_channel, RDMA_CM_EVENT_ESTABLISHED);

@yidong0635 , do you mean there is no RDMA cable linked between two servers? This issue is from the host side when setting the transport to rdma?

**Comment by yidong0635** [comment]
@Comphix  yes, I checked the server or using this command to check.
ethtool enp216s0:
Link detected: no

**Comment by Comphix** [comment]
# ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.044 ms
^C
--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.044/0.044/0.044/0.000 ms

# ./perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420'
Starting SPDK v20.07-pre git sha1 03382cf79 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid34306 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
[2020-07-23 13:13:41.560101] nvme_rdma.c: 546:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_ESTABLISHED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = 8)
[2020-07-23 13:13:41.560157] nvme_rdma.c:1103:nvme_rdma_connect: *ERROR*: RDMA connect error -74
[2020-07-23 13:13:41.560166] nvme_rdma.c:1334:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
[2020-07-23 13:13:42.572894] nvme_rdma.c:2003:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
[2020-07-23 13:13:42.572944] nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
[2020-07-23 13:13:42.572952] nvme_ctrlr.c: 817:nvme_ctrlr_shutdown: *ERROR*: ctrlr 192.168.1.1 get_cc() failed
[2020-07-23 13:13:42.572961] nvme_qpair.c: 553:_nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2020-07-23 13:13:42.573008] nvme_qpair.c: 535:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
[2020-07-23 13:13:42.573029] nvme_qpair.c: 245:nvme_admin_qpair_print_command: *NOTICE*: FABRIC PROPERTY GET qid:0 cid:0 PRP1 0x0 PRP2 0x0
[2020-07-23 13:13:42.573044] nvme_qpair.c: 454:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
[2020-07-23 13:13:42.573106] nvme.c: 630:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2020-07-23 13:13:42.573118] nvme.c: 707:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '192.168.1.1'
./perf: errors occured

Not sure whether my reproduction is same. I've tried:

1. Did not start the NVMe-oF target
2. The RDMA NIC is configured with 192.168.1.1
3. Run the Perf with RDMA transport
4. It failed also at the nvme_rdma_connect().
==> Error code is different, here it is 74 and above it is 99

**Comment by Comphix** [comment]
Also added more about my NIC used where the link is On and different than yours @yidong0635 

root@storage35:/home/gangcao/spdk/build/examples# ethtool ens1f0 | grep -i link
        Supported link modes:   1000baseKX/Full
        Advertised link modes:  1000baseKX/Full
                               link
        Link detected: yes
root@storage35:/home/gangcao/spdk/build/examples# ethtool -i ens1f0
driver: mlx5_core
version: 5.0-0
firmware-version: 12.20.1010 (MT_2190110032)
expansion-rom-version:
bus-info: 0000:03:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes

**Comment by Comphix** [comment]
Changed the links status to No and looks like a different error stack report.

This time did not fail at nvme_rdma_connect()

root@storage35:/home/gangcao/storage17/spdk/build/examples# ethtool ens1f0 | grep -i link
        Supported link modes:   1000baseKX/Full
        Advertised link modes:  1000baseKX/Full
                               link
        Link detected: no
root@storage35:/home/gangcao/storage17/spdk/build/examples# ./perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420'
Starting SPDK v20.07-pre git sha1 03382cf79 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid35537 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
[2020-07-23 13:28:50.267562] nvme_rdma.c:1018:nvme_rdma_resolve_addr: *ERROR*: RDMA address resolution error
[2020-07-23 13:28:50.267608] nvme_rdma.c:1322:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: nvme_rdma_resolve_addr() failed
[2020-07-23 13:28:50.267679] nvme_rdma.c:2003:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
[2020-07-23 13:28:50.267692] nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
[2020-07-23 13:28:50.267706] nvme_ctrlr.c: 817:nvme_ctrlr_shutdown: *ERROR*: ctrlr 192.168.1.1 get_cc() failed
[2020-07-23 13:28:50.267719] nvme_qpair.c: 553:_nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2020-07-23 13:28:50.267730] nvme_qpair.c: 535:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
[2020-07-23 13:28:50.267744] nvme_qpair.c: 245:nvme_admin_qpair_print_command: *NOTICE*: FABRIC PROPERTY GET qid:0 cid:0 PRP1 0x0 PRP2 0x0
[2020-07-23 13:28:50.267757] nvme_qpair.c: 454:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
[2020-07-23 13:28:50.267828] nvme.c: 630:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2020-07-23 13:28:50.267840] nvme.c: 707:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '192.168.1.1'

@yidong0635 , please take a look further look. Thanks.

**Comment by yidong0635** [comment]
@Comphix 
I can confirm it holds by "`rdma_destroy_id`", and  Don't we need to clear something  if _nvme_rdma_ctrlr_connect_qpair failed somewhere? 
For example "rqpair->cm_id" .
@AlekseyMarchuk @Seth5141 @benlwalker @changpe1

**Comment by AlekseyMarchuk** [comment]
Hi, rdma_destroy_id waits for completion of all events submitted to kernel driver, that is why it can freeze. I'll try to reproduce it next week.

**Comment by AlekseyMarchuk** [comment]
Hi @yidong0635 
I tried to reproduce this problem, but I didn't notice that perf hung:
```
 13:10:52       # perf_app=/tmp/spdk/build/examples/perf
 13:10:52       # /tmp/spdk/build/examples/perf -i 0 -q 32 -o 4096 -w randrw -M 50 -t 1 -r 'trtype:PCIe traddr:0000:86:00.0'
Starting SPDK v20.07-pre git sha1 29bbb9b / DPDK 20.05.0 initialization...
[ DPDK EAL parameters: perf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: VFIO support initialized
EAL: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
EAL: Failed to hotplug add device on primary
EAL:   using IOMMU type 1 (Type 1)
Attached to NVMe Controller at 0000:86:00.0 [8086:2700]
Associating PCIE (0000:86:00.0) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                           Latency(us)
Device Information                     :       IOPS      MiB/s    Average        min        max
PCIE (0000:86:00.0) NSID 1 from core  0:  243566.00     951.43     131.12      30.47   20101.82
========================================================
Total                                  :  243566.00     951.43     131.12      30.47   20101.82

EAL: Driver cannot detach the device (0000:86:00.0)
EAL: Failed to hotplug remove device on secondary
EAL: Failed to hotplug remove device
 13:10:54       # /tmp/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r 'trtype:rdma adrfam:IPv4 traddr:1.1.10.1 trsvcid:4420'
Starting SPDK v20.07-pre git sha1 29bbb9b / DPDK 20.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid313780 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
[2020-07-29 13:10:54.278194] nvme_rdma.c: 455:nvme_rdma_qpair_process_cm_event: *NOTICE*: ack event RDMA_CM_EVENT_ADDR_RESOLVED
[2020-07-29 13:10:54.279263] nvme_rdma.c: 455:nvme_rdma_qpair_process_cm_event: *NOTICE*: ack event RDMA_CM_EVENT_ROUTE_RESOLVED
[2020-07-29 13:10:55.294344] nvme_rdma.c:1104:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-07-29 13:10:55.294410] nvme_rdma.c:1335:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
[2020-07-29 13:10:56.316713] nvme_rdma.c:2004:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
[2020-07-29 13:10:56.316814] nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
[2020-07-29 13:10:56.316833] nvme_ctrlr.c: 828:nvme_ctrlr_shutdown: *ERROR*: ctrlr 1.1.10.1 get_cc() failed
[2020-07-29 13:10:56.316876] nvme_qpair.c: 553:_nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
[2020-07-29 13:10:56.316892] nvme_qpair.c: 535:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
[2020-07-29 13:10:56.316913] nvme_qpair.c: 245:nvme_admin_qpair_print_command: *NOTICE*: FABRIC PROPERTY GET qid:0 cid:0 PRP1 0x0 PRP2 0x0
[2020-07-29 13:10:56.316932] nvme_qpair.c: 454:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
[2020-07-29 13:10:56.317527] nvme.c: 630:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2020-07-29 13:10:56.317549] nvme.c: 707:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '1.1.10.1'
/tmp/spdk/build/examples/perf: errors occured
```
Link status:
```
sudo ethtool enp94s0f0 | grep -i link
        Supported link modes:   1000baseKX/Full
        Advertised link modes:  1000baseKX/Full
        Link partner advertised link modes:  Not reported
        Link partner advertised pause frame use: No
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
                               link
        Link detected: no
```

I haven't unplugged the cable, I just set link status to down, but I believe the effect will be the same.
Could you clarify your OS and kernel version? This issue might depend on the environment.

**Comment by yidong0635** [comment]
@AlekseyMarchuk  : 5.0.16-100.fc28.x86_64 
I found this issue for at least on two different machines, and another one is perf running is ok but he IOPS is holding on zero.
And I need to retest this on more machines , I can confirm these are ok on last release that we had resolved an issue about 
nvme_rdma receiving before sending.

**Comment by yidong0635** [comment]
I changed another machine:  5.0.9-301.fc30.x86_64, this is really a bug. `commit b0a28e9509369d7a6e77a0400133393bce11512b`
ethtool -i ens785f1:
```
driver: mlx5_core
version: 5.0-0
firmware-version: 12.21.2010 (MT_2190110032)
expansion-rom-version:
bus-info: 0000:18:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
```
ethtool ens785f1 |grep  "Link detected"
`        Link detected: yes
`
```
/home/spdk/build/examples/perf -q 128 -o 262144 -w randrw -M 50 -t 2 -r 'trtype:rdma adrfam:IPv4 traddr:10.67.110.182 trsvcid:4420'
Starting SPDK v20.07-pre git sha1 b0a28e950 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid49016 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
[2020-07-30 09:51:51.486145] rdma.c: 584:nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 123, maybe hardware issue
[2020-07-30 09:51:51.680243] rdma.c: 584:nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 59, maybe hardware issue

Attached to NVMe over Fabrics controller at 10.67.110.182:4420: nqn.2016-06.io.spdk:cnode1
controller IO queue size 128 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
controller IO queue size 128 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
Associating RDMA (addr:10.67.110.182 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 2 with lcore 0
Associating RDMA (addr:10.67.110.182 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 with lcore 0
Initialization complete. Launching workers.
[2020-07-30 09:51:51.837387] rdma.c: 584:nvmf_rdma_update_ibv_state: *ERROR*: QP#1: bad state updated: 187, maybe hardware issue
[2020-07-30 09:51:51.890372] rdma.c: 584:nvmf_rdma_update_ibv_state: *ERROR*: QP#2: bad state updated: 123, maybe hardware issue
[2020-07-30 09:51:51.979308] rdma.c:3684:_qp_reset_failed_sends: *ERROR*: Failed to post a send for the qpair 0x612000002bc0 with errno 22
[2020-07-30 09:51:51.998442] rdma.c:3684:_qp_reset_failed_sends: *ERROR*: Failed to post a send for the qpair 0x612000002a40 with errno 22
        0 IOPS,     0.00 MiB/s

```

**Comment by yidong0635** [comment]
I checked above log , that the IP address is not right. The test scripts may have issue.

**Comment by AlekseyMarchuk** [comment]
Hi @yidong0635, you wrote that test script may have an issue, Have you checked it? Is this issue still relevant?

**Comment by yidong0635** [comment]
@AlekseyMarchuk  For the issue described as "can't kill -9" is still existed.
I said the test scripts have issue:  
1. test scripts can't find  the right rdma nic to test perf(this is not fatal,maybe overlook this , or sort NICS)
2. even though I deleted an address, the test scripts still can found it.
3. Second target IP and First target IP sometimes not right to meet nvmf test. 
In all , I want to run this locally, but I don't want to get stuck our machine that only restart a machine can recover.

**Comment by yidong0635** [comment]
@AlekseyMarchuk  I git pull the latest code, and test again , "can't kill -9 " this issue disappeared. Are there any updates ?
If so we can close this one .

**Comment by yidong0635** [comment]
corrected , there's still some threads not clean:
ps -ef |grep perf
root       13146       1  0 Jul29 ?        00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root       15465       1  0 Jul29 ?        00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root       18264       1  0 Jul29 ?        00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root       28480       1  0 Jul31 ?        00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      181913       1  0 Aug05 pts/1    00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      214865       1  0 Aug05 ?        00:00:01 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      678736  678638  0 11:52 pts/5    00:00:01 /home/spdk/build/examples/perf -q 64 -o 4096 -w randrw -M 30 -t 10 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1
root      678868       1  0 11:53 pts/5    00:00:03 /home/yidong/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      679005       1  0 11:55 pts/5    00:00:03 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420
root      689022       1  1 12:00 pts/5    00:00:03 /home/spdk/build/examples/perf -q 1 -o 4096 -w randrw -M 50 -t 1 -r trtype:rdma adrfam:IPv4 traddr:192.168.1.1 trsvcid:4420

**Comment by jimharris** [comment]
Hi @yidong0635,

Can you update this issue with your latest findings with current SPDK master?  Please close if this issue is no longer relevant.

If the issue still exists, please provide very clear and concise instructions so that @AlekseyMarchuk can try to reproduce.

Thanks,

Jim

**Comment by yidong0635** [comment]
@jimharris @AlekseyMarchuk ,
using the latest master branch, test script looks good.
It's strong enough .
with a RDMA cable in or out, tests are ok which are exceeded the expectation even without a cable .
```
[root@waikikibeach45 spdk]# ifconfig
enp216s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 7c:fe:90:c4:0b:f0  txqueuelen 1000  (Ethernet)
        RX packets 2491  bytes 149460 (145.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 69  bytes 13256 (12.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
[root@waikikibeach45 spdk]# ethtool enp216s0 | grep Link
        Link detected: no
Does it have some remember function?
```
but I think we can close this one.
