### ISSUE TITLE
[iscsi-vg-autotest/bdev_nbd] g_accel_task_pool allocation failed

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1510]
00:10:03.561  ************************************
00:10:03.561  START TEST bdev_nbd
00:10:03.561  ************************************
00:10:03.561   22:29:56	# xtrace_enable
00:10:03.561   22:29:56	# nbd_function_test /home/vagrant/spdk_repo/spdk/test/bdev/bdev.json Ceph0
00:10:03.562    22:29:56	# uname -s
00:10:03.563   22:29:56	# '[' Linux = Linux ']'
00:10:03.563   22:29:56	# modprobe -n nbd
00:10:03.567   22:29:56	# local rpc_server=/var/tmp/spdk-nbd.sock
00:10:03.567   22:29:56	# local conf=/home/vagrant/spdk_repo/spdk/test/bdev/bdev.json
00:10:03.567   22:29:56	# nbd_all=($(ls /dev/nbd* | grep -v p))
00:10:03.570    22:29:56	# ls /dev/nbd0 /dev/nbd1 /dev/nbd10 /dev/nbd11 /dev/nbd12 /dev/nbd13 /dev/nbd14 /dev/nbd15 /dev/nbd2 /dev/nbd3 /dev/nbd4 /dev/nbd5 /dev/nbd6 /dev/nbd7 /dev/nbd8 /dev/nbd9
00:10:03.570    22:29:56	# grep -v p
00:10:03.571   22:29:56	# local nbd_all
00:10:03.571   22:29:56	# bdev_all=($bdevs_name)
00:10:03.571   22:29:56	# local bdev_all
00:10:03.571   22:29:56	# local nbd_num=0
00:10:03.571   22:29:56	# '[' 16 -le 0 ']'
00:10:03.571   22:29:56	# nbd_list=(${nbd_all[@]:0:$nbd_num})
00:10:03.571   22:29:56	# local nbd_list
00:10:03.571   22:29:56	# bdev_list=(${bdev_all[@]:0:$nbd_num})
00:10:03.571   22:29:56	# local bdev_list
00:10:03.572   22:29:56	# '[' '!' -e /home/vagrant/spdk_repo/spdk/test/bdev/bdev.json ']'
00:10:03.572   22:29:56	# modprobe nbd
00:10:03.576  Process nbd pid: 34271
00:10:03.576  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk-nbd.sock...
00:10:03.576   22:29:56	# nbd_pid=34271
00:10:03.576   22:29:56	# trap 'killprocess $nbd_pid; exit 1' SIGINT SIGTERM EXIT
00:10:03.576   22:29:56	# /home/vagrant/spdk_repo/spdk/test/app/bdev_svc/bdev_svc -r /var/tmp/spdk-nbd.sock -i 0 --json /home/vagrant/spdk_repo/spdk/test/bdev/bdev.json
00:10:03.576   22:29:56	# echo 'Process nbd pid: 34271'
00:10:03.576   22:29:56	# waitforlisten 34271 /var/tmp/spdk-nbd.sock
00:10:03.576   22:29:56	# '[' -z 34271 ']'
00:10:03.576   22:29:56	# local rpc_addr=/var/tmp/spdk-nbd.sock
00:10:03.576   22:29:56	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk-nbd.sock...'
00:10:03.576   22:29:56	# xtrace_disable
00:10:03.576   22:29:56	# '[' no '!=' yes ']'
00:10:03.576   22:29:56	# PREV_BASH_OPTS=ehxBET
00:10:03.576   22:29:56	# [[ ehxBET == *\x* ]]
00:10:03.576   22:29:56	# XTRACE_DISABLED=yes
00:10:03.576   22:29:56	# set +x
00:10:03.624  Starting SPDK v20.07-pre git sha1 f41616ca3 / DPDK 20.05.0 initialization...
00:10:03.624  [ DPDK EAL parameters: bdev_svc -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
00:10:03.648  EAL: No legacy callbacks, legacy socket not created
00:10:03.672  [2020-07-27 22:29:56.880563] app.c: 666:spdk_app_start: *NOTICE*: Total cores available: 1
00:10:04.285  [2020-07-27 22:29:57.493353] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
00:10:04.313  [2020-07-27 22:29:57.521611] accel_engine.c: 498:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:10:04.313  bdev_svc: accel_engine.c:491: accel_engine_module_initialize: Assertion `g_accel_task_pool' failed.
00:10:04.425  /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 628: 34271 Aborted                 (core dumped) $rootdir/test/app/bdev_svc/bdev_svc -r $rpc_server -i 0 --json "$conf"
00:10:04.927  ERROR: process (pid: 34271) is no longer running
00:10:04.927  /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 644: kill: (34271) - No such process
00:10:0
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_23189.html

## Execution failed at

00:10:04.928  ========== Backtrace start: ==========
00:10:04.928  
00:10:04.940  in ./test/bdev/blockdev.sh:176 -> nbd_function_test(["/home/vagrant/spdk_repo/spdk/test/bdev/bdev.json"],["Ceph0"])
00:10:04.940       ...
00:10:04.940     171 			modprobe nbd
00:10:04.940     172 			$rootdir/test/app/bdev_svc/bdev_svc -r $rpc_server -i 0 --json "$conf" &
00:10:04.940     173 			nbd_pid=$!
00:10:04.940     174 			trap 'killprocess $nbd_pid; exit 1' SIGINT SIGTERM EXIT
00:10:04.940     175 			echo "Process nbd pid: $nbd_pid"
00:10:04.940  => 176 			waitforlisten $nbd_pid $rpc_server
00:10:04.940     177 	
00:10:04.940     178 			nbd_rpc_start_stop_verify $rpc_server "${bdev_list[*]}"
00:10:04.940     179 			nbd_rpc_data_verify $rpc_server "${bdev_list[*]}" "${nbd_list[*]}"
00:10:04.940     180 	
00:10:04.940     181 			killprocess $nbd_pid
00:10:04.940       ...
00:10:04.946  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:924 -> run_test(["bdev_nbd"],["nbd_function_test"],["/home/vagrant/spdk_repo/spdk/test/bdev/bdev.json"],["Ceph0"])
00:10:04.946       ...
00:10:04.946     919 		timing_enter $test_name
00:10:04.946     920 		echo "************************************"
00:10:04.946     921 		echo "START TEST $test_name"
00:10:04.946     922 		echo "************************************"
00:10:04.946     923 		xtrace_restore
00:10:04.946  => 924 		time "$@"
00:10:04.946     925 		xtrace_disable
00:10:04.946     926 		echo "************************************"
00:10:04.946     927 		echo "END TEST $test_name"
00:10:04.946     928 		echo "************************************"
00:10:04.946     929 		timing_exit $test_name
00:10:04.946       ...
00:10:04.952  Process with pid 34271 is not found
00:10:04.952  in ./test/bdev/blockdev.sh:373 -> main(["rbd"])
00:10:04.952       ...
00:10:04.952     368 	# End bdev configuration
00:10:04.952     369 	#-----------------------------------------------------
00:10:04.952     370 	
00:10:04.952     371 	run_test "bdev_hello_world" $SPDK_EXAMPLE_DIR/hello_bdev --json "$conf_file" -b "$hello_world_bdev"
00:10:04.952     372 	run_test "bdev_bounds" bdev_bounds
00:10:04.952  => 373 	run_test "bdev_nbd" nbd_function_test $conf_file "$bdevs_name"
00:10:04.952     374 	if [[ $CONFIG_FIO_PLUGIN == y ]]; then
00:10:04.952     375 		if [ "$test_type" = "nvme" ] || [ "$test_type" = "gpt" ]; then
00:10:04.952     376 			# TODO: once we get real multi-ns drives, re-enable this test for NVMe.
00:10:04.952     377 			echo "skipping fio tests on NVMe due to multi-ns failures."
00:10:04.952     378 		else
00:10:04.952       ...
00:10:04.952  
00:10:04.952  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_23189.html

**Comment by peluse** [comment]
@karlatec for this VM, how much hugepage mem is setup?

**Comment by karlatec** [comment]
@peluse Each VM gets 12288MB of memory

**Comment by tomzawadzki** [comment]
[Bug scrub] @peluse Any other environment details we could provide to help solve this issue ?
