### ISSUE TITLE
[centos7-vg-autotest] Build timed out

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1511]
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_23216.html

## Execution failed at
Git works too slow:

```
00:00:00.394  copy managed file [copy_or_clone] to file:/var/jenkins/workspace/centos7-vg-autotest/copy_or_clone.sh
00:00:00.405  [centos7-vg-autotest] $ /usr/bin/env bash /tmp/jenkins6204418001908644890.sh
00:00:00.413  MANUAL, will clone
00:00:00.415  Cloning into '/var/jenkins/workspace/centos7-vg-autotest/spdk'...
00:00:03.701  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:01:04.578  git version 2.17.1
00:01:07.494  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:12:10.023  remote: Counting objects: 1           
remote: Counting objects: 14, done        
00:12:10.183  remote: Finding sources:  11% (1/9)           
remote: Finding sources:  22% (2/9)           
remote: Finding sources:  33% (3/9)           
remote: Finding sources:  44% (4/9)           
remote: Finding sources:  55% (5/9)           
remote: Finding sources:  66% (6/9)           
remote: Finding sources:  77% (7/9)           
remote: Finding sources:  88% (8/9)           
remote: Finding sources: 100% (9/9)           
remote: Finding sources: 100% (9/9)        
00:12:10.239  remote: Total 9 (delta 4), reused 9 (delta 4)        
00:12:10.308  From https://review.spdk.io/spdk/spdk
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_23216.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23324.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_23572.html

**Comment by karlatec** [comment]
> Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_23572.html

Not related. Unit test compilation fail.

> Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23324.html

Not related.  Well, kind of. It is timeout, but different test job and timeout was just close to finishing the tests.

**Comment by tomzawadzki** [comment]
Closing this Intermittent Failure since last occurrence was over a month ago.

**Comment by AlekseyMarchuk** [comment]
I met this problem again:
https://ci.spdk.io/public_build/autotest-per-patch_27223.html

```
00:00:00.580  [crypto-autotest] $ /usr/bin/env bash /tmp/jenkins1868893082996481414.sh
00:00:00.592  MANUAL, will clone
00:00:00.602  Cloning into '/var/jenkins/workspace/crypto-autotest/spdk'...
00:00:02.930  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:11:16.381  git version 2.26.2
00:11:18.374  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:11:19.039  remote: Counting objects: 1           
remote: Counting objects: 9, done        
```
Maybe it is a temporary connectivity issue? I'll keep this issue closed until another occurrence.
