### ISSUE TITLE
[ocf_fio_modes] dd fails, operation not supported.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1515]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/23238/archive/nvme-phy-autotest/build.log

## Execution failed at

00:06:42.333   21:30:30	# mountpoints=0
00:06:42.333   21:30:30	# '[' 0 '!=' 0 ']'
00:06:42.333   21:30:30	# dd if=/dev/zero of=/dev/nvme0n1 bs=1M count=1000 oflag=direct
00:06:42.336  dd: error writing '/dev/nvme0n1': Operation not supported
00:06:42.336  1+0 records in
00:06:42.336  0+0 records out

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23238.html

**Comment by tomzawadzki** [comment]
Duplicate of #1456
