### ISSUE TITLE
[nvmf-vg-autotest] bdevperf failure related with nvme_rdma driver

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1521]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/23348/archive/nvmf-vg-autotest/build.log

## Execution failed at

ccel_engine.c: 509:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:05:32.117  [2020-07-30 02:28:10.976645] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0xa2a430, Response Index 10731114 (5): Work Request Flushed Error
00:05:32.157  [2020-07-30 02:28:11.016511] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0xa3c640, Response Index 10651866 (5): Work Request Flushed Error
00:05:32.432   02:28:11	# xtrace_enable
00:05:32.432   02:28:11	# (( i == 0 ))
00:05:32.432   02:28:11	# return 0
00:05:32.432   02:28:11	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock framework_wait_init
00:05:32.548   02:28:11	# kill -9 24110
00:05:32.548   02:28:11	# rm -f /var/run/spdk_bdev1
00:05:32.549   02:28:11	# sleep 1
00:05:33.552  test/nvmf/target/shutdown.sh: line 76: 24110 Killed                  $rootdir/test/app/bdev_svc/bdev_svc -m 0x1 -i 1 -r /var/tmp/bdevperf.sock --json <(gen_nvmf_target_json "${num_subsystems[@]}")
00:05:33.552   02:28:12	# kill -0 24042
00:05:33.552   02:28:12	# /home/vagrant/spdk_repo/spdk/test/bdev/bdevperf/bdevperf -r /var/tmp/bdevperf.sock --json /dev/fd/62 -q 64 -o 65536 -w verify -t 1
00:05:33.552    02:28:12	# gen_nvmf_target_json 1 2
00:05:33.552    02:28:12	# config=()
00:05:33.552    02:28:12	# local subsystem config
00:05:33.552    02:28:12	# for subsystem in "${@:-1}"
00:05:33.552    02:28:12	# config+=("$(
00:05:33.552  				cat <<- EOF
00:05:33.552  					{
00:05:33.552  					  "params": {
00:05:33.552  					    "name": "Nvme$subsystem",
00:05:33.552  					    "trtype": "$TEST_TRANSPORT",
00:05:33.552  					    "traddr": "$NVMF_FIRST_TARGET_IP",
00:05:33.552  					    "adrfam": "ipv4",
00:05:33.552  					    "trsvcid": "$NVMF_PORT",
00:05:33.552  					    "subnqn": "nqn.2016-06.io.spdk:cnode$subsystem"
00:05:33.552  					  },
00:05:33.552  					  "method": "bdev_nvme_attach_controller"
00:05:33.552  					}
00:05:33.552  				EOF
00:05:33.552  			)")
00:05:33.554     02:28:12	# cat
00:05:33.558    02:28:12	# for subsystem in "${@:-1}"
00:05:33.558    02:28:12	# config+=("$(
00:05:33.558  				cat <<- EOF
00:05:33.558  					{
00:05:33.558  					  "params": {
00:05:33.558  					    "name": "Nvme$subsystem",
00:05:33.558  					    "trtype": "$TEST_TRANSPORT",
00:05:33.558  					    "traddr": "$NVMF_FIRST_TARGET_IP",
00:05:33.558  					    "adrfam": "ipv4",
00:05:33.558  					    "trsvcid": "$NVMF_PORT",
00:05:33.558  					    "subnqn": "nqn.2016-06.io.spdk:cnode$subsystem"
00:05:33.558  					  },
00:05:33.558  					  "method": "bdev_nvme_attach_controller"
00:05:33.558  					}
00:05:33.558  				EOF
00:05:33.558  			)")
00:05:33.558     02:28:12	# cat
00:05:33.562    02:28:12	# jq .
00:05:33.564     02:28:12	# IFS=,
00:05:33.564     02:28:12	# printf '%s\n' '{
00:05:33.564    "params": {
00:05:33.564      "name": "Nvme1",
00:05:33.564      "trtype": "rdma",
00:05:33.564      "traddr": "192.168.121.46",
00:05:33.564      "adrfam": "ipv4",
00:05:33.564      "trsvcid": "4420",
00:05:33.564      "subnqn": "nqn.2016-06.io.spdk:cnode1"
00:05:33.564    },
00:05:33.564    "method": "bdev_nvme_attach_controller"
00:05:33.564  },{
00:05:33.564    "params": {
00:05:33.564      "name": "Nvme2",
00:05:33.564      "trtype": "rdma",
00:05:33.564      "traddr": "192.168.121.46",
00:05:33.564      "adrfam": "ipv4",
00:05:33.564      "trsvcid": "4420",
00:05:33.564      "subnqn": "nqn.2016-06.io.spdk:cnode2"
00:05:33.564    },
00:05:33.564    "method": "bdev_nvme_attach_controller"
00:05:33.564  }'
00:05:33.593  Starting SPDK v20.07-pre git sha1 7eaf51d5c / DPDK 20.05.0 initialization...
00:05:33.593  [ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid24131 ]
00:05:33.599  EAL: No available hugepages reported in hugepages-1048576kB
00:05:33.703  EAL: No legacy callbacks, legacy socket not created
00:05:33.725  [2020-07-30 02:28:12.584097] app.c: 666:spdk_app_start: *NOTICE*: Total cores available: 1
00:05:33.899  [2020-07-30 02:28:12.758210] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
00:05:33.899  [2020-07-30 02:28:12.758926] accel_engine.c: 509:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:05:34.006  [2020-07-30 02:28:12.865516] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0xdf1780, Response Index 14692794 (5): Work Request Flushed Error
00:05:34.057  Running I/O for 1 seconds...
00:05:34.068  [2020-07-30 02:28:12.927572] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0xe03a90, Response Index 14613482 (5): Work Request Flushed Error
00:05:35.073  [2020-07-30 02:28:13.931544] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0xdc7140, Response Index 14448698 (5): Work Request Flushed Error
00:05:35.074  
 Thread name: Nvme1n1_1
00:05:35.074  
 Core Mask: 0x1
00:05:35.074  
 Nvme1n1             :    2773.00 IOPS     173.31 MiB/s
00:05:35.074  
 Thread name: Nvme2n1_1
00:05:35.074  
 Core Mask: 0x1
00:05:35.074  
 Nvme2n1             :    2770.00 IOPS     173.12 MiB/s
00:05:35.074  
 =====================================================
00:05:35.074  
 Total               :    5543.00 IOPS     346.44 MiB/s
00:05:35.082  [2020-07-30 02:28:13.941515] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0xdc8430, Response Index 14459530 (5): Work Request Flushed Error
00:05:35.300   02:28:14	# stoptarget
00:05:35.300   02:28:14	# rm -f ./local-job0-0-verify.state
00:05:35.301   02:28:14	# rm -rf /home/vagrant/spdk_repo/spdk/test/nvmf/target/bdevperf.conf
00:05:35.302   02:28:14	# rm -rf /home/vagrant/spdk_repo/spdk/test/nvmf/target/rpcs.txt
00:05:35.304   02:28:14	# nvmftestfini
00:05:35.304   02:28:14	# nvmfcleanup
00:05:35.304   02:28:14	# sync
00:05:35.317   02:28:14	# set +e
00:05:35.317   02:28:14	# for i in {1..20}
00:05:35.317   02:28:14	# modprobe -v -r nvme-rdma
00:05:35.322  rmmod nvme_rdma
00:05:35.329  rmmod nvme_fabrics
00:05:35.338   02:28:14	# modprobe -v -r nvme-fabrics
00:05:35.343   02:28:14	# set -e
00:05:35.343   02:28:14	# return 0
00:05:35.343   02:28:14	# '[' -n 24042 ']'
00:05:35.343   02:28:14	# killprocess 24042
00:05:35.343   02:28:14	# '[' -z 24042 ']'
00:05:35.343   02:28:14	# kill -0 24042
00:05:35.343    02:28:14	# uname
00:05:35.346   02:28:14	# '[' Linux = Linux ']'
00:05:35.347    02:28:14	# ps --no-headers -o comm= 24042
00:05:35.364  killing process with pid 24042
00:05:35.364   02:28:14	# process_name=reactor_1
00:05:35.364   02:28:14	# '[' reactor_1 = sudo ']'
00:05:35.364   02:28:14	# echo 'killing process with pid 24042'
00:05:35.364   02:28:14	# kill 24042
00:05:35.364   02:28:14	# wait 24042
00:05:39.383  ************************************
00:05:39.383  END TEST nvmf_shutdown_tc1
00:05:39.383  ************************************
00:05:39.383   02:28:18	# '[' '' == iso ']'
00:05:39.383  
00:05:39.383  real	0m9.091s
00:05:39.383  user	0m36.313s
00:05:39.383  sys	0m1.255s
00:05:39.383   02:28:18	# xtrace_disable
00:05:39.383   02:28:18	# '[' no '!=' yes ']'
00:05:39.383   02:28:18	# PREV_BASH_OPTS=ehxBET
00:05:39.383   02:28:18	# [[ ehxBET == *\x* ]]
00:05:39.383   02:28:18	# XTRACE_DISABLED=yes
00:05:39.383   02:28:18	# set +x
00:05:39.417   02:28:18	# xtrace_enable
00:05:39.417   02:28:18	# run_test nvmf_shutdown_tc2 nvmf_shutdown_tc2
00:05:39.417   02:28:18	# '[' 2 -le 1 ']'
00:05:39.417   02:28:18	# xtrace_disable
00:05:39.417   02:28:18	# '[' no '!=' yes ']'
00:05:39.417   02:28:18	# PREV_BASH_OPTS=ehxBET
00:05:39.417   02:28:18	# [[ ehxBET == *\x* ]]
00:05:39.417   02:28:18	# XTRACE_DISABLED=yes
00:05:39.417   02:28:18	# set +x
00:05:39.421  ************************************
00:05:39.421  START TEST nvmf_shutdown_tc2
00:05:39.421  ************************************
00:05:39.421   02:28:18	# xtrace_enable
00:05:39.421   02:28:18	# nvmf_shutdown_tc2
00:05:39.421   02:28:18	# starttarget
00:05:39.421   02:28:18	# nvmfappstart -m 0x1E
00:05:39.421   02:28:18	# timing_enter start_nvmf_tgt
00:05:39.421   02:28:18	# xtrace_disable
00:05:39.421   02:28:18	# '[' no '!=' yes ']'
00:05:39.421   02:28:18	# PREV_BASH_OPTS=ehxBET
00:05:39.421   02:28:18	# [[ ehxBET == *\x* ]]
00:05:39.421   02:28:18	# XTRACE_DISABLED=yes
00:05:39.421   02:28:18	# set +x
00:05:39.427  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:05:39.427   02:28:18	# xtrace_enable
00:05:39.427   02:28:18	# nvmfpid=24175
00:05:39.427   02:28:18	# trap 'process_shm --id $NVMF_APP_SHM_ID; nvmftestfini; exit 1' SIGINT SIGTERM EXIT
00:05:39.427   02:28:18	# waitforlisten 24175
00:05:39.427   02:28:18	# /home/vagrant/spdk_repo/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x1E
00:05:39.427   02:28:18	# '[' -z 24175 ']'
00:05:39.427   02:28:18	# local rpc_addr=/var/tmp/spdk.sock
00:05:39.427   02:28:18	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:05:39.427   02:28:18	# xtrace_disable
00:05:39.427   02:28:18	# '[' no '!=' yes ']'
00:05:39.427   02:28:18	# PREV_BASH_OPTS=ehxBET
00:05:39.427   02:28:18	# [[ ehxBET == *\x* ]]
00:05:39.427   02:28:18	# XTRACE_DISABLED=yes
00:05:39.427   02:28:18	# set +x
00:05:39.464  Starting SPDK v20.07-pre git sha1 7eaf51d5c / DPDK 20.05.0 initialization...
00:05:39.464  [ DPDK EAL parameters: nvmf -c 0x1E --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
00:05:39.469  EAL: No available hugepages reported in hugepages-1048576kB
00:05:39.571  EAL: No legacy callbacks, legacy socket not created
00:05:39.587  [2020-07-30 02:28:18.446194] app.c: 666:spdk_app_start: *NOTICE*: Total cores available: 4
00:05:39.707  [2020-07-30 02:28:18.565968] app.c: 563:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
00:05:39.707  [2020-07-30 02:28:18.566036] app.c: 564:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
00:05:39.707  [2020-07-30 02:28:18.566044] app.c: 569:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
00:05:39.707  [2020-07-30 02:28:18.566214] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 2
00:05:39.708  [2020-07-30 02:28:18.567023] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 3
00:05:39.713  [2020-07-30 02:28:18.567661] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 4
00:05:39.713  [2020-07-30 02:28:18.568203] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 1
00:05:39.713  [2020-07-30 02:28:18.568255] accel_engine.c: 509:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:05:40.208   02:28:19	# xtrace_enable
00:05:40.208   02:28:19	# (( i == 0 ))
00:05:40.208   02:28:19	# return 0
00:05:40.208   02:28:19	# timing_exit start_nvmf_tgt
00:05:40.208   02:28:19	# xtrace_disable
00:05:40.208   02:28:19	# '[' no '!=' yes ']'
00:05:40.208   02:28:19	# PREV_BASH_OPTS=ehxBET
00:05:40.208   02:28:19	# [[ ehxBET == *\x* ]]
00:05:40.208   02:28:19	# XTRACE_DISABLED=yes
00:05:40.208   02:28:19	# set +x
00:05:40.239   02:28:19	# xtrace_enable
00:05:40.239   02:28:19	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_create_transport -t rdma -u 8192
00:05:40.447   02:28:19	# num_subsystems=({1..10})
00:05:40.447   02:28:19	# check_ip_is_soft_roce 192.168.121.46
00:05:40.447   02:28:19	# rxe_cfg status rxe
00:05:40.447   02:28:19	# /home/vagrant/spdk_repo/spdk/scripts/rxe_cfg_small.sh status rxe
00:05:40.448   02:28:19	# grep -wq 192.168.121.46
00:05:40.482   02:28:19	# num_subsystems=({1..2})
00:05:40.482   02:28:19	# timing_enter create_subsystems
00:05:40.482   02:28:19	# xtrace_disable
00:05:40.482   02:28:19	# '[' no '!=' yes ']'
00:05:40.482   02:28:19	# PREV_BASH_OPTS=ehxBET
00:05:40.482   02:28:19	# [[ ehxBET == *\x* ]]
00:05:40.482   02:28:19	# XTRACE_DISABLED=yes
00:05:40.482   02:28:19	# set +x
00:05:40.485   02:28:19	# xtrace_enable
00:05:40.485   02:28:19	# rm -rf /home/vagrant/spdk_repo/spdk/test/nvmf/target/rpcs.txt
00:05:40.487   02:28:19	# for i in "${num_subsystems[@]}"
00:05:40.487   02:28:19	# cat
00:05:40.490   02:28:19	# for i in "${num_subsystems[@]}"
00:05:40.490   02:28:19	# cat
00:05:40.493   02:28:19	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py
00:05:40.659  [2020-07-30 02:28:19.517877] rdma.c:2677:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.121.46 port 4420 ***
00:05:40.718  Malloc1
00:05:40.718  Malloc2
00:05:40.731   02:28:19	# timing_exit create_subsystems
00:05:40.731   02:28:19	# xtrace_disable
00:05:40.731   02:28:19	# '[' no '!=' yes ']'
00:05:40.731   02:28:19	# PREV_BASH_OPTS=ehxBET
00:05:40.731   02:28:19	# [[ ehxBET == *\x* ]]
00:05:40.731   02:28:19	# XTRACE_DISABLED=yes
00:05:40.731   02:28:19	# set +x
00:05:40.764  Waiting for process to start up and listen on UNIX domain socket /var/tmp/bdevperf.sock...
00:05:40.764   02:28:19	# xtrace_enable
00:05:40.764   02:28:19	# perfpid=24243
00:05:40.764   02:28:19	# waitforlisten 24243 /var/tmp/bdevperf.sock
00:05:40.764   02:28:19	# '[' -z 24243 ']'
00:05:40.764   02:28:19	# local rpc_addr=/var/tmp/bdevperf.sock
00:05:40.764   02:28:19	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/bdevperf.sock...'
00:05:40.764   02:28:19	# xtrace_disable
00:05:40.764   02:28:19	# '[' no '!=' yes ']'
00:05:40.764   02:28:19	# PREV_BASH_OPTS=ehxBET
00:05:40.764   02:28:19	# [[ ehxBET == *\x* ]]
00:05:40.764   02:28:19	# XTRACE_DISABLED=yes
00:05:40.764   02:28:19	# set +x
00:05:40.764   02:28:19	# /home/vagrant/spdk_repo/spdk/test/bdev/bdevperf/bdevperf -r /var/tmp/bdevperf.sock --json /dev/fd/63 -q 64 -o 65536 -w verify -t 10
00:05:40.764    02:28:19	# gen_nvmf_target_json 1 2
00:05:40.764    02:28:19	# config=()
00:05:40.764    02:28:19	# local subsystem config
00:05:40.764    02:28:19	# for subsystem in "${@:-1}"
00:05:40.764    02:28:19	# config+=("$(
00:05:40.764  				cat <<- EOF
00:05:40.764  					{
00:05:40.764  					  "params": {
00:05:40.764  					    "name": "Nvme$subsystem",
00:05:40.764  					    "trtype": "$TEST_TRANSPORT",
00:05:40.764  					    "traddr": "$NVMF_FIRST_TARGET_IP",
00:05:40.764  					    "adrfam": "ipv4",
00:05:40.764  					    "trsvcid": "$NVMF_PORT",
00:05:40.764  					    "subnqn": "nqn.2016-06.io.spdk:cnode$subsystem"
00:05:40.764  					  },
00:05:40.764  					  "method": "bdev_nvme_attach_controller"
00:05:40.764  					}
00:05:40.764  				EOF
00:05:40.764  			)")
00:05:40.766     02:28:19	# cat
00:05:40.770    02:28:19	# for subsystem in "${@:-1}"
00:05:40.770    02:28:19	# config+=("$(
00:05:40.770  				cat <<- EOF
00:05:40.770  					{
00:05:40.770  					  "params": {
00:05:40.770  					    "name": "Nvme$subsystem",
00:05:40.770  					    "trtype": "$TEST_TRANSPORT",
00:05:40.770  					    "traddr": "$NVMF_FIRST_TARGET_IP",
00:05:40.770  					    "adrfam": "ipv4",
00:05:40.770  					    "trsvcid": "$NVMF_PORT",
00:05:40.770  					    "subnqn": "nqn.2016-06.io.spdk:cnode$subsystem"
00:05:40.770  					  },
00:05:40.770  					  "method": "bdev_nvme_attach_controller"
00:05:40.770  					}
00:05:40.770  				EOF
00:05:40.770  			)")
00:05:40.770     02:28:19	# cat
00:05:40.773    02:28:19	# jq .
00:05:40.775     02:28:19	# IFS=,
00:05:40.775     02:28:19	# printf '%s\n' '{
00:05:40.775    "params": {
00:05:40.775      "name": "Nvme1",
00:05:40.775      "trtype": "rdma",
00:05:40.775      "traddr": "192.168.121.46",
00:05:40.775      "adrfam": "ipv4",
00:05:40.775      "trsvcid": "4420",
00:05:40.775      "subnqn": "nqn.2016-06.io.spdk:cnode1"
00:05:40.775    },
00:05:40.775    "method": "bdev_nvme_attach_controller"
00:05:40.775  },{
00:05:40.775    "params": {
00:05:40.775      "name": "Nvme2",
00:05:40.775      "trtype": "rdma",
00:05:40.775      "traddr": "192.168.121.46",
00:05:40.775      "adrfam": "ipv4",
00:05:40.775      "trsvcid": "4420",
00:05:40.775      "subnqn": "nqn.2016-06.io.spdk:cnode2"
00:05:40.775    },
00:05:40.775    "method": "bdev_nvme_attach_controller"
00:05:40.775  }'
00:05:40.800  Starting SPDK v20.07-pre git sha1 7eaf51d5c / DPDK 20.05.0 initialization...
00:05:40.800  [ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid24243 ]
00:05:40.805  EAL: No available hugepages reported in hugepages-1048576kB
00:05:40.910  EAL: No legacy callbacks, legacy socket not created
00:05:40.932  [2020-07-30 02:28:19.790399] app.c: 666:spdk_app_start: *NOTICE*: Total cores available: 1
00:05:41.090  [2020-07-30 02:28:19.948542] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
00:05:41.090  [2020-07-30 02:28:19.949216] accel_engine.c: 509:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:05:41.190  [2020-07-30 02:28:20.048503] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0x193d780, Response Index 26538426 (5): Work Request Flushed Error
00:05:41.250  Running I/O for 10 seconds...
00:05:41.250  [2020-07-30 02:28:20.108584] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0x194fa90, Response Index 26459082 (5): Work Request Flushed Error
00:05:41.547   02:28:20	# xtrace_enable
00:05:41.547   02:28:20	# (( i == 0 ))
00:05:41.547   02:28:20	# return 0
00:05:41.547   02:28:20	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock framework_wait_init
00:05:41.667   02:28:20	# waitforio /var/tmp/bdevperf.sock Nvme1n1
00:05:41.667   02:28:20	# '[' -z /var/tmp/bdevperf.sock ']'
00:05:41.667   02:28:20	# '[' -z Nvme1n1 ']'
00:05:41.667   02:28:20	# local ret=1
00:05:41.667   02:28:20	# local i
00:05:41.667   02:28:20	# (( i = 10 ))
00:05:41.667   02:28:20	# (( i != 0 ))
00:05:41.667    02:28:20	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_get_iostat -b Nvme1n1
00:05:41.667    02:28:20	# jq -r '.bdevs[0].num_read_ops'
00:05:41.807   02:28:20	# read_io_count=1481
00:05:41.807   02:28:20	# '[' 1481 -ge 100 ']'
00:05:41.807   02:28:20	# ret=0
00:05:41.807   02:28:20	# break
00:05:41.807   02:28:20	# return 0
00:05:41.807   02:28:20	# killprocess 24243
00:05:41.807   02:28:20	# '[' -z 24243 ']'
00:05:41.807   02:28:20	# kill -0 24243
00:05:41.807    02:28:20	# uname
00:05:41.810   02:28:20	# '[' Linux = Linux ']'
00:05:41.811    02:28:20	# ps --no-headers -o comm= 24243
00:05:41.827  killing process with pid 24243
00:05:41.827   02:28:20	# process_name=reactor_0
00:05:41.827   02:28:20	# '[' reactor_0 = sudo ']'
00:05:41.827   02:28:20	# echo 'killing process with pid 24243'
00:05:41.827   02:28:20	# kill 24243
00:05:41.827   02:28:20	# wait 24243
00:05:41.849  [2020-07-30 02:28:20.707601] nvme_rdma.c:2237:nvme_rdma_cq_process_completions: *ERROR*: CQ error on Queue Pair 0x19139e0, Response Index 26297242 (5): Work Request Flushed Error
00:05:41.850  Received shutdown signal, test time was about 0.578867 seconds

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_23348.html

**Comment by optimistyzy** [comment]
@AlekseyMarchuk  Can you look at this issue?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_23358.html

**Comment by changpe1** [comment]
[Bug Scrub] let's keep it open for while to see is this related with softRoCE.

**Comment by tomzawadzki** [comment]
The two reports here should have been moved to #1513, which share the error signature.
That issue was closed since shutdown tests for Soft-RoCE were disabled.

Since both issues are the same, closing this one too.
