### ISSUE TITLE
Disks or nvme-cli problem/bug

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1522]
Disk:
```
sudo nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     PHLJ9512048J2P0BGN   INTEL SSDPE2KX020T8                      1           2.00  TB /   2.00  TB    512   B +  0 B   VDV10170
```
Namespaces on disk:
```
sudo nvme list-ns /dev/nvme0 -a
[   0]:0x1
```
When trying to detach namespaces like we have in autotest_common.sh this will fail:
```
[sys_sgci@localhost ~]$ sudo nvme detach-ns /dev/nvme0n1 -n 0xffffffff -c 0
NVMe status: INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(0x4002)
```
When I detach namespaces without mask `0xffffffff `, but this way: `sudo nvme detach-ns /dev/nvme0n1 -n 0x1 -c 0` it works fine.
Next fail I have when trying to create new namespace using all the disk capacity reported by: 
```
sudo nvme id-ctrl /dev/nvme0 | grep cap
tnvmcap   : 2000398934016
unvmcap   : 2000398934016
```
with `bs=512`,  using this command:
```
sudo nvme create-ns /dev/nvme0 -s 3907029168 -c 3907029168 -b 512
NVMe status: NS_INSUFFICIENT_CAPACITY: Creating the namespace requires more free space than is currently available. The Command Specific Information field of the Error Information Log specifies the total amount of NVM capacity required to create the namespace in bytes(0x4115)
```

I do some manual tests, and figure out that I can create namespace on this disk using this `nvme create-ns` command like below: 
```
sudo nvme create-ns /dev/nvme0 -s 3905000000 -c 3905000000 -b 512
```
but this is `0,99948%` real disk capacity.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_23790.html

**Comment by wawryk** [comment]
It was tested on two nvme-cli versions:
```
nvme version 1.10.1
nvme version 1.11.1.9.ge770
```

**Comment by karlatec** [comment]
@AlekseyMarchuk 

> Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_23790.html

Fixed on GP12 by FW update

**Comment by tomzawadzki** [comment]
@karlatec thanks for the update.

Will close when no new reports show up in 7 days since your comment.
