### ISSUE TITLE
[iscsi_tgt_calsoft] timeout after successful test case run

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1523]
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_23507.html

## Execution failed at

```
00:04:14.926   11:30:05	# failed=0
00:04:14.926   11:30:05	# trap - SIGINT SIGTERM EXIT
00:04:14.926   11:30:05	# killprocess 22524
00:04:14.926   11:30:05	# '[' -z 22524 ']'
00:04:14.926   11:30:05	# kill -0 22524
00:04:14.927    11:30:05	# uname
00:04:14.929   11:30:05	# '[' Linux = Linux ']'
00:04:14.929    11:30:05	# ps --no-headers -o comm= 22524
00:04:14.942  killing process with pid 22524
00:04:14.942   11:30:05	# process_name=reactor_0
00:04:14.942   11:30:05	# '[' reactor_0 = sudo ']'
00:04:14.942   11:30:05	# echo 'killing process with pid 22524'
00:04:14.942   11:30:05	# kill 22524
00:04:14.942   11:30:05	# wait 22524
00:15:00.249  Build timed out (after 15 minutes). Marking the build as failed.
00:15:00.256  Build was aborted
00:15:00.257  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:00.268  [iscsi-vg-autotest] $ /usr/bin/env bash /tmp/jenkins1327033735374349468.sh
00:15:00.272  + mv /var/jenkins/workspace/iscsi-vg-autotest/fedora31-libvirt/output /var/jenkins/workspace/iscsi-vg-autotest/output
00:15:00.291  [iscsi-vg-autotest] $ /usr/bin/env bash /tmp/jenkins4892187287761222389.sh
00:15:00.351  + vagrant destroy -f
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_23507.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23821.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_23965.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_24056.html

**Comment by optimistyzy** [comment]
This is issue is related with ISCSI shutdown. It seems that the iSCSI target is waiting for some events, but the iSCSI target does not get it . I tried to produce this issue on my local physical machine, but cannot produce it (Running the calsoft testcases more than 20 times). So I think that it need some one's help to get some clues (e.g., to get some code execution path with some tools like pstack or others in Vagrant VM when executes the calsoft test). Then it will be helpful for the debug. @jimharris @shuhei-matsumoto

**Comment by tomzawadzki** [comment]
Closing this Intermittent Failure since last occurrence was over a month ago.
