### ISSUE TITLE
make CONFIG_WERROR=y fails

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#1528]
Building with CONFIG_WERROR=y option failing.

## Expected Behavior

SPDK should pass build.

## Current Behavior

Build with CONFIG_WERROR=y because of:
json_config.c: In function ‘app_json_config_load_subsystem_config_entry’:
json_config.c:415:3: error: ‘params_len’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   spdk_json_write_val_raw(w, cfg.params->start, params_len);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Possible Solution

Fix warning.

## Steps to Reproduce

1. ./configure
2. make CONFIG_WERROR=y

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 18.04,
SPDK from current master

**Comment by darsto** [comment]
Thanks, that's a recently introduced false positive. Fix here: https://review.spdk.io/gerrit/c/spdk/spdk/+/3626

**Comment by darsto** [comment]
Fix merged
