### ISSUE TITLE
--with-reduce causes compilation failure

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1529]
## Expected Behavior

SPDK successfully compiled when configured with the following parameters:
`./configure --with-rdma --with-pmdk --with-reduce`

## Current Behavior

DPDK compilation failed:

```
[183/255] Compiling C object drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_qp.c.o
FAILED: drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_qp.c.o
cc -Idrivers/libtmp_rte_pmd_qat.a.p -Idrivers -I../drivers -Idrivers/compress/qat -I../drivers/compress/qat -Idrivers/common/qat -I../drivers/common/qat -I../drivers/common/qat/qat_adf -Ilib/librte_compressdev -I../lib/librte_compressdev -I. -I.. -Iconfig -I../config -Ilib/librte_eal/include -I../lib/librte_eal/include -Ilib/librte_eal/linux/include -I../lib/librte_eal/linux/include -Ilib/librte_eal/arm/include -I../lib/librte_eal/arm/include -Ilib/librte_eal/common -I../lib/librte_eal/common -Ilib/librte_eal -I../lib/librte_eal -Ilib/librte_kvargs -I../lib/librte_kvargs -Ilib/librte_metrics -I../lib/librte_metrics -Ilib/librte_telemetry -I../lib/librte_telemetry -Ilib/librte_mbuf -I../lib/librte_mbuf -Ilib/librte_mempool -I../lib/librte_mempool -Ilib/librte_ring -I../lib/librte_ring -Idrivers/bus/pci -I../drivers/bus/pci -I../drivers/bus/pci/linux -Ilib/librte_pci -I../lib/librte_pci -I/root/repo/spdk/isa-l -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -O0 -g -Wno-error -fPIC -mcpu=cortex-a72 -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -Wno-format-truncation -MD -MQ drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_qp.c.o -MF drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_qp.c.o.d -o drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_qp.c.o -c ../drivers/common/qat/qat_qp.c
../drivers/common/qat/qat_qp.c:18:10: fatal error: qat_sym.h: No such file or directory
 #include "qat_sym.h"
          ^~~~~~~~~~~
compilation terminated.
[184/255] Compiling C object drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_device.c.o
FAILED: drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_device.c.o
cc -Idrivers/libtmp_rte_pmd_qat.a.p -Idrivers -I../drivers -Idrivers/compress/qat -I../drivers/compress/qat -Idrivers/common/qat -I../drivers/common/qat -I../drivers/common/qat/qat_adf -Ilib/librte_compressdev -I../lib/librte_compressdev -I. -I.. -Iconfig -I../config -Ilib/librte_eal/include -I../lib/librte_eal/include -Ilib/librte_eal/linux/include -I../lib/librte_eal/linux/include -Ilib/librte_eal/arm/include -I../lib/librte_eal/arm/include -Ilib/librte_eal/common -I../lib/librte_eal/common -Ilib/librte_eal -I../lib/librte_eal -Ilib/librte_kvargs -I../lib/librte_kvargs -Ilib/librte_metrics -I../lib/librte_metrics -Ilib/librte_telemetry -I../lib/librte_telemetry -Ilib/librte_mbuf -I../lib/librte_mbuf -Ilib/librte_mempool -I../lib/librte_mempool -Ilib/librte_ring -I../lib/librte_ring -Idrivers/bus/pci -I../drivers/bus/pci -I../drivers/bus/pci/linux -Ilib/librte_pci -I../lib/librte_pci -I/root/repo/spdk/isa-l -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -O0 -g -Wno-error -fPIC -mcpu=cortex-a72 -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -Wno-format-truncation -MD -MQ drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_device.c.o -MF drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_device.c.o.d -o drivers/libtmp_rte_pmd_qat.a.p/common_qat_qat_device.c.o -c ../drivers/common/qat/qat_device.c
../drivers/common/qat/qat_device.c:11:10: fatal error: qat_sym_pmd.h: No such file or directory
 #include "qat_sym_pmd.h"
```

## Possible Solution

I'm not familiar with meson/ninja, from DPDK output I see that `-I` directive doesn't point to `crypto/qat` directory where qat_sym_pmd.h is located. I applied the following workaround on my side

```
diff --git a/drivers/common/qat/meson.build b/drivers/common/qat/meson.build
index 8de2492..6a2e371 100644
--- a/drivers/common/qat/meson.build
+++ b/drivers/common/qat/meson.build
@@ -10,6 +10,6 @@ qat_sources = files('qat_common.c',
                'qat_qp.c',
                'qat_device.c',
                'qat_logs.c')
-qat_includes = [include_directories('.', 'qat_adf')]
+qat_includes = [include_directories('.', 'qat_adf', '../../crypto/qat', '../../../lib/librte_cryptodev')]
 qat_ext_deps = []
 qat_cflags = []
```

## Steps to Reproduce

```
./configure --with-rdma --with-pmdk --with-reduce
make -j
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK version `809ab04 version: 20.10 pre`
OS 1: CentOS Linux release 7.7.1908 (Core) 3.10.0-862.el7.x86_64
OS 2: Ubuntu 18.04.4 LTS 5.4.31

**Comment by changpe1** [comment]
[Bug Scrub] @peluse @darsto could you take a look for this issue?

**Comment by peluse** [comment]
LOL I just ran into this working on something else and found the previous issue (right here) via google. Didn't see the question to me above.  OK, I'll guess I'll own it ;)

**Comment by peluse** [comment]
@AlekseyMarchuk did your patch work? I tried it and get this:
------
In file included from ../drivers/common/qat/qat_qp.c:18:0:
../drivers/crypto/qat/qat_sym.h:10:10: fatal error: rte_net_crc.h: No such file or directory
 #include <rte_net_crc.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
------
@karlatec how are we building in CI --with-reduce?

**Comment by AlekseyMarchuk** [comment]
@peluse 
My workaround worked when I created this issue. Probably something has changed with the update of DPDK

**Comment by peluse** [comment]
I VAGUELY remember an issue with the old build system when trying to build crypto and compress at the same time there was an ordering issue.  If I choose crypto only, the meson output says its trying to build both and things work.  If I chose reduce only it also says both but things fail. I suspect that’s the problem.  If I choose BOTH then it builds OK so I’m pretty sure its an ordering dependency thing.  That’s a decent workaround for now - or so it seems I need to make sure compression works now.  Just do --with-crypto in addition to --with-reduce.  @AlekseyMarchuk can you try this on your system?

**Comment by AlekseyMarchuk** [comment]
@peluse 
You are right, configuring SPDK with both `--with-reduce` and `--with-crypto` solves this issue. The main difference from DPDK point of view is that `--with-crypto` also builds crypto/qat PMD. in crypto/qat/meson/build I see the following line: `qat_includes += include_directories('.')`. I'm not familiar with meson build system but I think that it adds the current directory (dpdk/drivers/crypto/qat) to common qat includes list. And this directory contains the missing qat_pmd_sym.h file, so that compress_qat now compiles fine). It seems that compress/qat can't be built without crypto/qat
I'm not sure if it is correct, but this small patch allows to build `reduce` without `crypto`
```
diff --git a/dpdkbuild/Makefile b/dpdkbuild/Makefile
index f6429eb44..d65c1e49f 100644
--- a/dpdkbuild/Makefile
+++ b/dpdkbuild/Makefile
@@ -59,7 +59,7 @@ DPDK_LDFLAGS += -L$(IPSEC_MB_DIR)
 endif

 ifeq ($(CONFIG_REDUCE),y)
-DPDK_DRIVERS += compress compress/isal compress/qat common/qat
+DPDK_DRIVERS += compress compress/isal crypto/qat compress/qat common/qat
 DPDK_CFLAGS += -I$(ISAL_DIR)
 DPDK_LDFLAGS += -L$(ISAL_DIR)/.libs -lisal
 endif

```

**Comment by peluse** [comment]
@AlekseyMarchuk I suppose that's not the worst thing ever, this isn't my area of expertise but it could be that in the old system changing the order handled the include issue. I played around with this a bit and couldn't find anything better.  Do you want to submit it @AlekseyMarchuk or should I?

**Comment by AlekseyMarchuk** [comment]
I pushed a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4179

**Comment by tomzawadzki** [comment]
[Bug scrub] Thanks @AlekseyMarchuk for fixing this. @peluse confirms that this is the right solution with DPDK right now.
