### ISSUE TITLE
[NVMe-phy-autotest] Cannot create new namespace during nvme_namespace_revert

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1532]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/23779/archive/nvme-phy-autotest/build.log

## Execution failed at
00:01:12.251  ========== Backtrace start: ==========
00:01:12.251  
00:01:12.257  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:1292 -> nvme_namespace_revert([])
00:01:12.257       ...
00:01:12.257     1287	
00:01:12.257     1288				size=$((tnvmcap / blksize))
00:01:12.257     1289	
00:01:12.257     1290				nvme detach-ns ${nvme_ctrlr} -n 0xffffffff -c 0 || true
00:01:12.257     1291				nvme delete-ns ${nvme_ctrlr} -n 0xffffffff || true
00:01:12.257     1292				nvme create-ns ${nvme_ctrlr} -s ${size} -c ${size} -b ${blksize}
00:01:12.257     1293				nvme attach-ns ${nvme_ctrlr} -n 1 -c 0
00:01:12.257     1294				nvme reset ${nvme_ctrlr}
00:01:12.257     1295				waitforblk "${nvme_ctrlr}n1"
00:01:12.257     1296			fi
00:01:12.257     1297		done
00:01:12.257       ...
00:01:12.261  in /var/jenkins/workspace/nvme-phy-autotest/spdk/autotest.sh:119 -> main(["/home/sys_sgci/autorun-spdk.conf"])
00:01:12.261       ...
00:01:12.262     114 			export PCI_BLACKLIST
00:01:12.262     115 		fi
00:01:12.262     116 	fi
00:01:12.262     117 	
00:01:12.262     118 	# Revert NVMe namespaces to default state
00:01:12.262  => 119 	nvme_namespace_revert
00:01:12.262     120 	
00:01:12.262     121 	# Delete all leftover lvols and gpt partitions
00:01:12.262     122 	# Matches both /dev/nvmeXnY on Linux and /dev/nvmeXnsY on BSD
00:01:12.262     123 	# Filter out nvme with partitions - the "p*" suffix
00:01:12.262     124 	for dev in $(ls /dev/nvme*n* | grep -v p || true); do
00:01:12.262       ...
00:01:12.262  
00:01:12.262  ========== Backtrace end ==========

## relevant log

00:01:12.244  NVMe status: INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(0x4002)
00:01:12.244   22:12:05	# true
00:01:12.244   22:12:05	# nvme delete-ns /dev/nvme0 -n 0xffffffff
00:01:12.246  NVMe status: INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(0x4002)
00:01:12.247   22:12:05	# true
00:01:12.247   22:12:05	# nvme create-ns /dev/nvme0 -s 1953525168 -c 1953525168 -b 512
00:01:12.249  NVMe status: NS_INSUFFICIENT_CAPACITY: Creating the namespace requires more free space than is currently available. The Command Specific Information field of the Error Information Log specifies the total amount of NVM capacity required to create the namespace in bytes(0x4115)
00:01:12.249    22:12:05	# trap - ERR
00:01:12.250    22:12:05	# print_backtrace
00:01:12.250    22:12:05	# [[ ehxBET =~ e ]]
00:01:12.250    22:12:05	# args=("${BASH_ARGV[@]}")
00:01:12.250    22:12:05	# local args
00:01:12.251    22:12:05	# xtrace_disable
00:01:12.251    22:12:05	# '[' no '!=' yes ']'
00:01:12.251    22:12:05	# PREV_BASH_OPTS=ehxBET
00:01:12.251    22:12:05	# [[ ehxBET == *\x* ]]
00:01:12.251    22:12:05	# XTRACE_DISABLED=yes
00:01:12.251    22:12:05	# set +x

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23779.html

**Comment by mkenguva** [comment]
Hi 
Instance at https://ci.spdk.io/results/autotest-per-patch/builds/23784/archive/nvme-phy-autotest/build.log
SPDK CI recognizes 1532 as invalid . can someone confirm why i have received such comment on this log?

Thanks

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_23788.html

**Comment by changpe1** [comment]
[Bug Scrub] it's same with #1522 , so closing this issue for now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_24479.html
