### ISSUE TITLE
nvme_ctrlr_destruct() takes too long time when remote target is out of communication  

### ISSUE THREAD

**Issue by cyx-cathy** [spdk/spdk#1536]
When remote target is out of communication  ( target is down or remote node's network is unavailable)   nvme_ctrlr_destruct(struct spdk_nvme_ctrlr *ctrlr) will spend too long time on below piece of code
	if (ctrlr->opts.no_shn_notification) {
		SPDK_INFOLOG(SPDK_LOG_NVME, "Disable SSD: %s without shutdown notification\n",
			     ctrlr->trid.traddr);
		nvme_ctrlr_disable(ctrlr);
	} else {
		nvme_ctrlr_shutdown(ctrlr);
	}

Is it safe to add a flag to skip above code?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
When the remote  target isn't available, is it stuck at one of the above functions?

**Comment by cyx-cathy** [comment]
yes, it stuck at nvme_ctrlr_get_cc( ) which is called by both nvme_ctrlr_disable( ) and nvme_ctrlr_shutdown( )

**Comment by cyx-cathy** [comment]
we do some test based on SPDK V20.01, here is the result:
RDMA   connect retry count | NVME_RDMA_TIME_OUT_IN_MS | NVME_RDMA_QPAIR_CM_EVENT_TIMEOUT_US | Runtime    for nvme_ctrlr_get_cc()
-- | -- | -- | --
7 (Default) | 2000(Default) | 1000000 (Default) | 33 [sec] 198639 [usec]
7 (Default) | 20 | 1000000 (Default) | 34 [sec] 108872 [usec]
7 (Default) | 2000(Default) | 10000 | 32 [sec] 918902 [usec]
4 | 2000(Default) | 1000000 (Default) | 19 [sec] 779127 [usec]
0 | 2000(Default) | 1000000 (Default) | 3 [sec] 422706 [usec]

**Comment by cyx-cathy** [comment]
Also try on SPDK V20.07, here is the result:


RDMA   connect retry count | NVME_RDMA_TIME_OUT_IN_MS | NVME_RDMA_QPAIR_CM_EVENT_TIMEOUT_US | runtime  for nvme_ctrlr_get_cc()
-- | -- | -- | --
7 (Default) | 2000(Default) | 1000000 (Default) | 21 [sec] 376037 [usec]
7 (Default) | 20 | 1000000 (Default) | 21 [sec] 519722 [usec]
7 (Default) | 2000(Default) | 10000 | 19 [sec] 804296 [usec]

**Comment by changpe1** [comment]
[Bug Scrub] @AlekseyMarchuk Could you take a look of this issue?

**Comment by AlekseyMarchuk** [comment]
@cyx-cathy could you try to set `spdk_nvme_ctrlr_opts::transport_ack_timeout` to some non-zero value? I would recommend to try different values to find one that meets your needs. This value can be set in `probe_cb` passed to `spdk_nvme_probe` function.
I did some rough measurements with this parameter, they are described in #1124

**Comment by tomzawadzki** [comment]
Closing the since `transport_ack_timeout` can be configured to help with reaching the expected timeout.
@cyx-cathy please feel free to re-open if there is more to be done to address this issue.
