### ISSUE TITLE
[crypto-autotest] timeouts

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#1538]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/23824/archive/crypto-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/23828/archive/crypto-autotest/build.log

## Execution failed at

Not always the same log, sometimes it fails at the end when doing lcov, sometimes it fails earlier on.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23828.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23824.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23837.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_23919.html

**Comment by tomzawadzki** [comment]
Even on passing crypto-autotest job seems overloaded. Addition of spdk_dd tests lasting 6+ minutes took it over the 15min timeout mark on some CI runs. See [this ](https://ci.spdk.io/results/autotest-per-patch/builds/23914/archive/crypto-autotest/timing.svg) example from build that did not time out.

@Maciej-Szwed Can you please see if spdk_dd tests require such length to cover the required use cases ?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_24077.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_24081.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Seth5141. log: https://ci.spdk.io/public_build/autotest-per-patch_24230.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_24234.html

**Comment by peluse** [comment]
Proposed fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/3740

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_24356.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_23889.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_24582.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_24586.html

**Comment by tomzawadzki** [comment]
Series of patches ending in https://review.spdk.io/gerrit/c/spdk/spdk/+/3843 were merged.
They reduce time of spdk_dd tests from 6 to 3 minutes. This issue should no longer be occurring for patches that rebase on top of the latest SPDK.

Leaving open for 7 days, to let everyone rebase. If no new reports after rebase are seen, issue will be closed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25191.html
