### ISSUE TITLE
spdk_app_get_core_mask() - doc should include a warning that modifying the set returned will modify the framework

### ISSUE THREAD

**Issue by nufosmatic** [spdk/spdk#1541]
spdk_app_get_core_mask() - doc should include a warning that modifying the set returned will modify the framework.

## Expected Behavior

I probably expect too much.

## Current Behavior

Example: if you call spdk_setcpu_and(spdk_app_get_core_mask(), other), subsequent calls to spdk_app_get_core_mask() will return the modified CPU mask.

## Possible Solution

1) Doc should warn that the cpu set returned under the pointer should not be modified - recommend allocating a new spdk_cpuset and using spdk_cpuset_copy().
2) API should return a "const" type to at least elicit a warning to the unwary.

## Steps to Reproduce

```
  uint32_t core = 2;
  struct spdk_cpuset
    *appP = spdk_app_get_core_mask(),
    *coreP = spdk_cpuset_alloc();
  fprintf(stderr, "from API  cpumask=0x%s\n", spdk_cpuset_fmt(appP));
  spdk_cpuset_set_cpu(coreP, core, true);
  spdk_cpuset_and(appP, coreP);
  fprintf(stderr, "after AND cpumask=0x%s\n", spdk_cpuset_fmt(appP));
  appP = spdk_app_get_core_mask();
  fprintf(stderr, "from API  cpumask=0x%s\n", spdk_cpuset_fmt(appP));

$ sudo ./framework -m 0xf --json bdev_NVMex4.json -b NVMe0n1
framework.c:402:main(): 166705: main() done
Starting SPDK v20.04.1 git sha1 c5f0959 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: framework --no-shconf -c 0xf --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid166705 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 4
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 2
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 3
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
framework.c:320:frameworkStart(): 166705: frameworkStart() called
from API  cpumask=0xf
after AND cpumask=0x4
from API  cpumask=0x4

```

## Context (Environment including OS version, SPDK version, etc.)

CentOS 7.5 SPDK 20.04.1

**Comment by changpe1** [comment]
[Bug Scrub] Ben will take a look.

**Comment by benlwalker** [comment]
We should mark the return value as const as suggested.

**Comment by changpe1** [comment]
I submitted a fix patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4306.

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4306 fixing this issue was merged.
