### ISSUE TITLE
pkgdep.sh does not complete successfully on RHEL 8.x

### ISSUE THREAD

**Issue by mkirkconnell** [spdk/spdk#1542]
##Summary
Running pkgdep.sh on recently released RHEL 8 doesn't complete successfully. Looks like current checks in rhel.sh is for rhel7 only which is causing different commands to be executed resulting in failure

$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"

## Expected Behavior
Running pkgdep.sh should complete without errors

## Current Behavior
$ scripts/pkgdep.sh
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Last metadata expiration check: 0:05:06 ago on Mon 10 Aug 2020 08:28:22 PM EDT.
Package gcc-8.3.1-4.5.el8.x86_64 is already installed.
Package gcc-c++-8.3.1-4.5.el8.x86_64 is already installed.
Package make-1:4.2.1-9.el8.x86_64 is already installed.
Package CUnit-devel-2.1.3-17.el8.x86_64 is already installed.
Package libaio-devel-0.3.112-1.el8.x86_64 is already installed.
Package openssl-devel-1:1.1.1c-2.el8.x86_64 is already installed.
Package libuuid-devel-2.32.1-17.el8.x86_64 is already installed.
Package libiscsi-devel-1.18.0-8.module+el8.1.0+4066+0f1aadab.x86_64 is already installed.
Package ncurses-devel-6.1-7.20180224.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Last metadata expiration check: 0:05:07 ago on Mon 10 Aug 2020 08:28:22 PM EDT.
No match for argument: python   <<<<<<
There are following alternatives for "python": python2, python36
Error: Unable to find a match: python
Error!

## Possible Solution

The checks in rhel.sh should check against rhel8 too.

## Steps to Reproduce
1. On a RHEL 8 system, download SPDK and corresponding submodules.
2. run sudo ./scripts/pkgdep.sh 

## Context (Environment including OS version, SPDK version, etc.)
cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"

SPDK version: 20.07 or later

**Comment by jimharris** [comment]
@wawryk @mikeBashStuff would one of you have time to take a look at this one?

**Comment by mikeBashStuff** [comment]
@jimharris Sure, will look into this.

**Comment by mikeBashStuff** [comment]
Fixing this can be a bit problematic since we don't have any actual RHEL boxes in the CI pool, so the support here is really a "best effort" thing. I fetched 8.2 image under a dev licence but I am getting some wonky results with plenty of packages missing from the repos I got available under my subscription. So for instance, I am missing the `CUnit-devel` package, but from the description of the issue it seems like it's already installed on the affected system (even though it doesn't seem to be registered?). 

With the above in mind, @mkirkconnell would you kindly share what repos your system is actually using? Is it using something other than the standard `appstream` and `baseos` repos?

Nevertheless, the issue from the description can be fixed with simple patch:
```
diff --git a/scripts/pkgdep/rhel.sh b/scripts/pkgdep/rhel.sh
index 6d861dc9a..c093f4fcc 100755
--- a/scripts/pkgdep/rhel.sh
+++ b/scripts/pkgdep/rhel.sh
@@ -8,7 +8,7 @@ if echo "$ID $VERSION_ID" | grep -E -q 'centos 8'; then
 fi
 yum install -y gcc gcc-c++ make CUnit-devel libaio-devel openssl-devel \
        libuuid-devel libiscsi-devel ncurses-devel
-if echo "$ID $VERSION_ID" | grep -E -q 'centos 8'; then
+if echo "$ID $VERSION_ID" | grep -E -q 'centos 8|rhel 8'; then
        yum install -y python36
        #Create hard link to use in SPDK as python
        ln -sf /etc/alternatives/python3 /usr/bin/python || true
```
But this doesn't guarantee that `pkgdep.sh` won't fail on other steps (e.g., on my rhel box, all dev tools are missing and some other like nasm).

**Comment by mkirkconnell** [comment]
Yes I tripped over CUnit-devel and nasm, had to locate repos online as they are not included in base OS.

This is my repo for them:

[ol8_codeready_builder]
name=Oracle Linux 8 Repositories - Codeready Builder
baseurl=http://yum.oracle.com/repo/OracleLinux/OL8/codeready/builder/x86_64
enable=1
gpgcheck=0

**Comment by mikeBashStuff** [comment]
@mkirkconnell Appreciate the feedback, thank you :) I will take that and try to cook some more patches for rhel 8.x so we know for sure `pkgdep,sh` won't suddenly fail there.

**Comment by tomzawadzki** [comment]
[Bug scrub] @mkirkconnell There were series of fixes for RHEL done by @mikeBashStuff on latest SPDK. Could you try and see if this resolves the issues you've been seeing ?

**Comment by mkirkconnell** [comment]
Latest SPDK gets much further, past the python install issue. Thank you!

First tripped over this:

/opt/spdk/scripts/pkgdep/rhel.sh: line 51: yum-config-manager: command not found
Error!

May want to document yum-utils as a Prerequisite here(?):
https://github.com/spdk/spdk

Next hitting error because we do not have Subscription Management. Not all users do.

Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
This system has no repositories available through subscriptions.
Error!

Is this a requirement for SPDK pkgdep.sh?

**Comment by mikeBashStuff** [comment]
@mkirkconnell Appreciate your feedback!

We actually do install `yum-utils`, but for `centos8` only. The reason why I didn't include this particular package for `rhel8` was that I actually had `yum-config-manager` already installed on my freshly rhel VM I managed to deploy- I reckoned it's shipped by default, yet it seems to be not the case. This one should be an easy fix though. :)

As to the SM thing, this was the main reason behind e989faa936. :) I was working on the VM which I also decided to register since these rhel{7,8} repos are needed in order to get most of the dependencies covered. I wouldn't want to remove this step, instead what can do is to simply avoid triggering `errexit` upon failing while trying to enable these repos. This will prevent `pkgdep.sh` from failing but also won't guarantee all the packages are going to be installed. The sad reality is that default `centos|rhel` repos simply don't provide all the packages we need (and I think we need to avoid situations where we compensate by installing separate .rpms or adding bunch of 3rd party repos just get everything installed on the box).

**Comment by mkirkconnell** [comment]
I think users can figure out the yum-config-manager thing, if not already installed :)

For the SM issue, could you possibly list out the packages that were not able to be installed due to missing SM subscription? That way users can manually find and install?

**Comment by mikeBashStuff** [comment]
@mkirkconnell Sure, I will try to compile similar list as soon as possible. :)

**Comment by mikeBashStuff** [comment]
@mkirkconnell Apologies for the late reply, I have been occupied by other tasks.

Now, it seems that without the subscription, and if you don't rely on any other 3rd-party repos, you won't be able to install most of the packages. I tested it against clean kvm image I got from the `access.redhat` and with only these repos enabled:

```
elrepo                                                                                     ELRepo.org Community Enterprise Linux Repository - el8
elrepo-testing                                                                             ELRepo.org Community Enterprise Linux Testing Repository - el8
epel                                                                                       Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                                                               Extra Packages for Enterprise Linux Modular 8 - x86_64
```
`pkgdep.sh` fails at the very beginning while trying to install core packages like `gcc, make`, etc. I tried to see if `rhel` disables any repos which are outside of the `redhat.repo` through some plugins of theirs (like `subscription-manager.conf`) but that doesn't seem to be the case, at least not by default. Only when I subscribed and attached to subscription(s) I got available for my account (it's under standard developer license which anyone can get I recon) the repos from `redhat.repo` were finally enabled. In particular, `rhel-8-for-x86_64-appstream-rpms, rhel-8-for-x86_64-baseos-rpms` (without subscribing, attempt to enable these repos manually via `subscription-manager` simply fails) - with these in place, I managed to fully provision my VM with `pkgdep.sh`. 

Also, just to note, two simple fixes addressing issues with failing `subscription-manager` and missing `yum-utils` were already merged so you can try run `pkgdep.sh` again to see if you can get any further. :)

**Comment by tomzawadzki** [comment]
> Also, just to note, two simple fixes addressing issues with failing subscription-manager and missing yum-utils were already merged so you can try run pkgdep.sh again to see if you can get any further. :)

[Bug scrub] @mkirkconnell Can you please see if suggestion from @mikeBashStuff works for you ?

**Comment by mkirkconnell** [comment]
I did a clean RHEL 8.1 install, configured yum repos, installed git, and cloned latest spdk. Verified commit id f883d5a7 was there, and ran scripts/pkgdep.sh.... It works!! The script installed everything cleanly. Thank you so much!

**Comment by tomzawadzki** [comment]
@mikeBashStuff Thanks for resolving this issue !

**Comment by tkekan** [comment]
I just downloaded the latest spdk 
i.e. Date:   Fri Oct 18 11:44:11 2024 +0800

And I'm hitting this same issue Can someone share what is the workaround for this ? 
```
 ./scripts/pkgdep.sh
Last metadata expiration check: 14:53:22 ago on Tue Oct 22 08:16:53 2024.
Package gcc-8.5.0-22.0.1.el8_10.aarch64 is already installed.
Package gcc-c++-8.5.0-22.0.1.el8_10.aarch64 is already installed.
Package make-1:4.2.1-11.el8.aarch64 is already installed.
Package CUnit-devel-2.1.3-17.el8.aarch64 is already installed.
Package libaio-devel-0.3.112-1.el8.aarch64 is already installed.
Package openssl-devel-1:1.1.1g-15.el8_3.aarch64 is already installed.
Package libuuid-devel-2.32.1-46.0.1.el8.aarch64 is already installed.
Package libiscsi-devel-1.18.0-8.module+el8.9.0+90052+d3bf71d8.aarch64 is already installed.
Package ncurses-devel-6.1-10.20180224.el8.aarch64 is already installed.
Package json-c-devel-0.13.1-3.el8.aarch64 is already installed.
Package libcmocka-devel-1.1.5-1.el8.aarch64 is already installed.
Package clang-17.0.6-1.0.1.module+el8.10.0+90411+e344f03e.aarch64 is already installed.
Package clang-devel-17.0.6-1.0.1.module+el8.10.0+90411+e344f03e.aarch64 is already installed.
Package python3-pip-9.0.3-24.el8.noarch is already installed.
Package unzip-6.0-46.0.1.el8.aarch64 is already installed.
Package keyutils-1.5.10-9.0.1.el8.aarch64 is already installed.
Package keyutils-libs-devel-1.5.10-9.0.1.el8.aarch64 is already installed.
Package fuse3-devel-3.3.0-19.0.1.el8.aarch64 is already installed.
Package patchelf-0.12-1.el8.aarch64 is already installed.
Package pkgconf-pkg-config-1.4.2-1.el8.aarch64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Looking in indexes: https://artifactory.oci.oraclecorp.com/api/pypi/global-release-pypi/simple
Requirement already satisfied: scikit-build in /usr/local/lib/python3.6/site-packages (0.16.7)
Requirement already satisfied: typing-extensions>=3.7 in /usr/lib/python3.6/site-packages (from scikit-build) (4.1.1)
Requirement already satisfied: distro in /usr/local/lib/python3.6/site-packages (from scikit-build) (1.9.0)
Requirement already satisfied: setuptools>=42.0.0 in /usr/lib/python3.6/site-packages (from scikit-build) (44.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from scikit-build) (21.3)
Requirement already satisfied: wheel>=0.32.0 in /usr/lib/python3.6/site-packages (from scikit-build) (0.37.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->scikit-build) (3.1.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Last metadata expiration check: 14:53:24 ago on Tue Oct 22 08:16:53 2024.
No match for argument: python
There are following alternatives for "python": python2, python3.11, python3.12, python36, python38, python39
Package python36-devel-3.6.8-39.module+el8.10.0+90274+07ba55de.aarch64 is already installed.
Error: Unable to find a match: python
```
