### ISSUE TITLE
spdk_nvme_ctrlr_create_ns fails on devices that support NVMe version 1.3 and above

### ISSUE THREAD

**Issue by kumaran-coder** [spdk/spdk#1551]
Namespace creation fails on NVMe devices that support version 1.3 and above.

## Expected Behavior

Namespace creation should succeed. spdk_nvme_ctrlr_create_ns should return the newly created namespace id.

## Current Behavior
nvme_ctrlr_identify_id_desc is called in the context of creating a new namespace (spdk_nvme_ctrlr_create_ns), nvme_ctrlr_identify_id_desc tries to get the Namespace Identification Descriptor list (CNS 03h) but it will fail because the newly created namespace is still inactive (not yet attached to the controller) and the NVMe spec 1.4 says that  Namespace Identification Descriptor list (CNS 03h) will fail with "INVALID FIELD" if the namespace specified in the command is inactive.

## Possible Solution
Do not call nvme_ctrlr_identify_id_desc in the namespace creation path.

## Steps to Reproduce
NVMe Management Options
	[1: list controllers]
	[2: create namespace]
	[3: delete namespace]
	[4: attach namespace to controller]
	[5: detach namespace from controller]
	[6: format namespace or controller]
	[7: firmware update]
	[8: opal]
	[9: quit]
2
0000:af:00.00 MZWLJ3T8HBLS-000GG                       S5L0NYZM9A0026          65
Please Input PCI Address(domain:bus:dev.func):
0000:af:00.00

Supported LBA formats:
 0: 512 data bytes
 1: 512 data bytes + 8 metadata bytes
 2: 4096 data bytes
 3: 4096 data bytes + 8 metadata bytes
 4: 4096 data bytes + 16 metadata bytes
 5: 4096 data bytes + 64 metadata bytes
Please input LBA format index (0 - 5):
2
Please Input Namespace Size (in LBAs):
4194304
Please Input Namespace Capacity (in LBAs):
4194304
Please Input Data Protection Type (0 - 3):
0
Please Input Multi-path IO and Sharing Capabilities (1: Share; 0: Private):
0
third_party/spdk/lib/nvme/nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:1 cdw10:00000003 cdw11:00000000
third_party/spdk/lib/nvme/nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0011 p:1 m:0 dnr:0
third_party/spdk/lib/nvme/nvme_ns.c: 161:nvme_ctrlr_identify_id_desc: *WARNING*: Failed to retrieve NS ID Descriptor List
ns manage: Failed

## Context (Environment including OS version, SPDK version, etc.)
SPDK v19.10 / DPDK 19.08.2
Linux OS running 4.15

**Comment by Comphix** [comment]
@liang2yan , please check whether we have the SSD with NVMe 1.3 and have a try on this case.

**Comment by kumaran-coder** [comment]
Yes, it is NVMe 1.3
Output from SPDK identity example

Controller Capabilities/Features
================================
...
NVMe Specification Version (VS):       1.3
NVMe Specification Version (Identify): 1.3
...

**Comment by changpe1** [comment]
Yeah, the issue does exist, I submit a fix https://review.spdk.io/gerrit/c/spdk/spdk/+/3860 here

**Comment by changpe1** [comment]
Patch has been merged, so closing this issue now.
