### ISSUE TITLE
Performance of random read tested by db_bench with SPDK is much worse than which with kernel device driver(KDD)

### ISSUE THREAD

**Issue by YafeiWangAlice** [spdk/spdk#1555]
As SPDK instructions, I think the performance of RocksDB with spdk should be better than which with KDD. 
And in some case it is better, such as fillseq,overwrite. readseq is similar at least.
But the readrandom is much worse than KDD.

Below is my test result about **readrandom**:
   1) latency(micros/op)
        KDD               0.547	
        spdk18.04      16.33	       
        spdk20.01      22.425	
	
   2) IOPS(ops/sec)
          KDD              1828592	     
          spdk18.04     61251
          spdk20.01     44592	
  3) BW(MB/s)
          KDD              1771.8	
          spdk18.04      59.3	
          spdk20.01      43.2

From the test result, we can see KDD is better more than 30 times than SPDK.
  
After many test include change the test server and linux os, the big gap between SPDK and KDD is still there.
Is this an issue of SPDK? or blobfs?

My test environment:
OS: ubuntu18.04(kernel 4.15.0)
Mem : 256G
Rocksdb version:5.14.3
db_bench parameters:
                    --disable_seek_compaction=1
--mmap_read=0
--statistics=1
--histogram=1
--key_size=16
--value_size=1000
--block_size=4096
--cache_size=0
--bloom_bits=10
--cache_numshardbits=4
--open_files=500000
--verify_checksum=1
--db=/mnt/rocksdb
--sync=0
--compression_type=none
--stats_interval=1000000
--compression_ratio=1
--disable_data_sync=0
--target_file_size_base=67108864
--max_write_buffer_number=3
--max_bytes_for_level_multiplier=10
--max_background_compactions=10
--num_levels=10
--delete_obsolete_files_period_micros=3000000
--max_grandparent_overlap_factor=10
--stats_per_interval=1
--max_bytes_for_level_base=10485760
--benchmarks=readrandom
--threads=16
--duration=60
--disable_wal=1
--use_existing_db=1
--num=20000000
--spdk=/home/66/20.01/spdk/test/blobfs/rocksdb/rocksdb.conf
--spdk_bdev=Nvme0n1
--spdk_cache_size=4096

**Comment by jimharris** [comment]
Hi @YafeiWangAlice,

If I am reading your configuration correctly, you have 20M entries (--num=20000000) and value size of 1000 bytes.  This means total database is approximately 20GB in size.  This means the entire database will fit in kernel page cache.

The SPDK RocksDB plugin cannot utilize the kernel page cache.  It will buffer writes and do read ahead to improve compaction performance.  But for random read workloads, almost all values will need to be read from disk.

I would expect to see much closer performance between kernel and SPDK when the working set is much larger than the system memory.  SPDK will still trail a bit though due to lack of page cache.  You should also see SPDK perform better when there is an insert component to the workload, rather than purely random reads.

Regards,

Jim

**Comment by YafeiWangAlice** [comment]
Hi, @jimharris 
I retest it with a bigger data number, and the result is as you said.

**Comment by jimharris** [comment]
Thanks for the update @YafeiWangAlice.

I'm going to close this issue since the behavior you have seen is expected.  If you have additional questions on this issue, please feel free to continue responding here.

**Comment by chenxu14** [comment]
The same thing happened in my randread test
```
--disable_seek_compaction=1
--mmap_read=0
--statistics=1
--histogram=1
--key_size=16
--value_size=1000
--block_size=4096
--cache_size=0
--bloom_bits=10
--cache_numshardbits=4
--open_files=500000
--verify_checksum=1
--db=/data13/rocksdb
--sync=0
--compression_type=none
--stats_interval=1000000
--compression_ratio=1
--disable_data_sync=0
--target_file_size_base=67108864
--max_write_buffer_number=3
--max_bytes_for_level_multiplier=10
--max_background_compactions=10
--num_levels=10
--delete_obsolete_files_period_micros=3000000
--max_grandparent_overlap_factor=10
--stats_per_interval=1
--max_bytes_for_level_base=10485760
--benchmarks=readrandom
--threads=16
--duration=300
--disable_wal=1
--use_existing_db=1
--num=1000000000
--spdk=/home/chenxu14/spdk/test/blobfs/rocksdb/rocksdb.conf
--spdk_bdev=Nvme0n1
--spdk_cache_size=4096
```
The maximum memory usage is limited to 10g through cgroup，test result as below
![image](https://user-images.githubusercontent.com/47170471/94136423-813d0c80-fe97-11ea-9ad6-6232b1aa8ced.png)
The long tail delay increases obviously.
