### ISSUE TITLE
Application termination with lots of threads results in "thread <threadname> is marked as exited" and a hang.

### ISSUE THREAD

**Issue by nufosmatic** [spdk/spdk#1556]
Application termination with lots of threads results in "thread <threadname> is marked as exited" and a hang. 
We scaled our simple framework from one NVMe device to four. With one device or two devices the framework terminates nicely (implemented with the shutdown_cb per https://github.com/spdk/spdk/issues/1539. With three or four devices we will frequently get this message:

[2020-08-18 16:12:15.573318] thread.c: 838:spdk_thread_send_msg: *ERROR*: Thread writer is marked as exited.

The application will also fail to terminate, and must killed with prejudicewith <control-/>

## Expected Behavior

We would expect the application to terminate nicely all of the time ;-).

## Current Behavior

As described.

## Possible Solution

This looks like a race condition between the message being serviced and the shutdown methods being called in shutdown_cb.  

## Steps to Reproduce

Unfortunately, this work product is a bit too far along to share. It will take some time to scrub it. This looks to happen whether we have a single core or multiple cores assigned to threads.

## Context (Environment including OS version, SPDK version, etc.)

CentOS 7.5 SPDK 20.07 or 20.04.1

**Comment by ak-gh** [comment]
On Tue, Aug 18, 2020, 23:36 NUFOSMATIC <notifications@github.com> wrote:

> Application termination with lots of threads results in "thread is marked
> as exited" and a hang.
> We scaled our simple framework from one NVMe device to four. With one
> device or two devices the framework terminates nicely (implemented with the
> shutdown_cb per #1539 <https://github.com/spdk/spdk/issues/1539>. With
> three or four devices we will frequently get this message:
>
> [2020-08-18 16:12:15.573318] thread.c: 838:spdk_thread_send_msg: *ERROR*:
> Thread writer is marked as exited.
>

You might want to spend some time on your threading logic. The above
message tells you that the thread the message is being sent to has already
called spdk_thread_exit (so the message has no valid addressee). BTW,
spdk_thread_send_msg returns a code worth checking.

Regards,
Andrey

**Comment by nufosmatic** [comment]
We renamed the four bdev "writer" threads to include the launch order in the name. No matter what order we launch, the same physical device exhibits this message. So we have some sort of device issue, not a middleware issue. We are not seeing a performance issue between devices (spdk_top is very nice, thank you).  Th e prototype type case runs all of the devices at the same rate and block size and there is no "drift" between the four devices.

**Comment by jimharris** [comment]
Hi @nufosmatic,

Can you describe more about your shutdown callback and where you are calling spdk_thread_exit() for your four "writer" threads?

Thanks,

Jim

**Comment by jimharris** [comment]
Closing issue.  @nufosmatic feel free to reopen if you're able to provide more information.  Thanks.
