### ISSUE TITLE
Does SPDK support VF(sriov ) ?

### ISSUE THREAD

**Issue by punkie44** [spdk/spdk#1558]
## Expected Behavior

Using SRIOV supported NVME SSD, make 1 VF and run perf tool then it should be run without any issue.

## Current Behavior
For PF it runs well while VF is failed.

## Steps to Reproduce

1. using sriov, make VF (nvme1)
2. attach namespace on VF (nvme1n1)
3. run setup.sh in spdk/scripts directory. (it makes 2 vfio-pci (e.g.>0000:03:00.0 , 0000:03:00.1))
4. run perf tool in spdk/example/nvme/perf
   --> for PF(0000:03:00.0) works fine but, for VF(0000:03:00.1) is not working with below error log
  nvme_pcie.c: 856:nvme_pcie_ctrlr_construct: *ERROR*: get_cap() failed
  nvme.c: 484:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD : 0000:03:00.1
## Context (Environment including OS version, SPDK version, etc.)

Centos7 kernel 4.1518 / SPDK 19.04

**Comment by jimharris** [comment]
Hi,

SPDK should work fine with VFs.  But you may need to keep the PF attached to the kernel nvme driver and only run SPDK with the VF.

Could you try:

PCI_BLACKLIST="0000:03:00.0" setup.sh 

This will keep the PF attached to the kernel nvme driver, and allow any VFs to get attached to vfio-pci for SPDK usage.

**Comment by punkie44** [comment]
Hi Jim,
Thank you for your advice.
Now I can run perf tool on VF.

BTW,  Is it a constraint of SPDK that it is impossible to use VF and PF at the same time?
If my SSD supports 1 PF and 7 VF, and also supports 8 namespace.
I want to attach a namespace to a total of 8 controllers and give IO to each side.
Howerver, if PF should be in the kernel space, I can use only 7 controllers. 
Am I correct ?

**Comment by jimharris** [comment]
Hi @punkie44,

When the PF is bound to vfio-pci, do you see a /sys/bus/pci/devices/<0000:03:00.0>/sriov_numvfs entry?  If so, what is the value when you cat that file?

-Jim

**Comment by punkie44** [comment]
in this condition....
1.using sriov, make VF (nvme1)
2.attach namespace on VF (nvme1n1)
3.run setup.sh in spdk/scripts directory. (it makes 2 vfio-pci (e.g.>0000:03:00.0 , 0000:03:00.1))
---> I can see " /sys/bus/pci/devices/<0000:03:00.0>/sriov_numvfs" and the value is 1.

**Comment by jimharris** [comment]
Thanks @punkie44.  When you run the nvme perf tool, do you run it on both SSDs at the same time, or just one at a time?

**Comment by punkie44** [comment]
@jimharris, maybe you or me....mis-understand something....

As I said I can't run perf tool on VF if PF & VF all are bound to vfio-pci
-----------------------------------------------------------------------------------
3.run setup.sh in spdk/scripts directory. (it makes 2 vfio-pci (e.g.>0000:03:00.0 , 0000:03:00.1))
4.run perf tool in spdk/example/nvme/perf
 --> for PF(0000:03:00.0) works fine but, for VF(0000:03:00.1) is not working with below error log
 nvme_pcie.c: 856:nvme_pcie_ctrlr_construct: ERROR: get_cap() failed
 nvme.c: 484:nvme_ctrlr_probe: ERROR: Failed to construct NVMe controller for SSD : 0000:03:00.1
------------------------------------------------------------------------------------------------------------
So you recommended to use "PCI_BLACKLIST" in order to make PF keep in kernel space.
Then I can run perf tool on VF but I can't run this tool on PF (Because PF is in kernel space)
So I don't understand why you ask this..
----------------------------------------------------
 When you run the nvme perf tool, do you run it on both SSDs at the same time, or just one at a time?
----------------------------------------------------
I can run perf tool on VF or PF, can't run VF and PF at the same time.
I can run 2 VF (if I make 2 VF) at the same time but still can't run PF(due to "PCI_BLACKLIST )

**Comment by punkie44** [comment]
@jimharris , I got it.
Here is my answer.
"You are testing one SSD at a time by specifying the transport ID parameters for each"
--> Yes
"or testing both SSDs together by omitting those parameters entirely"
--> If I omit a transport ID,  Perf tool can't find both PF and VF.

Anyway, I've got correct answer how to run spdk for VF.(using PCI_BLACKLIST)
So, I close this issue.
Thanks,

**Comment by Mr-Chengcheng** [comment]
hello  , I also use sriov. i have two vf with PCI_ALLOWED,  but  when i execute "bdev_nvme_attach_controller" with second vf, it will fail , the log is show "bdev_nvme_check_secondary_trid: *ERROR*: PCIe failover is not supported."
