### ISSUE TITLE
[vagrant] - Hit timeout while waiting for ssh during ubuntu18-vg-autotest

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1561]
https://ci.spdk.io/results/autotest-per-patch/builds/24659/archive/ubuntu18-vg-autotest/build.log

Point of failure:
```
00:01:17.927  An error occurred in the underlying SSH library that Vagrant uses.
00:01:17.927  The error message is shown below. In many cases, errors from this
00:01:17.927  library are caused by ssh-agent issues. Try disabling your SSH
00:01:17.927  agent or removing some keys and try again.
00:01:17.927  
00:01:17.927  If the problem persists, please report a bug to the net-ssh project.
00:01:17.927  
00:01:17.927  Net::SSH::ConnectionTimeout
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_24659.html

**Comment by tomzawadzki** [comment]
[Bug scrub] This issue has not occurred for over a month on CI. Closing it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98829.html
