### ISSUE TITLE
[Clearlinux] blob_ut: No such file or directory

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1562]
## Expected Behavior
Test pass

## Current Behavior
Test fail

## Context (Environment including OS version, SPDK version, etc.)
Test fails on: 
```
./test/unit/unittest.sh: line 29: /home/vagrant/spdk_repo/spdk/test/unit/lib/blob/blob.c/blob_ut: No such file or directory
```

During compilation there is warning: 
```
13:31:17 Makefile:41: "blob_ut.c compilation skipped, only CUnit version 2.1-3 is supported"
```
When I checked CUnit version:
```
clear@clearlinux~ $ echo "#include <CUnit/CUnit.h>" | gcc -E -dM - | sed -n -e 's/.*VERSION "\([0-9\.\-]*\).*/\1/p'
2.1-3
```

Example failure from our CI: [here](https://10.102.17.111:8080/job/clearlinux-autotest/3/console)
Kernel:
```
Linux clearlinux 5.4.33-31.lts2019 #1 SMP Fri Apr 17 03:03:03 PDT 2020 x86_64 GNU/Linux
```
gcc:
```
gcc version 9.3.1 20200420 releases/gcc-9.3.0-156-g47ea8616d4 (Clear Linux OS for Intel Architecture)
```

**Comment by tomzawadzki** [comment]
Please see patch resolving this on clearlinux:
https://review.spdk.io/gerrit/c/spdk/spdk/+/4240
