### ISSUE TITLE
question regarding keep alive to ssd

### ISSUE THREAD

**Issue by eyuval** [spdk/spdk#1565]
I am looking at the function nvme_ctrlr_set_keep_alive_timeout_done in lib/nvme/nvme_ctrlr.c. For me it is strange, that a zero value of the cdw0 (kato) of the nvme completion seems not to disable keep alive but instead is replace by:
if (keep_alive_interval_ms == 0) {
		keep_alive_interval_ms = 1;
	}

**Comment by changpe1** [comment]
> I am looking at the function nvme_ctrlr_set_keep_alive_timeout_done in lib/nvme/nvme_ctrlr.c. For me it is strange, that a zero value of the cdw0 (kato) of the nvme completion seems not to disable keep alive but instead is replace by:
> if (keep_alive_interval_ms == 0) {
> keep_alive_interval_ms = 1;
> }

keep alive is expressed via millisecond, so spdk will use timer / 2 as the interval poller to send keep alive command, when the timeout value was set to 1 millisecond, we will use 1 ms as the interval poller in SPDK.

I think the may cause issue in practice, for this case it's better to use 500 us as the interval timer.

**Comment by changpe1** [comment]
[Bug Scrub] it's two bugs here, if the target return 0, we can just skip it, if returned 1, we can use microsecond as the interval unit.

**Comment by eyuval** [comment]
My original intention was, that if the ssd tells us a zero kato value we should respect this and not do any keep alives as if we had received a zero kas value in the identify structure.

**Comment by changpe1** [comment]
> My original intention was, that if the ssd tells us a zero kato value we should respect this and not do any keep alives as if we had received a zero kas value in the identify structure.

Keep alive was mainly used for NVMf target, for local PCIe based SSDs, I assume most of the physical SSDs will return 0 for kato, for this case SPDK will not enter the keep alive process.

**Comment by benlwalker** [comment]
Yes - if KATO is 0 we shouldn't be sending any keep alives. But there's also a bug if KATO is 1ms (which is an unreasonable but valid value). We need to fix both.

The bug only occurs when someone tries to enable keep alive on a local SSD. If you just don't try to enable it on a local SSD SPDK won't send keep-alives.

**Comment by tomzawadzki** [comment]
[Bug scrub] Patch https://github.com/spdk/spdk/commit/ba773a54c769b2a4bee0ef08895659cb4fc9388e was merged, if this addresses this issue - please close it.
