### ISSUE TITLE
nvme/rdma: Memory leak when controller is reset

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1567]
There seems to be a memory leak when an NVME initiator using RDMA is continuously resetting the controller while the target is restarting.
The call to spdk_nvme_ctrlr_reset is happening fairly often. 

The trace clearly shows that we're exhausting the qpair->free_req list:
```
reset ctrlr failed: rc=-1
IO completion error: rc=-6
IO reconnection error: rc=-6
[2020-08-24 08:05:58.338982] nvme_internal.h: 967:nvme_allocate_request: *NOTICE*: !!! mhae: nvme_allocate_request req=(nil)
adm completion error: rc=-6
[2020-08-24 08:05:58.339020] nvme_ctrlr.c:1209:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
[2020-08-24 08:05:58.382444] nvme_internal.h: 967:nvme_allocate_request: *NOTICE*: !!! mhae: nvme_allocate_request req=(nil)
[2020-08-24 08:05:58.382464] nvme_fabric.c: 457:nvme_fabric_qpair_connect: *ERROR*: Connect command failed (1), rc=-12
[2020-08-24 08:05:58.382492] nvme_rdma.c:1363:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command, rc=-12
[2020-08-24 08:05:58.389056] nvme_ctrlr.c:1224:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
[2020-08-24 08:05:58.389078] nvme_ctrlr.c: 799:nvme_ctrlr_fail: *ERROR*: ctrlr 192.168.0.1 in failed state.
```

The following code is processing IOs and adm cmds and also deals with connection issues:
```
~~~      
      int32_t rc = spdk_nvme_qpair_process_completions(dev->qpair, 0);
      if (rc < 0) {
        printf("IO completion error: rc=%d\n", rc);
        if (rc == -ENXIO) {
          rc = spdk_nvme_ctrlr_reconnect_io_qpair(dev->qpair);
          if (rc) {
            printf("IO reconnection error: rc=%d\n", rc);
          }
        }
      }
      rc = spdk_nvme_ctrlr_process_admin_completions(dev->ctrlr);
      if (rc < 0) {
        printf("adm completion error: rc=%d\n", rc);
        if (rc == -ENXIO) {
          rc = spdk_nvme_ctrlr_reset(dev->ctrlr);
          if (rc) {
            printf("reset ctrlr failed: rc=%d\n", rc);
          }
        }
      }
    }
~~~
``` 

## Expected Behavior

No memory leak.

## Possible Solution

The code below handles an ENXIO and frees the request. This seems to fix the issue but I'm not really comfortable submitting this change.
```
nvme_qpair.c:
nvme_qpair_submit_request:
~~~
        rc = _nvme_qpair_submit_request(qpair, req);
	if (rc == -EAGAIN) {
		STAILQ_INSERT_TAIL(&qpair->queued_req, req, stailq);
		req->queued = true;
		rc = 0;
	} else if (rc == -ENXIO) {
		SPDK_NOTICELOG("!!! mhae: nvme_qpair_submit_request failed; free request\n");
		nvme_free_request(req);
	}
~~~
```

## Steps to Reproduce
- NVMF target and basic initiator that uses above code for completion checking in the main thread (I'm using my own code that's pretty much perf with stuff from the reconnect example).
- Target and initiator are running on 2 different systems over RDMA
- Restarting the app a **couple** of times results in the memory leak in the initiator

## Context (Environment including OS version, SPDK version, etc.)
CentOS8, Almost top of tree

**Comment by Seth5141** [comment]
@mhae You are absolutely right. Thanks for finding this. The change that adds the -ENXIO path to _nvme_qpair_submit_request was added about a month ago (I think in time for 20.07). I have implemented the fix that you mentioned above. https://review.spdk.io/gerrit/c/spdk/spdk/+/3921. We should also backport it for 20.07.

**Comment by changpe1** [comment]
patch was merged, closing this issue for now.
