### ISSUE TITLE
util/cpuset: spdk_cpuset_parse cannot parse core_mask if masked core num over 128

### ISSUE THREAD

**Issue by fishman419** [spdk/spdk#1570]
we have a 256-core experimental machine, and use last several cores to do polling, but we found spdk_cpuset_parse didn't work in this case.

## Expected Behavior
spdk_cpuset_parse does work, masked core should be set in the spdk_cpuset which can tell correct masked core.

## Current Behavior
masked core num over 128 cannot be parsed.

## Possible Solution
it seems the statement in function **parse_mask** has a mistake
```
...
for (j = 0; j < 4 && lcore < sizeof(set->cpus); j++, lcore++) {
  if ((1 << j) & val) {
    spdk_cpuset_set_cpu(set, lcore, true);
  }
}
...
```
`lcore < sizeof(set->cpus)` -> `lcore < sizeof(set->cpus) * 8` ?
## Steps to Reproduce
here is the example code, core_used should not be zero :

```
...
struct spdk_cpuset *cpuset = spdk_cpuset_alloc();
if (spdk_cpuset_parse(cpuset, "0xf000000000000000000000000000000000000000000000000000000000000000")) {
  return -1;
}
uint32_t core_used = spdk_cpuset_count(cpuset);
assert(core_used != 0);
...
```

## Context (Environment including OS version, SPDK version, etc.)
spdk v19.04(but the same code in latest version)

**Comment by jimharris** [comment]
Patch including unit test here:  https://review.spdk.io/gerrit/c/spdk/spdk/+/3931
