### ISSUE TITLE
SPDK vs DPDK main branch compilation fail

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1573]
## Current Behavior

SPDK compilation fails when building versus latest DPDK main branch.
This issue was discovered using a patch which is still not merged, so may not fully apply to SPDK master branch.

## Steps to Reproduce

1. Use SPDK with following patch for building with external DPDK: https://review.spdk.io/gerrit/c/spdk/spdk/+/868/4
2. Use following ~/autorun-spdk.conf:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_BLOBFS=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
RUN_NIGHTLY=0
SPDK_TEST_NATIVE_DPDK=main
SPDK_RUN_EXTERNAL_DPDK=/tmp/spdk/dpdk/build
```
3. Run spdk/autorun.sh

Full error log is quite long, so attaching them as files.
[lvol-autotest-build.log](https://github.com/spdk/spdk/files/5124225/lvol-autotest-build.log)
[blobfs-autotest-build.log](https://github.com/spdk/spdk/files/5124226/blobfs-autotest-build.log)

## Context (Environment including OS version, SPDK version, etc.)
Linux fedora31.localdomain 5.6.11-200.fc31.x86_64 #1 SMP Wed May 6 19:10:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
SPDK: https://review.spdk.io/gerrit/c/spdk/spdk/+/868/4
DPDK: b9b10ddb4 (HEAD -> main, origin/main) switch default git branch name to main

**Comment by karlatec** [comment]
Similar errors encountered also when trying to build versus DPDK 20.08

**Comment by AlekseyMarchuk** [comment]
`00:04:15.915  make[2]: *** No rule to make target '/tmp/spdk/dpdk/build/lib/librte_eal.so', needed by '/home/vagrant/spdk_repo/spdk/build/bin/spdk_trace'.  Stop.`

I believe that means that librte_eal.so was not found and we expect that DPDK is already compiled. I tried to use external DPDK, it works fine (when I compiled DPDK before SPDK)

**Comment by jimharris** [comment]
This 868 patch seems to be using the old DPDK make system.  Maybe that's supposed to still work, but I'd suggest changing it to use the meson/ninja build system.

Alexey reported separately that he can compile latest SPDK against external DPDK without any problem.

@karlatec - could you debug this test patch further - maybe update it to use meson/ninja build system and see if the problem persists?

**Comment by tomzawadzki** [comment]
[Bug scrub] There is no compilation issue with latest DPDK right now. @karlatec is working on updating patch https://review.spdk.io/gerrit/c/spdk/spdk/+/868/ to use meson-ninja.

**Comment by tomzawadzki** [comment]
[Bug scrub] Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/868/ was merged, enabling building 'vs_dpdk' jobs on nightly basis. @karlatec will enable the jobs and report any new issues with DPDK compatibility that might come up.
