### ISSUE TITLE
NVMe-OF target on RDMA transport hang when using ctrl+c to shutdown

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1578]
The NVMe-OF target on RDMA transport can shutdown correctly if with ctrl+c from users. 

It hangs in nvmf_rdma_destroy_drained_qpair  on the following statements:

 if (rqpair->srq == NULL && rqpair->current_recv_depth != rqpair->max_queue_depth) {
                return;
        }

## Possible Solution

https://review.spdk.io/gerrit/c/spdk/spdk/+/3936 //This patch can solve the issue, may not be perfect as mentioned by Alex

## Steps to Reproduce

1.  Compile SPDK nvme-oF target (./configure --with-rdma --enable-debug; make). Using the following command and conf configuration to start NVMe-oF target: 

rdma.conf 
---
[Global]

[Bdev]

[Malloc]
  NumberOfLuns 8
  LunSizeInMB 64

[Nvmf]
  AcceptorPollRate 10000

[Transport]
  Type rdma
  NoSRQ Yes
  InCapsuleDataSize 4096
  NumSharedBuffers 2048
[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.7.55:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  #Namespace Nvme0n1 1
  Namespace Malloc0
---

./build/bin/nvmf_tgt  -c rdma_local_test.conf -m 0x10000

2. In another machine or the same host, run the following command:  ./build/examples/perf -q 128 -w randrw -t 50 -o 4096 -M 50 -r 'trtype:rdma adrfam:ipv4 traddr:192.168.7.55 trsvcid:4420' 
3.  Do not wait for the completion of the perf program, during the test, use ctrl+c to kill the nvme-of target
4. Then you will see hang for the NVMe-oF target

## Context (Environment including OS version, SPDK version, etc.)

OS: Fedora 30 with 5.6 kernel
SPDK: commit 2b16cfff9e56ebe5da4f850e26af4ba60dfe54aa  (Actually you can use the master branch)

**Comment by optimistyzy** [comment]
Another approach to fix the non SRQ case, may be: https://review.spdk.io/gerrit/c/spdk/spdk/+/3960

**Comment by AlekseyMarchuk** [comment]
I think that the problem is not in RDMA transport. When we are exiting SPDK target, we stop pg poller too early so we can't reap all RDMA completions and RDMA qpair is not deleted. But at the same time RDMA qpair holds io_channel of poll group, so the poll group can't be removed as well and we get a hang. I prepared a patch to test is through CI where I stop pg's poller when we are ready to destroy poll group https://review.spdk.io/gerrit/c/spdk/spdk/+/3962.

**Comment by optimistyzy** [comment]
@AlekseyMarchuk Thanks Alex, This is the right fix. Thanks for your efforts.
