### ISSUE TITLE
Add GPT support for metadata

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1580]
## Current Behavior

When creating a bdev with metadata enabled (as in, for example #1577) GPT complains about lack of support for provided block size (which includes metadata size)

## Steps to Reproduce

1. sudo scripts/rpc.py bdev_null_create Null0 100 4224 -t 1 -m 128
```
[2020-08-27 08:28:10.161091] vbdev_gpt.c: 552:vbdev_gpt_examine: *ERROR*: GPT module does not support block size 4224 for bdev Null0

Null0
```
2. Bdev is created successfully anyways
```
[
  {
    "name": "Null0",
    "aliases": [],
    "product_name": "Null disk",
    "block_size": 4224,
    "num_blocks": 24824,
    "uuid": "294e677a-3ec9-46e6-88fb-00dd0c8ee3cb",
    "md_size": 128,
    "md_interleave": true,
    "dif_type": 1,
    "dif_is_head_of_md": false,
    "enabled_dif_check_types": {
      "reftag": true,
      "apptag": false,
      "guard": true
    },
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": false,
      "write_zeroes": true,
      "flush": false,
      "reset": true,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {}
  }
]
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK b5fd1f8
Fedora 32 5.7.8-200.fc32.x86_64
gcc version 10.1.1

**Comment by karlatec** [comment]
@shuhei-matsumoto you asked to create this as separate issue, so assigning you. Feel free to re-assign!

**Comment by changpe1** [comment]
[Bug Scrub] We will not support GPT with extended LBA format, so this can be a debug log.

**Comment by shuhei-matsumoto** [comment]
I posted a patch to change ERRLOG to DEBUGLOG.
https://review.spdk.io/gerrit/c/spdk/spdk/+/4058
