### ISSUE TITLE
DPDK 20.08 VirtioSCSI device never ends up in ready state

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1583]
Using DPDK 20.08 with latest SPDK results in VirtioScsi device finishing in ready state. This is exposed in `json_config` test where only RPC is sent to configure the device, without any traffic actually going through.

Going through DPDK commits between 20.05 and 20.08, https://github.com/DPDK/dpdk/commit/d0fcc38f5fa41778968b6f39777a61edb3aef813 is one that introduces this behavior.

## Expected Behavior

00:02:54.995   09:46:06	# initiator_rpc bdev_virtio_attach_controller -t user -a /var/tmp/VhostScsiCtrlr0 -d scsi VirtioScsiCtrlr0
00:02:54.995   09:46:06	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_initiator.sock bdev_virtio_attach_controller -t user -a /var/tmp/VhostScsiCtrlr0 -d scsi VirtioScsiCtrlr0
00:02:55.136  VHOST_CONFIG: new vhost user connection is 525
00:02:55.136  VHOST_CONFIG: new device, handle is 0
00:02:55.136  VHOST_CONFIG: read message VHOST_USER_SET_OWNER
00:02:55.136  VHOST_CONFIG: read message VHOST_USER_GET_FEATURES
00:02:55.136  VHOST_CONFIG: read message VHOST_USER_SET_FEATURES
00:02:55.136  VHOST_CONFIG: negotiated Virtio features: 0x140000003
00:02:55.136  VHOST_CONFIG: read message VHOST_USER_GET_PROTOCOL_FEATURES
00:02:55.136  VHOST_CONFIG: read message VHOST_USER_SET_PROTOCOL_FEATURES
00:02:55.136  VHOST_CONFIG: negotiated Vhost-user protocol features: 0x1
00:02:55.136  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
00:02:55.136  VHOST_CONFIG: set queue enable: 0 to qp idx: 0
00:02:55.136  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
00:02:55.137  VHOST_CONFIG: set queue enable: 0 to qp idx: 1
00:02:55.137  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
00:02:55.137  VHOST_CONFIG: set queue enable: 0 to qp idx: 2
00:02:55.137  VHOST_CONFIG: read message VHOST_USER_GET_QUEUE_NUM
00:02:55.138  VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
00:02:55.138  VHOST_CONFIG: vring call idx:0 file:536
00:02:55.138  VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
00:02:55.138  VHOST_CONFIG: vring call idx:1 file:537
00:02:55.138  VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
00:02:55.138  VHOST_CONFIG: vring call idx:2 file:538
00:02:55.140  VHOST_CONFIG: read message VHOST_USER_SET_MEM_TABLE
00:02:55.140  VHOST_CONFIG: guest memory region 0, size: 0x40000000
00:02:55.140  	 guest physical addr: 0x200000200000
00:02:55.140  	 guest virtual  addr: 0x200000200000
00:02:55.140  	 host  virtual  addr: 0x7f0dc0000000
00:02:55.140  	 mmap addr : 0x7f0dc0000000
00:02:55.140  	 mmap size : 0x40000000
00:02:55.140  	 mmap align: 0x200000
00:02:55.140  	 mmap off  : 0x0
00:02:55.140  VHOST_CONFIG: read message VHOST_USER_GET_FEATURES
00:02:55.148  VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
00:02:55.148  VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
00:02:55.148  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
00:02:55.148  VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
00:02:55.148  VHOST_CONFIG: vring kick idx:0 file:540
00:02:55.161  VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
00:02:55.162  VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
00:02:55.162  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
00:02:55.162  VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
00:02:55.162  VHOST_CONFIG: vring kick idx:1 file:541
00:02:55.162  VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
00:02:55.162  VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
00:02:55.162  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
00:02:55.162  VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
00:02:55.162  VHOST_CONFIG: vring kick idx:2 file:542
**00:02:55.162  VHOST_CONFIG: virtio is now ready for processing.**
00:02:55.172  VirtioScsiCtrlr0t0 VirtioScsiCtrlr0t1

## Current Behavior
See patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/3865
log output:
https://ci.spdk.io/results/autotest-per-patch/builds/24715/archive/vhost-initiator-vg-autotest/build.log

00:03:04.451   11:05:14	# initiator_rpc bdev_virtio_attach_controller -t user -a /var/tmp/VhostScsiCtrlr0 -d scsi VirtioScsiCtrlr0
00:03:04.451   11:05:14	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_initiator.sock bdev_virtio_attach_controller -t user -a /var/tmp/VhostScsiCtrlr0 -d scsi VirtioScsiCtrlr0
00:03:04.596  VHOST_CONFIG: new vhost user connection is 525
00:03:04.596  VHOST_CONFIG: new device, handle is 0
00:03:04.596  VHOST_CONFIG: read message VHOST_USER_SET_OWNER
00:03:04.596  VHOST_CONFIG: read message VHOST_USER_GET_FEATURES
00:03:04.596  VHOST_CONFIG: read message VHOST_USER_SET_FEATURES
00:03:04.596  VHOST_CONFIG: negotiated Virtio features: 0x140000003
00:03:04.596  VHOST_CONFIG: read message VHOST_USER_GET_PROTOCOL_FEATURES
00:03:04.596  VHOST_CONFIG: read message VHOST_USER_SET_PROTOCOL_FEATURES
00:03:04.596  VHOST_CONFIG: negotiated Vhost-user protocol features: 0x1
00:03:04.596  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
00:03:04.597  VHOST_CONFIG: set queue enable: 0 to qp idx: 0
00:03:04.597  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
00:03:04.597  VHOST_CONFIG: set queue enable: 0 to qp idx: 1
00:03:04.597  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
00:03:04.597  VHOST_CONFIG: set queue enable: 0 to qp idx: 2
00:03:04.597  VHOST_CONFIG: read message VHOST_USER_GET_QUEUE_NUM
00:03:04.598  VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
00:03:04.598  VHOST_CONFIG: vring call idx:0 file:536
00:03:04.598  VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
00:03:04.598  VHOST_CONFIG: vring call idx:1 file:537
00:03:04.598  VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
00:03:04.598  VHOST_CONFIG: vring call idx:2 file:538
00:03:04.600  VHOST_CONFIG: read message VHOST_USER_SET_MEM_TABLE
00:03:04.600  VHOST_CONFIG: guest memory region 0, size: 0x40000000
00:03:04.600  	 guest physical addr: 0x200000200000
00:03:04.600  	 guest virtual  addr: 0x200000200000
00:03:04.600  	 host  virtual  addr: 0x7f3504000000
00:03:04.600  	 mmap addr : 0x7f3504000000
00:03:04.600  	 mmap size : 0x40000000
00:03:04.600  	 mmap align: 0x200000
00:03:04.600  	 mmap off  : 0x0
00:03:04.600  VHOST_CONFIG: read message VHOST_USER_GET_FEATURES
00:03:04.610  VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
00:03:04.610  VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
00:03:04.610  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
00:03:04.610  VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
00:03:04.610  VHOST_CONFIG: vring kick idx:0 file:540
00:03:04.621  VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
00:03:04.623  VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
00:03:04.623  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
00:03:04.623  VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
00:03:04.623  VHOST_CONFIG: vring kick idx:1 file:541
00:03:04.623  VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
00:03:04.623  VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
00:03:04.623  VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
00:03:04.623  VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
00:03:04.623  VHOST_CONFIG: vring kick idx:2 file:542
**00:04:04.656  Timeout while waiting for response:**

## Possible Solution

Fix on DPDK for patch https://github.com/DPDK/dpdk/commit/d0fcc38f5fa41778968b6f39777a61edb3aef813 or adjusting SPDK behavior to accommodate it.

## Steps to Reproduce

Besides running full CI suite, a simpler way to reproduce it to call:
`sudo SPDK_TEST_VHOST=1 SPDK_TEST_VHOST_INIT=1 ./test/json_config/json_config.sh --iso`

**Comment by tomzawadzki** [comment]
Hi @changpe1 , would mind take a look at this issue ?

**Comment by changpe1** [comment]
> Hi @changpe1 , would mind take a look at this issue ?

I submitted a fix patch for SPDK https://review.spdk.io/gerrit/c/spdk/spdk/+/3989 at here, and you must use --vq-count with a number bigger than 1 for virtio_blk(virtio_scsi will use 3 vrings), I think this should be fixed in DPDK, so there is another DPDK related patch coming.

**Comment by tomzawadzki** [comment]
> you must use --vq-count with a number bigger than 1 for virtio_blk(virtio_scsi will use 3 vrings)

The `json_config` test passes for virtio_blk without passing any `--vq-count` argument.
Meanwhile specifying 4 virtqueues for virtio_scsi does not seem to workaround the issue, please see patch (and submodule update next in series):
https://review.spdk.io/gerrit/c/spdk/spdk/+/4001/

**Comment by changpe1** [comment]
A patch for DPDK submitted at https://patches.dpdk.org/patch/76197

**Comment by tomzawadzki** [comment]
[Bug scrub] @tomzawadzki will push the DPDK patch  https://patches.dpdk.org/patch/76197 to spdk/dpdk submodule.

**Comment by tomzawadzki** [comment]
Patch ready on spdk/dpdk fork:
https://review.spdk.io/gerrit/c/spdk/dpdk/+/4219

**Comment by tomzawadzki** [comment]
Hi @changpe1 I've backported the patch to spdk/dpdk fork. It seems to affect the VM boot, see in vhost_boot in vhost-autotest and nvmf_vhost in nvmf-phy-autotest.
https://ci.spdk.io/public_build/autotest-per-patch_26060.html

Specific example from the above log [vhost_boot]:
```
00:02:27.731  VHOST_CONFIG: vring call idx:3 file:207
00:03:40.341  ...WARN: timeout waiting for machines to boot
00:07:29.850  WARN: ================
00:07:29.850  WARN: QEMU LOG:
....
00:07:29.856  [  240.267374] INFO: task kworker/u4:3:68 blocked for more than 120 seconds.
00:07:29.856  [  240.268652]       Not tainted 4.4.0-83-generic #106-Ubuntu
00:07:29.856  [  240.269649] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
00:07:29.856  [  240.271068] kworker/u4:3    D ffff8800373dfc48     0    68      2 0x00000000
00:07:29.856  [  240.272430] Workqueue: scsi_tmf_2 scmd_eh_abort_handler
00:07:29.856  [  240.273402]  ffff8800373dfc48 0000000000000003 ffffffff81e11500 ffff880037385400
00:07:29.856  [  240.274821]  ffff8800373e0000 ffff8800373dfd80 ffff8800373dfd78 ffff880037385400
00:07:29.856  [  240.276264]  0000000000002003 ffff8800373dfc60 ffffffff8183ca55 7fffffffffffffff
00:07:29.856  [  240.277701] Call Trace:
00:07:29.856  [  240.278174]  [<ffffffff8183ca55>] schedule+0x35/0x80
00:07:29.856  [  240.279075]  [<ffffffff8183fba5>] schedule_timeout+0x1b5/0x270
00:07:29.856  [  240.280160]  [<ffffffffc0033477>] ? virtscsi_add_cmd+0x177/0x290 [virtio_scsi]
00:07:29.856  [  240.281487]  [<ffffffff810cb001>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
00:07:29.856  [  240.282930]  [<ffffffff8183d4b3>] wait_for_completion+0xb3/0x140
00:07:29.856  [  240.284050]  [<ffffffff810ac5e0>] ? wake_up_q+0x70/0x70
00:07:29.856  [  240.284999]  [<ffffffffc00338e5>] virtscsi_tmf.constprop.12+0xa5/0x110 [virtio_scsi]
00:07:29.856  [  240.286408]  [<ffffffffc00341db>] virtscsi_abort+0xbb/0xc0 [virtio_scsi]
00:07:29.856  [  240.287628]  [<ffffffff815c2024>] scmd_eh_abort_handler+0x74/0x270
00:07:29.856  [  240.288774]  [<ffffffff8109a585>] process_one_work+0x165/0x480
00:07:29.856  [  240.289832]  [<ffffffff8109a8eb>] worker_thread+0x4b/0x4c0
00:07:29.856  [  240.290854]  [<ffffffff8109a8a0>] ? process_one_work+0x480/0x480
00:07:29.856  [  240.291972]  [<ffffffff810a0c25>] kthread+0xe5/0x100
00:07:29.856  [  240.292877]  [<ffffffff810a0b40>] ? kthread_create_on_node+0x1e0/0x1e0
00:07:29.856  [  240.294064]  [<ffffffff81840f0f>] ret_from_fork+0x3f/0x70
00:07:29.856  [  240.295034]  [<ffffffff810a0b40>] ? kthread_create_on_node+0x1e0/0x1e0
00:07:29.856  [  240.296234] INFO: task systemd-udevd:112 blocked for more than 120 seconds.
00:07:29.856  [  240.297483]       Not tainted 4.4.0-83-generic #106-Ubuntu
00:07:29.856  [  240.298470] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
00:07:29.856  [  240.299903] systemd-udevd   D ffff880035577c88     0   112    110 0x00000004
00:07:29.856  [  240.301224]  ffff880035577c88 0000000000000000 ffff8800354c8e00 ffff880035510e00
00:07:29.856  [  240.302673]  ffff880035578000 0000000000000000 ffff88003aef6fa0 ffffffffc0036400
00:07:29.856  [  240.304111]  ffff88003bcc10c0 ffff880035577ca0 ffffffff8183ca55 ffffffffffffffff
00:07:29.856  [  240.305536] Call Trace:
00:07:29.856  [  240.305992]  [<ffffffff8183ca55>] schedule+0x35/0x80
00:07:29.856  [  240.306905]  [<ffffffff810a379e>] async_synchronize_cookie_domain+0x6e/0x150
00:07:29.856  [  240.308193]  [<ffffffff810c4330>] ? wake_atomic_t_function+0x60/0x60
00:07:29.856  [  240.309348]  [<ffffffff810a38b7>] async_synchronize_full+0x17/0x20
00:07:29.856  [  240.310483]  [<ffffffff8118dde5>] do_init_module+0xc1/0x1cf
00:07:29.856  [  240.311515]  [<ffffffff8110aaaf>] load_module+0x166f/0x1c10
00:07:29.856  [  240.312539]  [<ffffffff81107050>] ? __symbol_put+0x60/0x60
00:07:29.856  [  240.313537]  [<ffffffff81215140>] ? kernel_read+0x50/0x80
00:07:29.856  [  240.314519]  [<ffffffff8110b294>] SYSC_finit_module+0xb4/0xe0
00:07:29.856  [  240.315570]  [<ffffffff8110b2de>] SyS_finit_module+0xe/0x10
00:07:29.856  [  240.316591]  [<ffffffff81840b72>] entry_SYSCALL_64_fastpath+0x16/0x71
```

**Comment by changpe1** [comment]
I will try to reproduce this issue in my local environment.

**Comment by changpe1** [comment]
@tomzawadzki I reproduced this issue with the DPDK change, it failed with virtio-scsi, but worked with virtio-blk.

Maxime sent another workaround, I will try that patch.

**Comment by changpe1** [comment]
Seabios can't work with SPDK vhost for a long time, I just realized this, it's not critical, but SPDK used to support this feature.

**Comment by changpe1** [comment]
@tomzawadzki The dpdk patch is still outside out git repository, but the tests can pass now, what did you do for this issue?

**Comment by tomzawadzki** [comment]
Following patch was merged in the meantime https://review.spdk.io/gerrit/c/spdk/spdk/+/4001/ to allow update to DPDK 20.08.
This will be now reverted, since now submodule patch was merged.

**Comment by changpe1** [comment]
> Following patch was merged in the meantime https://review.spdk.io/gerrit/c/spdk/spdk/+/4001/ to allow update to DPDK 20.08.
> This will be now reverted, since now submodule patch was merged.

Ah, I remembered this patch.

**Comment by tomzawadzki** [comment]
This issue can be closed after patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4783/ is merged
