### ISSUE TITLE
"Write failed" running ftl.sh in spdk v19.07 with spdk-3.0.0

### ISSUE THREAD

**Issue by john4477** [spdk/spdk#1584]
Write failed when running spdk/test/ftl/ftl.sh in spdk v19.07 with spdk-3.0.0

## Expected Behavior

write to ftl_bdev successfully

## Current Behavior

Write failed at ppa

```C
/home/yohan/test/spdk_v19.07/test/bdev/bdevperf/bdevperf -c /home/yohan/test/spdk_v19.07/test/ftl/config/ftl.conf -q 128 -w verify -t 4 -o 4096
Warning: printing stderr to console terminal without -q option specified.
Suggest using --silence-noticelog to disable logging to stderr and
monitor syslog, or redirect stderr to a file.
(Delaying for 10 seconds...)
Starting SPDK v19.07.1 / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid10823 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
app.c: 627:spdk_app_start: NOTICE: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: NOTICE: Reactor started on core 0
Running I/O for 4 seconds...
nand_rule: previous page state(W) is not (W) for ppa(0x000000000000000f)
lnvm_rwc: set written + meta status failed with psl[0] = ppa: ch(0), lun(0), blk(0), pg(1), pl(0), sec(0)
nvme_qpair.c: 137:nvme_io_qpair_print_command: NOTICE: WRITE sqid:1 cid:190 nsid:1 lba:16 len:16
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: NOTICE: ABORTED - MISSING FUSED (00/0a) sqid:1 cid:190 cdw0:ffff sqhd:0009 p:1 m:0 dnr:1
ftl_io.c: 502:ftl_io_process_error: ERROR: Status code type 0x0, status code 0xa for IO type 1 @ppa: (grp: 0, pu: 0, chk: 0, lbk: 16), lba 0xffffffffffffffff, cnt 16
ftl_core.c:1309:ftl_write_fail: ERROR: Write failed @ppa: (grp: 0, pu: 0, chk: 0, lbk: 16), status: -5
nand_rule: previous page state(W) is not (W) for ppa(0x000000000200800f)
lnvm_rwc: set written + meta status failed with psl[0] = ppa: ch(0), lun(2), blk(1), pg(1), pl(0), sec(0)
nvme_qpair.c: 137:nvme_io_qpair_print_command: NOTICE: WRITE sqid:1 cid:188 nsid:1 lba:33587216 len:16
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: NOTICE: ABORTED - MISSING FUSED (00/0a) sqid:1 cid:188 cdw0:ffff sqhd:0015 p:1 m:0 dnr:1
ftl_io.c: 502:ftl_io_process_error: ERROR: Status code type 0x0, status code 0xa for IO type 1 @ppa: (grp: 0, pu: 2, chk: 1, lbk: 16), lba 0xffffffffffffffff, cnt 16
ftl_core.c:1309:ftl_write_fail: ERROR: Write failed @ppa: (grp: 0, pu: 2, chk: 1, lbk: 16), status: -5
Logical core: 0
nvme0 : 85182.00 IO/s 332.74 MB/s
Total : 85182.00 IO/s 332.74 MB/s
```
full output file : 
[bug.txt](https://github.com/spdk/spdk/files/5149429/bug.txt)

## Possible Solution

changes the message below error to correct one?

nand_rule: previous page state(W) is not (W) for ppa(0x000000000200800f)

## Steps to Reproduce

1. install spdk-3.0.0
git clone https://github.com/spdk/qemu.git
git checkout origin/spdk-3.0.0
git submodule update --init
cd qemu
mkdir build
cd build
../configure --target-list=x86_64-softmmu --python=/usr/bin/python2.7
make
make install

2. install spdk v19.07 on qemu
./x86_64-softmmu/qemu-system-x86_64
-hda /home/yohan/etc/images/ubuntu.img
-m 16384 -smp 4 -cpu host --enable-kvm
-kernel /home/yohan/etc/images/bzImage
-net user,hostfwd=tcp::3000-:22
-net nic,model=virtio
-nographic
-drive format=raw,file=/home/yohan/etc/images/myocssd-datafile,if=none,id=myocssd
-device nvme,drive=myocssd,serial=deadbeef,lba_index=3,lver=2,lnum_ch=1,lnum_lun=8,lnum_pln=4,lblks_per_pln=512,lpgs_per_blk=1536,lsecs_per_pg=4,metadata=/home/yohan/etc/images/myocssd-datafile
-append 'root=/dev/sda1 rw console=ttyS0 nokaslr'

git clone https://github.com/spdk/spdk
git checkout v19.07.x
git submodule update --init

3. run ftl.sh
cd spdk
sudo ./test/ftl/ftl.sh

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 18.04.5 LTS , spdk-3.0.0, spdk_v19.07

**Comment by changpe1** [comment]
[Bug Scrub] @tomzawadzki could you find the right person who can take a look? thanks.

**Comment by tomzawadzki** [comment]
@john4477 Have you had a chance to check out if this reproduces on latest SPDK v20.07 or SPDK v20.01.2 LTS ?

**Comment by john4477** [comment]
@tomzawadzki 
On SPDK v20.07, it shows

* Purging old temporary test storage (/tmp/spdk.YS55IT)
* Looking for test storage...
* Test storage is not available


On spdk v20.01.x
it shows the same errors like below files
[v20.01.output.txt](https://github.com/spdk/spdk/files/5193582/v20.01.output.txt)
[v20.01.output2.txt](https://github.com/spdk/spdk/files/5193583/v20.01.output2.txt)

**Comment by john4477** [comment]
#1593 shows the same error
