### ISSUE TITLE
Discovery command behaviour.

### ISSUE THREAD

**Issue by senthilkumar-v** [spdk/spdk#1586]
Setup Details:-
============

I've configured SPDK target as below:-

# 1) Example subsystem configuration :-  cat ./etc/spdk/nvmf.conf.in

Namespaces backed by physical NVMe devices

[Subsystem1]

  NQN nqn.2016-06.io.spdk:cnode1

  Listen RDMA 192.168.122.227:4420 <<<<<<<<<<< n/w 1

  AllowAnyHost Yes 

  SN SPDK00000000000001

  MN SPDK_Controller1

  Namespace Nvme0n1 1

[Subsystem2]

  NQN nqn.2016-06.io.spdk:cnode2

  Listen RDMA 192.168.123.254:4421 <<<<<<<<<<<<< n/w 2

  AllowAnyHost Yes 

  SN SPDK00000000000002

  MN SPDK_Controller2

  Namespace Nvme1n1 2

# 2) Start the target:-  

[root@vm2 ]# build/bin/nvmf_tgt -c ./etc/spdk/nvmf.conf.in

[2020-09-01 02:59:35.030163] rdma.c:2653:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.122.227 port 4420 ***

[2020-09-01 02:59:35.030268] rdma.c:2653:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.123.254 port 4421 ***

# 3) Initiator configuration :-

[root@vm1 ~]# ifconfig

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500

        inet 192.168.122.114  netmask 255.255.255.0  broadcast 192.168.122.255 <<<<<< only one n/w.

        inet6 fe80::3153:8b9b:ee23:9bf2  prefixlen 64  scopeid 0x20<link>

        inet6 fe80::b200:2d4b:3efa:4f2  prefixlen 64  scopeid 0x20<link>

        ether 52:54:00:8f:5c:d9  txqueuelen 1000  (Ethernet)

        RX packets 1976585  bytes 103720411 (98.9 MiB)

        RX errors 0  dropped 4  overruns 0  frame 0

        TX packets 172393  bytes 14385946 (13.7 MiB)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536

        inet 127.0.0.1  netmask 255.0.0.0

        inet6 ::1  prefixlen 128  scopeid 0x10<host>

        loop  txqueuelen 1000  (Local Loopback)

        RX packets 64  bytes 5184 (5.0 KiB)

        RX errors 0  dropped 0  overruns 0  frame 0

        TX packets 64  bytes 5184 (5.0 KiB)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

As you can see only one n/w is configure i.e. 192.168.123.254.

# 4) Issue discovery as below.

[root@vm1 ~]# nvme discover -t rdma -a 192.168.122.227 -s 4420

Discovery Log Number of Records 2, Generation counter 5

=====Discovery Log Entry 0======

trtype:  rdma

adrfam:  ipv4

subtype: nvme subsystem

treq:    not required

portid:  0

trsvcid: 4420

subnqn:  nqn.2016-06.io.spdk:cnode1

traddr:  192.168.122.227

rdma_prtype: not specified

rdma_qptype: connected

rdma_cms:    rdma-cm

rdma_pkey: 0x0000

=====Discovery Log Entry 1======

trtype:  rdma

adrfam:  ipv4

subtype: nvme subsystem

treq:    not required

portid:  1

trsvcid: 4421

subnqn:  nqn.2016-06.io.spdk:cnode2

traddr:  192.168.123.254

rdma_prtype: not specified

rdma_qptype: connected

rdma_cms:    rdma-cm

rdma_pkey: 0x0000

Though there is no "192.168.123.254" network configured on initiator and the discover is issued on only "192.168.122.227" but sill discovery reports nqn on "192.168.123.254" n/w also. 

## Expected Behavior

In NVMe-oF spec, section 5. Discovery Service, it says,

"The Discovery Log entries should return addresses on the same fabric as the Discovery Service."

So, I'm expecting discovery to not report NQN on 192.168.123.254 interface, in this configuration.

## Current Behavior

Though there is no "192.168.123.254" network configured on initiator and the discover is issued on only "192.168.122.227", but sill discovery reports nqn on "192.168.123.254" n/w also. 

## Possible Solution

Restrict to discovery inventory to the same IP address of discover command. In this case, "192.168.122.227" n/w alone.

## Steps to Reproduce

1. Configure proper subsystem.
2. Issue, "nvme discover -t rdma -a 192.168.122.227 -s 4420".

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.01.

**Comment by yidong0635** [comment]
This is really strange, I try to reproduce this:
`./build/bin/nvmf_tgt -c ../nvmf.conf.in`
```
[2020-09-02 01:52:31.508997] conf.c: 626:spdk_conf_read: *ERROR*: INI configuration has been deprecated and will be removed in a future release. Please switch to JSON-RPC.
Starting SPDK v20.10-pre git sha1 1e1f9b34b / DPDK 20.05.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid24430 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2020-09-02 01:52:31.589048] app.c: 666:spdk_app_start: *NOTICE*: Total cores available: 1
[2020-09-02 01:52:31.721531] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 0
[2020-09-02 01:52:31.721594] accel_engine.c: 509:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2020-09-02 01:52:31.815406] conf.c: 120:nvmf_read_config_file_tgt_conf: *NOTICE*: The ConnectionScheduler option is no longer valid. Ignoring it.
[2020-09-02 01:52:31.886093] rdma.c:2469:nvmf_rdma_create: *NOTICE*: Adjusting the io unit size to fit the device's maximum I/O size. New I/O unit size 45056
[2020-09-02 01:52:31.943094] conf.c: 351:nvmf_parse_subsystem: *NOTICE*: Subsystem nqn.2016-06.io.spdk:cnode1: missing model number, will use default
[2020-09-02 01:52:31.943361] rdma.c:2664:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.167.125.13 port 4420 ***
[2020-09-02 01:52:31.943378] conf.c: 351:nvmf_parse_subsystem: *NOTICE*: Subsystem nqn.2016-06.io.spdk:cnode2: missing model number, will use default
[2020-09-02 01:52:31.943394] rdma.c:2625:nvmf_rdma_listen: *ERROR*: rdma_bind_addr() failed
[2020-09-02 01:52:31.943406] nvmf.c: 585:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address '192.168.2.21'
[2020-09-02 01:52:31.943414] conf.c: 466:nvmf_parse_subsystem: *ERROR*: Failed to listen on transport address
[2020-09-02 01:52:31.943422] subsystem.c: 804:spdk_nvmf_subsystem_add_listener: *ERROR*: Cannot find transport listener for 192.168.2.21
[2020-09-02 01:52:31.943430] conf.c: 273:nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address

```

**Comment by senthilkumar-v** [comment]
Looks like there is no NIC with 192.168.2.21 IP on the target side (check “ifconfig -a” o/p) so it is not able to listen & BIND failed.
Please check your target n/w configuration.

Regards,
Senthil Kumar V.

**Comment by yidong0635** [comment]
@senthilkumar-v  but are your NICs are ok? why 'ifconfig' dispalys only one nic?

**Comment by senthilkumar-v** [comment]
@yidong0635 Sorry for not being more clear. I meant, target side I've configured two NICs with IPs 192.168.122.227 &  192.168.123.254 and initiator side, I've configured only one NIC with IP 192.168.122.114. 

# Target NIC config

[root@vm2 ]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.122.227  netmask 255.255.255.0  broadcast 192.168.122.255
        inet6 fe80::b200:2d4b:3efa:4f2  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:1a:49:98  txqueuelen 1000  (Ethernet)
        RX packets 468913  bytes 27236713 (25.9 MiB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 180683  bytes 12705587 (12.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.123.254  netmask 255.255.255.0  broadcast 192.168.123.255
        inet6 fe80::537f:9313:ecd9:82b6  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:12:b3:66  txqueuelen 1000  (Ethernet)
        RX packets 372176  bytes 19499252 (18.5 MiB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 1774  bytes 236600 (231.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# Initiator NIC 

[root@vm1 ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.122.114  netmask 255.255.255.0  broadcast 192.168.122.255
        inet6 fe80::3153:8b9b:ee23:9bf2  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::b200:2d4b:3efa:4f2  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:8f:5c:d9  txqueuelen 1000  (Ethernet)
        RX packets 2056392  bytes 109420685 (104.3 MiB)
        RX errors 0  dropped 4  overruns 0  frame 0
        TX packets 206906  bytes 17362256 (16.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by benlwalker** [comment]
Hi Senthil - In SPDK, an spdk_nvmf_tgt defines a discovery service. A discovery service behaves as follows according to the specification:

```The set of Discovery Log entries should include all applicable addresses on the same fabric as the Discovery Service and may include addresses on other fabrics.
```
If you want the two subsystems to appear in different discovery services, place them into separate targets. You can create targets using the `nvmf_create_tgt` RPC. Right now SPDK will list all subsystems in a target that are on the same fabric type that the host, by host NQN, is allowed to access.

I do think I understand the confusion though. You have two entirely separate networks, with one NIC connected to each, right? I don't think the SPDK NVMe-oF target has any way to know that the two NICs are on separate networks automatically - it just assumes they're all the same network. You'll need to use multiple targets to teach it that the two listeners are really for entirely independent networks.

**Comment by senthilkumar-v** [comment]
Thank you for the explanation, Ben. Really appreciate it. Just one last question,

>>You'll need to use multiple targets to teach it that the two listeners are really for entirely independent networks.

Do you mean implementing ANA at target or can you please elaborate your comment here?

**Comment by changpe1** [comment]
> Thank you for the explanation, Ben. Really appreciate it. Just one last question,
> 
> > > You'll need to use multiple targets to teach it that the two listeners are really for entirely independent networks.
> 
> Do you mean implementing ANA at target or can you please elaborate your comment here?

It's not related with ANA, here you are using two listeners with two subsystems.

**Comment by senthilkumar-v** [comment]
Thank you @changpe1. I'm closing this issue.
