### ISSUE TITLE
Not able to generate password on gerrit

### ISSUE THREAD

**Issue by rouming** [spdk/spdk#1589]
Hi folks,

I'm desperate, I want to submit a patch to spdk (I'm a new user to spdk gerrit), but https://review.spdk.io/gerrit/settings/ returns 500 error on attempt to generate a HTTP password. Whom can I ask for help? Any support email etc are welcome. Or any other possibilities to send the patch upstream bypassing gerrit?

--
Roman

**Comment by jimharris** [comment]
Hi Roman,

SPDK patches can only be submitted through Gerrit.  Can you confirm that you have configured your e-mail address on your Gerrit profile before trying to generate the HTTP password?

-Jim

**Comment by rouming** [comment]
Hi Jim,

I'm a github user, I simply followed the https://spdk.io/development/  guide, which says:

```
Gerrit Configuration
Log into Gerrit using your GitHub account credentials. Once logged in, in the top right corner click your user name and select ‘Settings’. You should set up the following:

Profile: Verify that the information is correct here.
HTTP Password: Generate a password. You’ll use this password when prompted by git (not your GitHub password!).

```

 and immediately stuck on the second line "HTTP Password", because server responds with 500 error.

**Comment by jimharris** [comment]
Yes.  Thanks @rouming.  I'm keeping this issue open for now - I'll push a patch to clarify the e-mail registration in step 1.  You are not the first person to run into this.

**Comment by rouming** [comment]
Awesome, now issue is fixed (after putting email address). Thanks, Jim.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk.github.io/+/4034

**Comment by tomzawadzki** [comment]
Patch clarifying the docs is now merged.
