### ISSUE TITLE
blob: md pages for extent tables are not getting released

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1590]
Unit test reproducing the failure: https://review.spdk.io/gerrit/c/spdk/spdk/+/4038

This unit test describes the conditions fairly well.  You just need to repeatedly create and delete a blob (with no intermediate blobstore unload/load) to hit this condition.

Found while create a benchmark application to test efficiency of allocating blobstore clusters and md_pages.

**Comment by jimharris** [comment]
Unit test ported to 20.01 LTS branch:  https://review.spdk.io/gerrit/c/spdk/spdk/+/4040

**Comment by tomzawadzki** [comment]
Patch resolving this issue posted:
https://review.spdk.io/gerrit/c/spdk/spdk/+/4051/
@jimharris Shall we backport fix and UT to LTS ?

**Comment by jimharris** [comment]
Hi Tomek,

Yes, I think we should backport this fix and UT to 20.01 branch.

-Jim
