### ISSUE TITLE
[E810]unable to connect to the rqpair when running nvmf/host/multipath.sh 

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#1595]
Unable to connect to the rqpair when running nvmf/host/multipath.sh test
## Expected Behavior
Finishing the script running successfully.

## Current Behavior
 15:23:13	# /home/qwan/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4422
 15:23:13	# sleep 5
 15:23:18	# wait 100999
Timeout while waiting for response:

  15:24:02	# trap - ERR
  15:24:02	# print_backtrace
  15:24:02	# [[ ehxBET =~ e ]]
  15:24:02	# args=("${BASH_ARGV[@]}")
  15:24:02	# local args
  15:24:02	# xtrace_disable
  15:24:02	# '[' no '!=' yes ']'
  15:24:02	# PREV_BASH_OPTS=ehxBET
  15:24:02	# [[ ehxBET == *\x* ]]
  15:24:02	# XTRACE_DISABLED=yes
  15:24:02	# set +x
========== Backtrace start: ==========

in ./test/nvmf/host/multipath.sh:62 -> main(["--iso"],["--transport=rdma"])
     ...
   57  	
   58  	sleep 3
   59  	
   60  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_THIRD_PORT
   61  	sleep 5
=> 62  	wait $rpc_pid
   63  	
   64  	killprocess $bdevperf_pid
   65  	
   66  	cat $testdir/try.txt
   67  	# if this test fails it means we didn't fail over to the second
     ...

========== Backtrace end ==========

## Possible Solution
N/A

## Steps to Reproduce

1. cd spdk
2. vim /test/nvmf/common.sh
search for function "get_rdma_if_list", change the script to running with cvl nic name
3. ./test/nvmf/host/multipath.sh --iso --transport=rdma

**Comment by changpe1** [comment]
@wanqunintel could you try again with this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4284?

**Comment by wanqunintel** [comment]
i tried with this patch, and it also failed, i checked that this only failed on CVL NIC

**Comment by wanqunintel** [comment]
And it seems when remove the listener with -s 4420, it doesn't fail, there is a dmesg info when remove the listener with -s 4421 and -s 4422
/home/qwan/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s **4421**
**[  566.169167] iwpm_add_and_query_mapping_cb: Received a Reject (pid = 2025, echo seq = 20)**
/home/qwan/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s **4422**
**[ 7800.483708] iwpm_add_and_query_mapping_cb: Received a Reject (pid = 1986, echo seq = 80)**

**Comment by yidong0635** [comment]
@wanqunintel  I can check this on your environment to see what kind of issue it is, from the log that it seems it can't opereate
from a different port?

**Comment by changpe1** [comment]
@wanqunintel is the issue still exist? if not we may close it now.

**Comment by changpe1** [comment]
closing this issue for now.
