### ISSUE TITLE
Ocssd bdev differs from the ocssd Specification v2.0.

### ISSUE THREAD

**Issue by john4477** [spdk/spdk#1598]
## Expected Behavior

when send read command on ocssd bdev, opcode should be 0x92 according to ocssd specification v2.0.

## Current Behavior

opcode is 0x02 for read command on ocssd bdev.

## Possible Solution

ocssd bdev should use spdk_nvme_ocssd_ns_cmd_vector_read_md command() to send read request not spdk_nvme_ns_cmd_readv_with_md() which is used for current ocssd bdev 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
[Bug Scrub] @wmalikow could you take a look ?

**Comment by dong-liuliu** [comment]
Located in module/bdev/nvme/bdev_ocssd.c.
I think john4477 is saying, inside bdev_ocssd.c, the read/write cmds to ocssd should use spdk_nvme_ocssd_ns_cmd_XXX series, not spdk_nvme_ns_cmd_XXX series.

**Comment by ksztyber** [comment]
These vector commands are marked as optional by the OCSSD 2.0 spec and don't have to be supported by every OCSSD compliant device, while the regular NVMe read/write (0x01, 0x02) are, of course, mandatory. It's perfectly fine for bdev_ocssd to only rely on the regular commands.
However, as an improvement, it could be extended to use vector I/O, but would have to probe the device underneath for its support first and fall back to the regular commands if the device doesn't support it.

**Comment by jimharris** [comment]
Thanks @ksztyber.

Based on your input I'm going to mark this as an enhancement request.

**Comment by jimharris** [comment]
We are not planning on any further OCSSD work within SPDK, so going to close this issue.
