### ISSUE TITLE
set_qd_sampling_period cannot persist into the json file and it does not work with iostat.py

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1599]
## Expected Behavior
below is the steps to reproduce this. 

intel@wcp116:~/wayne/warraid5/nvcache/war$ sudo scripts/rpc.py bdev_set_qd_sampling_period Malloc0 1000000
intel@wcp116:~/wayne/warraid5/nvcache/war$ sudo scripts/rpc.py save_config >  /tmp/warmallocqd.json
intel@wcp116:~/wayne/warraid5/nvcache/war$ sudo vim /tmp/warmallocqd.json 
intel@wcp116:~/wayne/warraid5/nvcache/war$ sudo scripts/rpc.py save_config | grep qd

## Steps to Reproduce

1.
2.
3.
4.

**Comment by gwnet** [comment]
more urgent thing is that even I enable qd sampling, it cannot show in iostat.py though code looks like has this feature.
```
intel@wcp116:~/wayne/warraid5/nvcache/war$ sudo scripts/rpc.py bdev_set_qd_sampling_period Malloc0 1000000
intel@wcp116:~/wayne/warraid5/nvcache/war$ sudo scripts/iostat.py -k -i 1 -t 600
cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           0.39%      0.00%      0.01%        0.00%        0.00%       99.60%   

Device   tps     KB_read/s  KB_wrtn/s  KB_dscd/s  KB_read  KB_wrtn        KB_dscd
Malloc0  297.54  0.00       1190.18    0.00       36.00    1088273384.00  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.14%      0.00%      0.00%        0.00%        0.00%       98.86%   

Device   tps         KB_read/s  KB_wrtn/s   KB_dscd/s  KB_read  KB_wrtn     KB_dscd
Malloc0  2460568.18  0.00       9842272.73  0.00       0.00     9923120.00  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.13%      0.00%      0.00%        0.00%        0.00%       98.87%   

Device   tps         KB_read/s  KB_wrtn/s   KB_dscd/s  KB_read  KB_wrtn     KB_dscd
Malloc0  2456830.58  0.00       9827322.33  0.00       0.00     9907980.00  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.14%      0.00%      0.00%        0.00%        0.00%       98.86%   

Device   tps         KB_read/s  KB_wrtn/s   KB_dscd/s  KB_read  KB_wrtn     KB_dscd
Malloc0  2459079.88  0.00       9836319.50  0.00       0.00     9917148.00  0.00   

cpu_stat:  user_stat  nice_stat  system_stat  iowait_stat  steal_stat  idle_stat
           1.14%      0.00%      0.00%        0.00%        0.00%       98.86%  
```

**Comment by Comphix** [comment]
@gwnet , what information that you would like to get in the iostat.py? To get the runtime queue depth? The bdev_set_qd_sampling_period is to set the timer poller and use another RPC bdev_get_iostat() to get the related information.

**Comment by gwnet** [comment]
@Comphix thank you so much Gang.
I already found it. the scripts/rpc.py has one command that can get the run time qd for me. just iostat.py did not put this information into output. not very critical for me now. but maybe we can add it, kernel iostat has more columns. :)

**Comment by changpe1** [comment]
@jiaqizho could you take a look if it's reasonable to add the queue depth, if not you can close this issue. thanks.

**Comment by jiaqizho** [comment]
@changpe1 
sorry for just see this issue 
queue depth can be add , i will submit a patch to enhancement iostat.

**Comment by jiaqizho** [comment]
please follow this patch set(no merge yet): https://review.spdk.io/gerrit/c/spdk/spdk/+/4847

closed this issue .

**Comment by jimharris** [comment]
Re-opening issue.  We should not close the issue until patches are merged.

**Comment by gwnet** [comment]
@jiaqizho thank you so much, buddy, I have one private branch, I will merge this patch to enable more qd dumping. 👍

**Comment by gwnet** [comment]
@jiaqizho hello man, I branch code do not have the module folder as your version did, could you please share me your suggestion how I merge your code into my repo? I see one big code structure change here.

spdk\module\bdev\rpc\bdev_rpc.c

**Comment by jimharris** [comment]
Hi @jiaqizho,

These patches above are still open with some unresolved comments.  Have you had a chance to take a look?

Thanks,

Jim

**Comment by jiaqizho** [comment]
> Hi @jiaqizho,
> 
> These patches above are still open with some unresolved comments. Have you had a chance to take a look?
> 
> Thanks,
> 
> Jim

hi jim , before i leave intel , i think @gwnet have already verified this issue.

So i will closed this issue.
