### ISSUE TITLE
can't open libspdk_nvme.so.4.0 since upgrading to SPDK version v20.07

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1600]
We upgrade SPDK version to v20.07 from previous version v20.04 and compile it to shared library files.
But an error occurred when we tried to run example hello_world :
`Error while loading shared libraries, cannot open shared object file: libspdk_nvme.so.4.0 :No such file or directory `

We check that the file libspdk_nvme.so.4.0 is indeed stored under the path build/lib,
We also run ldconfig specifying the directory containing SPDK shared libraries :
```
ldconfig -v -n ./build/lib
LD_LIBRARY_PATH=./build/lib/
```
but still can't link with library libspdk_nvme.so.4.0, can someone help clarify this problem?
 
another problem is we can't find libdpdk.so anywhere on version v20.07,
 It seems that this version will not produce libdpdk.so?
our applications can link with libdpdk.so successful when using version v20.04,
now it can’t run because it can’t find file libdpdk.so,
Please help confirm how to fix this problem, thanks!

**Comment by ryderhsu0129** [comment]
Can someone help clarify this problem?thanks!

**Comment by changpe1** [comment]
how do you upgrade your SPDK version? just checkout the v20.07 ?

**Comment by Comphix** [comment]
For the libdpdk.so, may refer to below weblink:

https://doc.dpdk.org/guides/prog_guide/build-sdk-meson.html

57.7. Using the DPDK within an Application
To compile and link against DPDK within an application, pkg-config should be used to query the correct parameters. Examples of this are given in the makefiles for the example applications included with DPDK. They demonstrate how to link either against the DPDK shared libraries, or against the static versions of the same.

From examples/helloworld/Makefile:

PC_FILE := $(shell pkg-config --path libdpdk)
CFLAGS += -O3 $(shell pkg-config --cflags libdpdk)
LDFLAGS_SHARED = $(shell pkg-config --libs libdpdk)
LDFLAGS_STATIC = $(shell pkg-config --static --libs libdpdk)

build/$(APP)-shared: $(SRCS-y) Makefile $(PC_FILE) | build
        $(CC) $(CFLAGS) $(SRCS-y) -o $@ $(LDFLAGS) $(LDFLAGS_SHARED)

build/$(APP)-static: $(SRCS-y) Makefile $(PC_FILE) | build
        $(CC) $(CFLAGS) $(SRCS-y) -o $@ $(LDFLAGS) $(LDFLAGS_STATIC)

build:
        @mkdir -p $@

**Comment by ryderhsu0129** [comment]
> how do you upgrade your SPDK version? just checkout the v20.07 ?
@changpe1 

Thanks for your reply.
Yes, we checkout to tag v20.07 and then compile it,
Is there any problem with this?

**Comment by changpe1** [comment]
> > how do you upgrade your SPDK version? just checkout the v20.07 ?
> > @changpe1
> 
> Thanks for your reply.
> Yes, we checkout to tag v20.07 and then compile it,
> Is there any problem with this?

No, this is fine, can you post your application Makefile that related to SPDK library?

**Comment by ryderhsu0129** [comment]
> > > how do you upgrade your SPDK version? just checkout the v20.07 ?
> > > @changpe1
> > 
> > 
> > Thanks for your reply.
> > Yes, we checkout to tag v20.07 and then compile it,
> > Is there any problem with this?
> 
> No, this is fine, can you post your application Makefile that related to SPDK library?

@changpe1 

The problem with not finding the library **libspdk_nvme.so.4.0** occurred in running SPDK provided example hello_world.

The problem with not finding the library **libdpdk.so** occurred in running our applications,
and the Makefile is :
```
LIBS+=-L/usr/local/lib \
 -Wl,--whole-archive,--no-as-needed \
 -lspdk \
 -ldpdk \
 -Wl,--no-whole-archive \
 -lspdk_env_dpdk \
 -lisal
}
```
We will copy SPDK compiled libraries under the path build/lib to our system path,
but we found that the libdpdk.so was not compiled under the path build/lib on v20.07.

**Comment by ryderhsu0129** [comment]
> For the libdpdk.so, may refer to below weblink:
> 
> https://doc.dpdk.org/guides/prog_guide/build-sdk-meson.html
> 
> 57.7. Using the DPDK within an Application
> To compile and link against DPDK within an application, pkg-config should be used to query the correct parameters. Examples of this are given in the makefiles for the example applications included with DPDK. They demonstrate how to link either against the DPDK shared libraries, or against the static versions of the same.
> 
> From examples/helloworld/Makefile:
> 
> PC_FILE := $(shell pkg-config --path libdpdk)
> CFLAGS += -O3 $(shell pkg-config --cflags libdpdk)
> LDFLAGS_SHARED = $(shell pkg-config --libs libdpdk)
> LDFLAGS_STATIC = $(shell pkg-config --static --libs libdpdk)
> 
> build/$(APP)-shared: $(SRCS-y) Makefile $(PC_FILE) | build
> $(CC) $(CFLAGS) $(SRCS-y) -o $@ $(LDFLAGS) $(LDFLAGS_SHARED)
> 
> build/$(APP)-static: $(SRCS-y) Makefile $(PC_FILE) | build
> $(CC) $(CFLAGS) $(SRCS-y) -o $@ $(LDFLAGS) $(LDFLAGS_STATIC)
> 
> build:
> @mkdir -p $@

@Comphix 
thanks for your reply.

We don't have to use a version of DPDK different from the submodule included in the SPDK repository,
there should be no need to do these actions? we don’t need to do additional actions in the previous version.

**Comment by changpe1** [comment]
The issue does exist, I will figure it out.

**Comment by jimharris** [comment]
I think we should break the libdpdk problem into a separate GitHub issue.  They look similar but will have two different resolutions.  @ryderhsu0129 would you mind submitting a separate issue for this?

Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported.  Or could you try:

LD_LIBRARY_PATH=./build/lib build/examples/hello_world

**Comment by jimharris** [comment]
Using pkg-config to get DPDK linker args doesn't work.  It omits the rte_bus_pci library which results in link errors against rte_pci_read/write_config and rte_pci_register.  It also specifies --as-needed which will only link functions that are "needed" meaning referenced directly.  This excludes constructor functions such as the mempool ops registration in the rte_mempool_ring library (see issue #518).

I think something pkg-config related would be the way forward, rather than SPDK building a libdpdk library itself.  @changpe1 I can take a look at this.

**Comment by jimharris** [comment]
I've sent an e-mail to dev@dpdk.org to get more clarification on this.

**Comment by ryderhsu0129** [comment]
> I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> 
> Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> 
> LD_LIBRARY_PATH=./build/lib build/examples/hello_world



> I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> 
> Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> 
> LD_LIBRARY_PATH=./build/lib build/examples/hello_world

@jimharris 

thanks for your help.

We tried to do this:
LD_LIBRARY_PATH=./build/lib build/examples/hello_world

but an error still occurred:
`Error while loading shared libraries, cannot open shared object file: librte_telemetry.so.0.200.2 :No such file or directory`

**Comment by changpe1** [comment]
> > I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> > Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> 
> > I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> > Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> 
> @jimharris
> 
> thanks for your help.
> 
> We tried to do this:
> LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> 
> but an error still occurred:
> `Error while loading shared libraries, cannot open shared object file: librte_telemetry.so.0.200.2 :No such file or directory`

could you try this LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib build/examples/hello_world ?
it works in my environment

**Comment by ryderhsu0129** [comment]
> > > I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> > > Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> > > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> > 
> > 
> > > I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> > > Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> > > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> > 
> > 
> > @jimharris
> > thanks for your help.
> > We tried to do this:
> > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> > but an error still occurred:
> > `Error while loading shared libraries, cannot open shared object file: librte_telemetry.so.0.200.2 :No such file or directory`
> 
> could you try this LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib build/examples/hello_world ?
> it works in my environment

@changpe1 

it's work 
`LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib build/examples/hello_world`

so it can be concluded that the problem is can't produce libdpdk.so?
another question is in the previous version will go to the system folder `/usr/local/lib` to find libraries,
no need to use LD_LIBRARY_PATH specify the path, 
It seems that the v20.07 needs to do this extra? thanks!

**Comment by changpe1** [comment]
> > > > I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> > > > Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> > > > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> > > 
> > > 
> > > > I think we should break the libdpdk problem into a separate GitHub issue. They look similar but will have two different resolutions. @ryderhsu0129 would you mind submitting a separate issue for this?
> > > > Regarding libspdk_nvme.so.4.0 - I see you've set LD_LIBRARY path, but it isn't exported. Or could you try:
> > > > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> > > 
> > > 
> > > @jimharris
> > > thanks for your help.
> > > We tried to do this:
> > > LD_LIBRARY_PATH=./build/lib build/examples/hello_world
> > > but an error still occurred:
> > > `Error while loading shared libraries, cannot open shared object file: librte_telemetry.so.0.200.2 :No such file or directory`
> > 
> > 
> > could you try this LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib build/examples/hello_world ?
> > it works in my environment
> 
> @changpe1
> 
> it's work
> `LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib build/examples/hello_world`
> 
> so it can be concluded that the problem is can't produce libdpdk.so?
> another question is in the previous version will go to the system folder `/usr/local/lib` to find libraries,
> no need to use LD_LIBRARY_PATH specify the path,
> It seems that the v20.07 needs to do this extra? thanks!

I think so, we did some change recently, I may need to update the README.md.

**Comment by ryderhsu0129** [comment]
May I ask if there is any update progress about this issue?thanks!

**Comment by changpe1** [comment]
@ryderhsu0129 I've update the README.md to add DPDK library to LD_LIBRARY_PATH, I can't see any issues from my tests now, let me know if you have further questions.

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 I've update the README.md to add DPDK library to LD_LIBRARY_PATH, I can't see any issues from my tests now, let me know if you have further questions.

@changpe1 

I want to confirm so it's normal that the libdpdk.so will not be created now?

**Comment by changpe1** [comment]
> > @ryderhsu0129 I've update the README.md to add DPDK library to LD_LIBRARY_PATH, I can't see any issues from my tests now, let me know if you have further questions.
> 
> @changpe1
> 
> I want to confirm so it's normal that the libdpdk.so will not be created now?

Yeah, SPDK will not help to generate libdpdk.so for now.

**Comment by ryderhsu0129** [comment]
> > > @ryderhsu0129 I've update the README.md to add DPDK library to LD_LIBRARY_PATH, I can't see any issues from my tests now, let me know if you have further questions.
> > 
> > 
> > @changpe1
> > I want to confirm so it's normal that the libdpdk.so will not be created now?
> 
> Yeah, SPDK will not help to generate libdpdk.so for now.

@changpe1 
Ok, thanks.

**Comment by ryderhsu0129** [comment]
@changpe1 

May I ask how to successfully include all DPDK libraries?
The content of our original Makefile that incluing `libdpdk.so` is:
```
LIBS+=-L/usr/local/lib \
 -Wl,--whole-archive,--no-as-needed \
 -lspdk \
 -ldpdk \
 -Wl,--no-whole-archive \
 -lspdk_env_dpdk \
 -lisal
}
```
The libdpdk.so will not be generated now in lastest SPDK, 
How do we include all DPDK libraries by modifying Makefile.
thanks.

**Comment by changpe1** [comment]
Could you try the following libraries? 

-lrte_eal -lrte_mempool -lrte_ring \
-lrte_mempool_ring -lrte_pci -lrte_bus_pci \
-lrte_kvargs -lrte_telemetry

**Comment by ryderhsu0129** [comment]
@changpe1 

It still looks like this error message:
`error: cannot find -ldpdk`
 
We modify the Makefile as follows:
```
LIBS+=-L/usr/local/lib \
 -Wl,--whole-archive,--no-as-needed \
 -lspdk \
 -lrte_eal \
 -lrte_mempool \
 -lrte_ring \
 -lrte_mempool_ring \
 -lrte_pci \
 -lrte_bus_pci \
 -lrte_kvargs \
 -lrte_telemetry \
 -Wl,--no-whole-archive \
 -lspdk_env_dpdk \
 -lisal
}
```

ps. we put all libraries under folder `/build/lib/ /dpdk/build/lib` into our system folder /usr/local/lib

**Comment by changpe1** [comment]
SPDK doesn't use -ldpdk anymore since 20.07, you may check your Makefile, you may refer to test/external_code/hello_world/Makefile as an example.

**Comment by ryderhsu0129** [comment]
it work when we include all DPDK libraries on Makefile
