### ISSUE TITLE
hello_world show no NVMe controllers found. After running scripts/setup.sh

### ISSUE THREAD

**Issue by Panlichen** [spdk/spdk#1602]
When running scripts/setup.sh, it says `0000:03:00.0 (15ad 07f0): Active mountpoints on /dev/nvme0n1, so not binding PCI dev`, I walked through scripts/setup.sh, it seems that this message is printed because the NVMe device works fine. However, examples/nvme/hello_world/hello_world still shows `no NVMe controllers found`.

I found that there was an old issue(#197) about this, It seems that simply running scripts/setup.sh solved it perfectly, but I am not that lucky.

## Context (Environment including OS version, SPDK version, etc.)

- OS version: Ubuntu 16.04 in VMware Workstation Pro 15 on Windows 10(2004) host, with NVMe virtual disk.
- SPDK version: Release v20.04.1, commit c5f0959d.

## Expected Behavior
I hope hello_world just say hello.

## Current Behavior
It doesn't.

## Possible Solution
Have no idea yet.

## Steps to Reproduce

I think the above description is clear enough.

**Comment by jimharris** [comment]
Hi,

Can you post the output of ‘mount’ on your system?

Thanks,

Jim

**Comment by Panlichen** [comment]
Thank you for your prompt response.
```shell
➜  ~ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=4041792k,nr_inodes=1010448,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=814468k,mode=755)
/dev/nvme0n1p1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=34,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=21392)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
vmware-vmblock on /run/vmblock-fuse type fuse.vmware-vmblock (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
vmhgfs-fuse on /mnt/hgfs type fuse.vmhgfs-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=814468k,mode=700)
gvfsd-fuse on /run/user/0/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```

**Comment by jimharris** [comment]
It looks like your root file system is on nvme0n1.  The setup.sh script will not unbind that controller since it would make your root filesystem inaccessible. You can try creating a second virtual NVMe disk for this VM instead.

**Comment by Panlichen** [comment]
I thought about to create another VM with root file system in a SATA disk, then add another NVMe disk, but I was not sure so I made this issue. Your advise is more convenient and clear. Thanks a lot, I will try it.

**Comment by Panlichen** [comment]
I added another virtual nvme disk, but it shares the same `bdf` with the previous one, so setup.sh still does nothing to the newly added nvme disk, and when I run hello_world, it still says that `no NVMe controllers found`. It seems that I can only solve this by creating a new VM with the root file system on a SATA(or SCSI) disk, and then add another nvme disk(without mounting it), I tried, and it works.
I am wondering why spdk cannot use the nvme disk that the root file system is on or another nvme disk that shares the same `bdf`. It seems kind of weird. If I have a physical machine with only one nvme disk, then I can hardly use spdk.

**Comment by wanghailiangx** [comment]
@Panlichen 
I also encountered a similar problem. Please check if your VMD is enabled on BIOS, disable it.
Checking steps：
./scripts/setup.sh status, if BDF is “10000...”, VMD is enabled.
```
NVMe devices
BDF             Vendor  Device  NUMA    Driver          Device name
**10000:02:00.0**   8086    0953    0       nvme                    nvme0
```
Disabled, you will see BDF is “0000...”.
```
BDF             Vendor  Device  NUMA    Driver          Device name
NVMe devices
**0000:d9:00.0**    8086    0953    1       vfio-pci                -
```
Then NVMe controllers can be found.

**Comment by Panlichen** [comment]
Thanks, the BDF on my machine(VM) begins with 0000. 

After I re-create a VM with root fs on a SCSI disk and then add a new NVMe disk without mounting it, hello_world works fine.

As I mentioned in the last comment, I still have some questions.

**Comment by Panlichen** [comment]
The doc helps.
