### ISSUE TITLE
CentOS8 build SPDK NVMF hang and never complete, but Ubuntu20.04 and CentOS7 is good

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#1603]
this build hang below on CentOS8
[root@localhost spdk]# make
The Meson build system
Version: 0.55.3
Source dir: /root/wayne/spdk/dpdk
Build dir: /root/wayne/spdk/dpdk/build-tmp
Build type: native build
Program cat found: YES
Project name: DPDK
Project version: 20.08.0
Using 'CC' from environment with value: 'cc'
Using 'CC' from environment with value: 'cc'
C compiler for the host machine: cc (gcc 8.3.1 "cc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)")
C linker for the host machine: cc ld.bfd 2.30-49
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program pkg-config found: YES
Program gen-pmdinfo-cfile.sh found: YES
Program list-dir-globs.py found: YES
Program check-symbols.sh found: YES
Program options-ibverbs-static.sh found: YES
Program binutils-avx512-check.sh found: YES
Program python3 found: YES (/usr/bin/python3.6)
Program cat found: YES
Program ../buildtools/symlink-drivers-solibs.sh found: YES (/bin/sh /root/wayne/spdk/dpdk/config/../buildtools/symlink-drivers-solibs.sh)
Checking for size of "void *" : 8
Library m found: YES
Library numa found: YES
Has header "numaif.h" : YES 
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Found CMake: /usr/bin/cmake (3.11.4)
---------------- Hang here -------------

[root@localhost etc]# cat /etc/issue
\S
Kernel \r on an \m

[root@localhost etc]# uname -a
Linux localhost 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomzawadzki** [comment]
[Bug scrub] @gwnet Is this using latest SPDK, if yes please provide a commit hash to be sure. Can you provide configure line too ?

We are in process of establishing separate Jenkins job to verify CentOS8 and will be able to check that particular setup. So far we've not encountered this issue. @mikeBashStuff please update with the status when the job is up and running.

**Comment by mikeBashStuff** [comment]
Currently, `Centos8` is being tested against CI configuration present for `Centos7`, including recent additions targeted for the use of DPDK's `igb_uio` driver (785d6ca209 in particular). During said tests, we haven't encountered any issues similar to this one. So, like @tomzawadzki mentioned, we would need some more details on what's the setup, configuration, etc. used on the affected system.

**Comment by mhae** [comment]
FWIW, I've been running various SPDK versions on CentOS8 for almost a year now.

**Comment by tomzawadzki** [comment]
@gwnet Please reopen this issue with more details if this still occurs for you.
