### ISSUE TITLE
Potential bug in pci_unplug()

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#1605]
In the pci_unplug() (dpdk/drivers/bus/pci/pci_common.c), why do we call rte_devargs_remove() to remove the saved device args? That looks a defect to me, since that’ll result in the hot removed device failed to be detected when it’s plugged back (when white list option was provided), the situation is described following:

      1.  App starts with white list option provided, let’s suppose the device in white list is: 0000:81:00.0;
      2.  rte_devargs_add() is called to add this device arg on rte_eal_init();
      3.  Issue “echo 1 > /sys/bus/pci/devices/0000\:81\:00.0/remove” to hot remove the device;
      4.  pci_unplug() is called to remove the device, and rte_devargs_remove() is called, so this device arg for white list is remove too;
      5.  Issue “echo 1 > /sys/bus/pci/rescan” then “PCI_WHITELIST=”0000:81:00.0” spdk/script/setup.sh” to do hot plug;
      6.  In pci_scan_one(), new dev is generated, however, the dev->device.devargs is set NULL since the device args has been removed on device unplug;
      7.  rte_pci_probe() does white list scan, however, it unexpectedly skips the device because the devargs of the device is NULL now;

I don’t fully understand the DPDK code, but this rte_devargs_remove() in pci_unplug() doesn’t make sense to me (when I commented it out, seems everything will work as expected). Is this a glitch or I missed anything?

## Expected Behavior

The device should be detected when it's plugged back. (with white list option provided)

## Current Behavior

The plugged device will never being detected.

## Possible Solution

Remove the rte_devargs_remove() in pci_unplug().

## Steps to Reproduce

      1.  App starts with white list option provided, let’s suppose the device in white list is: 0000:81:00.0;
      2.  rte_devargs_add() is called to add this device arg on rte_eal_init();
      3.  Issue “echo 1 > /sys/bus/pci/devices/0000\:81\:00.0/remove” to hot remove the device;
      4.  pci_unplug() is called to remove the device, and rte_devargs_remove() is called, so this device arg for white list is remove too;
      5.  Issue “echo 1 > /sys/bus/pci/rescan” then “PCI_WHITELIST=”0000:81:00.0” spdk/script/setup.sh” to do hot plug;
      6.  In pci_scan_one(), new dev is generated, however, the dev->device.devargs is set NULL since the device args has been removed on device unplug;
      7.  rte_pci_probe() does white list scan, however, it unexpectedly skips the device because the devargs of the device is NULL now;

## Context (Environment including OS version, SPDK version, etc.)

SPDK v20.01.1 and built in DPDK. CentOS 7

**Comment by mhae** [comment]
I didn't encounter this issue in CentOS8 with 20.01 doing a real hot plug. I also think there are hot remove/add tests in SPDK using KVM's hot plug capability.
I wonder if step 5 is correctly simulating a hot add.

**Comment by NiuYawei** [comment]
> I didn't encounter this issue in CentOS8 with 20.01 doing a real hot plug. I also think there are hot remove/add tests in SPDK using KVM's hot plug capability.
> I wonder if step 5 is correctly simulating a hot add.

So what's the correct way to do hot plug/remove simulation? Did you specify PCI_WHITELIST in your test? This option is the key difference, if we always do full scan without any whiltelis specified, there won't be any problem.

**Comment by changpe1** [comment]
@NiuYawei I think the issue is related with DPDK, did you send an email to DPDK community?

**Comment by NiuYawei** [comment]
> @NiuYawei I think the issue is related with DPDK, did you send an email to DPDK community?

Yes, I've already forwarded the mail in SPDK mail list to dev@dpdk.org, but no response yet. Is there any other channel to raise the issue for DPDK team? Thanks in advance.

**Comment by changpe1** [comment]
> > @NiuYawei I think the issue is related with DPDK, did you send an email to DPDK community?
> 
> Yes, I've already forwarded the mail in SPDK mail list to [dev@dpdk.org](mailto:dev@dpdk.org), but no response yet. Is there any other channel to raise the issue for DPDK team? Thanks in advance.

That's the right channel to DPDK, you may send a fix patch to that maillist, someone will review the patch.

**Comment by jimharris** [comment]
Hi @NiuYawei - which application did you run to demonstrate this issue?

**Comment by NiuYawei** [comment]
> Hi @NiuYawei - which application did you run to demonstrate this issue?

I used latest DAOS, but I think the problem could be reproduced by the SPDK hotplug example if you change the code a bit to specify a whitelist option before calling spdk_env_init().

I'm wondering if this problem has been fixed in recent SPDK master by the commit 814072 (where devargs was reconstructed after rte_bus_scan() and before rte_bus_probe()), I'm going to test and verify this. (unfortunately my testbed was re-deployed for some reason, so it could take some time for me to re-run the test, I'll get back to you immediately once I have any new findings)

**Comment by NiuYawei** [comment]
Ok, I verified that commit 814072 didn't fix the issue.

I patched SPDK hotplug to reproduce the issue:

`diff --git a/examples/nvme/hotplug/hotplug.c b/examples/nvme/hotplug/hotplug.c
index ff821c7..4298b87 100644
--- a/examples/nvme/hotplug/hotplug.c
+++ b/examples/nvme/hotplug/hotplug.c
@@ -73,6 +73,7 @@ static int g_insert_times;
 static int g_removal_times;
 static int g_shm_id = -1;
 static uint64_t g_timeout_in_us = SPDK_SEC_TO_USEC;
+static char *g_tr_addr;
 
 static void
 task_complete(struct perf_task *task);
@@ -411,6 +412,7 @@ static void usage(char *program_name)
 	printf("\t[-n expected hot insert times]\n");
 	printf("\t[-r expected hot removal times]\n");
 	printf("\t[-t time in seconds]\n");
+	printf("\t[-w transport ID]\n");
 }
 
 static int
@@ -421,13 +423,16 @@ parse_args(int argc, char **argv)
 
 	/* default value */
 	g_time_in_sec = 0;
+	g_tr_addr = NULL;
 
-	while ((op = getopt(argc, argv, "c:i:n:r:t:")) != -1) {
+	while ((op = getopt(argc, argv, "c:i:n:r:t:w:")) != -1) {
 		if (op == '?') {
 			usage(argv[0]);
 			return 1;
+		} else if (op == 'w') {
+			g_tr_addr = optarg;
+			continue;
 		}
-
 		val = spdk_strtol(optarg, 10);
 		if (val < 0) {
 			fprintf(stderr, "Converting a string to integer failed\n");
@@ -482,6 +487,7 @@ int main(int argc, char **argv)
 {
 	int rc;
 	struct spdk_env_opts opts;
+	struct spdk_pci_addr pci_addr;
 
 	rc = parse_args(argc, argv);
 	if (rc != 0) {
@@ -491,6 +497,15 @@ int main(int argc, char **argv)
 	spdk_env_opts_init(&opts);
 	opts.name = "hotplug";
 	opts.core_mask = "0x1";
+	if (g_tr_addr != NULL) {
+		if (spdk_pci_addr_parse(&pci_addr, g_tr_addr)) {
+			fprintf(stderr, "Invalid %s\n", g_tr_addr);
+			return 1;
+		}
+		opts.pci_whitelist = &pci_addr;
+		opts.num_pci_addr = 1;
+	}
+	
 	if (g_shm_id > -1) {
 		opts.shm_id = g_shm_id;
 	}
`
With above patch, you can provide whitelist by '-w' option to reproduce the problem:
- Unbind device by "PCI_WHITELIST="0000:81:00.0" spdk/scripts/setup.sh"
- Run hotplug example by "spdk/build/examples/hotplug -n 1 -r 1 -t 200 -w 0000:81:00.0"
- Emulate hot remove by "echo 1 > /sys/bus/pci/devices/0000\:81\:00.0/remove"
- Observed that hotplug works as expected on hot remove event
- Emulate hot plug by "echo 1 > /sys/bus/pci/rescan" then unbind device by "PCI_WHITELIST="0000:81:00.0" spdk/scripts/setup.sh"
- Hotplug example won't detect the hotplug event and timed out at the end

**Comment by jimharris** [comment]
After further discussion on the DPDK and SPDK mailing lists, this behavior is as expected.

The PCI whitelist refers to the specific device at the BDF when the application starts.  It does not apply to other devices that may occupy that same BDF at a later point.  BDFs can also change for a given physical PCIe slot based on any number of factors.

The use case here was to have multiple independent SPDK processes, each of which are responsible for handling SSDs plugged into a specific subset of physical PCIe slots (for example, one process per NUMA node that owns the SSDs attached to that NUMA node).  For this type of use case, messages (such as an RPC) need to be sent to a process to tell it to attach to a new SSD rather than relying on the PCI whitelist + automatic bdev nvme hotplug poller.
