### ISSUE TITLE
EAL errors when running a secondary process

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1606]
Is it expected to see such EAL errors when running secondary process (perf app)?
```
EAL: Failed to hotplug add device on primary
EAL: Driver cannot detach the device (0000:cf:00.0)
EAL: Failed to hotplug remove device on primary
```
Functionally it seems working i.e. IO traffic is completed and results are displayed.

from Jim
> You can ignore these error messages.  I admit they are annoying though.  These have been reported before in https://github.com/spdk/spdk/issues/1372.  I would not be opposed to filing a new issue for this though, then someone from SPDK team can submit a patch to upstream DPDK to eliminate the error messages in this case.

Issue is definitely not critical but introduce confusion.

## Expected Behavior

No errors from EAL reported.

## Current Behavior

EAL reports error.

## Possible Solution

Double check SPDK integration with DPDK's EAL. If no root-cause found then submit a patch to upstream DPDK.

## Steps to Reproduce

1. run nvmf_tgt as a primary process e.g. 
> ./nvmf_tgt -i 1
2. attach nvme device e.g. 
> ./rpc.py bdev_nvme_attach_controller -b NVMe0 -t PCIe -a cf:00.0
3. run perf as a secondary process e.g. 
> ./perf -r 'trtype:PCIe traddr:0000:cf:00.0' -q 128 -o 512 -w read -t 1 -i 1

## Context (Environment including OS version, SPDK version, etc.)

master branch (ebc227d9b23abcf5f81099611254eef84221d186)

**Comment by changpe1** [comment]
As Jim said, the log information doesn't affect anything, there are lots of such logs in CI system everyday. I can submit a patch to DPDK to eliminate such logs.

**Comment by tomzawadzki** [comment]
[Bug scrub] @changpe1 have you had a chance to look at submitting the patch to DPDK ?

**Comment by changpe1** [comment]
I looked the issue again, SPDK needs to be improved too.

**Comment by changpe1** [comment]
SPDK patch is here https://review.spdk.io/gerrit/c/spdk/spdk/+/7944

**Comment by changpe1** [comment]
DPDK patch is here https://patches.dpdk.org/project/dpdk/patch/1621406749-15536-1-git-send-email-changpeng.liu@intel.com/

**Comment by changpe1** [comment]
The error handling in DPDK hotplug module is really bad, I don't want to fix them all, so just had a small patch to fix the hot add case.  There is issue in the hot remove case too.

**Comment by jkalwas** [comment]
Hi @changpe1 ,
thank you for looking into this
DPDK patch seems fine to me, as for SPDK I do have some concerns - I put a comment in the patch itself.

**Comment by changpe1** [comment]
Using the same test steps, **before spdk patch:**

Primary process:
EAL: Failed to hotplug add device on primary
EAL: Failed to hotplug remove device on secondary

Secondary processs:
EAL: Driver cannot detach the device (0000:d9:00.0)
EAL: Failed to hotplug remove device

 **after spdk patch:**

Primary process:
EAL: Failed to hotplug add device on primary
EAL: Driver cannot detach the device (0000:d9:00.0)
EAL: Failed to hotplug remove device on primary

Secondary process:
EAL: Failed to hotplug remove device

According to the DPDK code the error log "EAL: Driver cannot detach the device (0000:d9:00.0)" should not occur in the secondary, so my patch only fix this error log.

**Comment by changpe1** [comment]
Closing this issue too as it doesn't affect anything, just the log isn't quite clear.
