### ISSUE TITLE
The system gets significantly slower with the kernel oops message related with the uio driver

### ISSUE THREAD

**Issue by yongseokoh** [spdk/spdk#161]
I tried to execute example/nvme/perf tool to measure my SSDs. However, the system usually gets slower after the kernel oops related with the uio driver messages happens as you can see the kernel log. After this situation, it is hard to do anything. Is there a solution to this problem? 

[   73.178728] irq 16: nobody cared (try booting with the "irqpoll" option)
[   73.178731] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.4.68 #1
[   73.178732] Hardware name: System manufacturer System Product Name/MAXIMUS VIII HERO ALPHA, BIOS 1504 01/28/2016
[   73.178733]  0000000000000086 52bf4d8ec394a64e ffff880873d83e58 ffffffff813e5684
[   73.178735]  ffff88084f58d600 ffff88084f58d69c ffff880873d83e88 ffffffff810ddd15
[   73.178736]  ffff88084f58d600 0000000000000000 0000000000000000 00000000000001c8
[   73.178737] Call Trace:
[   73.178738]  <IRQ>  [<ffffffff813e5684>] dump_stack+0x63/0x8f
[   73.178743]  [<ffffffff810ddd15>] __report_bad_irq+0x35/0xc0
[   73.178744]  [<ffffffff810de094>] note_interrupt+0x234/0x270
[   73.178745]  [<ffffffff810db364>] handle_irq_event_percpu+0x164/0x1d0
[   73.178746]  [<ffffffff810db40b>] handle_irq_event+0x3b/0x60
[   73.178747]  [<ffffffff810de5a9>] handle_fasteoi_irq+0x89/0x140
[   73.178748]  [<ffffffff8101a13a>] handle_irq+0x1a/0x30
[   73.178750]  [<ffffffff81824edb>] do_IRQ+0x4b/0xd0
[   73.178751]  [<ffffffff81822fc2>] common_interrupt+0x82/0x82
[   73.178752]  <EOI>  [<ffffffff816b63e7>] ? cpuidle_enter_state+0x107/0x2a0
[   73.178755]  [<ffffffff816b65b7>] cpuidle_enter+0x17/0x20
[   73.178756]  [<ffffffff810c4542>] call_cpuidle+0x32/0x60
[   73.178758]  [<ffffffff816b6593>] ? cpuidle_select+0x13/0x20
[   73.178759]  [<ffffffff810c480d>] cpu_startup_entry+0x29d/0x360
[   73.178760]  [<ffffffff81050a87>] start_secondary+0x157/0x190
[   73.178761] handlers:
[   73.178764] [<ffffffffc0086330>] ahci_single_level_irq_intr [libahci]
[   73.178766] [<ffffffffc0611110>] uio_interrupt [uio]
[   73.178767] Disabling IRQ #16

**Comment by jimharris** [comment]
> On May 17, 2017, at 12:22 AM, Yongseok Oh <notifications@github.com> wrote:
> 
> I tried to execute example/nvme/perf tool to measure my SSDs. However, the system usually gets slower after the kernel oops related with the uio driver messages happens as you can see the kernel log. After this situation, it is hard to do anything. Is there a solution to this problem?

Hi Yongseok,

This callstack seems to indicate that an AHCI controller is bound to uio?  Or there is some IRQ that is shared between the AHCI controller and one of the devices bound to uio (either NVMe or could be IOAT).

Could you attach the output of lspci -vvv to this issue?  This may help us diagnose and/or reproduce.  I have not seen this issue, nor have heard any reports of a similar issue, but maybe your system has some unique characteristics.

Thanks,

-Jim

**Comment by yongseokoh** [comment]
This situation has been cleared after reinserting my NVMe AIC card and rebooting the system. This is still challenging. I will let you know and post a result of lspci if this issue happens again.
