### ISSUE TITLE
[BlobFS-autotest] Build timed out (after 15 minutes). Marking the build as failed.

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#1614]
## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_27775.html

## Execution failed at
https://ci.spdk.io/results/autotest-per-patch/builds/27775/archive/BlobFS-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @liang2yan. log: https://ci.spdk.io/public_build/autotest-per-patch_27775.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_27781.html

**Comment by karlatec** [comment]
There was a slight misconfiguration in CI infrastructure which caused tests to fail on GP8 node. It's been fixed and problem should no longer appear.

**Comment by karlatec** [comment]
Hasn't been reported in 2 days. Can I close it?

**Comment by liang2yan** [comment]
ok. let me close it.
