### ISSUE TITLE
SPDK hotplug example doesn't work with VFIO dirver

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#1616]
SPDK hotplug example in spdk/example/nvme/hotplug works well with UIO driver, but it doesn't work with VFIO driver.

## Expected Behavior

Run SPDK hotplug example with UIO driver in following steps:
1. Unbind device by "spdk/scripts/setup.sh"
2. Run hotplug example "examples/nvme/hotplug/hotplug -n 1 -r 1 -t 100"
3. Emulate device remove by "echo 1 > /sys/bus/pci/devices/0000\:81\:00.0/remove"
4. Observed bunch of error messages indicating the ctrlr is failed & removed by SPDK
5. Emulate device plug by "echo 1 > /sys/bus/pci/rescan" and unbind device by "spdk/scripts/setup.sh"
6. Observed messages indicating the ctrlr is detected and attached by SPDK
7. Hotplug example exit successfully

## Current Behavior

However, when I run the hotplug example with VFIO driver, it didn't work as expected:
- On step 4, error messages like "EAL: Unexpected device scan at /sys/bus/pci/devices/0000:81:00.0/driver!" are observed
- On step 5, "echo 1 > /sys/bus/pci/rescan" never completes
- The hotplug exmaple timed out at the end

## Possible Solution

I debugged into the issue a bit, seems no remove event is detected in _nvme_pcie_hotplug_monitor() after step 3.

## Steps to Reproduce

See the steps in "Expected behavior" section.

## Context (Environment including OS version, SPDK version, etc.)

Tried v20.01.1, v20.07 and latest master, used built-in DPDK. CentOS7.

**Comment by glodfish-zg** [comment]
I will take a look and try to reproduce this issue. The device should trigger an interrupt when it is removed with VFIO driver.

**Comment by jimharris** [comment]
I'm concerned this could be an issue with older CentOS 7 kernel.  I ran this same test on 5.0 kernel and didn't see any issues.

@NiuYawei - would you be able to test on CentOS 8 and see if same problem exists?

**Comment by NiuYawei** [comment]
> I'm concerned this could be an issue with older CentOS 7 kernel. I ran this same test on 5.0 kernel and didn't see any issues.
> 
> @NiuYawei - would you be able to test on CentOS 8 and see if same problem exists?

Sure, but we don't have CentOS 8 test node by hand, need some time to find an available node for re-provision. Will get back to you later.

**Comment by sydneyvanda** [comment]
@jimharris @NiuYawei I was just able to test on CentOS 8.2, and I was not able to reproduce the issue. Seems VFIO with hotplug example only has issues in CentOS 7 kernel like you mentioned

**Comment by tomzawadzki** [comment]
[Bug scrub] This looks like an issue with the kernel in CentOS 7, since CentOS 8.2 work.
