### ISSUE TITLE
Hugepage leaks when kill qemu with vhost-user-scsi-pci device 

### ISSUE THREAD

**Issue by subo7** [spdk/spdk#162]
I tried start a guest with vhosts-user-scsi-pci device:
./qemu-spdk/x86_64-softmmu/qemu-system-x86_64 -m 4096 -smp 8 -object memory-backend-file,id=mem,size=4G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem -drive file=/mnt/spdk-vhost/rhel1.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=char0,path=/mnt/spdk-vhost/spdk-17.03/vhost.0 -device vhost-user-scsi-pci,id=scsi0,chardev=char0 --enable-kvm -vnc 0.0.0.0:3

after I killed qemu with ctr+c,  I can't start guest again:
./qemu-spdk/x86_64-softmmu/qemu-system-x86_64 -m 4096 -smp 8 -object memory-backend-file,id=mem,size=4G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem -drive file=/mnt/spdk-vhost/rhel1.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=char0,path=/mnt/spdk-vhost/spdk-17.03/vhost.0 -device vhost-user-scsi-pci,id=scsi0,chardev=char0 --enable-kvm -vnc 0.0.0.0:3
qemu-system-x86_64: -object memory-backend-file,id=mem,size=4G,mem-path=/dev/hugepages,share=on: unable to map backing store for guest RAM: Cannot allocate memory

vhost app still open hugepage file:
linux-rXzDEU:~ # ps aux | grep vhost | grep -v grep
root     172315  199  0.1 1232020 136416 pts/0  Rl+  07:41  26:04 ./app/vhost/vhost -c /home/vhost.conf
linux-rXzDEU:~ # ll /proc/172315/fd | grep qemu
lrwx------ 1 root root 64 May 17 07:44 61 -> /dev/hugepages/qemu_back_mem._objects_mem.mq9mtT (deleted)
lrwx------ 1 root root 64 May 17 07:44 62 -> /dev/hugepages/qemu_back_mem._objects_mem.mq9mtT (deleted)
lrwx------ 1 root root 64 May 17 07:44 63 -> /dev/hugepages/qemu_back_mem._objects_mem.mq9mtT (deleted)

**Comment by tomzawadzki** [comment]
Thanks for the bug report.
I've been able to reproduce this error by issuing ctrl+c exactly at the point when VM switches from BIOS to OS. This seems to related to remapping memory at that time.
No fix is available yet, but it is currently being worked on.

**Comment by tomzawadzki** [comment]
We've been able to resolve this issue with commit currently in [review](https://review.gerrithub.io/#/c/361787/).
That patch helps if VM is killed during transition from BIOS to OS, and I've not been able to reproduce this issue with patch applied anymore.
Please let us know if you happen to encounter it in some other case.

**Comment by dverkamp-intel** [comment]
Closing as fixed by commit 216901dbd783faf190a8ac9eac194d439036e260
