### ISSUE TITLE
Creating I/O queue pair after controller reset failed

### ISSUE THREAD

**Issue by aohzju** [spdk/spdk#1621]
The following sequence fails:
1. Allocate an I/O queue pair
2. Do controller reset via spdk_nvme_ctrlr_reset
3. Allocate an I/O queue pair

The 3rd step fails due to SPDK allocates qid from  1 again, but spdk_nvme_ctrlr_reset has reactivated the qid 1 created in step 1.

**Comment by changpe1** [comment]
Thanks for submitting, this is a bug in SPDK, I will provide a fix.

**Comment by changpe1** [comment]
I submitted a fix patch https://review.spdk.io/gerrit/c/spdk/spdk/+/4698, could you have a try ? thanks.

**Comment by aohzju** [comment]
Confirm fixed. Thanks. When will be the next release?

**Comment by changpe1** [comment]
> Confirm fixed. Thanks. When will be the next release?

Thanks, the next version will be 20.10 by end of this Oct.

**Comment by changpe1** [comment]
Patch has been merged, I'm going to close it now.
