### ISSUE TITLE
spdk bdev aio can not retry submit nomem_io, when disk is busy.

### ISSUE THREAD

**Issue by yaojingen** [spdk/spdk#1622]
In spdk/module/bdev/aio/bdev_aio.c bdev_aio_group_poll func, if all of io callback(shared_resource->io_outstanding) and do bdev_ch_retry_io but still return -EAGAIN, the bdev_io will insert to shared_resource->nomem_io tailq again. But all of io(shared_resource->io_outstanding == 0) is done, so the bdev_io which is in shared_resource->nomem_io taiq will still in the queue. If application is not to submit any new io, the bdev_io which in the queue was no opportunity to resubmit.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
Hi @yaojingen,

Which version of SPDK are you testing with?

Thanks,

Jim

**Comment by yaojingen** [comment]
> Hi @yaojingen,
> 
> Which version of SPDK are you testing with?
> 
> Thanks,
> 
> Jim

Hi，The version is v20.07！

**Comment by jimharris** [comment]
Could you try your test on master?  There were some fixes that went if for this issue last month which are not in the SPDK 20.07 release.

**Comment by yaojingen** [comment]
> Could you try your test on master? There were some fixes that went if for this issue last month which are not in the SPDK 20.07 release.
I have already check that the code logic of the master branch is consistent with that of this version 20.07. Please help to check again of this problem.

**Comment by yaojingen** [comment]
This bug has been fixed of master. So, close it.
