### ISSUE TITLE
[test_name] Failure description

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1627]
hi all：
When I submitted a new patch in git push review, something happened:

suh@suh-virtual-machine:~/src/spdk/git/push/spdk$ git push review 
warning: 重定向到 https://review.spdk.io/gerrit/spdk/spdk/
Running make with gcc ...
  CC lib/bdev/bdev.o
  LIB libspdk_sock.a
  CC lib/bdev/bdev_rpc.o
app.c: In function ‘spdk_app_parse_args’:
app.c:968:7: error: this statement may fall through [-Werror=implicit-fallthrough=]
    if (rc < 0) {
       ^
app.c:977:3: note: here
   case HUGE_UNLINK_OPT_IDX:
   ^~~~
cc1: all warnings being treated as errors
make[2]: *** [/home/suh/src/spdk/git/push/spdk/mk/spdk.common.mk:370：app.o] 错误 1
make[1]: *** [/home/suh/src/spdk/git/push/spdk/mk/spdk.subdirs.mk:44：event] 错误 2
make[1]: *** 正在等待未完成的任务....
  CC lib/bdev/bdev_zone.o
  CC lib/bdev/part.o
  CC lib/bdev/scsi_nvme.o
  LIB libspdk_blob.a
  LIB libspdk_bdev.a
make: *** [/home/suh/src/spdk/git/push/spdk/mk/spdk.subdirs.mk:44：lib] 错误 2

ERROR make returned errors!
ERROR Fix the problem and use 'git commit' to update your changes.
ERROR See /home/suh/src/spdk/git/push/spdk/make.log for more information.

error: 推送一些引用到 'https://review.spdk.io/spdk/spdk' 失败

=================================================================================
make.log:
[https://github.com/zlsh007/Others/blob/master/spdk/make-spdk_app_parse_args.log](url)
=================================================================================

Thanks
    su

**Comment by shuhei-matsumoto** [comment]
Hi @zlsh007 

I think this is the one fixed by Jim very recently :) Please take a look at 
https://github.com/spdk/spdk/commit/eecc14df1958049e4134ab0a01daa610a598a789.

**Comment by zlsh007** [comment]
@shuhei-matsumoto 
Thanks, I didn't notice it :), it's okay now.
