### ISSUE TITLE
Problems caused by the order of execution

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1628]
Hi all：
When the sampling period is set by spdk_bdev_set_qd_sampling_period, bdev_calculate_measured_queue_depth will be executed periodically. This function calls spdk_for_each_channel. In this function, ch->dev->for_each_count++ will be executed; and in the callback function _calculate_measured_qd, through the execution of sp->dev->for_each_count++; >for_each_count--operation. When our process exits, such as the vhost process, in the exit path spdk_bdev_finish--->bdev_finish_unregister_bdevs_iter ----> spdk_bdev_unregister(bdev, bdev_finish_unregister_bdevs_iter, bdev); ---> bdev_fini ----> spdk_io_dev_fini ----> spdk_io_dev_fini ----> spdk_io_dev_unregister , bdev_destroy_cb); There will be an if (dev->for_each_count> 0) problem occasionally, resulting in the failure of the entire bdev_finish, because now spdk_io_device_unregister has no return value, we have not judged whether this function is executed correctly; The reason for this >0 is that although the poller is deleted through spdk_bdev_set_qd_sampling_period(bdev, 0) in the spdk_bdev_close phase when the process exits, this is an asynchronous process. As a result, the poller function bdev_calculate_measured_queue_depth does not completely exit at the stage of spdk_io_device_unregister, and it is executed to for_each_count++.

## Expected Behavior
Process exits correctly.

## Current Behavior
There is a problem with the process exit：
thread.c:1088:spdk_io_device_unregister: *ERROR*: io_device xxx (0x1582a6e1) has 1 for_each calls outstanding

## Possible Solution
We can add an interface function that deletes poller synchronously to ensure that there will be no timing problems caused by this asynchronous execution. 
I submitted a related [patch：](https://review.spdk.io/gerrit/c/spdk/spdk/+/4735)

## Steps to Reproduce
1.Start a vhost process
2.Set a bdev sampling period through spdk_bdev_set_qd_sampling_period
3.Stop the vhost process
4.Repeat steps 1->3

Thanks
    Su

**Comment by shuhei-matsumoto** [comment]
Hi @zlsh007 

Thanks for your investigation and clear explanation about this issue.
How about removing the check simply?
Did you already try this idea?

spdk_for_each_channel() does not access the global list g_io_devices.

If no IO channel (dev->refcnt == 0), spdk_for_each_channel() does not increment or decrement dev->for_each_count.
spdk_io_device_unregister() just registers callback function if any IO channel (dev->refcnt > 0).


```
--- a/lib/thread/thread.c
+++ b/lib/thread/thread.c
@@ -1443,13 +1443,6 @@ spdk_io_device_unregister(void *io_device, spdk_io_device_unregister_cb unregist
                return;
        }

-       if (dev->for_each_count > 0) {
-               SPDK_ERRLOG("io_device %s (%p) has %u for_each calls outstanding\n",
-                           dev->name, io_device, dev->for_each_count);
-               pthread_mutex_unlock(&g_devlist_mutex);
-               return;
-       }
-
        dev->unregister_cb = unregister_cb;
        dev->unregistered = true;
        TAILQ_REMOVE(&g_io_devices, dev, tailq);
```

-Shuhei

**Comment by jimharris** [comment]
I don't think removing the for_each_count check will work.  It has the potential to access freed memory if the for_each_count is > 0. The for_each_count check is there for a reason - if we are performing some kind of for_each_channel operation, we *must* make sure that we do not unregister the underlying device while that for_each operation is still iterating.

But I'm also not sure about the sync interface.  In this specific case it might be OK, but in general you would not be able to call this function from within the poller callback itself.  It will add confusion to users on which interface they should use and why.

Can we handle this transparently inside of spdk_poller_unregister() instead?  Something like this:

if (poller->state != SPDK_POLLER_STATE_RUNNING) {
  if (poller->state == SPDK_POLLER_STATE_PAUSED) {
    /* remove poller from thread->paused_pollers */
  else if (poller->period_ticks) {
    /* remove poller from thread->timed_pollers */
  } else {
    /* remove poller from thread->active_pollers */
  }
  free(poller);
  return;
}

You'll want to put this before the current if (poller->state == SPDK_POLLER_STATE_PAUSED) check.

**Comment by shuhei-matsumoto** [comment]
Thank you Jim, Suhua, I read critically again and I'm fine with your ideas.

**Comment by shuhei-matsumoto** [comment]
Hi @Jim,

This may not be the place for code review but then the current if (poller->state == PAUSED) check cannot be true after synchronous unregister? Hence can we do more as follows?

if (poller->state == RUNNING) {
  poller->state = UNREGISTERED;
  return;
}

if (poller->state == PAUSED) {
  remove poller from thread->paused_pollers;
} else if (poller->period_ticks) {
  remove poller from thread->timed_pollers;
} else {
  remove poller from thread->active_pollers;
}
free(poller);

**Comment by jimharris** [comment]
Good catch Shuhei.  But I did miss something - we need to check:

if (poller->state == RUNNING || poller->state == PAUSING)

We use PAUSING state if user calls spdk_poller_pause() from the poller callback context.  So in this case we cannot immediately free the poller either.

**Comment by shuhei-matsumoto** [comment]
Thank you Jim for recheck.

**Comment by zlsh007** [comment]
@jimharris @shuhei-matsumoto Thank you very much for your suggestions. I will think about how to modify the code logic.

**Comment by tomzawadzki** [comment]
@zlsh007 have you had a chance to modify the [patch ](https://review.spdk.io/gerrit/c/spdk/spdk/+/4735) resolving this issue ?

**Comment by zlsh007** [comment]
@tomzawadzki 
I need to look at the processing logic of the new version. I recently used the 20.04 branch to test and found that sometimes the same problem occurs even if it is deleted synchronously. It may be caused by some changes in the processing logic. Currently, the sampling period is set to 0 in advance through rpc, and then stop the service to avoid this problem

**Comment by zlsh007** [comment]
Close this question temporarily, open it when there is progress

**Comment by zlsh007** [comment]
If other people have ideas to fix this problem, they can fix it directly.
