### ISSUE TITLE
deadlock when vfio_pci_memory_region_op failed

### ISSUE THREAD

**Issue by subo7** [spdk/spdk#163]
Started poller for vhost controller vhost.1 on lcore 0
Registering VM memory for vtophys translation - 0x2aac6ae00000 len:0x100000000
vhost_iommu.c: 132:vfio_pci_memory_region_map: ***ERROR*** Cannot set up DMA mapping, error 22 (Invalid argument)
vhost_iommu.c: 271:spdk_vfio_mem_op: ***ERROR*** Failed to map region region vaddr=0x2aad2ae00000 phys_addr=0xfbc600000 len=0x200000
PANIC in new_device():
Failed to register new device 'vhost.1'
8: [/lib64/libc.so.6(clone+0x6d) [0x7f80a0f8171d]]
7: [/lib64/libpthread.so.0(+0x7dc5) [0x7f80a1253dc5]]
6: [./app/vhost/vhost() [0x429bde]]
5: [./app/vhost/vhost() [0x426dc2]]
4: [./app/vhost/vhost() [0x427fe4]]
3: [./app/vhost/vhost() [0x41abb9]]
2: [./app/vhost/vhost() [0x40484e]]
1: [./app/vhost/vhost() [0x436a7a]]

spdk_vfio_mem_op must hold the &vfio_cfg.map_lock，but if vfio_pci_memory_region_op failed，spdk_vfio_mem_op is called again without releasing the lock
if (ret) {
		spdk_vfio_mem_op(addr, vaddr - addr, VFIO_IOMMU_UNMAP_DMA);
	}
 
then deadlock

**Comment by pawelwod** [comment]
Please check if this https://review.gerrithub.io/#/c/361934/ fixes the issue.
