### ISSUE TITLE
[lvol_bg_autotest] bdev.c:1520:bdev_finish_unregister_bdevs_iter: *WARNING*: Unregistering claimed bdev

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1630]
This occurs always in one of the test system. This is not error but warning 
Unclaiming the bdev before SPDK application shutdown is better to do.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/28684/archive/lvol-vg-autotest/build.log

## Execution failed at

```
00:03:52.553  killing process with pid 23591
00:03:52.553   13:08:28	# process_name=reactor_0
00:03:52.553   13:08:28	# '[' reactor_0 = sudo ']'
00:03:52.553   13:08:28	# echo 'killing process with pid 23591'
00:03:52.553   13:08:28	# kill 23591
00:03:52.553   13:08:28	# wait 23591
00:03:52.773  [2020-10-18 13:08:29.024926] bdev.c:1520:bdev_finish_unregister_bdevs_iter: *WARNING*: Unregistering claimed bdev 'aio_bdev0'!
00:03:52.832  [2020-10-18 13:08:29.083368] bdev.c:1520:bdev_finish_unregister_bdevs_iter: *WARNING*: Unregistering claimed bdev 'aio_bdev1'!
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_29034.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30098.html

**Comment by optimistyzy** [comment]
@shuhei-matsumoto Do we see this issue recently? If there is no such issue found, we will close this issue.

**Comment by tomzawadzki** [comment]
This issue still occurs. Please see a recent build of merged patch https://ci.spdk.io/results/autotest-per-patch/builds/54345/archive/lvol-vg-autotest/build.log.

This is specific to lvolstore. `bdev_finish_unregister_bdevs_iter` calls `spdk_bdev_unregister`, but the `vbdev_lvol_unregister` only closes the lvol. It will not call `spdk_lvs_unload` for the lvolstore itself, meaning that underlying bdev will still be claimed.
One way to address it would be to unload lvs on last lvol unregister, but this does not address issue when there are no lvol on top of lvolstore.

I'll give it a shot.
