### ISSUE TITLE
spdk_nvme_ns_cmd_write_zeroes does not actually zero the device.

### ISSUE THREAD

**Issue by jingliu9** [spdk/spdk#1634]
## Expected Behavior

use `spdk_nvme_ns_cmd_write_zeroes(0, 8); spdk_nvme_ns_cmd_write_zeroes(8,8); spdk_nvme_ns_cmd_write_zeroes(16, 8);` to erase the first three 4K blocks of the nvme devices. I expect when I read back by `spdk_nvme_ns_cmd_read`, it will be all zero. 

## Current Behavior

However, from the second 4K block (lba start from 8) there is some byte not 0.

## Steps to Reproduce

1. `spdk_nvme_ns_cmd_write_zeroes(0, 8); spdk_nvme_ns_cmd_write_zeroes(8,8); spdk_nvme_ns_cmd_write_zeroes(16, 8);`
2. read them back
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

18.04.01 spdk, intel optane SSD 905p, linux 5.4.0-51-generic.

**Comment by jimharris** [comment]
Hi @jingliu9,

Are you able to reproduce this with most recent SPDK release?

-Jim

**Comment by jingliu9** [comment]
nvm.  the reason is that `spdk_nvme_get_flags` shows it does not support `WRITE_ZEROES` flag. 
I haven't tried the latest spdk yet. 

Initially, I simply run the test case (https://github.com/spdk/spdk/blob/f49fa23d9ad0c3f9bf05c9ff845918b4307ac230/test/unit/lib/nvme/nvme_ns_cmd.c/nvme_ns_cmd_ut.c#L543) and thought it was fine.

I'm wondering does this feature requires the support from SSD? CPU? or mother board?

Thanks!

**Comment by jimharris** [comment]
Hi @jingliu9,

The SSD must support the WRITE_ZEROES command.

FYI - the SPDK identify tool (found under examples/nvme/identify in SPDK 18.01) will show whether or not your SSDs support it.

-Jim
