### ISSUE TITLE
[vhost_boot] Test failed with 'No bootable device.'

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1640]
https://ci.spdk.io/results/autotest-per-patch/builds/29005/archive/vhost-autotest/build.log

00:07:11.346  Searching bootorder for: /pci@i0cf8/*@3
00:07:11.346  Searching bootorder for: /rom@genroms/kvmvapic.bin
00:07:11.346  Searching bootorder for: HALT
00:07:11.346  drive 0x000e8e20: PCHS=0/0/0 translation=lba LCHS=1024/255/63 s=40960000
00:07:11.346  Running option rom at cb00:0003
00:07:11.346  Space available for UMB: cd800-e8000, f3da0-f5950
00:07:11.346  Returned 118784 bytes of ZoneHigh
00:07:11.346  e820 map has 7 items:
00:07:11.346    0: 0000000000000000 - 000000000009fc00 = 1 RAM
00:07:11.346    1: 000000000009fc00 - 00000000000a0000 = 2 RESERVED
00:07:11.346    2: 00000000000f0000 - 0000000000100000 = 2 RESERVED
00:07:11.346    3: 0000000000100000 - 000000003ffdd000 = 1 RAM
00:07:11.346    4: 000000003ffdd000 - 0000000040000000 = 2 RESERVED
00:07:11.346    5: 00000000feffc000 - 00000000ff000000 = 2 RESERVED
00:07:11.346    6: 00000000fffc0000 - 0000000100000000 = 2 RESERVED
00:07:11.346  enter handle_19:
00:07:11.346    NULL
00:07:11.346  Booting from Hard Disk...
00:07:11.346  Boot failed: not a bootable disk
00:07:11.346  
00:07:11.346  enter handle_18:
00:07:11.346    NULL
00:07:11.346  Booting from Floppy...
00:07:11.346  floppy error: 40 00 00 00 00 01 02
00:07:11.346  Boot failed: could not read the boot disk
00:07:11.346  
00:07:11.346  enter handle_18:
00:07:11.346    NULL
00:07:11.346  Booting from DVD/CD...
00:07:11.346  Device reports MEDIUM NOT PRESENT
00:07:11.346  scsi_is_ready returned -1
00:07:11.346  Boot failed: Could not read from CDROM (code 0003)
00:07:11.346  enter handle_18:
00:07:11.346    NULL
00:07:11.346  Booting from ROM...
00:07:11.346  Booting from ca00:0385
00:07:11.346  enter handle_18:
00:07:11.346    NULL
00:07:11.346  No bootable device.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_29005.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_29146.html

**Comment by Maciej-Szwed** [comment]
It looks like real issue with my patch, not intermittent failure. Closing.
