### ISSUE TITLE
[CI]There was an error talking to Libvirt.

### ISSUE THREAD

**Issue by jiaqizho** [spdk/spdk#1644]
## Link to the failed CI build

https://review.spdk.io/gerrit/c/spdk/spdk/+/4818
https://ci.spdk.io/results/autotest-per-patch/builds/29391/archive/unittest-vg-autotest/build.log

## Execution failed at

00:00:33.257  There was an error talking to Libvirt. The error message is shown
00:00:33.257  below:
00:00:33.257  
00:00:33.257  Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: 2020-10-23 02:30:51.807+0000: Domain id=5333 is tainted: custom-argv
00:00:33.257  qemu-system-x86_64: -realtime mlock=off: warning: '-realtime mlock=...' is deprecated, please use '-overcommit mem-lock=...' instead
00:00:33.257  2020-10-23T02:30:51.866981Z qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory

rerun pls : )

**Comment by jimharris** [comment]
Hi Jiaqi,

I think this is a duplicate of 1639. Can you check?

Thanks,

Jim

**Comment by jiaqizho** [comment]
> Hi Jiaqi,
> 
> I think this is a duplicate of 1639. Can you check?
> 
> Thanks,
> 
> Jim

duplicate , closed this
