### ISSUE TITLE
[freebsd-vg-autotes] SSH timeout

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1646]
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_29327.html

## Execution failed at

```
00:00:44.251  ==> default:  -- Command line args: 
00:00:44.251  ==> default:     -> value=-drive, 
00:00:44.251  ==> default:     -> value=format=raw,file=/var/lib/libvirt/images/backends/ex0-nvme.img,if=none,id=nvme-0, 
00:00:44.252  ==> default:     -> value=-device, 
00:00:44.252  ==> default:     -> value=nvme,drive=nvme-0,serial=12340, 
00:00:47.238  ==> default: Creating shared folders metadata...
00:00:47.260  ==> default: Starting domain.
00:00:48.634  ==> default: Waiting for domain to get an IP address...
00:01:11.009  ==> default: Waiting for SSH to become available...
00:04:05.358      default: 
00:04:05.358      default: Inserting generated public key within guest...
00:04:06.432      default: Removing insecure key from the guest if it's present...
00:04:07.571      default: Key inserted! Disconnecting and reconnecting using new SSH key...
00:05:04.333  ==> default: Configuring and enabling network interfaces...
```

Might be duplicate of #1645 but logs are different

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_29327.html

**Comment by mikeBashStuff** [comment]
Duplicate of #1645 - the error log is the same. Fortune cookies are spamming the log though so it may look a bit different. These will be disabled in a newer image we built for freebsd.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_29436.html

**Comment by AlekseyMarchuk** [comment]
@mikeBashStuff thanks, I'm closing this issue
