### ISSUE TITLE
[bdev_verify] bdevperf data verification error

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1647]
00:06:14.975  ************************************
00:06:14.975  START TEST bdev_verify
00:06:14.975  ************************************
00:06:14.975   18:54:00	# xtrace_enable
00:06:14.975   18:54:00	# /home/vagrant/spdk_repo/spdk/test/bdev/bdevperf/bdevperf --json /home/vagrant/spdk_repo/spdk/test/bdev/bdev.json -q 128 -o 4096 -w verify -t 5 -C -m 0x3
00:06:15.024  [2020-10-23 18:54:00.868345] Starting SPDK v20.10-pre git sha1 bab685662 / DPDK 20.08.0 initialization...
00:06:15.024  [2020-10-23 18:54:00.868584] [ DPDK EAL parameters: [2020-10-23 18:54:00.868611] bdevperf [2020-10-23 18:54:00.868647] --no-shconf [2020-10-23 18:54:00.868663] -c 0x3 [2020-10-23 18:54:00.868683] --log-level=lib.eal:6 [2020-10-23 18:54:00.868699] --log-level=lib.cryptodev:5 [2020-10-23 18:54:00.868731] --log-level=user1:6 [2020-10-23 18:54:00.868751] --iova-mode=pa [2020-10-23 18:54:00.868770] --base-virtaddr=0x200000000000 [2020-10-23 18:54:00.868785] --match-allocations [2020-10-23 18:54:00.868806] --file-prefix=spdk_pid75693 [2020-10-23 18:54:00.868821] ]
00:06:15.035  EAL: No available hugepages reported in hugepages-1048576kB
00:06:15.137  EAL: No legacy callbacks, legacy socket not created
00:06:15.155  [2020-10-23 18:54:01.000598] app.c: 450:spdk_app_start: *NOTICE*: Total cores available: 2
00:06:15.376  [2020-10-23 18:54:01.212633] reactor.c: 369:reactor_run: *NOTICE*: Reactor started on core 1
00:06:15.376  [2020-10-23 18:54:01.213648] reactor.c: 369:reactor_run: *NOTICE*: Reactor started on core 0
00:06:15.386  [2020-10-23 18:54:01.230960] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:06:15.573  [2020-10-23 18:54:01.417734] 'OCF Core' volume operations registered
00:06:15.581  [2020-10-23 18:54:01.423590] 'SPDK block device' volume operations registered
00:06:15.707  Running I/O for 5 seconds...
00:06:20.739  Buffer mismatch! Target: Nvme1n3 Disk Offset: 228331
00:06:20.739     First dword expected 0x4a4a4a4a got 0xadadadad
00:06:20.739  Buffer mismatch! Target: Nvme1n3 Disk Offset: 228323
00:06:20.739     First dword expected 0x45454545 got 0x8e8e8e8e
00:06:20.739  Buffer mismatch! Target: Nvme1n3 Disk Offset: 228324
00:06:20.739     First dword expected 0xa5a5a5a5 got 0x30303030
00:06:20.739  Buffer mismatch! Target: Nvme1n3 Disk Offset: 228329
00:06:20.739     First dword expected 0xb6b6b6b6 got 0xe0e0e0e
00:06:20.739  Buffer mismatch! Target: Nvme1n3 Disk Offset: 228332
00:06:20.739     First dword expected 0x15151515 got 0xf0f0f0f
00:06:20.739  Buffer mismatch! Target: Nvme1n3 Disk Offset: 10391
00:06:20.739     First dword expected 0x21212121 got 0xb0b0b0b0
00:06:20.739  Job run time less than one microsecond, no performance data will be shown
00:06:20.739  
 Thread name: Nvme0n1_1
00:06:20.739  
 Core Mask: 0x1
00:06:20.739  
 Nvme0n1             :        inf IOPS        inf MiB/s
00:06:20.739  
                     :       -nan Fail/s     -nan TO/s
00:06:20.739  
 Thread name: Nvme0n1_2
00:06:20.739  
 Core Mask: 0x2
00:06:20.739  
 Nvme0n1             :        inf IOPS        inf MiB/s
00:06:20.739  
                     :       -nan Fail/s     -nan TO/s
00:06:20.739  
 Thread name: Nvme1n1_1
00:06:20.739  
 Core Mask: 0x1

**Comment by jimharris** [comment]
First two failures are both on VM-host-PE3

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_29517.html

**Comment by optimistyzy** [comment]
@jimharris 

"128 -o 4096 -w verify -t 5 -C -m 0x3". Not sure in verification mode, we can use multiple cores.  Because I see the following info:

Thread name: Nvme0n1_1
00:06:20.739
Core Mask: 0x1
00:06:20.739
Nvme0n1 : inf IOPS inf MiB/s
00:06:20.739
: -nan Fail/s -nan TO/s
00:06:20.739
Thread name: Nvme0n1_2
00:06:20.739
Core Mask: 0x2


Does it mean that NVMe0n1 is operating by two different CPU cores. Will the two CPUs access the same region and make the verification not correct.  In my mind, verification should be run by one thread, it will write and read.  If we run multiple threads, we need to make sure that different threads will not operate on the same region.

**Comment by peluse** [comment]
It didn't used to support verify w/multi-core but it should now.  See bdevperf_construct_job() where jobs w/multiple cores are assigned their own LBA ranges to operate on.  This was pretty heavily tested when I added it however there's been a ton of refactoring since then so it's entirely possible something was introduced.  Lets talk in bug scrub, I can probably take this one

**Comment by changpe1** [comment]
[Bug Scrub] @peluse assign this issue to Paul now.

**Comment by peluse** [comment]
@jimharris I don't see anything wrong with the LBA range code and could not repro locally.  I added the LBA range info per thread to the debug output and changed the seed data from random to LBA to maybe provide a clue if it happens again.  See https://review.spdk.io/gerrit/c/spdk/spdk/+/5177

**Comment by peluse** [comment]
Has anyone seen this again? The patch to maybe provide a bit of a clue has been merged (the one above) but certainly no fixes.

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue has not occurred for three months and Paul added more debug information for easier tracking in case it happens again.
