### ISSUE TITLE
[build_queue] Patches run through CI multiple times

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1648]
Some of the builds occur twice for the same patch set.

## Link to the failed CI build

Patch set 12 twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/4338/

**Comment by tomzawadzki** [comment]
Patch set 1 twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/5526/1

**Comment by tomzawadzki** [comment]
Patch set 15 twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/1715/

**Comment by tomzawadzki** [comment]
Patch set 2 twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/6158

**Comment by jimharris** [comment]
Patch set 4 twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/6330

**Comment by tomzawadzki** [comment]
Patch sets 23 and 24 both ran twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/2693

**Comment by tomzawadzki** [comment]
Patch set 1 ran twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/6545/1

**Comment by tomzawadzki** [comment]
Patch set 4 ran twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/6617

**Comment by floatious** [comment]
Patch set 4 ran twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/7726/

Patch set 4 ran twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/7727/

**Comment by tomzawadzki** [comment]
[Bug scrub] This issue does not result in a build failure by itself, so reports are unreliable measure of how often it occurs. @karlatec will assign a person to give one last look at the CI scripts to figure out the cause.

**Comment by ksztyber** [comment]
Patch set 4 run twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/8403

Patch set 5 run twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/8405

Patch set 7 run twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/8406

**Comment by tomzawadzki** [comment]
Patch set 6 ran twice
https://review.spdk.io/gerrit/c/spdk/spdk/+/8288/6

**Comment by ksztyber** [comment]
Patch set 6 ran twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/8615

**Comment by ksztyber** [comment]
Patch set 1 ran twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/8842/1

**Comment by tomzawadzki** [comment]
Patch set 2 ran twice:
https://review.spdk.io/gerrit/c/spdk/spdk/+/8914/2

**Comment by xjjx** [comment]
This issue hit us about 5 to 10 times per day. After some investigation it seems that it was some race hazard type issue.
Fix has been implemented today, so we need to wait for verification.

**Comment by xjjx** [comment]
I gathered some statistics and seems that this issue hit us 461 in last 30 days.
It was finally solved in last week.

**Comment by tomzawadzki** [comment]
Patch set 4 https://review.spdk.io/gerrit/c/spdk/spdk/+/9390/4 ran twice.
Note a "prioritize change" request was put after a rebase.

@xjjx could you take a look ?

**Comment by jimharris** [comment]
@tomzawadzki @karlatec Do we know if this has been resolved?  I haven't really been watching for it, but there aren't any reports here for the last 4 months.

**Comment by tomzawadzki** [comment]
I believe it does. It just is never reported, since getting two sets of results are usually unnoticed.
Let me take a look through out next week, to spot such reports. If non show up, lets close.

**Comment by karlatec** [comment]
A week has passed, no new reports. Let's close this :)
