### ISSUE TITLE
[autotest-nightly] compilation errors for package build

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1652]
## Current Behavior

Compilation error when building SPDK package build. Discovered in nightly builds because we don't have a packaging build test in per-patch (yet; I will create a patch for that in a couple of minutes).

Failures in multiple builds:
https://ci.spdk.io/public_build/autotest-nightly_1613.html

## Steps to Reproduce

1. Build SPDK with configure options:
```
./configure --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --with-ocf --enable-ubsan --enable-asan --enable-coverage --enable-lto
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 214b9847d0fb37067f754f7481c4277c45525b8d

**Comment by changpe1** [comment]
duplicate with issue #1650, here is the fix.

**Comment by karlatec** [comment]
Duplicate of #1650
