### ISSUE TITLE
partition failed

### ISSUE THREAD

**Issue by beef9999** [spdk/spdk#1653]
### OS:
CentOS 7

### Version: 
v20.10.x

### Cmds:
./build/bin/spdk_tgt
./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:3b:00.0
./scripts/rpc.py nbd_start_disk Nvme0n1 /dev/nbd0
\# Use `parted` cmd to create the 1st GPT partition
> For example
>parted -a optimal -s /dev/nbd0  -- unit s mklabel gpt
>parted -a optimal -s /dev/nbd0  -- unit s mkpart primary ext2 0% 10%

### Output:
`lsblk` won't show a successful partition

### Questions:
1. Why no partitions could be seen immediately?
2. Will SPDK automatically create a GPT partition table for me when using bdev_split_create ?

**Comment by tomzawadzki** [comment]
Hi @beef9999 

1. Why no partitions could be seen immediately?
Have you made sure that nbd module is loaded (`modprobe nbd`) ?
Does `nbd_start_disk` RPC return success ?
Are there any errors in `spdk_tgt` output ?

2. Will SPDK automatically create a GPT partition table for me when using bdev_split_create ?
[Split bdev](https://spdk.io/doc/bdev.html#bdev_ug_split) does not use GPT. No data for split is preserved on disk. To recreate split bdev, the JSON configuration has to be saved and loaded on spdk_tgt restart (`--json` option).

**Comment by beef9999** [comment]
@tomzawadzki 
`nbd_start_disk` was succeeded because I could see /dev/nbd0 by `lsblk` in the first place.
But I didn't see the next /dev/nbd0p1 after making partition with `parted`

**Comment by beef9999** [comment]
As to how to recreate split bdev, is JSON the only supported config format? What about the plain text configure file?

**Comment by optimistyzy** [comment]
When a new bdev is created to be used, there will be some bdevs to check whether there are format (e.g., GPT, blobstore). I am thinking these are the checking format info printed in GPT.  Because you firstly formated the disk into GPT, then you use split. However the split operation does not change anything in the disk. So the GPT info in the disk may still be exist (in the first split bdev).
