### ISSUE TITLE
Does the vhost user blk device use the virtio 1.0 protocol?

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1656]
I use a centos 6.8 virtual machine [kernel version 2.6.x]. After the vhost user blk device is configured, the virtual machine cannot be started. After removing the device, it starts normally. When I upgraded the kernel of this virtual machine to 3.10.x, there was no problem so.

I checked the differences in some directories of the two different versions of the kernel：
`cat /usr/src/kernels/2.6.32-642.15.1.el6.x86_64/drivers/virtio/Makefile 

obj-$(CONFIG_VIRTIO) += virtio.o
obj-$(CONFIG_VIRTIO_RING) += virtio_ring.o
obj-$(CONFIG_VIRTIO_PCI) += virtio_pci.o
obj-$(CONFIG_VIRTIO_BALLOON) += virtio_balloon.o`

`cat /usr/src/kernels/3.10.0-327.8.0.0.el6.ksyun.x86_64/drivers/virtio/Makefile

obj-$(CONFIG_VIRTIO) += virtio.o virtio_ring.o
obj-$(CONFIG_VIRTIO_MMIO) += virtio_mmio.o
obj-$(CONFIG_VIRTIO_PCI) += virtio_pci.o
virtio_pci-y := virtio_pci_modern.o virtio_pci_common.o
virtio_pci-$(CONFIG_VIRTIO_PCI_LEGACY) += virtio_pci_legacy.o
obj-$(CONFIG_VIRTIO_BALLOON) += virtio_balloon.o
obj-$(CONFIG_VIRTIO_INPUT) += virtio_input.o`

So it may be caused by the unsupported protocol?

Thanks
    su

**Comment by changpe1** [comment]
@zlsh007 Yes, SPDK vhost user blk can support virtio 1.0, if your kernel driver is using virtio 0.95 or legacy mode, SPDK can't support that.

For more debug information, you may boot to your CentOS 6.8 kernel without this device , and add this device via QMP command, then the kernel may report the error log.

**Comment by zlsh007** [comment]
@changpe1 Thanks a lot!
