### ISSUE TITLE
Why are huge pages created in multiple directories?

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1660]
When I only have one mount point for /dev/hugepages, the huge page specified by the -s parameter of the spdk process is created in this directory, but when I create two other mount points /mnt/huge_1GB /mnt/huge_2MB.

After that, huge pages will be created both in the /dev/hugepages and /mnt/huge_1GB directories.

Although the --huge-dir parameter can be used to specify that huge pages are created under a certain directory, I want to know why huge pages of the same size are created under two directories without this parameter.

## Expected Behavior
Create huge pages only under one directory.

## Current Behavior
Will be created in /dev/hugepages and /mnt/huge_1GB.

mount info:
mount | grep huge
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
nodev on /mnt/huge_1GB type hugetlbfs (rw,relatime,pagesize=1GB)
nodev on /mnt/huge_2MB type hugetlbfs (rw,relatime,pagesize=2MB)

## Steps to Reproduce
1: echo 2048 > /proc/sys/vm/nr_hugepages  &  only mount /dev/hugepages 
2: app/vhost/vhost -c ./xxx.conf -i 0 -r /var/tmp/spdk.sock -S /var/tmp/ -s 1024
3: Because the system creates 2MB large pages by default, 512 large page files will be found under /dev/hugepages
4: mount /mnt/huge_1GB  & echo 4 > /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
5: kill app/vhost/vhost & app/vhost/vhost -c ./xxx.conf -i 0 -r /var/tmp/spdk.sock -S /var/tmp/ -s 1024
6: At this time we will see that there are 512 2MB large page files under /dev/hugepages, and there is a 1GB large page file under /mnt/huge_1GB

Thanks
    su

**Comment by changpe1** [comment]
[Bug Scrub] I will try to reproduce this issue.

**Comment by changpe1** [comment]
@zlsh007 By default, SPDK will not unlink the mapped huge files, the mapped hugefiles will be cleaned for the next startup, but you can enable "-R, --huge-unlink" option in SPDK. This should not be a bug.

**Comment by zlsh007** [comment]
@changpe1 Maybe I have described some problems. The actual problem is this: before the spdk service starts, first mount /dev/hugepages and /mnt/huge_2MB /mnt/huge_1GB, and then start the spdk service, for example, we configure 1GB HUGEPAGE, and Without specifying the huge page directory, after the service is started, 512 2MB huge pages will be created in /dev/hugepages and a 1GB huge page will be created in /mnt/huge_1GB. Huge pages with a total size of 1GB are created under both directories.

**Comment by changpe1** [comment]
@zlsh007 I can't reproduce this issue in my local environment, if both 2MiB and 1GiB huge pages were mounted, the application will choose the 2MiB one. after you killed the vhost application, the files in the mount point will be cleared in my environment.

**Comment by changpe1** [comment]
@zlsh007 can you try the latest version? I used the master branch.

**Comment by zlsh007** [comment]
@changpe1 Ok i will try it, thanks

**Comment by changpe1** [comment]
@zlsh007 do you have any update for the issue?

**Comment by zlsh007** [comment]
@changpe1 Sorry for taking so long to reply, there is no new progress at present, I will close it first, and wait for new information to add.
