### ISSUE TITLE
Autobuild failed at external_make_tc1

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1662]
# Issue
```
************************************
START TEST external_make_tc1
************************************
 02:22:42       # xtrace_enable
 02:22:42       # make -C /git_repos/spdk_repo/spdk/test/external_code hello_world_bdev_shared_combo
make: Entering directory '/git_repos/spdk_repo/spdk/test/external_code'
make --directory=passthru shared
make[1]: Entering directory '/git_repos/spdk_repo/spdk/test/external_code/passthru'
cc -I/git_repos/spdk_repo/spdk/include -L/git_repos/spdk_repo/spdk/build/lib -L/git_repos/spdk_repo/spdk/dpdk/build/lib -c -fPIC ./vbdev_passthru_rpc.c -o ./vbdev_passthru_rpc.o
cc -I/git_repos/spdk_repo/spdk/include -L/git_repos/spdk_repo/spdk/build/lib -L/git_repos/spdk_repo/spdk/dpdk/build/lib -c -fPIC ./vbdev_passthru.c -o ./vbdev_passthru.o
cc -I/git_repos/spdk_repo/spdk/include -L/git_repos/spdk_repo/spdk/build/lib -L/git_repos/spdk_repo/spdk/dpdk/build/lib -shared ./vbdev_passthru_rpc.o ./vbdev_passthru.o -o ./libpassthru_external.so
make[1]: Leaving directory '/git_repos/spdk_repo/spdk/test/external_code/passthru'
make --directory=hello_world bdev_shared_combo
make[1]: Entering directory '/git_repos/spdk_repo/spdk/test/external_code/hello_world'
cc -I/git_repos/spdk_repo/spdk/include -L/git_repos/spdk_repo/spdk/build/lib -L/git_repos/spdk_repo/spdk/dpdk/build/lib -L../passthru -Wl,-rpath=/git_repos/spdk_repo/spdk/build/lib,--no-as-needed -o hello_bdev ./hello_bdev.c -lpassthru_external \
-lspdk -lspdk_env_dpdk -lrte_eal -lrte_mempool -lrte_ring -lrte_mbuf -lrte_mempool_ring -lrte_pci -lrte_bus_pci -lrte_kvargs -lrte_vhost -lrte_net -lrte_hash -lrte_telemetry -lrte_cryptodev -lrte_power -lrte_rcu -Wl,--no-whole-archive
/usr/sbin/ld: cannot find libspdk_accel_idxd.so
/usr/sbin/ld: cannot find libspdk_bdev_iscsi.so
/usr/sbin/ld: cannot find libspdk_bdev_pmem.so
/usr/sbin/ld: cannot find libspdk_idxd.so
/usr/sbin/ld: cannot find libspdk_rdma.so
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:40: bdev_shared_combo] Error 1
make[1]: Leaving directory '/git_repos/spdk_repo/spdk/test/external_code/hello_world'
make: *** [Makefile:55: hello_world_bdev_shared_combo] Error 2
make: Leaving directory '/git_repos/spdk_repo/spdk/test/external_code'
  02:22:42      # trap - ERR
  02:22:42      # print_backtrace
  02:22:42      # [[ ehxBET =~ e ]]
  02:22:42      # args=("${BASH_ARGV[@]}")
  02:22:42      # local args
  02:22:42      # xtrace_disable
  02:22:42      # '[' no '!=' yes ']'
  02:22:42      # PREV_BASH_OPTS=ehxBET
  02:22:42      # [[ ehxBET == *\x* ]]
  02:22:42      # XTRACE_DISABLED=yes
  02:22:42      # set +x
========== Backtrace start: ==========

in /git_repos/spdk_repo/spdk/test/external_code/../../test/common/autotest_common.sh:942 -> run_test(["external_make_tc1"],["make"],["-C"],["/git_repos/spdk_repo/spdk/test/external_code"],["hello_world_bdev_shared_combo"])
     ...
   937          timing_enter $test_name
   938          echo "************************************"
   939          echo "START TEST $test_name"
   940          echo "************************************"
   941          xtrace_restore
=> 942          time "$@"
   943          xtrace_disable
   944          echo "************************************"
   945          echo "END TEST $test_name"
   946          echo "************************************"
   947          timing_exit $test_name
     ...
in /git_repos/spdk_repo/spdk/test/external_code/test_make.sh:23 -> main(["/git_repos/spdk_repo/spdk"])
     ...
   18   export SPDK_LIB_DIR="$SPDK_DIR/build/lib"
   19   export DPDK_LIB_DIR="${SPDK_RUN_EXTERNAL_DPDK:-$SPDK_DIR/dpdk/build}/lib"
   20   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SPDK_LIB_DIR:$DPDK_LIB_DIR:"$test_root/passthru"
   21
   22   # The default target is to make both the app and bdev and link them against the combined SPDK shared library libspdk.so.
=> 23   run_test "external_make_tc1" make -C $test_root hello_world_bdev_shared_combo
   24   run_test "external_run_tc1" $test_root/hello_world/hello_bdev --json $test_root/hello_world/bdev_external.json -b TestPT
   25
   26   make -C $test_root clean
   27
   28   # Make just the application linked against the combined SPDK shared library libspdk.so.
     ...
```
with config:
```
SPDK_RUN_VALGRIND=1
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_UNITTEST=0
SPDK_TEST_AUTOBUILD=1
SPDK_TEST_NVME=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_NVMF=1
SPDK_TEST_PMDK=1
SPDK_TEST_JSON=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1

```

## Context (Environment including OS version, SPDK version, etc.)

`Linux clearlinux-cloud-1602846708-e3f08eef8 5.4.71-71.lts2019 `
`Fedora28 5.0.16-100.fc28.x86_64`
add patch serials  or not : 

commit e2ecceaca29532c6f980164447a0e2e9a1b053cd
Author: Jim Harris <james.r.harris@intel.com>
Date:   Wed Oct 28 17:27:13 2020 +0000

    env_dpdk: add rte_rcu library dependency

    rte_hash depends on rte_rcu starting in upcoming
    DPDK 20.11 release.  rte_rcu was only added in
    DPDK 19.05 release, so we need to check if it
    exists before linking it.

    Fixes issue #1661.

    Signed-off-by: Jim Harris <james.r.harris@intel.com>
    Change-Id: I7e343c6f964b03cc62484b57803a3bad00f80288

commit 9be0756a9340ea7d34b7d4dd3597f31932052863
Author: Jim Harris <james.r.harris@intel.com>
Date:   Wed Oct 28 21:50:40 2020 +0000

    dpdk: move submodule to build rte_rcu library

    Signed-off-by: Jim Harris <james.r.harris@intel.com>
    Change-Id: Ie38573774612ac7ec7cf23367d3233124acd1a66

commit 188ab0f4eda9676a490d114e070922eaa9308edc
Author: Jim Harris <james.r.harris@intel.com>
Date:   Wed Oct 28 17:30:43 2020 +0000

    test/external_code: use variable to hold DPDK lib list

    Signed-off-by: Jim Harris <james.r.harris@intel.com>
    Change-Id: Ie4a489926695cc56125f0e18796071f7730190f1

commit c4c37f1cf1c9ba7dc6596c8cb667eac2e3e3c0ef (origin/master, origin/HEAD)
Author: Maciej Wawryk <maciejx.wawryk@intel.com>
Date:   Wed Oct 7 16:16:34 2020 +0200

    Modifications for using universal qcow2 image in tests

    We want to replace few qcow2 images with one universal.
    This commit contains:
     - change password in autotest.sh
     - change image path
     - change image name
     - use snapshot mode in hotplug.sh instead of copying base image

    Signed-off-by: Maciej Wawryk <maciejx.wawryk@intel.com>
    Change-Id: I75c457fe75f005b0ab43ca909be7886529ed115b
    Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/4551
    Reviewed-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
    Reviewed-by: Pawel Piatek <pawelx.piatek@intel.com>
    Reviewed-by: Jim Harris <james.r.harris@intel.com>
    Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
    Community-CI: Mellanox Build Bot
```

**Comment by changpe1** [comment]
[Bug Scrub] Assign it to Jim now.

**Comment by jimharris** [comment]
I needed three patches to get this all working in my Ubuntu VM.  The last patch is here: https://review.spdk.io/gerrit/c/spdk/spdk/+/4970

Patch #1 I already had as part of the #1613 debug.  This ensures that the shared library dependencies get written into the final .so in all cases.

Patch #2 I also already had as part of some pkgconfig work I've been doing.  The check_so_deps.sh script modifies one of the Makefiles as part of detecting so dependencies - and in this failure case, that change never gets reverted!  So then if you do a make clean and run autobuild.sh again, the external_code tests fail because it only links in the leaf libraries and assumes those libraries have their dependencies embedded.

Patch #3 adds a "make clean" before building for the external_code tests.  For these two issues (#1662 and #1665) the .conf file specifies options that the external_code tests do not use.  This means that if we first build based on the conf file it may enable something like the iscsi initiator module.  Then later the external_code test_make.sh script builds again, but if it isn't cleaned first, the composite libspdk.so will still reference that iscsi initiator module.  The external_code Makefiles don't account for these libraries and don't include the system libraries they depend on.  So we need to "make clean" to ensure we start from a fresh state.

**Comment by yidong0635** [comment]
verified, test_make.sh is ok.

**Comment by yidong0635** [comment]
close this one, since patch was merged.
