### ISSUE TITLE
[unittest-vg-autotest] Build timed out (after 20 minutes). Marking the build as failed

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1663]
fail log shows：
START TEST scanbuild_make
00:08:14.018  ************************************
00:08:14.018   07:45:13	$ xtrace_enable
00:08:14.018   07:45:13	$ scanbuild_make
00:08:14.018   07:45:13	$ pass=true
00:08:14.019   07:45:13	$ scan-build -o /home/vagrant/spdk_repo/spdk/../output/scan-build-tmp --exclude /home/vagrant/spdk_repo/spdk/dpdk/ --status-bugs make -j10
00:11:31.395  In file included from vbdev_crypto.c:45:
00:11:31.395  In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_crypto.h:25:
00:11:31.395  /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_crypto_sym.h:935:4: warning: Value stored to 'left' is never read
00:11:31.395                          left = 0;
00:11:31.395                          ^      ~
00:11:31.395  1 warning generated.
00:12:39.678   07:49:39	$ rm -rf /home/vagrant/spdk_repo/spdk/../output/scan-build-tmp
00:12:39.690   07:49:39	$ xtrace_disable
00:12:39.690   07:49:39	$ '[' no '!=' yes ']'
00:12:39.690   07:49:39	$ PREV_BASH_OPTS=ehxBET
00:12:39.690   07:49:39	$ [[ ehxBET == *\x* ]]
00:12:39.690   07:49:39	$ XTRACE_DISABLED=yes
00:12:39.690   07:49:39	$ set +x
00:12:53.701   07:49:53	$ xtrace_enable
00:12:53.701   07:49:53	$ grep -E 'CC|CXX' /home/vagrant/spdk_repo/spdk/../output/build_output.txt
00:12:53.701   07:49:53	$ sed 's/\s\s\(CC\|CXX\)\s//g'
00:12:53.702   07:49:53	$ sed 's/\.o//g'
00:12:53.711   07:49:53	$ cat /home/vagrant/spdk_repo/spdk/test/common/skipped_build_files.txt
00:12:53.714   07:49:53	$ sort -o /home/vagrant/spdk_repo/spdk/../output/all_c_files.txt /home/vagrant/spdk_repo/spdk/../output/all_c_files.txt
00:12:53.724   07:49:53	$ sort -o /home/vagrant/spdk_repo/spdk/../output/built_c_files.txt /home/vagrant/spdk_repo/spdk/../output/built_c_files.txt
00:12:53.734   07:49:53	$ comm -2 -3 /home/vagrant/spdk_repo/spdk/../output/all_c_files.txt /home/vagrant/spdk_repo/spdk/../output/built_c_files.txt
00:12:53.744    07:49:53	$ wc -l
00:12:53.750   07:49:53	$ '[' 0 -ge 1 ']'
00:12:53.750   07:49:53	$ true
00:12:53.750  
00:12:53.750  real	4m39.724s
00:12:53.750  user	23m44.361s
00:12:53.750  sys	2m55.249s
00:12:53.750   07:49:53	$ xtrace_disable
00:12:53.750   07:49:53	$ '[' no '!=' yes ']'
00:12:53.750   07:49:53	$ PREV_BASH_OPTS=ehxBET
00:12:53.751   07:49:53	$ [[ ehxBET == *\x* ]]
00:12:53.751   07:49:53	$ XTRACE_DISABLED=yes
00:12:53.751   07:49:53	$ set +x
00:12:53.751  ************************************
00:12:53.751  END TEST scanbuild_make
00:12:53.751  ************************************
00:12:53.785   07:49:53	$ xtrace_enable
00:12:53.785   07:49:53	$ run_test autobuild_generated_files_check porcelain_check
00:12:53.786   07:49:53	$ '[' 2 -le 1 ']'
00:12:53.786   07:49:53	$ xtrace_disable
00:12:53.786   07:49:53	$ '[' no '!=' yes ']'
00:12:53.786   07:49:53	$ PREV_BASH_OPTS=ehxBET
00:12:53.786   07:49:53	$ [[ ehxBET == *\x* ]]
00:12:53.786   07:49:53	$ XTRACE_DISABLED=yes
00:12:53.786   07:49:53	$ set +x
00:12:53.790  ************************************
00:12:53.790  START TEST autobuild_generated_files_check
00:12:53.790  ************************************
00:12:53.790   07:49:53	$ xtrace_enable
00:12:53.790   07:49:53	$ porcelain_check
00:12:53.792    07:49:53	$ git status --porcelain --ignore-submodules
00:12:53.792    07:49:53	$ wc -l
00:12:53.820   07:49:53	$ '[' 0 -ne 0 ']'
00:12:53.820  
00:12:53.820  real	0m0.030s
00:12:53.820  user	0m0.010s
00:12:53.820  sys	0m0.021s
00:12:53.820   07:49:53	$ xtrace_disable
00:12:53.820   07:49:53	$ '[' no '!=' yes ']'
00:12:53.820   07:49:53	$ PREV_BASH_OPTS=ehxBET
00:12:53.821   07:49:53	$ [[ ehxBET == *\x* ]]
00:12:53.821   07:49:53	$ XTRACE_DISABLED=yes
00:12:53.821   07:49:53	$ set +x
00:12:53.821  ************************************
00:12:53.821  END TEST autobuild_generated_files_check
00:12:53.821  ************************************
00:12:53.850   07:49:53	$ xtrace_enable
00:12:53.850   07:49:53	$ run_test autobuild_header_dependency_check header_dependency_check
00:12:53.850   07:49:53	$ '[' 2 -le 1 ']'
00:12:53.850   07:49:53	$ xtrace_disable
00:12:53.850   07:49:53	$ '[' no '!=' yes ']'
00:12:53.850   07:49:53	$ PREV_BASH_OPTS=ehxBET
00:12:53.850   07:49:53	$ [[ ehxBET == *\x* ]]
00:12:53.850   07:49:53	$ XTRACE_DISABLED=yes
00:12:53.850   07:49:53	$ set +x
00:12:53.854  ************************************
00:12:53.854  START TEST autobuild_header_dependency_check
00:12:53.854  ************************************
00:12:53.854   07:49:53	$ xtrace_enable
00:12:53.854   07:49:53	$ header_dependency_check
00:12:53.855    07:49:53	$ stat /home/vagrant/spdk_repo/spdk/build/bin/spdk_tgt
00:12:53.869   07:49:53	$ STAT1='  File: /home/vagrant/spdk_repo/spdk/build/bin/spdk_tgt
00:12:53.869    Size: 66758088  	Blocks: 130392     IO Block: 4096   regular file
00:12:53.869  Device: fc03h/64515d	Inode: 33576188    Links: 1
00:12:53.869  Access: (0755/-rwxr-xr-x)  Uid: ( 1000/ vagrant)   Gid: ( 1000/ vagrant)
00:12:53.869  Context: unconfined_u:object_r:user_home_t:s0
00:12:53.869  Access: 2020-10-29 07:48:49.620586606 +0000
00:12:53.869  Modify: 2020-10-29 07:48:49.943579940 +0000
00:12:53.869  Change: 2020-10-29 07:48:49.943579940 +0000
00:12:53.869   Birth: 2020-10-29 07:48:48.182616280 +0000'
00:12:53.869   07:49:53	$ sleep 1
00:12:54.871   07:49:54	$ touch lib/nvme/nvme_internal.h
00:12:54.873   07:49:54	$ make -j10
00:20:00.211  Build timed out (after 20 minutes). Marking the build as failed.

**Comment by glodfish-zg** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29804.html
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29801.html
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29803.html
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29802.html

**Comment by mikeBashStuff** [comment]
This probably happened at the time when PE1 run out of storage some time ago. Haven't seen similar timeouts since then, closing for now.
