### ISSUE TITLE
format of hostnqn sent by perf does not start with 'nqn'

### ISSUE THREAD

**Issue by eyuval** [spdk/spdk#1669]
I see in the code (nvme_ctrlr.c) that the hostnqn sent by SPDK in the connect command is initialized as follows:

snprintf(opts->hostnqn, sizeof(opts->hostnqn), "2014-08.org.nvmexpress:uuid:%s", host_id_str);

This seems to be in contradiction with section 7.9 of the nvme express specification, which states, that it should start with the string 'nqn'. This is relevant for me, since I want to check in the target whether the connecting host (e.g. spdk perf) provides a valid nqn.

**Comment by yidong0635** [comment]
Host NVMe Qualified Name (HOSTNQN):  NVMe Qualified Name (NQN) that uniquely identifies the host. Refer to section 7.9 of the NVMe Base specification .
If  it means there're some missing prefixes about "nqn"?

**Comment by eyuval** [comment]
I think the nqn is missing, because 7.9 of the nvme spec states, that both formats need to start with nqn. My problem is actually the following: A customer pointed out to me, that the host  (nvme cli) can provide an invalid hostnqn in the fabric connect data. I wanted to fix this problem in the SPDK target code by adding the following check in the function spdk_nvmf_ctrlr_connect:

      if (!spdk_nvmf_valid_nqn(hostnqn)) {
                SPDK_ERRLOG("Connect HOSTNQN %s invalid format\n", hostnqn);
                SPDK_NVMF_INVALID_CONNECT_DATA(rsp, hostnqn);
                return SPDK_NVMF_REQUEST_EXEC_STATUS_COMPLETE;
        }

This fixed the problem for linux kernel client, but I saw , that the hostnqn sent by spdk perf is rejected by this validity check.

**Comment by jimharris** [comment]
Good catch @eyuval.  This is a bug.  I'll push a fix shortly.

**Comment by changpe1** [comment]
Patch has been merged, so closing this issue for now.
