### ISSUE TITLE
[autotest] libvirt error Cannot allocate memory

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1670]
error message:

There was an error talking to Libvirt. The error message is shown
00:00:37.884  below:
00:00:37.884  
00:00:37.884  Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: qemu-system-x86_64: -realtime mlock=off: warning: '-realtime mlock=...' is deprecated, please use '-overcommit mem-lock=...' instead
00:00:37.884  2020-11-02T07:23:04.418862Z qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory
00:00:37.916  + cd fedora31-libvirt
00:00:37.916  + vagrant destroy -f
00:00:40.921  ==> default: Removing domain...
00:00:40.987  Build step 'Execute shell' marked build as failure
00:00:41.082  [PostBuildScript] - [INFO] Executing post build scripts.
00:00:41.089  [iscsi-vg-autotest@2] $ /usr/bin/env bash /tmp/jenkins4791817236705560966.sh
00:00:41.093  + [[ -n fedora31 ]]
00:00:41.094  + mv /var/jenkins/workspace/iscsi-vg-autotest@2/fedora31-libvirt/output /var/jenkins/workspace/iscsi-vg-autotest@2/output
00:00:41.111  [iscsi-vg-autotest@2] $ /usr/bin/env bash /tmp/jenkins4750765860119054565.sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29934.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29933.html

**Comment by jimharris** [comment]
FYI - this is the same issue as #1639 and #1644 that were previously closed.  Perhaps we should reopen #1639 and close this issue? #1639 has a lot more history on it.

**Comment by karlatec** [comment]
@jimharris I agree, let's use #1639

**Comment by jimharris** [comment]
Copied reports to #1639 and re-opened that issue.
