### ISSUE TITLE
build should depend on a specific liburing hash or tag

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#1673]
## Expected Behavior

I should be able to have reproducible builds despite some upstream repo making incompatible changes in master.

## Current Behavior

See https://gitlab.com/mgerdts/docker-spdk/-/jobs/830785558

```
queue.c: In function '__io_uring_get_cqe':
queue.c:136:4: error: 'struct get_data' has no member named 'extra_flags'; did you mean 'get_flags'?
   .extra_flags = 0,
    ^~~~~~~~~~~
    get_flags
queue.c: In function 'io_uring_wait_cqes_new':
queue.c:236:4: error: 'struct get_data' has no member named 'extra_flags'; did you mean 'get_flags'?
   .extra_flags = ts ? IORING_ENTER_GETEVENTS_TIMEOUT : 0,
    ^~~~~~~~~~~
    get_flags
make[1]: *** [Makefile:45: queue.ol] Error 1
```

A couple hours earlier earlier, this breakage happened in the liburing repo.

https://github.com/axboe/liburing/commit/0de9d8c06d21c0d0d84608119b3dd1bfa53fb776

And the fix came in a bit later.

https://github.com/axboe/liburing/commit/5a7c8ac028dbf9ba548c9689f9840a1a1e6d2b08

## Possible Solution

In `/scripts/pkgdep/common.sh`, use one of the release tags when checking out from the liburing repo or add liburing to the list of dependency packages that are automatically installed.

Workaround:

```
dnf install -y liburing
```

## Steps to Reproduce

It should be reproducible with
```
docker build --no-cache -t spdk:broken https://gitlab.com/mgerdts/docker-spdk/-/raw/ea4a1f8e162a01ab8714d0ef4bb1d41bed328494/centos8/Dockerfile
```

But it's not because as I was verifying that this reproduces the bug, a fix was applied to the master branch of the repo that spdk depends on.

## Context (Environment including OS version, SPDK version, etc.)

See dockerfile mentioned above.

**Comment by mikeBashStuff** [comment]
The problem with `liburing` is that not every supported distro provides a package for it, unfortunately. But the idea of checking out to a specific release sounds good to me (or fetching source bundle for a specific version directly, instead of cloning the entire repo). The question now is which release we should use. @tomzawadzki @Maciej-Szwed would you kindly provide any feedback on the matter?

We should probably also review `pkgdep/git` to make sure similar issues can be avoided for other sources which are in use.

**Comment by jimharris** [comment]
Jens has liburing-x.y tags in his repo - I'd say just use the latest one of those.

It's liburing-0.7 from July, so it's a bit out of date but I think that's fine for the pkgdep script.  If someone wants something more up to date, they have the option of building and installing themselves from whatever commit they choose.

**Comment by jimharris** [comment]
Looks like Jens is planning a 2.0 release soon: https://github.com/axboe/liburing/issues/228

Not sure why it is jumping from 0.7 to 2.0, but we'd probably want to move to that 2.0 tag once it's available.

**Comment by tomzawadzki** [comment]
[Bug scrub] Since 2.0 might be some months away and 0.7 is quite old at this point, lets point to specific commit on liburing on master.

**Comment by mikeBashStuff** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/5058 - points at the latest commit from the master as of now. Tested under different distros, shipped with different versions of the compiler. Seems to be stable.

**Comment by tomzawadzki** [comment]
Patch that points to specific liburing commit was merged. This should be sufficient for resolving this issue.
