### ISSUE TITLE
blob_io_wait times out on last wait()

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1675]
https://ci.spdk.io/results/autotest-per-patch/builds/30131/archive/lvol-vg-autotest/build.log

Build timed out after second `bdevperf` run while test was `wait()`ing for the process to finish. Point of failure:
```
00:06:43.984   09:47:21	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_enable_histogram aio0 -d
00:06:44.142   09:47:21	# wait 25606
00:06:46.332  
 Thread name: 76e05148-959a-43a0-b2fa-89b2151
00:06:46.332  
 Core Mask: 0x1
00:06:46.332  
 76e05148-959a-43a0-b2fa-89b2151d5acb:    3986.40 IOPS      15.57 MiB/s
00:06:46.332  
 =====================================================
00:06:46.332  
 Total               :    3986.40 IOPS      15.57 MiB/s
00:06:46.332  [2020-11-09 09:47:23.438466] bdev.c:1479:bdev_finish_unregister_bdevs_iter: *WARNING*: Unregistering claimed bdev 'aio0'!
00:06:46.718   09:47:23	# bdev_perf_pid=25618
00:06:46.718   09:47:23	# /home/vagrant/spdk_repo/spdk/test/bdev/bdevperf/bdevperf --json /home/vagrant/spdk_repo/spdk/test/blobstore/blob_io_wait/bdevperf.json -q 128 -o 4096 -w read -t 5 -r /var/tmp/spdk.sock
00:06:46.718   09:47:23	# waitforlisten 25618
00:06:46.718   09:47:23	# '[' -z 25618 ']'
00:06:46.718   09:47:23	# local rpc_addr=/var/tmp/spdk.sock
00:06:46.718   09:47:23	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:06:46.718  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:06:46.718   09:47:23	# xtrace_disable
00:06:46.718   09:47:23	# '[' no '!=' yes ']'
00:06:46.718   09:47:23	# PREV_BASH_OPTS=ehxBET
00:06:46.718   09:47:23	# [[ ehxBET == *\x* ]]
00:06:46.718   09:47:23	# XTRACE_DISABLED=yes
00:06:46.718   09:47:23	# set +x
00:06:46.778  [2020-11-09 09:47:23.884549] Starting SPDK v21.01-pre git sha1 d7005937b / DPDK 20.08.0 initialization...
00:06:46.778  [2020-11-09 09:47:23.884881] [ DPDK EAL parameters: [2020-11-09 09:47:23.884918] bdevperf [2020-11-09 09:47:23.884944] --no-shconf [2020-11-09 09:47:23.884963] -c 0x1 [2020-11-09 09:47:23.884986] --log-level=lib.eal:6 [2020-11-09 09:47:23.885004] --log-level=lib.cryptodev:5 [2020-11-09 09:47:23.885044] --log-level=user1:6 [2020-11-09 09:47:23.885062] --iova-mode=pa [2020-11-09 09:47:23.885085] --base-virtaddr=0x200000000000 [2020-11-09 09:47:23.885103] --match-allocations [2020-11-09 09:47:23.885210] --file-prefix=spdk_pid25618 [2020-11-09 09:47:23.885229] ]
00:06:46.791  EAL: No available hugepages reported in hugepages-1048576kB
00:06:46.897  EAL: No legacy callbacks, legacy socket not created
00:06:46.916  [2020-11-09 09:47:24.022600] app.c: 462:spdk_app_start: *NOTICE*: Total cores available: 1
00:06:47.183  [2020-11-09 09:47:24.289318] reactor.c: 696:reactor_run: *NOTICE*: Reactor started on core 0
00:06:47.208  [2020-11-09 09:47:24.314925] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:06:47.297  Running I/O for 5 seconds...
00:06:47.629   09:47:24	# xtrace_enable
00:06:47.629   09:47:24	# (( i == 0 ))
00:06:47.629   09:47:24	# return 0
00:06:47.629   09:47:24	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_enable_histogram aio0 -e
00:06:47.845   09:47:24	# sleep 2
00:06:49.848   09:47:26	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_get_histogram aio0
00:06:49.849   09:47:26	# /home/vagrant/spdk_repo/spdk/scripts/histogram.py
00:06:50.067  Latency histogram
00:06:50.067  ==============================================================================
00:06:50.067         Range in us     Cumulative    IO count
00:06:50.072   09:47:27	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_enable_histogram aio0 -d
00:06:50.272   09:47:27	# wait 25618
00:15:00.393  Build timed out (after 15 minutes). Marking the build as failed.
00:15:00.404  Build was aborted
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_30131.html

**Comment by changpe1** [comment]
[Bug Scrub] mark it as intermittent failure now, let's wait to see if any more failures.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_30201.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_30252.html

**Comment by shuhei-matsumoto** [comment]
Rui Chang submitted a patch to an intermittent failure very similar with this issue.
 https://review.spdk.io/gerrit/c/spdk/spdk/+/5093

I asked Rui to take a look at this issue.

**Comment by changruinj** [comment]
Yes, same issue as I am trying to fix in https://review.spdk.io/gerrit/c/spdk/spdk/+/5093

**Comment by shuhei-matsumoto** [comment]
Got it. Thank you @changruinj. Will you take a look at the test pool logs? The patch might cause another failure.

**Comment by changruinj** [comment]
Sure, looking at it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @floatious. log: https://ci.spdk.io/public_build/autotest-per-patch_30342.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @floatious. log: https://ci.spdk.io/public_build/autotest-per-patch_30477.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_30779.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_31141.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mkenguva. log: https://ci.spdk.io/public_build/autotest-per-patch_31523.html

**Comment by yidong0635** [comment]
Issue can be reproduced locally.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_31738.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_31703.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_31783.html

**Comment by yidong0635** [comment]
I found that :
sometimes in bdevperf  :  `bdev=  spdk_bdev_first_leaf()`  is NULL, then `job_config_list `is NULL, that can't create a thread job. and hold there.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_31843.html

**Comment by yidong0635** [comment]
@tomzawadzki  I just saw that you had patches about this, if you are ready, please let me to check it, it easy to reproduce  for me.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_32423.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_32525.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_32648.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_33292.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_33586.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_33739.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_33810.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_33942.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_34005.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_34035.html
