### ISSUE TITLE
iSCSI initiator failed to login to the cached target node after SPDK iSCSI target application restarts

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1676]
If SPDK iSCSI target application restarts while iSCSI host caches discovered target, the iSCSI host intermittently failed to re-login discovered targets.

The reason is as follows:
iSCSI target application configures by the following ordering.
1. Portal group 1 is added first.
2. Target node A is created by associating with the portal group 1.

If iSCSI host tries to login to the target node A via portal group 1 between the step 1 and the step 2, portal group 1 is already opened and so iSCSI target application accepts the login request, but target node A is not added yet, and login request is failed.

## Expected Behavior

iSCSI host successfully login to the discovered targets even if SPDK iSCSI target application restarts.

## Current Behavior

See above

## Possible Solution

SPDK iSCSI target application allows iSCSI target node to be created even if the specified portal group is not found, and then associates portal group with the target node later when the portal group is added.

We can disaggregate the RPC, iscsi_create_target_node into multiple RPCs like SPDK nvmf library, but it will require the existing users to accept large changes. We should avoid that.
 
## Steps to Reproduce

See above

## Context (Environment including OS version, SPDK version, etc.)

Reported by SPDK 20.01 but even the latest master will have the same issue.

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris 

I got another idea. How about this?
When we create a portal group, we test if we can listen all portals in the portal group, and then immediately close all portals.
Then later, when the first target node is created and associated with the portal group (i.e. the reference count of the portal group is changed 0 to 1), we start listening all portals in the portal group, or when the last target node is deleted and disassociated with the portal group (i.e., the reference count of the portal group is changed 1 to 0), we stop listening all portals.

The first idea was as follows:
we allow users to swap two RPC calls, iscsi_create_target_node and iscsi_create_portal_group, i.e., we allow target node to be created even if any associating portal group does not exist.

The first idea worked but the patch size was not small and required usage of RPCs.

-Shuhei

**Comment by shuhei-matsumoto** [comment]
The third idea may be to just pause acceptor poller while no target node is associated with the portal group, but this may cause timeout error to iSCSI initiator, or I'm afraid any negative side effect on this.

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris 

I'm leaning toward the third idea. If we don't call accept(), we can ignore socket activity and defer any acceptance until we are ready. The backlog queue is limited and if it is full, further connection attempts are dropped.

In our use case, one portal group is associated with multiple target nodes, and at startup, we load multiple target nodes and want to start listening after all target nodes are loaded.

Hence how about adding two RPCs, iscsi_pause_portal_group and iscsi_resume_portal_group?

**Comment by jimharris** [comment]
Hi @shuhei-matsumoto,

Do we still have the race condition between iscsi_create_portal_group and iscsi_pause_portal_group?  Maybe we would need a parameter to iscsi_create_portal_group to say that it should start in paused state.

Which iSCSI host are you using?  I thought that Linux would continue to retry, even if it connects and login fails.  But it has been a long time since I've tested that.

-Jim

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris 

The issue has been caused by Windows hosts.

And adding an new option to creare_portal_group will be better. I think race condition is not fixed completely

**Comment by shuhei-matsumoto** [comment]
My colleague reported that windows hosts didn’t retry login in his case

**Comment by jimharris** [comment]
OK, thanks Shuhei.  I think we should go with the create_portal_group option.

**Comment by shuhei-matsumoto** [comment]
Hi Jim and all,

The patches are ready to review, starting from https://review.spdk.io/gerrit/c/spdk/spdk/+/5088/1
Please review them when you can.

-Shuhei

**Comment by jimharris** [comment]
Hi @shuhei-matsumoto,

Overall the patches look good.  I added some comments on the last two patches in the series.

-Jim

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris 

Thanks for your careful review. Your suggestion and recent merge required me to update all four patches.
Please take a look again when you can.

-Shuhei

**Comment by shuhei-matsumoto** [comment]
Patches were merged.
