### ISSUE TITLE
[vhost-initiator-vg-autotest ] vhost fuzz failed

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#1681]
error log:
START TEST vhost_fuzz
00:06:31.162  ************************************
00:06:31.162   09:05:34	# xtrace_enable
00:06:31.162   09:05:34	# ./test/vhost/fuzz/fuzz.sh
00:06:31.216    09:05:34	# xtrace_enable
00:06:31.216   09:05:34	# source /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/common.sh
00:06:31.218  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:06:31.218   09:05:34	# VHOST_APP+=(-p 0)
00:06:31.218   09:05:34	# FUZZ_RPC_SOCK=/var/tmp/spdk_fuzz.sock
00:06:31.218   09:05:34	# VHOST_FUZZ_APP+=(-r "$FUZZ_RPC_SOCK" -g --wait-for-rpc)
00:06:31.218   09:05:34	# vhost_rpc_py=/home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py
00:06:31.218   09:05:34	# fuzz_generic_rpc_py='/home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py -s /var/tmp/spdk_fuzz.sock'
00:06:31.218   09:05:34	# fuzz_specific_rpc_py='/home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock'
00:06:31.218   09:05:34	# vhostpid=23365
00:06:31.218   09:05:34	# waitforlisten 23365
00:06:31.218   09:05:34	# /home/vagrant/spdk_repo/spdk/build/bin/vhost -p 0
00:06:31.218   09:05:34	# '[' -z 23365 ']'
00:06:31.218   09:05:34	# local rpc_addr=/var/tmp/spdk.sock
00:06:31.218   09:05:34	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:06:31.218   09:05:34	# xtrace_disable
00:06:31.218   09:05:34	# '[' '' '!=' yes ']'
00:06:31.218   09:05:34	# PREV_BASH_OPTS=ehxBET
00:06:31.218   09:05:34	# [[ ehxBET == *\x* ]]
00:06:31.218   09:05:34	# XTRACE_DISABLED=yes
00:06:31.218   09:05:34	# set +x
00:06:32.250  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_fuzz.sock...
00:06:32.250   09:05:35	# xtrace_enable
00:06:32.250   09:05:35	# (( i == 0 ))
00:06:32.250   09:05:35	# return 0
00:06:32.250   09:05:35	# trap 'killprocess $vhostpid; exit 1' SIGINT SIGTERM exit
00:06:32.250   09:05:35	# /home/vagrant/spdk_repo/spdk/test/app/fuzz/vhost_fuzz/vhost_fuzz -r /var/tmp/spdk_fuzz.sock -g --wait-for-rpc -t 10
00:06:32.250   09:05:35	# fuzzpid=23371
00:06:32.250   09:05:35	# waitforlisten 23371 /var/tmp/spdk_fuzz.sock
00:06:32.250   09:05:35	# '[' -z 23371 ']'
00:06:32.250   09:05:35	# local rpc_addr=/var/tmp/spdk_fuzz.sock
00:06:32.250   09:05:35	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_fuzz.sock...'
00:06:32.250   09:05:35	# xtrace_disable
00:06:32.250   09:05:35	# '[' no '!=' yes ']'
00:06:32.250   09:05:35	# PREV_BASH_OPTS=ehxBET
00:06:32.250   09:05:35	# [[ ehxBET == *\x* ]]
00:06:32.250   09:05:35	# XTRACE_DISABLED=yes
00:06:32.250   09:05:35	# set +x
00:06:32.250  EAL: No legacy callbacks, legacy socket not created
00:06:32.855   09:05:35	# xtrace_enable
00:06:32.855   09:05:35	# (( i == 0 ))
00:06:32.855   09:05:35	# return 0
00:06:32.855   09:05:35	# trap 'killprocess $vhostpid; killprocess $fuzzpid; exit 1' SIGINT SIGTERM exit
00:06:32.855   09:05:35	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py bdev_malloc_create -b Malloc0 64 512
00:06:33.045  Malloc0
00:06:33.055   09:05:36	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py vhost_create_blk_controller Vhost.1 Malloc0
00:06:33.249   09:05:36	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py bdev_malloc_create -b Malloc1 64 512
00:06:33.451  Malloc1
00:06:33.460   09:05:36	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py vhost_create_scsi_controller naa.VhostScsi0.1
00:06:33.626   09:05:36	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py vhost_scsi_controller_add_target naa.VhostScsi0.1 0 Malloc1
00:06:33.763  0
00:06:33.769   09:05:36	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py bdev_malloc_create -b Malloc2 64 512
00:06:33.963  Malloc2
00:06:33.972   09:05:36	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py vhost_create_scsi_controller naa.VhostScsi0.2
00:06:34.138   09:05:37	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py vhost_scsi_controller_add_target naa.VhostScsi0.2 0 Malloc2
00:06:34.278  0
00:06:34.284    09:05:37	# pwd
00:06:34.284   09:05:37	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/vagrant/spdk_repo/spdk/Vhost.1 -b -v
00:06:34.473    09:05:37	# pwd
00:06:34.473   09:05:37	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/vagrant/spdk_repo/spdk/naa.VhostScsi0.1 -l -v
00:06:34.684    09:05:37	# pwd
00:06:34.684   09:05:37	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/vagrant/spdk_repo/spdk/naa.VhostScsi0.2 -v -m
00:06:34.920   09:05:37	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../scripts/rpc.py -s /var/tmp/spdk_fuzz.sock framework_start_init
00:06:35.064   09:05:38	# wait 23371
00:06:42.628  Fuzzing completed.
00:06:42.628  device 0x18c58e0 stats: Completed I/O: 352, Successful I/O: 0
00:06:42.628  device 0x196d9c0 stats: Completed I/O: 348, Successful I/O: 2
00:06:42.628  device 0x18c4910 stats: Completed I/O: 320, Successful I/O: 36
00:06:42.650  ./test/vhost/fuzz/fuzz.sh: line 48: 23365 Aborted                 (core dumped) "${VHOST_APP[@]}" > "$output_dir/vhost_fuzz_tgt_output.txt" 2>&1
00:06:42.652   09:05:45	# fuzzpid=23393
00:06:42.652   09:05:45	# waitforlisten 23393 /var/tmp/spdk_fuzz.sock
00:06:42.652   09:05:45	# /home/vagrant/spdk_repo/spdk/test/app/fuzz/vhost_fuzz/vhost_fuzz -r /var/tmp/spdk_fuzz.sock -g --wait-for-rpc -j /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../test/app/fuzz/vhost_fuzz/example.json
00:06:42.652   09:05:45	# '[' -z 23393 ']'
00:06:42.652   09:05:45	# local rpc_addr=/var/tmp/spdk_fuzz.sock
00:06:42.653  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_fuzz.sock...
00:06:42.653   09:05:45	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk_fuzz.sock...'
00:06:42.653   09:05:45	# xtrace_disable
00:06:42.653   09:05:45	# '[' no '!=' yes ']'
00:06:42.653   09:05:45	# PREV_BASH_OPTS=ehxBET
00:06:42.653   09:05:45	# [[ ehxBET == *\x* ]]
00:06:42.653   09:05:45	# XTRACE_DISABLED=yes
00:06:42.653   09:05:45	# set +x
00:06:42.783  EAL: No legacy callbacks, legacy socket not created
00:06:43.492   09:05:46	# xtrace_enable
00:06:43.492   09:05:46	# (( i == 0 ))
00:06:43.492   09:05:46	# return 0
00:06:43.492   09:05:46	# trap 'killprocess $vhostpid; killprocess $fuzzpid; exit 1' SIGINT SIGTERM exit
00:06:43.492    09:05:46	# pwd
00:06:43.493   09:05:46	# /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/vagrant/spdk_repo/spdk/Vhost.1 -b -v
00:06:43.556  request:
00:06:43.556  {
00:06:43.556    "socket": "/home/vagrant/spdk_repo/spdk/Vhost.1",
00:06:43.556    "is_blk": true,
00:06:43.556    "use_bogus_buffer": false,
00:06:43.556    "use_valid_buffer": true,
00:06:43.556    "test_scsi_tmf": false,
00:06:43.556    "valid_lun": false,
00:06:43.556    "method": "fuzz_vhost_create_dev",
00:06:43.556    "req_id": 1
00:06:43.556  }
00:06:43.556  Got JSON-RPC error response
00:06:43.556  response:
00:06:43.556  {
00:06:43.556    "code": -32603,
00:06:43.556    "message": "Unexpected error code.\n"
00:06:43.556  }
00:06:43.562    09:05:46	# trap - ERR
00:06:43.562    09:05:46	# print_backtrace
00:06:43.562    09:05:46	# [[ ehxBET =~ e ]]
00:06:43.562    09:05:46	# args=("${BASH_ARGV[@]}")
00:06:43.562    09:05:46	# local args
00:06:43.562    09:05:46	# xtrace_disable
00:06:43.562    09:05:46	# '[' no '!=' yes ']'
00:06:43.562    09:05:46	# PREV_BASH_OPTS=ehxBET
00:06:43.562    09:05:46	# [[ ehxBET == *\x* ]]
00:06:43.562    09:05:46	# XTRACE_DISABLED=yes
00:06:43.562    09:05:46	# set +x
00:06:43.562  ========== Backtrace start: ==========
00:06:43.562  
00:06:43.572  Process with pid 23365 is not found
00:06:43.572  in ./test/vhost/fuzz/fuzz.sh:57 -> main([])
00:06:43.572       ...
00:06:43.572     52  	waitforlisten $fuzzpid $FUZZ_RPC_SOCK
00:06:43.572     53  	
00:06:43.572     54  	# re-evaluate fuzzpid
00:06:43.572     55  	trap 'killprocess $vhostpid; killprocess $fuzzpid; exit 1' SIGINT SIGTERM exit
00:06:43.572     56  	
00:06:43.572  => 57  	$fuzz_specific_rpc_py fuzz_vhost_create_dev -s $(pwd)/Vhost.1 -b -v
00:06:43.572     58  	$fuzz_specific_rpc_py fuzz_vhost_create_dev -s $(pwd)/naa.VhostScsi0.1 -l -v
00:06:43.572     59  	$fuzz_specific_rpc_py fuzz_vhost_create_dev -s $(pwd)/naa.VhostScsi0.2 -v -m
00:06:43.572     60  	$fuzz_generic_rpc_py framework_start_init
00:06:43.572     61  	
00:06:43.572     62  	wait $fuzzpid
00:06:43.572       ...
00:06:43.572  
00:06:43.572  ========== Backtrace end ==========
00:06:43.572    09:05:46	# xtrace_enable
00:06:43.572    09:05:46	# return 0
00:06:43.572   09:05:46	# killprocess 23365
00:06:43.572   09:05:46	# '[' -z 23365 ']'
00:06:43.572   09:05:46	# kill -0 23365
00:06:43.572  /home/vagrant/spdk_repo/spdk/test/vhost/fuzz/../../../test/common/autotest_common.sh: line 763: kill: (23365) - No such process
00:06:43.572   09:05:46	# echo 'Process with pid 23365 is not found'
00:06:43.572   09:05:46	# exit 1
00:06:43.572    09:05:46	# trap - ERR
00:06:43.572    09:05:46	# print_backtrace
00:06:43.573    09:05:46	# [[ ehxBET =~ e ]]
00:06:43.573    09:05:46	# args=("${BASH_ARGV[@]}")
00:06:43.573    09:05:46	# local args
00:06:43.573    09:05:46	# xtrace_disable
00:06:43.573    09:05:46	# '[' no '!=' yes ']'
00:06:43.573    09:05:46	# PREV_BASH_OPTS=ehxBET
00:06:43.573    09:05:46	# [[ ehxBET == *\x* ]]
00:06:43.573    09:05:46	# XTRACE_DISABLED=yes
00:06:43.573    09:05:46	# set +x
00:06:43.573  ========== Backtrace start: ==========
00:06:43.573  
00:06:43.583  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:943 -> run_test(["vhost_fuzz"],["./test/vhost/fuzz/fuzz.sh"])
00:06:43.583       ...
00:06:43.583     938 		timing_enter $test_name
00:06:43.583     939 		echo "************************************"
00:06:43.583     940 		echo "START TEST $test_name"
00:06:43.583     941 		echo "************************************"
00:06:43.583     942 		xtrace_restore
00:06:43.583  => 943 		time "$@"
00:06:43.583     944 		xtrace_disable
00:06:43.583     945 		echo "************************************"
00:06:43.583     946 		echo "END TEST $test_name"
00:06:43.583     947 		echo "************************************"
00:06:43.583     948 		timing_exit $test_name
00:06:43.583       ...
00:06:43.590  in /home/vagrant/spdk_repo/spdk/autotest.sh:270 -> main(["/home/vagrant/autorun-spdk.conf"])
00:06:43.590       ...
00:06:43.590     265 		if [ $SPDK_TEST_VHOST_INIT -eq 1 ]; then
00:06:43.590     266 			timing_enter vhost_initiator
00:06:43.590     267 			run_test "vhost_blockdev" ./test/vhost/initiator/blockdev.sh
00:06:43.590     268 			run_test "spdkcli_virtio" ./test/spdkcli/virtio.sh
00:06:43.590     269 			run_test "vhost_shared" ./test/vhost/shared/shared.sh
00:06:43.590  => 270 			run_test "vhost_fuzz" ./test/vhost/fuzz/fuzz.sh
00:06:43.590     271 			timing_exit vhost_initiator
00:06:43.590     272 		fi
00:06:43.590     273 	
00:06:43.590     274 		if [ $SPDK_TEST_PMDK -eq 1 ]; then
00:06:43.590     275 			run_test "blockdev_pmem" ./test/bdev/blockdev.sh "pmem"
00:06:43.590       ...
00:06:43.590  
00:06:43.590  ========== Backtrace end ==========
00:06:43.590    09:05:46	# xtrace_enable
00:06:43.590    09:05:46	# return 0
00:06:43.590  
00:06:43.590  real	0m12.427s
00:06:43.590  user	0m13.177s
00:06:43.590  sys	0m0.769s
00:06:43.590   09:05:46	# process_core
00:06:43.590   09:05:46	# ret=0
00:06:43.590   09:05:46	# IFS=
00:06:43.590   09:05:46	# read -r -d '' core
00:06:43.590    09:05:46	# find . -type f '(' -name 'core.[0-9]*' -o -name core -o -name '*.core' ')' -print0
00:06:43.620    09:05:46	# grep psargs
00:06:43.620    09:05:46	# eu-readelf -n ./core.23365
00:06:43.620    09:05:46	# sed 's/.*psargs: \([^ \'\''" ]*\).*/\1/'
00:06:43.643  exe for ./core.23365 is /home/vagrant/spdk_repo/spdk/build/bin/vhost
00:06:43.643   09:05:46	# exe=/home/vagrant/spdk_repo/spdk/build/bin/vhost
00:06:43.643   09:05:46	# [[ ! -f /home/vagrant/spdk_repo/spdk/build/bin/vhost ]]
00:06:43.643   09:05:46	# echo 'exe for ./core.23365 is /home/vagrant/spdk_repo/spdk/build/bin/vhost'
00:06:43.643   09:05:46	# [[ -n /home/vagrant/spdk_repo/spdk/build/bin/vhost ]]
00:06:43.643   09:05:46	# hash gdb
00:06:43.643   09:05:46	# gdb -batch -ex 'thread apply all bt full' /home/vagrant/spdk_repo/spdk/build/bin/vhost ./core.23365
00:06:43.826  
00:06:43.826  warning: core file may not match specified executable file.
00:06:43.844  [New LWP 23365]
00:06:43.844  [New LWP 23367]
00:06:43.844  [New LWP 23368]
00:06:43.844  [New LWP 23379]
00:06:44.407  [Thread debugging using libthread_db enabled]
00:06:44.407  Using host libthread_db library "/lib64/libthread_db.so.1".
00:06:44.649  Core was generated by `/home/vagrant/spdk_repo/spdk/build/bin/vhost -p 0'.
00:06:44.649  Program terminated with signal SIGABRT, Aborted.
00:06:44.649  #0  0x00007f934eea9625 in raise () from /lib64/libc.so.6
00:06:44.664  [Current thread is 1 (Thread 0x7f934e7c5b40 (LWP 23365))]
00:06:44.694  
00:06:44.694  Thread 4 (Thread 0x7f934cfba700 (LWP 23379)):
00:06:44.694  #0  0x00007f934ef63a3f in poll () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  #1  0x00007f934fa5bec1 in fdset_event_dispatch (arg=0x7f934faee2e0 <vhost_user+8192>) at ../lib/librte_vhost/fd_man.c:252
00:06:44.694          i = 7
00:06:44.694          pfd = 0x7f934faee310 <vhost_user+8240>
00:06:44.694          pfdentry = 0x7f934faf03d0 <vhost_user+16624>
00:06:44.694          rcb = 0x7f934fa6cb47 <vhost_user_read_cb>
00:06:44.694          wcb = 0x0
00:06:44.694          dat = 0x7f933800b750
00:06:44.694          fd = 312
00:06:44.694          numfds = 7
00:06:44.694          remove1 = 0
00:06:44.694          remove2 = 0
00:06:44.694          need_shrink = 0
00:06:44.694          pfdset = 0x7f934faee2e0 <vhost_user+8192>
00:06:44.694          val = 0
00:06:44.694  #2  0x00007f934fbc0672 in ctrl_thread_init (arg=0x1358d10) at ../lib/librte_eal/common/eal_common_thread.c:193
00:06:44.694          ret = -1
00:06:44.694          internal_conf = 0x7f934fc184c0 <internal_config>
00:06:44.694          cpuset = 0x7f934fc1b5f8 <internal_config+12600>
00:06:44.694          params = 0x1358d10
00:06:44.694          start_routine = 0x7f934fa5be3f <fdset_event_dispatch>
00:06:44.694          routine_arg = 0x7f934faee2e0 <vhost_user+8192>
00:06:44.694  #3  0x00007f934f03f4e2 in start_thread () from /lib64/libpthread.so.0
00:06:44.694  No symbol table info available.
00:06:44.694  #4  0x00007f934ef6e6a3 in clone () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  
00:06:44.694  Thread 3 (Thread 0x7f934dfc0700 (LWP 23368)):
00:06:44.694  #0  0x00007f934f0499af in accept () from /lib64/libpthread.so.0
00:06:44.694  No symbol table info available.
00:06:44.694  #1  0x00007f934fb0730e in socket_listener (socket=0x7f934fb0b7c0 <v2_socket>) at ../lib/librte_telemetry/telemetry.c:279
00:06:44.694          th = 0
00:06:44.694          s = 0x7f934fb0b7c0 <v2_socket>
00:06:44.694          s_accepted = 0
00:06:44.694  #2  0x00007f934f03f4e2 in start_thread () from /lib64/libpthread.so.0
00:06:44.694  No symbol table info available.
00:06:44.694  #3  0x00007f934ef6e6a3 in clone () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  
00:06:44.694  Thread 2 (Thread 0x7f934e7c1700 (LWP 23367)):
00:06:44.694  #0  0x00007f934ef6e9de in epoll_wait () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  #1  0x00007f934fbda358 in eal_intr_handle_interrupts (pfd=8, totalfds=1) at ../lib/librte_eal/linux/eal_interrupts.c:1041
00:06:44.694          events = {{events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}}
00:06:44.694          nfds = 0
00:06:44.694  #2  0x00007f934fbda551 in eal_intr_thread_main (arg=0x0) at ../lib/librte_eal/linux/eal_interrupts.c:1126
00:06:44.694          pipe_event = {events = 3, data = {ptr = 0x4, fd = 4, u32 = 4, u64 = 4}}
00:06:44.694          src = 0x0
00:06:44.694          numfds = 1
00:06:44.694          pfd = 8
00:06:44.694          __func__ = "eal_intr_thread_main"
00:06:44.694  #3  0x00007f934fbc0672 in ctrl_thread_init (arg=0x1298fe0) at ../lib/librte_eal/common/eal_common_thread.c:193
00:06:44.694          ret = -1
00:06:44.694          internal_conf = 0x7f934fc184c0 <internal_config>
00:06:44.694          cpuset = 0x7f934fc1b5f8 <internal_config+12600>
00:06:44.694          params = 0x1298fe0
00:06:44.694          start_routine = 0x7f934fbda3ba <eal_intr_thread_main>
00:06:44.694          routine_arg = 0x0
00:06:44.694  #4  0x00007f934f03f4e2 in start_thread () from /lib64/libpthread.so.0
00:06:44.694  No symbol table info available.
00:06:44.694  #5  0x00007f934ef6e6a3 in clone () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  
00:06:44.694  Thread 1 (Thread 0x7f934e7c5b40 (LWP 23365)):
00:06:44.694  #0  0x00007f934eea9625 in raise () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  #1  0x00007f934ee928d9 in abort () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  #2  0x00007f934ee927a9 in __assert_fail_base.cold () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  #3  0x00007f934eea1a66 in __assert_fail () from /lib64/libc.so.6
00:06:44.694  No symbol table info available.
00:06:44.694  #4  0x00007f934fed5ff6 in scsi2_release (task=0x200023bbf7c0) at scsi_pr.c:1030
00:06:44.694          lun = 0x1390750
00:06:44.694          ret = 0
00:06:44.694          __PRETTY_FUNCTION__ = "scsi2_release"
00:06:44.694  #5  0x00007f934fecd81a in bdev_scsi_process_primary (task=0x200023bbf7c0) at scsi_bdev.c:1946
00:06:44.694          lun = 0x1390750
00:06:44.694          bdev = 0x1359690
00:06:44.694          alloc_len = -1
00:06:44.694          data_len = -1
00:06:44.694          cdb = 0x7f9337adfb7b <error: Cannot access memory at address 0x7f9337adfb7b>
00:06:44.694          data = 0x0
00:06:44.694          rc = 0
00:06:44.694          pllen = 32659
00:06:44.694          md = 0
00:06:44.694          llba = 0
00:06:44.694          dbd = 934148987
00:06:44.694          pc = 32659
00:06:44.694          page = 749123090
00:06:44.694          subpage = 32765
00:06:44.694          cmd_parsed = 0
00:06:44.694          __PRETTY_FUNCTION__ = "bdev_scsi_process_primary"
00:06:44.694          __func__ = "bdev_scsi_process_primary"
00:06:44.695  #6  0x00007f934fecd9d4 in bdev_scsi_execute (task=0x200023bbf7c0) at scsi_bdev.c:1977
00:06:44.695          rc = -1
00:06:44.695          __func__ = "bdev_scsi_execute"
00:06:44.695  #7  0x00007f934febc5f1 in _scsi_lun_execute_task (lun=0x1390750, task=0x200023bbf7c0) at lun.c:209
00:06:44.695          rc = 0
00:06:44.695  #8  0x00007f934febce8d in scsi_lun_execute_task (lun=0x1390750, task=0x200023bbf7c0) at lun.c:263
00:06:44.695  No locals.
00:06:44.695  #9  0x00007f934feb91d5 in spdk_scsi_dev_queue_task (dev=0x7f934fef49e0 <g_devs>, task=0x200023bbf7c0) at dev.c:292
00:06:44.695          __PRETTY_FUNCTION__ = "spdk_scsi_dev_queue_task"
00:06:44.695  #10 0x00007f93503db3bd in task_submit (task=0x200023bbf7c0) at vhost_scsi.c:381
00:06:44.695  No locals.
00:06:44.695  #11 0x00007f93503dfa83 in process_scsi_task (vsession=0x7f933800b800, vq=0x7f933800b980, req_idx=20) at vhost_scsi.c:724
00:06:44.695          task = 0x200023bbf7c0
00:06:44.695          result = 0
00:06:44.695          __func__ = "process_scsi_task"
00:06:44.695  #12 0x00007f93503e0c1d in process_vq (svsession=0x7f933800b800, vq=0x7f933800b980) at vhost_scsi.c:799
00:06:44.695          vsession = 0x7f933800b800
00:06:44.695          reqs = {960, 963, 966, 969, 972, 975, 978, 981, 984, 987, 990, 993, 996, 999, 1002, 1005, 1008, 1011, 1014, 1017, 1020, 1023, 2, 5, 8, 11, 14, 17, 20, 23, 26, 29}
00:06:44.695          reqs_cnt = 32
00:06:44.695          i = 28
00:06:44.695          __PRETTY_FUNCTION__ = "process_vq"
00:06:44.695          __func__ = "process_vq"
00:06:44.695  #13 0x00007f93503e0f4b in vdev_worker (arg=0x7f933800b800) at vhost_scsi.c:826
00:06:44.695          svsession = 0x7f933800b800
00:06:44.695          vsession = 0x7f933800b800
00:06:44.695          q_idx = 2
00:06:44.695  #14 0x00007f934fe32fa3 in thread_poll (thread=0x13903d0, max_msgs=0, now=862953417489) at thread.c:645
00:06:44.695          poller_rc = 1
00:06:44.695          msg_count = 0
00:06:44.695          poller = 0x1350bf0
00:06:44.695          tmp = 0x0
00:06:44.695          critical_msg = 0x0
00:06:44.695          rc = 0
00:06:44.695          __func__ = "thread_poll"
00:06:44.695  #15 0x00007f934fe34cb3 in spdk_thread_poll (thread=0x13903d0, max_msgs=0, now=862953417489) at thread.c:733
00:06:44.695          orig_thread = 0x0
00:06:44.695          rc = 1
00:06:44.695  #16 0x00007f935033beb5 in _reactor_run (reactor=0x134ee40) at reactor.c:666
00:06:44.695          thread = 0x13903d0
00:06:44.695          lw_thread = 0x1390710
00:06:44.695          tmp = 0x1391570
00:06:44.695          now = 862953417489
00:06:44.695          rc = 1
00:06:44.695  #17 0x00007f935033c6ba in reactor_run (arg=0x134ee40) at reactor.c:710
00:06:44.695          reactor = 0x134ee40
00:06:44.695          thread = 0x7f934fbb0aff <rte_get_next_lcore+42>
00:06:44.695          lw_thread = 0x7f00000001
00:06:44.695          tmp = 0x7ffd2ca6b930
00:06:44.695          thread_name = "reactor_0\000\000\000\200\000\000\000`\271\246,\375\177\000\000P\033\316O\000\000\000"
00:06:44.695          last_sched = 0
00:06:44.695          __func__ = "reactor_run"
00:06:44.695          __PRETTY_FUNCTION__ = "reactor_run"
00:06:44.695  #18 0x00007f935033d5f9 in spdk_reactors_start () at reactor.c:828
00:06:44.695          reactor = 0x134ee40
00:06:44.695          tmp_cpumask = {str = '\000' <repeats 256 times>, cpus = '\000' <repeats 127 times>}
00:06:44.695          i = 4294967295
00:06:44.695          current_core = 0
00:06:44.695          rc = 8192
00:06:44.695          thread_name = "\200\374O\000\000 \000\000\030\273\246,\375\177\000\000\000\376O\000\000 \000\000\030\273\246,\375\177\000"
00:06:44.695          __func__ = "spdk_reactors_start"
00:06:44.695          __PRETTY_FUNCTION__ = "spdk_reactors_start"
00:06:44.695  #19 0x00007f9350334b7c in spdk_app_start (opts=0x7ffd2ca6bd60, start_fn=0x40255e <vhost_started>, arg1=0x0) at app.c:501
00:06:44.695          rc = 0
00:06:44.695          tty = 0x0
00:06:44.695          tmp_cpumask = {str = '\000' <repeats 256 times>, cpus = "\001", '\000' <repeats 126 times>}
00:06:44.695          g_env_was_setup = false
00:06:44.695          __func__ = "spdk_app_start"
00:06:44.695  #20 0x00000000004026a4 in main (argc=3, argv=0x7ffd2ca6bf08) at vhost.c:105
00:06:44.695          opts = {name = 0x4050d7 "vhost", config_file = 0x0, json_config_file = 0x0, json_config_ignore_errors = false, rpc_addr = 0x7f935035015d "/var/tmp/spdk.sock", reactor_mask = 0x7f9350350159 "0x1", tpoint_group_mask = 0x0, shm_id = -1, shutdown_cb = 0x0, enable_coredump = true, mem_channel = -1, master_core = 0, mem_size = -1, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, hugedir = 0x0, print_level = SPDK_LOG_INFO, num_pci_addr = 0, pci_blacklist = 0x0, pci_whitelist = 0x0, iova_mode = 0x0, max_delay_us = 0, delay_subsystem_init = false, num_entries = 32768, env_context = 0x0, log = 0x0, base_virtaddr = 35184372088832}
00:06:44.695          rc = 1
00:06:44.709   09:05:47	# cp /home/vagrant/spdk_repo/spdk/build/bin/vhost /home/vagrant/spdk_repo/spdk/../output
00:06:44.718   09:05:47	# mv ./core.23365 /home/vagrant/spdk_repo/spdk/../output
00:06:44.811  mv: failed to preserve ownership for '/home/vagrant/spdk_repo/spdk/../output/core.23365': Permission denied
00:06:44.815   09:05:47	# chmod a+r /home/vagrant/spdk_repo/spdk/../output/./core.23365
00:06:44.818   09:05:47	# ret=1
00:06:44.818   09:05:47	# IFS=
00:06:44.818   09:05:47	# read -r -d '' core
00:06:44.818   09:05:47	# return 1
00:15:00.314  Build timed out (after 15 minutes). Marking the build as failed.
00:15:00.322  Build was aborted
00:15:00.329  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:00.335  [vhost-initiator-vg-autotest] $ /usr/bin/env bash /tmp/jenkins3190582332687264809.sh
00:15:00.339  + [[ -n fedora31 ]]
00:15:00.340  + mv /var/jenkins/workspace/vhost-initiator-vg-autotest/fedora31-libvirt/output /var/jenkins/workspace/vhost-initiator-vg-autotest/output
00:15:00.367  [vhost-initiator-vg-autotest] $ /usr/bin/env bash /tmp/jenkins5588961868229049579.sh
00:15:00.382  + vagrant destroy -f

**Comment by tomzawadzki** [comment]
@glodfish-zg Can you please link to patch where this failure occurred ? 
CI bot can link that here when patch receives comment `false positive: 1681`. More info on that [here](https://spdk.io/development/#integration_false_positive)

**Comment by glodfish-zg** [comment]
patch has been abandoned. So close this issue.
