### ISSUE TITLE
[ocf-master-vs-spdk-master] Fail at ocf_persistent_metadata test case

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1683]
## Current Behavior

SPDK ocf tests fail at "ocf_persistent_metadata" test case when testing versus latest OCF sources.

## Steps to Reproduce

1. Prepare SPDK test config in ~/autorun-spdk.conf
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_RUN_UBSAN=1
SPDK_TEST_OCF=1
RUN_NIGHTLY=1
```

2. Checkout latest ocf sources in spdk ocf module
```
cd spdk/ocf
git fetch origin master
git checkout FETCH_HEAD
```

3. Build SPDK & OCF:
```
spdk/autobuild.sh ~/autorun-spdk.conf
```

4. Run tests:
```
sudo -E spdk/autotest.sh ~/autorun-spdk.conf
```

Tests fail at ocf_persistent_metadata test case. Example build log attached: 
[ocf-build-log.txt](https://github.com/spdk/spdk/files/5555094/ocf-build-log.txt)

## Context (Environment including OS version, SPDK version, etc.)
SPDK  a2be549268 
OCF  ec723e1

**Comment by gwnet** [comment]
@karlatec could you please fetch the OCF code just using git submodule update --init, then try again?

**Comment by gwnet** [comment]
@Comphix could you please assign this to me first?

**Comment by karlatec** [comment]
@gwnet You mean using OCF 02f6fc3 commit, which is the current "default" for OCF submodule in SPDK?

**Comment by gwnet** [comment]
@rafalste could you please help confirm the commit id that @karlatec should use?

**Comment by rafalste** [comment]
@gwnet @karlatec I can see that after running `git submodule update --init` on SPDK sources, the last OCF commit is indeed `02f6fc3`, so I suppose this is the right one. Try this one and let us know if it helped.

**Comment by karlatec** [comment]
@rafalste @gwnet I am aware that OCF 02f6fc3 (currently checked out after SPDK git submodule update --init) is OK.
The issue I created is specifically about using OCF master instead of top of v20.3.1.

**Comment by rafalste** [comment]
@karlatec OCF in master branch have some API changes, so it won't work with SPDK at the moment.

**Comment by tomzawadzki** [comment]
@gwnet @rafalste In case of some dependencies test are being performed for their upstream. This is to get some heads up for when the version is moved forward. This is common for components like DPDK, QEMU, OCF etc.

This is not an issue _right now_, but if the OCF version is ever to be moved up it has to be addressed. @karlatec thanks for reporting this.

Let's leave it up and @rafalste can handle it when appropriate.

**Comment by gwnet** [comment]
@karlatec can we go head close this issue?

**Comment by gwnet** [comment]
temp close this for now. if has any new questions, please reopen it
