### ISSUE TITLE
nvme discover fails with `*ERROR*: Admin command sent before CONNECT`

### ISSUE THREAD

**Issue by bharatpotnuri** [spdk/spdk#1684]
Hi All,
I am seeing the following error on trying to discover NVMF target. I see the same behavior with both 'nvme' app and 'fio with spdk'.
`
[2020-11-18 10:41:45.383980] ctrlr.c:2679:nvmf_ctrlr_process_admin_cmd: *ERROR*: Admin command sent before CONNECT
`

## Expected Behavior
Discover should succeed.

## Current Behavior
Target prints the following error:
`
[2020-11-18 10:41:45.383980] ctrlr.c:2679:nvmf_ctrlr_process_admin_cmd: *ERROR*: Admin command sent before CONNECT
`

## Steps to Reproduce

Here is the script I am using to create target:
```
#!/bin/bash

RPC_PATH=/home/spdk_nvme-cli/spdk/scripts

/home/spdk_nvme-cli/spdk/build/bin/nvmf_tgt -m 0x3FFF &

python3 $RPC_PATH/rpc.py nvmf_create_transport -t RDMA -u 131072 -c 8192 -n 8192 -b 256

for i in `seq 1 $1`
do
  python3 $RPC_PATH/rpc.py bdev_malloc_create -b Malloc$i 256 512
  python3 $RPC_PATH/rpc.py nvmf_create_subsystem  nqn.2016-06.io.spdk:cnode$i -a -s SPDK0000000000000$i -d SPDK_Controller$i
  python3 $RPC_PATH/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode$i Malloc$i
  python3 $RPC_PATH/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode$i -t rdma -a 10.0.3.2 -s 4420 -f ipv4
done
```

nvme command used for discover:
`
nvme discover -t rdma -a 10.0.3.2 -s 4420
`
```
LD_PRELOAD=/home/spdk_nvme-cli/spdk/examples/nvme/fio_plugin/fio_plugin fio --rw=randwrite --name=random --norandommap --ioengine=spdk --size=400m --group_reporting --exitall --fsync_on_close=1 --invalidate=1 --direct=1 --filename='trtype=RDMA adrfam=IPv4 traddr=10.0.3.2 trsvcid=4420 subnqn=nqn.2016-06.io.spdk\:cnode1 ns=1' --time_based --runtime=10 --iodepth=64 --numjobs=32 --unit_base=1 --bs=4K --kb_base=1000 --ramp_time=1 --thread=1
```

## Context (Environment including OS version, SPDK version, etc.)

OS: RHEL 8.2.
kernel: 4.18.0-193.el8
SPDK: commit 10ed0eb755932458c060f0709635d733c370f2ac
nvmecli: commit 26bbb6f40335403559c179388d6b853a89b268a9

**Comment by yidong0635** [comment]
@bharatpotnuri  please try new plugin path: build/fio/spdk_bdev or build/fio/spdk_nvme. And I will try to reproduce this issue.

**Comment by bharatpotnuri** [comment]
> 
> 
> @bharatpotnuri please try new plugin path: build/fio/spdk_bdev or build/fio/spdk_nvme. And I will try to reproduce this issue.

@yidong0635 tried with fio/spdk_nvme.
Still see the same issue. Follwoing prints are flooding dmesg:
`
[2020-11-18 12:28:36.337203] ctrlr.c:2679:nvmf_ctrlr_process_admin_cmd: *ERROR*: Admin command sent before CONNECT
`

Fio command:
```
#LD_PRELOAD=/home/spdk_nvme-cli/spdk/build/fio/spdk_nvme fio --rw=randwrite --name=random --norandommap --ioengine=spdk --size=400m --group_reporting --exitall --fsync_on_close=1 --invalidate=1 --direct=1 --filename='trtype=RDMA adrfam=IPv4 traddr=10.0.3.2 trsvcid=4420 subnqn=nqn.2016-06.io.spdk\:cnode1 ns=1' --time_based --runtime=1000 --iodepth=64 --numjobs=32 --unit_base=1 --bs=4K --kb_base=1000 --ramp_time=1 --thread=1
```

**Comment by yidong0635** [comment]
My test result is :
```
 LOAD_PRELOAD=build/fio/spdk_nvme /usr/src/fio/fio --rw=randwrite --name=random --norandommap --ioengine=build/fio/spdk_nvme --size=400m --group_reporting --exitall --fsync_on_close=1 --invalidate=1 --direct=1 --filename='trtype=RDMA adrfam=IPv4 traddr=192.168.35.11 trsvcid=4420 ns=1' --time_based --runtime=10 --iodepth=64 --numjobs=32 --unit_base=1 --bs=4K --kb_base=1000 --ramp_time=1 --thread=1
random: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=64
...
fio-3.15
Starting 32 threads
[2020-11-18 15:01:18.199704] Starting SPDK v21.01-pre git sha1 10ed0eb / DPDK 20.08.0 initialization...
[2020-11-18 15:01:18.200265] [ DPDK EAL parameters: [2020-11-18 15:01:18.200280] fio [2020-11-18 15:01:18.200289] --no-shconf [2020-11-18 15:01:18.200297] -c 0x1 [2020-11-18 15:01:18.200305] -m 0 [2020-11-18 15:01:18.200313] --log-level=lib.eal:6 [2020-11-18 15:01:18.200321] --log-level=lib.cryptodev:5 [2020-11-18 15:01:18.200330] --log-level=user1:6 [2020-11-18 15:01:18.200338] --iova-mode=pa [2020-11-18 15:01:18.200346] --base-virtaddr=0x200000000000 [2020-11-18 15:01:18.200354] --match-allocations [2020-11-18 15:01:18.200362] --file-prefix=spdk_pid3949 [2020-11-18 15:01:18.200371] ]
EAL: No legacy callbacks, legacy socket not created
Jobs: 32 (f=32): [w(32)][100.0%][w=66.4Gbit/s][w=2076k IOPS][eta 00m:00s]
random: (groupid=0, jobs=32): err= 0: pid=4119: Wed Nov 18 15:01:31 2020
  write: IOPS=2075k, BW=67.0Gbit/s (63.3Gibit/s)(85.0GB/10002msec)
    slat (nsec): min=144, max=3632.6k, avg=361.06, stdev=4599.93
    clat (usec): min=61, max=22328, avg=983.79, stdev=182.92
     lat (usec): min=62, max=22328, avg=984.15, stdev=183.46
    clat percentiles (usec):
     |  1.00th=[  914],  5.00th=[  947], 10.00th=[  955], 20.00th=[  963],
     | 30.00th=[  971], 40.00th=[  979], 50.00th=[  988], 60.00th=[  988],
     | 70.00th=[  996], 80.00th=[ 1004], 90.00th=[ 1020], 95.00th=[ 1029],
     | 99.00th=[ 1045], 99.50th=[ 1057], 99.90th=[ 1106], 99.95th=[ 2704],
     | 99.99th=[11076]
   bw (  MiB/s): min= 8017, max= 8813, per=100.00%, avg=8322.91, stdev= 6.19, samples=610
   iops        : min=2004261, max=2203335, avg=2080727.52, stdev=1546.51, samples=610
  lat (usec)   : 100=0.04%, 250=0.18%, 500=0.26%, 750=0.18%, 1000=73.61%
  lat (msec)   : 2=25.69%, 4=0.02%, 10=0.02%, 20=0.01%, 50=0.01%
  cpu          : usr=99.59%, sys=0.40%, ctx=311, majf=0, minf=3275
  IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=0,20751403,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
  WRITE: bw=67.0Gbit/s (63.3Gibit/s), 67.0Gbit/s-67.0Gbit/s (63.3Gibit/s-63.3Gibit/s), io=85.0GB (79.2GiB), run=10002-10002msec

```

**Comment by bharatpotnuri** [comment]
> 
> 
> My test result is :
> 
> ```
>  LOAD_PRELOAD=build/fio/spdk_nvme /usr/src/fio/fio --rw=randwrite --name=random --norandommap --ioengine=build/fio/spdk_nvme --size=400m --group_reporting --exitall --fsync_on_close=1 --invalidate=1 --direct=1 --filename='trtype=RDMA adrfam=IPv4 traddr=192.168.35.11 trsvcid=4420 ns=1' --time_based --runtime=10 --iodepth=64 --numjobs=32 --unit_base=1 --bs=4K --kb_base=1000 --ramp_time=1 --thread=1
> random: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=64
> ...
> fio-3.15
> Starting 32 threads
> [2020-11-18 15:01:18.199704] Starting SPDK v21.01-pre git sha1 10ed0eb / DPDK 20.08.0 initialization...
> [2020-11-18 15:01:18.200265] [ DPDK EAL parameters: [2020-11-18 15:01:18.200280] fio [2020-11-18 15:01:18.200289] --no-shconf [2020-11-18 15:01:18.200297] -c 0x1 [2020-11-18 15:01:18.200305] -m 0 [2020-11-18 15:01:18.200313] --log-level=lib.eal:6 [2020-11-18 15:01:18.200321] --log-level=lib.cryptodev:5 [2020-11-18 15:01:18.200330] --log-level=user1:6 [2020-11-18 15:01:18.200338] --iova-mode=pa [2020-11-18 15:01:18.200346] --base-virtaddr=0x200000000000 [2020-11-18 15:01:18.200354] --match-allocations [2020-11-18 15:01:18.200362] --file-prefix=spdk_pid3949 [2020-11-18 15:01:18.200371] ]
> EAL: No legacy callbacks, legacy socket not created
> Jobs: 32 (f=32): [w(32)][100.0%][w=66.4Gbit/s][w=2076k IOPS][eta 00m:00s]
> random: (groupid=0, jobs=32): err= 0: pid=4119: Wed Nov 18 15:01:31 2020
>   write: IOPS=2075k, BW=67.0Gbit/s (63.3Gibit/s)(85.0GB/10002msec)
>     slat (nsec): min=144, max=3632.6k, avg=361.06, stdev=4599.93
>     clat (usec): min=61, max=22328, avg=983.79, stdev=182.92
>      lat (usec): min=62, max=22328, avg=984.15, stdev=183.46
>     clat percentiles (usec):
>      |  1.00th=[  914],  5.00th=[  947], 10.00th=[  955], 20.00th=[  963],
>      | 30.00th=[  971], 40.00th=[  979], 50.00th=[  988], 60.00th=[  988],
>      | 70.00th=[  996], 80.00th=[ 1004], 90.00th=[ 1020], 95.00th=[ 1029],
>      | 99.00th=[ 1045], 99.50th=[ 1057], 99.90th=[ 1106], 99.95th=[ 2704],
>      | 99.99th=[11076]
>    bw (  MiB/s): min= 8017, max= 8813, per=100.00%, avg=8322.91, stdev= 6.19, samples=610
>    iops        : min=2004261, max=2203335, avg=2080727.52, stdev=1546.51, samples=610
>   lat (usec)   : 100=0.04%, 250=0.18%, 500=0.26%, 750=0.18%, 1000=73.61%
>   lat (msec)   : 2=25.69%, 4=0.02%, 10=0.02%, 20=0.01%, 50=0.01%
>   cpu          : usr=99.59%, sys=0.40%, ctx=311, majf=0, minf=3275
>   IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
>      submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
>      complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
>      issued rwts: total=0,20751403,0,0 short=0,0,0,0 dropped=0,0,0,0
>      latency   : target=0, window=0, percentile=100.00%, depth=64
> 
> Run status group 0 (all jobs):
>   WRITE: bw=67.0Gbit/s (63.3Gibit/s), 67.0Gbit/s-67.0Gbit/s (63.3Gibit/s-63.3Gibit/s), io=85.0GB (79.2GiB), run=10002-10002msec
> ```
> 
> you can refer to examples/nvme/fio_plugin/README.md.

Looks like issue is with kernel. I reran on 5.4.44 kernel where discovery and fio works fine.

```
# nvme discover -t rdma -a 10.0.3.2 -s 4420

Discovery Log Number of Records 1, Generation counter 5
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not required
portid:  0
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  10.0.3.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
```

I am fine with using latest kernel. Can I close the issue?

**Comment by jimharris** [comment]
I'm closing the issue.  It will only change the status of this issue - all of the details will remain here for tracking purposes in the future.
