### ISSUE TITLE
NVMeOF-TCP: initiator hangs when zero copy is enabled

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1685]
NVMEoF TCP initiator hangs when zero copy is enabled. This issue observed several times in regression tests.
More information can be found in #1633 

## Expected Behavior

NVMEoF TCP initiator works without hangs

## Current Behavior

In some cases NVMEoF TCP initiator hangs

## Possible Solution

None

## Steps to Reproduce

Run bdev_perf or nvme_perf with enabled zero copy send feature. For perf it is `-Z` option, for bdev_perf it is socket layer json config.

## Context (Environment including OS version, SPDK version, etc.)

Reproducible with SPDK 20.10 and later versions (master branch)

**Comment by optimistyzy** [comment]
The following patch may help:  https://review.spdk.io/gerrit/c/spdk/spdk/+/5423 
What I think is that if the initiator's connection does not belong to a group. When zero copy is enabled, I checked the code path if a connection is not in the group. We do not have an code to call _sock_check_zcopy

**Comment by AlekseyMarchuk** [comment]
@optimistyzy I plan to start working on this issue next week, will update with test results

**Comment by yidong0635** [comment]
@AlekseyMarchuk  May I ask a question, what's  the status of this issue, any testing help do you need?

**Comment by AlekseyMarchuk** [comment]
@yidong0635 I'm working on it, trying to reproduce and find the root cause. I would appreciate your help validating the fix when I find it.

**Comment by AlekseyMarchuk** [comment]
Fix is here https://review.spdk.io/gerrit/c/spdk/spdk/+/6162

**Comment by karlatec** [comment]
I ran https://review.spdk.io/gerrit/c/spdk/spdk/+/6162/1 (with zcopy enabled for both Target and Initiator)  a couple of times (7 times I think) on our TCP regression setup and did not see a freeze or hang.

**Comment by AlekseyMarchuk** [comment]
Path https://review.spdk.io/gerrit/c/spdk/spdk/+/6162 is merged, closing this issue
