### ISSUE TITLE
spdk_pci_device_cfg_write* functions fail to update MSI-X control register

### ISSUE THREAD

**Issue by aohzju** [spdk/spdk#1687]
I have an NVMe testing program, which calls spdk_pci_device_cfg_write16 to change MSI-X control register (CAP_MSIX+0x02). The function returns zero as if it has update the register correctly, but actually the register is not updated at all.
I tried spdk_pci_device_cfg_write32 as well, which has no effect either. 

I ever reported such an issue: https://github.com/spdk/spdk/issues/1631. The root cause of it is that vfio-pci protected the MSI-X table from being changed. Is this issue caused by the same/similar reason? It's a major inconvenience for me if yes.

**Comment by aohzju** [comment]
Byt the way, the utility tool setpci can update the MSI-X control register from command line. Doesn't setpci update the register via vfio-pci as well?

**Comment by jimharris** [comment]
This is the same root cause as #1631. 

setpci has no dependencies on vfio-pci.  setpci can manipulate PCI config registers for any PCI device, regardless of what driver that device is bound to.

You could try integrating pcilib or libpciaccess into your test application if you need to directly manipulate these MSI-X registers.

**Comment by aohzju** [comment]
Thanks, Jim. Perhaps the spdk APIs should return a value indicating the failure.

**Comment by jimharris** [comment]
The SPDK APIs do return status from these APIs.  SPDK is returning the status it receives from the corresponding DPDK rte_pci_write_config call.

If you're already checking this return status, and it's returning 0, could you step through or instrument the rte_pci_write_config() code to see where things might be going wrong?

**Comment by aohzju** [comment]
I drilled it down until the  low level function pwrite64, which returns 0 in this case. 
![image](https://user-images.githubusercontent.com/64340020/99612837-5fa07180-2a51-11eb-96a8-90a56b181dfa.png)

**Comment by jimharris** [comment]
Thanks @aohzju.  I guess there's not much DPDK or SPDK can do in that case to return an error indication.  Maybe the vfio-pci driver could return error somehow when the pwrite64 tries to write to the MSI-X capability register?  But I haven't looked into it in any detail.
