### ISSUE TITLE
lcov takes considerable time to process clang coverage

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1693]
Building spdk with clang hang on lcov.

How to enable lcov quickly with the current SPDK autorun scripts:
1.  Install llvm
2.  Create llvm-gcov.sh :
```
#!/bin/bash
exec llvm-cov gcov "$@"
```
3. Add to `LCOV_OPTS`:
```
--gcov-tool llvm-gcov.sh
```
Test configuration:
```
SPDK_RUN_VALGRIND=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_PMDK=1
SPDK_TEST_ISAL=1
SPDK_TEST_REDUCE=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_FTL=1
SPDK_TEST_OCF=1
SPDK_TEST_RAID5=1
SPDK_TEST_RBD=1
SPDK_TEST_URING=1
SPDK_TEST_NVME_CUSE=1
SPDK_TEST_BLOBFS=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
```
Above test configuration run by `autorun.sh` script takes something about one hour.

Removing `-q` parameter from lcov_opts allow me to figure out, that this files consumed most of time:
```
Processing test/unit/lib/bdev/crypto.c/crypto_ut.gcda
Processing lib/env_dpdk/env.gcda
test/unit/lib/bdev/crypto.c/crypto_ut.gcda
```

Removing additional params from  lcov_opts (`--rc lcov_branch_coverage=1 --rc lcov_function_coverage=1 --rc genhtml_branch_coverage=1 --rc genhtml_function_coverage=1 --rc genhtml_legend=1 --rc geninfo_all_blocks=1`) have no impact in this case.

**Comment by jimharris** [comment]
Marking this as an enhancement request.  Maybe also add some additional information in the description on how we use gcov today and why you want to add llvm/lcov support.

Can you confirm exactly where you hit this delay?  Is it when running the various $LCOV commands near the end of test/unit/unittest.sh?

**Comment by wawryk** [comment]
The biggest delay I noticed during this command in `test/unit/unittest.sh`:
```
$LCOV -q -d . -c -t "$(hostname)" -o $UT_COVERAGE/ut_cov_test.info
```

**Comment by tomzawadzki** [comment]
[Bug scrub] At this time the CI does not gather coverage with clang. If anyone is interested in this combination and reducing the coverage gather time, feel free to reopen the issue.
