### ISSUE TITLE
[ubuntu16/18-vg-autotest ] unable to access 'https://review.spdk.io/spdk/spdk/'

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1695]
# Issue
00:00:28.842  + set +x
00:01:06.767  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:02:39.135  fatal: unable to access 'https://review.spdk.io/spdk/spdk/': gnutls_handshake() failed: Error in the pull function.
00:02:39.148  /tmp/jenkins7447453100779926008.sh: line 38: refs: bad array subscript
00:02:39.165  Build step 'Execute shell' marked build as failure
00:02:39.233  [PostBuildScript] - [INFO] Executing post build scripts.
00:02:39.239  [ubuntu16-vg-autotest] $ /usr/bin/env bash /tmp/jenkins1192054119070418565.sh
00:02:39.243  + [[ -n ubuntu1604 ]]
00:02:39.243  + mv /var/jenkins/workspace/ubuntu16-vg-autotest/ubuntu1604-libvirt/output /var/jenkins/workspace/ubuntu16-vg-autotest/output
00:02:39.246  mv: cannot stat '/var/jenkins/workspace/ubuntu16-vg-autotest/ubuntu1604-libvirt/output': No such file or directory
00:02:39.262  [ubuntu16-vg-autotest] $ /usr/bin/env bash /tmp/jenkins10313255571168768012.sh
## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/30605/archive/ubuntu16-vg-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_30605.html

**Comment by yidong0635** [comment]
close this one, it doesn't happen for a long time for this jenkins issue,
