### ISSUE TITLE
nvmf_example test hangs on wait() [transport=rdma]

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1696]
```
SPDK:  v20.10-rc1-146-gb8c99a3aa
OS: Fedora31 (VM, kernel: 5.8.17-100.fc31)
```

Configuration:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_NVMF=1
SPDK_TEST_PMDK=1
SPDK_TEST_JSON=1
SPDK_RUN_UBSAN=1
```

Either run directly by executing `test/nvmf/nvmf.sh` or through `autotest.sh`,  the entire suite hangs indefinitely on `nvmf_example` test.  This seems to be related to the latest kernel version available for fedora31 since the very same test passes just fine under kernel 5.3 and 5.6. This concerns rdma transport (tcp works just fine).

**Comment by AlekseyMarchuk** [comment]
Hi, is it possible to attach to nvmf process with gdb and check where it hangs? E.g. execute `thread apply all bt`

**Comment by mikeBashStuff** [comment]
@AlekseyMarchuk Appreciate the response. No problem, here's the output:
[nvmf_gdb_bt.txt](https://github.com/spdk/spdk/files/5574449/nvmf_gdb_bt.txt)

Let me know if there's anything else needed to troubleshoot this further. :)

**Comment by AlekseyMarchuk** [comment]
@mikeBashStuff I didn't find anything useful in the backtrace :). I'll try to find a host/VM with Fedora31 to debug this problem

**Comment by tomzawadzki** [comment]
[Bug scrub] This issue has only been seen on the specific Fedora 31, and has not been seen since.
