### ISSUE TITLE
QP not destroyed with SPDK NVMEoF target

### ISSUE THREAD

**Issue by bharatpotnuri** [spdk/spdk#1697]
## Current Behavior
Hi All,
When running SPDK NVMEoF target run over iWARP, I see that .destroy_qp() is not invoked while connection teardown and results in QP leak.
I see this behavior only with SPDK target and not other user rdma applications.

below logs are seen on target side per connection:
[2020-11-21 00:16:05.310968] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)

## Steps to Reproduce

Here is the script I am using to create target:
```
#!/bin/bash

RPC_PATH=/home/spdk_nvme-cli/spdk/scripts

/home/spdk_nvme-cli/spdk/build/bin/nvmf_tgt -m 0x3FFF &

python3 $RPC_PATH/rpc.py nvmf_create_transport -t RDMA -u 131072 -c 8192 -n 8192 -b 256

for i in `seq 1 $1`
do
  python3 $RPC_PATH/rpc.py bdev_malloc_create -b Malloc$i 256 512
  python3 $RPC_PATH/rpc.py nvmf_create_subsystem  nqn.2016-06.io.spdk:cnode$i -a -s SPDK0000000000000$i -d SPDK_Controller$i
  python3 $RPC_PATH/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode$i Malloc$i
  python3 $RPC_PATH/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode$i -t rdma -a 10.0.3.2 -s 4420 -f ipv4
done
```

nvme command used for discover, to establish a connection, can use fio or any command:
`
nvme discover -t rdma -a 10.0.3.2 -s 4420
`

## Context (Environment including OS version, SPDK version, etc.)

spdk version: commit b8c99a3aadc85b74889815cdd22e0a8cd1b90692 
rdma-core version: v32.0 (commit 7a4f9ad9a1d906c5f2bbb18b588309c3d12460ac)
kernel: 5.4.44
Adapter: Chelsio

**Comment by changpe1** [comment]
I don't see .destroy_qp(), can you clarify which function?

**Comment by bharatpotnuri** [comment]
Update:
-> I see this behavior only if SRQ is used while creating RDMA transport.
-> QPs are destroyed once transport is removed by killing the `nvmf_tgt` process.

Now I am not sure if the QPs need to be destroyed explicitly calling ibv_destroy_qp().

**Comment by bharatpotnuri** [comment]
> 
> 
> I don't see .destroy_qp(), can you clarify which function?

I meant, the HW QP resources.
In general user rdma applications the RDMA connections are closed using rdma_disconnect() and RDMA resources like QP/SRQ are destroyed or freed when application is closed via
ib_uverbs_close() --> ib_destroy_qp_user() --> HW specific .destroy_qp() handlers.

Here in case of SPDK NVMF target, SRQ is created while transport is created and is freed only when nvmf_tgt app is killed.
So the rdma QPs associated to the SRQ during discover/login gets disconnected but not destroyed.
Now the problem is, if Connections are run in a loop, it will leak QPs and HW resources.

**Comment by changpe1** [comment]
I see, indeed SPDK doesn't call rdma_destroy_qp(). @AlekseyMarchuk does this cause potential leaks?

**Comment by AlekseyMarchuk** [comment]
Let me check it

**Comment by AlekseyMarchuk** [comment]
@bharatpotnuri I don't see resource leaks in rdma. I added several logs and checked that ibv qpair is created and later destroyed:
```
rdma.c:1327:nvmf_rdma_connect: *NOTICE*: new conn, cm_id 0x555ffc1642b0
[2020-11-24 10:34:06.416570] rdma_verbs.c:  74:spdk_rdma_qp_create: *NOTICE*: created qp 0x7fd99426a5d8 cm_id 0x555ffc1642b0
[2020-11-24 10:34:06.436171] rdma_verbs.c: 120:spdk_rdma_qp_disconnect: *NOTICE*: disconnect cm_id 0x555ffc1642b0
[2020-11-24 10:34:06.446169] rdma_verbs.c: 105:spdk_rdma_qp_destroy: *NOTICE*: destroy qp 0x7fd99426a5d8 (cm_id 0x555ffc1642b0)
[2020-11-24 10:34:06.446890] rdma.c: 911:nvmf_rdma_qpair_destroy: *NOTICE*: destroy cm_id 0x555ffc1642b0
```

You might miss qpair destruction (rdma_destroy_qp or ibv_destroy_qp) because it is done in SPDK rdma library - `lib/rdma/rdma_verbs.c:103`. This library is an abstraction over regular verbs interface and Mellanox specific direct verbs interface. Verbs implementation is used by default.

**Comment by bharatpotnuri** [comment]
> lib/rdma/rdma_verbs.c:103

Thanks for trying it out @AlekseyMarchuk 

I see different thing happening on my setup:
Here I ran nvmf_tgt under gdb and set break at `spdk_rdma_qp_destroy`, spdk_rdma_qp_destroy() is not invoked in my case. 

```
(gdb) break spdk_rdma_qp_destroy
Breakpoint 1 at 0x468990: file rdma_verbs.c, line 95.
(gdb) info break
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x0000000000468990 in spdk_rdma_qp_destroy at rdma_verbs.c:95
(gdb) c
Continuing.
[2020-11-24 18:17:32.206030] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
[2020-11-24 18:17:32.421475] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
[2020-11-24 18:17:32.579616] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
[2020-11-24 18:17:32.803022] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
[2020-11-24 18:17:32.891745] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
```

looking further.

**Comment by bharatpotnuri** [comment]
> 
> 
> > lib/rdma/rdma_verbs.c:103
> 
> Thanks for trying it out @AlekseyMarchuk
> 
> I see different scenario happening on my setup:
> Here I ran nvmf_tgt under gdb and set break at `spdk_rdma_qp_destroy`, spdk_rdma_qp_destroy() is not invoked in my case.
> 
> ```
> (gdb) break spdk_rdma_qp_destroy
> Breakpoint 1 at 0x468990: file rdma_verbs.c, line 95.
> (gdb) info break
> Num     Type           Disp Enb Address            What
> 1       breakpoint     keep y   0x0000000000468990 in spdk_rdma_qp_destroy at rdma_verbs.c:95
> (gdb) c
> Continuing.
> [2020-11-24 18:17:32.206030] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
> [2020-11-24 18:17:32.421475] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
> [2020-11-24 18:17:32.579616] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
> [2020-11-24 18:17:32.803022] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
> [2020-11-24 18:17:32.891745] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
> ```
> 
> looking further.


This check is at `lib/nvmf/rdma.c` added by this commit ` 85ff3fcea6 : rdma: Do not use the poller to handle the qpair exiting`, is avoiding calling nvmf_rdma_qpair_destroy()
```
        /* Judge whether the device is emulated by Software RoCE.
         * And it will not send last_wqe event
         */
        if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != 0 &&
            rqpair->last_wqe_reached == false) {
                return;
        }
```

**Comment by AlekseyMarchuk** [comment]
@bharatpotnuri what is the vendor ID in your case? I'm not familiar with iWARP but this check was added for soft roce - this driver doesn't generate LAST_WQE_REACHED ib event needed to cleanup the qpair. No sure but maybe iWARP also doesn't support this event. If it doesn't support it then we can detect iWARP (don't know how yet) and allow qpair destruction without LAST_WQE_REACHED event. Or as an alternative you can disable SRQ

**Comment by bharatpotnuri** [comment]
> 
> 
> @bharatpotnuri what is the `rqpair->device->attr.vendor_id` in your case? I'm not familiar with iWARP but this check was added for soft roce - this driver doesn't generate LAST_WQE_REACHED ib event needed to cleanup the qpair. No sure but maybe iWARP also doesn't support this event. If it doesn't support it then we can detect iWARP (don't know how yet) and allow qpair destruction without LAST_WQE_REACHED event. Or as an alternative you can disable SRQ

In may case it is 0x1425. I doubt if this check is correct. Vendor ID for softroce is 0xFFFFF. Vendor id is non zero for other vendor devices too. This check passes for all devices.
I am not sure about this LAST_WQE_REACHED event. I am checking that part.
Most importantly above check was added to prevent double free. Now with commit `fdf2490a32412    nvmf/rdma: Don't destroy qpair if rdma_accept fails`, it wont happen and this check for softroce devices would be redundant.

**Comment by AlekseyMarchuk** [comment]
A small correction, if we are talking about this check `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != 0 && rqpair->last_wqe_reached == false)` then it was added due to softroce doesn't send LAST_WQE_REACHED event, so we can't destroy a qpair when we are using softroce with SRQ. Regarding a commit that you mentioned - it covers the case when rdma_accept fails and in this case NVMF qpair is in SPDK_NVMF_QPAIR_UNINITIALIZED state and we will use another qpair destruction path, i.e. we won't call `nvmf_rdma_destroy_drained_qpair` and will directly destroy the qpair.

**Comment by bharatpotnuri** [comment]
> 
> 
> A small correction, if we are talking about this check `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != 0 && rqpair->last_wqe_reached == false)` then it was added due to softroce doesn't send LAST_WQE_REACHED event, so we can't destroy a qpair when we are using softroce with SRQ. Regarding a commit that you mentioned - it covers the case when rdma_accept fails and in this case NVMF qpair is in SPDK_NVMF_QPAIR_UNINITIALIZED state and we will use another qpair destruction path, i.e. we won't call `nvmf_rdma_destroy_drained_qpair` and will directly destroy the qpair.

Right, I was talking about the check. The commit `85ff3fcea6` that added the check has multiple reasons. from the commit description, it looks like this is solving a segfault.
I think the check for softroce isn't working as expected and the segfault is solved by your `fdf2490a32412`.
Right check would be something like this:
`
if (rqpair->srq != NULL && rqpair->device->attr.vendor_id == 0XFFFFFF && rqpair->last_wqe_reached == false)
`

```
commit 85ff3fcea673b3b90d465320280a6f94ad69a28e
Author: Ziye Yang <ziye.yang@intel.com>
Date:   Tue Aug 4 23:24:01 2020 +0800

    rdma: Do not use the poller to handle the qpair exiting.

    Generally, this patch did the following work:

    Remove the destruct poller. I think that we do not need this,
    the destruct poller is specially for Software RoCE case.
    Since SoftRoCE will not have IBV_EVENT_QP_LAST_WQE_REACHED event,
    we will not wait the last_wqe_reached flag when srq is enabled.
    So we can avoid using the poller.

    And the purpose of this patch is to solve the coredump issue.
    For example, if we run rdma local test such as, e.g.,

    test/nvmf/host/bdevperf.sh --transport=rdma

    The coredump reason: the qpair is freed twice. Because for RDMA transport,
    we do not really remove the qpair from the group if the upper layer
    does it.

    The first time is called by nvmf_rdma_destroy_drained_qpair in nvmf_rdma_poller_poll,
    and the second time is called by nvmf_rdma_qpair_reject_connection in
    in nvme_rdma_close_qpair. Since nvme_rdma_close_qpair will always called,
    so we need make sure that the qpair will be close after calling this function.
    Otherwise we will have the double free qpair. So our approach here is add a flag
    ("to_close")in rqpair structure and make sure the rqpair be freed after the
    "to_close" is set  nvme_rdma_close_qpair
```

I have tried bypassing the check and it works fine for me, except the disconnect logs.
`
[2020-11-21 00:16:05.310968] rdma_verbs.c: 119:spdk_rdma_qp_disconnect: ERROR: rdma_disconnect failed, errno Invalid argument (22)
`
This is an unwanted error log that I'll probably raise in a new issue.

**Comment by AlekseyMarchuk** [comment]
Could you clarify where you found that softroce vendor id is 0XFFFFFF? I checked driver's code and as I see,  when we create a softroce device we don't initialize attr.vendor_id, so it remains 0 after kzmalloc. 
Also let me clarify that this check `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != 0 && rqpair->last_wqe_reached == false)` can be re-written to `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != SOFT_ROCE_VENDOR_ID && rqpair->last_wqe_reached == false)` where `SOFT_ROCE_VENDOR_ID ` is 0 or 0XFFFFFF. 
In your last comment you wrote that you modified it to `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id == 0XFFFFFF && rqpair->last_wqe_reached == false)` please pay attention to this part `attr.vendor_id == 0XFFFFFF`. I think that is not correct since the intention of this check is:
1. Make sure that we received LAST_WQE_REACHED if we are using SRQ before destroying the qpair. If we delete a qpair without LAST_WQE_REACHED event we can leak Work Completions in SRQ
2. But if we are using rxe we can ignore this condition (I mean LAST_WQE_REACHED) since it is a known issue that rxe doesn't generate this event.
With this change you ignore this check since your vendor_id is highly likely is not 0XFFFFFF
I think that we need to understand whether iWARP supports LAST_WQE_REACHED ibv event. If it doesn't support it then we can modify this check to also ignore iWARP devices like
```
bool ignore_last_wqe = rqpair->device->attr.vendor_id == SOFT_ROCE_VENDOR_ID || 
                  rqpair->device->context->device->transport_type == IBV_TRANSPORT_IWARP;
if (rqpair->srq != NULL && rqpair->last_wqe_reached == false && !ignore_last_wqe) {
    return;
{
```

**Comment by bharatpotnuri** [comment]
@AlekseyMarchuk 
I see it from linux softroce code `drivers/infiniband/sw/rxe/rxe_param.h`
```
        RXE_VENDOR_ID                   = 0XFFFFFF,
```
Here in `drivers/infiniband/sw/rxe/rxe.c`, it is initialized.
```
/* initialize rxe device parameters */
static void rxe_init_device_param(struct rxe_dev *rxe)
{
        rxe->max_inline_data                    = RXE_MAX_INLINE_DATA;

        rxe->attr.vendor_id                     = RXE_VENDOR_ID;
        rxe->attr.max_mr_size                   = RXE_MAX_MR_SIZE;
        rxe->attr.page_size_cap                 = RXE_PAGE_SIZE_CAP;
        rxe->attr.max_qp                        = RXE_MAX_QP;
```

**Comment by bharatpotnuri** [comment]
> 
> 
> Could you clarify where you found that softroce vendor id is 0XFFFFFF? I checked driver's code and as I see, when we create a softroce device we don't initialize attr.vendor_id, so it remains 0 after kzmalloc.
> Also let me clarify that this check `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != 0 && rqpair->last_wqe_reached == false)` can be re-written to `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != SOFT_ROCE_VENDOR_ID && rqpair->last_wqe_reached == false)` where `SOFT_ROCE_VENDOR_ID ` is 0 or 0XFFFFFF.
> In your last comment you wrote that you modified it to `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id == 0XFFFFFF && rqpair->last_wqe_reached == false)` please pay attention to this part `attr.vendor_id == 0XFFFFFF`. I think that is not correct since the intention of this check is:
> 
>     1. Make sure that we received LAST_WQE_REACHED if we are using SRQ before destroying the qpair. If we delete a qpair without LAST_WQE_REACHED event we can leak Work Completions in SRQ
> 
>     2. But if we are using rxe we can ignore this condition (I mean LAST_WQE_REACHED) since it is a known issue that rxe doesn't generate this event.
>        With this change you ignore this check since your vendor_id is highly likely is not 0XFFFFFF
>        I think that we need to understand whether iWARP supports LAST_WQE_REACHED ibv event. If it doesn't support it then we can modify this check to also ignore iWARP devices like
> 
@AlekseyMarchuk  yeah I understand your point. last_wqe_reached is always 0 in my case and I see from code that Chelsio devices doesn't support LAST_WQE_REACHED. I trying to confirm if we can safely say all iwarp devices dont support LAST_WQE_REACHED.

**Comment by AlekseyMarchuk** [comment]
> @AlekseyMarchuk
> I see it from linux softroce code `drivers/infiniband/sw/rxe/rxe_param.h`
> 
> ```
>         RXE_VENDOR_ID                   = 0XFFFFFF,
> ```
> 

Thanks, I was looking at kernel version `Linux 5.5-rc1` and there was no such definition and initialization of `rxe->attr.vendor_id`. That was added in 0184afd15a141d7ce24c32c0d86a1e3ba6bc0eb3 in April. I think we need to take it into account in SPDK

**Comment by tomzawadzki** [comment]
Just for future reference, patch adding the vendor_id for SoftRoCE is available here:
https://review.spdk.io/gerrit/c/spdk/spdk/+/5307

**Comment by bharatpotnuri** [comment]
> 
> 
> > Could you clarify where you found that softroce vendor id is 0XFFFFFF? I checked driver's code and as I see, when we create a softroce device we don't initialize attr.vendor_id, so it remains 0 after kzmalloc.
> > Also let me clarify that this check `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != 0 && rqpair->last_wqe_reached == false)` can be re-written to `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id != SOFT_ROCE_VENDOR_ID && rqpair->last_wqe_reached == false)` where `SOFT_ROCE_VENDOR_ID ` is 0 or 0XFFFFFF.
> > In your last comment you wrote that you modified it to `if (rqpair->srq != NULL && rqpair->device->attr.vendor_id == 0XFFFFFF && rqpair->last_wqe_reached == false)` please pay attention to this part `attr.vendor_id == 0XFFFFFF`. I think that is not correct since the intention of this check is:
> > ```
> > 1. Make sure that we received LAST_WQE_REACHED if we are using SRQ before destroying the qpair. If we delete a qpair without LAST_WQE_REACHED event we can leak Work Completions in SRQ
> > 
> > 2. But if we are using rxe we can ignore this condition (I mean LAST_WQE_REACHED) since it is a known issue that rxe doesn't generate this event.
> >    With this change you ignore this check since your vendor_id is highly likely is not 0XFFFFFF
> >    I think that we need to understand whether iWARP supports LAST_WQE_REACHED ibv event. If it doesn't support it then we can modify this check to also ignore iWARP devices like
> > ```
> 
> @AlekseyMarchuk yeah I understand your point. last_wqe_reached is always 0 in my case and I see from code that Chelsio devices doesn't support LAST_WQE_REACHED. I trying to confirm if we can safely say all iwarp devices dont support LAST_WQE_REACHED.

Hi @AlekseyMarchuk,
From linux code looks like not many rdma devices /vendors support LAST_WQE_REACHED. 
Can this be checked some how in spdk?

Thanks.

**Comment by AlekseyMarchuk** [comment]
Hi @bharatpotnuri I checked, iWARP doesn't support LAST_WQE_REACHED event. I think we can ignore it but there is a chance that we will need to cleanup all WQEs related to a qpair being destroyed that are not completed yet and queued in SRQ. That needs further investigation. For now I'm preparing a patch to simply ignore this event for iWARP so that you can test it and check if a proper cleanup needs to be done.

**Comment by bharatpotnuri** [comment]
> 
> 
> Hi @bharatpotnuri I checked, iWARP doesn't support LAST_WQE_REACHED event. I think we can ignore it but there is a chance that we will need to cleanup all WQEs related to a qpair being destroyed that are not completed yet and queued in SRQ. That needs further investigation. For now I'm preparing a patch to simply ignore this event for iWARP so that you can test it and check if a proper cleanup needs to be done.

@AlekseyMarchuk Thanks. Agreed, I've been thinking if some sort of drain_srq() can do the job. Shall check the possible scenarios and update.

**Comment by AlekseyMarchuk** [comment]
@bharatpotnuri please check this commit which ignores LAST_WQE_REACHED for iWARP https://review.spdk.io/gerrit/c/spdk/spdk/+/5474

**Comment by bharatpotnuri** [comment]
> 
> 
> @bharatpotnuri please check this commit which ignores LAST_WQE_REACHED for iWARP https://review.spdk.io/gerrit/c/spdk/spdk/+/5474

Patch works as expected. Thanks @AlekseyMarchuk !

**Comment by bharatpotnuri** [comment]
4ede905352536e1671fd1f6fd947a27b87202526 is merged. so closing the issue.
Thanks @AlekseyMarchuk !!

**Comment by AlekseyMarchuk** [comment]
@bharatpotnuri You are welcome) Please let us know if iWARP SRQ clean up process needs to be implemented

**Comment by bharatpotnuri** [comment]
> @bharatpotnuri You are welcome) Please let us know if iWARP SRQ clean up process needs to be implemented

Sure, I'll let you know.
