### ISSUE TITLE
iscsi_tgt segmentation fault

### ISSUE THREAD

**Issue by linwenbo** [spdk/spdk#1699]
use iscsi_tgt as iscsi target. use 2 initiator to test performance and I got segmentation fault on target node.

## Current Behavior
(gdb) bt
#0  0x00000000004a2ca9 in spdk_iscsi_task_is_read (task=0x20002b8818c0) at /root/spdk.git.149/lib/iscsi/task.h:164
#1  0x00000000004a51d5 in spdk_iscsi_task_cpl (scsi_task=0x20002b8818c0) at conn.c:1115
#2  0x00000000004c25de in spdk_scsi_lun_complete_task (lun=0x3469800, task=0x20002b8818c0) at lun.c:48
#3  0x00000000004c5a93 in bdev_scsi_task_complete_cmd (bdev_io=0x200007281c80, success=true, cb_arg=0x20002b8818c0) at scsi_bdev.c:1171
#4  0x000000000049e23e in _spdk_bdev_io_complete (ctx=0x200007281c80) at bdev.c:3799
#5  0x000000000049e535 in spdk_bdev_io_complete (bdev_io=0x200007281c80, status=SPDK_BDEV_IO_STATUS_SUCCESS) at bdev.c:3883
#6  0x00000000004799f9 in bdev_aio_group_poll (arg=0x346c8d0) at bdev_aio.c:337
#7  0x00000000004cd150 in spdk_thread_poll (thread=0x341c370, max_msgs=0, now=1399388586596216) at thread.c:476
#8  0x000000000048bdd5 in _spdk_reactor_run (arg=0x2789240) at reactor.c:365
#9  0x000000000048c103 in spdk_reactors_start () at reactor.c:468
#10 0x000000000048a717 in spdk_app_start (opts=0x7fff20e23f30, start_fn=0x405ee1 <spdk_startup>, arg1=0x0) at app.c:691
#11 0x0000000000406073 in main (argc=3, argv=0x7fff20e240c8) at iscsi_tgt.c:112
(gdb) up
#1  0x00000000004a51d5 in spdk_iscsi_task_cpl (scsi_task=0x20002b8818c0) at conn.c:1115
1115	
(gdb) p pdu
$1 = (struct spdk_iscsi_pdu *) 0x0

## Steps to Reproduce

iscsi.conf:
[PortalGroup1]
  Portal DA1 14.254.4.71:3260
[InitiatorGroup1]
  InitiatorName ANY
  Netmask 14.254.4.0/24
[AIO]
  AIO /dev/vg1/lv0 AIO0
  AIO /dev/vg1/lv1 AIO1
  AIO /dev/vg1/lv2 AIO2
  AIO /dev/vg1/lv3 AIO3
  AIO /dev/vg2/lv0 AIO4
  AIO /dev/vg2/lv1 AIO5
  AIO /dev/vg2/lv2 AIO6
  AIO /dev/vg2/lv3 AIO7

[TargetNode1]
  TargetName disk1
  TargetAlias "Data Disk1"
  Mapping PortalGroup1 InitiatorGroup1
  AuthMethod Auto
  AuthGroup AuthGroup1
  UseDigest Auto
  LUN0 AIO0
  QueueDepth 256
  LUN1 AIO1
  QueueDepth 256
  LUN2 AIO2
  QueueDepth 256
  LUN3 AIO3
  QueueDepth 256
  LUN4 AIO4
  QueueDepth 256
  LUN5 AIO5
  QueueDepth 256
  LUN6 AIO6
  QueueDepth 256
  LUN7 AIO7
  QueueDepth 256

## Context (Environment including OS version, SPDK version, etc.)

SPDK v19.10
OS centos7.5.1804

**Comment by shuhei-matsumoto** [comment]
Hi @linwenbo 

Thank you for posting this issue. If possible, will you run the same test on SPDK 20.10 or the latest master and check if you still see the same issue? We have added a couple of critical fixes after 19.01.

-Shuhei

**Comment by optimistyzy** [comment]
@yidong0635 Can you replace this issuse with SPDK master branch?  //Currently, we cannot use configuration file, you need to transfer the configuration into RPC or json.   Thanks.

**Comment by linwenbo** [comment]
I runed the same test on branch v20.10  and  everything OK.

**Comment by shuhei-matsumoto** [comment]
Thank you @linwenbo  We all are good to know that.

**Comment by optimistyzy** [comment]
> @yidong0635 Can you replace this issuse with SPDK master branch? //Currently, we cannot use configuration file, you need to transfer the configuration into RPC or json. Thanks.

@yidong0635  you do not need to test it again since this issue is closed. And @linwenbo confirms that no issues are related with the latest SPDK version.
