### ISSUE TITLE
Unrecovered read error - 

### ISSUE THREAD

**Issue by hlitz** [spdk/spdk#17]
Hi 
spdk's perf application ran fine for a while but since recently I am getting this:

Created task_pool
Initializing NVMe Controllers
associate_workers_with_ns()
Associating INTEL SSDPEDMW400G4  (CVCQ514500A2400AGN  ) with lcore 0
Starting thread on core 0
READ sqid:1 cid:113 nsid:1 lba:95459283 len:1
UNRECOVERED READ ERROR (02/81) sqid:1 cid:113 cdw0:0 sqhd:00db p:1 m:1 dnr:0

I tried to reformat the device via nvme-cli which fails as well:

 sudo ./nvme format /dev/nvme0n1 --lbaf=03
ioctl: Interrupted system call

any ideas?

**Comment by benlwalker** [comment]
We need to narrow down the problem a bit. Can you provide the following two pieces of information:

* The command line arguments passed to perf when you produce this error
* The output of our identify example (it will be long)

That should be enough information for us to give you an idea of what's going on.

**Comment by hlitz** [comment]
perf cmd: sudo ./perf -s 4096 -q 64 -w randrw -M 100 -c 1 -t 60

How do I generate the output of my identify example? Do you mean this (obtained with nvme-cli)?

$ sudo ./nvme id-ctrl /dev/nvme0
NVME Identify Controller:
vid     : 0x8086
ssvid   : 0x8086
sn      : CVCQ514500A2400AGN
mn      : INTEL SSDPEDMW400G4
fr      : 8EV10135
rab     : 0
ieee    : 5cd2e4
cmic    : 0
mdts    : 5
cntlid  : 0
ver     : 0
rtd3r   : 0
rtd3e   : 0
oaes    : 0
oacs    : 0x6
acl     : 3
aerl    : 3
frmw    : 0x2
lpa     : 0
elpe    : 63
npss    : 0
avscc   : 0
apsta   : 0
wctemp  : 0
cctemp  : 0
mtfa    : 0
hmmin   : 0
tnvmcap : 0
unvmcap : 0
rpmbs   : 0
sqes    : 0x66
cqes    : 0x44
nn      : 1
oncs    : 0x6
fuses   : 0
fna     : 0x7
vwc     : 0
awun    : 0
awupf   : 0
nvscc   : 0
acwu    : 0
sgls    : 0
ps    0 : mp:2500 flags:0 enlat:0 exlat:0 rrt:0 rrl:0
          rwt:0 rwl:0 idlp:0 ips:0 actp:0 ap flags:0

**Comment by benlwalker** [comment]
You can run our identify example much like our perf example

```bash
sudo ./examples/nvme/identify/identify
```

Our identify example prints out all of the additional log pages and will tell us a lot about your device.

**Comment by hlitz** [comment]
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 4 on socket 0
EAL: Detected lcore 5 as core 5 on socket 0
EAL: Detected lcore 6 as core 0 on socket 1
EAL: Detected lcore 7 as core 1 on socket 1
EAL: Detected lcore 8 as core 2 on socket 1
EAL: Detected lcore 9 as core 3 on socket 1
EAL: Detected lcore 10 as core 4 on socket 1
EAL: Detected lcore 11 as core 5 on socket 1
EAL: Detected lcore 12 as core 0 on socket 0
EAL: Detected lcore 13 as core 1 on socket 0
EAL: Detected lcore 14 as core 2 on socket 0
EAL: Detected lcore 15 as core 3 on socket 0
EAL: Detected lcore 16 as core 4 on socket 0
EAL: Detected lcore 17 as core 5 on socket 0
EAL: Detected lcore 18 as core 0 on socket 1
EAL: Detected lcore 19 as core 1 on socket 1
EAL: Detected lcore 20 as core 2 on socket 1
EAL: Detected lcore 21 as core 3 on socket 1
EAL: Detected lcore 22 as core 4 on socket 1
EAL: Detected lcore 23 as core 5 on socket 1
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 24 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: Ask a virtual area of 0xa400000 bytes
EAL: Virtual area found at 0x7f3914800000 (size = 0xa400000)
EAL: Ask a virtual area of 0x3ec00000 bytes
EAL: Virtual area found at 0x7f38d5a00000 (size = 0x3ec00000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f38d5600000 (size = 0x200000)
EAL: Ask a virtual area of 0x1b5800000 bytes
EAL: Virtual area found at 0x7f371fc00000 (size = 0x1b5800000)
EAL: Ask a virtual area of 0x400000 bytes
EAL: Virtual area found at 0x7f371f600000 (size = 0x400000)
EAL: Ask a virtual area of 0x800000 bytes
EAL: Virtual area found at 0x7f371ec00000 (size = 0x800000)
EAL: Ask a virtual area of 0xa00000 bytes
EAL: Virtual area found at 0x7f371e000000 (size = 0xa00000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f371dc00000 (size = 0x200000)
EAL: Ask a virtual area of 0x1ff800000 bytes
EAL: Virtual area found at 0x7f351e200000 (size = 0x1ff800000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f351de00000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f351da00000 (size = 0x200000)
EAL: Ask a virtual area of 0x200000 bytes
EAL: Virtual area found at 0x7f351d600000 (size = 0x200000)
EAL: Requesting 4096 pages of size 2MB from socket 0
EAL: Requesting 4096 pages of size 2MB from socket 1
EAL: TSC frequency is ~2299998 KHz
EAL: Master lcore 0 is ready (tid=21e46940;cpuset=[0])
=====================================================
NVMe Controller at PCI bus 4, device 0, function 0
=====================================================
Controller Capabilities/Features
================================
Vendor ID:                  8086
Subsystem Vendor ID:        8086
Serial Number:              CVCQ514500A2400AGN
Model Number:               INTEL SSDPEDMW400G4
Firmware Version:           8EV10135
Recommended Arb Burst:      0
IEEE OUI Identifier:        e4 d2 5c
Multi-Interface Cap:        00
Max Data Transfer Size:     131072
Error Recovery Timeout:     Unlimited

Admin Command Set Attributes
============================
Security Send/Receive:       Not Supported
Format NVM:                  Supported
Firmware Activate/Download:  Supported
Abort Command Limit:         4
Async Event Request Limit:   4
Number of Firmware Slots:    1
Firmware Slot 1 Read-Only:   No
Per-Namespace SMART Log:     No
Error Log Page Entries:      64

NVM Command Set Attributes
==========================
Submission Queue Entry Size
  Max:                       64
  Min:                       64
Completion Queue Entry Size
  Max:                       16
  Min:                       16
Number of Namespaces:        1
Compare Command:             Not Supported
Write Uncorrectable Command: Supported
Dataset Management Command:  Supported
Volatile Write Cache:        Not Present

Arbitration
===========
Arbitration Burst:           1
Low Priority Weight:         1
Medium Priority Weight:      1
High Priority Weight:        1

Power Management
================
Number of Power States:      1
Current Power State:         Power State #0
Power State #0:  Max Power:  25.00 W

Health Information
==================
Critical Warnings:
  Available Spare Space:     OK
  Temperature:               OK
  Device Reliability:        OK
  Read Only:                 No
  Volatile Memory Backup:    OK
Current Temperature:         309 Kelvin (36 Celsius)
Temperature Threshold:       358 Kelvin (85 Celsius)
Available Spare:             99%
Life Percentage Used:        7%
Data Units Read:             3437671
Data Units Written:          2180832
Host Read Commands:          25046163124
Host Write Commands:         15129535402
Controller Busy Time:        3759 minutes
Power Cycles:                7
Power On Hours:              2991 hours
Unsafe Shutdowns:            5
Unrecoverable Media Errors:  7
Lifetime Error Log Entries:  7

Namespace ID:1
Deallocate:                  Supported
Flush:                       Not Supported
Size (in LBAs):              97677846 (93M)
Capacity (in LBAs):          97677846 (93M)
Utilization (in LBAs):       97677846 (93M)
Thin Provisioning:           Not Supported
Number of LBA Formats:       7
Current LBA Format:          LBA Format #03
LBA Format #00: Data Size:   512  Metadata Size:     0
LBA Format #01: Data Size:   512  Metadata Size:     8
LBA Format #02: Data Size:   512  Metadata Size:    16
LBA Format #03: Data Size:  4096  Metadata Size:     0
LBA Format #04: Data Size:  4096  Metadata Size:     8
LBA Format #05: Data Size:  4096  Metadata Size:    64
LBA Format #06: Data Size:  4096  Metadata Size:   128

**Comment by benlwalker** [comment]
Everything looks ok with your device except these lines:

> Unrecoverable Media Errors: 7
> Lifetime Error Log Entries: 7

There are special log entries describing those errors, but our tool doesn't print those out yet. I'm going to make a patch to add that to our identify tool. Once I push that out, I'll have you run it again.

**Comment by benlwalker** [comment]
Actually, since you already have nvme-cli installed, you can use that to get the error logs.

```bash
sudo nvme error-log /dev/nvme0
```

You only need to paste the first 7 entries - not all 64. I'll still work on adding this to our tool in the mean time.

**Comment by hlitz** [comment]
thanks Ben awesome support here. Below is the nvme-cli dump, only the first error entry contains anything, shouldn't the error count be 7? anyways:

$ sudo nvme error-log /dev/nvme0
Error Log Entries for device:/dev/nvme0 entries:64
.................
 Entry[ 0]
.................
error_count  : 1
sqid         : 1
cmdid        : 0x69
status_field : 0x4502
parm_err_loc : 0
lba          : 0x1190b298
nsid         : 1
vs           : 0
.................
 Entry[ 1]
.................
error_count  : 0
sqid         : 0
cmdid        : 0
status_field : 0
parm_err_loc : 0
lba          : 0
nsid         : 0
vs           : 0

**Comment by benlwalker** [comment]
Ok, here's my working theory. I don't think this is a problem with SPDK or the device.

I suspect that you initialized your disk with data, but since then have been doing only reads (`-M 100` is all reads). At some point in time, a cosmic ray or latent heat or something flipped some bits in your NAND. When you now read the sector that was corrupted, the device's CRC check fails and it reports the UNRECOVERED READ ERROR. I'd like to try and prove this using dd. If you bind the device back to the kernel driver (`./scripts/setup.sh reset`), you can try to read from the sector where the error occurred directly with:

```bash
sudo dd if=/dev/nvme0n1 of=/dev/null skip=95459283 bs=4K count=1 iflag=direct
```

Try that and see if it fails. If it does fail, try writing over the sector with 0's to replace the data with new data, which regenerates matching CRCs, and then reading it again:

```bash
sudo dd if=/dev/zero of=/dev/nvme0n1 skip=95459283 bs=4K count=1 oflag=direct
sudo dd if=/dev/nvme0n1 of=/dev/null skip=95459283 bs=4K count=1 iflag=direct
```

Let me know how that goes.

**Comment by hlitz** [comment]
Hi Ben,
I think your hypothesis is correct. I wrote all sectors of the device and I can now again read from it :+1: 

thanks again!
