### ISSUE TITLE
SPDK NVMe CLI hung up only when formatting specific vendor's NVMe SSD just after power on

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1701]
My colleague (SPDK end user) reported an issue.

When we format a specific vendor's NVMe SSD (Kioxia, formerly Toshiba Memory) via SPDK NVMe CLI, SPDK NVMe CLI hung up.

## Expected Behavior

Retry after forceful termination

```
[root@localhost examples]# ./nvme_manage 

(snip)

0000:07:00.00 SNB5A-R1R9NC                             CTN020WM                 2

Please Input PCI Address(domain:bus:dev.func):

0000:07:00.00

Please Input Namespace ID (1 - 16):

1

(snip)

Warning: use this utility at your own risk.

This command will format your namespace and all data will be lost.

This command may take several minutes to complete,

so do not interrupt the utility until it completes.

Press 'Y' to continue with the format operation.

y

[2020-11-19 08:50:43.131706] nvme_ctrlr.c:1393:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller

press Enter to display cmd menu ...

 

NVMe Management Options (<-- completed successfully)

        [1: list controllers]

        [2: create namespace]

        [3: delete namespace]

        [4: attach namespace to controller]

        [5: detach namespace from controller]

        [6: format namespace or controller]

        [7: firmware update]

        [8: opal]

        [9: quit]

```

## Current Behavior

```
[root@localhost examples]# ./nvme_manage

(snip)

0000:07:00.00 SNB5A-R1R9NC                             CTN020WM                 2

Please Input PCI Address(domain:bus:dev.func):

0000:07:00.00

Please Input Namespace ID (1 - 16):

1

(snip)

Warning: use this utility at your own risk.

This command will format your namespace and all data will be lost.

This command may take several minutes to complete,

so do not interrupt the utility until it completes.

Press 'Y' to continue with the format operation.

y 

(No response, LED of drive continued blinking slowly. LED was simply on when idle)                                                                                 

 

 

^C 
(After 12 hours, we terminated forcefully. Then LED returned to idle)

 
```
## Steps to Reproduce

1. Power on NVMe SSD drive.
2. format by SPDK NVMe CLI

After 12 hours without any response, we terminated SPDK NVMe CLI forcefully, and then retried formatting. However, format completed successfully.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.10 (SPDK 18.01 did not cause this issue).
Kioxia NVMe SSD (Intel or Western DIgital's NVMe SSD don't have any issue.)

**Comment by shuhei-matsumoto** [comment]
I'm asking my colleague to narrow down the version from which the issue occurs. I will share any update here.

**Comment by shuhei-matsumoto** [comment]
My colleague identified from which version this issue occurred. It looks that this issue occurs from SPDK18.07.

**Comment by yidong0635** [comment]
This issue looks the same that I met in #1723. At that time I ready to format a disk (Intel Corporation NVMe Datacenter SSD [3DNAND, Beta Rock Controller]), It's no response, but can't be reproduced after that time.

**Comment by rmvasuki** [comment]
@shuhei-matsumoto We also see this error with Kioxia drives. Our application has set up a 15s timeout, and we see that the Controller Fatal Status (CFS) bit is set when the timeout is seen after issuing a format command.
The format command works fine when using the kernel nvme driver, but does not work with SPDK cli/SPDK nvme-cli. We are using SPDK 20.07.

**Comment by balamsg** [comment]
The issue seems to be because of the AER command which is sent during the controller initialization.
When the drives are tested with the spdk nvmecli , the SQE for format command contains the [ SQTail: 13 , CID:23 ] and the corresponding CQE has [SQHD: 13, CID: 22]. This Command id 22 corresponds to the AER command which was submitted during the controller init. 
Without this AER submission the format command is working.

**Comment by balamsg** [comment]
@shuhei-matsumoto  When the format command is issued, the Kioxia drive issues a AEN ( Namespace Attribute Change Notice ) which calls the callback function nvme_ctrlr_async_event_cb( ) . Inside this callback function, there are SYNCHRONOUS submissions of 2 commands which is Active Ns List & Identify Ns. I doubt whether this should be a synchronous submissions ? because the application has already issued a format command & waiting for the completion, and this synchronous submissions is called from the completion callback. I have tried making these submissions as  Asynchronous and the format is working.

**Comment by shuhei-matsumoto** [comment]
@balamsg 

Thank you, that's great update!  How about submitting patches to fix this issue if possible according to https://spdk.io/development/ ?

This issue was pretty urgent for my colleague and I backported the necessary feature onto the older SPDK as workaround, but the true fix was anticipated.

@jimharris Thanks for raising this issue in today's meeting. Please share here if you have any.

**Comment by shuhei-matsumoto** [comment]
@yidong0635 @rmvasuki 

Thanks for sharing your update too. I had worked on creating a workaround but had not checked any update.
Sorry for my delayed response.

**Comment by shuhei-matsumoto** [comment]
test
[test.log](https://github.com/spdk/spdk/files/6226209/test.log)
