### ISSUE TITLE
No response to reservation register action in test reserve

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1702]
We run reservation test(test/nvme/reserve/reserve) but no response from controller, 
we are sure that drive supports reservation feature through nvme cli command lines.
The cause seems to be unable to poll completion successfully so enter the infinite polling procedure.
attach the log displayed by the reserve test:

```
=====================================================
NVMe Controller at PCI bus 2, device 0, function 0
=====================================================
Reservations:                Supported
Using 64-bit host identifier
Set Feature: Host Identifier:
00000000  ab ab ab ab cd cd cd cd                            ........
Using 64-bit host identifier
Get Feature: Host Identifier:
00000000  ab ab ab ab cd cd cd cd                            ........


```
please help to clarify this issue, thanks!

**Comment by yidong0635** [comment]
@ryderhsu0129  Can you debug using GDB to see it blocked at what step on your side?

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 Can you debug using GDB to see it blocked at what step on your side?

@yidong0635 
it's unable to poll completion successfully so enter the infinite polling procedure(while loop).

```
	ret = spdk_nvme_ns_cmd_reservation_register(ns, qpair, &rr_data, true,
			action,
			SPDK_NVME_RESERVE_PTPL_CLEAR_POWER_ON,
			reservation_ns_completion, NULL);
	if (ret) {
		fprintf(stderr, "Reservation Register Failed\n");
		return -1;
	}

	g_outstanding_commands++;
	while (g_outstanding_commands) {
		spdk_nvme_qpair_process_completions(qpair, 100);
	}
```

**Comment by changpe1** [comment]
Is this related with your drives? you may add a debug log in reservation_ns_completion() to see the reservation register command is executed before polling the IO queue.

**Comment by ryderhsu0129** [comment]
> Is this related with your drives? you may add a debug log in reservation_ns_completion() to see the reservation register command is executed before polling the IO queue.

@changpe1 

We only have one drive that supports reservation feature,
and the result of testing it on the nvme-cli is successful.

We added a debug log in reservation_ns_completion() but the log was not printed, 
do you have any other suggestions to clarify this problem? thanks!

**Comment by changpe1** [comment]
Can you clear your drive's reservation and run again? I guess if the drive contains old reservation.

**Comment by ryderhsu0129** [comment]
@changpe1 

I'm sure that reservation has been cleared,
even if it is not cleared, 
It should also receive the error status code, not no response?

**Comment by ryderhsu0129** [comment]
I use the same drive and commands through the linux's ioctl mechanism to test reservation feature, it seems to be working well,
are there other ways to try to clarify this issue?

**Comment by changpe1** [comment]
> I use the same drive and commands through the linux's ioctl mechanism to test reservation feature, it seems to be working well,
> are there other ways to try to clarify this issue?

Can you show me the output from "nvme resv-report" using the kernel driver?
I guess your drive may contain the old reservation information before running this test utility.

**Comment by ryderhsu0129** [comment]
> > I use the same drive and commands through the linux's ioctl mechanism to test reservation feature, it seems to be working well,
> > are there other ways to try to clarify this issue?
> 
> Can you show me the output from "nvme resv-report" using the kernel driver?
> I guess your drive may contain the old reservation information before running this test utility.

@changpe1 

the output from "nvme resv-report":
```
NVME Reservation Report success

NVME Reservation status:

gen       : 0
rtype     : 0
regctl    : 0
ptpls     : 0
```

If my drive contain the old reservation,
I should get a status of reservation conflict when I execute test utility that try to re-register reservation key, not no any response.

**Comment by changpe1** [comment]
> > > I use the same drive and commands through the linux's ioctl mechanism to test reservation feature, it seems to be working well,
> > > are there other ways to try to clarify this issue?
> > 
> > 
> > Can you show me the output from "nvme resv-report" using the kernel driver?
> > I guess your drive may contain the old reservation information before running this test utility.
> 
> @changpe1
> 
> the output from "nvme resv-report":
> 
> ```
> NVME Reservation Report success
> 
> NVME Reservation status:
> 
> gen       : 0
> rtype     : 0
> regctl    : 0
> ptpls     : 0
> ```
> 
> If my drive contain the old reservation,
> I should get a status of reservation conflict when I execute test utility that try to re-register reservation key, not no any response.

Yeah, your drive is in clear state.  can you show me the "nvme resv-register" command line ? the test utility is very easy, it build a reservation register command and send to the drive, looks like the drive didn't return a response after the submission.

**Comment by ryderhsu0129** [comment]
@changpe1 


> > > > I use the same drive and commands through the linux's ioctl mechanism to test reservation feature, it seems to be working well,
> > > > are there other ways to try to clarify this issue?
> > > 
> > > 
> > > Can you show me the output from "nvme resv-report" using the kernel driver?
> > > I guess your drive may contain the old reservation information before running this test utility.
> > 
> > 
> > @changpe1
> > the output from "nvme resv-report":
> > ```
> > NVME Reservation Report success
> > 
> > NVME Reservation status:
> > 
> > gen       : 0
> > rtype     : 0
> > regctl    : 0
> > ptpls     : 0
> > ```
> > 
> > 
> > If my drive contain the old reservation,
> > I should get a status of reservation conflict when I execute test utility that try to re-register reservation key, not no any response.
> 
> Yeah, your drive is in clear state. can you show me the "nvme resv-register" command line ? the test utility is very easy, it build a reservation register command and send to the drive, looks like the drive didn't return a response after the submission.

@changpe1 

#issue nvme-cli resv-register cmdline
`$nvme resv-register /dev/nvme0 -n 1 -r 0 -k 1 -c 0 -p 2 `

#console show as below
`NVME Reservation success`

because the behavior of the test is so simple, I can’t find out the cause of the problem.
can you help retry to run the test utility on your drive is it ok?

**Comment by changpe1** [comment]
we have daily tests for this utility:

 05:19:16	# /home/storage/workspace/opal-end-to-end-reservation-autotest/spdk/test/nvme/reserve/reserve
[2020-11-25 05:19:16.396442] Starting SPDK v21.01-pre git sha1 0d98a94901 / DPDK 20.08.0 initialization...
[2020-11-25 05:19:16.396512] [ DPDK EAL parameters: [2020-11-25 05:19:16.396524] reserve [2020-11-25 05:19:16.396532] -c 0x1 [2020-11-25 05:19:16.396539] --log-level=lib.eal:6 [2020-11-25 05:19:16.396548] --log-level=lib.cryptodev:5 [2020-11-25 05:19:16.396556] --log-level=user1:6 [2020-11-25 05:19:16.396565] --base-virtaddr=0x200000000000 [2020-11-25 05:19:16.396573] --match-allocations [2020-11-25 05:19:16.396581] --file-prefix=spdk0 [2020-11-25 05:19:16.396590] --proc-type=auto [2020-11-25 05:19:16.396598] ]
EAL: No legacy callbacks, legacy socket not created
=====================================================
NVMe Controller at PCI bus 217, device 0, function 0
=====================================================
Reservations:                Supported
Using 64-bit host identifier
Set Feature: Host Identifier:
00000000  ab ab ab ab cd cd cd cd                            ........
Using 64-bit host identifier
Get Feature: Host Identifier:
00000000  ab ab ab ab cd cd cd cd                            ........
Reservation Generation Counter                  14
Reservation type                                0
Reservation Number of Registered Controllers    0
Reservation Persist Through Power Loss State    0

**Comment by ryderhsu0129** [comment]
@changpe1 

thanks for providing this information.
So I temporarily don’t know why my drive can't run the test utility,
but can run on kernel driver.

**Comment by changpe1** [comment]
> @changpe1
> 
> thanks for providing this information.
> So I temporarily don’t know why my drive can't run the test utility,
> but can run on kernel driver.

The drive should give a response anyway, from your tests, the drive just keep silent for this command.

**Comment by ryderhsu0129** [comment]
It seems to be a problem with the drive, close this issue first.
