### ISSUE TITLE
vhost core dumped when executing sg_reset in vm

### ISSUE THREAD

**Issue by subo7** [spdk/spdk#171]
start vhost app with conf：
[Nvme]
TransportID "trtype:PCIe traddr:0000:82:00.0" Nvme0
[Split]
Split Nvme0n1 2
[VhostScsi0]
Name vhost.0
Dev 0 Nvme0n1p0
[VhostScsi1]
Name vhost.1
Dev 0 Nvme0n1p1

create 2 vms with with vhost-user-scsi-pci device using vhost.0、vhost.1
after vms running，running fio in one vm，and executing sg_reset -d in another

vhost crash：
vhost: nvme_pcie.c:1069: nvme_pcie_qpair_complete_tracker: Assertion `cpl->cid == req->cmd.cid' failed.

**Comment by jimharris** [comment]
Hi,

Can you provide the spdk git commit ID you are using when seeing this error?

Thanks,

-Jim

**Comment by jimharris** [comment]
Hi,

Are you running with SPDK 17.03 or latest master (or something in between)?

Thanks,

-Jim

**Comment by subo7** [comment]
Hi，I downloaded the source zip on Jun 15, 2017

**Comment by subo7** [comment]
I can reproduce it with commit e6d5f6c4181ea865323b4f35981655766d66370b.
it's fixed in 80161622b8d69606d05e570e70ef64ca03dd3448,
but i have got the assert 
vhost: vhost.c:235: spdk_vhost_dev_task_unref: Assertion `vdev->task_cnt > 0' failed

in laster master，issue above disappears
but i still meet another problen：
run fio in vm, and execute examples/nvme/identify -r 0000:82:00.0(NVME used by vm), fio stucks.

**Comment by pawelwod** [comment]
I can confirm identify app issue on master but only when using uio_pci_generic. With vfio identify example is denied to use NVMe device used by vhost (as expected I think).
I can't tell if this is a bug or not. @jimharris or @dverkamp-intel can you put some light on that issue?

**Comment by pawelwod** [comment]
It seam that we lack of multiprocess support in vhost library.
It can be added after 17.07 release as new feature for vhost.

**Comment by jimharris** [comment]
Thanks Pawel for your investigation on this.  Were you able to reproduce this issue (vhost w/ fio plus running identify on the host)?

Regardless, it sounds like we should close the original issue, and open a new one for this latest issue.
