### ISSUE TITLE
Access denied to ci.spdk.io status pages and artifacts

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1711]
"Access denied" message displayed when trying to access status pages and log files for some of the CI builds.

## Current Behavior

"Access denied" message displayed when trying to access status pages and log files for some of the CI builds.

## Possible Solution

Caused by a bug in CI configuration. Already solved by reverting faulty patch.
Affects builds 30926 to 31991.
Will retrigger any patches which are "Failed" and which haven't been already retriggered by the patch owner.

## Steps to Reproduce

N/A

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_31180.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_31289.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_31177.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_31174.html

**Comment by karlatec** [comment]
No more occurrences. I think we can close this one.
