### ISSUE TITLE
For centos 8 series mirroring WRITE ZERO setting does not seem to work

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#1714]
We configure a data disk for a virtual machine through vhost user blk pci. When testing on the centos8.1 image, the following prompt message will appear after formatting and mounting "blk_update_request: operation not supported error, dev vdb, sector 826298624 op 0x9: (WRITE_ZEROES) flags 0x800 phys_seg 0 prio class 0", at the bdev layer, we have a newly added device ourselves, and the io_type_supported setting only supports SPDK_BDEV_IO_TYPE_READ and SPDK_BDEV_IO_TYPE_WRITE. I understand that if this is set, the virtual machine should not Is the WRITE_ZEROES request issued? Is this a problem with the kernel driver of the virtual machine? Centos 7 series mirrors currently do not have this problem.

## Expected Behavior
No error message after mounting

## Steps to Reproduce
VM info:
```
[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 8.1.1911 (Core) 
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
1: mkfs.ext4 /dev/vdb
2: mount /dev/vdb /mnt
Then will report:
`blk_update_request: operation not supported error, dev vdb, sector 826298624 op 0x9:(WRITE_ZEROES) flags 0x800 phys_seg 0 prio class 0`

HOST info:
`vhost_blk.c: 483:process_blk_request: *NOTICE*: Can't support Write Zeroes with Unmap flag`

```
.io_type_supported    = bdev_XXX_io_type_supported,
static bool bdev_XXX_io_type_supported(void *ctx, enum spdk_bdev_io_type io_type)                                               
{
        switch (io_type) {
        case SPDK_BDEV_IO_TYPE_READ:
        case SPDK_BDEV_IO_TYPE_WRITE:
                return true;
        default:
                return false;
        }
}
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK V20.04

Thanks
      Su

**Comment by changpe1** [comment]
Can you try with SPDK malloc device to see the issue is still exist or not? You may also change the supported IO types for the malloc device.

**Comment by zlsh007** [comment]
@changpe1 We experimented with aio and local nvme devices, and the same phenomenon exists

**Comment by changpe1** [comment]
I can't reproduce this issue in my local environment with Fedora 32, can you list the attributes in your VM?

/sys/block/vda/queue/write_zeroes_max_bytes, discard_max_bytes, discard_granularity, discard_zeroes_data, max_discard_segments

**Comment by zlsh007** [comment]
```
[root@localhost queue]# cat write_zeroes_max_bytes discard_max_bytes discard_granularity discard_zeroes_data max_discard_segments 
16777216
0
0
0
1
```
I found this problem on the centos 8 series of standard mirrors. Centos 7 did not see this problem.

**Comment by zlsh007** [comment]
@changpe1 This problem only occurs after formatting as ext4 and have mount

**Comment by changpe1** [comment]
@zlsh007 I don't have a CentOS8 VM, can you test it with SPDK Malloc Bdev?

**Comment by zlsh007** [comment]
@changpe1 
At present, we modified to temporarily not support the write zero feature, so that all write zero operations in vm are converted to write operations. The vhost blk layer will support write zero featrue by default, as long as bdev supports write. For the virtual machine before the 4.18 version of the kernel, the real WRITE ZERO operation is not supported, and it will be converted into a write operation in virtio blk, but after 4.18, the real write zero command will be issued, and for ext4, after mount, it will Issue a combined command write zero + unmap, resulting in spdk the vhost blk layer prompts that this type of operation is not supported;

**Comment by changpe1** [comment]
> @changpe1
> At present, we modified to temporarily not support the write zero feature, so that all write zero operations in vm are converted to write operations. The vhost blk layer will support write zero featrue by default, as long as bdev supports write. For the virtual machine before the 4.18 version of the kernel, the real WRITE ZERO operation is not supported, and it will be converted into a write operation in virtio blk, but after 4.18, the real write zero command will be issued, and for ext4, after mount, it will Issue a combined command write zero + unmap, resulting in spdk the vhost blk layer prompts that this type of operation is not supported;

If your block device can't support SPDK_BDEV_IO_TYPE_WRITE_ZEROES command, SPDK vhost-blk target won't set the feature bit, I'm wondering how your change it, is it related with SPDK?

**Comment by zlsh007** [comment]
Even if the bdev code does not support WRITE_ZERO in the feature, it will be modified to support in the spdk_bdev_io_type_supported function as long as the WRITE operation is supported.

bool
spdk_bdev_io_type_supported(struct spdk_bdev *bdev, enum spdk_bdev_io_type io_type)
{                                                                                                                                                                                           
        bool supported;

        supported = bdev_io_type_supported(bdev, io_type);

        if (!supported) {
                switch (io_type) {
                case SPDK_BDEV_IO_TYPE_WRITE_ZEROES:
                        /* The bdev layer will emulate write zeroes as long as write is supported. */
                        supported = bdev_io_type_supported(bdev, SPDK_BDEV_IO_TYPE_WRITE);
                        break;
                case SPDK_BDEV_IO_TYPE_ZCOPY:
                        /* Zero copy can be emulated with regular read and write */
                        supported = bdev_io_type_supported(bdev, SPDK_BDEV_IO_TYPE_READ) &&
                                    bdev_io_type_supported(bdev, SPDK_BDEV_IO_TYPE_WRITE);
                        break;
                default:
                        break;
                }    
        }    

        return supported;
}

**Comment by zlsh007** [comment]
if (!supported)->case SPDK_BDEV_IO_TYPE_WRITE_ZEROES:->supported = bdev_io_type_supported(bdev, SPDK_BDEV_IO_TYPE_WRITE);

**Comment by changpe1** [comment]
> if (!supported)->case SPDK_BDEV_IO_TYPE_WRITE_ZEROES:->supported = bdev_io_type_supported(bdev, SPDK_BDEV_IO_TYPE_WRITE);

Ah~, I see, there is a mismatch between SPDK and kernel driver, the kernel driver should not set the UNMAP bit, since the DISCARD feature bit wasn't negotiated.

**Comment by changpe1** [comment]
OK, this should be fixed in SPDK, I will provide a patch for it.

**Comment by zlsh007** [comment]
Is this vm's kernel driver imperfect? It should confirm that the backend supports UNMAP, and then send a separate DISCARD down?

**Comment by changpe1** [comment]
> Is this vm's kernel driver imperfect? It should confirm that the backend supports UNMAP, and then send a separate DISCARD down?

The fact is that the kernel generic block driver will enable UNMAP bit by default unless it specify the flag BLKDEV_ZERO_NOUNMAP.  

It should be more reasonable to check the DISCARD is support or not before setting this flag, either way, changing in SPDK is much easier than the kernel.

**Comment by zlsh007** [comment]
I understand, thank you, look forward to patch :)

**Comment by changpe1** [comment]
I pushed a patch to fix this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/5565.

**Comment by zlsh007** [comment]
Thanks a lot. The effect of unmap attached to this write zero is to clear the data and then delete the mapping table? Is this operation equivalent to sending a discard after sending a write zero?

**Comment by changpe1** [comment]
> Thanks a lot. The effect of unmap attached to this write zero is to clear the data and then delete the mapping table? Is this operation equivalent to sending a discard after sending a write zero?

This isn't defined in specification, but all the READs will return zeroes for the discarded regions for most of the SSDs in practice.
so at least this operation acts correctly, if it does need DISCARD, it can send DISCARD command directly.

**Comment by zlsh007** [comment]
OK, Thanks!
