### ISSUE TITLE
passing wrong context to remove callback in _nvme_pcie_hotplug_monitor()

### ISSUE THREAD

**Issue by rdxsasha** [spdk/spdk#1715]
In _nvme_pcie_hotplug_monitor() remove_cb should pass context of the controller (saved upon its primary probe), not one from probe_ctx of ongoing probe call

## Expected Behavior
When hotplug monitor gets SPDK_NVME_UEVENT_REMOVE event or detects device to be removed it calls
for remove callback of the controller of this device.

But it should pass cb_ctx (1st param) the context of controller (that its device is detected removed) ctrlr->cb_ctx

## Current Behavior

Currentrly it passes for context probe_ctx->cb_ctx of ongoing spdk_nvme_probe call, that is wrong.
This call that is not intended to attach new device, but only to check the status of previously attached device. 
It get notified about device (pending) removal by cb_remove callback called from the context of _nvme_pcie_hotplug_monitor():

` ctrlr->remove_cb(probe_ctx->cb_ctx, ctrlr);`

## Possible Solution
Correct solution (we assuming it is bug fix):
Pass primary context of the controller (that its device is removed), as expected behavior:

`ctrlr->remove_cb(ctrlr->cb_ctx, ctrlr);
`
Alternative solution, that is "bug backward compatible":
 
`ctrlr->remove_cb(probe_ctx->cb_ctx ? probe_ctx->cb_ctx : ctrlr->cb_ctx, ctrlr);
`
## Steps to Reproduce

1. Call probe and attach device, passing some context as cb_ctx param:

```
spdk_nvme_probe(trid, cb_ctx,
		probe_cb, attach_cb,
		remove_cb);
```
	
 
2. For checking if the device was  hot removed, call anew with the same trid, 
note that the context must be the same one as upon attach, so it should pass NULL for cb_ctx

`spdk_nvme_probe(trid, NULL, NULL, NULL, NULL);
`
## Context (Environment including OS version, SPDK version, etc.)
SPDK version: 20.4
OS: ubuntu:18.04

**Comment by jimharris** [comment]
This is a bug that exists still in master (original report was for v20.04).  I think we should fix it without making it "bug backward compatible".  This means we need to also fix nvme bdev module which is depending on this incorrect usage.  Incidentally, fixing the nvme bdev module will result in some nice simplifications in the remove callback.

**Comment by jimharris** [comment]
This will be a bit more work to fix than originally anticipated.  The spdk_nvme_connect (and connect_async) APIs do not take a remove_cb nor a cb_arg parameter.  I think the proper way to fix this would be:

1) add remove_cb and remove_cb_arg members to spdk_nvme_ctrlr_opts
2) users of the spdk_nvme_probe APIs will see these members initialized to the associated spdk_nvme_probe parameters in the spdk_nvme_ctrlr_opts parameter of the spdk_nvme_probe_cb (where they can override them if desired)
3) users of the spdk_nvme_connect APIs will set these members before calling spdk_nvme_connect

@tomzawadzki let's discuss this one in bug scrub tomorrow.

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris 

I would like to confirm my understanding about the first simplification for the remove_cb used in the nvme bdev module.
The nvme bdev module have not used cb_ctx parameter yet.
If we fix the bug, we can hold the created nvme_bdev_ctrlr pointer in spdk_nvme_ctrlr_opts or nvme_async_probe_ctx by attach_cb(), and refer it by remove_cb() later. Then we don't parse the global nvme_bdev_ctrlr list.
Does this match your thought?

**Comment by jimharris** [comment]
Yes Shuhei, that is exactly my thought!

**Comment by shuhei-matsumoto** [comment]
Thanks Jim. That will be nice improvement. Thanks @rdxsasha for your nice finding and fix.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/5510

I took a slightly different approach than passing value through spdk_nvme_ctrlr_opts.  I created a new spdk_nvme_ctrlr_set_remove_cb() API instead.  Passing through opts structure is not convenient, for example bdev module does not create the bdev_nvme_ctrlr before calling spdk_nvme_connect_async().

**Comment by rdxsasha** [comment]
Jim, 
in nvme_pcie.c (_nvme_pcie_hotplug_monitor()) you fixed the 1st param in remove_cb() call in the line 309, 
but I assume it should be also fixed in the line 338. 
(in the case of our code just this call was critical to be fixed - we don't receive SPDK_NVME_UEVENT_REMOVE, but probing actively to get remove_cb() called as soon as PCI devhandle gets pending_removal flag enabled). 

Sorry, commenting here - have no gerrit installed at my Mac yet.

**Comment by jimharris** [comment]
Yes, it should be fixed in line 338 too.  I'll clean that up and push again.  Thanks for the review.

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5510 fixing this issue was merged.
