### ISSUE TITLE
Running the identify example from SPDK library in host with Kernel target configuration is failing

### ISSUE THREAD

**Issue by ksubbiahx** [spdk/spdk#172]
Hi,
Both NVMeOF target server and host is configured with RHEL OS v7.3 and upstream kernel v4.10.4.
Downloaded the SPDK source code from spdk master branch and NIC card (both target and host) - Mellanox Technologies MT27710 Family [ConnectX-4    Lx], driver: mlx5_core, version: 3.0-1, firmware v14.14.1100
Built the SPDK with CONFIG_RDMA=y argument.
Running spdk's identify example from host and  configured kernel nvme target and it is listening on address 1.1.1.1 and port 4440.

[root@localhost identify]# ./identify  -r 'trtype:RDMA adrfam:IPv4 traddr:1.1.1.1 trsvcid:4440'
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: identify -c 0x1 -n 1 -m 64 --file-prefix=spdk_pid34080 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
nvme_rdma.c: 548:nvme_rdma_parse_addr: ***ERROR*** getaddrinfo failed - invalid hostname or IP address
nvme_rdma.c: 725:nvme_rdma_qpair_connect: ***ERROR*** nvme_rdma_parse_addr() failed
Segmentation fault (core dumped)

**Comment by dverkamp-intel** [comment]
Could you please try applying this patch to see what the specific getaddrinfo() error is?

~~~
diff --git a/lib/nvme/nvme_rdma.c b/lib/nvme/nvme_rdma.c
index 4281b7b..6d91184 100644
--- a/lib/nvme/nvme_rdma.c
+++ b/lib/nvme/nvme_rdma.c
@@ -542,7 +542,7 @@ nvme_rdma_parse_addr(struct sockaddr_storage *sa, int family, const char *addr,
 
        ret = getaddrinfo(addr, service, &hints, &res);
        if (ret) {
-               SPDK_ERRLOG("getaddrinfo failed - invalid hostname or IP address\n");
+               SPDK_ERRLOG("getaddrinfo failed: %s (%d)\n", gai_strerror(ret), ret);
                return ret;
        }
~~~

(Also posted as https://review.gerrithub.io/369642)

**Comment by ksubbiahx** [comment]
The  following is the error from getaddrinfo() after applying the given patch:

[root@localhost identify]# ./identify  -r 'trtype:RDMA adrfam:IPv4 traddr:1.1.1.1 trsvcid:4440'
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: identify -c 0x1 -n 1 -m 64 --file-prefix=spdk_pid30780 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
nvme_rdma.c: 548:nvme_rdma_parse_addr: ***ERROR*** getaddrinfo failed - invalid hostname or IP address
nvme_rdma.c: 549:nvme_rdma_parse_addr: ***ERROR*** getaddrinfo failed: Servname not supported for ai_socktype (-8)
nvme_rdma.c: 726:nvme_rdma_qpair_connect: ***ERROR*** nvme_rdma_parse_addr() failed
Segmentation fault (core dumped)

But, identify example is running without error when tried hard coding the value of transport service identifier as : 
 ret = getaddrinfo(addr,"4440", &hints, &res);

**Comment by dverkamp-intel** [comment]
Hmm, if changing the getaddrinfo() line to hard-code the service changes the behavior, then it seems like we have an invalid ctrlr->trid.trsvcid somehow.  Can you try this patch and then run `./identify -r 'trtype:RDMA adrfam:IPv4 traddr:1.1.1.1 trsvcid:4440' -t nvme` (same command as before, but add `-t nvme` to enable NVMe tracelogs)?

For the trace code to work, you will need to compile with debug enabled, e.g. `make CONFIG_DEBUG=y` or `./configure --enable-debug`.

~~~
diff --git a/lib/nvme/nvme_rdma.c b/lib/nvme/nvme_rdma.c
index 4281b7b..77e4fd9 100644
--- a/lib/nvme/nvme_rdma.c
+++ b/lib/nvme/nvme_rdma.c
@@ -716,6 +716,7 @@ nvme_rdma_qpair_connect(struct nvme_rdma_qpair *rqpair)
 
        memset(&sin, 0, sizeof(struct sockaddr_storage));
 
+       SPDK_TRACEDUMP(SPDK_TRACE_NVME, "trsvcid", ctrlr->trid.trsvcid, sizeof(ctrlr->trid.trsvcid));
        SPDK_TRACELOG(SPDK_TRACE_DEBUG, "trsvcid is %s\n", ctrlr->trid.trsvcid);
        rc = nvme_rdma_parse_addr(&sin, family, ctrlr->trid.traddr, ctrlr->trid.trsvcid);
        if (rc != 0) {
~~~

If the transport address parsing is working correctly, we should see this output (which should be equivalent to specifying "4440" directly in the getaddrinfo() call):

~~~
trsvcid
00000000  34 34 34 30 00 00 00 00  00 00 00 00 00 00 00 00  4440............
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000020  00                                                .
~~~

**Comment by ksubbiahx** [comment]
Getting the below output after applying the given patch:

[root@localhost identify]# ./identify -r 'trtype:RDMA adrfam:IPv4 traddr:1.1.1.1 trsvcid:4440' -t nvme
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: identify -c 0x1 -n 1 -m 64 --file-prefix=spdk_pid24204 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
[nvme] nvme_ctrlr.c: 513:nvme_ctrlr_set_state: setting state to init (no timeout)
[nvme] nvme_rdma.c: 719:nvme_rdma_qpair_connect: adrfam 1 ai_family 2
trsvcid
00000000  34 34 34 30 00 00 00 00  00 00 00 00 00 00 00 00  4440............
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000020  00                                                .
[nvme] nvme_rdma.c: 521:nvme_rdma_connect: Requested queue depth 32. Actually got queue depth 32.
[nvme] nvme_ctrlr.c: 513:nvme_ctrlr_set_state: setting state to init (no timeout)
[nvme] nvme_rdma.c: 719:nvme_rdma_qpair_connect: adrfam 1 ai_family 2
trsvcid
00000000  34 34 34 30 0a 00 00 00  00 00 00 00 00 00 00 00  4440............
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000020  00                                                .
nvme_rdma.c: 548:nvme_rdma_parse_addr: ***ERROR*** getaddrinfo failed - invalid hostname or IP address
nvme_rdma.c: 549:nvme_rdma_parse_addr: ***ERROR*** getaddrinfo failed: Servname not supported for ai_socktype (-8)
nvme_rdma.c: 727:nvme_rdma_qpair_connect: ***ERROR*** nvme_rdma_parse_addr() failed
Segmentation fault (core dumped)

**Comment by dverkamp-intel** [comment]
It looks like the kernel discovery service is returning a newline in the trsvcid field.  If you are configuring the kernel target using 'echo' commands, make sure you are using 'echo -n' so it doesn't have an embedded newline.

**Comment by ksubbiahx** [comment]
Yes. Tried the echo command with -n option during kernel target configuration and now identify example is running without any error. Thanks.

**Comment by dverkamp-intel** [comment]
OK, closing this issue, since it is a configuration error on the target, not a SPDK bug.

I've also pushed a patch that works around this specific misconfiguration: https://review.gerrithub.io/#/c/370593/
