### ISSUE TITLE
nvmf kernel host connect fail while MaxQueueDepth is lower than 128

### ISSUE THREAD

**Issue by ehudmarvell** [spdk/spdk#173]
Hi,

I am trying to work with kernel host and spdk as target.

kernel host(ubuntu 17.04):
1.	sudo nvme discover –t rdma –a 3.3.3.2 –s 4420 		-> pass
2.	sudo nvme connect –t rdma –a 3.3.3.2 –s 4420 –n <my nqn> 
                                        -> fail on  “Invalid SQSIZE 32 (min 1, max 32)”

spdk server: 
1.	MaxQueueDepth = 32 (similar problem also with other sizes)(my conf file is attached)
[nvmf_new.txt](https://github.com/spdk/spdk/files/1154916/nvmf_new.txt)

2.	sudo app/nvmf_tgt/nvmf_tgt –t all –c <my conf file>

The attached log includes discover and connect. 
[log.txt](https://github.com/spdk/spdk/files/1154915/log.txt)

short log:

rdma.c: 826:spdk_nvmf_request_prep_data: *INFO*: In-capsule data: offset 0x0, length 0x400
rdma.c:1375:process_incoming_queue: *INFO*: Request 0x55e1447bb010 is ready for execution
request.c: 237:nvmf_trace_command: *INFO*: Admin Fabrics cmd: fctype 0x01 cid 0
request.c: 261:nvmf_trace_command: *INFO*: SGL: Data block: offs 0x0 len 0x400
session.c: 243:spdk_nvmf_session_connect: *INFO*: recfmt 0x0 qid 1 sqsize 32
session.c: 245:spdk_nvmf_session_connect: *INFO*: Connect data:
session.c: 246:spdk_nvmf_session_connect: *INFO*:   cntlid:  0x0002
session.c: 254:spdk_nvmf_session_connect: *INFO*:   hostid: 30041346-b90d-41e4-bfc4-3808a70e2b05 ***
session.c: 255:spdk_nvmf_session_connect: *INFO*:   subnqn: "nqn.2016-06.io.spdk:cnode1"

session.c: 256:spdk_nvmf_session_connect: *INFO*:   hostnqn: "nqn.2014-08.org.nvmexpress:NVMf:uuid:30041346-b90d-41e4-bfc4-3808a70e2b05"
**# session.c: 271:spdk_nvmf_session_connect: *ERROR*: Invalid SQSIZE 32 (min 1, max 31)**
request.c: 108:spdk_nvmf_handle_connect: *INFO*: connect capsule response: cntlid = 0x002c
request.c:  60:spdk_nvmf_request_complete: *INFO*: cpl: cid=0 cdw0=0x0000002c rsvd1=0 status=0x0304
rdma.c: 473:request_transfer_out: *INFO*: RDMA RECV POSTED. Recv: 0x55e1447bde20 Connection: 0x55e14479eec0
rdma.c: 499:request_transfer_out: *INFO*: RDMA SEND POSTED. Request: 0x55e1447bb010 Connection: 0x55e14479eec0
rdma.c:1059:spdk_nvmf_rdma_acceptor_poll: *INFO*: Acceptor Event: RDMA_CM_EVENT_DISCONNECTED
rdma.c:1059:spdk_nvmf_rdma_acceptor_poll: *INFO*: Acceptor Event: RDMA_CM_EVENT_DISCONNECTED
rdma.c:1059:spdk_nvmf_rdma_acceptor_poll: *INFO*: Acceptor Event: RDMA_CM_EVENT_DISCONNECTED
rdma.c:1059:spdk_nvmf_rdma_acceptor_poll: *INFO*: Acceptor Event: RDMA_CM_EVENT_DISCONNECTED

Thanks!
Ehud

**Comment by dverkamp-intel** [comment]
This is a bug in the Linux kernel NVMe-oF host code, fixed across a few commits:
https://github.com/torvalds/linux/commit/f994d9dc28bc27353acde2caaf718222d92a3e24
https://github.com/torvalds/linux/commit/c5af8654c422cfdd8480be3a244748e18cace6c5
https://github.com/torvalds/linux/commit/1af76ddaa80e3bca8001b535e44aaaebd3e1907e

It's likely that Ubuntu 17.04 doesn't have a new enough kernel to have all of the fixes.

Specifically, we report the maximum allowed queue size via the Identify Controller MQES field, and the kernel host code requests a SQSIZE that is one greater than the maximum that we reported via MQES.

**Comment by ehudmarvell** [comment]
Thanks a lot
