### ISSUE TITLE
show "no NVMe controllers found"

### ISSUE THREAD

**Issue by profove** [spdk/spdk#1730]
I have followed the guidance of spdk and show "no NVMe controllers found" when run the examples, like "hello_world"

I'm using a lenovo server SR650 with two CPUs:

I'm already run the setup.sh script to config, and the status info below:
./setup.sh status
[root@localhost scripts]# ./setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB     1023 /   1024
node1   1048576kB        0 /      0
node1      2048kB        0 /      0

Type     BDF             Vendor Device NUMA    Driver           Device     Block devices
I/OAT    0000:00:04.0    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.1    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.2    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.3    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.4    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.5    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.6    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.7    8086   2021   0       ioatdma          -          -
I/OAT    0000:80:04.0    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.1    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.2    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.3    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.4    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.5    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.6    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.7    8086   2021   1       ioatdma          -          -
NVMe     0000:86:00.0    8086   2701   1       -                -          -
NVMe     0000:d8:00.0    8086   0a54   1       nvme             nvme1      nvme1n1

because i have two SSDs, "0000:d8:00.0" is mounted and for load OS, "0000:86:00.0" is not mounted,
then I set the env "export PCI_ALLOWED="0000:86:00.0"" and want to use only the later one.

but when I run the example app shows below:
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
no NVMe controllers found

Can we use a nvme file system for the OS when using spdk?

**Comment by changpe1** [comment]
You may run scripts/setup again before running the example.

For you second question, SPDK will skip SSDs which have filesystems formatted.

**Comment by profove** [comment]
> You may run scripts/setup again before running the example.
> 
> For you second question, SPDK will skip SSDs which have filesystems formatted.

run setup.sh again still get the error info "no NVMe controllers found", my mount info below:
[root@localhost scripts]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        189G     0  189G   0% /dev
tmpfs           189G     0  189G   0% /dev/shm
tmpfs           189G   14M  189G   1% /run
tmpfs           189G     0  189G   0% /sys/fs/cgroup
/dev/nvme1n1p5  316G  3.4G  296G   2% /
/dev/nvme1n1p2  976M  148M  761M  17% /boot
/dev/nvme1n1p1  599M  6.9M  592M   2% /boot/efi
/dev/nvme1n1p3  1.5T  9.6G  1.4T   1% /home
tmpfs            38G     0   38G   0% /run/user/1000

"0000:86:00.0" is not mounted and not in the list ,

**Comment by changpe1** [comment]
What's input if you run scripts/setup reset & lsblk for the drive 0000:86:00.0?

**Comment by profove** [comment]
[root@localhost scripts]# ./setup.sh reset
0000:d8:00.0 (8086 0a54): Skipping denied controller at 0000:d8:00.0
0000:d8:00.0 (8086 0a54): Active mountpoints on nvme1n1:nvme1n1p1,nvme1n1:nvme1n1p2,nvme1n1:nvme1n1p3,nvme1n1:nvme1n1p5, so not binding PCI dev
0000:00:04.0 (8086 2021): Skipping denied controller at 0000:00:04.0
0000:00:04.1 (8086 2021): Skipping denied controller at 0000:00:04.1
0000:00:04.2 (8086 2021): Skipping denied controller at 0000:00:04.2
0000:00:04.3 (8086 2021): Skipping denied controller at 0000:00:04.3
0000:00:04.4 (8086 2021): Skipping denied controller at 0000:00:04.4
0000:00:04.5 (8086 2021): Skipping denied controller at 0000:00:04.5
0000:00:04.6 (8086 2021): Skipping denied controller at 0000:00:04.6
0000:00:04.7 (8086 2021): Skipping denied controller at 0000:00:04.7
0000:80:04.0 (8086 2021): Skipping denied controller at 0000:80:04.0
0000:80:04.1 (8086 2021): Skipping denied controller at 0000:80:04.1
0000:80:04.2 (8086 2021): Skipping denied controller at 0000:80:04.2
0000:80:04.3 (8086 2021): Skipping denied controller at 0000:80:04.3
0000:80:04.4 (8086 2021): Skipping denied controller at 0000:80:04.4
0000:80:04.5 (8086 2021): Skipping denied controller at 0000:80:04.5
0000:80:04.6 (8086 2021): Skipping denied controller at 0000:80:04.6
0000:80:04.7 (8086 2021): Skipping denied controller at 0000:80:04.7
0000:86:00.0 (8086 2701): no driver -> nvme

[root@localhost scripts]# lsblk 
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 698.7G  0 disk 
└─nvme0n1p1 259:1    0 698.7G  0 part 
nvme1n1     259:2    0   1.8T  0 disk 
├─nvme1n1p1 259:3    0   600M  0 part /boot/efi
├─nvme1n1p2 259:4    0     1G  0 part /boot
├─nvme1n1p3 259:5    0   1.5T  0 part /home
├─nvme1n1p4 259:6    0     4G  0 part [SWAP]
└─nvme1n1p5 259:7    0 321.4G  0 part /

**Comment by changpe1** [comment]
I see, do you have UIO or VFIO driver in your OS?
Users must bind NVMe SSD to UIO or VFIO before running SPDK, for most cases setup.sh will bind automatically.

**Comment by profove** [comment]
> I see, do you have UIO or VFIO driver in your OS?
> Users must bind NVMe SSD to UIO or VFIO before running SPDK, for most cases setup.sh will bind automatically.

how to check uio or vfio driver?

**Comment by Comphix** [comment]
It looks like that there are partitions on both NVMe SSDs as listed above. Are you saying that you would like like to run SPDK on the second nvme1 (0000:86:00.0) SSD?

[root@localhost scripts]# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1 259:0 0 698.7G 0 disk
└─nvme0n1p1 259:1 0 698.7G 0 part
nvme1n1 259:2 0 1.8T 0 disk
├─nvme1n1p1 259:3 0 600M 0 part /boot/efi
├─nvme1n1p2 259:4 0 1G 0 part /boot
├─nvme1n1p3 259:5 0 1.5T 0 part /home
├─nvme1n1p4 259:6 0 4G 0 part [SWAP]
└─nvme1n1p5 259:7 0 321.4G 0 part /

**Comment by profove** [comment]
> It looks like that there are partitions on both NVMe SSDs as listed above. Are you saying that you would like like to run SPDK on the second nvme1 (0000:86:00.0) SSD?
> 
> [root@localhost scripts]# lsblk
> NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
> nvme0n1 259:0 0 698.7G 0 disk
> └─nvme0n1p1 259:1 0 698.7G 0 part
> nvme1n1 259:2 0 1.8T 0 disk
> ├─nvme1n1p1 259:3 0 600M 0 part /boot/efi
> ├─nvme1n1p2 259:4 0 1G 0 part /boot
> ├─nvme1n1p3 259:5 0 1.5T 0 part /home
> ├─nvme1n1p4 259:6 0 4G 0 part [SWAP]
> └─nvme1n1p5 259:7 0 321.4G 0 part /

yep

**Comment by Comphix** [comment]
Is 0000:86:00.0 for below SSD (nvme0) ?

nvme0n1 259:0 0 698.7G 0 disk
└─nvme0n1p1 259:1 0 698.7G 0 part

Looks like 0000:d8:00.0 is for nvme1 where OS is loaded
NVMe 0000:d8:00.0 8086 0a54 1 nvme nvme1 nvme1n1

**Comment by profove** [comment]
yes, 
"0000:86:00.0" is nvme0
"0000:d8:00.0" is nvme1 and for OS

**Comment by Comphix** [comment]
If there is no data on nvme0 (0000:86:00.0), you could have a try to format it with kernel driver (or to destroy the partition nvme0n1p1) as it is listed there is a partition on it.

nvme0n1 259:0 0 698.7G 0 disk
└─nvme0n1p1 259:1 0 698.7G 0 part  <<<<<<<<<

Once there is no mountpoint, then run the scripts/setup.sh to check whether UIO or VFIO could be loaded on this SSD. You could run scripts/setup.sh status to check.

**Comment by profove** [comment]
> If there is no data on nvme0 (0000:86:00.0), you could have a try to format it with kernel driver (or to destroy the partition nvme0n1p1) as it is listed there is a partition on it.
> 
> nvme0n1 259:0 0 698.7G 0 disk
> └─nvme0n1p1 259:1 0 698.7G 0 part <<<<<<<<<
> 
> Once there is no mountpoint, then run the scripts/setup.sh to check whether UIO or VFIO could be loaded on this SSD. You could run scripts/setup.sh status to check.

I format the disk and still not work, and now the partition info below:
[root@localhost scripts]# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 698.7G  0 disk 
nvme1n1     259:2    0   1.8T  0 disk 
├─nvme1n1p1 259:3    0   600M  0 part /boot/efi
├─nvme1n1p2 259:4    0     1G  0 part /boot
├─nvme1n1p3 259:5    0   1.5T  0 part /home
├─nvme1n1p4 259:6    0     4G  0 part [SWAP]
└─nvme1n1p5 259:7    0 321.4G  0 part /

then run setup.sh and the status below:
[root@localhost scripts]# ./setup.sh  status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB     1024 /   1024
node1   1048576kB        0 /      0
node1      2048kB        0 /      0

Type     BDF             Vendor Device NUMA    Driver           Device     Block devices
I/OAT    0000:00:04.0    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.1    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.2    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.3    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.4    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.5    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.6    8086   2021   0       ioatdma          -          -
I/OAT    0000:00:04.7    8086   2021   0       ioatdma          -          -
I/OAT    0000:80:04.0    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.1    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.2    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.3    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.4    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.5    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.6    8086   2021   1       ioatdma          -          -
I/OAT    0000:80:04.7    8086   2021   1       ioatdma          -          -
NVMe     0000:86:00.0    8086   2701   1       -                -          -
NVMe     0000:d8:00.0    8086   0a54   1       nvme             nvme1      nvme1n1

**Comment by Comphix** [comment]
What's your OS and kernel information?

You could also check whether uio or vfio driver is loaded in the system like below:

~# lsmod | grep -i uio
uio_pci_generic        16384  0
uio                    16384  1 uio_pci_generic

**Comment by profove** [comment]
> What's your OS and kernel information?
> 
> You could also check whether uio or vfio driver is loaded in the system like below:
> 
> ~# lsmod | grep -i uio
> uio_pci_generic 16384 0
> uio 16384 1 uio_pci_generic

centos 8.3 and 4.18.0-240.1.1.el8_3.x86_64

[root@localhost scripts]#  lsmod | grep -i uio
uio_pci_generic        16384  0
uio                    20480  1 uio_pci_generic

**Comment by mikeBashStuff** [comment]
This issue is probably caused by a faulty io_pci_generic driver (similar to https://github.com/spdk/spdk/issues/1658 or https://github.com/spdk/spdk/issues/1563) considering this:
`0000:86:00.0 (8086 2701): no driver -> nvme`

`setup.sh` won't fail if write to bind|unbind is not successful and from this example it seems that the driver did reject the controller when `setup.sh` was run in config mode for the first time (so the device was unbind from the `nvme` driver but didn't end up under `uio_pci_generic`).

**Comment by profove** [comment]
> This issue is probably caused by a faulty io_pci_generic driver (similar to #1658 or #1563) considering this:
> `0000:86:00.0 (8086 2701): no driver -> nvme`
> 
> `setup.sh` won't fail if write to bind|unbind is not successful and from this example it seems that the driver did reject the controller when `setup.sh` was run in config mode for the first time (so the device was unbind from the `nvme` driver but didn't end up under `uio_pci_generic`).

oops， same problem like before.  I update kernel to latest 5.10.4-1 and now it's working
Thank you all for your help.
