### ISSUE TITLE
nvme_rdma_calloc() can`t return NULL pointer while allocate zero entry

### ISSUE THREAD

**Issue by JiangMaox** [spdk/spdk#1735]
nvme_rdma_calloc() can`t return NULL pointer while allocate zero entry
```
nvme_rdma_calloc (nmemb=0, size=192) at /mnt/c/Users/maojia1x/Desktop/code/spdk/spdk/lib/nvme/nvme_rdma.c:307
307             if (!g_nvme_hooks.get_rkey) {
(gdb) n
308                     return calloc(nmemb, size);
(gdb) p calloc(nmemb, size)
$4 = (void *) 0x8414f90
```

## Expected Behavior

Return NULL pointer.

## Current Behavior
Return a unique pointer

## Possible Solution
Add a check before call common allocation APIs.
```
	if (!nmemb || !size) {
		return NULL;
	}
```

## Steps to Reproduce

1. call nvme_rdma_calloc(0, 192); and check the return pointer.
2. return a unique pointer.

## Context (Environment including OS version, SPDK version, etc.)
4.4.0-18362-Microsoft
SPDK commit 45c42ac2f

**Comment by JiangMaox** [comment]
Done.

**Comment by Comphix** [comment]
Add the patch fix here: https://review.spdk.io/gerrit/c/spdk/spdk/+/5809
