### ISSUE TITLE
[autotest-per-patch] failed incomplete but all tests pass

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1739]
https://review.spdk.io/gerrit/c/spdk/spdk/+/5845

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_33724.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_33768.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_33789.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_33748.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_33798.html

**Comment by karlatec** [comment]
I allowed myself to edit the title ;)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_33825.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szwed. log: https://ci.spdk.io/public_build/autotest-per-patch_33821.html

**Comment by karlatec** [comment]
@xjjx Made appropriate changes to CI configuration today. Let's close the issue if no more instances are reported by end of the week.
