### ISSUE TITLE
[autotest-per-patch] vhost-initiator-vg-autotest stopped before finishing test

### ISSUE THREAD

**Issue by dong-liuliu** [spdk/spdk#1742]
The patch is at https://review.spdk.io/gerrit/c/spdk/spdk/+/5782 

## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_33638.html

## Execution failed at
https://ci.spdk.io/results/autotest-per-patch/builds/33638/archive/vhost-initiator-vg-autotest/index.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_33638.html

**Comment by tomzawadzki** [comment]
[Bug scrub] The log stops right in the middle of outputting the string, @karlatec could you take a look at the job log above to see what might have caused it ?

**Comment by tomzawadzki** [comment]
The build log no longer contains the output and this issue has not occurred for two months. Closing.
