### ISSUE TITLE
fio job doesn't terminate after runtime

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#1746]
I am using fio with the bdev fio_plugin to benchmark the SPDK NVMe-oF TCP initiator and target. When I run 24 fio jobs at QD >= 128, fio continues to run after the configured runtime. I have a runaway job that will not terminate. I see the issue only when I have zcopy=true on the target.
## Expected Behavior

After the 5 minute runtime fio should terminate all threads
## Current Behavior

Some fio threads continue to run after the configured runtime. I see the CPU utilization go from 2400% to 200% (sometimes 300%). So there are 2 or 3 fio threads that continue running beyond the runtime.
## Possible Solution

I reproduced the issue on the current master and verified that the issue did not exist in the 20.10 release. I did a git bisect of the commits between the current master and 20.10 and it pointed me to commit 0bcaf050d74138f1191a3c18814f0991dd182db2 as the first bad commit. I cannot reproduce the issue on the previous commit 23a1916935fd98fa031aa314a154ece648163a84. 
## Steps to Reproduce

1. Start the SPDK NVMe-oF TCP target to run on 8 CPU cores and configure the target with zcopy=true.
2. Add 8 NVMe subsystem and export them over TCP.
3. Create an fio configuration file with the following content

[global]
ioengine=/tmp/spdk/build/fio/spdk_bdev
spdk_json_conf=/tmp/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

norandommap=1
rw=randrw
rwmixread=0
bs=4k
time_based=1
ramp_time=60
runtime=300
numjobs=3

[filename0]
filename=Nvme0n1
iodepth=128
[filename1]
filename=Nvme1n1
iodepth=128
[filename2]
filename=Nvme2n1
iodepth=128
[filename3]
filename=Nvme3n1
iodepth=128
[filename4]
filename=Nvme4n1
iodepth=128
[filename5]
filename=Nvme5n1
iodepth=128
[filename6]
filename=Nvme6n1
iodepth=128
[filename7]
filename=Nvme7n1
iodepth=128

4. Run fio with above config file. Note the issue doesn't happen all the time. The most I have had to run fio to reproduce the issue is 3 times.

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora 30 with Linux 5.7.12
SPDK: commit a9a0761bccc15218f28631a1b9d3360e03c36a4b
You can also use the SPDK NVMe-oF performance test script (scripts/perf/nvmf/run_nvmf.py) with the following json file to reproduce the issue.
{
  "general": {
    "username": "root",
    "password": "xxxxxx",
    "transport": "tcp"
  },
  "target": {
    "nic_ips": ["target ip address"],
    "mode": "spdk",
    "use_null_block": false,
    "nvmet_dir": "/path/to/nvmetcli",
    "num_cores": "F0000F0",
    "num_shared_buffers": 4096,
    "zcopy_settings": true
  },
  "initiator1": {
    "ip": "ini management ip address",
    "nic_ips": ["target ip address"],
    "mode": "spdk",
    "num_cores": "8",
    "nvmecli_dir": "/path/to/nvmecli",
    "fio_dir": "/home/john/fio/fio",
    "extra_params": ""
  },
  "fio": {
    "bs": ["4k"],
    "qd": [384,576,768],
    "rw": ["randrw"],
    "rwmixread": 100,
    "run_time": 300,
    "ramp_time": 60,
    "num_jobs": 3,
    "run_num": 3
  }
}

**Comment by jimharris** [comment]
Thanks for the bisect @KariukiJ.  Could you revert that patch on tip of master and see if the problem goes away?

Tagging @optimistyzy.

**Comment by optimistyzy** [comment]
Hi @jimharris @KariukiJ I figured out the reason, we should revert this patch. 

Reason：After this patch, the sock which is in waiting req state and  with no in coming data (readin event ) will never have a chance to execute again for the last command again.

// Please firstly test it and I will submit the revert patch

**Comment by KariukiJ** [comment]
Looks good. I ran the patch at least 20 times and could not reproduce the issue

**Comment by jimharris** [comment]
Thanks @KariukiJ!

It's better to wait to close the issue until the patch has been merged.  But I just merged the patch so it's all good.  :-)
