### ISSUE TITLE
[nvmf-phy-autotest] much longer test execution time on E810 NICs

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1748]
## Current Behavior

When running autotest.sh RDMA test suite with Intel E810-XXV NIC total execution time is roughly 40-50% longer than when testing with Mellanox NIC such as ConnectX-4 Lx. Not sure if this is a NIC driver or SPDK problem.

Also - tests pass, so it's a minor problem, but should be improved if possible, as execution time is close to CI timeout limit for this test.

## Expected Behavior

Similar execution time as when run on Mellanox?

## Possible Solution

N/A

## Steps to Reproduce

1. Need a E800 series Intel RDMA-Capable NIC and iRDMA driver installed
2. Use patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5943, build SPDK with
```
./configure --with-fio=/usr/src/fio --with-rdma
make -j100
```

3. In file `spdk/test/nvmf.sh` comment out line with `nvmf_vhost.sh` test if you don't have Qemu or any other vhost test dependencies.
4. Do `rmmod mlx5_ib && modprobe irdma` to make sure proper driver is used in test
5. Run autotest.sh with following config, to run whole RDMA test suite:
```
[klateck@eagle1 spdk]$ cat ~/autorun-spdk.conf
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_NVMF=1
SPDK_TEST_NVME_CLI=1
SPDK_RUN_UBSAN=1
RUN_NIGHTLY=0

[klateck@eagle1 spdk]$ time sudo -E ./autotest.sh ~/autorun-spdk.conf
```

5. If possible re-run again, but this time do `rmmod irdma && modprobe mlx5_ib` to run with Mellanox NIC. In my case Mellanox time is always lower.

Results comparison:

* ZIP files with all test artifacts (log file & dmesg & svg timings):
[mlx-rdma-test-run.zip](https://github.com/spdk/spdk/files/5831468/mlx-rdma-test-run.zip)
[cvl-rdma-test-run.zip](https://github.com/spdk/spdk/files/5831469/cvl-rdma-test-run.zip)

* Time run in seconds (including CI specific operations)
MLX / CVL
523 / 744
523 / 740
530 / 740

* Biggest time differences are in test where we try to do a reconnect in case rdma target is killed:
test/nvmf/host/bdevperf.sh (22 vs 87 sec)
test/nvmf/host/target_disconnect.sh (24 vs 239 sec)

## Context (Environment including OS version, SPDK version, etc.)
SPDK df2c932e09
Fedora 32 5.8.15

Installed userspace rdma-core v27.0 (hard dependency for irdma driver)

Intel NIC info:
E810-XXV, FW 1.52

Mellanox NIC:
ConnectX-4 Lx, FW 14.23.1020

**Comment by karlatec** [comment]
Additional log & dmesg output for test/nvmf/target/bdevperf.sh test (dmesg timestamps easier to match what's in log file)

[cvl-bdevperf-log.txt](https://github.com/spdk/spdk/files/5831544/cvl-bdevperf-log.txt)
[cvl-bdevperf-dmesg.txt](https://github.com/spdk/spdk/files/5831545/cvl-bdevperf-dmesg.txt)
[mlx-bdevperf-log.txt](https://github.com/spdk/spdk/files/5831546/mlx-bdevperf-log.txt)
[mlx-bdevperf-dmesg.txt](https://github.com/spdk/spdk/files/5831547/mlx-bdevperf-dmesg.txt)

**Comment by karlatec** [comment]
Possible workaround is to modify irdma-1.7.72/src/irdma/verbs.h before building iRDMA driver.
Change the value in
```
#define IRDMA_FLUSH_DELAY_MS          1500
```
to 500 or less.
With original 1500ms `nvme disconnect` takes about 40-50 seconds when using Kernel Target + Kernel Initiator. About 120-150 seconds for SPDK Target + Kernel Initiator.

With 500ms Kernel Target + Initiator takes ~6 seconds to disconnect. ~1-2 seconds for 100ms. Similarly when running SPDK tests. 
Works for both iWARP and RoCEv2.

**Comment by karlatec** [comment]
I've lowered the flush delay even further. https://review.spdk.io/gerrit/c/spdk/spdk/+/11309 fixes the issue.
The OS image with irdma-on board is already deployed in CI and tests are passing in nightly tests: https://ci.spdk.io/public_build/autotest-nightly_288.html

**Comment by jimharris** [comment]
Patches merged.
