### ISSUE TITLE
Fix of issue #1621 introduced bug - segmentation fault after failed reset

### ISSUE THREAD

**Issue by rdxsasha** [spdk/spdk#1749]
With the fix of #1621 
(made by 9ae19a41 nvme: restore qid in free_io_qids bit array) - another bug was introduced. 
After calling reset spdk_nvme_ctrlr_reset() that fails, segmentation fault occurs upon calling to spdk_nvme_ctrlr_free_io_qpair() with qpair of this controller
 
## Expected Behavior
upon failed reset of controller, it should be possible to free I/O qpair (spdk_nvme_ctrlr_free_io_qpair()) associated with this controller

## Current Behavior
after this fix introduced in SPDK 20.10 and calling reset of controller that fails: subsequent call to spdk_nvme_ctrlr_free_io_qpair() causes segmentation fault to occur in call stack of spdk_nvme_ctrlr_free_qid() at line  lib/nvme/nvme_ctrlr.c:591

Reason: the mentioned fix releases ctrlr->free_io_qids at reset (lib/nvme/nvme_ctrlr.c:1419), and it is not re-allocated if reset fails 

## Possible Solution
The fix of this issue we propose is simple: check ctrlr->free_io_qids for non-NULL before calling spdk_nvme_ctrlr_free_qid() in spdk_nvme_ctrlr_free_io_qpair() at lib/nvme/nvme_ctrlr.c:591
```
if (!ctrlr->free_io_qids) {
	SPDK_WARNLOG("Free I/O queue ids array was disposed on failed reset\n");
} else {
	spdk_nvme_ctrlr_free_qid(ctrlr, qpair->id);
}
```

## Steps to Reproduce

1. Upon working controller "ctrlr" with qpair.
2. remove device physically 
3. Call spdk_nvme_ctrlr_reset(ctrlr) - it will fail 
4. Call  #spdk_nvme_ctrlr_free_io_qpair()
5. It fails with segmentation fault at lib/util/bit_array.c:168, since ba is NULL, that is called from lib/nvme/nvme_ctrlr.c:591

## Context (Environment including OS version, SPDK version, etc.)
SPDK 20.10
OS: ubuntu 18.04

**Comment by optimistyzy** [comment]
@rdxsasha Could you submit a patch to address this issue?  You can follow the guide in https://spdk.io/development/

**Comment by rdxsasha** [comment]
Hi, Ziye!

I can do it. 

But cannot do immediately (I have to get arranged with environment and learn guide). 
Presumably will do it in a week or so.

Thanks,
Sasha.

**Comment by changpe1** [comment]
@rdxsasha what's the application you are using? 

For your case, SPDK can do controller destruction automatically if you enable the hotplug, so IO queue pairs will be released too.
I don't think it's worth to fix the scenario that you mentioned.

**Comment by changpe1** [comment]
[Bug Scrub] @rdxsasha Go ahead to submit your fix patch, we discussed this, it's OK for us. thanks.

**Comment by tomzawadzki** [comment]
Hi @rdxsasha, have you had a chance to create a patch following what you've suggested ?

**Comment by rdxsasha** [comment]
Hi, @tomzawadzki 
sorry, had a problem to setup gerrit at my Mac.
Assume will be able to arrange it and subscribe patch not later than this weekend.

**Comment by tomzawadzki** [comment]
@rdxsasha Have you had a change to look at submitting a patch ?

**Comment by optimistyzy** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/8813

**Comment by tomzawadzki** [comment]
Patch fixing this issue has been merged.
