### ISSUE TITLE
igb_uio.ko fails to load when using --with-igb-uio-driver

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1751]
## Current Behavior

igb_uio.ko fails to load when SPDK is built with --with-igb-uio-driver option
First occurrence: https://ci.spdk.io/public_build/autotest-per-patch_34571.html

## Steps to Reproduce

1. Checkout SPDK https://review.spdk.io/gerrit/c/5347/13, update submodules (make sure dpdk 20.11 is used)
2. Build with `--with-igb-uio-driver` 
3. Run scripts/setup.sh
4. Results in:
```
00:02:46.699  15:44:20	# /home/vagrant/spdk_repo/spdk/scripts/setup.sh
00:02:46.879 0000:00:03.0 (1af4 1001): Active mountpoints on vda:vda1, so not binding PCI dev
00:02:46.896 insmod: ERROR: could not load module /home/vagrant/spdk_repo/spdk/dpdk/build-tmp/kernel/linux/igb_uio/igb_uio.ko: No such file or directory
00:02:46.965 0000:00:06.0 (8086 5845): nvme -> igb_uio
00:02:46.965 /home/vagrant/spdk_repo/spdk/scripts/setup.sh: line 139: /sys/bus/pci/drivers/igb_uio/new_id: No such file or directory
00:02:46.965 /home/vagrant/spdk_repo/spdk/scripts/setup.sh: line 140: /sys/bus/pci/drivers/igb_uio/bind: No such file or directory
[...]
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK 8f40b23192bd305af03d794420a58db71886a5d2
SPDK/DPDK v20.11

Encountered on CentOS8 4.18.0-240.1.1.el8_3.x86_64
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

**Comment by karlatec** [comment]
Proposed fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/6006
Let's use this to provision CI test systems and have igb_uio module in place.

**Comment by karlatec** [comment]
Along with the updated provisioning script this is needed: https://review.spdk.io/gerrit/c/spdk/spdk/+/6016/2

**Comment by tomzawadzki** [comment]
Both patches above are now merged to allow compiling of the igb_uio module. 
Besides that, option `--with-igb-uio-driver` is now removed since DPDK submodule does not support it https://review.spdk.io/gerrit/c/spdk/spdk/+/6033. 

@karlatec Can you confirm that after the merges, test systems provision correctly with igb_uio ?

**Comment by karlatec** [comment]
@tomzawadzki Centos8 VMs (which user igb_uio) now run correctly. Closing the issue.
