### ISSUE TITLE
Blobfs performance seems too slow

### ISSUE THREAD

**Issue by toan2013** [spdk/spdk#1752]
## Expected Behavior
I compare performance of blobfs using rocksdb against perf (SPDK app). Both of tests are done in sequential writing to NVMe (Samsung 960 pro). Perf produces 32820.12 IOPS, 2051.23 MiB/s which is close to Samsung spec (2100 MiB/s). rocksdb application only reaches to 1381 MiB/s.  Blobfs performance (67% of Perf test) seems too slow. Are there any parameters should I change to improve it? Thanks

## Current Behavior
Blobfs performance is about 67% of perf test

## Steps to Reproduce

1.  Run perf test for 60sec until complete: 
sudo ./perf -q 16 -o 65535 -w write -r 'trtype:PCIe traddr:0000:07:00.0' -t 60 -c 0x8
2.  Run rocksdb until complete
cd /opt/spdk/spdk-20.07/test/blobfs/rocksdb
sudo ./rocksdb.sh rocksdb.conf Nvme0n1

## Context (Environment including OS version, SPDK version, etc.)
OS: CentOS Linux release 7.9.2009
Kernel: 5.1.6-1.el7.elrepo.x86_64
SPDK: 20.07
Samsung Pro 960
768GB RAM

**_rocksdb test configuration:_**
_insert_flags.txt:_
--disable_seek_compaction=1
--mmap_read=0
--statistics=1
--histogram=1
--key_size=256
--value_size=16384
--block_size=65536
#--cache_size=0
--bloom_bits=10
--cache_numshardbits=4
--open_files=500000
--verify_checksum=0
--db=/mnt/rocksdb
--sync=0
--compression_type=none
--stats_interval=1000000
--compression_ratio=0
--disable_data_sync=0
--target_file_size_base=67108864
--max_write_buffer_number=3
--max_bytes_for_level_multiplier=1
--max_background_compactions=1
--num_levels=1
--delete_obsolete_files_period_micros=3000000
--max_grandparent_overlap_factor=10
--stats_per_interval=1
--writable_file_max_buffer_size=64
--benchmarks=fillseq
--threads=1
--disable_wal=1
--use_existing_db=0
#NOTE: --num=200000000 produces 1281.5 MiB/s
--num=20000000
--spdk=/opt/spdk/spdk-20.07/test/blobfs/rocksdb/rocksdb.conf
--spdk_bdev=Nvme0n1
--spdk_cache_size=2048

_rocksdb.conf:_
[Global]
  ReactorMask 0x8
  TpointGroupMask 0x80
[Nvme]
  TransportID "trtype:PCIe traddr:0000:07:00.0" Nvme0

**Comment by changpe1** [comment]
@toan2013 I don't think it's fair to compare the performance like this.

For perf tests, it's sequential write, for Rocksdb fillseq test, it's may not 100% sequential write from the drive's perspective.

**Comment by changpe1** [comment]
closing this issue for now as there is noting for SPDK to do in practice.
