### ISSUE TITLE
nvmf apps conf cause segmentation fault, due to uninitialized pointer

### ISSUE THREAD

**Issue by ehudmarvell** [spdk/spdk#176]
spdk_nvmf_parse_subsystem() call spdk_nvmf_construct_subsystem() after initialized the following listen_addrs fields:
	char *transport;
	char *traddr;
	char *trsvcid;
but didn’t initialized char *adrfam ;

afterwards  while calling spdk_nvmf_construct_subsystem “addresses[i].adrfam” may be NULL or not, if it doesn’t and the pointer isn’t valid a segmentation fault will happen at spdk_nvme_transport_id_parse_adrfam() while calling to “strcasecmp()”

```
static int
spdk_nvmf_parse_subsystem(struct spdk_conf_section *sp)
{
	const char *nqn, *mode_str;
	int i, ret;
	int lcore;
	int num_listen_addrs;
	struct rpc_listen_address listen_addrs[MAX_LISTEN_ADDRESSES]; -> **didn’t initialized (using {} fixed the problem**)  
	char *listen_addrs_str[MAX_LISTEN_ADDRESSES] = {};
...
spdk_nvmf_construct_subsystem(const char *name,
			      const char *mode_str, int32_t lcore,
			      int num_listen_addresses, struct rpc_listen_address *addresses,
			      int num_hosts, char *hosts[], const char *bdf,
			      const char *sn, int num_devs, char *dev_list[])
{
...
		adrfam_str = addresses[i].adrfam; **-> isnt always NULL may have invalid pointer**
		if (adrfam_str == NULL) {
			adrfam_str = "IPv4";
		}

```

my conf file:
[nvmf_target2.txt](https://github.com/spdk/spdk/files/1190141/nvmf_target2.txt)

to fix the problem I replace:
**struct rpc_listen_address listen_addrs[MAX_LISTEN_ADDRESSES];**
with
**struct rpc_listen_address listen_addrs[MAX_LISTEN_ADDRESSES] = {};** 

Thanks,
Ehud

**Comment by jimharris** [comment]
Hi Ehud,

Thanks for the bug report, root cause and fix.  We will apply this shortly.

-Jim

**Comment by dverkamp-intel** [comment]
Patch is out for review: https://review.gerrithub.io/#/c/372143/

Thanks for the report!

**Comment by ehudmarvell** [comment]
Thanks again for your help and the fast response
