### ISSUE TITLE
examples/interrupt_tgt/interrupt_tgt.c should not be compiled when vhost is disabled

### ISSUE THREAD

**Issue by rch0wdhury** [spdk/spdk#1765]
If --without-vhost is specified or we are using custom env (vhost is diabled in that case also) intrrupt_tgt.c should not be compiled because it might not be able to find vhost symbols

interrupt_tgt.c:51: undefined reference to `spdk_vhost_set_socket_path'

**Comment by yidong0635** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/6088

**Comment by tomzawadzki** [comment]
Fix linked by @yidong0635 was merged. This should resolve the issue.
@rch0wdhury thank you for the submission !
