### ISSUE TITLE
spdk_for_each_reactor() can cause memory leak on application shutdown

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#1766]
When spdk_for_each_reactor function is called before application shutdown started and shutdown is triggered before spdk_for_each_reactor finished going through all reactors we end up with memory leak from this function.

This line in spdk_for_each_reactor() is causing memory leak:

cr = calloc(1, sizeof(*cr));

Shutdown process aborts events calls and function on_reactor(), which frees 'cr', is never called.

**Comment by changpe1** [comment]
Here is one reference failure log:
https://ci.spdk.io/results/autotest-per-patch/builds/35259/archive/nvme-vg-autotest/build.log

**Comment by changpe1** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/6080

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35323.html

**Comment by dong-liuliu** [comment]
this might be a general but potential issue.
Due to no alignment on reactors' leaving reactor_run, not only spdk_for_each_reactor will meet this issue.
When the event function of one spdk_event has malloc operation, it is also possible that the allocated memory has no chance to free, if the spdk_event is enqueued into reactor, but reactor is already leave reactor_run.

**Comment by shuhei-matsumoto** [comment]
I think the right fix is to use not global state but state per reactor, and then maybe to reap received events and fail spdk_event_allocate(). However, it is hard to complete by 21.01 :)

How frequent does this issue occur? If so frequent, Maciej's fix or disbling the corresponding test case will be practical workaround.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/6104

**Comment by tomzawadzki** [comment]
Alternative approach from Jim was merged, which should resolve the currently observed issue.

It might be worth to see how we could address further potential, yet unobserved, issues with spdk_for_each_reactor(). Just like @shuhei-matsumoto and @dong-liuliu suggested.
