### ISSUE TITLE
lib/event/dpdk_governor.c should not get compiled for non-DPDK env

### ISSUE THREAD

**Issue by rch0wdhury** [spdk/spdk#1767]
lib/event/dpdk_governor.c includes DPDK header file and it will fail to compile for custom env. If custom env is being used, lib/event Makefile should be changed so that we do not compile lib/event/dpdk_governor.c

**Comment by Maciej-Szwed** [comment]
Fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/6102

**Comment by changpe1** [comment]
Patch has been merged, closing this issue now.
