### ISSUE TITLE
Spdk Compiling Error

### ISSUE THREAD

**Issue by hellowaywewe** [spdk/spdk#177]
Hi, my name is Helloway and this is my first try of installing spdk, but some errors occured as follows.

When I compiled spdk package, something unexpected happened:
```
make DPDK_DIR=x86_64-native-linuxapp-gcc
CC test/unit/lib/vhost/vhost.c/vhost_ut.o
rte_vhost.h:47:24: fatal error: rte_memory.h: No such file or directory
#include "rte_memory.h"
^
compilation terminated.
make[5]: *** [vhost_ut.o] Error 1
make[4]: *** [vhost.c] Error 2
make[3]: *** [vhost] Error 2
make[2]: *** [lib] Error 2
make[1]: *** [unit] Error 2
make: *** [test] Error 2
```

I tried two versions of dpdk, such as dpdk-16.11 and dpdk-17.02,  to compile spdk, but it was still not working. Could someone offer some help? I compiled spdk in CENTOS 7.2.

**Comment by optimistyzy** [comment]
You can checkout the spdk code, then type "./configure". Then init the submodule "git submodule init". It will download the dpdk, and you just type make, this should be easy

**Comment by benlwalker** [comment]
This means that your DPDK installation is not in the directory x86_64-native-linuxapp-gcc. Make DPDK_DIR point at the the DPDK installation directory and it will work.

If you are using the latest SPDK, you can do what @optimistyzy suggested and take advantage of our new configure script and our DPDK submodule. That will set everything up for you correctly. Follow the steps starting here:

https://github.com/spdk/spdk#source-code

**Comment by hellowaywewe** [comment]
Thank @optimistyzy and @benlwalker  for all. I Made DPDK_DIR point at the the DPDK installation directory and it  works.  But when I ran the hello_world in the /spdk/examples/nvme／hello_world/, it showed "no NVMe controllers found". I tried use vagrant command, However, In my centos7.2, I could not find "vagrant" command. 
'''
[ceph@node-client hello_world]$ sudo ./hello_world 
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk0 --base-virtaddr=0x1000000000 --proc-type=auto ]
EAL: Detected 2 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: Probing VFIO support...
Initializing NVMe Controllers
no NVMe controllers found
'''
I use parelles desktop virtual machine, not VirtualBox in my macbook pro. Should I use VirtualBox and install vagrant in my centos7.2?  Could someone offer some help?

**Comment by hellowaywewe** [comment]
Thank @optimistyzy and @benlwalker for all. I Made DPDK_DIR point at the the DPDK installation directory and it works. But when I ran the hello_world in the /spdk/examples/nvme／hello_world/, it showed "no NVMe controllers found". I tried use vagrant command, However, In my centos7.2, I could not find "vagrant" command.
```
[ceph@node-client hello_world]$ sudo ./hello_world
Starting DPDK 17.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk0 --base-virtaddr=0x1000000000 --proc-type=auto ]
EAL: Detected 2 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: Probing VFIO support...
Initializing NVMe Controllers
no NVMe controllers found
```
I use parelles desktop virtual machine, not VirtualBox in my macbook pro. Should I use VirtualBox and install vagrant in my centos7.2? Could someone offer some help?

**Comment by jimharris** [comment]
Hi,

The SPDK Vagrant scripts are not set up to use a Parallels Desktop provider – primarily because it does not support NVMe emulation.  So I would suggest using VirtualBox on your MacBook Pro (including the VirtualBox Extension Pack needed for NVMe emulation).  Also install Vagrant on your MacBook Pro (not in your CentOS 7.2 VM) and clone SPDK on your MacBook Pro.  Then you can follow the instructions in scripts/vagrant/README.md to get the VM up and running and ready to use SPDK.

One note – by default, the SPDK Vagrant scripts will set up an Ubuntu 16.04 VM.  if you want Vagrant to set up a CentOS 7.2 VM instead, edit scripts/vagrant/env.sh and set SPDK_VAGRANT_DISTRO=centos7.

-Jim

**Comment by hellowaywewe** [comment]
@optimistyzy @benlwalker @jimharris thank you vey much! I have succeeded in running hello_world.

**Comment by ravisure** [comment]
Hi,
I followed the following steps to download latest source code.
_________________________________________________
git clone https://github.com/spdk/spdk
cd spdk
git submodule update --init
_______________________________________
Then I ran ./configure   and make 
But I get the following error asking meson.

[root@c202f06fs03a spdk]# make
/bin/sh: meson: command not found
make[1]: *** [Makefile:149: /home/rs/spdk/new_spdk/spdk/dpdk/build-tmp] Error 127
make: *** [/home/rs/spdk/new_spdk/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
[root@c202f06fs03a spdk]#

Is there a way to build this code without meson?

**Comment by AlekseyMarchuk** [comment]
Hi, the latest DPDK requires meson and ninja. You can run `scripts/pkgdep.sh` to install all needed packages
