### ISSUE TITLE
[vagrant] start of ubuntu fails at `rm -rf /var/cache/apt/archives`

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1775]
```
00:01:56.364  The following SSH command responded with a non-zero exit status.
00:01:56.364  Vagrant assumes that this means the command failed!
00:01:56.364  
00:01:56.364  rm -rf /var/cache/apt/archives
00:01:56.364  
00:01:56.364  Stdout from the command:
00:01:56.364  
00:01:56.364  
00:01:56.364  
00:01:56.364  Stderr from the command:
00:01:56.364  
00:01:56.364  rm: cannot remove '/var/cache/apt/archives': Directory not empty
00:01:56.412  + cd ubuntu1804-libvirt
00:01:56.412  + vagrant destroy -f
00:01:59.401  ==> default: Removing domain...
00:01:59.788  Build step 'Execute shell' marked build as failure
00:01:59.902  [PostBuildScript] - [INFO] Executing post build scripts.
00:01:59.909  [ubuntu18-vg-autotest@2] $ /usr/bin/env bash /tmp/jenkins5288946763623174228.sh
00:01:59.913  + [[ -n ubuntu1804 ]]
00:01:59.914  + mv /var/jenkins/workspace/ubuntu18-vg-autotest@2/ubuntu1804-libvirt/output /var/jenkins/workspace/ubuntu18-vg-autotest@2/output
00:01:59.934  [ubuntu18-vg-autotest@2] $ /usr/bin/env bash /tmp/jenkins5799317812572911072.sh
00:01:59.938  Start stage post_get_build_log.sh
```

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_35508.html
https://ci.spdk.io/results/autotest-per-patch/builds/35508/archive/ubuntu18-vg-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35508.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35864.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35869.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36687.html

**Comment by karlatec** [comment]
https://ci.spdk.io/public_build/autotest-per-patch_37526.html

**Comment by tomzawadzki** [comment]
@mikeBashStuff Any update on this issue ?

**Comment by mikeBashStuff** [comment]
@tomzawadzki This should not be happening anymore since we already merged patches which disable vagrant's cachier, so the path the plugin was touching should be free of its curse.

**Comment by mikeBashStuff** [comment]
Also, just to note, the VM images are now also cleaned up of any lingering, unnecessary garbage, this includes contents of apt-get's archive dir. So even if vagrant's cachier would be in play, the dir it touches would be in fact empty.

**Comment by mikeBashStuff** [comment]
So with the above in mind, closing.
