### ISSUE TITLE
SPDK applications fail to link after DPDK main branch commit 682a6454

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1776]
DPDK main branch commit 682a6454 adds a new rte_power dependency on rte_ethdev.  SPDK build environment currently does not link rte_ethdev, so the link operations fail.

I'll be pushing a patch to add this new dependency.  I've also contacted the patch author (Liang Ma from Intel) about moving the functionality from this patch into rte_ethdev instead, since these APIs are operations to perform on an ethdev queue.  It's doubtful that will happen in time for the upcoming DPDK 21.02 release though - more likely they would change the APIs in DPDK 21.05 (these APIs are marked experimental).

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/6210

**Comment by tomzawadzki** [comment]
The patch https://review.spdk.io/gerrit/c/spdk/spdk/+/6210 was merged to latest SPDK and backported to v21.01.x.
