### ISSUE TITLE
Segmentation fault in nvme_ctrlr_proc_remove_io_qpair() when trying to free an I/O qpair

### ISSUE THREAD

**Issue by rmvasuki** [spdk/spdk#1777]
Segmentation fault in nvme_ctrlr_proc_remove_io_qpair() seen when freeing an I/O qpair.

## Expected Behavior

The application should not panic and no segmentation fault should be seen.

## Current Behavior

A segmentation fault when trying to access the per_process_tailq tailq in the ctrlr->active_proc.

## Possible Solution

For SPDK 20.07, this patch seems to solve the problem:
```
diff --git a/lib/nvme/nvme_ctrlr.c b/lib/nvme/nvme_ctrlr.c
index 648cc83..36d76ca 100644
--- a/lib/nvme/nvme_ctrlr.c
+++ b/lib/nvme/nvme_ctrlr.c
@@ -452,7 +452,18 @@ spdk_nvme_ctrlr_alloc_io_qpair(struct spdk_nvme_ctrlr *ctrlr,
        rc = spdk_nvme_ctrlr_connect_io_qpair(ctrlr, qpair);
        if (rc != 0) {
                SPDK_ERRLOG("nvme_transport_ctrlr_connect_io_qpair() failed\n");
+
+               nvme_robust_mutex_lock(&ctrlr->ctrlr_lock);
+
+               nvme_ctrlr_proc_remove_io_qpair(qpair);
+
+               TAILQ_REMOVE(&ctrlr->active_io_qpairs, qpair, tailq);
+
+               spdk_bit_array_set(ctrlr->free_io_qids, qpair->id);
+
                nvme_transport_ctrlr_delete_io_qpair(ctrlr, qpair);
+
+               nvme_robust_mutex_unlock(&ctrlr->ctrlr_lock);
                return NULL;
        }
```

## Steps to Reproduce

1. Introduce a failure in spdk_nvme_ctrlr_connect_io_qpair() so that spdk_nvme_ctrlr_alloc_io_qpair() fails.
    The qpair variable will still be on various tailqs, but will be freed by nvme_transport_ctrlr_delete_io_qpair().
2. Allocate and free another I/O qpair. The segmentation fault should be seen while trying to free the qpair.

## Context (Environment including OS version, SPDK version, etc.)
Linux 3.10
SPDK 20.07

**Comment by rmvasuki** [comment]
@jimharris suggested that a unit test also be added for this.

**Comment by changpe1** [comment]
@rmvasuki do you want to submit a patch for it?

**Comment by rmvasuki** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/6272
