### ISSUE TITLE
compile err,can not find <libaio.h>

### ISSUE THREAD

**Issue by liable11** [spdk/spdk#178]
CC lib/bdev/aio/bdev_aio.o
In file included from bdev_aio.c:34:0:
bdev_aio.h:39:20: fatal error: libaio.h: No such file or directory
 #include <libaio.h>

**Comment by liable11** [comment]
libaio.h  can not find in spdk 1707  include

**Comment by jimharris** [comment]
Hi,

This file should be installed with the appropriate aio package prerequisite. Can you check the README and make sure you installed all of the prerequisite packages?

Thanks,

Jim

On Aug 7, 2017, at 7:30 PM, liable11 <notifications@github.com<mailto:notifications@github.com>> wrote:


libaio.h can not find in spdk 1707 include

**Comment by liable11** [comment]
thanks!
