### ISSUE TITLE
iSCSI target cannot process the case that each Data-Out PDU is not block multiples but totally Data-Out sequence is block multiples  

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1781]
When we use VMware ESXi7.0 + Emulex OCe11102 (H/W iSCSI) as a iSCSI host to SPDK iSCSI target, read I/O worked but write I/O caused check condition to SPDK iSCSI target.

The iSCSI host sent 1st Data-Out PDU whose data size is 2848 and 2nd Data-Out PDU whose data size is 6368, and sum of  two is 9216. 9216 is 512 multiples but 2848 and 6368 cannot be divided by 512.

## Expected Behavior

SCSI write whose data size is 9216 is submitted to SPDK SCSI.

## Current Behavior

Two SCSI writes, whose size are 2848 and 6368, are submitted to SPDK SCSI, and both caused check condition.
 
## Possible Solution

One iSCSI task has two such PDUs and SCSI task creates SGL by two data segments.

## Steps to Reproduce

See above.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.04
VMware ESXi 7.0
Emulex OCe11102 (H/W iSCSI)

**Comment by optimistyzy** [comment]
Hi @shuhei-matsumoto  Could you show some log in SPDK target side.

**Comment by shuhei-matsumoto** [comment]
Hi @optimistyzy Unfortunately it's difficult or probably impossible for me to get and share such log.
I feel that associating multiple PDUs with one subtask and using SGL is easier solution, and will work on that.

**Comment by shuhei-matsumoto** [comment]
Hi @optimistyzy @jimharris 

I know that iSCSI host sent multiple Data-Out PDUs to one R2T from my colleague.

Current my idea is as follows:
-  associate multiple pdus with one iscsi_subtask by changing pointer to linked list (use STAILQ)
-  add a fixed-size iov array and iovcnt to struct spdk_iscsi_task
-  set multiple pdu->data to iscsi_subtask->iovs
-  set iscsi_subtask->iovs and iscsi_subtask->iovcnt to scsi_task->iovs and scsi_task->iovcnt.

Current struct spdk_scsi_task has a pointer, iovs, and iovcnt as same as struct spdk_bdev_io, but there is no way to configure them from outside.

**Comment by optimistyzy** [comment]
> Hi @optimistyzy Unfortunately it's difficult or probably impossible for me to get and share such log.
> I feel that associating multiple PDUs with one subtask and using SGL is easier solution, and will work on that.

I do not suggest use multiple subtask. My suggestion is that using one sub task for all the data out pdu for one R2T pdu response

**Comment by shuhei-matsumoto** [comment]
[Bug scrub] The idea we got consensus is as follows. Share the same data buffer among multiple PDUs by shifting the offset, associate multiple PDUs with the same single task. Sharing the same data buffer is needed to use NVMe bdev. Out of order Data-Out PDUs may come. So connection has to hold  data buffer for each SCSI command until receiving all the data.

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris @ZiyeYang and all,

Patch series is on gerrit now. The idea is as follows.

Try to merge multiple Data-OUT PDUs in the same sequence as much as possible until 64KB or the sequnce ends (i.e., F bit is set).
MaxRecvDataSegmentLength is 64KB but MaxBurstLength is 1MB. The data buffer size is at most 64KB. So iSCSI initiator sends 1MB Data-OUT PDU sequence at the maximum. 

Number of splitting the data segment of a single PDU is  at most two.

Submit one write subtask per data buffer.
Data buffer is made of struct spdk_mobj and it may have multiple PDUs' data segment.

When processing the data segment of the Data-OUT PDU,
submit a write subtask if the first data buffer is full or F bit is set, or inherit the first data buffer to the current primary task otherwise.
If the second data buffer is empty, return now, or submit a write subtask if the second data buffer is full or F bit is set.

When reading the data segment of the Data-OUT PDU,
if the first data buffer becomes full, allocate the second data buffer and shift related offsets.

When processing the header of the Data-Out PDU,
inherit the data buffer from the primary task if the primary task has it, and update related offsets. It is used as the first data buffer.
This is done before allocating the first data buffer.

All are enabled only if DIF is disabled. Supporting DIF case is TODO.

The patch series starts from https://review.spdk.io/gerrit/c/spdk/spdk/+/6360/2

Testing on the actual system is being done separately in parallel.

**Comment by jimharris** [comment]
Patches have been merged.  Thanks @shuhei-matsumoto!
