### ISSUE TITLE
[rocksdb_insert] Build timeout

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1782]
00:14:22.592  ************************************
00:14:22.592  START TEST rocksdb_insert
00:14:22.592  ************************************
00:14:22.593   17:36:47	# xtrace_enable
00:14:22.593   17:36:47	# run_step insert
00:14:22.593   17:36:47	# '[' -z insert ']'
00:14:22.593   17:36:47	# cat
00:14:22.594   17:36:47	# db_bench=insert_db_bench.txt
00:14:22.594   17:36:47	# echo -n Start insert test phase...
00:14:22.594  Start insert test phase... 17:36:47	# taskset 0xFF /var/jenkins/workspace/BlobFS-autotest/spdk/../rocksdb/db_bench --flagfile=insert_flags.txt
00:15:00.490  Build timed out (after 15 minutes). Marking the build as failed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_35760.html

**Comment by jimharris** [comment]
@peluse,

This looks more like another case of #1686.  I looked briefly at the log, there's this:

00:00:00.526  Cloning into '/var/jenkins/workspace/BlobFS-autotest/spdk'...
00:11:04.328  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:11:15.127  git version 2.26.2
00:11:17.535  warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
00:11:18.526  remote: Counting objects: 1           
remote: Counting objects: 85, done        
00:11:18.767  remote: Finding sources:   1% (1/61)           

So we wasted 11 minutes cloning.  This didn't have anything to do with the rocksdb_insert test - it was just victim to so much time wasted earlier in the autotest.

Could you move this report to #1686 and close this issue?

**Comment by jimharris** [comment]
Moved this report to #1686.
