### ISSUE TITLE
SPDK Compiling Error While Executing "vagrant up" on centos7

### ISSUE THREAD

**Issue by kriw** [spdk/spdk#179]
Compilation Error occurred when I set up spdk on centos7.
It seems to need CUnit.
```bash
$ SPDK_VAGRANT_DISTRO="centos7" vagrant up

==> default: In file included from spdk_cunit.c:36:0:
==> default: /spdk/test/spdk_cunit.h:39:25: fatal error: CUnit/Basic.h: No such file or directory
==> default:  #include <CUnit/Basic.h>
==> default:                          ^
==> default: compilation terminated.
```

**Comment by alekseymmm** [comment]
As it is said in README... 
Prerequisites section

**Comment by kriw** [comment]
I know this is written in prerequisites section.
The issue is that it is used vagrant of https://github.com/spdk/spdk/tree/master/scripts/vagrant .
 `build.sh` is executed during `vagrant up`, but the installation is failed because of lack of a library.
Setting up should have successfully finished when `vagrant up` is executed.
