### ISSUE TITLE
Enhance error messages to include information that identifies the controller

### ISSUE THREAD

**Issue by rmvasuki** [spdk/spdk#1790]
Error messages do not include any details that can help identify the actual controller that is seeing errors.

## Expected Behavior

Include some information that can uniquely identify the controller (e.g. PCIe: bus address/RDMA: subnqn) in the error message.

## Current Behavior

No identifying information seen:
```
nvme_fabric.c:451 - nvme_fabric_qpair_connect: Connect command failed
nvme_rdma.c:1363 - _nvme_rdma_ctrlr_connect_qpair: Failed to send an NVMe-oF Fabric CONNECT command
nvme_ctrlr.c:454 - spdk_nvme_ctrlr_alloc_io_qpair: nvme_transport_ctrlr_connect_io_qpair() failed
nvme_ctrlr.c:1209 - spdk_nvme_ctrlr_reset: resetting controller
nvme_ctrlr.c:799 - nvme_ctrlr_fail: ctrlr 10.3.1.100 in failed state.
```

## Possible Solution

None.

## Steps to Reproduce

Observe log files after any sort of failure.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.07

**Comment by AlekseyMarchuk** [comment]
Hi @rmvasuki do you plan to submit a patch to address this issue? I'm asking because recently I faced the same problem and I have a draft patch which adds more details to these prints, I can clean it up and send for review

**Comment by AlekseyMarchuk** [comment]
I pushed a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/6338 
It updates error logs in nvme_fabric.c
With this patch I got the following errors when I didn't allow subsystem to accept connections from the host:
```
[2021-02-09 12:21:19.206233] nvme_fabric.c: 464:nvme_fabric_qpair_connect: *ERROR*: Connect command failed (0) trtype:RDMA adrfam:IPv4 traddr:1.1.75.1 trsvcid:4420 subnqn:nqn.2018-09.io.spdk:cnode1
[2021-02-09 12:21:19.206269] nvme_fabric.c: 467:nvme_fabric_qpair_connect: *ERROR*: Connect command completed with error: sct 1, sc 132
[2021-02-09 12:21:19.206290] nvme_rdma.c:1223:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
[2021-02-09 12:21:19.215363] nvme_rdma.c:1836:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
[2021-02-09 12:21:19.215396] nvme_ctrlr.c: 919:nvme_ctrlr_shutdown_async: *ERROR*: ctrlr 1.1.75.1 get_cc() failed
[2021-02-09 12:21:19.215436] nvme.c: 675:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 1.1.75.1
[2021-02-09 12:21:19.215457] nvme.c: 818:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2021-02-09 12:21:19.215473] nvme.c: 895:spdk_nvme_probe: *ERROR*: Create probe context failed

```
Please reply if you want to add more details

**Comment by rmvasuki** [comment]
> I pushed a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/6338
> It updates error logs in nvme_fabric.c
> With this patch I got the following errors when I didn't allow subsystem to accept connections from the host:
> 
> ```
> [2021-02-09 12:21:19.206233] nvme_fabric.c: 464:nvme_fabric_qpair_connect: *ERROR*: Connect command failed (0) trtype:RDMA adrfam:IPv4 traddr:1.1.75.1 trsvcid:4420 subnqn:nqn.2018-09.io.spdk:cnode1
> [2021-02-09 12:21:19.206269] nvme_fabric.c: 467:nvme_fabric_qpair_connect: *ERROR*: Connect command completed with error: sct 1, sc 132
> [2021-02-09 12:21:19.206290] nvme_rdma.c:1223:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
> [2021-02-09 12:21:19.215363] nvme_rdma.c:1836:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
> [2021-02-09 12:21:19.215396] nvme_ctrlr.c: 919:nvme_ctrlr_shutdown_async: *ERROR*: ctrlr 1.1.75.1 get_cc() failed
> [2021-02-09 12:21:19.215436] nvme.c: 675:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 1.1.75.1
> [2021-02-09 12:21:19.215457] nvme.c: 818:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
> [2021-02-09 12:21:19.215473] nvme.c: 895:spdk_nvme_probe: *ERROR*: Create probe context failed
> ```
> 
> Please reply if you want to add more details

Thanks, I think this information is good enough for us to identify the failing controller.
The only problem is that we need to make this change in a few different places.
I will also submit a patch after modifying the log messages that we have found useful on our system.

**Comment by changpe1** [comment]
@rmvasuki Go ahead to submit a improvement patch for it, I assign this issue back to you.

**Comment by jimharris** [comment]
It looks like this patch from @Comphix is going to eventually address this issue:

https://review.spdk.io/gerrit/c/spdk/spdk/+/7057

**Comment by jimharris** [comment]
Patch from @Comphix was merged, so closing this issue.
