### ISSUE TITLE
[compress_qat] bdevperf.py perform_tests timed out

### ISSUE THREAD

**Issue by floatious** [spdk/spdk#1791]
00:15:27.279  ************************************
00:15:27.279  START TEST compress_qat
00:15:27.279  ************************************
...
00:15:34.460   14:33:07	# /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_get_bdevs
00:15:34.461   14:33:07	# jq -r '.[] .name'
00:15:34.461   14:33:07	# grep -qw COMP_lvs0/lv0
00:15:34.644   14:33:07	# return 0
00:15:34.693   14:33:07	# /var/jenkins/workspace/crypto-autotest/spdk/test/bdev/bdevperf/bdevperf.py perform_tests
00:15:34.720  Running I/O for 3 seconds...
00:15:36.341  Build timed out (after 15 minutes). Marking the build as failed.
00:15:36.353  Build was aborted

https://ci.spdk.io/public_build/autotest-per-patch_36198.html
https://ci.spdk.io/results/autotest-per-patch/builds/36198/archive/crypto-autotest/index.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @floatious. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36198.html

**Comment by mikeBashStuff** [comment]
This is yet another case of #1686

**Comment by jimharris** [comment]
Agreed.  I've copied this report to #1686 and closing this issue.
