### ISSUE TITLE
An error occurred in the underlying SSH library that Vagrant uses

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1792]
```
00:03:56.619  + vagrant ssh -c 'git -C /home/vagrant/spdk_repo/spdk reset --hard'
00:04:15.845  HEAD is now at 74d670bfd nvme/rdma: Use RDMA provider API to post recv WRs
00:04:15.882  + [[ -f /var/jenkins/workspace/freebsd-vg-autotest/autorun-spdk.conf ]]
00:04:15.882  + vagrant upload /var/jenkins/workspace/freebsd-vg-autotest/autorun-spdk.conf /home/vagrant/autorun-spdk.conf
00:04:19.001  Uploading /var/jenkins/workspace/freebsd-vg-autotest/autorun-spdk.conf to /home/vagrant/autorun-spdk.conf
00:04:34.232  An error occurred in the underlying SSH library that Vagrant uses.
00:04:34.232  The error message is shown below. In many cases, errors from this
00:04:34.232  library are caused by ssh-agent issues. Try disabling your SSH
00:04:34.232  agent or removing some keys and try again.
00:04:34.232  
00:04:34.232  If the problem persists, please report a bug to the net-ssh project.
00:04:34.232  
00:04:34.232  timeout during server version negotiating
00:04:34.259  + vagrant destroy -f
00:04:37.359  ==> default: Removing domain...
00:04:37.664  Build step 'Execute shell' marked build as failure
00:04:37.707  [PostBuildScript] - [INFO] Executing post build scripts.
00:04:37.713  [freebsd-vg-autotest] $ /usr/bin/env bash /tmp/jenkins6943410328465888421.sh
00:04:37.717  + [[ -n freebsd12 ]]
00:04:37.717  + mv /var/jenkins/workspace/freebsd-vg-autotest/freebsd12-libvirt/output /var/jenkins/workspace/freebsd-vg-autotest/output
00:04:37.735  [freebsd-vg-autotest] $ /usr/bin/env bash /tmp/jenkins5674928603913516642.sh
00:04:37.739  Start stage post_get_build_log.sh
```

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_36183.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36183.html

**Comment by AlekseyMarchuk** [comment]
I think that it will be hard to reproduce this issue manually, but let's keep it for some time, if no new occurrences reported then we could close it

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36807.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_36832.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @nconnolly1. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_37966.html

**Comment by AlekseyMarchuk** [comment]
Reporting manually since `false positive` is not working https://ci.spdk.io/public_build/autotest-per-patch_38031.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_38140.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_38470.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_38465.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_38585.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @floatious. log: https://ci.spdk.io/public_build/autotest-per-patch_39151.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_39564.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_39651.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_39938.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_40380.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_41193.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41151.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41145.html

**Comment by jimharris** [comment]
Haven't seen this intermittent CI issue for over a month.  Closing.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_47472.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_47468.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_47490.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_47678.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_47855.html

**Comment by mikeBashStuff** [comment]
We are planning to bump ubuntu vm hosts to 20.04, hopefully newer version of the net-ssh gem will work better with openssh package installed in the freebsd VM we are using. 

@karlatec I think we should also update freebsd to 12.2 since this is what we are currently building but hosts still use 12.1 (will look into bringing 13.0 release as well since it's been available for some time now).

**Comment by mikeBashStuff** [comment]
12.2 was deployed on all VM hosts, this issue should be gone now. Closing.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_93162.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_94263.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_94745.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_95431.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_96099.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_97823.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_99031.html
