### ISSUE TITLE
[spdk_top] App crash when calling pop-up details window after switching tabs with TAB key

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#1793]
When selecting a data row in a tab, then switching to a different tab with TAB key, if the second tab has fewer rows and user calls pop-up details window with ENTER key, it'll crash the application. 

## Expected Behavior
Show pop-up details window for currently selected row.

## Current Behavior
spdk_top crashes.

## Possible Solution
Reset row counter when switching tabs with TAB key.

## Steps to Reproduce
1. Select a row unavailable in next tab (eg. POLLERS tab has 5 rows and CORES tab has only 1).
2. Switch tabs using TAB key.
3. Call pop-up details window with ENTER key.

## Context
SPDK 21.01

**Comment by KKaras169169** [comment]
Possible solution: https://review.spdk.io/gerrit/c/spdk/spdk/+/6367

**Comment by tomzawadzki** [comment]
Patch resolving the issue was merged.
