### ISSUE TITLE
event framework should not depend on dpdk

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#1802]
This issue is an output from the discussion on slack related to *.pc files which describes dependencies.

Background from Jim below.
> Jim Harris  21 hours ago
we originally kept it inside of the event framework, because the APIs for scheduler/governor are still quite experimental and we didn't want to have to define a 'public' API to put the dpdk governor in a module - but I think by time 21.04 hits it will be in good enough shape to make the governors (and schedulers) pluggable as modules

## Expected Behavior

event framework should not depend on dpdk

## Current Behavior

event framework depends on dpdk
*.pc file doesn't reflect this dep

## Steps to Reproduce

cd spdk/lib/event
grep rte_ * -r

## Context (Environment including OS version, SPDK version, etc.)

21.01 LTS

**Comment by tomzawadzki** [comment]
There is work towards this being done by @KKaras169169, [here](https://review.spdk.io/gerrit/c/spdk/spdk/+/6995). Still need to iron out the APIs to achieve that.

**Comment by tomzawadzki** [comment]
As of latest SPDK (containing https://review.spdk.io/gerrit/c/spdk/spdk/+/7119/) this is no longer an issue. @jkalwas Please let us know if the result is satisfactory.
