### ISSUE TITLE
vhost_target performance of 4k random read

### ISSUE THREAD

**Issue by zhuohaofan** [spdk/spdk#1805]
vhost_target performance of 4k random read is much lower than expected.
## Expected Behavior
I created nvmf_tgt on the storage node and added a nvme SSD. The storage client reads and writes the SSD through the RDMA network. The IOPS of random read tested by fio_plugin on the storage client can reach 700k. But the VM created on the storage client is only 300k.
By the way, the sequential read and write bandwidth, latency and 4k random write IOPS of the virtual machine vhost-user-blk are not much different from the client's performance. For example, the Random Write (100% Span) of the virtual machine is 482k, and the clinet is 505k.
The vhost I configured 4 cpus, the virtual machine configured 16 cpus, the same NUMA node with the vhost cpu.
And I have scsi_mod.use_blk_mq=1 enabled inside the guest OS.

## Steps to Reproduce

nvmf_tgt:
HUGEMEM=40960 HUGENODE=0 ./scripts/setup.sh
./build/bin/nvmf_tgt -m 0x00000fffff00000fffff -s 8192 &
./scripts/rpc.py nvmf_create_transport -t RDMA
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe0 -t PCIe -a 0000:af:00.0
./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 NVMe0n1
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.26 -s 4420

./scripts/rpc.py nvmf_get_transports
[
  {
    "trtype": "RDMA",
    "max_queue_depth": 128,
    "max_io_qpairs_per_ctrlr": 127,
    "in_capsule_data_size": 4096,
    "max_io_size": 131072,
    "io_unit_size": 8192,
    "max_aq_depth": 128,
    "num_shared_buffers": 4095,
    "buf_cache_size": 32,
    "dif_insert_or_strip": false,
    "max_srq_depth": 4096,
    "no_srq": false,
    "acceptor_backlog": 100,
    "no_wr_batching": false,
    "abort_timeout_sec": 1
  }
]

vhost:
1. host:~# HUGEMEM=81920 HUGENODE=0 ./scripts/setup.sh
2. host:~# ./build/bin/vhost -m 0xf -s 4096 -S /var/tmp/ &
3. host:~# ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t rdma -a 192.168.100.26 -f ipv4 -s 4420 -n nqn.2016-06.io.spdk:cnode1
4. host:~# ./scripts/rpc.py vhost_create_blk_controller --packed_ring --cpumask 0x0000000000f vhost.0 Nvme0n1
5. start VM
host:~# taskset -a 0x0000000000ffff0 /home/spdk/qemu/qemu-5.1.0/build/x86_64-softmmu/qemu-system-x86_64 
--enable-kvm
-cpu host -smp 16
-m 16G -object memory-backend-file,id=mem0,size=16G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0
-drive file=guest_os_image.qcow2,if=none,id=disk
-device ide-hd,drive=disk,bootindex=0
-chardev socket,id=spdk_vhost_blk0,path=/var/tmp/vhost.0
-device vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=4
6. Login VM, and run fio.
vm:~# cat test_iops_read.conf
[global]
direct=1
thread=1
iodepth=64
rw=randread
ioengine=libaio
bs=4k
#ramp_time=30
#runtime=60
runtime=100
group_reporting=1
time_based=1

[test]
offset=10%
size=100g
numjobs=12
filename=/dev/vdb
vm:~# fio -f test_iops_read.conf

## Context (Environment including OS version, SPDK version, etc.)

SPDK version:
SPDK v21.01-pre git sha1 0e47be4b4 / DPDK 20.08.0 
Qemu version: 
qemu-5.1.0

**Comment by jimharris** [comment]
Hi @zhuohaofan,

Could you try latest SPDK v21.01 release?  Please also provide more details on the VM you are using for your tests.

Can you try testing with 8 VM cores + 8 virtio-blk queues + 8 jobs?

-Jim

**Comment by zhuohaofan** [comment]
> Hi @zhuohaofan,
> 
> Could you try latest SPDK v21.01 release? Please also provide more details on the VM you are using for your tests.
> 
> Can you try testing with 8 VM cores + 8 virtio-blk queues + 8 jobs?
> 
> -Jim

The VM OS information is:
[root@vm44 ~]# uname -a
Linux vm44 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@vm44 ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
Because of network problems, I have never succeeded in pulling the latest SPDK v21.01 release.
And I will try to update later.
I try testing with 8 VM cores + 8 virtio-blk queues + 8 jobs on SPDK v21.01-pre git sha1 0e47be4 / DPDK 20.08.0.
The 4k random read IOPS is still 333k, the same as last time.

**Comment by zhuohaofan** [comment]
Hi all,
If I put the virtual machine and SSD on the same server.
I means:
host:~# ./build/bin/vhost -S /var/tmp -s 4096 -m 0x0f &
host:~# ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:af:00.0
host:~# ./scripts/rpc.py vhost_create_blk_controller --packed_ring --cpumask 0x0000000000f vhost.0 Nvme0n1

The 4k random read IOPS can reach 680k. Very ideal performance.
It looks like there is a problem with spdk vhost using RDMA network.

BTW, SPDK version is 'v21.01-pre git sha1 0e47be4 / DPDK 20.08.0'.

**Comment by zhuohaofan** [comment]
> > Hi @zhuohaofan,
> > Could you try latest SPDK v21.01 release? Please also provide more details on the VM you are using for your tests.
> > Can you try testing with 8 VM cores + 8 virtio-blk queues + 8 jobs?
> > -Jim
> 
> The VM OS information is:
> [root@vm44 ~]# uname -a
> Linux vm44 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> [root@vm44 ~]# cat /etc/redhat-release
> CentOS Linux release 7.9.2009 (Core)
> Because of network problems, I have never succeeded in pulling the latest SPDK v21.01 release.
> And I will try to update later.
> I try testing with 8 VM cores + 8 virtio-blk queues + 8 jobs on SPDK v21.01-pre git sha1 [0e47be4](https://github.com/spdk/spdk/commit/0e47be4b41dc141c03f9338f7c18dc16930fcdc2) / DPDK 20.08.0.
> The 4k random read IOPS is still 333k, the same as last time.

The 4k random read IOPS is still 330k with the latest SPDK v21.01 release.

**Comment by changpe1** [comment]
For the test case, vhost is using just 1 CPU core to process the IOs, how many CPU cores are you using with fio_plugin in Client?

**Comment by optimistyzy** [comment]
> For the test case, vhost is using just 1 CPU core to process the IOs, how many CPU cores are you using with fio_plugin in Client?

Hi Changpeng,

Could we change the vhost internal strategy. Currently, we use one cpu to server all the I/Os even if multiple coremask is enabled. Could we enable the same strategy as in NVMe-oF subsystem, that we could have multiple CPUs to serve on vhost?

**Comment by zhuohaofan** [comment]
> For the test case, vhost is using just 1 CPU core to process the IOs, how many CPU cores are you using with fio_plugin in Client?
I use the following command to run fio_plugin.
host:~# cat spdk_rand_read_4k.conf
[global]
direct=1
thread=1
iodepth=64
rw=randread
ioengine=spdk
bs=4k
ramp_time=10
runtime=60
group_reporting=1
time_based=1

[test]
offset=10%
numjobs=8
size=100g
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.100.26 trsvcid=4420

sudo LD_PRELOAD=/home/spdk/spdk/build/fio/spdk_nvme /home/spdk/fio/fio -f spdk_rand_read_4k.conf

BTW, I created vhost with '-m 0xf'.
So you mean that vhost only uses one cpu now, even if I bind more than one?

**Comment by changpe1** [comment]
@zhuohaofan You can limit fio plugin to use 1 core to see the performance result, @optimistyzy vhost is designed for multiple VMs, so users can span multiple controllers to different cores, but for 1 controller, even you can specify the core mask, it means the controller can schedule to other cores, when doing the IOs, it's running in 1 lcore.

**Comment by zhuohaofan** [comment]
> @zhuohaofan You can limit fio plugin to use 1 core to see the performance result, @optimistyzy vhost is designed for multiple VMs, so users can span multiple controllers to different cores, but for 1 controller, even you can specify the core mask, it means the controller can schedule to other cores, when doing the IOs, it's running in 1 lcore.

@changpe1 When I changed the numjobs in the fio configuration file from 8 to 1, the 4k random read iops of fio_plugin was also about 310k.
As you said, even if a controller has multiple cores, it can only use one at a time. So for a VM, it can easily reach a performance bottleneck. For example, the current 330k IOPS.

**Comment by changpe1** [comment]
Right, but in practice users can use multiple VMs, or you can assign two controllers in one VM.

**Comment by changpe1** [comment]
@zhuohaofan We don't have the plan to implement vhost to per-queue poll mechanism, do you have further question about it?
if not, I'm going to close this issue.

**Comment by changpe1** [comment]
[Bug Scrub] @tomzawadzki is investigating virtio part,  we may change the existing poll mechanism in future(not recently), so label it as an enhancement.

**Comment by zhuohaofan** [comment]
> @zhuohaofan We don't have the plan to implement vhost to per-queue poll mechanism, do you have further question about it?
> if not, I'm going to close this issue.

I don't have any other questions. Thank you for your answer.
