### ISSUE TITLE
[clang-vg-autotest] qemu-system-x86_64: failed to initialize kvm: Cannot allocate memory

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1806]
## Link to the failed CI build

http://10.211.11.56/results/autotest-per-patch/builds/37238/archive/clang-vg-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: build failed. results: https://ci.spdk.io/public_build/autotest-per-patch_37238.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_38169.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_38361.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_38228.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_38541.html

**Comment by wawryk** [comment]
All above reports occurred on SM9. 
HugePages configuration on server fixed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_38830.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_38840.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_38841.html

**Comment by wawryk** [comment]
Last reported failure was almost two weeks ago, closing this issue.
