### ISSUE TITLE
nvme hotplug: Unable to to access NVMe drives if drives are hotplugged while controller initialization is in process

### ISSUE THREAD

**Issue by rmvasuki** [spdk/spdk#1809]
If the NVMe drives are powered off while the application is probing and constructing controllers, the application is never able to recognize and construct controllers when the drives are powered on again.

## Expected Behavior

Application should be able to recognize and construct controllers after a drive power off/power on sequence.

## Current Behavior

We’re using the vfio-pci kernel driver with our application. We get into a situation where spdk_nvme_probe() fails continuously printing a few log messages, and dumps some garbage eventually:
```
EAL: Cannot find bus for device (0000:68:00.0)
EAL: Cannot find bus for device (0000:68:00.0)
..
EAL: Cannot find bus for device (ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ)
EAL: Cannot find bus for device (ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ)
```

This happens when the probe thread is attempting to intitialize a controller, and the drives are powered off externally. With some instrumentation, I was able to figure out that the device cleanup never completed, because the vfio req notifier `pci_vfio_req_handler` could not be unregistered due to `errno 11 (EAGAIN).`

```
EAL: request: eal_dev_mp_request
EAL: No shared files mode enabled, IPC is disabled
EAL: PCI device 0000:68:00.0 on NUMA socket 0
EAL:   remove driver: 144d:a822 spdk_nvme
EAL: fail to unregister req notifier handler ret = -11.
EAL: fail to disable req notifier.
```

```
(gdb) bt
#0  0x00007fffdbce07bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffdbccb535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00005555556662db in pci_vfio_unmap_resource_primary (dev=0x555555fbcf70) at ../drivers/bus/pci/linux/pci_vfio.c:1041
#3  0x00005555556665f4 in pci_vfio_unmap_resource (dev=0x555555fbcf70) at ../drivers/bus/pci/linux/pci_vfio.c:1121
#4  0x00005555556616e5 in rte_pci_unmap_device (dev=0x555555fbcf70) at ../drivers/bus/pci/linux/pci.c:103
#5  0x000055555565fd78 in rte_pci_detach_dev (dev=0x555555fbcf70) at ../drivers/bus/pci/pci_common.c:259
#6  0x00005555556605a5 in pci_unplug (dev=0x555555fbcf80) at ../drivers/bus/pci/pci_common.c:531
#7  0x000055555560ad99 in local_dev_remove (dev=0x555555fbcf80) at ../lib/librte_eal/common/eal_common_dev.c:321
#8  0x000055555560afa9 in rte_dev_remove (dev=0x555555fbcf80) at ../lib/librte_eal/common/eal_common_dev.c:402
#9  0x000055555560ad34 in rte_eal_hotplug_remove (busname=0x7fffee50a513 "pci", devname=0x7fffdb6194d0 "0000:68:00.0") at ../lib/librte_eal/common/eal_common_dev.c:306
#10 0x00007fffee4c0911 in remove_rte_dev (rte_dev=0x555555fbcf70) at pci.c:109
#11 0x00007fffee4c0c52 in pci_device_rte_hotremove (device_name=0x555555fc3890 "0000:68:00.0", event=RTE_DEV_EVENT_REMOVE, cb_arg=0x0) at pci.c:241
#12 0x000055555560bac9 in rte_dev_event_callback_process (device_name=0x555555fc3890 "0000:68:00.0", event=RTE_DEV_EVENT_REMOVE) at ../lib/librte_eal/common/eal_common_dev.c:557
#13 0x0000555555660480 in pci_hot_unplug_handler (dev=0x555555fbcf80) at ../drivers/bus/pci/pci_common.c:475
#14 0x0000555555664b22 in pci_vfio_req_handler (param=0x555555fbcf80) at ../drivers/bus/pci/linux/pci_vfio.c:377
#15 0x0000555555647b23 in eal_intr_process_interrupts (events=0x7fffdb6196a0, nfds=1) at ../lib/librte_eal/linux/eal_interrupts.c:983
#16 0x0000555555647df5 in eal_intr_handle_interrupts (pfd=8, totalfds=14) at ../lib/librte_eal/linux/eal_interrupts.c:1056
#17 0x0000555555647fa8 in eal_intr_thread_main (arg=0x0) at ../lib/librte_eal/linux/eal_interrupts.c:1127
#18 0x00005555556297f5 in rte_thread_init (arg=0x555555d80e90) at ../lib/librte_eal/common/eal_common_thread.c:175
#19 0x00007fffeee1ffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#20 0x00007fffdbda24cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
It seems like we are executing in the pci_vfio_req_handler context, and we are unable to unregister the notifier because it is currently active/executing.
Note that the application does not yet have a handle on this controller because the controller is being initialized. In fact, because the drive is powered off, the controller is freed within the context of spdk_nvme_probe itself, and we do not have any way to ask DPDK to detach this device.

Also, if our application is restarted, then the subsequent probe is able to successfully discover all the drives. This points to an issue in the cleanup path in DPDK itself.
Without a restart, our application will never be able to access the drives after they are powered on.

Slack thread: https://spdk-team.slack.com/archives/CNRUQN85P/p1614202068007400

## Possible Solution

I tried to add `spdk_pci_device_detach`  in all the failure paths in `nvme_pcie_ctrlr_construct`  but I hit an assertion in that function: `assert(dev->internal.attached);`

## Steps to Reproduce

This issue is really hard to reproduce.
We needed to restart the application and power off the drives in order to reproduce this issue.

This can be easily reproduced with some instrumentation:
1. Introduce a long delay, say 60s in `nvme_pcie_ctrlr_construct` before `nvme_ctrlr_get_cap`.
2. Power off the drive(s) before the 60s delay runs out.

## Context (Environment including OS version, SPDK version, etc.)
SPDK: 20.07
DPDK: 20.05
OS: CentOS
Using inbox vfio-pci kernel driver.

**Comment by glodfish-zg** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/6553 @rmvasuki  please try this patch.

**Comment by rmvasuki** [comment]
> https://review.spdk.io/gerrit/c/spdk/spdk/+/6553 @rmvasuki please try this patch.

@glodfish-zg this idea works. Since I'm using SPDK 20.07, the function names are a bit different, but using deferred removal works great.
