### ISSUE TITLE
SPDK scripts/setup linux_iter_pci_dev_id issue

### ISSUE THREAD

**Issue by omermargolin** [spdk/spdk#181]
linux_iter_pci_dev_id returns an extended list comparing to the previous version causing the host to halt.
introduced in:

commit c8328f557c23ad5f6f43457696da0dabed479aa9
Author: Jim Harris <james.r.harris@intel.com>
Date:   Tue Jun 20 08:39:13 2017 -0700

    setup.sh: improve class code and dev/vendor ID checking
    
    1) Create separate functions for checking the PCI class code
       vs. checking the PCI device/vendor IDs
    2) Instead of a simple grep, check the specific fields to
       ensure we avoid accidental matching of a class code
       against a device ID (or vice versa)
    
    This will make it a bit cleaner to add some new device
    IDs (i.e. virtio devices) in some future commits.
    
    Signed-off-by: Jim Harris <james.r.harris@intel.com>
    Change-Id: I36d4e2dec2f0f15dc0d603fc2512ea03a64dd560
    
    Reviewed-on: https://review.gerrithub.io/374014
    Reviewed-by: Daniel Verkamp <daniel.verkamp@intel.com>
    Tested-by: SPDK Automated Test System <sys_sgsw@intel.com>
    Reviewed-by: Ben Walker <benjamin.walker@intel.com>

**Comment by jimharris** [comment]
Hi,

Can you check if this patch fixes your issue?

https://review.gerrithub.io/#/c/374507/

Thanks,

-Jim

**Comment by omermargolin** [comment]
Patch is good.

Thanks.
