### ISSUE TITLE
crypto-autotest timed out due to a blocking make test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1810]
`make` test blocked for almost 3 minutes before it finally started building SPDK.

https://ci.spdk.io/results/autotest-per-patch/builds/37518/archive/crypto-autotest/index.html

```
00:01:05.654   15:11:56	$ xtrace_enable
00:01:05.655   15:11:56	$ make -j16
00:03:51.645  The Meson build system
00:03:51.645  Version: 0.55.3
00:03:51.645  Source dir: /var/jenkins/workspace/crypto-autotest/spdk/dpdk
00:03:51.645  Build dir: /var/jenkins/workspace/crypto-autotest/spdk/dpdk/build-tmp
```
Hence leaving the job with not enough time to properly finish. Most likely caused by a blip in a cosmos.

**Comment by tomzawadzki** [comment]
Closing due to last occurrence being 3 months ago.
