### ISSUE TITLE
app compiled in intel x86 fails to run in amd x86 platform. [-funsigned-char]

### ISSUE THREAD

**Issue by ghnicky** [spdk/spdk#1811]
when i run my application which compiled in intel x86, it will core dump in amd environment.
after i compiled the my app wich adding -funsigned-char in CFLAGS, it seems that it can solve this problem. 
But i am not sure whether it  does harm to the normal logic in SPDK.
Anyone can give some help on this question? Any help is aprreciated!

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
Can you provide more information about it? e.g core dump trace and environment information.

**Comment by changpe1** [comment]
I'm going to close this issue for now, you may open it if have any questions.
