### ISSUE TITLE
NVMe driver performance degradation

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#1814]
When I run the NVMe perf in the 21.01 LTS I get 1.1M lower IOPS/Core than with the 20.10 release. 

## Expected Behavior
In the SPDK 20.10 release, I get up to 13.8M IOPS/Core when I run NVMe perf for the 512B Rand Read workload

## Current Behavior
In the SPDK 21.01 release, I get 12.7M IOPS/Core when I run NVMe perf for the 512B Rand Read workload

## Possible Solution
Git bisect shows that there are 2 commits that caused performance degradation:
At commit 6b4b2d2913 I see a degradation of 400K IOPS/Core
At commit c078941ca1 I see a degradation of 700K IOPS/Core

## Steps to Reproduce

1. Check out the latest 21.01 LTS
2. Build SPDK
3. Run perf: build/examples/perf -q 128 -o 512 -w randrw -M 100 -t 300 -c 0x2

## Context (Environment including OS version, SPDK version, etc.)
Fedora 30, Linux Kernel 5.7.12, SPDK 21.01 LTS

**Comment by KariukiJ** [comment]
This issue is fixed in the current master. Did a bisect from the current master to v21.01 to find out where the issue was fixed. The commit 4249dc1010e3163c610d5ee8f9780b0059dfedc5 fixed the issue. Looking at that commit its and update to the _nvme_get_host_buffer_sector_size() function that will avoid splitting requests that don't need splitting.

**Comment by changpe1** [comment]
I'm still confused, the commit 4249dc1 only affect one extended LBA format case, but for your test case, I assume that you are using the 512 Bytes format.

**Comment by jimharris** [comment]
@KariukiJ @changpe1 could the two of you sync up on this and provide an update on whether we should close this issue?  Latest post from John indicates this has been fixed now but will wait to close until we get confirmation.

Thanks,

Jim

**Comment by KariukiJ** [comment]
@jimharris I talked to @changpe1 and determined that the next steps are to collect perftop data for the commit above and the one before to help understand the issue. I will also cherry-pick the commit  4249dc1010 and submit it for next LTS patch to fix the issue in the LTS.

**Comment by jimharris** [comment]
Hi @KariukiJ - any update on this issue, or can we close it?

**Comment by KariukiJ** [comment]
@jimharris I talked @changpe1 about this issue. He reviewed the commit 4249dc101 again and determined that the change to replace ns->sectors_per_max_io with an inline function in _nvme_ns_cmd_rw may improve the performance. Therefore, the test result showing patch 4249dc101 improved performance makes sense. The next step is to for me to cherry-pick commit 4249dc101 and submit it to LTS, to fix the issue in the next LTS patch 21.01.2. When do we kick off the release cycle for the next LTS patch 21.01.2?

**Comment by jimharris** [comment]
We don't have a firm date for a 21.01.2 release.  But please push forward on this - we can get a patch on to the v21.01.x branch now, and then it will automatically be included whenever we do the 21.01.2 release.

**Comment by KariukiJ** [comment]
Submitted patch https://review.spdk.io/gerrit/c/spdk/spdk/+/8023 to fix this issue in the LTS.
