### ISSUE TITLE
[vhost-autotest] spdk_test_image.qcow2 does not exist

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1815]
Issue appears on vhost job when attempting to use the spdk_test_image.qcow2.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/37705/archive/vhost-autotest/build.log

## Execution failed at
```
00:01:50.222   16:35:33	# [[ ! -r /root/spdk_test_image.qcow2 ]]
00:01:50.222   16:35:33	# echo ''
00:01:50.222  
00:01:50.223   16:35:33	# echo 'ERROR: VM image '\''/root/spdk_test_image.qcow2'\'' does not exist.'
00:01:50.223  ERROR: VM image '/root/spdk_test_image.qcow2' does not exist.
00:01:50.223   16:35:33	# echo ''
00:01:50.223  
00:01:50.223   16:35:33	# exit 1
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: Not Found

**Comment by karlatec** [comment]
@wawryk please make sure all new test nodes have vhost test image provisioned

**Comment by karlatec** [comment]
@tomzawadzki this is strange however `ERROR: VM image '/root/spdk_test_image.qcow2' does not exist.`
We run tests with `sudo -E` so this should point to /home/sys_sgci/spdk_test_image.qcow2 instead

**Comment by mikeBashStuff** [comment]
That actually depends on how sudo is configured (different distros handle this particular setting differently),  `always_set_home` in particular.

**Comment by karlatec** [comment]
True, but that's the same distribution and I think we re-used an OS image for this host

**Comment by mikeBashStuff** [comment]
@karlatec This is fedora and as far as I recall they always have `always_set_home` set to defaults (i.e. `$HOME` should be set to that of a target user, `root` in this case). And from that I see now, it's there in `/etc/sudoers`.

**Comment by wawryk** [comment]
All new test nodes provisioned.

**Comment by wawryk** [comment]
Last reported failure was almost three weeks ago, closing this issue.
