### ISSUE TITLE
[nvmf_multipath] core dump from bdevperf

### ISSUE THREAD

**Issue by nconnolly1** [spdk/spdk#1817]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/37767/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

00:08:33.410  Connection closed with partial response:
00:08:33.410  
00:08:33.410  
00:08:33.421  test/nvmf/host/multipath.sh: line 62: 35746 Aborted                 (core dumped) $rootdir/test/bdev/bdevperf/bdevperf -z -r $bdevperf_rpc_sock -q 128 -o 4096 -w verify -t 10 -f &> $testdir/try.txt
00:08:33.421    09:33:58	# trap - ERR
00:08:33.421    09:33:58	# print_backtrace
00:08:33.421    09:33:58	# [[ ehxBET =~ e ]]
00:08:33.421    09:33:58	# args=("${BASH_ARGV[@]}")
00:08:33.421    09:33:58	# local args
00:08:33.421    09:33:58	# xtrace_disable
00:08:33.421    09:33:58	# '[' no '!=' yes ']'
00:08:33.421    09:33:58	# PREV_BASH_OPTS=ehxBET
00:08:33.421    09:33:58	# [[ ehxBET == *\x* ]]
00:08:33.421    09:33:58	# XTRACE_DISABLED=yes
00:08:33.421    09:33:58	# set +x
00:08:33.421  ========== Backtrace start: ==========
00:08:33.421  
00:08:33.431  in test/nvmf/host/multipath.sh:62 -> main(["--transport=tcp"])
00:08:33.431       ...
00:08:33.431     57  	
00:08:33.431     58  	sleep 1
00:08:33.431     59  	
00:08:33.431     60  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_THIRD_PORT
00:08:33.431     61  	
00:08:33.431  => 62  	wait $rpc_pid
00:08:33.431     63  	
00:08:33.431     64  	killprocess $bdevperf_pid
00:08:33.431     65  	
00:08:33.431     66  	cat $testdir/try.txt
00:08:33.431     67  	# if this test fails it means we didn't fail over to the second
00:08:33.431       ...
00:08:33.431  
00:08:33.431  ========== Backtrace end ==========

**Comment by changpe1** [comment]
I submit a fix patch https://review.spdk.io/gerrit/c/spdk/spdk/+/6690 for it.
