### ISSUE TITLE
nvme_rdma.c:40:30: fatal error: infiniband/verbs.h: No such file or directory

### ISSUE THREAD

**Issue by ShuaiGeng** [spdk/spdk#182]
root@shuai-MS-7A71:/home/shuai/spdk# make CONFIG_RDMA=y
make[3]: Entering directory '/home/shuai/spdk/dpdk'
== Build lib
== Build lib/librte_compat
== Build lib/librte_eal
== Build lib/librte_eal/common
== Build lib/librte_eal/linuxapp
== Build lib/librte_eal/linuxapp/eal
== Build lib/librte_ring
== Build lib/librte_timer
== Build lib/librte_eventdev
== Build lib/librte_metrics
== Build lib/librte_kvargs
== Build lib/librte_mempool
== Build lib/librte_mbuf
== Build lib/librte_net
== Build lib/librte_ether
== Build lib/librte_vhost
== Build buildtools
== Build buildtools/pmdinfogen
== Build drivers
== Build drivers/bus
== Build drivers/event
== Build drivers/mempool
== Build drivers/mempool/ring
== Build drivers/net
== Build app
== Build app/proc_info
Build complete [x86_64-native-linuxapp-gcc]
make[3]: Leaving directory '/home/shuai/spdk/dpdk'
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[3]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
  CC lib/nvme/nvme_rdma.o
nvme_rdma.c:40:30: fatal error: infiniband/verbs.h: No such file or directory
 #include <infiniband/verbs.h>
                              ^
compilation terminated.
/home/shuai/spdk/mk/spdk.common.mk:171: recipe for target 'nvme_rdma.o' failed
make[2]: *** [nvme_rdma.o] Error 1
/home/shuai/spdk/mk/spdk.subdirs.mk:35: recipe for target 'nvme' failed
make[1]: *** [nvme] Error 2
/home/shuai/spdk/mk/spdk.subdirs.mk:35: recipe for target 'lib' failed
make: *** [lib] Error 2

**Comment by jimharris** [comment]
Hi,

Can you confirm that you have installed the ibverbs and rdmacm packages?  The package names for both Fedora/Centos and Ubuntu/Debian are listed in the README (see “Additional dependencies for NVMe over Fabrics”).

Thanks,

-Jim

**Comment by benlwalker** [comment]
I'm going to close this issue since we haven't heard back and we're fairly confident we've provided the fix. If you are still running into any issues please re-open the issue or file a new one. Thanks!
