### ISSUE TITLE
[UpdateNamespace]Spdk lib in host side cannot update the namespace list after the new namespace added to the existing target.. 

### ISSUE THREAD

**Issue by HellenViolet** [spdk/spdk#1820]
After adding a new namespace to the existing target, spdk lib in the host side cannot get the  spdk_nvme_ns  of the new namespace, so cannot submit io to the new namespace.

## Expected Behavior
Expect that the host could get the spdk_nvme_ns  of the new namespace and could do IO on the new namespace without affecting IO stream on the other namespaces of the target.

## Current Behavior

we are trying to make one target with multiple namespaces, and one disk configured as one namespace. For example, 10 disks in one node, we make one target with 10 namespaces(with nsid 1-10).  And then in host side, app could do IO on these all 10 namespaces(disks) based on SPDK lib.  

If add one disk to the node and configured it as one new namespace(nsid 11) to the existing target, (target contains 11 namespaces now),  however in the host side,  cannot get the spdk_nvme_ns of the new namespace(nsid 11)  without re-connect nvme controller (spdk_nvme_connect), Seems spdk lib didn't update the active namespace list dynamically. So in the host side, app cannot submit io the new namespace because cannot get  spdk_nvme_ns of the new namespace.

## Possible Solution

From our understanding, nvme_ctrlr_update_namespaces seems cannot update the new namespace.  The detail things of our understanding as below.  Just for reference.

The following things seems only be done in the initialization phase of a controller
•	identify the controller and got the result in ctrlr->cdata
•	uint32_t nn = ctrlr->cdata.nn;
•	ctrlr->ns = spdk_zmalloc(nn * sizeof(struct spdk_nvme_ns), 64, NULL, …);
•	ctrlr->num_ns = nn;
Then in the whole lifecycle of the controller, the ctrlr->ns and ctrlr->num_ns would not be changed.
ctrlr->ns points to an array of struct spdk_nvme_ns containing all possible name-spaces (including active/inactive) of the controller.
ctrlr->num_ns is the number of all possible name-spaces (including active/inactive) of the controller.
ctrlr->cdata.nn represent the maximum value of a valid nsid for the controller.

So a controller seem can only handle the dynamically enable/disable of name-spaces in nsid range [1, NN]. But for the new namespace(out range of NN), it seems cannot be updated. 

Following is the name-space updating function:
static void nvme_ctrlr_update_namespaces(struct spdk_nvme_ctrlr *ctrlr)
{
    uint32_t i, nn = ctrlr->cdata.nn;
    struct spdk_nvme_ns_data *nsdata;
    bool ns_is_active;

    for (i = 0; i < nn; i++) {
        struct spdk_nvme_ns    *ns = &ctrlr->ns[i];
        uint32_t        nsid = i + 1;

        nsdata = &ctrlr->nsdata[nsid - 1];
        ns_is_active = spdk_nvme_ctrlr_is_active_ns(ctrlr, nsid);

        //active -> active
        if (nsdata->ncap && ns_is_active) {
            if (nvme_ns_update(ns) != 0) {
                SPDK_ERRLOG("Failed to update active NS %u\n", nsid);
                continue;
            }
        }

        // inactive -> active
        if ((nsdata->ncap == 0) && ns_is_active) {
            if (nvme_ns_construct(ns, nsid, ctrlr) != 0) {
                continue;
            }
        }

        // active -> inactive
        if (nsdata->ncap && !ns_is_active) {
            nvme_ns_destruct(ns);
        }
    }
}

## Steps to Reproduce

1. add the following code in worker_fn, before check_io(ns_ctx);
         for (nsid = spdk_nvme_ctrlr_get_first_active_ns(ctrlr);
		     nsid != 0; nsid = spdk_nvme_ctrlr_get_next_active_ns(ctrlr, nsid)) {
             printf("nsid= %s\n", nsid);
         }
2. run perf with one core(one io worker)
3. during perf run, on target node, configure a new namespace in the target via the following linux command: 
        mkdir /sys/kernel/config/nvmet/subsystems/nqn_test/namespaces/11
        echo /dev/nvme12n1 >/sys/kernel/config/nvmet/subsystems/nqn_test/namespaces/11/device_path
	echo 1 >/sys/kernel/config/nvmet/subsystems/nqn_test/namespaces/11/enable

4. perf finished. But the new namespace didn't be printed.

## Context (Environment including OS version, SPDK version, etc.)

Intel SPDK v20.01.x for NVMe over RDMA. 
Suse 4.12.14-95.54-default

**Comment by changpe1** [comment]
@HellenViolet Actually we discussed similar issue before, NN(number of namespaces) is a fixed value, and when there is AER for namespace change notice to initiator, I don't see the specification that says initiator should call Identify Controller to update the NN first, so I think existing SPDK logic is correct.  Correct me if I missed something in the specification. Also copy @benlwalker @ZiyeYang .

**Comment by yidong0635** [comment]
Adding a test for checking max namespace from the target side and with host configure . https://review.spdk.io/gerrit/c/spdk/spdk/+/6762.

**Comment by yidong0635** [comment]
@ZiyeYang  you ask me to test this from the target side. and It seems this doesn't give any helps.
@HellenViolet do you still need have question to ask from the maintainers ?

**Comment by jimharris** [comment]
Closing this issue.  @HellenViolet, if you still think there is an SPDK issue here, please continue to comment on this thread.
