### ISSUE TITLE
spdk_top: The title of the column is out of sync with the value of the column

### ISSUE THREAD

**Issue by ChengqiangMeng** [spdk/spdk#1829]
## Current Behavior

The title of the column exists, but the corresponding value does not exist.
![spdk_top1](https://user-images.githubusercontent.com/77378851/110590515-d6a17780-81b2-11eb-838e-d024a85d36f0.JPG)
The title of the column does not exists, but the corresponding value exist.
![spdk_top2](https://user-images.githubusercontent.com/77378851/110590959-6fd08e00-81b3-11eb-9aaf-ac1d5c91169b.JPG)

## Steps to Reproduce

1. `./build/bin/nvmf_tgt &`
2. `./build/bin/spdk_top`
3. Press 'c' and a table of Columns will appear. Then select  "Thread name", press Enter to disable it and then press Esc. After that, the phenomenon of Figure 1 will appear.
4. Then press 'c', select "CLOSE" and press Enter. Next, press 'c', select "Thread name" and Enter to enable it. And press Esc, then phenomenon of Figure 2 will appear.

## Context (Environment including OS version, SPDK version, etc.)

OS version: Linux fedora33.localdomain 5.10.20-200.fc33.x86_64
SPDK version: e8cde795605107fcd5a43a76a70021e43168396d

**Comment by yidong0635** [comment]
A fix from  ChengqiangMeng : https://review.spdk.io/gerrit/c/spdk/spdk/+/6893.

**Comment by ChengqiangMeng** [comment]
The patch on this has been merged. Now, close issue.

**Comment by ChengqiangMeng** [comment]
fix patch： https://review.spdk.io/gerrit/c/spdk/spdk/+/6893.
