### ISSUE TITLE
nvme-cli INVALID_FIELD on Intel SSD DC P4600 Series

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1830]
## Expected Behavior
nvme_cli_cuse test should pass

## Current Behavior
test fail, log:
```
 12:38:49       # /usr/local/src/nvme-cli/nvme get-ns-id /dev/nvme0n1
 12:38:49       # /usr/local/src/nvme-cli/nvme id-ns /dev/nvme0n1
 12:38:49       # /usr/local/src/nvme-cli/nvme list-ns /dev/nvme0n1
 12:38:49       # /usr/local/src/nvme-cli/nvme id-ctrl /dev/nvme0
 12:38:49       # /usr/local/src/nvme-cli/nvme list-ctrl /dev/nvme0
NVMe status: INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(0x4002)
```

## Steps to Reproduce

1. run nvme-cli commands on P4600 disks.

## Context (Environment including OS version, SPDK version, etc.)

OS: Fedora 33 
Kernel: 5.10.17-100.fc32.x86_64
nvme-cli: nvme version 1.10.1
Disk FW: QDV101D1

**Comment by tomzawadzki** [comment]
The above suggests this is issue between the drive behavior and nvme-cli, not strictly related to SPDK.

I imagine this could be worked-around in tests, but is this disk to be included in the CI or its just something observed that you wanted to report ?

**Comment by jimharris** [comment]
Can you run same NVMe cli test but with the SSD attached to the kernel NVMe driver?

**Comment by changpe1** [comment]
I used the nvme-cli to test it with P4500, the same result showed below. I used nvme-1.6.128.ge145.

nvme list-ctrl /dev/nvme1
NVMe Status:INVALID_FIELD: A reserved coded value or an unsupported value in a defined field(4002) cntid:0

**Comment by changpe1** [comment]
[Bug Scrub] let's close this issue for now, it's not related with SPDK.
