### ISSUE TITLE
spdk_subsystem_fini() won't complete with blob opened

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#1831]
I observed that completion callback of spdk_subsystem_fini() won't be called when there is any opened blobs.

## Expected Behavior

The spdk_subsystem_fini() should run to completion without problem.

## Current Behavior

Immediately after the spdk_subsystem_fini() call, a spdk_thread_poll() is called in a loop to test if the completion callback is done, but seems the completion callback for the spdk_subsystem_fini() is never called.

## Steps to Reproduce

1. Initialize subsystem by spdk_subsystem_init(), bdev subsystem is registered;
2. Create a blobstore, create a blob on it;
3. open the blob;
4. Unload blobstore without closing blob, blobstore unloading failed with EBUSY as expected;
5. Finalize subsystems by spdk_subsystem_fini();
6. Call spdk_thread_poll() in a loop to check if spdk_subsystem_fini() is done, seems the completion callback of spdk_subsystem_fini() is never called;

## Context (Environment including OS version, SPDK version, etc.)

SPDK v20.01.2
CentOS Linux release 7.9.2009

**Comment by yidong0635** [comment]
@NiuYawei  Why not to close this blob?  bdev should be closed that our bdev subsystem then can be  finished.

**Comment by NiuYawei** [comment]
The blob won't be closed in some error cases or on force shutdown.

We'll improve our code to close blob in the force shutdown case, but I just don't see why opened blob could prevent the bdev subsystem from finalizing? Shouldn't it return an EBUSY error (like what blobstore unload does) or just log a warning message?

**Comment by optimistyzy** [comment]
I see spdk_subsystem_fini in the master branch, it is an async function. Only the callback function passed in the spdk_subsystem_fini is called, then means that the spdk_subsystem_fini is really finished.

**Comment by NiuYawei** [comment]
> I see spdk_subsystem_fini in the master branch, it is an async function. Only the callback function passed in the spdk_subsystem_fini is called, then means that the spdk_subsystem_fini is really finished.

Right, spdk_subsystem_fini() is async, my observation is that completion callback will never be called when bdev is held by some open blobs.

We are currently using a workaround to set a timeout for the completion polling, so that application won't be blocked on polling spdk_subsystem_fini() completion even when blob is still opened. Though some SPDK errors are observed on console in such unclean shutdown case:

`
ERROR: daos_engine:0 thread.c: 200:spdk_thread_lib_fini: *ERROR*: io_device memcpy_engine not unregistered
ERROR: daos_engine:0 thread.c: 200:spdk_thread_lib_fini: *ERROR*: io_device copy_module not unregistered
thread.c: 200:spdk_thread_lib_fini: *ERROR*: io_device bdev_mgr not unregistered
thread.c: 200:spdk_thread_lib_fini: *ERROR*: io_device Nvme__0 not unregistered
thread.c: 200:spdk_thread_lib_fini: *ERROR*: io_device bdev_Nvme__0n1 not unregistered
thread.c: 200:spdk_thread_lib_fini: *ERROR*: io_device aio_module not unregistered
thread.c: 200:spdk_thread_lib_fini: *ERROR*: io_device blobstore not unregistered
ERROR: daos_engine:0 Device 0000:8a:00.0 is still attached at shutdown!
`

Given that everything in memory will be cleared eventually after app exits, I suppose those errors won't impede next app start, is it correct?

I'm just wondering if it's better make the spdk_subsystem_fini() completion callback returning an EBUSY error instead of indefinitely waiting for bdev being released?

**Comment by jimharris** [comment]
Hi @NiuYawei,

I don't see any reason yet why we shouldn't be able to make this work.  We already have code in bdev_finish_unregister_bdevs_iter (which is in the spdk_subsystem_fini code path) that tries to handle the case where bdevs are not appropriately cleaned up during application shutdown.

Could you instrument bdev_finish_unregister_bdevs_iter?  I don't have a test currently to duplicate your setup.

We keep calling this function over and over until there are no more registered bdevs.  First we go through the unclaimed bdevs.  In your case, I think the underlying bdev for the blobstore is claimed, so I don't think this first loop is interesting.

But then if there are still bdevs, but all of them are still claimed, it loops through the claimed bdevs.  it should print out a WARNLOG and unregister one of those bdevs.  Do you see that WARNLOG?  This should result in the bdev getting removed, calling bdev_finish_unregister_bdevs_iter again, and kicking us out into the bdev_module_finish_iter code path.

Let's also instrument bdev_module_finish_iter and bdev_mgr_unregister_cb to see if those two functions are getting executed.

This instrumentation should help us know where to look next.

-Jim

**Comment by NiuYawei** [comment]
Thanks @jimharris , I didn't see the WARNLOG.

I checked bdev_finish_unregister_bdev_iter() code a bit, it looks to me that bdev_finish_unregister_bdev_iter() won't be called again if the bdev is still opened by blobstore (the blobstore didn't unload successfully since there is still open blob).

bdev_finish_unregister_bdev_iter() -> spdk_bdev_unregister() -> bdev_unregister_unsafe() -> spdk_thread_send_msg(_remove_notify);

And _remove_notify() will call the remove event callback function (provided by user) and relies on the callback to close the bdev eventually. So if the remove event callback failed to close the bdev, seems bdev_module_finish_iter() won't be called again. Is my reading correct?

To be clear, if the design is to stop proceeding on subsystem finalizing on busy bdev, it totally makes sense to me. I just didn't realize it before.

**Comment by jimharris** [comment]
Hi @NiuYawei,

How do you want to proceed on this issue?

-Jim

**Comment by jimharris** [comment]
I accidentally ran into this problem today while testing a blobcli patch series from Mike Gerdts.

I created an lvstore on an NVMe SSD, then later created blobs (*not* lvols!) using blobcli.

Later when attaching that controller again to the SPDK target, the lvolstore failed to load since it found blobs with no names (the ones created by blobcli).  The app wouldn't exit when hitting Ctrl-C.

The problem was that the lvol library was prematurely stopping iteration through the blobs when building its lvol list.  You cannot stop iteration in the middle and try to unload the blobstore - because the iterator callback is called with the blob open (and will close it when the iterator returns).  Since the blobstore doesn't get unloaded, the bdev descriptor doesn't get closed, and the bdev subsystem won't shut down cleanly.

https://review.spdk.io/gerrit/c/spdk/spdk/+/11352 fixes the lvol issue.

I'm going to close this issue though, I think we have consensus here that the user just needs to be careful to close all blobs before trying to unload the blobstore.

**Comment by NiuYawei** [comment]
@jimharris Yes, agreed. Let's close this one. Thanks a lot.
