### ISSUE TITLE
[vhost-autotest] qemu image not found

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#1833]
00:02:49.152  ************************************
00:02:49.152  START TEST vhost
00:02:49.152  ************************************
00:02:49.152   16:34:02	# xtrace_enable
00:02:49.153   16:34:02	# ./test/vhost/vhost.sh
00:02:49.223  * Purging old temporary test storage (/tmp/spdk.H3Mp05)
00:02:49.265  * Looking for test storage...
00:02:49.272  * Found test storage at /var/jenkins/workspace/vhost-autotest/spdk/test/vhost
00:02:49.272    16:34:02	# xtrace_enable
00:02:49.273   16:34:02	# source /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh
00:02:49.273    16:34:02	# : false
00:02:49.273    16:34:02	# : /root/vhost_test
00:02:49.273    16:34:02	# : qemu-system-x86_64
00:02:49.274    16:34:02	# : qemu-img
00:02:49.274     16:34:02	# readlink -f /var/jenkins/workspace/vhost-autotest/spdk/..
00:02:49.276    16:34:02	# TEST_DIR=/var/jenkins/workspace/vhost-autotest
00:02:49.276    16:34:02	# VM_DIR=/root/vhost_test/vms
00:02:49.277    16:34:02	# TARGET_DIR=/root/vhost_test/vhost
00:02:49.277    16:34:02	# VM_PASSWORD=root
00:02:49.277    16:34:02	# VM_IMAGE=/root/spdk_test_image.qcow2
00:02:49.277    16:34:02	# hash qemu-img qemu-system-x86_64
00:02:49.277  /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh: line 13: hash: qemu-img: not found
00:02:49.278  /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh: line 13: hash: qemu-system-x86_64: not found
00:02:49.278    16:34:02	# error 'QEMU is not installed on this system. Unable to run vhost tests.'
00:02:49.278  /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh: line 14: error: command not found
00:02:49.278     16:34:02	# trap - ERR
00:02:49.278     16:34:02	# print_backtrace
00:02:49.279     16:34:02	# [[ ehxBET =~ e ]]
00:02:49.279     16:34:02	# args=("${BASH_ARGV[@]}")
00:02:49.279     16:34:02	# local args
00:02:49.279     16:34:02	# xtrace_disable
00:02:49.279     16:34:02	# '[' '' '!=' yes ']'
00:02:49.279     16:34:02	# PREV_BASH_OPTS=ehxBET
00:02:49.280     16:34:02	# [[ ehxBET == *\x* ]]
00:02:49.280     16:34:02	# XTRACE_DISABLED=yes
00:02:49.280     16:34:02	# set +x
00:02:49.280  ========== Backtrace start: ==========

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_38848.html

## Execution failed at

00:02:49.280  ========== Backtrace start: ==========
00:02:49.280  
00:02:49.289  in /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh:14 -> source(["/var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh"])
00:02:49.289       ...
00:02:49.289     9   	VM_PASSWORD="root"
00:02:49.289     10  	
00:02:49.289     11  	VM_IMAGE=${VM_IMAGE:-"$HOME/spdk_test_image.qcow2"}
00:02:49.289     12  	
00:02:49.289     13  	if ! hash $QEMU_IMG_BIN $QEMU_BIN; then
00:02:49.289  => 14  		error 'QEMU is not installed on this system. Unable to run vhost tests.'
00:02:49.289     15  		exit 1
00:02:49.289     16  	fi
00:02:49.289     17  	
00:02:49.289     18  	mkdir -p $VHOST_DIR
00:02:49.289     19  	mkdir -p $VM_DIR
00:02:49.289       ...
00:02:49.295  in ./test/vhost/vhost.sh:5 -> main([])
00:02:49.295       ...
00:02:49.295     1   	#!/usr/bin/env bash
00:02:49.295     2   	testdir=$(readlink -f $(dirname $0))
00:02:49.295     3   	rootdir=$(readlink -f $testdir/../..)
00:02:49.295     4   	source $rootdir/test/common/autotest_common.sh
00:02:49.295  => 5   	source $rootdir/test/vhost/common.sh
00:02:49.295     6   	
00:02:49.295     7   	echo "Running SPDK vhost fio autotest..."
00:02:49.295     8   	if [[ $(uname -s) != Linux ]]; then
00:02:49.295     9   		echo ""
00:02:49.295     10  		echo "INFO: Vhost tests are only for Linux machine."
00:02:49.296       ...
00:02:49.296  
00:02:49.296  ========== Backtrace end ==========

**Comment by karlatec** [comment]
@wawryk 
Qemu not installed on test node:
```
00:02:49.277  /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh: line 13: hash: qemu-img: not found
00:02:49.278  /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh: line 13: hash: qemu-system-x86_64: not found
00:02:49.278    16:34:02	# error 'QEMU is not installed on this system. Unable to run vhost tests.'
00:02:49.278  /var/jenkins/workspace/vhost-autotest/spdk/test/vhost/common.sh: line 14: error: command not found
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_38848.html

**Comment by wawryk** [comment]
Missing packages installed.
