### ISSUE TITLE
[clang-vg-autotest] setup.sh fails to allocate proper amount of hugepages

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1835]
https://ci.spdk.io/results/autotest-per-patch/builds/38840/archive/clang-vg-autotest/build.log

Seems to be happening from time to time exclusively on SM9.

**Comment by changpe1** [comment]
00:05:53.883  ## ERROR: requested 4096 hugepages but 3402 could be allocated on node0.
00:05:53.883  ## Memory might be heavily fragmented. Please try flushing the system cache, or reboot the machine.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_40469.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_40476.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_40480.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_40503.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40887.html

**Comment by karlatec** [comment]
Last entry does not match the issue, so it's been over 3 weeks since last report.
@wawryk could you add a comment what was done on infrastructure side, so we can close the issue?

**Comment by tomzawadzki** [comment]
Closing since it has been over a month with no occurrence.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_49512.html
