### ISSUE TITLE
Failed to boot a VM guest Only in CentOS 7.x with a vhost-user-blk-pci disk

### ISSUE THREAD

**Issue by zxx1985** [spdk/spdk#1836]
## Expected Behavior

I have been troubled for three days = =  

CentOS 8.3 and Fedora 27 strart Normally, but CentOS 7 start failed

However [this issue](https://github.com/spdk/spdk/issues/1205),   can't solve my problem.

## Current Behavior

![image](https://user-images.githubusercontent.com/58806546/111114097-bcdea680-859d-11eb-90d8-95d05a2e9db9.png)

![image](https://user-images.githubusercontent.com/58806546/111114167-d253d080-859d-11eb-9cd7-ef85f6eff8fc.png)

![image](https://user-images.githubusercontent.com/58806546/111114192-d97ade80-859d-11eb-92a4-d88e545819a9.png)

## Steps to Reproduce

1. Start SPDK, Like this:

```bash
cd spdk-20.01.2/
HUGEMEM=2048 ./scripts/setup.sh
./app/vhost/vhost -S /var/tmp -s 1024 -m 0x3 &
./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:03:00.0
./scripts/rpc.py vhost_create_blk_controller --cpumask 0x2 vhost.0 Nvme0n1
```

2. Boot a CentOS 7.5 VM guest use Qemu (Version 5.2.1)

```bash
qemu-system-x86_64 --enable-kvm -cpu host -smp 2 -m 1G -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 -drive file=/var/lib/libvirt/images/centos7.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=spdk_vhost_blk0,path=/var/tmp/vhost.0 -device vhost-user-blk-pci,chardev=spdk_vhost_blk0 --vnc 0.0.0.0:0 -net user,hostfwd=tcp::10021-:22 -net nic
```

## Context (Environment including OS version, SPDK version, etc.)

- Host OS: CentOS 7.7 
- SPDK: 20.01.2 
- VM Guest: CentOS 7.5 (CentOS 7.7 also like this)

**Comment by changpe1** [comment]
@zxx1985 You may start QEMU with a telnet monitor, then add vhost-blk device via QMP:
device_add driver=vhost-user-blk-pci,chardev=spdk_vhost_blk0
of course you should remove "-device vhost-user-blk-pci,chardev=spdk_vhost_blk0" in your QEMU startup command line.

BTW, you are creating a vhost-blk device, but why the logs here didn't show anything about vhost-blk, it's SCSI boot drive.

**Comment by yidong0635** [comment]
I just test this today, 
`./qemu-system-x86_64  -enable-kvm -m 8G -smp 4 -drive file=/home/fedora.qcow2,if=none,id=disk,format=qcow2 -device ide-hd,drive=disk,bootindex=0  -object memory-backend-file,id=mem,size=8G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem -mem-prealloc  _-chardev socket,id=char0,path=/home/spdk/vhost.0 -device vhost-user-blk-pci,id=block0,chardev=char0_  -monitor telnet::1111,server,nowait -net user,hostfwd=tcp::10020-:22 -net nic -vnc 0.0.0.0:2`

also curious about above log with changpeng, seem using  :
 `-chardev socket,id=char0,path=/home/spdk/vhost.0 -device vhost-user-scsi-pci,chardev=char0`

**Comment by zxx1985** [comment]
> I just test this today, it works,
> `./qemu-system-x86_64 -enable-kvm -m 8G -smp 4 -drive file=/home/fedora.qcow2,if=none,id=disk,format=qcow2 -device ide-hd,drive=disk,bootindex=0 -object memory-backend-file,id=mem,size=8G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem -mem-prealloc -chardev socket,id=char0,path=/home/spdk/vhost.0 -device vhost-user-blk-pci,id=block0,chardev=char0 -monitor telnet::1111,server,nowait -net user,hostfwd=tcp::10020-:22 -net nic -vnc 0.0.0.0:2`
> 
> also curious about above log with changpeng, seems using :
> `-chardev socket,id=char0,path=/home/spdk/vhost.0 -device vhost-user-scsi-pci,chardev=char0`



yes 👍 , fedora use command like :
`-chardev socket,id=char0,path=/home/spdk/vhost.0 -device vhost-user-blk-pci,id=block0,chardev=char0` 
can boot normally, 
but  a error occurs when  `vhost-user-scsi-pci`  be used to CentOS 7.x 😖

![emergency](https://user-images.githubusercontent.com/58806546/111128275-ab9e9580-85af-11eb-9f18-8a775849541a.png)


> @zxx1985 You may start QEMU with a telnet monitor, then add vhost-blk device via QMP:
> device_add driver=vhost-user-blk-pci,chardev=spdk_vhost_blk0
> of course you should remove "-device vhost-user-blk-pci,chardev=spdk_vhost_blk0" in your QEMU startup command line.
> 
> BTW, you are creating a vhost-blk device, but why the logs here didn't show anything about vhost-blk, it's SCSI boot drive.

 The VM guest can boot normally after removing `-device vhost-user-blk-pci,chardev=spdk_vhost_blk0` , while  nvme disk (like /dev/vda ) is not exist the VM guest, only a system disk

![image](https://user-images.githubusercontent.com/58806546/111128476-e6083280-85af-11eb-84fa-01e6e199e795.png)

**Comment by yidong0635** [comment]
@zxx1985  before using “vhost-user-scsi-pci “  to start  a QEMU， Do you use these steps ?
./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:03:00.0
./scripts/rpc.py vhost_create_scsi_controller --cpumask 0x1 vhost.0
./scripts/rpc.py vhost_scsi_controller_add_target vhost.0 0 Nvme0n1

**Comment by zxx1985** [comment]
@yidong0635 Of course I did it. While the miracle didn't happen in the end .

**Comment by zxx1985** [comment]
The problem is driving me crazy. Maybe I'm a muggle, not a wizard 😂

**Comment by yidong0635** [comment]
@zxx1985 please follow changpeng's suggestion :
you may start QEMU with a telnet monitor, then add vhost-blk device via QMP:
device_add driver=vhost-user-blk-pci,chardev=spdk_vhost_blk0
using commands to add a device other than initial starting.

**Comment by zxx1985** [comment]
@yidong0635 Thank you for your advice

**Comment by zxx1985** [comment]
@changpe1 @yidong0635 
thank you for your advice. 
 I have found a solution to the problem that modify bdev_nvme.c to avoid the systemd-udevd bug.
