### ISSUE TITLE
how to export file as block device from target to initiator 

### ISSUE THREAD

**Issue by onkar6699** [spdk/spdk#1838]
Can Anybody tell me how to export file as block device from target to initiator

**Comment by yidong0635** [comment]
Do you mean save the target bdev config  and use it as initiator config ?  Fox example:
jsonf.json
```
 {
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_set_options",
          "params": {
            "action_on_timeout": "none",
            "timeout_us": 0,
            "retry_count": 4,
            "arbitration_burst": 0,
            "low_priority_weight": 0,
            "medium_priority_weight": 0,
            "high_priority_weight": 0,
            "nvme_adminq_poll_period_us": 10000,
            "keep_alive_timeout_ms": 10000,
            "nvme_ioq_poll_period_us": 0,
            "io_queue_requests": 0,
            "delay_cmd_submit": true
          }
        },
        {
          "params": {
            "name": "Nvme0",
            "trtype": "rdma",
            "traddr": "x.x.x.x",
            "adrfam": "ipv4",
            "trsvcid": "4420",
            "subnqn": "nqn.2016-06.io.spdk:cnode0",
            "hostnqn": "nqn.2016-06.io.spdk:host0"
          },
          "method": "bdev_nvme_attach_controller"
        }
      ]
    }
  ]
}
```
test/bdev/bdevperf/bdevperf --json jsonf.json  -q 128 -o 4096 -w verify -t 1
indeed json file can get from target using` gen_nvmf_target_json` or rpc mathod `save_config`  from target to cut out `"subsystem": "bdev"` which similar above.

**Comment by changpe1** [comment]
@onkar6699 we have slack chat channel spdk-team.slack.com for questions, you may ask questions there, it's really unclear to me for your question here, please clarify your question again.

**Comment by onkar6699** [comment]
How to join slack channel I think need invitation

**Comment by Aniruddha8699** [comment]
@changpe1 can you please invite me on that channel as well? I have a few doubts that need to be solved.

**Comment by changpe1** [comment]
> @changpe1 can you please invite me on that channel as well? I have a few doubts that need to be solved.

sure, can you provide your email?

**Comment by Aniruddha8699** [comment]
@changpe1 I joined the channel just now. Still thank you!

**Comment by onkar6699** [comment]
@changpe1 thanks i have joined slack channel
