### ISSUE TITLE
unsuccessful probe after detach

### ISSUE THREAD

**Issue by menacingChicken** [spdk/spdk#1842]
A spdk_nvme_probe does not show a device which was previously spdk_nvme_detach'd. 

Steps to repro:
1. Perform spdk_nvme_probe. Do not attach to anything.
2. Perform spdk_nvme_connect using one of the found spdk_nvme_transport_id pointers from step 1.
3. Immediately perform spdk_nvme_detach.
4. Perform spdk_nvme_probe again. Note that the previously detached device does not appear.

If you follow up with one or more spdk_nvme_probe calls, the device will continue to be absent; however, if enough time goes by (seemingly ~1s) and at least ONE probe was done, then the device eventually reappears.

My expectation is that a probe immediately after a successful detach will show the previously detached device. Please let me know if my expectation is wrong.

**Comment by menacingChicken** [comment]
This works fine... 

`
auto ctrlr = spdk_nvme_connect(&trid, NULL, 0);
spdk_nvme_detach(ctrlr);
ctrlr = spdk_nvme_connect(&trid, NULL, 0);
`

So if I already know the transport id, I could just force a single connection no problem. It's just the probe that doesn't see it.

**Comment by jimharris** [comment]
This is actually a known issue.  You can find a very good explanation on https://github.com/spdk/spdk/issues/1574.

I'm going to close this issue here as a duplicate.  Feel free to ask additional questions on #1574.

**Comment by jimharris** [comment]
Note that #1574 is focused on the underlying spdk_pci_* calls, but it applies here since that is what spdk_nvme_connect and spdk_nvme_detach are calling.

**Comment by menacingChicken** [comment]
Sounds good, I'll go take a look through the other ticket. Thanks!
