### ISSUE TITLE
how to export file as storage device  using spdk(NVMf target/iSCSI target)

### ISSUE THREAD

**Issue by onkar6699** [spdk/spdk#1843]
i created file using **xfs_mkfile 1G testfile**
then i created aio block device over that file **scripts/rpc.py bdev_aio_create /test/testfile file 512** 
i able to export file as storage device using ISCSI Target or NVMf target
But i want to export file directly without creating block device over file 
how i can do it?

**Comment by changpe1** [comment]
@onkar6699 iSCSI and NVMf target are the right way, or you may try with NBD client/server.

**Comment by onkar6699** [comment]
@changpe1 ok I'll but is there any way to directly exporting file without using block device using nvmf or iscsi

**Comment by changpe1** [comment]
You can use one file in the host server to VM, inside the VM, the file exported from host is a block device.

**Comment by onkar6699** [comment]
Ok thanks
Just one doubt while exporting file as storage device always need to create block device over it right?

**Comment by changpe1** [comment]
> Ok thanks
> Just one doubt while exporting file as storage device always need to create block device over it right?

Correct.
