### ISSUE TITLE
bdevperf support zipf workload as fio

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#1844]
## Expected Behavior
it will be great that bdevperf can support zipf workload as fio, I know we can use fio_plugin, but it will be still great that if bdevperf can do it, it is easy for us to debug and SPDK under different workload.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomzawadzki** [comment]
Bug scrub: @gaowayne is this something you are interested in contributing ?

**Comment by jimharris** [comment]
If someone does pick this up, please develop the zipf distribution functionality such that it could also be integrated into nvme perf.

**Comment by gaowayne** [comment]
@tomzawadzki buddy, my this half year will be very busy on other project. currently we test our workload with fio plugin. if anyone in SPDK team who like work on it? this is not very high priority blocking feature for our project, but it will be very nice to have zipf in bdevperf,

**Comment by jimharris** [comment]
I've added APIs to the spdk util library to do a zipf distribution.

 https://review.spdk.io/gerrit/c/spdk/spdk/+/7780 

It is not integrated into bdevperf or nvme/perf yet, but there is an example app here that shows how the API works and uses the spdk_histogram_data APIs to illustrate the distribution properties of different theta values.

**Comment by jimharris** [comment]
Patch series has been extended with support in bdevperf.

https://review.spdk.io/gerrit/c/spdk/spdk/+/7790

**Comment by jimharris** [comment]
Patches merged.
