### ISSUE TITLE
how can we automate exporting block device using iscsi ?

### ISSUE THREAD

**Issue by onkar6699** [spdk/spdk#1845]
hey i want to  automate the procedure of an exporting block device using iscsi?
which language is used for that?

**Comment by onkar6699** [comment]
@changpe1 can you give answer of it

**Comment by changpe1** [comment]
@onkar6699 You can refer test/iscsi_tgt/fio/fio.sh as an example, SPDK uses Python and shell scripts to do it.

BTW, please don't open github issues for questions, we use it to track bugs here, not questions. thanks.
