### ISSUE TITLE
SPDK compilation error with fio-3.19 when using clang as compiler

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1848]
## Current Behavior

SPDK compilation fails when using --with-fio option along with fio-3.19.
Issue reported, because our provisioning scripts for tests (`/test/common/config/vm_setup.sh`) use this specific version.

## Possible Solution

a) Upgrade fio to latest version 3.26 (which on the other hand has different compilation issue - `-Wsign-compare`)
**NOTE**:  Upgrading fio in `/test/common/config/vm_setup.sh` will cause problems with installing it on Centos 7 (and possibly 8) system, or any other pretty old LTS distros which use old tool versions. 
Alternatively we could try doing if-else in vm_setup.sh script and select fio version based on OS or GCC version. It's an option but I'd not recommend it as it increases the maintenance burden.

b) Set -Wno-error for building fio with clang compiler: https://review.spdk.io/gerrit/c/spdk/spdk/+/6991 (or just disable error on warning for specific error)

## Steps to Reproduce

1. Clone & build fio 3.19
```
git clone https://github.com/axboe/fio.git
git checkout fio-3.19
make -j50
```
2  ./configure --with-fio=/usr/src/fio --enable-werror
3.  CXX=/usr/bin/clang++ CC=/usr/bin/clang  make -j50
```
/usr/src/fio/arch/../lib/rand.h:109:25: error: implicit conversion from 'unsigned long long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-const-int-float-conversion]
                return (val + 1.0) / (FRAND64_MAX + 1.0);
                                      ^~~~~~~~~~~ ~
/usr/src/fio/arch/../lib/rand.h:9:22: note: expanded from macro 'FRAND64_MAX'
#define FRAND64_MAX     (-1ULL)
                         ^~~~~
/usr/src/fio/arch/../lib/rand.h:136:41: error: implicit conversion from 'unsigned long long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-const-int-float-conversion]
        return (uint64_t) ((double)end * (r / (FRAND64_MAX + 1.0)));
                                               ^~~~~~~~~~~ ~
/usr/src/fio/arch/../lib/rand.h:9:22: note: expanded from macro 'FRAND64_MAX'
#define FRAND64_MAX     (-1ULL)
                         ^~~~~
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK `b8db1af4e` `thread: criticalmsg also indicates valid event`
clang version 11.0.0 (Fedora 11.0.0-2.fc33)
Fedora 33 5.10.23-200.fc33.x86_64
fio 3.19

**Comment by karlatec** [comment]
Might be a good idea to cherry pick to 21.01.x if this solution is used: https://review.spdk.io/gerrit/c/spdk/spdk/+/6991

**Comment by jimharris** [comment]
Patch merged.
