### ISSUE TITLE
NVMF RDMA with multiSGL payload and NVME disk

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#1853]
Recently we met an issue with multiSGL payload in NVMF target and following IO submitted to NVME disk with PRP payload
Setup:
1. Local host, x86 initiator with Smart NIC, the Smart NIC exposes NVME PCI subfunction, so the host writes/reads data using NVME driver 
2. Remote host, x86 macine running SPDK NVMF RDMA target NVME disks.

Scenario:
1. Smart NIC handles NVME commands from the initiator and forwards requests to the remote target, payload is described by PRP. 4KiB payload is described by PRP1 and PRP2 (not contig). According to the spec, PRP1 end address must be aligned to controller page size, start address is not necessary aligned. Addresses of PRP1 and PRP2 received on the Smart NIC are SPEC compatible.
2. Application of the Smart NIC uses spdk bdev API to send data to remote target. In particular it uses spdk_bdev_writev with 2 iov entries (PRP1 and PRP2). Let's say that `iov[0].iov_len == 2000` and `iov[1].iov_len == 2096`. SPDK NVME RDMA driver prepares a capsule with 2 SGL entries (multi SGL).
3. When SPDK target on the remote host receives such a capsule, it allocates 2 transport buffers (each transport buffer is 4KiB aligned) and for Read operation these buffers are passed to generic bdev -> bdev_nvme -> nvme. 
4. Here we have SGL payload and NVME controller that doesn't support SGL. The problem is that now `iov[0]` start address is aligned to controller's page size while end address is not aligned. That is due to NVMF transport allocated a buffer and buffer's start address is 4KiB aligned. This violates NVME spec and SPDK driver tries to split such a request  
5. Split logic (`_nvme_ns_cmd_split_request_prp`) tries to create a child request from `iov[0]` but it's length is not multiple of block size and the request is failed. 

My idea of how we can fix such a problem is to modify NVMF RDMA target (step `#3`) so that it tries to merge SGL entries into 1 buffer. In this case we'll have a contig buffer in NVMF target and the problem will be solved.
I would be happy to hear other opinions on the described problem before starting implementation.

P.S. during checking of this problem I found that when NVME driver fails such a request, the return code from NVME function is -ENOMEM which seems to be incorrect. Due to this error code, generic bdev layer puts the request into `nomem_io` queue and tries to resubmit it later, after X requests. But in my case there were no other requests and this problematic request remained in the queue forever. I pushed a patch to address this problem https://review.spdk.io/gerrit/c/spdk/spdk/+/7036

**Comment by jimharris** [comment]
Maybe in nvmf_request_set_buffer(), for the first iov, pick the iov_base that would *end* on a 4KiB alignment?  This should fix your case above.

Merging the SGL entries might work, but my initial thought is it could get rather complicated, especially if you expand the case above into a 128KiB I/O with a PRP1 that doesn't have a 4KiB start aligned address.

**Comment by jimharris** [comment]
By the way, good catch on the -ENOMEM handling when the SGL violates PRP - I posted a comment on the patch 7036.

**Comment by benlwalker** [comment]
The behavior you outlined in #3 is not how the target works. The target allocates its buffers only based on the total length of the command. In this case, it will allocate a single 4KiB buffer and then perform two RDMA reads to fetch data into it.

**Comment by AlekseyMarchuk** [comment]
In the case of multi SGL target allocates a separate buffer for every SGL descriptor. That is done in `nvmf_rdma_request_fill_iovs_multi_sgl` function, this function prepares `lengths` array and passed in to `spdk_nvmf_request_get_buffers_multi`. As a result in this particular case we'll have 2 transport buffers

**Comment by benlwalker** [comment]
This is the bug then - the memory allocations on the target side should only be based on the total length, not the way the host side has carved up the data into segments.

**Comment by AlekseyMarchuk** [comment]
Agree, I add bug label to this issue. Working on the fix

**Comment by AlekseyMarchuk** [comment]
This patch addresses the problem: https://review.spdk.io/gerrit/c/spdk/spdk/+/7259

**Comment by AlekseyMarchuk** [comment]
The patch is merged, closing this issue
