### ISSUE TITLE
is a Dell R610 usable to try spdk development ? Or should I go for R620 / R630 / R710 ?

### ISSUE THREAD

**Issue by ionuthristodorescu** [spdk/spdk#186]
... the reason I'm asking is because there's a lot of used Dell machines going for cheap on the web. Alternatively, could somebody let me know about a cheap/cheapest setup I could try ? Thank you.

**Comment by jimharris** [comment]
Hi,

If you are just trying SPDK development, you don’t really need a physical system at all.  Both QEMU and VirtualBox support emulated NVMe devices.  The SoftRoCE support in Linux kernel 4.12 also enables NVMe-oF testing in loopback mode.  The SPDK repository has Vagrant instructions and scripts for setting up a VM for SPDK development as well to help get you kickstarted.

-Jim

**Comment by ionuthristodorescu** [comment]
Cool, thank you.
