### ISSUE TITLE
iscsi_tgt/rbd/rbd.sh test fails due to loop module not loaded

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1861]
## Current Behavior

iscsi_tgt_rbd test fails due to loop module not loaded. This is caused by scripts/ceph/start.sh script to be more specific.

```
 10:31:39       # ip netns exec spdk_iscsi_ns /home/vagrant/spdk_repo/spdk/scripts/ceph/start.sh 10.0.0.1
+ set -e
+++ dirname /home/vagrant/spdk_repo/spdk/scripts/ceph/start.sh
++ readlink -f /home/vagrant/spdk_repo/spdk/scripts/ceph
+ script_dir=/home/vagrant/spdk_repo/spdk/scripts/ceph
+ base_dir=/var/tmp/ceph
+ mon_ip=10.0.0.1
+ mon_dir=/var/tmp/ceph/mon.a
+ pid_dir=/var/tmp/ceph/pid
+ ceph_conf=/var/tmp/ceph/ceph.conf
+ mnt_dir=/var/tmp/ceph/mnt
+ image=/var/tmp/ceph_raw.img
+ dev=/dev/loop200
+ umount /dev/loop200p2
umount: /dev/loop200p2: no mount point specified.
+ true
+ losetup -d /dev/loop200
losetup: /dev/loop200: failed to use device: No such device
+ true
+ '[' -d /var/tmp/ceph ']'
+ mkdir /var/tmp/ceph
+ cp /home/vagrant/spdk_repo/spdk/scripts/ceph/ceph.conf /var/tmp/ceph/ceph.conf
+ '[' '!' -e /var/tmp/ceph_raw.img ']'
+ fallocate -l 4G /var/tmp/ceph_raw.img
+ mknod /dev/loop200 b 7 200
+ losetup /dev/loop200 /var/tmp/ceph_raw.img
losetup: /var/tmp/ceph_raw.img: failed to set up loop device: No such device or address
+ true
+ PARTED='parted -s'
+ SGDISK=sgdisk
+ echo 'Partitioning /dev/loop200'
Partitioning /dev/loop200
+ parted -s /dev/loop200 mktable gpt
```

Losetup fails due to missing loop module. This was not detected before in CI because we still use a bit older version (2.34) than the one which caused the issue (2.36.1). Not sure if it's a bug or a feature on  losetup side, but we should still load the needed module if we're going to use it.

## Possible Solution
https://review.spdk.io/gerrit/c/spdk/spdk/+/7086 scripts/ceph

## Context (Environment including OS version, SPDK version, etc.)

Fedora 33 5.11.7-100.fc32.x86_64
losetup version 2.36.1

**Comment by tomzawadzki** [comment]
@karlatec patch https://review.spdk.io/gerrit/c/spdk/spdk/+/7086 has been merged. Does this resolve this issue ?

**Comment by jimharris** [comment]
Karol reported to me offline that this issue is fixed.  Thanks @karlatec!
