### ISSUE TITLE
Question about spdk_tgt

### ISSUE THREAD

**Issue by jianlenovo** [spdk/spdk#1862]
I am trying to build spdk on ubuntu 18.04 and followed the doc with following steps. However, I got "command not found" error when trying to start the target app on the last step.
1.  git clone https://github.com/spdk/spdk.git
2.  cd spdk
     git submodule update --init
3.  ./configure --with-ocf
4.  make
5.  sudo ./scripts/setup.sh
6.  sudo ./app/spdk_tgt/spdk_tgt &      --> this got  "command not found" error

**Comment by jimharris** [comment]
Hi @jianlenovo,

Can you provide details on where you found the doc that had these steps?

The spdk_tgt binary used to be in app/spdk_tgt directory, but now exists under build/bin.  So step 6 should be:

sudo ./build/bin/spdk_tgt &

-Jim

**Comment by jianlenovo** [comment]
Jim,

Thank you for the quick reply.

The following are 2 docs that I followed,
https://open-cas.github.io/getting_started_spdk.html
https://spdk.io/doc/getting_started.html

Thanks,

Jian

From: Jim Harris ***@***.***>
Sent: Friday, March 26, 2021 2:56 PM
To: spdk/spdk ***@***.***>
Cc: Jian Li ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [spdk/spdk] Question about spdk_tgt (#1862)


Hi @jianlenovo<https://github.com/jianlenovo>,

Can you provide details on where you found the doc that had these steps?

The spdk_tgt binary used to be in app/spdk_tgt directory, but now exists under build/bin. So step 6 should be:

sudo ./build/bin/spdk_tgt &

-Jim

**Comment by jimharris** [comment]
Yeah, the open-cas documentation needs to be updated.  I filed an issue in their GitHub:

https://github.com/Open-CAS/open-cas-linux/issues/765

**Comment by jianlenovo** [comment]
Jim,

I was able to start tgt without error following your instruction, but it failed at a later command as following,

***@***.***:~/SPDK/spdk$ sudo ./build/bin/spdk_tgt &
[2] 16023
***@***.***:~/SPDK/spdk$ sudo scripts/rpc.py construct_nvme_bdev -b nvme0 -t PCIe -a 0000:86:00.0
[sudo] password for lab-ai:
Error while connecting to /var/tmp/spdk.sock
Is SPDK application running?
Error details: [Errno -2] Name or service not known

[2]+  Stopped                 sudo ./build/bin/spdk_tgt

From: Jim Harris ***@***.***>
Sent: Friday, March 26, 2021 3:11 PM
To: spdk/spdk ***@***.***>
Cc: Jian Li ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [spdk/spdk] Question about spdk_tgt (#1862)


Yeah, the open-cas documentation needs to be updated. I filed an issue in their GitHub:

Open-CAS/open-cas-linux#765<https://github.com/Open-CAS/open-cas-linux/issues/765>

**Comment by jimharris** [comment]
Please try starting spdk_tgt in the foreground, and run scripts/rpc.py from a separate terminal.

It is possible that your sudo spdk_tgt & prompted a sudo password prompt, meaning spdk_tgt hadn't actually started.

**Comment by jianlenovo** [comment]
Jim,

I have run into another issue when trying out SPDK. When I tried to follow the example of “MVMe bdev character device”, https://spdk.io/doc/bdev.html#bdev_config_nvme_cuse, I got an error:
rpc.py: error: unrecognized arguments: -p spdk/nvme0

Thank you for your help.

Regards,

Jian
From: Jim Harris ***@***.***>
Sent: Friday, March 26, 2021 3:23 PM
To: spdk/spdk ***@***.***>
Cc: Jian Li ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [spdk/spdk] Question about spdk_tgt (#1862)


Please try starting spdk_tgt in the foreground, and run scripts/rpc.py from a separate terminal.

It is possible that your sudo spdk_tgt & prompted a sudo password prompt, meaning spdk_tgt hadn't actually started.
