### ISSUE TITLE
[MLX5_DV - SPDK-tgt] Failed to run image 'ubuntu2004-ofed-spdk_dev'

### ISSUE THREAD

**Issue by sun-mingbao** [spdk/spdk#1865]
Following are the error log:

[2021-03-29T05:32:29.366Z] + docker inspect -f . ubuntu2004-ofed-spdk_dev

[2021-03-29T05:32:29.366Z] .

Failed to run image 'ubuntu2004-ofed-spdk_dev'. Error: docker: Error response from daemon: Conflict. The container name "/dev_spdk_dv_app" is already in use by container "9480d2c950895dc6f3e2c615f7e4570bd60c4518a8089d2e250e0ddcaabfc16f". You have to remove (or rename) that container to be able to reuse that name.

See 'docker run --help'.

**Comment by jimharris** [comment]
Hi @sun-mingbao,

SPDK does not release container images, so this does not seem to be an SPDK failure.

I am going to change the label on this issue to "question" for now.  I'm not sure if anyone here will be able to help you with your container image, but please provide more details including reproduction steps in case someone wants to try to help.

-Jim

**Comment by AlekseyMarchuk** [comment]
@sun-mingbao @jimharris there was a problem in Mellanox CI, it is fixed now. @sun-mingbao please retrigger another build by leaving a comment with `Mellanox:retest` content

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_40270.html

**Comment by jimharris** [comment]
Closing.  This was related to an intermittent problem with Mellanox CI.
