### ISSUE TITLE
[nvmf-phy-autotest] Test Failure

### ISSUE THREAD

**Issue by sun-mingbao** [spdk/spdk#1868]
https://ci.spdk.io/public_build/autotest-per-patch_40271.html

The above URL has the following failures:

nvmf-phy-autotest #33492		
nvmf-tcp-phy-autotest #136		
nvmf-tcp-uring-vg-autotest #16337	
nvmf-tcp-vg-autotest #19774		
nvmf-vg-autotest #19751			

However, I could not see any relationship between my commit and the nvmef.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sun-mingbao. log: https://ci.spdk.io/public_build/autotest-per-patch_40272.html

**Comment by changpe1** [comment]
@sun-mingbao I checked the failure of your CI results, it's related with your patch.

test/nvme/aer/aer.c is doing the same thing as you did in your patch, so you may remove the duplicated code in test/nvme/aer/aer.c to pass the CI.

**Comment by karlatec** [comment]
@sun-mingbao Also - if possible please rebase your patch on latest master branch head. This was announced on Slack yesterday, but you might have missed it.

**Comment by sun-mingbao** [comment]
@changpe1 @karlatec 
Got it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_40455.html

**Comment by karlatec** [comment]
@dong-liuliu First report is unrelated, second seems to be resolved after rebase like suggested in previous comments

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_41030.html

**Comment by jimharris** [comment]
Closing this issue.  The most recent reports here are duplicates of #1870.
