### ISSUE TITLE
NVMe bdev character device

### ISSUE THREAD

**Issue by jianlenovo** [spdk/spdk#1869]
I am trying out spdk on ubuntu 18.04. Following the user doc, https://spdk.io/doc/bdev.html#bdev_config_nvme, "MVMe bdev character device" section -- was able to create bdev Nvme0 successfully , but got an error when executing the following command:

rpc.py bdev_nvme_cuse_register -n Nvme0 -p spdk/nvme0  --> an error as below

rpc.py: error: unrecognized arguments: -p spdk/nvme0

**Comment by jimharris** [comment]
/dev/spdk directory will not be created until the first bdev_nvme_cuse_register RPC.

**Comment by jianlenovo** [comment]
Jim,

Got it.

However, I got an error response for bdev_nvme_cuse_register RPC without -p as following,

***@***.***:~/SPDK/spdk$ sudo ./scripts/rpc.py bdev_nvme_cuse_register -n NVMe0
request:
{
  "name": "NVMe0",
  "method": "bdev_nvme_cuse_register",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"
}

From: Jim Harris ***@***.***>
Sent: Tuesday, March 30, 2021 3:37 PM
To: spdk/spdk ***@***.***>
Cc: Jian Li ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [spdk/spdk] NVMe bdev character device (#1869)


/dev/spdk directory will not be created until the first bdev_nvme_cuse_register RPC.

**Comment by jimharris** [comment]
Can you confirm you ran configure with the --with-nvme-cuse option before building?

I just posted another rev of the doc patch above, with an addition for this configure option.

**Comment by jianlenovo** [comment]
Jim,

It did not build with --with-nvme-cuse option.
Will rebuild with that.

Thanks,

Jian

From: Jim Harris ***@***.***>
Sent: Tuesday, March 30, 2021 3:50 PM
To: spdk/spdk ***@***.***>
Cc: Jian Li ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [spdk/spdk] NVMe bdev character device (#1869)


Can you confirm you ran configure with the --with-nvme-cuse option before building?

I just posted another rev of the doc patch above, with an addition for this configure option.

**Comment by Comphix** [comment]
@jianlenovo , how is the current status? After rebuilding with --with-nvme-cuse option, is it working now?

**Comment by jianlenovo** [comment]
Yes, rebuilding with –with-nvme-cuse option works.
Thanks,

Jian

From: GangCao ***@***.***>
Sent: Tuesday, April 6, 2021 4:34 AM
To: spdk/spdk ***@***.***>
Cc: Jian Li ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [spdk/spdk] NVMe bdev character device (#1869)


@jianlenovo<https://github.com/jianlenovo> , how is the current status? After rebuilding with --with-nvme-cuse option, is it working now?

**Comment by Comphix** [comment]
Close this issue.
