### ISSUE TITLE
GP1 has no free nvme drives for the tests

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1870]
This fails the `devices` test: https://ci.spdk.io/results/autotest-per-patch/builds/40447/archive/nvmf-tcp-phy-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_40447.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_40453.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_40468.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_40523.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_40609.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_40607.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40554.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40541.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40559.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40546.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40535.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_40540.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_40285.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_40719.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_40714.html

**Comment by karlatec** [comment]
@mikeBashStuff  I'm pretty sure that there is a NVMe drive in GP1:

```
[sys_sgci@GrizzlyPass1 spdk]$ sudo nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     PHLJ910003481P0FGN   INTEL SSDPE2KX010T8                      1           1.00  TB /   1.00  TB    512   B +  0 B   VDV10170
[sys_sgci@GrizzlyPass1 spdk]$ ll /sys/block | grep nvme
lrwxrwxrwx 1 root root 0 Apr  5 11:53 nvme0n1 -> ../devices/pci0000:80/0000:80:02.0/0000:82:00.0/nvme/nvme0/nvme0n1
[sys_sgci@GrizzlyPass1 spdk]$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 232.9G  0 disk
├─sda1        8:1    0   976M  0 part /boot
├─sda2        8:2    0  14.9G  0 part [SWAP]
└─sda3        8:3    0   217G  0 part /
sr0          11:0    1  1024M  0 rom
sr1          11:1    1  1024M  0 rom
nvme0n1     259:0    0 931.5G  0 disk
└─nvme0n1p1 259:1    0 931.5G  0 part
```

**Comment by mikeBashStuff** [comment]
> @mikeBashStuff I'm pretty sure that there is a NVMe drive in GP1:
> 
> ```
> [sys_sgci@GrizzlyPass1 spdk]$ sudo nvme list
> Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
> ---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
> /dev/nvme0n1     PHLJ910003481P0FGN   INTEL SSDPE2KX010T8                      1           1.00  TB /   1.00  TB    512   B +  0 B   VDV10170
> [sys_sgci@GrizzlyPass1 spdk]$ ll /sys/block | grep nvme
> lrwxrwxrwx 1 root root 0 Apr  5 11:53 nvme0n1 -> ../devices/pci0000:80/0000:80:02.0/0000:82:00.0/nvme/nvme0/nvme0n1
> [sys_sgci@GrizzlyPass1 spdk]$ lsblk
> NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
> sda           8:0    0 232.9G  0 disk
> ├─sda1        8:1    0   976M  0 part /boot
> ├─sda2        8:2    0  14.9G  0 part [SWAP]
> └─sda3        8:3    0   217G  0 part /
> sr0          11:0    1  1024M  0 rom
> sr1          11:1    1  1024M  0 rom
> nvme0n1     259:0    0 931.5G  0 disk
> └─nvme0n1p1 259:1    0 931.5G  0 part
> ```
> 
> Although I'm not sure why is there a partition created there

Yes, there is, but it's not free. It has a ntfs partition installed. I could remove it but don't know why it's there in a first place.

**Comment by karlatec** [comment]
@mikeBashStuff  I have a suspicion. Could you check the CI job running Windows SCSI compliance test? This job is designated to only run on GP1, maybe something isn't cleaned properly after the test.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_41000.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_40961.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_40977.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_40979.html

**Comment by mikeBashStuff** [comment]
@karlatec Sure, will check it out.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_41025.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_41020.html

**Comment by mikeBashStuff** [comment]
Potential fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/7269

**Comment by jimharris** [comment]
Thanks @mikeBashStuff - I added my +2.

Any idea why this problem started just recently?

**Comment by mikeBashStuff** [comment]
@jimharris It started right after the `test/setup` suite got merged (and that happened quite recently) - that's where the failing test is coming from. Failures were limited to GP1 since any other system in the pool had available nvme disk for these particular tests. And the reason why there was none on GP1 was due to `windows_scsi_compliance` not cleaning up after itself (hence the patch above). :)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41232.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41271.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41273.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_41276.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_41409.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41280.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41281.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_41289.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_41306.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_41284.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_41419.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_41430.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_41707.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_41763.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_41718.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_41774.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_41765.html

**Comment by tomzawadzki** [comment]
[Bug scrub] @mikeBashStuff please link that was to fix the latest report with vhost tests. If that confirms the resolution, feel free to close this one.

**Comment by mikeBashStuff** [comment]
The initial issue with GP1 was fixed via https://review.spdk.io/gerrit/c/spdk/spdk/+/7269. Later reports point at GP8 which was being affected by a separate job and fixed via this series: https://review.spdk.io/gerrit/c/spdk/spdk/+/7321 Haven't seen similar failures since the last report and GP1 and GP8 seem to have their nvme drives in order so far. Closing, if this issue resurfaces, please reopen the issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47029.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_47192.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_50598.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_55050.html
