### ISSUE TITLE
[unittest-vg-autotest] The CQ Head Doorbell is updated twice with the same value during format

### ISSUE THREAD

**Issue by balamsg** [spdk/spdk#1871]
[unittest-vg-autotest] The CQ Head Doorbell is updated twice with the same value during format command.

00:20:11.231  Build timed out (after 20 minutes). Marking the build as failed.
00:20:27.804  Build was aborted
00:20:27.812  [PostBuildScript] - [INFO] Executing post build scripts.

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/40456/archive/unittest-vg-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @balamsg. log: https://ci.spdk.io/public_build/autotest-per-patch_40456.html

**Comment by mikeBashStuff** [comment]
@balamsg you need to rebase your patches against the latest master. This timeout was due to recent changes that got merged in the spdk repo and the CI pool.

**Comment by balamsg** [comment]
@mikeBashStuff I have done the rebase before pushing it for review

**Comment by mikeBashStuff** [comment]
@balamsg I am looking at the patchset 3 of your commit https://review.spdk.io/gerrit/c/spdk/spdk/+/7149 and it doesn't seem to be up-to-date. 
```
root@debianMB[SPDK]:~/spdk_repo/spdk# git checkout FETCH_HEAD
 * branch                refs/changes/49/7149/3 -> FETCH_HEAD
HEAD is now at 7afc688ae NVMe: Fix the bug that the CQ Head Doorbell is updated twice with the same value
root@debianMB[SPDK]:~/spdk_repo/spdk# git cherry -v  FETCH_HEAD origin/master

# Missing commits
+ 13cd7c597ab365b2b8158721d8202f052d193197 example/abort: Fix missing optarg.
+ d22233ac592a1ca5025e16fbb4c7acd44f73b0e9 autopackage: Make lto build dependent only on RUN_NIGHTLY flag 
+ c4a1b3431a242c7c8da7c12aac09e0681615f9f9 nvmf: Fix bug when subsystem failed to pause
+ b69356a85d4cd53bcd59f9a86a1373ca4f591cac test/nvme_ctrlr: cases for ctrlr adding and removing process
+ 0ccf4a9ce6b81d9c6de89b0cdd012497858f47dd env_pci: fix device_allow small issue
root@debianMB[SPDK]:~/spdk_repo/spdk#

```

From the above list, the lack of  d22233ac592a1ca5025e16fbb4c7acd44f73b0e9  is causing the build to timeout.

**Comment by balamsg** [comment]
I got the same issue even after rebasing

**Comment by changpe1** [comment]
Link this issue to #1701.

**Comment by changpe1** [comment]
[Bug Scrub] we discussed this issue today, SPDK should try to avoid recursive call to spdk_nvme_qpair_process_completions() in the aer_cb function, one way is to execute aer_cb sequentially.

**Comment by balamsg** [comment]
Hi @changpe1 , Yes, asynchronous submission of Active NS list & the Identify NS commands will solve the issue. But that comes  with a lot of code changes so i have just avoided the CQ head doorbell updation twice with the same value.

**Comment by changpe1** [comment]
Yeah, do you want to have a try? if no I can take care of this change.

**Comment by balamsg** [comment]
Sure @changpe1,  i will make the changes. I will make the submission of Active Ns list & identify Ns as asynchronous.

**Comment by balamsg** [comment]
00:15:28.295  Build timed out (after 15 minutes). Marking the build as failed.
00:15:28.307  Build was aborted
00:15:28.308  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:28.317  [nvmf-phy-autotest] $ /usr/bin/env bash /tmp/jenkins7740217856687376351.sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @balamsg. log: https://ci.spdk.io/public_build/autotest-per-patch_41428.html

**Comment by balamsg** [comment]
The following tests are failing which are not related to my patch.
nvmf-phy-autotest, nvmf-tcp-phy-autotest , nvmf-tcp-uring-vg-autotest, nvmf-tcp-vg-autotest, nvmf-vg-autotest.

**Comment by jimharris** [comment]
Hi @balamsg, thanks for your work on this issue!  The patches have been merged, so closing this issue.
