### ISSUE TITLE
config option to just compile and not link

### ISSUE THREAD

**Issue by rch0wdhury** [spdk/spdk#1877]
Hi,
Is there any config option that just compiles the files and creates the static/dynamic libraries but does not link anything (apps, examples, tests ...)
Thanks.

**Comment by jimharris** [comment]
Hi @rch0wdhury,

There are some options to disable some of those but not all.  I see no reason not to add more config options though to do what you are looking for.

--disable-tests
--disable-unit-tests
--disable-examples

We just need one for --disable-apps.  Assigning this to me, I'll push a patch for this tomorrow.

-Jim

**Comment by rch0wdhury** [comment]
Thanks Jim. Yes, --disable-apps should do it.

**Comment by rch0wdhury** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/7462

**Comment by jimharris** [comment]
Thanks @rch0wdhury!  I posted some feedback on the Gerrit review.

**Comment by jimharris** [comment]
hi @rch0wdhury, would you be able to post a new version of your patch with the requested feedback?
