### ISSUE TITLE
add support for physical block size and/or preferred write granularity

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#1884]
The SPDK bdev layer today has no support for modules to report the physical block size and/or preferred write granularity for a bdev.  Some bdevs have the ability to get this, for example:

* bdev_iscsi, bdev_virtio_scsi - READ_CAPACITY_16
* bdev_nvme - NPWG (Namespace Preferred Write Granularity)

Steps to implement:
1) add new phys_blocklen field to struct spdk_bdev
2) add bdev getter API to return this field (spdk_bdev_get_physical_block_size?)
3) update lib/scsi/scsi_bdev.c to report logical_block_per_physical_block_exponent in READ_CAPACITY_16
4) update nvmf target to report npwg value based on bdev's physical block size (also need to set NSFEAT bit 4 to indicate NPWG is valid)

It would be good for SPDK to report this correctly, although In practice, this should have little or no effect on consumers of NVMe namespaces or SCSI LUNs exported by SPDK.  Partitioning tools for example have for a long time aligned partitions on at least 4KB boundaries (usually 1MB actually).  Applications that consume block storage directly likely already use implicit 4KB assumptions regardless of what the reports, since even for NVMe, NPWG is a relatively recent addition and there are a lot of NVMe SSDs out there today that still do not support it (in which case physical block size is reported same as logical block size).

**Comment by jlevon** [comment]
For NVMe specifically as well, there is the possibility of LBA formats as well, which is another way of identifying a preferred block size. From googling it appears at least some NVMe controllers in hardware do do this.

**Comment by jimharris** [comment]
That's true @jlevon.

One of the side effects of selecting a 4KB logical block size is that it forces you to also always read at least 4KB of data at a time.  There are some database applications that either use O_DIRECT or consume block storage directly, and will read sub-4KB chunks (of 512B multiples) if possible to optimize the amount of data transferred and resulting latency.

**Comment by Comphix** [comment]
I will take a look at this one.

**Comment by Comphix** [comment]
@jimharris , for the SCSI of Read Capacity 16.

I am looking at the SCSI spec https://www.t10.org/ftp/t10/document.05/05-344r0.pdf

At P55 of "5.11 READ CAPACITY (16) command", in this case, we will return the "Physical Blocklen" for the "Block Length in Bytes" field?

**Comment by Comphix** [comment]
So in this case, if there is no physical block size set already, we will just set phys_blocklen = blocklen in this case. For a real NVMe backend, if it has NPWG there, will also set the bdev_nvme to that value and then report out to nvmf target.

**Comment by swapnili** [comment]
I have raised https://review.spdk.io/gerrit/c/spdk/spdk/+/7310 to address bdev_iscsi.
Please have a look.
Thanks

**Comment by Comphix** [comment]
Thanks @swapnili  Let me assign this issue to you.

**Comment by jimharris** [comment]
Patch merged.  Thanks @swapnili!
