### ISSUE TITLE
bdev_iscsi_unmap() doesn't respect maximum unmap LBA count

### ISSUE THREAD

**Issue by jlevon** [spdk/spdk#1888]
Using current master, we hit a problem with an iSCSI server, which was refusing unmap requests. This was because its maximum LBA count was 32768 (and its maximum descriptor count was 1).

bdev_iscsi_unmap() doesn't respect these values, and just presumes it can pass through the request.
I've made a prototype change to split up large requests as needed, and it works again (although it is potentially unbounded in stack allocations).

There is some history in this area:

https://review.gerrithub.io/c/spdk/spdk/+/419165/3/lib/bdev/iscsi/bdev_iscsi.c#354

This was an abandoned gerrit from @jessehui. I believe that @benlwalker's comment was mis-understood there: it's the check against .blockcnt that is not necessary, not the splitting of requests.

That gerrit has a couple of problems anyway; it was dropping all descriptors other than the first (no change to line :352 nr of list items), and it wouldn't help in our case anyway, as it needs to respect the max. descriptor count for the iscsi server.

I also think the UINT32_MAX change might still be needed?

**Comment by jlevon** [comment]
cc @changpe1

**Comment by jimharris** [comment]
Thanks for the report @jlevon.

We could also consider doing these checks and splits in the bdev layer itself.  Allow modules to report a max unmap LBA count, and if spdk_bdev_unmap_blocks exceeds that, the bdev layer splits it up into multiple bdev_ios.

But I think we want some kind of upper bound on how many of those split I/O can be outstanding at once.  If the iSCSI target is exposing a 2TB LUN w/ 512B sector size, that's 128K unmap requests.  We need that whether we do this work in the bdev layer or the bdev iscsi module.

For now, I'd say let's just do it in the bdev iscsi module.  Can you share your prototype patch as a starting point?

**Comment by jlevon** [comment]
Patch I have is here:

https://github.com/jlevon/spdk/commit/8a964852d895c77edc837572476b48c3837babcd

As mentioned it works, but clearly has some problems. It doesn't have the pending I/O issue you mentioned, at the cost of a giant stack instead :)

I see we already have some split support in bdev, though it doesn't immediately look suitable for the unmap split you're suggesting (I think we'd want multiple bdev_io's??)

**Comment by jimharris** [comment]
I was thinking it would look more like the spdk_bdev_write_zeroes_blocks(), where it does an explicit write of a zeroed buffer when the bdev doesn't natively support write zeroes.  In that case, we have a single 1MB buffer that is written 1MB at a time to the specified LBA range.  In this unmap case, we would instead check the maximum LBA count and go down the split path if the specified LBA count exceeds it.

Now for write zeroes, we only do 1 write at a time, but for unmap I don't see any reason why we can queue several up.  There needs to be a limit obviously - is 8 or 16 sufficient?  If we need more than 8 or 16, we just wait until one of the previous ones complete and submit a new one to replace it.

**Comment by jlevon** [comment]
You'll have to excuse my lack of familiarity with the bdev code, but doesn't this have an arbitrarily-long

bdev_write_zero_buffer_next()->bdev_write_blocks_with_md()->bdev_write_zero_buffer_done()->bdev_write_zero_buffer_next()->...

call chain until u.bdev.split_remaining_num_blocks reaches zero?

Basically the same issue with my prototype fix?

**Comment by jimharris** [comment]
bdev completions are always executed asynchronously - never in the context of the submission.

**Comment by changpe1** [comment]
I submitted the patch serial here, https://review.spdk.io/gerrit/c/spdk/spdk/+/7519/1.

Currently I added the SCSI specification with "MAXIMUM UNMAP LBA COUNT" and "MAXIMUM UNMAP BLOCK DESCRIPTOR COUNT", ignored the "OPTIMAL UNMAP GRANULARITY" and "GRANULARITY ALIGNMENT", because I found both SPDK iSCSI target and Linux kernel LIO target don't support that, and the NVMe specification also doesn't include that.

**Comment by jlevon** [comment]
I tested it in our env, works well, thank you.

**Comment by changpe1** [comment]
patch has been merged, closing this issue now.
