### ISSUE TITLE
Nightly tests fail due to missing dependencies directory

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1890]
## Current Behavior

Some of the nightly builds fail because of `/home/sys_sgci/spdk_dependencies/spdk_test_image.qcow2 is missing` error.
See:
https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v20.11_607.html

## Possible Solution

Provision test node filesystem according to: https://review.spdk.io/gerrit/c/spdk/spdk/+/6940/9

## Context (Environment including OS version, SPDK version, etc.)
SPDK 1fc0c2d8b

**Comment by wawryk** [comment]
Nightly systems provisioned.

**Comment by karlatec** [comment]
@wawryk please wait a couple of hours and verify if nightly builds are in passing state again. If these fail will not show up then please close the issue. Thanks!

**Comment by wawryk** [comment]
Nightly build passing.
Closing this issue.
