### ISSUE TITLE
Support NVME_IOCTL_IO_CMD in cuse block device.

### ISSUE THREAD

**Issue by gcoakes** [spdk/spdk#1892]
Currently, only `NVME_IOCTL_ADMIN_CMD`, `NVME_IOCTL_SUBMIT_IO`, and `NVME_IOCTL_ID` are supported by the cuse interface. This prevents commands such as dsm trim from being issued against the block device.

## Expected Behavior

The following command should successfully run when under SPDK drivers. This is essentially just a hello world for IO commands. It's extracted directly from `man nvme-io-passthru`.

``` bash
nvme io-passthru /dev/spdk/nvme0n1 --opcode=2 --namespace-id=1 --data-len=4096 --read --cdw10=0 --cdw11=0 --cdw12=0x70000 --raw-binary
```

## Current Behavior

The `spdk_tgt` process reports an error indicating the IOCTL is unsupported:

``` bash
[2021-03-30 18:35:16.696735] nvme_cuse.c: 611:cuse_ns_ioctl: *ERROR*: Unsupported IOCTL 0x1268.
```

## Possible Solution

Implement the relevant IOCTL handler in `cuse_ns_ioctl` of `lib/nvme/nvme_cuse.c`. From a cursory glance, it seems to be similar to the way [admin commands](https://github.com/spdk/spdk/blob/50569293ef0d2ea1527465e4fc9bfad416d07c1e/lib/nvme/nvme_cuse.c#L193) are handled currently. It would just have to be adapted to support the I/O commands.

## Steps to Reproduce

``` bash
# From SPDK's repository root after compiling the apps.
modprobe cuse
./scripts/setup.sh
./build/spdk_tgt 2>&1 1>spdk_tgt.log &
./scripts/rpc.py bdev_nvme_attach_controller -r 10 -b nvme0 -t PCIe -a $DEVICE_PCI_ADDR
./scripts/rpc.py bdev_nvme_cuse_register -n nvme0
nvme io-passthru /dev/spdk/nvme0n1 --opcode=2 --namespace-id=1 --data-len=4096 --read --cdw10=0 --cdw11=0 --cdw12=0x70000 --raw-binary > io-passthru.bin
```

`spdk_tgt.log` should contain the error message seen above.

## Context (Environment including OS version, SPDK version, etc.)

Context should be irrelevant. The functionality is simply not implemented, but...

OS version: Ubuntu 20.04
SPDK version: 0968ee2fc

**Comment by gcoakes** [comment]
The basic io-passthru command from the description works. I've also gotten several internal tests to work properly with this change. Thank you @jimharris and @curtbruns.

**Comment by jimharris** [comment]
Thanks for the confirmation @gcoakes!
