### ISSUE TITLE
NVMe FIO plugin always reports success regardless of status code.

### ISSUE THREAD

**Issue by gcoakes** [spdk/spdk#1893]
The FIO plugin which uses SPDK's NVMe API directly ([`examples/nvme/fio_plugin`](https://github.com/spdk/spdk/tree/master/examples/nvme/fio_plugin)) appears to always pass regardless of errors. The function [`spdk_fio_completion_cb`](https://github.com/spdk/spdk/blob/558be98fd3b0a35cfefb4c758f9b62e6e10c3087/examples/nvme/fio_plugin/fio_plugin.c#L895) never dereferences the [`spdk_nvme_cpl`](https://spdk.io/doc/structspdk__nvme__cpl.html) when read or write completes which indicates it never inspects the status code or status code type to determine whether an I/O unit failed. I'm fairly certain something like gcoakes/spdk@2fdcd87 would suffice, but I'm finding the FIO I/O engine documentation shockingly sparse to confirm if it's correct. I would submit a pull request, but I'm realizing the contribution process is a little bit different here.

To clarify, this is not something I've confirmed by experiment but by code inspection.

**Comment by mkenguva** [comment]
patch submitted https://review.spdk.io/gerrit/c/spdk/spdk/+/7567 to address this.
