### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by rch0wdhury** [spdk/spdk#1895]
Minor issue - looks like g_tsc_us_rate is unused .

https://github.com/spdk/spdk/blob/90db6167ce6331bcb9c93abd05c0999d3d834726/test/event/event_perf/event_perf.c#L100

**Comment by yidong0635** [comment]
not only here , but also in Accel_perf. here should be ?
g_tsc_us_rate = spdk_get_ticks_hz();
g_tsc_rate = g_tsc_us_rate / (1000 * 1000);
g_tsc_end = spdk_get_ticks() + g_time_in_sec * g_tsc_rate;

**Comment by yidong0635** [comment]
oh , no it's not right just unused, I just guest the meaning.
