### ISSUE TITLE
rpc.py construct_lvol_bdev failed that report timeout. but the size of lvs is reduced, and lvol bdev wasn't created.

### ISSUE THREAD

**Issue by yangliang20065613** [spdk/spdk#1896]
rpc.py construct_lvol_bdev failed that report timeout. but the size of lvs is reduced, and lvol bdev wasn't created.

## Expected Behavior
1. construct one 1G logical volume from lvs0
rpc.py construct_lvol_bdev -l lvs0 disk0 10240

2. we can get logical volume of disk0 by rpc get_bdevs command.

## Current Behavior
1. construct one 1G logical volume from lvs0
rpc.py construct_lvol_bdev -l lvs0 disk0 10240

2. we can't get logical volume of disk0 by rpc get_bdevs command.

3.the free clusters of lvs0 is reduced after constructing disk0
rpc.py get_lvol_stores
[
  {
    "block_size": 4096,
    "uuid": "ff3cd675-2c7a-4dbb-b62d-ec01b12dcf7f",
    "base_bdev": "Nvme0n1",
    "cluster_size": 4194304,
    **"free_clusters": 210074,**
    "name": "lvs0",
    "total_data_clusters": 238234
  },

## Possible Solution
none

## Steps to Reproduce
none

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
spdk:18.01
OS:centos 6.3

**Comment by Comphix** [comment]
Looks like SPDK is old of v18.01. Have you tried SPDK v21.01? Also what logs are reported at the SPDK side when failed to create the device?

**Comment by yangliang20065613** [comment]
> 
> 
> Looks like SPDK is old of v18.01. Have you tried SPDK v21.01? Also what logs are reported at the SPDK side when failed to create the device?

I haven't try v21.01 becasuse this issue can't be reproduced easily, and we've only had two. There is no log in spdk.log, and we only get timeout from rpc.py construct_lvol_bdev.

Is this issue one known issue? Could I get any patch link about this issue?

Thank you very much.

**Comment by changpe1** [comment]
In the old SPDK version, the RPC is running in synchronous mode, this RPC is marked with "depreciated" and renamed to "bdev_lvol_create", I guess this is the reason why you met the timeout.

**Comment by changpe1** [comment]
[Bug Scrub] The version you are using is too old, you can check the git log to see which RPC you can check out for your branch. thanks.

**Comment by changpe1** [comment]
closing this issue for now.

**Comment by yangliang20065613** [comment]
> 
> 
> [Bug Scrub] The version you are using is too old, you can check the git log to see which RPC you can check out for your branch. thanks.

Ok, thank you.
