### ISSUE TITLE
SPDK Vhost memory mapping issues

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1901]
## Current Behavior

After recent changes to SPDK vhost there are problems with memory mapping. This does not show up in CI most probably due to scale (number of Vhost CPU cores and/or VMs attached to Vhost) when this occurs. The issue was detected in vhost performance regression tests when the builds started to fail due to IO errors.

I was not able to reproduce this in 1CPU Vhost + 6 VMs or 2CPU Vhost + 12 VMs. Issue is easily reproduced at scale where 4CPU Vhost + 24 VMs are used.

## Possible Solution

Vhost performance regression tests started to fail after this patch `aaac48880 env: Register external memory with DPDK` was merged, so it might be the root cause.
`git revert` of this commit currently does not cause any git conflicts or compilation problems, so I guess it could be used as a solution of last resort.

## Steps to Reproduce

Because the issue happens in larger scale tests than what we usually test in CI, the reproduction is done using vhost performance test scripts. It might not be obvious how to run them at the first try, so let me know if more details are needed. I'll also add a comment with high-level description about what's actually happening in the test script.

1. Compile SPDK with `./configure --with-fio=/usr/src/fio  --enable-debug`. Debug seems optional, I did not notice it giving any more information or output than when builiding without debug.
2. Bind NVMes to userspace and allocate hugepages:
```
sudo HUGEMEM=300000 HUGE_EVEN_ALLOC=yes ./scripts/setup.sh
```
3. Run vhost performance test with 4 CPU Vhost ,24VMs attached and run fio randwrite IO.
```
sudo -E test/vhost/perf_bench/vhost_perf.sh --vm-image=/home/sys_sgsw/fedora33.qcow2 \
--vm-memory=4096 \
--fio-jobs=/var/perf_jenkins/workspace/vhost-perf/tc1-blk-nvme-4k/tc1_4k_randwrite_1_blk_nvme_4CPU_24VM.conf \
--custom-cpu-cfg=/var/perf_jenkins/workspace/vhost-perf/tc1-blk-nvme-4k/cpu_map_4CPU_24VMs.conf \
--disk-map=/var/perf_jenkins/workspace/vhost-perf/tc1-blk-nvme-4k/disk_map_4CPU_24VMs.conf \
--fio-iterations=1 --ctrl-type=spdk_vhost_blk --use-split --fio-gtod-reduce
```
4. Following results in:
DPDK EAL messages when the VMs are booting and connecting to SPDK Vhost:
(there's A LOT of these messages, so copying only some lines for example)
```
[...]
11:26:27 EAL: WARNING! Base virtual address hint (0x202001035000 != 0x7f8ea0160000) not respected!
11:26:27 EAL:    This may cause issues with mapping memory into secondary processes
11:26:28 EAL: WARNING! Base virtual address hint (0x20200103b000 != 0x7f8ea0147000) not respected!
11:26:28 EAL:    This may cause issues with mapping memory into secondary processes
11:26:28 VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
11:26:28 VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
11:26:28 VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
11:26:28 VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
11:26:28 VHOST_CONFIG: vring kick idx:1 file:506
11:26:28 VHOST_CONFIG: virtio is now ready for processing.
11:26:28 EAL: WARNING! Base virtual address hint (0x202001041000 != 0x7f8ea0160000) not respected!
11:26:28 EAL:    This may cause issues with mapping memory into secondary processes
11:26:28 EAL: WARNING! Base virtual address hint (0x202001047000 != 0x7f8ea0147000) not respected!
11:26:28 EAL:    This may cause issues with mapping memory into secondary processes
11:26:28 VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
[...]
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 EAL: No more space for user mem maps
11:26:35 VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
11:26:35 EAL: Not enough space to store partial mapping
[...]
11:26:36 EAL: No more space for user mem maps
11:26:36 EAL: No more space for user mem maps
11:26:36 EAL: No more space for user mem maps
11:26:36 VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
11:26:36 EAL: Couldn't find previously mapped region
11:26:36 EAL: Couldn't find previously mapped region
11:26:36 EAL: Couldn't find previously mapped region
11:26:36 EAL: Couldn't find previously mapped region
11:26:36 EAL: Couldn't find previously mapped region
```

The VMs are able to boot up regardless of these error/warning messages. After the VMs have booted we start fio tasks in server-client mode. Each VM has a FIO server running and we issue a command from host to start the IO:
```
fio --eta=never \
--output=/var/perf_jenkins/workspace/vhost-perf/tc1-blk-nvme-4k/vhost_test/fio_results/tc1_4k_randwrite_1_blk_nvme_4CPU_24VM.log \
--output-format=json \
--client=127.0.0.1,10001 --remote-config /root/tc1_4k_randwrite_1_blk_nvme_4CPU_24VM.conf \
--client=127.0.0.1,10101 --remote-config /root/tc1_4k_randwrite_1_blk_nvme_4CPU_24VM.conf \
[etc, etc...] \
--client=127.0.0.1,12201 --remote-config /root/tc1_4k_randwrite_1_blk_nvme_4CPU_24VM.conf \
--client=127.0.0.1,12301 --remote-config /root/tc1_4k_randwrite_1_blk_nvme_4CPU_24VM.conf
```

Which results in following error messages, this time from SPDK:
```
11:27:56 [2021-04-15 11:27:56.594163] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:892 nsid:1 lba:23564608 len:1 PRP1 0x7f677b9b2000 PRP2 0x0
11:27:56 [2021-04-15 11:27:56.594280] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:2 cid:892 cdw0:0 sqhd:0096 p:1 m:1 dnr:0
11:27:56 [2021-04-15 11:27:56.594960] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:895 nsid:1 lba:23564608 len:1 PRP1 0x7f7953472000 PRP2 0x0
11:27:56 [2021-04-15 11:27:56.595026] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:2 cid:895 cdw0:0 sqhd:0096 p:1 m:1 dnr:0
11:27:56 [2021-04-15 11:27:56.595204] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:890 nsid:1 lba:23564608 len:1 PRP1 0x7f7090846000 PRP2 0x0
11:27:56 [2021-04-15 11:27:56.595242] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:2 cid:890 cdw0:0 sqhd:0095 p:1 m:1 dnr:0
11:27:56 [2021-04-15 11:27:56.595489] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:895 nsid:1 lba:23564608 len:1 PRP1 0x7f82108bc000 PRP2 0x0
11:27:56 [2021-04-15 11:27:56.595546] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:2 cid:895 cdw0:0 sqhd:0096 p:1 m:1 dnr:0
11:27:56 [2021-04-15 11:27:56.596021] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:891 nsid:1 lba:23564608 len:1 PRP1 0x7f6b5357b000 PRP2 0x0
11:27:56 [2021-04-15 11:27:56.596043] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:2 cid:891 cdw0:0 sqhd:0094 p:1 m:1 dnr:0
11:27:56 [2021-04-15 11:27:56.596891] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:893 nsid:1 lba:23564608 len:1 PRP1 0x7f6993bc1000 PRP2 0x0
11:27:56 [2021-04-15 11:27:56.596906] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:2 cid:893 cdw0:0 sqhd:0097 p:1 m:1 dnr:0
11:27:56 [2021-04-15 11:27:56.596973] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:894 nsid:1 lba:23564608 len:1 PRP1 0x7f6ed088e000 PRP2 0x0
11:27:56 [2021-04-15 11:27:56.596990] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:2 cid:894 cdw0:0 sqhd:0094 p:1 m:1 dnr:0
11:27:56 [2021-04-15 11:27:56.597657] nvme_qpair.c: 268:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:894 nsid:1 lba:23564608 len:1 PRP1 0x7f7ab1f79000 PRP2 0x0
```
Fio exits with return code =! 0, which fails the test.

## Context (Environment including OS version, SPDK version, etc.)
SPDK 50569293ef (Issue present since `aaac48880`)

Host system:
5.10.19-200.fc33.x86_64
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
QEMU emulator version 5.1.0 (qemu-5.1.0-9.fc33)
fio-3.24
24 Intel P4610 1.6TB NVMe Drives (FW: VDV10170)
384GB RAM (192GB per NUMA node)

Guest systems:
5.9.16-200.fc33.x86_64
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
fio-3.24
spectre-meltdown mitigations disabled with `mitigations=off`
2 vCPU each
4GB RAM each

**Comment by karlatec** [comment]
### Steps to reproduce extended

High-level description what's actually happening during test script execution:
* Launch SPDK Vhost with given core mask (4CPUs in this case)
* Create NVMe bdevs
* Create Vhost controllers
* Add 1 NVMe Bdev per vhost controller
* Run given number of VMs; each with 2vCPUs, 4GB RAM, connected to a single SPDK Vhost controller
* Wait until all VMs are up and running
* Run fio server on each VM `fio --eta=never --server --daemonize=/root/fio.pid`
* On host issue a command for all fio servers to start IO test using given fio config file:
```
[global]
ioengine=libaio
thread=1
group_reporting=1
direct=1
verify=0
norandommap=1

[perf_test]
stonewall
description="Run NVMe driver performance test for a given workload"
bs=4k
rw=randwrite
rwmixread=70
iodepth=1
time_based=1
ramp_time=60
runtime=240
numjobs=1
filename=/dev/vda
gtod_reduce=1
```
* wait until fio finishes (test actually crashes here)
* shutdown VMs
* stop SPDK Vhost process

**Comment by jimharris** [comment]
Bumping this one to critical.

@karlatec - can you confirm that reverting aaac48880 from master fixes the issue?

**Comment by karlatec** [comment]
After `git revert aaac48880d`  and rebuilding SPDK I don't see EAL messages anymore when booting VMs and IO data transfer errors are gone too.

**Comment by jimharris** [comment]
Thanks @karlatec.  Seems like we should revert this commit for now and continue debugging offline.

**Comment by jimharris** [comment]
Revert:  https://review.spdk.io/gerrit/c/spdk/spdk/+/7424

**Comment by benlwalker** [comment]
DPDK has a limit of 256 registrations. It's hard coded. I don't see a way to make this work with that limit in place.

**Comment by jimharris** [comment]
Revert merged.
