### ISSUE TITLE
undefined reference to `spdk_blobfs_bdev_mount' 

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1905]
## Current Behavior

SPDK compilation fails with:
```
00:19:50.195 /usr/bin/ld.bfd: /tmp/fuse.qhDZ4f.ltrans12.ltrans.o: in function `spdk_fuse_run':
00:19:50.195 <artificial>:(.text+0xcd4): undefined reference to `spdk_blobfs_bdev_mount'
00:19:50.195 collect2: error: ld returned 1 exit status
00:19:50.196 make[3]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.app.mk:67: fuse] Error 1
00:19:50.196 make[2]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.subdirs.mk:44: fuse] Error 2
00:19:50.198 make[1]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.subdirs.mk:44: blobfs] Error 2
00:19:50.198 make[1]: *** Waiting for unfinished jobs....
```

https://ci.spdk.io/public_build/autotest-nightly_2916.html

## Steps to Reproduce

1. Build SPDK with:
```
./configure --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio \
--with-iscsi-initiator --with-nvme-cuse --with-pmdk --with-reduce --with-rbd \
--with-crypto --with-ocf --enable-ubsan --enable-asan --enable-coverage \
--with-fuse --with-raid5 --with-vfio-user --with-uring --enable-lto

This is from nightly unittest job; I believe  --enable-lto --with-rbd --with-fuse should suffice.
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK `2fd233413b spdk_top: check if SPDK target app has been initialized`
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
fedora31.localdomain 5.6.11-200.fc31.x86_64

**Comment by jimharris** [comment]
I'm not able to reproduce this on my system, but I'm running Ubuntu with gcc 9.1.  The test/blobfs/fuse/Makefile looks right to me.

Can you confirm on this Fedora31+gcc 9.3.1 system that the reduced configure parameters reproduce the issue?
Can you also try removing --enable-lto?

Either way, with a failing case, can you run:

```
Q= make
```

and attach the full link command here.  blobfs_bdev library should be getting linked in, but I'd like to confirm.

**Comment by karlatec** [comment]
TBH I did not run this manually before, so I did not check the short version. I cannot reproduce this manually with configure + make, even with all these configuration options.
I am pretty sure that this build fails because of `run_test "build_rpms" build_rpms` in `autopackage.sh`. The build with LTO runs just after this test. If I comment `build_rpms` then there's no error from ld.

**Comment by karlatec** [comment]
Fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/7562

**Comment by karlatec** [comment]
https://ci.spdk.io/public_build/autotest-nightly_2930.html (results should upload shortly)

**Comment by jimharris** [comment]
Patch merged.  Thanks @karlatec!
