### ISSUE TITLE
nvmf: `make run` fails in `nvme-cli/tests`

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#1907]
## Expected Behavior
`make run` should succeed (?)

## Current Behavior
`make run` fails in `nvme-cli/tests` with lots of errors. Log file attached. I don't know whether these tests are correct in the first place, maybe worth looking into.

## Steps to Reproduce

1.  Clone https://github.com/linux-nvme/nvme-cli and enter `tests`. Make sure to install the dependencies documented in `tests/README`. The tests seem broken with Python 2, the work fine with Python 3.
2. `cd tests && make run` (No need to build anything). 

## Context (Environment including OS version, SPDK version, etc.)

Using SPDK de9f4857d085214c15f424b4aa1b1e95c7658549.

**Comment by tmakatos** [comment]
[test.txt.gz](https://github.com/spdk/spdk/files/6365276/test.txt.gz)

**Comment by changpe1** [comment]
[Bug Scrub] This issue does exist, we will go through the failures one by one, some failures we will not fix it, e.g: format command.

**Comment by dong-liuliu** [comment]
@wumengjin Seems I can only find your name only after your first reply to any github issue

**Comment by changpe1** [comment]
I looked the issue, the namespace management commands are not supported, and most likely the SPDK NVMf library will not support it.  For other failures, there are two parts I think the NVMf library may add support for that:
1. Get Features with feature ID Interrupt Coalescing (Feature Identifier 08h) and Interrupt Vector Configuration (Feature Identifier 09h)
2. Identify with CNS 0x13 Controller list of controllers exist in the NVM subsystem

**Comment by tmakatos** [comment]
> I looked the issue, the namespace management commands are not supported, and most likely the SPDK NVMf library will not support it.

Is this command mandatory in NVMe?

**Comment by changpe1** [comment]
> > I looked the issue, the namespace management commands are not supported, and most likely the SPDK NVMf library will not support it.
> 
> Is this command mandatory in NVMe?

Namespace Management is optional in NVMe specification.

**Comment by jlevon** [comment]
Sounds like they're bugs in the test suite then - they should probably say "skipped" rather than "failed".

Although I think the list of controllers one is expected?

**Comment by changpe1** [comment]
> Sounds like they're bugs in the test suite then - they should probably say "skipped" rather than "failed".
> 
> Although I think the list of controllers one is expected?

SPDK nvmf is using dynamic controller, actually there should only one active controller for PCIe transport, I'm not sure it's useful or not.

**Comment by tmakatos** [comment]
@changpe1 FYI when I try to boot Windows from a regular disk with an NVMf/vfio-user disk attached I get the following:
```
[2021-06-18 09:44:04.706777] vfio_user.c: 995:consume_admin_cmd: *DEBUG*: /var/tmp/vfio-user//8b0915f2-ebd8-4f08-9170-2e38b3fe9c6a/nvme/8b0915f2-ebd8-4f08-9170-2e38b3fe9c6a: handle admin req opc=0x9 cid=66
[2021-06-18 09:44:04.706788] nvme_qpair.c: 238:nvme_admin_qpair_print_command: *NOTICE*: SET FEATURES INTERRUPT COALESCING cid:66 cdw10:00000008 PRP1 0x0 PRP2 0x0                                                                              
[2021-06-18 09:44:04.706815] ctrlr.c:2791:nvmf_ctrlr_set_features: *ERROR*: Set Features command with unsupported feature ID 0x08
[2021-06-18 09:44:04.706841] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:0 cid:66 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
```
Maybe related?

**Comment by changpe1** [comment]
> @changpe1 FYI when I try to boot Windows from a regular disk with an NVMf/vfio-user disk attached I get the following:
> 
> ```
> [2021-06-18 09:44:04.706777] vfio_user.c: 995:consume_admin_cmd: *DEBUG*: /var/tmp/vfio-user//8b0915f2-ebd8-4f08-9170-2e38b3fe9c6a/nvme/8b0915f2-ebd8-4f08-9170-2e38b3fe9c6a: handle admin req opc=0x9 cid=66
> [2021-06-18 09:44:04.706788] nvme_qpair.c: 238:nvme_admin_qpair_print_command: *NOTICE*: SET FEATURES INTERRUPT COALESCING cid:66 cdw10:00000008 PRP1 0x0 PRP2 0x0                                                                              
> [2021-06-18 09:44:04.706815] ctrlr.c:2791:nvmf_ctrlr_set_features: *ERROR*: Set Features command with unsupported feature ID 0x08
> [2021-06-18 09:44:04.706841] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:0 cid:66 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
> ```
> 
> Maybe related?

Yes, I think the two features are required, because from Guest's view, it's a PCIe drive.

**Comment by tmakatos** [comment]
BTW, shouldn't the `nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:0 cid:66 cdw0:0 sqhd:0000 p:0 m:0 dnr:0` message be warning?

**Comment by changpe1** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/8765 and https://review.spdk.io/gerrit/c/spdk/spdk/+/8766 will address the noise logs.

**Comment by changpe1** [comment]
Get Features with feature ID Interrupt Coalescing (Feature Identifier 08h) and Interrupt Vector Configuration (Feature Identifier 09h) is supported now, so closing this issue for now.
