### ISSUE TITLE
-Werror=unused-result when building in  thread.c busy_poller_set_interrupt_mode()

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1910]
## Current Behavior

Compliation fail during autopackage.sh build without debug and with enabled lto.
https://ci.spdk.io/public_build/autotest-nightly_2949.html

## Steps to Reproduce

1. SPDK built with 
```
./configure --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --enable-ubsan --enable-asan --enable-coverage --without-isal --enable-lto
```
2.
```
00:09:11.379 thread.c: In function ‘busy_poller_set_interrupt_mode’:
00:09:11.379 thread.c:1132:3: error: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Werror=unused-result]
00:09:11.379  1132 |   read(busy_efd, &notify, sizeof(notify));
00:09:11.379       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK `365db9ee48 sock/posix: Deal with hung I/O with MSG_ZEROCOPY and interrupt suppression`
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
fedora31.localdomain 5.6.11-200.fc31.x86_64

**Comment by yidong0635** [comment]
Jim‘s patch has been merged ：https://review.spdk.io/gerrit/c/spdk/spdk/+/7593 . Please rebase the code.

**Comment by karlatec** [comment]
Thanks @yidong0635 , I did not notice it.

**Comment by yidong0635** [comment]
I'm also not notice about it and happy to submit a duplicated patch. :)
