### ISSUE TITLE
Unrelated CI test fail due to "Not all tests were run. Failing the build." 

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1911]
## Current Behavior

Some of the CI tests failed due to "Not all tests were run. Failing the build." even though tested change had nothing to do with changing the tests.

## Possible Solution

None, already resolved. This was caused by CI misconfiguration resulting in some test jobs being run with wrong VM images.

**Comment by karlatec** [comment]
This was already fixed. Will re-trigger affected builds here and close the issue after couple of days.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43478.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43493.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43479.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_43498.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_43498.html

**Comment by changpe1** [comment]
closing this issue for now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: Not Found
