### ISSUE TITLE
Various CI jobs timeout on PE1-VM-Host test node

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1912]
## Current Behavior

Some of the CI tests failed due to timeout occurring especially on PE1-VM-Host test node.

## Possible Solution

None, already resolved. This was caused by CI misconfiguration resulting in some test jobs being run with wrong VM images.

**Comment by karlatec** [comment]
This was already fixed. Will re-trigger affected builds here and close the issue after couple of days.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43495.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43496.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43489.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43491.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43471.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43475.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43470.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_43469.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_43471.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_43495.html

**Comment by tomzawadzki** [comment]
>None, already resolved. This was caused by CI misconfiguration resulting in some test jobs being run with wrong VM images. 
Closing.
