### ISSUE TITLE
SPDK v21.01 vs OCF master various compilation failures

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1914]
## Steps to Reproduce

1. Checkout SPDK v21.01.x branch, update submodules
2. Change directory into OCF submodule directory. Change branch to master and pull latest sources.
3. Build SPDK with
```
cat ~/autorun-spdk.conf
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_RUN_UBSAN=1
SPDK_TEST_OCF=1
RUN_NIGHTLY=1

./autorun.sh ~/autorun-spdk.conf

(Above results in following configuration)
./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --with-ocf --enable-ubsan --enable-coverage --without-isal --with-ocf=//var/jenkins/workspace/ocf-master-vs-spdk-v21.01.x/spdk/build/ocf.a --with-shared
```
4. Build fails due to compilation errors:
```
00:00:48.146 In file included from stats.c:34:
00:00:48.146 ctx.h:51:2: error: unknown type name ‘env_atomic’
00:00:48.146    51 |  env_atomic                   refcnt;
00:00:48.146       |  ^~~~~~~~~~
00:00:48.147 make[3]: *** [/var/jenkins/workspace/ocf-master-vs-spdk-v21.01.x/spdk/mk/spdk.common.mk:399: stats.o] Error 1
00:00:48.147 make[3]: *** Waiting for unfinished jobs....
00:00:48.206   LIB libspdk_blobfs_bdev.a
00:00:48.206 In file included from ctx.c:39:
00:00:48.206 ctx.h:51:2: error: unknown type name ‘env_atomic’
00:00:48.206    51 |  env_atomic                   refcnt;
00:00:48.206       |  ^~~~~~~~~~
00:00:48.207 make[3]: *** [/var/jenkins/workspace/ocf-master-vs-spdk-v21.01.x/spdk/mk/spdk.common.mk:399: ctx.o] Error 1
00:00:48.211 In file included from vbdev_ocf.c:38:
00:00:48.211 ctx.h:51:2: error: unknown type name ‘env_atomic’
00:00:48.211    51 |  env_atomic                   refcnt;
00:00:48.211       |  ^~~~~~~~~~
00:00:48.212   SO libspdk_blobfs_bdev.so.2.0
00:00:48.212 make[3]: *** [/var/jenkins/workspace/ocf-master-vs-spdk-v21.01.x/spdk/mk/spdk.common.mk:399: vbdev_ocf.o] Error 1
00:00:48.218 data.c: In function ‘vbdev_ocf_data_alloc’:
00:00:48.218 data.c:43:9: error: implicit declaration of function ‘env_malloc’; did you mean ‘valloc’? [-Werror=implicit-function-declaration]
00:00:48.218    43 |  data = env_malloc(sizeof(*data), ENV_MEM_NOIO);
00:00:48.218       |         ^~~~~~~~~~
00:00:48.218       |         valloc
00:00:48.218 data.c:43:35: error: ‘ENV_MEM_NOIO’ undeclared (first use in this function)
00:00:48.218    43 |  data = env_malloc(sizeof(*data), ENV_MEM_NOIO);
00:00:48.218       |                                   ^~~~~~~~~~~~
00:00:48.218 data.c:43:35: note: each undeclared identifier is reported only once for each function it appears in
00:00:48.218 data.c:53:4: error: implicit declaration of function ‘env_free’ [-Werror=implicit-function-declaration]
00:00:48.218    53 |    env_free(data);
00:00:48.218       |    ^~~~~~~~
00:00:48.218 data.c: In function ‘vbdev_ocf_iovs_add’:
00:00:48.218 data.c:86:3: error: implicit declaration of function ‘SPDK_ERRLOG’ [-Werror=implicit-function-declaration]
00:00:48.218    86 |   SPDK_ERRLOG("IOV error\n");
00:00:48.218       |   ^~~~~~~~~~~
00:00:48.218 cc1: all warnings being treated as errors
00:00:48.219 make[3]: *** [/var/jenkins/workspace/ocf-master-vs-spdk-v21.01.x/spdk/mk/spdk.common.mk:399: data.o] Error 1
```

[SPDK-v2101-vs-ocf-master.txt](https://github.com/spdk/spdk/files/6377085/SPDK-v2101-vs-ocf-master.txt)

## Context (Environment including OS version, SPDK version, etc.)

SPDK ` 64f1ea8ea41 SPDK 21.01.2-pre`
OCF `2d625941657 Merge pull request #491 from mmichal10/tests-seq-cutoff-security`
gcc version 10.2.1 20200723 (Red Hat 10.2.1-1) (GCC) 
Fedora 32 5.7.17-200.fc32.x86_64

**Comment by karlatec** [comment]
@tomzawadzki FYI

**Comment by rafalste** [comment]
This is due to OCF 20.12.2 changes (SPDK 21.01 has OCF 20.3 included). But it is already fixed in latest SPDK with this patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/6413

**Comment by jimharris** [comment]
Patches have been pushed that would update OCF to a newer version, but looks like they still need some work: https://review.spdk.io/gerrit/c/spdk/spdk/+/7775

What is the long term strategy for handling these kinds of OCF updates in an LTS branch though?  Should we only support the OCF version that is pointed to by the SPDK submodule?  But still allow the option to specify an alternate version for development purposes.

**Comment by rafalste** [comment]
Hi @jimharris!
Yes, the only supported version of OCF in SPDK is the one pointed by a submodule. User of course can switch to desired version at any time but we cannot guarantee the usability of such configuration.
Broken compatibility may be due to various changes in OCF behavior or even OCF API which requires some further changes in OCF adapter in SPDK.

**Comment by rafalste** [comment]
I suggest to close this issue as the officially supported OCF version is the one pointed by SPDK submodule.
Other OCF versions may cause various problems and such configuration is considered experimental/non-stable.

**Comment by tomzawadzki** [comment]
In general testing latest SPDK against OCF master is useful to get ahead of required changes for next release. The same thing is done for compatibility between SPDK and DPDK. In the future such issues would be worth taking a look at.

This particular issue was reported against SPDK v21.01, but is resolved on latest SPDK via OCF update.
