### ISSUE TITLE
Spdk nvmf performmance

### ISSUE THREAD

**Issue by vinayakhegdev** [spdk/spdk#192]
Can you please point me of any latency related tests report done/published  with spdk nvmf.

**Comment by vinayakhegdev** [comment]
Answer for this would be appreciated.

**Comment by benlwalker** [comment]
We do not currently have any published latency numbers.

**Comment by zy-tough** [comment]
The following two reports may help.
(1) NVMe-over-Fabrics Performance Characterization and the Path to Low-Overhead Flash Disaggregation
(2) Accelerating NVMe-oF for VMs with the Storage Performance Development Kit
