### ISSUE TITLE
Can't download vhost_image

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1924]
# issue 
download link is invalid:

https://ci.spdk.io/download/test_resources/vhost_vm_image.tar.gz

**Comment by Comphix** [comment]
This is mentioned in the below

https://spdk.io/development/ and https://spdk.io/cn/development/ two webpages.

Is it also meaning we could not directly download it? Need the username and password?

vhost Tests
The vhost tests under test/vhost require the presence of a virtual machine image on the host machine. We have made a tarball containing a working vm image that is available for download *here*. Please feel free to download and use this image as the guest when running the vhost tests locally. The credentials are below:

uname: root
pass: root

**Comment by tomzawadzki** [comment]
The image is not provided intentionally now, as to avoid issues with maintenance of such images. The development page should be updated to reflect that.

There are detailed steps for anyone to create the same image located here https://github.com/spdk/spdk/blob/master/test/common/config/README.md#additional-steps-for-preparing-the-vhost-tests

**Comment by Comphix** [comment]
Thanks @tomzawadzki , in this case, we will need to update the development page.

**Comment by changpe1** [comment]
@tomzawadzki could you update the document? thanks

**Comment by tomzawadzki** [comment]
Sure, please see https://review.spdk.io/gerrit/c/spdk/spdk.github.io/+/7880

**Comment by tomzawadzki** [comment]
The EN page is now updated in patch above. @Comphix Could you update the CN page too ?

**Comment by Comphix** [comment]
Sure. I will handle the CN page. Thanks Tomek.

**Comment by Comphix** [comment]
The patch to update the Chinese page is below:

https://review.spdk.io/gerrit/c/spdk/spdk.github.io/+/7906

**Comment by jimharris** [comment]
Patches all merged.
