### ISSUE TITLE
Compile error for fuse.c on FreeBSD 

### ISSUE THREAD

**Issue by varun2784** [spdk/spdk#193]
$ gmake
  CC fuse/fuse.o
  LINK fuse/fuse
/usr/bin/ld: cannot find -ldl
cc: error: linker command failed with exit code 1 (use -v to see invocation)

FreeBsd doesn't have libdl.so. This can be omitted for FreeBSD

**Comment by dverkamp-intel** [comment]
This should be fixed as of 4454df7006940e2cc051ce62c5764f35826bc55d - thanks for the report!
