### ISSUE TITLE
Segfault in blobstore.c with spdk_tgt while playing with snapshots

### ISSUE THREAD

**Issue by jfgd** [spdk/spdk#1933]
I encounter a segfault with spdk_tgt app while I do the following lvol operations: 
 - lvol creation
 - 3 snapshots of that lvol
 - decouple_parent of lvol and last snapshot
 - delete lvol
 - delete last snapshot
 - *segfault*

The segfault happens all the time.
There is no IO (read or write) on those lvols.

## Expected Behavior

It should not segfault.

## Current Behavior

Segfault with the following back-trace:
```
#0  bs_blob_list_remove (blob=blob@entry=0x555555d35490) at blobstore.c:3159
#1  0x00005555555ae260 in bs_delete_open_cpl (cb_arg=0x555555cecd00, blob=0x555555d35490, 
    bserrno=<optimized out>) at blobstore.c:6826
#2  0x00005555555af3bc in bs_request_set_complete (set=<optimized out>) at request.c:90
#3  0x00005555555a514f in blob_load_final (ctx=0x555555cea160, bserrno=0) at blobstore.c:1314
#4  0x00005555555a9bbe in bs_open_blob (bs=0x555555ce7aa0, blobid=4294967300, opts=0x0, 
    cb_fn=0x5555555a5cc0 <blob_load_snapshot_cpl>, cb_arg=0x555555cea160) at blobstore.c:6939
#5  0x00005555555a0a0e in bdev_blob_io_complete (bdev_io=0x200006cc7a00, success=<optimized out>, 
    arg=<optimized out>) at blob_bdev.c:86
#6  0x000055555563fcee in msg_queue_run_batch (max_msgs=<optimized out>, thread=0x555555cc88c0)
    at thread.c:544
#7  thread_poll (thread=thread@entry=0x555555cc88c0, max_msgs=max_msgs@entry=0, 
    now=now@entry=8284562699354906) at thread.c:623
#8  0x0000555555640930 in spdk_thread_poll (thread=thread@entry=0x555555cc88c0, 
    max_msgs=max_msgs@entry=0, now=8284562699354906) at thread.c:733
#9  0x000055555563c049 in _reactor_run (reactor=0x555555cc84c0) at reactor.c:906
#10 reactor_run (arg=0x555555cc84c0) at reactor.c:944
#11 0x000055555563c417 in spdk_reactors_start () at reactor.c:1052
#12 0x0000555555639382 in spdk_app_start (opts_user=<optimized out>, 
    start_fn=0x555555582c10 <spdk_tgt_started>, arg1=0x0) at app.c:577
#13 0x000055555557e211 in main (argc=1, argv=0x7fffffffe578) at spdk_tgt.c:120

```

## Steps to Reproduce

1. Run spdk_tgt app (or nvmf_tgt):
```
sudo ./build/bin/spdk_tgt
```
2. Run the following RPC sequence:
```
./scripts/rpc.py bdev_malloc_create -b Malloc0 1024 512
./scripts/rpc.py bdev_lvol_create_lvstore Malloc0 lvs0
./scripts/rpc.py bdev_lvol_create -l lvs0 lva 64
./scripts/rpc.py bdev_lvol_snapshot lvs0/lva snap0
./scripts/rpc.py bdev_lvol_snapshot lvs0/lva snap1
./scripts/rpc.py bdev_lvol_snapshot lvs0/lva snap2
./scripts/rpc.py bdev_lvol_decouple_parent lvs0/lva
./scripts/rpc.py bdev_lvol_decouple_parent lvs0/snap2
./scripts/rpc.py bdev_lvol_delete lvs0/lva
./scripts/rpc.py bdev_lvol_delete lvs0/snap2
```
The issue happens during the last bdev_lvol_delete

## Context (Environment including OS version, SPDK version, etc.)

Tested on master branch (e3997dc23b212aa7b3c1ad73d517e3c92a68dbbf) on Ubuntu 20.04

**Comment by KKaras169169** [comment]
I was able to reproduce this issue on my setup as well.

**Comment by tomzawadzki** [comment]
Patch fixing this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/8420.

When investigating this, @ksztyber noticed another issue for similar https://github.com/spdk/spdk/issues/2028.

**Comment by jimharris** [comment]
Patch has been merged.  This issue can be closed, but should we also close #2028?

**Comment by ksztyber** [comment]
@jimharris, no it's a different issue that isn't addressed by Tomek's patch.

**Comment by optimistyzy** [comment]
> @jimharris, no it's a different issue that isn't addressed by Tomek's patch.

Hi @ksztyber, So let's reopen this issue? Thanks

**Comment by ksztyber** [comment]
Hi @optimistyzy, I was talking about #2028, not this one. I think we need to keep #2028 open, but this one should be closed.
