### ISSUE TITLE
vhost_blk.c: 569:process_blk_task: *ERROR*: vhost.100s0: request with idx '5' is already pending.

### ISSUE THREAD

**Issue by yuhongxiao123456** [spdk/spdk#1934]
![image](https://user-images.githubusercontent.com/71329144/117537160-d64a1f00-b031-11eb-8ac7-56e8b069d8c2.png)_blk.c: 569:process_blk_task: *ERROR*: vhost.100s0: request with idx '5' is already pending.
## Expected Behavior

On the VM, use fio to test the virtio-blk performance.virtio-blk bankend is the vhost of spdk and bdev is the ceph rbd.
## Current Behavior

The FIO test fails, and the SPDK Vhost outputs a pending error.

## Steps to Reproduce

1.  vhost start
2.  virsh start vm
3.  fio test

fio config:
[grobal]
ioengine=libaio
direct=1
numjobs=1
#ramp_time=20
#log_avg_msec=500
thread
filename=/dev/vdb
bs=4k
size=10240M
rw=randrw
rwmixwrite=30
rwmixread=70
iodepth=128
runtime=60
time_based
#stonewall

## Context (Environment including OS version, SPDK version, etc.)
OS:Centos7.6
SPDK:20.07
libvirt:7.1.0
qemu:5.2.90

**Comment by changpe1** [comment]
Do you see any error logs in the Ceph RBD part? I assume this may related with Ceph.

**Comment by yuhongxiao123456** [comment]
This one came up by accident. I remember this problem when bdev is ramdisk. I'll try to reproduce it later and provide the corresponding test steps.
Thank you.

**Comment by optimistyzy** [comment]
@yuhongxiao123456 is there any new clue for this issue?

**Comment by yuhongxiao123456** [comment]
I‘m sorry，it's no recurrence. I will close this issue.
If it reappears in the future, then record the detailed information.
