### ISSUE TITLE
NVMe/TCP TLS support

### ISSUE THREAD

**Issue by ericcurtin** [spdk/spdk#1939]
## Expected Behavior

I'm working on it in a personal branch. Would you guys be happy to review this when complete?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ericcurtin** [comment]
I'm using openssl at the moment. It made sense because it was linked in already (lcrypto, just had to add lssl).

**Comment by ericcurtin** [comment]
> Yes that sounds great. Are you planning to use one of the SSL libraries? kTLS?

On ktls, I think we may get that with minimal effort once openssl is done, will look into that in more detail later. If you build openssl with ktls enabled, I think the library might handle the ktls calls.

**Comment by ericcurtin** [comment]
If anyone wants a peek at this before it hits gerrit, I'm pushing here:

https://github.com/spdk/spdk/compare/master...ericcurtin:tls_support

it's messy at the moment though, doesn't work yet. It should be cleaner when it hits gerrit.

**Comment by jimharris** [comment]
Hi @ericcurtin,

Thanks!  I took a peek and have a few questions and/or suggestions.  Maybe some of this you're already planning to clean up before pushing to Gerrit.

1) We need to be able to support both normal TCP and TLS connections at the same time.  So the TLS ifdefs won't be a long-term option.
2) How will TLS be configured?  For example, will nvme_subsystem_add_listener add parameters for TLS?
3) How will the SSL certificate be specified?
4) I would suggest starting to run scripts/check_format.sh on your patches now to make sure the changes are all inline with SPDK style guidelines.
5) How will we test TLS in SPDK CI?

Thanks,

Jim

**Comment by peluse** [comment]
Additionally what parameters you are using to generate the key pair/cert?

**Comment by ericcurtin** [comment]
> 1. We need to be able to support both normal TCP and TLS connections at the same time. So the TLS ifdefs won't be a long-term option.

Yeah I thought about this, will need a few command line switches to specify things like tls 1.2/1.3 what the psk is, etc. Would it be reasonable to do whatever openssl does for command line args? I'm using the ifdefs until something is working.

> 2. How will TLS be configured? For example, will the nvmf_subsystem_add_listener RPC add parameters for TLS?

Good question, I don't know yet.

> 3. How will the SSL certificate be specified?

No certs supported in the TP yet for NVMe/TCP/TLS only PSK mode.

> 4. I would suggest starting to run scripts/check_format.sh on your patches now to make sure the changes are all inline with SPDK style guidelines.

Ok

> 5. How will we test TLS in SPDK CI?

I'd hope to run the same test suite as is run generally for NVMe/TCP, except in TLS mode, any guidance would be appreciated.

> Additionally what parameters you are using to generate the key pair/cert?

Only PSK mode in the TP at the moment.

**Comment by jimharris** [comment]
Thanks @ericcurtin.

I think once you get it working, go ahead and push it to Gerrit, even if it has ifdefs and no RPC configuration.  We can start answering some of these questions during the review process once we see the working implementation.

I agree that we should be able to use existing NVMe/TCP tests for TLS, it will need some plumbing but no major blockers from my perspective.  We will just be limited to using the SPDK initiator for TLS testing since the kernel NVMe driver doesn't support it.

**Comment by ericcurtin** [comment]
Some info on ktls with OpenSSL https://github.com/openssl/openssl/issues/14595

**Comment by KariukiJ** [comment]
@ericcurtin Are you doing TLS 1.2? Or are you shooting for 1.3?

**Comment by ericcurtin** [comment]
I'm shooting for 1.3 at the moment, but 1.2 should be easy to add after that if required.

**Comment by KariukiJ** [comment]
> I'm shooting for 1.3 at the moment, but 1.2 should be easy to add after that if required.

1.3 hasn't been approved. Looks like the TP 8011 is pending. Are you aligning your schedule with the TP approval timeline?

**Comment by ericcurtin** [comment]
Does 1.2 suit @KariukiJ ?

**Comment by ericcurtin** [comment]
I made progress here until the point where the TLS connection is completed and we are starting to run IO. Some small bits of IO run through, but I mostly hit this state. I'll get there soon I think. I'm doing without zerocopy and such for now, just SSL_write and SSL_read calls with wrappers for the iovec versions of those calls, etc.

"Write completed with error (sct=0, sc=8)
starting I/O failed
Write completed with error (sct=0, sc=8)
starting I/O failed
        0 IOPS,     0.00 MiB/s"

**Comment by jimharris** [comment]
If you run perf for 60 seconds let's say, do you see these errors immediately, or only at the end of the 60 seconds?

sct=0 means generic command status code type
sc=8 means "command aborted due to SQ deletion"

So this sc is probably being generated by the nvme driver in perf, either as part of freeing the io qpair, or some kind of error condition on the TCP socket when there are outstanding I/O.

Any other log messages, from perf or the SPDK target?

**Comment by ericcurtin** [comment]
Just that log message looks different on the perf side, no odd logs on the other side. That sc error is the only difference I see to the normal TCP mode, although my code is flooded with temp logging for myself, just trying to figure out how this codebase works. If you'd like to pull my branch above. I basically run:

./target.sh

in one terminal and:

./host.sh 

in the other. If you want to run without TLS, you can still do it, by running:

./target.sh n

and it recompiles in unencrypted TCP mode.

I normally have two repos I am using in parallel (4 terminals in total) to compare TLS vs non-TLS TCP.

**Comment by ericcurtin** [comment]
> If you run perf for 60 seconds let's say, do you see these errors immediately, or only at the end of the 60 seconds?

Almost immediately, I get some IOPS, etc. for a few milliseconds, but everything quickly goes to zero then.

**Comment by jimharris** [comment]
But do you get the "Write completed with error" messages after a few milliseconds?  Or do those come later?

**Comment by ericcurtin** [comment]
> But do you get the "Write completed with error" messages after a few milliseconds? Or do those come later?

Instantly, before the IOPS even appear, Then I will get a very small number of IOPS displayed like 411, then to zero infinitely.

**Comment by KariukiJ** [comment]
> Does 1.2 suit @KariukiJ ?

@ericcurtin We usually align the schedule for new features with the TP approval. So it more a question of the state TP 8011 when you are ready for release. As far as version 1.2 goes, TP 8011 discourages that version due to security flaws, therefore, I don't think we should be looking at 1.2 at all.

**Comment by peluse** [comment]
@ericcurtin any movement on this? Just curious, someone was asking about the feature on Slack

**Comment by ericcurtin** [comment]
Hi Guys,

I just heard from him he messaged. Sorry I should have dropped a note on this sooner. I left the storage industry to take up an opportunity in the automotive industry, so my focus has been more on that and finishing my masters thesis ever since.

So:

https://github.com/ericcurtin/spdk/tree/tls_support

is where I left it. I was running target.sh and host.sh scripts to test. It connects and run IO, but the IOPS seen are very limited, there is more work to do. There's a few memory cleanups also.

I'd be happy to give a quick demo sometime to you guys, it's unlikely I'll get around to finishing this because I want to give my new role in automotive my full commitment.

It's fairly standard openssl TLS 1.3 PSK boilerplate code with SSL_read() and SSL_write() function calls replacing the reads/recvs and sends/writes respectively.

**Comment by glimchb** [comment]
I picked up and pushed to gerrit for review https://review.spdk.io/gerrit/c/spdk/spdk/+/12327

**Comment by jimharris** [comment]
> I picked up and pushed to gerrit for review https://review.spdk.io/gerrit/c/spdk/spdk/+/12327

Thanks @glimchb!

For those interested, here's a link to the Slack thread in progress on this patch set:

https://spdk-team.slack.com/archives/CNRUQN85P/p1650542652729249

**Comment by glimchb** [comment]
@jimharris @tomzawadzki can you please close this issue ? we merged NVMe/TCP TLS support here https://github.com/spdk/spdk/commit/2fb5ff4985d5d7020f284a78202b5181cd4ec1ea

**Comment by ericcurtin** [comment]
Go @glimchb 🎉🎉🎉 I'm glad someone got to this. Felt guilty not finishing it, I just had too much on my plate. Stuck in libcamera/graphics world now. I hope my start was at least somewhat helpful. Funnily enough this could be helpful in an automotive context in future. Intercepting data in transit between an ECU and a automotive storage device is probably more likely than in a data centre.
