### ISSUE TITLE
[Centos 8][SPDK Vhost]{CLX Wolfpass Server} bdev_nvme_attach_controller failed if vfio driver loaded onto NVMe controller

### ISSUE THREAD

**Issue by ZHENJIZHAO** [spdk/spdk#1940]
## Expected Behavior

1. Load vfio driver onto nvme controller by using HUGEMEM=16384 ./scripts/setup.sh
2. Execute "./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 10000:01:00.0" shall return a message like "Nvm0n1"

## Current Behavior
Execute the command line above will return,

- nvme.c: 818:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
- bdev_nvme_create: *ERROR* No controller was found with provided trid(traddr: 10001:01:00.0)

This b/d/v is displayed correctly by executing "lspci | grep Non".

## Possible Solution
Turn off the vfio driver on BIOS setup screen, then nvme controller will load uio_pci_generic driver. 
On the same system, the bdev/nvme_create will work successfully as expected.

## Steps to Reproduce

1. HUGEMEM=16384 ./scripts/setup.sh
2. ./build/bin/vhost -S /var/tmp -s1024 -m0x3 & -> then <CTRL +C>
3../scripts/rpc.py bdev_nvme_attach_controller -b NVMe0 -t pcie -a 10000:01:00.0
4. lspci | grep Non

Refer to vhost link: https://spdk.io/doc/vhost.html
## Context (Environment including OS version, SPDK version, etc.)
OS: Centos 8.2
SPDK: build from the latest master branch

**Comment by ZHENJIZHAO** [comment]
The screenshots of vfio failure.
![image](https://user-images.githubusercontent.com/45022230/118110457-ffddbe80-b414-11eb-971a-1b5ecf7746c9.png)
![image](https://user-images.githubusercontent.com/45022230/118110502-0bc98080-b415-11eb-8df3-13b914672a53.png)
![image](https://user-images.githubusercontent.com/45022230/118110524-14ba5200-b415-11eb-8894-99103c0949f7.png)

The screenshots of uio pci generic success case.
![image](https://user-images.githubusercontent.com/45022230/118110616-374c6b00-b415-11eb-83ea-bbca65998b7b.png)

**Comment by jimharris** [comment]
Hi,

Unfortunately the Linux kernel does not support binding the vfio driver to devices behind a VMD endpoint.

Your options here are:

1) Disable IOMMU and use uio_pci_generic instead (as you mentioned in your report)
2) Disable VMD
3) Use the SPDK VMD driver.  See https://spdk.io/doc/vmd.html for additional information.

Closing this issue since the behavior here is expected, but please feel free to continue here with any questions.

Thanks,

Jim
