### ISSUE TITLE
[spdk.io homepage]https://spdk.io/doc/rpms.html can not be opened.

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#1942]
## Current Behavior
![image](https://user-images.githubusercontent.com/18566118/118235643-9ff42000-b4c7-11eb-9ca6-080fc8b96b40.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Comphix** [comment]
Looking at this issue.

**Comment by Comphix** [comment]
Raised a patch here https://review.spdk.io/gerrit/c/spdk/spdk.github.io/+/7945

**Comment by jimharris** [comment]
Hi @Comphix,

I don't think this patch will work.  The HTML is generated automatically based on latest markdown files in the doc/ directory in the main SPDK repository.  We never check in HTML directly or modify the navtree manually.

I think the real problem might be that rpm.md is not referenced from any of the other markdown files, but cannot say for sure.

-Jim

**Comment by Comphix** [comment]
Thanks Jim. Talked with @tomzawadzki earlier and he will work on this. Thanks Tomek!

**Comment by tomzawadzki** [comment]
Turns out this was bug on spdk/spdk.github.io, please see https://review.spdk.io/gerrit/c/spdk/spdk.github.io/+/8016
