### ISSUE TITLE
[Centos 8.2 as Host][Centos 7.5 as VM] [SPDK Vhost ][CLX Wolfpass Server] Failed to boot Centos 7.5 VM with error message "Dependency failed for /sysroot" message"

### ISSUE THREAD

**Issue by ZHENJIZHAO** [spdk/spdk#1943]
## Expected Behavior
Centos 7.5 VM shall boot up properly with SPDK vhost by using below command line.
"taskset -c 2,3 ../qemu/build/qemu-system-x86_64 --enable-kvm -smp 2 -m 1G -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 -drive file=/home/centos/c7.img,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=spdk_vhost_blk0,path=/var/tmp/vhost.1 -device vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=1 -monitor telnet::1111,server,nowait -net user,hostfwd=tcp::10020-:22 -net nic -vnc 0.0.0.0:2 -serial stdio"

## Current Behavior
Centos 7.5 VM will enter into emergency mode if running the above command line. With warning messages as below.
"Warning: /dev/disk/by-uuid/dce9a189-5640-48fc-875d-f44b3fd7e504 does not exist"

By executing cat /run/initrams/rdsosreport, there are quite a lot of messages as below.
<symlink '../../vda' '/dev/disk/by-id/virtio-Malloc.tmp-b253:0' failed: Not a directory>
...
<symlink '../../sda' '/dev/disk/by-id/ata-QEMU_HARDDISK_QM00003.tmp-b8:0' failed: Not a directory>
...
<Dependency failed for /sysroot.>
...
Please see attached 1.txt for more detail.
[1.txt](https://github.com/spdk/spdk/files/6477811/1.txt)

Please note: This is only seen when using Centos 7.5 as VM.
                    No issue seen on Centos 8.2/8.3 and Fedora 34 server/desktop as VM.

## Possible Solution
The Centos 7.5 VM is able to boot up by removing vhost parameters as below.
taskset -c 2,3 ../qemu/build/qemu-system-x86_64 --enable-kvm -smp 2 -m 1G -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 -drive file=/home/centos/c7.img,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -monitor telnet::1111,server,nowait -net user,hostfwd=tcp::10020-:22 -net nic -vnc 0.0.0.0:2 -serial stdio

Please see the attached 2.txt for more detail.
[2.txt](https://github.com/spdk/spdk/files/6477830/2.txt)

## Steps to Reproduce

1. Enable VMD on BIOS setup (see 1.txt for more detail).
>  [root@localhost spdk]# lspci | grep Non
10000:01:00.0 Non-Volatile memory controller: Intel Corporation Device 4140
10000:02:00.0 Non-Volatile memory controller: Intel Corporation Device 4140
10001:01:00.0 Non-Volatile memory controller: Intel Corporation Device 4140
10001:02:00.0 Non-Volatile memory controller: Intel Corporation Device 4140

2. HUGEMEM=16384 ./scripts/setup.sh  (see 1.txt for more detail).
3. ./build/bin/vhost -S /var/tmp -s 1024 -m 0x03 &
4. ./scripts/rpc.py bdev_malloc_create 64 512 -b Malloc1
5.  ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 10000:01:00.0
6. ./scripts/rpc.py vhost_create_blk_controller --cpumask 0x02 vhost.1 Malloc1
7. taskset -c 2,3 ../qemu/build/qemu-system-x86_64 --enable-kvm -smp 2 -m 1G -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 -drive file=/home/centos/c7.img,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=spdk_vhost_blk0,path=/var/tmp/vhost.1 -device vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=1 -monitor telnet::1111,server,nowait -net user,hostfwd=tcp::10020-:22 -net nic -vnc 0.0.0.0:2 -serial stdio

## Context (Environment including OS version, SPDK version, etc.)

- Centos 8.2 as Host. 
- Qemu build from the latest master branch.
- SPDK build from the latest master branch.

Again, this issue only seen if using Centos 7.5, not Centos 8.2 and 8.3 and fedora 34. 
Besides, either the original Centos 7.5 kernel or updated kernel may see the failure.

It is weird that even the fd0 (floppy disk) module reports errors on the failure case. I disabled the floppy module however still unable to boot the Centos 7.5 VM.

**Comment by mikeBashStuff** [comment]
The issue here is with `systemd-udevd`. `/dev/disk` ends up being on a `DEVLINKS` list for the `/dev/vda` device which is wrong - this should be a directory holding all the symlinks. This happens since it improperly parses virtio's `serial` attribute which includes a space: `Malloc disk`. Since `systemd-udevd` creates `/dev/disk` as a symlink it's not able to populate other ones. If you remove the symlink, create the dir, trigger the uevents - so `udevd` can go through sysfs and populate `/dev/disk/` again - and then exit from the emergency shell, centos will boot just fine after `switch_root()`. It's likely a problem for older versions of systemd (like `219` which is used in centos7's initramfs) where `virtio` devices are not handled very well.

**Comment by mikeBashStuff** [comment]
With something like this:
```
diff --git a/module/bdev/malloc/bdev_malloc.c b/module/bdev/malloc/bdev_malloc.c
index 3f5f65e59..91c713e95 100644
--- a/module/bdev/malloc/bdev_malloc.c
+++ b/module/bdev/malloc/bdev_malloc.c
@@ -423,7 +423,7 @@ create_malloc_disk(struct spdk_bdev **bdev, const char *name, const struct spdk_
                malloc_disk_free(mdisk);
                return -ENOMEM;
        }
-       mdisk->disk.product_name = "Malloc disk";
+       mdisk->disk.product_name = "Malloc_disk";

        mdisk->disk.write_cache = 1;
        mdisk->disk.blocklen = block_size;
```
You could boot the centos7 just fine. That said, there's no need to change that in the spdk since `systemd` is able to handle such whitespaces just fine now.

**Comment by mikeBashStuff** [comment]
I think there's no action needed from the spdk side so I will proceed with closing this issue. :)
