### ISSUE TITLE
SPDK QEMU reports Write Zeroes failure

### ISSUE THREAD

**Issue by changpe1** [spdk/spdk#1945]
I enabled Write Zeroes support via patch https://review.spdk.io/gerrit/c/spdk/spdk/+/7876, and SPDK CI reported errors in
https://ci.spdk.io/results/autotest-per-patch/builds/47392/archive/nvme-vg-autotest/build.log.

1. Check out SPDK QEMU branch
2. Create NVMe image via qemu-img create -f raw /tmp/nvme.img 8G
3. Start QEMU with `-drive file=/tmp/nvme.img,format=raw,if=none,id=ns0 -device nvme,serial=500e38,drive=ns0,namespaces=3`
4. Running test/bdev/blockdev.sh "nvme" inside VM

can reproduce this issue easily.

This issue only happened with NVMe0n2 and NVMe0n3, NVMe0n1 is good.

I tested the above patch with QEMU upstream branch and tests can pass, so this issue may only related with SPDK QEMU branch and need to investigate more.

**Comment by changpe1** [comment]
This is QEMU error, a fix patch is submitted here https://review.spdk.io/gerrit/c/spdk/qemu/+/7989

**Comment by tomzawadzki** [comment]
Hi @changpe1 thanks for the patch !

@karlatec or @mikeBashStuff could we test the [QEMU patch ](https://review.spdk.io/gerrit/c/spdk/qemu/+/7989) with [bdev/nvme: add write zeroes support](https://review.spdk.io/gerrit/c/spdk/spdk/+/7876). If it passes, then provide the +1 verified vote to QEMU patch. So that it can later be merged and deployed ?

**Comment by mikeBashStuff** [comment]
@tomzawadzki Sure, will do.

**Comment by mikeBashStuff** [comment]
`unittest` job passed fine on my end with https://review.spdk.io/gerrit/c/spdk/spdk/+/7876 on board (spdk qemu built with https://review.spdk.io/gerrit/c/spdk/qemu/+/7989 on top), seems to be working fine then - +1ed.

**Comment by tomzawadzki** [comment]
@mikeBashStuff thanks, the patch is merged. Please let @changpe1 know once the QEMU with it is deployed so write zeroes patches can be rebased.

**Comment by mikeBashStuff** [comment]
@tomzawadzki @changpe1 spdk qemu was rebuilt on all of the vm hosts in the CI pool (3394706d77 should be on top). You should be able now to rebase your SPDK patch and see if it passes the tests. :)

**Comment by changpe1** [comment]
@mikeBashStuff thanks, I will have a try.

**Comment by changpe1** [comment]
issue gone after the QEMU patch, closing it now.
