### ISSUE TITLE
[spdk_top/POLLERS tab] Incorrect value inside Run count column for Timed and Paused pollers 

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#1947]
Timed and Paused pollers do not display run count correctly.

## Expected Behavior
Show appropriate run count values.

## Current Behavior
Timed and Paused pollers show zeros in the Run count column.

spdk_top screenshot:
![image](https://user-images.githubusercontent.com/49611974/118617026-86eab800-b7c2-11eb-91df-11d402eb66a7.png)

RPC call "thread_get_pollers" used in spdk_top:

{
  "tick_rate": 2800000000,
  "threads": [
    {
      "name": "app_thread",
      "id": 1,
      "active_pollers": [],
      "timed_pollers": [],
      "paused_pollers": []
    },
    {
      "name": "nvmf_tgt_poll_group_0",
      "id": 2,
      "active_pollers": [
        {
          "name": "nvmf_poll_group_poll",
          "state": "waiting",
          "run_count": 2655723013,
          "busy_count": 0
        }
      ],
      "timed_pollers": [
        {
          "name": "nvmf_poll_group_poll",
          "state": "waiting",
          "run_count": 2655723013,
          "busy_count": 0
        }
      ],
      "paused_pollers": [
        {
          "name": "nvmf_poll_group_poll",
          "state": "waiting",
          "run_count": 2655723013,
          "busy_count": 0
        }
      ]
    },
    {
      "name": "iscsi_poll_group_0",
      "id": 3,
      "active_pollers": [
        {
          "name": "iscsi_poll_group_poll",
          "state": "waiting",
          "run_count": 2655723010,
          "busy_count": 0
        }
      ],
      "timed_pollers": [
        {
          "name": "iscsi_poll_group_poll",
          "state": "waiting",
          "run_count": 2655723010,
          "busy_count": 0
        }
      ],
      "paused_pollers": [
        {
          "name": "iscsi_poll_group_poll",
          "state": "waiting",
          "run_count": 2655723010,
          "busy_count": 0
        }
      ]
    }
  ]
}

## Steps to Reproduce

1. launch SPDK application: ./build/bin/spdk_tgt
2. launch spdk_top: ./build/bin/spdk_top
3. switch to POLLERS tab ("2" key or "TAB")

**Comment by KKaras169169** [comment]
This happens, because pollers running on the same thread do not have unique name and thread_id in above case, and those two values are the only ones being checked when saving last_run_counter for later comparison and display with current run_count of each poller.

**Comment by tomzawadzki** [comment]
This is a bug in thread library listing only active_pollers, as all the types at once. See https://review.spdk.io/gerrit/c/spdk/spdk/+/7952

**Comment by shuhei-matsumoto** [comment]
Ah, this bug is my fault and sorry for this. Thank you for your finding and fixing.
