### ISSUE TITLE
Initialization failed due to VFIO exception and example execution failed

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1948]
1. We want to execute the example hello_world on latest release v21.04, but get some error messages during initialization,
the main messages are as follows :
`vfio group is not viable not all devices in iommu group bound to vfio or unbound`

We refer to section **Device access** of below page to try to fix this issue, but the same problem still occurs : 
https://spdk.io/doc/system_configuration.html

2. Then we use the setup.sh to select another driver uio_pci_generic but another problem occurred : 
```
[2021-05-18 19:43:50.905520] [ DPDK EAL parameters: [2021-05-18 19:43:50.905529] hello_world [2021-05-18 19:43:50.905534] -c 0x1 [2021-05-18 19:43:50.905538] --log-level=lib.eal:6 [2021-05-18 19:43:50.905543] --log-level=lib.cryptodev:5 [2021-05-18 19:43:50.905547] --log-level=user1:6 [2021-05-18 19:43:50.905552] --iova-mode=pa [2021-05-18 19:43:50.905556] --base-virtaddr=0x200000000000 [2021-05-18 19:43:50.905561] --match-allocations [2021-05-18 19:43:50.905567] --file-prefix=spdk0 [2021-05-18 19:43:50.905573] --proc-type=auto [2021-05-18 19:43:50.905577] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attaching to 0000:02:00.0
[2021-05-18 19:44:23.369962] nvme_ctrlr.c:3298:nvme_ctrlr_process_init: *ERROR*: [0000:02:00.0] Initialization timed out in state 8
[2021-05-18 19:44:23.370010] nvme.c: 710:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:02:00.0
[2021-05-18 19:44:23.370020] nvme_pcie_common.c: 703:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2021-05-18 19:44:23.370029] nvme_qpair.c: 250:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) qid:0 cid:23 nsid:0 cdw10:00000001 cdw11:00000000 PRP1 0x3365c7000 PRP2 0x0
[2021-05-18 19:44:23.370036] nvme_qpair.c: 455:spdk_nvme_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) qid:0 cid:23 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2021-05-18 19:44:23.370045] nvme_ctrlr.c:1548:nvme_ctrlr_identify_done: *ERROR*: [0000:02:00.0] nvme_identify_controller failed!
[2021-05-18 19:44:23.370051] nvme_ctrlr.c: 921:nvme_ctrlr_fail: *ERROR*: [0000:02:00.0] in failed state.
no NVMe controllers found
```
It looks like an error occurred in the identify controller command, so I tried to execute this command with a nvme-cli,
the execution result was successful, I don’t understand why there is an error, the following are my test steps : 

a. compile the source code into shared libraries
```
./configure --with-shared
make
```
b. binding device to driver uio_pci_generic 
`DRIVER_OVERRIDE=uio_pci_generic ./setup.sh`

c. running example hello_world
```
ldconfig -v -n ./build/lib
LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib/ ./build/examples/hello_world
```

How can I solve these problems about each of the two drivers, thanks!

**Comment by Comphix** [comment]
It seems that the SSD initialization met some issue:

[2021-05-18 19:44:23.369962] nvme_ctrlr.c:3298:nvme_ctrlr_process_init: *ERROR*: [0000:02:00.0] Initialization timed out in state 8
[2021-05-18 19:44:23.370010] nvme.c: 710:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:02:00.0

Any log reported on dmesg?

**Comment by ryderhsu0129** [comment]
@Comphix 

dmesg is displayed as follows :
```
[  267.632706] DMAR: DRHD: handling fault status reg 2
[  267.632709] DMAR: [DMA Read] Request device [02:00.0] PASID ffffffff fault addr 36dde2000 [fault reason 06] PTE Read access is not set
```

It looks like something is abnormal, do you know what caused it? thanks!

**Comment by Comphix** [comment]
Is kernel nvme driver working properly for this SSD? Also what's the information of this SSD like vendor, type and etc?

**Comment by ryderhsu0129** [comment]
> Is kernel nvme driver working properly for this SSD? Also what's the information of this SSD like vendor, type and etc?

This SSD(Samsung 1725a) can work normally on the kernel nvme driver.

**Comment by ryderhsu0129** [comment]
I modify parameter intel_iommu=off in the GRUB file, execution result of example hello_world was successful.
What I am confused about is that I have used the driver uio_pci_generic, why it still seems to be related to IOMMU setting(intel_iommu).
Can I still run the example successfully without modifying this parameter?

**Comment by Comphix** [comment]
In the link you mentioned in the issue description, for the UIO, it is suggested:

"However, some devices do not function correctly when bound to vfio-pci and instead must be attached to the uio_pci_generic kernel driver. In that case, users should take care to disable the IOMMU or to set it into passthrough mode prior to running scripts/setup.sh.

To disable the IOMMU or place it into passthrough mode, add intel_iommu=off or amd_iommu=off or intel_iommu=on iommu=pt to the GRUB command line on x86_64 system, or add iommu.passthrough=1 on arm64 systems."

In this case, if using UIO, either turn off iommu or turn on the passthrough setting.

**Comment by jimharris** [comment]
Hi,

```
vfio group is not viable not all devices in iommu group bound to vfio or unbound
```

Let's see if there are other devices are in this iommu group.  Can you try:

```
ls /sys/bus/pci/devices/0000:02:00.0/iommu_group/devices
```

-Jim

**Comment by ryderhsu0129** [comment]
> In the link you mentioned in the issue description, for the UIO, it is suggested:
> 
> "However, some devices do not function correctly when bound to vfio-pci and instead must be attached to the uio_pci_generic kernel driver. In that case, users should take care to disable the IOMMU or to set it into passthrough mode prior to running scripts/setup.sh.
> 
> To disable the IOMMU or place it into passthrough mode, add intel_iommu=off or amd_iommu=off or intel_iommu=on iommu=pt to the GRUB command line on x86_64 system, or add iommu.passthrough=1 on arm64 systems."
> 
> In this case, if using UIO, either turn off iommu or turn on the passthrough setting.

@Comphix 
I get it, thank you for your reply.

**Comment by ryderhsu0129** [comment]
> Hi,
> 
> ```
> vfio group is not viable not all devices in iommu group bound to vfio or unbound
> ```
> 
> Let's see if there are other devices are in this iommu group. Can you try:
> 
> ```
> ls /sys/bus/pci/devices/0000:02:00.0/iommu_group/devices
> ```
> 
> -Jim

@jimharris 

There are indeed other devices in the same IOMMU group. 
Is there an easy way to circumvent this restriction so that the VFIO driver can be used?
or I can only use the UIO driver.

**Comment by jimharris** [comment]
Depending on your system and SSD, you might try plugging your SSD into a different PCIe slot.  You should also look at the other devices that are in the iommu_group to understand the PCIe topology.

Depending on the other devices in the iommu_group, you could try also attaching those devices to vfio.

Posting full ```lspci -vvv``` and ```lspci -t``` contents, as well as the output of the ls command above would make it easier to assist you.

**Comment by ryderhsu0129** [comment]
> Depending on your system and SSD, you might try plugging your SSD into a different PCIe slot. You should also look at the other devices that are in the iommu_group to understand the PCIe topology.
> 
> Depending on the other devices in the iommu_group, you could try also attaching those devices to vfio.
> 
> Posting full `lspci -vvv` and `lspci -t` contents, as well as the output of the ls command above would make it easier to assist you.

Thanks for your suggestion, I probably know how to do it.

**Comment by recklessnl** [comment]
> > Depending on your system and SSD, you might try plugging your SSD into a different PCIe slot. You should also look at the other devices that are in the iommu_group to understand the PCIe topology.
> > Depending on the other devices in the iommu_group, you could try also attaching those devices to vfio.
> > Posting full `lspci -vvv` and `lspci -t` contents, as well as the output of the ls command above would make it easier to assist you.
> 
> Thanks for your suggestion, I probably know how to do it.

 Would you share your knowledge about how you fixed it? This would be great for documentation purposes.
