### ISSUE TITLE
[spdk.io homepage]https://spdk.io/releases/ has several spaces before red-colored characters

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#1952]
The page of https://spdk.io/releases/ **with red colored characters has several spaces** before it. Tested on Chrome/IE/MS Edge, has the same phenomenon.
## Current Behavior
![image](https://user-images.githubusercontent.com/18566118/118928459-d3c2c000-b975-11eb-9b08-65a9824cc4fa.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Comphix** [comment]
The markdown looks like having no problem:

The version names are in the format `YY.MM.vv`, where `YY` is year, `MM` is month, and `vv` is a minor version number and is often omitted.

Not sure why it is shown with spaces before the `YY.MM.vv`

**Comment by wanqunintel** [comment]
it seems this is the format issue

**Comment by changpe1** [comment]
Closing this issue for now.
