### ISSUE TITLE
[new feature] spdk_top cannot create long time csv result as iostat.py that can be imported into grafana 

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#1956]
## Expected Behavior
it will be great that spdk_top can have one script version that is very similar with iostat.py, it can dump CPU usage on every interval. the result can be csv format. that can be uploaded into grafana 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomzawadzki** [comment]
Please note that this would not be related to spdk_top. The RPCs (`framework_get_reactors`, `thread_get_stats` and `thread_get_pollers`) are available to get from any SPDK application based on event framework.

Are you interested in adding a script that would periodically request that data and translate JSON output to CSV ?

**Comment by gaowayne** [comment]
> Please note that this would not be related to spdk_top. The RPCs (`framework_get_reactors`, `thread_get_stats` and `thread_get_pollers`) are available to get from any SPDK application based on event framework.
> 
> Are you interested in adding a script that would periodically request that data and translate JSON output to CSV ?

Yes, because spdk_top cannot do this. I think it will be great add one script like iostat.py to periodically dump cpu usage to CSV, need do some match based on the json data, not just simple output to CSV.

**Comment by changpe1** [comment]
@gaowayne assign this issue to you now.

**Comment by gaowayne** [comment]
> @gaowayne assign this issue to you now.

changpe, :( I plan to work on this. but truly too busy. I am looking forward SPDK main team can create this thing, then we can use directly. :)

**Comment by tomzawadzki** [comment]
It has been over a year since the original report. If you feel like this is worthy addition, please re-open the issue.
