### ISSUE TITLE
test/vhost/fio/fio.sh doesn't seem to be used

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1957]
## Expected Behavior
test/vhost/fio/fio.sh shall be used.

## Current Behavior
I can't find where test/vhost/fio/fio.sh be used.

## Possible Solution
We may remove test/vhost/fio/fio.sh

## Steps to Reproduce
N/A

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit ed2942461da5d929df1611a705fa3ceeda4d0da9

**Comment by mikeBashStuff** [comment]
This was added as part of 236dbd955080e921c44805362fc3c1dbc76fb2cf but not put into any top wrappers - from the commit message it seems like it was added for quick, manual use. We do have `test/vhost/fiotest/fio.sh` which performs similar job and which is currently running under CI. We could either remove `test/vhost/fio` or merge it with `test/vhost/fiotest` (that said, it feels a bit redundant so I would opt for removing it unless we want to just keep it "as-is" in case there are still users actively using this script). :)

**Comment by changpe1** [comment]
[Bug Scrub] let's keep the scripts here, closing this issue now.
