### ISSUE TITLE
SPDK perf can not run without root privilege under SLES-15-SP2

### ISSUE THREAD

**Issue by sun-mingbao** [spdk/spdk#1958]
SPDK perf can not run without root privilege under SLES-15-SP2.
However, when running with the root account, everything is OK.

## Steps to Reproduce

Following are the logs of a reproduction:

layton-dirt:/home/admin # whoami
root
layton-dirt:/home/admin # ls -l /dev | grep huge
drwxrwxrwx 2 root root           0 May 24 06:11 hugepages
layton-dirt:/home/admin # rm -rf /dev/hugepages/*
layton-dirt:/home/admin # 
layton-dirt:/home/admin # ./perf  -s 512 -r 'trtype:RDMA adrfam:IPv4 traddr:169.254.85.7 trsvcid:4420' -t 5  -w write -o 4096  -c 0x1 -P 1  -q 32
Starting SPDK v20.04.1 git sha1 5536f6635 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 512 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=va --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid55009 ]
EAL: No available hugepages reported in hugepages-1048576kB
--iova-mode is VA
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 169.254.85.7:4420: testnqn_1
Associating RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 6 with lcore 0
Associating RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 5 with lcore 0
Associating RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 4 with lcore 0
Associating RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 3 with lcore 0
Associating RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 2 with lcore 0
Associating RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                                                 Latency(us)
Device Information                                           :       IOPS      MiB/s    Average        min        max
RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 1 from core  0:   98163.80     383.45     325.98     149.06    7431.17
RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 2 from core  0:   96676.60     377.64     331.00     157.34    7405.81
RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 3 from core  0:   98251.00     383.79     325.68     149.16    6133.35
RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 4 from core  0:   96076.60     375.30     333.05     161.29    7863.25
RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 5 from core  0:   97936.80     382.57     326.72     153.46    5990.01
RDMA (addr:169.254.85.7 subnqn:testnqn_1) NSID 6 from core  0:   97909.20     382.46     326.81     156.95    6447.46
========================================================
Total                                                        :  585014.00    2285.21     328.18     149.06    7863.25

layton-dirt:/home/admin # 
layton-dirt:/home/admin # 
layton-dirt:/home/admin # 
layton-dirt:/home/admin # rm -rf /dev/hugepages/*
layton-dirt:/home/admin # 
layton-dirt:/home/admin # exit
exit
admin@layton-dirt:~> whoami
admin
admin@layton-dirt:~> ./perf  -s 512 -r 'trtype:RDMA adrfam:IPv4 traddr:169.254.85.7 trsvcid:4420' -t 5  -w write -o 4096  -c 0x1 -P 1  -q 32
Starting SPDK v20.04.1 git sha1 5536f6635 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 512 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=va --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid55594 ]
EAL: No available hugepages reported in hugepages-1048576kB
--iova-mode is VA
Initializing NVMe Controllers
nvme_rdma.c: 986:nvme_rdma_mr_map_notify: *ERROR*: ibv_reg_mr() failed
nvme_rdma.c:1052:nvme_rdma_register_mem: *ERROR*: spdk_mem_map_alloc() failed
nvme_rdma.c:1185:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to register memory for RDMA
nvme_rdma.c:1817:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
nvme_fabric.c: 119:nvme_fabric_prop_get_cmd: *ERROR*: Property Get failed
nvme_ctrlr.c: 797:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
nvme_qpair.c: 399:nvme_qpair_abort_queued_reqs: *ERROR*: aborting queued i/o
nvme_qpair.c: 381:nvme_qpair_manual_complete_request: *NOTICE*: Command completed manually:
nvme_qpair.c: 118:nvme_admin_qpair_print_command: *NOTICE*: ADMIN COMMAND (7f) sqid:0 cid:0 nsid:4 cdw10:00000000 cdw11:00000014
nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: ABORTED - BY REQUEST (00/07) sqid:0 cid:0 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
nvme.c: 686:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '169.254.85.7'
./perf_-Q-S-v: errors occured
admin@layton-dirt:~>

**Comment by sun-mingbao** [comment]
It seems that it was caused by certain threshold for controlling the resource using of non-root users.

**Comment by optimistyzy** [comment]
How about changing some settings in  /etc/security/limits.conf in order to provide some resource usage for a special user?

**Comment by sun-mingbao** [comment]
@optimistyzy 
Yes.
The issue was muted by adding the following in  /etc/security/limits.conf
*        hard    memlock        unlimited
*        soft    memlock        unlimited

**Comment by sun-mingbao** [comment]
@optimistyzy
Yes.
The issue can be muted by changing the limit of memlock in /etc/security/limits.conf.

**Comment by optimistyzy** [comment]
> @optimistyzy
> Yes.
> The issue can be muted by changing the limit of memlock in /etc/security/limits.conf.

So could we close this issue? I think it is an environment  issue and it is documented in this page: https://spdk.io/doc/system_configuration.html  

"Increasing the memlock limit permanently"

**Comment by sun-mingbao** [comment]
@optimistyzy 
Yes. SPDK has no job to do with this issue.
Many thanks for your support :)

**Comment by optimistyzy** [comment]
@sun-mingbao Let me close this issue.
