### ISSUE TITLE
SPDK Compile Error: gcc: error: unrecognized command line option ‘-m64’

### ISSUE THREAD

**Issue by HouYuu** [spdk/spdk#196]
how can i fix it?

**Comment by jimharris** [comment]
Can you provide details on your build environment?  Specifically Linux distribution/version and gcc version.  Also are you building on the host or in a virtual machine?

**Comment by HouYuu** [comment]
Thank you for your response，i used the arm64-armv8a-linuxapp-gcc to build the spdk on arm board and the linux kernel version is 4.4.38。
# And this is the build info：
nvidia@tegra-ubuntu:~/project/spdk-17.07$ make
make[3]: Entering directory '/home/nvidia/project/spdk-17.07/dpdk'
== Build lib
== Build lib/librte_compat
== Build lib/librte_eal
== Build lib/librte_eal/common
== Build lib/librte_eal/linuxapp
== Build lib/librte_eal/linuxapp/eal
== Build lib/librte_eal/linuxapp/igb_uio
  CC eal.o
  CC eal_hugepage_info.o
  CC eal_memory.o
gcc: error: unrecognized command line option ‘-m64’
/home/nvidia/project/spdk-17.07/dpdk/mk/internal/rte.compile-pre.mk:138: recipe for target 'eal.o' failed
make[8]: *** [eal.o] Error 1
make[8]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command line option ‘-m64’
/home/nvidia/project/spdk-17.07/dpdk/mk/internal/rte.compile-pre.mk:138: recipe for target 'eal_hugepage_info.o' failed
make[8]: *** [eal_hugepage_info.o] Error 1
gcc: error: unrecognized command line option ‘-m64’
/home/nvidia/project/spdk-17.07/dpdk/mk/internal/rte.compile-pre.mk:138: recipe for target 'eal_memory.o' failed
make[8]: *** [eal_memory.o] Error 1
/home/nvidia/project/spdk-17.07/dpdk/mk/rte.subdir.mk:63: recipe for target 'eal' failed
make[7]: *** [eal] Error 2
make[7]: *** Waiting for unfinished jobs....
  LD      /home/nvidia/project/spdk-17.07/dpdk/build/build/lib/librte_eal/linuxapp/igb_uio/built-in.o
  CC [M]  /home/nvidia/project/spdk-17.07/dpdk/build/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o
/bin/sh: scripts/basic/fixdep: cannot execute binary file: Exec format error
/usr/src/linux-headers-4.4.38-tegra/scripts/Makefile.build:267: recipe for target '/home/nvidia/project/spdk-17.07/dpdk/build/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o' failed
make[11]: *** [/home/nvidia/project/spdk-17.07/dpdk/build/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o] Error 126
/usr/src/linux-headers-4.4.38-tegra/Makefile:1414: recipe for target '_module_/home/nvidia/project/spdk-17.07/dpdk/build/build/lib/librte_eal/linuxapp/igb_uio' failed
make[10]: *** [_module_/home/nvidia/project/spdk-17.07/dpdk/build/build/lib/librte_eal/linuxapp/igb_uio] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[9]: *** [sub-make] Error 2
/home/nvidia/project/spdk-17.07/dpdk/mk/rte.module.mk:78: recipe for target 'igb_uio.ko' failed
make[8]: *** [igb_uio.ko] Error 2
/home/nvidia/project/spdk-17.07/dpdk/mk/rte.subdir.mk:63: recipe for target 'igb_uio' failed
make[7]: *** [igb_uio] Error 2
/home/nvidia/project/spdk-17.07/dpdk/mk/rte.subdir.mk:63: recipe for target 'linuxapp' failed
make[6]: *** [linuxapp] Error 2
/home/nvidia/project/spdk-17.07/dpdk/mk/rte.subdir.mk:63: recipe for target 'librte_eal' failed
make[5]: *** [librte_eal] Error 2
/home/nvidia/project/spdk-17.07/dpdk/mk/rte.sdkbuild.mk:73: recipe for target 'lib' failed
make[4]: *** [lib] Error 2
/home/nvidia/project/spdk-17.07/dpdk/mk/rte.sdkroot.mk:128: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/nvidia/project/spdk-17.07/dpdk'
Makefile:12: recipe for target 'all' failed
make[2]: *** [all] Error 2
Makefile:75: recipe for target 'all' failed
make[1]: *** [all] Error 2
/home/nvidia/project/spdk-17.07/mk/spdk.subdirs.mk:35: recipe for target 'dpdkbuild' failed
make: *** [dpdkbuild] Error 2

**Comment by dverkamp-intel** [comment]
ARM64 build support has been added recently (specifically commits 9f1fd30d5c65daf2829e53ee42d69281ffba4217 and dcfbafeb776c6a369d8d8898a3f03bf47799a724) - please retry with latest master.
