### ISSUE TITLE
How to re-probe device after calling API spdk_nvme_ctrlr_reset_subsystem?

### ISSUE THREAD

**Issue by ryderhsu0129** [spdk/spdk#1962]
According to the description below the API spdk_nvme_ctrlr_reset_subsystem :
`A subsystem reset is typically seen by the OS as a hot remove, followed by a hot add event.`

So we call spdk_nvme_probe immediately after calling spdk_nvme_ctrlr_reset_subsystem, but it seems that the re-probe failed,
how to re-probe device after calling API spdk_nvme_ctrlr_reset_subsystem?what is the correct process?

Thanks!

**Comment by changpe1** [comment]
@ryderhsu0129 what's the transport in your system? PCIe based?

**Comment by ryderhsu0129** [comment]
> @ryderhsu0129 what's the transport in your system? PCIe based?

@changpe1 
We are using PCIe as the transport interface.

**Comment by changpe1** [comment]
I tried subsystem reset in my local environment, subsystem reset isn't supported with all my NVMe drives. 

Can you list the kernel messages here when doing subsystem reset?

**Comment by changpe1** [comment]
I used nvme-cli to send subsystem reset to NVMe drive, here is the patch to use SPDK https://review.spdk.io/gerrit/c/spdk/spdk/+/8084 to send subsystem reset to controller.

**Comment by ryderhsu0129** [comment]
> I tried subsystem reset in my local environment, subsystem reset isn't supported with all my NVMe drives.
> 
> Can you list the kernel messages here when doing subsystem reset?

 @changpe1 
The dmesg doesn't show any messages when performing subsystem reset(spdk_nvme_ctrlr_reset_subsystem()), 
and then trying to re-probe device(spdk_nvme_probe()). But the SPDK console show the following message : 
```
Initialization complete.
[2021-05-27 17:30:12.161190] nvme_ctrlr.c:1485:spdk_nvme_ctrlr_reset_subsystem: *NOTICE*: [0000:02:00.0] resetting subsystem
[2021-05-27 17:30:16.884876] nvme_pcie_common.c: 480:_nvme_pcie_ctrlr_create_io_qpair: *ERROR*: nvme_create_io_cq failed!
[2021-05-27 17:30:16.884898] nvme_ctrlr.c: 450:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: [0000:02:00.0] nvme_transport_ctrlr_connect_io_qpair() failed
ERROR: spdk_nvme_ctrlr_alloc_io_qpair() failed
[2021-05-27 17:30:16.886770] nvme_ctrlr.c: 949:nvme_ctrlr_shutdown_async: *ERROR*: [0000:02:00.0] get_cc() failed
 
```

If we redo the test, a message will be displayed :
```
Initializing NVMe Controllers
Attaching to 0000:02:00.0
[2021-05-27 17:47:51.353738] nvme_pcie.c: 351:nvme_pcie_ctrlr_map_cmb: *ERROR*: get registers failed
[2021-05-27 17:47:51.353759] nvme_pcie.c: 534:nvme_pcie_ctrlr_map_pmr: *ERROR*: get registers failed
[2021-05-27 17:47:51.353771] nvme_pcie.c: 957:nvme_pcie_ctrlr_construct: *ERROR*: get_cap() failed
[2021-05-27 17:47:51.353796] nvme.c: 675:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:02:00.0
EAL: Requested device 0000:02:00.0 cannot be used
no NVMe controllers found
```

**Comment by changpe1** [comment]
looks like the hot remove event didn't occur after the subsystem reset, what happened if you only call subsystem reset?
can you still see the PCI device via lspci? what's the bind driver then?

**Comment by ryderhsu0129** [comment]
> looks like the hot remove event didn't occur after the subsystem reset, what happened if you only call subsystem reset?
> can you still see the PCI device via lspci? what's the bind driver then?

If we only do subsystem reset, the next step to allocate the I/O queue will still fail :
```
Initialization complete.
[2021-05-28 16:29:40.402365] nvme_ctrlr.c:1485:spdk_nvme_ctrlr_reset_subsystem: *NOTICE*: [0000:02:00.0] resetting subsystem
[2021-05-28 16:29:45.131340] nvme_pcie_common.c: 480:_nvme_pcie_ctrlr_create_io_qpair: *ERROR*: nvme_create_io_cq failed!
[2021-05-28 16:29:45.131362] nvme_ctrlr.c: 450:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: [0000:02:00.0] nvme_transport_ctrlr_connect_io_qpair() failed
ERROR: spdk_nvme_ctrlr_alloc_io_qpair() failed
[2021-05-28 16:29:45.132802] nvme_ctrlr.c: 949:nvme_ctrlr_shutdown_async: *ERROR*: [0000:02:00.0] get_cc() failed
```
and the NVMe device still exist via lspci, the bind driver is also uio_pci_generic.

We tried to remove/rescan the device via Linux sysfs after doing subsystem reset, and then re-probe by calling spdk_nvme_probe, the error will still happen.

**Comment by changpe1** [comment]
I've no idea about this, I think this isn't a SPDK issue, you may try your drive with kernel driver and use nvme-cli to do subsystem reset to see what happen then.

**Comment by ryderhsu0129** [comment]
We have tried to subsystem reset our drive successfully in the kernel driver, 
the procedure is to remove/rescan drive through PCIe sysfs after doing subsystem reset.

**Comment by changpe1** [comment]
So I think the same steps that do remove througth PCIe sysfs are required for SPDK after subsystem reset.

**Comment by ryderhsu0129** [comment]
We tried it too, but couldn’t re-probe drive back.

**Comment by changpe1** [comment]
what's the kernel messages when doing above actions?

**Comment by ryderhsu0129** [comment]
It seems that only the rescan action has logs :
```
[ 4502.802987] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x00003fff 64bit]
[ 4502.803027] pci 0000:02:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[ 4502.803040] pci 0000:02:00.0: Max Payload Size set to 256 (was 128, max 256)
[ 4502.803192] pci 0000:02:00.0: reg 0x1bc: [mem 0x00000000-0x00003fff 64bit]
[ 4502.803197] pci 0000:02:00.0: VF(n) BAR0 space: [mem 0x00000000-0x0003ffff 64bit] (contains BAR0 for 16 VFs)
[ 4502.826752] pci 0000:02:00.0: BAR 6: assigned [mem 0xab200000-0xab20ffff pref]
[ 4502.826754] pci 0000:02:00.0: BAR 0: assigned [mem 0xab210000-0xab213fff 64bit]
[ 4502.826759] pci 0000:02:00.0: BAR 7: assigned [mem 0xab214000-0xab253fff 64bit]
[ 4502.826867] nvme nvme0: pci function 0000:02:00.0
[ 4502.826875] nvme 0000:02:00.0: enabling device (0000 -> 0002)
```

You can try to subsystem reset through the nvme-cli, and remove/rescan drive through PCI sysfs.

**Comment by changpe1** [comment]
[Bug Scrub] @ryderhsu0129 can you post the detailed steps after doing subsystem reset with SPDK?

**Comment by ryderhsu0129** [comment]
> [Bug Scrub] @ryderhsu0129 can you post the detailed steps after doing subsystem reset with SPDK?

Okay, proceed as follows :
1. subsystem reset the device through API spdk_nvme_ctrlr_reset_subsystem()
2. remove/rescan the device via PCI sysfs(also tried to skip this step)
3. re-probe the device through API spdk_nvme_probe()

**Comment by jimharris** [comment]
Hi @ryderhsu0129,

I think you may need to rebind the SSD to uio/vfio driver before trying reprobe.

**Comment by changpe1** [comment]
It's not related with SPDK, so closing it for now.
