### ISSUE TITLE
vfio-user: can't run VM when attaching to controller; Invalid zero-sized VFIO migration region 9

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1963]
## Current Behavior

Qemu VM fails to boot when attaching to vfio-user controller with error:
```
qemu-system-x86_64: -device vfio-user-pci,socket=/var/run/muser/domain/muser1/1/cntrl: VFIO user </var/run/muser/domain/muser1/1/cntrl>: Invalid zero-sized VFIO migration region 9
```
Also results in guest VM kernel panic (log below).

## Steps to Reproduce

1.  Build SPDK with vfiouser
```
git submodule update --init
./configure --with-fio=/usr/src/fio --with-vfio-user --with-rdma --enable-debug
make -j100
```
2. Start SPDK target, configure bdevs, controllers and paths:
```
#!/usr/bin/env bash

i=1

rm -rf /var/run/muser
rm -rf /dev/shm/muser

mkdir -p /var/run/muser
mkdir -p /var/run/muser/iommu_group
mkdir -p /var/run/muser/domain/muser$i/$i
mkdir -p /dev/shm/muser/muser$i

read -p "Waiting..."

build/bin/nvmf_tgt -m [12] &
pid=$!
echo "PID: $pid"
sleep 3
scripts/rpc.py bdev_malloc_create 64 512
scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:0b:00.0
scripts/rpc.py nvmf_create_transport --trtype VFIOUSER
scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode0 -s SPDK001 -a
scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode0 Malloc0
scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode0 -t VFIOUSER -a /var/run/muser/domain/muser$i/$i -s 0

read -p "Waiting..."
ln -s /var/run/muser/domain/muser$i/$i /var/run/muser/domain/muser$i/$i/iommu_group
ln -s /var/run/muser/domain/muser$i/$i /var/run/muser/iommu_group/$i
ln -s /var/run/muser/domain/muser$i/$i/bar0 /dev/shm/muser/muser$i/bar0
```
3. Start Qemu VM:
```
taskset -a -c 1-2 /home/klateck/work/qemu-vfiouser/build/qemu-system-x86_64 \
-m 1024 --enable-kvm -cpu host -smp 2 -vga std -vnc :100 -daemonize \
-object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,share=on,prealloc=yes,host-nodes=0,policy=bind \
-snapshot \
-monitor telnet:127.0.0.1:10002,server,nowait \
-numa node,memdev=mem \
-pidfile /home/klateck/vhost_test/vms/0/qemu.pid \
-serial file:/home/klateck/vhost_test/vms/0/serial.log \
-D /home/klateck/vhost_test/vms/0/qemu.log \
-chardev file,path=/home/klateck/vhost_test/vms/0/seabios.log,id=seabios \
-device isa-debugcon,iobase=0x402,chardev=seabios \
-net user,hostfwd=tcp::10000-:22,hostfwd=tcp::10001-:8765 \
-net nic \
-drive file=/home/sys_sgci/spdk_dependencies/spdk_test_image.qcow2,if=none,id=os_disk \
-device ide-hd,drive=os_disk,bootindex=0 \
-device vfio-user-pci,socket=/var/run/muser/domain/muser1/1/cntrl
```

Result:
```
qemu-system-x86_64: -device vfio-user-pci,socket=/var/run/muser/domain/muser1/1/cntrl: VFIO user </var/run/muser/domain/muser1/1/cntrl>: Invalid zero-sized VFIO migration region 9
```

Guest VM kernel panic:
[serial.log](https://github.com/spdk/spdk/files/6546618/serial.log)
(It might be caused by vfio-user-master Qemu itself though. I commented out vfio-user-pci device from qemu command and still got this kernel panic. It disappeared after I used "vanilla" Qemu from Fedora DNF repo. Let me know if I should create a separate issue for that.)

## Context (Environment including OS version, SPDK version, etc.)

Qemu:
```
[klateck@eagle1 qemu-vfiouser]$ git branch
  master
* vfio-user-master
  vfio-user-v0.6
[klateck@eagle1 qemu-vfiouser]$ git log -1
commit f1f728abab270872e48dc1b009225305b0d197e1 (HEAD -> vfio-user-master, origin/vfio-user-master)
Merge: 28aa095912 dab59ce031
Author: Thanos Makatos <thanos.makatos@nutanix.com>
Date:   Tue May 25 09:59:58 2021 -0400

    Merge commit 'dab59ce' into vfio-user-master

./configure --target-list="x86_64-softmmu" --enable-kvm --enable-linux-aio --enable-numa
```

SPDK:
```
commit 924bfd067e4ed4873ce72bfc27672367a9e982a7 (origin/master, origin/HEAD, master)
Author: Shuhei Matsumoto <shuhei.matsumoto.xt@hitachi.com>
Date:   Tue Apr 20 23:42:50 2021 +0900

    bdev/nvme: Add ANA state per namespace into JSON info dump
```

libvfio-user SPDK submodule:
```
commit cfe9901919943f14961e1da1c4a823336ff79555 (HEAD)
Author: Thanos Makatos <thanos.makatos@nutanix.com>
Date:   Thu May 20 17:10:51 2021 +0100

    migration: various dirty page tracking fixes (#457)
```

**Comment by karlatec** [comment]
Copying the note about encountered guest VM kernel panic, just for better visibility:
```
It might be caused by vfio-user-master Qemu itself though. I commented out vfio-user-pci device from qemu command and still got this kernel panic. It disappeared after I used "vanilla" Qemu from Fedora DNF repo. Let me know if I should create a separate issue for that.
```

**Comment by changpe1** [comment]
@karlatec the message "Invalid zero-sized VFIO migration region 9" doesn't affect anything, it's only used for live migration. I noticed that QEMU just has a huge update, but I tested it again in my local environment, everything works fine to me.

I saw the kernel panic is related with serial device, so can you have another try to remove the serial device?

I used Fedora 33 for the VM image.

**Comment by changpe1** [comment]
I just updated the libvfio-user submodule, still works for me, maybe you can have another try.

And it is much simple now to create vfio-user devices, see test/nvmf/target/nvmf_vfio_user.sh for more information, you only need to create a socket file now.

**Comment by karlatec** [comment]
>  "Invalid zero-sized VFIO migration region 9" doesn't affect anything, it's only used for live migration. 

I think even if it's not related to the problem I'm seeing, and it's just a message, then it should be fixed anyway. In my opinion it's very misleading to have an error/warning message like that, especially if it's unrelated.

> I saw the kernel panic is related with serial device, so can you have another try to remove the serial device?

Already tried that. See my previous comment. 

>  see test/nvmf/target/nvmf_vfio_user.sh
Will take a look, re-test, and report back.

**Comment by changpe1** [comment]
Yeah, I will bring this issue to Thanos

**Comment by tmakatos** [comment]
I merged QEMU upstream to vfio-user-master *and* pushed more changes related to vfio-user at the same time, so this might indeed be a QEMU problem. Can you try commit 28aa095912?

**Comment by karlatec** [comment]
`28aa095912` seems to be OK. Tried `3c4f65441c`, this one looks OK to.

I also attempted to bisect and ended up with `f5cc5a5c168674f84bf061cdb307c2d25fba5448`, but l'm not sure it's related. Either I messed something up or the issue is not 100% reproducible.

**Comment by tmakatos** [comment]
FYI we're changing the spec a bit and not testing thoroughly, should be done with it in the next few days.

**Comment by karlatec** [comment]
OK! Let me know when I can get back to testing please :)

**Comment by tmakatos** [comment]
@karlatec https://github.com/nutanix/libvfio-user/pull/543 fixes this.

**Comment by changpe1** [comment]
I just updated the submodule based on  Swapnil's patch https://review.spdk.io/gerrit/c/spdk/spdk/+/8088, I tested it with QEMU vfio-user-master-old branch and it worked.

**Comment by karlatec** [comment]
@tmakatos @changpe1  I'm confused. Which Qemu branch should I use? `vfio-user-master` or `vfio-user-master-old` which Changpeng uses? Or master? Is there any doc which describes which version should actually be used?

**Comment by karlatec** [comment]
Because if `vfio-user-master` is the correct branch, then recently merged PR https://github.com/nutanix/libvfio-user/pull/543 does not fix the issue. Actually it makes things worse. 

After running Qemu command, SPDK output:
```
[klateck@eagle1 spdk]$ [2021-05-31 14:45:39.382636] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad DMA map region size=32 argsz=0
[2021-05-31 14:45:39.382745] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0x1: cmd 2 failed: Invalid argument
[2021-05-31 14:45:39.382894] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad offset for new DMA region [(nil), 0x1) fd=-1 offset=0x40000 prot=0; existing=0x20000
[2021-05-31 14:45:39.382912] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: failed to add DMA region [0, 0x1) offset=0x40000 flags=0: Invalid argument
[2021-05-31 14:45:39.382924] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0x5: cmd 2 failed: Invalid argument
[2021-05-31 14:45:39.383171] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad command 6
[2021-05-31 14:45:39.383185] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0xf: cmd 6 failed: Invalid argument
[2021-05-31 14:45:39.383218] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad size 16
[2021-05-31 14:45:39.383231] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0x10: cmd 8 failed: Invalid argument
[2021-05-31 14:48:32.468566] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad DMA map region size=32 argsz=0
[2021-05-31 14:48:32.468655] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0x1: cmd 2 failed: Invalid argument
[2021-05-31 14:48:32.468785] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad offset for new DMA region [(nil), 0x1) fd=-1 offset=0x40000 prot=0; existing=0x20000
[2021-05-31 14:48:32.468805] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: failed to add DMA region [0, 0x1) offset=0x40000 flags=0: Invalid argument
[2021-05-31 14:48:32.468818] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0x5: cmd 2 failed: Invalid argument
[2021-05-31 14:48:32.469038] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad command 6
[2021-05-31 14:48:32.469052] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0xf: cmd 6 failed: Invalid argument
[2021-05-31 14:48:32.469082] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: bad size 16
[2021-05-31 14:48:32.469095] vfio_user.c:1448:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/1: msg0x10: cmd 8 failed: Invalid argument
```

Qemu fails to start and gives no output even on serial. In dmesg I can see:
```
[595827.629107] qemu-system-x86[1115973]: segfault at 0 ip 00005585726c6e86 sp 00007ffdf831e6f0 error 4 in qemu-system-x86_64[558571e8d000+b35000]
[595827.629116] Code: 49 89 f4 55 53 48 89 fb 31 ff 48 83 ec 08 e8 81 d6 a9 ff 4c 89 ea 4c 89 e6 48 89 c7 48 89 c5 e8 40 0e aa ff 48 8b 03 48 89 ef <48> 8b 30 e8 e2 ee a9 ff 48 8b 03 48 8b 38 e8 c7 a9 a9 ff 48 8b 1b
```

Branch `vfio-user-master-old`  does not have this issue.

**Comment by changpe1** [comment]
@karlatec we're trying to have a stable QEMU version, currently you can use `vfio-user-master-old` as suggested by Thanos, hopefully the specification will be stable very soon.

**Comment by tmakatos** [comment]
@karlatec I've pushed a couple of chanes to `vfio-user-master`, can you try again?

**Comment by karlatec** [comment]
@tmakatos The `Invalid zero-sized VFIO migration region 9` error message is gone, but the VM is back to the state where it either gets stuck during boot or fails with kernel panic.

**Comment by tmakatos** [comment]
@karlatec I just checked and it works for me, however in my case I'm using nested virtualization. Looking at the QEMU messages you've sent earlier, it looks like QEMU's version of vfio-user is incompatible with the version used by libvfio-user, e.g.:
```
bad offset for new DMA region [(nil), 0x1) fd=-1 offset=0x40000 prot=0; existing=0x20000
```
A DMA region of one byte at offset 0x40000. Can you double check that you're using the correct versions of QEMU and libvfio-user? Also, are you using the fix where SPDK fails to pick up new libvfio-user changes when building?

**Comment by karlatec** [comment]
I'm using https://review.spdk.io/gerrit/c/spdk/spdk/+/8088 to update libvfio-user, so that it includes PR which you linked previously.

So at the moment I use:
Qemu:
```
[klateck@eagle1 qemu-vfiouser]$ git branch
  master
* vfio-user-master
  vfio-user-master-old
  vfio-user-v0.6
[klateck@eagle1 qemu-vfiouser]$ git log -1
commit 52b530ed6171366ce84869dc7897bd89940a42ff (HEAD -> vfio-user-master, origin/vfio-user-master)
Author: Thanos Makatos <thanos.makatos@nutanix.com>
Date:   Thu May 27 11:13:34 2021 -0400

    adapt to spec changes

    Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>
```

SPDK:
```
99baf23a9 (HEAD -> vhost-vfio-user) libvfio-user: update submodule (submodule update)
3fdd264ff nvmf: don't use request internal variable after req_complete callback (Changpeng fixes)
4b238f431 [RFC] test/vhost: add vfio_user mode to performance scripts (just test scripts)
397c7734c [RFC] test/vhost: add test with vfio-user (just test scripts)
2dd04c144 test/common: update vfio-user capable Qemu branch (just test scripts)
252430a05 (origin/master, origin/HEAD, master) nvme_tcp: Correctly handle the data digest err
```

libvfio-user submodule:
```
commit d69581a45fa1c720cb796eb829259739c0ee2c2f (HEAD, origin/master, origin/HEAD)
Author: Thanos Makatos <thanos.makatos@nutanix.com>
Date:   Fri May 28 20:46:59 2021 +0100

    don't return non-zero caps for zero-sized regions (#543)

    Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>
    Reviewed-by: John Levon <john.levon@nutanix.com>

```

**Comment by changpe1** [comment]
@karlatec I used the exactly same commits with yours, and my VM started successfully without any exceptions, I think you may need to recompile your QEMU, I used ./configure --target-list=x86_64-softmmu to compile it, and my VM image is Fedora 33.

**Comment by jimharris** [comment]
@karlatec - can you recheck this?

**Comment by jimharris** [comment]
We think this is closed now.  @karlatec will recheck once we have CI up and running with QEMU vfio-user.
