### ISSUE TITLE
Vagrant fails to install rsync on the FreeBSD VM

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1968]
https://ci.spdk.io/results/autotest-per-patch/builds/48769/archive/freebsd-vg-autotest/build.log

Seems to be intermittent networking issue. This can be resolved by deploying latest build, 12.2, (currently some variants of 12.1 are being used across all VM hosts) we have available for FreeBSD where rsync is already on board.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_48781.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_48727.html

**Comment by jimharris** [comment]
Haven't seen this again for over 3 weeks.  Maybe this was a problem with the FreeBSD servers over this small time period?  All three failures were within the same 24 hours. @mikeBashStuff what do you think about closing this issue?

**Comment by mikeBashStuff** [comment]
@jimharris I think it should be safe to close it - we deployed freebsd image across the CI pool which already includes rsync on board so this should not happen again.
