### ISSUE TITLE
[Cannot get I/O channel] ubuntu18-vg-autotest

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1977]
https://ci.spdk.io/results/autotest-per-patch/builds/49112/archive/ubuntu18-vg-autotest/build.log

## Execution failed at

00:04:17.021   01:44:41	# event=bdev_register:Nvme0n1
00:04:17.021   01:44:41	# ev_type=bdev_register
00:04:17.021   01:44:41	# ev_ctx=Nvme0n1
00:04:17.021   01:44:41	# expected_notifications+=(${ev_type}:${ev_ctx})
00:04:17.021   01:44:41	# read -r event_line
00:04:17.022   01:44:41	# [[ 1 -eq 1 ]]
00:04:17.022   01:44:41	# local lvol_store_base_bdev=Nvme0n1
00:04:17.022   01:44:41	# tgt_rpc get_bdevs --name Nvme0n1
00:04:17.022   01:44:41	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock get_bdevs --name Nvme0n1
00:04:17.141  get_bdevs is deprecated, use bdev_get_bdevs instead.
00:04:17.149   01:44:42	# tgt_rpc bdev_split_create Nvme0n1 2
00:04:17.149   01:44:42	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_split_create Nvme0n1 2
00:04:17.300  Nvme0n1p0 Nvme0n1p1
00:04:17.309   01:44:42	# tgt_rpc bdev_split_create Malloc0 3
00:04:17.309   01:44:42	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_split_create Malloc0 3
00:04:17.441  [2021-06-07 01:44:42.337080] bdev.c:5820:spdk_bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: Malloc0
00:04:17.444  
00:04:17.451   01:44:42	# tgt_rpc bdev_malloc_create 8 4096 --name Malloc3
00:04:17.451   01:44:42	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_malloc_create 8 4096 --name Malloc3
00:04:17.583  Malloc3
00:04:17.590   01:44:42	# tgt_rpc bdev_passthru_create -b Malloc3 -p PTBdevFromMalloc3
00:04:17.590   01:44:42	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_passthru_create -b Malloc3 -p PTBdevFromMalloc3
00:04:17.721  [2021-06-07 01:44:42.616705] vbdev_passthru.c: 610:vbdev_passthru_register: *NOTICE*: Match on Malloc3
00:04:17.721  [2021-06-07 01:44:42.616777] vbdev_passthru.c: 638:vbdev_passthru_register: *NOTICE*: base bdev opened
00:04:17.721  [2021-06-07 01:44:42.616809] vbdev_passthru.c: 667:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x616000032180
00:04:17.721  [2021-06-07 01:44:42.616837] vbdev_passthru.c: 682:vbdev_passthru_register: *NOTICE*: bdev claimed
00:04:17.721  [2021-06-07 01:44:42.617529] vbdev_passthru.c: 695:vbdev_passthru_register: *NOTICE*: pt_bdev registered
00:04:17.721  [2021-06-07 01:44:42.617567] vbdev_passthru.c: 696:vbdev_passthru_register: *NOTICE*: created pt_bdev for: PTBdevFromMalloc3
00:04:17.723  PTBdevFromMalloc3
00:04:17.729   01:44:42	# tgt_rpc bdev_null_create Null0 32 512
00:04:17.729   01:44:42	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_null_create Null0 32 512
00:04:17.859  Null0
00:04:17.866   01:44:42	# tgt_rpc bdev_malloc_create 32 512 --name Malloc0
00:04:17.866   01:44:42	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_malloc_create 32 512 --name Malloc0
00:04:17.996  [2021-06-07 01:44:42.892600] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:17.996  [2021-06-07 01:44:42.892667] blobstore.c:3054:bs_channel_create: *ERROR*: Failed to create device channel.
00:04:17.996  [2021-06-07 01:44:42.892715] blobstore.c:5310:bs_register_md_thread: *ERROR*: Failed to get IO channel.
00:04:17.996  [2021-06-07 01:44:42.892777] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:17.996  [2021-06-07 01:44:42.892827] vbdev_gpt.c: 500:vbdev_gpt_read_gpt: *ERROR*: Failed to get an io_channel.
00:04:17.996  [2021-06-07 01:44:42.892859] vbdev_gpt.c: 553:vbdev_gpt_examine: *ERROR*: Failed to read info from bdev Malloc0p0
00:04:17.996  [2021-06-07 01:44:42.893028] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:17.996  [2021-06-07 01:44:42.893051] blobstore.c:3054:bs_channel_create: *ERROR*: Failed to create device channel.
00:04:17.996  [2021-06-07 01:44:42.893071] blobstore.c:5310:bs_register_md_thread: *ERROR*: Failed to get IO channel.
00:04:17.996  [2021-06-07 01:44:42.893099] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:17.996  [2021-06-07 01:44:42.893127] vbdev_gpt.c: 500:vbdev_gpt_read_gpt: *ERROR*: Failed to get an io_channel.
00:04:17.996  [2021-06-07 01:44:42.893144] vbdev_gpt.c: 553:vbdev_gpt_examine: *ERROR*: Failed to read info from bdev Malloc0p1
00:04:17.996  [2021-06-07 01:44:42.893290] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:17.996  [2021-06-07 01:44:42.893313] blobstore.c:3054:bs_channel_create: *ERROR*: Failed to create device channel.
00:04:17.996  [2021-06-07 01:44:42.893332] blobstore.c:5310:bs_register_md_thread: *ERROR*: Failed to get IO channel.
00:04:17.996  [2021-06-07 01:44:42.893356] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:17.996  [2021-06-07 01:44:42.893397] vbdev_gpt.c: 500:vbdev_gpt_read_gpt: *ERROR*: Failed to get an io_channel.
00:04:17.996  [2021-06-07 01:44:42.893415] vbdev_gpt.c: 553:vbdev_gpt_examine: *ERROR*: Failed to read info from bdev Malloc0p2
00:04:17.999  Malloc0
00:04:18.006   01:44:42	# tgt_rpc bdev_malloc_create 16 4096 --name Malloc1
00:04:18.006   01:44:42	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_malloc_create 16 4096 --name Malloc1
00:04:18.140  [2021-06-07 01:44:43.036350] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:18.140  [2021-06-07 01:44:43.036409] blobstore.c:3054:bs_channel_create: *ERROR*: Failed to create device channel.
00:04:18.140  [2021-06-07 01:44:43.036445] blobstore.c:5310:bs_register_md_thread: *ERROR*: Failed to get IO channel.
00:04:18.140  [2021-06-07 01:44:43.036496] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:18.140  [2021-06-07 01:44:43.036529] vbdev_gpt.c: 500:vbdev_gpt_read_gpt: *ERROR*: Failed to get an io_channel.
00:04:18.140  [2021-06-07 01:44:43.036566] vbdev_gpt.c: 553:vbdev_gpt_examine: *ERROR*: Failed to read info from bdev Malloc1
00:04:18.143  Malloc1
00:04:18.151   01:44:43	# expected_notifications+=(bdev_register:${lvol_store_base_bdev}p1 bdev_register:${lvol_store_base_bdev}p0 bdev_register:Malloc3 bdev_register:PTBdevFromMalloc3 bdev_register:Null0 bdev_register:Malloc0 bdev_register:Malloc0p2 bdev_register:Malloc0p1 bdev_register:Malloc0p0 bdev_register:Malloc1)
00:04:18.151    01:44:43	# uname -s
00:04:18.155   01:44:43	# [[ Linux = Linux ]]
00:04:18.155   01:44:43	# dd if=/dev/zero of=/sample_aio bs=1024 count=102400
00:04:18.393  102400+0 records in
00:04:18.393  102400+0 records out
00:04:18.393  104857600 bytes (105 MB, 100 MiB) copied, 0.235573 s, 445 MB/s
00:04:18.393   01:44:43	# tgt_rpc bdev_aio_create /sample_aio aio_disk 1024
00:04:18.393   01:44:43	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_aio_create /sample_aio aio_disk 1024
00:04:18.508  [2021-06-07 01:44:43.403970] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067e024e60
00:04:18.508  [2021-06-07 01:44:43.404035] blobstore.c:3054:bs_channel_create: *ERROR*: Failed to create device channel.
00:04:18.508  [2021-06-07 01:44:43.404054] blobstore.c:5310:bs_register_md_thread: *ERROR*: Failed to get IO channel.
00:04:18.508  [2021-06-07 01:44:43.404116] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067e024e60
00:04:18.508  [2021-06-07 01:44:43.404144] vbdev_gpt.c: 500:vbdev_gpt_read_gpt: *ERROR*: Failed to get an io_channel.
00:04:18.508  [2021-06-07 01:44:43.404180] vbdev_gpt.c: 553:vbdev_gpt_examine: *ERROR*: Failed to read info from bdev aio_disk
00:04:18.557  aio_disk
00:04:18.574   01:44:43	# expected_notifications+=(bdev_register:aio_disk)
00:04:18.574   01:44:43	# tgt_rpc bdev_lvol_create_lvstore -c 1048576 Nvme0n1p0 lvs_test
00:04:18.574   01:44:43	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_lvol_create_lvstore -c 1048576 Nvme0n1p0 lvs_test
00:04:18.711  [2021-06-07 01:44:43.606711] thread.c:2020:spdk_get_io_channel: *ERROR*: could not find io_device 0x7f067d672360
00:04:18.711  [2021-06-07 01:44:43.606799] bdev_nvme.c:1125:bdev_nvme_poll_group_create_cb: *ERROR*: Cannot get the accel_channel for bdev nvme polling group=0x60b000013c00
00:04:18.711  [2021-06-07 01:44:43.606839] blobstore.c:3054:bs_channel_create: *ERROR*: Failed to create device channel.
00:04:18.711  [2021-06-07 01:44:43.606878] blobstore.c:5310:bs_register_md_thread: *ERROR*: Failed to get IO channel.
00:04:18.711  [2021-06-07 01:44:43.606930] vbdev_lvol.c: 187:_vbdev_lvs_create_cb: *ERROR*: Cannot create lvol store bdev
00:04:18.711  [2021-06-07 01:44:43.607013] lvol.c: 541:lvs_init_cb: *ERROR*: Lvol store init failed: could not initialize blobstore
00:04:18.713  request:
00:04:18.713  {
00:04:18.713    "bdev_name": "Nvme0n1p0",
00:04:18.713    "lvs_name": "lvs_test",
00:04:18.713    "cluster_sz": 1048576,
00:04:18.713    "method": "bdev_lvol_create_lvstore",
00:04:18.713    "req_id": 1
00:04:18.713  }
00:04:18.713  Got JSON-RPC error response
00:04:18.713  response:
00:04:18.713  {
00:04:18.713    "code": -32602,
00:04:18.713    "message": "Cannot allocate memory"

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_49112.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_49139.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_49142.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_49194.html

**Comment by jimharris** [comment]
This is most likely due to recently merged commit 2246a9371809c30333b1844afbf9772c4b06.

I've pushed a revert for now: https://review.spdk.io/gerrit/c/spdk/spdk/+/8199

**Comment by jimharris** [comment]
Patch merged.

Keep this issue open for now, just in case the revert does not fix the issue.
