### ISSUE TITLE
iSCSI target incorrectly interprets Logout Request reason field

### ISSUE THREAD

**Issue by mlbzssk** [spdk/spdk#198]
Hi~~~
  I am a new to Spdk,when i use iscsi target,i found that the struct you defined is not same with the iscsi protocol.It is the iscsi_bhs_logout_req.The source code use on Byte to response reason,but in the commom protol which initiator may use ,it use 7 bit,the first bit is setted 1,so when the initiator send '10000000' the target regard reason as 128.I don't know if i said clearly,but i'm looking forword to somebody give me some advices.
thanks!

**Comment by dverkamp-intel** [comment]
Thanks for the report - this is a good catch!

I've prepared a patch to fix the issue - please review https://review.gerrithub.io/#/c/378658/

**Comment by mlbzssk** [comment]
Hi~ Thank you !
  And may I ask you a question?emmmmmm...When i run spdk iscsi,I found that the windows os will send logout command to terminate discovery session,but the ubuntu won't.Maybe this is why you don't found the logout question.I wanna know why the liunx don't send logout command? It seems like the reason is the diffrance between linux and  windows.But they also use TCP/IP,I'm puzzled.Could you please tell you about that if you know?
    very very very thanks.

**Comment by dverkamp-intel** [comment]
Fixed in commit 1e33a802b408ed72fa9c2d3ce9080759184dc419 - thanks for the report.
