### ISSUE TITLE
[nvmf-tcp-vg-autotest] ns_hotplug_stress.sh - No such process

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#1985]
Tests failed at [nvmf-tcp-vg-autotest].

00:06:59.265  ************************************
00:06:59.265  START TEST nvmf_ns_hotplug_stress
00:06:59.265  ************************************

## Link to the failed CI build
Patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/7972/4
Failed build: https://ci.spdk.io/results/autotest-per-patch/builds/48868/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

00:07:02.295  [2021-06-02 09:23:48.729536] ctrlr.c: 823:nvmf_ctrlr_cmd_connect: *ERROR*: Subsystem 'nqn.2016-06.io.spdk:cnode1' is not ready
00:07:02.295  [2021-06-02 09:23:48.729668] nvme_fabric.c: 460:nvme_fabric_qpair_connect: *ERROR*: Connect command failed, rc -5, trtype:TCP adrfam:IPv4 traddr:10.0.0.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1
00:07:02.295  [2021-06-02 09:23:48.729714] nvme_fabric.c: 468:nvme_fabric_qpair_connect: *ERROR*: Connect command completed with error: sct 1, sc 129
00:07:02.295  [2021-06-02 09:23:48.729730] nvme_tcp.c:1901:nvme_tcp_ctrlr_connect_qpair: *ERROR*: Failed to send an NVMe-oF Fabric CONNECT command
00:07:02.296  /home/vagrant/spdk_repo/spdk/build/examples/perf: errors occured
00:07:02.299  Initializing NVMe Controllers
00:07:02.299  Attached to NVMe over Fabrics controller at 10.0.0.2:4420: nqn.2016-06.io.spdk:cnode1
00:07:02.299  controller IO queue size 128 less than required
00:07:02.299  Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
00:07:02.299  controller IO queue size 128 less than required
00:07:02.299  Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
00:07:02.299  Associating TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 with lcore 0
00:07:02.299  Associating TCP (addr:10.0.0.2 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 2 with lcore 0
00:07:02.299  Initialization complete. Launching workers.
00:07:02.299  ERROR: unable to connect I/O qpair.
00:07:02.299  ERROR: init_ns_worker_ctx() failed
00:07:02.299  ========================================================
00:07:02.299                                                                                                               Latency(us)
00:07:02.299  Device Information                                                       :       IOPS      MiB/s    Average        min        max
00:07:02.308   09:23:48	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Delay0
00:07:02.490   09:23:48	# null_size=1001
00:07:02.490   09:23:48	# /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_null_resize NULL1 1001
00:07:02.660  true
00:07:02.670   09:23:49	# kill -0 53363
**00:07:02.670  test/nvmf/target/ns_hotplug_stress.sh: line 31: kill: (53363) - No such process**
00:07:02.670   09:23:49	# wait 53363
00:07:02.670    09:23:49	# trap - ERR
00:07:02.670    09:23:49	# print_backtrace
00:07:02.670    09:23:49	# [[ ehxBET =~ e ]]
00:07:02.670    09:23:49	# args=("${BASH_ARGV[@]}")
00:07:02.670    09:23:49	# local args
00:07:02.670    09:23:49	# xtrace_disable
00:07:02.670    09:23:49	# '[' no '!=' yes ']'
00:07:02.670    09:23:49	# PREV_BASH_OPTS=ehxBET
00:07:02.670    09:23:49	# [[ ehxBET == *\x* ]]
00:07:02.670    09:23:49	# XTRACE_DISABLED=yes
00:07:02.670    09:23:49	# set +x
00:07:02.670  ========== Backtrace start: ==========
00:07:02.670  
00:07:02.679  in test/nvmf/target/ns_hotplug_stress.sh:40 -> main(["--transport=tcp"])
00:07:02.679       ...
00:07:02.679     35  		# effect on subsystem/namespace handling in the nvmf target
00:07:02.679     36  		null_size=$((null_size + 1))
00:07:02.679     37  		$rpc_py bdev_null_resize NULL1 $null_size
00:07:02.679     38  	done
00:07:02.679     39  	
00:07:02.679  => 40  	wait $PERF_PID
00:07:02.679     41  	
00:07:02.679     42  	trap - SIGINT SIGTERM EXIT
00:07:02.679     43  	
00:07:02.679     44  	nvmftestfini
00:07:02.679       ...
00:07:02.679  
00:07:02.679  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_48868.html

**Comment by changpe1** [comment]
Beside adding retry mechanism in the NVMf target side when subsystem isn't active, I think we may also add a sleep delay before doing hot remove in the ns_hotplug_stress.sh, this will ensure the perf is running IO tests before the hot remove, for the above failure the perf tool is doing fabric connect when hot remove happened. what do you think? @jimharris @benlwalker

**Comment by jimharris** [comment]
The sleep would likely fix this particular test.

But I'd like to investigate queuing the CONNECT command internally so it can execute after the subsystem becomes active again.  That would be a cleaner fix overall, and avoid spurious CONNECT failures when the subsystem just happens to be paused at the same time.

**Comment by benlwalker** [comment]
Agree with Jim - we need to handle hot remove during fabric connect anyway so we need to do some kind of queueing. But maybe we should have two tests here to cover the hot remove during fabric connect case and the hot remove during I/O case.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/8572

I've added a new 'connect_stress' test application and test script as part of this series.  It helped me reproduce the issue here, as well as finding another bug that is also fixed in this series.

**Comment by tomzawadzki** [comment]
The patch fixing the issue was merged, so issue can be closed. The test application should get merged too and is out for review.
