### ISSUE TITLE
The Problem of Using SPDK

### ISSUE THREAD

**Issue by mlbzssk** [spdk/spdk#199]
Hi,friends~
  I have a problem with using SPDK. As we use config file to configure spdk,but how do we do if we want to change the parameters when it's running? I don't  know if there are anyway else to solve this problem.And I hear that if I add disk in the target when target is running,the initiator  won't find the new targer.It's seems true cause the parameters are changeless. Be so kind as to give me a reply, please.
thanks!

**Comment by gocamero** [comment]
I believe you can use rpc to modify target during run time. 

Jin

**Comment by mlbzssk** [comment]
oh,thanks for you advice! I find that I made a mistake. what I mean is when I add disk in the target,the initiator won't find the new disk.I know a little about rpc,and I don't know how to solve the problem with rpc.Could you please explain that to me?

**Comment by benlwalker** [comment]
If you add a new disk to the target (by creating a new subsystem and adding its bdev as a namespace), then you need to tell your initiator to connect to it the same way you told it to connect to other devices.
