### ISSUE TITLE
[nvme-tcp-phy-autotest] nvmf_vhost seg fault

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1990]
00:05:03.579  [2021-06-10 01:23:24.838546] lun.c: 403:bdev_event_cb: *NOTICE*: bdev name (Nvme0n1) received event(SPDK_BDEV_EVENT_REMOVE)
00:05:03.636  /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/target/../../../test/common/autotest_common.sh: line 842: 27000 Segmentation fault      (core dumped) "${VHOST_APP[@]}" -S "$(get_vhost_dir 3)"
00:05:03.636    01:23:24	# trap - ERR
00:05:03.636    01:23:24	# print_backtrace
00:05:03.637    01:23:24	# [[ ehxBET =~ e ]]
00:05:03.637    01:23:24	# args=("${BASH_ARGV[@]}")
00:05:03.637    01:23:24	# local args
00:05:03.637    01:23:24	# xtrace_disable
00:05:03.638    01:23:24	# '[' no '!=' yes ']'
00:05:03.638    01:23:24	# PREV_BASH_OPTS=ehxBET
00:05:03.638    01:23:24	# [[ ehxBET == *\x* ]]
00:05:03.638    01:23:24	# XTRACE_DISABLED=yes
00:05:03.638    01:23:24	# set +x
00:05:03.638  ========== Backtrace start: ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_49483.html

**Comment by jimharris** [comment]
This exact same failure happened on two different jobs, both related to vhost-scsi testing.  Since this patch is touching the scsi code, I think it's more likely that this is a bug in the patch, not an intermittent CI failure.
