### ISSUE TITLE
[clang-vg-autotest] could not allocate hugepages

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#1991]
00:07:01.815  ## ERROR: requested 4096 hugepages but 3814 could be allocated on node0.
00:07:01.815  ## Memory might be heavily fragmented. Please try flushing the system cache, or reboot the machine.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_49547.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_49562.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_49553.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_49556.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_49550.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_49543.html

**Comment by mikeBashStuff** [comment]
Seems to be limited to SM9.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_49762.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_49711.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_49823.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49885.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_49944.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_50022.html

**Comment by karlatec** [comment]
@wawryk please take a look. Most of the fails seem to be on SM9, but I've also seen at least 1 on SM4

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50184.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50219.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_50209.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50234.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50263.html

**Comment by wawryk** [comment]
Currently i see that occurs on:

- VM-host-WFP1
- VM-host-PE3
- VM-host-SM4
- VM-host-SM9

and not only on clang autotest.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_50278.html

**Comment by mikeBashStuff** [comment]
Ok, I went through recent changes in the CI and this seems to be related to the work which updated the amount of resources we started to allocate per VM. We dropped the default to 12GB of total memory for all the jobs which run functional tests, unittest job and the clang job (talking about the per-patch only here) - the scanbuild and autobuild are exceptions as they may work under 8GB since we almost don't need hugepages there at all. For f33 it was known that memory consumption overall is greater than on f31 which we used previously (this became apparent especially for the scan-build runs which was consuming ~5GB alone hence we initially increased total mem for these jobs to 14GB). 

Since 12GB per VM is still, relatively speaking, plenty, I suggest the following: https://review.spdk.io/gerrit/c/spdk/spdk/+/8433 - we drop the global 8GB hp allocation in half, i.e., leave it at setup.sh's default. It should be enough for most of the tests. If there are some that require more we should determine exactly what resources should be allocated and do that only for the tests|jobs which require it. Going to test it out next week.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_50287.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_50292.html

**Comment by mikeBashStuff** [comment]
Small correction - setup.sh's default is 2048 MB, my mistake. This actually may not be enough for some of the tests which explicitly request more (e.g. spdkcli) so the patch needs a small fix.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_50162.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_50435.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_50446.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @dong-liuliu. log: https://ci.spdk.io/public_build/autotest-per-patch_50449.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_50651.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_50750.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_50957.html

**Comment by mikeBashStuff** [comment]
The potential fix just got merged: https://review.spdk.io/gerrit/c/spdk/spdk/+/8436

if you still see this issue hitting your patches (especially if it includes this line in the log `ERROR: requested 4096 hugepages ...` then please make sure the patches are rebased against the latest master.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_50973.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50984.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50992.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_51001.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50991.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_50355.html

**Comment by mikeBashStuff** [comment]
The fix (https://review.spdk.io/gerrit/c/spdk/spdk/+/8436) got already merged so closing this for now.
