### ISSUE TITLE
Building SPDK with system installed DPDK

### ISSUE THREAD

**Issue by tanabarr** [spdk/spdk#1993]
Building with a system installed DPDK doesn't seem to be supported, --with-dpdk should presumably support the option of a pkg-config file.

## Expected Behavior

SPDK should be able to be built with a system installed DPDK version that is found automatically or referenced with a .pc file.

## Current Behavior

If the dpdk-devel package installs the /usr/share/..linuxapp.. target then it can be supplied to --with-dpdk when building. Supplying pkg-config won't work.

## Possible Solution

Provide ability to use pkg-config to look up a system installed version of DPDK during configure/build.

## Context (Environment including OS version, SPDK version, etc.)

CentOS 7
SPDK 21.04
DPDK 21.02

Reference: https://github.com/spdk/spdk/issues/1750

**Comment by tanabarr** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/8348

**Comment by jimharris** [comment]
Patch merged.
