### ISSUE TITLE
Build failure on Linux ARM64

### ISSUE THREAD

**Issue by martin-g** [spdk/spdk#1998]
## Expected Behavior

I expect the build to succeed on Linux ARM64 (Ubuntu 20.04.2).
There are several [issues](https://github.com/spdk/spdk/issues?q=arm64) which mention `arm64`, so I assume Linux ARM64 is a supported platform.

## Current Behavior

`make` fails with:

```
config/arm/meson.build:239:2: ERROR: Problem encountered: Unsupported Arm implementer: 0x48. Please add support for it or use the generic (-Dmachine=generic) build.
```

## Steps to Reproduce

I've followed the steps from the README:

```
$ git clone https://github.com/spdk/spdk
$ cd spdk
$ git submodule update --init
$ ./scripts/pkgdep.sh
$ ./configure
$ make
```

but it fails with:

```
The Meson build system
Version: 0.58.1
Source dir: /home/ubuntu/git/spdk/dpdk
Build dir: /home/ubuntu/git/spdk/dpdk/build-tmp
Build type: native build
Program cat found: YES (/bin/cat)
Project name: DPDK
Project version: 21.02.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: aarch64
Host machine cpu: aarch64
Program pkg-config found: YES (/usr/bin/pkg-config)
Program list-dir-globs.py found: YES (/home/ubuntu/git/spdk/dpdk/buildtools/list-dir-globs.py)
Program check-symbols.sh found: YES (/home/ubuntu/git/spdk/dpdk/buildtools/check-symbols.sh)
Program options-ibverbs-static.sh found: YES (/home/ubuntu/git/spdk/dpdk/buildtools/options-ibverbs-static.sh)
Program binutils-avx512-check.sh found: YES (/home/ubuntu/git/spdk/dpdk/buildtools/binutils-avx512-check.sh)
Program python3 found: YES (/usr/bin/python3)
Program cat found: YES (/bin/cat)
Program ../buildtools/symlink-drivers-solibs.sh found: YES (/bin/sh /home/ubuntu/git/spdk/dpdk/config/../buildtools/symlink-drivers-solibs.sh)
Checking for size of "void *" : 8
Checking for size of "void *" : 8
Library m found: YES
Library numa found: YES
Has header "numaif.h" : YES 
Library libfdt found: YES
Has header "fdt.h" : YES 
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libbsd found: YES 0.10.0
Run-time dependency libpcap found: YES 1.9.1
Has header "pcap.h" with dependency libpcap: YES 
Compiler for C supports arguments -Wextra: YES 
config/meson.build:238: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C supports arguments -Wcast-qual: YES 
Compiler for C supports arguments -Wdeprecated: YES 
Compiler for C supports arguments -Wformat: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Wmissing-declarations: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -Wno-address-of-packed-member: YES 
Compiler for C supports arguments -Wno-packed-not-aligned: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Program /home/ubuntu/git/spdk/dpdk/config/arm/armv8_machine.py found: YES (/home/ubuntu/git/spdk/dpdk/config/arm/armv8_machine.py)

config/arm/meson.build:239:2: ERROR: Problem encountered: Unsupported Arm implementer: 0x48. Please add support for it or use the generic (-Dmachine=generic) build.

A full log can be found at /home/ubuntu/git/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
make[1]: *** [Makefile:164: /home/ubuntu/git/spdk/dpdk/build-tmp] Error 1
make: *** [/home/ubuntu/git/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
```

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 20.04.2 ARM64 (HiSilicon chip)
Project name: DPDK
Project version: 21.02.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: aarch64
Host machine cpu: aarch64

## Meson log

[meson-log.txt](https://github.com/spdk/spdk/files/6661632/meson-log.txt)

**Comment by AlekseyMarchuk** [comment]
I compile SPDK on arm64 with Ubuntu 20.04 quite often but didn't notice such a failure. I'm going to take a closer look at this issue.

**Comment by martin-g** [comment]
Thanks, @AlekseyMarchuk !
Please let me know if you need more information from me!

**Comment by martin-g** [comment]
Could this be related: https://patches.dpdk.org/project/dpdk/patch/1612356396-21309-2-git-send-email-oulijun@huawei.com/#128305 ?
I don't see `config/arm/arm64_kunpeng920_linux_gcc` at https://github.com/spdk/dpdk/tree/master/config/arm

**Comment by martin-g** [comment]
Yes! This was the problem! After manually applying the patch the build does not fail with this problem anymore !

**Comment by AlekseyMarchuk** [comment]
Great @martin-g thank you for your analysis. Currently SPDK uses this DPDK branch https://github.com/spdk/dpdk/tree/spdk-21.02 and `config/arm/arm64_kunpeng920_linux_gcc` is absent here as well. However SPDK will soon migrate to https://github.com/spdk/dpdk/tree/spdk-21.05 and this DPDK version provides this ARM config. I believe that the issue will be solved as soon as DPDK submodule is updated to 21.05. Until then, could you use your fix locally? You could also try to update DPDK submodule to https://github.com/spdk/dpdk/commit/175af25734f295874e31b33ccd0879e69fd152a9 but I'm not sure that it will work out of box.

**Comment by tomzawadzki** [comment]
The DPDK submodule is about to be updated. Patches from @KKaras169169 for the DPDK branch are outstanding https://review.spdk.io/gerrit/c/spdk/dpdk/+/8137. DPDK submodule update will follow up as those get merged.

**Comment by martin-g** [comment]
Thank you guys!

Feel free to close this ticket now or when 21.05 is landed!

**Comment by martin-g** [comment]
I confirm that the build on HiSilicon CPU is fixed now!
