### ISSUE TITLE
NVMf/vfio-user: "ASYNC LIMIT EXCEEDED" when booting Windows guest

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2000]
## Current Behavior

When Windows boots from a regular (non-NVMF/vfio-user) disk with an additional NVMf/vfio-user disk we get the following in the logs:
```
[2021-06-18 09:48:12.762161] nvme_qpair.c: 248:nvme_admin_qpair_print_command: *NOTICE*: ASYNC EVENT REQUEST (0c) qid:0 cid:10 nsid:0 cdw10:00000000 cdw11:00000000
[2021-06-18 09:48:12.762187] ctrlr.c:1718:nvmf_ctrlr_async_event_request: *DEBUG*: Async Event Request
[2021-06-18 09:48:12.762197] ctrlr.c:1727:nvmf_ctrlr_async_event_request: *DEBUG*: AERL exceeded
[2021-06-18 09:48:12.762204] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: ASYNC LIMIT EXCEEDED (01/05) qid:0 cid:10 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
```

## Steps to Reproduce

Simply boot a Windows guest from a regular disk with an NVMf/vfio-user disk attached.

## Context (Environment including OS version, SPDK version, etc.)

TODO

**Comment by jimharris** [comment]
Hi @tmakatos,

Do these debug prints not occur with a boot vfio-user disk, or have you just not tested that?  I'm not necessarily asking you to try it, but if you're getting different behavior based on whether it's a boot disk or not, that would be very strange.

Could you try increasing NVMF_MAX_ASYNC_EVENTS to something like 16, to see if this problem goes away?  I'm curious if Windows just has a hardcoded number of AERs it sends, or if it just keeps sending them until we report the limit is exceeded.  Either way, it seems Windows isn't respecting AERL.

Are there any other problems observed, other than these debug prints?

-Jim

**Comment by tmakatos** [comment]
> Do these debug prints not occur with a boot vfio-user disk, or have you just not tested that?

I haven't tried that, I'm planning to do so once a NVMf/vfio-user namespace is usable as a secondary disk.

> Could you try increasing NVMF_MAX_ASYNC_EVENTS to something like 16, to see if this problem goes away? I'm curious if Windows just has a hardcoded number of AERs it sends, or if it just keeps sending them until we report the limit is exceeded. Either way, it seems Windows isn't respecting AERL.

Sure will try.

> Are there any other problems observed, other than these debug prints?

Yes, I also get the following:
```
[2021-06-18 09:44:04.706777] vfio_user.c: 995:consume_admin_cmd: *DEBUG*: /var/tmp/vfio-user//8b0915f2-ebd8-4f08-9170-2e38b3fe9c6a/nvme/8b0915f2-ebd8-4f08-9170-2e38b3fe9c6a: handle admin req opc=0x9 cid=66
[2021-06-18 09:44:04.706788] nvme_qpair.c: 238:nvme_admin_qpair_print_command: *NOTICE*: SET FEATURES INTERRUPT COALESCING cid:66 cdw10:00000008 PRP1 0x0 PRP2 0x0                                                                              
[2021-06-18 09:44:04.706815] ctrlr.c:2791:nvmf_ctrlr_set_features: *ERROR*: Set Features command with unsupported feature ID 0x08
[2021-06-18 09:44:04.706841] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:0 cid:66 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
```
Maybe related to https://github.com/spdk/spdk/issues/1907#issuecomment-865360920.

There a couple of libvfio-user specific bugs (https://github.com/nutanix/libvfio-user/issues/570 and https://github.com/nutanix/libvfio-user/issues/571)

**Comment by jimharris** [comment]
I propose we don't try to support interrupt coalescing in the nvmf target for now.  I'm wondering if Windows is actually turning interrupt coalescing on though.  Could you instrument nvme_admin_qpair_print_command locally to also print out cdw11 for SET_FEATURES/GET_FEATURES?  (I wouldn't mind getting that change on master too, if you're up for pushing it to SPDK Gerrit. Or let me know and I'll get something pushed.)

If it's 0, then we can just check cdw11 for INTERRUPT_COALESCING feature and squash the error if it's 0.

**Comment by tmakatos** [comment]
@jimharris 

> > Could you try increasing NVMF_MAX_ASYNC_EVENTS to something like 16, to see if this problem goes away? I'm curious if > > Windows just has a hardcoded number of AERs it sends, or if it just keeps sending them until we report the limit is 
> > exceeded. Either way, it seems Windows isn't respecting AERL.
>
> Sure will try.

I tried that and I got the same error. It turns out that `NVMF_MAX_ASYNC_EVENTS` isn't honored by the NVMf/vfio-user target. `test/nvmf/target/nvmf_vfio_user.sh` reports:
```
Async Event Request Limit:             1
```
And I also checked with `nvme-cli` in a Linux guest and it reports it as 0 (which is 1 since it's a zero-based value).

I seem to remember that I had hard coded AERL to 0 for some reason, but can't find it in the code anymore. Maybe @changpe1 could shed some light here?

**Comment by changpe1** [comment]
Currently SPDK library already hardcoded aerl to 0, and set the discovery controller aerl to 3, looks like that the Windows doesn't respect this value, I will setup a Windows environment to see what happened.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/8487 will remove the ERRLOG associated with the INTERRUPT COALESCING feature mentioned in this thread.  This patch does not affect the ASYNC LIMIT EXCEEDED issue.

**Comment by jimharris** [comment]
It's not clear to me why we need to still hardcode AERL to 0 for non-discovery controllers.  This was set to 0 for non-discovery controllers in the original nvmf code from what I can tell (commit bf6caa753), but more recently we've added support for queuing multiple AERs (commit 8cd9ef28 to queue events until target receives an AER, commit b7cc4dd to support multiple AERs).

In fact, I'm not even sure how much b7cc4dd was really tested.  It sets cdata->aerl at the beginning of the function, but still overwrites it with 0 when we see it's a non-discovery controller.

I really think that  https://review.spdk.io/gerrit/c/spdk/spdk/+/8488 fixes this.  @tmakatos could you try this patch and see if this eliminates that DEBUGLOG "AERL exceeded"?

**Comment by jimharris** [comment]
b7cc4dd has at least one bug it that would need fixing as part of this 8488 patch I just posted.  It uses an array of req pointers for the AERs as a stack, but doesn't properly manage the stack should if we get an abort for one of the AERs.

@tmakatos it would still be helpful if you could see if this eliminates that DEBUGLOG though.

@changpe1 or @optimistyzy could one of you take a further look at this?  We need some tests to make sure this is working correctly.

**Comment by changpe1** [comment]
> [b7cc4dd](https://github.com/spdk/spdk/commit/b7cc4dd7dd81c6c312c96da336b6a1726583a577) has at least one bug it that would need fixing as part of this 8488 patch I just posted. It uses an array of req pointers for the AERs as a stack, but doesn't properly manage the stack should if we get an abort for one of the AERs.
> 
> @tmakatos it would still be helpful if you could see if this eliminates that DEBUGLOG though.
> 
> @changpe1 or @optimistyzy could one of you take a further look at this? We need some tests to make sure this is working correctly.

OK, I will add some AER tests to NVMf.

**Comment by tmakatos** [comment]
> I really think that https://review.spdk.io/gerrit/c/spdk/spdk/+/8488 fixes this. @tmakatos could you try this patch and see if this eliminates that DEBUGLOG "AERL exceeded"?

I tried that and I still get the same error. I also double-checked with a Linux guest and `nvme-cli` reports AERL of 15, which is correct since I've still set `NVMF_MAX_ASYNC_EVENTS` to 16.

**Comment by jimharris** [comment]
> > I really think that https://review.spdk.io/gerrit/c/spdk/spdk/+/8488 fixes this. @tmakatos could you try this patch and see if this eliminates that DEBUGLOG "AERL exceeded"?
> 
> I tried that and I still get the same error. I also double-checked with a Linux guest and `nvme-cli` reports AERL of 15, which is correct since I've still set `NVMF_MAX_ASYNC_EVENTS` to 16.

OK, sounds like maybe Windows just keeps sending AERs until we report that they've sent to many?  That would be really bizarre though.

@changpe1 once you get your environment up and running, can you add some debug logs to confirm that with my 8488 patch that we accept the first 4 AERs correctly and only fail once we get the 5th one?

**Comment by changpe1** [comment]
> > > I really think that https://review.spdk.io/gerrit/c/spdk/spdk/+/8488 fixes this. @tmakatos could you try this patch and see if this eliminates that DEBUGLOG "AERL exceeded"?
> > 
> > 
> > I tried that and I still get the same error. I also double-checked with a Linux guest and `nvme-cli` reports AERL of 15, which is correct since I've still set `NVMF_MAX_ASYNC_EVENTS` to 16.
> 
> OK, sounds like maybe Windows just keeps sending AERs until we report that they've sent to many? That would be really bizarre though.
> 
> @changpe1 once you get your environment up and running, can you add some debug logs to confirm that with my 8488 patch that we accept the first 4 AERs correctly and only fail once we get the 5th one?

OK.

**Comment by changpe1** [comment]
Link to https://github.com/spdk/spdk/issues/2016, this is a bug in vfio-user target, we didn't abort the previous submitted AERs when doing controller reset, I will submit a fix patch.

**Comment by jimharris** [comment]
Patches merged.
