### ISSUE TITLE
run bdevperf with debug log, it is great there is one option that enable dump all details nvme_commands for trace and analysis 

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2010]
## Expected Behavior
run bdevperf with debug log, it is great there is one option that enable dump all details nvme_commands for trace and analysis 
currently only nvmf has this feature. we need it in the local nvme device too.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
bdevperf already has "-L nvme" option to enable the NVMe driver debug log, not sure this can meet your requirement or not.

**Comment by gaowayne** [comment]
@changpe1 I checked it cannot meet my expectation. I add below print code to meet my expectation. currently this print only print nvmf requests, not for local nvme device

	rc = _nvme_qpair_submit_request(qpair, req);
	if(0 == rc)
		spdk_nvme_print_command(qpair->id, &req->cmd);

**Comment by changpe1** [comment]
OK, I will push a fix to add the NVMe command trace.

**Comment by changpe1** [comment]
@gaowayne Can you try if https://review.spdk.io/gerrit/c/spdk/spdk/+/8493 can meet your request?

**Comment by jimharris** [comment]
Patch merged.
