### ISSUE TITLE
CFLAGS ignored if set before build

### ISSUE THREAD

**Issue by brianjmurrell** [spdk/spdk#2011]
In configure, any `CFLAGS` that are gathered, are added to `$rootdir/mk/cc.flags.mk` with https://github.com/spdk/spdk/blob/5fc0475c140b86802ab8759a43845dcc34e7329d/configure#L886

But because the assignment in that Makefile fragment is assigning with `?=` those `CFLAGS` are only used if the caller has not set any.

It's not atypical for packaging systems such as RPM or DEB to set some `CFLAGS` before doing their build, to enforce platform specific requirements, to harden builds, or make processor portable binaries for example.

I'm wondering what your thoughts are regarding this.  Should that `CFLAGS` assignment really only be effective if the caller has not set any `CFLAGS` himself, or should that assignment be _additive_ to the caller's defined `CFLAGS`?

**Comment by mikeBashStuff** [comment]
Interesting topic to raise. :)

So currently I believe you can do something like this:

`CFLAGS=-my-super-cflags ./configure ...` 
or 
`CFLAGS=-my-super-cflags make ...`

both yielding same result in context of the SPDK build, i.e.,  the final `CFLAGS` will consist of what was defined in the env + what mk decided to add (the notable difference is that what's passed to make through env will end up also picked up by other pieces, like DPDK). 

As you stated in the description, with `CFLAGS=... make ...` what was added to `cc.flags.mk` via `./configure` won't be included in the final `CFLAGS`.  So in case it's known that given packaging system does indeed set extra `CFLAGS` in the environment you could just expand on that instead of relaying on `./configure`:
```
...
CFLAGS=${CFLAGS:+$CFLAGS }-my-super-cflags
# don't set CFLAGS via ./configure let make to pick it up
CFLAGS= ./configure ...
CFLAGS=$CFLAGS make ...
# or just this since we know cc.flags.mk is going to be ignored anyway
export CFLAGS=${CFLAGS:+$CFLAGS }-my-super-cflags
./configure ...
make ...
```

Or you can override it completely via `make CFLAGS="$CFLAGS -my-super-cflags"`  

So technically speaking, `CFLAGS` is handled, sort of, in an additive manner (it can be also fully customized). But regarding the main point of interest here: should  `CFLAGS=-my-super-cflags0 ./configure` and `CFLAGS=-my-super-cflags1 make` yield `CFLAGS=-my-super-cflags0 -my-super-cflags1 ...`?  Not sure about anyone else, but I guess it would be nice to have that,  yes. :)

**Comment by jimharris** [comment]
Or we could keep the current CFLAGS behavior, but add ability for user to specify extra flags using EXTRA_CFLAGS.  So then:

```
CFLAGS=xxx make
```

would replace the CFLAGS specified by configure, while:

```
EXTRA_CFLAGS=xxx make
```

would append to the CFLAGS specified by configure.

**Comment by brianjmurrell** [comment]
> Interesting topic to raise. :)

Thanks.  I try to keep things interesting.  :smile: 

> So currently I believe you can do something like this:
> 
> `CFLAGS=-my-super-cflags ./configure ...`
> or
> `CFLAGS=-my-super-cflags make ...`

I don't think you can.  Example:

```
$ echo "CFLAGS=$CFLAGS"
CFLAGS=-g -O2 -fdebug-prefix-map=/build/spdk-21.04=. -fstack-protector-strong -Wformat -Werror=format-security 
$ bash -x ./configure --prefix=/usr \
            --disable-tests \
            --without-vhost \
            --without-crypto \
            --without-pmdk \
            --without-rbd \
            --with-rdma \
            --with-shared \
            --without-iscsi-initiator \
            --without-isal \
            --without-vtune \
            --with-dpdk
…
+ pkg-config --exists libdpdk
++ pkg-config --variable=libdir libdpdk
+ CONFIG[DPDK_LIB_DIR]=/usr/lib/x86_64-linux-gnu
++ pkg-config --variable=includedir libdpdk
+ CONFIG[DPDK_INC_DIR]=/usr/include/dpdk
+ CONFIG[DPDK_PKG_CONFIG]=y
+ CONFIG[SHARED]=y
++ pkg-config --cflags libdpdk
+ CFLAGS='-g -O2 -fdebug-prefix-map=/build/spdk-21.04=. -fstack-protector-strong -Wformat -Werror=format-security  -include rte_config.h -march=corei7 -I/usr/include/dpdk -I/usr/include/libnl3 -I/usr/include/dpdk/../x86_64-linux-gnu/dpdk -I/usr/include/dpdk'
…
+ echo 'CFLAGS?=-g -O2 -fdebug-prefix-map=/build/spdk-21.04=. -fstack-protector-strong -Wformat -Werror=format-security  -include rte_config.h -march=corei7 -I/usr/include/dpdk -I/usr/include/libnl3 -I/usr/include/dpdk/../x86_64-linux-gnu/dpdk -I/usr/include/dpdk'
…
$ echo "CFLAGS=$CFLAGS"
CFLAGS=-g -O2 -fdebug-prefix-map=/build/spdk-21.04=. -fstack-protector-strong -Wformat -Werror=format-security 
$ make V=1
…
echo "  CC lib/event/dpdk_governor.o"; cc -o dpdk_governor.o -MMD -MP -MF dpdk_governor.d.tmp -g -O2 -fdebug-prefix-map=/build/spdk-21.04=. -fstack-protector-strong -Wformat -Werror=format-security  -g  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-declarations -fno-strict-aliasing -I/build/spdk-21.04/include -march=native -Wformat -Wformat-security -D_GNU_SOURCE -fPIC -fstack-protector -fno-common -DNDEBUG -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -pthread -Wno-pointer-sign -Wstrict-prototypes -Wold-style-definition -std=gnu99 -g  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-declarations -fno-strict-aliasing -I/build/spdk-21.04/include -march=native -Wformat -Wformat-security -D_GNU_SOURCE -fPIC -fstack-protector -fno-common -DNDEBUG -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -pthread -Wno-pointer-sign -Wstrict-prototypes -Wold-style-definition -std=gnu99 -g  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-declarations -fno-strict-aliasing -I/build/spdk-21.04/include -march=native -Wformat -Wformat-security -D_GNU_SOURCE -fPIC -fstack-protector -fno-common -DNDEBUG -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -pthread -Wno-pointer-sign -Wstrict-prototypes -Wold-style-definition -std=gnu99 -I/usr/include/dpdk -DALLOW_EXPERIMENTAL_API -g  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-declarations -fno-strict-aliasing -I/build/spdk-21.04/include -march=native -Wformat -Wformat-security -D_GNU_SOURCE -fPIC -fstack-protector -fno-common -DNDEBUG -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -pthread -Wno-pointer-sign -Wstrict-prototypes -Wold-style-definition -std=gnu99 -c dpdk_governor.c && mv -f dpdk_governor.d.tmp dpdk_governor.d && touch -c dpdk_governor.o
  CC lib/event/dpdk_governor.o
In file included from /usr/include/dpdk/rte_power.h:13,
                 from dpdk_governor.c:40:
/usr/include/dpdk/rte_common.h:25:10: fatal error: rte_config.h: No such file or directory
   25 | #include <rte_config.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

As you can see, the `CFLAGS` that `configure` stuffed into `mk/cc.flags.mk` was still not used, unsurprisingly.
 
> both yielding same result in context of the SPDK build, i.e., the final `CFLAGS` will consist of what was defined in the env + what mk decided to add

So yes, while this is true, the resulting `mk/cc.flags.mk` is still ignored due to the presence of `CFLAGS` in the environment of `make`'s caller.

> So in case it's known that given packaging system does indeed set extra `CFLAGS` in the environment you could just expand on that instead of relaying on `./configure`:

Indeed, that is what I have done for the Ubuntu build.  In `debian/rules`:

```
export DEB_CFLAGS_MAINT_APPEND = $(shell pkg-config --cflags libdpdk)
```

This just doesn't seem to scale very well, in that a packager needs to know (i.e. too much about your `configure`'s internal workings and) to do this and needs to expand their calling `CFLAGS` to include any future possible `pkg-config` calls that your `configure` might introduce.

**Comment by brianjmurrell** [comment]
> Or we could keep the current CFLAGS behavior, but add ability for user to specify extra flags using EXTRA_CFLAGS. So then:
> 
> ```
> CFLAGS=xxx make
> ```
> 
> would replace the CFLAGS specified by configure, while:
> 
> ```
> EXTRA_CFLAGS=xxx make
> ```
> 
> would append to the CFLAGS specified by configure.

Where any environment (packaging or otherwise) that sets a CFLAGS would then have to (know to) do:

```
EXTRA_CFLAGS="$CFLAGS" make
```

when building spdk.  It's not ideal, but just expanding above , so that it's obvious how this would interact with build environments.

Not trying to be difficult.  Just trying to aim for the principle of least surprise.

**Comment by jimharris** [comment]
[Bug Scrub] Jim will look at what autotools does in this regard to help guide what we should do for SPDK.

**Comment by jimharris** [comment]
It seems other projects are all over the map on this.  I ran some tests with isa-l, fio and Qemu to see how they handle this situation.  In none of the cases did the CFLAGS env variable at make time get appended to the CFLAGS set at configure time.  In two cases that are completely ignored, in the third case they are added but not in a useful way.

Based on this I'd lean towards making SPDK just ignore CFLAGS set in the environment at build time.

@brianjmurrell please advise if you have any examples of other projects that append CFLAGS as described earlier in this thread.

Thanks,

-Jim

In each case I configured using:

```
CFLAGS="-O3 -g" ./configure
```

Then I tried setting CFLAGS as both an environment variable and a make parameter:

```
V=1 CFLAGS="-g -O1" make
V=1 make CFLAGS="-g -O1"
```

isa-l:
CFLAGS as environment variable: not used
CFLAGS as make parameter: replaces those set during configure

fio:
CFLAGS as environment variable: they get added, but not in a useful way; the CFLAGS specified at configure time show up twice during compilation, and the CFLAGS specified by the environment variable during make get inserted between those two instances
CFLAGS as make parameter: they get added, after the CFLAGS specified at configure time

Qemu:
CFLAGS as environment variable: not used
CFLAGS as make parameter: not used

**Comment by jimharris** [comment]
@brianjmurrell - going back through some old bug reports, and there was an open question here.  Do you have examples of other projects that append CFLAGS as described in the description?  Or if this is no longer impacting you, can this bug report be closed?
