### ISSUE TITLE
NVMf segment fault when running "nvme disconnect" command

### ISSUE THREAD

**Issue by changpe1** [spdk/spdk#2015]
## Current Behavior

Segmentation fault (core dumped)

## Steps to Reproduce

1. build/bin/nvmf_tgt -L nvmf
2. scripts/rpc.py nvmf_create_transport -t TCP
3. scripts/rpc.py nvmf_create_subsystem -a nqn.2019-07.io.spdk:cnode0
4. scripts/rpc.py bdev_malloc_create -b malloc0 $((512)) 512
5. scripts/rpc.py nvmf_subsystem_add_ns -n 1 nqn.2019-07.io.spdk:cnode0 malloc0
6. scripts/rpc.py bdev_malloc_create -b malloc1 $((512)) 512
7. scripts/rpc.py nvmf_subsystem_add_ns -n 2 nqn.2019-07.io.spdk:cnode0 malloc1
8. scripts/rpc.py nvmf_subsystem_add_listener -t tcp -a 127.0.0.1 -s 4420 nqn.2019-07.io.spdk:cnode0
9. nvme connect -t tcp -n "nqn.2019-07.io.spdk:cnode0" -a 127.0.0.1 -s 4420
10. nvme list
11. nvme disconnect -n nqn.2019-07.io.spdk:cnode0

BT trace:
#0  0x0000000000479c0d in posix_sock_group_impl_remove_sock (_group=0x20d03e0, _sock=0x286e9b0) at posix.c:1302
1302                    TAILQ_REMOVE(&group->socks_with_data, sock, link);
[Current thread is 1 (Thread 0x7f02db3d19c0 (LWP 25560))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-29.fc30.x86_64 json-c-0.13.1-12.fc30.x86_64 libaio-0.3.111-4.fc30.x86_64 libuuid-2.33.2-2.fc30.x86_64 numactl-libs-2.0.12-2.fc30.x86_64 openssl-libs-1.1.1d-2.fc30.x86_64 zlib-1.2.11-19.fc30.x86_64
(gdb) bt
#0  0x0000000000479c0d in posix_sock_group_impl_remove_sock (_group=0x20d03e0, _sock=0x286e9b0) at posix.c:1302
#1  0x0000000000512d80 in spdk_sock_group_remove_sock (group=0x20d03c0, sock=0x286e9b0) at sock.c:586
#2  0x00000000004a9977 in nvmf_tcp_poll_group_remove (group=0x20d0330, qpair=0x286ea60) at tcp.c:2707
#3  0x00000000004a14b0 in nvmf_transport_poll_group_remove (group=0x20d0330, qpair=0x286ea60) at transport.c:507
#4  0x000000000049973e in spdk_nvmf_poll_group_remove (qpair=0x286ea60) at nvmf.c:991
#5  0x0000000000499625 in _nvmf_transport_qpair_fini (ctx=0x214e620) at nvmf.c:957
#6  0x000000000050b987 in msg_queue_run_batch (thread=0x20b6730, max_msgs=8) at thread.c:688
#7  0x000000000050c18e in thread_poll (thread=0x20b6730, max_msgs=0, now=4708205466007338) at thread.c:906
#8  0x000000000050c31b in spdk_thread_poll (thread=0x20b6730, max_msgs=0, now=4708205466007338) at thread.c:966
#9  0x000000000047e80b in _reactor_run (reactor=0x20b2d80) at reactor.c:924
#10 0x000000000047e8f9 in reactor_run (arg=0x20b2d80) at reactor.c:962
#11 0x000000000047ed22 in spdk_reactors_start () at reactor.c:1070
#12 0x000000000047b8b7 in spdk_app_start (opts_user=0x7ffc319ebc80, start_fn=0x4068ff <nvmf_tgt_started>, arg1=0x0) at app.c:579
#13 0x0000000000406a51 in main (argc=3, argv=0x7ffc319ebe28) at nvmf_main.c:75

## Context (Environment including OS version, SPDK version, etc.)

SPDK latest master commit bb8102b1ff
5.6.13-100.fc30.x86_64

**Comment by optimistyzy** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/8541  This patch can fix this issue. For the rotation of the list, I suggest do not use the   low level operation. Since the maximal event is 32, so we will only need 32 times for loop for the worst cases.

**Comment by changpe1** [comment]
Tested after this commit and it fixes the issue, closing it for now.

**Comment by adamagniv** [comment]
@jonathan-teh you got mixed between #2105 and #2015 in the commit message :P
