### ISSUE TITLE
NVMf/vfio-user Namespace notice AER doesn't work as expected

### ISSUE THREAD

**Issue by changpe1** [spdk/spdk#2016]
## Expected Behavior

Hot remove/add a Namespace can be showed in the Guest

## Current Behavior

Hot remove a Namespace in the host, the Guest still can see the removed Namespace

## Steps to Reproduce

Start nvmf target:
build/bin/nvmf_tgt -L nvmf -L nvmf_vfio
scripts/rpc.py nvmf_create_transport -t VFIOUSER
scripts/rpc.py nvmf_create_subsystem -a nqn.2019-07.io.spdk:cnode0
scripts/rpc.py bdev_malloc_create -b malloc0 $((512)) 512
scripts/rpc.py nvmf_subsystem_add_ns -n 1 nqn.2019-07.io.spdk:cnode0 malloc0
scripts/rpc.py bdev_malloc_create -b malloc1 $((512)) 512
scripts/rpc.py nvmf_subsystem_add_ns -n 2 nqn.2019-07.io.spdk:cnode0 malloc1
scripts/rpc.py nvmf_subsystem_add_listener -t VFIOUSER -a "/var/run/muser/domain/muser0/8" -s 0 nqn.2019-07.io.spdk:cnode0

Start QEMU:
qemu-oracle/build/qemu-system-x86_64 -cpu host -smp 1 -enable-kvm -m 4G -object memory-backend-file,id=mem0,size=4G,mem-path=/dev/hugepages,share=on,prealloc=yes, -numa node,memdev=mem0 -drive file=/root/fedora_33.img,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -device vfio-user-pci,socket=/var/run/muser/domain/muser0/8/cntrl,x-enable-migration=true -net user,hostfwd=tcp::10022-:22 -net nic -trace enable=vfio* -vnc 0.0.0.0:1 -monitor telnet::4444,server,nowait

Log into VM:
nvme list and there are two namespaces showed in the Guest

Remove Namespace:
scripts/rpc.py nvmf_subsystem_remove_ns nqn.2019-07.io.spdk:cnode0 1

The removed Namespace is still exist in the Guest

## Context (Environment including OS version, SPDK version, etc.)
SPDK latest commit
Fedora 33 Guest VM

**Comment by changpe1** [comment]
Link this issue to https://github.com/spdk/spdk/issues/2000

**Comment by changpe1** [comment]
Here is the patch to fix this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/8556.

**Comment by jimharris** [comment]
Patches merged.
