### ISSUE TITLE
[crypto-autotest] Failure to build

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#2017]
## Link to the failed CI build

http://10.211.11.56/results/autotest-per-patch/builds/51166/archive/crypto-autotest/build.log

## Execution failed at

**00:15:06.955   07:32:43	# /var/jenkins/workspace/crypto-autotest/spdk/scripts/setup.sh cleanup
00:15:07.153  ls: cannot access '/dev/shm/*': No such file or directory**
00:15:08.099  Cleaning
00:15:08.102  Removing:    /run/dpdk/spdk0/config
00:15:08.105  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-0
00:15:08.108  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-1
00:15:08.111  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-2
00:15:08.114  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-0-3
00:15:08.116  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-0
00:15:08.119  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-1
00:15:08.122  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-2
00:15:08.125  Removing:    /run/dpdk/spdk0/fbarray_memseg-2048k-1-3
00:15:08.128  Removing:    /run/dpdk/spdk0/fbarray_memzone
00:15:08.131  Removing:    /run/dpdk/spdk0/hugepage_info
00:15:08.134  Removing:    /run/dpdk/spdk0/mp_socket
00:15:08.136  Removing:    /var/run/dpdk/spdk0
00:15:08.139  Clean
00:15:08.140    07:32:45	# uname -s
00:15:08.142   07:32:45	# '[' Linux = Linux ']'
00:15:08.142   07:32:45	# [[ 0 -eq 1 ]]
00:15:08.143   07:32:45	# modprobe -r uio_pci_generic
00:15:08.161   07:32:45	# rm -rf /var/tmp/asan_suppression_file
00:15:08.163   07:32:45	# [[ -n |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h ]]
00:15:08.163   07:32:45	# echo '|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h'
00:15:08.163   07:32:45	# [[ -e /proc/147304/status ]]
00:15:08.163   07:32:45	# kill 147304
00:15:08.164   07:32:45	# revert_soft_roce
00:15:08.164   07:32:45	# rxe_cfg stop
00:15:08.164   07:32:45	# /var/jenkins/workspace/crypto-autotest/spdk/scripts/rxe_cfg_small.sh stop
00:15:08.177   07:32:45	# shopt -s nullglob
00:15:08.177   07:32:45	# storage_fallback_purge=("${TMPDIR:-/tmp}/spdk."??????)
00:15:08.178   07:32:45	# local storage_fallback_purge
00:15:08.178   07:32:45	# shopt -u nullglob
00:15:08.178   07:32:45	# (( 27 > 0 ))
00:15:08.179   07:32:45	# printf '* Purging old temporary test storage (%s)\n' '/tmp/spdk.4F8nGa /tmp/spdk.52tLYA /tmp/spdk.6hUX5C /tmp/spdk.8ktN1O /tmp/spdk.8qAw22 /tmp/spdk.aQiAT7 /tmp/spdk.b1TY48 /tmp/spdk.BwpzHZ /tmp/spdk.DcddNK /tmp/spdk.dpH5WA /tmp/spdk.eeudrL /tmp/spdk.ez0npW /tmp/spdk.fDZZI4 /tmp/spdk.fVlLE1 /tmp/spdk.HY4eX6 /tmp/spdk.jZH4XE /tmp/spdk.kIPdtA /tmp/spdk.KNevVN /tmp/spdk.nFqH2i /tmp/spdk.PYGNvF /tmp/spdk.pymaAQ /tmp/spdk.S2YjoH /tmp/spdk.tehc5D /tmp/spdk.UAuenG /tmp/spdk.vTRtC3 /tmp/spdk.vywhZ9 /tmp/spdk.yRb5af'
00:15:08.179  * Purging old temporary test storage (/tmp/spdk.4F8nGa /tmp/spdk.52tLYA /tmp/spdk.6hUX5C /tmp/spdk.8ktN1O /tmp/spdk.8qAw22 /tmp/spdk.aQiAT7 /tmp/spdk.b1TY48 /tmp/spdk.BwpzHZ /tmp/spdk.DcddNK /tmp/spdk.dpH5WA /tmp/spdk.eeudrL /tmp/spdk.ez0npW /tmp/spdk.fDZZI4 /tmp/spdk.fVlLE1 /tmp/spdk.HY4eX6 /tmp/spdk.jZH4XE /tmp/spdk.kIPdtA /tmp/spdk.KNevVN /tmp/spdk.nFqH2i /tmp/spdk.PYGNvF /tmp/spdk.pymaAQ /tmp/spdk.S2YjoH /tmp/spdk.tehc5D /tmp/spdk.UAuenG /tmp/spdk.vTRtC3 /tmp/spdk.vywhZ9 /tmp/spdk.yRb5af)
00:15:08.179   07:32:45	# rm -rf /tmp/spdk.4F8nGa /tmp/spdk.52tLYA /tmp/spdk.6hUX5C /tmp/spdk.8ktN1O /tmp/spdk.8qAw22 /tmp/spdk.aQiAT7 /tmp/spdk.b1TY48 /tmp/spdk.BwpzHZ /tmp/spdk.DcddNK /tmp/spdk.dpH5WA /tmp/spdk.eeudrL /tmp/spdk.ez0npW /tmp/spdk.fDZZI4 /tmp/spdk.fVlLE1 /tmp/spdk.HY4eX6 /tmp/spdk.jZH4XE /tmp/spdk.kIPdtA /tmp/spdk.KNevVN /tmp/spdk.nFqH2i /tmp/spdk.PYGNvF /tmp/spdk.pymaAQ /tmp/spdk.S2YjoH /tmp/spdk.tehc5D /tmp/spdk.UAuenG /tmp/spdk.vTRtC3 /tmp/spdk.vywhZ9 /tmp/spdk.yRb5af
00:15:08.180   07:32:45	# timing_exit cleanup
00:15:08.181   07:32:45	# xtrace_disable
00:15:08.181   07:32:45	# '[' no '!=' yes ']'
00:15:08.181   07:32:45	# PREV_BASH_OPTS=ehxBET
00:15:08.181   07:32:45	# [[ ehxBET == *\x* ]]
00:15:08.181   07:32:45	# XTRACE_DISABLED=yes
00:15:08.182   07:32:45	# set +x
00:15:08.199   07:32:45	# xtrace_enable
00:15:08.200   07:32:45	# timing_exit autotest
00:15:08.200   07:32:45	# xtrace_disable
00:15:08.200   07:32:45	# '[' no '!=' yes ']'
00:15:08.200   07:32:45	# PREV_BASH_OPTS=ehxBET
00:15:08.200   07:32:45	# [[ ehxBET == *\x* ]]
00:15:08.201   07:32:45	# XTRACE_DISABLED=yes
00:15:08.201   07:32:45	# set +x
00:15:08.220   07:32:45	# xtrace_enable
00:15:08.220   07:32:45	# chmod a+r /var/jenkins/workspace/crypto-autotest/spdk/../output/timing.txt
00:15:08.222   07:32:45	# trap - SIGINT SIGTERM EXIT
00:15:08.222   07:32:45	# process_core
00:15:08.223   07:32:45	# local es=0
00:15:08.223   07:32:45	# (( es != 0 ))
00:15:08.223   07:32:45	# local coredumps core
00:15:08.223   07:32:45	# shopt -s nullglob
00:15:08.223   07:32:45	# coredumps=("$output_dir/coredumps/"*.bt.txt)
00:15:08.224   07:32:45	# shopt -u nullglob
00:15:08.224   07:32:45	# (( 0 > 0 ))
00:15:08.224   07:32:45	# return 0
00:15:08.225   07:32:45	# hash lcov
00:15:08.225   07:32:45	# [[ CC_TYPE=gcc == *\c\l\a\n\g* ]]
00:15:08.225    07:32:45	# hostname
00:15:08.225   07:32:45	# lcov --rc lcov_branch_coverage=1 --rc lcov_function_coverage=1 --rc genhtml_branch_coverage=1 --rc genhtml_function_coverage=1 --rc genhtml_legend=1 --rc geninfo_all_blocks=1 --no-external -q -c -d /var/jenkins/workspace/crypto-autotest/spdk -t spdk-GP-03 -o /var/jenkins/workspace/crypto-autotest/spdk/../output/cov_test.info
00:15:08.411  geninfo: WARNING: invalid characters removed from testname!
00:15:27.049   07:33:04	# lcov --rc lcov_branch_coverage=1 --rc lcov_function_coverage=1 --rc genhtml_branch_coverage=1 --rc genhtml_function_coverage=1 --rc genhtml_legend=1 --rc geninfo_all_blocks=1 --no-external -q -a /var/jenkins/workspace/crypto-autotest/spdk/../output/cov_base.info -a /var/jenkins/workspace/crypto-autotest/spdk/../output/cov_test.info -o /var/jenkins/workspace/crypto-autotest/spdk/../output/cov_total.info
00:15:28.847  Build timed out (after 15 minutes). Marking the build as failed.
00:15:28.858  Build was aborted
00:15:28.860  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:28.866  [crypto-autotest] $ /usr/bin/env bash /tmp/jenkins8264005054175675365.sh
00:15:28.869  Start stage post_get_build_log.sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51082.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51171.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51202.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51214.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_51196.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_51229.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_51227.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51239.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jonathan-teh. log: https://ci.spdk.io/public_build/autotest-per-patch_51254.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51260.html

**Comment by jimharris** [comment]
[Bug Scrub] This test has always run near the 15 minute timeout.  Just noticed that HT on GP3 was disabled, which could have affected test runs on those systems.  HT enabled now, let's see if that impacts failure rate.

Michal has a patch that reduces crypto length, including removing dd test (which also runs in other jobs).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_51242.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_51404.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51412.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51414.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_51477.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_51468.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jonathan-teh. log: https://ci.spdk.io/public_build/autotest-per-patch_51535.html

**Comment by mikeBashStuff** [comment]
Potential fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/8545

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_51606.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_51581.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_51608.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_51590.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @the-castle. log: https://ci.spdk.io/public_build/autotest-per-patch_51526.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @the-castle. log: https://ci.spdk.io/public_build/autotest-per-patch_51794.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51793.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51813.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51819.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51837.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_51843.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51874.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51970.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_51984.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_52009.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_51852.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_52314.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_51960.html
