### ISSUE TITLE
NVMf/vfio-user: SeaBIOS doesn't boot from NVMe namespace

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2019]
Using SPDK master (bb8102b1ffc8bf209d7da4e545c2f8b645aa9372), SeaBIOS doesn't boot from the NVMe controller. It does identify the namespace but then don't seem to progress booting, it simply waits:
```
|7ffa5000| Registering bootable: NVMe NS 1: 11264 MiB (2883584 4096-byte blocks + 0-byte metadata)
...
Booting from Hard Disk...
Booting from 0000:7c00
```
[debian.zip](https://github.com/spdk/spdk/files/6739534/debian.zip)

**Comment by changpe1** [comment]
Link this issue to https://github.com/spdk/spdk/issues/2020

**Comment by tomzawadzki** [comment]
@changpe1 Are you suggesting this issue is the same as #2020 and therefore this one can be closed ?

**Comment by changpe1** [comment]
Yeah, so closing this issue for now, just leave #2020  opened.

**Comment by tmakatos** [comment]
@changpe1 this issue is not related to #2020. Rather, #2019 blocks reproducing #2020.

**Comment by changpe1** [comment]
> @changpe1 this issue is not related to #2020. Rather, #2019 blocks reproducing #2020.

OK, since the patch for #2020 has been merged, so I close #2020 and reopen this one.

**Comment by changpe1** [comment]
I just tested in my environment, and the Seabios worked for me to boot from it. Here is the steps I used:
1. Create a raw image
2. scripts/rpc.py bdev_aio_create /root/fedora_33_raw.img aio_bdev0 512

The command line in QEMU is `device vfio-user-pci,socket=/var/run/muser/domain/muser1/9/cntrl,bootindex=0`

**Comment by changpe1** [comment]
I think the key part is that you are using 4096 as the block size, when I use 4096 as the block size, I see the same issue, but 512 works well.

**Comment by tmakatos** [comment]
Then I suppose this is something that we need to fix in SeaBIOS.

**Comment by changpe1** [comment]
Not a SPDK issue, closing it now.
