### ISSUE TITLE
Segfault in iscsi_tgt

### ISSUE THREAD

**Issue by devilsgrotto** [spdk/spdk#202]
This checkin seems to introduce a segfault in iscsi_tgt:
d3828a2 scsi: remove LUN I/O channel ref counting

I can repro this by simply running IO from a iscsi initiator.

(gdb) back
#0  __submit_request (bdev=0x7f3ef1b2e980, bdev_io=0x7f3efa4f5300) at bdev.c:577
#1  spdk_bdev_io_submit (bdev_io=0x7f3efa4f5300) at bdev.c:588
#2  spdk_bdev_writev (desc=<optimized out>, ch=<optimized out>, iov=0x7f3eae6232f8, iovcnt=1, offset=260120576, len=<optimized out>, cb=cb@entry=0x42fa30 <spdk_bdev_scsi_task_complete_cmd>, 
    cb_arg=cb_arg@entry=0x7f3eae623280) at bdev.c:929
#3  0x000000000043014f in spdk_bdev_scsi_write (len=1024, lba=507904, task=0x7f3eae623280, bdev=0x7f3ef1b2e980) at scsi_bdev.c:1360
#4  spdk_bdev_scsi_readwrite (bdev=bdev@entry=0x7f3ef1b2e980, task=task@entry=0x7f3eae623280, lba=507904, xfer_len=1024, is_read=<optimized out>) at scsi_bdev.c:1475
#5  0x0000000000430613 in spdk_bdev_scsi_process_block (task=0x7f3eae623280, bdev=0x7f3ef1b2e980) at scsi_bdev.c:1666
#6  spdk_bdev_scsi_execute (bdev=0x7f3ef1b2e980, task=task@entry=0x7f3eae623280) at scsi_bdev.c:2021
#7  0x000000000042f043 in spdk_scsi_lun_execute_tasks (lun=0x2727db0) at lun.c:203
#8  0x000000000042e87f in spdk_scsi_dev_queue_task (dev=<optimized out>, task=task@entry=0x7f3eae623280) at dev.c:210
#9  0x000000000041e087 in spdk_iscsi_queue_task (task=task@entry=0x7f3eae623280, conn=<optimized out>, conn=<optimized out>) at iscsi.c:2854
#10 0x00000000004240fd in spdk_iscsi_op_data (pdu=<optimized out>, conn=0x7f3f1f6ef000) at iscsi.c:4167
#11 spdk_iscsi_execute (conn=conn@entry=0x7f3f1f6ef000, pdu=<optimized out>) at iscsi.c:4432
#12 0x000000000041b91a in spdk_iscsi_conn_handle_incoming_pdus (conn=<optimized out>) at conn.c:1319
#13 spdk_iscsi_conn_execute (conn=conn@entry=0x7f3f1f6ef000) at conn.c:1367
#14 0x000000000041bbe1 in spdk_iscsi_conn_full_feature_do_work (arg=0x7f3f1f6ef000) at conn.c:1448
#15 0x000000000043cfe3 in _spdk_reactor_run (arg=arg@entry=0x86bc00 <g_reactors+256>) at reactor.c:383
#16 0x000000000043d2c1 in spdk_reactors_start () at reactor.c:574
#17 0x000000000043be6b in spdk_app_start (opts=opts@entry=0x7fff41603550, start_fn=start_fn@entry=0x4057c0 <spdk_startup>, arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:386
#18 0x0000000000404a80 in main (argc=3, argv=0x7fff416036c8) at iscsi_tgt.c:182
(gdb)

**Comment by optimistyzy** [comment]
I agree with @devilsgrotto , the ref is for counting the reference for the LUN. Two or more iscsi connection operated on same LUN will be handled in ISCSI target with the same cpu core, i.e., with same I/O channel. So additional ref for counting the LUN is need.    I remember that I submitted a patch to fix this issue in:   https://github.com/spdk/spdk/issues/92.

**Comment by dverkamp-intel** [comment]
To fix the immediate problem, I've pushed a patch to revert the change here: https://review.gerrithub.io/379866

@optimistyzy: Can we add a test that reproduces this bug to autotest?
