### ISSUE TITLE
NVMF/vfio-user: SPDK attempts to map RO DMA region as RW

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2020]
This is a repro of https://review.spdk.io/gerrit/c/spdk/spdk/+/7288. I cannot reproduce using SPDK master (bb8102b1ffc8bf209d7da4e545c2f8b645aa9372) since SeaBIOS doesn't even attempt to read from the NVMe controller because of #2019. I can only reproduce it using our own infrastructure. The reason why this bug hasn't been triggering might be related to how much spare memory SeaBIOS has. It is possible that in my tests SeaBIOS has to use RO memory. Need to do more digging.

**Comment by tmakatos** [comment]
This is reproducable with upstream SeaBIOS. When I patch SeaBIOS with https://mail.coreboot.org/hyperkitty/list/seabios@seabios.org/thread/2Q7NPH7TJNHK6JGPHQL7755HILO23ISN/ I can't repro it. My (limited) understanding is that upstream SeaBIOS consumes more memory than it does with my patch so it ends up using some of its read-only memory, which is fine since the PRP contains read-only information. It should be possible to trigger this bug even with my patch.

**Comment by tmakatos** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/7288 fixes this.

**Comment by changpe1** [comment]
Patch has been merged, so closing this issue now.
