### ISSUE TITLE
libspdk_copy.so is removed?

### ISSUE THREAD

**Issue by lymlhhj123** [spdk/spdk#2024]
i am compile DAOs-stack(master branch), it depend on spdk , when ld -lspdk_cpoy, report error.

libspdk_copy.so is removed?

**Comment by lymlhhj123** [comment]
19.01x branch libspdk_copy.so is exist

**Comment by optimistyzy** [comment]
May be the following libraries  are needed:
libspdk_accel.so libspdk_event_accel.so also ioat or idxd related library.

**Comment by lymlhhj123** [comment]
use 19.01x branch, miss libspdk_vmd.so.   so i use 21.04x branch. it has libspdk_vmd.so,but still miss libspdk_copy.so.

libspdk_accel.so libspdk_event_accel.so is exist in 21.04x branch.

do i compile wrong way?

**Comment by peluse** [comment]
the copy library was replaced with the accel library
