### ISSUE TITLE
[unittest-vg-autotes] Can‘t allocate hugepages 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#2025]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/51360/archive/unittest-vg-autotest/build.log

## Execution failed at
00:05:27.874   06:34:19	# ./scripts/setup.sh
00:05:27.914  0000:00:06.0 (8086 5845): Skipping denied controller at 0000:00:06.0
00:05:27.973  0000:00:07.0 (8086 5845): Skipping denied controller at 0000:00:07.0
00:05:28.063  0000:00:08.0 (8086 5845): Skipping denied controller at 0000:00:08.0
00:05:28.201  0000:00:03.0 (1af4 1001): Skipping denied controller at 0000:00:03.0
00:05:28.267  0000:00:03.0 (1af4 1001): Active mountpoints on vda:vda1, so not binding PCI dev
00:05:28.355  0000:00:09.0 (1d1d 1f1f): nvme -> pci-stub
00:05:28.740  
00:05:28.740  ## ERROR: requested 4096 hugepages but 4075 could be allocated on node0.
00:05:28.740  ## Memory might be heavily fragmented. Please try flushing the system cache, or reboot the machine.
00:05:28.741    06:34:20	# trap - ERR
00:05:28.741    06:34:20	# print_backtrace
00:05:28.741    06:34:20	# [[ ehxBET =~ e ]]
00:05:28.741    06:34:20	# args=("${BASH_ARGV[@]}")
00:05:28.741    06:34:20	# local args
00:05:28.741    06:34:20	# xtrace_disable
00:05:28.741    06:34:20	# '[' no '!=' yes ']'
00:05:28.742    06:34:20	# PREV_BASH_OPTS=ehxBET
00:05:28.742    06:34:20	# [[ ehxBET == *\x* ]]
00:05:28.742    06:34:20	# XTRACE_DISABLED=yes
00:05:28.742    06:34:20	# set +x
00:05:28.743  ========== Backtrace start: ==========
00:05:28.743  
00:05:28.752  in /home/vagrant/spdk_repo/spdk/autotest.sh:120 -> main(["/home/vagrant/autorun-spdk.conf"])
00:05:28.752       ...
00:05:28.752     115 		# Now, bind blocked devices to pci-stub module. This will prevent
00:05:28.752     116 		# automatic grabbing these devices when we add device/vendor ID to
00:05:28.752     117 		# proper driver.
00:05:28.752     118 		if [[ -n "$PCI_BLOCKED" ]]; then
00:05:28.752     119 			# shellcheck disable=SC2097,SC2098
00:05:28.752  => 120 			PCI_ALLOWED="$PCI_BLOCKED" \
00:05:28.752     121 				PCI_BLOCKED="" \
00:05:28.752     122 				DRIVER_OVERRIDE="pci-stub" \
00:05:28.752     123 				./scripts/setup.sh
00:05:28.752     124 	
00:05:28.752     125 			# Export our blocked list so it will take effect during next setup.sh
00:05:28.752       ...
00:05:28.752  
00:05:28.752  ========== Backtrace end ==========
00:05:28.752    06:34:20	# xtrace_enable
00:05:28.752    06:34:20	# return 0
00:05:28.753   06:34:20	# process_core
00:05:28.753   06:34:20	# local es=1
00:05:28.753   06:34:20	# (( es != 0 ))
00:05:28.753   06:34:20	# sleep 5s
00:05:33.756   06:34:25	# local coredumps core
00:05:33.756   06:34:25	# shopt -s nullglob
00:05:33.756   06:34:25	# coredumps=("$output_dir/coredumps/"*.bt.txt)
00:05:33.760   06:34:25	# shopt -u nullglob
00:05:33.760   06:34:25	# (( 0 > 0 ))
00:05:33.760   06:34:25	# return 0
00:05:33.760   06:34:25	# autotest_cleanup
00:05:33.761   06:34:25	# /home/vagrant/spdk_repo/spdk/scripts/setup.sh reset
00:05:34.169  0000:00:03.0 (1af4 1001): Active mountpoints on vda:vda1, so not binding PCI dev
00:05:34.225  Waiting for block devices as requested
00:05:34.259  0000:00:09.0 (1d1d 1f1f): pci-stub -> nvme
00:05:34.285  0000:00:06.0 (8086 5845): Already using the nvme driver
00:05:34.305  0000:00:07.0 (8086 5845): Already using the nvme driver
00:05:34.321  0000:00:08.0 (8086 5845): Already using the nvme driver
00:05:34.343   06:34:26	# /home/vagrant/spdk_repo/spdk/scripts/setup.sh cleanup
00:05:34.762  0000:00:03.0 (1af4 1001): Active mountpoints on vda:vda1, so not binding PCI dev
00:05:34.786  ls: cannot access '/dev/shm/*': No such file or directory

**Comment by mikeBashStuff** [comment]
@yidong0635 Please, see https://github.com/spdk/spdk/issues/1991#issuecomment-868441676- make sure your patches are rebased on top of the latest master to include 227428c3a4.

**Comment by yidong0635** [comment]
@mikeBashStuff  Thanks，duplicated of issue #1991, close this one.
