### ISSUE TITLE
[nvmf-tcp-phy-autotest] nvmf_filesystem_incapsule keep_alive timeout causes build timeout failure

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2030]
00:02:48.303  ************************************
00:02:48.303  START TEST nvmf_filesystem_incapsule
00:02:48.303  ************************************
00:02:48.304   10:31:57	# xtrace_enable
00:02:48.304   10:31:57	# nvmf_filesystem_part 4096
00:02:48.304   10:31:57	# incapsule=4096
00:02:48.304   10:31:57	# nvmfappstart -m 0xF
00:02:48.304   10:31:57	# timing_enter start_nvmf_tgt
00:02:48.304   10:31:57	# xtrace_disable
00:02:48.305   10:31:57	# '[' no '!=' yes ']'
00:02:48.305   10:31:57	# PREV_BASH_OPTS=ehxBET
00:02:48.305   10:31:57	# [[ ehxBET == *\x* ]]
00:02:48.305   10:31:57	# XTRACE_DISABLED=yes
00:02:48.305   10:31:57	# set +x
00:02:48.307   10:31:57	# xtrace_enable
00:02:48.307   10:31:57	# nvmfpid=137555
00:02:48.308   10:31:57	# waitforlisten 137555
00:02:48.308   10:31:57	# ip netns exec enp8s0f0_ns /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0xF
00:02:48.308   10:31:57	# '[' -z 137555 ']'
00:02:48.308   10:31:57	# local rpc_addr=/var/tmp/spdk.sock
00:02:48.308   10:31:57	# echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:02:48.308  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:02:48.308   10:31:57	# xtrace_disable
00:02:48.309   10:31:57	# '[' no '!=' yes ']'
00:02:48.309   10:31:57	# PREV_BASH_OPTS=ehxBET
00:02:48.309   10:31:57	# [[ ehxBET == *\x* ]]
00:02:48.309   10:31:57	# XTRACE_DISABLED=yes
00:02:48.309   10:31:57	# set +x
00:02:48.336  [2021-07-06 10:31:57.110709] Starting SPDK v21.07-pre git sha1 977f8f05a / DPDK 21.05.0 initialization...
00:02:48.336  [2021-07-06 10:31:57.110812] [ DPDK EAL parameters: [2021-07-06 10:31:57.110826] nvmf [2021-07-06 10:31:57.110836] -c 0xF [2021-07-06 10:31:57.110846] --log-level=lib.eal:6 [2021-07-06 10:31:57.110855] --log-level=lib.cryptodev:5 [2021-07-06 10:31:57.110864] --log-level=user1:6 [2021-07-06 10:31:57.110874] --base-virtaddr=0x200000000000 [2021-07-06 10:31:57.110883] --match-allocations [2021-07-06 10:31:57.110892] --file-prefix=spdk0 [2021-07-06 10:31:57.110901] --proc-type=auto [2021-07-06 10:31:57.110911] ]
00:02:48.377  EAL: No free 2048 kB hugepages reported on node 1
00:02:48.377  EAL: No available 1048576 kB hugepages reported
00:02:48.381  TELEMETRY: No legacy callbacks, legacy socket not created
00:02:48.411  [2021-07-06 10:31:57.186267] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 4
00:02:48.602  [2021-07-06 10:31:57.376649] app.c: 384:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
00:02:48.602  [2021-07-06 10:31:57.376745] app.c: 385:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
00:02:48.602  [2021-07-06 10:31:57.376759] app.c: 390:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
00:02:48.602  [2021-07-06 10:31:57.376856] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 1
00:02:48.602  [2021-07-06 10:31:57.376927] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 2
00:02:48.604  [2021-07-06 10:31:57.379426] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 3
00:02:48.604  [2021-07-06 10:31:57.379433] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
00:02:48.605  [2021-07-06 10:31:57.379574] accel_engine.c: 920:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:02:49.253   10:31:58	# xtrace_enable
00:02:49.253   10:31:58	# (( i == 0 ))
00:02:49.253   10:31:58	# return 0
00:02:49.254   10:31:58	# timing_exit start_nvmf_tgt
00:02:49.254   10:31:58	# xtrace_disable
00:02:49.254   10:31:58	# '[' no '!=' yes ']'
00:02:49.255   10:31:58	# PREV_BASH_OPTS=ehxBET
00:02:49.255   10:31:58	# [[ ehxBET == *\x* ]]
00:02:49.255   10:31:58	# XTRACE_DISABLED=yes
00:02:49.255   10:31:58	# set +x
00:02:49.279   10:31:58	# xtrace_enable
00:02:49.279   10:31:58	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_create_transport -t tcp -o -u 8192 -c 4096
00:02:49.491  [2021-07-06 10:31:58.265889] tcp.c: 564:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
00:02:49.510   10:31:58	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc1
00:02:49.746  Malloc1
00:02:49.756   10:31:58	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
00:02:49.985   10:31:58	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:02:50.209   10:31:58	# /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4420
00:02:50.420  [2021-07-06 10:31:59.194767] tcp.c: 758:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.0.0.2 port 4420 ***
00:02:50.434   10:31:59	# nvme connect -t tcp -n nqn.2016-06.io.spdk:cnode1 -a 10.0.0.2 -s 4420
00:02:50.617   10:31:59	# waitforserial SPDK00000000000001
00:02:50.617   10:31:59	# local i=0
00:02:50.617   10:31:59	# local nvme_device_counter=1
00:02:50.617   10:31:59	# [[ -n '' ]]
00:02:50.618    10:31:59	# lsblk -l -o NAME,SERIAL
00:02:50.618    10:31:59	# grep -c SPDK00000000000001
00:02:50.624   10:31:59	# '[' 1 -lt 1 ']'
00:02:50.626    10:31:59	# lsblk -l -o NAME,SERIAL
00:02:50.626    10:31:59	# grep -c SPDK00000000000001
00:02:50.632   10:31:59	# [[ 1 -lt 1 ]]
00:02:50.632   10:31:59	# return 0
00:02:50.633    10:31:59	# lsblk -l -o NAME,SERIAL
00:02:50.633    10:31:59	# grep -oP '([\w]*)(?=\s+SPDK00000000000001)'
00:02:50.639   10:31:59	# nvme_name=nvme0n1
00:02:50.640   10:31:59	# mkdir -p /mnt/device
00:02:50.641   10:31:59	# parted -s /dev/nvme0n1 mklabel msdos mkpart primary 0% 100%
00:02:50.657  Warning: The resulting partition is not properly aligned for best performance: 1s % 2048s != 0s
00:02:50.661   10:31:59	# partprobe
00:03:10.498  [2021-07-06 10:32:19.272865] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:ffef293172f04ccc892566990e70ba84 from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
00:15:27.741  Build timed out (after 15 minutes). Marking the build as failed.
00:15:27.755  Build was aborted
00:15:27.756  [PostBuildScript] - [INFO] Executing post build scripts.
00:15:27.763  [nvmf-tcp-phy-autotest] $ /usr/bin/env bash /tmp/jenkins1006823486138704079.sh
00:15:27.767  Start stage post_get_build_log.sh

**Comment by krish-reddy** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/51787/archive/nvmf-tcp-phy-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_51787.html

**Comment by jimharris** [comment]
This has some similarities to #1863.  This failure here is with the kernel initiator, but we see an unexpected keep alive timeout on the target.

Note this in the dmesg.log for this test run:

```
[ 3551.629127] block nbd1: Attempted send on invalid socket
[ 3551.629136] blk_update_request: I/O error, dev nbd1, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0
[ 3551.770748] block nbd0: Attempted send on invalid socket
[ 3551.770760] blk_update_request: I/O error, dev nbd0, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0
[ 3561.635893] nvme nvme0: queue 0: timeout request 0x1 type 4
[ 3561.635908] nvme nvme0: starting error recovery
[ 3561.636581] nvme nvme0: failed nvme_keep_alive_end_io error=10
[ 3561.639112] block nvme0n1: no usable path - requeuing I/O
[ 3561.640931] block nvme0n1: no usable path - requeuing I/O
[ 3561.642918] nvme nvme0: Reconnecting in 10 seconds...
[ 3575.011252] nvme nvme0: failed to connect socket: -110
[ 3575.011285] nvme nvme0: Failed reconnect attempt 1
[ 3575.011289] nvme nvme0: Reconnecting in 10 seconds...
[ 3588.322564] nvme nvme0: failed to connect socket: -110
[ 3588.322592] nvme nvme0: Failed reconnect attempt 2
[ 3588.322597] nvme nvme0: Reconnecting in 10 seconds...
[ 3601.633902] nvme nvme0: failed to connect socket: -110
[ 3601.633932] nvme nvme0: Failed reconnect attempt 3
[ 3601.633936] nvme nvme0: Reconnecting in 10 seconds...
[ 3614.945236] nvme nvme0: failed to connect socket: -110
[ 3614.945267] nvme nvme0: Failed reconnect attempt 4
[ 3614.945272] nvme nvme0: Reconnecting in 10 seconds...
[ 3628.256583] nvme nvme0: failed to connect socket: -110
```

 I don't understand where the nbd failures are coming from yet...

**Comment by optimistyzy** [comment]
@jimharris  Is it related with the setting. Can we use -k parameter when we use nvme connect command.  Then we can increase the timeout value.  And see whether we still this issue. 

"-k <#>, --keep-alive-tmo=<#>

Overrides the default keep alive timeout (in seconds)."

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_52074.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @MengjinWu. log: https://ci.spdk.io/public_build/autotest-per-patch_52086.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @the-castle. log: https://ci.spdk.io/public_build/autotest-per-patch_53015.html

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue has not occurred for couple months.
