### ISSUE TITLE
connect to nvme subsystem successful even if hostnqn is blank 

### ISSUE THREAD

**Issue by rahulndr** [spdk/spdk#2035]
connection to nvme subsystem is succesful even if hostnqn field is blank in fabric connect packet. As per spec , if there is syntax issue in any of the parameters (ex hostnqn, targetnqn and hostid) , target should reject connect request. 

nvme-cli generates hostnqn if -q   is not passed and /etc/nvme/hostnqn is empty. However, hostnqn is an optional field in perf and abort tool. this allows successful connection to nvme subsystem with empty hostnqn field. 

Here is an excerpt from the spec. 
==========================
If the Host Identifier, Host NQN, NVM Subsystem NQN, and Controller ID values specified for an I/O Queue
are not the same as the values specified for the associated Admin Queue in which the association between
the host and controller was established then a status value of Connect Invalid Parameters is returned. If
the Host NQN or NVM Subsystem NQN values do not match the values that the NVM subsystem is
configured to support, then a status value of Connect Invalid Parameters is returned. **If there is a syntax 
error in the Host NQN or NVM Subsystem NQN value (refer to section 7.9 in the NVMe Base specification),
then a status value of Connect Invalid Parameters is returned**. If the Host Identifier is cleared to 0h, then a
status value of Connect Invalid Parameters is returned.

## Expected Behavior

hostnqn field is null/blank , it should not allow the connection to happen. 

## Current Behavior

perf and abort tool connects nvme subsystem with blank hostnqn

console logs 
============
[root@dhcp scripts]# ./rpc.py nvmf_subsystem_get_controllers nqn.2016-06.io.spdk:cnode1
[
  {
    "cntlid": 1,
    "hostnqn": "",
    "hostid": "bbd064bb-4752-46f7-9ef8-b3510fe4ee49",
    "num_io_qpairs": 5
  }
]
[root@dhcp scripts]# 
[root@dhcp scripts]# 
[root@dhcp scripts]# ./rpc.py nvmf_subsystem_get_controllers nqn.2016-06.io.spdk:cnode1
[
  {
    "cntlid": 2,
    "hostnqn": "test",
    "hostid": "730d55d5-7c4c-4654-8b7f-277d239672dd",
    "num_io_qpairs": 5
  }
]
[root@dhcp scripts]# 

Initiator console log

==========================================================================================
[root@winterfell spdk]# ./build/examples/perf -q 32 -s 40960 -w rw -M 100 -t 60 -P 4  -o 4096 -r 'trtype:tcp adrfam:IPv4 traddr:192.168.10.247 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1'
[2021-07-08 16:34:46.771886] Starting SPDK v21.07-pre git sha1 b8b1f1922 / DPDK 20.11.0 initialization...
[2021-07-08 16:34:46.771950] [ DPDK EAL parameters: [2021-07-08 16:34:46.771960] perf [2021-07-08 16:34:46.771969] --no-shconf [2021-07-08 16:34:46.771974] -c 0x1 [2021-07-08 16:34:46.771978] -m 40960 [2021-07-08 16:34:46.771982] --no-pci [2021-07-08 16:34:46.771990] --log-level=lib.eal:6 [2021-07-08 16:34:46.771996] --log-level=lib.cryptodev:5 [2021-07-08 16:34:46.772003] --log-level=user1:6 [2021-07-08 16:34:46.772008] --iova-mode=pa [2021-07-08 16:34:46.772013] --base-virtaddr=0x200000000000 [2021-07-08 16:34:46.772020] --match-allocations [2021-07-08 16:34:46.772026] --file-prefix=spdk_pid87244 [2021-07-08 16:34:46.772031] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 192.168.10.247:4420: nqn.2016-06.io.spdk:cnode1
Associating TCP (addr:192.168.10.247 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                                                                   Latency(us)
Device Information                                                             :       IOPS      MiB/s    Average        min        max
TCP (addr:192.168.10.247 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 from core  0:   87213.11     340.68     366.91      38.48    3122.74
========================================================
Total                                                                          :   87213.11     340.68     366.91      38.48    3122.74

[root@winterfell spdk]# ./build/examples/perf -q 32 -s 40960 -w rw -M 100 -t 60 -P 4  -o 4096 -r 'trtype:tcp adrfam:IPv4 traddr:192.168.10.247 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1 hostnqn:test'. 
[2021-07-08 16:36:21.932505] Starting SPDK v21.07-pre git sha1 b8b1f1922 / DPDK 20.11.0 initialization...
[2021-07-08 16:36:21.932572] [ DPDK EAL parameters: [2021-07-08 16:36:21.932582] perf [2021-07-08 16:36:21.932589] --no-shconf [2021-07-08 16:36:21.932595] -c 0x1 [2021-07-08 16:36:21.932599] -m 40960 [2021-07-08 16:36:21.932604] --no-pci [2021-07-08 16:36:21.932610] --log-level=lib.eal:6 [2021-07-08 16:36:21.932615] --log-level=lib.cryptodev:5 [2021-07-08 16:36:21.932620] --log-level=user1:6 [2021-07-08 16:36:21.932624] --iova-mode=pa [2021-07-08 16:36:21.932632] --base-virtaddr=0x200000000000 [2021-07-08 16:36:21.932638] --match-allocations [2021-07-08 16:36:21.932645] --file-prefix=spdk_pid87294 [2021-07-08 16:36:21.932650] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 192.168.10.247:4420: nqn.2016-06.io.spdk:cnode1
Associating TCP (addr:192.168.10.247 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
                                                                                                                   Latency(us)
Device Information                                                             :       IOPS      MiB/s    Average        min        max
TCP (addr:192.168.10.247 subnqn:nqn.2016-06.io.spdk:cnode1) NSID 1 from core  0:   85757.44     334.99     373.13      37.30    3158.95
========================================================
Total                                                                          :   85757.44     334.99     373.13      37.30    3158.95

[root@winterfell spdk]#
=====================================================================================
## Steps to Reproduce

1. configure SPDK target with TCP transport 
2. using perf tool, connect nvme subsys info (without hostnqn) 
3. check if connect works without hostnqn

>

## Context (Environment including OS version, SPDK version, etc.)

RHEL 8.2 
Host Kernel : 5.12.8 
perf (top of the trunk)

**Comment by optimistyzy** [comment]
What  I observe is :

We hope that the nqn format is:  nqn.2014-08.org.nvmexpress:uuid:11111111-2222-3333-4444-555555555555
And we have nqn_valid_check function.


And the kernel passed nqn is something like: 
nqn.2014-08.org.nvmexpress:uuid:07e4a0a641d54bff96b28a173dcfb6b5
So we do not check the nqn whether is valid on SPDK target side. 

In NVMe 2.0 spec,  Page 154, it has description:

A 128-bit UUID based on the definition in RFC 4122 represented as a string formatted as
“11111111-2222-3333-4444-555555555555”.
So it seems that the hostnqn string we received from the linux kernel imitator, does not fully obey the format on the uuid.  So in SPDK target side, we do not call nvmf_valid_nqn check.

**Comment by rahulndr** [comment]
Thanks for the response @optimistyzy. 
I see there are two supported nqn formats as per spec. I am not clear whether "" (empty string) is considered a valid nqn format during connection. wireshark clearly indicates that the hostnqn format is "" and still target accepts the connection. 

Can you pls shed some light on why blank hostnqn is considered a valid one ?

**Comment by AlekseyMarchuk** [comment]
@rahulndr if you don't specify nqn in perf tool, it will connect to discovery subsystem (it's nqn is predefined), get discovery log page (it contains all subsystems on the target) and connect to every port on every subsystem. You can refer to `nvme_fabric_ctrlr_discover` in nvme_fabric.c

**Comment by rahulndr** [comment]
Hello Aleksey,

Thanks for the response. This issue is about hostnqn not target nqn. As per
spec , if there is any syntax error in hostnqn then it should return a
proper error code.
blank hostnqn ("") should be considered as an error here but SPDK allows
connection to establish.

Hope this helps. Pls let me know if you need any information.

**Comment by optimistyzy** [comment]
> Thanks for the response @optimistyzy.
> I see there are two supported nqn formats as per spec. I am not clear whether "" (empty string) is considered a valid nqn format during connection. wireshark clearly indicates that the hostnqn format is "" and still target accepts the connection.
> 
> Can you pls shed some light on why blank hostnqn is considered a valid one ?

I do not mean that the blank hostnqn is a valid one. I mean if we open the check, but the current linux kernel still sends this format 07e4a0a641d54bff96b28a173dcfb6b5  but one this one 11111111-2222-3333-4444-555555555555.  So I think that we face a issue to choose. So this is why we do not check it. Adding a check to handle blank one is easy.

**Comment by optimistyzy** [comment]
> Thanks for the response @optimistyzy.
> I see there are two supported nqn formats as per spec. I am not clear whether "" (empty string) is considered a valid nqn format during connection. wireshark clearly indicates that the hostnqn format is "" and still target accepts the connection.
> 
> Can you pls shed some light on why blank hostnqn is considered a valid one ?
It is simple to check the blank case. What I mean is about the spec, which kinds of hostnqn should be really supported. SPDK has the function to check this format "11111111-2222-3333-4444-555555555555".  Currently in our path, we did not check the whether the hostnqn is valid.

**Comment by optimistyzy** [comment]
> Thanks for the response @optimistyzy.
> I see there are two supported nqn formats as per spec. I am not clear whether "" (empty string) is considered a valid nqn format during connection. wireshark clearly indicates that the hostnqn format is "" and still target accepts the connection.
> 
> Can you pls shed some light on why blank hostnqn is considered a valid one ?

For uuid, I did not see two kinds of format.  So this is a question, for SPDK side, we need 36 bytes for uuid string, but kernel initiator sends 32bytes uuid without -.  So SPDK does not check hostnqn format.

**Comment by benlwalker** [comment]
This was an intentional choice. Many initiators send invalid hostnqn values and there's no downside to supporting those. The hostnqn is ultimately just a string, even if not formatted correctly. I'm going to close this issue for that reason.

If you'd like, we'd accept a patch that adds an optional parameter to turn on a "strict" mode that does enforce the hostnqn format, if you wanted to submit one. It would need to be off by default.
