### ISSUE TITLE
SPDK test error when compiled with DPDK v20.11

### ISSUE THREAD

**Issue by trochumski** [spdk/spdk#2042]
We have decided to run SPDK build versus LTS versions of DPDK.
When building SPDK against DPDK `v20.11` we encounter an error in `external_make_hello_no_bdev_shared_combo` test.

## Expected Behavior
All tests should pass.

## Current Behavior
Following error occurs:
`undefined reference to 'rte_version'`

```
14:15:57 ************************************
14:15:57 START TEST external_make_hello_bdev_shared_combo
14:15:57 ************************************
14:15:57  12:15:57	# xtrace_enable
14:15:57  12:15:57	# make -C /home/vagrant/spdk_repo/spdk/test/external_code hello_world_bdev_shared_combo
14:15:57 make: Entering directory '/home/vagrant/spdk_repo/spdk/test/external_code'
14:15:57 make --directory=passthru shared
14:15:57 make[1]: Entering directory '/home/vagrant/spdk_repo/spdk/test/external_code/passthru'
14:15:57 cc -I/home/vagrant/spdk_repo/spdk/include -L/home/vagrant/spdk_repo/spdk/build/lib -L/spdk-temp/dpdk/build/lib -L/home/vagrant/spdk_repo/spdk/libvfio-user/build/release/lib -c -fPIC ./vbdev_passthru_rpc.c -o ./vbdev_passthru_rpc.o
14:15:57 cc -I/home/vagrant/spdk_repo/spdk/include -L/home/vagrant/spdk_repo/spdk/build/lib -L/spdk-temp/dpdk/build/lib -L/home/vagrant/spdk_repo/spdk/libvfio-user/build/release/lib -c -fPIC ./vbdev_passthru.c -o ./vbdev_passthru.o
14:15:57 cc -I/home/vagrant/spdk_repo/spdk/include -L/home/vagrant/spdk_repo/spdk/build/lib -L/spdk-temp/dpdk/build/lib -L/home/vagrant/spdk_repo/spdk/libvfio-user/build/release/lib -shared ./vbdev_passthru_rpc.o ./vbdev_passthru.o -o ./libpassthru_external.so
14:15:57 make[1]: Leaving directory '/home/vagrant/spdk_repo/spdk/test/external_code/passthru'
14:15:57 make --directory=hello_world bdev_shared_combo
14:15:57 make[1]: Entering directory '/home/vagrant/spdk_repo/spdk/test/external_code/hello_world'
14:15:57 cc -I/home/vagrant/spdk_repo/spdk/include -L/home/vagrant/spdk_repo/spdk/build/lib -L/spdk-temp/dpdk/build/lib -L/home/vagrant/spdk_repo/spdk/libvfio-user/build/release/lib -L../passthru -Wl,-rpath=/home/vagrant/spdk_repo/spdk/build/lib,--no-as-needed -o hello_bdev ./hello_bdev.c -lpassthru_external \
14:15:57 -lspdk -L/home/vagrant/spdk_repo/spdk/build/lib -lspdk_env_dpdk -lspdk_log -L/home/vagrant/spdk_repo/spdk/dpdk/build/lib -lrte_eal -lrte_mempool -lrte_ring -lrte_mbuf -lrte_bus_pci -lrte_pci -lrte_mempool_ring -lrte_power -lrte_ethdev -lrte_net -lrte_telemetry -lrte_kvargs -lrte_vhost -lrte_cryptodev -lrte_hash -lrte_rcu  -Wl,--no-whole-archive
14:15:58 /usr/bin/ld: /home/vagrant/spdk_repo/spdk/build/lib/libspdk_env_dpdk.so: undefined reference to `rte_version'
14:15:58 collect2: error: ld returned 1 exit status
14:15:58 make[1]: *** [Makefile:43: bdev_shared_combo] Error 1
14:15:58 make[1]: Leaving directory '/home/vagrant/spdk_repo/spdk/test/external_code/hello_world'
14:15:58 make: *** [Makefile:59: hello_world_bdev_shared_combo] Error 2
14:15:58 make: Leaving directory '/home/vagrant/spdk_repo/spdk/test/external_code'
```
## Steps to Reproduce
Run `autobuild.sh CONFIG_FILE`
With following config:
```shell
SPDK_TEST_AUTOBUILD=1
SPDK_TEST_UNITTEST=0
SPDK_RUN_FUNCTIONAL_TEST=0
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_PMDK=1
SPDK_TEST_ISAL=1
SPDK_TEST_REDUCE=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_FTL=1
SPDK_TEST_OCF=1
SPDK_TEST_RAID5=1
SPDK_TEST_RBD=1
SPDK_TEST_URING=1
SPDK_TEST_NVME_CUSE=1
SPDK_TEST_BLOBFS=1
SPDK_TEST_VFIOUSER=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
EXTERNAL_MAKE_HUGEMEM=2048
RUN_NIGHTLY=0
SPDK_TEST_NATIVE_DPDK=v20.11
SPDK_RUN_EXTERNAL_DPDK=/spdk-temp/dpdk/build
```

Link to whole test job:
https://ci.spdk.io/results/autotest-spdk-master-vs-dpdk-v20.11/builds/5/archive/autobuild-nightly-vg-autotest/build.log

## Context (Environment including OS version, SPDK version, etc.)
SPDK branch: `master`
OS: `Fedora 3` - `Linux version 5.11.20-200.fc33.x86_64 (mockbuild@bkernel02.iad2.fedoraproject.org) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.35-18.fc33) #1 SMP Wed May 12 12:48:34 UTC 2021`
`

**Comment by optimistyzy** [comment]
@trochumski The link address is a internal link. Could you update it?

**Comment by trochumski** [comment]
@optimistyzy Sorry, my bad - link updated

**Comment by optimistyzy** [comment]
I think that we did not add -lrte_version while linking dpdk libraries. //Currently, dpdk complication is generated from pkgconfig. So I did not find the explicit library name setting yet.

**Comment by karlatec** [comment]
@optimistyzy is it even available in DPDK 20.11? For example when I search for rte_version.c in DPDK 21.05:

```
[klateck@eagle1 dpdk]$ grep -rniI rte_version.c ./
175af25734 (HEAD, tag: v21.05, origin/releases) version: 21.05.0
./lib/eal/common/meson.build:39:            'rte_version.c',
./lib/eal/common/meson.build:83:        'rte_version.c',
```

but for DPDK 20.11 I cannot find it:
```
b1d36cf (grafted, tag: v20.11) version: 20.11.0
[klateck@eagle1 dpdk]$ grep -rniI rte_version.c ./
[klateck@eagle1 dpdk]$ echo $?
1
```

**Comment by changpe1** [comment]
[Bug Scrub] @karlatec This maybe a bug in SPDK, can you take a look?

**Comment by jimharris** [comment]
So I think this is pointing out a bug in the test_make.sh test script.

Note that test_make.sh runs configure multiple times, to test different linking scenarios (primarily static v. shared).  But one thing it does *not* do is specify an out-of-tree DPDK build.  This means that SPDK is being compiled against the DPDK submodule - not the DPDK v20.11 specified in the CONFIG_FILE.

But autobuild.sh passes the LD_LIBRARY_PATH to the test_make.sh invocation, so I think what's happening is that the SPDK applications are linking against the DPDK v20.11 libraries - not those that are built from the DPDK submodule.

This would explain the rte_version error.  DPDK v21.05 defines rte_version() in rte_version.c, meaning it's provided by rte_eal shared library.  But DPDK v20.11 defines it as a static inline function, meaning it is not provided by any of the v20.11 shared libraries.

I think the solution here is that we need to somehow pass the out-of-tree DPDK build to test_make.sh if one has been specified, and then test_make.sh needs to incorporate that into the configure invocations.

@trochumski - could you take a look at trying this out?  Let me know if you have any questions.

**Comment by jimharris** [comment]
Moving to low, since this looks like a test issue, not a functional issue.

**Comment by trochumski** [comment]
@jimharris your analysis seems to be correct

`confgure` called by `test_make.sh` always used submodule DPDK

This seems to do the trick:
https://review.spdk.io/gerrit/c/spdk/spdk/+/9202

**Comment by jimharris** [comment]
Thanks @trochumski.  Patch looks good.  Once we get another +2 we'll get this merged and can close this issue.

**Comment by tomzawadzki** [comment]
Fix is now merged, this issue can be closed. Thanks @trochumski !
