### ISSUE TITLE
Request to return bdev name during bdev_nvme_attach_controller and respone "File exist"

### ISSUE THREAD

**Issue by feixue1860** [spdk/spdk#2044]
We need create bdev by ourself, sometimes, we use rpc command (bdev_nvme_attach_controller) to create a bdev, it response as below:
Got JSON-RPC error response
response:
{
  "code": -17,
  "message": "File exists"
} res:1

## Expected Behavior

Can you response "File exist", and also response the bdev name also?
If you reply with the bdev name, i can use it directly. Thanks.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dong-liuliu** [comment]
hi, feixue,

When response result error code is "-17" as EEXIST, the failure reason is also probably that your specified NVMe Transport ctrlr is already attached, not bdev_name.

Can you also check the error info printed from SPDK app? More error details were there.

**Comment by feixue1860** [comment]
Yes, i  want to get the bdev name if the device is already attached. 
Another question, how we can check wehther the specified NVMe Transport ctrlr attached or not? and can we get bdev by the BDF name?

**Comment by AlekseyMarchuk** [comment]
@feixue1860 you can run `bdev_get_bdevs` RPC command, it will print transport address for bdev_nvme (and other bdevs). You only need to parse output
```
./scripts/rpc.py bdev_get_bdevs
[
  {
    "name": "Nvme0n1",
    "aliases": [],
    "product_name": "NVMe disk",
    "block_size": 4096,
    "num_blocks": 2097152,
    "uuid": "92c360cb-a71b-4726-a974-13dbb6cd71c5",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": true,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": true,
      "nvme_io": true
    },
    "driver_specific": {
      "nvme": {
        "trid": {
          "trtype": "RDMA",
          "adrfam": "IPv4",
          "traddr": "1.1.6.1",
          "trsvcid": "4420",
          "subnqn": "nqn.2018-09.io.spdk:cnode1"
        },
        "ctrlr_data": {
          "vendor_id": "0x0000",
          "model_number": "SPDK bdev Controller",
          "serial_number": "SPDK001",
          "firmware_revision": "21.07",
          "subnqn": "nqn.2018-09.io.spdk:cnode1",
          "oacs": {
            "security": 0,
            "format": 0,
            "firmware": 0,
            "ns_manage": 0
          }
        },
        "vs": {
          "nvme_version": "1.3"
        },
        "csts": {
          "rdy": 1,
          "cfs": 0
        },
        "ns_data": {
          "id": 1
        }
      }
    }
  },

```

**Comment by changpe1** [comment]
You can use bdev_nvme_get_controllers to see the specified controller bdev is exist or not before  bdev_nvme_attach_controller, if it still can't meet your requirements, you may develop a new RPC by yourself and contribute back to SPDK. @feixue1860

**Comment by feixue1860** [comment]
@changpe1 bdev_nvme_get_controllers is also a rpc call, can we use some api to check/get directly? and for rpc  bdev_nvme_get_controllers, the parameter  is the prefix name of bdev, and the output not show the bdev name just the contrller name.

**Comment by changpe1** [comment]
OK, you may not rely on us to provide such requirements from you, I encourage you do it by yourself,  :).

**Comment by Comphix** [comment]
If need to call the API directly, may take a look at below API:

struct nvme_ctrlr *nvme_ctrlr_get_by_name(const char *name);

**Comment by Comphix** [comment]
Or below one with transport_id (BDF as local attached)

struct nvme_ctrlr *nvme_ctrlr_get(const struct spdk_nvme_transport_id *trid);

**Comment by feixue1860** [comment]
Hi， i saw other guy submit the issue that sometimes bdev_nvme_attach_controller timeout, i also meet this issue, can u guide how to check it? should we modify the timeout time in somewhere?

**Comment by changpe1** [comment]
> Hi， i saw other guy submit the issue that sometimes bdev_nvme_attach_controller timeout, i also meet this issue, can u guide how to check it? should we modify the timeout time in somewhere?

RPC has a default timeout value, some drives may need longer that that timeout value, but it doesn't mean errors.
