### ISSUE TITLE
rpc: save_config can't save all bdevs into a json file

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2045]
When we created a lvol bdevs as below steps, then run RPC save_config to a json file.
We will find save_config can't save lvol bdevs. Here is an example of aio base bdev, and NVMe base bdev has the same problem.

## Expected Behavior

```
    {
      "subsystem": "bdev",
      "config": [
        ......
        {
          "method": "bdev_aio_create",
          "params": {
            "name": "aio0",
            "block_size": 4096,
            "filename": "test/blobstore/blob_io_wait/aio.bdev"
          }
        },
        {
          "method": "bdev_lvol_create_lvstore",
          "params": {
            "bdev_name": "aio0",
            "lvs_name": "lvs0"
          }
        },
        {
          "method": "bdev_lvol_create",
          "params": {
            "lvol_name": "lvol0",
            "lvs_name": "lvs0",
            "size": 16
          }
        },
        ......
```

## Current Behavior

```
    {
      "subsystem": "bdev",
      "config": [
        ......
        {
          "method": "bdev_aio_create",
          "params": {
            "name": "aio0",
            "block_size": 4096,
            "filename": "test/blobstore/blob_io_wait/aio.bdev"
          }
        },
        ......
```

## Possible Solution

Check save_config code.

## Steps to Reproduce

1. start a target , ./test/app/bdev_svc/bdev_svc
2. build a aio bdev, truncate -s 64M test/blobstore/blob_io_wait/aio.bdev
3. ./scripts/rpc.py bdev_aio_create test/blobstore/blob_io_wait/aio.bdev aio0 4096
4. ./scripts/rpc.py bdev_lvol_create_lvstore aio0 lvs0
5. ./scripts/rpc.py bdev_lvol_create -l lvs0 lvol0 32
6. ./scripts/rpc.py save_config > bdevperf_aio_issue.json
7. vim bdevperf_aio_issue.json, found there is no lvol bdevs.
8. clean
./scripts/rpc.py bdev_lvol_delete lvs0/lvol0
./scripts/rpc.py bdev_lvol_delete_lvstore -l lvs0
./scripts/rpc.py bdev_aio_delete aio0
rm -f test/blobstore/blob_io_wait/aio.bdev

## Context (Environment including OS version, SPDK version, etc.)

SPDK commit da2fd6651a9cd4732b0910d30291821e77f4d643

**Comment by jimharris** [comment]
Hi @wanghailiangx,

This is expected behavior.  lvol metadata is stored on the aio (or nvme) bdev.  After you run bdev_aio_create RPC, the lvol bdev module will read the metadata on the aio bdev and recreate the lvol bdevs automatically.

-Jim

**Comment by wanghailiangx** [comment]
@jimharris Thank you for your explanation. Now close this issue.
