### ISSUE TITLE
Will spdk support cli  in the development plan？

### ISSUE THREAD

**Issue by mlbzssk** [spdk/spdk#205]
Hi~  I am a developer of a company,we are very interested  in spdk,and we have a plan to use spdk.It's no doubt a good software.I wonder if it will support command line interface?If you have a plan,I wonder when it will be done.
 Thank you!

**Comment by pelplinski** [comment]
Hi,
We do not have interactive CLI in SPDK.
There is however RPC functionality already built-in.
You can use spdk/scripts/rpc.py script to execute them.
Start the script with -h switch for more information about RPC commands.

--
Best Regards,
Piotr Pelpliński

**Comment by peluse** [comment]
Well there are CLI's coming for nvme and there is one for blobstore that was just merged to master and has some better features coming soon so depending on what you're after there may be a specific CLI that works for you

**Comment by mlbzssk** [comment]
OK,I see.I am poor in rpc,AHA,As you all say that,I will   try to use it.Thank you very much!
