### ISSUE TITLE
bdev_nvme_attach_controller timeout

### ISSUE THREAD

**Issue by zhuohaofan** [spdk/spdk#2050]
## Expected Behavior
add success

## Current Behavior
There are a total of four Samsung 980Pro NVMe SSDs on my machine.
Normally, it will time out when create the second or third nvme bdev.
The error message printed is as follows:
Timeout while waiting for response:

Timeout while waiting for response:

## Steps to Reproduce

1. setup SPDK
./scripts/setup.sh
2. start spdk_tgt
./build/bin/spdk_tgt -m 0x0000ff0000ff &
2. create RDMA transport
./scripts/rpc.py nvmf_create_transport -t RDMA
3. create NVMe bdev
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe0 -t PCIe -a 0000:b0:00.0
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:3c:00.0
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe2 -t PCIe -a 0000:3b:00.0
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe3 -t PCIe -a 0000:af:00.0

Normally, it will time out when creating the second or third nvme bdev.

## Context (Environment including OS version, SPDK version, etc.)
$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
$ git branch
* (HEAD detached at v20.10)
$ lspci | grep -i samsung
3b:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd Device a80a
3c:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd Device a80a
af:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd Device a80a
b0:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd Device a80a

**Comment by tomzawadzki** [comment]
Hi @zhuohaofan Can you post logs from the spdk_tgt application ?

As well please make sure to use SPDK LTS 21.01 LTS, latest release (21.04) or current master branch. Just in case the issue has already been fixed.

**Comment by zhuohaofan** [comment]
Has been updated to v21.04. In order to facilitate the test, I wrote a simple script called "timeout_test.sh" as follows to create nvme bdev in a loop. I ran the script twice, and it was timeout on the seventh time.

`csi@node23:~/spdk-v21.04$ cat timeout_test.sh
#!/bin/bash

for ((i = 0; i < 10; i++))
do

./scripts/setup.sh
sleep 2

./build/bin/spdk_tgt -m 0x0000ff0000ff &
sleep 2

./scripts/rpc.py nvmf_create_transport -t RDMA
sleep 2

echo $i
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe0 -t PCIe -a 0000:b0:00.0
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:3c:00.0
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe2 -t PCIe -a 0000:3b:00.0
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe3 -t PCIe -a 0000:af:00.0
sleep 2

./scripts/rpc.py bdev_nvme_detach_controller NVMe0
./scripts/rpc.py bdev_nvme_detach_controller NVMe1
./scripts/rpc.py bdev_nvme_detach_controller NVMe2
./scripts/rpc.py bdev_nvme_detach_controller NVMe3
sleep 2

spdk_pid=`ps aux|grep spdk_tgt | grep -v grep | awk '{print $2}'`
kill -9 $spdk_pid
sleep 2

./scripts/setup.sh reset
sleep 2

done
csi@node23:~/spdk-v21.04$`

**Comment by zhuohaofan** [comment]
BTW, once the timeout occurs, I need to restart the server to use the timeout nvme ssd again. Otherwise, "no driver" will be displayed when setting up spdk. Is there an easier way instead of restarting the server?
`**0000:af:00.0 (144d a80a): no driver -> vfio-pci**
0000:00:04.7 (8086 2021): ioatdma -> vfio-pci
0000:b0:00.0 (144d a80a): nvme -> vfio-pci
0000:3c:00.0 (144d a80a): nvme -> vfio-pci
0000:3b:00.0 (144d a80a): nvme -> vfio-pci

[2021-07-26 02:00:00.251551] nvme_pcie.c: 351:nvme_pcie_ctrlr_map_cmb: *ERROR*: get registers failed
[2021-07-26 02:00:00.251606] nvme_pcie.c: 534:nvme_pcie_ctrlr_map_pmr: *ERROR*: get registers failed
[2021-07-26 02:00:00.251622] nvme_pcie.c: 957:nvme_pcie_ctrlr_construct: *ERROR*: get_cap() failed
[2021-07-26 02:00:00.251670] nvme.c: 675:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:af:00.0
EAL: Driver cannot attach the device (0000:af:00.0)
EAL: Failed to attach device on primary process
[2021-07-26 02:00:00.420972] nvme.c: 818:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2021-07-26 02:00:00.420984] bdev_nvme.c:2326:bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:af:00.0)
request:
{
  "name": "NVMe3",
  "trtype": "PCIe",
  "traddr": "0000:af:00.0",
  "method": "bdev_nvme_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -19,
  "message": "No such device"
}

`

**Comment by optimistyzy** [comment]
How about the following function:

nvme_pcie_ctrlr_allocate_bars(struct nvme_pcie_ctrlr *pctrlr)
{
        int rc;
        void *addr = NULL;
        uint64_t phys_addr = 0, size = 0;

        rc = spdk_pci_device_map_bar(pctrlr->devhandle, 0, &addr,
                                     &phys_addr, &size);

        if ((addr == NULL) || (rc != 0)) {
                SPDK_ERRLOG("nvme_pcicfg_map_bar failed with rc %d or bar %p\n",
                            rc, addr);
                return -1;
        }

        pctrlr->regs = (volatile struct spdk_nvme_registers *)addr;
        pctrlr->regs_size = size;
        pctrlr->doorbell_base = (volatile uint32_t *)&pctrlr->regs->doorbell[0].sq_tdbl;
       // nvme_pcie_ctrlr_map_cmb(pctrlr);
        //nvme_pcie_ctrlr_map_pmr(pctrlr);

        return 0;
}

Can you comment out the usage of the two functions and recompile the program and see what happens. I am afraid your nvme SSD do not have the two features, then it will make you timeout.

**Comment by zhuohaofan** [comment]
It will still time out after commenting out these two lines of code. And every time an nvme bdev is created, some error messages will be printed. as follows:
`[2021-07-26 03:00:37.385436] accel_engine.c: 852:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
3
[2021-07-26 03:00:42.211625] nvme_pcie_common.c: 106:nvme_pcie_ctrlr_alloc_cmb: *ERROR*: Tried to allocate past valid CMB range!
[2021-07-26 03:00:42.238527] nvme_pcie_common.c: 106:nvme_pcie_ctrlr_alloc_cmb: *ERROR*: Tried to allocate past valid CMB range!
NVMe0n1
[2021-07-26 03:00:42.595584] nvme_pcie_common.c: 106:nvme_pcie_ctrlr_alloc_cmb: *ERROR*: Tried to allocate past valid CMB range!
[2021-07-26 03:00:42.622368] nvme_pcie_common.c: 106:nvme_pcie_ctrlr_alloc_cmb: *ERROR*: Tried to allocate past valid CMB range!
NVMe1n1
[2021-07-26 03:00:42.975599] nvme_pcie_common.c: 106:nvme_pcie_ctrlr_alloc_cmb: *ERROR*: Tried to allocate past valid CMB range!
[2021-07-26 03:00:43.002373] nvme_pcie_common.c: 106:nvme_pcie_ctrlr_alloc_cmb: *ERROR*: Tried to allocate past valid CMB range!
NVMe2n1
Timeout while waiting for response:


Timeout while waiting for response:
`

**Comment by optimistyzy** [comment]
@zhuohaofan Can you confirm that the timeout is always no the same NVME SSD? or randomly timeout on any nvme ssd? (if you test it using SPDK master branch)

**Comment by zhuohaofan** [comment]
I think it is random. We have 4 nvme ssds and timeouts have occurred in all three of them, except for the first one. And an interesting phenomenon is that the later SSDs are more likely to time out. For example, the third and fourth SSDs have a higher probability of overtime.
So I guess it is because some of the resources applied for when spdk_tgt are started are not enough, so the later SSDs are more likely to time out?

**Comment by tomzawadzki** [comment]
[Bug scrub] There is coverage for attachment of multiple nvme devices in the tests, so that's hard to tell what might be the issue.
Can you share details on the NVMe devices and platforms used ? What is the NVMe version reporting by the device ?

**Comment by zhuohaofan** [comment]
The four NVMe SSD are all Samsung 980Pro.
https://www.samsung.com/semiconductor/minisite/ssd/product/consumer/980pro/
The NVMe version is 1.3.
`NVMe Specification Version (VS):       1.3
NVMe Specification Version (Identify): 1.3
`

**Comment by changpe1** [comment]
I'm going to close this issue, feel free to open it if you find something wrong in SPDK.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_76686.html
