### ISSUE TITLE
Cannot attach NVMe when using uio_pci_generic

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#2051]
Running:

```
sudo DRIVER_OVERRIDE=uio_pci_generic ./scripts/setup.sh
sudo ./build/bin/spdk_tgt &
sudo ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:86:00.0
```

Results in:

```
EAL:   Expecting 'PA' IOVA mode but current mode is 'VA', not initializing
EAL: Driver cannot attach the device (0000:81:00.0)
EAL: Failed to attach device on primary process
[2021-07-21 09:57:49.014122] nvme.c: 814:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2021-07-21 09:57:49.014139] bdev_nvme.c:2658:bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:81:00.0)
```

With vfio-pci driver everything works correctly. Tested on current master (https://github.com/spdk/spdk/commit/153f03cf42880f083dad9de71bc73e287bf7f997) on 3 machines.

**Comment by mikeBashStuff** [comment]
Works fine on my side. But don't you have to disable iommu for uio to work properly (I have it disabled on my box)? Also,  here's a note from DPDK (https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html):

>If the devices used for DPDK are bound to the uio_pci_generic kernel module, please make sure that the IOMMU is disabled or is in passthrough mode. One can add intel_iommu=off or amd_iommu=off or intel_iommu=on iommu=pt in GRUB command line on x86_64 systems, or add iommu.passthrough=1 on aarch64 systems.

**Comment by Maciej-Szwed** [comment]
I missed that information and I have iommu enabled. In that case let's close this issue as it is not an issue.
