### ISSUE TITLE
blobfs rocksdb db_bench performance degradation in multi threads mode

### ISSUE THREAD

**Issue by hyswtj** [spdk/spdk#2054]
I have a test with blobfs rocksdb, performance degradation  in multi threads mode
## Expected Behavior

performance growth with thread number.

## Current Behavior

    threads      	         ops
------------------------------------
	1 			1231088
	2			612148
	4			535236
	8			580043
	16			748137
SPDK v21.04 / DPDK 20.05.0
rocksdb-6.15.fb
SSD：INTEL P4610

[2021-07-23 16:30:10.055101] Starting SPDK v21.04 / DPDK 20.05.0 initialization...
[2021-07-23 16:30:10.055308] [ DPDK EAL parameters: [2021-07-23 16:30:10.055356] rocksdb [2021-07-23 16:30:10.055376] --no-shconf [2021-07-23 16:30:10.055392] -c 0x1 [2021-07-23 16:30:10.055408] --log-level=lib.eal:6 [2021-07-23 16:30:10.055427] --log-level=lib.cryptodev:5 [2021-07-23 16:30:10.055450] --log-level=user1:6 [2021-07-23 16:30:10.055469] --iova-mode=pa [2021-07-23 16:30:10.055485] --base-virtaddr=0x200000000000 [2021-07-23 16:30:10.055503] --match-allocations [2021-07-23 16:30:10.055522] --file-prefix=spdk_pid54115 [2021-07-23 16:30:10.055539] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No free hugepages reported in hugepages-2048kB
EAL: No legacy callbacks, legacy socket not created
[2021-07-23 16:30:10.179028] app.c: 535:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-07-23 16:30:10.299043] app.c: 383:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0x80 specified.
[2021-07-23 16:30:10.299098] app.c: 387:app_setup_trace: *NOTICE*: Use 'spdk_trace -s rocksdb -p 54115' to capture a snapshot of events at runtime.
[2021-07-23 16:30:10.299108] app.c: 389:app_setup_trace: *NOTICE*: Or copy /dev/shm/rocksdb_trace.pid54115 for offline analysis/debug.
[2021-07-23 16:30:10.299122] reactor.c: 929:reactor_run: *NOTICE*: Reactor started on core 0
[2021-07-23 16:30:10.299703] accel_engine.c: 852:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
using bdev Nvme0n1
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
RocksDB:    version 6.15
Date:       Fri Jul 23 16:30:21 2021
CPU:        64 * Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
CPUCache:   22528 KB
Keys:       16 bytes each (+ 0 bytes user-defined timestamp)
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
Write rate: 0 bytes/second
Read rate: 0 ops/second
Compression: Snappy
Compression sampling rate: 0
Memtablerep: skip_list
Perf Level: 1
------------------------------------------------
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
DB path: [/tmp/rocksdbtest-0/dbbench]
fillseq      :       0.812 micros/op 1231088 ops/sec;  136.2 MB/s
Please disable_auto_compactions in FillDeterministic benchmark

## Steps to Reproduce

1./db_bench -spdk  /root/rocksdb_test/rocksdb.json  -spdk_bdev Nvme0n1 -spdk_cache_size 1024 –statistics=1 –histogram=1 –key_size=16 –value_size=1000 –block_size=4096 –cache_size=0 –bloom_bits=10 –cache_numshardbits=8 –verify_checksum=1 –db=/Nvme0n1/rocksdb –compression_type=none –stats_interval=1000000 –compression_ratio=0 –stats_per_interval=1 –benchmarks=readrandom –duration=600 –use_existing_db=1 –num=2000000000 --threads=1
2./db_bench -spdk  /root/rocksdb_test/rocksdb.json  -spdk_bdev Nvme0n1 -spdk_cache_size 1024 –statistics=1 –histogram=1 –key_size=16 –value_size=1000 –block_size=4096 –cache_size=0 –bloom_bits=10 –cache_numshardbits=8 –verify_checksum=1 –db=/Nvme0n1/rocksdb –compression_type=none –stats_interval=1000000 –compression_ratio=0 –stats_per_interval=1 –benchmarks=readrandom –duration=600 –use_existing_db=1 –num=2000000000 --threads=2
3./db_bench -spdk  /root/rocksdb_test/rocksdb.json  -spdk_bdev Nvme0n1 -spdk_cache_size 1024 –statistics=1 –histogram=1 –key_size=16 –value_size=1000 –block_size=4096 –cache_size=0 –bloom_bits=10 –cache_numshardbits=8 –verify_checksum=1 –db=/Nvme0n1/rocksdb –compression_type=none –stats_interval=1000000 –compression_ratio=0 –stats_per_interval=1 –benchmarks=readrandom –duration=600 –use_existing_db=1 –num=2000000000 --threads=4
4./db_bench -spdk  /root/rocksdb_test/rocksdb.json  -spdk_bdev Nvme0n1 -spdk_cache_size 1024 –statistics=1 –histogram=1 –key_size=16 –value_size=1000 –block_size=4096 –cache_size=0 –bloom_bits=10 –cache_numshardbits=8 –verify_checksum=1 –db=/Nvme0n1/rocksdb –compression_type=none –stats_interval=1000000 –compression_ratio=0 –stats_per_interval=1 –benchmarks=readrandom –duration=600 –use_existing_db=1 –num=2000000000 --threads=8
5./db_bench -spdk  /root/rocksdb_test/rocksdb.json  -spdk_bdev Nvme0n1 -spdk_cache_size 1024 –statistics=1 –histogram=1 –key_size=16 –value_size=1000 –block_size=4096 –cache_size=0 –bloom_bits=10 –cache_numshardbits=8 –verify_checksum=1 –db=/Nvme0n1/rocksdb –compression_type=none –stats_interval=1000000 –compression_ratio=0 –stats_per_interval=1 –benchmarks=readrandom –duration=600 –use_existing_db=1 –num=2000000000 --threads=16

**Comment by optimistyzy** [comment]
@hyswtj I see this issue was closed by you. Could you add some descriptions for why closing this issue

**Comment by hyswtj** [comment]
The question is my wrong test operation, so the issue is wrong.Close it.

**Comment by optimistyzy** [comment]
> The question is my wrong test operation, so the issue is wrong.Close it.

Got it, thanks.
