### ISSUE TITLE
we removed vhost-nvme support after 20.07, can we bring it back just for testing purpose?

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2056]
## Expected Behavior
if possible we have vhost nvme support with latest code?

## Current Behavior
we lost vhost-nvme totally

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
@gaowayne For some reason, the QEMU part worked with vhost-nvme can't be upstream to QEMU, now we're developing a new replacement vfio-user target to provide NVMe emulation in SPDK, so for you question, we won't add vhost-nvme back.

**Comment by gaowayne** [comment]
@changpe1 thank you so much changpe, this is very clear.
