### ISSUE TITLE
NVMf/vfio-user: Windows presents inactive namespaces

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2058]
Using https://review.spdk.io/gerrit/c/spdk/spdk/+/8971 I boot Windows and I notice that _all_ namespaces (NN) appear in the Disk Management tool are listed, even though they're not active. In this scenario there is only one active namespace. Attempting to initialize any other namespace fails with "The parameter is incorrect", which is expected.

Not sure whether we can do anything about it. Reducing NN is probably not an option as this way we won't be able to hot plug namespaces.

**Comment by jimharris** [comment]
@tmakatos or @changpe1 - can you see in your logs if Windows is sending IDENTIFY CNS=0x2 (ACTIVE_NS_LIST)?

**Comment by jimharris** [comment]
I don't see where we zero the spdk_nvme_ns_list before filling it out for IDENTIFY CNS=0x2.  It's possible Windows sees some garbage data in the active ns list, decides it can't trust it, so just displays everything?

Regardless, we should zero it out, even if it doesn't fix this specific issue.

https://review.spdk.io/gerrit/c/spdk/spdk/+/8984 zeroes the buffer - @tmakatos could you give it a try?

**Comment by changpe1** [comment]
I noticed that Windows doesn't send Identify Active NS list command, but my Windows 10 1903 build doesn't show inactive NS in the Disk Management tool, only one active NS is there. @tmakatos what's your Windows version?

**Comment by tmakatos** [comment]
> I noticed that Windows doesn't send Identify Active NS list command, but my Windows 10 1903 build doesn't show inactive NS in the Disk Management tool, only one active NS is there. @tmakatos what's your Windows version?

I'm using Windows 10.0 (Build 10240) (as reported by `winver`). I might be running an old version of Windows, let me update and see whether this issue is still valid.

**Comment by tmakatos** [comment]
I've updated Windows to Version 20H2 (OS Build 19042.1110) and I don't see the issue.
