### ISSUE TITLE
blobstore able to open bogus blobid w/unpredictable behavior

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#206]
If you create a new BS and then try to open a blob with a blobid of 0, it correctly gives you a -NOENT error however if you create a blob first and then try to open still with a bogus ID you will incorrectly get success.

Found during CLI dev, working on patch now...

**Comment by peluse** [comment]
proposed change at https://review.gerrithub.io/380865

**Comment by peluse** [comment]
never mind, this one... https://review.gerrithub.io/#/c/380872/

**Comment by dverkamp-intel** [comment]
The fix for this was merged in commit 721695e12184a1b43718752c677225c130e90497
