### ISSUE TITLE
scripts/setup.sh reset crashes guest

### ISSUE THREAD

**Issue by antroseco** [spdk/spdk#2065]
`scripts/setup.sh reset` sometimes causes a CentOS 8.3 guest to crash. Occurs with both `vfio` (no-iommu mode) and `uio_pci_generic` drivers.

## Expected Behavior

`scripts/setup.sh reset` should re-load the kernel's nvme driver.

## Current Behavior

`scripts/setup.sh reset` sometimes crashes the entire guest.

## Steps to Reproduce

Execute following script with root privileges:
```
#!/bin/bash
while true;
do
        spdk/scripts/setup.sh config
        spdk/scripts/setup.sh reset
done
```
Sometimes occurs on the first try.

## Context (Environment including OS version, SPDK version, etc.)
Guest: CentOS Linux release 8.3.2011
kernel: 4.18.0-240.el8.x86_64
SPDK: master

**Comment by changpe1** [comment]
[Bug Scrub] @antroseco can you post the kernel log here?

**Comment by changpe1** [comment]
Do you run the above scripts to reproduce this issue? if yes, can you add a delay to see this issue is exist or not.

**Comment by Comphix** [comment]
@antroseco , any feedback on this issue?

**Comment by antroseco** [comment]
Sorry for the delay. Re-tested this with the latest SPDK master and it looks like this issue has been fixed; the guest no longer crashes. I'll close the issue.
