### ISSUE TITLE
Could not install ibverbs and rdmacm packages in RHEL 7.4

### ISSUE THREAD

**Issue by ksubbiahx** [spdk/spdk#207]
Hi,

Could not install libibverbs-devel and librdmacm-devel in RHEL 7.4 when compiling spdk.

When trying to install libibverbs-devel-1.2.1-1.el7.x86_64.rpm, getting below error:

[root@localhost libibverbs packages]# rpm -ivh libibverbs-devel-1.2.1-1.el7.x86_64.rpm
warning: libibverbs-devel-1.2.1-1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
error: Failed dependencies:
        libibverbs = 1.2.1-1.el7 is needed by libibverbs-devel-1.2.1-1.el7.x86_64

And, when trying to install  libibverbs-1.2.1-1.el7.x86_64.rpm,

[root@localhost libibverbs packages]# rpm -ivh libibverbs-1.2.1-1.el7.x86_64.rpm
warning: libibverbs-1.2.1-1.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Preparing...                          ################################# [100%]
        package libibverbs-13-7.el7.x86_64 (which is newer than libibverbs-1.2.1-1.el7.x86_64) is already installed
        file /usr/lib64/libibverbs.so.1 from install of libibverbs-1.2.1-1.el7.x86_64 conflicts with file from package libibverbs-13-7.el7.x86_64

Seems that RHEL 7.4 is already having a newer version of libibverbs. But could not install libibverbs-devel package. Same is for librdmacm-devel package also.

Because of this, getting the below error when compiling spdk with make CONFIG_RDMA=y:
nvme_rdma.c:40:30: fatal error: infiniband/verbs.h: No such file or directory
 #include <infiniband/verbs.h>
                              ^
compilation terminated.
make[2]: *** [nvme_rdma.o] Error 1
make[1]: *** [nvme] Error 2
make: *** [lib] Error 2

**Comment by dverkamp-intel** [comment]
Is it possible that you have a vendor OFED stack installed that is conflicting with the RHEL packages?

Also, is there a specific reason you are attempting to install from an RPM file rather than via yum?

`scripts/pkgdep.sh` should automatically install the necessary dependencies.

**Comment by dverkamp-intel** [comment]
Since this is not an SPDK issue and no responses have been posted, I'm going to close this issue; please check with Red Hat support if you are still unable to install the necessary dependencies.

**Comment by ksingh2017** [comment]
I had a similar issue a while ago but with yum.  Later, I found out that libibverbs is already part of rdma-core so it does not need to be installed separately.  However, getting the latest from git (https://github.com/linux-rdma/rdma-core) yielded the best results.  Older rdma-core that installed via yum was causing crashes.
