### ISSUE TITLE
[Scheduler dynamic] Shall  the scheduler allocates multiple 100% active threads to one core？

### ISSUE THREAD

**Issue by ChengqiangMeng** [spdk/spdk#2070]
When I create multiple threads with 100% active status, the scheduler allocates them all to the same core.
Is this expected behavior？
Or if there is any problem with my test method, please let me know. Thanks.
## Current Behavior
As shown in the figure: all busy thread(busy0、busy1、busy2) are allocated on core 0.

![issue](https://user-images.githubusercontent.com/77378851/128309221-fa17be28-8c20-46c8-b041-149088b95e4c.JPG)

## Expected Behavior
busy0 on core0
busy1 on core1
busy2 on core3

## Steps to Reproduce
1. `test/event/scheduler/scheduler -m 0xF -p 2 --wait-for-rpc&`
2. `scripts/rpc.py framework_set_scheduler dynamic`
3. `scripts/rpc.py framework_start_init`
4. `build/bin/spdk_top`
5. open another terminal and create  thread :
   like this: 
 `rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n busy0 -m 0x1 -a 100`
 `rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n busy1 -m 0x1 -a 100`
 `rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n busy2 -m 0x1 -a 100`

## Context (Environment including OS version, SPDK version, etc.)
SPDK VERSION: 49ffdc18afc639a8f59e87e2e0945a379ced497b
OS VERSION: 5.11.22-100.fc32.x86_64

**Comment by dong-liuliu** [comment]
Thanks for your careful discovery and review, Chengqiang.
Current behavior met current ability of dynamic scheduler.

Your expected behavior is reasonable, but this requires more enhancement in spdk scheduler :)

**Comment by tomzawadzki** [comment]
Hi @ChengqiangMeng please keep in mind that `test/event/scheduler/scheduler` and it's RPC are test application only.

In below RPC the `-m 0x1` assigns the cpu mask for the thread, in this case only Core 0: 
```
rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n busy0 -m 0x1 -a 100
```

`scheduler_dynamic` does respect the cpu mask passed when creating the thread. If you want the threads to be balanced, please either skip assigning the cpu mask (don't pass the argument) or pass cpu mask that covers multiple cores.

**Comment by ChengqiangMeng** [comment]
Hi @tomzawadzki , thank you and @dong-liuliu for your answer. And when I don‘t add `-m`, this problem can be solved. However, when the number of 100% active threads I add exceeds the number of cores, all threads created later will be allocated to main_core. Is this what we expected？

**Comment by jimharris** [comment]
Question asked here has been answered - so closing.
