### ISSUE TITLE
Not enough interfaces found for phy-nvmf-tcp tests

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2072]
https://ci.spdk.io/results/autotest-per-patch/builds/55332/archive/nvmf-tcp-phy-autotest/build.log

Happened on GP1. I am guessing second interface was still in a separate namespace after failing test, hence the issue here.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_55332.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_55442.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_55576.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_55594.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_55585.html

**Comment by mikeBashStuff** [comment]
Potential workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/9168

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_56012.html
