### ISSUE TITLE
bdev/nvme: bdev_nvme_reset() must not free NVMe qpairs for PCIe

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#2073]
I think there is a fundamental issue in how bdev_nvme_reset() is executing a ctrlr reset.

The bdev_nvme_reset() first deletes all qpairs before calling the ctrlr_reset function:
```
/* First, delete all NVMe I/O queue pairs. */
	spdk_for_each_channel(nvme_bdev_ctrlr,
			      _bdev_nvme_reset_destroy_qpair,
			      bio,
			      _bdev_nvme_reset);
```

This is problematic:
The _bdev_nvme_reset_destroy_qpair() calls spdk_nvme_ctrlr_free_io_qpair() which eventually calls ctrlr_delete_io_qpair(). 
For the PCIe case, nvme_pcie_ctrlr_delete_io_qpair() actually submits the delete IO sq/cq NVMe command to the ctrlr. 
This doesn't really make sense since we are performing a ctrlr reset. A ctrlr reset for PCIe is typically performed because something is wrong with the controller/NVMe device or bring it in a well-known state. We don't want to submit more commands when we decide to do a ctrlr reset.

The NVMe spec says that the controller is already deleting the sq/cq queues, so it's not necessary for the initiator do that (freeing its associated resources is needed, of course):
_A Controller Level Reset consists of the following actions:
• The controller stops processing any outstanding Admin or I/O commands;
• All I/O Submission Queues are deleted;
• All I/O Completion Queues are deleted;
..._

## Expected Behavior

The bdev_nvme_reset() must not actively send cq/sq NVMe commands to the device (however, it still needs to free out internal qpair structures).

## Context (Environment including OS version, SPDK version, etc.)
SPDK 21.07 and below

**Comment by jimharris** [comment]
Hi @mhae,

Yeah - we need to avoid the admin commands in this case to PCIe controllers.  I'm going to work on this one.  @benlwalker and I talked about your issue last week - we think we want to keep the explicit delete operations in the bdev module before we do the reset, meaning we'd want a way to signal to the pcie transport (maybe a new API?) that it should just do cleanup on the qpair structure and not actually send any admin commands.

Will keep you posted.

-Jim

**Comment by mhae** [comment]
@jimharris , sorry to bug, but do you have a diff that I can try? I did a similar approach where I skip sending the cmd but mine is really just a hack where I set a flag on the qpair to disable sending the SQ deletion to the device.

**Comment by jimharris** [comment]
Hi @mhae,

Here's my initial cut:

https://review.spdk.io/gerrit/c/spdk/spdk/+/9250

At first I set this flag on the qpair, but then decided its probably better to do it on the ctrlr instead.  If you could give it a spin after it passes CI, I would appreciate it.

Thanks,

-Jim

**Comment by MattDumm** [comment]
Hi @jimharris , @mhae,
I tried some tests on the new code, and it does the job we were looking for. We were seeing trouble and sometimes a crash in our scenarios when the reset included the admin commands. With the skipping of the admin commands during reset, we are seeing the right things happen now. Thanks!

**Comment by tomzawadzki** [comment]
Patches fixing the issue have been merged https://review.spdk.io/gerrit/c/spdk/spdk/+/9250.
