### ISSUE TITLE
[START TEST devices] blkid returns PTTYPE="atari"

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2079]
00:01:49.383  ************************************
00:01:49.383  START TEST devices
00:01:49.383  ************************************
00:01:49.383   11:58:04	-- spdk/test/common/autotest_common.sh@956 -- # xtrace_enable
00:01:49.383   11:58:04	-- spdk/test/common/autotest_common.sh@957 -- # /var/jenkins/workspace/BlobFS-autotest/spdk/test/setup/devices.sh
00:01:49.467  * Looking for test storage...
00:01:49.475  * Found test storage at /var/jenkins/workspace/BlobFS-autotest/spdk/test/setup
00:01:49.476     11:58:04	-- spdk/test/common/autotest_common.sh@1410 -- # xtrace_enable
00:01:49.476   11:58:04	-- spdk/test/setup/devices.sh@6 -- # shopt -s nullglob
00:01:49.477   11:58:04	-- spdk/test/setup/devices.sh@167 -- # trap cleanup EXIT
00:01:49.477   11:58:04	-- spdk/test/setup/devices.sh@169 -- # setup reset
00:01:49.477   11:58:04	-- spdk/test/setup/common.sh@4 -- # [[ reset == output ]]
00:01:49.477   11:58:04	-- spdk/test/setup/common.sh@7 -- # /var/jenkins/workspace/BlobFS-autotest/spdk/scripts/setup.sh reset
00:01:49.727   11:58:04	-- spdk/test/setup/devices.sh@171 -- # blocks=()
00:01:49.727   11:58:04	-- spdk/test/setup/devices.sh@171 -- # declare -a blocks
00:01:49.727   11:58:04	-- spdk/test/setup/devices.sh@172 -- # blocks_to_pci=()
00:01:49.727   11:58:04	-- spdk/test/setup/devices.sh@172 -- # declare -A blocks_to_pci
00:01:49.727   11:58:04	-- spdk/test/setup/devices.sh@173 -- # min_disk_size=2147483648
00:01:49.728   11:58:04	-- spdk/test/setup/devices.sh@175 -- # for block in "/sys/block/nvme"*
00:01:49.728    11:58:04	-- spdk/test/setup/devices.sh@176 -- # readlink -f /sys/block/nvme0n1/device/device
00:01:49.731   11:58:04	-- spdk/test/setup/devices.sh@176 -- # pci=/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0
00:01:49.731   11:58:04	-- spdk/test/setup/devices.sh@177 -- # pci=0000:01:00.0
00:01:49.731   11:58:04	-- spdk/test/setup/devices.sh@187 -- # blkid /dev/nvme0n1
00:01:49.741  /dev/nvme0n1: PTTYPE="atari"
00:01:49.742   11:58:04	-- spdk/test/setup/devices.sh@192 -- # (( 0 > 0 ))
00:01:49.742    11:58:04	-- spdk/test/setup/devices.sh@192 -- # trap - ERR
00:01:49.742    11:58:04	-- spdk/test/setup/devices.sh@192 -- # print_backtrace

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_55598.html

**Comment by jimharris** [comment]
```
00:01:49.741 /dev/nvme0n1: PTTYPE="atari"
```

Looks like this issue isn't unique to SPDK:
https://forums.gentoo.org/viewtopic-t-1095976-start-0.html
https://forums.linuxmint.com/viewtopic.php?t=330769

And looks like maybe it's been fixed with more recent versions of blkid?
https://github.com/karelzak/util-linux/issues/1116

Probably we'll just need to special case this Atari thing for now.  @mikeBashStuff can you take a look?

**Comment by peluse** [comment]
I wonder if its related to the Nintendo bug... :)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_55587.html

**Comment by mikeBashStuff** [comment]
@jimharris https://review.spdk.io/gerrit/c/spdk/spdk/+/9143 this should do the trick I think.

**Comment by jimharris** [comment]
Patch merged.  Thanks @mikeBashStuff!
