### ISSUE TITLE
[nvmf_multipath] timeout before ANA state (nvme0 c1) becomes optimized

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2081]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/55491/archive/nvmf-tcp-uring-vg-autotest/build.log

## Execution failed at

00:10:53.642    11:23:55	-- nvmf/target/multipath.sh@19 -- # cat /sys/block/nvme0c1n1/ana_state
00:10:53.647   11:23:55	-- nvmf/target/multipath.sh@19 -- # '[' inaccessible '!=' optimized ']'
00:10:53.647   11:23:55	-- nvmf/target/multipath.sh@20 -- # sleep 1
00:10:54.652   11:23:56	-- nvmf/target/multipath.sh@21 -- # (( timeout-- == 0 ))
00:10:54.652   11:23:56	-- nvmf/target/multipath.sh@22 -- # echo 'timeout before ANA state (nvme0 c1) becomes optimized'
00:10:54.652  timeout before ANA state (nvme0 c1) becomes optimized
00:10:54.653   11:23:56	-- nvmf/target/multipath.sh@23 -- # return 1
00:10:54.653    11:23:56	-- nvmf/target/multipath.sh@91 -- # trap - ERR
00:10:54.653    11:23:56	-- nvmf/target/multipath.sh@91 -- # print_backtrace
00:10:54.654    11:23:56	-- common/autotest_common.sh@985 -- # [[ ehxBET =~ e ]]
00:10:54.654    11:23:56	-- common/autotest_common.sh@987 -- # args=("${BASH_ARGV[@]}")
00:10:54.654    11:23:56	-- common/autotest_common.sh@987 -- # local args
00:10:54.654    11:23:56	-- common/autotest_common.sh@989 -- # xtrace_disable
00:10:54.655    11:23:56	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:10:54.655    11:23:56	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:10:54.655    11:23:56	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:10:54.655    11:23:56	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:10:54.656    11:23:56	-- common/autotest_common.sh@19 -- # set +x
00:10:54.656  ========== Backtrace start: ==========
00:10:54.656  
00:10:54.673  in test/nvmf/target/multipath.sh:91 -> main(["--transport=tcp"])
00:10:54.673       ...
00:10:54.673     86  	
00:10:54.673     87  	$rpc_py nvmf_subsystem_listener_set_ana_state nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT" -n optimized
00:10:54.673     88  	$rpc_py nvmf_subsystem_listener_set_ana_state nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a "$NVMF_SECOND_TARGET_IP" -s "$NVMF_PORT" -n optimized
00:10:54.673     89  	
00:10:54.673     90  	check_ana_state "$subsys_id" "$ctrl1_id" "optimized"
00:10:54.673  => 91  	check_ana_state "$subsys_id" "$ctrl2_id" "optimized"
00:10:54.673     92  	
00:10:54.673     93  	# Set IO policy to round-robin
00:10:54.673     94  	echo round-robin > /sys/class/nvme-subsystem/nvme-subsys$subsys_id/iopolicy
00:10:54.673     95  	
00:10:54.674     96  	$rootdir/scripts/fio-wrapper -p nvmf -i 4096 -d 128 -t randrw -r 6 -v &
00:10:54.674       ...
00:10:54.674  
00:10:54.675  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_55491.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_56224.html

**Comment by changpe1** [comment]
@shuhei-matsumoto Hi Shuhei, can you take a look? thanks.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_56616.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_56747.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_56881.html

**Comment by shuhei-matsumoto** [comment]
Hi All,

Sorry for my delayed response.
I noticed a common signature in dmsg. log for the reported cases.

>[  584.436852] nvme nvme1: starting error recovery
[  584.447248] nvme nvme1: Reconnecting in 10 seconds...

For some reason, connection was lost and reconnecting was scheduled after 10 seconds.
10 seconds is the default value.
However, I set the timeout to 3 seconds.

I propose extending the timeout to 20 seconds to cover this case.
For most cases Linux NVMe host recognizes the new ANA state within 2 seconds.

https://review.spdk.io/gerrit/c/spdk/spdk/+/9393

**Comment by shuhei-matsumoto** [comment]
All reported failures were nvmf-tcp-uring-autotest so far. We may have any transport specific cause about connection loss while ANA states are changed.

**Comment by tomzawadzki** [comment]
@shuhei-matsumoto usually the intermittent failure issues are closed if no new reports are submitted for long time. The patch you've submitted looks good to me. Do you want to work further on this issue besides the patch or should this issue be closed ?

**Comment by shuhei-matsumoto** [comment]
Thank you @tomzawadzki 

No, I don't want to work further on this issue :)
This issue might be temporary and fixed by recent changes.
More than one month passed since the last report. I'm happy if the patch is merged but I'm OK to close this issue even if it is not.

**Comment by shuhei-matsumoto** [comment]
The last date we saw this issue was more than a month ago.
Let's close this issue.
