### ISSUE TITLE
No space left on device reported by vagrant

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2083]
https://ci.spdk.io/results/autotest-per-patch/builds/55690/archive/freebsd-vg-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_55689.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_55691.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_55694.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_55690.html

**Comment by tomzawadzki** [comment]
This issue was temporary due to work performed on CI, it was reported to allow the 'false positive' retriggers. Since it no longer serves a purpose, it will be closed.
