### ISSUE TITLE
messy code in log

### ISSUE THREAD

**Issue by liupan1111** [spdk/spdk#209]
Hi,

We developed an app for our use model, and enabled log by referring the code in app/iscsi_tgt, but got the messy code in /var/log/message:

Oct 10 19:29:25 e07d07265.eu6sqa spdk[9371]: device_manager.c: 172:dm_set_log_level: *NOTICE*: Device manager log level:2
Oct 10 19:29:25 e07d07265.eu6sqa spdk[9371]: device_manager.c: 117:check_only_one_instance: *NOTICE*: notice
Oct 10 19:29:25 e07d07265.eu6sqa È<87>QXù^?[9371]: EAL: Probing VFIO support...
Oct 10 19:29:26 e07d07265.eu6sqa su[9368]: pam_unix(su:session): session closed for user root
Oct 10 19:29:26 e07d07265.eu6sqa Pë0^A[9371]: device_manager.c: 503:main: *ERROR*: Initializing NVMe Controllers
Oct 10 19:29:26 e07d07265.eu6sqa Pë0^A[9371]: EAL: PCI device 0000:03:00.0 on NUMA socket 0
Oct 10 19:29:26 e07d07265.eu6sqa Pë0^A[9371]: EAL:   probe driver: 8086:953 spdk_nvme
Oct 10 19:29:26 e07d07265.eu6sqa Pë0^A[9371]: device_manager.c: 260:dm_probe_cb: *NOTICE*: Attaching to 0000:03:00.0

If we don't enable log in our app, and only dump dpdk log, there is no issue.

Could you give me some help?

Thanks
Pan

**Comment by Comphix** [comment]
Hi Pan,

Have you tried SPDK’s existed app like NVMe-oF target and whether there is same issue in your environment? If not, then you may need to find the difference in your app and SPDK’s existed app.

Another thing is that maybe you can use GDB to debug this app to narrow down the issue.

Thanks,
Gang
