### ISSUE TITLE
bdev malloc performance is very poor if I comment the memcpy code in accel engine

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2094]
# Bug report

bdev malloc perf is not good enough, even when I remove the real memcpy inside accel engine, this may use much more CPUs.

## Expected Behavior

even Optane SSD bdevperf can get 6-7GiB performance. why bdevperf on Malloc and I actually remove the memcpy method. why it only give 9000MiB/s?

## Current Behavior

do not know where is bottleneck? 

## Steps to Reproduce

1. remove the memcpy calling inside accel engine
2. rebuild SPDK
3. run below command
```
[root@localhost spdk]# ./test/bdev/bdevperf/bdevperf --json /tmp/perfmalloc4G.json  --json-ignore-init-errors -r /var/tmp/spdk.sock -m 3 -q 128  -o 4096 -w randwrite  -t 300
[2021-07-24 23:29:53.522714] Starting SPDK v21.07 git sha1 adeb04968 / DPDK 21.05.0 initialization...
[2021-07-24 23:29:53.522886] [ DPDK EAL parameters: [2021-07-24 23:29:53.522909] bdevperf [2021-07-24 23:29:53.522926] --no-shconf [2021-07-24 23:29:53.522942] -c 3 [2021-07-24 23:29:53.522959] --log-level=lib.eal:6 [2021-07-24 23:29:53.522976] --log-level=lib.cryptodev:5 [2021-07-24 23:29:53.522992] --log-level=user1:6 [2021-07-24 23:29:53.523009] --base-virtaddr=0x200000000000 [2021-07-24 23:29:53.523025] --match-allocations [2021-07-24 23:29:53.523042] --file-prefix=spdk_pid470706 [2021-07-24 23:29:53.523057] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-07-24 23:29:53.697302] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 2
[2021-07-24 23:29:54.063342] reactor.c: 931:reactor_run: *NOTICE*: Reactor started on core 1
[2021-07-24 23:29:54.063347] reactor.c: 931:reactor_run: *NOTICE*: Reactor started on core 0
[2021-07-24 23:29:54.088094] accel_engine.c: 988:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Running I/O for 300 seconds...
 Job: Malloc0 (Core Mask 0x1)
	 Malloc0             : 2367833.48 IOPS    9249.35 MiB/s
 =============================================================
 Total                       : 2367833.48 IOPS    9249.35 MiB/s

```
4. only 9249MiB/s, this is framework overhead here, because there is no real copy here, it should be higher. or is this upper limit of bdev device?

**Comment by gaowayne** [comment]
if remove accel engine, complete the IO directly get below result
```
[root@localhost spdk]# ./test/bdev/bdevperf/bdevperf --json /tmp/perfmalloc4G.json  --json-ignore-init-errors -r /var/tmp/spdk.sock -m 3 -q 128  -o 4096 -w randwrite  -t 300
[2021-07-25 02:15:32.018447] Starting SPDK v21.07 git sha1 adeb04968 / DPDK 21.05.0 initialization...
[2021-07-25 02:15:32.018613] [ DPDK EAL parameters: [2021-07-25 02:15:32.018638] bdevperf [2021-07-25 02:15:32.018655] --no-shconf [2021-07-25 02:15:32.018672] -c 3 [2021-07-25 02:15:32.018697] --log-level=lib.eal:6 [2021-07-25 02:15:32.018713] --log-level=lib.cryptodev:5 [2021-07-25 02:15:32.018727] --log-level=user1:6 [2021-07-25 02:15:32.018744] --base-virtaddr=0x200000000000 [2021-07-25 02:15:32.018762] --match-allocations [2021-07-25 02:15:32.018779] --file-prefix=spdk_pid618575 [2021-07-25 02:15:32.018793] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-07-25 02:15:32.190572] app.c: 537:spdk_app_start: *NOTICE*: Total cores available: 2
[2021-07-25 02:15:32.560911] reactor.c: 931:reactor_run: *NOTICE*: Reactor started on core 1
[2021-07-25 02:15:32.560916] reactor.c: 931:reactor_run: *NOTICE*: Reactor started on core 0
[2021-07-25 02:15:32.585682] accel_engine.c: 988:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Running I/O for 300 seconds...
 Job: Malloc0 (Core Mask 0x1)
	 Malloc0             : 2764746.35 IOPS   10799.79 MiB/s
 =============================================================
 Total                       : 2764746.35 IOPS   10799.79 MiB/s
```

**Comment by peluse** [comment]
@gaowayne for steps to reproduce, we need everything necessary to actually reproduce this. Can you please attach or paste the contents of /tmp/perfmalloc4G.json

**Comment by jimharris** [comment]
I suspect it's related to what I described in https://github.com/spdk/spdk/issues/2084#issuecomment-897081540.

**Comment by jimharris** [comment]
Specifically this part:

"If we are using SW path, when we submit an I/O, it does the SW operation (copy, CRC, whatever) and then immediately calls the completion routine. So the completion routine cannot submit the next I/O, otherwise we'll end up blowing the stack with recursive calls. So it does an spdk_thread_send_msg() to call accel_done instead to avoid the recursion. That seems fairly expensive. It would be nicer if the SW engine behaved similarly to the HW engines, in that the completions are always called from the context of a completion poller. Note this is exactly what we do in the null bdev, exactly for same reasons."

**Comment by peluse** [comment]
So I've started addressing that already, this at least gets it into the engine and removes the caller from knowing anything about it.  I'll look at what malloc is doing and update accordingly. https://review.spdk.io/gerrit/c/spdk/spdk/+/9171

**Comment by peluse** [comment]
cool, will have it ready short;y

**Comment by peluse** [comment]
@gaowayne please give this a try, it's still under review and I just tested it briefly so.. https://review.spdk.io/gerrit/c/spdk/spdk/+/9171/8

**Comment by peluse** [comment]
@jimharris one thing wrt your comment still doesn't make sense though, he's not using accel_perf which is where that extra scheduling step was happening.  He's running bdevperf.  I didn't add the accel support there but looking at malloc_bdev there's no extra send-message step in there that I could see on quick review.  @gaowayne if you could post that json file I asked for I can repro this and see what's happening

**Comment by jimharris** [comment]
If a bdev I/O is completed in the context of the submission, then bdev layer has to do an spdk_thread_send_msg for same reason we currently have one in accel_perf.  That's what is happening currently, bdev malloc module calls spdk_accel_submit_copy, if it's the SW backend we call the completion immediately which goes back up to the bdev layer in the context of the submission.

**Comment by peluse** [comment]
OK, so you're thinking if the accel_engine completes via a poller (as the patch above will do) then bdev won't use send_msg?

**Comment by jimharris** [comment]
> OK, so you're thinking if the accel_engine completes via a poller (as the patch above will do) then bdev won't use send_msg?

Yes

**Comment by peluse** [comment]
cool, any reason why the bdev layer is using send_msg to get off the callers stack as opposed to what I just did to the accel_engine? Seems like a good change for the bdev layer also...

**Comment by gaowayne** [comment]
@peluse thank you so much man. I will test. I create one empty malloc driver. it can reach 17800MiB/s, but I need bring null device model. put request into linked list, then one poller finish them to upper. with this, we can reach 17800MiB/s. 
if I just complete IO in the caller thread, it is only 9000MiB/s. 
I will test with your patch. :)

**Comment by jimharris** [comment]
> cool, any reason why the bdev layer is using send_msg to get off the callers stack as opposed to what I just did to the accel_engine? Seems like a good change for the bdev layer also...

Putting one in the bdev layer would be similar to creating a poller in accel_perf to handle completions made from the submit context. It would work, but it’s better to just have the bdev module (or libraries it depends on like accel_engine) be responsible for it.

**Comment by jimharris** [comment]
> > cool, any reason why the bdev layer is using send_msg to get off the callers stack as opposed to what I just did to the accel_engine? Seems like a good change for the bdev layer also...
> 
> Putting one in the bdev layer would be similar to creating a poller in accel_perf to handle completions made from the submit context. It would work, but it’s better to just have the bdev module (or libraries it depends on like accel_engine) be responsible for it.

Just to explain a bit more, if we added a poller to the bdev layer, then for all of the non-malloc cases, this poller would always run but never do anything so it would be wasted cycles.

**Comment by gaowayne** [comment]
> @gaowayne for steps to reproduce, we need everything necessary to actually reproduce this. Can you please attach or paste the contents of /tmp/perfmalloc4G.json

sorry for late guys. I am busy on other things. here is my json now.
```
{
  "subsystems": [
    {
      "subsystem": "accel",
      "config": []
    },
    {
      "subsystem": "vmd",
      "config": []
    },
    {
      "subsystem": "sock",
      "config": [
        {
          "method": "sock_impl_set_options",
          "params": {
            "impl_name": "posix",
            "recv_buf_size": 2097152,
            "send_buf_size": 2097152
          }
        }
      ]
    },
    {
      "subsystem": "interface",
      "config": null
    },
    {
      "subsystem": "net_framework",
      "config": null
    },
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_set_options",
          "params": {
            "bdev_io_pool_size": 65535,
            "bdev_io_cache_size": 256,
            "bdev_auto_examine": true
          }
        },
        {
          "method": "bdev_nvme_set_options",
          "params": {
            "action_on_timeout": "none",
            "timeout_us": 0,
            "retry_count": 4,
            "arbitration_burst": 0,
            "low_priority_weight": 0,
            "medium_priority_weight": 0,
            "high_priority_weight": 0,
            "nvme_adminq_poll_period_us": 10000,
            "nvme_ioq_poll_period_us": 0,
            "io_queue_requests": 0,
            "delay_cmd_submit": true
          }
        },
        {
          "method": "bdev_nvme_set_hotplug",
          "params": {
            "period_us": 100000,
            "enable": false
          }
        },
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc0",
            "num_blocks": 262144,
            "block_size": 4096,
            "uuid": "b25034ba-416a-49c3-bcc6-552a5779418e"
          }
        }
      ]
    }
  ]
}
```

**Comment by gaowayne** [comment]
> I suspect it's related to what I described in [#2084 (comment)](https://github.com/spdk/spdk/issues/2084#issuecomment-897081540).

this issue has nothing to do with accel framework. I just mock Malloc driver, make it complete IO directly without real copy.

**Comment by gaowayne** [comment]
> @gaowayne please give this a try, it's still under review and I just tested it briefly so.. https://review.spdk.io/gerrit/c/spdk/spdk/+/9171/8

buddy, these patches are for accel perf, my issue is for malloc device performance upper bound related. :)

**Comment by gaowayne** [comment]
> @gaowayne please give this a try, it's still under review and I just tested it briefly so.. https://review.spdk.io/gerrit/c/spdk/spdk/+/9171/8

sorry for late. actually I did not enable accel engine in my test above. it is just malloc removed real copy, it is upper bound test. one fake testing.

**Comment by jimharris** [comment]
> > I suspect it's related to what I described in [#2084 (comment)](https://github.com/spdk/spdk/issues/2084#issuecomment-897081540).
> 
> this issue has nothing to do with accel framework. I just mock Malloc driver, make it complete IO directly without real copy.

Please take a look at the second paragraph of that comment.  When you complete I/O immediately like this, you do an extra spdk_thread_send_msg per I/O which is going to hurt your performance.

I'm just curious, why not use null bdev driver instead if you want to test upper limit of bdev layer?

**Comment by gaowayne** [comment]
> > > I suspect it's related to what I described in [#2084 (comment)](https://github.com/spdk/spdk/issues/2084#issuecomment-897081540).
> > 
> > 
> > this issue has nothing to do with accel framework. I just mock Malloc driver, make it complete IO directly without real copy.
> 
> Please take a look at the second paragraph of that comment. When you complete I/O immediately like this, you do an extra spdk_thread_send_msg per I/O which is going to hurt your performance.
> 
> I'm just curious, why not use null bdev driver instead if you want to test upper limit of bdev layer?

yes, I tested null bdev too. it is 17000MiB/s its internal has one poller, and all requests will be insert into list, poller pick them up and complete IO. but malloc one without real copy is only half BW of null bdev. I monitored spdk_top, cpu usage is similar, so I am curious about this.

**Comment by jimharris** [comment]
> > > > I suspect it's related to what I described in [#2084 (comment)](https://github.com/spdk/spdk/issues/2084#issuecomment-897081540).
> > > 
> > > 
> > > this issue has nothing to do with accel framework. I just mock Malloc driver, make it complete IO directly without real copy.
> > 
> > 
> > Please take a look at the second paragraph of that comment. When you complete I/O immediately like this, you do an extra spdk_thread_send_msg per I/O which is going to hurt your performance.
> > I'm just curious, why not use null bdev driver instead if you want to test upper limit of bdev layer?
> 
> yes, I tested null bdev too. it is 17000MiB/s its internal has one poller, and all requests will be insert into list, poller pick them up and complete IO. but malloc one without real copy is only half BW of null bdev. I monitored spdk_top, cpu usage is similar, so I am curious about this.

bdev layer never completes I/O to caller in the context of its submission.  So when you complete the I/O immediately in the submission path, the bdev layer has to do an spdk_thread_send_msg() to itself so that the I/O is completed after the submission context unwinds.  A well-designed bdev module will make sure that it does not complete I/O in the submission context (or at least only do it very rarely).

**Comment by gaowayne** [comment]
> > > > > I suspect it's related to what I described in [#2084 (comment)](https://github.com/spdk/spdk/issues/2084#issuecomment-897081540).
> > > > 
> > > > 
> > > > this issue has nothing to do with accel framework. I just mock Malloc driver, make it complete IO directly without real copy.
> > > 
> > > 
> > > Please take a look at the second paragraph of that comment. When you complete I/O immediately like this, you do an extra spdk_thread_send_msg per I/O which is going to hurt your performance.
> > > I'm just curious, why not use null bdev driver instead if you want to test upper limit of bdev layer?
> > 
> > 
> > yes, I tested null bdev too. it is 17000MiB/s its internal has one poller, and all requests will be insert into list, poller pick them up and complete IO. but malloc one without real copy is only half BW of null bdev. I monitored spdk_top, cpu usage is similar, so I am curious about this.
> 
> bdev layer never completes I/O to caller in the context of its submission. So when you complete the I/O immediately in the submission path, the bdev layer has to do an spdk_thread_send_msg() to itself so that the I/O is completed after the submission context unwinds. A well-designed bdev module will make sure that it does not complete I/O in the submission context (or at least only do it very rarely).

thank you so much. Jim, this is very clear for me now. 👍
