### ISSUE TITLE
SW implmentation of copy+CRC32C in accel_fw fails data verification test

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2096]
This cmd will fail: sudo ./accel_perf -t 2 -w copy_crc32c -y -C 2 

From master or better yet from here git fetch https://review.spdk.io/gerrit/spdk/spdk refs/changes/90/9190/2 && git checkout FETCH_HEAD so that after it's fixed the commented out line that tests it in that patch can be uncommencted.

**Comment by optimistyzy** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/9193  I posted this patch on top of yours @peluse .  I think that for vector cases, you did not copy the whole contents from the src vectors.

**Comment by peluse** [comment]
@optimistyzy yes I know, Monica was assigned to this issue.

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue should be resolved with patch in review https://review.spdk.io/gerrit/c/spdk/spdk/+/9193. The issue can be closed once merged.
