### ISSUE TITLE
[nvmf-tcp-vg-autotest] tcp_req->datao != c2h_data->datao

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#2098]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_56206.html

## Execution failed at

00:12:17.157  EAL: No available 1048576 kB hugepages reported
00:12:17.158  TELEMETRY: No legacy callbacks, legacy socket not created
00:12:17.158  [2021-08-17 00:41:48.329096] accel_engine.c:1022:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:12:17.158  [2021-08-17 00:41:48.469971] nvme_tcp.c:1317:nvme_tcp_c2h_data_hdr_handle: *ERROR*: Invalid datao for tcp_req(0x7f3ca8148930), received datal(30720) != datao(15360) in tcp_req
00:12:17.158  [2021-08-17 00:41:48.470078] vbdev_gpt.c: 437:gpt_bdev_complete: *ERROR*: Gpt: bdev=Nvme0n1 io error status=0
00:12:17.158  [2021-08-17 00:41:48.470107] nvme_qpair.c: 722:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 1
00:12:17.158  [2021-08-17 00:41:48.476410] nvme_tcp.c:1074:tcp_data_recv_crc32_done: *ERROR*: data digest error on tqpair=(0x7f3ca8148670) with pdu=0x200012855440
00:12:17.158  fio: nvme_tcp.c:964: nvme_tcp_c2h_data_payload_handle: Assertion `tcp_req != NULL' failed.
00:12:59.527  [2021-08-17 00:42:08.436515] ctrlr.c: 185:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2016-06.io.spdk:host0 from subsystem nqn.2016-06.io.spdk:cnode0 due to keep alive timeout.
00:15:54.001  Build timed out (after 15 minutes). Marking the build as failed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_56211.html

**Comment by changpe1** [comment]
[Bug Scrub] let's keep this open to see any new reports here.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58256.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_58429.html

**Comment by jimharris** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/58570/archive/nvmf-tcp-uring-vg-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_58602.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_58800.html

**Comment by jimharris** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_58969.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_59022.html

**Comment by jimharris** [comment]
Ziye posted a patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/9612 which looks good to me!

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_59040.html

**Comment by optimistyzy** [comment]
> Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_59040.html

This is another issue, which is related with datao != c2h_data->datao case.
