### ISSUE TITLE
[autobuild-vg-autotest] shared object test failed

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2099]
# CI Intermittent Failure

************************************
START TEST confirm_abi_deps
************************************
* Running confirm_abi_deps against spdk_abi_latest
Please update the major SO version for libspdk_accel.so. API functions or variables have been removed since last release.
Leaf changes summary: 1 artifact changed
Changed leaf types summary: 0 leaf type changed
Removed/Changed/Added functions summary: 1 Removed, 0 Changed, 0 Added function
Removed/Changed/Added variables summary: 0 Removed, 0 Changed, 0 Added variable

1 Removed function:

  [D] 'function int spdk_accel_submit_copy_crc32cv(spdk_io_channel*, void*, iovec*, uint32_t, uint32_t*, uint32_t, spdk_accel_completion_cb, void*)'    {spdk_accel_submit_copy_crc32cv}

Please update the major SO version for libspdk_event.so. A header accessible type has been modified since last release.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_56164.html

## Execution failed at

shared object test failed
  14:39:40	$ trap - ERR
  14:39:40	$ print_backtrace
  14:39:40	$ [[ ehxBET =~ e ]]
  14:39:40	$ args=("${BASH_ARGV[@]}")
  14:39:40	$ local args
  14:39:40	$ xtrace_disable
  14:39:40	$ '[' no '!=' yes ']'
  14:39:40	$ PREV_BASH_OPTS=ehxBET
  14:39:40	$ [[ ehxBET == *\x* ]]
  14:39:40	$ XTRACE_DISABLED=yes
  14:39:40	$ set +x
========== Backtrace start: ==========

in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:959 -> run_test(["autobuild_check_so_deps"],["/home/vagrant/spdk_repo/spdk/test/make/check_so_deps.sh"],["/home/vagrant/autorun-spdk.conf"])
     ...
   954 		timing_enter $test_name
   955 		echo "************************************"
   956 		echo "START TEST $test_name"
   957 		echo "************************************"
   958 		xtrace_restore
=> 959 		time "$@"
   960 		xtrace_disable
   961 		echo "************************************"
   962 		echo "END TEST $test_name"
   963 		echo "************************************"
   964 		timing_exit $test_name
     ...
in /home/vagrant/spdk_repo/spdk/autobuild.sh:273 -> autobuild_test_suite(["/home/vagrant/autorun-spdk.conf"])
     ...
   268 	}
   269 	
   270 	function autobuild_test_suite() {
   271 		run_test "autobuild_check_format" ./scripts/check_format.sh
   272 		run_test "autobuild_external_code" sudo -E --preserve-env=PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH $rootdir/test/external_code/test_make.sh $rootdir
=> 273 		run_test "autobuild_check_so_deps" $rootdir/test/make/check_so_deps.sh $1
   274 		./configure $config_params --without-shared
   275 		$MAKE $MAKEFLAGS
   276 		run_test "autobuild_generated_files_check" porcelain_check
   277 		run_test "autobuild_header_dependency_check" header_dependency_check
   278 		run_test "autobuild_make_install" $MAKE $MAKEFLAGS install DESTDIR="$SPDK_WORKSPACE" prefix=/usr
     ...
in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:959 -> run_test(["autobuild"],["autobuild_test_suite"],["/home/vagrant/autorun-spdk.conf"])
     ...
   954 		timing_enter $test_name
   955 		echo "************************************"
   956 		echo "START TEST $test_name"
   957 		echo "************************************"
   958 		xtrace_restore
=> 959 		time "$@"
   960 		xtrace_disable
   961 		echo "************************************"
   962 		echo "END TEST $test_name"
   963 		echo "************************************"
   964 		timing_exit $test_name
     ...
in /home/vagrant/spdk_repo/spdk/autobuild.sh:316 -> main(["/home/vagrant/autorun-spdk.conf"])
     ...
   311 	if [[ $SPDK_TEST_OCF -eq 1 ]]; then
   312 		run_test "autobuild_ocf_precompile" ocf_precompile
   313 	fi
   314 	
   315 	if [[ $SPDK_TEST_AUTOBUILD -eq 1 ]]; then
=> 316 		run_test "autobuild" autobuild_test_suite $1
   317 	elif [[ $SPDK_TEST_UNITTEST -eq 1 ]]; then
   318 		run_test "unittest_build" unittest_build
   319 	elif [[ $SPDK_TEST_SCANBUILD -eq 1 ]]; then
   320 		run_test "scanbuild_make" scanbuild_make
   321 	else
     ...

========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_56164.html

**Comment by ksztyber** [comment]
I don't think it's a false positive. The failure occurred on patchset 2, which was based on 320ab72fb53956ca2c2e27132c8607405e98ea72, which doesn't have `spdk_accel_submit_copy_crc32cv` defined. And the `confirm_abi_deps` test verifies the ABI against the latest release (21.07), which does include this function. This is why it reports it as being deleted.

I can see that after rebasing the patch, the failure disappeared, so I think we can close this.
