### ISSUE TITLE
vfio-user block assertion fail while rebooting VMs 

### ISSUE THREAD

**Issue by JiangMaox** [spdk/spdk#2100]
# Bug report
vfio-user transport assertion failed while reboot vm

## Expected Behavior

Reboot success
## Current Behavior

root@waikikibeach37:~/spdk# sshpass -p tester   ssh -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 10100 root@10.238.55.93
Warning: Permanently added '[10.238.55.93]:10100' (ECDSA) to the list of known hosts.
Last login: Mon Jul 26 14:43:51 2021
[root@localhost ~]#
[root@localhost ~]#
[root@localhost ~]# reboot
Connection to 10.238.55.93 closed by remote host.
Connection to 10.238.55.93 closed.
root@waikikibeach37:~/spdk#
root@waikikibeach37:~/spdk#
root@waikikibeach37:~/spdk#
root@waikikibeach37:~/spdk# [2021-08-17 07:15:02.295780] memory.c: 893:vtophys_iommu_unmap_dma: *NOTICE*: Cannot clear DMA mapping, error 22, ignored
[2021-08-17 07:15:02.296272] memory.c: 893:vtophys_iommu_unmap_dma: *NOTICE*: Cannot clear DMA mapping, error 22, ignored
[2021-08-17 07:15:02.296730] memory.c: 893:vtophys_iommu_unmap_dma: *NOTICE*: Cannot clear DMA mapping, error 22, ignored
nvmf_tgt: /root/spdk/libvfio-user/lib/dma.c:179: dma_controller_remove_region: Assertion `region->refcnt == 0' failed.

## Steps to Reproduce

1. create a vfio-user transport and assign to vms
2. ssh to second VM and reboot
3. details refer to launch script:

#!/usr/bin/env bash

./build/bin/nvmf_tgt -p 0 -m 0xFF &
pid=$!
echo "PID: $pid"
sleep 1
#read -p "Waiting..."
rm -rf /dev/shm/muser
scripts/rpc.py nvmf_create_transport --trtype VFIOUSER

for i in $(seq 0 1); do
        cpu1=$((25 + i))
        cpu2=$((30 + i))
        vm_muser_dir="/home/jm/vms/$i/muser"
        rm -rf $vm_muser_dir
        mkdir -p $vm_muser_dir/iommu_group
        mkdir -p $vm_muser_dir/domain/muser$i/$i
        mkdir -p /dev/shm/muser/muser$i

        scripts/rpc.py bdev_malloc_create 128 512 -b Malloc${i}
        scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode${i} -s SPDK00${i} -a
        scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode${i} Malloc${i}
        scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode${i} -t VFIOUSER -a $vm_muser_dir/domain/muser$i/$i -s 0
        ln -s $vm_muser_dir/domain/muser$i/$i $vm_muser_dir/domain/muser$i/$i/iommu_group
        ln -s $vm_muser_dir/domain/muser$i/$i $vm_muser_dir/iommu_group/$i
        ln -s $vm_muser_dir/domain/muser$i/$i/bar0 /dev/shm/muser/muser$i/bar0
done

for i in $(seq 0 1); do

        vm_muser_dir="/home/jm/vms/$i/muser"

        sudo taskset -a -c ${cpu1},${cpu2} /home/jm/qemu/build/x86_64-softmmu/qemu-system-x86_64 \
                -m 1024 --enable-kvm -cpu host -smp 8 -vga std -vnc :10${i} -daemonize \
                -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,prealloc=yes,share=yes,host-nodes=1,policy=bind \
                -snapshot -monitor telnet:127.0.0.1:10${i}02,server,nowait \
                -numa node,memdev=mem -pidfile /home/jm/vms/${i}/qemu.pid \
                -serial file:/home/jm/vms/${i}/serial.log \
                -D /home/jm/vms/${i}/qemu.log \
                -chardev file,path=/home/jm/vms/${i}/seabios.log,id=seabios \
                -device isa-debugcon,iobase=0x402,chardev=seabios \
                -net user,hostfwd=tcp::10${i}00-:22,hostfwd=tcp::10${i}01-:8765 \
                -net nic -drive file=/root/vm_image/centos7${i}.img,if=none,id=os_disk \
                -device ide-hd,drive=os_disk,bootindex=0 \
                -device vfio-user-pci,socket=$vm_muser_dir/domain/muser${i}/${i}/cntrl
    echo " create vm_done"
done

## Context (Environment including OS version, SPDK version, etc.)

SPDK v21.10-pre git sha1 5263f0a12
ubuntu 20.04 5.4.0-81-generic
Qemu: https://github.com/tmakatos/qemu.git 177847aa98

**Comment by changpe1** [comment]
@JiangMaox  this is related with https://github.com/spdk/spdk/issues/2074, you can change libvfio-user as I mentioned in that issue to have another try, thanks.

**Comment by JiangMaox** [comment]
Related with #2074
