### ISSUE TITLE
Failed to alloc memory in specific numa nodes

### ISSUE THREAD

**Issue by USTCqzy** [spdk/spdk#2110]
# Bug report

Failed to alloc memory in specific numa nodes.

## Expected Behavior

bdevperf can alloc memory in specific numa nodes.
(Just like we can assign specific cores by flag -m as we want.)

## Current Behavior

Failed to alloc memory in specific numa nodes. (I have tried numactl, but it seems of no effect.)

## Possible Solution

Maybe there is a way to control SPDK hugepage memory allocation.

## Steps to Reproduce

1. numactl -m 0 ./bdevperf -q 1 -t 300 -w read -o 4096 -m [CPUs on node 0] -c test.json -C
2. ./bdevperf -q 1 -t 300 -w read -o 4096 -m [CPUs on node 0] -c test.json -C

Get same performance

test.json
```json
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_malloc_create",
            "params": {
              "name": "Malloc0",
              "num_blocks": 51200,
              "block_size": 512,
              "uuid": "a2e6d1bb-1cf5-484a-bd4a-ebbff0043c8b"
            }
          }
        ]
      }
    ]
  }
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 21.07.x
Ubuntu 20.04.2

**Comment by Comphix** [comment]
You may refer to https://software.intel.com/content/www/us/en/develop/articles/memory-in-dpdk-part-4-1811-and-beyond.html

"The memory reservation related parameters --m and --socket-mem have been changed to indicate the minimum amount DPDK will use. For example, initializing DPDK with --socket-mem 1024,1024 reserves 1 gigabyte (GB) on non-uniform memory access (NUMA) nodes 0 and 1, and this memory will never be released for the duration of the application’s lifetime."

**Comment by USTCqzy** [comment]
@Comphix 
"malloc bdevs are created from hugepage memory given to SPDK application." [https://spdk.io/doc/bdev.html](url)
I guess malloc bdev allocation related to hugepage memory allocation. As I used setup.sh, I found message like "the hugepages will be distributed on node0 by default" in setup.sh, but my results (as previously mentioned) are not in line with such messages.

```bash
spdk$ scripts/setup.sh -h
...
The following environment variables can be specified.
HUGEMEM           Size of hugepage memory to allocate (in MB). 2048 by default.
                  For NUMA systems, the hugepages will be distributed on node0 by
                  default.
HUGE_EVEN_ALLOC   If set to 'yes', hugepages will be evenly distributed across all
                  system's NUMA nodes (effectively ignoring anything set in HUGENODE).
                  Uses kernel's default for hugepages size.
```

**Comment by jimharris** [comment]
Hi,

It looks like you are asking for a couple of new features that don't exist today:

1) Ability to specify the numa node when creating a malloc bdev
2) Ability to specify the numa node when allocating buffers in bdevperf

Going to mark this as an enhancement request.  @USTCqzy - feel free to submit patches for either/both of these features.

Thanks,

Jim

**Comment by USTCqzy** [comment]
@jimharris 
Thanks for your answer.
However, my question remains. Why can't I control malloc bdev memory by allocating hugepage memory on specific numa node?

> @Comphix
> "malloc bdevs are created from hugepage memory given to SPDK application." [https://spdk.io/doc/bdev.html](url)
> I guess malloc bdev allocation related to hugepage memory allocation. As I used setup.sh, I found message like "the hugepages will be distributed on node0 by default" in setup.sh, but my results (as previously mentioned) are not in line with such messages.
> 
> ```shell
> spdk$ scripts/setup.sh -h
> ...
> The following environment variables can be specified.
> HUGEMEM           Size of hugepage memory to allocate (in MB). 2048 by default.
>                   For NUMA systems, the hugepages will be distributed on node0 by
>                   default.
> HUGE_EVEN_ALLOC   If set to 'yes', hugepages will be evenly distributed across all
>                   system's NUMA nodes (effectively ignoring anything set in HUGENODE).
>                   Uses kernel's default for hugepages size.
> ```

**Comment by jimharris** [comment]
Hi @USTCqzy,

Please read further down in the setup.sh help, specifically the HUGENODE option.

I also don't believe the numactl can be used to affect DPDK-based memory allocations (which the SPDK allocations are based on top of).  But you can check the DPDK code to confirm.

-Jim

**Comment by USTCqzy** [comment]
As I setup like this:
```bash
$ HUGENODE='nodes_hp[1]=2048' scripts/setup.sh
```
If it succeeded, there might be difference between using local numa cores and using remote ones.
```bash
threads=("0xFFFF" "[0,4,8,12,16,20,24,28,32,36,40,44,48,52,56,60]" "[1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61]")

bdevperf -q 1 -t 10 -w read -o 4096 -m "$thread" -c test.json -C
```
The first case is 4 cores each numa node, the second is all remote, and the last one is all local. However, here are the results.
 Total                       : 55295528.60 IOPS  215998.16 MiB/s
 Total                       : 45070442.00 IOPS  176056.41 MiB/s
 Total                       : 45119371.70 IOPS  176247.55 MiB/s

numa info attached:
```bash
$ numactl --hardware
available: 4 nodes (0-3)
node 0 cpus: 0 4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76
node 0 size: 63906 MB
node 0 free: 34521 MB
node 1 cpus: 1 5 9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77
node 1 size: 64479 MB
node 1 free: 35212 MB
node 2 cpus: 2 6 10 14 18 22 26 30 34 38 42 46 50 54 58 62 66 70 74 78
node 2 size: 64503 MB
node 2 free: 23510 MB
node 3 cpus: 3 7 11 15 19 23 27 31 35 39 43 47 51 55 59 63 67 71 75 79
node 3 size: 64501 MB
node 3 free: 16632 MB
node distances:
node   0   1   2   3 
  0:  10  21  21  21 
  1:  21  10  21  21 
  2:  21  21  10  21 
  3:  21  21  21  10
```

> Hi @USTCqzy,
> 
> Please read further down in the setup.sh help, specifically the HUGENODE option.
> 
> I also don't believe the numactl can be used to affect DPDK-based memory allocations (which the SPDK allocations are based on top of). But you can check the DPDK code to confirm.
> 
> -Jim
