### ISSUE TITLE
DPDK 21.08 fails to build with configure option --with-reduce

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2111]
# Bug report
DPDK 21.08 fails to build with current SPDK master branch, when option _"--with-reduce"_ is used during ./spdk/configure.
Meson build reports _Message: Disabling mlx5 [drivers/common/mlx5]: missing internal dependency "bus_auxiliary"_ even though it is present in:

spdk/dpdk/drivers/bus/auxiliary/

This leads to disabling of mlx5 driver all together and further failures to build the project. I have encountered this problem on CI side ([link](https://ci.spdk.io/results/autotest-per-patch/builds/56382/archive/unittest-vg-autotest/build.log)) and was able to reproduce it on my machine as well.

## Steps to Reproduce

1. download latest SPDK repo from https://github.com/spdk/spdk (_git clone https://github.com/spdk/spdk.git_)
2. _cd spdk_
3. _git submodule update --init_
4. _cd dpdk_
5. _git checkout spdk-21.08_
6. _cd .._
7. _./configure --enable-debug --enable-werror --with-rdma --with-idxd  --with-iscsi-initiator --with-nvme-cuse --with-pmdk --with-reduce --with-rbd --with-crypto --with-ocf --enable-ubsan --enable-asan --enable-coverage --with-fuse --with-raid5 --with-vfio-user --without-shared_
8. _make -j_

The project will build fine without the _"--with-reduce"_ option.

## Context
I have used the the latest master branch to reproduce it o my side.

**Comment by KKaras169169** [comment]
@AlekseyMarchuk Could you take a look at this?

**Comment by AlekseyMarchuk** [comment]
Sure, I'm on it

**Comment by AlekseyMarchuk** [comment]
@KKaras169169 the fix is very simple but it depends on rte_bus_auxiliary DPDK library which is absent in 21.05. So the fix can be applied only after update of DPDK submodule to 21.08. I think it can be done in your patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9211

Could you apply this small diff?
```
diff --git a/dpdkbuild/Makefile b/dpdkbuild/Makefile
index 5c6b4facf..d51b1a6e5 100644
--- a/dpdkbuild/Makefile
+++ b/dpdkbuild/Makefile
@@ -68,7 +68,7 @@ endif
 ifeq ($(CONFIG_REDUCE),y)
 DPDK_DRIVERS += compress compress/isal
 ifeq ($(CONFIG_REDUCE_MLX5),y)
-DPDK_DRIVERS += common/mlx5 compress/mlx5
+DPDK_DRIVERS += common/mlx5 compress/mlx5 bus/auxiliary
 endif
 DPDK_CFLAGS += -I$(ISAL_DIR)
 DPDK_LDFLAGS += -L$(ISAL_DIR)/.libs -lisal
diff --git a/lib/env_dpdk/env.mk b/lib/env_dpdk/env.mk
index 3ff5a7db6..3d1d3a8bd 100644
--- a/lib/env_dpdk/env.mk
+++ b/lib/env_dpdk/env.mk
@@ -95,7 +95,7 @@ else
 DPDK_LIB_LIST += rte_pmd_isal
 endif
 ifeq ($(CONFIG_REDUCE_MLX5),y)
-DPDK_LIB_LIST += rte_common_mlx5 rte_compress_mlx5
+DPDK_LIB_LIST += rte_common_mlx5 rte_compress_mlx5 rte_bus_auxiliary
 endif
 endif

```

**Comment by KKaras169169** [comment]
@AlekseyMarchuk Thank you for a quick response. I already applied this diff to my patch.

**Comment by tomzawadzki** [comment]
Patches [dpdk: update DPDK to 21.08 version](https://review.spdk.io/gerrit/c/spdk/spdk/+/9211) and [configure: Check if DPDK support mlx5_pci PMD](https://review.spdk.io/gerrit/c/spdk/spdk/+/9257) address this issue. Once merged can be closed.

**Comment by jimharris** [comment]
Patches merged.
