### ISSUE TITLE
[test-setup/devices] failed to find a suitable device due to GPT partition

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2114]
Looks very similar to https://github.com/spdk/spdk/issues/2090, however here a disk *was* found, but it had gpt, so it was skipped.

```
00:02:17.785   10:00:27	-- spdk/test/setup/common.sh@7 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/scripts/setup.sh reset
00:02:18.186   10:00:27	-- spdk/test/setup/devices.sh@171 -- # blocks=()
00:02:18.186   10:00:27	-- spdk/test/setup/devices.sh@171 -- # declare -a blocks
00:02:18.186   10:00:27	-- spdk/test/setup/devices.sh@172 -- # blocks_to_pci=()
00:02:18.186   10:00:27	-- spdk/test/setup/devices.sh@172 -- # declare -A blocks_to_pci
00:02:18.186   10:00:27	-- spdk/test/setup/devices.sh@173 -- # min_disk_size=2147483648
00:02:18.186   10:00:27	-- spdk/test/setup/devices.sh@175 -- # for block in "/sys/block/nvme"*
00:02:18.188    10:00:27	-- spdk/test/setup/devices.sh@176 -- # readlink -f /sys/block/nvme0n1/device/device
00:02:18.190   10:00:27	-- spdk/test/setup/devices.sh@176 -- # pci=/sys/devices/pci0000:80/0000:80:03.0/0000:89:00.0
00:02:18.191   10:00:27	-- spdk/test/setup/devices.sh@177 -- # pci=0000:89:00.0
00:02:18.191    10:00:27	-- spdk/test/setup/devices.sh@190 -- # blkid -s PTTYPE -o value /dev/nvme0n1
00:02:18.202   10:00:27	-- spdk/test/setup/devices.sh@190 -- # pt=gpt
00:02:18.202   10:00:27	-- spdk/test/setup/devices.sh@191 -- # [[ gpt == none ]]
00:02:18.202   10:00:27	-- spdk/test/setup/devices.sh@191 -- # [[ gpt == atari ]]
00:02:18.202   10:00:27	-- spdk/test/setup/devices.sh@196 -- # (( 0 > 0 ))
00:02:18.203    10:00:27	-- spdk/test/setup/devices.sh@196 -- # trap - ERR
00:02:18.203    10:00:27	-- spdk/test/setup/devices.sh@196 -- # print_backtrace
00:02:18.203    10:00:27	-- spdk/test/common/autotest_common.sh@985 -- # [[ ehxBET =~ e ]]
00:02:18.203    10:00:27	-- spdk/test/common/autotest_common.sh@987 -- # args=("${BASH_ARGV[@]}")
00:02:18.203    10:00:27	-- spdk/test/common/autotest_common.sh@987 -- # local args
00:02:18.204    10:00:27	-- spdk/test/common/autotest_common.sh@989 -- # xtrace_disable
00:02:18.204    10:00:27	-- spdk/test/common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
00:02:18.204    10:00:27	-- spdk/test/common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:02:18.204    10:00:27	-- spdk/test/common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:02:18.204    10:00:27	-- spdk/test/common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:02:18.204    10:00:27	-- spdk/test/common/autotest_common.sh@19 -- # set +x
00:02:18.204  ========== Backtrace start: ==========
00:02:18.204  
00:02:18.209  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/setup/devices.sh:196 -> main([])
00:02:18.209       ...
00:02:18.209     191 		if [[ $pt == none || $pt == atari ]] && (($(sec_size_to_bytes "${block##*/}") >= min_disk_size)); then
00:02:18.209     192 			blocks+=("${block##*/}")
00:02:18.209     193 			blocks_to_pci["${block##*/}"]=$pci
00:02:18.209     194 		fi
00:02:18.209     195 	done
00:02:18.209  => 196 	((${#blocks[@]} > 0))
00:02:18.209     197 	
00:02:18.209     198 	declare -r test_disk=${blocks[0]}
00:02:18.209     199 	
00:02:18.209     200 	run_test "nvme_mount" nvme_mount
00:02:18.209     201 	run_test "dm_mount" dm_mount
00:02:18.209       ...
00:02:18.209  
00:02:18.209  ========== Backtrace end ==========
```

After going through the builds on this machine (GP16), it seems that in a previous build a `test/bdev/blockdev.sh gpt` test failed and didn't clear the GPT. All builds are failing from that point on this machine.

It seems that autotest does clear the drives, but it does it *after* the setup.sh test. We should probably either do that before the test or always clear the GPT in `blockdev.sh` (or both).

```
# Delete all leftover lvols and gpt partitions
# Matches both /dev/nvmeXnY on Linux and /dev/nvmeXnsY on BSD
# Filter out nvme with partitions - the "p*" suffix
for dev in $(ls /dev/nvme*n* | grep -v p || true); do
	dd if=/dev/zero of="$dev" bs=1M count=1
done
```
Also, as a side note, should we do that for all NVMes under /dev/nvme*? Shouldn't we skip those with active mountpoints?

Link to the previous build: https://ci.spdk.io/results/autotest-per-patch/builds/56481/archive/nvme-phy-autotest/build.log

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/56487/archive/nvme-phy-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_56487.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_56490.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_56487.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_56492.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_56504.html

**Comment by mikeBashStuff** [comment]
I would suggest to add some routine to our CI which would clean up the nvme drives upon the failure right before we try to hit the affected system with the reset-job - this way we could remove entirely this quite unsafe piece of code from `autotest`:

```
for dev in $(ls /dev/nvme*n* | grep -v p || true); do
        dd if=/dev/zero of="$dev" bs=1M count=1
done
```
In this particular case it's not even run since `setup` tests try to be gentle with the underlying devices and they bail if they find devices in-use. But having something cleaning the drives directly from the CI would definitely help in avoiding issues like that altogether.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_56500.html

**Comment by mikeBashStuff** [comment]
@karlatec For the one-shot VM setups this is not needed at all and for actual hardware it's clearly too aggressive since it doesn't perform any checks at all it just wipes everything in its sight. The only alternative I can think of is to move what setup tests are doing into autotest and bail in case no free nvmes are found. But again, I think handling that from the CI side is better since doing these kind of checks all over the place in autotest suite is just messy in my mind.

**Comment by mikeBashStuff** [comment]
And having a documentation describing what autotest is actually doing would be also nice in case someone was about to actually use these tests in their own environment (not sure if we have something of that sort anywhere in the repo).

**Comment by tomzawadzki** [comment]
[Bug scrub] Steps we can do to resolve this issue
1) Move the dd above even setup.sh tests
2) Before dd, skip devices with non-SPDK GPT
3) Add clean up to `test/bdev/blockdev.sh` on test failure

**Comment by mikeBashStuff** [comment]
Series ready for review: https://review.spdk.io/gerrit/c/spdk/spdk/+/9291

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59129.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59352.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59348.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59359.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_59374.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59376.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59364.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59369.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59384.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59387.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59362.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59370.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59379.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59389.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59394.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59392.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59410.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59408.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59406.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59402.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59673.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_59677.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_59873.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61418.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61422.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61420.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61425.html

**Comment by mikeBashStuff** [comment]
Patches addressing used nvme devices got merged (https://review.spdk.io/gerrit/c/spdk/spdk/+/9291), closing for now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_66656.html
