### ISSUE TITLE
[crypto-autotest] ERROR: requested 2560 hugepages but 2471 could be allocated

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2118]
# CI Intermittent Failure

00:04:19.311  ************************************
00:04:19.311  START TEST spdkcli_tcp
00:04:19.311  ************************************

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/56542/archive/crypto-autotest/build.log

## Execution failed at

00:04:19.551  ========== Backtrace start: ==========
00:04:19.551  
00:04:19.557  in /var/jenkins/workspace/crypto-autotest/spdk/test/spdkcli/common.sh:48 -> source(["/var/jenkins/workspace/crypto-autotest/spdk/test/spdkcli/common.sh"])
00:04:19.557       ...
00:04:19.558     43  		$rootdir/test/app/match/match $testdir/match_files/${MATCH_FILE}.match
00:04:19.558     44  		rm -f $testdir/match_files/${MATCH_FILE}
00:04:19.558     45  	}
00:04:19.558     46  	
00:04:19.558     47  	# Allocate 5GB of hugepages to have some overhead for run_*()s
00:04:19.558  => 48  	HUGEMEM=5120 CLEAR_HUGE=yes "$rootdir/scripts/setup.sh"
00:04:19.558       ...
00:04:19.563  in test/spdkcli/tcp.sh:6 -> main([])
00:04:19.563       ...
00:04:19.563     1   	#!/usr/bin/env bash
00:04:19.563     2   	
00:04:19.563     3   	testdir=$(readlink -f $(dirname $0))
00:04:19.563     4   	rootdir=$(readlink -f $testdir/../..)
00:04:19.563     5   	source $rootdir/test/common/autotest_common.sh
00:04:19.563  => 6   	source $rootdir/test/spdkcli/common.sh
00:04:19.563     7   	
00:04:19.563     8   	function err_cleanup() {
00:04:19.563     9   		if [ -n "$socat_pid" ]; then
00:04:19.563     10  			killprocess $socat_pid || true
00:04:19.563     11  		fi
00:04:19.563       ...
00:04:19.564  
00:04:19.564  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_56542.html

**Comment by tomzawadzki** [comment]
[Bug scrub] The actual failure occurs due to allotment of hugepages
```
00:04:19.549  ## ERROR: requested 2560 hugepages but 2471 could be allocated .
00:04:19.549  ## Memory might be heavily fragmented. Please try flushing the system cache, or reboot the machine.
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mkenguva. log: https://ci.spdk.io/public_build/autotest-per-patch_56953.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_57762.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_57960.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58250.html

**Comment by tomzawadzki** [comment]
@mikeBashStuff Any updates on changes on the SM7 ?

**Comment by mikeBashStuff** [comment]
@tomzawadzki The grub's env was completely broken for some reason - fixed that and updated the kernel cmdline as well (iommu was disabled, as compared to other nodes in the pool, so now vfio should be used instead of uio for the tests). Nothing in particular changed regarding the hp setup since it all looks sane to me. Added the node back to the pool to see how it behaves so let's monitor for now.

**Comment by mikeBashStuff** [comment]
No reports for almost a month, I think we can close this for now. Also, there's the https://review.spdk.io/gerrit/c/spdk/spdk/+/10209 series which should mitigate similar issues further.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_70361.html
