### ISSUE TITLE
something about the rpc of SPDK

### ISSUE THREAD

**Issue by hellowaywewe** [spdk/spdk#212]
Hi, 
I am a new guy who is currently trying to learn and use the rpc of SPDK. If I need to make the other applications call the SPDK to receive what they want, such as: get_luns. what should I do? I know there are  some files of lib/rpc/rpc.c and lib/jsonrpc/jsonrpc.c which provide functions of rpc's server. Should I write the example file of server.c  so that I can connect with it to get something about SPDK through scripts/rpc.py. For this reason, the server.c should be able to Initialize and start the rpc'server.

I looked at the directory structure of the SPDK, and I also made and installed the SPDK in Ubuntu16.04. I did not see any active process about SPDK in the system, so I think whether SPDK exists as a library rather than as a process.  

Am I right?  Could anyone can tell me? 

Regards,
Helloway

**Comment by optimistyzy** [comment]
@hellowaywewe  rpc is a component, and it is integrated with applications you created (e.g., nvmf target  or iSCSI target and etc).  And the application can use the configuration file to enable rpc or not. And for the detailed rpc logic, you need to implement it by yourself. I suggest you can refer the rpc logic in NVMe-oF target as an example.

**Comment by hellowaywewe** [comment]
@optimistyzy Thanks a lot.  I ran it successfully through nvmf_tgt.

**Comment by dverkamp-intel** [comment]
Assuming this is resolved - if not, please reopen/file a new issue.
