### ISSUE TITLE
[nvmf-tcp-vg-autotest] "1 device(s) expected, found 2" during nvmf_filesystem_incapsule test

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2123]
# CI Intermittent Failure

During nvmf-tcp-vg-autotest, nvmf_filesystem_incapsule, two available nvme devices were reported, when one was expected to be found. This happened right after setting a tcp listener. 

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/56699/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

00:04:38.394  ************************************
00:04:38.394  START TEST nvmf_filesystem_incapsule
00:04:38.394  ************************************

...

00:04:40.217  [2021-08-23 11:56:52.545141] tcp.c: 758:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.0.0.2 port 4420 ***
00:04:40.231   11:56:52	-- nvmf/target/filesystem.sh@55 -- # nvme connect -t tcp -n nqn.2016-06.io.spdk:cnode1 -a 10.0.0.2 -s 4420
00:04:40.348   11:56:52	-- nvmf/target/filesystem.sh@57 -- # waitforserial SPDK00000000000001
00:04:40.348   11:56:52	-- common/autotest_common.sh@1030 -- # local i=0
00:04:40.348   11:56:52	-- common/autotest_common.sh@1031 -- # local nvme_device_counter=1 nvme_devices=0
00:04:40.348   11:56:52	-- common/autotest_common.sh@1032 -- # [[ -n '' ]]
00:04:40.348   11:56:52	-- common/autotest_common.sh@1040 -- # sleep 2
00:04:42.351   11:56:54	-- common/autotest_common.sh@1041 -- # (( i++ <= 15 ))
00:04:42.353    11:56:54	-- common/autotest_common.sh@1042 -- # lsblk -l -o NAME,SERIAL
00:04:42.353    11:56:54	-- common/autotest_common.sh@1042 -- # grep -c SPDK00000000000001
00:04:42.362   11:56:54	-- common/autotest_common.sh@1042 -- # nvme_devices=2
00:04:42.362   11:56:54	-- common/autotest_common.sh@1043 -- # (( nvme_devices == nvme_device_counter ))
00:04:42.362   11:56:54	-- common/autotest_common.sh@1044 -- # (( nvme_devices > nvme_device_counter ))
00:04:42.362  Waiting for devices
00:04:42.362   11:56:54	-- common/autotest_common.sh@1045 -- # echo '1 device(s) expected, found 2'
00:04:42.362  1 device(s) expected, found 2
00:04:42.362   11:56:54	-- common/autotest_common.sh@1047 -- # echo 'Waiting for devices'
00:04:42.362   11:56:54	-- common/autotest_common.sh@1048 -- # sleep 1

... _**(above part repeats 15 times)**_

00:04:58.553   11:57:10	-- common/autotest_common.sh@1041 -- # (( i++ <= 15 ))
00:04:58.553   11:57:10	-- common/autotest_common.sh@1050 -- # return 1
00:04:58.553    11:57:10	-- nvmf/target/filesystem.sh@57 -- # trap - ERR
00:04:58.554    11:57:10	-- nvmf/target/filesystem.sh@57 -- # print_backtrace
00:04:58.554    11:57:10	-- common/autotest_common.sh@985 -- # [[ ehxBET =~ e ]]
00:04:58.554    11:57:10	-- common/autotest_common.sh@987 -- # args=("${BASH_ARGV[@]}")
00:04:58.554    11:57:10	-- common/autotest_common.sh@987 -- # local args
00:04:58.555    11:57:10	-- common/autotest_common.sh@989 -- # xtrace_disable
00:04:58.555    11:57:10	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:04:58.555    11:57:10	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:04:58.555    11:57:10	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:04:58.556    11:57:10	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:04:58.556    11:57:10	-- common/autotest_common.sh@19 -- # set +x
00:04:58.556  ========== Backtrace start: ==========
00:04:58.556  
00:04:58.562  in test/nvmf/target/filesystem.sh:57 -> nvmf_filesystem_part(["4096"])
00:04:58.562       ...
00:04:58.563     52  		$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:04:58.563     53  		$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT
00:04:58.563     54  	
00:04:58.563     55  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:04:58.563     56  	
00:04:58.563  => 57  		waitforserial "$NVMF_SERIAL"
00:04:58.563     58  		nvme_name=$(lsblk -l -o NAME,SERIAL | grep -oP "([\w]*)(?=\s+${NVMF_SERIAL})")
00:04:58.563     59  	
00:04:58.563     60  		mkdir -p /mnt/device
00:04:58.563     61  	
00:04:58.563     62  		parted -s /dev/${nvme_name} mklabel msdos mkpart primary '0%' '100%'
00:04:58.563       ...
00:04:58.571  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:957 -> run_test(["nvmf_filesystem_incapsule"],["nvmf_filesystem_part"],["4096"])
00:04:58.571       ...
00:04:58.571     952 		timing_enter $test_name
00:04:58.571     953 		echo "************************************"
00:04:58.571     954 		echo "START TEST $test_name"
00:04:58.571     955 		echo "************************************"
00:04:58.571     956 		xtrace_restore
00:04:58.571  => 957 		time "$@"
00:04:58.571     958 		xtrace_disable
00:04:58.571     959 		echo "************************************"
00:04:58.571     960 		echo "END TEST $test_name"
00:04:58.571     961 		echo "************************************"
00:04:58.571     962 		timing_exit $test_name
00:04:58.571       ...
00:04:58.580  in test/nvmf/target/filesystem.sh:90 -> main(["--transport=tcp"])
00:04:58.580       ...
00:04:58.580     85  		killprocess $nvmfpid
00:04:58.580     86  		nvmfpid=
00:04:58.580     87  	}
00:04:58.580     88  	
00:04:58.580     89  	run_test "nvmf_filesystem_no_incapsule" nvmf_filesystem_part 0
00:04:58.580  => 90  	run_test "nvmf_filesystem_incapsule" nvmf_filesystem_part 4096
00:04:58.580     91  	
00:04:58.580     92  	nvmftestfini
00:04:58.581       ...
00:04:58.581  
00:04:58.581  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_56699.html

**Comment by mikeBashStuff** [comment]
Same cause as #2060 so let's consider it as a duplicate. Closing.
