### ISSUE TITLE
[ubuntu18-vg-autotest] Tests don't appear to start

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2127]
0:02:19.204  + vagrant_dir_root=/home/vagrant/spdk_repo
00:02:19.204  + vagrant_dir_spdk=/home/vagrant/spdk_repo/spdk
00:02:19.204  + cd ubuntu1804-libvirt
00:02:19.204  + trap 'vagrant destroy -f' SIGTERM SIGINT EXIT
00:02:19.204  + vagrant ssh -c 'uname -a'
00:02:26.124  + vagrant destroy -f
00:02:32.906  ==> default: Removing domain...
00:02:33.608  Build step 'Execute shell' marked build as failure
00:02:33.700  [PostBuildScript] - [INFO] Executing post build scripts.
00:02:33.706  [ubuntu18-vg-autotest] $ /usr/bin/env bash /tmp/jenkins15591787769200107298.sh
00:02:33.713  + [[ -n ubuntu1804 ]]
00:02:33.713  + mv /var/jenkins/workspace/ubuntu18-vg-autotest/ubuntu1804-libvirt/output /var/jenkins/workspace/ubuntu18-vg-autotest/output
00:02:33.732  [ubuntu18-vg-autotest] $ /usr/bin/env bash /tmp/jenkins10546300098119486968.sh
00:02:33.737  Start stage post_get_build_log.sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_56845.html

**Comment by changpe1** [comment]
[Bug Scrub] @karlatec can you take a look? thanks.

**Comment by tomzawadzki** [comment]
[Bug scrub] This issue has literally no logs to go off of unfortunately. There has been no occurrence outside of the single one, let's close it.
