### ISSUE TITLE
[nvmf_multipath] The log file try.txt had the first few seconds logs. We don't know if the test succeeded or failed.

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2128]
00:11:43.403  [2021-08-24 21:38:00.129892] app.c: 540:spdk_app_start: *NOTICE*: Total cores available: 1
00:11:43.403  [2021-08-24 21:38:00.446005] reactor.c: 936:reactor_run: *NOTICE*: Reactor started on core 0
00:11:43.403  [2021-08-24 21:38:00.446092] accel_engine.c:1005:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:11:43.403  Running I/O for 10 seconds...
00:11:43.403  [2021-08-24 21:38:03.583389] nvme_qpair.c: 730:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
00:11:43.403  [2021-08-24 21:38:03.583479] nvme_ctrlr.c: 981:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode1] in failed state.
00:11:43.403  [2021-08-24 21:38:03.583490] bdev_nvme.c: 751:bdev_nvme_failover_start: *NOTICE*: Start failover from 192.168.100.8:4420 to 192.168.100.8:4421
00:11:43.403  [2021-08-24 21:38:03.583497] nvme_ctrlr.c: 975:nvme_ctrlr_fail: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] already in failed state
00:11:43.403  [2021-08-24 21:38:03.645853] rdma_verbs.c: 111:spdk_rdma_qp_destroy: *WARNING*: Destroying qpair with queued Work Requests
00:11:43.403  [2021-08-24 21:38:03.646566] bdev_nvme.c:3378:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:11:43.403  [2021-08-24 21:38:03.646614] bdev_nvme.c:3378:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:11:43.403  [2021-08-24 21:38:03.646644] bdev_nvme.c:3378:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:11:43.403  [2021-08-24 21:38:03.646671] bdev_nvme.c:3378:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:11:43.403  [2021-08-24 21:38:03.646698] bdev_nvme.c:3378:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:11:43.403  [2021-08-24 21:38:03.646725] bdev_nvme.c:3378:bdev_nvme_writev: *ERROR*: writev failed: rc = -6

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_56847.html

**Comment by changpe1** [comment]
[Bug Scrub] @shuhei-matsumoto could you take a look? thanks.

**Comment by shuhei-matsumoto** [comment]
I read the log https://ci.spdk.io/results/autotest-per-patch/builds/56847/archive/nvmf-phy-autotest/build.log in detail.

The test determines success or failure by grepping failover count in try.txt.
bdevperf could write error log into try.txt only for the first 700 miliseconds and included only one failover.
Storage was full and failed to write data to file?

The end of try.txt was

> 00:11:43.403  [2021-08-24 21:38:03.650127] nvme_ctrlr.c:1457:nvme_ctrlr_reset_pre: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] resetting controller
> 00:11:43.403  [2021-08-24 21:38:03.786010] bdev_nvme.c: 528:bdev_nvme_reset_complete: *NOTICE*: Resetting controller successful.

try.txt should include logs by 21:38:11

>00:11:32.184   21:38:00	-- nvmf/host/multipath.sh@38 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t rdma -a 192.168.100.8 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
>00:11:32.520  NVMe0n1
>00:11:32.532   21:38:01	-- nvmf/host/multipath.sh@39 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t rdma -a 192.168.100.8 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:11:32.788  
00:11:32.804   21:38:01	-- nvmf/host/multipath.sh@42 -- # rpc_pid=340129
00:11:32.804   21:38:01	-- nvmf/host/multipath.sh@44 -- # sleep 1
00:11:32.804   21:38:01	-- nvmf/host/multipath.sh@41 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/bdev/bdevperf/bdevperf.py -s /var/tmp/bdevperf.sock perform_tests
00:11:33.806   21:38:02	-- nvmf/host/multipath.sh@46 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
00:11:33.947   21:38:02	-- nvmf/host/multipath.sh@48 -- # sleep 3
00:11:36.949   21:38:05	-- nvmf/host/multipath.sh@50 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t rdma -a 192.168.100.8 -s 4422 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:11:38.410  
00:11:38.426   21:38:07	-- nvmf/host/multipath.sh@51 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4421
00:11:38.570   21:38:07	-- nvmf/host/multipath.sh@53 -- # sleep 3
00:11:41.572   21:38:10	-- nvmf/host/multipath.sh@56 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
00:11:41.695  [2021-08-24 21:38:10.314467] rdma.c:2670:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.8 port 4420 ***
00:11:41.705   21:38:10	-- nvmf/host/multipath.sh@58 -- # sleep 1
00:11:42.707   21:38:11	-- nvmf/host/multipath.sh@60 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4422
00:11:42.855   21:38:11	-- nvmf/host/multipath.sh@62 -- # wait 340129
00:11:43.013  0
00:11:43.026   21:38:11	-- nvmf/host/multipath.sh@64 -- # killprocess 340118
00:11:43.026   21:38:11	-- spdk/test/common/autotest_common.sh@808 -- # '[' -z 340118 ']'
00:11:43.026   21:38:11	-- spdk/test/common/autotest_common.sh@812 -- # kill -0 340118
00:11:43.026    21:38:11	-- spdk/test/common/autotest_common.sh@813 -- # uname
00:11:43.029   21:38:11	-- spdk/test/common/autotest_common.sh@813 -- # '[' Linux = Linux ']'
00:11:43.030    21:38:11	-- spdk/test/common/autotest_common.sh@814 -- # ps --no-headers -o comm= 340118
00:11:43.065   21:38:11	-- spdk/test/common/autotest_common.sh@814 -- # process_name=reactor_0
00:11:43.065   21:38:11	-- spdk/test/common/autotest_common.sh@818 -- # '[' reactor_0 = sudo ']'
00:11:43.066   21:38:11	-- spdk/test/common/autotest_common.sh@826 -- # echo 'killing process with pid 340118'
00:11:43.066  killing process with pid 340118
00:11:43.066   21:38:11	-- spdk/test/common/autotest_common.sh@827 -- # kill 340118
00:11:43.066   21:38:11	-- spdk/test/common/autotest_common.sh@832 -- # wait 340118
00:11:43.400   21:38:12	-- nvmf/host/multipath.sh@66 -- # cat /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/host/try.txt

In the other test run, try.txt included logs by the end of run.

>00:12:52.963  Waiting for process to start up and listen on UNIX domain socket /var/tmp/bdevperf.sock...
00:12:52.964   09:13:23	-- spdk/test/common/autotest_common.sh@704 -- # xtrace_disable
00:12:52.964   09:13:23	-- spdk/test/common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:12:52.964   09:13:23	-- spdk/test/common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:12:52.964   09:13:23	-- spdk/test/common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:12:52.965   09:13:23	-- spdk/test/common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:12:52.965   09:13:23	-- spdk/test/common/autotest_common.sh@19 -- # set +x
00:12:53.737   09:13:23	-- spdk/test/common/autotest_common.sh@723 -- # xtrace_enable
00:12:53.737   09:13:23	-- spdk/test/common/autotest_common.sh@724 -- # (( i == 0 ))
00:12:53.737   09:13:23	-- spdk/test/common/autotest_common.sh@728 -- # return 0
00:12:53.737   09:13:23	-- nvmf/host/multipath.sh@38 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t rdma -a 192.168.100.8 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:12:54.064  NVMe0n1
00:12:54.079   09:13:24	-- nvmf/host/multipath.sh@39 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t rdma -a 192.168.100.8 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:12:54.308  
00:12:54.324   09:13:24	-- nvmf/host/multipath.sh@42 -- # rpc_pid=111132
00:12:54.324   09:13:24	-- nvmf/host/multipath.sh@41 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/bdev/bdevperf/bdevperf.py -s /var/tmp/bdevperf.sock perform_tests
00:12:54.324   09:13:24	-- nvmf/host/multipath.sh@44 -- # sleep 1
00:12:55.327   09:13:25	-- nvmf/host/multipath.sh@46 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
00:12:55.477   09:13:25	-- nvmf/host/multipath.sh@48 -- # sleep 3
00:12:58.480   09:13:28	-- nvmf/host/multipath.sh@50 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t rdma -a 192.168.100.8 -s 4422 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:12:59.975  
00:12:59.990   09:13:30	-- nvmf/host/multipath.sh@51 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4421
00:13:00.144   09:13:30	-- nvmf/host/multipath.sh@53 -- # sleep 3
00:13:03.147   09:13:33	-- nvmf/host/multipath.sh@56 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
00:13:03.275  [2021-08-30 09:13:33.478717] rdma.c:2670:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 192.168.100.8 port 4420 ***
00:13:03.292   09:13:33	-- nvmf/host/multipath.sh@58 -- # sleep 1
00:13:04.294   09:13:34	-- nvmf/host/multipath.sh@60 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4422
00:13:04.443   09:13:34	-- nvmf/host/multipath.sh@62 -- # wait 111132
00:13:06.549  0
00:13:06.563   09:13:36	-- nvmf/host/multipath.sh@64 -- # killprocess 111124
00:13:06.563   09:13:36	-- spdk/test/common/autotest_common.sh@808 -- # '[' -z 111124 ']'
00:13:06.563   09:13:36	-- spdk/test/common/autotest_common.sh@812 -- # kill -0 111124
00:13:06.564    09:13:36	-- spdk/test/common/autotest_common.sh@813 -- # uname
00:13:06.567   09:13:36	-- spdk/test/common/autotest_common.sh@813 -- # '[' Linux = Linux ']'
00:13:06.567    09:13:36	-- spdk/test/common/autotest_common.sh@814 -- # ps --no-headers -o comm= 111124
00:13:06.603   09:13:36	-- spdk/test/common/autotest_common.sh@814 -- # process_name=reactor_0
00:13:06.603   09:13:36	-- spdk/test/common/autotest_common.sh@818 -- # '[' reactor_0 = sudo ']'
00:13:06.603   09:13:36	-- spdk/test/common/autotest_common.sh@826 -- # echo 'killing process with pid 111124'
00:13:06.603  killing process with pid 111124
00:13:06.603   09:13:36	-- spdk/test/common/autotest_common.sh@827 -- # kill 111124
00:13:06.604   09:13:36	-- spdk/test/common/autotest_common.sh@832 -- # wait 111124
00:13:06.952   09:13:37	-- nvmf/host/multipath.sh@66 -- # cat /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/host/try.txt

>00:13:06.957  [2021-08-30 09:13:36.679791] bdev_nvme.c:3381:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:13:06.957  [2021-08-30 09:13:36.679818] bdev_nvme.c:3381:bdev_nvme_writev: *ERROR*: writev failed: rc = -6
00:13:06.957  [2021-08-30 09:13:36.679853] nvme_ctrlr.c:1457:nvme_ctrlr_reset_pre: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] resetting controller

**Comment by shuhei-matsumoto** [comment]
I renamed the title and added the infrastructure label for now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_57418.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_57452.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_57422.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_57530.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_57698.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_57707.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_57801.html

**Comment by shuhei-matsumoto** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/57728/archive/nvmf-phy-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_57826.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58175.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58195.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58248.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58345.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_58335.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_58337.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_58588.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_58607.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_58601.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58650.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58768.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58986.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_59323.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59440.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_59470.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_59495.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_59597.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_60132.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_60386.html

**Comment by tomzawadzki** [comment]
Another instance https://ci.spdk.io/public_build/autotest-per-patch_60485.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_60448.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_60730.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_61411.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_61412.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61568.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61604.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61609.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61917.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61970.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62062.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62044.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62092.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62085.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62128.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62154.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_62213.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_62531.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62630.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62651.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62649.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62518.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62730.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62668.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62744.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Maciej-Szulik. log: https://ci.spdk.io/public_build/autotest-per-patch_62865.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62879.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_62935.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_63047.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @rafalste. log: https://ci.spdk.io/public_build/autotest-per-patch_63073.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_62926.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_63133.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_63100.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_63092.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_62999.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_63277.html

**Comment by yty77566872** [comment]
邮件收到，我会尽快回复的~

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_63278.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_63616.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_63615.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_63792.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_64107.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_64251.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_64323.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_64603.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_64617.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_64638.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_66424.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_66426.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_66450.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_67974.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_68326.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: Not Found

**Comment by shuhei-matsumoto** [comment]
One update for this issue.

We may be able to improve the non-multipath failover feature.

We always failover to the next path if connecting to the current path failed.

I noticed that we got RDMA_CM_EVENT_TIMEWAIT_EXIT when connecting qpair. In this case, the current connection may be still live. So retrying to the current path without switching to the next path may be better.

This is only for RDMA transport.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: Not Found

**Comment by tomzawadzki** [comment]
[Bug scrub] The multipath has seen changes around the 22.01 LTS release, together with the tests. It does not seem to occur for quite a while, so this issue can be closed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_73539.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_74786.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75030.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75039.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75303.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75302.html

**Comment by shuhei-matsumoto** [comment]
I am investigating this issue again.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75574.html

**Comment by shuhei-matsumoto** [comment]
The last registration was 3 weeks ago. Let's close this issue again.
