### ISSUE TITLE
bdev nvme module does not check cdw0 bit 0 when handling abort completions

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2131]
The bdev nvme module allows the user to specify the action to take when the nvme driver reports a timeout - NONE, ABORT, RESET.

If ABORT is selected, we currently check the completion status of the abort - if it completed with error status, we escalate to a reset.  But the controller is also allowed to complete the abort command with no error status, but set cdw0 bit 0 to 1.  This indicates that the controller processed the abort request, but was not able to abort the specified command.  The bdev nvme module also needs to reset in this case.

**Comment by changpe1** [comment]
Patch has been merged, so closing it now.
