### ISSUE TITLE
[nvmf-tcp-phy-autotest ] Cannot unload nvme related kernel modules.

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#2138]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/57178/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

00:18:49.702   09:19:19	-- nvmf/host/perf.sh@48 -- # sync
00:18:49.712   09:19:19	-- nvmf/host/perf.sh@49 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
00:18:49.930   09:19:20	-- nvmf/host/perf.sh@51 -- # '[' 0 -eq 1 ']'
00:18:49.930   09:19:20	-- nvmf/host/perf.sh@94 -- # trap - SIGINT SIGTERM EXIT
00:18:49.930   09:19:20	-- nvmf/host/perf.sh@96 -- # nvmftestfini
00:18:49.930   09:19:20	-- spdk/test/nvmf/common.sh@462 -- # nvmfcleanup
00:18:49.930   09:19:20	-- spdk/test/nvmf/common.sh@239 -- # sync
00:18:49.934   09:19:20	-- spdk/test/nvmf/common.sh@241 -- # '[' tcp == tcp ']'
00:18:49.935   09:19:20	-- spdk/test/nvmf/common.sh@242 -- # set +e
00:18:49.935   09:19:20	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:49.935   09:19:20	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:49.938  rmmod nvme_tcp
00:18:49.948   09:19:20	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:49.951  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:49.951   09:19:20	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:50.954   09:19:21	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:50.954   09:19:21	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:50.957   09:19:21	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:50.960  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:50.961   09:19:21	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:51.963   09:19:22	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:51.963   09:19:22	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:51.967   09:19:22	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:51.971  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:51.971   09:19:22	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:52.973   09:19:23	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:52.973   09:19:23	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:52.976   09:19:23	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:52.979  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:52.980   09:19:23	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:53.982   09:19:24	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:53.982   09:19:24	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:53.985   09:19:24	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:53.989  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:53.989   09:19:24	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:54.991   09:19:25	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:54.992   09:19:25	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:54.994   09:19:25	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:54.998  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:54.999   09:19:25	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:56.001   09:19:26	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:56.001   09:19:26	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:56.004   09:19:26	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:56.008  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:56.008   09:19:26	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:57.010   09:19:27	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:57.011   09:19:27	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:57.013   09:19:27	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:57.017  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:57.017   09:19:27	-- spdk/test/nvmf/common.sh@249 -- # sleep 1
00:18:57.385  Build timed out (after 15 minutes). Marking the build as failed.
00:18:57.402  Build was aborted
00:18:57.403  [PostBuildScript] - [INFO] Executing post build scripts.
00:18:57.413  [nvmf-tcp-phy-autotest] $ /usr/bin/env bash /tmp/jenkins7274798584644258707.sh
00:18:57.419  Start stage post_get_build_log.sh
00:18:58.019   09:19:28	-- spdk/test/nvmf/common.sh@243 -- # for i in {1..20}
00:18:58.020   09:19:28	-- spdk/test/nvmf/common.sh@244 -- # modprobe -v -r nvme-tcp
00:18:58.023   09:19:28	-- spdk/test/nvmf/common.sh@245 -- # modprobe -v -r nvme-fabrics
00:18:58.027  modprobe: FATAL: Module nvme_fabrics is in use.
00:18:58.027   09:19:28	-- spdk/test/nvmf/common.sh@249 -- # sleep 1

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_57178.html

**Comment by changpe1** [comment]
[Bug Scrub] maybe the RDMA driver is using the fabric module, so let's keep it open for a while.

**Comment by mikeBashStuff** [comment]
I think the issue described in the title is a red herring here - the loop which attempts to unload `nvme-*` modules from the kernel should iterate for max 20 times, here it didn't even reach the half of that. The job was eventually hit by a timeout but at the beginning of the log you can see that there were 4 minutes lost on preparing the job (from which 3 minutes got wasted on fetching the actual commit to test).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58168.html

**Comment by ksztyber** [comment]
@mikeBashStuff I'm not sure this is the case. Only the last loop didn't reach 20 iterations, but all of the earlier nvmf tests had the same problem and they *did* reach 20 iterations. That means that each of these tests spent 20 extra seconds trying to rmmod the nvme-fabrics module, which I think could explain the timeout.

**Comment by mikeBashStuff** [comment]
@ksztyber Hmm, you are right. And the `nvmftestfini()` prevents `nvmfcleanup()` from aborting the tests earlier on hence the slow agony.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58297.html

**Comment by tomzawadzki** [comment]
Closing, no new reports for over 2 months.
