### ISSUE TITLE
deadlock when shutdown down vhost and reboot vm

### ISSUE THREAD

**Issue by subo7** [spdk/spdk#214]
kill the vhost with SIGTERM, the stack is:

Thread 3 (Thread 0x7f78503e6700 (LWP 118585)):
#0  0x00007f789987cf4d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f7899878d02 in _L_lock_791 () from /lib64/libpthread.so.0
#2  0x00007f7899878c08 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000044247a in rte_vhost_driver_get_features (path=0x7f788e25ebf0 "/home/spdk/vhost.0", features=0x7f78503e5b38) at socket.c:583
#4  0x0000000000449534 in vhost_user_set_features (dev=0x7f788e25e3c0, features=6) at vhost_user.c:178
#5  0x000000000044b12e in vhost_user_msg_handler (vid=0, fd=3) at vhost_user.c:1073
#6  0x000000000044197a in vhost_user_read_cb (connfd=3, dat=0x24930c0, remove=0x7f78503e5d48) at socket.c:278
#7  0x000000000044c998 in fdset_event_dispatch (arg=0x6aabc0 <vhost_user+8192>) at fd_man.c:273
#8  0x00007f7899876dc5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f78995a472d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f784fbe5700 (LWP 120367)):
#0  0x00007f7899879bdc in pthread_mutex_unlock () from /lib64/libpthread.so.0
#1  0x000000000044c7ec in fdset_del (pfdset=0x6aabc0 <vhost_user+8192>, fd=3) at fd_man.c:197
#2  0x00000000004429a1 in rte_vhost_driver_unregister (path=0x7f784fbe3d70 "/home/spdk/vhost.0") at socket.c:734
#3  0x0000000000429885 in session_shutdown (arg=0x0) at vhost.c:644
#4  0x00007f7899876dc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f78995a472d in clone () from /lib64/libc.so.6

**Comment by darsto** [comment]
Hello subo7
Thanks for the report. I created the following patch that should fix this issue: https://review.gerrithub.io/c/386294/
Regards,
D.
