### ISSUE TITLE
[scheduler/load_balancing] busy threads found to be moved across cores

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2140]
# CI Intermittent Failure
Seems like the test failed, because on of the threads (thread0) was scheduled on two cpus (cpu2 and cpu3), while it was expected to be running on a single one. It only happens in the first sample.
```
00:10:45.824  *Sample 1
00:10:46.371    Thread 2 (thread0) on cpu2; load: 100%
00:10:46.372    Thread 3 (thread1) on cpu2; load: 100%
00:10:46.421    No threads found on cpu3
00:10:46.975  *Sample 2
00:10:47.600    Thread 3 (thread1) on cpu2; load: 100%
00:10:48.141    Thread 2 (thread0) on cpu3; load: 100%
00:10:48.695  *Sample 3
00:10:49.237    Thread 3 (thread1) on cpu2; load: 100%
00:10:49.777    Thread 2 (thread0) on cpu3; load: 100%
00:10:50.331  *Sample 4
00:10:50.871    Thread 3 (thread1) on cpu2; load: 100%
00:10:51.410    Thread 2 (thread0) on cpu3; load: 100%
00:10:51.964  *Sample 5
00:10:52.503    Thread 3 (thread1) on cpu2; load: 100%
00:10:53.130    Thread 2 (thread0) on cpu3; load: 100%
00:10:53.151  Thread 2 (thread0) cpus: 2 3
00:10:53.151  Thread 3 (thread1) cpus: 2
00:10:53.152  ========== Backtrace start: ==========
00:10:53.152  
00:10:53.162  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/load_balancing.sh:80 -> busy([])
00:10:53.162       ...
00:10:53.162     75  		# thread not becoming idle even for a tick, scheduler should not put any other threads on
00:10:53.162     76  		# that cpu nor move its assigned thread to any other cpu.
00:10:53.162     77  		printf 'Thread %u (%s) cpus: %s\n' "$thread0" "${thread_map[thread0]}" "${thread0_cpus[*]:-none}"
00:10:53.162     78  		printf 'Thread %u (%s) cpus: %s\n' "$thread1" "${thread_map[thread1]}" "${thread1_cpus[*]:-none}"
00:10:53.162     79  		[[ ${thread0_cpus[*]} != "${thread1_cpus[*]}" ]]
00:10:53.162  => 80  		((${#thread0_cpus[@]} == 1 && ${#thread1_cpus[@]} == 1 && all_set == 1))
00:10:53.162     81  	
00:10:53.162     82  		xtrace_restore
00:10:53.162     83  	}
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/57404/archive/nvme-phy-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_57404.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_57404.html

**Comment by tomzawadzki** [comment]
Proposed fix https://review.spdk.io/gerrit/c/spdk/spdk/+/9387

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62506.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62539.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_66538.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_76819.html
