### ISSUE TITLE
nvmf/vfio-user: map_admin_cmd_req() does not check the PSDT field properly

### ISSUE THREAD

**Issue by antroseco** [spdk/spdk#2141]
# Bug report

## Expected Behavior

The NVMe 2.0a standard states that 
> SGLs shall not be used for Admin commands in NVMe over PCIe implementations.

Therefore, `map_admin_cmd_req()` should verify that the PSDT field is set to 0 (signaling that PRPs are used), and fail gracefully otherwise.

## Current Behavior

```C
	/* ADMIN command will not use SGL */
	assert(req->cmd->nvme_cmd.psdt == 0);
	iovcnt = vfio_user_map_cmd(ctrlr, req, req->iov, len);
```

This is currently only checked with an `assert`, which is optimised out in release builds. Hence, `vfio_user_map_cmd()` will happily call `nvme_cmd_map_sgls()` if PSDT is not 0.

**Comment by changpe1** [comment]
thanks here is the fix patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9383
