### ISSUE TITLE
autotest.sh leaves processes after test failure

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#2154]
# Bug report

Sometimes when test fail autotest.sh leaves active processes on machine.
For example for CI job nvmf-phy-autotest:
root      541528       1 99 Sep08 ?        4-03:30:20 /var/jenkins/workspace/nvmf-phy-autotest/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0xF

or for CI job "nvme-phy-autotest"
root     1241112       1  2 12:27 ?        00:00:34 qemu-system-x86_64 -daemonize -display none -m 8192 -pidfile /root/qemupid -hda /root/spdk_dependencies/spdk_test_image.

## Expected Behavior

autotest.sh should kill all it's processes on exit.

## Current Behavior

Currently it leaves processes when test fail.

## Possible Solution

Probably some additional trap or fix in script is needed. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mikeBashStuff** [comment]
Series addressing the issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/10209

**Comment by tomzawadzki** [comment]
Patches have been merged, issue can be closed.
