### ISSUE TITLE
Make install not coping DPDK .so files.

### ISSUE THREAD

**Issue by Davido71** [spdk/spdk#2155]
# Bug report

For SPDK version 21.07 with shared is enabled, running make install copies all the SPDK .so files to /usr/local/lib but not any of the DPDK files. Previous version (v21.07) I was able to cd into DPDK directory and run sudo make install.

## Expected Behavior

All .so files and soft links (libspdk* and  librte*) should be installed to /usr/local/lib directory 

## Current Behavior

Only libspdk* .so files and associated soft links are installed into /usr/local/lib.

## Steps to Reproduce

1. Checkout code with git and update all submodules 
2. ./configure --with-shared
3. make 
4. sudo make install
5. ls /usr/local/lib

**Comment by yidong0635** [comment]
Got failures as above steps:  commit:e91d7428f9968d9e208b1994cc67a71e597abf6d
cc: error: /home/spdk/build/lib/libspdk_event_scheduler.so: No such file or directory
make[4]: *** [/home/spdk/mk/spdk.lib.mk:108: /home/spdk/build/lib/libspdk_event_iscsi.so.3.0] Error 1
make[3]: *** [/home/spdk/mk/spdk.subdirs.mk:44: iscsi] Error 2
make[2]: *** [/home/spdk/mk/spdk.subdirs.mk:44: subsystems] Error 2
make[1]: *** [/home/spdk/mk/spdk.subdirs.mk:44: event] Error 2
make: *** [/home/spdk/mk/spdk.subdirs.mk:44: module] Error 2
need double confirm about this.

**Comment by yidong0635** [comment]
sometimes, 
Using 1. make clean.
           2. ./configure --with-shared 
           3. make (not make -j)  compiling reports error as issue described.
 if compiles successfully:
DPDP libs such as librte_*.so will not be copied  to /usr/local/lib.

**Comment by Davido71** [comment]
Here is more details in my steps: First of all I'm building on a AMD  Ryzen 7 3700X machine with Linux Mint 20.2.

1. git clone --depth 1 --branch v21.07 https://github.com/spdk/spdk spdk_21.07
2. cd spdk_21.07
3. python3 -m pip install --upgrade pip
4. git submodule update --init
5. Linux Mint only: cd scripts/pkgdep
6. Linux Mint only: ln -s debian.sh linuxmint.sh
7. Back to spdk_21.07 directory: sudo ./scripts/pkgdep.sh
8. ./configure --with-shared --without-isal
9. make (-j or not doesn't matter)
10. sudo make install
11. sudo ldconfig
12. ls /usr/local/lib (the bug: missing all librte* files)

The prevision version I initially used was  v21.07
from spdk directory after everything built without errors.
1. cd dpdk
2. sudo make install (would copy all librte* files to /usr/local/lib)
3. sudo ldconfig

My theory is when the newer releases of SPDK changed the build system  to  meson  ninja  build,  is missing the install step for DPDK.
