### ISSUE TITLE
Performance drop in Test Case 4: NVMe-oF Performance with increasing # of connections

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#2158]
# Bug report

## Expected Behavior

Have constant level of performance results

## Current Behavior

Have about 60% IOPS drop.

## Possible Solution

When doing bisect between v21.04 and v21.07 have found two possible commits:
2cd948c with IOPS results (which are not stable): 

- 375605.052
- 338690.083
- 1058384.612
- 1077318.904
- 333754.914
 
d9f5da13e with IOPS results: 

- 339574.61
- 310367.165
- 307845.986
- 308828.500

last good commit, what gives me good results: 
1347830be:
	1071312.400
	1064084.727
	1062692.048
	1071384.636
	1069010.953

## Steps to Reproduce

config.json:
```
{
  "general": {
    "username": "sys_sgci",
    "password": "espidikej",
    "transport": "tcp"
  },
  "target": {
    "nic_ips": ["20.0.0.1", "20.0.1.1", "10.0.0.1", "10.0.1.1"],
    "mode": "spdk",
    "use_null_block": false,
    "nvmet_dir": "/home/sys_sgci/nvmetcli",
    "core_mask": "[0-1,20-21]",
    "zcopy_settings": true,
    "sar_settings": [true, 10, 1, 90]
  },
  "initiator1": {
    "ip": "10.211.11.74",
    "nic_ips": ["20.0.0.2", "20.0.1.2"],
    "target_nic_ips": ["20.0.0.1", "20.0.1.1"],
    "fio_dir": "/usr/src/fio",
    "mode": "kernel",
    "extra_params": "",
    "num_cores": 4
  },
  "initiator2": {
    "ip": "10.211.11.73",
    "nic_ips": ["10.0.0.2", "10.0.1.2"],
    "target_nic_ips": ["10.0.0.1", "10.0.1.1"],
    "fio_dir": "/usr/src/fio",
    "mode": "kernel",
    "extra_params": "",
    "num_cores": 4
  },
  "fio": {
    "bs": ["4k"],
    "qd": [64],
    "rw": ["randwrite"],
    "rwmixread": 70,
    "num_jobs": 1,
    "run_time": 60,
    "ramp_time": 10,
    "run_num": 1
  }
}
```
1. Run `run_nvmf.py` script located in `spdk/scripts/perf/nvmf/run_nvmf.py`

**Comment by optimistyzy** [comment]
Hi @wawryk https://github.com/spdk/spdk/commit/2cd948c4a6fb0b26a495dfc861d26f7dfe9bc90d is used to fix a coredump issue related test reported by @karlatec (#1970). Previously there is a refactoring work in posix (https://github.com/spdk/spdk/commit/1ae601b573b8cf2be93b87b4fbd7ef491cbb6d87#diff-12ec6112c947de645d68808a3642d4c7346e4053497d9fd96201873d8893f403). So what my suggestion is that:  1  Go back to an earlier version and not using the change and see what it helps; 2  Using the uring on the initiator and check whether there is similar issue with uring (And the purpose is to eliminate the possibility in the general socket or in upper layer if no performance drop issue with uring socket implementaiton. Then we can make sure the issue happens in posix implementation)

**Comment by wawryk** [comment]
@benlwalker 
i revert 2cd948c on v21.07
```
git log --oneline
76c47f94b (HEAD) Revert "sock/posix: fix the socket pipe_has_data or socket_has_data."
adeb04968 (tag: v21.07) SPDK 21.07
7003e8309 scripts: remove gdb from Python requirements file
631592f92 autobuild.sh: Update DPDK 21.05 patches
98060549d pkgdep/git: Patch refspdk repos
26e8bc2ea nvmf: In zcopy, delay setting req->data until end of start operation
```
as You suggest on yesterday call, and here results from 5 tests: 
```
1062614.949
1062913.526
1069970.912
1053818.593
1062085.589
```
This IOPS are expected, and look stable in five runs.

Also I do 5 runs on v21.07 to confirm, that revert give us expected result.
Here IOPS from v21.07:
```
330253.377
416645.394
376561.136
335755.951
395605.992
```

Created revert commit on current master: https://review.spdk.io/gerrit/c/spdk/spdk/+/9510 
Please review.

**Comment by optimistyzy** [comment]
@wawryk If we simplily revert this patch, we  will trigger #1970 issue again? So could you alSo revert 1ae601b patch and see what's performance is.

**Comment by wawryk** [comment]
@optimistyzy 
I create revert patch for 1ae601b like You mention above, [patch here](https://review.spdk.io/gerrit/c/spdk/spdk/+/9512)
performance tests results: 
```
1064018.306
1044570.609
1060271.308
1056533.826
```
IOPS results above looks good.
@benlwalker can you take a look on it ?

**Comment by wawryk** [comment]
@optimistyzy 
I do some tests like You ask
git log: 
```
62fd19d94 (HEAD) sock/posix: Fix the NULL pointer access while rotating the socks_has_data list
ddd45c07c Revert "sock/posix: fix the socket pipe_has_data or socket_has_data."
593055821 spdk_top: display pollers' busy counts
78d7ce3c9 spdk_top: fix sorting when total data is displayed
```
Performance results: 
```
1110424.762
1123174.235
1116011.789
1100134.201
```
iops looks ok.

**Comment by wawryk** [comment]
I also run fast test 10 times with parameters from #1970 and all tests pass
@karlatec how often this segmentation fault occurs ? 10 tests is enough to confirm that it works ?

**Comment by karlatec** [comment]
@wawryk to be honest - I don't know. The issue was created in closed in June, so I don't remember.
If it's not mentioned then it was probably 100% reproducible, on each run with given configuration.

**Comment by optimistyzy** [comment]
> @wawryk to be honest - I don't know. The issue was created in closed in June, so I don't remember.
> If it's not mentioned then it was probably 100% reproducible, on each run with given configuration.

Hi  @karlatec Could you also run this test described in #1970 ? We need make sure that the issue can be fixed and still keep the good performance.  Thanks.

**Comment by karlatec** [comment]
@optimistyzy  For any re-test requests please ask @wawryk.

@wawryk could you please do a re-run for @optimistyzy?

**Comment by wawryk** [comment]
Run 5 tests today, all finished without errors

**Comment by optimistyzy** [comment]
@wawryk great，So I think that the solution is to revert my old patch and apply the new one.

**Comment by wawryk** [comment]
Ok, then we need this two patches merged to close this issue:
https://review.spdk.io/gerrit/c/spdk/spdk/+/9510
https://review.spdk.io/gerrit/c/spdk/spdk/+/9521

**Comment by tomzawadzki** [comment]
The performance drop is no longer observed after merging https://review.spdk.io/gerrit/c/spdk/spdk/+/9510. Closing this issue.

As for #1970, so far has not reproduced with the revert above. If it does, then original issue should be re-opened.
