### ISSUE TITLE
endless loop in vhost session_shutdown

### ISSUE THREAD

**Issue by subo7** [spdk/spdk#216]
the patch below fix a double free when vhost shutdown:
https://github.com/spdk/spdk/commit/3788c907bb25be18a57a57f7b29da7d0a50d7eee#diff-3bf650d7f74e96c9bcedd900433213ac

I merged it to spdk-17.07.
but when I shutdown vhost while starting a vm connecting to it, vhost got stuck in session shutdown:
do {
			pthread_mutex_lock(&vsocket->conn_mutex);
			conn = TAILQ_FIRST(&vsocket->conn_list);
			pthread_mutex_unlock(&vsocket->conn_mutex);
} while (conn != NULL);

vsocket->conn_list never be empty, conn->connfd is reused by  a eventfd(maybe a vring kick/call).
no poll event appear, connection thread won't remove the  conn from vsocket->conn_list.

**Comment by darsto** [comment]
could you paste the vhost log? I'll be trying to reproduce this issue.

**Comment by dverkamp-intel** [comment]
Any updates on this issue? Is this still reproducible in SPDK v18.01?

**Comment by subo7** [comment]
I have not encountered this problem again, If it happens again, i will update the log

**Comment by jimharris** [comment]
Closing issue based on feedback from @subo7.

Please re-open the issue if you encounter it again, with the vhost log.

Thanks,

-Jim
