### ISSUE TITLE
fio can't work when ocf bdev created with rpc

### ISSUE THREAD

**Issue by CryusYoung** [spdk/spdk#2161]
spdk version is v21.01x,
the test step is:
1. spdk configure with fio and ocf
2. create an ocf bdev(cache0) with rpc
3. fio test with fio conf.in

fio can't work. 
cache0.conf.in:
[root@localhost spdk]# cat cache0.conf.in 
[Split]
  Split Nvme0n1 2 10240

fio:
[root@localhost spdk]# cat cache0.fio 
[global]
ioengine=examples/bdev/fio_plugin/fio_plugin
spdk_conf=cache0.conf.in
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
runtime=30
rw=randwrite
bs=4k

[cache0]
iodepth=1
numjobs=1
filename=trtype=PCIe traddr=03.00.0 ns=1
#name=cache0

i've tried all method i could thought of. i'm here to ask for help to run fio with this creation method of ocf.
thx~

**Comment by Comphix** [comment]
@wanghailiangx , will you help on this issue?

**Comment by wanghailiangx** [comment]
@Comphix OK, let me have a look.

**Comment by wanghailiangx** [comment]
```
ioengine=examples/bdev/fio_plugin/fio_plugin
spdk_conf=cache0.conf.in
```
these have been changed to 
```
ioengine=build/fio/spdk_bdev
spdk_json_conf=cache0.json
```

cache0.json come from command: ./scripts/config_converter.py < cache0.conf.in > cache0.json

filename=trtype=PCIe traddr=0000.03.00.0 ns=1

If any errors else, please show here, thanks.

**Comment by CryusYoung** [comment]
> ```
> ioengine=examples/bdev/fio_plugin/fio_plugin
> spdk_conf=cache0.conf.in
> ```
> 
> these have been changed to
> 
> ```
> ioengine=build/fio/spdk_bdev
> spdk_json_conf=cache0.json
> ```
> 
> cache0.json come from command: ./scripts/config_converter.py < cache0.conf.in > cache0.json
> 
> filename=trtype=PCIe traddr=0000.03.00.0 ns=1
> 
> If any errors else, please show here, thanks.

thanks for  your reply. the problem is my spdk version is v20.01x, there is no spdk_bdev, even no build/fio directory. this version configured to fio_plugin, not the spdk_bedv in build/.
and i've succeed with the above method. but now i must use this verion because of some reasons,. 
if it can't work with conf.in file indeed, i will upgrade spdk to newer version.
thanks again~

**Comment by wanghailiangx** [comment]
Can you post the error log about cache0.fio with cache0.conf.in in v20.01x?

**Comment by CryusYoung** [comment]
> Can you post the error log about cache0.fio with cache0.conf.in in v20.01x?

the err log is:
spdk_fio_setup: ERROR: Unable to find bdev with name cache0

**Comment by rafalste** [comment]
I think the reason it fails is creating OCF bdev manually prior running fio. Configuration for OCF bdev should be passed in SPDK config file instead.
And another thing - are you trying to run fio on created bdev or are you using SPDK's fio_plugin according to [this guide](https://github.com/spdk/spdk/blob/v20.01.x/examples/bdev/fio_plugin/README.md)? I believe fio_plugin is the only way to run fio on bdevs created by SPDK but maybe there are some other methods I'm not aware of. Correct me if I'm wrong.

**Comment by wanghailiangx** [comment]
Yes, rafalste 's right. Let me give you an example for creating ocf bdev.
bdev.conf.in
```
[Nvme]
  TransportID "trtype:PCIe traddr:0000:03:00.0" Nvme0
[Split]
  Split Nvme0n1 2 10240
[AIO]
  AIO /dev/sdb AIO0
[OCF]
  OCF wb_test wb Nvme0n1p1 AIO0  ( you can set OCF wb_test wb Nvme0n1p1 Nvme0n1p2)
```
then
`fio cache0.fio--filename=wb_test`

**Comment by CryusYoung** [comment]
thanks very much, i've succeed in the way you mentioned several days ago. Thank you and rafalste again~发自我的华为手机-------- 原始邮件 --------发件人： wanghailiang ***@***.***>日期： 2021年9月17日周五 晚上7:22收件人： spdk/spdk ***@***.***>抄送： CryusYoung ***@***.***>, Author ***@***.***>主    题： Re: [spdk/spdk] fio can't work when ocf bdev created with rpc (#2161)
Yes, rafalste 's right. Let me give you an example for creating ocf bdev.
bdev.conf.in
[Nvme]
  TransportID "trtype:PCIe traddr:0000:03:00.0" Nvme0
[Split]
  Split Nvme0n1 2 10240
[AIO]
  AIO /dev/sdb AIO0
[OCF]
  OCF wb_test wb Nvme0n1p1 AIO0  ( you can set OCF wb_test wb Nvme0n1p1 Nvme0n1p2)

then
fio cache0.fio--filename=wb_test

**Comment by CryusYoung** [comment]
> I think the reason it fails is creating OCF bdev manually prior running fio. Configuration for OCF bdev should be passed in SPDK config file instead.
> And another thing - are you trying to run fio on created bdev or are you using SPDK's fio_plugin according to [this guide](https://github.com/spdk/spdk/blob/v20.01.x/examples/bdev/fio_plugin/README.md)? I believe fio_plugin is the only way to run fio on bdevs created by SPDK but maybe there are some other methods I'm not aware of. Correct me if I'm wrong.

yes,that is what i wanna know. thanks very very much~

**Comment by CryusYoung** [comment]
problem sloved, thank wanghailiang and rafalste
