### ISSUE TITLE
nvme_tcp_c2h_data_hdr_handle: *ERROR*: Invalid datao for tcp_req

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#2169]
# CI Intermittent Failure

fio_dif_digest

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/58570/archive/nvmf-tcp-uring-vg-autotest/build.log

## Execution failed at

00:14:14.180  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1176 -> fio_bdev(["--ioengine=spdk_bdev"],["--spdk_json_conf"],["/dev/fd/62"],["/dev/fd/61"])

**Comment by peluse** [comment]
dup of #2098?

**Comment by jimharris** [comment]
Yeah it is.  I'll copy this log over to #2098.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_58570.html
