### ISSUE TITLE
nvmf/vfio-user: doorbell writes are not validated

### ISSUE THREAD

**Issue by antroseco** [spdk/spdk#2171]
# Bug report

vfio-user controller does not validate doorbell writes (as suggested by the spec).

## Expected Behavior

See "Invalid Doorbell Write Value" in Figure 144 of the NVMe Base Specification 2.0a for a list of possible checks.

## Current Behavior

No validation takes place - the host is allowed to write any 32-bit value.
This could lead to all sorts of issues, e.g. writing `0xFFFF...` to the SQ tail would cause an infinite loop here
```C
while (sq_head(qpair) != new_tail) {
```

## Context

Affects SPDK master (`4aff2dfda7a7381620d8d80a53df0240d7fb58bc` at the time of writing)

CC: @jlevon

**Comment by changpe1** [comment]
Yeah, I agree that we should add a valid check for SQ tail doorbell register.

**Comment by changpe1** [comment]
Here is the patch to fix this issue, https://review.spdk.io/gerrit/c/spdk/spdk/+/9584, and it will also reports an error event for this case according to the specification.

**Comment by antroseco** [comment]
Great, thank you
