### ISSUE TITLE
nvmf/vfio-user: deleting the same SQ more than once hits an assert

### ISSUE THREAD

**Issue by antroseco** [spdk/spdk#2173]
# Bug report

Relevant code (`handle_del_io_q()`)
```C
	} else {
		/*
		 * This doesn't actually delete the SQ, We're merely telling the poll_group_poll
		 * function to skip checking this SQ.  The queue pair will be disconnected in Delete
		 * IO CQ command.
		 */
		assert(vu_qpair->state == VFIO_USER_QPAIR_ACTIVE);
		vu_qpair->state = VFIO_USER_QPAIR_DELETED;
	}
```

## Expected Behavior

First call to
`$ nvme admin-passthru /dev/nvme0 --opcode=0 --cdw10=1`
should return `SUCCESS`.

Second call to
`$ nvme admin-passthru /dev/nvme0 --opcode=0 --cdw10=1`
should return `INVALID_QUEUE_IDENTIFIER`.

## Current Behavior

First call to
`$ nvme admin-passthru /dev/nvme0 --opcode=0 --cdw10=1`
does return `SUCCESS`.

Second call to
`$ nvme admin-passthru /dev/nvme0 --opcode=0 --cdw10=1`
either crashes due to the `assert` or returns `SUCCESS` if it's a release build.

## Possible Solution

Change the `assert` to an `if` to pretend that the queue has already been deleted. Not sure how to deal with queue states other than `ACTIVE` or `DELETED`.

CC: @jlevon

**Comment by changpe1** [comment]
Thanks, here is the patch to fix it. https://review.spdk.io/gerrit/c/spdk/spdk/+/9604

**Comment by tomzawadzki** [comment]
Patch fixing the issue has been merged https://review.spdk.io/gerrit/c/spdk/spdk/+/9604. Closing the issue.
