### ISSUE TITLE
Builds failing due to lack of storage on the jenkins node

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2176]
Placeholder for issues similar to https://ci.spdk.io/public_build/autotest-per-patch_58892.html

**Comment by mikeBashStuff** [comment]
Issues has been already mitigated.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_58892.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_58896.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @nconnolly1. log: https://ci.spdk.io/public_build/autotest-per-patch_58883.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_59123.html

**Comment by tomzawadzki** [comment]
This was temporary CI infrastructure issue that has since been resolved.
