### ISSUE TITLE
DSA idxd better can enable the PMU performance counter the same as kernel idxd driver do 

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2177]
# Bug report

DSA idxd better can enable the PMU performance counter the same as kernel idxd driver do .
I am not sure if we need develop code in SPDK to enable idxd performance counter. 

## Expected Behavior
==below is kernel driver related enablement.
static void perfmon_pmu_enable(struct pmu *pmu)
{
	struct idxd_device *idxd = pmu_to_idxd(pmu);

	enable_perfmon_pmu(idxd);
}

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
I don't have the answer, probably not. @peluse any comments about this?

@gaowayne I believe we have better channel(slack, teams) to ask questions instead of here, so can you reach us via slack or teams next time? thanks.

**Comment by peluse** [comment]
@gaowayne yes for sure.  I've had it in the back of my mind but wasn't sure how valuable anyone would find it.  I'll close this and put it on Trello where we like to keep backlog items.  Feel free to work on it if not it's possible it well get some attention in the next quarter or so.
