### ISSUE TITLE
ADQ performance drop

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#2178]
# Bug report

It looks like ADQ do not use all available cores on target side.
For example, when I start test with 40 cores: and run spdk_top
Intel 800 Series network adapter  without ADQ: 
![image](https://user-images.githubusercontent.com/15612188/135040890-aaa39a44-b146-4562-9ef2-abda0880c931.png)
As we can see, all 40 core are busy.

Intel 800 Series network adapter with ADQ (enable_placement_id=1):
![image](https://user-images.githubusercontent.com/15612188/135040994-c58497a2-c063-41fa-b9c0-477dcc3a2be4.png)
Here, we have only 4 cores busy.

Intel 800 Series network adapter with ADQ (enable_placement_id=2):
![image](https://user-images.githubusercontent.com/15612188/135041236-d5b15f5b-2e44-475a-9c26-2122a571b79a.png)
when I change enable_placement_id parameter from 1:incoming_napi to 2:incoming_cpu, there are only 2 cores busy.

## Expected Behavior

Have better performance results when using ADQ.

## Current Behavior

Performance results are really bad.

## Steps to Reproduce

1. Configure ADQ with adq_config_guide
2. Run performance tests.

**Comment by benlwalker** [comment]
How many hardware queues were assigned to the traffic class? My guess is 4 and it needs to be 40.

**Comment by wawryk** [comment]
When we configure adq, we set in scripts queues equals to num cores:
```
        num_queues_tc0 = 2
        num_queues_tc1 = self.num_cores
```

**Comment by optimistyzy** [comment]
@msudheer337 Hi Sudheer, could you look at this issue? Whether there will be some misconfiguration of the adq scripts.

**Comment by tomzawadzki** [comment]
This was indeed misconfiguration, the `sudo tc filter add...` was not called.
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9703/ works around it, but it's already suggested to create a separate patch that targets this issue specifically.
@msudheer337 no need to look into this particular issue, thanks tho !

**Comment by wawryk** [comment]
[Patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/9717) created
