### ISSUE TITLE
Better to add DRIVER_OVERRIDE explanation to README.md

### ISSUE THREAD

**Issue by thatsdone** [spdk/spdk#2179]
# Bug report

Difficult to find out how to use `uio_pci_generic` under SR-IOV enabled environment.

## Expected Behavior

Users can easily enable uio devices even if they are using SR-IOV enabled environment.

## Current Behavior

When `scripts/setup.sh` was executed, vfio-pci driver is used and uio devices will not be created.
Actually, this is the correct behavior, and already considered by `scripts/setup.sh`.
Just setting DRIVER_OVERRIDE is the correct resolution.

But, it's better to add some descriptions to README.md on this topic, IMHO.

## Possible Solution

I think it's a good idea to add some descriptions to README.md, for example:

```
1. `Generic Help`

`scripts/setup.sh help` gives you useful information. It's recommended to read the help messages
in prior.

Putting this section after `Unite Tests` is a good place, IMHO.

2. `DRIVER_OVERRIDE option`

`scripts/setup.sh` detects hardware features and selects the device driver 
to be loaded automatically.

In case you are using SR-IOV enabled system, maybe vfio-pci could be used against your
intention to use uio_pci_generic. If this is the case, use the DRIVER_OVERRIDE environment variable
as you can see below.
```

## Steps to Reproduce

1. Prepare an SR-IOV enabled environment.
2. Install SPDK
3. execute `scripts/setup.sh`
4. `vfio-pci` is used and you would see `/dev/nvmeXYZ`, not `/dev/uio*`.

## Context (Environment including OS version, SPDK version, etc.)

distro: Ubuntu 20.04.2 LTS
kernel: Linux kioxia1 5.8.0-49-generic #55~20.04.1-Ubuntu SMP Fri Mar 26 01:01:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
SPDK: 
```
$ git log -n 1 --oneline
b0cdf7663 (HEAD) autobuild.sh: restore patches for older DPDK versions
$ git branch
* (HEAD detached at b0cdf7663)
  master
  v20.01.x
  v21.01.x
$
```

## Reference

`scripts/setup.sh help` example. I didn't notice these help messages at first and lost 30 min or so.

```
$ bash scripts/setup.sh help
Helper script for allocating hugepages and binding NVMe, I/OAT, VMD and Virtio devices
to a generic VFIO kernel driver. If VFIO is not available on the system, this script
will fall back to UIO. NVMe and Virtio devices with active mountpoints will be ignored.
All hugepage operations use default hugepage size on the system (hugepagesz).
Usage: setup.sh [config|reset|status|cleanup|help]

[config|reset|status|cleanup|help] - as following:
config            Default mode. Allocate hugepages and bind PCI devices.
cleanup           Remove any orphaned files that can be left in the system after SPDK application exit
reset             Rebind PCI devices back to their original drivers.
                  Also cleanup any leftover spdk files/resources.
                  Hugepage memory size will remain unchanged.
status            Print status of all SPDK-compatible devices on the system.
help              Print this help message.

The following environment variables can be specified.
HUGEMEM           Size of hugepage memory to allocate (in MB). 2048 by default.
                  For NUMA systems, the hugepages will be distributed on node0 by
                  default.
HUGE_EVEN_ALLOC   If set to 'yes', hugepages will be evenly distributed across all
                  system's NUMA nodes (effectively ignoring anything set in HUGENODE).
                  Uses kernel's default for hugepages size.
NRHUGE            Number of hugepages to allocate. This variable overwrites HUGEMEM.
HUGENODE          Specific NUMA node to allocate hugepages on. Multiple nodes can be
                  separated with comas. By default, NRHUGE will be applied on each node.
                  Hugepages can be defined per node with e.g.:
                  HUGENODE='nodes_hp[0]=2048,nodes_hp[1]=512,2' - this will allocate
                  2048 pages for node0, 512 for node1 and default NRHUGE for node2.
HUGEPGSZ          Size of the hugepages to use in kB. If not set, kernel's default
                  setting is used.
CLEAR_HUGE        If set to 'yes', the attempt to remove hugepages from all nodes will
                  be made prior to allocation.
PCI_ALLOWED
PCI_BLOCKED       Whitespace separated list of PCI devices (NVMe, I/OAT, VMD, Virtio).
                  Each device must be specified as a full PCI address.
                  E.g. PCI_ALLOWED="0000:01:00.0 0000:02:00.0"
                  To block all PCI devices use a non-valid address.
                  E.g. PCI_BLOCKED="none"
                  If PCI_ALLOWED and PCI_BLOCKED are empty or unset, all PCI devices
                  will be bound.
                  Each device in PCI_BLOCKED will be ignored (driver won't be changed).
                  PCI_BLOCKED has precedence over PCI_ALLOWED.
TARGET_USER       User that will own hugepage mountpoint directory and vfio groups.
                  By default the current user will be used.
DRIVER_OVERRIDE   Disable automatic vfio-pci/uio_pci_generic selection and forcefully
                  bind devices to the given driver.
                  E.g. DRIVER_OVERRIDE=uio_pci_generic or DRIVER_OVERRIDE=/home/public/dpdk/build/kmod/igb_uio.ko
PCI_BLOCK_SYNC_ON_RESET
                  If set in the environment, the attempt to wait for block devices associated
                  with given PCI device will be made upon reset
$
```

**Comment by jimharris** [comment]
Hi @thatsdone,

I don't have any problem with adding a short note to README.md telling users about running ```scripts/setup.sh --help``` to get information on additional parameters or environment variables.

But can you describe the configuration and use case where SR-IOV is enabled, but you want to use uio_pci_generic instead?  I'm mostly familiar with Intel platforms, and if kernel is configured with intel_iommu=on, you *must* use vfio-pci - uio_pci_generic won't work.  intel_iommu=pt will still default to using uio_pci_generic.

It sounds like you have a very specific configuration and use case here, and we would need to understand that further before suggesting that users override the default behavior from scripts/setup.sh.

Thanks,

Jim

**Comment by thatsdone** [comment]
Hi @jimharris ,

Thanks for your clarification requests.

Outline of my use case is a kind of converged system like the following:
* Each node has  bunch of NVMe devices (storage) and running VMs (compute).
* Each node is connected by RDMA capable NICs (Mellanox CX-5)
    * Each VM has at least one attached SR-IOV VF of the RNIC.
* the NVMe storage devices are controlled by a special management software stack (under development), and the software stack uses uio access of SPDK.
   * NVMe devices are out of scope of SR-IOV virtualization.
 
Here, the point is that I need SR-IOV only for RNICs, not for NVMe devices.

Regarding hardware and software:
* server: ASUS ESC4000A-E10
* CPU : AMD EPYC 7702P
* NIC: Mellanox ConnectX-5 (MT27800)
* NVMe: KXG60ZNV1T02 
* OS: Ubuntu 20.04.2 LTS (amd64)
* kernel: 5.8.0-49-generic
* SPDK: master branch around April 26, 2021. (with a special internal patch).

I hope that now I'm clear and the above is useful for the community. 

Best regards,
Masanori

**Comment by jimharris** [comment]
Thanks @thatsdone!  I understand your use case better now.  I've posted a patch to point users towards the setup.sh help:

https://review.spdk.io/gerrit/c/spdk/spdk/+/9676

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9676 has been merged. @thatsdone Does that resolve this issue from your point of view ?

**Comment by thatsdone** [comment]
Hi @tomzawadzki,

Yes, it looks good to me. :)
Thanks @jimharris !

Best regards,
Masanori
