### ISSUE TITLE
wrong logic when configure vhost controller with lcore larger than 63

### ISSUE THREAD

**Issue by subo7** [spdk/spdk#218]
spdk_vhost_parse_core_mask parse vdev cpumask and store it with uint64_t.
if configure a vhost app with  Reactormask 0x10000000000000000(RTE_MAX_LCORE = 128), and leave the vhost controller Cpumask  NULL,   spdk_vhost_parse_core_mask got the wrong cpumask of vdev(1 << 64 ).

**Comment by dverkamp-intel** [comment]
Pawel is right - we currently only support core masks up to 64 bits; however, we should be able to extend our core mask abstraction to handle larger numbers of cores.

I've added a Trello card to track this idea: https://trello.com/c/HnpEjtM0

**Comment by subo7** [comment]
i configured reactormask with 0x10000000000000000(socket 1) run vhost app on a server with 72 cpu,  reactor_64 thread is created successfully. but when i run a vm connecting to vhost, vhost is coredumped:
#0  0x000000000043119d in spdk_mempool_get ()
#1  0x000000000042c0ed in spdk_event_allocate ()
#2  0x000000000041c328 in vhost_timed_event_init ()
#3  0x000000000041d737 in spdk_vhost_timed_event_send ()
#4  0x000000000041f1c3 in new_device ()
#5  0x000000000042ed01 in vhost_user_msg_handler ()
#6  0x000000000042d8a2 in vhost_user_read_cb ()
#7  0x0000000000430e35 in fdset_event_dispatch ()

because vhost device find the wrong reactor in socket 0,  whose event_mempool is NULL, 

my spdk version is 17.07

**Comment by optimistyzy** [comment]
In my mind, we should remove the 64 core limitation

**Comment by dverkamp-intel** [comment]
As of commit 601bcbcf666516cd6a3e3a0b515d4ea477485187, all apps now support systems with more than 64 logical cores when specifying CPU masks.  Please let us know if you have any further issues.
