### ISSUE TITLE
[bdev_ut] git push review failed

### ISSUE THREAD

**Issue by mkenguva** [spdk/spdk#2188]
`bdev_ut.c: In function ‘bdev_multi_allocation’:
bdev_ut.c:4753:43: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
   snprintf(name[j], sizeof(name[j]), "bdev%d", j);
                                           ^~
bdev_ut.c:4753:38: note: directive argument in the range [0, 2147483646]
   snprintf(name[j], sizeof(name[j]), "bdev%d", j);
                                      ^~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /home/peluse/spdk/spdk/include/spdk/stdinc.h:58,
                 from /home/peluse/spdk/spdk/test/spdk_cunit.h:37,
                 from bdev_ut.c:35:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 6 and 15 bytes into a destination of size 10
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());

LINK iscsi_fuzz
  LINK part_ut
  LINK ctrlr_ut
  LINK ftl_io_ut
  LINK iscsi_ut
  LINK nvme_ns_cmd_ut
  LINK tcp_ut
  LINK bdev_ut
  LINK nvme_ns_ocssd_cmd_ut
  LINK blob_ut
cc1: all warnings being treated as errors
/home/peluse/spdk/spdk/mk/spdk.common.mk:459: recipe for target 'bdev_ut.o' failed
make[5]: *** [bdev_ut.o] Error 1
/home/peluse/spdk/spdk/mk/spdk.subdirs.mk:44: recipe for target 'bdev.c' failed
make[4]: *** [bdev.c] Error 2
/home/peluse/spdk/spdk/mk/spdk.subdirs.mk:44: recipe for target 'bdev' failed
make[3]: *** [bdev] Error 2
make[3]: *** Waiting for unfinished jobs....
  LINK json_parse_ut
/home/peluse/spdk/spdk/mk/spdk.subdirs.mk:44: recipe for target 'lib' failed
make[2]: *** [lib] Error 2
/home/peluse/spdk/spdk/mk/spdk.subdirs.mk:44: recipe for target 'unit' failed
make[1]: *** [unit] Error 2
/home/peluse/spdk/spdk/mk/spdk.subdirs.mk:44: recipe for target 'test' failed```

**Comment by optimistyzy** [comment]
change the size of the destination string according to the description, then the issue can be addressed，e.g., change the size of name From 6 to 11.

**Comment by mkenguva** [comment]
Hi Ziye, the bdev_ut is not my focus code. I did not edit bdev_ut tests. I rebase my accel_engine_ut patch on latest master today morning and no longer see this issue,
