### ISSUE TITLE
spdk_rpc_close should set g_jsonrpc_server to NULL

### ISSUE THREAD

**Issue by eyuval** [spdk/spdk#219]
I have added a new subsystem for my special purposes and then I get for some reason a 'double free error' on the rpc server pointer.  I noted that g_jsonrpc_server is not reset to NULL in spdk_rpc_close and I assume  that this is the reason why I get the double free error.

**Comment by dverkamp-intel** [comment]
I've posted a patch that does this: https://review.gerrithub.io/389394
