### ISSUE TITLE
blobstore: large unmap operations not performed optimally

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2190]
Reported by DAOS team (https://daosio.atlassian.net/browse/DAOS-8616 - may require an Atlassian account to view).

struct spdk_bs_dev defines its unmap and write_zeroes function pointers to take a uint32_t lba_count parameter.  uint32_t is not sufficient for 2TB+ SSDs formatted for 512B block size.

This primarily affects unmap operations, since by default we only write zeroes to the metadata pages which are a small fraction of the overall SSD space.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/9737

We should consider back porting this to SPDK 21.07.x and 21.01.x branches.

**Comment by jimharris** [comment]
The uint32_t parameters are problematic, and will be fixed with the 9737 patch above.

But the large unmap operations aren't taking effect for a different reason.  The spdk_bs_init() already tries to chunk up the large unmap into UINT32_MAX size chunks, but UINT32_MAX number of 512B blocks is not an even number of physical blocks on the SSD (usually 4KiB or 64KiB).  So some SSDs may just complete the associate DSM DEALLOCATE command without actually unmapping/deallocating any blocks, since you cannot unmap part of a physical block.

**Comment by dong-liuliu** [comment]
Do we need to lable this issue as "enhancement", and remove other lables?

**Comment by tomzawadzki** [comment]
Backports out for review:
https://review.spdk.io/gerrit/c/spdk/spdk/+/9970/
https://review.spdk.io/gerrit/c/spdk/spdk/+/9971/

**Comment by tomzawadzki** [comment]
Patches for latest SPDK and backports for LTS have been merged. This issue can now be closed.
