### ISSUE TITLE
Inconsistent crc found at the bdev layer

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#2191]
# Bug report
Hi, everyone. Recently, our testing colleagues found that the bdev layer occasionally has two consecutive crc verification results that are different. Even if a memory barrier is added, it has no effect. The following code is the test logic, output the crc check value for two consecutive iterations, and then compare whether they are equal. If they are not equal, print out the content in the iov.

```
@@ -3830,6 +3888,8 @@ bdev_writev_blocks_with_md(struct spdk_bdev_desc *desc, struct spdk_io_channel *
        struct spdk_bdev_io *bdev_io;
        struct spdk_bdev_channel *channel = spdk_io_channel_get_ctx(ch);
+       uint32_t crc = 0xffffffffUL;
+       uint32_t crc_tmp_1, crc_tmp_2, i, j;
+       char tmp[32][65536];
 
        if (!desc->write) {
                return -EBADF;
@@ -3854,12 +3914,59 @@ bdev_writev_blocks_with_md(struct spdk_bdev_desc *desc, struct spdk_io_channel *
        bdev_io->u.bdev.offset_blocks = offset_blocks;
        bdev_io_init(bdev_io, bdev, cb_arg, cb);
        SPDK_NOTICELOG("iovcnt:%d iov:%p md_buf:%p offset_blocks:%lu num_blocks:%lu md_inter:%d spdk_bdev_is_md_separate:%d\n", iovcnt, iov, md_buf,offset_blocks, num_blocks, spdk_bdev_is_md_interleaved(bdev), spdk_bdev_is_md_separat);
+       spdk_smp_rmb();
+
+       if (bdev_io->type == SPDK_BDEV_IO_TYPE_WRITE) {
+               SPDK_NOTICELOG("----------Total len:%lu-----------\n", bdev_io->u.bdev.num_blocks << 9);
+               for (i = 0; i < bdev_io->u.bdev.iovcnt; i++) {
+                       crc = spdk_crc32c_update(bdev_io->u.bdev.iovs[i].iov_base,
+                                       bdev_io->u.bdev.iovs[i].iov_len, crc);
+                       memcpy(tmp[i], bdev_io->u.bdev.iovs[i].iov_base, bdev_io->u.bdev.iovs[i].iov_len);
+               }
+               crc_tmp_1 = crc ^ 0xffffffffUL;
+
+               crc = 0xffffffffUL;
+               for (i = 0; i < bdev_io->u.bdev.iovcnt; i++) {
+                       crc = spdk_crc32c_update(bdev_io->u.bdev.iovs[i].iov_base,
+                                       bdev_io->u.bdev.iovs[i].iov_len, crc);
+               }
+               crc_tmp_2 = crc ^ 0xffffffffUL;
+               if (crc_tmp_1 != crc_tmp_2) {
+                       SPDK_NOTICELOG("Get it, crc_tmp_1:%u, crc_tmp_2:%u\n", crc_tmp_1, crc_tmp_2);
+                       for (i = 0; i < bdev_io->u.bdev.iovcnt; i++) {
+                               crc = SPDK_BDEV_CRC_32;
+                               crc = spdk_crc32c_update(bdev_io->u.bdev.iovs[i].iov_base,
+                                               bdev_io->u.bdev.iovs[i].iov_len, crc);
+                               crc ^= SPDK_BDEV_CRC_32;
+                               SPDK_NOTICELOG("WRITE iovs[%d], len:%u, crc:%u\n",
+                                               i, (uint32_t)bdev_io->u.bdev.iovs[i].iov_len, crc);
+                               for (j = 0; j < bdev_io->u.bdev.iovs[i].iov_len; j++) {
+                                       SPDK_NOTICELOG("ori:[%d]: 0x%x, then: 0x%x\n", j, tmp[i][j],
+                                                       *((char *)bdev_io->u.bdev.iovs[i].iov_base + j));
+                               }
+                       }
+                       SPDK_NOTICELOG("Calca it again\n");
+                       SPDK_NOTICELOG("----------Total len:%lu-----------\n", bdev_io->u.bdev.num_blocks << 9);
+                       crc = 0xffffffffUL;
+                       for (i = 0; i < bdev_io->u.bdev.iovcnt; i++) {
+                               crc = spdk_crc32c_update(bdev_io->u.bdev.iovs[i].iov_base,
+                                               bdev_io->u.bdev.iovs[i].iov_len, crc);
+                       }
+                       crc_tmp_1 = crc ^ 0xffffffffUL;
+
+                       crc = 0xffffffffUL;
+                       for (i = 0; i < bdev_io->u.bdev.iovcnt; i++) {
+                               crc = spdk_crc32c_update(bdev_io->u.bdev.iovs[i].iov_base,
+                                               bdev_io->u.bdev.iovs[i].iov_len, crc);
+                       }
+                       crc_tmp_2 = crc ^ 0xffffffffUL;
+                       SPDK_NOTICELOG("crc_tmp_1:%u, crc_tmp_2:%u\n", crc_tmp_1, crc_tmp_2);
+               }
+       }

```
## Expected Behavior
crc_tmp_1 allways equal crc_tmp_2

## Current Behavior
Sometimes crc_tmp_1 not equal to crc_tmp_2

bdev.c:3921:bdev_writev_blocks_with_md: *NOTICE*: ----------Total len:65536-----------
bdev.c:3936:bdev_writev_blocks_with_md: *NOTICE*: Get it, crc_tmp_1:789176956, crc_tmp_2:3503967504
bdev.c:3943:bdev_writev_blocks_with_md: *NOTICE*: WRITE iovs[0], len:8192, crc:1795457025
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[0]: 0x36, then: 0x36
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[1]: 0x30, then: 0x30
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[2]: 0x30, then: 0x30
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[3]: 0x30, then: 0x30
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[4]: 0x31, then: 0x31
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[5]: 0x36, then: 0x36
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[6]: 0x39, then: 0x39
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[7]: 0x37, then: 0x37
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[8]: 0x37, then: 0x37
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[9]: 0x33, then: 0x33
......
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[646]: 0xa, then: 0xa
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[647]: 0x0, then: 0x32
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[648]: 0x0, then: 0x30
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[649]: 0x0, then: 0x32
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[650]: 0x0, then: 0x31
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[651]: 0x0, then: 0x30
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[652]: 0x0, then: 0x39
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[653]: 0x0, then: 0x32
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[654]: 0x0, then: 0x38
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[655]: 0x0, then: 0x20
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[656]: 0x0, then: 0x30
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[657]: 0x0, then: 0x31
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[658]: 0x0, then: 0x3a
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[659]: 0x0, then: 0x35
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[660]: 0x0, then: 0x38
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[661]: 0x0, then: 0x3a
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[662]: 0x0, then: 0x30
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[663]: 0x0, then: 0x31
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[664]: 0x0, then: 0x2e
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[665]: 0x0, then: 0x36
......
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[972]: 0x0, then: 0x34
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[973]: 0x0, then: 0x34
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[974]: 0x0, then: 0x31
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[975]: 0x0, then: 0x32
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[976]: 0x0, then: 0x39
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[977]: 0x0, then: 0x34
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[978]: 0x0, then: 0xa
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[979]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[980]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[981]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[982]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[983]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[984]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[985]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[986]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[987]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[988]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[989]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[990]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[991]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[992]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[993]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[994]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[995]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[996]: 0x0, then: 0x0
bdev.c:3946:bdev_writev_blocks_with_md: *NOTICE*: ori:[997]: 0x0, then: 0x0
......
bdev.c:3950:bdev_writev_blocks_with_md: *NOTICE*: Calca it again
bdev.c:3951:bdev_writev_blocks_with_md: *NOTICE*: ----------Total len:65536-----------
bdev.c:3965:bdev_writev_blocks_with_md: *NOTICE*: crc_tmp_1:3503967504, crc_tmp_2:3503967504
bdev.c:3968:bdev_writev_blocks_with_md: *NOTICE*:

## Steps to Reproduce
1. Start the vhost process, create a bdev and vhost controller
2. Give this vhost controller to a virtual machine
3. Random write test using fio inside the virtual machine

## Context (Environment including OS version, SPDK version, etc.)
The spdk test code is based on the 20.10 branch of the main line.

Thanks,
        Su

**Comment by Comphix** [comment]
Could you have a try to config --with-out isa-l as this implementation is through ISA-L? Let's first have another check with the CPU version.

#ifdef SPDK_HAVE_ISAL

uint32_t
spdk_crc32c_update(const void *buf, size_t len, uint32_t crc)
{
	return crc32_iscsi((unsigned char *)buf, len, crc);
}

#elif defined(SPDK_HAVE_SSE4_2)

**Comment by Comphix** [comment]
Ok, in this case, it shall use the CPU (SSE4_2) version (the CPU with sse4_2 as mentioned). Could add some trace to make sure whether version is used. 

And maybe we still could have a try for the ISA-L version.

If this issue is gone with ISA-L version (as described, this issue could be reproduced after hours running), it could be some possible issue with the CPU (SSE4_2) implementation.

If this issue is still there with ISA-L version, will need to further narrow down...

Thanks Suhua!

**Comment by zlsh007** [comment]
I added debugging information, the logic is sse4_2. 

` Sat Oct  9 17:13:26 2021 440816 us: crc32c.c:  66:spdk_crc32c_update: *NOTICE*: sse4_2`
Later, I will run through the logic of isal to see if there is the same problem.

**Comment by changpe1** [comment]
You can run fio inside the VM with the verification enabled.

For your tests above, do you have a chance to test spdk_crc32_update() with allocated data buffers? we should narrow down this issue.

**Comment by zlsh007** [comment]
@changpe1 Do you want to calculate the CRC from the tmp array of memcpy after finding that crc_tmp_1 is not equal to crc_tmp_2, or calculate the CRC at each stage of iov copy? The method of fio verify remembers that there was no inconsistency in the previous operation, I will run the test again to verify it.

Thanks

**Comment by dong-liuliu** [comment]
From your issue description, memory barrier is used for some kind of concurrency consideration.
So probably that during CRC calculation and memory copy, data inside iovs was polluted.
Can you add some details about your external concurrency logic?

**Comment by zlsh007** [comment]
@jimharris Sorry I just saw this message today. I'll try it this way.

Thanks

Su

**Comment by zlsh007** [comment]
The test results are in, but so far the crc-inconsistent check information is in a self-implemented Bdev under the generic Bdev layer. I applied the same validation policy to both layers. CRC check is performed on the IOV data twice in a row. If any inconsistency is found, the DATA in the MEMCPY and IOV is printed out. Then, the DATA in the IOV and MEMCPY are verified twice in a row.he current phenomenon is that the data in MEMCPY is the same as the first CRC check in iov.  Verifying the IOV twice in a row yields the same CRC with the same value as the second CRC that failed the first CRC.

```
 *NOTICE*: Get it, crc_tmp_1:2810780199, crc_tmp_2:3139062245   
......
 *NOTICE*: iov addr:0x2000f218d860 ori:[61426]: 0x0, then: 0x2c
 *NOTICE*: iov addr:0x2000f218d860 ori:[61427]: 0x0, then: 0x32
 *NOTICE*: iov addr:0x2000f218d860 ori:[61428]: 0x0, then: 0x33
 *NOTICE*: iov addr:0x2000f218d860 ori:[61429]: 0x0, then: 0x37
 *NOTICE*: iov addr:0x2000f218d860 ori:[61430]: 0x0, then: 0x35
 *NOTICE*: iov addr:0x2000f218d860 ori:[61431]: 0x0, then: 0x36
 *NOTICE*: iov addr:0x2000f218d860 ori:[61432]: 0x0, then: 0x36
 *NOTICE*: iov addr:0x2000f218d860 ori:[61433]: 0x0, then: 0x31
 *NOTICE*: iov addr:0x2000f218d860 ori:[61434]: 0x0, then: 0x31
 *NOTICE*: iov addr:0x2000f218d860 ori:[61435]: 0x0, then: 0x35
 *NOTICE*: iov addr:0x2000f218d860 ori:[61436]: 0x0, then: 0x3b
 *NOTICE*: iov addr:0x2000f218d860 ori:[61437]: 0x0, then: 0x53
 *NOTICE*: iov addr:0x2000f218d860 ori:[61438]: 0x0, then: 0x45
 *NOTICE*: iov addr:0x2000f218d860 ori:[61439]: 0x0, then: 0x51
 *NOTICE*: Calca memcpy data
 *NOTICE*: memcpy data crc is:2810780199
 *NOTICE*: Calca it again
 *NOTICE*: Get it, crc_tmp_1:3139062245, crc_tmp_2:3139062245    
```

Thanks
  Su Hua

**Comment by zlsh007** [comment]
Clicking on the link directly may not reach the target page, you can copy the address to search.

**Comment by yidong0635** [comment]
@zlsh007  I got  compiling errors due to the unit of iovcnt, I found that sometime it uses uint32_t sometimes int, first of all , we should unify this , I am curious that doesn't have your meet this problem?

**Comment by yidong0635** [comment]
@zlsh007 Could you let me know what's your platform.  I plan to apply this to CI. but the unittest is failed.  Can you try that?
./test/unit/unittest.sh
```
spdk_crc32c_update (buf=0x10000, len=512, crc=crc@entry=4294967295) at crc32c.c:77
77                      crc_tmp64 = _mm_crc32_u64(crc_tmp64, block);
(gdb) up 1
#1  0x000000000041df19 in bdev_writev_blocks_with_md (desc=desc@entry=0x60f0000009a0, ch=ch@entry=0x612000000340, iov=iov@entry=0x7fffffffdc90, iovcnt=iovcnt@entry=3, md_buf=md_buf@entry=0xff000000, offset_blocks=offset_blocks@entry=14, num_blocks=<optimized out>, cb=<optimized out>,
    cb_arg=<optimized out>, opts=<optimized out>) at /home/yidong/spdk/lib/bdev/bdev.c:4103
4103                            crc = spdk_crc32c_update(bdev_io->u.bdev.iovs[i].iov_base,
(gdb) s

Program received signal SIGSEGV, Segmentation fault.
_mm_crc32_u64 (__V=<error reading variable: Cannot access memory at address 0x10000>, __C=4294967295) at /usr/lib/gcc/x86_64-redhat-linux/9/include/smmintrin.h:848
848       return __builtin_ia32_crc32di (__C, __V);
(gdb) s
0x00007ffff7699ba0 in __asan::AsanOnDeadlySignal(int, void*, void*) () from /usr/lib64/libasan.so.5
```

but I do some simple test but not reproduced using bdevperf, I need to confirm the patch is right edit.  Then will apply some 
complex procedures .

**Comment by zlsh007** [comment]
@yidong0635 Hi，This is my platform info：
CPU：
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                72
On-line CPU(s) list:   0-71
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz

Kernel：
3.10.0-862.3.0.0.el7

System：
CentOS Linux release 7.3.1611

**Comment by yidong0635** [comment]
That's very strange using bdevperf and fio in VM can't catch such error after a long run .

**Comment by Comphix** [comment]
Thanks @yidong0635 , @zlsh007 SuHua, have you hit the issue with the common SPDK bdev?

**Comment by changpe1** [comment]
As discussed in the community meeting, you can use fio or iozone as the test tool, for your own binary test tool we don't know if the test cases have *transaction* protect or not.  The data buffers maybe changed by your test tool during the IOs are live in the VM. @zlsh007

**Comment by zlsh007** [comment]
@changpe1 Okay, we are here to see if there is a problem with the test program itself. @Comphix Sorry, my local disk test has not come out yet. There is a problem after the code is transplanted. Data reading and writing will cause the process to be cored. I am still trying to solve this problem.However, according to Yidong’s test, this crc problem may not have much to do with the back-end bdev type.

**Comment by zlsh007** [comment]
Thank you everyone for your help. At present, the inconsistency of CRC in data writing is triggered by the use of wget command to copy files. But I think this problem should be normal. If the user performs a continuous update of a certain data block, the old request data may be part of the new and part of the old. However, in the end, the new request will also cover the old data as a whole, and there will be no data inconsistency.

**Comment by Comphix** [comment]
Thanks @zlsh007 Suhua for this update.

**Comment by changpe1** [comment]
@zlsh007 data consistency should be guaranteed, but it's up to different layers, e.g: for NVMe device, the atomic normally is logical block size,  file system based on NVMe device should have its own transaction support to respect this.

**Comment by zlsh007** [comment]
@changpe1 Yes, the block size level data in a request is atomic, only because the crc here has verified a lot of iovs to get an inconsistent crc data.
