### ISSUE TITLE
An error is reported when the SPDK connects to the iSCSI.

### ISSUE THREAD

**Issue by Pangzhihong** [spdk/spdk#2193]
**linux-DMEYYd:~ # /opt/uvp/spdk/vhost -c ~/vhost.conf**
vhost.c: 165:vhost_lock: *NOTICE*: lock vhost /var/run/vhost.lock.
app.c: 859:spdk_try_env_lock: *NOTICE*: lock file successfully:/var/run/hugepages_dpdk_lock.
Starting SPDK v19.01.1 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: vhost --iova-mode=pa --match-allocations --no-shconf -c 0x30 --no-pci --base-virtaddr=0x200000000000 --file-prefix=spdk_pid8427 ]
EAL: Detected 24 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
app.c: 873:spdk_env_unlock: *NOTICE*: unlock file successfully:/var/run/hugepages_dpdk_lock.app.c: 944:spdk_app_start: *NOTICE*: Total cores available: 2
app.c: 764:spdk_memory_base_init: *NOTICE*: get hugepage iovcnt 0, shm_id 0xffffffff
reactor.c: 305:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
reactor.c: 305:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
bdev_iscsi.c: 635:iscsi_readcapacity16_cb: *ERROR*: iSCSI error: SENSE KEY:ILLEGAL_REQUEST(5) ASCQ:LOGICAL_UNIT_NOT_SUPPORTED(0x2500)
sdi_ep.c: 283:spdk_sdi_init: *NOTICE*: dma channel info: use [0, 3), boot vhost false
sdi_dma.c:  63:spdk_sdi_set_dma_channel_info: *NOTICE*: set total dma channel: 3
sdi_ep.c: 299:spdk_sdi_init: *NOTICE*: get sdi 1620 controller!
hi1620/sdi_1620_dma.c: 995:sdi_1620_dma_init: *NOTICE*: channel 0 alloc sq/cq mem, sq phy:0x25f6600000, virt:0x200076600000, cq phy:0x25f6c00000, virt:0x200076c00000
hi1620/sdi_1620_dma.c: 995:sdi_1620_dma_init: *NOTICE*: channel 1 alloc sq/cq mem, sq phy:0x25f6800000, virt:0x200076800000, cq phy:0x25f6d00000, virt:0x200076d00000
hi1620/sdi_1620_dma.c: 995:sdi_1620_dma_init: *NOTICE*: channel 2 alloc sq/cq mem, sq phy:0x25f6a00000, virt:0x200076a00000, cq phy:0x25f6e00000, virt:0x200076e00000
hi1620/sdi_1620_dma.c:1006:sdi_1620_dma_init: *NOTICE*: dma hardware init done
VHOST_CONFIG: vhost-user server: socket created, fd: 20
VHOST_CONFIG: bind to /root/vhost.0
sdi_ep.c: 421:spdk_sdi_write_sockpath: *NOTICE*: write /root/vhost.0 to /sys/kernel/config/sdi_ep/functions/sdi_virtio_scsi/PF2/usockpath
sdi_ep.c: 396:spdk_sdi_write_file: *NOTICE*: write 1 to /sys/kernel/config/sdi_ep/functions/sdi_virtio_scsi/PF2/operation
dev.c: 130:spdk_scsi_dev_add_lun: *ERROR*: device TGT 0: cannot find bdev 'iSCSI0' (target 0)
sdi_scsi.c:3044:spdk_sdi_scsi_dev_add_tgt: *ERROR*: Couldn't create spdk SCSI target 'TGT 0' using bdev 'iSCSI0' in controller: vhost.0
sdi_scsi.c:3152:spdk_sdi_scsi_controller_construct: *WARNING*: vhost.0: add Target0 failed!
**bdev_iscsi.c: 635:iscsi_readcapacity16_cb: *ERROR*: iSCSI error: SENSE KEY:ILLEGAL_REQUEST(5) ASCQ:LOGICAL_UNIT_NOT_SUPPORTED(0x2500)**

file: vhost.conf
[Global]
ReactorMask 0x30

[iSCSI_Initiator]
URL iscsi://172.28.32.24:3260/iqn.2006-08.com.huawei:oceanstor:2100f86eee5d0531::20000:172.28.32.24/1 iSCSI0
[SdiScsi0]
Name vhost.0
PF 2
VF -1
Queues 12
Target 0 iSCSI0
[SDI]
StartChannel 0
TotalChannel 3

**Comment by Pangzhihong** [comment]
> @Pangzhihong this issue is related with your third party storage array, that the READ CAPACITY 16 command isn't supported. You can change SPDK iscsi bdev module to send READ CAPACITY 10 as a workaround.

but the previous error is still reported when Read Capacity 10 is used.

**Comment by jimharris** [comment]
Hi @Pangzhihong,

Note - it looks like you're using an old version of SPDK, since it is still using the INI conf file format (instead of JSON-RPC).  But I think I might still see the problem:

```
[iSCSI_Initiator]
URL iscsi://172.28.32.24:3260/iqn.2006-08.com.huawei:oceanstor:2100f86eee5d0531::20000:172.28.32.24/1 iSCSI0
```

I believe the /1 at the end of the URL specifies the LUN ID.  Can you confirm that you've configured the target with a LUN 1 on this target node?  If you only configured a LUN 0, then it would explain the issue you are seeing.  You could then either use /0 at the end of the URL in your conf file, or configure LUN 1 on the target node.

Regards,

Jim

**Comment by jimharris** [comment]
It looks like v19.01.1 had a lot of bugs around lun handling, which have since been fixed.  For example, see line 670 - the second argument should be req->lun, not 0.  You'll want to look for similar cases in other libiscsi calls in this file.

**Comment by Pangzhihong** [comment]
> It looks like v19.01.1 had a lot of bugs around lun handling, which have since been fixed. For example, see line 670 - the second argument should be req->lun, not 0. You'll want to look for similar cases in other libiscsi calls in this file.

Thank you, I did see the problem with this parameter 0, so I'll try to fix it including other libiscsi calls in this file.
