### ISSUE TITLE
[NVMf/vfio-user] cannot fail to abort command

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2194]
I'm looking at the abort behavior in NVMf/vfio-user. I'm using a custom bdev device (it's super simple) and I'm trying to simulate a scenario where the guest needs to abort a command. Specifically I'm deliberately not completing write commands at all so after 30 seconds the guest driver sends an abort command. My plan is to always complete abort requests without aborting the command in question (set bit 0 of Dword0 to '1'). When I do that (via `spdk_bdev_io_complete_nvme_status`), I see the following in `nvmf_bdev_ctrlr_complete_abort_cmd`:
```
        if (success) {
                req->rsp->nvme_cpl.cdw0 &= ~1U;
        }
```
Which means that NVMf doesn't allow the abort to fail in aborting the command. Is there a reason for this? I comment out this line and then retest. Here's the write command:
```
[2021-10-11 10:47:38.713164] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:0 nsid:1 lba:0 len:8 PRP1 0x124cae000 PRP2 0x0
```
After 30 seconds the guest drier tries to abort the write command:
```
[  126.053704] nvme nvme0: I/O 0 QID 2 timeout, aborting
[  126.054151] nvme nvme0: Abort status: 0x0
```
I immediately complete the abort with cdw0 set to 1 (aborting the command in question failed):
```
[2021-10-11 10:48:09.022953] nvme_qpair.c: 249:nvme_admin_qpair_print_command: *NOTICE*: ABORT (08) qid:0 cid:2 nsid:0 cdw10:00000002 cdw11:00000000
[2021-10-11 10:48:09.023140] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: SUCCESS (00/00) qid:0 cid:2 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
```
The guest driver however doesn't seem to take notice:
```
[  156.774511] nvme nvme0: I/O 0 QID 2 timeout, reset controller
Even worse, the guest driver now thinks that the abort command is stuck and proceeds with resetting the controller:
[  218.215053] nvme nvme0: I/O 9 QID 0 timeout, reset controller
```
While trying to reset the controller it complains with:
```
[  218.337032] nvme nvme0: Could not set queue count (12)
[  218.337088] nvme nvme0: IO queues not created
```
Possibly the following is relevant?
```
[2021-10-11 10:49:41.304406] nvme_qpair.c: 239:nvme_admin_qpair_print_command: *NOTICE*: SET FEATURES NUMBER OF QUEUES cid:28 cdw10:00000007 PRP1 0x0 PRP2 0x0
[2021-10-11 10:49:41.304435] ctrlr.c:1767:nvmf_ctrlr_set_features_number_of_queues: *DEBUG*: Set Features - Number of Queues, cdw11 0xef00ef
[2021-10-11 10:49:41.304444] ctrlr.c:1773:nvmf_ctrlr_set_features_number_of_queues: *DEBUG*: Queue pairs already active!
[2021-10-11 10:49:41.304450] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: COMMAND SEQUENCE ERROR (00/0c) qid:0 cid:28 cdw0:0 sqhd:0000 p:0 m:0 dnr:0
[2021-10-11 10:49:41.304474] vfio_user.c:1324:post_completion: *DEBUG*: /var/tmp/vfio-user//9919f1c8-e19b-4625-a1fe-85144cbb1c8e/nvme/9919f1c8-e19b-4625-a1fe-85144cbb1c8e: request complete SQ0 cid=28 status=0xc SQ head=0x2 CQ tail=0x1
```
The controller then goes bust:
```
[  218.338430] block nvme0n1: no available path - failing I/O
[  218.338440] Buffer I/O error on dev nvme0n1, logical block 0, async page read
[  218.338475] block nvme0n1: no available path - failing I/O
[  218.338476] Buffer I/O error on dev nvme0n1, logical block 1, async page read
[  218.338534] block nvme0n1: no available path - failing I/O
[  218.338535] Buffer I/O error on dev nvme0n1, logical block 2, async page read
[  218.338563] block nvme0n1: no available path - failing I/O
[  218.338564] Buffer I/O error on dev nvme0n1, logical block 3, async page read
[  218.338591] block nvme0n1: no available path - failing I/O
[  218.338592] Buffer I/O error on dev nvme0n1, logical block 4, async page read
[  218.338618] block nvme0n1: no available path - failing I/O
[  218.338619] Buffer I/O error on dev nvme0n1, logical block 5, async page read
[  218.338646] block nvme0n1: no available path - failing I/O
[  218.338646] Buffer I/O error on dev nvme0n1, logical block 6, async page read
[  218.338673] block nvme0n1: no available path - failing I/O
[  218.338674] Buffer I/O error on dev nvme0n1, logical block 7, async page read
[  218.338706] block nvme0n1: no available path - failing I/O
[  218.338707] Buffer I/O error on dev nvme0n1, logical block 0, async page read
[  218.338734] block nvme0n1: no available path - failing I/O
[  218.338735] Buffer I/O error on dev nvme0n1, logical block 1, async page read
[  218.338821] ldm_validate_partition_table(): Disk read failed.
[  218.338848] Dev nvme0n1: unable to read RDB block 0
[  218.338922]  nvme0n1: unable to read partition table
```
So there are many issues here:
1. Why does `nvmf_bdev_ctrlr_complete_abort_cmd` ignore whether abort failed?
2. Why does the guest driver ignore the abort completion?
3. Why does the guest driver fail to reset the controller?

**Comment by changpe1** [comment]
@tmakatos similar with live migration, for reset callback, SPDK still needs the asynchronous API, I can add the support to delete all the IO queues in the reset callback for now.

**Comment by changpe1** [comment]
For the controller reset failure issue inside the VM, because when CC.EN is set to 0, SPDK will disconnect all the IO queues, since there is one request didn't return from backend, so SPDK will not free that IO queue, but SPDK do set the RDY to 1, because SPDK just calls `spdk_nvmf_qpair_disconnect` but doesn't wait for its completion. @jlevon also mentioned this in Slack.

**Comment by tmakatos** [comment]
@changpe1 so what happens if the request never completes? Shouldn't NVMf/vfio-user handle this case?

**Comment by jlevon** [comment]
I agree with thanos that nvmf should attempt to abort commands on a reset...

**Comment by changpe1** [comment]
I proposed a fix patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9909
