### ISSUE TITLE
[nvmf-tcp-uring-vg-autotest] Build timed out (after 15 minutes)

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2198]
# CI Intermittent Failure

nvmf-tcp-uring-vg-autotest job is packed to the brim, slight differences in execution time causes it to go over the 15 minute limit.

Parts of this job need to be re-evaluated across other jobs. By finding the longest parts of the tests https://ci.spdk.io/results/autotest-per-patch/builds/60157/archive/nvmf-tcp-uring-vg-autotest/timing.svg and comparing to duplicates across jobs https://ci.spdk.io/results/autotest-per-patch/builds/60157/archive/post_process/completions_table_by_agent.html.

The autotest.sh part takes around 12-13 minutes, while job start up takes 2-3 minutes (repo clone, VM start up, etc). This would be another optimization to be made, either shorten the job start up and/or remove that time from the 15 minute job limit.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_60157.html

## Execution failed at

```
00:15:22.687  + echo 'End stage autorun'
00:15:22.687  End stage autorun
00:15:22.688  + vagrant destroy -f
00:15:27.355  Build timed out (after 15 minutes). Marking the build as failed.
00:15:27.362  Build was aborted
00:15:27.364  [PostBuildScript] - [INFO] Executing post build scripts.
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_60157.html

**Comment by mikeBashStuff** [comment]
@tomzawadzki will try to take a stab at it, thanks for all the feedback.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_60390.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61572.html

**Comment by mikeBashStuff** [comment]
Patches addressing this issue had been already merged - execution time of the job in question dropped about ~5min (e.g. https://ci.spdk.io/public_build/autotest-per-patch_61859.html). Closing.
