### ISSUE TITLE
[nvme_fio] LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2202]
# CI Intermittent Failure

During nvme-vg-autotest, nvme_fio test LeakSanitizer reported memory leaks. 

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_60389.html

## Execution failed at

`Run status group 0 (all jobs):
00:06:47.660     READ: bw=79.5MiB/s (83.4MB/s), 79.5MiB/s-79.5MiB/s (83.4MB/s-83.4MB/s), io=159MiB (167MB), run=2001-2001msec
00:06:47.660    WRITE: bw=79.3MiB/s (83.2MB/s), 79.3MiB/s-79.3MiB/s (83.2MB/s-83.2MB/s), io=159MiB (166MB), run=2001-2001msec
00:06:47.890  
00:06:47.890  =================================================================
00:06:47.890  ==72541==ERROR: LeakSanitizer: detected memory leaks
00:06:47.891  
00:06:47.891  Direct leak of 8 byte(s) in 1 object(s) allocated from:
00:06:47.891      #0 0x7f664c630b57 in operator new(unsigned long) (/usr/lib64/libasan.so.6+0xacb57)
00:06:47.891      #1 0x7f664c329643  (/usr/lib64/libtcmalloc_minimal.so.4+0xe643)
00:06:47.891  
00:06:47.891  -----------------------------------------------------
00:06:47.891  Suppressions used:
00:06:47.891    count      bytes template
00:06:47.891        2         38 /usr/src/fio/parse.c
00:06:47.891  -----------------------------------------------------
00:06:47.891  
00:06:47.891  SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
00:06:47.903    08:16:15	-- common/autotest_common.sh@1187 -- # trap - ERR
00:06:47.903    08:16:15	-- common/autotest_common.sh@1187 -- # print_backtrace
00:06:47.903    08:16:15	-- common/autotest_common.sh@988 -- # [[ ehxBET =~ e ]]
00:06:47.903    08:16:15	-- common/autotest_common.sh@990 -- # args=("${BASH_ARGV[@]}")
00:06:47.903    08:16:15	-- common/autotest_common.sh@990 -- # local args
00:06:47.904    08:16:15	-- common/autotest_common.sh@992 -- # xtrace_disable
00:06:47.904    08:16:15	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:06:47.904    08:16:15	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:06:47.904    08:16:15	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:06:47.904    08:16:15	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:06:47.904    08:16:15	-- common/autotest_common.sh@19 -- # set +x
00:06:47.904  ========== Backtrace start: ==========
00:06:47.904  
00:06:47.917  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1187 -> fio_nvme(["/home/vagrant/spdk_repo/spdk/examples/nvme/fio_plugin/example_config.fio"],["--filename=trtype=PCIe traddr=0000.00.06.0"],["--bs=4096"])
00:06:47.917       ...
00:06:47.917     1182		local nvme_plugin="$rootdir/build/fio/spdk_nvme"
00:06:47.917     1183	
00:06:47.917     1184		# Preload AddressSanitizer library to fio if fio_plugin was compiled with it
00:06:47.917     1185		asan_lib=$(ldd $nvme_plugin | grep libasan | awk '{print $3}')
00:06:47.917     1186	
00:06:47.917     1187		LD_PRELOAD="$asan_lib $nvme_plugin" "$fio_dir"/fio "$@"
00:06:47.917     1188	}
00:06:47.917     1189	
00:06:47.917     1190	function get_lvs_free_mb() {
00:06:47.917     1191		local lvs_uuid=$1
00:06:47.917     1192		local lvs_info
00:06:47.917       ...
00:06:47.928  in test/nvme/nvme.sh:38 -> nvme_fio_test([])
00:06:47.928       ...
00:06:47.928     33  			if $SPDK_EXAMPLE_DIR/identify -r "trtype:PCIe traddr:${bdf}" | grep -q "Extended Data LBA"; then
00:06:47.928     34  				bs=4160
00:06:47.928     35  			else
00:06:47.928     36  				bs=4096
00:06:47.928     37  			fi
00:06:47.928  => 38  			fio_nvme $PLUGIN_DIR/example_config.fio --filename="trtype=PCIe traddr=${bdf//:/.}" --bs="$bs"
00:06:47.928     39  			ran_fio=true
00:06:47.928     40  		done
00:06:47.928     41  		$ran_fio || (echo "No valid NVMe drive found. Failing test." && false)
00:06:47.928     42  	}
00:06:47.928     43  	
00:06:47.928       ...
00:06:47.938  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:960 -> run_test(["nvme_fio"],["nvme_fio_test"])
00:06:47.938       ...
00:06:47.938     955 		timing_enter $test_name
00:06:47.938     956 		echo "************************************"
00:06:47.938     957 		echo "START TEST $test_name"
00:06:47.938     958 		echo "************************************"
00:06:47.938     959 		xtrace_restore
00:06:47.938  => 960 		time "$@"
00:06:47.938     961 		xtrace_disable
00:06:47.938     962 		echo "************************************"
00:06:47.938     963 		echo "END TEST $test_name"
00:06:47.938     964 		echo "************************************"
00:06:47.938     965 		timing_exit $test_name
00:06:47.938       ...
00:06:47.949  in test/nvme/nvme.sh:136 -> main([])
00:06:47.949       ...
00:06:47.949     131 		trap - SIGINT SIGTERM EXIT
00:06:47.949     132 		kill_stub
00:06:47.949     133 	fi
00:06:47.949     134 	
00:06:47.949     135 	if [[ $CONFIG_FIO_PLUGIN == y ]]; then
00:06:47.949  => 136 		run_test "nvme_fio" nvme_fio_test
00:06:47.949     137 	fi
00:06:47.950       ...
00:06:47.950  
00:06:47.950  ========== Backtrace end ==========`

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_60389.html

**Comment by KKaras169169** [comment]
Duplicate of  [#2192](https://github.com/spdk/spdk/issues/2192)
