### ISSUE TITLE
[nvme_hotplug] Huge log files of INVALID NAMESPACE OR FORMAT generated

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2207]
https://ci.spdk.io/public_build/autotest-per-patch_60773.html shows the problem, but the failure there does not seem to be related to these huge log files.

We see the following when running the nvme_hotplug test.  The logs are HUGE and make it difficult to get to the actual failure at the end of the log.

00:05:42.825   22:16:01	-- nvme/hotplug.sh@16 -- # local hotplug_wait=6
00:05:42.825   22:16:01	-- nvme/hotplug.sh@52 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/build/examples/hotplug -i 0 -t 24 -n 3 -r 3
00:05:42.825   22:16:01	-- nvme/hotplug.sh@17 -- # local dev
00:05:42.825   22:16:01	-- nvme/hotplug.sh@23 -- # sleep 6
00:05:42.832  [2021-10-20 22:16:01.253906] Starting SPDK v21.10-pre git sha1 e1449a54a / DPDK 21.08.0 initialization...
00:05:42.832  [2021-10-20 22:16:01.253968] [ DPDK EAL parameters: [2021-10-20 22:16:01.253976] hotplug [2021-10-20 22:16:01.253982] -c 0x1 [2021-10-20 22:16:01.253987] --log-level=lib.eal:6 [2021-10-20 22:16:01.253992] --log-level=lib.cryptodev:5 [2021-10-20 22:16:01.253997] --log-level=user1:6 [2021-10-20 22:16:01.254002] --base-virtaddr=0x200000000000 [2021-10-20 22:16:01.254008] --match-allocations [2021-10-20 22:16:01.254013] --file-prefix=spdk0 [2021-10-20 22:16:01.254018] --proc-type=auto [2021-10-20 22:16:01.254023] ]
00:05:42.856  EAL: No available 1048576 kB hugepages reported
00:05:42.859  TELEMETRY: No legacy callbacks, legacy socket not created
00:05:42.885  Initializing NVMe Controllers
00:05:43.216  Attaching to 0000:65:00.0
00:05:43.227  Attached to 0000:65:00.0
00:05:43.228  Initialization complete. Starting I/O...
00:05:43.228  [2021-10-20 22:16:01.650318] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:895 nsid:1 lba:0 len:8 PRP1 0x200000266e00 PRP2 0x200000267000
00:05:43.229  [2021-10-20 22:16:01.650355] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:895 cdw0:0 sqhd:0001 p:1 m:0 dnr:1
00:05:43.229  [2021-10-20 22:16:01.650376] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:894 nsid:1 lba:8 len:8 PRP1 0x200000265c00 PRP2 0x200000266000
00:05:43.229  [2021-10-20 22:16:01.650389] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:894 cdw0:0 sqhd:0002 p:1 m:0 dnr:1
00:05:43.229  [2021-10-20 22:16:01.650405] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:893 nsid:1 lba:16 len:8 PRP1 0x200000264a00 PRP2 0x200000265000
00:05:43.230  [2021-10-20 22:16:01.650415] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:893 cdw0:0 sqhd:0003 p:1 m:0 dnr:1
00:05:43.230  [2021-10-20 22:16:01.650429] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:892 nsid:1 lba:24 len:8 PRP1 0x200000263800 PRP2 0x200000264000
00:05:43.230  [2021-10-20 22:16:01.650439] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:892 cdw0:0 sqhd:0004 p:1 m:0 dnr:1
00:05:43.230  [2021-10-20 22:16:01.650458] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:891 nsid:1 lba:32 len:8 PRP1 0x200000266e00 PRP2 0x200000267000
00:05:43.230  [2021-10-20 22:16:01.650471] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:891 cdw0:0 sqhd:0005 p:1 m:0 dnr:1
00:05:43.230  [2021-10-20 22:16:01.650488] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:895 nsid:1 lba:40 len:8 PRP1 0x200000265c00 PRP2 0x200000266000
00:05:43.230  [2021-10-20 22:16:01.650498] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:895 cdw0:0 sqhd:0006 p:1 m:0 dnr:1
00:05:43.230  [2021-10-20 22:16:01.650513] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:894 nsid:1 lba:48 len:8 PRP1 0x200000264a00 PRP2 0x200000265000
00:05:43.231  [2021-10-20 22:16:01.650526] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:894 cdw0:0 sqhd:0007 p:1 m:0 dnr:1
00:05:43.231  [2021-10-20 22:16:01.650543] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:893 nsid:1 lba:56 len:8 PRP1 0x200000263800 PRP2 0x200000264000
00:05:43.231  [2021-10-20 22:16:01.650556] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:893 cdw0:0 sqhd:0008 p:1 m:0 dnr:1
00:05:43.231  [2021-10-20 22:16:01.650571] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:892 nsid:1 lba:64 len:8 PRP1 0x200000266e00 PRP2 0x200000267000
00:05:43.231  [2021-10-20 22:16:01.650582] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:892 cdw0:0 sqhd:0009 p:1 m:0 dnr:1
00:05:43.231  [2021-10-20 22:16:01.650600] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:891 nsid:1 lba:72 len:8 PRP1 0x200000265c00 PRP2 0x200000266000
00:05:43.231  [2021-10-20 22:16:01.650610] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:891 cdw0:0 sqhd:000a p:1 m:0 dnr:1
00:05:43.231  [2021-10-20 22:16:01.650624] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:895 nsid:1 lba:80 len:8 PRP1 0x200000264a00 PRP2 0x200000265000
00:05:43.231  [2021-10-20 22:16:01.650633] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:895 cdw0:0 sqhd:000b p:1 m:0 dnr:1
00:05:43.231  [2021-10-20 22:16:01.650647] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:894 nsid:1 lba:88 len:8 PRP1 0x200000263800 PRP2 0x200000264000
00:05:43.231  [2021-10-20 22:16:01.650656] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:894 cdw0:0 sqhd:000c p:1 m:0 dnr:1
00:05:43.231  [2021-10-20 22:16:01.650675] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:893 nsid:1 lba:96 len:8 PRP1 0x200000266e00 PRP2 0x200000267000
00:05:43.232  [2021-10-20 22:16:01.650688] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:893 cdw0:0 sqhd:000d p:1 m:0 dnr:1
00:05:43.232  [2021-10-20 22:16:01.650705] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:892 nsid:1 lba:104 len:8 PRP1 0x200000265c00 PRP2 0x200000266000
00:05:43.232  [2021-10-20 22:16:01.650717] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:892 cdw0:0 sqhd:000e p:1 m:0 dnr:1
00:05:43.232  [2021-10-20 22:16:01.650732] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:891 nsid:1 lba:112 len:8 PRP1 0x200000264a00 PRP2 0x200000265000
00:05:43.232  [2021-10-20 22:16:01.650741] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:891 cdw0:0 sqhd:000f p:1 m:0 dnr:1
00:05:43.232  [2021-10-20 22:16:01.650755] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:895 nsid:1 lba:120 len:8 PRP1 0x200000263800 PRP2 0x200000264000
00:05:43.232  [2021-10-20 22:16:01.650767] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:895 cdw0:0 sqhd:0010 p:1 m:0 dnr:1
00:05:43.232  [2021-10-20 22:16:01.650785] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:894 nsid:1 lba:128 len:8 PRP1 0x200000266e00 PRP2 0x200000267000
00:05:43.232  [2021-10-20 22:16:01.650797] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:894 cdw0:0 sqhd:0011 p:1 m:0 dnr:1
00:05:43.232  [2021-10-20 22:16:01.650815] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:893 nsid:1 lba:136 len:8 PRP1 0x200000265c00 PRP2 0x200000266000
00:05:43.232  [2021-10-20 22:16:01.650825] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:893 cdw0:0 sqhd:0012 p:1 m:0 dnr:1
00:05:43.233  [2021-10-20 22:16:01.650848] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:892 nsid:1 lba:144 len:8 PRP1 0x200000264a00 PRP2 0x200000265000
00:05:43.233  [2021-10-20 22:16:01.650859] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:892 cdw0:0 sqhd:0013 p:1 m:0 dnr:1
00:05:43.233  [2021-10-20 22:16:01.650877] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:891 nsid:1 lba:152 len:8 PRP1 0x200000263800 PRP2 0x200000264000
00:05:43.233  [2021-10-20 22:16:01.650887] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:891 cdw0:0 sqhd:0014 p:1 m:0 dnr:1
00:05:43.233  [2021-10-20 22:16:01.650904] nvme_qpair.c: 269:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:895 nsid:1 lba:160 len:8 PRP1 0x200000266e00 PRP2 0x200000267000
00:05:43.233  [2021-10-20 22:16:01.650915] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) qid:1 cid:895 cdw0:0 sqhd:0015 p:1 m:0 dnr:1
00:0

**Comment by jimharris** [comment]
I think it's possible this has something to do with issue #1456.  I mentioned above that these logs aren't the cause of the actual failure, but the eventual failure is exactly what is described in #1456.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_60779.html

**Comment by jimharris** [comment]
Issue hasn't been seen in almost a year.
