### ISSUE TITLE
about the parameter of  rpc command: iscsi_create_initiator_group

### ISSUE THREAD

**Issue by ghnicky** [spdk/spdk#2209]
1. the help for the parameter 'initiator_list'  is as the following:
 p.add_argument('initiator_list', help="""Whitespace-separated list of initiator hostnames or IP addresses,
    enclosed in quotes.  Example: 'ANY' or '127.0.0.1 192.168.200.100'""")

but  the code seems to only support iqn or 'ANY' instead of ip or hostname.

could you please give some advice?

**Comment by Comphix** [comment]
For initiator hostname, you may refer below link (SPDK UT) as example:

https://github.com/spdk/spdk/blob/66f7c55ed503365eeb601fcf3e2824ba64c5a248/test/unit/lib/iscsi/iscsi.c/iscsi_ut.c

#define UT_INITIATOR_NAME1	"iqn.2017-11.spdk.io:i0001"
#define UT_INITIATOR_NAME2	"iqn.2017-11.spdk.io:i0002"

**Comment by shuhei-matsumoto** [comment]
Hi @ghnicky 

Your confusion is very reasonable.
The following patch is helpful for you?
https://review.spdk.io/gerrit/c/spdk/spdk/+/10236

Besides, the following information may be for my learning :)

For Linux iSCSI initiator, IQN is in /etc/iscsi/initiatorname.iscsi. In my Linux, it is InitiatorName=iqn.1994-05.com.redhat:50e992c3873f. We can change it to any preferred value.

Besides, if we use iSCSI bdev and create it, we can specify its IQN via the RPC bdev_iscsi_create.

These initiator's IQN is passed as InitiatorName to the SPDK iSCSI target in the login processing.

**Comment by tomzawadzki** [comment]
Hi @ghnicky clarification for the RPC is now merged. Do you think this answers the original question in this issue ?

**Comment by jimharris** [comment]
Closing issue - @ghnicky please feel free to reopen if the merged patch does not provide adequate help in your opinion.  Thanks.
