### ISSUE TITLE
Submit AER command when disconnecting by host will incur wrong pending IO.

### ISSUE THREAD

**Issue by sejun000** [spdk/spdk#2215]
# Bug report

Each qpair group has pending io for each subsystem.
For admin commands, spdk uses "mgmt_io_outstanding"
When disconnect by host is incurred (usually, linux nvmf driver triggers disconnect with target when timeout happened), 
this pending count (mgmt_io_outstanding) can be wrong.
So, next time, subsystem pause and resuming by rpc (for, example, bdev is attached to a subsystem)

(Solution is also developed with Seungyeon Shin)

## Expected Behavior

mgmt_io_outstanding should be successfully to 0 when idle.

## Current Behavior

mgmt_io_outstanding cannot become to 0 even if idle.

That is because AER command does not decrease their count.
AER command will decrease mgmt_io_outstanding in nvmf_ctrlr_async_event_request.
But before that function is called, there are several early return routine.

## Possible Solution

In below 3 cases, we saw third case (cc.en != 1).
From nvme base spec, if cc.en is not 1, host should not issue the command.
but cc.en and admin command can be asynchronously processed.
So, command can be already come in even if cc.en = 0.
We need handling this cases as decreasing count if op code of request is AER command.

```
diff --git a/lib/nvmf/ctrlr.c b/lib/nvmf/ctrlr.c
index 154a1b2..fd581ee 100644
--- a/lib/nvmf/ctrlr.c
+++ b/lib/nvmf/ctrlr.c
@@ -3080,7 +3080,13 @@ nvmf_ctrlr_process_admin_cmd(struct spdk_nvmf_request *req)
        struct spdk_nvme_cpl *response = &req->rsp->nvme_cpl;
        int rc;

+       struct spdk_nvmf_subsystem_poll_group *sgroup;
+       sgroup = &req->qpair->group->sgroups[ctrlr->subsys->id];
        if (ctrlr == NULL) {
+               if (cmd->opc == SPDK_NVME_OPC_ASYNC_EVENT_REQUEST)
+                {
+                       sgroup->mgmt_io_outstanding--;
+                }
                SPDK_ERRLOG("Admin command sent before CONNECT\n");
                response->status.sct = SPDK_NVME_SCT_GENERIC;
                response->status.sc = SPDK_NVME_SC_COMMAND_SEQUENCE_ERROR;
@@ -3089,6 +3095,10 @@ nvmf_ctrlr_process_admin_cmd(struct spdk_nvmf_request *req)

        if (cmd->fuse != 0) {
                /* Fused admin commands are not supported. */
+               if (cmd->opc == SPDK_NVME_OPC_ASYNC_EVENT_REQUEST)
+                {
+                       sgroup->mgmt_io_outstanding--;
+                }
                response->status.sct = SPDK_NVME_SCT_GENERIC;
                response->status.sc = SPDK_NVME_SC_INVALID_FIELD;
                return SPDK_NVMF_REQUEST_EXEC_STATUS_COMPLETE;
@@ -3096,6 +3106,10 @@ nvmf_ctrlr_process_admin_cmd(struct spdk_nvmf_request *req)

        if (ctrlr->vcprop.cc.bits.en != 1) {
                SPDK_ERRLOG("Admin command sent to disabled controller\n");
+               if (cmd->opc == SPDK_NVME_OPC_ASYNC_EVENT_REQUEST)
+                {
+                       sgroup->mgmt_io_outstanding--;
+                }
                response->status.sct = SPDK_NVME_SCT_GENERIC;
                response->status.sc = SPDK_NVME_SC_COMMAND_SEQUENCE_ERROR;
                return SPDK_NVMF_REQUEST_EXEC_STATUS_COMPLETE;

```

## Steps to Reproduce

1. intermittent issues when timeout happened when nvme SSD is slow if we utilize "nvmf_tgt".
2.  If you just inject function which sleep several seconds periodically, you can see intermittently

## Context (Environment including OS version, SPDK version, etc.)

1. Initiator, target : 5.3.18 linux kernel. ubuntu 18.04
2. spdk 21.04. but I think the code in master has same issues. 

``

**Comment by jimharris** [comment]
I've posted an alternate fix for the issue described here:  https://review.spdk.io/gerrit/c/spdk/spdk/+/13678.

**Comment by tomzawadzki** [comment]
Closing the issue since the patch fixing it has been merged https://review.spdk.io/gerrit/c/spdk/spdk/+/13678.
