### ISSUE TITLE
vfio-user target does not fail OPC_FABRICS commands

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2218]
vfio-user uses the nvme fabrics (nvmf) target library, but is not actually a fabrics controller.  So it needs to fail commands with OPC_FABRICS opcode.

Ideally we can handle this generically in the nvmf library rather than doing it per-transport.  We should be able to look at the trtype of the transport, similar to spdk_nvme_ctrlr_is_fabrics().

**Comment by changpe1** [comment]
Fix patch and test case patch are merged, closing it for now.
