### ISSUE TITLE
call path from spdk_bdev_close() to spdk_bdev_unregister()

### ISSUE THREAD

**Issue by youngtack** [spdk/spdk#222]
Hi SPDK team,

As I walked through bdev layer, `spdk_bdev_unregister()` only can set its status as `REMOVING` but `spdk_bdev_close()` will never call `spdk_bdev_unregister()` since its status is not `REMOVING`.

Here, I'm wondering status comparison in `spdk_bdev_close()` should be as this below.
`if (bdev->status != SPDK_BDEV_STATUS_REMOVING && TAILQ_EMPTY(&bdev->open_descs)) {`

Please let me know any other call path between `spdk_bdev_close()` and `spdk_bdev_unregister()` if any.

```
void
spdk_bdev_close(struct spdk_bdev_desc *desc)
{
	struct spdk_bdev *bdev = desc->bdev;
	bool do_unregister = false;

	pthread_mutex_lock(&bdev->mutex);

	TAILQ_REMOVE(&bdev->open_descs, desc, link);
	free(desc);

	if (bdev->status == SPDK_BDEV_STATUS_REMOVING && TAILQ_EMPTY(&bdev->open_descs)) {
		do_unregister = true;
	}
	pthread_mutex_unlock(&bdev->mutex);

	if (do_unregister == true) {
		spdk_bdev_unregister(bdev, bdev->unregister_cb, bdev->unregister_ctx);
	}
}
void
spdk_bdev_unregister(struct spdk_bdev *bdev, spdk_bdev_unregister_cb cb_fn, void *cb_arg)
{
	struct spdk_bdev_desc	*desc, *tmp;
	int			rc;
	bool			do_destruct = true;

	SPDK_DEBUGLOG(SPDK_TRACE_BDEV, "Removing bdev %s from list\n", bdev->name);

	pthread_mutex_lock(&bdev->mutex);

	bdev->status = SPDK_BDEV_STATUS_REMOVING;
```

Thanks,
YT (Young Tack)

**Comment by jimharris** [comment]
Hi YT,

Please feel free in the future to send questions like this to the SPDK mailing list – you can sign up here:

https://lists.01.org/mailman/listinfo/spdk

Closing a bdev only means that an upper layer protocol (i.e. iSCSI, NVMe-oF or vhost) no longer needs to send I/O to the bdev.  Think of it like POSIX close(fd) – this just means the application no longer needs to perform I/O on the fd – it does not remove the underlying device node.

spdk_bdev_unregister() is used when a block device is no longer available.  This could happen (for example) if an NVMe device was removed or a logical volume was deleted.  When this action occurs, if there are any open descriptors, anyone who has the bdev open gets a callback from the function pointer registered when they called spdk_bdev_open().  The bdev is not actually unregistered until all open descriptors are closed.

Then the code you have referenced below checks as open descriptors get closed – once the last descriptor is closed from a device in REMOVING state, we can retry the spdk_bdev_unregister() call to actually remove the bdev.

Hope this helps answer your questions.

Regards,

-Jim

**Comment by youngtack** [comment]
Hi James,

Appreciate your kind elaboration.
I have more question and will post it to SPDK mailing list with same title.

Thanks,
YT
