### ISSUE TITLE
add_io_qpair can access invalid pointer.

### ISSUE THREAD

**Issue by sejun000** [spdk/spdk#2220]
# Bug report

When disconnect by host is incurred (usually, linux nvmf driver triggers disconnect with target when timeout happened),
Host try to recover by delete io qpair and create new io qpair by issue connect command.
On the other hand, target can trigger keep alive timeout (nvmf_ctrlr_keep_alive_poll), which will destroy all qpairs and ctrlr.
Those two incident can happen simultaneously and asynchronously, so, add io qpair needs to handle the cases that ctrlr is already destroyed.  (When I traced 19.10 version and 21.04, I found that many fixes for these cases are commited)
We founded one more scenario. Existing implementation prevents spdk from accessing ctrlr structure. but, there are no guard  for admin qpair. Admin qpair is accessed in the same function and I think it has already destroyed, so it should be also protected. The patch I introduced here is for "ctrlr was not destructed yet, but admin qpair was already destroyed"

## Expected Behavior
_nvmf_ctrlr_add_io_qpair should return its function before code accesses admin qpair's memory.

## Current Behavior
_nvmf_ctrlr_add_io_qpair does not return its function before code accesses admin qpair's memory. Invalid access for admin qpair can happen.

## Possible Solution

```
diff --git a/lib/nvmf/ctrlr.c b/lib/nvmf/ctrlr.c
index 154a1b2..6393dea 100644
--- a/lib/nvmf/ctrlr.c
+++ b/lib/nvmf/ctrlr.c
@@ -518,6 +518,14 @@ nvmf_ctrlr_add_io_qpair(void *ctx)
        qpair->ctrlr = NULL;

        /* Make sure the controller is not being destroyed. */
+       /* if admin queue is destroyed, we handle same as ctrlr->in_destruct */
+       if (!spdk_bit_array_get(ctrlr->qpair_mask, 0)) {
+               SPDK_ERRLOG("Got I/O connect while admin qpair was being destroyed.\n");
+               SPDK_NVMF_INVALID_CONNECT_CMD(rsp, qid);
+               spdk_nvmf_request_complete(req);
+               return;
+       }
+
        if (ctrlr->in_destruct) {
                SPDK_ERRLOG("Got I/O connect while ctrlr was being destroyed.\n");
                SPDK_NVMF_INVALID_CONNECT_CMD(rsp, qid);
@@ -585,6 +593,16 @@ _nvmf_ctrlr_add_io_qpair(void *ctx)
        assert(subsystem != NULL);

        ctrlr = nvmf_subsystem_get_ctrlr(subsystem, data->cntlid);
+
+       /* Make sure the controller is not being destroyed. */
+       /* if admin queue is destroyed, we handle same as ctrlr->in_destruct */
+       if (!spdk_bit_array_get(ctrlr->qpair_mask, 0)) {
+               SPDK_ERRLOG("Got I/O connect while admin qpair was being destroyed.\n");
+               SPDK_NVMF_INVALID_CONNECT_CMD(rsp, qid);
+               spdk_nvmf_request_complete(req);
+               return;
+       }
+
        if (ctrlr == NULL) {
                SPDK_ERRLOG("Unknown controller ID 0x%x\n", data->cntlid);
                SPDK_NVMF_INVALID_CONNECT_DATA(rsp, cntlid);
~
```

## Steps to Reproduce

1. intermittent issues when timeout happened when nvme SSD is slow if we utilize "nvmf_tgt".
2. If you just inject function which sleep several seconds periodically, you can see intermittently

## Context (Environment including OS version, SPDK version, etc.)

1. Initiator, target : 5.3.18 linux kernel. ubuntu 18.04. Inspur PSD server
2. spdk 21.04. but I think the code in master has same issues.

**Comment by yidong0635** [comment]
@sejun000  the codes have changed a lot, Do you think this issue is still existed? @changpe1 @AlekseyMarchuk What do you think? #2055 was closed.

**Comment by changpe1** [comment]
Closing this issue now, you may reopen it if it still exists with latest code.
