### ISSUE TITLE
bdev_iscsi Error

### ISSUE THREAD

**Issue by Pangzhihong** [spdk/spdk#2221]
When I execute: **/root/spdk-19.01.1/scripts/rpc.py construct_iscsi_bdev -b iscsi3 -i iqn.2016-06.io.spdk:init --url iscsi://172.28.32.24:3260/iqn.2006-08.com.huawei:oceanstor:2100f86eee5d0531::20000:172.28.32.24/3**
The following error is reported when the Bdev is added.

bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed:
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: socket error Broken pipe(32).
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.
bdev_iscsi.c: 726:iscsi_bdev_conn_poll: *ERROR*: iscsi_service failed: iscsi_service: POLLHUP, socket error.

**Comment by changpe1** [comment]
Did you try with latest SPDK version?

**Comment by changpe1** [comment]
Closing this issue now, if this issue still happen with latest SPDK, you can reopen it.
