### ISSUE TITLE
nvme_cuse: memory corruption when cuse thread early-exits 

### ISSUE THREAD

**Issue by sydidelot** [spdk/spdk#2227]
# Bug report

There is a bad memory corruption where the code for nvme cuse attempts to write one byte (with value 0x1) after the memory is freed.

## Expected Behavior

I expect the SPDK not to corrupt memory :)

## Current Behavior

When the CUSE device is unregistered, the poller thread is signaled with
`fuse_session_exit()`, which writes the value 1 to `fuse_session::exited`.
The poller thread then detects with `fuse_session_exited()` that it must exit
the routing and finally destroys its own fuse session with `cuse_lowlevel_teardown()` 
before it exits.

However, FUSE may also call `fuse_session_exit()` for its internal purposes 
(you can grep for `fuse_session_exit()` in the source code for FUSE).
If the poller thread early-exits, it would destroy its own FUSE session
(and free the memory) before `fuse_session_exit()` gets executed, causing
the memory to be corrupted with a single byte of value 0x1.

## Possible Solution

The fix I suggest is to destroy the FUSE session with `cuse_lowlevel_teardown()` after the thread is joined.
The patch is already available for review: https://review.spdk.io/gerrit/c/spdk/spdk/+/9931

## Steps to Reproduce

I'm not sure exactly under what conditions the bug happens (and for what reasons FUSE would 
call `fuse_session_exit()`), but it seems to trigger when the NVMe device is closed and immediately 
reopened. I added some trace messages in my application and I could clearly see that the 
CUSE thread exits before it was requested to exit in `cuse_nvme_ns_stop()`.
Unfortunately, I cannot share my code because it's closed source.

The bug can be intercepted before the memory corruption happens 
if we set `cuse_device->session` to NULL after the call to `fuse_session_reset()`.
That would cause `cuse_nvme_ns_stop()` to crash with a segmentation
fault in `fuse_session_exit()` because it tries to access a NULL pointer.
```
static void *
cuse_thread(void *arg)
{
    [...]
    free(buf.mem);
    fuse_session_reset(cuse_device->session);
+    cuse_device->session = NULL;
    pthread_exit(NULL);
}
```

## Context (Environment including OS version, SPDK version, etc.)

Linux/Ubuntu 20.04, SPDK 21.07. I have reviewed the code for SPDK 21.10 and it is impacted by the same bug.

**Comment by sydidelot** [comment]
Hi @dong-liuliu. Here is the Github issue you requested for https://review.spdk.io/gerrit/c/spdk/spdk/+/9931

**Comment by tomzawadzki** [comment]
The patch is now merged, the issue can be closed. @sydidelot thank you !
