### ISSUE TITLE
A segmentation fault occurred when spdk_ioat_probe() is called

### ISSUE THREAD

**Issue by Lyhugo** [spdk/spdk#2229]
# Bug report

When I followed [https://www.intel.com/content/www/us/en/developer/articles/technical/fast-memcpy-using-spdk-and-ioat-dma-engine.html] to test memcpy，a segmentation fault occurred when spdk_ioat_probe() is called.
![1636167595(1)](https://user-images.githubusercontent.com/71816089/140595848-9996fb26-5801-4147-9874-c3dfa1dbe464.jpg)

When I use GDB for debugging, the program stopped in scan_pci_bus().
![1636167951(1)](https://user-images.githubusercontent.com/71816089/140595924-0d5ac2c5-a2e3-452e-a22a-2e919eb105e6.jpg)

When I run ./build/bin/spdk_lspci, the list of available PCI devices can be seen.
![image](https://user-images.githubusercontent.com/71816089/140596074-ddb4d0af-23b0-483f-b73e-987fb1f20cc3.png)

I have just recently started learning SPDK, so I'm not very familiar with it. Can someone tell me what the problem is?

## Context (Environment including OS version, SPDK version, etc.)

ubuntu1~16.04.12
SPDK v21.10

**Comment by Lyhugo** [comment]
ioat_perf can be run successfully as followed.
![image](https://user-images.githubusercontent.com/71816089/140603203-d4cca868-0eb7-4cbb-8181-0c22896311d0.png)

**Comment by jimharris** [comment]
Please post the source code for your test application.

**Comment by optimistyzy** [comment]
@Lyhugo This code you mentioned is not based on latest SPDK version.  You may try this branch:  https://review.spdk.io/gerrit/c/spdk/spdk/+/8443   (But it requires on gcc version or C++14 support). For further support, you can reach @Comphix  since I do not work on this anymore.

**Comment by Lyhugo** [comment]
> @Lyhugo This code you mentioned is not based on latest SPDK version. You may try this branch: https://review.spdk.io/gerrit/c/spdk/spdk/+/8443 (But it requires on gcc version or C++14 support). For further support, you can reach @Comphix since I do not work on this anymore.

It works fine when I refer to ioat_perf's source code to write test code. It seems the bug is indeed due to a version change. Thank you very much!

**Comment by Lyhugo** [comment]
> Please post the source code for your test application.

It works fine when I refer to ioat_perf's source code to write test code. It seems the bug is indeed due to a version change. Thank you very much!
