### ISSUE TITLE
Opal Not Supported on drives

### ISSUE THREAD

**Issue by adamagniv** [spdk/spdk#2230]
# Bug report

running fio (engine = spdk_bdev) I get the print:
```nvme_opal.c: 828:opal_discovery0_end: *ERROR*: Opal Not Supported.```
for each bdev in the spdk_json_conf I attach to.
After the print the IO runs ok.

## Possible Solution
SPDK should not assume that the security protocol the SSD supports is Opal.

## Context (Environment including OS version, SPDK version, etc.)
tested with SPDK 21.07
RDMA transport
```
$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
$ uname -r
3.10.0-957.el7.x86_64
```

**Comment by changpe1** [comment]
Yes, an error log isn't friendly to users. here is the fix https://review.spdk.io/gerrit/c/spdk/spdk/+/10139

**Comment by changpe1** [comment]
Patch has been merged, closing it now.
