### ISSUE TITLE
nvme drives not present on the target node (WFP15)

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2232]
https://ci.spdk.io/results/autotest-per-patch/builds/61605/archive/nvmf-phy-autotest/build.log

There are no nvme drives installed on the WFP15, removed it from the CI pool for now.

```
[root@spdk-WFP-15 ~]# grep 010802 /sys/bus/pci/devices/*/class
[root@spdk-WFP-15 ~]#
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_61605.html

**Comment by mikeBashStuff** [comment]
@karlatec @wawryk Would you kindly look into this? We need someone to do some lab work to verify if nvme drive was actually installed inside that box - from the system's perspective it looks like it's missing.

**Comment by wawryk** [comment]
Disk replaced and installed newest firmware on it.
Taken back online in CI.
Will close if no new occurrence in this week.

**Comment by mikeBashStuff** [comment]
@wawryk Now there are two nvme drives, but one of them (nvme0) doesn't have any active namespaces:

```
[root@spdk-WFP-15 ~]# grep  . /sys/class/nvme/nvme*/model
/sys/class/nvme/nvme0/model:INTEL SSDPE2KX010T8
/sys/class/nvme/nvme1/model:INTEL SSDPE2KE020T7
[root@spdk-WFP-15 ~]# readlink -f /sys/class/nvme/nvme*
/sys/devices/pci0000:5d/0000:5d:03.0/0000:5f:00.0/nvme/nvme0
/sys/devices/pci0000:d7/0000:d7:01.0/0000:d9:00.0/nvme/nvme1
[root@spdk-WFP-15 ~]# readlink -f /sys/class/nvme/nvme*/nvme*
# No ns devices for nvme0
/sys/devices/pci0000:d7/0000:d7:01.0/0000:d9:00.0/nvme/nvme1/nvme1n1
```

I can format an ns on that nvme0 manually but for some reason it cannot fit the whole drive. I think we had similar issue before and upgrading firmware did help back then - would you kindly look into bumping the firmware on the `/dev/nvme0` as well? 

The problem with this is that autotest fails early on in `nvme_namespace_revert()` when `nvme0` is picked up (as there are no namespaces available). Example here:

https://ci.spdk.io/results/autotest-per-patch/builds/62387/archive/nvmf-phy-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_62387.html

**Comment by wawryk** [comment]
`nvme list` show me only one disk, and I upgrade them.
Created namespace on second one, upgraded FW.

**Comment by tomzawadzki** [comment]
[bug scrub] WFP15 now hold all required hardware to run the tests. Reported issue no longer occurs.
