### ISSUE TITLE
bdev/nvme: canceled outstanding commands are completed twice

### ISSUE THREAD

**Issue by sydidelot** [spdk/spdk#2233]
# Bug report

We are hitting a bug where canceled bdev/nvme outstanding commands are completed twice:
```
[2021-11-03 11:32:45.002197] nvme_pcie_common.c: 708:nvme_pcie_qpair_abort_trackers: ERROR: aborting outstanding command
[2021-11-03 11:32:45.002294] nvme_qpair.c: 277:nvme_io_qpair_print_command: NOTICE: DATASET MANAGEMENT sqid:1 cid:895 nsid:1
[2021-11-03 11:32:45.002319] nvme_qpair.c: 453:spdk_nvme_print_completion: NOTICE: ABORTED - BY REQUEST (00/07) qid:1 cid:895 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
[2021-11-03 11:32:47.564094] nvme_pcie_common.c: 863:nvme_pcie_qpair_process_completions: ERROR: cpl does not map to outstanding cmd
[2021-11-03 11:32:47.564166] nvme_qpair.c: 453:spdk_nvme_print_completion: NOTICE: SUCCESS (00/00) qid:1 cid:895 cdw0:0 sqhd:0001 p:1 m:0 dnr:0
red: nvme_pcie_common.c:865: nvme_pcie_qpair_process_completions: Assertion `0' failed.
2021-11-03 11:32:47.577194 CRITC SIGNAL - Aborted
```

The bug is intermittent and happens only in specific environments where the bdev/nvme devices are very slow to complete initialization (it could be a bad device, right now I'm not sure exactly what is the trigger). 

In order to understand the context of the bug, you need to know that our application sets a timeout of 10 seconds with `spdk_bdev_set_timeout()` after `spdk_bdev_open_ext()` succeeds. The timeout callback is responsible of resetting the bdev device with `spdk_bdev_reset()`.

To my understanding, the very first completion event is the result of executing `nvme_qpair_check_enabled() (lib/nvme/nvme_qpair.c)` when the qp is transitioned to the state `NVME_QPAIR_ENABLING`. It appears that one command was queued before the device transitioned to `NVME_QPAIR_ENABLING` and aborted after it has moved to the CONNECTED state. The code block in question is:
```
 /*                                                                      
  * PCIe is special, for fabrics transports, we can abort requests before disconnect during reset
  * but we have historically not disconnected pcie qpairs during reset so we have to abort requests
  * here.                                                                
  */                                                                     
 if (qpair->ctrlr->trid.trtype == SPDK_NVME_TRANSPORT_PCIE) {            
     nvme_qpair_abort_reqs(qpair, 0);                                    
 }                                                                       
```

2 seconds after the first completion event, the 10-second timeout triggers (it does not show up in the logs above but I could trace it and it happened) and the device is reset.
As part of the reset process the function `nvme_pcie_ctrlr_delete_io_qpair() (lib/nvme/nvme_pcie_common.c)` is executed to delete the existing qp. The submission queue is destroyed and remaining completion events are polled with `nvme_pcie_qpair_process_completions()`:
```
/* Now that the submission queue is deleted, the device is supposed to have 
 * completed any outstanding I/O. Try to complete them. If they don't complete,
 * they'll be marked as aborted and completed below. */                     
nvme_pcie_qpair_process_completions(qpair, 0);                              
```

`nvme_pcie_qpair_process_completions()` attempts to generate the second completion event but it fails on an assert because the command was already completed (`tr->req == NULL` in this case).

## Expected Behavior

I expect the bdev/nvme code to cancel outstanding commands without crashing.

## Current Behavior

Canceled outstanding commands are completed twice. The first completion event is successful but the second completion event causes the user application to enter an assertion failure.

## Possible Solution

I reviewed the bdev/nvme code related to cancellation of commands and something looks very suspicious: aborting an outstanding command basically removes it from the list `pqpair->outstanding_tr`, executes the completion callback and returns `tr` back to the free list. However, the command may already have complete and the completion event may already be available in the completion queue. I believe we need a flag, which we would set to `true` when the outstanding command is aborted. `nvme_pcie_qpair_process_completions()` would then basically skip all commands that are complete already (`flag == true`). There might be other solutions, like issuing a 'cancel' command to the device.

## Steps to Reproduce

Unfortunately our application is proprietary and we cannot share the reproducer. Do you know if we have a bdev/nvme unit test that verifies cancellation of outstanding commands? We could use such unit test to reproduce the bug.

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 20.04, reproducible with SPDK 21.07 and 21.10

**Comment by sydidelot** [comment]
Is there a patch available already? (I see the tag "Patches out for review")

**Comment by jimharris** [comment]
I think that tag was added by mistake.  I've removed the tag.

**Comment by changpe1** [comment]
Indeed it's a bug, especially some drives will take long time to complete DSM command which may also cause timeout in host driver.  I think adding another state to queue pair is fine, we may not continue to poll the queue pairs which have manual aborted requests.  @sydidelot do you want to a try? we don't have such environment to test this?

**Comment by sydidelot** [comment]
I can test the patch for you. I have a consistent reproducer.

**Comment by changpe1** [comment]
OK, I will fix it.

**Comment by sydidelot** [comment]
Thanks, @changpe1!

**Comment by changpe1** [comment]
Here is the patch to fix this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/10233

**Comment by changpe1** [comment]
Actually I can remove the call to `nvme_qpair_abort_reqs` in `spdk_nvme_ctrlr_free_io_qpair`, this will also fix the scenario here, but there are other cases such as hotplug do require this function, so I think just remove the assertion is better.

**Comment by sydidelot** [comment]
@changpe1 Thanks for the patch, but I think the fix is incorrect. I have posted my comments to Gerrit. Please have a look.

**Comment by changpe1** [comment]
> @changpe1 Thanks for the patch, but I think the fix is incorrect. I have posted my comments to Gerrit. Please have a look.

We've already set the queue pair to DESTROYING state, so there will no new requests sent from applications, so it's safe in practice, but it's indeed a little weird that we use the tracker data structure in the free list.

**Comment by changpe1** [comment]
@sydidelot I used a different way to fix this issue which is more clean, can you have a try with above patch?

**Comment by sydidelot** [comment]
@changpe1 Thanks for the patch!
I'll be verifying it soon.

**Comment by sydidelot** [comment]
@changpe1 I could successfully verify your patch today! No assertion failure anymore. Thanks a lot!
