### ISSUE TITLE
 Failed to configure spdk with shared libraries

### ISSUE THREAD

**Issue by yasharzb** [spdk/spdk#2235]
# Bug report

## Expected Behavior

Successful make

## Current Behavior

Error while making

```

/usr/bin/ld.bfd: cannot find ~/spdk/build/lib/libspdk_event_scheduler.so: No such file or directory
```

![image](https://user-images.githubusercontent.com/45389623/141252558-53a4175d-8fa9-431d-bfec-b00116d3d4b0.png)

## Possible Solution

Maybe a dependency is missing from the prerequisites.

## Steps to Reproduce

1. Executing `./scripts/pkgdep.sh`
2. Executing `./configure --with-shared`
3. `make`

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 21.10
SPDK 21.10

**Comment by Comphix** [comment]
Thanks for reporting this issue. Tried the latest code and hit the same issue. Will take a further look.

**Comment by Comphix** [comment]
Can you have a try with below patch?

https://review.spdk.io/gerrit/c/spdk/spdk/+/10199

**Comment by yasharzb** [comment]
Thanks! This patch worked. But I have another problem right now. I expected after this, I'd be able to work with the library inside of an IDE. But the library is still not recognized in CLion or VSCode. I also executed this after the `make`:
```

ldconfig -v -n ./build/lib
```
I should mention that I am running this on my PC. But I thought that development (without building) might be possible with a computer without a NVMe family SSD.

**Comment by Comphix** [comment]
If this issue is fixed, I'd suggest to submit a new issue to track it.

**Comment by Comphix** [comment]
Patch has been merged. Close this issue.
