### ISSUE TITLE
ncurses update causes build failures [-Werror=format-security]

### ISSUE THREAD

**Issue by ChrisMacNaughton** [spdk/spdk#2237]
# Bug report

Ubuntu has just uploaded a new version of ncurses which changes handling of the `mvwprintw` function and causes errors during build:

```
error: format not a string literal and no format arguments [-Werror=format-security]
```

## Expected Behavior

it should build successfully

## Current Behavior

The build fails referencing three locations where `mvwprintw` is used:

```
spdk_top.c: In function 'print_max_len':
spdk_top.c:658:34: error: format not a string literal and no format arguments [-Werror=format-security]
  658 |         mvwprintw(win, row, col, tmp_str);
      |                                  ^~~~~~~                                                                                            
spdk_top.c: In function 'show_stats':                                                                                                       
spdk_top.c:1864:33: error: format not a string literal and no format arguments [-Werror=format-security]
 1864 |                                 mvprintw(g_max_row - 1, g_max_col - strlen(refresh_error) - 2, refresh_error);
      |                                 ^~~~~~~~
spdk_top.c:1870:52: error: format not a string literal and no format arguments [-Werror=format-security]
 1870 |                         mvprintw(g_max_row - 1, 1, current_page_str);
      |                                                    ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
```

## Possible Solution

Adding a patch like the following around the three failing instances of `mvwprintw` resolve the build failure:

```diff
+#ifdef __GNUC__
+  #pragma GCC diagnostic push
+  /* The following allows us to use these pragmas irrespective
+     of the gcc version. */
+  #pragma GCC diagnostic warning "-Wpragmas"
+  #pragma GCC diagnostic warning "-Wformat-security"
+#endif
        mvwprintw(win, row, col, tmp_str);
-
+#ifdef __GNUC__
+#  pragma diagnostic pop
+#endif
```

## Steps to Reproduce

Build against a new version of ncurses.

This issue was identified when building the Ceph package on Ubuntu for the next release of Ubuntu.

**Comment by Comphix** [comment]
Thanks @ChrisMacNaughton , will you raise a patch to SPDK Gerrit?

**Comment by changpe1** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/10227

**Comment by jimharris** [comment]
Hi @ChrisMacNaughton,

Thanks for the report!  I'm wondering if we can change the code to something like:

```
mvwprintw(..., "%s", tmp_str);
```

I'd prefer that to adding #pragmas around these calls in spdk_top.c.

Jim

**Comment by jimharris** [comment]
@trofi submitted this patch, independently it seems from this issue:
https://review.spdk.io/gerrit/c/spdk/spdk/+/10300

This is similar to the suggestion provided above - @ChrisMacNaughton can you confirm this fixes your build failures?

**Comment by jimharris** [comment]
> @trofi submitted this patch, independently it seems from this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/10300
> 
> This is similar to the suggestion provided above - @ChrisMacNaughton can you confirm this fixes your build failures?

This 10300 patch fixes a lot more instances of this same pattern - assuming @ChrisMacNaughton doesn't see any issues with this patch, I'd rather merge this one than 10227 since it covers all of the cases in this file.

**Comment by jimharris** [comment]
Patches merged.
