### ISSUE TITLE
build with LTO fails on clang

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#2239]
It's happen when test is started with RUN_NIGHTLY=1 flag.

10:32:34  09:32:34	-- spdk/autopackage.sh@78 -- $ ./configure --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --with-nvme-cuse --with-pmdk --with-reduce --with-rbd --with-crypto --with-ocf --enable-ubsan --enable-asan --enable-coverage --with-fuse --with-raid5 --with-uring --enable-lto
10:32:34 Using LTO with clang requires the gold linker.
10:32:35 
10:32:35 
10:32:35 Configuration failed
10:32:35 
10:32:35 
10:32:35   09:32:34	-- spdk/autopackage.sh@78 -- $ trap - ERR
10:32:35   09:32:34	-- spdk/autopackage.sh@78 -- $ print_backtrace
10:32:35   09:32:34	-- common/autotest_common.sh@993 -- $ [[ ehxBET =~ e ]]
10:32:35   09:32:34	-- common/autotest_common.sh@995 -- $ args=("${BASH_ARGV[@]}")
10:32:35   09:32:34	-- common/autotest_common.sh@995 -- $ local args
10:32:35   09:32:34	-- common/autotest_common.sh@997 -- $ xtrace_disable
10:32:35   09:32:34	-- common/autotest_common.sh@14 -- $ '[' no '!=' yes ']'
10:32:35   09:32:34	-- common/autotest_common.sh@15 -- $ PREV_BASH_OPTS=ehxBET
10:32:35   09:32:34	-- common/autotest_common.sh@16 -- $ [[ ehxBET == *\x* ]]
10:32:35   09:32:34	-- common/autotest_common.sh@17 -- $ XTRACE_DISABLED=yes
10:32:35   09:32:34	-- common/autotest_common.sh@19 -- $ set +x
10:32:35 ========== Backtrace start: ==========
10:32:35 
10:32:35 in /home/vagrant/spdk_repo/spdk/autopackage.sh:78 -> main(["/home/vagrant/autorun-spdk.conf"])
10:32:35      ...
10:32:35    73  	
10:32:35    74  	timing_enter build_release
10:32:35    75  	
10:32:35    76  	config_params="$(get_config_params | sed 's/--enable-debug//g')"
10:32:35    77  	if [ $(uname -s) = Linux ]; then
10:32:35 => 78  		./configure $config_params --enable-lto
10:32:35    79  	else
10:32:35    80  		# LTO needs a special compiler to work on BSD.
10:32:35    81  		./configure $config_params
10:32:35    82  	fi
10:32:35    83  	$MAKE ${MAKEFLAGS}
10:32:35      ...

**Comment by mikeBashStuff** [comment]
Going to look into that one.

**Comment by mikeBashStuff** [comment]
We would need couple of fixes here: https://review.spdk.io/gerrit/c/spdk/spdk/+/10238

**Comment by tomzawadzki** [comment]
@xjjx Patch linked by @mikeBashStuff has been merged. Can you confirm the new dependency has been deployed and issue is now fixed ?

**Comment by mikeBashStuff** [comment]
Tested it under our CI - the setup for the clang works now just fine, but it seems that the amount of memory we allocate for the VM is not enough (lto build fails due to kernel bashing it with a stick (oom)). I've seen similar issues across some recent ipsec patches but under the scanbuild job. We are going to fix that on the CI side by redistributing resources for the VMs (per affected job) properly. As to this issue, it can be closed now.
