### ISSUE TITLE
SPDK initiator reports wrong amount of available IOQ

### ISSUE THREAD

**Issue by adamagniv** [spdk/spdk#2242]
# Bug report
SPDK ran as initiator thinks there are a wrong amount of IOQ available on the target (not running SPDK) 
it takes the **Max virtual controllers amount** as the **max IOQ amount**

## Expected Behavior
report 128 Max IOQ instead of 512

## Current Behavior
reporting Max Virtual Controllers as Max IOQ.

## Steps to Reproduce

added this change to SPDK:
```
--- a/lib/nvme/nvme_ctrlr.c
+++ b/lib/nvme/nvme_ctrlr.c
@@ -5128,6 +5128,7 @@ spdk_nvme_ctrlr_alloc_qid(struct spdk_nvme_ctrlr *ctrlr)
 
        nvme_robust_mutex_lock(&ctrlr->ctrlr_lock);
        qid = spdk_bit_array_find_first_set(ctrlr->free_io_qids, 1);
+       NVME_CTRLR_ERRLOG(ctrlr, "qid: %u | opts.num_io_queues: %u\n", qid, ctrlr->opts.num_io_queues);
        if (qid > ctrlr->opts.num_io_queues) {
                NVME_CTRLR_ERRLOG(ctrlr, "No free I/O queue IDs\n");
                nvme_robust_mutex_unlock(&ctrlr->ctrlr_lock);
```
when running perf (also happens with fio spdk_bdev) this is the output:
```
[root@host-3 ~]# /root/spdk/build/examples/perf -w randread -t 120 -q 1 -o $((68*1024)) -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.01" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.02" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.03" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.04" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.05" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.06" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.07" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.08" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.09" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.10" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.11" -r "trtype:RDMA adrfam:IPv4 traddr:169.254.100.11 trsvcid:4420 subnqn:<SUBNQN>.12" -P 1
[2021-11-17 22:07:52.410019] Starting SPDK v21.10 git sha1 4e4f11f / DPDK 21.05.0 initialization...
[2021-11-17 22:07:52.410085] [ DPDK EAL parameters: [2021-11-17 22:07:52.410094] perf [2021-11-17 22:07:52.410102] --no-shconf [2021-11-17 22:07:52.410126] -c 0x1 [2021-11-17 22:07:52.410134] --no-pci [2021-11-17 22:07:52.410148] --log-level=lib.eal:6 [2021-11-17 22:07:52.410157] --log-level=lib.cryptodev:5 [2021-11-17 22:07:52.410165] --log-level=user1:6 [2021-11-17 22:07:52.410173] --iova-mode=pa [2021-11-17 22:07:52.410192] --base-virtaddr=0x200000000000 [2021-11-17 22:07:52.410200] --match-allocations [2021-11-17 22:07:52.410217] --file-prefix=spdk_pid132628 [2021-11-17 22:07:52.410225] ]
EAL: No available 1048576 kB hugepages reported
EAL: No free 2048 kB hugepages reported on node 1
TELEMETRY: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.01
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.02
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.03
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.04
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.05
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.06
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.07
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.08
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.09
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.10
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.11
Attached to NVMe over Fabrics controller at 169.254.100.11:4420: <SUBNQN>.12
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.01) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.02) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.03) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.04) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.05) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.06) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.07) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.08) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.09) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.10) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.11) NSID 1 with lcore 0
Associating RDMA (addr:169.254.100.11 subnqn:<SUBNQN>.12) NSID 1 with lcore 0
Initialization complete. Launching workers.
[2021-11-17 22:07:54.933382] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.01] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.046152] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.02] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.145969] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.03] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.245812] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.04] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.345655] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.05] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.445499] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.06] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.545364] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.07] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.645189] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.08] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.745032] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.09] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.844876] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.10] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:55.944720] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.11] qid: 1 | opts.num_io_queues: 128
[2021-11-17 22:07:56.044560] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.12] qid: 1 | opts.num_io_queues: 128
```
but when using nvme-cli this is the result:
notice the **-i 42** in the nvme connect command command
```
[  --nr-io-queues=<LIST>, -i <LIST> ] --- number of io queues to use (default is core count)

[root@host-3 ~]# for i in 0{1..9} {10..12};do nvme connect -t rdma -a 169.254.100.11 -s 4420 -i 42 -n <SUBNQN>.${i}; done;
[root@host-3 ~]# ls /dev/nvme*
/dev/nvme0    /dev/nvme1   /dev/nvme10n1  /dev/nvme11n1  /dev/nvme2    /dev/nvme3    /dev/nvme4    /dev/nvme5    /dev/nvme6    /dev/nvme7    /dev/nvme8    /dev/nvme9    /dev/nvme-fabrics
/dev/nvme0n1  /dev/nvme10  /dev/nvme11    /dev/nvme1n1   /dev/nvme2n1  /dev/nvme3n1  /dev/nvme4n1  /dev/nvme5n1  /dev/nvme6n1  /dev/nvme7n1  /dev/nvme8n1  /dev/nvme9n1
[root@host-3 ~]# dmesg | less
[201802.668699] nvme nvme0: creating 42 I/O queues.
[201807.041447] nvme nvme0: new ctrl: NQN "<SUBNQN>.01", addr 169.254.100.11:4420
[201807.087099] nvme nvme1: creating 42 I/O queues.
[201811.473885] nvme nvme1: new ctrl: NQN "<SUBNQN>.02", addr 169.254.100.11:4420
[201811.514102] nvme nvme2: creating 42 I/O queues.
[201815.906279] nvme nvme2: new ctrl: NQN "<SUBNQN>.03", addr 169.254.100.11:4420
[201815.940495] nvme nvme3: creating 42 I/O queues.
[201820.328725] nvme nvme3: new ctrl: NQN "<SUBNQN>.04", addr 169.254.100.11:4420
[201820.376881] nvme nvme4: creating 42 I/O queues.
[201824.771097] nvme nvme4: new ctrl: NQN "<SUBNQN>.05", addr 169.254.100.11:4420
[201824.816707] nvme nvme5: creating 42 I/O queues.
[201829.203504] nvme nvme5: new ctrl: NQN "<SUBNQN>.06", addr 169.254.100.11:4420
[201829.242377] nvme nvme6: creating 42 I/O queues.
[201833.635931] nvme nvme6: new ctrl: NQN "<SUBNQN>.07", addr 169.254.100.11:4420
[201833.681672] nvme nvme7: creating 42 I/O queues.
[201838.068336] nvme nvme7: new ctrl: NQN "<SUBNQN>.08", addr 169.254.100.11:4420
[201838.119918] nvme nvme8: creating 42 I/O queues.
[201842.501428] nvme nvme8: new ctrl: NQN "<SUBNQN>.09", addr 169.254.100.11:4420
[201842.540956] nvme nvme9: creating 42 I/O queues.
[201846.973018] nvme nvme9: new ctrl: NQN "<SUBNQN>.10", addr 169.254.100.11:4420
[201847.019348] nvme nvme10: creating 42 I/O queues.
[201851.415365] nvme nvme10: new ctrl: NQN "<SUBNQN>.11", addr 169.254.100.11:4420
[201851.454109] nvme nvme11: creating 42 I/O queues.
[201855.847810] nvme nvme11: new ctrl: NQN "<SUBNQN>.12", addr 169.254.100.11:4420
```
so in total **12 drives * 42 IOQ per drive = 504 IOQ** (you can open up to 512 but it doesn't devide equally between 12 drives)

## Context (Environment including OS version, SPDK version, etc.)
SPDK 21.10 (seen also in 21.07)
on the target there are 12 drives, all availible from the same port (IP 169.254.100.11)
Max IOQ 512
Max Virtual Controllers 128

**Comment by Comphix** [comment]
Not quite clear.

In above SPDK log:

[2021-11-17 22:07:54.933382] nvme_ctrlr.c:5131:spdk_nvme_ctrlr_alloc_qid: *ERROR*: [<SUBNQN>.01] qid: 1 | opts.num_io_queues: 128  <<<<<<<<

The Max IO Queues is 128 for this single controller.

And for the nvme cli, it successfully allocated 42 queues.

Are you expecting SPDK to report 128 queues or 512 queues?

**Comment by jimharris** [comment]
> # Bug report
> SPDK ran as initiator thinks there are a wrong amount of IOQ available on the target (not running SPDK) it takes the **Max virtual controllers amount** as the **max IOQ amount**

Hi,

Please clarify which target you are using.  Is it the kernel target?  If not, can you reproduce this problem with the SPDK target or kernel target?

It's not clear what is meant by "max virtual controllers amount".  SPDK uses the GET_NUM_QUEUES NVMe feature to determine the maximum number of IOQ per controller.

> 
> but when using nvme-cli this is the result: notice the **-i 42** in the nvme connect command command

In this case, you are telling the kernel how many IOQs to use per controller.  This is different than the opts.num_io_queues above, which indicates the maximum number of IOQs that could be allocated.

> 
> ```
> [  --nr-io-queues=<LIST>, -i <LIST> ] --- number of io queues to use (default is core count)
> 
> [root@host-3 ~]# for i in 0{1..9} {10..12};do nvme connect -t rdma -a 169.254.100.11 -s 4420 -i 42 -n <SUBNQN>.${i}; done;
> 
> so in total **12 drives * 42 IOQ per drive = 504 IOQ** (you can open up to 512 but it doesn't devide equally between 12 drives)
> 
> ## Context (Environment including OS version, SPDK version, etc.)
> SPDK 21.10 (seen also in 21.07) on the target there are 12 drives, all availible from the same port (IP 169.254.100.11) Max IOQ 512 Max Virtual Controllers 128

Please explain more about "max IOQ" and "max virtual controllers" - specifically how these map to the NVMe specification.

Thanks,

Jim

**Comment by adamagniv** [comment]
Hi @jimharris, thank you for the reply.
So the target is a specific nvme enclosure from a vendor I use. So, I don't 100% know how to answer regarding this.

> SPDK uses the GET_NUM_QUEUES NVMe feature to determine the maximum number of IOQ per controller.

If this is true, running nvme-cli to connect to the 1st drive in the target with **-i 128** should have shown in the dmesg log that 128 I/O Queue were created.
but in fact this is the result on my end:
```
[root@host-3 ~]# nvme connect -t rdma -a 169.254.100.11 -s 4420 -i 128 -n <SUBNQN>.01
[root@host-3 ~]# dmesg | less
[229090.368039] nvme nvme0: creating 63 I/O queues.
[229096.922005] nvme nvme0: new ctrl: NQN "<SUBNQN>.01", addr 169.254.100.11:4420
```
you can see that only **63 IOQ** were created, this number is returned for each -i higher than 63 when I try to connect so "GET_NUM_QUEUES" should have returned 63 and not 128.

> Please explain more about "max IOQ" and "max virtual controllers" 

As far as I understand:
**Max IO Queues -**  is the number of maximum IOQ the target can handle to manage across all of it's drives combined and divided between them how ever the user would like to by connecting to them. It is set to **512** on my target.

- Example: I have "Max IO Queues" set to 512. if I had 4 initiators trying to connect one-by-one to all 12 drives on the target with nvme-cli passing -i 12, the last initiator would have failed, the total IOQ the first 3 initiators took is 3 * 12 *12 (=432 IOQ). The 4th initiator needs 144 IOQ but the target has 80 left, the first 6 drives would have gotten 12 IOQ each just fine, the 7th would have gotten the last 8 IOQ remaining and drives 8-12 would have failed to connect completely. 

**Max Virtual Controllers -** is the number of maximum virtual controllers the target can handle and manage across different initiators connected to the target. It is set to **128** on my target. 
- Example: I have "Max Virtual Controllers" set to 128, if I had 129 initiators connected to the same target, having all of them trying to run nvme-cli to connect only to the 1st drive on the target, 128 of could have created 1 bdev under /dev and the 129th would have failed and return `Failed to write to /dev/nvme-fabrics: Input/output error` and the dmesg would have shown `Connect command failed, error wo/DNR bit: 6`

So what I think is happening because of seeing 128 (which is familiar) printed for num_io_queues, is that it shows the max virtual controllers instead of 512 in case we need to see the Max IOQ amount or 63 if we go with what I see using nvme-cli when connecting to a drive with -i > 63.

**Comment by jimharris** [comment]
> Hi @jimharris, thank you for the reply. So the target is a specific nvme enclosure from a vendor I use. So, I don't 100% know how to answer regarding this.
> 
> > SPDK uses the GET_NUM_QUEUES NVMe feature to determine the maximum number of IOQ per controller.
> 
> If this is true, running nvme-cli to connect to the 1st drive in the target with **-i 128** should have shown in the dmesg log that 128 I/O Queue were created. but in fact this is the result on my end:

How many CPU cores do you have on this system?  Will the Linux kernel actually try to allocate more IO queues than there are CPU cores on the system?

> 
> ```
> [root@host-3 ~]# nvme connect -t rdma -a 169.254.100.11 -s 4420 -i 128 -n <SUBNQN>.01
> [root@host-3 ~]# dmesg | less
> [229090.368039] nvme nvme0: creating 63 I/O queues.
> [229096.922005] nvme nvme0: new ctrl: NQN "<SUBNQN>.01", addr 169.254.100.11:4420
> ```
> 
> you can see that only **63 IOQ** were created, this number is returned for each -i higher than 63 when I try to connect so "GET_NUM_QUEUES" should have returned 63 and not 128.

We need to differentiate between how many queues the controller reports through the NUMBER_OF_QUEUES feature, and how many queues are actually created using CREATE_CQ/CREATE_SQ commands.

When the kernel reports "creating 63 I/O queues", that only indicates to me that it created 63 queues with CREATE_CQ/CREATE_SQ commands.  This is different than the opts.num_io_queues value from SPDK which indicates the number of queues reported by NUMBER_OF_QUEUES NVMe feature.

> 
> > Please explain more about "max IOQ" and "max virtual controllers"
> 
> As far as I understand: **Max IO Queues -** is the number of maximum IOQ the target can handle to manage across all of it's drives combined and divided between them how ever the user would like to by connecting to them. It is set to **512** on my target.

This may be a limit created by the vendor of this target, but it's not something I'm aware of that can be reported to the initiator.  The initiator can only determine per-controller limits on the number of queues using the NUMBER_OF_QUEUES feature with SET_FEATURE/GET_FEATURE admin command.

> 
> * Example: I have "Max IO Queues" set to 512. if I had 4 initiators trying to connect one-by-one to all 12 drives on the target with nvme-cli passing -i 12, the last initiator would have failed, the total IOQ the first 3 initiators took is 3 * 12 *12 (=432 IOQ). The 4th initiator needs 144 IOQ but the target has 80 left, the first 6 drives would have gotten 12 IOQ each just fine, the 7th would have gotten the last 8 IOQ remaining and drives 8-12 would have failed to connect completely.
> 
> **Max Virtual Controllers -** is the number of maximum virtual controllers the target can handle and manage across different initiators connected to the target. It is set to **128** on my target.
> 
> * Example: I have "Max Virtual Controllers" set to 128, if I had 129 initiators connected to the same target, having all of them trying to run nvme-cli to connect only to the 1st drive on the target, 128 of could have created 1 bdev under /dev and the 129th would have failed and return `Failed to write to /dev/nvme-fabrics: Input/output error` and the dmesg would have shown `Connect command failed, error wo/DNR bit: 6`
> 
> So what I think is happening because of seeing 128 (which is familiar) printed for num_io_queues, is that it shows the max virtual controllers instead of 512 in case we need to see the Max IOQ amount or 63 if we go with what I see using nvme-cli when connecting to a drive with -i > 63.

I don't think this is what is happening.  There is no "max virtual controllers" that I am aware of in the NVMe spec, meaning there is no way for the initiator to know anything about this value.

**Comment by adamagniv** [comment]
> How many CPU cores do you have on this system? Will the Linux kernel actually try to allocate more IO queues than there are CPU cores on the system?
``[root@host-2 ~]# grep -c ^processor /proc/cpuinfo
64
``
Good observation! I totally forgot about that part!

I also ran `nvme connect -t rdma -a 169.254.100.11 -s 4420 -i 128 -n <SUBNQN>.01` from 3 different hosts to see the sum of IOQP that will be created:
**server1 dmesg**
```
[423731.277609] nvme nvme0: creating 63 I/O queues.
[423737.871116] nvme nvme0: new ctrl: NQN "<SUBNQN>.01", addr 169.254.100.11:4420
```
**server2 dmesg**
```
[504995.441554] nvme nvme0: creating 63 I/O queues.
[505002.015473] nvme nvme0: new ctrl: NQN "<SUBNQN>.01", addr 169.254.100.11:4420
```
**server3 dmesg**
```
[854540.159033] nvme nvme0: creating 2 I/O queues.
[854540.368252] nvme nvme0: new ctrl: NQN "<SUBNQN>.01", addr 169.254.100.11:4420
```

total of 128 IOQP were created. @jimharris , you are totally right and I got it all wrong! Closing this ticket.
So now this is clearly my mistake, we can continue to handle the issue that started this mess #2243
