### ISSUE TITLE
[scheduler_create_thread] Assertion `spdk_interrupt_mode_is_enabled()' failed

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2247]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_62229.html

## Execution failed at

00:03:43.994  ************************************
00:03:43.994  START TEST scheduler_create_thread
00:03:43.994  ************************************
00:03:43.994   16:54:33	-- common/autotest_common.sh@964 -- # xtrace_enable
00:03:43.994   16:54:33	-- common/autotest_common.sh@965 -- # scheduler_create_thread
00:03:43.995   16:54:33	-- scheduler/scheduler.sh@8 -- # rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n active_pinned -m 0x1 -a 100
00:03:43.995   16:54:33	-- common/autotest_common.sh@473 -- # xtrace_disable
00:03:43.995   16:54:33	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:43.995   16:54:33	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:03:43.996   16:54:33	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:03:43.996   16:54:33	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:43.996   16:54:33	-- common/autotest_common.sh@19 -- # set +x
00:03:44.003  2
00:03:44.003   16:54:33	-- common/autotest_common.sh@500 -- # xtrace_enable
00:03:44.003   16:54:33	-- common/autotest_common.sh@501 -- # [[ 0 == 0 ]]
00:03:44.003   16:54:33	-- scheduler/scheduler.sh@9 -- # rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n active_pinned -m 0x2 -a 100
00:03:44.004   16:54:33	-- common/autotest_common.sh@473 -- # xtrace_disable
00:03:44.004   16:54:33	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:44.004   16:54:33	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:03:44.004   16:54:33	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:03:44.005   16:54:33	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:44.005   16:54:33	-- common/autotest_common.sh@19 -- # set +x
**_00:03:44.005  scheduler: thread.c:1909: spdk_thread_set_interrupt_mode: Assertion `spdk_interrupt_mode_is_enabled()' failed._**
00:03:47.732  Traceback (most recent call last):
00:03:47.732    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2774, in <module>
00:03:47.732      call_rpc_func(tmp_args)
00:03:47.732    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2701, in call_rpc_func
00:03:47.732      args.func(args)
00:03:47.732    File "/home/vagrant/spdk_repo/spdk/test/rpc_plugins/scheduler_plugin.py", line 14, in create_thread
00:03:47.732      print_json(thread_create(args))
00:03:47.732    File "/home/vagrant/spdk_repo/spdk/test/rpc_plugins/scheduler_plugin.py", line 10, in thread_create
00:03:47.732      return args.client.call('scheduler_thread_create', params)
00:03:47.732    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 183, in call
00:03:47.732      response = self.recv()
00:03:47.732    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 161, in recv
00:03:47.732      newdata = self.sock.recv(4096)
00:03:47.732  ConnectionResetError: [Errno 104] Connection reset by peer
00:03:47.761   16:54:37	-- common/autotest_common.sh@500 -- # xtrace_enable
00:03:47.761   16:54:37	-- common/autotest_common.sh@501 -- # [[ '' == 0 ]]
00:03:47.761  /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 472: 22938 Aborted                 (core dumped) $testdir/scheduler -m 0xF -p 0x2 --wait-for-rpc
00:03:47.761    16:54:37	-- common/autotest_common.sh@472 -- # trap - ERR
00:03:47.761    16:54:37	-- common/autotest_common.sh@472 -- # print_backtrace
00:03:47.761    16:54:37	-- common/autotest_common.sh@993 -- # [[ ehxBET =~ e ]]
00:03:47.762    16:54:37	-- common/autotest_common.sh@995 -- # args=("${BASH_ARGV[@]}")
00:03:47.762    16:54:37	-- common/autotest_common.sh@995 -- # local args
00:03:47.762    16:54:37	-- common/autotest_common.sh@997 -- # xtrace_disable
00:03:47.762    16:54:37	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:47.762    16:54:37	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:03:47.763    16:54:37	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:03:47.763    16:54:37	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:47.763    16:54:37	-- common/autotest_common.sh@19 -- # set +x
00:03:47.763  ========== Backtrace start: ==========
00:03:47.763  
00:03:47.768  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:472 -> rpc_cmd(["--plugin"],["scheduler_plugin"],["scheduler_thread_create"],["-n"],["active_pinned"],["-m"],["0x2"],["-a"],["100"])
00:03:47.768       ...
00:03:47.769     467 	
00:03:47.769     468 		echo "$config_params"
00:03:47.769     469 		xtrace_restore
00:03:47.769     470 	}
00:03:47.769     471 	
00:03:47.769  => 472 	function rpc_cmd() {
00:03:47.769     473 		xtrace_disable
00:03:47.769     474 		local rsp rc=1
00:03:47.769     475 		local stdin cmd cmds_number=0 status_number=0 status
00:03:47.769     476 	
00:03:47.769     477 		if (($#)); then
00:03:47.769       ...
00:03:47.776  in /home/vagrant/spdk_repo/spdk/test/event/scheduler/scheduler.sh:9 -> scheduler_create_thread([])
00:03:47.776       ...
00:03:47.776     4   	rootdir=$(readlink -f $testdir/../../..)
00:03:47.776     5   	source $rootdir/test/common/autotest_common.sh
00:03:47.776     6   	
00:03:47.776     7   	function scheduler_create_thread() {
00:03:47.776     8   		$rpc --plugin scheduler_plugin scheduler_thread_create -n active_pinned -m 0x1 -a 100
00:03:47.776  => 9   		$rpc --plugin scheduler_plugin scheduler_thread_create -n active_pinned -m 0x2 -a 100
00:03:47.776     10  		$rpc --plugin scheduler_plugin scheduler_thread_create -n active_pinned -m 0x4 -a 100
00:03:47.776     11  		$rpc --plugin scheduler_plugin scheduler_thread_create -n active_pinned -m 0x8 -a 100
00:03:47.776     12  		$rpc --plugin scheduler_plugin scheduler_thread_create -n idle_pinned -m 0x1 -a 0
00:03:47.776     13  		$rpc --plugin scheduler_plugin scheduler_thread_create -n idle_pinned -m 0x2 -a 0
00:03:47.776     14  		$rpc --plugin scheduler_plugin scheduler_thread_create -n idle_pinned -m 0x4 -a 0
00:03:47.776       ...
00:03:47.784  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:965 -> run_test(["scheduler_create_thread"],["scheduler_create_thread"])
00:03:47.784       ...
00:03:47.784     960 		timing_enter $test_name
00:03:47.784     961 		echo "************************************"
00:03:47.784     962 		echo "START TEST $test_name"
00:03:47.784     963 		echo "************************************"
00:03:47.784     964 		xtrace_restore
00:03:47.784  => 965 		time "$@"
00:03:47.784     966 		xtrace_disable
00:03:47.784     967 		echo "************************************"
00:03:47.784     968 		echo "END TEST $test_name"
00:03:47.784     969 		echo "************************************"
00:03:47.784     970 		timing_exit $test_name
00:03:47.784       ...
00:03:47.792  in /home/vagrant/spdk_repo/spdk/test/event/scheduler/scheduler.sh:36 -> main([])
00:03:47.792       ...
00:03:47.792     31  	
00:03:47.792     32  	$rpc framework_set_scheduler dynamic
00:03:47.792     33  	$rpc framework_start_init
00:03:47.792     34  	
00:03:47.792     35  	# basic integrity test
00:03:47.792  => 36  	run_test "scheduler_create_thread" scheduler_create_thread
00:03:47.792     37  	
00:03:47.792     38  	trap - SIGINT SIGTERM EXIT
00:03:47.792     39  	killprocess $scheduler_pid
00:03:47.792       ...
00:03:47.792  
00:03:47.792  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_62229.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_64233.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_71291.html

**Comment by jimharris** [comment]
Issue not seen for over 5 months.
