### ISSUE TITLE
[vfio-user]Hot remove namespace with multiple namespaces can only show first one removed in guest

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2249]
# Bug report
Hot remove namespace with multiple namespaces can only show first time removed in guest

## Expected Behavior
Hot remove the namespace second/third time in the host, the Guest will not show the removed Namespace 

## Current Behavior
Hot remove the second/third Namespace in the host, the Guest still can see the removed Namespace 

## Steps to Reproduce
[Host machine]Start nvmf target:
./build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x1
mkdir -p /var/run/vfio-user/domain/vfio-user1/1
./scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode1 -a -s SPDK1
./scripts/rpc.py bdev_malloc_create 64 512 -b Malloc1
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode1 Malloc1
./scripts/rpc.py bdev_malloc_create 64 1024 -b Malloc2
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode1 Malloc2
./scripts/rpc.py bdev_malloc_create 256 1024 -b Malloc3
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode1 Malloc3
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode1 -t VFIOUSER -a /var/run/vfio-user/domain/vfio-user1/1 -s 0

[Host Machine]Start Qemu:
sudo taskset -a -c 1,2 /home/qwan/utils/qemu/build/x86_64-softmmu/qemu-system-x86_64 -m 4096 --enable-kvm -cpu host -smp 2 \
-object memory-backend-file,id=mem,size=4096M,mem-path=/dev/hugepages,prealloc=yes,share=yes,host-nodes=0,policy=bind \
-numa node,memdev=mem \
-vga std -vnc :100 -daemonize  -snapshot \
-monitor telnet:127.0.0.1:10002,server,nowait \
-pidfile /home/qwan/vfio-user/vm/0/qemu.pid \
 -serial file:/home/qwan/vfio-user/vm/0/serial.log \
-D /home/qwan/vfio-user/vm/0/qemu.log \
-chardev file,path=/home/qwan/vfio-user/vm/0/seabios.log,id=seabios \
-device isa-debugcon,iobase=0x402,chardev=seabios \
-net user,hostfwd=tcp::10000-:22,hostfwd=tcp::10001-:8765 -net nic \
-drive file=/home/qwan/utils/centos7.01804qcow2.qcow2,if=none,id=os_disk -device ide-hd,drive=os_disk,bootindex=0 \
-device vfio-user-pci,socket=/var/run/vfio-user/domain/vfio-user1/1/cntrl

[Host Machine]Remove namespace:
./scripts/rpc.py nvmf_subsystem_remove_ns nqn.2019-07.io.spdk:cnode1 1
./scripts/rpc.py nvmf_subsystem_remove_ns nqn.2019-07.io.spdk:cnode1 2

[VM]Show namespace:
nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n2     SPDK1                SPDK bdev Controller                     2           0.00   B /   0.00   B      1   B +  0 B   22.01
/dev/nvme0n3     SPDK1                SPDK bdev Controller                     3         268.44  MB / 268.44  MB      1 KiB +  0 B   22.01

## Context (Environment including OS version, SPDK version, etc.)
Only first time removed namespace will not show in guest, second/third time removed namespace still exist in guest with nvme list command. 
qemu:
vfio-user-rfc1.9
commit d687f0be9ef2f93224bebb761369fdb0d61378e3
spdk: commit f386632

**Comment by jimharris** [comment]
@changpe1 @wanqunintel Is this issue still valid?

**Comment by jimharris** [comment]
Closing issue.  @changpe1 @wanqunintel please reopen if this issue still exists.
