### ISSUE TITLE
[run_nvmf.py]: The fio_config_file  may absent [jobs] module that generated by scripts/perf/nvmf/run_nvmf.py, line 886

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2251]
# Bug report
[jobs] module absent in fio_config_file  generated by scripts/perf/nvmf/run_nvmf.py in line 886

## Expected Behavior
Want the fio config file format

[global]
ioengine=/tmp/spdk/build/fio/spdk_bdev
spdk_json_conf=/tmp/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

norandommap=1
rw=randread
rwmixread=100
bs=4k
time_based=1
ramp_time=10
runtime=60
rate_iops=0
numjobs=8
cpus_allowed=0-7
cpus_allowed_policy=shared

[jobs]
filename=Nvme0n1
filename=Nvme1n1
filename=Nvme2n1
filename=Nvme3n1
filename=Nvme4n1
filename=Nvme5n1
filename=Nvme6n1

## Current Behavior
[global]
ioengine=/tmp/spdk/build/fio/spdk_bdev
spdk_json_conf=/tmp/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

norandommap=1
rw=randread
rwmixread=100
bs=4k
time_based=1
ramp_time=10
runtime=60
rate_iops=0
numjobs=8
cpus_allowed=0-7
cpus_allowed_policy=shared

## Steps to Reproduce

1. Build SPDK on target machine
`./configure --without-isal --enable-debug --with-fio=/usr/src/fio`

2. Prepare the config30.json as below on target machine
`{ "general": { "username": "root", "password": "tester", "transport": "TCP", "skip_spdk_install": true }, "target": { "mode": "spdk", "nic_ips": [ "192.168.20.11" ], "core_mask": "[0-7]", "null_block_devices": 8, "sar_settings": [ false, 30, 1, 60 ], "enable_bandwidth": [ false, 60 ], "enable_dpdk_memory": [ false, 30 ], "num_shared_buffers": 4096, "bpf_proc": "None", "scheduler_settings": "dynamic", "zcopy_settings": false, "dif_insert_strip": true, "null_block_dif_type": 3 }, "initiator1": { "ip": "10.67.114.250", "nic_ips": [ "192.168.20.12" ], "target_nic_ips": [ "192.168.20.11" ], "mode": "spdk", "fio_bin": "/usr/src/fio/fio", "nvmecli_bin": "/path/to/nvmecli/bin", "cpus_allowed": "0-7", "cpus_allowed_policy": "shared", "num_cores": 8, "adq_enable": false, "kernel_engine": "io_uring" }, "fio": { "bs": [ "4k" ], "qd": [ 128 ], "rw": [ "randread" ], "rwmixread": 100, "rate_iops": 0, "num_jobs": 8, "run_time": 60, "ramp_time": 10, "run_num": 1, "thinktime": 0 } }`
 

3. Run scripts/perf/nvmf/run_nvmf.py -c scripts/perf/nvmf/config30.json on target machine

4. Run fio command fail because the absence of  [jobs] module
![fio](https://user-images.githubusercontent.com/87507097/143184181-d9280381-5a01-43a5-b3f3-52ffb98efc35.png)

## Context (Environment including OS version, SPDK version, etc.)
SPDK 1fa4d590d  `test/vfio_user: add vfio-user fuzzing test`
Fio `fio-3.28-104-gf7c3f`

Host and target env, connect with local area network.

**Comment by changpe1** [comment]
@junwenx do you want to a try to add this feature? it's OK to me to add them manually.

**Comment by changpe1** [comment]
@junwenx I don't think this is an issue, closing it now.

**Comment by junwenx** [comment]
@changpe1 OK, manually is OK. thanks
