### ISSUE TITLE
spdk nvmf rdma discover fails with iwarp transport

### ISSUE THREAD

**Issue by bharatpotnuri** [spdk/spdk#2253]
# Bug report

Hi All,
With TOT spdk, NVMF discover fails with iWARP. on debugging further, the following commit has introduced a regression for iwarp devices.

commit 64fa301f6728ac752de30e3c3c427618ab87aa7e
Author: Alexey Marchuk <alexeymar@mellanox.com>
Date:   Thu Nov 18 22:12:53 2021 +0300

    rdma: Update for memory map

    Add a parameter which determines the owner of the
    map - target or initiator. It allows to set different
    access flags when creating Memory Regions

    Signed-off-by: Alexey Marchuk <alexeymar@mellanox.com>
    Change-Id: I0016847fe116e193d0954db1c8e65066b4ff82bf
    Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/10283
    Community-CI: Broadcom CI <spdk-ci.pdl@broadcom.com>
    Community-CI: Mellanox Build Bot
    Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
    Reviewed-by: Ben Walker <benjamin.walker@intel.com>
    Reviewed-by: Shuhei Matsumoto <shuhei.matsumoto.xt@hitachi.com>

## Current Behavior

discovering SPDK target fails for iwarp transport. 

## Possible Solution

Failure is due to memory access violations for RDMA read operation on the target side. Commit '64fa301f6728' provides different memory access permissions for target and initiator. RDMA READ works a bit different from that of RoCE/Infiniband and it needs REMOTE_WRITE access permission according to standard. Following is the easiest way for fixing the issue. @AlekseyMarchuk, Please review.

```
diff --git a/lib/rdma/common.c b/lib/rdma/common.c
index 37de0ffde730..4ea3c9f75003 100644
--- a/lib/rdma/common.c
+++ b/lib/rdma/common.c
@@ -72,7 +72,7 @@ rdma_mem_notify(void *cb_ctx, struct spdk_mem_map *map,
                } else {
                        switch (rmap->role) {
                        case SPDK_RDMA_MEMORY_MAP_ROLE_TARGET:
-                               access_flags = IBV_ACCESS_LOCAL_WRITE;
+                               access_flags = IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_WRITE;
                                break;
                        case SPDK_RDMA_MEMORY_MAP_ROLE_INITIATOR:
                                access_flags = IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_READ | IBV_ACCESS_REMOTE_WRITE;

```

## Steps to Reproduce

Generic spdk target creation with rdma transport and discover/fio using iwarp device.

## Context (Environment including OS version, SPDK version, etc.)

version: SPDK v22.01-pre git sha1 a1014fcceecf
linux 5.16

**Comment by AlekseyMarchuk** [comment]
Hi @bharatpotnuri 
Thanks for reporting this issue. Please try this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/10392 It sets REMOTE_WRITE access flag for iWARP transport

**Comment by bharatpotnuri** [comment]
> Hi @bharatpotnuri Thanks for reporting this issue. Please try this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/10392 It sets REMOTE_WRITE access flag for iWARP transport

@AlekseyMarchuk patch looks fine and works as expected. Thanks for the quick patch!
