### ISSUE TITLE
scripts/check_format.sh breaks on darwin

### ISSUE THREAD

**Issue by jsoref** [spdk/spdk#2255]
# Bug report

`scripts/check_format.sh` breaks when run on macOS Big Sur 11.6.1 (which like all versions of macOS from Apple doesn't have a bash newer than 3.2 because of a GPL license change for the subsequent bash versions)

## Expected Behavior

Script should not fail

## Current Behavior

```
+++ dirname scripts/check_format.sh
++ readlink -f scripts
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

## Possible Solution

Solutions are discussed here:
https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

Change the shbang to specify bashX where X is the minimum supported version of bash (this at least documents what's going on).

Add documentation (or code) telling users to install bashX (e.g. using `brew`).

I'm not prescribing any particular solution.

## Steps to Reproduce

1. get a mac (using zsh, the default shell)
2. clone spdk/spdk
3. see https://spdk.io/development/#submitting-a-patch which hints about running: `scripts/check_format.sh`
4. try running `scripts/check_format.sh`

## Context (Environment including OS version, SPDK version, etc.)

Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
Base commit is 1fa4d590d829703af88722ff9424c2c51bc7957b

**Comment by mikeBashStuff** [comment]
I wonder if MacOS still ships with an ancient Bash on board (last time I checked it was at 3.2 or something similar). If that's the case, users would still need to upgrade it to be able to run most of the scripts from the repo (including `check_format.sh`).

**Comment by jsoref** [comment]
macOS defaults to zsh instead.
Apple isn't a fan of gpl, so the licence change pushed them to abandon it.

https://discussions.apple.com/thread/252176464

**Comment by jimharris** [comment]
I needed to install bash, readlink and grep using homebrew to get this to work on MacOS, along with this patch:

https://review.spdk.io/gerrit/c/spdk/spdk/+/10476

Default bash doesn't support mapfile.
Default readlink doesn't support -f option.
Default grep doesn't support -P option.
