### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by jsoref** [spdk/spdk#2256]
# Bug report

Any project larger / older than `hello world` will have typos. This issue is to hang a series of changesets to fix some of them.

## Expected Behavior

Ideally there wouldn't be typos (and CI would block them from being introduced), or at least the check-spelling action could report a ✅ when run against a corrected baseline.

## Current Behavior

https://github.com/jsoref/spdk/commit/03f3f5471346f99a69cc3fde0c2a45dafcf679ec#commitcomment-60785664

<details><summary>Unrecognized words (297)</summary>

```
absoulte
acccelerator
Acccess
accesible
ACKNOLWEDGE
activatation
adddress
Additionall
Addres
addtional
adrmfam
Aggregration
alisaes
alllocated
allocat
alreday
anoter
apperarance
apssed
archieve
aruments
asociated
assocation
asyncronously
attepmt
Autority
avaiable
avaialble
Aymmetric
barier
betwen
boardcast
bookeeping
bufer
caces
Caculate
caculated
calback
calllback
capabilites
chaning
channnel
chilren
classess
coalese
cofniguration
comapre
commmand
comparision
compatiblity
completition
configration
configure'ed
confiuration
connnect
conntroller
conroller
consturct
continueing
contoller
controlqueue
copyied
cource
cpusmask
curently
currenty
currrent
decice
decriptor
defered
deferenced
definitons
defult
deinitalize
deinitalized
dependecies
desciptor
DESCIRPTORS
Descripter
destory
detachement
differeniate
diffrent
dirver
Disect
displying
Disscussed
doens't
doesnot
doobell
dosen't
dpends
effciently
elasicity
enqueuing
envirionment
Environemnt
Envronment
ERRRORS
evething
excecution
excluced
execeeds
execuction
Exended
existsing
Exmaple
expaction
explictly
failback
faile
failse
failuer
fasion
finilize
fisrt
folllowing
frequencey
fucntion
funciton
funtions
gracfully
hadling
hdgest
Hugepagesize
huges
hugesize
Identidfiers
IGNORRED
implcitly
implemenation
implemention
implmentation
incapsule
incomming
incompatiblity
incremention
indefinitedly
inexistant
infilght
ingoring
inilialization
init'ing
initailzied
initalization
Initalizing
initator
initializaiton
initilization
initilize
inititator
initlize
integity
interation
interupt
intialization
intialize
iteraion
latiencies
libaries
malicionus
managment
mangement
miliseconds
musn't
namesapce
namespce
negociated
negotation
negotitated
negtive
notificaton
Nubmer
obatined
obious
occure
occured
occuring
offseting
Onput
operatons
opertations
oprations
orginal
otherwirse
oustanding
outstaind
overwhelmmed
parameteres
paramter
parmaters
parralel
partialy
partion
Partitio
partiular
pocessing
possitive
premmpts
preping
presistent
prioity
priviledged
properites
provisoned
puposes
receving
recieve
recieved
redirectd
REGISONS
reocvery
reponse
reqeust
requsted
responsed
retrievie
retrived
reveived
revison
rigth
runnning
satic
satisified
sccessful
scenerio
segmemt
sementics
separatate
seperate
sequece
sevral
sgainst
shoud
shoule
similiar
skiped
snpashot
sourcable
specfic
speicifed
Stauts
struture
stuct
subsytem
subystems
succedds
succeeed
succesfully
Succesfuly
succesufully
succssful
suceess
sufficienntly
suplied
susbsystem
susbsytem
sybsystem
sync'ing
synchronosuly
tempalte
ternminate
thead
thesame
theshold
thie
thiose
tranlate
TRANPARENT
tranport
transfered
trasnfer
treshold
triggerring
unchaged
unerlying
unexpetced
unpluged
unregisted
unregistereed
unregistred
unregiter
unregsiter
Unspported
urfsafe
ussless
usuable
utilility
valies
varaible
vaule
Versoning
virtuque
volumnes
workolad
workround
zero'ed
```
</details>

## Possible Solution

I'll send some changesets to Gerrit when I can convince the tooling to cooperate

## Steps to Reproduce

1. Fork this repository in GitHub and pull https://github.com/jsoref/spdk/commit/03f3f5471346f99a69cc3fde0c2a45dafcf679ec into your fork
2. Wait for GitHub Actions to run

## Context (Environment including OS version, SPDK version, etc.)

GitHub Actions CI can identify typos and help guard against them, but, that's fairly outside the scope of this issue.

To generate corrections, I take the output from the above and feed it to a Google Sheet and then ask Google Sheets to suggest spelling fixes, from there I apply them and _try_ to make sure I haven't introduced additional errors (but, I'm human so I make errors too).

I'm splitting the changes by top level file/directory and will try to submit them...

**Comment by Comphix** [comment]
Thanks @jsoref , let me first assign to you as you will submit the changes. Thanks.

**Comment by mikeBashStuff** [comment]
I actually opened a trello card some time ago to use misspel-fixer as part of `check_format.sh`.  Closed it (quite recently) as it wasn't getting much of a prio and time resources to actually implement it. Wonder if we should reopen it.

**Comment by jimharris** [comment]
All patches but one have been merged.  @shuhei-matsumoto could you take a look at the comment on https://review.spdk.io/gerrit/c/spdk/spdk/+/10397?

**Comment by shuhei-matsumoto** [comment]
@jsoref @jimharris @tomzawadzki

Will you check my reply on https://review.spdk.io/gerrit/c/spdk/spdk/+/10397?

**Comment by jsoref** [comment]
@shuhei-matsumoto: reading through it now.

**Comment by shuhei-matsumoto** [comment]
Hi @jsoref 

Thanks for the quick update! I'm sorry but the term "stream" was bad. Will you take a look at my reply again?

**Comment by changpe1** [comment]
@jsoref thanks for all the spelling fixes, all patches are merged, closing it now.
