### ISSUE TITLE
SPDK_ZEROCOPY did not work for IPV6

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2257]
# Bug report

When we use SPDK_ZEROCOPY for IPV6, _sock_check_zcopy() outputs WARNLOG Unexpected cmsg level or type! and did not work.

## Expected Behavior

SPDK_ZEROCOPY should work for IPV6.

## Current Behavior

The above

## Possible Solution

https://review.spdk.io/gerrit/c/spdk/spdk/+/10428

## Steps to Reproduce

Enable SPDK_ZEROCOPY in IPV6 environment.

## Context (Environment including OS version, SPDK version, etc.)

Latest SPDK master

**Comment by tomzawadzki** [comment]
Fix https://review.spdk.io/gerrit/c/spdk/spdk/+/10428 has been merged. Issue can be closed.
