### ISSUE TITLE
[nvmf_filesystem_no_incapsule] nvme connect failed to the SPDK NVMe-oF target

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2259]
# CI Intermittent Failure

>>00:03:00.800  [2021-11-25 06:52:26.567474] Starting SPDK v22.01-pre git sha1 867a9ee73 / DPDK 21.08.0 initialization...
00:03:00.800  [2021-11-25 06:52:26.567517] [ DPDK EAL parameters: [2021-11-25 06:52:26.567523] nvmf [2021-11-25 06:52:26.567527] -c 0xF [2021-11-25 06:52:26.567531] --log-level=lib.eal:6 [2021-11-25 06:52:26.567535] --log-level=lib.cryptodev:5 [2021-11-25 06:52:26.567539] --log-level=user1:6 [2021-11-25 06:52:26.567542] --base-virtaddr=0x200000000000 [2021-11-25 06:52:26.567546] --match-allocations [2021-11-25 06:52:26.567550] --file-prefix=spdk0 [2021-11-25 06:52:26.567554] --proc-type=auto [2021-11-25 06:52:26.567557] ]
00:03:00.822  EAL: No free 2048 kB hugepages reported on node 1
00:03:00.822  EAL: No available 1048576 kB hugepages reported
00:03:00.825  TELEMETRY: No legacy callbacks, legacy socket not created
00:03:00.853  [2021-11-25 06:52:26.620098] app.c: 543:spdk_app_start: *NOTICE*: Total cores available: 4
00:03:00.996  [2021-11-25 06:52:26.763377] app.c: 389:app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
00:03:00.996  [2021-11-25 06:52:26.763435] app.c: 390:app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
00:03:00.996  [2021-11-25 06:52:26.763442] app.c: 395:app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
00:03:00.997  [2021-11-25 06:52:26.763560] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 1
00:03:00.997  [2021-11-25 06:52:26.763641] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 2
00:03:00.997  [2021-11-25 06:52:26.763761] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
00:03:00.997  [2021-11-25 06:52:26.763761] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 3
00:03:00.997  [2021-11-25 06:52:26.763836] accel_engine.c:1012:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
00:03:01.541   06:52:27	-- common/autotest_common.sh@731 -- # xtrace_enable
00:03:01.541   06:52:27	-- common/autotest_common.sh@732 -- # (( i == 0 ))
00:03:01.541   06:52:27	-- common/autotest_common.sh@736 -- # return 0
00:03:01.541   06:52:27	-- nvmf/common.sh@450 -- # timing_exit start_nvmf_tgt
00:03:01.542   06:52:27	-- common/autotest_common.sh@603 -- # xtrace_disable
00:03:01.542   06:52:27	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:01.542   06:52:27	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:03:01.542   06:52:27	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:03:01.542   06:52:27	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:01.543   06:52:27	-- common/autotest_common.sh@19 -- # set +x
00:03:01.569   06:52:27	-- common/autotest_common.sh@605 -- # xtrace_enable
00:03:01.570   06:52:27	-- target/filesystem.sh@49 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_transport -t rdma -u 8192 -c 0
00:03:01.711  [2021-11-25 06:52:27.478116] rdma.c:2432:nvmf_rdma_create: *NOTICE*: Adjusting the io unit size to fit the device's maximum I/O size. New I/O unit size 45056
00:03:01.779   06:52:27	-- target/filesystem.sh@50 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py bdev_malloc_create 64 512 -b Malloc1
00:03:01.908  Malloc1
00:03:01.927   06:52:27	-- target/filesystem.sh@51 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
00:03:02.072   06:52:27	-- target/filesystem.sh@52 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:03:02.212   06:52:27	-- target/filesystem.sh@53 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.211.11.93 -s 4420
00:03:02.333  [2021-11-25 06:52:28.099672] rdma.c:2650:nvmf_rdma_listen: *NOTICE*: *** NVMe/RDMA Target Listening on 10.211.11.93 port 4420 ***
00:03:02.357   06:52:28	-- target/filesystem.sh@55 -- # nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 10.211.11.93 -s 4420
00:03:03.386  [2021-11-25 06:52:29.152891] rdma.c: 876:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 1
00:03:03.386  [2021-11-25 06:52:29.152928] rdma.c: 651:nvmf_rdma_dump_qpair_contents: *ERROR*: Dumping contents of queue pair (QID 0)
00:03:03.386  [2021-11-25 06:52:29.152936] rdma.c: 637:nvmf_rdma_dump_request: *ERROR*: 		Request Data From Pool: 1
00:03:03.386  [2021-11-25 06:52:29.152941] rdma.c: 639:nvmf_rdma_dump_request: *ERROR*: 		Request opcode: 127
00:03:03.386  [2021-11-25 06:52:29.152945] rdma.c: 642:nvmf_rdma_dump_request: *ERROR*: 		Request recv wr_id139939430451376
00:04:03.227  Failed to write to /dev/nvme-fabrics: Input/output error
00:04:03.228    06:53:28	-- target/filesystem.sh@55 -- # trap - ERR
00:04:03.228    06:53:28	-- target/filesystem.sh@55 -- # print_backtrace
00:04:03.228    06:53:28	-- common/autotest_common.sh@993 -- # [[ ehxBET =~ e ]]
00:04:03.229    06:53:28	-- common/autotest_common.sh@995 -- # args=("${BASH_ARGV[@]}")
00:04:03.229    06:53:28	-- common/autotest_common.sh@995 -- # local args
00:04:03.229    06:53:28	-- common/autotest_common.sh@997 -- # xtrace_disable
00:04:03.230    06:53:28	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:04:03.230    06:53:28	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:04:03.230    06:53:28	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:04:03.230    06:53:28	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:04:03.231    06:53:28	-- common/autotest_common.sh@19 -- # set +x
00:04:03.231  ========== Backtrace start: ==========
00:04:03.231  
00:04:03.239  in test/nvmf/target/filesystem.sh:55 -> nvmf_filesystem_part(["0"])
00:04:03.239       ...
00:04:03.239     50  		$rpc_py bdev_malloc_create $MALLOC_BDEV_SIZE $MALLOC_BLOCK_SIZE -b Malloc1
00:04:03.239     51  		$rpc_py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s $NVMF_SERIAL
00:04:03.239     52  		$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
00:04:03.239     53  		$rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT
00:04:03.239     54  	
00:04:03.239  => 55  		nvme connect -t $TEST_TRANSPORT -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:04:03.239     56  	
00:04:03.239     57  		waitforserial "$NVMF_SERIAL"
00:04:03.239     58  		nvme_name=$(lsblk -l -o NAME,SERIAL | grep -oP "([\w]*)(?=\s+${NVMF_SERIAL})")
00:04:03.239     59  	
00:04:03.239     60  		mkdir -p /mnt/device
00:04:03.239       ...
00:04:03.247  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:965 -> run_test(["nvmf_filesystem_no_incapsule"],["nvmf_filesystem_part"],["0"])
00:04:03.247       ...
00:04:03.247     960 		timing_enter $test_name
00:04:03.247     961 		echo "************************************"
00:04:03.247     962 		echo "START TEST $test_name"
00:04:03.247     963 		echo "************************************"
00:04:03.247     964 		xtrace_restore
00:04:03.247  => 965 		time "$@"
00:04:03.247     966 		xtrace_disable
00:04:03.247     967 		echo "************************************"
00:04:03.247     968 		echo "END TEST $test_name"
00:04:03.247     969 		echo "************************************"
00:04:03.247     970 		timing_exit $test_name
00:04:03.247       ...
00:04:03.255  in test/nvmf/target/filesystem.sh:89 -> main(["--transport=rdma"])
00:04:03.255       ...
00:04:03.255     84  	
00:04:03.255     85  		killprocess $nvmfpid
00:04:03.255     86  		nvmfpid=
00:04:03.255     87  	}
00:04:03.255     88  	
00:04:03.255  => 89  	run_test "nvmf_filesystem_no_incapsule" nvmf_filesystem_part 0
00:04:03.255     90  	run_test "nvmf_filesystem_incapsule" nvmf_filesystem_part 4096
00:04:03.255     91  	
00:04:03.255     92  	nvmftestfini
00:04:03.255       ...
00:04:03.255  
00:04:03.255  ========== Backtrace end ==========

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_62521.html

## Execution failed at

See above

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62521.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_62510.html

**Comment by mikeBashStuff** [comment]
Both reports point at the WFP15 node which was improperly configured in the CI pool (phy-nvmf tests should not be scheduled on it due to lack of proper hardware) - this was fixed couple of days ago. Let's leave this issue open for couple more days just in case somebody else's patches got hit by it.

**Comment by tomzawadzki** [comment]
No new reports after fixing configuration in WFP15.
