### ISSUE TITLE
[iscsi]End-to-end resize failed

### ISSUE THREAD

**Issue by ye1xchen** [spdk/spdk#2260]
# Bug report

End-to-end resize failed

## Expected Behavior

 resize iscsi null bdev in target A,  the bdev in target B resize successfully.

## Current Behavior

resize iscsi null bdev target A , but the bdev in target B dose not change.

## Steps to Reproduce

1.target A:
./build/bin/iscsi_tgt &
./scripts/rpc.py iscsi_create_portal_group 1 192.168.20.11:3260
./scripts/rpc.py iscsi_create_initiator_group 1 ANY 192.168.20.12
./scripts/rpc.py  bdev_null_create null0 1024 512
./scripts/rpc.py iscsi_create_target_node iqn.2016-06.io.spdk:disk1 disk1-alias "null0:0" "1:1" 64

2.target B:
~~iscsiadm -m discovery -t sendtargets -p 192.168.20.11:3260~~
~~iscsiadm -m node --login -p  192.168.20.11:3260~~
./build/bin/vhost -S /var/tmp -s 1024 -m 0x3 &
./scripts/rpc.py bdev_iscsi_create -b iSCSI0 -i iqn.2016-06.io.spdk:disk1/0 --url iscsi://192.168.20.11/iqn.2016-06.io.spdk:disk1/0
./scripts/rpc.py vhost_create_blk_controller --cpumask 0x2 vhost.1 iSCSI0
taskset -c 2,3 qemu-system-x86_64 \
  --enable-kvm \
  -cpu host -smp 2 \
  -m 1G -object memory-backend-file,id=mem0,size=1G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem0 \
  -drive file=/home/chenye/centos7.01804qcow2.qcow2,if=none,id=disk \
  -device ide-hd,drive=disk,bootindex=0 \
  -chardev socket,id=spdk_vhost_blk0,path=/var/tmp/vhost.1 \
  -device vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=4 \
  -net user,hostfwd=tcp::10020-:22 -net nic \
  -vnc 0.0.0.0:0 --enable-kvm

ssh -p 10020 root@localhost
[root@localhost ~]# lsblk 
vda                      1G 
3.target A:
./scripts/rpc.py bdev_null_resize null0 2048

4.[root@localhost ~]# lsblk 
vda                      1G 

target B:
./scripts/rpc.py bdev_get_bdevs
iSCSI0  size is 1G, not 2G as expected

## Context (Environment including OS version, SPDK version, etc.)
fedora 32
Latest SPDK master

**Comment by Comphix** [comment]
Will take a look at this issue.

**Comment by Comphix** [comment]
As discussed, there are several areas needs the enhancement for the resize operation from iSCSI Target.

1. Take NULL bdev as example, once NULL bdev is resized on the iSCSI Target side, the resize_cb needs to be properly set to "lun->resize_cb" in the SCSI Dev construct
2. Once the resize_cb is there and the resize is triggered, in-operation and finished, needs to update with iSCSI target (so far there is the related handling in vhost-scsi target)
3. Needs to let the iSCSI Host detects the resize operation of LUN on iSCSI Target. Either through the Unit Attention Sense Code or through the Active Polling (may need a new poller)
4. Left shall be same for NVMe Host and iSCSI Host to bump up this Bdev Resize to higher layers

**Comment by Comphix** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11086 created for this change.

**Comment by ye1xchen** [comment]
@Comphix I tried this patch, but the problem still exists. Resize iscsi null bdev in target A, bdev in target B will not change unless vhost is restarted.

**Comment by Comphix** [comment]
Have you run on IOs from target B? The current implementation needs the Read and Write IOs from target B to Target A.

**Comment by ye1xchen** [comment]
@Comphix  After writing IO on target B,  lsblk shows the resized size, but using cmd ' ./scripts/rpc.py bdev_get_bdevs ' iSCSI0's size does  not change.

**Comment by Comphix** [comment]
Thanks ChenYe. Just make sure when using bdev_get_bdevs, have you sent the IO already?

**Comment by ye1xchen** [comment]
yes, before using bdev_get_bdevs, the fio read and write tests are over.

**Comment by ye1xchen** [comment]
Thanks! skip cmd ‘iscsiadm -m discovery -t sendtargets -p 192.168.20.11:3260 && iscsiadm -m node --login -p  192.168.20.11:3260‘, This patch worked.
’

**Comment by Comphix** [comment]
Patch merged and verification passed. Close this issue.
