### ISSUE TITLE
FAQ - bdevperf run different workload on different bdev partition at the same time

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2262]
# Bug report

hello here my scenario
we split one big bdev into 8 split bdevs.
we want to run randwrite zipf workload on one 4x bdevs
we want to run randread workload on other 4x bdevs

how can we do this with current bdevperf?

## Expected Behavior

we can run these mixed workload with bdevperf easily

## Current Behavior

we workaround this by using fio plugin

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Comphix** [comment]
So far I think we could only select one workload for assigned bdevs.

**Comment by jimharris** [comment]
> So far I think we could only select one workload for assigned bdevs.

No, we have config file support for bdevperf which can enable different workloads.  Please see https://spdk.io/doc/bdevperf.html.

**Comment by gaowayne** [comment]
thank you so much Jim and Gang. :)

**Comment by gaowayne** [comment]
@Comphix @jimharris I review the code and also tried fio configuration. I am pretty sure below zipf parameter is not supported in bdevperf fio configuration. But bdevperf command line have -F parameter to support it. can we re-open this issue add zipf parameter into bdevperf fio configuration too?
```
[global]
filename=wsrp0:wsrp1:wsrp2:wsrp3:wsrp4:wsrp5:wsrp6:wsrp7
bs=65536
#bs=4096
iodepth=64


[POR-w]
filename=wsrp0:wsrp1:wsrp2:wsrp3
rw=randwrite
#random_distribution=zipf:1.2
#runtime=1800s


[POR-r]
filename=wsrp4:wsrp5:wsrp6:wsrp7
rw=randread
#random_distribution=zipf:1.2
#runtime=1800s
```

**Comment by jimharris** [comment]
You can still pass the -F parameter on the bdevperf command line to enable zipf and specify a global theta value.

Marking this as a low priority enhancement request.  If for some reason passing the -F option doesn't work, please feel free to submit a patch to add the necessary functionality to the bdevperf job parsing code.

Thanks,

Jim
