### ISSUE TITLE
nvmf_subsystem_remove_listener optional arguments are actually required

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#2265]
From nvmf_subsystem_remove_listener help:

```
./scripts/rpc.py nvmf_subsystem_remove_listener -h
usage: rpc.py [options] nvmf_subsystem_remove_listener [-h] -t TRTYPE -a TRADDR [-p TGT_NAME] [-f ADRFAM] [-s TRSVCID] nqn

positional arguments:
  nqn                   NVMe-oF subsystem NQN

optional arguments:
  -h, --help            show this help message and exit
  -t TRTYPE, --trtype TRTYPE
                        NVMe-oF transport type: e.g., rdma
  -a TRADDR, --traddr TRADDR
                        NVMe-oF transport address: e.g., an ip address
  -p TGT_NAME, --tgt-name TGT_NAME
                        The name of the parent NVMe-oF target (optional)
  -f ADRFAM, --adrfam ADRFAM
                        NVMe-oF transport adrfam: e.g., ipv4, ipv6, ib, fc, intra_host
  -s TRSVCID, --trsvcid TRSVCID
                        NVMe-oF transport service id: e.g., a port number
```

-t TRTYPE and -a TRADDR are required (correctly displayed in second line), but described as optional.

Also this will fail:

`./scripts/rpc.py nvmf_subsystem_remove_listener -t TCP -a 192.168.0.1 nqn.2016-06.io.spdk:cnode1`

because `spdk_nvme_transport_id_compare()` in `nvmf_subsystem_find_listener()` will fail when searching for transport if `-s TRSVCID` argument is not present.

Tested with TCP transport type.

**Comment by yidong0635** [comment]
This should be a document edit fault.

**Comment by yidong0635** [comment]
python command ArgumentParser puts these required items list in optional arguments.

**Comment by ksztyber** [comment]
I agree with @yidong0635, this is how the python's argparse module works and I don't think there's much we can do about it, other than what @yidong0635 suggested. But I'd be a bit hesitant to change it, as it could break a lot of existing scripts.

As for `trsvcid`, it is indeed required by TCP, but some of the transports don't use this field (e.g. FC). So, for them it doesn't make sense to specify it, so I don't think we can make it a required argument.

**Comment by yidong0635** [comment]
Thanks @ksztyber for  your further explanation, @Maciej-Szwed  what's your idea？

**Comment by Maciej-Szwed** [comment]
In such case I would just add in description to the '-s TRSVCID' flag something like that: ... (required for TCP and RDMA transport types).

**Comment by yidong0635** [comment]
if you no mind adding https://review.spdk.io/gerrit/c/spdk/spdk/+/10580, please let me know if it needs more.

**Comment by Maciej-Szwed** [comment]
One small comment on gerrit. Overall looks good - thanks :)

**Comment by yidong0635** [comment]
@Maciej-Szwed  updated, thanks for your idea.
