### ISSUE TITLE
[NVMf] Removing subsystem with active namespace leaves block device on initiator side

### ISSUE THREAD

**Issue by Maciej-Szwed** [spdk/spdk#2266]
When removing subsystem with active namespace we end up with block device on initiator side still present. Tested with kernel and SPDK initiators.

Steps to reproduce:
```
build/bin/spdk_tgt
scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 192.168.0.1 -s 4420
```
a) For kernel initiator:
```
nvme connect -t tcp -n "nqn.2016-06.io.spdk:cnode1" -a 192.168.0.1 -s 4420
scripts/rpc.py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
lsblk 
(device still present)
```
b) For SPDK initiator:
```
build/bin/spdk_tgt -r /var/tmp/spdk.sock2
scripts/rpc.py -s /var/tmp/spdk.sock2 bdev_nvme_attach_controller -b Nvme0 -t tcp -a 192.168.0.1 -f ipv4 -s 4420 -n nqn.2016-06.io.spdk:cnode1
scripts/rpc.py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode1
scripts/rpc.py -s /var/tmp/spdk.sock2 bdev_get_bdevs
(device still present)
```

Suggesting to block subsystem removal when active namespace are present.

**Comment by ksztyber** [comment]
@Maciej-Szwed not sure why having a namespace should change the behavior in this case. With the kernel initiator you should be able to specify the controller loss timeout via the `-l` option:
```
  [  --ctrl-loss-tmo=<NUM>, -l <NUM> ]  --- controller loss timeout period in
                                            seconds
```
This will cause the controller to be removed from the system after that time.

For the SPDK initiator, I can see that it tries to constantly reset the controller in a loop. Perhaps we could add a similar option to SPDK too?

**Comment by jimharris** [comment]
> @Maciej-Szwed not sure why having a namespace should change the behavior in this case. With the kernel initiator you should be able to specify the controller loss timeout via the `-l` option:
> 
> ```
>   [  --ctrl-loss-tmo=<NUM>, -l <NUM> ]  --- controller loss timeout period in
>                                             seconds
> ```
> 
> This will cause the controller to be removed from the system after that time.
> 
> For the SPDK initiator, I can see that it tries to constantly reset the controller in a loop. Perhaps we could add a similar option to SPDK too?

I think @shuhei-matsumoto has plans to add something like this to the bdev/nvme module.

**Comment by shuhei-matsumoto** [comment]
Yes, I'm adding a similar option path_loss_timeout_sec to the SPDK initiator in the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/10128
Still testing and being reviewed but looks working as expected so far.

**Comment by shuhei-matsumoto** [comment]
The kernel initiator have other options, --max-retries, --fast-io-fail-tmo and --reconnect-delay. --fast-io-fail-tmo has been used via a famous multipath driver DM-multipath. The SPDK initiator supports a similar option for --max-retries now, and will support similar options for --fast-io-fail-tmo and --reconnect-delay in my remaining patch series.
Currently I'm working on mainly now is to reduce I/O down time during path failover.

**Comment by Maciej-Szwed** [comment]
OK, so I think we can close this one as I was not aware of this ongoing work.
