### ISSUE TITLE
core dump with poll group on SPDK nvme initiator

### ISSUE THREAD

**Issue by dashan8020** [spdk/spdk#2269]
# Bug report
A core dump occasionally happen when use poll group in SPDK nvme initiator (over RDMA)

## Expected Behavior
No core dump happen.

## Current Behavior
the core dump stack is as below, the SPDK version is v21.01.x, because I added some debug logs to debug such issue, so the call stack line number may be different from the standard SPDK v21.01.x.  libibverbs version on my setup is 16.9-3.3.1, my kernel version is linux-4.12.14-95

Core dump:
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007fcc8ad07af2 in ibv_poll_cq (wc=0x7fcc73ff5a20, num_entries=1, num_entries@entry=128, cq=0x7fcc685ba9d0)
    at /usr/include/infiniband/verbs.h:2055
#1  nvme_rdma_cq_process_completions (cq=0x7fcc685ba9d0, batch_size=batch_size@entry=1, group=group@entry=0x7fcc685b9ac0,
    rdma_qpair=rdma_qpair@entry=0x0) at nvme_rdma.c:2072
#2  0x00007fcc8ad082d1 in nvme_rdma_poll_group_process_completions (tgroup=0x7fcc685b9ac0,
    completions_per_qpair=<optimized out>, disconnected_qpair_cb=<optimized out>) at nvme_rdma.c:2602
#3  0x00007fcc8acf9935 in nvme_transport_poll_group_process_completions (tgroup=tgroup@entry=0x7fcc685b9ac0,
    completions_per_qpair=completions_per_qpair@entry=0,
    disconnected_qpair_cb=disconnected_qpair_cb@entry=0x4ddf50 <nfevent::NvmePollingGroupHandle::DisconnectedQpairCb(spdk_nvme_qpair*, void*)>) at nvme_transport.c:537
#4  0x00007fcc8ad03d42 in spdk_nvme_poll_group_process_completions (group=<optimized out>, completions_per_qpair=0,
    disconnected_qpair_cb=0x4ddf50 <DisconnectedQpairCb(spdk_nvme_qpair*, void*)>)
    at nvme_poll_group.c:127

## Steps to Reproduce
The issue appear not frequently, so may be not easy to reproduce.
When it appear, the RDMA connection not stable because some test.

1.To cut off RDMA connection when system work well 
2.
3.
4.

**Comment by changpe1** [comment]
Did you unplug the cable while the IO was running for your case?

**Comment by jimharris** [comment]
> Did you unplug the cable while the IO was running for your case?

Hi @dashan8020,

Please add much more detail on how this issue can be reproduced.  For example, what kind of workload is being run on the connection, how do you "cut off RDMA connection", etc.

**Comment by dashan8020** [comment]
please ignore the issue, it should be my mistake, I will close it. sorry.
