### ISSUE TITLE
[ubuntu18-vg-autotest] Guest-specific operations were attempted on a machine that is not ready for guest communication

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2270]
# CI Intermittent Failure

During [ubuntu18-vg-autotest] a notification has been printed:

```
00:01:36.852  Guest-specific operations were attempted on a machine that is not
00:01:36.852  ready for guest communication. This should not happen and a bug
00:01:36.852  should be reported.
```

and the test exited with failed status.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_63155.html

## Execution failed at

00:00:38.608  ==> default: Creating shared folders metadata...
00:00:38.608  ==> default: Starting domain.
00:00:39.992  ==> default: Waiting for domain to get an IP address...
00:01:01.971  ==> default: Waiting for SSH to become available...
00:01:10.115  ==> default: Configuring and enabling network interfaces...
_**00:01:36.852  Guest-specific operations were attempted on a machine that is not
00:01:36.852  ready for guest communication. This should not happen and a bug
00:01:36.852  should be reported.**_
00:01:36.852  + cd ubuntu1804-libvirt
00:01:36.852  + vagrant destroy -f
00:01:36.852  ==> default: Removing domain...
00:01:36.869  [Pipeline] }
00:01:36.885  [Pipeline] // stage
00:01:36.898  [Pipeline] }
00:01:36.903  ERROR: script returned exit code 1
00:01:36.916  [Pipeline] // catchError
00:01:36.931  [Pipeline] stage
00:01:36.934  [Pipeline] { (Epilogue)
00:01:36.952  [Pipeline] sh
00:01:37.241  + mv ubuntu1804-libvirt/output output
00:01:37.258  [Pipeline] sh

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_63155.html

**Comment by tomzawadzki** [comment]
[Bug scrub] This failure is vagrant/infrastructure related. Since it occurred just once over period of week, closing.
