### ISSUE TITLE
[rpmbuild]run rpmbuild/rpm.sh failed

### ISSUE THREAD

**Issue by ye1xchen** [spdk/spdk#2272]
# Bug report

run rpmbuild/rpm.sh failed

## Expected Behavior

run rpmbuild/rpm.sh passed

## Current Behavior

run rpmbuild/rpm.sh failed
error: File not found: /root/rpmbuild/buildroot/spdk-v21.10-1.x86_64/usr/local/lib/lib*.so

run rpmbuild/rpm.sh --with-shared passed

## Steps to Reproduce

1. cd spdk
2. rpmbuild/rpm.sh
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
fedora 32
Latest SPDK master

**Comment by mikeBashStuff** [comment]
Regression introduced by 6317642ce6296d078aeabe88e17c467d4173c5df. Potential fix here https://review.spdk.io/gerrit/c/spdk/spdk/+/10591 - @ye1xchen would you kindly test this patch to see if it works on your end?

**Comment by ye1xchen** [comment]
Thanks! This patch worked.

**Comment by mikeBashStuff** [comment]
@ye1xchen Appreciate the feedback, thanks. :) Patch got merged, so closing this issue.
