### ISSUE TITLE
vm hang when using kata containers (qemu + spdk + vhost-user-blk-pci driver)

### ISSUE THREAD

**Issue by shuochen0311** [spdk/spdk#2276]
# Bug report
You can check this link for more detail: [here](https://github.com/kata-containers/kata-containers/issues/3249)

we are trying to use kata container to create a vm along with spdk block device.
The way that kata works is:
* create a qemu process(a qemu vm) with some default memory cpu resources.
* hotplug the spdk device with vhost-user-blk-pci driver as well as the extra memory that container requires.

From our kubernetes pod spec, kata will hotplug 5G memories after sandbox getting created and then hotplug the vhost-user block device.

The way that we created the device is:
```
        mkdir -p /var/run/kata-containers/vhost-user/block/devices
        mkdir -p /var/run/kata-containers/vhost-user/block/sockets

        /spdk_deploy/build/bin/spdk_tgt -S /var/run/kata-containers/vhost-user/block/sockets/ -m [7] -L all&
        sleep 2
        /spdk_deploy/scripts/rpc.py bdev_aio_create /dev/kata aio0
        /spdk_deploy/scripts/rpc.py vhost_create_blk_controller vhostblk0 aio0
        mknod /var/run/kata-containers/vhost-user/block/devices/vhostblk0 b 241 0
```
We can see the kata starts hot plugging the device and then later the qemu vm hangs. We can not login to the vm and the pod creating process is also getting stuck. We are here to asking some advice how to debug it.

The detail logs from spdk is pasted in the [kata github issue](https://github.com/kata-containers/kata-containers/issues/3249).

## Expected Behavior

vm can hot plug the device succesfully and pod runs normally.

## Current Behavior

qemu vm hangs and we are asking to root cause the issue.

## Possible Solution

unknown

## Steps to Reproduce

we currently don't have a easy reproduce only with interacting with spdk and qemu, since we use kata conntainer to reproduce it. The detail reproduction is here at[ kata github issue link.](https://github.com/kata-containers/kata-containers/issues/3249)

## Context (Environment including OS version, SPDK version, etc.)

We use spdk v21.10 and qemu 6.1.0

**Comment by changpe1** [comment]
@shuochen0311 You need to narrow down this issue to reproduce it with QEMU + SPDK only, we don't know the usage model in Kata.

**Comment by shuochen0311** [comment]
Thanks! I am trying to narrow it down.

**Comment by fengwang666** [comment]
@changpe1 We were able to narrow down the issue to qemu hot plug memory. It seems this issues happens only when we try to hotplug more memory into qemu through qmp.

**Comment by changpe1** [comment]
> @changpe1 We were able to narrow down the issue to qemu hot plug memory. It seems this issues happens only when we try to hotplug more memory into qemu through qmp.

Yeah, I think that's the problem.  SPDK vhost is always tested with pre-allocated memory, we didn't test this case in practice, I will take a look first.

**Comment by changpe1** [comment]
@fengwang666 I tested it today, the memory hotplug can work correctly with QEMU + SPDK Vhost-blk.
