### ISSUE TITLE
[nvme cuse] Incorrect response from nvme cli

### ISSUE THREAD

**Issue by ahribeng** [spdk/spdk#2278]
# Bug report

The "create-ns" command in nvme cli is not returning the nsid.

## Expected Behavior
The create-ns command should return a valid nsid if the command was succesfull.
nvme create-ns /dev/spdk/nvme0 -c 1 -d 0 -f 0 -m 0 -s 1 -t 50000000
create-ns: Success, created **nsid:1**

## Current Behavior
Currently nsid will always be 0.
nvme create-ns /dev/spdk/nvme0 -c 1 -d 0 -f 0 -m 0 -s 1 -t 50000000
create-ns: Success, created **nsid:0**

Looking at this deeper it seems the nvme cli function is relying on nsid to be in the result field of the nvme_admin_cmd struct. Currently in nvme_cuse.c(cuse_nvme_passthru_cmd_send) the result field is only populated if data_transfer portion of the opcode is set to 10b (controller to host). The namespace managment command is host to controller but the spec specifies that upon a create request the nsid will be populated in cdw0 of the completion entry.

```
int nvme_ns_create(int fd, __u64 nsze, __u64 ncap, __u8 flbas, __u8 dps,
		__u8 nmic, __u32 anagrpid, __u16 nvmsetid, __u8 csi,
		__u32 timeout, __u32 *result)
{
	struct nvme_id_ns ns = {
		.nsze		= cpu_to_le64(nsze),
		.ncap		= cpu_to_le64(ncap),
		.flbas		= flbas,
		.dps		= dps,
		.nmic		= nmic,
		.anagrpid	= anagrpid,
		.nvmsetid	= nvmsetid,
	};

	struct nvme_admin_cmd cmd = {
		.opcode		= nvme_admin_ns_mgmt,
		.addr		= (__u64)(uintptr_t) ((void *)&ns),
		.cdw10		= 0,
		.cdw11		= csi << 24,
		.data_len	= 0x1000,
		.timeout_ms	= timeout,
	};
	int err;

	err = nvme_submit_admin_passthru(fd, &cmd);
	if (!err && result)
		*result = cmd.result;
	return err;
}
```
## Possible Solution
I think it might be ok to always set the result field of the admin_cmd to cdw0 of the completion queue. Either it will be some dummy reserved bits or the command specific info. I have pushed a RFC patch for reference as to what that may look like. Alternatively, maybe namespace management command is treated as a unique case.

Experimental Patch: [https://review.spdk.io/gerrit/c/spdk/spdk/+/10633](https://review.spdk.io/gerrit/c/spdk/spdk/+/10633)

## Steps to Reproduce

1. Setup cuse
2. Delete Current Namespace : nvme admin-passthru /dev/spdk/nvme0 -t 99999999 --cdw10=0x1 -o 0x0d -n 1
3. Create a Namespace: nvme create-ns /dev/spdk/nvme0 -c 1 -d 0 -f 0 -m 0 -s 1 -t 50000000
4. Check output of create-ns

## Context (Environment including OS version, SPDK version, etc.)

OS: RHEL 7.6
Kernel: 5.4.6
SPDK: 21.07

**Comment by jimharris** [comment]
Thanks @ahribeng!  I posted a few comments on the patch.  @tomzawadzki could you take a closer look at the CUSE specifics?

**Comment by ahribeng** [comment]
@jimharris, Would we want to modify test\nvme\cuse\nvme_ns_manage_cuse.sh to parse stdout of create-ns to find the nsid or is that creating fragility in the test by relying on nvme cli output?

**Comment by jimharris** [comment]
> @jimharris, Would we want to modify test\nvme\cuse\nvme_ns_manage_cuse.sh to parse stdout of create-ns to find the nsid or is that creating fragility in the test by relying on nvme cli output?

I think that's a fantastic idea.  I'm not especially worried about the nvme cli output format changing, and even if it did I'm guessing we could find a way to parse both an old and new format.

Do you want to take a shot at either updating your existing patch to add that, or adding a second patch to do it?

**Comment by ahribeng** [comment]
> > @jimharris, Would we want to modify test\nvme\cuse\nvme_ns_manage_cuse.sh to parse stdout of create-ns to find the nsid or is that creating fragility in the test by relying on nvme cli output?
> 
> I think that's a fantastic idea. I'm not especially worried about the nvme cli output format changing, and even if it did I'm guessing we could find a way to parse both an old and new format.
> 
> Do you want to take a shot at either updating your existing patch to add that, or adding a second patch to do it?

Yea I will push up a change for that.

**Comment by ahribeng** [comment]
@jimharris, Updated the commit to include testing changes. Didn't seem like an unrelated change so I used the same commit. Let me know if the community prefers them split up. 

https://review.spdk.io/gerrit/c/spdk/spdk/+/10633/3/test/nvme/cuse/nvme_ns_manage_cuse.sh

**Comment by jimharris** [comment]
Patch merged - thanks @ahribeng!
