### ISSUE TITLE
[vhost_boot] Could not access KVM kernel module

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2280]
Looks like qemu failed, because the kvm kernel module was missing:
```
00:03:35.876  INFO: running /root/vhost_test/vms/0/run.sh
00:03:35.876   17:52:47	-- vhost/common.sh@865 -- # /root/vhost_test/vms/0/run.sh
00:03:35.876  Running VM in /root/vhost_test/vms/0
00:03:36.821  VHOST_CONFIG: new vhost user connection is 182
00:03:36.821  VHOST_CONFIG: new device, handle is 0
00:03:36.821  VHOST_CONFIG: vhost peer closed
00:03:36.821  Waiting for QEMU pid file
00:03:38.739  ERROR: no qemu pid file found
00:03:38.739  === qemu.log ===
00:03:38.739  Could not access KVM kernel module: No such file or directory
00:03:38.739  qemu-system-x86_64: failed to initialize kvm: No such file or directory
00:03:38.739  === qemu.log ===
```
Info on the machine the test was executed:
```
00:00:48.762  ** START ** Info for Hostname: spdk-WFP-17
00:00:48.762   17:50:00	-- spdk/autobuild.sh@318 -- $ uname -a
00:00:48.762  Linux spdk-WFP-17 5.12.10-200.fc33.x86_64 #1 SMP Thu Jun 10 14:19:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/63664/archive/vhost-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_63664.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_63664.html

**Comment by mikeBashStuff** [comment]
WFP17 seems to be a new box in the pool and from the look of it VT|VT-d is not enabled in the BIOS. Removed it from the pool  until it's properly set up.

**Comment by wawryk** [comment]
Virtualization enabled on WFP17, added back to CI.

**Comment by tomzawadzki** [comment]
[Bug scrub] WFP17 configuration is now fixed.

**Comment by karlatec** [comment]
@wawryk Could you please check the same thing on WFP18? 
https://10.211.11.56:8080/job/vfio-user-integration-autotest/29/consoleFull

**Comment by wawryk** [comment]
I forgot to reply here.
WFP18 was configured 7 days ago with WFP17 and log attached above was before I configured machines.
