### ISSUE TITLE
vfio-user compiling failed with error "PCI_CFG_SPACE_SIZE/PCI_CFG_SPACE_EXP_SIZE undecleared..", when linux kernel version is 4.9.x

### ISSUE THREAD

**Issue by Apokleos** [spdk/spdk#2282]
# Bug report

vfio-user compiling failed with error "PCI_CFG_SPACE_SIZE/PCI_CFG_SPACE_EXP_SIZE undecleared..", when linux kernel version is 4.9.x

## Expected Behavior

compiled ok

## Current Behavior

```
spdk/libvfio-user/include/pci_defs.h:187:21: error: ‘PCI_CFG_SPACE_SIZE’ undeclared here (not in a function)
         uint8_t raw[PCI_CFG_SPACE_SIZE];
...
spdk/libvfio-user/lib/pci.c:473:16: error: ‘PCI_CFG_SPACE_EXP_SIZE’ undeclared (first use in this function)
         size = PCI_CFG_SPACE_EXP_SIZE;
```

## Possible Solution

add checking of kernel versioin into the header fie `spdk/libvfio-user/include/pci_defs.h` 

```
...
#include <linux/version.h>
...

#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 10, 0)
#define PCI_CFG_SPACE_SIZE 	256
#define PCI_CFG_SPACE_EXP_SIZE	4096
#endif
...
```

## Steps to Reproduce
```
# git clone https://github.com/spdk/spdk
# cd spdk
# git submodule update --init
# ./scripts/pkgdep.sh
# ./configure --enable-debug --with-vfio-user
# make -j$(nproc)
```

## Context (Environment including OS version, SPDK version, etc.)
```
1. OS version
# uname -a
Linux localhost.localdomain 4.9.151-xxx
2. SPDK 
# git log
commit 050565e5abeb1073d8777a329df385598b1a8953
```

**Comment by changpe1** [comment]
Thanks, here is the fix patch https://review.spdk.io/gerrit/c/spdk/spdk/+/10691

**Comment by changpe1** [comment]
patch has been merged, closing it now.

**Comment by Apokleos** [comment]
@changpe1 Thanks Changpeng. 
I have tested it with the version `commit 2af48ebf5847a5588cf516040b6c0059ddf290c8`, it seems that the bugfix doesn't work and with the same errors.

**Comment by changpe1** [comment]
You may use `git submodule update` to update your submodule first.

**Comment by Apokleos** [comment]
> 
Hi,@Changpeng, I have cloned a new one and do `git submodule update`, got the same error.
So, I think the bugfix doesn't work. 
And I have tested libvfio-user(`master 17769cf fix coverity issues`), got the similar error.

**Comment by changpe1** [comment]
I see, I suggest to submit an issue to https://github.com/nutanix/libvfio-user, SPDK removed direct use of `PCI_CFG_SPACE_SIZE/PCI_CFG_SPACE_EXP_SIZE`.
