### ISSUE TITLE
missing library rt in spdk_trace.pc  

### ISSUE THREAD

**Issue by winglq** [spdk/spdk#2283]
# Bug report

spdk_trace use shm_open/close functions, but spdk_trace.pc only require following link libraries:

```bash
PKG_CONFIG_PATH=./build/lib/pkgconfig/ pkg-config --libs   ./build/lib/pkgconfig/spdk_trace.pc
-L/home/qing/Projects/spdk/build/lib -lspdk_trace -lspdk_rpc -lspdk_jsonrpc -lspdk_json -lspdk_util -lspdk_log
```

uuid should be added to spdk_util.pc, as it use uuid_copy/compare functions.

```bash
PKG_CONFIG_PATH=./build/lib/pkgconfig/ pkg-config --libs   ./build/lib/pkgconfig/spdk_util.pc
-L/home/qing/Projects/spdk/build/lib -lspdk_util -lspdk_log
```

## expected behavior

rt library shoud be added to Requires in spdk_trace.pc
uuid library shoud be added to Requires in spdk_util.pc

**Comment by jimharris** [comment]
Hi @winglq,

You need to also include spdk_syslibs if linking with static libraries.  This will pull in both rt and uuid.  https://github.com/spdk/spdk/blob/master/doc/pkgconfig.md explains this in more detail.

Regards,

Jim
