### ISSUE TITLE
[nvmf_fuzz]llvm_nvme_fuzz help doesn't show -D option usage

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2286]
# Bug report
llvm_nvme_fuzz help doesn't show -D option usage

## Expected Behavior
llvm_nvme_fuzz help should show -D option usage

## Current Behavior
llvm_nvme_fuzz help doesn't show -D option usage

## Possible Solution
Add -D option usage

## Steps to Reproduce
1. yum install clang
2. yum install llvm 
3. cd <path_to_spdk>
3. CC=clang-12 CXX=clang++-12 ./configure --with-fuzzer=/usr/lib64/clang/12/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a
4. make -j
5.  cd /test/app/fuzz/llvm_nvme_fuzz
6.  ./llvm_nvme_fuzz --help
./llvm_nvme_fuzz [options]
options:
 -c, --config <config>     JSON config file (default none)
     --json <config>       JSON config file (default none)
     --json-ignore-init-errors
                           don't exit on invalid config entry
 -d, --limit-coredump      do not set max coredump size to RLIM_INFINITY
 -g, --single-file-segments
                           force creating just one hugetlbfs file
 -h, --help                show this usage
 -i, --shm-id <id>         shared memory ID (optional)
 -m, --cpumask <mask or list>    core mask (like 0xF) or core list of '[]' embraced (like [0,1,10]) for DPDK
 -n, --mem-channels <num>  channel number of memory channels used for DPDK
 -p, --main-core <id>      main (primary) core for DPDK
 -r, --rpc-socket <path>   RPC listen address (default /var/tmp/spdk.sock)
 -s, --mem-size <size>     memory size in MB for DPDK (default: 0MB)
     --silence-noticelog   disable notice level logging to stderr
 -u, --no-pci              disable PCI access
     --wait-for-rpc        wait for RPCs to initialize subsystems
     --max-delay <num>     maximum reactor delay (in microseconds)
 -B, --pci-blocked <bdf>
                           pci addr to block (can be used more than once)
 -R, --huge-unlink         unlink huge files after initialization
 -v, --version             print SPDK version
 -A, --pci-allowed <bdf>
                           pci addr to allow (-B and -A cannot be used at the same time)
     --huge-dir <path>     use a specific hugetlbfs mount to reserve memory from
     --iova-mode <pa/va>   set IOVA mode ('pa' for IOVA_PA and 'va' for IOVA_VA)
     --base-virtaddr <addr>      the base virtual address for DPDK (default: 0x200000000000)
     --num-trace-entries <num>   number of trace entries for each core, must be power of 2, setting 0 to disable trace (default 32768)
     --env-context         Opaque context for use of the env implementation
 -L, --logflag <flag>    enable log flag (all, accel, accel_ioat, aio, app_config, app_rpc, bdev, bdev_ftl, bdev_malloc, bdev_null, bdev_nvme, bdev_raid, bdev_raid0, blob, blob_rw, blobfs, blobfs_bdev, blobfs_bdev_rpc, blobfs_rw, ftl_core, ftl_init, gpt_parse, ioat, json_util, log, log_rpc, lvol, lvol_rpc, notify_rpc, nvme, nvmf, nvmf_tcp, opal, reactor, rpc, rpc_client, sock, thread, trace, vbdev_delay, vbdev_gpt, vbdev_lvol, vbdev_opal, vbdev_passthru, vbdev_split, vbdev_zone_block, virtio, virtio_blk, virtio_dev, virtio_pci, virtio_user, vmd)
 -e, --tpoint-group-mask <mask>
                           tracepoint group mask for spdk trace buffers (default 0x0, bdev 0x8, nvmf_tcp 0x20, blobfs 0x80, thread 0x400, nvme_pcie 0x800, all 0xffff)
 -F                        Transport ID for subsystem that should be fuzzed.
 -t                        Time to run fuzz tests (in seconds). Default: 10
 -Z                        Fuzzer to run (0 to 1)

## Context (Environment including OS version, SPDK version, etc.)
N/A

**Comment by changpe1** [comment]
Thanks @wanqunintel.  Here is the patch to fix it, https://review.spdk.io/gerrit/c/spdk/spdk/+/10814

**Comment by wanqunintel** [comment]
verified and now we can see this -D option now.
 -D                        Path of corpus directory.
 -F                        Transport ID for subsystem that should be fuzzed.
 -t                        Time to run fuzz tests (in seconds). Default: 10
 -Z                        Fuzzer to run (0 to 1)
