### ISSUE TITLE
[nvmf_fuzz]run test/nvmf/target/llvm_nvme_fuzz.sh --time=3000 --fuzzer=0 fail

### ISSUE THREAD

**Issue by ye1xchen** [spdk/spdk#2287]
# Bug report

run test/nvmf/target/llvm_nvme_fuzz.sh --time=3000 --fuzzer=0  
*ERROR*: Set Features - Invalid Namespace ID

## Expected Behavior

run test/nvmf/target/llvm_nvme_fuzz.sh --time=3000 --fuzzer=0 without errors

## Current Behavior

run test/nvmf/target/llvm_nvme_fuzz.sh --time=3000 --fuzzer=0  
#10254  NEW    cov: 1406 ft: 2906 corp: 268/16Kb lim: 320 exec/s: 4 rss: 486Mb L: 12/320 MS: 5 PersAutoDict-ChangeBinInt-ChangeBinInt-ShuffleBytes-ChangeBinInt- DE: "\xff\x03\x00\x00\x00\x00\x00\x00"-
[2021-12-21 20:02:20.809198] ctrlr.c:1604:nvmf_ctrlr_get_features_reservation_notification_mask: *ERROR*: Set Features - Invalid Namespace ID

## Steps to Reproduce

1.yum install clang
2.yum install llvm
3.cd spdk
4.CC=clang-12 CXX=clang++-12 ./configure --with-fuzzer=/usr/lib64/clang/12/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a
5.make -j
6.test/nvmf/target/llvm_nvme_fuzz.sh --time=3000 --fuzzer=0

## Context (Environment including OS version, SPDK version, etc.)
fedora 32
Latest SPDK master

**Comment by changpe1** [comment]
@ye1xchen this is the purpose for fuzz tests, fuzzer will try all kinds of different input and NVMf target will return error for some cases.

**Comment by ye1xchen** [comment]
@changpe1 thanks, I'm not familiar with this, if that so, I will close this issue.
