### ISSUE TITLE
[llvm_nvme_fuzz]spdk_nvmf_transport_create: *ERROR*: Unable to allocate buffer pool for poll group

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2288]
# Bug report
llvm_nvme_fuzz test with spdk_nvmf_transport_create: *ERROR*: Unable to allocate buffer pool for poll group

## Current Behavior
llvm_nvme_fuzz test with spdk_nvmf_transport_create: *ERROR*: Unable to allocate buffer pool for poll group

## Steps to Reproduce
1. ./test/nvmf/target/llvm_nvme_fuzz.sh --time=60000 --fuzzer=0
during the running time, it will report the following errors
_* Found test storage at /home/qwan/spdk/test/nvmf/target
  19:23:04      -- common/autotest_common.sh@1496 -- # xtrace_enable
 19:23:04       -- target/llvm_nvme_fuzz.sh@20 -- # trap 'process_shm --id 0; exit 1' SIGINT SIGTERM EXIT
 19:23:04       -- target/llvm_nvme_fuzz.sh@22 -- # mkdir -p /tmp/corpus0
 19:23:04       -- target/llvm_nvme_fuzz.sh@23 -- # trid='trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420'
 19:23:04       -- target/llvm_nvme_fuzz.sh@25 -- # /home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F 'trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420' -c /home/qwan/spdk/test/nvmf/target/fuzz_json.conf -t 60000 -D /tmp/corpus0 -Z 0
[2021-12-22 19:23:04.845795] Starting SPDK v22.01-pre git sha1 54efe6552 / DPDK 21.08.0 initialization...
[2021-12-22 19:23:04.845999] [ DPDK EAL parameters: [2021-12-22 19:23:04.846025] nvme_fuzz [2021-12-22 19:23:04.846044] -c 0x1 [2021-12-22 19:23:04.846061] --log-level=lib.eal:6 [2021-12-22 19:23:04.846078] --log-level=lib.cryptodev:5 [2021-12-22 19:23:04.846097] --log-level=user1:6 [2021-12-22 19:23:04.846115] --base-virtaddr=0x200000000000 [2021-12-22 19:23:04.846132] --match-allocations [2021-12-22 19:23:04.846151] --file-prefix=spdk0 [2021-12-22 19:23:04.846296] --proc-type=auto [2021-12-22 19:23:04.846319] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2021-12-22 19:23:04.969901] app.c: 562:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-12-22 19:23:05.091900] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
[2021-12-22 19:23:05.159307] accel_engine.c: 563:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-12-22 19:23:05.270219] tcp.c: 587:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2021-12-22 19:23:05.270247] transport.c: 260:spdk_nvmf_transport_create: *ERROR*: Unable to allocate buffer pool for poll group
[2021-12-22 19:23:05.270254] nvmf_rpc.c:2044:rpc_nvmf_create_transport: *ERROR*: Transport type 'TCP' create failed
[2021-12-22 19:23:05.286428] json_config.c: 221:rpc_client_poller: *ERROR*: error response:
{
  "code": -32603,
  "message": "Transport type 'TCP' create failed"
}
[2021-12-22 19:23:05.286504] app.c: 652:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
  19:23:05      -- target/llvm_nvme_fuzz.sh@25 -- # trap - ERR
  19:23:05      -- target/llvm_nvme_fuzz.sh@25 -- # print_backtrace
  19:23:05      -- common/autotest_common.sh@990 -- # [[ ehxBET =~ e ]]
  19:23:05      -- common/autotest_common.sh@992 -- # args=('--fuzzer=0' '--time=60000')
  19:23:05      -- common/autotest_common.sh@992 -- # local args
  19:23:05      -- common/autotest_common.sh@994 -- # xtrace_disable
  19:23:05      -- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
  19:23:05      -- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
  19:23:05      -- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
  19:23:05      -- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
  19:23:05      -- common/autotest_common.sh@19 -- # set +x
========== Backtrace start: ==========

in ./test/nvmf/target/llvm_nvme_fuzz.sh:25 -> main(["--time=60000"],["--fuzzer=0"])
     ...
   20   trap 'process_shm --id 0; exit 1' SIGINT SIGTERM EXIT
   21
   22   mkdir -p /tmp/corpus$FUZZER
   23   trid="trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420"
   24
=> 25   $rootdir/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F "$trid" -c $testdir/fuzz_json.conf -t $TIME -D /tmp/corpus$FUZZER -Z $FUZZER
   26
   27   trap - SIGINT SIGTERM EXIT
     ...

========== Backtrace end ==========
  19:23:05      -- common/autotest_common.sh@1030 -- # xtrace_enable
  19:23:05      -- common/autotest_common.sh@1031 -- # return 0
 19:23:05       -- target/llvm_nvme_fuzz.sh@1 -- # process_shm --id 0
 19:23:05       -- common/autotest_common.sh@681 -- # type=--id
 19:23:05       -- common/autotest_common.sh@682 -- # id=0
 19:23:05       -- common/autotest_common.sh@683 -- # '[' --id = --pid ']'
  19:23:05      -- common/autotest_common.sh@687 -- # find /dev/shm -name '*.0' -printf '%f\n'
 19:23:05       -- common/autotest_common.sh@687 -- # shm_files='nvme_fuzz_trace.0
nvmf_trace.0'
 19:23:05       -- common/autotest_common.sh@689 -- # [[ -z nvme_fuzz_trace.0
nvmf_trace.0 ]]
 19:23:05       -- common/autotest_common.sh@693 -- # for n in $shm_files
 19:23:05       -- common/autotest_common.sh@694 -- # tar -C /dev/shm/ -cvzf /home/qwan/spdk/../output/nvme_fuzz_trace.0_shm.tar.gz nvme_fuzz_trace.0
nvme_fuzz_trace.0
#26253  REDUCE cov: 1453 ft: 2991 corp: 280/15443b lim: 320 exec/s: 4 rss: 804Mb L: 146/320 MS: 1 InsertByte-
 19:23:06       -- common/autotest_common.sh@693 -- # for n in $shm_files
 19:23:06       -- common/autotest_common.sh@694 -- # tar -C /dev/shm/ -cvzf /home/qwan/spdk/../output/nvmf_trace.0_shm.tar.gz nvmf_trace.0
nvmf_trace.0
 19:23:07       -- common/autotest_common.sh@696 -- # return 0
 19:23:07       -- target/llvm_nvme_fuzz.sh@1 -- # exit 1_

## Context (Environment including OS version, SPDK version, etc.)
This is long time test, i didn't capture when this error happens, but it happens after a while during the fuzz test. Will keep monitoring when this happens.

**Comment by changpe1** [comment]
NVMf uses dynamic controller model for TCP transport and we will do connect/disconnect in client for llvm fuzz test, so each new connection is one new controller with new CNTLID, the memory will be exhausted in NVMf target, so the tests can't run long time.

**Comment by changpe1** [comment]
we can connect the nvmf target before the fuzz test, and then disconnect it after fuzz test, I will fix it in this way.

**Comment by changpe1** [comment]
Here is the patch to fix it, https://review.spdk.io/gerrit/c/spdk/spdk/+/10863

**Comment by benlwalker** [comment]
Are we leaving ourselves open to DDoS with this behavior? I'm not worried about an intentional attack so much as an initiator bug reconnecting repeatedly that blocks anyone else from being able to connect. Maybe instead, if we detect that the number of controllers has hit some low threshold, new connections attempt to force garbage collect old controllers that no one is connected to?

**Comment by jimharris** [comment]
> Here is the patch to fix it, https://review.spdk.io/gerrit/c/spdk/spdk/+/10863

@wanqunintel, @changpe1 - I'm concerned that we are looking at the wrong problem here.

The output that Anna posted shows the failure happening immediately after starting the llvm_nvme_fuzz application.  It fails when creating the transport.  So I don't think this is related to connecting and disconnecting from the target for each iteration of fuzz data.

I think it is useful to connect and disconnect for each iteration of fuzz data.  This will allow us to potentially fuzz connect parameters in the future.  It always polls the detach context before returning from the TestOneInput function, so we shouldn't have a lot of association timers outstanding.  But I still don't think the association timers are the problem here - Anna's test is failing before we even get a chance to make any connections.

**Comment by wanqunintel** [comment]
@jimharris I have tried to run llvm_nvme_fuzz for 10 times, and the issue persist, tried to reproduce the issue with the generated crash file with following command `./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -D /tmp/corpus0 -F "trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420" -t 6000 -Z 0 ./crash-583c01ebaf8aa847d2a2afb673c09e6c5dd50df1`, it prints log as attached
[fuzz0 6000s crash file.txt](https://github.com/spdk/spdk/files/7879073/fuzz0.6000s.crash.file.txt)

**Comment by changpe1** [comment]
> @jimharris I have tried to run llvm_nvme_fuzz for 10 times, and the issue persist, tried to reproduce the issue with the generated crash file with following command `./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -D /tmp/corpus0 -F "trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420" -t 6000 -Z 0 ./crash-583c01ebaf8aa847d2a2afb673c09e6c5dd50df1`, it prints log as attached [fuzz0 6000s crash file.txt](https://github.com/spdk/spdk/files/7879073/fuzz0.6000s.crash.file.txt)

The error messages here should belong to #2289.

**Comment by wanqunintel** [comment]
oh, apologize, log error messages should belong to #2289, i have updated on the issue #2289.

**Comment by jimharris** [comment]
@wanqunintel - I think this issue can be closed.  Can you confirm?

**Comment by wanqunintel** [comment]
@jimharris , sorry for late, yes, let's close it.

**Comment by GitHubGDong** [comment]
hello~ I was packaging and writing the spdk.spec file and it had a problem during the build.log Test phase "Test storage is not available".
In the test phase, is test/unit/unittest.sh enough? Do you need any other parameters ?

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.k6JyIY
+ umask 022
+ cd /builddir/build/BUILD
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/OpenCloudOS/OpenCloudOS-hardened-cc1 -fstack-protector-strong  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/OpenCloudOS/OpenCloudOS-hardened-cc1 -fstack-protector-strong  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/OpenCloudOS/OpenCloudOS-hardened-cc1 -fstack-protector-strong  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/OpenCloudOS/OpenCloudOS-hardened-cc1 -fstack-protector-strong  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/OpenCloudOS/OpenCloudOS-hardened-ld  -Wl,--build-id=sha1'
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ cd spdk-23.01
+ test/unit/unittest.sh
+++ dirname test/unit/unittest.sh
++ readlink -f test/unit
+ testdir=/builddir/build/BUILD/spdk-23.01/test/unit
+++ dirname test/unit/unittest.sh
++ readlink -f test/unit/../..
+ rootdir=/builddir/build/BUILD/spdk-23.01
+ source /builddir/build/BUILD/spdk-23.01/test/common/autotest_common.sh
++ rpc_py=rpc_cmd
++ xtrace_disable
++ '[' '' '!=' yes ']'
++ PREV_BASH_OPTS=ehxB
++ [[ ehxB == *\x* ]]
++ XTRACE_DISABLED=yes
++ set +x
* Looking for test storage...
* Test storage is not available
error: Bad exit status from /var/tmp/rpm-tmp.k6JyIY (%check)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.k6JyIY (%check)
Child return code was: 1
```
