### ISSUE TITLE
[llvm_nvme_fuzz]nvme_tcp_qpair_connect_sock: *ERROR*: sock connection error of t qpair=0x7fc3af3a1a10 with addr=127.0.0.1, port=4420

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2289]
# Bug report
llvm_nvme_fuzz test with nvme_tcp_qpair_connect_sock: *ERROR*: sock connection error of t qpair=0x7fc3af3a1a10 with addr=127.0.0.1, port=4420

## Current Behavior
llvm_nvme_fuzz test with nvme_tcp_qpair_connect_sock: *ERROR*: sock connection error of t qpair=0x7fc3af3a1a10 with addr=127.0.0.1, port=4420

## Steps to Reproduce
1../test/nvmf/target/llvm_nvme_fuzz.sh --time=60000 --fuzzer=1
_#28048 REDUCE cov: 1380 ft: 2820 corp: 244/2278b lim: 30 exec/s: 4 rss: 842Mb L: 12/30 MS: 2 ChangeByte-Eras eBytes-
[2021-12-21 23:45:33.314740] posix.c: 507:posix_sock_create: *ERROR*: connect() failed, errno = 99
[2021-12-21 23:45:33.315155] nvme_tcp.c:1924:nvme_tcp_qpair_connect_sock: *ERROR*: sock connection error of t qpair=0x7fc3af3a1a10 with addr=127.0.0.1, port=4420
[2021-12-21 23:45:33.315173] nvme_tcp.c:2113:nvme_tcp_ctrlr_construct: *ERROR*: failed to create admin qpair
[2021-12-21 23:45:33.315180] nvme.c: 705:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for S SD: 127.0.0.1
[2021-12-21 23:45:33.315186] nvme.c: 838:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2021-12-21 23:45:33.315191] nvme.c:1020:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed for transport address '127.0.0.1'
[2021-12-21 23:45:33.315197] app.c: 652:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==424887==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x0000000005b8 (pc 0x7fc3e7d29474 bp 0x7 fc3dd8d2040 sp 0x7fc3dd8d1fd8 T424891)
==424887==The signal is caused by a READ memory access.
==424887==Hint: address points to the zero page.
#0 0x7fc3e7d29474 in pthread_mutex_lock (/lib64/libpthread.so.0+0xb474)
#1 0x51a4aa in nvme_robust_mutex_lock /home/qwan/spdk/lib/nvme/./nvme_internal.h:1082:11
#2 0x51a4aa in spdk_nvme_ctrlr_cmd_admin_raw /home/qwan/spdk/lib/nvme/nvme_ctrlr_cmd.c:122:2
#3 0x460765 in run_cmds /home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:141:8
#4 0x460765 in TestOneInput /home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:167:2
#5 0x6a8ea9 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/qwan/spdk/test /app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6a8ea9)
#6 0x6a9a10 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool , bool*) (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6a9a10)
#7 0x6aab23 in fuzzer::Fuzzer::MutateAndTestOne() (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme _fuzz+0x6aab23)
#8 0x6ac617 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::Sized File> >&) (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6ac617)
#9 0x69167a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/q wan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x69167a)
#10 0x46060e in start_fuzzer /home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:207:2
#11 0x7fc3e7d27298 in start_thread (/lib64/libpthread.so.0+0x9298)
#12 0x7fc3e7c34352 in clone (/lib64/libc.so.6+0x100352)

UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: SEGV (/lib64/libpthread.so.0+0xb474) in pthread_mutex_lock
==424887==ABORTING
MS: 5 CrossOver-ChangeBinInt-EraseBytes-ChangeBit-ChangeBit-; base unit: 67cf3fd457fb09aff2253d5d80283bb520c7 8dea
0xb7,0xf7,0xf7,0xf7,0xf6,0xf7,0xf7,0x2,0x4a,0x31,0xf7,0xf7,0xf7,0xa,
\xb7\xf7\xf7\xf7\xf6\xf7\xf7\x02J1\xf7\xf7\xf7\x0a
artifact_prefix='./'; Test unit written to ./crash-c3b7369300a3898e294a11ffcb47bff9796a37dd
Base64: t/f39/b39wJKMff39wo=
==424887== ERROR: libFuzzer: deadly signal
#0 0x45fb1e in __sanitizer_print_stack_trace (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz +0x45fb1e)
#1 0x6c7c19 in fuzzer::PrintStackTrace() (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6 c7c19)
#2 0x6a8976 in fuzzer::Fuzzer::CrashCallback() (.part.0) (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/ll vm_nvme_fuzz+0x6a8976)
#3 0x6a8a3b in fuzzer::Fuzzer::StaticCrashSignalCallback() (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/ llvm_nvme_fuzz+0x6a8a3b)
#4 0x7fc3e7d31a1f (/lib64/libpthread.so.0+0x13a1f)
#5 0x7fc3e7b712a1 in raise (/lib64/libc.so.6+0x3d2a1)
#6 0x7fc3e7b5a8a3 in abort (/lib64/libc.so.6+0x268a3)
#7 0x44e4fe in __sanitizer::Abort() (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x44e4fe )
#8 0x44c43b in __sanitizer::Die() (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x44c43b)
#9 0x4584c4 in __sanitizer::HandleDeadlySignal(void*, void*, unsigned int, void (*)(__sanitizer::SignalCo ntext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) (/home/qwan/spdk/test/app/fuzz/llv m_nvme_fuzz/llvm_nvme_fuzz+0x4584c4)
#10 0x7fc3e7d31a1f (/lib64/libpthread.so.0+0x13a1f)
#11 0x7fc3e7d29473 in pthread_mutex_lock (/lib64/libpthread.so.0+0xb473)
#12 0x51a4aa in nvme_robust_mutex_lock /home/qwan/spdk/lib/nvme/./nvme_internal.h:1082:11
#13 0x51a4aa in spdk_nvme_ctrlr_cmd_admin_raw /home/qwan/spdk/lib/nvme/nvme_ctrlr_cmd.c:122:2
#14 0x460765 in run_cmds /home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:141:8
#15 0x460765 in TestOneInput /home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:167:2
#16 0x6a8ea9 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/qwan/spdk/tes t/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6a8ea9)
#17 0x6a9a10 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, boo l, bool*) (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6a9a10)
#18 0x6aab23 in fuzzer::Fuzzer::MutateAndTestOne() (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvm e_fuzz+0x6aab23)
#19 0x6ac617 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::Size dFile> >&) (/home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6ac617)
#20 0x69167a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/ qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x69167a)
#21 0x46060e in start_fuzzer /home/qwan/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:207:2
#22 0x7fc3e7d27298 in start_thread (/lib64/libpthread.so.0+0x9298)
#23 0x7fc3e7c34352 in clone (/lib64/libc.so.6+0x100352)

NOTE: libFuzzer has rudimentary signal handlers.
Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 5 CrossOver-ChangeBinInt-EraseBytes-ChangeBit-ChangeBit-; base unit: 67cf3fd457fb09aff2253d5d80283bb520c7 8dea
0xb7,0xf7,0xf7,0xf7,0xf6,0xf7,0xf7,0x2,0x4a,0x31,0xf7,0xf7,0xf7,0xa,
\xb7\xf7\xf7\xf7\xf6\xf7\xf7\x02J1\xf7\xf7\xf7\x0a
artifact_prefix='./'; Test unit written to ./crash-c3b7369300a3898e294a11ffcb47bff9796a37dd
Base64: t/f39/b39wJKMff39wo=
23:45:33 -- ./llvm_nvme_fuzz.sh@25 -- # trap - ERR
23:45:33 -- ./llvm_nvme_fuzz.sh@25 -- # print_backtrace
23:45:33 -- common/autotest_common.sh@990 -- # [[ ehxBET =~ e ]]
23:45:33 -- common/autotest_common.sh@992 -- # args=('--fuzzer=1' '--time=60000')
23:45:33 -- common/autotest_common.sh@992 -- # local args
23:45:33 -- common/autotest_common.sh@994 -- # xtrace_disable
23:45:33 -- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
23:45:33 -- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
23:45:33 -- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
23:45:33 -- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
23:45:33 -- common/autotest_common.sh@19 -- # set +x
========== Backtrace start: ==========

in ./llvm_nvme_fuzz.sh:25 -> main(["--time=60000"],["--fuzzer=1"])
...
20 trap 'process_shm --id 0; exit 1' SIGINT SIGTERM EXIT
21
22 mkdir -p /tmp/corpus$FUZZER
23 trid="trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420"
24
=> 25 $rootdir/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F "$trid" -c $testdir/fuzz_json.con f -t $TIME -D /tmp/corpus$FUZZER -Z $FUZZER
26
27 trap - SIGINT SIGTERM EXIT_

## Context (Environment including OS version, SPDK version, etc.)
This is long time test, i didn't capture when this error happens, but it happens after a while during the fuzz test. Will keep monitoring when this happens.

**Comment by changpe1** [comment]
Can you have another try with patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11133? thanks.

**Comment by wanqunintel** [comment]
@changpe1 thank you for the update, i have verified with this patch and rerun the tests, it now passed.

**Comment by changpe1** [comment]
patch has been merged, closing it now.
