### ISSUE TITLE
Unable to modify a subsystem in nvmf target via RPC

### ISSUE THREAD

**Issue by aneeeshp3** [spdk/spdk#229]
Hi,
  I am trying to configure nvmf target using rpc.py script. I could run construct_nvmf_subsystem RPC method and create a subsystem containing some namespaces. However I don`t see any options to modify a subsystem after constructing it. It would be useful if a namespaces can be added or removed from a nvmf subsystem without affecting the existing namespaces.
  Is this feature already available? Is there any development in progress related to this?

**Comment by benlwalker** [comment]
The feature is currently being developed. Work on NVMe-oF dynamic configuration is being tracked on this Trello board: https://trello.com/b/G2f3dVcs/nvme-of

**Comment by aneeeshp3** [comment]
Thank you Ben. Is there any timeline in mind as to when these features will be part of mainstream?

**Comment by benlwalker** [comment]
I have a few patches out already that start to add some of the necessary RPCs, and all of them should go in over the next two weeks more or less. I'm only available to work on this for the next two weeks, so if something hasn't been added after that point please either note it here, or even better, submit a patch to add it!

**Comment by h170** [comment]
Hi Ben,
For the trello task named 'Implement NVMe namespace management emulation', I'm not too certain what it means, but my thought was it would allow online creation or deletion of namespaces? Thanks

**Comment by dverkamp-intel** [comment]
I believe this issue is resolved since we now have RPC methods to modify NVMe-oF target subsystems at runtime (add/remove of namespaces, allowed hosts, and listen addresses).  Please see http://www.spdk.io/doc/jsonrpc.html#jsonrpc_components_nvmf_tgt for additional docs.

If other RPC methods are needed, please open a new issue with details.
