### ISSUE TITLE
Intermittent CI failures

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2293]
Looks like lots of patches failed on the CI yesterday (Dec 21st) because of various issues: either builds were timing out, or not starting at all (`logs have not been generated`). It should already be resolved, but opening this issue in case it reappears and to have something to point the failures on gerrit.
```
...
lvol-vg-autotest #1206						|   |   |   | Aborted | 0:31:45s
nvme-cmb-pmr-vg-autotest #1769					|   |   |   | Pass | 0:25:44s
nvme-phy-autotest #897						|   |   |   | Pass | 0:29:48s
nvme-vg-autotest #1211						|   |   |   | Aborted | 0:32:18s
nvmf-phy-autotest #892						|   |   |   | Aborted | 0:29:04s
nvmf-tcp-phy-autotest #892					|   |   |   | Pass | 0:28:18s
nvmf-tcp-uring-vg-autotest #1207				|   |   |   | Pass | 0:26:49s
nvmf-tcp-vg-autotest #1207 - logs have not been generated	|   |   |   | Test Failure | 0:05:46s
nvmf-vg-autotest #1208						|   |   |   | Aborted | 0:31:59s
...
```

## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_64301.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_64301.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_64306.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_64286.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_64296.html

**Comment by ksztyber** [comment]
Two weeks have passed and no similar failures occurred, so closing the issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80364.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_83971.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_83968.html
