### ISSUE TITLE
nvmf/rdma: not all spdk memory needs to be registered to rdma memory region

### ISSUE THREAD

**Issue by jiewei-ke** [spdk/spdk#2302]
# Bug report

When using nvmf/rdma together with ioat, it takes a long time to create rdma transport, e.g. about 1 min in my testbed with 4 rdma nics and 700GB pmem.

The ioat engine needs to call spdk_mem_register() to register the whole pmem memory to spdk. While for nvmf/rdma, spdk_rdma_create_mem_map() will register all memory to the rdma memory region unconditionally. The ibv_reg_mr() call with 700G size is obviously non-negligible.

## Expected Behavior

Only rdma related memory needs to be registered to the MR.

## Current Behavior

spdk_rdma_create_mem_map() will register all memory to the rdma memory region unconditionally.

## Possible Solution

Maybe we can distinguish spdk memory for usage, but it seems a big change.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
Are you saying that for your 700GiB pmem memory region, you only want to access them via IOAT, the RDMA NICs will not access them, so they don't need to be registered to RDMA memory region?

If so, currently SPDK doesn't have a good idea to address this issue.  We don't have different types of memory region now.

**Comment by jiewei-ke** [comment]
Yes. Could we add some other API to let users choose which memory regions need to be registered to the RDMA memory region?

**Comment by changpe1** [comment]
Maybe you can add a new callback in `spdk_mem_map_ops`, e.g: filter_cb to allow user to define the rule which memory region is allowed to register.

SPDK's default policy is to allow every memory region, then you may need to rewrite your own filter rule.

**Comment by jiewei-ke** [comment]
Thanks @changpe1 for your suggestion.

A simple workaround for me to speed up the `spdk_rdma_create_mem_map() ` is to skip those huge-size memory regions. But maybe we need a better way. 

We may add filter_cb in `spdk_mem_map_ops` and user can pass the filter_cb by `struct spdk_nvme_rdma_hooks`. But it's hard for user to write the filtering rule since not all spdk memory is registered by the user. Some may be registered by other spdk internal components and the user won't be aware of it, so the user cannot filter them out.

In my mind, only the buffers used for RDMA transmission are needed to register RDMA MR, including the message headers and read/write buffers, which are mainly allocated and registered by the nvmf/rdma components. Is it correct? Can we just register these buffers into RDMA MR? If other components want to transfer by RDMA NICs, they have the duty to register RDMA MR themselves.

**Comment by changpe1** [comment]
that's true. @AlekseyMarchuk any comments about this issue?

**Comment by benlwalker** [comment]
The reason we have historically registered everything is that we support zero copy sending in nvmf/rdma. The data buffer is provided by the bdev in that case, so rather than having each individual bdev decide to register it's memory with RDMA, we just registered everything.

We could move away from this model by maybe having a flag on the allocation calls or the memory registration calls.
