### ISSUE TITLE
PCI hotplug surprise removal causes system to crash

### ISSUE THREAD

**Issue by raman-singh** [spdk/spdk#231]
On a Linux (Centos7) system running SPDK with NVME drive connected, hotplug removal of the NVME device causes host system to crash and reboot. Hotplug add of the NVME drive seems to work fine.

The issue occurs in SPDK 17.10.1 as well as in master branch.

**Comment by jimharris** [comment]
Hi,

Can you provide more details please?


1)       Kernel version

2)       Using uio_pci_generic or vfio-pci

3)       Which application are you running when you remove the NVMe device?

4)       If #3 is a target application such as iSCSI or NVMe-oF, are you removing the device during I/O or is it idle?

Any other details you can add will help the community narrow down the problem.

Thanks,

-Jim

**Comment by raman-singh** [comment]
Hi Jim,

1) Kernel version is 3.10
2) Using uio_pci_generic or vfio-pci  - uio_pci_generic
3) Which application are you running when you remove the NVMe device? - Only SPDK is running as an NVMEoF target
4) If #3 is a target application such as iSCSI or NVMe-oF, are you removing the device during I/O or is it idle? - Removing the device when it is idle is enough to cause the issue.

On further debug, we found this bug fix related to uio_release() in this kernel version.
 https://bugzilla.redhat.com/show_bug.cgi?id=1430225

Will try with updated kernel and let you know.

Thanks
Raman

**Comment by raman-singh** [comment]
We are not able to reproduce the issue on updating to the kernel having fix for above mentioned  uio_release() crash. 
Closing this issue. Thanks.

**Comment by jimharris** [comment]
Thanks @baruch for the heads-up.

**Comment by ak-gh** [comment]
I'm still seeing this on a pretty modern kernel (ubuntu 18.04.2, kernel 4.15). Any idea if the above fix has been merged into the kernel and/or other suggestions?

Thanks,
Andrey

Jun  9 02:17:49 kernel: [587473.878509] nvme nvme0: pci function 0000:84:00.0
Jun  9 02:17:49 kernel: [587473.909184] nvme nvme1: pci function 0000:85:00.0
Jun  9 02:17:49 kernel: [587473.940255] nvme nvme2: pci function 0000:86:00.0
Jun  9 02:17:51 kernel: [587475.608230] BUG: unable to handle kernel paging request at 00000001003e022b
Jun  9 02:17:51 kernel: [587475.608259] IP: uio_release+0x20/0x60 [uio]
Jun  9 02:17:51 kernel: [587475.608272] PGD 0 P4D 0 
Jun  9 02:17:51 kernel: [587475.608284] Oops: 0000 [#1] SMP PTI
Jun  9 02:17:51 kernel: [587475.608296] Modules linked in: uio_pci_generic uio binfmt_misc ipmi_ssif intel_rapl sb_edac shpchp x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass lpc_ich dcdbas ipmi_si ipmi_devintf mei_me mei intel_cstate mac_hid acpi_power_meter intel_rapl_perf ipmi_msghandler tcp_bbr sch_fq sunrpc ib_iser rdma_cm iw_cm ib_cm ib_core iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi ip_tables x_tables autofs4 btrfs zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear mgag200 ttm drm_kms_helper syscopyarea crct10dif_pclmul igb sysfillrect ixgbe crc32_pclmul sysimgblt ghash_clmulni_intel qla2xxx fb_sys_fops pcbc dca i2c_algo_bit aesni_intel aes_x86_64 nvme_fc crypto_simd nvme glue_helper nvme_fabrics
Jun  9 02:17:51 kernel: [587475.608494]  ptp ahci drm mxm_wmi cryptd nvme_core pps_core megaraid_sas libahci scsi_transport_fc mdio wmi
Jun  9 02:17:51 kernel: [587475.608526] CPU: 0 PID: 28814 Comm: reactor_0 Not tainted 4.15.0-39-generic #42-Ubuntu
Jun  9 02:17:51 kernel: [587475.608546] Hardware name: Dell Inc. PowerEdge R630/02C2CP, BIOS 2.8.0 005/17/2018
Jun  9 02:17:51 kernel: [587475.608567] RIP: 0010:uio_release+0x20/0x60 [uio]
Jun  9 02:17:51 kernel: [587475.608581] RSP: 0000:ffffacc109d7fc48 EFLAGS: 00010286
Jun  9 02:17:51 kernel: [587475.608596] RAX: ffffffffc09d54a0 RBX: ffff8a82389268c0 RCX: ffff8a823baa0f20
Jun  9 02:17:51 kernel: [587475.608615] RDX: ffff8a92364f93e0 RSI: ffff8a8203e67100 RDI: 00000001003e0003
Jun  9 02:17:51 kernel: [587475.608634] RBP: ffffacc109d7fc60 R08: 0000000000000000 R09: 0000000000000000
Jun  9 02:17:51 kernel: [587475.608654] R10: ffff8a92364f93e0 R11: ffff8a8203e67110 R12: ffff8a92090efb18
Jun  9 02:17:51 kernel: [587475.608672] R13: ffff8a92364f93e0 R14: ffff8a823baa0f20 R15: ffff8a9233482540
Jun  9 02:17:51 kernel: [587475.608692] FS:  0000000000000000(0000) GS:ffff8a823f600000(0000) knlGS:0000000000000000
Jun  9 02:17:51 kernel: [587475.608712] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jun  9 02:17:51 kernel: [587475.608728] CR2: 00000001003e022b CR3: 00000005dba0a002 CR4: 00000000003606f0
Jun  9 02:17:51 kernel: [587475.608747] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Jun  9 02:17:51 kernel: [587475.608765] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Jun  9 02:17:51 kernel: [587475.608783] Call Trace:
Jun  9 02:17:51 kernel: [587475.608796]  __fput+0xea/0x220
Jun  9 02:17:51 kernel: [587475.608807]  ____fput+0xe/0x10
Jun  9 02:17:51 kernel: [587475.608819]  task_work_run+0x9d/0xc0
Jun  9 02:17:51 kernel: [587475.608832]  do_exit+0x2ec/0xb40
Jun  9 02:17:51 kernel: [587475.608843]  do_group_exit+0x43/0xb0
Jun  9 02:17:51 kernel: [587475.608856]  get_signal+0x27b/0x590
Jun  9 02:17:51 kernel: [587475.608869]  do_signal+0x37/0x730
Jun  9 02:17:51 kernel: [587475.608882]  ? _copy_to_user+0x26/0x30
Jun  9 02:17:51 kernel: [587475.608895]  exit_to_usermode_loop+0x73/0xd0
Jun  9 02:17:51 kernel: [587475.608908]  prepare_exit_to_usermode+0x77/0x80
Jun  9 02:17:51 kernel: [587475.608923]  retint_user+0x8/0x8
Jun  9 02:17:51 kernel: [587475.608934] RIP: 0033:0x563cd230da23
Jun  9 02:17:51 kernel: [587475.608945] RSP: 002b:00007ffe59416b30 EFLAGS: 00000293 ORIG_RAX: ffffffffffffff02
Jun  9 02:17:51 kernel: [587475.608965] RAX: 0000563cd38e1fa0 RBX: 0000000000000000 RCX: 00007ffe59416ae0
Jun  9 02:17:51 kernel: [587475.608983] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000200006c32158
Jun  9 02:17:51 kernel: [587475.609002] RBP: 00007ffe59416b80 R08: 0000000000000000 R09: 0000000080000000
Jun  9 02:17:51 kernel: [587475.609020] R10: 00007ffe594168f0 R11: 0000000000000202 R12: 0000563cd2277db0
Jun  9 02:17:51 kernel: [587475.609039] R13: 00007ffe59416e90 R14: 0000000000000000 R15: 0000000000000000
Jun  9 02:17:51 kernel: [587475.609581] Code: c1 18 e8 f4 71 ab e4 5d c3 66 90 0f 1f 44 00 00 55 48 89 fa 48 89 e5 41 55 41 54 53 48 8b 9e c8 00 00 00 4c 8b 23 49 8b 7c 24 38 <48> 8b 87 28 02 00 00 48 85 c0 74 26 48 89 d6 e8 2c db 42 e5 41 
Jun  9 02:17:51 kernel: [587475.610869] RIP: uio_release+0x20/0x60 [uio] RSP: ffffacc109d7fc48
Jun  9 02:17:51 kernel: [587475.611430] CR2: 00000001003e022b
Jun  9 02:17:51 kernel: [587475.611979] ---[ end trace c389e4af0a222f41 ]---
Jun  9 02:17:51 kernel: [587475.652162] Fixing recursive fault but reboot is needed!
