### ISSUE TITLE
[nvmf_delete_subsystem] Assertion `wc[i].opcode == IBV_WC_SEND' failed.

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#2311]
# CI Intermittent Failure

Somehow we're getting work completions with invalid opcodes all the sudden with RDMA. See discussion at:

https://review.spdk.io/gerrit/c/spdk/spdk/+/10955

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/67151/archive/nvmf-phy-autotest/build.log

**Comment by mikeBashStuff** [comment]
The affected test is different, but in general I think this is a duplicate of #2310 (and there's possible relation with the #2300). But I guess it would be beneficial to keep this open, just for easier identification of the issue for other users.

**Comment by benlwalker** [comment]
Closing this one (duplicate of #2310). I renamed #2310 so it's clearer to find for people searching for the failure.
