### ISSUE TITLE
DSA does not support UIO

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2316]
virt to phy translation doesn't handle crossing 2MB boundary right now.  Use only with VFIO until this support is added.

**Comment by jimharris** [comment]
For now, could we use spdk_iommu_is_enabled() in accel_engine_idxd_init() to ensure we don't even try to use idxd if the iommu is disabled?

**Comment by peluse** [comment]
Great idea, yes I'll get that ready ASAP!

**Comment by peluse** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/11816

**Comment by jimharris** [comment]
Getting the driver merged to enable broader testing was important, even if it was limited to IOMMU enabled.  So tracking this here a bug, even though this limitation was known when merged.

**Comment by peluse** [comment]
Ben has a patch for this: https://review.spdk.io/gerrit/c/spdk/spdk/+/12217
