### ISSUE TITLE
Unable to get the correct AIO ret

### ISSUE THREAD

**Issue by fp208** [spdk/spdk#2325]
# Bug report
read Disk data with bad sector by spdk_bdev_readv_blocks，but unable to get the correct AIO ret by spdk_bdev_io_get_aio_status。
## Expected Behavior
aio_ret = -ENODATA
## Current Behavior
aio_ret = 0

in function：bdev_aio_io_channel_poll：
events[i].res is negative when read Disk with bad sector，but io_result is u64_t ， the condition io_result < MAX_AIO_ERRNO is always false.
## Possible Solution
static int
bdev_aio_io_channel_poll(struct bdev_aio_io_channel *io_ch)
{
	int nr, i = 0;
	struct bdev_aio_task *aio_task;
	struct io_event events[SPDK_AIO_QUEUE_DEPTH];
	uint64_t io_result;

	nr = bdev_user_io_getevents(io_ch->io_ctx, SPDK_AIO_QUEUE_DEPTH, events);

	if (nr < 0) {
		return 0;
	}

#define MAX_AIO_ERRNO 256
	for (i = 0; i < nr; i++) {
		aio_task = events[i].data;
		aio_task->ch->io_inflight--;
		io_result = events[i].res;
		if (io_result == aio_task->len) {
			spdk_bdev_io_complete(spdk_bdev_io_from_ctx(aio_task), SPDK_BDEV_IO_STATUS_SUCCESS);
		} else if ((int)io_result < MAX_AIO_ERRNO) {
			/* Linux AIO will return its errno to io_event.res */
			int aio_errno = io_result;

			spdk_bdev_io_complete_aio_status(spdk_bdev_io_from_ctx(aio_task), aio_errno);
		} else {
			SPDK_ERRLOG("failed to complete aio: requested len is %lu, but completed len is %lu.\n",
				    aio_task->len, io_result);
			spdk_bdev_io_complete(spdk_bdev_io_from_ctx(aio_task), SPDK_BDEV_IO_STATUS_FAILED);
		}
	}

	return nr;
}
## Context (Environment including OS version, SPDK version, etc.)
kernel version：4.10.0+

**Comment by jimharris** [comment]
Hi @dong-liuliu, and update on this issue?

**Comment by dong-liuliu** [comment]
> Hi @dong-liuliu, and update on this issue?
Sorry， I missed it, JIm.

**Comment by dong-liuliu** [comment]
Looked into LInux Kernel source code related to io completions.
Confirmed that negatvie errno will directly passed to "aio_complete_rw" in fs and block modules. And then directly assigned to io_event.res

Patch is raised at https://review.spdk.io/gerrit/c/spdk/spdk/+/12882
