### ISSUE TITLE
nvmf target with 8 subsystem crashed after using ctrl+c to kill it

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#233]
[nvmf-nvme.docx](https://github.com/spdk/spdk/files/1688479/nvmf-nvme.docx)
I have created 8 subsystem, including NVMe and Malloc backend. Please see attached file for the config.
Then I started nvmf target with this config file.
From the host machine, I used nvme command to discover and login to the 8 SPDK nvmf subsystem.
Then I used ctrl+c to kill nvmf target. The nvmf target reported core dump.
SPDK commit ID:
commit ad9b3ef5a558c5acc569c07f5071534cb93f021e 
Author: Hailiang Wang <hailiangx.e.wang@intel.com>
Date:   Thu Dec 7 21:37:12 2017 +0800

    autotest: bdevperf test with gpt(porting from nightly to autotest)

    This patch is used to test bdevperf on one NVMe disk with 2 GPT partition.
The core dump is as below:

(gdb) bt
#0  0x0000000000002410 in ?? ()
#1  0x0000000000431378 in spdk_nvmf_ctrlr_destruct (ctrlr=0x7f1b94096390) at ctrlr.c:134
#2  0x000000000042d839 in spdk_nvmf_subsystem_destroy (subsystem=0x149c540) at subsystem.c:313
#3  0x000000000042e130 in spdk_nvmf_tgt_destroy (tgt=0x1394ba0) at nvmf.c:203
#4  0x0000000000406401 in nvmf_tgt_advance_state (arg1=<optimized out>, arg2=<optimized out>) at nvmf_tgt.c:334
#5  0x0000000000434972 in _spdk_event_queue_run_batch (reactor=0xa58000, reactor=0xa58000) at reactor.c:196
#6  _spdk_reactor_run (arg=0xa58000) at reactor.c:438
#7  0x0000000000434e88 in spdk_reactors_start () at reactor.c:628
#8  0x0000000000433b8c in spdk_app_start (opts=opts@entry=0x7ffd9a3c6890, start_fn=start_fn@entry=0x4063c0 <nvmf_tgt_advance_state>,
    arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:435
#9  0x0000000000406a8c in spdk_nvmf_tgt_start (opts=opts@entry=0x7ffd9a3c6890) at nvmf_tgt.c:356
#10 0x0000000000404d4f in main (argc=3, argv=0x7ffd9a3c69e8) at nvmf_main.c:67

**Comment by dverkamp-intel** [comment]
Hi Liang,

Thanks for the report.

I was able to reproduce this bug (at least I think it's the same crash) with a slight modification to our existing test/nvmf/shutdown/shutdown.sh test: https://review.gerrithub.io/#/c/398251/

When we prepare a patch to fix the bug, this test should be included.

**Comment by liang2yan** [comment]
I have verified this issue with latest codes. I have used the same steps. And I also run the test/nvmf/shutdown/shutdown.sh in https://review.gerrithub.io/#/c/398251/ patch. This issue still can not be reproduced.

**Comment by wanqunintel** [comment]
@liang2yan it seems there is failure on the nightly test, and this patch has been for a while, is it the same issue as the failure in the autotest?

**Comment by liang2yan** [comment]
I have tried to reproduce this issue with latest codes. But it can't be reproduced. I have rebased the shutdown.sh patch. The patch failed but not caused by this issue.
