### ISSUE TITLE
Trace: Unable to activate all traces via 'all' or '0xffff'

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2331]
# Bug report

Recently introduced patch (https://review.spdk.io/gerrit/c/spdk/spdk/+/10431) changed the call from spdk_trace_set_tpoint_group_mask() function to spdk_trace_set_tpoints(), which registers tracepoints only once instead of iterating over all groups. In result 'all' and '0xffff' activate only one tracepoint group.  

## Expected Behavior

All tracepoints should be enabled with 'all' and '0xffff' as trace arguments passed to target.

## Current Behavior

Only a single group is activated.

## Possible Solution

Detect if user specified 'all' or '0xffff' as argument and activate tracepoint differently.

## Steps to Reproduce

1. run SPDK
2. perform some operations on target (example: sudo scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192 - this should invoke THREAD_IOCH_GET tpoints)
3. sudo build/bin/spdk_trace -s nvmf -p `pidof nvmf_tgt` to check recorded tracepoints

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 20.04 LTS, branch: master (with a69541fc3118c0d406bf0e51aaa19c7534ee5576 on top)

**Comment by KKaras169169** [comment]
Solution: https://review.spdk.io/gerrit/c/spdk/spdk/+/11126

**Comment by ksztyber** [comment]
Patch was merged.
