### ISSUE TITLE
[nvmf_failover] Assertion `qpair->state_cb != NULL' failed

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2336]
# CI Intermittent Failure

During nvmf-tcp-phy-autotest, nvmf_failover failed at Assertion `qpair->state_cb != NULL'.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/68832/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

00:08:49.437   14:04:15	-- host/failover.sh@38 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 10.0.0.2 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:08:49.696  NVMe0n1
00:08:49.696   14:04:15	-- host/failover.sh@39 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py -s /var/tmp/bdevperf.sock bdev_nvme_attach_controller -b NVMe0 -t tcp -a 10.0.0.2 -s 4421 -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:08:49.955  
00:08:50.214   14:04:16	-- host/failover.sh@42 -- # rpc_pid=295991
00:08:50.214   14:04:16	-- host/failover.sh@44 -- # sleep 1
00:08:50.214   14:04:16	-- host/failover.sh@41 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/bdev/bdevperf/bdevperf.py -s /var/tmp/bdevperf.sock perform_tests
00:08:51.152   14:04:17	-- host/failover.sh@46 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4420
00:08:51.412  nvmf_tgt: ctrlr.c:3949: nvmf_qpair_request_cleanup: Assertion `qpair->state_cb != NULL' failed.
00:08:51.412  Connection closed with partial response:
00:08:51.412  
00:08:51.412  
00:08:51.412  test/nvmf/host/failover.sh: line 46: 295948 Aborted                 (core dumped) "${NVMF_APP[@]}" "$@"
00:08:51.412    14:04:17	-- host/failover.sh@46 -- # trap - ERR
00:08:51.412    14:04:17	-- host/failover.sh@46 -- # print_backtrace
00:08:51.412    14:04:17	-- common/autotest_common.sh@991 -- # [[ ehxBET =~ e ]]
00:08:51.412    14:04:17	-- common/autotest_common.sh@993 -- # args=('--transport=tcp')
00:08:51.412    14:04:17	-- common/autotest_common.sh@993 -- # local args
00:08:51.412    14:04:17	-- common/autotest_common.sh@995 -- # xtrace_disable
00:08:51.412    14:04:17	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:08:51.412    14:04:17	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:08:51.412    14:04:17	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:08:51.412    14:04:17	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:08:51.412    14:04:17	-- common/autotest_common.sh@19 -- # set +x
00:08:51.412  ========== Backtrace start: ==========
00:08:51.412  
00:08:51.412  in test/nvmf/host/failover.sh:46 -> main(["--transport=tcp"])
00:08:51.412       ...
00:08:51.412     41  	$rootdir/test/bdev/bdevperf/bdevperf.py -s $bdevperf_rpc_sock perform_tests &
00:08:51.412     42  	rpc_pid=$!
00:08:51.412     43  	
00:08:51.412     44  	sleep 1
00:08:51.412     45  	
00:08:51.412  => 46  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_PORT
00:08:51.412     47  	
00:08:51.412     48  	sleep 3
00:08:51.412     49  	
00:08:51.412     50  	$rpc_py -s $bdevperf_rpc_sock bdev_nvme_attach_controller -b NVMe0 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_THIRD_PORT -f ipv4 -n nqn.2016-06.io.spdk:cnode1
00:08:51.412     51  	$rpc_py nvmf_subsystem_remove_listener nqn.2016-06.io.spdk:cnode1 -t $TEST_TRANSPORT -a $NVMF_FIRST_TARGET_IP -s $NVMF_SECOND_PORT
00:08:51.412       ...
00:08:51.412  
00:08:51.412  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_68832.html

**Comment by AlekseyMarchuk** [comment]
This issue can be related to https://github.com/spdk/spdk/issues/2314 where qpair seems to be destroyed twice

**Comment by ksztyber** [comment]
[Bug scrub] Similarly, to #2314, this happened only once and it was long time ago. Let's close this one to and re-open if it happens again.
