### ISSUE TITLE
[vfio-user-autotest] Not all tests were run

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2340]
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_69033.html - list missing **vfio-user-autotest**

## Execution failed at

[2022-01-21T09:44:42.594Z] Not all tests were run. Failing the build.
[2022-01-21T09:44:42.594Z] ['vfio_user_fio', 'vfio_user_qemu', 'vfio_user_restart_vm']

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69033.html

**Comment by tomzawadzki** [comment]
[bug scrub] This occurred during the code freeze for SPDK 22.01, it seems to be related to the way tests are selected for last LTS. Since then no further occurrence.
