### ISSUE TITLE
[clang-vg-autotest] VM running out of disk space while compiling

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2343]
# CI Intermittent Failure

Clang VM on VM-host-PE3 seems to run out of the disk space while compiling.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/69052/archive/clang-vg-autotest/build.log

## Execution failed at

```
00:05:53.146    CXX test/cpp_headers/vfio_user_spec.o
00:05:53.146    LINK json_util_ut
00:05:53.146  fatal error: error in backend: IO failure on output stream: No space left on device
00:05:53.146  PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
```

**Comment by xjjx** [comment]
Same story on SM0 https://ci.spdk.io/results/autotest-per-patch/builds/69058/archive/clang-vg-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_69103.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_69107.html

**Comment by tomzawadzki** [comment]
This is eerily similar to https://github.com/spdk/spdk/issues/2115. I've ran some tests for size difference between SPDK v21.10 and latest SPDK.

Using `./configure` very similar to `clang-vg-autotest` job:
`./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --with-nvme-cuse --with-pmdk --with-reduce --with-rbd --with-crypto --with-ocf --enable-ubsan --enable-asan --enable-coverage --with-fuse --with-raid5 --with-uring --without-shared`

Patches referenced below are as follows:
- `no-apps` - https://review.spdk.io/gerrit/c/spdk/dpdk/+/11239
- `minimal libs` - https://review.spdk.io/gerrit/c/spdk/spdk/+/10506

```
SPDK master (61dadf2)
gcc (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)
8.4G [master]
6.4G [master + no-apps]
6.3G [master + no-apps + minimal libs]

SPDK master (61dadf2)
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
Cannot compile due to error reported by new clang in one of the DPDK apps [master]
6.5G [master + no-apps]
6.5G [master + no-apps + minimal libs]

SPDK v21.10 (4e4f11f)
gcc (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)
5.9G 

SPDK v21.10 (4e4f11f)
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
Cannot compile due to error reported by new clang:
./lib/eal/linux/eal.c:565:11: error: variable 'total_mem' set but not used [-Werror,-Wunused-but-set-variable]
        uint64_t total_mem = 0;
```

Unfortunately I couldn't run clang comparison on my dev machines, but there seems to be a build size increase between SPDK v21.10 and latest SPDK. For gcc it is ~2.5G for DPDK apps and ~0.1G for DPDK libs that are not required by SPDK.
After #2115 the size of image used for VM system was increased from 16GB to 20GB, so it is still concerning that the system still ran out of the space.

Patches above will reduce the build size, but there could be more information that could help with determining if that resolves this issue completely. Meanwhile jobs that run upstream DPDK, rather than submodule, will be in large part affected.

@karlatec 
1) What is the used/remaining space after running clang autotest job within the VM used in tests ?
2) Can we find if at the time of job failure, the VM host has any space remaining for system and nvme device images ?

The 2) is concerning for me, since every nvme device created for tests is thin provisioned. This means that in unfortunate case that all VMs use those images at the same time, it could affect rest of the system. Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11243 tries to remedy that. Please verify that every VM host will be able to use the preallocated images.
For system images, I believe they are not modified during VM run (to reuse base image on next job). This would mean that any diff during the VM run is kept on disk and increases in size as job runs. Could you make sure that enough space is reserved for each system image in similar manner to patch above ?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69444.html

**Comment by jimharris** [comment]
> Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11243 tries to remedy that.

This patch was merged, and last report was over 4 weeks ago.  Can this be closed?

**Comment by karlatec** [comment]
Let's close it:)
