### ISSUE TITLE
[nvmf_connect_stress] Disconnecting host from subsystem due to keep alive timeout

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2348]
# CI Intermittent Failure

During nvmf-tcp-phy-autotest, nvm_connect_stress failed due to keep alive timeout.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/69171/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

00:06:12.113   19:52:33	-- target/connect_stress.sh@32 -- # kill -0 1992325
00:06:12.113   19:52:33	-- target/connect_stress.sh@33 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py
00:06:12.680   19:52:34	-- target/connect_stress.sh@32 -- # kill -0 1992325
00:06:12.680   19:52:34	-- target/connect_stress.sh@33 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py
**00:06:12.938  [2022-01-25 19:52:34.282124] ctrlr.c: 195:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:03ce9c66-d236-426d-a3ec-78942b5e60ef from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.**
00:06:13.197   19:52:34	-- target/connect_stress.sh@32 -- # kill -0 1992325
00:06:13.197  test/nvmf/target/connect_stress.sh: line 32: kill: (1992325) - No such process
00:06:13.197   19:52:34	-- target/connect_stress.sh@36 -- # wait 1992325
00:06:13.197    19:52:34	-- target/connect_stress.sh@36 -- # trap - ERR
00:06:13.197    19:52:34	-- target/connect_stress.sh@36 -- # print_backtrace
00:06:13.197    19:52:34	-- common/autotest_common.sh@991 -- # [[ ehxBET =~ e ]]
00:06:13.197    19:52:34	-- common/autotest_common.sh@993 -- # args=('--transport=tcp')
00:06:13.197    19:52:34	-- common/autotest_common.sh@993 -- # local args
00:06:13.197    19:52:34	-- common/autotest_common.sh@995 -- # xtrace_disable
00:06:13.197    19:52:34	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:06:13.197    19:52:34	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:06:13.197    19:52:34	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:06:13.197    19:52:34	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:06:13.197    19:52:34	-- common/autotest_common.sh@19 -- # set +x
00:06:13.197  ========== Backtrace start: ==========
00:06:13.197  
00:06:13.198  in test/nvmf/target/connect_stress.sh:36 -> main(["--transport=tcp"])
00:06:13.198       ...
00:06:13.198     31  	
00:06:13.198     32  	while kill -0 $PERF_PID; do
00:06:13.198     33  		$rpc_py < $rpcs
00:06:13.198     34  	done
00:06:13.198     35  	
00:06:13.198  => 36  	wait $PERF_PID
00:06:13.198     37  	rm -f $rpcs
00:06:13.198     38  	
00:06:13.198     39  	trap - SIGINT SIGTERM EXIT
00:06:13.198     40  	
00:06:13.198     41  	nvmftestfini
00:06:13.198       ...
00:06:13.198  
00:06:13.198  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69171.html

**Comment by ksztyber** [comment]
[Bug scrub] Only happened once and the logs don't point to what actually failed. Let's keep it open for another 2 weeks and see if it happens again.
