### ISSUE TITLE
 SPDK env with PCIe interface failed in identify nvme devices

### ISSUE THREAD

**Issue by Embedded-linux** [spdk/spdk#2349]
# Bug report

Hi all , this is Satish I am complete newbie to SPDK, am working on one of  task, Need to identify nvme devices connected to target board using pcie interface from Host & run fio from Host pc. 

## Expected Behavior
Need to identify nvme devices connected to target board using pcie interface, these nvme devices need to identify from Host & run fio from Host pc

## Current Behavior
Target is running with SPDK env. with attached nvme devices.
here VPP is running on target board &  binding the PCIe interface devices 
using vfio-pci driver,  

nvme_ctrlr.c: 548:nvme_ctrlr_set_intel_support_log_pages: *WARNING*: Intel log pages not supported on Intel drive!
nvme_opal.c: 900:opal_discovery0_end: *ERROR*: Opal Not Supported.
nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: GET LOG PAGE (02) sqid:0 cid:95 nsid:ffffffff cdw10:007f00c0 cdw11:00000000
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID LOG PAGE (01/09) sqid:0 cid:95 cdw0:0 sqhd:0010 p:1 m:0 dnr:0
nvme_ctrlr.c: 548:nvme_ctrlr_set_intel_support_log_pages: *WARNING*: Intel log pages not supported on Intel drive!
nvme_opal.c: 900:opal_discovery0_end: *ERROR*: Opal Not Supported.
nvme_qpair.c: 119:nvme_admin_qpair_print_command: *NOTICE*: GET LOG PAGE (02) sqid:0 cid:95 nsid:ffffffff cdw10:007f00c0 cdw11:00000000
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID LOG PAGE (01/09) sqid:0 cid:95 cdw0:0 sqhd:0010 p:1 m:0 dnr:0
nvme_ctrlr.c: 548:nvme_ctrlr_set_intel_support_log_pages: *WARNING*: Intel log pages not supported on Intel drive!
***nvme_opal.c: 900:opal_discovery0_end: *ERROR*: Opal Not Supported.****
tcp.c: 537:spdk_nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
tcp.c: 732:spdk_nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.13.10.1 port 4420 ***

This is client connection listen to through port 10.13.10.1 
& on Host side , enabled other interface "lo" with 10.13.10.2 
while running 
nvme discover -t tcp -a 10.13.10.1 -s 4420  on host it is saying 
"no NVMe controller(s) detected.
Failed to open /dev/nvme-fabrics: No such file or directory "

## Possible Solution
Host needs to identify the target TCP connection , 
Need support/suggestion where is issue & how to fix the issue & identify the nvme devices from Host 
 
## Steps to Reproduce
1. Connect nvme devices to target board 
2. On target run VPP to create l2bridge with Host
3. Run SPDK on target 
4. Load Pcie drivers on Host & listen the TCP/IP connection from Target

## Context (Environment including OS version, SPDK version, etc.)
Os version: RHEL 
SPDK version: v19.10.1 
DPDK version: 19.11.0
 

Thanks in advance

Regards
Satish G

**Comment by tomzawadzki** [comment]
Hi @Embedded-linux,

Below might be pointing to lack of nvme-tcp kernel module on the NVMe-oF Initiator.
```
nvme discover -t tcp -a 10.13.10.1 -s 4420 on host it is saying
"no NVMe controller(s) detected.
Failed to open /dev/nvme-fabrics: No such file or directory "
```
Please try `modprobe nvme-tcp` and refer to https://spdk.io/doc/nvmf.html for additional details.


Note that the `SPDK version: v19.10.1` that you are using is no longer supported. At the end of this week SPDK 22.01 LTS will be released at the end of this week, and will be supported for a year. Please consider switching to the latest SPDK release.

**Comment by Embedded-linux** [comment]
Hi @tomzawadzki  
thanks for quick reply
yes I have installed the "modprobe nvme-tcp " on Host side.
after installing the nvme-tcp it removed the no NVMe controller detected but it is giving other issue as

sudo nvme discover -t tcp -a 10.13.10.1 -s 4420
**Failed to write to /dev/nvme-fabrics: Connection refused**
& Regards SPDK version right now I need to make sure once SPDK/DPDK will work with  NVMe-OF with PCIe interface & later  
will upgrade to higher version of SPDK.

Can you please help me to find out reason for the above issue

Thanks in advance
Regards
Satish G

**Comment by jimharris** [comment]
> Hi @tomzawadzki thanks for quick reply yes I have installed the "modprobe nvme-tcp " on Host side. after installing the nvme-tcp it removed the no NVMe controller detected but it is giving other issue as
> 
> sudo nvme discover -t tcp -a 10.13.10.1 -s 4420 **Failed to write to /dev/nvme-fabrics: Connection refused** & Regards SPDK version right now I need to make sure once SPDK/DPDK will work with NVMe-OF with PCIe interface & later will upgrade to higher version of SPDK.
> 
> Can you please help me to find out reason for the above issue
> 
> Thanks in advance Regards Satish G

Hi @Embedded-linux,

The experimental SPDK support for VPP was removed from SPDK about 18 months ago.  You should move to just using the kernel TCP stack.

Regards,

Jim

**Comment by jimharris** [comment]
Closing issue.  If you are able to reproduce using kernel TCP stack with a later version of SPDK, please reopen.
