### ISSUE TITLE
[nvme-multi-secondary] Assertion `!dev->internal.removed' failed

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2351]
# CI Intermittent Failure

During nvme-phy-autotest, nvme-multi-secondary test failed at Assertion `!dev->internal.removed' failed.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/69266/archive/nvme-phy-autotest/build.log

## Execution failed at

...
00:03:55.499  Attached to NVMe Controller at 0000:65:00.0 [8086:0a54]
00:03:55.499  Associating PCIE (0000:65:00.0) NSID 1 with lcore 2
00:03:55.499  Initialization complete. Launching workers.
00:03:55.499  ========================================================
00:03:55.499                                                                             Latency(us)
00:03:55.499  Device Information                     :       IOPS      MiB/s    Average        min        max
00:03:55.499  PCIE (0000:65:00.0) NSID 1 from core  2:   38693.52     151.15     412.91      24.76   14670.40
00:03:55.499  ========================================================
00:03:55.499  Total                                  :   38693.52     151.15     412.91      24.76   14670.40
00:03:55.499  
00:03:55.499   08:47:18	-- nvme/nvme.sh@50 -- # wait 17227
00:03:55.499   08:47:18	-- nvme/nvme.sh@51 -- # wait 17228
00:03:55.499  EAL: Failed to hotplug remove device
**00:03:55.499  perf: pci.c:539: pci_device_fini: Assertion `!dev->internal.removed' failed.
00:03:55.499  test/nvme/nvme.sh: line 51: 17228 Aborted                 (core dumped) $SPDK_EXAMPLE_DIR/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x2**
00:03:55.499    08:47:18	-- nvme/nvme.sh@51 -- # trap - ERR
00:03:55.499    08:47:18	-- nvme/nvme.sh@51 -- # print_backtrace
00:03:55.499    08:47:18	-- common/autotest_common.sh@991 -- # [[ ehxBET =~ e ]]
00:03:55.499    08:47:18	-- common/autotest_common.sh@993 -- # args=("${BASH_ARGV[@]}")
00:03:55.499    08:47:18	-- common/autotest_common.sh@993 -- # local args
00:03:55.499    08:47:18	-- common/autotest_common.sh@995 -- # xtrace_disable
00:03:55.499    08:47:18	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:55.499    08:47:18	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:03:55.499    08:47:18	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:03:55.499    08:47:18	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:55.499    08:47:18	-- common/autotest_common.sh@19 -- # set +x
00:03:55.499  ========== Backtrace start: ==========
00:03:55.499  
00:03:55.499  in test/nvme/nvme.sh:51 -> nvme_multi_secondary([])
00:03:55.499       ...
00:03:55.499     46  		pid0=$!
00:03:55.499     47  		$SPDK_EXAMPLE_DIR/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x2 &
00:03:55.499     48  		pid1=$!
00:03:55.499     49  		$SPDK_EXAMPLE_DIR/perf -i 0 -q 16 -w read -o 4096 -t 3 -c 0x4
00:03:55.499     50  		wait $pid0
00:03:55.499  => 51  		wait $pid1
00:03:55.499     52  	}
00:03:55.499     53  	
00:03:55.499     54  	if [ $(uname) = Linux ]; then
00:03:55.499     55  		# check that our setup.sh script does not bind NVMe devices to uio/vfio if they
00:03:55.499     56  		# have an active mountpoint
00:03:55.499       ...
00:03:55.499  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:963 -> run_test(["nvme_multi_secondary"],["nvme_multi_secondary"])
00:03:55.500       ...
00:03:55.500     958 		timing_enter $test_name
00:03:55.500     959 		echo "************************************"
00:03:55.500     960 		echo "START TEST $test_name"
00:03:55.500     961 		echo "************************************"
00:03:55.500     962 		xtrace_restore
00:03:55.500  => 963 		time "$@"
00:03:55.500     964 		xtrace_disable
00:03:55.500     965 		echo "************************************"
00:03:55.500     966 		echo "END TEST $test_name"
00:03:55.500     967 		echo "************************************"
00:03:55.500     968 		timing_exit $test_name
00:03:55.500       ...
00:03:55.500  in test/nvme/nvme.sh:130 -> main([])
00:03:55.500       ...
00:03:55.500     125 	run_test "nvme_overhead" $testdir/overhead/overhead -s 4096 -t 1 -H -i 0
00:03:55.500     126 	run_test "nvme_arbitration" $SPDK_EXAMPLE_DIR/arbitration -t 3 -i 0
00:03:55.500     127 	
00:03:55.500     128 	if [ $(uname) != "FreeBSD" ]; then
00:03:55.500     129 		run_test "nvme_startup" $testdir/startup/startup -t 1000000
00:03:55.500  => 130 		run_test "nvme_multi_secondary" nvme_multi_secondary
00:03:55.500     131 		trap - SIGINT SIGTERM EXIT
00:03:55.500     132 		kill_stub
00:03:55.500     133 	fi
00:03:55.500     134 	
00:03:55.500     135 	if [[ $CONFIG_FIO_PLUGIN == y ]]; then
00:03:55.500       ...
00:03:55.500  
00:03:55.500  ========== Backtrace end ==========
...

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69266.html

**Comment by tomzawadzki** [comment]
@KKaras169169 please rebase the patches to latest SPDK before submission, as this test and relevant implementation has changed.

This test has changed with patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11216 due to issue https://github.com/spdk/spdk/issues/2320. 
The issue above does not result in the same assert, but has very similar error pattern beforehand:
```
00:03:55.239  EAL: Driver cannot detach the device (0000:65:00.0)
00:03:55.239  EAL: Driver cannot detach the device (0000:65:00.0)
00:03:55.239  EAL: Failed to hotplug remove device on secondary
00:03:55.239  EAL: Failed to hotplug remove device
...
00:03:55.240  EAL: Driver cannot detach the device (0000:65:00.0)
00:03:55.240  EAL: Failed to hotplug remove device on secondary
00:03:55.499  EAL: Failed to hotplug remove device
00:03:55.499  EAL: failed to send to (/var/run/dpdk/spdk0/mp_socket_17229_42573c7e8a0) due to No such file or directory
00:03:55.499  EAL: Fail to send request /var/run/dpdk/spdk0/mp_socket_17229_42573c7e8a0:eal_dev_mp_request
00:03:55.499  EAL: rte_mp_request_sync failed
00:03:55.499  EAL: Failed to send hotplug request to secondary
```

Due to that let keep this issue open for this week, but if no other reports occur close it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69315.html

**Comment by tomzawadzki** [comment]
The report above is part of the series that includes backport of the mentioned patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11274/1. This would imply this GH issue is unique from #2320 and not resolved by that patch.

>Due to that let keep this issue open for this week, but if no other reports occur close it.

This is no longer true, and issue will be open till resolution.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69415.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_69601.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69614.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_69616.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_69618.html

**Comment by ksztyber** [comment]
[Bug scrub] No reports for two weeks. Let's keep it open for another 2 weeks and see if it happens again.
