### ISSUE TITLE
NVMF target  starts reporting shared object file not found

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#2352]
# Bug report
./build/bin/nvmf_tgt
./build/bin/nvmf_tgt: error while loading shared libraries: librte_bus_pci.so.22: cannot open shared object file: No such file or directory

checkout 097ccf06a9ef9b77b72cdc582364ffa3096dd33a is ok
## Steps to Reproduce
git pull 
git submodule update --init
./configure --with-rdma
make -j100

## Context (Environment including OS version, SPDK version, etc.)
commit: 241d06070a9e91583399288e517055d50fb8ac8e

**Comment by yidong0635** [comment]
diff --git a/lib/env_dpdk/env.mk b/lib/env_dpdk/env.mk
index 59c2e3f3c..ae80454fb 100644
--- a/lib/env_dpdk/env.mk
+++ b/lib/env_dpdk/env.mk
@@ -171,7 +171,7 @@ else
 ENV_DPDK_FILE = $(call spdk_lib_list_to_static_libs,env_dpdk)
 endif

-ifneq (,$(DPDK_SHARED_LIB))
+ifeq (,$(DPDK_SHARED_LIB))
 ENV_LIBS = $(ENV_DPDK_FILE) $(DPDK_SHARED_LIB)
 DPDK_LINKER_ARGS = -Wl,-rpath-link $(DPDK_LIB_DIR) $(DPDK_SHARED_LIB_LINKER_ARGS)
 ENV_LINKER_ARGS = $(ENV_DPDK_FILE) $(DPDK_LINKER_ARGS)

**Comment by yidong0635** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/11284

**Comment by yidong0635** [comment]
I found   ./configure --with-rdma --with-shard 
this doesn't work  
./build/bin/nvmf_tgt
./build/bin/nvmf_tgt: error while loading shared libraries: libspdk_bdev_malloc.so.3.0: cannot open shared object file: No such file or directory

**Comment by yidong0635** [comment]
if we don't config --with-share, we should use static lib as well for DPDK , because we use 
ifeq ($(CONFIG_SHARED),y)
ENV_DPDK_FILE = $(call spdk_lib_list_to_shared_libs,env_dpdk)
else
ENV_DPDK_FILE = $(call spdk_lib_list_to_static_libs,env_dpdk)
endif

**Comment by KKaras169169** [comment]
Encountered this issue while trying to run spdk_tgt on latest master branch. The above fix resolved the problem for me.
