### ISSUE TITLE
nvme initiator RDMA not work any more after run "service network restart"

### ISSUE THREAD

**Issue by dashan8020** [spdk/spdk#2356]
# Bug report

## Expected Behavior
After "service network restart", the RDMA in spdk nvme host could recover and work well again.

## Current Behavior
when every thing works well, I restarted netowk with command "service network restart", then spdk nvme host could not work any more with RDMA connection error, and if process of spdk nvme host restart, every thing will become well again.
the nvme host error log is shown as below (SPDK version is 20.1)

**nvme_rdma.c: 857:nvme_rdma_resolve_addr: *ERROR*: RDMA address resolution error
nvme_rdma.c:1140:nvme_rdma_ctrlr_connect_qpair: *ERROR*: nvme_rdma_resolve_addr() failed**

 or

**nvme_rdma.c: 468:nvme_rdma_qpair_init: *ERROR*: Failed to query RDMA device attributes.
nvme_rdma.c:1146:nvme_rdma_ctrlr_connect_qpair: *ERROR*: nvme_rdma_qpair_init() failed**

## Steps to Reproduce

1. start spdk nvme host and every thing works well
2.service network restart
3. check nvme host log
4.

## Context (Environment including OS version, SPDK version, etc.)
spdk version: 20.1
Linux: 4.12.14-95.83-default

**Comment by ksztyber** [comment]
A lot of improvements have been made to the reconnect/reset path recently, could you recheck it on a more recent version of SPDK (e.g. latest LTS release, 22.01)?
