### ISSUE TITLE
Undefined reference libarchive

### ISSUE THREAD

**Issue by mattyouill** [spdk/spdk#2357]
# Bug report

SPDK build fails with undefined references to libarchive symbols.

## Expected Behavior

Build succeeds.

## Current Behavior

make fails with the following link errors.

/home/ubuntu/spdk/dpdk/build/lib/librte_eal.a(eal_unix_eal_firmware.c.o): In function `rte_firmware_read':
eal_firmware.c:(.text.internal+0x3a): undefined reference to `archive_read_new'
eal_firmware.c:(.text.internal+0x4e): undefined reference to `archive_read_support_format_raw'
eal_firmware.c:(.text.internal+0x5e): undefined reference to `archive_read_support_filter_xz'
eal_firmware.c:(.text.internal+0x76): undefined reference to `archive_read_open_filename'
eal_firmware.c:(.text.internal+0x87): undefined reference to `archive_read_next_header'
eal_firmware.c:(.text.internal+0xab): undefined reference to `archive_read_data'
eal_firmware.c:(.text.internal+0xf8): undefined reference to `archive_read_free'
eal_firmware.c:(.text.internal+0x13c): undefined reference to `archive_read_new'
eal_firmware.c:(.text.internal+0x150): undefined reference to `archive_read_support_format_raw'
eal_firmware.c:(.text.internal+0x160): undefined reference to `archive_read_support_filter_xz'
eal_firmware.c:(.text.internal+0x178): undefined reference to `archive_read_open_filename'
eal_firmware.c:(.text.internal+0x18d): undefined reference to `archive_read_next_header'
eal_firmware.c:(.text.internal+0x1b3): undefined reference to `archive_read_data'
eal_firmware.c:(.text.internal+0x202): undefined reference to `archive_read_free'
eal_firmware.c:(.text.internal+0x23e): undefined reference to `archive_read_free'

## Possible Solution

Suspect "-larchive" missing in link arguments.

## Steps to Reproduce

The following will reproduce the error on Ubuntu.

1. Ensure libarchive-dev is installed
2. Follow steps at https://spdk.io/doc/getting_started.html

## Context (Environment including OS version, SPDK version, etc.)

Tested on...
Ubuntu 18.04, Ubuntu 20.04
GCC 7 and 9
SPDK latest master as at bug report file date

**Comment by jimharris** [comment]
Thanks for the detailed report @mattyouill.  I've pushed https://review.spdk.io/gerrit/c/spdk/spdk/+/11385 which should fix this issue.

**Comment by jimharris** [comment]
Patch merged.
