### ISSUE TITLE
[nvmf-autotest] fio verification not run during tests?

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2358]
# Bug report

Stumbled upon this accidentally while inspecting logs for something else. Seems like IO verification process is not run by fio during tests.

Let's take https://ci.spdk.io/public_build/autotest-per-patch_70230.html as an example, `nvmf-phy-autotest` build results.
Search for `START TEST nvmf_fio_target` and scroll a bit down to where fio process starts.

```
00:11:12.044   03:03:32	-- target/fio.sh@38 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/fio-wrapper -p nvmf -i 4096 -d 1 -t write -r 1 -v
00:11:12.044  [global]
00:11:12.044  thread=1
00:11:12.044  invalidate=1
00:11:12.044  rw=write
00:11:12.044  time_based=1
00:11:12.044  runtime=1
00:11:12.044  ioengine=libaio
00:11:12.044  direct=1
00:11:12.044  bs=4096
00:11:12.044  iodepth=1
00:11:12.044  norandommap=0
00:11:12.044  numjobs=1
00:11:12.044  verify_dump=1
00:11:12.044  do_verify=1
00:11:12.044  verify=crc32c-intel
00:11:12.044  [job0]
00:11:12.044  filename=/dev/nvme0n1
00:11:12.044  [job1]
00:11:12.044  filename=/dev/nvme0n2
00:11:12.044  [job2]
00:11:12.044  filename=/dev/nvme0n3
00:11:12.044  Could not set queue depth (nvme0n1)
00:11:12.044  Could not set queue depth (nvme0n2)
00:11:12.044  Could not set queue depth (nvme0n3)
00:11:12.044  fio: verification read phase will never start because write phase uses all of runtime
00:11:12.044  job0: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
00:11:12.044  fio: verification read phase will never start because write phase uses all of runtime
00:11:12.044  job1: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
00:11:12.044  fio: verification read phase will never start because write phase uses all of runtime
00:11:12.044  job2: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
00:11:12.044  fio-3.28
00:11:12.044  Starting 3 threads
00:11:13.441  
```

## Expected Behavior

Well. we should verify.

## Current Behavior

As in description.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 047c067c05ff22df06c053990998184b8a940514

**Comment by karlatec** [comment]
Proposed fix:  https://review.spdk.io/gerrit/c/spdk/spdk/+/11376
This causes fio to stop writing and verify after every N blocks written. Downside is that last batch of blocks might not be verified due to run_time running out.

Alternatively this could be fixed differently - by inserting a `rw=(rand)read` job after write phase to verify previously written data. This would add time to test execution though.

**Comment by ksztyber** [comment]
Patch was merged.
