### ISSUE TITLE
centos8 test fails on install dpdk-devel

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#2359]
# Bug report

Centos8 test fails on install dpdk-devel package

## Expected Behavior

test should pass

## Current Behavior

test failing

## Possible Solution

Unknown

## Steps to Reproduce

06:08:51     43  		build_rpm_with_rpmed_dpdk() {
06:08:51  => 44  			sudo dnf install -y dpdk-devel
06:08:51     45  			build_rpm --with-shared --with-dpdk
06:08:51     46  		}

06:08:33   05:08:33	-- spdk/autopackage.sh@44 -- $ sudo dnf install -y dpdk-devel
06:08:34  CentOS-8 - Ceph Nautilus                        201  B/s |  38  B     00:00    
06:08:34  Error: Failed to download metadata for repo 'centos-ceph-nautilus': Cannot prepare internal mirrorlist: No URLs in mirrorlist
06:08:34  CentOS Linux 8 - AppStream                      242  B/s |  38  B     00:00    
06:08:34  Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
06:08:34  CentOS Linux 8 - BaseOS                         116  B/s |  38  B     00:00    
06:08:34  Error: Failed to download metadata for repo 'baseos': Cannot prepare internal mirrorlist: No URLs in mirrorlist
06:08:35  CentOS Linux 8 - Extras                          16 kB/s |  10 kB     00:00    
06:08:35  CentOS Linux 8 - PowerTools                     307  B/s |  38  B     00:00    
06:08:35  Error: Failed to download metadata for repo 'powertools': Cannot prepare internal mirrorlist: No URLs in mirrorlist
06:08:36  ELRepo.org Community Enterprise Linux Repositor 265 kB/s | 257 kB     00:00    
06:08:37  ELRepo.org Community Enterprise Linux Testing R 2.7 kB/s | 1.8 kB     00:00    
06:08:47  Extra Packages for Enterprise Linux Modular 8 - 116 kB/s | 979 kB     00:08    
06:08:48  Extra Packages for Enterprise Linux 8 - x86_64  5.9 MB/s |  11 MB     00:01    
06:08:51  Ignoring repositories: centos-ceph-nautilus, appstream, baseos, powertools
06:08:51  No match for argument: dpdk-devel
06:08:51  Error: Unable to find a match: dpdk-devel

**Comment by ksztyber** [comment]
[Bug scrub] Karol will update CI to use different mirror lists. Replacement for Centos 8 being EOL - Rocky Linux.
