### ISSUE TITLE
spdk_nvme_cli_cuse.sh tests fail with nvme-cli v1.15

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2361]
# Bug report

spdk_nvme_cli_cuse.sh tests with nvme-cli v1.15:

```
 11:50:49       -- cuse/spdk_nvme_cli_cuse.sh@98 -- # /usr/local/src/nvme-cli/nvme write /dev/spdk/nvme0n1 --data-size=512 --data=/home/sys_sgci/spdk/test/nvme/cuse/write_file
[2022-02-04 11:50:49.260996] nvme_qpair.c: 270:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:895 nsid:1 lba:0 len:1 PRP1 0x0 PRP2 0x0
[2022-02-04 11:50:49.261011] nvme_qpair.c: 454:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:1 cid:895 cdw0:0 sqhd:0001 p:1 m:1 dnr:0
NVMe status: DATA_XFER_ERROR: Error while trying to transfer the data or metadata(0x2004)
```

In dmesg this seems to be a related message:
```
[ 2974.605334] DMAR: DRHD: handling fault status reg 102
[ 2974.605338] DMAR: [DMA Read] Request device [5e:00.0] PASID ffffffff fault addr 0 [fault reason 06] PTE Read access is not set
```

## Possible Solution

Bumping up nvme-cli version to v1.16 seems to solve the issue.

## Steps to Reproduce

1. Build nvme-cli v1.15 in `/usr/local/src/nvme-cli`
2. Build SPDK  with `--with-nvme-cuse` and run `sudo -E test/nvme/cuse/spdk_nvme_cli_cuse.sh` test.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 5eb363cf8cea9ec5042b22a36185f29d1eb421e7

**Comment by jimharris** [comment]
I suspect that linux-nvme/nvme-cli@633579877f2 broke this.  This commit was introduced in v1.15.

v1.16 has linux-nvme/nvme-cli@bbf3beaf4 which probably fixes it.

If you're able to confirm this through a bisect or manual testing of these commits, we can confidently close this as a 3rd party issue.

**Comment by karlatec** [comment]
Bisected. Resulting commits are exactly the same to the ones you pointed out :) 
Let's please not close the issue until our CI infra is updated with new version.

**Comment by jimharris** [comment]
> Bisected. Resulting commits are exactly the same to the ones you pointed out :)

Thanks for confirming!

> Let's please not close the issue until our CI infra is updated with new version.

FYI - https://review.spdk.io/gerrit/c/spdk/spdk/+/11408 was merged.  Please go ahead and close this one CI infra is updated with new version.

**Comment by karlatec** [comment]
Patch for building CI OS images merged; images built and deployed. Closing issue.
