### ISSUE TITLE
FIO Plugin device still attached at shutdown

### ISSUE THREAD

**Issue by jsrolon** [spdk/spdk#2366]
# Bug report

I am currently using [bench-fio](https://github.com/louwrentius/fio-plot/tree/24fa05f864512e9173d49b188ef16941b548fff5/bench_fio) from [fio-plot](https://github.com/louwrentius/fio-plot) which is a very simple Python wrapper around fio to run multiple test cases and store their results in a directory tree.

I have modified bench-fio to run my own compiled version of fio 3.29 with the SPDK plugin. I have verified that I can run fio normally through CLI, and as long as I'm running a 1-job fio test using bench-fio, I have no errors.

Starting with >= 2 jobs on fio-bench, I get this error message every time:

```
[2022-02-07 21:54:04.868240] pci.c: 424:pci_env_fini: *ERROR*: Device 0000:bc:00.0 is still attached at shutdown!
[2022-02-07 21:54:04.868652] pci.c: 424:pci_env_fini: *ERROR*: Device 0000:bc:00.0 is still attached at shutdown!
[2022-02-07 21:54:04.868880] pci.c: 424:pci_env_fini: *ERROR*: Device 0000:bc:00.0 is still attached at shutdown!
[2022-02-07 21:54:04.869235] pci.c: 424:pci_env_fini: *ERROR*: Device 0000:bc:00.0 is still attached at shutdown!
```

Apparently my bench-fio tests continue, but I don't know if the benchmark results I'm getting after this are to be trusted. Is the device in a healthy state?

## Expected Behavior

No errors when running a fio test with 2 or more jobs

## Current Behavior

I get `*ERROR*: Device 0000:bc:00.0 is still attached at shutdown!` at the end of every fio test.

## Steps to Reproduce

1. Follow the SPDK fio plugin steps [here](https://github.com/spdk/spdk/tree/master/examples/nvme/fio_plugin)
2. Run a fio+spdk plugin test with 4 jobs: `~/fio/fio --output-format=json --output=your_output ~/lib/python3.8/site-packages/bench_fio/benchlib/../templates/fio-job-template.fio --size=4g --runtime=60 --time_based --engine spdk --filename "trtype=PCIe traddr=0000.bc.00.0 ns=1"`

## Context (Environment including OS version, SPDK version, etc.)

* Ubuntu 20.04 Focal
* SPDK checked out at 8175ef2944cb5679b33f0365aed720b636fa11ef
* FIO 3.29
* uio_pci_generic driver

**Comment by changpe1** [comment]
thanks for reporting, it's a bug in fio_plugin tool, but it doesn't affect your test results, I will push a fix patch later.

**Comment by changpe1** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11443 should fix this issue, can you have a try? thanks.

**Comment by jsrolon** [comment]
I just tried it and the `*ERROR*: Device 0000:bc:00.0 is still attached at shutdown!` errors have gone away. Thanks!

However, I notice that I'm now getting `symbol lookup error: ~/spdk/build/fio/spdk_nvme: undefined symbol: is_backend`. I don't know if this was the case before as well. I get the feeling this means something went wrong when compiling SPDK with the fio plugin?

**Comment by changpe1** [comment]
patch has been merged, closing it now.
