### ISSUE TITLE
[nvmf/nvmf_fio_host] nvmf_fio_host case fail because configure with CC=clang-12 CXX=clang++-12

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2367]
# Bug report

Nvmf llvm fuzz need the CC=clang-12 CXX=clang++-12 configuration to compile, but when use CC=clang-12 CXX=clang++-12 will cause another case: nvmf_fio_host run fail.

## Expected Behavior

All nvmf cases pass.

## Current Behavior

CC=clang-12 CXX=clang++-12 configuration cause a case nvmf_fio_host fail

## Possible Solution

No

## Steps to Reproduce

1. Configure and compile
CC=clang-12 CXX=clang++-12 ./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --enable-ubsan --enable-coverage --without-isal --with-shared
make -j128
2. Run case
test/nvmf/host/fio.sh --transport=tcp
3. Error inforamtion
 20:49:16       -- common/autotest_common.sh@1195 -- # /usr/src/fio/fio /home/wenjun/spdk/examples/nvme/fio_plugin/example_config.fio '--filename=trtype=tcp adrfam=IPv4 traddr=10.0.0.2 trsvcid=4420 ns=1' --bs=4096
/usr/src/fio/fio: symbol lookup error: /home/wenjun/spdk/build/lib/libspdk_log.so.5.0: undefined symbol: __ubsan_handle_shift_out_of_bounds

## Context (Environment including OS version, SPDK version, etc.)
Fio version: fio-3.28-93-ga87e
OS: Fedora34
SPDK: d4b8944881744ed46c4d47c342810ab2acfe8266

**Comment by ksztyber** [comment]
[Bug scrub] clang uses static libraries for the libasan. Need to adjust build/test scripts for that.

**Comment by junwenx** [comment]
@ksztyber Thanks ksztyber.

**Comment by ksztyber** [comment]
@junwenx could you check if https://review.spdk.io/gerrit/c/spdk/spdk/+/11662 fixes the issue on your end?

**Comment by junwenx** [comment]
@ksztyber  Pull the patch to may local, error "build/lib/libspdk_log.so.5.0: undefined symbol: __ubsan_handle_shift_out_of_bounds" seems solved, but there is new problem raise after pull this patch:
info as below:
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: mismatched number of counters (64)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000003)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr_cmd.gcda: cannot merge previous run count: corrupt object tag (0x00000022)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: mismatched number of counters (64)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)
profiling: /home/wenjun/spdk/lib/nvme/nvme_ctrlr.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000000)


Could you please have a check, thanks!

**Comment by junwenx** [comment]
@ksztyber It seems no issue now, thank you for the support! I think this issue can be closed :)
