### ISSUE TITLE
[spdk master vs dpdk main] undefined references to dma/vhost libraries

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2374]
# Bug report

When building latest SPDK master with latest mainline DPDK compilation fails due to multiple linker `undefined reference to:` errors.
Full logs can be found at:
https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_347.html

Builds started to fail after DPDK commit 53d3f4778c1dbdebbef6c5e94e772b24f0998d35
was merged into DPDK main branch.

## Steps to Reproduce

1. Create SPDK autorun.conf file:
```
SPDK_RUN_VALGRIND=1
SPDK_RUN_FUNCTIONAL_TEST=0
SPDK_TEST_AUTOBUILD=0
SPDK_TEST_UNITTEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_PMDK=1
SPDK_TEST_ISAL=1
SPDK_TEST_REDUCE=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_FTL=1
SPDK_TEST_OCF=1
SPDK_TEST_RAID5=1
SPDK_TEST_RBD=1
SPDK_TEST_URING=1
SPDK_TEST_NVME_CUSE=1
SPDK_TEST_BLOBFS=1
SPDK_TEST_VFIOUSER=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
SPDK_TEST_RELEASE_BUILD=1
EXTERNAL_MAKE_HUGEMEM=2048
SPDK_TEST_NATIVE_DPDK=main
SPDK_RUN_EXTERNAL_DPDK=/spdk-temp/dpdk/build
```
2. Run build tests:
```
./autorun.sh ~/autorun.conf
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 9cd85928e5e92b5b2c1782237cb8947ec75d3213
DPDK 53d3f4778c1dbdebbef6c5e94e772b24f0998d35
```
commit 53d3f4778c1dbdebbef6c5e94e772b24f0998d35 (HEAD, refs/bisect/bad)
Date:   Wed Feb 9 07:51:45 2022 -0500

    vhost: integrate dmadev in asynchronous data-path

    Since dmadev is introduced in 21.11, to avoid the overhead of vhost DMA
    abstraction layer and simplify application logics, this patch integrates
    dmadev in asynchronous data path.
```

**Comment by karlatec** [comment]
Also affects 22.01.x branch

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/11594

**Comment by karlatec** [comment]
Thank you Jim!
Confirmed that this fixes the problem: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_357.html
I'll cherry pick that on top of 22.01.x as well

**Comment by changpe1** [comment]
patch was merged, closing it now.
