### ISSUE TITLE
double unlock in spdk_io_device_register

### ISSUE THREAD

**Issue by liwg06** [spdk/spdk#2378]
`pthread_mutex_unlock()` in the `tmp != NULL` branch should be removed, otherwise will cause a double unlock.

https://github.com/spdk/spdk/blob/662678dfbef02424b0d55d4ea5aca603941fb48d/lib/thread/thread.c#L1989-L2001

**Comment by changpe1** [comment]
@liwg06 thanks for reporting, will you have a try to submit a fix patch to SPDK? you may refer https://spdk.io/development/.

**Comment by changpe1** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/11642

**Comment by jimharris** [comment]
Patch merged.  Thanks @liwg06!
