### ISSUE TITLE
[nvme-phy-autotest]  /proc/1142605/cgroup: No such file or directory

### ISSUE THREAD

**Issue by jlevon** [spdk/spdk#2381]
# CI Intermittent Failure

00:08:11.086  ************************************
00:08:11.086  START TEST scheduler
00:08:11.086  ************************************

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/71627/archive/nvme-phy-autotest/build.log

## Execution failed at

00:08:11.347  /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/cgroups.sh: line 30: /proc/1142605/cgroup: No such file or directory
00:08:11.347  ========== Backtrace start: ==========
00:08:11.347  
00:08:11.347  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/cgroups.sh:30 -> init_cpuset_cgroup([])
00:08:11.347       ...
00:08:11.347     25  			# maintaining user's session. To recreate the simple /cpuset setup from
00:08:11.347     26  			# v1, move all the threads from all the existing cgroups to the top
00:08:11.347     27  			# cgroup / and then migrate it to the /cpuset we created above.
00:08:11.347     28  			for cgroup in /proc/+([0-9])/cgroup; do
00:08:11.347     29  				[[ -e $cgroup ]] || continue
00:08:11.347  => 30  				cgroup=$(< "$cgroup") cgroup=${cgroup##*:}
00:08:11.347     31  				[[ $cgroup != / ]] || continue
00:08:11.347     32  				move_cgroup_procs "${cgroup##*:}" /
00:08:11.347     33  			done
00:08:11.347     34  			# Now, move all the threads to the cpuset
00:08:11.347     35  			move_cgroup_procs / /cpuset
00:08:11.347       ...

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_71627.html

**Comment by mikeBashStuff** [comment]
Potential mitigation: https://review.spdk.io/gerrit/c/spdk/spdk/+/11670

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_71819.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_71770.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_72525.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72576.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_72594.html

**Comment by mikeBashStuff** [comment]
The last two reports don't match the main issue, they actually point at something new (by looking at the code path, it seems to be the problem with missing cgroup under sysfs, probably the one that's being moved). So I would suggest to open a new issue and close this one.

**Comment by mikeBashStuff** [comment]
Here's potential mitigation: https://review.spdk.io/gerrit/c/spdk/spdk/+/11815 I would suggest to spin this bunch of times on the CI first, to make sure it's stable.

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11815 is now merged. No recent reports so closing the issue.
