### ISSUE TITLE
Leak eventfd when restart/reboot VM

### ISSUE THREAD

**Issue by YamboZhou** [spdk/spdk#2385]
Hi all,

When VM restarts/reboots, the eventfd used to notify cq completion will leak.  The number of leaked eventfd depends on how many qpairs used in virtual devices.  Now we use vhost-nvme. I notice vhost-blk/scsi use the same mechanism for CQ notification as vhost-nvme so that maybe they have same issues.

The reason why spdk leak eventfd is QEMU creates a eventfd for CQ notification and then share this eventfd through socket message with SCM_RIGHTS flag. SPDK target receives this eventfd and opens the eventfd passively. This eventfd finally is set to cq->virq but do not be closed after deleting cq. 

```
int
vhost_nvme_set_cq_call(int vid, uint16_t qid, int fd)
{
	struct spdk_vhost_nvme_dev *nvme;
	struct spdk_vhost_nvme_cq *cq;

	nvme = spdk_vhost_nvme_get_by_name(vid);
	if (!nvme) {
		return -1;
	}

	cq = spdk_vhost_nvme_get_cq_from_qid(nvme, qid);
	if (!cq) {
		return -1;
	}
	if (cq->irq_enabled) {
		cq->virq = fd;
	} else {
		SPDK_ERRLOG("NVMe Qid %d Disabled IRQ\n", qid);
	}

	return 0;
}
```

## Expected Behavior

Eventfd should be closed after stopping VM.

## Current Behavior

Eventfd is still opened in vhost-nvme process. Below is the output by using Linux shell "lsof -p <pid of vhost-nvme>" after we stopped VM. Here we start and then stop a VM that is configured with 8 devices and 3 queues per device.
```
......
xxxx 14279 root 4594u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4599u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4609u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4611u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4620u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4622u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4624u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4626u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4628u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4630u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4632u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4637u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4643u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4645u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4647u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4649u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4652u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4654u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4656u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4658u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4661u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4662u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4664u  a_inode               0,13          0     12544 [eventfd]
xxxx 14279 root 4666u  a_inode               0,13          0     12544 [eventfd]
```

## Possible Solution

close eventfd when delete CQ.

## Steps to Reproduce

1. start vhost-nvme target
2. start qemu with multiple devices with multiple queues
3. check opened eventfd by vhost-nvme target: lsof -p <pid of vhost nvme target>
4. kill qemu or stop VM by poweroff
5. check opened eventfd by vhost-nvme target: lsof -p <pid of vhost nvme target>
6. repeat steps 1-5 mane times again leading to eventfd leak exceeding maximum eventfd number. 

## Context (Environment including OS version, SPDK version, etc.)

SPDK v20.04: vhost-nvme
Qemu Version: qemu v2.12 patched with newest vhost-nvme feature from SPDK team.

**Comment by tomzawadzki** [comment]
Hi @YamboZhou vhost-nvme is no longer supported in SPDK [[1](https://github.com/spdk/spdk/commit/6bd7bd0da2ca5f5045f071b8e48dabebe26974aa)]. The suggested approach to exposing NVMe devices to the VMs is vfio-user [[2](https://spdk.io/news/2021/05/04/vfio-user/)][[3](https://github.com/nutanix/libvfio-user)][[4](https://github.com/nutanix/libvfio-user/blob/master/docs/spdk.md)].

Please note that at this time only SPDK v22.01 LTS is supported.

> I notice vhost-blk/scsi use the same mechanism for CQ notification as vhost-nvme so that maybe they have same issues.

Would you be able to check if the vhost-blk/scsi show the same errors as you expect ?

**Comment by changpe1** [comment]
@YamboZhou I think this issue is related with vhost-nvme QEMU driver, for rebooting and shutdown cases, you may need to add the cleanup in vhost-nvme QEMU driver. E.g: for CREATE IO CQ command, cleanup the old eventfd, and create a new one for it.

**Comment by YamboZhou** [comment]
@changpe1 Hi Changpeng, when qemu open an eventfd and then send it to vhost target, it will duplicate this eventfd. Hence this eventfd should be closed twice. (one from qemu and one from vhost target). Otherwise, eventfd will leak in vhost target side instead of qemu side.

Let me try whether vhost-blk/scsi has the same issue. @tomzawadzki

**Comment by tomzawadzki** [comment]
@YamboZhou Any updates on reproducing it with vhost-blk/scsi ?

**Comment by changpe1** [comment]
The issue here doesn't exist with vhost-blk/scsi, so closing it now. @YamboZhou as I mentioned above, you may need to add fixes in QEMU to close old CQ FDs when VM rebooting.
