### ISSUE TITLE
[nvme_cli_cuse]  NVMe status: DATA_XFER_ERROR: Error while trying to transfer the data or metadata(0x2004)

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2389]
# CI Intermittent Failure

00:05:34.194  [2022-02-21 10:40:57.510009] nvme_qpair.c: 270:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:895 nsid:1 lba:0 len:1 PRP1 0x0 PRP2 0x0
00:05:34.194  [2022-02-21 10:40:57.510042] nvme_qpair.c: 454:spdk_nvme_print_completion: *NOTICE*: DATA TRANSFER ERROR (00/04) qid:1 cid:895 cdw0:0 sqhd:0001 p:1 m:1 dnr:0
00:05:34.194  NVMe status: DATA_XFER_ERROR: Error while trying to transfer the data or metadata(0x2004)
00:05:34.194    10:40:57	-- cuse/spdk_nvme_cli_cuse.sh@98 -- # trap - ERR
00:05:34.194    10:40:57	-- cuse/spdk_nvme_cli_cuse.sh@98 -- # print_backtrace
00:05:34.194    10:40:57	-- common/autotest_common.sh@994 -- # [[ ehxBET =~ e ]]
00:05:34.194    10:40:57	-- common/autotest_common.sh@996 -- # args=("${BASH_ARGV[@]}")
00:05:34.194    10:40:57	-- common/autotest_common.sh@996 -- # local args
00:05:34.194    10:40:57	-- common/autotest_common.sh@998 -- # xtrace_disable
00:05:34.194    10:40:57	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:34.194    10:40:57	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:34.194    10:40:57	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:34.194    10:40:57	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:34.194    10:40:57	-- common/autotest_common.sh@19 -- # set +x

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_71771.html

## Execution failed at

00:05:34.194  ========== Backtrace start: ==========
00:05:34.194  
00:05:34.194  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/spdk_nvme_cli_cuse.sh:98 -> main([])
00:05:34.194       ...
00:05:34.194     93  	
00:05:34.194     94  	rm -Rf $testdir/match_files
00:05:34.194     95  	
00:05:34.194     96  	# Verify read/write path
00:05:34.194     97  	tr < /dev/urandom -dc "a-zA-Z0-9" | fold -w 512 | head -n 1 > $testdir/write_file
00:05:34.194  => 98  	${NVME_CMD} write $ns --data-size=512 --data=$testdir/write_file
00:05:34.194     99  	${NVME_CMD} read $ns --data-size=512 --data=$testdir/read_file
00:05:34.194     100 	diff --ignore-trailing-space $testdir/write_file $testdir/read_file
00:05:34.194     101 	rm -f $testdir/write_file $testdir/read_file
00:05:34.194     102 	
00:05:34.194     103 	# Verify admin cmd when no data is transferred,
00:05:34.194       ...
00:05:34.194  
00:05:34.194  ========== Backtrace end ==========
00:05:34.194    10:40:57	-- common/autotest_common.sh@1034 -- # xtrace_enable
00:05:34.194    10:40:57	-- common/autotest_common.sh@1035 -- # return 0
00:05:34.194   10:40:57	-- cuse/spdk_nvme_cli_cuse.sh@1 -- # kill -9 47105
00:05:34.194   10:40:57	-- cuse/spdk_nvme_cli_cuse.sh@1 -- # exit 1
00:05:34.194    10:40:57	-- common/autotest_common.sh@966 -- # trap - ERR
00:05:34.194    10:40:57	-- common/autotest_common.sh@966 -- # print_backtrace
00:05:34.194    10:40:57	-- common/autotest_common.sh@994 -- # [[ ehxBET =~ e ]]
00:05:34.194    10:40:57	-- common/autotest_common.sh@996 -- # args=("${BASH_ARGV[@]}")
00:05:34.194    10:40:57	-- common/autotest_common.sh@996 -- # local args
00:05:34.194    10:40:57	-- common/autotest_common.sh@998 -- # xtrace_disable
00:05:34.194    10:40:57	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:34.194    10:40:57	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:34.194    10:40:57	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:34.194    10:40:57	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:34.194    10:40:57	-- common/autotest_common.sh@19 -- # set +x
00:05:34.194  ========== Backtrace start: ==========
00:05:34.194  
00:05:34.194  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:966 -> run_test(["nvme_cli_cuse"],["/var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/spdk_nvme_cli_cuse.sh"])
00:05:34.194       ...
00:05:34.194     961 		timing_enter $test_name
00:05:34.194     962 		echo "************************************"
00:05:34.194     963 		echo "START TEST $test_name"
00:05:34.194     964 		echo "************************************"
00:05:34.194     965 		xtrace_restore
00:05:34.194  => 966 		time "$@"
00:05:34.194     967 		xtrace_disable
00:05:34.194     968 		echo "************************************"
00:05:34.194     969 		echo "END TEST $test_name"
00:05:34.194     970 		echo "************************************"
00:05:34.194     971 		timing_exit $test_name
00:05:34.194       ...
00:05:34.194  in test/nvme/cuse/nvme_cuse.sh:16 -> main([])
00:05:34.194       ...
00:05:34.194     11  	fi
00:05:34.194     12  	
00:05:34.194     13  	modprobe cuse
00:05:34.195     14  	run_test "nvme_cuse_app" $testdir/cuse
00:05:34.195     15  	run_test "nvme_cuse_rpc" $testdir/nvme_cuse_rpc.sh
00:05:34.195  => 16  	run_test "nvme_cli_cuse" $testdir/spdk_nvme_cli_cuse.sh
00:05:34.195     17  	run_test "nvme_smartctl_cuse" $testdir/spdk_smartctl_cuse.sh
00:05:34.195     18  	
00:05:34.195     19  	# Only run Namespace management test case when such device is present
00:05:34.195     20  	bdfs=$(get_nvme_bdfs)
00:05:34.195     21  	
00:05:34.195       ...
00:05:34.195  
00:05:34.195  ========== Backtrace end ==========
00:05:34.195    10:40:57	-- common/autotest_common.sh@1034 -- # xtrace_enable
00:05:34.195    10:40:57	-- common/autotest_common.sh@1035 -- # return 0
00:05:34.195  
00:05:34.195  real	0m6.339s
00:05:34.195  user	0m1.448s
00:05:34.195  sys	0m0.643s
00:05:34.195    10:40:57	-- common/autotest_common.sh@966 -- # trap - ERR
00:05:34.195    10:40:57	-- common/autotest_common.sh@966 -- # print_backtrace
00:05:34.195    10:40:57	-- common/autotest_common.sh@994 -- # [[ ehxBET =~ e ]]
00:05:34.195    10:40:57	-- common/autotest_common.sh@996 -- # args=("${BASH_ARGV[@]}")
00:05:34.195    10:40:57	-- common/autotest_common.sh@996 -- # local args
00:05:34.195    10:40:57	-- common/autotest_common.sh@998 -- # xtrace_disable
00:05:34.195    10:40:57	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:34.195    10:40:57	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:34.195    10:40:57	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:34.195    10:40:57	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:34.195    10:40:57	-- common/autotest_common.sh@19 -- # set +x
00:05:34.195  ========== Backtrace start: ==========
00:05:34.195  
00:05:34.195  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:966 -> run_test(["nvme_cuse"],["test/nvme/cuse/nvme_cuse.sh"])
00:05:34.195       ...
00:05:34.195     961 		timing_enter $test_name
00:05:34.195     962 		echo "************************************"
00:05:34.195     963 		echo "START TEST $test_name"
00:05:34.195     964 		echo "************************************"
00:05:34.195     965 		xtrace_restore
00:05:34.195  => 966 		time "$@"
00:05:34.195     967 		xtrace_disable
00:05:34.195     968 		echo "************************************"
00:05:34.195     969 		echo "END TEST $test_name"
00:05:34.195     970 		echo "************************************"
00:05:34.195     971 		timing_exit $test_name
00:05:34.195       ...
00:05:34.195  in /var/jenkins/workspace/nvme-phy-autotest/spdk/autotest.sh:201 -> main(["autorun-spdk.conf"])
00:05:34.195       ...
00:05:34.195     196 			fi
00:05:34.195     197 			if [[ $SPDK_TEST_NVME_BP -eq 1 ]]; then
00:05:34.195     198 				run_test "nvme_bp" test/nvme/nvme_bp.sh
00:05:34.195     199 			fi
00:05:34.195     200 			if [[ $SPDK_TEST_NVME_CUSE -eq 1 ]]; then
00:05:34.195  => 201 				run_test "nvme_cuse" test/nvme/cuse/nvme_cuse.sh
00:05:34.195     202 			fi
00:05:34.195     203 			if [[ $SPDK_TEST_NVME_CMB -eq 1 ]]; then
00:05:34.195     204 				run_test "nvme_cmb" test/nvme/cmb/cmb.sh
00:05:34.195     205 			fi
00:05:34.195     206 	
00:05:34.195       ...
00:05:34.195  
00:05:34.195  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_71771.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_71776.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_71856.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_71836.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_71834.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_71807.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_71874.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_71965.html

**Comment by jimharris** [comment]
All of these failures are on GP16.  I spot checked a few other passing nvme-phy-autotest runs, and none of them were on GP16.

@karlatec or @xjjx, can you double check the nvme-cli version on that system, and compare it to other systems?

**Comment by karlatec** [comment]
The version is in fact different

GP16:
```
[sys_sgci@spdk-GP-16 ~]$ nvme --version
nvme version 1.11.1
[sys_sgci@spdk-GP-16 ~]$ /usr/local/src/nvme-cli/nvme --version
nvme version 1.15
```

Random other system:
```
[sys_sgci@spdk-GP-15 ~]$ nvme --version
nvme version 1.11.1
[sys_sgci@spdk-GP-15 ~]$ /usr/local/src/nvme-cli/nvme --version
nvme version 1.16
```

GP16 is one of the systems we keep booted with older OS image version because of rdma-core issue in [Fedora 34 and Fedora35](https://github.com/spdk/spdk/issues/2310).
@xjjx perhaps we should keep those systems with only `nvmf_f33` label and remove the rest, so that these nodes only  pick up NVMe-oF RDMA tests?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_72039.html

**Comment by karlatec** [comment]
@xjjx  did not notice my question so I removed labels from node configuration myself :) Should be fine now.

**Comment by jimharris** [comment]
> @xjjx did not notice my question so I removed labels from node configuration myself :) Should be fine now.

Thanks @karlatec.  I'm going to assign this issue to you, feel free to close it once you think it's appropriate.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_71915.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_71909.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_71934.html

**Comment by tomzawadzki** [comment]
[Bug scrub] @karlatec Could you check if the last 3 logs come from the node that is no longer part of the configuration for nvme-cli-cuse tests ? If yes, this issue could be closed.

**Comment by karlatec** [comment]
All 3 logs were run on GP16 and failing builds have failed before I removed the label from the node. I think we can close this one.
