### ISSUE TITLE
 A positive test case response an error in pmem.sh

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#239]
# **Problem Statement**

A pmem.sh's case "create_pmem_pool_tc3" response an error in  in Building Pool , but this is a positive test case.

error log as bellow:
Now running: create_pmem_pool_tc3
[
  {
    "block_size": 512, 
    "num_blocks": 519896
  }
]
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0", 
  "params": {
    "pmem_file": "/home/sys_sgsw/build_pool/agent/repo/test/pmem/pool_file"
  }, 
  "method": "pmem_pool_info", 
  "id": 1
}
response:
{
  "message": "Invalid parameters", 
  "code": -32602
}

Test plan:
https://review.gerrithub.io/#/c/378618/18/test/pmem/test_plan.md
create_pmem_pool_tc3
Positive test case for creating a new pmem pool on disk space.
Steps & expected results:
- call create_pmem_pool with correct path argument,
blocksize=512 and total size=256MB
- call return code = 0
- call pmem_pool_info and check that pmem file was created
- call return code = 0
- call delete_pmem_pool on previously created pmem
- return code = 0 and no error code

# **Steps to reproduce**

Run command ./test/pmem/pmem.sh

**Comment by wanghailiangx** [comment]
A patch has been raised to resolve it. https://review.gerrithub.io/#/c/398469/

**Comment by dverkamp-intel** [comment]
The patch above has been abandoned, and a comment was posted saying "Actually pmem_pool_info check is in the test plan so it should stay..."

Can someone clarify what the original issue is and whether it is still present? Do we need a test change, or a test plan change, or is this not an issue at all?

**Comment by dverkamp-intel** [comment]
Ping - is this issue still applicable?

**Comment by wanghailiangx** [comment]
Originally, I found an error response in a positive test case in "SPDK NIGHTLY TEST RUN“, that is above "create_pmem_pool_tc3". It is still present now.
Paweł's team replied this is reasonable in email at that time, and then raised a patch to do some optimization. At last the patch above was abandoned. So we can maintain the original case well, it can be closed.
