### ISSUE TITLE
[acl] collect_setup_devs function fails

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2397]
```
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # [[ ioatdma == nvme ]]
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # continue
00:07:35.668   17:33:29	-- setup/acl.sh@14 -- # read -r _ dev _ _ _ driver _
00:07:35.668   17:33:29	-- setup/acl.sh@15 -- # [[ 0000:80:04.5 == *:*:*.* ]]
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # [[ ioatdma == nvme ]]
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # continue
00:07:35.668   17:33:29	-- setup/acl.sh@14 -- # read -r _ dev _ _ _ driver _
00:07:35.668   17:33:29	-- setup/acl.sh@15 -- # [[ 0000:80:04.6 == *:*:*.* ]]
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # [[ ioatdma == nvme ]]
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # continue
00:07:35.668   17:33:29	-- setup/acl.sh@14 -- # read -r _ dev _ _ _ driver _
00:07:35.668   17:33:29	-- setup/acl.sh@15 -- # [[ 0000:80:04.7 == *:*:*.* ]]
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # [[ ioatdma == nvme ]]
00:07:35.668   17:33:29	-- setup/acl.sh@16 -- # continue
00:07:35.668   17:33:29	-- setup/acl.sh@14 -- # read -r _ dev _ _ _ driver _
00:07:35.668   17:33:29	-- setup/acl.sh@20 -- # (( 0 > 0 ))
00:07:35.668    17:33:29	-- setup/acl.sh@20 -- # trap - ERR
00:07:35.668    17:33:29	-- setup/acl.sh@20 -- # print_backtrace
00:07:35.668    17:33:29	-- common/autotest_common.sh@994 -- # [[ ehxBET =~ e ]]
00:07:35.668    17:33:29	-- common/autotest_common.sh@996 -- # args=()
00:07:35.668    17:33:29	-- common/autotest_common.sh@996 -- # local args
00:07:35.668    17:33:29	-- common/autotest_common.sh@998 -- # xtrace_disable
00:07:35.668    17:33:29	-- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
00:07:35.668    17:33:29	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:07:35.668    17:33:29	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:07:35.668    17:33:29	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:07:35.668    17:33:29	-- common/autotest_common.sh@19 -- # set +x
00:07:35.668  ========== Backtrace start: ==========
00:07:35.668  
00:07:35.668  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/setup/acl.sh:20 -> collect_setup_devs([])
00:07:35.668       ...
00:07:35.668     15  			[[ $dev == *:*:*.* ]] || continue
00:07:35.668     16  			[[ $driver == nvme ]] || continue
00:07:35.668     17  			[[ ${zoned_devs[*]} == *"$dev"* ]] && continue
00:07:35.668     18  			devs+=("$dev") drivers["$dev"]=$driver
00:07:35.668     19  		done < <(setup output status)
00:07:35.668  => 20  		((${#devs[@]} > 0))
00:07:35.668     21  	}
00:07:35.668     22  	
00:07:35.668     23  	verify() {
00:07:35.668     24  		local dev driver
00:07:35.668     25  	
00:07:35.668       ...
00:07:35.668  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/setup/acl.sh:48 -> main([])
00:07:35.668       ...
00:07:35.668     43  		verify "${devs[@]:1}"
00:07:35.668     44  		setup reset
00:07:35.668     45  	}
00:07:35.668     46  	
00:07:35.668     47  	setup reset
00:07:35.668  => 48  	collect_setup_devs
00:07:35.668     49  	
00:07:35.668     50  	run_test "denied" denied
00:07:35.668     51  	run_test "allowed" allowed
00:07:35.668       ...
00:07:35.668  
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72175.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72172.html

**Comment by jimharris** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/72174/archive/nvme-phy-autotest/index.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72179.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72183.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72182.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_72188.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72294.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72298.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72306.html

**Comment by mikeBashStuff** [comment]
From the logs it seems that WFP15 doesn't have a nvme driver installed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_72307.html

**Comment by jimharris** [comment]
> From the logs it seems that WFP15 doesn't have a nvme driver installed.

@karlatec could you take a look at WFP15?  Seems this issue is affecting a lot of test runs.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72311.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_72382.html

**Comment by karlatec** [comment]
WFP15 responsible for majority of these failures did not have a NVMe disk present. The reason was a faulty connection of cable used for hotplug tests. Adjusted hotplug connector and now NVMe drive is visible. Leaving the issue open until the end of week to see if this is resolved.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_72641.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72353.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72607.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72608.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72619.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72618.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72627.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72629.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72631.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_72634.html

**Comment by karlatec** [comment]
Same issue with WFP13 and WFP14 after yesterday HW modification in server room. 
Disconnected HW hotplug  boards. Both platform should not cause any more issues from now on.

**Comment by karlatec** [comment]
Seems this is fixed for now. @tomzawadzki  we can close this on next community meeting.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_72918.html

**Comment by karlatec** [comment]
Alright, so this time the issue was one of the systems not rebooting properly after failed builds. Fixed that. Hopefully this time no more reports of this issue show up.

**Comment by tomzawadzki** [comment]
This issue has not occurred in over two weeks after fixing the infrastructure issue. Can be closed.
