### ISSUE TITLE
[nvmf-llvm-fuzz]: The limitation of NUM_FUZZERS is 9

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2398]
# Bug report

The limitation of NUM_FUZZERS is 9

## Expected Behavior

Should no limitation about this fuzzer number

## Current Behavior

Invalid fuzz type 10 (max 9)
[2022-02-25 21:46:02.346066] app.c:1001:spdk_app_parse_args: *ERROR*: Parsing application specific arguments failed: -22

## Steps to Reproduce
1. Configuration and compile
`CC=clang-12 CXX=clang++-12 ./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --enable-ubsan --enable-coverage --without-isal --with-shared`
`make -j`
2. mkdir and run command
`mkdir -p /tmp/corpus10`
`test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F 'trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420' -c /home/wenjun/spdk/test/nvmf/target/fuzz_json.conf -t 10 -D /tmp/corpus10 -Z 10`
3. Error information as below
`Invalid fuzz type 10 (max 9)
[2022-02-25 21:46:02.346066] app.c:1001:spdk_app_parse_args: *ERROR*: Parsing application specific arguments failed: -22`

## Context (Environment including OS version, SPDK version, etc.)
OS: `Fedora34`
SPDK Version: ecdbaa2310e243e83095396942b888267bbdb151

**Comment by jimharris** [comment]
Hi @junwenx,

I am not able to reproduce this issue.  Can you please make sure that your llvm_nvme_fuzz binary was actually built with this ecdbaa2 SPDK commit?  I notice that your configure line does not have --with-fuzzer option, so maybe you are using an older version of the llvm_nvme_fuzz binary that has a fewer number of fuzzers available.

-Jim

**Comment by junwenx** [comment]
@jimharris Sorry, I forgot to add --with-fuzzer=xxxx parameter in the configuration line, after add it, this is normal. Sorry for that, I think issue can be closed :)

**Comment by jimharris** [comment]
Thanks for the update!

**Comment by junwenx** [comment]
Hi @jimharris   Thank you for the support!
