### ISSUE TITLE
How to set DIF Mode in NVMe-oF controller ?

### ISSUE THREAD

**Issue by springeee** [spdk/spdk#2399]
Hi all:
SPDK 19.07 begin supports DIF mode per NVMe-oF transport(eg TCP), But I don't know how to set it .

My environment as follows:
SPDK nvme_tcp target is centos 8, with  intel X520 10G NIC , one nvme ssd support dif;
nvme_tcp initiator is oracle linux 8 , with  intel X520 10G NIC .

my step as follow:
1, install SPDK on centos8 ;
2,  format nvme ssd support dif
nvme format /dev/nvme0n1 -l 1 -i 1 -p 0 -m 1
3, 
./build/bin/nvmf_tgt

./scripts/setup.sh
./scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:b3:00.0
./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 NVMe1n1
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t TCP -a 11.11.11.71 -s 4420

4, on oracle linux 8 
nvme discover -t tcp -a 11.11.11.71 -s 4420
nvme connect -t tcp -n "nqn.2016-06.io.spdk:cnode1" -a 11.11.11.71 -s 4420

problem:
now I can see nvme1n1 on oracle linux 8, but there are have many error. and this disk cann't be read and write.
![image](https://user-images.githubusercontent.com/72604063/155670109-49400057-0bc6-464d-bad0-266a0690b8d9.png)

Could you please give me some advices? how to set NVMe_TCP to support dif?
Thanks,
Regards
Spring

**Comment by changpe1** [comment]
@springeee if you are using Linux kernel NVMe initiator driver, I remembered that the DIF support in kernel isn't enabled by default, so you may check your kernel configuration first. CONFIG_BLK_DEV_INTEGRITY_T10 and CONFIG_BLK_DEV_INTEGRITY are the two options in my platform.

**Comment by springeee** [comment]
> @springeee if you are using Linux kernel NVMe initiator driver, I remembered that the DIF support in kernel isn't enabled by default, so you may check your kernel configuration first. CONFIG_BLK_DEV_INTEGRITY_T10 and CONFIG_BLK_DEV_INTEGRITY are the two options in my platform.

@changpe1 , thanks for your reply.
from the ./scripts/rpc.py nvmf_create_transport --help message, we can see 
-f, --dif-insert-or-strip
                        Enable DIF insert/strip. Relevant only for TCP transport
from this : ./scripts/rpc.py bdev_nvme_attach_controller --help
-r, --prchk-reftag    Enable checking of PI reference tag for I/O
                        processing.
  -g, --prchk-guard     Enable checking of PI guard for I/O processing.

so  create tgt step, I add -f and -g ， as follows:
./scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192 -f 
./scripts/rpc.py bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:b3:00.0 -g
                    
now  ,on oracle linux 8 I can read and write the nvme disk .
and I'm not sure , the step if ok ?

Thanks,
Regards
springee

**Comment by changpe1** [comment]
it's OK for the SPDK setup.

**Comment by springeee** [comment]
ok， Thanks
