### ISSUE TITLE
"setup.sh" doesn't seem to be working——"no NVMe controllers found"

### ISSUE THREAD

**Issue by weisonx** [spdk/spdk#2402]
# Bug report

## Current Behavior

lspci | grep Non:
    03:00.0 Non-Volatile memory controller: VMware Device 07f0
its class id (lspci -x):
    010802
When I run setup.sh, the setup.sh status display is as follows:  
>[root@localhost scripts]# ./setup.sh status
>Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB     1024 /   1024
>
>Type     BDF             Vendor Device NUMA    Driver           Device     Block 
NVMe     0000:03:00.0    15ad   07f0   0       -                          -          -

./setup.sh dmesg:
[  350.705222] genirq: Threaded irq requested with handler=NULL and !ONESHOT for irq 18
[  350.705869] uio_pci_generic: probe of 0000:03:00.0 failed with error -22

but run the "./build/exsamples/hello_world":
 >  EAL: No available 1048576 kB hugepages reported
    TELEMETRY: No legacy callbacks, legacy socket not created
    Initializing NVMe Controllers
    no NVMe controllers found

## Context (Environment including OS version, SPDK version, etc.)
>VMware Workstation Player16-CentOS-8, SPDK v22

**Comment by changpe1** [comment]
Did you install your OS image on this NVMe drive or not? SPDK don't use the drives which have valid filesystem partition.

**Comment by weisonx** [comment]
No, it is a new nvme disk without any filestystem.

**Comment by weisonx** [comment]
Thanks Jim. 
Updating the kernel solved this problem
