### ISSUE TITLE
DSA device cannot be properly initialized

### ISSUE THREAD

**Issue by MengjinWu** [spdk/spdk#2408]
# Bug report

I pulled the latest version of the code, but found that recent changes prevented the DSA device from being properly initialized.

Using following command:

`sudo ./build/examples/idxd_perf -t 10 -w crc32c -y`

It will return:

```
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-03-02 17:22:38.734498] idxd_user.c: 128:idxd_wait_cmd: *ERROR*: Command status reg reports error 0x18
[2022-03-02 17:22:38.734591] idxd_user.c: 399:idxd_device_configure: *ERROR*: Error enabling device 4294967274
[2022-03-02 17:22:38.734613] idxd_user.c: 128:idxd_wait_cmd: *ERROR*: Command status reg reports error 0x31
[2022-03-02 17:22:38.734629] idxd_user.c: 191:idxd_disable_dev: *ERROR*: Error disabling device 4294967274
free(): double free detected in tcache 2
Aborted
```

Similarly, using RPC commands will produce the same problem:

```
sudo ./build/bin/nvmf_tgt -r /tmp/spdk1.sock -m 0x4 --wait-for-rpc & 
sleep 2
scripts/rpc.py -s /tmp/spdk1.sock idxd_scan_accel_engine -c 1
scripts/rpc.py -s /tmp/spdk1.sock framework_start_init
```

In a past version of the code, DSA can be used correctly. 
[bdev/nvme: Remove ctrlr_ch from group's list in error case](https://review.spdk.io/gerrit/c/spdk/spdk/+/10840)

**Comment by peluse** [comment]
This was just reported this morning out of our lab, something went in post release that is causing it.  I will address it today.

**Comment by peluse** [comment]
@MengjinWu can you please specify the commit that you are using? It could be relevant when I look at this in a few hours

**Comment by peluse** [comment]
@MengjinWu  the fix is here: https://review.spdk.io/gerrit/c/spdk/spdk/+/11723

**Comment by KariukiJ** [comment]
I had the same issue yesterday with master. Once patch 11723 was merged, I pulled down the latest code and the issue is resolved.

**Comment by peluse** [comment]
Thanks John.  @MengjinWu please confirm this works for you so we can close the issue.

**Comment by MengjinWu** [comment]
Thanks @peluse. I pulled down the latest code and it is resolved. Thanks!
