### ISSUE TITLE
Failure to build --with-reduce

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2411]
Tried on master as well as 22.01, suspect this has something to do with MLX support being added for compression a while back.  Will dig in a bit and add more info soon but here is the failure.

/usr/bin/ld.bfd: /home/peluse/spdk/dpdk/build/lib/librte_common_mlx5.a(common_mlx5_linux_mlx5_glue.c.o): undefined reference to symbol 'ibv_ack_async_event@@IBVERBS_1.1'
/usr/bin/ld.bfd: /usr/lib/x86_64-linux-gnu/libibverbs.so.1: error adding symbols: DSO missing from command line

@karlatec can you point me to a CI system that builds with reduce?

**Comment by peluse** [comment]
Looks like its been broken since Aug when MLX support was added as I suspected.

mk: Enable build of mlx5_pci compress PMD
https://review.spdk.io/gerrit/c/spdk/spdk/+/8780/8

@karlatec lets find out for sure why CI didn't catch this.

**Comment by jimharris** [comment]
If you add --with-rdma, it should work.

It's likely CI didn't catch this because wherever we add --with-reduce, --with-rdma is included as well.

**Comment by jimharris** [comment]
> If you add --with-rdma, it should work.
> 
> It's likely CI didn't catch this because wherever we add --with-reduce, --with-rdma is included as well.

https://review.spdk.io/gerrit/c/spdk/spdk/+/11795 changes configure to throw an error if --with-reduce is specified without --with-rdma.

**Comment by peluse** [comment]
Thanks Jim, I'll try that in just a bit.  Lets not close this until we get doc updates merged though.  Nobody would ever guess that you need RDMA to do crypto/compression via DPDK. Would even be better if we add a config option --with-mlxoffload or something that just added --with-rdma for the user

**Comment by jimharris** [comment]
We should probably just enable --with-rdma by default, at least on Linux.

**Comment by peluse** [comment]
OK, builds with rdma included.  I'll update the doc page tomorrow and submit a patch to always config rmda

**Comment by AlekseyMarchuk** [comment]
Hi @jimharris @peluse 

Sorry, I missed this dependency. mlx5_pci compress PMD requires linkage with libibverbs. 
Maybe that is not obvious that --with-reduce requires --with-rdma, I think this problem can be solved in another way. There is patch that adds mlx5_pci crypto PMD https://review.spdk.io/gerrit/c/spdk/spdk/+/11620
This patch adds linkage of libibverbs when mlx5_pci compress/crypto are used. Please check `lib/env_dpdk/env.mk` file in the patchset

**Comment by AlekseyMarchuk** [comment]
Now this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11620 checks for libmlx5 and libibverbs in the system and doesn't enable mlx5 cyrpto/compress PMD if these libraries were not found. That means that `--with-reduce` works independently of `--with-rdma`

**Comment by peluse** [comment]
Fantastic and works great for me!  Can we add fixes #2411 to the commit message so this gets closed once merged? Much better solution!!

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/11620 is now merged.
