### ISSUE TITLE
Valgrind not tested on Jenkins CI

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2422]
# Bug report

Valgrind is enabled via `SPDK_RUN_VALGRIND=1` on following jobs:
- unittest-vg-autotest
- freebsd-vg-autotest
- clang-vg-autotest

Despite that it's not actually executed due snippet below, where `valgrind` variable is emptied due to ASAN being enabled.
https://github.com/spdk/spdk/blob/c8837711239bdf69654102a641b25d977bb78ab9/test/unit/unittest.sh#L139-L147

It was not caught on CI because verification being done via `run_test` only checking for test variable, not verifying the actual execution of tests with valgrind.
https://github.com/spdk/spdk/blob/c8837711239bdf69654102a641b25d977bb78ab9/autobuild.sh#L336-L338

## Expected Behavior

Valgrind can be run only when ASAN is not enabled and in applications that do not Hugepages (so ones not linked with DPDK).
This leaves unit tests, which are already can be configured to run with valgrind.

 `unittest-vg-autotest` and `clang-vg-autotest` both run unit tests, but neither can have the ASAN disabled if coverage of testing is not to be reduced. Clang and GCC versions of ASAN are bit different. This most likely implies a new job is required.

## Possible Solution

1) SPDK_RUN_VALGRIND and SPDK_RUN_ASAN need to be checked against each other. If both are enabled on a job, a failure should be produced.
2) `run_test "valgrind"` should be moved from `autobuild.sh` to `unitest.sh` and be executed only if `valgrind` variable is not empty.
3) A job needs to be selected/created to run unit tests with valgrind.

**Comment by kgodzwox** [comment]
Working on it
https://review.spdk.io/gerrit/c/spdk/spdk/+/11998
