### ISSUE TITLE
Long delay in unbinding VMD devices on Icelake with SPDK setup script

### ISSUE THREAD

**Issue by sydneyvanda** [spdk/spdk#2423]
# Bug report

This issue was found when testing on IceLake nodes with VMD devices on SLES 15.3 OS. Currently takes about 4 minutes to unbind 16 NVMe SSDs behind 4 VMD addresses from the Kernel (using the SPDK setup script). 

On a similar IceLake system with SLES 15.3 and VMD disabled, it took ~5 seconds to unbind 8 NVMe SSDs with the SPDK setup script.
On another IceLake system (Wilson City Sample) with CentOS 8 and VMD enabled, it took ~26 seconds to unbind 8 NVMe SSDs behind 2 VMD addresses with the SPDK setup script.
On a Cascade Lake system with SLES 15.3 and VMD enabled, it took ~15 seconds to unbind 10 NVMe SSDs behind 3 VMD addresses with the SPDK setup script.

## Expected Behavior

Unbinding VMD devices should be comparable to unbinding NVMe SSDs in duration, not significantly larger.

## Current Behavior

**System 1 Test: Icelake System, SLES 15.3, VMD enabled**

OS Version: "SUSE Linux Enterprise Server 15 SP3", Linux version 5.3.18-57-default (geeko@buildhost) (gcc version 7.5.0 (SUSE Linux)) #1 SMP Wed Apr 28 10:54:41 UTC 2021 (ba3c2e9)

SSDs: 16 SSDs, model: SAMSUNG MZWLR15THALA-00007

When tested with SPDK source (v21.10-rc1, commit 98b1301fe4 from Oct 22 2021 ), script took ~3 min 40 sec to fully run:

daos5:~ # PCI_ALLOWED="0000:4a:00.5 0000:64:00.5 0000:97:00.5 0000:e2:00.5" /home/smvanda/SPDK_21.10/scripts/setup.sh
0000:e2:00.5 (8086 28c0): vmd -> vfio-pci
0000:97:00.5 (8086 28c0): vmd -> vfio-pci
0000:64:00.5 (8086 28c0): vmd -> vfio-pci
0000:4a:00.5 (8086 28c0): vmd -> vfio-pci

Also tested on SPDK source v22.01 (most recent release tag), and same behavior noticed with the same delay.

__________________________________________________________________________________________________________________________________

**System 2 Test: Icelake System, SLES 15.3, VMD disabled**

OS Version: "SUSE Linux Enterprise Server 15 SP3", Linux version 5.3.18-57-default (geeko@buildhost) (gcc version 7.5.0 (SUSE Linux)) #1 SMP Wed Apr 28 10:54:41 UTC 2021 (ba3c2e9)

SSDs: 8 SSDs, model: SAMSUNG MZWLR3T8HBLS-00007

When tested with SPDK source (v21.10-rc1, commit 98b1301fe4 from Oct 22 2021 ), script took ~5 sec to fully run:

daos2:~ # PCI_ALLOWED="0000:65:00.0 0000:67:00.0 0000:69:00.0 0000:6b:00.0 0000:e3:00.0 0000:e5:00.0 0000:e7:00.0 0000:e9:00.0" /home/smvanda/SPDK_21.10/scripts/setup.sh
0000:6b:00.0 (144d a824): nvme -> vfio-pci
0000:e9:00.0 (144d a824): nvme -> vfio-pci
0000:67:00.0 (144d a824): nvme -> vfio-pci
0000:e5:00.0 (144d a824): nvme -> vfio-pci
0000:69:00.0 (144d a824): nvme -> vfio-pci
0000:65:00.0 (144d a824): nvme -> vfio-pci
0000:e3:00.0 (144d a824): nvme -> vfio-pci
0000:e7:00.0 (144d a824): nvme -> vfio-pci

________________________________________________________________________________________________________________________________________

For comparison, when tested on SUSE on Cascade Lake, for 10 SSDs behind 3 VMD addresses (7 behind 1 VMD address, 2 behind 1 VMD address, and 1 behind another VMD address), it took ~15 sec for the SPDK v22.01 setup script to unbind.

OS Version: "openSUSE Leap 15.3", Linux version 5.3.18-59.10-default (geeko@buildhost) (gcc version 7.5.0 (SUSE Linux)) #1 SMP Fri Jun 25 12:36:56 UTC 2021 (6856d31)

SSDs: 10 SSDs, model: (8 ) INTEL SSDPE2KE016T8, (2) INTEL SSDPED1K750GA

_________________________________________________________________________________________________________________________________________

Also for comparison, tested on wolf-151 which is a Wilson City Sample of IceLake, 8 Samsung SSDs all behind 2 VMD addresses (4 behind each). it took ~26 seconds for the SPDK v22.01 setup script to unbind.

OS Version: “CentOS Linux 8”, Linux version 4.18.0-305.19.1.el8_4.x86_64 ([mockbuild@kbuilder.bsys.centos.org](mailto:mockbuild@kbuilder.bsys.centos.org)) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Wed Sep 15 15:39:39 UTC 2021

SSDs: 8 SSDs, model: Samsung Electronics Co Ltd NVMe SSD Controller PM173X

## Steps to Reproduce

1. PCI_ALLOWED="" /home/smvanda/SPDK_21.10/scripts/setup.sh

**Comment by jimharris** [comment]
Hi @sydneyvanda,

The differences between systems are more likely due to the SSDs, not the platform.  When the SSDs are unbound from their kernel driver, the kernel nvme driver does a full shutdown of the SSDs.  This is also done implicitly when you unbind the VMD endpoint that is in front of the NVMe SSD.  There can be very large differences between shutdown times between SSD models.  Note that the system that takes the longest has the most SSDs in it, and they are each 15+ TB in size.  So a fair comparison between these systems would use the same SSD model.

The setup.sh script for a long time has tried to unbind NVMe SSDs in parallel, specifically to speed up this process.  If you were to disable VMD on that first system, you'd probably see the elapsed time to unbind cut by a factor of 16, since the shutdown for all 16 SSDs would be happening in parallel.  But we only do this parallel unbind for NVMe devices - nothing else (including VMD).  We avoided doing this for ioat devices due to a kernel bug.  It's possible we could do it for VMD. in which case we might reduce by a factor of 4 - the 4 VMD devices that we are unbinding.  You can try this by changing this part of the setup.sh script:

```
        for bdf in "${!all_devices_d[@]}"; do
                if ((all_devices_d["$bdf"] == 0)); then
                        if [[ -n ${nvme_d["$bdf"]} ]]; then
                                # Some nvme controllers may take significant amount of time while being
                                # unbound from the driver. Put that task into background to speed up the
                                # whole process. Currently this is done only for the devices bound to the
                                # nvme driver as other, i.e., ioatdma's, trigger a kernel BUG when being
                                # unbound in parallel. See https://bugzilla.kernel.org/show_bug.cgi?id=209041.
                                linux_bind_driver "$bdf" "$driver_name" &
                        else
                                linux_bind_driver "$bdf" "$driver_name"
                        fi
                fi
        done
 ```

Change the nvme_d array reference there to vmd_d.

I think any further improvement would require unbinding the NVMe SSDs (without binding them to uio/vfio) in parallel, followed by unbinding the VMD devices from kernel and binding them to vfio-pci.  Maybe we could support something like DRIVER_OVERRIDE="none" which would cause linux_bind_driver() to just unbind from the current driver and not bind to a new one.  That's not there today but probably wouldn't be difficult to add.

**Comment by ravalsam** [comment]
Hi @jimharris ,

@sydneyvanda will be on leave so I will give it try the setup.sh and let you know the result.

**Comment by ravalsam** [comment]
Hello @jimharris 

So I tried on daos5 and time got reduced from 3 min 40 seconds to 56 min.

**With original setup.sh:**
`time PCI_ALLOWED='0000:4a:00.5 0000:64:00.5 0000:97:00.5 0000:e2:00.5' /usr/share/daos/control/../../spdk/scripts/setup.sh
10000:81:00.0 (144d a824): Skipping denied controller at 10000:81:00.0
10000:82:00.0 (144d a824): Skipping denied controller at 10000:82:00.0
10000:83:00.0 (144d a824): Skipping denied controller at 10000:83:00.0
10000:84:00.0 (144d a824): Skipping denied controller at 10000:84:00.0
10001:81:00.0 (144d a824): Skipping denied controller at 10001:81:00.0
10001:82:00.0 (144d a824): Skipping denied controller at 10001:82:00.0
10001:83:00.0 (144d a824): Skipping denied controller at 10001:83:00.0
10001:84:00.0 (144d a824): Skipping denied controller at 10001:84:00.0
10002:01:00.0 (144d a824): Skipping denied controller at 10002:01:00.0
10002:02:00.0 (144d a824): Skipping denied controller at 10002:02:00.0
10002:03:00.0 (144d a824): Skipping denied controller at 10002:03:00.0
10002:04:00.0 (144d a824): Skipping denied controller at 10002:04:00.0
10003:01:00.0 (144d a824): Skipping denied controller at 10003:01:00.0
10003:02:00.0 (144d a824): Skipping denied controller at 10003:02:00.0
10003:03:00.0 (144d a824): Skipping denied controller at 10003:03:00.0
10003:04:00.0 (144d a824): Skipping denied controller at 10003:04:00.0
0000:00:01.0 (8086 0b00): Skipping denied controller at 0000:00:01.0
0000:00:01.1 (8086 0b00): Skipping denied controller at 0000:00:01.1
0000:00:01.2 (8086 0b00): Skipping denied controller at 0000:00:01.2
0000:00:01.3 (8086 0b00): Skipping denied controller at 0000:00:01.3
0000:00:01.4 (8086 0b00): Skipping denied controller at 0000:00:01.4
0000:00:01.5 (8086 0b00): Skipping denied controller at 0000:00:01.5
0000:00:01.6 (8086 0b00): Skipping denied controller at 0000:00:01.6
0000:00:01.7 (8086 0b00): Skipping denied controller at 0000:00:01.7
0000:80:01.0 (8086 0b00): Skipping denied controller at 0000:80:01.0
0000:80:01.1 (8086 0b00): Skipping denied controller at 0000:80:01.1
0000:80:01.2 (8086 0b00): Skipping denied controller at 0000:80:01.2
0000:80:01.3 (8086 0b00): Skipping denied controller at 0000:80:01.3
0000:80:01.4 (8086 0b00): Skipping denied controller at 0000:80:01.4
0000:80:01.5 (8086 0b00): Skipping denied controller at 0000:80:01.5
0000:80:01.6 (8086 0b00): Skipping denied controller at 0000:80:01.6
0000:80:01.7 (8086 0b00): Skipping denied controller at 0000:80:01.7
0000:e2:00.5 (8086 28c0): vmd -> vfio-pci
0000:97:00.5 (8086 28c0): vmd -> vfio-pci
0000:64:00.5 (8086 28c0): vmd -> vfio-pci
0000:4a:00.5 (8086 28c0): vmd -> vfio-pci

real    3m38.491s
user    0m1.303s
sys     0m1.124s
`

**After changing it to Change the nvme_d array reference there to vmd_d as you sugested.:**
`time PCI_ALLOWED='0000:4a:00.5 0000:64:00.5 0000:97:00.5 0000:e2:00.5' /usr/share/daos/control/../../spdk/scripts/setup.sh
10000:01:00.0 (144d a824): Skipping denied controller at 10000:01:00.0
10000:02:00.0 (144d a824): Skipping denied controller at 10000:02:00.0
10000:03:00.0 (144d a824): Skipping denied controller at 10000:03:00.0
10000:04:00.0 (144d a824): Skipping denied controller at 10000:04:00.0
10001:01:00.0 (144d a824): Skipping denied controller at 10001:01:00.0
10001:02:00.0 (144d a824): Skipping denied controller at 10001:02:00.0
10001:03:00.0 (144d a824): Skipping denied controller at 10001:03:00.0
10001:04:00.0 (144d a824): Skipping denied controller at 10001:04:00.0
10002:81:00.0 (144d a824): Skipping denied controller at 10002:81:00.0
10002:82:00.0 (144d a824): Skipping denied controller at 10002:82:00.0
10002:83:00.0 (144d a824): Skipping denied controller at 10002:83:00.0
10002:84:00.0 (144d a824): Skipping denied controller at 10002:84:00.0
10003:81:00.0 (144d a824): Skipping denied controller at 10003:81:00.0
10003:82:00.0 (144d a824): Skipping denied controller at 10003:82:00.0
10003:83:00.0 (144d a824): Skipping denied controller at 10003:83:00.0
10003:84:00.0 (144d a824): Skipping denied controller at 10003:84:00.0
0000:00:01.0 (8086 0b00): Skipping denied controller at 0000:00:01.0
0000:00:01.1 (8086 0b00): Skipping denied controller at 0000:00:01.1
0000:00:01.2 (8086 0b00): Skipping denied controller at 0000:00:01.2
0000:00:01.3 (8086 0b00): Skipping denied controller at 0000:00:01.3
0000:00:01.4 (8086 0b00): Skipping denied controller at 0000:00:01.4
0000:00:01.5 (8086 0b00): Skipping denied controller at 0000:00:01.5
0000:00:01.6 (8086 0b00): Skipping denied controller at 0000:00:01.6
0000:00:01.7 (8086 0b00): Skipping denied controller at 0000:00:01.7
0000:80:01.0 (8086 0b00): Skipping denied controller at 0000:80:01.0
0000:80:01.1 (8086 0b00): Skipping denied controller at 0000:80:01.1
0000:80:01.2 (8086 0b00): Skipping denied controller at 0000:80:01.2
0000:80:01.3 (8086 0b00): Skipping denied controller at 0000:80:01.3
0000:80:01.4 (8086 0b00): Skipping denied controller at 0000:80:01.4
0000:80:01.5 (8086 0b00): Skipping denied controller at 0000:80:01.5
0000:80:01.6 (8086 0b00): Skipping denied controller at 0000:80:01.6
0000:80:01.7 (8086 0b00): Skipping denied controller at 0000:80:01.7
0000:64:00.5 (8086 28c0): vmd -> vfio-pci
0000:e2:00.5 (8086 28c0): vmd -> vfio-pci
0000:97:00.5 (8086 28c0): vmd -> vfio-pci
0000:4a:00.5 (8086 28c0): vmd -> vfio-pci

real    0m56.274s
user    0m1.310s
sys     0m1.181s
`

**Comment by tomzawadzki** [comment]
[Bug scrub] To make the process more clear to the users, two changes in the setup.sh would be benefical:
1) If a VMD device present, add message to communicate to the user to use next steps
2) Allow for DRIVER_OVERRIDE="none" to just unbind the driver without binding it to any other

After that the user could call the `PCI_ALLOWED="xxxx:xx:xx.x" setup.sh` to bind the devices behind VMD.

@ravalsam would be interested in modifying the setup.sh ?

**Comment by ravalsam** [comment]
@jimharris and @tomzawadzki,

So for option 1, it's just needs to print the message or script should also exit? I created the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12035 so feel free to update.

Can this be improve further as well?  I see only single VMD address (4 NVMe) is unbinding at a single given time. Can that also be done in parallel for all VMD address? So in that case time can be further reduce from 60 seconds to 15 seconds.

**Comment by jimharris** [comment]
> @jimharris and @tomzawadzki,
> 
> So for option 1, it's just needs to print the message or script should also exit? I created the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12035 so feel free to update.
> 
> Can this be improve further as well? I see only single VMD address (4 NVMe) is unbinding at a single given time. Can that also be done in parallel for all VMD address? So in that case time can be further reduce from 60 seconds to 15 seconds.

Hi @ravalsam,

Thanks for the patch!  I wouldn't expect to see only one VMD address unbinding at a time.  With the patch it should be unbinding all 4 VMD devices in parallel.  What I think you should see is that when you unbind each VMD device, it has to in turn shutdown each of the NVMe SSDs behind it, and those are done serially for each VMD device.  (Meaning 4 SSDs are shutdown in parallel, then the next 4, then the next 4, and finally the last 4).

I'm posting some other comments on the Gerrit review.

Thanks,

Jim

**Comment by ravalsam** [comment]
Updated the patch and verified locally. It's taking ~15 second to unbind the NVMe driver and later VMD.
Total unbind time with this two commands is under 20 seconds.

Please review the patch and let me know if any changes required.

daos-0003:~ # lsblk
NAME     MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0      7:0    0   1.4G  1 loop /root_ro
loop1      7:1    0     2G  0 loop /rootfs.rw
sda        8:0    0 447.1G  0 disk
sdb        8:16   0 447.1G  0 disk
nvme1n1  259:0    0    14T  0 disk
nvme2n1  259:1    0    14T  0 disk
nvme0n1  259:2    0    14T  0 disk
nvme3n1  259:3    0    14T  0 disk
nvme5n1  259:4    0    14T  0 disk
nvme6n1  259:5    0    14T  0 disk
nvme4n1  259:6    0    14T  0 disk
nvme7n1  259:7    0    14T  0 disk
nvme8n1  259:8    0    14T  0 disk
nvme10n1 259:9    0    14T  0 disk
nvme11n1 259:10   0    14T  0 disk
nvme9n1  259:11   0    14T  0 disk
nvme15n1 259:12   0    14T  0 disk
nvme12n1 259:13   0    14T  0 disk
nvme14n1 259:14   0    14T  0 disk
nvme13n1 259:15   0    14T  0 disk
pmem0    259:16   0   3.9T  0 disk
pmem1    259:17   0   3.9T  0 disk

daos-0003:~ # readlink -f /sys/bus/pci/devices/0000:e2:00.5/driver; readlink -f /sys/bus/pci/devices/10003:83:00.0/driver
/sys/bus/pci/drivers/vmd
/sys/bus/pci/drivers/nvme

daos-0003:~ # time PCI_ALLOWED='0000:4a:00.5 0000:64:00.5 0000:97:00.5 0000:e2:00.5' /usr/share/daos/control/../../spdk/scripts/setup_new.sh
10000:01:00.0 (144d a824): Skipping denied controller at 10000:01:00.0
10000:03:00.0 (144d a824): Skipping denied controller at 10000:03:00.0
10000:05:00.0 (144d a824): Skipping denied controller at 10000:05:00.0
10000:07:00.0 (144d a824): Skipping denied controller at 10000:07:00.0
10001:01:00.0 (144d a824): Skipping denied controller at 10001:01:00.0
10001:03:00.0 (144d a824): Skipping denied controller at 10001:03:00.0
10001:05:00.0 (144d a824): Skipping denied controller at 10001:05:00.0
10001:07:00.0 (144d a824): Skipping denied controller at 10001:07:00.0
10002:81:00.0 (144d a824): Skipping denied controller at 10002:81:00.0
10002:83:00.0 (144d a824): Skipping denied controller at 10002:83:00.0
10002:85:00.0 (144d a824): Skipping denied controller at 10002:85:00.0
10002:87:00.0 (144d a824): Skipping denied controller at 10002:87:00.0
10003:81:00.0 (144d a824): Skipping denied controller at 10003:81:00.0
10003:83:00.0 (144d a824): Skipping denied controller at 10003:83:00.0
10003:85:00.0 (144d a824): Skipping denied controller at 10003:85:00.0
10003:87:00.0 (144d a824): Skipping denied controller at 10003:87:00.0
0000:00:01.0 (8086 0b00): Skipping denied controller at 0000:00:01.0
0000:00:01.1 (8086 0b00): Skipping denied controller at 0000:00:01.1
0000:00:01.2 (8086 0b00): Skipping denied controller at 0000:00:01.2
0000:00:01.3 (8086 0b00): Skipping denied controller at 0000:00:01.3
0000:00:01.4 (8086 0b00): Skipping denied controller at 0000:00:01.4
0000:00:01.5 (8086 0b00): Skipping denied controller at 0000:00:01.5
0000:00:01.6 (8086 0b00): Skipping denied controller at 0000:00:01.6
0000:00:01.7 (8086 0b00): Skipping denied controller at 0000:00:01.7
0000:80:01.0 (8086 0b00): Skipping denied controller at 0000:80:01.0
0000:80:01.1 (8086 0b00): Skipping denied controller at 0000:80:01.1
0000:80:01.2 (8086 0b00): Skipping denied controller at 0000:80:01.2
0000:80:01.3 (8086 0b00): Skipping denied controller at 0000:80:01.3
0000:80:01.4 (8086 0b00): Skipping denied controller at 0000:80:01.4
0000:80:01.5 (8086 0b00): Skipping denied controller at 0000:80:01.5
0000:80:01.6 (8086 0b00): Skipping denied controller at 0000:80:01.6
0000:80:01.7 (8086 0b00): Skipping denied controller at 0000:80:01.7
VMD is enabled with NVMe driver loaded so use DRIVER_OVERRIDE="none" to just unbind the nvme driver only

real    0m2.462s
user    0m1.589s
sys     0m1.011s

daos-0003:~ # readlink -f /sys/bus/pci/devices/0000:e2:00.5/driver; readlink -f /sys/bus/pci/devices/10003:83:00.0/driver
/sys/bus/pci/drivers/vmd
/sys/bus/pci/drivers/nvme

daos-0003:~ # time DRIVER_OVERRIDE="none" /usr/share/daos/control/../../spdk/scripts/setup_new.sh
0000:4a:00.5 (8086 28c0): Skipping not allowed VMD controller at 0000:4a:00.5
0000:64:00.5 (8086 28c0): Skipping not allowed VMD controller at 0000:64:00.5
0000:97:00.5 (8086 28c0): Skipping not allowed VMD controller at 0000:97:00.5
0000:e2:00.5 (8086 28c0): Skipping not allowed VMD controller at 0000:e2:00.5
not binding 10002:83:00.0 to any driver ( ):
not binding 10000:05:00.0 to any driver ( ):
not binding 10003:81:00.0 to any driver ( ):
not binding 10003:87:00.0 to any driver ( ):
not binding 10002:81:00.0 to any driver ( ):
not binding 10001:03:00.0 to any driver ( ):
not binding 10000:07:00.0 to any driver ( ):
not binding 0000:80:01.3 to any driver ( ):
not binding 0000:80:01.2 to any driver ( ):
not binding 10001:05:00.0 to any driver ( ):
0000:80:01.3 (8086 0b00): no driver -> no driver
not binding 0000:80:01.1 to any driver ( ):
0000:80:01.2 (8086 0b00): no driver -> no driver
not binding 0000:80:01.0 to any driver ( ):
0000:80:01.1 (8086 0b00): no driver -> no driver
not binding 0000:80:01.7 to any driver ( ):
not binding 0000:80:01.6 to any driver ( ):
0000:80:01.0 (8086 0b00): no driver -> no driver
not binding 0000:80:01.5 to any driver ( ):
0000:80:01.7 (8086 0b00): no driver -> no driver
not binding 0000:80:01.4 to any driver ( ):
0000:80:01.6 (8086 0b00): no driver -> no driver
not binding 10003:85:00.0 to any driver ( ):
0000:80:01.5 (8086 0b00): no driver -> no driver
0000:80:01.4 (8086 0b00): no driver -> no driver
not binding 10003:83:00.0 to any driver ( ):
not binding 10001:07:00.0 to any driver ( ):
not binding 10002:87:00.0 to any driver ( ):
not binding 10001:01:00.0 to any driver ( ):
not binding 10000:01:00.0 to any driver ( ):
not binding 10002:85:00.0 to any driver ( ):
not binding 10000:03:00.0 to any driver ( ):
not binding 0000:00:01.3 to any driver ( ):
not binding 0000:00:01.2 to any driver ( ):
not binding 0000:00:01.1 to any driver ( ):
0000:00:01.3 (8086 0b00): no driver -> no driver
not binding 0000:00:01.0 to any driver ( ):
0000:00:01.2 (8086 0b00): no driver -> no driver
not binding 0000:00:01.7 to any driver ( ):
0000:00:01.1 (8086 0b00): no driver -> no driver
not binding 0000:00:01.6 to any driver ( ):
0000:00:01.0 (8086 0b00): no driver -> no driver
not binding 0000:00:01.5 to any driver ( ):
0000:00:01.7 (8086 0b00): no driver -> no driver
not binding 0000:00:01.4 to any driver ( ):
0000:00:01.6 (8086 0b00): no driver -> no driver
0000:00:01.5 (8086 0b00): no driver -> no driver
0000:00:01.4 (8086 0b00): no driver -> no driver
10002:83:00.0 (144d a824): nvme -> no driver
10002:81:00.0 (144d a824): nvme -> no driver
10002:85:00.0 (144d a824): nvme -> no driver
10001:05:00.0 (144d a824): nvme -> no driver
10000:05:00.0 (144d a824): nvme -> no driver
10003:87:00.0 (144d a824): nvme -> no driver
10003:85:00.0 (144d a824): nvme -> no driver
10000:07:00.0 (144d a824): nvme -> no driver
10000:01:00.0 (144d a824): nvme -> no driver
10001:03:00.0 (144d a824): nvme -> no driver
10002:87:00.0 (144d a824): nvme -> no driver
10003:81:00.0 (144d a824): nvme -> no driver
10000:03:00.0 (144d a824): nvme -> no driver
10001:01:00.0 (144d a824): nvme -> no driver
10001:07:00.0 (144d a824): nvme -> no driver
10003:83:00.0 (144d a824): nvme -> no driver

real    0m16.110s
user    0m1.525s
sys     0m1.878s

daos-0003:~ # readlink -f /sys/bus/pci/devices/0000:e2:00.5/driver; readlink -f /sys/bus/pci/devices/10003:83:00.0/driver
/sys/bus/pci/drivers/vmd
/sys/devices/pci0000:4a/0000:4a:00.5/pci10003:80/10003:80:03.0/10003:83:00.0/driver

daos-0003:~ # time PCI_ALLOWED='0000:4a:00.5 0000:64:00.5 0000:97:00.5 0000:e2:00.5' /usr/share/daos/control/../../spdk/scripts/setup_new.sh
10000:01:00.0 (144d a824): Skipping denied controller at 10000:01:00.0
10000:03:00.0 (144d a824): Skipping denied controller at 10000:03:00.0
10000:05:00.0 (144d a824): Skipping denied controller at 10000:05:00.0
10000:07:00.0 (144d a824): Skipping denied controller at 10000:07:00.0
10001:01:00.0 (144d a824): Skipping denied controller at 10001:01:00.0
10001:03:00.0 (144d a824): Skipping denied controller at 10001:03:00.0
10001:05:00.0 (144d a824): Skipping denied controller at 10001:05:00.0
10001:07:00.0 (144d a824): Skipping denied controller at 10001:07:00.0
10002:81:00.0 (144d a824): Skipping denied controller at 10002:81:00.0
10002:83:00.0 (144d a824): Skipping denied controller at 10002:83:00.0
10002:85:00.0 (144d a824): Skipping denied controller at 10002:85:00.0
10002:87:00.0 (144d a824): Skipping denied controller at 10002:87:00.0
10003:81:00.0 (144d a824): Skipping denied controller at 10003:81:00.0
10003:83:00.0 (144d a824): Skipping denied controller at 10003:83:00.0
10003:85:00.0 (144d a824): Skipping denied controller at 10003:85:00.0
10003:87:00.0 (144d a824): Skipping denied controller at 10003:87:00.0
0000:00:01.0 (8086 0b00): Skipping denied controller at 0000:00:01.0
0000:00:01.1 (8086 0b00): Skipping denied controller at 0000:00:01.1
0000:00:01.2 (8086 0b00): Skipping denied controller at 0000:00:01.2
0000:00:01.3 (8086 0b00): Skipping denied controller at 0000:00:01.3
0000:00:01.4 (8086 0b00): Skipping denied controller at 0000:00:01.4
0000:00:01.5 (8086 0b00): Skipping denied controller at 0000:00:01.5
0000:00:01.6 (8086 0b00): Skipping denied controller at 0000:00:01.6
0000:00:01.7 (8086 0b00): Skipping denied controller at 0000:00:01.7
0000:80:01.0 (8086 0b00): Skipping denied controller at 0000:80:01.0
0000:80:01.1 (8086 0b00): Skipping denied controller at 0000:80:01.1
0000:80:01.2 (8086 0b00): Skipping denied controller at 0000:80:01.2
0000:80:01.3 (8086 0b00): Skipping denied controller at 0000:80:01.3
0000:80:01.4 (8086 0b00): Skipping denied controller at 0000:80:01.4
0000:80:01.5 (8086 0b00): Skipping denied controller at 0000:80:01.5
0000:80:01.6 (8086 0b00): Skipping denied controller at 0000:80:01.6
0000:80:01.7 (8086 0b00): Skipping denied controller at 0000:80:01.7
0000:e2:00.5 (8086 28c0): vmd -> vfio-pci
0000:64:00.5 (8086 28c0): vmd -> vfio-pci
0000:97:00.5 (8086 28c0): vmd -> vfio-pci
0000:4a:00.5 (8086 28c0): vmd -> vfio-pci

real    0m1.313s
user    0m0.798s
sys     0m0.621s
daos-0003:~ # readlink -f /sys/bus/pci/devices/0000:e2:00.5/driver; readlink -f /sys/bus/pci/devices/10003:83:00.0/driver
/sys/bus/pci/drivers/vfio-pci
daos-0003:~ #

**Comment by jimharris** [comment]
Thanks @ravalsam!  So glad to hear that you got this working!  I posted a few more comments on the Gerrit patch.
