### ISSUE TITLE
How to run FIO test with shadow doorbell?

### ISSUE THREAD

**Issue by edchengg** [spdk/spdk#243]
Hi,
What should I do to run FIO test with shadow doorbell?

Thanks in advance.

**Comment by dverkamp-intel** [comment]
The SPDK NVMe driver will automatically use the shadow doorbell feature if it is available; if you use the SPDK NVMe fio plugin (see examples/nvme/fio_plugin/README.md) with a virtualized controller that supports the feature, it will take advantage of it.

Patches have been posted to add this feature to the QEMU NVMe device model, but I don't believe they are merged.  You can find the original mailing list thread here: http://lists.nongnu.org/archive/html/qemu-devel/2015-11/msg04127.html

**Comment by jimharris** [comment]
Closing this issue based on Daniel's response.
