### ISSUE TITLE
lib/nvmf/tcp: code does not look at the return code from accel API, could miss an error

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2430]
In tcp.c when we call spdk_accel_submit_crc32cv() we aren't looking at the return code.  Under really heavy IO testing we're able to run out of accel_tasks and the call return -ENOMEM but tcp.c ignores it so things don't work. We should eb able to repro this by making MAX_TASKS_PER_CHANNEL much smaller.

Optimally we'd not only have a fix in tcp.c (and other places in SPDK where we call accel_functions) but also a CI test that uses a yet to be coded start-time RPC to adjust the number of tasks so we can test these applications' behavior under low memory conditions.

**Comment by changpe1** [comment]
There is another similar issue https://github.com/spdk/spdk/issues/2284, which is also caused by no enough acceleration task.

**Comment by changpe1** [comment]
[Bug Scrub] @MengjinWu can take a look to add some protection in call stack.

**Comment by Comphix** [comment]
@MengjinWu , any update on this issue?

**Comment by MengjinWu** [comment]
I am watching on it.

**Comment by dong-liuliu** [comment]
@MengjinWu ，any update on this issue?

**Comment by ksprzacz** [comment]
It has been already fixed [https://review.spdk.io/gerrit/c/spdk/spdk/+/12841].

Added an error handling if spdk_accel_submit_crc32cv() returns value != 0 (e.g. if accel_tasks are used up it returns -ENOMEM). If so, there is another chance to calculate it directly. In other places, where this function is called, error handling is correct (accel_perf, bdev/nvme)
