### ISSUE TITLE
ADQ: FIO performance loss much when configure+debug and enable-placement-id 1

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2431]
# Bug report
When rpc_py sock_impl_set_options --enable-placement-id 1,
I found "configure with enable debug" will affect the FIO performance of ADQ, although this is reasonable.
But it will drop about 50% compared with non ADQ, this is not normal. 
When rpc_py sock_impl_set_options --enable-placement-id 2,
This situation still exists, but the gap is not too obvious.
Here are some performance comparison data of FIO as below.

## Current Behavior
Take rw= randread as an example.
rpc_py sock_impl_set_options --enable-placement-id 1
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hailia2x/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hailia2x/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

fio | configure | configure+debug
-- | -- | --
adq | bw=1063MiB/s,IOPS=272k | bw=281MiB/s,IOPS=71.9k
no adq | bw=860MiB/s,IOPS=220k | bw=433MiB/s,IOPS=111k
perf delta | +23% | **-54%!!**

</body>

</html>

rpc_py sock_impl_set_options --enable-placement-id 2
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hailia2x/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hailia2x/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

fio | configure | configure+debug
-- | -- | --
adq | bw=720MiB/s,IOPS=184k | bw=432MiB/s,IOPS=111k
no adq | bw=600MiB/s,IOPS=154k | bw=489MiB/s,IOPS=125k
perf delta | +20% | -13%

</body>

</html>
The following is more detailed data.

iodepth=32,bs=4k,

./configure --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --without-isal --enable-asan
randrw
bw=727MiB/s,IOPS=186k (adq)
bw=690MiB/s,IOPS=177k (no adq)

randread
bw=1063MiB/s,IOPS=272k (adq)
bw=860MiB/s,IOPS=220k (no adq)

./configure --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --without-isal --enable-asan --enable-debug
randrw
bw=365MiB/s,IOPS=93.5k (adq)
bw=425MiB/s,IOPS=109k (no adq)

randread
bw=281MiB/s,IOPS=71.9k (adq)
bw=433MiB/s,IOPS=111k (no adq)

rpc_py sock_impl_set_options --enable-placement-id 2
./configure --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --without-isal --enable-asan
randrw
bw=506MiB/s,IOPS=130k (adq)
bw=665MiB/s,IOPS=170k (no adq)

randread
bw=720MiB/s,IOPS=184k (adq)
bw=600MiB/s,IOPS=154k (no adq)

./configure --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --without-isal --enable-asan --enable-debug
randrw
bw=283MiB/s,IOPS=72.4k (adq)
bw=429MiB/s,IOPS=110k (no adq)

randread
bw=432MiB/s,IOPS=111k (adq)
bw=489MiB/s,IOPS=125k (no adq)

## Steps to Reproduce

1../configure --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --without-isal --enable-asan
or ./configure --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --without-isal --enable-asan --enable-debug
2. ./test/nvmf/target/fio_adq_2cases.sh --transport=tcp --iso
fio_adq_2cases.sh is attached in the end.

## Context (Environment including OS version, SPDK version, etc.)
The latest SPDK version
Linux kernel 5.5.1, Fedora 29
ice driver 1.6.8
[fio_adq_2cases.sh.txt](https://github.com/spdk/spdk/files/8258809/fio_adq_2cases.sh.txt)

**Comment by changpe1** [comment]
[Bug Scrub] @wanghailiangx can you use perf top tool to show what's the difference between the two tests, it can give more information.

**Comment by wanghailiangx** [comment]
@changpe1  Unfortunately, this issue has not reappeared recently on local. I'll wait a few more days and turn it off if I can't see it again.

**Comment by tomzawadzki** [comment]
@wanghailiangx Can this issue be closed ?

**Comment by wanghailiangx** [comment]
@tomzawadzki OK.
