### ISSUE TITLE
idxd: copy_crc32 with multi-vector hangs

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2432]
On master, use the following:

[peluse@fedora examples]$ sudo ./accel_perf -w copy_crc32c -C 2 -c j
SPDK Configuration:
Core mask:      0x1

Accel Perf Configuration:
Workload Type:  copy_crc32c
CRC-32C seed:   0
vector count    2
Vector size:    4096 bytes
Transfer size:  8192 bytes
Queue depth:    32
Allocate depth: 32
# threads/core: 1
Run time:       5 seconds
Verify:         No

where j is the json file:

{
   "subsystems":[
      {
         "subsystem":"accel",
         "config":[
            {
               "method":"idxd_scan_accel_engine"
            }
         ]
      }
   ]
}

I did not root cause however did determine on initial review that the for loop using the function spdk_ioviter_first()  in spdk_idxd_submit_copy_crc32c() never enters.

**Comment by peluse** [comment]
@benlwalker since you'll be touching this code soon will toss your way.  LMK if you need any help from me....

**Comment by benlwalker** [comment]
This is working for me on the latest. Closing issue.
