### ISSUE TITLE
segmentation fault when attaching to nvme device with enabled probes

### ISSUE THREAD

**Issue by ogerlitz** [spdk/spdk#2440]
# Bug report

I stepped on some segmentation fault that takes place when enabling uprobes and attaching nvme bdev - it exists in 22.01 and maybe in 21.10 as well. It has to do with the SPDK_DTRACE_PROBE3(bdev_nvme_create_qpair [..]) probe. The qp argument in spdk_nvme_qpair_get_id(ctrlr_ch->qpair) is null.

This was introduced by commit 30ea7ecc6 "bdev/nvme: implement additional dtrace probes" and later as part of commit d7f0a1820e
"bdev/nvme: Inline bdev_nvme_destroy_qpair()" the code was changed.

So we are crashing if probes are enabled and someone attached block device.

## Steps to Reproduce

1. build spdk with probes enabled --with-usdt on env where uprobes are supported (kernel built with CONFIG_UPROBES=y -- e.g Fedora Core 33)

2. set up target with nvme bdev 

3. connect to the target --> seg fault 

## more details on the fault

0x00000000004f3952 in spdk_nvme_qpair_get_id (qpair=0x0) at nvme_qpair.c:1151
1151            return qpair->id;
(gdb) bt
#0  0x00000000004f3952 in spdk_nvme_qpair_get_id (qpair=0x0) at
nvme_qpair.c:1151
#1  0x000000000040e2d5 in bdev_nvme_create_qpair (ctrlr_ch=0xb939a0)
at bdev_nvme.c:1232
#2  0x000000000040ff17 in bdev_nvme_create_ctrlr_channel_cb
(io_device=0xb95610, ctx_buf=0xb939a0) at bdev_nvme.c:2070
#3  0x0000000000545952 in spdk_get_io_channel (io_device=0xb95610) at
thread.c:2172
#4  0x000000000040cd6b in _bdev_nvme_add_io_path (nbdev_ch=0xb938c0,
nvme_ns=0xb95d80) at bdev_nvme.c:587
#5  0x000000000040d06d in bdev_nvme_create_bdev_channel_cb
(io_device=0xb93010, ctx_buf=0xb938c0) at bdev_nvme.c:646
#6  0x0000000000545952 in spdk_get_io_channel (io_device=0xb93010) at
thread.c:2172
#7  0x0000000000410360 in bdev_nvme_get_io_channel (ctx=0xb93010) at
bdev_nvme.c:2183
#8  0x000000000052662d in bdev_channel_create (io_device=0xb93011,
ctx_buf=0xb93790) at bdev.c:3097

db) f 1
#1  0x000000000040e2d5 in bdev_nvme_create_qpair (ctrlr_ch=0xb939a0)
at bdev_nvme.c:1232
1232            SPDK_DTRACE_PROBE3(bdev_nvme_create_qpair,
nvme_ctrlr->nbdev_ctrlr->name,

(gdb) list
1227            qpair =
spdk_nvme_ctrlr_alloc_io_qpair(nvme_ctrlr->ctrlr, &opts,
sizeof(opts));
1228            if (qpair == NULL) {
1229                    return -1;
1230            }
1231
1232            SPDK_DTRACE_PROBE3(bdev_nvme_create_qpair,
nvme_ctrlr->nbdev_ctrlr->name,
1233
spdk_nvme_qpair_get_id(ctrlr_ch->qpair),
spdk_thread_get_id(nvme_ctrlr->thread));
1234
1235            assert(ctrlr_ch->group != NULL);
1236

(gdb) p ctrlr_ch->qpair
$1 = (struct spdk_nvme_qpair *) 0x0

**Comment by shuhei-matsumoto** [comment]
Hi @ogerlitz Thank you for finding and reporting this issue. We fixed this issue by the commit d7f0a18 for the master branch but we missed the v22.01.x branch. I extracted only the fix and applied it to the v22.01.x branch. https://review.spdk.io/gerrit/c/spdk/spdk/+/12086 Will you review the patch when you can?

**Comment by changpe1** [comment]
[Bug Scrub] @tomzawadzki can you take a look how to fix this issue? use cherry pick or a separate patch, thanks.

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12086 has been merged to v22.01.x branch. @ogerlitz Can you confirm that is sufficient to close this issue ?
