### ISSUE TITLE
[SPDK_VHOST_SCSI_CTRLR_MAX_DEVS]Error: SCSI target number is too big

### ISSUE THREAD

**Issue by interaustin** [spdk/spdk#2441]
# Bug report

SPDK currently supports up to 8 SCSI targets mounted on each vhost-scsi controller(slot 0-7). If I set the `scsi_tgt_num` parameter to 8, the error log is confusing.

## Expected Behavior

*ERROR*: SCSI target number is too big (got 8, max `SPDK_VHOST_SCSI_CTRLR_MAX_DEVS`)

## Current Behavior

*ERROR*: vhost.01: SCSI target number is too big (got 8, max 8)

## Possible Solution

I set the parameter to 8 and the error statement prompts me that the max is 8, this confuses me a bit. Is it better for the parameter of max to be 7?  
```
if (scsi_tgt_num >= SPDK_VHOST_SCSI_CTRLR_MAX_DEVS) {
	SPDK_ERRLOG("%s: SCSI target number is too big (got %d, max %d)\n",
				  vdev->name, scsi_tgt_num, SPDK_VHOST_SCSI_CTRLR_MAX_DEVS);
```
set the `max` to `SPDK_VHOST_SCSI_CTRLR_MAX_DEVS-1`

**Comment by Comphix** [comment]
yes, looks like it is somewhat confusing here.

**Comment by Comphix** [comment]
Raised the patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/12087

**Comment by tomzawadzki** [comment]
Patch fixing the issue is now merged https://review.spdk.io/gerrit/c/spdk/spdk/+/12087.
