### ISSUE TITLE
[test/nvme/nvme_rpc_timeouts.sh] This case not run in CI, seems not added in nvme.sh

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2443]
# Bug report

test/nvme/nvme_rpc_timeouts.sh has not been scheduled by CI
Patch info: https://review.spdk.io/gerrit/c/spdk/spdk/+/8352

## Expected Behavior

test/nvme/nvme_rpc_timeouts.sh should be auto run

## Current Behavior

test/nvme/nvme_rpc_timeouts.sh not run

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

SPDK version: `c81c10c529de8dc230a9a27721ed700359734a77`

**Comment by mikeBashStuff** [comment]
The fa44df3627463eed328494b1ff525905f4438f93 did not add this test to autotest suite (nor the `test/nvme/nvme.sh` one), that's why it's not being picked up on the CI.

**Comment by junwenx** [comment]
@mikeBashStuff Yes, maybe need to add it.

**Comment by tomzawadzki** [comment]
[Bug scrub] Jarek will take a look at this, to be assigned.

**Comment by tomzawadzki** [comment]
[Bug scrub] @jchachux any update on the missing test case ?

**Comment by jchachux** [comment]
@tomzawadzki patch is ready for review https://review.spdk.io/gerrit/c/spdk/spdk/+/12239
