### ISSUE TITLE
Arm build fail

### ISSUE THREAD

**Issue by XiangXiangHotSpot** [spdk/spdk#2444]
# Bug report

make fails with:

make: Warning: File '/home/kylin/Desktop/spdk/mk/spdk.subdirs.mk' has modification time 2427186 s in the future
make[1]: Warning: File '/home/kylin/Desktop/spdk/lib/env_dpdk/env.mk' has modification time 2427186 s in the future
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Warning: File '/home/kylin/Desktop/spdk/lib/env_dpdk/env.mk' has modification time 2427138 s in the future
The Meson build system
Version: 0.62.0
Source dir: /home/kylin/Desktop/spdk/dpdk
Build dir: /home/kylin/Desktop/spdk/dpdk/build-tmp
Build type: native build
Program cat found: YES (/usr/bin/cat)
Project name: DPDK
Project version: 22.07.0-rc0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10kylin2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: aarch64
Host machine cpu: aarch64
Program pkg-config found: YES (/usr/bin/pkg-config)
Program check-symbols.sh found: YES (/home/kylin/Desktop/spdk/dpdk/buildtools/check-symbols.sh)
Program options-ibverbs-static.sh found: YES (/home/kylin/Desktop/spdk/dpdk/buildtools/options-ibverbs-static.sh)
Program objdump found: YES (/usr/bin/objdump)
Program python3 found: YES (/usr/bin/python3)
Program cat found: YES (/usr/bin/cat)
config/meson.build:83: WARNING: The "machine" option is deprecated. Please use "cpu_instruction_set" instead.
Checking for size of "void *" : 8
Checking for size of "void *" : 8
Library m found: YES
Library numa found: YES
Has header "numaif.h" : YES 
Library libfdt found: YES
Has header "fdt.h" : YES 
Library libexecinfo found: YES
Has header "execinfo.h" : YES 
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency libarchive found: YES 3.4.0
Run-time dependency libbsd found: YES 0.10.0
Run-time dependency jansson found: YES 2.12
Run-time dependency libpcap found: YES 1.9.1
Has header "pcap.h" with dependency libpcap: YES 
Compiler for C supports arguments -Wcast-qual: YES 
Compiler for C supports arguments -Wdeprecated: YES 
Compiler for C supports arguments -Wformat: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Wmissing-declarations: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -Wno-address-of-packed-member: YES 
Compiler for C supports arguments -Wno-packed-not-aligned: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Program /home/kylin/Desktop/spdk/dpdk/config/arm/armv8_machine.py found: YES (/home/kylin/Desktop/spdk/dpdk/config/arm/armv8_machine.py)

**config/arm/meson.build:509:8: ERROR: Problem encountered: Unsupported Arm implementer: 0x70. Please add support for it or use the generic (-Dplatform=generic) build.**

A full log can be found at /home/kylin/Desktop/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
make[1]: *** [Makefile:195: /home/kylin/Desktop/spdk/dpdk/build-tmp] Error 1
make: *** [/home/kylin/Desktop/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2

## Steps to Reproduce

$ git clone https://github.com/spdk/spdk
$ cd spdk
$ git submodule update --init
$ ./scripts/pkgdep.sh
$ ./configure
$ make

## Context (Environment including OS version, SPDK version, etc.)

Linux kernel version ：5.4.18-23-generic
Project name ： DPDK
Project version ：21.05
SPDK version ：latest 
Host machine cpu: aarch64
Host machine cpu family: aarch64
cpu vendor ID ： 0x70
cpu model name ： Phytium，FT-2000/4

  thanks in advance.

**Comment by jimharris** [comment]
> can you share build output of:
> 
> ```
> ./configure --target-arch=generic
> make
> ```

Never mind, I don't think this will work.

Please try adding this line to dpdkbuild/Makefile:

```
DPDK_OPTS = -Denable_docs=false
DPDK_OPTS += -Dtests=false
DPDK_OPTS += -Dplatform=generic <=== add this line
```

You may also want to consider adding this ARM implementer to upstream DPDK.

**Comment by XiangXiangHotSpot** [comment]
l tried 
```
./configure --target-arch=generic
make
``` 
still failed, but different report:
```
New rpath must not be longer than the old one.
 Old: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 New: /home/kylin/Desktop/spdk/dpdk/build/lib/dpdk/pmds-22.2
make[1]: *** [Makefile:178: all] Error 1
make: *** [/home/kylin/Desktop/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
``` 
[failed report 1.txt](https://github.com/spdk/spdk/files/8394323/failed.report.1.txt)

**Comment by XiangXiangHotSpot** [comment]
And l tried
```
DPDK_OPTS += -Dplatform=generic <=== add this line
./configure --target-arch=generic
make
```
similar failed report：
```
Found ninja-1.10.2.git.kitware.jobserver-1 at /usr/local/bin/ninja
ninja: Entering directory `/home/kylin/Desktop/spdk/dpdk/build-tmp'
[489/489] Linking target app/dpdk-testpmd
New rpath must not be longer than the old one.
 Old: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 New: /home/kylin/Desktop/spdk/dpdk/build/lib/dpdk/pmds-22.2
make[1]: *** [Makefile:178: all] Error 1
make: *** [/home/kylin/Desktop/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
```
[failed report 2.txt](https://github.com/spdk/spdk/files/8394346/failed.report.2.txt)

**Comment by tomzawadzki** [comment]
@XiangXiangHotSpot It does not look like you are using latest SPDK - either SPDK 22.01 or master branch. Can you please try out one of those ?
Have you been able to build DPDK project by itself ?

**Comment by jimharris** [comment]
I have a new M1-based MacBook where I hit this same problem when building SPDK in a VM.  So I'm going to take ownership on this issue and propose a solution.

**Comment by jimharris** [comment]
Patches have been merged which now allow you to specify DPDKBUILD_FLAGS to specify a platform type to work around this problem:

```
DPDKBUILD_FLAGS="-Dplatform=generic" make -j32
```
