### ISSUE TITLE
[vfio-user] Subsequent listener add fails. Files not removed after listener removal.

### ISSUE THREAD

**Issue by Mionsz** [spdk/spdk#2449]
# Bug report
Vfiouser listener creation for subsystem creates files (socket, bar etc.) which are not deleted after listener removal or subsystem deletion. This produces obvious errors when trying to recreate the same listener for second time as directory is not empty.

## Expected Behavior
Directory `/tmp/vfiotest/1` content should be cleaned-up, so listing content of transport address directory should find no files
```bash
ls -la /tmp/vfiotest/1
```

Listener creation for vfiouser creates socket and bar files inside specified address directory `/tmp/vfiotest/1`.
Expected behavior is that after subsystem delete and/or listener remove the content of this directory should be cleanup and files should be deleted.

## Current Behavior
Files created when adding vfiouser listener are still present inside the directory. Subsequent run of add, remove add listener for  the same address fails.

## Possible Solution
Final step for cleanup of vfiouser listener for subsystem should remove no longer used files.

## Steps to Reproduce
```bash
# Make sure dir is empty
ls -la "/tmp/vfiotest/1"
build/bin/nvmf_tgt -r /var/tmp/spdk.sock
scripts/rpc.py nvmf_create_transport -t VFIOUSER
scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode1 -a -s SPDK1
scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode1 -t vfiouser -a "/tmp/vfiotest/1"
# Now 3 files will be inside
ls -la "/tmp/vfiotest/1"
scripts/rpc.py nvmf_subsystem_remove_listener nqn.2019-07.io.spdk:cnode1 -t vfiouser -a "/tmp/vfiotest/1"
# 3 Files are still present inside the directory
ls -la "/tmp/vfiotest/1"
# Bellow will fail due to not empty transport directory
scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode1 -t vfiouser -a "/tmp/vfiotest/1"
```

**Comment by ksztyber** [comment]
@changpe1 could you take a look at this?

**Comment by changpe1** [comment]
> @changpe1 could you take a look at this?

sure, I will take a look.

**Comment by Mionsz** [comment]
> @Mionsz Could you have a try with patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12195? thanks.

@changpe1 I will do so now.

**Comment by Mionsz** [comment]
@changpe1 @ksztyber Yes, this patch fixed the issue, all files are removed now when removing listener or removing namespace and subsequent runs no longer fails.

> @Mionsz Could you have a try with patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12195? thanks.

**Comment by changpe1** [comment]
There are 3 files, and two of them have been removed, the last one will be removed via https://github.com/nutanix/libvfio-user/issues/660.

**Comment by changpe1** [comment]
submodule was updated, so closing this issue now.
