### ISSUE TITLE
[SM4] No space left on device

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2450]
Several builds failed yesterday (6 Apr) due to no space left on one of the VM hosts (SM4). It should already be resolved, this issue is just to have something to link to as false positive on Gerrit.

```
00:05:28.074    LINK nvme_rdma_ut
00:05:28.643    LINK ftl_wptr_ut
00:05:29.213    LINK ftl_io_ut
00:05:29.213  
00:05:29.213  real	3m30.942s
00:05:29.213  user	22m11.865s
00:05:29.213  sys	2m27.464s
00:05:29.213   15:48:16	-- common/autotest_common.sh@965 -- $ xtrace_disable
00:05:29.213   15:48:16	-- common/autotest_common.sh@14 -- $ '[' no '!=' yes ']'
00:05:29.213   15:48:16	-- common/autotest_common.sh@15 -- $ PREV_BASH_OPTS=ehxBET
00:05:29.213   15:48:16	-- common/autotest_common.sh@16 -- $ [[ ehxBET == *\x* ]]
00:05:29.213   15:48:16	-- common/autotest_common.sh@17 -- $ XTRACE_DISABLED=yes
00:05:29.213   15:48:16	-- common/autotest_common.sh@19 -- $ set +x
00:05:29.213  ************************************
00:05:29.213  END TEST unittest_build
00:05:29.213  ************************************
00:05:29.213   15:48:16	-- common/autotest_common.sh@981 -- $ xtrace_enable
00:05:29.213   15:48:16	-- spdk/autobuild.sh@1 -- $ [[ -d /tmp/spdk_1649259841.ZmH3fC ]]
00:05:29.213   15:48:16	-- spdk/autobuild.sh@1 -- $ rm -rf /tmp/spdk_1649259841.ZmH3fC
00:41:10.747  Cancelling nested steps due to timeout
00:41:10.765  Sending interrupt signal to process
00:41:22.298  [Pipeline] sleep
00:41:22.300  Sleeping for 5 sec
00:41:27.302  [Pipeline] }
00:41:27.324  [Pipeline] // timeout
00:41:27.331  [Pipeline] }
00:41:27.350  [Pipeline] // stage
00:41:27.357  [Pipeline] }
00:41:27.375  [Pipeline] // catchError
00:41:27.383  [Pipeline] stage
00:41:27.384  [Pipeline] { (Stop VM)
00:41:27.400  [Pipeline] sh
00:41:27.681  + vagrant halt
00:41:28.251  /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:835:in `close': No space left on device @ fptr_finalize_flush - /var/lib/libvirt/images/.vagrant.d/perm_test_SCQPDWBIDPKYLGGQXKNVVDBHLOQHNDEJ (Errno::ENOSPC)
00:41:28.251  	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:835:in `open'
00:41:28.251  	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:835:in `open'
00:41:28.251  	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:835:in `setup_home_path'
00:41:28.251  	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:135:in `initialize'
00:41:28.251  	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `new'
00:41:28.251  	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `<main>'
00:41:28.262  [Pipeline] }
```

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/74835/archive/unittest-vg-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_74835.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74808.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74840.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74835.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74834.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74839.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74838.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74837.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74848.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74847.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74846.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74845.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74844.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74843.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74842.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_74836.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_74857.html

**Comment by ksztyber** [comment]
A week has passed, I think we can close this one.
