### ISSUE TITLE
[crypto-autotest] COMP_lvs0/lv0 blockdev reset *ERROR*: Unknown I/O type 5

### ISSUE THREAD

**Issue by kgodzwox** [spdk/spdk#2454]
# CI Intermittent Failure

crypto-autotest nightly
TEST: compress_qat

## Link to the failed CI build

https://ci.spdk.io/results/autotest-nightly/builds/560

```
## Execution failed at

0:08:38.620  Suite: bdevio tests on: COMP_lvs0/lv0
00:08:38.620    Test: blockdev write read 4k ...passed
00:08:38.620    Test: blockdev write zeroes read 4k ...passed
00:08:38.620    Test: blockdev write zeroes read 1m ...passed
00:08:38.620    Test: blockdev write zeroes read 3m ...passed
00:08:38.880    Test: blockdev write zeroes read 3.5m ...passed
00:08:38.880    Test: blockdev reset ...[2022-04-11 09:09:19.394184] vbdev_compress.c: 839:_comp_bdev_io_submit: *ERROR*: Unknown I/O type 5
00:08:38.880  FAILED
00:08:38.880      1. bdevio.c:961  - CU_ASSERT_EQUAL(g_completion_success,true)
00:08:38.880    Test: blockdev write read 512 bytes ...passed
00:08:38.880    Test: blockdev write read size > 128k ...passed
00:08:38.880    Test: blockdev write read invalid size ...passed
00:08:38.880    Test: blockdev write read offset + nbytes == size of blockdev ...passed
00:08:38.880    Test: blockdev write read offset + nbytes > size of blockdev ...passed
00:08:38.880    Test: blockdev write read max offset ...passed
00:08:38.880    Test: blockdev write read 8k on overlapped address offset ...passed
00:08:38.880    Test: blockdev writev readv 4k ...passed
00:08:38.880    Test: blockdev writev readv 30 x 4k ...passed
00:08:38.880    Test: blockdev writev readv 512 bytes ...passed
00:08:38.880    Test: blockdev writev readv size > 128k ...passed
00:08:38.880    Test: blockdev writev readv size > 128k in two iovs ...passed
00:08:38.880    Test: blockdev comparev and writev ...passed
00:08:38.880    Test: blockdev nvme passthru rw ...passed
00:08:38.880    Test: blockdev nvme passthru vendor specific ...passed
00:08:38.880    Test: blockdev nvme admin passthru ...passed
00:08:38.880  
00:08:38.880  Run Summary:    Type  Total    Ran Passed Failed Inactive
00:08:38.880                suites      1      1    n/a      0        0
00:08:38.880                 tests     22     22     21      1        0
00:08:38.880               asserts     73     73     72      1      n/a
00:08:38.880  
00:08:38.880  Elapsed time =    0.509 seconds
00:08:38.880  request:
00:08:38.880  {
00:08:38.880    "method": "perform_tests",
00:08:38.880    "req_id": 1
00:08:38.880  }
00:08:38.880  Got JSON-RPC error response
00:08:38.880  response:
00:08:38.880  {
00:08:38.880    "code": -32603,
00:08:38.880    "message": "1 test cases failed"
00:08:38.880  }
00:08:38.880    09:09:19	-- compress/compress.sh@50 -- # trap - ERR
00:08:38.880    09:09:19	-- compress/compress.sh@50 -- # print_backtrace
00:08:38.880    09:09:19	-- common/autotest_common.sh@992 -- # [[ ehxBET =~ e ]]
00:08:38.880    09:09:19	-- common/autotest_common.sh@994 -- # args=('qat')
00:08:38.880    09:09:19	-- common/autotest_common.sh@994 -- # local args
00:08:38.880    09:09:19	-- common/autotest_common.sh@996 -- # xtrace_disable
00:08:38.880    09:09:19	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:08:38.880    09:09:19	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:08:38.881    09:09:19	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:08:38.881    09:09:19	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:08:38.881    09:09:19	-- common/autotest_common.sh@19 -- # set +x
00:11:03.946  ========== Backtrace start: ==========
00:11:03.946  
00:11:03.946  in ./test/compress/compress.sh:50 -> run_bdevio([])
00:11:03.946       ...
00:11:03.946     45  		$rootdir/test/bdev/bdevio/bdevio -w &
00:11:03.946     46  		bdevio_pid=$!
00:11:03.946     47  		trap 'killprocess $bdevio_pid; error_cleanup; exit 1' SIGINT SIGTERM EXIT
00:11:03.946     48  		waitforlisten $bdevio_pid
00:11:03.946     49  		create_vols
00:11:03.946  => 50  		$rootdir/test/bdev/bdevio/tests.py perform_tests
00:11:03.946     51  		destroy_vols
00:11:03.946     52  		trap - SIGINT SIGTERM EXIT
00:11:03.946     53  		killprocess $bdevio_pid
00:11:03.946     54  	}
00:11:03.946     55  	
00:11:03.946       ...
00:11:03.946  in ./test/compress/compress.sh:91 -> main(["qat"])
00:11:03.946       ...
00:11:03.946     86  	run_bdevperf 32 4096 3
00:11:03.946     87  	run_bdevperf 32 4096 3 512
00:11:03.946     88  	run_bdevperf 32 4096 3 4096
00:11:03.946     89  	
00:11:03.946     90  	if [ $RUN_NIGHTLY -eq 1 ]; then
00:11:03.946  => 91  		run_bdevio
00:11:03.946     92  		run_bdevperf 64 16384 30
00:11:03.946     93  	
00:11:03.946     94  		# run perf on nvmf target w/compressed vols
00:11:03.946     95  		export TEST_TRANSPORT=tcp && nvmftestinit
00:11:03.946     96  		nvmfappstart -m 0x7
00:11:03.946       ...
00:11:03.946  
00:11:03.946  ========== Backtrace end ==========
```

**Comment by peluse** [comment]
FYI the compress vbdev never added support for reset (IO type 5).  I assume someone added something recently that is now propagating reset in the compress tests?

	/* TODO support RESET in future patch in the series */
	case SPDK_BDEV_IO_TYPE_RESET:
	case SPDK_BDEV_IO_TYPE_WRITE_ZEROES:
	case SPDK_BDEV_IO_TYPE_UNMAP:
	case SPDK_BDEV_IO_TYPE_FLUSH:
	default:
		SPDK_ERRLOG("Unknown I/O type %d\n", bdev_io->type);

**Comment by kgodzwox** [comment]
@peluse thanks for pointing it out. I've checked the changes and here is what I found.
I checked commit `bdev/compress: Verify mbuf chain if the driver doesn't suppot SGL` with SHA `f530abcab33850cbca9d24da7dfcb5aed4673554 ` and test went further, step with `Test: blockdev reset ...passed` passed but there is a problem later:
`13:00:18  ISA-L library version used: 2.30.0
13:00:18  [2022-04-12 13:00:18.124938] vbdev_compress.c: 359:vbdev_init_compress_drivers: *NOTICE*: created virtual PMD compress_isal
13:00:18  [2022-04-12 13:00:18.466799] vbdev_compress.c: 408:vbdev_init_compress_drivers: *NOTICE*: initialized QAT PMD
13:00:18   13:00:18	-- common/autotest_common.sh@735 -- # xtrace_enable
13:00:18   13:00:18	-- common/autotest_common.sh@736 -- # (( i == 0 ))
13:00:18   13:00:18	-- common/autotest_common.sh@740 -- # return 0
13:00:18   13:00:18	-- compress/compress.sh@61 -- # create_vols
13:00:18   13:00:18	-- compress/compress.sh@28 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/gen_nvme.sh
13:00:18   13:00:18	-- compress/compress.sh@28 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py load_subsystem_config
13:00:21  [2022-04-12 13:00:21.078102] bdev_nvme.c:1150:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x20003c4058a0 is disconnected, free the qpair and reset controller.
13:00:21   13:00:21	-- compress/compress.sh@29 -- # waitforbdev Nvme0n1
13:00:21   13:00:21	-- common/autotest_common.sh@775 -- # local bdev_name=Nvme0n1
13:00:21   13:00:21	-- common/autotest_common.sh@776 -- # local i
13:00:21   13:00:21	-- common/autotest_common.sh@778 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_wait_for_examine
13:00:21   13:00:21	-- common/autotest_common.sh@780 -- # (( i = 1 ))
13:00:21   13:00:21	-- common/autotest_common.sh@780 -- # (( i <= 20 ))
13:00:21   13:00:21	-- common/autotest_common.sh@781 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_get_bdevs
13:00:21   13:00:21	-- common/autotest_common.sh@781 -- # jq -r '.[] .name'
13:00:21   13:00:21	-- common/autotest_common.sh@781 -- # grep -qw Nvme0n1
13:00:21   13:00:21	-- common/autotest_common.sh@782 -- # return 0
13:00:21   13:00:21	-- compress/compress.sh@31 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_lvol_create_lvstore Nvme0n1 lvs0
13:00:25  a3eb71ce-7127-4591-ae31-501289dfd61a
13:00:25   13:00:24	-- compress/compress.sh@32 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_lvol_create -t -l lvs0 lv0 100
13:00:25  96216cfd-2505-45ce-a13e-0d25f06eb9ee
13:00:25   13:00:25	-- compress/compress.sh@33 -- # waitforbdev lvs0/lv0
13:00:25   13:00:25	-- common/autotest_common.sh@775 -- # local bdev_name=lvs0/lv0
13:00:25   13:00:25	-- common/autotest_common.sh@776 -- # local i
13:00:25   13:00:25	-- common/autotest_common.sh@778 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_wait_for_examine
13:00:25   13:00:25	-- common/autotest_common.sh@780 -- # (( i = 1 ))
13:00:25   13:00:25	-- common/autotest_common.sh@780 -- # (( i <= 20 ))
13:00:25   13:00:25	-- common/autotest_common.sh@781 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_get_bdevs
13:00:25   13:00:25	-- common/autotest_common.sh@781 -- # jq -r '.[] .name'
13:00:25   13:00:25	-- common/autotest_common.sh@781 -- # grep -qw lvs0/lv0
13:00:25   13:00:25	-- common/autotest_common.sh@785 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_get_bdevs
13:00:25   13:00:25	-- common/autotest_common.sh@785 -- # jq -r '.[] .aliases'
13:00:25   13:00:25	-- common/autotest_common.sh@785 -- # grep -qw lvs0/lv0
13:00:25   13:00:25	-- common/autotest_common.sh@786 -- # return 0
13:00:25   13:00:25	-- compress/compress.sh@35 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py compress_set_pmd -p 1
13:00:26  compress_set_pmd is deprecated, use bdev_compress_set_pmd instead.
13:00:26   13:00:25	-- compress/compress.sh@36 -- # '[' -z '' ']'
13:00:26   13:00:25	-- compress/compress.sh@37 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_compress_create -b lvs0/lv0 -p /tmp/pmem
13:00:26  [2022-04-12 13:00:26.196854] vbdev_compress.c:1398:_set_pmd: *NOTICE*: PMD being used: compress_qat
13:00:26  [2022-04-12 13:00:26.200351] vbdev_compress.c:1671:vbdev_compress_claim: *NOTICE*: QAT in use: Required alignment set to 9
13:00:26  [2022-04-12 13:00:26.200601] vbdev_compress.c:1716:vbdev_compress_claim: *NOTICE*: registered io_device and virtual bdev for: COMP_lvs0/lv0
13:00:26  COMP_lvs0/lv0
13:00:26   13:00:26	-- compress/compress.sh@41 -- # waitforbdev COMP_lvs0/lv0
13:00:26   13:00:26	-- common/autotest_common.sh@775 -- # local bdev_name=COMP_lvs0/lv0
13:00:26   13:00:26	-- common/autotest_common.sh@776 -- # local i
13:00:26   13:00:26	-- common/autotest_common.sh@778 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_wait_for_examine
13:00:26   13:00:26	-- common/autotest_common.sh@780 -- # (( i = 1 ))
13:00:26   13:00:26	-- common/autotest_common.sh@780 -- # (( i <= 20 ))
13:00:26   13:00:26	-- common/autotest_common.sh@781 -- # /var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py bdev_get_bdevs
13:00:26   13:00:26	-- common/autotest_common.sh@781 -- # jq -r '.[] .name'
13:00:26   13:00:26	-- common/autotest_common.sh@781 -- # grep -qw COMP_lvs0/lv0
13:00:26   13:00:26	-- common/autotest_common.sh@782 -- # return 0
13:00:26   13:00:26	-- compress/compress.sh@62 -- # /var/jenkins/workspace/crypto-autotest/spdk/test/bdev/bdevperf/bdevperf.py perform_tests
13:00:26  Running I/O for 30 seconds...
13:00:26  [2022-04-12 13:00:26.759869] vbdev_compress.c: 610:_compress_operation: *ERROR*: Dst buffer crosses 2MB boundary but driver compress_qat doesn't support SGL output
13:00:26  [2022-04-12 13:00:26.759931] vbdev_compress.c: 771:_comp_reduce_decompress: *ERROR*: with decompress operation code -22 (Invalid argument)
13:00:26  [2022-04-12 13:00:26.759954] vbdev_compress.c: 437:_reduce_rw_blocks_cb: *ERROR*: status -22 on operation from reduce API
13:00:58  [2022-04-12 13:00:56.814680] bdev_nvme.c:1150:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x20003c4056a0 is disconnected, free the qpair and reset controller.
13:00:58  task offset: 0 on job bdev=COMP_lvs0/lv0 fails
13:00:58  Job run time less than one microsecond, no performance data will be shown
13:00:58  
 Job: COMP_lvs0/lv0 (Core Mask 0x2)
13:00:58  	 Verification LBA range: start 0x0 length 0xc40
13:00:58  	 COMP_lvs0/lv0       :        inf IOPS        inf MiB/s
13:00:58  	                     :        inf Fail/s     -nan TO/s
13:00:58  
 Job: COMP_lvs0/lv0 (Core Mask 0x4)
13:00:58  	 Verification LBA range: start 0xc40 length 0xc40
13:00:58  	 COMP_lvs0/lv0       :        inf IOPS        inf MiB/s
13:00:58  	                     :       -nan Fail/s     -nan TO/s
13:00:58  
 =============================================================`
 
 The next commit `bdev/compress: Update error handling in IO submission path` with SHA `ce49d2f91f14d2ae26cfc4e358a3fa38b22289c2` stops tests before, here:
 
 `12:58:33    Test: blockdev reset ...[2022-04-12 12:58:33.110301] vbdev_compress.c: 839:_comp_bdev_io_submit: *ERROR*: Unknown I/O type 5
12:58:33  FAILED` 
as described in current issue.

Both commits are from @AlekseyMarchuk. @AlekseyMarchuk could you take a look, please? :)

**Comment by xjjx** [comment]
body=Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_73087.html

**Comment by AlekseyMarchuk** [comment]
@kgodzwox Sure, I'm on it

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci. log: https://ci.spdk.io/public_build/autotest-per-patch_75170.html

**Comment by peluse** [comment]
@AlekseyMarchuk let me know if you need anything.  Seems like maybe before those patches we weren't getting the reset and now we are? I dunno but clearly the initial report is because we don't handle reset so that's probably a good thing to do regardless.

**Comment by AlekseyMarchuk** [comment]
vbdev_compress reports that it doesn't support IO_TYPE_RESET but bdevio test issues spdk_bdev_reset.
Before my patch RESET request was just completed like it was successfully executed. So I believe that the current behavior is correct. I think that we can update bdevio test to check whether IO_TYPE_RESET supported or not and to expect corresponding result.
bfd7fcb8fedd603ae3a2da4348743ea754ecf1da:
```
	int rc = 0;
	....
	case SPDK_BDEV_IO_TYPE_RESET:
		break;
	case SPDK_BDEV_IO_TYPE_WRITE_ZEROES:
	case SPDK_BDEV_IO_TYPE_UNMAP:
	case SPDK_BDEV_IO_TYPE_FLUSH:
	default:
		SPDK_ERRLOG("Unknown I/O type %d\n", bdev_io->type);
		rc = -EINVAL;
	}

	if (rc) {     // rc is 0 here
		if (rc == -ENOMEM) {
			SPDK_ERRLOG("No memory, start to queue io for compress.\n");
			io_ctx->ch = ch;
			vbdev_compress_queue_io(bdev_io);
			return;
		} else {
			SPDK_ERRLOG("on bdev_io submission!\n");
			io_ctx->status = rc;
		}
	}

	/* Complete this on the orig IO thread. */
	orig_thread = spdk_io_channel_get_thread(ch);
	if (orig_thread != spdk_get_thread()) {
		spdk_thread_send_msg(orig_thread, _complete_other_io, io_ctx);
	} else {
		_complete_other_io(io_ctx);
	}
```

Regarding the first problem where destination buffer crossed huge page boundary - it depends on the memory allocation. That is decompress operation, libreduce manages memory for comp/decomp buffers by itself - it allocates a big contiguous buffer and then splits it into `chunk_size`  parts. So it is possible that some of the chunks crossed huge page boundary. I think that instead we can try to use spdk_mempool here - AFAIK DPDK tries to allocate buffers so that they don't cross huge pages

**Comment by AlekseyMarchuk** [comment]
I agree it's worth supporting reset_io. But since vbdev_compress uses lvol, lvol just completes reset with failed status :) So we need to add support of reset to lvol too

**Comment by peluse** [comment]
good point!

**Comment by AlekseyMarchuk** [comment]
I prepared patches to address these issues https://review.spdk.io/gerrit/c/spdk/spdk/+/12249
@kgodzwox could you please verify them?

**Comment by kgodzwox** [comment]
Yes, sure.
```
17:38:23  Suite: bdevio tests on: COMP_lvs0/lv0
17:38:23    Test: blockdev write read 4k ...passed
17:38:23    Test: blockdev write zeroes read 4k ...passed
17:38:23    Test: blockdev write zeroes read 1m ...passed
17:38:23    Test: blockdev write zeroes read 3m ...passed
17:38:23    Test: blockdev write zeroes read 3.5m ...passed
17:38:23    Test: blockdev reset ...[2022-04-14 17:38:23.862121] vbdev_compress.c: 839:_comp_bdev_io_submit: *ERROR*: Unknown I/O type 5
17:38:23  passed
17:38:23    Test: blockdev write read 512 bytes ...passed
17:38:23    Test: blockdev write read size > 128k ...passed
17:38:23    Test: blockdev write read invalid size ...passed
17:38:23    Test: blockdev write read offset + nbytes == size of blockdev ...passed
17:38:23    Test: blockdev write read offset + nbytes > size of blockdev ...passed
17:38:23    Test: blockdev write read max offset ...passed
17:38:23    Test: blockdev write read 8k on overlapped address offset ...passed
17:38:23    Test: blockdev writev readv 4k ...passed
17:38:23    Test: blockdev writev readv 30 x 4k ...passed
17:38:23    Test: blockdev writev readv 512 bytes ...passed
17:38:23    Test: blockdev writev readv size > 128k ...passed
17:38:23    Test: blockdev writev readv size > 128k in two iovs ...passed
17:38:23    Test: blockdev comparev and writev ...passed
17:38:23    Test: blockdev nvme passthru rw ...passed
17:38:23    Test: blockdev nvme passthru vendor specific ...passed
17:38:23    Test: blockdev nvme admin passthru ...passed
```

Now the error is logged but tests pass anyway.
It stopped at:

```
17:38:35   17:38:35	-- compress/compress.sh@62 -- # /var/jenkins/workspace/crypto-autotest/spdk/test/bdev/bdevperf/bdevperf.py perform_tests
17:38:35  Running I/O for 30 seconds...
17:38:35  [2022-04-14 17:38:35.660756] vbdev_compress.c: 613:_compress_operation: *ERROR*: Dst buffer crosses 2MB boundary but driver compress_qat doesn't support SGL output
17:38:35  [2022-04-14 17:38:35.660792] vbdev_compress.c: 774:_comp_reduce_decompress: *ERROR*: with decompress operation code -22 (Invalid argument)
17:38:35  [2022-04-14 17:38:35.660805] vbdev_compress.c: 440:_reduce_rw_blocks_cb: *ERROR*: status -22 on operation from reduce API
17:39:07  task offset: 256 on job bdev=COMP_lvs0/lv0 fails
17:39:07  Job run time less than one microsecond, no performance data will be shown
17:39:07  
 Job: COMP_lvs0/lv0 (Core Mask 0x2)
17:39:07  	 Verification LBA range: start 0x0 length 0xc40
17:39:07  	 COMP_lvs0/lv0       :        inf IOPS        inf MiB/s
17:39:07  	                     :        inf Fail/s     -nan TO/s
17:39:07  
 Job: COMP_lvs0/lv0 (Core Mask 0x4)
17:39:07  	 Verification LBA range: start 0xc40 length 0xc40
17:39:07  	 COMP_lvs0/lv0       :        inf IOPS        inf MiB/s
17:39:07  	                     :       -nan Fail/s     -nan TO/s
17:39:07  
 =============================================================
17:39:07  
 Total                       :        inf IOPS        inf MiB/s
17:39:07  
                             :       -nan Fail/s     -nan TO/s
17:39:07  request:
17:39:07  {
17:39:07    "method": "perform_tests",
17:39:07    "req_id": 1
17:39:07  }
17:39:07  Got JSON-RPC error response
17:39:07  response:
17:39:07  {
17:39:07    "code": -32603,
17:39:07    "message": "bdevperf failed with error Operation not permitted"
17:39:07  }
17:39:07    17:39:05	-- compress/compress.sh@62 -- # trap - ERR
17:39:07    17:39:05	-- compress/compress.sh@62 -- # print_backtrace
17:39:07    17:39:05	-- common/autotest_common.sh@992 -- # [[ ehxBET =~ e ]]
17:39:07    17:39:05	-- common/autotest_common.sh@994 -- # args=('30' '16384' '64' 'qat')
17:39:07    17:39:05	-- common/autotest_common.sh@994 -- # local args
17:39:07    17:39:05	-- common/autotest_common.sh@996 -- # xtrace_disable
17:39:07    17:39:05	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
17:39:07    17:39:05	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
17:39:07    17:39:05	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
17:39:07    17:39:05	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
17:39:07    17:39:05	-- common/autotest_common.sh@19 -- # set +x
17:39:07  ========== Backtrace start: ==========
17:39:07  
17:39:07  in ./test/compress/compress.sh:62 -> run_bdevperf(["64"],["16384"],["30"])
17:39:07       ...
17:39:07     57  		$rootdir/test/bdev/bdevperf/bdevperf -z -q $1 -o $2 -w verify -t $3 -C -m 0x6 &
17:39:07     58  		bdevperf_pid=$!
17:39:07     59  		trap 'killprocess $bdevperf_pid; error_cleanup; exit 1' SIGINT SIGTERM EXIT
17:39:07     60  		waitforlisten $bdevperf_pid
17:39:07     61  		create_vols $4
17:39:07  => 62  		$rootdir/test/bdev/bdevperf/bdevperf.py perform_tests
17:39:07     63  		destroy_vols
17:39:07     64  		trap - SIGINT SIGTERM EXIT
17:39:07     65  		killprocess $bdevperf_pid
17:39:07     66  	}
17:39:07     67  	
17:39:07       ...
17:39:07  in ./test/compress/compress.sh:92 -> main(["qat"])
17:39:07       ...
17:39:07     87  	run_bdevperf 32 4096 3 512
17:39:07     88  	run_bdevperf 32 4096 3 4096
17:39:07     89  	
17:39:07     90  	if [ $RUN_NIGHTLY -eq 1 ]; then
17:39:07     91  		run_bdevio
17:39:07  => 92  		run_bdevperf 64 16384 30
17:39:07     93  	
17:39:07     94  		# run perf on nvmf target w/compressed vols
17:39:07     95  		export TEST_TRANSPORT=tcp && nvmftestinit
17:39:07     96  		nvmfappstart -m 0x7
17:39:07     97  		trap "nvmftestfini; error_cleanup; exit 1" SIGINT SIGTERM EXIT
17:39:07       ...
17:39:07  
17:39:07  ========== Backtrace end ==========
```

**Comment by AlekseyMarchuk** [comment]
Thanks, I thought I solved both problems :)
Will check what is wrong

**Comment by AlekseyMarchuk** [comment]
I found what caused latest failure. When the app issues IO size less than reduce vol chunk_size then user's buffers are copied into reduce vol buffers. Now these buffers are properly aligned and there should be not problem. However when the user issues IO size equal to vol chunk_size and user's buffer is contig, then user's buffer is used directly. And the problem is that bdevperf allocated not aligned buffers. So we need to either update how test applications allocate IO buffers (to many changes might be required) or add a check that buffers are properly aligned to reduce library. In the worst case reduce library can copy user's buffers. I guest that the 2nd option is more preferable since we can't require applications to use buffers which do not cross huge page boundaries

**Comment by AlekseyMarchuk** [comment]
Hi @kgodzwox I pushed one more patch, it should fix the problem https://review.spdk.io/gerrit/c/spdk/spdk/+/12281
it works on my setup, could you verify it?
@peluse may I ask you to look at this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12249? I tried to cover cases when chunk_size is not power of 2, but it seems it is not needed. If we only support chunk_size 16KiB then this patch can be simplified.

**Comment by kgodzwox** [comment]
@AlekseyMarchuk it seems like both problems are fixed with your patch :) this first reset error is still logged (I assume it is expected?) but as I said in the previous comment, the test is passing.

**Comment by AlekseyMarchuk** [comment]
Thanks @kgodzwox ! Yes, the logged error is expected

**Comment by kgodzwox** [comment]
Issue fixed. Closing
