### ISSUE TITLE
[vagrant virtual client] fedora34 vagrant virtual client can't run scripts/setup.sh normally

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2457]
# Bug report

fedora34 vagrant virtual client can't run scripts/setup.sh normally

## Expected Behavior

scripts/setup.sh can run normally on fedora34 virtual client

## Current Behavior

`[root@fedora spdk]# ./scripts/setup.sh`
`No valid drivers found [vfio-pci, uio_pci_generic, igb_uio]. Please enable one of the kernel modules.`

## Steps to Reproduce

1. download SPDK code, `cd spdk/scripts/vagrant`
2. `./create_vbox.sh -s 4096 -n 4 fedora34`
3. `vagrant reload`
4. `vagrant ssh` to load to virtual client
5.  on virtual client `sudo su`, `cd /home/vagrant/spdk_repo/spdk/scripts/vagrant/`, `./update.sh`, `cd /home/vagrant/spdk_repo/spdk`, `./scripts/pkgdep.sh`, `./scripts/setup.sh`
There is error raise:
`No valid drivers found [vfio-pci, uio_pci_generic, igb_uio]. Please enable one of the kernel modules.`

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: `247390e81add28a3009ef34c82d12888e7f34d67`

**Comment by tomzawadzki** [comment]
Bug scrub: @junwenx Can you confirm that lsmod for either of the missing drivers does not produce any output ?

**Comment by junwenx** [comment]
@jchachux @tomzawadzki  Hi, thank you for the support, I'll try again about fedora34, and paste the lsmod output to here.

**Comment by junwenx** [comment]
@jchachux @tomzawadzki  Hi, it seems the issue is I execute "su -" on virtual client, when I use "sudo su", it is normal and success, so may be it is not a issue.

**Comment by tomzawadzki** [comment]
@junwenx Thank you for investigating this further and finding the difference.
If curious, you can check what kind of environment variable is missing (due to `su -` ) that the `configure_linux_pci()` in `scripts/setup.sh` doesn't detect any of the drivers.

Otherwise, if you think this issue is resolved - please feel free to close this issue.

**Comment by junwenx** [comment]
@tomzawadzki  Thanks a lot. Yes, I think can close, sorry for my mistake
