### ISSUE TITLE
compileing failed with "CUnit/Basic.h": No such file or directory

### ISSUE THREAD

**Issue by ddwolf** [spdk/spdk#2458]
# Bug report
## Steps to Reproduce

I followed the instructions here: https://spdk.io/doc/getting_started.html
after running ./configure, when execute make, it paniked like this:
bdevio.c:46:10: fatal error: CUnit/Basic.h: No such file or directory
 #include "CUnit/Basic.h"

**Comment by ksztyber** [comment]
Looks like you don't have CUnit devel packages installed. Did you run `scripts/pkgdep.sh`?

**Comment by ddwolf** [comment]
thanks for your reply, it is true that I dont have these libraries, I will find them:)

No package CUnit-devel available.
No package libiscsi-devel available.
No package json-c-devel available.
No package libcmocka-devel available.
No package python3-pip available
