### ISSUE TITLE
Possible missing linked-list remove in unregister_trids()

### ISSUE THREAD

**Issue by ranjitnoronha** [spdk/spdk#246]
While reviewing the code, I came across the following code in examples/nvme/perf/perf.c:
static void
unregister_trids(void)
{
	struct trid_entry *trid_entry, *tmp;

	TAILQ_FOREACH_SAFE(trid_entry, &g_trid_list, tailq, tmp) {
		free(trid_entry);
	}
}

Is there a missing TAILQ_REMOVE()?

ie. should the code be:

static void
unregister_trids(void)
{
	struct trid_entry *trid_entry, *tmp;

	TAILQ_FOREACH_SAFE(trid_entry, &g_trid_list, tailq, tmp) {
                TAILQ_REMOVE(trid_entry, &g_trid_list, tailq);
		free(trid_entry);
	}
}

**Comment by jimharris** [comment]
Hi Ranjit,

The TAILQ_REMOVE would be OK, but it is not technically needed since the g_trid_list is not used again after unregister_trids() is called.

But if you would like to submit a patch through GerritHub to add the TAILQ_REMOVE I think it would be a nice cleanup.

Thanks,

-Jim

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/436994/ adds the TAILQ_REMOVE.

**Comment by jimharris** [comment]
Patch merged.
