### ISSUE TITLE
The cpu usage in spdk_top may not right.

### ISSUE THREAD

**Issue by YafeiWangAlice** [spdk/spdk#2461]
# Bug report
The cpu usage in spdk_top may not right.

## Expected Behavior

In THREADS tab, a
As the code in spdk_top.c, I think the cpu usage can be calculated by busy time and idle time in THREADS tab like:

cpu usage = busy /(busy + idle)

## Steps to Reproduce

1. $SPDKDIR/test/event/scheduler/scheduler -m 0xF -p 2 --wait-for-rpc &
2. scripts/rpc.py framework_set_scheduler dynamic
3. scripts/rpc.py framework_start_init
4. build/bin/spdk_top
5. scripts/rpc.py --plugin scheduler_plugin scheduler_thread_create -n busy0 -a 50
6. scripts/rpc.py --plugin scheduler_plugin scheduler_thread_create -n busy1 -a 40
7. scripts/rpc.py --plugin scheduler_plugin scheduler_thread_create -n busy2 -a 50

## Current Behavior
The cpu usage displayed in spdk_top is not related with the busy time and idle time of THREADS tab.
"busy0" runs on core1.
"busy1" runs on core2.
"busy2" runs on core0.
Sorry I can not upload image. I will describe thread "busy0" as below. "busy1" and "busy2" are very similar with "busy0".

In the first few minutes, idle time (**Idle [us]**) of busy0 is 599908, busy time (**Busy [us]**) of busy0 is 600149, "CPU %" is **0.02**.
After a while ( may be 1 hour or longer), idle time of busy0 is 517870, busy time of busy0 is 550137, "CPU %" is **0.00**.

I think the cpu usage is not right.

## Context (Environment including OS version, SPDK version, etc.)
OS version : Linux version 3.10.0-1160.59.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44)
SPDK version : 22.01

**Comment by ksztyber** [comment]
Yeah, it doesn't seem right. @KKaras169169 could you take a look at this?

**Comment by KKaras169169** [comment]
I found the issue. Here is the patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/12319

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_87195.html
