### ISSUE TITLE
fatal: unsafe repository ('/home/vagrant/spdk_repo/spdk' is owned by someone else)

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2462]
# CI Intermittent Failure

00:08:55.979   02:38:21	-- spdk/autotest.sh@349 -- # git clean -f '*.gcda'
00:08:55.979  fatal: unsafe repository ('/home/vagrant/spdk_repo/spdk' is owned by someone else)
00:08:55.979  To add an exception for this directory, call:
00:08:55.979  
00:08:55.979  	git config --global --add safe.directory /home/vagrant/spdk_repo/spdk
00:08:55.979    02:38:21	-- spdk/autotest.sh@349 -- # trap - ERR
00:08:55.979    02:38:21	-- spdk/autotest.sh@349 -- # print_backtrace
00:08:55.979    02:38:21	-- common/autotest_common.sh@992 -- # [[ ehxBET =~ e ]]
00:08:55.979    02:38:21	-- common/autotest_common.sh@994 -- # args=("${BASH_ARGV[@]}")
00:08:55.979    02:38:21	-- common/autotest_common.sh@994 -- # local args
00:08:55.979    02:38:21	-- common/autotest_common.sh@996 -- # xtrace_disable
00:08:55.979    02:38:21	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:08:55.979    02:38:21	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:08:55.979    02:38:21	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:08:55.979    02:38:21	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:08:55.979    02:38:21	-- common/autotest_common.sh@19 -- # set +x
00:08:55.979  ========== Backtrace start: ==========

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_75208.html

## Execution failed at

00:08:55.979  ========== Backtrace start: ==========
00:08:55.979  
00:08:55.979  in /home/vagrant/spdk_repo/spdk/autotest.sh:349 -> main(["/home/vagrant/autorun-spdk.conf"])
00:08:55.979       ...
00:08:55.979     344 		# generate coverage data and combine with baseline
00:08:55.979     345 		$LCOV -q -c -d $src -t "$(hostname)" -o $out/cov_test.info
00:08:55.979     346 		$LCOV -q -a $out/cov_base.info -a $out/cov_test.info -o $out/cov_total.info
00:08:55.979     347 		$LCOV -q -r $out/cov_total.info '*/dpdk/*' -o $out/cov_total.info
00:08:55.979     348 		$LCOV -q -r $out/cov_total.info '/usr/*' -o $out/cov_total.info
00:08:55.979  => 349 		git clean -f "*.gcda"
00:08:55.979     350 		rm -f cov_base.info cov_test.info OLD_STDOUT OLD_STDERR
00:08:55.979     351 	fi
00:08:55.979       ...
00:08:55.979  
00:08:55.979  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75212.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75213.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75211.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_75224.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_75226.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_75220.html

**Comment by changpe1** [comment]
@karlatec can you take a look? thanks.

**Comment by karlatec** [comment]
We already fixed that yesterday with @xjjx. Let's leave the issue open until the end of the week so that everyone has a chance to retrigger their patches.
