### ISSUE TITLE
Replay SPDK vhost Performance Report [Test Case 3]

### ISSUE THREAD

**Issue by Second222None** [spdk/spdk#2463]
# Bug report

## Expected Behavior

Results close to Table 15 in **SPDK Vhost Performance Report**.

## Current Behavior

- fio configuration file
```
[global]
ioengine=libaio
direct=1
thread=1
norandommap=1
time_based=1
runtime=60s
ramp_time=0s
bs=4k
iodepth=64
numjobs=1
size=1600G

[test-randrw]
rw=randrw
rwmixread=70
filename=/dev/vda
```

- My test result: 89.8K (read IOPS), 498.5us (avg), 38.5K (write IOPS), 494.36us (avg)
- SPDK test result：374466.14 (IOPS) 339.86us (avg)

## Possible Solution

There is an error in **spdk-vhost.log**. I am not sure whether it matters.
```
VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:0 file:43
[2022-04-13 14:12:22.909290] memory.c: 841:vtophys_iommu_map_dma: *NOTICE*: Cannot set up DMA mapping, error 17, ignored
VHOST_CONFIG: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: read message VHOST_USER_SET_VRING_KICK
```

## Steps to Reproduce

1. Start SPDK vhost 
```
./build/bin/vhost -S /var/tmp -m 0x3 > spdk-vhost.log 2>&1 &
```
3. Create bdev device 
```
./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:81:00.0
````
4. Create vhost-blk-controller and attach the bdev device.
```
./scripts/rpc.py vhost_create_blk_controller --cpumask 0x2 vhostblk0 Nvme0n1
```
5. start VM. The related content in xml.
```
<qemu:arg value='-chardev'/>
<qemu:arg value='socket,id=spdk_vhost_blk0,path=/var/tmp/vhostblk0'/>
<qemu:arg value='-device'/>
<qemu:arg value='vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=4'/>
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK version: master
Hardware：aarch64

**Comment by changpe1** [comment]
@Second222None I saw you are using an ARM platform, for a better comparison, you can run the same workload using a Malloc backend first. BTW, what's SSD model you are testing with?

**Comment by Second222None** [comment]
> 
Thanks for your suggestion!
We have a similar result on x86. Even though the Malloc backend is attached, the result is still similar. It seems that the VM IO requests cannot transfer to SPDK vhost efficiently. The following is the Malloc backend test results:
```
test-randrw: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.29
Starting 1 thread
Jobs: 1 (f=1): [m(1)][100.0%][r=319MiB/s,w=138MiB/s][r=81.6k,w=35.3k IOPS][eta 00m:00s]
test-randrw: (groupid=0, jobs=1): err= 0: pid=996: Wed Apr 13 08:12:21 2022
  read: IOPS=81.2k, BW=317MiB/s (333MB/s)(18.6GiB/60001msec)
    slat (usec): min=2, max=447, avg= 5.47, stdev= 3.45
    clat (usec): min=13, max=1409, avg=544.34, stdev=11.26
     lat (usec): min=16, max=1412, avg=550.30, stdev=11.20
    clat percentiles (usec):
     |  1.00th=[  529],  5.00th=[  529], 10.00th=[  529], 20.00th=[  537],
     | 30.00th=[  537], 40.00th=[  545], 50.00th=[  545], 60.00th=[  545],
     | 70.00th=[  545], 80.00th=[  553], 90.00th=[  553], 95.00th=[  562],
     | 99.00th=[  570], 99.50th=[  570], 99.90th=[  652], 99.95th=[  660],
     | 99.99th=[  676]
   bw (  KiB/s): min=320896, max=329856, per=100.00%, avg=325059.36, stdev=1565.59, samples=119
   iops        : min=80224, max=82464, avg=81264.84, stdev=391.39, samples=119
  write: IOPS=34.8k, BW=136MiB/s (143MB/s)(8165MiB/60001msec); 0 zone resets
    slat (usec): min=2, max=824, avg= 6.38, stdev= 3.30
    clat (usec): min=29, max=1401, avg=544.33, stdev=11.08
     lat (usec): min=32, max=1412, avg=550.99, stdev=11.22
    clat percentiles (usec):
     |  1.00th=[  529],  5.00th=[  529], 10.00th=[  537], 20.00th=[  537],
     | 30.00th=[  537], 40.00th=[  545], 50.00th=[  545], 60.00th=[  545],
     | 70.00th=[  545], 80.00th=[  553], 90.00th=[  553], 95.00th=[  562],
     | 99.00th=[  570], 99.50th=[  570], 99.90th=[  652], 99.95th=[  660],
     | 99.99th=[  676]
   bw (  KiB/s): min=136720, max=141968, per=100.00%, avg=139379.97, stdev=1087.98, samples=119
   iops        : min=34180, max=35492, avg=34844.99, stdev=271.98, samples=119
  lat (usec)   : 20=0.01%, 50=0.01%, 100=0.01%, 250=0.01%, 500=0.01%
  lat (usec)   : 750=99.99%, 1000=0.01%
  lat (msec)   : 2=0.01%
  cpu          : usr=25.17%, sys=49.39%, ctx=322, majf=0, minf=1
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=4874644,2090337,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=317MiB/s (333MB/s), 317MiB/s-317MiB/s (333MB/s-333MB/s), io=18.6GiB (20.0GB), run=60001-60001msec
  WRITE: bw=136MiB/s (143MB/s), 136MiB/s-136MiB/s (143MB/s-143MB/s), io=8165MiB (8562MB), run=60001-60001msec

Disk stats (read/write):
  vdb: ios=4866340/2086666, merge=0/0, ticks=48750/22838, in_queue=71588, util=99.87%
```

**Comment by Comphix** [comment]
> > 
> 
> Thanks for your suggestion! We have a similar result on x86. Even though the Malloc backend is attached, the result is still similar. It seems that the VM IO requests cannot transfer to SPDK vhost efficiently. The following is the Malloc backend test results:
> 
> ```
> test-randrw: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
> fio-3.29
> Starting 1 thread
> Jobs: 1 (f=1): [m(1)][100.0%][r=319MiB/s,w=138MiB/s][r=81.6k,w=35.3k IOPS][eta 00m:00s]
> test-randrw: (groupid=0, jobs=1): err= 0: pid=996: Wed Apr 13 08:12:21 2022
>   read: IOPS=81.2k, BW=317MiB/s (333MB/s)(18.6GiB/60001msec)
>     slat (usec): min=2, max=447, avg= 5.47, stdev= 3.45
>     clat (usec): min=13, max=1409, avg=544.34, stdev=11.26
>      lat (usec): min=16, max=1412, avg=550.30, stdev=11.20
>     clat percentiles (usec):
>      |  1.00th=[  529],  5.00th=[  529], 10.00th=[  529], 20.00th=[  537],
>      | 30.00th=[  537], 40.00th=[  545], 50.00th=[  545], 60.00th=[  545],
>      | 70.00th=[  545], 80.00th=[  553], 90.00th=[  553], 95.00th=[  562],
>      | 99.00th=[  570], 99.50th=[  570], 99.90th=[  652], 99.95th=[  660],
>      | 99.99th=[  676]
>    bw (  KiB/s): min=320896, max=329856, per=100.00%, avg=325059.36, stdev=1565.59, samples=119
>    iops        : min=80224, max=82464, avg=81264.84, stdev=391.39, samples=119
>   write: IOPS=34.8k, BW=136MiB/s (143MB/s)(8165MiB/60001msec); 0 zone resets
>     slat (usec): min=2, max=824, avg= 6.38, stdev= 3.30
>     clat (usec): min=29, max=1401, avg=544.33, stdev=11.08
>      lat (usec): min=32, max=1412, avg=550.99, stdev=11.22
>     clat percentiles (usec):
>      |  1.00th=[  529],  5.00th=[  529], 10.00th=[  537], 20.00th=[  537],
>      | 30.00th=[  537], 40.00th=[  545], 50.00th=[  545], 60.00th=[  545],
>      | 70.00th=[  545], 80.00th=[  553], 90.00th=[  553], 95.00th=[  562],
>      | 99.00th=[  570], 99.50th=[  570], 99.90th=[  652], 99.95th=[  660],
>      | 99.99th=[  676]
>    bw (  KiB/s): min=136720, max=141968, per=100.00%, avg=139379.97, stdev=1087.98, samples=119
>    iops        : min=34180, max=35492, avg=34844.99, stdev=271.98, samples=119
>   lat (usec)   : 20=0.01%, 50=0.01%, 100=0.01%, 250=0.01%, 500=0.01%
>   lat (usec)   : 750=99.99%, 1000=0.01%
>   lat (msec)   : 2=0.01%
>   cpu          : usr=25.17%, sys=49.39%, ctx=322, majf=0, minf=1
>   IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
>      submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
>      complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
>      issued rwts: total=4874644,2090337,0,0 short=0,0,0,0 dropped=0,0,0,0
>      latency   : target=0, window=0, percentile=100.00%, depth=64
> 
> Run status group 0 (all jobs):
>    READ: bw=317MiB/s (333MB/s), 317MiB/s-317MiB/s (333MB/s-333MB/s), io=18.6GiB (20.0GB), run=60001-60001msec
>   WRITE: bw=136MiB/s (143MB/s), 136MiB/s-136MiB/s (143MB/s-143MB/s), io=8165MiB (8562MB), run=60001-60001msec
> 
> Disk stats (read/write):
>   vdb: ios=4866340/2086666, merge=0/0, ticks=48750/22838, in_queue=71588, util=99.87%
> ```

Thanks for reporting the issue. Would like to double confirm first, is this result collected on ARM platform or on Intel platform?

**Comment by Second222None** [comment]
> > > 
> > 
> > 
> > Thanks for your suggestion! We have a similar result on x86. Even though the Malloc backend is attached, the result is still similar. It seems that the VM IO requests cannot transfer to SPDK vhost efficiently. The following is the Malloc backend test results:
> > ```
> > test-randrw: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
> > fio-3.29
> > Starting 1 thread
> > Jobs: 1 (f=1): [m(1)][100.0%][r=319MiB/s,w=138MiB/s][r=81.6k,w=35.3k IOPS][eta 00m:00s]
> > test-randrw: (groupid=0, jobs=1): err= 0: pid=996: Wed Apr 13 08:12:21 2022
> >   read: IOPS=81.2k, BW=317MiB/s (333MB/s)(18.6GiB/60001msec)
> >     slat (usec): min=2, max=447, avg= 5.47, stdev= 3.45
> >     clat (usec): min=13, max=1409, avg=544.34, stdev=11.26
> >      lat (usec): min=16, max=1412, avg=550.30, stdev=11.20
> >     clat percentiles (usec):
> >      |  1.00th=[  529],  5.00th=[  529], 10.00th=[  529], 20.00th=[  537],
> >      | 30.00th=[  537], 40.00th=[  545], 50.00th=[  545], 60.00th=[  545],
> >      | 70.00th=[  545], 80.00th=[  553], 90.00th=[  553], 95.00th=[  562],
> >      | 99.00th=[  570], 99.50th=[  570], 99.90th=[  652], 99.95th=[  660],
> >      | 99.99th=[  676]
> >    bw (  KiB/s): min=320896, max=329856, per=100.00%, avg=325059.36, stdev=1565.59, samples=119
> >    iops        : min=80224, max=82464, avg=81264.84, stdev=391.39, samples=119
> >   write: IOPS=34.8k, BW=136MiB/s (143MB/s)(8165MiB/60001msec); 0 zone resets
> >     slat (usec): min=2, max=824, avg= 6.38, stdev= 3.30
> >     clat (usec): min=29, max=1401, avg=544.33, stdev=11.08
> >      lat (usec): min=32, max=1412, avg=550.99, stdev=11.22
> >     clat percentiles (usec):
> >      |  1.00th=[  529],  5.00th=[  529], 10.00th=[  537], 20.00th=[  537],
> >      | 30.00th=[  537], 40.00th=[  545], 50.00th=[  545], 60.00th=[  545],
> >      | 70.00th=[  545], 80.00th=[  553], 90.00th=[  553], 95.00th=[  562],
> >      | 99.00th=[  570], 99.50th=[  570], 99.90th=[  652], 99.95th=[  660],
> >      | 99.99th=[  676]
> >    bw (  KiB/s): min=136720, max=141968, per=100.00%, avg=139379.97, stdev=1087.98, samples=119
> >    iops        : min=34180, max=35492, avg=34844.99, stdev=271.98, samples=119
> >   lat (usec)   : 20=0.01%, 50=0.01%, 100=0.01%, 250=0.01%, 500=0.01%
> >   lat (usec)   : 750=99.99%, 1000=0.01%
> >   lat (msec)   : 2=0.01%
> >   cpu          : usr=25.17%, sys=49.39%, ctx=322, majf=0, minf=1
> >   IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
> >      submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
> >      complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
> >      issued rwts: total=4874644,2090337,0,0 short=0,0,0,0 dropped=0,0,0,0
> >      latency   : target=0, window=0, percentile=100.00%, depth=64
> > 
> > Run status group 0 (all jobs):
> >    READ: bw=317MiB/s (333MB/s), 317MiB/s-317MiB/s (333MB/s-333MB/s), io=18.6GiB (20.0GB), run=60001-60001msec
> >   WRITE: bw=136MiB/s (143MB/s), 136MiB/s-136MiB/s (143MB/s-143MB/s), io=8165MiB (8562MB), run=60001-60001msec
> > 
> > Disk stats (read/write):
> >   vdb: ios=4866340/2086666, merge=0/0, ticks=48750/22838, in_queue=71588, util=99.87%
> > ```
> 
> Thanks for reporting the issue. Would like to double confirm first, is this result collected on ARM platform or on Intel platform?

All the info I provided above comes from ARM platform. And My colleague found a similar problem on Intel's platform. If necessary, I can provide.

**Comment by Comphix** [comment]
Please Karol take a look and give some suggestion.

**Comment by karlatec** [comment]
Hi @Second222None 

So in your reproduction you get `89.8K (read IOPS), 498.5us (avg), 38.5K (write IOPS), 494.36us (avg)` which totals at about 128k IOPS.

In the reproduction steps you wrote `start VM`. I am assuming that's correct, and not a typo, in which case you run a single VM while in Vhost Report Test Case 3 there are 2 VMs used. Quoting from the document:
```
• 2 VMs were tested
• Each VM had a single Vhost device which was one of two equal partitions of
a single NVMe drive. 
```
Now assuming that you'd get similar results from a second VM then the result of 2 * 128k =~ 256k looks much better.  


In order to provide more tips I need some information about your set up. Could you please provide some, just like we did in `Test setup` chapter in the report document?
* CPU model (+ freq, cache, etc.)
* Host operating OS + kernel version
* Guest operating OS + kernel version
* SPDK version used (was it 22.01, or `master`?)
* Qemu emulator version
* Fio (in guest VM) version
* Used NVMe model
* BIOS Settings (power & performance policy, c-states, p-states, turbo boost, hyper threading, etc; I'm not sure what names could be used in your platform)
* Scaling governor set on the host systems (`cpupower frequency-info get` and/or `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`)

**Comment by Second222None** [comment]
NVMe SSD model： [ES3000 V5](https://vectorsolutions.net/wp-content/uploads/import/Huawei%20SSD%20ES3000%20V5%20NVMe%20Data%20Sheet.pdf) 6.4TB (88us/15us)
![image](https://user-images.githubusercontent.com/24448002/163707944-d062b326-f800-417c-9984-d8d5beb23d88.png)

Host and Guest OS: openEuler-21.09
fio：3.7
SPDK version：master[commit 0db0c443df06f68210e5504a90d32311ada9106b]
For the rest of the info, I didn't find the counterpart on the ARM platform for the time being.

**Comment by karlatec** [comment]
Hi @Second222None! Sorry for a late reply, I must have missed your comment.

> fio：3.7
I don't think it'd make that much difference, but could we try something a bit more recent? For the benchmark process we used 3.19.

> For the rest of the info

Could you provide info on these as well?

* CPU model (+ freq, cache, etc.)
* Host & Guest kernel version
* Qemu emulator version
* Scaling governor set on the host systems
* block device scheduler used in the guest VM

> I didn't find the counterpart on the ARM platform for the time being.

You also mentioned x86 results were not satisfactory. If you have access to this setup we could use it for comparison instead of ARM setup as it's easier to compare the BIOS stuff settings.

**Comment by changpe1** [comment]
closing this issue without responses from submitter for a long time. we don't see performance drop of  vhost in x86 platform.
