### ISSUE TITLE
lib/nvmf/tcp.c: nvmf_tcp_capsule_cmd_hdr_handle(): host sends more cmds than queue depth.

### ISSUE THREAD

**Issue by davidcs12** [spdk/spdk#2474]
# Bug report
This is more of a query and may not be a bug.
In the following function "nvmf_tcp_qpair_disconnect(tqpair);" is invoked when the  host sends more cmds than the queue depth. The query has to do with exploring if there a less disruptive solution?

static void
nvmf_tcp_capsule_cmd_hdr_handle(struct spdk_nvmf_tcp_transport *ttransport,
                struct spdk_nvmf_tcp_qpair *tqpair,
                struct nvme_tcp_pdu *pdu)
{
:    
    tcp_req = nvmf_tcp_req_get(tqpair);
    if (!tcp_req) {
:
        /* The host sent more commands than the maximum queue depth. */
        SPDK_ERRLOG("Cannot allocate tcp_req on tqpair=%p\n", tqpair);
        nvmf_tcp_qpair_disconnect(tqpair);        
        return;
    }
:
}

## Expected Behavior

Please see under "Possible Solutions"

## Current Behavior

In the current behavior nvmf_tcp_qpair_disconnect(tqpair); is invoked which Is disruptive.

## Possible Solution

To the best of my knowledge NVMe Specs do not prescribe a way method to handle this situation. Is there a more forgiving approach, perhaps:
1. dropping the command.
2. delay processing further cmds on the qpair till the "tcp_req" is replenished up to a defined threshold.

## Steps to Reproduce

Encountered while running heavy loads with 10 volumes (with  RHEL 8..3 host and SPDK22.01)

## Context (Environment including OS version, SPDK version, etc.)

Encountered while testing with  RHEL 8..3 host and SPDK22.01

**Comment by davidcs12** [comment]
@ksztyber @mkotwani1

**Comment by benlwalker** [comment]
NVMe-oF 1.1a:

```
If SQ flow control is disabled, then the host should limit the number of outstanding commands for a queue
pair to be less than the size of the Submission Queue. If the controller detects that the number of
outstanding commands for a queue pair is greater than or equal to the size of the Submission Queue, then
the controller shall:
a) stop processing commands and set the Controller Fatal Status (CSTS.CFS) bit to ‘1’ (refer to
section 10.5 in the NVMe Base specification); and
b) terminate the NVMe Transport connection and end the association between the host and the
controller.

[If SQ flow control is enabled] If the controller detects that the host has submitted a command capsule to a full Submission Queue, then
the controller shall:
a) stop processing commands and set the Controller Fatal Status (CSTS.CFS) bit to ‘1’ (refer to
section 10.5 in the NVMe Base specification); and
b) terminate the NVMe Transport connection and end the association between the host and the
controller
```

Closing this one as the correct behavior is to disconnect per spec.

**Comment by jimharris** [comment]
> ## Steps to Reproduce
> Encountered while running heavy loads with 10 volumes (with RHEL 8..3 host and SPDK22.01)

Can you describe more how these heavy loads are being run?  If the target reports it only supports 128 I/O queue size, then a well-functioning host driver shouldn't be sending more I/O commands than that (actually it shouldn't send more than 127).  I agree with everything here that the target is doing exactly what it should - my concern is that maybe the SPDK nvme driver is sending too many commands.

And incidentally, the SPDK nvme driver had a bug in this area - see commit 834e3c5.  This was merged after SPDK 22.01.  If you are using the SPDK nvme driver as part of testing the target, and it doesn't have this patch, you could hit this disconnect behavior.

I'm reopening this issue for now, just until we confirm that this isn't related to bad SPDK nvme driver behavior.

**Comment by davidcs12** [comment]
Thanks @ksztyber @benlwalker @jimharris .

@jimharris, we are not using the SPDK NVMe Driver on the Initiator side. The initiator side uses the stock nvme driver which comes with RHEL8.3 release (hence commit [834e3c5 ](https://github.com/spdk/spdk/commit/834e3c5a0eab5c2b37f0dc5012ed0822f3d3c4a9) is not relevant here) . Since the behavior is per spec., for NVMe/TCP target side we can close the issue #2474.
Incidentally the heavy load is generated by our internal tool.
Thanks
David S.

**Comment by jimharris** [comment]
> Thanks @ksztyber @benlwalker @jimharris .
> 
> @jimharris, we are not using the SPDK NVMe Driver on the Initiator side. The initiator side uses the stock nvme driver which comes with RHEL8.3 release (hence commit [834e3c5 ](https://github.com/spdk/spdk/commit/834e3c5a0eab5c2b37f0dc5012ed0822f3d3c4a9) is not relevant here) . Since the behavior is per spec., for NVMe/TCP target side we can close the issue #2474. Incidentally the heavy load is generated by our internal tool. Thanks David S.

Thanks for confirming @davidcs12!  Re-closing this issue.
