### ISSUE TITLE
[fio_dif_rand_params] unclear

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2476]
/home/vagrant/spdk_repo/spdk/build/fio/spdk_bdev'
00:14:45.238   23:34:47	-- common/autotest_common.sh@1194 -- # /usr/src/fio/fio --ioengine=spdk_bdev --spdk_json_conf /dev/fd/62 /dev/fd/61
00:14:45.238  filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=16
00:14:45.238  ...
00:14:45.238  filename1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=16
00:14:45.238  ...
00:14:45.238  filename2: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=16
00:14:45.238  ...
00:14:45.238  fio-3.28
00:14:45.238  Starting 24 threads
00:14:45.238  EAL: No available 1048576 kB hugepages reported
00:14:45.498  TELEMETRY: No legacy callbacks, legacy socket not created
00:14:49.694  /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 1177: 24899 Killed                  LD_PRELOAD="$asan_lib $plugin" "$fio_dir"/fio "$@"
00:14:49.694    23:34:51	-- common/autotest_common.sh@1194 -- # trap - ERR
00:14:49.694    23:34:51	-- common/autotest_common.sh@1194 -- # print_backtrace
00:14:49.694    23:34:51	-- common/autotest_common.sh@992 -- # [[ ehxBET =~ e ]]
00:14:49.694    23:34:51	-- common/autotest_common.sh@994 -- # args=('/dev/fd/61' '/dev/fd/62' '--spdk_json_conf' '--ioengine=spdk_bdev' '/home/vagrant/spdk_repo/spdk/build/fio/spdk_bdev' '/dev/fd/61' '/dev/fd/62' '--spdk_json_conf' '--ioengine=spdk_bdev' '/dev/fd/62' 'fio_dif_rand_params' 'fio_dif_rand_params' '--iso' '--transport=tcp')
00:14:49.694    23:34:51	-- common/autotest_common.sh@994 -- # local args
00:14:49.694    23:34:51	-- common/autotest_common.sh@996 -- # xtrace_disable
00:14:49.694    23:34:51	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:14:49.695    23:34:51	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:14:49.695    23:34:51	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:14:49.695    23:34:51	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:14:49.695    23:34:51	-- common/autotest_common.sh@19 -- # set +x
00:14:49.695  ========== Backtrace start: ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_75681.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_75682.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_75689.html

**Comment by jimharris** [comment]
Each of these failing builds exhibited the exact same failure on two different jobs - always nvmf-tcp-uring-vg-autotest on VM-host-SM0, and nvmf-tcp-vg-autotest on VM-host-PE1.

Passing builds between these failed builds, including names of the VM-host-*** systems these two jobs ran on:
(different) SM9, WFP1: https://ci.spdk.io/public_build/autotest-per-patch_75687.html
(same) SM0, PE1: https://ci.spdk.io/public_build/autotest-per-patch_75686.html
(different) SM4, WFP1: https://ci.spdk.io/public_build/autotest-per-patch_75685.html

Clearly this can't be a coincidence that we got these three failures in such a short time period?  And they all happened against the same patch.

I think we wait a day or so to see if this ever hits any other patches, or only https://review.spdk.io/gerrit/c/spdk/spdk/+/12310.

**Comment by peluse** [comment]
yeah, strange.  I'll take a closer look at my patch too

**Comment by peluse** [comment]
from dmesg: (note out_of_memory)
[  845.468590] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.14.0-0-g155821a1990b-prebuilt.qemu.org 04/01/2014
[  845.470032] Call Trace:
[  845.470365]  dump_stack+0x76/0x94
[  845.470797]  dump_header+0x4a/0x1f3
[  845.471246]  oom_kill_process.cold+0xb/0x10
**[  845.471778]  out_of_memory+0x229/0x4c0**
[  845.472258]  __alloc_pages_slowpath.constprop.0+0xbf0/0xcc0
[  845.472963]  __alloc_pages_nodemask+0x30a/0x340
[  845.473544]  pagecache_get_page+0x291/0x630
[  845.474082]  filemap_fault+0x6bf/0xa60
[  845.474563]  ext4_filemap_fault+0x2d/0x40
[  845.475077]  __do_fault+0x36/0x100
[  845.475515]  __handle_mm_fault+0xf55/0x15c0
[  845.476048]  handle_mm_fault+0xd5/0x2b0
[  845.476538]  do_user_addr_fault+0x1ba/0x670
[  845.477072]  exc_page_fault+0x67/0x150
[  845.477557]  ? asm_exc_page_fault+0x8/0x30
[  845.478084]  asm_exc_page_fault+0x1e/0x30
[  845.478596] RIP: 0033:0x7f4dbcde1718
[  845.479057] Code: Unable to access opcode bytes at RIP 0x7f4dbcde16ee.
[  845.479877] RSP: 002b:00007ffc5861ec28 EFLAGS: 00010206
[  845.480539] RAX: 0000000000000006 RBX: 00007f4dbe00dc26 RCX: 0000000000000066
[  845.481433] RDX: 0000000000000000 RSI: 00007f4dbe00dc26 RDI: 00007f4dbdc37f7b
[  845.482338] RBP: 00007ffc5861ec60 R08: 000000000000ffff R09: 0000000000000000
[  845.483234] R10: 00007f4dbcde1010 R11: 0000000000000293 R12: 0000000001a36380
[  845.484128] R13: 0000000000893880 R14: 0000000000000000 R15: 0000000000000000
[  845.485037] Mem-Info:

**Comment by peluse** [comment]
oh man, I'm allocating WAY more memory than the estimate that I was given.  Need to figure out how to solve this little problem.  It's in my patch for sure though so closing this issue.
