### ISSUE TITLE
qemu vfio branch no longer exists

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#2482]
# Bug report
Our image build system detect that branch vfio-user-v0.93 is no longer exits in repository https://github.com/oracle/qemu

[2022-04-25T03:28:53.467Z] 2022-04-25T05:28:53+02:00: ==> ubuntu2004: Cloning into '/git_repos/qemu/vfio-user-v0.93'...

[2022-04-25T03:28:53.726Z] 2022-04-25T05:28:53+02:00: ==> ubuntu2004: fatal: Remote branch vfio-user-v0.93 not found in upstream origin

## Expected Behavior

git clone should success

## Current Behavior

not working

## Possible Solution

I created test patch, but I'm not sure which branch should be chosen
https://review.spdk.io/gerrit/c/spdk/spdk/+/12358

## Steps to Reproduce
use pkgdep.sh script to install qemu vfio

**Comment by changpe1** [comment]
I used branch `vfio-user-dbfix` for testing, @tmakatos which branch do you suggest ? thanks.

**Comment by tmakatos** [comment]
Same, `vfio-user-dbfix`.

**Comment by karlatec** [comment]
@tmakatos @changpe1 is there any possibility to somehow mark this branch as "do not delete"? 
The process of building OS images for SPDK CI relies on the existence of the branch.

**Comment by karlatec** [comment]
@xjjx could you please update the vfio-user branch in our builder scripts?

**Comment by karlatec** [comment]
@changpe1 
Please also consider that starting with SPDK 22.01 release we've started to add vfio-user vs vhost comparison to quarterly SPDK Vhost performance report. How much does `dbfix` branch differ from `v0.93` and was it tested with functional tests?

**Comment by changpe1** [comment]
> @changpe1 Please also consider that starting with SPDK 22.01 release we've started to add vfio-user vs vhost comparison to quarterly SPDK Vhost performance report. How much does `dbfix` branch differ from `v0.93` and was it tested with functional tests?

QEMU will not affect performance, because the data path isn't related with QEMU, so just functional tests is OK.

**Comment by tmakatos** [comment]
> @tmakatos @changpe1 is there any possibility to somehow mark this branch as "do not delete"? The process of building OS images for SPDK CI relies on the existence of the branch.

@karlatec I don't own this repository, you can speak to the maintainers. I suppose you could fork this repo in SPDK? Also, there is good chance that this will get merged in QEMU pretty soon so this might be a temporary problem.

**Comment by changpe1** [comment]
> > @tmakatos @changpe1 is there any possibility to somehow mark this branch as "do not delete"? The process of building OS images for SPDK CI relies on the existence of the branch.
> 
> @karlatec I don't own this repository, you can speak to the maintainers. I suppose you could fork this repo in SPDK? Also, there is good chance that this will get merged in QEMU pretty soon so this might be a temporary problem.

See the latest comments on https://lists.gnu.org/archive/html/qemu-devel/2022-04/msg02243.html, looks like the QEMU community will accept it shortly, the migration feature was removed for this version, is it? @tmakatos

**Comment by tmakatos** [comment]
> See the latest comments on https://lists.gnu.org/archive/html/qemu-devel/2022-04/msg02243.html, looks like the QEMU community will accept it shortly, the migration feature was removed for this version, is it? @tmakatos

Yes, migration is temporarily removed until it gets replaced by v2, so maybe we should fork QEMU in SPDK temporarily just to have an copy of the working migration code.

**Comment by xjjx** [comment]
Branch has been changed so issue is no longer valid. Closing.
