### ISSUE TITLE
On branch v22.01.x, found `Could not allocate cache buffer` again

### ISSUE THREAD

**Issue by ddwolf** [spdk/spdk#2485]
On branch v22.01.x, found this issue raised again:
[root@host-10-90-54-107 spdk]# `cat rocksdb.json`
```json
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "trtype": "PCIe",
            "name":"Nvme0",
            "traddr":"0000:d8:00.0"
          }
        }
      ]
    }
  ]
}
```
[root@host1 fufs]# `test/blobfs/mkfs/mkfs rocksdb.json Nvme0n1`
> [2022-04-26 16:25:39.696417] Starting SPDK v22.01.1-pre git sha1 7fc39d249 / DPDK 21.11.0 initialization...
> [2022-04-26 16:25:39.696495] [ DPDK EAL parameters: [2022-04-26 16:25:39.696508] spdk_mkfs [2022-04-26 16:25:39.696517] --no-shconf [
> 2022-04-26 16:25:39.696528] -c 0x3 [2022-04-26 16:25:39.696537] --log-level=lib.eal:6 [2022-04-26 16:25:39.696546] --log-level=lib.cr
> yptodev:5 [2022-04-26 16:25:39.696555] --log-level=user1:6 [2022-04-26 16:25:39.696564] --iova-mode=pa [2022-04-26 16:25:39.696573] -
> -base-virtaddr=0x200000000000 [2022-04-26 16:25:39.696581] --match-allocations [2022-04-26 16:25:39.696591] --file-prefix=spdk_pid154
> 2595 [2022-04-26 16:25:39.696600] ]
> EAL: No free 2048 kB hugepages reported on node 1
> EAL: No available 1048576 kB hugepages reported
> TELEMETRY: No legacy callbacks, legacy socket not created
> [2022-04-26 16:25:39.755723] app.c: 601:spdk_app_start: *NOTICE*: Total cores available: 2
> [2022-04-26 16:25:39.908928] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 1
> [2022-04-26 16:25:39.908931] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
> [2022-04-26 16:25:39.909729] accel_engine.c: 510:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
> Initializing filesystem on bdev Nvme0n1...done.

[root@host1 fufs]# ` ./test/blobfs/fuse/fuse rocksdb.json Nvme0n1 fufs/`
> [root@host-10-90-54-107 spdk]# ./test/blobfs/fuse/fuse rocksdb.json Nvme0n1 fufs3
> [2022-04-26 16:28:35.538164] Starting SPDK v22.01.1-pre git sha1 7fc39d249 / DPDK 21.11.0 initialization...
> [2022-04-26 16:28:35.538234] [ DPDK EAL parameters: [2022-04-26 16:28:35.538246] spdk_fuse [2022-04-26 16:28:35.538255] --no-shconf [
> 2022-04-26 16:28:35.538264] -c 0x3 [2022-04-26 16:28:35.538272] --log-level=lib.eal:6 [2022-04-26 16:28:35.538281] --log-level=lib.cr
> yptodev:5 [2022-04-26 16:28:35.538289] --log-level=user1:6 [2022-04-26 16:28:35.538297] --iova-mode=pa [2022-04-26 16:28:35.538306] -
> -base-virtaddr=0x200000000000 [2022-04-26 16:28:35.538320] --match-allocations [2022-04-26 16:28:35.538328] --file-prefix=spdk_pid159
> 6428 [2022-04-26 16:28:35.538337] ]
> EAL: No free 2048 kB hugepages reported on node 1
> EAL: No available 1048576 kB hugepages reported
> TELEMETRY: No legacy callbacks, legacy socket not created
> [2022-04-26 16:28:35.595372] app.c: 601:spdk_app_start: *NOTICE*: Total cores available: 2
> [2022-04-26 16:28:35.748647] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 1
> [2022-04-26 16:28:35.748649] reactor.c: 943:reactor_run: *NOTICE*: Reactor started on core 0
> [2022-04-26 16:28:35.749397] accel_engine.c: 510:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software eng
> ine.
> Mounting filesystem on bdev Nvme0n1 to path fufs3...
> done.
> [2022-04-26 16:28:35.936471] blobfs_fuse.c: 268:fuse_loop_new_thread: *NOTICE*: Start to loop blobfs on bdev Nvme0n1 mounted at fufs

[root@host1 fufs]# `ls -lh`
> total 0
> -rw-r--r--. 1 root root 768M Jan  1  1970 hello.o

[root@host-10-90-54-107 fufs3]# yes >> hello
> yes: standard output: Cannot allocate memory
**and the output in the fuse command window shows this**
> blobfs.c:2146:cache_insert_buffer: *ERROR*: Could not allocate cache buffer for file=0x1c9c6d0 on offset=3a80000

With restarting of fuse command, I can still append to the file, but after many times of these steps, finally the fuse dumped with a segmentation fault
> Segmentation fault (core dumped)

build commands are:
```
./configure --prefix=$HOME/app/spdk --with-fuse
make
```

_Originally posted by @ddwolf in https://github.com/spdk/spdk/issues/1211#issuecomment-1109438519_

**Comment by Comphix** [comment]
From above log:

```
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
```

Looks like there is no Hugepage allocated on node 1?

Please share the result of ./scripts/setup.sh status for the Hugepage allocation.

**Comment by ddwolf** [comment]
> Please share the result of ./scripts/setup.sh status for the Hugepage allocation.

@Comphix here is the output, looks like all good

# HUGEMEM=5120 scripts/setup.sh
0000:80:04.7 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.6 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.5 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.4 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.3 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.2 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.1 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.0 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.7 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.6 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.5 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.4 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.3 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.2 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.1 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.0 (8086 2021): ioatdma -> uio_pci_generic
0000:d8:00.0 (19e5 0123): nvme -> uio_pci_generic

**Comment by dong-liuliu** [comment]
@Bianyfan hi, Yifan, let's also watch on this issue

**Comment by ddwolf** [comment]
finally, I got these directories and don't know how to remove them:)
```
$ ls -lt | grep fufs
ls: cannot access 'fufs': Transport endpoint is not connected
ls: cannot access 'fufs1': Transport endpoint is not connected
ls: cannot access 'fufs3': Transport endpoint is not connected
d??????????  ? ?    ?          ?            ? fufs
d??????????  ? ?    ?          ?            ? fufs1
d??????????  ? ?    ?          ?            ? fufs3
```

**Comment by Bianyfan** [comment]
hi @ddwolf , thanks for your reporting. These files are just mountpoint you tested before but with a incorrect close, a simple way to remove is to use "umount fufs" and then you can remove like directory.

**Comment by ddwolf** [comment]
@Bianyfan that works, Great~

**Comment by jimharris** [comment]
@ddwolf - is this issue resolved for you now?  If so can we close this issue?  Thanks.

**Comment by ddwolf** [comment]
This issue has been Solved, you can close it now, thank you so much.
