### ISSUE TITLE
Retrieving drive logs 

### ISSUE THREAD

**Issue by BhanuKumarRV** [spdk/spdk#249]
How do we retrieve drive logs through SPDK for vendor specific commands?
Can we extend spdk_nvme_log_page in Nvme_spec.h under include\spdk?

**Comment by BhanuKumarRV** [comment]
We are adding commands to retrieve data for multiple failures and logs of various components within our system.

**Comment by dverkamp-intel** [comment]
spdk_nvme_ctrlr_cmd_get_log_page() is generic and should work for any log page (vendor specific or not).

Can you provide some clarifying details on what you're trying to achieve and why the existing API doesn't work?

**Comment by jimharris** [comment]
Closing this issue - recommendations above describe how to retrieve drive logs.
