### ISSUE TITLE
Setting scheduler back to `static` from `dynamic` doesn't re-distribute threads evenly to all reactors

### ISSUE THREAD

**Issue by fangli** [spdk/spdk#2492]
# Bug report

**Reproduce step is simple as below:**

```
# (start latest SPDK with more than 1 CPU cores)
# ./scripts/rpc.py framework_set_scheduler dynamic
# ./scripts/rpc.py framework_set_scheduler static
```

**Current Behaviour:**

Then look at the CPU or spdk_top, all threads still reside on a single CPU core.

**Expected Behaviour:**

When setting scheduler back to `static`, threads should be re-distributed evenly to all reactors again.

-----

Just a thought, we probably want to call `_move_thread` explicitly when scheduler is set to `static`.

Please let me know if I understand it wrong.

// DISCLAIMER: This issue report and entire discussion is only for software I use personally, outside of work. The issue report has nothing to do with the company I work for. I wouldn't be able to propose a CR without going through some extra processes.

**Comment by jimharris** [comment]
Currently "static" is just defined and implemented as "keep the threads where they are and don't move them".  This should be clarified in the docs.

```
When setting scheduler back to static, threads should be re-distributed evenly to all reactors again.
```

I think what you are really expecting or wanting is the ability to revert the thread placement back to what it was when the application started.  This is not necessarily an even distribution across all reactors, and is not easily done by the scheduler framework itself.  I can see where this might be useful, but I would consider this an enhancement request, with multiple possibilities for implementation.

**Comment by fangli** [comment]
Thanks Harris! I understand that. Sounds reasonable just feel a bit weird
A user can't go back to its original status once dynamic is set, so the `static` and `dynamic` seems to be a one-way door, meaning `static` is more like a `pause` status for current scheduler.

I'm closing the issue as it's an expected feature.
Thanks again.

**Comment by jimharris** [comment]
> Thanks Harris! I understand that. Sounds reasonable just feel a bit weird A user can't go back to its original status once dynamic is set, so the `static` and `dynamic` seems to be a one-way door, meaning `static` is more like a `pause` status for current scheduler.

Would you be OK if we leave this open, but mark as enhancement request?  I don't think we should implement this as part of the static scheduler, but maybe we could have an RPC that gets the current thread/reactor assignments and another RPC that can specifically move thread X to reactor Y.  We could have a helper script then to enable setting up any specific thread-to-reactor topology.  I could this being useful for more than just reverting back to the startup state of the target.

**Comment by fangli** [comment]
This is a brilliant idea! It also gives user more precise control or implement their own logic with simple scripts.

Looking forward to seeing it soon.

**Comment by KKaras169169** [comment]
TODO on next Bug Scrub: Are RPCs the way to go?

**Comment by KKaras169169** [comment]
Bug Scrub: Setting scheduler back to static at runtime is not desired, as it is currently impossible to map SPDK threads to reactors consistently over multiple back and forth scheduler changes (if we were force redistribution of threads, we would get different performance results, as threads would not always land on the same core).
As a result of discussion during BugScrub meeting, I'll implement a mechanism to block setting scheduler back to static at runtime. Setting scheduler from static to dynamic will still be possible at runtime.

**Comment by KKaras169169** [comment]
Here is the patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/15055

**Comment by KKaras169169** [comment]
The change has been merged. I'll close the issue for now, but we may reopen it in the future if we find a way to ensure consistent SPDK thread distribution on reactors.
