### ISSUE TITLE
nvmf/vfio-performance lower than virtio-scsi

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2494]
I'm using eef6af95d to compare the performance of nvmf/vfio-user to virtio-scsi from within a guest, specifically single I/O random read IOPS. With virtio-scsi I get 560K IOPS while with nvmf/vfio-user I only get 370K IOPS. Using a custom virtio-scsi implermentation instead of SPDK's, I get over 930K IOPS, while nvmf/vfio-user only goes up to 383K IOPS.

The nvmf/vfio-user and virtio-scsi disks are both backed by a {{bdev_null}}.
The guest has a single vCPU and 4GiB of RAM, using 
The host is Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz,

I'm using the following fio configuration:
```
[global]
allrandrepeat=1
blocksize=4KiB
direct=1
end_fsync=0
exitall=1
exitall_on_error=1
fadvise_hint=1
group_reporting=1
kb_base=1000
nice=-16
norandommap=1
numjobs=1
iodepth=1
randseed=314159
thread=1
size=100%
readwrite=randread
#size=16384
runtime=300
time_based=1
gtod_reduce=1
nice=-16
norandommap=1
numjobs=1
iodepth=1
randseed=314159
thread=1
size=100%
readwrite=randread
runtime=300
time_based=1
gtod_reduce=1
disable_lat=1

[vnvme-single]
ioengine=spdk
filename=trtype=PCIe traddr=00.04.0 ns=1

[virtio-scsi-single]
ioengine=spdk_bdev
spdk_json_conf=bdev.json
filename=thanost0
```
bdev.json:
```
{
        "subsystems": [
                {
                        "subsystem": "bdev",
                        "config": [
                                {
                                        "method": "bdev_virtio_attach_controller",
                                        "params": {
                                                "trtype": "pci",
                                                "name": "thanos",
                                                "traddr": "0000:00:04.0",
                                                "dev_type": "scsi"
                                        }
                                }
                        ]
                }
        ]
}
```

Using
```
./build/examples/perf -q 1 -w randread -t 30 -r 'trtype:PCIe traddr:000:00:04.0' -b 000:00:04.0 -O $((2*1024*1024*1024)) -o 4096 |& tee perf.log
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
Attached to NVMe Controller at 0000:00:04.0 [4e58:0001]
Associating PCIE (0000:00:04.0) NSID 1 with lcore 0
Initialization complete. Launching workers.
========================================================
										                           Latency(us)
Device Information                     :       IOPS      MiB/s    Average        min        max
PCIE (0000:00:04.0) NSID 1 from core  0:  372614.20    1455.52       2.67       1.56     363.96
========================================================
Total                                  :  372614.20    1455.52       2.67       1.56     363.96
```
I've tried looking at where the time goes but I don't find anything that stands out.

FYI @jlevon @changpe1 @jimharris @benlwalker

**Comment by tmakatos** [comment]
I've reduced the frequency of calling `vfio_user_poll_vfu_ctx` to one millionth and IOPS shot up to over 1M IOPS.

**Comment by jimharris** [comment]
[Bug scrub] We should be able to reduce polling on this vfu_ctx to once every millisecond or so, if the doorbells are mapped.  We could also make this somewhat adaptive to be more responsive when we expect a sequence of register writes - i.e. controller reset.  In that case we could change the frequency temporarily.  But for now just reducing this to a 1ms polling period would be sufficient.

If the doorbells are not mapped, we need to poll this more frequently, but that should be based on an fd becoming ready, not active polling.  Interrupt mode for this is not enabled yet however.

@tmakatos can you push a patch for the polling period changes?  And then we need someone to take a look at enabling interrupt mode for the vfu_ctx.

**Comment by jimharris** [comment]
Assigning to @tmakatos for now, for the polling period change.  We can reassign later for the interrupt mode.

**Comment by tmakatos** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/12494

**Comment by changpe1** [comment]
Indeed polling the socket fd too frequently will cause performance issue, it's a good fix, just wondering why I can't produce similar performance result in my test environment, see https://github.com/spdk/spdk/issues/2477, I also tried some tests between vfio-user NVMe and vhost-user BLK.
