### ISSUE TITLE
lib/nvmf/vfio user: Validate count, Register read writes - one byte read

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2495]
In vfio_user_property_access() we are not validating the input var count so a one byte read here:

req->req.cmd->prop_set_cmd.attrib.size = (count / 4) - 1;

would be bad.

**Comment by changpe1** [comment]
A fix patch is submitted via https://review.spdk.io/gerrit/c/spdk/spdk/+/12643.

**Comment by changpe1** [comment]
patch has been merged, closing it now.
