### ISSUE TITLE
[VM-host-CH2] Fetch failure: premature end of Content-Length delimited message body

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2497]
# CI Intermittent Failure
Failed to fetch the sources on VM-host-CH2. Supposedly, this only happens on CH machines. @xjjx says it should already be fixed, but opening the issue to have something to link as a false positive.
```
00:00:12.827  Found a total of 1 nodes with the 'sorcerer' label
00:00:12.838  [Pipeline] httpRequest
00:00:13.037  HttpMethod: GET
00:00:13.038  URL: http://spdk-GP-10.igk.intel.com/spdk_af4214d1bf79895b9996eb1aabb02e5eac1d8aa9.tar.gz
00:00:13.039  Sending request to url: http://spdk-GP-10.igk.intel.com/spdk_af4214d1bf79895b9996eb1aabb02e5eac1d8aa9.tar.gz
00:00:13.442  Response Code: HTTP/1.1 200 OK
00:00:13.442  Success: Status code 200 is in the accepted range: 200,404
00:00:13.443  Saving response body to /var/jenkins/workspace/scanbuild-vg-autotest/spdk_af4214d1bf79895b9996eb1aabb02e5eac1d8aa9.tar.gz
00:01:29.154  [Pipeline] }
00:01:29.177  [Pipeline] // stage
00:01:29.186  [Pipeline] }
00:01:29.204  [Pipeline] // node
00:01:29.222  [Pipeline] End of Pipeline
00:01:29.237  org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 201,771,937; received: 56,051,464)
00:01:29.237  	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
00:01:29.237  	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
00:01:29.237  	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
00:01:29.237  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1309)
00:01:29.237  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
00:01:29.237  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
00:01:29.237  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
00:01:29.237  	at jenkins.plugins.http_request.HttpRequestExecution.processResponse(HttpRequestExecution.java:484)
00:01:29.237  	at jenkins.plugins.http_request.HttpRequestExecution.authAndRequest(HttpRequestExecution.java:367)
00:01:29.237  	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:271)
```

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/76472/archive/scanbuild-vg-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_76472.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76472.html

**Comment by xjjx** [comment]
Patch is waiting for review.
On CH* machines we back to standard git clone because this issue happen when we transfer package with sources, seems that internal network is a little unstable :)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76464.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76564.html

**Comment by xjjx** [comment]
Patch has been merged. It should work better from now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_76592.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_76573.html

**Comment by ksztyber** [comment]
Closing since the patch has been merged almost a week ago.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_76935.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_81453.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @xjjx. log: https://ci.spdk.io/public_build/autotest-per-patch_84305.html
