### ISSUE TITLE
[spdk compile issue]spdk compile failed with error

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2505]
# Bug report
spdk compile failed with error

## Expected Behavior
spdk should pass compilation

## Steps to Reproduce

1. yum install bpftrace libubsan
2. git clone https://github.com/spdk/spdk.git
3. git submodule update --init
4. ./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/home/qwan/utils/fio --with-iscsi-initiator --disable-unit-tests --enable-ubsan --enable-coverage --without-isal --with-shared
5. make

then it will report the following errors:

> _ninja: Entering directory `/home/qwan/multipath/spdk/dpdk/build-tmp'
> ninja: no work to do.
>   CC examples/bdev/fio_plugin/fio_plugin.o
> In file included from /home/qwan/multipath/spdk/include/spdk/stdinc.h:55,
>                  from fio_plugin.c:34:
> /home/qwan/utils/fio/arch/../lib/types.h:5:13: error: two or more data types in declaration specifiers
>     5 | typedef int bool;
>       |             ^~~~
> In file included from /home/qwan/utils/fio/arch/arch.h:10,
>                  from /home/qwan/utils/fio/thread_options.h:4,
>                  from /home/qwan/utils/fio/fio.h:18,
>                  from fio_plugin.c:50:
> /home/qwan/utils/fio/arch/../lib/types.h:5:1: error: useless type name in empty declaration [-Werror]
>     5 | typedef int bool;
>       | ^~~~~~~
> In file included from /home/qwan/utils/fio/os/os.h:39,
>                  from /home/qwan/utils/fio/thread_options.h:5,
>                  from /home/qwan/utils/fio/fio.h:18,
>                  from fio_plugin.c:50:
> /home/qwan/utils/fio/os/os-linux.h:147:19: error: static declaration of ‘gettid’ follows non-static declaration
>   147 | static inline int gettid(void)
>       |                   ^~~~~~
> In file included from /usr/include/unistd.h:1187,
>                  from /home/qwan/multipath/spdk/include/spdk/stdinc.h:76,
>                  from fio_plugin.c:34:
> /usr/include/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ with type ‘__pid_t(void)’ {aka ‘int(void)’}
>    34 | extern __pid_t gettid (void) __THROW;
>       |                ^~~~~~
> In file included from /home/qwan/utils/fio/os/os.h:39,
>                  from /home/qwan/utils/fio/thread_options.h:5,
>                  from /home/qwan/utils/fio/fio.h:18,
>                  from fio_plugin.c:50:
> /home/qwan/utils/fio/os/os-linux.h:346:23: error: conflicting types for ‘preadv2’; have ‘ssize_t(int,  const struct iovec *, int,  off_t,  unsigned int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  unsigned int)’}
>   346 | static inline ssize_t preadv2(int fd, const struct iovec *iov, int iovcnt,
>       |                       ^~~~~~~
> In file included from /home/qwan/multipath/spdk/include/spdk/stdinc.h:86,
>                  from fio_plugin.c:34:
> /usr/include/sys/uio.h:127:16: note: previous declaration of ‘preadv2’ with type ‘ssize_t(int,  const struct iovec *, int,  __off_t,  int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  int)’}
>   127 | extern ssize_t preadv2 (int __fp, const struct iovec *__iovec, int __count,
>       |                ^~~~~~~
> In file included from /home/qwan/utils/fio/os/os.h:39,
>                  from /home/qwan/utils/fio/thread_options.h:5,
>                  from /home/qwan/utils/fio/fio.h:18,
>                  from fio_plugin.c:50:
> /home/qwan/utils/fio/os/os-linux.h:354:23: error: conflicting types for ‘pwritev2’; have ‘ssize_t(int,  const struct iovec *, int,  off_t,  unsigned int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  unsigned int)’}
>   354 | static inline ssize_t pwritev2(int fd, const struct iovec *iov, int iovcnt,
>       |                       ^~~~~~~~
> In file included from /home/qwan/multipath/spdk/include/spdk/stdinc.h:86,
>                  from fio_plugin.c:34:
> /usr/include/sys/uio.h:131:16: note: previous declaration of ‘pwritev2’ with type ‘ssize_t(int,  const struct iovec *, int,  __off_t,  int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  int)’}
>   131 | extern ssize_t pwritev2 (int __fd, const struct iovec *__iodev, int __count,
>       |                ^~~~~~~~
> In file included from /home/qwan/utils/fio/fio.h:29,
>                  from fio_plugin.c:50:
> /home/qwan/utils/fio/helpers.h:11:12: error: conflicting types for ‘sync_file_range’; have ‘int(int,  uint64_t,  uint64_t,  unsigned int)’ {aka ‘int(int,  long unsigned int,  long unsigned int,  unsigned int)’}
>    11 | extern int sync_file_range(int fd, uint64_t offset, uint64_t nbytes,
>       |            ^~~~~~~~~~~~~~~
> In file included from /usr/include/bits/fcntl.h:61,
>                  from /usr/include/fcntl.h:35,
>                  from /home/qwan/multipath/spdk/include/spdk/stdinc.h:67,
>                  from fio_plugin.c:34:
> /usr/include/bits/fcntl-linux.h:383:12: note: previous declaration of ‘sync_file_range’ with type ‘int(int,  __off64_t,  __off64_t,  unsigned int)’ {aka ‘int(int,  long int,  long int,  unsigned int)’}
>   383 | extern int sync_file_range (int __fd, __off64_t __offset, __off64_t __count,
>       |            ^~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> make[3]: *** [/home/qwan/multipath/spdk/mk/spdk.common.mk:465: fio_plugin.o] Error 1
> make[2]: *** [/home/qwan/multipath/spdk/mk/spdk.subdirs.mk:44: fio_plugin] Error 2
> make[1]: *** [/home/qwan/multipath/spdk/mk/spdk.subdirs.mk:44: bdev] Error 2
> make: *** [/home/qwan/multipath/spdk/mk/spdk.subdirs.mk:44: examples] Error 2_

## Context (Environment including OS version, SPDK version, etc.)
spdk commit: 0849aadceb820b8390902a2f06999c6eced94c6d
os kernel: 5.11.12-300.fc34.x86_64

**Comment by changpe1** [comment]
Are you using gcc as the compiler?

**Comment by wanqunintel** [comment]
yes, i think so.

**Comment by wanqunintel** [comment]
i tried to recompile the fio and also recompile the spdk, now it passed. sorry for the confusion.

**Comment by Comphix** [comment]
Issue solved. Close it.
