### ISSUE TITLE
spdk_thread not destroyed after call spdk_thread_exit in interrupt mode

### ISSUE THREAD

**Issue by jumpapex** [spdk/spdk#2506]
# Bug report

1. call spdk_interrupt_mode_enable() to enable interrupt mode.
2. create a spdk_thread with by spdk_thread_create. 
3. call spdk_thread_exit on it. the spdk_thread is not destroyed until app exit.

## Expected Behavior
spdk_thread should be destroyed after call spdk_thread_exit on it.

## Current Behavior
spdk_thread not destroyed after call spdk_thread_exit, it will be destroyed until app exit

## Possible Solution
reactor_run() call reactor_interrupt_run() in interrupt mode, and reactor_interrupt_run() does not do the destroy as _reactor_run() does with exited thread.
Is it by design or I have missed something?

## Steps to Reproduce
1. call spdk_interrupt_mode_enable() to enable interrupt mode.
2. enable thread debug message
3. create a spdk_thread with by spdk_thread_create. 
4. call spdk_thread_exit on it. no "Destroy thread..." message.
5. exit app. seen "Destroy thread..." message.

## Context (Environment including OS version, SPDK version, etc.)
RockyLinux 8.4, SPDK 22.01

**Comment by changpe1** [comment]
@jumpapex I think this is expected, you can call spdk_thread_destroy() to destroy the thread.

**Comment by changpe1** [comment]
[Bug Scrub] closing this one now.
