### ISSUE TITLE
Unable to mount ext4 over nbd with logical volume bdev

### ISSUE THREAD

**Issue by TheSSDGuy** [spdk/spdk#2508]
# Bug report

I'm trying to mount a ext4 file-system on an nbd device which is connected to a logical volume block device.
The OS fails to format the device and no file-system is mounted.

## Steps to Reproduce
sudo ./scripts/rpc.py **bdev_nvme_attach_controller** -b hNVMe0 -t PCIe -a 0000:01:00.0
hNVMe0n1

sudo ./scripts/rpc.py bdev_lvol_create_lvstore hNVMe0n1 glvs
8e7335e3-c5a6-4c24-8745-efa001281591

sudo ./scripts/rpc.py bdev_lvol_create -l glvs p0 16384
cf3bdf48-d6d3-40aa-bd10-503fa2036e40

sudo ./scripts/rpc.py nbd_start_disk glvs/p0 /dev/nbd0
/dev/nbd0

Here's the message i get:
![image](https://user-images.githubusercontent.com/46682946/167999522-32d7372b-d261-4be5-82bd-ee4ed9f99a5f.png)

The same bug is manifested also with malloc block device:
sudo ./scripts/rpc.py **bdev_malloc_create** -b hNVMe0n1 1024 4096
hNVMe0n1

sudo ./scripts/rpc.py bdev_lvol_create_lvstore hNVMe0n1 glvs
09e5f6f1-9b38-4bcf-87ba-909d475eb9db

sudo ./scripts/rpc.py bdev_lvol_create -l glvs p0 128
a41b66c8-0527-4e70-a33a-06544662adf3

sudo ./scripts/rpc.py nbd_start_disk glvs/p0 /dev/nbd0
/dev/nbd0

Here's the message i get:
![image](https://user-images.githubusercontent.com/46682946/168003056-3203ad6d-2522-42b9-bd36-dc91268feaad.png)

## Possible Solution

Since the bug seems not related to the underlying storage block device (the bug is manifested both with nvme bdev and malloc bdev) maybe it sits between the lvstore bdev and lvol bedev.

## Context (Environment including OS version, SPDK version, etc.)
OS version: Ubuntu: 18.04LTS
Kernel version: 5.3.0-050300-generic
Grub command line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_iommu=on"
SSD used: Intel P4610

SPDK configuration:

sudo ./scripts/setup.sh
0000:01:00.0 (8086 0a54): nvme -> uio_pci_generic

sudo ./build/bin/spdk_tgt -m [0,1]
[2022-05-12 07:54:56.714725] **Starting SPDK v22.05-pre git sha1 f331ae167 / DPDK 21.11.0 initialization**...
[2022-05-12 07:54:56.715017] [ DPDK EAL parameters: [2022-05-12 07:54:56.715110] spdk_tgt [2022-05-12 07:54:56.715157] --no-shconf [2022-05-12 07:54:56.715198] -l 0,1 [2022-05-12 07:54:56.715240] --huge-unlink [2022-05-12 07:54:56.715281] --log-level=lib.eal:6 [2022-05-12 07:54:56.715322] --log-level=lib.cryptodev:5 [2022-05-12 07:54:56.715364] --log-level=user1:6 [2022-05-12 07:54:56.715399] --iova-mode=pa [2022-05-12 07:54:56.715434] --base-virtaddr=0x200000000000 [2022-05-12 07:54:56.715464] --match-allocations [2022-05-12 07:54:56.715494] --file-prefix=spdk_pid3090 [2022-05-12 07:54:56.715533] ]
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-05-12 07:54:56.857654] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 2
[2022-05-12 07:54:56.980764] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 1
[2022-05-12 07:54:56.980766] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-05-12 07:54:56.980866] accel_engine.c: 842:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.

**Comment by Comphix** [comment]
Will you have a try with 512 blocksize?

sudo ./scripts/rpc.py bdev_malloc_create -b hNVMe0n1 1024 512  <<<<<<

**Comment by TheSSDGuy** [comment]
> Will you have a try with 512 blocksize?
> 
> sudo ./scripts/rpc.py bdev_malloc_create -b hNVMe0n1 1024 512 <<<<<<

Nope, same result:

sudo ./scripts/rpc.py bdev_malloc_create -b hNVMe0n1 1024 512
hNVMe0n1

sudo ./scripts/rpc.py bdev_lvol_create_lvstore hNVMe0n1 glvs
127493fc-716c-49ef-8cc0-40c35459668a

sudo ./scripts/rpc.py bdev_lvol_create -l glvs p0 128
92c16328-0fd9-4e0f-a570-29a465463008

sudo ./scripts/rpc.py nbd_start_disk glvs/p0 /dev/nbd0
/dev/nbd0

![image](https://user-images.githubusercontent.com/46682946/168006040-b3d37d31-ff2d-477c-a621-27a3bc8a57b9.png)

**Comment by Comphix** [comment]
Will you also try to create the Logical Volume with 512 blocksize

Refer to https://spdk.io/doc/bdev.html

Example command

rpc.py bdev_lvol_create_lvstore Malloc2 lvs -c 4096

This will create lvol store named lvs with cluster size 4096, build on top of Malloc2 bdev. In response user will be provided with uuid which is unique lvol store identifier.

User can get list of available lvol stores using bdev_lvol_get_lvstores RPC command (no parameters available).

If blocksize parameter is not specified, it is using the default 4096.

The basic idea here is to have the 512 blocksize for related block devices.

Example response

{
  "uuid": "330a6ab2-f468-11e7-983e-001e67edf35d",
  "base_bdev": "Malloc2",
  "free_clusters": 8190,
  "cluster_size": 8192,
  "total_data_clusters": 8190,
  "block_size": 4096,  <<<<<<
  "name": "lvs"
}

**Comment by TheSSDGuy** [comment]
> Will you also try to create the Logical Volume with 512 blocksize
> 
> Refer to https://spdk.io/doc/bdev.html
> 
> Example command
> 
> rpc.py bdev_lvol_create_lvstore Malloc2 lvs -c 4096
> 
> This will create lvol store named lvs with cluster size 4096, build on top of Malloc2 bdev. In response user will be provided with uuid which is unique lvol store identifier.
> 
> User can get list of available lvol stores using bdev_lvol_get_lvstores RPC command (no parameters available).
> 
> If blocksize parameter is not specified, it is using the default 4096.
> 
> The basic idea here is to have the 512 blocksize for related block devices.
> 
> Example response
> 
> { "uuid": "330a6ab2-f468-11e7-983e-001e67edf35d", "base_bdev": "Malloc2", "free_clusters": 8190, "cluster_size": 8192, "total_data_clusters": 8190, "block_size": 4096, <<<<<< "name": "lvs" }

Sure, here we go:

sudo ./scripts/rpc.py bdev_malloc_create -b hNVMe0n1 1024 512
hNVMe0n1

sudo ./scripts/rpc.py bdev_get_bdevs
[
  {
    "name": "hNVMe0n1",
    "aliases": [
      "79a132a2-9f05-47d1-97ac-ccbe85235f8a"
    ],
    "product_name": "Malloc disk",
    "block_size": 512,
    "num_blocks": 2097152,
    "uuid": "79a132a2-9f05-47d1-97ac-ccbe85235f8a",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {}
  }
]


sudo ./scripts/rpc.py bdev_lvol_create_lvstore hNVMe0n1 glvs -c 512
request:
{
  "bdev_name": "hNVMe0n1",
  "lvs_name": "glvs",
  "cluster_sz": 512,
  "method": "bdev_lvol_create_lvstore",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid argument"
}


I've tried also with 4096:
sudo ./scripts/rpc.py bdev_lvol_create_lvstore hNVMe0n1 glvs -c 4096
request:
{
  "bdev_name": "hNVMe0n1",
  "lvs_name": "glvs",
  "cluster_sz": 4096,
  "method": "bdev_lvol_create_lvstore",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Cannot allocate memory"
}

**Comment by Comphix** [comment]
Sorry to bring the confusion, looks like Logical Volume store could not specify the blocksize.

-c parameter is for the cluster size which is a different from the block size

**Comment by TheSSDGuy** [comment]
I've tried with this:

sudo ./scripts/rpc.py bdev_lvol_create_lvstore hNVMe0n1 glvs -c **8192**
3b8985f2-2879-4f98-a22b-a77222e7990b

**this command lets me build the logical volume store bdev (512 is not supported and with 4096 there are too many metadata pages)**

sudo ./scripts/rpc.py bdev_lvol_get_lvstores
[
  {
    "uuid": "3b8985f2-2879-4f98-a22b-a77222e7990b",
    "name": "glvs",
    "base_bdev": "hNVMe0n1",
    "total_data_clusters": 65528,
    "free_clusters": 65528,
    "block_size": 512,
    "cluster_size": 8192
  }
]

then I went thru the same command to build the logical volume and the nbd device.
**Same result, mkfs.ext4 crashes**

**Comment by Comphix** [comment]
By the way, could you also try to create the nbd device directly on the Malloc Bdev with 512 blocksize?

This is try to narrow down the problem and not involve Logical Volume here.

**Comment by TheSSDGuy** [comment]
> By the way, could you also try to create the nbd device directly on the Malloc Bdev with 512 blocksize?
> 
> This is try to narrow down the problem and not involve Logical Volume here.

Sure, here we go:

sudo ./scripts/rpc.py bdev_malloc_create -b hNVMe0n1 1024 512
hNVMe0n1

sudo ./scripts/rpc.py nbd_start_disk hNVMe0n1 /dev/nbd0
/dev/nbd0

sudo ./scripts/rpc.py bdev_get_bdevs
[
  {
    "name": "hNVMe0n1",
    "aliases": [
      "e5ccd452-9887-4205-8f53-93a064fd75a8"
    ],
    "product_name": "Malloc disk",
    "block_size": 512,
    "num_blocks": 2097152,
    "uuid": "e5ccd452-9887-4205-8f53-93a064fd75a8",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {}
  }
]

**Worked like a charm**
![image](https://user-images.githubusercontent.com/46682946/168013002-b6cff506-d0d6-4659-8c42-b8c2c7c715d8.png)

**Comment by Comphix** [comment]
To further confirm this:

Create a Malloc with 4096 blocksize and create NBD bdev on it, let's see whether it is ok or not

And for the Logical Volume, it depends on SPDK Blobstore whose Pagesize is set to 4096 and not sure whether this is relating to the usage of Logical Volume as NBD underlying device.

**Comment by TheSSDGuy** [comment]
Sure:

sudo ./scripts/rpc.py bdev_malloc_create -b hNVMe0n1 1024 4096
hNVMe0n1

sudo ./scripts/rpc.py bdev_get_bdevs
[
  {
    "name": "hNVMe0n1",
    "aliases": [
      "e27afc94-e203-4563-b335-876223382fec"
    ],
    "product_name": "Malloc disk",
    "block_size": 4096,
    "num_blocks": 262144,
    "uuid": "e27afc94-e203-4563-b335-876223382fec",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {}
  }
]

sudo ./scripts/rpc.py nbd_start_disk hNVMe0n1 /dev/nbd0
/dev/nbd0

**Worked as expected**
![image](https://user-images.githubusercontent.com/46682946/168016470-5231e1bc-f493-4dce-8aa0-686b52395846.png)

**Note**
Disk /dev/nbd0: 1 GiB, 1073741824 bytes, 262144 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

**Comment by TheSSDGuy** [comment]
> So that it looks like have no relationship with the blocksize.
> 
> May relate to the Logical Volume itself.
> 
> Any error logs are shown when using the Logical Volume?

Here's the results:

sudo ./scripts/rpc.py log_set_flag nbd
sudo ./scripts/rpc.py log_set_flag vbdev_lvol

sudo ./scripts/rpc.py nbd_start_disk glvs/p0 /dev/nbd0
[2022-05-12 13:22:14.619615] nbd.c:1148:spdk_nbd_start: *INFO*: Enabling kernel access to bdev glvs/p0 via /dev/nbd0

When I try to format the nbd drive with mkfs.ext4 this is what I get on SPDK back-end

[2022-05-12 13:22:38.374387] vbdev_lvol.c: 902:vbdev_lvol_submit_request: *INFO*: lvol: unsupported I/O type 4
[2022-05-12 13:22:38.781109] vbdev_lvol.c: 902:vbdev_lvol_submit_request: *INFO*: lvol: unsupported I/O type 4

**Comment by TheSSDGuy** [comment]
OK digging into the code I've found that in file "vbdev_lvol.c" at line 902 (where the error happens) I/O 4, i.e., SPDK_BDEV_IO_TYPE_FLUSH is not supported!

I've tryed this crazy thing just to see what happens:

`case SPDK_BDEV_IO_TYPE_FLUSH: //crazy hack`
`case SPDK_BDEV_IO_TYPE_UNMAP:`
`lvol_unmap(lvol, ch, bdev_io);`
`break;`

basically FLUSH command goes in fall-thru with UNMAP (I strongly believe this is not correct), anyhow thanks to this I can format the drive in ext4.

Clearly as soon as I try to mount it everything crashes 😄 
![image](https://user-images.githubusercontent.com/46682946/168080544-197f4004-9cce-4db2-b5b1-7937807bbcc2.png)

Question now is, why lvol bdev does not support flush?

**Comment by jimharris** [comment]
> On the other hand, if I add another case like this (see the "crazy hack" comments):
> 
> ```
> 	case SPDK_BDEV_IO_TYPE_FLUSH: //crazy hack
> 		spdk_bdev_io_complete(bdev_io, SPDK_BDEV_IO_STATUS_SUCCESS); //crazy hack
> 		break;
> ```

This isn't a completely crazy hack.  It actually is fine if using an NVMe SSD w/o a VWC as the lvol backing store (which is the norm).

There are a few changes needed:

1) bdev nvme module needs to only report FLUSH support if there is a VWC present
2) bdev nvme module needs to translate FLUSH to an spdk_nvme_ns_cmd_flush() call (which flushes the whole namespace - it is not range-based)
3) blob bdev shim needs to disallow creation of a blob store on any device that says it supports flush - flush indicates lack of atomicity, which doesn't work with blobstore
4) lib/nbd needs to check if underlying bdev supports FLUSH before calling spdk_bdev_flush_blocks()

**Comment by Comphix** [comment]
Hi Jim,

For this
```
bdev nvme module needs to only report FLUSH support if there is a VWC present
```

If the NVMe SSD w/ VWC, then it means to do this Flush operation (translate to spdk_nvme_ns_cmd_flush).
If the NVMe SSD w/o VWC, then it means this Flush operation is a No-Op and we could return and complete the IO directly.

In both cases, the NVMe bdev module could support the Flush operation. Is this right?

Or in the case of w/o VWC, the NVMe bdev module just reports it does not support flush and fail the higher layer flush IOs? This may potentially cause the upper layer stack IO failure on flush request like in this issue. If we just return and complete the IO in the case of w/o VWC, it looks like fine.

**Comment by dong-liuliu** [comment]
This is probably same with the issue we met when do mkfs.ext4 on lvol backed nbd device.
It is because SPDK NBD module will set NBD flush/trim flag but doesn't base on backend bdev capability.
lvol bdev doesn't support flush, but kernel expect related nbd support flush. Then error occurs.

**Comment by dong-liuliu** [comment]
XInrui already raised a patch to fix this problem.
@TheSSDGuy  Can you retry this case with this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/14099

**Comment by jimharris** [comment]
Closing.  If you still see this problem after the #14099 fix, please reopen this issue or create a new one.
