### ISSUE TITLE
[vfio_user_fio] VM boot timeout

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2509]
# CI Intermittent Failure

00:04:10.701  ========== Backtrace start: ==========
00:04:10.701  
00:04:10.701  in /var/jenkins/workspace/vfio-user-autotest/spdk/test/vfio_user/common.sh:9 -> clean_vfio_user([""],["49"])
00:04:10.701       ...
00:04:10.701     4   	# Verify vfio-user support of qemu.
00:04:10.701     5   	QEMU_BIN="/usr/local/qemu/vfio-user-v0.93/bin/qemu-system-x86_64"
00:04:10.701     6   	
00:04:10.701     7   	function clean_vfio_user() {
00:04:10.701     8   		trap - ERR
00:04:10.701  => 9   		print_backtrace
00:04:10.701     10  		set +e
00:04:10.701     11  		error "Error on $1 $2"
00:04:10.701     12  		vm_kill_all
00:04:10.701     13  		vhost_kill 0
00:04:10.701     14  		exit 1
00:04:10.701       ...
00:04:10.701  in /var/jenkins/workspace/vfio-user-autotest/spdk/test/vfio_user/vfio_user_fio/vfio_user_fio.sh:49 -> main([])
00:04:10.701       ...
00:04:10.701     44  		vm_setup --disk-type=vfio_user --force=$i --os=$VM_IMAGE --disks="$i"
00:04:10.701     45  		used_vms+=" $i"
00:04:10.701     46  	done
00:04:10.701     47  	
00:04:10.701     48  	vm_run $used_vms
00:04:10.701  => 49  	vm_wait_for_boot 60 $used_vms
00:04:10.702     50  	
00:04:10.702     51  	timing_exit launch_vms
00:04:10.702     52  	
00:04:10.702     53  	timing_enter run_vm_cmd
00:04:10.702     54  	
00:04:10.702       ...
00:04:10.702  
00:04:10.702  ========== Backtrace end ==========

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_77128.html

## Execution failed at

Please see above

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_77128.html

**Comment by shuhei-matsumoto** [comment]
Maybe this is as same as #2372

**Comment by changpe1** [comment]
> Maybe this is as same as #2372

I don't see kernel panic when staring VM for this one, but I I see that the NVMe device is online, both of them failed after NVMe is online, still not sure they are related or not.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_77560.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_77561.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_77618.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_77653.html

**Comment by shuhei-matsumoto** [comment]
this is duplicated with #2392
