### ISSUE TITLE
[clang-vg-autotest] Package 'jbp_....tar.gz' not exists after creation

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2510]
# CI Intermittent Failure
[iscsi-uring-vg-autotest] is also.
```
00:00:09.081  Saving response body to /var/jenkins/workspace/clang-vg-autotest/jbp_bc4227c11ffa7f200060bb31032f9ef2f4732486.tar.gz
00:00:09.091  [Pipeline] sh
00:00:09.373  + rm -f jbp_bc4227c11ffa7f200060bb31032f9ef2f4732486.tar.gz
00:00:09.384  [Pipeline] error
00:00:09.388  [Pipeline] }
00:00:09.405  [Pipeline] // stage
00:00:09.411  [Pipeline] }
00:00:09.427  [Pipeline] // node
00:00:09.440  [Pipeline] End of Pipeline
00:00:09.452  ERROR: Package 'jbp_bc4227c11ffa7f200060bb31032f9ef2f4732486.tar.gz' not exists after creation
00:00:09.457  Finished: FAILURE
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/77223/archive/clang-vg-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/77223/archive/iscsi-uring-vg-autotest/build.log

## Execution failed at

```
00:00:08.658  + rm -f jbp_bc4227c11ffa7f200060bb31032f9ef2f4732486.tar.gz
00:00:08.673  [Pipeline] error
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_77223.html

**Comment by xjjx** [comment]
This is problem with internal DNS. We'll try to add some workaround for this.
`00:00:09.080  Treating UnknownHostException(sorcerer.igk.intel.com) as 404 Not Found
`

**Comment by xjjx** [comment]
There are no more occurrences of this issue.
Seems that this was only temporary network problem.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80183.html

**Comment by ksztyber** [comment]
[Bug scrub] Since there are workarounds in place, closing until it happens again.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_82080.html
