### ISSUE TITLE
Disable messages:  EAL: Unexpected size 0 of DMA remapping cleared instead of X

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2512]
# Bug report

During exiting from SPDK app (e.g. spdk_tgt) DPDK produces a lot of following messages:
```
EAL: Unexpected size 0 of DMA remapping cleared instead of 2097152
```

In some cases I get even over 2000 lines of this output, which makes it hard to inspect any application or tests output.
Could we please disable this?

## Steps to Reproduce
N/A

**Comment by changpe1** [comment]
This is related with DPDK dynamic memory management with vfio, it doesn't affect anything.

**Comment by karlatec** [comment]
Functionally - no. But it does affect the output on the screen. It's pretty inconvenient to need to scroll 2k lines up every time you need to check the output.

**Comment by jimharris** [comment]
@changpe1 @karlatec Isn't this same issue as #2075?

I agree with @karlatec, these logs are pretty inconvenient.  By sheer coincidence, @gaowayne filed #2511 for this same problem, just before this issue was filed.

I propose we close this issue, and continue the discussion on #2075.

**Comment by changpe1** [comment]
> @changpe1 @karlatec Isn't this same issue as #2075?
> 
> I agree with @karlatec, these logs are pretty inconvenient. By sheer coincidence, @gaowayne filed #2511 for this same problem, just before this issue was filed.
> 
> I propose we close this issue, and continue the discussion on #2075.

Yes, they're same, I already opened an issue in DPDK, there are other issues with dynamic memory model in DPDK, not just this one, this one doesn't affect the functional feature.

**Comment by jimharris** [comment]
> Yes, they're same, I already opened an issue in DPDK, there are other issues with dynamic memory model in DPDK, not just this one, this one doesn't affect the functional feature.

Thanks @changpe1.  I see Anatoly hasn't responded to last post on the DPDK bug tracker.  Could you ping him again on this?  Or if this doesn't affect functionality, maybe we just do a patch removing (or lowering log level) on this message for now, and then post that patch to dpdk-dev mailing list.

**Comment by changpe1** [comment]
> > Yes, they're same, I already opened an issue in DPDK, there are other issues with dynamic memory model in DPDK, not just this one, this one doesn't affect the functional feature.
> 
> Thanks @changpe1. I see Anatoly hasn't responded to last post on the DPDK bug tracker. Could you ping him again on this? Or if this doesn't affect functionality, maybe we just do a patch removing (or lowering log level) on this message for now, and then post that patch to dpdk-dev mailing list.

Yeah, let me follow up this one.

**Comment by changpe1** [comment]
I asked Anatoly to update the status of this issue, and provided a fix patch https://review.spdk.io/gerrit/c/spdk/dpdk/+/12706 here.

**Comment by karlatec** [comment]
Closing the issue as duplicate of #2075

**Comment by pppcn** [comment]
Have this issue been fixed? However,,it appears that I encounter the same issue on the latest version of spdk when running multiple jobs testing.
Here is the fio script:

```
[global]
ioengine=/home/bpan/BergCentos/tools/spdk/spdk_latest_240708/spdk/build/fio/spdk_nvme
bs=128k
thread=1
direct=1
#time_based
group_reporting
#runtime=1h
rw=write
zonemode=zbd
zonesize=1073741824
#initial_zone_reset=1
iodepth=1

[test]
numjobs=16
filename=trtype=PCIe traddr=2f.00.0 ns=1
offset=0z
offset_increment=1z
size=10z
```
