### ISSUE TITLE
Running with num_io_queues:16  parameter via bdev_nvme_attach_controller only uses a single queue 

### ISSUE THREAD

**Issue by sekar-wdc** [spdk/spdk#2513]
# Bug report

When running with bdev_nvme_attach_controller parameter num_io_queues of 16, number of I/O queues actually connected/used during I/O is 1. 

## Expected Behavior

The initiator should connect with 16 I/O queues to the target. 

## Current Behavior

Only 1 I/O queue is observed when running 

## Steps to Reproduce
Using bdev conf file below:

[root@perf-16-9 spdk]# more /root/fio_1_bdev.conf
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "log_set_flag",
          "params": { "flag": "all" }
        },
        {
          "method": "log_set_level",
          "params": { "level": "DEBUG" }
        },
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "name": "Nvme0",
            "trtype": "tcp",
            "traddr": "10.10.10.39",
            "trsvcid": "4420",
            "subnqn": "nqn.2015-09.com.wdc:nvme.1",
            "adrfam": "IPv4",
            "num_io_queues": 16
          }
        }
      ]
    }
  ]
}

Running with fio job file:

[global]
ioengine=spdk_bdev
spdk_conf=/root/fio_1_bdev.conf
direct=1
randrepeat=0
group_reporting=1
time_based=1
norandommap=1
runtime=1m
size=100%
blocksize=128KB
numjobs=1
iodepth=64
rw=write
thread=1

[job0]
filename=Nvme0n1

## Context (Environment including OS version, SPDK version, etc.)

SPDK 22.01, CentOS Stream 8, 5.15.21-200.el7.x86_64

**Comment by Comphix** [comment]
I think below is to create 16 IO queues for this NVMe ctrlr
```
"method": "bdev_nvme_attach_controller",
"params": {
"name": "Nvme0",
"trtype": "tcp",
"traddr": "10.10.10.39",
"trsvcid": "4420",
"subnqn": "nqn.2015-09.com.wdc:nvme.1",
"adrfam": "IPv4",
"num_io_queues": 16
```

While in the case that FIO is running with numjobs = 1, it means to use only 1 IO queue. You could try numjobs = 2, 4 to check there will be corresponding number of IO queues used by FIO.

**Comment by AlekseyMarchuk** [comment]
@sekar-wdc  the "num_io_queues" parameter determines the maximum number of IO queues to be used by NVME controller (SPDK_NVME_FEAT_NUMBER_OF_QUEUES request). As @Comphix mentioned, to create a real qpair, you need to increase numjobs fio parameter since SPDK fio plugin creates a qpair per job

**Comment by jimharris** [comment]
> @AlekseyMarchuk Our target is an NVMEoF target. With nvme cli we are able to connect to a drive with more than 1 queue and run a single job fio. Is there a way to use multiple queues without using multiple jobs ? I thought the new "num_io_queues" parameter for bdev_nvme_attach_controller would be per drive based on the release notes:
> 
> An new parameter num_io_queues is added to bdev_nvme_attach_controller RPC to allow specifying amount of requested IO queues.

@AlekseyMarchuk is correct.  This only defines the value we specify for the NUMBER_OF_QUEUES NVMe feature.

The Linux kernel automatically allocates all queues when the controller is initialized, and associates them with CPU cores.  But SPDK defers allocation until the queues are required.  So if the fio job file only has one job and is using the spdk fio plugin, then that will only create one spdk_thread (even if we told the controller that we may use up to 'num_io_queues').  The SPDK bdev name module only allocates one NVMe qpair per spdk_thread.

Note that if the fio job has only one job and it is using a Linux-kernel based ioengine, it doesn't mean that all of those queues are used for sending I/O.  Only the queue assigned to the CPU core that is running the fio job will be used for submitting I/O.  With SPDK, the queue is associated with the lightweight spdk_thread construct, not the CPU core.

**Comment by changpe1** [comment]
we don't treat this as an issue, closing it now.
