### ISSUE TITLE
spdk_thread_exit timeout due to nvmf_tcp_qpair_handle_timeout poller still registered after spdk target is destroyed

### ISSUE THREAD

**Issue by pvonti** [spdk/spdk#2527]
# Bug report

With IOs on nvme disks did a process restart which results in spdk shutdown. During SPDK shutdown see all requests on the qpair are completed, qpair is destroyed, poll group removed, subsystem stopped and SPDK target is destroyed. 

But see spdk_thread exit timeout because of  nvmf_tcp_qpair_handle_timeout poller is still registered on the spdk thread after SPDK target destroy.

`17511 2022-05-22,20:21:39.218268-06 ERROR: nvmeof.spdk:thread_exit: ln:526 thread nvmeof_thr_1 got timeout, and move it to the exited state forcefully  

`17490 2022-05-22,20:21:39.221408-06 WARN: nvmeof.spdk:_free_thread: ln:376 timed_poller nvmf_tcp_qpair_handle_timeout still registered at thread exit `

## Expected Behavior

After all subsystems are stopped and SPDK target is destroyed, all the SPDK threads should exit without timeout.

## Current Behavior

After subsystems are stopped and spdk target is destroyed, spdk thread exit times out because of nvmf_tcp_qpair_handle_timeout poller still registered on the spdk thread.

// Qpair disconnect sets qpair state to DEACTIVATING. This message was added for debugging
`17524 2022-05-22,20:21:34.215179-06 NOTE: nvmeof.spdk:spdk_nvmf_qpair_disconnect: ln:1135 Qpair state DEACTIVATING. Abort pending reqs. qpair:0xdea59c00 qpair_id:1 spdk_thread:nvmeof_thr_1`

// nvmf_qpair_abort_zcopy_pending _reqs() completes requests in NVMF_ZCOPY_PHASE_EXECUTE state. 
// This message was added for debugging
`17524 2022-05-22,20:21:34.215214-06 NOTE: nvmeof.spdk:nvmf_qpair_abort_pending_zcopy_reqs: ln:2957 nvmf_transport_req_free for req:0xc8e525a0 zcopy_phase:2 qpair:0xdea59c00 qpair_id:1 [[NVMF_ZCOPY_PHASE_EXECUTE=2]]`

// Requests in NVMF_ZCOPY_PHASE_EXECUTE state in TCP_REQUEST_STATE_TRANSFERRING_HOST_TO_CONTROLLER=5 state
// with data out from host. This message was added for debugging
`17524 2022-05-22,20:21:34.215220-06 NOTE: nvmeof.spdk:nvmf_tcp_request_free: ln:542 tcp_req=0xc8e525a0 req:0xc8e525a0 ttag:32897 qpair.qid:1 **state:5** zcopy_phase:2 will be freed `

// Target gets host to controller data PDU and does not find a request in TRANSFERRING_HOST_TO_CONTROLLER or AWAITING_R2T_ACK states
```
17524 2022-05-22,20:21:34.215285-06 ERROR: nvmeof.spdk:nvmf_tcp_h2c_data_hdr_handle: ln:1777 tcp_req in TRANSFERRING_HOST_TO_CONTROLLER state not found for pdu=0xc8dd21a0 tqpair=0xdea59c00
17524 2022-05-22,20:21:34.215289-06 ERROR: nvmeof.spdk:nvmf_tcp_h2c_data_hdr_handle: ln:1784 tcp_req in AWAITING_R2T_ACK not found for pdu=0xc8dd21a0 tqpair=0xdea59c00
```

//  Target terminates the request and on completion registers timeout_poller with the spdk thread
// These logs were added for debugging
```
17524 2022-05-22,20:21:34.215297-06 ERROR: nvmeof.spdk:nvmf_tcp_send_c2h_term_req: ln:1626 Terminate tcp_req:(nil) req:(nil) pdu:0xc8dd21a0 tqpair:0xdea59c00 qid:1
17524 2022-05-22,20:21:34.215307-06 ERROR: nvmeof.spdk:nvmf_tcp_send_c2h_term_req_complete: ln:1607 Registering nvmf_tcp_qpair_handle_timeout() for tqpair:0xdea59c00 qid:1 with tmo:30
```

// All requests in qpair are completed, outstanding queue is empty. qpair is destroyed WITHOUT unregistering the timeout_poller. This log was added for debugging
`17512 2022-05-22,20:21:34.215498-06 NOTE: nvmeof.spdk:nvmf_qpair_request_cleanup: ln:4052 Empty Qpair->outstanding. call _nvmf_qpair_destroy() cb. qpair:0xdea59c00 qpair_id:1 spdk_thread:nvmeof_thr_1`

// Poll group is removed and spdk target is destroyed. This log was added for debugging
`17512 2022-05-22,20:21:34.215503-06 NOTE: nvmeof.spdk:spdk_nvmf_poll_group_remove: ln:1013 Removing qpair from tgroup. qpair:0xdea59c00 qpair_id:1 tgroup:0xe2fe60ACTIVE. Complete req. tcp_req:0xc8e65000`

// SPDK thread exit timesout and is exited forcefully
`17511 2022-05-22,20:21:39.218268-06 ERROR: nvmeof.spdk:thread_exit: ln:526 thread nvmeof_thr_1 got timeout, and move it to the exited state forcefully`

// nvmf_tcp_qpair_handle_timeout poller is still registered when spdk_thread is freed
`17490 2022-05-22,20:21:39.221408-06 WARN: nvmeof.spdk:_free_thread: ln:376 timed_poller nvmf_tcp_qpair_handle_timeout still registered at thread exitregistered at thread exit`

## Possible Solution
In nvmf_tcp_send_c2h_term_req_complete(), dont register the nvmf_tcp_qpair_handle_timeout() poller if the qpair is in SPDK_NVMF_QPAIR_DEACTIVATING or SPDK_NVMF_QPAIR_ERROR state. If qpair is in DEACTIVATING or ERROR state, qpair is already being disconnected, so timeout_poller need not be registered.

Heres the diff of the proposed solution

```
@@ -1598,12 +1600,18 @@ nvmf_tcp_send_c2h_term_req_complete(void *cb_arg)
 {
        struct spdk_nvmf_tcp_qpair *tqpair = (struct spdk_nvmf_tcp_qpair *)cb_arg;

-    SPDK_ERRLOG("Registering nvmf_tcp_qpair_handle_timeout() for tqpair:%p qid:%d with tmo:%d\n", tqpair,
-        tqpair->qpair.qid, SPDK_NVME_TCP_QPAIR_EXIT_TIMEOUT);
+       if (tqpair && !tqpair->timeout_poller) {
+        if (!(tqpair->qpair.state == SPDK_NVMF_QPAIR_DEACTIVATING) &&
+               !(tqpair->qpair.state == SPDK_NVMF_QPAIR_ERROR)) {
+            /* If QPAIR is in DEACTIVATING or ERROR states, qpair is already being disconnected.
+             * Dont register timeout_poller in that case.
+             */
+            SPDK_ERRLOG("Registering nvmf_tcp_qpair_handle_timeout() for exit tqpair:%p qid:%d within tmo:%dsecs\n",
+                tqpair, tqpair->qpair.qid, SPDK_NVME_TCP_QPAIR_EXIT_TIMEOUT);

-       if (!tqpair->timeout_poller) {
-               tqpair->timeout_poller = SPDK_POLLER_REGISTER(nvmf_tcp_qpair_handle_timeout, tqpair,
+                   tqpair->timeout_poller = SPDK_POLLER_REGISTER(nvmf_tcp_qpair_handle_timeout, tqpair,
                                         SPDK_NVME_TCP_QPAIR_EXIT_TIMEOUT * 1000000);
+        }
        }
 }
```

## Steps to Reproduce
1. Create a subsystem and export 1 volume to a linux host.
2. Connect to the subsystem with 1 IO queue pair.
nvme connect -t tcp -a  <data IP> -n <subsystem_nqn> -q <host_nqn> -s4420 --nr-io-queues=1
3. Issue Write IOs to the nvme disk using your IO tool with 8 outstanding IOs.
4. Restart the target application for 10-15 iterations

Target application restart triggers SPDK shutdown, qpair disconnect and abort of IOs. Issue seen when IO in NVMF_ZCOPY_PHASE_EXECUTE and TCP_REQUEST_STATE_TRANSFERRING_HOST_TO_CONTROLLER state is completed.

## Context (Environment including OS version, SPDK version, etc.)
SPDK version 22.01 with patches  
[nvmf/tcp: delay completion for zcopy reqs w/ in-progress writes](https://review.spdk.io/gerrit/c/spdk/spdk/+/12255/3)
(Merged)
[nvmf/tcp: update pdu_in_use flag in write functions](https://review.spdk.io/gerrit/c/spdk/spdk/+/12254/2)
(Merged)
[nvmf/tcp: use different callbacks for sending mgmt/req PDUs](https://review.spdk.io/gerrit/c/spdk/spdk/+/12253/2)
(Merged)
[v22.01.x: nvmf/tcp: delay qpair destruction](https://review.spdk.io/gerrit/c/spdk/spdk/+/12487)

**Comment by jimharris** [comment]
> ## Steps to Reproduce
> Issue was reproduced by
> 
> 1. nvme connect with one IO queue pair
> 2. Write IOs on nvme disk
> 3. Process restart - 20 times

Hi @pvonti,

Please provide a specific set of reproduction steps.

Thanks,

-Jim

**Comment by pvonti** [comment]
@jimharris, @konrad the issue was seen when restarting our module process which causes spdk target destroy and spdk_thread exit

**Comment by pvonti** [comment]
Hi @jimharris, @ksztyber,

I have updated the Steps to Reproduce and Possible Solution sections of the Bug Report, please let me know if you need any more details

**Comment by ksztyber** [comment]
Hi @pvonti, your solution seems fine and should fix this problem, but I think there are other cases when this can happen, so I think it's better to unregister the poller in `qpair_fini`. Could you check if this patch also works on your side: https://review.spdk.io/gerrit/c/spdk/spdk/+/12844

**Comment by ksztyber** [comment]
Thanks for the confirmation @pvonti.

**Comment by pvonti** [comment]
Hi @ksztyber, ran the test in "Steps To Reproduce" with 10 volumes, 4 qpairs, 8 outstanding reads and writes. 

I am seeing a segmentation fault when thread_poll() calls thread_execute_timed_poller() and qpair_handle_timeout poller gets unregistered from qpair disconnect/qpair destroy path.

Here are the steps which causes the segfault
1. Write tcp_request with data outstanding from host is aborted and freed during qpair disconnect 
shutdown_spdk -> spdk_nvmf_subsystem_stop() -> subsystem_state_change_on_pg() -> nvmf_poll_group_remove_subsystem() -> nvmf_poll_group_remove_subsystem_msg() -> spdk_nvmf_qpair_disconnect() -> nvmf_qpair_abort_pending_zcopy_reqs() 

2.  Host sends data, nvmf_tcp_h2c_data_hdr_handle() does not find a tcp_request in TCP_REQUEST_STATE_TRANSFERRING_HOST_TO_CONTROLLER or TCP_REQUEST_STATE_AWAITING_R2T_ACK and sends c2h terminate request.

3. nvmf_tcp_send_c2h_term_req_complete()  registers nvmf_tcp_qpair_handle_timeout() 

4.  Poller is still running, thread_poll() calls thread_execute_timed_poller() 

5. Qpair disconnect unregisters qpair_handle_timeout pollerand destroys the qpair. 

6. thread_execute_timed_poller() hits a segfault at thread.c line 872, with qpair_handle_timeout poller removed.

static inline int
thread_execute_timed_poller(struct spdk_thread *thread, struct spdk_poller *poller,
                uint64_t now)
850 static inline int
851 thread_execute_timed_poller(struct spdk_thread *thread, struct spdk_poller *poller,
852                 uint64_t now)
853 {
854     int rc;
855
856     switch (poller->state) {
857     case SPDK_POLLER_STATE_UNREGISTERED:
858         free(poller);
859         return 0;
860     case SPDK_POLLER_STATE_PAUSING:
861         TAILQ_INSERT_TAIL(&thread->paused_pollers, poller, tailq);
862         poller->state = SPDK_POLLER_STATE_PAUSED;
863         return 0;
864     case SPDK_POLLER_STATE_WAITING:
865         break;
866     default:
867         assert(false);
868         break;
869     }
870
871     poller->state = SPDK_POLLER_STATE_RUNNING;
872     rc = poller->fn(poller->arg);   <====== Seg fault poller->fn ==NULL
873
874     poller->run_count++;
875     if (rc > 0) {
876         poller->busy_count++;
877     }
878     …..
                }
