### ISSUE TITLE
vfio-user-blk(vfu target) does has the same limitatiion as vhost-user-blk?

### ISSUE THREAD

**Issue by Apokleos** [spdk/spdk#2529]
# Bug report
Hi @changpe1

I am now testing the unreleased vfu-target(vfio-user-blk), and comparison test with vhost-user-blk. 

I have many tests with backend media: NVMe SSD(split bdev with SSD) or SATA HDD(raw block with aio). In my test, I will try to keep other factors same. And I have a similar result:
(1) The IOPS of vfu-target is very close to vhu-target's.
(2) There is little difference in IOPS when VM works with 1/4/8 queuesm, no matter vfu-target or vhu-target.
(3) No matter how many cores assigned to the vfu endpoint, the IOPS of VM with FIO has no change.

As I know, a virtio blk device, no matter how many rings it has, all IO queues are processed in the same core context(will be processed in one vhost thread).
What's about vfu target? Is vfu-target also has the same design?

Thx.

**Comment by changpe1** [comment]
@Apokleos thanks for testing vfu_target, for the thread modeling in vfu_target, it's same with vhost target, so the performance number should be almost same, I start one poller to poll all the vrings.

Do you see other benefits to span vrings to different cores? we can get better performance number with 1 VM test case, but this add extra limitations if we support many VMs, because different vrings which belong to different VMs may run in the same core.

**Comment by Apokleos** [comment]
Thx. @changpe1

> @Apokleos thanks for testing vfu_target, for the thread modeling in vfu_target, it's same with vhost target, so the performance number should be almost same, I start one poller to poll all the vrings.
>
OK, I see. Same as what I observed with rpc client cli `framework_get_reactors` . If so, what is the advantage of vfu-target over vhu-target?
> Do you see other benefits to span vrings to different cores? we can get better performance number with 1 VM test case, but this add extra limitations if we support many VMs, because different vrings which belong to different VMs may run in the same core.
>
 I refer to your [topic page18-19](https://static.sched.com/hosted_files/kvmforum2021/f8/Changpeng%20Liu%26Ben%20Walker_High%20Performance%20NVMe%20Virtualization%20with%20SPDK%20and%20vfio-user.pdf) in KVM forum 2021.
I found that,  for NVMf/VFIOUSER multiple IO queues, submission queues can be processed in different core context, so I want to make sure that whether vfu-target is designed  so.

**Comment by changpe1** [comment]
> Thx. @changpe1
> 
> > @Apokleos thanks for testing vfu_target, for the thread modeling in vfu_target, it's same with vhost target, so the performance number should be almost same, I start one poller to poll all the vrings.
> 
> OK, I see. Same as what I observed with rpc client cli `framework_get_reactors` . If so, what is the advantage of vfu-target over vhu-target?
> 
One benefit is the thin driver layer in hypervisor side, hypervisor can just use one driver to connect to different emulated devices, e.g: nvme virtio-blk virtio-scsi. This is important for cloud hypervisor.

> > Do you see other benefits to span vrings to different cores? we can get better performance number with 1 VM test case, but this add extra limitations if we support many VMs, because different vrings which belong to different VMs may run in the same core.
> 
> I refer to your [topic page18-19](https://static.sched.com/hosted_files/kvmforum2021/f8/Changpeng%20Liu%26Ben%20Walker_High%20Performance%20NVMe%20Virtualization%20with%20SPDK%20and%20vfio-user.pdf) in KVM forum 2021. I found that, for NVMf/VFIOUSER multiple IO queues, submission queues can be processed in different core context, so I want to make sure that whether vfu-target is designed so.

I leave this thread modeling implementation in the device layer, e.g: users may add the support to span vrings to different cores very easily, I just provide the default thread modeling in existing version.

**Comment by Apokleos** [comment]
> > Thx. @changpe1
> > > @Apokleos thanks for testing vfu_target, for the thread modeling in vfu_target, it's same with vhost target, so the performance number should be almost same, I start one poller to poll all the vrings.
> > 
> > 
> > OK, I see. Same as what I observed with rpc client cli `framework_get_reactors` . If so, what is the advantage of vfu-target over vhu-target?
> 
> One benefit is the thin driver layer in hypervisor side, hypervisor can just use one driver to connect to different emulated devices, e.g: nvme virtio-blk virtio-scsi. This is important for cloud hypervisor.
> 
Yeah, we will do benefit from it, eliminating devices' "Qemu Zoo". 
> > > Do you see other benefits to span vrings to different cores? we can get better performance number with 1 VM test case, but this add extra limitations if we support many VMs, because different vrings which belong to different VMs may run in the same core.
> > 
> > 
> > I refer to your [topic page18-19](https://static.sched.com/hosted_files/kvmforum2021/f8/Changpeng%20Liu%26Ben%20Walker_High%20Performance%20NVMe%20Virtualization%20with%20SPDK%20and%20vfio-user.pdf) in KVM forum 2021. I found that, for NVMf/VFIOUSER multiple IO queues, submission queues can be processed in different core context, so I want to make sure that whether vfu-target is designed so.
> 
> I leave this thread modeling implementation in the device layer, e.g: users may add the support to span vrings to different cores very easily, I just provide the default thread modeling in existing version.
>
If so, it will add extra limitations in many VMs scenarios? As you said yesterday, "...different vrings which belong to different VMs may run in the same core."

**Comment by changpe1** [comment]
> > > Thx. @changpe1
> > > > @Apokleos thanks for testing vfu_target, for the thread modeling in vfu_target, it's same with vhost target, so the performance number should be almost same, I start one poller to poll all the vrings.
> > > 
> > > 
> > > OK, I see. Same as what I observed with rpc client cli `framework_get_reactors` . If so, what is the advantage of vfu-target over vhu-target?
> > 
> > 
> > One benefit is the thin driver layer in hypervisor side, hypervisor can just use one driver to connect to different emulated devices, e.g: nvme virtio-blk virtio-scsi. This is important for cloud hypervisor.
> 
> Yeah, we will do benefit from it, eliminating devices' "Qemu Zoo".
> 
> > > > Do you see other benefits to span vrings to different cores? we can get better performance number with 1 VM test case, but this add extra limitations if we support many VMs, because different vrings which belong to different VMs may run in the same core.
> > > 
> > > 
> > > I refer to your [topic page18-19](https://static.sched.com/hosted_files/kvmforum2021/f8/Changpeng%20Liu%26Ben%20Walker_High%20Performance%20NVMe%20Virtualization%20with%20SPDK%20and%20vfio-user.pdf) in KVM forum 2021. I found that, for NVMf/VFIOUSER multiple IO queues, submission queues can be processed in different core context, so I want to make sure that whether vfu-target is designed so.
> > 
> > 
> > I leave this thread modeling implementation in the device layer, e.g: users may add the support to span vrings to different cores very easily, I just provide the default thread modeling in existing version.
> 
> If so, it will add extra limitations in many VMs scenarios? As you said yesterday, "...different vrings which belong to different VMs may run in the same core."

Yes, it's up to users, e.g: users may want to see one VM can get line performance improvement when adding more cores.

**Comment by Apokleos** [comment]
> > > > Thx. @changpe1
> > > > > @Apokleos thanks for testing vfu_target, for the thread modeling in vfu_target, it's same with vhost target, so the performance number should be almost same, I start one poller to poll all the vrings.
> > > > 
> > > > 
> > > > OK, I see. Same as what I observed with rpc client cli `framework_get_reactors` . If so, what is the advantage of vfu-target over vhu-target?
> > > 
> > > 
> > > One benefit is the thin driver layer in hypervisor side, hypervisor can just use one driver to connect to different emulated devices, e.g: nvme virtio-blk virtio-scsi. This is important for cloud hypervisor.
> > 
> > 
> > Yeah, we will do benefit from it, eliminating devices' "Qemu Zoo".
> > > > > Do you see other benefits to span vrings to different cores? we can get better performance number with 1 VM test case, but this add extra limitations if we support many VMs, because different vrings which belong to different VMs may run in the same core.
> > > > 
> > > > 
> > > > I refer to your [topic page18-19](https://static.sched.com/hosted_files/kvmforum2021/f8/Changpeng%20Liu%26Ben%20Walker_High%20Performance%20NVMe%20Virtualization%20with%20SPDK%20and%20vfio-user.pdf) in KVM forum 2021. I found that, for NVMf/VFIOUSER multiple IO queues, submission queues can be processed in different core context, so I want to make sure that whether vfu-target is designed so.
> > > 
> > > 
> > > I leave this thread modeling implementation in the device layer, e.g: users may add the support to span vrings to different cores very easily, I just provide the default thread modeling in existing version.
> > 
> > 
> > If so, it will add extra limitations in many VMs scenarios? As you said yesterday, "...different vrings which belong to different VMs may run in the same core."
> 
> Yes, it's up to users, e.g: users may want to see one VM can get line performance improvement when adding more cores.

Got it! Waiting for the released vfu-target
Thank you very much!
