### ISSUE TITLE
nvmf initiator fails on FreeBSD due to rdma_create_event_channel() failure

### ISSUE THREAD

**Issue by stallamr** [spdk/spdk#253]
My working environment is FreeBSD initiator and Linux target. I'm working with FreeBSD master and SPDK master.

Issue: Upon running "perf" example, I see error like below

...
...
Initializing NVMe Controllers
libibverbs: Warning: couldn't open config directory '/etc/ibverbs/'.
nvme_rdma.c: 736:nvme_rdma_qpair_connect: *ERROR*: rdma_create_event_channel() failed
nvme_rdma.c:1339:nvme_rdma_ctrlr_construct: *ERROR*: failed to create admin qpair
No valid NVMe controllers or AIO devices found
Feb 28 20:47:24 rajesh perf: nvme_rdma.c: 736:nvme_rdma_qpair_connect: *ERROR*: rdma_create_event_channel() failed
Feb 28 20:47:24 rajesh perf: nvme_rdma.c:1339:nvme_rdma_ctrlr_construct: *ERROR*: failed to create admin qpair

On debugging, I realized this error stems from ibverbs_init() which is not able to find the driver. As a result, number of IB devices or IB devices list is returned as NULL in ibv_get_device_list().

The fix is to link required OFED drivers to SPDK. Like libibverbs, librdma and libmlx4 or libmlx5 or libcxgb4 depending on your RDMA hardware.

Edit file mk/spdk.common.mk and add following lines.

ifeq ($(CONFIG_RDMA), y)
ifeq ($(OS),FreeBSD)
LDFLAGS+= -libverbs -lrdmacm -lmlx4 -lpthread
endif
endif

PS: I didnot  try BSD 11, so cannot comment if nvmof works on BSD 11 or not.

**Comment by jimharris** [comment]
Hi Rajesh,

Thanks for your analysis on this!

Your issue says:

“The fix is to link required OFED drivers to SPDK. Like libibverbs, librdma and libmlx4 or libmlx5 or libcxgb4 depending on your RDMA hardware.”

Should this replace “Like” with “Link” and “librdma” with “librdmacm” instead?

“The fix is to link required OFED drivers to SPDK. Link libibverbs, librdmacm and libmlx4 or libmlx5 or libcxgb4 depending on your RDMA hardware.”

I’m guessing this is a FreeBSD thing – needing to link in mlx4/mlx5/cxgb4 explicitly – this isn’t required on Linux.

-Jim

**Comment by rajeshsai810** [comment]
Thanks Jim. That's right.

To be more precise, we only need to link respective userspace library for your device. In my case its libmlx4.

ifeq ($(CONFIG_RDMA), y)
ifeq ($(OS),FreeBSD)
LDFLAGS+=  -lmlx4 
endif
endif

That did the trick for me.

**Comment by jimharris** [comment]
Thanks Rajesh!

We’ll need to think if/how we can automate this in our build scripts.  But at least getting your FreeBSD steps documented in our public docs will be a great step forward.

Is this something you’d like to push a patch for?  If not, we’ll make sure someone takes care of it.

-Jim

**Comment by rajeshsai810** [comment]
Hi Jim,

For now, updating documentation sounds like a good idea.  If README is not the right place, let me know the right public doc.

If its ok, we can still add change in mk/spdk.common.mk and link all existing libraries under FreeBSD like libcxgb4, libmlx4 and libmlx5. However on BSD 11, I see we do not have libmlx5 yet. I donot think it will cause any harm if we include some non-existent driver.

If you agree, I can push a patch for changing some public doc and spdk.common.mk.

This will be my first commit, so bear with me if any delay caused.

**Comment by jimharris** [comment]
Hi Rajesh,

That would be great if you can push some patches.  We will definitely be patient – please reach out on the SPDK mailing list or IRC channel (#spdk on Freenode) if you run into problems.

Regarding linking in all of the existing libraries – how will you determine which libraries are available on the system?  And is it OK to link both libcxgb4 and libmlx4 into the same application?  (Maybe it is – I just don’t know the answer.)

-Jim

**Comment by dverkamp-intel** [comment]
Just for curiosity, how are you installing the OFED/ibverbs user-mode support?

Based on this page, it looks like it's not installed by default and requires rebuilding world with a non-default config flag enabled: https://wiki.freebsd.org/InfiniBand (this may be out of date, though).

Is there some easy way to install the required infiniband/verbs.h, libmlx4, etc. via ports/pkg/... or does it still require a buildworld?

**Comment by jimharris** [comment]
Hi Rajesh,

I think instead of modifying spdk.common.mk, you can just update the docs that the user should do this:

LDFLAGS=-lmlx4 make

Then the user can specify the library they are using – instead of trying to figure out which libraries might be available on the system.

Could you try this on your system to ensure that it works?

Thanks,

-Jim

**Comment by rajeshsai810** [comment]
Hi Jim,

Agreed. I plan to update README.md and make a note for FreeBSD to include necessary userspace driver for your hardware (HBA). As example, I plan to commit a Makefile change in perf example makefile (./examples/nvme/perf/Makefile).

Thanks,
Rajesh.

**Comment by rajeshsai810** [comment]
@dverkamp-intel  To my knowledge there is no pkg for OFED userspace.  And yes you need to buildworld with make option WITH_OFED=yes to have required headers installed. Also, you need this make option to build kernel.

make -j4 buildworld WITH_OFED=yes
make -j4 kernel WITH_OFED=yes

**Comment by wanqunintel** [comment]
currently we don't have the test environment for freebsd yet, we may need to set it up to test if necessary.

**Comment by jimharris** [comment]
Hi Rajesh - did you have a chance to push any patches for this issue?  I looked in GerritHub and didn't see anything but if I've missed it please send a link.

Thanks,

-Jim

**Comment by rajeshsai810** [comment]
Hi Jim,

Not yet. I plan to get this in by end of April.

Thanks,
Rajesh,

**Comment by jimharris** [comment]
No problem Rajesh. Thanks.

On Apr 19, 2018, at 5:45 PM, Sai Rajesh <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jim,

Not yet. I plan to get this in by end of April.

Thanks,
Rajesh,

**Comment by johnmeneghini** [comment]
Please see the proposed changes  to fix this problem in GerritHub patch https://review.gerrithub.io/#/c/spdk/spdk/+/409539/

**Comment by stallamr** [comment]
Fix is now submitted. Hence closing.
