### ISSUE TITLE
[bdev_nvme_set_hotplug RPC] The bdev does not reappear after sysfs remove/rescan

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2537]
# Question/Bug report

I have found out that one of our RPCs, bdev_nvme_set_hotplug -e does not work the way I think it should. In docs the description says: "Change settings of the NVMe hotplug feature. If enabled, PCIe NVMe bdevs will be automatically discovered on insertion and deleted on removal." - to my understanding, after performing a hotremove/hotplug operations via sysfs, SPDK target should behave the same way as if we physically disconnected the NVMe device.

## Expected Behavior

After running:
echo 1 > "/sys/bus/pci/devices/0000:0a:00.0/remove"
sleep 6
echo 1 > "/sys/bus/pci/rescan"

the bdev attached to 0000:0a:00.0 should reappear and be visible via bdev_get_bdevs RPC.

## Current Behavior

The bdev does not appear.

## Steps to Reproduce

1.scripts/setup.sh
2.build/bin/spdk_tgt &
3.spdk_tgt_pid=$!
4.sleep 6
5.scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:0a:00.0
6.sleep 6
7.scripts/rpc.py bdev_get_bdevs #[**_the bdev Nvme0n1 appears here_**]
8.scripts/rpc.py bdev_nvme_set_hotplug -e
9.sleep 6
10.scripts/rpc.py bdev_get_bdevs #[**_here a second bdev, HotInNvme0n1 appears_**]
11.echo 1 > "/sys/bus/pci/devices/0000:0a:00.0/remove"
12.sleep 6
13.scripts/rpc.py bdev_get_bdevs #[**_the Nvme0n1 is removed_**]
14.echo 1 > "/sys/bus/pci/rescan"
15.sleep 6
16.scripts/rpc.py bdev_get_bdevs #[**_after rescan only the HotInNvme0n1 remains_**]

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 20.04, SPDK master branch with 64df311ebaed017f869ee2158e02563a4134629f on top

Additionally, I attached logs generated with "script" program during execution of above commands.
[log.txt](https://github.com/spdk/spdk/files/8803751/log.txt)

I marked this as a question, because I am not sure if my way of testing this is correct or not.

**Comment by Comphix** [comment]
After below steps:

```
13.scripts/rpc.py bdev_get_bdevs #[the Nvme0n1 is removed]
14.echo 1 > "/sys/bus/pci/rescan"
15.sleep 6
```

We may first check whether 0000:0a:00.0 is bounded with UIO or kernel NVMe.

If NVMe, we will need to run ./scripts/setup.sh again.

Also, checked the log, the HotInNvme0n1 is bound to another SSD 0000:84:00.0 in the system. This is detected as expected when enabling the hotplug and it is also bound with UIO already.

```
0000:80:04.7 (8086 0e27): Already using the uio_pci_generic driver
0000:80:04.6 (8086 0e26): Already using the uio_pci_generic driver
0000:80:04.5 (8086 0e25): Already using the uio_pci_generic driver
0000:80:04.4 (8086 0e24): Already using the uio_pci_generic driver
0000:80:04.3 (8086 0e23): Already using the uio_pci_generic driver
0000:80:04.2 (8086 0e22): Already using the uio_pci_generic driver
0000:80:04.1 (8086 0e21): Already using the uio_pci_generic driver
0000:80:04.0 (8086 0e20): Already using the uio_pci_generic driver
**0000:84:00.0 (8086 0953): Already using the uio_pci_generic driver**
0000:00:04.7 (8086 0e27): Already using the uio_pci_generic driver
0000:00:04.6 (8086 0e26): Already using the uio_pci_generic driver
0000:00:04.5 (8086 0e25): Already using the uio_pci_generic driver
0000:00:04.4 (8086 0e24): Already using the uio_pci_generic driver
0000:00:04.3 (8086 0e23): Already using the uio_pci_generic driver
0000:00:04.2 (8086 0e22): Already using the uio_pci_generic driver
0000:00:04.1 (8086 0e21): Already using the uio_pci_generic driver
0000:00:04.0 (8086 0e20): Already using the uio_pci_generic driver
0000:0a:00.0 (8086 0953): nvme -> uio_pci_generic
```

**Comment by KKaras169169** [comment]
I inserted scripts/setup.sh between 15th and 16th commands. setup.sh reported:
`0000:0a:00.0 (8086 0953): nvme -> uio_pci_generic`

and a new bdev appeared:
```
 {
    "name": "HotInNvme1n1",
    "aliases": [
      "f44b71be-7ccc-4eaf-bfd9-2ae2c20de1da"
    ],
    "product_name": "NVMe disk",
    "block_size": 512,
    "num_blocks": 1562824368,
    "uuid": "f44b71be-7ccc-4eaf-bfd9-2ae2c20de1da",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": true,
      "nvme_io": true
    },
    "driver_specific": {
      "nvme": [
        {
          "pci_address": "0000:0a:00.0",
          "trid": {
            "trtype": "PCIe",
            "traddr": "0000:0a:00.0"
          },
          "ctrlr_data": {
            "cntlid": 0,
            "vendor_id": "0x8086",
            "model_number": "INTEL SSDPEDMW800G4",
            "serial_number": "CVCQ5380000E800EGN",
            "firmware_revision": "8EV10171",
            "oacs": {
              "security": 0,
              "format": 1,
              "firmware": 1,
              "ns_manage": 0
            },
            "multi_ctrlr": false,
            "ana_reporting": false
          },
          "vs": {
            "nvme_version": "1.0"
          },
          "ns_data": {
            "id": 1,
            "can_share": false
          }
        }
      ],
      "mp_policy": "active_passive"
    }
  }
```

Does that mean that the NVMe is not properly bound to uio_pci_generic after hotremove/hotplug?

**Comment by Comphix** [comment]
Yes, looks like the SSD is automatically bound to kernel nvme driver so that SPDK could not detect it.

Needs to first run scripts/setup.sh to bound to UIO or VFIO first.

**Comment by KKaras169169** [comment]
Thank you, this explains a lot. Now the new questions arises: Is the appearance of a new bdev HotInNvme1n1 (the new one with "pci_address": "0000:0a:00.0") the expected behaviour, or should it somehow resurrect the original Nvme0n1?

**Comment by Comphix** [comment]
Yes, the name is generated in this way.

```
module/bdev/nvme/bdev_nvme.c:
static void
attach_cb(void *cb_ctx, const struct spdk_nvme_transport_id *trid,
	  struct spdk_nvme_ctrlr *ctrlr, const struct spdk_nvme_ctrlr_opts *drv_opts)
{
	char *name;

	name = spdk_sprintf_alloc("HotInNvme%d", g_hot_insert_nvme_controller_index++);   <<<<<<
	if (!name) {
		SPDK_ERRLOG("Failed to assign name to NVMe device\n");
		return;
	}

	SPDK_DEBUGLOG(bdev_nvme, "Attached to %s (%s)\n", trid->traddr, name);

	nvme_ctrlr_create(ctrlr, name, trid, NULL);

	free(name);
}
```
