### ISSUE TITLE
[nvmf_perf_adq] num_busy_count != tc1 queues of traffic classes

### ISSUE THREAD

**Issue by curtbruns** [spdk/spdk#2539]
# CI Intermittent Failure

## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_78158.html

## Execution failed at
https://ci.spdk.io/results/autotest-per-patch/builds/78158/archive/nvmf-tcp-phy-autotest/build.log

00:11:53.428  ========== Backtrace start: ==========
00:11:53.428  
00:11:53.428  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/common/autotest_common.sh:970 -> run_test(["nvmf_perf_adq"],["test/nvmf/target/perf_adq.sh"],["--transport=tcp"])
00:11:53.428       ...
00:11:53.428     965 		timing_enter $test_name
00:11:53.428     966 		echo "************************************"
00:11:53.428     967 		echo "START TEST $test_name"
00:11:53.428     968 		echo "************************************"
00:11:53.428     969 		xtrace_restore
00:11:53.428  => 970 		time "$@"
00:11:53.428     971 		xtrace_disable
00:11:53.428     972 		echo "************************************"
00:11:53.428     973 		echo "END TEST $test_name"
00:11:53.428     974 		echo "************************************"
00:11:53.428     975 		timing_exit $test_name
00:11:53.428       ...
00:11:53.428  in ./test/nvmf/nvmf.sh:65 -> main(["--transport=tcp"])
00:11:53.428       ...
00:11:53.428     60  	if [[ $NET_TYPE == phy ]]; then
00:11:53.428     61  		if [ "$SPDK_TEST_NVMF_TRANSPORT" = "tcp" ]; then
00:11:53.428     62  			gather_supported_nvmf_pci_devs
00:11:53.428     63  			TCP_INTERFACE_LIST=("${net_devs[@]}")
00:11:53.428     64  			if ((${#TCP_INTERFACE_LIST[@]} > 0)); then
00:11:53.428  => 65  				run_test "nvmf_perf_adq" test/nvmf/target/perf_adq.sh "${TEST_ARGS[@]}"
00:11:53.428     66  			fi
00:11:53.428     67  		fi
00:11:53.428     68  		run_test "nvmf_shutdown" test/nvmf/target/shutdown.sh "${TEST_ARGS[@]}"
00:11:53.428     69  		#TODO: disabled due to intermittent failures. Need to triage.
00:11:53.428     70  		# run_test "nvmf_srq_overwhelm" test/nvmf/target/srq_overwhelm.sh $TEST_ARGS
00:11:53.428       ...
00:11:53.428  
00:11:53.428  ========== Backtrace end ==========

**Comment by jimharris** [comment]
@wanghailiangx - could you take a look at this issue?

**Comment by wanghailiangx** [comment]
@jimharris I found that ./perf -P when the value of -P(number of io queues per namespace) is smaller, for example 1, the issue is easier to reproduce. In perf_adq.sh code, it is 2. Then local tests are not easy to reproduce. In the previous adq patch version, I set 4. Now I change it back to 4. I believe this will make the test run more stable.
A new patch to fix it, https://review.spdk.io/gerrit/c/spdk/spdk/+/12859

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_78363.html

**Comment by wanghailiangx** [comment]
I will double check it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_78543.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_78968.html
