### ISSUE TITLE
autobuild-vg-autotest: confirm_abi_deps fails on libspdk_nvme.so major version

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2545]
# Bug report

`autobuild_check_so_deps` AKA `confirm_abi_deps` fails when doing ABI comparison vs latest SPDK relase.
https://ci.spdk.io/public_build/autotest-per-patch_78332.html

The VM image was not regenerated with fresh ABI reference builds just after 22.05 release and the tests now fail when trying to deploy the new image. CI does not fail on every patch right now because I rolled back the updated image.

## Possible Solution

Increase SO major version for libspdk_nvme.so.

The test passed yesterday with HEAD at `test/nvmf: test reconnect_delay_sec parameter` (95e057210) and failed today at `bdev_aio: fix aio error indication` (9be660eab).

```
git log --oneline 95e057210..9be660eab
9be660eab (HEAD -> master, origin/master, origin/HEAD) bdev_aio: fix aio error indication
b79199af3 include/nvme_spec.h: update fields for power state descriptor
da4540009 nvme/perf: add missing square brackets for usage
```

## Steps to Reproduce

N/A

## Context (Environment including OS version, SPDK version, etc.)

SPDK `9be660eabd23d20c2742406a37ae7f09ea2eb209`

**Comment by jimharris** [comment]
> ```
> git log --oneline 95e057210..9be660eab
> 9be660eab (HEAD -> master, origin/master, origin/HEAD) bdev_aio: fix aio error indication
> b79199af3 include/nvme_spec.h: update fields for power state descriptor
> da4540009 nvme/perf: add missing square brackets for usage
> ```

```bu9199af3``` is the culprit.  From the log:

```
00:07:35.227  * Running confirm_abi_deps against spdk_abi_latest
00:07:40.510  Please update the major SO version for libspdk_nvme.so. A header accessible type has been modified since last release.
00:07:41.082  Leaf changes summary: 1 artifact changed
00:07:41.082  Changed leaf types summary: 1 leaf type changed
00:07:41.082  Removed/Changed/Added functions summary: 0 Removed, 0 Changed, 0 Added function
00:07:41.082  Removed/Changed/Added variables summary: 0 Removed, 0 Changed, 0 Added variable
00:07:41.082  
00:07:41.082  'struct spdk_nvme_power_state at nvme_spec.h:1703:1' changed:
00:07:41.082    type size hasn't changed
00:07:41.082    8 data member insertions:
00:07:41.082      'uint16_t idlp', at offset 128 (in bits) at nvme_spec.h:1727:1
00:07:41.082      'uint8_t ips', at offset 150 (in bits) at nvme_spec.h:1730:1
00:07:41.082      'uint8_t reserved8', at offset 152 (in bits) at nvme_spec.h:1732:1
00:07:41.082      'uint16_t actp', at offset 160 (in bits) at nvme_spec.h:1734:1
00:07:41.082      'uint8_t apw', at offset 176 (in bits) at nvme_spec.h:1736:1
```

I've pushed https://review.spdk.io/gerrit/c/spdk/spdk/+/12931 to suppress that failure.
