### ISSUE TITLE
fio verify state files and output files in build artifacts

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2546]
# Bug report

There are leftovers after fio tests present in build artifacts.

For example:
https://ci.spdk.io/public_build/autotest-per-patch_78328.html

https://ci.spdk.io/results/autotest-per-patch/builds/78328/archive/centos8-vg-autotest/blockdev_fio_verify.txt
https://ci.spdk.io/results/autotest-per-patch/builds/78328/archive/centos8-vg-autotest/local-job_AIO0-14-verify.state
https://ci.spdk.io/results/autotest-per-patch/builds/78328/archive/centos7-vg-autotest/blockdev_trim.txt
https://ci.spdk.io/results/autotest-per-patch/builds/78328/archive/iscsi-vg-autotest/local-job_Ceph0-0-verify.state

## Expected Behavior

I don't think these should be archived.
verify.state files are not very useful because we fail the tests at any first failure. If there was something wrong with IO verification then  autotest.sh would fail.
fio files with metrics output (IOPS, BW, latency, etc) are also not very useful as per-patch tests are not focused on benchmarking.

## Possible Solution

* Look for any output redirections (`>, &>, 1>, | tee or similar `) from fio process, or fio run with `--output=x` parameter and disable saving the output in the $output_dir
* look for tests with fio do_verify=1 and add `verify_state_save=0` to it's parameters to disable saving state files (see `man fio`)

**Comment by kgodzwox** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/13019
