### ISSUE TITLE
Script pkdep.sh can't find python in Ubuntu 22.04

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#2547]
# Bug report

When I run scripts/pkgdep.sh in a system with Ubuntu 22.04 the script throws and error indicating python has no installation candidate.

## Expected Behavior

pkdep.sh runs successfully and installs all packages needed to compile and run spdk on Ubuntu 22.04

## Current Behavior

pkdep.sh fails and throws an error indicating package python has no installation candidate.

## Possible Solution

1. Removed python from line 7 of scripts/pkdep/debian.sh and successfully ran scripts/pkgdep.sh
2. Will try wrapping python package around an if statement checking for version 22.04 or greater

## Steps to Reproduce

1. I cloned spdk and went into the spdk directory and ran scripts/pkgdep.sh
2. Got the following error:
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal python2 dh-python 2to3 python-is-python3
E: Package 'python' has no installation candidate
Error!
3. I got the same exact error when I ran apt-get install python
4. Checked system for python and confirmed that python 3.10.4 is already installed
5. Removed python from line 7 of scripts/pkdep/debian.sh and successfully ran scripts/pkgdep.sh

## Context (Environment including OS version, SPDK version, etc.)
OS: Ubuntu 22.04
SPDK version: commit 9be660eabd

**Comment by mikeBashStuff** [comment]
I believe there's already a commit waiting on gerrit to be merged and which addresses this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/12804

**Comment by peluse** [comment]
See https://review.spdk.io/gerrit/c/spdk/spdk/+/12804

**Comment by jimharris** [comment]
> See https://review.spdk.io/gerrit/c/spdk/spdk/+/12804

Correct, I've added my +2 to Alexey's patch, it's just waiting for another +2.
