### ISSUE TITLE
[llvm_fuzz] llvm fuzz test failed in CI with llvm_nvme_fuzz.c:242:30: runtime error: left shift of 177 by 24 places cannot be represented in type 'int'

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2549]
# Bug report

llvm fuzz test failed in CI with llvm_nvme_fuzz.c:242:30: runtime error: left shift of 177 by 24 places cannot be represented in type 'int'

## Expected Behavior

test can pass

## Current Behavior

CI job raise an error: llvm_nvme_fuzz.c:242:30: runtime error: left shift of 177 by 24 places cannot be represented in type 'int'. But it can't be reproduce on local machine.

## Steps to Reproduce

1. cd to the spdk directory  `rm -rf /tmp/llvm_fuzz10`
2. `CC=clang-12 CXX=clang++-12 ./configure --without-isal --with-fuzzer=/usr/lib64/clang/12/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a`
3. `make -j128`
4. `mkdir -p /tmp/llvm_fuzz10`
5. `./scripts/setup.sh`
6. `./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F 'trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420' -c test/nvmf/target/fuzz_json.conf -t 60000 -D /tmp/llvm_fuzz10 -Z 10`

It failed in CI, link is https://spdkci.intel.com/job/nvmf-fuzz-autotest/22/consoleFull
Error information as below:
11:04:48  #84	NEW    cov: 11512 ft: 15100 corp: 80/707b lim: 40 exec/s: 21 rss: 193Mb L: 1/40 MS: 2 ChangeByte-ChangeByte-
11:04:48  #85	NEW    cov: 11512 ft: 15164 corp: 81/742b lim: 40 exec/s: 21 rss: 193Mb L: 35/40 MS: 1 InsertRepeatedBytes-
11:04:48  llvm_nvme_fuzz.c:242:30: runtime error: left shift of 177 by 24 places cannot be represented in type 'int'
11:04:48      #0 0x473e14 in fuzz_admin_security_receive_command /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:242:30
11:04:48      #1 0x4a709a in run_cmds /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:763:3
11:04:48      #2 0x4a6d34 in TestOneInput /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:803:2
11:04:48      #3 0x1e35a39 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e35a39)
11:04:48      #4 0x1e365a0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e365a0)
11:04:48      #5 0x1e376b3 in fuzzer::Fuzzer::MutateAndTestOne() (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e376b3)
11:04:48      #6 0x1e391a7 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e391a7)
11:04:48      #7 0x1e1e20a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e1e20a)
11:04:48      #8 0x4a68be in start_fuzzer /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:856:3
11:04:48      #9 0x7f8f50095298 in start_thread (/usr/lib64/libpthread.so.0+0x9298)
11:04:48      #10 0x7f8f4ffa2352 in clone (/usr/lib64/libc.so.6+0x100352)
11:04:48  
11:04:48  SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior llvm_nvme_fuzz.c:242:30 in 
11:04:48  MS: 2 ShuffleBytes-InsertRepeatedBytes-; base unit: 5ba93c9db0cff93f52b521d7420e43f6eda2784f
11:04:48  0x0,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,
11:04:48  \x00\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1
11:04:48  artifact_prefix='./'; Test unit written to ./crash-3e2933350a49825843ff75bb7a0bfcd0e52d4b7d
11:04:48  Base64: ALGxsbGxsbGxsbGxsbGxsbGx
11:04:48  ==2436678== ERROR: libFuzzer: deadly signal
11:04:48      #0 0x463f3e in __sanitizer_print_stack_trace (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x463f3e)
11:04:48      #1 0x1e547a9 in fuzzer::PrintStackTrace() (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e547a9)
11:04:48      #2 0x1e35506 in fuzzer::Fuzzer::CrashCallback() (.part.0) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e35506)
11:04:48      #3 0x1e355cb in fuzzer::Fuzzer::StaticCrashSignalCallback() (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e355cb)
11:04:48      #4 0x7f8f5009fa1f  (/usr/lib64/libpthread.so.0+0x13a1f)
11:04:48      #5 0x7f8f4fedf2a1 in raise (/usr/lib64/libc.so.6+0x3d2a1)
11:04:48      #6 0x7f8f4fec88a3 in abort (/usr/lib64/libc.so.6+0x268a3)
11:04:48      #7 0x45291e in __sanitizer::Abort() (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x45291e)
11:04:48      #8 0x45085b in __sanitizer::Die() (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x45085b)
11:04:48      #9 0x45e38e in __ubsan::ScopedReport::~ScopedReport() (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x45e38e)
11:04:48      #10 0x46217e in handleShiftOutOfBoundsImpl(__ubsan::ShiftOutOfBoundsData*, unsigned long, unsigned long, __ubsan::ReportOptions) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x46217e)
11:04:48      #11 0x46308a in __ubsan_handle_shift_out_of_bounds (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x46308a)
11:04:48      #12 0x473e14 in fuzz_admin_security_receive_command /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:242:30
11:04:48      #13 0x4a709a in run_cmds /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:763:3
11:04:48      #14 0x4a6d34 in TestOneInput /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:803:2
11:04:48      #15 0x1e35a39 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e35a39)
11:04:48      #16 0x1e365a0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e365a0)
11:04:48      #17 0x1e376b3 in fuzzer::Fuzzer::MutateAndTestOne() (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e376b3)
11:04:48      #18 0x1e391a7 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e391a7)
11:04:48      #19 0x1e1e20a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x1e1e20a)
11:04:48      #20 0x4a68be in start_fuzzer /var/jenkins/workspace/nvmf-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:856:3
11:04:48      #21 0x7f8f50095298 in start_thread (/usr/lib64/libpthread.so.0+0x9298)
11:04:48      #22 0x7f8f4ffa2352 in clone (/usr/lib64/libc.so.6+0x100352)
11:04:48  
11:04:48  NOTE: libFuzzer has rudimentary signal handlers.
11:04:48        Combine libFuzzer with AddressSanitizer or similar for better crash reports.
11:04:48  SUMMARY: libFuzzer: deadly signal
11:04:48  MS: 2 ShuffleBytes-InsertRepeatedBytes-; base unit: 5ba93c9db0cff93f52b521d7420e43f6eda2784f
11:04:48  0x0,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,0xb1,
11:04:48  \x00\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1\xb1
11:04:48  artifact_prefix='./'; Test unit written to ./crash-3e2933350a49825843ff75bb7a0bfcd0e52d4b7d
11:04:48  Base64: ALGxsbGxsbGxsbGxsbGxsbGx

But when I use same code and same OS on local machine, it can't be reproduce any more.

## Context (Environment including OS version, SPDK version, etc.)

OS version: `fedora34`
Kernel version: `5.12.10-300.fc34.x86_64`
SPDK version: 9be660eabd23d20c2742406a37ae7f09ea2eb209

**Comment by jimharris** [comment]
> I think what happens here is `g_data[4]`, which is an `uint8_t`, is being promoted to 32b `int`, which doesn't fit the result of `177 << 24`. Could you check if the following fixes it?

And if it does, we need to make this same fix in several other fuzzers in this file.

**Comment by junwenx** [comment]
@jimharris @ksztyber Thank you all, is it need a patch to fix it? And I don't understand one thing, why it can't be  reproduced on my local machine?

**Comment by yidong0635** [comment]
If you want to catch this issue, it depends on the analyzer version. Add we can add a macro here.

**Comment by yidong0635** [comment]
Add a patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/13005
