### ISSUE TITLE
vhost user set_mem_table cost much time during vhost-user-blk negotiating with cloud-hypervisor

### ISSUE THREAD

**Issue by Apokleos** [spdk/spdk#2552]
# Bug report
In my scenario,  time of creating a VM must be limited to 4s. However, only the vhost-user backend and frontend negotiation costs  8654361.000000 (us). Obviously it's not acceptable.  
(1) SPDK main thread monitor indicates that `VHOST_USER_SET_MEM_TABLE` costs a long time, as below:
```
...
VHOST_CONFIG: read message VHOST_USER_SET_MEM_TABLE
EAL: VFIO support not initialized
EAL: Couldn't map new region for DMA
VHOST_CONFIG: guest memory region size: 0xc0000000
	 guest physical addr: 0x0
	 guest virtual  addr: 0x7f9738000000
	 host  virtual  addr: 0x7fc7f4000000
	 mmap addr : 0x7fc7f4000000
	 mmap size : 0xc0000000
	 mmap align: 0x200000
	 mmap off  : 0x0
VHOST_CONFIG: vhost_user_mmap_region[0] Cost02 1659819.000000(us)
EAL: VFIO support not initialized
EAL: Couldn't map new region for DMA
VHOST_CONFIG: guest memory region size: 0x340000000
	 guest physical addr: 0x100000000
	 guest virtual  addr: 0x7f93f8000000
	 host  virtual  addr: 0x7fc4b4000000
	 mmap addr : 0x7fc4b4000000
	 mmap size : 0x340000000
	 mmap align: 0x200000
	 mmap off  : 0x0
VHOST_CONFIG: vhost_user_mmap_region[1] Cost02 6994318.000000(us)
VHOST_CONFIG: Mem table negotiates Cost 8654361.000000(us)
...
```
(2) Deep into spdk/dpdk, get the place `vhost_user_mmap_region` and further locate to ```	mmap(NULL, mmap_size, PROT_READ | PROT_WRITE,MAP_SHARED | populate, region->fd, 0);```

So, I want to know that
(1) The negotiation will indeed cost lot of time?
(2) Is there a way to optimize the setting memory table negotiation and reduce the time?

## Expected Behavior
**Reduce the consumption of set_Mem_table negotiation.**

## Steps to Reproduce

1. cloud hypervisor(v24.0-29) and spdk(v22.05/v22.01)
2. 
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

Thank you!

**Comment by changpe1** [comment]
Do you have a physical PCI device that bind to kernel vfio driver? 
Some users complained about the time when registering vhost memory region to vfio device fd via IOCTL, it's the first time that I see the time is consumed in MMAP.

**Comment by Apokleos** [comment]
> Do you have a physical PCI device that bind to kernel vfio driver? 
>
No, I set `DRIVER_OVERRIDE=uio_pci_generic` when setup.sh. and I just use `bdev_aio_create ` to create a raw disk with linux `dd`. 
> Some users complained about the time when registering vhost memory region to vfio device fd via IOCTL, it's the first time that I see the time is consumed in MMAP.
> 
Do you mean that it relates to vfio with the mssage `EAL: VFIO support not initialized
EAL: Couldn't map new region for DMA` ?
```
$lsmod |grep vfio
vfio_pci               57344  1 
vfio_virqfd            16384  1 vfio_pci
vfio_iommu_type1       28672  0 
vfio                   32768  4 vfio_iommu_type1,vfio_pci
$lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
nvme0n1 25:0    0  1T  0 disk /home/xxx
...
```
and with my shell scripts:
```
...
  DRIVER_OVERRIDE=uio_pci_generic scripts/setup.sh
  /build/bin/vhost -m 0xF000 -S /tmp/spdk -c config.json 
```

**Comment by changpe1** [comment]
do you use hugepages for the VM?

**Comment by Apokleos** [comment]
> do you use hugepages for the VM?
1. SPDK: I have set huge pages with `sysctl -w vm.nr_hugepages=12288`,but setup.sh with default HUGEMEM:2048
2. I did not set memory with hugepages=on but set the share=on.
A little better now!!! 
After that, I set `hugepages=on` and the clh cmd `"--cpus boot=8 --memory size=${MEMOR},shared=on,hugepages=on"` and the memory table negotiation consumption reduces to `VHOST_CONFIG: Negotiate Cost 4063202.000000 (us)`

But it is still a big consumption!

**Comment by changpe1** [comment]
> > do you use hugepages for the VM?
> 
> 1. SPDK: I have set huge pages with `sysctl -w vm.nr_hugepages=12288`,but setup.sh with default HUGEMEM:2048
> 2. I did not set memory with hugepages=on but set the share=on.
>    A little better now!!!
>    After that, I set `hugepages=on` and the clh cmd `"--cpus boot=8 --memory size=${MEMOR},shared=on,hugepages=on"` and the memory table negotiation consumption reduces to `VHOST_CONFIG: Negotiate Cost 4063202.000000 (us)`
> 
> But it is still a big consumption!

can you also add  `prealloc=yes` to see it helps or not?

**Comment by Apokleos** [comment]
> 
>


> > > do you use hugepages for the VM?
> > 
> > 
> > 
> > 1. SPDK: I have set huge pages with `sysctl -w vm.nr_hugepages=12288`,but setup.sh with default HUGEMEM:2048
> > 2. I did not set memory with hugepages=on but set the share=on.
> >    A little better now!!!
> >    After that, I set `hugepages=on` and the clh cmd `"--cpus boot=8 --memory size=${MEMOR},shared=on,hugepages=on"` and the memory table negotiation consumption reduces to `VHOST_CONFIG: Negotiate Cost 4063202.000000 (us)`
> > 
> > But it is still a big consumption!
> 
> can you also add `prealloc=yes` to see it helps or not?
>
@changpe1 Thank you very much. Good news.
Though there's no `prealloc=yes` but `prefault=on` , and I set the cmd as `MACHINE="--cpus boot=8 --memory size=${MEMOR},shared=on,hugepages=on,hugepage_size=2M,prefault=on"`  and the negotiation consumption reduces to `VHOST_CONFIG: Negotiate Cost 9614.000000 (us)`.


But, I'm confused with the cloud-hypervisor [prefault](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/memory.md#prefault). The expected behaviour is slower booting when setting prefault=on, but faster in my test, Why?

**Comment by junwenx** [comment]
@Apokleos Hi, what kind of tool you use to start vm? It looks not qemu, could you please paste the whole cmd about it? I want to  try it on my machine. Thanks a lot.

**Comment by changpe1** [comment]
> @Apokleos Hi, what kind of tool you use to start vm? It looks not qemu, could you please paste the whole cmd about it? I want to try it on my machine. Thanks a lot.

it's cloud-hypervisor, not qemu. we don't provide such test cases.

**Comment by junwenx** [comment]
@changpe1 Thanks Changpeng, I understood. Thank you.

**Comment by Apokleos** [comment]
Thank you @changpe1  problem now is solved, the issue is closed now.
