### ISSUE TITLE
NVMe Over TCP: SPDK_BDEV_IO_STATUS_ABORTED is not handled in the Fuse command

### ISSUE THREAD

**Issue by balamsg** [spdk/spdk#2553]
# Bug report

The SPDK_BDEV_IO_STATUS_ABORTED is not handled in the spdk_bdev_io_get_nvme_fused_status( ) of the fuse command. So, when the abort is issued for the fuse command it returns with the error code as SPDK_NVME_SC_INTERNAL_DEVICE_ERROR. But as per the NVMe spec when a command is aborted it should return SPDK_NVME_SC_ABORTED_BY_REQUEST.

## Expected Behavior
When the abort command is issued for the fuse command, it should return SPDK_NVME_SC_ABORTED_BY_REQUEST instead of SPDK_NVME_SC_INTERNAL_DEVICE_ERROR.

## Current Behavior

Currently the response is SPDK_NVME_SC_INTERNAL_DEVICE_ERROR.

## Possible Solution

Return the proper error by handling the abort

## Steps to Reproduce

Issue an abort for the fuse command i.e Compare and write.

## Context (Environment including OS version, SPDK version, etc.)
SPDK 22.05

**Comment by changpe1** [comment]
@balamsg would you like to provide a fix patch for this issue?

**Comment by balamsg** [comment]
Hi @changpe1 , can you please review the patch 
https://review.spdk.io/gerrit/c/spdk/spdk/+/13025

**Comment by balamsg** [comment]
astyling issues were there... Fixed it & submitted the patch again..
Please review it.
