### ISSUE TITLE
Potential NULL pointer access in nvmf_ctrlr_cc_timeout()

### ISSUE THREAD

**Issue by davidcs12** [spdk/spdk#2554]
# Bug report
During "controller shutdown" **nvmf_ctrlr_cc_timeout** is registered/armed  in **nvmf_prop_set_cc()**
```
nvmf_prop_set_cc()
{
:
ctrlr->cc_timeout_timer = SPDK_POLLER_REGISTER(nvmf_ctrlr_cc_timeout, ctrlr,
        NVMF_CC_RESET_SHN_TIMEOUT_IN_MS * 1000);
:
}
```
Thereafter the following sequence of calls are made.

```
nvmf_prop_set_cc() 
    nvmf_ctrlr_disconnect_io_qpairs_on_pg ()    
        _nvmf_ctrlr_disconnect_qpairs_on_pg()    
              spdk_nvmf_qpair_disconnect()           
                    _nvmf_qpair_destroy()                 
                           nvmf_transport_qpair_fini()   
                                _nvmf_transport_qpair_fini_complete() 
```

 **ctrlr->admin_qpair** is set to NULL in **_nvmf_transport_qpair_fini_complete()**

```
_nvmf_transport_qpair_fini_complete()
{
:
ctrlr->admin_qpair = NULL;
:
}  
```                             
Now nvmf_ctrlr_cc_timeout() is unregistered/disarmed in 
**_nvmf_ctrlr_cc_reset_shn_done()** and **nvmf_ctrlr_cc_timeout()**

So if the timeout fires before **_nvmf_ctrlr_cc_reset_shn_done()** is invoked, but after "ctrlr->admin_qpair is set to NULL"  in **_nvmf_transport_qpair_fini_complete()**  we can hit the following condition in nvmf_ctrlr_cc_timeout()

```
static int
nvmf_ctrlr_cc_timeout(void *ctx)
{
    struct spdk_nvmf_ctrlr *ctrlr = ctx;
    struct spdk_nvmf_poll_group *group = ctrlr->admin_qpair->group;  
```  
**ctrl->admin_qpair = NULL** . Hence **ctrlr->admin_qpair->group** results in NULL pointer access.
                              

## Expected Behavior

We should check if **ctrlr->admin_qpair** == NULL before setting 
**group = ctrlr->admin_qpair->group**

## Current Behavior

We have a potential NULL pointer access

## Possible Solution

```
diff --git a/lib/nvmf/ctrlr.c b/lib/nvmf/ctrlr.c
index 0aa8d4ca8..63c9e8f32 100644
--- a/lib/nvmf/ctrlr.c
+++ b/lib/nvmf/ctrlr.c
@@ -1027,10 +1027,15 @@ static int
 nvmf_ctrlr_cc_timeout(void *ctx)
 {
        struct spdk_nvmf_ctrlr *ctrlr = ctx;
-       struct spdk_nvmf_poll_group *group = ctrlr->admin_qpair->group;
+       struct spdk_nvmf_poll_group *group;
        struct spdk_nvmf_ns *ns;
        struct spdk_nvmf_subsystem_pg_ns_info *ns_info;

+       if (ctrlr->admin_pair == NULL) {
+               return SPDK_POLLER_IDLE;
+       }
+
+       group = ctrlr->admin_qpair->group;
        assert(group != NULL && group->sgroups != NULL);
        spdk_poller_unregister(&ctrlr->cc_timeout_timer);
        SPDK_DEBUGLOG(nvmf, "Ctrlr %p reset or shutdown timeout\n", ctrlr);

```

## Steps to Reproduce

1.Connect to an nvme device from a RHEL host.
2.While Random Read/Write I/Os are performed to the nvme device, issue "Controller Shutdown"
nvme set-property /dev/ --offset=0x14 --value=0x464001
Please make sure that sufficient traffic is present when the controller shutdown is performed.  Several retries of "controller shutdown" may be needed to trigger the issue.

## Context (Environment including OS version, SPDK version, etc.)

RedHat Linux (RHEL8.3) , SPDK Version : 22.01

**Comment by davidcs12** [comment]
Adding  @ksztyber @shuhei-matsumoto @mkotwani1

**Comment by shuhei-matsumoto** [comment]
Hi @davidcs12 

_nvmf_transport_qpair_fini_complete() sets ctrlr->admin_qpair to NULL only if qpair_ctx->qid is 0.

nvmf_ctrlr_disconnect_io_qpairs_on_pg() excludes admin qpair by setting the second parameter of _nvmf_ctrlr_disconnect_qpairs_on_pg() to false.

_nvmf_ctrlr_disconnect_qpairs_on_pg() skips admin qpair if the parameter include_admin is false.

spdk_nvmf_qpair_disconnect() for admin qpair is executed by nvmf_ctrlr_association_remove(), and nvme_ctrlr_association_remove() is called by nvmf_ctrlr_cc_reset_shn_done()?

Hence,

>So if the timeout fires before _nvmf_ctrlr_cc_reset_shn_done() is invoked, but after "ctrlr->admin_qpair is set to NULL" in _nvmf_transport_qpair_fini_complete() we can hit the following condition in nvmf_ctrlr_cc_timeout()

can occur? If NULL pointer access occurs, different call sequence happened?

**Comment by davidcs12** [comment]
Hi @shuhei-matsumoto
thanks for the response. You are correct. The call sequence which triggers this should be different from the one I mentioned above. It appears that the only two cases where "ctrlr->admin_qpair == NULL" are 
1. ctrlr was added but an admin_qpair was not assigned to it.
2. in _nvmf_transport_qpair_fini_complete()  if qpair_ctx->qid is 0. 

Will investigate further.

**Comment by shuhei-matsumoto** [comment]
Thank you @davidcs12 I want to wait for your further investigation

**Comment by ksztyber** [comment]
@davidcs12, any updates on this?

**Comment by davidcs12** [comment]
@ksztyber @shuhei-matsumoto  I haven't encountered this issue again. We can close this bug.
