### ISSUE TITLE
Segfault in thread_execute_timed_poller() at thread.c:872 after qpair_handle_timeout poller gets unregistered from qpair destroy

### ISSUE THREAD

**Issue by pvonti** [spdk/spdk#2555]
# Bug report

With fixes for SPDK bugs 2445, 2471 and 2527 added, see Segfault in thread_execute_timed_poller() at thread.c:872 during SPDK target shutdown and qpair destroy.

## Expected Behavior

Process restart with IOs on 8 nvme devices, should result in a clean SPDK target shutdown and SPDK thread exit of all SPDK threads.

## Current Behavior

With 20 iterations of process restart with 10 volumes exported to the host, 4 Qpairs and 8 outstanding Reads/writes, see segmentation fault when thread_poll() calls thread_execute_timed_poller() and qpair_handle_timeout poller gets unregistered from qpair disconnect/qpair destroy path.

## Steps to Reproduce

Here are the steps which causes the segfault
1. Create a subsystem and export 1 volume to a linux host.
2. Connect to the subsystem with 1 IO queue pair.
3. nvme connect -t tcp -a -n <subsystem_nqn> -q <host_nqn> -s4420 --nr-io-queues=1
4. Issue Write IOs to the nvme disk using your IO tool with 8 outstanding IOs.
5. Restart the target application for 10-15 iterations

Segmentation fault seen when thread_poll() calls thread_execute_timed_poller() and qpair_handle_timeout poller gets unregistered from qpair disconnect/qpair destroy path.

Target application restart triggers SPDK shutdown, qpair disconnect and abort of IOs. Issue seen when IO in NVMF_ZCOPY_PHASE_EXECUTE and TCP_REQUEST_STATE_TRANSFERRING_HOST_TO_CONTROLLER state is completed.

Write tcp_request with data outstanding from host is aborted and freed during qpair disconnect
shutdown_spdk -> spdk_nvmf_subsystem_stop() -> subsystem_state_change_on_pg() -> nvmf_poll_group_remove_subsystem() -> nvmf_poll_group_remove_subsystem_msg() -> spdk_nvmf_qpair_disconnect() -> nvmf_qpair_abort_pending_zcopy_reqs()

Host sends data, nvmf_tcp_h2c_data_hdr_handle() does not find a tcp_request in TCP_REQUEST_STATE_TRANSFERRING_HOST_TO_CONTROLLER or TCP_REQUEST_STATE_AWAITING_R2T_ACK and sends c2h terminate request.

nvmf_tcp_send_c2h_term_req_complete() registers nvmf_tcp_qpair_handle_timeout()

Poller is still running, thread_poll() calls thread_execute_timed_poller()

Qpair disconnect unregisters qpair_handle_timeout pollerand destroys the qpair.

thread_execute_timed_poller() hits a segfault at thread.c line 872, with qpair_handle_timeout poller removed.

static inline int
thread_execute_timed_poller(struct spdk_thread *thread, struct spdk_poller *poller,
uint64_t now)
850 static inline int
851 thread_execute_timed_poller(struct spdk_thread *thread, struct spdk_poller *poller,
852 uint64_t now)
853 {
854 int rc;
855
856 switch (poller->state) {
857 case SPDK_POLLER_STATE_UNREGISTERED:
858 free(poller);
859 return 0;
860 case SPDK_POLLER_STATE_PAUSING:
861 TAILQ_INSERT_TAIL(&thread->paused_pollers, poller, tailq);
862 poller->state = SPDK_POLLER_STATE_PAUSED;
863 return 0;
864 case SPDK_POLLER_STATE_WAITING:
865 break;
866 default:
867 assert(false);
868 break;
869 }
870
871 poller->state = SPDK_POLLER_STATE_RUNNING;
872 rc = poller->fn(poller->arg); <====== Seg fault poller->fn ==NULL
873
874 poller->run_count++;
875 if (rc > 0) {
876 poller->busy_count++;
877 }
878 …..
}

## Context (Environment including OS version, SPDK version, etc.)

Segfault seen with SPDK version 22.01 with fixes for SPDK bugs 2445, 2471, 2527.

**Comment by pvonti** [comment]
Hello @ksztyber, can you please take a look at the issue. I am seeing this issue with fix for 2527.

**Comment by pvonti** [comment]
Hi @ksztyber,

1. Can the qpair handle timepout poller get unregistered from qpair disconnect context when the poller is running? I'll add debug logs and try to reproduce the issue again.

2. I have not tried to reproduce the issue with upstream target apps. Issue was seen with SPDK target integrated with HPE OS.

**Comment by ksztyber** [comment]
@pvonti, any updates on this issue?

**Comment by jimharris** [comment]
Closing issue.  @pvonti, if you are able to repro with upstream apps, please reopen.
