### ISSUE TITLE
Test case "confirm_makefile_deps" in check_so_deps.sh isn't accurate

### ISSUE THREAD

**Issue by changpe1** [spdk/spdk#2556]
# Bug report

One of my patch got failure in CI environment via the following log:

https://ci.spdk.io/results/autotest-per-patch/builds/78130/archive/autobuild-vg-autotest/build.log
https://review.spdk.io/gerrit/c/spdk/spdk/+/12315

00:08:58.322  START TEST confirm_makefile_deps
00:08:58.322  ************************************
00:08:58.322  ---------------------------------------------------------------------
00:09:06.444  there was a dependency mismatch in the library vfio_user_device
00:09:06.444  The makefile (spdk.lib_deps.mk) lists: 'log util json jsonrpc rpc bdev thread vfio_user_target'
00:09:06.444  readelf outputs   : 'bdev jsonrpc json log nvmf rpc thread util vfio_user_target'

## Expected Behavior

"confirm_makefile_deps" is accurate.

## Current Behavior

The new added library libspdk_vfio_user_device.so has dependency on third party libvfio-user.a library, and existing libspdk_nvmf.so also has dependency on same library, so when checking libspdk_vfio_user_device.so, this test case will report false
dependency.

## Possible Solution

Maybe we should only check the dependency for public SPDK APIs with "spdk_" prefix.

## Steps to Reproduce

1. Use this patch https://review.spdk.io/gerrit/c/spdk/spdk/+/12315
2. ./configure --enable-debug --with-shared --with-vfio-user
3. run check_so_deps.sh

**Comment by changpe1** [comment]
@mikeBashStuff could you take a look? 

readelf outputs : 'bdev jsonrpc json log **nvmf** rpc thread util vfio_user_target'

nvmf is the false dependency library reported by "confirm_makefile_deps". thanks.

**Comment by mikeBashStuff** [comment]
@changpe1 Sure, will check it out.

**Comment by mikeBashStuff** [comment]
@changpe1 Here's the WIP patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/13033 Would you kindly take a look? I am not sure if that's the correct approach - I based that solely on your suggestion here:

>Maybe we should only check the dependency for public SPDK APIs with "spdk_" prefix.

Let me know if I understood it right. :) Also, I thought that `readelf`'s view always takes precedence (unless some specific exceptions are needed like for `env_dpdk`, etc.), that's why I don't really have other ideas for alternatives here. I am open for feedback though. :)

**Comment by mikeBashStuff** [comment]
Ok, this definitely needs a bit more work. When I have something more concrete will push for review.

**Comment by mikeBashStuff** [comment]
@jimharris Appreciate the feedback and thanks for stepping in. With your comment in mind, I will just abandon my patches as you are definitely ahead of me with this one. :)

**Comment by changpe1** [comment]
sure, let me have a check first.

**Comment by changpe1** [comment]
thanks to @jimharris @mikeBashStuff  with the fix patch https://review.spdk.io/gerrit/c/spdk/spdk/+/13041,  my other patches passed the CI now.
