### ISSUE TITLE
NVMF Perf report error with high qd(like 127&128)- No valid NVMe controllers or AIO devices found

### ISSUE THREAD

**Issue by sudhesam** [spdk/spdk#256]
I have 2 CentOS machines.  I am using one of the machines as 'target' and one of them as initiator.

# **Target configuration:**

[root@test38 spdk]# lspci | grep -i mel
d8:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
d8:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]

[root@test38 spdk]# lspci | grep -i nvme | grep b7
b7:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961

### **nvmf.conf.in:**
[Nvme]
...
...
  TransportId "trtype:PCIe traddr:0000:b7:00.0" Nvme0
...
...

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 12.12.12.38:4420
  AllowAnyHost yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  Namespace Nvme0n1 1

I am now invoking nvmf_tgt with the above setup in nvmf.conf.in.

[root@test38 spdk]# ./app/nvmf_tgt/nvmf_tgt -c ./etc/spdk/nvmf.conf.in
Starting DPDK 18.02.0 initialization...
[ DPDK EAL parameters: nvmf -c 0x1 --file-prefix=spdk_pid72839 ]
EAL: Detected 48 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid72839_unix
EAL: Probing VFIO support...
app.c: 376:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 642:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
app.c: 415:spdk_app_start: *NOTICE*: Tracepoint Group Mask 0xFFFFFFFFFFFF specified.
app.c: 419:spdk_app_start: *NOTICE*: Use 'spdk_trace -s nvmf -p 72839' to capture a snapshot of events at runtime.
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 16
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 17
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 18
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 19
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 20
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 21
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 22
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 23
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 24
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 25
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 26
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 27
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 28
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 29
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 30
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 31
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 32
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 33
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 34
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 35
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 36
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 37
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 38
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 39
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 40
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 41
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 42
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 43
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 44
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 45
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 46
trace_flags.c:  58:spdk_trace_set_tpoints: *ERROR*: spdk_trace_set_tpoints: invalid group ID 47
reactor.c: 426:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
EAL: PCI device 0000:00:04.0 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.0 vendor:0x8086 device:0x2021
EAL: PCI device 0000:00:04.1 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.1 vendor:0x8086 device:0x2021
EAL: PCI device 0000:00:04.2 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.2 vendor:0x8086 device:0x2021
EAL: PCI device 0000:00:04.3 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.3 vendor:0x8086 device:0x2021
EAL: PCI device 0000:00:04.4 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.4 vendor:0x8086 device:0x2021
EAL: PCI device 0000:00:04.5 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.5 vendor:0x8086 device:0x2021
EAL: PCI device 0000:00:04.6 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.6 vendor:0x8086 device:0x2021
EAL: PCI device 0000:00:04.7 on NUMA socket 0
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:00:04.7 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.0 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.0 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.1 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.1 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.2 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.2 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.3 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.3 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.4 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.4 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.5 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.5 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.6 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.6 vendor:0x8086 device:0x2021
EAL: PCI device 0000:80:04.7 on NUMA socket 1
EAL:   probe driver: 8086:2021 spdk_ioat
copy_engine_ioat.c: 242:probe_cb: *NOTICE*:  Found matching device at 0000:80:04.7 vendor:0x8086 device:0x2021
copy_engine_ioat.c: 306:copy_engine_ioat_init: *NOTICE*: Ioat Copy Engine Offload Enabled
EAL: PCI device 0000:60:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:61:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:62:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:63:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:64:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:65:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:66:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:67:00.0 on NUMA socket 0
EAL:   probe driver: 144d:a802 spdk_nvme
EAL: PCI device 0000:b7:00.0 on NUMA socket 1
EAL:   probe driver: 144d:a804 spdk_nvme
EAL: PCI device 0000:b8:00.0 on NUMA socket 1
EAL:   probe driver: 144d:a804 spdk_nvme
EAL: PCI device 0000:b9:00.0 on NUMA socket 1
EAL:   probe driver: 144d:a804 spdk_nvme
EAL: PCI device 0000:ba:00.0 on NUMA socket 1
EAL:   probe driver: 144d:a804 spdk_nvme
EAL: PCI device 0000:bb:00.0 on NUMA socket 1
EAL:   probe driver: 144d:a804 spdk_nvme
EAL: PCI device 0000:bc:00.0 on NUMA socket 1
EAL:   probe driver: 144d:a804 spdk_nvme
bdev_aio.c:  76:bdev_aio_open: *ERROR*: open() failed (file:/dev/sdc), errno 2: No such file or directory
bdev_aio.c: 442:create_aio_disk: *ERROR*: Unable to open file /dev/sdc. fd: -1 errno: 2
bdev_aio.c: 560:bdev_aio_initialize: *ERROR*: Unable to create AIO bdev from file /dev/sdc
bdev_aio.c:  76:bdev_aio_open: *ERROR*: open() failed (file:/tmp/myfile), errno 2: No such file or directory
bdev_aio.c: 442:create_aio_disk: *ERROR*: Unable to open file /tmp/myfile. fd: -1 errno: 2
bdev_aio.c: 560:bdev_aio_initialize: *ERROR*: Unable to create AIO bdev from file /tmp/myfile
nvmf_tgt.c: 108:nvmf_tgt_create_subsystem: *NOTICE*: allocated subsystem nqn.2014-08.org.nvmexpress.discovery
nvmf_tgt.c: 108:nvmf_tgt_create_subsystem: *NOTICE*: allocated subsystem nqn.2016-06.io.spdk:cnode1
rdma.c:1136:spdk_nvmf_rdma_create: *NOTICE*: *** RDMA Transport Init ***
rdma.c:1376:spdk_nvmf_rdma_listen: *NOTICE*: *** NVMf Target Listening on 12.12.12.38 port 4420 ***
conf.c: 289:spdk_nvmf_parse_subsystem: *NOTICE*: Attaching block device Nvme0n1 to subsystem nqn.2016-06.io.spdk:cnode1
rdma.c:1517:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
rdma.c:1517:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
rdma.c:1517:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
nvmf_tgt.c: 283:nvmf_tgt_advance_state: *NOTICE*: Acceptor running

**Comment by sudhesam** [comment]
# **Initiator configuration:**
[test39@test39 identify]$ lspci | grep -i mel
d8:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
d8:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]

I am running 'identify' and passing 'discovery' subsystem to the command.  Below is the output of discovery:

[test39@test39 identify]$ sudo ./identify -r 'trtype:RDMA adrfam:IPv4 traddr:12.12.12.38 trsvcid:4420 subnqn:nqn.2014-08.org.nvmexpress.discovery'
Starting DPDK 18.02.0 initialization...
[ DPDK EAL parameters: identify -c 0x1 -n 1 -m 64 --no-pci --file-prefix=spdk_pid105450 ]
EAL: Detected 48 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid105450_unix
EAL: Probing VFIO support...
get_feature(0x01) failed
get_feature(0x02) failed
get_feature(0x04) failed
get_feature(0x05) failed
get_feature(0x07) failed
get log page failed
get log page failed
=====================================================
NVMe over Fabrics controller at 12.12.12.38:4420: nqn.2014-08.org.nvmexpress.discovery
=====================================================
Controller Capabilities/Features
================================
Vendor ID:                             0000
Subsystem Vendor ID:                   0000
Serial Number:
Model Number:
Firmware Version:                      18.04
Recommended Arb Burst:                 0
IEEE OUI Identifier:                   00 00 00
Multi-path I/O
  May have multiple subsystem ports:   No
  May be connected to multiple hosts:  No
  Associated with SR-IOV VF:           No
Max Data Transfer Size:                4194304
NVMe Specification Version (VS):       1.2.1
NVMe Specification Version (Identify): 1.2.1
Maximum Queue Entries:                 128
Contiguous Queues Required:            Yes
Arbitration Mechanisms Supported
  Weighted Round Robin:                Not Supported
  Vendor Specific:                     Not Supported
Reset Timeout:                         500 ms
Doorbell Stride:                       4 bytes
NVM Subsystem Reset:                   Not Supported
Command Sets Supported
  NVM Command Set:                     Supported
Boot Partition:                        Not Supported
Memory Page Size Minimum:              4096 bytes
Memory Page Size Maximum:              4096 bytes
Optional Asynchronous Events Supported
  Namespace Attribute Notices:         Not Supported
  Firmware Activation Notices:         Not Supported
128-bit Host Identifier:               Not Supported

Admin Command Set Attributes
============================
Security Send/Receive:                 Not Supported
Format NVM:                            Not Supported
Firmware Activate/Download:            Not Supported
Namespace Management:                  Not Supported
Device Self-Test:                      Not Supported
Directives:                            Not Supported
NVMe-MI:                               Not Supported
Virtualization Management:             Not Supported
Doorbell Buffer Config:                Not Supported
Abort Command Limit:                   1
Async Event Request Limit:             1
Number of Firmware Slots:              N/A
Firmware Slot 1 Read-Only:             N/A
Firmware Update Granularity:           No Information Provided
Per-Namespace SMART Log:               No
Command Effects Log Page:              Not Supported
Get Log Page Extended Data:            Supported
Telemetry Log Pages:                   Not Supported
Error Log Page Entries Supported:      128
Keep Alive:                            Not Supported

NVM Command Set Attributes
==========================
Submission Queue Entry Size
  Max:                       1
  Min:                       1
Completion Queue Entry Size
  Max:                       1
  Min:                       1
Number of Namespaces:        0
Compare Command:             Not Supported
Write Uncorrectable Command: Not Supported
Dataset Management Command:  Not Supported
Write Zeroes Command:        Not Supported
Set Features Save Field:     Not Supported
Reservations:                Not Supported
Timestamp:                   Not Supported
Volatile Write Cache:        Not Present
Atomic Write Unit (Normal):  1
Atomic Write Unit (PFail):   1
Scatter-Gather List
  SGL Command Set:           Supported
  SGL Keyed:                 Supported
  SGL Bit Bucket Descriptor: Not Supported
  SGL Metadata Pointer:      Not Supported
  Oversized SGL:             Not Supported
  SGL Metadata Address:      Not Supported
  SGL Offset:                Supported

Error Log
=========

Discovery Log Page
==================
Generation Counter:                    4
Number of Records:                     1
Record Format:                         0

Discovery Log Entry 0
----------------------
Transport Type:                        1 (RDMA)
Address Family:                        1 (IPv4)
Subsystem Type:                        2 (NVM Subsystem)
Transport Requirements:
  Secure Channel:                      Not Specified
Port ID:                               0 (0x0000)
Controller ID:                         65535 (0xffff)
Admin Max SQ Size:                     128
Transport Service Identifier:          4420
NVM Subsystem Qualified Name:          nqn.2016-06.io.spdk:cnode1
Transport Address:                     12.12.12.38                                                                                                                                                                                        
Transport Specific Address Subtype - RDMA
  RDMA QP Service Type:                1 (Reliable Connected)
  RDMA Provider Type:                  1 (No provider specified)
  RDMA CM Service:                     1 (RDMA_CM)

**Comment by ChenWang01** [comment]
## nvmf.conf.in:
Set the MaxQueueDepth in configuration file
```
[Nvmf]
  MaxQueuesPerSession 4
  AcceptorPollRate 10000
  MaxQueueDepth 256
```
Then the perf with 128 queuedepth can run successfully.
The value needs to be set greater than or equal to double queuedepth which used run perf.
Example:
```
./perf -q 256
MaxQueueDepth 512 
```

**Comment by changpe1** [comment]
I've submitted a patch to fix the issue: https://review.gerrithub.io/#/c/403256/

**Comment by jimharris** [comment]
This patch should fix the issue – but the same problem will still happen if we specify an I/O size that is bigger than 64KB (our NVMe-oF MDTS).

I’ve posted a comment on how I think we can fix it for all cases.

-Jim

**Comment by WenqianZong** [comment]
I can reproduce this issue with latest spdk version ,and patch https://review.gerrithub.io/#/c/403256/ was abandoned.

**Comment by jimharris** [comment]
Hi Wenqian,

Do you mean that you cannot reproduce this issue?

-Jim

**Comment by wanqunintel** [comment]
chang peng will submit the patch for this

**Comment by changpe1** [comment]
I uploaded a new version https://review.gerrithub.io/#/c/403256/, this should be the right fix.

**Comment by WenqianZong** [comment]
Hi changpeng:

After use patch https://review.gerrithub.io/#/c/403256/ , perf can not be setup. log report like following:

EAL: Detected 72 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.3.11:4420: nqn.2016-06.io.spdk:cnode1
nvme_rdma.c: 211:nvme_rdma_get_event: *ERROR*: Received event: 8(RDMA_CM_EVENT_REJECTED) from CM event channel, but expected event: (RDMA_CM_EVENT_ESTABLISHED)
nvme_rdma.c: 538:nvme_rdma_connect: *ERROR*: RDMA connect error
nvme_rdma.c: 799:nvme_rdma_qpair_connect: *ERROR*: Unable to connect the rqpair
nvme_rdma.c:1339:nvme_rdma_ctrlr_construct: *ERROR*: failed to create admin qpair
nvme.c: 353:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 192.168.3.11
No valid NVMe controllers or AIO devices found

**Comment by WenqianZong** [comment]
This issue verified pass on latest spdk version , I can't reproduce error.
