### ISSUE TITLE
[ocf_remove] jq error, broken pipe

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2562]
00:07:28.878  TELEMETRY: No legacy callbacks, legacy socket not created
00:07:28.878  [2022-06-21 17:35:43.434434] app.c: 575:spdk_app_start: *NOTICE*: Total cores available: 1
00:07:29.158  [2022-06-21 17:35:43.601876] reactor.c: 919:reactor_run: *NOTICE*: Reactor started on core 0
00:07:29.158  [2022-06-21 17:35:43.602959] accel_engine.c: 970:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
00:07:29.158  [2022-06-21 17:35:43.750901] 'OCF Core' volume operations registered
00:07:29.158  [2022-06-21 17:35:43.754074] 'SPDK_block_device' volume operations registered
00:07:29.467   17:35:44	-- common/autotest_common.sh@743 -- # xtrace_enable
00:07:29.467   17:35:44	-- common/autotest_common.sh@744 -- # (( i == 0 ))
00:07:29.467   17:35:44	-- common/autotest_common.sh@748 -- # return 0
00:07:29.467    17:35:44	-- management/remove.sh@79 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_ocf_get_bdevs
00:07:29.467    17:35:44	-- management/remove.sh@79 -- # jq -r '.[] | select(name == "ocfWT") | .name'
00:07:29.728  jq: error: name/0 is not defined at <top-level>, line 1:
00:07:29.728  .[] | select(name == "ocfWT") | .name             
00:07:29.728  jq: 1 compile error
00:07:29.728  Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
00:07:29.728  BrokenPipeError: [Errno 32] Broken pipe
00:07:29.728     17:35:44	-- management/remove.sh@79 -- # trap - ERR
00:07:29.728     17:35:44	-- management/remove.sh@79 -- # print_backtrace
00:07:29.728     17:35:44	-- common/autotest_common.sh@998 -- # [[ hxBET =~ e ]]
00:07:29.728     17:35:44	-- common/autotest_common.sh@998 -- # return 0
00:07:29.728   17:35:44	-- management/remove.sh@79 -- # [[ -z '' ]]
00:07:29.728   17:35:44	-- management/remove.sh@81 -- # trap - SIGINT SIGTERM EXIT
00:07:29.728   17:35:44	-- management/remove.sh@83 -- # killprocess 73757

**Comment by jimharris** [comment]
> Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_78945.html

@peluse - this one needs to be double-checked too.  It is also not related to this report.

Since both of these logs point to different issues, I think this issue needs to be closed.

**Comment by jimharris** [comment]
> @jimharris something strange is happening here, I only did one false positive - why are there 2 "another instance...." messages in here I wonder?

Hmmm, yeah both of those are pointing to the same patch revision.  My guess is it is related to the patch getting marked WIP right after it got retriggered.  So we should ignore the 78945 log failure.

> The first one is what generated this issues, the errors I pasted in are right the from the log so why would you suggest closing the issue? The other one I didn't report, not sure how it got linked to this issue

Can you please double-check that log?  The failing log that I see from the 78939 failure doesn't include any of the text in the original description.

**Comment by peluse** [comment]
@jimharris you got it, I'll triple check in the morning.  Maybe I'm clicking the wrong tabs in Chrome :)
