### ISSUE TITLE
Reading data may cause dirty data（theory）

### ISSUE THREAD

**Issue by SoftBob** [spdk/spdk#2569]
# Bug report

Reading data may cause dirty data

## Expected Behavior

Normal data reading and writing

## Current Behavior
When spdk_nvme_ns_cmd_read is used to read data, the pcie address is used. If the process in the read data exits for some reason and does not reclaim the address, the firmware writes the dirty data to the address space using the pcie address information. If the address is used by another thread at this time, Whether it causes dirty data to appear in other threads

## Possible Solution

cause dirty data

## Steps to Reproduce
1. spdk_nvme_ns_cmd_read  read data
2. the process in the read data exits

**Comment by SoftBob** [comment]
1. The process by spdk_nvme_ns_cmd_read read data
2. firmware write data to pcie address space
3. Process Exits unexpectedly（The firmware does not perceive that the process exits abnormally）
4. The pcie address space is allocated to another process
5. Firmware continues to write data to the pcie address space
6. another process read dirty data

**Comment by changpe1** [comment]
> 1. The process by spdk_nvme_ns_cmd_read read data
> 2. firmware write data to pcie address space
> 3. Process Exits unexpectedly（The firmware does not perceive that the process exits abnormally）
> 4. The pcie address space is allocated to another process
> 5. Firmware continues to write data to the pcie address space
> 6. another process read dirty data

You may raise your concerns in the slack channel for discussion purpose, here we just use it to track issues, I'm going to close this one.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_81336.html
