### ISSUE TITLE
When the host shutdown, SPDK does not have shutdown NVMe SSD

### ISSUE THREAD

**Issue by zhuohaofan** [spdk/spdk#2570]
# Bug report
When the host shutdown, SPDK does not have shutdown NVMe SSD.

## Expected Behavior
When the host shutdown, SPDK should first shutdown NVMe SSD.

## Current Behavior
When the host shutdown, SPDK does not have shutdown NVMe SSD. So SSD calls the abnormal shutdown process.

## Possible Solution
We detected it through the protocol analyzer that SPDK will shutdown SSD during Setup SPDK. This is the normal shutdown process of SSD. Finally, when we shutdown the host, SPDK did not have Shutdown SSD. This can lead to NVMe SSD into an abnormal shutdown process. Frequent abnormal shutdown will reduce the service life of SSD and increase the risk of losing data.
Do you have any suggestions for this?

## Steps to Reproduce

1. setup SPDK
2. identify
3. shutdown host

**Comment by changpe1** [comment]
@zhuohaofan do you mean after the SPDK IDENTIFY application, SPDK doesn't shutdown the SSDs?

**Comment by zhuohaofan** [comment]
> @zhuohaofan do you mean after the SPDK IDENTIFY application, SPDK doesn't shutdown the SSDs?

yes

**Comment by zhuohaofan** [comment]
> For below steps:
> 
> ```
> Steps to Reproduce
> setup SPDK
> identify
> shutdown host
> ```
> 
> Do you mean when SPDK identify tool is running, directly shutdown the Host (server)?

yes

**Comment by changpe1** [comment]
> > For below steps:
> > ```
> > Steps to Reproduce
> > setup SPDK
> > identify
> > shutdown host
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you mean when SPDK identify tool is running, directly shutdown the Host (server)?
> 
> yes

I don't think this is an issue for SPDK, SPDK will always shutdown the controller for normal cases.
