### ISSUE TITLE
doc: document how to use DSA and PMEM together with accel_fw

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2571]
A few things need to be documented:

- there are some flags that need to be set that are only documented in code
- there is a kernel pci driver patch pending that w/o it will not make it possible to use DSA however the workaround is to use the kernel idxd driver which is already documented.  Using this driver avoids the transition form idxd->vfio which is causing us to lose TPH configuration which is used by the fore mentioned flags.

**Comment by peluse** [comment]
Can probably just close this but if not someone else will need to pick it up as I'm moving on...

**Comment by jimharris** [comment]
pmem support is deprecated and being removed.
