### ISSUE TITLE
checkout format reports error

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#2572]
# Bug report
No sure this is a common error or false positive.
Checking Python style... Python formatting errors detected
python/spdk/rpc/iscsi.py:1:1: E302 expected 2 blank lines, found 0
python/spdk/rpc/nvme.py:1:1: E302 expected 2 blank lines, found 0
Checking .sh formatting style... OK

## Steps to Reproduce

Just run ./scripts/check_format.sh
## Context (Environment including OS version, SPDK version, etc.)
5.11.22-100.fc32.x86_64

**Comment by ksztyber** [comment]
What's the version of `pep8`/`pycodestyle` on your system?

**Comment by yidong0635** [comment]
@ksztyber 
`pycodestyle --version`
2.5.0

**Comment by ksztyber** [comment]
I think it's a known issue - see https://github.com/PyCQA/pycodestyle/issues/473 that's been fixed for a while now. On the two systems that I have on hand I have 2.6.0 and 2.7.0 and this doesn't happen on neither one, so I suggest upgrading to a more recent `pycodestyle`.

**Comment by yidong0635** [comment]
@ksztyber Thanks for your help.  That I think I can close it.
