### ISSUE TITLE
Upgrade to spdk v22.05 gives no libssl.so.1.1 file error

### ISSUE THREAD

**Issue by Alvinlst** [spdk/spdk#2573]
# Bug report

I have been using spdk v21.10 and v22.01, which work fine. But when I try to upgrade to v22.05, an error caused by lack of libssl.so.1.1 library happens.

## Expected Behavior

Running spdk_tgt binary should succeed.

## Current Behavior

After building spdk, running the built spdk_tgt binary gives the following error:
spdk_tgt: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

## Possible Solution

As a workaround, I had to comment out those few lines in mk/spdk.common.mk, which check libssl.so.1.1 exist and add it to LDFLAGS.
To fix it, it can either use libssl.so.10 by default instead of libssl.so.1.1, or give developers an option to choose.

## Steps to Reproduce

1. Build spdk on a centos7 machine which has libssl.so.1.1 installed.
2. Run spdk_tgt on a centos7 machine which doesn't have libssl.so.1.1 installed.

## Context (Environment including OS version, SPDK version, etc.)

OS: centos7
SPDK: v22.05

Detailed discussions can be found in slack channel: https://spdk-team.slack.com/archives/CJE4C98G1/p1656564681321359

**Comment by Comphix** [comment]
Hi @Alvinlst , could you check whether below change is related?

https://github.com/spdk/spdk/commit/341924593348c3da2d25338a6ba0881dac6e7c12

**Comment by Alvinlst** [comment]
Hi @Comphix, I think the commit you posted is not related. That is a recently added change which is not part of v22.05 release. I think [this commit](https://github.com/spdk/spdk/commit/468b3e92555955a0da17aa6a25bf2cab809ed652) is the one related.

**Comment by Comphix** [comment]
Thanks for the information.

In this case, will check later whether below change is ok as the SPDK v22.05.x backport fix. And it will also be contained in the current SPDK v22.09 release.

> Hi @Alvinlst , could you check whether below change is related?
> 
> [3419245](https://github.com/spdk/spdk/commit/341924593348c3da2d25338a6ba0881dac6e7c12)
> 
> ```
> configure: add --with-openssl=<dir> option
> Users can now provide custom location for openssl lib.
> 
> Example:
>     ./configure --with-openssl=../openssl-3.0.2
>     LD_LIBRARY_PATH=../openssl-3.0.2 ./build/examples/hello_sock --help
> ```

**Comment by Alvinlst** [comment]
@Comphix Sounds good, thank you!

**Comment by changpe1** [comment]
Closing this issue now as the workaround method is provided.
