### ISSUE TITLE
SPDK/vhost with interrupt mode set will crash when do spdk_top

### ISSUE THREAD

**Issue by Apokleos** [spdk/spdk#2574]
# Bug report
(1) First, I start vhost app with interrupt mode and then start `spdk_top`, 
(2) Then, I will normally create bdev and vhost controller. It will be OK. 
(3) Next, I will delete the new created vhost controller.
(4) Finally, the app `vhost` crashed, with the error message:
```
thread.c:1215:spdk_thread_send_msg: *ERROR*: Thread vhost001.sock is marked as exited.
vhost: thread.c:1857: _on_thread: Assertion `rc == 0' failed.
Aborted (core dumped)
```

## Expected Behavior

The app has the ability to handle(destroy) the exited threads in time;

## Current Behavior
crash

## Possible Solution

1. When I dig into the `spdk_top` program, I found that it will iteratively call commands(framework_get_reactors, thread_get_stats and so on) through RPC, and the exited thread vhost001.sock will  be get, ... finally causing the Assertion failure.

2. Add the process of destroying  exited thread in the function `reactor_interrupt_run`;

My Solution:
```
diff --git a/lib/event/reactor.c b/lib/event/reactor.c
index 5e874a5..015973e 100644
--- a/lib/event/reactor.c
+++ b/lib/event/reactor.c
@@ -892,6 +892,47 @@ reactor_post_process_lw_thread(struct spdk_reactor *reactor, struct spdk_lw_thre
 }
 
 static void
+reactor_maybe_interrupt_run(struct spdk_reactor *reactor)
+{
+	int block_timeout = -1; /* _EPOLL_WAIT_FOREVER */
+	struct spdk_thread	*thread;
+	struct spdk_lw_thread	*lw_thread, *tmp;
+	uint64_t		now;
+	int			rc;
+
+	if(spdk_unlikely(reactor->in_interrupt))
+		spdk_fd_group_wait(reactor->fgrp, block_timeout);
+	else {
+		event_queue_run_batch(reactor);
+	}
+
+	/* If no threads are present on the reactor,
+	 * tsc_last gets outdated. Update it to track
+	 * thread execution time correctly. */
+	if (spdk_unlikely(TAILQ_EMPTY(&reactor->threads))) {
+		now = spdk_get_ticks();
+		reactor->idle_tsc += now - reactor->tsc_last;
+		reactor->tsc_last = now;
+		return;
+	}
+
+	TAILQ_FOREACH_SAFE(lw_thread, &reactor->threads, link, tmp) {
+		thread = spdk_thread_get_from_ctx(lw_thread);
+		rc = spdk_thread_poll(thread, 0, reactor->tsc_last);
+
+		now = spdk_thread_get_last_tsc(thread);
+		if (rc == 0) {
+			reactor->idle_tsc += now - reactor->tsc_last;
+		} else if (rc > 0) {
+			reactor->busy_tsc += now - reactor->tsc_last;
+		}
+		reactor->tsc_last = now;
+
+		reactor_post_process_lw_thread(reactor, lw_thread);
+	}
+}
+
+static void
 reactor_interrupt_run(struct spdk_reactor *reactor)
 {
 	int block_timeout = -1; /* _EPOLL_WAIT_FOREVER */
@@ -956,11 +997,16 @@ reactor_run(void *arg)
 
 	while (1) {
 		/* Execute interrupt process fn if this reactor currently runs in interrupt state */
-		if (spdk_unlikely(reactor->in_interrupt)) {
-			reactor_interrupt_run(reactor);
-		} else {
-			_reactor_run(reactor);
-		}
+		
+		/* Execute process if this reactor currently runs in interrupt state, 
+		* 	or runs in polling state. 
+		* */
+		reactor_maybe_interrupt_run(reactor);
 
 		if (g_framework_context_switch_monitor_enabled) {
 			if ((reactor->last_rusage + g_rusage_period) < reactor->tsc_last) {
```

## Steps to Reproduce

1. set interrupt mode when start vhost app.
2. start spdk_top in another terminal;
3. add vhost controller and then delete it. 
4. the vhost app will crash.

## Context (Environment including OS version, SPDK version, etc.)
1. SPDK v22.05.x
2. OS CentOS7

**Comment by Comphix** [comment]
Thanks @Apokleos , will you also directly raise a patch for these changes to SPDK Gerrit for more review and discussion? Thanks.

**Comment by Apokleos** [comment]
> Thanks @Apokleos , will you also directly raise a patch for these changes to SPDK Gerrit for more review and discussion? Thanks.
>
Thanks @Comphix 
I will raise the patch to Gerrit later today.

**Comment by Apokleos** [comment]
Hi @Comphix I have raised my patch on Gerrit. This is my patch https://review.spdk.io/gerrit/c/spdk/spdk/+/13543
Thank you!

**Comment by Comphix** [comment]
Thanks @Apokleos !

**Comment by changpe1** [comment]
Fix patch for main branch is in https://review.spdk.io/gerrit/c/spdk/spdk/+/13706

**Comment by changpe1** [comment]
Patch has been merged, closing this issue now.
