### ISSUE TITLE
Question: Why does adding --zcopy not improve the performance of bdevperf?

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2575]
## Expected Behavior
In principle, take Malloc bdev as an example, the performance of bdevperf can improve with adding --zcopy in Target.

## Current Behavior

From the results, there is little change in the performance data.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt;color:black'>

<div style='direction:ltr'>

  | Without   --zcopy | With   --zcopy
-- | -- | --
verify<br>randrw | 882.00   IOPS       6.89 MiB/s<br>1503.00 IOPS      11.74 MiB/s | 893.60   IOPS       6.98 MiB/s<br>1531.60 IOPS      11.97 MiB/s
verify<br>randrw | 986.30   IOPS       7.71 MiB/s<br>1477.60 IOPS      11.54 MiB/s | 970.90   IOPS       7.59 MiB/s<br>1436.60 IOPS      11.22 MiB/s

</div>

</body>

</html>

## Possible Solution
If need any other settings?

## Steps to Reproduce
These steps are from test/nvmf/target/zcopy.sh.
```
1./build/bin/nvmf_tgt -i 0 -e 0xFFFF
2./scripts/rpc.py nvmf_create_transport -t tcp -o -c 0 --zcopy
 ./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -m 10
 ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.0.0.2 -s 4420
 ./scripts/rpc.py nvmf_subsystem_add_listener discovery -t tcp -a 10.0.0.2 -s 4420
 ./scripts/rpc.py bdev_malloc_create 32 4096 -b malloc0
 ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 malloc0 -n 1
3./test/bdev/bdevperf/bdevperf --json zcopy.json -t 10 -q 128 -w verify -o 8192
 ./test/bdev/bdevperf/bdevperf --json zcopy.json -t 5 -q 128 -w randrw -M 50 -o 8192
zcopy.json
{
    "subsystems": [
        {
            "subsystem": "bdev",
            "config": [
                {
                    "params": {
                        "name": "Nvme0",
                        "trtype": "tcp",
                        "traddr": "10.0.0.2",
                        "adrfam": "ipv4",
                        "trsvcid": "4420",
                        "subnqn": "nqn.2016-06.io.spdk:cnode1"
                    },
                    "method": "bdev_nvme_attach_controller"
                }
            ]
        }
    ]
}
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK commit 4be6d30438d753b1e883d963e80ed1a3dba51930

**Comment by jimharris** [comment]
Hi @wanghailiangx,

--zcopy is only effective for bdev modules that implement zcopy.

bdev zcopy is useful for bdev modules that have something like a DRAM cache.  Instead of copying data into a buffer provided by the bdev layer or upper layer module (i.e. nvmf), the bdev module can provide pointers directly to the DRAM cache contents instead.

bdev nvme module doesn't support bdev zcopy, since there is no associated DRAM cache on the host.  The malloc bdev module does support bdev zcopy though, you should see a big difference in performance if you specify zcopy with bdevperf and a malloc bdev.

-Jim
