### ISSUE TITLE
[autobuild-vg-autotest]shared object test failed

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#2578]
# Bug report
https://ci.spdk.io/results/autotest-per-patch/builds/79921/archive/autobuild-vg-autotest/build.log
Shared object test failed
## Expected Behavior
Should pass
## Current Behavior
00:08:44.781  real	0m7.368s
00:08:44.781  user	0m45.621s
00:08:44.781  sys	0m37.888s
00:08:47.336  Makefile:16: Skipping building dpdk_governor and gscheduler, due to missing rte_power
00:08:48.717  shared object test failed
00:08:48.717    00:29:37	-- common/autotest_common.sh@970 -- $ trap - ERR
00:08:48.717    00:29:37	-- common/autotest_common.sh@970 -- $ print_backtrace
00:08:48.717    00:29:37	-- common/autotest_common.sh@998 -- $ [[ ehxBET =~ e ]]
00:08:48.717    00:29:37	-- common/autotest_common.sh@1000 -- $ args=('/home/vagrant/autorun-spdk.conf' '/home/vagrant/spdk_repo/spdk/test/make/check_so_deps.sh' 'autobuild_check_so_deps' '/home/vagrant/autorun-spdk.conf' '/home/vagrant/autorun-spdk.conf' 'autobuild_test_suite' 'autobuild' '/home/vagrant/autorun-spdk.conf')
00:08:48.717    00:29:37	-- common/autotest_common.sh@1000 -- $ local args
00:08:48.717    00:29:37	-- common/autotest_common.sh@1002 -- $ xtrace_disable
00:08:48.717    00:29:37	-- common/autotest_common.sh@14 -- $ '[' no '!=' yes ']'
00:08:48.717    00:29:37	-- common/autotest_common.sh@15 -- $ PREV_BASH_OPTS=ehxBET
00:08:48.717    00:29:37	-- common/autotest_common.sh@16 -- $ [[ ehxBET == *\x* ]]
00:08:48.717    00:29:37	-- common/autotest_common.sh@17 -- $ XTRACE_DISABLED=yes
00:08:48.717    00:29:37	-- common/autotest_common.sh@19 -- $ set +x
00:08:48.717  ========== Backtrace start: ==========
00:08:48.717  
00:08:48.717  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:970 -> run_test(["autobuild_check_so_deps"],["/home/vagrant/spdk_repo/spdk/test/make/check_so_deps.sh"],["/home/vagrant/autorun-spdk.conf"])
00:08:48.717       ...
00:08:48.717     965 		timing_enter $test_name
00:08:48.717     966 		echo "************************************"
00:08:48.717     967 		echo "START TEST $test_name"
00:08:48.717     968 		echo "************************************"
00:08:48.717     969 		xtrace_restore
00:08:48.717  => 970 		time "$@"
00:08:48.717     971 		xtrace_disable
00:08:48.717     972 		echo "************************************"
00:08:48.717     973 		echo "END TEST $test_name"
00:08:48.717     974 		echo "************************************"
00:08:48.717     975 		timing_exit $test_name
00:08:48.717       ...
00:08:48.717  in /home/vagrant/spdk_repo/spdk/autobuild.sh:335 -> autobuild_test_suite(["/home/vagrant/autorun-spdk.conf"])
00:08:48.717       ...
00:08:48.717     330 	}
00:08:48.717     331 	
00:08:48.717     332 	function autobuild_test_suite() {
00:08:48.717     333 		run_test "autobuild_check_format" ./scripts/check_format.sh
00:08:48.717     334 		run_test "autobuild_external_code" $rootdir/test/external_code/test_make.sh $rootdir
00:08:48.717  => 335 		run_test "autobuild_check_so_deps" $rootdir/test/make/check_so_deps.sh $1
00:08:48.717     336 		./configure $config_params --without-shared
00:08:48.717     337 		$MAKE $MAKEFLAGS
00:08:48.717     338 		run_test "autobuild_generated_files_check" porcelain_check
00:08:48.717     339 		run_test "autobuild_header_dependency_check" header_dependency_check
00:08:48.718     340 		run_test "autobuild_make_install" $MAKE $MAKEFLAGS install DESTDIR="$SPDK_WORKSPACE" prefix=/usr
00:08:48.718       ...
00:08:48.718  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:970 -> run_test(["autobuild"],["autobuild_test_suite"],["/home/vagrant/autorun-spdk.conf"])
00:08:48.718       ...
00:08:48.718     965 		timing_enter $test_name
00:08:48.718     966 		echo "************************************"
00:08:48.718     967 		echo "START TEST $test_name"
00:08:48.718     968 		echo "************************************"
00:08:48.718     969 		xtrace_restore
00:08:48.718  => 970 		time "$@"
00:08:48.718     971 		xtrace_disable
00:08:48.718     972 		echo "************************************"
00:08:48.718     973 		echo "END TEST $test_name"
00:08:48.718     974 		echo "************************************"
00:08:48.718     975 		timing_exit $test_name
00:08:48.718       ...
00:08:48.718  in /home/vagrant/spdk_repo/spdk/autobuild.sh:378 -> main(["/home/vagrant/autorun-spdk.conf"])
00:08:48.718       ...
00:08:48.718     373 	if [[ $SPDK_TEST_FUZZER -eq 1 ]]; then
00:08:48.718     374 		run_test "autobuild_llvm_precompile" llvm_precompile
00:08:48.718     375 	fi
00:08:48.718     376 	
00:08:48.718     377 	if [[ $SPDK_TEST_AUTOBUILD -eq 1 ]]; then
00:08:48.718  => 378 		run_test "autobuild" autobuild_test_suite $1
00:08:48.718     379 	elif [[ $SPDK_TEST_UNITTEST -eq 1 ]]; then
00:08:48.718     380 		run_test "unittest_build" unittest_build
00:08:48.718     381 	elif [[ $SPDK_TEST_SCANBUILD -eq 1 ]]; then
00:08:48.718     382 		run_test "scanbuild_make" scanbuild_make
00:08:48.718     383 	else
00:08:48.718       ...
00:08:48.718  
00:08:48.718  ========== Backtrace end ==========
00:08:48.718    00:29:37	-- common/autotest_common.sh@1038 -- $ xtrace_enable
00:08:48.718    00:29:37	-- common/autotest_common.sh@1039 -- $ return 0
00:08:48.718  
00:08:48.718  real	3m25.321s
00:08:48.718  user	19m39.984s
00:08:48.718  sys	3m11.207s
00:08:48.718  
00:08:48.718  real	7m7.762s
00:08:48.718  user	37m47.884s
00:08:48.718  sys	6m4.675s
00:08:48.718   00:29:37	-- common/autotest_common.sh@1 -- $ [[ -d /tmp/spdk_1657153305.ZxazAQ ]]
00:08:48.718   00:29:37	-- common/autotest_common.sh@1 -- $ rm -rf /tmp/spdk_1657153305.ZxazAQ
00:08:48.730  [Pipeline] }
00:08:48.755  [Pipeline] // timeout
00:08:48.764  [Pipeline] }
00:08:48.786  [Pipeline] // stage
00:08:48.795  [Pipeline] }
00:08:48.798  ERROR: script returned exit code 1
00:08:48.818  [Pipeline] // catchError
00:08:48.828  [Pipeline] stage
00:08:48.830  [Pipeline] { (Stop VM)
00:08:48.847  [Pipeline] sh
00:08:49.129  + vagrant halt
00:08:53.327  ==> default: Halting domain...
00:08:56.663  [Pipeline] sh
00:08:56.946  + vagrant destroy -f
00:09:01.143  ==> default: Removing domain...
00:09:01.156  [Pipeline] sh
00:09:01.438  + mv output /var/jenkins/workspace/autobuild-vg-autotest/output
00:09:01.448  [Pipeline] }
00:09:01.466  [Pipeline] // stage
00:09:01.473  [Pipeline] }
00:09:01.492  [Pipeline] // dir
00:09:01.499  [Pipeline] }
00:09:01.517  [Pipeline] // catchError
00:09:01.526  [Pipeline] stage
00:09:01.529  [Pipeline] { (Epilogue)
00:09:01.545  [Pipeline] sh
00:09:01.829  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:09:01.844  [Pipeline] archiveArtifacts
00:09:01.852  Archiving artifacts
00:09:01.872  [Pipeline] cleanWs
00:09:01.887  [WS-CLEANUP] Deleting project workspace...
00:09:01.887  [WS-CLEANUP] Deferred wipeout is used...
00:09:01.894  [WS-CLEANUP] done
00:09:01.896  [Pipeline] }
00:09:01.917  [Pipeline] // stage
00:09:01.924  [Pipeline] }
00:09:01.939  [Pipeline] // node
00:09:01.946  [Pipeline] End of Pipeline
00:09:01.977  Finished: FAILURE

**Comment by changpe1** [comment]
https://review.spdk.io/gerrit/#/c/13293/17

**Comment by changpe1** [comment]
This is patch bug, it should be fixed in the patch serial.
