### ISSUE TITLE
[zns-vg-autotest] Hotplug Test Failure

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2579]
# CI Intermittent Failure

************************************
START TEST sw_hotplug
************************************
00:04:42.326   07:52:54	-- common/autotest_common.sh@969 -- # xtrace_enable
00:04:42.326   07:52:54	-- common/autotest_common.sh@970 -- # test/nvme/sw_hotplug.sh
00:04:42.326  * Looking for test storage...
00:04:42.326  * Found test storage at /home/vagrant/spdk_repo/spdk/test/nvme
00:04:42.326    07:52:54	-- common/autotest_common.sh@1514 -- # xtrace_enable
00:04:42.326   07:52:54	-- nvme/sw_hotplug.sh@70 -- # run_hotplug
00:04:42.326   07:52:54	-- nvme/sw_hotplug.sh@45 -- # /home/vagrant/spdk_repo/spdk/scripts/setup.sh
00:04:42.326  0000:00:06.0 (1b36 0010): Skipping denied controller at 0000:00:06.0
00:04:42.585  0000:00:03.0 (1af4 1001): Active devices: mount@vda:vda2,mount@vda:vda3,mount@vda:vda5, so not binding PCI dev
00:04:42.585  0000:00:07.0 (1b36 0010): Already using the uio_pci_generic driver
00:04:42.585   07:52:54	-- nvme/sw_hotplug.sh@47 -- # local hotplug_events=3
00:04:42.585   07:52:54	-- nvme/sw_hotplug.sh@48 -- # local hotplug_wait=6
00:04:42.846    07:52:54	-- nvme/sw_hotplug.sh@49 -- # nvme_in_userspace
00:04:42.846    07:52:54	-- scripts/common.sh@255 -- # local bdf bdfs
00:04:42.846    07:52:54	-- scripts/common.sh@256 -- # local nvmes
00:04:42.846    07:52:54	-- scripts/common.sh@258 -- # [[ -n '' ]]
00:04:42.846    07:52:54	-- scripts/common.sh@261 -- # nvmes=($(iter_pci_class_code 01 08 02))
00:04:42.846     07:52:54	-- scripts/common.sh@261 -- # iter_pci_class_code 01 08 02
00:04:42.846     07:52:54	-- scripts/common.sh@241 -- # local bdf=
00:04:42.846      07:52:54	-- scripts/common.sh@243 -- # iter_all_pci_class_code 01 08 02
00:04:42.846      07:52:54	-- scripts/common.sh@176 -- # local class
00:04:42.846      07:52:54	-- scripts/common.sh@177 -- # local subclass
00:04:42.846      07:52:54	-- scripts/common.sh@178 -- # local progif
00:04:42.846       07:52:54	-- scripts/common.sh@179 -- # printf %02x 1
00:04:42.846      07:52:54	-- scripts/common.sh@179 -- # class=01
00:04:42.846       07:52:54	-- scripts/common.sh@180 -- # printf %02x 8
00:04:42.846      07:52:54	-- scripts/common.sh@180 -- # subclass=08
00:04:42.846       07:52:54	-- scripts/common.sh@181 -- # printf %02x 2
00:04:42.846      07:52:54	-- scripts/common.sh@181 -- # progif=02
00:04:42.846      07:52:54	-- scripts/common.sh@183 -- # hash lspci
00:04:42.846      07:52:54	-- scripts/common.sh@184 -- # '[' 02 '!=' 00 ']'
00:04:42.846      07:52:54	-- scripts/common.sh@185 -- # lspci -mm -n -D
00:04:42.846      07:52:54	-- scripts/common.sh@186 -- # grep -i -- -p02
00:04:42.846      07:52:54	-- scripts/common.sh@187 -- # awk -v 'cc="0108"' -F ' ' '{if (cc ~ $2) print $1}'
00:04:42.846      07:52:54	-- scripts/common.sh@188 -- # tr -d '"'
00:04:42.846     07:52:54	-- scripts/common.sh@243 -- # for bdf in $(iter_all_pci_class_code "$@")
00:04:42.846     07:52:54	-- scripts/common.sh@244 -- # pci_can_use 0000:00:06.0
00:04:42.846     07:52:54	-- scripts/common.sh@10 -- # local i
00:04:42.846     07:52:54	-- scripts/common.sh@13 -- # [[  0000:00:06.0  =~  0000:00:06.0  ]]
00:04:42.846     07:52:54	-- scripts/common.sh@14 -- # return 1
00:04:42.846     07:52:54	-- scripts/common.sh@243 -- # for bdf in $(iter_all_pci_class_code "$@")
00:04:42.846     07:52:54	-- scripts/common.sh@244 -- # pci_can_use 0000:00:07.0
00:04:42.846     07:52:54	-- scripts/common.sh@10 -- # local i
00:04:42.846     07:52:54	-- scripts/common.sh@13 -- # [[  0000:00:06.0  =~  0000:00:07.0  ]]
00:04:42.846     07:52:54	-- scripts/common.sh@17 -- # [[ -z '' ]]
00:04:42.846     07:52:54	-- scripts/common.sh@19 -- # return 0
00:04:42.846     07:52:54	-- scripts/common.sh@245 -- # echo 0000:00:07.0
00:04:42.846    07:52:54	-- scripts/common.sh@264 -- # for bdf in "${nvmes[@]}"
00:04:42.846    07:52:54	-- scripts/common.sh@265 -- # [[ -e /sys/bus/pci/drivers/nvme/0000:00:07.0 ]]
00:04:42.846     07:52:54	-- scripts/common.sh@266 -- # uname -s
00:04:42.846    07:52:54	-- scripts/common.sh@266 -- # [[ Linux == FreeBSD ]]
00:04:42.846    07:52:54	-- scripts/common.sh@269 -- # bdfs+=("$bdf")
00:04:42.846    07:52:54	-- scripts/common.sh@271 -- # (( 1 ))
00:04:42.846    07:52:54	-- scripts/common.sh@272 -- # printf '%s\n' 0000:00:07.0
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@49 -- # nvmes=('0000:00:07.0')
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@49 -- # local nvmes
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@50 -- # local nvme_count=1
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@52 -- # xtrace_disable
00:04:42.846   07:52:54	-- common/autotest_common.sh@14 -- # '[' '' '!=' yes ']'
00:04:42.846   07:52:54	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:04:42.846   07:52:54	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:04:42.846   07:52:54	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:04:42.846   07:52:54	-- common/autotest_common.sh@19 -- # set +x
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@54 -- # xtrace_enable
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@56 -- # trap cleanup EXIT
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@59 -- # hotplug_pid=19192
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@58 -- # remove_attach_helper 3 6
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@15 -- # local hotplug_events=3
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@62 -- # /home/vagrant/spdk_repo/spdk/build/examples/hotplug -i 0 -t 24 -n 3 -r 3 -l warning
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@16 -- # local hotplug_wait=6
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@17 -- # local dev
00:04:42.846   07:52:54	-- nvme/sw_hotplug.sh@23 -- # sleep 6
00:04:43.107  TELEMETRY: No legacy callbacks, legacy socket not created
00:04:43.107  Initializing NVMe Controllers
00:04:43.107  Attaching to 0000:00:07.0
00:04:43.107  Attached to 0000:00:07.0
00:04:43.107  Initialization complete. Starting I/O...
00:04:43.107  QEMU NVMe Ctrl       (12341               ):          5 I/Os completed (+5)
00:04:43.107  
00:04:44.047  QEMU NVMe Ctrl       (12341               ):       7111 I/Os completed (+7106)
00:04:44.047  
00:04:44.987  QEMU NVMe Ctrl       (12341               ):      13950 I/Os completed (+6839)
00:04:44.987  
00:04:46.369  QEMU NVMe Ctrl       (12341               ):      22557 I/Os completed (+8607)
00:04:46.369  
00:04:47.309  QEMU NVMe Ctrl       (12341               ):      29150 I/Os completed (+6593)
00:04:47.309  
00:04:48.250  QEMU NVMe Ctrl       (12341               ):      33402 I/Os completed (+4252)
00:04:48.250  
00:04:48.820   07:53:00	-- nvme/sw_hotplug.sh@25 -- # (( hotplug_events-- ))
00:04:48.820   07:53:00	-- nvme/sw_hotplug.sh@26 -- # for dev in "${nvmes[@]}"
00:04:48.820   07:53:00	-- nvme/sw_hotplug.sh@27 -- # echo 1
00:04:48.820  [2022-07-07 07:53:00.725066] nvme_ctrlr.c:1023:nvme_ctrlr_fail: *ERROR*: [0000:00:07.0] in failed state.
00:04:48.820  Controller removed: QEMU NVMe Ctrl       (12341               )
00:04:48.821  [2022-07-07 07:53:00.726710] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:48.821  [2022-07-07 07:53:00.726898] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:48.821  [2022-07-07 07:53:00.727052] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:49.081  [2022-07-07 07:53:00.727198] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:49.081  unregister_dev: QEMU NVMe Ctrl       (12341               )
00:04:49.081  [2022-07-07 07:53:00.728905] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:49.081  [2022-07-07 07:53:00.729063] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:49.081  [2022-07-07 07:53:00.729214] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:49.081  [2022-07-07 07:53:00.729360] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:04:49.081   07:53:00	-- nvme/sw_hotplug.sh@30 -- # echo 1
00:04:49.081   07:53:00	-- nvme/sw_hotplug.sh@35 -- # for dev in "${nvmes[@]}"
00:04:49.081   07:53:00	-- nvme/sw_hotplug.sh@36 -- # echo 0000:00:07.0
00:04:49.081   07:53:00	-- nvme/sw_hotplug.sh@37 -- # echo 0000:00:07.0
00:04:49.081   07:53:00	-- nvme/sw_hotplug.sh@40 -- # sleep 6
00:04:49.081  Attaching to 0000:00:07.0
00:04:55.731   07:53:06	-- nvme/sw_hotplug.sh@25 -- # (( hotplug_events-- ))
00:04:55.731   07:53:06	-- nvme/sw_hotplug.sh@26 -- # for dev in "${nvmes[@]}"
00:04:55.731   07:53:06	-- nvme/sw_hotplug.sh@27 -- # echo 1
00:04:55.731   07:53:06	-- nvme/sw_hotplug.sh@30 -- # echo 1
00:04:55.732  [2022-07-07 07:53:06.831653] nvme_ctrlr.c:4008:nvme_ctrlr_process_init: *ERROR*: [0000:00:07.0] Ctrlr operation failed with error: -1, ctrlr state: 10[2022-07-07 07:53:06.831796] nvme.c: 702:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:00:07.0
00:04:55.732  [2022-07-07 07:53:06.831868] nvme_ctrlr.c:1023:nvme_ctrlr_fail: *ERROR*: [0000:00:07.0] in failed state.
00:04:55.732  [2022-07-07 07:53:06.831935] nvme_ctrlr.c:1123:nvme_ctrlr_shutdown_async: *ERROR*: [0000:00:07.0] Failed to read the CC register
00:04:55.732   07:53:06	-- nvme/sw_hotplug.sh@35 -- # for dev in "${nvmes[@]}"
00:04:55.732  
00:04:55.732   07:53:06	-- nvme/sw_hotplug.sh@36 -- # echo 0000:00:07.0
00:04:55.732  
00:04:55.732  
00:04:55.732  
00:04:55.732  
00:04:55.732  
00:04:55.732  
00:04:55.732   07:53:06	-- nvme/sw_hotplug.sh@37 -- # echo 0000:00:07.0
00:04:55.732   07:53:06	-- nvme/sw_hotplug.sh@40 -- # sleep 6
00:04:55.732  Attaching to 0000:00:07.0
00:04:55.732  Attached to 0000:00:07.0
00:04:55.992  QEMU NVMe Ctrl       (12341               ):       3718 I/Os completed (+3718)
00:04:55.992  
00:04:57.375  QEMU NVMe Ctrl       (12341               ):       7617 I/Os completed (+3899)
00:04:57.375  
00:04:58.317  QEMU NVMe Ctrl       (12341               ):      11531 I/Os completed (+3914)
00:04:58.317  
00:04:59.260  QEMU NVMe Ctrl       (12341               ):      15443 I/Os completed (+3912)
00:04:59.260  
00:05:00.200  QEMU NVMe Ctrl       (12341               ):      19355 I/Os completed (+3912)
00:05:00.200  
00:05:01.139  QEMU NVMe Ctrl       (12341               ):      23619 I/Os completed (+4264)
00:05:01.139  
00:05:01.139   07:53:12	-- nvme/sw_hotplug.sh@25 -- # (( hotplug_events-- ))
00:05:01.139   07:53:12	-- nvme/sw_hotplug.sh@26 -- # for dev in "${nvmes[@]}"
00:05:01.139   07:53:12	-- nvme/sw_hotplug.sh@27 -- # echo 1
00:05:01.139  [2022-07-07 07:53:12.927138] nvme_ctrlr.c:1023:nvme_ctrlr_fail: *ERROR*: [0000:00:07.0] in failed state.
00:05:01.139  Controller removed: QEMU NVMe Ctrl       (12341               )
00:05:01.139  [2022-07-07 07:53:12.928257] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139  [2022-07-07 07:53:12.928333] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139  [2022-07-07 07:53:12.928403] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139  [2022-07-07 07:53:12.928452] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139  unregister_dev: QEMU NVMe Ctrl       (12341               )
00:05:01.139  [2022-07-07 07:53:12.929783] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139  [2022-07-07 07:53:12.929860] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139  [2022-07-07 07:53:12.929929] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139  [2022-07-07 07:53:12.929981] nvme_pcie_common.c: 748:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
00:05:01.139   07:53:12	-- nvme/sw_hotplug.sh@30 -- # echo 1
00:05:01.139   07:53:12	-- nvme/sw_hotplug.sh@35 -- # for dev in "${nvmes[@]}"
00:05:01.139   07:53:12	-- nvme/sw_hotplug.sh@36 -- # echo 0000:00:07.0
00:05:01.139   07:53:13	-- nvme/sw_hotplug.sh@37 -- # echo 0000:00:07.0
00:05:01.398  Attaching to 0000:00:07.0
00:05:01.398  Attached to 0000:00:07.0
00:05:01.398   07:53:13	-- nvme/sw_hotplug.sh@40 -- # sleep 6
00:05:01.968  QEMU NVMe Ctrl       (12341               ):       3157 I/Os completed (+3157)
00:05:01.968  
00:05:03.348  QEMU NVMe Ctrl       (12341               ):       7052 I/Os completed (+3895)
00:05:03.348  
00:05:04.297  QEMU NVMe Ctrl       (12341               ):      11008 I/Os completed (+3956)
00:05:04.297  
00:05:05.266  QEMU NVMe Ctrl       (12341               ):      15065 I/Os completed (+4057)
00:05:05.266  
00:05:06.207  QEMU NVMe Ctrl       (12341               ):      19033 I/Os completed (+3968)
00:05:06.207  
00:05:07.148  unregister_dev: QEMU NVMe Ctrl       (12341               )
00:05:07.148  Expected inserts 3 != actual inserts 2
00:05:07.148    07:53:18	-- nvme/sw_hotplug.sh@62 -- # trap - ERR
00:05:07.148    07:53:18	-- nvme/sw_hotplug.sh@62 -- # print_backtrace
00:05:07.148    07:53:18	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:05:07.148    07:53:18	-- common/autotest_common.sh@1000 -- # args=()
00:05:07.148    07:53:18	-- common/autotest_common.sh@1000 -- # local args
00:05:07.148    07:53:18	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:05:07.148    07:53:18	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:07.148    07:53:18	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:07.148    07:53:18	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:07.148    07:53:18	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:07.148    07:53:18	-- common/autotest_common.sh@19 -- # set +x

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/79928/archive/zns-vg-autotest/build.log

## Execution failed at

00:05:07.148  ========== Backtrace start: ==========
00:05:07.148  
00:05:07.148  in test/nvme/sw_hotplug.sh:62 -> run_hotplug([])
00:05:07.148       ...
00:05:07.148     57  	
00:05:07.148     58  		remove_attach_helper "$hotplug_events" "$hotplug_wait" &
00:05:07.148     59  		hotplug_pid=$!
00:05:07.148     60  	
00:05:07.148     61  		"$SPDK_EXAMPLE_DIR/hotplug" \
00:05:07.148  => 62  			-i 0 \
00:05:07.148     63  			-t $((hotplug_events * hotplug_wait + hotplug_wait)) \
00:05:07.148     64  			-n $((hotplug_events * nvme_count)) \
00:05:07.148     65  			-r $((hotplug_events * nvme_count)) \
00:05:07.148     66  			-l warning
00:05:07.148     67  	}
00:05:07.148       ...
00:05:07.148  in test/nvme/sw_hotplug.sh:70 -> main([])
00:05:07.148       ...
00:05:07.148     65  			-r $((hotplug_events * nvme_count)) \
00:05:07.148     66  			-l warning
00:05:07.148     67  	}
00:05:07.148     68  	
00:05:07.148     69  	# Run pci bus hotplug test
00:05:07.148  => 70  	run_hotplug
00:05:07.148       ...
00:05:07.148  
00:05:07.148  ========== Backtrace end ==========
00:05:07.148    07:53:18	-- common/autotest_common.sh@1038 -- # xtrace_enable
00:05:07.148    07:53:18	-- common/autotest_common.sh@1039 -- # return 0
00:05:07.148   07:53:18	-- nvme/sw_hotplug.sh@1 -- # cleanup
00:05:07.148   07:53:18	-- nvme/sw_hotplug.sh@10 -- # [[ -e /proc/19192/status ]]
00:05:07.148   07:53:18	-- nvme/sw_hotplug.sh@11 -- # kill 19192
00:05:07.148    07:53:18	-- common/autotest_common.sh@970 -- # trap - ERR
00:05:07.148    07:53:18	-- common/autotest_common.sh@970 -- # print_backtrace
00:05:07.148    07:53:18	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:05:07.148    07:53:18	-- common/autotest_common.sh@1000 -- # args=('test/nvme/sw_hotplug.sh' 'sw_hotplug' '/home/vagrant/autorun-spdk.conf')
00:05:07.148    07:53:18	-- common/autotest_common.sh@1000 -- # local args
00:05:07.148    07:53:18	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:05:07.148    07:53:18	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:05:07.148    07:53:18	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:05:07.148    07:53:18	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:05:07.148    07:53:18	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:05:07.148    07:53:18	-- common/autotest_common.sh@19 -- # set +x
00:05:07.148  ========== Backtrace start: ==========
00:05:07.148  
00:05:07.148  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:970 -> run_test(["sw_hotplug"],["test/nvme/sw_hotplug.sh"])
00:05:07.148       ...
00:05:07.148     965 		timing_enter $test_name
00:05:07.148     966 		echo "************************************"
00:05:07.148     967 		echo "START TEST $test_name"
00:05:07.148     968 		echo "************************************"
00:05:07.148     969 		xtrace_restore
00:05:07.148  => 970 		time "$@"
00:05:07.148     971 		xtrace_disable
00:05:07.148     972 		echo "************************************"
00:05:07.148     973 		echo "END TEST $test_name"
00:05:07.148     974 		echo "************************************"
00:05:07.148     975 		timing_exit $test_name
00:05:07.148       ...
00:05:07.148  in /home/vagrant/spdk_repo/spdk/autotest.sh:221 -> main(["/home/vagrant/autorun-spdk.conf"])
00:05:07.148       ...
00:05:07.148     216 			run_test "nvme_rpc_timeouts" test/nvme/nvme_rpc_timeouts.sh
00:05:07.148     217 			# Only test hotplug without ASAN enabled. Since if it is
00:05:07.148     218 			# enabled, it catches SEGV earlier than our handler which
00:05:07.148     219 			# breaks the hotplug logic.
00:05:07.148     220 			if [ $SPDK_RUN_ASAN -eq 0 ] && [ $(uname -s) = Linux ]; then
00:05:07.148  => 221 				run_test "sw_hotplug" test/nvme/sw_hotplug.sh
00:05:07.148     222 			fi
00:05:07.148     223 		fi
00:05:07.148     224 	
00:05:07.148     225 		if [ $SPDK_TEST_IOAT -eq 1 ]; then
00:05:07.148     226 			run_test "ioat" test/ioat/ioat.sh
00:05:07.148       ...
00:05:07.148  
00:05:07.148  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_79928.html

**Comment by mikeBashStuff** [comment]
Duplicate of #2201

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_81198.html
