### ISSUE TITLE
RBD bdev have a performance degradation with specifying -c for bdev_rbd_create

### ISSUE THREAD

**Issue by Bianyfan** [spdk/spdk#2580]
# Bug report

RBD bdev have a performance degradation with specifying -c for bdev_rbd_create after registering cluster.
## Expected Behavior
The performance of setting -c or not for bde_rbd_create should have the same behavior.

## Current Behavior

When setting option -c for bdev_rbd_create, the performance of RBD bdev decreased.
There are two results for RBD bdev testing.
**With specifying -c:**
 Total                       :   62504.90 IOPS     244.16 MiB/s
**Without specifying -c:**
 Total                       :  115457.47 IOPS     451.01 MiB/s

## Steps to Reproduce

This could be reproduced with bdevperf test tool and ceph cluster. I used 256 pg for my ceph pool with 8 images.
One scenario with specifying -c
1. terminal A: ./test/bdev/bdevperf/bdevperf -q 32 -o 4096 -w randwrite -t 30 -m 0xf -k 0 -C -z
2. terminal B: ./scripts/rpc.py bdev_rbd_register_cluster iscsi_rbd_cluster --config-file /etc/ceph/ceph.conf
3. for number in {0..7};do ./scripts/rpc.py bdev_rbd_create spdktest iscsidev$number 4096 -c iscsi_rbd_cluster; done;
4. PYTHONPATH=$PYTHONPATH:./python/ test/bdev/bdevperf/bdevperf.py  perform_tests

Another one without specifying -c
1. terminal A: ./test/bdev/bdevperf/bdevperf -q 32 -o 4096 -w randwrite -t 30 -m 0xf -k 0 -C -z
2. terminal B: for number in {0..7};do ./scripts/rpc.py bdev_rbd_create spdktest iscsidev$number 4096; done;
3. PYTHONPATH=$PYTHONPATH:./python/ test/bdev/bdevperf/bdevperf.py  perform_tests

## Context (Environment including OS version, SPDK version, etc.)

I'm working on this commit:f656eed6e0853f4fbdc0f2e87e8f1b2e37bd0071
root@icelake-client-5:/home/spdk# uname -a
Linux icelake-client-5 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue https://github.com/spdk/spdk/issues/2189 seems to be related. Could you please take a look at it and if it is close this one ?

**Comment by Bianyfan** [comment]
> [Bug scrub] The issue #2189 seems to be related. Could you please take a look at it and if it is close this one ?

Yes, I can look at this issue. Since I found this problem in the experiments of others, I will reproduce it by myself and report it back if it is a bug.

**Comment by Bianyfan** [comment]
Hi @tomzawadzki , I reproduce this issue locally. Actually, it's not a code bug but about the performance tuning. We provide a way to share the same rados object for different rbd bdev with images to reduce some threads. However, there might be a bottleneck in ceph side. In ceph side, it will create some proprietary threads for every image by default, with two 'io_contxt_pool' threads for I/O request and three 'msgr-worker' threads for thread message. In that case, ceph cluster as backend can't know we will share rados object and all the I/O request from the whole images will be handled by only two 'io_contxt_pool' threads and three 'msgr-worker' threads, which brings a performance degradation. A simple solution is to update the default configuration in ceph side. But do we need to add some notice message to tell customer that their images are sharing rados object like that:https://review.spdk.io/gerrit/c/spdk/spdk/+/13682
Also add @jimharris , do you think it necessary?

**Comment by jimharris** [comment]
> Hi @tomzawadzki , I reproduce this issue locally. Actually, it's not a code bug but about the performance tuning. We provide a way to share the same rados object for different rbd bdev with images to reduce some threads. However, there might be a bottleneck in ceph side. In ceph side, it will create some proprietary threads for every image by default, with two 'io_contxt_pool' threads for I/O request and three 'msgr-worker' threads for thread message. In that case, ceph cluster as backend can't know we will share rados object and all the I/O request from the whole images will be handled by only two 'io_contxt_pool' threads and three 'msgr-worker' threads, which brings a performance degradation. A simple solution is to update the default configuration in ceph side. But do we need to add some notice message to tell customer that their images are sharing rados object like that:https://review.spdk.io/gerrit/c/spdk/spdk/+/13682
> Also add @jimharris , do you think it necessary?

Hi @Bianyfan,

I think it would be better to document the performance tuning considerations in doc/bdev.md.

Adding the NOTICELOG doesn't help the user know anything about why sharing the rados context object is good or bad.  The user already specified the -c option, so the NOTICELOG is not really adding much additional information.  Plus this can add unwanted noise to the log for users that know exactly what they are doing and want the shared rados context behavior.

I think we will find that in some cases using -c is better, in other cases it makes it worse.  And there may be cases where we want something in between - for example, have all of the images share 2 or 4 rados contexts, instead of 1 per image or sharing only 1 context.

The tests listed above are comparing results of using 8 images with 1 rados contexts vs. 8 rados contexts.  What if you use 2 or 4 rados contexts?  I'm also curious about results with 32 or 64 images (but still using the -m 0xF core mask).

-Jim

**Comment by Bianyfan** [comment]
Hi @jimharris ,
It's right that we may print noise spam in the log when customer create many images by sharing 1 rados. Maybe document is a better choice. But as I mentioned before, every new rados object will create 2 io_contxt_pool threads for I/O and 3 msgr-worker threads for thread message by default in ceph side. Obviously, these default threads could be a bottleneck since all the I/O requests are handled by them. We need to update the configuration to create more io_contxt_pool threads and msgr-worker threads. However, users don't have any idea to check status to know how many images they create and how may rados objects they share, for example, 8 images share one rados contexts and 32 images share another one. It brings a problem they don't know how many io_contxt_pool threads and magr-worker threads they need to add. Maybe we can add a RPC api to return these info.
Also it's hard to say in which cases using -c is better, in other cases it makes it worse. Because I think it depends on machine performance. Actually, I set up two experiment environments. In high-performance machines, bottleneck is more likely to occur and I can update configuration to recover the performance. The number of these threads need to fit the machine, it will introduce additional overhead if you create too many threads. 
It's true that performance has a improvement if we have 8 images share 2 or 4 rados contexts, but without increasing by scale. The result of 32 or 64 images with 1 rados contexts have the same performance as 8 images since the thread bottleneck(using the -m 0xF core mask).
In addition, specifying -c means we share the rados object, it reduce some threads in ceph side. I just find io_contxt_pool and msgr-worker threads have a obvious influence, other threads I may need to check with colleague who is familiar with ceph.
As for current behavior, I have another idea. We just provide two modes for creating rbd_bdev, one is created without specifying -c, that means a rados object for every image. Another one is with -c, users can share one rados object with multiple images, but they need update configuration in ceph side. We can add some explanation about the difference in document and customers can decide which one they want to use.

**Comment by jimharris** [comment]
> Hi @jimharris ,
> It's right that we may print noise spam in the log when customer create many images by sharing 1 rados. Maybe document is a better choice. But as I mentioned before, every new rados object will create 2 io_contxt_pool threads for I/O and 3 msgr-worker threads for thread message by default in ceph side.  Obviously, these default threads could be a bottleneck since all the I/O requests are handled by them.  We need to update the configuration to create more io_contxt_pool threads and msgr-worker threads. However, users don't have any idea to check status to know how many images they create and how may rados objects they share, for example, 8 images share one rados contexts and 32 images share another one. It brings a problem they don't know how many io_contxt_pool threads and magr-worker threads they need to add. Maybe we can add a RPC api to return these info.

Can you propose what this RPC would look like?

> Also it's hard to say in which cases using -c is better, in other cases it makes it worse. Because I think it depends on machine performance. Actually, I set up two experiment environments. In high-performance machines, bottleneck is more likely to occur and I can update configuration to recover the performance. The number of these threads need to fit the machine, it will introduce additional overhead if you create too many threads.

I agree, it is hard to say.  I'm not convinced that the rbd bdev module can always return an exact answer of what is best.  The optimal number could depend on a lot of factors - number of images, I/O workload, number of cores available or desired for the extra Ceph threads, etc.

> It's true that performance has a improvement if we have 8 images share 2 or 4 rados contexts, but without increasing by scale. The result of 32 or 64 images with 1 rados contexts have the same performance as 8 images since the thread bottleneck(using the -m 0xF core mask).
> In addition, specifying -c means we share the rados object, it reduce some threads in ceph side. I just find io_contxt_pool and msgr-worker threads have a obvious influence, other threads I may need to check with colleague who is familiar with ceph.
> As for current behavior, I have another idea. We just provide two modes for creating rbd_bdev, one is created without specifying -c, that means a rados object for every image. Another one is with -c, users can share one rados object with multiple images, but they need update configuration in ceph side. We can add some explanation about the difference in document and customers can decide which one they want to use.

Can you share more about "update configuration on ceph side"?  Do you mean configuring number of io_context_pool and msgr-worker threads?

**Comment by Bianyfan** [comment]
Yes, @jimharris you are right. "update configuration on ceph side" means that we add the number of io_context_pool and msgr-worker threads. A simple way is to update the file "/etc/ceph/ceph.conf" and set the value. For example, add the configuration like that:
[global]
librados_thread_count = 3 (The number of io_context_pool thread is set to 3)
ms_async_op_threads = 5 (The number of msgr-worker thread is set to 5)
If you add these commands under global list, it will work on the whole ceph cluster.
As for RPC, I found bdev_get_bdevs showed the difference. There are some differences between register and unregister:
Register:
`    "driver_specific": {
      "rbd": {
        "pool_name": "spdktest",
        "rbd_name": "iscsidev7",
        "config_file": "/etc/ceph/ceph.conf"
      }
    }`
Unregister:
`    "driver_specific": {
      "rbd": {
        "pool_name": "spdktest",
        "rbd_name": "iscsidev7"
      }
    }`
Therefore, maybe add some info in bdev.md is enough. Do you think we need to add more description in RPC?

**Comment by jimharris** [comment]
> Yes, @jimharris you are right. "update configuration on ceph side" means that we add the number of io_context_pool and msgr-worker threads. A simple way is to update the file "/etc/ceph/ceph.conf" and set the value. For example, add the configuration like that:
> [global]
> librados_thread_count = 3 (The number of io_context_pool thread is set to 3)
> ms_async_op_threads = 5 (The number of msgr-worker thread is set to 5)
> If you add these commands under global list, it will work on the whole ceph cluster.
> As for RPC, I want to design bdev_rbd_get_bdevs to check the rbd bdev status. But I found bdev_get_bdevs showed the difference between register and unregister:
> Register:
> ` "driver_specific": { "rbd": { "pool_name": "spdktest", "rbd_name": "iscsidev7", "config_file": "/etc/ceph/ceph.conf" } }`
> Unregister:
> ` "driver_specific": { "rbd": { "pool_name": "spdktest", "rbd_name": "iscsidev7" } }`
> Therefore, maybe add some info in bdev.md is enough. Do you think we need to add more description in RPC?

I think additional info in bdev.md would be very helpful.  I don't think we need any more NOTICELOGs when executing the RPC, but we could reference the "bdev_config_rbd" tag in the jsonrpc.md documentation for the RBD RPCs.

It might even be helpful to add a note to the rpc.py help for the bdev_rbd_create RPC to reference the SPDK documents for additional tuning guidance around the -c parameter.

**Comment by Bianyfan** [comment]
> > Yes, @jimharris you are right. "update configuration on ceph side" means that we add the number of io_context_pool and msgr-worker threads. A simple way is to update the file "/etc/ceph/ceph.conf" and set the value. For example, add the configuration like that:
> > [global]
> > librados_thread_count = 3 (The number of io_context_pool thread is set to 3)
> > ms_async_op_threads = 5 (The number of msgr-worker thread is set to 5)
> > If you add these commands under global list, it will work on the whole ceph cluster.
> > As for RPC, I want to design bdev_rbd_get_bdevs to check the rbd bdev status. But I found bdev_get_bdevs showed the difference between register and unregister:
> > Register:
> > ` "driver_specific": { "rbd": { "pool_name": "spdktest", "rbd_name": "iscsidev7", "config_file": "/etc/ceph/ceph.conf" } }`
> > Unregister:
> > ` "driver_specific": { "rbd": { "pool_name": "spdktest", "rbd_name": "iscsidev7" } }`
> > Therefore, maybe add some info in bdev.md is enough. Do you think we need to add more description in RPC?
> 
> I think additional info in bdev.md would be very helpful. I don't think we need any more NOTICELOGs when executing the RPC, but we could reference the "bdev_config_rbd" tag in the jsonrpc.md documentation for the RBD RPCs.
> 
> It might even be helpful to add a note to the rpc.py help for the bdev_rbd_create RPC to reference the SPDK documents for additional tuning guidance around the -c parameter.

Update the rbd bdev user guide: https://review.spdk.io/gerrit/c/spdk/spdk/+/13771

**Comment by Bianyfan** [comment]
Close this issue since commit has been merged
