### ISSUE TITLE
[build] *** No rule to make target '/usr/local/src/spdk/dpdk/build/lib/librte_vhost.a'

### ISSUE THREAD

**Issue by banhbao916** [spdk/spdk#2582]
# CI Intermittent Failure

Hi, I have issues while trying to build SPDK.  This is the error:

% ./configure --with-fio=/usr/bin --with-nvme-cuse
% make
make[3]: *** No rule to make target '/usr/local/src/spdk/dpdk/build/lib/librte_vhost.a', needed by '/usr/local/src/spdk/build/examples/accel_perf'.  Stop.
make[2]: *** [/usr/local/src/spdk/mk/spdk.subdirs.mk:44: perf] Error 2
make[1]: *** [/usr/local/src/spdk/mk/spdk.subdirs.mk:44: accel] Error 2
make: *** [/usr/local/src/spdk/mk/spdk.subdirs.mk:44: examples] Error 2

## Execution failed at
make[3]: *** No rule to make target '/usr/local/src/spdk/dpdk/build/lib/librte_vhost.a', needed by '/usr/local/src/spdk/build/examples/accel_perf'.  Stop.
make[2]: *** [/usr/local/src/spdk/mk/spdk.subdirs.mk:44: perf] Error 2
make[1]: *** [/usr/local/src/spdk/mk/spdk.subdirs.mk:44: accel] Error 2
make: *** [/usr/local/src/spdk/mk/spdk.subdirs.mk:44: examples] Error 2

**Comment by tomzawadzki** [comment]
Hello @banhbao916 !

Have you gone through https://spdk.io/doc/getting_started.html ? This might be helpful to start with it first, then move on to adding fio plugin and nvme-cuse.

As for the issue at hand, could you provide full log to better understand the failure ?
Probably unrelated, please note that you need to point `--with-fio=` to directory with FIO sources, not the binary.

**Comment by ksztyber** [comment]
Hi @banhbao916, any updates?

**Comment by jimharris** [comment]
Closing issue - @banhbao916, please feel free to reopen if you still see this issue after following the suggestions above.

Thanks,

Jim
