### ISSUE TITLE
[trace bdev]how to trace the specified io device

### ISSUE THREAD

**Issue by dawin2015** [spdk/spdk#2585]
# Bug report
when enable trace function, like: 
`./script/rpc.py trace_enable_tpoint_group bdev`
It will enable bdev’s trace. But how can I just trace the specified io device, like: 
`blktrace -b /dev/sda`
Because I found that enable to trace all io device, it would cause a little performance degradation.
Can just trace one io device?

## Expected Behavior
Trace specified io device, like `-b <bdev_name>`

## Current Behavior
Trace all io device

## Possible Solution
Can add filtering of `bdev_name`  into include/spdk/trace.h `_spdk_trace_record_tsc` , when user specified `bdev_name`?

## Steps to Reproduce

1. ./script/rpc.py trace_enable_tpoint_group bdev

## Context (Environment including OS version, SPDK version, etc.)
OS: Rockylinux 8.5
SPDK: v22.01

**Comment by Comphix** [comment]
Looks like this is a To Do enhancement.

**Comment by Comphix** [comment]
Looking at below function, as it supports extra arguments, looks like we could also output the bdev_name in the caller although now we are not dumping the bdev_name.

For example:

```
bdev_io_submit()
{
		spdk_trace_record_tsc(bdev_io->internal.submit_tsc, TRACE_BDEV_IO_START, 0, 0,
				      (uintptr_t)bdev_io, (uint64_t)bdev_io->type, bdev_io->internal.caller_ctx,
				      bdev_io->u.bdev.offset_blocks, bdev_io->u.bdev.num_blocks); <<<
}

If we also dump the bdev->name, it looks like workable and once all the trace is there, then we could filter by the bdev_name.
bdev_io_submit()
{
		spdk_trace_record_tsc(bdev_io->internal.submit_tsc, TRACE_BDEV_IO_START, 0, 0,
				      (uintptr_t)bdev_io, (uint64_t)bdev_io->type, bdev_io->internal.caller_ctx,
				      bdev_io->u.bdev.offset_blocks, bdev_io->u.bdev.num_blocks, bdev->name); <<<
}

/**
 * Record the current trace state for tracing tpoints. Debug tool can read the
 * information from shared memory to post-process the tpoint entries and display
 * in a human-readable format.
 *
 * \param tsc Current tsc.
 * \param tpoint_id Tracepoint id to record.
 * \param poller_id Poller id to record.
 * \param size Size to record.
 * \param object_id Object id to record.
 * \param ... Extra tracepoint arguments. The number, types, and order of the arguments
 *	      must match the definition of the tracepoint.
 */
#define spdk_trace_record_tsc(tsc, tpoint_id, poller_id, size, object_id, ...)	\
	_spdk_trace_record_tsc(tsc, tpoint_id, poller_id, size, object_id,	\
			       spdk_trace_num_args(__VA_ARGS__), ## __VA_ARGS__)
```

**Comment by Comphix** [comment]
Is this workable for you?

**Comment by dawin2015** [comment]
> Is this workable for you?

yeah! It needs to add `bdev_name` in lib\bdev\bdev.c. 

```
SPDK_TRACE_REGISTER_FN(bdev_trace, "bdev", TRACE_GROUP_BDEV)
{
....
    { "bdev_name", SPDK_TRACE_ARG_TYPE_STR, 40 }
}
```
I will submit a PR.

**Comment by Comphix** [comment]
Thanks. You may follow the https://spdk.io/development/ to submit a patch to https://review.spdk.io/gerrit/dashboard/self

**Comment by dawin2015** [comment]
> Thanks. You may follow the https://spdk.io/development/ to submit a patch to https://review.spdk.io/gerrit/dashboard/self

Thanks for @Comphix 
already submit a patch for that: https://review.spdk.io/gerrit/c/spdk/spdk/+/13823
