### ISSUE TITLE
spdk_idxd_process_events / idxd_poll running for a long time and block other pollers

### ISSUE THREAD

**Issue by chenyou-intel** [spdk/spdk#2586]
# Bug report

I'm testing https://review.spdk.io/gerrit/c/spdk/spdk/+/13546 , which is follow up of https://review.spdk.io/gerrit/c/spdk/spdk/+/9304, and will use DSA to copy data to PMEM. 
Also, I included this workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/12351/ to enable DSA copy on PMEM.

I'm using **bdevperf** to do the basic benchmark testing, but when queue depth is large, 

https://github.com/spdk/spdk/blob/20cd4841f14e2f674277bb8069640f3f185054c4/module/accel/dsa/accel_engine_dsa.c#L269

this function inside `idxd_poll` will hangs for a very long time

and then block all the registered pollers of this thread from execution here:

https://github.com/spdk/spdk/blob/20cd4841f14e2f674277bb8069640f3f185054c4/lib/thread/thread.c#L909-L917

I've read the code of `spdk_idxd_process_events`, found that here
https://github.com/spdk/spdk/blob/20cd4841f14e2f674277bb8069640f3f185054c4/lib/idxd/idxd.c#L1305-L1316
will do the check and remove in a loop for the `chan->ops_outstanding` list, while
https://github.com/spdk/spdk/blob/20cd4841f14e2f674277bb8069640f3f185054c4/lib/idxd/idxd.c#L551-L555
will keep submitting to this list, caused the loop inside `spdk_idxd_process_events` never ends or takes a very long time. 

## Expected Behavior

bdevperf stops when configured running time ends.

## Current Behavior

bdevperf uses way more time than configured.

## Steps to Reproduce

./test/bdev/bdevperf/bdevperf --json ../pmem.json -q 64 -o 4096 -w write -t 20

**Comment by peluse** [comment]
Sorry, 2 more quick things... can you try this with straight master and non PMEM at all?

Also, if what you believe is happening really is you can confirm and potentially workaround it by count how many times we're going through the loop in spdk_idxd_process_events() and lets see what that average and high water marks are.  As a test you can always break out of the loop at some maximum value, for example, 32.

**Comment by chenyou-intel** [comment]
@peluse Thanks for the help! I'll switch to https://review.spdk.io/gerrit/c/spdk/spdk/+/13572 for workaround.

And I've tried to break the loop of spdk_idxd_process_events() by adding a line of code:
```cpp
if(rc >= 32) break;
```
it worked, to break this loop will let other registered pollers be called.
Then the **bdevperf** can exit when configured time runs out, which relies on the `bdevperf_job_drain` function to stop the **bdevperf** 's jobs from keeping submitting I/O to bdev.
https://github.com/spdk/spdk/blob/20cd4841f14e2f674277bb8069640f3f185054c4/test/bdev/bdevperf/bdevperf.c#L955-L959

I guess is that my callback function called here:
https://github.com/spdk/spdk/blob/20cd4841f14e2f674277bb8069640f3f185054c4/lib/idxd/idxd.c#L1396-L1398
cost too much time, then the outstanding list is keep growing if more I/O submitted, so the loop here won't stop.

Anyway, I'll try to create a simple pure DRAM version code snippet to reproduce this issue easily.

**Comment by peluse** [comment]
Great, thanks.  We actually had that break in there over a year ago and determined it wasn't actually needed.  However we have made big changes since then in how IO are submitted and completed and I suspect we just never pushed it hard enough to add it back in.  Please feel free to add a patch that just does that break with a comment that it is to prevent the processing of outstanding commands from starving the rest of the system.  Lets start with breaking when its > DESC_PER_BATCH which is the size of a batch and we can tune it based on reviews (BTW that define is also 32)

**Comment by chenyou-intel** [comment]
@peluse I submitted a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/13685 to address this issue
