### ISSUE TITLE
vfio-pci driver occasionally unloads

### ISSUE THREAD

**Issue by tanabarr** [spdk/spdk#2587]
# Bug report

In DAOS CI after a large number of tests have been run, occasionally the following (and similar variants) is being seen when trying to run either "spdk/scripts/setup.sh" or the same with the reset parameter supplied.

```
0000:2c:00.0 (144d a824): no driver -> nvme
0000:2b:00.0 (144d a824): no driver -> nvme
```

The suggested workaround has been "rmmod vfio_pci && modprobe vfio_pci" which we have integrated into our CI scripts which has reduced the frequency of the issue but not completely removed it.

The issue has been seen on both IceLake and CascadeLake systems and on both Rocky linux 8.5 and CentOS 7.9 distros. 

## Expected Behavior

Driver should not unload.

## Current Behavior

Driver unloads.

## Steps to Reproduce

Switch between kernel and userspace driver 100s of times using the SPDK script.

**Comment by yidong0635** [comment]
@tanabarr  you are using the VMs to setup , right ?
I setup a script to loop 100s setup.sh/reset, but can't catch that issue.
```
0000:2c:00.0 (144d a824): no driver -> nvme
0000:2b:00.0 (144d a824): no driver -> nvme
```
above is the setup.sh log. It's hard to debug such issue.

**Comment by tanabarr** [comment]
This is on bare metal (IceLake platform + Rocky Linux 8.5), @jimharris has acknowledged it's an issue already, perhaps you can add some additional context Jim.

**Comment by tanabarr** [comment]
We see it in our CI occasionally and have introduced the rmmod/modprobe workaround in the test provisioning scripts which has reduced (but not to zero) the frequency of the issue occurring. There is a concern that this may cause high exposure problems in production.

**Comment by yidong0635** [comment]
@jimharris @tanabarr We need to setup this Rocky Linux8.5 locally anyway.  The first step is to reproduce it locally.

**Comment by jimharris** [comment]
> This is on bare metal (IceLake platform + Rocky Linux 8.5), @jimharris has acknowledged it's an issue already, perhaps you can add some additional context Jim.

Hi @tanabarr,

We had a lengthy discussion about this issue in our internal Teams chat - can you add all of that context to this issue?

-Jim

**Comment by tanabarr** [comment]
DAOS related tickets: https://daosio.atlassian.net/browse/DAOS-10608 https://daosio.atlassian.net/browse/DAOS-8848

Teams chat dialogue:

[12/05 16:20] Nabarro, Tom
it says it does but then still can't be accessed

[12/05 16:24] Harris, James R
did this issue just start happening recently?  just wondering if there are any recent changes to scripts, configurations, etc. that might help us narrow this down

[12/05 16:24] Nabarro, Tom
the script output lists 0000:2b:00.0 (144d a824): no driver -> vfio-pci but still not accessible from SPDK

[12/05 16:25] Nabarro, Tom
yes we've been trying to do that as well, we have updated to use the parallel-bind technique with VMD that Samir was working with you guys

[12/05 16:25] Harris, James R
these systems don't have VMD enabled (domain == 0000) so those changes shouldn't matter here

[12/05 16:26] Harris, James R
we already do parallel unbind with VMD disabled - that has been in place for a long time

[12/05 16:26] Nabarro, Tom
ok sorry ignore that then

[12/05 16:27] Nabarro, Tom
I think we might have been seeing this for a little while but not properly identifying/chasing it tbh

[12/05 16:27] Harris, James R
are you only testing with these Samsung SSDs? 

[12/05 16:27] Harris, James R
and if not, do you only see this issue with Samsung SSDs?

[12/05 16:28] Nabarro, Tom
Harris, James Rwas the SSD accessible by the kernel before you did the first kernel->userspace binding change?

I was trying to find this out but I am afraid I don't actually know, that info was lost

[12/05 16:29] Harris, James R
can you try to manually bind this SSD back to the kernel nvme driver?

[12/05 16:30] Harris, James R
see if it works, look for dmesg output, etc.

[12/05 16:30] Nabarro, Tom
how do I do it?

[12/05 16:30] Harris, James R
check linux_bind_driver() function in scripts/setup.sh

[12/05 16:31] Harris, James R
basically something like "echo 0000:2b:00.0 > /sys/bus/pci/drivers/nvme/bind"

[12/05 16:31] Nabarro, Tom
looking, thanks for the tip

[12/05 16:31] Nabarro, Tom
just multitasking a little

[12/05 16:42] Nabarro, Tom
we have seen on both Intel Optane and Samsung

Nabarro, Tom12/05 16:42
we have seen on both Intel Optane and Samsung

Nabarro, Tom12/05 17:00
[root@wolf-219 ~]# echo 0000:2b:00.0 > /sys/bus/pci/drivers/nvme/bind
-bash: echo: write error: No such device
[root@wolf-219 ~]# lspci| grep 2b
2b:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X

Harris, James R12/05 17:04
can you check a different valid bdf?

Harris, James R12/05 17:05
and please verify that the sysfs pathname is correct

Nabarro, Tom12/05 17:22
the others are all listed under /sys/bus/I/drivers/nvme

Nabarro, Tom12/05 17:23
[root@wolf-219 ~]# cat /sys/bus/pci/drivers/nvme/
0000:2c:00.0/ 0000:63:00.0/ 0000:66:00.0/ 0000:a4:00.0/ 0000:df:00.0/ bind remove_id
0000:2d:00.0/ 0000:64:00.0/ 0000:a2:00.0/ 0000:a5:00.0/ 0000:e0:00.0/ module/ uevent
0000:2e:00.0/ 0000:65:00.0/ 0000:a3:00.0/ 0000:de:00.0/ 0000:e1:00.0/ new_id unbind

Harris, James R12/05 17:24
can you try to unbind one of those devices manually, do an ls (the bdf should disappear from that directory), then bind that device manually again

Nabarro, Tom12/05 17:24
issue is with only one of 16 SSDs

Nabarro, Tom12/05 17:24
all the others are behaving normally wrt driver binding

Harris, James R12/05 17:25
right, at this point, I want to make sure that the manual bind works for one of the SSDs that is working

Nabarro, Tom12/05 17:26
sure, doing now, so just doing unbind / bind with the echo method

Harris, James R12/05 17:26
yes

Nabarro, Tom12/05 17:30
works fine

Nabarro, Tom12/05 17:30
[root@wolf-219 ~]# echo 0000:2c:00.0 > /sys/bus/pci/drivers/nvme/unbind
[root@wolf-219 ~]# ls /sys/bus/pci/drivers/nvme/
0000:2d:00.0 0000:63:00.0 0000:65:00.0 0000:a2:00.0 0000:a4:00.0 0000:de:00.0 0000:e0:00.0 bind new_id uevent
0000:2e:00.0 0000:64:00.0 0000:66:00.0 0000:a3:00.0 0000:a5:00.0 0000:df:00.0 0000:e1:00.0 module remove_id unbind
[root@wolf-219 ~]# echo 0000:2c:00.0 > /sys/bus/pci/drivers/nvme/bind
[root@wolf-219 ~]# ls /sys/bus/pci/drivers/nvme/
0000:2c:00.0 0000:2e:00.0 0000:64:00.0 0000:66:00.0 0000:a3:00.0 0000:a5:00.0 0000:df:00.0 0000:e1:00.0 module remove_id unbind
0000:2d:00.0 0000:63:00.0 0000:65:00.0 0000:a2:00.0 0000:a4:00.0 0000:de:00.0 0000:e0:00.0 bind new_id uevent

Harris, James R12/05 17:31
ok, when you do the bind for the bad device, does anything show up in dmesg?

Nabarro, Tom12/05 17:35
nothing

Nabarro, Tom12/05 17:36
tried it a couple of times and literally nothing

Harris, James R12/05 17:36
ok, it still keeps giving you that same "write error" message though?

Nabarro, Tom12/05 17:37
yes

Harris, James R12/05 17:38
sudo lspci -s 2b:00.0 -xxx

Nabarro, Tom12/05 17:39
[root@wolf-219 ~]# sudo lspci -s 2b:00.0 -xxx
2b:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X
00: 4d 14 24 a8 42 01 10 00 00 02 08 01 10 00 00 00
10: 04 00 70 ae 00 00 00 00 00 00 00 00 00 00 00 00
20: 00 00 00 00 00 00 00 00 00 00 00 00 4d 14 14 a8
30: 00 00 00 00 40 00 00 00 00 00 00 00 ff 01 00 00
40: 01 50 03 00 0b 00 00 00 00 00 00 00 00 00 00 00
50: 05 70 8a 00 00 00 00 00 00 00 00 00 00 00 00 00
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
70: 10 b0 02 00 e2 8f 64 10 56 59 00 00 44 70 43 00
80: 40 00 44 10 00 00 00 00 00 00 00 00 00 00 00 00
90: 00 00 00 00 1f 00 01 00 00 00 00 00 1e 00 80 01
a0: 04 00 1e 01 00 00 00 00 00 00 00 00 00 00 00 00
b0: 11 00 3f 00 00 40 00 00 00 30 00 00 00 00 00 00
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
d0: 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00



[root@wolf-219 ~]#

Harris, James R12/05 17:41
sudo lspci -s 2b:00.0 -vvv

Nabarro, Tom12/05 17:42
[root@wolf-219 ~]# sudo lspci -s 2b:00.0 -vvv
2b:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X (prog-if 02 [NVM Express])
Subsystem: Samsung Electronics Co Ltd Device a814
Physical Slot: 5-1
Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr+ Stepping- SERR+ FastB2B- DisINTx-
Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
Interrupt: pin A routed to IRQ 18
NUMA node: 0
IOMMU group: 37
Region 0: Memory at ae700000 (64-bit, non-prefetchable) [size=32K]
Expansion ROM at ae710000 [virtual] [disabled] [size=64K]
Capabilities: [40] Power Management version 3
Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
Status: D3 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
Capabilities: [50] MSI: Enable- Count=1/32 Maskable- 64bit+
Address: 0000000000000000 Data: 0000
Capabilities: [70] Express (v2) Endpoint, MSI 00
DevCap: MaxPayload 512 bytes, PhantFunc 0, Latency L0s unlimited, L1 unlimited
ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 25.000W
DevCtl: CorrErr- NonFatalErr+ FatalErr+ UnsupReq-
RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+ FLReset-
MaxPayload 512 bytes, MaxReadReq 4096 bytes
DevSta: CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
LnkCap: Port #0, Speed 16GT/s, Width x4, ASPM not supported
ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp+
LnkCtl: ASPM Disabled; RCB 64 bytes, Disabled- CommClk+
ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
LnkSta: Speed 16GT/s (ok), Width x4 (ok)
TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
DevCap2: Completion Timeout: Range ABCD, TimeoutDis+ NROPrPrP- LTR-
10BitTagComp+ 10BitTagReq- OBFF Not Supported, ExtFmt- EETLPPrefix-
EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
FRS- TPHComp- ExtTPHComp-
AtomicOpsCap: 32bit- 64bit- 128bitCAS-
DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR- OBFF Disabled,
AtomicOpsCtl: ReqEn-
LnkCap2: Supported Link Speeds: 2.5-16GT/s, Crosslink- Retimer+ 2Retimers+ DRS-
LnkCtl2: Target Link Speed: 16GT/s, EnterCompliance- SpeedDis-
Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
Compliance De-emphasis: -6dB
LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete+ EqualizationPhase1+
EqualizationPhase2+ EqualizationPhase3+ LinkEqualizationRequest-
Retimer- 2Retimers- CrosslinkRes: Upstream Port
Capabilities: [b0] MSI-X: Enable- Count=64 Masked-
Vector table: BAR=0 offset=00004000
PBA: BAR=0 offset=00003000
Capabilities: [100 v2] Advanced Error Reporting
UESta: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
UEMsk: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
UESvrt: DLP- SDES+ TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
CESta: RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr-
CEMsk: RxErr+ BadTLP+ BadDLLP+ Rollover+ Timeout+ AdvNonFatalErr+
AERCap: First Error Pointer: 00, ECRCGenCap+ ECRCGenEn- ECRCChkCap+ ECRCChkEn-
MultHdrRecCap+ MultHdrRecEn- TLPPfxPres- HdrLogCap-
HeaderLog: 00000000 00000000 00000000 00000000
Capabilities: [148 v1] Device Serial Number f1-24-02-11-9b-38-25-00
Capabilities: [178 v1] Secondary PCI Express
LnkCtl3: LnkEquIntrruptEn- PerformEqu-
LaneErrStat: 0
Capabilities: [198 v1] Physical Layer 16.0 GT/s <?>
Capabilities: [1c0 v1] Lane Margining at the Receiver <?>
Capabilities: [3a4 v1] Data Link Feature <?>
Kernel modules: nvme



[root@wolf-219 ~]#

Harris, James R12/05 17:47
can you do that same command, but for a good bdf

Harris, James R12/05 17:48
also please check if this bad bdf has an entry in /sys/bus/pci/devices

looks like more lines for a good one by Nabarro, Tom
Nabarro, Tom12/05 17:50
looks like more lines for a good one

Nabarro, Tom12/05 17:50
[root@wolf-219 ~]# sudo lspci -s 2c:00.0 -vvv
2c:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X (prog-if 02 [NVM Express])
Subsystem: Samsung Electronics Co Ltd Device a814
Physical Slot: 6
Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr+ Stepping- SERR+ FastB2B- DisINTx+
Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
Latency: 0, Cache Line Size: 64 bytes
Interrupt: pin A routed to IRQ 19
NUMA node: 0
IOMMU group: 38
Region 0: Memory at ae600000 (64-bit, non-prefetchable) [size=32K]
Expansion ROM at ae610000 [virtual] [disabled] [size=64K]
Capabilities: [40] Power Management version 3
Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
Capabilities: [50] MSI: Enable- Count=1/32 Maskable- 64bit+
Address: 0000000000000000 Data: 0000
Capabilities: [70] Express (v2) Endpoint, MSI 00
DevCap: MaxPayload 512 bytes, PhantFunc 0, Latency L0s unlimited, L1 unlimited
ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 25.000W
DevCtl: CorrErr- NonFatalErr+ FatalErr+ UnsupReq-
RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+ FLReset-
MaxPayload 512 bytes, MaxReadReq 4096 bytes
DevSta: CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
LnkCap: Port #0, Speed 16GT/s, Width x4, ASPM not supported
ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp+
LnkCtl: ASPM Disabled; RCB 64 bytes, Disabled- CommClk+
ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
LnkSta: Speed 16GT/s (ok), Width x4 (ok)
TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
DevCap2: Completion Timeout: Range ABCD, TimeoutDis+ NROPrPrP- LTR-
10BitTagComp+ 10BitTagReq- OBFF Not Supported, ExtFmt- EETLPPrefix-
EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
FRS- TPHComp- ExtTPHComp-
AtomicOpsCap: 32bit- 64bit- 128bitCAS-
DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR- OBFF Disabled,
AtomicOpsCtl: ReqEn-
LnkCap2: Supported Link Speeds: 2.5-16GT/s, Crosslink- Retimer+ 2Retimers+ DRS-
LnkCtl2: Target Link Speed: 16GT/s, EnterCompliance- SpeedDis-
Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
Compliance De-emphasis: -6dB
LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete+ EqualizationPhase1+
EqualizationPhase2+ EqualizationPhase3+ LinkEqualizationRequest-
Retimer- 2Retimers- CrosslinkRes: Upstream Port
Capabilities: [b0] MSI-X: Enable+ Count=64 Masked-
Vector table: BAR=0 offset=00004000
PBA: BAR=0 offset=00003000
Capabilities: [100 v2] Advanced Error Reporting
UESta: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
UEMsk: DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
UESvrt: DLP- SDES+ TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
CESta: RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr-
CEMsk: RxErr+ BadTLP+ BadDLLP+ Rollover+ Timeout+ AdvNonFatalErr+
AERCap: First Error Pointer: 00, ECRCGenCap+ ECRCGenEn- ECRCChkCap+ ECRCChkEn-
MultHdrRecCap+ MultHdrRecEn- TLPPfxPres- HdrLogCap-
HeaderLog: 00000000 00000000 00000000 00000000
Capabilities: [148 v1] Device Serial Number 6b-78-00-11-9c-38-25-00
Capabilities: [178 v1] Secondary PCI Express
LnkCtl3: LnkEquIntrruptEn- PerformEqu-
LaneErrStat: 0
Capabilities: [198 v1] Physical Layer 16.0 GT/s <?>
Capabilities: [1c0 v1] Lane Margining at the Receiver <?>
Capabilities: [3a4 v1] Data Link Feature <?>
Kernel driver in use: nvme
Kernel modules: nvme



[root@wolf-219 ~]#

Nabarro, Tom12/05 17:52
[root@wolf-219 ~]# /sys/bus/pci/devices/0000\:2
0000:2a:00.0/ 0000:2a:00.1/ 0000:2a:00.2/ 0000:2a:00.4/ 0000:2a:02.0/ 0000:2a:03.0/ 0000:2a:04.0/ 0000:2a:05.0/ 0000:2b:00.0/ 0000:2c:00.0/ 0000:2d:00.0/ 0000:2e:00.0/

Harris, James R12/05 17:55
could you do me a favor and redirect the lspci output for those two devices into two separate files, then do a diff between the two?

Harris, James R12/05 17:56
my feeble brain will miss the differences between the two if I try to do it by sight

[12/05 20:47] Nabarro, Tom
ok, we have a spot in CI where we do that, let me just add it there

[12/05 20:48] Harris, James R
the delay would be roughly 100ms (or whatever time period we find works) times the number of devices

[12/05 20:48] Harris, James R
where number of devices includes anything that SPDK tries to bind to - not just nvme ssds, but could be ioatdma as well 

[12/05 20:51] Nabarro, Tom
sorry are you talking about a delay that I should implement somewhere?

[12/05 20:51] Harris, James R
if we do the delay, it will go into the setup.sh script

[12/05 20:52] Harris, James R
right now, the only workaround you could do is the rmmod + modprobe

[12/05 20:52] Nabarro, Tom
I was just going to add 
rmmod vfio_pci
modprobe vfio_pci

[12/05 20:52] Harris, James R
yes, that should be sufficient to work around your CI failures for now

[12/05 20:52] Nabarro, Tom
after the setup.sh reset

[12/05 20:52] Nabarro, Tom
thanks

[12/05 21:17] Nabarro, Tom
Ray is running the script now

**Comment by jimharris** [comment]
IIRC when we looked at this a while back, there was at least one device that would get unbound from vfio-pci but it's associated iommu_group would not get removed.  Or something like this.  It resulted in being unable to bind the device back to vfio-pci in later iterations.

I don't recall all the specifics.  If you can get me access to a failing system, ping me internally so I can take a look and I'll report out more details here in the ticket.

**Comment by tanabarr** [comment]
I will ask Ray to run the script that you suggested before and try to get a machine in the state so you can investigate. I missed out some of the conversation on teams and having trouble accessing the chat history in any sensible way so I've just screenshot the message search for the given missing messages: 
![teams_conv_1](https://user-images.githubusercontent.com/3277648/179956891-8ddbe62a-ec62-4f17-ae3a-40fea91fb755.png)
![teams_conv_2](https://user-images.githubusercontent.com/3277648/179956898-a8d597f4-6be3-4532-b343-2bfa8e60a8c7.png)
![teams_conv_3](https://user-images.githubusercontent.com/3277648/179956901-027866bd-ecd4-4046-9cd7-d73ef0701c7f.png)

**Comment by yidong0635** [comment]
I have a method to reproduce this kind of issue, I just to want generate this kind of scenario:
```
#/usr/bin/bash
for i in $(seq 1 100);
do
./scripts/setup.sh reset
./scripts/setup.sh &
done
```
that's 100% reproduced, maybe I'm wrong to do this :
the "no driver" can be assigned , here only has one nvme 
```
0000:80:01.5 (8086 0b00): Already using the ioatdma driver
0000:80:01.4 (8086 0b00): vfio-pci -> ioatdma
0000:67:00.0 (8086 0953): no driver -> nvme
0000:00:01.3 (8086 0b00): vfio-pci -> ioatdma
0000:00:01.2 (8086 0b00): Already using the ioatdma driver
0000:00:01.1 (8086 0b00): vfio-pci -> ioatdma
0000:00:01.0 (8086 0b00): Already using the ioatdma driver
0000:00:01.7 (8086 0b00): vfio-pci -> ioatdma
0000:00:01.6 (8086 0b00): vfio-pci -> ioatdma
0000:00:01.5 (8086 0b00): vfio-pci -> ioatdma
0000:00:01.4 (8086 0b00): Already using the ioatdma driver
0000:80:01.3 (8086 0b00): Already using the ioatdma driver
0000:80:01.3 (8086 0b00): ioatdma -> vfio-pci
0000:80:01.2 (8086 0b00): Already using the ioatdma driver
0000:80:01.1 (8086 0b00): Already using the ioatdma driver
0000:80:01.0 (8086 0b00): Already using the ioatdma driver
0000:80:01.7 (8086 0b00): Already using the ioatdma driver
0000:80:01.6 (8086 0b00): Already using the ioatdma driver
0000:80:01.5 (8086 0b00): vfio-pci -> ioatdma
0000:80:01.4 (8086 0b00): Already using the ioatdma driver
0000:67:00.0 (8086 0953): no driver -> nvme
```
I don't know if this is helpful.
if it's helpful, that seems can be improvement from the scritps/setup.sh side to avoid.

**Comment by jimharris** [comment]
This has been narrowed down to a kernel issue which has been fixed in more recent Linux kernels.

A focused script to reproduce this issue would hit the failure on Rocky Linux 8.5 rather consistently (once every few hours).  With Rocky Linux 8.6, no failures have been observed over several days.

Marking this as a 3rd party issue and closing.
