### ISSUE TITLE
Unable to execute FIO with spdk_bdev on Ubuntu 22.04

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2588]
# Bug report

Unable to execute FIO with spdk_bdev.

"LD_PRELOAD=./build/fio/spdk_bdev fio"
fio: IFUNC symbol 'spdk_u64log2' referenced in './build/fio/spdk_bdev' is defined in the executable and creates an unsatisfiable circular dependency.

## Expected Behavior

FIO should execute with the spdk_bdev preloaded and should show the list of options.

"LD_PRELOAD=./build/fio/spdk_bdev fio"
No job(s) defined

fio-3.30
fio [options] [job options] <job file(s)>
  --debug=options       Enable debug logging. May be one/more of:
                        process,file,io,mem,blktrace,verify,random,parse,
                        diskutil,job,mutex,profile,time,net,rate,compress,
                        steadystate,helperthread,zbd
  --parse-only          Parse options only, don't start any IO
  --merge-blktrace-only Merge blktraces only, don't start any IO
  --output              Write output to file

and so on....

## Current Behavior

"LD_PRELOAD=./build/fio/spdk_bdev fio"
fio: IFUNC symbol 'spdk_u64log2' referenced in './build/fio/spdk_bdev' is defined in the executable and creates an unsatisfiable circular dependency.

## Possible Solution

No idea yet. Debugging the issue now !

## Steps to Reproduce

1. ./configure --with-fio=/path/to/fio
2. make -j
3. LD_PRELOAD=./build/fio/spdk_bdev fio
4. LD_PRELOAD=./build/fio/spdk_bdev fio examples/bdev/fio_plugin/example_config.fio

## Context (Environment including OS version, SPDK version, etc.)

Linux Distro : Ubuntu 22.04
GCC version : 11.2.0
Processor Model : AMD Ryzen 9 5900X 12-Core Processor (24 CPUs)

**Comment by krish-reddy** [comment]
Even without any configuration file, the FIO should execute and show a list of options.

But, I am getting
"fio: IFUNC symbol 'spdk_u64log2' referenced in './build/fio/spdk_bdev' is defined in the executable and creates an unsatisfiable circular dependency."
as the output.

**Comment by krish-reddy** [comment]
Even with the configuration file, the FIO shows the below output.

"LD_PRELOAD=./build/fio/spdk_bdev fio examples/bdev/fio_plugin/example_config.fio"

fio: IFUNC symbol 'spdk_u64log2' referenced in './build/fio/spdk_bdev' is defined in the executable and creates an unsatisfiable circular dependency.

**Comment by yidong0635** [comment]
fio: IFUNC symbol 'spdk_u64log2' referenced in './build/fio/spdk_bdev' is defined in the executable and creates an unsatisfiable circular dependency.
From this expression itself:  there're  circular calling the -lspdk_util  libs .  That's to say there are 2 different version of libspdk_util

to solve this need to unify a same path .
Maybe you need to clean all your code and try it compile it again. 
Not sure if your need to specify a LD_LIBRARY_PATH=/path/ , and don't know how it comes .

**Comment by krish-reddy** [comment]
xNVMe library is installed in the system when it was built. FIO links to the xNVMe library if it is available in the system.
Due to this there was a circular dependency.

After removing the xNVMe libraries from the system and rebuilding the FIO, the issue is not reproduced.
FIO could be executed successfully with spdk_bdev on Ubuntu 22.04

**Comment by ajaykumar-mnit** [comment]
> xNVMe library is installed in the system when it was built. FIO links to the xNVMe library if it is available in the system. Due to this there was a circular dependency.
> 
> After removing the xNVMe libraries from the system and rebuilding the FIO, the issue is not reproduced. FIO could be executed successfully with spdk_bdev on Ubuntu 22.04

I was facing the same issue, can you specify more specifically how you removed xNVMe library?

**Comment by krish-reddy** [comment]
Try to run with a FIO built with "./configure --disable-xnvme"

**Comment by ajaykumar-mnit** [comment]
Now it is working fine. Thank you very much.
