### ISSUE TITLE
[vfio_user_fio] Missing nvme drive inside the testing VM

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2589]
ZNS drives were installed today in some of the CI nodes causing this issue to appear.  Drives have been removed from the affected nodes to troubleshoot the issue, hence CI should not be affected anymore. Opening this issue as a placeholder for false positives. 

https://ci.spdk.io/results/autotest-per-patch/builds/80377/archive/vfio-user-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_80554.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_80563.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_80574.html

**Comment by mikeBashStuff** [comment]
Fixed via: 7cd8de9c2bebee2c09a056dbc1d859b916e18e79
