### ISSUE TITLE
[configure] Unsupported linker: ld, Configuration failed

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2594]
# CI Intermittent Failure

```
00:00:30.269   03:05:00	-- common/autotest_common.sh@987 -- $ xtrace_enable
00:00:30.269   03:05:00	-- spdk/autobuild.sh@358 -- $ '[' -n '' ']'
00:00:30.269   03:05:00	-- spdk/autobuild.sh@362 -- $ ./configure --enable-debug --enable-werror --with-idxd --disable-unit-tests --enable-ubsan --enable-asan --enable-coverage --without-isal
00:00:30.269  Unsupported linker: ld
00:00:30.269  
00:00:30.269  
00:00:30.269  Configuration failed
00:00:30.269  
00:00:30.269  
00:00:30.269    03:05:00	-- spdk/autobuild.sh@362 -- $ trap - ERR
00:00:30.269    03:05:00	-- spdk/autobuild.sh@362 -- $ print_backtrace
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/80673/archive/vhost-autotest/build.log

## Execution failed at

```
00:00:30.269  ========== Backtrace start: ==========
00:00:30.269  
00:00:30.269  in /var/jenkins/workspace/vhost-autotest/spdk/autobuild.sh:362 -> main(["autorun-spdk.conf"])
00:00:30.269       ...
00:00:30.269     357 	
00:00:30.269     358 	if [ -n "$SPDK_TEST_NATIVE_DPDK" ]; then
00:00:30.269     359 		run_test "build_native_dpdk" build_native_dpdk
00:00:30.269     360 	fi
00:00:30.269     361 	
00:00:30.270  => 362 	./configure $config_params
00:00:30.270     363 	echo "** START ** Info for Hostname: $HOSTNAME"
00:00:30.270     364 	uname -a
00:00:30.270     365 	$MAKE cc_version
00:00:30.270     366 	$MAKE cxx_version
00:00:30.270     367 	echo "** END ** Info for Hostname: $HOSTNAME"
00:00:30.270       ...
00:00:30.270  
00:00:30.270  ========== Backtrace end ==========
00:00:30.532    03:05:00	-- common/autotest_common.sh@1038 -- $ xtrace_enable
00:00:30.532    03:05:00	-- common/autotest_common.sh@1039 -- $ return 0
00:00:30.532   03:05:00	-- spdk/autobuild.sh@1 -- $ [[ -d /tmp/spdk_1658199900.FzQF42 ]]
00:00:30.532   03:05:00	-- spdk/autobuild.sh@1 -- $ rm -rf /tmp/spdk_1658199900.FzQF42
00:00:30.546  [Pipeline] }
00:00:30.567  [Pipeline] // timeout
00:00:30.576  [Pipeline] }
00:00:30.596  [Pipeline] // stage
00:00:30.605  [Pipeline] }
00:00:30.608  ERROR: script returned exit code 1
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_80673.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80663.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80661.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80662.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80668.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80667.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80664.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_80666.html

**Comment by mikeBashStuff** [comment]
This issue was occurring on the node which should not be enabled in the CI pool (SM5) - @karlatec already disabled it so the issue should be gone.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_80680.html

**Comment by mikeBashStuff** [comment]
SM5 was disabled from the CI pool so closing this issue.
