### ISSUE TITLE
[nvmf_discovery] Possible timeout

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2598]
0:17:19.498   22:35:20	-- host/timeout.sh@132 -- # sleep 5
00:17:24.778   22:35:25	-- host/timeout.sh@133 -- # cat /home/vagrant/spdk_repo/spdk/test/nvmf/host/trace.txt
00:17:24.778  Attaching 5 probes...
00:17:24.778    22:35:25	-- host/timeout.sh@136 -- # grep -c 'reconnect delay bdev controller NVMe0'
00:17:24.778     22:35:25	-- host/timeout.sh@136 -- # trap - ERR
00:17:24.778     22:35:25	-- host/timeout.sh@136 -- # print_backtrace
00:17:24.778     22:35:25	-- common/autotest_common.sh@998 -- # [[ hxBET =~ e ]]
00:17:24.778     22:35:25	-- common/autotest_common.sh@998 -- # return 0
00:17:24.778   22:35:25	-- host/timeout.sh@136 -- # (( 0 != 2 ))
00:17:24.778   22:35:25	-- host/timeout.sh@137 -- # false
00:17:24.778    22:35:25	-- host/timeout.sh@137 -- # trap - ERR
00:17:24.778    22:35:25	-- host/timeout.sh@137 -- # print_backtrace
00:17:24.778    22:35:25	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:17:24.778    22:35:25	-- common/autotest_common.sh@1000 -- # args=('--transport=tcp')
00:17:24.778    22:35:25	-- common/autotest_common.sh@1000 -- # local args
00:17:24.778    22:35:25	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:17:24.778    22:35:25	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:17:24.778    22:35:25	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:17:24.778    22:35:25	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:17:24.778    22:35:25	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:17:24.778    22:35:25	-- common/autotest_common.sh@19 -- # set +x
00:17:24.778  ========== Backtrace start: ==========
00:17:24.778  
00:17:24.778  in test/nvmf/host/timeout.sh:137 -> main(["--transport=tcp"])

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_80950.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_80956.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_80953.html

**Comment by jimharris** [comment]
Duplicated of #2595.
