### ISSUE TITLE
SPDK can't attach nvme device with make config CONFIG_PCIACCESS=n, which using DPDK PCI probe.

### ISSUE THREAD

**Issue by gang2015** [spdk/spdk#26]
When building with make config CONFIG_PCIACCESS=n, e.g. adopting DPDK pci probe, it can't attach nvme device. Does anyone make it work with DPDK rte_eal_pci_probe() on uio_pci_generic?

It seems DPDK try to parse maps folders under /sys/class/uio_pci_generic, and they don't exist. So DPDK skip mmap PCI BARs.

In pci_uio_map_resource(),  nb_maps gets 0 from pci_uio_get_mappings(). And it skip any mmap for uio deivce. That results in nvme_attach() failure due to NULL virtual address in mem_resource[], later.

/* collect info about device mappings */
nb_maps = pci_uio_get_mappings(dirname, uio_res->maps,
      RTE_DIM(uio_res->maps));
if (nb_maps < 0) {
rte_free(uio_res);
return nb_maps;
}

With default CONFIG_PCIACCESS=y, no such problem with the same setup.
Because libpciaccess probe pci by parsing /sys/bus/0001:001:00.0/resource instead of maps folders under /sys/class/uio_pci_generic

All tests are based on example app nvme_manage.

**Comment by optimistyzy** [comment]
While  CONFIG_PCIACCESS=n,  It seems that you need to bind those devices into uio_pci_generic first.

**Comment by benlwalker** [comment]
Our testing is showing that this is working - you just need to run scripts/setup.sh first.
