### ISSUE TITLE
 spdk_mem_register doesnt work when the virtual address is not backed by physical page

### ISSUE THREAD

**Issue by kreuzerkrieg** [spdk/spdk#260]
spdk_mem_register fails to register memory range when the address is not backed by physical page. Theoretically, vtophys_get_paddr_pagemap takes care of such a case, here
```
paddr = rte_mem_virt2phy((void *)vaddr);
if (paddr == 0) {
		/*
		 * The vaddr was valid but returned 0.  Touch the page
		 * to ensure a backing page gets assigned, then call
		 * rte_mem_virt2phy() again.
		 */
		rte_atomic64_read((rte_atomic64_t *)vaddr);
		paddr = rte_mem_virt2phy((void *)vaddr);
	}

```
 in fact, rte_mem_virt2phy does not have a codepath which returns zero.

**Comment by jimharris** [comment]
This situation only happens when memory is allocated by another process (typically QEMU) and a file descriptor for that memory is passed to the SPDK process (typically as part of vhost SET_MEM_TABLE message).  When SPDK registers that memory, there are cases where /proc/self/pagemap hasn’t yet been updated – then touching the page ensures the page is assigned in /proc/self/pagemap.

So there’s no bug here, but the comment could be cleaned up to more precisely describe this situation.

-Jim

**Comment by kreuzerkrieg** [comment]
the point is that the touching never occurs. Sounds like a bug, no?

**Comment by jimharris** [comment]
rte_atomic64_read is the touch.

Regarding the comment that rte_mem_virt2phy has no codepath which returns zero - it may never explicitly return zero, but for this specific case, the /proc/self/pagemap lookup results in zero which gets returned to the caller.

**Comment by kreuzerkrieg** [comment]
Could you please point out what code takes care of this case? I see that here the page is zero:
```
if ((page & 0x7fffffffffffffULL) == 0) 
	return RTE_BAD_IOVA;
```
and it returns -1
Jim, this case is not something I think may happen, it actually happens in my code when NVMe runs in cloned process, when the page is not backed by physical one the rte_mem_virt2phy returns -1 and the page is never touched by rte_atomic64_read, so it registering the memory simply doesnt work.

**Comment by jimharris** [comment]
Hmmm – I’ll need to take a look at the DPDK logs – this must have changed at some point.  Clearly we’re not hitting the problem with vhost anymore either or we would have found this sooner.

If instead of comparing against 0 in vtophys_get_paddr_pagemap, it compares against RTE_BAD_IOVA instead, does that help in your case?

**Comment by kreuzerkrieg** [comment]
Actually I've changed it in the DPDK code, to something like
if ((page & 0x7fffffffffffffULL) == 0) {
	if (page == 0) {
		return 0;
	} else {
		return RTE_BAD_IOVA;
	}
}
and it solved my problem.
Actually, symptoms are quite odd, when I clone and register memory, registration iterates over the addresses and doing well until it reaches 2Gb, from this point on, the /proc/self/pagemap does not contain the mapping, the page will be zero. Just wondering what is the 2Gb magic limit means? `clone` side effect?

**Comment by jimharris** [comment]
It’s a great question – I’m not exactly sure.

I’m trying to think if there’s any harm in checking for RTE_BAD_IOVA in the SPDK code.  If user tries to register some completely invalid memory region, touching the page could trigger a seg fault – but in my mind that’s what you get if you try to register invalid memory.

Then in the “valid” case (like yours), SPDK would touch the page and you could avoid having to modify the DPDK code.

**Comment by kreuzerkrieg** [comment]
I wasnt sure too how to approach this problem. Returning 0 from rte_mem_virt2phy when the page is 0 sounds like more right think to do and not to try and touch just any invalid address you get from rte_mem_virt2phy. But its up to you, guess you know the flow better than I.

**Comment by jimharris** [comment]
How will DMA operations work to this address if the PA/IOVA gets interpreted as zero?

**Comment by kreuzerkrieg** [comment]
Hm... good point, so I guess, my solution is no-go, and yours is more correct. Meanwhile I will change my fix to the one you suggested. Thanks for your assistance!

**Comment by jimharris** [comment]
No problem – thanks for pointing this out.

**Comment by jimharris** [comment]
Submitted https://review.gerrithub.io/#/c/spdk/spdk/+/410071/ to fix this issue.

**Comment by wanqunintel** [comment]
@kreuzerkrieg would you verify it and update? thanks.

**Comment by kreuzerkrieg** [comment]
Unfortunately, I dont have any NVMe environment at hand now. Sorry :(

**Comment by wanqunintel** [comment]
@kreuzerkrieg When you have any update and got the environment, pls. just update it, thx.

**Comment by kreuzerkrieg** [comment]
I dont think I will have an update on it in foreseeable future. I'm quite out of NVMe business for now.

**Comment by jimharris** [comment]
No problem.  We will take care of updating the issue.
