### ISSUE TITLE
[bdev_error] Process was expected to fail but did not

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2611]
00:05:58.488  [2022-07-27 19:08:53.032963] app.c: 665:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
00:05:58.488  Connection closed with partial response:
00:05:58.488  
00:05:58.488  
00:05:59.426   19:08:53	-- bdev/blockdev.sh@409 -- # kill -0 17341
00:05:59.426   19:08:53	-- bdev/blockdev.sh@410 -- # echo 'Process still exists, but was expected to fail due to IO error. Pid: 17341'
00:05:59.426  Process still exists, but was expected to fail due to IO error. Pid: 17341
00:05:59.426   19:08:53	-- bdev/blockdev.sh@411 -- # exit 1
00:05:59.426  
00:05:59.426  real	0m10.142s
00:05:59.426  user	0m8.296s
00:05:59.426  sys	0m0.732s
00:05:59.426    19:08:53	-- common/autotest_common.sh@970 -- # trap - ERR
00:05:59.426    19:08:53	-- common/autotest_common.sh@970 -- # print_backtrace

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81366.html

**Comment by Comphix** [comment]
Looking at this issue

**Comment by Comphix** [comment]
Patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/13804

Also started a long iteration locally.

**Comment by jimharris** [comment]
Hi @Comphix, this patch will probably work, but I provided an alternative solution on Gerrit - please take a look when you have a chance.  Thanks!

**Comment by Comphix** [comment]
Thanks. Updated as suggested.

**Comment by jimharris** [comment]
Patch merged.
