### ISSUE TITLE
I/O queue initialized quickly

### ISSUE THREAD

**Issue by guzebing** [spdk/spdk#2612]
# Bug report

In nvme lib module, when initialize I/O queue's free state, set one bit once. When the number of queues is 1024, and the function has a mutex, sometimes the function may delay.

## Expected Behavior

May be set all queues once.

**Comment by changpe1** [comment]
@guzebing the IO queue pair resources are allocated on demand, SPDK only initialize one IO queue when users ask for it, it's a great waste to initialize all IO queue pairs at once.

**Comment by jimharris** [comment]
Hi @guzebing,

Can you provide more details on the issue you are seeing?  Is there a specific use case that shows some kind of performance degradation?

Thanks,

Jim

**Comment by changpe1** [comment]
@guzebing I'm going to close this one, feel free to re-open it if you find something wrong in SPDK.
