### ISSUE TITLE
nvme_tcp_qpair_check_timeout not called when spdk_sock_flush fails

### ISSUE THREAD

**Issue by LiadOz** [spdk/spdk#2614]
# Bug report

In the function **nvme_tcp_qpair_process_completions** in the case the socket was closed the **spdk_sock_flush** will return a negative value and the code won't reach **nvme_tcp_qpair_check_timeout**, This prevents checking for timeouts on sent commands

## Expected Behavior

**nvme_tcp_qpair_check_timeout** should be called when **spdk_sock_flush** fails.

## Current Behavior

**spdk_sock_flush**  returns before reaching **nvme_tcp_qpair_check_timeout**

## Possible Solution

calling **nvme_tcp_qpair_check_timeout** if rc < 0

**Comment by jimharris** [comment]
Hi @LiadOz,

I agree with your assessment on this - would you like to submit a patch for it?  I'm happy to post one instead of you would prefer.

-Jim

**Comment by LiadOz** [comment]
I will submit a patch, thanks!

**Comment by LiadOz** [comment]
patch is waiting for review https://review.spdk.io/gerrit/c/spdk/spdk/+/13891
