### ISSUE TITLE
[[vfio_user_fio] failure in clean_vfio_user

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2616]
VBE mode info request: f
00:14:56.991  VBE mode info request: 10
00:14:56.991  VBE mode info request: 11
00:14:56.991  VBE mode info request: 12
00:14:56.991  VBE mode info request: 13
00:14:56.991  VBE mode info request: 6a
00:14:56.991  set VGA mode 3
00:14:56.991  WARN: ================
00:14:56.991   18:50:21	-- vhost/common.sh@934 -- # xtrace_enable
00:14:56.991   18:50:21	-- vhost/common.sh@935 -- # return 1
00:14:56.991    18:50:21	-- vfio_user_fio/vfio_user_fio.sh@49 -- # clean_vfio_user '' 49
00:14:56.991    18:50:21	-- vfio_user/common.sh@8 -- # trap - ERR
00:14:57.251    18:50:21	-- vfio_user/common.sh@9 -- # print_backtrace
00:14:57.251    18:50:21	-- common/autotest_common.sh@998 -- # [[ ehxBET =~ e ]]
00:14:57.251    18:50:21	-- common/autotest_common.sh@1000 -- # args=('49' '')
00:14:57.251    18:50:21	-- common/autotest_common.sh@1000 -- # local args
00:14:57.251    18:50:21	-- common/autotest_common.sh@1002 -- # xtrace_disable
00:14:57.251    18:50:21	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:14:57.251    18:50:21	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:14:57.251    18:50:21	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:14:57.251    18:50:21	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:14:57.251    18:50:21	-- common/autotest_common.sh@19 -- # set +x
00:14:57.251  ========== Backtrace start: ==========
00:14:57.251  
00:14:57.251  in /var/jenkins/workspace/vfio-user-autotest/spdk/test/vfio_user/common.sh:9 -> clean_vfio_user([""],["49"])
00:14:57.251       ...
00:14:57.251     4   	# Verify vfio-user support of qemu.
00:14:57.251     5   	QEMU_BIN="/usr/local/qemu/vfio-user-v0.93/bin/qemu-system-x86_64"
00:14:57.251     6   	
00:14:57.251     7   	function clean_vfio_user() {
00:14:57.251     8   		trap - ERR
00:14:57.251  => 9   		print_backtrace
00:14:57.251     10  		set +e
00:14:57.251     11  		error "Error on $1 $2"
00:14:57.251     12  		vm_kill_all
00:14:57.251     13  		vhost_kill 0
00:14:57.251     14  		exit 1
00:14:57.251       ...
00:14:57.251  in /var/jenkins/workspace/vfio-user-autotest/spdk/test/vfio_user/vfio_user_fio/vfio_user_fio.sh:49 -> main([])
00:14:57.251       ...
00:14:57.251     44  		vm_setup --disk-type=vfio_user --force=$i --os=$VM_IMAGE --disks="$i"
00:14:57.251     45  		used_vms+=" $i"
00:14:57.251     46  	done
00:14:57.251     47  	
00:14:57.251     48  	vm_run $used_vms
00:14:57.251  => 49  	vm_wait_for_boot 60 $used_vms
00:14:57.252     50  	
00:14:57.252     51  	timing_exit launch_vms
00:14:57.252     52  	
00:14:57.252     53  	timing_enter run_vm_cmd
00:14:57.252     54  	
00:14:57.252       ...
00:14:57.252  
00:14:57.252  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_81619.html

**Comment by jimharris** [comment]
This looks like a dup of #2530, which was closed.  I've reopened #2530 and closing this issue.

@changpe1 - can you take a look at #2530 again?  Thanks.
