### ISSUE TITLE
[devices] WFP16 has no free nvme drives

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#2619]
# CI Intermittent Failure

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/81547/archive/nvme-phy-autotest/build.log

## Execution failed at

> 00:01:58.801  ========== Backtrace start: ==========
00:01:58.801  
00:01:58.801  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/setup/devices.sh:203 -> main([])
00:01:58.801       ...
00:01:58.801     198 		if ! block_in_use "${block##*/}" && (($(sec_size_to_bytes "${block##*/}") >= min_disk_size)); then
00:01:58.801     199 			blocks+=("${block##*/}")
00:01:58.801     200 			blocks_to_pci["${block##*/}"]=$pci
00:01:58.801     201 		fi
00:01:58.801     202 	done
00:01:58.801  => 203 	((${#blocks[@]} > 0))
00:01:58.801     204 	
00:01:58.801     205 	declare -r test_disk=${blocks[0]}
00:01:58.801     206 	
00:01:58.801     207 	run_test "nvme_mount" nvme_mount
00:01:58.801     208 	run_test "dm_mount" dm_mount

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_81547.html

**Comment by ksztyber** [comment]
This happened just as the CI was being brought up online after the shutdown and I know there were some small issues with it, so this is probably related. I've logged into that machine and everything looks fine now. But let's keep it open for a while to have something to point the false positives at.

**Comment by mikeBashStuff** [comment]
Just to add a note - when this particular node (WFP16) was brought back online it was noticed  that the active namespace was missing from the underlying nvme drive. This was fixed yesterday, hence the issue should be gone (the block device is now properly picked up by the tests). But as @ksztyber suggested let's keep this issue open just in case more patches got affected.

**Comment by mikeBashStuff** [comment]
I think it's safe to close this one. In case similar failure happens, will reopen it.
