### ISSUE TITLE
directly use dpdk mempool failed.

### ISSUE THREAD

**Issue by clicx** [spdk/spdk#262]
I build app by myself, and link with dpdk_mempool but always encounter the following problems:

LFLAGS = -lrt -Wall -lm -lc -laio -ldl -lpthread -libverbs -lrdmacm -lpciaccess -lnuma -lrte_mempool -lrte_mempool_ring -lrte_ring -lrte_eal -lrte_pci -lrte_bus_pci -ldpdk -luuid -Ldpdk/build/lib

lib/event/reactor.c: 685:spdk_reactors_init: *ERROR*: spdk_event_mempool creation failed
lib/event/app.c: 385:spdk_app_start: *ERROR*: Invalid reactor mask.

Did I miss something?

**Comment by jimharris** [comment]
Hi,

More information is needed to help here.


1)       Which app did you build and run?

2)       If this is your own app that you created, can you post the source code of your app?

3)       Can you post a complete log?

This will help others be able to provide assistance.

Thanks,

-Jim

**Comment by clicx** [comment]
I'm trying to create an app, now try to use nvmf app for testing, its the same result, only changes are use my own makefile to build, CFLAGS:
-Wall -Wextra -Wl,-z,relro,-z,now -Wl,-z,noexecstack -march=native -std=gnu99 -D_LINUX -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -m64 -mssse3 -D_GNU_SOURCE -D_REENTRANT -fPIC

I think I maybe miss some flags to build it?

Starting SPDK v18.04-pre / DPDK 17.11.0 initialization...
[ DPDK EAL parameters: nvmf -c 0x1 --file-prefix=spdk_pid91771 ]
EAL: Detected 2 lcore(s)
EAL: Probing VFIO support...
lib/event/app.c: 377:spdk_app_start: *NOTICE*: Total cores available: 1
lib/event/reactor.c: 643:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
lib/event/reactor.c: 664:spdk_reactors_init: *NOTICE*: Event_mempool creation failed on preferred socket 0.
lib/event/reactor.c: 685:spdk_reactors_init: *ERROR*: spdk_event_mempool creation failed
lib/event/app.c: 385:spdk_app_start: *ERROR*: Invalid reactor mask.

**Comment by Comphix** [comment]
Have you run the ./scripts/setup.sh first?

Looks like not enough memory configured there.

**Comment by clicx** [comment]
Yes, memory and hugepages are good, as the one (./app/nvmf_tgt/nvmf_tgt) which built from sdpk can work. And all c codes are same, therefor I think I should lack of something in build flags.

**Comment by jimharris** [comment]
You need to use the whole-archive linker flags.  Otherwise many constructor functions will get removed from the final application since they are not directly referenced.

When you build SPDK, add Q= at the beginning of your make line – then you can see the full linker arguments used to link one of the working SPDK applications.

-Jim

**Comment by clicx** [comment]
that does work, many thanks.

**Comment by vonnyfly** [comment]
Hi, I have the same issue when writing my own target with C++.
Which GCC options affects?
I have tried all, it still doesn't work.
```
-Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-declarations -fno-strict-aliasing  -Wl,-z,relro,-z,now -Wl,-z,noexecstack

reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
count: 131071, ele_size: 32, cache_size: 512 
reactor.c: 739:spdk_reactors_init: *NOTICE*: Event_mempool creation failed on preferred socket 0.
count: 131071, ele_size: 32, cache_size: 512 
reactor.c: 760:spdk_reactors_init: *ERROR*: spdk_event_mempool creation failed

```

**Comment by optimistyzy** [comment]
you have not link the related dpdk mem related ilb in your make file，so it
failed， can you refer the cmake file in ceph to use spdk

2018年8月23日星期四，Feng,Li <notifications@github.com> 写道：
