### ISSUE TITLE
json_parse_ut param error in calling function: spdk_json_parse

### ISSUE THREAD

**Issue by zerodistance00** [spdk/spdk#2623]
# Bug report

the json_parse_ut.c has a wrong param in calling function 'spdk_json_parse', the sizeof(g_vals) should be the num of array, not the num of bytes. see follow:

CU_ASSERT(spdk_json_parse(g_buf, sizeof(in) - 1, g_vals, sizeof(g_vals), &g_end, flags | SPDK_JSON_PARSE_FLAG_DECODE_IN_PLACE) == num_vals);

## Possible Solution

fix sizeof(g_vals) to num of array.

**Comment by Comphix** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/13841 is the fix from @zerodistance00 , thanks!
