### ISSUE TITLE
[ test/sma/sma.sh ] Run test/sma/vhost_blk.sh in sma.sh fail, qemu-system-x86_64: -device ide-hd,drive=os_disk,bootindex=0: Device needs media, but drive is empty

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2624]
# Bug report

When run test/sma/vhost_blk.sh, qemu command fail
qemu-system-x86_64: -device ide-hd,drive=os_disk,bootindex=0: Device needs media, but drive is empty

## Steps to Reproduce

1. Config `./configure --without-isal --with-sma`
2. `make -j`
3. Only keep `run_test "sma_vhost" $testdir/vhost_blk.sh` in test/sma/vhost_blk.sh
4. Run `./test/sma/sma.sh`
5. vm_run function failed, information as below:
Qemu command:
taskset -a -c 1-2 /home/wenjun/oracle_qemu/build/x86_64-softmmu/qemu-system-x86_64 -m 1024 --enable-kvm -cpu host -smp 2 -vga std -vnc :100 -daemonize -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,share=on,prealloc=yes,host-nodes=0,policy=bind -snapshot -monitor telnet:127.0.0.1:10002,server,nowait -numa node,memdev=mem -pidfile /root/vhost_test/vms/0/qemu.pid -serial file:/root/vhost_test/vms/0/serial.log -D /root/vhost_test/vms/0/qemu.log -chardev file,path=/root/vhost_test/vms/0/seabios.log,id=seabios -device isa-debugcon,iobase=0x402,chardev=seabios -net user,hostfwd=tcp::10000-:22,hostfwd=tcp::10001-:8765 -net nic -drive file=,if=none,id=os_disk -device ide-hd,drive=os_disk,bootindex=0 -device virtio-scsi-pci,num_queues=2 -device scsi-hd,drive=hd,vendor=RAWSCSI -drive if=none,id=hd,file=/home/wenjun/spdk/default_virtio.img,format=raw '-qmp tcp:localhost:9080,server,nowait -device pci-bridge,chassis_nr=1,id=pci.spdk.0 -device pci-bridge,chassis_nr=2,id=pci.spdk.1'

Error information:
=== qemu.log ===
qemu-system-x86_64: -device ide-hd,drive=os_disk,bootindex=0: Device needs media, but drive is empty
=== qemu.log ===

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: c6880a3974a0eb7a90eb7cd327df5d64d3b6e47e
Qemu version: `version 6.0.93`

**Comment by mikeBashStuff** [comment]
The `vm_run()` is missing the `--os` argument which should point at the boot image. We should handle it a bit better as this leads to a faulty cmdline which we build for the qemu:

```
... file=,if=none,id=os_disk ... # note the empty file argument
```

**Comment by junwenx** [comment]
@mikeBashStuff Thanks! So should we add this `--os` argument in test/sma/vhost_blk.sh file, **vm_setup --force=$vm_no --disk-type=virtio `--os=xxx` --qemu-args=***********

**Comment by mikeBashStuff** [comment]
@junwenx Yes, I am planning to push some patches to address that. :) For our test suite it should boil down to simply adding `--os="$VM_IMAGE"` (where `$VM_IMAGE` is provided via `test/vhost/common.sh`).

**Comment by junwenx** [comment]
:) Thanks @mikeBashStuff

**Comment by mikeBashStuff** [comment]
Apologies for the delay but I just got swamped by other tasks. :) This patch should help here (that said, I haven't tested the actual `test/sma` suite so not sure if the remaining parts of it will still work): https://review.spdk.io/gerrit/c/spdk/spdk/+/13903

**Comment by tomzawadzki** [comment]
Closing the issue since patch fixing it was merged https://review.spdk.io/gerrit/c/spdk/spdk/+/13903.
