### ISSUE TITLE
[ compile warning ] Warning message in compile log in the newest SPDK code.

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2625]
# Bug report

Warning message in compile log in the newest SPDK code

## Expected Behavior

no warning message

## Steps to Reproduce

1. `./configure --without-isal`
2. `make -j`
3. Warning appeared:

 LINK blobfs_bdev_ut
In file included from ftl_io_ut.c:11:
/home/wenjun/spdk/lib/ftl/ftl_io.c: In function ‘ftl_io_cb’:
/home/wenjun/spdk/lib/ftl/ftl_io.c:121:16: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
  121 |         size_t result;
      |                ^~~~~~

## Context (Environment including OS version, SPDK version, etc.)

SPDK version: c6880a3974a0eb7a90eb7cd327df5d64d3b6e47e

**Comment by yidong0635** [comment]
for the second one: https://review.spdk.io/gerrit/c/spdk/spdk/+/13838

**Comment by junwenx** [comment]
Thanks. This can be closed.
