### ISSUE TITLE
Error while handling network vagrant-libvirt

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2628]
# CI Intermittent Failure

Error occurs when removing vagrant-libvirt network when job is finishing up.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/81856/archive/ubuntu20-vg-autotest/build.log

## Execution failed at

```
00:10:52.409  ==> default: Attempting graceful shutdown of VM...
00:10:57.681  [Pipeline] sh
00:10:57.962  + vagrant destroy -f
00:10:58.895  If run with libvirt provider please execute create_nvme_img.sh
00:10:58.895  If run with libvirt provider please execute create_nvme_img.sh
00:10:59.152  If run with libvirt provider please execute create_nvme_img.sh
00:10:59.152  If run with libvirt provider please execute create_nvme_img.sh
00:10:59.152  If run with libvirt provider please execute create_nvme_img.sh
00:10:59.152  If run with libvirt provider please execute create_nvme_img.sh
00:10:59.152  If run with libvirt provider please execute create_nvme_img.sh
00:10:59.152  If run with libvirt provider please execute create_nvme_img.sh
00:10:59.718  ==> default: Removing domain...
00:10:59.975  Error while removing network vagrant-libvirt. Call to virNetworkDestroy failed: Network not found: no network with matching uuid '82787543-c1fb-459f-87be-78fb3ec75a3f' (vagrant-libvirt).
00:10:59.990  [Pipeline] }
00:11:00.012  [Pipeline] // stage
00:11:00.025  [Pipeline] }
00:11:00.047  [Pipeline] // dir
00:11:00.056  [Pipeline] }
00:11:00.060  ERROR: script returned exit code 1
00:11:00.079  [Pipeline] // catchError
00:11:00.091  [Pipeline] stage
00:11:00.094  [Pipeline] { (Epilogue)
00:11:00.112  [Pipeline] sh
00:11:00.397  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:11:00.397  jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: line 8: cd: /var/jenkins/workspace/ubuntu20-vg-autotest/output: No such file or directory
00:11:00.410  [Pipeline] }
00:11:00.431  [Pipeline] // stage
00:11:00.440  [Pipeline] }
00:11:00.457  [Pipeline] // node
00:11:00.470  [Pipeline] End of Pipeline
00:11:00.489  ERROR: script returned exit code 1
00:11:00.493  Finished: FAILURE
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_81856.html

**Comment by mikeBashStuff** [comment]
This is peculiar.  This network should be automatically created by vagrant when we create the VM - at the end we destroy just the VM, not the network  so it should remain as is. It looks like somehow the network was removed when the VM was running.  This happened on our new VM hosts where we were just syncing new images so maybe some awkward race condition happened (we boot testing VM while create volumes, etc. so maybe when we were destroying that testing image when a job got scheduled on the host). 

In any case, I verified the state of all the new VM hosts (SM1{6..8}) and everything seems to be working fine now. Let's leave this issue for a day or two to see if anyone's patches got hit by it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_82137.html

**Comment by mikeBashStuff** [comment]
Ok, this is an actual problem with the `vagrant-libvirt` plugin - since 0.7.0 it now tries to destroy network created for given domain by the very default. This currently may happen on SM16, SM17 and SM18 where latest version of the plugin is used. This is bad as we currently relay on this mgmt network to exist as all VMs are being attached to it.

I will try to add support for creating our own network into the Vagrantfile. The alternative is to either downgrade the plugin or update it to at least 0.8.0 where `management_network_keep` option got introduced (https://github.com/vagrant-libvirt/vagrant-libvirt/commit/76544f04).

**Comment by mikeBashStuff** [comment]
I have series here that I am going to test this week, see if we can mitigate it in some sensible way: https://review.spdk.io/gerrit/q/topic:vagrant-libvirt

**Comment by tomzawadzki** [comment]
[Bug scrub] The changes to SPDK vagrant are done, the deployment and changes on CI side are still in progress.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_86795.html

**Comment by tomzawadzki** [comment]
Please see https://ci.spdk.io/results/autotest-nightly/builds/1295/archive/ubuntu20-vg-autotest/build.log for similar report to above, which occurs when creating the vagrant-libvirt network.
@mikeBashStuff please let me know if its correct to report such failures against this issue, or there should be a separate GH issue for it.

**Comment by mikeBashStuff** [comment]
@tomzawadzki It is correct, yes.

**Comment by jimharris** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_91046.html

**Comment by jimharris** [comment]
@mikeBashStuff do you think we can close this?

**Comment by mikeBashStuff** [comment]
@jimharris Yes - this issue was affecting only particular number of VM hosts (3 to be exact) which were using latest version of the `vagrant-libvirt` plugin. Since then we downgraded it and aligned across all VM hosts. In short, this should not affect the CI anymore. I still need to figure out how to properly adjust our CI side to work with the latest version of the plugin - as sooner or later we will have to upgrade it - but the issue itself can be closed (all needed work is already included in my planning).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98142.html

**Comment by mikeBashStuff** [comment]
The report above is not related to this issue.
