### ISSUE TITLE
[vfio_user_fio] vfio-user-v0.93/bin/qemu-system-x86_64 : No such file or directory

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#2633]
# CI Intermittent Failure

00:14:02.589   07:34:19	-- vhost/common.sh@348 -- # [[ ! -r /root/vhost_test/vms/0/qemu.pid ]]
00:14:02.589   07:34:19	-- vhost/common.sh@349 -- # return 1
00:14:02.589   07:34:19	-- vhost/common.sh@867 -- # notice 'running /root/vhost_test/vms/0/run.sh'
00:14:02.589   07:34:19	-- vhost/common.sh@89 -- # message INFO 'running /root/vhost_test/vms/0/run.sh'
00:14:02.589   07:34:19	-- vhost/common.sh@55 -- # local verbose_out
00:14:02.589   07:34:19	-- vhost/common.sh@56 -- # false
00:14:02.589   07:34:19	-- vhost/common.sh@57 -- # verbose_out=
00:14:02.589   07:34:19	-- vhost/common.sh@64 -- # local msg_type=INFO
00:14:02.589   07:34:19	-- vhost/common.sh@65 -- # shift
00:14:02.589   07:34:19	-- vhost/common.sh@66 -- # echo -e 'INFO: running /root/vhost_test/vms/0/run.sh'
00:14:02.589  INFO: running /root/vhost_test/vms/0/run.sh
00:14:02.589   07:34:19	-- vhost/common.sh@868 -- # /root/vhost_test/vms/0/run.sh
00:14:02.589  Running VM in /root/vhost_test/vms/0
00:14:02.589  taskset: failed to execute /usr/local/qemu/vfio-user-v0.93/bin/qemu-system-x86_64: No such file or directory
00:14:02.589  Waiting for QEMU pid file
00:14:05.129  ERROR: no qemu pid file found
00:14:05.129  === qemu.log ===
00:14:05.129  === qemu.log ===
00:14:05.129   07:34:21	-- vhost/common.sh@869 -- # error 'FAILED to run vm 0'
00:14:05.129   07:34:21	-- vhost/common.sh@77 -- # echo ===========
00:14:05.129  ===========

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/82027/archive/vfio-user-autotest/build.log

## Execution failed at

00:14:05.129  in /var/jenkins/workspace/vfio-user-autotest/spdk/test/vfio_user/common.sh:9 -> clean_vfio_user(["error"],["81"])
00:14:05.129       ...
00:14:05.129     4   	# Verify vfio-user support of qemu.
00:14:05.129     5   	QEMU_BIN="/usr/local/qemu/vfio-user-v0.93/bin/qemu-system-x86_64"
00:14:05.129     6   	
00:14:05.129     7   	function clean_vfio_user() {
00:14:05.129     8   		trap - ERR
00:14:05.129  => 9   		print_backtrace
00:14:05.129     10  		set +e
00:14:05.129     11  		error "Error on $1 $2"
00:14:05.129     12  		vm_kill_all
00:14:05.129     13  		vhost_kill 0
00:14:05.129     14  		exit

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_81987.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_82032.html

**Comment by changpe1** [comment]
@mikeBashStuff @karlatec this issue happened frequently now, can you check the test image why the qemu binary isn't exist sometimes? thanks.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_82029.html

**Comment by mikeBashStuff** [comment]
@changpe1 We missed this during last CI update - all images are now shipped with QEMU updated via https://review.spdk.io/gerrit/c/spdk/spdk/+/12358. Here's a mitigation: https://review.spdk.io/gerrit/c/spdk/spdk/+/13894. We are preparing to update to vfio-user-irqmask2 branch but until that happens we need to switch to dbfix.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yidong0635. log: https://ci.spdk.io/public_build/autotest-per-patch_82020.html

**Comment by changpe1** [comment]
> @changpe1 We missed this during last CI update - all images are now shipped with QEMU updated via https://review.spdk.io/gerrit/c/spdk/spdk/+/12358. Here's a mitigation: https://review.spdk.io/gerrit/c/spdk/spdk/+/13894. We are preparing to update to vfio-user-irqmask2 branch but until that happens we need to switch to dbfix.

Thanks, let's use `vfio-user-dbfix` for a while to see this branch is stable enough or not.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_82097.html

**Comment by Comphix** [comment]
From https://ci.spdk.io/results/autotest-per-patch/builds/82095/archive/vfio-user-autotest/build.log

Looks like with vfio-user-dbfix, the issue still remains.

```
00:04:18.621  Running VM in /root/vhost_test/vms/0
00:04:18.621  taskset: failed to execute /usr/local/qemu/vfio-user-dbfix/bin/qemu-system-x86_64: No such file or directory
00:04:18.621  Waiting for QEMU pid file
00:04:20.530  ERROR: no qemu pid file found
```

**Comment by mikeBashStuff** [comment]
@Comphix Based on the logs, this happened on a node (WFP3) where an old image of fedora34 was still booted. I verified that after the failure this particular node was properly rebooted into fedora35 image where dbfix is on board:

```
[root@spdk-WFP-03 ~]# [[ -e /usr/local/qemu/vfio-user-dbfix/ ]]; echo ok; grep . /proc/sys/kernel/hostname
ok
spdk-WFP3-03
```

**Comment by Comphix** [comment]
Thanks @mikeBashStuff . Let me close this issue.

**Comment by Bianyfan** [comment]
> @Comphix Based on the logs, this happened on a node (WFP3) where an old image of fedora34 was still booted. I verified that after the failure this particular node was properly rebooted into fedora35 image where dbfix is on board:
> 
> ```
> [root@spdk-WFP-03 ~]# [[ -e /usr/local/qemu/vfio-user-dbfix/ ]]; echo ok; grep . /proc/sys/kernel/hostname
> ok
> spdk-WFP3-03
> ```
Hi @mikeBashStuff , I find the same issue on "WFP11", is it related with some particular nodes?
There is my error logs
`00:45:38.305  Running VM in /root/vhost_test/vms/0
00:45:38.305  taskset: failed to execute /usr/local/qemu/vfio-user-v0.93/bin/qemu-system-x86_64: No such file or directory
00:45:38.305  Waiting for QEMU pid file
00:45:40.215  ERROR: no qemu pid file found`
I also put my build link here:
https://ci.spdk.io/public_build/autotest-per-patch_82761.html
