### ISSUE TITLE
[performance of nvmf] unbalance when nvmf rdma add poller to poll group

### ISSUE THREAD

**Issue by liuqinfei** [spdk/spdk#2636]
# Bug report

In the initialization phase of nvmf client, The client sends a link setup request to the server. Then the server selects one of the existing poll groups to establish a link( nvmf_rdma_get_optimal_poll_group() ). The existing allocation method is traversal. This is fine when several clients link setup in sequence. However, when some link disconnect, the server will not know and still select poll group as default. Thus, in the server node, some core is busy, and some is idle. 

## Expected Behavior

The server node can distribute the pollers fairly over the poller_groups according the real-time number of poller for each poller_group .

## Current Behavior

The existing allocation method is traversal and unperceived link disconnection.

## Possible Solution

An active poller "num_active_pollers" count can be added to struce spdk_nvmf_poll_group.
When call add a new poller, num_active_pollers++; when disconnect a poller, num_active_pollers--;
Then we can allocate a poll group with a more fair behaviour. 

## Steps to Reproduce

1. start a nvmf_tgt with 2 cores in server node, and create a transport, attach one nvme controller, create subsystem, and so on: 
./build/bin/nvmf_tgt -m [65,66] &
2. start a perf test case1 with 1 core in client node:
./spdk/build/examples/perf -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.86.30 trsvcid:4420' -w randwrite -q 128 -o 4096 -t 1200 -c [5]
3. start a perf test case2 with 1 core in client node:
./spdk/build/examples/perf -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.86.30 trsvcid:4420' -w randwrite -q 128 -o 4096 -t 1200 -c [6]
By the way, we can see the 2 cores in server node work in a balanced way.
4. Now cancel test case2; and run test case2 again(repeat step 3). We can see only one core in server node is working , and the other one is idle.

## Context (Environment including OS version, SPDK version, etc.)
centos8.1, 
spdk22.05

**Comment by AlekseyMarchuk** [comment]
Hi @liuqinfei thanks for this report. I'll mark this as an enchantment, that is definitely worth to do. Would you like to implement it by yourself? If no then I can do it next week.

**Comment by liuqinfei** [comment]
> Hi @liuqinfei thanks for this report. I'll mark this as an enchantment, that is definitely worth to do. Would you like to implement it by yourself? If no then I can do it next week.

Fine, i will submit a patch later this week.

**Comment by liuqinfei** [comment]
@Comphix Sorry, The assignment was accidentally removed by me a few minutes ago. In fact, i have just submit the patch alreaday. Please review it. https://review.spdk.io/gerrit/c/spdk/spdk/+/14002.

**Comment by tomzawadzki** [comment]
Closing since patch fixing the issue was merged https://review.spdk.io/gerrit/c/spdk/spdk/+/14002.
