### ISSUE TITLE
bdev/part_ut.c : There is a memory leak in part_ut.

### ISSUE THREAD

**Issue by KanKuox123** [spdk/spdk#2638]
# Bug report

688 bytes are still reachable after termination of part_ut when debugging with valgrind. But SPDK CI doesn't report errors. 

## Expected Behavior

There are no memory leaks when debugging with valgrind.

## Current Behavior

[root@waikikibeach36 ~/kankuo/spdk]# valgrind ./test/unit/lib/bdev/part.c/part_ut
==687085== Memcheck, a memory error detector
==687085== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==687085== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==687085== Command: ./test/unit/lib/bdev/part.c/part_ut
==687085==

     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/

Suite: bdev_part
  Test: part_test ...passed

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      1      1    n/a      0        0
               tests      1      1      1      0        0
             asserts      5      5      5      0      n/a

Elapsed time =    0.043 seconds
[2022-08-16 13:19:36.749217] thread.c: 311:spdk_thread_lib_fini: *ERROR*: io_device test1 not unregistered
[2022-08-16 13:19:36.799133] thread.c: 311:spdk_thread_lib_fini: *ERROR*: io_device test2 not unregistered
==687085==
==687085== HEAP SUMMARY:
==687085==     in use at exit: 688 bytes in 2 blocks
==687085==   total heap usage: 1,092 allocs, 1,090 frees, 61,284 bytes allocated
==687085==
==687085== LEAK SUMMARY:
==687085==    definitely lost: 0 bytes in 0 blocks
==687085==    indirectly lost: 0 bytes in 0 blocks
==687085==      possibly lost: 0 bytes in 0 blocks
==687085==    still reachable: 688 bytes in 2 blocks
==687085==         suppressed: 0 bytes in 0 blocks
==687085== Rerun with --leak-check=full to see details of leaked memory
==687085==
==687085== For lists of detected and suppressed errors, rerun with: -s
==687085== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by tomzawadzki** [comment]
Hi @KanKuox123 Please note that SPDK Jenkins CI reports exactly the same summary https://ci.spdk.io/results/autotest-per-patch/builds/82790/archive/valgrind-vg-autotest/build.log.

`Still reachable` does mean that memory is leaked, see the other types above `definitely / indirectly /possibly lost`. Quick summary [here](https://valgrind.org/docs/manual/faq.html#faq.deflost).

**Comment by Comphix** [comment]
Raised the patch here

https://review.spdk.io/gerrit/c/spdk/spdk/+/14063
