### ISSUE TITLE
Nvmf target sees Remote access error while running perf

### ISSUE THREAD

**Issue by stallamr** [spdk/spdk#264]
I see remote access error after running 8 iterations of perf application. Each iteration would run perf application with queue_depth == 64, size == 131072 and time 300seconds.

I dont think there is any setup issue or else the test would not run for ~30mins. The target node is seeing remote access error that means some buffer (used by perf application) is either out of protection domain or freed or swapped? How can I know what buffer has caused this issue? Task buffer of perf application? or internal send/recv buffers? I take any buffer gets allocated on hugepages and so they should be pinned.

My setup: (Linux <-> Linux)

Linux: Debian 4.9
RDMA NIC: CX-5
SPDK - v18.01 & master
NVMe disks - 12 1TB disks from Samsung 

Both initiator & target are connected back-to-back.

Conf file:
~~~
[Nvmf]
  # Set the maximum number of submission and completion queues per session.
  # Setting this to '8', for example, allows for 8 submission and 8 completion queues
  # per session.
  MaxQueuesPerSession 4

  # Set the maximum number of outstanding I/O per queue.
  #MaxQueueDepth 128

  # Set the maximum in-capsule data size. Must be a multiple of 16.
  #InCapsuleDataSize 4096

  # Set the maximum I/O size. Must be a multiple of 4096.
  MaxIOSize 1048576

  # Set the global acceptor lcore ID, lcores are numbered starting at 0.
  #AcceptorCore r09

  # Set how often the acceptor polls for incoming connections. The acceptor is also
  # responsible for polling existing connections that have gone idle. 0 means continuously
  # poll. Units in microseconds.
  AcceptorPollRate 10000
~~~
Initiator: 

Run perf application in loop. 
~~~
#!/bin/bash
count=1
while true; do
echo $count
./perf -q 64 -s 131072 -w write -t 300 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.22.55 trsvcid:4420'
let count++
done

...
nvme_rdma.c:1521:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x557dcf57fca0, qpn: 557, Response Index 1 (5): Work Request Flushed Error
nvme_rdma.c:1521:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x557dcf57fca0, qpn: 557, Response Index 65 (5): Work Request Flushed Error
~~~
Target side:
~~~
root@localhost:~/spdk# ./app/nvmf_tgt/nvmf_tgt -c etc/spdk/nvmf_eth0.conf.in
...
...
mlx5: localhost: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000014 00000000 00000000 00000000
00000000 00008813 1000059c 0035e5d3
rdma.c:1802:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7f1304000a60, qp_num: 1436, Request 0x139719649295056 (10): remote access error vendor_err: 136
rdma.c:1802:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7f1304000a60, qp_num: 1436, Request 0x139719649295424 (5): Work Request Flushed Error vendor_err: 249
rdma.c:1802:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7f1304000a60, qp_num: 1436, Request 0x139719649295792 (5): Work Request Flushed Error vendor_err: 249
rdma.c:1802:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7f1304000a60, qp_num: 1436, Request 0x139719649296160 (5): Work Request Flushed Error vendor_err: 249
rdma.c:1802:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7f1304000a60, qp_num: 1436, Request 0x139719649296528 (5): Work Request Flushed Error vendor_err: 249
rdma.c:1802:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7f1304000a60, qp_num: 1436, Request 0x139719649296896 (5): Work Request Flushed Error vendor_err: 249
~~~
Let me know if you need any more information.

**Comment by xuhuagen** [comment]
My setup: (Linux <-> Linux)

Linux: Centos7.4
RDMA NIC: CX-5
SPDK - v18.04-pre & master
NVMe disks -  4 Intel ssds.

I used your scripts to run perf for 60 mins and CTRL+C, but target machine  core dumped and your issue not be reproduced .

**Comment by rajeshsai810** [comment]
Thanks Xuhuagen for trying this out. And you used same [Nvmf] configuration like mine? From below observation, I think even you may hit this issue if you run the test for 24hrs?

Yesterday, I had 2 more runs on same setup.

1st run:
- MaxIOSize 262144
- MTU 2048
This run completed 136 iterations ~13hrs to hit the issue.

2nd run:
- MaxIOSize 1048576
- MTU 1024
Hitting this issue in <5 iterations ~20-25mins.

Now, I used other new setup with 8 SSDs instead, it took ~10hrs to hit the issue. This setup is with 
MaxIOSize 1048576 and MTU 1024. 

In this context, following is my observation/theory.

1) Number of SSDs matter.
2) MaxIOSize in the conf file is influencing the panic
3) IB device MTU also playing some role in panic.

Now, how can I debug this more? How can I know which buffer is resulting in this error? RDMA_WRITE buffer ? RDMA_READ buffer? RECV buffer? 

When I tried to enable logging for all (-t all) and my machine ran out of space before I hit this issue. 

Thanks,
Rajesh.

**Comment by rajeshsai810** [comment]
Disabling transparent huge pages fixed this problem.

https://docs.oracle.com/en/database/oracle/oracle-database/18/ladbi/disabling-transparent-hugepages.html#GUID-02E9147D-D565-4AF8-B12A-8E6E9F74BEEA

**Comment by rajeshsai810** [comment]
@jimharris  @wanqunintel  @dverkamp-intel 

I'm relatively new to SPDK, but I'm trying to understand how disabling ASLR works for my test.
My script is mentioned in my first post.

In my test, I'm running "perf" application for 5mins in a infinite loop. 

With ASLR enabled, my test fails randomly in an hr or 2hrs depending on IOSize. 
WIth ASLR disabled, same test runs successfully for 48hrs for any IOSize.

In that context can someone help me understand and answer my questions:
1. When does DPDK reserve or allocate huge pages for perf application?
2. When does memory mappings between huge pages & physical memory happen? & when does these mappings gets torn?
3. When perf application calls spdk_env_init(), do perf application gets a copy of those memory mappings?
4. Perf allocates a task buffer via spdk_dma_zalloc() but when does this memory gets registered with RDMA NIC? ibv_reg_mr() ? 
5. When did ASLR come into play in all of this? Why disabling ASLR helped me? 

Thanks for your time.

**Comment by rajeshsai810** [comment]
I know its not fair to reopen this issue when we know what setting can mitigate the issue. But I'm more concerned when I see same failure with FIO test too. 

Same script just change "perf" application with "fio". Below is my test.fio.

~~~
root@localhost:~/fio# cat spdk-test.fio
[global]
ioengine=/root/spdk/examples/nvme/fio_plugin/fio_plugin
rw=read
iodepth=64
bs=64k
size=1M
thread=1
time_based=1
runtime=300

[fio_test1]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.22.55 trsvcid=4420 ns=1
numjobs=3
~~~

Any my test script,

~~~
#!/bin/bash
count=1
while true; do
echo $count
./fio test.fio
let count++
done
~~~

Error seen on target side:

~~~
mlx5: localhost: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
0000001a 00000000 00000000 00000000
00000000 00008813 0800a2f3 007e43d2
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7fb958000a60, Request 0x140434023255056 (10): remote access error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7fb958000a60, Request 0x140434023255056 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7fb958000a60, Request 0x140434023254688 (5): Work Request Flushed Error

~~~

Now, I'm still clueless on how disabling ASLR is working here. From mailing list, community has confirmed my script is running perf application or fio application as a single process. Then ASLR should not even come into picture. But ASLR seems to mitigate my issue. 

Only plausible explanation I have is "stale" entries. Some where on some iteration RNIC device must be accessing stale memory mapping for a buffer. When I disabled ASLR, across multiple iterations the memory mappings would remain same and RNIC device is accessing memory it should not have access to? 

Looks like this issue is more serious.

**Comment by senthilkumar-v** [comment]
I too face similar issue but it my case it is hitting,

rdma.c:1796:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0xffff100010b0, Request 0x281470950288832 (12): transport retry counter exceeded

It is "transport retry counter exceeded" instead of "remote access error". I've faced this signature in 3 different runs using FIO and IOZONE tools.

**Comment by rajeshsai810** [comment]
I used to hit this issue "transport retry counter exceeded" earlier. But after I turn on Rx and Tx pause, flow control on, I didnot see this error yet.

**Comment by wanqunintel** [comment]
we are reproducing this issue now and it takes some time, we will update later

**Comment by WenqianZong** [comment]
Hi qun:

I reproduce this issue with latest spdk version ,but this issue unstable. following is error log:

## target machine:
```
## mlx5: waikikibeach5: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000000 00008813 10000146 0045b9d3
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36713264 (10): remote access error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36706736 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36713648 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36707120 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36714032 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36707504 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36714416 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36707888 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36714800 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x23ecfa0, Request 0x36708272 (5): Work Request Flushed Error
```

## initator machine:
```
EAL: Detected 72 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.4.11:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.4.11:4420: nqn.2016-06.io.spdk:cnode1
Associating SPDK bdev Controller (SPDK00000000000001  ) with lcore 0
Associating SPDK bdev Controller (SPDK00000000000001  ) with lcore 0
Associating SPDK bdev Controller (SPDK00000000000001  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 26 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 65 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 35228176 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 12 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 35217424 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 35217592 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 35217760 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 35217928 (5): Work Request Flushed Error
nvme_rdma.c:1519:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x216bc60, Response Index 35218096 (5): Work Request Flushed Error
```

**Comment by WenqianZong** [comment]
1.I run perf test keep about 24 hours , but no error occurred.
2. run perf test 5 minutes per cycle, after 13 cycles ,"Work Request Flushed Error" reported.

**Comment by WenqianZong** [comment]
run perf test 5 minutes per cycle, after 1156 cycles ,"Work Request Flushed Error" reported.
commit 34de1542eb418fbc6f88365f269694baa5f5379f

**Comment by wanqunintel** [comment]
@benlwalker, is there any patch for this issue being worked on?

**Comment by JuanA1-ZY** [comment]
mlx5: e07a01227.eu6sqa: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000004 00000000 00000000 00000000
00000000 00008813 10002c02 00112cd2
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298690096 (10): remote access error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298690480 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298690864 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298691248 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298691632 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298692016 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298692400 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298689712 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298692784 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298693168 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298693552 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298693936 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298694320 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298694704 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298695088 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298695472 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298695856 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785056 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785152 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785248 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785344 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785440 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785536 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785632 (5): Work Request Flushed Error
rdma.c:1797:spdk_nvmf_rdma_poller_poll: *ERROR*: CQ error on CQ 0x7eecc0000c20, Request 0x139555298785728 (5): Work Request Flushed Error

I also encountered such problem while using NVMf target, I have four malloc disks in one subsystem, and then tried using the fio_plugin on Host server to run stress test, and found the problem encountered every time when I running write test as below:
[global]
ioengine=spdk
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=60
runtime=120
thread=1
numjobs=4
mem_size_mb=40960
bs=1024k
rw=write
iodepth=32
[test_01]
filename=trtype=RDMA adrfam=IPv4 traddr=XX trsvcid=4420 ns=1
size=8G
[test_02]
filename=trtype=RDMA adrfam=IPv4 traddr=XX trsvcid=4420 ns=2
size=8G
[test_03]
filename=trtype=RDMA adrfam=IPv4 traddr=XX trsvcid=4420 ns=3
size=8G
[test_04]
filename=trtype=RDMA adrfam=IPv4 traddr=XX trsvcid=4420 ns=4
size=8G

**Comment by benlwalker** [comment]
We currently believe that the connection is dropping either due to configuration problems on the NIC or switch, or due to other problems with the cables or firmware on the cards. There is ongoing work to add additional recovery mechanisms to handle these cases now, but it isn't all merged yet.

**Comment by wanqunintel** [comment]
@benlwalker , do you have the patch link for it? just a soft reminder

**Comment by wanqunintel** [comment]
@WenqianZong would you retest with latest SPDK master code and update status here? thanks.

**Comment by WenqianZong** [comment]
I verified this issue with latest spdk b6938efd0b8a3a85bb0b65091eafbb79d8165108 , But when I run perf after 337 cycles error occurred . Following is log : 
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==108697==ERROR: AddressSanitizer: SEGV on unknown address 0x7ffc00000009 (pc 0x0000004f4480 bp 0x7ffcf632e6d0 sp 0x7ffcf632e630 T0)
==108697==The signal is caused by a READ memory access.
    #0 0x4f447f in spdk_nvmf_process_ib_event /home/zong/spdk/lib/nvmf/rdma.c:2204
    #1 0x4f4b29 in spdk_nvmf_rdma_accept /home/zong/spdk/lib/nvmf/rdma.c:2286
    #2 0x4e5582 in spdk_nvmf_transport_accept /home/zong/spdk/lib/nvmf/transport.c:139
    #3 0x4e0708 in spdk_nvmf_tgt_accept /home/zong/spdk/lib/nvmf/nvmf.c:579
    #4 0x4ce23c in acceptor_poll /home/zong/spdk/lib/event/subsystems/nvmf/nvmf_tgt.c:144
    #5 0x50eee2 in _spdk_reactor_run /home/zong/spdk/lib/event/reactor.c:537
    #6 0x50f8aa in spdk_reactors_start /home/zong/spdk/lib/event/reactor.c:677
    #7 0x50acb2 in spdk_app_start /home/zong/spdk/lib/event/app.c:645
    #8 0x40679b in main /home/zong/spdk/app/nvmf_tgt/nvmf_main.c:75
    #9 0x7fcbd176418a in __libc_start_main (/lib64/libc.so.6+0x2318a)
    #10 0x406439 in _start (/home/zong/spdk/app/nvmf_tgt/nvmf_tgt+0x406439)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/zong/spdk/lib/nvmf/rdma.c:2204 in spdk_nvmf_process_ib_event
==108697==ABORTING
```

**Comment by jimharris** [comment]
Hi @stallamr,

Do you think your original issue should be closed?  A lot of work has gone into the NVMe-oF target over the last 1-2 months - I'm curious if your original issue is now addressed.

@WenqianZong - I think maybe this issue you have seen, after 337 cycles, should be a separate GitHub issue.

-Jim

**Comment by stallamr** [comment]
Hi Jim,

I agree that new occurence is different issue and you can go ahead and close this issue. This issue would have propped up <50-100 iterations.

Thanks,
Sai.
