### ISSUE TITLE
how to rollback to snapshot with rpc.py script

### ISSUE THREAD

**Issue by ncist2011** [spdk/spdk#2640]
# CI Intermittent Failure

**Comment by tomzawadzki** [comment]
Hi @ncist2011 would you mind to elaborate on the title of the issue ? If this is regarding the Logical Volume snapshot feature, maybe the answer is in https://spdk.io/doc/logical_volumes.html.

**Comment by tomzawadzki** [comment]
Please try to experiment with `bdev_get_bdevs`, `bdev_lvol_snapshot` and `bdev_lvol_clone` RPC. It should be much more clear after getting some hands on experience.

In general, lvol snapshot is a ready-only version of the volume. The original volume is still accessible under the original name and is read-write enabled.
To use the lvol snapshot in read-write capacity, please issue `bdev_lvol_clone` RPC. This will create new volume that uses the snapshot as starting point.

**Comment by ncist2011** [comment]
> Please try to experiment with `bdev_get_bdevs`, `bdev_lvol_snapshot` and `bdev_lvol_clone` RPC. It should be much more clear after getting some hands on experience.
> 
> In general, lvol snapshot is a ready-only version of the volume. The original volume is still accessible under the original name and is read-write enabled. To use the lvol snapshot in read-write capacity, please issue `bdev_lvol_clone` RPC. This will create new volume that uses the snapshot as starting point.

Got it，i should clone volume from this snapshot which i want to rollback to.

Thank you.
