### ISSUE TITLE
[bdev_bounds] bdevio tests fail under nvme drive with metadata size set

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2644]
```
SPDK:  v22.05-rc1-373-g40d89d602
OS: Fedora35 (5.18.13-100, VM)
QEMU:  7.0.0
```

Only single test is in the bdevio suite is failing, `blockdev comparev and writev -> blockdev_comparev_and_writev()`:

```
 08:41:24       -- bdev/blockdev.sh@178 -- # /root/spdk/test/bdev/bdevio/tests.py perform_tests
I/O targets:
  Nvme0n1: 1548666 blocks of 4096 bytes (6050 MiB)


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: bdevio tests on: Nvme0n1
  Test: blockdev write read block ...passed
  Test: blockdev write zeroes read block ...passed
  Test: blockdev write zeroes read no split ...passed
  Test: blockdev write zeroes read split ...passed
  Test: blockdev write zeroes read split partial ...passed
  Test: blockdev reset ...[2022-08-17 08:41:24.805827] nvme_ctrlr.c:1612:nvme_ctrlr_disconnect: *NOTICE*: [0000:00:06.0] resetting controller
[2022-08-17 08:41:24.808001] bdev_nvme.c:1655:_bdev_nvme_reset_complete: *NOTICE*: Resetting controller successful.
passed
  Test: blockdev write read 8 blocks ...passed
  Test: blockdev write read size > 128k ...passed
  Test: blockdev write read invalid size ...passed
  Test: blockdev write read offset + nbytes == size of blockdev ...passed
  Test: blockdev write read offset + nbytes > size of blockdev ...passed
  Test: blockdev write read max offset ...passed
  Test: blockdev write read 2 blocks on overlapped address offset ...passed
  Test: blockdev writev readv 8 blocks ...passed
  Test: blockdev writev readv 30 x 1block ...passed
  Test: blockdev writev readv block ...passed
  Test: blockdev writev readv size > 128k ...passed
  Test: blockdev writev readv size > 128k in two iovs ...passed
  Test: blockdev comparev and writev ...[2022-08-17 08:41:24.816712] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.816801] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:0016 p:1 m:0 dnr:0
[2022-08-17 08:41:24.817205] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.817312] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:0017 p:1 m:0 dnr:0
[2022-08-17 08:41:24.817689] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.817802] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:0018 p:1 m:0 dnr:0
[2022-08-17 08:41:24.818314] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.818419] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:0019 p:1 m:0 dnr:0
[2022-08-17 08:41:24.819067] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.819132] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:001a p:1 m:0 dnr:0
[2022-08-17 08:41:24.819594] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.819646] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:001b p:1 m:0 dnr:0
[2022-08-17 08:41:24.820101] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.820209] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:001c p:1 m:0 dnr:0
[2022-08-17 08:41:24.820612] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:191 nsid:1 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x17ac39000 len:0x1000
[2022-08-17 08:41:24.820661] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:191 cdw0:0 sqhd:001d p:1 m:0 dnr:0
FAILED
    1. bdevio.c:475  - CU_ASSERT_EQUAL(g_completion_success,true)
    2. bdevio.c:485  - CU_ASSERT_EQUAL(rc,0)
  Test: blockdev nvme passthru rw ...passed
  Test: blockdev nvme passthru vendor specific ...[2022-08-17 08:41:24.821866] nvme_qpair.c: 218:nvme_admin_qpair_print_command: *NOTICE*: FABRIC CONNECT qid:1 cid:191 PRP1 0x0 PRP2 0x0
[2022-08-17 08:41:24.822006] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: INVALID OPCODE (00/01) qid:1 cid:191 cdw0:0 sqhd:0021 p:1 m:0 dnr:1
passed
  Test: blockdev nvme admin passthru ...passed

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      1      1    n/a      0        0
               tests     22     22     21      1        0
             asserts    100    100     98      2      n/a

Elapsed time =    0.077 seconds
request:
{
  "method": "perform_tests",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32603,
  "message": "2 test cases failed"
}

```

Verified that LBAF in use has proper ms set (64B):
```
# kernel view
[root@fedora35-cloud-21845 spdk]# nvme id-ns /dev/nvme0n1 | grep "in use"
lbaf  7 : ms:64  lbads:12 rp:0 (in use)

# SPDK view
[root@fedora35-cloud-21845 spdk]# grep . /sys/class/nvme/nvme0/address
0000:00:06.0
[root@fedora35-cloud-21845 spdk]# ./build/bin/spdk_tgt &
[1] 6624
[root@fedora35-cloud-21845 spdk]# [2022-08-17 08:46:58.429048] Starting SPDK v22.09-pre git sha1 40d89d602 / DPDK 22.03.0 initialization...
[2022-08-17 08:46:58.429259] [ DPDK EAL parameters: [2022-08-17 08:46:58.429300] spdk_tgt [2022-08-17 08:46:58.429340] --no-shconf [2022-08-17 08:46:58.429379] -c 0x1 [2022-08-17 08:46:58.429456] --huge-unlink [2022-08-17 08:46:58.429485] --log-level=lib.eal:6 [2022-08-17 08:46:58.429531] --log-level=lib.cryptodev:5 [2022-08-17 08:46:58.429560] --log-level=user1:6 [2022-08-17 08:46:58.429594] --iova-mode=pa [2022-08-17 08:46:58.429623] --base-virtaddr=0x200000000000 [2022-08-17 08:46:58.429659] --match-allocations [2022-08-17 08:46:58.429689] --file-prefix=spdk_pid6624 [2022-08-17 08:46:58.429735] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-08-17 08:46:58.590674] app.c: 586:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-08-17 08:46:58.844643] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 0
[2022-08-17 08:46:58.844893] accel_sw.c: 377:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
[2022-08-17 08:46:59.076863] 'OCF Core' volume operations registered
[2022-08-17 08:46:59.081123] 'SPDK_block_device' volume operations registered

[root@fedora35-cloud-21845 spdk]# ./scripts/rpc.py bdev_nvme_attach_controller -t pcie -a 0000:00:06.0 -b test
testn1
[root@fedora35-cloud-21845 spdk]# ./scripts/rpc.py bdev_get_bdevs | jq '.[] | ."md_size"'
64
```
This currently blocks https://trello.com/c/neiHoXlr/448-add-extra-nvme-drive-to-vms-to-accommodate-for-new-ftl-tests from being completed.

**Comment by changpe1** [comment]
@mikeBashStuff From the log, it says block size is 4096 and metadata is 64, I guess you are using separate metadata for the NVMe drive.  But for all the test cases, we don't pass a valid metadata buffer, I think it's up to QEMU how to response this behavior.

**Comment by changpe1** [comment]
Jim already post a workaround patch via https://review.spdk.io/gerrit/c/spdk/spdk/+/14081.

**Comment by changpe1** [comment]
From the log https://ci.spdk.io/results/autotest-per-patch/builds/83069/archive/nvme-vg-autotest/build.log, although it didn't fail the bdev_bounds test case, but COMPARE still reported errors.

00:04:45.898    Test: blockdev comparev and writev ...[2022-08-18 00:41:00.970694] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000
00:04:45.898  [2022-08-18 00:41:00.970863] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:0018 p:1 m:0 dnr:0
00:04:45.898  [2022-08-18 00:41:00.971246] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000
00:04:45.898  [2022-08-18 00:41:00.971361] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:0019 p:1 m:0 dnr:0
00:04:45.898  [2022-08-18 00:41:00.971596] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000
00:04:45.898  [2022-08-18 00:41:00.971708] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:001a p:1 m:0 dnr:0
00:04:45.898  [2022-08-18 00:41:00.971996] nvme_qpair.c: 243:nvme_io_qpair_print_command: *NOTICE*: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000
00:04:45.898  [2022-08-18 00:41:00.972109] nvme_qpair.c: 427:spdk_nvme_print_completion: *NOTICE*: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:001b p:1 m:0 dnr:0
00:04:45.898  passed

**Comment by jimharris** [comment]
> From the log https://ci.spdk.io/results/autotest-per-patch/builds/83069/archive/nvme-vg-autotest/build.log, although it didn't fail the bdev_bounds test case, but COMPARE still reported errors.
> 
> 00:04:45.898 Test: blockdev comparev and writev ...[2022-08-18 00:41:00.970694] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.970863] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:0018 p:1 m:0 dnr:0 00:04:45.898 [2022-08-18 00:41:00.971246] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.971361] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:0019 p:1 m:0 dnr:0 00:04:45.898 [2022-08-18 00:41:00.971596] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.971708] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:001a p:1 m:0 dnr:0 00:04:45.898 [2022-08-18 00:41:00.971996] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.972109] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:001b p:1 m:0 dnr:0 00:04:45.898 passed

I think this is OK - the bdevio test has some cases which expect failure.

**Comment by jimharris** [comment]
> > From the log https://ci.spdk.io/results/autotest-per-patch/builds/83069/archive/nvme-vg-autotest/build.log, although it didn't fail the bdev_bounds test case, but COMPARE still reported errors.
> > 00:04:45.898 Test: blockdev comparev and writev ...[2022-08-18 00:41:00.970694] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.970863] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:0018 p:1 m:0 dnr:0 00:04:45.898 [2022-08-18 00:41:00.971246] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.971361] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:0019 p:1 m:0 dnr:0 00:04:45.898 [2022-08-18 00:41:00.971596] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.971708] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:001a p:1 m:0 dnr:0 00:04:45.898 [2022-08-18 00:41:00.971996] nvme_qpair.c: 243:nvme_io_qpair_print_command: _NOTICE_: COMPARE sqid:1 cid:190 nsid:3 lba:0 len:1 SGL DATA BLOCK ADDRESS 0x27fa31000 len:0x1000 00:04:45.898 [2022-08-18 00:41:00.972109] nvme_qpair.c: 427:spdk_nvme_print_completion: _NOTICE_: COMPARE FAILURE (02/85) qid:1 cid:190 cdw0:0 sqhd:001b p:1 m:0 dnr:0 00:04:45.898 passed
> 
> I think this is OK - the bdevio test has some cases which expect failure.

bdevio expects one failure.  But QEMU sets dnr=0 for the compare failure, so the bdev_nvme module retries it 3 times.  That is why we see 4 failures here.

Tagging @birkelund here, should QEMU return dnr=1 for COMPARE failures?

**Comment by birkelund** [comment]
> bdevio expects one failure. But QEMU sets dnr=0 for the compare failure, so the bdev_nvme module retries it 3 times. That is why we see 4 failures here.
> 
> Tagging @birkelund here, should QEMU return dnr=1 for COMPARE failures?

Adding DNR would probably be the most reasonable here. On the other hand, if a writer is concurrently writing the data that we try to compare against, the Compare *may* very well complete successfully if resubmitted.

However, I'd rather follow the consensus, so if hardware that you are testing against uses DNR on compare failure, then I'll be happy to change the behavior of hw/nvme in QEMU.

**Comment by jimharris** [comment]
> > Tagging @birkelund here, should QEMU return dnr=1 for COMPARE failures?
> 
> Adding DNR would probably be the most reasonable here. On the other hand, if a writer is concurrently writing the data that we try to compare against, the Compare _may_ very well complete successfully if resubmitted.
> 
> However, I'd rather follow the consensus, so if hardware that you are testing against uses DNR on compare failure, then I'll be happy to change the behavior of hw/nvme in QEMU.

Will need to check if existing hardware is setting DNR or not.  This detail gets hidden from applications, since the nvme driver automatically handles the retries.  We only caught this behavior by chance since we had another bug in this code path that led us to scour the logs.  ;-)

The spec says:

```
Do Not Retry (DNR): If set to ‘1’, indicates that if the same command is re-submitted to any
controller in the NVM subsystem, then that re-submitted command is expected to fail. If cleared to
‘0’, indicates that the same command may succeed if retried. If a command is aborted due to time
limited error recovery (refer to the Error Recovery section in the NVM Command Set Specification),
this bit should be cleared to ‘0’. If the SCT and SC fields are cleared to 0h, then this bit should be
cleared to ‘0’.
```

I've always interpreted this to be from the device's perspective.  I hadn't considered the device setting DNR based on whether some action or command by the host might allow the command to complete successfully if resubmitted.  I'd still lean towards setting DNR=1 here though, if the host is using compare or compare-and-write, I think we want the host application to get notified as quickly as possible if the compare fails, rather than having to wait for X number of retries since the host driver things that a retry might get it complete successfully.

**Comment by birkelund** [comment]
> I've always interpreted this to be from the device's perspective. I hadn't considered the device setting DNR based on whether some action or command by the host might allow the command to complete successfully if resubmitted. I'd still lean towards setting DNR=1 here though, if the host is using compare or compare-and-write, I think we want the host application to get notified as quickly as possible if the compare fails, rather than having to wait for X number of retries since the host driver things that a retry might get it complete successfully.

That sounds reasonable. I'll post a fix for QEMU.
