### ISSUE TITLE
[dd_flag_append] Cannot contact VM-host-SM16

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#2646]
# CI Intermittent Failure

Aborted run of ubuntu20-vg-autotest at VM-host-SM16
## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_82954.html
https://ci.spdk.io/results/autotest-per-patch/builds/82954/archive/ubuntu20-vg-autotest/index.html
## Execution failed at

> 00:06:53.813   11:06:16	-- dd/posix.sh@21 -- # /home/vagrant/spdk_repo/spdk/build/bin/spdk_dd --if=/home/vagrant/spdk_repo/spdk/test/dd/dd.dump0 --of=/home/vagrant/spdk_repo/spdk/test/dd/dd.dump1 --oflag=append
00:06:53.813  [2022-08-17 11:06:16.740839] Starting SPDK v22.09-pre git sha1 165d73327 / DPDK 22.03.0 initialization...
00:06:53.813  [2022-08-17 11:06:16.741152] [ DPDK EAL parameters: [2022-08-17 11:06:16.741237] spdk_dd [2022-08-17 11:06:16.741300] --no-shconf [2022-08-17 11:06:16.741358] -c 0x1 [2022-08-17 11:06:16.741419] --huge-unlink [2022-08-17 11:06:16.741477] --log-level=lib.eal:6 [2022-08-17 11:06:16.741554] --log-level=lib.cryptodev:5 [2022-08-17 11:06:16.741619] --log-level=user1:6 [2022-08-17 11:06:16.741680] --iova-mode=pa [2022-08-17 11:06:16.741752] --base-virtaddr=0x200000000000 [2022-08-17 11:06:16.741818] --match-allocations [2022-08-17 11:06:16.741875] --file-prefix=spdk_pid19751 [2022-08-17 11:06:16.741957] ]
00:07:13.811  Cannot contact VM-host-SM16: java.lang.InterruptedException
00:16:18.359  Cancelling nested steps due to timeout
00:17:18.360  Body did not finish within grace period; terminating with extreme prejudice

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_82954.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_82956.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_82588.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_83836.html

**Comment by mikeBashStuff** [comment]
Same story as in case of #2648 - new VM hosts (SM{16..18}) had a period of instability which hopefully should be over now.
