### ISSUE TITLE
Nvme-cli compile error with SPDK

### ISSUE THREAD

**Issue by sdfsdfsdxx2** [spdk/spdk#265]
I am using the latest code and I have built the spdk already. But I always encounter these errors when I tried to build nvme-cli:

/home/cordite/Desktop/new_nvme/new/nvme-cli/spdk/dpdk/build/lib/librte_eal.a(eal_memory.o): In function rte_eal_hugepage_init': eal_memory.c:(.text+0xa28): undefined reference tonuma_allocate_nodemask'
eal_memory.c:(.text+0xa34): undefined reference to numa_available' eal_memory.c:(.text+0xa79): undefined reference toget_mempolicy'
eal_memory.c:(.text+0xcce): undefined reference to numa_bitmask_free' eal_memory.c:(.text+0xd9f): undefined reference tonuma_allocate_nodemask'
eal_memory.c:(.text+0xdab): undefined reference to numa_available' eal_memory.c:(.text+0x10e8): undefined reference tonuma_bitmask_free'
eal_memory.c:(.text+0x234e): undefined reference to set_mempolicy' eal_memory.c:(.text+0x237e): undefined reference tonuma_set_localalloc'
eal_memory.c:(.text+0x24c5): undefined reference to numa_set_preferred' eal_memory.c:(.text+0x28ab): undefined reference tonuma_bitmask_free'
/home/cordite/Desktop/new_nvme/new/nvme-cli/spdk/dpdk/build/lib/librte_eal.a(eal_common_options.o): In function eal_plugins_init': eal_common_options.c:(.text+0x7d8): undefined reference todlopen'
eal_common_options.c:(.text+0x7e9): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
Makefile:41: recipe for target 'nvme' failed
make: *** [nvme] Error 1

**Comment by dverkamp-intel** [comment]
Which nvme-cli and SPDK commit are you on?

The symbols you are apparently missing are from libnuma and libdl, both of which should be in the link command line (`-lnuma` and `-ldl` in env.spdk.mk from nvme-cli).

**Comment by xuhuagen** [comment]
I have compiled nvme-cli in my machine. the step is as below:
1. git clone -b spdk https://github.com/spdk/nvme-cli.git
2 cd nvme-cli/spdk && ./configure && make -j
3. cd ../
4. make

There is not produced any error when I complied nvme-cli.
it is due to the environment of your machine.

**Comment by ranjitrv** [comment]
I'm still facing this compilation error with spdk v18.01 spdk/nvme-cli v1.3 on Ubuntu 4.14 kernel. I have tried make CONFIG_RDMA=y

**Comment by Comphix** [comment]
After getting nvme-cli from code repository https://github.com/spdk/nvme-cli.git, for spdk v18.01, have you run the "git submodule update --init" and "./configure", "make clean && make"? After this, try "make clean && make" in the nvme-cli folder.

**Comment by ranjitrv** [comment]
Yes, I have done. Infact  I have just repeated exact sequence just mentioned in the comment. PFA's for screenshots. 

nvme-cli$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

nvme-cli$ uname -a
Linux nile-initiator 4.14.15 #5 SMP Thu Jan 25 16:01:32 MST 2018 x86_64 x86_64 x86_64 GNU/Linux

nvme-cli$ git branch
* spdk

nvme-cli$ cd spdk/
nvme-cli/spdk$ git branch
* master

To test, branched spdk from master to v18.01. Still same issue. 

![git seq](https://user-images.githubusercontent.com/37576224/37646889-e4625cb4-2c50-11e8-82e2-d566d77eb2dc.jpg)
![nvme_cli make](https://user-images.githubusercontent.com/37576224/37646893-e4aa8c3c-2c50-11e8-8a55-5b0dd7495717.jpg)
![history](https://user-images.githubusercontent.com/37576224/37646894-e4ee8f90-2c50-11e8-9ab1-1c18beeb02e7.jpg)

**Comment by dverkamp-intel** [comment]
Can you check if the build works if you apply this patch to nvme-cli?

~~~
diff --git a/env.spdk.mk b/env.spdk.mk
index e1acf39..0d54f27 100644
--- a/env.spdk.mk
+++ b/env.spdk.mk
@@ -43,6 +43,7 @@ override LDFLAGS += -ldl -pthread -lrt -lrdmacm -lnuma -libverbs \
         -Wl,--whole-archive \
         -L$(SPDK_LIB_DIR) -lspdk_log -lspdk_nvme -lspdk_env_dpdk -lspdk_util \
         -L$(DPDK_LIB_DIR) -lrte_eal -lrte_mempool -lrte_ring -lrte_pci -lrte_bus_pci \
+        -ldl -lnuma \
         -Wl,--no-whole-archive
 
 ifeq ($(CONFIG_ASAN),y)
~~~

**Comment by ranjitrv** [comment]
Yes, with these flags nvme-cli make succeeds. Thanks.

**Comment by wanqunintel** [comment]
Hi, @dverkamp-intel , is there a link for this patch in the gerrithub for it?

**Comment by dverkamp-intel** [comment]
This issue should be fixed by this nvme-cli commit: https://github.com/spdk/nvme-cli/commit/230837963d38ad0a4ca3696e21b6d9e1e317fdb1

If not, please re-open with more details.
