### ISSUE TITLE
Missing autobuild, autotest support for xNVME

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2656]
```
SPDK:  v22.05-rc1-426-gcd1b7ab0e
```

Currently, there's nothing on the SPDK side that tests xNVME functionality. The following series attempts to hook xnvme into autobuild and autotest suites: https://review.spdk.io/gerrit/q/topic:mb-xnvme-autorun, however, several issues have been detected. Please see the list below:

- https://github.com/spdk/spdk/issues/2655
- https://github.com/spdk/spdk/issues/2654
- https://github.com/spdk/spdk/issues/2653
-  Dependencies are not clearly defined. Since `xnvme` depends on latest liburing which it builds as part of  its subprojects it cannot be used under older kernels. In the context of our CI, this disqualifies use of `xnvme` from the distro-specific jobs that we currently have: ubuntu1804, ubuntu2004, rocky8 and centos7. For ubuntu*, rocky8 using io_uring mechanism leads to segfaults (libaio works), however, under 3.x kernel which is shipped on board of centos7 it doesn't work at all - it simply refuses to create bdev, e.g., on top of a nvme block device. This basically means that we cannot simply enable `--with-xnvme` in all the test suites we have but rather we need to introduce yet another test flag, e.g. `SPDK_TEST_XNVME` to make sure it's run under fairly stable environment. 
- missing unittests covering xNVME

Here are examples of crashes under different kernels when io_uring mechanism is in use:

https://ci.spdk.io/results/autotest-per-patch/builds/83451/archive/centos7-vg-autotest/build.log (can't create bdev)
https://ci.spdk.io/results/autotest-per-patch/builds/83451/archive/ubuntu18-vg-autotest/build.log (SIGSEGV while using io_uring)
https://ci.spdk.io/results/autotest-per-patch/builds/83451/archive/rocky8-vg-autotest/build.log (SIGSEGV while using io_uring but caught by ASAN)
https://ci.spdk.io/results/autotest-per-patch/builds/83451/archive/ubuntu20-vg-autotest/build.log (log is quite extensive as bdevperf was logging plenty of errors before finally reporting IO failures).

**Comment by yidong0635** [comment]
@mikeBashStuff I think we need to clean the issues, some of errors have been fixed.

**Comment by changpe1** [comment]
The issue is done via https://review.spdk.io/gerrit/c/spdk/spdk/+/14118, closing it now.
