### ISSUE TITLE
unhexlify util (from vbdev_crypto.h) is private

### ISSUE THREAD

**Issue by Brotholomew** [spdk/spdk#2658]
# Feature request

Right now hexlifying utils are internal to SPDK. My team is developing a change which involves making use of the same mechanism that is introduced in the vbdev_crypto.h lib. We would like to be able to use your existing solution which is this function: ```static inline char *hexlify(const char *bin, size_t len)```. 

Could you make this util public so that it could be included outside of SPDK?

## Expected Behavior

```unhexlify``` util is in the include path

---
Could you please change labels on this issue to `enhancement` - it seems that I can't do it

**Comment by jimharris** [comment]
Hi @Brotholomew,

Moving these functions to util/ is fine with me.  Would you like to submit a patch for it?

hexlify => spdk_hexlify
unhexlify => spdk_unhexlify

add lib/util/hexlify.c and include/spdk/hexlify.h

-Jim

**Comment by jimharris** [comment]
> @jimharris or spdk/util.h ?

I'd prefer a separate header file.  Putting it in util.h is probably fine, but we've typically created small header files like this for other util-related groups of functions - see file.h, fd.h, uuid.h, zipf.h.

**Comment by Brotholomew** [comment]
thanks @jimharris!
I just published a patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/14191

**Comment by tomzawadzki** [comment]
The patches are now merged. @Brotholomew thank you for the submission !
