### ISSUE TITLE
[llvm_fuzz] llvm fuzz test failed in new CI job with llvm_nvme_fuzz.c:232:40: runtime error: left shift of 136 by 24 places cannot be represented in type 'int'

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2659]
# Bug report

New CI job fail: llvm_nvme_fuzz.c:232:40: runtime error: left shift of 136 by 24 places cannot be represented in type 'int'

## Steps to Reproduce

1. There are 2 new CI job fail because of llvm_nvme_fuzz.c:232:40: runtime error: left shift of 136 by 24 places cannot be represented in type 'int'
Job link: https://10.211.11.56/job/nvmf-phy-short-fuzz-autotest/
21:14:18   15:14:18	-- target/llvm_nvme_fuzz.sh@22 -- # /var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F 'trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420' -c /var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/nvmf/target/fuzz_json.conf -t 1 -D /tmp/llvm_fuzz11 -Z 11
21:14:18  [2022-08-23 15:14:18.137737] Starting SPDK v22.09-pre git sha1 2b1ddcc29 / DPDK 22.03.0 initialization...
21:14:18  [2022-08-23 15:14:18.137817] [ DPDK EAL parameters: [2022-08-23 15:14:18.137832] nvme_fuzz [2022-08-23 15:14:18.137843] -c 0x1 [2022-08-23 15:14:18.137853] --log-level=lib.eal:6 [2022-08-23 15:14:18.137862] --log-level=lib.cryptodev:5 [2022-08-23 15:14:18.137871] --log-level=user1:6 [2022-08-23 15:14:18.137881] --base-virtaddr=0x200000000000 [2022-08-23 15:14:18.137890] --match-allocations [2022-08-23 15:14:18.137900] --file-prefix=spdk0 [2022-08-23 15:14:18.137909] --proc-type=auto [2022-08-23 15:14:18.137919] ]
21:14:18  EAL: No free 2048 kB hugepages reported on node 1
21:14:18  TELEMETRY: No legacy callbacks, legacy socket not created
21:14:18  [2022-08-23 15:14:18.205282] app.c: 575:spdk_app_start: *NOTICE*: Total cores available: 1
21:14:18  [2022-08-23 15:14:18.358163] reactor.c: 919:reactor_run: *NOTICE*: Reactor started on core 0
21:14:18  [2022-08-23 15:14:18.383103] accel_engine.c: 943:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
21:14:18  [2022-08-23 15:14:18.478841] tcp.c: 614:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
21:14:18  [2022-08-23 15:14:18.495263] tcp.c: 817:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.1 port 4420 ***
21:14:18  INFO: Running with entropic power schedule (0xFF, 100).
21:14:18  INFO: Seed: 3584541669
21:14:18  INFO: Loaded 1 modules   (239292 inline 8-bit counters): 239292 [0x1e87c6c, 0x1ec2328), 
21:14:18  INFO: Loaded 1 PC tables (239292 PCs): 239292 [0x1ec2328,0x2268ee8), 
21:14:18  INFO:        0 files found in /tmp/llvm_fuzz11
21:14:18  INFO: A corpus is not provided, starting from an empty corpus
21:14:18  #2	INITED cov: 10873 ft: 10873 corp: 1/1b exec/s: 0 rss: 187Mb
21:14:18  #3	NEW    cov: 10879 ft: 11475 corp: 2/2b lim: 40 exec/s: 0 rss: 188Mb L: 1/1 MS: 1 ChangeBit-
21:14:18  #4	NEW    cov: 10965 ft: 11710 corp: 3/3b lim: 40 exec/s: 0 rss: 188Mb L: 1/1 MS: 1 CrossOver-
21:14:18  #5	NEW    cov: 10965 ft: 11743 corp: 4/4b lim: 40 exec/s: 0 rss: 188Mb L: 1/1 MS: 1 ChangeBit-
21:14:18  #6	NEW    cov: 10965 ft: 11891 corp: 5/5b lim: 40 exec/s: 0 rss: 188Mb L: 1/1 MS: 1 ChangeByte-
21:14:18  #7	NEW    cov: 10965 ft: 11997 corp: 6/6b lim: 40 exec/s: 0 rss: 188Mb L: 1/1 MS: 1 CrossOver-
21:14:18  llvm_nvme_fuzz.c:232:40: runtime error: left shift of 136 by 24 places cannot be represented in type 'int'
21:14:18      #0 0x4776b4 in fuzz_admin_security_send_command /var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:232:40
21:14:18      #1 0x4a409a in run_cmds /var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:756:3
21:14:18      #2 0x4a3d34 in TestOneInput /var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:797:2
21:14:18      #3 0x19b4859 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x19b4859)
21:14:18      #4 0x19b53c0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x19b53c0)
21:14:18      #5 0x19b6653 in fuzzer::Fuzzer::MutateAndTestOne() (/var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x19b6653)
21:14:18      #6 0x19b8147 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x19b8147)
21:14:18      #7 0x199ca9a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x199ca9a)
21:14:18      #8 0x4a38c3 in start_fuzzer /var/jenkins/workspace/nvmf-phy-short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:851:3
21:14:18      #9 0x7f27c2501db1 in start_thread (/usr/lib64/libc.so.6+0x9fdb1)
21:14:18      #10 0x7f27c24a19df in __GI___clone3 (/usr/lib64/libc.so.6+0x3f9df)
21:14:18  
21:14:18  SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior llvm_nvme_fuzz.c:232:40 in 
21:14:18  MS: 1 InsertRepeatedBytes-; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
21:14:18  0xa,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,0x88,
21:14:18  \x0a\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88\x88
21:14:18  artifact_prefix='./'; Test unit written to ./crash-18eae8b867f0733ccecf564fd6433e2313f5a4c0
21:14:18  Base64: CoiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI
21:14:18  ==695608== ERROR: libFuzzer: deadly signal

## Context (Environment including OS version, SPDK version, etc.)

SPDK: master

**Comment by changpe1** [comment]
@Bianyfan can you take a look? thanks.

**Comment by Bianyfan** [comment]
> @Bianyfan can you take a look? thanks.

This issue is the same as #2549, but we should use typecast for left shift value. I put my commit here: https://review.spdk.io/gerrit/c/spdk/spdk/+/14175 to fix

**Comment by junwenx** [comment]
Thanks all, this issue has been fixed, so close it.
