### ISSUE TITLE
malloc_buf spdk_dma_zmalloc() failed

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#266]
I compiled SPDK 18.01 from source. ./unittests.sh ran without issues. Now I am trying to follow the vhost example (http://www.spdk.io/doc/vhost.html#vhost_start) but that fails for me. `setup.sh` seems to complete fine and /proc/sys/vm/nr_hugepages confirms that the expected number of pages is allocated. But then `app/vhost/vhost` warns that `No free hugepages reported in hugepages-1048576kB` and creating the malloc bdev fails with `*ERROR*: malloc_buf spdk_dma_zmalloc() failed.

Here's the full output:
```
root@pohly-desktop:/fast/work/spdk# HUGEMEM=4096 scripts/setup.sh
root@pohly-desktop:/fast/work/spdk# app/vhost/vhost -S /var/tmp -m 0x3 &
[1] 31280
root@pohly-desktop:/fast/work/spdk# Starting DPDK 17.11.0 initialization...
[ DPDK EAL parameters: vhost -c 0x3 -m 1024 --file-prefix=spdk_pid31280 ]
EAL: Detected 44 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...

root@pohly-desktop:/fast/work/spdk# app.c: 377:spdk_app_start: *NOTICE*: Total cores available: 2
reactor.c: 654:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 426:_spdk_reactor_run: *NOTICE*: Reactor started on core 1 on socket 0
reactor.c: 426:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
copy_engine_ioat.c: 306:copy_engine_ioat_init: *NOTICE*: Ioat Copy Engine Offload Enabled

root@pohly-desktop:/fast/work/spdk# scripts/rpc.py construct_malloc_bdev 64 512 -b Malloc0
bdev_malloc.c: 378:create_malloc_disk: *ERROR*: malloc_buf spdk_dma_zmalloc() failed
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0", 
  "params": {
    "block_size": 512, 
    "num_blocks": 131072, 
    "name": "Malloc0"
  }, 
  "method": "construct_malloc_bdev", 
  "id": 1
}
response:
{
  "message": "Invalid parameters", 
  "code": -32602
}
root@pohly-desktop:/fast/work/spdk# cat /proc/sys/vm/nr_hugepages
2048
```

I'm on Debian Stable,  Linux 4.9.82-1+deb9u2. The machine has a Intel(R) Xeon(R) CPU E5-2699 v4 and 32GB of RAM. Fragmentation shouldn't be an issue, but I'll try rebooting just in case.

BTW, is it possible to get better error reporting via the JSON API? Without the spdk debug output it would be impossible to diagnose the issue, and the log isn't available to an app trying to remote-control spdk via the JSON API.

**Comment by pohly** [comment]
Hmm, perhaps it was memory fragmentation after all. It's working after a reboot :-/

**Comment by dverkamp-intel** [comment]
Just to clarify, the `No free hugepages reported in hugepages-1048576kB` message just means that no 1 GB hugepages are available, which is normal if you ran setup.sh and only configured 2 MB hugepages.

We definitely want to improve error reporting for the RPCs - there's an open card tracking this topic here: https://trello.com/c/gntU51Fq

**Comment by nissan7** [comment]
Using -g parameter it worked.
