### ISSUE TITLE
[build] Link Time Optimization (LTO) & maybe-uninitilized warnings

### ISSUE THREAD

**Issue by Maciej-Szulik** [spdk/spdk#2661]
# Bug report
Final app linking with SPDK (with `--enable-lto`) and DPDK (with `-Db_lto=true`) libs causes `maybe-uninitialized` warnings, which may happen according to https://doc.dpdk.org/guides/prog_guide/lto.html:
> In particular due to interprocedural analysis compiler can produce additional warnings about variables that might be used uninitialized. Some of these warnings might be “false positives” though and you might need to explicitly initialize variable in order to silence the compiler.

Depending on libs linked, issues may occur in other places not described here.
Standalone SPDK and DPDK compilation is fine, issues occur with final linking.

## Expected Behavior

No warnings emitted. 

## Current Behavior
Final linking emits warnings:
```
error: <variable> may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

## Possible Solution

Explicit initialization of variables. In my case:

SPDK:
```
diff --git a/lib/ftl/ftl_init.c b/lib/ftl/ftl_init.c
index 0865a26ce..a4a3ee540 100644
--- a/lib/ftl/ftl_init.c
+++ b/lib/ftl/ftl_init.c
@@ -182,7 +182,7 @@ ftl_check_conf(const struct spdk_ftl_dev *dev, const struct spdk_ftl_conf *conf)
 static int
 ftl_dev_init_bands(struct spdk_ftl_dev *dev)
 {
-       struct ftl_band *band, *pband;
+       struct ftl_band *band, *pband = NULL;
        unsigned int i;
        int rc = 0;
 
diff --git a/lib/nvmf/ctrlr_bdev.c b/lib/nvmf/ctrlr_bdev.c
index 9e755fa1d..3b832360d 100644
--- a/lib/nvmf/ctrlr_bdev.c
+++ b/lib/nvmf/ctrlr_bdev.c
@@ -805,7 +805,7 @@ nvmf_bdev_ctrlr_zcopy_start_complete(struct spdk_bdev_io *bdev_io, bool success,
 {
        struct spdk_nvmf_request        *req = cb_arg;
        struct iovec *iov;
-       int iovcnt;
+       int iovcnt = 0;
 
        if (spdk_unlikely(!success)) {
                int                     sc = 0, sct = 0;
```

DPDK fork:
```
diff --git a/lib/ethdev/rte_class_eth.c b/lib/ethdev/rte_class_eth.c
index c8e8fc9244..ae6fac5207 100644
--- a/lib/ethdev/rte_class_eth.c
+++ b/lib/ethdev/rte_class_eth.c
@@ -68,7 +68,7 @@ eth_representor_cmp(const char *key __rte_unused,
        const struct rte_eth_dev *edev = opaque;
        const struct rte_eth_dev_data *data = edev->data;
        struct rte_eth_devargs eth_da;
-       uint16_t id, nc, np, nf, i, c, p, f;
+       uint16_t id = 0, nc, np, nf, i, c, p, f;
 
        if ((data->dev_flags & RTE_ETH_DEV_REPRESENTOR) == 0)
                return -1; /* not a representor port */
```                

## Steps to Reproduce

1. Compile DPDK with `-Db_lto=true`.
2. Compile SPDK with  `--enable-lto`.
3. Link libraries with some app, difficult to be precise here (with enabled LTO as well).

## Context (Environment including OS version, SPDK version, etc.)
SPDK 22.05
Cross compile for ARM 64.
GCC 10.2

**Comment by jimharris** [comment]
Hi @Maciej-Szulik,

The DPDK issue would need to be fixed in DPDK.  I'm OK with a patch in our DPDK submodule once such a patch is posted to the DPDK mailing list.

For the SPDK ones, the nvmf one should definitely be fixed on master as you suggest.  The ftl code is being rewritten for 22.09, so the code shown above no longer exists.

It looks like autopackage.sh does an LTO build - are we just not catching these because we don't do it with --enable-werror?  It only enables LTO for SPDK though, we should separately fix dpdkbuild/Makefile to set -Db_lto=true when the CONFIG_LTO flag is enabled.

-Jim

**Comment by jimharris** [comment]
I did this patch locally in my ARM-based VM (MacBook Pro M1):

https://review.spdk.io/gerrit/c/spdk/spdk/+/14223

```
./configure --enable-lto --enable-werror
```

This was with master, but everything built and linked fine.  My VM has gcc 11.2 though.  Let's see what CI has to say about it.

-Jim

**Comment by Maciej-Szulik** [comment]
Hi @jimharris,

> The ftl code is being rewritten for 22.09, so the code shown above no longer exists.\

I'll try to rebuild with newer SPDK, maybe it'll catch some other issues.

> This was with master, but everything built and linked fine. My VM has gcc 11.2 though. Let's see what CI has to say about it.

I'm worried you cannot reproduce it in your env and neither can CI. It strongly depends on what functions from what libs and how were used as compiler does some advanced inlining. In my env SPDK as such was built without any problems as well, issues occurred later. However I'm afraid we cannot fix it everywhere and such issues are unpredictable and may appear in the future, even if initial build was successful. 

Proposed fix is harmless, if you are ok with submitting it to master, I'll prepare a patch for SPDK.

>The DPDK issue would need to be fixed in DPDK. I'm OK with a patch in our DPDK submodule once such a patch is posted to the DPDK mailing list.

Could I ask for support with this one?

Thanks

**Comment by Maciej-Szulik** [comment]
I switched to `cd1b7ab0e7709a117ed6d0a727695e0d2749eda6`.
DPDK error persists. 
As expected previous `ftl` disappear, but some new are present:
```
diff --git a/dpdk b/dpdk
--- a/dpdk
+++ b/dpdk
@@ -1 +1 @@
-Subproject commit d0470b2491529499eab84608b41a715f4c240be6
+Subproject commit d0470b2491529499eab84608b41a715f4c240be6-dirty
diff --git a/lib/accel/accel_engine_rpc.c b/lib/accel/accel_engine_rpc.c
index 335239203..e2ce05731 100644
--- a/lib/accel/accel_engine_rpc.c
+++ b/lib/accel/accel_engine_rpc.c
@@ -37,7 +37,7 @@ rpc_accel_get_opc_assignments(struct spdk_jsonrpc_request *request,
 {
 	struct spdk_json_write_ctx *w;
 	enum accel_opcode opcode;
-	const char *name, *engine_name;
+	const char *name, *engine_name = "";
 	int rc;
 
 	if (params != NULL) {
diff --git a/lib/ftl/mngt/ftl_mngt_band.c b/lib/ftl/mngt/ftl_mngt_band.c
index 4757032ce..d87d973eb 100644
--- a/lib/ftl/mngt/ftl_mngt_band.c
+++ b/lib/ftl/mngt/ftl_mngt_band.c
@@ -220,7 +220,7 @@ void
 ftl_mngt_finalize_init_bands(struct spdk_ftl_dev *dev, struct ftl_mngt_process *mngt)
 {
 	struct ftl_band *band, *temp_band, *open_bands[FTL_MAX_OPEN_BANDS];
-	struct ftl_writer *writer;
+	struct ftl_writer *writer = NULL;
 	uint64_t i, num_open = 0, num_shut = 0;
 	uint64_t offset;
 
diff --git a/lib/nvmf/ctrlr_bdev.c b/lib/nvmf/ctrlr_bdev.c
index 2d7c606d6..0474d579f 100644
--- a/lib/nvmf/ctrlr_bdev.c
+++ b/lib/nvmf/ctrlr_bdev.c
@@ -761,7 +761,7 @@ nvmf_bdev_ctrlr_zcopy_start_complete(struct spdk_bdev_io *bdev_io, bool success,
 {
 	struct spdk_nvmf_request	*req = cb_arg;
 	struct iovec *iov;
-	int iovcnt;
+	int iovcnt = 0;
 
 	if (spdk_unlikely(!success)) {
 		int                     sc = 0, sct = 0;
```

**Comment by tomzawadzki** [comment]
[Bug scrub] Going forward enabling LTO on SPDK, will be enabling DPDK LTO in the submodule - Jim has a patch for this. Nightly testing of LTO build is sufficient for now.
@Maciej-Szulik for issues on SPDK side, please report them and will be fixing them as they come.

**Comment by Maciej-Szulik** [comment]
Based on `v22.09.x ` I spotted a new warning, here is the fix patch:
https://review.spdk.io/gerrit/c/spdk/spdk/+/14674

**Comment by Maciej-Szulik** [comment]
Based on v22.09.x I spotted 2 warnings in SPDK, patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/14849
and one in DPDK fork:
```diff --git a/lib/ethdev/rte_class_eth.c b/lib/ethdev/rte_class_eth.c
index 3be84dd45c..5731582d8e 100644
--- a/lib/ethdev/rte_class_eth.c
+++ b/lib/ethdev/rte_class_eth.c
@@ -66,7 +66,7 @@ eth_representor_cmp(const char *key __rte_unused,
        const struct rte_eth_dev *edev = opaque;
        const struct rte_eth_dev_data *data = edev->data;
        struct rte_eth_devargs eth_da;
-       uint16_t id, nc, np, nf, i, c, p, f;
+       uint16_t id = 0, nc, np, nf, i, c, p, f;
 
        if ((data->dev_flags & RTE_ETH_DEV_REPRESENTOR) == 0)
                return -1; /* not a representor port */             
```

**Comment by tomzawadzki** [comment]
All the patches against SPDK posted in this issue were merged, along with one upstreamed to DPDK: https://git.dpdk.org/dpdk-stable/commit/?h=22.11&id=00af2661ac7a56f1f093cb94c4a702ac971b8fe7. Closing.
