### ISSUE TITLE
Timeout due to no space left on device

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2663]
# CI Intermittent Failure

VM-host-PE3 hung during scanbuild_make for 19 minutes and then timed out with a message "No space left on device"

## Link to the failed CI build

[Link](https://ci.spdk.io/results/autotest-per-patch/builds/83749/archive/scanbuild-vg-autotest/build.log)

## Execution failed at

```
00:01:54.031  Type 'make' to build.
00:20:54.162  Cancelling nested steps due to timeout
00:20:54.166  Sending interrupt signal to process
00:21:01.405  script returned exit code 255
00:21:01.413  [Pipeline] }
00:21:01.437  [Pipeline] // timeout
00:21:01.445  [Pipeline] }
00:21:01.467  [Pipeline] // stage
00:21:01.476  [Pipeline] }
00:21:01.480  Timeout has been exceeded
00:21:01.500  [Pipeline] // catchError
00:21:01.511  [Pipeline] stage
00:21:01.513  [Pipeline] { (Stop VM)
00:21:01.529  [Pipeline] sh
00:21:01.810  + vagrant halt
00:21:02.380  /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:835:in `close': No space left on device @ fptr_finalize_flush - /var/lib/libvirt/images/.vagrant.d/perm_test_SNGHNLKSQWKJNMSKUUORCUPOIDBQLTOS (Errno::ENOSPC)
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_83749.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_83750.html

**Comment by mikeBashStuff** [comment]
Just updated title a bit to not point at a specific test (this might have caused failures at different stages, different jobs, etc.). In any case, PE3 should be stable for now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_83752.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_83751.html

**Comment by KKaras169169** [comment]
This issue should not be occuring any more, since @mikeBashStuff cleaned up some disk space, but let's leave it open for a few more days in case anyone has not yet reported their failures.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_84320.html

**Comment by tomzawadzki** [comment]
@karlatec and @KKaras169169 verified that the issue has been fixed and should no longer be occuring.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_88592.html

**Comment by mikeBashStuff** [comment]
> Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_88592.html
This last report doesn't match this issue. It shares similarities (the kernel log in particular) with: https://github.com/spdk/spdk/issues/2602 though. WFP4 seems to be unstable so I will remove it from the pool for now.
