### ISSUE TITLE
[nvme_single_aen] produces way too much output

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#2664]
# Bug report

The nvme_single_aen produces way too much output, overwhelming the build.logs we post.

## Expected Behavior

Don't repeat this print thousands of times:

```
00:04:50.853  0000:5e:00.0: aer_cb for log page 2, aen_event_type: 0x01, aen_event_info: 0x01
00:04:50.853  aer_cb - Resetting Temp Threshold for device: 0000:5e:00.0
00:04:50.854  0000:5e:00.0: Current Temperature:         313 Kelvin (40 Celsius)
00:04:50.854  0000:5e:00.0: aer_cb for log page 2, aen_event_type: 0x01, aen_event_info: 0x01
00:04:50.854  aer_cb - Resetting Temp Threshold for device: 0000:5e:00.0
00:04:50.854  0000:5e:00.0: Current Temperature:         313 Kelvin (40 Celsius)
00:04:50.854  0000:5e:00.0: aer_cb for log page 2, aen_event_type: 0x01, aen_event_info: 0x01
00:04:50.854  aer_cb - Resetting Temp Threshold for device: 0000:5e:00.0
00:04:50.854  0000:5e:00.0: Current Temperature:         313 Kelvin (40 Celsius)
00:04:50.854  0000:5e:00.0: aer_cb for log page 2, aen_event_type: 0x01, aen_event_info: 0x01
```

## Current Behavior

It's printing thousands upon thousands of extra lines to the build logs. See:

https://ci.spdk.io/results/autotest-per-patch/builds/83555/archive/nvme-phy-autotest/build.log

**Comment by curtbruns** [comment]
Yeah - that's excessive logging for sure. This is related to the sighting #2660 . The controller is told to reset the threshold back to its original temp threshold (to stop triggering AEN), but that Set Temp Threshold command doesn't seem to work so the controller keeps triggering AENs. In #2660 it never resets the threshold, but in this failure, it actually eventually does reset the threshold and the test passes. I'll keep digging and trying to reproduce this lost "Set Temp Threshold" command.
