### ISSUE TITLE
JSON RPC: document all methods

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#267]
I'm trying to figure out how to control app/vhost/vhost via RPC. http://www.spdk.io/doc/vhost.html#vhost_config shows some examples, but I found no documentation of the RPC calls used by those examples. `rpc.py --help` helps (sic) a bit, but not as much as one might hope ;-}

For example, scsi_target_num isn't explained:
```
$ scripts/rpc.py add_vhost_scsi_lun --help
usage: rpc.py add_vhost_scsi_lun [-h] ctrlr scsi_target_num bdev_name

positional arguments:
  ctrlr            conntroller name where add lun
  scsi_target_num  scsi_target_num
  bdev_name        bdev name

optional arguments:
  -h, --help       show this help message and exit
```

I assume that different binaries have different APIs. doc/jsonrpc.md should mention which methods are common (`set_log_level` ?) and which are specific to certain binaries.

Here's a complete list of undocumented methods in current master:
```
$ for method in $(git grep SPDK_RPC_REGISTER | sed -e 's/.*"\(.*\)".*/\1/' | grep -v '#define' | sort -u ); do if grep -q -w $method doc/jsonrpc.md; then :; else echo $method; fi; done
add_initiator_group
add_initiators_to_initiator_group
add_ip_address
add_pg_ig_maps
add_portal_group
add_vhost_scsi_lun
apply_nvme_firmware
bdev_inject_error
clear_trace_flag
construct_aio_bdev
construct_error_bdev
construct_lvol_bdev
construct_lvol_store
construct_malloc_bdev
construct_null_bdev
construct_nvme_bdev
construct_pmem_bdev
construct_rbd_bdev
construct_target_node
construct_vhost_blk_controller
construct_vhost_scsi_controller
construct_virtio_pci_blk_bdev
construct_virtio_pci_scsi_bdev
construct_virtio_user_blk_bdev
construct_virtio_user_scsi_bdev
create_pmem_pool
delete_initiator_group
delete_initiators_from_initiator_group
delete_ip_address
delete_pg_ig_maps
delete_pmem_pool
delete_portal_group
delete_target_node
destroy_lvol_store
get_initiator_groups
get_interfaces
get_iscsi_connections
get_iscsi_global_params
get_log_level
get_log_print_level
get_lvol_stores
get_nbd_disks
get_portal_groups
get_rpc_methods
get_scsi_devices
get_subsystems
get_target_nodes
get_trace_flags
get_vhost_controllers
nvmf_subsystem_remove_listener
pmem_pool_info
remove_vhost_controller
remove_vhost_scsi_target
remove_virtio_scsi_bdev
rename_lvol_bdev
rename_lvol_store
resize_lvol_bdev
set_log_level
set_log_print_level
set_trace_flag
set_vhost_controller_coalescing
start_nbd_disk
stop_nbd_disk
target_node_add_lun
```

**Comment by pawelwod** [comment]
Yeah, documentation is very briefly :)
`add_vhost_scsi_lun` is used to add bdev `bdev_name` as SCSI LUN0 to SCSI target id `scsi_target_num`.

**Comment by pohly** [comment]
@pawelwod don't worry, I have the example working and even could add a second target while the virtual machine was running. So I'm fine for now, I just wanted to illustrate the room for improvement in the current command line.

What would be interesting now is how to create additional bdevs in app/vhost, in particular Ceph block devices, iSCSI targets, and NVMeF - not sure which of these are already supported.

**Comment by pawelwod** [comment]
First, you  need to create bdev. iSCSI initiator is not supported (yet).  you can see which type of bdev is supportd by `./scripts/rpc.py -h | egrep 'construct_[^_]+_bdev`. When you will have new bdev constructed you can add it as SCSI LUN to vhost target. Eg for AIO bdev (presenting file or OS block device to vhost):

```
truncate -s 1G /tmp/test_file
scripts/rpc.py construct_aio_bdev /tmp/test_file test_bdev_aio 4096
scripts/rpc.py get_bdevs
[
  {
    "num_blocks": 262144,
    "name": "test_bdev_aio",
    "driver_specific": {
      "aio": {
        "filename": "/tmp/test_file"
      }
    },
    "supported_io_types": {
      "reset": true,
      "nvme_admin": false,
      "unmap": false,
      "read": true,
      "write_zeroes": false,
      "write": true,
      "flush": true,
      "nvme_io": false
    },
    "claimed": false,
    "block_size": 4096,
    "product_name": "AIO disk",
    "aliases": []
  }
]
scripts/rpc.py construct_vhost_scsi_controller vhost0
scripts/rpc.py add_vhost_scsi_lun vhost0 4 "test_bdev_aio"
scripts/rpc.py get_vhost_controllers
[
  {
    "cpumask": "0x1",
    "backend_specific": {
      "scsi": [
        {
          "target_name": "Target 4",
          "luns": [
            {
              "id": 0,
              "bdev_name": "test_bdev_aio"
            }
          ],
          "id": 0,
          "scsi_dev_num": 4
        }
      ]
    },
    "ctrlr": "vhost0"
  }
]
```

**Comment by dverkamp-intel** [comment]
We have the beginnings of RPC documentation here: http://www.spdk.io/doc/jsonrpc.html

This currently only covers a small subset of the available RPC methods, so it definitely needs more work.

**Comment by pohly** [comment]
Let me add that not only does one need a semantic description of the parameters and return values (as in the current documentation), but also a more formal description of the expected types (e.g. int vs. int64 vs. float). I don't know whether it would be useful to do in, for example, a JSON schema (http://json-schema.org/) or whether precise documentation would be enough.

**Comment by pawelwod** [comment]
I would vote for JSON schema for 💯 %

**Comment by pawelwod** [comment]
Reviving this as the documentation force is turned ON. For now there are patches that waiting for another eye :) @pohly Can you help review documentation patches?

https://review.gerrithub.io/#/c/spdk/spdk/+/417719/
https://review.gerrithub.io/#/c/spdk/spdk/+/417718/
https://review.gerrithub.io/#/c/spdk/spdk/+/417237/

The rest of RPC methods (including bdev) will be sent shortly. Can we count on you to help reviewing next patches?

**Comment by pohly** [comment]
pawelwod <notifications@github.com> writes:

> @pohly Can you help review documentation patches?

Sure, no problem.

However, it would be nice if this opportunity was used not only to
document the status quo, but also address some of the open API change
requests (error codes or strings, assigning resources on the server side).
