### ISSUE TITLE
virt_addr  not dword aligned

### ISSUE THREAD

**Issue by skypexu** [spdk/spdk#2673]
# Bug report

"virt_addr xxx not dword aligned", I got this error.
However there is no document said virtual address must be double word aligned!

**Comment by Comphix** [comment]
Please Changpeng give some feedback. Thanks, Gang.

**Comment by changpe1** [comment]
I've replied this via https://github.com/spdk/spdk/issues/1454#issuecomment-1229675475. it's not a bug.

**Comment by changpe1** [comment]
closing it now, @skypexu you can re-open it if can reproduce with SPDK applications.
