### ISSUE TITLE
Aio read disk successfully with an unexpected return value zero , ranther than with expected task requested length non-zero value

### ISSUE THREAD

**Issue by mmlgq** [spdk/spdk#2679]
# Bug report
Test case: Power down of hard disk with IO.
Task requested a non-zero length, but Aio read disk with an unexpected result "success" when getting a return value zero.

## Expected Behavior

The expected result should be processed with unsuccessful when Aio read disk geting a zero return value which is not equal to requsted length.

## Current Behavior
The current result is successful when Aio read disk geting a zero return value in this scenario.

## Possible Solution

static int
bdev_aio_io_channel_poll(struct bdev_aio_io_channel *io_ch)
{
	int nr, i = 0;
	struct bdev_aio_task *aio_task;
        
	struct io_event events[SPDK_AIO_QUEUE_DEPTH];
        
	nr = bdev_user_io_getevents(io_ch->io_ctx, SPDK_AIO_QUEUE_DEPTH, events);
	if (nr < 0) {
		return 0;
	}

	for (i = 0; i < nr; i++) {
		aio_task = events[i].data;
		aio_task->ch->io_inflight--;
		if (events[i].res == aio_task->len) {
			spdk_bdev_io_complete(spdk_bdev_io_from_ctx(aio_task), SPDK_BDEV_IO_STATUS_SUCCESS);
		} else {
			/* From aio_abi.h, io_event.res is defined __s64, negative errno
			 * will be assigned to io_event.res for error situation.
			 * But from libaio.h, io_event.res is defined unsigned long, so
			 * convert it to signed value for error detection.
			 */
			SPDK_ERRLOG("failed to complete aio: rc %"PRId64"\n", events[i].res);
                        if (spdk_unlikely(0 == events[i].res)) {
                                spdk_bdev_io_complete(spdk_bdev_io_from_ctx(aio_task), SPDK_BDEV_IO_STATUS_FAILED);
                        }
                        else {
			         spdk_bdev_io_complete_aio_status(spdk_bdev_io_from_ctx(aio_task), (int)events[i].res);
                        }
		}
	}

	return nr;
}

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Comphix** [comment]
The observed question here is that: events[i].res is 0 and not equal to the aio_task->len, by default it is converted to SUCCESS.

Will you just raise a patch in https://review.spdk.io/gerrit/dashboard/self for more review? Thanks.

```
void
spdk_bdev_io_complete_aio_status(struct spdk_bdev_io *bdev_io, int aio_result)
{
	if (aio_result == 0) {   <<<<<<
		bdev_io->internal.status = SPDK_BDEV_IO_STATUS_SUCCESS;
	} else {
		bdev_io->internal.status = SPDK_BDEV_IO_STATUS_AIO_ERROR;
	}

	bdev_io->internal.error.aio_result = aio_result;

	spdk_bdev_io_complete(bdev_io, bdev_io->internal.status);
}
```

**Comment by mmlgq** [comment]
Hi spdk experts,




I have fixed the issue by the commit.

https://review.spdk.io/gerrit/c/spdk/spdk/+/14364

Could you please help to review the change?




Thanks in advance!

Best Regards//Jun Ran




At 2022-09-05 10:10:19, "GangCao" ***@***.***> wrote:

The observed question here is that: events[i].res is 0 and not equal to the aio_task->len, by default it is converted to SUCCESS.

Will you just raise a patch in https://review.spdk.io/gerrit/dashboard/self for more review? Thanks.

void
spdk_bdev_io_complete_aio_status(struct spdk_bdev_io *bdev_io, int aio_result)
{
	if (aio_result == 0) {   <<<<<<
		bdev_io->internal.status = SPDK_BDEV_IO_STATUS_SUCCESS;
	} else {
		bdev_io->internal.status = SPDK_BDEV_IO_STATUS_AIO_ERROR;
	}

	bdev_io->internal.error.aio_result = aio_result;

	spdk_bdev_io_complete(bdev_io, bdev_io->internal.status);
}

**Comment by changpe1** [comment]
Patch has been merged, closing this issue.
