### ISSUE TITLE
iscsi-vg-autotest and iscsi-uring-vg-autotest fails in nightly mode

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#2680]
# Bug report

Jobs iscsi-vg-autotest and iscsi-uring-vg-autotest fails in nightly mode.
Starting from commit https://review.spdk.io/gerrit/c/spdk/spdk/+/12872

Previous commit pass successfully:
4cbd23e28bb0e2598d3c88f42d533870b21d98d5 vmd: method for forcing a rescan

## Expected Behavior

Jobs should pass.

## Current Behavior

Jobs fails.

## Possible Solution

Revert commit or fix issue.

## Steps to Reproduce

Detected by CI in nightly mode.

## Context (Environment including OS version, SPDK version, etc.)
Fails on CI.

**Comment by KKaras169169** [comment]
Fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/14356

**Comment by jimharris** [comment]
Patch merged.
