### ISSUE TITLE
[nvmf-tcp] spdk initiator with liburing get stuck when running fio test

### ISSUE THREAD

**Issue by xin3liang** [spdk/spdk#2685]
# Bug report

[nvmf-tcp] spdk initiator get stuck when running fio test.

## Expected Behavior

no stuck and finish the fio test.

## Current Behavior

Fio test Just stuck without exiting.

## Steps to Reproduce

1.  config-local.json
```
{
  "general": {
    "username": "root",
    "password": "root",
    "transport": "tcp",
    "skip_spdk_install": "true"
  },
  "target": {
    "nic_ips": ["127.0.0.1"],
    "mode": "spdk",
    "core_mask": "[1-8,28-35,56-64,84-92]",
    "null_block_devices": 1,
    "irq_scripts_dir": "/usr/src/ofa_kernel/x86_64/5.4.0-124-generic/ofed_scripts",
    "zcopy_settings": "true"
  },
  "initiator1": {
    "ip":  "127.0.0.1",
    "nic_ips": ["127.0.0.1"],
    "target_nic_ips": ["127.0.0.1"],
    "mode": "spdk",
    "spdk_dir": "/root/spdk",
    "fio_bin": "/root/fio/fio",
    "kernel_engine": "libaio",
    "num_cores": 1
  },
  "fio": {
    "bs": ["4k"],
    "qd": [2048],
    "rw": ["randread"],
    "rwmixread": 100,
    "run_time": 20,
    "ramp_time": 1,
    "run_num": 1,
    "num_jobs": 1
  }
}

```
2. run fio test on ubuntu20.04
```
root@ubuntu:~/spdk# ./scripts/perf/nvmf/run_nvmf.py -c ~/config-local.json

```

Output
```
...
iodepth=2048' > /root/spdk/nvmf_perf/4k_2048_randread_m_100_1CPU.fio
[initiator1] Created FIO Config:
[initiator1]
[global]
ioengine=/root/spdk/build/fio/spdk_bdev
spdk_json_conf=/root/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999
#numa_cpu_nodes=0,1
#cpus_allowed=5-27,32-55,60-83,88-111

norandommap=1
rw=randread
rwmixread=100
bs=4k
time_based=1
ramp_time=1
runtime=20
rate_iops=0
numjobs=1

[filename0]
filename=Nvme0n1
iodepth=2048
[initiator1] Starting FIO run for job: /root/spdk/nvmf_perf/4k_2048_randread_m_100_1CPU
[initiator1] Using FIO: /root/fio/fio
[initiator1] Runing cmd: sudo /root/fio/fio /root/spdk/nvmf_perf/4k_2048_randread_m_100_1CPU.fio
[2022-09-07 03:32:27.967466] ctrlr.c: 169:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:3be1cdc3-d143-4131-b5a7-d5ca32b3103c from subsystem nqn.2018-09.io.spdk:cnode0 due to keep alive timeout.

*Stuck here*
```
## Context (Environment including OS version, SPDK version, etc.)
```
# fio --version
fio-3.30-80-gdff3
SPDK master: 86619848e (HEAD) Ftl: Add clean restore management path
spdk configure: ./configure --with-uring --with-fio=/root/fio #(latest master)

root@ubuntu:~/spdk# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
root@ubuntu:~/spdk# uname -a
Linux microk8s-4 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xin3liang** [comment]
Note that `kernel initiator` has no this issue.

**Comment by Comphix** [comment]
Would like to confirm that FIO is stuck after below keep alive message?

```
[initiator1] Runing cmd: sudo /root/fio/fio /root/spdk/nvmf_perf/4k_2048_randread_m_100_1CPU.fio
[2022-09-07 03:32:27.967466] ctrlr.c: 169:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:3be1cdc3-d143-4131-b5a7-d5ca32b3103c from subsystem nqn.2018-09.io.spdk:cnode0 due to keep alive timeout.
```

If so, will you have a try after disabling the keep alive by the PRC bdev_nvme_set_options command. Also what's the SPDK version that you are running?

```
{"keep_alive_timeout_ms", offsetof(struct spdk_bdev_nvme_opts, keep_alive_timeout_ms), spdk_json_decode_uint32, true},
```

**Comment by xin3liang** [comment]
> Would like to confirm that FIO is stuck after below keep alive message?

I think is after this keep alive meesage, it only been printed once.

> 
> If so, will you have a try after disabling the keep alive by the PRC bdev_nvme_set_options command. Also what's the SPDK version that you are running?

Sorry, I thought I was running the latest master tip. It was SPDK master commit "86619848e (HEAD) Ftl: Add clean restore management path". I just try the latest master, the stuck issue is fixed by recent changes, but there are still some errors , although it can the finish fio test. 

```
[initiator1] Created FIO Config:
[initiator1]
[global]
ioengine=/root/spdk/build/fio/spdk_bdev
spdk_json_conf=/root/spdk/bdev.conf
thread=1
group_reporting=1
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999
#numa_cpu_nodes=0,1
#cpus_allowed=5-27,32-55,60-83,88-111

norandommap=1
rw=randread
rwmixread=100
bs=4k
time_based=1
ramp_time=1
runtime=20
rate_iops=0
numjobs=1

[filename0]
filename=Nvme0n1
iodepth=2048
[initiator1] Starting FIO run for job: /root/spdk/nvmf_perf/4k_2048_randread_m_100_1CPU
[initiator1] Using FIO: /root/fio/fio
[initiator1] Runing cmd: sudo /root/fio/fio /root/spdk/nvmf_perf/4k_2048_randread_m_100_1CPU.fio
[2022-09-07 08:28:17.269482] ctrlr.c: 169:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:e564c824-dbb7-4d6a-9eef-3282a00e48e2 from subsyst
em nqn.2018-09.io.spdk:cnode0 due to keep alive timeout.
[2022-09-07 08:28:57.317842] ctrlr.c: 169:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:e564c824-dbb7-4d6a-9eef-3282a00e48e2 from subsyst
em nqn.2018-09.io.spdk:cnode0 due to keep alive timeout.
[initiator1] filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=2048
fio-3.30-80-gdff3
Starting 1 thread
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-09-07 08:28:17.309054] nvme_qpair.c: 750:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
[2022-09-07 08:28:17.309121] nvme_ctrlr.c:1011:nvme_ctrlr_fail: *ERROR*: [nqn.2018-09.io.spdk:cnode0] in failed state.
Jobs: 1 (f=1): [r(1)][100.0%][r=1284MiB/s][r=329k IOPS][eta 00m:00s]
filename0: (groupid=0, jobs=1): err= 0: pid=97162: Wed Sep  7 08:28:38 2022
  read: IOPS=327k, BW=1276MiB/s (1338MB/s)(24.9GiB/20007msec)
    slat (nsec): min=83, max=15304, avg=113.63, stdev=48.10
    clat (usec): min=6028, max=12337, avg=6268.20, stdev=83.42
     lat (usec): min=6028, max=12337, avg=6268.31, stdev=83.42
    clat percentiles (usec):
     | 50.000th=[ 6259], 90.000th=[ 6325], 99.000th=[ 6325], 99.500th=[ 6390],
     | 99.900th=[ 6783], 99.990th=[10421], 99.999th=[12125]
   bw (  MiB/s): min= 1270, max= 1286, per=100.00%, avg=1276.28, stdev= 4.22, samples=40
   iops        : min=325256, max=329232, avg=326726.47, stdev=1079.64, samples=40
  lat (msec)   : 10=100.02%, 20=0.01%
   iops        : min=325256, max=329232, avg=326726.47, stdev=1079.64, samples=40                                                                                          [34/1971]
  lat (msec)   : 10=100.02%, 20=0.01%
  cpu          : usr=43.28%, sys=56.71%, ctx=342, majf=0, minf=1996
  IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=88.9%, 8=11.1%, 16=0.1%, 32=0.1%, 64=0.0%, >=64=0.1%
     issued rwts: total=6533474,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=2048

Run status group 0 (all jobs):
   READ: bw=1276MiB/s (1338MB/s), 1276MiB/s-1276MiB/s (1338MB/s-1338MB/s), io=24.9GiB (26.8GB), run=20007-20007msec
[2022-09-07 08:28:57.318134] nvme_qpair.c: 750:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
[2022-09-07 08:28:57.318188] nvme_ctrlr.c:1011:nvme_ctrlr_fail: *ERROR*: [nqn.2018-09.io.spdk:cnode0] in failed state.

[initiator1] FIO run finished. Results in: /root/spdk/nvmf_perf/4k_2048_randread_m_100_1CPU_run_1_initiator1.json

```

> 
> ```
> {"keep_alive_timeout_ms", offsetof(struct spdk_bdev_nvme_opts, keep_alive_timeout_ms), spdk_json_decode_uint32, true},
> ```

This setting should at the initiator side right? I try on the target side it won't work. If so I need to put this setting into config file spdk_json_conf=/root/spdk/bdev.conf , right?

**Comment by xin3liang** [comment]
The above SPDK is build with `./configure --with-uring --with-fio=/root/fio #(latest master)` , the fio running time seems a bit longer than the fio setting `runtime=20`.

When building SPDK without `--with-uring`, no errors during fio test and the running time seems the same as fio setting `runtime=20` :
```
...
[filename0]
filename=Nvme0n1
iodepth=1024
[filename1]
filename=Nvme1n1
iodepth=1024
[initiator1] Starting FIO run for job: /root/spdk/nvmf_perf/4k_1024_randread_m_100_2CPU
[initiator1] Using FIO: /usr/local/bin/fio
[initiator1] filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=1024
filename1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=1024
fio-3.30-86-g55037
Starting 2 threads
TELEMETRY: No legacy callbacks, legacy socket not created
Jobs: 2 (f=2): [r(2)][100.0%][r=2208MiB/s][r=565k IOPS][eta 00m:00s]
filename0: (groupid=0, jobs=2): err= 0: pid=105598: Thu Sep  8 10:57:26 2022
  read: IOPS=564k, BW=2205MiB/s (2312MB/s)(21.5GiB/10004msec)
    slat (nsec): min=160, max=90830, avg=218.58, stdev=141.81
    clat (usec): min=2915, max=7023, avg=3574.90, stdev=341.72
     lat (usec): min=2915, max=7024, avg=3575.12, stdev=341.73
    clat percentiles (usec):
     | 50.000th=[ 3294], 90.000th=[ 3916], 99.000th=[ 4359], 99.500th=[ 4359],
     | 99.900th=[ 4424], 99.990th=[ 5866], 99.999th=[ 6587]
   bw (  MiB/s): min= 2200, max= 2210, per=100.00%, avg=2205.70, stdev= 1.40, samples=40
   iops        : min=563380, max=565868, avg=564660.10, stdev=360.18, samples=40
  lat (msec)   : 4=97.01%, 10=3.02%
  cpu          : usr=57.81%, sys=42.18%, ctx=216, majf=0, minf=1080
  IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=99.2%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.8%
     issued rwts: total=5645912,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1024

Run status group 0 (all jobs):
   READ: bw=2205MiB/s (2312MB/s), 2205MiB/s-2205MiB/s (2312MB/s-2312MB/s), io=21.5GiB (23.1GB), run=10004-10004msec

[initiator1] FIO run finished. Results in: /root/spdk/nvmf_perf/4k_1024_randread_m_100_2CPU_run_1_initiator1.json

```

**Comment by changpe1** [comment]
@xin3liang do you use the default `iodepth` value in nvmf target? e.g: much smaller than 1024 or 2048?

**Comment by xin3liang** [comment]
> iodepth

Use the default iodepth.

**Comment by changpe1** [comment]
> > iodepth
> 
> Use the default iodepth.

I can also reproduce this issue easily, that's because nvmf target uses 128 queue depth as the default value while you use 1024 or 2048 queue depth in initiator, many IOs are queued in initiator which make the ADMIN poller doesn't have a chance to send Keep Alive in time.

This is wrong use case of fio tool but we may also need to take a look of SPDK, ADMIN poller should have high priority in practice.

**Comment by xin3liang** [comment]
> > > iodepth
> > 
> > 
> > Use the default iodepth.
> 
> I can also reproduce this issue easily, that's because nvmf target uses 128 queue depth as the default value while you use 1024 or 2048 queue depth in initiator, many IOs are queued in initiator which make the ADMIN poller doesn't have a chance to send Keep Alive in time.
> 
> This is wrong use case of fio tool but we may also need to take a look of SPDK, ADMIN poller should have high priority in practice.

But I've tried SPDK built without `--with-uring` has no this issue.

**Comment by changpe1** [comment]
> > > > iodepth
> > > 
> > > 
> > > Use the default iodepth.
> > 
> > 
> > I can also reproduce this issue easily, that's because nvmf target uses 128 queue depth as the default value while you use 1024 or 2048 queue depth in initiator, many IOs are queued in initiator which make the ADMIN poller doesn't have a chance to send Keep Alive in time.
> > This is wrong use case of fio tool but we may also need to take a look of SPDK, ADMIN poller should have high priority in practice.
> 
> But I've tried SPDK built without `--with-uring` has no this issue.

I used the POSIX sock but can still reproduce it, I would say it's not related with URING config.

**Comment by changpe1** [comment]
I checked the implementation in bdev_nvme module, everything is OK to me, you may use `bdev_nvme_set_options` RPC in your configuration file to use a bigger value of  `io_queue_requests` , and for getting better performance, a more reasonable value of `iodepth` in target is preferred.

**Comment by xin3liang** [comment]
> I checked the implementation in bdev_nvme module, everything is OK to me, you may use `bdev_nvme_set_options` RPC in your configuration file to use a bigger value of `io_queue_requests` , and for getting better performance, a more reasonable value of `iodepth` in target is preferred.

Thanks @changpe1 for the checking. 
I found that this issue might related to kernel when switching to openEuler with a higher kernel version 5.10,  the same SPDK master branch without any stuck, timeout and errors.

**Comment by junzeng1** [comment]
> > I checked the implementation in bdev_nvme module, everything is OK to me, you may use `bdev_nvme_set_options` RPC in your configuration file to use a bigger value of `io_queue_requests` , and for getting better performance, a more reasonable value of `iodepth` in target is preferred.
> 
> Thanks @changpe1 for the checking. I found that this issue might related to kernel when switching to openEuler with a higher kernel version 5.10, the same SPDK master branch without any stuck, timeout and errors.

**Comment by junzeng1** [comment]
I also didn't reproduce this issue on Ubuntu 18.04.6 LTS (5.11.0-051100-generic) and CentOS Linux 7 (Core) (3.10.0-1062.18.1.el7.x86_64) as well.  But I can easily reproduce similar phenomenon when injecting network problem (like turning down the eth port when test in remote scenario and so on) .  So the reason for fio got stuck may due to the lack of exception or timeout handling mechanism on initiator side for those commands without response.  And the no response may caused by the disconnecting from keepalive timeout.  In addition, from the code of spdk fio_plugin, the admin queue and io queues are dealt in different thread, so the keepalive timeout may not caused by the queue depth.  Then it's still hard to say what cause the delay of keep alive message. Whether it possible for the fio thread to run on the same cpu core with nvmf_tgt reactor ?  (but I didn't reproduce this issue when constructing this scenario manually).  Personally , I think if there is mechanism to handle timeout or similar exception on initiator, this problem may has less influence.

**Comment by junzeng1** [comment]
I've reproduced this issue after changing an environment with liburing version (
https://github.com/axboe/liburing). It seems to be a problem with the uring library path set in Makefile in my  scenario. 
    In "./mk/spdk.common.mk",  the path for uring are set as following (see the fragment listed at the bottom), the CONFIG_URING_PATH is the path which has been set in configure command with "--with-uring=<uring srouce path>". But in fact, we can only find the ".h" file and new created liburing.a  under "<uring source path>/src/include" and "<uring source path>/src". But it's strange, no error reported during the compilation on this environment (In my other environment, it would report error). 
    With the nvmf_tgt compiled with the default uring library path, the initiator fio would hung and report the "keep alive timeout" error. 
    As the third input parameter for  function spdk_sock_listen_ext is NULL when adding listener  for a nvmf subsystem, so the uring implementation is used by default, even posix has been set during the creation of tcp transport. So this issue can be seen when nvmf_tgt is compiled with uring enabled, no matter posix or uring is used.
    Also the above reason can explain why this issue only appear when uring enabled in nvmf_tgt compilation. 
    After changing the path which point to the uring head file and library in spdk.common.mk, this issue disappear.  @xin3liang  @changpe1  Can you try the changes as following in your environment ?  

========== The original in spdk.common.mk ========
ifeq ($(CONFIG_URING),y)
SYS_LIBS += -luring
ifneq ($(strip $(CONFIG_URING_PATH)),)
CFLAGS += -I$(CONFIG_URING_PATH)
LDFLAGS += -L$(CONFIG_URING_PATH)
endif
endif

========== changes in spdk.common.mk and Makefile ========
ifeq ($(CONFIG_URING),y)
SYS_LIBS += -luring
ifneq ($(strip $(CONFIG_URING_PATH)),)
CFLAGS += -I$(CONFIG_URING_PATH)/src/include
LDFLAGS += -L$(CONFIG_URING_PATH)/src
endif
endif

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KanKuox123. log: https://ci.spdk.io/public_build/autotest-per-patch_86582.html

**Comment by changpe1** [comment]
> Another instance of this failure. Reported by @KanKuox123. log: https://ci.spdk.io/public_build/autotest-per-patch_86582.html

The intermittent failure isn't related with this issue, this failure should be a separate one . @KanKuox123

**Comment by KanKuox123** [comment]
> 
Thanks, I will check it again.

**Comment by ksztyber** [comment]
[Bug scrub] This hasn't seen any activity in half a year. Feel free to reopen if the issue is still happaning.
