### ISSUE TITLE
In Multipath mode, if active io_path becomes unreachable, other working io_paths too gets reset resulting in data failure

### ISSUE THREAD

**Issue by parkrish** [spdk/spdk#2688]
# Bug report

I'm testing Multipath mode in SPDK v22.05 at the initiator. I'm observing an issue with it.
In Multipath mode, when one of the paths fail, I see that all the controllers including the properly working ones are reset and all TCP connections to the target are brought down. This result in traffic failure.
Only on expiry of ctrlr-loss-timeout-sec timer, the problematic controller gets deleted automatically and the reset of controllers is stopped. Data traffic happens uninterruptedly only after the expiry of ctrlr-loss-timeout-sec. I tried with different values for reconnect-delay-sec and ctrlr-loss-timeout-sec like 0, -1 etc but nothing resolved this issue. This issue is seen both  in active-active and active-passive mode.

## Expected Behavior

While the problematic controllers need to be periodically probed to check if it is active or not, the working ones shouldn't be disturbed.Or else we may not see the full benefit of multipath mode and the "failover" mode,where similar issue was not there,  seem to fair better than the multipath mode.

## Current Behavior

All Io-paths are seen to be reset periodically till ctrlr-loss-timeout-sec timer expire.

## Steps to Reproduce

Test environment
==============
SPDK v22.05 used in initiator host
Linux Ubuntu 20.04 run on target and initiator servers. 
 Linux nullb device used as target NVME device and was exposed on ports 4420 and 5520 for NVME-OF TCP connections.

1. Start spdk app
 
root@ubuntu-pm-18-226:~/spdk/build/bin# ./nvmf_tgt -i 1 -s 2048 -m 0xF &
[1] 619093
root@ubuntu-pm-18-226:~/spdk/build/bin# [2022-09-01 17:02:12.342953] Starting SPDK v22.05.1-pre git sha1 a09e0dc0b / DPDK 22.03.0 initialization...
[2022-09-01 17:02:12.343086] [ DPDK EAL parameters: [2022-09-01 17:02:12.343096] nvmf [2022-09-01 17:02:12.343105] -c 0xF [2022-09-01 17:02:12.343114] -m 2048 [2022-09-01 17:02:12.343138] --log-level=lib.eal:6 [2022-09-01 17:02:12.343146] --log-level=lib.cryptodev:5 [2022-09-01 17:02:12.343155] --log-level=user1:6 [2022-09-01 17:02:12.343164] --iova-mode=pa [2022-09-01 17:02:12.343172] --base-virtaddr=0x200000000000 [2022-09-01 17:02:12.343181] --match-allocations [2022-09-01 17:02:12.343190] --file-prefix=spdk1 [2022-09-01 17:02:12.343198] --proc-type=auto [2022-09-01 17:02:12.343207] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-09-01 17:02:12.755436] app.c: 603:spdk_app_start: *NOTICE*: Total cores available: 4
[2022-09-01 17:02:12.863144] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 1
[2022-09-01 17:02:12.863301] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 0
[2022-09-01 17:02:12.863228] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 2
[2022-09-01 17:02:12.863303] reactor.c: 947:reactor_run: *NOTICE*: Reactor started on core 3
[2022-09-01 17:02:12.863490] accel_engine.c: 969:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
 
2. Connect to target running on port 4420 for namespace nqn.2014-08.com.abc:nvme:nvm-subsystem-sn-d70005
 
root@ubuntu-pm-18-226:~/spdk# ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t tcp -a 66.1.1.2 -s 4420 -f ipv4 -n nqn.2014-08.com.abc:nvme:nvm-subsystem-sn-d70005 --reconnect-delay-sec 5 --ctrlr-loss-timeout-sec 8 --fast-io-fail-timeout-sec 7
 
3. Connect to target running on port 5520 for same namespace nqn.2014-08.com.abc:nvme:nvm-subsystem-sn-d70005 with multipath option.
 
./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t tcp -a 66.1.1.2 -s 5520 -f ipv4 -n nqn.2014-08.com.abc:nvme:nvm-subsystem-sn-d70005 -x multipath --reconnect-delay-sec 5 --ctrlr-loss-timeout-sec 8 --fast-io-fail-timeout-sec 7
 
4. Map SPDK bdev to Linux NBD device
 
root@ubuntu-pm-18-226:~/spdk# ./scripts/rpc.py nbd_start_disk Nvme0n10 /dev/nbd0
/dev/nbd0

5. Simulate n/w failure for traffic to 4420 , by adding iptables rule at the target.

iptables -A INPUT -p tcp --destination-port 4420 -j DROP

6. It was observed that the working connections were also brought down

root@ubuntu-pm-18-226:~/spdk# ./scripts/rpc.py bdev_nvme_get_controllers -n Nvme0
[
{
"name": "Nvme0",
"ctrlrs": [
{
"state": "reconnect_is_delayed",
"trid": {
"trtype": "TCP",
"adrfam": "IPv4",
"traddr": "66.1.1.2",
"trsvcid": "4420",
"subnqn": "nqn.2014-08.com.abc:nvme:nvm-subsystem-sn-d70005"
},
"cntlid": 1,
"host": {
"nqn": "nqn.2014-08.org.nvmexpress:uuid:8edd9463-04d1-4c90-bb4c-a30561c9069b",
"addr": "",
"svcid": ""
}
},
{
"state": "failed",
"trid": {
"trtype": "TCP",
"adrfam": "IPv4",
"traddr": "66.1.1.2",
"trsvcid": "5520",
"subnqn": "nqn.2014-08.com.abc:nvme:nvm-subsystem-sn-d70005"
},
"cntlid": 1,
"host": {
"nqn": "nqn.2014-08.org.nvmexpress:uuid:8edd9463-04d1-4c90-bb4c-a30561c9069b",
"addr": "",
"svcid": ""
}
}
]
}
]

**Comment by shuhei-matsumoto** [comment]
Hi @parkrish 

Thanks for testing multipath and reporting this issue. I could reproduce this issue locally.
However, the behavior we saw, not only 4420 but also 5520 down, is a limitation of the operation "iptables -A INPUT -p tcp --destination-port 4420 -j DROP" ?

If I use two network interfaces and bring down one network interface by using ip command, only one path was disconnected and failover occurred expectedly. ifdown/up and ipconfig commands were same.

Will you test again by using two network interfaces and bring down/up either interface?

A tips, please set a option --transport_-ack-timeout of the bdev_nvme_set_options RPC to a sufficiently small value, for example, 9 or 10. Otherwise, timeout is very long and you have to wait until minutes passed.

```
./scripts/rpc.py -s /var/tmp/host.sock bdev_nvme_set_options -e 10
./scripts/rpc.py -s /var/tmp/host.sock bdev_nvme_attach_controller -b nvme0 -t tcp -a 10.0.2.15 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1 -o 5 -l -1
nvme0n1
./scripts/rpc.py -s /var/tmp/host.sock bdev_nvme_attach_controller -b nvme0 -t tcp -a 192.168.155.5 -s 4420 -f ipv4 -n nqn.2016-06.io.spdk:cnode1 -o 5 -l -1 -x multipath
nvme0n1
./scripts/rpc.py -s /var/tmp/host.sock nbd_start_disk nvme0n1 /dev/nbd0
```

By the way, thanks to your issue report, I found a bug and could fix it.
https://review.spdk.io/gerrit/c/spdk/spdk/+/14446

The bug caused a segmentation fault in the initiator if the NBD is started after bringing down an interface.

**Comment by parkrish** [comment]
@shuhei-matsumoto , Thanks for looking into the issue and sharing your inputs. The issue got resolved on setting transport-ack-timeout to a low value(./scripts/rpc.py -s /var/tmp/host.sock bdev_nvme_set_options -e 10).

On setting this, even if I used iptables rule("iptables -A INPUT -p tcp --destination-port 4420 -j DROP") to block traffic to port 4420 , the traffic continued on port 5520.

And as you suggested, the scenario of having different IP addresses for the primary path and secondary path also worked fine. But this case too required transport-ack-timeout to be set to a low value. Otherwise, both the controllers kept resetting.

Thanks once again for the quick resolution.

**Comment by shuhei-matsumoto** [comment]
Hi @parkrish 

Thank you so much, I only tried
- iptables port DROP
- ip link down/up + transport_ack_timeout

I have not tried

- iptabloes port DROP + transport_ack_timeout

yet. 

I am very happy to know reducing transport_ack_timeout resolved your case.

I will try adding some notes about transport_ack_timeout into https://spdk.io/doc/nvme_multipath.html

Even after this issue is closed, I can work on patches and ping you when doc is updated.
But you can keep opening this issue to wait until document is updated.
Please close this issue when you are OK.

**Comment by shuhei-matsumoto** [comment]
I pushed a patch to suggest tuning transport_ack_timeout in doc/nvme_multipath.doc
https://review.spdk.io/gerrit/c/spdk/spdk/+/14482

**Comment by parkrish** [comment]
@shuhei-matsumoto , Thanks for your support. I shall close the issue.
