### ISSUE TITLE
rw_ios_per_sec does not limit properly on malloc bdev exposed over virtio-blk to qemu instance

### ISSUE THREAD

**Issue by artek-koltun** [spdk/spdk#2691]
# Bug report
`rw_ios_per_sec` does not limit properly on a malloc bdev exposed over virtio-blk to a qemu instance

## Expected Behavior

read/write iops are not higher than a value set in `rw_ios_per_sec`

## Current Behavior

Fio reported iops are in a specific scale to set values in `rw_ios_per_sec`
For example:
for `fio --filename=/dev/vda --rw=read  --runtime=30 --time_based --name=job0 --bs=4096` the fio reported iops are
| rw_ios_per_sec value| fio reported iops|
| --- | ----------- |
| 1000| ~60 000|
| 2000| ~120 000|
| 4000| ~240 000|

Here we can see that required and actually reported iops are in the proportion 1 - 60

My Fio output for `rw_ios_per_sec`=1000 and fio bs=4096
```
fio-3.29
Starting 1 process
Jobs: 1 (f=1): [R(1)][100.0%][r=236MiB/s][r=60.5k IOPS][eta 00m:00s]
job0: (groupid=0, jobs=1): err= 0: pid=1279: Mon Sep 12 11:25:49 2022
  read: IOPS=62.5k, BW=244MiB/s (256MB/s)(7324MiB/30001msec)
    clat (nsec): min=362, max=12209k, avg=14889.42, stdev=108687.40
     lat (nsec): min=388, max=12209k, avg=14989.63, stdev=108687.76
    clat percentiles (nsec):
     |  1.00th=[   644],  5.00th=[  1080], 10.00th=[  1096], 20.00th=[  1112],
     | 30.00th=[  1128], 40.00th=[  1144], 50.00th=[  1176], 60.00th=[  1176],
     | 70.00th=[  1192], 80.00th=[  1240], 90.00th=[  1352], 95.00th=[  1464],
     | 99.00th=[872448], 99.50th=[880640], 99.90th=[880640], 99.95th=[897024],
     | 99.99th=[954368]
   bw (  KiB/s): min=227328, max=258048, per=100.00%, avg=250193.46, stdev=12191.70, samples=59
   iops        : min=56832, max=64512, avg=62548.42, stdev=3047.96, samples=59
  lat (nsec)   : 500=0.34%, 750=0.98%, 1000=0.67%
  lat (usec)   : 2=95.97%, 4=0.14%, 10=0.07%, 20=0.16%, 50=0.10%
  lat (usec)   : 100=0.01%, 250=0.01%, 500=0.01%, 750=0.01%, 1000=1.56%
  lat (msec)   : 2=0.01%, 20=0.01%
  cpu          : usr=5.68%, sys=18.98%, ctx=29612, majf=0, minf=14
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1875068,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=244MiB/s (256MB/s), 244MiB/s-244MiB/s (256MB/s-256MB/s), io=7324MiB (7680MB), run=30001-30001msec

Disk stats (read/write):
  vda: ios=29254/0, merge=0/0, ticks=51452/0, in_queue=51452, util=97.29%
```

---

for `fio --filename=/dev/vda --rw=read  --runtime=30 --time_based --name=job0 --bs=512` the fio reported iops are
| rw_ios_per_sec value| fio reported iops|
| --- | ----------- |
| 1000| ~480 000|
| 2000| ~700 000|
| 4000| ~700 000|

And here we can observe that required and actually reported iops are in the proportion 1 - 480 up to some system performance limit

---
Note: Approximately the same numbers can be seen on writes as well
Note: Bandwidth QoS limits work as expected

## Possible Solution
--

## Steps to Reproduce

1. Build SPDK b4e9ce466cbbbfdc7ef235fbf6b6cb29bcb11921 (master for 9/13/22)
Use QEMU emulator version 7.0.50
2. Run spdk
```
LD_LIBRARY_PATH=build/lib:dpdk/build/lib build/bin/spdk_tgt
```
3. Create malloc bdev
```
scripts/rpc.py bdev_malloc_create 512 4096 -b Malloc0
```
or
```
scripts/rpc.py bdev_malloc_create 512 512 -b Malloc0
```
4. Create virtio-blk backed by created Malloc0
```
scripts/rpc.py vhost_create_blk_controller --cpumask 0x1 vhost.1 Malloc0
```
5. Setup QoS on iops for Malloc0
```
scripts/rpc.py  bdev_set_qos_limit Malloc0 --rw_ios_per_sec=1000
```
6. Check bdev that "rw_ios_per_sec" is set to 1000,
```
scripts/rpc.py bdev_get_bdevs --name Malloc0 | grep "rw_ios_per_sec"
```

7. Run a virtual machine with attached virtio-blk:
```
sudo qemu-system-x86_64 \
  --enable-kvm \
  -cpu host \
  -nographic \
  -smp 24 \
  -drive file=<path_to_image>,if=none,id=disk \
  -device ide-hd,drive=disk,bootindex=0 \
  -monitor tcp:127.0.0.1:8888,server,wait=off \
	-m 4G \
	-object memory-backend-file,id=mem0,size=4G,mem-path=/dev/hugepages,share=on,prealloc=yes \
	-numa node,memdev=mem0 \
	-chardev socket,id=char1,path=<path_unix_socket_for_virtio_blk>/vhost.1 \
	-device vhost-user-blk-pci,id=blk0,chardev=char1
```
In my config [Fedora36 ](https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.qcow2) image was used

8. Run fio against attached device
```
fio --filename=/dev/vda --rw=read  --runtime=30 --time_based --name=job0 --bs=4096
```

## Context (Environment including OS version, SPDK version, etc.)
* SPDK b4e9ce466cbbbfdc7ef235fbf6b6cb29bcb11921
* QEMU emulator version 7.0.50
* [Fedora36 vm image ](https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.qcow2)
* Host OS: Fedora34/Ubuntu18.04
* fio 3.29

**Comment by Comphix** [comment]
Could you have a try with other Bdev type like NULL bdev or NVMe bdev?

IOs to Malloc Bdev could be handled in a more efficient way and QoS may not handle properly here.

**Comment by artek-koltun** [comment]
Hi @Comphix 
I checked with Null and NVMe bdevs. Unfortunately, the fio iops numbers are different from `rw_ios_per_sec` value

**Comment by Comphix** [comment]
Thanks for your quick verification on other Bdev types.

So the question here is that FIO's IOPS is different from Bdev's QoS setting? And it is also mentioned the Bandwidth of QoS is correct？

Could the kernel virtio-blk driver do some optimization here to merge some continuous IOs? And you may also run `bdev_get_iostat` RPC command or `scripts\iostat.py` to get the IO stats from the bdev directly.

Maybe you could have a try with randread or randwrite and use the same QoS setting (e.g., rw_ios_per_sec = 1000). Or you could try to use SPDK's user space virtio-blk driver?

**Comment by artek-koltun** [comment]
It looks like you are correct with this implication.
After running `fio --filename=/dev/vda --rw=readwrite  --runtime=30 --time_based --name=job0` with 1000 iops limit  on bdev, `bdev_get_iostat` shows
```
{
  "tick_rate": 3300000000,
  "ticks": 12344094964309602,
  "bdevs": [
    {
      "name": "Malloc0",
      "bytes_read": 7337365504,
      "num_read_ops": 28180,
      "bytes_written": 0,
      "num_write_ops": 0,
      "bytes_unmapped": 0,
      "num_unmap_ops": 0,
      "read_latency_ticks": 127126578072,
      "write_latency_ticks": 0,
      "unmap_latency_ticks": 0
    }
  ]
}

```
It looks like the kernel driver indeed performs some optimizations and merge continuous IOs

Thank you for the help
