### ISSUE TITLE
When performing I/O as much as the MDTS of device, is it possible to support SPDK to perform I/O without split the command?

### ISSUE THREAD

**Issue by warrick3050** [spdk/spdk#2692]
When the MDTS value supported by the device is 9 (2^9=512), even if 2 MiB write is actually performed, 
SPDK is performing split(503+9) into two write commands due to the limitation of the `NVME_MAX_PRP_LIST_ENTRIES` value.

It is understood that the `NVME_MAX_PRP_LIST_ENTRIES` value, which determines the size of the PRP list, 
must be set to a value less than 512 (actually 503) by the design of the SPDK that processes the `nvme_tracker` structure as a 4 KiB page. [Re: [SPDK] Determination of NVMe max_io_xfer_size](https://lists.01.org/hyperkitty/list/spdk@lists.01.org/message/4JTKCREKA47J2LQE2VE6HRYGPHTCUKNO/)

I simply changed the `NVME_MAX_PRP_LIST_ENTRIES` value (503 -> 1015) and did an I/O test. (nvme_tracker = 4k->8k)
However, If IOSIZE is set to 2MiB, 
it can be confirmed that the status of multiple completion queue entries is returned as sct 0h, sc 13h (PRP Offset Invalid).

This may be resolved if logic pointing to the next PRP List is added when crossing the 4KiB Page boundary in `nvme_pcie_prp_list_append()` of `lib/nvme/nvme_pcie_common.c`, but I did not proceed with the analysis further.

I would like to know the official direction from the SPDK side.

In the current trend of increasing MDTS value ​​supported by devices,
I would like to know if there are any plans to support the size of the `nvme_tracker` structure larger than 4 KiB Pages in the SPDK.

**Comment by jimharris** [comment]
Hi @warrick3050,

I am not aware of anyone planning to support larger nvme_tracker structures.

All memory for qpairs, including nvme_trackers, are pre-allocated.  So supporting larger nvme_tracker sizes means that more memory is then consumed, even if the application does not require the larger sizes.  The nvme_tracker sizes could potentially be configurable, but in practice there is a negligible difference between a single 2MB write and two writes totaling 2MB, so there is little motivation to add the extra complexity.

For use cases where someone wants to force a chained PRP list to validate an SSD, there is `spdk_nvme_ctrlr_io_cmd_raw_no_payload_build` which allows the application to completely define everything that goes into the SQE, including the PRP pointer.  This can be used to build arbitrary PRP lists of any size.

-Jim

**Comment by warrick3050** [comment]
@jimharris,  Thanks for your response.

Like your comment I'm currently checking the list of chained PRPs while validating the SSD.

Before proceeding with the use of `spdk_nvme_ctrlr_io_cmd_raw_no_payload_build`, I would like to ask one more question.

> This may be resolved if logic pointing to the next PRP List is added when crossing the 4KiB Page boundary in nvme_pcie_prp_list_append() of lib/nvme/nvme_pcie_common.c, but I did not proceed with the analysis further.

If I don't need to consider excessive memory consumption, 
it would be really appreciated if you could answer whether the correction direction I mentioned above is correct.

**Comment by jimharris** [comment]
> Before proceeding with the use of `spdk_nvme_ctrlr_io_cmd_raw_no_payload_build`, I would like to ask one more question.
> 
> > This may be resolved if logic pointing to the next PRP List is added when crossing the 4KiB Page boundary in nvme_pcie_prp_list_append() of lib/nvme/nvme_pcie_common.c, but I did not proceed with the analysis further.
> 
> If I don't need to consider excessive memory consumption, it would be really appreciated if you could answer whether the correction direction I mentioned above is correct.

At a high level, that is correct.

**Comment by ajaykumar-mnit** [comment]
Hi @warrick3050 , I am going through the same page size constraint in the case of SGLs. If you have implemented the next pointer to PRP list when exceeding the page size, Can you please guide me for that, Since I also want to do the same for SGLs.
