### ISSUE TITLE
Using dpdk eth ports under SPDK

### ISSUE THREAD

**Issue by reeveyoung** [spdk/spdk#2695]
This is basically a question, not an issue, because I cannot find anywhere else to ask SPDK experts.

I'm trying to write an experimental application under SPDK to take received packet from two eth ports and write to NVME controller through SPDK APIs. Usually for DPDK app, I just call rte_eal_init(), but under SPDK framework, spdk_env_init() calls rte_eal_init() so I couldn't call it twice. Therefore I reply on spdk_env_init() to do the initialization for eth-dev as well. 

The problem is that the app could find an eth dev/port, obviously it's not discovered/initialized though both eth ports are bound to vfio-pci kernel module.

I understand SPDK is for storage, but I don't think it should block eth dev usage of dpdk though. Is there filtering in SPDK on non-storage device? Am I missing anything?

**Comment by changpe1** [comment]
@reeveyoung I think you can add the eth driver compilation option in spdk/dpdkbuild/Makefile or you can use distros DPDK library when compiling SPDK.

**Comment by reeveyoung** [comment]
> @reeveyoung I think you can add the eth driver compilation option in spdk/dpdkbuild/Makefile or you can use distros DPDK library when compiling SPDK.

May I know what are the appropriate options?

**Comment by changpe1** [comment]
@reeveyoung you may reach us in slack channel for questions, so closing this issue now.
