### ISSUE TITLE
SPDK crashes when testing nvmf-tcp in some abnormal connection

### ISSUE THREAD

**Issue by YuanlongJing** [spdk/spdk#2696]
# Bug report

SPDK crashes when testing nvmf-tcp in some abnormal connection.

## Steps to Reproduce
1. SPDK used as nvmf-tcp server creates some targets.
2. Initiator  connecting target  failed  by command("nvme connect" )because of the special reason(such as physical machine limited).
3. SPDK will crash.

##Crash log:
#0  0x00007f3d13110207 in raise () from /lib64/libc.so.6
#1  0x00007f3d131118f8 in abort () from /lib64/libc.so.6
#2  0x00007f3d13109026 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f3d131090d2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f3d2e437814 in handle_fatal_signal (signum=6) at signal_handler.cc:140
#5  <signal handler called>
#6  0x00007f3d13110207 in raise () from /lib64/libc.so.6
#7  0x00007f3d131118f8 in abort () from /lib64/libc.so.6
#8  0x00007f3d13109026 in __assert_fail_base () from /lib64/libc.so.6
#9  0x00007f3d131090d2 in __assert_fail () from /lib64/libc.so.6
#10 0x00007f3d2e437814 in handle_fatal_signal (signum=11) at signal_handler.cc:140
#11 <signal handler called>
#12 spdk_sock_is_connected (sock=0x0) at sock.c:449
#13 0x00007f3d14c01091 in spdk_nvmf_tcp_sock_process (tqpair=tqpair@entry=0x1ef93400) at tcp.c:1802
#14 0x00007f3d14c019f9 in spdk_nvmf_tcp_sock_cb (arg=0x1ef93400, group=<optimized out>, sock=<optimized out>)
    at tcp.c:2262
#15 0x00007f3d142edb7c in spdk_sock_group_impl_poll_count (max_events=32, group=0x28a6cc0, group_impl=0x280bcc0)
    at sock.c:618
#16 spdk_sock_group_poll_count (group=0x28a6cc0, max_events=max_events@entry=32) at sock.c:645
#17 0x00007f3d142edc1a in spdk_sock_group_poll (group=<optimized out>) at sock.c:582
#18 0x00007f3d14c0197d in spdk_nvmf_tcp_poll_group_poll (group=0x27eecb0) at tcp.c:2394
#19 0x00007f3d14bf7bbb in spdk_nvmf_poll_group_poll (ctx=<optimized out>) at nvmf.c:100
#20 0x00007f3d13ee245d in _spdk_thread_poll (now=5345717753705266, max_msgs=0, thread=0x2ff2a80) at thread.c:593
#21 spdk_thread_poll (thread=thread@entry=0x2ff2a80, max_msgs=max_msgs@entry=0, now=5345717753705266) at thread.c:680
#22 0x00000000004b9c98 in reactor_run (reactor=0x2904300) at service/nvmf/reactor.c:240
#23 _spdk_reactor_run (arg=0x2904300) at service/nvmf/reactor.c:289
#24 0x00000000004ba008 in spdk_reactors_start () at service/nvmf/reactor.c:384
#25 0x00000000004b86de in app_start (args=0x7fff023e38b0) at service/nvmf/nvmf_target.c:206
#26 0x00007f3d37cc6dd5 in start_thread () from /lib64/libpthread.so.0
#27 0x00007f3d131d7ead in clone () from /lib64/libc.so.6

## Expected Behavior
Step 3 : SPDK works well

## Possible Solution

if qpair adding to group failed, please remove related sock info from sock group.
`  static int
spdk_nvmf_tcp_poll_group_add(struct spdk_nvmf_transport_poll_group *group,
        struct spdk_nvmf_qpair *qpair)
{
 struct spdk_nvmf_tcp_poll_group *tgroup;
 struct spdk_nvmf_tcp_qpair *tqpair;
 int    rc;

 tgroup = SPDK_CONTAINEROF(group, struct spdk_nvmf_tcp_poll_group, group);
 tqpair = SPDK_CONTAINEROF(qpair, struct spdk_nvmf_tcp_qpair, qpair);

 rc = spdk_sock_group_add_sock(tgroup->sock_group, tqpair->sock,
          spdk_nvmf_tcp_sock_cb, tqpair); //加入sock组成功
 if (rc != 0) {
  SPDK_ERRLOG("Could not add sock to sock_group: %s (%d)\n",
       spdk_strerror(errno), errno);
  return -1;
 }

 rc =  spdk_nvmf_tcp_qpair_sock_init(tqpair);
 if (rc != 0) {
  SPDK_ERRLOG("Cannot set sock opt for tqpair=%p\n", tqpair);
  return -1;
 }

 rc = spdk_nvmf_tcp_qpair_init(&tqpair->qpair);
 if (rc < 0) {
  SPDK_ERRLOG("Cannot init tqpair=%p\n", tqpair);
  return -1;
 }

 rc = spdk_nvmf_tcp_qpair_init_mem_resource(tqpair);
 if (rc < 0) {
  **spdk_sock_group_remove_sock(tgroup->sock_group, tqpair->sock);//remove sock** 
  SPDK_ERRLOG("Cannot init memory resource info for tqpair=%p\n", tqpair);
  return -1;
 }

 tqpair->group = tgroup;
 tqpair->state = NVME_TCP_QPAIR_STATE_INVALID;
 TAILQ_INSERT_TAIL(&tgroup->qpairs, tqpair, link);

 return 0;
}`

## Context (Environment including OS version, SPDK version, etc.)
SPDK version 20.04

**Comment by changpe1** [comment]
@YuanlongJing SPDK 20.04 is out of maintenance, do you see this issue with latest main branch?

**Comment by changpe1** [comment]
This issue has been fixed via commit 2bd41c5187b, closing it now.
