### ISSUE TITLE
riscv

### ISSUE THREAD

**Issue by martinzhu2022** [spdk/spdk#2698]
# Bug report

## Steps to Reproduce

1.
2.
3.
4.

**Comment by martinzhu2022** [comment]
Do we plan to support riscv arch?

**Comment by changpe1** [comment]
> Do we plan to support riscv arch?

We don't have a plan for RISCV, but you can have a try on RISCV platform and contribute patches back to SPDK project while enabling SPDK on RISCV(if necessary).
