### ISSUE TITLE
[UT/bdev/part.c] The argument "freebsd13" is judged  invalid during freebsd-vg-autotest

### ISSUE THREAD

**Issue by KanKuox123** [spdk/spdk#2699]
# CI Intermittent Failure
This UT has been successfully built with the argument "freebsd12". 

## Link to the failed CI build
https://review.spdk.io/gerrit/c/spdk/spdk/+/14074
https://ci.spdk.io/results/autotest-per-patch/builds/85512/archive/freebsd-vg-autotest/build.log

## Execution failed at
00:01:06.253  + ./spdk/scripts/vagrant/create_vbox.sh -n 10 -s 12288 -x http://proxy-dmz.intel.com:911 -p libvirt --qemu-emulator=/usr/local/qemu/vanilla-v7.0.0/bin/qemu-system-x86_64 -b /var/lib/libvirt/images/backends/ex4-nvme.img -H -a -v freebsd13
**00:01:06.253    Invalid argument "freebsd13"**
00:01:06.253    Try: "./spdk/scripts/vagrant/create_vbox.sh -h"
00:01:06.253  + cd freebsd13-libvirt
00:01:06.253  jbp/jenkins/jjb-config/jobs/scripts/vagrant_create_vm.sh: line 1: cd: freebsd13-libvirt: No such file or directory
00:01:06.264  [Pipeline] }
00:01:06.285  [Pipeline] // stage
00:01:06.294  [Pipeline] }
00:01:06.297  ERROR: script returned exit code 1
00:01:06.314  [Pipeline] // catchError
00:01:06.325  [Pipeline] stage
00:01:06.327  [Pipeline] { (Epilogue)
00:01:06.342  [Pipeline] sh
00:01:06.622  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:01:06.622  jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: line 8: cd: /var/jenkins/workspace/freebsd-vg-autotest/output: No such file or directory
00:01:06.632  [Pipeline] }
00:01:06.651  [Pipeline] // stage
00:01:06.660  [Pipeline] }
00:01:06.680  [Pipeline] // wrap
00:01:06.692  [Pipeline] }
00:01:06.712  [Pipeline] // node
00:01:06.725  [Pipeline] End of Pipeline
00:01:06.738  ERROR: script returned exit code 1
00:01:06.743  Finished: FAILURE

**Comment by mikeBashStuff** [comment]
Previous patchsets under https://review.spdk.io/gerrit/c/spdk/spdk/+/14074 were missing the d21dc1501fd02f3d5388227b02ad1b50fe1a1161 commit - latest patchset (6) should now work just fine under freebsd-vg-autotest job.
