### ISSUE TITLE
Check if API for accelerate engine could be optimized or not

### ISSUE THREAD

**Issue by YuanlongJing** [spdk/spdk#2701]
# Bug report
We would like to use SPDK accel_engine.
Please refer to include/spdk/accel_engine.h

Some API such as ”spdk_accel_submit_copy“ need arg: spdk io channel.
Could user get it from API: "struct spdk_io_channel *spdk_accel_engine_get_io_channel(void)"?
It seems that it's not necessary to bed exposed to user.
User don't care about io channel. 
Please check if related APIs could be optimized for user.
Thansk. 
 
SPDK ver : 22.05

**Comment by peluse** [comment]
Hi @YuanlongJing so the channel is required as an input parameter to all of the other accel_fw API so the caller must first get this handle so it can pass it on subsequent calls much in the same fashion as spdk_bdev_get_io_channel() used in examples like the fio plug-in and hello_bdev.  Does that make sense?

**Comment by YuanlongJing** [comment]
Got it.
Thank you very much
