### ISSUE TITLE
Check if ISCSI over RDMA supports or not

### ISSUE THREAD

**Issue by YuanlongJing** [spdk/spdk#2704]
# Bug report

We checked related doc of SPDK. It seems that SPDK supports iscsi over tcp no rdma.
Does it support iscsi over rdma ?  
If not, Would you have plan to release it?

Thank you very much.

**Comment by changpe1** [comment]
> # Bug report
> We checked related doc of SPDK. It seems that SPDK supports iscsi over tcp no rdma. Does it support iscsi over rdma ? If not, Would you have plan to release it?
> 
> Thank you very much.

Do you mean iSER? we don't have a plan to support it.

**Comment by YuanlongJing** [comment]
Got it. Thanks.
