### ISSUE TITLE
Test failures due to CI network downtime

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2706]
# CI Intermittent Failure

Ci has reported some tests as failed due to network issues. The logs are incomplete for builds like:
https://ci.spdk.io/public_build/autotest-per-patch_85855.html
https://ci.spdk.io/public_build/autotest-per-patch_85856.html

This issue is not really bug-related, but it will let us retrigger some of the failed tests and should be closed after we confirm the network is stable.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_85855.html

**Comment by ksztyber** [comment]
A week occurred and no other similar failures have been reported, closing.
