### ISSUE TITLE
xNVME bdev performance vs NVME bdev performance

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2708]
There is an ongoing work to hooking xNVME bdev into our existing performance test suites tracked under https://review.spdk.io/gerrit/q/topic:xnvme-perf. The main goal for now is to compare it with NVME bdev under `bdevperf` based on the TC1 setup. All the results so far seem to show much lower performance on the xNVME end (examples below). This issue is meant to be ground for discussion and/or troubleshooting to understand where the difference is coming from.

Notes:
* OS: fedora35, 5.15.7-200.fc35.x86_64
* examples prepared for this issue were executed without preconditioning
* model of all the drives used in the examples: `KCM6XVUL3T20`
*  all drives used in the examples were places on the same NUMA node (0)
*  xNVME uses io_uring for the io_mechanism

In all cases `bdevperf` was executed as the following:
```
bdevperf --json bdev.conf -q 192 -o 4096 -w randread -t 120 -m '[0]' -r /var/tmp/spdk.sock -z
```

xNVME results:
* 1 nvme drive:
```
Running I/O for 120 seconds...
 Job: nvme0n1 (Core Mask 0x1)
         nvme0n1             :  495018.45 IOPS    1933.67 MiB/s
 =============================================================
 Total                       :  495018.45 IOPS    1933.67 MiB/s
```
* 5 nvme drives:
```
Running I/O for 120 seconds...
 Job: nvme15n1 (Core Mask 0x1)
         nvme15n1            :   89365.17 IOPS     349.08 MiB/s
 Job: nvme8n1 (Core Mask 0x1)
         nvme8n1             :   89365.34 IOPS     349.08 MiB/s
 Job: nvme4n1 (Core Mask 0x1)
         nvme4n1             :   89365.63 IOPS     349.08 MiB/s
 Job: nvme0n1 (Core Mask 0x1)
         nvme0n1             :   89366.16 IOPS     349.09 MiB/s
 Job: nvme11n1 (Core Mask 0x1)
         nvme11n1            :   89366.64 IOPS     349.09 MiB/s
 =============================================================
 Total                       :  446828.94 IOPS    1745.43 MiB/s
```

NVME results:
* 1 nvme drive:
```
Running I/O for 120 seconds...
 Job: Nvme0n1 (Core Mask 0x1)
         Nvme0n1             : 1210769.98 IOPS    4729.57 MiB/s
 =============================================================
 Total                       : 1210769.98 IOPS    4729.57 MiB/s

```
* 5 nvme drives:
```
Running I/O for 120 seconds...
 Job: Nvme0n1 (Core Mask 0x1)
         Nvme0n1             :  262519.06 IOPS    1025.47 MiB/s
 Job: Nvme1n1 (Core Mask 0x1)
         Nvme1n1             :  262519.05 IOPS    1025.47 MiB/s
 Job: Nvme2n1 (Core Mask 0x1)
         Nvme2n1             :  262517.80 IOPS    1025.46 MiB/s
 Job: Nvme3n1 (Core Mask 0x1)
         Nvme3n1             :  262518.04 IOPS    1025.46 MiB/s
 Job: Nvme4n1 (Core Mask 0x1)
         Nvme4n1             :  262517.46 IOPS    1025.46 MiB/s
 =============================================================
 Total                       : 1312591.41 IOPS    5127.31 MiB/s

```

So the drop in performance is roughly ~60% in those particular scenarios. 

bdev configuration, results and the perf data from all the above examples: 
[xnvme.zip](https://github.com/spdk/spdk/files/9617413/xnvme.zip)
[nvme.zip](https://github.com/spdk/spdk/files/9617416/nvme.zip)

Here's a quick overview of the perf data for the xnvme (in both cases it looks mostly the same):
[xnvme.txt](https://github.com/spdk/spdk/files/9617739/xnvme.txt)

**Comment by benlwalker** [comment]
Can you measure the performance of the SPDK io_uring bdev against a physical NVMe device (with the kernel nvme driver loaded)? That result will provide a worst case for the expected performance of xNVMe, much like the SPDK NVMe driver provides the best case. It may very well be that xNVMe is performing exactly as well as we'd expect.

**Comment by mikeBashStuff** [comment]
@benlwalker Will try to gather this data asap.

**Comment by mikeBashStuff** [comment]
Here are the results for the io_uring bdev:

* 1 nvme drive:
```
Running I/O for 120 seconds...
Job: nvme0n1 (Core Mask 0x1)
         nvme0n1             :  722911.59 IOPS    2823.87 MiB/s
=============================================================
Total                       :  722911.59 IOPS    2823.87 MiB/s
0
Received shutdown signal, test time was about 120.000000 seconds
=============================================================
Total                       :       0.00 IOPS       0.00 MiB/s

```
5 nvme drives:
```
Running I/O for 120 seconds...
Job: nvme0n1 (Core Mask 0x1)
         nvme0n1             :  137018.20 IOPS     535.23 MiB/s
Job: nvme1n1 (Core Mask 0x1)
         nvme1n1             :  136222.17 IOPS     532.12 MiB/s
Job: nvme2n1 (Core Mask 0x1)
         nvme2n1             :  136088.47 IOPS     531.60 MiB/s
Job: nvme3n1 (Core Mask 0x1)
         nvme3n1             :  135981.50 IOPS     531.18 MiB/s
Job: nvme4n1 (Core Mask 0x1)
         nvme4n1             :  135675.60 IOPS     529.98 MiB/s
=============================================================
Total                       :  680985.94 IOPS    2660.10 MiB/s

```

**Comment by benlwalker** [comment]
Great thanks. That's the real bug then - xNVMe should not be slower than those numbers. About 700k.

The SPDK io_uring bdev is going through the kernel blk layer. The xNVMe path should be bypassing that, giving it an advantage. But it seems that there's too much overhead in xNVMe itself.

**Comment by jimharris** [comment]
> Great thanks. That's the real bug then - xNVMe should not be slower than those numbers. About 700k.
> 
> The SPDK io_uring bdev is going through the kernel blk layer. The xNVMe path should be bypassing that, giving it an advantage. But it seems that there's too much overhead in xNVMe itself.

@mikeBashStuff, correct me if I'm wrong, but you tested the xNVMe "normal" io_uring code path?  For xNVMe, io-uring io mechanism means "normal" io_uring, and io-uring-cmd means NVMe command io-uring passthrough.  So at least for this test case, we should expect xNVMe to be close to 700K but not bypassing it.

**Comment by mikeBashStuff** [comment]
@jimharris io_uring was used as the io_mechanism for all these xnvme examples (it should be visible in the bdev configs included in the provided .zip files). The io_uring_cmd seems to depend on a specific op being present in the kernel which our benchmark systems currently don't support (we are using 5.15 kernels where that particular op was introduced in 5.18 as far as I recall). That said, I can boot one of the benchmark nodes into our per-patch images and try it that way if needed (these images have 5.18.13 on board so I think it should suffice).

**Comment by krish-reddy** [comment]
Sure, will look into this. The xNVMe BDEV with io_uring io_mechanism should be almost at par with the SPDK's io_uring BDEV, maybe slightly lesser due the minimal xNVMe stack overhead, but it should be not a difference of 700K.

To use the io_uring_cmd io_mechanism, the Kernel version should be >= 5.19.0-rc3+

**Comment by safl** [comment]
Quick comment here as well, I have a similar observation when comparing using ``fio``. What I see via ``fio`` is that ``bdev_uring`` and ``bdev_libaio`` consume (usr=81%-sys19%) CPU core and achieves higher IOPS than: ``bdev_xnvme`` (``io_mechanism=io_uring | io_uring_cmd | libaio``) and the built-in engines ``io_uring_cmd``, ``io_uring`` and ``libaio``.

``bdev_xnvme`` and the built-in engines are by default interrupt-driven and consume about (usr=11%,sys=25)%) CPU.

xNVMe does introduce some overhead, however, not as severe as the results here. It seems to me that the difference lies in whether or not CPU utilization is traded for I/O processing.

Previously, the default behavior of the xNVMe implementations were to spin when processing completions and consuming a cpu-core when doing so. However, this behavior did not align with the default use of ``io_uring`` and ``libaio``, so the behavior was changed to wait for interrupts.

How about we add a toggle in xNVMe, controlling whether  to spin or wait-on-interrupt on the ``io_uring``, ``io_uring_cmd``, and ``libaio`` backend implementations?
The ``bdev_xnvme`` can  then use this by default or also provide a toggle. Regardless, documentation needs improvement as noted [here](https://github.com/spdk/spdk/issues/2709). A couple of additional toggles would be useful for ``io_uring`` and ``io_uring_cmd`` "io_mechanisms" as well, e.g. enabling io_uring submission-queue-thread-polling in the kernel and enabling "hipri". Providing the means to trade even more CPU for higher IOPS and lower latency via the Kernel interfaces.

**Comment by jimharris** [comment]
> How about we add a toggle in xNVMe, controlling whether to spin or wait-on-interrupt on the `io_uring`, `io_uring_cmd`, and `libaio` backend implementations? The `bdev_xnvme` can then use this by default or also provide a toggle. Regardless, documentation needs improvement as noted [here](https://github.com/spdk/spdk/issues/2709). A couple of additional toggles would be useful for `io_uring` and `io_uring_cmd` "io_mechanisms" as well, e.g. enabling io_uring submission-queue-thread-polling in the kernel and enabling "hipri". Providing the means to trade even more CPU for higher IOPS and lower latency via the Kernel interfaces.

A toggle would be good.  Could we get a patch in ASAP to change the default in the bdev_xnvme module to spin?  I'd like to get that in for the 22.09 release next week, it will make bdev_xnvme match what we do in bdev_uring and bdev_aio.  And then for next release we can add the toggle to enable interrupt-driven.

**Comment by safl** [comment]
Have a patch ready now, will send it during Monday.

**Comment by safl** [comment]
# Numbers on ``conserve_cpu`` patchset

Data for the plots are produced using **fio** ``rw=randread`` at using M.2 NVMe SSD. The barplots show **IOPS**  using different **bdev** implementations: ``bdev_aio``, ``bdev_uring``, and ``bdev_xnvme`` via the fio ``spdk_bdev`` engine and labelled "reference" are fio built-in I/O engines utilizing the same system-interface/API/io_mechanism, and labelled **xnvme** without **bdev** are using xNVMe fio engine, accessing xNVMe directly.

| | conserve_cpu: true | conserve_cpu: false |
| - | ------------- | ------------- |
| libaio | ![libaio_barplot](https://user-images.githubusercontent.com/608657/192353569-a9300bdf-3999-4171-90c5-7c2ef282056e.png)  | ![libaio_barplot](https://user-images.githubusercontent.com/608657/192353902-fa8dbb4c-4785-4915-8630-1cce0fe5bff8.png)  |
| libaio |  ![libaio_lineplot](https://user-images.githubusercontent.com/608657/192357696-5d4d7377-6c43-472f-af0a-a860727fe4b8.png) | ![libaio_lineplot](https://user-images.githubusercontent.com/608657/192357773-b42efc5c-6dc5-4ab2-a039-d661e3287613.png) |
| io_uring | ![io_uring_barplot](https://user-images.githubusercontent.com/608657/192354087-f8d6ee64-6e8d-421a-baf1-531c36755168.png)  |  ![io_uring_barplot](https://user-images.githubusercontent.com/608657/192354151-0866c36d-8d86-47d4-aee9-3532c05d9f58.png) |
| io_uring | ![io_uring_lineplot](https://user-images.githubusercontent.com/608657/192358013-ebbe670e-3d14-4b9e-921c-f6a25389f8ba.png) | ![io_uring_lineplot](https://user-images.githubusercontent.com/608657/192358055-72efc8f7-7ed3-48f4-a209-2456c5516e97.png) |
| io_uring_cmd |  ![io_uring_cmd_barplot](https://user-images.githubusercontent.com/608657/192354504-ebe47977-ba0d-46fb-98e2-ebb351f53734.png)  | ![io_uring_cmd_barplot](https://user-images.githubusercontent.com/608657/192354554-c48d1404-c013-47e1-8918-62e8a4b4bb12.png) |
| io_uring_cmd | ![io_uring_cmd_lineplot](https://user-images.githubusercontent.com/608657/192358412-048525e2-d0c4-4001-9b59-704acadaeabb.png)  |  ![io_uring_cmd_lineplot](https://user-images.githubusercontent.com/608657/192358448-3ee586b6-9924-4e4f-adb2-42600c95779a.png) |

## Observations

- ``bdev_xnvme`` with ``conserve_cpu=false`` increases **IOPS** on all io_mechanisms
- ``bdev_xnvme`` with ``io_mechanism=io_uring_cmd`` and ``conserve_cpu=false`` achieves the highest IOPS

**Comment by safl** [comment]
# Patchset obstacles

These are a couple of notes on obstacles for the two patchsets, starting with the smallest one.

## The ``minimal_poll`` patchset

Not many obstacles here, it enables polling for ``io_mechanism=io_uring_cmd``, however, it uses ``SQPOLL`` to do so and thus consuming a core exclusively. Unfortunately then ``IOPOLL`` is currently not supported for ``io_uring_cmd`` on Linux 5.19. It will come with 6.1. This "obstacle" also applies to the ``conserve_cpu`` patchset.

## The ``conserve_cpu`` patchset

* Enabling polling for ``io_mechanism=libaio`` requires updating the git-submodule to xNVMe v0.5.0, this in turn requires the availability of Liburing 2.2 on the system as xNVMe v0.5.0 no longer bundles the library.
* Enabling polling for ``io_mechanism=io_uring`` is implemented using ``IOPOLL`` in xNVMe. Then the ``bdev_xnvme`` toggles this via ``opts.poll_io``, then Jenkins CI fails on the zram device, as it seems that zram devices do not support ``IORING_SETUP_IOPOLL``, e.g. running ``fio`` on a zram device with ``--hipri`` also fails. A null-block instance might work better here?

**Comment by mikeBashStuff** [comment]
@safl Your feedback is greatly appreciated! :)

I can prepare patches targeting the functional tests (i.e. switching to `null_blk`). Bumping liburing to 2.2 on the CI will probably take a bit more time since we would need to test it across all the CI distros and then update all needed images. That said, I will try to plan this work this week (we have been already planning to update the images to address other changes so I believe we can simply add liburing's version bump as the cherry on the top of that list).
