### ISSUE TITLE
Update documentation on xNVME

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2709]
Existing documentation doesn't provide enough information regarding the usage and potential dependencies, especially in terms of supported io_mechanisms.

For instance, from the SPDK perspective it seems like the main point of interest would be the `io_uring_cmd` mechanism, however, it requires linux kernel which provides `IORING_OP_URING_CMD` op (so top shelf, 5.18 and onward) - making this information clear would be definitely beneficial to the user in terms of what system setups are needed for this functionality to work.

**Comment by krish-reddy** [comment]
Sure, will work on this !

**Comment by jimharris** [comment]
Hi @krish-reddy - is there any update on this documentation?

**Comment by krish-reddy** [comment]
No @jimharris . Nothing on this yet. Will take it up on priority. Sorry for the delay !

**Comment by karlatec** [comment]
@krish-reddy Any update on updating the docs?

**Comment by karlowich** [comment]
@karlatec I have updated the docs:
https://review.spdk.io/gerrit/c/spdk/spdk/+/24090

**Comment by karlatec** [comment]
@karlowich @safl many thanks!

**Comment by tomzawadzki** [comment]
Closing the issue since the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/24090 was merged.
