### ISSUE TITLE
[nvme_multi_process] fio stuck at second time in multi-process mode

### ISSUE THREAD

**Issue by PaulJen1127** [spdk/spdk#2711]
# Bug report
fio stuck at second time in multi-process mode

## Current Behavior

fio stuck this while loop because the initialized is false

```
### nvme.c

g_spdk_nvme_driver = spdk_memzone_lookup(SPDK_NVME_DRIVER_NAME);

fprintf(stdout, "g_spdk_nvme_driver: '%p'\n", g_spdk_nvme_driver);
fprintf(stdout, "g_spdk_nvme_driver default_extended_host_id: '%p'\n", &g_spdk_nvme_driver->default_extended_host_id);
fprintf(stdout, "SPDK_NVME_DRIVER_NAME: '%s'\n", SPDK_NVME_DRIVER_NAME);

/* The unique named memzone already reserved by the primary process. */
if (g_spdk_nvme_driver != NULL) {
	int ms_waited = 0;

	/* Wait the nvme driver to get initialized. */
	while ((g_spdk_nvme_driver->initialized == false) &&
			     (ms_waited < g_nvme_driver_timeout_ms)) {
		ms_waited++;
		nvme_delay(1000); /* delay 1ms */
	fprintf(stdout, "g_spdk_nvme_driver->initialized: '%d'\n", g_spdk_nvme_driver->initialized);
	fprintf(stdout, "g_spdk_nvme_driver->hotplug_fd: '%d'\n", g_spdk_nvme_driver->hotplug_fd);
	}
	if (g_spdk_nvme_driver->initialized == false) {
		SPDK_ERRLOG("timeout waiting for primary process to init\n");
		pthread_mutex_unlock(&g_init_mutex);
		return -1;
	}
} 
```

We use spdk_memzone_lookup() to check some information to make sure if we access same memory zone.
And we can get the same results both test app and fio at first time

but at the second time, fio will show the different info => hotplug_fd: 0...
still can get hotplug_fd: 53 at test app 

The following message are shown while fio execute

**_First time fio execute_**
```
shm id 1
EAL: No legacy callbacks, legacy socket not created
spdk_process_is_primary 0
thread id 208553
g_spdk_nvme_driver: '0x2010803e9e80'
g_spdk_nvme_driver default_extended_host_id: '0x2010803e9eb9'
SPDK_NVME_DRIVER_NAME: 'spdk_nvme_driver'
g_spdk_nvme_driver->initialized: '1'
g_spdk_nvme_driver->hotplug_fd: '53'
```

**_Second time fio execute_**
```
shm id 1
EAL: No legacy callbacks, legacy socket not created
spdk_process_is_primary 0
thread id 213051
g_spdk_nvme_driver: '0x2010803e9e80'
g_spdk_nvme_driver default_extended_host_id: '0x2010803e9eb9'
SPDK_NVME_DRIVER_NAME: 'spdk_nvme_driver'
g_spdk_nvme_driver->initialized: '0'
g_spdk_nvme_driver->hotplug_fd: '0'
```

## Steps to Reproduce

1.Switch to spdk driver and init env with shm_id = 1 in test app
2.Test app run fio with shm_id = 1 (it works)
3.Call spdk_env_fini() after fio finish
4.Switch to nvme driver without closing test app (test app process still exist)
5.Repeat step 1.
6.Repeat Step2. and fio will stuck

## Context (Environment including OS version, SPDK version, etc.)
SPDK version 21.04

**Comment by jimharris** [comment]
Hi,

v21.04 is no longer supported.  Can you please retry with v22.01.1, v22.05 or latest master?

Please also include *exact* steps, including patches for any changes made locally.

Marking this as an enhancement request, since the fio plugin is not designed to support this today.  Adding the requested information makes it more likely someone will take a look at it in the future.

Thanks,

Jim

**Comment by jimharris** [comment]
Closing.  Please reopen if you are able to provide the requested info.
