### ISSUE TITLE
pkgdep.sh not support openEuler Linux

### ISSUE THREAD

**Issue by xin3liang** [spdk/spdk#2713]
# Bug report

## Expected Behavior

 `sudo ./scripts/pkgdep.sh --all ` should success.

## Current Behavior

```
[openeuler@oe2203-test spdk]$ sudo ./scripts/pkgdep.sh --all
Not supported distribution detected (openeuler), aborting
```

## Steps to Reproduce

1. [openeuler@oe2203-test spdk]$ sudo ./scripts/pkgdep.sh --all

## Context (Environment including OS version, SPDK version, etc.)

SPDK: master branch
```
[openeuler@oe2203-test spdk]$ lsb_release -a
LSB Version:    n/a
Distributor ID: openEuler
Description:    openEuler release 22.03 LTS
Release:        22.03
Codename:       n/a
[openeuler@oe2203-test spdk]$ uname -a
Linux oe2203-test.novalocal 5.10.0-60.56.0.84.nvmftcp.aarch64 #1 SMP Thu Sep 22 02:55:05 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by changpe1** [comment]
@xin3liang we don't have a openEuler Linux environment, so it's not in SPDK support list, you can improve scripts/pkgdep.sh with your environment and contribute your patches back to SPDK. I'm going to close it, no one in our team will fix it.

**Comment by jimharris** [comment]
> @xin3liang we don't have a openEuler Linux environment, so it's not in SPDK support list, you can improve scripts/pkgdep.sh with your environment and contribute your patches back to SPDK. I'm going to close it, no one in our team will fix it.

He did post a patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/14639. Should we reopen and then close later if/when this patch is merged?

**Comment by changpe1** [comment]
> > @xin3liang we don't have a openEuler Linux environment, so it's not in SPDK support list, you can improve scripts/pkgdep.sh with your environment and contribute your patches back to SPDK. I'm going to close it, no one in our team will fix it.
> 
> He did post a patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/14639. Should we reopen and then close later if/when this patch is merged?

Reopened.

**Comment by xin3liang** [comment]
Yeah, I've just sent the fixed patch and verified building and running fio test on openEuler. 
Thanks for reopening this issue. Please help to review that patch.
```
[openeuler@oe2203-test spdk]$ sudo ./scripts/perf/nvmf/run_nvmf.py -c ~/config-local.json
...
[initiator1] Starting FIO run for job: /home/openeuler/spdk/nvmf_perf/4k_1024_randread_m_100_2CPU
[initiator1] Using FIO: /home/openeuler/fio/fio
[initiator1] Run cmd: sudo /home/openeuler/fio/fio /home/openeuler/spdk/nvmf_perf/4k_1024_randread_m_100_2CPU.fio
Redirecting to /tmp/results/4k_randread_1024_collect-bmc-pm.bmc.pm.log
[initiator1] filename0: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring, iodepth=1024
filename1: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring, iodepth=1024
fio-3.32-38-gd146
Starting 2 threads
Jobs: 2 (f=2): [r(2)][100.0%][r=550MiB/s][r=141k IOPS][eta 00m:00s]
filename0: (groupid=0, jobs=2): err= 0: pid=32049: Fri Sep 23 01:48:12 2022
  read: IOPS=102k, BW=400MiB/s (420MB/s)(4006MiB/10010msec)
    slat (usec): min=2, max=12984, avg= 3.52, stdev=18.42
    clat (usec): min=2481, max=39424, avg=19997.65, stdev=8558.52
     lat (usec): min=2484, max=39428, avg=20001.17, stdev=8558.37
    clat percentiles (usec):
     | 50.000th=[22152], 90.000th=[31327], 99.000th=[35914], 99.500th=[36439],
     | 99.900th=[38011], 99.990th=[39060], 99.999th=[39584]
   bw (  KiB/s): min=265864, max=778260, per=99.91%, avg=409390.60, stdev=82587.08, samples=40
   iops        : min=66464, max=194565, avg=102347.65, stdev=20646.77, samples=40
  lat (msec)   : 4=0.04%, 10=18.12%, 20=30.71%, 50=51.32%
  cpu          : usr=16.74%, sys=20.99%, ctx=219577, majf=0, minf=0
  IO depths    : 1=0.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=1023374,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1024

Run status group 0 (all jobs):
   READ: bw=400MiB/s (420MB/s), 400MiB/s-400MiB/s (420MB/s-420MB/s), io=4006MiB (4200MB), run=10010-10010msec

Disk stats (read/write):
  nvme0n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme1n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
```

**Comment by wanghailiangx** [comment]
@xin3liang openEuler is very close to CentOS8/RHEL8, the modified logic in your patch is reasonable.

**Comment by xin3liang** [comment]
> @xin3liang openEuler is very close to CentOS8/RHEL8, the modified logic in your patch is reasonable.

Yes, like I said in the patch git log "OpenEuler Linux although is not compatible with RHEL, but it uses the same package manager DNF as RHEL and references the package naming of RHEL."
And we also handled it as a RHEL family OS in OpenStack project too. 
Thanks for reviewing the patch.
