### ISSUE TITLE
[vhost/ocf]ocf_bdev is attach to vhost as cache, and the low read hit leads to poor performance

### ISSUE THREAD

**Issue by dawin2015** [spdk/spdk#2714]
# Bug report
ocf_bdev is attach to vhost as cache, and the low read hit leads to poor performance

## Expected Behavior
First read  all missed and second read all hited.

## Current Behavior
First read  all missed and second read all missed.

## Possible Solution
It's suspected that reading is different every time.

## Steps to Reproduce

1.  create a malloc bdev as core bdev: `./scripts/rpc.py bdev_malloc_create -b Core 1024 512`
2. create a malloc bdev as cache bdev: `./scripts/rpc.py bdev_malloc_create -b Cache 1024 512`
3. create a ocf bdev: `./scripts/rpc.py bdev_ocf_create Ocf wi Cache Core --cache-line-size 4`
4. ocf bdev is attached to vhost: `/scripts/rpc.py vhost_create_blk_controller --cpumask 0x2 vhost.1 Ocf`
5. redefine file vm.xml, like below: 
```
...
  <memoryBacking>
    <hugepages>
      <page size='2048' unit='KiB'/>
    </hugepages>
    <source type='file'/>
    <access mode='shared'/>
    <allocation mode='immediate'/>
    <discard/>
  </memoryBacking>
...
    <disk type='vhostuser' device='disk' snapshot='no'>
      <driver name='qemu' type='raw'/>
      <source type='unix' path='/var/tmp/vhost.1'>
        <reconnect enabled='yes' timeout='10'/>
      </source>
      <target dev='vda' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </disk>
...
```
6. virsh define vm.xml
7. virsh start vm
8. fio started to write: `fio --name=rbd -group_reporting -direct=1 -iodepth=128 -thread -rw=randwrite -ioengine=libaio -norandommap -bs=4k -size=1G-numjobs=1 -filename=/dev/vda --output=vda_128.log &`
9. get ocf stat: `./scripts/rpc.py bdev_ocf_get_stats Ocf`
10. fio started to read: `fio --name=rbd -group_reporting -direct=1 -iodepth=128 -thread -rw=read -ioengine=libaio -norandommap -bs=4k -size=1G -numjobs=1 -filename=/dev/vda --output=vda_128.log &`
11. get ocf stat: `./scripts/rpc.py bdev_ocf_get_stats Ocf`. This time read missed.
12. read and get ocf stat again. This time was read missed also, but expect to read hited

## Context (Environment including OS version, SPDK version, etc.)
OS: RockyLinux 8.4
SPDK: 22.01
OCF: 21.6

**Comment by dawin2015** [comment]
![image](https://user-images.githubusercontent.com/12325204/191929868-4fb29656-16dd-467f-9cb3-a4a09f96a7d4.png)

**Comment by gaowayne** [comment]
@dawin2015  random write is not cache friendly workload, try random zipf1.2

**Comment by gaowayne** [comment]
@dawin2015 and to keep cacheline in cache wb is correct mode, https://open-cas.github.io/cache_configuration.html

**Comment by dawin2015** [comment]
Thanks @gaowayne. I use seqwrite but the performance of vhot/ocf/malloc still not good. But I still wonder why vhost connect with multi VMs like SPDK performance reports do, can have good performance.[SPDK 22.05 Vhost Performance Report](https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2205.pdf)

**Comment by changpe1** [comment]
> Thanks @gaowayne. I use seqwrite but the performance of vhot/ocf/malloc still not good. But I still wonder why vhost connect with multi VMs like SPDK performance reports do, can have good performance.[SPDK 22.05 Vhost Performance Report](https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2205.pdf)

Multiple VMs are more useful in practice, you can test OCF and vhost performance separately first, and your test case isn't reasonable to me. The device capacity is too small for performance evaluation.

**Comment by gaowayne** [comment]
> Thanks @gaowayne. I use seqwrite but the performance of vhot/ocf/malloc still not good. But I still wonder why vhost connect with multi VMs like SPDK performance reports do, can have good performance.[SPDK 22.05 Vhost Performance Report](https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2205.pdf)

as I know malloc bdev use memcpy if you do not have DSA enabled, this burn CPUs. to get best performance please try Intel OptaneSSD P5800 that best performance under SPDK. SPDK P5800 bdev can reach above 6.0 GB/s random 4K write with 0.5 CPU core

**Comment by dawin2015** [comment]
Thank you @changpe1 @gaowayne  for your reply, which is of great help.

**Comment by gaowayne** [comment]
> > Thanks @gaowayne. I use seqwrite but the performance of vhot/ocf/malloc still not good. But I still wonder why vhost connect with multi VMs like SPDK performance reports do, can have good performance.[SPDK 22.05 Vhost Performance Report](https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2205.pdf)
> 
> Multiple VMs are more useful in practice, you can test OCF and vhost performance separately first, and your test case isn't reasonable to me. The device capacity is too small for performance evaluation.

@changpe1  OCF has one policy seq cut off, too large seqwrite IO will not goes into cache, IO size is configurable, I guess maybe impacted by this. also best write IO best equals OCF cacheline to get best performance. :) we can talk internally if you like to tune vhost OCF test report together.

**Comment by dawin2015** [comment]
@gaowayne I have these questions below:
1. In the large seqread, will the IO **not** be promoted to cache?
2. In wa and wi cahce mode, will the cache be updated? If not, will these cache be tagged  as invalid?
Looking forward for your reply. Thanks.
