### ISSUE TITLE
[vhost_fuzz] Core dump when vhost autofuzz in spdk/test/fuzz/autofuzz_vhost.sh file, line 65

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2716]
# Bug report

There will raise core dump when autofuzz vhost

## Expected Behavior

No core

## Steps to Reproduce

1. execute `./test/fuzz/autofuzz.sh --module=vhost --transport=all` on SPDK master code
    Core dump as below:
 14:11:50      -- fuzz/autofuzz_vhost.sh@50 -- # pwd
 14:11:50       -- fuzz/autofuzz_vhost.sh@50 -- # /home/wenjun/spdk/test/fuzz/../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/wenjun/spdk/Vhost.1 -b -v
 14:11:51       -- fuzz/autofuzz_vhost.sh@53 -- # '[' all == scsi ']'
 14:11:51       -- fuzz/autofuzz_vhost.sh@53 -- # '[' all == all ']'
 14:11:51       -- fuzz/autofuzz_vhost.sh@54 -- # /home/wenjun/spdk/test/fuzz/../../scripts/rpc.py bdev_malloc_create -b Malloc1 64 512
Malloc1
 14:11:51       -- fuzz/autofuzz_vhost.sh@55 -- # /home/wenjun/spdk/test/fuzz/../../scripts/rpc.py vhost_create_scsi_controller naa.VhostScsi0.1
 14:11:51       -- fuzz/autofuzz_vhost.sh@56 -- # /home/wenjun/spdk/test/fuzz/../../scripts/rpc.py vhost_scsi_controller_add_target naa.VhostScsi0.1 0 Malloc1
0
 14:11:51       -- fuzz/autofuzz_vhost.sh@58 -- # /home/wenjun/spdk/test/fuzz/../../scripts/rpc.py bdev_malloc_create -b Malloc2 64 512
Malloc2
 14:11:51       -- fuzz/autofuzz_vhost.sh@59 -- # /home/wenjun/spdk/test/fuzz/../../scripts/rpc.py vhost_create_scsi_controller naa.VhostScsi0.2
 14:11:51       -- fuzz/autofuzz_vhost.sh@60 -- # /home/wenjun/spdk/test/fuzz/../../scripts/rpc.py vhost_scsi_controller_add_target naa.VhostScsi0.2 0 Malloc2
0
  14:11:52      -- fuzz/autofuzz_vhost.sh@63 -- # pwd
 14:11:52       -- fuzz/autofuzz_vhost.sh@63 -- # /home/wenjun/spdk/test/fuzz/../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/wenjun/spdk/naa.VhostScsi0.1 -l -v
  14:11:52      -- fuzz/autofuzz_vhost.sh@65 -- # pwd
 14:11:52       -- fuzz/autofuzz_vhost.sh@65 -- # /home/wenjun/spdk/test/fuzz/../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/wenjun/spdk/naa.VhostScsi0.2 -v -m
Connection closed with partial response:

/home/wenjun/spdk/test/fuzz/autofuzz_vhost.sh: line 66: 194140 Aborted                 (core dumped) "${VHOST_FUZZ_APP[@]}" -t $TEST_TIMEOUT 2> "$output_dir/vhost_autofuzz_output1.txt"
  14:11:52      -- fuzz/autofuzz_vhost.sh@65 -- # trap - ERR

CI fail link: https://spdkci.intel.com/job/autofuzz_vhost_all/351/consoleFull 

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: 896a25fb16eae674150e9fe5c8a6f7a4520b527c

**Comment by wanqunintel** [comment]
@tomzawadzki , will you have a look at this issue? thanks.

**Comment by karlatec** [comment]
Quick git bisect points to this f869197b76ff6981e901b6d9a05789e1b993494a (https://review.spdk.io/gerrit/c/spdk/spdk/+/14249) as first faulty commit.

**Comment by wanqunintel** [comment]
@junwenx , did you try VHOST_FUZZ_APP+=(-r "$FUZZ_RPC_SOCK" -g --wait-for-rpc) command which is previous patch that passed the test?

**Comment by tomzawadzki** [comment]
Fix https://review.spdk.io/gerrit/c/spdk/spdk/+/14672

**Comment by junwenx** [comment]
> @junwenx , did you try VHOST_FUZZ_APP+=(-r "$FUZZ_RPC_SOCK" -g --wait-for-rpc) command which is previous patch that passed the test?

@wanqunintel I tried this, it still failed, error same as this ticket report.

**Comment by junwenx** [comment]
> Fix https://review.spdk.io/gerrit/c/spdk/spdk/+/14672

Verified this patch on local, fixed.

**Comment by wanghailiangx** [comment]
By the way, -g -s 256 --wait-for-rpc, -g --wait-for-rpc -s 256, --wait-for-rpc -g -s 256, -s 256 --wait-for-rpc -g are all right.

**Comment by wanghailiangx** [comment]
Patch merged. This issue can be closed.

**Comment by junwenx** [comment]
Thank you all, closed.
