### ISSUE TITLE
SPDK nvmf target setup for Ubuntu

### ISSUE THREAD

**Issue by sungjoonahn** [spdk/spdk#272]
I'm trying to setup SPDK nvmf target for Ubuntu 16.04 LTS. When I run nvmf_tgt after installations, I observe following errors from nvmf_tgt.

_...
copy_engine_ioat.c: 308:copy_engine_ioat_init: *NOTICE*: Ioat Copy Engine Offload Enabled
conf.c: 232:spdk_nvmf_parse_subsystem: *NOTICE*: Attaching block device Malloc0 to subsystem nqn.2016-06.io.spdk:cnode1
rdma.c:1136:spdk_nvmf_rdma_create: *NOTICE*: *** RDMA Transport Init ***
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
rdma.c:1144:spdk_nvmf_rdma_create: *ERROR*: rdma_create_event_channel() failed, No such device
transport.c:  76:spdk_nvmf_transport_create: *ERROR*: Unable to create new transport of type RDMA
nvmf.c: 255:spdk_nvmf_tgt_listen: *ERROR*: Transport initialization failed
conf.c: 284:spdk_nvmf_parse_subsystem: *ERROR*: Failed to listen on transport RDMA address 10.0.0.12:4420
nvmf_tgt.c: 277:nvmf_tgt_advance_state: *NOTICE*: Acceptor running
..._

This is what I did for the installations:
-Clean install of Ubuntu 16.04 LTS on an Intel Xeon server with Mellanox ConnectX-5 card
-Clean install of SPDK from github
  : git clone
  : run pkgdep.sh
  : sudo apt install libmlx5-1 (for user libraries to get ConnectX-5 work with SPDK)
  : compile SPDK with RDMA option tuned on
  : modprobe necessary modules (as specified in http://www.spdk.io/doc/nvmf.html )
  : run nvmf_tgt with one SPDK malloc target (conf file copied and edited from the installed SPDKs etc/spdk directory)

When I took the exact same steps for Ubuntu 17.10, everything worked fine. libibverbs1 and libmlx5-1 versions appear different between two Ubuntu distributions. Compiling those libs didn't seem trivial. Due to other software dependencies of my work, I would really like to get SPDK nvmf target work on Ubuntu 16.04 LTS. Would you let me know what I'm missing out here? Thx.

**Comment by Maciej-Szwed** [comment]
Hello Sungjoon
What kernel version do you use?
I’m not sure where the problem is, but my suggestion would be to try installing Mellanox OFED package with nvmf enabled. Here you can find details where to get it and how to install it:
https://community.mellanox.com/docs/DOC-2504
I have similar 16.04 configuration and the OFED package is the only difference between mine and yours setup. I’m using kernel 4.13.

Regards,
Maciej

**Comment by sungjoonahn** [comment]
Thanks Maciej. Installing Mellanox OFED package solved the problem.

**Comment by alokprasad** [comment]
most of this channel related issue is due to "rdma_ucm" module not loaded in system
