### ISSUE TITLE
Setup.sh overrides huge page allocation without checking the current value

### ISSUE THREAD

**Issue by xinyangge-db** [spdk/spdk#2724]
# Bug report

## Expected Behavior

When unbinding an NVMe drive from the kernel driver, `setup.sh` would reserve 2GB of huge pages by default.  In our setup, we have already reserved a set of huge pages before calling `setup.sh`, so `setup.sh` accidentally overrides our allocation.  We expect `setup.sh` to check the currently allocated huge pages before overriding it.  The relevant function is `configure_linux_hugepages` in `setup.sh`.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
This is a reasonable expectation.  @mikeBashStuff, can you take a look at this when you have a chance?  I think we change it to basically check currently allocated huge pages, and if it already meets what user specified (or what our default specified, if user doesn't specify), then we don't change anything.

We may also want to check for some new env var like SHRINK_HUGE.  If user specifies SHRINK_HUGE, then we will override the behavior described above, and shrink the number of huge pages based on the user's specified value.

I'm open to alternatives to any of the above.

**Comment by mikeBashStuff** [comment]
@jimharris Sure, will take a look.

**Comment by mikeBashStuff** [comment]
@jimharris Solution based on your suggestion: https://review.spdk.io/gerrit/c/spdk/spdk/+/14912

**Comment by jimharris** [comment]
Patch merged.
