### ISSUE TITLE
Bevperf: seed is initialized to 0 for all threads

### ISSUE THREAD

**Issue by plestrin** [spdk/spdk#2726]
The state of the rand_r PRNG is initialized to 0 for all threads. Threads request the exact same sequence of LBAs. Always.

**Comment by Comphix** [comment]
Raised following patch

https://review.spdk.io/gerrit/c/spdk/spdk/+/14911

Please have a verification. Thanks.

**Comment by Comphix** [comment]
Close this issue as patch merged.

**Comment by jimharris** [comment]
The patch was incorrect, I’ve posted a comment on Gerrit.

**Comment by Comphix** [comment]
A new and following patch raised: https://review.spdk.io/gerrit/c/spdk/spdk/+/15108

**Comment by jimharris** [comment]
> A new and following patch raised: https://review.spdk.io/gerrit/c/spdk/spdk/+/15108

Looks good @Comphix - thanks for the quick turnaround!
