### ISSUE TITLE
Setup.sh unable to bind to the NVMe disk, reports it active even when not mounted or part of the file system

### ISSUE THREAD

**Issue by meherpkolli** [spdk/spdk#2727]
# Bug report

root@qst01:~/spdk# ./scripts/setup.sh
0000:5e:00.0 (8086 0b60): Active devices: data@nvme0n1, so not binding PCI dev
0000:5f:00.0 (8086 0b60): Active devices: data@nvme1n1, so not binding PCI dev
0000:00:04.7 (8086 2021): ioatdma -> uio_pci_generic
0000:00:04.6 (8086 2021): ioatdma -> uio_pci_generic

## Expected Behavior
We should be able to bind to pci generic like below.
**This works on LTS release SPDK 22.01.1**
root@qst01:~/spdk# ./scripts/setup.sh
0000:80:04.1 (8086 2021): ioatdma -> uio_pci_generic
0000:80:04.0 (8086 2021): ioatdma -> uio_pci_generic
0000:5f:00.0 (8086 0b60): nvme -> uio_pci_generic
0000:5e:00.0 (8086 0b60): nvme -> uio_pci_generic

## Current Behavior
Broken on the current master

## Steps to Reproduce

1.  Same as above in bug report 
2.
3.
4.

**Comment by Comphix** [comment]
Is there any data or partition on these two SSDs?

It is enhanced with below commit to check and skip if devices has valid data.

```
https://github.com/spdk/spdk/commit/9af7c30e8f4d18959ce34f7815b99f4991ef8c30
```

**Comment by wanghailiangx** [comment]
It is recommended to format the disk and try again.

**Comment by KariukiJ** [comment]
@meherpkolli 
I observed the same issue in my environment. 
scripts/setup.sh
0000:d9:00.0 (8086 0a54): Active devices: data@nvme15n1, so not binding PCI dev

My disk was not mounted but there was a filesystem on the disk as detected by the following blockid command:
blkid /dev/nvme15n1
/dev/nvme15n1: UUID="6cc63f74-a8dc-4bc5-b73f-55cd4c53c0e7" TYPE="ext4"

I formatted the disk as follows:
nvme format /dev/nvme15n1

And confirmed that "blkid /dev/nvme15n1" returns nothing.
The setup.sh script runs and successfully binds the disk to the uio_pci_generic driver
0000:d9:00.0 (8086 0a54): nvme -> uio_pci_generic
