### ISSUE TITLE
Got wrong CMB BAR virtual address when use vfio driver. Because NVMe not ready.

### ISSUE THREAD

**Issue by joshualin-petaio** [spdk/spdk#2728]
# Bug report

Got wrong CMB BAR virtual address when use vfio driver. Because NVMe not ready.

## Expected Behavior

When example try to get CMB BAR virtual address. It can report address correctly.

## Current Behavior

When example try to get CMB BAR virtual address. It will report NULL.

## Possible Solution

Maybe can update CMB BAR virtual address after nvme ready.

## Steps to Reproduce

1. enable linux kernel and motherboard iommu feature.
2. check SPDK use vfio driver.
3. run identify or CMB example.
4. example will use host memory not CMB

## Context (Environment including OS version, SPDK version, etc.)

1. OS version : CentOS Stream release 8
2. SPDK git version : bcdedd1a
3. CPU : 12th Gen Intel(R) Core(TM) i7-12700
4. motherboard : ASUS Z690-plus

**Comment by Comphix** [comment]
From my understanding, CMB capability based on SSD. You may use SPDK's identify tool to check the SSD whether it supports CMB or not.

**Comment by joshualin-petaio** [comment]
Hi Comphix,

After NVMe SSD ready, it can get correct CMB capability. But CMB BAR virtual address is updated before NVMe ready only (only in nvme_pcie_ctrlr_map_cmb(), pctrlr->cmb.bar_va = addr;). So, although identify example can get correct CMB capability but get wrong CMB BAR virtual address.

Thanks, Joshua

**Comment by Comphix** [comment]
@Changpeng , maybe you could take a look? Thanks, Gang.

**Comment by changpe1** [comment]
@joshualin-petaio what's the device type of your NVMe SSD?

**Comment by joshualin-petaio** [comment]
The NVMe SSD is our company's device.

**Comment by changpe1** [comment]
> The NVMe SSD is our company's device.

This issue is likely with your SSD drive not SPDK, CMB doesn't require the SSD in ready state before using, because ADMIN queue pair can also in this region.

**Comment by joshualin-petaio** [comment]
Hi,

In function spdk_nvme_probe(), it try to probe PCI device without polling NVMe ready first. This step will update CMB BAR virtual address according NVMe register report CMB supported or not. But I saw the NVMe not ready and CMB cap. report the wrong value in this step. So, I can't get the correct CMB BAR virtual address. 
In the same function spdk_nvme_probe(), it will initialize controller after probe PCI device. In this step, it will polling NVMe ready. Then I can get the correct CMB cap.. But it don't update the CMB BAR virtual address.

**Comment by changpe1** [comment]
> Hi,
> 
> In function spdk_nvme_probe(), it try to probe PCI device without polling NVMe ready first. This step will update CMB BAR virtual address according NVMe register report CMB supported or not. But I saw the NVMe not ready and CMB cap. report the wrong value in this step. So, I can't get the correct CMB BAR virtual address. In the same function spdk_nvme_probe(), it will initialize controller after probe PCI device. In this step, it will polling NVMe ready. Then I can get the correct CMB cap.. But it don't update the CMB BAR virtual address.

if your SSD requires this extra step to wait for RDY bit, you can add a quirk in SPDK to map CMB later again, I don't see other vendors' SSD report this issue.

**Comment by joshualin-petaio** [comment]
Thank you for your reply. I'll try to modify SPDK first. 

Thanks, Joshua
