### ISSUE TITLE
[llvm_fuzz] There is an error when multiple process run nvmf llvm fuzz

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2729]
# Bug report

There is an error when multiple process run llvm fuzz, seems only support one fuzz at once.

## Steps to Reproduce

1. Config `CC=clang-12 CXX=clang++-12 ./configure --with-fuzzer=/usr/lib64/clang/12/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a`
2. Compile `make -j`
3. Run fuzzer 0 in one terminal window
`mkdir -p /tmp/llvm_fuzz0`
`./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F "trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420" -c test/nvmf/target/fuzz_json.conf -t 100 -D /tmp/llvm_fuzz0/ -Z 0`
4. Run fuzzer 1 in another terminal window at same time, with fuzzer 0 run together.
`mkdir -p /tmp/llvm_fuzz1`
`./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F "trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420" -c test/nvmf/target/fuzz_json.conf -t 100 -D /tmp/llvm_fuzz1/ -Z 1`

Error raised as below:
[2022-10-11 10:04:16.847081] tcp.c: 613:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2022-10-11 10:04:16.847115] transport.c: 237:spdk_nvmf_transport_create: *ERROR*: Unable to allocate poll group buffer pull: already exists
[2022-10-11 10:04:16.847122] transport.c: 239:spdk_nvmf_transport_create: *ERROR*: Probably running in multiprocess environment, which is unsupported by the nvmf library
[2022-10-11 10:04:16.847127] nvmf_rpc.c:1996:rpc_nvmf_create_transport: *ERROR*: Transport type 'TCP' create failed
[2022-10-11 10:04:16.851160] json_config.c: 194:rpc_client_poller: *ERROR*: error response:
{
  "code": -32603,
  "message": "Transport type 'TCP' create failed"
}

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: 896a25fb16eae674150e9fe5c8a6f7a4520b527c

**Comment by wanghailiangx** [comment]
Could you try to change a core? For example, Run fuzzer 1 llvm_nvme_fuzz -m **0x2**.

**Comment by junwenx** [comment]
> Could you try to change a core? For example, Run fuzzer 1 llvm_nvme_fuzz -m **0x2**.

Yes, already tried this, another error.

[2022-10-13 14:33:44.956786] reactor.c: 924:reactor_run: *NOTICE*: Reactor started on core 1
[2022-10-13 14:33:44.977553] nvmf_rpc.c: 151:nvmf_decode_poll_groups_mask: *ERROR*: Poll groups cpumask 0x1 is out of range
[2022-10-13 14:33:44.977579] nvmf_rpc.c: 179:rpc_nvmf_set_config: *ERROR*: spdk_json_decode_object() failed
[2022-10-13 14:33:44.981616] json_config.c: 194:rpc_client_poller: *ERROR*: error response:
{
  "code": -32602,
  "message": "Invalid parameters"
}
[2022-10-13 14:33:44.981683] app.c: 676:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero

**Comment by ksztyber** [comment]
@junwenx is there any reason you're trying to start the app in a multiprocess mode (sharing the same shm-id, `-i 0`)?

**Comment by junwenx** [comment]
@ksztyber Hi Konrad, we plan to run all fuzzer at same time, not one by one mode, because one by one is a weekly job, will cost very long time to run all fuzzer, so try to run all fuzzer in multiprocess mode.

**Comment by jimharris** [comment]
> @ksztyber Hi Konrad, we plan to run all fuzzer at same time, not one by one mode, because one by one is a weekly job, will cost very long time to run all fuzzer, so try to run all fuzzer in multiprocess mode.

I think you want to run multiple processes, each in single process mode.  When you specify "-i 0", you are saying that you want all of the processes to run together in multi-process mode.  Why would you need multi-process mode for this?

But the real problem here is here:

> [2022-10-13 14:33:44.977553] nvmf_rpc.c: 151:nvmf_decode_poll_groups_mask: ERROR: Poll groups cpumask 0x1 is out of range

Check fuzz_json.conf.  It is specifying poll_groups_mask to 0x1, but the core mask for your command line is 0x2.

Closing this issue, feel free to ask more questions here, but this is not an SPDK bug.

**Comment by junwenx** [comment]
@jimharris Thnaks Jim. I tried to modify something in test/nvmf/target/fuzz_json.conf. Add a new bdev Malloc1, uuid is different from Malloc0. Then add extra nvmf_subsystem_add_listener and nvmf_subsystem_add_ns module. Listen address's port is 4421, different from the original one. And then run 2 commands on 2 terminals. I used same shmid -i 0
`./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F "trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4421" -c test/nvmf/target/fuzz_json.conf -D /tmp/llvm_fuzz1/ -Z 1 -t 100`
`./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F "trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420" -t 100 -D /tmp/llvm_fuzz0/ -Z 0`

In the second command. there is no -c parameter, because the first is start and listen address. Looks can't do this for twice.
But there will core dump for the second command, info as below:
[2022-10-24 09:59:52.652344] nvme_qpair.c: 430:spdk_nvme_print_completion: *NOTICE*: INVALID OPCODE (00/01) qid:0 cid:5 cdw0:0 sqhd:0010 p:0 m:0 dnr:0
[2022-10-24 09:59:52.653692] nvme_qpair.c: 751:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
[2022-10-24 09:59:52.653706] nvme_ctrlr.c:1015:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode1] in failed state.
[2022-10-24 09:59:52.653712] nvme_ctrlr.c:3975:nvme_ctrlr_process_init: *ERROR*: [nqn.2016-06.io.spdk:cnode1] Ctrlr is in error state
[2022-10-24 09:59:52.653718] nvme.c: 702:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 127.0.0.1
[2022-10-24 09:59:52.653723] nvme_ctrlr.c:1004:nvme_ctrlr_fail: *NOTICE*: [nqn.2016-06.io.spdk:cnode1] already in failed state
[2022-10-24 09:59:52.653730] nvme_fabric.c: 214:nvme_fabric_prop_get_cmd_async: *ERROR*: Failed to send Property Get fabrics command
[2022-10-24 09:59:52.653735] nvme_ctrlr.c:1115:nvme_ctrlr_shutdown_async: *ERROR*: [nqn.2016-06.io.spdk:cnode1] Failed to read the CC register
spdk_nvme_connect() failed for transport address '127.0.0.1'
[2022-10-24 09:59:52.653744] app.c: 676:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==1123492==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x00000000026c (pc 0x000000547168 bp 0x7f1c8d0e0040 sp 0x7f1c8d0dff80 T1123495)
==1123492==The signal is caused by a READ memory access.
==1123492==Hint: address points to the zero page.
    #0 0x547168 in spdk_nvme_ctrlr_alloc_io_qpair /home/wenjun/spdk/lib/nvme/nvme_ctrlr.c:453:6
    #1 0x469b53 in TestOneInput /home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:789:15
    #2 0x6f7a39 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6f7a39)
    #3 0x6f85a0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6f85a0)
    #4 0x6f96b3 in fuzzer::Fuzzer::MutateAndTestOne() (/home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6f96b3)
    #5 0x6fb1a7 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6fb1a7)
    #6 0x6e020a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6e020a)
    #7 0x469a27 in start_fuzzer /home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:851:3
    #8 0x7f1c8efad2a4 in start_thread (/usr/lib64/libpthread.so.0+0x92a4)
    #9 0x7f1c8eeba322 in clone (/usr/lib64/libc.so.6+0x100322)

**Comment by junwenx** [comment]
> Do not use same shmid. You do not want these tests to run in multi process mode. Let each test process run independently.

Thanks. One use -i 0, another use -i 1. I tried 2 test now. Maybe know the origin of SEGV, if the first test end, if will disconnect all controller, but another still running, so the second test will core. Need wait the second test end,

**Comment by junwenx** [comment]
@jimharris There are some questions want to ask you for help.
1. If only use one fuzz_json.conf file, config lots of different Malloc and port and nqn information, but run in multi process mode. Only the first fuzz can use -c fuzz_json.conf, other llvm_nvme_fuzz command not permitted to use -c fuzz_json.conf, it will say xxxx port is being listened. But in this method, the first fuzzer can't end before other fuzzers, or other fuzzers will disconnect connection.
2. If one fuzz_json.conf config one target information, there need lots of fuzz_json.conf, such as fuzz_json_**fuzzer0**.conf, fuzz_json_**fuzzer1**.conf, etc.
3. Run in multi process mode, each fuzz command should run in background, the father-shell need wait all these sub-process finish, and kill them.
4. Log, if all fuzzer run together, each fuzzer's log will mixed, so maybe looks not clearly. And the log size is very big. Because each fuzzer will run 60000s.

There are some questions confused. Thanks

**Comment by jimharris** [comment]
> @jimharris There are some questions want to ask you for help.
> 
> 1. If only use one fuzz_json.conf file, config lots of different Malloc and port and nqn information, but run in multi process mode. Only the first fuzz can use -c fuzz_json.conf, other llvm_nvme_fuzz command not permitted to use -c fuzz_json.conf, it will say xxxx port is being listened. But in this method, the first fuzzer can't end before other fuzzers, or other fuzzers will disconnect connection.

Please let's not try to use multi-process mode.  The nvmf target is not designed for it.
  
> 2. If one fuzz_json.conf config one target information, there need lots of fuzz_json.conf, such as fuzz_json_**fuzzer0**.conf, fuzz_json_**fuzzer1**.conf, etc.

I think multiple fuzz_json.conf is fine.  Put a template into the repository, then have the test script generate the actual .conf files used by each fuzz application.

> 3. Run in multi process mode, each fuzz command should run in background, the father-shell need wait all these sub-process finish, and kill them.

Same as above, let's not use multi-process mode.

> 4. Log, if all fuzzer run together, each fuzzer's log will mixed, so maybe looks not clearly. And the log size is very big. Because each fuzzer will run 60000s.

You will probably need to redirect each fuzzer's output to a different log file.

**Comment by junwenx** [comment]
@jimharris Thanks Jim! I'll try them 👍

**Comment by junwenx** [comment]
Hi Jim @jimharris , Thanks a lot.
Can run fuzzers parallel now, I tried 3 or 4 fuzzer run at same time, it passed. but when lots of fuzzer run together, it fails.
log shows:
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-11-10 10:14:28.007587] app.c: 586:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-11-10 10:14:28.305160] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 0
[2022-11-10 10:14:28.476324] accel_sw.c: 466:sw_accel_module_init: *NOTICE*: Accel framework software module initialized.
[2022-11-10 10:14:28.996431] bdev.c:1627:spdk_bdev_initialize: *ERROR*: create rbuf large pool failed
[2022-11-10 10:14:28.996500] subsystem.c: 141:spdk_subsystem_init_next: *ERROR*: Init subsystem bdev failed
[2022-11-10 10:14:28.996600] app.c: 676:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero

I only modify the port info about test/fuzz/llvm/nvmf/fuzz_json.conf, and redirect to a new json conf file, each fuzzer uses one conf, and shm_id is different.  fuzzer 0 uses -i 0, fuzzer 1 uses fuzzer 1....

It looks like the resource is not enough for all fuzzers.
