### ISSUE TITLE
Invalid check for AMD iommu

### ISSUE THREAD

**Issue by mpiszczek** [spdk/spdk#2730]
# Bug report

The check for an AMD iommu in get_amd_iommu_width() in lib/env_dpdk/init.c may fail to properly detect an AMD iommu.

From AMD developers:
AMD EPYC can be configured into various Logical NUMA divisions for both 1P and 2P (sockets) for Naples, Rome and Milan.  This leads various combinations as 1, 2, 4 for a single socket. Hence hard coding the check for ` ivhd2` could fail even for a valid NPS configuration.

## Expected Behavior

The AMD iommu should be detected for all AMD Logical NUMA divisions for both 1P and 2P (sockets)

## Possible Solution

Use glob to locate the AMD iommu capability register with "/sys/class/iommu/ivhd*/amd-iommu/cap"

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

AMD EPYC cpus

**Comment by peluse** [comment]
Who are the devs in the comment "From AMD developers"? Are they able to propose a patch?

**Comment by mpiszczek** [comment]
From: Varghese, Vipin <Vipin.Varghese@amd.com>

> >  pci_device_iommu_support_va(const struct rte_pci_device *dev)  { @@
> > -501,6 +534,16 @@ pci_device_iommu_support_va(const struct
> rte_pci_device *dev)
> >         char filename[PATH_MAX];
> >         FILE *fp;
> >         uint64_t mgaw, vtd_cap_reg = 0;
> > +       struct stat s;
> > +
> > +       if (stat("/sys/class/iommu/ivhd2/amd-iommu", &s) == 0) {

AMD EPYC can be configured into various Logical NUMA divisions for both 1P and 2P (sockets) for Naples, Rome and Milan.  This leads various combinations as 1, 2, 4 for a single socket. Hence hard coding the check for ` ivhd2` could fail even for a valid NPS configuration.

I have pushed up another patch to the DPDK to address this issue. I will try to keep the DPDK and SPDK similar.

**Comment by mpiszczek** [comment]
Patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/14961

**Comment by jimharris** [comment]
Patch was merged.
