### ISSUE TITLE
Vhost fuzzing fails when changing core mask of the second VHOST_FUZZ_APP call 

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2732]
# Sighting report

test/vhost/fuzz/fuzz.sh fails when changing core mask (-m) of the second VHOST_FUZZ_APP call to something different than what was assigned to VHOST_APP.

I am currently developing a core lock file mechanism for SPDK applications [here](https://review.spdk.io/gerrit/c/spdk/spdk/+/14919) that disallows usage of the same core mask in multiple SPDK applications. I encountered problems with the above vhost fuzz test during CI tests in [vhost-initiator-vg-autotest](https://ci.spdk.io/results/autotest-per-patch/builds/87639/archive/vhost-initiator-vg-autotest/index.html). This only happens to the second call to VHOST_FUZZ_APP, when calling framework_start_init RPC. There is no clear indication why the test fails, only "Connection closed with partial response:".
I ran fuzz.sh multiple times:
- without my patch applied and no changed CPU masks - the test passes
- without my patch and with changed CPU masks - the test fails at the RPC call framework_start_init for the second VHOST_FUZZ_APP
- with my patch and no changed masks - the test fails as expected by the introduced code
- with my patch and changed masks - the test fails at the RPC framework_start_init of second VHOST_FUZZ_APP.

Here are the logs from failed run:
[output_failing.zip](https://github.com/spdk/spdk/files/9799534/output_failing.zip)

and from successful run for comparison:
[output_passing.zip](https://github.com/spdk/spdk/files/9799537/output_passing.zip)

In the failed logs I could find error log: `rte_vhost_user.c: 671:vhost_vring_desc_payload_to_iov: *ERROR*: gpa_to_vva(0x200009a63c08) == NULL`, which points out to an error in rte_vhost_va_from_guest_pa() (converting guest physical address to host virtual address) error as a possibility. After running vhost app in GDB I got the following backtrace:

```
#0  vhost_vring_desc_payload_to_iov (vsession=vsession@entry=0x7ffff000bb00, 
    iov=iov@entry=0x20001afda060, iov_index=iov_index@entry=0x7fffffffdbba, 
    payload=35184533978504, remaining=0) at rte_vhost_user.c:671
#1  0x000055555561c8f0 in vhost_vring_desc_to_iov (vsession=vsession@entry=0x7ffff000bb00, 
    iov=iov@entry=0x20001afda060, iov_index=iov_index@entry=0x7fffffffdbba, 
    desc=<optimized out>) at rte_vhost_user.c:760
#2  0x0000555555619366 in blk_iovs_split_queue_setup (bvsession=0x7ffff000bb00, 
    vq=<optimized out>, req_idx=0, iovs=iovs@entry=0x20001afda060, 
    iovs_cnt=iovs_cnt@entry=0x20001afda05c, length=length@entry=0x20001afda870)
    at vhost_blk.c:218
#3  0x000055555561a60e in process_blk_task (vq=<optimized out>, req_idx=<optimized out>)
    at vhost_blk.c:658
#4  0x000055555561ae0e in process_vq (vq=0x7ffff000bc80, bvsession=0x7ffff000bb00)
    at vhost_blk.c:872
#5  _vdev_vq_worker (vq=vq@entry=0x7ffff000bc80) at vhost_blk.c:910
#6  0x000055555561aeb3 in vdev_worker (arg=0x7ffff000bb00) at vhost_blk.c:936
#7  0x00005555556431b6 in thread_execute_poller (poller=0x555555d7e660, thread=0x555555d878a0)
    at thread.c:795
#8  thread_poll (thread=thread@entry=0x555555d878a0, max_msgs=max_msgs@entry=0, 
    now=now@entry=685637943608342) at thread.c:917
#9  0x0000555555644182 in spdk_thread_poll (thread=thread@entry=0x555555d878a0, 
    max_msgs=max_msgs@entry=0, now=685637943608342) at thread.c:968
#10 0x0000555555621bb1 in _reactor_run (reactor=0x555555cd0f40) at reactor.c:903
#11 reactor_run (arg=0x555555cd0f40) at reactor.c:941
#12 0x0000555555621fd3 in spdk_reactors_start () at reactor.c:1043
#13 0x000055555561f1c0 in spdk_app_start (opts_user=opts_user@entry=0x7fffffffe350, 
    start_fn=start_fn@entry=0x555555587a40 <vhost_started>, arg1=arg1@entry=0x0) at app.c:628
#14 0x00005555555831de in main (argc=<optimized out>, argv=<optimized out>) at vhost.c:77
```

I also noticed that sometimes the test passes with no problems, even with changed CPU masks. This can be seen in one of CI's builds [here](https://ci.spdk.io/results/autotest-per-patch/builds/87521/archive/vhost-initiator-vg-autotest/build.log).

## Expected Behavior

Vhost fuzzing application should not be dependent on CPU configuration of vhost app.

## Current Behavior

The second call to VHOST_FUZZ_APP inside test/vhost/fuzz/fuzz.sh fails if its CPU mask differs from VHOST_APP's CPU mask.

## Steps to Reproduce

1. First terminal: sudo ./build/bin/vhost -p 0 -m 0x1
2. Second terminal: sudo ./test/app/fuzz/vhost_fuzz/vhost_fuzz -r /var/tmp/spdk_fuzz.sock -g -s 256 -m 0x2 -t 10 --wait-for-rpc
3. Third terminal: sudo ./scripts/rpc.py bdev_malloc_create -b Malloc0 64 512
4. Third terminal: sudo ./scripts/rpc.py vhost_create_blk_controller Vhost.1 Malloc0
5. Third terminal: sudo PYTHONPATH=$HOME/spdk/python ./test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s $(pwd)/Vhost.1 -b -v
6. Third terminal: sudo ./scripts/rpc.py -s /var/tmp/spdk_fuzz.sock framework_start_init
*Wait until first fuzzing stops printing to the First terminal*
7. Second terminal: sudo ./test/app/fuzz/vhost_fuzz/vhost_fuzz -r /var/tmp/spdk_fuzz.sock -g -s 256 -m 0x4 -j "test/app/fuzz/vhost_fuzz/example.json" --wait-for-rpc
8. Third terminal: sudo PYTHONPATH=$HOME/spdk/python ./test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s $(pwd)/Vhost.1 -b -v
9. Third terminal: sudo ./scripts/rpc.py -s /var/tmp/spdk_fuzz.sock framework_start_init

The Third terminal at this point should display "Connection closed with partial response" and first terminal should show a line with the error mentioned above.

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 22.04 with 5.15 kernel on my machine, and Fedora 35 or Ubuntu 20.04 on CI machines
SPDK master with this change on top: dcf30711ef1a6e5692f310d94d1c9290eeae68f7 and latest master for CI machines

**Comment by KKaras169169** [comment]
Konrad Sztyber requested more debugging details, I will provide them soon.

**Comment by wanghailiangx** [comment]
Follow your steps to reproduce, when the last step is completed
First terminal:    **vhost_vring_desc_payload_to_iov: *ERROR* (you mentioned)**
```
VHOST_CONFIG: vring kick idx:2 file:236
VHOST_CONFIG: virtio is now ready for processing.
[2022-10-18 15:24:11.594967] rte_vhost_user.c: 671:vhost_vring_desc_payload_to_iov: *ERROR*: gpa_to_vva(0x200009a65408) == NULL 
VHOST_CONFIG: read message VHOST_USER_GET_VRING_BASE
VHOST_CONFIG: vring base idx:0 file:0
VHOST_CONFIG: read message VHOST_USER_GET_VRING_BASE
VHOST_CONFIG: vring base idx:1 file:0
VHOST_CONFIG: read message VHOST_USER_GET_VRING_BASE
VHOST_CONFIG: vring base idx:2 file:1
VHOST_CONFIG: read message VHOST_USER_SET_MEM_TABLE
VHOST_CONFIG: (0) memory regions not changed
VHOST_CONFIG: read message VHOST_USER_GET_FEATURES
VHOST_CONFIG: vhost peer closed
```
Second terminal: 
```
There is also a good chance that the target just failed before setting a status.
"vhost_blk_cmd": {
  "req_iov": {
    "iov_base": "200009a65408",
    "iov_len": 0
  },
  "data_iov": {
    "iov_base": "200009941e00",
    "iov_len": 1024
  },
  "resp_iov": {
    "iov_base": "200009a65440",
    "iov_len": 0
  },
  "type": 2,
  "ioprio": 4343,
  "sector": 24323523
}
Fuzzing completed.
device 0x23530f0 stats: Completed I/O: 1, Successful I/O: 1
```
Third terminal: 
```Connection closed with partial response:```

**Comment by KKaras169169** [comment]
Thanks @wanghailiangx, the Connection closed error should be in the Third terminal. I updated the Issue body above.

**Comment by changpe1** [comment]
@wanghailiangx since you can also reproduce this issue, can you have a try with https://review.spdk.io/gerrit/c/spdk/spdk/+/15038 patch serial to see this issue is still exist or not?

**Comment by wanghailiangx** [comment]
@changpe1 Downloaded the patch, this issue still exists.

**Comment by changpe1** [comment]
@KKaras169169 I can also reproduce this issue, in the second test case, you are using vhost_scsi test cases to connect to a vhost-blk socket file, the error response from vhost is expected.

**Comment by wanghailiangx** [comment]
@KKaras169169 Now that the error response from vhost is expected, could you readjust your test steps or close it?

**Comment by KKaras169169** [comment]
> @KKaras169169 I can also reproduce this issue, in the second test case, you are using vhost_scsi test cases to connect to a vhost-blk socket file, the error response from vhost is expected.

If the error is thrown by design then we can close this issue. I have implemented a workaround to disable the core locks, so I'll use that with a comment pointing to this issue.
