### ISSUE TITLE
bdevperf hangs during reads and is getting unblocked by keep alive timeout on target side

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#2738]
# Sighting report

**scenario**
bdevnvme used as nvmeof/tcp initiator, 1 core, 1 namespace, 128 qdepth, nvmf_tgt as a nvmof/tcp target, read traffic running for 1s

the bdev nvme timeout_us is getting changed experimentally from 0 (disabled) -> 100ms (debug)
and keep_alive_timeout_ms 0 (disabled) -> 10s

bdevnvme doesn't exit properly although test shall run for 1s, it is getting terminated after keep alive timeout detected on target side and disconnect happens

the odd thing which I cannot explain is that admin/io command timeouts are not observed and with that there is no clear reason for "hang"

## Expected Behavior

application shall exit with 0 after 1s

## Current Behavior

application exits with non 0 after 10s

## Possible Solution

TBD

## Steps to Reproduce

./bdevperf -q 128 -o 4096 -w randread -t 1 -m 0x1 -C -c $config_file -L nvme -L bdev_nvme

## Context (Environment including OS version, SPDK version, etc.)

v22.09

**Comment by jkalwas** [comment]
[bdevperf.config.txt](https://github.com/spdk/spdk/files/9814844/bdevperf.config.txt)

the log is too big, i need to figure out how to shrink it
do we need logs from both nvme + nvme_bdev here for now?

**Comment by shuhei-matsumoto** [comment]
@jkalwas 

If action_on_timeout is none, just a few logs are collected and no action is done for a timeout.
Will you set action_on_timeout to abort?

But, you did not observe the following warning log?
```
        SPDK_WARNLOG("Warning: Detected a timeout. ctrlr=%p qpair=%p cid=%u\n", ctrlr, qpair, cid);
```

Do you see some change if you set bdev_retry_count to 0?

**Comment by wanghailiangx** [comment]
Yes, there are lots of warning as below. There is no change if set bdev_retry_count from 3 to 0. 
```
[2022-10-19 13:58:42.409716] bdev_nvme.c:3115:timeout_cb: *WARNING*: Warning: Detected a timeout. ctrlr=0x1ba9c20 qpair=0x1ba2be0 cid=63
[2022-10-19 13:58:42.435716] bdev_nvme.c:3115:timeout_cb: *WARNING*: Warning: Detected a timeout. ctrlr=0x1ba9c20 qpair=0x1ba2be0 cid=76
[2022-10-19 13:58:42.461714] bdev_nvme.c:3115:timeout_cb: *WARNING*: Warning: Detected a timeout. ctrlr=0x1ba9c20 qpair=0x1ba2be0 cid=60
[2022-10-19 13:58:42.487715] bdev_nvme.c:3115:timeout_cb: *WARNING*: Warning: Detected a timeout. ctrlr=0x1ba9c20 qpair=0x1ba2be0 cid=65
[2022-10-19 13:58:42.513715] bdev_nvme.c:3115:timeout_cb: *WARNING*: Warning: Detected a timeout. ctrlr=0x1ba9c20 qpair=0x1ba2be0 cid=58
```
But with smaller -q and -o, then there is no problem. For example, 
`./test/bdev/bdevperf/bdevperf -q 16 -o 1024 -w randwrite -t 1 -m 0x1 -C -c bdevperf.config -L nvme -L bdev_nvme`

**Comment by jkalwas** [comment]
@wanghailiangx 

right, I tried to go with lower qdepth and issue either doesn't occur or is less frequent (as for transaction size I haven't tried)

you also used timeout_us 100000 and keep_alive_timeout_ms 10000?
so your observation is different - for some reason I'm not getting warnings (and abort does nothing because of that @shuhei-matsumoto )

I'm getting
> [2021-01-04 09:26:25.350558] ctrlr.c: 197:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2014-08.org.nvmexpress:uuid:9d70527a-eb53-450a-be16-9713ce5a0ea8 from subsystem nqn.2019-06.io.spdk:1 due to keep alive timeout.

on the target and just after that bdevperf is terminated

**Comment by wanghailiangx** [comment]
@jkalwas You could see my comments in https://github.com/spdk/spdk/issues/2737,
"timeout_us": 100000, ↓  ( keep_alive_timeout_ms 0,10000,1000000) ,  can work well. 
```
Running I/O for 1 seconds...
 Job: Null0n1 (Core Mask 0x1)
         Null0n1             :    4501.79 IOPS      17.59 MiB/s
 =============================================================
 Total                       :    4501.79 IOPS      17.59 MiB/s

```

**Comment by jkalwas** [comment]
so essentially you cannot reproduce the issue, right?

please make sure to use randread pattern, as I do observe difference (writes are fine)
with writes the only "issue" is the one you referenced above which is more like a concern for now

**Comment by wanghailiangx** [comment]
@jkalwas Yes, it is randread pattern, work well with "timeout_us": 100000.(randwrite also fine)
```
./test/bdev/bdevperf/bdevperf -q 128 -o 4096 -w randread -t 1 -m 0x1 -C -c bdevperf.config -L nvme -L bdev_nvme
......
Running I/O for 1 seconds...
 Job: Null0n1 (Core Mask 0x1)
         Null0n1             :    2912.75 IOPS      11.38 MiB/s
 =============================================================
 Total                       :    2912.75 IOPS      11.38 MiB/s

```

**Comment by changpe1** [comment]
> @jkalwas Yes, it is randread pattern, work well with "timeout_us": 100000.(randwrite also fine)
> 
> ```
> ./test/bdev/bdevperf/bdevperf -q 128 -o 4096 -w randread -t 1 -m 0x1 -C -c bdevperf.config -L nvme -L bdev_nvme
> ......
> Running I/O for 1 seconds...
>  Job: Null0n1 (Core Mask 0x1)
>          Null0n1             :    2912.75 IOPS      11.38 MiB/s
>  =============================================================
>  Total                       :    2912.75 IOPS      11.38 MiB/s
> ```

@jkalwas what are your configurations for your test environment in initiator and target?

**Comment by jkalwas** [comment]
with @Maciej-Szulik patch merged
https://review.spdk.io/gerrit/c/spdk/spdk/+/15136 
issue is no longer reproducible

I think the key questions are
- what was the actual rootcause (slow initiator & fast target) 
- how to reproduce that in SPDK testing environment
- is patch from Maciej ultimate solution or there is some refactor required (@benlwalker working on that?)

**Comment by ksztyber** [comment]
[Bug scrub] Since this is no longer happening, I think we can close this. Feel free to reopen if the issue reappears.
