### ISSUE TITLE
nvme discover failed,due to identify controller failed (7)

### ISSUE THREAD

**Issue by xiawei0411** [spdk/spdk#2739]
# Sighting report

we build spdk(22.05) on aarch64 platfrom ,then using ram to create a /dev/ram0 block device 。 use nvmf_tgt （by tcp） to mount block device to initiator which is x86_64 platform。

## Expected Behavior

initiator discover successful.

## Current Behavior

failde to discover。
initiator dmesg  as below:
nvme nvme0:  queue 0: timeout request 0x1b type 4
nvme nvme0:  identify controller failed (7)

## Steps to Reproduce
target:
get into top level of spdk source code
1.   ./build/bin/nvmf_tgt &
2.   ./scripts/rpc.py  nvmf_create_tranfsport -t TCP -u 16384 -m 8 -c 8192 -n 2048
3.   ./scripts/rpc.py  bdev_aio_create /dev/ram0 aio0
4.   ./scripts/rpc.py  nvmf_create_subsystem -a -s SPDK00000000000000 -d SPDK_Controller nqn.2022-10.org.nvme:lun0
5.   ./scripts/rpc.py  nvmf_subsystem_add_ns  nqn.2022-10.org.nvme:lun0 aio0
6.   ./scripts/rpc.py  nvmf_subsystem_add_listener -t TCP -a 192.169.1.10 -f ipv4 -s 4420 nqn.2022-10.org.nvme:lun0

initiator:
1.  nvme discover -t tcp -a 192.169.1.10 -s 4420

## Context (Environment including OS version, SPDK version, etc.)

v22.05

**Comment by Comphix** [comment]
Below logs are from initiator side?

Any more logs from SPDK NVMe-oF target? And the initiator used is kernel initiator? You may also have a try with SPDK initiator like by using the SPDK identify tool.

```
failde to discover。
initiator dmesg as below:
nvme nvme0: queue 0: timeout request 0x1b type 4
nvme nvme0: identify controller failed (7)
```

**Comment by xiawei0411** [comment]
> Below logs are from initiator side?
> 
> Any more logs from SPDK NVMe-oF target? And the initiator used is kernel initiator? You may also have a try with SPDK initiator like by using the SPDK identify tool.
> 
> ```
> failde to discover。
> initiator dmesg as below:
> nvme nvme0: queue 0: timeout request 0x1b type 4
> nvme nvme0: identify controller failed (7)
> ```

Yes,initiator used is kernel initiator. the logs form target  is ok . And we use wireshark to grab message for both target and initiator ,find initiator has get message, i guess initator may has something wrong. BTW, i'm freshmen in spdk ,how can i use the SPDK identify tool ?

**Comment by Comphix** [comment]
For SPDK identify tool, you may refer below shell file.
```
test/nvmf/host/identify.sh
```

**Comment by xiawei0411** [comment]
> For SPDK identify tool, you may refer below shell file.
> 
> ```
> test/nvmf/host/identify.sh
> ```

thanks a lot. i'll have a try.

**Comment by xiawei0411** [comment]
> For SPDK identify tool, you may refer below shell file.
> 
> ```
> test/nvmf/host/identify.sh
> ```
It dosent work. 
And which linux kernel  version do you suggest for fitting this spdk(v22.05)?  we are now useing kernel at 5.0.20 . i'am not sure  is kernel version cause this error

**Comment by Comphix** [comment]
Kernel shall be ok as this is by TCP.

**Comment by Comphix** [comment]
On the other hand, have you also tried the "nvme connect" command?

**Comment by xiawei0411** [comment]
> On the other hand, have you also tried the "nvme connect" command?

Due to nvme discover timeout.I think next "nvme connect" will make no sense ,so i did not try "nvme connect" command.But as you suggest, i‘ll also have a try

**Comment by wanghailiangx** [comment]
Unfortunately, I did not reproduce, the steps I listed below are for reference only.
```
# mkdir /tmp/ramdisk0
# mknod -m 660 /dev/ram0 b 1 0
# chown root:disk /dev/ram0
# ls /dev/ram*
/dev/ram0
# mount -t ramfs -o size=4M,maxsize=4M /dev/ram0 /tmp/ramdisk0
# mkfs /dev/ram0 4M
# mount /dev/ram0 /tmp/ramdisk0

# ./scripts/rpc.py bdev_aio_create /dev/ram0 aio0
aio0
# ./scripts/rpc.py nvmf_create_subsystem -a -s SPDK00000000000000 -d SPDK_Controller nqn.2022-10.org.nvme:lun0
# ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2022-10.org.nvme:lun0 aio0
# ./scripts/rpc.py nvmf_subsystem_add_listener -t TCP -a 192.168.4.8 -f ipv4 -s 4420 nqn.2022-10.org.nvme:lun0
# modprobe nvme-fabrics
# nvme discover -t tcp -a 192.168.4.8 -s 4420
Discovery Log Number of Records 1, Generation counter 1
=====Discovery Log Entry 0======
trtype:  unrecognized
adrfam:  ipv4
subtype: nvme subsystem
treq:    not required
portid:  0
trsvcid: 4420
subnqn:  nqn.2022-10.org.nvme:lun0
traddr:  192.168.4.8
```

**Comment by changpe1** [comment]
> > For SPDK identify tool, you may refer below shell file.
> > ```
> > test/nvmf/host/identify.sh
> > ```
> 
> It dosent work. And which linux kernel version do you suggest for fitting this spdk(v22.05)? we are now useing kernel at 5.0.20 . i'am not sure is kernel version cause this error

You can use the following SPDK initiator tool to have a try, I guess it may be related with your kernel version.

build/examples/identify -r "\
        trtype:tcp \
        adrfam:IPv4 \
        traddr:192.169.1.10 \
        trsvcid:4420 \
        subnqn:nqn.2014-08.org.nvmexpress.discovery" -L all

**Comment by changpe1** [comment]
closing this issue now as we don't get any responses from submitter for 2 weeks.
