### ISSUE TITLE
Fedora36: syntax error in setup.sh due to changes in extglob in bash 5.2.2

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2740]
# Sighting report

Running setup.sh on Fedora 36 with Bash 5.2.2 will fail with syntax error:

`./scripts/setup.sh: line 414: syntax error near unexpected token `('`

due to changes in extglob.

## Steps to Reproduce

1. run setup.sh (./scripts/setup.sh)

## Context (Environment including OS version, SPDK version, etc.)

Linux fedora 5.17.5-300.fc36.x86_64

**Comment by mikeBashStuff** [comment]
@KKaras169169 Would you kindly confirm if the patch works on your end as well? :)

**Comment by KKaras169169** [comment]
I have confirmed that above fix indeed works for my Fedora 36 instance

**Comment by mikeBashStuff** [comment]
Submitted patches were merged, issue can be closed.
