### ISSUE TITLE
Setting reactor cpumask when running rocksdb.sh

### ISSUE THREAD

**Issue by jsrolon** [spdk/spdk#2746]
I asked about this on the SPDK Slack last week but I didn't get a response. I'm using `test/blobfs/rocksdb/rocksdb.sh` to benchmark various I/O configurations on my system, following the instructions here: https://spdk.io/doc/blobfs.html

When I run `spdk_top` while `rocksdb.sh` is running, I can see that there's only 1 core being used. I want to use 4 cores. I've done this in the past by passing `--cpumask` to an SPDK application, but I can't find anywhere to do this in the `rocksdb.sh` script.

From what I can tell, the compiled `db_bench` is spinning up the SPDK application I'd like to set the cpumask on. Is there any way to do this?

**Comment by wanghailiangx** [comment]
I also didn't find the parameter `-- cpumask` in `db_bench -help`, but it is effective to set 4 cores as follows
`taskset 0xF $DB_BENCH`

**Comment by wanghailiangx** [comment]
Let me add, if you want 4 cores, you may set 
```
taskset 0xF $DB_BENCH......
cat << EOL >> insert_flags.txt
......
--threads=4
```
if you want 16 cores, you may set 
```
taskset 0xFFFF $DB_BENCH......
cat << EOL >> insert_flags.txt
......
--threads=16
```

**Comment by jimharris** [comment]
> Let me add, if you want 4 cores, you may set
> 
> ```
> taskset 0xF $DB_BENCH......
> cat << EOL >> insert_flags.txt
> ......
> --threads=4
> ```
> 
> if you want 16 cores, you may set
> 
> ```
> taskset 0xFFFF $DB_BENCH......
> cat << EOL >> insert_flags.txt
> ......
> --threads=16
> ```

taskset only specifies the set of cores that the application is allowed to run, it does not change the number of cores or threads that the application actually uses.

For the RocksDB blobfs plugin, it purposely only uses one reactor core.  There is no way currently to make it use more than one.  Most of the RocksDB work is done in the foreground RocksDB threads themselves, including much of the blobfs processing.  Only when blobfs requires a block I/O operation does it send a request to the reactor core for processing.  The benchmarking work that was done indicated that one reactor core was more than enough to satisfy the block I/O requests generated by the RocksDB threads - a lot of the block I/O are very large requests, i.e. flushing a large buffered write to disk, or large reads/writes as part of compaction.

**Comment by wanghailiangx** [comment]
@jsrolon Jim's explanation is very comprehensive, now could you close this issue?
