### ISSUE TITLE
Suggested improvements for trace RPCs

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2747]
We have some RPCs currently to manage SPDK tracepoints at runtime - for example, trace_enable_tpoint_group and trace_set_tpoint_mask.

But I think some additional ones would be useful.  It would be useful to be able to get the following information via RPC:

* name of shared memory file - this is emitted from the console if any trace groups are enabled from the command line, but there's no way to get it if enabled via RPC
* list of the available trace point groups - this is available from the application help text, but there's no way to get it via RPC, bonus points if it also shows a mask of the available trace points for each group

I think this can all be done via a single RPC - maybe something like trace_get_info.

**Comment by Comphix** [comment]
Hi Jim, will you work on this enhancement or other member could take on this? Thanks, Gang.

**Comment by jimharris** [comment]
> Hi Jim, will you work on this enhancement or other member could take on this? Thanks, Gang.

I would be happy if someone else picked this up!

**Comment by Comphix** [comment]
Got it. Thanks, Jim.

**Comment by Comphix** [comment]
Xinrui, please take a look and also let Jim know if there is any question. Thanks, Gang.

**Comment by dong-liuliu** [comment]
@Xinrui-Mao already looked into this issue, and found existing RPC command "trace_get_tpoint_group_mask" could list of the available trace point groups. But the "mask" in each group is its “tpoint_group_mask”, not “tpoint_mask”. 
(These two names are somehow a bit confusing when taking a glance.)

**Comment by Xinrui-Mao** [comment]
Hi Jim @jimharris , just as Xiaodong said, the existing RPC command "trace_get_tpoint_group_mask" could list the available trace point groups, and the RPC command "trace_get_tpoint_group_mask" shows:
`{
  "tpoint_group_mask": "0x0",
  "iscsi_conn": {
    "enabled": false,
    "mask": "0x2"
  },
  "scsi": {
    "enabled": false,
    "mask": "0x4"
  },
  "bdev": {
    "enabled": false,
    "mask": "0x8"
  },
  "nvmf_tcp": {
    "enabled": false,
    "mask": "0x20"
  },
  "blobfs": {
    "enabled": false,
    "mask": "0x80"
  },
  "thread": {
    "enabled": false,
    "mask": "0x400"
  },
  "nvme_pcie": {
    "enabled": false,
    "mask": "0x800"
  },
  "nvme_tcp": {
    "enabled": false,
    "mask": "0x2000"
  },
  "bdev_nvme": {
    "enabled": false,
    "mask": "0x4000"
  }
}`
But “name of shared memory file” and “shows a mask of the available trace points for each group” are still missed, So I want to make sure that whether add a new RPC "trace_get_info", or do some modification and enhancement into RPC "trace_get_tpoint_group_mask"?

**Comment by jimharris** [comment]
Hi @Xinrui-Mao,

Thanks for looking into this further.  I think a new trace_get_info RPC would still be better.  The existing RPC was useful when trace point groups could only be enabled by bit mask.  Now we do everything by name, which makes it much easier on the user.   I think it is also better to put the shared memory filename into a new RPC, it doesn't really fit into that existing RPC.

-Jim
