### ISSUE TITLE
[default_setup] verify_nr_hugepages failed

### ISSUE THREAD

**Issue by richael02** [spdk/spdk#2749]
# CI Intermittent Failure

during default_setup test, failed at " (($(< "$default_huge_nr") == nr_hugepages + surp + resv)) "

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/88324/archive/nvmf-phy-autotest/build.log

## Execution failed at

 12:50:21	-- setup/hugepages.sh@98 -- # resv=0
00:04:06.725   12:50:21	-- setup/hugepages.sh@100 -- # echo nr_hugepages=1024
00:04:06.725  nr_hugepages=1024
00:04:06.725   12:50:21	-- setup/hugepages.sh@101 -- # echo resv_hugepages=0
00:04:06.725  resv_hugepages=0
00:04:06.725   12:50:21	-- setup/hugepages.sh@102 -- # echo surplus_hugepages=2527
00:04:06.725  surplus_hugepages=2527
00:04:06.725   12:50:21	-- setup/hugepages.sh@103 -- # echo anon_hugepages=12288
00:04:06.725  anon_hugepages=12288
00:04:06.725   12:50:21	-- setup/hugepages.sh@105 -- # (( 2527 == nr_hugepages + surp + resv ))
00:04:06.725    12:50:21	-- setup/hugepages.sh@105 -- # trap - ERR
00:04:06.725    12:50:21	-- setup/hugepages.sh@105 -- # print_backtrace
00:04:06.725    12:50:21	-- common/autotest_common.sh@1083 -- # [[ ehxBET =~ e ]]
00:04:06.725    12:50:21	-- common/autotest_common.sh@1085 -- # args=('default_setup' 'default_setup')
00:04:06.725    12:50:21	-- common/autotest_common.sh@1085 -- # local args
00:04:06.725    12:50:21	-- common/autotest_common.sh@1087 -- # xtrace_disable
00:04:06.725    12:50:21	-- common/autotest_common.sh@16 -- # '[' no '!=' yes ']'
00:04:06.725    12:50:21	-- common/autotest_common.sh@17 -- # PREV_BASH_OPTS=ehxBET
00:04:06.725    12:50:21	-- common/autotest_common.sh@18 -- # [[ ehxBET == *\x* ]]
00:04:06.725    12:50:21	-- common/autotest_common.sh@19 -- # XTRACE_DISABLED=yes
00:04:06.725    12:50:21	-- common/autotest_common.sh@21 -- # set +x
00:04:06.725  ========== Backtrace start: ==========
00:04:06.725  
00:04:06.725  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/setup/hugepages.sh:105 -> verify_nr_hugepages([])
00:04:06.725       ...
00:04:06.725     100 		echo "nr_hugepages=$nr_hugepages"
00:04:06.725     101 		echo "resv_hugepages=$resv"
00:04:06.725     102 		echo "surplus_hugepages=$surp"
00:04:06.725     103 		echo "anon_hugepages=${anon:-disabled}"
00:04:06.725     104 	
00:04:06.725  => 105 		(($(< "$default_huge_nr") == nr_hugepages + surp + resv))
00:04:06.725     106 		# This knob doesn't account for the surp, resv hugepages
00:04:06.725     107 		(($(< "$global_huge_nr") == nr_hugepages))
00:04:06.725     108 		(($(get_meminfo HugePages_Total) == nr_hugepages + surp + resv))
00:04:06.725     109 	
00:04:06.725     110 		get_nodes
00:04:06.725       ...
00:04:06.725  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/setup/hugepages.sh:136 -> default_setup([])
00:04:06.725       ...
00:04:06.725     131 	# Test cases
00:04:06.725     132 	default_setup() {
00:04:06.725     133 		# Default HUGEMEM (2G) alloc on node0
00:04:06.725     134 		get_test_nr_hugepages $((2048 * 1024)) 0
00:04:06.725     135 		setup
00:04:06.725  => 136 		verify_nr_hugepages
00:04:06.726     137 	}
00:04:06.726     138 	
00:04:06.726     139 	per_node_2G_alloc() {
00:04:06.726     140 		# 2G alloc per node, total N*2G pages
00:04:06.726     141 		local IFS=","
00:04:06.726       ...
00:04:06.726  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:1055 -> run_test(["default_setup"],["default_setup"])
00:04:06.726       ...
00:04:06.726     1050		timing_enter $test_name
00:04:06.726     1051		echo "************************************"
00:04:06.726     1052		echo "START TEST $test_name"
00:04:06.726     1053		echo "************************************"
00:04:06.726     1054		xtrace_restore
00:04:06.726     1055		time "$@"
00:04:06.726     1056		xtrace_disable
00:04:06.726     1057		echo "************************************"
00:04:06.726     1058		echo "END TEST $test_name"
00:04:06.726     1059		echo "************************************"
00:04:06.726     1060		timing_exit $test_name
00:04:06.726       ...
00:04:06.726  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/setup/hugepages.sh:208 -> main([])
00:04:06.726       ...
00:04:06.726     203 	}
00:04:06.726     204 	
00:04:06.726     205 	get_nodes
00:04:06.726     206 	clear_hp
00:04:06.726     207 	
00:04:06.726  => 208 	run_test "default_setup" default_setup
00:04:06.726     209 	run_test "per_node_2G_alloc" per_node_2G_alloc
00:04:06.726     210 	run_test "even_2G_alloc" even_2G_alloc
00:04:06.726     211 	run_test "odd_alloc" odd_alloc
00:04:06.726     212 	run_test "custom_alloc" custom_alloc
00:04:06.726     213 	run_test "no_shrink_alloc" no_shrink_alloc
00:04:06.726       ...
00:04:06.726  
00:04:06.726  ========== Backtrace end ==========
00:04:06.726    12:50:21	-- common/autotest_common.sh@1123 -- # xtrace_enable
00:04:06.726    12:50:21	-- common/autotest_common.sh@1124 -- # return 0

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_88324.html

**Comment by mikeBashStuff** [comment]
WFP9 was not being properly reset upon previous failures - there were lingering qemu and vhost instance still running which use hugepages. This can be seen here: https://ci.spdk.io/results/autotest-per-patch/builds/88324/archive/nvmf-phy-autotest/proc_list.txt
This node was taken offline until issue with the APC is resolved.

**Comment by wanghailiangx** [comment]
Run ./test/setup/hugepages.sh, I can reproduce on some local servers.
Sometimes the function clear_hp doesn't work.
cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages **not 0**
cat /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages **not 0**

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_88448.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_88451.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88480.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88484.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88490.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88491.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88486.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88487.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88492.html

**Comment by Comphix** [comment]
@mikeBashStuff Michal, will you also take a look at this one? And is it also relating to issue #1999 ?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_88493.html

**Comment by mikeBashStuff** [comment]
@Comphix Yes, it's the same - I disabled WFP17 for now. Basically, we have issues with some of the APC units that are not performing proper power reset of the target nodes. You can identify this issue by looking into https://ci.spdk.io/results/autotest-per-patch/builds/88487/archive/vfio-user-autotest/proc_list.txt and see the lingering SPDK (reactor) and qemu processes. These are probably remains of failed vhost or vfio-user tests but it's hard to identify which one. The normal procedure is to reboot phy nodes upon failures like that but in this case some nodes stay online due to faulty APC.

> Run ./test/setup/hugepages.sh, I can reproduce on some local servers.
Sometimes the function clear_hp doesn't work.
cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages not 0
cat /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages not 0

This is true when there are processes around that still have hugepages allocated (so what we can see in the proc_list.txt basically).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88450.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88465.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88464.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88466.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88453.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88470.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88460.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88458.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88425.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88435.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88433.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88431.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88441.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88427.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_88440.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_91074.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_91475.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_91775.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_92510.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_93078.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_93258.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_93656.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_93831.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_96002.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_96085.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_96401.html

**Comment by mikeBashStuff** [comment]
Here's a series which attempts to mitigate similar issues https://review.spdk.io/gerrit/q/topic:mb-mitigate-crashes. As discussed during the bug scrub, the issue is a consequence of jenkins not being able to reset affected physical nodes due to a hard crash caused by one of the tests in the nvmf suite (zcopy, related to https://github.com/spdk/spdk/issues/2789). There's an ongoing work to pinpoint the state the affected machine ends up in after this test fails.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_97118.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_97563.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_99538.html

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue is now mitigated after merging patches from @mikeBashStuff

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_100454.html

**Comment by mikeBashStuff** [comment]
https://github.com/spdk/spdk/issues/2749#issuecomment-1476158013 This was caused by a faulty job that runs outside per-patch but uses same phy nodes. Fixed.
