### ISSUE TITLE
SPDK fails to init in single app which uses ODP (DPDK)

### ISSUE THREAD

**Issue by repu1sion** [spdk/spdk#275]
I have an app which needs to work with network and nvme both, linked with OpenDataPlane library. ODP itself does a DPDK init inside. After odp init I call spdk_env_init() which fails because dpdk was initialized already! It happens because  rte_eal_init() doesn't allow to be called twice (even in latest DPDK master). Somehow app seems to work if I just comment out rte_eal_init() call inside spdk_env_init(). So dpdk init is done by odp only. Is there maybe a correct way to check that dpdk is already inited so we would be able to avoid such a double init issue?

**Comment by SuFredyTing** [comment]
I have the same issue that rte_eal_init() doesn't allow to be called twice？could you share your solution with me？

**Comment by jimharris** [comment]
https://github.com/spdk/spdk/issues/529 was filed recently which is the same as this issue.

Closing this issue, since 529 has a discussion already started on how to improve SPDK to handle this use case.
