### ISSUE TITLE
[FAQ] how NVMF target specify run nvmf pollers into fixed CPU cores, not every core in SPDK process

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2755]
# Sighting report

[FAQ] how NVMF target specify run nvmf pollers into fixed CPU cores, not every core in SPDK process

## Expected Behavior

[FAQ] how NVMF target specify run nvmf pollers into fixed CPU cores, not every core in SPDK process

## Current Behavior

nvmf poller will run inside every SPDK core, can we specify only run nvmf in specific cores?
![image](https://user-images.githubusercontent.com/67108838/199179487-f65481da-657b-4261-93f3-14373096b83d.png)

## Steps to Reproduce

1. follow SPDK steps to set up nvmf tgt
2. start SPDK process with more CPU cores
3. run spdk_top, it will show the relationship
4.

## Context (Environment including OS version, SPDK version, etc.)

we would like one core is used for other task only, nvmf can pass message to other core, not using the same core cause performance not good enough.

**Comment by changpe1** [comment]
> SPDK could use NAPI_ID as the connection judgement for the pollers running on the core. Question is that what kinds of tasks you've described here? Are these also normal IOs from the host? Are these coming through dedicated connection or coming from each connection? Any method to differentiate these special tasks?

I think he is asking `nvmf_set_config` RPC to set a subset of CPU mask to nvmf poll groups.

**Comment by gaowayne** [comment]
> SPDK could use NAPI_ID as the connection judgement for the pollers running on the core. Question is that what kinds of tasks you've described here? Are these also normal IOs from the host? Are these coming through dedicated connection or coming from each connection? Any method to differentiate these special tasks?

other task is CSAL ftl core task poller, it poll requests from CSAL bdev, so I do not want NVMF poller also run the same core, how can I use NAPI_ID to make NVMF run on fixed core or exclude some cores.

**Comment by gaowayne** [comment]
> 

cool, I believe this is what we are looking, nvmf_set_config

**Comment by changpe1** [comment]
> > 
> 
> cool, I believe this is what we are looking, nvmf_set_config

Great, so I'm going to close this issue now.
