### ISSUE TITLE
MLX5 and some crypto driver performance drops significantly when large IO

### ISSUE THREAD

**Issue by yin19941005** [spdk/spdk#2756]
Hello,

# Sighting report

The MLX5 crypto driver and some crypto driver performance drops significantly when large amount of data transferring. The issue seems to be caused by the spdk vbdev_crypto re-enqueue implementation. For AESNI_MB crypto driver, it is not impacted by this issue.

The issue is not limited to MLX5 crypto driver. The crypto drivers has different approach on the timing for actual cryptography operation (encryption or decryption). For AESNI_MB crypto driver, the cryptography operation happens on the dequeue. On the other hand, MLX5 and OPENSSL crypto driver are performing the cryptography operation on enqueue. The issue should affect all the crypto driver trying to implement the cryptography operation on enqueue.

The issue seems to be caused by the spdk vbdev_crypto re-enqueue implementation. When a large amount of IO occur, the driver no longer able to enqueue all of them at once. The driver starts trying to re-enqueue (re-submit) the operation after dequeue. However, it starts to re-enqueue the request one by one instead of enqueue a batch of request and this causing the issue. Also just guessing, crypto acceleration is not helping much with small amount of data which also affect the performance.

## Expected Behavior

The MLX5 and other crypto driver should having a relative reasonable performance even it starts to re-enqueue, just as the AESNI_MB crypto driver.

## Current Behavior

The MLX5 and other crypto driver having terrible performance when it starts to re-enqueue.

## Possible Solution

1. Fix the re-enqueue implementation, don't try to re-enqueue the one by one but re-enqueue them with a single batch. Base on my understanding, spdk_io_channel is the per-thread context associated with a particular spdk_io_device. And this should also apply to crypto_io_channel. So, re-enqueue the operations in batch should be possible. However, how to locate the `op_to_resubmit->crypto_op` should be a problem.
 
2. Migrate the crypto operation for all affected crypto from enqueue to dequeue and adding a guide or instruction for crypto driver development. But this doesn't sound good to me.

## Steps to Reproduce

Prerequisite: a fast environment for reproduce. From my experience, if using NVMe-oF with 1Gb ethernet, almost impossible to reproduce the issue. I am using 100Gb ethernet and spot the issue.

For MLX5 crypto driver,
1. Follow the DPDK guide to setup keys and the env, https://doc.dpdk.org/guides/cryptodevs/mlx5.html
2. Make the SPDK with crypto option (MLX5 driver should be auto enabled if you get the Nvidia Hardware and driver installed)
3. Start the SPDK and start MLX5 crypto driver
4. Monitoring and launch a large amount of IO

For reference, to setup AESNI_MB crypto driver
1. Make the SPDK with crypto option
2. Start the SPDK and start AESNI_MB crypto driver
3. Monitoring and launch a large amount of IO

## Context (Environment including OS version, SPDK version, etc.)
I am using Nvidia Bluefield-2 with NVMe-oF environment on 100Gb network for the testing.

NVMe-oF initiator:
Using NIC: NVIDIA BLUEFIELD-2 DPU
OS version= "Ubuntu 20.04.3 LTS (Focal Fossa)" (not sure NVIDIA BLUEFIELD-2 DPU got any customization on it or not)
tested SPDK version: v22.05

For reference, NVMe-oF target:
Using NIC: NVIDIA Mellanox ConnectX-5
OS version= Rocky Linux 8.6
tested SPDK version: v22.05, v22.09, v23.01-pre

**Comment by Comphix** [comment]
This looks like an enhancement for the current handling?

**Comment by yin19941005** [comment]
Hi @Comphix,

Yes, this should be an enhancement for the current handling. However, there is another minor issue on the OpenSSL crypto driver related to this, and I will open an issue for it on DPDK.

**Comment by AlekseyMarchuk** [comment]
Hi @yin19941005 Thank you for posting so detailed description. I'm working on refactoring of SPDK crypto block device and crypto operations and I'll address issues found by you in this refactoring

**Comment by AlekseyMarchuk** [comment]
@yin19941005 
vbdev_crypto was significantly reworked in 23.01. Could you check if large IO performance is good enough? Please note that vbdev_crypto configuration has been changes, please refer to this article for more info: https://spdk.io/doc/bdev.html

**Comment by yin19941005** [comment]
Hi,

I am still checking this issue but it looks like the v23.01 (maybe related to new accel framework?) introduced #2759 issue to all crypto bdev. As the data is corrupted, I don't think the transfer rate reporting by the system is the actual value.

I was simply running linux dd tool to write zeros to bdev and trying to hexdump the drive to verify result. One of the hexdump result:

```
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
002dc000  f8 1b ad 8f 06 b0 10 b3  7d 58 5e 75 9a 50 d4 f8  |........}X^u.P..|
002dc010  cb b5 80 83 f2 5c 63 19  2d ad a0 d2 23 22 91 f1  |.....\c.-...#"..|
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00192000  55 f0 ae a8 d4 5f 47 cd  dd 6e 83 29 c5 1d 04 01  |U...._G..n.)....|
```
Some random data occur after some random address. 

But if I swap to 1GbE, everything works fine. The issue seems only occurring in high speed network (I was using 100GbE). 

I am still trying to figure out what's going on with the issue.

**Comment by yin19941005** [comment]
Hi @AlekseyMarchuk,

Thank you for your patches! The patches boost the IO performance quite a lot which is impressive but I am still looking for ways to optimize the mlx5 crypto driver IO performance. Is there any limitation of mlx5_pci crypto engine for single link? Let's say if I bind port 0 and port 1 together to a single link, is there difference to compare with using them separately except the link speed? How many mlx5_pci crypto acceleration engine is available? 

Once again thank you for your help and I look forward to hearing from you.

**Comment by AlekseyMarchuk** [comment]
Hi @yin19941005 
BF2 can do AES_XTS at 200Gbit/s bidirectional (200 Gbit on send (encrypt) and 200 Gbit on receive (decrypt)). If you use 2 ports then 200Gbit/s will be split by 2 ports, i.e. if the workload is evenly distributed between 2 ports then 1st port will do 100Gbits and 2nd port will do 100Gbits

**Comment by ksztyber** [comment]
[Bug scrub] @yin19941005 have the patches posted by @AlekseyMarchuk fixed the issue? If so, could you close the issue?
