### ISSUE TITLE
Question: Using Interface rte_ring_enqueue failed

### ISSUE THREAD

**Issue by YuanlongJing** [spdk/spdk#2757]
# Sighting report

We use dpdk rte ring but it seems to have some problem.
example codes such as:
<---------
ring_pool = rte_ring_create("test", 1024, SOCKET_ID_ANY, 0);
int i = 0;
for(i = 0; i < 1024; i++) {
        ret = rte_ring_enqueue(ring_pool, pool_addr);
}
---------->

we could find when "i" is 1023, rte_ring_enqueue always failed. return ret value is -105
It seems it will fail for en-queuing  the last elem.
Is it the expected result?

Thanks

**Comment by changpe1** [comment]
> rte_ring_create

DPDK guide says:
"The new ring size is set to *count*, which must be a power of two. Water marking is disabled by default. The real usable ring size is *count-1* instead of *count* to differentiate a full ring from an empty ring."

So this is expected, closing it now.
