### ISSUE TITLE
How to list all configure options that have been set in the current compiled code

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2758]
# Sighting report

For the same set of code, every time I switch from one test to another, an error may occur, and the report is missing a --with. I allways check it through `history | grep configure`. If there is a command to check the configure options, that might not need to re-configure and compile, that will be great. 

## Expected Behavior

A command to list the configure options

## Current Behavior

Don't know current configure options.

**Comment by changpe1** [comment]
@wanghailiangx  Does `./configure --help` helps?

**Comment by wanghailiangx** [comment]
Sorry, I didn't express it clearly enough, I mean to list the configure options that have been set in the currently compiled code. For example, run a command like:
`# ./configurelist`
Shows:
` --with-rdma --disable-unit-tests`

**Comment by mmkayPL** [comment]
Would the contents of mk/config.mk help then?

**Comment by wanghailiangx** [comment]
> Would the contents of mk/config.mk help then?

Thanks, this file is barely OK, but it doesn't display concisely enough. Also, disabled items(--disable) cannot be viewed.

**Comment by jimharris** [comment]
> Would the contents of mk/config.mk help then?

How about this patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/15249

It emits the configure options directly into the generated mk/config.mk file, like this:

```
#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (c) Intel Corporation.
#  All rights reserved.
#  Copyright (c) 2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#

# configure options: --enable-debug --with-rdma

# Installation prefix
CONFIG_PREFIX?=/usr/local

# Target architecture
CONFIG_ARCH?=native

# Destination directory for the libraries
CONFIG_LIBDIR?=
```

**Comment by wanghailiangx** [comment]
Thanks Jim's patch, it has been merged, I'm closing this issue now.
