### ISSUE TITLE
Are there anyway to run scrublet without hugepages? 

### ISSUE THREAD

**Issue by ZhenyuZ** [spdk/spdk#2762]
# Sighting report

The tool requires hugepages, and will fail on clusters where hugepages are not enabled. 

## Expected Behavior

We are a large data processing center. We expect all workflow to run on the same compute nodes consistently. 

## Current Behavior
As scrublet workflow requires special hugepages support, we have to assign it to a separate cluster/availability zone. 

## Possible Solution

Is there a way to update scrublet to run without hugepages support? Or at least provide an option to run it on nodes without hugepages. 

## Context (Environment including OS version, SPDK version, etc.)

This might work for individual bioinformaticians to run pipeline on a few compute node, this does not work well for large data processing clusters. 

Because enabling/disabling hugepage requires node reboot, and cannot happen inside of the workflow, we have to create a separate cluster of nodes that are dedicated to run (and only run) scrublet workflows.  We don't want to enable hugepages in all of our nodes because it affects node performance in general.

**Comment by Comphix** [comment]
Can you give us more relationship between scrublet and SPDK?

**Comment by changpe1** [comment]
I don't know why it matters with SPDK, closing it now.
