### ISSUE TITLE
GDB macros spdk_print_threads and spdk_print_threads no longer working

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#2763]
# Sighting report
Both of the above mentioned macros currently return an error on execution:

```
(gdb) spdk_print_threads
Python Exception <class 'gdb.error'> There is no member named tqh_first.: 
Error occurred in Python: There is no member named tqh_first.
```

## Expected Behavior
They should return the SPDK objects as in the documentation

```
SPDK object of type struct spdk_thread at 0x7fffd0008b50
((struct spdk_thread*) 0x7fffd0008b50)
name 0x7fffd00008e0 "reactor_1"
IO Channels:
        SPDK object of type struct spdk_io_channel at 0x7fffd0052610
        ((struct spdk_io_channel*) 0x7fffd0052610)
        name
        ref 1
        device 0x7fffd0008c80 (0x7fffd0008ce0 "nvmf_tgt")
        ---------------

        SPDK object of type struct spdk_io_channel at 0x7fffd0056cd0
        ((struct spdk_io_channel*) 0x7fffd0056cd0)
        name
        ref 2
        device 0x7fffd0056bf0 (0x7fffd0008e70 "test_vol1")
```

## Current Behavior

spdk_print_io_devices and spdk_print_threads return the above error, spdk_print_bdevs still works
## Possible Solution

It seems like both **struct io_device** (lib/thread/thread.c) and **struct spdk_io_channel** (lib/thread/thread_internal.h) have moved from storing the objects in a list, to a RB tree, so similar parsing methods need to be added to the gdb_macros.py

## Steps to Reproduce

1. Add path to gdb_macros.py to ~/.gdbinit (eg. **source /home/spdk/scrips/gdb_macros.py**)
2. Run SPDK app under gdb (**gdb ./build/bin/spdk_tgt**)
3. Run **spdk_load_macros**
4. Run **spdk_print_io_devices** or **spdk_print_threads**

## Context (Environment including OS version, SPDK version, etc.)
Commit cabbb25d5d3625115b6013bb7ad82b280bc5d9fa

**Comment by mhae** [comment]
@mmkayPL , we fixed it by adding the following to the macros which seems to work:
```
class SpdkRbTree(object):

    def __init__(self, list_pointer, list_member, tailq_name_list):
        self.list_pointer = list_pointer
        self.tailq_name_list = tailq_name_list
        self.list_member = list_member
        self.list = gdb.parse_and_eval(self.list_pointer)

    def get_left_node(self, node):
        return node['node']['rbe_left']

    def get_righ_node(self, node):
        return node['node']['rbe_right']

    def traverse_rb_tree(self, node):
        if node:
            self.rb_list.append(node)
            self.traverse_rb_tree(self.get_left_node(node))
            self.traverse_rb_tree(self.get_righ_node(node))

    def __iter__(self):
        self.rb_list = []
        tree_top = self.list['rbh_root']
        if tree_top:
            self.traverse_rb_tree(tree_top)
            for rb_node in self.rb_list:
                yield self.list_member(rb_node)
        else:
            yield

class IoChannels(SpdkRbTree):

    def __init__(self, list_obj):
        self.tailq_name_list = ['rbh_root']
        self.list_member = IoChannel
        self.list = list_obj

class RbPollers(SpdkRbTree):

    def __init__(self, list_obj):
        self.tailq_name_list = ['rbh_root']
        self.list_member = Poller
        self.list = list_obj

class SpdkThread(SpdkObject):

    type_name = 'struct spdk_thread'

    def __init__(self, gdb_obj):
        super(SpdkThread, self).__init__(gdb_obj)
        self.io_channels = IoChannels(self.obj['io_channels'])
        self.active_pollers = Pollers(self.obj['active_pollers'])
        self.timed_pollers = RbPollers(self.obj['timed_pollers'])
        self.paused_pollers = Pollers(self.obj['paused_pollers'])
...
```

**Comment by jimharris** [comment]
> @mmkayPL , we fixed it by adding the following to the macros which seems to work:
> 
> ```
> class SpdkRbTree(object):
> 
>     def __init__(self, list_pointer, list_member, tailq_name_list):
>         self.list_pointer = list_pointer
>         self.tailq_name_list = tailq_name_list
>         self.list_member = list_member
>         self.list = gdb.parse_and_eval(self.list_pointer)
> 
>     def get_left_node(self, node):
>         return node['node']['rbe_left']
> 
>     def get_righ_node(self, node):
>         return node['node']['rbe_right']
> 
>     def traverse_rb_tree(self, node):
>         if node:
>             self.rb_list.append(node)
>             self.traverse_rb_tree(self.get_left_node(node))
>             self.traverse_rb_tree(self.get_righ_node(node))
> 
>     def __iter__(self):
>         self.rb_list = []
>         tree_top = self.list['rbh_root']
>         if tree_top:
>             self.traverse_rb_tree(tree_top)
>             for rb_node in self.rb_list:
>                 yield self.list_member(rb_node)
>         else:
>             yield
> 
> class IoChannels(SpdkRbTree):
> 
>     def __init__(self, list_obj):
>         self.tailq_name_list = ['rbh_root']
>         self.list_member = IoChannel
>         self.list = list_obj
> 
> class RbPollers(SpdkRbTree):
> 
>     def __init__(self, list_obj):
>         self.tailq_name_list = ['rbh_root']
>         self.list_member = Poller
>         self.list = list_obj
> 
> class SpdkThread(SpdkObject):
> 
>     type_name = 'struct spdk_thread'
> 
>     def __init__(self, gdb_obj):
>         super(SpdkThread, self).__init__(gdb_obj)
>         self.io_channels = IoChannels(self.obj['io_channels'])
>         self.active_pollers = Pollers(self.obj['active_pollers'])
>         self.timed_pollers = RbPollers(self.obj['timed_pollers'])
>         self.paused_pollers = Pollers(self.obj['paused_pollers'])
> ...
> ```

Thanks @mhae.

Could someone incorporate this into a patch so we can get these changes into upstream for others to use?

-Jim

**Comment by Comphix** [comment]
Thanks @mhae , will you raise a patch for the fix? Thanks.

**Comment by mmkayPL** [comment]
@mhae Thanks! I went ahead and cleaned up the changes a bit (just naming to make sure we're not calling tree nodes lists in the script) and posted the review here. I noticed you have additional Pollers and Poller objects, I think these can be added separately?
https://review.spdk.io/gerrit/c/spdk/spdk/+/15330

**Comment by mhae** [comment]
@mmkayPL , thanks so much for the cleaning it up and posting it for review. Agreed, we don't need to add the additional poller objects.

**Comment by jimharris** [comment]
> @mmkayPL , thanks so much for the cleaning it up and posting it for review. Agreed, we don't need to add the additional poller objects.

Yes - thanks @mmkayPL!  The patch looks good, I left a small comment on Gerrit.
