### ISSUE TITLE
[bdev_qos_iops] unable to reach IOPS target

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2766]
# CI Intermittent Failure

During one run of bdev_qos_iops, it was trying to reach 33,000 IOPS but could only hit 27,502 IOPS.  It needed to do at least 29,700 to pass.  There were no changes in this commit or others in the series before this that are likely to impact performance.  Other executions of the same test on other operating systems and a retest did not show this problem.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/88938/archive/ubuntu18-vg-autotest/build.log

## Execution failed at

```
00:07:08.346  ************************************
00:07:08.346  START TEST bdev_qos_iops
00:07:08.346  ************************************
00:07:08.346   06:00:47	-- common/autotest_common.sh@1058 -- # xtrace_enable
00:07:08.346   06:00:47	-- common/autotest_common.sh@1059 -- # run_qos_test 33000 IOPS Malloc_0
00:07:08.346   06:00:47	-- bdev/blockdev.sh@322 -- # local qos_limit=33000
00:07:08.346   06:00:47	-- bdev/blockdev.sh@323 -- # local qos_result=0
00:07:08.346    06:00:47	-- bdev/blockdev.sh@325 -- # get_io_result IOPS Malloc_0
00:07:08.346    06:00:47	-- bdev/blockdev.sh@308 -- # local limit_type=IOPS
00:07:08.346    06:00:47	-- bdev/blockdev.sh@309 -- # local qos_dev=Malloc_0
00:07:08.346    06:00:47	-- bdev/blockdev.sh@310 -- # local iostat_result
00:07:08.346     06:00:47	-- bdev/blockdev.sh@311 -- # /home/vagrant/spdk_repo/spdk/scripts/iostat.py -d -i 1 -t 5
00:07:08.346     06:00:47	-- bdev/blockdev.sh@311 -- # grep Malloc_0
00:07:08.346     06:00:47	-- bdev/blockdev.sh@311 -- # tail -1
00:07:13.610    06:00:52	-- bdev/blockdev.sh@311 -- # iostat_result='Malloc_0  27502.40  110009.61  0.00       0.00       111048.00  0.00     0.00   '
00:07:13.610    06:00:52	-- bdev/blockdev.sh@312 -- # '[' IOPS = IOPS ']'
00:07:13.610     06:00:52	-- bdev/blockdev.sh@313 -- # awk '{print $2}'
00:07:13.610    06:00:52	-- bdev/blockdev.sh@313 -- # iostat_result=27502.40
00:07:13.610    06:00:52	-- bdev/blockdev.sh@318 -- # echo 27502
00:07:13.610   06:00:52	-- bdev/blockdev.sh@325 -- # qos_result=27502
00:07:13.610   06:00:52	-- bdev/blockdev.sh@326 -- # '[' IOPS = BANDWIDTH ']'
00:07:13.610   06:00:52	-- bdev/blockdev.sh@329 -- # lower_limit=29700
00:07:13.610   06:00:52	-- bdev/blockdev.sh@330 -- # upper_limit=36300
00:07:13.610   06:00:52	-- bdev/blockdev.sh@333 -- # '[' 27502 -lt 29700 ']'
00:07:13.610   06:00:52	-- bdev/blockdev.sh@334 -- # echo 'Failed to limit the io read rate of NULL bdev by qos'
00:07:13.610  Failed to limit the io read rate of NULL bdev by qos
```

**Comment by Comphix** [comment]
From the log https://ci.spdk.io/results/autotest-per-patch/builds/88938/archive/ubuntu18-vg-autotest/build.log

When QoS is disabled, the IO is about io_result=134548, the calculated and set QoS goal is 33000 while the actual result is 27502 which is far below than the 10% threshold of variation.

**Comment by mgerdts** [comment]
@Comphix I think that I had that in my initial summary.  I don't know of any way to understand what caused this.  Was it unlucky scheduling of the qos thread on a reactor that was busy?  Was the server relatively idle when it did 134k IOPS and extremely busy when it could only do 27.5k IOPS?  Is there something else going on?  I don't see how my changes could be to blame, but I'm not at all comfortable as a potential user of qos that the performance can degrade unexpectedly like this.

**Comment by Comphix** [comment]
So this is coming from the CI result of your working patches? Could you point me the related patch? QoS will be handled on the specific spdk_thread and if that related CPU is not busy, it shall get the CPU resource and expect the reach the setting Limit.

**Comment by shuhei-matsumoto** [comment]
@Comphix The patch by Mike is https://review.spdk.io/gerrit/c/spdk/spdk/+/15278/5

**Comment by Comphix** [comment]
Seems that the change is not relating to QoS. Let me pay attention to the recent per patch testing to check if there is other instance of same failure.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_88938.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_92461.html

**Comment by Comphix** [comment]
This issue is not recently and there is also another QoS issue #2861 . Let me close this one.
