### ISSUE TITLE
[unittest_pci_event] valgrind-vg job hits timeout while executing pci_event_ut

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2767]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-per-patch/builds/89162/archive/valgrind-vg-autotest/build.log

```
00:07:37.292  START TEST unittest_pci_event
00:07:37.292  ************************************
00:07:37.292   21:09:16	-- common/autotest_common.sh@1058 -- # xtrace_enable
00:07:37.292   21:09:16	-- common/autotest_common.sh@1059 -- # valgrind --leak-check=full --error-exitcode=2 /home/vagrant/spdk_repo/spdk/test/unit/lib/env_dpdk/pci_event.c/pci_event_ut
00:07:37.292  ==77564== Memcheck, a memory error detector
00:07:37.292  ==77564== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
00:07:37.292  ==77564== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
00:07:37.292  ==77564== Command: /home/vagrant/spdk_repo/spdk/test/unit/lib/env_dpdk/pci_event.c/pci_event_ut
00:07:37.292  ==77564== 
00:41:48.636  Cancelling nested steps due to timeout
00:41:48.640  Sending interrupt signal to process
00:42:00.314  script returned exit code 255
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_89163.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_89162.html

**Comment by jimharris** [comment]
There seems to be something wrong with this valgrind job.  This whole series seems to have failed too from the same issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/13813.

This seems to be failing not due to something with this unit test in particular, but because it's the first unit test that gets run in unittest.sh.

Is this valgrind job new, or has it been changed recently?

**Comment by jimharris** [comment]
OK, let's keep this open for now.  I just filed https://github.com/spdk/spdk/issues/2769 against the valgrind job too - it seems unrelated but thought I'd mention it.

**Comment by ksztyber** [comment]
[Bug scrub] Patches that should fix this were already merged, closing.
