### ISSUE TITLE
SPDK unitest failed 

### ISSUE THREAD

**Issue by sumanchakraborty1510** [spdk/spdk#277]
Hi ,

While executing the unittest.sh in the latest spdk master  i am getting histogram_test failed . Is it expected ?

Suite: histogram
  Test: histogram_test ...FAILED
    1. histogram_ut.c:76  - **values <= end
    2. histogram_ut.c:71  - **values >= start
    3. histogram_ut.c:71  - **values >= start
    4. histogram_ut.c:71  - **values >= start
    5. histogram_ut.c:85  - count == 0
    6. histogram_ut.c:61  - so_far == (g_total + count)
    7. histogram_ut.c:76  - **values <= end
    8. histogram_ut.c:61  - so_far == (g_total + count)
    9. histogram_ut.c:76  - **values <= end
    10. histogram_ut.c:61  - so_far == (g_total + count)
    11. histogram_ut.c:71  - **values >= start
    12. histogram_ut.c:71  - **values >= start
    13. histogram_ut.c:85  - count == 0

Run Summary:    Type  Total    Ran Passed Failed Inactive
                          suites      1      1           n/a      0        0
                            tests        1      1            0         1        0
                             asserts     28     28       15        13      n/a

**Comment by peluse** [comment]
No, unit tests on master should always pass.  I’d double check and make sure you have a clean shot of master, sounds maybe like you have a mix of multiple versions.  I just ran mine w/o problems.

**Comment by dverkamp-intel** [comment]
As Paul mentioned, the unit tests should always be passing on master; they are executed as part of the autotest.sh framework (https://ci.spdk.io/spdk/status/), as well as Travis CI (https://travis-ci.org/spdk/spdk/).

Can you provide some more details on what your configuration is like? (Compiler version, Linux distro, SPDK configure options, etc.)

**Comment by WenqianZong** [comment]
I can not reproduce histogram_test ...FAILED when start unittest.sh with latest SPDK version. please provide detail reproduce step.

**Comment by wanqunintel** [comment]
@sumanchakraborty1510 This unittest should pass with latest SPDK version, do you have the test steps on how this occur?

**Comment by wanqunintel** [comment]
@sumanchakraborty1510 can you see if you see this issue with latest code v18.04, if you can not see, we may close it.

**Comment by jimharris** [comment]
Closing this issue as not reproducible.  If you are able to reproduce on v18.04, please post a log and reopen this issue.
