### ISSUE TITLE
created raid5f size is not as expected

### ISSUE THREAD

**Issue by ye1xchen** [spdk/spdk#2771]
# Sighting report

Create three 32MB malloc bdevs and add them all to raid5f, but raid5f shows only 64MB instead of 96MB.

## Expected Behavior

raid5f size is 96MB.

## Current Behavior

raid5f size is 64MB.

## Steps to Reproduce

./scripts/rpc.py bdev_malloc_create 32 512 -b Malloc0
./scripts/rpc.py bdev_malloc_create 32 512 -b Malloc1
./scripts/rpc.py bdev_malloc_create 32 512 -b Malloc2
./scripts/rpc.py bdev_raid_create -n raid5f -z 2 -r 5f -b "Malloc0 Malloc1 Malloc2"
 ./scripts/rpc.py bdev_get_bdevs
[
  {
    "name": "Malloc0",
    "aliases": [
      "93e40797-2923-4b89-ab8b-e74ce8a3ed15"
    ],
    "product_name": "Malloc disk",
    "block_size": 512,
    "num_blocks": 65536,
    "uuid": "93e40797-2923-4b89-ab8b-e74ce8a3ed15",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": true,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": true,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {}
  },
  {
    "name": "Malloc1",
    "aliases": [
      "e0495be5-4324-465d-8280-bc53e7633c63"
    ],
    "product_name": "Malloc disk",
    "block_size": 512,
    "num_blocks": 65536,
    "uuid": "e0495be5-4324-465d-8280-bc53e7633c63",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": true,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": true,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {}
  },
  {
    "name": "Malloc2",
    "aliases": [
      "4446b564-b0fd-44a3-baa0-be8079daed9f"
    ],
    "product_name": "Malloc disk",
    "block_size": 512,
    "num_blocks": 65536,
    "uuid": "4446b564-b0fd-44a3-baa0-be8079daed9f",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": true,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": true,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {}
  },
  {
    "name": "**raid5f**",
    "aliases": [
      "2c7f290d-a76f-412e-99c5-bcebade0e7a6"
    ],
    "product_name": "Raid Volume",
    "block_size": 512,
    "num_blocks": **131072**,
    "uuid": "2c7f290d-a76f-412e-99c5-bcebade0e7a6",
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": false,
    "zoned": false,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": false,
      "write_zeroes": true,
      "flush": false,
      "reset": true,
      "compare": false,
      "compare_and_write": false,
      "abort": false,
      "nvme_admin": false,
      "nvme_io": false
    },
    "driver_specific": {
      "raid": {
        "strip_size_kb": 2,
        "state": 0,
        "raid_level": "raid5f",
        "destruct_called": 0,
        "num_base_bdevs": 3,
        "num_base_bdevs_discovered": 3,
        "base_bdevs_list": [
          "Malloc0",
          "Malloc1",
          "Malloc2"
        ]
      }
    }
  }
]

raid5f size should be 96MB but shows only 64MB.

## Context (Environment including OS version, SPDK version, etc.)

OS: fedora32
last spdk: 3afa8c2f434ee48727636a9f3c05f4172d70aa4c

**Comment by tomzawadzki** [comment]
@ye1xchen This is expected behavior of RAID5, capacity of one disk is reserved for redundancy. The expected size you mention matches behavior of RAID0 for example, that does not have any redundancy.

**Comment by mmkayPL** [comment]
To expand on this - bdev_get_bdevs returns the exposed number of blocks. With 3 disks in a RAID5(F), the total number of used up blocks is 96MiB, but the user can only write to 64MiBs, the last 32 being used for XOR.

**Comment by jimharris** [comment]
Closing this issue as expected behavior.
