### ISSUE TITLE
[sw_hotplug] Application didn't terminate in time

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2774]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-per-patch/builds/89466/archive/nvme-phy-autotest/build.log

After the test finishes its hotplug operation via sysfs it waits extra `$hotplug_wait` before proceeding to check app's status. It assumes that if the app is still running, it terminates it and considers the operation as failure. This potentially may introduce some false positives unless we wait long enough (extra 6s may be not that long) - from the log below it's not clear if the application did indeed
hang. 

The 1819d49e4f9405d0f8c75fd621f3b8ae58e2f45c changed a logic a bit to guard the test from freezing, however, it dropped control over the actual status of the app. 

I think that either we should allow the app to freeze (which clearly indicates a failure and potential bugs) by either reverting the logic, or applying some longer timeout on existing implementation (which match more closely the arguments that are passed to the app as from the look of it we should wait for extra `$hotplug_wait`). I would consider using `timeout` to control that as well, e.g.:

```
diff --git a/test/nvme/sw_hotplug.sh b/test/nvme/sw_hotplug.sh
index c351d6c58..d0214e187 100755
--- a/test/nvme/sw_hotplug.sh
+++ b/test/nvme/sw_hotplug.sh
@@ -67,9 +67,11 @@ remove_attach_helper() {
 }

 run_hotplug() {
+       local tt
+       tt=$((hotplug_events * hotplug_wait + hotplug_wait * 3))
        trap 'killprocess $hotplug_pid; exit 1' SIGINT SIGTERM EXIT

-       "$SPDK_EXAMPLE_DIR/hotplug" \
+       timeout -k$((tt + 5)) "$tt" "$SPDK_EXAMPLE_DIR/hotplug" \
                -i 0 \
                -t $((hotplug_events * hotplug_wait + hotplug_wait * 3)) \
                -n $((hotplug_events * nvme_count)) \
@@ -78,19 +80,7 @@ run_hotplug() {
        hotplug_pid=$!

        remove_attach_helper "$hotplug_events" "$hotplug_wait" false
-
-       # Wait in case hotplug app is lagging behind
-       # and kill it, if it hung.
-       sleep $hotplug_wait
-
-       if ! kill -0 "$hotplug_pid"; then
-               # hotplug already finished, check for the error code.
-               wait "$hotplug_pid"
-       else
-               echo "Killing hotplug application"
-               killprocess $hotplug_pid
-               return 1
-       fi
+       wait "$hotplug_pid"

```

```
00:16:15.741   21:19:39	-- nvme/sw_hotplug.sh@62 -- # for dev in "${nvmes[@]}"
00:16:15.741   21:19:39	-- nvme/sw_hotplug.sh@63 -- # echo 0000:d9:00.0
00:16:16.000  Attaching to 0000:5e:00.0
00:16:17.905  Attached to 0000:5e:00.0
00:16:17.905  INTEL SSDPE2KX020T8  (BTLJ126204352P0BGN  ):          0 I/Os completed (+0)
00:16:17.905  
00:16:18.732   21:19:41	-- nvme/sw_hotplug.sh@64 -- # echo 0000:d9:00.0
00:16:18.732   21:19:41	-- nvme/sw_hotplug.sh@68 -- # sleep 6
00:16:18.992  Attaching to 0000:d8:00.0
00:16:21.526  Attached to 0000:d8:00.0
00:16:21.526  INTEL SSDPE2KX020T8  (BTLJ126204352P0BGN  ):        128 I/Os completed (+128)
00:16:21.526  INTEL SSDPE2MD400G4  (CVFT6176004P400GGN  ):          0 I/Os completed (+0)
00:16:21.526  
00:16:22.634  Attaching to 0000:5f:00.0
00:16:23.799  Attaching to 0000:d9:00.0
00:16:24.367   21:19:47	-- nvme/sw_hotplug.sh@25 -- # (( hotplug_events-- ))
00:16:24.367   21:19:47	-- nvme/sw_hotplug.sh@87 -- # sleep 6
00:16:25.745  Attached to 0000:d9:00.0
00:16:25.745  Attached to 0000:5f:00.0
00:16:25.745  unregister_dev: INTEL SSDPE2KX020T8  (BTLJ126204352P0BGN  )
00:16:25.745  unregister_dev: INTEL SSDPE2MD400G4  (CVFT6176004P400GGN  )
00:16:25.745  unregister_dev: INTEL SSDPE2MD400G4  (CVFT6123001Z400GGN  )
00:16:25.745  unregister_dev: INTEL SSDPE2MD400G4  (CVFT61750039400GGN  )
00:16:31.018   21:19:53	-- nvme/sw_hotplug.sh@89 -- # kill -0 3050106
00:16:31.018   21:19:53	-- nvme/sw_hotplug.sh@93 -- # echo 'Killing hotplug application'
00:16:31.018  Killing hotplug application
00:16:31.018   21:19:53	-- nvme/sw_hotplug.sh@94 -- # killprocess 3050106
00:16:31.018   21:19:53	-- common/autotest_common.sh@890 -- # '[' -z 3050106 ']'
00:16:31.018   21:19:53	-- common/autotest_common.sh@894 -- # kill -0 3050106
00:16:31.018    21:19:53	-- common/autotest_common.sh@895 -- # uname
00:16:31.018   21:19:53	-- common/autotest_common.sh@895 -- # '[' Linux = Linux ']'
00:16:31.018    21:19:53	-- common/autotest_common.sh@896 -- # ps --no-headers -o comm= 3050106
00:16:31.018   21:19:53	-- common/autotest_common.sh@896 -- # process_name=hotplug
00:16:31.018   21:19:53	-- common/autotest_common.sh@900 -- # '[' hotplug = sudo ']'
00:16:31.018   21:19:53	-- common/autotest_common.sh@908 -- # echo 'killing process with pid 3050106'
00:16:31.018  killing process with pid 3050106
00:16:31.018   21:19:53	-- common/autotest_common.sh@909 -- # kill 3050106
00:16:31.018   21:19:53	-- common/autotest_common.sh@914 -- # wait 3050106
00:16:31.018   21:19:53	-- nvme/sw_hotplug.sh@95 -- # return 1
00:16:31.018    21:19:53	-- nvme/sw_hotplug.sh@144 -- # trap - ERR
00:16:31.018    21:19:53	-- nvme/sw_hotplug.sh@144 -- # print_backtrace
00:16:31.018    21:19:53	-- common/autotest_common.sh@1090 -- # [[ ehxBET =~ e ]]
00:16:31.018    21:19:53	-- common/autotest_common.sh@1092 -- # args=()
00:16:31.018    21:19:53	-- common/autotest_common.sh@1092 -- # local args
00:16:31.018    21:19:53	-- common/autotest_common.sh@1094 -- # xtrace_disable
00:16:31.018    21:19:53	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
00:16:31.018    21:19:53	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
00:16:31.018    21:19:53	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
00:16:31.018    21:19:53	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
00:16:31.018    21:19:53	-- common/autotest_common.sh@24 -- # set +x
00:16:31.018  ========== Backtrace start: ==========
00:16:31.018  
00:16:31.018  in test/nvme/sw_hotplug.sh:144 -> main([])
00:16:31.018       ...
00:16:31.018     139 	xtrace_disable
00:16:31.018     140 	cache_pci_bus_sysfs
00:16:31.018     141 	xtrace_restore
00:16:31.018     142 	
00:16:31.018     143 	# Run pci bus hotplug test
00:16:31.018  => 144 	run_hotplug
00:16:31.018     145 	
00:16:31.018     146 	# Run SPDK target based hotplug
00:16:31.018     147 	tgt_run_hotplug
00:16:31.018       ...
00:16:31.018  
00:16:31.018  ========== Backtrace end ==========
00:16:31.018    21:19:53	-- common/autotest_common.sh@1130 -- # xtrace_enable
00:16:31.018    21:19:53	-- common/autotest_common.sh@1131 -- # return 0
00:16:31.018   21:19:53	-- nvme/sw_hotplug.sh@1 -- # killprocess 3050106
00:16:31.018   21:19:53	-- common/autotest_common.sh@890 -- # '[' -z 3050106 ']'
00:16:31.018   21:19:53	-- common/autotest_common.sh@894 -- # kill -0 3050106
00:16:31.018  /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh: line 894: kill: (3050106) - No such process
00:16:31.018   21:19:53	-- common/autotest_common.sh@917 -- # echo 'Process with pid 3050106 is not found'
00:16:31.018  Process with pid 3050106 is not found
00:16:31.018   21:19:53	-- nvme/sw_hotplug.sh@1 -- # exit 1
00:16:31.018    21:19:53	-- common/autotest_common.sh@1062 -- # trap - ERR
00:16:31.018    21:19:53	-- common/autotest_common.sh@1062 -- # print_backtrace
00:16:31.018    21:19:53	-- common/autotest_common.sh@1090 -- # [[ ehxBET =~ e ]]
00:16:31.018    21:19:53	-- common/autotest_common.sh@1092 -- # args=('test/nvme/sw_hotplug.sh' 'sw_hotplug' '/var/jenkins/workspace/nvme-phy-autotest/autorun-spdk.conf')
00:16:31.018    21:19:53	-- common/autotest_common.sh@1092 -- # local args
00:16:31.018    21:19:53	-- common/autotest_common.sh@1094 -- # xtrace_disable
00:16:31.018    21:19:53	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
00:16:31.018    21:19:53	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
00:16:31.018    21:19:53	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
00:16:31.018    21:19:53	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
00:16:31.018    21:19:53	-- common/autotest_common.sh@24 -- # set +x
00:16:31.018  ========== Backtrace start: ==========
00:16:31.018  
00:16:31.018  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:1062 -> run_test(["sw_hotplug"],["test/nvme/sw_hotplug.sh"])
00:16:31.018       ...
00:16:31.018     1057		timing_enter $test_name
00:16:31.018     1058		echo "************************************"
00:16:31.018     1059		echo "START TEST $test_name"
00:16:31.018     1060		echo "************************************"
00:16:31.018     1061		xtrace_restore
00:16:31.018     1062		time "$@"
00:16:31.018     1063		xtrace_disable
00:16:31.018     1064		echo "************************************"
00:16:31.018     1065		echo "END TEST $test_name"
00:16:31.018     1066		echo "************************************"
00:16:31.018     1067		timing_exit $test_name
00:16:31.019       ...
00:16:31.019  in /var/jenkins/workspace/nvme-phy-autotest/spdk/autotest.sh:225 -> main(["/var/jenkins/workspace/nvme-phy-autotest/autorun-spdk.conf"])
00:16:31.019       ...
00:16:31.019     220 			run_test "nvme_rpc_timeouts" test/nvme/nvme_rpc_timeouts.sh
00:16:31.019     221 			# Only test hotplug without ASAN enabled. Since if it is
00:16:31.019     222 			# enabled, it catches SEGV earlier than our handler which
00:16:31.019     223 			# breaks the hotplug logic.
00:16:31.019     224 			if [ $SPDK_RUN_ASAN -eq 0 ] && [ $(uname -s) = Linux ]; then
00:16:31.019  => 225 				run_test "sw_hotplug" test/nvme/sw_hotplug.sh
00:16:31.019     226 			fi
00:16:31.019     227 	
00:16:31.019     228 			if [[ $SPDK_TEST_XNVME -eq 1 ]]; then
00:16:31.019     229 				run_test "nvme_xnvme" test/nvme/xnvme/xnvme.sh
00:16:31.019     230 				run_test "blockdev_xnvme" test/bdev/blockdev.sh "xnvme"
00:16:31.019       ...
00:16:31.019  
00:16:31.019  ========== Backtrace end ==========
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_89466.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krzysztofsmolinski. log: https://ci.spdk.io/public_build/autotest-per-patch_89376.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krzysztofsmolinski. log: https://ci.spdk.io/public_build/autotest-per-patch_89351.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_90861.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_90935.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_90949.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_91409.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_91878.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_92216.html

**Comment by KKaras169169** [comment]
Suggested use of "timeout" command is already incorporated as part of [this patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/15965), which also aims to fix #2201.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_96837.html

**Comment by KKaras169169** [comment]
A little update here: patch linked in my comment from Jan 24 has been reverted due to a bug. Here is a new version of this change: https://review.spdk.io/gerrit/c/spdk/spdk/+/16543

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_99832.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_100152.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_100171.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @benlwalker. log: https://ci.spdk.io/public_build/autotest-per-patch_100059.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_100204.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_100322.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_100587.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_100614.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_100657.html

**Comment by KKaras169169** [comment]
The sw_hotplug script does not throw any errors besides the timeout - in the last linked fail for example, device "0000:5f:00.0" was unable to attach due to time for hotplug application running out.
I think we should not be so strict with time when it comes to attaching and removing devices, as we sometimes encounter a race condition (we assue that all operations should be done in some time, which is apparently not always the case).
We already have some communication with hotplug app (usage of bdev_get_bdevs RPC to make sure a device was attached/removed), so the only solution I see here is to fine tune the timings on the sw_hotplug.sh side (I think we need to be more lenient with how much time we let hotplug app run for).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_100911.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_101056.html

**Comment by jimharris** [comment]
This one is clearly related to #2201, and this one also hasn't happened in over 5 weeks.  That doesn't seem like a coincidence.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/18077 (based on suggestion from @mikeBashStuff in #2201 thread).

General idea is that the time it takes to process a hotplug is highly variable.  So don't try to figure out a maximum time for the hotplug app to wait for the expected events.  Just let it keep running until it gets all of them.  CI already has a global timeout if it actually gets hung waiting for events that never show up.

**Comment by jimharris** [comment]
> https://review.spdk.io/gerrit/c/spdk/spdk/+/18077 (based on suggestion from @mikeBashStuff in #2201 thread).
> 
> General idea is that the time it takes to process a hotplug is highly variable. So don't try to figure out a maximum time for the hotplug app to wait for the expected events. Just let it keep running until it gets all of them. CI already has a global timeout if it actually gets hung waiting for events that never show up.

Based on discussion in today's community call, we will keep the timeout parameter, but add `-t 0` as an option to disable the timeout.  We identified some possibilities for using the parameter in the future, so keep it around for now.  We will still disable the timeout for in-tree tests, to fix this issue.

https://review.spdk.io/gerrit/c/spdk/spdk/+/18158

**Comment by jimharris** [comment]
Patches merged.
