### ISSUE TITLE
configure: --with/without-DEPENDENCY return unrecognized error

### ISSUE THREAD

**Issue by KanKuox123** [spdk/spdk#2776]
# Sighting report
./configure --with-DEPENDENCY
./configure --without-DEPENDENCY
all return unrecognized error.

## Expected Behavior
return no error

## Current Behavior
return unrecognized error

## Steps to Reproduce

1. ./configure --with-DEPENDENCY
   ./configure --without-DEPENDENCY

**Comment by changpe1** [comment]
"DEPENDENCY" means the modules that supported in SPDK not the word itself.
