### ISSUE TITLE
Problem with building SPDK（use a special version of DPDK）

### ISSUE THREAD

**Issue by YuanlongJing** [spdk/spdk#2780]
We wish to use a version of DPDK different from the submodule included in the SPDK repository.
But int the new DPDK version,  we have to build DPDK by using meson and ninja way.
It seems to miss some files in the new DPDK version.
So We couldn't build SPDK  by using the following cmd such as :

_./configure --with-dpdk=/path/to/dpdk/x86_64-native-linuxapp-gcc
make_

Please help to check.
Thank you.

**Comment by Comphix** [comment]
Hi Tomek, will you take a look at this? The question here is to configure a user specified DPDK folder. Thanks.

**Comment by changpe1** [comment]
@YuanlongJing please provide detailed information of SPDK and DPDK, include DPDK version and build flags etc.

**Comment by wanghailiangx** [comment]
@YuanlongJing You may cd spdk/dpdk, git branch -a to see all branch, and git check one old branch. Or git pull an old spdk, copy it's dpdk and dpdkbuild to your new spdk dir, rebuild. Here is spdk/dpdk repos.
https://review.spdk.io/gerrit/admin/repos/spdk/dpdk,general
But if you do this, you may encounter the similar following error.
`#error RTE_VERSION is too old! Minimum 19.11 is required.`

**Comment by wanghailiangx** [comment]
@YuanlongJing Is your problem solved? If there is no doubt, we will close this question. If there is any later, you can reopen it.
