### ISSUE TITLE
NVMe over RDMA is malfunctioning or stuck at ibv_get_async_event after restart network.service

### ISSUE THREAD

**Issue by KKRainbow** [spdk/spdk#2786]
# Sighting report

If making a Linux bonding device over two ports of a CX4/CX5 device, NVMe over RDMA will just stop working after modifying bonding slaves or restarting the network.service.

## Expected  Behavior

The NVMF subsystems should function normally after the network operations are completed.

## Current Behavior

I observed two possible results after the bonding slaves is modified.

1. The polling thread is stuck at ibv_get_async_event. the stack is in the __context__ section. 
2. Port listeners are stopped and all NVMF client is disconnected.

## Possible Solution

This problem is the result of the improper handling of RDMA_CM_EVENT_DEVICE_REMOVAL & IBV_EVENT_DEVICE_FATAL events. I found a correlated issue #1184 in which a patch is merged to remove all ports when a device receives the RDMA_CM_EVENT_DEVICE_REMOVAL event.

This patch has two problems.
1. It only destroyed all resources belonging to librdmacm such as listening cm_id and qpair cm_id. But the objects belonging to libuverbs are not destroyed properly.  e.g. CQ is still being polled. MR & SRQ is not unregistered. Async fd in ibv_context is not closed.  Considering that the device and driver are already reset we should also deallocate these things. Besides, IBV_EVENT_DEVICE_FATAL is not handled so if there is no cm_id bound to the device, all device resources will not be cleaned.

2. The patch assumed that the device will be removed permanently. It may be true with soft ROCE but not with real-world NIC. I tested with both CX4 & CX5 which both use the mlx5 driver.  After making a bonding device over the two ports of the NIC card, the InfiniBand device is removed and comes back in a short period when removing/adding slaves to the bonding master. I analyzed the driver code and confirmed that it's a by-designed behavior for at least the mlx5 driver. The operation on bonding slaves is also something that happens during the restarting of the network.service.

I investigated the rdma-core lib and find that IB devices hotplugging is supported after commit 4deaad058 (v30.0). So I try to make [a patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/15541) to correctly handle the device removal events. With that patch, all listeners will keep working and resources are properly deallocated. Initiators will also reconnect normally after listeners come back.

## Steps to Reproduce

1. Create bonding over two ports on the same CX4/CX5 card.

```bash
sudo ip link add bond0 type bond mode 1
sudo ip link set em1 down && sudo ip link set em1 master bond0
sudo ip link set em2 down && sudo ip link set em2 master bond0
sudo ip link set bond0 up
sudo ip addr add 10.0.57.75/24 dev bond0
```

2. Launch nvmf_tgt and create listener & subsystem & ns.

```bash
./nvmf_tgt &
scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -i 131072 -c 8192
scripts/rpc.py nvmf_get_transports
scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.0.57.75 -s 4422
```

3. Connect the host to the target.

``` bash
sudo nvme connect -n nqn.2016-06.io.spdk:cnode1 -a 10.0.57.75 -s 4422 -t rdma --reconnect-delay=1
```

4. Remove a slave from bonding.

```bash
echo -em1 | sudo tee /sys/class/net/bond1/bonding/slaves
# echo +em1 | sudo tee /sys/class/net/bond1/bonding/slaves
```

## Context (Environment including OS version, SPDK version, etc.)

spdk origin/master c6ffad06fac1aa41c2c59140286d9165f8d786c4
linux-4.18
rdma-core-54mlnx1-1.54310
CX4 / CX5

- Situation 1: stuck at ibv_get_async_event

```
#0  0x00007fc2345d22d4 in __libc_read (fd=1693, buf=0x7fc1715f8cc0, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x00007fc234482f1f in ibv_get_async_event () from /lib64/libibverbs.so.1
#2  0x000055911d84db8f in nvmf_process_ib_event (device=0x559133896360) at rdma.c:3080
#3  nvmf_process_ib_events (max_events=<optimized out>, device=<optimized out>) at rdma.c:3158
#4  nvmf_rdma_accept (transport=0x559120e747e0) at rdma.c:3195
#5  0x000055911d83d969 in nvmf_tgt_accept (ctx=<optimized out>) at nvmf.c:254
#6  0x000055911d85d6de in thread_execute_timed_poller (now=141298014272020, poller=0x559133868340, thread=0x559120e7ee00)
    at thread.c:865
#7  thread_poll (thread=thread@entry=0x559120e7ee00, max_msgs=max_msgs@entry=0, now=now@entry=141298014272020) at thread.c:953
#8  0x000055911d85e13e in spdk_thread_poll (thread=thread@entry=0x559120e7ee00, max_msgs=max_msgs@entry=0, now=141298014272020,
    now@entry=0) at thread.c:979
#9  0x000055911d34e972 in zbs::spdk_reactor_run (arg=0x559120e4ce20) at src/common/spdk.cc:89
```

- Situation 2: port is removed and listeners stop working.

```
[2022-11-21 16:45:40.451641] rdma.c:3290:nvmf_process_ib_event: *NOTICE*: Async event: GID table change
[2022-11-21 16:45:40.451694] rdma.c:3290:nvmf_process_ib_event: *NOTICE*: Async event: GID table change
[2022-11-21 16:45:40.451711] rdma.c:3290:nvmf_process_ib_event: *NOTICE*: Async event: GID table change
[2022-11-21 16:45:42.350665] rdma.c:3290:nvmf_process_ib_event: *NOTICE*: Async event: port active
[2022-11-21 16:45:42.350730] rdma.c:3290:nvmf_process_ib_event: *NOTICE*: Async event: GID table change
[2022-11-21 16:45:42.350757] rdma.c:3290:nvmf_process_ib_event: *NOTICE*: Async event: GID table change
[2022-11-21 16:45:43.189456] rdma.c:3034:nvmf_rdma_handle_cm_event_port_removal: *NOTICE*: Port 10.0.57.75:4422 is being removed
```

**Comment by AlekseyMarchuk** [comment]
A link to patch from @KKRainbow https://review.spdk.io/gerrit/c/spdk/spdk/+/15541

**Comment by tomzawadzki** [comment]
Just for future reference, the patch above has been split into separate series starting here https://review.spdk.io/gerrit/c/spdk/spdk/+/15614/3

**Comment by jimharris** [comment]
@KKRainbow @AlekseyMarchuk these patches have been merged, can we close this issue?

**Comment by AlekseyMarchuk** [comment]
Hi @jimharris only the 1st patch was merged, other patches are under review. I think we can merge them in 23.01, I'll focus on reviewing these patches

**Comment by KKRainbow** [comment]
Sorry, the patches were blocked by a CI failure for a moment and the problem has been figured out. I've updated the patch set and wait for review. @jimharris

**Comment by AlekseyMarchuk** [comment]
All patches are merged, the issue can be closed. Thanks to @KKRainbow for great job!
