### ISSUE TITLE
spdk_bdev fio cannot execute when spdk_tgt application is running due to maintain kernel device like /dev/spdk/nvme0

### ISSUE THREAD

**Issue by shadiao233** [spdk/spdk#2787]
# Sighting report
spdk_bdev fio cannot execute when spdk_tgt application is running due to maintain kernel device like /dev/spdk/nvme0

## Expected Behavior
spdk_bdev fio should progess normally

## Current Behavior
```
root@SHLAP0202004:~# fio /root/spdk/examples/bdev/fio_plugin/example_config.conf
test: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=8
fio-3.30
Starting 1 thread
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-11-22 01:18:44.442761] pci.c:1037:spdk_pci_device_claim: *ERROR*: Cannot create lock on device /var/tmp/spdk_pci_lock_0000:06:00.0, probably process 4420 has claimed it
[2022-11-22 01:18:44.442779] nvme_pcie.c: 890:nvme_pcie_ctrlr_construct: *ERROR*: could not claim device 0000:06:00.0 (Permission denied)
[2022-11-22 01:18:44.442783] nvme.c: 677:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:06:00.0
EAL: Driver cannot attach the device (0000:06:00.0)
EAL: Failed to attach device on primary process
[2022-11-22 01:18:44.442864] nvme.c: 815:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2022-11-22 01:18:44.442868] nvme.c: 892:spdk_nvme_probe: *ERROR*: Create probe context failed
[2022-11-22 01:18:44.442871] fio_plugin.c: 663:spdk_fio_setup: *ERROR*: spdk_nvme_probe() failed
test: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:1155, func=total_file_size, error=Invalid argument

Run status group 0 (all jobs):
```

here is .conf:
```
[global]
ioengine=/root/spdk/build/fio/spdk_bdev
spdk_json_conf=/root/spdk/examples/bdev/fio_plugin/bdev.json

thread=1
direct=1
group_reporting=1

bs=4k
rw=randread
rwmixread=70
time_based=1
runtime=10
norandommap=1

[test]
filename=Nvme1n1
iodepth=8
```

here is .json:
```
{
"subsystems": [
{
"subsystem": "bdev",
"config": [
{
"method": "bdev_nvme_attach_controller",
"params": {
"trtype": "PCIe",
"name":"Nvme1",
"traddr":"0000:06:00.0"
}
}
]
}
]
}
```

why will spdk_bdev do bdev_nvme_attach_controller again while a bdev device /dev/spdk/nvme0 has already done this when generating it . it seems that the application spdk_tgt has conflicts with spdk_bdev
i tried spdk_bdev fio successfully before setup spdk_tgt, but it is meaningless if i want to operate by bdev device

## Possible Solution
spdk_bdev fio share process with spdk_tgt may solve this problem

## Steps to Reproduce

1.generate a bdev device /dev/spdk/nvme0
2.generate .json: scripts/gen_nvme.sh --json-with-subsystems > /root/spdk/examples/bdev/fio_plugin/bdev.json
3.config fio
4.run fio

## Context (Environment including OS version, SPDK version, etc.)
```
spdk v22.09
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by shadiao233** [comment]
> For FIO performance testing, you may just use FIO SPDK Bdev plugin with SPDK bdevs.
oh is that mean i cannot use fio while cuse_device has been generated?
what about spdk_tgt? can both of them exist at same time?

**Comment by Comphix** [comment]
> > For FIO performance testing, you may just use FIO SPDK Bdev plugin with SPDK bdevs.
> > oh is that mean i cannot use fio while cuse_device has been generated?
> > what about spdk_tgt? can both of them exist at same time?

This SPDK generated kernel device is more for control patch purpose and not for the performance testing purpose as it will introduce overhead here.

For spdk_tgt, yes, it could co-exist and when spdk_tgt is using the bdev, for generated /dev/spdk/nvme0 and /dev/spdk/nvme0n1, you could use the nvme cli tool to collect information like smart-log, id-ctrlr such kinds of commands. Once the /dev/spdk/nvme0 device is not used, you could use the RPC cuse_unregister to remove it.

**Comment by shadiao233** [comment]
> > > For FIO performance testing, you may just use FIO SPDK Bdev plugin with SPDK bdevs.
> > > oh is that mean i cannot use fio while cuse_device has been generated?
> > > what about spdk_tgt? can both of them exist at same time?
> 
> This SPDK generated kernel device is more for control patch purpose and not for the performance testing purpose as it will introduce overhead here.
> 
> For spdk_tgt, yes, it could co-exist and when spdk_tgt is using the bdev, for generated /dev/spdk/nvme0 and /dev/spdk/nvme0n1, you could use the nvme cli tool to collect information like smart-log, id-ctrlr such kinds of commands. Once the /dev/spdk/nvme0 device is not used, you could use the RPC cuse_unregister to remove it.

ok i get it ,i'll try it later,thank you for explaination

**Comment by Comphix** [comment]
@shadiao233 , if there is no other question, I will close this issue. Thanks.

**Comment by ksztyber** [comment]
[Bug scrub] Let's close this one. @shadiao233 , feel free to reopen if you have any more questions.
