### ISSUE TITLE
UUIDs generated for nvme bdevs do not conform to standards

### ISSUE THREAD

**Issue by apaszkie** [spdk/spdk#2788]
# Sighting report

When the `generate_uuids` option is enabled in `bdev_nvme_set_options`, the generated UUIDs are based on a non-standard algorithm. The UUID format is standardized:

https://datatracker.ietf.org/doc/html/rfc4122
https://pubs.opengroup.org/onlinepubs/9629399/apdxa.htm
https://en.wikipedia.org/wiki/Universally_unique_identifier

## Expected Behavior

The UUIDs should be generated according to the standards.

## Current Behavior

The generated UUIDs are non-standard. For example:
```
1e7b002c-3c00-847a-0123-456789abcdef
1e7b0026-cb06-747a-0123-456789abcdef
```

## Possible Solution

The recommended way to generate UUIDs based on strings is to use version-5 UUID (see [RFC 4122](https://datatracker.ietf.org/doc/html/rfc4122#section-4.3)). The uuid_generate_sha1() function from libuuid can be used for that. This library is already used by lib/util/uuid.c.

## Steps to Reproduce

1. Use bdev_nvme_set_options RPC with generate_uuids set to true.
2. Use bdev_nvme_attach_controller RPC on a nvme device which has a namespace without a UUID.
3. Use bdev_get_bdevs RPC and check the nvme bdev's UUID.

## Context (Environment including OS version, SPDK version, etc.)

spdk origin/master (13b7f1b20)

**Comment by changpe1** [comment]
@apaszkie I don't think this is a problem, actually it's SPDK's intention to do like this via commit b5bdbbb9598.

**Comment by apaszkie** [comment]
> @apaszkie I don't think this is a problem, actually it's SPDK's intention to do like this via commit [b5bdbbb](https://github.com/spdk/spdk/commit/b5bdbbb9598badb6c6b11193654f1cccb64896cc).

I understand that the intention was to always generate the same UUID for a nvme bdev based on serial number and namespace ID. The same thing can be achieved using version-5 (also version-3) UUIDs. They are generated by hashing a string - the result is always the same as long as the string is the same.

**Comment by changpe1** [comment]
> > @apaszkie I don't think this is a problem, actually it's SPDK's intention to do like this via commit [b5bdbbb](https://github.com/spdk/spdk/commit/b5bdbbb9598badb6c6b11193654f1cccb64896cc).
> 
> I understand that the intention was to always generate the same UUID for a nvme bdev based on serial number and namespace ID. The same thing can be achieved using version-5 (also version-3) UUIDs. They are generated by hashing a string - the result is always the same as long as the string is the same.

@jimharris @tomzawadzki @KKaras169169 what's your opinion about this?

**Comment by jimharris** [comment]
> > > @apaszkie I don't think this is a problem, actually it's SPDK's intention to do like this via commit [b5bdbbb](https://github.com/spdk/spdk/commit/b5bdbbb9598badb6c6b11193654f1cccb64896cc).
> > 
> > 
> > I understand that the intention was to always generate the same UUID for a nvme bdev based on serial number and namespace ID. The same thing can be achieved using version-5 (also version-3) UUIDs. They are generated by hashing a string - the result is always the same as long as the string is the same.
> 
> @jimharris @tomzawadzki @KKaras169169 what's your opinion about this?

Using the RFC 4122 described method would be better.

@apaszkie is there something functional that breaks with the current UUID format?

**Comment by apaszkie** [comment]
> @apaszkie is there something functional that breaks with the current UUID format?

Nothing that I'm aware of. I just think that these UUIDs should follow the standard and be consistent with what spdk_uuid already uses.

**Comment by KKaras169169** [comment]
I will take a look and change the way we currently generate UUIDs to follow the standards.
