### ISSUE TITLE
[nvmf_zcopy] Operation not permitted during spdk_nvme_qpair_process_completions

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#2789]
# CI Intermittent Failure

The test timeouts due to not being able to process qpair completions (spamming the last log for 20+seconds), before that it also seems to have problems with namespaces, though I'm not sure if it's related:

```
00:13:23.290  [2022-11-23 09:51:08.023626] subsystem.c:1607:spdk_nvmf_subsystem_add_ns_ext: *ERROR*: Requested NSID 1 already in use
00:13:23.290  [2022-11-23 09:51:08.023662] nvmf_rpc.c:1234:nvmf_rpc_ns_paused: *ERROR*: Unable to add namespace
```

## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_90684.html
https://ci.spdk.io/results/autotest-per-patch/builds/90684/archive/nvmf-tcp-vg-autotest/index.html (note the log is 100+MiB in size)
VM-host-SM18

## Execution failed at

```
00:13:28.814   09:51:13	-- target/zcopy.sh@51 -- # /home/vagrant/spdk_repo/spdk/build/examples/abort -c 0x1 -t 5 -q 64 -w randrw -M 50 -l warning -r 'trtype:tcp adrfam:IPv4 traddr:10.0.0.2 trsvcid:4420 ns:1'
00:13:29.071  TELEMETRY: No legacy callbacks, legacy socket not created
00:13:32.345  [2022-11-23 09:51:17.007696] tcp.c: 967:_tcp_write_pdu: *ERROR*: IC_RESP or TERM_REQ could not write to socket.
00:13:32.345  [2022-11-23 09:51:17.007868] tcp.c:1450:nvmf_tcp_qpair_set_recv_state: *ERROR*: The recv state of tqpair=0x1f388e0 is same with the state(5) to be set
00:13:34.288  [2022-11-23 09:51:19.007290] nvme_qpair.c: 750:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -1 (Operation not permitted) on qpair id 1
00:13:34.288  [2022-11-23 09:51:19.007472] nvme_qpair.c: 750:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -1 (Operation not permitted) on qpair id 1
00:13:34.288  [2022-11-23 09:51:19.007522] nvme_qpair.c: 750:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -1 (Operation not permitted) on qpair id 1
00:13:34.288  [2022-11-23 09:51:19.007590] nvme_qpair.c: 750:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -1 (Operation not permitted) on qpair id 1

```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_90684.html

**Comment by ksztyber** [comment]
Those logs related to the namespace not being able to be added are expected - the test does it intentionally, because it's the easiest way to enforce subsystem pause/resume and we want to make sure requests using zero-copy are handled correctly in that case.

```
00:13:32.345  [2022-11-23 09:51:17.007696] tcp.c: 967:_tcp_write_pdu: *ERROR*: IC_RESP or TERM_REQ could not write to socket.
```
This seems to be the real problem here. Unfortunately, the logs don't say much, so it's hard to tell why this happened.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_90976.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_91247.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_91383.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_92097.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @richael02. log: https://ci.spdk.io/public_build/autotest-per-patch_92489.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_93470.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_93828.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_96082.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_97092.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wanghailiangx. log: https://ci.spdk.io/public_build/autotest-per-patch_97305.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_97560.html

**Comment by ksztyber** [comment]
This patch should fix this: https://review.spdk.io/gerrit/c/spdk/spdk/+/16641

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jlevon. log: https://ci.spdk.io/public_build/autotest-per-patch_97913.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98050.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_98068.html
