### ISSUE TITLE
[nvmf-tcp-phy-autotest] tar: spdk/mk: Cannot mkdir: Permission denied

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#2790]
# CI Intermittent Failure

00:00:21.441  Saving response body to /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk_50144d2a7b05ef549b1143c555627c9f7008ac24.tar.gz
00:00:37.193  [Pipeline] sh
00:00:37.502  + tar xf spdk_50144d2a7b05ef549b1143c555627c9f7008ac24.tar.gz
00:00:37.502  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.502  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.502  tar: spdk/mk/spdk.app.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk_blank.map: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/nvme.libtest.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.lib.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.modules.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.common.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.unittest.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.mock.unittest.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.lib_deps.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.app_vars.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.subdirs.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.app_cxx.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.nvmecli.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.deps.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/mk: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/mk/spdk.fio.mk: Cannot open: No such file or directory
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts/sync_dev_uevents.sh: Cannot open: No such file or directory
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts/pc.sh: Cannot open: No such file or directory
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts/gen_ftl.sh: Cannot open: No such file or directory
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts/rxe_cfg_small.sh: Cannot open: No such file or directory
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts/detect_cc.sh: Cannot open: No such file or directory
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts/genconfig.py: Cannot open: No such file or directory
00:00:37.503  tar: spdk/scripts: Cannot mkdir: Permission denied
00:00:37.503  tar: spdk/scripts/bpftrace.sh: Cannot open: No such file or directory

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/90783/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

00:00:37.502  + tar xf spdk_50144d2a7b05ef549b1143c555627c9f7008ac24.tar.gz
00:00:37.502  tar: spdk/mk: Cannot mkdir: Permission denied

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_90977.html

**Comment by jimharris** [comment]
Assigning to @mikeBashStuff to take an initial look.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_91251.html

**Comment by mikeBashStuff** [comment]
Will try to look into this as soon as possible.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_97116.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_97585.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_97570.html

**Comment by ksztyber** [comment]
[Bug scrub] Last report was over a month ago, closing until it reappears again.
