### ISSUE TITLE
spdk_top: top menu display and refresh issues

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2793]
# Sighting report

After launching spdk_top only the first button of the top tab menu can be seen:

![spdk_top_bad_menu](https://user-images.githubusercontent.com/49611974/203981216-9dcbfe21-8968-4e1e-b6c0-0f136f441cb3.png)

Another issue can be spotted after closing large pop-up windows (eg. when scheduler is set to dynamic and all threads are running on core 0 and user opens pop-up in CORES tab or user opens the help popup with small terminal window):

![spdk_top_no_menu_refresh](https://user-images.githubusercontent.com/49611974/203981541-3a95c3a4-4823-4d8e-9619-46ac87a57cb3.png)

## Possible Solution

For the first issue: the COLOR_PAIR in draw_tab_win() should be changed from 2 to 10.

For the second issue: a complete interface refresh should be performed to avoid leaving unrefreshed parts of the window buffer. This can be done by simply redrawing windows where needed.

## Steps to Reproduce

1. build SPDK (./configure; make -j)
2. launch spdk_top (./build/bin/spdk_top) - at this point first issue can be seen
3. decrease size of terminal, so a pop-up draws on top of the top parts of interface
4. exit the pop-up - at this point the second issue can be seen

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 22.04 LTS (Jammy Jellyfish), SPDK v23.01-pre git sha1 e3110f45d

**Comment by KKaras169169** [comment]
Fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/15655

**Comment by wanghailiangx** [comment]
I didn't see the phenomenon you mentioned, could you try another machine with different kernel?
