### ISSUE TITLE
spdk_top: top and bottom menu display issue

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2794]
# Sighting report

In some server like fc29(kernel 5.3.11), fc34(5.11.12), fc30(5.4.7), fc29(5.5.1), there is some confusion about the background strip as below.
While in Ubuntu 20.04.2(5.4.0), fc34(5.16.18), fc32(5.11.22) that is OK.

<img width="917" alt="spdk_top2" src="https://user-images.githubusercontent.com/28918060/204210330-3bea417d-ac2c-4560-ac03-34dd2de36343.PNG">

## Expected Behavior
<img width="804" alt="spdk_top3" src="https://user-images.githubusercontent.com/28918060/204219871-cd6509d4-5555-4865-93a5-2751d2c8544b.PNG">

## Possible Solution
This may be related to the kernel version.

## Steps to Reproduce

1../build/bin/nvmf_tgt
2../build/bin/spdk_top

## Context (Environment including OS version, SPDK version, etc.)
SPDK: the latest version.

**Comment by jimharris** [comment]
Hi @wanghailiangx,

Can you confirm, this happens just with starting nvmf_tgt and then spdk_top - no RPCs, configuration, spdk_top actions, etc?

fc34 w/ 5.11.12 kernel works fine, but fc34 w/ 5.16.18 kernel does not?  Were there any other changes between the two - i.e. other package upgrades?  I guess it is possible that kernel version could affect this somehow, but I would think curses package changes would be a more likely culprit.

@KKaras169169, I'm assigning this to you, to work with @wanghailiangx to get more details.

-Jim

**Comment by wanghailiangx** [comment]
@jimharris @KKaras169169 This happens just with starting nvmf_tgt and then spdk_top - no other operation. As for the comparison of other upgrade packages, I will look for them too.

**Comment by karlatec** [comment]
> In some server like fc29(kernel 5.3.11), fc34(5.11.12), fc30(5.4.7), fc29(5.5.1), there is some confusion about the background strip as below.

> I think this might be a problem with NCURSES version

If this confirms and this is a ncurses version issue then I think we should close this issue as `won't fix`. Fedora 29 and Fedora 30 are EOL for quite some time now.

**Comment by KKaras169169** [comment]
After some investigating and discussions, I decided to close this issue. Fedora 29 and 30 are EOL and we will not support spdk_top on those.

**Comment by jimharris** [comment]
> After some investigating and discussions, I decided to close this issue. Fedora 29 and 30 are EOL and we will not support spdk_top on those.

FWIW, I agree with your decision to close it.
