### ISSUE TITLE
how to get nvme controller flags from bdev

### ISSUE THREAD

**Issue by skypexu** [spdk/spdk#2795]
# Sighting report

After a nvme device is opened by bdev layer, is there a way to get nvme controller information ?

## Expected Behavior

Expect to be able to get nvme controller informations

## Current Behavior
no way to get nvme controller

## Possible Solution
Don't know

## Context (Environment including OS version, SPDK version, etc.)
spdk version: v22.05.x
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by Comphix** [comment]
Please refer https://spdk.io/doc/nvme.html, search "Enabling cuse support for NVMe" which is able to support the tool like nvme cli to query the NVMe controller information.
