### ISSUE TITLE
how to config bit_bucket_data_len in .fio config file with offset?

### ISSUE THREAD

**Issue by shadiao233** [spdk/spdk#2796]
# Sighting report
how to config bit_bucket_data_len in .fio config file with offset?
![image](https://user-images.githubusercontent.com/51295923/204246537-29aac679-41ae-41e6-99f2-b754b902be2a.png)
![image](https://user-images.githubusercontent.com/51295923/204246650-405e4eda-1d8a-48a2-ac3f-4ece40158ed4.png)
could you please give an example? 
thanks a lot!

## Context (Environment including OS version, SPDK version, etc.)

spdk version: 22.09

**Comment by changpe1** [comment]
@shadiao233  As an example, you can set the following 3 parameters for READ commands 
`enable_sgl=1`
`sge_size=4096`
`bit_bucket_data_len=1024`

But make sure that your SSD drive can support this feature, currently we only add the READ support in the nvme driver.

**Comment by shadiao233** [comment]
> 



> @shadiao233 As an example, you can set the following 3 parameters for READ commands `enable_sgl=1` `sge_size=4096` `bit_bucket_data_len=1024`
> 
> But make sure that your SSD drive can support this feature, currently we only add the READ support in the nvme driver.

well how to set the offset of bit_bucket_data_len? or it maybe definited by user?

**Comment by changpe1** [comment]
> > 
> 
> > @shadiao233 As an example, you can set the following 3 parameters for READ commands `enable_sgl=1` `sge_size=4096` `bit_bucket_data_len=1024`
> > But make sure that your SSD drive can support this feature, currently we only add the READ support in the nvme driver.
> 
> well how to set the offset of bit_bucket_data_len? or it maybe definited by user?

You can overwrite the layout of each SGE(e.g include offset) in fio plugin source code by yourself.

**Comment by shadiao233** [comment]
> 



> > > 
> > 
> > 
> > > @shadiao233 As an example, you can set the following 3 parameters for READ commands `enable_sgl=1` `sge_size=4096` `bit_bucket_data_len=1024`
> > > But make sure that your SSD drive can support this feature, currently we only add the READ support in the nvme driver.
> > 
> > 
> > well how to set the offset of bit_bucket_data_len? or it maybe definited by user?
> 
> You can overwrite the layout of each SGE(e.g include offset) in fio plugin source code by yourself.

all right ,thanks for your explaination~
