### ISSUE TITLE
gpt: off-by-one error in size

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2801]
# Sighting report

`vbdev_gpt_create_bdevs()` creates gpt bdevs that are one block smaller than the actual partition.

## Expected Behavior

The partition size and the gpt bdev size should match.

## Current Behavior

The gpt bdev is one block smaller than the partition.

## Possible Solution

Absent compatibility concerns, this is a simple one-liner.

```diff
diff --git a/module/bdev/gpt/vbdev_gpt.c b/module/bdev/gpt/vbdev_gpt.c
index b93da2893..d5c377df6 100644
--- a/module/bdev/gpt/vbdev_gpt.c
+++ b/module/bdev/gpt/vbdev_gpt.c
@@ -339,7 +339,7 @@ vbdev_gpt_create_bdevs(struct gpt_base *gpt_base)
                }

                rc = spdk_bdev_part_construct(&d->part, gpt_base->part_base, name,
-                                             lba_start, lba_end - lba_start, "GPT Disk");
+                                             lba_start, lba_end - lba_start + 1, "GPT Disk");
                free(name);
                if (rc) {
                        SPDK_ERRLOG("could not construct bdev part\n");
```

I'm concerned that this could be toxic to data on the device if the following happens:

1. Create an SPDK partition on a device
2. With a version of SPDK without a fix for this bug, expose that partition to some consumer by way of a gpt bdev.
3. The consumer lays down data structures that are sensitive to the size.
4. SPDK is upgraded to a version with this fix.
5. The consumer recognizes that the device has grown by one block and adjusts on-disk data structures accordingly.
6. For some reason, SPDK needs to be downgraded.
7. The consumer recognizes that the device has shrunk, a condition that it cannot handle.

## Steps to Reproduce

I don't have an environment handy to reproduce. Please let me know if you need help reproducing.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 22.09, OS-independent. Observed on Rocky Linux 8.5, Ubuntu 20.04.

**Comment by wanghailiangx** [comment]
If it's convenient, please push a patch, is that ok?

**Comment by jimharris** [comment]
> If it's convenient, please push a patch, is that ok?

It's a bit more complicated than that.  We need to have a strategy for how to properly communicate the possibility of steps 6 and 7 in Mike's list above.

I'm taking ownership of this one for now.

**Comment by mgerdts** [comment]
See https://review.spdk.io/gerrit/c/spdk/spdk/+/14964

**Comment by jimharris** [comment]
We only create bdevs for partitions that have the SPDK_GPT_PART_TYPE_GUID partition type.  So I think the best way to fix this is to do the following:

* Create a new SPDK_GPT_PART_TYPE_GUID_2
* If we find a partition with type PART_TYPE_GUID, we still register the bdev with the off-by-one size.
* If we find a partition with type PART_TYPE_GUID_2, we register the bdev with the correct size.

This way if someone does create a partition with TYPE_GUID_2 on SPDK 23.01 for example, if they go back and try to use it on older SPDK, it just won't get recognized at all which is the desired behavior I think.

I don't think we should deprecate the "old" PART_TYPE_GUID, supporting both will be very minimal code and easily commented.  We could print some kind of warning message, although it would be purely informative, I don't really want to recommend any kind of migration path for those partitions to gain that extra block.

**Comment by jimharris** [comment]
This still needs some work, but posting for initial feedback:

https://review.spdk.io/gerrit/c/spdk/spdk/+/16298

**Comment by mgerdts** [comment]
I love the simplicity of this approach.  Great idea @jimharris!

**Comment by tomzawadzki** [comment]
Patch fixing this issue has been merged https://github.com/spdk/spdk/commit/3a39d90b03f7581d60716e3e9cf4dbcf7c48b08a
