### ISSUE TITLE
SPDK vhost aio_bdev error report

### ISSUE THREAD

**Issue by yewhen** [spdk/spdk#2802]
# Sighting report
I was trying to use "a hard disk cached by NVME ssd on host" at vm by SPDK vhost application, nvme bdev and aio bdev. 

## Expected Behavior
No error should be expected I guess. 

## Current Behavior
host-side vhost log:
............
[2022-11-30 17:50:43.013568] vhost_blk.c: 607:virtio_blk_process_request: *WARNING*: Ignore the unmap flag for WRITE ZEROES from 1078181c000, len 200000
[2022-11-30 17:50:43.133567] vhost_blk.c: 607:virtio_blk_process_request: *WARNING*: Ignore the unmap flag for WRITE ZEROES from 10781a1c000, len 200000
[2022-11-30 18:41:37.687260] bdev_aio.c: 362:bdev_aio_io_channel_poll: *ERROR*: failed to complete aio: rc 16384 12288
[2022-11-30 18:41:37.687409] Cache1: read_miss failed with error 1
[2022-11-30 18:42:17.180358] bdev_aio.c: 362:bdev_aio_io_channel_poll: *ERROR*: failed to complete aio: rc 16384 12288
[2022-11-30 18:42:17.180445] Cache1: read_miss failed with error 1

(12288 was the aio_task->len I added to the SPDK_ERRLOG print to check.)

vm-side mysql error-log:
2022-11-30T11:42:16.307245Z 0 [Warning] [MY-012638] [InnoDB] Retry attempts for reading partial data failed.
2022-11-30T11:42:16.307266Z 0 [ERROR] [MY-012642] [InnoDB] Tried to read 16384 bytes at offset 19332972544, but was only able to read 0
2022-11-30T11:42:16.307281Z 0 [ERROR] [MY-012592] [InnoDB] Operating system error number 5 in a file operation.
2022-11-30T11:42:16.307298Z 0 [ERROR] [MY-012596] [InnoDB] Error number 5 means 'Input/output error'
2022-11-30T11:42:16.307312Z 0 [ERROR] [MY-012646] [InnoDB] File (unknown): 'read' returned OS error 105. Cannot continue operation
2022-11-30T11:42:16.307322Z 0 [ERROR] [MY-012981] [InnoDB] Cannot continue operation.
2022-11-30T11:42:26.549443Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 10 seconds for 128 pending reads
2022-11-30T11:42:36.653476Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 20 seconds for 128 pending reads
2022-11-30T11:42:46.758310Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 30 seconds for 128 pending reads
2022-11-30T11:42:56.862619Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 40 seconds for 128 pending reads
2022-11-30T11:43:06.966868Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 50 seconds for 128 pending reads

## Steps to Reproduce

1./tmp/spdk/build/bin/vhost -S /var/tmp/ -m 2000000000020000000
2./tmp/spdk/scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:d8:00.0
3./tmp/spdk/scripts/rpc.py bdev_split_create -s 61440 Nvme0n1 4
4./tmp/spdk/scripts/rpc.py bdev_aio_create /dev/sdb4 core1
5./tmp/spdk/scripts/rpc.py bdev_ocf_create Cache1 wt Nvme0n1p0 core1 --cache-line-size 4
6./tmp/spdk/scripts/rpc.py vhost_create_blk_controller --cpumask 2000000000000000000 vhostblk0 Cache1
7.virsh start xx_vm and run mysql's tpcc test framework

## Context (Environment including OS version, SPDK version, etc.)
qemu arguments in vm's xml file:

qemu:commandline
<qemu:arg value='-object'/>
<qemu:arg value='memory-backend-file,id=mem0,size=64G,mem-path=/dev/hugepages,share=on'/>
<qemu:arg value='-numa'/>
<qemu:arg value='node,memdev=mem0'/>
<qemu:arg value='-chardev'/>
<qemu:arg value='socket,id=spdk_vhost_blk0,path=/var/tmp/vhostblk0'/>
<qemu:arg value='-device'/>
<qemu:arg value='vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=1'/>
</qemu:commandline>

kernel version: 5.10.0
architecture: x86_64
SPDK v22.05

**Comment by changpe1** [comment]
@yewhen could this happen with aio bdev only? I mean you can have a try with `core1` block device without OCF, we need to narrow down this a little bit.

**Comment by yewhen** [comment]
no, it doesn't happen with aio bdev only.

**Comment by yewhen** [comment]
Furthermore, when the Nvme ssd size is 60G for cache, I can get this error everytime, but I never encountered this error when I use 200G Nvme ssd. (The mysql data directory is 104G in total)

**Comment by yewhen** [comment]
any idea?

**Comment by yewhen** [comment]
@changpe1

**Comment by changpe1** [comment]
> > @changpe1
> 
> I think this may relate with the OCF module, since you can reproduce this issue, I suggest you can add a check in `bdev_aio_readv` to validate `nbytes` with total data buffer length in `iov` to see the two values are same or not.

as the error message you added above, if total data buffer length is 16384 while the nbytes is 12288, we might to add code to treat this as a normal case.

**Comment by changpe1** [comment]
@yewhen Can you also use `bdev_aio_create` with block size set to 4096 to have another try ?

**Comment by yewhen** [comment]
Another question, how about the case iovcnt is greater than 1?

> > > @changpe1
> > 
> > 
> > I think this may relate with the OCF module, since you can reproduce this issue, I suggest you can add a check in `bdev_aio_readv` to validate `nbytes` with total data buffer length in `iov` to see the two values are same or not.
> 
> as the error message you added above, if total data buffer length is 16384 while the nbytes is 12288, we might to add code to treat this as a normal case.

**Comment by changpe1** [comment]
> Another question, how about the case iovcnt is greater than 1?
> 
> > > > @changpe1
> > > 
> > > 
> > > I think this may relate with the OCF module, since you can reproduce this issue, I suggest you can add a check in `bdev_aio_readv` to validate `nbytes` with total data buffer length in `iov` to see the two values are same or not.
> > 
> > 
> > as the error message you added above, if total data buffer length is 16384 while the nbytes is 12288, we might to add code to treat this as a normal case.

iovcnt could be greater than 1, this is a normal case.

**Comment by yewhen** [comment]
Let me clarify one thing first: aio_task->len is the requested length and events[i].res is the actual read length, right?

**Comment by changpe1** [comment]
> Let me clarify one thing first: aio_task->len is the requested length and events[i].res is the actual read length, right?

yes, from my understanding, if the total buffer length is also 16384, we should treat it as a normal case, but we still need to dig why data buffer length is greater than the actual read length.

**Comment by yewhen** [comment]
make sense, let me verify it now.

**Comment by yewhen** [comment]
Thread 3 "reactor_73" hit Breakpoint 1, bdev_aio_readv (fdisk=0xe51630, ch=0x7fffe8092100,
    aio_task=0x201008088178, iov=0x2010b9e97520, iovcnt=6, nbytes=24576, offset=36864)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:02:13.232208] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 6 iovs size 24576 to off: 0x9000, data buffer size 4096

Thread 3 "reactor_73" hit Breakpoint 1, bdev_aio_readv (fdisk=0xe51630, ch=0x7fffe8092100,
    aio_task=0x201008089678, iov=0x2010b9e97db8, iovcnt=14, nbytes=61440, offset=69632)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:02:14.716721] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 14 iovs size 61440 to off: 0x11000, data buffer size 4096

Thread 3 "reactor_73" hit Breakpoint 1, bdev_aio_readv (fdisk=0xe51630, ch=0x7fffe8092100,
    aio_task=0x201008089bb8, iov=0x2010b9e98650, iovcnt=29, nbytes=122880, offset=135168)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:03:40.116388] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 29 iovs size 122880 to off: 0x21000, data buffer size 4096

Thread 3 "reactor_73" hit Breakpoint 1, bdev_aio_readv (fdisk=0xe51630, ch=0x7fffe8092100,
    aio_task=0x2010080871b8, iov=0x2010b9e98ee8, iovcnt=29, nbytes=139264, offset=266240)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);

**Comment by yewhen** [comment]
It shows that iov->iov_len is always 4096 and it's weird that (iov->iov_len) * iovcnt is not always equal to nbytes

**Comment by changpe1** [comment]
> It shows that iov->iov_len is always 4096 and it's weird that (iov->iov_len) * iovcnt is not always equal to nbytes. 24576 = 4096 * 6; 61440 = 4096 * (14 + 1); 122880 = 4096 * (29 + 1)

what if to set aio device's block size to 4096?

**Comment by yewhen** [comment]
> > It shows that iov->iov_len is always 4096 and it's weird that (iov->iov_len) * iovcnt is not always equal to nbytes. 24576 = 4096 * 6; 61440 = 4096 * (14 + 1); 122880 = 4096 * (29 + 1)
> 
> what if to set aio device's block size to 4096?

manually set fdisk->disk.blocklen to 4096 at create_aio_bdev?

**Comment by yewhen** [comment]
btw, I changed SPDK_BDEV_LARGE_BUF_MAX_SIZE before. 
``
-#define SPDK_BDEV_LARGE_BUF_MAX_SIZE (64 * 1024)
``
``
+#define SPDK_BDEV_LARGE_BUF_MAX_SIZE (1024 * 1024)
``

**Comment by changpe1** [comment]
> > > It shows that iov->iov_len is always 4096 and it's weird that (iov->iov_len) * iovcnt is not always equal to nbytes. 24576 = 4096 * 6; 61440 = 4096 * (14 + 1); 122880 = 4096 * (29 + 1)
> > 
> > 
> > what if to set aio device's block size to 4096?
> 
> manually set fdisk->disk.blocklen to 4096 at create_aio_bdev?

You can use RPC `bdev_aio_create`,  there is a block size parameter to overwrite detected block size.

**Comment by yewhen** [comment]
> > > > It shows that iov->iov_len is always 4096 and it's weird that (iov->iov_len) * iovcnt is not always equal to nbytes. 24576 = 4096 * 6; 61440 = 4096 * (14 + 1); 122880 = 4096 * (29 + 1)
> > > 
> > > 
> > > what if to set aio device's block size to 4096?
> > 
> > 
> > manually set fdisk->disk.blocklen to 4096 at create_aio_bdev?
> 
> You can use RPC `bdev_aio_create`, there is a block size parameter to overwrite detected block size.

`/tmp/spdk/scripts/rpc.py bdev_aio_create /dev/sdb4 core1 4096` like this?

**Comment by yewhen** [comment]
Thread 3 "reactor_73" hit Breakpoint 2, bdev_aio_readv (fdisk=0xe516b0, ch=0x7fffe8065af0,
    aio_task=0x201007fde538, iov=0x2010b9e98650, iovcnt=29, nbytes=122880, offset=135168)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:22:53.741198] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 29 iovs size 122880 to off: 0x21000, data buffer size 8192

Thread 3 "reactor_73" hit Breakpoint 2, bdev_aio_readv (fdisk=0xe516b0, ch=0x7fffe8065af0,
    aio_task=0x201007fde538, iov=0x2010b9e98ee8, iovcnt=29, nbytes=143360, offset=266240)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:23:21.336621] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 29 iovs size 143360 to off: 0x41000, data buffer size 4096

Thread 3 "reactor_73" hit Breakpoint 2, bdev_aio_readv (fdisk=0xe516b0, ch=0x7fffe8065af0,
    aio_task=0x201007fce938, iov=0x2010b9e98650, iovcnt=8, nbytes=114688, offset=409600)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:24:06.037093] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 8 iovs size 114688 to off: 0x64000, data buffer size 8192

Thread 3 "reactor_73" hit Breakpoint 2, bdev_aio_readv (fdisk=0xe516b0, ch=0x7fffe8065af0,
    aio_task=0x201007fe09f8, iov=0x2010b9e98650, iovcnt=2, nbytes=16384, offset=1133571997696)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:24:19.368162] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 2 iovs size 16384 to off: 0x107ee280000, data buffer size 8192

Thread 3 "reactor_73" hit Breakpoint 2, bdev_aio_readv (fdisk=0xe516b0, ch=0x7fffe8065af0,
    aio_task=0x201007fdb0b8, iov=0x2010b9e96c88, iovcnt=2, nbytes=8192, offset=1133572026368)
    at bdev_aio.c:186
186                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) c
Continuing.
[2022-12-02 19:24:25.832678] bdev_aio.c: 186:bdev_aio_readv: *WARNING*: read 2 iovs size 8192 to off: 0x107ee287000, data buffer size 4096

**Comment by changpe1** [comment]
> 

yes, you need to iterate all iov based on iovcnt to get total length.

**Comment by yewhen** [comment]
Am I supposed to iterate all iov inside one `bdev_aio_readv` right?

**Comment by changpe1** [comment]
> Am I supposed to iterate all iov inside one `bdev_aio_readv` right?

yes.

**Comment by yewhen** [comment]
but I need `struct iovec *iovs` inside `struct` spdk_bdev_io` right? How do I access that inside `bdev_aio_readv`?

**Comment by yewhen** [comment]
oh, I can do the check inside `bdev_aio_get_buf_cb` right?

**Comment by yewhen** [comment]
> # Sighting report
> I was trying to use "a hard disk cached by NVME ssd on host" at vm by SPDK vhost application, nvme bdev and aio bdev.
> 
> ## Expected Behavior
> No error should be expected I guess.
> 
> ## Current Behavior
> host-side vhost log: ............ [2022-11-30 17:50:43.013568] vhost_blk.c: 607:virtio_blk_process_request: _WARNING_: Ignore the unmap flag for WRITE ZEROES from 1078181c000, len 200000 [2022-11-30 17:50:43.133567] vhost_blk.c: 607:virtio_blk_process_request: _WARNING_: Ignore the unmap flag for WRITE ZEROES from 10781a1c000, len 200000 [2022-11-30 18:41:37.687260] bdev_aio.c: 362:bdev_aio_io_channel_poll: _ERROR_: failed to complete aio: rc 16384 12288 [2022-11-30 18:41:37.687409] Cache1: read_miss failed with error 1 [2022-11-30 18:42:17.180358] bdev_aio.c: 362:bdev_aio_io_channel_poll: _ERROR_: failed to complete aio: rc 16384 12288 [2022-11-30 18:42:17.180445] Cache1: read_miss failed with error 1
> 
> (12288 was the aio_task->len I added to the SPDK_ERRLOG print to check.)
> 
> vm-side mysql error-log: 2022-11-30T11:42:16.307245Z 0 [Warning] [MY-012638] [InnoDB] Retry attempts for reading partial data failed. 2022-11-30T11:42:16.307266Z 0 [ERROR] [MY-012642] [InnoDB] Tried to read 16384 bytes at offset 19332972544, but was only able to read 0 2022-11-30T11:42:16.307281Z 0 [ERROR] [MY-012592] [InnoDB] Operating system error number 5 in a file operation. 2022-11-30T11:42:16.307298Z 0 [ERROR] [MY-012596] [InnoDB] Error number 5 means 'Input/output error' 2022-11-30T11:42:16.307312Z 0 [ERROR] [MY-012646] [InnoDB] File (unknown): 'read' returned OS error 105. Cannot continue operation 2022-11-30T11:42:16.307322Z 0 [ERROR] [MY-012981] [InnoDB] Cannot continue operation. 2022-11-30T11:42:26.549443Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 10 seconds for 128 pending reads 2022-11-30T11:42:36.653476Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 20 seconds for 128 pending reads 2022-11-30T11:42:46.758310Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 30 seconds for 128 pending reads 2022-11-30T11:42:56.862619Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 40 seconds for 128 pending reads 2022-11-30T11:43:06.966868Z 1 [ERROR] [MY-011970] [InnoDB] Waited for 50 seconds for 128 pending reads
> 
> ## Possible Solution
> ## Steps to Reproduce
> 1./tmp/spdk/build/bin/vhost -S /var/tmp/ -m 2000000000020000000 2./tmp/spdk/scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:d8:00.0 3./tmp/spdk/scripts/rpc.py bdev_split_create -s 61440 Nvme0n1 4 4./tmp/spdk/scripts/rpc.py bdev_aio_create /dev/sdb4 core1 5./tmp/spdk/scripts/rpc.py bdev_ocf_create Cache1 wt Nvme0n1p0 core1 --cache-line-size 4 6./tmp/spdk/scripts/rpc.py vhost_create_blk_controller --cpumask 2000000000000000000 vhostblk0 Cache1 7.virsh start xx_vm and run mysql's tpcc test framework
> 
> ## Context (Environment including OS version, SPDK version, etc.)
> qemu arguments in vm's xml file:
> 
> qemu:commandline <qemu:arg value='-object'/> <qemu:arg value='memory-backend-file,id=mem0,size=64G,mem-path=/dev/hugepages,share=on'/> <qemu:arg value='-numa'/> <qemu:arg value='node,memdev=mem0'/> <qemu:arg value='-chardev'/> <qemu:arg value='socket,id=spdk_vhost_blk0,path=/var/tmp/vhostblk0'/> <qemu:arg value='-device'/> <qemu:arg value='vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=1'/> </qemu:commandline>
> 
> kernel version: 5.10.0 architecture: x86_64 SPDK v22.05

I am verifying right now; but I just noticed one problem: in my error msg, 16384 is events[i].res and 12288 is the aio_task->len; from my understanding, aio_task->len was assigned by `nbytes` in `bdev_aio_readv`. However, in mysqld error.log, it stated `Tried to read 16384 bytes at offset 19332972544, but was only able to read 0`, which means mysqld did ask to read 16384 bytes, but it didn't match aio_task->len(12288), but the data buffer length is correct, 16384. That's so weird... I am so confused..

**Comment by changpe1** [comment]
@yewhen
you can use the following sample code in `bdev_aio_readv` to get the total data buffer length.
int i, total_len;
for (i = 0; i < iovcnt; i++) {
    total_len += iov[i].iov_len;
}

**Comment by yewhen** [comment]
yeah, I am doing it right now~~

**Comment by yewhen** [comment]
> yes, from my understanding, if the total buffer length is also 16384, we should treat it as a normal case, but we still need to dig why data buffer length is greater than the actual read length.

Thread 3 "reactor_73" hit Breakpoint 1, bdev_aio_readv (fdisk=0xe51630, ch=0x7fffe8092100,
    aio_task=0x201009efd8f8, iov=0x2010af2fbc00, iovcnt=2, nbytes=12288, offset=106986078208)
    at bdev_aio.c:192
192                     SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len);
(gdb) p total_data_buf_len
$1 = 16384
(gdb) p nbytes
$2 = 12288
(gdb) p aio_task->len
$3 = 12288

Yeah, the total data buffer size is 16384, but nbytes is 12288 @changpe1

**Comment by changpe1** [comment]
> > yes, from my understanding, if the total buffer length is also 16384, we should treat it as a normal case, but we still need to dig why data buffer length is greater than the actual read length.
> 
> Thread 3 "reactor_73" hit Breakpoint 1, bdev_aio_readv (fdisk=0xe51630, ch=0x7fffe8092100, aio_task=0x201009efd8f8, iov=0x2010af2fbc00, iovcnt=2, nbytes=12288, offset=106986078208) at bdev_aio.c:192 192 SPDK_WARNLOG("read %d iovs size %lu to off: %#lx, data buffer size %lu\n", iovcnt, nbytes, offset, iov->iov_len); (gdb) p total_data_buf_len $1 = 16384 (gdb) p nbytes $2 = 12288 (gdb) p aio_task->len $3 = 12288 (gdb) p iovcnt $4 = 2 (gdb) p iov[0].iov_len $5 = 12288 (gdb) p iov[1].iov_len $6 = 4096 (gdb)
> 
> Yeah, the total data buffer size is 16384, but nbytes is 12288 @changpe1

OK, do you still see this issue after using 4096 as the AIO device's block size?

**Comment by yewhen** [comment]
Let me check it with 4096 then, the above report was generated with 512 blk size.

**Comment by yewhen** [comment]
I found the reason why the ocf allocated larger buffer size than nbytes; we modified the ocf a bit, but it turned out we made a bug. Thanks for your help, Changpeng. It's ok to close this issue I guess. @changpe1
