### ISSUE TITLE
NVMe/TCP target data digest performance degradation

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#2809]
# Sighting report

Significant NVMe/TCP IOPS performance degradation when data digest computation is offloaded to DSA in SPDK 22.09 vs. SPDK 22.05.

## Expected Behavior

There should be no IOPS performance degradation in SPDK 22.09 NVMe/TCP target.

## Current Behavior

The NVMe/TCP target with data digest offloaded to DSA in SPDK 22.09 show a 43% performance degradation at 1 target core vs. SPDK 22.05. At 2,3 and 4 target cores the performance degradation is 25% - 28%. The degradation was only observed when the NVMe/TCP target uses DSA for the data digest. There was no performance degradation observed when using ISA-L to compute the data digest.

## Possible Solution

Did a git bisect and tracked down the root cause to patch https://review.spdk.io/gerrit/c/spdk/spdk/+/13685
The patch introduced a limit to the number of idxd completions that can be processed in a batch. The limit is set to 32 using DESC_PER_BATCH parameter in lib/idxd/idxd.c. A batch size of 32 is too small for a storage system with 16 NVMe SSDs at high QD. In my test I am doing QD=64 per SSD so a total of 1024 I/Os are issued concurrently.
Will experiment with larger batch sizes and determine the optimal batch size.

## Steps to Reproduce

1. Start the NVMe/TCP target. Use 1 Core on a system with 16 or more NVMe SSDs.
2. Configure and export 16 NVM Subsystems
3. On the host system configure fio to use the spdk_bdev ioengine. 1 job per subsystem running 16K Rand Read @ QD=64. 
4. Run fio

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 22.04, Kernel 5.15, SPDK 22.09

**Comment by KariukiJ** [comment]
For 1 CPU Core NVMe/TCP target test, setting the completion batch size to 64 reduces the IOPS degradation from 43% to 27%. Using a batch size of 128 reduces the degradation to 12%. A batch size of 256 shows 3% IOPS degradation.

**Comment by jimharris** [comment]
Hi John,

Thanks for the bisect and further analysis.  How is the degradation on 2, 3, 4 cores affected if you bump to 64 or 128 batch size?

-Jim

**Comment by KariukiJ** [comment]
For batch size of 128, 2 target cores show a 6 % performance degradation. 3 and 4 core numbers show no performance degradation.

**Comment by jimharris** [comment]
[Bug scrub] Short term, we will bump completion count from 32 to 128.  This issue will track that change.  I will file another issue as an enhancement request to more elegantly solve this - Ben's suggestion is to maintain two lists in the idxd driver, such that when the poller runs it will only try to complete any ops that were submitted before the poller started execution.

**Comment by KariukiJ** [comment]
Submitted patch https://review.spdk.io/gerrit/c/spdk/spdk/+/15801 to increase max batch size to 128.

**Comment by KariukiJ** [comment]
Ran performance testing with 4K Rand Read with the target application using 1,4,8, 12 and 16 CPU cores. At 1 core the performance degradation was 14% when IDXD_MAX_COMPLETIONS was set to 128. There was no performance degradation at 4, 8, 12 and 16 cores with a value of 128.
