### ISSUE TITLE
Cannot build SPDK with latest DPDK master

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#281]
## Expected Behavior
Should be able to build SPDK with latest DPDK master from GitHub.

## Current Behavior
SPDK compilation with latest DPDK master from GitHub fails.

## Possible Solution
N/A

## Steps to Reproduce
1. Check out latest DPDK from git 
git clone http://dpdk.org/git/dpdk (commit is e1d26e4 crypto/mrvl: add to meson build)
2. Build DPDK
make config T=x86_64-native-linuxapp-gcc && EXTRA_CFLAGS=-fPIC make -j $(nproc)
Build log attached.
3. Try to build SPDK with that DPDK
(commit is fc0dc65 test/common: Fix flamegraph typo in vm_setup)
export WITH_DPDK_DIR=/home/klateck/work/dpdk/build
./autobuild.sh

Compilation error:

```
memory.c: In function ‘spdk_mem_map_init’:
memory.c:519:30: error: ‘RTE_MAX_MEMSEG’ undeclared (first use in this function)
  for (seg_idx = 0; seg_idx < RTE_MAX_MEMSEG; seg_idx++) {
                              ^
memory.c:519:30: note: each undeclared identifier is reported only once for each function it appears in
memory.c:520:33: error: ‘struct rte_mem_config’ has no member named ‘memseg’
   struct rte_memseg *seg = &mcfg->memseg[seg_idx];
                                 ^
/home/klateck/work/spdk/mk/spdk.common.mk:228: recipe for target 'memory.o' failed
make[2]: *** [memory.o] Error 1
make[2]: *** Waiting for unfinished jobs....
vtophys.c: In function ‘vtophys_get_paddr_memseg’:
vtophys.c:223:30: error: ‘RTE_MAX_MEMSEG’ undeclared (first use in this function)
  for (seg_idx = 0; seg_idx < RTE_MAX_MEMSEG; seg_idx++) {
                              ^
vtophys.c:223:30: note: each undeclared identifier is reported only once for each function it appears in
vtophys.c:224:14: error: ‘struct rte_mem_config’ has no member named ‘memseg’
   seg = &mcfg->memseg[seg_idx];
              ^
  CC lib/vhost/vhost_rpc.o
/home/klateck/work/spdk/mk/spdk.common.mk:228: recipe for target 'vtophys.o' failed
make[2]: *** [vtophys.o] Error 1
```

## Context (Environment including OS version, SPDK version, etc.)
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

[spdk_autobuild.log](https://github.com/spdk/spdk/files/1938362/spdk_autobuild.log)
[dpdk_make.log](https://github.com/spdk/spdk/files/1938363/dpdk_make.log)

**Comment by darsto** [comment]
I've fixed this particular conflict you quoted, but will publish patches not before DPDK 18.05 release,
as some other conflicts may still arise.

**Comment by darsto** [comment]
@dverkamp-intel @karlatec 
ok, published: https://review.gerrithub.io/c/spdk/spdk/+/410540

**Comment by wanqunintel** [comment]
@karlatec , would you verify it and update the result here?

**Comment by darsto** [comment]
DPDK just broke the API, so this doesn't even compile against latest master.
I will revisit this patch after final DPDK 18.05 is released.
