### ISSUE TITLE
Use --lcores to map lcore ids greater than 128

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#2812]
# Sighting report
On a system with more than 128 lcores, the nvmf_target fails to start when configured with a core mask greater than 128.

## Expected Behavior
nvmf_target starts and uses lcores assigned to it, include those with ids greater than 128

## Current Behavior
nvmf_target application fails to start with the following error message
EAL: lcore 169 >= RTE_MAX_LCORE (128)
EAL: lcore 170 >= RTE_MAX_LCORE (128)
EAL: To use high physical core ids, please use --lcores to map them to lcore ids below RTE_MAX_LCORE, e.g. --lcores 0@1,1@2,2@57,3@58,4@113,5@114,6@169,7@170

## Possible Solution
When initializing the application environment layer, use --lcores to map them to lcore ids below RTE_MAX_LCORE, e.g. --lcores 0@1,1@2,2@57,3@58,4@113,5@114,6@169,7@170

## Steps to Reproduce

1. On a system with more than 128 cores, start the nvmf_tgt with a core mask > 128 e.g. build/bin/nvmf_tgt -m 0x100000000000000000000000000000000
2. The result will be an error that looks as follows
build/bin/nvmf_tgt -m 0x100000000000000000000000000000000
[2022-12-02 11:18:22.881444] Starting SPDK v22.05 git sha1 797ff94b2 / DPDK 22.03.0 initialization...
[2022-12-02 11:18:22.881495] [ DPDK EAL parameters: [2022-12-02 11:18:22.881503] nvmf [2022-12-02 11:18:22.881507] --no-shconf [2022-12-02 11:18:22.881514] -c 0x100000000000000000000000000000000 [2022-12-02 11:18:22.881518]
--huge-unlink [2022-12-02 11:18:22.881523] --log-level=lib.eal:6 [2022-12-02 11:18:22.881529] --log-level=lib.cryptodev:5 [2022-12-02 11:18:22.881533] --log-level=user1:6 [2022-12-02 11:18:22.881539] --base-virtaddr=0x200000
000000 [2022-12-02 11:18:22.881543] --match-allocations [2022-12-02 11:18:22.881549] --file-prefix=spdk_pid565057 [2022-12-02 11:18:22.881552] ]
EAL: lcore 128 >= RTE_MAX_LCORE (128)
EAL: To use high physical core ids, please use --lcores to map them to lcore ids below RTE_MAX_LCORE, e.g. --lcores 0@128
EAL: invalid coremask syntax

Usage: nvmf [options]

EAL common options:
  -c COREMASK         Hexadecimal bitmask of cores to run on
  -l CORELIST         List of cores to run on
                      The argument format is <c1>[-c2][,c3[-c4],...]
                      where c1, c2, etc are core indexes between 0 and 128
  --lcores COREMAP    Map lcore set to physical cpu set
                      The argument format is
                            '<lcores[@cpus]>[<,lcores[@cpus]>...]'
                      lcores and cpus list are grouped by '(' and ')'
                      Within the group, '-' is used for range separator,
                      ',' is used for single number separator.
                      '( )' can be omitted for single element group,
                      '@' can be omitted if cpus and lcores have the same value
  -s SERVICE COREMASK Hexadecimal bitmask of cores to be used as service cores
  --main-lcore ID     Core ID that is used as main
  --mbuf-pool-ops-name Pool ops name for mbuf to use
  -n CHANNELS         Number of memory channels
  -m MB               Memory to allocate (see also --socket-mem)
  -r RANKS            Force number of memory ranks (don't detect)
  -b, --block         Add a device to the blocked list.
                      Prevent EAL from using this device. The argument
                      format for PCI devices is <domain:bus:devid.func>.
  -a, --allow         Add a device to the allow list.
                      Only use the specified devices. The argument format
                      for PCI devices is <[domain:]bus:devid.func>.
                      This option can be present several times.
                      [NOTE: allow cannot be used with block option]
  --vdev              Add a virtual device.
                      The argument format is <driver><id>[,key=val,...]
                      (ex: --vdev=net_pcap0,iface=eth2).
  --iova-mode   Set IOVA mode. 'pa' for IOVA_PA
                      'va' for IOVA_VA
  -d LIB.so|DIR       Add a driver or driver directory
                      (can be used multiple times)
  --vmware-tsc-map    Use VMware TSC map instead of native RDTSC
  --proc-type         Type of this process (primary|secondary|auto)
  --syslog            Set syslog facility
  --log-level=<level> Set global log level
  --log-level=<type-match>:<level>
                      Set specific log level
  --log-level=help    Show log types and levels
  --trace=<regex-match>
                      Enable trace based on regular expression trace name.
                      By default, the trace is disabled.
                      User must specify this option to enable trace.
  --trace-dir=<directory path>
                      Specify trace directory for trace output.
                      By default, trace output will created at
                      $HOME directory and parameter must be
                      specified once only.
  --trace-bufsz=<int>
                      Specify maximum size of allocated memory
                      for trace output for each thread. Valid
                      unit can be either 'B|K|M' for 'Bytes',
                      'KBytes' and 'MBytes' respectively.
                      Default is 1MB and parameter must be
                      specified once only.
  --trace-mode=<o[verwrite] | d[iscard]>
                      Specify the mode of update of trace
                      output file. Either update on a file can
                      be wrapped or discarded when file size
                      reaches its maximum limit.
                      Default mode is 'overwrite' and parameter
                      must be specified once only.
  -v                  Display version information on startup
  -h, --help          This help
  --in-memory   Operate entirely in memory. This will
                      disable secondary process support
  --base-virtaddr     Base virtual address
  --telemetry   Enable telemetry support (on by default)
  --no-telemetry   Disable telemetry support
  --force-max-simd-bitwidth Force the max SIMD bitwidth

EAL options for DEBUG use only:
  --huge-unlink[=existing|always|never]
                      When to unlink files in hugetlbfs
                      ('existing' by default, no value means 'always')
  --no-huge           Use malloc instead of hugetlbfs
  --no-pci            Disable PCI
  --no-hpet           Disable HPET
  --no-shconf         No shared config (mmap'd files)

EAL Linux options:
  --socket-mem        Memory to allocate on sockets (comma separated values)
  --socket-limit      Limit memory allocation on sockets (comma separated values)
  --huge-dir          Directory where hugetlbfs is mounted
  --file-prefix       Prefix for hugepage filenames
  --create-uio-dev    Create /dev/uioX (usually done by hotplug)
  --vfio-intr         Interrupt mode for VFIO (legacy|msi|msix)
  --vfio-vf-token     VF token (UUID) shared between SR-IOV PF and VFs
  --legacy-mem        Legacy memory mode (no dynamic allocation, contiguous segments)
  --single-file-segments Put all hugepage memory in single files
  --match-allocations Free hugepages exactly as allocated

EAL: FATAL: Invalid 'command line' arguments.
EAL: Invalid 'command line' arguments.
[2022-12-02 11:18:22.885323] init.c: 611:spdk_env_init: *ERROR*: Failed to initialize DPDK
[2022-12-02 11:18:22.885338] app.c: 361:app_setup_env: *ERROR*: Unable to initialize SPDK env

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 22.04, Kernel 5.15, SPDK 22.05

**Comment by ksztyber** [comment]
[Bug scrub] If someone would like to pick that up - feel free. It can be tested on a system with less than 128 cores by changing `RTE_MAX_LCORE` to a smaller value.

**Comment by m-spiewak** [comment]
For testing purposes, the correct file to adjust RTE_MAX_LCORE is `dpdk/config/x86/meson.build` (for x86 architecture).
Line:
`dpdk_conf.set('RTE_MAX_LCORE', 128)`
