### ISSUE TITLE
Error upon Modifying Environment Variables in Configure

### ISSUE THREAD

**Issue by pTpTk** [spdk/spdk#2813]
# Sighting report

The configure script interprets the environment variables as unrecognized option.

## Current Behavior

I ran 
```
./configure CFLAGS="-fPIC -g -O2" --enable-shared=yes
```
And the output I got was
```
Unrecognized option CFLAGS=-fPIC -g -O2
'configure' configures SPDK to compile on supported platforms.

Usage: ./configure [OPTION]...

Defaults for the options are specified in brackets.

General:
 -h, --help                Display this help and exit
...
```

## Context (Environment including OS version, SPDK version, etc.)

OS: Ubuntu 20.04 LTS
SPDK commit 296bca0

**Comment by peluse** [comment]
I think this is what you're after (env vars go first):

[peluse@fedora spdk]$ CFLAGS="-fPIC -g -O2" ./configure  --without-shared

**Comment by peluse** [comment]
pls confirm and close if that works for you :)

**Comment by pTpTk** [comment]
Yes it works for me. On line 174 autobuild.sh there's a similar command as the one I used. I'm not sure if that's a cause for concern.

**Comment by mikeBashStuff** [comment]
> Yes it works for me. On line 174 autobuild.sh there's a similar command as the one I used. I'm not sure if that's a cause for concern.

The `configure` on that line is not SPDK's, it's isa-l's - and since it's autoconf-driven it does indeed support similar cmdline.
