### ISSUE TITLE
Cannot contact VM-host-SM17

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2816]
```
00:09:22.617  Cannot contact VM-host-SM17: java.lang.InterruptedException
00:16:19.899  Cancelling nested steps due to timeout
00:17:19.900  Body did not finish within grace period; terminating with extreme prejudice
```

Looks like there was some kind of network issue on VM-host-SM17.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/92120/archive/ubuntu20-vg-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_92120.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_92120.html

**Comment by mikeBashStuff** [comment]
The issue with the actual VM host - it's scheduled to be downgraded due to existing instability.

**Comment by tomzawadzki** [comment]
[Bug scrub] The VM-host-SM17 has been disabled from the CI machine pool for the maintenance. Once it's back online the issue will no longer occur.
