### ISSUE TITLE
IOs waiting for a buf from pool can stack

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#2824]
# Sighting report

When the app submits read IO request and doesn't provide a buffer, bdev layer allocated one using small or large memory pool. If there are no buffers in the pool, IO is put to a dedicated queue. When any IO request on the same channel releases a buffer, the first queued IO picks up this buffer and continues execution.

That works fine in most cases, however it may happen that read IO request was submitted when memory pool was empty (IO request goes to a queue) and no more IO requests on the same channel completed, no buffers released and IO hangs in the need_buf_small/large queue.

## Expected Behavior

Read IO request completed

## Current Behavior

Read IO requests are stuck forever

## Possible Solution

First I would like to discuss if that can be a configuration issue. Of course, increasing size of large_buf_pool solves this problem.
If it is a bug then we need some trigger to resubmit IO in need_buf_small/large queues. Since in this particular case no IO complete on the IO channel, there is no event to resubmit queued IOs. Most probably, bdev shared pool contains entries for the queued IOs, we just don't resubmit them.

Solution that I implemented is to register a poller - that is pretty simple and solves the problem, but I have concern regarding possible performance regression.

## Steps to Reproduce

Modify `bdev_verify` test in [test/bdev/blockdev.sh ](https://github.com/spdk/spdk/blob/a64acd100c83c7795b2bdfd8787194aedd3cb212/test/bdev/blockdev.sh#L662) - change IO size to 65536. On my setup this test always hangs

Run `sudo ./test/bdev/blockdev.sh`

## Context (Environment including OS version, SPDK version, etc.)

SPDK a64acd100c

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue seems to be related to the buffers being tied per-core, not per-thread. So the get exhausted when there are more than one spdk_thread submitting I/O per core. @AlekseyMarchuk there is series from @ksztyber that might help with this.

**Comment by AlekseyMarchuk** [comment]
Sorry for long delay, I confirm that this issue is fixed with patches from @ksztyber
