### ISSUE TITLE
[spdk_top] thread and poller run are always shown as busy although there is no IO.

### ISSUE THREAD

**Issue by yumingqiao** [spdk/spdk#2827]
# Sighting report
We want to use spdk_top to understand our performance and we found three issues:
1. The vhost-blk pollers are always shown as busy although there is no IO.
2. The vhost-blk threads are always shown as busy although there is no IO.
3. The CPU usage is always 0% although there is IO.

We use AIO bdev with vhost-blk, the physical disk is nvme. In this reproduce example, the `nvme7n1` is used by `vhostblk6`. We verified there is no IO to the `nvme7n1`. However, in the spdk_top poller tab, every `vhostblk6` poller run is busy. In the thread tab, `vhostblk6` idle[us] is 0 and busy[us] is large.
![image (4)](https://user-images.githubusercontent.com/13025688/207136693-9da1d68a-4604-40d4-9043-29d8d74a20df.png)
![image (5)](https://user-images.githubusercontent.com/13025688/207136690-87f6de8a-776a-4c88-8350-0d3c16ed8b1b.png)
![image (6)](https://user-images.githubusercontent.com/13025688/207136688-19c5cd14-526c-43d1-84c5-3083e8f09a52.png)
![image (7)](https://user-images.githubusercontent.com/13025688/207136685-eddb1d26-7527-4266-9a83-f44e22a87331.png)

To compare. we issue some IO to the `nvme7n1` and see that the `vhostblk6` poller run is decreased significantly. We assume this is because each run needs to do actual IO, and therefore is busy.
![image (8)](https://user-images.githubusercontent.com/13025688/207138695-a1c416c8-b1ef-45d5-8864-24d1d05aad89.png)
![image (9)](https://user-images.githubusercontent.com/13025688/207138693-688d5cec-5532-4f6b-9c03-c2abda7c76aa.png)
![image (10)](https://user-images.githubusercontent.com/13025688/207138692-81981b29-8be5-4bba-a531-d7de7aaeada6.png)
![image (11)](https://user-images.githubusercontent.com/13025688/207138690-6a01ee70-c586-442c-aacb-ef2a8f2823c8.png)

In both cases, the `CPU %` in both threads and cores tab is 0.

## Expected Behavior

Where there is no IO, the poller run should be idle.
Where there is no IO, the thread should be idle.
Where there is IO, CPU percentage should reflect actual usage.

## Current Behavior

When there is no IO, the poller and thread still show as busy. The CPU percentage is always shown as 0%.

## Steps to Reproduce

See the summary above.

## Context (Environment including OS version, SPDK version, etc.)
OS: Ubuntu 18.04.6
Kernel: 5.4.0-1094-azure
SPDK: 22.01

**Comment by jimharris** [comment]
Hi @yumingqiao,

This has been fixed in commit 3ed4c29.

-Jim

**Comment by yumingqiao** [comment]
Hey @jimharris , I tried the version with the fix. However, the `CPU percentage` and `Idle[us]` seems to be reported incorrectly.

Initially, there is no IO, but top and spdk_top correctly reflect the idle.
![image (12)](https://user-images.githubusercontent.com/13025688/207172258-2a9e7e7d-56e7-4a7a-ae11-2358407316b9.png)
We start doing IO in one thread. We see `top` reports cpu 62 idle, but spdk_top shows 99% busy.
![image (13)](https://user-images.githubusercontent.com/13025688/207172252-03314e8b-c0b3-4c34-9d25-7d4eabef97e6.png)
We start another IO in another thread that are backed by the same core. We see `top` cpu idle decreased from 62 to 44.3, however, the spdk_top doesn't change.
![image (14)](https://user-images.githubusercontent.com/13025688/207172245-b8d1a2a3-6d04-4119-ac6d-ad8c8a48c9a1.png)

From this experiment, I suspect the `CPU %` and busy[us] are not correctly counted. In addition, what can cause SPDK to make the CPU idle?

**Comment by yumingqiao** [comment]
Hi @jimharris , is there any update for this?

**Comment by jimharris** [comment]
> Hi @jimharris , is there any update for this?

blk_mq_get_tag will go through io_schedule path when there are no tags available.  But nvme suds should have 1023 tags available per cpu by default.  What does /sys/block/nvmeXnY/mq/nr_tags look like for the SSDs in your environment?  And does the idle % go away if you reduce the queue depth in your fio workload?

**Comment by jimharris** [comment]
Hi @yumingqiao, the original issue filed has been resolved so closing this issue.

Follow-up problem discussed here regarding kernel idle time reported is being tracked in issue #2868.
