### ISSUE TITLE
nvmf_tgt core dump with HDGST and DDGST enabled with DSA

### ISSUE THREAD

**Issue by tsrjzq** [spdk/spdk#2828]
# Sighting report
When using SPDK as nvmeoF target, and enable HDGST and DDGST with DSA, I ran fio benchmark, after several minutes, the nvmf_tgt core dump.

I'm testing SPDK as NVMeoF target and initiator on two SPR servers. The server side use nvmf_tgt as target, and client side use spdk as initiator. I use DSA and enable HDGST and DDGST. Then use fio to run read/write IO workload. But after several minutes, the nvmf_tgt crashed.

My environment is as below:

CPU: Intel Xeon 8480+
Memory: 16GB x16
NVMe SSD: Intel P4510 2TB x4
NIC: MLNX ConnectX-6 Dx 200GbE
OS: Rocky Linux 8.7
Kernel: 5.15.0-spr.bkc.pc.5.3.0.x86_64
SPDK: 22.09

Below is my spdk json file for target side, bdev and fio configuration file for client side, and core dump for target.

Thanks.
[spdk_with_dsa.config.txt](https://github.com/spdk/spdk/files/10216688/spdk_with_dsa.config.txt)
[bdev.conf.txt](https://github.com/spdk/spdk/files/10216691/bdev.conf.txt)
[fio.conf.txt](https://github.com/spdk/spdk/files/10216692/fio.conf.txt)

[core.reactor_0.0.52783fd981d54340ad6b9cae6c9eac3a.29637.1670913873000000.zip](https://github.com/spdk/spdk/files/10216705/core.reactor_0.0.52783fd981d54340ad6b9cae6c9eac3a.29637.1670913873000000.zip)

**Comment by Comphix** [comment]
Mengjin will take a look.

**Comment by tsrjzq** [comment]
After applying patch https://review.spdk.io/gerrit/c/spdk/spdk/+/15992, the issue fixed.

**Comment by Comphix** [comment]
P

**Comment by changpe1** [comment]
patch has been merged, closing this issue now.
