### ISSUE TITLE
Build warnings with GCC 12.2.1

### ISSUE THREAD

**Issue by skamuda** [spdk/spdk#2829]
# Sighting report

Warnings are raised during build with gcc 12.2. Build fails when WERROR enabled.
`gcc (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2)`

## Expected Behavior

No warnings.

## Current Behavior

Two warning are raised:

1. **ioat.c**

```
In file included from ioat.c:14:
/home/skamuda/git/spdk/include/spdk/log.h: In function ‘ioat_enum_cb’:
/home/skamuda/git/spdk/include/spdk/log.h:113:9: warning: ‘status’ may be used uninitialized [-Wmaybe-uninitialized]
  113 |         spdk_log(SPDK_LOG_ERROR, __FILE__, __LINE__, __func__, __VA_ARGS__)
      |         ^~~~~~~~
ioat.c:360:18: note: ‘status’ was declared here
  360 |         uint64_t status;
      |                  ^~~~~~
```
2. **ftl_nv_cache.c:**
```
ftl_nv_cache.c: In function ‘ftl_nv_cache_load_state’:
ftl_nv_cache.c:1584:59: warning: array subscript 0 is outside array bounds of ‘struct ftl_nv_cache[0]’ [-Warray-bounds]
 1584 |                       nv_cache->chunk_full_count, nv_cache->chunk_free_count);
      |                                                           ^~
utils/ftl_log.h:15:92: note: in definition of macro ‘FTL_LOG_COMMON’
   15 |                 spdk_log(SPDK_LOG_##type, __FILE__, __LINE__, __func__, "[FTL] "format, ## __VA_ARGS__); \
      |                                                                                            ^~~~~~~~~~~
ftl_nv_cache.c:1583:9: note: in expansion of macro ‘FTL_NOTICELOG’
 1583 |         FTL_NOTICELOG(dev, "FTL NV Cache: full chunks = %lu, empty chunks = %lu\n",
      |         ^~~~~~~~~~~~~
ftl_nv_cache.c:1584:31: warning: array subscript 0 is outside array bounds of ‘struct ftl_nv_cache[0]’ [-Warray-bounds]
 1584 |                       nv_cache->chunk_full_count, nv_cache->chunk_free_count);
      |                               ^~
utils/ftl_log.h:15:92: note: in definition of macro ‘FTL_LOG_COMMON’
   15 |                 spdk_log(SPDK_LOG_##type, __FILE__, __LINE__, __func__, "[FTL] "format, ## __VA_ARGS__); \
      |                                                                                            ^~~~~~~~~~~
ftl_nv_cache.c:1583:9: note: in expansion of macro ‘FTL_NOTICELOG’
 1583 |         FTL_NOTICELOG(dev, "FTL NV Cache: full chunks = %lu, empty chunks = %lu\n",
      |         ^~~~~~~~~~~~~
```

## Possible Solution

Address warnings.

## Steps to Reproduce

```
make clean 
make CONFIG_DEBUG=n
```

## Context (Environment including OS version, SPDK version, etc.)

OS: Fedora Linux 36 (Workstation Edition)
SPDK: latest master branch (git sha: 7019dbbdbab32e0a7a98151ed63feb3d4145e470)

C compiler for the host machine: cc (gcc 12.2.1 "cc (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2)")
C linker for the host machine: cc ld.bfd 2.37-36
Host machine cpu family: x86_64
Host machine cpu: x86_64

**Comment by wanghailiangx** [comment]
Could you try `make CONFIG_DEBUG=n -j` ?

**Comment by tomzawadzki** [comment]
Hi @skamuda, thank you for the report.
I was able to reproduce what you've observed on latest SPDK (33833272) using gcc 12.2.1. Steps were (please disregard DPDK commit, its due to my F37):
```
git -C ./dpdk reset --hard fe2c18a0a8b22703dec3add385a371ad819d7872
./configure --enable-werror
make -j
```
To get to FTL one, ioat needed to be fixed.

**Comment by sberbz** [comment]
Hi
Here is a link to patch series with fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/16340

I added pragma min-pagesize=0 to when compiling with gcc-12 according to gcc bug report: https://gcc.gnu.org/bugzilla//show_bug.cgi?id=105523

**Comment by jimharris** [comment]
Hi @sberbz,

I took a few minutes to debug this more on my end.  I think I figured out how gcc-12 came to this conclusion on the FTL warning - it's actually pretty clever.  I think https://review.spdk.io/gerrit/c/spdk/spdk/+/16342 also fixes the problem, but in a way that doesn't require the pragma.  Can you confirm?

-Jim

**Comment by sberbz** [comment]
I confirm, no warning now.
