### ISSUE TITLE
incorrect test return code of io_submit

### ISSUE THREAD

**Issue by jumpapex** [spdk/spdk#283]
Dear team,

in lib/bdev/aio/bdev_aio.c bdev_aio_writev

	rc = io_submit(aio_ch->io_ctx, 1, &iocb);
	if (rc < 0) {
		if (rc == EAGAIN) {
			spdk_bdev_io_complete(spdk_bdev_io_from_ctx(aio_task), SPDK_BDEV_IO_STATUS_NOMEM);
		} else {
			spdk_bdev_io_complete(spdk_bdev_io_from_ctx(aio_task), SPDK_BDEV_IO_STATUS_FAILED);
		}
		SPDK_ERRLOG("%s: io_submit returned %d\n", __func__, rc);
		return -1;
	}

io_submit already return negative errno, so rc should check with -EAGAIN

Regards!

jumpapex

**Comment by dverkamp-intel** [comment]
This has been fixed in commit 55eb9617cfe2e4506f2c47c6cbea9ccbe2f7e7ac.
