### ISSUE TITLE
Lvol bdevs not starting after spdk application crash

### ISSUE THREAD

**Issue by arutk** [spdk/spdk#2830]
# Sighting report
Lvol bdevs sometimes fail to load after killing spdk application.

## Expected Behavior
Once created, lvols should always load and export lvol bdev.

## Current Behavior
LV store always loads correctly, but lvol bdevs are often times missing after load. Please see the script in reproduction steps for detailed info. The flow is:
1. setup lvstore and lvol
2. save json config 
3. run dd for 5 seconds using the config
4. kill -9 dd
5. start spdk_tgt using the config - at this point typically lvol loads correctly
6. stop spdk_tgt
7. repeat steps 3-4
8. start spdk_tgt again using the config - lvol is now gone.

## Possible Solution
No clue. I suspect problem occurs around the moment when new blobstore clusters are allocated

## Steps to Reproduce
1. run scripts/setup.sh to assign a test drive to SPDK - I've been using Optane p5800x, block size 4K, no metadata.
9. run repro.py script from here:
       https://github.com/arutk/spdk/commit/1f50dc89884a126aeb2f7b7fab8d0178934c1d1d
  usage:
       ./repro.py <path_to_spdk_repo> <PCI_address_of_test device>
  for example:
       ./repro.py $PWD 0000:65:00.0
  Expected behavior is to see "PASS". When the problem reproduces you will get "FAIL". Other types of errors are not expected.

## Context (Environment including OS version, SPDK version, etc.)
Reproducible on
 - SPDK 21.03 and 22.09. 
 - Fedora 36
100% reproducibility across multiple runs on one system. Checked once on another system and got fail as well.

**Comment by tomzawadzki** [comment]
Thank you for reporting and providing the reproduction script ! This was very helpful and I can confirm the 100% reproducibility.

I'd tend to agree with your assessment, the issue probably resides with path that handles cluster allocation.
High level steps for repro are 1) create blob 2) allocate cluster 3) cleanly shutdown the blob 4) allocate another cluster. After that the blob itself does not load. If blobstore recovery is forced (ex. `blobcli -R`), then the blob is recovered.

This most likely points to incorrect contents of extent pages causing failure to load the blob. I'll take a more detailed look.

**Comment by tomzawadzki** [comment]
The issue occurs due to not marking blobstore as dirty and mismatch between used_clusters and extent page contents. Right now the blobstore is marked dirty on first persist of metadata of any blob. In the test case you've shown, there is just one blob that has already its extent page allocated, so on the second spdk_dd run no new allocation occur (just updates in place).

A workaround is https://review.spdk.io/gerrit/c/spdk/spdk/+/16179, the final resolution will need to refactor `blob_persist_check_dirty()` out of persist path and use it on extent page update.

**Comment by arutk** [comment]
Thank you @tomzawadzki. I successfully verified the workaround on my side using the reproduction script.
