### ISSUE TITLE
 nvme: fix memleak when submit request failed

### ISSUE THREAD

**Issue by poluo** [spdk/spdk#2832]
# Sighting report

some memory alloc in nvme_allocate_request_user_copy, and submit
through nvme_ctrlr_submit_admin_request, if nvme ctrlr is failed,
submit return -ENXIO, but memory will not be free

## Expected Behavior
free memory properly

## Current Behavior

memory leak

## Possible Solution

From 1d41bbc3561c2198da2c6edc7c92c43be952829c Mon Sep 17 00:00:00 2001
From: Fengnan Chang <changfengnan@bytedance.com>
Date: Fri, 16 Dec 2022 15:23:08 +0800
Subject: [PATCH] nvme: fix memleak when submit request failed

some memory alloc in nvme_allocate_request_user_copy, and submit
through nvme_ctrlr_submit_admin_request, if nvme ctrlr is failed,
submit return -ENXIO, but memory will not be free.

Signed-off-by: Fengnan Chang <changfengnan@bytedance.com>
---
 lib/nvme/nvme_qpair.c | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/lib/nvme/nvme_qpair.c b/lib/nvme/nvme_qpair.c
index 3eb1e805a..b7f93f79e 100644
--- a/lib/nvme/nvme_qpair.c
+++ b/lib/nvme/nvme_qpair.c
@@ -1037,6 +1037,10 @@ nvme_qpair_submit_request(struct spdk_nvme_qpair *qpair, struct nvme_request *re
 		rc = 0;
 	}
 
+	if (rc < 0 && req->user_buffer && req->payload_size) {
+		spdk_free(req->payload.contig_or_cb_arg);
+	}
+
 	return rc;
 }

**Comment by changpe1** [comment]
@poluo please follow https://spdk.io/development/ process to submit your fix patch to gerrit for code review, thanks.

**Comment by poluo** [comment]
> @poluo please follow https://spdk.io/development/ process to submit your fix patch to gerrit for code review, thanks.

ok, I this patch submit to https://review.spdk.io/gerrit/c/spdk/spdk/+/15985

**Comment by changpe1** [comment]
patch has been merged, closing it now.

**Comment by wanghailiangx** [comment]
The above patch has been merged, let me close the issue.
