### ISSUE TITLE
[nvmf_vfio_user_fuzz] runtime error: signed integer overflow

### ISSUE THREAD

**Issue by sberbz** [spdk/spdk#2835]
# CI Intermittent Failure
nvmf_vfio_user_fuzz - runtime error: signed integer overflow: 1029833220 * 4 cannot be represented in type 'int'

`vfio_user.c:5370:97: runtime error: signed integer overflow: 1029833220 * 4 cannot be represented in type 'int'
    #0 0x7fa76d6c46d3 in map_admin_cmd_req /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5370
    #1 0x7fa76d6c5acc in handle_cmd_req /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5490
    #2 0x7fa76d6a376d in consume_admin_cmd /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:2467
    #3 0x7fa76d6a40e2 in consume_cmd /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:2504
    #4 0x7fa76d6a448b in handle_sq_tdbl_write /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:2542
    #5 0x7fa76d6c71b2 in nvmf_vfio_user_sq_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5635
    #6 0x7fa76d6c743c in nvmf_vfio_user_poll_group_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/vfio_user.c:5670
    #7 0x7fa76d65d837 in nvmf_transport_poll_group_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/transport.c:582
    #8 0x7fa76d63582c in nvmf_poll_group_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/nvmf/nvmf.c:71
    #9 0x7fa76ce83cb2 in thread_execute_poller /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:932
    #10 0x7fa76ce85ada in thread_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:1058
    #11 0x7fa76ce85eca in spdk_thread_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:1109
    #12 0x7fa76d1eaf04 in _reactor_run /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:903
    #13 0x7fa76d1eb578 in reactor_run /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:941
    #14 0x7fa76d1ec039 in spdk_reactors_start /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:1053
    #15 0x7fa76d1e07c3 in spdk_app_start /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/app.c:753
    #16 0x4024f6 in main /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/app/nvmf_tgt/nvmf_main.c:47
    #17 0x7fa76c31beaf in __libc_start_call_main (/usr/lib64/libc.so.6+0x3feaf)
    #18 0x7fa76c31bf5f in __libc_start_main_alias_1 (/usr/lib64/libc.so.6+0x3ff5f)
    #19 0x4022a4 in _start (/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/build/bin/nvmf_tgt+0x4022a4)`

https://ci.spdk.io/results/autotest-per-patch/builds/92928/archive/nvmf-tcp-phy-autotest/vfio_user_fuzz_tgt_output.txt

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_92928.html

## Execution failed at

> 
> 00:11:20.330  ************************************
> 00:11:20.330  START TEST nvmf_vfio_user_fuzz
> 00:11:20.330  ************************************
> 00:11:20.330   13:18:36	-- common/autotest_common.sh@1059 -- # xtrace_enable
> 00:11:20.330   13:18:36	-- common/autotest_common.sh@1060 -- # test/nvmf/target/vfio_user_fuzz.sh --transport=tcp
> 00:11:20.330  * Looking for test storage...
> 00:11:20.330  * Found test storage at /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/target
> 00:11:20.330    13:18:36	-- common/autotest_common.sh@1619 -- # xtrace_enable
> 00:11:20.330   13:18:36	-- target/vfio_user_fuzz.sh@10 -- # source /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/common.sh
> 00:11:20.330    13:18:36	-- nvmf/common.sh@6 -- # NVMF_PORT=4420
> 00:11:20.330    13:18:36	-- nvmf/common.sh@7 -- # NVMF_SECOND_PORT=4421
> 00:11:20.330    13:18:36	-- nvmf/common.sh@8 -- # NVMF_THIRD_PORT=4422
> 00:11:20.330    13:18:36	-- nvmf/common.sh@9 -- # NVMF_IP_PREFIX=192.168.100
> 00:11:20.330    13:18:36	-- nvmf/common.sh@10 -- # NVMF_IP_LEAST_ADDR=8
> 00:11:20.330    13:18:36	-- nvmf/common.sh@11 -- # NVMF_TCP_IP_ADDRESS=127.0.0.1
> 00:11:20.330    13:18:36	-- nvmf/common.sh@12 -- # NVMF_TRANSPORT_OPTS=
> 00:11:20.330    13:18:36	-- nvmf/common.sh@13 -- # NVMF_SERIAL=SPDK00000000000001
> 00:11:20.330    13:18:36	-- nvmf/common.sh@14 -- # NVME_CONNECT='nvme connect'
> 00:11:20.330    13:18:36	-- nvmf/common.sh@15 -- # NET_TYPE=phy
> 00:11:20.330    13:18:36	-- nvmf/common.sh@36 -- # source /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/common.sh
> 00:11:20.330     13:18:36	-- scripts/common.sh@375 -- # [[ -e /bin/wpdk_common.sh ]]
> 00:11:20.330    13:18:36	-- nvmf/common.sh@38 -- # : 0
> 00:11:20.330    13:18:36	-- nvmf/common.sh@39 -- # export NVMF_APP_SHM_ID
> 00:11:20.330    13:18:36	-- nvmf/common.sh@40 -- # build_nvmf_app_args
> 00:11:20.330    13:18:36	-- nvmf/common.sh@18 -- # '[' 0 -eq 1 ']'
> 00:11:20.330    13:18:36	-- nvmf/common.sh@22 -- # NVMF_APP+=(-i "$NVMF_APP_SHM_ID" -e 0xFFFF)
> 00:11:20.330    13:18:36	-- nvmf/common.sh@24 -- # '[' -n '' ']'
> 00:11:20.330    13:18:36	-- nvmf/common.sh@26 -- # '[' 0 -eq 1 ']'
> 00:11:20.330    13:18:36	-- nvmf/common.sh@42 -- # have_pci_nics=0
> 00:11:20.330   13:18:36	-- target/vfio_user_fuzz.sh@12 -- # MALLOC_BDEV_SIZE=64
> 00:11:20.330   13:18:36	-- target/vfio_user_fuzz.sh@13 -- # MALLOC_BLOCK_SIZE=512
> 00:11:20.330   13:18:36	-- target/vfio_user_fuzz.sh@15 -- # nqn=nqn.2021-09.io.spdk:cnode0
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@16 -- # traddr=/var/run/vfio-user
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@18 -- # export TEST_TRANSPORT=VFIOUSER
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@18 -- # TEST_TRANSPORT=VFIOUSER
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@20 -- # rm -rf /var/run/vfio-user
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@24 -- # nvmfpid=1885635
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@23 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x1
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@25 -- # echo 'Process pid: 1885635'
> 00:11:20.331  Process pid: 1885635
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@27 -- # trap 'killprocess $nvmfpid; exit 1' SIGINT SIGTERM EXIT
> 00:11:20.331   13:18:36	-- target/vfio_user_fuzz.sh@28 -- # waitforlisten 1885635
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@781 -- # '[' -z 1885635 ']'
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@785 -- # local rpc_addr=/var/tmp/spdk.sock
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@786 -- # local max_retries=100
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@788 -- # echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
> 00:11:20.331  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@790 -- # xtrace_disable
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@19 -- # '[' '' '!=' yes ']'
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
> 00:11:20.331   13:18:36	-- common/autotest_common.sh@24 -- # set +x
> 00:11:21.266   13:18:37	-- common/autotest_common.sh@809 -- # xtrace_enable
> 00:11:21.266   13:18:37	-- common/autotest_common.sh@810 -- # (( i == 0 ))
> 00:11:21.266   13:18:37	-- common/autotest_common.sh@814 -- # return 0
> 00:11:21.266   13:18:37	-- target/vfio_user_fuzz.sh@30 -- # sleep 1
> 00:11:22.200   13:18:38	-- target/vfio_user_fuzz.sh@32 -- # rpc_cmd nvmf_create_transport -t VFIOUSER
> 00:11:22.200   13:18:38	-- common/autotest_common.sh@548 -- # xtrace_disable
> 00:11:22.200   13:18:38	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
> 00:11:22.200   13:18:38	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
> 00:11:22.200   13:18:38	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
> 00:11:22.200   13:18:38	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
> 00:11:22.200   13:18:38	-- common/autotest_common.sh@24 -- # set +x
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@575 -- # xtrace_enable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@576 -- # [[ 0 == 0 ]]
> 00:11:22.201   13:18:38	-- target/vfio_user_fuzz.sh@34 -- # mkdir -p /var/run/vfio-user
> 00:11:22.201   13:18:38	-- target/vfio_user_fuzz.sh@36 -- # rpc_cmd bdev_malloc_create 64 512 -b malloc0
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@548 -- # xtrace_disable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@24 -- # set +x
> 00:11:22.201  malloc0
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@575 -- # xtrace_enable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@576 -- # [[ 0 == 0 ]]
> 00:11:22.201   13:18:38	-- target/vfio_user_fuzz.sh@37 -- # rpc_cmd nvmf_create_subsystem nqn.2021-09.io.spdk:cnode0 -a -s spdk
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@548 -- # xtrace_disable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@24 -- # set +x
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@575 -- # xtrace_enable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@576 -- # [[ 0 == 0 ]]
> 00:11:22.201   13:18:38	-- target/vfio_user_fuzz.sh@38 -- # rpc_cmd nvmf_subsystem_add_ns nqn.2021-09.io.spdk:cnode0 malloc0
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@548 -- # xtrace_disable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@24 -- # set +x
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@575 -- # xtrace_enable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@576 -- # [[ 0 == 0 ]]
> 00:11:22.201   13:18:38	-- target/vfio_user_fuzz.sh@39 -- # rpc_cmd nvmf_subsystem_add_listener nqn.2021-09.io.spdk:cnode0 -t VFIOUSER -a /var/run/vfio-user -s 0
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@548 -- # xtrace_disable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@24 -- # set +x
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@575 -- # xtrace_enable
> 00:11:22.201   13:18:38	-- common/autotest_common.sh@576 -- # [[ 0 == 0 ]]
> 00:11:22.201   13:18:38	-- target/vfio_user_fuzz.sh@41 -- # trid='trtype:VFIOUSER subnqn:nqn.2021-09.io.spdk:cnode0 traddr:/var/run/vfio-user'
> 00:11:22.201   13:18:38	-- target/vfio_user_fuzz.sh@43 -- # /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/app/fuzz/nvme_fuzz/nvme_fuzz -m 0x2 -r /var/tmp/vfio_user_fuzz -t 30 -S 123456 -F 'trtype:VFIOUSER subnqn:nqn.2021-09.io.spdk:cnode0 traddr:/var/run/vfio-user' -N -a
> 00:41:50.008  Cancelling nested steps due to timeout
> 00:41:50.011  Sending interrupt signal to process
> 00:41:59.820  Terminated
> 00:41:59.830  script returned exit code 143
> 
>

**Comment by sberbz** [comment]
Not sure if its possible to overflow signed int outside fuzzing test.

https://review.spdk.io/gerrit/c/spdk/spdk/+/16029

**Comment by changpe1** [comment]
patch has been merged, closing it now.
