### ISSUE TITLE
[vfio-user] initiator errors with 2nd nvmf_tgt having null_bdev from 1st nvmf_tgt via vfiouser

### ISSUE THREAD

**Issue by joshyunho** [spdk/spdk#2836]
# Sighting report

Hi, I'm running two nvme_tgt (spdk v22.01) processes in the same server with vfiouser enabled. The first nvme_tgt has the null-bdev and export it via vfiouser. The second nvme_tgt attaches this exported null-bdev and successfully accesses it. Here on the second nvme_tgt, I created nvmf_subsystem with TCP and exported the device. And the `nvme connect -t tcp` with this second nvme_tgt worked well and FIO ran fine on it. So the 1st nvmf_tgt is a target. And the 2nd nvmf_tgt is like both an initiator and a target. 

Everything worked well when 2nd nvmf_tgt was running as a single thread. (e.g. ./lib/spdk/build/bin/nvmf_tgt -m [1]). However, when 2nd nvmf_tgt runs with more than 1 core (e.g. ./nvmf_tgt -m [1,2]), the `nvme connect -t tcp` produced errors in 2nd nvmf_tgt.

Can you help with this issue? Is only a single thread allowed for vfiouser? No multiple reactor support for vfiouser?

* 2nd nvmf_tgt when `nvme connect -t tcp`
```
[2022-12-21 14:39:51.522941] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 2 return failure
[2022-12-21 14:39:51.524050] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 3 return failure
[2022-12-21 14:40:01.000250] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 2 return failure
[2022-12-21 14:40:01.001825] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 3 return failure
```
If FIO runs on /dev/nvme7n1 that is from 2nd nvme_tgt, both kernel and 2nd_nvme_tgt got errors as follows:

* kernel
```
[Wed Dec 21 14:49:14 2022] nvme_ns_head_make_request: 9346 callbacks suppressed
[Wed Dec 21 14:49:14 2022] block nvme7n1: no usable path - requeuing I/O
[Wed Dec 21 14:49:14 2022] block nvme7n1: no usable path - requeuing I/O
...
[Wed Dec 21 14:49:14 2022] block nvme7n1: no usable path - requeuing I/O
[Wed Dec 21 14:49:14 2022] block nvme7n1: no usable path - requeuing I/O
[Wed Dec 21 14:49:14 2022] block nvme7n1: no usable path - requeuing I/O
[Wed Dec 21 14:49:14 2022] nvme nvme6: creating 8 I/O queues.
[Wed Dec 21 14:49:15 2022] nvme nvme6: nvme_report_ns_ids: Identify Descriptors failed
[Wed Dec 21 14:49:15 2022] nvme nvme6: identifiers changed for nsid 1
[Wed Dec 21 14:49:15 2022] nvme nvme6: creating 8 I/O queues.
[Wed Dec 21 14:49:15 2022] nvme_ns_head_make_request: 1032 callbacks suppressed
[Wed Dec 21 14:49:15 2022] block nvme7n1: no available path - failing I/O
[Wed Dec 21 14:49:15 2022] block nvme7n1: no available path - failing I/O
...
[Wed Dec 21 14:49:15 2022] block nvme7n1: no available path - failing I/O
[Wed Dec 21 14:49:15 2022] buffer_io_error: 7 callbacks suppressed
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] ldm_validate_partition_table(): Disk read failed.
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] Dev nvme7n1: unable to read RDB block 0
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 3, async page read
[Wed Dec 21 14:49:15 2022] Buffer I/O error on dev nvme7n1, logical block 0, async page read
[Wed Dec 21 14:49:15 2022]  nvme7n1: unable to read partition table
[Wed Dec 21 14:49:15 2022] nvme nvme6: creating 8 I/O queues.
[Wed Dec 21 14:49:15 2022] nvme7n1: detected capacity change from 0 to 1099511627776
```
* 2nd nvmf_tgt
```
[2022-12-21 14:51:05.913005] nvme_qpair.c: 274:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:188 nsid:1 lba:26339870 len:1 SGL DATA BLOCK ADDRESS 0x200016114000 len:0x1000 key:0x0
[2022-12-21 14:51:05.913066] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: INTERNAL DEVICE ERROR (00/06) qid:1 cid:188 cdw0:0 sqhd:0094 p:0 m:0 dnr:0
[2022-12-21 14:51:05.913083] nvme_qpair.c: 274:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:20 nsid:1 lba:219852630 len:1 SGL DATA BLOCK ADDRESS 0x200016116000 len:0x1000 key:0x0
[2022-12-21 14:51:05.913093] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: INTERNAL DEVICE ERROR (00/06) qid:1 cid:20 cdw0:0 sqhd:0095 p:0 m:0 dnr:0
[2022-12-21 14:51:05.913112] nvme_qpair.c: 274:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:19 nsid:1 lba:184171043 len:1 SGL DATA BLOCK ADDRESS 0x200016118000 len:0x1000 key:0x0
[2022-12-21 14:51:05.913131] nvme_qpair.c: 457:spdk_nvme_print_completion: *NOTICE*: INTERNAL DEVICE ERROR (00/06) qid:1 cid:19 cdw0:0 sqhd:0096 p:0 m:0 dnr:0
...
[2022-12-21 14:51:06.434889] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 3 return failure
[2022-12-21 14:51:06.435335] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 3 return failure
[2022-12-21 14:51:06.436946] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 3 return failure
[2022-12-21 14:51:06.493111] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 2 return failure
[2022-12-21 14:51:06.503040] vfio_user.c: 172:vfio_user_read: *ERROR*: Command 2 return failure
```

## Expected Behavior

The `nvme connect` should be able to connect with the 2nd nvmf_tgt without any errors.

## Current Behavior

The `nvme connect` failed with the error above when the 2nd nvmf_tgt has more than 1 core assigned.

## Possible Solution

Run the 2nd nvmf_tgt only with a single core.

## Steps to Reproduce

* The first nvmf_tgt
```
./lib/spdk/build/bin/spdk_tgt -m [1] -r /var/tmp2/s1.sock
./lib/spdk/scripts/rpc.py -s /var/tmp2/s1.sock nvmf_create_transport -t VFIOUSER
./lib/spdk/scripts/rpc.py -s /var/tmp2/s1.sock nvmf_create_subsystem -a nqn.2022-12.io.spdk:dnode1 -s SPDK00000000000001 -d SPDK_Controller1
./lib/spdk/scripts/rpc.py -s /var/tmp2/s1.sock bdev_null_create Null0 1048576 4096
./lib/spdk/scripts/rpc.py -s /var/tmp2/s1.sock nvmf_subsystem_add_ns -n 1 nqn.2022-12.io.spdk:dnode1 Null0
./lib/spdk/scripts/rpc.py -s /var/tmp2/s1.sock nvmf_subsystem_add_listener nqn.2022-12.io.spdk:dnode1 -t VFIOUSER -a /var/tmp2 -s 0
```
* The second nvmf_tgt 
```
./lib/spdk/build/bin/nvmf_tgt -m [2,3] -r -s /var/tmp2/s2.sock
./lib/spdk/scripts/rpc.py -s /var/tmp2/s2.sock nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
./lib/spdk/scripts/rpc.py -s /var/tmp2/s2.sock nvmf_create_subsystem nqn.2022-12.io.spdk:dnode2 -a -s SPDK00000000000002 -d SPDK_Controller2
./lib/spdk/scripts/rpc.py -s /var/tmp2/s2.sock bdev_nvme_attach_controller -b NVMe2 -t VFIOUSER -a /var/tmp2 -n nqn.2022-12.io.spdk:dnode1 -s 0
./lib/spdk/scripts/rpc.py -s /var/tmp2/s2.sock nvmf_subsystem_add_ns -n 2 nqn.2022-12.io.spdk:dnode2 NVMe2n1
./lib/spdk/scripts/rpc.py -s /var/tmp2/s2.sock nvmf_subsystem_add_listener nqn.2022-12.io.spdk:dnode2 -t tcp -a 127.0.0.1 -s 4420
```
* nvme_connect with 2nd nvmf_tgt
```
nvme connect -t tcp -n "nqn.2022-12.io.spdk:dnode2" -a 127.0.0.1 -s 4420
```

## Context (Environment including OS version, SPDK version, etc.)

* Ubuntu 20.04.2 LTS (Focal Fossa)
* SPDK v22.01.1 (updated version)

**Comment by changpe1** [comment]
@joshyunho do you have a try with latest SPDK?

**Comment by joshyunho** [comment]
Oh I'm sorry with the typo on spdk version. I used SPDK v22.01.1. Updated the version info.

Do you think this `nvmf_tgt -> vfiouser -> nvmf_tgt -> tcp -> nvme_connect` should work with the multi cores/reactors?

**Comment by joshyunho** [comment]
Thanks @changpe1. I tried `SPDK v23.01-pre` and `DPDK 22.07.0`. Now `nvmf_tgt` seems to work with multiple reactors/cores.

However, I still see `vfio_user_read` error when `nvme connect` and `nvme disconnect`. Do you know why?
* nvme connect to 2nd nvmf_tgt that gets bdev from 1st nvmf_tgt over vfiouser
```
[2022-12-22 10:05:24.435392] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
[2022-12-22 10:05:24.445340] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
[2022-12-22 10:05:24.455329] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
[2022-12-22 10:05:24.465315] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
```
* nvme disconnect from 2nd nvmf_tgt that gets bdev from 1st nvmf_tgt over vfiouser
```
[2022-12-22 10:05:38.475296] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
[2022-12-22 10:05:38.476266] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
[2022-12-22 10:05:38.477247] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
[2022-12-22 10:05:38.478248] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
```

**Comment by changpe1** [comment]
> Thanks @changpe1. I tried `SPDK v23.01-pre` and `DPDK 22.07.0`. Now `nvmf_tgt` seems to work with multiple reactors/cores.
> 
> However, I still see `vfio_user_read` error when `nvme connect` and `nvme disconnect`. Do you know why?
> 
> * nvme connect to 2nd nvmf_tgt that gets bdev from 1st nvmf_tgt over vfiouser
> 
> ```
> [2022-12-22 10:05:24.435392] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
> [2022-12-22 10:05:24.445340] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
> [2022-12-22 10:05:24.455329] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
> [2022-12-22 10:05:24.465315] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 2 return failure
> ```
> 
> * nvme disconnect from 2nd nvmf_tgt that gets bdev from 1st nvmf_tgt over vfiouser
> 
> ```
> [2022-12-22 10:05:38.475296] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
> [2022-12-22 10:05:38.476266] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
> [2022-12-22 10:05:38.477247] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
> [2022-12-22 10:05:38.478248] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 3 return failure
> ```

For the second nvmf_tgt process, you should start it with `-g` and `-s` parameters, because the first nvmf_tgt requires the whole memory layout for zero-copy processing.

**Comment by joshyunho** [comment]
Great. Thanks @changpe1. with `-g` and `-s`, the second nvmf_tgt works well. 

Now I'm testing with the failure case when the first nvmf_tgt is killed and is restarted with the same VFIOUSER address (e.g. `/var/tmp2`). The first nvmf_tgt is restarted with the previous VFIOUSER address. However, the second nvmf_tgt seems to lose all connections to the first nvmf_tgt. When I issued `./rpc.py nvmf_subsystem_remove_ns`, the rpc.py got stuck with this error.
```
[2022-12-22 12:34:16.910737] nvmf_rpc.c:1354:nvmf_rpc_remove_ns_paused: *ERROR*: Unable to remove namespace ID 0
```
Is there a way for the 2nd nvmf_tgt to work again when the 1st nvmf_tgt is restarted? Does it also need the 2nd nvmf_tgt to restart again and attach to the 1st nvmf_tgt?

**Comment by Comphix** [comment]
Just make sure, this nvmf_subsystem_remove_ns is sent to first nvmf_tgt by its own sock file?

**Comment by joshyunho** [comment]
No, `nvmf_subsystem_remove_ns` was sent to the 2nd nvmf_tgt while 1st nvmf_tgt was restarting.

**Comment by changpe1** [comment]
> Great. Thanks @changpe1. with `-g` and `-s`, the second nvmf_tgt works well.
> 
> Now I'm testing with the failure case when the first nvmf_tgt is killed and is restarted with the same VFIOUSER address (e.g. `/var/tmp2`). The first nvmf_tgt is restarted with the previous VFIOUSER address. However, the second nvmf_tgt seems to lose all connections to the first nvmf_tgt. When I issued `./rpc.py nvmf_subsystem_remove_ns`, the rpc.py got stuck with this error.
> 
> ```
> [2022-12-22 12:34:16.910737] nvmf_rpc.c:1354:nvmf_rpc_remove_ns_paused: *ERROR*: Unable to remove namespace ID 0
> ```
> 
> Is there a way for the 2nd nvmf_tgt to work again when the 1st nvmf_tgt is restarted? Does it also need the 2nd nvmf_tgt to restart and re-attach to the 1st nvmf_tgt?

For your use case here, yes, you should restart 2nd nvmf_tgt again here, because 2nd nvmf_tgt <--> 1st nvmf_tgt is running like VM case.

**Comment by joshyunho** [comment]
Thakns @changpe1. Does it mean that the guest VM should also restart when the nvmf_tgt VFIOUSER is restarted? I expected that there should be a way to automatically reconnect to the new 1st nvmf_tgt and restore the target if they use the same VFIOUSER address. Any plan to support this kind of recovery behavior?

**Comment by changpe1** [comment]
> Thakns @changpe1. Does it mean that the guest VM should also restart when the nvmf_tgt VFIOUSER is restarted? I expected that there should be a way to automatically reconnect to the new 1st nvmf_tgt and restore the target if they use the same VFIOUSER address. Any plan to support this kind of recovery behavior?

Currently we don't have a plan to support this feature, because the VFIO-USER client driver for QEMU is still WIP, but I agree this is a nice feature, we will support it in future.

**Comment by joshyunho** [comment]
Thanks for helping this issue to be resolved.
