### ISSUE TITLE
[sma_vfiouser_qemu] vm_kill() fails to rm QEMU's pidfile

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2837]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-per-patch/builds/92468/archive/vfio-user-autotest/build.log

This is a result of a race - since QEMU is capable of unlinking its own pidfile, we are basically racing with it (after we attempt to signal it to terminate) to do it on our own.

Potential fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/16040

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_92468.html

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/16040 has been merged.
