### ISSUE TITLE
incorrect  rpc.py set_trace_flag help information

### ISSUE THREAD

**Issue by jumpapex** [spdk/spdk#284]
Dear team,

./rpc.py set_trace_flag -h
usage: rpc.py set_trace_flag [-h] flag

positional arguments:
  flag        trace mask we want to set. (for example "debug").

the flag should be the module name, such as aio, blob, but not debug

also the ./rpc.py clear_trace_flag -h

Regards!

jumpapex

**Comment by WenqianZong** [comment]
I use command "./rpc.py set_trace_flag -h" and "./rpc.py clear_trace_flag -h" .it reported following infomation:
ositional arguments:
  flag        trace mask we want to clear. **(for example "debug").**

optional arguments:
  -h, --help  show this help message and exit

**Comment by darsto** [comment]
Hi jumpapex,
Thanks for the report. Fixed here -
https://review.gerrithub.io/c/spdk/spdk/+/408945
D.


2018-04-25 10:05 GMT+02:00 WenqianZong <notifications@github.com>:
