### ISSUE TITLE
[qemu]vhost-user-scsi doesn't support reconnection from qemu

### ISSUE THREAD

**Issue by interaustin** [spdk/spdk#2840]
#  vhost-user-scsi doesn't support reconnection from qemu
After setting 'reconnect' parameter for vhost-user-scsi, vm boot failed.

## Expected Behavior
The version of QEMU is 5.2.0，After setting 'reconnect' parameter for vhost-user-scsi, vm boot failed. the vm configuration is as follows:
`  <qemu:commandline>
    <qemu:arg value='-chardev'/>
    <qemu:arg value='socket,id=scsi.1,path=/var/tmp/scsi.1,reconnect=10'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='vhost-user-scsi-pci,chardev=scsi.1,id=scsi.1,bootindex=1'/>
  </qemu:commandline>
`

However the 'reconnect' parameter takes effect when vhost-user-blk is used, and vm boot successfully.

## Current Behavior

VM boot failed, the following error occurs on the VM:
`qemu-kvm: -device vhost-user-scsi-pci,chardev=scsi.1,id=scsi.1,addr=0x10,bootindex=1: Failed to set msg fds.
qemu-kvm: -device vhost-user-scsi-pci,chardev=scsi.1,id=scsi.1,addr=0x10,bootindex=1: vhost-user-scsi: vhost initialization failed: Operation not permitted`

## Possible Solution
Qemu failed at function `tcp_set_msgfds`, the value of s->state is `TCP_CHARDEV_STATE_CONNECTING'` but not `TCP_CHARDEV_STATE_DISCONNECTED`.
I don't know if this is due to the QEMU version.

## Context (Environment including OS version, SPDK version, etc.)

QEMU version: 5.2.0
SPDK version: v20.10

**Comment by interaustin** [comment]
Is there a preliminary conclusion to this question?

**Comment by changpe1** [comment]
> reconnect

I don't see the support of reconnect feature in `vhost-user-scsi` QEMU driver.

**Comment by interaustin** [comment]
Thank you for your answer @changpei1.  I found this patch [vhost-scsi: support live recovery](https://review.spdk.io/gerrit/c/spdk/spdk/+/4092), does qemu support live recovery for vhost-user-scsi?

**Comment by changpe1** [comment]
> Thank you for your answer @changpe1. I found this patch [vhost-scsi: support live recovery](https://review.spdk.io/gerrit/c/spdk/spdk/+/4092), does qemu support live recovery for vhost-user-scsi?

If  QEMU doesn't support reconnect feature, so I guess this patch in SPDK will not work either.

**Comment by wanghailiangx** [comment]
@interaustin Have any questions? If not, please close this question, thanks.

**Comment by interaustin** [comment]
Thank you for your detailed answers.
