### ISSUE TITLE
all metadata will use sgl when ssd sgl is supported

### ISSUE THREAD

**Issue by yuntianDong** [spdk/spdk#2844]
# Sighting report
all metadata will use sgl when ssd sgl is supported even i specified prp payload type

## Expected Behavior
it shall use prp when i specified prp payload type

## Current Behavior
`sgl_supported = (ctrlr->flags & SPDK_NVME_CTRLR_SGL_SUPPORTED) != 0 &&
				!nvme_qpair_is_admin_queue(qpair);`
this func just set sgl_supported=1 when ssd support sgl and the cmd is not admin cmd
which leads to this func always use sgl
`rc = nvme_pcie_qpair_build_metadata(qpair, tr, sgl_supported, dword_aligned);`

```
nvme_pcie_qpair_build_metadata(struct spdk_nvme_qpair *qpair, struct nvme_tracker *tr,
			       bool sgl_supported, bool dword_aligned)
{
	void *md_payload;
	struct nvme_request *req = tr->req;

	if (req->payload.md) {
		md_payload = req->payload.md + req->md_offset;
		if (dword_aligned && ((uintptr_t)md_payload & 3)) {
			SPDK_ERRLOG("virt_addr %p not dword aligned\n", md_payload);
			goto exit;
		}

		if (sgl_supported && dword_aligned) {
			assert(req->cmd.psdt == SPDK_NVME_PSDT_SGL_MPTR_CONTIG);
			req->cmd.psdt = SPDK_NVME_PSDT_SGL_MPTR_SGL;
			tr->meta_sgl.address = nvme_pcie_vtophys(qpair->ctrlr, md_payload, NULL);
			if (tr->meta_sgl.address == SPDK_VTOPHYS_ERROR) {
				goto exit;
			}
			tr->meta_sgl.unkeyed.type = SPDK_NVME_SGL_TYPE_DATA_BLOCK;
			tr->meta_sgl.unkeyed.length = req->md_size;
			tr->meta_sgl.unkeyed.subtype = 0;
			req->cmd.mptr = tr->prp_sgl_bus_addr - sizeof(struct spdk_nvme_sgl_descriptor);
		} else {
			req->cmd.mptr = nvme_pcie_vtophys(qpair->ctrlr, md_payload, NULL);
			if (req->cmd.mptr == SPDK_VTOPHYS_ERROR) {
				goto exit;
			}
		}
	}

	return 0;

exit:
	nvme_pcie_fail_request_bad_vtophys(qpair, tr);
	return -EINVAL;
}
```
add print to show PSDT find it is always 2 when build matadata
```
rc = nvme_pcie_qpair_build_metadata(qpair, tr, sgl_supported, dword_aligned);
if (rc < 0) {
	assert(rc == -EFAULT);
	rc = 0;
	goto exit;
}
// printf("PSDT : 0x%X , SGL_SUPPORTED : %d\r",req->cmd.psdt,sgl_supported);
```

## Possible Solution
PSDT should be 0 when specified using prp type
add a if func to judge which payload type is in used

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
spdk v22.09

**Comment by changpe1** [comment]
@yuntianDong I don't see the issue you mentioned here, can you describe it more clearly?

**Comment by yuntianDong** [comment]
> @yuntianDong I don't see the issue you mentioned here, can you describe it more clearly?

use 4k+8 lbaf and specify prp method in fio_plugin, the PSDT value is 2 when transfer metadata

**Comment by changpe1** [comment]
> > @yuntianDong I don't see the issue you mentioned here, can you describe it more clearly?
> 
> use 4k+8 lbaf and specify prp method in fio_plugin, the PSDT value is 2 when transfer metadata

how do you specify the PRP method in fio_plugin? I don't see related code?

**Comment by yuntianDong** [comment]
> how do you specify the PRP method in fio_plugin? I don't see related code?

set enable_sgl = 0 isn't mean io should use prp ?

**Comment by changpe1** [comment]
> > how do you specify the PRP method in fio_plugin? I don't see related code?
> 
> set enable_sgl = 0 isn't mean io should use prp ?

NO, it doesn't take effect on PSDT field directly.  If your drive requires special action on separate metadata, you may refer to quirk flags in SPDK NVMe driver to add support.

**Comment by yuntianDong** [comment]
all right , thank you
