### ISSUE TITLE
FIO test using bs=4160

### ISSUE THREAD

**Issue by mtnredhed** [spdk/spdk#2848]
spdk 22.05, centos7.2009, fio 3.28 built from source.  
spdk configure cmd was: "./configure --with-fio=/usr/local/src/fio --with-nvme-cuse"

I want to run the fio test using the drive formatted as lbaf 4 (4 KiB + 64 B). I ran setup.sh to pick up the drives into spdk.

Next:
LD_PRELOAD=/usr/local/src/nvme-cli/spdk/build/fio/spdk_nvme fio "wr_qd_256_133120b_1w.ini" --output-format=json+ --output wr_qd_256_133120b_1w_summary.log.
the .ini file had filename=trtype=PCIe traddr=0000.68.00.0 ns=1

If i set bs=4160 in the .ini, fio immediately fails and tells me bs must be multiple of blocksize (which in theory, it is). 

Should I be able to set bs=4160 (or a multiple) or am I missing something?

thanks

**Comment by changpe1** [comment]
@mtnredhed set `bs` to 4160 multiple is correct. You may double check your ini file to see any conflict.

**Comment by wanghailiangx** [comment]
@mtnredhed How about post the whole ini file?

**Comment by mtnredhed** [comment]
cmd
LD_PRELOAD=/usr/local/src/nvme-cli/spdk/build/fio/spdk_nvme fio "wr_qd_256_13312
0b_1w.ini" --output-format=json+ --output wr_qd_256_133120b_1w_summary.log

[global]
name=[deleted]_ver1.csv
ioengine=spdk
log_hist_msec=1000
log_hist_coarseness=0
direct=1
thread=1
buffered=0
allow_mounted_write=1
randrepeat=0
time_based
norandommap
group_reporting
exitall
percentile_list=1.0:25.0:50.0:75.0:90.0:95.0:99.0:99.9:99.99:99.999:99.9999:99.9
9999:99.999999:100.0
cpus_allowed_policy=split
numjobs=1
pi_act=0
pi_chk=GUARD|REFTAG|APPTAG
cpus_allowed=4
size=100%
#bs=133120
bs=4160
iodepth=256
rw=rw
rwmixread=70
runtime=7200
#pwravg=600
ramp_time=300

[wr_qd_256_133120b_1w]
filename=trtype=PCIe traddr=0000.68.00.0 ns=1
write_hist_log=wr_qd_256_133120b_1w

**Comment by changpe1** [comment]
what's the error log in fio plugin?

**Comment by mmkayPL** [comment]
Can you check whether the drive was formatted with metadata in DIX or DIF mode? With SPDK you can run the rpc bdev_get_bdevs and look at the md_interleave value of the NVMe device.

**Comment by mtnredhed** [comment]
It never gets that far.  It fails immediately parsing the .ini file when it hits the bs=4096.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_94267.html
