### ISSUE TITLE
spdk_tgt reactor 0 occupy 100% cpu

### ISSUE THREAD

**Issue by jumpapex** [spdk/spdk#285]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

just run spdk_tgt with no argument, top command show that reactor 0 occupy 100% cpu

## Expected Behavior

it should not occupy 100% cpu

## Current Behavior

reactor 0 occupy 100% cpu

## Possible Solution

Is is by design?

## Steps to Reproduce

1. 
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

ESXi virtual machine ,Centos 7.0 with 8GB memory, 1024 2048KB huge pages
SPDK master branch with commit a3f8876 vhost: add JSON config dump

**Comment by optimistyzy** [comment]
@jumpapex It is the expected behavior of 100% CPU usage, the reactor thread executes the function _spdk_reactor_run, there is a while(1) loop inside it.

**Comment by wanqunintel** [comment]
this should be the polling mode expected behavior as i know
