### ISSUE TITLE
bdev: spdk_bdev_notify_media_management should not call event_fn() with spinlock held

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2851]
# Sighting report

Media management event notifications happen with `bdev->internal.spinlock`. The `event_fn` callback is called on whatever thread happened to call `spdk_bdev_notify_media_management()`.

<details><summary>spdk_bdev_notify_media_management()</summary>

```c
void
spdk_bdev_notify_media_management(struct spdk_bdev *bdev)
{
        struct spdk_bdev_desc *desc;

        spdk_spin_lock(&bdev->internal.spinlock);
        TAILQ_FOREACH(desc, &bdev->internal.open_descs, link) {
                if (!TAILQ_EMPTY(&desc->pending_media_events)) {
                        desc->callback.event_fn(SPDK_BDEV_EVENT_MEDIA_MANAGEMENT, bdev,
                                                desc->callback.ctx);
                }
        }
        spdk_spin_unlock(&bdev->internal.spinlock);
}
```
</details>

This is undesirable for at least two reasons:

1. If `event_fn()` makes a call into the bdev layer (e.g. to close this descriptor, to release a claim, etc.) it will attempt to recursively lock `bdev->internal.spinlock`, resulting in a call to `abort()`. Conversion to some form a recursive lock is not advisable for reasons described in the [SPDK Spinlock Introduction](https://spdk.io/spdk_spinlock/2023/01/04/spdk_lock/) blog post.
2. The `event_fn()` implementation can make no assumptions about which thread it is executing on. If it needs to be on `desc->thread`, it would have to send (or exec) a message.

## Expected Behavior

The `event_fn` implementor should not need to worry about the private implementation details of the bdev layer.

## Current Behavior

If an `event_fn` implementation makes certain calls into the bdev layer, the deadlock detection in`spdk_spin_lock()` will cause the program to abort.

## Possible Solution

Use an approach like is used with `_resize_notify` to perform the media management notification on the proper thread.

## Steps to Reproduce

No tests exist to produce the error.  There seem to be no tests that exercise `spdk_bdev_notify_media_management()`.

## Context (Environment including OS version, SPDK version, etc.)

spdk master at commit ce92d919d7d4494488a92a2626bd1af547d10087.

**Comment by mgerdts** [comment]
I've written a potential fix for this but do not have the time/motivation to write tests right now to get it over the finish line.  The main purpose of this bug report is to not lose sight of a bug that I've spotted by inspection.

https://review.spdk.io/gerrit/c/spdk/spdk/+/16138

**Comment by jimharris** [comment]
> I've written a potential fix for this but do not have the time/motivation to write tests right now to get it over the finish line. The main purpose of this bug report is to not lose sight of a bug that I've spotted by inspection.
> 
> https://review.spdk.io/gerrit/c/spdk/spdk/+/16138

Thanks @mgerdts.  I'm going to make a few comments on the patch, not for you but for whoever ends up picking this up.

We should add thread-checking tests to test/unit/lib/bdev/mt/bdev.c/bdev_ut.c for both this media_management code as well as blockcnt_change.

**Comment by shuhei-matsumoto** [comment]
@mgerdts @jimharris I wrote two patches https://review.spdk.io/gerrit/c/spdk/spdk/+/16577/1 and https://review.spdk.io/gerrit/c/spdk/spdk/+/16578/1, and am writing unit tests. If these are OK for you, I will complete and upload unit tests.

**Comment by tomzawadzki** [comment]
[Bug scrub] Both patches from @shuhei-matsumoto were merged. Thank you !
