### ISSUE TITLE
[nvmf-tcp-uring-vg-autotest] fio_dif_digest test failure

### ISSUE THREAD

**Issue by krish-reddy** [spdk/spdk#2853]
# CI Intermittent Failure

************************************
 START TEST fio_dif_digest
 ************************************

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_94036.html

## Execution failed at

00:16:02.575  ========== Backtrace start: ==========
00:16:02.575  
00:16:02.575  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1290 -> fio_plugin(["/home/vagrant/spdk_repo/spdk/build/fio/spdk_bdev"],["--ioengine=spdk_bdev"],["--spdk_json_conf"],["/dev/fd/62"],["/dev/fd/61"])
00:16:02.575       ...
00:16:02.575     1285				break
00:16:02.575     1286			fi
00:16:02.575     1287		done
00:16:02.575     1288	
00:16:02.576     1289		# Preload the sanitizer library to fio if fio_plugin was compiled with it
00:16:02.576     1290		LD_PRELOAD="$asan_lib $plugin" "$fio_dir"/fio "$@"
00:16:02.576     1291	}
00:16:02.576     1292	
00:16:02.576     1293	function fio_bdev() {
00:16:02.576     1294		fio_plugin "$rootdir/build/fio/spdk_bdev" "$@"
00:16:02.576     1295	}
00:16:02.576       ...
00:16:02.576  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1294 -> fio_bdev(["--ioengine=spdk_bdev"],["--spdk_json_conf"],["/dev/fd/62"],["/dev/fd/61"])
00:16:02.576       ...
00:16:02.576     1289		# Preload the sanitizer library to fio if fio_plugin was compiled with it
00:16:02.576     1290		LD_PRELOAD="$asan_lib $plugin" "$fio_dir"/fio "$@"
00:16:02.576     1291	}
00:16:02.576     1292	
00:16:02.576     1293	function fio_bdev() {
00:16:02.576     1294		fio_plugin "$rootdir/build/fio/spdk_bdev" "$@"
00:16:02.576     1295	}
00:16:02.576     1296	
00:16:02.576     1297	function fio_nvme() {
00:16:02.576     1298		fio_plugin "$rootdir/build/fio/spdk_nvme" "$@"
00:16:02.576     1299	}
00:16:02.576       ...
00:16:02.576  in test/nvmf/target/dif.sh:82 -> fio(["/dev/fd/62"])
00:16:02.576       ...
00:16:02.576     77  			FIO
00:16:02.576     78  		done
00:16:02.576     79  	}
00:16:02.576     80  	
00:16:02.576     81  	fio() {
00:16:02.576  => 82  		fio_bdev --ioengine=spdk_bdev --spdk_json_conf "$@" <(gen_fio_conf)
00:16:02.576     83  	}
00:16:02.576     84  	
00:16:02.576     85  	fio_dif_1() {
00:16:02.576     86  		create_subsystems 0
00:16:02.576     87  		fio <(create_json_sub_conf 0)
00:16:02.576       ...
00:16:02.576  in test/nvmf/target/dif.sh:131 -> fio_dif_digest([])
00:16:02.576       ...
00:16:02.576     126 	
00:16:02.576     127 		NULL_DIF=3 bs=128k,128k,128k numjobs=3 iodepth=3 runtime=10
00:16:02.576     128 		hdgst=true ddgst=true
00:16:02.576     129 	
00:16:02.576     130 		create_subsystems 0
00:16:02.576  => 131 		fio <(create_json_sub_conf 0)
00:16:02.576     132 		destroy_subsystems 0
00:16:02.576     133 	}
00:16:02.576     134 	
00:16:02.576     135 	nvmftestinit
00:16:02.576     136 	NVMF_TRANSPORT_OPTS+=" --dif-insert-or-strip"
00:16:02.576       ...
00:16:02.576  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1060 -> run_test(["fio_dif_digest"],["fio_dif_digest"])
00:16:02.576       ...
00:16:02.576     1055		timing_enter $test_name
00:16:02.576     1056		echo "************************************"
00:16:02.576     1057		echo "START TEST $test_name"
00:16:02.576     1058		echo "************************************"
00:16:02.576     1059		xtrace_restore
00:16:02.576     1060		time "$@"
00:16:02.576     1061		xtrace_disable
00:16:02.576     1062		echo "************************************"
00:16:02.576     1063		echo "END TEST $test_name"
00:16:02.576     1064		echo "************************************"
00:16:02.576     1065		timing_exit $test_name
00:16:02.576       ...
00:16:02.576  in test/nvmf/target/dif.sh:144 -> main(["--transport=tcp"],["--iso"])
00:16:02.576       ...
00:16:02.576     139 	create_transport
00:16:02.576     140 	
00:16:02.576     141 	run_test "fio_dif_1_default" fio_dif_1
00:16:02.576     142 	run_test "fio_dif_1_multi_subsystems" fio_dif_1_multi_subsystems
00:16:02.576     143 	run_test "fio_dif_rand_params" fio_dif_rand_params
00:16:02.576  => 144 	run_test "fio_dif_digest" fio_dif_digest
00:16:02.576     145 	
00:16:02.576     146 	trap - SIGINT SIGTERM EXIT
00:16:02.576     147 	nvmftestfini
00:16:02.576       ...
00:16:02.576  
00:16:02.576  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @krish-reddy. log: https://ci.spdk.io/public_build/autotest-per-patch_94036.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: https://ci.spdk.io/public_build/autotest-per-patch_94191.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mchomnic. log: https://ci.spdk.io/public_build/autotest-per-patch_123210.html
