### ISSUE TITLE
vhost cpu affinity changed automatic

### ISSUE THREAD

**Issue by HeColder** [spdk/spdk#2857]
we want to creat 2 vm by using spdk+ceph, and specifies the core on which the vhost runs

1) use "./build/bin/vhost -S /var/tmp -m 0xfc0000000000" to start vhost on cpu 42-47

2) use 
./scripts/rpc.py bdev_rbd_create -b core1 ceph_pool vm1 512
./scripts/rpc.py bdev_rbd_create -b core2 ceph_pool vm2 512
to create 2 rbd bdev

3) use
./scripts/rpc.py vhost_create_blk_controller --cpumask 0x1c0000000000 vhostblk1 core1
./scripts/rpc.py vhost_create_blk_controller --cpumask 0xe00000000000 vhostblk2 core2
to create vhostblk1 on cpu 42-44 , vhostblk2 on cpu 45-47

4) use
virsh define vm1.xml
virsh define vm2.xml
to create vm1, vm2

in xml, use
<qemu:commandline>
    <qemu:arg value='-chardev'/>
    <qemu:arg value='socket,id=spdk_vhost_blk0,path=/var/tmp/vhostblk1'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='vhost-user-blk-pci,chardev=spdk_vhost_blk0,num-queues=32'/>
</qemu:commandline>
to use vhostblk as blk device

5) use
virsh start vm1
virsh start vm2
to start vm

6) at beginning, the cpu affinity of vhost process is 42, got by "taskset -c -p [vhost-pid]"(this maybe right because the lowest cpu selected to be the main core);
and use "pidstat -p [vhost-pid] -t 2" can see reactor thread run on right cpu, e.g. reactor_42 run on cpu 42,  reactor_43 run on cpu 43, the other 4 is similar;

7) when i do something in vm disk, like scp data to vm disk or run process on vm disk,
the cpu affinity of vhost will changed automatic,
when i use "taskset -c -p [vhost-pid]", the result is 0-47, the whole cpu of node0 (total 96 cpu, 2 numa node),
and thread like reactor_42 will also change to other cpu, keep change dynamic;
spdk_top doesn't seem to recognize this change, it still show core 42-47;

this confused me, who change the cpu affinity of vhost? and why?I want vhost to run on the CPU I specified.

**Comment by changpe1** [comment]
@HeColder I think this may related with your misuse of `taskset`.

**Comment by HeColder** [comment]
> @HeColder I think this may related with your misuse of `taskset`.

eh, i just use taskset to check the affinity, i try use pidstat -p [vhostpid] -t replace taskset command  to check reactor thread's affinity, the reactor thread's affinity also change automatic.
and once i try to use taskset -c 46-47 [vhostpid] to bind core manual, soon the affinity change back to 0-47.

**Comment by HeColder** [comment]
latest news, i reboot host twice, the question seems disappear.
