### ISSUE TITLE
SPDK QoS RPC method can't work if there is no QoS config in the config file 

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#286]
As the title. SPDK QoS RPC method can't work at some situation.

## Steps to Reproduce
1. Configure the iSCSI target config file, don't add QoS config in the config file;
2. start iscsi target with this config file;
3.  run RPC method set_bdev_qos_limit_iops to set the bdev IOPS;
4. run fio job in initiator machine

## Expected Behavior
The IOPS is  expected vale which is set by RPC method.

## Current Behavior
The IOPS is unlimited.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: 
130307862b126743edce192e29f436a69ee2203d

**Comment by liang2yan** [comment]
Just tried the patch. The issue can't be reproduced with this patch.

**Comment by dverkamp-intel** [comment]
Fix has been merged as commit 804ebf9985e93697809c7e09cc732b0bfcf0c19f.
