### ISSUE TITLE
SPDK make report error "unknown value ‘native’ for -march" in Arm(kernel 5.10.112) environment

### ISSUE THREAD

**Issue by wangxf8888** [spdk/spdk#2863]
Kernel info:
5.10.112.aarch64

Error print

[275/275] Linking target lib/librte_vhost.so.22.2
  CC lib/log/log.o
  CC lib/ut_mock/mock.o
  CC lib/log/log_flags.o
  CC lib/log/log_deprecated.o
log.c:1:0: error: unknown value ‘native’ for -march
 /*   SPDX-License-Identifier: BSD-3-Clause
 ^
mock.c:1:0: error: unknown value ‘native’ for -march
 /*   SPDX-License-Identifier: BSD-3-Clause
 ^
make[2]: *** [log.o] Error 1
make[2]: *** Waiting for unfinished jobs....
log_flags.c:1:0: error: unknown value ‘native’ for -march
 /*   SPDX-License-Identifier: BSD-3-Clause
 ^
make[2]: *** [mock.o] Error 1
make[1]: *** [ut_mock] Error 2
make[1]: *** Waiting for unfinished jobs....
log_deprecated.c:1:0: error: unknown value ‘native’ for -march
 /*   SPDX-License-Identifier: BSD-3-Clause
 ^
make[2]: *** [log_flags.o] Error 1
make[2]: *** [log_deprecated.o] Error 1
make[1]: *** [log] Error 2
make: *** [lib] Error 2

It seems the CONFIG_ARCH=native is not supported
![image](https://user-images.githubusercontent.com/59608750/211970052-ca04c46a-d9fb-42cd-82e0-e2510bbf5629.png)

**Comment by changpe1** [comment]
@wangxf8888 can you help debug this issue? we don't have ARM environment to debug this.

**Comment by jimharris** [comment]
I do not see this problem when building SPDK in my ARM-based VM (MacBook Pro).

Please provide more specifics on your environment, SPDK version used, compiler version, details on your ARM environment, etc.
