### ISSUE TITLE
SPDK core sleeps in the kernel with AIO bdev

### ISSUE THREAD

**Issue by xinyangge-db** [spdk/spdk#2868]
# Sighting report

We use SPDK's AIO bdev to expose a vhost-blk to a VM run by QEMU.  We notice that one reserved SPDK core can spend a significant amount of time sleeping in the kernel when one VM is busy doing disk I/O.  This can cause another VM's I/O requests starving.

![image](https://user-images.githubusercontent.com/110936471/212144521-c7519a0a-f1fb-465a-b2f2-cf66522846b1.png)

We profiled the execution and found that the sleep behavior was triggered by `io_submit`/`aio_read`.  Our expected behavior is that it should never sleep in the kernel, and instead, it should immediately return to the user space to keep polling new I/O requests from the VM.

![image](https://user-images.githubusercontent.com/110936471/212144830-fbb961b0-60b7-41fe-b2b9-55d10312af2f.png)

After looking at the aio bdev's implementation, we noticed that `io_submit` is not always done asynchronously.  In fact, it depends on whether the SPDK process is launched in the interrupt mode (which initializes `aio_ch->group_ch->efd`).

![image](https://user-images.githubusercontent.com/110936471/212145238-8b035f90-07ee-449c-9b7d-8e82ec3aba5e.png)

Is it by design that the SPDK core will sleep in the kernel upon `io_submit` (and leave new I/O requests starving)?  If so, would enabling the interrupt mode prevent this from happening?  If so again, how can we enable the interrupt mode when launching `spdk_tgt`?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
@xinyangge-db According to the Linux Asynchronous I/O manual, I think existing implementation in SPDK is correct, by default, SPDK is running in polling mode, so we don't need to set the event file descriptor for each IOs.

**Comment by xinyangge-db** [comment]
Thank you for your reply, @changpe1 .  Can you clarify if it's expected for io_submit to be blocked in the kernel?  Our understanding is that it shouldn't, as otherwise it can't return to the user mode polling future I/O requests from other VMs.

**Comment by changpe1** [comment]
> Thank you for your reply, @changpe1 . Can you clarify if it's expected for io_submit to be blocked in the kernel? Our understanding is that it shouldn't, as otherwise it can't return to the user mode polling future I/O requests from other VMs.

I guess it's related with your IO workloads, the queue depth from VM to backend AIO device should in the same page.

**Comment by xinyangge-db** [comment]
> the queue depth from VM to backend AIO device should in the same page.

Is there a way to check this?  If so, can you point us to the steps?

**Comment by changpe1** [comment]
> > the queue depth from VM to backend AIO device should in the same page.
> 
> Is there a way to check this? If so, can you point us to the steps?

you can check attributes in `/sys/block/bdev_Name/queue/` to get more information about your block device.

**Comment by dong-liuliu** [comment]
@xinyangge-db 
Here interrupt mode should have no relationship with this issue. if intr is enabled, it only tags an eventfd to the iocb.

From libaio， io_submit will always not wait for IO completion, it will directly return after the iocb is submitted in kernel stack.

**Comment by xinyangge-db** [comment]
Thanks, @changpe1 and @dong-liuliu .  If you look at the following profiling, `io_submit` becomes a blocking call as it triggers the rescheduling to the idle process (`swapper/2`).  @dong-liuliu , can you kindly clarify if this is expected or not?  If so, what conditions might lead to such a behavior?

![image](https://user-images.githubusercontent.com/110936471/212378794-0df9404b-aa46-4884-9582-368f53ebc0ac.png)

**Comment by xinyangge-db** [comment]
Merging the discussion from [another thread](https://github.com/spdk/spdk/issues/2827) where @jimharris replied:

> blk_mq_get_tag will go through io_schedule path when there are no tags available. But nvme suds should have 1023 tags available per cpu by default. What does /sys/block/nvmeXnY/mq/nr_tags look like for the SSDs in your environment? And does the idle % go away if you reduce the queue depth in your fio workload?

The number of available tags is much smaller than 1023.  Is this something that can be changed by software or it's fixed in the hardware?  Also, I thought the tags are a NVMe disk concept, and why is it per-CPU?  Given we run SPDK only one 3 reserved cores, can we steal the tags from other CPUs and give them to that 3 cores? cc @shuochen0311 @yumingqiao

```
$ cat /sys/block/nvme1n1/mq/0/nr_tags
127
```

**Comment by jimharris** [comment]
> Merging the discussion from [another thread](https://github.com/spdk/spdk/issues/2827) where @jimharris replied:
> 
> > blk_mq_get_tag will go through io_schedule path when there are no tags available. But nvme suds should have 1023 tags available per cpu by default. What does /sys/block/nvmeXnY/mq/nr_tags look like for the SSDs in your environment? And does the idle % go away if you reduce the queue depth in your fio workload?
> 
> The number of available tags is much smaller than 1023. Is this something that can be changed by software or it's fixed in the hardware? Also, I thought the tags are a NVMe disk concept, and why is it per-CPU? Given we run SPDK only on 3 reserved cores, can we steal the tags from other CPUs and give them to that 3 cores? cc @shuochen0311 @yumingqiao
> 
> ```
> $ cat /sys/block/nvme1n1/mq/0/nr_tags
> 127
> ```

If you reduce your workload to a smaller queue depth than 127, does this stop the sleeping in the aio kernel code path?

**Comment by xinyangge-db** [comment]
> If you reduce your workload to a smaller queue depth than 127, does this stop the sleeping in the aio kernel code path?

@jimharris , yes, it does.  I tried queue depth of 128, and I can see a significant amount of time spending in idle; but with the queue depth of 127, no time is in idle any more.

**Comment by jimharris** [comment]
> > If you reduce your workload to a smaller queue depth than 127, does this stop the sleeping in the aio kernel code path?
> 
> @jimharris , yes, it does. I tried queue depth of 128, and I can see a significant amount of time spending in idle; but with the queue depth of 127, no time is in idle any more.

Thanks @xinyangge-db!  We could teach the aio bdev module how to read nr_tags, and then ensure each spdk_thread does not submit more I/O than that without waiting for some to complete.

But this could have problems if we use static spdk scheduler.  In that case we may have (for example) 4 spdk_threads running on 1 reactor, and be right back to the original problem.

**Comment by xinyangge-db** [comment]
@jimharris is `nr_tags` something that can be increased by software?  Or it's tied to the disk hardware?

**Comment by xinyangge-db** [comment]
@jimharris alternatively, we can make instruct AIO not to wait when running out of tags: https://patchwork.kernel.org/project/linux-block/patch/20170615160002.17233-5-rgoldwyn@suse.de/

**Comment by changpe1** [comment]
> @jimharris alternatively, we can make instruct AIO not to wait when running out of tags: https://patchwork.kernel.org/project/linux-block/patch/20170615160002.17233-5-rgoldwyn@suse.de/

As I said earlier, your VM queue depth should be in the same page with your AIO device, if all the IOs are queued in the SPDK bdev layer, then you will see very high IO WAIT inside the VM, this workaround doesn't help anything.

When you start the QEMU client, there is a parameter `queue-size` can do this, so you can set it based on your hardware's capability to the correct value to eliminate this issue.

**Comment by dong-liuliu** [comment]
Maybe we can also add RWF_NOWAIT into bdev_aio.
I saw fio also has same code for no wait consideration there https://github.com/axboe/fio/blob/master/engines/libaio.c#L188

**Comment by xinyangge-db** [comment]
@changpe1 can you clarify what the same page means?  We have one SPDK core handling IOs from multiple AIO bdevs, and in that case, does the queue depth of all bdevs combined need to be equal or less to `nr_tags`?

**Comment by changpe1** [comment]
> @changpe1 can you clarify what the same page means? We have one SPDK core handling IOs from multiple AIO bdevs, and in that case, does the queue depth of all bdevs combined need to be equal or less to `nr_tags`?

For example, if your VM with the AIO bdev is 1:1 mapping relationship, so queue depth in VM should be same with queue depth of the AIO device in host.

**Comment by xinyangge-db** [comment]
@changpe1 Yes, it's a 1:1 mapping between a VM and an AIO bdev (thought multiple AIO bdevs can be handled by a single host CPU).  I verified /sys/block/XX/queue/nr_requests has the same value on both the host and the guest.  But when multiple VMs making IO requests at the same time, we can still run out of `nr_tags` (of that host CPU), right?

**Comment by changpe1** [comment]
> @changpe1 Yes, it's a 1:1 mapping between a VM and an AIO bdev (thought multiple AIO bdevs can be handled by a single host CPU). I verified /sys/block/XX/queue/nr_requests has the same value on both the host and the guest. But when multiple VMs making IO requests at the same time, we can still run out of `nr_tags` (of that host CPU), right?

It's really up to your configurations. You can see `nr_tags` in your host system, it means that you AIO device can support multiple queues, but vhost framework will only use one thread to doing all the IOs.

For example, `nr_tags` and `nr_reqests` is 1024 in the host system, and only one IO queue is used in VM, the values could be same from VM and host, but if you use 4 IO queues in the VM, then the value in VM could be 256.

**Comment by xinyangge-db** [comment]
@changpe1 Thanks for the elaboration, and it makes a lot of sense.  For AIO bdev, where can we change these parameters (e.g., number of queues, and the depth of each queue) exposed to the VM?

**Comment by xinyangge-db** [comment]
Just saw you posted earlier that it's a parameter to QEMU.  I was thinking whether it was something configurable from the SPDK side.

**Comment by xinyangge-db** [comment]
@dong-liuliu sorry I missed your reply.  If `RWF_NOWAIT` can be added, it could be a principled fix as this is the behavior the aio bdev expects, right?

**Comment by jimharris** [comment]
> @dong-liuliu sorry I missed your reply. If `RWF_NOWAIT` can be added, it could be a principled fix as this is the behavior the aio bdev expects, right?

Yes, I think we can just always set this flag.

Can you try https://review.spdk.io/gerrit/c/spdk/spdk/+/16406?

**Comment by jimharris** [comment]
> > @dong-liuliu sorry I missed your reply. If `RWF_NOWAIT` can be added, it could be a principled fix as this is the behavior the aio bdev expects, right?
> 
> Yes, I think we can just always set this flag.
> 
> Can you try https://review.spdk.io/gerrit/c/spdk/spdk/+/16406?

Please try this patch when you have a chance.

Can you also share the kernel version you are using?  And do you see RWF_NOWAIT in your /usr/include/linux/fs.h?

**Comment by ksztyber** [comment]
[Bug scrub] @xinyangge-db, could you check Jim's patch?

**Comment by tomzawadzki** [comment]
[Bug scrub] @xinyangge-db @jimharris any updates to the comment above ?

**Comment by jimharris** [comment]
> [Bug scrub] @jimharris, please take a look at this one again.

https://review.spdk.io/gerrit/c/spdk/spdk/+/16406 is ready for review.

**Comment by jimharris** [comment]
> > [Bug scrub] @jimharris, please take a look at this one again.
> 
> https://review.spdk.io/gerrit/c/spdk/spdk/+/16406 is ready for review.

Patch merged.
