### ISSUE TITLE
The test result of  vhost-scsi with QoS enabled have more than 5% deviation 

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#287]
As the title, if the QoS IOPS is 5-10%(I just tried) smaller than the unlimited IOPS. The final result has more than 5% deviation.

the unlimited IOPS is:
job0  109k
job1   91.3k
job2  175k
job3 177k
job5 126k
job6  170k

Set the QoS for each bdev. The IOPS is 95% of the unlimited IOPS.
Then run fio job. The result is as below:
job0 58.1k
job1  67.5k
job2  130k
job3  133k
job5   103k
job6    136k

**Comment by dverkamp-intel** [comment]
Can you provide a test script that reproduces the issue?

Also, can you measure the overhead when enabling QoS with a very high limit (e.g. just the overhead of having QoS enabled without actually limiting submission speed)?

**Comment by wanqunintel** [comment]
@liang2yan can you provide the script?

**Comment by liang2yan** [comment]
I have used QoS rpc method to set the bdev an unreachable IOPS. Then run the testing again.
The final result is similar with the result which is got by setting the bdev 95% IOPS.
So I think the QoS overhead have reduced some IOPS.

**Comment by jimharris** [comment]
Hi Liang,

Please add the test script.  It is not clear what kind of bdev is used, what fio workload is being tested and exactly what is meant by "setting the bdev 95% IOPS".

If you run this same fio job without any QoS - do you get exactly the same results each time?

And also, why is there no job4?

-Jim

**Comment by Comphix** [comment]
Back to Daniel's comment. If we set a QoS goal higher the actual IOPS (means QoS disabled), how much overhead we can see? From the above, it seems like around 30% overhead (95% QoS goal of the actual IOPS)? This is only one configured Core for the vhost target?

**Comment by Comphix** [comment]
Also maybe we can also do the same testing in our usage cases like:
1. just BdevPerf to have different backends
2. NVMe-oF target
3. iSCSI target
With different cases, may have a good understanding on where the overhead costs. Thanks.

**Comment by wanqunintel** [comment]
@liang2yan to get the bdevperf result firslty and update

**Comment by liang2yan** [comment]
I have used latest codes to run bdevperf. The bdev.conf is as below:
[Malloc]
  NumberOfLuns 2
  LunSizeInMB 64
[Nvme]
  TransportID "trtype:PCIe traddr:0000:07:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:81:00.0" Nvme1
  TransportID "trtype:PCIe traddr:0000:82:00.0" Nvme2
 HotplugEnable No
[Ioat]
  Disable Yes
[QoS]
  Limit_IOPS Malloc0 200000000
  Limit_IOPS Malloc1 200000000
  Limit_IOPS Nvme0n1 200000000
  Limit_IOPS Nvme1n1 200000000
  Limit_IOPS Nvme2n1 200000000

The result without QoS is as below:
1st running:
 Logical core: 0
 Nvme2n1             :  741816.85 IO/s    2897.72 MB/s
 Nvme0n1             :  451665.38 IO/s    1764.32 MB/s
 Nvme1n1             :  329279.46 IO/s    1286.25 MB/s
 Malloc1             :  979106.07 IO/s    3824.63 MB/s
 Malloc0             :  979105.80 IO/s    3824.63 MB/s
2nd running:
 Logical core: 0
 Nvme0n1             :  450916.09 IO/s    1761.39 MB/s
 Nvme1n1             :  330991.96 IO/s    1292.94 MB/s
 Nvme2n1             :  745311.95 IO/s    2911.37 MB/s
 Malloc1             : 1002092.03 IO/s    3914.42 MB/s
 Malloc0             : 1002092.37 IO/s    3914.42 MB/s
3rd running:
 Nvme0n1             :  452642.00 IO/s    1768.13 MB/s
 Nvme1n1             :  332203.58 IO/s    1297.67 MB/s
 Nvme2n1             :  747815.33 IO/s    2921.15 MB/s
 Malloc1             : 1000811.07 IO/s    3909.42 MB/s
 Malloc0             : 1000810.80 IO/s    3909.42 MB/s

I have set a very large QoS value for each bdev and run testing again.
The result with QoS enabled is as below:
1st running:
 Logical core: 0
 Nvme0n1             :  313110.04 IO/s    1223.09 MB/s
 Nvme1n1             :  328670.75 IO/s    1283.87 MB/s
 Nvme2n1             :  446884.58 IO/s    1745.64 MB/s
 Malloc1             :  465173.80 IO/s    1817.09 MB/s
 Malloc0             :  465173.85 IO/s    1817.09 MB/s
2nd running:
 Logical core: 0
 Nvme0n1             :  312524.67 IO/s    1220.80 MB/s
 Nvme2n1             :  449925.47 IO/s    1757.52 MB/s
 Nvme1n1             :  328298.24 IO/s    1282.42 MB/s
 Malloc1             :  468599.04 IO/s    1830.46 MB/s
 Malloc0             :  468599.04 IO/s    1830.46 MB/s
3rd running:
 Logical core: 0
 Nvme0n1             :  312349.74 IO/s    1220.12 MB/s
 Nvme1n1             :  328919.77 IO/s    1284.84 MB/s
 Nvme2n1             :  448871.65 IO/s    1753.40 MB/s
 Malloc1             :  467446.61 IO/s    1825.96 MB/s
 Malloc0             :  467446.61 IO/s    1825.96 MB/s

From the result, the malloc bdev have more than 50% overhead. the nvme bdev overhead is different. some have little overhead, some have about 30-40% overhead.

**Comment by jimharris** [comment]
Have the NVMe SSDs been preconditioned?  740K IO/s seems very high (Nvme2n1 in 2nd and 3rd run w/o QoS).

Can you try this with only NVMe and then with only Malloc?  I think the QoS overhead affects Malloc more because Malloc is higher performing.

**Comment by Comphix** [comment]
I will have that change and request Liang to test again. Thanks.

**Comment by liang2yan** [comment]
@Comphix . any patch for this issue?

**Comment by Comphix** [comment]
Working on the patch. Thanks for the reminder.

**Comment by Comphix** [comment]
Hi Liang,

Please have a try on below patch to see how much overhead with the change.

https://review.gerrithub.io/#/c/spdk/spdk/+/413028/

Please use the same testing method to get the overhead.

Thanks, Gang

**Comment by liang2yan** [comment]
Since gang's patch already merged, so I used latest codes. The commit is:
40b6f761b2554c12848583e3a686fd705e2e29bf

I have run following command to run bdevperf:
./test/bdev/bdevperf/bdevperf -c bdev.conf -q 128 -s 4096 -w randread -t 600

The bdev.conf is as below:
```
[Malloc]
NumberOfLuns 2
LunSizeInMB 64
[Ioat]
Disable Yes
#[QoS]
#Limit_IOPS Malloc0 200000000
#Limit_IOPS Malloc1 200000000
```

The test result without QoS is as below:
```
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1341264.12 IO/s    5239.31 MB/s
 Malloc0             : 1341264.21 IO/s    5239.31 MB/s
 =====================================================
 Total               : 2682528.33 IO/s   10478.63 MB/s

Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1336189.29 IO/s    5219.49 MB/s
 Malloc0             : 1336189.40 IO/s    5219.49 MB/s
 =====================================================
 Total               : 2672378.69 IO/s   10438.98 MB/s

Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1343268.60 IO/s    5247.14 MB/s
 Malloc0             : 1343268.69 IO/s    5247.14 MB/s
 =====================================================
 Total               : 2686537.29 IO/s   10494.29 MB/s
```

The test result with QoS is as below:
```
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1227320.96 IO/s    4794.22 MB/s
 Malloc0             : 1227320.96 IO/s    4794.22 MB/s
 =====================================================
 Total               : 2454641.92 IO/s    9588.44 MB/s

Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1228347.82 IO/s    4798.23 MB/s
 Malloc0             : 1228347.85 IO/s    4798.23 MB/s
 =====================================================
 Total               : 2456695.68 IO/s    9596.47 MB/s

Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1222907.52 IO/s    4776.98 MB/s
 Malloc0             : 1222907.48 IO/s    4776.98 MB/s
 =====================================================
 Total               : 2445815.00 IO/s    9553.96 MB/s
```

From the result, 1222908 / 1343269 ~= 0.91.  So there are about 10% overhead. Better than before.
I will verify this issue on other machine to get more data.

**Comment by liang2yan** [comment]
I have run same testing in another machine. The result is as below:

Test result without QoS:

```
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 2110450.15 IO/s    8243.95 MB/s
 Malloc0             : 2110450.48 IO/s    8243.95 MB/s
 =====================================================
 Total               : 4220900.63 IO/s   16487.89 MB/s
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 2091396.91 IO/s    8169.52 MB/s
 Malloc0             : 2091397.00 IO/s    8169.52 MB/s
 =====================================================
 Total               : 4182793.91 IO/s   16339.04 MB/s
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 2100352.20 IO/s    8204.50 MB/s
 Malloc0             : 2100352.35 IO/s    8204.50 MB/s
 =====================================================
 Total               : 4200704.55 IO/s   16409.00 MB/s

```

Test result with QoS:

```
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1960316.37 IO/s    7657.49 MB/s
 Malloc0             : 1960316.57 IO/s    7657.49 MB/s
 =====================================================
 Total               : 3920632.95 IO/s   15314.97 MB/s
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1934159.79 IO/s    7555.31 MB/s
 Malloc0             : 1934160.04 IO/s    7555.31 MB/s
 =====================================================
 Total               : 3868319.82 IO/s   15110.62 MB/s
Running I/O for 600 seconds...
 Logical core: 0
 Malloc1             : 1940551.91 IO/s    7580.28 MB/s
 Malloc0             : 1940552.32 IO/s    7580.28 MB/s
 =====================================================
 Total               : 3881104.23 IO/s   15160.56 MB/s

```
From the result, 1934160 / 2091397 ~= 0.91. about 10% overhead. still better than before.

**Comment by jimharris** [comment]
These seems reasonable to me.  Realistically, QoS is not meant to set a maximum of 4M IO/s – it will usually be a much smaller number (10K-100K).

Can we close this issue?

From: "noreply@github.com" <noreply@github.com>
Reply-To: spdk/spdk <reply@reply.github.com>
Date: Thursday, May 31, 2018 at 10:04 PM
To: spdk/spdk <spdk@noreply.github.com>
Cc: James Harris <james.r.harris@intel.com>, Comment <comment@noreply.github.com>
Subject: Re: [spdk/spdk] The test result of vhost-scsi with QoS enabled have more than 5% deviation (#287)


I have run same testing in another machine. The result is as below:

Test result without QoS:

Running I/O for 600 seconds...

 Logical core: 0

 Malloc1             : 2110450.15 IO/s    8243.95 MB/s

 Malloc0             : 2110450.48 IO/s    8243.95 MB/s

 =====================================================

 Total               : 4220900.63 IO/s   16487.89 MB/s

Running I/O for 600 seconds...

 Logical core: 0

 Malloc1             : 2091396.91 IO/s    8169.52 MB/s

 Malloc0             : 2091397.00 IO/s    8169.52 MB/s

 =====================================================

 Total               : 4182793.91 IO/s   16339.04 MB/s

Running I/O for 600 seconds...

 Logical core: 0

 Malloc1             : 2100352.20 IO/s    8204.50 MB/s

 Malloc0             : 2100352.35 IO/s    8204.50 MB/s

 =====================================================

 Total               : 4200704.55 IO/s   16409.00 MB/s



Test result with QoS:

Running I/O for 600 seconds...

 Logical core: 0

 Malloc1             : 1960316.37 IO/s    7657.49 MB/s

 Malloc0             : 1960316.57 IO/s    7657.49 MB/s

 =====================================================

 Total               : 3920632.95 IO/s   15314.97 MB/s

Running I/O for 600 seconds...

 Logical core: 0

 Malloc1             : 1934159.79 IO/s    7555.31 MB/s

 Malloc0             : 1934160.04 IO/s    7555.31 MB/s

 =====================================================

 Total               : 3868319.82 IO/s   15110.62 MB/s

Running I/O for 600 seconds...

 Logical core: 0

 Malloc1             : 1940551.91 IO/s    7580.28 MB/s

 Malloc0             : 1940552.32 IO/s    7580.28 MB/s

 =====================================================

 Total               : 3881104.23 IO/s   15160.56 MB/s



From the result, 1934160 / 2091397 ~= 0.91. about 10% overhead. still better than before.

**Comment by Comphix** [comment]
Thanks Liang on your effort on this issue and we can close it now.

**Comment by liang2yan** [comment]
Patch merged and test result is reasonable, so close this enhancement.
