### ISSUE TITLE
unplug the ssd but copy data to cmb is still working

### ISSUE THREAD

**Issue by haibowu323** [spdk/spdk#2873]
# Sighting report

I called spdk_nvme_ctrlr_map_cmb() and then used rte_memcpy() to copy data to this cmb. When I unplugged the ssd, the rte_memcpy was still working. I read the source code and knew cmb addr is obtained by mmap the ssd resource file like /sys/bus/pci/devices/0000:5e:00.0/resource4_wc. I want to ask whether this is a normal behavior?

## Expected Behavior

rte_memcpy() will crash when unplug the ssd.

## Current Behavior
Nothing happends

## Steps to Reproduce
1. call spdk_nvme_ctrlr_map_cmb() to get cmb addr.
2. call rte_memcpy to copy data to this cmb region
3. unplug the ssd from the server

## Context (Environment including OS version, SPDK version, etc.)

linux kernel version: 5.15.88
spdk version : v22.01

**Comment by changpe1** [comment]
@haibowu323 SPDK can remap controller registers after getting PCI bus errors but not include the CMB area, maybe you can have a try to add it in `nvme_sigbus_fault_sighandler`.

**Comment by haibowu323** [comment]
@changpe1
In nvme_peic.c file `nvme_pcie_ctrlr_construct` calls `spdk_pci_register_error_handler` to register sigbus handler and I deleted this, and adds a mmio read in `_nvme_pcie_event_process` like this
```
union spdk_nvme_cmbsz_register cmbsz; 
int result = nvme_ctrlr_get_cmbsz(ctrlr, &cmbsz);    
printf("get cmbsz result is %d,  size is %" PRId32 "\n", result, cmbsz.bits.sz);
```

Then I ran the hotplug example. I expectd to generate a sigbus when I unplugged the ssd but it didn't.  It just printed this 
`get cmbsz result is -1,  size is 1048575`
and the program continued.

Was there anything wrong with my approach?
Thanks.

**Comment by jimharris** [comment]
> @changpe1 In nvme_peic.c file `nvme_pcie_ctrlr_construct` calls `spdk_pci_register_error_handler` to register sigbus handler and I deleted this, and adds a mmio read in `_nvme_pcie_event_process` like this
> 
> ```
> union spdk_nvme_cmbsz_register cmbsz; 
> int result = nvme_ctrlr_get_cmbsz(ctrlr, &cmbsz);    
> printf("get cmbsz result is %d,  size is %" PRId32 "\n", result, cmbsz.bits.sz);
> ```
> 
> Then I ran the hotplug example. I expectd to generate a sigbus when I unplugged the ssd but it didn't. It just printed this `get cmbsz result is -1, size is 1048575` and the program continued.
> 
> Was there anything wrong with my approach? Thanks.

Hi @haibowu323,

Are you using uio_pci_generic or vfio-pci to bind your SSD to the SPDK driver?

SIGBUS will only happen with uio.  For vfio, address range remains valid (at least for writes) even after hot remove, until open vfio device handles are closed by userspace.

**Comment by haibowu323** [comment]
> > @changpe1 In nvme_peic.c file `nvme_pcie_ctrlr_construct` calls `spdk_pci_register_error_handler` to register sigbus handler and I deleted this, and adds a mmio read in `_nvme_pcie_event_process` like this
> > ```
> > union spdk_nvme_cmbsz_register cmbsz; 
> > int result = nvme_ctrlr_get_cmbsz(ctrlr, &cmbsz);    
> > printf("get cmbsz result is %d,  size is %" PRId32 "\n", result, cmbsz.bits.sz);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I ran the hotplug example. I expectd to generate a sigbus when I unplugged the ssd but it didn't. It just printed this `get cmbsz result is -1, size is 1048575` and the program continued.
> > Was there anything wrong with my approach? Thanks.
> 
> Hi @haibowu323,
> 
> Are you using uio_pci_generic or vfio-pci to bind your SSD to the SPDK driver?
> 
> SIGBUS will only happen with uio. For vfio, address range remains valid (at least for writes) even after hot remove, until open vfio device handles are closed by userspace.


Hi @jimharris 
I have binded the SSD to the SPDK driver using uio_pci_generic. This is the full log:

```
[root@hcd30cn spdk-hcd]# sudo PCI_ALLOWED="0000:5e:00.0" ./scripts/setup.sh
0000:01:00.0 (144d a802): Skipping denied controller at 0000:01:00.0
0000:01:00.0 (144d a802): Active mountpoints on nvme0n1:centos-home,nvme0n1:centos-root,nvme0n1:nvme0n1p1,nvme0n1:nvme0n1p2, so not binding PCI dev
0000:61:00.0 (1ee4 abcd): Skipping denied controller at 0000:61:00.0
0000:87:00.0 (1ee4 abcd): Skipping denied controller at 0000:87:00.0
0000:af:00.0 (8086 2700): Skipping denied controller at 0000:af:00.0
0000:00:04.0 (8086 2021): Skipping denied controller at 0000:00:04.0
0000:00:04.1 (8086 2021): Skipping denied controller at 0000:00:04.1
0000:00:04.2 (8086 2021): Skipping denied controller at 0000:00:04.2
0000:00:04.3 (8086 2021): Skipping denied controller at 0000:00:04.3
0000:00:04.4 (8086 2021): Skipping denied controller at 0000:00:04.4
0000:00:04.5 (8086 2021): Skipping denied controller at 0000:00:04.5
0000:00:04.6 (8086 2021): Skipping denied controller at 0000:00:04.6
0000:00:04.7 (8086 2021): Skipping denied controller at 0000:00:04.7
0000:80:04.0 (8086 2021): Skipping denied controller at 0000:80:04.0
0000:80:04.1 (8086 2021): Skipping denied controller at 0000:80:04.1
0000:80:04.2 (8086 2021): Skipping denied controller at 0000:80:04.2
0000:80:04.3 (8086 2021): Skipping denied controller at 0000:80:04.3
0000:80:04.4 (8086 2021): Skipping denied controller at 0000:80:04.4
0000:80:04.5 (8086 2021): Skipping denied controller at 0000:80:04.5
0000:80:04.6 (8086 2021): Skipping denied controller at 0000:80:04.6
0000:80:04.7 (8086 2021): Skipping denied controller at 0000:80:04.7
0000:5e:00.0 (1ee4 abcd): nvme -> uio_pci_generic
[root@hcd30cn spdk-hcd]#
[root@hcd30cn spdk-hcd]#
[root@hcd30cn spdk-hcd]# ./build/examples/hotplug -t 5
EAL: Detected CPU lcores: 40
EAL: Detected NUMA nodes: 2
EAL: Detected shared linkage of DPDK
EAL: Selected IOVA mode 'PA'
EAL: No free 2048 kB hugepages reported on node 1
EAL: No available 1048576 kB hugepages reported
TELEMETRY: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
EAL: Probe PCI driver: spdk_nvme (1ee4:abcd) device: 0000:5e:00.0 (socket 0)
Attaching to 0000:5e:00.0
Attached to 0000:5e:00.0
Initialization complete. Starting I/O...
PETAIO_SSD_TITANIUM_ (P116W122212-00000098):          0 I/Os completed (+0)

PETAIO_SSD_TITANIUM_ (P116W122212-00000098):        104 I/Os completed (+104)

PETAIO_SSD_TITANIUM_ (P116W122212-00000098):        216 I/Os completed (+112)

get cmbsz result is -1,  size is 1048575
[2023-01-30 21:22:45.981555] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981620] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981635] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981648] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981660] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981684] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981695] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981707] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:45.981720] nvme_ctrlr.c:1052:nvme_ctrlr_fail: *ERROR*: [0000:5e:00.0] in failed state.
Controller removed: PETAIO_SSD_TITANIUM_ (P116W122212-00000098)
[2023-01-30 21:22:46.018331] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:46.018411] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:46.018424] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
[2023-01-30 21:22:46.018436] nvme_pcie_common.c: 763:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
unregister_dev: PETAIO_SSD_TITANIUM_ (P116W122212-00000098)


[root@hcd30cn spdk-hcd]#
```

You said "SIGBUS will only happen with uio. For vfio, address range remains valid (at least for writes) even after hot remove, until open vfio device handles are closed by userspace."  What does "address range" refer to? Do you mean physical address?
Befor I unplugged the ssd , /proc/iomem was
```
b8800000-c5ffffff : PCI Bus 0000:5d
    b8800000-b89fffff : PCI Bus 0000:5e

38c000000000-38ffffffffff : PCI Bus 0000:5d
    38c008000000-38c01fffffff : PCI Bus 0000:5e
        38c008000000-38c008007fff : 0000:5e:00.0
            38c008000000-38c008007fff : nvme
        38c010000000-38c01fffffff : 0000:5e:00.0
            38c010000000-38c01fffffff : nvme
```

Then I binded the ssd to the SPDK driver using uio. /proc/iomem was
```
b8800000-c5ffffff : PCI Bus 0000:5d
    b8800000-b89fffff : PCI Bus 0000:5e

38c000000000-38ffffffffff : PCI Bus 0000:5d
    38c008000000-38c01fffffff : PCI Bus 0000:5e
        38c008000000-38c008007fff : 0000:5e:00.0
        38c010000000-38c01fffffff : 0000:5e:00.0
```

After I unplugged the ssd, /proc/iomem was
```
b8800000-c5ffffff : PCI Bus 0000:5d
    b8800000-b89fffff : PCI Bus 0000:5e

38c000000000-38ffffffffff : PCI Bus 0000:5d
    38c008000000-38c01fffffff : PCI Bus 0000:5e
```

Thanks.

**Comment by jimharris** [comment]
The /proc/iomem looks correct here.

Can you explain more about your test?  You mentioned that you used the hotplug test, but this test does not use CMB.  Your original description mentions using rte_memcpy.  Please attach exactly the code you are testing, or push it as a Gerrit review.  The hotplug test as written detects hot removal events, and stops submitting IO to that device.

Thanks,

Jim

**Comment by jimharris** [comment]
Closing, no response on this issue in almost a year.
