### ISSUE TITLE
No test logs: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2879]
No test logs were generated for these 5 test runs:
https://ci.spdk.io/public_build/autotest-per-patch_96474.html
https://ci.spdk.io/public_build/autotest-per-patch_96475.html
https://ci.spdk.io/public_build/autotest-per-patch_96476.html
https://ci.spdk.io/public_build/autotest-per-patch_96477.html
https://ci.spdk.io/public_build/autotest-per-patch_96463.html

In supplemental logs Java exception can be found:
```
00:04:40.166  [Pipeline] }
00:04:40.169  java.io.FileNotFoundException: /var/jenkins/workspace/autotest-per-patch@3/jbp/jenkins/jjb-config/jobs/autotest-upstream/autotest-per-patch-v23.01.json does not exist.
00:04:40.169  	at org.jenkinsci.plugins.pipeline.utility.steps.json.ReadJSONStepExecution.doRun(ReadJSONStepExecution.java:83)
00:04:40.169  	at org.jenkinsci.plugins.pipeline.utility.steps.AbstractFileOrTextStepExecution.run(AbstractFileOrTextStepExecution.java:29)
00:04:40.169  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
00:04:40.169  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
00:04:40.169  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:04:40.169  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:04:40.169  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:04:40.169  	at java.base/java.lang.Thread.run(Thread.java:829)
00:04:40.187  [Pipeline] // catchError
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_96477.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_96476.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_96474.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_96475.html

**Comment by ksztyber** [comment]
[Bug scrub] No longer occurring, closing.
