### ISSUE TITLE
SPDK iSCSI target crashed while running QoS rpc method to configure bdev QoS

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#288]
## Steps to Reproduce

1. start the iSCSI target with config file like below:
[Global]
ReactorMask 0x3
[iSCSI]
  NodeBase "iqn.2016-06.io.spdk"

  AuthFile /usr/local/etc/spdk/auth.conf

  MinConnectionsPerCore 4
  Timeout 30
  DiscoveryAuthMethod Auto

  DefaultTime2Wait 2
  DefaultTime2Retain 60

  ImmediateData Yes
  ErrorRecoveryLevel 0
[PortalGroup1]
  Portal DA1 192.168.11.11:3260
[InitiatorGroup1]
  InitiatorName ANY
  Netmask 192.168.11.0/24

[Nvme]
  TransportID "trtype:PCIe traddr:0000:84:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:85:00.0" Nvme1
  TransportID "trtype:PCIe traddr:0000:86:00.0" Nvme2
  TransportID "trtype:PCIe traddr:0000:87:00.0" Nvme3
  TransportID "trtype:PCIe traddr:0000:88:00.0" Nvme4
  TransportID "trtype:PCIe traddr:0000:89:00.0" Nvme5

  RetryCount 4
  Timeout 0
  AdminPollRate 100000
  HotplugEnable No
  HotplugPollRate 0

[Malloc]
  NumberOfLuns 3
  LunSizeInMB 128
  BlockSize 4096

[Split]
  Split Malloc0 2
  Split Nvme0n1 2

[TargetNode1]
  TargetName disk1
  TargetAlias "Data Disk1"
  Mapping PortalGroup1 InitiatorGroup1
  AuthMethod Auto
  AuthGroup AuthGroup1
  UseDigest Auto
  LUN0 Malloc0p0
  QueueDepth 128

[TargetNode2]
  TargetName disk2
  TargetAlias "Data Disk2"
  Mapping PortalGroup1 InitiatorGroup1
  AuthMethod Auto
  AuthGroup AuthGroup1
  UseDigest Auto
  LUN0 Malloc1
  QueueDepth 128

[TargetNode3]
  TargetName disk3
  TargetAlias "Data Disk3"
  Mapping PortalGroup1 InitiatorGroup1
  AuthMethod Auto
  AuthGroup AuthGroup1
  UseDigest Auto
  LUN0 Nvme0n1p0
  QueueDepth 128

[TargetNode4]
  TargetName disk4
  TargetAlias "Data Disk4"
  Mapping PortalGroup1 InitiatorGroup1
  AuthMethod Auto
  AuthGroup AuthGroup1
  UseDigest Auto
  LUN0 Nvme1n1
  QueueDepth 128

2.  in initiator machine, connect to the target node;
3.in target machine, run following command:
[root@ scripts]# ./rpc.py set_bdev_qos_limit_iops Nvme1n1 10000
[root@ scripts]# ./rpc.py  set_bdev_qos_limit_iops   Nvme0n1p0 10000
[root@ scripts]# ./rpc.py  set_bdev_qos_limit_iops   Malloc1 10000
[root@  scripts]# ./rpc.py  set_bdev_qos_limit_iops   Malloc0p0  10000
[root@  scripts]# ./rpc.py set_bdev_qos_limit_iops Nvme1n1 0
[root@  scripts]# ./rpc.py  set_bdev_qos_limit_iops   Nvme0n1p0 0
[root@  scripts]# ./rpc.py  set_bdev_qos_limit_iops   Malloc1 0
[root@  scripts]# ./rpc.py  set_bdev_qos_limit_iops   Malloc0p0  0
[root@  scripts]# ./rpc.py set_bdev_qos_limit_iops Nvme1n1 10000
[root@  scripts]# ./rpc.py  set_bdev_qos_limit_iops   Nvme0n1p0 10000
[root@  scripts]# ./rpc.py  set_bdev_qos_limit_iops   Malloc1 10000
[root@  scripts]# ./rpc.py  set_bdev_qos_limit_iops   Malloc0p0  10000

4. run fio job in initiator machine;
[global]
thread=1
rw=randread
runtime=300
ioengine=libaio
direct=1
bs=4096
invalidate=1
iodepth=128
norandommap=1
[job0]
filename=/dev/sdb
[job1]
filename=/dev/sdc
[job2]
filename=/dev/sdd
[job3]
filename=/dev/sde

## Expected Behavior
fio finished successfully
## Current Behavior
iscsi target crashed. the core dump is as below:
Program terminated with signal SIGSEGV, Segmentation fault.
#0  spdk_thread_send_msg (thread=0x0, fn=0x44ebc0 <_spdk_bdev_io_submit>, ctx=0x7f360f0006c0) at io_channel.c:197
197             thread->msg_fn(fn, ctx, thread->thread_ctx);
[Current thread is 1 (Thread 0x7f3616a1b280 (LWP 24175))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.24-10.fc25.x86_64 libuuid-2.28.2-2.fc25.x86_64 numactl-libs-2.0.11-2.fc24.x86_64 openssl-libs-1.0.2m-1.fc25.x86_64
(gdb) bt
#0  spdk_thread_send_msg (thread=0x0, fn=0x44ebc0 <_spdk_bdev_io_submit>, ctx=0x7f360f0006c0) at io_channel.c:197
#1  0x000000000044ed15 in spdk_bdev_io_submit (bdev_io=<optimized out>) at bdev.c:916
#2  0x000000000044eee6 in spdk_bdev_readv_blocks (desc=<optimized out>, ch=0x357d870, iov=0x7f35c95adaa0,
    iovcnt=1, offset_blocks=76675024, num_blocks=8, cb=0x446140 <spdk_bdev_scsi_task_complete_cmd>,
    cb_arg=0x7f35c95ada40) at bdev.c:1532
#3  0x0000000000446901 in spdk_bdev_scsi_read (len=8, lba=76675024, task=0x7f35c95ada40, bdev_ch=0x357d870,
    bdev_desc=0x3575240, bdev=<optimized out>) at scsi_bdev.c:1317
#4  spdk_bdev_scsi_readwrite (task=task@entry=0x7f35c95ada40, lba=<optimized out>, xfer_len=8,
    is_read=<optimized out>) at scsi_bdev.c:1477
#5  0x0000000000446f50 in spdk_bdev_scsi_process_block (task=0x7f35c95ada40) at scsi_bdev.c:1662
#6  spdk_bdev_scsi_execute (task=task@entry=0x7f35c95ada40) at scsi_bdev.c:2029
#7  0x000000000044598f in spdk_scsi_lun_execute_task (lun=0x35751d0, task=0x7f35c95ada40) at lun.c:162
#8  0x0000000000445509 in spdk_scsi_dev_queue_task (dev=<optimized out>, task=<optimized out>) at dev.c:264
#9  0x0000000000435208 in spdk_iscsi_queue_task (task=<optimized out>, conn=<optimized out>, conn=<optimized out>)
    at iscsi.c:2903
#10 0x000000000043966c in spdk_iscsi_op_scsi (pdu=<optimized out>, conn=0x7f36136778e0) at iscsi.c:3127
#11 spdk_iscsi_execute (conn=conn@entry=0x7f36136778e0, pdu=<optimized out>) at iscsi.c:4493
#12 0x00000000004321bf in spdk_iscsi_conn_handle_incoming_pdus (conn=<optimized out>) at conn.c:1143
#13 spdk_iscsi_conn_sock_cb (arg=0x7f36136778e0, group=<optimized out>, sock=<optimized out>) at conn.c:1170
#14 0x000000000042edd4 in spdk_sock_group_impl_poll_count (max_events=32, group=0x2417340, group_impl=0x3599b80)
    at sock.c:296
#15 spdk_sock_group_poll_count (group=0x2417340, max_events=32) at sock.c:321
#16 0x0000000000440368 in spdk_iscsi_poll_group_poll (ctx=0x24172d0) at iscsi_subsystem.c:862
#17 0x000000000045669c in _spdk_reactor_run (arg=0x2415680) at reactor.c:455
#18 0x0000000000456bad in spdk_reactors_start () at reactor.c:624
#19 0x0000000000455c31 in spdk_app_start (opts=opts@entry=0x7ffdd8ded740,
    start_fn=start_fn@entry=0x406080 <spdk_startup>, arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:484
#20 0x0000000000404f19 in main (argc=3, argv=0x7ffdd8ded898) at iscsi_tgt.c:113

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit:
e6acab9930647dc0468fc05ca3bd07fe1aadb43e

**Comment by Comphix** [comment]
Looking at this issue.

**Comment by Comphix** [comment]
Please verify this patch https://review.gerrithub.io/#/c/spdk/spdk/+/409125/ 

Thanks.

**Comment by liang2yan** [comment]
verified with the patch. Issue can't be reproduced.

**Comment by dverkamp-intel** [comment]
The patch above has been merged as commit 2f94b4d4e3607400419068eb74b64221df93ea15 - thanks for the quick turnaround.
