### ISSUE TITLE
[bdev] spdk_bdev_unregister does not call its callback on the same thread its was called on

### ISSUE THREAD

**Issue by plestk** [spdk/spdk#2883]
Consider two threads (1 & 2) and a bdev. This is what I have in 22.05 :

1.  thread 1 opens a bdev descriptor ;
2. `spdk_bdev_unregister` is called on thread 2 ;
3. the bdev internal status is set to `SPDK_BDEV_STATUS_REMOVING` on thread 2 (in `bdev_unregister`) ;
4. `spdk_io_device_unregister` is not called by thread 2 because `bdev_unregister_unsafe` returns `-EBUSY` because of the opened descriptor ;
5. thread 1 closes its descriptor ;
6. `spdk_io_device_unregister` is called on thread 1 as part of `bdev_close` (since the bdev internal state is `SPDK_BDEV_STATUS_REMOVING`) ;
7. the callback argument of `spdk_bdev_unregister` is called on thread 1

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/16554

**Comment by jimharris** [comment]
Patch merged.
