### ISSUE TITLE
aux buf leak in vbdev_crypto.c

### ISSUE THREAD

**Issue by llicety** [spdk/spdk#2886]
# Sighting report

aux buf not put for no spdk_bdev_io_put_aux_buf called in _crypto_operation_complete in write path when rc = -EINVAL

## Expected Behavior

crypto bdev write io aux buf should be put back in _crypto_operation_complete function when rc = -EINVA 

## Current Behavior

now  just use spdk_bdev_io_complete func， aux buf not free

## Possible Solution

add spdk_bdev_io_put_aux_buf in write path when rc = -EINVA. what's more, _crypto_operation function rc should init to zero

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by AlekseyMarchuk** [comment]
Thank you for reporting this issue, I'll provide a fix tomorrow

**Comment by AlekseyMarchuk** [comment]
Fix can be found here: https://review.spdk.io/gerrit/c/spdk/spdk/+/16600
Please note that in SPDK 23.01 vbdev_crypto was redesigned to use accel framework for crypto operations, this also changes RPC configuration. More info can be found here: https://spdk.io/doc/bdev.html#bdev_config_crypto

**Comment by jimharris** [comment]
Patch merged.
