### ISSUE TITLE
how concurrent that an iSCSI target that has two luns 

### ISSUE THREAD

**Issue by happyzyz** [spdk/spdk#2887]
# Sighting report

When I create an iscsi target containing two luns (bdev), these two luns are mapped to two disks. When I use fio to read and write two disks, iscsi target uses a thread (or core) to perform the operation.

具体的操作：
./scripts/rpc.py bdev_malloc_create -b Malloc0 64 512
./scripts/rpc.py bdev_malloc_create -b Malloc1 64 512

./scripts/rpc.py --verbose DEBUG iscsi_create_portal_group 1 172.20.20.156:3261
./scripts/rpc.py --verbose DEBUG iscsi_create_initiator_group 2 ANY 172.20.20.156/24

./scripts/rpc.py --verbose DEBUG iscsi_create_target_node disk1 "Data Disk1" "Malloc0:0 Malloc1:1" 1:2 64 -d

iscsiadm -m discovery -t sendtargets -p 172.20.20.156:3261

iscsiadm -m node --targetname iqn.2016-06.io.spdk:disk1 --portal 172.20.20.156:3261 --login

fio -ioengine=libaio -bs=512B -direct=1 -thread -numjobs=2 -size=64M -rw=write -filename=/dev/sdd -name="BS 512B read test" -iodepth=2
fio -ioengine=libaio -bs=512B -direct=1 -thread -numjobs=2 -size=64M -rw=write -filename=/dev/sde -name="BS 512B read test" -iodepth=2

![image](https://user-images.githubusercontent.com/123857360/215316843-e9653724-5965-488c-9379-2b6b528777de.png)
The log circled in red above was added by myself. When I read and write to two disks at the same time, the thread does not change.

Can't the read and write operations of these two disks be performed on two different threads?
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Comphix** [comment]
This looks like as expected. What's the detailed parameters when starting the iSCSI target? Have you tried with -m parameter to assign more cores to it? The bdev(s) will be handled concurrently on multiple cores (threads).

**Comment by happyzyz** [comment]
Thank you for your reply,@Comphix .  
The specific command is as follows
/build/bin/iscsi_tgt -m 0x21 -L all.   
the read and write operations of these two disks be performed on the same thread and may affect performance

**Comment by shuhei-matsumoto** [comment]
@happyzyz 

SPDK iSCSI target has been designed and implemented so that for one iSCSI target all I/Os are processed by one SPDK thread.
Hence, if you want to use two SPDK threads for 2 LUNs, you will have to create two iSCSI targets and add one LUN to each iSCSI target.

**Comment by happyzyz** [comment]
Thank you for your reply,@shuhei-matsumoto.
Do you know why it is so designed? Is it better to allocate SPDK thread (or core) by lun?

**Comment by shuhei-matsumoto** [comment]
@happyzyz 

iSCSI connection is for not each LUN but each target. iSCSI connection is between one initiator and one target.
Hence, I think your point may not be architecturally possible.

What we can improve is allocate a different SPDK thread for each iSCSI connection.
Now, for one target, I/Os from all initiators use the same SPDK thread.

Make sense to you? I may miss something. Please correct me if I am wrong.

**Comment by happyzyz** [comment]
Thank you for your reply,@shuhei-matsumoto. I got
