### ISSUE TITLE
perf does not exit when receiving errors from aio device

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2893]
When using perf tool with kernel block devices via aio, it does not exit when it receives an error.  Reproduced with ublk from SPDK target currently, but suspect it will happen with other block devices too.

Steps to reproduce:

1) ./configure --with-ublk --with-uring
2) build/bin/spdk_tgt
3) scripts/rpc.py bdev_null_create null0 1000 512
4) scripts/rpc.py ublk_create_target
5) scripts/rpc.py ublk_start_disk null0 0 -q 4 -d 64
6) build/examples/perf -w read -t 300 -o 4096 -q 32 -c 0x10 /dev/ublkb0

Notice the performance while the test is running.  Then Ctrl-C the spdk_tgt, and you'll see performance jump and perf won't exit.

The io_uring error handling in perf works fine though.  Just add -R option to step 6.  When you Ctrl-C spdk_tgt, perf will print an error and exit.

**Comment by Bianyfan** [comment]
Raise a patch to add an aio event check for aio device like uring device, please help review:https://review.spdk.io/gerrit/c/spdk/spdk/+/16652
thanks.

**Comment by changpe1** [comment]
patch has been merged, closing it now.
