### ISSUE TITLE
ublk target build error under ubuntu 22.10 kernel 6.1.9

### ISSUE THREAD

**Issue by gaowayne** [spdk/spdk#2895]
# Sighting report

ublk target build error under ubuntu 22.10 kernel 6.1.9.
configure report no liburing and ublk_drv. but I am pretty sure they are ready and I can run ubdsrv null engine very well following this link on the same machine.
```
root@wayne-VirtualBox:/home/wayne/wayne/spdklatest/spdk# ./configure --with-ublk
Using default SPDK env in /home/wayne/wayne/spdklatest/spdk/lib/env_dpdk
Using default DPDK in /home/wayne/wayne/spdklatest/spdk/dpdk/build
--with-ublk requires liburing and ublk_drv.
Please install then re-run this script.
root@wayne-VirtualBox:/home/wayne/wayne/spdklatest/spdk# 
```

## Expected Behavior

./configure --with-ublk should not report error after we can run even run ubdsrv well.

## Steps to Reproduce

1. install 6.1.9 on ubuntu 22.10 enable ublk driver
2. modprobe ublk_drv
3. build and install liburing 2.2, build and install ubdsrv latest, run ublk verify these
4. ./configure --with-ublk
5. still report liburing and ublk_drv not ready
6.

**Comment by mikeBashStuff** [comment]
Do you have proper ublk headers available?  `configure` will check by compiling against liburing.h but also ublk_cmd.h.

**Comment by gaowayne** [comment]
> Do you have proper ublk headers available? `configure` will check by compiling against liburing.h but also ublk_cmd.h.

yes, it is fixed after I deploy ublk_cmd.h file into kernel headers folder. thank you so much man.
