### ISSUE TITLE
fio_plugin.c:50:25: fatal error: config-host.h: No such file or directory

### ISSUE THREAD

**Issue by cooljiansir** [spdk/spdk#29]
I followed the introduction `spdk/examples/nvme/fio_plugin/README`, but meet the following ERROR:
```
fio_plugin.c:50:25: fatal error: config-host.h: No such file or directory
 #include "config-host.h"
                         ^
compilation terminated.
make[3]: *** [fio_plugin.o] Error 1
make[2]: *** [fio_plugin] Error 2
make[1]: *** [nvme] Error 2
make: *** [examples] Error 2
```

**Comment by dverkamp-intel** [comment]
Make sure you have set SPDK's `CONFIG_FIO_PLUGIN` to the correct location, and verify that the FIO source has been configured and built (`config-host.h` is generated by the FIO `configure` script).

**Comment by cooljiansir** [comment]
Thanks! It works after running `configure` script.
