### ISSUE TITLE
vtophys test fails on FreeBSD

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#290]
## Expected Behavior
Basic SPDK test set on FreeBSD should be possible to run and succeed.

## Current Behavior
Vtophys tests fails.

## Possible Solution
Revert DPDK commit 190ce864 from  DPDK submodule.

## Steps to Reproduce
Used SPDK commit: 130307862 vhost/nvme: fix doorbell buffer size calculation
Used DPDK submodule commit: 8ba8947e0 memory: implement "single file segments"

1. Download & compile SPDK as described in README.md
2. load contigmem.ko and nic_uio.ko modules from DPDK submodule
3. Allocate superpages via setup.sh
4. Run vtophys test - ./test/env/vtophys/vtophys
5. Test fails.

## Context
Test run on virtualized FreeBSD system with 16GB or RAM (backed by hugepages on host) and passthrough 10 CPU cores from host - Xeon E5-2680
FreeBSD version: 11.1-RELEASE

**Comment by dverkamp-intel** [comment]
This should be resolved as of commit 396bedd09fb4d274a703f950e288400d5d7551a4, which pulls in the revert in the DPDK submodule.

**Comment by wanqunintel** [comment]
@karlatec would you update the info with commit 396bedd? Thank you.

**Comment by karlatec** [comment]
Retested with:
SPDK 14222198 test/lvol: make tests python3 compatible
DPDK sub-module cfaddaa2f Revert "contigmem: do not zero pages during each mmap"

Run spdk/autorun.sh with following config five times in a row, all pass.

```
SPDK_BUILD_DOC=0

SPDK_TEST_ISCSI=0
SPDK_TEST_NVME=1
SPDK_TEST_NVMF=0
SPDK_TEST_VHOST=0
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_IOAT=1
SPDK_TEST_EVENT=1
SPDK_TEST_PMDK=0
SPDK_TEST_VHOST_INIT=0
SPDK_TEST_LVOL=0
SPDK_TEST_VPP=0

RUN_NIGHTLY=0
```
Issue can be closed.
