### ISSUE TITLE
ssl sock implementation does not store impl_opts separately from posix

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2911]
The posix and ssl sock impls are very similar, and share almost all of the same code (as they should).  But the ssl implementation does not keep its own copy of its impl opts.

This results in problems if you for example, want different impl opt values for posix and ssl.  Or if you do a save_config RPC, edit a posix value, but not the corresponding ssl value.  save_config will always emit a sock_impl_set_opts RPC for each impl, and it puts posix before ssl.  So if you only edit the posix one, it is effectively ignored, since the ssl one right after it will overwrite it.

https://review.spdk.io/gerrit/c/spdk/spdk/+/16841 is an initial stab at fixing part of the problem - just the get/set for the impl_opts.  The rest of the posix.c file has to be scrubbed and fixed up all of the places where it currently hardcodes using the posix impl_opts.  We either need different implementations of each impl function (similar to what I do in the 16841 patch above), or maybe in some cases it can do a comparison of the sock->impl to determine which impl_opts to use.

**Comment by KKaras169169** [comment]
I uploaded a couple of patches here (the second one incorporates Jim's initial stab):
https://review.spdk.io/gerrit/c/spdk/spdk/+/18335
