### ISSUE TITLE
Package dependency installation failing on CentOS Stream (version 8).

### ISSUE THREAD

**Issue by acvitano** [spdk/spdk#2912]
# Sighting report

Package dependency installation failing on CentOS Stream (version 8).

When attempting to install on CentOS Stream 8 the command ./scripts/pkgdep.sh --all fails to install the ceph-release package due to an SSL error.

I also tried downloading the package manually but centos complains that it is not a proper rpm package when I do this (ssl certificate checking disabled to do this).

I suggest altering the centos.sh file to use the "centos-release-ceph-nautilus.noarch" package from CentOS-Extras repo instead, because with this workaround I was able to fix the issue and install spdk on the system.

## Expected Behavior

pkgdep.sh should install packages successfully

## Current Behavior

sudo scripts/pkgdep.sh --all
Last metadata expiration check: 1:57:19 ago on Fri 17 Feb 2023 11:00:32 AM PST.
epel-release-latest-8.noarch.rpm                                                                                                                                                                             71 kB/s |  24 kB     00:00
elrepo-release-8.el8.elrepo.noarch.rpm                                                                                                                                                                       66 kB/s |  13 kB     00:00
[MIRROR] ceph-release-1-1.el8.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://download.ceph.com/rpm-nautilus/el8/noarch/ceph-release-1-1.el8.noarch.rpm [SSL certificate problem: self signed certificate in certificate chain]
[MIRROR] ceph-release-1-1.el8.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://download.ceph.com/rpm-nautilus/el8/noarch/ceph-release-1-1.el8.noarch.rpm [SSL certificate problem: self signed certificate in certificate chain]
[MIRROR] ceph-release-1-1.el8.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://download.ceph.com/rpm-nautilus/el8/noarch/ceph-release-1-1.el8.noarch.rpm [SSL certificate problem: self signed certificate in certificate chain]
[MIRROR] ceph-release-1-1.el8.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://download.ceph.com/rpm-nautilus/el8/noarch/ceph-release-1-1.el8.noarch.rpm [SSL certificate problem: self signed certificate in certificate chain]
[FAILED] ceph-release-1-1.el8.noarch.rpm: Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://download.ceph.com/rpm-nautilus/el8/noarch/ceph-release-1-1.el8.noarch.rpm [SSL certificate problem: self signed certificate in certificate chain]
Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://download.ceph.com/rpm-nautilus/el8/noarch/ceph-release-1-1.el8.noarch.rpm [SSL certificate problem: self signed certificate in certificate chain]
Error!

After downloading and trying to install the rpm manually:

rpm -Uvh ceph-release-1-1.el8.noarch.rpm
error: ceph-release-1-1.el8.noarch.rpm: not an rpm package (or package manifest):

## Possible Solution

Update centos.sh to use this package instead: https://centos.pkgs.org/8/centos-extras-x86_64/centos-release-ceph-nautilus-1.2-2.el8.noarch.rpm.html

## Steps to Reproduce

1. git clone https://github.com/spdk/spdk
2. cd spdk
3. git submodule update --init
4. sudo scripts/pkgdep.sh --all [FAILS]

## Context (Environment including OS version, SPDK version, etc.)

CentOS Stream (version 8)

**Comment by mikeBashStuff** [comment]
I would say this has more to do with the actual `ca-certificates` on the target system rather than the location of the .rpm itself. We do build and provision `centos8` (not the Stream version though) images with this particular package without any issues (same thing for `rocky8` which serves as an actual replacement in tests for `centos8`).

**Comment by acvitano** [comment]
Thank you, I tried updating ca-certificates on the system and that didn't help. The only way I could make the installer work was with the workaround I describe (using a different package source). Perhaps this is just a CentOS Stream issue. I don't have a regular CentOS 8 system to test on.

**Comment by mikeBashStuff** [comment]
Based on the contents of http://mirror.centos.org/centos-8/8/storage/x86_64/ I don't really see the `nautilus` release anywhere. Which is especially weird as .repo from https://vault.centos.org/centos/8/extras/x86_64/os/Packages/centos-release-ceph-nautilus-1.2-2.el8.noarch.rpm (or its mirrorlist for that matter) points back at mirror.centos.org. So this won't work under rocky at all, but I would dare to say it shouldn't work under centos either. The only way I see is to actually modify the .repo file to point at https://vault.centos.org/centos/8/storage/x86_64/ceph-nautilus/ (this would work for rocky as well, but the mirrorlist would have to be hardcoded to centos/8 as valut.centos.org simply doesn't hold packages for rocky). 

With that in mind, we will be sticking to what ceph.com provides as switching to centos mirrors would require more hacking than necessary. :)
