### ISSUE TITLE
The second disk cannot respond to RPCs after deleting the first disk from spdk on a single server

### ISSUE THREAD

**Issue by Alvinlst** [spdk/spdk#2921]
# Sighting report

Assuming we have 2 nvme disks on a target node, something like this:
```
DeviceName       SerialNumber
/dev/nvme0n1     d1
/dev/nvme1n1     d2
```
Then we add both of them to spdk (unbind from kernel space and attach nvme controllers in spdk), the kernel loses control of these two disks. When getting bdevs in spdk, it looks like this:
```
bdev index 0: {Name:nvme0n1 ... Driver:{Nvme:[{PCIAddress:0000:b7:00.0 Controller:{VendorID:0x8086 ModelNumber:INTEL SSDPE2KE032T8 SerialNumber:d1111111111 FirmwareRevision:VDV10152 SubNQN:}}] ...  

bdev index 1: {Name:nvme1n1 ... Driver:{Nvme:[{PCIAddress:0000:b8:00.0 Controller:{VendorID:0x8086 ModelNumber:INTEL SSDPE2KE032T8 SerialNumber:d2222222222 FirmwareRevision:VDV10152 SubNQN:}}] ... 
```
Now we remove the second disk d2 from spdk, the disk is bind back to the kernel space. At this point, the bdev of d1 is still controlled by spdk, but the RPCs coming to this disk get stuck (e.g. create a lvol, detach the controller...).

## Expected Behavior

When there are two disks on a single server and both added to spdk, removing one disk should not cause any issues to the other disk.

## Current Behavior

After removing disk d2 from spdk, d1 cannot work properly. Creating lvols on d1 or removing d1 from spdk will get stuck.

## Possible Solution

Restarting spdk will temporarily solve the issue. But a fix would be appreciated to avoid this issue happening.

## Steps to Reproduce

1. Add disk d1 to spdk: unbind the device from `nvme` driver and bind it to `uio/vfio` driver; construct nvme bdev in spdk (rpc `bdev_nvme_attach_controller`); create lvstore (`rpc bdev_lvol_create_lvstore`)
2. Add disk d2 to spdk: same step as d1
3. Remove d2 from spdk: delete lvstore (rpc `bdev_lvol_delete_lvstore`); delete bdev (rpc `bdev_nvme_detach_controller`); unbind from user-space driver and bind the device back to kernel nvme driver
4. Remove d1 from spdk: same step as d2, but now it **gets stuck**

## Context (Environment including OS version, SPDK version, etc.)

We are running `spdk_tgt` binary on a server with 2 nvme disks.
CentOS 7
SPDK v22.05

**Comment by jimharris** [comment]
Hi,

Please post all of the details steps here in the GitHub issue directly.  SPDK does not have a paid Slack plan, so it has only limited message history.  Since the steps on Slack were posted 2 months ago, they are likely to be not visible soon.

Thanks,

Jim

**Comment by Alvinlst** [comment]
Actually while updating the description, I did more testing and realized the issue is caused by the incorrect unbinding (a bug in our code). This has nothing to do with spdk.

Sorry for the bother, and thanks a lot for all the help! I will close the issue now.
