### ISSUE TITLE
nvmf_tgt After booting, after the RDMA network card is hot-swapped，when i remove subsystem，add listener ，poll_cq  happen coredump

### ISSUE THREAD

**Issue by ztz114119** [spdk/spdk#2922]
# Sighting report

![image](https://user-images.githubusercontent.com/63161109/221787059-6f4b5d61-df9c-4048-a837-deb1c3f8f704.png)

## Expected Behavior

Establish a listener normally

## Current Behavior

segmentation fault coredump

## Steps to Reproduce

1../bin/nvmf_tgt -m [16-23,40-47]
2../scripts/rpc.py nvmf_create_transport -t RDMA -u 16384 -m 16 -c 4096 -q 256
3../scripts/rpc.py nvmf_create_subsystem  nqn.2023-06.io.h3c:noderdma -a -s h3c0000000rdma -d h3c_contorllerrdma
4. rdma card hotplug
5../scripts/rpc.py nvmf_subsystem_add_listener nqn.2023-06.io.h3c:noderdma -t rdma -a 192.169.1.1 -s 4420
 

## Context (Environment including OS version, SPDK version, etc.)

SPDK VERSION:21.0.1
environment：openeuler 22.03

**Comment by tomzawadzki** [comment]
[Bug scrub] There are patches outstanding for review that should address the issue, starting https://review.spdk.io/gerrit/c/spdk/spdk/+/15615/.

>4. rdma card hotplug

Could you describe what specificaly is done to hotplug the card ?

**Comment by ztz114119** [comment]
![image](https://user-images.githubusercontent.com/63161109/222020077-123acc55-5705-49c3-b784-9b5b1be6e9d8.png)
Replace remove with reset
echo ”1“ > reset

**Comment by ztz114119** [comment]
I also have a problem that when I create multiple listeners, there is a coredump when the RDMA NIC is reset
![image](https://user-images.githubusercontent.com/63161109/222021604-611b7212-17e9-447a-896a-8221c9e05a73.png)

**Comment by KKRainbow** [comment]
@ztz114119 could you please paste a backtrace of the core-dump here? So I can confirm that the patch can fix this.

**Comment by ztz114119** [comment]
![image](https://user-images.githubusercontent.com/63161109/222085317-e13ae219-7129-4e69-9970-d3939e308b56.png)
This is the same problem

**Comment by ztz114119** [comment]
When the nvmf_tgt is running, if there is a newly rdma card, can we listen to this network card?

**Comment by KKRainbow** [comment]
The current patchset can only retry to listen. But your demand can be fulfilled by doing a rescan_device before listening new port.
I think it can be an enhancement to the current patchset and I'll try to submit a patch for it after current patchset is merged.

**Comment by ksztyber** [comment]
[Bug scrub] @KKRainbow are still you planning on submitting the patch? If not, @AlekseyMarchuk said he can take a look at that.

**Comment by KKRainbow** [comment]
> [Bug scrub] @KKRainbow are still you planning on submitting the patch? If not, @AlekseyMarchuk said he can take a look at that.

I'll work on it in these two weeks.
