### ISSUE TITLE
spdk/blobfs: multiple reactor reported error

### ISSUE THREAD

**Issue by YankunLi** [spdk/spdk#2925]
# multiple reactor error
Use reactor_mask = "xo3"option to enable multiple reactor, but rocksdb db_bench report a error on starting. 

# stack info:
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `../rocksdb/db_bench --flagfile=./readrandomwriterandom.txt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  rte_mempool_default_cache (lcore_id=<optimized out>, mp=0x0) at /root/liyankun/spdk/dpdk/build/include/rte_mempool.h:1320
1320		if (lcore_id >= RTE_MAX_LCORE)
[Current thread is 1 (Thread 0x7f953ae5ed40 (LWP 1023684))]
Missing separate debuginfos, use: yum debuginfo-install bzip2-libs-1.0.6-26.el8.x86_64 fuse3-libs-3.2.1-12.el8.x86_64 glibc-2.28-220.el8.x86_64 libgcc-8.5.0-4.el8_5.x86_64 libstdc++-8.5.0-4.el8_5.x86_64 libuuid-2.32.1-38.el8.x86_64 lz4-libs-1.8.3-3.el8_4.x86_64 openssl-libs-1.1.1k-7.el8.x86_64 snappy-1.1.8-3.el8.x86_64 zlib-1.2.11-20.el8.x86_64
(gdb) bt
#0  rte_mempool_default_cache (lcore_id=<optimized out>, mp=0x0) at /root/liyankun/spdk/dpdk/build/include/rte_mempool.h:1320
#1  rte_mempool_get_bulk (n=1, obj_table=0x7ffdaa9b8468, mp=0x0) at /root/liyankun/spdk/dpdk/build/include/rte_mempool.h:1637
#2  rte_mempool_get (obj_p=0x7ffdaa9b8468, mp=0x0) at /root/liyankun/spdk/dpdk/build/include/rte_mempool.h:1665
#3  spdk_mempool_get (mp=0x0) at env.c:248
#4  0x00000000008540ae in cache_insert_buffer (file=file@entry=0x7f9530179ed0, offset=0) at blobfs.c:2114
#5  0x0000000000855ef8 in cache_append_buffer (file=0x7f9530179ed0) at blobfs.c:2425
#6  spdk_file_write (file=0x7f9530179ed0, ctx=0x232e870, payload=payload@entry=0x23594a0, offset=offset@entry=0, length=length@entry=37) at blobfs.c:2425
#7  0x0000000000610c6a in rocksdb::SpdkWritableFile::Append (this=0x2329c90, data=...) at ../spdk//lib/rocksdb/env_spdk.cc:62
#8  0x00000000004c2362 in rocksdb::LegacyWritableFileWrapper::Append (this=<optimized out>, data=...) at /usr/include/c++/8/bits/unique_ptr.h:345
#9  0x0000000000613077 in rocksdb::WriteStringToFile (fs=fs@entry=0x7ffdaa9b87c0, data=..., fname="/data2/rocksdb/000000.dbtmp", should_sync=should_sync@entry=true) at /usr/include/c++/8/chrono:333
#10 0x00000000006040af in rocksdb::WriteStringToFile (env=env@entry=0x23274c0, data=..., fname="/data2/rocksdb/000000.dbtmp", should_sync=should_sync@entry=true) at env/env.cc:390
#11 0x000000000064344d in rocksdb::SetIdentityFile (env=0x23274c0, dbname="/data2/rocksdb", db_id="") at /usr/include/c++/8/bits/basic_string.h:934
#12 0x0000000000522bb3 in rocksdb::DBImpl::NewDB (this=0x234cb20, new_filenames=0x7ffdaa9b8df0) at /usr/include/c++/8/bits/char_traits.h:287
#13 0x000000000052d7b0 in rocksdb::DBImpl::Recover (this=0x234cb20, column_families=std::vector of length 1, capacity 1 = {...}, read_only=<optimized out>, error_if_wal_file_exists=<optimized out>,
    error_if_data_exists_in_wals=<optimized out>, recovered_seq=0x7ffdaa9b9138) at db/db_impl/db_impl_open.cc:416
#14 0x00000000005264ad in rocksdb::DBImpl::Open (db_options=..., dbname=..., column_families=std::vector of length 1, capacity 1 = {...}, handles=0x7ffdaa9b9660, dbptr=0x232cb20, seq_per_batch=false,
    batch_per_txn=true) at db/db_impl/db_impl_open.cc:1554
#15 0x0000000000527cc5 in rocksdb::DB::Open (db_options=..., dbname="/data2/rocksdb", column_families=std::vector of length 1, capacity 1 = {...}, handles=handles@entry=0x7ffdaa9b9660,
    dbptr=dbptr@entry=0x232cb20) at db/db_impl/db_impl_open.cc:1447
#16 0x0000000000527e56 in rocksdb::DB::Open (options=..., dbname="/data2/rocksdb", dbptr=dbptr@entry=0x232cb20) at db/db_impl/db_impl_open.cc:1425
#17 0x000000000049dd34 in rocksdb::Benchmark::OpenDb (this=this@entry=0x232cad0, options=..., db_name="/data2/rocksdb", db=db@entry=0x232cb08) at tools/db_bench_tool.cc:4282
#18 0x000000000049ed14 in rocksdb::Benchmark::InitializeOptionsGeneral (this=this@entry=0x232cad0, opts=opts@entry=0x232cbf0) at include/rocksdb/options.h:1202
#19 0x00000000004b2f4c in rocksdb::Benchmark::Open (opts=0x232cbf0, this=0x232cad0) at tools/db_bench_tool.cc:4140
#20 rocksdb::Benchmark::Run (this=this@entry=0x232cad0) at tools/db_bench_tool.cc:2923
#21 0x0000000000487633 in rocksdb::db_bench_tool (argc=<optimized out>, argv=<optimized out>) at tools/db_bench_tool.cc:7405
#22 0x00007f9537e96d85 in __libc_start_main () from /lib64/libc.so.6
#23 0x000000000048637e in _start () at tools/db_bench_tool.cc:7423

**Comment by jimharris** [comment]
Hi @YankunLi,

RocksDB plugin is not designed to support multiple reactor cores.  There was never a workload that generated enough block I/O to warrant multiple polled mode reactor cores.

-Jim
