### ISSUE TITLE
One of the nvme drive is not detected by spdk

### ISSUE THREAD

**Issue by rkothiya** [spdk/spdk#2929]
# Sighting report

One of the nvme drive is not detected by spdk. Below is trimmed output of setup.sh.

```
Type       BDF                Vendor Device NUMA    Driver           Device     Block devices
NVMe     0000:20:00.0    1e0f   0007   0       uio_pci_generic  -          -
NVMe     0000:21:00.0    144d   a824   0       uio_pci_generic  -          -
NVMe     0000:43:00.0    1e0f   0007   0       uio_pci_generic  -          -
NVMe     0000:44:00.0    144d   a824   0       uio_pci_generic  -          -
NVMe     0000:88:00.0    1e0f   0007   1       uio_pci_generic  -          -
NVMe     0000:89:00.0    144d   a824   1       -                -          -
NVMe     0000:b1:00.0    1e0f   0007   1       uio_pci_generic  -          -
NVMe     0000:b2:00.0    144d   a824   1       uio_pci_generic  -          -
```

## Expected Behavior

Ideally the nvme drive should be dected by spdk

## Current Behavior

Drive on 89 slot is not dected for all the servers that we have.

## Possible Solution

Currently there is no know workaround that I am aware of. 

## Steps to Reproduce
1. clone spdk
2. compile and install spdk
3. run setup.sh as follows:
    `#  spdk/scripts/setup.sh`

## Context (Environment including OS version, SPDK version, etc.)
**spdk version:** v23.01
**spdk commit id :** 10edc60aa8b5f1b04d6496fea976dec75e276a95
**disto version (OS):** Ubuntu 20.04.4 LTS
**kernel version:** 5.4.0-139-generic

**Comment by jimharris** [comment]
Hi @rkothiya,

Anything interesting from dmesg when this happens?

Could you also try `PCI_ALLOWED=0000:89:00.0 spdk/scripts/setup.sh`?  Try it both in isolation (i.e. after a fresh boot) and then again after you've run setup.sh to bind the rest of the SSDs to uio_pci_generic.

-Jim

**Comment by rkothiya** [comment]
Apart from the above I also wanted to bring the following to your notice. The below trimed output is of lspci -vvv.

```
# lspci -vvv 
.
.
.
89:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X (prog-if 02 [NVM Express])
        Subsystem: Samsung Electronics Co Ltd NVMe SSD Controller PM173X
        Physical Slot: 9
        Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Interrupt: pin A routed to IRQ -2147483648   <<<<<<<<<<<<<
        NUMA node: 1
        Region 0: Memory at d3a00000 (64-bit, non-prefetchable) [size=32K]
        Expansion ROM at <ignored> [disabled]
        Capabilities: <access denied>
        Kernel modules: nvme

--
b2:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X (prog-if 02 [NVM Express])
        Subsystem: Samsung Electronics Co Ltd NVMe SSD Controller PM173X
        Physical Slot: 9-1
        Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Interrupt: pin A routed to IRQ 76
        NUMA node: 1
        Region 0: Memory at e1200000 (64-bit, non-prefetchable) [size=32K]
        Expansion ROM at <ignored> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: uio_pci_generic
        Kernel modules: nvme

```

**Comment by jimharris** [comment]
Thanks @rkothiya.

Unfortunately this looks like a Linux kernel or even BIOS problem.  SPDK isn't able to do anything to get a valid IRQ assigned to the device so that it can be bound by uio_pci_generic (SPDK doesn't even use the interrupt vector).

You can try using vfio-pci instead - it should not be affected by this IRQ allocation problem.

It's possible some kernel patch could bypass this IRQ allocation problem and still allow the device to bind to uio_pci_generic.  For example, Linux kernel commit acec09e which fixed a similar problem for devices behind a VMD endpoint.

**Comment by rkothiya** [comment]
@jimharris , thanks for the inputs. 

I am using `kernel version: 5.4.0-139-generic` which already has the above fix. I checked in the [ubuntu kernel rep](https://kernel.ubuntu.com/git/ubuntu/ubuntu-focal.git/tree/drivers/uio/uio_pci_generic.c) it has the above fix for my kernel version. 

For using the vfio-pci, I tried with the below command but it failed :
```
#sudo HUGE_EVEN_ALLOC=yes NRHUGE=32768  DRIVER_OVERRIDE=vfio-pci ./setup.sh
```

Do I need to do some other steps before executing the above command so that I can use vfio-pci.
Can you help me point to some good article on how to set this up.

**Comment by jimharris** [comment]
You will need to add `intel_iommu=on` (or equivalent for your platform).  You may also need to check BIOS settings on your platform to ensure virtualization extensions are enabled.  For Intel platforms this may look like "VT-x" or "VT-d".

**Comment by rkothiya** [comment]
Thanks for the suggestion, when I am using the vfio driver it seems to be working.
