### ISSUE TITLE
Cannot split nvme bdev after spdk_tgt restart if lvol store was previously created on first split

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#293]
## Expected Behavior
After spdk_tgt restart I can split nvme disk

## Current Behavior
Error occurs:
bdev.c:2752:spdk_bdev_module_claim_bdev: *ERROR*: bdev Nvme0n1 already claimed by module lvol
If split cannot be done then information on second split can be lost.

## Possible Solution
None

## Steps to Reproduce
Use following script:
#!/usr/bin/env bash
source ./test/common/autotest_common.sh

cat > /tmp/spdk.conf <<EOF
[Ioat]
  Disable Yes
EOF

./scripts/gen_nvme.sh >> /tmp/spdk.conf
app/spdk_tgt/spdk_tgt -c /tmp/spdk.conf &
pid=$!
waitforlisten $pid

./scripts/rpc.py destroy_lvol_store -l lvs_test || true
./scripts/rpc.py construct_split_vbdev Nvme0n1 2
./scripts/rpc.py construct_lvol_store -c 1048576 Nvme0n1p0 lvs_test

set +xe
kill -9 $pid
wait $pid
set -xe

app/spdk_tgt/spdk_tgt -c /tmp/spdk.conf &
pid=$!
waitforlisten $pid
./scripts/rpc.py construct_split_vbdev Nvme0n1 2

## Context (Environment including OS version, SPDK version, etc.)
Virtual machine with ubuntu and two emulated nvme devices (1G, 2G).

**Comment by darsto** [comment]
This can't really be fixed.
Creating an lvol on split 0 writes some lvol metadata on a couple of first
blocks of the underlying device. After a restart you can't tell if the
metadata refers to the entire device or some split, so lvol examine chooses
the former.

If you need such setup for testing purposes, you could replace split with
gpt, which occupies the first block of the device (the superblock) and
prevents the lvol examine from parsing the disk as one lvol.
D.

2018-05-08 12:30 GMT+02:00 pawelkax <notifications@github.com>:

**Comment by peluse** [comment]
I'm curious, why are you trying to do this? I'm guessing there's a good reason but I'm not seeing it :)

**Comment by benlwalker** [comment]
I think there's two choices to fix this:

* Introduce some order of operations for loading volumes based on whether they're explicitly configured or "discovered" via metadata.
* Don't fix it. The bdev modules that don't write metadata are really only for testing.

I'm ok with either solution.

**Comment by wanqunintel** [comment]
@benlwalker , is there any patch for it?

**Comment by pawelwod** [comment]
I will talk about this today on community meeting.
Thanks

**Comment by wanqunintel** [comment]
@pawelkax can you update the status about this issue after discussion in the community meeting?

**Comment by pawelwod** [comment]
We need to fix this for sure but as there was SPDK summit in progresss, Jim was not abble to attend to community meeting. We are in touch and talking on possible solutions. I will update as soon we agree how to fix this.

**Comment by wanqunintel** [comment]
@pawelkax any update?

**Comment by ChenWang01** [comment]
@wanqunintel  
https://trello.com/c/zmbepRYG/119-github-issue-293  work in progress

**Comment by pawelwod** [comment]
@wanqunintel I think the current owner of this issue is @pelplinski 

There are also some pathes for this from @pelplinski. I will review them tommorow.

**Comment by wanqunintel** [comment]
@ChenWang01 , you may refer to the links in this trello task and verify this bug. thanks.https://trello.com/c/zmbepRYG/119-github-issue-293

**Comment by pelplinski** [comment]
Last patch in series to workaround this issue is here: https://review.gerrithub.io/c/spdk/spdk/+/413913

Even with this patch we need to modify test a little bit.

This patch will not help with this exact scenario, because we load lvol during Nvme0n1 examine. This creates race condition, where lvol claims Nvme0n1 before split does.

To workaround this we need to specify split in config file. This way we will have information about split ahead of Nvme examine. Therefore we can split first, and then run examine on each virtually splitted bdev.

So, if we replace construct_split_vbdev  rpc call with following lines in config file it should work:
[Split]
  Split Nvme0n1 2

**Comment by pelplinski** [comment]
@pawelkax I think it should work as long as you call construct_split_vbdev before corresponding construct_nvme_bdev

**Comment by tomzawadzki** [comment]
All patches from @pelplinski were merged. So scenario described in his previous comment should apply.

@pawelkax This should work for new json config format as well. Like Piotr mentioned - as long as split is done before constructing nvme bdev. Can you please verify it with json config ?

**Comment by pawelkax** [comment]
@tomzawadzki 
I try to check applied patches:
1.	Run spdk_tgt
2.	Run ./scripts/rpc.py construct_split_vbdev Nvme0n1 2
3.	Run ./scripts/rpc.py construct_nvme_bdev -t PCIe -a 0000.00.04.0 -b Nvme0
4.	Spdk_tgt crashes with output:
spdk_tgt: blobstore.c:2739: _spdk_bs_load_used_clusters_cpl: Assertion `ctx->mask->length == ctx->bs->total_clusters' failed.
Aborted (core dumped)

This kind of error also occurs when loading old and new config where split and nvme is defined.

**Comment by pelplinski** [comment]
Following steps should work on current master:

```
start spdk_tgt with empty config

./scripts/rpc.py construct_split_vbdev Nvme0n1 2
./scripts/rpc.py construct_nvme_bdev -t PCIe -a 0000.00.81.0 -b Nvme0
./scripts/rpc.py construct_lvol_store -c 1048576 Nvme0n1p0 lvs_test

restart spdk_tgt

./scripts/rpc.py construct_split_vbdev Nvme0n1 2
./scripts/rpc.py construct_nvme_bdev -t PCIe -a 0000.00.81.0 -b Nvme0

get_lvol_stores should contain "lvs_test" on "Nvme0n1p0"
```

@pawelkax Could you confirm?

**Comment by pawelkax** [comment]
@pelplinski I checked this issue on master. Now it works properly.
