### ISSUE TITLE
Bogus message: spdk_nvme_print_completion: *ERROR*: sqid 55038 doesn't match qid

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#2930]
# Sighting report

When the SPDK initiator gets into a scenario where `nvme_rdma_qpair_abort_reqs` is called, we're seeing the `spdk_nvme_print_completion: *ERROR*: sqid 55038 doesn't match qid` message printed to stdout.
The message is caused by some uninitialized struct spdk_nvme_cpl members.

In our case, the initiator terminated gracefully while there was still outstanding commands on the target.

## Expected Behavior

No error message.

## Current Behavior

As mentioned, the issue is due the partial initialization of the cpl. Here's a stack trace showing the flow to the error message:
```
#0  spdk_nvme_print_completion (qid=1, cpl=0x7fffffffe480, bdf=0x2000003d84f6 "nqn.2019-20.com.hpe:51402ECAFFE00000.1.bay00", wwn=6097593526860129536) at nvme_qpair.c:514
#1  0x00005555556c2a90 in spdk_nvme_qpair_print_completion (qpair=0x2000003cf000, cpl=0x7fffffffe480) at nvme_qpair.c:541
#2  0x00005555556dd79c in nvme_rdma_req_complete (rdma_req=0x200000396d80, rsp=0x7fffffffe480, print_on_error=true) at nvme_rdma.c:453
#3  0x00005555556e296c in nvme_rdma_qpair_abort_reqs (qpair=0x2000003cf000, dnr=0) at nvme_rdma.c:2367
#4  0x00005555556e171a in nvme_rdma_qpair_disconnected (rqpair=0x2000003cf000, ret=0) at nvme_rdma.c:1926
#5  0x00005555556ddffb in nvme_rdma_process_event_poll (rqpair=0x2000003cf000) at nvme_rdma.c:673
#6  0x00005555556e1a18 in nvme_rdma_ctrlr_disconnect_qpair_poll (ctrlr=0x2000003d8380, qpair=0x2000003cf000) at nvme_rdma.c:2018
#7  0x00005555556e1acd in nvme_rdma_ctrlr_disconnect_qpair (ctrlr=0x2000003d8380, qpair=0x2000003cf000) at nvme_rdma.c:2058
#8  0x00005555556ca30a in nvme_transport_ctrlr_disconnect_qpair (ctrlr=0x2000003d8380, qpair=0x2000003cf000) at nvme_transport.c:538
#9  0x00005555556a6ec1 in spdk_nvme_ctrlr_free_io_qpair (qpair=0x2000003cf000) at nvme_ctrlr.c:599
...

(gdb) p *cpl
$1 = {cdw0 = 1, cdw1 = 0, sqhd = 55805, sqid = 21869, cid = 21845, {status_raw = 16, status = {p = 0, sc = 8, sct = 0, crd = 0, m = 0, dnr = 0}}}
```
When `nvme_rdma_qpair_abort_reqs` is called, it partially initializes `cpl` and passes it to `nvme_rdma_req_complete(rdma_req, &cpl, true)`. The cpl struct is not fully initialized (only status).
Now `nvme_rdma_req_complete` calls `spdk_nvme_qpair_print_completion(qpair, rsp);` with the cpl and eventually the condition below fails since sqid wasn't initialized and has random values:
```
if (cpl->sqid != qid && cpl->sqid != 0) {
		SPDK_ERRLOG("sqid %u doesn't match qid = %u\n", cpl->sqid, qid);
	}
```

## Possible Solution

It's not clear to me if the above condition is necessary. I would think so. However, we then need to initialize struct spdl_nvme_cpl correctly and I believe we're not fully initializing it in other scenarios either.

Note, in `nvme_qpair_manual_complete_request, we do seem to set `cpl.sqid = qpair->id`. Maybe this is good enough?

## Context (Environment including OS version, SPDK version, etc.)

SPDK 23.01 with --enable-debug (!!!)

**Comment by shuhei-matsumoto** [comment]
Thank you @mhae. I pushed a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/17067 for both RDMA and TCP transports.
