### ISSUE TITLE
spdk_bs_create_blob_ext() issue

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#2932]
# Sighting report

spdk_bs_create_blob_ext() succeeded but follow-on spdk_bs_open_blob() failed with EINVAL

## Expected Behavior

Today when I tried to create a very large blob (on DAOS server), the blob creation succeeded, but the follow-on blob open failed with EINVAL, so I collected some numbers before blob creating:
-          Cluster size: 1048576 bytes
-          Blobstore total clusters (acquired by spdk_bs_total_data_cluster_count()): 1526104
-          Blobstore free clusters (acquired by spdk_bs_free_cluster_count()): 1526104
-          num_clusters for the blob: 1526104
 
Then I tried to use SPDK blobcli to initialize a blobstore on the same device and create a blob with 1526104 clusters, it failed with ENOSPACE on blob resizing. The difference of DAOS server and blobcli is that DAOS server calls spdk_bs_create_blob_ext() with 'num_cluster' specified to do inline resizing, but blobcli calls spdk_bs_create_blob() to create blob first, then explicitly calls spdk_blob_resize() to resize blob to ‘num_clusters’.

## Current Behavior

My question is that should blob creation/resize fail with ENOSPACE in above case? If so, why spdk_bs_create_blob_ext() doesn't fail?

## Steps to Reproduce

1. Create blobstore on a SPDK bdev
2. Create a blob by spdk_bs_create_blob_ext() with spdk_bs_free_cluster_count() number of clusters specified
3. Open the blob by spdk_bs_open_blob()
4. The blob open failed with EINVAL

## Context (Environment including OS version, SPDK version, etc.)

SPDK version: v22.01.2
Kernel version: Rocky Linux release 8.6 (Green Obsidian)

**Comment by NiuYawei** [comment]
I did further investigation on this, and seems the issue is on the 'num_md_pages' specified on blobstore creation.

If I create the blobstore with 'num_md_pages = 20k' specified, the total & free clusters of blobstore will be showed as 1526104, but if I create the blobstore without 'num_md_pages' specified, the total & free clusters of blobstore will be 1520222.

- When the blobstore is created without 'num_md_pages' specified, both "spdk_bs_create_blob_ext(1520222)->spdk_bs_open_blob()" and "spdk_bs_create_blob() -> spdk_bs_open_blob() -> spdk_blob_resize(1520222)" work without any issue;

- When the blobstore is created with 20k 'num_md_pages' specified, the spdk_bs_create_blob_ext(1526104) will succeed but follow-on spdk_bs_open_blob() will fail with EINVAL. The spdk_bs_create_blob() & spdk_bs_open_blob() will succeed but follow-on spdk_blob_resize(1526104) will fail with ENOSPACE.

I was thinking that 'num_md_pages' is used to inform SPDK the maximum blob count a blobstore can have, is that correct? How should I specify this number if I want to create a blobstore with limited blob count (for minimizing meta page overhead)?

Thanks
-Niu

Thanks
-Niu

**Comment by Comphix** [comment]
Maybe Tomek could give some feedback here? Thanks.

**Comment by jimharris** [comment]
Tomek is on leave for a few weeks, so I'm taking ownership.  Working on a unit test to reproduce, based on the detailed steps from @NiuYawei.

**Comment by jimharris** [comment]
Good find @NiuYawei, and great triage.  Helped me create a unit test to recreate the issue.  Ended up being a one line fix.

https://review.spdk.io/gerrit/c/spdk/spdk/+/17150

**Comment by ksztyber** [comment]
Patch was merged, closing.
