### ISSUE TITLE
bdevperf with -C option and 2 NVMe bdevs creates two poll groups on each CPU core.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2933]
# Sighting report

This is not actually a bug but the behavior is not expected and want to be improved.

If bdevperf runs with -C option and 2 NVMe bdevs, bdevperf creates two SPDK threads on each CPU core. In the NVMe bdev module, each SPDK thread creates a poll group. Hence two poll groups are created on each CPU core. However, generally SPDK application creates one SPDK thread on each CPU core. Hence we want bdevperf to create one SPDK thread on each CPU core and to share one poll group by two NVMe bdevs.

## Expected Behavior

Create one SPDK thread on each CPU core and two I/O channels share one poll group in the NVMe bdev module.

## Current Behavior

Create two SPDK threads on each core, and two I/O channels use a different poll group in the NVMe bdev module.

## Possible Solution

https://review.spdk.io/gerrit/c/spdk/spdk/+/16994/1

## Steps to Reproduce

-C option + two or more NVMe bdevs

## Context (Environment including OS version, SPDK version, etc.)

The latest SPDK master

**Comment by jimharris** [comment]
This is great Shuhei.  It helps bdev layer w/ `bdevperf` operate much more like bdev layer in applications like `nvmf_tgt`.  I'll definitely be using this feature once it is merged.

Overall the patch looks great, I posted a few comments.

**Comment by jimharris** [comment]
Patch merged.  Thanks @shuhei-matsumoto!
