### ISSUE TITLE
blob_freeze_io() does not correctly handle nested freezes

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2935]
While reviewing some of the esnap clone patches from @mgerdts, I noticed something fishy with `blob_freeze_io()`.

```
static void
blob_freeze_io(struct spdk_blob *blob, spdk_blob_op_complete cb_fn, void *cb_arg)
{
        struct freeze_io_ctx *ctx;

        ctx = calloc(1, sizeof(*ctx));
        if (!ctx) {
                cb_fn(cb_arg, -ENOMEM);
                return;
        }

        ctx->cpl.type = SPDK_BS_CPL_TYPE_BS_BASIC;
        ctx->cpl.u.blob_basic.cb_fn = cb_fn;
        ctx->cpl.u.blob_basic.cb_arg = cb_arg;
        ctx->blob = blob;

        /* Freeze I/O on blob */
        blob->frozen_refcnt++;

        if (blob->frozen_refcnt == 1) {
                spdk_for_each_channel(blob->bs, blob_io_sync, ctx, blob_io_cpl);
        } else {
                cb_fn(cb_arg, 0);
                free(ctx);
        }
}
```

`frozen_refcnt` is trying to track nested freezes.  This is only called on the `bs->md_thread` (note, we should add an assert for that in this function), so incrementing/decrementing doesn't require a lock.

When frozen_refcnt is already 1, we might still be in the middle of the spdk_for_each_channel, ensuring that all threads have seen the frozen_refcnt != 0 before proceeding.  So we can't just immediately completely with success in this case.

@mgerdts, @benlwalker, @tomzawadzki - can you double-check my findings?  Anything I'm missing?  It's a super tiny window that could possibly cause this, but I think it is possible, even before the esnap clone changes.  For example, running heavy I/O on many threads, then do a resize immediately followed by snapshot.

We really need to put these ctx structures in some kind of SLIST, and complete all of them in blob_io_cpl.  We also need unit tests for this case.

**Comment by mgerdts** [comment]
> `frozen_refcnt` is trying to track nested freezes. This is only called on the `bs->md_thread` (note, we should add an assert for that in this function), so incrementing/decrementing doesn't require a lock.

An `assert()` seems reasonable. Note that it seems as though `spdk_bs_create_snapshot()` could be called from any thread and will trip over an assert() in `bs_open_blob()` before it gets here. This should be handled better at the public API in debug and non-debug builds.

> When frozen_refcnt is already 1, we might still be in the middle of the spdk_for_each_channel, ensuring that all threads have seen the frozen_refcnt != 0 before proceeding. So we can't just immediately completely with success in this case.

Yeah, you are right - good catch!

> 
While reviewing some of the esnap clone patches from @mgerdts, I noticed something fishy with blob_freeze_io().

static void
blob_freeze_io(struct spdk_blob *blob, spdk_blob_op_complete cb_fn, void *cb_arg)
{
        struct freeze_io_ctx *ctx;

        ctx = calloc(1, sizeof(*ctx));
        if (!ctx) {
                cb_fn(cb_arg, -ENOMEM);
                return;
        }

        ctx->cpl.type = SPDK_BS_CPL_TYPE_BS_BASIC;
        ctx->cpl.u.blob_basic.cb_fn = cb_fn;
        ctx->cpl.u.blob_basic.cb_arg = cb_arg;
        ctx->blob = blob;

        /* Freeze I/O on blob */
        blob->frozen_refcnt++;

        if (blob->frozen_refcnt == 1) {
                spdk_for_each_channel(blob->bs, blob_io_sync, ctx, blob_io_cpl);
        } else {
                cb_fn(cb_arg, 0);
                free(ctx);
        }
}
frozen_refcnt is trying to track nested freezes. This is only called on the bs->md_thread (note, we should add an assert for that in this function), so incrementing/decrementing doesn't require a lock.

When frozen_refcnt is already 1, we might still be in the middle of the spdk_for_each_channel, ensuring that all threads have seen the frozen_refcnt != 0 before proceeding. So we can't just immediately completely with success in this case.

@mgerdts, @benlwalker, @tomzawadzki - can you double-check my findings? Anything I'm missing? It's a super tiny window that could possibly cause this, but I think it is possible, even before the esnap clone changes. For example, running heavy I/O on many threads, then do a resize immediately followed by snapshot.

> We really need to put these ctx structures in some kind of SLIST, and complete all of them in blob_io_cpl. We also need unit tests for this case.

It could be done that way, or we could just send all freezes in a lap around the blob's channels. How often are concurrent snapshot and/or resize (and/or esnap hotplug) operations targeting the same blob expected to happen? I'd guess that this is rare enough that it doesn't make sense to try to optimize for it, particularly if it means adding more code that needs to be maintained.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/17148

**Comment by ksztyber** [comment]
Patch was merged, closing.
