### ISSUE TITLE
In some cases, it can cause the jsonrpc tcp connection to be unable to be removed.

### ISSUE THREAD

**Issue by benqwu** [spdk/spdk#2939]
# Sighting report

## Expected Behavior
When the client closes the connection prematurely, it should not cause the corresponding spdk_jsonrpc_server_conn to be unable to be released.

## Current Behavior
In some cases, it can cause the jsonrpc tcp connection to be unable to be removed.

## Possible Solution
If a client sends 2 requests in a connection, the outstanding_requests count will be 2. If the client closes the connection prematurely and the server responds to one of the requests, jsonrpc_server_conn_send will fail and the connection will be closed. jsonrpc_server_conn_send will only clear the requests that are already in the send queue, leading to outstanding_requests becoming 1. Even if the server responds to the remaining request, it will not be cleared, causing the connection to be unable to be released.

```
int
spdk_jsonrpc_server_poll(struct spdk_jsonrpc_server *server)
{
	int rc;
	struct spdk_jsonrpc_server_conn *conn, *conn_tmp;

	TAILQ_FOREACH_SAFE(conn, &server->conns, link, conn_tmp) {
		/* If we can't receive and there are no outstanding requests close the connection. */
		if (conn->closed == true && conn->outstanding_requests == 0) {
			jsonrpc_server_conn_close(conn);
		}

                //If there are still unanswered requests in this connection, this conn will never be remove
		if (conn->sockfd == -1 && conn->outstanding_requests == 0) { 
			jsonrpc_server_conn_remove(conn);
		}
	}

	/* Check listen socket */
	if (!TAILQ_EMPTY(&server->free_conns)) {
		jsonrpc_server_accept(server);
	}

	TAILQ_FOREACH(conn, &server->conns, link) {
		if (conn->sockfd == -1) {
			continue;
		}

		rc = jsonrpc_server_conn_send(conn);
		if (rc != 0) {
			jsonrpc_server_conn_close(conn);
			continue;
		}

		if (!conn->closed) {
			rc = jsonrpc_server_conn_recv(conn);
			if (rc != 0) {
				jsonrpc_server_conn_close(conn);
			}
		}
	}

	return 0;
}
```

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
This sounds like a bug, but can you please add reproduction steps?  In-tree rpc.py only sends one RPC request at a time - you must have your own script sending multiple in parallel?  If so, please post a version here that someone can use to help reproduce and fix the problem.

**Comment by benqwu** [comment]
> This sounds like a bug, but can you please add reproduction steps? In-tree rpc.py only sends one RPC request at a time - you must have your own script sending multiple in parallel? If so, please post a version here that someone can use to help reproduce and fix the problem.

We developed a client RPC program using Python, which sends multiple requests during a single connection. If the SPDK RPC script is used, everything works fine.
