### ISSUE TITLE
NVMe library AER callback should be per-process

### ISSUE THREAD

**Issue by dverkamp-intel** [spdk/spdk#294]
Similar to commit 31bf5d795e5464ba7d152d6705293221c6efa2ec, the AER callback function set by spdk_nvme_ctrlr_register_aer_callback() should be tracked in the per-process controller data structure.  Otherwise, the AER callback for another process could be called when polling the admin queue from multiple processes, leading to a crash.

**Comment by wanqunintel** [comment]
@dverkamp-intel is there any error log for it?

**Comment by dverkamp-intel** [comment]
There isn't an error log (this was just found by inspection); we should write a test that reproduces the issue as part of the fix, though. The test could be something like: process A and B both attach to an NVMe device and set AER callbacks; begin a loop in both processes that polls for admin completions; trigger an AER and make sure no crashes occur and one process's AER gets called.

**Comment by dverkamp-intel** [comment]
I've pushed a series for review that implements the fix: https://review.gerrithub.io/#/c/spdk/spdk/+/410953/

However, we should also still add tests for this.

**Comment by ChenWang01** [comment]
Hi Daniel,
I have try to reproduce this issue with following steps, but it's failed. Can you help me to check these steps.
1. Start nvmf tgt:
    `./app/nvmf_tgt/nvmf_tgt -s 512 &`

2.  Create subsystem:
    ` ./scripts/rpc.py construct_nvme_bdev -b "nvme0" -t "PCIe" -a "0000:81:00.0"`
    ` ./scripts/rpc.py construct_nvmf_subsystem nqn.2016-06.io.spdk:cnode1 
     "trtype:RDMA traddr:192.168.3.11 trsvcid:4420" '' -a -s SPDK00000000000001 -n nvme0n1`

3.  Start process A and B: 
      `Process A: ./test/nvme/aer/aer -r '  trtype:RDMA  adrfam:IPv4  traddr:192.168.3.11 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1' -n 2`
      `Process B: ./test/nvme/aer/aer -r '  trtype:RDMA  adrfam:IPv4  traddr:192.168.3.11 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1' -n 3`

4. Trigger an AER with ns 2
    `./scripts/rpc.py construct_nvme_bdev -b "nvme1" -t "PCIe" -a "0000:84:00.0"`
    `./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 nvme1n1 -n 2`

5.  Results:
    no crashes occur and  process A's AER gets called, process B gets Error:
  ```
Process A
[ DPDK EAL parameters: aer -c 0x1 -m 64 --file-prefix=spdk_pid8821 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid8821_unix
EAL: Probing VFIO support...
Asynchronous Event Request test
Attaching to 192.168.3.11
Attached to 192.168.3.11
Registering asynchronous event callbacks...
Starting namespce attribute notice tests for all controllers...
192.168.3.11: aer_cb for log page 4
192.168.3.11: changed NS list contains expected NSID: 2
Cleaning up...

Process B
[ DPDK EAL parameters: aer -c 0x1 -m 64 --file-prefix=spdk_pid9336 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid9336_unix
EAL: Probing VFIO support...
Asynchronous Event Request test
Attaching to 192.168.3.11
Attached to 192.168.3.11
Registering asynchronous event callbacks...
Starting namespce attribute notice tests for all controllers...
192.168.3.11: aer_cb for log page 4
192.168.3.11: Error: Cann't find expected NSID 3

```
Thanks,
Chen

**Comment by wanqunintel** [comment]
@ChenWang01 maybe we can try to add more process to see?
