### ISSUE TITLE
FreeBSD unittest_rdma: common_ut: No such file or directory

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2941]
# Sighting report

RDMA unit tests fail  on FreeBSD 13.1 CI VMs due to 

```
/usr/home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 1065:
/usr/home/vagrant/spdk_repo/spdk/test/unit/lib/rdma/common.c/common_ut: No such file or directory
```

Apparently[ verbs.h ](https://github.com/spdk/spdk/blob/master/test/common/autotest_common.sh#L393) is present in the system although I don't see any RDMA / Infiniband deps being installed in [pkgdep scripts](https://github.com/spdk/spdk/blob/master/scripts/pkgdep/freebsd.sh).

https://ci.spdk.io/public_build/autotest-per-patch_100028.html
https://ci.spdk.io/results/autotest-per-patch/builds/100028/archive/freebsd-vg-autotest/build.log

## Expected Behavior

RDMA UT's should either be skipped (we don't expect RDMA deps on FreeBSD images?) or complete successfully.

## Current Behavior

Fails.

## Possible Solution

One solution would be to just not build RDMA under FreeBSD: https://review.spdk.io/gerrit/c/spdk/spdk/+/17152

## Steps to Reproduce

1. Use following autorun.conf flags:
```
SPDK_TEST_UNITTEST=1                                                                                                                                                                                                 
SPDK_RUN_VALGRIND=0                                                                                                                                                                                                  
SPDK_RUN_FUNCTIONAL_TEST=1                                                                                                                                                                                           
SPDK_TEST_NVME=1                                                                                                                                                                                                     
SPDK_TEST_BLOCKDEV=1   
```

2. Run `autorun.sh`

## Context (Environment including OS version, SPDK version, etc.)

SPDK eda537344aa895b3f6b3538fad6d5af48584724e
FreeBSD 13.1 FreeBSD freebsd-cloud-1661763008-1335.local 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64
clang 13.0.0 "FreeBSD clang version 13.0.0

**Comment by ksztyber** [comment]
This patch should fix this: https://review.spdk.io/gerrit/c/spdk/spdk/+/17182

**Comment by karlatec** [comment]
Did a manual re-test and now FreeBSD runs RDMA unittest rdma_common suite and passes.
