### ISSUE TITLE
unittest_sock failed on FreeBSD

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2943]
# Sighting report

unittest_sock  fails on FreeBSD 13.1 CI VMs.
https://ci.spdk.io/public_build/autotest-per-patch_100150.html
https://ci.spdk.io/results/autotest-per-patch/builds/100150/archive/freebsd-vg-autotest/build.log

## Current Behavior

```
00:03:41.895  ************************************
00:03:41.895  START TEST unittest_sock
00:03:41.895  ************************************
00:03:41.895   08:27:24	-- common/autotest_common.sh@1064 -- # xtrace_enable
00:03:41.895   08:27:24	-- common/autotest_common.sh@1065 -- # unittest_sock
00:03:41.895   08:27:24	-- unit/unittest.sh@122 -- # /usr/home/vagrant/spdk_repo/spdk/test/unit/lib/sock/sock.c/sock_ut
00:03:41.895  
00:03:41.895  
00:03:41.895       CUnit - A unit testing framework for C - Version 2.1-3
00:03:41.895       http://cunit.sourceforge.net/
00:03:41.895  
00:03:41.895  
00:03:41.895  Suite: sock
00:03:42.867    Test: posix_sock ...FAILED
00:03:42.867      1. sock_ut.c:397  - rc == 0
00:03:42.867      2. sock_ut.c:401  - rc == 0
00:03:44.241    Test: ut_sock ...passed
00:03:44.241    Test: posix_sock_group ...passed
00:03:44.241    Test: ut_sock_group ...passed
00:03:44.241    Test: posix_sock_group_fairness ...passed
00:03:44.241    Test: _posix_sock_close ...passed
00:03:44.241    Test: sock_get_default_opts ...passed
00:03:44.241    Test: ut_sock_impl_get_set_opts ...passed
00:03:44.241    Test: posix_sock_impl_get_set_opts ...passed
00:03:44.241    Test: ut_sock_map ...passed
00:03:44.241    Test: override_impl_opts ...passed
00:03:44.241    Test: ut_sock_group_get_ctx ...passed
00:03:44.241  
00:03:44.241  Run Summary:    Type  Total    Ran Passed Failed Inactive
00:03:44.241                suites      1      1    n/a      0        0
00:03:44.241                 tests     12     12     11      1        0
00:03:44.241               asserts    349    349    347      2      n/a
```

## Steps to Reproduce

1. Use following autorun.conf flags:
```
SPDK_TEST_UNITTEST=1                                                                                                                                                                                                 
SPDK_RUN_VALGRIND=0                                                                                                                                                                                                  
SPDK_RUN_FUNCTIONAL_TEST=1                                                                                                                                                                                           
SPDK_TEST_NVME=1                                                                                                                                                                                                     
SPDK_TEST_BLOCKDEV=1   
```

2. Run `autorun.sh`

## Context (Environment including OS version, SPDK version, etc.)

SPDK 6a86385dade5c48c86ec1bdcdbaca44c250f6269
(well, actually it's using https://review.spdk.io/gerrit/c/spdk/spdk/+/17184 and https://review.spdk.io/gerrit/c/spdk/spdk/+/17152/2 on top to get around https://github.com/spdk/spdk/issues/2942 and https://github.com/spdk/spdk/issues/2941 issues)
FreeBSD 13.1 FreeBSD freebsd-cloud-1661763008-1335.local 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64
clang 13.0.0 "FreeBSD clang version 13.0.0

**Comment by ksztyber** [comment]
I've looked at this and it seems the problem here is that we're trying to do `setsockopt(SO_RCVBUF|SO_SNDBUF)` with a 2M buffer, which fails with `ENOBUFS`, because the max buffer size (`kern.ipc.maxsockbuf`) is too small. What's interesting is that `kern.ipc.maxsockbuf` is actually set to 2M on our freebsd image, but that still doesn't allow setting `SO_RCVBUF|SO_SNDBUF` to 2M. Apparantly the BSD kernel does some adjustments to that max value and won't actually allow setting it. There even was a discussion to change that behavior on FreeBSD's [bugzilla](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204438), but it hasn't been changed.

Anyway, I think the easiest way to fix this would be to simply increase `kern.ipc.maxsockbuf` to something larger (e.g. 4M) on our CI images.

**Comment by karlatec** [comment]
Proposed change: https://review.spdk.io/gerrit/c/spdk/spdk/+/17370/2

**Comment by mikeBashStuff** [comment]
Reopening since this is still happening. The trace is a bit different now (different parts of sock_ut.c are failing) but I think it's close enough to keep it under the same issue:

https://ci.spdk.io/results/autotest-per-patch/builds/101839/archive/freebsd-vg-autotest/build.log

```
00:04:13.021  ************************************
00:04:13.021  START TEST unittest_sock
00:04:13.021  ************************************
00:04:13.021   07:24:34	-- common/autotest_common.sh@1068 -- # xtrace_enable
00:04:13.021   07:24:34	-- common/autotest_common.sh@1069 -- # unittest_sock
00:04:13.021   07:24:34	-- unit/unittest.sh@122 -- # /usr/home/vagrant/spdk_repo/spdk/test/unit/lib/sock/sock.c/sock_ut
00:04:13.021  
00:04:13.021  
00:04:13.021       CUnit - A unit testing framework for C - Version 2.1-3
00:04:13.021       http://cunit.sourceforge.net/
00:04:13.021  
00:04:13.021  
00:04:13.021  Suite: sock
00:04:13.958    Test: posix_sock ...passed
00:04:14.895    Test: ut_sock ...passed
00:04:14.895    Test: posix_sock_group ...FAILED
00:04:14.895      1. sock_ut.c:553  - rc == 1
00:04:14.895      2. sock_ut.c:554  - g_read_data_called == true
00:04:14.895      3. sock_ut.c:555  - g_bytes_read == 7
00:04:14.895      4. sock_ut.c:557  - strncmp(test_string, g_buf, 7) == 0
00:04:15.154    Test: ut_sock_group ...passed
00:04:15.154    Test: posix_sock_group_fairness ...passed
00:04:15.155    Test: _posix_sock_close ...passed
00:04:15.155    Test: sock_get_default_opts ...passed
00:04:15.155    Test: ut_sock_impl_get_set_opts ...passed
00:04:15.155    Test: posix_sock_impl_get_set_opts ...passed
00:04:15.155    Test: ut_sock_map ...passed
00:04:15.155    Test: override_impl_opts ...passed
00:04:15.155    Test: ut_sock_group_get_ctx ...passed
00:04:15.155  
00:04:15.155  Run Summary:    Type  Total    Ran Passed Failed Inactive
00:04:15.155                suites      1      1    n/a      0        0
00:04:15.155                 tests     12     12     11      1        0
00:04:15.155               asserts    348    348    344      4      n/a
00:04:15.155  
00:04:15.155  Elapsed time =    0.008 seconds
00:04:15.155    07:24:36	-- unit/unittest.sh@122 -- # trap - ERR
00:04:15.155    07:24:36	-- unit/unittest.sh@122 -- # print_backtrace
00:04:15.155    07:24:36	-- common/autotest_common.sh@1097 -- # [[ ehxBET =~ e ]]
00:04:15.155    07:24:36	-- common/autotest_common.sh@1099 -- # args=('unittest_sock' 'unittest_sock')
00:04:15.155    07:24:36	-- common/autotest_common.sh@1099 -- # local args
00:04:15.155    07:24:36	-- common/autotest_common.sh@1101 -- # xtrace_disable
00:04:15.155    07:24:36	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
00:04:15.155    07:24:36	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
00:04:15.155    07:24:36	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
00:04:15.155    07:24:36	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
00:04:15.155    07:24:36	-- common/autotest_common.sh@24 -- # set +x
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_101839.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_101709.html

**Comment by jimharris** [comment]
And then the one that Konrad just posted has an even different failing signature.

I'll take a look...

**Comment by jimharris** [comment]
I pushed https://review.spdk.io/gerrit/c/spdk/spdk/+/17572 and ran it through Jenkins CI a few times.

I wasn't able to hit @mikeBashStuff's failing signature, but can reliably hit the one that Konrad report showed.  In that case, the override_impl_opts case fails intermittently.  The failure is that we do a listen + connect + accept, and the accept never returns a sock.  But we do this sequence a bunch of other times in other places, and don't see a problem there.

And now I've encountered a third test that fails with this Jenkins CI testing I'm doing:

```
12:45:50    Test: ut_sock_group ...passed
12:45:50    Test: posix_sock_group_fairness ...FAILED
12:45:50      1. sock_ut.c:701  - rc == 1
12:45:50      2. sock_ut.c:702  - g_server_sock_read == server_sock[0]
12:45:50    Test: _posix_sock_close ...passed
12:45:50    Test: sock_get_default_opts ...passed
12:45:50    Test: ut_sock_impl_get_set_opts ...passed
```

So there's a lot here that needs to be figured out.  I propose we merge patch https://review.spdk.io/gerrit/c/spdk/spdk/+/17573 for now so we stop hitting these failures.

**Comment by ksztyber** [comment]
[Bug scrub] Let's disable the tests for now, but keep the issue open. If anyone is willing to take a look at this - feel free.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_103016.html

**Comment by tomzawadzki** [comment]
[Bug scrub] Due to low priority of UT socket interface on FreeBSD, closing the issue.
