### ISSUE TITLE
vhost-initiator-vg-autotest: sigabrt in json_config.sh test when --with-ocf enabled

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2951]
# Sighting report

SIGABRT encountered when running json_config.sh vhost initiator test cases.
https://ci.spdk.io/public_build/autotest-per-patch_100311.html

Seems to be caused by:
`spdk_tgt: virtio_vhost_user.c:596: virtio_user_map_notify: Assertion 'false' failed.`

## Current Behavior

Logs too big to paste here.
See:
https://ci.spdk.io/results/autotest-per-patch/builds/100311/archive/vhost-initiator-vg-autotest/errtrace.log
https://ci.spdk.io/results/autotest-per-patch/builds/100311/archive/vhost-initiator-vg-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/100311/archive/vhost-initiator-vg-autotest/coredumps/index.html

## Steps to Reproduce

1. Build SPDK with:
```
./configure --with-rdma --enable-debug --enable-werror --with-idxd --with-fio=/usr/src/fio --disable-unit-tests --enable-ubsan --enable-asan --with-ocf; make -j
```
(That's less options than in linked build logs, but this reduced set still allows for reproduction)

2. Run json_config.sh test for vhost initiator:
```
sudo -E SPDK_TEST_VHOST_INIT=1 SPDK_TEST_VHOST=1 test/json_config/json_config.sh
```
(SPDK_TEST_VHOST set to 1 because test script would set it to 1 itself anyway)

## Context (Environment including OS version, SPDK version, etc.)

SPDK https://github.com/spdk/spdk/commit/7c3c0b663022417e6ebe1a99c21d2e2b52b30968
Linux fedora37-cloud-1678329680-1737 6.1.14-200.fc37.x86_64 https://github.com/spdk/spdk/issues/1 SMP PREEMPT_DYNAMIC Sun Feb 26 00:13:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
gcc 12.2.1 "cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)"

**Comment by ksztyber** [comment]
This patch should fix this: https://review.spdk.io/gerrit/c/spdk/spdk/+/17265

**Comment by karlatec** [comment]
Test passes with patch

**Comment by karlatec** [comment]
Need to reopen.
This happened in two other tests as well:
* test/vhost/initiator/blockdev.sh - proposed fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/17371/1 (same as what you did for json_config.sh test)
* test/spdkcli/virtio.sh - proposed fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/17372/1

The second issue can't be fixed by simple `bdev_virtio_controller_detach` because sigabrt occurs when secondary process in  test/spdkcli/virtio.sh does `/bdevs/virtioblk_disk create virtioblk_user user` spdkcli command https://github.com/spdk/spdk/blob/master/test/spdkcli/virtio.sh#L50 (which translates to bdev_virtio_attach_controller https://github.com/spdk/spdk/blob/master/python/spdk/spdkcli/ui_root.py#L222).
Following commit message https://review.spdk.io/gerrit/c/spdk/spdk/+/17265 I increased the memory allocated for target app.

Can you take a look this makes sense?

**Comment by karlatec** [comment]
Logs for second issue, virtio.sh test:
[spdkcli_virtio_log.txt](https://github.com/spdk/spdk/files/11097641/spdkcli_virtio_log.txt)

**Comment by karlatec** [comment]
Since we want some test to terminate SPDK process with virtio controllers still attached - I ditched the commit adding `detach` commands and squashed them into one which just increases memory for SPDK processes: https://review.spdk.io/gerrit/c/spdk/spdk/+/17371/5

**Comment by karlatec** [comment]
Patches were merged, virtio tests are now passing. Closing the issue.
