### ISSUE TITLE
spdk hugepage leak

### ISSUE THREAD

**Issue by netjia-cpu** [spdk/spdk#2954]
On the centos 7.9 system, use the spdk app to test the nvme disk, use the script to start 16 apps concurrently. Use free -g to check the system memory before starting, and use free -g to check the system memory after starting, and found that dozens of G are missing, and the hugepage memory configured for the app is only 10G, which is far from matching.
If you don’t start the app concurrently, it’s right, in the test, we use unlink-hugepage flags, so you suspect that there is a leak when spdk maps hugepage memory, or there is a problem with hugetlbfs

**Comment by jimharris** [comment]
Please use English for any posts in the SPDK GitHub issue database.
