### ISSUE TITLE
[nvmf_discovery] nvme0 not present 1 second after nvmf_subsystem_add_host

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2956]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/100574/archive/nvmf-tcp-phy-autotest/build.log

## Execution failed at

```
00:29:53.494  [2023-03-23 00:49:52.807085] bdev_nvme.c:5604:discovery_attach_controller_done: *INFO*: Discovery[10.0.0.2:8009] attach nvme0 done
00:29:53.494  [2023-03-23 00:49:52.807105] bdev_nvme.c:5563:discovery_remove_controllers: *INFO*: Discovery[10.0.0.2:8009] NVM nqn.2016-06.io.spdk:cnode0:10.0.0.2:4420 found again
00:29:53.494    00:49:52	-- common/autotest_common.sh@580 -- # xtrace_enable
00:29:53.494    00:49:52	-- common/autotest_common.sh@581 -- # [[ 0 == 0 ]]
00:29:53.494   00:49:52	-- host/discovery.sh@101 -- # [[ '' == \n\v\m\e\0 ]]
00:29:53.494    00:49:52	-- host/discovery.sh@101 -- # trap - ERR
00:29:53.494    00:49:52	-- host/discovery.sh@101 -- # print_backtrace
00:29:53.494    00:49:52	-- common/autotest_common.sh@1093 -- # [[ ehxBET =~ e ]]
00:29:53.494    00:49:52	-- common/autotest_common.sh@1095 -- # args=('--transport=tcp')
00:29:53.494    00:49:52	-- common/autotest_common.sh@1095 -- # local args
00:29:53.494    00:49:52	-- common/autotest_common.sh@1097 -- # xtrace_disable
00:29:53.494    00:49:52	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
00:29:53.494    00:49:52	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
00:29:53.494    00:49:52	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
00:29:53.494    00:49:52	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
00:29:53.494    00:49:52	-- common/autotest_common.sh@24 -- # set +x
00:29:53.494  ========== Backtrace start: ==========
00:29:53.494  
00:29:53.494  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/host/discovery.sh:101 -> main(["--transport=tcp"])
00:29:53.494       ...
00:29:53.494     96  	
00:29:53.494     97  	# Discovery hostnqn is added, so now the host should see the subsystem, with a single path for the
00:29:53.494     98  	# port of the single listener on the target.
00:29:53.494     99  	$rpc_py nvmf_subsystem_add_host ${NQN}0 $HOST_NQN
00:29:53.494     100 	sleep 1 # Wait a bit to make sure the discovery service has a chance to detect the changes
00:29:53.494  => 101 	[[ "$(get_subsystem_names)" == "nvme0" ]]
00:29:53.494     102 	[[ "$(get_bdev_list)" == "nvme0n1" ]]
00:29:53.494     103 	[[ "$(get_subsystem_paths nvme0)" == "$NVMF_PORT" ]]
00:29:53.494     104 	get_notification_count
00:29:53.494     105 	[[ $notification_count == 1 ]]
00:29:53.494     106 	
00:29:53.494       ...
00:29:53.494  
00:29:53.494  ========== Backtrace end ==========
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_100574.html

**Comment by tomzawadzki** [comment]
This intermittent failure did not occur for last 3 months, closing.

**Comment by xjjx** [comment]
Another instance of this issue: https://ci.spdk.io/public_build/autotest-nightly_3470.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1631.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3537.html

**Comment by tomzawadzki** [comment]
Fix was posted in https://review.spdk.io/gerrit/c/spdk/spdk/+/22380/

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1779.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1809.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_463.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v22.11_581.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_2055.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_812.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_2231.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v22.11_876.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_886.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_938.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_2362.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_963.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_2378.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_986.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_996.html
