### ISSUE TITLE
Error occurs when recreating rbd bdev

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#296]
## Expected Behavior
Create rbd bdev again should end with no error

## Current Behavior
io_channel.c: 328:spdk_io_device_register: *ERROR*: io_device 0x222a570 already registered

## Possible Solution
None

## Steps to Reproduce
./scripts/rpc.py -s /var/tmp/spdk.sock construct_rbd_bdev rbd foo 4096
./scripts/rpc.py -s /var/tmp/spdk.sock delete_bdev Ceph0
./scripts/rpc.py -s /var/tmp/spdk.sock construct_rbd_bdev rbd foo 4096
bdev_rbd.c: 643:spdk_bdev_rbd_create: *NOTICE*: Add Ceph1 rbd disk to lun

## Context (Environment including OS version, SPDK version, etc.)
Virtual machine with ubuntu and two emulated nvme devices (1G, 2G).

**Comment by dverkamp-intel** [comment]
It looks like the bdev_rbd destruct function doesn't fully clean up (spdk_io_device_unregister() is not called at all in the cleanup path).

**Comment by wanqunintel** [comment]
@yidong0635 can you try with ./configure --with-rbd and compile to see if it occurs

**Comment by yidong0635** [comment]
this issue will debug together with #301 ,#302. to setup similar Ceph enviroments.

**Comment by yidong0635** [comment]
@pawelkax 
![image](https://user-images.githubusercontent.com/39082016/40896292-b5ad164e-67e6-11e8-9313-2431a6fb3e43.png)

**Comment by wanqunintel** [comment]
@yidong0635 would you add your SPDK commit id so that Pawel can refer to it? thanks.

**Comment by yidong0635** [comment]
follow #301 to create rbd ,  recreate rbd without error. maybe due to the method of ceph setup.

**Comment by pawelwod** [comment]
@wanqunintel  @yidong0635  what is status og this issue? Can you reproduce it? Is someone going to fix it?

**Comment by yidong0635** [comment]
what's your procedures to setup the ceph enviroment? I  can't reproduce it if follow my procedures to create rbd.
download spdk.
apt install ceph (ubantu)or dnf install ceph(fedora)
vim CONFIG : `ASAN=y`
`./configure --with-rbd `then` make && make install`
Create config.conf:
```
[Global]
[Ioat]
Disable Yes
```
`./scripts/setup.sh reset`
`NRHUGE=12288 ./script/setup.sh`
`./app/spdk_tgt/spdk_tgt -m 0x1 -p 0 -c config.conf -s 1024 -r /var/tmp/spdk.sock & spdk_tgt_pid=$!`
`./scripts/ceph/start.sh 127.0.0.1`
`ceph osd pool create rbd 128`
`rbd pool init rbd`
`rbd create foo --size 4096`
```
./scripts/rpc.py construct_rbd_bdev rbd foo 4096
./scripts/rpc.py -s /var/tmp/spdk.sock delete_bdev Ceph0
./scripts/rpc.py -s /var/tmp/spdk.sock construct_rbd_bdev rbd foo 4096
```

**Comment by pawelkax** [comment]
@yidong0635 Thanks for checking this issue. I also cannot reproduce this bug, so I decided to close it.
