### ISSUE TITLE
[nvmf_filesystem] Failure while removing the target partition

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2961]
# CI Intermittent Failure

From the kernel log it looks like the target got suddenly disconnected. 

```
[Mon Mar 27 17:11:42 2023] SGI XFS with ACLs, security attributes, scrub, quota, no debug enabled
[Mon Mar 27 17:11:42 2023] XFS (nvme0n1p1): Mounting V5 Filesystem
[Mon Mar 27 17:11:44 2023] XFS (nvme0n1p1): Ending clean mount
[Mon Mar 27 17:11:44 2023] XFS (nvme0n1p1): Unmounting Filesystem
[Mon Mar 27 17:11:45 2023] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] block nvme0n1: no available path - failing I/O
[Mon Mar 27 17:11:45 2023] Buffer I/O error on dev nvme0n1, logical block 130944, async page read
```

Actual test failing here:
```
00:05:23.477  ************************************
00:05:23.477  END TEST filesystem_xfs
00:05:23.477  ************************************
00:05:23.477   17:11:42	-- common/autotest_common.sh@1086 -- # xtrace_enable
00:05:23.477   17:11:42	-- target/filesystem.sh@86 -- # parted -s /dev/nvme0n1 rm 1
00:05:24.851  Error: Partition(s) 1 on /dev/nvme0n1 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
00:05:24.851    17:11:43	-- target/filesystem.sh@86 -- # trap - ERR
00:05:24.851    17:11:43	-- target/filesystem.sh@86 -- # print_backtrace
00:05:24.851    17:11:43	-- common/autotest_common.sh@1097 -- # [[ ehxBET =~ e ]]
00:05:24.851    17:11:43	-- common/autotest_common.sh@1099 -- # args=('0' '0' 'nvmf_filesystem_part' 'nvmf_filesystem_no_in_capsule' '--transport=tcp')
00:05:24.851    17:11:43	-- common/autotest_common.sh@1099 -- # local args
00:05:24.851    17:11:43	-- common/autotest_common.sh@1101 -- # xtrace_disable
00:05:24.851    17:11:43	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
00:05:24.851    17:11:43	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
00:05:24.851    17:11:43	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
00:05:24.851    17:11:43	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
00:05:24.851    17:11:43	-- common/autotest_common.sh@24 -- # set +x
00:05:24.851  ========== Backtrace start: ==========
00:05:24.851  
00:05:24.851  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/target/filesystem.sh:86 -> nvmf_filesystem_part(["0"])
00:05:24.851       ...
00:05:24.851     81  			run_test "filesystem_in_capsule_ext4" nvmf_filesystem_create "ext4" ${nvme_name}
00:05:24.851     82  			run_test "filesystem_in_capsule_btrfs" nvmf_filesystem_create "btrfs" ${nvme_name}
00:05:24.851     83  			run_test "filesystem_in_capsule_xfs" nvmf_filesystem_create "xfs" ${nvme_name}
00:05:24.851     84  		fi
00:05:24.851     85  	
00:05:24.851  => 86  		parted -s /dev/${nvme_name} rm 1
00:05:24.851     87  	
00:05:24.851     88  		sync
00:05:24.851     89  		nvme disconnect -n "nqn.2016-06.io.spdk:cnode1"
00:05:24.851     90  		waitforserial_disconnect "$NVMF_SERIAL"
00:05:24.851     91  	
00:05:24.851       ...
00:05:24.851  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/common/autotest_common.sh:1069 -> run_test(["nvmf_filesystem_no_in_capsule"],["nvmf_filesystem_part"],["0"])
00:05:24.851       ...
00:05:24.851     1064		timing_enter $test_name
00:05:24.851     1065		echo "************************************"
00:05:24.851     1066		echo "START TEST $test_name"
00:05:24.851     1067		echo "************************************"
00:05:24.851     1068		xtrace_restore
00:05:24.851     1069		time "$@"
00:05:24.851     1070		xtrace_disable
00:05:24.851     1071		echo "************************************"
00:05:24.851     1072		echo "END TEST $test_name"
00:05:24.851     1073		echo "************************************"
00:05:24.851     1074		timing_exit $test_name
00:05:24.851       ...
00:05:24.851  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/target/filesystem.sh:100 -> main(["--transport=tcp"])
00:05:24.851       ...
00:05:24.851     95  	
00:05:24.851     96  		killprocess $nvmfpid
00:05:24.851     97  		nvmfpid=
00:05:24.851     98  	}
00:05:24.851     99  	
00:05:24.851  => 100 	run_test "nvmf_filesystem_no_in_capsule" nvmf_filesystem_part 0
00:05:24.851     101 	run_test "nvmf_filesystem_in_capsule" nvmf_filesystem_part 4096
00:05:24.851     102 	
00:05:24.851     103 	nvmftestfini
00:05:24.851       ...
00:05:24.851  
00:05:24.851  ========== Backtrace end ==========
```

**Comment by jimharris** [comment]
I'm lost on this one.  Unfortunately the logs were culled, so we don't have any more info other than what was pasted above.

I suspect that the target crashed, resulting in the parted failing (and the messages in the kernel log), but that's just a guess.

Let's keep it open for a bit longer.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_103435.html

**Comment by jimharris** [comment]
OK, so build.log shows this (similar to original post):

```
00:06:13.498   23:54:31	-- target/filesystem.sh@43 -- # lsblk -l -o NAME
00:06:13.498   23:54:31	-- target/filesystem.sh@43 -- # grep -q -w nvme0n1p1
00:06:13.498  
00:06:13.498  real	0m3.654s
00:06:13.498  user	0m0.015s
00:06:13.498  sys	0m0.087s
00:06:13.498   23:54:31	-- common/autotest_common.sh@1079 -- # xtrace_disable
00:06:13.498   23:54:31	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:06:13.498   23:54:31	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:06:13.498   23:54:31	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:06:13.498   23:54:31	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:06:13.498   23:54:31	-- common/autotest_common.sh@25 -- # set +x
00:06:13.498  ************************************
00:06:13.498  END TEST filesystem_xfs
00:06:13.498  ************************************
00:06:13.498   23:54:31	-- common/autotest_common.sh@1095 -- # xtrace_enable
00:06:13.498   23:54:31	-- target/filesystem.sh@86 -- # parted -s /dev/nvme0n1 rm 1
00:06:14.869  Error: Partition(s) 1 on /dev/nvme0n1 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
00:06:14.869    23:54:32	-- target/filesystem.sh@86 -- # trap - ERR
00:06:14.869    23:54:32	-- target/filesystem.sh@86 -- # print_backtrace
00:06:14.869    23:54:32	-- common/autotest_common.sh@1106 -- # [[ ehxBET =~ e ]]
00:06:14.869    23:54:32	-- common/autotest_common.sh@1108 -- # args=('0' '0' 'nvmf_filesystem_part' 'nvmf_filesystem_no_in_capsule' '--transport=tcp')
00:06:14.869    23:54:32	-- common/autotest_common.sh@1108 -- # local args
00:06:14.869    23:54:32	-- common/autotest_common.sh@1110 -- # xtrace_disable
00:06:14.869    23:54:32	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:06:14.869    23:54:32	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:06:14.869    23:54:32	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:06:14.869    23:54:32	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:06:14.869    23:54:32	-- common/autotest_common.sh@25 -- # set +x
```

Note the timestamp here: `23:54:31`.  Now let's look at dmesg.log around that same time:

```
[Mon May  8 23:54:20 2023] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 10.0.0.2:4420
[Mon May  8 23:54:23 2023]  nvme0n1: p1
[Mon May  8 23:54:23 2023] block nbd1: Attempted send on invalid socket
[Mon May  8 23:54:23 2023] I/O error, dev nbd1, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 2
[Mon May  8 23:54:26 2023] block nbd0: Attempted send on invalid socket
[Mon May  8 23:54:26 2023] I/O error, dev nbd0, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 2
[Mon May  8 23:54:28 2023] EXT4-fs (nvme0n1p1): mounted filesystem with ordered data mode. Quota mode: none.
[Mon May  8 23:54:29 2023] EXT4-fs (nvme0n1p1): unmounting filesystem.
[Mon May  8 23:54:29 2023] BTRFS: device fsid 44d85058-36ff-4da2-bb0d-ab46bd5cf7bb devid 1 transid 6 /dev/nvme0n1p1 scanned by mkfs.btrfs (56417)
[Mon May  8 23:54:30 2023] BTRFS info (device nvme0n1p1): using crc32c (crc32c-intel) checksum algorithm
[Mon May  8 23:54:30 2023] BTRFS info (device nvme0n1p1): using free space tree
[Mon May  8 23:54:30 2023] BTRFS info (device nvme0n1p1): enabling ssd optimizations
[Mon May  8 23:54:30 2023] BTRFS info (device nvme0n1p1): checking UUID tree
[Mon May  8 23:54:32 2023] SGI XFS with ACLs, security attributes, scrub, quota, no debug enabled
[Mon May  8 23:54:32 2023] XFS (nvme0n1p1): Mounting V5 Filesystem
[Mon May  8 23:54:33 2023] XFS (nvme0n1p1): Ending clean mount
[Mon May  8 23:54:33 2023] XFS (nvme0n1p1): Unmounting Filesystem
[Mon May  8 23:54:35 2023] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
[Mon May  8 23:54:35 2023] block nvme0n1: no available path - failing I/O
[Mon May  8 23:54:35 2023] block nvme0n1: no available path - failing I/O
[Mon May  8 23:54:35 2023] Buffer I/O error on dev nvme0n1p1, logical block 64, async page read
```

This doesn't make sense to me, unless the timestamps between build.log and dmesg.log aren't aligned?  This says we unmounted the XFS partition at `23:54:33`, but the `parted` failure comes two seconds before that (which in the filesystem.sh script happens after the unmount).

**Comment by jimharris** [comment]
> This doesn't make sense to me, unless the timestamps between build.log and dmesg.log aren't aligned? This says we unmounted the XFS partition at `23:54:33`, but the `parted` failure comes two seconds before that (which in the filesystem.sh script happens after the unmount).

OK, I think there is a small 2.5-3 second discrepancy between the logs.  We can correlate them by looking at the mount/unmount messages in the build.log and dmesg.log.

Based on this, I don't think the target crashed.  I think we simply are waiting for an I/O to complete after the umount in `nvmf_filesystem_create`.  I suspect the umount itself generates an I/O that hasn't completed by time we try to remove the partition with `parted`.

I think next steps are for someone with access to internal SPDK CI (i.e. Intel) to rev a patch with `[RFC]` in the title that removes the `kill -0` and the two `lsblk` lines from `nvmf_filesystem_create`, put the filesystem.sh test in a loop that runs 100 times, then specifically run that patch on the nvmf-tcp-phy-autotest job.

Let's assume that reliably fails.  Put a `sync` before the `parted` and run it again.  If it consistently passes, we've proven this theory and have our fix.

Any takers?

**Comment by tomzawadzki** [comment]
[Bug scrub] There were some good next steps posted by Jim
> I think next steps are for someone with access to internal SPDK CI (i.e. Intel) to rev a patch with [RFC] in the title that removes the kill -0 and the two lsblk lines from nvmf_filesystem_create, put the filesystem.sh test in a loop that runs 100 times, then specifically run that patch on the nvmf-tcp-phy-autotest job.

@Marcin Suski, can you please take a look at the above ?

**Comment by masuski** [comment]
ok

**Comment by masuski** [comment]
> > This doesn't make sense to me, unless the timestamps between build.log and dmesg.log aren't aligned? This says we unmounted the XFS partition at `23:54:33`, but the `parted` failure comes two seconds before that (which in the filesystem.sh script happens after the unmount).
> 
> OK, I think there is a small 2.5-3 second discrepancy between the logs. We can correlate them by looking at the mount/unmount messages in the build.log and dmesg.log.
> 
> Based on this, I don't think the target crashed. I think we simply are waiting for an I/O to complete after the umount in `nvmf_filesystem_create`. I suspect the umount itself generates an I/O that hasn't completed by time we try to remove the partition with `parted`.
> 
> I think next steps are for someone with access to internal SPDK CI (i.e. Intel) to rev a patch with `[RFC]` in the title that removes the `kill -0` and the two `lsblk` lines from `nvmf_filesystem_create`, put the filesystem.sh test in a loop that runs 100 times, then specifically run that patch on the nvmf-tcp-phy-autotest job.
> 
> Let's assume that reliably fails. Put a `sync` before the `parted` and run it again. If it consistently passes, we've proven this theory and have our fix.
> 
> Any takers?

**Comment by masuski** [comment]
> I think next steps are for someone with access to internal SPDK CI (i.e. Intel) to rev a patch with `[RFC]` in the title that removes the `kill -0` and the two `lsblk` lines from `nvmf_filesystem_create`, put the filesystem.sh test in a loop that runs 100 times, then specifically run that patch on the nvmf-tcp-phy-autotest job.
> 
> Let's assume that reliably fails. Put a `sync` before the `parted` and run it again. If it consistently passes, we've proven this theory and have our fix.
> 
> Any takers?

Becouse of extended duration of tests I had to run them synchronous overnight.

In first case scenerio job was automatically aborded after 8h: https://spdkci.intel.com/job/nvmf-tcp-phy-autotest/47767/console

Second case failed after 7h with same error as above: 
 23:21:42  Error: Partition(s) 1 on /dev/nvme0n1 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
23:21:42    23:21:42	-- target/filesystem.sh@85 -- # trap - ERR
23:21:42    23:21:42	-- target/filesystem.sh@85 -- # print_backtrace
23:21:42    23:21:42	-- common/autotest_common.sh@1125 -- # [[ ehxBET =~ e ]]
23:21:42    23:21:42	-- common/autotest_common.sh@1127 -- # args=('4096' '4096' 'nvmf_filesystem_part' 'nvmf_filesystem_in_capsule' '--transport=tcp')
23:21:42    23:21:42	-- common/autotest_common.sh@1127 -- # local args
23:21:42    23:21:42	-- common/autotest_common.sh@1129 -- # xtrace_disable
23:21:42    23:21:42	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
23:21:42    23:21:42	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
23:21:42    23:21:42	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
23:21:42    23:21:42	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
23:21:42    23:21:42	-- common/autotest_common.sh@25 -- # set +x

**Comment by masuski** [comment]
I rerun tests with less iterations (33), both failed with the same error. We should consider other cause/fix.

**Comment by tomzawadzki** [comment]
Link to the patch above for reference https://review.spdk.io/gerrit/c/spdk/spdk/+/19302

**Comment by masuski** [comment]
@ksztyber logs ware deleted after 250 new builds. I reruned tests with "keep forever" flag.
Second (fix) case:
i=33 https://spdkci.intel.com/job/nvmf-tcp-phy-autotest/48068/
i=100 https://spdkci.intel.com/job/nvmf-tcp-phy-autotest/48077/

**Comment by masuski** [comment]
First case (repro):
i=33 https://spdkci.intel.com/job/nvmf-tcp-phy-autotest/48080/
i=100 https://spdkci.intel.com/job/nvmf-tcp-phy-autotest/48082/

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @artek-koltun. log: https://ci.spdk.io/public_build/autotest-per-patch_107703.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107775.html

**Comment by masuski** [comment]
https://spdkci.intel.com/job/nvmf-tcp-phy-autotest/49252/ reproduction run
https://spdkci.intel.com/job/nvmf-tcp-phy-autotest/49253/ fix run

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_109781.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_111384.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_111720.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_112198.html

**Comment by xjjx** [comment]
Another instance of this failure https://ci.spdk.io/public_build/autotest-spdk-v23.09-vs-dpdk-v22.11_193.html

**Comment by mikeBashStuff** [comment]
This issue has been happening more frequently at scale under new fedora38 image (which had been deployed this morning) so I went ahead and tried to tackle this one once again.

`parted`, `sgdisk`, `partprobe` etc. they all fall victim to the same issue here: they fail to perform re-read of the partition table via ioctl's `BLKRRPART`. To my understanding, on the kernel side, this falls into `disk_scan_partitions()` which checks if it can safely claim the device the scan was requested for. If that's not the case `bd_prepare_to_claim()` will report `EBUSY` accordingly. 

This indicates that prior our call to `parted` something holds the target block device. 

Quickly glancing through all open fds (when `parted` fails) shows that there are indeed holders which acquired access to our block device. Unsurprisingly, these are `udev-worker`(s) - considering that we flood kernel with udev events during this test it should be expected that we end up stepping on systemd-udevd's toes (and vice versa). 

The whole flow of `worker_process_device() -> worker_lock_whole_disk()` from `udev` seems to confirm that. In fact, comments in both functions indicate that either `udev` should back off or the external process should block and wait until the device is released by `udev` (looking through `/proc/locks` also confirms that the `udev-worker` is indeed holding said lock on the block device).

Considering all the above, I would suggest to either ignore this failure (for instance, `sgdisk` doesn't even bother to report failure with es != 0, it just spits proper warning) since the next step during the test is to simply disconnect from the target entirely. Or acquire lock of our own - this seems to be working fine; with proper locking in place the issue is basically gone, while without it, reproduction boils down to running the test couple of times in the loop.

https://review.spdk.io/gerrit/c/spdk/spdk/+/21022

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sarveshlanke. log: https://ci.spdk.io/public_build/autotest-per-patch_113686.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_113693.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_113694.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_113841.html

**Comment by mikeBashStuff** [comment]
@mmkayPL Please, make sure to rebase your series to slurp the workaround for this issue.
