### ISSUE TITLE
env_dpdk: Support disabling Huge Pages

### ISSUE THREAD

**Issue by epuertat** [spdk/spdk#2973]
# Sighting report

Launching DPDK's EAL with no Huge Pages (`--no-huge`) via `--env-context` fails. This setting is essential for unprivileged/sensitive environments (e.g.: rootless containers, testing/CI, ...).

## Expected Behavior

`nvmf_tgt --env-context=--no-huge` should init EAL without huge pages.

## Current Behavior

However, due to the automatic setting of `--huge-unlink`, it fails:

```
Starting SPDK v23.01 / DPDK 21.11.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --no-pci --huge-unlink --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --no-huge --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid19 ]
EAL: Option --huge-unlink cannot be specified together with --no-huge
```

## Possible Solution

1. Either detecting the `--no-huge` substring within the `--env-context` and not setting `--huge-unlink` accordingly:
 https://github.com/spdk/spdk/blob/acad335521de75778b7181f1c6bf16af2af2c6f5/lib/env_dpdk/init.c#L302-L314

1. Or making it a explicit option via a new `--no-huge` flag.

## Steps to Reproduce

1. `nvmf_tgt --env-context=--no-huge`

## Context (Environment including OS version, SPDK version, etc.)

SPDK v23.01 / DPDK 21.11.0 (UBI/CentOS 9 rootless containers)

**Comment by jimharris** [comment]
Thanks for the report @epuertat.  Can you try https://review.spdk.io/gerrit/c/spdk/spdk/+/17483?

**Comment by epuertat** [comment]
Reviewed! Thank you for the quick response, @jimharris!

**Comment by epuertat** [comment]
@jimharris could we reopen this issue? I'm not familiar with spdk's issue workflow.

I'm sorry for the late feedback, but I recently tested this for the first time, and I found that other options, automatically by SPDK, conflict with DPDK's `--no-huge` (e.g.: `--match-allocations`) or might be unnecessary (e.g.: `--base-virtaddr`, `--file-prefix`).

I already have a fix and plan to submit it asap.

Thanks!

**Comment by jimharris** [comment]
Hi @epuertat,

Let's reopen this issue.

It seems we should probably promote `--no-huge` to its own env_opts field, instead of continuing to require passing it through env-context.  But maybe that's for later, let's review your patch first.

-Jim

**Comment by epuertat** [comment]
Thank you very much @jimharris (and @sberbz)!

To add more context, if it helps, we're looking to deploy SPDK's `nvmf_tgt` containerized, and to make it more secure, non `privileged` and (if possible) without added `caps` (for the time being it needs `SYS_ADMIN`, for the hugepages mount, and `CAP_SYS_NICE` for the `set_mempolicy` syscall).

I'm not familiar with the legacy memory mode in DPDK. Would it be possible to run it on a simple malloc + Transparent Huge Pages instead of pre-allocated explicit Huge Pages?

**Comment by jimharris** [comment]
> Thank you very much @jimharris (and @sberbz)!
> 
> To add more context, if it helps, we're looking to deploy SPDK's `nvmf_tgt` containerized, and to make it more secure, non `privileged` and (if possible) without added `caps` (for the time being it needs `SYS_ADMIN`, for the hugepages mount, and `CAP_SYS_NICE` for the `set_mempolicy` syscall).
> 
> I'm not familiar with the legacy memory mode in DPDK. Would it be possible to run it on a simple malloc + Transparent Huge Pages instead of pre-allocated explicit Huge Pages?

This *should* work although I've not tried it myself.

If you run with `--no-huge`, DPDK automatically enables legacy memory mode.  This mode means that all memory is pre-allocated at application start.  It looks like there are only two calls to `set_mempolicy` - one in `eal_memalloc_alloc_seg_bulk` that doesn't get called in legacy mode (see check at top of function) and another in `map_all_hugepages` which shouldn't get called with huge pages disabled.

**Comment by epuertat** [comment]
Thanks, @jimharris! I assume that all pages will still be mem-locked on start, right? I'll have a look at DPDK!

BTW, I also had to swith IOVA to VA mode, since PA wasn't allowed.

**Comment by abhineet99** [comment]
Hi @epuertat , I'm trying to run nvmf target without hugepages. But looks like spdk is getting an address which is not 2mb aligned, any clue what might be off?

`sudo ./build/bin/nvmf_tgt --env-context='--no-huge --legacy-mem --log-level=eal,8' --iova-mode='va'

[2023-07-03 12:10:14.048938] Starting SPDK v23.05-pre git sha1 ca0c4dc / DPDK 22.11.1 initialization...
[2023-07-03 12:10:14.049119] [ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --no-huge --legacy-mem --log-level=eal,8 --iova-mode=va --base-virtaddr=0x200000000000 --file-prefix=spdk_pid18911 ]
EAL: lib.eal log level changed from notice to debug
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 0 on socket 0
EAL: Detected lcore 3 as core 0 on socket 0
EAL: Detected lcore 4 as core 0 on socket 0
EAL: Detected lcore 5 as core 0 on socket 0
EAL: Detected lcore 6 as core 0 on socket 0
EAL: Detected lcore 7 as core 0 on socket 0
EAL: Maximum logical cores by configuration: 128
EAL: Detected CPU lcores: 8
EAL: Detected NUMA nodes: 1
EAL: Static memory layout is selected, amount of reserved memory can be adjusted with -m or --socket-mem
EAL: Checking presence of .so 'librte_eal.so.23.0'
EAL: Checking presence of .so 'librte_eal.so.23'
EAL: Checking presence of .so 'librte_eal.so'
EAL: Detected static linkage of DPDK
EAL: No shared files mode enabled, IPC will be disabled
EAL: No shared files mode enabled, IPC is disabled
EAL: Selected IOVA mode 'VA'
EAL: Probing VFIO support...
EAL: IOMMU type 1 (Type 1) is supported
EAL: IOMMU type 7 (sPAPR) is not supported
EAL: IOMMU type 8 (No-IOMMU) is not supported
EAL: VFIO support initialized
EAL: Ask a virtual area of 0x2e000 bytes
EAL: Virtual area found at 0x200000000000 (size = 0x2e000)
EAL: Setting up physically contiguous memory...
EAL: Setting maximum number of open files to 20480
EAL: Ask a virtual area of 0xc1000 bytes
EAL: Virtual area found at 0x20000002e000 (size = 0xc1000)
EAL: Memseg list allocated at socket 0, page size 0x4kB
EAL: Ask a virtual area of 0x4000000 bytes
EAL: Virtual area found at 0x2000000ef000 (size = 0x4000000)
EAL: VA reserved for memseg list at 0x2000000ef000, size 4000000
EAL: No shared files mode enabled, IPC is disabled
EAL: Added 64M to heap on socket 0
EAL: TSC frequency is ~2400000 KHz
EAL: Main lcore 0 is ready (tid=7f72e249d9c0;cpuset=[0])
EAL: No shared files mode enabled, IPC is disabled
EAL: lib.telemetry log level changed from disabled to warning
TELEMETRY: No legacy callbacks, legacy socket not created
EAL: No PCI address specified using 'addr=<id>' in: bus=pci
EAL: Registering mem event callbacks not supported
[2023-07-03 12:10:14.183181] memory.c: 346:spdk_mem_register: *ERROR*: invalid spdk_mem_register parameters, vaddr=0x2000000ef000 len=67108864
[2023-07-03 12:10:14.184873] app.c: 738:spdk_app_start: *NOTICE*: Total cores available: 1
[2023-07-03 12:10:14.237121] thread.c: 331:_thread_lib_init: *ERROR*: spdk_msg_mempool creation failed
[2023-07-03 12:10:14.237191] reactor.c: 252:spdk_reactors_init: *ERROR*: Initialize spdk thread lib failed
[2023-07-03 12:10:14.283485] app.c: 741:spdk_app_start: *ERROR*: Reactor Initialization failed: rc = -12
EAL: No shared files mode enabled, IPC is disabled
EAL: No shared files mode enabled, IPC is disabled
EAL: No shared files mode enabled, IPC is disabled`

**Comment by epuertat** [comment]
Hi @abhineet99, I'm not very familiar with the legacy memory mode. Maybe @jimharris can help you here?

**Comment by jimharris** [comment]
> Hi @abhineet99, I'm not very familiar with the legacy memory mode. Maybe @jimharris can help you here?

With huge pages disabled, DPDK does not try to allocate memory with any kind of alignment restrictions.  It just does a regular malloc/calloc.

There's definitely some work needed here:

1) The memory maps are used for various types of address translation.  One is virtual to physical address translation.  That's not possible to do in this use case.  Yes, you could get "normal" memory via malloc, and then call VFIO ioctls on it to make it DMA-safe, but not in an unprivileged application.  It also wouldn't be as performant.  So I think we want to disable virtual-to-physical address translation completely when disabling huge pages.

2) There's also translation for RDMA - translating a virtual address to a key + offset pair.  RDMA can be done with non-huge page memory, and from unprivileged processes, but maybe this gets deferred to start.  If we defer it for now, that means we disable this mem_map as well, when huge pages are disabled.

3) Longer term if we want to support RDMA without huge pages, the SPDK userspace "page table" code would need to handle memory that isn't aligned on 2MB boundaries.  This has actually come up in other contexts too, for example, NVMe CMBs may not always be 2MB aligned (currently we will just lop off the parts that aren't aligned).

**Comment by abhineet99** [comment]
@jimharris my use case is to use tcp as the fabric, and not rdma. So I thought it would be possible as DMA is not required there. But configuring spdk with --without-rdma doesn't change anything.

**Comment by jimharris** [comment]
For anyone that wants to pick this issue up...

This issue is easily reproduced by running nvmf_tgt as `build/bin/nvmf_tgt --env-context "--legacy-mem -m 512 --no-huge".

To temporarily work around the issue for debugging purposes, change lib/env_dpdk/memory.c line 347 to return 0 instead of `-EINVAL`.

I did some very basic checks, it all seems to work fine.

I think we need a top-level SPDK command line option `--no-huge`.  It adds `--legacy-mem --no-huge` to DPDK command line.  Make the SPDK option require the -s (size) SPDK parameter, since in legacy-mem mode we need to specify how much memory will be allocated.

Add new env memory internal API (lib/env_dpdk/env_internal.h) called something like `mem_disable_huge_pages(void)`.  Init code calls this if `--no-huge` was specified, memory.c saves the state in a static global variable (true by default, false if the disable function is called).

mem_map functions need to always return failure with appropriate error message if huge pages are disabled.

spdk_mem_register should immediately return 0, with appropriate info message, if huge pages are disabled.

In legacy-mem mode, memory is not dynamically added or removed, but let's still a basic check just to make sure (it really shouldn't affect anything, even if such memory is added).  In memory_hotplug_cb, check if huge pages are disabled, and if so, add ERRLOG + assert(false).

Of course let's also add some nvme/tcp test that utilizes this functionality.  We should be able to use one of the existing target tests as-is, just with some parameter specifying no-huge mode.

**Comment by lukashino** [comment]
Hi @abhineet99 

found this thread by accident, I am not familiar with SPDK but running to be able to run DPDK app with --no-huge option I had to specify the `--socket-mem` argument (it is also mentioned in your output). 

I was then able to run dpdk-testpmd app without `--legacy-mem`/`--iova-mode='va'`
Note: I was running it directly on a physical machine, I can try it in a container.
