### ISSUE TITLE
SPDK rejects latest DPDK release 23.3.0

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2974]
Opened for tracking. This currently affects vs-dpdk jobs as `dpdk_pci_init()` rejects that particular version whenever the app starts. 

Example:
https://ci.spdk.io/results/autotest-spdk-master-vs-dpdk-main/builds/1883/archive/BlobFS-autotest/build.log

```
00:03:52.691  [2023-04-05 04:28:29.320558] Starting SPDK v23.05-pre git sha1 da7f0f98b / DPDK 23.03.0 initialization...
00:03:52.691  [2023-04-05 04:28:29.320704] [ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --huge-unlink --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid617465 ]
00:03:52.950  TELEMETRY: No legacy callbacks, legacy socket not created
00:03:52.950  [2023-04-05 04:28:29.400293] pci_dpdk.c:  44:dpdk_pci_init: *ERROR*: DPDK version 23.03.0 not supported.
00:03:52.950  [2023-04-05 04:28:29.400349] init.c: 489:spdk_env_dpdk_post_init: *ERROR*: pci_env_init() failed
00:03:52.950  [2023-04-05 04:28:29.400379] app.c: 350:app_setup_env: *ERROR*: Unable to initialize SPDK env
00:03:52.950  [2023-04-05 04:28:29.400445] app.c: 552:unclaim_cpu_cores: *ERROR*: Failed to unlink lock fd for core 0, errno: 2
```

**Comment by jimharris** [comment]
This should be fixed now with Konrad's series merged: https://review.spdk.io/gerrit/c/spdk/spdk/+/17480

Can you confirm and close?

**Comment by mikeBashStuff** [comment]
@jimharris The master-vs-dpdk-main builds look fine now, but we also have LTS-vs-dpdk-main spinning under CI - I am afraid that without backports to 23.01.x they will remain red.

**Comment by jimharris** [comment]
> @jimharris The master-vs-dpdk-main builds look fine now, but we also have LTS-vs-dpdk-main spinning under CI - I am afraid that without backports to 23.01.x they will remain red.

Ah, of course.  @KKaras169169 can you back port these patches back to v23.01.x branch?

**Comment by ksztyber** [comment]
Patches are up for review: https://review.spdk.io/gerrit/c/spdk/spdk/+/17599/1

**Comment by jimharris** [comment]
Patches merged.

Thanks @ksztyber and @KKaras169169!
