### ISSUE TITLE
[subsystem] subsystem_sort: 'depends_on_sorted' may be used uninitialized in this function

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2978]
# Sighting report

## Expected Behavior

No build errors

## Current Behavior

Build failure on some systems.  For instance, see:

https://swx-ci.mellanox.com/spdk-test/blue/organizations/jenkins/basic_test_spdk_upstream_ci/detail/basic_test_spdk_upstream_ci/47203/pipeline

## Possible Solution

Initialize `depends_on_sorted`, likely in the same place as `depends_on` is initialized.  That being said,  commit aaba5d9c9e8fca9925d5812030ff3ec9ba869fa3 recently touched this function.  If this change was intended to have no functional difference, it should have been implemented with `^`, not `||`.  With the change from OR to XOR, the additional initialization is not needed.

## Steps to Reproduce

Mellanox CI seems to consistently hit this with gcc 9.4.0 on Ubuntu 20.04 on aarch64. It does seem to be a legit issue.

```
[2023-04-12T04:12:06.835Z] C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
[2023-04-12T04:12:06.835Z] C linker for the host machine: cc ld.bfd 2.34
[2023-04-12T04:12:06.835Z] Host machine cpu family: aarch64
[2023-04-12T04:12:06.835Z] Host machine cpu: aarch64
```

## Context (Environment including OS version, SPDK version, etc.)

Last commit in master was 78df9be4492a0bc098a0c6f58fb342d9f13abecc. 

cc: @yidong0635

**Comment by shuhei-matsumoto** [comment]
Hi @mgerdts 

@jimharris wrote a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/17496 to fix this issue. Please take a look when you can.

**Comment by jimharris** [comment]
> Hi @mgerdts
> 
> @jimharris wrote a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/17496 to fix this issue. Please take a look when you can.

I revised one of the comments based on @benlwalker's feedback - @shuhei-matsumoto - can you review again and add your +2?  Thanks!

**Comment by jimharris** [comment]
Patch merged
