### ISSUE TITLE
[rocky8-vg-autotest] timeout in Waiting for domain to get an IP address

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2979]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/101557/archive/rocky8-vg-autotest/build.log

## Execution failed at

```
00:17:30.611  ==> default: Creating shared folders metadata...
00:17:30.611  ==> default: Starting domain.
00:17:33.143  ==> default: Waiting for domain to get an IP address...
00:32:55.352  ==> default: Removing domain...
00:32:55.352  /usr/lib/ruby/vendor_ruby/fog/core/wait_for.rb:9:in `block in wait_for': The specified wait_for timeout (2 seconds) was exceeded (Fog::Errors::TimeoutError)
00:32:55.352  	from /usr/lib/ruby/vendor_ruby/fog/core/wait_for.rb:6:in `loop'
00:32:55.352  	from /usr/lib/ruby/vendor_ruby/fog/core/wait_for.rb:6:in `wait_for'
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_101590.html

**Comment by mikeBashStuff** [comment]
The proper image was re-deployed on the affected VM hosts so the issue should be gone. If it pops up again, please feel free to reopen this issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_111441.html
