### ISSUE TITLE
SPDK_DTRACE_PROBE macros are not zero overhead when disabled

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2986]
# Sighting report

One of the ideas behind dtrace is that it has zero overhead when probes are not enabled.  SPDK's `SPDK_DTRACE_PROBE()` macros are not living up to that promise.

## Expected Behavior

`SPDK_DTRACE_PROBE` macros that are not enabled should appear as a single `nop` instruction.

This code source code:

```c
void
spdk_spin_destroy(struct spdk_spinlock *sspin)
{
        int rc;

        SPDK_DTRACE_PROBE1(spin_destroy, sspin);
```
Should generate this x64 assembly, which was generated with `DTRACE_PROBE1(spdk, spin_destroy, sspin)`.

```
(gdb) disassemble spdk_spin_destroy
Dump of assembler code for function spdk_spin_destroy:
   0x000000000042cfb6 <+0>:     push   %rbp
   0x000000000042cfb7 <+1>:     mov    %rsp,%rbp
   0x000000000042cfba <+4>:     sub    $0x20,%rsp
   0x000000000042cfbe <+8>:     mov    %rdi,-0x18(%rbp)
   0x000000000042cfc2 <+12>:    nop
```

## Current Behavior

Even when the probe is disabled, `spdk_get_ticks()` is called.

```
Dump of assembler code for function spdk_spin_destroy:
   0x000000000042cfb6 <+0>:     push   %rbp
   0x000000000042cfb7 <+1>:     mov    %rsp,%rbp
   0x000000000042cfba <+4>:     sub    $0x20,%rsp
   0x000000000042cfbe <+8>:     mov    %rdi,-0x18(%rbp)
   0x000000000042cfc2 <+12>:    call   0x44beef <spdk_get_ticks>
   0x000000000042cfc7 <+17>:    nop
```

## Possible Solution

Rework the way that probes are created so that `spdk_get_ticks()` is called in the probe, not before the probe.

## Steps to Reproduce

1. Add a probe as I described above
2. Configure with `--with-usdt`

## Context (Environment including OS version, SPDK version, etc.)

This was introduced by commit a4044e77d67c8d53179ac05b738a87dd25a41995, seemingly for a good reason.

**Comment by mgerdts** [comment]
It looks like it takes about 23 instructions on x64 to accomplish what should be one instruction.

```
(gdb) disassemble spdk_get_ticks
Dump of assembler code for function spdk_get_ticks:
   0x000000000044beea <+0>:     push   %rbp
   0x000000000044beeb <+1>:     mov    %rsp,%rbp
   0x000000000044beee <+4>:     call   0x445e0a <rte_get_timer_cycles>
   0x000000000044bef3 <+9>:     pop    %rbp
   0x000000000044bef4 <+10>:    ret
End of assembler dump.
(gdb) disassemble rte_get_timer_cycles
Dump of assembler code for function rte_get_timer_cycles:
   0x0000000000445e0a <+0>:     push   %rbp
   0x0000000000445e0b <+1>:     mov    %rsp,%rbp
   0x0000000000445e0e <+4>:     call   0x445e32 <rte_get_tsc_cycles>
   0x0000000000445e13 <+9>:     pop    %rbp
   0x0000000000445e14 <+10>:    ret
End of assembler dump.
(gdb) disassemble rte_get_tsc_cycles
Dump of assembler code for function rte_get_tsc_cycles:
   0x00000000005b3741 <+0>:     push   %rbp
   0x00000000005b3742 <+1>:     mov    %rsp,%rbp
   0x00000000005b3745 <+4>:     call   0x5b372f <rte_rdtsc>
   0x00000000005b374a <+9>:     pop    %rbp
   0x00000000005b374b <+10>:    ret
End of assembler dump.
(gdb) disassemble rte_rdtsc
Dump of assembler code for function rte_rdtsc:
   0x00000000005b372f <+0>:     push   %rbp
   0x00000000005b3730 <+1>:     mov    %rsp,%rbp
   0x00000000005b3733 <+4>:     rdtsc
   0x00000000005b3735 <+6>:     mov    %eax,-0x8(%rbp)
   0x00000000005b3738 <+9>:     mov    %edx,-0x4(%rbp)
   0x00000000005b373b <+12>:    mov    -0x8(%rbp),%rax
   0x00000000005b373f <+16>:    pop    %rbp
   0x00000000005b3740 <+17>:    ret
End of assembler dump.
```

**Comment by jimharris** [comment]
Hi @mgerdts,

Userspace trace points require a trap, so we purposely don't have these today in any performance critical code paths.  The places where they do exist don't execute frequently enough to even notice the spdk_get_ticks() calls.

I'm looking at the macro maze that is `sys/sdt.h`, but don't see a way yet to avoid evaluation of the spdk_get_ticks() argument when the tracepoint is not enabled.  I'd be happy to look into this further, but want to make sure we aren't optimizing something unnecessarily.

Now, if by some magic userspace trace points stopped requiring a trap, we would absolutely need to rethink this, mostly likely by ensuring we have SPDK_DTRACE_PROBE variants that don't auto-insert the spck_get_ticks() parameter.

-Jim

**Comment by jimharris** [comment]
We discussed this more on Slack.

The use case is for spdk_spin_lock statistics.  These spin locks are not acquired very frequently, so the extra overhead of the spdk_get_ticks() when SPDK is configured `--with-usdt` (but traces disabled) is negligible.

But it is a bit cleaner to provide variants that don't automatically collect the ticks.  Existing SPDK_DTRACE_PROBE points that want the ticks because they are used in conjunction with native SPDK tracepoints can use new SPDK_DTRACE_PROBE_TICKS variants.

https://review.spdk.io/gerrit/c/spdk/spdk/+/17669

-Jim
