### ISSUE TITLE
[spdkcli_vhost] Error in cmd: load_subsystem_config /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/config_bdev.json

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2988]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/102382/archive/vhost-autotest/build.log

## Execution failed at

```
00:12:02.171   02:33:56	-- spdkcli/vhost.sh@135 -- # sleep 2
00:12:04.070   02:33:58	-- spdkcli/vhost.sh@143 -- # /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/spdkcli_job.py ''\''load_subsystem_config /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/config_bdev.json'\''
00:12:04.070  '\''load_subsystem_config /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/config_vhost_scsi.json'\''
00:12:04.070  '\''load_subsystem_config /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/config_vhost_blk.json'\''
00:12:04.070  '\''/lvol_stores create lvs0 Malloc0'\'' '\''lvs0'\'' True
00:12:04.070  '\''/lvol_stores create lvs1 Malloc5'\'' '\''lvs1'\'' True
00:12:04.070  '\''/bdevs/logical_volume create lvol0 16 lvs0'\'' '\''lvs0/lvol0'\'' True
00:12:04.070  '\''/bdevs/logical_volume create lvol1 16 lvs0'\'' '\''lvs0/lvol1'\'' True
00:12:04.070  '
00:12:04.636  [2023-04-22 02:33:59.199205] bdev.c:7664:spdk_bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: Malloc1
00:12:04.636  [2023-04-22 02:33:59.207222] bdev.c:7664:spdk_bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: Malloc4
00:12:04.636  [2023-04-22 02:33:59.215242] bdev.c:7664:spdk_bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: Nvme0n1
00:12:04.636  [2023-04-22 02:33:59.215266] bdev.c:7664:spdk_bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: Nvme0n1
00:12:05.202  Executing command: ['load_subsystem_config /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/config_bdev.json', False]
00:12:05.202  Error in cmd: load_subsystem_config /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/config_bdev.json
00:12:05.202    02:33:59	-- spdkcli/vhost.sh@143 -- # trap - ERR
00:12:05.202    02:33:59	-- spdkcli/vhost.sh@143 -- # print_backtrace
00:12:05.202    02:33:59	-- common/autotest_common.sh@1104 -- # [[ ehxBET =~ e ]]
00:12:05.202    02:33:59	-- common/autotest_common.sh@1106 -- # args=()
00:12:05.202    02:33:59	-- common/autotest_common.sh@1106 -- # local args
00:12:05.202    02:33:59	-- common/autotest_common.sh@1108 -- # xtrace_disable
00:12:05.202    02:33:59	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:12:05.202    02:33:59	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:12:05.202    02:33:59	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:12:05.202    02:33:59	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:12:05.202    02:33:59	-- common/autotest_common.sh@25 -- # set +x
00:12:05.202  ========== Backtrace start: ==========
00:12:05.202  
00:12:05.202  in /var/jenkins/workspace/vhost-autotest/spdk/test/spdkcli/vhost.sh:143 -> main([])
00:12:05.202       ...
00:12:05.202     138 	'load_subsystem_config $testdir/config_vhost_blk.json'
00:12:05.202     139 	'/lvol_stores create lvs0 Malloc0' 'lvs0' True
00:12:05.202     140 	'/lvol_stores create lvs1 Malloc5' 'lvs1' True
00:12:05.202     141 	'/bdevs/logical_volume create lvol0 16 lvs0' 'lvs0/lvol0' True
00:12:05.202     142 	'/bdevs/logical_volume create lvol1 16 lvs0' 'lvs0/lvol1' True
00:12:05.202  => 143 	"
00:12:05.202     144 	check_match
00:12:05.202     145 	$spdk_clear_config_py clear_config
00:12:05.202     146 	rm -f $testdir/config.json
00:12:05.202     147 	rm -f $testdir/config_bdev.json
00:12:05.202     148 	rm -f $testdir/config_vhost_scsi.json
00:12:05.202       ...
00:12:05.202  
00:12:05.202  ========== Backtrace end ==========
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102382.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102374.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102380.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102371.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102366.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102367.html

**Comment by mgerdts** [comment]
My machine is not set up to be able to run this test easily.  It is a bit concerning that there are so many failures with my latest updates.  Note that this failure occurred in 7 out of 20 patches that I pushed, with some good runs in between.  Maybe there's a new test rig in the mix that has different timing than we've had in the past.  Maybe my code is busted in a way I can't immediately fathom.

Since it looks like aio may be in the mix, I also wonder if it could be that there's a missing `bdev_wait_for_examine`, like in #2980.

**Comment by jimharris** [comment]
I think this must be some kind of CI change/update. I was reviewing a long series of backports from @KKaras169169 earlier and saw this exact same failure in a bunch of those patches.

@karlatec @mikeBashStuff anything come to mind?

**Comment by mikeBashStuff** [comment]
Looks like the affected patches need a rebase. Please, see https://review.spdk.io/gerrit/c/spdk/spdk/+/17559.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102394.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102408.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_102420.html

**Comment by mgerdts** [comment]
I rebased. Prior to rebase, I was seeing this on about 30% of the commits.  After rebase, 0% of 21 commits.  Looks to be resolved.

**Comment by KKaras169169** [comment]
> I think this must be some kind of CI change/update. I was reviewing a long series of backports from @KKaras169169 earlier and saw this exact same failure in a bunch of those patches.
> 
> @karlatec @mikeBashStuff anything come to mind?

I think we could still locate a change that fixes this issue and potentially backport it to x23.01.x. Otherwise, we are going to be running into this problem every time we push patches to that branch.

**Comment by KKaras169169** [comment]
@mikeBashStuff thanks, I overlooked your comment. Still, do we backport that to v23.01.x?
