### ISSUE TITLE
PSDT caused cmd done with INVALID FILED

### ISSUE THREAD

**Issue by Gaowh** [spdk/spdk#2991]
# Sighting report
when sgl is supported, psdt always set to  2 in func nvme_pcie_qpair_build_metadata , even if ssd do not support.

## Expected Behavior
psdt should set to 1 ,if ssd support sgl(bit 01:00 in SGLS set to 10b), but don't support bit19 in SGLS( identify controller data structures)

##Current Behavior
psdt always set to 2, even ssd don't support bit19 in SGLS

## Possible Solution

1. before set psdt filed in cmd , check SGL Support(SGLS) in identify controller data structures first
![image](https://user-images.githubusercontent.com/10825744/233831129-117e6e6c-0e59-46f6-b9bf-1091fcf1273b.png)

## Steps to Reproduce
1. nvme ssd support sgl (sgls bit 01:00 in identify controller data structures);
3. but not support use of a MPTR containing an SGL Descriptor (sgls bit 19 in identify controller data structures);
4. format nvme ssd with 4k+64(or other lbaf with meta), and ms = 0;
5. send write cmd with md use  "spdk_nvme_ns_cmd_write_with_md"
6. check write cmd results

![image](https://user-images.githubusercontent.com/10825744/233830627-3174946a-86f5-40c0-b5c0-6766bd60ae2c.png)
![image](https://user-images.githubusercontent.com/10825744/233830657-f117a880-cc80-4882-ab81-789e98d2e24a.png)

## Context (Environment including OS version, SPDK version, etc.)
OS: Ubuntu 20.04.1
SPDK: 23.05

**Comment by ksztyber** [comment]
[Bug scrub] This indeed looks like a bug. @m-spiewak will take a look at this.

**Comment by m-spiewak** [comment]
@Gaowh The patch fixing this is prepared ([https://review.spdk.io/gerrit/c/spdk/spdk/+/18094/1]), could you please try it in your system with the SSD showing this issue?

**Comment by Gaowh** [comment]
> @Gaowh The patch https://review.spdk.io/gerrit/c/spdk/spdk/+/18094/1 fixing this is prepared, could please try it in your system with the SSD showing this issue?

I verified this patch,  look like the issue has been fixed @m-spiewak

**Comment by m-spiewak** [comment]
Thanks, @Gaowh

**Comment by jimharris** [comment]
Patches merged.  Thanks @m-spiewak!
