### ISSUE TITLE
[short-fuzz-autotest] vfio_fuzz failed due to deadly signal

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2992]
# Sighting report

In CI job `short-fuzz-autotest` test `vfio_fuzz` fails when testing with ASAN enabled with DEADLYSIGNAL.
https://ci.spdk.io/public_build/autotest-per-patch_102464.html
https://ci.spdk.io/results/autotest-per-patch/builds/102464/archive/short-fuzz-autotest/build.log

## Current Behavior

```
00:09:33.278  spdk_nvme_connect() failed for transport address '/tmp/vfio-user-0/domain/2'
00:09:33.278  [2023-04-24 08:37:59.813602] app.c: 844:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
00:09:33.278  AddressSanitizer:DEADLYSIGNAL
00:09:33.278  =================================================================
00:09:33.278  ==4130976==ERROR: AddressSanitizer: SEGV on unknown address 0x0000003f08a0 (pc 0x0000016de8fe bp 0x7f9a43e45e90 sp 0x7f9a43e45bf0 T3)
00:09:33.278  ==4130976==The signal is caused by a READ memory access.
00:09:33.535  llvm_vfio_fuzz: thread.c:1307: int spdk_thread_send_msg(const struct spdk_thread *, spdk_msg_fn, void *): Assertion `thread != NULL' failed.
00:10:00.091  /var/jenkins/workspace/short-fuzz-autotest/spdk/test/fuzz/llvm/vfio/run.sh: line 21: 4130976 Aborted                 (core dumped) $rootdir/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz -m $core -s $mem_size -P $output_dir/llvm/ -F $vfiouser_dir -c $vfiouser_cfg -t $timen -D $corpus_dir -Y $vfiouser_io_dir -r $fuzzer_dir/spdk$fuzzer_type.sock -Z $fuzzer_type
```
Full log:
https://ci.spdk.io/results/autotest-per-patch/builds/102464/archive/short-fuzz-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/102464/archive/short-fuzz-autotest/coredumps/index.html

## Steps to Reproduce

1. Prepare configuration file:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_FUZZER_SHORT=1
SPDK_TEST_FUZZER=1
SPDK_RUN_UBSAN=1
SPDK_RUN_ASAN=1
```
2. `./autorun.sh ~/autorun.conf`x

## Context (Environment including OS version, SPDK version, etc.)

Testing with https://review.spdk.io/gerrit/c/spdk/spdk/+/17143
based on SPDK master 737667e1551fe845cf7fbb681010f1bf6b6c53ec

**Comment by sberbz** [comment]
When build with --with-ocf there is more memory requirements. Here is a patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/18702

**Comment by tomzawadzki** [comment]
[Bug scrub] The patch out for review on top of latest SPDK is https://review.spdk.io/gerrit/c/spdk/spdk/+/18835. @sberbz There you mention working around and issue when OCF is enabled, could you please leave a bit more info what issue you are encountering ?

**Comment by sberbz** [comment]
The issue occurs when spdk is compiled with-ocf, spdk reports:
```
vfio_user_pci.c: 170:vfio_device_dma_map: *ERROR*: Failed to allocate memory map structure
```
,so I follow fix for a similar issue (22fa84f77a1b8184b3003c33044f6fba73f549e9) and increase memory for DPDK (-s option). This partially solve the problem but second vfio-user ctrlr (one that is used to send io while fuzzing) stuck during initialization.
Vfio-user ctrlr is waiting for NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY indefinitely, only issue with ctrlr that is reported by spdk is:
```
vfio_user.c:2292:handle_del_io_q: *ERROR*: /tmp/vfio-user-1/domain/2: I/O sqid:0 does not exist
```

**Comment by karlatec** [comment]
I've rebased my patch https://review.spdk.io/gerrit/c/spdk/spdk/+/17143/74 on top of https://review.spdk.io/gerrit/c/spdk/spdk/+/18835.

Deadly signal issue seems fixed, but fuzzer tests still fail on something else:
https://ci.spdk.io/public_build/autotest-per-patch_107465.html
https://ci.spdk.io/results/autotest-per-patch/builds/107465/archive/short-fuzz-phy-autotest/build.log
I am going to raise a separate issue for that.

@tomzawadzki  @ksztyber can you take a look at @sberbz patch so we can get it merged?

**Comment by tomzawadzki** [comment]
[Bug scrub] This issue is compounded by #2455, as it not OCF memory consumption is increased but ASAN too. 
Let's go ahead with merging https://review.spdk.io/gerrit/c/spdk/spdk/+/18835, but open a new one strictly related to OCF pool initialization.

**Comment by tomzawadzki** [comment]
[Bug scrub] @sberbz will open the issue regarding OCF.
