### ISSUE TITLE
nvmf_subsystem_add_listener return error when CONFIG_ARM64_64K_PAGES=y

### ISSUE THREAD

**Issue by peng6662001** [spdk/spdk#2994]
# Sighting report
I run the commands in the dir of spdk on Ampere Altra.
```
sudo scripts/setup.sh
rm ~/images/test-disk.raw
truncate ~/images/test-disk.raw -s 128M
mkfs.ext4  ~/images/test-disk.raw
killall reactor_0
sleep 2
./build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x1 &
sleep 2
sudo ./scripts/rpc.py nvmf_create_transport -t VFIOUSER
sudo rm -rf /tmp/nvme-vfio-user
sudo mkdir -p /tmp/nvme-vfio-user
sudo ./scripts/rpc.py bdev_aio_create ~/images/test-disk.raw test 512
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode -a -s test
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode test
sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode -t VFIOUSER -a /tmp/nvme-vfio-user -s 0
```
The last command returns error:
+ sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode -t VFIOUSER -a /tmp/nvme-vfio-user -s 0
[2023-04-25 09:14:12.193544] vfio_user.c:4454:nvmf_vfio_user_listen: *ERROR*: /tmp/nvme-vfio-user: error to mmap file /tmp/nvme-vfio-user/bar0: Invalid argument.
[2023-04-25 09:14:12.193687] nvmf.c: 684:spdk_nvmf_tgt_listen_ext: *ERROR*: Unable to listen on address '/tmp/nvme-vfio-user'

The relative code is:
```
lib/nvmf/vfio_user.c
nvmf_vfio_user_listen
  	endpoint->bar0_doorbells = mmap(NULL, NVMF_VFIO_USER_DOORBELLS_SIZE,
					PROT_READ | PROT_WRITE, MAP_SHARED, endpoint->devmem_fd, NVME_DOORBELLS_OFFSET);
```

It works well when CONFIG_ARM64_4K_PAGES=y.
How to resolve this issue?

./build/bin/nvmf_tgt -v
SPDK v23.05-pre git sha1 487069501

uname -a
Linux adam-ubuntu 6.3.0-rc4 #9 SMP Fri Apr 21 07:14:57 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by jimharris** [comment]
Hi @peng6662001,

vfio_user is currently only supported for 4K pages.  You may want to check with the vfio-user community at libvfio-user.slack.com on how to support alternate page sizes.

-Jim

**Comment by jlevon** [comment]
I don't think this has anything to do with (lib)vfio-user. The mmap() itself is failing, which is not related to the library or the protocol. @peng6662001 I would guess that you need NVMF_VFIO_USER_DOORBELLS_SIZE to be 64K-aligned. Please check that.

**Comment by jimharris** [comment]
> I don't think this has anything to do with (lib)vfio-user. The mmap() itself is failing, which is not related to the library or the protocol. @peng6662001 I would guess that you need NVMF_VFIO_USER_DOORBELLS_SIZE to be 64K-aligned. Please check that.

I don't think it's only `NVMF_VFIO_USER_DOORBELLS_SIZE` - will the migration data mmap have the same problem?  SPDK gets this length from vfio-user.

Sorry for the mixup @jlevon.  I agree SPDK is doing this mmap independently of vfio-user.  But I was under the assumption that vfio-user would need to do some amount of coordination between the target (i.e. SPDK) and the client (i.e. QEMU) on this.  Will QEMU just do the right thing if SPDK starts registering a 68KB BAR0 region (4K for register, 64K for doorbells)?  I wanted to avoid the submitter here getting the mmap to start working but then start having problems with QEMU.

**Comment by jlevon** [comment]
Yes, migration would need work, but that's generally not working right now.

Re qemu registering, not sure offhand.
