### ISSUE TITLE
Missing setup.py or pyproject.toml / Not having python package

### ISSUE THREAD

**Issue by ewaAdamska** [spdk/spdk#2997]
# Sighting report

Using your git repo subdirectories (like python/spdk/) as python packages is now not possible due to missing setup.py files. It would be nice to just use reference to your repo subdir in requirements.txt (or other dependency config)

## Expected Behavior

After adding such line to requirements.txt:
`spdk @ git+https://github.com/spdk/spdk.git#subdirectory=python/spdk` i would just install your code as a python package

## Current Behavior

If I do so I get an error:
`ERROR: spdk@ git+https://github.com/spdk/spdk.git#subdirectory=python/spdk from git+https://github.com/spdk/spdk.git#subdirectory=python/spdk (from -r requirements.txt (line 66)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

## Possible Solution

Adding simple setup.py to python/spdk subdirectory

## Steps to Reproduce

1. `pip install git+https://git+https://github.com/spdk/spdk.git#subdirectory=python/spdk`

## Context (Environment including OS version, SPDK version, etc.)

All newest.

**Comment by jimharris** [comment]
[Bug Scrub] @ksztyber could you take a look at this?

**Comment by ewaAdamska** [comment]
@ksztyber yes, I have just checked it out. It works fine. Great. Thanks for it :)
