### ISSUE TITLE
bdev/nvme example for (accelerated) file writing ?

### ISSUE THREAD

**Issue by repu1sion** [spdk/spdk#300]
the only bdev example is hardly integrated with fio.
even from "Block Device Layer Programming Guide" it is unclear - who should create a block device ?
If I have a single Samsung nvme in the system - would it be discovered with spdk_bdev_first() /next() or not?
Should I firstly call something like : "./scripts/rpc.py construct_nvme_bdev -b SAMSUNG -t pcie -a 0000:00:02.0" ?
But it doesn't work , because there is no a socket file.
Do I need all these config function calls like spdk_conf_read()? spdk_conf_first_section()?
But what is the config format and where is it described?
Can I finally store a data to something like file or the only option is BlobFS and for BlobFS the only option is RocksDB? 
Thanks.

**Comment by darsto** [comment]
Hi,
To understand the concept behind SPDK I suggest reading this doc -
http://www.spdk.io/doc/userspace.html
For bdevs there's a separate guide - http://www.spdk.io/doc/bdev.html - and
you'll find a ton more in http://www.spdk.io/doc/
D.

2018-05-16 16:05 GMT+02:00 repu1sion <notifications@github.com>:

**Comment by repu1sion** [comment]
I understand SPDK concept: drivers in userspace, polling instead of interrupts, kernel stack doesn't work. 
The question is - how via Bdev API I should create a block device for samsung nvme at 0000:00:02.0 ?

**Comment by pawelwod** [comment]
See the RPC call that call `spdk_bdev_nvme_create`

https://github.com/spdk/spdk/blob/08daa4477e8fd86269697be7354f4526e7d41678/lib/bdev/nvme/bdev_nvme_rpc.c#L85 

From other hand, we could expose this `spdk_bdev_nvme_create` to public API ;)

**Comment by pawelwod** [comment]
Before modifying or adding any code you can use existing `app/spdk_tgt/spdk_tgt` application to test if `construct_nvme_bdev` RPC call will create bdev or it fail for some reason. If succed you can got to the next steps.

Then, if you have any custom written code and you don't want to hack SPDK internals and move `spdk_bdev_nvme_create` declaration to public header under spdk/include you can do as follow:

1. Port you code to to `app/spdk_tgt/spdk_tgt` target application - don't remove code that parse cmd line options.
2.  Start this modified spdk_tgt application
3. All RPC methods should be available now in you application. Now you can call `construct_nvme_bdev` 
4. This is (not so) optional: create your own RPC method called eg `start_doing_some_work` that you can call to inform your application that it might do whatever you need to do on your samsung nvme bdev.

**Comment by jimharris** [comment]
It depends what you are trying to do.

If you’re wanting to run the bdev fio plugin, or the SPDK bdevperf utility, then RPCs won’t work – you’ll need to create a configuration file with an [Nvme] section to specify the NVMe SSD at 0000:00:02.0.

RPCs are possible if you’re wanting to use this SSD as the backing storage for iSCSI, NVMe-oF or vhost.  In these cases, you’ll start the associated target application which will create the Unix domain socket and start an RPC listener.  Then you can send this RPC to probe and attach the SSD with the SPDK userspace driver, and a bdev will be created for each namespace.  Then you can attach these bdevs as iSCSI LUNs, NVMe-oF namespaces or vhost storage targets (blk/scsi).

-Jim

**Comment by repu1sion** [comment]
Thanks, Pawel! That helps a lot.

Yes, after running app/spdk_tgt/spdk_tgt I was able to create bdev device with rpc.py

I'm trying to create an own app, with help of SPDK API, which will be able to do some parallel reading/writing faster with bdev/nvme than standard kernel driver does.

**Comment by xxks-kkk** [comment]
Hello, 

I'm new to the SPDK. I'm playing around with example program under `spdk/examples/bdev/hello_world/`. My goal is to build some program based on the underlying NVMe SSD. However, I run into some issues:

1. I fire up `spdk/app/spdk_tgt/spdk_tgt` and tried to use `rpc.py` to create a NVMe bdev as follows:

```
$ sudo ./rpc.py construct_nvme_bdev -b hzy -t pcie -a 0000:02:00.0
hzyn1
```

I think I can run the example program as `sudo ./hello_bdev -b hzyn1` but I got the following error:

```
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 --legacy-mem --file-prefix=spdk_pid10426 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid10426/mp_socket
EAL: No free hugepages reported in hugepages-2048kB
EAL: No free hugepages reported in hugepages-1048576kB
EAL: FATAL: Cannot get hugepage information.
EAL: Cannot get hugepage information.
Failed to initialize DPDK
app.c: 498:spdk_app_setup_env: *ERROR*: Unable to initialize SPDK env
hello_bdev.c: 250:main: *ERROR*: ERROR starting application
```

I tried to run `sudo ./hello_bdev -c bdev.conf -b Malloc0` and got the same error message. How do I fix this?

2. If I write a program using underlying NVMe SSD, which interface I should use? `bdev.h` or `bdev_module.h` or `bdev_nvme.h`?  In other words, how do I utilize the block layer abstraction for NVMe?

3. Is there any performance difference between using NVMe block layer interface and `nvme.h` interface with custom block interface?

Thanks much!

**Comment by xxks-kkk** [comment]
I followed the [guide](http://www.spdk.io/doc/bdev.html#bdev_config_nvme) and do the following:

```
[window1]
$ sudo ./spdk_tgt

[window2]
$ sudo ./rpc.py construct_nvme_bdev -b NVMe1 -t PCIe -a 0000:02:00.0
NVMe1n1
$ sudo ./rpc.py get_bdevs
[
  {
    "num_blocks": 2344225968, 
    "name": "NVMe1n1", 
    "claimed": false, 
    "driver_specific": {
      "nvme": {
        "trid": {
          "trtype": "PCIe", 
          "traddr": "0000:02:00.0"
        }, 
        "ns_data": {
          "id": 1
        }, 
        "pci_address": "0000:02:00.0", 
        "vs": {
          "nvme_version": "1.0"
        }, 
        "ctrlr_data": {
          "firmware_revision": "8EV10171", 
          "serial_number": "CVCQ5176004B1P2BGN", 
          "oacs": {
            "ns_manage": 0, 
            "security": 0, 
            "firmware": 1, 
            "format": 1
          }, 
          "vendor_id": "0x8086", 
          "model_number": "INTEL SSDPEDMW012T4"
        }, 
        "csts": {
          "rdy": 1, 
          "cfs": 0
        }
      }
    }, 
    "supported_io_types": {
      "reset": true, 
      "nvme_admin": true, 
      "unmap": true, 
      "read": true, 
      "write_zeroes": true, 
      "write": true, 
      "flush": true, 
      "nvme_io": true
    }, 
    "qos_ios_per_sec": 0, 
    "block_size": 512, 
    "product_name": "NVMe disk", 
    "aliases": []
  }
]
```

However, when `./spdk_tgt` is running, `hello_bdev.c` will lead to errors

```
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 --legacy-mem --file-prefix=spdk_pid24060 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid24060/mp_socket
EAL: No free hugepages reported in hugepages-2048kB
EAL: No free hugepages reported in hugepages-1048576kB
EAL: FATAL: Cannot get hugepage information.
EAL: Cannot get hugepage information.
Failed to initialize DPDK
app.c: 498:spdk_app_setup_env: *ERROR*: Unable to initialize SPDK env
/home/zeyuanhu/rustfs/examples/hello_nvme_bdev/hello_nvme_bdev.c: 233:main: *ERROR*: ERROR starting application
```

If I terminate the `spdk_tgt` (`sudo ./rpc.py kill_instance 9`), I can run `hello_bdev.c`. However,  if I run `hello_bdev.c` like

```
$ sudo ./hello_bdev -c bdev.conf -b NVMe1n1
```
with `bdev.conf` looks like

```
[Passthru]
  PT Malloc1 PT0
[Malloc]
  NumberOfLuns 2
  LunSizeInMB  16
[Nvme]
  TransportID "trtype:PCIe traddr:0000:02:00.0" NVMe1n1
```

I got the error that `NVMe1n1` is not found

```
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 --legacy-mem --file-prefix=spdk_pid24265 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid24265/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 594:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
vbdev_passthru.c: 389:vbdev_passthru_init: *NOTICE*: conf parse matched: Malloc1
vbdev_passthru.c: 493:vbdev_passthru_register: *NOTICE*: Match on Malloc1
vbdev_passthru.c: 527:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x2089eb0
vbdev_passthru.c: 538:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 549:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 560:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 561:vbdev_passthru_register: *NOTICE*: created pt_bdev for: PT0
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
/home/zeyuanhu/rustfs/examples/hello_nvme_bdev/hello_nvme_bdev.c: 135:hello_start: *NOTICE*: Successfully started the application
/home/zeyuanhu/rustfs/examples/hello_nvme_bdev/hello_nvme_bdev.c: 144:hello_start: *ERROR*: Could not find the bdev: NVMe1n1
app.c: 678:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
/home/zeyuanhu/rustfs/examples/hello_nvme_bdev/hello_nvme_bdev.c: 233:main: *ERROR*: ERROR starting application
```

If I restart `spdk_tgt` and run `sudo ./rpc.py get_bdevs`, I cannot see any bdevs any more (i.e. no `NVM1e1`). 

I'm guessing there is no way to keep bdevs persistent (a runtime information that is kept at `spdk_tgt` side) and if I want to create a NVMe block device, I have to do it at the runtime. However, from @pawelwod answer, it seems like there is no public API available by creating a NVMe device inside a program without invoking `spdk_tgt`.  I need to expose `construct_nvme_bdev` to the public by hacking the internal SPDK. Do I understand correctly?

I think there are two types of programs here: one is leveraging `spdk_tgt` and the other one is similar to `hello_bdev.c`. Doing `spdk_tgt` way requires the program separate its logic into server part and application part. I need to modify `spdk_tgt` to incorporate the server part. Basically, the program with the application part sends out the request and the server part inside `spdk_tgt` knows how to handle it.

For a program like `hello_bdev.c`, it does everything inside one program. Overall, I really like `hello_bdev.c` style if I know how I can create a NVMe block device whether beforehand or during the runtime and interact with it?

Thanks much!

**Comment by xxks-kkk** [comment]
I printout all the bdev names in `hello_bdev.c` and I find a bdev named `Nvme01n1`. Maybe this is created from some of the previous commands mentioned above. How can I verify this is this NVMe physical SSD? Where does `Nvme01n1` name come from?

Sorry for the multiple posts. 

Thanks!

**Comment by xxks-kkk** [comment]
I'm also wondering if `bdev_nvme` module supports the operations like requesting a logical block? Can I think about NVMe bdev as a device that directly read and write into a certain block? I think NVMe driver (`nvme.h`) allows me to directly read or write to a block. What's the difference between NVMe bdev and NVMe driver? 

Thanks much!

**Comment by nmarusha** [comment]
Hi Zeyuan,

Using the NVMe BDEV instead of the NVMe driver directly allows you to utilize other block device functionality. For example, SPDK has implemented virtual block devices that can be stacked on top of the physical BDEVs like the NVMe driver. A couple examples are: logical volumes (for carving up SSDs to look like more SSDs of smaller sizes), pooled volumes (currently RAID 0 and experimental), QoS, etc. If you have written to the BDEV API, you can also utilize other physical BDEVs, without rewriting your code, if you want to instead of write to an NVMe SSD but rather write to say an Optane DIMM or if you want talk to a SAS or SATA device you can use your Lib AIO BDEV or even if you would rather write to a Ceph cluster you can use the Ceph BDEV module.

So, the BDEV abstraction actually provides a great deal of power to those that opt to use it.

Thanks for the questions and there’s no problem with sending multiple emails. ☺

Thanks,
Nate

**Comment by benlwalker** [comment]
@xxks-kkk - I think the confusion here is that you're running both the SPDK target application and the hello_bdev application at the same time and they're both configured to claim all available huge pages unless told otherwise. You don't need to be running these two applications at the same time - they don't interact with one another.

The hello_bdev example application is configured via a configuration file currently. You create a configuration file and then run

~~~
sudo ./examples/bdev/hello_world/hello_bdev -c your_config.conf
~~~

There is an example configuration file in `examples/bdev/hello_world/bdev.conf` specifically for this example, and more in `etc/spdk/` that are heavily commented. SPDK is currently going through a bit of a transformation to be driven primarily by JSON-RPC (and JSON config files), but the hello_bdev example hasn't been converted yet.

The other application you were trying to run - `spdk_tgt` - is a unified iSCSI/NVMe-oF/vhost target. That has been converted to be configured by JSON-RPC, so you can start it up with essentially no parameters and then use `scripts/rpc.py` to send it configuration commands. The two applications don't depend on one another.

**Comment by xxks-kkk** [comment]
@benlwalker Thanks for the detailed response. I'm wondering how can I configure the underlying hardware ("they're both configured to claim all available huge pages unless told otherwise") so that I can have both applications running? In other words, I want to be part of my logical blocks to be managed by the JSON-RPC approach and part of the blocks managed in a similar style as "hello_bdev.c"? Do I need to use `spdk_bdev_part` related object to add one virtual device layer on top of my physical device? Will that introduces extra overhead?

Thanks much!

**Comment by benlwalker** [comment]
Run `sudo ./examples/bdev/hello_world/hello_bdev -h` to see the command line options. This is the option you need:

```
-s  --mem-size <size> memory size in MB for DPDK (default: all hugepage memory)
```
If you limit it to claim, say, half of your reserved hugepages on each application you can run both at the same time.

In an upcoming SPDK release we'll be moving to dynamic memory management so by default applications will claim 0 hugepages instead of all of them, and take them as they need them instead. Then you won't have to worry about this.

**Comment by xxks-kkk** [comment]
Hello @benlwalker 

I tried the command, I got the same error messages for `spdk_agt` and `hello_bdev`:

```
$ sudo ./hello_bdev --mem-size 100
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 -m 100 --legacy-mem --file-prefix=spdk_pid27703 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid27703/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 594:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
bdev.c: 762:spdk_bdev_initialize: *ERROR*: create rbuf small pool failed
subsystem.c: 120:spdk_subsystem_init_next: *ERROR*: Init subsystem bdev failed
app.c: 678:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
hello_bdev.c: 250:main: *ERROR*: ERROR starting application

$ sudo ./spdk_tgt --mem-size 100
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 -m 100 --legacy-mem --file-prefix=spdk_pid27646 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid27646/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 594:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
bdev.c: 762:spdk_bdev_initialize: *ERROR*: create rbuf small pool failed
subsystem.c: 120:spdk_subsystem_init_next: *ERROR*: Init subsystem bdev failed
app.c: 678:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
```

I figured my HUGEPAGES may not be allocated, so I run `sudo HUGEMEM=4096 scripts/setup.sh`, which probably what @pawelwod suggested. I still hit the same errors. However, if I don't specify `--mem-size` parameter, there will be no problem for both programs.

Thanks!

**Comment by benlwalker** [comment]
The -s parameter is the memory in MB, not the number of hugepages. You just didn't give the program enough memory to actually run. Try giving it 1024 MB.

**Comment by nmarusha** [comment]
Sort of. But, let me completely open, I’m no longer a developer. I’m the lucky person who is responsible for the SW organization that does SPDK. So, I’m relatively sure I know how this probably works, but I would definitely be guessing and the last thing I want to do is lead you in the wrong direction. So, someone else will need to give an answer.

Thanks,
Nate

**Comment by jimharris** [comment]
This issue seems to have diverted from the original submission.

Closing this issue - if there's something here that warrants further discussion, please submit a question on the mailing list.  Thanks!
