### ISSUE TITLE
NVMe-oF RDMA Latency Regression for Target and Initiator

### ISSUE THREAD

**Issue by kgodzwox** [spdk/spdk#3012]
# Sighting report

Latency regression detected on [performance.spdk.io](https://performance.spdk.io/d/upDz4sOVz/spdk-nvme-of-rdma-performance?orgId=1&from=now-90d&to=now&var-cpus=4&var-qd=64&var-rw=randread&refresh=5s).

Issue noted in increased latency for the target and initiator (randread, randrw and randwrite).

## Randread
![RDMA-regression-randread](https://github.com/spdk/spdk/assets/85180036/32f543a2-0965-4b89-97d3-df4c85164028)

Before avg. latency: 

- SPDK Target Latency (w. Kernel Init): 10.4 µs
- SPDK Initiator Latency (w. SPDK Target): 4.64 µs

After avg. latency:

- SPDK Target Latency (w. Kernel Init): 11.0 µs
- SPDK Initiator Latency (w. SPDK Target): 4.75 µs

## Randrw
![RDMA-regression-randrw](https://github.com/spdk/spdk/assets/85180036/34adc6b3-3d4e-4ae6-a3f6-1ed370baf99e)

Before avg. latency: 

- SPDK Target Latency (w. Kernel Init): 10.1 µs
- SPDK Initiator Latency (w. SPDK Target): 4.48 µs

After avg. latency:

- SPDK Target Latency (w. Kernel Init): 10.8 µs
- SPDK Initiator Latency (w. SPDK Target): 4.56 µs

## Randwrite
![RDMA-regression-randwrite](https://github.com/spdk/spdk/assets/85180036/1476d8b2-9c69-4664-988e-16f48aec5be6)

Before avg. latency: 

- SPDK Target Latency (w. Kernel Init): 9.06 µs
- SPDK Initiator Latency (w. SPDK Target): 4.01 µs

After avg. latency:

- SPDK Target Latency (w. Kernel Init): 9.83 µs
- SPDK Initiator Latency (w. SPDK Target): 4.04 µs

In detail, change between commits looks like:
![RDMA-regression](https://github.com/spdk/spdk/assets/85180036/de387373-0094-4089-b28d-a1708fdc6693)

The last good test result was with SPDK@1ae6a83a and the first bad result was with SPDK@1eb06bd6.
Further bisecting leads to SPDK@b41efae2 as a first faulty commit.

## Expected Behavior

N/A

## Current Behavior

N/A

## Context (Environment including OS version, SPDK version, etc.)

SPDK SPDK@b41efae2

**Comment by kgodzwox** [comment]
I did some tests but I'm not sure if they are conclusive because the differences are not very visible.
Used commits:
good: 1ae6a83aa562f6ad5042fba8c78032e6d3e73e44
bad: b41efae2c6c9328fc90c8a7f2afe692f977e4ebf
master: 0a06a6abdc07504644b959a9491b2ba146a4ed28
revert: from https://review.spdk.io/gerrit/c/spdk/spdk/+/17989

Parts of the FIO config:
```
 "target": {
    "mode": "spdk",
```
```
  "initiator1": {
    "mode": "kernel",
```
```
  "fio": {
    "bs": ["4k"],
    "qd": [1],
    "rw": ["randread"],
    "rwmixread": 70,
    "run_time": 20,
    "ramp_time": 0,
    "run_num": 10,
    "num_jobs": 1
  }

```
(Changed `rw` to `randread`, `randrw` or `randwrite` accordingly)


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


## First stage
First   stage| 10runs, 20s,   1CPU     SPDK+Kernel | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 | Run 7 | Run 8 | Run 9 | Run 10 | avg
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
doc/distributions:   don't mention Fedora version      (1ae6a83aa562f6ad5042fba8c78032e6d3e73e44) | randread | 11.1544359850 | 11.1619405180 | 11.1992249930 | 11.1652812190 | 11.2068728250 | 11.2070730270 | 10.8962162820 | 10.9785638130 | 11.0669975020 | 11.2892453620 | 11.1325851526
  | randwrite | 9.8499551640 | 9.9387283320 | 10.1281777500 | 9.8666199560 | 10.0658882670 | 9.9288497980 | 9.9431734640 | 9.8805602190 | 9.7943063050 | 10.0746520830 | 9.9470911338
  | randrw | 11.2953436970 | 11.0350585410 | 11.3615504460 | 11.1904800990 | 11.2774486230 | 11.3884613590 | 11.3875921760 | 10.8567579680 | 11.2424693810 | 11.2912555860 | 11.2326417876
  |   |   |   |   |   |   |   |   |   |   |   |  
refs/heads/master | randread | 11.0433506290 | 10.9764710950 | 11.0110962030 | 11.1325069940 | 11.0533758040 | 10.7612766850 | 11.1077069800 | 11.1775681570 | 11.0370506120 | 10.7807983920 | 11.0081201551
  | randwrite | 9.7974146090 | 9.9171084140 | 9.8593559980 | 9.6279574070 | 9.9883406240 | 9.8548850490 | 9.6887867720 | 9.8306156000 | 9.7004239630 | 9.7604546150 | 9.8025343051
  | randrw | 11.3838195440 | 11.2976466020 | 11.1700928010 | 11.2994129790 | 11.2552358170 | 11.2607213720 | 11.2958128510 | 11.2781785480 | 11.1142962470 | 11.2103240140 | 11.2565540775
  |   |   |   |   |   |   |   |   |   |   |   |  
accel: add support for xor     (b41efae2c6c9328fc90c8a7f2afe692f977e4ebf) | randread | 11.2450980100 | 11.2886698660 | 11.0307377590 | 11.2604325590 | 11.1028355990 | 10.9933358550 | 11.2291858910 | 11.2344083530 | 10.9942931500 | 11.2270347760 | 11.1606031818
  | randwrite | 9.8492991220 | 10.0100436590 | 10.1972605870 | 10.1135012780 | 10.1686593030 | 10.1734938390 | 9.9599219750 | 9.9525995260 | 9.9891043070 | 9.7572490560 | 10.0171132652
  | randrw | 11.3034453110 | 11.3248032970 | 11.3947289710 | 11.2036735710 | 11.3937482390 | 11.4034066980 | 11.1711873050 | 11.2394272320 | 11.2466297120 | 11.2500865230 | 11.2931136859

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


## Second   stage
Second   stage | 10runs, 20s,   1CPU     SPDK+Kernel | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 | Run 7 | Run 8 | Run 9 | Run 10 | avg
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
doc/distributions:   don't mention Fedora version      (1ae6a83aa562f6ad5042fba8c78032e6d3e73e44) | randread | 11.1855019320 | 11.0743465420 | 11.0280634120 | 11.2438643480 | 10.9624388190 | 11.0831811060 | 11.0148403760 | 11.0241393810 | 11.0806388720 | 11.1572514040 | 11.0854266192
  | randwrite | 9.6573086820 | 9.6825798830 | 9.7770918830 | 9.7009080760 | 9.5320145100 | 9.9698415950 | 9.6734601490 | 9.8060904150 | 9.8107069890 | 9.7641228890 | 9.7374125071
  | randrw | 11.3665931090 | 11.3063765730 | 11.2603590960 | 11.2617792960 | 11.2727188420 | 11.2978849410 | 11.0710748530 | 11.1309931770 | 11.1694739050 | 11.2251099280 | 11.2362363720
  |   |   |   |   |   |   |   |   |   |   |   |  
refs/heads/master | randread | 11.1329848020 | 11.3434928950 | 11.2461090650 | 11.1576873820 | 11.2843566530 | 11.2478028530 | 11.2491586230 | 11.1812271510 | 11.1753044930 | 11.2342608840 | 11.2252384801
  | randwrite | 9.8703453210 | 9.9139786520 | 9.9483667200 | 9.5668973310 | 9.9516061720 | 9.8422405960 | 9.9305945410 | 9.8807882580 | 9.8888092920 | 9.5898567630 | 9.8383483646
  | randrw | 11.3281002530 | 11.3122533910 | 11.3140408180 | 11.3564471150 | 11.3019793620 | 11.3052098600 | 11.2650880520 | 11.3245917140 | 11.0813183490 | 11.0559172600 | 11.2644946174
  |   |   |   |   |   |   |   |   |   |   |   |  
accel: add support for xor     (b41efae2c6c9328fc90c8a7f2afe692f977e4ebf) | randread | 11.2952863020 | 11.1651965570 | 11.1559111740 | 11.2322398170 | 11.2315918210 | 11.1998716830 | 11.2010255370 | 11.1105826500 | 11.2481886460 | 11.1332909620 | 11.1973185149
  | randwrite | 9.8712223050 | 10.0424712400 | 9.7419445750 | 9.8540732080 | 9.7538995680 | 9.8498244360 | 9.8431412180 | 9.7100845710 | 9.8718156260 | 9.7382662010 | 9.8276742948
  | randrw | 11.3824116390 | 11.2812420850 | 11.3809447190 | 11.2285419170 | 10.8481789250 | 11.1964702610 | 11.4166001220 | 11.2879648190 | 11.3887266630 | 11.3223927710 | 11.2733473921


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Revert   stage 1 and 2 | 10runs, 20s,   1CPU     SPDK+Kernel | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 | Run 7 | Run 8 | Run 9 | Run 10 | avg
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | randread | 11.2736374460 | 10.8653924560 | 11.0274947730 | 10.9086175760 | 11.0812635790 | 10.8909948030 | 10.8940394180 | 11.0869611140 | 11.0079685110 | 11.0225714970 | 11.0058941173
  | randwrite | 9.7337047810 | 9.4280662950 | 10.0122072590 | 9.9587569650 | 9.6025084010 | 9.8720612630 | 9.8818736120 | 9.8864049430 | 9.8095708290 | 9.6921887540 | 9.7877343102
  | randrw | 11.3197126730 | 10.9953497640 | 11.0744688760 | 11.0359271910 | 11.0952412190 | 10.9811919220 | 11.3271293040 | 11.3933048120 | 10.9439493450 | 11.1539163950 | 11.1320191501
  |   |   |   |   |   |   |   |   |   |   |   |  
  | randread | 10.8328670010 | 10.8010956450 | 11.0922526250 | 10.9684430760 | 10.8913498490 | 10.8673483020 | 11.1545599970 | 11.2601893810 | 10.9818103950 | 11.1860523950 | 11.0035968666
  | randwrite | 9.7141310240 | 9.7058137730 | 9.9001482620 | 9.8640456890 | 9.8453490560 | 9.8159356820 | 9.9632789820 | 9.7811479550 | 9.7776171030 | 9.8090735040 | 9.8176541030
  | randrw | 11.3580918230 | 11.1415724990 | 11.2138723140 | 11.1003194150 | 11.4197120760 | 11.2869947490 | 11.3042446800 | 11.3631319040 | 10.9746390110 | 11.3404751120 | 11.2503053583

</body>

</html>

## First stage
![image](https://github.com/spdk/spdk/assets/85180036/becfb359-fc2a-4208-b5f6-41a66050ea29)
![image](https://github.com/spdk/spdk/assets/85180036/87d950c2-4739-4f15-b4fc-fdbd073171e8)
![image](https://github.com/spdk/spdk/assets/85180036/24b9888c-50d4-4a74-9166-d9a5121c7bb9)

## Second stage
![image](https://github.com/spdk/spdk/assets/85180036/cd0a10f5-e3f0-49de-a9f6-f565d33faadc)
![image](https://github.com/spdk/spdk/assets/85180036/d346e14d-e594-4f3c-a042-2f59a8245ce6)
![image](https://github.com/spdk/spdk/assets/85180036/024a31cc-5fad-4579-88e4-0fb33259184d)

**Comment by tomzawadzki** [comment]
[Bug scrub] The faulty patch is unlikely to be the actual culprit, with data not being so reliable when bisecting we need track down more likely candidate. @jimharris will take a look at patches between Feb 20-22 and provide a list of potential patches for @kgodzwox to test.

**Comment by jimharris** [comment]
```
% git log --oneline --since="2023/02/17" --until="2023/02/26"
2b772dbbb ut/vbdev_lvol: examine multiple lvols
fd7641d57 bdev/lvol: retry lvol open if it fails due to insufficient resources
0194aa5bd bdev/lvol: eliminate grow examine code duplication
f64fe6fe3 bdev/lvol: remove _vbdev_lvol_examine_close_cb
03e2374c9 test/nvme/cmb: Use get-pmr as fallback
b0107e8cf scripts/get-pmr: Use pci_bus_cache[@]
843606d7c scripts/get-pmr: Adjust BAR2 lookup
d254a3b92 bdevperf: Random map for picking I/O offsets
d78b5f77e doc: SPDK NVMe Bdev 23.01 Performance Report
3e5cefb51 doc: add Vhost 23.01 performance report link
82c61e067 lib/nvme: 0 based numd for reservation report
a67da4e64 thread: use spdk_thread_get_app_thread instead of _spdk_get_app_thread
652db802f bdevperf: Outstanding requests array size check
5867f4da7 scripts: add a ledctl wrapper script for NPEM
1eb06bd60 malloc_bdev: Add physical block size optional argument
7f50da15b null_bdev: Add physical block size optional argument
a3f9583a8 common/config: Remove unused pieces
c1cab017a pkgdep/git: Remove install_{,ref}spdk()
ea91da8d2 pkgdep: Install git at the default /usr/local/bin dir
4dcb94480 autobuild: patch DPDK with "hash: fix GFNI implementation build with GCC12"
24f6172ac rpc: fix new line formatting
0093da08a log: make macro parameters lowercase
bdf1bf407 autotest: remove spdk_top from coverage
0473a7816 accel: clear out domain/step_cb pointers in encrypt/decrypt
3c5a8ddc4 bdev/rbd: fix double-free when failing to initialize cluster
a5d5ab27d examples/accel/perf: add support for xor
b41efae2c accel: add support for xor
1ae6a83aa doc/distributions: don't mention Fedora version
```

I broadened the search to Feb 17-26.  I don't see anything the would point to a perf regression, at least for this test.

This test does not use accel, rbd, malloc, null, lvols, or bdevperf.
I did look at the thread patch `a67da4e` but it doesn't touch the main I/O path at all.

Is it possible there were any other changes to CI around this time, NIC FW upgrade, that sort of thing?

**Comment by kgodzwox** [comment]
Hi @jimharris 
> Is it possible there were any other changes to CI around this time, NIC FW upgrade, that sort of thing?
I checked my notes, and yes, the regression machines have been updated to Fedora 37, and maybe that's the reason for the increase in latency as you mentioned.

**Comment by jimharris** [comment]
> Hi @jimharris
> 
> > Is it possible there were any other changes to CI around this time, NIC FW upgrade, that sort of thing?
> 
> I checked my notes, and yes, the regression machines were updated to Fedora 37 the week this issue occurred, and maybe that's the reason for the latency increase as you mentioned.

Thanks @kgodzwox.

I feel like we should close this issue.  We've analyzed all relevant commits in SPDK, and the F37 upgrade seems like the most likely culprit.

-Jim
