### ISSUE TITLE
[external_run_nvme_shared] Timeout during call to test/external_code/nvme/identify

### ISSUE THREAD

**Issue by m-spiewak** [spdk/spdk#3017]
During execution of the CI on a patch, a timeout occurred during execution of the external_run_nvme_shared test, when calling test/external_code/nvme/identify

# CI Intermittent Failure
external_run_nvme_shared

## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_103677.html

##Log

00:09:46.181  ************************************
00:09:46.181  START TEST external_run_nvme_shared
00:09:46.181  ************************************
00:09:46.181   09:37:34	-- common/autotest_common.sh@1077 -- $ xtrace_enable
00:09:46.181   09:37:34	-- common/autotest_common.sh@1078 -- $ sudo -E --preserve-env=PATH LD_LIBRARY_PATH=:/home/vagrant/spdk_repo/spdk/build/lib:/home/vagrant/spdk_repo/spdk/dpdk/build/lib:/home/vagrant/spdk_repo/spdk/build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../dpdk/build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/passthru /home/vagrant/spdk_repo/spdk/test/external_code/nvme/identify.sh
00:09:46.441  * Looking for test storage...
00:09:46.441  * Found test storage at /home/vagrant/spdk_repo/spdk/test/external_code/nvme
00:09:46.441    09:37:34	-- common/autotest_common.sh@1641 -- # xtrace_enable
00:09:46.441   09:37:34	-- nvme/identify.sh@12 -- # export SPDK_LIB_DIR=/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/lib
00:09:46.441   09:37:34	-- nvme/identify.sh@12 -- # SPDK_LIB_DIR=/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/lib
00:09:46.441   09:37:34	-- nvme/identify.sh@13 -- # export DPDK_LIB_DIR=/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../dpdk/build/lib
00:09:46.441   09:37:34	-- nvme/identify.sh@13 -- # DPDK_LIB_DIR=/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../dpdk/build/lib
00:09:46.441   09:37:34	-- nvme/identify.sh@14 -- # export LD_LIBRARY_PATH=:/home/vagrant/spdk_repo/spdk/build/lib:/home/vagrant/spdk_repo/spdk/dpdk/build/lib:/home/vagrant/spdk_repo/spdk/build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../dpdk/build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/passthru:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../dpdk/build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../dpdk/build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme
00:09:46.441   09:37:34	-- nvme/identify.sh@14 -- # LD_LIBRARY_PATH=:/home/vagrant/spdk_repo/spdk/build/lib:/home/vagrant/spdk_repo/spdk/dpdk/build/lib:/home/vagrant/spdk_repo/spdk/build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../dpdk/build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/../../build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/passthru:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../dpdk/build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/libvfio-user/usr/local/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme/../../../dpdk/build/lib:/home/vagrant/spdk_repo/spdk/test/external_code/nvme
00:09:46.441    09:37:34	-- nvme/identify.sh@17 -- **# /home/vagrant/spdk_repo/spdk/test/external_code/nvme/identify**
00:09:46.441  TELEMETRY: No legacy callbacks, legacy socket not created
**00:31:51.485  Cancelling nested steps due to timeout**
00:31:51.488  Sending interrupt signal to process
00:31:53.778  script returned exit code 255
00:31:53.783  [Pipeline] }
**00:31:53.806  [Pipeline] // timeout**
00:31:53.815  [Pipeline] }
00:31:53.835  [Pipeline] // stage
00:31:53.843  [Pipeline] }
00:31:53.847  Timeout has been exceeded
00:31:53.867  [Pipeline] // catchError
00:31:53.878  [Pipeline] stage
00:31:53.881  [Pipeline] { (Stop VM)
00:31:53.897  [Pipeline] sh
00:31:54.178  + vagrant halt
00:31:56.714  ==> default: Halting domain...
00:32:02.004  [Pipeline] sh
00:32:02.284  + vagrant destroy -f
00:32:04.818  ==> default: Removing domain...
00:32:05.089  [Pipeline] sh
00:32:05.369  + mv output /var/jenkins/workspace/autobuild-vg-autotest/output
00:32:05.377  [Pipeline] }
00:32:05.394  [Pipeline] // stage
00:32:05.401  [Pipeline] }
00:32:05.418  [Pipeline] // dir
00:32:05.424  [Pipeline] }
00:32:05.442  [Pipeline] // wrap
00:32:05.449  [Pipeline] }
00:32:05.464  [Pipeline] // catchError
00:32:05.474  [Pipeline] stage
00:32:05.476  [Pipeline] { (Epilogue)
00:32:05.491  [Pipeline] sh
00:32:05.771  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:32:05.784  [Pipeline] catchError
00:32:05.786  [Pipeline] {
00:32:05.802  [Pipeline] sh
00:32:06.083  + jbp/jenkins/jjb-config/jobs/scripts/check_artifacts_size.sh
00:32:06.083  Artifacts sizes are good
00:32:06.091  [Pipeline] }
00:32:06.108  [Pipeline] // catchError
00:32:06.117  [Pipeline] archiveArtifacts
00:32:06.123  Archiving artifacts
00:32:06.160  [Pipeline] cleanWs
00:32:06.170  [WS-CLEANUP] Deleting project workspace...
00:32:06.170  [WS-CLEANUP] Deferred wipeout is used...
00:32:06.176  [WS-CLEANUP] done
00:32:06.178  [Pipeline] }
00:32:06.196  [Pipeline] // stage
00:32:06.202  [Pipeline] }
00:32:06.215  [Pipeline] // node
00:32:06.221  [Pipeline] End of Pipeline
00:32:06.238  Finished: ABORTED

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @m-spiewak. log: https://ci.spdk.io/public_build/autotest-per-patch_103677.html

**Comment by mikeBashStuff** [comment]
This happened after deplying qemu 8.0.0 for our vg jobs. This was already reverted back to 7.0.0 and is being troubleshooted. Basically, the external `identify` is blocking while performing the `spdk_mmio_read_4()` (note that that `identify` from examples works just fine). Currently figuring out why the actual write blocks.

**Comment by jimharris** [comment]
This is just a wild guess, but could you try something like this?

```
diff --git a/test/external_code/nvme/nvme.c b/test/external_code/nvme/nvme.c
index f25020c76..3ca7641ee 100644
--- a/test/external_code/nvme/nvme.c
+++ b/test/external_code/nvme/nvme.c
@@ -467,6 +467,8 @@ process_ctrlr_init(struct nvme_ctrlr *ctrlr)
                return 0;
        }

+       SPDK_ERRLOG("Delay 10ms\n");
+       spdk_delay_us(10 * 1000);
        nvme_ctrlr_get_cc(ctrlr, &cc);
        nvme_ctrlr_get_csts(ctrlr, &csts);
```

This is just a wild guess.  With the "real" NVMe driver, there's definitely a bit longer delay between initial probe and the first register read.  And it isn't unheard of to have to delay a bit before reading a register (we already have a DELAY_BEFORE_INIT quirk for some physical SSDs).

Could you try the static version of this binary too?  I don't see how shared v. static could have anything to do with it, but please let's just rule that out.  You'll see the nvme_static part later in that test/external_code/test_make.sh script.

**Comment by mikeBashStuff** [comment]
@jimharris Appreciate the response. :)

The static build shows exactly the same behavior. Adding delay does not seem to work, but the `SPDK_ERRLOG` nicely showed that we enter an infinite loop while handling ctrlr's state - it gets stuck on `NVME_CTRLR_STATE_DISABLE_WAIT_FOR_READY_1`. I tried to compare handling of the external's `nvme_ctrlr_state` to the "real" one but these enums differ quite a bit and I am having a hard time to follow each and every state. I had done something like this, thinking it may look a bit closer as to what the "real" stuff does, but it didn't help either:

```
diff --git a/test/external_code/nvme/nvme.c b/test/external_code/nvme/nvme.c
index f25020c76..2ddd32a68 100644
--- a/test/external_code/nvme/nvme.c
+++ b/test/external_code/nvme/nvme.c
@@ -52,6 +52,7 @@ struct nvme_qpair {
 };

 enum nvme_ctrlr_state {
+       NVME_CTRLR_STATE_INIT_DELAY,
        /* Controller has not been initialized yet */
        NVME_CTRLR_STATE_INIT,
        /* Waiting for CSTS.RDY to transition from 0 to 1 so that CC.EN may be set to 0 */
@@ -467,10 +468,18 @@ process_ctrlr_init(struct nvme_ctrlr *ctrlr)
                return 0;
        }

+       // SPDK_ERRLOG("Delay 10ms\n");
+       // spdk_delay_us(10 * 1000);
        nvme_ctrlr_get_cc(ctrlr, &cc);
        nvme_ctrlr_get_csts(ctrlr, &csts);

+       SPDK_ERRLOG("State: %u\n", ctrlr->state);
+
        switch (ctrlr->state) {
+       case NVME_CTRLR_STATE_INIT_DELAY:
+               ctrlr->state = NVME_CTRLR_STATE_INIT;
+               spdk_delay_us(2 * 1000 * 1000);
+               break;
        case NVME_CTRLR_STATE_INIT:
                if (cc.bits.en) {
                        if (csts.bits.rdy == 0) {
@@ -488,6 +497,8 @@ process_ctrlr_init(struct nvme_ctrlr *ctrlr)
                        cc.bits.en = 0;
                        nvme_ctrlr_set_cc(ctrlr, &cc);
                        ctrlr->state = NVME_CTRLR_STATE_DISABLE_WAIT_FOR_READY_0;
+               } else {
+                       process_completions(ctrlr->admin_qpair); // this differs quite a bit from spdk_nvme_qpair_process_completions() so I don't really know what I am doing :P
                }
                break;
        case NVME_CTRLR_STATE_DISABLE_WAIT_FOR_READY_0:
```
With the above this is what happens:

```
# There are two nvmes attached to the VM
[2023-05-12 10:11:29.322742] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 0 # <- waits for 2s, 1st nvme
[2023-05-12 10:11:31.320384] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 0 # <- waits for 2s, 2nd nvme
[2023-05-12 10:11:33.318002] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 1 # 1st
[2023-05-12 10:11:33.320121] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 1 # 2nd
[2023-05-12 10:11:33.320176] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2 # etc.
[2023-05-12 10:11:33.320215] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2 
[2023-05-12 10:11:33.320252] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
[2023-05-12 10:11:33.320291] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
[2023-05-12 10:11:33.320329] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
[2023-05-12 10:11:33.320366] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
[2023-05-12 10:11:33.320402] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
[2023-05-12 10:11:33.320439] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
[2023-05-12 10:11:33.320476] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
[2023-05-12 10:11:33.320513] nvme.c: 476:process_ctrlr_init: *ERROR*: State: 2
# To infinity, and beyond!
```

**Comment by ksztyber** [comment]
@mikeBashStuff, could you check this:
```
diff --git a/test/external_code/nvme/nvme.c b/test/external_code/nvme/nvme.c
index f25020c76..62b413f18 100644
--- a/test/external_code/nvme/nvme.c
+++ b/test/external_code/nvme/nvme.c
@@ -484,7 +484,8 @@ process_ctrlr_init(struct nvme_ctrlr *ctrlr)
                ctrlr->state = NVME_CTRLR_STATE_DISABLE_WAIT_FOR_READY_0;
                break;
        case NVME_CTRLR_STATE_DISABLE_WAIT_FOR_READY_1:
-               if (csts.bits.rdy) {
+               SPDK_ERRLOG("cc=0x%x, csts=%0x\n", cc.raw, csts.raw);
+               if (csts.bits.rdy || csts.bits.cfs) {
                        cc.bits.en = 0;
                        nvme_ctrlr_set_cc(ctrlr, &cc);
                        ctrlr->state = NVME_CTRLR_STATE_DISABLE_WAIT_FOR_READY_0;
```
We've added something similar in our regular NVMe driver to fix issues under sw_hotplug tests, but maybe it's now needed in other cases too.

**Comment by mikeBashStuff** [comment]
@ksztyber I am afraid it didn't help - now it's stuck on the `NVME_CTRLR_STATE_ENABLE_WAIT_FOR_READY_1`.  When I add this bit check `csts.bits.cfs` there, nvme reaches `NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY` but that's it (i.e. it does not switch to `READY`). I guess maybe some change is needed in the `identify_ctrlr()`?

**Comment by ksztyber** [comment]
I don't think there's a problem with `identify_ctrlr()`, I wouldn't expect a controller to respond to any commands if it has the CFS (Controller Fail Status) bit set. The real problem is that it doesn't get cleared after we do `cc.en = 0`, `cc.en = 1`. I'll try to reproduce this lcoally.

**Comment by ksztyber** [comment]
I think the problem was that we didn't set `iocqes`/`iosqes` and newer versions of qemu have them cleared. This patch [1] should fix this. @mikeBashStuff, could you verify that it also works on your end?

[1] https://review.spdk.io/gerrit/c/spdk/spdk/+/18087

**Comment by jimharris** [comment]
> @ksztyber It does work now, thanks! Just a question about this:
> 
> > newer versions of qemu have them cleared.
> 
> Does this refer to some particular change|commit in more recent QEMU versions? If yes, would you kindly point me to it? :)

This looks like the culprit:

qemu/qemu@cc9bcee265a22f6e2391eaa76a0dc2b34469b2a7

Specifically this part here:

```
diff --git a/hw/nvme/ctrl.c b/hw/nvme/ctrl.c
index 658584d417..a558f5cb29 100644
--- a/hw/nvme/ctrl.c
+++ b/hw/nvme/ctrl.c
@@ -6190,10 +6190,15 @@ static void nvme_ctrl_reset(NvmeCtrl *n, NvmeResetType rst)

     if (pci_is_vf(pci_dev)) {
         sctrl = nvme_sctrl(n);
+
         stl_le_p(&n->bar.csts, sctrl->scs ? 0 : NVME_CSTS_FAILED);
     } else {
         stl_le_p(&n->bar.csts, 0);
     }
+
+    stl_le_p(&n->bar.intms, 0);
+    stl_le_p(&n->bar.intmc, 0);
+    stl_le_p(&n->bar.cc, 0);
 }

 static void nvme_ctrl_shutdown(NvmeCtrl *n)
```

**Comment by mikeBashStuff** [comment]
> > @ksztyber It does work now, thanks! Just a question about this:
> > 
> > > newer versions of qemu have them cleared.
> > 
> > Does this refer to some particular change|commit in more recent QEMU versions? If yes, would you kindly point me to it? :)
> 
> This looks like the culprit:
> 
> qemu/qemu@cc9bcee265a22f6e2391eaa76a0dc2b34469b2a7
> 
> Specifically this part here:
> 
> ```
> diff --git a/hw/nvme/ctrl.c b/hw/nvme/ctrl.c
> index 658584d417..a558f5cb29 100644
> --- a/hw/nvme/ctrl.c
> +++ b/hw/nvme/ctrl.c
> @@ -6190,10 +6190,15 @@ static void nvme_ctrl_reset(NvmeCtrl *n, NvmeResetType rst)
> 
>      if (pci_is_vf(pci_dev)) {
>          sctrl = nvme_sctrl(n);
> +
>          stl_le_p(&n->bar.csts, sctrl->scs ? 0 : NVME_CSTS_FAILED);
>      } else {
>          stl_le_p(&n->bar.csts, 0);
>      }
> +
> +    stl_le_p(&n->bar.intms, 0);
> +    stl_le_p(&n->bar.intmc, 0);
> +    stl_le_p(&n->bar.cc, 0);
>  }
> 
>  static void nvme_ctrl_shutdown(NvmeCtrl *n)
> ```

Thanks!
