### ISSUE TITLE
Pkgconfig files not correctly regenerated

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#3018]
# Sighting report

```
./configure --without-idxd
make
```
`./build/lib/pkgconfig/spdk_accel_dsa.pc` does not exist (expected) and `./build/lib/pkgconfig/spdk_accel_modules.pc` lists only spdk_accel_ioat and spdk_ioat (expected).

Then, without cleaning anything:

```
./configure --with-idxd
make
```
`./build/lib/pkgconfig/spdk_accel_dsa.pc` now exists (expected) but `./build/lib/pkgconfig/spdk_accel_modules.pc` still only lists spdk_accel_ioat and spdk_ioat (not expected). If you delete spdk_accel_modules.pc and make again, it is regenerated correctly.

## Expected Behavior

The modules pc files need to get regenerated if there is a configuration change.

## Current Behavior

The modules files do not get regenerated. This is not specific to accel - it's any module.pc.

## Possible Solution

Need to get the dependency correct in the Makefile.

## Steps to Reproduce

Exact steps above.

## Context (Environment including OS version, SPDK version, etc.)

Fedora 38, latest SPDK.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/18233

**Comment by tomzawadzki** [comment]
Patch https://review.spdk.io/gerrit/c/spdk/spdk/+/18233 was merged fixing this issue.
