### ISSUE TITLE
[nvmf_discovery_remove_ifc] Controller is not removed after ctrlr_loss_timeout_sec 

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#3024]
# CI Intermittent Failure

Following patch introduced the test https://review.spdk.io/gerrit/c/spdk/spdk/+/17112.
It seems that the ctlr is still present after sleeping 2 and 5 seconds, despite CTRLR_LOSS_TIMEOUT_SEC being set to 2 seconds. 

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/104058/archive/nvmf-tcp-vg-autotest/build.log

## Execution failed at

```
00:27:56.387  [2023-05-16 20:54:33.287268] nvme_fabric.c: 214:nvme_fabric_prop_get_cmd_async: *ERROR*: Failed to send Property Get fabrics command
00:27:56.387  [2023-05-16 20:54:33.287453] nvme_ctrlr.c:1122:nvme_ctrlr_shutdown_async: *ERROR*: [nqn.2014-08.org.nvmexpress.discovery] Failed to read the CC register
00:27:56.387  [2023-05-16 20:54:33.287889] nvme_fabric.c: 214:nvme_fabric_prop_get_cmd_async: *ERROR*: Failed to send Property Get fabrics command
00:27:56.388  [2023-05-16 20:54:33.288082] nvme_ctrlr.c:1122:nvme_ctrlr_shutdown_async: *ERROR*: [nqn.2016-06.io.spdk:cnode0] Failed to read the CC register
00:27:56.388    20:54:33	-- common/autotest_common.sh@587 -- # xtrace_enable
00:27:56.388    20:54:33	-- common/autotest_common.sh@588 -- # [[ 0 == 0 ]]
00:27:56.388   20:54:33	-- host/discovery_remove_ifc.sh@76 -- # [[ nvme0n1 == '' ]]
00:27:56.388    20:54:33	-- host/discovery_remove_ifc.sh@76 -- # trap - ERR
00:27:56.388    20:54:33	-- host/discovery_remove_ifc.sh@76 -- # print_backtrace
00:27:56.388    20:54:33	-- common/autotest_common.sh@1106 -- # [[ ehxBET =~ e ]]
00:27:56.388    20:54:33	-- common/autotest_common.sh@1108 -- # args=('--transport=tcp')
00:27:56.388    20:54:33	-- common/autotest_common.sh@1108 -- # local args
00:27:56.388    20:54:33	-- common/autotest_common.sh@1110 -- # xtrace_disable
00:27:56.388    20:54:33	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:27:56.388    20:54:33	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:27:56.388    20:54:33	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:27:56.388    20:54:33	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:27:56.388    20:54:33	-- common/autotest_common.sh@25 -- # set +x
00:27:56.388  ========== Backtrace start: ==========
00:27:56.388  
00:27:56.388  in /home/vagrant/spdk_repo/spdk/test/nvmf/host/discovery_remove_ifc.sh:76 -> main(["--transport=tcp"])
00:27:56.388       ...
00:27:56.388     71  	sleep 2
00:27:56.388     72  	[[ $(get_bdev_list) == "nvme0n1" ]]
00:27:56.388     73  	
00:27:56.388     74  	# Wait a few sec to ensure that ctrlr is removed and ctrlr_loss_timeout_sec exceeded
00:27:56.388     75  	sleep 5
00:27:56.388  => 76  	[[ $(get_bdev_list) == "" ]]
00:27:56.388     77  	
00:27:56.388     78  	# Resume network connection
00:27:56.388     79  	"${NVMF_TARGET_NS_CMD[@]}" ip addr add $NVMF_FIRST_TARGET_IP/24 dev $NVMF_TARGET_INTERFACE
00:27:56.388     80  	"${NVMF_TARGET_NS_CMD[@]}" ip link set $NVMF_TARGET_INTERFACE up
00:27:56.388     81  	
00:27:56.388       ...
00:27:56.388  
00:27:56.388  ========== Backtrace end ==========
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_104058.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_104149.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_104279.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_104301.html

**Comment by mikeBashStuff** [comment]
Can we switch to some busy-wait checks instead? Recently we did similar things in various places (like vhost tests) where instead of relaying on sleep's flakiness we just busy loop until the condition is met. Of course, the risk is that we will block forever, but if that's the case then we still will be hit by the job's timeout (so similar rationale as in recent `sw_hotplug` conundrum that we had to solve) failing the test. 

Unless of course this:
> ctlr is still present after sleeping 2 and 5 seconds, despite CTRLR_LOSS_TIMEOUT_SEC being set to 2 seconds.

is an actual bug.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_104455.html

**Comment by jimharris** [comment]
> Can we switch to some busy-wait checks instead? Recently we did similar things in various places (like vhost tests) where instead of relaying on sleep's flakiness we just busy loop until the condition is met. Of course, the risk is that we will block forever, but if that's the case then we still will be hit by the job's timeout (so similar rationale as in recent `sw_hotplug` conundrum that we had to solve) failing the test.
> 
> Unless of course this:
> 
> > ctlr is still present after sleeping 2 and 5 seconds, despite CTRLR_LOSS_TIMEOUT_SEC being set to 2 seconds.
> 
> is an actual bug.

Yeah, I think this is a bug.  It needs more investigation.

@sberbz, can you prep a patch with `[RFC]` prefix, that runs this specific test in a loop 100 times?  And work w/ @mikeBashStuff on how to trigger running it on the `nvmf-tcp-vg-autotest` job.  We can use that to start gathering more data on why the timeout isn't triggering, and to be more confident in whatever fix we come up with.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @kgodzwox. log: https://ci.spdk.io/public_build/autotest-per-patch_104681.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_104639.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_104718.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_104763.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_104830.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_105013.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_105099.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_105139.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_104965.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_105182.html

**Comment by sberbz** [comment]
Hi 
Here is a patch with busy wait: https://review.spdk.io/gerrit/c/spdk/spdk/+/18399/7

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_105321.html

**Comment by sberbz** [comment]
Stop reproducing since, patch with busy wait has been merged.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_109489.html

**Comment by KKaras169169** [comment]
> Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_109489.html

Reported on a backport to v23.05.x.
