### ISSUE TITLE
[Fedora38] [scanbuild_make] values stored to variables are never read

### ISSUE THREAD

**Issue by kgodzwox** [spdk/spdk#3026]
# Sighting report

During SPDK autotests on Fedora 38, the scan-build found warnings about the never read values from variables and it failed the test.
```
14:24:30   12:24:29	-- common/autobuild_common.sh@243 -- $ scan-build -o /home/vagrant/spdk_repo/spdk/../output/scan-build-tmp --exclude /home/vagrant/spdk_repo/spdk/dpdk/ --exclude /home/vagrant/spdk_repo/spdk/xnvme --exclude /tmp --status-bugs make -j12
14:29:07  In file included from accel_dpdk_cryptodev.c:20:
14:29:07  In file included from /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_crypto.h:25:
14:29:07  /home/vagrant/spdk_repo/spdk/dpdk/build/include/rte_crypto_sym.h:997:4: warning: Value stored to 'left' is never read [deadcode.DeadStores]
14:29:07                          left = 0;
14:29:07                          ^      ~
14:29:07  1 warning generated.
14:29:53  spdk_dd.c:221:8: warning: Value stored to 'speed_type' during its initialization is never read [deadcode.DeadStores]
14:29:53          char *speed_type = "";
14:29:53                ^~~~~~~~~~   ~~
14:29:53  1 warning generated.
```

From the submodule ~~`dpdk`~~, and `spdk/app/spdk_dd.c`
Here are possible fixes:
~~* spdk/dpdk: https://review.spdk.io/gerrit/c/spdk/dpdk/+/18188~~
* spdk: https://review.spdk.io/gerrit/c/spdk/spdk/+/18187

## Context (Environment including OS version, SPDK version, etc.)
* OS: `Fedora 38`
* Kernel: `6.2.15-300.fc38.x86_64`
* SPDK ver.:  `v23.05-pre-743-ga7d920a69`
* GCC ver: `13.1.1`

**Comment by jimharris** [comment]
Hi @kgodzwox,

Can you confirm that the DPDK patch is really needed here?

I know it's producing a warning, but this warning has been around for a long time, and hasn't caused failures.  For example, see https://ci.spdk.io/results/autotest-per-patch/builds/102242/archive/scanbuild-vg-autotest/build.log from a recent test run.  I'd rather not merge this into our submodule if it really isn't needed.

I posted a comment on the DPDK patch, it needs a different fix.  It would be great for you (or someone) to push this patch to upstream DPDK.

-Jim

**Comment by kgodzwox** [comment]
Hi @jimharris,
I can confirm that a DPDK patch is not actually needed. I posted a comment -> https://review.spdk.io/gerrit/c/spdk/dpdk/+/18188
and abandon this change. Also, I will push your patch to upstream DPDK.

(SPDK patch is still valid)
Thanks

**Comment by kgodzwox** [comment]
@jimharris DPDK patch: https://patches.dpdk.org/project/dpdk/patch/20230522190453.453281-1-kamilx.godzwon@intel.com/
