### ISSUE TITLE
Assertion `!ns->nsdata_zns' on ZNS Drive with SPDK_NVME_ASYNC_EVENT_NS_ATTR_CHANGED AEN

### ISSUE THREAD

**Issue by curtbruns** [spdk/spdk#3028]
Using a ZNS drive that sends an SPDK_NVME_ASYNC_EVENT_NS_ATTR_CHANGED AEN, the nvme_ctrlr code will re-construct the namespace, but it does not destruct the previous memory allocation for nsdata_zns. This causes the assertion to hit for !ns->nsdata_zns.

## Expected Behavior
Software should be able to re-identify the namespace on SPDK_NVME_ASYNC_EVENT_NS_ATTR_CHANGED AEN without any issue.

## Current Behavior
For a ZNS drive, there is a block of memory (nsdata_zns) that is allocated when the ZNS drive is enumerated. This memory is already allocated when the controller code goes to re-construct the namespace for an SPDK_NVME_ASYNC_EVENT_NS_ATTR_CHANGED AEN so the controller code asserts.

identify: nvme_ns.c:147: nvme_ctrlr_identify_ns_iocs_specific: Assertion `!ns->nsdata_zns' failed.

## Possible Solution
diff --git a/lib/nvme/nvme_ctrlr.c b/lib/nvme/nvme_ctrlr.c
index 9a4837a2d..e6b98a242 100644
--- a/lib/nvme/nvme_ctrlr.c
+++ b/lib/nvme/nvme_ctrlr.c
@@ -2977,6 +2977,8 @@ nvme_ctrlr_update_namespaces(struct spdk_nvme_ctrlr *ctrlr)
        for (nsid = spdk_nvme_ctrlr_get_first_active_ns(ctrlr);
             nsid != 0; nsid = spdk_nvme_ctrlr_get_next_active_ns(ctrlr, nsid)) {
                ns = spdk_nvme_ctrlr_get_ns(ctrlr, nsid);
\+               // Clear out previous settings/memory
\+               nvme_ns_destruct(ns);
                nvme_ns_construct(ns, nsid, ctrlr);
        }
}
[failing_identify_zns_spdk.txt](https://github.com/spdk/spdk/files/11511374/failing_identify_zns_spdk.txt)

**Comment by jimharris** [comment]
Hi @curtbruns!

This patch looks good to me, I just dug into the nvme_ctrlr.c and nvme_ns.c and this definitely looks like the right fix.

Can you push this as a patch to SPDK Gerrit?

-Jim

**Comment by curtbruns** [comment]
Hey @jimharris - you bet, I will push it this morning. Thanks!

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/18251 - thanks @curtbruns.
