### ISSUE TITLE
[nvmf-phy-autotest] thread.c: 518:spdk_thread_create: *ERROR*: Unable to allocate memory for message ring

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3031]
# Sighting report

SPDK bdevperf hits an error and segfaults during NVMe-oF test `START TEST nvmf_bdev_io_wait` because of:
https://ci.spdk.io/public_build/autotest-per-patch_104992.html
https://ci.spdk.io/results/autotest-per-patch/builds/104992/archive/nvmf-phy-autotest/build.log

```
00:13:18.912  RING: Cannot reserve memory
00:13:18.912  [2023-05-25 09:10:23.089143] thread.c: 518:spdk_thread_create: *ERROR*: Unable to allocate memory for message ring
00:13:18.912  bdevperf: bdevperf.c:1914: bdevperf_construct_jobs: Assertion `thread' failed.
[...]
00:13:27.357  /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/bdev_io_wait.sh: line 40: 1448885 Aborted                 (core dumped) "$rootdir/build/examples/bdevperf" -m 0x80 -i 4 --json <(gen_nvmf_target_json) -q 128 -o 4096 -w unmap -t 1
```

This happens during tests as part of the effort to enable all build flags for test: https://github.com/spdk/spdk/issues/2900

## Current Behavior

^up

## Steps to Reproduce

1. Configure & build SPDK:
```
./configure --enable-asan --enable-ubsan --enable-coverage \
--enable-werror --enable-debug --with-crypto --with-fuse \
--with-idxd --with-nvme-cuse --with-rdma --with-usdt --with-fio \
--with-iscsi-initiator --with-nvme-cuse --with-vbdev-compress \
--with-dpdk-compressdev --with-rbd --with-ublk --with-raid5f --with-ocf \
--with-vfio-user --with-sma --with-xnvme --with-avahi --with-uring;
make -j
```
2. Run `sudo -E SPDK_TEST_NVMF_NICS=mlx5 SPDK_TEST_NVMF=1 NET_TYPE=phy /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/bdev_io_wait.sh --transport=rdma --iso` (TCP works too)

## Context (Environment including OS version, SPDK version, etc.)

Tested with: https://review.spdk.io/gerrit/c/spdk/spdk/+/17143/57
based on: 113075be6639ff9ca8fa9aa553edb483746fab1b

**Comment by karlatec** [comment]
Backtrace: https://ci.spdk.io/results/autotest-per-patch/builds/104992/archive/nvmf-phy-autotest/coredumps/bdevperf_1448885.core.bt.txt

**Comment by jimharris** [comment]
This one baffles me a bit.  Are you able to narrow down which of those additional flags added for #2900 causes this out of memory error?

This test does run 4 bdevperfs in parallel, but I don't see which of these flags would result in more memory.  ublk for example, this test doesn't enable it, and even if it did, it is using iobufs, not allocating its own buffers anymore.

Maybe something about the additional flags results in those 1 second executions overlapping more?  That's really a stretch.  One test would be increase the time of those bdevperfs from 1 second to 10 seconds and see if it fails on master (without your test configuration changes).

**Comment by KKaras169169** [comment]
How easy is it to break this test - do the reproduction steps work every time?
I followed the steps a few times for RDMA and TCP and cannot get this to break in the same way (tested on GP12 with Fedora37). Full CI logs are not available anymore unfortunately.

**Comment by karlatec** [comment]
Seems to be reproducible each time test is run.
Today's test run, after rebasing on master branch: https://ci.spdk.io/public_build/autotest-per-patch_106563.html

**Comment by tomzawadzki** [comment]
@KKaras169169 I'd imagine that one of the increases in memory consumption might be OCF, which in this particular test is enabled on 4 instances of SPDK. You could verify the difference in memory allocated on particular SPDK instance via `env_dpdk_get_mem` RPC and `./scripts/dpdk_mem_info.py`.
To reproduce the issue most likely you need to enable the same flags as on the CI job and have the same amount of hugepages allocated. If you cannot do that locally there is always option of using the CI via submitting a patch and using `test:...` comment on Gerrit.

**Comment by karlatec** [comment]
Provided repro steps are OK with one exception - I noticed that `--with-ocf` was missing and it makes all the difference.

**Comment by karlatec** [comment]
Proposed fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/19264
