### ISSUE TITLE
Remove /home/sys_sgsw dependency from test scripts

### ISSUE THREAD

**Issue by johnmeneghini** [spdk/spdk#304]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Title says it all.

## Expected Behavior

vm_setup.sh, autotest_common.sh, and vhost tests should use a relative path instead of /home/sys_sgsw

## Current Behavior

Current test scripts assume a hardcoded path to /home/sys_sgsw in some places

## Possible Solution

Check all dependent utilities, images, and rpms into the repository and replace /home/sys_sgsw with  /home/${USER} in all places.

## Steps to Reproduce

```
[sys_sgsw@localhost spdk]$ find . -name \*.sh -exec grep sys_sgsw {} \; -print
# but it may be easiest if you create your user with the name sys_sgsw for now.
./test/common/config/vm_setup.sh
if [ -d /home/sys_sgsw/vtune_codes ]; then
        config_params+=' --with-vtune=/home/sys_sgsw/vtune_codes'
./test/common/autotest_common.sh
base_img=/home/sys_sgsw/fedora24.img
test_img=/home/sys_sgsw/fedora24_test.img
qemu_pidfile=/home/sys_sgsw/qemupid
./test/nvme/hotplug.sh
spdk_nvme_cli="/home/sys_sgsw/nvme-cli"
./test/nvme/spdk_nvme_cli.sh
spdk_nvme_cli="/home/sys_sgsw/nvme-cli"
./test/nvmf/nvme_cli/nvme_cli.sh
        echo "    --vm_image=PATH   Path to VM image used in these tests [default=/home/sys_sgsw/vhost_vm_image.qcow2]"
os_image="/home/sys_sgsw/vhost_vm_image.qcow2"
./test/vhost/initiator/blockdev.sh
setup_cmd+=" --os=/home/sys_sgsw/vhost_vm_image.qcow2"
./test/vhost/integrity/integrity_start.sh
        setup_cmd+=" --os=/home/sys_sgsw/spdk_vhost_CentOS_vm_image.qcow2"
        setup_cmd+=" --os=/home/sys_sgsw/vhost_vm_image.qcow2"
./test/vhost/lvol/lvol_test.sh
DEFAULT_VM_IMAGE="/home/sys_sgsw/vhost_vm_image.qcow2"
CENTOS_VM_IMAGE="/home/sys_sgsw/spdk_vhost_CentOS_vm_image.qcow2"
DEFAULT_FIO_BIN="/home/sys_sgsw/fio_ubuntu"
CENTOS_FIO_BIN="/home/sys_sgsw/fio_ubuntu_bak"
./test/vhost/spdk_vhost.sh
```
## Context (Environment including OS version, SPDK version, etc.)

```
[sys_sgsw@localhost spdk]$ git logl -1 origin/master
* f750c4eb 2018-05-17  (origin/master, origin/HEAD, master) nvme: apply Identify CNS quirk to NS ID Descriptor [ Jim Harris / daniel.verkamp@intel.com ]
[sys_sgsw@localhost spdk]$ cat /etc/system-release
Fedora release 26 (Twenty Six)
[sys_sgsw@localhost spdk]$ uname -r
4.16.7-100.fc26.x86_64
```

**Comment by xuhuagen** [comment]
could we use $HOME instead of /home/sys_sysw?

**Comment by dverkamp-intel** [comment]
Most of these paths point at the location for VM test images that are not published anywhere currently; part of solving this issue is finding a way to provide the VM images (or ideally, generate them from an unmodified installer ISO and a script of some kind, maybe via Kickstart for Fedora).

**Comment by johnmeneghini** [comment]
The new patch I've created for this enhancement is at:

https://review.gerrithub.io/#/c/spdk/spdk/+/415907/

**Comment by liang2yan** [comment]
close this issue since patch merged.
