### ISSUE TITLE
Segmentation fault after using spdk_nvme_ctrlr_fail inside timeout callback

### ISSUE THREAD

**Issue by LiadOz** [spdk/spdk#3040]
# Sighting report

This issue happens when using the SPDK nvme_tcp backend of xNVMe in the latest `next` branch.
The initiator has 10 seconds timeout configured for admin commands and 5 minutes for io commands, when a timeout is detected `spdk_nvme_ctrlr_fail` is called on the controller, this will abort the all commands in the queue.

My code will sends a synchronous KEEP_ALIVE command every 30 seconds to make sure the device is responding, if it fails to respond, in 10 seconds `spdk_nvme_ctrlr_fail` will be called and all io should be aborted.

## Example scenario:
Start running io on an NVMe device, after some time drop all packets on port 4420, in the next 40 seconds a keep alive command will be issued.

## Expected Behavior

Controller will be set to a failed state and all pending commands will complete with an error.

## Current Behavior

When an async event has been issued by the device (by adding another namespace to the controller for example) this scenario sometimes causes segmentation fault when the tcp transport tries to check the timeout of commands in the admin queue (after the controller was set to be failed)

Here is the backtrace:
```
Program terminated with signal 11, Segmentation fault.
#0  nvme_request_check_timeout (req=0x0, cid=6, active_proc=active_proc@entry=0x2000003e7380, now_tick=now_tick@entry=558286727986) at nvme.c:474
474	nvme.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64
(gdb) bt
#0  nvme_request_check_timeout (req=0x0, cid=6, active_proc=active_proc@entry=0x2000003e7380, now_tick=now_tick@entry=558286727986) at nvme.c:474
#1  0x000000000054f1a9 in nvme_tcp_qpair_check_timeout (qpair=qpair@entry=0xeeafb0) at nvme_tcp.c:1728
#2  0x00000000005528ae in nvme_tcp_qpair_process_completions (qpair=0xeeafb0, max_completions=<optimized out>) at nvme_tcp.c:1779
#3  0x000000000054a8f0 in spdk_nvme_qpair_process_completions (qpair=qpair@entry=0xeeafb0, max_completions=max_completions@entry=0) at nvme_qpair.c:745
#4  0x000000000054b75a in nvme_wait_for_completion_robust_lock_timeout_poll (qpair=qpair@entry=0xeeafb0, status=status@entry=0xe4a9a0, robust_mutex=robust_mutex@entry=0x0) at nvme.c:253
#5  0x000000000054b826 in nvme_wait_for_completion_robust_lock_timeout (qpair=0xeeafb0, status=status@entry=0xe4a9a0, robust_mutex=robust_mutex@entry=0x0, timeout_in_usecs=<optimized out>)
    at nvme.c:332
#6  0x000000000054b89a in nvme_wait_for_completion_timeout (qpair=<optimized out>, status=status@entry=0xe4a9a0, timeout_in_usecs=<optimized out>) at nvme.c:389
#7  0x000000000053dcf1 in nvme_ctrlr_clear_changed_ns_log (ctrlr=0xeee7e0) at nvme_ctrlr.c:3017
#8  nvme_ctrlr_process_async_event (ctrlr=0xeee7e0, cpl=0x2000003b19c0) at nvme_ctrlr.c:3051
#9  0x000000000053de72 in nvme_ctrlr_complete_queued_async_events (ctrlr=0xeee7e0) at nvme_ctrlr.c:3111
#10 0x000000000053df6a in spdk_nvme_ctrlr_process_admin_completions (ctrlr=0xeee7e0) at nvme_ctrlr.c:4310
#11 0x000000000057a9f7 in xnvme_be_spdk_sync_cmd_admin (ctx=0x7ffdf6f98840, dbuf=0x0, dbuf_nbytes=0, mbuf=0x0, mbuf_nbytes=0) at ../lib/xnvme_be_spdk_admin.c:61
#12 0x000000000057ef53 in xnvme_cmd_pass_admin (ctx=0x7ffdf6f98840, dbuf=0x0, dbuf_nbytes=0, mbuf=0x0, mbuf_nbytes=0) at ../lib/xnvme_cmd.c:101
```

I believe this happens because the `spdk_nvme_ctrlr_fail` causes the outstanding requests to be freed while `nvme_tcp_qpair_check_timeout` is iterating over them.

## Possible Solution

I have made the following change to make the scenario work:
```c
diff --git a/lib/nvme/nvme_tcp.c b/lib/nvme/nvme_tcp.c
index cb32c1bdd..4fb72e428 100644
--- a/lib/nvme/nvme_tcp.c
+++ b/lib/nvme/nvme_tcp.c
@@ -1723,6 +1723,8 @@ nvme_tcp_qpair_check_timeout(struct spdk_nvme_qpair *qpair)

 	t02 = spdk_get_ticks();
 	TAILQ_FOREACH_SAFE(tcp_req, &tqpair->outstanding_reqs, link, tmp) {
+		if (ctrlr->is_failed)
+			return;
 		assert(tcp_req->req != NULL);

 		if (nvme_request_check_timeout(tcp_req->req, tcp_req->cid, active_proc, t02)) {
```
I assume there may be a better way to do it.

## Steps to Reproduce

1. Open NVMe device, set admin command timeout of 10 seconds and io command timeout of 5 minutes, configure the timeout function to call `spdk_nvme_ctrlr_fail`
2. Cause an async event to happen (possibly by adding another namespace to the controller)
3. Cause a timeout between the host and target (for example use `iptables -A OUTPUT -p tcp --dport 4420 -j DROP`)
4. Send sync keep alive command.

If you used iptables to drop the connection make sure to run `iptables -D OUTPUT -p tcp --dport 4420 -j DROP` after.

## Context (Environment including OS version, SPDK version, etc.)

SPDK v22.09

**Comment by tomzawadzki** [comment]
[Bug scrub] @LiadOz The proposed solution looks correct, would you be able to submit it for review on review.spdk.io ?
