### ISSUE TITLE
[check_artifacts_size.sh] Removing oversized artifacts and failing the build

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#3042]
# CI Intermittent Failure

00:23:03.657  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:23:07.876  [Pipeline] sh
00:23:08.166  + jbp/jenkins/jjb-config/jobs/scripts/check_artifacts_size.sh
00:23:08.166  There are 2 files which size exeeds 250MB
00:23:08.166  ERROR: Removing oversized artifacts and failing the build
00:23:08.166  /var/jenkins/workspace/nvmf-tcp-phy-autotest/output/vfio_user_fuzz_log.txt
00:23:08.166  /var/jenkins/workspace/nvmf-tcp-phy-autotest/output/vfio_user_fuzz_tgt_output.txt
00:23:08.179  [Pipeline] }
00:23:08.182  ERROR: script returned exit code 5
00:23:08.195  [Pipeline] // catchError

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_105285.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_105285.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_105280.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_105326.html

**Comment by mikeBashStuff** [comment]
This was recently fixed on the jenkins side with an extra addition of https://review.spdk.io/gerrit/c/spdk/spdk/+/18441. I will leave this issue open for some time just in case it affected more patches out there.

**Comment by mikeBashStuff** [comment]
As per:

> This was recently fixed on the jenkins side with an extra addition of https://review.spdk.io/gerrit/c/spdk/spdk/+/18441. I will leave this issue open for some time just in case it affected more patches out there.

This issue can be closed.
