### ISSUE TITLE
[iscsi] Resetting the portal field in spdk_iscsi_conn

### ISSUE THREAD

**Issue by balamsg** [spdk/spdk#3043]
# Sighting report

While opening the portal , iscsi_conn_construct( ) gets called and the created portal gets assigned to the portal field of connection structure (i.e spdk_iscsi_conn ) as follows.

// conn.c
iscsi_conn_construct(struct spdk_iscsi_portal *portal,
		     struct spdk_sock *sock)
{
    .....
   conn = allocate_conn();
   .....
   conn->portal = portal;
  ......
}

So similarly, shouldnt we reset this field ( i.e conn->portal ) when we close & destroy the portal ?  But this not done in the below functions.

iscsi_portal_grp_release(struct spdk_iscsi_portal_grp *pg)
{
	iscsi_portal_grp_close(pg);
	iscsi_portal_grp_destroy(pg);
}

Any reasons behind this ?

**Comment by shuhei-matsumoto** [comment]
Hi @balamsg 

allocate_conn() clalls SPDK_ISCSI_CONNECTION_MEMSET. SPDK_ISCSI_CONNECTION_MEMSET clears conn->portal.
Hence, portal field is reset at allocation correctly?

#define SPDK_ISCSI_CONNECTION_MEMSET(conn)              \
        memset(&(conn)->portal, 0, sizeof(*(conn)) -    \
                offsetof(struct spdk_iscsi_conn, portal));

**Comment by balamsg** [comment]
Hi @shuhei-matsumoto , Yes memset is done while allocating which is called while opening the portal.
But  my question was while closing the portal. Shouldnt we reset the pointer after closing the portal as well ??

**Comment by shuhei-matsumoto** [comment]
Thank you @balamsg I understand what you asked now.

conn->portal is copied to conn->pg_tag, conn->portal_host, and conn->portal_port. Hence, conn is safe for portal removal. However, this may have bugs. Will you check?

**Comment by ksztyber** [comment]
[Bug scrub] There was no updates since last year, closing. @balamsg feel free to re-open if you have any updates.
