### ISSUE TITLE
[vfio]expect SPDK nvme perf to support multiple NVMe SSDs run I/O at the same time in multi-process with vfio driver

### ISSUE THREAD

**Issue by floraXiao** [spdk/spdk#3044]
# Sighting report

When opening 2 terminal to run I/O for 2 NVMe SSDs with perf with vfio driver, the second SSD report 
"EAL: Cannot open /dev/vfio/2: Device or resource busy
EAL: Failed to open VFIO group 2
EAL: Driver cannot attach the device (0000:06:00.0)
EAL: Failed to attach device on primary process
[2023-06-05 13:35:49.202878] nvme.c: 815:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2023-06-05 13:35:49.202892] nvme.c: 892:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '06:00.0'
./perf: errors occurred"

## Expected Behavior

Expected that the second SSD can run I/O success.

## Current Behavior

The 2nd SSD failed to run I/O when the 1st SSD running I/O. 

## Steps to Reproduce

1. ./setup.sh return modinfo: ERROR: Module vfio_iommu_type1 not found.
2. open a terminal, root@test-desktop:/../spdk/build/examples# ./perf -q 256 -o 4096 -w randread -c 0x01 -r 'trtype:PCIe traddr:0000:05:00.0' -t 300
3. open another terminal, root@test-desktop:/../spdk/build/examples# ./perf -q 256 -o 4096 -w randread -c 0x02 -r 'trtype:PCIe traddr:0000:06:00.0' -t 300
4. The device 05:00.0 can run I/O success, but the device 06:00.0 return an error:" TELEMETRY: No legacy callbacks, legacy socket not created
Initializing NVMe Controllers
EAL: Cannot open /dev/vfio/2: Device or resource busy
EAL: Failed to open VFIO group 2
EAL: Driver cannot attach the device (0000:06:00.0)
EAL: Failed to attach device on primary process
[2023-06-02 13:54:18.081018] nvme.c: 815:nvme_probe_internal: *ERROR*: NVMe ctrl                                                                             r scan failed
[2023-06-02 13:54:18.081027] nvme.c: 892:spdk_nvme_probe: *ERROR*: Create probe                                                                              context failed
spdk_nvme_probe() failed for transport address '0000:06:00.0'
./perf: errors occurred"

## Context (Environment including OS version, SPDK version, etc.)

OS: Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-149-generic x86_64)
SPDK version: v23.01-pre

**Comment by changpe1** [comment]
@floraXiao Your test case is really a common one, SPDK can support it well.  I suggest you to check your system configuration with vfio, e.g: vt-d is enabled or not, is `intel_iommu=on` in the booting parameter.

The other reason maybe related with your second SSD, you may use kernel driver to see it can work normally or not.

**Comment by floraXiao** [comment]
@changpe1 Thanks for your reply. I enable the vt-d in BIOS and config  amd_iommu=on in the booting parameter.  I want to konw if I configure it success.
_dmesg | grep -e DMAR -e IOMMU_
[    1.229151] pci 0000:00:00.2: AMD-Vi: IOMMU performance counters supported
[    1.230490] pci 0000:00:00.2: AMD-Vi: Found IOMMU cap 0x40
[    1.230790] perf/amd_iommu: Detected AMD IOMMU #0 (2 banks, 4 counters/bank).

_dmesg | grep -i iommu_
[    0.886634] iommu: Default domain type: Passthrough (set via kernel command l                                                                       ine)
[    1.229151] pci 0000:00:00.2: AMD-Vi: IOMMU performance counters supported
[    1.229381] pci 0000:00:01.0: Adding to iommu group 0
[    1.229409] pci 0000:00:01.2: Adding to iommu group 0
[    1.229428] pci 0000:00:02.0: Adding to iommu group 1
[    1.229463] pci 0000:00:03.0: Adding to iommu group 2
[    1.229489] pci 0000:00:03.1: Adding to iommu group 2
[    1.229515] pci 0000:00:03.3: Adding to iommu group 2
[    1.229535] pci 0000:00:04.0: Adding to iommu group 3
[    1.229556] pci 0000:00:05.0: Adding to iommu group 4
[    1.229578] pci 0000:00:07.0: Adding to iommu group 5
[    1.229604] pci 0000:00:07.1: Adding to iommu group 6
[    1.229627] pci 0000:00:08.0: Adding to iommu group 7
[    1.229652] pci 0000:00:08.1: Adding to iommu group 8
[    1.229674] pci 0000:00:14.0: Adding to iommu group 9
[    1.229690] pci 0000:00:14.3: Adding to iommu group 9
[    1.229722] pci 0000:00:18.0: Adding to iommu group 10
[    1.229738] pci 0000:00:18.1: Adding to iommu group 10
[    1.229754] pci 0000:00:18.2: Adding to iommu group 10
[    1.229769] pci 0000:00:18.3: Adding to iommu group 10
[    1.229785] pci 0000:00:18.4: Adding to iommu group 10
[    1.229801] pci 0000:00:18.5: Adding to iommu group 10
[    1.229817] pci 0000:00:18.6: Adding to iommu group 10
[    1.229833] pci 0000:00:18.7: Adding to iommu group 10
[    1.229856] pci 0000:01:00.0: Adding to iommu group 0
[    1.229877] pci 0000:01:00.1: Adding to iommu group 0
[    1.229897] pci 0000:01:00.2: Adding to iommu group 0
[    1.229915] pci 0000:02:00.0: Adding to iommu group 0
[    1.229932] pci 0000:02:08.0: Adding to iommu group 0
[    1.229953] pci 0000:03:00.0: Adding to iommu group 0
[    1.229974] pci 0000:03:00.1: Adding to iommu group 0
[    1.230002] pci 0000:04:00.0: Adding to iommu group 0
[    1.230031] pci 0000:05:00.0: Adding to iommu group 2
[    1.230061] pci 0000:06:00.0: Adding to iommu group 2
[    1.230088] pci 0000:07:00.0: Adding to iommu group 11
[    1.230122] pci 0000:08:00.0: Adding to iommu group 12
[    1.230151] pci 0000:08:00.1: Adding to iommu group 13
[    1.230181] pci 0000:08:00.3: Adding to iommu group 14
[    1.230210] pci 0000:08:00.4: Adding to iommu group 15
[    1.230490] pci 0000:00:00.2: AMD-Vi: Found IOMMU cap 0x40
[    1.230790] perf/amd_iommu: Detected AMD IOMMU #0 (2 banks, 4 counters/bank).

Running IO seperately on these 2 SSDs  with perf is successfully.  And using kernel driver, these 2 SSDs can run IO successfully at the same time.

**Comment by changpe1** [comment]
You may have a try with newer kernel to see this issue still exists or not, or you can switch to use Intel platform.

**Comment by floraXiao** [comment]
@changpe1 I found nothing output when execute "dmesg | grep DMAR".   Does my platform enable VT-d / IOMMU successfully?

**Comment by changpe1** [comment]
issue has been resolved via configuration parameters, closing it.

**Comment by ThomasJonathanJackson** [comment]
@changpe1 Could you be more specific about how it got resolved?
Thanks
