### ISSUE TITLE
How do I execute identify when running fio

### ISSUE THREAD

**Issue by zhuohaofan** [spdk/spdk#3048]
When running fio using the spdk engine, I can not execute identify on the nvme ssd.
The "identify " error message is:
`[2023-06-07 02:17:54.124610] pci.c:1037:spdk_pci_device_claim: *ERROR*: Cannot create lock on device /var/tmp/spdk_pci_lock_0000:01:00.0, probably process 3595 has claimed it
[2023-06-07 02:17:54.124629] nvme_pcie.c: 890:nvme_pcie_ctrlr_construct: *ERROR*: could not claim device 0000:01:00.0 (Permission denied)
[2023-06-07 02:17:54.124633] nvme.c: 677:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:01:00.0
EAL: Requested device 0000:01:00.0 cannot be used
No NVMe controllers found.
`
My spdk version is v22.08.
If I want to do this, what do I need to do?

**Comment by ksztyber** [comment]
Hi @zhuohaofan, you need to specify shared memory ID if you want to access a device from multiple processes.  With the nvme fio plugin (`examples/nvme/fio_plugin`), you can specify it in a config using `shm_id`, e.g.:
```
[global]
ioengine=spdk
shm_id=1
...
```
and specify the same ID when starting the identify app via the `-i` option:
```
$ build/examples/identify -i 1
```
