### ISSUE TITLE
How does spdk bind nvmf subsystem to a fixed core

### ISSUE THREAD

**Issue by fengjiansunren** [spdk/spdk#3049]
# Sighting report
spdk application have three reactor bind to core1, core2, core3; i just want nvmf-tcp target is created on core1 reactor, The other two cores have other uses，how to do ?
i find vhost_blk_controller and bdev can do this by rpc parameter specify core_mask

## Expected Behavior
nvmf-tcp target is created on core1

**Comment by changpe1** [comment]
RPC `nvmf_set_config` is used to do this, you can use it directly.

**Comment by fengjiansunren** [comment]
您好！已收到！

**Comment by fengjiansunren** [comment]
> RPC `nvmf_set_config` is used to do this, you can use it directly.

thanks
