### ISSUE TITLE
Slow blobstore loading

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#3053]
# Sighting report

Since we start to use smaller cluster size (we used to use 1GB cluster size, it's reduced to 32MB now), we observed blobstore loading slowness on large SSDs. The blobstore loading time for a 15TB SSD increased from 1 second to 34 seconds.

## Expected Behavior

I understand that smaller cluster size means more metadata to be loaded & processed during blobstore loading, but I'm not quite sure if the amount of increased time is expected, it sounds to me that something could be optimized.

## Current Behavior

Loading blobstore for a large SSD with 32MB cluster size takes 34 seconds, it used to take 1 second with 1GB cluster size.

## Steps to Reproduce

1. Create blobstore with 32MB cluster size over an 15TB SSD (4a0005:81:00.0 SAMSUNG MZWLR15THALA-00007 MPK92B5Q    0         15 TB);
2. Create few giant blobs to consume 90% of the SSD capacity;
3. Unload blobstore;
4. Load blobstore, it takes around 34 seconds;
5. Unload blobstore;
6. Load blobstore again, it takes around 1 second; (hitting SSD cache?)

BTW, even if the blobs are destroyed before step 3, the loading on step 4 is still slow.

## Context (Environment including OS version, SPDK version, etc.)

SPDK v22.01.2

**Comment by tomzawadzki** [comment]
Can you please expand on some of the reproduction steps ?
> Create blobstore with 32MB cluster size over an 15TB SSD (4a0005:81:00.0 SAMSUNG MZWLR15THALA-00007 MPK92B5Q 0 15 TB);

1) Were `struct spdk_bs_opts` modified ?

> Create few giant blobs to consume 90% of the SSD capacity;

2) Similar to above, what were the `struct spdk_blob_opts` options. If thin provisioned, was there any data written before unloading ?

> Unload blobstore;
> Load blobstore, it takes around 34 seconds;

3) Did the blobstore unload cleanly or did the blobstore load go through recovery path ? You can either check the bserrno in the unload call back or check SPDK notice logs during load.

> SPDK v22.01.2

4) Is this something you've encountered on supported versions of SPDK, either SPDK v23.01.1 LTS or SPDK v23.05 ?

**Comment by tomzawadzki** [comment]
@NiuYawei any updates on the above ?

**Comment by tanabarr** [comment]
My initial answers are:
1. no I don't think these were adjusted for the SPDK-only reproducer but when calling in DAOS these opts are calculated, @NiuYawei to confirm
2. no (as above)
3. ? need to check
4. only tried with v22.01, we are in the process of updating to v24.09 and need to try with that.

The suspicion is that if unload is forced then the identifier that enables quick load isn't written on cleanup resulting in slow "reload" times. This maybe being seen in DAOS if engines are killed with SIGKILL which doesn't enable SPDK to execute cleanup routines within the signal handler. 

Revisit reproducer and check the items above.
