### ISSUE TITLE
vhost-blk/qos->thread: switching from default app_thread to the spdk_thread thread of the vhost instance reduce cross-thread and improve performance

### ISSUE THREAD

**Issue by liuqinfei** [spdk/spdk#3060]
# Sighting report

The default qos->thread of vhost-blk is app_thread.  So when i deploy vhost-blk instances over all the NUMA nodes. All of the qos caculating will be sent to the app_thread. The hotpot of cross-thread overthread is very high. And the performance of vhost QoS verification cases is reduced.
## Expected Behavior

Switching qos->thread to the spdk_thread thread of the vhost instance reduces cross-thread overhead and improves performance.

## Current Behavior
The qos->thread of spdk_bdev is choosen by the fist spdk_thrad of  g_threads. It seems that the fisrt  spdk_thread is always app_thread for vhost_blk.

## Possible Solution
When we set the qos->thread, we may check and get the first spdk_thread without the app_thread.

## Steps to Reproduce

1. Just the deployment of Vhost-blk.
2. run case 2 of QOS. 
Reference: https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2301.pdf

## Context (Environment including OS version, SPDK version, etc.)
spdk 23.01
NAME="openEuler"
VERSION="22.03 (LTS-SP1)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP1)"
ANSI_COLOR="0;31"

**Comment by jimharris** [comment]
The problem here is that spdk_vhost_blk_construct() allocates a "dummy" io channel, see comment on line 1652:

```
1651         /*
1652          * When starting qemu with multiqueue enable, the vhost device will
1653          * be started/stopped many times, related to the queues num, as the
1654          * exact number of queues used for this device is not known at the time.
1655          * The target has to stop and start the device once got a valid IO queue.
1656          * When stopping and starting the vhost device, the backend bdev io device
1657          * will be deleted and created repeatedly.
1658          * Hold a bdev reference so that in the struct spdk_vhost_blk_dev, so that
1659          * the io device will not be deleted.
1660          */
```

This gets called from RPC context, which always runs on the app thread.  The bdev layer uses spdk_for_each_channel to enable QOS, since the app thread is always the first thread to be iterated, that's where the qos context gets constructed.

Probably the bdev layer should wait to allocate the qos context until the first I/O is detected.  We could add some kind of explicit API to allow the upper layer to pick where the QoS handling should occur, but that's just more complexity that I don't think is needed.

**Comment by liuqinfei** [comment]
@jimharris Thanks for the analysis. However, This has a big impact on the performance for the Case 2 in [reprot](https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2301.pdf). With the hotpot of QOS, i can only get less than 90% throughput of expected throughput. For example, vhost-blk, 48VM, set qos: 10K iops per VM, i can only get about 430 KIOPS. 
So, i try to fix this issue. I do only implement in the API bdev_enable_qos as following. So, what do you think about this?  

static void
bdev_enable_qos(struct spdk_bdev *bdev, struct spdk_bdev_channel *ch)
{
	struct spdk_bdev_qos	*qos = bdev->internal.qos;
	int			i;

	assert(spdk_spin_held(&bdev->internal.spinlock));

	/* Rate limiting on this bdev enabled */
	if (qos) {
		bool is_app_thread = spdk_get_thread() == spdk_thread_get_app_thread();
		if (qos->ch == NULL && !is_app_thread) {
		 ...
		    qos->poller = SPDK_POLLER_REGISTER(bdev_channel_poll_qos,
							   qos,
							   SPDK_BDEV_QOS_TIMESLICE_IN_USEC);
		}

		ch->flags |= BDEV_CH_QOS_ENABLED;
	}
}

**Comment by liuqinfei** [comment]
And I have submit a PR [#18999](https://review.spdk.io/gerrit/c/spdk/spdk/+/18999) to fix that.
In this PR, i just switch to the vhost thread to allocate the "dummy" io channel.

**Comment by changpe1** [comment]
> And I have submitted a PR [#18999](https://review.spdk.io/gerrit/c/spdk/spdk/+/18999) to fix that. In this PR, i just switch to the vhost thread to allocate the "dummy" io channel.

In very recent changes in SPDK vhost, we will not start/stop device multiple times, so we can just remove the dummy IO channel code.

**Comment by liuqinfei** [comment]
@changpe1 So, you will fix that issue soon?

**Comment by changpe1** [comment]
> @changpe1 So, you will fix that issue soon?

OK, here it is, https://[review.spdk.io/gerrit/c/spdk/spdk/+/19300](https://review.spdk.io/gerrit/c/spdk/spdk/+/19300)

**Comment by tomzawadzki** [comment]
Hi @liuqinfei, patch https://review.spdk.io/gerrit/c/spdk/spdk/+/19300 was merged. Can you confirm this resolves your issue ?

**Comment by liuqinfei** [comment]
THX. And when i check and get the result, i will let you know.

**Comment by tomzawadzki** [comment]
Closing the issue since https://review.spdk.io/gerrit/c/spdk/spdk/+/19300 was merged. @liuqinfei please feel free to re-open if there is more to resolve in this issue.
