### ISSUE TITLE
Question about spdk

### ISSUE THREAD

**Issue by zhangsen1121** [spdk/spdk#3064]
1. we run into a case that we need to discard certain cluster(s), is there any suggesions?
2. our spdk is a bit old(v20.10), read/write request may run into EIO (actually is caused by memory allocation failure), do u have any suggestions?

thanks a lot!

**Comment by tomzawadzki** [comment]
Hi @zhangsen1121 please do expand on specifics of your questions. Either describe the scenario more in general, provide some specific interactions you are doing with SPDK or the best would be step-by-step.

Please do note that SPDK v20.10 is very outdated at this point, updating would be best course of action for most cases.
SPDK supports only latest release (v23.05 right now) and latest LTS (v23.01.1 right now). Obviously questions/bug reports against the 'master' development branch are welcome too.

**Comment by tomzawadzki** [comment]
@zhangsen1121 Please feel free to re-open the issue if you have any further questions.
Remember that you can join us on Slack too ! https://spdk.io/community/
