### ISSUE TITLE
[bdev_qos_bw] Failure when executing the test

### ISSUE THREAD

**Issue by mariuszbarczak** [spdk/spdk#3066]
# CI Intermittent Failure

## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-per-patch_106919.html
https://ci.spdk.io/results/autotest-per-patch/builds/106919/archive/freebsd-vg-autotest/build.log

## Execution failed at

00:05:28.509  ========== Backtrace start: ==========
00:05:28.509  
00:05:28.509  in /usr/home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1097 -> run_test(["blockdev_general"],["/usr/home/vagrant/spdk_repo/spdk/test/bdev/blockdev.sh"])
00:05:28.509       ...
00:05:28.509     1092		timing_enter $test_name
00:05:28.509     1093		echo "************************************"
00:05:28.509     1094		echo "START TEST $test_name"
00:05:28.509     1095		echo "************************************"
00:05:28.509     1096		xtrace_restore
00:05:28.509     1097		time "$@"
00:05:28.509     1098		xtrace_disable
00:05:28.509     1099		echo "************************************"
00:05:28.509     1100		echo "END TEST $test_name"
00:05:28.509     1101		echo "************************************"
00:05:28.509     1102		timing_exit $test_name
00:05:28.509       ...
00:05:28.509  in /usr/home/vagrant/spdk_repo/spdk/autotest.sh:176 -> main(["/usr/home/vagrant/spdk_repo/autorun-spdk.conf"])
00:05:28.509       ...
00:05:28.509     171 		run_test "accel" $rootdir/test/accel/accel.sh
00:05:28.509     172 		run_test "app_cmdline" $rootdir/test/app/cmdline.sh
00:05:28.509     173 		run_test "version" $rootdir/test/app/version.sh
00:05:28.509     174 	
00:05:28.509     175 		if [ $SPDK_TEST_BLOCKDEV -eq 1 ]; then
00:05:28.509  => 176 			run_test "blockdev_general" $rootdir/test/bdev/blockdev.sh
00:05:28.509     177 			run_test "bdev_raid" $rootdir/test/bdev/bdev_raid.sh
00:05:28.509     178 			run_test "bdevperf_config" $rootdir/test/bdev/bdevperf/test_config.sh
00:05:28.509     179 			if [[ $(uname -s) == Linux ]]; then
00:05:28.509     180 				run_test "reactor_set_interrupt" $rootdir/test/interrupt/reactor_set_interrupt.sh
00:05:28.509     181 				run_test "reap_unregistered_poller" $rootdir/test/interrupt/reap_unregistered_poller.sh
00:05:28.509       ...
00:05:28.509  
00:05:28.509  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mariuszbarczak. log: https://ci.spdk.io/public_build/autotest-per-patch_106919.html

**Comment by tomzawadzki** [comment]
[Bug scrub] The crucial part of failure is at:
```
00:05:28.508  Failed to limit the io read rate of NULL bdev by qos
00:05:28.508   12:21:01	-- bdev/blockdev.sh@400 -- # echo 'Failed to limit the io read rate of NULL bdev by qos'
00:05:28.508   12:21:01	-- bdev/blockdev.sh@401 -- # rpc_cmd bdev_malloc_delete Malloc_0
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_112287.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_114090.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_114605.html

**Comment by kgodzwox** [comment]
- Issue stress tested via CI with `ubuntu22-vg-autotest`: 50 runs, **no repro**.
- Issue was tested manually on the VM using spdk `autorun.sh`: **no repro**.
- Issue was tested manually according to the steps below (using the ubuntu22 CI image where the issue appeared, looking at the latest available logs): **no repro**.

1. `spdk/build/examples/bdevperf -z -m 0x2 -q 256 -o 4096 -w randread -t 60 '' &`
2. `./scripts/rpc.py bdev_malloc_create -b Malloc_0 128 512`
`./scripts/rpc.py bdev_get_bdevs -b Malloc_0 -t 2000`
`./scripts/rpc.py bdev_null_create Null_1 128 512`
`./scripts/rpc.py bdev_get_bdevs -b Null_1 -t 20001`

3. `/home/vagrant/spdk_repo/spdk/examples/bdev/bdevperf/bdevperf.py perform_tests &`
`./scripts/iostat.py -d -i 1 -t 5 &`

4. `./scripts/rpc.py bdev_set_qos_limit --rw_ios_per_sec 14000 Malloc_0`
5. VERIFY OUTPUT
```
Device    tps       KB_read/s  KB_wrtn/s  KB_dscd/s  KB_read    KB_wrtn  KB_dscd
Malloc_0  13998.10  55992.41   0.00       0.00       57008.00   0.00     0.00
```
6. `./scripts/rpc.py bdev_set_qos_limit --rw_mbytes_per_sec 10 Null_1`
7. VERIFY OUTPUT
```
Device    tps       KB_read/s  KB_wrtn/s  KB_dscd/s  KB_read   KB_wrtn  KB_dscd
Null_1    2561.58   10246.31   0.00       0.00       10372.00  0.00     0.00
```
8. `./scripts/rpc.py bdev_set_qos_limit --r_mbytes_per_sec 2 Malloc_0`
9. VERIFY OUTPUT
```
Device    tps      KB_read/s  KB_wrtn/s  KB_dscd/s  KB_read   KB_wrtn  KB_dscd
Malloc_0  511.84   2047.36    0.00       0.00       2076.00   0.00     0.00
```

After verifying there is no reproduction, I suspect changes in the CI configuration. The issue, according to the available logs, occurred during tests on the `VM-host-SM4` machine, which was overloaded (too many executors per node). The last issue log was recorded on 3rd January, and the configuration change for this machine was done on 9th January. The excessive load on the machine (running out of RAM, etc.) could have affected the results, which slightly deviated from the accepted min/max limits.

Closing. Feel free to open if the issue happens again.
