### ISSUE TITLE
[vfio_user_fio] vm_wait_for_boot timed out

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#3067]
```
00:06:38.861   16:55:47	-- vhost/common.sh@883 -- # for vm in $vms_to_run
00:06:38.861   16:55:47	-- vhost/common.sh@884 -- # vm_is_running 2
00:06:38.861   16:55:47	-- vhost/common.sh@357 -- # vm_num_is_valid 2
00:06:38.861   16:55:47	-- vhost/common.sh@297 -- # [[ 2 =~ ^[0-9]+$ ]]
00:06:38.861   16:55:47	-- vhost/common.sh@297 -- # return 0
00:06:38.861   16:55:47	-- vhost/common.sh@358 -- # local vm_dir=/root/vhost_test/vms/2
00:06:38.861   16:55:47	-- vhost/common.sh@360 -- # [[ ! -r /root/vhost_test/vms/2/qemu.pid ]]
00:06:38.861   16:55:47	-- vhost/common.sh@361 -- # return 1
00:06:38.861   16:55:47	-- vhost/common.sh@889 -- # notice 'running /root/vhost_test/vms/2/run.sh'
00:06:38.861   16:55:47	-- vhost/common.sh@93 -- # message INFO 'running /root/vhost_test/vms/2/run.sh'
00:06:38.861   16:55:47	-- vhost/common.sh@59 -- # local verbose_out
00:06:38.861   16:55:47	-- vhost/common.sh@60 -- # false
00:06:38.861   16:55:47	-- vhost/common.sh@61 -- # verbose_out=
00:06:38.861   16:55:47	-- vhost/common.sh@68 -- # local msg_type=INFO
00:06:38.861   16:55:47	-- vhost/common.sh@69 -- # shift
00:06:38.861   16:55:47	-- vhost/common.sh@70 -- # echo -e 'INFO: running /root/vhost_test/vms/2/run.sh'
00:06:38.861  INFO: running /root/vhost_test/vms/2/run.sh
00:06:38.861   16:55:47	-- vhost/common.sh@890 -- # /root/vhost_test/vms/2/run.sh
00:06:38.861  Running VM in /root/vhost_test/vms/2
00:06:39.118  Waiting for QEMU pid file
00:06:40.490  === qemu.log ===
00:06:40.490  === qemu.log ===
00:06:40.490   16:55:48	-- nvme/vfio_user_fio.sh@53 -- # vm_wait_for_boot 60 0 1 2
00:06:40.490   16:55:48	-- vhost/common.sh@926 -- # assert_number 60
00:06:40.491   16:55:48	-- vhost/common.sh@269 -- # [[ 60 =~ [0-9]+ ]]
00:06:40.491   16:55:48	-- vhost/common.sh@269 -- # return 0
00:06:40.491   16:55:48	-- vhost/common.sh@928 -- # xtrace_disable
00:06:40.491   16:55:48	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:06:40.491   16:55:48	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:06:40.491   16:55:48	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:06:40.491   16:55:48	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:06:40.491   16:55:48	-- common/autotest_common.sh@25 -- # set +x
00:06:40.491  INFO: Waiting for VMs to boot
00:06:40.491  INFO: waiting for VM0 (/root/vhost_test/vms/0)
00:08:01.921  WARN: timeout waiting for machines to boot
00:08:01.921  WARN: ================
00:08:01.921  WARN: QEMU LOG:
00:08:01.921  WARN: VM LOG:
...
00:08:01.924  in /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/vfio_user/nvme/common.sh:53 -> clean_vfio_user([""],["53"])
00:08:01.924       ...
00:08:01.924  backtrace unavailable
00:08:01.924       ...
00:08:01.924  in /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/vfio_user/nvme/vfio_user_fio.sh:53 -> main([])
00:08:01.924       ...
00:08:01.924     48  		vm_setup --disk-type=vfio_user --force=$i --os=$VM_IMAGE --memory=768 --disks="$i"
00:08:01.924     49  		used_vms+=" $i"
00:08:01.924     50  	done
00:08:01.924     51  	
00:08:01.924     52  	vm_run $used_vms
00:08:01.924  => 53  	vm_wait_for_boot 60 $used_vms
00:08:01.924     54  	
00:08:01.924     55  	timing_exit launch_vms
00:08:01.924     56  	
00:08:01.924     57  	timing_enter run_vm_cmd
00:08:01.924     58  	
00:08:01.924       ...
```

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/106944/archive/vfio-user-phy-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_106944.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_106944.html

**Comment by changpe1** [comment]
Still looks like a QEMU issue, but with this new QEMU version, since no coredump happened compared with previous one, so can't confirm it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_107045.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107268.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_107701.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_107866.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_108117.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_108022.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mariuszbarczak. log: https://ci.spdk.io/public_build/autotest-per-patch_108346.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @sberbz. log: https://ci.spdk.io/public_build/autotest-per-patch_108548.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_108885.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_108965.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_109071.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_109129.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_109166.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_109381.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ehaligow. log: https://ci.spdk.io/public_build/autotest-per-patch_109372.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_109651.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_109666.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ehaligow. log: https://ci.spdk.io/public_build/autotest-per-patch_109687.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ehaligow. log: https://ci.spdk.io/public_build/autotest-per-patch_109837.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_110002.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_109982.html

**Comment by tomzawadzki** [comment]
Bunch of latest reports seem unrelated to original issue and are misreports of new issue. The concerning part of logs start at:
```
00:05:57.642  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/cgroups.sh: line 33: syntax error near unexpected token `('
00:05:57.642  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/cgroups.sh: line 33: `		for pid in /proc/+([0-9]); do'
00:05:57.643  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/common.sh: line 87: syntax error near unexpected token `('
00:05:57.643  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/common.sh: line 87: `	for node in "$sysfs_node/node"+([0-9]); do'
00:05:57.643  Running VM in /root/vhost_test/vms/0
00:05:57.643  /root/vhost_test/vms/0/run.sh: line 64: get_cgroup: command not found
00:05:57.643  /root/vhost_test/vms/0/run.sh: line 65: set_cgroup_attr_top_bottom: command not found
00:05:57.643  /root/vhost_test/vms/0/run.sh: line 66: create_cgroup: command not found
00:05:57.643  /root/vhost_test/vms/0/run.sh: line 67: set_cgroup_attr: command not found
00:05:57.643  /root/vhost_test/vms/0/run.sh: line 68: set_cgroup_attr: command not found
```
Which could potentially be related to this series - https://review.spdk.io/gerrit/c/spdk/spdk/+/19678.

@mikeBashStuff Could you take a look ?

**Comment by mikeBashStuff** [comment]
> Bunch of latest reports seem unrelated to original issue and are misreports of new issue. The concerning part of logs start at:
> 
> ```
> 00:05:57.642  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/cgroups.sh: line 33: syntax error near unexpected token `('
> 00:05:57.642  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/cgroups.sh: line 33: `		for pid in /proc/+([0-9]); do'
> 00:05:57.643  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/common.sh: line 87: syntax error near unexpected token `('
> 00:05:57.643  /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/scheduler/common.sh: line 87: `	for node in "$sysfs_node/node"+([0-9]); do'
> 00:05:57.643  Running VM in /root/vhost_test/vms/0
> 00:05:57.643  /root/vhost_test/vms/0/run.sh: line 64: get_cgroup: command not found
> 00:05:57.643  /root/vhost_test/vms/0/run.sh: line 65: set_cgroup_attr_top_bottom: command not found
> 00:05:57.643  /root/vhost_test/vms/0/run.sh: line 66: create_cgroup: command not found
> 00:05:57.643  /root/vhost_test/vms/0/run.sh: line 67: set_cgroup_attr: command not found
> 00:05:57.643  /root/vhost_test/vms/0/run.sh: line 68: set_cgroup_attr: command not found
> ```
> 
> Which could potentially be related to this series - https://review.spdk.io/gerrit/c/spdk/spdk/+/19678.
> 
> @mikeBashStuff Could you take a look ?

https://review.spdk.io/gerrit/c/spdk/spdk/+/19923

**Comment by mikeBashStuff** [comment]
Also, this part is not really relevant, since it would not prevent qemu from being executed. From the logs you can actually see that qemu is indeed running.

**Comment by tomzawadzki** [comment]
[Bug scrub] @mikeBashStuff Thanks for clarifying, then the few recent report seem to be correct.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_110663.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_110811.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_111164.html

**Comment by mikeBashStuff** [comment]
@tomzawadzki This is the issue I had in mind: https://github.com/spdk/spdk/issues/3109#issuecomment-1698507212

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_112069.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_112158.html
