### ISSUE TITLE
nvmf/rdma: Issues with advertised number of SGEs

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#3069]
# Sighting report

While using more modifying SPDK_NVMF_MAX_SGL_ENTRIES from 16 to 30 and instructing the initiator to use more than 16 SGEs in a write reques, we were running into a timeout.
Basically, the IO never completes since we can only have 16 outstanding RDMA_READs (max_qp_init_rd_atom)
Here's the relevant code:
```
max_read_depth = spdk_min(max_read_depth, port->device->attr.max_qp_init_rd_atom); // 16 since CX6 returns 16
...
case RDMA_REQUEST_STATE_DATA_TRANSFER_TO_CONTROLLER_PENDING:
if (rqpair->current_send_depth + rdma_req->num_outstanding_data_wr > rqpair->max_send_depth
                || rqpair->current_read_depth + rdma_req->num_outstanding_data_wr > rqpair->max_read_depth) {
                /* We can only have so many WRs outstanding. we have to wait until some finish. */
                rqpair->poller->stat.pending_rdma_read++;
                break;
            }
...
```
Like with 17 SGEs, we create num_outstanding_data_wr=17 but max_read_depth is 16 and therefore we always hit the break and never make any progress with this request.

Alexey found a couple of issues with using SPDK_NVMF_MAX_SGL_ENTRIES = 16 and max_qp_init_rd_atom being less than 16.

## Expected Behavior

Ideally, we should be able to support max_sges that the HW supports. For CX6, max_sges is 30 but max_qp_init_rd_atom is 16.

## Context (Environment including OS version, SPDK version, etc.)
SPDK 23.01

**Comment by AlekseyMarchuk** [comment]
From my point of view, the main issue here is that we report `msdbd = SPDK_NVMF_MAX_SGL_ENTRIES = 16`
If there is a HW which supports `max_qp_init_rd_atom < 16` then we'll have the same situation as @mhae 
That could be a  historical reason or just a coincidence that SPDK_NVMF_MAX_SGL_ENTRIES matches max_qp_init_rd_atom which is reported by majority of RDMA NICs
The easiest fix would be to set msdbd = max_qp_init_rd_atom (min value among all NICs) since we use RDMA_READs to handle write IO with multiple SGL entries.

**Comment by jchachux** [comment]
Performance tests were completed today. No issues were observed in the test results.

You can review the detailed results at the link below:

[SPDK NVMe-oF RDMA Performance Results](https://performance.spdk.io/d/upDz4sOVz/spdk-nvme-of-rdma-performance?orgId=1&refresh=5s&from=now-7d&to=now&var-cpus=4&var-qd=64&var-rw=randread&var-manual_builds=true)
Timestamp  "20-07-2023, 11:32:12" on commit 0c9dacc40.

**Comment by karlatec** [comment]
@jchachux thanks for doing this for me!
@AlekseyMarchuk FYI in case the dashboard opens the same way for you as it did for me: set `manual_builds` and `Build annotations` to `true`. This way you will exactly know which builds to look at.
