### ISSUE TITLE
NVMe simple_copy and connect_stress tests always return RC=0

### ISSUE THREAD

**Issue by jsawickx** [spdk/spdk#3071]
# Sighting report

After running the NVMe tests: simple_copy (https://github.com/spdk/spdk/blob/master/test/nvme/simple_copy/simple_copy.c) and connect_stress (https://github.com/spdk/spdk/blob/master/test/nvme/connect_stress/connect_stress.c), I noticed that test always returns RC=0, even though stderr returns ERROR information. After reviewing the code, you can see that this value is set "rigidly".

## Expected Behavior

After performing the tests, the RC value should be returned depending on the test result. RC=0 should only appear if there are no errors.

## Current Behavior

After performing the tests, the RC value is always returned as 0, even though there is error returned.

## Possible Solution

In connect_stress test:
1. return RC from line: https://github.com/spdk/spdk/blob/master/test/nvme/connect_stress/connect_stress.c#L268 on line: https://github.com/spdk/spdk/blob/master/test/nvme/connect_stress/connect_stress.c#L271

In simple_copy test:
1. add returning appropriate error codes in the simple_copy_test() method (https://github.com/spdk/spdk/blob/master/test/nvme/simple_copy/simple_copy.c#L471)
2. return at the end of the main() method (https://github.com/spdk/spdk/blob/master/test/nvme/simple_copy/simple_copy.c#L471), the value returned from the simple_copy_test() method

## Steps to Reproduce

Look at the end of the code of those tests.

## Context (Environment including OS version, SPDK version, etc.)

Tests are available on the latest master branch.

**Comment by shuhei-matsumoto** [comment]
Hi @jsawickx, Thank  you for reporting this issue.

For test/nvme/connect_stress, I created a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/19342 to return EXIT_FAILURE if test_controller() returned non-zero value.

On the other hand, test/nvme/simple_copy() already uses exit(1) nicely if the test failed. Will you check the usage of exit(1) of the simple_copy program? These are good enough?

**Comment by shuhei-matsumoto** [comment]
I want to hear the opinion of the original author of the connect_stress program. @jimharris the connect_stress program returns always 0 but this may be your intention. Will you check this issue report when you can?

**Comment by jimharris** [comment]
> I want to hear the opinion of the original author of the connect_stress program. @jimharris the connect_stress program returns always 0 but this may be your intention. Will you check this issue report when you can?

Your patch is correct @shuhei-matsumoto.  You could also just return rc, but the ternary operator you have is more precise.  I added my +2.

**Comment by shuhei-matsumoto** [comment]
Thank you Jim

**Comment by tomzawadzki** [comment]
[Bug scrub] @jsawickx Have you been able to produce incorrect return from `simple_copy` ? If so, what lead to that ?

**Comment by jsawickx** [comment]
Hi @tomzawadzki, @shuhei-matsumoto,
Regarding the "simple_copy" test, It seems that I misread the code, because when the test fails it returns RC=1. So in this case everything is correct.

**Comment by tomzawadzki** [comment]
@jsawickx Thank you for the original report and double checking :) I'll close the issue then (you can do so in the future too!).
