### ISSUE TITLE
NVMe reset test return RC=0 even though there was an ERROR

### ISSUE THREAD

**Issue by jsawickx** [spdk/spdk#3072]
# Sighting report

After running the NVMe test: reset (https://github.com/spdk/spdk/blob/master/test/nvme/reset/reset.c) I got the following output:
```
Starting thread on core 0
========================================================
         6465550 IO completed successfully
               1 IO completed with error
--------------------------------------------------------
         6465551 IO completed total
         6465551 IO submitted
```
... despite the fact that there is information that 1 IO ended with ERROR, the test returns RC=0.

## Expected Behavior

After getting output that some IO has completed with error, test app should return RC different than 0.

## Current Behavior

After getting output that some IO has completed with error, test app return RC=0.

## Steps to Reproduce

Look at the code of this test or perform failing test.

## Context (Environment including OS version, SPDK version, etc.)

Tests are available on the latest master branch.

**Comment by ksztyber** [comment]
This application resets NVMe controllers while sending IO, so it is perfectly fine for some IOs to be failed, so it doesn't make sense for the app to exit with non-zero status when that happens. I'm going to close this issue, but feel free to re-open it, in case you have more related questions.
