### ISSUE TITLE
nvmf: adding second listener with same transport but different secure channel should fail

### ISSUE THREAD

**Issue by glimchb** [spdk/spdk#3073]
copy from slack : no error if I issue those 2 commands one after another:
```
./rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a  10.10.2.2 -f ipv4 -s 4420
./rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a  10.10.2.2 -f ipv4 -s 4420 --secure-channel
```
What people think about failing the second RPC ?
Otherwise the user can think that secure channel was established, but not really...

Proposed patch https://review.spdk.io/gerrit/c/spdk/spdk/+/19082

Reproduction example:
```
./build/bin/spdk_tgt -m 0x1 -s 512 --no-pci &
./scripts/rpc.py nvmf_create_transport -t TCP -u 8192 -m 4 -c 0 
./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
./scripts/rpc.py nvmf_subsystem_allow_any_host nqn.2016-06.io.spdk:cnode1 --disable
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a  127.0.0.1 -f ipv4 -s 4420
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a  127.0.0.1 -f ipv4 -s 4420 --secure-channel
```

@KKaras169169 please review

**Comment by glimchb** [comment]
@jimharris can you please help me get `secure_channel` from `listener` object in a better way then parsing json ?
https://review.spdk.io/gerrit/c/spdk/spdk/+/19082
thanks

**Comment by glimchb** [comment]
tested
```
./build/bin/spdk_tgt -m 0x1 -s 512 --no-pci &
./scripts/rpc.py nvmf_create_transport -t TCP -u 8192 -m 4 -c 0 
./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
./scripts/rpc.py nvmf_subsystem_allow_any_host nqn.2016-06.io.spdk:cnode1 --disable
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a  127.0.0.1 -f ipv4 -s 4420
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a  127.0.0.1 -f ipv4 -s 4420 --secure-channel
```
output
```
[2023-07-18 21:20:44.975046] nvmf_rpc.c: 921:rpc_nvmf_subsystem_add_listener: *NOTICE*: TLS support is considered experimental
[2023-07-18 21:20:44.975151] nvmf_rpc.c: 769:nvmf_rpc_listen_paused: *NOTICE*: Listener already exists, not adding another one
[2023-07-18 21:20:44.975173] nvmf_rpc.c: 772:nvmf_rpc_listen_paused: *ERROR*: Not allowed to change listener secure channel
request:
{
  "nqn": "nqn.2016-06.io.spdk:cnode1",
  "secure_channel": true,
  "listen_address": {
    "trtype": "tcp",
    "traddr": "127.0.0.1",
    "trsvcid": "4420",
    "adrfam": "ipv4"
  },
  "method": "nvmf_subsystem_add_listener",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}
```

**Comment by KKaras169169** [comment]
I left a comment on your proposed patch. I think we can skip checking `secure_channel`, as this limits us in the future, if we ever introduce more parameters that should not be changed in a running listener - instead lets just inform the user that we do not overwrite existing listeners and ignore any changes in parameters.

**Comment by tomzawadzki** [comment]
[Bug scrub] @glimchb Do you plan to continue to iterate on the patch with proposed solution https://review.spdk.io/gerrit/c/spdk/spdk/+/19082/ ? Asking mainly in context of the upcoming SPDK 23.09 release.

**Comment by glimchb** [comment]
@tomzawadzki waiting for feedback from @ksztyber and @KKaras169169 how to continue

**Comment by glimchb** [comment]
@slawekptak I can, but not sure if the commenters and maintainers agreed on the implementation direction... any suggestions ?

**Comment by slawekptak** [comment]
I agree we should return an error in such a case - this is related to security. Would it make sense to rebase your patches and use the listener->opts.secure_channel for the check?

**Comment by tomzawadzki** [comment]
@glimchb - @slawekptak has taken your proposal and updated it, along with adding a test for it - https://review.spdk.io/gerrit/c/spdk/spdk/+/22786. Please take a look if you are fine with.

**Comment by glimchb** [comment]
yep!
