### ISSUE TITLE
 "error while loading shared libraries" when using shared libraries outside the SPDK installation path

### ISSUE THREAD

**Issue by ironmn** [spdk/spdk#3074]
# Sighting report

I want to write my application outside spdk's installation path so that I can clearly divede the libs and the logical code. So I followed the instructions in [this page](https://spdk.io/doc/libraries.html) and used the "libspdk.so" shared library for linking. The compilation was successful after using the "make" command. However, during runtime, I encountered the following error: "error while loading shared libraries: libspdk_env_dpdk.so.12.0: cannot open shared object file: No such file or directory."
The example code I used is `hello_blob.c` and I didn't change any line of it. It was put in `~/test` path. And spdk is installed in `~/DPDK/spdk` path. The Makefile of `test` folder is just below:
```Makefile
APP = hello_blob
SRCS-y := hello_blob.c
SPDK_DIR := /home/xym/DPDK/spdk
PKG_CONFIG_PATH := $(SPDK_DIR)/build/lib/pkgconfig
ISAL_DIR := $(SPDK_DIR)/isa-l

SPDK_PC_FILES := spdk_env_dpdk
all: shared static
.PHONY: shared static
shared: build/$(APP)-shared
	ln -sf $(APP)-shared build/$(APP)
static: build/$(APP)-static
	ln -sf $(APP)-static build/$(APP)
# $(foreach PC_FILE,$(SPDK_PC_FILES),ifneq ($(shell PKG_CONFIG_PATH="$(PKG_CONFIG_PATH)" pkg-config --exists $(PC_FILE) && echo 0),0) $(error "no installation of $(PC_FILE)") endif)

CFLAGS +=  $(shell PKG_CONFIG_PATH="$(PKG_CONFIG_PATH)" pkg-config --cflags $(SPDK_PC_FILES))


SPDK_SHARED_LIB := $(shell PKG_CONFIG_PATH="$(PKG_CONFIG_PATH)" pkg-config --libs $(SPDK_PC_FILES))
SPDK_SHARED_LIB += -lspdk
SPDK_STATIC_LIB := $(shell PKG_CONFIG_PATH="$(PKG_CONFIG_PATH)" pkg-config --libs --static $(SPDK_PC_FILES))


build/$(APP)-shared: $(SRCS-y) Makefile | build
	$(CC) $(CFLAGS) $(SRCS-y) -o $@ $(LDFLAGS) $(SPDK_SHARED_LIB)
build/$(APP)-static: $(SRCS-y) Makefile | build
	$(CC) $(CFLAGS) $(SRCS-y) -o $@ $(LDFLAGS) $(SPDK_STATIC_LIB) 
build:
	@mkdir -p $@

.PHONY: clean
clean:
	rm -f build/$(APP) build/$(APP)-shared
	test -d build && rmdir -p build || true
# hello_blob: hello_blob.c
# 	$(CC) -o $(APP) hello_blob.c -pthread -Wl,--no-as-needed $(SPDK_LIB) $(DPDK_LIB) -Wl,--as-needed
```
The spdk version is 23.03. And I compile the shared libraries by command `./configure --with-shared ` then `make`.

## Expected Behavior
On anther computer of my own, I didn't use the `--with-shared` parameter, just use normal `./configure`, it turned out OK. The `hello_blob` example program output the information about the bdev. So, if linking is correct, it will do the same thing.

## Current Behavior

I didn't put spdk's libraries into system-wide place. So I use the `-L` option when linking. 
The output message in bash is ：
```bash
xym@xinjinbo02:~/test$ make shared 
cc -I/home/xym/DPDK/spdk/build/include hello_blob.c -o build/hello_blob-shared  -L/home/xym/DPDK/spdk/build/lib -L/home/xym/DPDK/spdk/dpdk/build/lib -lspdk_env_dpdk -lspdk_util -lspdk_log -lrte_eal -lrte_mempool -lrte_ring -lrte_mbuf -lrte_bus_pci -lrte_pci -lrte_mempool_ring -lrte_telemetry -lrte_kvargs -lrte_power -lrte_ethdev -lrte_net -lrte_vhost -lrte_net -lrte_dmadev -lrte_cryptodev -lrte_hash -lrte_rcu -lspdk
ln -sf hello_blob-shared build/hello_blob
xym@xinjinbo02:~/test$ sudo ./build/hello_blob hello_blob.json 
./build/hello_blob: error while loading shared libraries: libspdk_env_dpdk.so.12.0: cannot open shared object file: No such file or directory
```
It can pass the compilation, but gets error runtime.
## Possible Solution

I have tried to configure `LD_LIBRARY_PATH` env variable, but it didn't work. 
I also doubt that the link libraried was damaged, so I re-compiled spdk project. It still didn't work.
Furthermore, I find that after I add `--with-shared` option at configure time, the applications inside spdk folder also couldn't run. The following message is that :
```bash
xym@nisk-OptiPlex-7050:~/spdk$ sudo ./build/examples/hello_blob 
./build/examples/hello_blob: error while loading shared libraries: libspdk_bdev_malloc.so.5.0: cannot open shared object file: No such file or directory
```
## Steps to Reproduce

1. OS: Ubuntu 20.04        SPDK version: 23.03 （latest）
2. Clone the code from repository.
3. Follow the step on [this page](https://spdk.io/doc/getting_started.html).
4. At the configure step, use `./configure --with-shared` command.
5. `make`
6. After successfully compile, create a empty folder, and copy the `examples/blob/hello_world/hello_blob.c` file to it.
7. Write the Makefile above.
8. Execute `make shared` command, then run the app using `./build/hello_blob` command.

**Comment by tomzawadzki** [comment]
Hi @ironmn have you had a chance to checkout some of the examples at https://github.com/spdk/spdk/blob/master/test/external_code/ ? There you can find samples of external 'application', 'library' and 'bdev_module'.

I didn't analyze your Makefile in depth yet. Judging by the Current Behaviour and Possible solution sections it seems you are on the right track with `LD_LIBRARY_PATH`. Almost all SPDK CI tests are compiled using `--with-shared` and the section below is used to point to the libraries https://github.com/spdk/spdk/blob/master/test/common/autotest_common.sh#L184.
```
# always test with SPDK shared objects.
export SPDK_LIB_DIR="$rootdir/build/lib"
export DPDK_LIB_DIR="${SPDK_RUN_EXTERNAL_DPDK:-$rootdir/dpdk/build}/lib"
export VFIO_LIB_DIR="$rootdir/build/libvfio-user/usr/local/lib"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SPDK_LIB_DIR:$DPDK_LIB_DIR:$VFIO_LIB_DIR
```

Please let me know if it helped in your case.

**Comment by ironmn** [comment]
> Hi @ironmn have you had a chance to checkout some of the examples at https://github.com/spdk/spdk/blob/master/test/external_code/ ? There you can find samples of external 'application', 'library' and 'bdev_module'.
> 
> I didn't analyze your Makefile in depth yet. Judging by the Current Behaviour and Possible solution sections it seems you are on the right track with `LD_LIBRARY_PATH`. Almost all SPDK CI tests are compiled using `--with-shared` and the section below is used to point to the libraries https://github.com/spdk/spdk/blob/master/test/common/autotest_common.sh#L184.
> 
> ```
> # always test with SPDK shared objects.
> export SPDK_LIB_DIR="$rootdir/build/lib"
> export DPDK_LIB_DIR="${SPDK_RUN_EXTERNAL_DPDK:-$rootdir/dpdk/build}/lib"
> export VFIO_LIB_DIR="$rootdir/build/libvfio-user/usr/local/lib"
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SPDK_LIB_DIR:$DPDK_LIB_DIR:$VFIO_LIB_DIR
> ```
> 
> Please let me know if it helped in your case.
Thank you very much for your reply, I carefully read your suggestion and changed my static libraries to shared libraries. At the same time, in order to prevent the problem caused by the variable LD_LIBRARY_PATH, I directly used the `make install` command to make the system wild SPDK library, and finally the problem was solved.
I really didn't expect to get a reply at first, until I saw this message today, and it really touched me. Anyway, thank you very much!

**Comment by tomzawadzki** [comment]
@ironmn Were all your questions answered and can this issue be closed ?

**Comment by ironmn** [comment]
> Contributor

Yes. I'll close it soon. Thanks a lot anyway.
