### ISSUE TITLE
In Common.sh, between none and "", doesn't work "" is none

### ISSUE THREAD

**Issue by JIN-096** [spdk/spdk#3075]
# Sighting report
When I start script/setup.sh, all of NVMe is already used. So NVMe driver can't unbind.
So, I trace the code, I found the something strange.
In common.sh, line 358. pt=$(blkid -s PTTYPE -o value "/dev/${block##*/}") || pt=none
when i use that command " blkid -s PTTYPE -o value "/dev/NVMe0" " That's result is nothing.
but pt=none is not execute.
nothing is not none?

## Expected Behavior
pt=[]
pt=none
return 1

## Current Behavior
pt=[]
pt=""
return 0;

## Possible Solution
pt=$(blkid -s PTTYPE -o value "/dev/${block##*/}") || pt=none
if [[ -z "$pt"]]
   pt = none
fi

of
if [[ -n "$pt"]]
   pt = none
fi

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
ubuntu 20.04, SPDK latest, Linux 5.15

**Comment by mikeBashStuff** [comment]
The logic here assumes that if there's any data present on the disk device, it should consist of a valid partition table. This of course won't be true in case someone, for instance, installed bare filesystem on the drive device. Also, `blkid` returns != 0 in case it cannot read ANY data from the device, however, it will return 0 in case it read something, regardless if it matches requested tag, `PTTYPE` in this case. 

So the actual solution here should be something along the lines of:
```
diff --git a/scripts/common.sh b/scripts/common.sh
index bbc74afcb..971f89340 100644
--- a/scripts/common.sh
+++ b/scripts/common.sh
@@ -357,7 +357,7 @@ block_in_use() {

        pt=$(blkid -s PTTYPE -o value "/dev/${block##*/}") || pt=none

-       if [[ $pt == none || $pt == atari ]]; then
+       if [[ -n $pt ]] && [[ $pt == none || $pt == atari ]]; then
                return 1
        fi
```
Alternatively, as per blkid(8):
> Note the option --match-tag filters output tags, but it does not  affect  exit status.

We could simplify it to something like this:
```
diff --git a/scripts/common.sh b/scripts/common.sh
index bbc74afcb..4ed8b097b 100644
--- a/scripts/common.sh
+++ b/scripts/common.sh
@@ -336,7 +336,7 @@ eq() { cmp_versions "$1" "==" "$2"; }
 neq() { ! eq "$1" "$2"; }

 block_in_use() {
-       local block=$1 data pt
+       local block=$1 pt
        # Skip devices that are in use - simple blkid it to see if
        # there's any metadata (pt, fs, etc.) present on the drive.
        # FIXME: Special case to ignore atari as a potential false
@@ -349,15 +349,9 @@ block_in_use() {
                return 1
        fi

-       data=$(blkid "/dev/${block##*/}") || data=none
-
-       if [[ $data == none ]]; then
+       if ! pt=$(blkid -s PTTYPE -o value "/dev/${block##*/}"); then
                return 1
-       fi
-
-       pt=$(blkid -s PTTYPE -o value "/dev/${block##*/}") || pt=none
-
-       if [[ $pt == none || $pt == atari ]]; then
+       elif [[ $pt == atari ]]; then
                return 1
        fi


```

**Comment by mikeBashStuff** [comment]
Here's the patch that simplifies the code. It should also make a bit easier to see what devices are considered to be in use: https://review.spdk.io/gerrit/c/spdk/spdk/+/19553 - note that device with ANY non-SPDK data is considered as such, not just the pt.

**Comment by mikeBashStuff** [comment]
Patch got merged, closing. The code was simplified to make sure the intention behind is clear (also, please see my previous comment).
