### ISSUE TITLE
Dynamic Threading Model

### ISSUE THREAD

**Issue by johnmeneghini** [spdk/spdk#308]
**SPDK needs to support a dynamic threading model where reactors are NOT bound to lcores.**

Many applications need SPDK to support a threading model that:
1. Does not assume a static number of threads
2. Does not bind threads to cores (this burns up cores)
3. Does not assume all treads use the same polling model

Removing these assumptions from the SPDK libraries will allow:
- Different applications to share the SPDK libraries on the same platform
  - E.g. FC-NVMe, RDMA-NVMe, and NVMe
- Different platforms to support the same applications with the same libraries
  - E.g. a 4 core platform and a 128 core plaform, a PowerPC  and NFS traffic
- Different workloads at different scales
  - E.g. 1 NVMF Host with 1 Subsystem and 1 Namespace, or 16 NVMF Hosts with 100 Subsystems and 1,000 namespaces.
- In particular, in SPDK, NVMF threads need to come and go depending upon the “NVMF load”.

**More Dynamic Use Cases Coming**

With the advent of FC-NVMe (which uses NPIV to visualize FC ports) NVMF Subsystem Ports and Host Ports are not static. Different Hosts and Subsystems can have a different number of Ports, and Ports can be dynamically added and removed from the configuration. This means: 
- The same platform may end up having different number of Subsystem ports at various points in its lifecycle
- The SPDK FC-NVMe application does NOT know up front how many ports it will have.

## Expected Behavior

1. SPDK libraries should not assume a static number of threads
2. SPDK libraries should bind threads to cores only optionally - supporting both static and dynamic threading models
3. SPDK libraries should support a Hybrid polling model (modified run to completion)

## Current Behavior

1. SPDK libraries assume a static number of threads
2. SPDK libraries bind threads to cores
3. SPDK libraries assume all treads use the same polling model

## Possible Solution

Proposal to solve above Use Cases: 

Use the `spdk_nvmf_poll_group` (PG) as the unit of threading abstraction
 
- Use PG as the fundamental unit on which a thread operates
- The spdk_thread will be a “virtual” thread that gets tied into a PG (1-1 relationship)
- Create PGs as and when hardware ports (and associated queue-pairs) come to life.
- No dependency between a PG and a “real” thread.
- A PG can be picked up by any “real” thread and worked upon. The PG contains everything needed for IO handling.
- PG continues to contain spdk_thread. spdk_thread continues same mechanisms for IO channels to different NS etc. etc.
- PG contains vendor data. Eg. A “ring” for depositing asynchronous callback events from the backend OR management events that come from external modules.
- spdk_thread contains thread_context that points to a PG instead of a reactor. So messages from the library get routed to the PG “ring” instead of a thread/reactor event ring.

Understanding the intent of the **event library**, it is believed this is the place for customization. However, the current event library assumes a threading model that's a part of the **util library**. Moreover, many of the other SPDK core libraries assume the same threading model as the **util library**.  If the SPDK **util library** can be modified to support these use dynamic threading use cases, all applications would be able to use the SPDK framework more effectively.

## Steps to Reproduce

This is an enhancement.  There is no bug.

## Context (Environment including OS version, SPDK version, etc.)

Would like to provide these enhancements in V18.07.

**Comment by paimad** [comment]
One clarification:
The diff that I have ready actually assumes the reactor as the unit of the threading abstraction (and NOT
the poll group). 
The patch comments has the actual details on the design which is a bit different from my earlier design approach (that is listed above).

**Comment by johnmeneghini** [comment]
Please see the RFC patches at:

https://review.gerrithub.io/#/c/spdk/spdk/+/412277/
https://review.gerrithub.io/#/c/spdk/spdk/+/412093/

**Comment by johnmeneghini** [comment]
Please review that patch at:

https://review.gerrithub.io/#/c/spdk/spdk/+/414293/

This patch is proposed to address this issue.

**Comment by jimharris** [comment]
This enhancement is being tracked in Trello:

https://trello.com/c/adbkfLja/2-dynamic-threading-model

Closing this issue - let's use the Trello card for further discussion on this enhancement.
