### ISSUE TITLE
[nvme] Memory leak in nvme_pcie_qpair_destroy

### ISSUE THREAD

**Issue by plestk** [spdk/spdk#3080]
Hello, I am running SPDK 22.09. I notice that the `stat` buffer allocated in `nvme_pcie_ctrlr_construct_admin_qpair` is not freed. I assume it should be freed in `nvme_pcie_qpair_destroy` but the condition `!pqpair->shared_stats && (qpair->active_proc == nvme_ctrlr_get_current_process(qpair->ctrlr))` is false.

- `pqpair->shared_stats` -> 0
- `qpair->active_proc` -> NULL
- `nvme_ctrlr_get_current_process(qpair->ctrlr)` -> not NULL

**Comment by AlekseyMarchuk** [comment]
Fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/19348

**Comment by changpe1** [comment]
patch has been merged, closing it now.
