### ISSUE TITLE
NVMe e2edp test return RC=0 even though there was an ERROR 

### ISSUE THREAD

**Issue by jsawickx** [spdk/spdk#3081]
# Sighting report

After running the NVMe test: https://github.com/spdk/spdk/blob/master/test/nvme/e2edp/nvme_dp.c I got the following output:
```
Finished executing '"sudo /opt/spdk/test/nvme/e2edp/nvme_dp -r 'trtype:PCIe traddr:83:00.1'"', rc=0, output:
stdout>>
NVMe Write/Read with End-to-End data protection test
Attaching to 0000:83:00.1
Cleaning up...

stderr>>
EAL: No free 1048576 kB hugepages reported on node 0
EAL: No free 1048576 kB hugepages reported on node 1
TELEMETRY: No legacy callbacks, legacy socket not created
[2023-07-21 19:51:56.229720] nvme_ctrlr.c:4041:nvme_ctrlr_process_init: *ERROR*: [0000:83:00.1] Initialization timed out in state 19 (wait for CSTS.RDY = 1 reg)
[2023-07-21 19:51:56.229747] nvme.c: 702:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:83:00.1
[2023-07-21 19:51:56.229752] nvme_ctrlr.c:1024:nvme_ctrlr_fail: *ERROR*: [0000:83:00.1] in failed state.
```
... despite the fact that there is information that controller failed to initialize, the test returns RC=0.

## Expected Behavior

After getting output that controller failed to initialize, test app should return RC different than 0.

## Current Behavior

After getting output that controller failed to initialize, test app should return RC=0.

## Steps to Reproduce

Look at the code of this test or perform failing test.

## Context (Environment including OS version, SPDK version, etc.)

Tests are available on the latest master branch.

**Comment by ksztyber** [comment]
The problem here is that this app doesn't parse *any* options. So, even if you do specify BDF, it's just ignored. I've pushed a patch to change that [1]. That should also return non-zero exit status when the controller fails to initialize.

[1] https://review.spdk.io/gerrit/c/spdk/spdk/+/19164
