### ISSUE TITLE
(Request help) When creating a blob snapshot, the original blob cannot be written to.

### ISSUE THREAD

**Issue by yangjunsen** [spdk/spdk#3082]
# Request help
In version 22.05, I am utilizing ‘spdk_bs_create_snapshot()’ of the snapshot function generates a snapshot of the original blob，and use the function ‘spdk_blob_io_write’ cannot write to the original blob, resulting in an error code of -28.  But performing ‘spdk_blob_io_read’ can be read  on the original blob。May I ask if spdk has imposed write restrictions after taking a snapshot of the original blob.  So how should we modify the original blob content while maintaining a snapshot. 

## code structure
//creat a snapshot
void object_store::snap_create(std::string object_name, object_rw_complete cb_fn, void* arg)
{
    ..................
    struct snap_create_ctx* ctx = new snap_create_ctx();
    spdk_blob_opts_init(&opts, sizeof(opts));
    ctx->bs = bs;
    ctx->snap_blob=new object_store:: fb_blob ();
    ctx->cb_fn =cb_fn;
    ctx->arg=arg;
    spdk_bs_create_snapshot(bs, it->second->blobid,&(opts.xattrs),snap_done, ctx);
  }else {
    SPDK_ERRLOG("the fb_blob name is not exist :%s\n",object_name.c_str());
}

//snap_done：snap_doneof function contains a callback re_write function and its parameters.
void re_write(void *arg1,int objerrno) {
        if (objerrno) 
      {
         return ;
        }
	struct hello_context_t *hello_context = (hello_context_t *)arg1;
	hello_context->cb_fn=load_snap;
	blob_write(hello_context,0x31,load_snap);
}

The original blob can complete reading and writing before creating the snapshot. However, after a snapshot is created and a callback is made, a -26 error will occur when reading the original data block.May I ask what the problem is and what methods are available to write to the original blob.

**Comment by tomzawadzki** [comment]
Hi @yangjunsen, please note that after `spdk_bs_create_snapshot()` the blobid passed to it should still be writable. Meanwhile the new blobid that is presented in cb_fn, is read-only and referred to as the snapshot. This is intentional, so that I/O can continue to use the original blobid, meanwhile blobid of the snapshot can be used for in calls like `spdk_bs_create_clone()`.

Please see the description of the `spdk_bs_create_snapshot`:
```
 * Create a read-only snapshot of specified blob with provided options.
 * This will automatically sync specified blob.
 *
 * When operation is done, original blob is converted to the thin-provisioned
 * blob with a newly created read-only snapshot set as a backing blob.
 ```

After reading the code snippet, I'm not sure if the two blobids were not confused. Can you please clarify ?

**Comment by yangjunsen** [comment]
Thank you very much for your answer，and I'm sorry for my messy code. What you said was very clear, which made me understand a lot. The problem I encountered was that there was an error writing to the original snapshot after creating it. But in reality, the original snapshot can be written to. Due to my first exposure to spdk, I mainly wrote based on examples. In the helloword file, after creating the blob_store, resize the blob to directly occupy all clusters. When writing to the original blob again, due to the COW effect, additional blob space is required, and at this point, there is no more space in the cluster, resulting in a write error. Thank you again for your answer.

**Comment by jimharris** [comment]
Thanks @yangjunsen for reaching out for help, and @tomzawadzki for the clear response.

Closing this issue.
