### ISSUE TITLE
Using the igb_uio driver is disabled?

### ISSUE THREAD

**Issue by Liu-rj** [spdk/spdk#3085]
In current master, there is no options for `--with-igb-uio-driver`, and also I don't find the `igb_uio.ko` in DPDK folder after build. Do I miss something here? How can I use igb_uio driver if IOMMU is disabled and there is no uio_pci_generic driver considering I'm using an AWS EC2 g4dn instance?

Any guidance is very appreciated.

**Comment by mikeBashStuff** [comment]
This driver is not handled as part of the main DPDK repo anymore. Please see https://doc.dpdk.org/dts/gsg/usr_guide/igb_uio.html.

We do include it in our `pkgdep` infra here: https://github.com/spdk/spdk/blob/7adbcfb20cd19b8e00dfd7d19578976ef5290910/test/common/config/pkgdep/git#L257

but it's not hooked into the SPDK build, meaning, it's up to the user to provision its system with it if needed. The simple usage would be:

```
# . ./test/common/config/pkgdep/git; install_igb_uio
Cloning into '/root/dpdk-kmods'...
remote: Enumerating objects: 537, done.
remote: Counting objects: 100% (537/537), done.
remote: Compressing objects: 100% (345/345), done.
remote: Total 537 (delta 167), reused 372 (delta 85)
Receiving objects: 100% (537/537), 121.04 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (167/167), done.
make -C /lib/modules/6.4.4-100.fc37.x86_64/build/ M=/root/dpdk-kmods/linux/igb_uio
make[1]: Entering directory '/usr/src/kernels/6.4.4-100.fc37.x86_64'
  CC [M]  /root/dpdk-kmods/linux/igb_uio/igb_uio.o
  MODPOST /root/dpdk-kmods/linux/igb_uio/Module.symvers
  CC [M]  /root/dpdk-kmods/linux/igb_uio/igb_uio.mod.o
  LD [M]  /root/dpdk-kmods/linux/igb_uio/igb_uio.ko
  BTF [M] /root/dpdk-kmods/linux/igb_uio/igb_uio.ko
Skipping BTF generation for /root/dpdk-kmods/linux/igb_uio/igb_uio.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/kernels/6.4.4-100.fc37.x86_64'
[root@test-hostname spdk]# modinfo igb_uio
filename:       /lib/modules/6.4.4-100.fc37.x86_64/extra/dpdk/igb_uio.ko
author:         Intel Corporation
license:        GPL
description:    UIO driver for Intel IGB PCI cards
rhelversion:    9.99
depends:        uio
retpoline:      Y
name:           igb_uio
vermagic:       6.4.4-100.fc37.x86_64 SMP preempt mod_unload
parm:           intr_mode:igb_uio interrupt mode (default=msix):
    msix       Use MSIX interrupt
    msi        Use MSI interrupt
    legacy     Use Legacy interrupt

 (charp)
parm:           wc_activate:Activate support for write combining (WC) (default=0)
    0 - disable
    other - enable
 (int)
#
```

this will build the driver against your currently booted kernel's sources (if available).

**Comment by mikeBashStuff** [comment]
In general, I believe `vfio-pci` is recommended whenever available (including the unsafe mode). https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html describes quite nicely differences between the uio|vfio drivers.

**Comment by Liu-rj** [comment]
Good to know this! Thanks again for your help. I may close this issue.
