### ISSUE TITLE
thread.c:3036:spdk_spin_lock: *ERROR*: unrecoverable spinlock 

### ISSUE THREAD

**Issue by ironmn** [spdk/spdk#3086]
# Sighting report

When I use the SPDK event library to create a Blobstore bdev object with multiple threads, it reports the error message below: 
```bash
[2023-08-01 19:17:23.736681] thread.c:3036:spdk_spin_lock: *ERROR*: unrecoverable spinlock error 1: Not an SPDK is displayed thread (thread != ((void *)0)) .
```

## Expected Behavior

To execute the `spdk_bdev_create_bs_dev_ext` function concurrently.

## Current Behavior

Whatever functions related to Blobstore, it seems that they can't be called in SPDK Reactor. If do so, the program will be aborted immediately and show the error message below:
```bash
[2023-08-01 19:17:23.736606] src/callbacks/blob_app.c: 209:spdk_capture_multi_bdev_poll_cb: *NOTICE*: entering lcore3's spdk_capture_multi_bdev_poll_cb
free(): invalid pointer
[2023-08-01 19:17:23.736651] src/callbacks/blob_app.c: 209:spdk_capture_multi_bdev_poll_cb: *NOTICE*: entering lcore4's spdk_capture_multi_bdev_poll_cb
[2023-08-01 19:17:23.736676] thread.c:3036:spdk_spin_lock: *ERROR*: unrecoverable spinlock error 1: Not an SPDK thread (thread != ((void *)0))
[2023-08-01 19:17:23.736681] thread.c:3036:spdk_spin_lock: *ERROR*: unrecoverable spinlock error 1: Not an SPDK thread (thread != ((void *)0))
Aborted

```

## Possible Solution

Maybe I should use the SPDK thread library. But I want to make my program simple, so is there any way that I can keep using SPDK event library to execute `spdk_bdev_create_bs_dev_ext` function?

## Steps to Reproduce

The function I use to call  `spdk_bdev_create_bs_dev_ext`
```C
void 
spdk_capture_multi_bdev_poll_cb(void *arg1, void *arg2)
{
    struct capture_resources *rsrc = arg1;
    uint16_t lcore_id = rte_lcore_id();
    struct blob_conf_t *blob_conf = get_blob_conf_by_lcore_id(rsrc, lcore_id);
    struct spdk_bs_dev *bs_dev = NULL;
    SPDK_NOTICELOG("The pointer of blob_conf is %p\n", blob_conf);
    SPDK_NOTICELOG("entering lcore%u's spdk_capture_multi_bdev_poll_cb\n", lcore_id);
    
    blob_conf->rc = spdk_bdev_create_bs_dev_ext("aaa", base_bdev_event_cb, NULL, &bs_dev);
    if(blob_conf->rc != 0) {
        SPDK_ERRLOG("Could not create blob bdev, %s!!\n",
                spdk_strerror(-blob_conf->rc));
        //不停止spdk_app，除非最后所有的blobstore都出现了问题
        return;
    }
    spdk_bs_init(bs_dev, NULL, spdk_capture_bs_init_complete_cb, blob_conf);
}
```

## Context (Environment including OS version, SPDK version, etc.)

OS：Ubuntu 20.04
SPDK version : 23.11

**Comment by shuhei-matsumoto** [comment]
Hi @ironmn  How about the following? We may be able to enable SPIN_ASSERT_IMPL only if we compile with debug mode. @mgerdts Do you have any idea?

```
diff --git a/lib/thread/thread.c b/lib/thread/thread.c
index 5ea4546b15..d5738159d3 100644
--- a/lib/thread/thread.c
+++ b/lib/thread/thread.c
@@ -222,6 +222,7 @@ __posix_abort(enum spin_error err)
 typedef void (*spin_abort)(enum spin_error err);
 spin_abort g_spin_abort_fn = __posix_abort;

+#ifdef DEBUG
 #define SPIN_ASSERT_IMPL(cond, err, extra_log, ret) \
        do { \
                if (spdk_unlikely(!(cond))) { \
@@ -232,6 +233,10 @@ spin_abort g_spin_abort_fn = __posix_abort;
                        ret; \
                } \
        } while (0)
+#else
+#define SPIN_ASSERT_IMPL(cond, err, extra_log, ret) do { } while (0)
+#endif
+
```

**Comment by shuhei-matsumoto** [comment]
Thank you so much @mgerdts. Your opinion is very reasonable.

@ironmn Sorry, I missed that you used the SPDK event library without the SPDK thread library.

We have sample applications to use the SPDK thread library without the SPDK event library.
- spdk/examples/nvmf/nvmf/nvmf.c
- https://review.spdk.io/gerrit/c/spdk/spdk/+/14846 by @KKaras169169 
I hope these provide good insight to you about how to use SPDK thread library.

Even more, you may be able to use only the SPDK thread library. This will be easier than using only the SPDK event library.
