### ISSUE TITLE
iscsi target create problem

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#309]
app/iscsi_tgt/iscsi_tgt do not create target from simple config

## Expected Behavior

target should be created
## Current Behavior

iscsi_tgt  *ERROR* on iscsiadm discover
## Possible Solution

?
## Steps to Reproduce

1. Create simple config etc/spdk/test_iscsi.conf.in

[Global]

[iSCSI]
  NodeBase "iqn.2016-06.io.spdk"
  AuthFile /usr/local/etc/spdk/auth.conf
  MinConnectionsPerCore 4
  Timeout 30
  DiscoveryAuthMethod Auto
  DefaultTime2Wait 2
  DefaultTime2Retain 60
  ImmediateData Yes
  ErrorRecoveryLevel 0

[PortalGroup1]
  Portal DA1 172.16.21.75:3260

[InitiatorGroup1]
  InitiatorName ANY
  Netmask 172.16.21.0/24

[AIO]
  AIO /dev/sdd AIO0

[TargetNode1]
  TargetName disk1
  TargetAlias "Data Disk1"
  Mapping PortalGroup1 InitiatorGroup1
  AuthMethod Auto
  AuthGroup AuthGroup1
  UseDigest Auto
  LUN0 AIO0
  QueueDepth 128

2. run iscsi_tgt
`app/iscsi_tgt/iscsi_tgt -c etc/spdk/test_iscsi.conf.in`
In log :
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: iscsi -c 0x1 --file-prefix=spdk_pid4122 ]
EAL: Detected 32 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid4122_unix
EAL: Probing VFIO support...
app.c: 521:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 669:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 453:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0

//note that there is nothing about iscsi tgt in this log, I am not sure that it is started correctly

3. discover tgt
`iscsiadm -m discovery -t sendtargets -p 172.16.21.75:3260`

In Log:
conn.c: 324:spdk_iscsi_conn_construct: *NOTICE*: Launching connection on acceptor thread
iscsi.c:2090:spdk_iscsi_op_login_notify_session_info: *NOTICE*: Login(discovery) from iqn.1994-05.com.redhat:fa882b6d4958 (172.16.21.75) on (172.16.21.75:3260,1), ISID=23d000000, TSIH=1, CID=0, HeaderDigest=off, DataDigest=off
conn.c: 741:spdk_iscsi_conn_read_data: *ERROR*: spdk_sock_recv() failed, errno 104: Connection reset by peer
conn.c: 456:spdk_iscsi_remove_conn: *NOTICE*: Terminating connections(tsih 1): 0

When I tried ./autotest.sh it were the same errors on iscsi tests.

## Context (Environment including OS version, SPDK version, etc.)

Centos 7.4
Linux Kernel 4.11.6
SPDK commit 3949140b2eea26f52a159e05e61ebd951ca5c0d2

**Comment by jimharris** [comment]
Can you check if selinux is enabled?  And if so, disable it?  I know we’ve seen this issue before where security modules interfere with iSCSI connections.

This is most certainly some kind of configuration issue – iSCSI configuration is known to work well.

Could you try the same discover command, but without creating any target nodes?  Discovery should normally succeed in that case – it will just show no target nodes available.  I suspect you’ll see the same failure but just want to confirm.

Thanks,

-Jim

**Comment by WenqianZong** [comment]
I use alekseymmm's iscsi .conf file to reproduce issue ,and I checked discovery iscsi target logs under disable /enable selinux.
iscsi target machine report same error:
```
conn.c: 324:spdk_iscsi_conn_construct: *NOTICE*: Launching connection on acceptor thread
iscsi.c:2090:spdk_iscsi_op_login_notify_session_info: *NOTICE*: Login(discovery) from iqn.1994-05.com.redhat:81a9a3a1a2 (192.168.11.12) on (192.168.11.11:3260,1), ISID=23d000000, TSIH=1, CID=0, HeaderDigest=off, DataDigest=off
conn.c: 741:spdk_iscsi_conn_read_data: *ERROR*: spdk_sock_recv() failed, errno 104: Connection reset by peer
conn.c: 456:spdk_iscsi_remove_conn: *NOTICE*: Terminating connections(tsih 1): 0
```
then I use command `iscsiadm -m node -T iqn.2016-06.io.spdk:disk1 -p 192.168.3.11 --login` to login iscsi target and run perf . No error occurred.

**Comment by jimharris** [comment]
Thanks Wenqian.  This is a great data point.

My guess here is that with the v18.04 iSCSI poll group changes, that we have a situation where we return the SendTargets data to the initiator, the initiator closes the connection, and we poll one last time resulting in this error message.  We shouldn’t be printing an error message in this case though.

Ziye – could you take a look at this?

**Comment by alekseymmm** [comment]
I have checked selinux and it is disabled. But it seems there are some configuration problems since iscsi kernel target also doesn't work properly. 
I believe you could close this issue as irrelevant.

**Comment by alekseymmm** [comment]
Hi @jimharris 
I have tried ignoring the ERROR message as @WenqianZong  suggested but  it still failed to connect targets
# iscsiadm -m discovery -t sendtargets -p 10.30.0.11:3261
10.30.0.11:3261,1 iqn.2016-06.io.spdk:disk1
# iscsiadm --mode node --targetname iqn.2016-06.io.spdk:Target1 --portal 10.30.0.11:3261 --login
iscsiadm: No records found

**Comment by alekseymmm** [comment]
I am curious whether you are going to fix this ERROR message on discover ?

**Comment by jimharris** [comment]
Yes – we plan to fix this error message.

I’m not sure why this issue was closed though?  Not only does the error message need to be fixed, but your last reply indicated that even after the error message during recovery, you were unable to log into the configured target node.

**Comment by optimistyzy** [comment]
@jimharris  I did not find any issue with the code yet. For the normal discovery,  it should goto spdk_iscsi_conn_read_data (line: 747), Which means that no data can be read, and the socket should be closed. Do not know why get -104 error.
