### ISSUE TITLE
[nvmftestinit] Destination Host Unreachable

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#3098]
# CI Intermittent Failure

It seems that when starting very first NVMe-oF test using `nvmftestinit` ping outside the namespace fails when pinging IP from inside the namespace.
This looks to be related to https://github.com/spdk/spdk/issues/2404 and https://github.com/spdk/spdk/issues/2916. This means that might be an issue with WFP19 specifically.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/107755/archive/crypto-phy-autotest_2230/build.log

## Execution failed at

```
00:14:11.649   11:16:28	-- nvmf/common.sh@259 -- # ping -c 1 10.0.0.2
00:14:14.935  PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
00:14:14.935  From 10.0.0.1 icmp_seq=1 Destination Host Unreachable
00:14:14.935  
00:14:14.935  --- 10.0.0.2 ping statistics ---
00:14:14.935  1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_107755.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_107760.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_107763.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_107767.html

**Comment by KKaras169169** [comment]
> Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_107767.html

Encountered during `crypto-phy-autotest` -> `chaining`.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107779.html

**Comment by mikeBashStuff** [comment]
I just wonder why we try to run nvmf-oriented test under crypto job, requesting actual hw. It feels like veth would suffice (unless we care about testing both transports, tcp and rdma).

**Comment by tomzawadzki** [comment]
[Bug scrub] The `chaining` test uses both crypto and NVMe-oF, so `crypto-phy-autotest` still is good choice. Forcing using VETH interfaces for this test might be a solution for this particular test, either in job or within test script. @mikeBashStuff and @ksztyber will discuss offline and arrive at best soultion.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107794.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107785.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107773.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107802.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_107807.html

**Comment by mikeBashStuff** [comment]
The affected node, WFP19, was already taken care of by @karlatec so this issue can be closed - all jobs that have been scheduled on WFP19 completed successfully since then.
