### ISSUE TITLE
Wrongly documented parameter name for bdev_nvme_set_hotplug rpc

### ISSUE THREAD

**Issue by Alvinlst** [spdk/spdk#3105]
# Sighting report
The parameter name for bdev_nvme_set_hotplug rpc at https://spdk.io/doc/jsonrpc.html is wrong.

## Expected Behavior
To make the json rpc work as expected, the first parameter should be `enable` instead of `enabled`, based on https://github.com/spdk/spdk/blob/master/module/bdev/nvme/bdev_nvme_rpc.c#L113

## Current Behavior
When calling this json rpc with variable name `enabled`, it doesn't work and gives "Invalid Argument" error.

## Possible Solution
Using either `enable` or `enabled` is fine, but it should be consistent across all places, including the C code, python code and documentation.

## Steps to Reproduce
Write a simple program (any language) with json marshal/unmarshal and interact with this RPC. Provide `enabled` as the first parameter, and you should be able to see the error.

## Context (Environment including OS version, SPDK version, etc.)
I'm using SPDK v23.01.1, but the latest repo has the same issue I believe.

**Comment by changpe1** [comment]
yes, it's should be `enable` in the rpc document, https://review.spdk.io/gerrit/c/spdk/spdk/+/19468

**Comment by Alvinlst** [comment]
> yes, it's should be `enable` in the rpc document, https://review.spdk.io/gerrit/c/spdk/spdk/+/19468

Thank you! Not sure if you want to change the struct field name as well: https://github.com/spdk/spdk/blob/master/module/bdev/nvme/bdev_nvme_rpc.c#L108 But I guess it won't affect the functionality.

**Comment by changpe1** [comment]
> > yes, it's should be `enable` in the rpc document, https://review.spdk.io/gerrit/c/spdk/spdk/+/19468
> 
> Thank you! Not sure if you want to change the struct field name as well: https://github.com/spdk/spdk/blob/master/module/bdev/nvme/bdev_nvme_rpc.c#L108 But I guess it won't affect the functionality.

Yes, it's internal variable. patch has been merged, closing it now.
