### ISSUE TITLE
nvme: spdk_nvme_probe_poll_async should report errors to callers

### ISSUE THREAD

**Issue by nickyc975** [spdk/spdk#3106]
# Sighting report

We found in our development that spdk_nvme_probe_poll_async does not report errors when attach failed. It turns out that commit [ddf86600bb16...b861369f50e8 "nvme: continue probing ctrlrs even if one fails"](https://github.com/spdk/spdk/commit/ddf86600bb1675d4fc501e70ea51b861369f50e8) changed its behavior. It is counterintuitive that a function returns 0 even on failure. It also results in that users have to do ugly hacks to detect attach failures.

## Expected Behavior

spdk_nvme_probe_poll_async should not return 0 when there are failures.

## Current Behavior

spdk_nvme_probe_poll_async returns 0 even if there are failures.

## Possible Solution

Considering that there might be multiple controllers to attach in one probe, returning the number of attach failures could be a good choice. In this way, 0 will still mean success, and negative numbers could be reserved for error codes.

If you agree with the solution, I can submit a patch.

## Context (Environment including OS version, SPDK version, etc.)

Since SPDK v21.01.

**Comment by changpe1** [comment]
Considering this commit already provided possible solution for this issue, I would suggest following the API definition to detect this error.

**Comment by nickyc975** [comment]
In my opinion, the API definition before the commit which reports errors explicitly is more user friendly and more intuitive. It's worth modifying the implementation of spdk_nvme_probe_poll_async slightly, as this will save users time and avoid misunderstandings.

**Comment by tomzawadzki** [comment]
[Bug scrub] @nickyc975 After short discussion on Bug Scrub the proposed approach seems reasonable. Could you submit a patch with suggested changes ?

**Comment by nickyc975** [comment]
> [Bug scrub] @nickyc975 After short discussion on Bug Scrub the proposed approach seems reasonable. Could you submit a patch with suggested changes ?

Sorry for the delayed response. I'm glad to submit a patch!

**Comment by nickyc975** [comment]
Hello, I have submitted a patch on Gerrit: [19872](https://review.spdk.io/gerrit/c/spdk/spdk/+/19872), looking forward to your responses.
