### ISSUE TITLE
Read and write errors when the blob size of the parent id of the blob is smaller than the blob

### ISSUE THREAD

**Issue by yanjiawei2** [spdk/spdk#3108]
# Sighting report

Use lvstore to create lv, expand the capacity after taking a snapshot, read and write in the expansion io_unit returns an error

## Expected Behavior

A valid underlying device should be read, such as the zero device. copy-on-write should also read valid device

## Current Behavior

The current reading of the underlying device or copy-on-write will return failure at the judgment condition of blob_request_submit_rw_iov, resulting in the fact that the behavior of lvol expansion is actually meaningless

if (offset + length > bs_cluster_to_lba(blob->bs, blob->active.num_clusters)) {
  cb_fn(cb_arg, -EINVAL);
  return;
}

## Possible Solution

When executing bs_sequence_readv_bs_dev, determine whether the underlying device has sufficient length

## Steps to Reproduce

1. create_lvol 1GB
2. make a lvol_snapshot
3. resize_lvol to 2GB
4. read or write(eg. by iscsi_target) on offset[1GB~2GB]
it will return -EINVAL

**Comment by dsharma-dc** [comment]
Is this issue on roadmap to be fixed? We've also been running into it while performing an lvol expansion after taking a snapshot. If the lba falls out of bounds of the clusters in parent i.e. snapshot, the assert is getting hit from inside `bs_io_unit_is_allocated`
```
assert(page < blob->active.num_clusters * pages_per_cluster);
```

**Comment by jimharris** [comment]
> Is this issue on roadmap to be fixed? We've also been running into it while performing an lvol expansion after taking a snapshot. If the lba falls out of bounds of the clusters in parent i.e. snapshot, the assert is getting hit from inside `bs_io_unit_is_allocated`
> 
> ```
> assert(page < blob->active.num_clusters * pages_per_cluster);
> ```
> 
> This happened in the path when `is_zeroes()` calls bs_io_unit_is_allocated on the snapshot blob.

I started some work on this a long time back, if someone wants to pick it up: https://review.spdk.io/gerrit/c/spdk/spdk/+/11597

**Comment by dsharma-dc** [comment]
@jimharris I've done some smoke testing using the patch you provided. Also added the same to readv_ext path. Added some additional changes in write path. Seems to work.
Was there any particular reason(any more work required / incomplete ?) that this patch has been pending in gerrit?

**Comment by jimharris** [comment]
> @jimharris I've done some smoke testing using the patch you provided. Also added the same to readv_ext path. Added some additional changes in write path. Seems to work. Was there any particular reason(any more work required / incomplete ?) that this patch has been pending in gerrit?

It has been pending in Gerrit because the work was incomplete and needs someone to continue the work.

I've rebased it just now, coded the readv_ext path, and made a helper function so all three functions (read, readv, readv_ext) can all share the same path. But it still needs work on the write path.  We need the unit test to pass - it hits multiple asserts on the write path when allocating a cluster past the end of the backing blob.

I won't have time to do any additional work on this for a while. If you'd like to move it forward feel free to start with my path and apply the necessary changes to the write path. I'd be happy to review and help get it merged.

**Comment by dsharma-dc** [comment]
> I won't have time to do any additional work on this for a while. If you'd like to move it forward feel free to start with my path and apply the necessary changes to the write path. I'd be happy to review and help get it merged.

Thank you @jimharris . Kindly take a look here https://review.spdk.io/gerrit/c/spdk/spdk/+/22377

**Comment by jimharris** [comment]
> > I won't have time to do any additional work on this for a while. If you'd like to move it forward feel free to start with my path and apply the necessary changes to the write path. I'd be happy to review and help get it merged.
> 
> Thank you @jimharris . Kindly take a look here https://review.spdk.io/gerrit/c/spdk/spdk/+/22377

Thanks @dsharma-dc! I left some comments on the Gerrit review.

**Comment by dsharma-dc** [comment]
@tomzawadzki Could you please kick this patch forward to CI once again?

**Comment by dsharma-dc** [comment]
@mchomnic The CI had failed because of issue 3307. I've rebased now to master.

**Comment by dsharma-dc** [comment]
Hi @jimharris , Latest patchset updated, kindly take a look.

**Comment by dsharma-dc** [comment]
Hi @jimharris , for your perusal again please (patchset 6).

**Comment by dsharma-dc** [comment]
@mchomnic I'm guessing we need two +2 votes. Jim has done one, and Gerrit shows another +2 can be given by SPDK CI Jenkins. How is that triggered?

**Comment by jimharris** [comment]
> @mchomnic I'm guessing we need two +2 votes. Jim has done one, and Gerrit shows another +2 can be given by SPDK CI Jenkins. How is that triggered?

Jenkins only votes +1. You need another +2 from a core maintainer. Now that it has one +2, you'll likely get another one in next few days - or a request for other changes to your patch.

**Comment by dsharma-dc** [comment]
The patch has been merged, perhaps this issue can be closed now.
A follow patch is also under review : https://review.spdk.io/gerrit/c/spdk/spdk/+/23020 - @jimharris
