### ISSUE TITLE
[vmd] *ERROR*: Cannot unmap DMA memory, error 22 in vmd test

### ISSUE THREAD

**Issue by mchomnic** [spdk/spdk#3117]
# Sighting report

VMD test fails with error:  memory.c:1461:vtophys_pci_device_removed: *ERROR*: Cannot unmap DMA memory, error 22

## Expected Behavior

no errors.

## Possible Solution

no suggestion.

## Steps to Reproduce

1. Enable VMD controller in BIOS setup
2. build: ./configure --enable-debug
3. build: make -j
4. run test: sudo ./test/vmd/vmd.sh

## Context (Environment including OS version, SPDK version, etc.)
fedora 37
spdk: 
   - master 0bc4c731ad 
   - release v23.01
   - release v23.05

[error_log.txt](https://github.com/spdk/spdk/files/12512735/error_log.txt)

**Comment by ksztyber** [comment]
This patch should fix the issue: http://review.spdk.io/gerrit/c/spdk/spdk/+/20187. @mchomnic, could you verify that it works on your end?

**Comment by mchomnic** [comment]
@ksztyber , I checked you patch and it works.
