### ISSUE TITLE
Duplicate I/OS were received when transferring data through nvmf over TCP

### ISSUE THREAD

**Issue by wyy007** [spdk/spdk#3120]
# Sighting report
  I use spdk_bdev_register interface to register a custom type bdev at Controller side and set a submit_request in spdk_bdev_fn_table to receive a data from Host side. The data channel is built on nvmf over tcp. The Host uses the spdk_nvme_ns_cmd_write/spdk_nvme_ns_cmd_read interface to send data to Controller.
  I found that when the network was poor, the Host send one io, but the Controller might receive two duplicate data from spdk_bdev_io. May I ask if this situation is normal.

## Expected Behavior

The io sent by Host corresponds to the io received by Controller.

## Current Behavior

One Host's io may correspond to two Controller's io.

## Steps to Reproduce
Controller side:
1.spdk_nvmf_subsystem_create and spdk_nvmf_subsystem_start
2.spdk_nvmf_tgt_listen and spdk_nvmf_subsystem_add_listener
3.spdk_bdev_register
4.spdk_nvmf_subsystem_add_ns 

Host side:
1.spdk_nvme_poll_group_create
2.spdk_nvme_probe
3.spdk_nvme_ctrlr_alloc_io_qpair
4.spdk_nvme_poll_group_add
5.spdk_nvme_ctrlr_reconnect_io_qpair
6.spdk_nvme_ns_cmd_write/spdk_nvme_ns_cmd_read

## Context (Environment including OS version, SPDK version, etc.)

SPDK: 20.07
OS: centos 7
kernel: 5.10.0

**Comment by changpe1** [comment]
@wyy007 this is abnormal, but I would suggest you reproduce this issue based on new SPDK release version (drop your own code), from your description we can't give useful help on it.
