### ISSUE TITLE
[short-fuzz-autotest] vfio_fuzz failed due to deadly signal

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3121]
# Sighting report

In CI job `short-fuzz-autotest` test `vfio_fuzz` fails when testing with ASAN enabled with DEADLYSIGNAL.
https://ci.spdk.io/public_build/autotest-per-patch_109100.html
https://ci.spdk.io/results/autotest-per-patch/builds/109100/archive/short-fuzz-phy-autotest_4550/build.log

## Current Behavior

```
00:07:25.874   10:48:29	-- vfio/run.sh@38 -- # /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz -m 0x1 -s 2048 -P /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/../output/llvm/ -F /tmp/vfio-user-0/domain/1 -c /tmp/vfio-user-0/fuzz_vfio_json.conf -t 1 -D /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/../corpus/llvm_vfio_0 -Y /tmp/vfio-user-0/domain/2 -r /tmp/vfio-user-0/spdk0.sock -Z 0
00:07:25.874  [2023-09-07 10:48:29.882773] Starting SPDK v23.09-pre git sha1 b38c939e6 / DPDK 23.03.0 initialization...
00:07:25.874  [2023-09-07 10:48:29.882865] [ DPDK EAL parameters: vfio_fuzz --no-shconf -c 0x1 -m 2048 --huge-unlink --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid328174 ]
00:07:25.874  EAL: No free 2048 kB hugepages reported on node 1
00:07:26.814  TELEMETRY: No legacy callbacks, legacy socket not created
00:07:26.814  [2023-09-07 10:48:30.942942] app.c: 767:spdk_app_start: *NOTICE*: Total cores available: 1
00:07:26.814  [2023-09-07 10:48:31.032241] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
00:07:27.073  [2023-09-07 10:48:31.080151] 'OCF_Core' volume operations registered
00:07:27.073  [2023-09-07 10:48:31.082735] 'OCF_Cache' volume operations registered
00:07:27.073  [2023-09-07 10:48:31.085296] 'OCF Composite' volume operations registered
00:07:27.073  [2023-09-07 10:48:31.087854] 'SPDK_block_device' volume operations registered
00:07:27.073  INFO: Running with entropic power schedule (0xFF, 100).
00:07:27.073  INFO: Seed: 2139924245
00:07:27.073  INFO: Loaded 1 modules   (411307 inline 8-bit counters): 411307 [0x43ee08c, 0x4452737), 
00:07:27.073  INFO: Loaded 1 PC tables (411307 PCs): 411307 [0x4452738,0x4a991e8), 
00:07:27.073  INFO:        0 files found in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/../corpus/llvm_vfio_0
00:07:27.073  INFO: A corpus is not provided, starting from an empty corpus
00:07:27.073  #2	INITED exec/s: 0 rss: 149Mb
00:07:27.073  WARNING: no interesting inputs were found so far. Is the code instrumented for coverage?
00:07:27.073  This may also happen if the target rejected all inputs we tried so far
00:07:27.073  [2023-09-07 10:48:31.253687] vfio_user.c:2301:handle_del_io_q: *ERROR*: /tmp/vfio-user-0/domain/2: I/O sqid:0 does not exist
00:07:27.591  	NEW_FUNC[1/337]: 0x588720 in fuzz_vfio_user_region_rw /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:80
00:07:27.591  	NEW_FUNC[2/337]: 0x58c1d0 in TestOneInput /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:105
00:07:27.591  #4	NEW    cov: 5543 ft: 5052 corp: 2/31b lim: 60 exec/s: 0 rss: 157Mb L: 30/30 MS: 2 InsertByte-InsertRepeatedBytes-
00:07:27.851  	NEW_FUNC[1/3]: 0x1ffc100 in nvme_pcie_qpair /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/lib/nvme/./nvme_pcie_internal.h:204
00:07:27.851  	NEW_FUNC[2/3]: 0x237cc50 in get_rusage /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/lib/event/reactor.c:609
00:07:27.851  #7	NEW    cov: 5617 ft: 6917 corp: 3/37b lim: 60 exec/s: 0 rss: 158Mb L: 6/30 MS: 3 CrossOver-CopyPart-CopyPart-
00:07:28.111  #8	NEW    cov: 5617 ft: 7227 corp: 4/44b lim: 60 exec/s: 8 rss: 159Mb L: 7/30 MS: 1 InsertByte-
00:07:28.681  #12	NEW    cov: 5617 ft: 7410 corp: 5/74b lim: 60 exec/s: 12 rss: 159Mb L: 30/30 MS: 4 InsertByte-CrossOver-InsertByte-CrossOver-
00:07:28.940  #13	NEW    cov: 5624 ft: 7634 corp: 6/81b lim: 60 exec/s: 13 rss: 160Mb L: 7/30 MS: 1 ShuffleBytes-
00:07:29.509  #14	NEW    cov: 5624 ft: 7694 corp: 7/110b lim: 60 exec/s: 7 rss: 161Mb L: 29/30 MS: 1 EraseBytes-
00:07:29.509  #14	DONE   cov: 5624 ft: 7694 corp: 7/110b lim: 60 exec/s: 7 rss: 161Mb
00:07:29.509  Done 14 runs in 2 second(s)
00:07:30.078  AddressSanitizer:DEADLYSIGNAL
00:07:30.078  =================================================================
00:07:30.078  ==328174==ERROR: AddressSanitizer: SEGV on unknown address 0x20004d7ffec8 (pc 0x00000200ae23 bp 0x7f8704604a40 sp 0x7f87046044e0 T4)
00:07:30.078  ==328174==The signal is caused by a READ memory access.
00:30:22.152  Cancelling nested steps due to timeout
00:30:22.155  Sending interrupt signal to process
00:30:37.537  Terminated
00:30:37.548  script returned exit code 143
```

## Steps to Reproduce

1. Prepare configuration file:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_FUZZER_SHORT=1
SPDK_TEST_FUZZER=1
SPDK_RUN_UBSAN=1
SPDK_RUN_ASAN=1
```
2. Build SPDK:
```
./configure --enable-asan --enable-ubsan --enable-coverage \
--enable-werror --enable-debug --with-crypto --with-fuse \
--with-idxd --with-nvme-cuse --with-rdma --with-usdt --with-fio \
--with-iscsi-initiator --with-nvme-cuse --with-vbdev-compress \
--with-dpdk-compressdev --with-rbd --with-ublk --with-raid5f --with-ocf \
--with-vfio-user --with-sma --with-xnvme --with-avahi --with-uring --with-ocf
make -j
```
3. Run tests:
```
sudo -E ./autotest.sh ~/autorun.conf
```

## Context (Environment including OS version, SPDK version, etc.)

Fedora 37 6.1.14-200.fc37.x86_64
clang version 15.0.7 (Fedora 15.0.7-1.fc37)

Test run with:
https://review.spdk.io/gerrit/c/spdk/spdk/+/17143
based on branch master commit:
2470b9957a6c60b0f5a3cd2cbee4bb5099ac8488

**Comment by karlatec** [comment]
This may seem like a duplicate of: https://github.com/spdk/spdk/issues/2992.
Unfortunately I don't have a full fail log of 2992 to compare, but I feel like this fails at some different point during testing.

**Comment by karlatec** [comment]
Issue seems still active. More recent logs:
https://ci.spdk.io/public_build/autotest-per-patch_111218.html
https://ci.spdk.io/results/autotest-per-patch/builds/111218/archive/short-fuzz-phy-autotest_8018/build.log

**Comment by karlatec** [comment]
Issue still active:
https://review.spdk.io/gerrit/c/spdk/spdk/+/17143/83
https://ci.spdk.io/public_build/autotest-per-patch_117759.html
https://ci.spdk.io/results/autotest-per-patch/builds/117759/archive/short-fuzz-phy-autotest_18542/build.log

@sberbz any chance we could get this going?

**Comment by sberbz** [comment]
Hi
It seems like a root cause of this issue is `ocf` being enabled at the same time as `vfio`. In this case there `vfio` cannot create controller and send signal to stop fuzzer drive (since fuzzer only exit on timeout), so it's common for fuzzer to crash when there is issue on SPDK side.

Vfio fuzzer create two ctrlr's, one for io and other for fuzzing, while io ctrlr is created libvfio log that `/tmp/vfio-user-6/domain/2: hit max regions 16` and fail ctrlr creation.
Increasing max_region to 32 solve this issue but I'm still not sure why enabling `ocf` caused it, I just don't see any obvious link between vfio and ocf.

**Comment by sberbz** [comment]
As I mention before, the root cause of this issue is an insufficient number of DMA regions provided by libvfio-user `#define MAX_DMA_REGIONS 16` lib/private.h, for both libvfio-user and OCF (needs 17).  An easy fix is to increase that value, but since it's really specific use case where OCF allocates a lot of resources at start and fuzzer starts target and initiator in the same process, makes me uncertain as to the value of this change. Especially because we don't encounter such problem in any other tests, and SPDK really doesn't need to map all the regions but memory that needs mapping and doesn't are indistinguishable.  

For this reason, I propose to make OCF and fuzzer mutual exclusive. 
Also, here is discussion from libvfio-user git page on issue of similar matter https://github.com/nutanix/libvfio-user/issues/588.

**Comment by jimharris** [comment]
I'm fine with making them mutually exclusive.

**Comment by sberbz** [comment]
Exception is added to patch that enable all flags.
https://review.spdk.io/gerrit/c/spdk/spdk/+/17143/88..91
