### ISSUE TITLE
Debian install issues

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3123]
Installed Debian 12.1, and ran into a couple of issues:

1) pkg-config must be installed explicitly, this doesn't seem to be the case with Ubuntu
2) the pip3 install lines fails, there are a few suggestions for fixing it here (https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3) but probably adding the --break-system-packages is best, it mimics what happens on Ubuntu I believe

**Comment by mikeBashStuff** [comment]
For 2., please see https://review.spdk.io/gerrit/c/spdk/spdk/+/17267. Will add patch for the pkg-config. I believe there's also issue with kernel headers (i.e. the pkg differs from what's used for ubuntu), so will fix that too.

**Comment by jimharris** [comment]
> For 2., please see https://review.spdk.io/gerrit/c/spdk/spdk/+/17267. Will add patch for the pkg-config. I believe there's also issue with kernel headers (i.e. the pkg differs from what's used for ubuntu), so will fix that too.

Thanks @mikeBashStuff, I'd looked at the patch somewhat recently, I didn't draw the correlation to this issue until just now.

I left a comment on that patch, it would require users changing their PATH to be able to build SPDK on affected systems.  And it sounds like eventually "affected systems" will equal "all systems". Is there any way we can avoid that?  i.e. install packages instead of through pip3? But maybe if some aren't available through packages, we revert to pip3. Open to other ideas as well.

**Comment by mikeBashStuff** [comment]
Sorry, I completely forgot about this issue - here's the extra patch addressing 1. - https://review.spdk.io/gerrit/c/spdk/spdk/+/23082 (it's on top of the series which also addresses 2.).

**Comment by mikeBashStuff** [comment]
Series got merged, hopefully it should mitigate the issue. If not, please feel free to reopen it.
