### ISSUE TITLE
[nvmf_ns_hotplug_stress] Read NLB 1 * block size 512 > SGL length 1

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#3130]
# CI Intermittent Failure

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/109215/archive/nvmf-phy-autotest_50850/build.log

## Execution failed at

00:08:48.285   20:32:22	-- target/ns_hotplug_stress.sh@35 -- # kill -0 692414
00:08:48.285   20:32:22	-- target/ns_hotplug_stress.sh@36 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_ns nqn.2016-06.io.spdk:cnode1 1
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718   20:32:23	-- target/ns_hotplug_stress.sh@37 -- # /var/jenkins/workspace/nvmf-phy-autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Delay0
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  Message suppressed 999 times: Read completed with error (sct=0, sc=11)
00:08:49.718  [2023-09-07 20:32:23.833092] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1

00:08:50.430  [2023-09-07 20:32:24.463977] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.463998] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464017] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464036] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464055] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464074] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464092] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464117] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464138] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464160] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.464196] ctrlr_bdev.c: 290:nvmf_bdev_ctrlr_read_cmd: *ERROR*: Read NLB 1 * block size 512 > SGL length 1
00:08:50.430  [2023-09-07 20:32:24.628965] nvme_ctrlr.c:3034:nvme_ctrlr_clear_changed_ns_log: *ERROR*: [nqn.2016-06.io.spdk:cnode1] spdk_nvme_ctrlr_cmd_get_log_page() failed: rc=-6
00:08:50.430  NVMe io qpair process completion error

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_109215.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksprzacz. log: https://ci.spdk.io/public_build/autotest-per-patch_114321.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_116482.html
