### ISSUE TITLE
[fio/spdk_bdev] Use of fsync_on_close with fio-3.35 breaks vhost_shared test

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3133]
Due to the following change https://github.com/axboe/fio/commit/870ea00243b1290541334bec2a56428c9f68dba6 (related issue https://github.com/axboe/fio/issues/1577)  the use of `fsync_on_close=1` forces fio to error out in the vhost_shared test:

```
10:52:25       -- common/autotest_common.sh@1324 -- # LD_PRELOAD=' /root/spdk/build/fio/spdk_bdev'
 10:52:25       -- common/autotest_common.sh@1324 -- # /usr/src/fio/fio --ioengine=spdk_bdev /root/spdk/test/vhost/common/fio_jobs/default_initiator.job --runtime=10 --rw=randrw --spdk_mem=1024 --spdk_single_seg=1 --verify_state_save=0 --spdk_json_conf=/dev/fd/62 --size=50% --offse
t=50% --filename=VirtioBlk0
job0: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=32
fio-3.35
Starting 1 thread
fio: io_u error on file VirtioBlk0: Input/output error: sync offset=19079168, buflen=4096
fio: end_fsync failed for file VirtioBlk0
fio: pid=215025, err=5/file:io_u.c:1889, func=io_u error, error=Input/output error

job0: (groupid=0, jobs=1): err= 5 (file:io_u.c:1889, func=io_u error, error=Input/output error): pid=215025: Thu Sep 14 10:52:25 2023
```

whole fio configuration looks like this https://github.com/spdk/spdk/blob/master/test/vhost/common/fio_jobs/default_initiator.job:
```
[global]
thread=1
group_reporting=1
direct=1
time_based=1
do_verify=1
verify=md5
verify_backlog=1024
fsync_on_close=1
iodepth=32
verify_state_save=0
[job0]
```

It seems the commit on the `fio` side is an actual improvement so this issue could've gone unnoticed for a while. Not sure what the proper solution should be in this case, given the nature of the test (two parallel fio instances that attempt to write to the same device|bdev on different offsets and then both trying to fsync() it).

Removing `fsync_on_close` is a valid mitigation though.  

Currently this does not affect CI as the test suites use fio-3.28. This however blocks us from bumping the version to the latest release in production (as per the `pkgdep` infra).

**Comment by mikeBashStuff** [comment]
Here's a small improvement for the cleanup of this test in case similar issue occurs: https://review.spdk.io/gerrit/c/spdk/spdk/+/19892

**Comment by mikeBashStuff** [comment]
Even though the test is using two fio instances running at the same time, this does not seem to be a factor here - failure occurs even when only single instance (e.g. the first one) is running. Also, tried with different bdev (nvme instead of malloc), same result.

**Comment by tomzawadzki** [comment]
Did a bit of research on fsync and related functionality with fio/fio_plugin. In general `fsync=` will result in `spdk_bdev_flush()`, that works on various bdevs. Meanwhile in some cases `fsync_on_close=` (or `end_fsync=`) will result in actual `fsync(f->fd)` being called despite SPDK plugins not opening any actual files (see `spdk_fio_open/close`).

Ideally it would be preferable to get one last `.queue` callback with DDIR_SYNC. If not, then at the very least skip the `fsync()` call on specific ioengines. There are few others that do not open files in upstream fio, so there might already be a case to repro there. There is more investigation to be done to either submit issue or PR to FIO, if not possible to force specific behaviour in spdk plugins.

Despite all of the above, fsync related options are unused in SPDK tests when one of  SPDK ioengines is used. Other instances in tests are with libaio and on VMs. This particular job config (`default_initiator.job`) seems to be a copy of `default_integrity.job`, that uses libaio. Meanwhile `test/vhost/shared/shared.sh` used virtio_blk, that does not support `SPDK_BDEV_IO_TYPE_FLUSH` - it never even had a chance to work.

I'd argue for removal of the fsync from this particular test, and if it is to be added back it has to be after resolving this issue and against a backend that does support flushes. See https://review.spdk.io/gerrit/c/spdk/spdk/+/19930/

**Comment by mikeBashStuff** [comment]
Patch got merged, verified in staging - all is working fine now.
