### ISSUE TITLE
fio_plugin: Has options for WRR Arbitration but doesn't perform set_features to enable them

### ISSUE THREAD

**Issue by curtbruns** [spdk/spdk#3135]
The spdk_nvme fio plugin has options for "enable_wrr" and different arbitration settings (low_weight, medium_weight, etc). When QP are created and enable_wrr is selected, those QP are created with the fio_options->wrr_priority for that job, but the WRR weights that are configured in the options are never setup in the controller. The weights are never sent to the controller with a "set_features" command.

## Expected Behavior
Similar to the examples/nvme/arbitration code, if enable_wrr is set as an option to the fio_plugin, I would expect the fio_plugin to use set_features to send down the arbitration settings to the controller.

## Current Behavior
Set_features is not called and arbitration settings are set to their default levels so all jobs are completed with the same priority.

## Possible Solution
Have fio_plugin call set_features and send down the arbitration settings that are set via the spdk engine options.

## Steps to Reproduce
Run an FIO job with the following settings in the fio job file:
...
enable_wrr=1
high_weight=32
medium_weight=16
low_weight=8
shm_id=1
...
[wr_rnd_qd_64_4k_low]
iodepth=64
wrr_priority=3
cpus_allowed=1
...

When the job is running, run the "identify" example and you will see the arbitration settings are not set in the controller.
...
Arbitration
===========
Arbitration Burst:           1
Low Priority Weight:         1
Medium Priority Weight:      3
High Priority Weight:        6
 ...

**Comment by changpe1** [comment]
@curtbruns I think you missed `arbitration_burst=1` parameter in your fio configuration file, so the set feature code just skipped.

**Comment by curtbruns** [comment]
Thank you @changpe1 - can you show me where in the code the "set feature" code is called? I don't see it.

**Comment by changpe1** [comment]
> Thank you @changpe1 - can you show me where in the code the "set feature" code is called? I don't see it.

https://github.com/spdk/spdk/blob/master/lib/nvme/nvme_ctrlr.c#L922

**Comment by curtbruns** [comment]
Thank you - this is very helpful. I'll close the issue.

**Comment by charuwad** [comment]
which version of fio is being used ? All these wrr options result in error as follows: 
[root@localhost fio_plugin]# LD_PRELOAD=/root/spdk/examples/nvme/fio_plugin/fio_plugin fio wrr_config.io '--filename=trtype=PCIe tradde=0000.03.00.0 ns=1'
Bad option <arbitration_burst=1>
Bad option <enable_wrr=1>
Bad option <high_weight=32>
Did you mean cgroup_weight?
Bad option <medium_weight=16>
Did you mean cgroup_weight?
Bad option <low_weight=8>
Did you mean cgroup_weight?
Bad option <...>
fio: job global dropped
**
