### ISSUE TITLE
[vfio_user_virtio_bdevperf] Timeout during bdev_virtio_attach_controller 

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#3136]
# CI Intermittent Failure

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/109859/archive/vfio-user-phy-autotest_5591/build.log

## Execution failed at
```
00:10:11.374  [2023-09-15 15:24:23.222941] vfu_virtio.c:1257:virtio_vfu_access_bar4: *DEBUG*: /tmp/vfu_devices/vfu.scsi: read bar4 0x14-0x14, len = 1
00:10:11.374  [2023-09-15 15:24:23.222948] vfu_virtio.c:1111:virtio_vfu_pci_common_cfg: *DEBUG*: /tmp/vfu_devices/vfu.scsi: READ PCI_COMMON_STATUS with 0xf
00:10:11.374  [2023-09-15 15:24:23.222981] virtio_vfio_user.c:  65:virtio_vfio_user_get_status: *DEBUG*: device status f
00:11:19.099  Timeout while waiting for response:
00:11:19.099  
00:11:19.099  
00:11:19.099    15:25:23	-- virtio/initiator_bdevperf.sh@44 -- # trap - ERR
00:11:19.099    15:25:23	-- virtio/initiator_bdevperf.sh@44 -- # print_backtrace
00:11:19.099    15:25:23	-- common/autotest_common.sh@1100 -- # [[ ehxBET =~ e ]]
00:11:19.099    15:25:23	-- common/autotest_common.sh@1102 -- # args=()
00:11:19.099    15:25:23	-- common/autotest_common.sh@1102 -- # local args
00:11:19.099    15:25:23	-- common/autotest_common.sh@1104 -- # xtrace_disable
00:11:19.099    15:25:23	-- common/autotest_common.sh@10 -- # set +x
00:11:19.099  ========== Backtrace start: ==========
00:11:19.099  
00:11:19.099  in /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/vfio_user/virtio/initiator_bdevperf.sh:44 -> main([])
00:11:19.099       ...
00:11:19.099     39  	
00:11:19.099     40  	$bdevperf -r $bdevperf_rpc_sock -g -s 2048 -q 256 -o 4096 -w randrw -M 50 -t 30 -m 0xf0 -L vfio_pci -L virtio_vfio_user &
00:11:19.099     41  	bdevperf_pid=$!
00:11:19.099     42  	trap 'killprocess $bdevperf_pid; exit 1' SIGINT SIGTERM EXIT
00:11:19.099     43  	waitforlisten $bdevperf_pid $bdevperf_rpc_sock
00:11:19.099  => 44  	$rpc_py -s $bdevperf_rpc_sock bdev_virtio_attach_controller --dev-type scsi \
00:11:19.099     45  		--trtype vfio-user --traddr $vfu_dir/vfu.scsi VirtioScsi0
00:11:19.099     46  	$rpc_py -s $bdevperf_rpc_sock bdev_virtio_attach_controller --dev-type blk \
00:11:19.099     47  		--trtype vfio-user --traddr $vfu_dir/vfu.blk VirtioBlk0
00:11:19.099     48  	
00:11:19.099     49  	# Start the tests
00:11:19.099       ...
00:11:19.099  
00:11:19.099  ========== Backtrace end ==========```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_109859.html

**Comment by tomzawadzki** [comment]
The concerning part I think might be starting at either of the below:
```
00:10:11.113  [2023-09-15 15:24:23.184971] vfu_virtio.c: 267:virtio_dev_enable_vq: *DEBUG*: vfu.scsi: enable vq 0
00:10:11.113  [2023-09-15 15:24:23.184976] vfu_virtio.c:  71:virtio_dev_map_vq: *DEBUG*: vfu.scsi: try to map vq 0
00:10:11.113  [2023-09-15 15:24:23.184985] vfu_virtio.c:  77:virtio_dev_map_vq: *DEBUG*: Error to map descs
00:10:11.113  [2023-09-15 15:24:23.184989] vfu_virtio.c: 277:virtio_dev_enable_vq: *ERROR*: Queue 0 failed to map
```
or
```
00:10:10.541  CRYPTODEV: rte_cryptodev_pmd_create() line 122: Failed to allocate crypto device for 0000:b1:01.0_qat_sym
00:10:10.541  qat_pci_probe(): Failed to create QAT SYM PMD on device 0000:b1:01.0_qat
00:10:10.541  rte_compressdev_pmd_create(): Failed to allocate comp device 0000:b1:01.0_qat_comp
00:10:10.541  qat_pci_probe(): Failed to create QAT COMP PMD on device 0000:b1:01.0_qat
00:10:10.541  CRYPTODEV: rte_cryptodev_pmd_create() line 122: Failed to allocate crypto device for 0000:b1:01.0_qat_asym
00:10:10.541  qat_pci_probe(): Failed to create QAT ASYM PMD on device 0000:b1:01.0_qat
```

**Comment by changpe1** [comment]
The failed physical memory address is 4ac8ec000 which not belong to "00:10:11.112  [2023-09-15 15:24:23.128284] vfio_user_pci.c:  65:vfio_add_mr: *DEBUG*: Add memory region: FD 10, VADDR 0x200000200000, IOVA 0x200000200000, Size 0x80000000" range. The client only registered this memory range to target.

00:10:11.113  [2023-09-15 15:24:23.185042] virtio_vfio_user.c: 332:virtio_vfio_user_setup_queue: *DEBUG*: 	 desc_addr: 4ac8ec000

let me take a look of this issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_111997.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_112418.html

**Comment by tomzawadzki** [comment]
[Bug scrub] @changpe1 Any updates on this issue, or ways we could improve the CI report/test to provide more information ?

**Comment by changpe1** [comment]
> [Bug scrub] @changpe1 Any updates on this issue, or ways we could improve the CI report/test to provide more information ?

This issue may be related with above QAT failures, all the failed 3 logs have the same error logs when starting `bdevperf` at the beginning.  In SPDK, we're assuming that the use of `spdk_zmalloc` for a 2 MiB memory allocation should be in one single memory segment file, `-m 2048 --single-file-segments` is used to make sure of that.

All the failed cases, the use of `spdk_zmalloc` returned a memory that exceed the expected memory range, while this memory range isn't registered to remote.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_115380.html

**Comment by tomzawadzki** [comment]
Closing, since the issue did not occur for last 5 months.
