### ISSUE TITLE
nvmf/rdma: qpairs not distributed evenly across pollgroups

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#3137]
# Sighting report

Connecting from multiple kernel initiators in parallel to a nvmf/rdma target leads to uneven distribution of IO qpairs.

Here's an example where one poll group has many more IO qpairs than others:
```
NVMF qpairs distribution across poll groups******************
           Poll Group|Current Admin Qpairs|Current IO Qpairs|
nvmf_tgt_poll_group_1|.................101|..............281|
nvmf_tgt_poll_group_2|.................100|...............40|
nvmf_tgt_poll_group_3|..................99|...............40|
nvmf_tgt_poll_group_4|.................100|...............39|
```

## Expected Behavior

The distribution of qpairs should be even across all pollgroups. It seems that disabling the optimal pollgroup in rmda.c gets better results but qpairs are still not distributed evenly.

## Possible Solution

Adding the unassociated qpairs is somewhat suspicous:
```
static uint32_t
nvmf_poll_group_get_io_qpair_count(struct spdk_nvmf_poll_group *pg)
{
	uint32_t count;

	/* Just assume that unassociated qpairs will eventually be io
	 * qpairs.  This is close enough for the use cases for this
	 * function.
	 */
	pthread_mutex_lock(&pg->mutex);
	count = pg->stat.current_io_qpairs + pg->current_unassociated_qpairs;
	pthread_mutex_unlock(&pg->mutex);

	return count;
}
```

## Steps to Reproduce

Do a "nvme connect-all" from a couple of hosts to the same NVMF target.

## Context (Environment including OS version, SPDK version, etc.)
SPDK 23.01
Debian 12

**Comment by AlekseyMarchuk** [comment]
Thanks for reporting this issue. That used to work, I'll check what is wrong

**Comment by mhae** [comment]
@AlekseyMarchuk , thanks. Also, shouldn't tgt->next_poll_group be protected by a mutex in spdk_nvmf_tgt_new_qpair?

**Comment by mhae** [comment]
It seems we're moving to the next pg too soon. This seems to help:

```
while ((count = nvmf_poll_group_get_io_qpair_count(pg_current->group.group)) > 0) {
			SPDK_NOTICELOG("??? pg=%s, count=%d\n", spdk_thread_get_name(pg_current->group.group->thread), count);
			// pg_current = TAILQ_NEXT(pg_current, link);
			// if (pg_current == NULL) {
			// 	pg_current = TAILQ_FIRST(&rtransport->poll_groups);
			// }

			if (count < min_value) {
				min_value = count;
				pg_min = pg_current;
			}

			// mhae:
			pg_current = TAILQ_NEXT(pg_current, link);
			if (pg_current == NULL) {
				pg_current = TAILQ_FIRST(&rtransport->poll_groups);
			}

			if (pg_current == pg_start) {
				break;
			}
		}
```

**Comment by AlekseyMarchuk** [comment]
Looks good. Since you found a solution, will you push a patch to gerrit?

**Comment by mhae** [comment]
Review at https://review.spdk.io/gerrit/c/spdk/spdk/+/19941

**Comment by AlekseyMarchuk** [comment]
Thank you @mhae!
As we discussed on the Community meeting yesterday, we need to add a functional test to verify this fix. Let's keep this issue open until such test is added

**Comment by mhae** [comment]
Fixed in https://review.spdk.io/gerrit/c/spdk/spdk/+/19941
