### ISSUE TITLE
run vhost as non-root

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#314]
## Expected Behavior

I'd like to invoke app/vhost/vhost as part of automated testing of my JSON-based client as unprivileged user. It's okay if vhost in that mode can't provide all functionality, as long as simple operations (like creating creating a malloc bdev) work.

## Current Behavior

It already fails early on:
```
$ app/vhost/vhost -S /tmp 
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: vhost -c 0x1 -m 1024 --file-prefix=spdk_pid184836 ]
EAL: Detected 44 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /home/pohly/.spdk_pid184836_unix
EAL: Probing VFIO support...
EAL: Cannot obtain physical addresses: No such file or directory. Only vfio will function.
EAL: Not enough memory available! Requested: 1024MB, available: 0MB
EAL: FATAL: Cannot init memory

EAL: Cannot init memory

Failed to initialize DPDK
app.c: 430:spdk_app_setup_env: *ERROR*: Unable to initialize SPDK env
```

This is because creating /dev/hugepages/spdk_pid* fails.

## Possible Solution

Probably adding file capabilities (which ones?) could be used to run vhost with elevated privileges when invoked by a normal user.

But perhaps a simpler solution where no huge pages are used is also possible?

DPDK has an option for it (http://dpdk.org/ml/archives/dev/2016-November/050109.html, lib/librte_eal/common/eal_common_options.c), but I can't find something similar in the vhost app.

**Comment by pawelwod** [comment]
Running any target without root privilage will be problematic. You can try this guide 
https://dpdk.org/doc/guides/linux_gsg/enable_func.html#running-dpdk-applications-without-root-privileges
but I don't feel this will work. Simple and fast solution is to run vhost as root. You can also run vhost inside virtual machine (just use hugepages as VM memory backend).

**Comment by pohly** [comment]
I understand that some operations won't work. What I'm aiming for is just something simple, like creating/destroying a malloc bdev. The goal is to run this as part of automated testing on "normal" Linux distros (no sudo rights, no special preparations), so the DPDK guide doesn't really help.

**Comment by pohly** [comment]
Jim Harris <notifications@github.com> writes:
> So you’re not looking to use PCI devices (and performance DMA with
> those devices) as non-root – you just want to run some app (like
> vhost) as non-root with a backend bdev like malloc?

Correct.

**Comment by darsto** [comment]
Some time ago I wrote a guide for running SPDK as a non priviledged user. It's still hanging on gerrithub, but needs to be updated now that DPDK 18.11 is released: https://review.gerrithub.io/c/spdk/spdk/+/432040

**Comment by pohly** [comment]
Darek Stojaczyk <notifications@github.com> writes:

> Some time ago I wrote a guide for running SPDK as a non priviledged
> user. It's still hanging on gerrithub, but needs to be updated now
> that DPDK 18.11 is released:
> https://review.gerrithub.io/c/spdk/spdk/+/432040

That still depends on reserving huge pages as root for a non-root
user. That's good, but even better would be to support a mode where huge
pages are not needed.

**Comment by changpe1** [comment]
Bug Scrub: @darsto , can you update the status? thanks.

**Comment by darsto** [comment]
> Can we build something around DPDK's --no-huge option?

Either that or we could enable DPDK's --in-memory flag for transparent hugepages. It's still hugepages, but there's no need to reserve them on the system by hand.

I still need to play a little more with DPDK 18.11

**Comment by darsto** [comment]
Bug scrub: There is quite amount of work required to get it tested on our CI. We'll just put in on the backlog for now.

**Comment by jimharris** [comment]
@Donaim @benlwalker Did we get this working with latest DPDK?

**Comment by benlwalker** [comment]
I just tested and at least the identify example and hello world are working as an unprivileged user as expected. I haven't set up the whole vhost suite just yet. There may be some additional set up to get the domain sockets created correctly, but beyond that I don't foresee any problems.

**Comment by jimharris** [comment]
Thanks Ben.  Do we need to add some docs somewhere to walk people through how to do this, before closing this issue?  Maybe @Donaim could take a look at writing something up.

**Comment by dong-liuliu** [comment]
hi @benlwalker 
which kernel are you using? I tried example/nvme/identify with kernel 4.15 and DPDK 19.05.
But it failed on read /proc/self/pagemap, as DPDK documented.

**Comment by benlwalker** [comment]
You just need to turn on the IOMMU, run ./scripts/setup.sh using sudo, and you should be able to run the SPDK applications without elevated permissions. All the magic to make it happen is in scripts/setup.sh.

Someone still does need to confirm this works with vhost though. There's just one or two more things that may pop up, such as the creation of the UNIX domain sockets, that may need permissions correctly set.

**Comment by Donaim** [comment]
@jimharris sure I will do that, but I first need to check if it everything works for vhost target as it does for examples that Ben tested. (Didn't try it yet)

**Comment by Donaim** [comment]
I could run vhost locally with no issues at all if hugepages were available for regular user,
but I couldn't even start hello_world example without allocating hugepages.
We don't support `--no-huge` or `--in-memory` flags for DPDK,
so there does not seem to be a way to achieve what @pohly initially requested.

For the case when hugepages are available, the guide of @darsto provides everything that user needs.
But for initial request, we would still need to add support for the case with no available hugepages.

**Comment by changpe1** [comment]
@Donaim Could you update the document so that we can close this issue, thanks.

**Comment by Donaim** [comment]
@changpe1 Ok, working on that.

**Comment by Donaim** [comment]
documentation patch is waiting for review, but someone needs to take over
https://review.spdk.io/gerrit/c/spdk/spdk/+/2850

**Comment by tomzawadzki** [comment]
Patch documenting running spdk as non-root is now merged.
https://review.spdk.io/gerrit/c/spdk/spdk/+/2850
