### ISSUE TITLE
[VM-host-SM18] Cannot contact VM-host-SM18 

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#3142]
# CI Intermittent Failure

Build times out on different tests specifically on VM-host-SM18. Couldn't find any other common denominator.

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/110626/archive/rocky8-vg-autotest_41394/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/110626/archive/ubuntu22-vg-autotest_19120/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/110625/archive/nvmf-tcp-vg-autotest_55994/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/110624/archive/nvmf-tcp-vg-autotest_55997/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/110623/archive/rocky8-vg-autotest_41393/build.log

## Execution failed at
```
00:20:49.148  Cannot contact VM-host-SM18: java.lang.InterruptedException
00:31:04.471  wrapper script does not seem to be touching the log file in /var/jenkins/workspace/nvmf-tcp-vg-autotest_3/fedora37-libvirt_tmp/durable-3966c5d8
00:31:04.471  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```
OR
```
00:21:04.171  Cannot contact VM-host-SM18: java.lang.InterruptedException
00:26:19.365  process apparently never started in /var/jenkins/workspace/nvmf-tcp-vg-autotest_2/fedora37-libvirt_tmp/durable-ca4c81d4
00:26:19.365  (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
```

**Comment by mikeBashStuff** [comment]
Disconnecting SM18 from the pool (it shouldn't be enabled in a first place).

**Comment by jimharris** [comment]
@mikeBashStuff can we close this?

**Comment by mikeBashStuff** [comment]
> @mikeBashStuff can we close this?

Most definitely, yes. :)
