### ISSUE TITLE
construct_malloc_bdev: total_size in MB or GB

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#315]
## Expected Behavior

``rpc.py construct_malloc_bdev 1 512`` should create a bdev of 1MB = two blocks, according to the help text:
```
rpc.py construct_malloc_bdev --help
usage: rpc.py construct_malloc_bdev [-h] [-b NAME] [-u UUID]
                                    total_size block_size

positional arguments:
  total_size            Size of malloc bdev in MB (int > 0)
  block_size            Block size for this bdev
```

## Current Behavior

It seems to create a bdev of 1GB:
```
{\"params\": {\"block_size\": 512, \"num_blocks\": 2048}
...
 {
    "num_blocks": 2048, 
    "uuid": "c58c3c79-5f54-415f-8d40-a4bd4353ae4b", 
    "aliases": [], 
    "claimed": false, 
    "driver_specific": {}, 
    "supported_io_types": {
      "reset": true, 
      "nvme_admin": false, 
      "unmap": true, 
      "read": true, 
      "write_zeroes": true, 
      "write": true, 
      "flush": true, 
      "nvme_io": false
    }, 
    "qos_ios_per_sec": 0, 
    "block_size": 512, 
    "product_name": "Malloc disk", 
    "name": "Malloc2"
  }
```

## Possible Solution

Looks like the help text is incorrect.

**Comment by pohly** [comment]
Is there a minimum size? I tried with block_size = 512, num_blocks = 10 in my JSON client and that was rejected.

**Comment by xuhuagen** [comment]
The minimum size of malloc bdev should be 1MB.
malloc bdev size can bd calculated as bdelow
bdev size(MB) = "block_size" * "num_blocks" /1024/1024

**Comment by wanqunintel** [comment]
@pohly The total_size is in unit of MB not GB, you may refer to the file spdk/scripts/rpc.py line 106 num_blocks = (args.total_size * 1024 * 1024) // args.block_size

**Comment by pohly** [comment]
Right, my bad.
