### ISSUE TITLE
`max_namespaces` defaults to 32 when set to 0 or omitted

### ISSUE THREAD

**Issue by 1pav** [spdk/spdk#3151]
# Sighting report

## Expected Behavior

When creating an nvmf subsystem via the JSON-RPC interface, setting `max_namespaces` to 0 (or omitting it entirely), should create an nvmf subsystem with an "unlimited" maximum number of namespaces. This is the expectation according to the [documentation](https://spdk.io/doc/jsonrpc.html).

## Current Behavior

When creating an nvmf subsystem via the JSON-RPC interface with `max_namespaces` set to 0 (or omitted), the resulting nvmf subsystem has its `max_namespaces` parameter set to 32.

## Possible Solution

The _default_ `max_namespaces` should be virtually unlimited, i.e. constrained by the resources of the running system. If that's not possible, maybe increase the default value of `max_namespaces`. I think it's not unreasonable for a production system to present more than 32 namespaces (i.e. nvmf devices).

## Steps to Reproduce

1. Setup hugepages/device binding:

```
./scripts/setup.sh
```

2. Run the nvmf target application:

```
./build/bin/nvmf_tgt &
```

3. Create an nvmf subsystem with `max_namespaces` omitted or set to `0`: 

```
./scripts/rpc.py nvmf_create_subsystem nqn.2023-10.com.github:foo
# OR
./scripts/rpc.py nvmf_create_subsystem --max-namespaces 0 nqn.2023-10.com.github:foo 
```

Verify the value of `max_namespaces`  in the resulting subsystem:

```
./scripts/rpc.py nvmf_get_subsystems nqn.2023-10.com.github:foo | grep max_namespaces
```

## Context (Environment including OS version, SPDK version, etc.)

- SPDK built from `master` branch (commit: 68d8ff470ac84d8128fcfa5d00b1be953e9e56cb):

```
./build/bin/nvmf_tgt --version
SPDK v24.01-pre git sha1 68d8ff470
```

- OS: Rocky Linux 8.8
- Kernel: 4.18.0-477.27.1.el8_8.x86_64

**Comment by jimharris** [comment]
This is a documentation bug. Intent is to use the default (32) if user does not specify a value or explicitly specifies 0. Unlimited namespaces is not supported - if it was we wouldn't need the max_namespaces parameter. There are many arrays that get allocated based on this value which would require significant redesign to make it truly unlimited.

Patch to fix documentation is here: https://review.spdk.io/gerrit/c/spdk/spdk/+/21375

If you need your subsystem to support a lot of namespaces, just specify a large max_namespaces value.

**Comment by jimharris** [comment]
Doc patch merged.
