### ISSUE TITLE
Error occurs when use malloc bdev( less than 1M) to construct target node with rpc

### ISSUE THREAD

**Issue by xuhuagen** [spdk/spdk#316]
I tried use block_size=512,num_blocks=1024,to construct malloc malloc bdev( bdev size is 512k)  and use it construct target node, a error 
 `blobstore.c:2240:_spdk_bs_alloc: *ERROR*: Device size 524288 is smaller than cluster size 1048576`
occured in spdk target.

malloc bdev's config file  malloc_bdev.conf   as below
```
{
  "subsystems": [
    {
      "subsystem": "copy",
      "config": null
    },
    {
      "subsystem": "interface",
      "config": null
    },
    {
      "subsystem": "net_framework",
      "config": null
    },
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "block_size": 512,
            "num_blocks": 1024,
            "name": "Malloc0",
            "uuid": "78a0c153-3095-4bed-bf89-639d0785b287"
          },
          "method": "construct_malloc_bdev"
        }
      ]
    },
    {
      "subsystem": "nbd",
      "config": []
    },
    {
      "subsystem": "nvmf",
      "config": null
    },
    {
      "subsystem": "scsi",
      "config": null
    },
    {
      "subsystem": "vhost",
      "config": []
    },
    {
      "subsystem": "iscsi",
      "config": []
    }
  ]
}
```

malloc bdev message as below
```
{
    "num_blocks": 1024,
    "uuid": "78a0c153-3095-4bed-bf89-639d0785b287",
    "aliases": [],
    "claimed": false,
    "driver_specific": {},
    "supported_io_types": {
      "reset": true,
      "nvme_admin": false,
      "unmap": true,
      "read": true,
      "write_zeroes": true,
      "write": true,
      "flush": true,
      "nvme_io": false
    },
    "qos_ios_per_sec": 0,
    "block_size": 512,
    "product_name": "Malloc disk",
    "name": "Malloc0"
  }
``` 
iscsiadm  discovery : 
`127.0.0.1:3260,1 iqn.2016-06.io.spdk:Target1`
## Expected Behavior

If error occured,the target node is should not be constructed.
## Current Behavior

The target node is constructed successfully and can be connected by initiator.
## Steps to Reproduce

1.  ./app/spdk_tgt/spdk_tgt
2.  scripts/rpc.py add_portal_group 1 127.0.0.1:3260
3.  scripts/rpc.py add_initiator_group 1 ANY 127.0.0.1/32
4.  scripts/prc.py load_config < malloc_bdev.conf
5.  scripts/rpc.py construct_target_node Target1 Target1_alias 'Malloc0:0' '1:1' 64 -d
6.   iscsiadm -m discovery -t st -p 127.0.0.1
7.  iscsiadm -m node -T iqn.2016-06.io.spdk:Target1 -p 127.0.0.1 --login

## Context (Environment including OS version, SPDK version, etc.)

OS version: CentOS Linux release 7.4
SPDK vsersion:    SPDK v18.07-pre

**Comment by wanqunintel** [comment]
@pawelkax , would you help to look at this issue?

**Comment by pawelkax** [comment]
I see that error occurs when creating malloc bdev via json config. But after loading config file malloc disk exists in spdk target.
I also noticed that iscsiadm works properly.
I also see that rpc method construct_malloc_bdev doesn't allow to create malloc with size < 1M. It is possible to create malloc with size lower that 1M using json config.
I think that rpc should be corrected to allow create small malloc bdevs and in spdk it also should be corrected (change error into notice).

**Comment by pawelwod** [comment]
Patch for this in review https://review.gerrithub.io/#/c/420054/

**Comment by xuhuagen** [comment]
@pawelwod  I patched https://review.gerrithub.io/#/c/420054/, error not occurs when use malloc bdev( less than 1M) to construct target node with rpc command line. it work for this issue.
