### ISSUE TITLE
Cannot save configuration with IAA/IOAT accel module enabled

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3161]
# Sighting report

Cannot save configuration with IAA accel module enabled.
RPC request times out.

## Expected Behavior

Configuration should be saved.

## Current Behavior

As in description.

## Steps to Reproduce

1. Start SPDK Target, configure DSA accel and a few Malloc bdevs and save config to make sure `save_config` works OK.
```
[sys_sgci@spdk-ac-02 spdk]$ sudo build/bin/spdk_tgt --wait-for-rpc &
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py dsa_scan_accel_module
[2023-10-20 20:46:26.528996] accel_dsa_rpc.c:  42:rpc_dsa_scan_accel_module: *NOTICE*: Enabling DSA user-mode
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py framework_start_init
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py bdev_malloc_create 10 4096
Malloc0
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py bdev_malloc_create 10 4096
Malloc1
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py save_config > /tmp/test1
```
Inspecting test1 file shows that configuration was saved successfully.

2. Do the same, but with IAA accel module
```
[sys_sgci@spdk-ac-02 spdk]$ sudo build/bin/spdk_tgt --wait-for-rpc &
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py iaa_scan_accel_module
[2023-10-20 20:48:31.223057] accel_iaa_rpc.c:  24:rpc_iaa_scan_accel_module: *NOTICE*: Enabling IAA user-mode
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py framework_start_init
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py bdev_malloc_create 10 4096
Malloc0
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py bdev_malloc_create 10 4096
Malloc1
[sys_sgci@spdk-ac-02 spdk]$ sudo -E ./scripts/rpc.py -t 30 --verbose DEBUG save_config > /tmp/test2
```

3. `save_config` gets stuck at:
```
DEBUG: Trying to decode response '
'
DEBUG: Partial response
DEBUG: Trying to decode response '
{"jsonrpc":"2.0","id":6,"result":[{"method":"accel_set_options","params":{"small_cache_size":128,"large_cache_size":16,"task_count":2048,"sequence_count":2048,"buf_count":2048}},{"method":"iaa_scan_accel_module"}}]}
'
DEBUG: Partial response
```
and ultimately times out.

4. Returned JSON response is not parsable by `jq` with error:
```
parse error: Objects must consist of key:value pairs at line 1, column 213
```
but after removing one of the curly braces from the very end of the string - it is possible to parse. Seems that somehwere there is this on extra brace added which makes the response not possible to parse.

## Context (Environment including OS version, SPDK version, etc.)

Linux spdk-ac-02 6.1.14-200.fc37.x86_64 https://github.com/spdk/spdk/issues/1 SMP PREEMPT_DYNAMIC Sun Feb 26 00:13:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
SPDK 631e75fc03a79bb5fe45a53d293e30bfabd947d8

**Comment by tomzawadzki** [comment]
[Bug scrub] IAA accel module is one place where the JSON is not written out correctly, but it would be worth to double check all the other accel modules as well.

**Comment by karlatec** [comment]
Check for this particular issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/21703
Unfortunately IAA is only tested in nightly.

IOAT has a similar problem: https://github.com/spdk/spdk/issues/3251
