### ISSUE TITLE
valgrind: m_libcfile.c:66 (vgPlain_safe_fd): Assertion 'newfd >= VG_(fd_hard_limit)' failed.

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#3165]
Looks like an issue with valgrind and the fd limits in our docker images.
```
00:05:48.408  ************************************
00:05:48.408  START TEST unittest_pci_event
00:05:48.408  ************************************
00:05:48.408   09:19:33	-- common/autotest_common.sh@1077 -- # valgrind --leak-check=full --error-exitcode=2 --verbose /var/jenkins/workspace/unittest-valgrind-docker-autotest/spdk/test/unit/lib/env_dpdk/pci_event.c/pci_event_ut
00:05:48.408  
00:05:48.408  valgrind: m_libcfile.c:66 (vgPlain_safe_fd): Assertion 'newfd >= VG_(fd_hard_limit)' failed.
00:05:48.408  /var/jenkins/workspace/unittest-valgrind-docker-autotest/spdk/test/common/autotest_common.sh: line 1055: 59979 Segmentation fault      (core dumped) "$@"
00:05:48.408    09:19:34	-- common/autotest_common.sh@1077 -- # trap - ERR
00:05:48.408    09:19:34	-- common/autotest_common.sh@1077 -- # print_backtrace
00:05:48.408    09:19:34	-- common/autotest_common.sh@1105 -- # [[ ehxBET =~ e ]]
00:05:48.408    09:19:34	-- common/autotest_common.sh@1107 -- # args=('/var/jenkins/workspace/unittest-valgrind-docker-autotest/spdk/test/unit/lib/env_dpdk/pci_event.c/pci_event_ut' '--verbose' '--error-exitcode=2' '--leak-check=full' 'valgrind' 'unittest_pci_event')
00:05:48.408    09:19:34	-- common/autotest_common.sh@1107 -- # local args
00:05:48.408    09:19:34	-- common/autotest_common.sh@1109 -- # xtrace_disable
00:05:48.408    09:19:34	-- common/autotest_common.sh@10 -- # set +x
```
According to the [bug report](https://bugs.kde.org/show_bug.cgi?id=465435) on valgrind's bugzilla, it's probably related to the limit set by docker and lowering should help.

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/111482/archive/unittest-valgrind-docker-autotest_6739/build.log
https://ci.spdk.io/public_build/autotest-per-patch_111482.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_111482.html

**Comment by mikeBashStuff** [comment]
There's already a patch awaiting review on the CI side (similar issue, under newer valgrind where proper debug msg is implemented, hit staging).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_111524.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_111538.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_111615.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_111604.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_111591.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_111623.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_111729.html
