### ISSUE TITLE
nvmf_create_transport - I/O unit size validation against 0

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3167]
# Sighting report

The following RPC crashes the NVMe-oF target:
./scripts/rpc.py nvmf_create_transport -t TCP -u 0

## Expected Behavior

Error should be reported, that the I/O unit size value is incorrect

## Current Behavior

NVMe-oF target application crashes

**Comment by tomzawadzki** [comment]
[Bug scrub] This does sound like a bug, as such value does not make much sense. It should be verified on the NVMe-oF target configuration, probably around the same place where max io size is checked too.
