### ISSUE TITLE
nvmf_create_transport - max I/O size validation against 0

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3168]
# Sighting report

The following RPC crashes the NVMe-oF target:
./scripts/rpc.py nvmf_create_transport -t TCP -i 0

## Expected Behavior

Error should be reported, that the max I/O size value is incorrect

## Current Behavior

NVMe-oF target application crashes

**Comment by tomzawadzki** [comment]
[Bug scrub] Let's combine it with https://github.com/spdk/spdk/issues/3167
