### ISSUE TITLE
nvmf_create_transport - num shared buffers validation against 0

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3169]
# Sighting report

The following RPC returns an incorrect error message:
./scripts/rpc.py nvmf_create_transport -t TCP -n 0

## Expected Behavior

The NVMe-oF target application should report an error message saying, that the number of pooled data buffers available to the transport cannot be equal to 0

## Current Behavior

The current error message says:
[2023-10-04 08:52:47.504531] iobuf.c: 251:spdk_iobuf_channel_init: *ERROR*: Couldn't find iobuf module: 'spdk_nvmf_TCP_data'

**Comment by tomzawadzki** [comment]
I don't think that `--num_shared_buffers` set to 0 should pose an issue. This basically means that pollers won't have preallocated per pollgroup cache from io_buffs. `spdk_iobuf_get()` should still get new buffers from global pool.

I wasn't able to reproduce the error you are seeing, nor see how it would be related to the `--num_shared_bufers`. Can you please post full scenario which resulted in the error you are seeing above ?

**Comment by tomzawadzki** [comment]
[Bug scrub] `num_shared_buffers` set to 0 should be supported, even if this is not the most optimal configuration. Could you describe bit more how you got the error message from the first post ?
