### ISSUE TITLE
nvmf_subsystem_add_listener - port number validation against "-0"

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3170]
# Sighting report

The following RPC does not report any error:
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode3 -t tcp -a 127.0.0.1 -s -0

## Expected Behavior

The port value "-0" should be rejected as an invalid value.

## Current Behavior

The above RPC passes without error, and then nvme_tcp_qpair_connect_sock returns an error, when creating an admin queue pair.

**Comment by tomzawadzki** [comment]
[Bug scrub] This definitely should be rejected, similar to any value that does not match a possible port number.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/20527

There are three patches there - one for nvmf/tcp (this issue), others for nvmf/rdma and iscsi.
