### ISSUE TITLE
nvmf_subsystem_add_listener - port number validation against 0

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3171]
# Sighting report

The following RPC does not report any error:
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode3 -t tcp -a 127.0.0.1 -s 0

## Expected Behavior

The port value 0 should be rejected as an invalid value.

## Current Behavior

The above RPC passes without error, and then nvme_tcp_qpair_connect_sock returns an error, when creating an admin queue pair.

**Comment by tomzawadzki** [comment]
For TCP listening (or specifically `bind()`) on port `0`, just reserves any ephemeral port available. I don't think this is behaviour of other transports.
Technically it should work, so I'd be curious what error you are getting, assuming you've provided that generated ephemeral port.

Yet I'm not sure this behaviour is useful and should be dependent upon.

**Comment by tomzawadzki** [comment]
[Bug scrub] Let's avoid allowing trsvcid set to 0 on NVMe-oF layer (not specific transports), as that type of behaviour is not really useful for NVMe-oF use cases.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/20527

There are three patches there - one for nvmf/tcp (this issue), others for nvmf/rdma and iscsi.
