### ISSUE TITLE
bdev_malloc_create - total_size and block_size validation against 0

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3172]
# Sighting report

The following RPC causes an rpc.py crash, instead of a graceful error message:
./scripts/rpc.py bdev_malloc_create -b Malloc1 0 0

## Expected Behavior

An error message should be displayed.

## Current Behavior

rpc.py crashes with no meaningful message.

**Comment by tomzawadzki** [comment]
> rpc.py crashes with no meaningful message.

Do you mean ?:
```
Traceback (most recent call last):
  File "/home/tzawadzk/spdk/./scripts/rpc.py", line 3628, in <module>
    call_rpc_func(args)
  File "/home/tzawadzk/spdk/./scripts/rpc.py", line 3507, in call_rpc_func
    args.func(args)
  File "/home/tzawadzk/spdk/./scripts/rpc.py", line 384, in bdev_malloc_create
    num_blocks = (args.total_size * 1024 * 1024) // args.block_size
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~
ZeroDivisionError: float floor division by zero
```

This applies to several instances
```
[tzawadzk@wisla spdk]$ git grep -n "num_blocks = " scripts python/
python/spdk/spdkcli/ui_node.py:347:        num_blocks = size * 1024 * 1024 // block_size
scripts/rpc.py:384:        num_blocks = (args.total_size * 1024 * 1024) // args.block_size
scripts/rpc.py:425:        num_blocks = (args.total_size * 1024 * 1024) // args.block_size
scripts/rpc.py:3410:        num_blocks = (args.total_size * 1024 * 1024) // args.block_size
```

We don't do much error reporting for such cases in rpc.py, usually generating the JSONs and passing it to the socket. If you feel strongly that error print would be more useful than output above, then args.block_size could be checked for 0.

**Comment by tomzawadzki** [comment]
[Bug scrub] `ZeroDivisionError: float floor division by zero` for block_size on calling the rpc.py should be clear enough to the user. Optionally a try catch could be done for similar instances, but both types of error logs seem clear enough. 
@slawekptak Are you interested in pursuing such change further or are you okay with leaving the traceback ?

**Comment by tomzawadzki** [comment]
[Bug scrub] @slawekptak Let's close this issue for now. If you feel there are some specific changes to make here, please re-open.
