### ISSUE TITLE
dsa_scan_accel_module - double RPC call causes application crash

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3174]
# Sighting report

The following RPC commands cause the application crash (tested on accel_perf):
 ./scripts/rpc.py  dsa_scan_accel_module
 ./scripts/rpc.py  dsa_scan_accel_module

## Expected Behavior

The second and subsequent calls of the dsa_scan_accel_module RPC should return a 'already scanned' or similar status.

## Current Behavior

Application crash (tested on accel_perf)

**Comment by tomzawadzki** [comment]
It's always useful to include bit more information, especially backtraces on crashes.

In this case it boils down to `spdk_accel_module_list_add()` not allowing to register the same module twice and asserting on debug builds. On release build, the module would not register again and just return. This applies to all accel modules, not just DSA.

All accel modules should keep track of their initialization state and not call into `spdk_accel_module_list_add()`. This is especially important in cases like DSA where besides adding to module list, other initialization steps should not execute as well.
In those cases `EALREADY` should be propagated to the calling RPC.

**Comment by tomzawadzki** [comment]
Fix in review https://review.spdk.io/gerrit/c/spdk/spdk/+/20786/

**Comment by tomzawadzki** [comment]
Fixes for IAA and DSA were merged in following series: https://review.spdk.io/gerrit/c/spdk/spdk/+/20786.
