### ISSUE TITLE
accel_get_module_info lists wrong supported opcodes for dpdk_compressdev

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3176]
# Sighting report

accel_get_module_info rpc lists wrong supported opcodes for dpdk_compressdev
Listed opcodes for this accel module should be `compress, decompress`, but `copy, fill` are reported.

## Steps to Reproduce

1. sudo build/bin/spdk_tgt --wait-for-rpc &
2. sudo scripts/rpc.py compressdev_scan_accel_module --pmd 0
3. sudo scripts/rpc.py framework_start_init 
```
accel_dpdk_compressdev.c: 296:accel_init_compress_drivers: *NOTICE*: initialized QAT PMD
```
4. sudo scripts/rpc.py accel_get_module_info
```
$ sudo scripts/rpc.py accel_get_module_info
[
  {
    "module": "software",
    "supported ops": [
      "copy",
      "fill",
      "dualcast",
      "compare",
      "crc32c",
      "copy_crc32c",
      "compress",
      "decompress",
      "encrypt",
      "decrypt",
      "xor"
    ]
  },
  {
    "module": "dpdk_compressdev",
    "supported ops": [
      "copy",
      "fill"
    ]
  }
]
```
5. accel_get_opc_assignments reports assigned opcodes correctly regardless of accel_get_module_info  output.
```
$ sudo scripts/rpc.py accel_get_opc_assignments
{
  "copy": "software",
  "fill": "software",
  "dualcast": "software",
  "compare": "software",
  "crc32c": "software",
  "copy_crc32c": "software",
  "compress": "dpdk_compressdev",
  "decompress": "dpdk_compressdev",
  "encrypt": "software",
  "decrypt": "software",
  "xor": "software"
}
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 986fb7b3ef33fe066da9bc9cb91d86f8db4da0b1

**Comment by jimharris** [comment]
Yeah, this is a general bug affecting all accel modules.

Can you try: https://review.spdk.io/gerrit/c/spdk/spdk/+/20512
