### ISSUE TITLE
 error: create_bdev failed: code": -32601, "Method not found

### ISSUE THREAD

**Issue by sarwanjassi** [spdk/spdk#3180]
# Sighting report

Started Listener using: python3 -m control

creating bdev using the command

python3 -m control.cli create_bdev -i demo_image -p rbd -b Ceph0

and getting this error:

INFO:control.grpc:Allocating cluster name='cluster_context_0'
ERROR:control.grpc:create_bdev failed with:
 request:
{
  "name": "cluster_context_0",
  "method": "bdev_rbd_register_cluster",
  "req_id": 2
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"

## Expected Behavior

it should create bdev as i am using local ceph cluster

## Current Behavior

  "code": -32601,
  "message": "Method not found"

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

sudo python3 -m control
INFO:root:Using configuration file ceph-nvmeof.conf
INFO:root:====================================== Configuration file content ======================================
INFO:root:#
INFO:root:#  Copyright (c) 2021 International Business Machines
INFO:root:#  All rights reserved.
INFO:root:#
INFO:root:#  SPDX-License-Identifier: LGPL-3.0-or-later
INFO:root:#
INFO:root:#  Authors: anita.shekar@ibm.com, sandy.kaur@ibm.com
INFO:root:#
INFO:root:
INFO:root:[gateway]
INFO:root:name =
INFO:root:group =
INFO:root:addr = 0.0.0.0
INFO:root:port = 5500
INFO:root:enable_auth = False
INFO:root:state_update_notify = True
INFO:root:state_update_interval_sec = 5
INFO:root:#min_controller_id = 1
INFO:root:#max_controller_id = 65519
INFO:root:enable_spdk_discovery_controller = True
INFO:root:
INFO:root:[discovery]
INFO:root:addr = 0.0.0.0
INFO:root:port = 8009
INFO:root:debug = 20
INFO:root:
INFO:root:[ceph]
INFO:root:pool = rbd
INFO:root:config_file = /etc/ceph/ceph.conf
INFO:root:id =
INFO:root:
INFO:root:[mtls]
INFO:root:server_key = ./etc/ceph/ceph.pub
INFO:root:client_key = ./etc/ceph/ceph.client.admin.keyring
INFO:root:#server_cert = ./server.crt
INFO:root:#client_cert = ./client.crt
INFO:root:
INFO:root:[spdk]
INFO:root:tgt_path = /usr/local/bin/nvmf_tgt
INFO:root:#rpc_socket_dir = /var/tmp/
INFO:root:#rpc_socket_name = spdk.sock
INFO:root:#tgt_cmd_extra_args = --env-context="--no-huge -m1024" --iova-mode=va
INFO:root:timeout = 60.0
INFO:root:log_level = WARN
INFO:root:
INFO:root:# Example value: -m 0x3 -L all
INFO:root:# tgt_cmd_extra_args =
INFO:root:
INFO:root:# transports = tcp
INFO:root:
INFO:root:# Example value: {"max_queue_depth" : 16, "max_io_size" : 4194304, "io_unit_size" : 1048576, "zcopy" : false}
INFO:root:transport_tcp_options = {"in_capsule_data_size" : 8192, "max_io_qpairs_per_ctrlr" : 7}
INFO:root:========================================================================================================
INFO:control.server:Starting gateway dcmir25ds21-01
DEBUG:control.server:Starting serve
INFO:control.state:Connected to Ceph with version "18.2.0 (5dd24139a1eada541a3bc16b6941c5dde975e26d) reef (stable)"
INFO:control.state:nvmeof.state omap object already exists.
DEBUG:control.server:Configuring server dcmir25ds21-01
INFO:control.server:SPDK Target Path: /usr/local/bin/nvmf_tgt
INFO:control.server:SPDK Socket: /var/run/ceph/8faf6af8-7b1f-11ee-93f1-fd60690dd255/spdk.sock
INFO:control.server:Starting /usr/local/bin/nvmf_tgt -u -r /var/run/ceph/8faf6af8-7b1f-11ee-93f1-fd60690dd255/spdk.sock
INFO:control.server:SPDK process id: 1508938
INFO:control.server:Attempting to initialize SPDK: rpc_socket: /var/run/ceph/8faf6af8-7b1f-11ee-93f1-fd60690dd255/spdk.sock, conn_retries: 300, timeout: 60.0
INFO: Setting log level to WARN
INFO:JSONRPCClient(/var/run/ceph/8faf6af8-7b1f-11ee-93f1-fd60690dd255/spdk.sock):Setting log level to WARN
[2023-11-06 06:48:22.443303] Starting SPDK v24.01-pre git sha1 17fdb2351 / DPDK 23.07.0 initialization...
[2023-11-06 06:48:22.443469] [ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --no-pci --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1508938 ]
EAL: No free 2048 kB hugepages reported on node 1
[2023-11-06 06:48:22.469358] app.c: 794:spdk_app_start: *NOTICE*: Total cores available: 1
[2023-11-06 06:48:22.547109] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
DEBUG:control.server:create_transport: tcp options: {"in_capsule_data_size" : 8192, "max_io_qpairs_per_ctrlr" : 7}
[2023-11-06 06:48:22.839217] tcp.c: 656:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
INFO:control.server:Using SPDK discovery service

**Comment by jimharris** [comment]
Hi @sarwanjassi,

Please confirm that you have built SPDK with Ceph RBD support:

```./configure --with-rbd```

Thanks,

Jim
