### ISSUE TITLE
Failing to bind to VFIO PCI on AWS Graviton3

### ISSUE THREAD

**Issue by Glitch18** [spdk/spdk#3181]
# Sighting report

When trying to test SPDK on my AWS Gravtion3 systems, I'm unable to bind my SSD to the VFIO driver, thus not being able to run the performance tests.

## Expected Behavior

After using the setup.sh script, the given SSD is bound successfully to the driver and the performance tests complete successfully.

## Current Behavior

When using the following setup.sh command before running the performace tests, I run into the following error

```
$: sudo DRIVER_OVERRIDE=vfio-pci PCI_ALLOWED="0000:00:1f.0" HUGEMEM=4096 ./scripts/setup.sh
0000:00:04.0 (1d0f 8061): Skipping denied controller at 0000:00:04.0
0000:00:04.0 (1d0f 8061): Active devices: mount@nvme1n1:nvme1n1p1,mount@nvme1n1:nvme1n1p15, so not binding PCI dev
0000:00:1f.0 (1d0f 8061): nvme -> vfio-pci
0000:00:1f.0 (1d0f 8061): failed to bind to vfio-pci, aborting
INFO: Requested 2048 hugepages but 2048 already allocated on node0
"ubuntu" user memlock limit: 971 MB

This is the maximum amount of memory you will be
able to use with DPDK and VFIO if run as user "ubuntu".
To change this, please adjust limits.conf memlock limit for user "ubuntu".
```

It fails to bind to vfio-pci

After this when I try
`build/examples/perf -q 32 -s 4096 -w randread -t 10 -o 1024 > results.txt` I get

```
[2023-11-07 07:27:33.799891] pci_event.c:  53:spdk_pci_event_listen: *ERROR*: Socket recv buffer is too small (< 1048576), see SO_RCVBUF section in socket(7) man page for specifics on how to adjust the system setting.No valid NVMe controllers or AIO or URING devices found
```

## Steps to Reproduce

I'm following these steps when I run into the issue

1. `sudo modprobe vfio-pci`
2. `sudo DRIVER_OVERRIDE=vfio-pci PCI_ALLOWED="0000:00:1f.0" HUGEMEM=4096 ./scripts/setup.sh`

The above commands gives the following output:

## Context (Environment including OS version, SPDK version, etc.)

I'm on a `c7g.xlarge` AWS server with an additional 8 GB gp2 SSD attached. Running ubuntu. 

SSD Details:

```
$: ~/spdk-2$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0          7:0    0  21.3M  1 loop /snap/amazon-ssm-agent/7529
loop1          7:1    0  21.6M  1 loop /snap/amazon-ssm-agent/7629
loop2          7:2    0  49.1M  1 loop /snap/core18/2794
loop3          7:3    0  59.3M  1 loop /snap/core20/2019
loop4          7:4    0 109.6M  1 loop /snap/lxd/24326
loop5          7:5    0  35.5M  1 loop /snap/snapd/20102
loop6          7:6    0  35.5M  1 loop /snap/snapd/20298
loop7          7:7    0  49.1M  1 loop /snap/core18/2800
nvme0n1      259:0    0     8G  0 disk
nvme1n1      259:1    0    20G  0 disk
├─nvme1n1p1  259:2    0  19.9G  0 part /
└─nvme1n1p15 259:3    0    99M  0 part /boot/efi
```
```
$: lspci
00:00.0 Host bridge: Amazon.com, Inc. Device 0200
00:01.0 Serial controller: Amazon.com, Inc. Device 8250
00:04.0 Non-Volatile memory controller: Amazon.com, Inc. NVMe EBS Controller
00:05.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
00:1f.0 Non-Volatile memory controller: Amazon.com, Inc. NVMe EBS Controller
```

So the address we want is 0000:00:1f.0

**Comment by mikeBashStuff** [comment]
Kernel log would be useful to determine why the bind to `vfio-pci` failed (since `setup.sh` won't tell us that on its own, it will just complain that write to the sysfs attr failed). :)

**Comment by Glitch18** [comment]
I'm seeing the following in the kernel log. Let me know if I should post more of the kernel log or look for something else in there

```
[   83.879249] VFIO - User Level meta-driver version: 0.3
[   83.978371] vfio-pci: probe of 0000:00:1f.0 failed with error -22
[10247.723801] perf: interrupt took too long (8065 > 8035), lowering kernel.perf_event_max_sample_rate to 24750
[10247.725312] perf: interrupt took too long (10094 > 10081), lowering kernel.perf_event_max_sample_rate to 19750
[10247.737114] perf: interrupt took too long (12641 > 12617), lowering kernel.perf_event_max_sample_rate to 15750
[10247.785623] perf: interrupt took too long (15823 > 15801), lowering kernel.perf_event_max_sample_rate to 12500
[10247.953282] perf: interrupt took too long (20071 > 19778), lowering kernel.perf_event_max_sample_rate to 9750
[11218.967603] vfio-pci: probe of 0000:00:1f.0 failed with error -22
[11796.363611] nvme nvme0: pci function 0000:00:1f.0
[11796.369457] nvme nvme0: 2/0/0 default/read/poll queues
[63607.075608] loop7: detected capacity change from 0 to 100592
[435578.255389] vfio-pci: probe of 0000:00:1f.0 failed with error -22
[546358.444225] nvme nvme0: pci function 0000:00:1f.0
[546358.449078] nvme nvme0: 2/0/0 default/read/poll queues
[546362.717964] vfio-pci: probe of 0000:00:1f.0 failed with error -22
```

**Comment by jimharris** [comment]
does it work if you omit the DRIVER_OVERRIDE?

setup.sh will pick the appropriate driver based on the environment - specifically checking if an IOMMU is enabled

so if an IOMMU is not enabled, and you try to use vfio-pci, you will hit errors like this

**Comment by Glitch18** [comment]
Okay I tried it without the DRIVER_OVERRIDE as follows:

```
$: sudo PCI_ALLOWED="0000:00:1f.0" HUGEMEM=4096 ./scripts/setup.sh

0000:00:04.0 (1d0f 8061): Skipping denied controller at 0000:00:04.0
0000:00:04.0 (1d0f 8061): Active devices: mount@nvme1n1:nvme1n1p1,mount@nvme1n1:nvme1n1p15, so not binding PCI dev
No valid drivers found [vfio-pci, uio_pci_generic, igb_uio]. Please enable one of the kernel modules.
```

**Comment by jimharris** [comment]
> Okay I tried it without the DRIVER_OVERRIDE as follows:
> 
> ```
> $: sudo PCI_ALLOWED="0000:00:1f.0" HUGEMEM=4096 ./scripts/setup.sh
> 
> 0000:00:04.0 (1d0f 8061): Skipping denied controller at 0000:00:04.0
> 0000:00:04.0 (1d0f 8061): Active devices: mount@nvme1n1:nvme1n1p1,mount@nvme1n1:nvme1n1p15, so not binding PCI dev
> No valid drivers found [vfio-pci, uio_pci_generic, igb_uio]. Please enable one of the kernel modules.
> ```

It is probably not finding vfio-pci because it needs to be loaded first. It looked like you explicitly modprobe'd vfio-pci in one of your earlier posts here. But we don't really want to use vfio-pci so let's not worry about that for now.

I think your issue is similar to #210. Please see if there are linux-image-extra packages available for your system, if so, they should include the uio_pci_generic module. Please make sure you modprobe the driver then re-run setup.sh without the DRIVER_OVERRIDE.

**Comment by jimharris** [comment]
HI @Glitch18, any update?

**Comment by jimharris** [comment]
Closing, please respond here if the suggestions above did not work.
