### ISSUE TITLE
[autobuild_ocf_precompile] Timeout when building ocf

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#3182]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/111959/archive/unittest-main-docker-autotest_7179/build.log
## Execution failed at

00:11:22.861    CC env_ocf/src/ocf/ocf_request.o
00:11:22.861    CC env_ocf/src/ocf/ocf_metadata.o
00:11:22.861    CC env_ocf/ocf_env.o
00:11:24.041  Cancelling nested steps due to timeout
00:11:24.055  Sending interrupt signal to process
00:11:24.298  Terminated
00:11:25.236  gcc: fatal error: Terminated signal terminated program cc1
00:11:25.236  compilation terminated.
00:11:25.236  make[1]: *** [/var/jenkins/workspace/unittest-main-docker-autotest/spdk/mk/spdk.common.mk:510: src/ocf/ocf_space.o] Error 1
00:11:25.236  make[1]: *** Waiting for unfinished jobs....
00:11:25.236  make: *** [Makefile:48: all] Error 2
00:11:25.236  make: Leaving directory '/var/jenkins/workspace/unittest-main-docker-autotest/spdk/lib/env_ocf'
00:11:25.236    08:11:51	-- common/autobuild_common.sh@23 -- # trap - ERR
00:11:25.236    08:11:51	-- common/autobuild_common.sh@23 -- # print_backtrace
00:11:25.236    08:11:51	-- common/autotest_common.sh@1106 -- # [[ ehxBET =~ e ]]
00:11:25.236    08:11:51	-- common/autotest_common.sh@1108 -- # args=('_ocf_precompile' 'autobuild_ocf_precompile')
00:11:25.236    08:11:51	-- common/autotest_common.sh@1108 -- # local args
00:11:25.236    08:11:51	-- common/autotest_common.sh@1110 -- # xtrace_disable
00:11:25.236    08:11:51	-- common/autotest_common.sh@10 -- # set +x
00:11:25.236  ========== Backtrace start: ==========
00:11:25.236  
00:11:25.236  in /var/jenkins/workspace/unittest-main-docker-autotest/spdk/test/common/autobuild_common.sh:23 -> _ocf_precompile([])
00:11:25.236       ...
00:11:25.236     18  		# We compile OCF sources ourselves
00:11:25.236     19  		# They don't need to be checked with scanbuild and code coverage is not applicable
00:11:25.236     20  		# So we precompile OCF now for further use as standalone static library
00:11:25.236     21  		"$rootdir/configure" $(echo $config_params | sed 's/--enable-coverage//g')
00:11:25.236     22  		$MAKE $MAKEFLAGS include/spdk/config.h
00:11:25.236  => 23  		CC=gcc CCAR=ar $MAKE $MAKEFLAGS -C "$rootdir/lib/env_ocf" exportlib O="$rootdir/ocf.a"
00:11:25.236     24  		# Set config to use precompiled library
00:11:25.236     25  		config_params="$config_params --with-ocf=/$rootdir/ocf.a"
00:11:25.237     26  		# need to reconfigure to avoid clearing ocf related files on future make clean.
00:11:25.237     27  		"$rootdir/configure" $config_params
00:11:25.237     28  	}
00:11:25.237       ...
00:11:25.237  in /var/jenkins/workspace/unittest-main-docker-autotest/spdk/test/common/autotest_common.sh:1078 -> run_test(["autobuild_ocf_precompile"],["_ocf_precompile"])
00:11:25.237       ...
00:11:25.237     1073		timing_enter $test_name
00:11:25.237     1074		echo "************************************"
00:11:25.237     1075		echo "START TEST $test_name"
00:11:25.237     1076		echo "************************************"
00:11:25.237     1077		xtrace_restore
00:11:25.237     1078		time "$@"
00:11:25.237     1079		xtrace_disable
00:11:25.237     1080		echo "************************************"
00:11:25.237     1081		echo "END TEST $test_name"
00:11:25.237     1082		echo "************************************"
00:11:25.237     1083		timing_exit $test_name
00:11:25.237       ...
00:11:25.237  in /var/jenkins/workspace/unittest-main-docker-autotest/spdk/test/common/autobuild_common.sh:429 -> ocf_precompile([])
00:11:25.237       ...
00:11:25.237     424 	scanbuild_make() {
00:11:25.237     425 		run_test "scanbuild_make" _scanbuild_make
00:11:25.237     426 	}
00:11:25.237     427 	
00:11:25.237     428 	ocf_precompile() {
00:11:25.237  => 429 		run_test "autobuild_ocf_precompile" _ocf_precompile
00:11:25.237     430 	}

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_111959.html

**Comment by mikeBashStuff** [comment]
Both affected jobs waited >10m for the container service to pop up. This happened most likely due to the fact that our swarm got overloaded as several workers were offline. Brought most of them back online so hopefully this issue won't resurface.

**Comment by tomzawadzki** [comment]
[Bug scrub] As @mikeBashStuff pointed out, the issue should be resolved by now. Feel free to report false positives to retrigger, otherwise the issue will be closed in next few days.

**Comment by tomzawadzki** [comment]
No further reports, closing.
