### ISSUE TITLE
Cannot contact GP14

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#3183]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/111966/archive/nvmf-phy-autotest_55410/build.log
## Execution failed at

00:12:02.228  [2023-11-07 10:04:43.620071] rdma.c: 679:nvmf_rdma_dump_request: *ERROR*: 		Request opcode: 1
00:12:02.228  [2023-11-07 10:04:43.620080] rdma.c: 677:nvmf_rdma_dump_request: *ERROR*: 		Request Data From Pool: 1
00:12:02.228  [2023-11-07 10:04:43.620090] rdma.c: 679:nvmf_rdma_dump_request: *ERROR*: 		Request opcode: 2
00:12:02.228  [2023-11-07 10:04:43.620099] rdma.c: 677:nvmf_rdma_dump_request: *ERROR*: 		Request Data From Pool: 1
00:12:02.228  [2023-11-07 10:04:43.620108] rdma.c: 679:nvmf_rdma_dump_request: *ERROR*: 		Request opcode: 2
00:12:22.483  Cannot contact GP14: java.lang.InterruptedException
00:16:55.189  [Pipeline] }
00:16:55.211  [Pipeline] // stage
00:16:55.219  [Pipeline] }
00:16:55.240  [Pipeline] // timeout
00:16:55.248  [Pipeline] }
00:16:55.252  ERROR: missing workspace /var/jenkins/workspace/nvmf-phy-autotest on GP14
00:16:55.269  [Pipeline] // catchError
00:16:55.276  [Pipeline] }
00:16:55.295  [Pipeline] // wrap
00:16:55.302  [Pipeline] }
00:16:55.317  [Pipeline] // catchError
00:16:55.338  [Pipeline] stage
00:16:55.340  [Pipeline] { (Epilogue)
00:16:55.355  [Pipeline] catchError
00:16:55.357  [Pipeline] {
00:16:55.372  [Pipeline] sh
00:16:56.404  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:16:56.404  /var/jenkins/workspace/nvmf-phy-autotest_tmp/durable-d81a30c3/script.sh: line 1: jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: No such file or directory
00:16:56.423  [Pipeline] }

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_111966.html
