### ISSUE TITLE
bdev_uring_create error on files and devices in /dev/disk/by-path

### ISSUE THREAD

**Issue by seingierf** [spdk/spdk#3185]
# Sighting report

The following error is displayed when attempting to call `bdev_uring_create` on a file:
```
bdev_uring.c: 530:bdev_uring_check_zoned_support: *ERROR*: Unable to open file bdev-file/queue/zoned. errno: 2
```

A similar message is shown when passing a device in `/dev/disk/by-path`:
```
bdev_uring.c: 530:bdev_uring_check_zoned_support: *ERROR*: Unable to open file /dev/disk/by-path/pci-0000:03:00.0-nvme-1/queue/zoned. errno: 2
```

## Expected Behavior

bdev_uring_create should succeed like aio does.

## Current Behavior

By default, SPDK is built with `SPDK_CONFIG_URING_ZNS` unless explicitly disabled using `--without-uring-zns`.
The above errors happen only if `URING_ZNS` is enabled.

## Possible Solution

The file issue could be solved by skipping the check for zoned namespaces in case the user attempts to create a bdev on a file.
Accessing devices `/dev/disk/by-path` could be simply a matter of following the symlink.

This would allow building with zoned namespaces while maintaining compatibility with files.
The reason for using paths in `/dev/disk/by-path` is that it is easier to identify a disk by its physical location and seems safer compared to `/dev/nvmeX` devices.

Possible implementation:
```
diff --git a/module/bdev/uring/bdev_uring.c b/module/bdev/uring/bdev_uring.c
index c000e7b75..458778eef 100644
--- a/module/bdev/uring/bdev_uring.c
+++ b/module/bdev/uring/bdev_uring.c
@@ -525,6 +525,18 @@ bdev_uring_check_zoned_support(struct bdev_uring *uring, const char *name, const
 
        uring->bdev.zoned = false;
 
+       /* Perform check on block devices only */
+       struct stat sb;
+       if (stat(filename, &sb) == 0 && (sb.st_mode & S_IFMT) != S_IFBLK) {
+               return 0;
+       }
+
+       /* Follow symlink */
+       char resolved_path[PATH_MAX], *rp;
+       if ((rp = realpath(filename, resolved_path))) {
+               filename = rp;
+       }
+
        /* Check if this is a zoned block device */
        if (bdev_uring_read_sysfs_attr(filename, "queue/zoned", str, sizeof(str))) {
                SPDK_ERRLOG("Unable to open file %s/queue/zoned. errno: %d\n", filename, errno);
```

## Steps to Reproduce

Shell 1:
```
spdk_tgt --iova-mode va --env-context --in-memory
```

Shell 2:
```
dd if=/dev/zero bs=4096 count=1024 of=bdev-file
rpc.py bdev_uring_create bdev-file bdev0 4096
rpc.py bdev_uring_create /dev/disk/by-path/pci-0000:03:00.0-nvme-1 bdev0
```

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 22.04, SPDK master (e57869c0088a67c4d994f37b808b141d79c3a7c9)

**Comment by jimharris** [comment]
Thanks for the detailed bug report and suggested fix.

Would you like to submit this patch? Or are you OK if someone else picks up your patch and gets it submitted?

See https://spdk.io/development for how to push patches to the SPDK Gerrit instance for review.

-Jim

**Comment by seingierf** [comment]
I'll give a try to Gerrit but I'm also perfectly fine if someone else picks the patch!
