### ISSUE TITLE
No information on multiprocessing in the documentation

### ISSUE THREAD

**Issue by m-kru** [spdk/spdk#3187]
In the SPDK API documentation user can read in multiple places that it is the user's responsibility to guarantee proper synchronization in the case of multithreading. For example, here is a snippet of doc from the `spdk_nvme_ns_cmd_write()`:
![image](https://github.com/spdk/spdk/assets/26227737/acaa9211-9f4d-4a35-81d5-ff41c85dab11)
However, there is no information (or at least I have not found any) on what is allowed in case of multiprocessing. For example, can I run multiple instances of the same program simultaneously as long as each application writes distinct LBA ranges?

**Comment by jimharris** [comment]
SPDK doesn't impose any restrictions on accessing the same LBA from multiple IO qpairs (either within the same application or across multiple applications).

The text here means that you cannot have multiple threads submitting IO to the same qpair at the same time. You also cannot submit IO to a qpair on one thread and check for completions on that qpair from another thread. If you want to use the same qpair from multiple threads, you must do your own synchronization.

**Comment by m-kru** [comment]
@jimharris the problem with multiprocessing is completely different.

```
nvme attaching to 0000:06:00.0
[2023-11-14 14:33:35.227310] pci.c:1043:spdk_pci_device_claim: *ERROR*: Cannot create lock on device /var/tmp/spdk_pci_lock_0000:06:00.0, probably process 8534 has claimed it
[2023-11-14 14:33:35.227358] nvme_pcie.c: 896:nvme_pcie_ctrlr_construct: *ERROR*: could not claim device 0000:06:00.0 (Permission denied)
[2023-11-14 14:33:35.227385] nvme.c: 677:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:06:00.0
EAL: Requested device 0000:06:00.0 cannot be used
Segmentation fault (core dumped)
```
If I understand correctly multiprocessing using the SPDK and utilizing the same disk is impossible, as you cannot attach to the same disk from multiple processes.

**Comment by jimharris** [comment]
You must enable multi-process mode to share the SSD between processes.  This is done by specifying an shm_id in your spdk_env_opts, the same shm_id in each process.

Each process can perform admin queue operations independently - the SPDK nvme driver will take care of synchronization with a process-shared mutex.  Each process can also allocate their own IO queues, but an IO queue must only be used in the application where it is allocated.
