### ISSUE TITLE
Memory corruption while using virtio disk

### ISSUE THREAD

**Issue by SWaoter** [spdk/spdk#3189]
# Sighting report

Running fio with verify on virtio disk that is shared with nvme transport results with failure.

## Expected Behavior

No fio verify error occurs.

## Current Behavior

Fio verify fails on some blocks.

## Possible Solution

Such corruption happens when `iov` that it submitted to `virtio` layer by `bdev_io` is splitted between two `hugemem` pages.
In fact, function that behaves wrongly is `virtqueue_req_add_iovs`:
`spdk_vtophys(iovs[i].iov_base, NULL)` does not check that all required memory was translated.
In order to correctly process such memory split we can change cycle of filling `vring` descriptors to something like this:

```
uint64_t processed_length, iovec_length, current_length;
void *current_base;
uint16_t used_desc_count = 0;

for (i = 0; i < iovcnt; ++i) {
    processed_length = 0;
    iovec_lenght = iovs[i].iov_len;
    current_base = iovs[i].iov_base;

    while (processed_length < iovec_length) {
        desc = &vq->vq_ring.desc[new_head];
        current_length = iovec_length - processed_length;

        if (!vq->vdev->is_hw) {
            desc->addr = (uintptr_t)current_base;
        } else {
            desc->addr = spdk_vtophys(current_base, &current_length);
        }

        desc->len = current_length;
        desc->flags = desc_type | VRING_DESC_F_NEXT;

        prev_head = new_head;
        new_head = desc->next;
        used_desc_count++;

        processed_length += current_length;
        current_base += current_length;
    }
}
```

and then
```
+    dxp->ndesc += used_desc_count;
-    dxp->ndesc += iovcnt;
```

```
+    vq->vq_free_cnt = (uint16_t)(vq->vq_free_cnt - used_desc_count);
-    vq->vq_free_cnt = (uint16_t)(vq->vq_free_cnt - iovcnt);
```

In order to make this fix works we have to somehow rework `virtqueue_req_start`.
It is needed because more than `iovcnt` entries may be added to the `virtqueue`.
Simplest solution is reserving enough entries to handle each `iov` split:
```
+ if (2 * iovcnt > vq->vq_free_cnt) {
- if (iovcnt > vq->vq_free_cnt) {
```
It does not look like an overkill, however it may impact when `iodepth` is big enough.

Another possible solution will be checking `vq->vq_free_cnt` inside loop in `virtqueue_add_iovs`. When we exceed free space rollback previously added iovs.

## Steps to Reproduce

Start SPDK:

1. sudo HUGEMEM=8192 ./scripts/setup.sh
2. sugo ./build/bin/spdk_tgt -m 0xf

Create Virtio disk and share it with NVME transport:

1. sudo ./rpc.py bdev_virtio_attach_controller --dev-type blk --trtype pci --traddr 0000:00:0e.0 VirtioBlk0
3. sudo ./rpc.py nvmf_create_transport -t TCP -z
4. sudo ./rpc.py nvmf_create_subsystem nqn.2018-09.io.spdk:cnode1 -s SPDK001 -a -r
5. sudo ./rpc.py nvmf_subsystem_add_ns nqn.2018-09.io.spdk:cnode1 VirtioBlk0
6. sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2018-09.io.spdk:cnode1 -t tcp -f ipv4 -a 127.0.0.1 -s 4420
7. sudo modprobe nvme-fabrics nvme-tcp
8. sudo nvme connect -t tcp -a 127.0.0.1 -s 4420 -n nqn.2018-09.io.spdk:cnode1

Run fio with verify. I've used following config:

```
[global]
ioengine=libaio
direct=1
group_reporting
exitall

bs=1M
rw=write
iodepth=32
size=30M
numjobs=1
verify=md5
loops=100

[job1]
newgroup

filename=/dev/nvme0n1
```

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 22.04, latest SPDK master

**Comment by jimharris** [comment]
Good find and analysis. Would you like to post your proposed patch to SPDK Gerrit? If you aren't familiar, check out https://spdk.io/development for details.

**Comment by SWaoter** [comment]
Sure, I will check out the guide and submit patch

**Comment by jimharris** [comment]
Thanks @swaoter! For those interested, patch is here: https://review.spdk.io/gerrit/c/spdk/spdk/+/20634.
