### ISSUE TITLE
Does the spdk iscsi module support exporting read-only target node （or LUN）?

### ISSUE THREAD

**Issue by xu-chaojie** [spdk/spdk#3192]
# Sighting report

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
Yes, you can create a read only block device and export via iSCSI to remote client, you can have a try with `bdev_aio_create` RPC to create RO device.

**Comment by xu-chaojie** [comment]
Thanks, I've found a solution to this problem, just close this issue.
