### ISSUE TITLE
Passing data between DPDK and SPDK without copying

### ISSUE THREAD

**Issue by m-kru** [spdk/spdk#3197]
I want to implement very simple application. I want to receive data from the network interface with the highest possible throughput and immediately dump it into the NVMe disk with the highest possible throughput.

However, if you read DPDK and SPDK documentation you will realize that both these  frameworks require users to allocate buffers using dedicated functions. For example, https://spdk.io/doc/memory.html says user must use `spdk_dma_malloc()` or its siblings. On the other hand, the DPDK requires the user to use [mbuf](https://doc.dpdk.org/guides/prog_guide/mbuf_lib.html) library for storing packet data. Coyping data between DPDK and SPDK requires extra time and resources. You can probably use DMA, but you still need to schedule the transfers what costs you extra CPU cycles and increases the initial latency.

Is there any recommended way to share data buffers between DPDK and SPDK?

**Comment by m-kru** [comment]
Ok, I think the documentation should be improved to indicate that this is possible. I understood

> all data buffers passed to SPDK must be allocated using [spdk_dma_malloc()](https://spdk.io/doc/env_8h.html#ac9b56bdbcfeeebe6ad61eb574c823268) or its siblings

very literally.

**Comment by tomzawadzki** [comment]
The patch improving documentation has been merged, https://github.com/spdk/spdk/commit/45229c77ebc88c10ab3eeb2e6165d461622a050f.

@m-kru Thank you for the question and pointing out the gap in docs. Is there anything else related to this issue or can it be closed ?
