### ISSUE TITLE
win10 can not start, when used vhost-blk

### ISSUE THREAD

**Issue by jialei-jialei** [spdk/spdk#3199]
# Sighting report
1.run spdk vhost 
build/bin/vhost -S /var/run -s 1024 -m 0x300000
2.crteate a malloc_bdev
./scripts/rpc.py bdev_malloc_create 64 512 -b Malloc0
3.create a vhost-blk ctrlr
./scripts/rpc.py vhost_create_blk_controller --cpumask 0x300000 vhost.0 Malloc0
4. add sock to a win10 vm
add /var/run/vhost.0 path to win10 libvirt xml
5.virsh start win10

Stuck here ever since starting Win10：
![image](https://github.com/spdk/spdk/assets/13553842/b156ca7d-c47f-421a-9af5-f2fb42f82ef6)

## Expected Behavior

start success

## Current Behavior

failed

## Possible Solution

Win10 is not compatible with vhost blk？linux is ok

## Steps to Reproduce

enable DEBUG log，has no errors
when start win10，has 5-6 io request to read offset:0 len:512

## Context (Environment including OS version, SPDK version, etc.)

qemu 6.2.0
sdpk 21.04
windows virtio：0.1.187

**Comment by changpe1** [comment]
@netjia-cpu which virtio driver do you use in Windows ?

**Comment by netjia-cpu** [comment]
> @netjia-cpu which virtio driver do you use in Windows ?

![image](https://github.com/spdk/spdk/assets/13553842/b6a810ba-12d2-4469-8559-22218d766e36)
0.1.187

**Comment by changpe1** [comment]
> > @netjia-cpu which virtio driver do you use in Windows ?
> 
> ![image](https://user-images.githubusercontent.com/13553842/285123446-b6a810ba-12d2-4469-8559-22218d766e36.png) 0.1.187

You may try to boot into windows first, and then use `device_add` QMP command to add vhost-blk device, or try redhat virtio windows driver.

**Comment by netjia-cpu** [comment]
> > > @netjia-cpu which virtio driver do you use in Windows ?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/13553842/285123446-b6a810ba-12d2-4469-8559-22218d766e36.png) 0.1.187
> 
> You may try to boot into windows first, and then use `device_add` QMP command to add vhost-blk device, or try redhat virtio windows driver.

run:
virsh attach-device vhost-blk.xml
after windows start
then, will has 
![c113f81a721a2d443bf04cdd8b0950e](https://github.com/spdk/spdk/assets/13553842/2e7dc771-3226-46cf-ab6f-65671d69fd50)
one is OS，the other is vhost-blk

but has no disk find on windows device manager

**Comment by netjia-cpu** [comment]
@changpe1 
not use multi-queue， the Windows run success！everything is ok

**Comment by tomzawadzki** [comment]
[Bug scrub] @changpe1 Do you think there is something to address in this issue with regards the need to disable multi-queue support ?

**Comment by changpe1** [comment]
> [Bug scrub] @changpe1 Do you think there is something to address in this issue with regards the need to disable multi-queue support ?

I think we can add the workaround note to SPDK document as known Windows limitations, https://github.com/virtio-win/kvm-guest-drivers-windows always contains the latest fix commits, but requires user's effort to have a try.
