### ISSUE TITLE
Should spdk_bdev_io be returned to the caller in spdk_bdev_cleanup_pending_rbuf_io()?

### ISSUE THREAD

**Issue by uchida2016** [spdk/spdk#32]
spdk_bdev_cleanup_pending_rbuf_io function removes spdk_bdev_io structures from g_need_rbuf_small list or g_need_rbuf_large list. Then anybody doesn't care about them and they don't go back to spdk_bdev_g_io_pool. I think these spdk_bdev_io should be returned to the caller.

**Comment by benlwalker** [comment]
This function has been removed and I think it's all fixed up. Thanks!
