### ISSUE TITLE
Hot-remove hangs SPDK process with SR-IOV enabled SSD

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3205]
Reproduction steps are easy, as long as you have an SR-IOV enabled SSD. Also make sure IOMMU is enabled, since you need to be using vfio-pci to reproduce.

1) Start spdk_tgt
2) scripts/rpc.py bdev_nvme_set_hotplug -e
3) echo 1 > /sys/bus/pci/devices/0000\:XX\:00.0/remove

Neither the echo nor spdk process can be killed.

Let's call the bullet #3 the "bash" process. The sysfs write triggers an eventfd_signal() (see which will be read by the DPDK interrupt thread. That kernel thread will block, waiting for userspace to release the vfio device. It is holding the underlying device lock while it waits. (See vfio_unregister_group_dev() and vfio_pci_core_request()).

So now the DPDK interrupt thread wakes up, and calls the SPDK hot plug callback. All it does is mark the internal device structure as removed.

Then the bdev nvme hotplug poller runs. First it processes any PCI hot plug events, it finds that the device is removed, and calls the user (bdev_nvme) remove_cb asynchronously. Note - it does *not* release the vfio device handle yet.  But then it also calls spdk_nvme_probe() with an empty address, meaning try to attach to any new device. This triggers a full PCI bus scan down in DPDK.

Part of the DPDK bus scan is figuring out if a device supports SR-IOV. It does this by reading the sysfs sriov_numvfs entry, if it exists. This is populated in the kernel by sriov_numvfs_show(), which also tries to acquire the device lock. Note at this point, the PCI device (and its sysfs entries) still exist - since vfio is still waiting on SPDK/DPDK to release the vfio device. So the DPDK PCI bus scan tries to read the just removed device's sriov_numvfs and deadlocks.

One workaround which so far passes my testing is to skip the spdk_pci_enumerate() if any removals were detected. This would give us one nvme hotplug poller period to complete the vfio removal notification before we try to scan the PCI bus again. But that's not foolproof - probably we need to actually keep track of the number of controllers we are waiting for the caller (i.e. bdev_nvme) to detach, and just keep skipping the spdk_pci_enumerate() until that reaches 0.

I'm also posting this to the pci and kvm/vfio kernel mailing lists - I'm not sure the implications of this sriov_numvfs was fully considered in the hot remove path.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/20987

**Comment by mhae** [comment]
@jimharris: FWIW, I've seen this behavior as well.

**Comment by jimharris** [comment]
SPDK workaround is merged, so closing this issue.

There is still work in progress to fix this in the kernel though.
