### ISSUE TITLE
Is there any way to quickly restart the SPDK process?

### ISSUE THREAD

**Issue by benqwu** [spdk/spdk#3209]
Currently, most of the initialization time is spent on the DPDK initializing hugepage stage. If 32GB huge pages are configured, it takes more than 7 seconds to complete the initialization.

**Comment by benqwu** [comment]
> There are two ways to do this, neither of which are particularly easy:
> 
> 1. Use multi-process DPDK feature. Have one process that is the primary process that _only_ does a static allocation of the required number of huge pages. It will also need to do all of the device attachment, since in DPDK only the primary process can attach devices. Then your real app that you want to be able to restart can be a secondary process. When it restarts, the memory does not need to be zeroed by the kernel because the primary process already has it mapped. See "shm_id" for how to specify an ID that designates the primary/secondary process relationships. There is also a stub application at test/app/stub that you can refer to.
> 2. I have not tried this, but there is kernel option CONFIG_INIT_ON_ALLOC_DEFAULT_ON. You can set this at kernel boot time (without recompiling kernel) by setting `init_on_alloc=0` on kernel command line. I looked briefly through the kernel code, this definitely affected allocations internally in the kernel, but not sure if it also affects allocations that will be exposed directly to userspace. It would be great if you could try this out and report back if it works or not.

Thank you for your suggestion. I checked the kernel configuration of the environment and found that CONFIG_INIT_ON_ALLOC_DEFAULT_ON is not set. Does this mean that this optimization has been included?

**Comment by jimharris** [comment]
> > There are two ways to do this, neither of which are particularly easy:
> > 
> > 1. Use multi-process DPDK feature. Have one process that is the primary process that _only_ does a static allocation of the required number of huge pages. It will also need to do all of the device attachment, since in DPDK only the primary process can attach devices. Then your real app that you want to be able to restart can be a secondary process. When it restarts, the memory does not need to be zeroed by the kernel because the primary process already has it mapped. See "shm_id" for how to specify an ID that designates the primary/secondary process relationships. There is also a stub application at test/app/stub that you can refer to.
> > 2. I have not tried this, but there is kernel option CONFIG_INIT_ON_ALLOC_DEFAULT_ON. You can set this at kernel boot time (without recompiling kernel) by setting `init_on_alloc=0` on kernel command line. I looked briefly through the kernel code, this definitely affected allocations internally in the kernel, but not sure if it also affects allocations that will be exposed directly to userspace. It would be great if you could try this out and report back if it works or not.
> 
> Thank you for your suggestion. I checked the kernel configuration of the environment and found that CONFIG_INIT_ON_ALLOC_DEFAULT_ON is not set. Does this mean that this optimization has been included?

If it is already turned off in your kernel configuration then #2 isn't an option.

It would be a dangerous path to take anyways, it would mean that pages mapped in userspace could have all kinds of interesting data in it from a previous user (kernel or other process).

**Comment by benqwu** [comment]
I tried the example of stub, using 32GB of huge page memory. It takes 3 seconds for the first stub process to initialize the huge page memory, while the second stub, using shm_id for initialization, only takes 0.2 seconds, which is very noticeable. When both processes are running, through the memory dump interface of dpdk, it is found that the memory is shared by the two processes, and the total memory usage is the sum of the memory usage of the two processes. I also found an issue: if a certain stub process is killed directly, another stub process, when performing memory statistics through the dpdk memory dump interface, detects a memory leak problem. If the process is terminated by sending a SIGTERM signal, the memory used by the process will be cleared. I have a question: if one of the processes exits in an abnormal way, such as through a coredump, how should the other processes reclaim the related memory?

**Comment by jimharris** [comment]
> I tried the example of stub, using 32GB of huge page memory. It takes 3 seconds for the first stub process to initialize the huge page memory, while the second stub, using shm_id for initialization, only takes 0.2 seconds, which is very noticeable. When both processes are running, through the memory dump interface of dpdk, it is found that the memory is shared by the two processes, and the total memory usage is the sum of the memory usage of the two processes. I also found an issue: if a certain stub process is killed directly, another stub process, when performing memory statistics through the dpdk memory dump interface, detects a memory leak problem. If the process is terminated by sending a SIGTERM signal, the memory used by the process will be cleared. I have a question: if one of the processes exits in an abnormal way, such as through a coredump, how should the other processes reclaim the related memory? @jimharris

When you say "is killed directly" - do you mean SIGKILL?

If process terminates unexpectedly, SPDK nvme driver running in other processes will do its best to detect the crashed process and cleanup memory. But you should be careful relying on this as a safe mechanism. If process crashed, it may have also corrupted some memory, which other processes cannot detect.  See code such as nvme_ctrlr_remove_inactive_proc().

**Comment by jimharris** [comment]
Closing issue, if you have follow-up questions feel free to still ask them here.
