### ISSUE TITLE
[vfio-user] failed to translate IOVA to local VA

### ISSUE THREAD

**Issue by yanbozyb** [spdk/spdk#3217]
Hi SPDK team,

I measure NVMe virtualization with vfio-user & nvme-of, but it shows the following issues:

`
vfio_user.c: 734:map_one: *ERROR*: failed to translate IOVA [3221078016, 3221082112) (prot=3) to local VA: No such file or directory
`

Below is my configuration and software version
1. Software:
    - SPDK release v23.09
    - qemu: qemu-orcl branch: vfio-user-p3.1 (as this https://github.com/nutanix/libvfio-user/blob/master/docs/spdk.md)
3. Hardware:
    - use UIO instead of VFIO
    - Host: Ubuntu kernel 6.1.8
    - Guest: Ubuntu kernel 5.4.0
4. Build Configuration:
    - I use same steps as described in libvfio-user guide: https://github.com/nutanix/libvfio-user/blob/master/docs/spdk.md
    - use Malloc bdev to emulate NVMe controller.

It doesn't have any influence on my measurement for Malloc bdev emulated NVMe controller. It seems like it tries to translate guest GVA to host HVA, but it doesn't find this memory map. I am not sure whether this is because  I use UIO for SPDK instead of VFIO? But from my mind, SPDK will translate memory address map using software instead of IOMMU if VFIO is disabled. 

Thanks

**Comment by yanbozyb** [comment]
BTW, SPDK release v23.05 doesn't show this issue.

**Comment by jimharris** [comment]
> BTW, SPDK release v23.05 doesn't show this issue.

Hi @yanbozyb, could you do a git bisect to see which SPDK commit introduces this issue?

**Comment by yanbozyb** [comment]
@jimharris It's hard to find that. Anyway, please leave this issue there. Let me fix it later. I haven't submitted patches to SPDK so many years.

**Comment by jimharris** [comment]
> @jimharris It's hard to find that. Anyway, please leave this issue there. Let me fix it later. I haven't submitted patches to SPDK so many years.

git bisect says there would be 8 steps needed (meaning you'd need to rebuild and retest 8 times) - does it take a long time on your system to rebuild and test?

**Comment by yanbozyb** [comment]
@jimharris I find that. It's funny because this is just a commit for adding more logs. So this issue already exits in all previous releases. 

Commit that introduces that issue output:
https://github.com/spdk/spdk/commit/3552b7e7e1c026a59ca602b35dc85d4f436ceed0

**Comment by jimharris** [comment]
> @jimharris I find that. It's funny because this is just a commit for adding more logs. So this issue already exits in all previous releases.
> 
> Commit that introduces that issue output: [3552b7e](https://github.com/spdk/spdk/commit/3552b7e7e1c026a59ca602b35dc85d4f436ceed0)

Thanks @yanbozyb. Tagging @changpe1 @jlevon @tmakatos to get their input.

**Comment by jlevon** [comment]
we'd probably need a full debug log from libvfio-user that shows the mappings coming and going.
Does it happen all the time, or just once? And when does it happen (e.g. on reconnect, reset, etc)

**Comment by yanbozyb** [comment]
@jlevon It happens just once when I launch QEMU and connect to the socket.

**Comment by changpe1** [comment]
Thanks @yanbozyb .

This failed memory region is 4KiB length, this is not a normal memory region in practice, I think this may be related with qemu, BTW do you see any exceptions in VM?

**Comment by yanbozyb** [comment]
QEMU and VM didn't show any exceptions though. FIO works well in guest OS.

**Comment by yanbozyb** [comment]
> Thanks @yanbozyb .
> 
> This failed memory region is 4KiB length, this is not a normal memory region in practice, I think this may be related with qemu, BTW do you see any exceptions in VM?

Oh, just forget to mention there are around 10+ outputs like this when I launch QEMU. I just post one line as an example here.

**Comment by tmakatos** [comment]
> Oh, just forget to mention there are around 10+ outputs like this when I launch QEMU. I just post one line as an example here.

Could you post/attach the full vfio-user and QEMU log? Also, what's your QEMU command line? Can you get the memory regions from QEMU and who each region belongs to?

**Comment by yanbozyb** [comment]
> [Bug scrub] @yanbozyb Would you be able to provide logs that @tmakatos mentioned above ?
> 
> Is it possible to narrow down at this point if the issue is '3rd party' - either vfio-user lib or QEMU ?

Hi Tom,

I use the same QEMU version, building steps, and command lines as described in libvfio-user guide: https://github.com/nutanix/libvfio-user/blob/master/docs/spdk.md

Maybe it's easy to reproduce this issues from your side.

Thanks

**Comment by jlevon** [comment]
I think this was a false positive error, now fixed by https://review.spdk.io/gerrit/c/spdk/spdk/+/22287

Please try latest SPDK master.

**Comment by jimharris** [comment]
Closing this issue, based on @jlevon's comment.

@yanbozyb - if you still see this with latest SPDK master, please post here and reopen.
