### ISSUE TITLE
[unittest-main-docker-autotest] Test storage is not available

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3219]
00:05:59.165  ++ (( target_space >= requested_size ))
00:05:59.165  ++ [[ overlay == tmpfs ]]
00:05:59.165  ++ [[ overlay == ramfs ]]
00:05:59.165  ++ [[ / == / ]]
00:05:59.165  ++ new_size=240735883264
00:05:59.165  ++ (( new_size * 100 / sizes[/] > 95 ))
00:05:59.165  ++ continue
00:05:59.165  ++ for target_dir in "${storage_candidates[@]}"
00:05:59.165  +++ awk '$1 !~ /Filesystem/{print $6}'
00:05:59.165  +++ df /tmp/spdk.elWYNW
00:05:59.165  ++ mount=/
00:05:59.165  ++ target_space=9195839488
00:05:59.165  ++ (( target_space == 0 || target_space < requested_size ))
00:05:59.165  ++ (( target_space >= requested_size ))
00:05:59.165  ++ [[ overlay == tmpfs ]]
00:05:59.165  ++ [[ overlay == ramfs ]]
00:05:59.165  ++ [[ / == / ]]
00:05:59.165  ++ new_size=240735883264
00:05:59.166  ++ (( new_size * 100 / sizes[/] > 95 ))
00:05:59.166  ++ continue
00:05:59.166  ++ printf '* Test storage is not available\n'
00:05:59.166  * Test storage is not available
00:05:59.166  ++ return 1
00:05:59.166    18:08:31	-- scripts/docker-autoruner.sh@56 -- # trap - ERR
00:05:59.166    18:08:31	-- scripts/docker-autoruner.sh@56 -- # print_backtrace
00:05:59.166    18:08:31	-- common/autotest_common.sh@1116 -- # [[ ehxBET =~ e ]]
00:05:59.166    18:08:31	-- common/autotest_common.sh@1118 -- # args=()
00:05:59.166    18:08:31	-- common/autotest_common.sh@1118 -- # local args
00:05:59.166    18:08:31	-- common/autotest_common.sh@1120 -- # xtrace_disable
00:05:59.166    18:08:31	-- common/autotest_common.sh@10 -- # set +x
00:05:59.166  ========== Backtrace start: ==========
00:05:59.166  
00:05:59.166  in jbp/jenkins/jjb-config/jobs/scripts/docker-autoruner.sh:56 -> main([])
00:05:59.166       ...
00:05:59.166  backtrace unavailable
00:05:59.166       ...
00:05:59.166  
00:05:59.166  ========== Backtrace end ==========
00:05:59.166    18:08:31	-- common/autotest_common.sh@1157 -- # return 0
00:05:59.177  [Pipeline] }
00:05:59.201  [Pipeline] // stage
00:05:59.210  [Pipeline] }
00:05:59.233  [Pipeline] // timeout
00:05:59.241  [Pipeline] }
00:05:59.245  ERROR: script returned exit code 1
00:05:59.261  [Pipeline] // catchError
00:05:59.270  [Pipeline] stage
00:05:59.273  [Pipeline] { (Epilogue)
00:05:59.288  [Pipeline] sh
00:05:59.632  [Pipeline] setCustomBuildProperty

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_114370.html

**Comment by mikeBashStuff** [comment]
Seems like we need to execute our cleaner more often on the relevant workers. Also, quite specific to SM32, during last migration, there were some issue that left lingering containers around which was preventing their layers from being cleaned up.

All resolved. Will leave this issue open till the end of the week in case more patches were affected.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_114367.html

**Comment by mikeBashStuff** [comment]
Cleanup on the CI side was improved, storage on related workers seems to be stable. Closing for now.
