### ISSUE TITLE
JSON: no response sent to NBD RPC

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#322]
I've written an automated test in Go that creates a malloc bdev, starts a nbd disk, mounts/unmounts that disk, and then destroys first the nbd disk, then the bdev. Before removing the nbd disk, get_nbd_disks is called because the mapping from bdev name to device name is needed.

Sometimes, usually when single-stepping through the test, this works. But most of the times the get_nbd_disks JSON call never gets a response. In an strace, I can see the recvfrom, but the corresponding sendto is missing.

## Expected Behavior

Always respond to JSON requests.

## Current Behavior

Here's how I run vhost so that my test ran run as normal user:
```
sudo app/vhost/vhost -S /var/tmp & sleep 1; sudo chmod a+rw /var/tmp/spdk.sock*; sudo strace -t -v -p `pidof vhost` -e 'trace=!accept,getrusage' -s 256 2>&1 | tee /tmp/full.log | grep -v EAGAIN & fg %-
```

Here's the output for a good run:
```
write(14, "gDf\230\0\0\0\0\5\0\0\0\0\0\0\0", 16) = 16
fcntl(13, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(13, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
# unmount /dev/nbd0:
read(14, "%`\225\23\0\0\0\1i\0\0\0\0\0\0\0\0\0\0\0\0\0\4\0\0\0\4\0", 28) = 28
read(14, "\200\0\0\0\0\4\0\0003\0\0\0\326\3\0\0u\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0 \0\0\0 \0\0\200\0\0\0Q>\21[\227>\21[\1\0\377\377S\357\1\0\1\0\0\0Q>\21[\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\v\0\0\0\200\0\0\0008\0\0\0\302\2\0\0k\4\0\0001\35\23\241\326\325B]\273\4\21=\272\350T^\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\372\367>\36\320+D\267\206e\364Vq\270sF\1\0@\0"..., 1024) = 1024
write(14, "gDf\230\0\0\0\0i\0\0\0\0\0\0\0", 16) = 16
# RPC:
recvfrom(13, "{\"jsonrpc\":\"2.0\",\"method\":\"get_nbd_disks\",\"id\":0}\n", 32768, 0, NULL, NULL) = 50
sendto(13, "{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":[{\"nbd_device\":\"/dev/nbd0\",\"bdev_name\":\"sanity\"}]}\n", 84, 0, NULL, 0) = 84
recvfrom(13, "{\"jsonrpc\":\"2.0\",\"method\":\"stop_nbd_disk\",\"params\":{\"nbd_device\":\"/dev/nbd0\"},\"id\":1}\n", 32768, 0, NULL, NULL) = 86
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fad028ed000
mprotect(0x7fad028ed000, 4096, PROT_NONE) = 0
clone(child_stack=0x7fad030ecdb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fad030ed9d0, tls=0x7fad030ed700, child_tidptr=0x7fad030ed9d0) = 7274
read(14, "%`\225\23\0\0\0\2`\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 28) = 28
```

And here it just hangs:
```
fcntl(17, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(17, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
recvfrom(13, "", 32768, 0, NULL, NULL)  = 0
close(13)                               = 0
read(14, "%`\225\23\0\0\0\1\10\0\0\0\0\0\0\0\0\0\0\0\0\0\4\0\0\0\4\0", 28) = 28
read(14, "\200\0\0\0\0\4\0\0003\0\0\0\326\3\0\0u\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0 \0\0\0 \0\0\200\0\0\0\357>\21[\357>\21[\1\0\377\377S\357\1\0\1\0\0\0\357>\21[\0\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\v\0\0\0\200\0\0\0008\0\0\0\302\2\0\0k\4\0\0\5\255uM\373=L$\264\352\307\327\361\343\237\225\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\16\207\232\0J\265I\f\263:\344\"\"W\10G\1\0@\0"..., 1024) = 1024
write(14, "gDf\230\0\0\0\0\10\0\0\0\0\0\0\0", 16) = 16
recvfrom(17, "{\"jsonrpc\":\"2.0\",\"method\":\"get_nbd_disks\",\"id\":0}\n", 32768, 0, NULL, NULL) = 50
# hangs
```

The full.log just shows attempts to get more data from fd 17:
```
15:18:18 recvfrom(17, 0x565525a110e8, 32768, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
15:18:18 recvfrom(17, "{\"jsonrpc\":\"2.0\",\"method\":\"get_nbd_disks\",\"id\":0}\n", 32768, 0, NULL, NULL) = 50
15:18:18 recvfrom(17, 0x565525a110e8, 32768, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
...
```

I also traced this under gdb and spdk_rpc_get_nbd_disks() was called and completed just fine but then the data never made it out of the process either. If you have further hints on how to debug this further, then I am all ears. Unfortunately this is a roadblock for me.

## Steps to Reproduce

I tried to reproduce this just with shell commands, but unfortunately that always succeeds:
```
(set -x; bdev=$(scripts/rpc.py construct_malloc_bdev 10 512) && scripts/rpc.py start_nbd_disk $bdev /dev/nbd0 && sudo mkfs.ext4 /dev/nbd0 && mkdir -p /tmp/target-path && sudo mount /dev/nbd0 /tmp/target-path/ && sudo umount /dev/nbd0 && scripts/rpc.py get_nbd_disks && scripts/rpc.py stop_nbd_disk /dev/nbd0 && scripts/rpc.py delete_bdev $bdev && echo done || echo failed)
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK rev 51806fa7 (current master)
Debian Stable, Linux 4.9.0-6-amd64

**Comment by pawelwod** [comment]
I will check this.

**Comment by pohly** [comment]
It's probably unrelated, but I also get this error:
```
bdev.c:1786:spdk_bdev_unmap_blocks: *ERROR*: Can't unmap 0 bytes
```

Setting a breakpoint at that line and then waiting once it is hit causes the mkfs.ext4 command to fail, perhaps due to a timeout?

**Comment by pohly** [comment]
I shared instructions for testing with my code with @pawelwod. Unfortunately I cannot make it available outside of Intel, but if someone else from Intel also wants it, please ping me via email.

**Comment by dverkamp-intel** [comment]
Looks like @pawelwod has a patch here: https://review.gerrithub.io/#/c/spdk/spdk/+/413828/

I posted some review comments, but it definitely looks like there is a race in the NBD code specifically.

**Comment by pawelwod** [comment]
`bdev.c:1786:spdk_bdev_unmap_blocks: *ERROR*: Can't unmap 0 bytes`

Yeah, I noticed this too and fixed together with the main issue here https://review.gerrithub.io/#/c/spdk/spdk/+/413808/

**Comment by wanqunintel** [comment]
@pohly would you verify with above patches and update if it works? thanks.

**Comment by pawelwod** [comment]
@pohly I reproduced your issue and this should be the fix https://review.gerrithub.io/#/c/spdk/spdk/+/414257/

**Comment by pohly** [comment]
pawelwod <notifications@github.com> writes:
> @pohly I reproduced your issue and this should be the fix
> https://review.gerrithub.io/#/c/spdk/spdk/+/414257/

Confirmed, that fixes it for me.
