### ISSUE TITLE
spdk_nvme_ns_cmd_write callback never called

### ISSUE THREAD

**Issue by m-kru** [spdk/spdk#3223]
# Sighting report

I try to implement a custom benchmark to check how the number of io qpairs impact the write throughput.
I have successfully initialized the SPDK environment, probed disk, attached to it, got namespace, and allocated qpair and buffer. None of the mentioned actions return an error. The code also successfully schedules a write using `spdk_nvme_ns_cmd_write` function. However, the callback is never called.

## Expected Behavior

The callback should be called regardless the completion succeeded or failed. There is also a chance that something is misconfigured. However, in such a case, some of the called functions should return an error.

## Current Behavior

Program hangs as the callback is never called.
Output:
```
EAL: No free 2048 kB hugepages reported on node 1
INF found disk 0000:06:00.0
INF trying to attach to 0000:06:00.0
INF found disk 0000:82:00.0
INF attached to 0000:06:00.0
INF   Namespace ID: 1 size: 1000GB
INF 0: allocated qpair
DBG 0: writing lba 0
````

## Steps to Reproduce

I have prepared a complete reproducer https://github.com/m-kru/spdk-nvme-queue-count-impact.

## Context (Environment including OS version, SPDK version, etc.)

OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
Disk: Samsung M.2 PCIe Gen4 NVMe 980 PRO 1TB
SPDK: master d5843

**Comment by jimharris** [comment]
You need to poll for completions.

Please see examples/nvme/hello_world for a template on how to do this.
