### ISSUE TITLE
nvmf-tcp-phy-autotest hit a general timeout

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3224]
The `nvmf_tcp` test suite took significant amount of time to complete (almost 2x as compared to the average time needed for all the tests in this suite to finish).

https://ci.spdk.io/results/autotest-per-patch/builds/114600/archive/nvmf-tcp-phy-autotest_59866/build.log

```
00:48:47.130  real	30m36.385s
00:48:47.130  user	77m26.794s
00:48:47.130  sys	5m17.847s
00:48:47.130   11:58:51	-- common/autotest_common.sh@1089 -- # xtrace_disable
00:48:47.130   11:58:51	-- common/autotest_common.sh@10 -- # set +x
00:48:47.130  ************************************
00:48:47.130  END TEST nvmf_tcp
00:48:47.130  ************************************
```

"Average" build:

```
[2024-01-03T10:38:45.531Z] real	16m23.930s
[2024-01-03T10:38:45.531Z] user	36m8.196s
[2024-01-03T10:38:45.531Z] sys	5m13.402s
[2024-01-03T10:38:45.531Z]  11:38:45	-- common/autotest_common.sh@1089 -- # xtrace_disable
[2024-01-03T10:38:45.531Z]  11:38:45	-- common/autotest_common.sh@10 -- # set +x
[2024-01-03T10:38:45.531Z] ************************************
[2024-01-03T10:38:45.531Z] END TEST nvmf_tcp
[2024-01-03T10:38:45.531Z] ************************************
```

In most cases the `nvmfcleanup()` took more time per test while trying to unload `nvme-fabrics` from the kernel.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_114600.html

**Comment by mikeBashStuff** [comment]
Not sure what to do with one. Unless this is related to specific hw and/or kernel itself then this is going to be hard to narrow down (especially considering the low frequency this issue pops up at (single report since two days and same job managed to execute successfully bunch of times on the same node during that time).

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mmkayPL. log: https://ci.spdk.io/public_build/autotest-per-patch_115144.html

**Comment by mmkayPL** [comment]
Isn't the job losing a lot of time waiting for a node (if I understand the logs correctly):

> 00:00:19.981  â€˜prc_bsc_waikikibeach64â€™ doesnâ€™t have label â€˜DiskNvme&&NetCVLâ€™
00:00:19.981  â€˜spdk-pxe-01â€™ doesnâ€™t have label â€˜DiskNvme&&NetCVLâ€™
00:12:42.680  Running on CYP10 in /var/jenkins/workspace/nvmf-tcp-phy-autotest

**Comment by mikeBashStuff** [comment]
> Isn't the job losing a lot of time waiting for a node (if I understand the logs correctly):
> 
> > 00:00:19.981  â€˜prc_bsc_waikikibeach64â€™ doesnâ€™t have label â€˜DiskNvme&&NetCVLâ€™
> > 00:00:19.981  â€˜spdk-pxe-01â€™ doesnâ€™t have label â€˜DiskNvme&&NetCVLâ€™
> > 00:12:42.680  Running on CYP10 in /var/jenkins/workspace/nvmf-tcp-phy-autotest

Timeout is set when the `autotest.sh` starts not the build.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_115233.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_115235.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @eugene-kobyak. log: https://ci.spdk.io/public_build/autotest-per-patch_115391.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: Not Found

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @eugene-kobyak. log: https://ci.spdk.io/public_build/autotest-per-patch_116761.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @eugene-kobyak. log: https://ci.spdk.io/public_build/autotest-per-patch_116762.html

**Comment by karlatec** [comment]
Assigning @KKaras169169.
We should make sure that HW configuration for Beetles in lab is 100% bulletproof before we close this issue.

**Comment by karlatec** [comment]
Duh, wrong issue, should be 3253

**Comment by tomzawadzki** [comment]
There are 4 valid reports, 3 occured on CYP10 and 1 on CYP9.
From recent builds of nvmf-tcp-phy job I don't see any on CYP10 node, but two on CYP9. No failures occur on those ([first](https://ci.spdk.io/results/autotest-per-patch/builds/117450/archive/nvmf-tcp-phy-autotest_64150/index.html), [second](https://ci.spdk.io/results/autotest-per-patch/builds/117445/archive/nvmf-tcp-phy-autotest_64138/index.html)).

Comparing either build logs or dmesg from fail/passing runs on CYP9 does now show relevant differences.
The systems have been upgraded from kernel `6.5.12` to `6.7.0`, which might be partially the reason for it no longer occurring.
This job seems to rarely execute on those two particular nodes (probably due to the way nodes are queued).

Would it be possible to run this specific job on either of those two nodes to confirm the issue still existing ?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @eugene-kobyak. log: https://ci.spdk.io/public_build/autotest-per-patch_118120.html

**Comment by karlatec** [comment]
@eugene-kobyak - unrelated.
The failure you reported is for `nvme`, not `nvmf`. It did not timeout and instead failed on a very specific test: `nvme_cli_cuse`

**Comment by kgodzwox** [comment]
Issue stress tested using the CI `nvmf-tcp-phy-autotest` subbuild on CYP9 and CYP10. Executed 50 test runs on each machine. During testing, it (issue) did not appear on the specified machines.

I'm closing, if it happens again, please, feel free to open this issue.
