### ISSUE TITLE
SPDK build fails with fio 3.7

### ISSUE THREAD

**Issue by ak-gh** [spdk/spdk#323]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Build with --with-fio and recent fio release (3.7 tried) fails.

## Expected Behavior

SPDK build is expected to succeed.

## Current Behavior

Build fails instead.

## Possible Solution

[Patch ](https://github.com/spdk/spdk/files/2069600/spdk-fio-3.7-build-fails.patch.gz) is attached.

## Steps to Reproduce

1. Check-out recent fio from github.com/axboes/fio.
2. Configure and build fio.
3. Run spdk/configure --with-fio=<directory you checked fio to>.

4. Run make.

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 18.04, fio-3.7-head, spdk-master

**Comment by WenqianZong** [comment]
I use latest spdk(6/5), and fio-3.7 to build, but no error occurred. Following are steps:

1. enter into /usr/local and git clone  https://github.com/axboe/fio.git
2.configure and build fio: ./configure && make&& make install
3.enter into spdk directory ,configure and build spdk: ./configure --with-fio=/usr/local/fio && make

**Comment by wanqunintel** [comment]
@ak-gh would you double check if the directory for the fio is as wenqian listed **./configure --with-fio=/usr/local/fio**

**Comment by darsto** [comment]
This is the fio commit that breaks our fio_plugin -
https://github.com/axboe/fio/commit/d3b07186b1d4c7c1d9adc1306407458ce41ad048
We should add #ifs for FIO_IOOPS_VERSION number to support both fio
versions. @ak-gh can you post a fix to gerrithub?
D.

2018-06-05 7:06 GMT+02:00 wanqunintel <notifications@github.com>:

**Comment by WenqianZong** [comment]
Hi @ak-gh 
Could you provide your error log ? After configure spdk with --enable-werror, I found following error:
```
fio_plugin.c:655:2: error: initialization from incompatible pointer type [-Werror]
  .queue   = spdk_fio_queue,
  ^
fio_plugin.c:655:2: error: (near initialization for ‘ioengine.queue’) [-Werror]
cc1: all warnings being treated as errors
make[3]: *** [fio_plugin.o] Error 1
make[2]: *** [fio_plugin] Error 2
make[1]: *** [bdev] Error 2
make: *** [examples] Error 2
```

**Comment by ak-gh** [comment]
@darsto, the [patch](https://review.gerrithub.io/c/spdk/spdk/+/413749) has been submitted to gerrithub.

**Comment by dverkamp-intel** [comment]
This should be fixed as of commit 4e51a274dee5e2fa942f9e8f39d02d8e96f9e7a5 - thanks for the patch!

**Comment by ak-gh** [comment]
Daniel,

patch submission, imo, would be simplified if checkpatch had been installed as pre-commit hook. If you have such a setup locally, you might want to consider adding it to the review tree.

Regards,
Andrey

**Comment by dverkamp-intel** [comment]
The formatting checks are available as a git pre-commit hook, but you have to enable it first, since git does not provide a way to automatically install hooks:
`git config core.hooksPath .githook`

**Comment by johnmeneghini** [comment]
Got to love it.  We’ve been using this pre-commit and pre-push hook for months internally.  It is a big help.

**Comment by johnmeneghini** [comment]
You’ll need to run this git config command each time you clone a new repository.  The configuration is change is kept in the .git/config file of each repository.

Also, after you’ve enabled the hooks, you can manually override them by specifying –no-verify on the git commit or git push command line.

/John

**Comment by ak-gh** [comment]
Thanks Daniel.

Regards,
Andrey

**Comment by ak-gh** [comment]
Surprisingly, after changing core.hooksPath as suggested I lost config-msg
hook (I've copied it under the new hooks path for sure, but it still didn't
work) which prevented pushes to gerrit. Restoring hooks path back to
default brought Change-Id back :).

Regards,
Andrey
