### ISSUE TITLE
[dm_mount] device-mapper: reload ioctl on nvme_dm_test

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#3232]
# CI Intermittent Failure

00:15:17.544  ************************************
00:15:17.544  START TEST dm_mount
00:15:17.544  ************************************
00:15:17.544   13:30:18	-- common/autotest_common.sh@1101 -- # dm_mount
00:15:17.544   13:30:18	-- setup/devices.sh@144 -- # pv=nvme0n1
00:15:17.544   13:30:18	-- setup/devices.sh@145 -- # pv0=nvme0n1p1
00:15:17.544   13:30:18	-- setup/devices.sh@146 -- # pv1=nvme0n1p2
00:15:17.544   13:30:18	-- setup/devices.sh@148 -- # partition_drive nvme0n1
00:15:17.544   13:30:18	-- setup/common.sh@39 -- # local disk=nvme0n1
00:15:17.544   13:30:18	-- setup/common.sh@40 -- # local part_no=2
00:15:17.544   13:30:18	-- setup/common.sh@41 -- # local size=1073741824
00:15:17.544   13:30:18	-- setup/common.sh@43 -- # local part part_start=0 part_end=0
00:15:17.544   13:30:18	-- setup/common.sh@44 -- # parts=()
00:15:17.544   13:30:18	-- setup/common.sh@44 -- # local parts
00:15:17.544   13:30:18	-- setup/common.sh@46 -- # (( part = 1 ))
00:15:17.544   13:30:18	-- setup/common.sh@46 -- # (( part <= part_no ))
00:15:17.544   13:30:18	-- setup/common.sh@47 -- # parts+=("${disk}p$part")
00:15:17.544   13:30:18	-- setup/common.sh@46 -- # (( part++ ))
00:15:17.544   13:30:18	-- setup/common.sh@46 -- # (( part <= part_no ))
00:15:17.544   13:30:18	-- setup/common.sh@47 -- # parts+=("${disk}p$part")
00:15:17.544   13:30:18	-- setup/common.sh@46 -- # (( part++ ))
00:15:17.544   13:30:18	-- setup/common.sh@46 -- # (( part <= part_no ))
00:15:17.544   13:30:18	-- setup/common.sh@51 -- # (( size /= 4096 ))
00:15:17.544   13:30:18	-- setup/common.sh@56 -- # sgdisk /dev/nvme0n1 --zap-all
00:15:17.544   13:30:18	-- setup/common.sh@53 -- # /home/vagrant/spdk_repo/spdk/scripts/sync_dev_uevents.sh block/partition nvme0n1p1 nvme0n1p2
00:15:18.524  Creating new GPT entries in memory.
00:15:18.524  GPT data structures destroyed! You may now partition the disk using fdisk or
00:15:18.524  other utilities.
00:15:18.524   13:30:19	-- setup/common.sh@57 -- # (( part = 1 ))
00:15:18.524   13:30:19	-- setup/common.sh@57 -- # (( part <= part_no ))
00:15:18.524   13:30:19	-- setup/common.sh@58 -- # (( part_start = part_start == 0 ? 2048 : part_end + 1 ))
00:15:18.524   13:30:19	-- setup/common.sh@59 -- # (( part_end = part_start + size - 1 ))
00:15:18.524   13:30:19	-- setup/common.sh@60 -- # sgdisk /dev/nvme0n1 --new=1:2048:264191
00:15:19.578  Creating new GPT entries in memory.
00:15:19.578  The operation has completed successfully.
00:15:19.578   13:30:20	-- setup/common.sh@57 -- # (( part++ ))
00:15:19.578   13:30:20	-- setup/common.sh@57 -- # (( part <= part_no ))
00:15:19.578   13:30:20	-- setup/common.sh@58 -- # (( part_start = part_start == 0 ? 2048 : part_end + 1 ))
00:15:19.578   13:30:20	-- setup/common.sh@59 -- # (( part_end = part_start + size - 1 ))
00:15:19.578   13:30:20	-- setup/common.sh@60 -- # sgdisk /dev/nvme0n1 --new=2:264192:526335
00:15:20.513  Warning: The kernel is still using the old partition table.
00:15:20.513  The new table will be used at the next reboot or after you
00:15:20.513  run partprobe(8) or kpartx(8)
00:15:20.513  The operation has completed successfully.
00:15:20.513   13:30:21	-- setup/common.sh@57 -- # (( part++ ))
00:15:20.513   13:30:21	-- setup/common.sh@57 -- # (( part <= part_no ))
00:15:20.513   13:30:21	-- setup/common.sh@62 -- # wait 156880
00:15:30.493  * Events for some block/partition devices (nvme0n1p2) were not caught, they may be missing
00:15:30.493   13:30:30	-- setup/devices.sh@150 -- # dm_name=nvme_dm_test
00:15:30.493   13:30:30	-- setup/devices.sh@151 -- # dm_mount=/home/vagrant/spdk_repo/spdk/test/setup/dm_mount
00:15:30.493   13:30:30	-- setup/devices.sh@152 -- # dm_dummy_test_file=/home/vagrant/spdk_repo/spdk/test/setup/dm_mount/test_dm
00:15:30.493   13:30:30	-- setup/devices.sh@155 -- # dmsetup create nvme_dm_test
00:15:30.493  device-mapper: reload ioctl on nvme_dm_test (253:0) failed: No such device
00:15:30.493  Command failed.
00:15:30.493    13:30:30	-- setup/devices.sh@155 -- # trap - ERR
00:15:30.493    13:30:30	-- setup/devices.sh@155 -- # print_backtrace
00:15:30.493    13:30:30	-- common/autotest_common.sh@1129 -- # [[ ehxBET =~ e ]]
00:15:30.493    13:30:30	-- common/autotest_common.sh@1131 -- # args=('dm_mount' 'dm_mount')
00:15:30.493    13:30:30	-- common/autotest_common.sh@1131 -- # local args
00:15:30.493    13:30:30	-- common/autotest_common.sh@1133 -- # xtrace_disable
00:15:30.493    13:30:30	-- common/autotest_common.sh@10 -- # set +x

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/115319/archive/rocky9-vg-autotest_5235/build.log

## Execution failed at

00:15:30.493  ========== Backtrace start: ==========
00:15:30.493  
00:15:30.493  in /home/vagrant/spdk_repo/spdk/test/setup/devices.sh:155 -> dm_mount([])
00:15:30.493       ...
00:15:30.493     150 		dm_name=nvme_dm_test
00:15:30.493     151 		dm_mount=$SPDK_TEST_STORAGE/dm_mount
00:15:30.493     152 		dm_dummy_test_file=$dm_mount/test_dm
00:15:30.493     153 	
00:15:30.493     154 		# Each partition is 1G in size, join their halves
00:15:30.493  => 155 		dmsetup create "$dm_name" <<- DM_TABLE

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_115319.html

**Comment by mikeBashStuff** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/21452

**Comment by tomzawadzki** [comment]
Let's close the issue since patch https://review.spdk.io/gerrit/c/spdk/spdk/+/21452 was merged.
