### ISSUE TITLE
fatal: unable to access spdk-abi

### ISSUE THREAD

**Issue by jkalwas** [spdk/spdk#3233]
# CI Intermittent Failure

00:00:00.000  Started by upstream project "autotest-per-patch" build number 115314
00:00:00.000  originally caused by:
00:00:00.000   Started by user sys_sgci
00:00:00.013  Checking out git https://review.spdk.io/gerrit/a/build_pool/jenkins_build_pool into /var/jenkins_home/workspace/autobuild-external-vg-autotest_script/33b20b30f0a51e6b52980845e0f6aa336787973ad45e341fbbf98d1b65b265d4 to read jbp/jenkins/jjb-config/jobs/autotest-downstream/autotest-vg.groovy
00:00:00.013  The recommended git tool is: git
00:00:00.014  using credential 00000000-0000-0000-0000-000000000002
00:00:00.016   > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/autobuild-external-vg-autotest_script/33b20b30f0a51e6b52980845e0f6aa336787973ad45e341fbbf98d1b65b265d4/jbp/.git # timeout=10
00:00:00.032  Fetching changes from the remote Git repository
00:00:00.038   > git config remote.origin.url https://review.spdk.io/gerrit/a/build_pool/jenkins_build_pool # timeout=10
00:00:00.072  Using shallow fetch with depth 1
00:00:00.072  Fetching upstream changes from https://review.spdk.io/gerrit/a/build_pool/jenkins_build_pool
00:00:00.072   > git --version # timeout=10
00:00:00.095   > git --version # 'git version 2.39.2'
00:00:00.095  using GIT_ASKPASS to set credentials SPDKCI HTTPS Credentials
00:00:00.102  Setting http proxy: proxy-dmz.intel.com:911
00:00:00.102   > git fetch --tags --force --progress --depth=1 -- https://review.spdk.io/gerrit/a/build_pool/jenkins_build_pool refs/heads/master # timeout=5
00:00:02.870   > git rev-parse origin/FETCH_HEAD^{commit} # timeout=10
00:00:02.881   > git rev-parse FETCH_HEAD^{commit} # timeout=10
00:00:02.893  Checking out Revision f1d65f40c19b3a3602f9259ed62e18c9aafd0eee (FETCH_HEAD)
00:00:02.893   > git config core.sparsecheckout # timeout=10
00:00:02.905   > git read-tree -mu HEAD # timeout=10
00:00:02.921   > git checkout -f f1d65f40c19b3a3602f9259ed62e18c9aafd0eee # timeout=5
00:00:02.941  Commit message: "jenkins/jjb: re-enable IAA tests in dsa-phy-autotest"
00:00:02.941   > git rev-list --no-walk f1d65f40c19b3a3602f9259ed62e18c9aafd0eee # timeout=10
00:00:03.030  [Pipeline] Start of Pipeline
00:00:03.040  [Pipeline] library
00:00:03.042  Loading library shm_lib@master
00:00:03.043  Library shm_lib@master is cached. Copying from home.
00:00:03.054  [Pipeline] node
00:00:03.066  Running on VM-host-SM16 in /var/jenkins/workspace/autobuild-external-vg-autotest
00:00:03.067  [Pipeline] {
00:00:03.075  [Pipeline] catchError
00:00:03.076  [Pipeline] {
00:00:03.085  [Pipeline] wrap
00:00:03.092  [Pipeline] {
00:00:03.097  [Pipeline] stage
00:00:03.098  [Pipeline] { (Prologue)
00:00:03.110  [Pipeline] echo
00:00:03.111  Node: VM-host-SM16
00:00:03.115  [Pipeline] cleanWs
00:00:03.122  [WS-CLEANUP] Deleting project workspace...
00:00:03.122  [WS-CLEANUP] Deferred wipeout is used...
00:00:03.128  [WS-CLEANUP] done
00:00:03.268  [Pipeline] setCustomBuildProperty
00:00:03.322  [Pipeline] nodesByLabel
00:00:03.323  Found a total of 1 nodes with the 'sorcerer' label
00:00:03.330  [Pipeline] httpRequest
00:00:03.333  HttpMethod: GET
00:00:03.334  URL: http://10.211.11.40/jbp_f1d65f40c19b3a3602f9259ed62e18c9aafd0eee.tar.gz
00:00:03.337  Sending request to url: http://10.211.11.40/jbp_f1d65f40c19b3a3602f9259ed62e18c9aafd0eee.tar.gz
00:00:03.340  Response Code: HTTP/1.1 200 OK
00:00:03.340  Success: Status code 200 is in the accepted range: 200,404
00:00:03.340  Saving response body to /var/jenkins/workspace/autobuild-external-vg-autotest/jbp_f1d65f40c19b3a3602f9259ed62e18c9aafd0eee.tar.gz
00:00:03.577  [Pipeline] sh
00:00:03.848  + tar --no-same-owner -xf jbp_f1d65f40c19b3a3602f9259ed62e18c9aafd0eee.tar.gz
00:00:03.862  [Pipeline] httpRequest
00:00:03.866  HttpMethod: GET
00:00:03.866  URL: http://10.211.11.40/spdk_2ad5fdf0640ac4969f5712a4786222f9f9e841ed.tar.gz
00:00:03.867  Sending request to url: http://10.211.11.40/spdk_2ad5fdf0640ac4969f5712a4786222f9f9e841ed.tar.gz
00:00:03.867  Response Code: HTTP/1.1 200 OK
00:00:03.868  Success: Status code 200 is in the accepted range: 200,404
00:00:03.868  Saving response body to /var/jenkins/workspace/autobuild-external-vg-autotest/spdk_2ad5fdf0640ac4969f5712a4786222f9f9e841ed.tar.gz
00:00:21.918  [Pipeline] sh
00:00:22.196  + tar --no-same-owner -xf spdk_2ad5fdf0640ac4969f5712a4786222f9f9e841ed.tar.gz
00:00:25.494  [Pipeline] sh
00:00:25.771  + git -C spdk log --oneline -n5
00:00:25.771  2ad5fdf06 nvme: mark (un)likely to improve hot path
00:00:25.771  3a0904564 nvmf: mark (un)likely to improve hot path
00:00:25.771  52bab482b bdev: mark (un)likely to improve hot path
00:00:25.771  3bcb19cca bdev_nvme: mark (un)likely to improve hot path
00:00:25.771  df8283060 test/nvmf/digest: group digest error tests
00:00:25.789  [Pipeline] withCredentials
00:00:25.799   > git --version # timeout=10
00:00:25.813   > git --version # 'git version 2.39.2'
00:00:25.828  Masking supported pattern matches of $GIT_USERNAME or $GIT_PASSWORD or $GIT_ASKPASS
00:00:25.830  [Pipeline] {
00:00:25.839  [Pipeline] retry
00:00:25.841  [Pipeline] {
00:00:25.858  [Pipeline] sh
00:00:26.152  + git ls-remote https://review.spdk.io/gerrit/a/spdk/spdk-abi refs/heads/master
00:00:28.059  fatal: unable to access 'https://review.spdk.io/gerrit/a/spdk/spdk-abi/': Received HTTP code 503 from proxy after CONNECT
00:00:28.073  [Pipeline] }
00:00:28.077  ERROR: script returned exit code 128

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/115314/archive/autobuild-external-vg-autotest_10461/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_115314.html

**Comment by mikeBashStuff** [comment]
This is a networking issue that our infra doesn't have much control over. I submitted a change to include similar pattern for retries.  Other than that, no more will be done so leaving this open for some time in case more patches have been affected.
