### ISSUE TITLE
Spinlock error when using multiple cores for blobstore

### ISSUE THREAD

**Issue by omidrostamabadi** [spdk/spdk#3237]
# Sighting report

I'm getting a spinlock related error when I run a thread on another core to init the blobstore.

## Expected Behavior

No errors on spinlocks.

## Current Behavior

`thread.c: 955:thread_execute_poller: *ERROR*: unrecoverable spinlock error 7: Lock(s) held while SPDK thread going off CPU (thread->lock_count == 0)`

## Steps to Reproduce

This is a minimal example:

```
void cb(arg) {
*arg = 1; // Terminates while loop in app thread
}

void fn(arg) {
spdk_bdev_create_bs_dev_ext(&dev);
spdk_bs_init(dev, NULL, cb, arg);
}

void called_by_spdk_app_start() {
/* core_1 is a cpuset having core number 1 set.
* application is run using two cores, 0 and 1. app thread
* is running on core 0 */
t = spdk_thread_create("worker", &core_1);
done = 0;
spdk_thread_send_msg(t, fn, &done);

while(!done)
    spdk_thread_poll(t, 0, 0);

}
```

## Context (Environment including OS version, SPDK version, etc.)

```
Ubuntu 22.04.3 LTS
Kernel version: 5.15.0-91-generic
SPDK version: SPDK v24.01
cmd: ./program -m 0x3 -c config.json
```

**Comment by jimharris** [comment]
Hi,

Please share a full example that someone can use to reproduce.  There are too many details missing, and sharing the example will be quicker than going back-and-forth with questions.

Thanks,

Jim

**Comment by omidrostamabadi** [comment]
Hi,

This is a full example:

```
#include "spdk/stdinc.h"

#include "spdk/thread.h"
#include "spdk/bdev.h"
#include "spdk/env.h"
#include "spdk/event.h"
#include "spdk/blob_bdev.h"
#include "spdk/blob.h"
#include "spdk/log.h"
#include "spdk/string.h"

static void base_bdev_event_cb(enum spdk_bdev_event_type type,
	                       struct spdk_bdev *bdev, void *event_ctx)
{
	printf("Unsupported bdev event: type %d\n", type);
}

static void fn_cb(void *cb_arg, struct spdk_blob_store *bs,
	int bserrno) {
	int *done= cb_arg;
	*done= 1;
}

void fn(void *a) {
	struct spdk_bs_dev *tmp;
	int rc = spdk_bdev_create_bs_dev_ext("Malloc0", base_bdev_event_cb, NULL, &tmp);
	if(rc) {
		printf("Failed bs_dev\n");
	}
	printf("Calling spdk_bs_init\n");
	spdk_bs_init(tmp, NULL, fn_cb, a);
}


void app_fn(void *unused_arg) {
	struct spdk_thread *t1;
	struct spdk_cpuset cpu;
	spdk_cpuset_zero(&cpu);
	spdk_cpuset_set_cpu(&cpu, 1, true);
	t1 = spdk_thread_create("worker_0", &cpu);
	int ok = 0;
	spdk_thread_send_msg(t1, fn, &ok);

	printf("Waiting\n");
	while(ok == 0) {
		spdk_thread_poll(t1, 0, 0);
	}
	printf("Finished!\n");
	spdk_app_stop(0);
}


int main(int argc, char **argv) {
	struct spdk_app_opts opts = {};
	spdk_app_opts_init(&opts, sizeof(opts));
	if(spdk_app_parse_args(argc, argv, &opts, NULL, NULL, NULL, NULL) != SPDK_APP_PARSE_ARGS_SUCCESS) {
		printf("Parse error");
	}
	opts.name = "test_multicore";

	int rc = spdk_app_start(&opts, app_fn, NULL);

	spdk_app_fini();

	return 0;
}

```

hello_blob.json contents:
```
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_malloc_create",
          "params": {
            "name": "Malloc0",
            "num_blocks": 32768,
            "block_size": 512
          }
        }
      ]
    }
  ]
}
```

cmd:
```
sudo ./test -c hello_blob.json -m 0x3
[2024-01-19 16:52:28.888478] Starting SPDK v24.01-pre git sha1 d4d9a181d / DPDK 23.07.0 initialization...
[2024-01-19 16:52:28.888556] [ DPDK EAL parameters: test_multicore --no-shconf -c 0x3 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid544230 ]
[2024-01-19 16:52:29.094750] app.c: 798:spdk_app_start: *NOTICE*: Total cores available: 2
[2024-01-19 16:52:29.102791] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
[2024-01-19 16:52:29.102789] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 1
Waiting
Calling spdk_bs_init
[2024-01-19 16:52:29.111742] thread.c: 955:thread_execute_poller: *ERROR*: unrecoverable spinlock error 7: Lock(s) held while SPDK thread going off CPU (thread->lock_count == 0)
[1]    544228 IOT instruction  sudo ./test -c hello_blob.json -m 0x3
```

**Comment by jimharris** [comment]
Thanks @omidrostamabadi.  I'll take a look at this, but probably not until week after next.

I've assigned it to myself for now.

**Comment by jimharris** [comment]
> Hi,
> 
> This is a full example:
> 
> ```
> #include "spdk/stdinc.h"
> 
> #include "spdk/thread.h"
> #include "spdk/bdev.h"
> #include "spdk/env.h"
> #include "spdk/event.h"
> #include "spdk/blob_bdev.h"
> #include "spdk/blob.h"
> #include "spdk/log.h"
> #include "spdk/string.h"
> 
> static void base_bdev_event_cb(enum spdk_bdev_event_type type,
> 	                       struct spdk_bdev *bdev, void *event_ctx)
> {
> 	printf("Unsupported bdev event: type %d\n", type);
> }
> 
> static void fn_cb(void *cb_arg, struct spdk_blob_store *bs,
> 	int bserrno) {
> 	int *done= cb_arg;
> 	*done= 1;
> }
> 
> void fn(void *a) {
> 	struct spdk_bs_dev *tmp;
> 	int rc = spdk_bdev_create_bs_dev_ext("Malloc0", base_bdev_event_cb, NULL, &tmp);
> 	if(rc) {
> 		printf("Failed bs_dev\n");
> 	}
> 	printf("Calling spdk_bs_init\n");
> 	spdk_bs_init(tmp, NULL, fn_cb, a);
> }
> 
> 
> void app_fn(void *unused_arg) {
> 	struct spdk_thread *t1;
> 	struct spdk_cpuset cpu;
> 	spdk_cpuset_zero(&cpu);
> 	spdk_cpuset_set_cpu(&cpu, 1, true);
> 	t1 = spdk_thread_create("worker_0", &cpu);
> 	int ok = 0;
> 	spdk_thread_send_msg(t1, fn, &ok);
> 
> 	printf("Waiting\n");
> 	while(ok == 0) {
> 		spdk_thread_poll(t1, 0, 0);

This part is not valid.

This code right here is running on core 0. You've created t1, with affinity for core 1.

So the reactor on core 1 is calling spdk_thread_poll() on this thread at same time as this code running on core 0. When using the app framework (spdk_app_start()), you should never poll spdk_threads explicitly - the reactors are responsible for this.

SPDK is meant to be asynchronous, so polling like this in general is not usually a good idea. If there is some next step you want to do after the blobstore has been created, have your `fn_cb` function send a message back to the original thread (using `spdk_thread_send_msg`) to perform that next step.

> 	}
> 	printf("Finished!\n");
> 	spdk_app_stop(0);
> }
> 
> 
> int main(int argc, char **argv) {
> 	struct spdk_app_opts opts = {};
> 	spdk_app_opts_init(&opts, sizeof(opts));
> 	if(spdk_app_parse_args(argc, argv, &opts, NULL, NULL, NULL, NULL) != SPDK_APP_PARSE_ARGS_SUCCESS) {
> 		printf("Parse error");
> 	}
> 	opts.name = "test_multicore";
> 
> 	int rc = spdk_app_start(&opts, app_fn, NULL);
> 
> 	spdk_app_fini();
> 
> 	return 0;
> }
> ```
> 
> hello_blob.json contents:
> 
> ```
> {
>   "subsystems": [
>     {
>       "subsystem": "bdev",
>       "config": [
>         {
>           "method": "bdev_malloc_create",
>           "params": {
>             "name": "Malloc0",
>             "num_blocks": 32768,
>             "block_size": 512
>           }
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> cmd:
> 
> ```
> sudo ./test -c hello_blob.json -m 0x3
> [2024-01-19 16:52:28.888478] Starting SPDK v24.01-pre git sha1 d4d9a181d / DPDK 23.07.0 initialization...
> [2024-01-19 16:52:28.888556] [ DPDK EAL parameters: test_multicore --no-shconf -c 0x3 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid544230 ]
> [2024-01-19 16:52:29.094750] app.c: 798:spdk_app_start: *NOTICE*: Total cores available: 2
> [2024-01-19 16:52:29.102791] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
> [2024-01-19 16:52:29.102789] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 1
> Waiting
> Calling spdk_bs_init
> [2024-01-19 16:52:29.111742] thread.c: 955:thread_execute_poller: *ERROR*: unrecoverable spinlock error 7: Lock(s) held while SPDK thread going off CPU (thread->lock_count == 0)
> [1]    544228 IOT instruction  sudo ./test -c hello_blob.json -m 0x3
> ```

**Comment by omidrostamabadi** [comment]
Hi,

Thank you @jimharris for pointing me to the right direction. I'm closing this issue now.
