### ISSUE TITLE
start_nbd_disk: allocate unused /dev/nbd*

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#324]
My code that calls the start_nbd_disk method might run without root privileges, for example as part of a "go test" invocation. That leads to a problem: the code needs to pick an unused /dev/nbd* device node, but how can it determine which one is unused?

My current approach is to determine the size of /dev/nbd* by opening it and then seeking to the end. ioctl(BLKGETSIZE64) would also work, but is a bit harder to call from Go. But this only works because my non-root user is in the "disks" group, which has r/w access to /dev/nbd* on Debian.

There's also a potential race: if multiple processes try to create a NBD disk, then the chosen device node might no longer be available when SPDK tries to use it.

## Current Behavior

Caller of start_nbd_disk must choose the device.

## Possible Solution

start_nbd_disk could also pick a device node itself if `nbd_device` is empty. By opening exclusively it should be possible to avoid the race.

**Comment by dverkamp-intel** [comment]
Automatically choosing a /dev/nbdN device in the RPC sounds like a great idea; we would probably have to change the `start_nbd_disk` API slightly to return the path to the chosen /dev node, but that should probably be OK (the only return value right now is a bool that is always `true` just to have a non-empty response for successful completions).

**Comment by pohly** [comment]
FWIW, I didn't even know that start_nbd_disk has a return value. In the Go bindings that I wrote I don't expect one and just check for an error response. The way how Go handles JSON is that it picks entries that it has a mapping for to the response struct and ignores everything that is unknown, so changing the return type won't break anything.

**Comment by pawelwod** [comment]
I disagree. Automatically choosing a /dev/nbdN device is bad idea. This is the administar task to know which device to use. This will lead to the same issues as we had in SPDK with automatic bdev name generation or hotplug automatic naming scheme.

**Comment by pohly** [comment]
pawelwod <notifications@github.com> writes:
> I disagree. Automatically choosing a /dev/nbdN device is bad idea.
> This is the administar task to know which device to use.

But who is the administrator in a fully automated, headless system?

There is none, so such a system has to allocate a device
automatically. Doing that on the client side of the JSON RPC is worse
than doing it on the server side (race condition, additional privileges
needed, client needs to know more about NBD than really necessary).

**Comment by jimharris** [comment]
Can’t start_nbd_disk just take an optional parameter?  If the parameter is specified, use that specific nbd node.  If it’s not, pick an unused one.

The original description suggests opening it exclusively to avoid a race – but it would have to be a separate file used as a lock, something like /var/tmp/spdk_nbdX?  If the SPDK app opens /dev/nbdX exclusively, then you can’t put a filesystem on it or mount it.

**Comment by pohly** [comment]
Jim Harris <notifications@github.com> writes:
> Can’t start_nbd_disk just take an optional parameter?  If the
> parameter is specified, use that specific nbd node.

The nbd_device could be treated as optional the way you described it.

> The original description suggests opening it exclusively to avoid a
> race – but it would have to be a separate file used as a lock,
> something like /var/tmp/spdk_nbdX?  If the SPDK app opens /dev/nbdX
> exclusively, then you can’t put a filesystem on it or mount it.

Right, I hadn't considered that. So the details may be different, but
because /dev/nbd is a shared resource I expect the kernel to ensure that
only one operations succeeds when different processes try conflicting
operations at the same time.

**Comment by darsto** [comment]
I just merged a patch for this into SPDK master.
Thanks @pohly , thanks @dong-liuliu . It took us quite an effort to enhance the NBD module.

https://review.gerrithub.io/c/spdk/spdk/+/440453
