### ISSUE TITLE
Performance Regression in NVMe Tests (TC1 - bdevperf)

### ISSUE THREAD

**Issue by jchachux** [spdk/spdk#3241]
# Sighting report

Performance Regression in NVMe Tests (TC1 - bdevperf) since Release 23.09

## Expected Behavior

The NVMe test (TC1 - bdevperf) should maintain consistent performance levels or show improvements across different commits

## Current Behavior

A noticeable performance drop was observed in the NVMe TC1 - bdevperf test during our smoke tests before 24.01 release. The specific performance figures are:

  | Commit | RW Mode | QD | Disks | IOPS |
| --- | --- | --- | --- | --- |
| 23.09 fb13eebf53 | randread | 192 | 7 | 5895838.94 |
| 055de83ac62 | randread | 192 | 7 | 5472347.04 |

The commit 055de83ac62 exhibits a significant drop in IOPS compared to the earlier 23.09 commit, indicating the commit where the regression likely occurred.

Git bisect history

| Commit Description                                                    | Commit SHA                              | Bisect Status | IOPS         |
|-----------------------------------------------------------------------|-----------------------------------------|---------------|--------------|
| SPDK 23.09                                                            | fb13eebf53d7f132baa2e39992a6ad79affdcdaa | Good          | 5,884,687.300|
| test/dd: Negative tests for spdk_dd app                               | 55ce71877279b518f64b3282e38a32e7f7d30f96 | Bad           | 5,451,625.330|
| test/fused_ordering: add multiple queue support                       | 1e3c98930cebfbca6bc22cf7580e7d79cd6e0d00 | Good          | 5,917,575.530|
| bdev/malloc: don't do verify when separate metadata buffer is null    | 9bec3f5891b5d0a3a5965ae3d77cef705f4dd420 | Good          | 5,911,411.620|
| nvme_rdma: Clear rdma_req->rdma_rsp to avoid posting garbage to SRQ   | c71f33ee50df93fd8fa10499a2fb6f00ed20d1fa | Bad           | 5,474,722.980|
| lvol/ut: reuse ut_cb_res in lvol_close UT                             | 84130e3900010c01e3d0c779c4388547cc773b70 | Bad           | 5,430,885.660|
| bdev: multiple QoS queues with atomic-based QoS quota                 | 055de83ac62de00d8c6214825cc5af86f5201b9c | Bad           | 5,471,117.510|
| pkgdep/git: Bump OOT irdma to latest release 1.12.55                  | cff6495bf4a1397fb4398dd0b842452aac2dacb2 | Good          | 5,946,171.420|
| nvme/pcie: drop nvme_qpair_free_request                               | 30560979e866ed94e12bc163cfcb9d733389a23d | Good          | 5,919,714.370|
| nvme: restore nvme_complete_request optimization for pcie             | ee06b4c234696e9a74bc776b252c9896ee30467a | Good          | 5,900,793.440|
| bdev_ut: abort all IOs upon reset                                     | debc2429a5c6f6ac952a065aded7e886ec3b8a6a | Good          | 5,862,229.130|
| **First Bad Commit**: bdev: multiple QoS queues with atomic-based QoS quota | 055de83ac62de00d8c6214825cc5af86f5201b9c | Bad           | 5,418,806.990|

## Context (Environment including OS version, SPDK version, etc.)

Fedora 37 - 6.1.6-200.fc37.x86_64

**Comment by tomzawadzki** [comment]
Short update on the issue. A quick revert is being tested on the suspected patch https://review.spdk.io/gerrit/c/spdk/spdk/+/21541.

**Comment by jchachux** [comment]
I managed to run test with revert patch ea0d115 and we got 5,792,768 IOPS and also run on master 71eba7f and we got 5,310,264 IOPS.

**Comment by jchachux** [comment]
I conducted a performance evaluation on today's master branch (commit ID: 67642ba9), where we observed a throughput of 5.2 million IOPS. In comparison, using Konrad's [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/21576) , the throughput increased to 5.74 million IOPS.
