### ISSUE TITLE
[nvmf_rpc] Failed to write to /dev/nvme-fabrics: Invalid argument

### ISSUE THREAD

**Issue by DamiaSan** [spdk/spdk#3246]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/116414/archive/nvmf-phy-autotest_62480/build.log

## Execution failed at

00:13:50.186   14:41:23	-- target/rpc.sh@62 -- # nvme connect -i 15 -t rdma -n nqn.2016-06.io.spdk:cnode1 -q nqn.2016-06.io.spdk:host1 -a 192.168.100.8 -s 4420
00:13:50.186  Failed to write to /dev/nvme-fabrics: Invalid argument
00:13:50.186  could not add new controller: invalid arguments/configuration
00:13:50.186    14:41:23	-- target/rpc.sh@62 -- # trap - ERR
00:13:50.187    14:41:23	-- target/rpc.sh@62 -- # print_backtrace
00:13:50.187    14:41:23	-- common/autotest_common.sh@1125 -- # [[ ehxBET =~ e ]]
00:13:50.187    14:41:23	-- common/autotest_common.sh@1127 -- # args=('--transport=rdma')
00:13:50.187    14:41:23	-- common/autotest_common.sh@1127 -- # local args
00:13:50.187    14:41:23	-- common/autotest_common.sh@1129 -- # xtrace_disable
00:13:50.187    14:41:23	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:13:50.187    14:41:23	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=ehxBET
00:13:50.187    14:41:23	-- common/autotest_common.sh@22 -- # [[ ehxBET == *\x* ]]
00:13:50.187    14:41:23	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:13:50.187    14:41:23	-- common/autotest_common.sh@25 -- # set +x
00:13:50.187  ========== Backtrace start: ==========
00:13:50.187  
00:13:50.187  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/rpc.sh:62 -> main(["--transport=rdma"])
00:13:50.187       ...
00:13:50.187     57  	# This connect should fail - the host NQN is not allowed
00:13:50.187     58  	NOT $NVME_CONNECT -t $TEST_TRANSPORT -n nqn.2016-06.io.spdk:cnode1 -q nqn.2016-06.io.spdk:host1 -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:13:50.187     59  	
00:13:50.187     60  	# Add the host NQN and verify that the connect succeeds
00:13:50.187     61  	$rpc_py nvmf_subsystem_add_host nqn.2016-06.io.spdk:cnode1 nqn.2016-06.io.spdk:host1
00:13:50.187  => 62  	$NVME_CONNECT -t $TEST_TRANSPORT -n nqn.2016-06.io.spdk:cnode1 -q nqn.2016-06.io.spdk:host1 -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
00:13:50.187     63  	waitforserial "$NVMF_SERIAL"
00:13:50.187     64  	nvme disconnect -n nqn.2016-06.io.spdk:cnode1
00:13:50.187     65  	waitforserial_disconnect "$NVMF_SERIAL"
00:13:50.187     66  	
00:13:50.187     67  	# Remove the host and verify that the connect fails
00:13:50.187       ...
00:13:50.187  
00:13:50.187  ========== Backtrace end ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116414.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116416.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116418.html

**Comment by mikeBashStuff** [comment]
@DamiaSan I am afraid your patch series is severely outdated (it also includes merge conflicts) and needs a rebase - failures here are caused due to several changes missing from your tree. My suggestion would to be quickly `git diff -v --stat HEAD origin/master` to see how far behind series really is (retriggering builds won't help here I am afraid).  For now, I am closing this issue (as this particular one was already fixed via 75bf61ffb7).
