### ISSUE TITLE
destruction of bdev is not synchronized with closing channels for bdev

### ISSUE THREAD

**Issue by SWaoter** [spdk/spdk#3252]
## Expected Behavior

bdev destroy callback invoked after all channels are closed

## Current Behavior

Currently race is possible when bdev_destroy_cb is invoked before all channels are closed

## Possible Solution

The problem is that in `spdk_bdev_for_each_channel` we provide completion callback, but we do not invoke it on the completion.
Instead it is invoked right after needed function was scheduled by `spdk_thread_send_msg`.

Because we already pass `struct spdk_io_channel_iter *i` as context for `_call_channel`, I think that it would be logical to add atomic counter inside `spdk_io_channel_iter` that will increase when request is scheduled for the channel. Then counter decreases when channel completes request and final callback is invoked only when it reaches 0.

Maybe there is more elegant solution.

However, I am sure that current design is definetly not safe, because destroying of channels includes destroying channel contextes, which most likely contain bdev related information, that is be freed during bdev destruction.

Please correct me if I'm missing something.

## Context (Environment including OS version, SPDK version, etc.)

latest SPDK

**Comment by jimharris** [comment]
> ## Expected Behavior
> bdev destroy callback invoked after all channels are closed
> 
> ## Current Behavior
> Currently race is possible when bdev_destroy_cb is invoked before all channels are closed

I don't see how `bdev_destroy_cb` can be called before all channels are closed.

`bdev_destroy_cb` is the callback function for the call to `spdk_io_device_unregister()`. `spdk_io_device_unregister()` will defer actual destruction (including calling the `bdev_destroy_cb` callback) until all channels are closed.

Please refer to `struct io_device`'s `refcnt` in lib/bdev/bdev.c.

> 
> ## Possible Solution
> The problem is that in `spdk_bdev_for_each_channel` we provide completion callback, but we do not invoke it on the completion. Instead it is invoked right after needed function was scheduled by `spdk_thread_send_msg`.
> 
> Because we already pass `struct spdk_io_channel_iter *i` as context for `_call_channel`, I think that it would be logical to add atomic counter inside `spdk_io_channel_iter` that will increase when request is scheduled for the channel. Then counter decreases when channel completes request and final callback is invoked only when it reaches 0.
> 
> Maybe there is more elegant solution.
> 
> However, I am sure that current design is definetly not safe, because destroying of channels includes destroying channel contextes, which most likely contain bdev related information, that is be freed during bdev destruction.
> 
> Please correct me if I'm missing something.
> 
> ## Context (Environment including OS version, SPDK version, etc.)
> latest SPDK

**Comment by SWaoter** [comment]
Hi @jimharris, thank you for answer. I am sorry for not observing code too deep and missing  `struct io_device`'s `refcnt`.

Let me please share a problem that I've encountered that lead me to opening this issue.
I have custom bdev, that I've registered as `io_device` with `spdk_io_device_register` and then as `bdev` with `spdk_bdev_register`.
As a result I end up with two separate `io_device`s, because `bdev_register` leads to creating explicit `io_device` (named with prefix `bdev_`). Obviously I have separate create/destroy channel callback functions that I provide to `spdk_io_device_register`, I will refer it as **MY_channels**.

After that I create NVME TCP transport over my device. It leads to creating **MY_channels** for every `nvmf_poll_group`.
As a last step I call `spdk_bdev_unregister()` and what I see is that a callback that I provide to unregister is executed before all of **MY_channels** are closed.

What I've understood from your comment and code is that there are a mechanism that synchronize channel close and unregister/destroy of bdev. However, as far as I understand, it waits for channels that are created for opaque `io_device` that was created during `bdev_register`. As `dev` itself and `refcnt` for it are different, it does not make sure that channels are closed for other `io_devices` that was registered for same bdev. 

So now I understand that what I've written in the original issue is wrong. However, I still do not understand if existing design works correctly.

Can you please comment on my new findings?

**Comment by jimharris** [comment]
In your `destruct` function in your spdk_bdev_fn_table, are you returning 0 or 1?

In your case, you have some asynchronous work you need to do in the destruct callback. The way to tell the bdev layer that you have async work to do is to return 1 from the destruct_cb. When you return 1, the bdev layer will defer calling the unregister callback.

Then once you've cleaned everything up on your end, call `spdk_bdev_destruct_done` which will then call your unregister callback.

This is not well-documented, and I see some areas this could be better clarified in bdev_module.h.  We'll use this issue to track those doc fixes, once you confirm this is the problem you are hitting.

**Comment by jimharris** [comment]
So you are returning 1 from your bdev destruct function?

**Comment by SWaoter** [comment]
I am returning 0 from destruct function

**Comment by jimharris** [comment]
You need to return 1 from your destruct function.  Then unregister the io_device from your bdev. After you get the io_device unregistration callback, call `spdk_bdev_destruct_done()`. You will see your spdk_bdev_unregister() callback get called after that.

**Comment by jimharris** [comment]
I've posted https://review.spdk.io/gerrit/c/spdk/spdk/+/21774 which helps improve the documentation around this code path. @SWaoter I would appreciate your review and feedback.

**Comment by SWaoter** [comment]
@jimharris Thank you. Your proposal with combining destruct_cb + io_device_unregister + destruct_done worked for me. I have just one more question. As you've written on gerrit spdk_bdev_unregister shouldn't be called from bdev modules. What I'm trying implement here is destroying bdev on user request. It includes several steps one of which is removing spdk_bdev itself. Is there a better strategy for it, or is it really case when bdev_unregister should be used?

**Comment by jimharris** [comment]
> @jimharris Thank you. Your proposal with combining destruct_cb + io_device_unregister + destruct_done worked for me. I have just one more question. As you've written on gerrit spdk_bdev_unregister shouldn't be called from bdev modules. What I'm trying implement here is destroying bdev on user request. It includes several steps one of which is removing spdk_bdev itself. Is there a better strategy for it, or is it really case when bdev_unregister should be used?

Copying my Gerrit comment here for reference for others:

"Your use case is still not clear to me. spdk_bdev_unregister() should really only be called by the bdev module itself (for its bdevs), or the bdev layer during shutdown (to unregister any bdevs that still exist). bdev modules shouldn't trigger actions based on the spdk_bdev_unregister() callback, it should base them on the destruct_cb."

Calling spdk_bdev_unregister() in the case you describe is valid - a bdev module should call spdk_bdev_unregister() when a bdev is going away - either by user request (in your case), or some kind of hot removal event (i.e. an NVMe SSD gets hot removed.)

Thank you for confirming the suggestions worked! Let's keep this issue open for now until the doc improvements get merged.

**Comment by jimharris** [comment]
Patch merged.
