### ISSUE TITLE
Beetle: connect to host 192.168.10.11 port 22: No route to host

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3253]
# CI Intermittent Failure

No specific test linked to intermittent failure.

One of the "prologue" CI script fails when attempting to configure "Beetle" add-on card attached to test systems, which is used in autotest-nightly nvme hotplug tests.
WFP9, WFP13 and WFP15 systems were recently migrated to new lab space and these addons were not appropriately reconfigured.

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_116748.html

## Execution failed at

```
16:26:58  [Pipeline] withCredentials
16:26:58  Masking supported pattern matches of $beetle_key
16:26:58  [Pipeline] {
16:26:58  [Pipeline] sh
16:26:59  + ssh -i **** -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=5 root@192.168.10.11 'for gpio in {0..10}; do Beetle --SetGpio "$gpio" HIGH; done'
16:27:21  ssh: connect to host 192.168.10.11 port 22: No route to host
16:27:21  [Pipeline] }
16:27:21  [Pipeline] // withCredentials
16:27:21  [Pipeline] }
16:27:21  [Pipeline] // stage
16:27:21  [Pipeline] }
16:27:21  [Pipeline] // wrap
16:27:21  [Pipeline] }
16:27:21  ERROR: script returned exit code 255
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_116748.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116787.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116785.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116788.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116789.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116796.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116795.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116794.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116798.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_116797.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_116780.html

**Comment by karlatec** [comment]
@KKaras169169 
We should make sure that HW configuration for Beetles in lab is 100% bulletproof before we close this issue.

**Comment by tomzawadzki** [comment]
@KKaras169169 has resolved the issues with Beetles for HW hotplug tests that were observed at the time. No issues reported since, closing.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_121353.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @DamiaSan. log: https://ci.spdk.io/public_build/autotest-per-patch_121354.html

**Comment by DamiaSan** [comment]
I have just found another couple of errors like these, it doesn't seem to be completely fixed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @m-spiewak. log: https://ci.spdk.io/public_build/autotest-per-patch_121365.html

**Comment by KKaras169169** [comment]
hw_hotplug is disabled in CI and scheduled for removal from our test suites.

**Comment by jimharris** [comment]
I hit this a couple of times today. Reopening.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_128453.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_128452.html

**Comment by mikeBashStuff** [comment]
Disabled the affected node. We are planning to get rid off the entire hw_hotplug suite in the near future, together with the beetle setup, so eventually this issue should stop bothering us (sooner or later).

**Comment by KKaras169169** [comment]
I disconnected Beetles from their nodes yesterday and unplugged all interposers, so `Beetle` specific issues should not bother anyone anymore.
