### ISSUE TITLE
In v24.01 isa-l and isa-l-crypto are always build with shared libraries

### ISSUE THREAD

**Issue by mpiszczek** [spdk/spdk#3257]
I am building SPDK v24.01. I am seeing that the isa-l and isa-l-crypto libraries are always built with shared libraries. I believe the check for shared libraries in configure is incorrect.

## Possible Solution

```
diff --git a/configure b/configure
index acf73b0d1..c9d5365bc 100755
--- a/configure
+++ b/configure
@@ -1223,7 +1223,7 @@ if [[ "${CONFIG[ISAL]}" = "y" ]]; then
        else
                ISAL_OPTS=()
        fi
-       if [[ -n "${CONFIG[SHARED]}" ]]; then
+       if [[ "${CONFIG[SHARED]}" == y ]]; then
                ISAL_OPTS+=("--enable-shared=yes")
        else
                ISAL_OPTS+=("--enable-shared=no")
@@ -1256,7 +1256,7 @@ if [[ "${CONFIG[ISAL]}" = "y" ]]; then
        if [[ -n "${CONFIG[CROSS_PREFIX]}" ]]; then
                ISAL_CRYPTO_OPTS+=("--host=${CONFIG[CROSS_PREFIX]}")
        fi
-       if [[ -n "${CONFIG[SHARED]}" ]]; then
+       if [[ "${CONFIG[SHARED]}" == y ]]; then
                ISAL_CRYPTO_OPTS+=("--enable-shared=yes")
        else
                ISAL_CRYPTO_OPTS+=("--enable-shared=no")
```

## Steps to Reproduce
```
Building on 6.5.0-15-generic #15~22.04.1-Ubuntu
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

Both tests below build isa-l and isa-l-crypto with shared libraries.
./configure --with-shared
./configure --without-shared

**Comment by mikeBashStuff** [comment]
I already have a series with a fix for that here https://review.spdk.io/gerrit/c/spdk/spdk/+/21768.

**Comment by jimharris** [comment]
> I already have a series with a fix for that here https://review.spdk.io/gerrit/c/spdk/spdk/+/21768.

Thanks @mikeBashStuff, I assigned this issue to you and updated the labels appropriately.

**Comment by mpiszczek** [comment]
Thanks. I will close this issue.

**Comment by jimharris** [comment]
Reopening, since @mikeBashStuff has patches outstanding, let's use this issue to track when this gets completed.

**Comment by mikeBashStuff** [comment]
Patch merged, closing.

**Comment by mpiszczek** [comment]
Thanks!\
