### ISSUE TITLE
[vfio_fuzz] I/O qpair stats leak

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#3258]
# CI Intermittent Failure

Since patch https://review.spdk.io/gerrit/c/spdk/spdk/+/20639 leak detection was turned on, but the job where short fuzz tests run do not compile with ASAN. Enabling it like in https://review.spdk.io/gerrit/c/spdk/spdk/+/20722/, results in reporting leaks of I/O qpair stats.

Running this test on my own machine, I can confirm the result. Due to the nature of the test, I wasn't yet able to confirm exact scenario - especially the exit path - when this leak occurs.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/117014/archive/short-fuzz-phy-autotest_17263/build.log

## Execution failed at

```
00:11:01.994  ==3083638==ERROR: LeakSanitizer: detected memory leaks
00:11:01.994  
00:11:01.994  Direct leak of 72 byte(s) in 1 object(s) allocated from:
00:11:01.994      #0 0x50a8dc in __interceptor_calloc (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz+0x50a8dc) (BuildId: 59b6211d6d9cee5c8177b806958a7311ba43a0f8)
00:11:01.994      #1 0x1984389 in _nvme_pcie_ctrlr_create_io_qpair /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/lib/nvme/nvme_pcie_common.c:538:19
00:11:01.994      #2 0x1983b3b in nvme_pcie_ctrlr_connect_qpair /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/lib/nvme/nvme_pcie_common.c:564:8
00:11:01.994      #3 0x1a557bd in nvme_transport_ctrlr_connect_qpair /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/lib/nvme/nvme_transport.c:478:7
00:11:01.994      #4 0x180b170 in spdk_nvme_ctrlr_connect_io_qpair /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/lib/nvme/nvme_ctrlr.c:423:7
00:11:01.994      #5 0x180dd55 in spdk_nvme_ctrlr_alloc_io_qpair /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/lib/nvme/nvme_ctrlr.c:495:7
00:11:01.994      #6 0x54e344 in init_io /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:475:25
00:11:01.994      #7 0x7f798dd43946 in start_thread (/usr/lib64/libc.so.6+0x8c946) (BuildId: f888be5f5e7d58e04cabb8c675c7ab94e77dd68c)
```

**Comment by m-spiewak** [comment]
This is false memory leak detected by leak sanitizer. The memory allocated for queue statistics, which is reported here as leaked, is freed at the end of test, after all passes of test loops (i.e. after 60000 seconds in our long fuzzer Jenkins job).
We have two allocations (for admin and IO queues) at the beginning, and two memory free calls at the end of test. LLVM's leak sanitizer probably detects that the memory is not freed after first call to tested function, so it reports a leak.
I have added some debug messages when a memory for queue statistics is allocated and freed, and it seems the memory is not leaked. The output from the fuzzer when running for 20 sec with memory allocation and free traces (indicated by 'MS++ [A1]...' 'MS++ [A2] ...', 'MS++ [F1] ... ' and 'MS++ [F2] ... ' strings) looks like:
```
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1209667198
MS++ [A1] 0x2000137ff0c0
INFO: Loaded 1 modules   (314821 inline 8-bit counters): 314821 [0x30b762c, 0x31043f1), 
INFO: Loaded 1 PC tables (314821 PCs): 314821 [0x31043f8,0x35d2048), 
INFO:        0 files found in /home/mspiewak/leak_spdk/../corpus/llvm_vfio_0
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED exec/s: 0 rss: 194Mb
WARNING: no interesting inputs were found so far. Is the code instrumented for coverage?
This may also happen if the target rejected all inputs we tried so far
MS++ [A2] 0x607000007020
	NEW_FUNC[1/549]: 0x5647c0 in fuzz_vfio_user_region_rw /home/mspiewak/leak_spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:80

[ . . . ]

#128	pulse  cov: 9446 ft: 19532 corp: 100/2000b lim: 60 exec/s: 6 rss: 264Mb
#128	NEW    cov: 9446 ft: 19532 corp: 101/2010b lim: 60 exec/s: 6 rss: 264Mb L: 10/59 MS: 1 ChangeByte-
#132	NEW    cov: 9446 ft: 19562 corp: 102/2035b lim: 60 exec/s: 6 rss: 264Mb L: 25/59 MS: 4 InsertByte-CrossOver-ChangeByte-EraseBytes-
#132	DONE   cov: 9446 ft: 19562 corp: 102/2035b lim: 60 exec/s: 6 rss: 264Mb
###### Recommended dictionary. ######
"\000C\230c,\230\023)" # Uses: 3
"r\000\000\000\000\000\000\000" # Uses: 2
"log_" # Uses: 2
"\000\000\000\000" # Uses: 0
"ioat" # Uses: 1
"\314\373\240\000\000\000\000\000" # Uses: 1
"RG_ring_5_1325879" # Uses: 0
"noti" # Uses: 1
"\000C\230m7Y\207e" # Uses: 0
"\000\220n\031\000 \000\000" # Uses: 0
###### End of recommended dictionary. ######
Done 132 runs in 21 second(s)
MS++ [F1] 0x607000007020
MS++ [F2] 0x2000137ff0c0
```

To avoid this issue we probably need to disable leak detection for this job.

**Comment by jimharris** [comment]
@m-spiewak I'm having trouble understanding exactly where the debug prints were put for this test. Can you post the patch you used for the test on Gerrit?

Fuzzing is meant to induce all kinds of failures, completely disabling leak detection for this job doesn't seem like a good idea.

**Comment by m-spiewak** [comment]
@jimharris here is the patch [https://review.spdk.io/gerrit/c/spdk/spdk/+/21827](url)  ("MS++" string used in the log I posted in my previous comment is now changed to "QP_stat")

Also, in this patch the run time for the fuzzer is changed from ~16 hrs to 10 sec to save time.

You can run this code without ASAN first to see alloc/free for specific addresses, then enable ASAN and check.

**Comment by m-spiewak** [comment]
@jimharris @tomzawadzki Jim, Tomek, there is other way: __lsan_disable() and __lsan_enable(). According to the LLVM LSAN API description:
"_// Allocations made between calls to __lsan_disable() and __lsan_enable() will
// be treated as non-leaks. Disable/enable pairs may be nested.
void SANITIZER_CDECL __lsan_disable(void);
void SANITIZER_CDECL __lsan_enable(void);_"

And indeed, when qpair stat allocation is 'excluded' from leak detection in _nvme_pcie_ctrlr_create_io_qpair() function:
```
	__lsan_disable();
	pqpair->stat = calloc(1, sizeof(*pqpair->stat));
	__lsan_enable();
```
we can run the fuzzer with leak detection enabled globally and the run is successful.

The issue here is that if we do exclusion this way, we are polluting nvme_pcie_common.c with some 'ifdefs' to check if this is compiled to be run under llvm fuzzer or just as regular SPDK. I don't even know yet how to do this, I just did a simple check whether the function works, but it is working - the results are in the attached logs (both runs with "-detect_leaks=1", so leak detection is enabled, but one run with statistics allocation excluded from leak detector, the other run was done with no exclusion):
[no__lsan_disable.txt](https://github.com/spdk/spdk/files/14294857/no__lsan_disable.txt)
[with__lsan_disable.txt](https://github.com/spdk/spdk/files/14294860/with__lsan_disable.txt)

**Comment by m-spiewak** [comment]
Please also look at this: [https://review.spdk.io/gerrit/c/spdk/spdk/+/21897](https://review.spdk.io/gerrit/c/spdk/spdk/+/21897)
Sebastian have found yet another other way to suppress this false leak detection.

**Comment by jimharris** [comment]
I'm running this test locally, and I do not see the qpair get freed.

The qpair gets freed via the exit_handler() code path, and I don't see exit_handler() getting called either. This function gets registered with atexit() in the fuzz app, but doesn't seem to be getting invoked.

**Comment by jimharris** [comment]
> I'm running this test locally, and I do not see the qpair get freed.
> 
> The qpair gets freed via the exit_handler() code path, and I don't see exit_handler() getting called either. This function gets registered with atexit() in the fuzz app, but doesn't seem to be getting invoked.

It's possible there is some difference in our configurations, where your exit_handler() is getting invoked, but maybe ASAN checks for leaks before any atexit handlers run.

**Comment by sberbz** [comment]
Hi @jimharris 

>  but maybe ASAN checks for leaks before any atexit handlers run.

It's exactly like that, when detect_leask is set to 1 in fuzzer config, fuzzerDrive calls '__lsan_do_recoverable_leak_check' after test execution not only at shut down. I believe that this issue is caused by LSAN not being able to detect reference that are hold on hugepage, even if ASan is enabled on DPDK.

**Comment by jimharris** [comment]
> Hi @jimharris
> 
> > but maybe ASAN checks for leaks before any atexit handlers run.
> 
> It's exactly like that, when detect_leask is set to 1 in fuzzer config, fuzzerDrive calls '__lsan_do_recoverable_leak_check' after test execution not only at shut down. I believe that this issue is caused by LSAN not being able to detect reference that are hold on hugepage, even if ASan is enabled on DPDK.

The detected leak is not a DPDK allocation, it is a regular `calloc`.

But I think your `__lsan_disable()` idea is the better one to go with. But don't put it around just this one specific allocation in the lib/nvme code. But it specifically around the io_qpair allocation in the fuzz app itself. I just tried that and it seems to work fine.

**Comment by sberbz** [comment]
> The detected leak is not a DPDK allocation, it is a regular calloc.

Yes, but 'pqpair' is. So we have 'stat' that is recognized by LSAN and the only reference to this variable is stored on 'pqpair', when FuzzerDrive calls '__lsan_do_recoverable_leak_check' LSAN knows that variable 'stat' has been allocated and yet not freed, but there is no available reference to this variable (cause its stored on hugepage), therefore LSAN report memory leak.

**Comment by sberbz** [comment]
Patch ready for review https://review.spdk.io/gerrit/c/spdk/spdk/+/21897

**Comment by jimharris** [comment]
Patch merged.
