### ISSUE TITLE
--enable-debug and --enable-lto mask compilation errors

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3259]
```
SPDK: v24.05-pre-67-g84532e3d2
GCC: 13.2.1
```

When building SPDK with enabled werror + enabled ASAN, the build fails with the following:

```
# ./configure --enable-werror --enable-asan
# ...
# make -j
...
In file included from nvme_tcp.c:23:
nvme_tcp.c: In function ‘nvme_tcp_qpair_write_pdu’:
/test/spdk_internal/nvme_tcp.h:37:38: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
37 |             ((*((uint8_t *)(BUF)+1)) = (uint8_t)((uint32_t)(CRC32C) >> 8)), \
|             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# what follows is exactly the same error for the entire MAKE_DIGEST_WORD()
```

Disabling asan (i.e. not enabling it explicitly on the cmdline), but keeping werror, passes just fine. Disabling werror also works since only warning is then emitted. However, adding `--enable-debug` or `--enable-lto` to the mix ALSO allows the build to pass, even when asan and werror are enabled together.

Summary:

```
# This fails
./configure --enable-werror --enable-asan --disable-debug --whatever-other-opt-you-like
# This builds
./configure --enable-werror --enable-asan --enable-debug --whatever-other-opt-you-like
# This also builds
./configure --enable-werror --enable-asan --disable-debug --enable-lto --whatever-other-opt-you-like
# This naturally works
./configure --disable-werror --enable-asan --whatever-other-opt-you-like
```

In context of asan and the actual error that's being caught all seems to make sense. But what doesn't is the fact that `--enable-debug`, `--enable-lto` somehow mask this issue. By quickly glancing through our mk infra I don't see any quirkiness in terms of compiler's opts when debug is being enabled (nor when lto is).

We don't see this under per-patch nor nightly as our autotest infra doesn't build SPDK without debug - what's close is the autopackage.sh build, but that one slaps lto into the mix. Some builds also don't enable asan at all.

**Comment by jimharris** [comment]
It sounds like the compilation errors are because of asan+werror?  I was a bit confused, the title says the compilation errors happen with debug+lto, but the description says those options actually get the compilation to pass.

**Comment by mikeBashStuff** [comment]
> the title says the compilation errors happen with debug+lto, but the description says those options actually get the compilation to pass.

Maybe that was a poor wording on my part but that's what I meant by "masking" here - even though werror and asan are enabled, enabling lto or debug as well allows the build to pass:
```
--enable-werror --enable-asan # fail
--enable-werror --enable-asan --enable-debug # pass
--enable-werror --enable-asan --enable-lto # pass
--enable-werror --enable-asan --enable-lto --enable-debug # pass
```

**Comment by jimharris** [comment]
> > the title says the compilation errors happen with debug+lto, but the description says those options actually get the compilation to pass.
> 
> Maybe that was a poor wording on my part but that's what I meant by "masking" here - even though werror and asan are enabled, enabling lto or debug as well allows the build to pass:
> 
> ```
> --enable-werror --enable-asan # fail
> --enable-werror --enable-asan --enable-debug # pass
> --enable-werror --enable-asan --enable-lto # pass
> --enable-werror --enable-asan --enable-lto --enable-debug # pass
> ```

Ah, I understand now. But I think we need to fix the werror+asan build, and maybe add werror+asan only build testing, rather than trying to get debug and/or lto to not make compilation errors go away.  debug/lto both fundamentally change how the compiler works, there's no way to "fix" that.

**Comment by mikeBashStuff** [comment]
To me it's a bit odd because this essentially makes the non-debug build, well, more debug than the debug one. :D - as a user, I would expect from the debug build to catch more issues not the other way around (I may be oversimplifying things, especially in context of how LTO impacts the build, but I still think it's a fair assumption).

**Comment by jimharris** [comment]
"debug" in this context means easier to debug issues, not compilation errors - i.e. we turn off optimization to make it easier to walk through code in gdb.

We already have other examples where --enable-debug "masks" compilation errors. Any variables used only in an assert() will compile with --enable-debug, but will throw a warning (or error with --enable-werror) without --enable-debug.

I don't disagree that you've found something here that is masking compilation errors, I'm just saying that we can't somehow fix --enable-debug or --enable-lto. As the commit title is worded currently, we should just close it as "3rd Party Issue" since there's nothing SPDK can do about it.

**Comment by mikeBashStuff** [comment]
I am fine with closing this then, but please look into the https://github.com/spdk/spdk/issues/3260 since on its own it blocks (or at least makes it a bit harder to complete)  https://github.com/spdk/spdk/issues/3096 since that's where the actual non-debug build will have to be used (working on it uncovered this werror+asan issue in a first place).
