### ISSUE TITLE
examples/nvme/fio_plugin should call spdk_nvme_ctrlr_process_admin_completions()

### ISSUE THREAD

**Issue by dverkamp-intel** [spdk/spdk#326]
## Expected Behavior

The NVMe `fio_plugin` example should call spdk_nvme_ctrlr_process_admin_completions(), resulting in keep-alives being sent for NVMe-oF connections.

## Current Behavior

The admin queue process completions function is never called, so the keep-alive command is never sent.  This results in a timeout when connected to an NVMe-oF target that correctly implements keep alive support, like the Linux kernel.

## Possible Solution

Add a call to spdk_nvme_ctrlr_process_admin_completions() for each active controller in examples/nvme/fio_plugin/fio_plugin.c.

## Steps to Reproduce
1. Configure Linux kernel NVMe-oF target to expose a subsystem
2. Run fio using examples/nvme/fio_plugin with a run time longer than 10 seconds (default keep-alive timeout for Linux target).

## Context (Environment including OS version, SPDK version, etc.)

Problem exists as of current SPDK master (01a9118d0c29e76df08581c2978d7f82e2b3e508).
User reported issue when running fio_plugin against a Linux 4.16.14 target.

**Comment by dverkamp-intel** [comment]
@benlwalker has posted a patch to fix this: https://review.gerrithub.io/c/spdk/spdk/+/414481

**Comment by wanqunintel** [comment]
@ChenWang01 pls. check this patch, thanks.

**Comment by benlwalker** [comment]
The patch posted above fixes this same bug in the bdev fio_plugin. Here's one that fixes it in the nvme fio_plugin:

https://review.gerrithub.io/#/c/415538/

**Comment by ChenWang01** [comment]
Hi, Qun
@wanqunintel 
I have verified this issue with master branch(include https://review.gerrithub.io/#/c/415538/ patch), and this issue can't be reproduced.
commit id：ddc63f077a6271a9fed4181ce65130b09d074433
The fio_plugin call the spdk_nvme_ctrlr_process_admin_completions() function, and the fioplugin can run successfully. So this issue can be closed.

Thanks,
Chen
