### ISSUE TITLE
SPDK crashes with core dump when block size 0 is passed

### ISSUE THREAD

**Issue by gbregman** [spdk/spdk#3263]
I neglected to set the block size when I called bdev_rbd_create(), a default of 0 was used. The result was I got a core dump for division by 0. There is no test for block size being zero and its value is used in a division. I expected to get a proper exception about an invalid parameter in such a case, not a crash.

**Comment by sberbz** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/21934

**Comment by jimharris** [comment]
Patch merged.
