### ISSUE TITLE
[clang-vg-autotest] clang-16: error: unable to execute command

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#3265]
In builds:
https://ci.spdk.io/public_build/autotest-nightly-lts_1473.html
https://ci.spdk.io/public_build/autotest-nightly-lts_1474.html

> 00:12:55.727  clang-16: error: unable to execute command: Killed
> 00:12:55.727  clang-16: error: linker command failed due to signal (use -v to see invocation)
> 00:12:55.727  make[3]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.app.mk:39: bdev_svc] Error 1
> 00:12:55.727  make[2]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.subdirs.mk:16: bdev_svc] Error 2
> 00:12:55.727  make[1]: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.subdirs.mk:16: app] Error 2

**Comment by mikeBashStuff** [comment]
This happens due to to the fact that `ld.gold` slurps all the memory from the VM (already 16GB). Here's a series with a mitigation on top: https://review.spdk.io/gerrit/c/spdk/spdk/+/21770.

**Comment by xjjx** [comment]
Another occurrence of this issue: https://ci.spdk.io/public_build/autotest-nightly_3332.html

**Comment by xjjx** [comment]
Another occurrence of this issue: https://ci.spdk.io/public_build/autotest-nightly_3333.html

**Comment by xjjx** [comment]
Another occurrence of this issue: https://ci.spdk.io/public_build/autotest-nightly_3339.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1481.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1483.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3362.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3365.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3366.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1503.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1508.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1509.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1521.html
