### ISSUE TITLE
[dpdk_cryptodev] receive "Method not found" when dpdk_cryptodev_scan_accel_module

### ISSUE THREAD

**Issue by liuqinfei** [spdk/spdk#3266]
# Sighting report

## Expected Behavior

With dpdk_cryptodev_scan_accel_module RPC, correct dpdk_cryptodev module should be listed.

## Current Behavior

[root@node1 spdk]# ./scripts/rpc.py dpdk_cryptodev_scan_accel_module
request:
{
  "method": "dpdk_cryptodev_scan_accel_module",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32601,
  "message": "Method not found"
}

## Possible Solution

Not know.

## Steps to Reproduce

1. sysctl -w vm.nr_hugepages=80000
2. ./scripts/setup.sh
3. ./build/bin/spdk_tgt --wait-for-rpc
4. ./scripts/rpc.py dpdk_cryptodev_scan_accel_module

## Context (Environment including OS version, SPDK version, etc.)
[root@node1 spdk]# cat /etc/os-release
NAME="openEuler"
VERSION="22.03 (LTS-SP1)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP1)"
ANSI_COLOR="0;31"
5.10.0-136.12.0.86.oe2203sp1.aarch64
HiSilicon Kunpeng-920

**Comment by liuqinfei** [comment]
It seems --with-crypto is necessaries when ./configure.
It works as following:
./configure --with-crypto --with-dpdk-compressdev
./build/bin/spdk_tgt -m 0xf0 --wait-for-rpc

./scripts/rpc.py dpdk_cryptodev_scan_accel_module
[root@node1 spdk]# ./scripts/rpc.py accel_assign_opc -o encrypt -m dpdk_cryptodev
[root@node1 spdk]# ./scripts/rpc.py accel_assign_opc -o decrypt -m dpdk_cryptodev
[root@node1 spdk]# ./scripts/rpc.py framework_start_init
[root@node1 spdk]# ./scripts/rpc.py accel_get_opc_assignments
{
  "copy": "software",
  "fill": "software",
  "dualcast": "software",
  "compare": "software",
  "crc32c": "software",
  "copy_crc32c": "software",
  "compress": "software",
  "decompress": "software",
  "encrypt": "dpdk_cryptodev",
  "decrypt": "dpdk_cryptodev",
  "xor": "software",
  "dif_verify": "software",
  "dif_generate": "software",
  "dif_generate_copy": "software"
}

However i get the error log:

[2024-02-19 08:56:32.978047] accel_rpc.c: 168:rpc_accel_assign_opc: *NOTICE*: Operation encrypt will be assigned to module dpdk_cryptodev
[2024-02-19 08:56:47.194332] accel_rpc.c: 168:rpc_accel_assign_opc: *NOTICE*: Operation decrypt will be assigned to module dpdk_cryptodev
**[2024-02-19 08:57:00.959678] accel_dpdk_cryptodev.c:1151:accel_dpdk_cryptodev_init: *NOTICE*: Failed to create virtual PMD crypto_aesni_mb: error -1. Possibly crypto_aesni_mb is not supported by DPDK library. Keep going...
[2024-02-19 08:57:00.959740] accel_dpdk_cryptodev.c:1158:accel_dpdk_cryptodev_init: *NOTICE*: Found crypto devices: 0**

**Comment by AlekseyMarchuk** [comment]
Hi @liuqinfei 

You are right, `--with-crypto` is required to build vbdev_crypto and dpdk crypto_dev accel module. Regarding `Found crypto devices: 0` - I see you are using ARM, default SW ipsec_mb driver doesn't work on ARM so there are no DPDK crypto drivers available. You can try using `software` accel module or modify `dpdkbuild/Makefile` to enable openssl dpdk SW driver. But please note, we don't test this driver in CI

**Comment by tomzawadzki** [comment]
This seems like a bug. Shouldn't `accel_dpdk_cryptodev_init()` return a failure when no devices are found ? This way the opc would get assigned to `software`, rather than `dpdk_cryptodev`.

**Comment by liuqinfei** [comment]
> dpdk_cryptodev

It may be a bug. But the 'software' is not the correct one for the case. Because the 'software' encrypt opt is in fact the crypto_aesni_mb. This may reference to the IPsec_mb library which is not supported on the arm platform yet.

**Comment by AlekseyMarchuk** [comment]
@tomzawadzki Agree, we should fail dpdk_cryptodev initialization if no drivers found
@liuqinfei `software` accel module uses isa-l-crypto library which is supported on ARM and performs pretty good

**Comment by liuqinfei** [comment]
> @tomzawadzki Agree, we should fail dpdk_cryptodev initialization if no drivers found @liuqinfei `software` accel module uses isa-l-crypto library which is supported on ARM and performs pretty good

Got that. Thanks.

**Comment by tomzawadzki** [comment]
Please see https://review.spdk.io/gerrit/c/spdk/spdk/+/22026, which addresses falling back when no devices are found for particular module.

**Comment by gaozhangfei** [comment]
Hi, @tomzawadzki , 
If we use module/accel/dpdk_cryptodev, the dpdk crypto pmd should be registered first, right?
Still not understand what cmd will trigger RTE_PMD_REGISTER_VDEV of dpdk/drivers/crypto/ipsec_mb.
If pmd is not registered, rte_vdev_init will fail.
Any hint？
Thanks

**Comment by tomzawadzki** [comment]
All SPDK acceleration framework modules need to be scanned before they can be used. Usually via `*_scan_accel_module` RPC. This applies to dpdk_cryptodev module too - https://spdk.io/doc/accel_fw.html#accel_dpdk_cryptodev.

As per documentation above, a select number of DPDK cryptodev PMDs are supported. This includes the [AESNI MB PMD](https://doc.dpdk.org/guides/cryptodevs/aesni_mb.html). Please note that specific PMD has be compiled in the DPDK used by SPDK. AESNI MB PMD is present in the DPDK supplied by the SPDK submodule, but if you use another DPDK build - please double check that.

Besides that, AESNI MB PMD should be the default for dpdk_cryptodev. In any case you can switch which PMD to use via `dpdk_cryptodev_set_driver` RPC.

**Comment by ksztyber** [comment]
[Bug scrub] There are no updates since April, closing the issue. @liuqinfei feel free to re-open if needed.
