### ISSUE TITLE
[raid_bdev] bdev_raid.c:1357:_raid_bdev_create: *ERROR*: Unsupported raid level '95'

### ISSUE THREAD

**Issue by liuqinfei** [spdk/spdk#3267]
# Sighting report

Can not create raid_bdev with raid level = raid5f (95)

## Expected Behavior
success to create. We know supported levels:
enum raid_level {
	INVALID_RAID_LEVEL	= -1,
	RAID0			= 0,
	RAID1			= 1,
	RAID5F			= 95, /* 0x5f */
	CONCAT			= 99,
};

## Current Behavior
[root@node1 spdk]# ./scripts/rpc.py bdev_raid_get_bdevs all
[]
[root@node1 spdk]# ./scripts/rpc.py bdev_raid_create -n Raid0 -z 4 -r RAID5F -b "NVMe1n1 NVMe2n1 NVMe3n1 NVMe4n1"
request:
{
  "name": "Raid0",
  "raid_level": "RAID5F",
  "base_bdevs": [
    "NVMe1n1",
    "NVMe2n1",
    "NVMe3n1",
    "NVMe4n1"
  ],
  "superblock": false,
  "strip_size_kb": 4,
  "method": "bdev_raid_create",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -22,
  "message": "Failed to create RAID bdev Raid0: Invalid argument"
}
[root@node1 spdk]# ./scripts/rpc.py bdev_raid_create -n Raid0 -z 4 -r RAID0 -b "NVMe1n1 NVMe2n1 NVMe3n1 NVMe4n1"
[root@node1 spdk]# ./scripts/rpc.py bdev_raid_get_bdevs all
[
  {
    "name": "Raid0",
    "uuid": "d91675c3-f75c-4691-85f4-a3750c621957",
    "strip_size_kb": 4,
    "state": "online",
    "raid_level": "raid0",
    "superblock": false,
    "num_base_bdevs": 4,
    "num_base_bdevs_discovered": 4,
    "num_base_bdevs_operational": 4,
    "base_bdevs_list": [
      {
        "name": "NVMe1n1",
        "uuid": "01000000-0000-0000-0022-a100900c5f56",
        "is_configured": true,
        "data_offset": 0,
        "data_size": 6251233968
      },
      {
        "name": "NVMe2n1",
        "uuid": "01000000-0000-0000-0022-a100b02d5f56",
        "is_configured": true,
        "data_offset": 0,
        "data_size": 6251233968
      },
      {
        "name": "NVMe3n1",
        "uuid": "01000000-0000-0000-0022-a100c0375f56",
        "is_configured": true,
        "data_offset": 0,
        "data_size": 6251233968
      },
      {
        "name": "NVMe4n1",
        "uuid": "01000000-0000-0000-0022-a100a00f5f56",
        "is_configured": true,
        "data_offset": 0,
        "data_size": 6251233968
      }
    ]
  }
]
The log shows:
[2024-02-18 16:57:50.558610] bdev_raid.c:1357:_raid_bdev_create: *ERROR*: Unsupported raid level '95'

## Possible Solution
Some bug.

## Steps to Reproduce
1. ./build/bin/spdk_tgt -m 0xf0
2. ./scripts/rpc.py bdev_raid_create -n Raid0 -z 4 -r RAID5F -b "NVMe1n1 NVMe2n1 NVMe3n1 NVMe4n1"

## Context (Environment including OS version, SPDK version, etc.)
[root@node1 spdk]# cat /etc/os-release
NAME="openEuler"
VERSION="22.03 (LTS-SP1)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP1)"
ANSI_COLOR="0;31"

[root@node1 spdk]# uname -r
5.10.0-136.12.0.86.oe2203sp1.aarch64
aarch64
Kunpeng-920

**Comment by SWaoter** [comment]
Have you configured your SPDK with `--with-raid5f` option? You have to provide it explicitly in `./configure --with-raid5f`
