### ISSUE TITLE
[vhost] Failure on NTFS format: child_length 65472 not even multiple of lba_size 4096

### ISSUE THREAD

**Issue by arsiesys** [spdk/spdk#3269]
# Sighting report
## Expected Behavior

Windows NTFS format being successful.

## Current Behavior

Using the windows disk management Tool to format a remote nvme/bdev presented with vhost/virtio-blk on qemu fail and generate the following logs in spdk_vhost:
```
[2024-02-19 21:51:36.590228] bdev_nvme.c:7574:bdev_nvme_writev: *ERROR*: writev failed: rc = -22
[2024-02-19 21:51:37.590463] nvme_ns_cmd.c: 378:_nvme_ns_cmd_split_request_sgl: *ERROR*: child_length 65472 not even multiple of lba_size 4096
```

## Possible Solution

I noticed that I was able to format the disk using PowerShell. Also, pre-formatting the disk in NTFS on a Linux VM before presenting it to the windows 10 vm is also working.
I assume that the GUI disk management of windows is doing on extra "call" which  spdk_vhost may not like ?

## Steps to Reproduce

1. Prepare SPDK_vhost
```
mkdir /tmp/vhost
HUGEMEM=50000 PCI_ALLOWED='' /opt/spdk/scripts/setup.sh
/opt/spdk/build/bin/vhost -S /tmp/vhost -m 0x3
/opt/spdk/scripts/rpc.py bdev_nvme_attach_controller -b rdma -t rdma -a xxxx -s 4420 -n nqn.2022-02.io.spdk:cnode1 -f ipv4
/opt/spdk/scripts/rpc.py vhost_create_blk_controller vhost.1 rdman1
```
2. Create a QEMU vm using vhostuser/virtio-blk
3. Install windows 10
4. Use the disk management GUI tool to format NTFS the virti-blk disk

This can't be reproduced using a simple Malloc device on the same spdk_vhost as it does not generate the issue.

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: 24.01
Windows 10 VM is created using kubevirt (QEMU) on kubernetes and using vhostuser
virtio drivers version: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/
- One SPDK_tgt exposing a bdev (stored on a local NVME) on server A
  The SPDK_tgt is running on Ubuntu 20.04 Server
- One spdk_vhost attaching the remote bdev from server A
  The SPDK_vhost is running on Ubuntu 22.04 Server
Slack: https://spdk-team.slack.com/archives/CRXKGCCTZ/p1708380183920629

**Comment by jimharris** [comment]
> # Sighting report
> ## Expected Behavior
> Windows NTFS format being successful.
> 
> ## Current Behavior
> Using the windows disk management Tool to format a remote nvme/bdev presented with vhost/virtio-blk on qemu fail and generate the following logs in spdk_vhost:
> 
> ```
> [2024-02-19 21:51:36.590228] bdev_nvme.c:7574:bdev_nvme_writev: *ERROR*: writev failed: rc = -22
> [2024-02-19 21:51:37.590463] nvme_ns_cmd.c: 378:_nvme_ns_cmd_split_request_sgl: *ERROR*: child_length 65472 not even multiple of lba_size 4096

This means we must be getting some IO with more than 250 iovs, each of them being some odd multiple.

> ```
> 
> ## Possible Solution
> I noticed that I was able to format the disk using PowerShell. Also, pre-formatting the disk in NTFS on a Linux VM before presenting it to the windows 10 vm is also working. I assume that the GUI disk management of windows is doing on extra "call" which spdk_vhost may not like ?
> 
> ## Steps to Reproduce
> 1. Prepare SPDK_vhost
> 
> ```
> mkdir /tmp/vhost
> HUGEMEM=50000 PCI_ALLOWED='' /opt/spdk/scripts/setup.sh
> /opt/spdk/build/bin/vhost -S /tmp/vhost -m 0x3

Can you please add one more RPC here, before `bdev_nvme_attach_controller`:

```
/opt/spdk/scripts/rpc.py bdev_nvme_set_options --io-queue-requests 64
```

This will set bdev max_num_segments to 64 for the nvme bdev, and then the bdev layer will split these large iovcnt IO into smaller ones, and will be careful to make sure they are block size aligned.

Please report back if this fixes the problem. This is not really a suitable long-term fix, but will confirm where the problem is.


> /opt/spdk/scripts/rpc.py bdev_nvme_attach_controller -b rdma -t rdma -a xxxx -s 4420 -n nqn.2022-02.io.spdk:cnode1 -f ipv4
> /opt/spdk/scripts/rpc.py vhost_create_blk_controller vhost.1 rdman1
> ```
> 
>  2. Create a QEMU vm using vhostuser/virtio-blk
> 3. Install windows 10
> 4. Use the disk management GUI tool to format NTFS the virti-blk disk
> 
> This can't be reproduced using a simple Malloc device on the same spdk_vhost as it does not generate the issue.

malloc bdev has no restriction on number of iovs. So it is expected that malloc would not suffer from same issue.

> 
> ## Context (Environment including OS version, SPDK version, etc.)
> SPDK version: 24.01 Windows 10 VM is created using kubevirt (QEMU) on kubernetes and using vhostuser virtio drivers version: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/
> 
> * One SPDK_tgt exposing a bdev (stored on a local NVME) on server A
>   The SPDK_tgt is running on Ubuntu 20.04 Server
> * One spdk_vhost attaching the remote bdev from server A
>   The SPDK_vhost is running on Ubuntu 22.04 Server
>   Slack: https://spdk-team.slack.com/archives/CRXKGCCTZ/p1708380183920629

**Comment by arsiesys** [comment]
Hi !

Thanks @jimharris 
I tried the rpc call you suggested. Followed by a save_config to verify, I can confirm that the returned config is 64. However, once I attach the first nvme controller, it change to 512. 
I tried to change:
#define DEFAULT_IO_QUEUE_REQUESTS       (512)
in lib/nvme/nvme_internal.h to 64 but the result printed in save-config is 128 x_x.

In both case, the issue during the format is the same.

**Comment by jimharris** [comment]
> Hi !
> 
> Thanks @jimharris I tried the rpc call you suggested. Followed by a save_config to verify, I can confirm that the returned config is 64. However, once I attach the first nvme controller, it change to 512. I tried to change: #define DEFAULT_IO_QUEUE_REQUESTS (512) in lib/nvme/nvme_internal.h to 64 but the result printed in save-config is 128 x_x.

OK, let's just hardcode it then for this experiment. Can you try with this patch instead of the extra RPC?

https://review.spdk.io/gerrit/c/spdk/spdk/+/21952

> 
> In both case, the issue during the format is the same.

**Comment by arsiesys** [comment]
There is the updated logs output:

```
[2024-02-21 00:51:36.142494] nvme_ns_cmd.c: 378:_nvme_ns_cmd_split_request_sgl: *ERROR*: max_sges=16 num_sges=16 req->payload_size=131072 req_current_length=65472
[2024-02-21 00:51:36.142537] nvme_ns_cmd.c: 380:_nvme_ns_cmd_split_request_sgl: *ERROR*: child_length 65472 not even multiple of lba_size 4096
[2024-02-21 00:51:36.142544] bdev_nvme.c:7575:bdev_nvme_writev: *ERROR*: writev failed: rc = -22
[2024-02-21 00:51:36.142550] bdev_nvme.c:7576:bdev_nvme_writev: *ERROR*: iovcnt=28 lba_count=32
```

**Comment by jimharris** [comment]
> There is the updated logs output:
> 
> ```
> [2024-02-21 00:51:36.142494] nvme_ns_cmd.c: 378:_nvme_ns_cmd_split_request_sgl: *ERROR*: max_sges=16 num_sges=16 req->payload_size=131072 req_current_length=65472
> [2024-02-21 00:51:36.142537] nvme_ns_cmd.c: 380:_nvme_ns_cmd_split_request_sgl: *ERROR*: child_length 65472 not even multiple of lba_size 4096
> [2024-02-21 00:51:36.142544] bdev_nvme.c:7575:bdev_nvme_writev: *ERROR*: writev failed: rc = -22
> [2024-02-21 00:51:36.142550] bdev_nvme.c:7576:bdev_nvme_writev: *ERROR*: iovcnt=28 lba_count=32
> ```

Can you change the hardcoded 64 number in my test patch to 16 instead?

**Comment by arsiesys** [comment]
Thanks for your support on this issue!

Now that you point out "SGL" (which I will need to read about to understand it), I notice the following logs in the SPDK_tgt that expose the nvme bdev that is attached by the spdk_vhost.

[2024-02-21 00:59:07.602418] rdma.c:3988:nvmf_rdma_cdata_init: *WARNING*: RDMA is configured to support up to 16 SGL entries while in capsule data is greater than 4KiB.

I do not know if that's an "expected" warning or not and if it have an impact on the issue we got today.

**Comment by jimharris** [comment]
> Thanks for your support on this issue!

Can you please pull series of two patches ending here: https://review.spdk.io/gerrit/c/spdk/spdk/+/21952 and retest?
(Note, 21952 is same Gerrit ID as the earlier test patch, but there is a prep patch before it now which you will need to build.)

> 
> Now that you point out "SGL" (which I will need to read about to understand it), I notice the following logs in the SPDK_tgt that expose the nvme bdev that is attached by the spdk_vhost.
> 
> [2024-02-21 00:59:07.602418] rdma.c:3988:nvmf_rdma_cdata_init: _WARNING_: RDMA is configured to support up to 16 SGL entries while in capsule data is greater than 4KiB.

This is unrelated, but you still need to pay attention to it. There should be another WARNLOG right after this one that says you can hit data corruption with certain versions of the Linux kernel NVMe-oF initiator.

> I do not know if that's an "expected" warning or not and if it have an impact on the issue we got today.

**Comment by arsiesys** [comment]
I did a test with a branch that had the commits:
```
git fetch https://review.spdk.io/gerrit/spdk/spdk refs/changes/52/21952/3 && git checkout FETCH_HEAD
```
d394a0596607d88c63e4fa0cd2d59a75676aa0ae bdev/nvme: set max_num_segments based on controller limit
c2dffb1922031280cddf1feb25e7394113b0d3f6 nvme: add spdk_nvme_ctrlr_get_max_sges

The format did works as expected and a basic bench write/read on the disk (form the OS) was working with similar performance numbers.

Thanks again for your support on this.

**Comment by jimharris** [comment]
Patch merged.
