### ISSUE TITLE
Support specification of namespace uuid via nvmf config file

### ISSUE THREAD

**Issue by akshorcl** [spdk/spdk#327]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Provide support for specifying a per-namespace uuid via the nvmf config file and via the RPC framework.

## Expected Behavior

We would like the ability to specify a user defined per-namespace uuid via the nvmf config file and this uuid would be query-able.

## Current Behavior
The NVMe-oF target currently uses the UUID provided by the bdevs backing each namespace as the NS UUID.

**Comment by johnmeneghini** [comment]
Is anyone working on this?

I have a patch to fix this problem.

**Comment by akshorcl** [comment]
Daniel might be working on this. Let's sync up with him.

**Comment by dverkamp-intel** [comment]
The JSON-RPC support for this has already been checked in as commit 57ae6bf646e6aaddf621fca007edfc7d937f92f6.  However, there is no configuration file support for it yet.

John, if you have patches for this, please go ahead and post them; otherwise I'll put together a proposed patch to add this to the config file parsing (lib/event/subsystems/nvmf/conf.c).

**Comment by dverkamp-intel** [comment]
The patch turned out to be quite simple, so I went ahead and posted it: https://review.gerrithub.io/#/c/spdk/spdk/+/414681

**Comment by akshorcl** [comment]
Let me test this out and will get back to you.

**Comment by akshorcl** [comment]
Thanks!

**Comment by dverkamp-intel** [comment]
@akshorcl, any update on the testing? This has been merged as commit 194d6af65db462541368ab8f83b31c8eccdfeabd, but I want to verify it works for you.

**Comment by akshorcl** [comment]
Thanks! Your change is fine and the uuid is available via spdk_nvme_ns. We were hoping to encode the PCIe addr via the user specified uuid so that will need some more work. Since the specification defines it as a uuid, we are limited to that.
