### ISSUE TITLE
NVMe-oF Authentication: DH-HMAC-CHAP Protocol (TP-8806)

### ISSUE THREAD

**Issue by glimchb** [spdk/spdk#3278]
We are starting to implement it in SPDK

backlog item link: https://trello.com/c/ibBiI9cR

linux kernel reference to test with:
- https://elixir.bootlin.com/linux/v6.6/source/drivers/nvme/target/auth.c
- https://elixir.bootlin.com/linux/v6.6/source/drivers/nvme/host/auth.c

**Comment by glimchb** [comment]
I see @ksztyber already posted patches last week https://review.spdk.io/gerrit/q/status:open+auth

**Comment by jimharris** [comment]
Summarizing some conversations on Slack and today's community meeting:

Patches from @ksztyber are for initiator side. He is starting to look at target side.
@glimchb says Dell is just starting this work.
A team at Samsung has also been working on target auth, and just received approval to start contributions upstream.

Samsung, Intel and Dell will continue discussions offline on next steps for collaboration on this.

**Comment by jimharris** [comment]
@ksztyber is going to continue with his patch set to implement target auth as well.  Dell and Samsung will focus on reviews and testing.

Secure channel concatenation (i.e. using generated auth key for TLS) is still TBD.

**Comment by jimharris** [comment]
@ksztyber @glimchb we can close this now?

**Comment by glimchb** [comment]
I'm ok closing this since @ksztyber implemented this feature and delivered to master

**Comment by jimharris** [comment]
Feature completed, thanks @ksztyber!
