### ISSUE TITLE
add_vhost_scsi_lun: dynamically allocate target (and LUN?)

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#328]
This is similar to #324: when a program tries to attach a BDev to some existing vhost SCSI controller, then it has to choose a target. But the program cannot find out which targets are available and even if it could, picking an unused one would lead to a race.

## Expected Behavior

-1 (or MAX_UINT32?) for scsi_target_num should cause app/vhost to allocate an unused target. The response then must include the actual target (currently it is just a boolean). Suitable, documented errors must be returned to signal "no target available".

## Current Behavior

Caller must choose target.

**Comment by pawelwod** [comment]
My state is the same as in #324 and also kernel vhost target interface (see targetcli utility) require to choose Target/LUN explicitly.

**Comment by pohly** [comment]
Slight correction: it looks like `add_vhost_scsi_lun` (despite the name) adds a *SCSI target*, not a *LUN*. Correct?

The underlying issue still remains the same, though: can the call itself choose an available SCSI target number?

**Comment by pohly** [comment]
@pawelwod explained on IRC that only one LUN is supported per target, so `add_vhost_scsi_lun` adds a new target and a LUN for that target at once.

**Comment by pohly** [comment]
He also explained that there is a maximum number of targets built in at compile time (vhost_internal.h, `#define SPDK_VHOST_SCSI_CTRLR_MAX_DEVS 8`).

**Comment by darsto** [comment]
We have a backlog trello item to support multiple LUNs per SCSI
target: https://trello.com/c/VQpj9shl/10-support-multiple-luns-per-target
Can this issue be closed?

**Comment by pohly** [comment]
No, multiple LUNs is a different issue. Once SPDK supports multiple LUNs, the same issue arises: when LUNs need to be allocated dynamically, then it is better done inside the server than the client.

**Comment by jimharris** [comment]
So to summarize, this issue covers:

1) passing -1 should indicate that SPDK application should choose a free target ID
2) on success, return the selected target ID
3) on failure, return clear message indicating "target ID not available" (this message should be used also if user selects an unavailable target ID)

@pohly - please clarify if there's anything I'm missing.  Wanted to spell out these steps for whoever is assigned this issue.

**Comment by pohly** [comment]
@jimharris this covers it.

How to return that error message needs to be defined in more detail. Probably needs to be worked on in combination with https://github.com/spdk/spdk/issues/319

**Comment by changpe1** [comment]
Bug Scrub: Pawel already work on it, so removing the bug scrub label for now.

**Comment by pawelwod** [comment]
Hi @pohly,
Here is a patch you can try https://review.gerrithub.io/#/c/spdk/spdk/+/442434/
