### ISSUE TITLE
LSAN detects memory leaks while running long vfio i nvmf fuzzing tests

### ISSUE THREAD

**Issue by m-spiewak** [spdk/spdk#3285]
If detect_leaks is set to 1 in start_fuzzer() function (test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c and test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c), leak sanitizer sometimes detects leaks in two places:
1) spdk_nvmf_qpair_disconnect() function
```
=================================================================
==1239102==ERROR: LeakSanitizer: detected memory leaks
 
Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x51f787 in __interceptor_calloc (/home/mspiewak/spdk_fuzzer/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz+0x51f787) (BuildId: 2ba667a8acf33a4a11c6f5c4597deed96902dbb2)
    #1 0x143eacf in spdk_nvmf_qpair_disconnect /home/mspiewak/spdk_fuzzer/lib/nvmf/nvmf.c:1442:14
    #2 0x15fb348 in _vfio_user_qpair_disconnect /home/mspiewak/spdk_fuzzer/lib/nvmf/vfio_user.c:4861:2
    #3 0x1e7705e in msg_queue_run_batch /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:848:3
    #4 0x1e2155d in thread_poll /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:1070:14
    #5 0x1e20a45 in spdk_thread_poll /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:1163:8
    #6 0x1abe23a in _reactor_run /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:914:8
    #7 0x1aafc03 in reactor_run /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:952:4
    #8 0x1aaf37e in spdk_reactors_start /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:1068:2
    #9 0x1a83d85 in spdk_app_start /home/mspiewak/spdk_fuzzer/lib/event/app.c:866:2
    #10 0x56318c in main /home/mspiewak/spdk_fuzzer/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:694:7
    #11 0x7f1b9044a50f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2750f) (BuildId: 765237b0355c030ff41d969eedcb87bfccb43595)
 
Objects leaked above:
0x6040000b1710 (48 bytes)
```

According to LSAN, memory allocated for 

> qpair_ctx = calloc(1, sizeof(struct nvmf_qpair_disconnect_ctx));

structure is lost

2) nvmf_ctrlr_create() function

```
=================================================================
==1838166==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4920 byte(s) in 1 object(s) allocated from:
    #0 0x51f787 in __interceptor_calloc (/home/mspiewak/spdk_fuzzer/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz+0x51f787) (BuildId: 774b0cb60bee70cc090299cf03b067a50865f668)
    #1 0x1303585 in nvmf_ctrlr_create /home/mspiewak/spdk_fuzzer/lib/nvmf/ctrlr.c:377:10
    #2 0x129191c in _nvmf_ctrlr_connect /home/mspiewak/spdk_fuzzer/lib/nvmf/ctrlr.c:856:11
    #3 0x134f90e in nvmf_ctrlr_cmd_connect /home/mspiewak/spdk_fuzzer/lib/nvmf/ctrlr.c:986:9
    #4 0x12f3702 in nvmf_ctrlr_process_fabrics_cmd /home/mspiewak/spdk_fuzzer/lib/nvmf/ctrlr.c:3714:11
    #5 0x12f293d in spdk_nvmf_request_exec_fabrics /home/mspiewak/spdk_fuzzer/lib/nvmf/ctrlr.c:4540:11
    #6 0x159445c in nvmf_vfio_user_poll_group_add /home/mspiewak/spdk_fuzzer/lib/nvmf/vfio_user.c:5252:2
    #7 0x14ad0ec in nvmf_transport_poll_group_add /home/mspiewak/spdk_fuzzer/lib/nvmf/transport.c:701:9
    #8 0x1441456 in spdk_nvmf_poll_group_add /home/mspiewak/spdk_fuzzer/lib/nvmf/nvmf.c:1213:9
    #9 0x143facb in _nvmf_poll_group_add /home/mspiewak/spdk_fuzzer/lib/nvmf/nvmf.c:1129:6
    #10 0x1e7705e in msg_queue_run_batch /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:848:3
    #11 0x1e2155d in thread_poll /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:1070:14
    #12 0x1e20a45 in spdk_thread_poll /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:1163:8
    #13 0x1abe23a in _reactor_run /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:914:8
    #14 0x1aafc03 in reactor_run /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:952:4
    #15 0x1aaf37e in spdk_reactors_start /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:1068:2
    #16 0x1a83d85 in spdk_app_start /home/mspiewak/spdk_fuzzer/lib/event/app.c:866:2
    #17 0x56318c in main /home/mspiewak/spdk_fuzzer/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:694:7
    #18 0x7f5d9104a50f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2750f) (BuildId: 765237b0355c030ff41d969eedcb87bfccb43595)

Objects leaked above:
0x6220000d5100 (4920 bytes)

```
According to LSAN, memory allocated for

> ctrlr = calloc(1, sizeof(*ctrlr));

structure is lost

Compiling code for fuzzing tests:
```
cd spdk
CC=clang CXX=clang++ ./configure --enable-debug --enable-asan --enable-ubsan --enable-coverage --with-vfio-user --with-fuzzer="/usr/lib64/clang/15/lib/libclang_rt.fuzzer_no_main-x86_64.a
CC=clang CXX=clang++ make -j
```

Running vfio test:

```
cd spdk/test/fuzz/llvm/vfio
sudo ./run.sh <test_function_number>
```
Running nvmf test:
```
cd spdk/test/fuzz/llvm/nvmf
sudo ./run.sh <test_function_number>
```
where <test_function_number> is 0..6 for vfio and 0...25 for nvmf

**Comment by jimharris** [comment]
This is interesting. When is the memory leak detected? at the end of the test run, or at the end of one specific iteration of the fuzzer?

**Comment by m-spiewak** [comment]
For this qpair_ctx the situation was very similar - pritnfs show that the memory is freed, and the LSAN detects a leak:
```
[A1] 0x6040000b1610
[F2] 0x6040000b1610
[A1] 0x6040000b1710
[F2] 0x6040000b1710
 
=================================================================
==1239102==ERROR: LeakSanitizer: detected memory leaks
 
Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x51f787 in __interceptor_calloc (/home/mspiewak/spdk_fuzzer/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz+0x51f787) (BuildId: 2ba667a8acf33a4a11c6f5c4597deed96902dbb2)
    #1 0x143eacf in spdk_nvmf_qpair_disconnect /home/mspiewak/spdk_fuzzer/lib/nvmf/nvmf.c:1442:14
    #2 0x15fb348 in _vfio_user_qpair_disconnect /home/mspiewak/spdk_fuzzer/lib/nvmf/vfio_user.c:4861:2
    #3 0x1e7705e in msg_queue_run_batch /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:848:3
    #4 0x1e2155d in thread_poll /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:1070:14
    #5 0x1e20a45 in spdk_thread_poll /home/mspiewak/spdk_fuzzer/lib/thread/thread.c:1163:8
    #6 0x1abe23a in _reactor_run /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:914:8
    #7 0x1aafc03 in reactor_run /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:952:4
    #8 0x1aaf37e in spdk_reactors_start /home/mspiewak/spdk_fuzzer/lib/event/reactor.c:1068:2
    #9 0x1a83d85 in spdk_app_start /home/mspiewak/spdk_fuzzer/lib/event/app.c:866:2
    #10 0x56318c in main /home/mspiewak/spdk_fuzzer/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:694:7
    #11 0x7f1b9044a50f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2750f) (BuildId: 765237b0355c030ff41d969eedcb87bfccb43595)
 
Objects leaked above:
0x6040000b1710 (48 bytes)
```

**Comment by m-spiewak** [comment]
I had some discussion with @sberbz , and we decided to create Github issue to keep track of it and have a place where we can further discuss this.

**Comment by m-spiewak** [comment]
> The disconnect path on target side is asynchronous. So my guess is that initiator side completes its iteration, target side has not executed the deferred function yet, and the fuzzer reports the leak before that deferred function gets a chance to run.

Sebastian and me had similar thoughts on this, this can be due to deferred free, so it is not counted properly before the sanitizer does the check. Why this sometimes pops up, and sometimes not, this is unclear.
I will add these delays and will check if this changes anything.

**Comment by sberbz** [comment]
`[2024-02-29 17:09:11.421447] vfio_user.c:3097:vfio_user_log: *ERROR*: /tmp/vfio-user-6/domain/1: msg0: cmd 8 failed: Invalid argument
[2024-02-29 17:09:11.421500] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 8 return failure
calloc1(0x6040000def10)
free(0x6040000def10)
free ctrlr1(0x6220000af900)

=================================================================
==281977==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x4a4682 in __interceptor_calloc (/home/sbrzezin/spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz+0x4a4682)
    #1 0x11e3d51 in spdk_nvmf_qpair_disconnect /home/sbrzezin/spdk/lib/nvmf/nvmf.c:1431:14
    #2 0x136b064 in _vfio_user_qpair_disconnect /home/sbrzezin/spdk/lib/nvmf/vfio_user.c:4861:2
    #3 0x1adc1a3 in msg_queue_run_batch /home/sbrzezin/spdk/lib/thread/thread.c:848:3
    #4 0x1a90e2d in thread_poll /home/sbrzezin/spdk/lib/thread/thread.c:1070:14
    #5 0x1a9046d in spdk_thread_poll /home/sbrzezin/spdk/lib/thread/thread.c:1163:8
    #6 0x1798e14 in _reactor_run /home/sbrzezin/spdk/lib/event/reactor.c:914:8
    #7 0x178c31d in reactor_run /home/sbrzezin/spdk/lib/event/reactor.c:952:4
    #8 0x178bb58 in spdk_reactors_start /home/sbrzezin/spdk/lib/event/reactor.c:1068:2
    #9 0x1765c2c in spdk_app_start /home/sbrzezin/spdk/lib/event/app.c:866:2
    #10 0x4d6732 in main /home/sbrzezin/spdk/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz.c:694:7
    #11 0x7fcbf90f4d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

Objects leaked above:
0x6040000def10 (48 bytes)

SUMMARY: AddressSanitizer: 48 byte(s) leaked in 1 allocation(s).`

I put `spdk_delay_us(1000);` before `free(qpair_ctx);` and it doesn't work for me.

**Comment by m-spiewak** [comment]
But this shall increase the chances for reproduction. I.e. you should be able get the false leak detection sooner, and every time the test is run.

**Comment by m-spiewak** [comment]
Ok. So there is no difference....

**Comment by jimharris** [comment]
Let's add a longer delay then. I'd really like to prove definitively that this is the problem.

**Comment by m-spiewak** [comment]
I did a series of vfio fuzzer tests (9 runs) with 100 ms delay before qpair_ctx (48 bytes) was freed. Every time I ran the test I got reproduction within 10 minutes since start. Sometimes it took 1 min to detect leak, sometimes 10 min, but 9/9 tests failed with leak detected.
Will also check if delay in freeing of ctrlr structure will speed up detection of the second leak (4920 bytes)

**Comment by sberbz** [comment]
Hi everyone 
At this point, I'm certain that this leak is a false positive, but I'm still not certain why it occurs. It may be due to an async operation or some internal LSan bug, but either is true; we can only suppress it. 

Here is a patch from Marcin:
https://review.spdk.io/gerrit/c/spdk/spdk/+/22157
And here is my proposal: 
https://review.spdk.io/gerrit/c/spdk/spdk/+/22226

Both of them have issues, but right now I cannot find a better solution.

**Comment by sberbz** [comment]
Hi @jimharris Could you, take a look at those patches ? Nothing new comes to my mind, either way, this fake leak need to be suppressed. And at this point, I'm pretty sure that this is a false positive.

**Comment by jimharris** [comment]
> Hi @jimharris Could you, take a look at those patches ? Nothing new comes to my mind, either way, this fake leak need to be suppressed. And at this point, I'm pretty sure that this is a false positive.

I prefer the 22226 approach, since it only does suppression for this specific test, instead of doing it globally.

What happens if you put a `spdk_delay_us(100);` at the end of `TestOneInput()`? Ideally we could wait just a bit in that function to give the target side time to free those objects. 100us should be plenty of time since we aren't sending any more I/O at this point. The only question is how much that impacts the test throughput - if it significantly reduces the number of iterations run per second, then we should just move forward with 22226.

**Comment by sberbz** [comment]
I tried putting spdk_delay_us(100); at the end of TestOneInput(), and leak still happen from time to time, also I tried to increase delay with same result. I double-checked it today and with 100us delay I hit leak report in the first minute of testing.

**Comment by jimharris** [comment]
> I tried putting spdk_delay_us(100); at the end of TestOneInput(), and leak still happen from time to time, also I tried to increase delay with same result. I double-checked it today and with 100us delay I hit leak report in the first minute of testing.

OK, thanks for checking this @sberbz.

**Comment by tomzawadzki** [comment]
[Bug scrub] @sberbz Will take a further look on the cause of the leak, since even with the delays the issue was occuring - rising concern this is not just an issue with LSAN.

**Comment by sberbz** [comment]
I retested this once again, and I'm convinced that every resource was released correctly, so it's highly unlikely that the leak found by LSAN is valid.

Here is a patch that adds prints on malloc and free, and it shows that the leak was only reported after the object was freed. https://review.spdk.io/gerrit/c/spdk/spdk/+/22109
Adding a delay reduces the reproduction frequency, but I cannot eliminate it or make it reproduce every time. 

I believe that issue can be closed, because the next thing that can be done is to debug LSAN, especially since we made sure there was no memory leak.
