### ISSUE TITLE
remove_ns call on a subsystem used by a raid1 will nulllify the uuid in the base_bdevs_list

### ISSUE THREAD

**Issue by arsiesys** [spdk/spdk#3286]
# Sighting report

In the case of a raid1 composed of two bdevs
- one local disk (disk1n1)
- one remote disk attached by NvmeOF RDMA (bdev_auto_examine set to false on that remote SPDK) (18disk1n1)

If, on the remote SPDK, I use the rpc call nvmf_subsystem_remove_ns to remove the ns presenting the disk to the SPDK handling the raid1, the base_bdev_lists will see the remote bdev get null values:

```
./scripts/rpc.py bdev_raid_get_bdevs all
[
  {
    "name": "test",
    "uuid": "271e4729-d8c4-4922-8b1b-112c607e647c",
    "strip_size_kb": 0,
    "state": "online",
    "raid_level": "raid1",
    "superblock": true,
    "num_base_bdevs": 2,
    "num_base_bdevs_discovered": 1,
    "num_base_bdevs_operational": 1,
    "base_bdevs_list": [
      {
        "name": "disk1n1",
        "uuid": "00000000-0000-0001-00a0-7522422d4868",
        "is_configured": true,
        "data_offset": 256,
        "data_size": 781403990
      },
      {
        "name": null,
        "uuid": "00000000-0000-0000-0000-000000000000",
        "is_configured": false,
        "data_offset": 256,
        "data_size": 781403990
      }
    ]
  }
]
```
In that situation, the raid can't be re-assembled without removing and re-adding the base_bdev (and then trigger a rebuild).

## Expected Behavior

I would have expected that the superblock data to be still looking for the uuid that was known before the remove_ns rpc call on the second SPDK. Ideally, until the ns/disk is back/re-add, the raid shouldn't show an "online" status but it's probably a different matter.

## Current Behavior

The uuid of the disk in the superblock seems to be now looking for the uuid 00000000-0000-0000-0000-000000000000

## Steps to Reproduce

SPDK A (handling the raid1):
- ./scripts/rpc.py bdev_nvme_attach_controller -b 18disk1 -t rdma -a 192.168.1.1 -s 4420 -n nqn.2024-02.io.raid:18disk1 -f ipv4
- ./scripts/rpc.py bdev_raid_create -n test -r raid1 -b "disk1n1 18disk1n1" -s

SPDK B:
- ./scripts/rpc.py nvmf_subsystem_remove_ns nqn.2024-02.io.raid:18disk1 1

## Context (Environment including OS version, SPDK version, etc.)

SPDK master b1cb73612a2ddaf948d4c588f14da6326b274381
Ubuntu 22.04.4 / 6.5.0-21-generic

**Comment by apaszkie** [comment]
Re-adding a removed base bdev needs to be fixed, currently it doesn't get added to the array because it has an outdated superblock and this is not handled correctly yet. But even then, this will require a rebuild to be performed on the added disk because its data may not be in sync with the rest of the array.

**Comment by arsiesys** [comment]
I got an other situation where this occur:

In a set of raid1 volume including an external attached one:
./scripts/rpc.py bdev_nvme_attach_controller -b 18disk1 -t tcp -a 192.168.1.1 -s 4420 -n nqn.2024-02.io.raid:18disk1 -f ipv4 -u 30 -l 60 -o 10

if I, on purpose (test) break the link with this remote attached volume, once we reach the CTRLR_LOSS_TIMEOUT_SEC of 60s, the controller (attached) is "removed" and the disk become "null" as in the first post. As a consequence, the RAID is not usable anymore because we can't replace or remove this "null" bdev ?

Is there a way to remove this null bdev so the raid is "unblocked" or the datas may be considered as lost in that situation due to an incorrect superblock state ?

**Comment by apaszkie** [comment]
The "null bdev" is simply an empty base bdev slot - the bdev is already removed. It should be possible to use raid_bdev_add_base_bdev RPC to add a bdev into this slot, starting rebuild. Doesn't this work for you?
________________________________
