### ISSUE TITLE
RPC: list existing LUNs

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#329]
It would be useful to query which LUNs are configured for a vhost SCSI controller and what their parameters are.

## Possible Solution

`get_vhost_scsi_luns -> [] (scsi_target_num, bdev_name)`

**Comment by pawelwod** [comment]
There are commands in rpc.py:
1. get_vhost_controllers - this will list controllers along with LUNS.
2. get_subsystem_config - will output subsystem configuration eg: vhost in the same form as used to construct complete vhost SCSI controller. This is undocumented yet as it is under development.

**Comment by pohly** [comment]
What is the output format of `get_subsystem_config`? If it is JSON or something similar which can be parsed easily on the client side, then the call sounds like one possible solution for this issue. It's not quite aligned with the other query functions, though.

**Comment by dverkamp-intel** [comment]
I don't think parsing the output of `get_subsystem_config` is something we want to encourage - it should be purely a way to round-trip configuration automatically, not a stable API that automation should be using.

If there is more information that would be useful from the vhost target that isn't already in `get_vhost_controllers`, I think we should be able to add it either as additional response data from an existing RPC method or as a new RPC method.

**Comment by dverkamp-intel** [comment]
Here's example output of `get_vhost_controllers` for a vhost-scsi controller from one of the automated tests:

~~~
[
  {
    "cpumask": "0x1", 
    "backend_specific": {
      "scsi": [
        {
          "target_name": "Target 0", 
          "luns": [
            {
              "id": 0, 
              "bdev_name": "0ebb2b2f-81bf-45c9-9995-c43f103fed02"
            }
          ], 
          "id": 0, 
          "scsi_dev_num": 0
        }
      ]
    }, 
    "ctrlr": "naa.0.0"
  }
]
~~~

**Comment by pohly** [comment]
`get_vhost_controllers` has the right amount of information. It's not documented, but that's already tracked by #267, so let's close this issue here.

**Comment by pohly** [comment]
FYI, handling the "backend_specific" result in Go required manual code because the Go JSON decoder cannot be told what structs to create for backend type "scsi". I suspect this kind of result type will also be hard to describe in a JSON schema.

**Comment by pawelwod** [comment]
@dverkamp-intel 

> I don't think parsing the output of get_subsystem_config is something we want to encourage - it should be purely a way to round-trip configuration automatically, not a stable API that automation should be using.

This will be as stable as RPC API.

@pohly 
Try get_subsystem_config - we use this to save and later restore vhost (and other targets) configuration.
Each entry in config array is one JSON RPC call. See https://github.com/spdk/spdk/blob/9f697e0fe24aa35a805e974de2b1d33eacc8721a/scripts/rpc/__init__.py#L31 and https://github.com/spdk/spdk/blob/9f697e0fe24aa35a805e974de2b1d33eacc8721a/scripts/rpc/__init__.py#L59

This should look like:
`./scripts/rpc.py get_subsystem_config vhost
[
   {
      "subsystem": "vhost", 
      "config": [
        {
          "params": {
            "cpumask": "1", 
            "ctrlr": "SCSI_CTRL_NAME_3"
          }, 
          "method": "construct_vhost_scsi_controller"
        }, 
        {
          "params": {
            "scsi_target_num": 1, 
            "bdev_name": "BDEV_NAME_1", 
            "ctrlr": "SCSI_CTRL_NAME_3"
          }, 
          "method": "add_vhost_scsi_lun"
        }, 
        {
          "params": {
            "scsi_target_num": 2, 
            "bdev_name": "BDEV_NAME_2", 
            "ctrlr": "SCSI_CTRL_NAME_3"
          }, 
          "method": "add_vhost_scsi_lun"
        }, 
        {
          "params": {
            "dev_name": "BDEV_NAME_3", 
            "readonly": false, 
            "ctrlr": "SCSI_CTRL_NAME_4", 
            "cpumask": "1"
          }, 
          "method": "construct_vhost_blk_controller"
        }
      ]
    }
]
`
