### ISSUE TITLE
[nvmf_fio_host] fail during bdev_lvol_delete

### ISSUE THREAD

**Issue by xjjx** [spdk/spdk#3295]
# CI Intermittent Failure

## Link to the failed CI build
https://ci.spdk.io/public_build/autotest-nightly_3438.html

## Execution failed at

> 00:30:05.938  ========== Backtrace start: ==========
> 00:30:05.938  
> 00:30:05.938  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/common/autotest_common.sh:577 -> rpc_cmd(["bdev_lvol_delete"],["lvs_n_0/lbd_nest_0"])
> 00:30:05.938       ...
> 00:30:05.938     572 			echo "$rsp"
> 00:30:05.938     573 		done
> 00:30:05.938     574 	
> 00:30:05.938     575 		rc=${!status[*]}
> 00:30:05.938     576 		xtrace_restore
> 00:30:05.938  => 577 		[[ $rc == 0 ]]
> 00:30:05.938     578 	}
> 00:30:05.938     579 	
> 00:30:05.938     580 	function rpc_cmd_simple_data_json() {
> 00:30:05.938     581 	
> 00:30:05.938     582 		local elems="$1[@]" elem
> 00:30:05.938       ...
> 00:30:05.938  in /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/host/fio.sh:74 -> main(["--transport=tcp"])
> 00:30:05.938       ...
> 00:30:05.938     69  		traddr=$NVMF_FIRST_TARGET_IP trsvcid=$NVMF_PORT ns=1" --bs=4096
> 00:30:05.938     70  		$rpc_py nvmf_delete_subsystem nqn.2016-06.io.spdk:cnode3
> 00:30:05.938     71  	
> 00:30:05.938     72  		sync
> 00:30:05.938     73  		# Delete lvol_bdev and destroy lvol_store.
> 00:30:05.938  => 74  		$rpc_py bdev_lvol_delete lvs_n_0/lbd_nest_0
> 00:30:05.938     75  		$rpc_py bdev_lvol_delete_lvstore -l lvs_n_0
> 00:30:05.938     76  		$rpc_py bdev_lvol_delete lvs_0/lbd_0
> 00:30:05.938     77  		$rpc_py bdev_lvol_delete_lvstore -l lvs_0
> 00:30:05.938     78  		$rpc_py bdev_nvme_detach_controller Nvme0
> 00:30:05.938     79  	fi
> 00:30:05.938       ...
> 00:30:05.938  
> 00:30:05.938  ========== Backtrace end ==========
>

**Comment by xjjx** [comment]
Another instance of this issue: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v23.11_319.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3700.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1830.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1841.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1885.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3616.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v22.11_1954.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3618.html

**Comment by mchomnic** [comment]
the error still occurs, reopening.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1961.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v23.11_45.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v22.11_566.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v23.11_53.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3852.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_1971.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3629.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v22.11_567.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v23.11_589.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v22.11_1986.html

**Comment by tomzawadzki** [comment]
[Bug scrub] @jchachux The issue seems to still be occurring on master (see nightly builds above). Could you check out if the fix is working as expected ?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v23.11_595.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_596.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3661.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v22.11_93.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_607.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_2013.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3672.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v22.11_2008.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v22.11_609.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3676.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v22.11_109.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3912.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3915.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v22.11_115.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v22.11_632.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_631.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v22.11_2042.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v23.11_129.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3707.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v22.11_130.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3935.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.01-LTS-vs-dpdk-v23.11_645.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3937.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly-lts_2059.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v22.11_149.html
