### ISSUE TITLE
VHost: identify block device inside QEMU

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#330]
Suppose a VHost SCSI target gets added dynamically to a running QEMU. The Linux kernel in the guest will notice that and provide a new /dev/sd* entry. Now suppose that some app inside the virtual machine is asking for the creation of these devices (via some way of remote controlling SPDK) and then wants to detect that a certain /dev/sd* entry is really the device it is waiting for.

It could make assumptions (like "the next new device is for me"), but that's a bit fragile. Can we expose some string chosen by the app via the VHost interface, for example as the "vendor" string (/sys/block/sda/device/vendor)? Currently that seems to be hard-coded to "INTEL". "model" seems to be based on the BDev type (e.g. "Malloc disk").

Same for VHost block.

## Possible Solution

Add a "vendor" parameter to the spdk_vhost_blk_construct and spdk_vhost_scsi_dev_add_tgt RPC calls.

**Comment by pohly** [comment]
pawelwod <notifications@github.com> writes:
> So this app could wait for kernel message that new device is hot-added
> or can poll for neew device in /dev or /sys folder.

Suppose the app is a storage driver which services two different apps X
and Y which ask for exposing two existing volumes A and B, both of
the same size but backed by different remote storage volumes with some
existing content. When /dev/sda and /dev/sdb appear, how does the
storage driver know which device is for A and which one for B?

The driver cannot distinguish them without additional meta data. It also
can't just mount them and give both to the apps, because volume A for
app X might contain confidential data that app Y is not supposed to see.

> Also you can force
> well known fixed PCI address for virtio controller so you know that
> all devices from this controller are for you. See
> http://www.spdk.io/doc/vhost.html#vhost_example to see to how figure
> out what is what.

This doesn't help with the issue above, because both devices would show
up at the same controller.

**Comment by pawelwod** [comment]
You can see that this controller have two LUNs
```
guest:~# lsblk --output "NAME,KNAME,MODEL,HCTL,SIZE,VENDOR,SUBSYSTEMS"
NAME   KNAME MODEL            HCTL         SIZE VENDOR   SUBSYSTEMS
sdb    sdb   NVMe disk        2:0:0:0    372,6G INTEL    block:scsi:virtio:pci
sdc    sdc   Malloc disk      2:0:1:0      128M INTEL    block:scsi:virtio:pci
```

Now look at `HCTL` column. You have `2:0:0:0` and `2:0:1:0` Last two digits are Target ID and LUN ID. The same info is available in sysfs, `udevadm info /dev/sdX`, `lsscsi` or by reading`/proc/scsi/scsi`.

As only one LUN per target is supported LUN id will always be 0, but Target ID is passed when adding LUN via RPC `add_vhost_scsi_lun CTRL_NAME  TARGET_ID BDEV_NAME`.

**Comment by pohly** [comment]
@pawelwod something is still missing: how can I ensure that the block device is from the right SCSI controller? I can't just compare the host:channel part (the 2:0 in the example above) because it is unknown how the kernel enumerates the hosts.

On the QEMU side, I set up the device with:
```
   -device vhost-user-scsi-pci,id=scsi0,chardev=vhost0,bus=pci.0,addr=0x15
```

This shows up in the VM as:
```
# ls -l /sys/dev/block/
...
lrwxrwxrwx 1 root root 0 Jun 20 08:52 8:0 -> ../../devices/pci0000:00/0000:00:15.0/virtio3/host0/target0:0:1/0:0:1:0/block/sda
```

Is it safe to make the following assumptions?
1. the `/sys/dev/block` directory and the symlinks in it are part of the Linux kernel API and thus won't change
2. `bus=pci.0` maps to `pci0000:00/0000:00:`
3. `addr=0x15` maps to `15.0`

Then finding the right block device can be done with a substring match: any entry in `/sys/dev/block` whose symlink target contains `/pci0000:00/0000:00:15.0/` and `:x:0/block' (for SCSI target `x`) must be the desired block device. This finds the block device itself as well as partitions on it.

**Comment by darsto** [comment]
On Wed, Jun 20, 2018 at 11:01 AM Patrick Ohly <notifications@github.com>
wrote:

> @pawelwod <https://github.com/pawelwod> something is still missing: how
> can I ensure that the block device is from the right SCSI controller? I
> can't just compare the host:channel part (the 2:0 in the example above)
> because it is unknown how the kernel enumerates the hosts.
>
> On the QEMU side, I set up the device with:
>
>    -device vhost-user-scsi-pci,id=scsi0,chardev=vhost0,bus=pci.0,addr=0x15
>
> This shows up in the VM as:
>
> # ls -l /sys/dev/block/
> ...
> lrwxrwxrwx 1 root root 0 Jun 20 08:52 8:0 -> ../../devices/pci0000:00/0000:00:15.0/virtio3/host0/target0:0:1/0:0:1:0/block/sda
>
> Is it safe to make the following assumptions?
>
>    1. the /sys/dev/block directory and the symlinks in it are part of the
>    Linux kernel API and thus won't change
>    2. bus=pci.0 maps to pci0000:00/0000:00:
>    3. addr=0x15 maps to 15.0
>
> Then finding the right block device can be done with a substring match:
> any entry in /sys/dev/block whose symlink target contains
> /pci0000:00/0000:00:15.0/ and :x:0/block' (for SCSI targetx`) must be the
> desired block device. This finds the block device itself as well as
> partitions on it.
>

Yes. In fact we already do such thing in setup.sh script to detect if a PCI
virtio device doesn't have any mountpoints on its block devices before we
unbind it from the kernel virtio driver. `get_virtio_names_from_bdf` is the
function if you want to look it up.

Also, you can specify your own buses in QEMU with custom bus numbers. You
can also create PCIe buses for Q35 machines.
D.

**Comment by pohly** [comment]
I've implemented this approach and it seems to work well enough. Let's close this issue.
