### ISSUE TITLE
rbd_open hang

### ISSUE THREAD

**Issue by faicker** [spdk/spdk#3308]
# Sighting report

rbd_open hang.

## Context (Environment including OS version, SPDK version, etc.)
ubuntu 22.04
ceph 18.2.2
SPDK v24.01-pre git sha1 dc93bd859

The hang thread backtrace,
Thread 1 (Thread 0x7f2c01fca980 (LWP 224802) "reactor_1"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7ffd63b83bb8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x7ffd63b83bb8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7ffd63b83bb8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f2c03a0da41 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7ffd63b83b68, cond=0x7ffd63b83b90) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x7ffd63b83b90, mutex=0x7ffd63b83b68) at ./nptl/pthread_cond_wait.c:627
#5  0x00007f2c03cea4f3 in std::condition_variable::wait<C_SaferCond::wait()::{lambda()#1}>(std::unique_lock<std::mutex>&, C_SaferCond::wait()::{lambda()#1}) (__p=..., __lock=..., this=0x7ffd63b83b90) at /usr/include/c++/11/condition_variable:103
#6  C_SaferCond::wait (this=0x7ffd63b83b60) at ./src/common/Cond.h:100
#7  librbd::ImageState<librbd::ImageCtx>::open (this=0x55d5f60c5f10, flags=0) at ./src/librbd/ImageState.cc:478
#8  0x00007f2c03cb85ee in rbd_open (p=<optimized out>, name=<optimized out>, image=image@entry=0x55d5f609baa8, snap_name=snap_name@entry=0x0) at ./src/librbd/librbd.cc:4734
#9  0x000055d5f3a945a7 in bdev_rbd_init_context (arg=0x55d5f609b870) at bdev_rbd.c:429
#10 0x000055d5f3a99535 in spdk_call_unaffinitized (cb=0x55d5f3a944a0 <bdev_rbd_init_context>, arg=0x55d5f609b870) at env.c:357
--Type <RET> for more, q to quit, c to continue without paging--
#11 0x000055d5f3a95e62 in bdev_rbd_init (rbd=0x55d5f609b870) at bdev_rbd.c:471
#12 bdev_rbd_create (bdev=bdev@entry=0x7ffd63b83e08, name=0x55d5f5ed38b0 "cnrvkip4rprnveqir610", user_id=<optimized out>, pool_name=<optimized out>, config=<optimized out>, rbd_name=0x55d5f5ed5c80 "img-zstorage-AS_E-1A-cnrvkip4rprnveqir6108fv", bl
ock_size=512, cluster_name=0x55d5f6013350 "rbd_cluster", uuid=0x7ffd63b83e48) at bdev_rbd.c:1332
#13 0x000055d5f3a9644a in rpc_bdev_rbd_create (request=0x55d5f601e7f0, params=<optimized out>) at bdev_rbd_rpc.c:105
#14 0x000055d5f3ae752a in parse_single_request (values=<optimized out>, request=0x55d5f601e7f0) at jsonrpc_server.c:126
#15 jsonrpc_parse_request (conn=conn@entry=0x7f2bff106040, json=json@entry=0x7f2bff106058, size=215) at jsonrpc_server.c:263
#16 0x000055d5f3ae8230 in jsonrpc_server_conn_recv (conn=0x7f2bff106040) at jsonrpc_server_tcp.c:294
#17 spdk_jsonrpc_server_poll (server=<optimized out>) at jsonrpc_server_tcp.c:425
#18 0x000055d5f3ae6ad0 in spdk_rpc_accept () at rpc.c:213
#19 0x000055d5f3add18d in rpc_subsystem_poll (arg=<optimized out>) at rpc.c:21
#20 0x000055d5f3ade550 in thread_execute_timed_poller (now=10348149065969312, poller=0x55d5f5c9e9b0, thread=0x55d5f5c87d80) at thread.c:1007
#21 thread_poll (thread=thread@entry=0x55d5f5c87d80, max_msgs=max_msgs@entry=0, now=now@entry=10348149065969312) at thread.c:1097
#22 0x000055d5f3adf2b3 in spdk_thread_poll (thread=thread@entry=0x55d5f5c87d80, max_msgs=max_msgs@entry=0, now=10348149065969312) at thread.c:1156
#23 0x000055d5f3ab1d21 in _reactor_run (reactor=0x55d5f5c85e40) at reactor.c:914
#24 reactor_run (arg=0x55d5f5c85e40) at reactor.c:952
#25 0x000055d5f3ab21e3 in spdk_reactors_start () at reactor.c:1068
#26 0x000055d5f3aaf078 in spdk_app_start (opts_user=opts_user@entry=0x7ffd63b84590, start_fn=start_fn@entry=0x55d5f3a00d50 <vhost_started>, arg1=arg1@entry=0x0) at app.c:835
#27 0x000055d5f39f975f in main (argc=<optimized out>, argv=<optimized out>) at vhost.c:77

**Comment by jimharris** [comment]
This needs a lot more information. rbd is tested quite a bit in SPDK CI, so there is likely something different in your environment causing this to happen. Without any information on how you built and configured SPDK, or your Ceph cluster, any further debug is not possible.

**Comment by faicker** [comment]
./configure --with-rbd --with-rdma

**Comment by ksztyber** [comment]
[Bug scrub] @faicker could you post more info how to reproduce this? E.g. what app are you starting the RPCs, etc.

**Comment by jimharris** [comment]
No responses, so closing.
