### ISSUE TITLE
NVMe-oF target: InCapsuleDataSize 0 does not work

### ISSUE THREAD

**Issue by senthilkumar-v** [spdk/spdk#331]
Hi,
      I’ve a query regarding Nvmf “InCapsuleDataSize” and its implementation. From the SPDK conf file Nvmf section, the “InCapsuleDataSize” is defined as below,

### Nvmf Conf. file
[Nvmf]
  ###Set the maximum number of outstanding I/O per queue.
  MaxQueueDepth 128
  ###Set the maximum in-capsule data size. Must be a multiple of 16.
  ###0 is a valid choice.
  InCapsuleDataSize 4096

Please note conf file comment says that “0 is a valid choice”. But when it is set to value zero i.e. InCapsuleDataSize 0, connect fails with below error.
“Unable to allocate sufficient memory for RDMA queue.”.

## Expected Behavior

The Nvmf connect is expected to pass.

## Current Behavior

The connect fails with below error.
“Unable to allocate sufficient memory for RDMA queue.”.

### Probable root-cause
From code walk-thru, the error is from below code section,

[root@vm2 spdkgit]# git describe --tags
v18.04-80-gf750c4e

static int
spdk_nvmf_rdma_qpair_initialize(struct spdk_nvmf_qpair *qpair)
{
…
…
  rqpair->bufs = spdk_dma_zmalloc(**_rqpair->max_queue_depth * rtransport->in_capsule_data_size,_**
          0x1000, NULL);
              if (!rqpair->reqs || !rqpair->recvs || !rqpair->cmds ||
                         !rqpair->cpls || !rqpair->bufs) {
               SPDK_ERRLOG("Unable to allocate sufficient memory for RDMA queue.\n");
               spdk_nvmf_rdma_qpair_destroy(rqpair);
                return -1;
  }
…
…
}

The root cause is in the above highlighted section of code where “rqpair->bufs” becomes zero when “in_capsule_data_size” is set to zero. 

I’ve cross-checked with “NVM Express over Fabrics 1.0” spec and didn’t see anywhere that it mandates to set “InCapsuleDataSize” to a non-zero value always.

With my above understanding, there seems to be a bug in above highlighted code where it should ignore “rtransport->in_capsule_data_size” if it is zero.

### Probable fixes

**Fix #1:-**

rqpair->bufs = spdk_dma_zmalloc(rqpair->max_queue_depth * **_( rtransport->in_capsule_data_size ? rtransport->in_capsule_data_size : 1)_**,  0x1000, NULL);

OR

**Fix #2:-**

In /home/spdkgit/lib/event/subsystems/nvmf/conf.c file,

  in_capsule_data_size = spdk_conf_section_get_intval(sp, "InCapsuleDataSize");
  if (**_in_capsule_data_size > 0_**) {                  **_<====  No more checks for “equal to 0” condition._**
    opts->in_capsule_data_size = in_capsule_data_size;
  **_} else {
    opts->in_capsule_data_size = 1;            <======== For zero & less than zero cases, it sets the value to 1.
}_**

**_Note-1:- The fix #1 scope is contained within that use case but fix #2 might have global impact compared to fix #1 so please suggest which is better way to fix._**

## **_Other areas of code to consider_**

Similar bug could be in other places of code as shown below,

1.	While constructing “bufs_mr” as show below,
  rqpair->bufs_mr = ibv_reg_mr(rqpair->cm_id->pd, rqpair->bufs,
             **_rqpair->max_queue_depth * rtransport->in_capsule_data_size,_**
             IBV_ACCESS_LOCAL_WRITE |
             IBV_ACCESS_REMOTE_WRITE);

**_Note-2:- I’m not sure how it’ll manifest in the field. May be we can apply fix #1(??), if it is a real bug here. Thoughts?_**

2.	**_Line 406: rdma_recv->buf = (void *)((uintptr_t)rqpair->bufs + (i * rtransport->in_capsule_data_size));_**
        **_Line 413: rdma_recv->sgl[1].length = rtransport->in_capsule_data_size;_**

**_Note-3:- I’m not sure whether there is any bug here but thought of highlight it to get the attention of wider audience._** 

3.	static int
spdk_nvmf_rdma_request_parse_sgl(struct spdk_nvmf_rdma_transport *rtransport,
        struct spdk_nvmf_rdma_device *device,
        struct spdk_nvmf_rdma_request *rdma_req)
 {
     …
     …
      **_914     uint32_t max_len = rtransport->in_capsule_data_size;_**
    ….
   ….
}

**_Note-4:- I’m not sure about impact of “max_len” here but highlighting it to get wider attention._**

4.	static struct spdk_nvmf_transport *
 spdk_nvmf_rdma_create(struct spdk_nvmf_tgt *tgt)
 {
     …
    …
    **_1141   rtransport->in_capsule_data_size = tgt->opts.in_capsule_data_size;_**
   …
   …
}

**_Note-5:- Again just highlighting it._**

**_Let me know your thoughts about the above bug fix proposals (fix1 & fix2) and all 5 notes (Note 1-5)._**

## Steps to Reproduce

1. Set "InCapsuleDataSize" value to 0.
2. Issue connect.

## Context (Environment including OS version, SPDK version, etc.)

[root@vm2 spdkgit]# git describe --tags
v18.04-80-gf750c4e

**Comment by dverkamp-intel** [comment]
This is definitely a bug - we should be checking InCapsuleDataSize before trying to allocate and register the in-capsule data buffers.

**Comment by senthilkumar-v** [comment]
Hi Xuhuagen,
        I'm already working on this issue but could see that it got assigned to you.  Can you please let me know whether you are working on fixing the same issue or it got assigned to you wrongly. 

Thanks,
Senthil Kumar V.

**Comment by wanqunintel** [comment]
Hi, @senthilkumar-v  Huagen is working on the validation for this issue. Will you submit the patch for this?

**Comment by senthilkumar-v** [comment]
Hi @wanqunintel, I'm planning to discuss the proposed solution in the upcoming SPDK Asia community meeting on 21st June. After which I'll submit the patch for review.

**Comment by wanqunintel** [comment]
Hi, @senthilkumar-v That's great, thank you and would you post the link for the patch here when it's done. Thanks a lot.

**Comment by senthilkumar-v** [comment]
Hi @wanqunintel, sure. I'll post it here.

**Comment by jimharris** [comment]
Suggestion is to *not* allocate 1-byte buffers.  Just don't allocate any memory when in-capsule-size is 0.

This will require some other changes - i.e. for the rdma recvs, it should just be one scatter gather element instead of two.

**Comment by xuhuagen** [comment]
@senthilkumar-v is there a patch to slove this issue?

**Comment by senthilkumar-v** [comment]
@xuhuagen Sorry for the late response. I couldn't spend time on this last week due to other priorities. I'll submit it in this week.

**Comment by senthilkumar-v** [comment]
@xuhuagen I've submitted code for review. Review URL is https://review.gerrithub.io/#/c/spdk/spdk/+/418170 . I've tested these changes by setting "InCapsuleDataSize" to zero in nvmf.conf file as I didn't find appropriate UT test file in /test/unit/lib/nvmf/. Please let me know if there is any other way to include this case in UT framework of /test/unit/lib/nvmf/.

**Comment by xuhuagen** [comment]
@senthilkumar-v  I patched https://review.gerrithub.io/#/c/spdk/spdk/+/418170 and it can resolve this issue.  From my observation,There are no ut tests for nvmf configuration files so far.

**Comment by senthilkumar-v** [comment]
Closing this issue as the patch is integrated.
