### ISSUE TITLE
Running bdev_examine on a base_bdev part of an existing raid will crash spdk

### ISSUE THREAD

**Issue by arsiesys** [spdk/spdk#3314]
# Sighting report

Running bdev_examine on a base_bdev part of an existing raid will crash spdk

```
[2024-03-19 20:15:55.637257] bdev_raid.c:1641:raid_bdev_configure_cont: *DEBUG*: raid bdev is created with name test, raid_bdev 0x574e0fec4c00
[2024-03-19 20:16:07.187391] bdev_raid.c:3369:raid_bdev_examine_load_sb_cb: *DEBUG*: raid superblock found on bdev local0
nvmf_tgt: bdev_raid.c:2904: raid_bdev_configure_base_bdev: Assertion `base_info->desc == NULL' failed.
Aborted (core dumped)
```

I noticed this bug while developing automation around SPDK and had a case where I got a double tasks and a missing check, running bdev_examine a second time.

## Expected Behavior

SPDK should handle this misuse of bdev_examine and ignore it then do not crash.

## Current Behavior

Spdk exit

## Possible Solution

If the bdev is part of an active and running raid, the examine could be ignored.

## Steps to Reproduce

```
./scripts/rpc.py bdev_malloc_create -b local0 64 4096
./scripts/rpc.py bdev_malloc_create -b local1 64 4096
./scripts/rpc.py bdev_raid_create -n test -r raid1 -b "local1 local0" -s
./scripts/rpc.py bdev_examine -b local0
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK master a771524779ceac7bdae7b15058404b9cc7320085

**Comment by apaszkie** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/22487

**Comment by arsiesys** [comment]
Hi,

As expected, the raid still can't be fully assembled (other issue/thread) but the tgt does not crash on a second bdev_examine anymore.

Thank you @apaszkie  !
