### ISSUE TITLE
Unable to build SPDK with FIO plugin

### ISSUE THREAD

**Issue by narayanbhosle** [spdk/spdk#3317]
# Sighting report

I am trying to build SPDK with FIO, compilation stops with the below erros. Without FIO plugin I can build till end.
This issue seems to compatibility issue b/w fio_plugin.c and FIO repo which I gave for ./configuration.

  CC app/fio/nvme/fio_plugin.o
In file included from /root/spdk/include/spdk/stdinc.h:28,
                 from fio_plugin.c:6:
/root/fio/arch/../lib/types.h:5:13: error: two or more data types in declaration specifiers
    5 | typedef int bool;
      |             ^~~~
In file included from /root/fio/arch/arch.h:10,
                 from /root/fio/thread_options.h:4,
                 from /root/fio/fio.h:18,
                 from fio_plugin.c:21:
/root/fio/arch/../lib/types.h:5:1: warning: useless type name in empty declaration
    5 | typedef int bool;
      | ^~~~~~~
In file included from /root/fio/os/os.h:37,
                 from /root/fio/thread_options.h:5,
                 from /root/fio/fio.h:18,
                 from fio_plugin.c:21:
/root/fio/os/os-linux.h:171:19: error: static declaration of ‘gettid’ follows non-static declaration
  171 | static inline int gettid(void)
      |                   ^~~~~~
In file included from /usr/include/unistd.h:1208,
                 from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /root/spdk/include/spdk/stdinc.h:49,
                 from fio_plugin.c:6:
/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ with type ‘__pid_t(void)’ {aka ‘int(void)’}
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
In file included from /root/fio/os/os.h:37,
                 from /root/fio/thread_options.h:5,
                 from /root/fio/fio.h:18,
                 from fio_plugin.c:21:
/root/fio/os/os-linux.h:356:23: error: conflicting types for ‘preadv2’; have ‘ssize_t(int,  const struct iovec *, int,  off_t,  unsigned int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  unsigned int)’}
  356 | static inline ssize_t preadv2(int fd, const struct iovec *iov, int iovcnt,
      |                       ^~~~~~~
In file included from /root/spdk/include/spdk/stdinc.h:62,
                 from fio_plugin.c:6:
/usr/include/sys/uio.h:133:16: note: previous declaration of ‘preadv2’ with type ‘ssize_t(int,  const struct iovec *, int,  __off_t,  int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  int)’}
  133 | extern ssize_t preadv2 (int __fp, const struct iovec *__iovec, int __count,
      |                ^~~~~~~
In file included from /root/fio/os/os.h:37,
                 from /root/fio/thread_options.h:5,
                 from /root/fio/fio.h:18,
                 from fio_plugin.c:21:
/root/fio/os/os-linux.h:364:23: error: conflicting types for ‘pwritev2’; have ‘ssize_t(int,  const struct iovec *, int,  off_t,  unsigned int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  unsigned int)’}
  364 | static inline ssize_t pwritev2(int fd, const struct iovec *iov, int iovcnt,
      |                       ^~~~~~~~
In file included from /root/spdk/include/spdk/stdinc.h:62,
                 from fio_plugin.c:6:
/usr/include/sys/uio.h:138:16: note: previous declaration of ‘pwritev2’ with type ‘ssize_t(int,  const struct iovec *, int,  __off_t,  int)’ {aka ‘long int(int,  const struct iovec *, int,  long int,  int)’}
  138 | extern ssize_t pwritev2 (int __fd, const struct iovec *__iodev, int __count,
      |                ^~~~~~~~
In file included from /root/fio/fio.h:29,
                 from fio_plugin.c:21:
/root/fio/helpers.h:11:12: error: conflicting types for ‘sync_file_range’; have ‘int(int,  uint64_t,  uint64_t,  unsigned int)’ {aka ‘int(int,  long unsigned int,  long unsigned int,  unsigned int)’}
   11 | extern int sync_file_range(int fd, uint64_t offset, uint64_t nbytes,
      |            ^~~~~~~~~~~~~~~
In file included from /usr/include/bits/fcntl.h:61,
                 from /usr/include/fcntl.h:35,
                 from /root/spdk/include/spdk/stdinc.h:40,
                 from fio_plugin.c:6:
/usr/include/bits/fcntl-linux.h:383:12: note: previous declaration of ‘sync_file_range’ with type ‘int(int,  __off64_t,  __off64_t,  unsigned int)’ {aka ‘int(int,  long int,  long int,  unsigned int)’}
  383 | extern int sync_file_range (int __fd, __off64_t __offset, __off64_t __count,
      |            ^~~~~~~~~~~~~~~
make[3]: *** [/root/spdk/mk/spdk.common.mk:525: fio_plugin.o] Error 1
make[2]: *** [/root/spdk/mk/spdk.subdirs.mk:16: nvme] Error 2
make[1]: *** [/root/spdk/mk/spdk.subdirs.mk:16: fio] Error 2
make: *** [/root/spdk/mk/spdk.subdirs.mk:16: app] Error 2

**Comment by jimharris** [comment]
Please add your configuration to this issue. Which version of SPDK are you using and which version of fio are you trying to compile.

**Comment by narayanbhosle** [comment]
SPDK: SPDK v24.01: DIF in accel, RAID rebuild, Blobstore grow
FIO: fio-3.36

./configure --with-fio=/root/fio

**Comment by jimharris** [comment]
Linux distro and gcc version?

**Comment by narayanbhosle** [comment]
**[root@nb ~]# gcc --version**
gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
**[root@nb ~]# uname -r**
6.6.0-gnr.bkc.6.6.10.2.16.x86_64
**[root@nb ~]# cat /etc/os-release**
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream

**Comment by jimharris** [comment]
> # Sighting report
> I am trying to build SPDK with FIO, compilation stops with the below erros. Without FIO plugin I can build till end. This issue seems to compatibility issue b/w fio_plugin.c and FIO repo which I gave for ./configuration.
> 
> CC app/fio/nvme/fio_plugin.o In file included from /root/spdk/include/spdk/stdinc.h:28, from fio_plugin.c:6: /root/fio/arch/../lib/types.h:5:13: error: two or more data types in declaration specifiers 5 | typedef int bool; | ^~~~ In file 

Please double-check your environment, including any changes you've made locally to SPDK.

This error can only happen if fio has been configured without CONFIG_HAVE_BOOL. CONFIG_HAVE_BOOL is only not defined if configure script cannot compile simple program with stdbool.h. Please check your configure output to debug why some of these errors are occurring.

**Comment by narayanbhosle** [comment]
I am able build with below env vaiables.
 ./configure --prefix=/usr --libdir=/usr/lib64 --with-fio=/root/fio
 
Now, I get below error while running, please help

**[root@nb fio]# sudo LD_PRELOAD=/root/spdk/build/fio/spdk_nvme  ./fio  /root/spdk_config.fio**
./fio: error while loading shared libraries: libfuse3.so.3: cannot open shared object file: No such file or directory


---------------spdk_config.fio-------------------
[global]
ioengine=spdk
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=60
iodepth=64
rw=rw
bs=4k
filename=/dev/nvme0n1
 
[test]
numjobs=1

**Comment by jimharris** [comment]
You probably need to set LD_LIBRARY_PATH, similar to how you overrode --libdir.

**Comment by jimharris** [comment]
Closing issue, since this is related to user's environment.
