### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by ziyizhou0813** [spdk/spdk#3321]
Build complete [x86_64-native-linuxapp-gcc]
  LINK app/trace/spdk_trace
/usr/bin/ld.bfd: trace.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld.bfd: trace.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld.bfd: trace.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld.bfd: trace.o: unable to initialize decompress status for section .debug_info
trace.o: file not recognized: Unrecognized file format
collect2: error: ld returned 1 exit status
Makefile:46: recipe for target 'spdk_trace' failed
make[2]: *** [spdk_trace] Error 1
/home/sgxubuntu/work/spdk/mk/spdk.subdirs.mk:44: recipe for target 'trace' failed
make[1]: *** [trace] Error 2
/home/sgxubuntu/work/spdk/mk/spdk.subdirs.mk:44: recipe for target 'app' failed
make: *** [app] Error 2

How to solve it?

**Comment by ziyizhou0813** [comment]
This is an error that occurs when V20.04 is installed to make on ubutun18.04.

**Comment by jimharris** [comment]
Hi @ziyizhou0813,

Neither SPDK v20.04 nor Ubuntu 18.04 are supported by SPDK anymore. Please move to newer versions.

Supported Linux distributions: https://spdk.io/doc/distributions.html
SPDK v24.01 LTS is currently supported. Sometimes we will make some effort to support an earlier version, but v20.04 is simply too old.

Best regards,

Jim
