### ISSUE TITLE
no NVMe controllers found

### ISSUE THREAD

**Issue by ziyizhou0813** [spdk/spdk#3324]
sudo scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB     1678 /   2048

NVMe devices
BDF		Vendor	Device	NUMA	Driver		Device name
0000:06:00.0	144d	a80a	0	nvme			nvme0
0000:07:00.0	15b7	5006	0	nvme			nvme1

I/OAT DMA
BDF		Vendor	Device	NUMA	Driver

IDXD DMA
BDF		Vendor	Device	NUMA	Driver

virtio
BDF		Vendor	Device	NUMA	Driver		Device name
VMD
BDF		Numa Node	Driver Name

sudo scripts/rpc.py construct_nvme_bdev -b Nvme0 -t PCIe -a 0000:06:00.0
request:
{
  "name": "Nvme0",
  "trtype": "PCIe",
  "traddr": "0000:06:00.0",
  "method": "bdev_nvme_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -19,
  "message": "No such device"
}
EAL: Driver cannot attach the device (0000:06:00.0)
EAL: Failed to attach device on primary process
nvme.c: 609:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
bdev_nvme.c:1765:spdk_bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:06:00.0)
how to solve?

**Comment by changpe1** [comment]
@ziyizhou0813 you should run scripts/setup.sh to bind your NVMe SSDs from kernel driver to vfio-pci or uio first.

**Comment by ziyizhou0813** [comment]
> @ziyizhou0813 you should run scripts/setup.sh to bind your NVMe SSDs from kernel driver to vfio-pci or uio first.
Yes, I did. But it still didn't solve the problem. I don't know why binding to NVME doesn't work.

**Comment by jimharris** [comment]
> > @ziyizhou0813 you should run scripts/setup.sh to bind your NVMe SSDs from kernel driver to vfio-pci or uio first.
> > Yes, I did. But it still didn't solve the problem. I don't know why binding to NVME doesn't work.

Please post the log when running `scripts/setup.sh`.

**Comment by ziyizhou0813** [comment]
> > > @ziyizhou0813 you should run scripts/setup.sh to bind your NVMe SSDs from kernel driver to vfio-pci or uio first.
> > > Yes, I did. But it still didn't solve the problem. I don't know why binding to NVME doesn't work.
> 
> Please post the log when running `scripts/setup.sh`.

$ sudo ./scripts/setup.sh 
0000:06:00.0 (144d a80a): Active mountpoints on /dev/nvme0n1, so not binding PCI dev
0000:07:00.0 (15b7 5006): Active mountpoints on /dev/nvme1n1, so not binding PCI dev

**Comment by mmkayPL** [comment]
Unmount any filesystems that are using these NVMe drives - just note with them switched to a userspace driver, the kernel block device stack won't be able to make use of them.

**Comment by ziyizhou0813** [comment]
> Unmount any filesystems that are using these NVMe drives - just note with them switched to a userspace driver, the kernel block device stack won't be able to make use of them.

I would like to ask, do I need to uninstall all of them? Can I uninstall one of the nvme devices?

**Comment by ziyizhou0813** [comment]
> > > Unmount any filesystems that are using these NVMe drives - just note with them switched to a userspace driver, the kernel block device stack won't be able to make use of them.
> > 
> > 
> > I would like to ask, do I need to uninstall all of them? Can I uninstall one of the nvme devices?
> 
> You need to remove filesystems from at least one device, and then that device can be used with SPDK.

Thanks, I'll try.
