### ISSUE TITLE
spdk_trace: non-json format is printed while -j option is given

### ISSUE THREAD

**Issue by dydwls-lee** [spdk/spdk#3326]
# Sighting report

## Current Behavior

Trace size info not in json format is printed when -j option is given, causing an error with jq.

## Possible Solution

Our team is going to create PR.

## Steps to Reproduce

```
$ ./spdk/build/bin/spdk_trace -s spdk_tgt -p <pid> -j | jq .
...
{"name":"THREAD_IOCH_PUT","id":641,"new_object":false,"args":[{"Trace Size of lcore (0): 32768
Trace Size of lcore (1): 32768
Trace Size of lcore (2): 32768
name":"refcnt","type":0,"size":8}]}
...
parse error: Invalid numeric literal at line 1, column 5499
```

## Context (Environment including OS version, SPDK version, etc.)

v24.01, Ubuntu 22.04.2 LTS

**Comment by jimharris** [comment]
Thanks for the report @dydwls-lee. I think you can just omit this extra text about trace sizes when selecting JSON output.

**Comment by dydwls-lee** [comment]
Hi @jimharris ,
I created PR for this issue. https://review.spdk.io/gerrit/c/spdk/spdk/+/22642
Instead of simple fix, our team thought switch statement would be better for adding new format.
We are going to contribute additional codes that print spdk_trace data in Jaeger format.
