### ISSUE TITLE
nvmf: NVMf with RDMA appears multiple IO hangs

### ISSUE THREAD

**Issue by ygtzf** [spdk/spdk#3328]
# Sighting report

We have some scenarios where SPDK and RDMA are used, and the problem of vhost's IO hang has occurred many times recently. There are many controllers on this vhost, and these controllers are normal. The corresponding nvmf target also has many controllers, and these controllers are also normal. Occasionally, we found that if we execute the nvme discover command on the abnormal IP and port, the abnormal IO will be restored.

When an IO Hang occurs, we do not see any logs of this controller on the vhost side, nor in the captured trace. When we executed the nvme discover command, vhost did not see the log and trace did not catch it. However, we saw a lot of IO started to be processed on the target side, as shown below in part of the trace，the bdev name is9b840683-00d9-4d：

```
TSC Rate: 2100000000
Trace Size of lcore (32): 1452647
Trace Size of lcore (33): 294798
Trace Size of lcore (34): 28382
Trace Size of lcore (80): 203053
Trace Size of lcore (81): 946932
Trace Size of lcore (82): 126689
...
32: 12520362.000     RDMA_CM_ASYNC_EVENT                   type:  4
32: 12521117.000     RDMA_QP_CREATE                        object:0x303d6950
32: 12522156.000     RDMA_QP_STATE_CHANGE                  object:0x303d6950       state: 0x3
32: 12524743.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524747.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524749.000     RDMA_REQ_TX_H2C                       id:    N/Aqpair: 0x2e8f3be0
32: 12524749.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524751.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524751.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524755.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524755.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524759.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524759.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524762.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524762.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524763.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524763.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524766.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524766.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524768.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524768.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524769.000     RDMA_REQ_RDY_TO_EXECUTE               id:    N/Aqpair: 0x2e8f3be0
32: 12524771.000 b00 BDEV_IO_START                         id:    i12638           type:  2                ctx:   0x20102bbe50f0   offset:397880320        len:   8                name:  9b840683-00d9-4d
32: 12524775.000 b00 BDEV_IO_START                         id:    i12639           type:  2                ctx:   0x25bb098        offset:4389800960       len:   8                name:  NVMee3n1
32: 12524776.000     BDEV_NVME_IO_START                    id:    N6322 (i12639)   ctx:   0x201011a09880
32: 12524777.000 q07 NVME_PCIE_SUBMIT                      id:    p6656 (N6322)    ctx:   0x201011a09c60   cid:   817              opc:   1                dw10:  0x5a70c00        dw11:  0x1              dw12:  0x7
32: 12524778.000     RDMA_REQ_EXECUTING                    id:    N/Aqpair: 0x2e8f3be0
32: 12524778.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524781.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524781.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524783.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524783.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524786.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524786.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524788.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524789.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524791.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524791.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524793.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524793.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524798.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524798.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524801.000     RDMA_REQ_TX_PENDING_H2C               id:    N/Aqpair: 0x2e8f3be0
32: 12524801.000     RDMA_REQ_NEED_BUFFER                  id:    N/Aqpair: 0x2e8f3be0
32: 12524802.000     RDMA_REQ_RDY_TO_EXECUTE               id:    N/Aqpair: 0x2e8f3be0
32: 12524802.000 b00 BDEV_IO_START                         id:    i12640           type:  2                ctx:   0x20102bbe1e30   offset:397881344        len:   8                name:  9b840683-00d9-4d
32: 12524803.000 b00 BDEV_IO_START                         id:    i12641           type:  2                ctx:   0x25acc00        offset:4389801984       len:   8                name:  NVMee3n1
32: 12524803.000     BDEV_NVME_IO_START                    id:    N6323 (i12641)   ctx:   0x201011a22240
32: 12524804.000 q07 NVME_PCIE_SUBMIT                      id:    p6657 (N6323)    ctx:   0x201011a22620   cid:   840              opc:   1                dw10:  0x5a71000        dw11:  0x1              dw12:  0x7
```

As can be seen from this trace, 1,452,647 pieces of data appeared on CPU core 32, and all of them were data from the abnormal controller. However, during IO Hang, there was almost no trace data on CPU core 32.
Another key point is that the qpair 0x2e8f3be0 did not appear in the trace during IO Hang, but when the nvmf target processed the discover message, after RDMA_QP_CREATE, the stale qpair 0x2e8f3be0 became active, and then the previously blocked IO began to respond.

## Expected Behavior
When NVMf target and vhost are both normal, IO Hang should not occur.

## Current Behavior

IO hang occurred many times recently.

## Possible Solution

I guess there may be the following possibilities:
1. The rdma event was not polled
2. The rdma event does not enter the qpair
3. nvmf_poll_group does not consume data in qpair

## Steps to Reproduce

It's not reproducible in our test environment yet, even though we really want it to be there.

## Context (Environment including OS version, SPDK version, etc.)
OS Version：CentOS Linux release 8.2.2004 (Core) 
Kernel Version: Linux 4.18.0-348.7.1.el8_5.x86_64
SPDK Version: V23.01
Vhost Version: V23.01/V24.01
RDMA library: 26.0-8.el8

**Comment by ygtzf** [comment]
@jimharris Could you help provide further investigation ideas? We are currently stuck in the problem. Thanks.

**Comment by changpe1** [comment]
virtio-blk doesn't have the timeout mechanism in the VM, so you will not see any exception logs in vhost side.
What's the timeout value in the nvme initiator?

**Comment by ygtzf** [comment]
@jimharris  @changpe1 Is it possible that the buffer cache is insufficient? The ransport options:

```
    "trtype": "RDMA",
    "max_queue_depth": 128,
    "max_io_qpairs_per_ctrlr": 127,
    "in_capsule_data_size": 4096,
    "max_io_size": 131072,
    "io_unit_size": 8192,
    "max_aq_depth": 128,
    "num_shared_buffers": 4095,
    "buf_cache_size": 32,
    "dif_insert_or_strip": false,
    "zcopy": false,
    "max_srq_depth": 4096,
    "no_srq": false,
    "acceptor_backlog": 100,
    "no_wr_batching": false,
    "abort_timeout_sec": 1
```

We found that the admin qpair and io qair in this situation are on different CPU cores, so the keep alive of admin qpair does not time out, and the admin qpair will not disconnect.

**Comment by ygtzf** [comment]
We now suspect that there is some lack of resources in the nvmf target, causing the rdma request not to be processed, resulting in IO Hang. The function ibv_poll_cq cannot get cqe，and the function nvmf_rdma_qpair_process_pending cannot be called，the pending_rdma_queue cannot be consumed.
When the new admin qpair  is scheduled to the CPU core again, the nvmf_rdma_qpair_process_pending function will be called again. At this time, the pending_rdma_queue will be consumed again, and IO will be restored.

**Comment by AlekseyMarchuk** [comment]
Hi, you have 4096 shared buffers, that is default config I can't say whether it is enough or not, it depends on your workflow. You can examine `nvmf_get_stats` RPC to check how many requests were pending on memory buffers.
If I remember correctly, vhost has a dedicated thread to process all IOs, a core which serves this thread might be overloaded with a lot of work. That is typically the first core in the core mask (number 32 in your case). But I'm just thinking out loud, that should not cause the issue.
Can you share more details about IO size and qdepth, number of qpairs and controllers used in your test? Also, is it possible to try latest SPDK v24.01 release? 
I see one suspicious place in the code and we hit similar problem in our internal tests but I need to reproduce the issue for further analysis and fix

**Comment by AlekseyMarchuk** [comment]
@ygtzf I guess this is your patch https://review.spdk.io/gerrit/c/spdk/spdk/+/22785
That could help with the issue, but full fix can be much more complicated. As I remember, the problem related to the `data_wr_pool` - it's size is hard coded and quite small - qdepth * 16. I don't know why this size was used, but this pool is common for the whole RDMA transport and 2048 entries much not be enough at some scale. There is a chance that a deadlock occurs - to process IO we need WRs from the pool but we can't release WRs due to we have no completions.
I can prepare a fix next week

**Comment by ygtzf** [comment]
@ After the IO was restored, I grabbed nvmf_get_stats. The specific content is in the attachment. The option pending_data_buffer seems to accumulated, and the value is large.
[nvmf_stats.log](https://github.com/spdk/spdk/files/14979063/nvmf_stats.log)

**Comment by ygtzf** [comment]
> @ygtzf I guess this is your patch https://review.spdk.io/gerrit/c/spdk/spdk/+/22785
> That could help with the issue, but full fix can be much more complicated. As I remember, the problem related to the `data_wr_pool` - it's size is hard coded and quite small - qdepth * 16. I don't know why this size was used, but this pool is common for the whole RDMA transport and 2048 entries much not be enough at some scale. There is a chance that a deadlock occurs - to process IO we need WRs from the pool but we can't release WRs due to we have no completions.
> I can prepare a fix next week

Yes, this patch was submitted by my colleague, trying to solve the problem of pending queue not being processed through timed poller.

**Comment by AlekseyMarchuk** [comment]
That is no so easy to catch it. We reproduced it few times occasionally, using big IO with fragmented payload (to utilize 16 data WRs per IO) and multithreads spdk instance (to share data_wr_pool among many cores) increase the chance

**Comment by ygtzf** [comment]
We are conducting a grayscale test in an online environment. Since it cannot be reproduced stably, this grayscale test may take a long time. We may need to wait for a while to see the results.

**Comment by ygtzf** [comment]
At present, that patch can solve the bug. I can close the issue first.
