### ISSUE TITLE
Guidelines on using both SPDK and DPDK

### ISSUE THREAD

**Issue by m-kru** [spdk/spdk#3329]
I have to implement an application requiring both SPDK and DPDK. If I understand correctly, SPDK depends on the DPDK. However, I am not certain about a few things.

1. Is DPDK automatically compiled and installed during the SPDK compilation/installation process, or do I have to compile/install it separately from the `dpdk` submodule directory?
2. Do I have to use the same DPDK version used for SPDK compilation?
3. How do I know which DPDK functions are safe to call when SPDK is used? For example, applications utilizing DPDK call the `rte_eal_init` function to initialize the Environment Abstraction Layer. However, SPDK applications call the `spdk_env_opts_init` function to initialize the environment.

**Comment by jimharris** [comment]
> I have to implement an application requiring both SPDK and DPDK. If I understand correctly, SPDK depends on the DPDK. However, I am not certain about a few things.
> 
> 1. Is DPDK automatically compiled and installed during the SPDK compilation/installation process, or do I have to compile/install it separately from the `dpdk` submodule directory?

By default, if you compile SPDK, it will also compile the DPDK submodule. Similarly if you do 'make install'.
But SPDK configure script allows you to specify your *own* version of DPDK if you do not want to use the DPDK submodule. In that case of course you are responsible for building/installing DPDK if you have a separate DPDK version from source. configure also supports using packaged DPDK on your system. Please see configure script for more details.

> 2. Do I have to use the same DPDK version used for SPDK compilation?

No, but SPDK only supports DPDK versions back about two years. Right now, it supports back to DPDK v21.11. We will likely be moving this to v22.11 before the SPDK v24.05 release.

> 3. How do I know which DPDK functions are safe to call when SPDK is used? For example, applications utilizing DPDK call the `rte_eal_init` function to initialize the Environment Abstraction Layer. However, SPDK applications call the `spdk_env_opts_init` function to initialize the environment.

See `spdk_env_dpdk_post_init()`.

**Comment by m-kru** [comment]
@jimharris what is the recommended way to see/change the build configuration for the DPDK provided as SPDK submodule? The default configuration does not build some of the pmds I require. Having SPDK scripts building and installing both SPDK and DPDK is very convenient. I would like to avoid building both SPDK and DPDK separately.

**Comment by jimharris** [comment]
> @jimharris what is the recommended way to see/change the build configuration for the DPDK provided as SPDK submodule? The default configuration does not build some of the pmds I require. Having SPDK scripts building and installing both SPDK and DPDK is very convenient. I would like to avoid building both SPDK and DPDK separately.

You'll need to modify dpdkbuild/Makefile. See DPDK_ENABLED_DRIVERS and DPDK_DISABLED_LIBS.
