### ISSUE TITLE
IOAT related errors are noisy during discovery

### ISSUE THREAD

**Issue by tanabarr** [spdk/spdk#3330]
After rebinding NVMe SSDs to vfio-pci with `spdk/scripts/setup.sh` (no args) on (Intel Xeon) Ice Lake platform IOAT device errors are seen during SPDK device discovery:

`IOAT: ioat_dmadev_probe(): Init 0000:00:01.1 on NUMA node 0`

Is there a way to only bind only NVMe devices in such a scenario other having to manually select PCI_ALLOWED/PCI_BLOCKED in setup script call?

It has been suggested the script could be extended with something like `PCI_TYPE=nvme` without too much effort.

Environment: SLES 15.4 or Alma 9, SPDK 22.01, Samsung SSDs, Intel Xeon ILX

**Comment by mikeBashStuff** [comment]
The patch suggested above has been merged, so closing this for now.
