### ISSUE TITLE
 Bdev Init: JSON method not found

### ISSUE THREAD

**Issue by moyucd** [spdk/spdk#3332]
# Sighting report

I created a file system based on Blobstore，when I  use origin/v24.01.x and not open ISAL. I run my app,meet error: json_config.c: 352:app_json_config_load_subsystem_config_entry: *ERROR*: Method 'bdev_nvme_attach_controller' was not found

## Expected Behavior
I will not encounter this problem on my previous version.remotes/origin/v21.01.x

## Current Behavior

when I use spdk_app_start，spdk give an error：bdev_nvme_attach_controller. my 

## Possible Solution

I use json file configuration bdev.
{
    "subsystems": [
      {
        "subsystem": "bdev",
        "config": [
          {
            "method": "bdev_nvme_attach_controller",
            "params": {
              "trtype": "PCIe",
              "name": "Nvme0",
              "traddr": "0000:86:00.0"
            }
          }
        ]
      }
    ]
  }

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
If libraries are not linked correctly (i.e. no `--whole-archive`), constructor functions are omitted from linked binary, meaning no RPC functions get registered. Please continue on #3333 if you have more questions.
