### ISSUE TITLE
Use Pkg_config in Cmake to compile spuds app failed

### ISSUE THREAD

**Issue by moyucd** [spdk/spdk#3333]
# Sighting report
in function `spdk_crc32c_update':

crc32c.c:25: undefined reference to `crc32_iscsi'

## Steps to Reproduce
this is my cmakelist.txt
find_package(PkgConfig REQUIRED)
set(ENV{PKG_CONFIG_PATH} ${SPDK_ROOT_DIR}/build/lib/pkgconfig)
pkg_check_modules(SPDK_EVENT_BDEV REQUIRED spdk_event_bdev)
pkg_check_modules(SPDK_INIT REQUIRED spdk_init)
pkg_check_modules(SPDK_ENV_DPDK REQUIRED spdk_env_dpdk)
pkg_check_modules(SPDK_BLOB REQUIRED spdk_blob)
pkg_check_modules(SPDK_EVENT REQUIRED spdk_event)
pkg_check_modules(SPDK_UTIL REQUIRED spdk_util)
pkg_check_modules(SPDK_BLOB_BDEV REQUIRED spdk_blob_bdev)
pkg_check_modules(SPDK_BDEV_NVME REQUIRED spdk_bdev_nvme)
target_link_libraries(chunkserver  -Wl,--no-as-needed ${SPDK_INIT_LINK_LIBRARIES}
	    ${EXTERNAL_LIB_FLAG}  ${SPDK_BLOB_LINK_LIBRARIES}  ${SPDK_BLOB_BDEV_LINK_LIBRARIES}    ${SPDK_EVENT_BDEV_LINK_LIBRARIES}
            ${SPDK_EVENT_LINK_LIBRARIES}      ${SPDK_ENV_DPDK_LINK_LIBRARIES} ${SPDK_SPDK_BDEV_NVME_LINK_LIBRARIES}
         -Wl,--as-needed)
target_compile_options(chunkserver PUBLIC  ${SPDK_INIT_CFLAGS_OTHER} ${SPDK_BLOB_CFLAGS_OTHER}  ${SPDK_BLOB_BDEV_CFLAGS_OTHER} ${SPDK_BDEV_NVME_CFLAGS_OTHER}
${SPDK_EVENT_CFLAGS_OTHER}  ${SPDK_EVENT_BDEV_CFLAGS_OTHER}   ${SPDK_ENV_DPDK_CFLAGS_OTHER} ${SPDK_UTIL_CFLAGS_OTHER}) 

target_include_directories(chunkserver PUBLIC ${SPDK_INIT_INCLUDE_DIRS} ${SPDK_BLOB_INCLUDE_DIRS}  ${SPDK_BLOB_BDEV_INCLUDE_DIRS} ${SPDK_BDEV_NVME_INCLUDE_DIRS} ${SPDK_EVENT_INCLUDE_DIRS}  ${SPDK_EVENT_BDEV_INCLUDE_DIRS} ${SPDK_UTIL_INCLUDE_DIRS} 
 ${SPDK_ENV_DPDK_INCLUDE_DIRS})

**Comment by jimharris** [comment]
Please review doc/pkgconfig.md. Make sure you are using correct linker options based on whether you are linking your application with shared or static libraries since the options are different.
