### ISSUE TITLE
Ubuntu16 check_format.sh bug.

### ISSUE THREAD

**Issue by johnmeneghini** [spdk/spdk#334]
https://review.gerrithub.io/#/c/spdk/spdk/+/415057/ is failing Verification because of a check_format.sh problem.  I believe this is a problem with the asytle utility on the Ubuntu 16 CIT testbed.  I have seen this problem before, and I have reproduced this problem on Ubuntu 16.  Note that the same patch does NOT display this problem on any other CIT testbed, so this is a CIT tool and configuration problem, not a problem with the patch.

If I update the patch with the recommended astyle changes from the Ubunto16 machine, all other CIT testbeds fail and format the patch again.  This is a tug of war.

## Expected Behavior

check_format.sh of the same patch should pass on all CIT testbeds.

## Current Behavior

check_format.sh of the same patch fails on one of the CIT testbeds.

## Possible Solution

Upgrade the Ubuntu 16 CIT Testbed to Unbuntu 18
Stop running apt-get update all of the time!!!

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

See https://ci.spdk.io/spdk/builds/review/9c36e7d11e849c901b1ae15a48c0d14c36885239.1529078920

**Comment by jimharris** [comment]
Maybe we have check_format.sh skip the astyle checks if the astyle version is less than <some revision number>?

**Comment by jimharris** [comment]
We could also uninstall astyle on ubuntu16.04.  But I think a check in check_format.sh would make it more clear which version of astyle SPDK conforms to.

**Comment by dverkamp-intel** [comment]
I removed astyle from the Ubuntu 16.04 test machine and re-ran the patch linked above, so that should resolve the short-term problem.

We should probably still add astyle version detection to check_format.sh to avoid problems like this in the future.

**Comment by chenlo2x** [comment]
The reason why check_format.sh failed on ubuntu 16.04 is that the astyle version is too low (2.0.3). I have resolved this problem on my ubuntu 14.04,  I install astyle (3.0.1) via the astyle source code. weblink: https://launchpad.net/ubuntu/+source/astyle/3.0.1-1ubuntu1

**Comment by Maciej-Szwed** [comment]
There has been added check of astyle version. For version < 3.0 warning message will be displayed that results may be not sufficient for our CI and astyle update is suggested. Patch introducing this change: https://review.gerrithub.io/420010
We can close this issue now.
