### ISSUE TITLE
`nvmf_tgt` unable to close gracefully when interrupt mode is enabled and TCP transport is created

### ISSUE THREAD

**Issue by KGoreczny** [spdk/spdk#3340]
# Sighting report

This issue was found during development of interrupt mode support for NVMe-of TCP.

Whenever TCP transport is created via rpc call entire `nvmf_tgt` application is not able to shutdown gracefully. Limited debug indicates that thread running `nvmf_tgt_poll_group` can't be closed as there are unhandled messages in the queue:
"thread_exit: *INFO*: thread nvmf_tgt_poll_group_0 still has messages"
Only way to close it is via 'kill -9' 

## Expected Behavior

nvmf_tgt app shall perform clean close at all times without the need for the SIGKILL signal. 

## Current Behavior

Process hangs, most likely as `thread_exit` can't set the thread state to SPDK_THREAD_STATE_EXITED due to unhandled massages. 

## Possible Solution

I did not dig it deep enough to understand why this happens.

## Steps to Reproduce

1. build/bin/nvmf_tgt --interrupt-mode &
2. scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
3. kill -SIGTERM <nvmf_tgt PID>

Note: if step 2 is omitted then SIGTERM works fine.

## Context (Environment including OS version, SPDK version, etc.)

Fedora 37
Tip of the SPDK master branch, at the time of writing: 62f5c5286f2992b6665f0d453dccdb7069583db2

**Comment by apaszkie** [comment]
This patch should fix it: https://review.spdk.io/gerrit/c/spdk/spdk/+/22878

**Comment by jimharris** [comment]
This patch seems to have caused a regression, issue #3351. I've revert this patch, so reopening this issue for now.

**Comment by apaszkie** [comment]
Another attempt, more specific this time: https://review.spdk.io/gerrit/c/spdk/spdk/+/22926

**Comment by glimchb** [comment]
@jimharris is it possible to add a test to prevent regression ?

**Comment by jimharris** [comment]
> @jimharris is it possible to add a test to prevent regression ?

Yes, a regression test for this would be welcome.

**Comment by glimchb** [comment]
> > @jimharris is it possible to add a test to prevent regression ?
> 
> Yes, a regression test for this would be welcome.

@KGoreczny if you have a minute, can you add a test for it ?
