### ISSUE TITLE
[spdk_nvme_perf] EAL: Failed to attach device on primary process

### ISSUE THREAD

**Issue by narayanbhosle** [spdk/spdk#3342]
I get below errors when I run perf, please help
SPDK Version: v24.01

[root@gnr-bkc scripts]# spdk_nvme_perf -q 128 -o 4096 -w randread -r 'trtype:PCIe traddr:0000:b7:00.0' -t 300
Initializing NVMe Controllers
EAL: Driver cannot attach the device (0000:b7:00.0)
EAL: Failed to attach device on primary process
[2024-04-17 06:13:01.922977] nvme.c: 821:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2024-04-17 06:13:01.922989] nvme.c: 898:spdk_nvme_probe: *ERROR*: Create probe context failed
spdk_nvme_probe() failed for transport address '0000:b7:00.0'
spdk_nvme_perf: errors occurred

**Comment by jimharris** [comment]
Please make sure you have attached the SSD to vfio-pci or uio_pci_generic using the `scripts/setup.sh` script.

If you run `scripts/setup.sh status` you should see which driver your SSD is attached to.

**Comment by vicentdsmin** [comment]
![Image](https://github.com/user-attachments/assets/42b7481d-7b90-47e7-b188-a5d18c4c3920)
why has this error？
