### ISSUE TITLE
raid1: nvme connect on a raid1 with a rebuild process will crash spdk_tgt

### ISSUE THREAD

**Issue by arsiesys** [spdk/spdk#3343]
# Sighting report

Using "nvme connect" to a raid1 rdma nvmeof exposed volume will crash spdk if a rebuild process is in progress:
```
[2024-04-17 19:17:09.081699] bdev_raid.c:2782:raid_bdev_process_thread_init: *NOTICE*: Started rebuild on raid bdev test
nvmf_tgt: bdev_raid.c:135: raid_bdev_channel_get_module_ctx: Assertion `raid_ch->module_channel != NULL' failed.
```

## Expected Behavior

nvme connect successful and be able to use the raid1 during the rebuild process

## Current Behavior

spdk_tgt will crash and the nvme client machine will be stuck in a bad state (can't disconnect the nvme connecting device) requiring a hard reboot (probably the kernel 6.5 that didn't handle very well this situation).

## Steps to Reproduce

```
./scripts/rpc.py bdev_lvol_create -l test local0 100000
./scripts/rpc.py bdev_lvol_create -l test local1 100000
./scripts/rpc.py bdev_lvol_create -l test local2 100000
sleep 2
./scripts/rpc.py bdev_raid_create -n test -r raid1 -b "test/local0 test/local1" -s
./scripts/rpc.py bdev_raid_remove_base_bdev test/local1
sleep 2
./scripts/rpc.py bdev_raid_add_base_bdev test test/local2
./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 test
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.1.10 -s 4420
nvme connect -t rdma -a 192.168.1.10 -s 4420 -n nqn.2016-06.io.spdk:cnode1 -i 8
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK: master 65b4e17c6736ae69784017a5d5557443b6997899
OS: ubuntu 22.04
kernel: 6.5.0-27-generic

**Comment by apaszkie** [comment]
Can you check if this patch helps? https://review.spdk.io/gerrit/c/spdk/spdk/+/22848

**Comment by arsiesys** [comment]
Hi,

Thanks for this light-speed patch!

It seems to solve the issue (no crash and nvme connect successful).

**Comment by arsiesys** [comment]
Hum, it works with the reproduce steps I posted earlier, but in my actual lab I got the error again, let me dig deeper and confirm.

**Comment by arsiesys** [comment]
All good, the issue was between the chair and the keyboard, I deployed the wrong commit on the lab :). The patch works perfectly.

**Comment by apaszkie** [comment]
Great! Thank you for confirming.

**Comment by apaszkie** [comment]
> However, the branch is conflicting with this patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/22641

I rebased that series onto this fix, should be good now.
