### ISSUE TITLE
[nvmf_device_removal_pci_remove] Cannot contact WFP13: java.lang.InterruptedException

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#3345]
# CI Intermittent Failure

Issue occurs in `nvmf_device_removal_pci_remove` test where RDMA devices are added/removed as part of the test. At some point Jenkins loses the connection to the machine, resulting in aborting the job after a while.
There were other issues related to this test like https://github.com/spdk/spdk/issues/3116, but they failed at bit different points and were tracked down to specific kernel versions - although not with 100% certainty, just in practice.

For now it is hard to tell more, nothing except build.log is available. 

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/120519/archive/nvmf-phy-autotest_69489/build.log

## Execution failed at

```
00:22:56.137   02:47:55	-- target/device_removal.sh@145 -- # remove_one_nic mlx_0_1
00:22:56.137   02:47:55	-- target/device_removal.sh@66 -- # dev_name=mlx_0_1
00:22:56.137   02:47:55	-- target/device_removal.sh@67 -- # echo 1
00:22:56.137    02:47:55	-- target/device_removal.sh@67 -- # get_pci_dir mlx_0_1
00:22:56.137    02:47:55	-- target/device_removal.sh@61 -- # dev_name=mlx_0_1
00:22:56.137    02:47:55	-- target/device_removal.sh@62 -- # readlink -f /sys/bus/pci/devices/0000:18:00.1/net/mlx_0_1/device
00:22:56.137  [2024-04-18 02:47:55.605068] rdma.c:3610:nvmf_rdma_handle_device_removal: *NOTICE*: Port 192.168.100.9:4420 on device mlx5_1 is being removed.
00:22:56.137  [2024-04-18 02:47:55.605152] rdma_verbs.c: 113:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
00:22:56.137  [2024-04-18 02:47:55.607554] rdma_verbs.c: 113:spdk_rdma_qp_disconnect: *ERROR*: rdma_disconnect failed, errno Invalid argument (22)
00:22:56.137  [2024-04-18 02:47:55.607573] rdma.c: 916:nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 97
00:24:23.816  Cannot contact WFP13: java.lang.InterruptedException
00:44:26.037  Cancelling nested steps due to timeout
00:44:26.039  Could not connect to WFP13 to send interrupt signal to process
```

**Comment by mikeBashStuff** [comment]
These tests are still triggering a kernel panic. The https://bugzilla.kernel.org/show_bug.cgi?id=218288 was basically rejected due to the fact that we were behind the mainline a few releases. Considering that, we went with a bump to then latest available build. The panic seen in that bug was essentially gone under smoketesting, but the panic here is a new one:

```
Apr 18 00:47:55 10.211.164.42 [36238.985287] mlx5_core 0000:18:00.1: E-Switch: Unload vfs: mode(LEGACY), nvfs(0), necvfs(0), active vports(0)
Apr 18 00:47:55 10.211.164.42 [36239.005563] mlx5_core 0000:18:00.1: E-Switch: Disable: mode(LEGACY), nvfs(0), necvfs(0), active vports(0)
Apr 18 00:47:57 10.211.164.42 [36240.828358] mlx5_core 0000:18:00.1: E-Switch: Disable: mode(LEGACY), nvfs(0), necvfs(0), active vports(0)
Apr 18 00:47:58 10.211.164.42 [36241.698713] mlx5_core 0000:18:00.1: E-Switch: cleanup
Apr 18 00:48:59 10.211.164.42 [36302.716121] mlx5_core 0000:18:00.1: wait_func:1155:(pid 984354): TEARDOWN_HCA(0x103) timeout. Will cause a leak of a command resource
Apr 18 00:48:59 10.211.164.42 [36302.729127] mlx5_core 0000:18:00.1: mlx5_function_close:1288:(pid 984354): tear_down_hca failed, skip cleanup
Apr 18 00:48:59 10.211.164.42 [36302.849883] pci 0000:18:00.1: [15b3:1013] type 00 class 0x020000
Apr 18 00:48:59 10.211.164.42 [36302.856828] pci 0000:18:00.1: reg 0x10: [mem 0x387ffc000000-0x387ffdffffff 64bit pref]
Apr 18 00:48:59 10.211.164.42 [36302.865607] pci 0000:18:00.1: reg 0x30: [mem 0xfff00000-0xffffffff pref]
Apr 18 00:48:59 10.211.164.42 [36302.873232] pci 0000:18:00.1: PME# supported from D3cold
Apr 18 00:48:59 10.211.164.42 [36302.880346] pci 0000:18:00.1: Adding to iommu group 9
Apr 18 00:48:59 10.211.164.42 [36302.886375] pci 0000:18:00.1: BAR 0: assigned [mem 0x387ffc000000-0x387ffdffffff 64bit pref]
Apr 18 00:48:59 10.211.164.42 [36302.895703] pci 0000:18:00.1: BAR 6: assigned [mem 0x9da00000-0x9dafffff pref]
Apr 18 00:48:59 10.211.164.42 [36302.906702] mlx5_core 0000:18:00.1: firmware version: 12.28.2006
Apr 18 00:48:59 10.211.164.42 [36302.913267] mlx5_core 0000:18:00.1: 126.016 Gb/s available PCIe bandwidth (8.0 GT/s PCIe x16 link)
Apr 18 00:48:59 10.211.164.42 [36303.236425] mlx5_core 0000:18:00.1: E-Switch: Total vports 2, per vport: max uc(1024) max mc(16384)
Apr 18 00:48:59 10.211.164.42 [36303.264868] mlx5_core 0000:18:00.1: Port module event: module 1, Cable unplugged
Apr 18 00:49:00 10.211.164.42 [36303.597953] general protection fault, probably for non-canonical address 0x50642201000008: 0000 [#1] PREEMPT SMP NOPTI
Apr 18 00:49:00 10.211.164.42 [36303.609345] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G           OE     -------  ---  6.7.0-68.fc38.x86_64 #1
Apr 18 00:49:00 10.211.164.42 [36303.619538] Hardware name: Intel Corporation S2600WFT/S2600WFT, BIOS SE5C620.86B.02.01.0013.121520200651 12/15/2020
Apr 18 00:49:00 10.211.164.42 [36303.630354] RIP: 0010:__run_timers+0x1e8/0x2c0
Apr 18 00:49:00 10.211.164.42 [36303.635193] Code: 00 49 8b 06 49 c7 47 08 00 00 00 00 48 85 c0 74 6b 4d 8b 2e 4d 89 6f 08 66 90 49 8b 45 00 49 8b 55 08 48 89 02 48 85 c0 74 04 <48> 89 50 08 4d 8b 65 18 49 c7 45 08 00 00 00 00 49 89 6d 00 4d 85
Apr 18 00:49:00 10.211.164.42 [36303.654733] RSP: 0018:ffffb29a80003ed8 EFLAGS: 00010006
Apr 18 00:49:00 10.211.164.42 [36303.660360] RAX: 0050642201000000 RBX: 00000001022560c0 RCX: ffff9c321f6222c0
Apr 18 00:49:00 10.211.164.42 [36303.667896] RDX: ffffb29a80003f00 RSI: 0000000000000088 RDI: ffff9c321f6222e8
Apr 18 00:49:00 10.211.164.42 [36303.675437] RBP: dead000000000122 R08: 0000000004089584 R09: ffff9c321f6222e8
Apr 18 00:49:00 10.211.164.42 [36303.682979] R10: 0000000000000004 R11: 000000000000090b R12: 0000000000000001
Apr 18 00:49:00 10.211.164.42 [36303.690518] R13: ffff9c2c276c4988 R14: ffffb29a80003f00 R15: ffff9c321f6222c0
Apr 18 00:49:00 10.211.164.42 [36303.698061] FS:  0000000000000000(0000) GS:ffff9c321f600000(0000) knlGS:0000000000000000
Apr 18 00:49:00 10.211.164.42 [36303.706567] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
```
full trace is not available since at that point netconsole drops entirely and kernel just jumps to a reboot. Funnily, similar trace was seen under 6.1.14 (mentioned in the bug above) which in the stack trace points at `mlx5_ib` paths.

This could be reported upstream, but considering that 6.7 is now again behind the mainline, I don't reckon such issue would get any traction. So the only sensible option to mitigate this issue is to disable the affected test suite again.

**Comment by mikeBashStuff** [comment]
In general, whenever this test suite kicks in, there's quite huge spike in power usage which also causes equal spike in a temperature.  One thing that we may have issues with keeping proper temperature in the server room but this seems to be one of the factors that leads to the kernel panic.  And for some nodes throttling seems to be a recurring theme, for instance: https://ci.spdk.io/results/autotest-per-patch/builds/120534/archive/nvmf-phy-autotest_69513/index.html (see `power` artifacts):

```
(10:43:05 CEST) ###### Throttling Node1 Status: Throttled ######
(10:43:05 CEST) CPU19: Throttled (count: 5, time: 0s)
(10:43:05 CEST) CPU22: Throttled (count: 54, time: 0s)
(10:43:05 CEST) CPU55: Throttled (count: 5, time: 0s)
(10:43:05 CEST) CPU58: Throttled (count: 44, time: 0s)
```
These counters don't increase constantly with each read and the time of "last" throttling is quite short (in ms), but it happens nonetheless.

**Comment by mikeBashStuff** [comment]
Unfortunately, similar crash (not temp related) happens under our staging where we spin latest 6.8 kernel builds available for fedora{38,39}.

**Comment by jimharris** [comment]
[Bug Scrub] @mikeBashStuff to submit issue with upstream for this kernel panic.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_121631.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @apaszkie. log: https://ci.spdk.io/public_build/autotest-per-patch_121910.html

**Comment by mikeBashStuff** [comment]
Haven't got time to prepare the report, will try to do it till the end of this week.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_123522.html

**Comment by mikeBashStuff** [comment]
Small update, there's an email thread available [here](https://lore.kernel.org/netdev/c51bef25-e8c5-492d-bb80-965b7f8542f7@nvidia.com/T/#t) regarding this issue.

**Comment by mikeBashStuff** [comment]
I give up. @tomzawadzki please review https://review.spdk.io/gerrit/c/spdk/spdk/+/23742 whenever you have a chance.

**Comment by mikeBashStuff** [comment]
Tests disabled, closing the issue. Fingers crossed this will get more attention on the kernel side.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_128432.html
