### ISSUE TITLE
Connection closed with partial response

### ISSUE THREAD

**Issue by ziyizhou0813** [spdk/spdk#3348]
sudo ./scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB      659 /   1024

NVMe devices
BDF		Vendor	Device	NUMA	Driver		Device name
0000:06:00.0	144d	a80a	0	nvme			nvme0
0000:07:00.0	15b7	5006	0	uio_pci_generic		-

I/OAT DMA
BDF		Vendor	Device	NUMA	Driver

IDXD DMA
BDF		Vendor	Device	NUMA	Driver

virtio
BDF		Vendor	Device	NUMA	Driver		Device name
VMD
BDF		Numa Node	Driver Name
$ sudo ./scripts/rpc.py bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:07:00.0
NVMe1n1
$ sudo ./scripts/rpc.py bdev_get_bdevs
Connection closed with partial response:

sudo ./app/iscsi_tgt/iscsi_tgt 
Starting SPDK v20.04 git sha1 c4e28a51a / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: iscsi --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4993 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 371:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
nvme_opal.c: 829:opal_discovery0_end: *ERROR*: Opal Not Supported.
bdev_nvme.c:1426:create_ctrlr: *ERROR*: Failed to initialize Opal

why?

**Comment by jimharris** [comment]
> sudo ./scripts/setup.sh status Hugepages node hugesize free / total node0 1048576kB 0 / 0 node0 2048kB 659 / 1024
> 
> NVMe devices BDF Vendor Device NUMA Driver Device name 0000:06:00.0 144d a80a 0 nvme nvme0 0000:07:00.0 15b7 5006 0 uio_pci_generic -
> 
> I/OAT DMA BDF Vendor Device NUMA Driver
> 
> IDXD DMA BDF Vendor Device NUMA Driver
> 
> virtio BDF Vendor Device NUMA Driver Device name VMD BDF Numa Node Driver Name $ sudo ./scripts/rpc.py bdev_nvme_attach_controller -b NVMe1 -t PCIe -a 0000:07:00.0 NVMe1n1 $ sudo ./scripts/rpc.py bdev_get_bdevs Connection closed with partial response:
> 
> sudo ./app/iscsi_tgt/iscsi_tgt Starting SPDK v20.04 git sha1 [c4e28a5](https://github.com/spdk/spdk/commit/c4e28a51a65f148719a70a092e6329d249479b25) / DPDK 19.11.0 initialization... [ DPDK EAL parameters: iscsi --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4993 ] EAL: No available hugepages reported in hugepages-1048576kB EAL: VFIO support initialized app.c: 646:spdk_app_start: _NOTICE_: Total cores available: 1 reactor.c: 371:_spdk_reactor_run: _NOTICE_: Reactor started on core 0 nvme_opal.c: 829:opal_discovery0_end: _ERROR_: Opal Not Supported. bdev_nvme.c:1426:create_ctrlr: _ERROR_: Failed to initialize Opal
> 
> why?

This version of SPDK is not supported. Please retry with v24.01 or latest master.
