### ISSUE TITLE
Creating an LVOL with all free clusters in LVS reports unexpected/reduced size for LVOL

### ISSUE THREAD

**Issue by noorshaheennoorudheen** [spdk/spdk#335]
Creating an LVOL using all the reported free clusters in LVS only reports a reduced LVOL size. 

As shown in "Steps to Reproduce tab, creating a single LVS out of the entire Intel 3.2TB P4500 and then creating a single LVOL volume out of the entire LVS only create/report ~999GB

## Context (Environment including OS version, SPDK version, etc.)
SPDK: version18.04
OS: Fedora Core 26
Kernel: 4.11.8-300.fc26.x86_64
Drive Used: Intel NVMe P4500 ( 3.2 TB)

## Steps to Reproduce
1. Compile SPDK with --with-rdma flag enabled 
2.  Start the nvmf_tgt application 
     _app/nvmf_tgt/nvmf_tgt   -c nvmf.sample.lvol.conf  -s 1024 -r 127.0.0.1_
3. Create an LVS out of the entire drive 
     _./rpc.py -s 127.0.0.1 construct_lvol_store Nvme0n1 LVS0_
4. Get the LVS details
[root@fmdcppzona19 scripts]# _./rpc.py -s 127.0.0.1 get_lvol_stores_
[
  {
    "uuid": "010e4ccc-d543-467e-b894-e8ba18a08ea1",
    "base_bdev": "Nvme0n1",
    **"free_clusters": 762344,**
    "cluster_size": 4194304,
    "total_data_clusters": 762344,
    "block_size": 4096,
    "name": "LVS0"
  }
]
    Please note there are 762344 free clusters and cluster size 4194304
5. Construct an LVOL consuming the entire free clusters
    _./rpc.py -s 127.0.0.1 construct_lvol_bdev -l LVS0 lvol0 3049376_
    The size is calculated by multiplying free clusters with cluster size and then converting to MB to get 
    3049376 (~2.9 TB)
6. Confirm all the free clusters are claimed by using get_lvol_store
    [root@fmdcppzona19 scripts]# _./rpc.py -s 127.0.0.1 get_lvol_stores_
[
  {
    "uuid": "010e4ccc-d543-467e-b894-e8ba18a08ea1",
    "base_bdev": "Nvme0n1",
    **"free_clusters": 0,**
    "cluster_size": 4194304,
    "total_data_clusters": 762344,
    "block_size": 4096,
    "name": "LVS0"
  }
]
    
7. Expose the LVM over NVMeOF to the initiator
    _/rpc.py -s 127.0.0.1 construct_nvmf_subsystem nqn.2016-06.io.spdk:cnode0 '' ''  -s SPDK00000000000000
    ./rpc.py -s 127.0.0.1 nvmf_subsystem_allow_any_host -e nqn.2016-06.io.spdk:cnode0
    ./rpc.py -s 127.0.0.1 nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode0 -t RDMA -a 100.100.1.99 -s 4420
    ./rpc.py -s 127.0.0.1 nvmf_subsystem_add_host nqn.2016-06.io.spdk:cnode0 nqn.2016-06.io.spdk:host0_
    _./rpc.py -s 127.0.0.1 nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode0 LVS0/lvol0_
8. Connect to the target from the initiator machine
    _nvme connect -t rdma -a 100.100.1.98 -n nqn.2016-06.io.spdk:cnode0 -s 4420_
9. Do "nvme list" to figure out the size of the listed namespace
    [root@fmdcppzona20 ~]# _nvme list_
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     SPDK00000000000000   SPDK bdev Controller                     1         **998.48  GB / 998.48**  GB      4 KiB +  0 B   18.07

10. We can only 998.4GB reported instead of 2.9TB

## Expected Behavior
Entire LVOL size should be listed as 2.9TB

## Current Behavior
Currently, we only see 998.4GB  being listed.

## Possible Solution
Had a first level investigation and had few clues on the possible reason. Right now keeping this blank as it would be premature to put those data here.

**Comment by dverkamp-intel** [comment]
I'm attempting to reproduce this  on my system, but it seems to work OK.

I have a slightly different setup (4.00 TB drive), but I think the basic properties should be the same; I see a correctly-sized /dev/nvme0n1 when exporting a ~4TB lvol via NVMe-oF to the kernel host and using "nvme list".

I'm testing with:
- SPDK nvmf_tgt from master (f387d321338578abbc5c159c1849418f99671d80)
- Linux 4.16.3 (host system, also running the SPDK target on this system in loopback)
- nvme-cli-1.4-4 from Fedora 28

Could you report which versions of each component above you are using?

**Comment by dverkamp-intel** [comment]
Also, the output of `nvme id-ns /dev/nvme0n1` would be very helpful.

**Comment by noorshaheennoorudheen** [comment]
Details as requested from the system where the issue is reported.

**SPDK Version :** 
_git show --oneline -s_
**ddc63f07** (HEAD -> master, origin/master, origin/HEAD) bdev: change spdk_bdev_free_io return type to void

**System Details**
Linux 4.11.8-300.fc26.x86_64 (host system, also running the SPDK target on this system in loopback)
nvme cli version 1.3 from Fedora 26

_[root@fmdcppzona26 ~]# nvme id-ns /dev/nvme0n1
NVME Identify Namespace 1:
nsze    : 0xe87a000
ncap    : 0xe87a000
nuse    : 0xe87a000
nsfeat  : 0
nlbaf   : 0
flbas   : 0
mc      : 0
dpc     : 0
dps     : 0
nmic    : 0x1
rescap  : 0
fpi     : 0
nawun   : 0
nawupf  : 0
nacwu   : 0
nabsn   : 0
nabo    : 0
nabspf  : 0
noiob   : 0
nvmcap  : 0
nguid   : 00000000000000000000000000000000
eui64   : 0000000000000000
lbaf  0 : ms:0   lbads:12 rp:0 (in use)
[root@fmdcppzona26 ~]#_

**Comment by jimharris** [comment]
Thanks!  LBA count matches the 998GB reported earlier.

Could you post the results from:

examples/blob/cli/blobcli -c nvmf.sample.lvol.conf -D -b Nvme0n1

This will dump the blobstore metadata contents of your logical volume store and help narrow down where we should be looking next.

I saw your original report was against SPDK 18.04, but the latest nvme-cli output was using master.  When using master, did you rebuild the logical volume store and the single logical volume?  If not, could you try that on master as well?

**Comment by dverkamp-intel** [comment]
My 4 TB device was formatted with 4 KB sectors, as @jimharris pointed out; I have reformatted it with 512-byte sectors, and now I can reproduce the problem.  There are several places where we store numbers of blocks in uint32_t variables; lib/blob will need a thorough audit to find all of them and make sure we are not truncating anywhere.

**Comment by noorshaheennoorudheen** [comment]
@jimharris: Please see the output below.

[root@fmdcppzona21 spdk]# examples/blob/cli/blobcli -c nvmf.sample.lvol.conf -D -b Nvme0n1
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: blobcli -c 0x003 --file-prefix=spdk_pid4255 ]
EAL: Detected 72 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid4255_unix
EAL: Probing VFIO support...
app.c: 524:spdk_app_start: *NOTICE*: Total cores available: 2
reactor.c: 659:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 451:_spdk_reactor_run: *NOTICE*: Reactor started on core 1 on socket 0
reactor.c: 451:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
copy_engine_ioat.c: 338:copy_engine_ioat_read_config_file_params: *WARNING*: "Disable" option is deprecated and will be removed in a future release.
copy_engine_ioat.c: 339:copy_engine_ioat_read_config_file_params: *WARNING*: IOAT is now disabled by default. It may be enabled by "Enable Yes"
EAL: PCI device 0000:5e:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:5f:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:88:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:89:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:b1:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:b2:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:d8:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:d9:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
Init blobstore using bdev Product Name: NVMe disk
Signature: "SPDKBLOB" (OK)
Version: 3
CRC: 0xbca617b7 (OK)
Blobstore Type: LVOLSTORE
Cluster Size: 4194304
Super Blob ID: 4294967296
Clean: 1
Used Metadata Page Mask Start: 1
Used Metadata Page Mask Length: 24
Used Cluster Mask Start: 25
Used Cluster Mask Length: 24
Used Blob ID Mask Start: 49
Used Blob ID Mask Length: 24
Metadata Start: 73
Metadata Length: 763090
=========
Metadata Page Index: 0 (0x0)
Blob ID: 0x100000000
CRC: 0x91c358b5 (OK)
XATTR: name = "uuid"
       value = "?"
               33 30 64 66 30 61 39 33 2d 63 31 37 39 2d 34 61
               38 39 2d 62 30 36 65 2d 30 36 63 61 31 34 65 32
               39 38 63 35 00
XATTR: name = "name"
       value = "LVS0"
               4c 56 53 30 00
=========
Metadata Page Index: 1 (0x1)
Blob ID: 0x100000001
CRC: 0x7e3ccd6d (OK)
XATTR: name = "name"
       value = "lvol0"
               6c 76 6f 6c 30 00 00 00 00 00 00 00 00 00 00 00
               00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
               00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
               00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
XATTR: name = "uuid"
       value = "?"
               66 35 30 38 38 30 63 32 2d 35 30 34 62 2d 34 36
               64 36 2d 39 66 31 38 2d 61 64 34 33 32 64 62 34
               37 64 38 62 00
Allocated Extent - Start: 746 Length: 238056

**Comment by jimharris** [comment]
We have checked in a patch to master that should fix this issue.  Could you pull latest master and confirm?

https://review.gerrithub.io/#/c/spdk/spdk/+/416231/

Thanks,

-Jim

**Comment by noorshaheennoorudheen** [comment]
I just verified with the changes and it gives me the entire volume size. Thanks for the fix, closing the bug
