### ISSUE TITLE
[scheduler_create_thread] Assertion 'reactor->in_interrupt' failed.

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3351]
00:09:28.576   20:36:52	-- scheduler/scheduler.sh@23 -- # rpc_cmd --plugin scheduler_plugin scheduler_thread_set_active 11 50
00:09:28.576   20:36:52	-- common/autotest_common.sh@549 -- # xtrace_disable
00:09:28.576   20:36:52	-- common/autotest_common.sh@10 -- # set +x
00:09:29.513   20:36:52	-- common/autotest_common.sh@577 -- # [[ 0 == 0 ]]
00:09:29.513    20:36:52	-- scheduler/scheduler.sh@25 -- # rpc_cmd --plugin scheduler_plugin scheduler_thread_create -n deleted -a 100
00:09:29.513    20:36:52	-- common/autotest_common.sh@549 -- # xtrace_disable
00:09:29.513    20:36:52	-- common/autotest_common.sh@10 -- # set +x
00:09:30.889    20:36:54	-- common/autotest_common.sh@577 -- # [[ 0 == 0 ]]
00:09:30.889   20:36:54	-- scheduler/scheduler.sh@25 -- # thread_id=12
00:09:30.889   20:36:54	-- scheduler/scheduler.sh@26 -- # rpc_cmd --plugin scheduler_plugin scheduler_thread_delete 12
00:09:30.889   20:36:54	-- common/autotest_common.sh@549 -- # xtrace_disable
00:09:30.889   20:36:54	-- common/autotest_common.sh@10 -- # set +x
00:09:31.825   20:36:55	-- common/autotest_common.sh@577 -- # [[ 0 == 0 ]]
00:09:31.825  
00:09:31.825  real	0m3.371s
00:09:31.825  user	0m0.027s
00:09:31.825  sys	0m0.004s
00:09:31.825   20:36:55	-- common/autotest_common.sh@1112 -- # xtrace_disable
00:09:31.825   20:36:55	-- common/autotest_common.sh@10 -- # set +x
00:09:31.825  ************************************
00:09:31.825  END TEST scheduler_create_thread
00:09:31.825  ************************************
00:09:32.084   20:36:55	-- scheduler/scheduler.sh@45 -- # trap - SIGINT SIGTERM EXIT
00:09:32.084   20:36:55	-- scheduler/scheduler.sh@46 -- # killprocess 180191
00:09:32.084   20:36:55	-- common/autotest_common.sh@936 -- # '[' -z 180191 ']'
00:09:32.084   20:36:55	-- common/autotest_common.sh@940 -- # kill -0 180191
00:09:32.084    20:36:55	-- common/autotest_common.sh@941 -- # uname
00:09:32.084   20:36:55	-- common/autotest_common.sh@941 -- # '[' Linux = Linux ']'
00:09:32.084    20:36:55	-- common/autotest_common.sh@942 -- # ps --no-headers -o comm= 180191
00:09:32.084   20:36:55	-- common/autotest_common.sh@942 -- # process_name=reactor_2
00:09:32.084   20:36:55	-- common/autotest_common.sh@946 -- # '[' reactor_2 = sudo ']'
00:09:32.084   20:36:55	-- common/autotest_common.sh@954 -- # echo 'killing process with pid 180191'
00:09:32.084  killing process with pid 180191
00:09:32.084   20:36:55	-- common/autotest_common.sh@955 -- # kill 180191
00:09:32.084   20:36:55	-- common/autotest_common.sh@960 -- # wait 180191
00:09:32.342  [2024-04-23 20:36:55.769203] scheduler.c: 360:test_shutdown: *NOTICE*: Scheduler test application stopped.
00:09:33.279  scheduler: reactor.c:1419: reactor_schedule_thread_event: Assertion `reactor->in_interrupt' failed.
00:09:38.602  /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 960: 180191 Aborted                 (core dumped) $testdir/scheduler -m 0xF -p 0x2 --wait-for-rpc -f
00:09:38.602    20:37:01	-- common/autotest_common.sh@960 -- # trap - ERR
00:09:38.602    20:37:01	-- common/autotest_common.sh@960 -- # print_backtrace
00:09:38.602    20:37:01	-- common/autotest_common.sh@1139 -- # [[ ehxBET =~ e ]]
00:09:38.602    20:37:01	-- common/autotest_common.sh@1141 -- # args=('180191')
00:09:38.602    20:37:01	-- common/autotest_common.sh@1141 -- # local args
00:09:38.602    20:37:01	-- common/autotest_common.sh@1143 -- # xtrace_disable
00:09:38.602    20:37:01	-- common/autotest_common.sh@10 -- # set +x
00:09:38.602  ========== Backtrace start: ==========
00:09:38.602  
00:09:38.602  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:960 -> killprocess(["180191"])
00:09:38.602       ...
00:09:38.602     955 				kill $1
00:09:38.602     956 			fi
00:09:38.602     957 	
00:09:38.602     958 			# wait for the process regardless if its the dummy sudo one
00:09:38.602     959 			# or the actual app - it should terminate anyway
00:09:38.602  => 960 			wait $1
00:09:38.602     961 		else
00:09:38.602     962 			# the process is not there anymore
00:09:38.602     963 			echo "Process with pid $1 is not found"
00:09:38.602     964 		fi
00:09:38.602     965 	}
00:09:38.602       ...
00:09:38.602  in /home/vagrant/spdk_repo/spdk/test/event/scheduler/scheduler.sh:46 -> main([])
00:09:38.602       ...
00:09:38.602     41  	
00:09:38.602     42  	# basic integrity test
00:09:38.602     43  	run_test "scheduler_create_thread" scheduler_create_thread
00:09:38.602     44  	
00:09:38.602     45  	trap - SIGINT SIGTERM EXIT
00:09:38.602  => 46  	killprocess $scheduler_pid
00:09:38.602       ...
00:09:38.602  
00:09:38.602  ========== Backtrace end ==========
00:09:38.602    20:37:01	-- common/autotest_common.sh@1180 -- # return 0
00:09:38.602    20:37:01	-- common/autotest_common.sh@1111 -- # trap - ERR
00:09:38.602    20:37:01	-- common/autotest_common.sh@1111 -- # print_backtrace
00:09:38.602    20:37:01	-- common/autotest_common.sh@1139 -- # [[ ehxBET =~ e ]]
00:09:38.602    20:37:01	-- common/autotest_common.sh@1141 -- # args=('/home/vagrant/spdk_repo/spdk/test/event/scheduler/scheduler.sh' 'event_scheduler')
00:09:38.602    20:37:01	-- common/autotest_common.sh@1141 -- # local args

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_120893.html

**Comment by jimharris** [comment]
This was rebased on top of https://review.spdk.io/gerrit/c/spdk/spdk/+/22878 which was just merged. I'm fairly confident that patch is the cause of this intermittent failure. @apaszkie could you take a look?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ankit-sam. log: https://ci.spdk.io/public_build/autotest-per-patch_120977.html

**Comment by jimharris** [comment]
I've pushed a revert for the patch in question: https://review.spdk.io/gerrit/c/spdk/spdk/+/22913.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_121029.html

**Comment by jimharris** [comment]
> I've pushed a revert for the patch in question: https://review.spdk.io/gerrit/c/spdk/spdk/+/22913.

Revert has been merged. Keeping this issue open for now to collect any additional CI failures related to this.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_121270.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_121250.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_121277.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_121282.html

**Comment by jimharris** [comment]
Closing, the revert was merged.

https://review.spdk.io/gerrit/c/spdk/spdk/+/22926 has been pushed which is the second attempt for fixing #3340.
