### ISSUE TITLE
Inconsistent bash shellcheck results

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3352]
This CI runs fails with a bash shell check error:

https://review.spdk.io/gerrit/c/spdk/spdk/+/22883/3
https://ci.spdk.io/public_build/autotest-per-patch_120901.html

But next patch in series, with no changes to any shell scripts, passes:

https://review.spdk.io/gerrit/c/spdk/spdk/+/22838/6
https://ci.spdk.io/public_build/autotest-per-patch_120900.html

**Comment by mikeBashStuff** [comment]
> But next patch in series, with no changes to any shell scripts, passes:

It passes because shellcheck is not being executed there as there're no changes in the bash scripts (this should be expected since in context of shfmt, shellcheck CI uses `CHECK_FORMAT_ONLY_DIFF`).

**Comment by jimharris** [comment]
> > But next patch in series, with no changes to any shell scripts, passes:
> 
> It passes because shellcheck is not being executed there as there're no changes in the bash scripts (this should be expected since in context of shfmt, shellcheck CI uses `CHECK_FORMAT_ONLY_DIFF`).

Thanks for the explanation @mikeBashStuff.
