### ISSUE TITLE
There was a low probability that core dump occurs during polling when the CUSE is enabled.

### ISSUE THREAD

**Issue by Zhanghongtao2417** [spdk/spdk#3353]
# Sighting report

spdk_nvme_cuse_unregister and spdk_nvme_ctrlr_process_admin_completions running at the same time，There was a low probability that core dump occurs

stack（ ctrlr->external_io_msgs was setted NULL after Judgment）：
Thread 1 (Thread 0x7f3e63fff640 (LWP 122122)):
#0  0x00007f3e6afc77d0 in rte_ring_dequeue_burst_elem (available=<optimized out>, n=<optimized out>, esize=<optimized out>, obj_table=<optimized out>, r=<optimized out>) at /usr/lib64/dpdk/pmds-22clude/rte_ring_elem.h:676
#1  rte_ring_dequeue_burst (available=<optimized out>, n=<optimized out>, obj_table=<optimized out>, r=<optimized out>) at /usr/lib64/dpdk/pmds-22.0/include/rte_ring.h:801
#2  spdk_ring_dequeue (ring=0x0, objs=objs@entry=0x7f3e63ffdb00, count=count@entry=8) at env.c:435
#3  0x00007f3e6af98bd1 in nvme_io_msg_process (ctrlr=ctrlr@entry=0x200001c4e180) at nvme_io_msg.c:92
#4  0x00007f3e6af7c79a in spdk_nvme_ctrlr_process_admin_completions (ctrlr=ctrlr@entry=0x200001c4e180) at nvme_ctrlr.c:3522

reason：
![image](https://github.com/spdk/spdk/assets/105726523/2098c490-727a-4f97-a26d-05f4e54cd9f4)

## Expected Behavior

The program is running properly.

## Current Behavior

core dump occurs （low probability）

## Possible Solution

add ctrlr->ctrlr_lock while nvme_io_msg_ctrlr_detach() & nvme_io_msg_ctrlr_register()

## Steps to Reproduce

1.one thread：create nvme ctrlr with cuse ，and call spdk_nvme_cuse_unregister
2.another thread ：submit admin cmd and polling ,or keeping call spdk_nvme_ctrlr_process_admin_completions repetitively

**Comment by m-spiewak** [comment]
@Zhanghongtao2417 @jimharris @tomzawadzki It seems the fix is ready and just needs to be submitted as a patch, not as a pull request. Assigning the issue back to the submitter.

**Comment by Zhanghongtao2417** [comment]
> @Zhanghongtao2417 @jimharris @tomzawadzki It seems the fix is ready and just needs to be submitted as a patch, not as a pull request. Assigning the issue back to the submitter.

OK，I submitted it as a patch。
https://review.spdk.io/gerrit/c/spdk/spdk/+/22927
