### ISSUE TITLE
Test build failing in Prologue stage with no logs available

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3356]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_121194.html

## Execution failed at

Various points in the pipeline, but generally on `git clone`, `fetch`, `submodule update` or similar.
All caused by local network issues which are, unfortunately, out of our hands to fix.

Let's use this issue to log how many failures were there and to automatically retrigger tests. We can close this after a few days of inactivity if no new occurrences are reported.

```
18:02:37  [Pipeline] }
18:02:37  ERROR: Execution failed
18:02:37  hudson.plugins.git.GitException: Command "git submodule update --init --recursive --reference /var/ci_repos/spdk_multi isa-l" returned status code 1:
18:02:37  stdout: 
18:02:37  stderr: Cloning into '/var/jenkins/workspace/autotest-per-patch_2/spdk/isa-l'...
18:02:37  fatal: unable to access 'https://github.com/spdk/isa-l.git/': CONNECT tunnel failed, response 503
18:02:37  fatal: clone of 'https://github.com/spdk/isa-l.git' into submodule path '/var/jenkins/workspace/autotest-per-patch_2/spdk/isa-l' failed
18:02:37  Failed to clone 'isa-l'. Retry scheduled
18:02:37  Cloning into '/var/jenkins/workspace/autotest-per-patch_2/spdk/isa-l'...
18:02:37  fatal: unable to access 'https://github.com/spdk/isa-l.git/': CONNECT tunnel failed, response 503
18:02:37  fatal: clone of 'https://github.com/spdk/isa-l.git' into submodule path '/var/jenkins/workspace/autotest-per-patch_2/spdk/isa-l' failed
18:02:37  Failed to clone 'isa-l' a second time, aborting
18:02:37  
```

```
18:06:42  hudson.plugins.git.GitException: Command "git submodule update --init --recursive --reference /var/ci_repos/spdk_multi isa-l" returned status code 1:
18:06:42  stdout: 
18:06:42  stderr: Cloning into '/var/jenkins/workspace/autotest-per-patch/spdk/isa-l'...
18:06:42  error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
18:06:42  fatal: expected 'acknowledgments'
18:06:42  fatal: clone of 'https://github.com/spdk/isa-l.git' into submodule path '/var/jenkins/workspace/autotest-per-patch/spdk/isa-l' failed
18:06:42  Failed to clone 'isa-l'. Retry scheduled
18:06:42  Cloning into '/var/jenkins/workspace/autotest-per-patch/spdk/isa-l'...
18:06:42  fatal: unable to access 'https://github.com/spdk/isa-l.git/': CONNECT tunnel failed, response 503
18:06:42  fatal: clone of 'https://github.com/spdk/isa-l.git' into submodule path '/var/jenkins/workspace/autotest-per-patch/spdk/isa-l' failed
18:06:42  Failed to clone 'isa-l' a second time, aborting
```

```
18:11:06  stdout: 
18:11:06  stderr: Cloning into '/var/jenkins/workspace/autotest-per-patch/spdk/ocf'...
18:11:06  error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
18:11:06  fatal: expected 'acknowledgments'
18:11:06  fatal: clone of 'https://github.com/Open-CAS/ocf.git' into submodule path '/var/jenkins/workspace/autotest-per-patch/spdk/ocf' failed
18:11:06  Failed to clone 'ocf'. Retry scheduled
18:11:06  Cloning into '/var/jenkins/workspace/autotest-per-patch/spdk/ocf'...
18:11:06  error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
18:11:06  fatal: expected 'acknowledgments'
18:11:06  fatal: clone of 'https://github.com/Open-CAS/ocf.git' into submodule path '/var/jenkins/workspace/autotest-per-patch/spdk/ocf' failed
18:11:06  Failed to clone 'ocf' a second time, aborting
18:11:06
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121194.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121168.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121166.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121164.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121161.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121158.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121172.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121170.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121182.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121180.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121178.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121176.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121145.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121113.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121110.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121109.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121107.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121122.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @karlatec. log: https://ci.spdk.io/public_build/autotest-per-patch_121117.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121184.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_121106.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_121108.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121157.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121165.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121160.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121169.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121167.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121179.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121177.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_121175.html

**Comment by karlatec** [comment]
This was caused by network issue and 3 weeks have passed since then. I think we can close this one.
