### ISSUE TITLE
NVME over FC not working

### ISSUE THREAD

**Issue by madxam44** [spdk/spdk#3360]
Hello

I'm trying to get working FC NVMe and  have problem.
I'm using SPDK v23.09 with compiled drivers from https://github.com/ecdufcdrvr/bcmufctdrvr  on Debian 11 with kernel 5.10

SPDK configuration:

```
[
  {
    "nqn": "nqn.2014-08.org.nvmexpress.discovery",
    "subtype": "Discovery",
    "listen_addresses": [],
    "allow_any_host": true,
    "hosts": []
  },
  {
    "nqn": "nqn.2024-04.spdk:node1",
    "subtype": "NVMe",
    "listen_addresses": [
      {
        "transport": "FC",
        "trtype": "FC",
        "adrfam": "FC",
        "traddr": "nn-0x200000109b51adba:pn-0x100000109b51adba",
        "trsvcid": ""
      }
    ],
    "allow_any_host": true,
    "hosts": [],
    "serial_number": "SPDK00000000000003",
    "model_number": "SPDK bdev Controller",
    "max_namespaces": 32,
    "min_cntlid": 1,
    "max_cntlid": 65519,
    "namespaces": [
      {
        "nsid": 1,
        "bdev_name": "aio0",
        "name": "aio0",
        "nguid": "7BDD67FC6C10410A80D96BA16AEF414A",
        "uuid": "7bdd67fc-6c10-410a-80d9-6ba16aef414a"
      }
    ]
  }
]
```
On initiator

`nvme discover --transport=fc --traddr=nn-0x200000109b51adba:pn-0x100000109b51adba --host-traddr=nn-0x200000109b51ae13:pn-0x100000109b51ae13`

error in dmesg

`nvme_fc: nvme_fc_create_ctrl: nn-0x200000109b51adba:pn-0x100000109b51adba - nn-0x200000109b51ae13:pn-0x100000109b51ae13 combination not found`

Anyone ever get working NVME FC ?
Is there any additonal module that need to be laoded with kernel ?
Anyone can please help ?

_Originally posted by @madxam44 in https://github.com/spdk/spdk/issues/2754#issuecomment-2076824519_

**Comment by jimharris** [comment]
@anilgv1

**Comment by madxam44** [comment]
Anyone please can help ?

**Comment by anilgv1** [comment]
Please post the SPDK target console logs. Also copy the 'lspci -d 10df:' output to the bug

**Comment by madxam44** [comment]
I have compiled new drivers from https://github.com/ecdufcdrvr/bcmufctdrvr with SPDK v2405 and it's working

**Comment by jimharris** [comment]
> I have compiled new drivers from https://github.com/ecdufcdrvr/bcmufctdrvr with SPDK v24.05 and it's working

Thanks for the update. Can this issue be closed?

**Comment by TimLand** [comment]
Does it support Qlogic FC cards?

**Comment by anilgv1** [comment]
> Does it support Qlogic FC cards?

AFAIK, a few OEM's are shipping SPDK based FC-NVMe Target arrays with the Qlogic/Marvell HBAs. Please contact Marvell directly to get the LLD drivers.
