### ISSUE TITLE
[dm_mount] mkfs.ext4: Input/output error while writing out and closing file system

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3371]
00:04:38.769   16:38:45 setup.sh.devices -- common/autotest_common.sh@10 -- # set +x
00:04:38.769  ************************************
00:04:38.769  START TEST dm_mount
00:04:38.769  ************************************
00:04:38.769   16:38:45 setup.sh.devices.dm_mount -- common/autotest_common.sh@1121 -- # dm_mount
00:04:38.769   16:38:45 setup.sh.devices.dm_mount -- setup/devices.sh@144 -- # pv=nvme0n1
00:04:38.769   16:38:45 setup.sh.devices.dm_mount -- setup/devices.sh@145 -- # pv0=nvme0n1p1
00:04:38.769   16:38:45 setup.sh.devices.dm_mount -- setup/devices.sh@146 -- # pv1=nvme0n1p2
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/devices.sh@148 -- # partition_drive nvme0n1
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@39 -- # local disk=nvme0n1
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@40 -- # local part_no=2
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@41 -- # local size=1073741824
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@43 -- # local part part_start=0 part_end=0
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@44 -- # parts=()
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@44 -- # local parts
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@46 -- # (( part = 1 ))
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@46 -- # (( part <= part_no ))
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@47 -- # parts+=("${disk}p$part")
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@46 -- # (( part++ ))
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@46 -- # (( part <= part_no ))
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@47 -- # parts+=("${disk}p$part")
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@46 -- # (( part++ ))
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@46 -- # (( part <= part_no ))
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@51 -- # (( size /= 4096 ))
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@56 -- # sgdisk /dev/nvme0n1 --zap-all
00:04:38.770   16:38:45 setup.sh.devices.dm_mount -- setup/common.sh@53 -- # /home/vagrant/spdk_repo/spdk/scripts/sync_dev_uevents.sh block/partition nvme0n1p1 nvme0n1p2
00:04:39.703  Creating new GPT entries in memory.
00:04:39.703  GPT data structures destroyed! You may now partition the disk using fdisk or
00:04:39.703  other utilities.
00:04:39.703   16:38:46 setup.sh.devices.dm_mount -- setup/common.sh@57 -- # (( part = 1 ))
00:04:39.703   16:38:46 setup.sh.devices.dm_mount -- setup/common.sh@57 -- # (( part <= part_no ))
00:04:39.703   16:38:46 setup.sh.devices.dm_mount -- setup/common.sh@58 -- # (( part_start = part_start == 0 ? 2048 : part_end + 1 ))
00:04:39.703   16:38:46 setup.sh.devices.dm_mount -- setup/common.sh@59 -- # (( part_end = part_start + size - 1 ))
00:04:39.703   16:38:46 setup.sh.devices.dm_mount -- setup/common.sh@60 -- # flock /dev/nvme0n1 sgdisk /dev/nvme0n1 --new=1:2048:264191
00:04:40.637  Creating new GPT entries in memory.
00:04:40.637  The operation has completed successfully.
00:04:40.637   16:38:47 setup.sh.devices.dm_mount -- setup/common.sh@57 -- # (( part++ ))
00:04:40.637   16:38:47 setup.sh.devices.dm_mount -- setup/common.sh@57 -- # (( part <= part_no ))
00:04:40.637   16:38:47 setup.sh.devices.dm_mount -- setup/common.sh@58 -- # (( part_start = part_start == 0 ? 2048 : part_end + 1 ))
00:04:40.637   16:38:47 setup.sh.devices.dm_mount -- setup/common.sh@59 -- # (( part_end = part_start + size - 1 ))
00:04:40.637   16:38:47 setup.sh.devices.dm_mount -- setup/common.sh@60 -- # flock /dev/nvme0n1 sgdisk /dev/nvme0n1 --new=2:264192:526335
00:04:42.009  The operation has completed successfully.
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/common.sh@57 -- # (( part++ ))
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/common.sh@57 -- # (( part <= part_no ))
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/common.sh@62 -- # wait 173003
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@150 -- # dm_name=nvme_dm_test
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@151 -- # dm_mount=/home/vagrant/spdk_repo/spdk/test/setup/dm_mount
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@152 -- # dm_dummy_test_file=/home/vagrant/spdk_repo/spdk/test/setup/dm_mount/test_dm
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@155 -- # dmsetup create nvme_dm_test
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@160 -- # for t in {1..5}
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@161 -- # [[ -e /dev/mapper/nvme_dm_test ]]
00:04:42.009   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@161 -- # break
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@164 -- # [[ -e /dev/mapper/nvme_dm_test ]]
00:04:42.010    16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@165 -- # readlink -f /dev/mapper/nvme_dm_test
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@165 -- # dm=/dev/dm-0
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@166 -- # dm=dm-0
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@168 -- # [[ -e /sys/class/block/nvme0n1p1/holders/dm-0 ]]
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@169 -- # [[ -e /sys/class/block/nvme0n1p2/holders/dm-0 ]]
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/devices.sh@171 -- # mkfs /dev/mapper/nvme_dm_test /home/vagrant/spdk_repo/spdk/test/setup/dm_mount
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/common.sh@66 -- # local dev=/dev/mapper/nvme_dm_test mount=/home/vagrant/spdk_repo/spdk/test/setup/dm_mount size=
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/common.sh@68 -- # mkdir -p /home/vagrant/spdk_repo/spdk/test/setup/dm_mount
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/common.sh@70 -- # [[ -e /dev/mapper/nvme_dm_test ]]
00:04:42.010   16:38:48 setup.sh.devices.dm_mount -- setup/common.sh@71 -- # mkfs.ext4 -qF /dev/mapper/nvme_dm_test
00:07:18.507  mkfs.ext4: Input/output error while writing out and closing file system
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- setup/common.sh@71 -- # trap - ERR
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- setup/common.sh@71 -- # print_backtrace
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- common/autotest_common.sh@1151 -- # args=('/home/vagrant/spdk_repo/spdk/test/setup/dm_mount' '/dev/mapper/nvme_dm_test' 'dm_mount' 'dm_mount')
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- common/autotest_common.sh@1151 -- # local args
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- common/autotest_common.sh@1153 -- # xtrace_disable
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- common/autotest_common.sh@10 -- # set +x
00:07:18.507  ========== Backtrace start: ==========
00:07:18.507  
00:07:18.507  in /home/vagrant/spdk_repo/spdk/test/setup/common.sh:71 -> mkfs(["/dev/mapper/nvme_dm_test"],["/home/vagrant/spdk_repo/spdk/test/setup/dm_mount"])
00:07:18.507       ...
00:07:18.507     66  		local dev=$1 mount=$2 size=$3
00:07:18.507     67  	
00:07:18.507     68  		mkdir -p "$mount"
00:07:18.507     69  	
00:07:18.507     70  		[[ -e $dev ]]
00:07:18.507  => 71  		mkfs.ext4 -qF "$dev" $size
00:07:18.507     72  		mount "$dev" "$mount"
00:07:18.507     73  	}
00:07:18.507     74  	
00:07:18.507     75  	sec_size_to_bytes() {
00:07:18.507     76  		local dev=$1
00:07:18.507       ...
00:07:18.507  in /home/vagrant/spdk_repo/spdk/test/setup/devices.sh:171 -> dm_mount([])
00:07:18.507       ...
00:07:18.507     166 		dm=${dm##*/}
00:07:18.507     167 	
00:07:18.507     168 		[[ -e /sys/class/block/$pv0/holders/$dm ]]
00:07:18.507     169 		[[ -e /sys/class/block/$pv1/holders/$dm ]]
00:07:18.507     170 	
00:07:18.507  => 171 		mkfs "/dev/mapper/$dm_name" "$dm_mount"
00:07:18.507     172 	
00:07:18.507     173 		verify \
00:07:18.507     174 			"${blocks_to_pci["$pv"]}" \
00:07:18.507     175 			"$pv:$dm_name" \
00:07:18.507     176 			"$dm_mount" \
00:07:18.507       ...
00:07:18.507  in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1121 -> run_test(["dm_mount"],["dm_mount"])
00:07:18.507       ...
00:07:18.507     1116		timing_enter $test_name
00:07:18.507     1117		echo "************************************"
00:07:18.507     1118		echo "START TEST $test_name"
00:07:18.507     1119		echo "************************************"
00:07:18.507     1120		xtrace_restore
00:07:18.507     1121		time "$@"
00:07:18.507     1122		xtrace_disable
00:07:18.507     1123		echo "************************************"
00:07:18.507     1124		echo "END TEST $test_name"
00:07:18.507     1125		echo "************************************"
00:07:18.507     1126		timing_exit $test_name
00:07:18.507       ...
00:07:18.507  in /home/vagrant/spdk_repo/spdk/test/setup/devices.sh:214 -> main([])
00:07:18.507       ...
00:07:18.507     209 	((${#blocks[@]} > 0))
00:07:18.507     210 	
00:07:18.507     211 	declare -r test_disk=${blocks[0]}
00:07:18.507     212 	
00:07:18.507     213 	run_test "nvme_mount" nvme_mount
00:07:18.507  => 214 	run_test "dm_mount" dm_mount
00:07:18.507       ...
00:07:18.507  
00:07:18.507  ========== Backtrace end ==========
00:07:18.507    16:41:19 setup.sh.devices.dm_mount -- common/autotest_common.sh@1190 -- # return 0
00:07:18.507

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_122215.html

**Comment by mchomnic** [comment]
I tried two times to reproduce the issue on the same node and ref spec, but I couldn't. Closing for now.
