### ISSUE TITLE
spdk_thread_send_msg very poor performance

### ISSUE THREAD

**Issue by benqwu** [spdk/spdk#3375]
When multiple pthread call spdk_thread_send_msg, the performance is very poor. Through analysis, it was found that a msg needs to be allocated from "g_spdk_msg_mempool" for sending. However, "spdk_mempool_get" essentially retrieves an element from an MPMC queue. If the caller is preempted by the the other pthread, it will cause blocking for other pthread callers, affecting overall performance. What are some good suggestions for efficiently passing messages bidirectionally between pthreads and spdk_threads?

**Comment by jimharris** [comment]
Hi @benqwu,

You are correct, spdk_thread_send_msg was not optimized for your use case.

You can try creating SP/SC rings between your pthreads and spdk_threads. You may need more rings, but checking a ring for elements is very cheap.

**Comment by benqwu** [comment]
> Hi @benqwu,
> 
> You are correct, spdk_thread_send_msg was not optimized for your use case.
> 
> You can try creating SP/SC rings between your pthreads and spdk_threads. You may need more rings, but checking a ring for elements is very cheap.

Thank you for your advice. One way is to create a new spdk_thread and register a poller to handle the SP/SC ring. Another way is to directly register a poller on each core's original spdk_thread to handle it. What is the performance difference between these two methods?

**Comment by jimharris** [comment]
> Thank you for your advice. One way is to create a new spdk_thread and register a poller to handle the SP/SC ring. Another way is to directly register a poller on each core's original spdk_thread to handle it. What is the performance difference between these two methods?

My guess is it would be better to register a poller in the original spdk_thread instead of creating new ones. But ultimately you'll need to evaluate the two options in your unique case.
