### ISSUE TITLE
[nvme_cuse_app] test_cuse_update unit test fails

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3377]
00:14:50.446   21:21:39 nvme_cuse -- cuse/nvme_cuse.sh@17 -- # run_test nvme_cuse_app /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/cuse
00:14:50.446   21:21:39 nvme_cuse -- common/autotest_common.sh@1097 -- # '[' 2 -le 1 ']'
00:14:50.446   21:21:39 nvme_cuse -- common/autotest_common.sh@1103 -- # xtrace_disable
00:14:50.446   21:21:39 nvme_cuse -- common/autotest_common.sh@10 -- # set +x
00:14:50.446  ************************************
00:14:50.446  START TEST nvme_cuse_app
00:14:50.446  ************************************
00:14:50.446   21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1121 -- # /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/cuse
00:14:50.446  
00:14:50.446  
00:14:50.446       CUnit - A unit testing framework for C - Version 2.1-3
00:14:50.446       http://cunit.sourceforge.net/
00:14:50.446  
00:14:50.446  
00:14:50.446  Suite: nvme_cuse
00:14:50.705    Test: test_cuse_update ...FAILED
00:14:50.705      1. cuse.c:126  - wait_for_file(ns_dev, false)
00:14:50.705  
00:14:50.706  Run Summary:    Type  Total    Ran Passed Failed Inactive
00:14:50.706                suites      1      1    n/a      0        0
00:14:50.706                 tests      1      1      0      1        0
00:14:50.706               asserts    925    925    924      1      n/a
00:14:50.706  
00:14:50.706  Elapsed time =    0.018 seconds
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1121 -- # trap - ERR
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1121 -- # print_backtrace
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1151 -- # args=('/var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/cuse' 'nvme_cuse_app')
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1151 -- # local args
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1153 -- # xtrace_disable
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@10 -- # set +x
00:14:50.706  ========== Backtrace start: ==========
00:14:50.706  
00:14:50.706  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:1121 -> run_test(["nvme_cuse_app"],["/var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/cuse"])
00:14:50.706       ...
00:14:50.706     1116		timing_enter $test_name
00:14:50.706     1117		echo "************************************"
00:14:50.706     1118		echo "START TEST $test_name"
00:14:50.706     1119		echo "************************************"
00:14:50.706     1120		xtrace_restore
00:14:50.706     1121		time "$@"
00:14:50.706     1122		xtrace_disable
00:14:50.706     1123		echo "************************************"
00:14:50.706     1124		echo "END TEST $test_name"
00:14:50.706     1125		echo "************************************"
00:14:50.706     1126		timing_exit $test_name
00:14:50.706       ...
00:14:50.706  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/nvme/cuse/nvme_cuse.sh:17 -> main([])
00:14:50.706       ...
00:14:50.706     12  		echo "NVMe cuse tests only supported on Linux"
00:14:50.706     13  		exit 1
00:14:50.706     14  	fi
00:14:50.706     15  	
00:14:50.706     16  	modprobe cuse
00:14:50.706  => 17  	run_test "nvme_cuse_app" $testdir/cuse
00:14:50.706     18  	run_test "nvme_cuse_rpc" $testdir/nvme_cuse_rpc.sh
00:14:50.706     19  	run_test "nvme_cli_cuse" $testdir/spdk_nvme_cli_cuse.sh
00:14:50.706     20  	run_test "nvme_cli_plugin" $testdir/spdk_nvme_cli_plugin.sh
00:14:50.706     21  	run_test "nvme_smartctl_cuse" $testdir/spdk_smartctl_cuse.sh
00:14:50.706     22  	run_test "nvme_ns_manage_cuse" $testdir/nvme_ns_manage_cuse.sh
00:14:50.706       ...
00:14:50.706  
00:14:50.706  ========== Backtrace end ==========
00:14:50.706    21:21:39 nvme_cuse.nvme_cuse_app -- common/autotest_common.sh@1190 -- # return 0
00:14:50.706

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_122960.html

**Comment by tomzawadzki** [comment]
Just due to recency of cuse issue appearing, it might be related to recent merge of 253cca4fc3a89c38e79d2e940c5a0b7bb082afcc.
There is very little information to go off of in the build.log, so submitted https://review.spdk.io/gerrit/c/spdk/spdk/+/23174 to remedy that.

Unfortunately wasn't able to reproduce this issue on my system.

**Comment by m-spiewak** [comment]
@tomzawadzki @jimharris 
I have reproduction on my local machine. I've tried to run nvme_cuse.sh in a loop, 500 iterations first, then 800 and have no success.
Then I did the loop again but also applied a stress test to all of the 72 cores in my machine:

`stress --cpu 72 --timeout 1200`

and this time the test failed shortly after start (5th-20th iteration, varies across runs).

```************************************
START TEST nvme_cuse_app
************************************
 12:38:10 nvme_cuse_app -- common/autotest_common.sh@1121 -- # /home/mspiewak/spdk_fuzzer/test/nvme/cuse/cuse


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: nvme_cuse
  Test: test_cuse_update ...FAILED
    1. cuse.c:126  - wait_for_file(ns_dev, false)

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites      1      1    n/a      0        0
               tests      1      1      0      1        0
             asserts    925    925    924      1      n/a

Elapsed time =    0.010 seconds
  12:38:10 nvme_cuse_app -- common/autotest_common.sh@1121 -- # trap - ERR
  12:38:10 nvme_cuse_app -- common/autotest_common.sh@1121 -- # print_backtrace
  12:38:10 nvme_cuse_app -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
  12:38:10 nvme_cuse_app -- common/autotest_common.sh@1151 -- # args=('/home/mspiewak/spdk_fuzzer/test/nvme/cuse/cuse' 'nvme_cuse_app')
  12:38:10 nvme_cuse_app -- common/autotest_common.sh@1151 -- # local args
  12:38:10 nvme_cuse_app -- common/autotest_common.sh@1153 -- # xtrace_disable
  12:38:10 nvme_cuse_app -- common/autotest_common.sh@10 -- # set +x
```

**Comment by tomzawadzki** [comment]
Did you try with patch above, to pinpoint if this is failing in a specific test or different one depending on the run ?

**Comment by m-spiewak** [comment]
Every time I got test fail, this was in the place:
```
Suite: nvme_cuse
  Test: test_cuse_update ...FAILED
    1. cuse.c:126  - wait_for_file(ns_dev, false)
```
There is a loop waiting up to 1000 iterations for a file 
```
		if ((access(filename, F_OK) != -1) ^ (!exists)) {
			return true;
		}
		usleep(100);
```
And if the system is busy this is not enough - I will to sleep for longer or do more iterations and let's see what will happen.

**Comment by m-spiewak** [comment]
The issue  doesn't seem to be related to 253cca4fc3a89c38e79d2e940c5a0b7bb082afcc.
I mean it reproduces on my system even if the changes are reverted.

**Comment by m-spiewak** [comment]
With Tomek's changes (extended log messages) applied, the test fails with message:
```Suite: nvme_cuse
  Test: test_cuse_update ...[2024-05-22 12:49:32.161951] cuse.c: 133:verify_devices: *ERROR*: Found unexpected namespace device: /dev/spdk/nvme0n1
FAILED
    1. cuse.c:165  - verify_devices(&ctrlr)
```

**Comment by m-spiewak** [comment]
The root cause is wrong parameter used in the test. This code from the test_cuse_update():
```
	g_active_num_ns = 0;
	g_active_nsid_min = 1;
	nvme_cuse_update(&ctrlr);
```
causes that all 4 namespaces created in previous step are removed by cuse_nvme_ctrlr_update_namespaces() function,
but then a namespace with nsid = 1 is created. Because g_active_nsid_min is set to 1, the function spdk_nvme_ctrlr_get_first_active_ns() returns 1 so cuse_nvme_ctrlr_update_namespaces() starts this namespace.

And depending on the system load and event processing time, the wait_for_files() function sometimes hits the moment when namespace nsid=1 is removed, but not yet re-created so the namespace doesn't exist yet and tests passes, but sometimes the cuse_nvme_ctrlr_update_namespaces() already created the namespace and wait_for_files detects the file exists and tests fails.

The fix is to modify the test and set:
```
	g_active_num_ns = 0;
	g_active_nsid_min = 0; 
```

**Comment by m-spiewak** [comment]
Additionally, when a system is heavy loaded, waiting 100 ms for the file to be created/deleted in wait_for_files() function might not be enough, so I will increase this 10 times changing `i < 1000` to `i < 10000`

**Comment by jimharris** [comment]
> The root cause is wrong parameter used in the test. This code from the test_cuse_update():
> 
> ```
> 	g_active_num_ns = 0;
> 	g_active_nsid_min = 1;
> 	nvme_cuse_update(&ctrlr);
> ```
> 
> causes that all 4 namespaces created in previous step are removed by cuse_nvme_ctrlr_update_namespaces() function, but then a namespace with nsid = 1 is created. Because g_active_nsid_min is set to 1, the function spdk_nvme_ctrlr_get_first_active_ns() returns 1 so cuse_nvme_ctrlr_update_namespaces() starts this namespace.

If g_active_num_ns = 0, shouldn't that mean that no namespaces are created? Or at least that's what I think it should mean. We should not be creating a namespace 1 in that case.

It is `spdk_nvme_ctrlr_get_first_active_ns()` that is wrong here. If g_active_num_ns == 0, it needs to ignore g_active_nsid_min and just return 0 meaning there is no first_active_ns.

> 
> And depending on the system load and event processing time, the wait_for_files() function sometimes hits the moment when namespace nsid=1 is removed, but not yet re-created so the namespace doesn't exist yet and tests passes, but sometimes the cuse_nvme_ctrlr_update_namespaces() already created the namespace and wait_for_files() detects the file exists and tests fails.
> 
> The fix is to modify the test and set:
> 
> ```
> 	g_active_num_ns = 0;
> 	g_active_nsid_min = 0; 
> ```

I don't think you can just set g_active_nsid_min to 0.  See spdk_nvme_ctrlr_is_active_ns() in cuse.c:

```
 28 bool
 29 spdk_nvme_ctrlr_is_active_ns(struct spdk_nvme_ctrlr *ctrlr, uint32_t nsid)
 30 {
 31         return nsid >= g_active_nsid_min && nsid < g_active_num_ns + g_active_nsid_min;
 32 }
```

This would mean that 0 could be an active nsid, which is never valid. nsid 0 is not allowed. We can't have this function return true in that case. But I think I've already identified the alternate fix above.

This all raises a question though. This test was clearly *meaning* to validate the CUSE case when there are no active namespaces, but failed to do so. So I suspect there are some other improvements needed to this test to actually validate the correct number of files are being created. Maybe verify_devices() needs to keep a running count of the namespaces that it found active, and CU_ASSERT this against g_active_num_ns.

**Comment by m-spiewak** [comment]
I would leave the verify_devices() as is and maybe would add some tests for cases where there were namespaces, e.g. 10-19 created (nsid_min 10, num_ns 10), then nsid_min is set e.g. 14, num_ns 3, so we are 'striping' couple of namespaces from the beginning and end of the previously created range while the middle namespces are still there. Then we are creating back 10-19. That kind of tests was missing.
The namespaces are created according tho these two global variables (g_active_num_ns, g_active_nsid_min) and this is always a consecutive, is terms of numbering, set of namespaces created from a starting point (g_active_nsid_min). The verify_namespaces() in its current shape shall be able to test this, no need to implement more sophisticated tracking as we do not have 'holes' in active namespaces numbering.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @eugene-kobyak. log: https://ci.spdk.io/public_build/autotest-per-patch_124023.html
