### ISSUE TITLE
[autobuild_check_so_deps ] meson.build:4:0: ERROR: Executables created by c compiler cc are not runnable.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#3378]
00:01:32.492  INFO: autodetecting backend as ninja
00:01:32.492  INFO: calculating backend command to run: /usr/local/bin/ninja -C /var/jenkins/workspace/check-so-deps-docker-autotest/spdk/xnvme/builddir
00:01:32.492  /var/jenkins/workspace/check-so-deps-docker-autotest/spdk/xnvmebuild
00:01:50.569  The Meson build system
00:01:50.569  Version: 1.3.1
00:01:50.569  Source dir: /var/jenkins/workspace/check-so-deps-docker-autotest/spdk/dpdk
00:01:50.569  Build dir: /var/jenkins/workspace/check-so-deps-docker-autotest/spdk/dpdk/build-tmp
00:01:50.569  Build type: native build
00:01:50.569  Program cat found: YES (/usr/bin/cat)
00:01:50.569  Project name: DPDK
00:01:50.569  Project version: 23.11.0
00:01:50.569  
00:01:50.569  meson.build:4:0: ERROR: Executables created by c compiler cc are not runnable.
00:01:50.569  
00:01:50.569  A full log can be found at /var/jenkins/workspace/check-so-deps-docker-autotest/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
00:01:50.569  make[1]: *** [Makefile:221: /var/jenkins/workspace/check-so-deps-docker-autotest/spdk/dpdk/build-tmp] Error 1
00:01:50.569  make: *** [/var/jenkins/workspace/check-so-deps-docker-autotest/spdk/mk/spdk.subdirs.mk:16: dpdkbuild] Error 2
00:01:50.569    18:41:25 autobuild_check_so_deps -- make/check_so_deps.sh@382 -- # trap - ERR
00:01:50.569    18:41:25 autobuild_check_so_deps -- make/check_so_deps.sh@382 -- # print_backtrace
00:01:50.569    18:41:25 autobuild_check_so_deps -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
00:01:50.569    18:41:25 autobuild_check_so_deps -- common/autotest_common.sh@1151 -- # args=('/var/jenkins/workspace/check-so-deps-docker-autotest/spdk-abi' '-a' '/var/jenkins/workspace/check-so-deps-docker-autotest/autorun-spdk.conf' '-c')
00:01:50.569    18:41:25 autobuild_check_so_deps -- common/autotest_common.sh@1151 -- # local args
00:01:50.569    18:41:25 autobuild_check_so_deps -- common/autotest_common.sh@1153 -- # xtrace_disable
00:01:50.569    18:41:25 autobuild_check_so_deps -- common/autotest_common.sh@10 -- # set +x

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_122957.html

**Comment by mikeBashStuff** [comment]
I believe this is bound to the very patch this failure occurred at: https://review.spdk.io/gerrit/c/spdk/spdk/+/23192/1

The actual failure reported by meson is this:

```
Build started at 2024-05-16T07:35:58.807441
Main binary: /usr/bin/python3
Build Options: '-Dc_args=-Wno-stringop-overflow -fcommon -Wno-stringop-overread -Wno-array-bounds -I/spdk/intel-ipsec-mb/lib -DNO_COMPAT_IMB_API_053 -I/spdk/isa-l -I/spdk/isalbuild -fPIC -Werror ' '-Dc_link_args=-L/spdk/intel-ipsec-mb/lib -L/spdk/isa-l/.libs -lisal' -Denable_docs=false -Dtests=false -Denable_kmods=false -Dcpu_instruction_set=native -Db_sanitize=address -Denable_drivers=bus,bus/pci,bus/vdev,mempool/ring,crypto/qat,compress/qat,common/qat,common/mlx5,bus/auxiliary,crypto,crypto/aesni_mb,crypto/mlx5,crypto/ipsec_mb,compress,compress/isal,compress/mlx5 -Ddisable_libs=dispatcher,gpudev,mldev,distributor,metrics,pdump,sched,pcapng,jobstats,stack,gro,graph,member,bbdev,cfgfile,bpf,pdcp,gso,bitratestats,port,regexdev,pipeline,eventdev,latencystats,rib,fib,acl,table,ip_frag,efd,rawdev,ipsec,lpm,node -Ddisable_apps=test,test-security-perf,test-regex,test-gpudev,test-pmd,proc-info,pdump,graph,test-compress-perf,test-flow-perf,test-fib,test-dma-perf,test-pipeline,test-mldev,test-acl,test-sad,dumpcap,test-cmdline,test-crypto-perf,test-bbdev,test-eventdev -Dprefix=/spdk/dpdk/build -Dlibdir=lib -Dbuildtype=debug -Ddefault_library=shared
Python system: Linux
The Meson build system
Version: 1.3.1
Source dir: /spdk/dpdk
Build dir: /spdk/dpdk/build-tmp
Build type: native build
Program cat found: YES (/usr/bin/cat)
Running command: /usr/bin/cat /spdk/dpdk/VERSION
--- stdout ---
23.11.0

--- stderr ---


Project name: DPDK
Project version: 23.11.0
-----------
Detecting compiler via: `cc --version` -> 0
stdout:
cc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-----------
Running command: cc -E -dM -
-----
-----------
Detecting linker via: `cc -Wl,--version -L/spdk/intel-ipsec-mb/lib -L/spdk/isa-l/.libs -lisal` -> 0
stdout:
GNU ld version 2.39-16.fc38
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
-----------
stderr:
collect2 version 13.2.1 20231011 (Red Hat 13.2.1-4)
/usr/bin/ld -plugin /usr/libexec/gcc/x86_64-redhat-linux/13/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/13/lto-wrapper -plugin-opt=-fresolution=/tmp/ccgsbvbk.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 /usr/lib/gcc/x86_64-redhat-linux/13/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/13/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/13/crtbegin.o -L/spdk/intel-ipsec-mb/lib -L/spdk/isa-l/.libs -L/usr/lib/gcc/x86_64-redhat-linux/13 -L/usr/lib/gcc/x86_64-redhat-linux/13/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/13/../../.. --version -lisal -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-redhat-linux/13/crtend.o /usr/lib/gcc/x86_64-redhat-linux/13/../../../../lib64/crtn.o
-----------
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc sanitycheckc.c -o sanitycheckc.exe -Wno-stringop-overflow -fcommon -Wno-stringop-overread -Wno-array-bounds -I/spdk/intel-ipsec-mb/lib -DNO_COMPAT_IMB_API_053 -I/spdk/isa-l -I/spdk/isalbuild -fPIC -Werror -D_FILE_OFFSET_BITS=64 -L/spdk/intel-ipsec-mb/lib -L/spdk/isa-l/.libs -lisal
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command:  /spdk/dpdk/build-tmp/meson-private/sanitycheckc.exe

meson.build:4:0: ERROR: Executables created by c compiler cc are not runnable.
~
```

The `sanitycheckc.cc` is simply meant to execute plain `main()` to see if the linked binary works. Since now `isa-l` builds shared libs, the `sanitycheckc.exe` needs to know where they (i.e. `libisal.so`) are. This probably requires adjustments in `dpdkbuild/Makefile`.  The ugly, quick HACK that works.
```
diff --git a/dpdkbuild/Makefile b/dpdkbuild/Makefile
index ecb2eb829..67c3ea19a 100644
--- a/dpdkbuild/Makefile
+++ b/dpdkbuild/Makefile
@@ -104,6 +104,10 @@ DPDK_DRIVERS += compress/mlx5
 endif
 DPDK_CFLAGS += -I$(ISAL_DIR) -I$(ISAL_BUILD_DIR)
 DPDK_LDFLAGS += -L$(ISAL_DIR)/.libs -lisal
+ifeq ($(CONFIG_SHARED),y)
+       # To make sure meson's sanitycheck works
+       export LD_LIBRARY_PATH=$(ISAL_DIR)/.libs
+endif
 endif

```

**Comment by benlwalker** [comment]
This seems like a good enough solution to me. If you're building with shared libraries, it's more or less assumed they'll be installed in the search path when you run the executable. I'll update the patch.
