### ISSUE TITLE
[Bug] Build break

### ISSUE THREAD

**Issue by AkashKumarSingh11032001** [spdk/spdk#3379]
While trying to make the spdk, got this error 

![image](https://github.com/spdk/spdk/assets/55061520/3344006d-6d70-426a-b2dc-d6b4b0eb0663)

followed by the build fail

![image](https://github.com/spdk/spdk/assets/55061520/09e8ba8e-d2e6-43b7-ac92-86e3b6f87e3f)

## Steps to Reproduce

1.cd spdk
2./configure --with-fio=/home/fio--with-ocf
     “with-fio” is the directory where you clone and compile FIO
3.make

## Env.

OS: Ubuntu
SPDK: Latest cloned from Master
FIO: 3.29

**Comment by jimharris** [comment]
Hi,

Please attach full logs, not just pictures. Please also provide specifics on your Ubuntu and gcc version.

Thanks,

Jim

**Comment by mikeBashStuff** [comment]
From that snippet above, it seems like your `meson` doesn't support `compile` cmd. If that's the case, it means it's extremely old (potentially < 0.53.0) and not really supported by the `dpdkbuild` infra anymore.

**Comment by ksztyber** [comment]
[Bug scrub] There was no response, so closing the issue. @AkashKumarSingh11032001 feel free to re-open.
