### ISSUE TITLE
Our Fedora 26 SPDK CIT testbeds are suddenly failing autotest.

### ISSUE THREAD

**Issue by johnmeneghini** [spdk/spdk#338]
CITs test suddenly started failing on our internal testbeds and now 2 out of 3 of our Fedora 26 SPDK CIT testbeds are down.

See:  https://lists.01.org/pipermail/spdk/2018-June/002066.html

We use vm_setup.sh to setup our SPDK CIT testbeds. 

## Expected Behavior

 autotest.sh on the master branch continues to run on Fedora 26 CIT testbeds.

## Current Behavior

 autotest.sh unpredictably and intermittently fails on Fedora 26 CIT testbeds

## Possible Solution

When you reboot the CIT testbed make sure to run the following command prior to running CIT tests,
 
echo eth | sudo tee /sys/bus/pci/devices/0000\:81\:00.0/mlx4_port1
sudo ifup ens7
 
After doing this I see that the master branch passes cit on ssan-rx2560-01, but not on ssan-rx2560-02.

ssan-rx2560-03 was so broken we had to wipe the OS and re-install it.

## Context (Environment including OS version, SPDK version, etc.)

Master branch at: 

ssan-rx2560-01:spdk(master) > git logg -1
* 714776c0 2018-06-20  (HEAD -> master, origin/master) test/config: Call pkgdep.sh from vm_setup [ Jim Harris / seth.howell@intel.com ]

[root@ssan-rx2560-03 ~]# lsb_release -av
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 26 (Twenty Six)
Release:        26
Codename:       TwentySix
[root@ssan-rx2560-03 ~]# uname -a
Linux ssan-rx2560-03.gdl.englab.netapp.com 4.16.11-100.fc26.x86_64 #1 SMP Tue May 22 20:02:12 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ssan-rx2560-02:spdk(master) > lsb_release -av
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 26 (Twenty Six)
Release:        26
Codename:       TwentySix
ssan-rx2560-02:spdk(master) > uname -a
Linux ssan-rx2560-02.gdl.englab.netapp.com 4.15.17-200.fc26.x86_64 #1 SMP Thu Apr 12 18:28:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ssan-rx2560-01:spdk(master) > lsb_release -av
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 26 (Twenty Six)
Release:        26
Codename:       TwentySix
ssan-rx2560-01:spdk(master) > uname -a
Linux ssan-rx2560-01.gdl.englab.netapp.com 4.15.17-200.fc26.x86_64 #1 SMP Thu Apr 12 18:28:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by liang2yan** [comment]
@johnmeneghini , any update about this issue?

**Comment by wanqunintel** [comment]
@johnmeneghini is this unstable issue fixed now with latest SPDK code?

**Comment by jimharris** [comment]
Hi @johnmeneghini,

We're going to close this issue.  If you are able to reproduce with latest SPDK code, please reopen it, or file a new issue.

Thanks,

-Jim
