### ISSUE TITLE
[rpc] bdev_nvme_attach_controller inconsistent error on existing secondary trid

### ISSUE THREAD

**Issue by arsiesys** [spdk/spdk#3383]
# Sighting report

Using the rpc call bdev_nvme_attach_controller have different error if we try to re-add an existing controller versus an existing alternate/secondary controller.

```
./scripts/rpc.py bdev_nvme_attach_controller -b 42c94a7b-a658-4d84-b839-f5373368be77 -t rdma -a 192.168.1.2 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}
```
The same action on the first added controller will return:
```
./scripts/rpc.py bdev_nvme_attach_controller -b 42c94a7b-a658-4d84-b839-f5373368be77 -t rdma -a 192.168.1.1 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77
response:
{
  "code": -114,
  "message": "A controller named 42c94a7b-a658-4d84-b839-f5373368be77 already exists with the specified network path\n"
}
```

On spdk logs :
```
[2024-05-16 18:44:15.898147] bdev_nvme.c:5875:bdev_nvme_check_secondary_trid: *WARNING*: This path (traddr: 192.168.1.2 subnqn: nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77) is already registered
```

## Expected Behavior

Using the call to add an existing controller should return the same error. This is important for automation purposes.

## Steps to Reproduce
1/ NODE A => Expose a nvme lvol using two differents ip's (same or different ports)
2/ NODE B => attach the controller two times using the two different IP in failover mode, example:
```
./scripts/rpc.py bdev_nvme_attach_controller -b 42c94a7b-a658-4d84-b839-f5373368be77 -t rdma -a 192.168.1.1 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77`
./scripts/rpc.py bdev_nvme_attach_controller -b 42c94a7b-a658-4d84-b839-f5373368be77 -t rdma -a 192.168.1.2 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77
```
3/ NODE B => Try to add the secondary controller a second times:
```
./scripts/rpc.py bdev_nvme_attach_controller -b 42c94a7b-a658-4d84-b839-f5373368be77 -t rdma -a 192.168.1.2 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}
```
The same action on the first added controller will return:
```
./scripts/rpc.py bdev_nvme_attach_controller -b 42c94a7b-a658-4d84-b839-f5373368be77 -t rdma -a 192.168.1.1 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77
response:
{
  "code": -114,
  "message": "A controller named 42c94a7b-a658-4d84-b839-f5373368be77 already exists with the specified network path\n"
}
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK master 4a90644cf8823946aaa1f4850ae09a4995d187ac

**Comment by shuhei-matsumoto** [comment]
Hi @arsiesys , thank you for posting this issue. I think this is reasonable requirement. I will consider.

**Comment by shuhei-matsumoto** [comment]
Hi @arsiesys, will you check my tiny two patches? https://review.spdk.io/gerrit/c/spdk/spdk/+/23217 The second patch should fix this issue.

**Comment by tomzawadzki** [comment]
Patches addressing this issue were merged https://review.spdk.io/gerrit/c/spdk/spdk/+/23218. @arsiesys Could you confirm this resolves the issue for you ?

**Comment by arsiesys** [comment]
Hi ! Sorry for the delay and thanks for the fast patch !

I just rebased on master to get the merged patch and now the rpc call output for the secondary path changed from "Invalid parameters" to "Operation already in progress":

```
./scripts/rpc.py bdev_nvme_attach_controller -b 8b2bf74d-688d-45ec-8a9a-d2cab8493e84  -t rdma -a 192.168.1.2 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:8b2bf74d-688d-45ec-8a9a-d2cab8493e84
request:
{
  "name": "8b2bf74d-688d-45ec-8a9a-d2cab8493e84",
  "trtype": "rdma",
  "traddr": "192.168.1.2",
  "adrfam": "ipv4",
  "trsvcid": "4420",
  "subnqn": "nqn.2020-04.io.spdk.csi:uuid:8b2bf74d-688d-45ec-8a9a-d2cab8493e84",
  "multipath": "failover",
  "ctrlr_loss_timeout_sec": -1,
  "reconnect_delay_sec": 10,
  "method": "bdev_nvme_attach_controller",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -114,
  "message": "Operation already in progress"
}
```

**Comment by shuhei-matsumoto** [comment]
Hi @arsiesys 

I tried to match one case with the following case you pointed out.
Hence, I thought this satisfied your request.

Do you need not only error code (-114) but also error message string match?

```
./scripts/rpc.py bdev_nvme_attach_controller -b 42c94a7b-a658-4d84-b839-f5373368be77 -t rdma -a 192.168.1.1 -s 4420 -f ipv4 -x failover -o 10 -l -1 -n nqn.2020-04.io.spdk.csi:uuid:42c94a7b-a658-4d84-b839-f5373368be77
response:
{
  "code": -114,
  "message": "A controller named 42c94a7b-a658-4d84-b839-f5373368be77 already exists with the specified network path\n"
}
```

If you request string match, it requires large code change and I am not sure if it is possible and reasonable.

**Comment by shuhei-matsumoto** [comment]
Maybe -EALREADY is not good. -EEXIST is better? Thanks.

**Comment by shuhei-matsumoto** [comment]
Otherwise'
```
diff --git a/module/bdev/nvme/bdev_nvme_rpc.c b/module/bdev/nvme/bdev_nvme_rpc.c
index 2aba8b1d9..f3b3ea8cb 100644
--- a/module/bdev/nvme/bdev_nvme_rpc.c
+++ b/module/bdev/nvme/bdev_nvme_rpc.c
@@ -384,7 +384,13 @@ rpc_bdev_nvme_attach_controller_done(void *cb_ctx, size_t bdev_count, int rc)
        struct spdk_jsonrpc_request *request = ctx->request;

        if (rc < 0) {
-               spdk_jsonrpc_send_error_response(request, rc, spdk_strerror(-rc));
+               if (rc == -EALREADY) {
+                       spdk_jsonrpc_send_error_response_fmt(request, -EALREADY,
+                                                            "A controller named %s already exists with the specified network path\n",
+                                                            ctx->req.name);
+               } else {
+                       spdk_jsonrpc_send_error_response(request, rc, spdk_strerror(-rc));
+               }
                free_rpc_bdev_nvme_attach_controller_ctx(ctx);
                return;
        }
```
is possible. If OK, I can submit this patch, but in future other cases may use -EALREADY.

Anyway, your further clarification is very appreciated.

**Comment by arsiesys** [comment]
Hi !

Long:
I forked the existing spdk-csi here: https://github.com/spdk/spdk-csi that use the messages output.
I kept the used logic of using the message string with errorMatches with the features I implemented.. However, In this specific case, I think using the error code -114 to assume the path already exist would be satisfying as well for the automation part an  no further change is necessary (thank you!).

However, in a user point of view in the future, having a message "Operation already in progress" for an already existing path may be confusing. But it's still much better than the previous one "Invalid parameters". I let you evaluate if the changes that would be required to have the same output worth the pain or not. For my own usage, the changes you made is enough and fulfil the request !

Short: 
I am good with the current change you submitted and I will be able to adapt my code with it, thanks!

**Comment by shuhei-matsumoto** [comment]
Hi @arsiesys,

Thank you so much for your feedback. All are clear to me now.

 I want to keep the current change.
The current change was minimal and will staisfy your case by your adjustment.

We find other cases use error code string rather than generic "Invalid Request".
-EEXIST may be clearer than -EALREADY but this is just one opinion.
-EALREADY has been used for a long time.

Will you close this if you are OK? Anyone can reopen and succeed this issue if needed anytime.

Thanks again.

**Comment by shuhei-matsumoto** [comment]
But for the long term, I can submit the following change. If needed, please let us know or you can do it yourself :)

diff --git a/module/bdev/nvme/bdev_nvme_rpc.c b/module/bdev/nvme/bdev_nvme_rpc.c
index 2aba8b1d9..f3b3ea8cb 100644
--- a/module/bdev/nvme/bdev_nvme_rpc.c
+++ b/module/bdev/nvme/bdev_nvme_rpc.c
@@ -384,7 +384,13 @@ rpc_bdev_nvme_attach_controller_done(void *cb_ctx, size_t bdev_count, int rc)
        struct spdk_jsonrpc_request *request = ctx->request;
```
        if (rc < 0) {
-               spdk_jsonrpc_send_error_response(request, rc, spdk_strerror(-rc));
+               if (rc == -EALREADY) {
+                       spdk_jsonrpc_send_error_response_fmt(request, -EALREADY,
+                                                            "A controller named %s already exists with the specified network path\n",
+                                                            ctx->req.name);
+               } else {
+                       spdk_jsonrpc_send_error_response(request, rc, spdk_strerror(-rc));
+               }
                free_rpc_bdev_nvme_attach_controller_ctx(ctx);
                return;
        }
```

**Comment by arsiesys** [comment]
It's all good to me ! Thank you ! I will close the issue and adapt my code to use the error number.
