### ISSUE TITLE
scsi persist reservation allow read and write to none registrant hosts when lun has reservation of mode 8

### ISSUE THREAD

**Issue by oded-mashbach-silk** [spdk/spdk#3409]
# Sighting report
in the following scenario:
1. Target starts.
2. adding lun X to the target.
3. host 1 connects to the target - lun X is now exposed as /dev/sdd for that host.
4. host 2 connects to the target - lun X is now exposed as /dev/sdd for that host as well.
5. host 1 register a pr key for lun X:
   ?> sg_persist --out --register --param-sark=1111 /dev/sdd
6. host 1 persist reserve lun X using mode 8 (all registrant - exclusive access):
   ?> sg_persist --out --reserve --param-rk=1111 --prout-type=8 /dev/sdd
7. host 2 perform read operation:
  ?> dd if=/dev/sdd iflag=direct of=/dev/null bs=4096 count=1
   
## Expected Behavior
We shall expect IO error response.
since host 1 registered and reserved lun X using mode 8 - only hosts who register to lun x can read/write from it - since host 2 did not do that - it should get IO error.
## Current Behavior
host 2 can either read/write - with no restrictions.

host 2 should not be able to read/write until it performs registration.
## Possible Solution
i have a patch that is pending code review which [fixes this bug](https://review.spdk.io/gerrit/c/spdk/spdk/+/23615).  
## Steps to Reproduce
create an environment with 2 hosts where iscsi target is running and exposing 1 LUN.
after login run from host 1:
?> sg_persist --out --reserve --param-rk=1111 --prout-type=8 /dev/sdd
?> sg_persist --out --reserve --param-rk=1111 --prout-type=8 /dev/sdd
?> dd if=/dev/sdd iflag=direct of=/dev/null bs=4096 count=1
we should see an io error.

## Context (Environment including OS version, SPDK version, etc.)
spdk version: SPDK master branch.
OS: Rocky8

again - the [fix is here](https://review.spdk.io/gerrit/c/spdk/spdk/+/23615)

**Comment by tomzawadzki** [comment]
Thanks for the submission @oded-mashbach-silk ! Since the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/23615 is merged, can this issue be closed ?

**Comment by oded-mashbach-silk** [comment]
of course.
i closed it.
thanks
