### ISSUE TITLE
Calloc argument order error in cpuset.c

### ISSUE THREAD

**Issue by CodyChengIOL** [spdk/spdk#3410]
# Sighting report

While compiling SPDK on Fedora 40 (which ships with GCC 14.1) I ran into this error:
```
cpuset.c:12:52: error: 'calloc' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
    12 |         return (struct spdk_cpuset *)calloc(sizeof(struct spdk_cpuset), 1);
       |                                                    ^~~~~~
cpuset.c:12:52: note: earlier argument should specify number of elements, later size of each element
```

## Expected Behavior

It should compile with no error.

## Current Behavior

It fails to compile and gives the error above.

## Possible Solution

Swap the `sizeof(struct spdk_cpuset)` and the `1`.

There is another instance of this in `module/bdev/iscsi/bdev_iscsi.c` at line 807 where `sizeof(*lun)` and the `1`  can be swapped.

## Steps to Reproduce

I compiled SPDK master with DPDK main using `./configure --with-dpdk=/usr/local/ --enable-werror && make`

## Context (Environment including OS version, SPDK version, etc.)

Fedora 40 Docker container, gcc 14.1.1

**Comment by changpe1** [comment]
@CodyChengIOL good catch, could you submit a fix to SPDK, you may refer https://spdk.io/development/ for the submission.

**Comment by CodyChengIOL** [comment]
I have submitted a patch here: https://review.spdk.io/gerrit/c/spdk/spdk/+/23734.
