### ISSUE TITLE
bdev_raid_create completes before raid bdev is registered

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3413]
An RPC that creates a bdev shouldn't complete until that bdev has actually been created (i.e. spdk_bdev_register() has been called). But that isn't the case for creating bdevs with superblock (i.e. on-disk metadata) enabled.

Set of RPCs for reproduction:

```
bdev_malloc_create -b malloc0 64 512
bdev_malloc_create -b malloc1 64 512
bdev_delay_create -b malloc0 -d delay0 -r 1000000 -t 1000000 -w 1000000 -n 1000000
bdev_delay_create -b malloc1 -d delay1 -r 1000000 -t 1000000 -w 1000000 -n 1000000
bdev_raid_create -n raid1 -r 1 -b "delay0 delay1" -s
bdev_wait_for_examine
bdev_lvol_create_lvstore raid1 lvs
```

I dug into this a little bit, I clearly see that the RPC completion callback occurs before the raid bdev has been registered. So then the bdev_wait_for_examine RPC completes immediately (since there are no bdevs waiting for examination) and then the bdev_lvol_create_lvstore fails.

**Comment by apaszkie** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/24216
