### ISSUE TITLE
iscsi chap authentication for discovery phase does not work

### ISSUE THREAD

**Issue by oded-mashbach-silk** [spdk/spdk#3417]
# Sighting report

When performing the following flow:

1. Create an iscsi target using the iscsi_tgt.
2. add authentication group, tagged X and set secret for it.
3. configure chap authentication for discovery phase using the iscsi_set_discovery_auth rpc.
4. try login from initiator without CHAP authentication for discovery.

## Expected Behavior
the host should not be able to discover any targets since we expect it to get block due to authentication failure.
## Current Behavior
the host discovers the target.
## Possible Solution
the following [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/23616) is available for review to fix the issue,
## Steps to Reproduce
please follow the test i added in the patch.
## Context (Environment including OS version, SPDK version, etc.)
tested on Rocky 8.

**Comment by shuhei-matsumoto** [comment]
Hi @oded-mashbach-silk , Thank you so much for the fix and test! Will you check the format error found in https://ci.spdk.io/results/autotest-per-patch/builds/125155/archive/check-format-docker-autotest_25215/build.log and update the patch?

**Comment by tomzawadzki** [comment]
Hi @oded-mashbach-silk, I see that two patches ending with https://review.spdk.io/gerrit/c/spdk/spdk/+/23617 were merged. Thank you for the submission !

Does that fully address this GH issue ?
