### ISSUE TITLE
[raid1] recalculate data_offset when a base_bdev is added

### ISSUE THREAD

**Issue by arsiesys** [spdk/spdk#3419]
# Sighting report

Currently, once a raid1 is created, the data_offset of each base_bdev is defined once. Then, a future slot replace by a new disk will keep using the data_offset that was calculated for the previous disk used at the raid creation and not consider the better value for the new one.

## Suggested Behavior

Every time a base_bdev is added (and then, logically replace a previously existing disk), recalculate the optimal data_offset for the new disk added.

## Context
1) In a storage cluster, some spdk nodes may have different rdma transport configuration which seems to impact how the io_optimal_boundary is calculated and will, then, impact how the data_offset is calculated as well. Using a data_offset not adapted/outdated to the base_bdev may have a performance impact.
2) In a k8s CSi, we are initializing a raid1 with 3 real bdev (lvol, rdma remote) and 1 null disk. The null disk is removed right after the raid is created. This allow us to pre-provision an extra raid1 slot that will be use to migrate data, create snapshot that we split from the raid1 etc..

Thank you !

**Comment by sberbz** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/24339
