### ISSUE TITLE
Dynamic scheduler efficiency degradation

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3421]
# Sighting report

Between 24.01 and 24.05 there was a change introduced which reduces SPDK's dynamic scheduler efficiency in reducing CPU utilization while handling workloads. For a given workload there is a very noticeable difference for CPU utilization of the process using the dynamic scheduler , while the IOPS between commits remain (rather) the same.

After bisecting b238468dc3a1c7c904831a89ddd1af0b055de416 was identified as first bad commit (check last column with Target's CPU utilization, where dynamic scheduler is used):
```
Name                  iops         bw           avg_lat_us  min_lat_us  max_lat_us   target_avg_cpu_util
4k_192_randread_m_70  1733420.206  6933765.000  1107.050    149.936     47256.552    839.280
```

Using dc9bc118cc7f96b9802babaa3c9df5f78a12df89 (1 commit eariler):
```
Name                  iops         bw           avg_lat_us  min_lat_us  max_lat_us  target_avg_cpu_util
4k_192_randread_m_70  1674122.910  6696576.000  1146.338    307.226     33445.756   444.490
```

## Expected Behavior

Dynamic scheduler efficiency at the same level as in 24.01 version.

## Current Behavior

Efficiency up to almost 2 times lower (at least for the used hw configuration and workload used).

## Steps to Reproduce

Considering this was reproduced using NVMe-oF performance scripts, exact reproduction steps would be quite lengthy. Instead I am adding a high-level HW/workload configuration used for reproduction. If exact, narrowed-down steps are needed - please let me know in the comments.

Configuration is very similar as described in [SPDK TCP 24.01 Performance Report](https://ci.spdk.io/download/performance-reports/SPDK_tcp_mlx_perf_report_2401.pdf) Appendix A:
* 24 CPU SPDK TCP Target
* 10 NVMe drives in Target system
* 10 TCP NVMe-oF subsystems, each with 1 NVMe Bdev as namespace
* Subsystems listeners spread across 4 NICs
* 2 Initiator systems; each system connects to 5 remote subsystems
* fio workload run against each connected subsystem:
```
bs=4kb
qd=192
numjobs=1 (single connection)
ioengine=libaio
run_time=90
ramp_time=30
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK b238468dc3a1c7c904831a89ddd1af0b055de416

**Comment by tomzawadzki** [comment]
Seeing the commit the results you were getting now make perfect sense. This patch resulted in scheduler specific settings not applying when changing the scheduler, only if it was previously set to that scheduler:
```
tzawadzk@wisla:~/spdk$ sudo ./scripts/rpc.py framework_set_scheduler dynamic --core-limit 50
tzawadzk@wisla:~/spdk$ sudo ./scripts/rpc.py framework_get_scheduler
{
  "scheduler_name": "dynamic",
  "scheduler_period": 1000000,
  "governor_name": "dpdk_governor",
  "load_limit": 20,
  "core_limit": 80,
  "core_busy": 95
}
tzawadzk@wisla:~/spdk$ sudo ./scripts/rpc.py framework_set_scheduler dynamic --core-limit 50
tzawadzk@wisla:~/spdk$ sudo ./scripts/rpc.py framework_get_scheduler
{
  "scheduler_name": "dynamic",
  "scheduler_period": 1000000,
  "governor_name": "dpdk_governor",
  "load_limit": 20,
  "core_limit": 50,
  "core_busy": 95
}
```

This means that prior reports contain data for the default settings of core limit. The results might have been different between default and modified settings previously due to the test execution. See example above when settings were modified if dynamic scheduler was already enabled.

I've added the patch to backports for 24.01. This means that some data from prior reports might have not been accurate, depending on the execution.
I propose that for purpose of reports, we again reevaluate the core-limit (maybe the 80% is fine) and consider getting data for 24.01 with that patch included to see which data (if not all) is valid.

**Comment by tomzawadzki** [comment]
[Bug scrub] The SPDK 24.05 will now include correct description - values for scheduler options are the defaults. Meanwhile SPDK 24.01 will see an update - same data, just the comment regarding the scheduler options.

**Comment by tomzawadzki** [comment]
As mentioned above, reports will include correct description from now on. Meanwhile test for this specific functionality was added https://review.spdk.io/gerrit/c/spdk/spdk/+/23956.
