### ISSUE TITLE
NVMe-oF RDMA performance variance issue

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3422]
# Sighting report

The name of this issue is very general, but unfortunately I don't know what could be the exact issue, so...

I am working on preparing a new test setup for https://performance.spdk.io. Hardware configuration is very similar to what's described in [SPDK NVMe-oF RDMA Performance Report](https://ci.spdk.io/download/performance-reports/SPDK_rdma_mlx_perf_report_2401.pdf).

I am observing rather high IOPS results variance when running NVMe-oF RDMA tests when running a specific test configuration, which is part of checking how performance scales with addition of Initiator IO CPU cores.
* SPDK NVMe-oF RDMA Target using 6 CPU cores
* Target configured with 10 RDMA NVMe-oF subsystems, each with single namespace
* Null block devices used for nvme-of namespaces
* Target connected with initiator using 2 x Mellanox CX-6 516-CDAT NICs (single port connections, so max 200GbE throughput, about 5.4-5.5M IOPS for 4k workloads)
* NVMe-oF subsystem listeners spread between these two NICs evenly (5 for 1st, 5 for 2nd NIC)
* SPDK bdev plugin workload run on Initiator side: 4k Randwrite, initiator using 5 threads to run IO (for detailed fio config see below; I don't want to put too much into this description)
* SPDK Target uses Null Block Devices and it's core mask are on the same NUMA node as both used NICs (core 0), so there's no cross-numa configuration

### **Why specifically 6 CPU cores for SPDK Target?**
6 is more than enough to handle 200GbE (~5.5M IOPS) generated by a single initiator in this configuration.
See [RDMA test case 1 results](https://ci.spdk.io/download/performance-reports/SPDK_rdma_mlx_perf_report_2401.pdf) where with 6 cores we handle ~10M IOPS.

Now, when I run the test using described configuration in a loop I get following results
```
IOPS         BW          AVG_LAT [usec]
5369419.505, 21477759.0, 58.999
5369391.774, 21477649.0, 59.203
5369036.798, 21476229.0, 59.128
4507874.942, 18031581.0, 70.666
4959656.823, 19838710.0, 64.722
5368996.734, 21476068.0, 59.202
5369579.895, 21478401.0, 59.143
5369458.703, 21477918.0, 59.181
4570681.821, 18282809.0, 69.687
4524834.478, 18099420.0, 70.448
```

However after modifying the configuration slightly, and using more cores for SPDK Target (e.g. 8 or 10) I get stable results:
```
IOPS         BW          AVG_LAT [usec]
5368930.938, 21475806.0, 59.07
5368990.267, 21476043.0, 59.198
5369048.397, 21476276.0, 59.185
5368920.605, 21475765.0, 59.255
5368869.513, 21475558.0, 59.172
5368867.675, 21475551.0, 59.129
5369009.533, 21476120.0, 59.213
5369007.733, 21476113.0, 59.319
5369082.061, 21476410.0, 59.095
5368913.072, 21475734.0, 59.155
```

Tested with a44a9620a68f2a8c29db1b7165d67fe7c070458c on both Target and Initiator side.

Initially this looked pretty similar to https://github.com/spdk/spdk/issues/2800, but I've checked qpairs distribution between poller groups and it looks OK.

## Context (Environment including OS version, SPDK version, etc.)

SPDK a44a9620a68f2a8c29db1b7165d67fe7c070458c

Initiator side fio configuration:
```
[global]
ioengine=/tmp/spdk/build/fio/spdk_bdev
spdk_json_conf=/tmp/spdk/bdev.conf
thread=1
group_reporting=0
direct=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

norandommap=1
rw=randwrite
rwmixread=70
bs=4k
time_based=1
ramp_time=15
runtime=15
rate_iops=0
numjobs=1

[filename0]
filename=Nvme0n1
filename=Nvme1n1
iodepth=64
cpus_allowed=0
numa_mem_policy=prefer:0


[filename1]
filename=Nvme2n1
filename=Nvme3n1
iodepth=64
cpus_allowed=1
numa_mem_policy=prefer:0


[filename2]
filename=Nvme4n1
filename=Nvme5n1
iodepth=64
cpus_allowed=2
numa_mem_policy=prefer:0


[filename3]
filename=Nvme6n1
filename=Nvme7n1
iodepth=64
cpus_allowed=28
numa_mem_policy=prefer:1


[filename4]
filename=Nvme8n1
filename=Nvme9n1
iodepth=64
cpus_allowed=29
numa_mem_policy=prefer:1
```

**Comment by karlatec** [comment]
Check:
* Disable SRQ?
* Check encapsulate data is enable
* If that doesn't work - perf profile maybe

Update description with transport layer params.

**Comment by karlatec** [comment]
Updates:

## RDMA Transport parameters used in test:

```
[
  {
    "trtype": "RDMA",
    "max_queue_depth": 128,
    "max_io_qpairs_per_ctrlr": 127,
    "in_capsule_data_size": 4096,
    "max_io_size": 131072,
    "io_unit_size": 8192,
    "max_aq_depth": 128,
    "num_shared_buffers": 4096,
    "buf_cache_size": 4294967295,
    "dif_insert_or_strip": false,
    "zcopy": false,
    "max_srq_depth": 4096,
    "no_srq": false,
    "acceptor_backlog": 100,
    "no_wr_batching": false,
    "abort_timeout_sec": 1,
    "ack_timeout": 0,
    "data_wr_pool_size": 4095
  }
]
```

## Check with Random Read workload

Re run the same configuration with 4KiB Random Read QD=8/16/32 - only stable results at expected 5.4M IOPS.
@jimharris 

## Data encapsulation

Any tips on how to check if it's encapsulated? @AlekseyMarchuk 

## 2KiB Random writes

When trying to run 2KiB workload using fio bdev plugin on Initiator side I get:
```
[sys_sgci@spdk-cyp-18 spdk]$ sudo /usr/src/fio/fio nvmf_perf/4k_32_randwrite_m_70_5CPU.fio
filename0: (g=0): rw=randwrite, bs=(R) 2048B-2048B, (W) 2048B-2048B, (T) 2048B-2048B, ioengine=spdk_bdev, iodepth=64
filename1: (g=0): rw=randwrite, bs=(R) 2048B-2048B, (W) 2048B-2048B, (T) 2048B-2048B, ioengine=spdk_bdev, iodepth=64
filename2: (g=0): rw=randwrite, bs=(R) 2048B-2048B, (W) 2048B-2048B, (T) 2048B-2048B, ioengine=spdk_bdev, iodepth=64
filename3: (g=0): rw=randwrite, bs=(R) 2048B-2048B, (W) 2048B-2048B, (T) 2048B-2048B, ioengine=spdk_bdev, iodepth=64
filename4: (g=0): rw=randwrite, bs=(R) 2048B-2048B, (W) 2048B-2048B, (T) 2048B-2048B, ioengine=spdk_bdev, iodepth=64
fio-3.35
Starting 5 threads
fio: first direct IO errored. File system may not support direct IO, or iomem_align= is bad, or invalid block size. Try setting direct=0.
fio: pid=2228587, err=22/file:ioengines.c:399, func=td_io_queue, error=Invalid argument
fio: first direct IO errored. File system may not support direct IO, or iomem_align= is bad, or invalid block size. Try setting direct=0.
fio: pid=2228586, err=22/file:ioengines.c:399, func=td_io_queue, error=Invalid argument
fio: first direct IO errored. File system may not support direct IO, or iomem_align= is bad, or invalid block size. Try setting direct=0.
fio: first direct IO errored. File system may not support direct IO, or iomem_align= is bad, or invalid block size. Try setting direct=0.
fio: pid=2228589, err=22/file:ioengines.c:399, func=td_io_queue, error=Invalid argument
fio: pid=2228585, err=22/file:ioengines.c:399, func=td_io_queue, error=Invalid argument
fio: first direct IO errored. File system may not support direct IO, or iomem_align= is bad, or invalid block size. Try setting direct=0.
fio: pid=2228588, err=22/file:ioengines.c:399, func=td_io_queue, error=Invalid argument
[2024-07-12 06:46:21.920011] nvme_rdma.c: 541:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_CONNECT_ERROR (6) from CM event channel (status = -1)
[2024-07-12 06:46:21.921176] nvme_rdma.c: 541:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_CONNECT_ERROR (6) from CM event channel (status = -1)

filename0: (groupid=0, jobs=5): err=22 (file:ioengines.c:399, func=td_io_queue, error=Invalid argument): pid=2228585: Fri Jul 12 06:46:21 2024
  cpu          : usr=0.00%, sys=0.00%, ctx=0, majf=0, minf=0
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=50.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,5,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
[2024-07-12 06:46:21.922952] nvme_rdma.c: 541:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_CONNECT_ERROR (6) from CM event channel (status = -1)
[2024-07-12 06:46:21.924339] nvme_rdma.c: 541:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_CONNECT_ERROR (6) from CM event channel (status = -1)
[2024-07-12 06:46:21.928264] nvme_rdma.c: 541:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_CONNECT_ERROR (6) from CM event channel (status = -1)
[2024-07-12 06:46:21.929897] nvme_rdma.c: 541:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_CONNECT_ERROR (6) from CM event channel (status = -1)
```
(also with direct=0)
@jimharris 

## Disable SRQ

So first I've noticed that in the [test script](https://github.com/spdk/spdk/blob/master/scripts/perf/nvmf/run_nvmf.py#L1189) I am setting num_cqe=4096. No idea if this affects the configuration if `no_srq` is set to `false` (does it?), but just to make sure - I've removed this param from creating transport. Did not have an impact on the results - still flaky.

Next, I've set `no_srq` to `true`, while still keeping `num_cqe`, `max_srq_depth` at default settings. **Seems this helped - for 4KiB Random Writes, QD=8/16/32 I get stable ~5.4M IOPS results**. @AlekseyMarchuk

**Comment by AlekseyMarchuk** [comment]
Thanks @karlatec, interesting results. I'll check it next week and will share more information

**Comment by karlatec** [comment]
@AlekseyMarchuk any updates? Just checking ;)

**Comment by AlekseyMarchuk** [comment]
@karlatec sorry, busy with another activities, but this issue is next in the list. Hopefully I can start working on it next week.

**Comment by karlatec** [comment]
Sure thing, no problem. In that case - removing from closest Bug Scrub agenda :)

**Comment by AlekseyMarchuk** [comment]
Eventually, I found something related to this issue.
There was a performance issue related to the free WQE selection logic in rdma-core which lead to cache misses in HW. The [fix](https://github.com/linux-rdma/rdma-core/commit/4827e3388baf96f2bf630246567ab40467b7352c) for this issue was merged a year ago, so most probably Fedora (39?) already includes that. Without the fix, the difference between good and bad results on my setup was about 50%. With the fix the difference is about 5-10% - similar to what you posted.
The last thing that can help to reach better/stable results is setting active ib mtu to 4096. That can be done by changing the L2 MTU to a value >= 4096, e.g. `ifconfig eth0 mtu 5000`. Then check the active MTU on the corresponding IB device:
```
hca_id: mlx5_7
        transport:                      InfiniBand (0)
        fw_ver:                         32.38.3040
        node_guid:                      b83f:d203:00f9:a799
        sys_image_guid:                 b83f:d203:00f9:a798
        vendor_id:                      0x02c9
        vendor_part_id:                 41692
        hw_ver:                         0x1
        board_id:                       MT_0000000998
        phys_port_cnt:                  1
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5) <-------
                        sm_lid:                 0
                        port_lid:               0
                        port_lmc:               0x00
                        link_layer:             Ethernet
```
There is nothing we can do in SPDK to improve SRQ performance. I'll mark this issue as 3rd party.

**Comment by benlwalker** [comment]
[bug scrub]: This is a third party issue and there is nothing SPDK can directly do to address it. The best approach is to make sure we have the latest version of rdma-core with the above mentioned fix and to increase the MTU size to 4096. I am going to close this bug now.
