### ISSUE TITLE
iscsi chap mutual authentication apllies when mutual secret is set while it should apply when mutual authenticatuin is set

### ISSUE THREAD

**Issue by oded-mashbach-silk** [spdk/spdk#3424]
# Sighting report

When following this flow:
1. Create an authentication group using the rpc iscsi_create_auth_group tagged X:
> ./rpc.py iscsi_create_auth_group 1
2. Adding a secret to auth group X using iscsi_auth_group_add_secret with --msecret option:
?> ./rpc.py iscsi_auth_group_add_secret -u user1 -s 123456 -r muser1 -r 6564321 1
3. configuring the target authentication using the rpc iscsi_target_node_set_auth to use auth group X without setting mutual authentication (without sending the -m/--mutual-chap):
?> ./rpc.py iscsi_target_node_set_auth -g 1 -r [target name] 1

## Expected Behavior
since we did not send -m on the iscsi_target_node_set_auth, we expect the the target to avoid performing mutual chap.
and when initiator requests mutual chap - login should fail.

## Current Behavior
when initiator requests mutual chap - the target act on it depending on the existence of the msecret in the configured auth group, and not on the --mutual_-chap flag sent to the iscsi_target_node_set_auth.
as a result, the --mutual-chap has no real meaning, it does not affect anything. 

## Possible Solution
this [patch](https://review.spdk.io/gerrit/c/spdk/spdk/+/23617) fixed the issue.

## Steps to Reproduce
please see the test section in the patch.

tested on Rocky linux 8 on master branch.

**Comment by tomzawadzki** [comment]
Hi @oded-mashbach-silk, I see that two patches ending with https://review.spdk.io/gerrit/c/spdk/spdk/+/23617 were merged. Does that fully address this GH issue ?
