### ISSUE TITLE
MAX_CPU_CORES hard coded to 128 in lib/event/app.c

### ISSUE THREAD

**Issue by mpiszczek** [spdk/spdk#3425]
# Sighting report

We are seeing messages that the SPDK is unable to parse /proc/stat for cores above 128.  There is a define in lib/event/app.c which hard codes the number of CPU cores at 128. This causes an issue when there are more than 128 cores in the system.

`#define MAX_CPU_CORES               128`

```
2024-07-02 14:26:23.257030000 SPDK NOTICE app.c:928  Unable to parse /proc/stat [core: 189].
2024-07-02 14:26:23.257050000 SPDK NOTICE app.c:928  Unable to parse /proc/stat [core: 190].
```

## Possible Solution

The code should use SPDK_CONFIG_MAX_LCORES or increase MAX_CPU_CORES to 1024 

## Steps to Reproduce

Build the SPDK code with CONFIG_MAX_LCORES defined as 256

1.
2.
3.
4.

**Comment by jimharris** [comment]
hi @mpiszczek, can you push a patch to fix this?

**Comment by mpiszczek** [comment]
Yes I will push a patch.

**Comment by jimharris** [comment]
Thanks @mpiszczek.

Ideally it would use SPDK_CONFIG_MAX_LCORES, but it looks like by default, that is only defined, with no value. Only if user overrides it does a value go there.  That might be nice to fix up too. Then anywhere we need to do lcore processing we can always rely on that SPDK_CONFIG_MAX_LCORES

**Comment by mpiszczek** [comment]
@jimharris 
I have pushed up these patches
https://review.spdk.io/gerrit/c/spdk/spdk/+/24004
https://review.spdk.io/gerrit/c/spdk/spdk/+/24005
https://review.spdk.io/gerrit/c/spdk/spdk/+/24006
