### ISSUE TITLE
nvmf no longer ignores missing persistent reservation json file

### ISSUE THREAD

**Issue by mpiszczek** [spdk/spdk#3427]
# Sighting report

This patch was added to allow the nvmf code to ignore a missing persistent reservation file since it is not an error.
https://review.spdk.io/gerrit/c/spdk/spdk/+/21489

However, this was broken in a later patch that removed the check to ignore the missing reservation file
https://review.spdk.io/gerrit/c/spdk/spdk/+/21829/2/lib/nvmf/subsystem.c

## Expected Behavior

The nvmf code should ignore a missing reservation file

## Current Behavior

The code now fails when the persistent reservation file is missing.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mpiszczek** [comment]
I have pushed up a potential fix for review:
https://review.spdk.io/gerrit/c/spdk/spdk/+/24073

**Comment by ksztyber** [comment]
The patch has been merged.
