### ISSUE TITLE
[autobuild_check_dpdk_pci_api] fatal: not a git repository

### ISSUE THREAD

**Issue by KGoreczny** [spdk/spdk#3430]
# CI Intermittent Failure

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-per-patch_125903.html

## Execution failed at

00:02:20.734  START TEST autobuild_check_dpdk_pci_api
00:02:20.734  ************************************
00:02:20.734   15:09:42 autobuild_check_dpdk_pci_api -- common/autotest_common.sh@1123 -- # check_dpdk_pci_api
00:02:20.734   15:09:42 autobuild_check_dpdk_pci_api -- common/autobuild_common.sh@216 -- # local dpdk_dir
00:02:20.734   15:09:42 autobuild_check_dpdk_pci_api -- common/autobuild_common.sh@218 -- # [[ -n '' ]]
00:02:20.734   15:09:42 autobuild_check_dpdk_pci_api -- common/autobuild_common.sh@222 -- # /var/jenkins/workspace/build-files-docker-autotest/spdk/scripts/env_dpdk/check_dpdk_pci_api.sh check ''
00:02:20.994  Checking DPDK PCI API from 24.03.0 against 22.11 ...
00:02:20.994  fatal: not a git repository: /var/jenkins/workspace/autotest-per-patch_3/spdk/.git/modules/dpdk
00:02:20.994  
00:02:20.994  real	0m0.020s
00:02:20.994  user	0m0.011s
00:02:20.994  sys	0m0.010s
00:02:20.994   15:09:42 autobuild_check_dpdk_pci_api -- common/autotest_common.sh@1123 -- # es=128
00:02:20.994   15:09:42 autobuild_check_dpdk_pci_api -- common/autotest_common.sh@1124 -- # xtrace_disable
00:02:20.994   15:09:42 autobuild_check_dpdk_pci_api -- common/autotest_common.sh@10 -- # set +x
00:02:20.994  ************************************
00:02:20.994  END TEST autobuild_check_dpdk_pci_api
00:02:20.994  ************************************
00:02:20.994   15:09:42  -- common/autotest_common.sh@1142 -- # return 128
00:02:20.994    15:09:42  -- common/autobuild_common.sh@367 -- # trap - ERR
00:02:20.994    15:09:42  -- common/autobuild_common.sh@367 -- # print_backtrace
00:02:20.994    15:09:42  -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
00:02:20.994    15:09:42  -- common/autotest_common.sh@1155 -- # args=()
00:02:20.994    15:09:42  -- common/autotest_common.sh@1155 -- # local args
00:02:20.994    15:09:42  -- common/autotest_common.sh@1157 -- # xtrace_disable
00:02:20.994    15:09:42  -- common/autotest_common.sh@10 -- # set +x
00:02:20.994  ========== Backtrace start: ==========

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_125903.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_125907.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_125908.html

**Comment by mikeBashStuff** [comment]
This was related to a specific copy of a repo that we cache across the builds per commit (and which got corrupted due to a net issues during fetch). Since the affected series was already rebased and merged, this can be closed.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_129644.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_129664.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @slawekptak. log: https://ci.spdk.io/public_build/autotest-per-patch_129692.html
