### ISSUE TITLE
vhost install win server 2008 R2 failed

### ISSUE THREAD

**Issue by jialei-jialei** [spdk/spdk#3432]
# Sighting report
install windows server 2008 R2 on spdk vhost-blk failed

## Expected Behavior

install success

## Current Behavior

![image](https://github.com/spdk/spdk/assets/13553842/46210eed-581b-4c22-9aea-aac5ae899cbe)

## Possible Solution

iovs exceeds max，get_config can not limit max iovcnt ？or a bug？

## Steps to Reproduce

1.create malloc bdev
2.create vhost-blk ctrlr
3.start qemu and install win

## Context (Environment including OS version, SPDK version, etc.)

spdk version 21.04
qemu 6.2.0
virtio-win-0.1.240

spdk log
vhost_blk.c: 230:blk_iovs_split_queue_setup: *ERROR*: vhost.0s0: max IOVs in request reached (req_idx = 0).

**Comment by jialei-jialei** [comment]
@changpe1

**Comment by jialei-jialei** [comment]
blkcfg.seg_max does not limit the maximum value for Windows
why？

**Comment by changpe1** [comment]
> blkcfg.seg_max does not limit the maximum value for Windows why？

can you use a new version of SPDK to try again? both `blkcfg.size_max` and `blkcfg.seg_max` are already configured.

**Comment by jialei-jialei** [comment]
> > blkcfg.seg_max does not limit the maximum value for Windows why？
> 
> can you use a new version of SPDK to try again? both `blkcfg.size_max` and `blkcfg.seg_max` are already configured.

spdk-21.04  blkcfg.size_max and blkcfg.seg_max value has the same with the newest spdk version

windows max iovcnt is 515，not limited by this blkcfg value
finally， i split the iovs which execeeds max，and win install success

**Comment by jialei-jialei** [comment]
split iovs works well
