### ISSUE TITLE
Shared library (--with-shared option) build failed with single job

### ISSUE THREAD

**Issue by yin19941005** [spdk/spdk#3434]
# Sighting report

Build failed while using `--with-shared` option and single job.

Tested version: 

1. Master branch commit (9937c0160db0c834d5fa91bc55689413b256518c)
2. tag v24.05

To reproduce issue:
```
./configure --with-shared

make
```

This issue should be caused by some build dependencies errors.

## Expected Behavior

SPDK build with shared library option.

## Current Behavior

SPDK failed to build with shared option.
```
  LIB libspdk_event_vmd.a
  SO libspdk_event_vmd.so.6.0
  SYMLINK libspdk_event_vmd.so
  CC module/event/subsystems/sock/sock.o
  LIB libspdk_event_sock.a
  SO libspdk_event_sock.so.5.0
  SYMLINK libspdk_event_sock.so
  CC module/event/subsystems/bdev/bdev.o
  LIB libspdk_event_bdev.a
  SO libspdk_event_bdev.so.6.0
c++: error: /home/user/git_repo/spdk/build/lib/libspdk_event_keyring.so: No such file or directory
make[4]: *** [/home/user/git_repo/spdk/mk/spdk.lib.mk:84: /home/user/git_repo/spdk/build/lib/libspdk_event_bdev.so.6.0] Error 1
make[3]: *** [/home/user/git_repo/spdk/mk/spdk.subdirs.mk:16: bdev] Error 2
make[2]: *** [/home/user/git_repo/spdk/mk/spdk.subdirs.mk:16: subsystems] Error 2
make[1]: *** [/home/user/git_repo/spdk/mk/spdk.subdirs.mk:16: event] Error 2
make: *** [/home/user/git_repo/spdk/mk/spdk.subdirs.mk:16: module] Error 2
```

## Possible Solution

Quick workaround:
```
./configure --with-shared

make -j8
```
Build the SPDK with multiple jobs and the build is very likely to success.
I tested **-j4** and **-j8** and both works for me.

This issue should be caused by some build dependencies errors. Multiple jobs compile simultaneously bypass the issue but always failed with single job compile. The dependency or the build order should be fixed.

## Steps to Reproduce

```
./configure --with-shared

make
```

## Context (Environment including OS version, SPDK version, etc.)

Tested OS version:

- Ubuntu 22.04 LTS
- Ubuntu 20.04 LTS

Tested SPDK version: 

1. Master branch commit (9937c0160db0c834d5fa91bc55689413b256518c)
2. tag v24.05

The full build log:
[spdk_shared_error_log.txt](https://github.com/user-attachments/files/16169673/spdk_shared_error_log.txt)

**Comment by mikeBashStuff** [comment]
Looks like for the `event_bdev` the `subdirs_rule` is never called for the `module/event/subsystems/keyring`  since its `DEPDIRS` is a bit off?

```
diff --git a/module/event/subsystems/Makefile b/module/event/subsystems/Makefile
index ea9c8c611..61fbaab36 100644
--- a/module/event/subsystems/Makefile
+++ b/module/event/subsystems/Makefile
@@ -23,7 +23,7 @@ DIRS-$(CONFIG_VFIO_USER) += vfu_tgt
 # themselves. Should that tree change, these dependencies should change
 # accordingly.
 DEPDIRS-accel := iobuf
-DEPDIRS-bdev := accel vmd sock iobuf
+DEPDIRS-bdev := accel vmd sock iobuf keyring
 DEPDIRS-iscsi := scsi
 DEPDIRS-nbd := bdev
 DEPDIRS-ublk := bdev
```

**Comment by yin19941005** [comment]
Hi @mikeBashStuff,

Thank you! Indeed that's the issue and the fix worked!

The issue could be closed after the fix merged.
