### ISSUE TITLE
undefined reference to 'xxx'

### ISSUE THREAD

**Issue by leiyuehui** [spdk/spdk#3435]
I first compiled and installed spdk 24.05 and dpdk 23.11. When I built my own defined project and referenced the so file of spdk, a large number of "undefined reference to xxx" errors appeared.

![微信图片_20240711143604](https://github.com/spdk/spdk/assets/69415107/f1446519-4c2b-4021-826b-471bbe83439e)

**Comment by ksztyber** [comment]
Looks like it's missing isa-l, isa-l-crypto, and DPDK's rte_power. What's the command you're using to link your app?

**Comment by leiyuehui** [comment]
Thanks! my command is:
g++ bluestore_manager.cc -o bluestore-manage -I ././src/-I /usr/include/dpdk/ -I /usr/include/ -D  _STDC_FORMAT_MACROS -L ./out/lib/-L /usr/lib64 L /usr/lib -st/usr/local/include -d=c+11 -lstore -lspdk_env_dpdk -lcommon -lz-lpthread -ltcmalloc -lboost program options -lboost iostreams -lboost thread -lboost system -ldl -lblkid  laio -lrte_eal -lrte_ring -lrte_mempool-lrte_bus_pci -lrte_vhost -lspdk_nvme -lpmem

**Comment by leiyuehui** [comment]
g++ bluestore_manager.cc -o bluestore-manage -I ././src/-I /usr/include/dpdk/ -I /usr/include/ -D  _STDC_FORMAT_MACROS -L ./out/lib/-L /usr/lib64 L /usr/lib -st/usr/local/include -d=c+11 -lstore -lspdk_env_dpdk -lcommon -lz-lpthread -ltcmalloc -lboost program options -lboost iostreams -lboost thread -lboost system -ldl -lblkid  laio -lrte_eal -lrte_ring -lrte_mempool-lrte_bus_pci -lrte_vhost -lspdk_nvme -lpmem

**Comment by leiyuehui** [comment]
The above problem has been solved, but new problems have arisen, as shown in the figure below：
![497d6cf9bda438be469154d355d8847](https://github.com/user-attachments/assets/d4a305e9-d1cf-4a9e-821a-09388b502829)

**Comment by ksztyber** [comment]
It looks like it's missing some header defining those `rte_smp*` symbols, but I don't think it's related to SPDK in any way.

**Comment by leiyuehui** [comment]
Thanks ，
The problem has been solved, the connection dependent library is missing when compiling dynamically.
