### ISSUE TITLE
setup.sh script removes NIC device files required by DPDK application

### ISSUE THREAD

**Issue by m-kru** [spdk/spdk#3438]
# Sighting report

At least on FreeBSD, the `setup.sh` scripts removes files representing uio NIC devices in the `/dev` directory. 
Here is the content of my `loader.conf` file:

```
hw.contigmem.num_buffers=8
hw.contigmem.buffer_size=1073741824
contigmem_load="YES"

hw.nic_uio.bdfs="4:0:0,4:0:1,5:0:0,5:0:1,129:0:0,129:0:1,132:0:0,132:0:1"
nic_uio_load="YES"
``` 

Here is the diff of the `ls -al /dev` command after running `setup.sh`.

```diff
113,120c103,104
< crw-rw----   1 root operator 0x3d Jul 11 17:07 uio@pci:129:0:0
< crw-rw----   1 root operator 0x3e Jul 11 17:07 uio@pci:129:0:1
< crw-rw----   1 root operator 0x40 Jul 11 17:07 uio@pci:132:0:0
< crw-rw----   1 root operator 0x41 Jul 11 17:07 uio@pci:132:0:1
< crw-rw----   1 root operator 0x34 Jul 11 17:07 uio@pci:4:0:0
< crw-rw----   1 root operator 0x35 Jul 11 17:07 uio@pci:4:0:1
< crw-rw----   1 root operator 0x36 Jul 11 17:07 uio@pci:5:0:0
< crw-rw----   1 root operator 0x37 Jul 11 17:07 uio@pci:5:0:1
---
> crw-------   1 root wheel    0x3f Jul 12 05:02 uio@pci:130:0:0
> crw-------   1 root wheel    0x38 Jul 12 05:02 uio@pci:6:0:0
```

As can be seen, 2 files for NVMe devices in my machine are correctly added. However, 8 files representing NIC devices were incorrectly removed.

## Context (Environment including OS version, SPDK version, etc.)
FreeBSD 14.1-RELEASE
SPDK `88c9e0c47`

**Comment by jimharris** [comment]
Unfortunately this script was never designed to interoperate with NIC devices on FreeBSD.

You could try modifying `configure_freebsd_pci()` to get the current value of `kenv hw.nic_uio.bdfs' before unloading nic_uio.ko, then prepending that to the list of "SPDK" bdfs it sets before reloading it.

Reset path would take more work. You would want to restore what ever set of BDFs were there originally, which isn't easy to know. You could always try to pull it from loader.conf, but that's still just a guess.

**Comment by m-kru** [comment]
Why is the `nic_uio.ko` even reloaded in the script? Why is it required? It is a driver for NICs, it should have nothing to do with the NVMe devices.

**Comment by jimharris** [comment]
> Why is the `nic_uio.ko` even reloaded in the script? Why is it required? It is a driver for NICs, it should have nothing to do with the NVMe devices.

`nic_uio.ko` is the FreeBSD equivalent of `uio_pci_generic`. It is unfortunate that `nic` is in the name since it is needed to for any device with a userspace driver - not just network cards.

**Comment by mikeBashStuff** [comment]
I will try to tackle this and push some suggestions for review.

**Comment by mikeBashStuff** [comment]
Here's a draft: https://review.spdk.io/gerrit/c/spdk/spdk/+/24175. Somewhat tested the use-case from the description under smaller VM (with 2 devices passed to nic_uio). Default use-case should not be affected (passes under CI).

**Comment by jimharris** [comment]
> Here's a draft: https://review.spdk.io/gerrit/c/spdk/spdk/+/24175. Somewhat tested the use-case from the description under smaller VM (with 2 devices passed to nic_uio). Default use-case should not be affected (passes under CI).

Thanks @mikeBashStuff!

@m-kru, can you please test this and vote +1 on Gerrit if it works for you?

**Comment by m-kru** [comment]
I can, but I don't know when. Right now I have switched to Ubuntu. I don't know why, but DPDK and NIC initialization takes  a few seconds on FreeBSD, whereas on Ubuntu it takes less than a second. The initialization code is the same.

**Comment by jimharris** [comment]
> I can, but I don't know when. Right now I have switched to Ubuntu. I don't know why, but DPDK and NIC initialization takes a few seconds on FreeBSD, whereas on Ubuntu it takes less than a second. The initialization code is the same.

By default on Linux, hugepage memory is allocated only on demand. But FreeBSD doesn't support this, if the user doesn't specify an amount of hugepage memory to allocate, it will allocate *all* hugepage memory available on the system, up front.

When hugepages get allocated, the kernel has to zero them. This could be the slowdown. You could try specifying an amount of memory when you initialize - SPDK apps use "-s" to specify this, it gets translated to the DPDK "-m" option for the same.

The patch from @mikeBashStuff looks good to me. I am fine checking this in now, we can close this issue and if @m-kru finds any problems with it later, feel free to open this issue again or file a new one.

**Comment by m-kru** [comment]
Fine for me.
