### ISSUE TITLE
Performance Drop in blk lvol vhost tests between 24.01 and 24.05 release

### ISSUE THREAD

**Issue by jchachux** [spdk/spdk#3439]
# Sighting report

We have observed a significant performance drop in blk lvol vhost tests between the 24.01 and 24.05 releases. The highly probable cause of this performance regression is the commit [vhost-blk: enable multiple thread poll group support](https://github.com/spdk/spdk/commit/1c05f3fb0a66c37da57a87de53e6bbb551ee51f7).

Performance Metrics:         

| Name                                        | IOPS         | Bandwidth (BW) | Avg Latency (ms) | Min Latency (ms) | Max Latency (ms) | Queue Depth (QD) | CPU Cores | VMs |
|---------------------------------------------|--------------|----------------|------------------|------------------|------------------|------------------|-----------|-----|
| 24.05 - 4k_randread_128_blk_lvol_10CPU_20VM | 12,025,425.08 | 48,101,785.00  | 422.46           | 86.35            | 20,908.67        | 128              | 10        | 20  |
| Revert - 4k_randread_128_blk_lvol_10CPU_20VM | 14,827,449.27 | 59,309,881.67  | 344.49           | 99.05            | 36,221.03        | 128              | 10        | 20  |

IOPS Degradation is around 18% for this datapoint

## Expected Behavior

No performance degradation

## Current Behavior

Significant performance degradation in IOPS, Bandwith and latency

## Steps to Reproduce

Tests where run with [script ](https://github.com/spdk/spdk/blob/719d03c6adf20011bb50ac4109e0be7741c0d1c5/scripts/perf/vhost/run_vhost_test.sh#L4)
Setup configuration available in our [report](https://ci.spdk.io/download/performance-reports/SPDK_vhost_perf_report_2401.pdf)

## Context (Environment including OS version, SPDK version, etc.)

SPDK 24.05
Fedora 6.1.6-200.fc37.x86_64

**Comment by ksztyber** [comment]
[Bug scrub] The patch in question is also causing #3416. @changpe1, @Jaylyn-Ren could you take a look at these two issues? If not, the only option would be to revert the patch in question.

**Comment by karlatec** [comment]
@changpe1 @Jaylyn-Ren kind reminder - could you take a look at this issue and #3416?

**Comment by jimharris** [comment]
[Community meeting] We will revert these changes. Karol says the revert is no longer clean, so @jimharris will take a look at preparing a resolved revert and push out to CI for testing.

**Comment by jimharris** [comment]
> [Community meeting] We will revert these changes. Karol says the revert is no longer clean, so @jimharris will take a look at preparing a resolved revert and push out to CI for testing.

I was able to cleanly revert the main patch after reverting one other patch plus one line from a third patch.

https://review.spdk.io/gerrit/c/spdk/spdk/+/24534
https://review.spdk.io/gerrit/c/spdk/spdk/+/24535

**Comment by jchachux** [comment]
I conducted further tests with a @jimharris revert applied. The performance was compared against the results from the parent commit of the revert series to assess the impact of the changes introduced by the revert.

| **Test Condition**          | **IOPS**       | **Bandwidth (BW)**   | **Average Latency (ms)** | **Minimum Latency (ms)** | **Maximum Latency (ms)** |
|-----------------------------|----------------|----------------------|--------------------------|--------------------------|--------------------------|
| Parent of the Revert Series  | 14,628,260.166 | 58,513,125.333 bytes | 358.344                  | 90.841                   | 36,055.347               |
| After Applying Revert | 16,622,479.340 | 66,490,002.000 bytes | 308.076                  | 104.364                  | 27,310.279               |

Observations
IOPS Improvement: After applying the revert, there was a noticeable improvement in IOPS, which increased from 14,628,260.166 to 16,622,479.340. This represents a 13.62% increase in IOPS.

Bandwidth Increase: Corresponding to the improvement in IOPS, bandwidth also increased significantly from 58,513,125.333 bytes to 66,490,002.000 bytes.

The retesting results demonstrate that reverting the changes introduced in the "vhost-blk: enable multiple thread poll group support" commit significantly improves performance metrics

**Comment by changpe1** [comment]
@jchachux what's the configuration for each VM, e.g: number of queues and cpumasks?

In theory, the commits use more poll groups compared with the old one,  so the overhead could be more LW threads in one lcore, just wondering if the test script should update accordingly.

**Comment by Comphix** [comment]
@jchachux , as @changpe1 mentioned, could we also check the configuration of testing scripts along with the multiple threads support in vhost-blk? As from SPDK's customer side, the support of multiple threads are requested and also verified of performance gain in customer usage. Thanks.

**Comment by karlatec** [comment]
@changpe1 @Comphix by multiple queues/threads for blk do you mean guest VM blk.mq option?

**Comment by changpe1** [comment]
> @changpe1 @Comphix by multiple queues/threads for blk do you mean guest VM blk.mq option?

No, for example, if we set each VM with 4 io queues and cpumask with 0x3, then with multiple threads poll group feature enabled, we will start 2 threads and assign the 4 IO queues to 2 threads with round robin method, I think the performance drop may be related with cpumask for each controller, if number of cores of cpumask for each vhost-blk controller is greater than number of io queues, then some poll groups are wasted.

**Comment by ksztyber** [comment]
Since the offending patches were reverted, I'm going to close the issue.
