### ISSUE TITLE
If rpc  method set_bdev_qos_limit_iops timeout,affects the execution of subsequent commands

### ISSUE THREAD

**Issue by xuhuagen** [spdk/spdk#344]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Though it is a wrong way to use  rpc method 'set_bdev_qos_limit_iops' and it occured 
'Timeout while waiting for response:' ,  it should not affact the execution of subsequent rpc commands.

## Current Behavior

After the execution of  rpc command 'set_bdev_qos_limit_iops',  The subsequent rpc  commands
also oocured 'Timeout while waiting for response:'  when  executed it.
## Steps to Reproduce

1. ./spdk/app/iscsi_tgt/iscsi_tgt &
2. ./spdk/scripts/rpc.py construct_malloc_bdev 128 512
3. ./spdk/scripts/rpc.py set_bdev_qos_limit_iops Malloc0 20000
4. ./spdk/scripts/rpc.py construct_malloc_bdev 128 512

## Context (Environment including OS version, SPDK version, etc.)

OS version:  CentOS Linux release 7.5.1804 (Core)
SPDK version:  commit ID is   322e50468cb79224697b01a0e87ce9f24b012a38

**Comment by dverkamp-intel** [comment]
The RPC usage looks fine to me; this is definitely a bug in the QoS RPC implementation.

It looks like the problem occurs when there are no I/O channels, so _spdk_bdev_enable_qos_done() is called synchronously within the context of the spdk_for_each_channel() call in spdk_bdev_set_qos_limit_iops(); this happens while we are still holding the bdev mutex, so the pthread_mutex_lock() call in _spdk_bdev_disable_qos_msg_done() deadlocks.

**Comment by dverkamp-intel** [comment]
Please try with https://review.gerrithub.io/#/c/spdk/spdk/+/417068 - this appears to fix the issue for me.

**Comment by xuhuagen** [comment]
Yes,I patched https://review.gerrithub.io/#/c/spdk/spdk/+/417068 for this issue and it worked.

**Comment by wanqunintel** [comment]
@xuhuagen will you close if no issue

**Comment by xuhuagen** [comment]
@wanqunintel  I will close this issue when  https://review.gerrithub.io/#/c/spdk/spdk/+/417068 merge.

**Comment by xuhuagen** [comment]
Pacth https://review.gerrithub.io/#/c/spdk/spdk/+/417068  can resolve it,so close this issue.
