### ISSUE TITLE
spdk_nvme_identify: Failed to read the CSTS register

### ISSUE THREAD

**Issue by glimchb** [spdk/spdk#3445]
SPDK version https://github.com/spdk/spdk/tree/v24.05.x

- Linux kernel nvme cli `nvme discover` works
- SPDK nvme discover `spdk_nvme_identify` fails with error below

```
nvme_ctrlr.c:3727:nvme_ctrlr_process_init_enable_wait_for_ready_1: *ERROR*: [nqn.2014-08.org.nvmexpress.discovery] Failed to read the CSTS register
```

Slack link https://spdk-team.slack.com/archives/CJE4C98G1/p1718803233408189

```
spdk_nvme_identify -r 'traddr:127.0.0.1 trtype:TCP adrfam:IPv4 trsvcid:7777 hostnqn:nqn.2014-08.org.nvmexpress:uuid:feb98abe-d51f-40c8-b348-2753f3571d3c'
```

reproduces same error above.

From debugging session and tcpdump recordings, 
found this code https://github.com/spdk/spdk/blob/v24.05.x/lib/nvme/nvme_ctrlr.c#L1271-L1306

```
After analyzing both TCP dumps (linux and SPDK) PowerFlex team found the difference in `Command Set` field of `Enable Controller` command.

PowerFlex team says:

- Linux sends value 0 (NVM Command Set) which is default
- and SPDK is sending value 111b (Admin Command Set only).

PowerFlex  accepts only values 0 (NVM Command Set) and 110b (All Supported Command Set). 
All other values are rejected with CSTS.CFS bit set to 1 (fatal)
```

I was looking at the code why SPDK send `111b` value https://github.com/spdk/spdk/blob/v24.05.x/lib/nvme/nvme_ctrlr.c#L1271-L1306

And looks like the value is picked according to `cap.bits.css`

After we do a quick and dirty check https://github.com/spdk/spdk/blob/0e983c5649ae335f96c81d5f4956e4b57641c482/lib/nvme/nvme_ctrlr.c#L1369
```diff
-	cc.bits.css = ctrlr->opts.command_set;
+	cc.bits.css = SPDK_NVME_CC_CSS_NVM;
```
Discovery started to work again (tested with `spdk_nvme_identify`)

So the problem appears to be how PowerFlex reports capabilities

```
Spec states that for Discovery Controller, Controller Capability property CSS field should be set to 1 (3.1.3.1 Offset 0h: CAP – Controller Capabilities, from NVM Express® Base Specification, revision 2.0b)

So cap.bits.css will be set to 1 by PowerFlex

For IO controller cap.bits.css is zero and SPDK_NVME_CAP_CSS_NVM is used, line 1341 of mentioned nvme_ctrl.c file of SPDK
```

in the TCPDUMP we checked
```
Indeed, I see in the analyzer of spdk dump the value of Command Set Supported is 0x80, with 7-th bit is set
```

According to @jimharris 
```
looks like kernel always treats cap values as NVM unless it is 0x40 (CSI/IOCS)
which explains why kernel works, it sees 0x80 and just sets CSS to NVM

seems like we could still quirk this, print an error message but just treat 0x80 as NVM
```
see https://github.com/spdk/spdk/blob/v24.05.x/lib/nvme/nvme_quirks.c

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/24222

**Comment by ksztyber** [comment]
The patch has been merged, closing the issue.
