### ISSUE TITLE
lvolstore/lvol: fs mount error after re-creating lvolstore/lvol with existing on-disk data

### ISSUE THREAD

**Issue by schmidt-scaled** [spdk/spdk#3447]
## Expected Behavior

When re-creating lvolstore and lvol based on existing data, the ext3 fs  previously used to format the lvol is correctly recognized on the nbd disk and can be mounted and accessed.

## Current Behavior

Upon attempting to mount the filesystem post-restoration, we received the following error:
`mount /dev/nbd1p1 /mnt/y1/`
`mount: /mnt/y1: wrong fs type, bad option, bad superblock on /dev/nbd1p1, missing codepage or helper program, or other error.`
This issue does not occur when the `thin_provision` flag is disabled, which suggests the problem is specific to thin provisioning.

## Possible Solution

not yet

## Steps to Reproduce

Attach NVMe controller: `./rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:00:1f.0`
o   Create lvol store: `./rpc.py bdev_lvol_create_lvstore Nvme0n1 lvs_bdev --cluster_sz=2097152 --clear_method=none`
o   Create thin-provisioned lvol: `./rpc.py bdev_lvol_create lvs_bdev 20000 --uuid=9c6b3c50-b540-455b-b1c0-6ec063ebf2f0 --thin_provision --clear-method=none`
o   Start NBD device: `./rpc.py nbd_start_disk 581e65b4-caba-4197-8e2f-05ef6fd32533 /dev/nbd1`
o   Partition and format: `echo 'start=256' | sfdisk /dev/nbd1 followed by mkfs.ext3 /dev/nbd1p1`
o   Mount, write data, and unmount: `mount /dev/nbd1p1 /mnt/y1/, dd if=/dev/zero of=/mnt/y1/test1.txt bs=1M count=20, umount /mnt/y1/`
o   Stop NBD device and clean up: .`/rpc.py nbd_stop_disk /dev/nbd1, ./rpc.py bdev_lvol_delete_lvstore --lvs-name lvs_bdev , ./rpc.py bdev_nvme_detach_controller Nvme0`
2.     Restoration Test:
o   Reattach and recreate storage environment using the same commands as above.
o   Restart NBD device:` ./rpc.py nbd_start_disk 'uuid' /dev/nbd1`

## Context (Environment including OS version, SPDK version, etc.)

v24.9
Rocky 9, RHEL 9, Ubuntu 22

**Comment by ksztyber** [comment]
[Bug scrub] @schmidt-scaled could you please explain the exact commands that encompass the

>  o Reattach and recreate storage environment using the same commands as above.

part?

**Comment by mmkayPL** [comment]
Note that if you're deleting the lvstore, then you're removing the lvstore metadata, effectively wiping out the data you wrote to it. So if you're using the exact same steps in the 'restoration test' phase, then you're basically creating a fresh clean block device.

**Comment by jimharris** [comment]
> Note that if you're deleting the lvstore, then you're removing the lvstore metadata, effectively wiping out the data you wrote to it. So if you're using the exact same steps in the 'restoration test' phase, then you're basically creating a fresh clean block device.

I agree with @mmkayPL. I'm closing this issue.
