### ISSUE TITLE
*ERROR*: NVMe trtype 256 (PCIE) not available

### ISSUE THREAD

**Issue by m-kru** [spdk/spdk#3450]
I had a working program with SPDK only and static linking. I have added DPDK and replaced static linking with dynamic.  Instead of  `spdk_env_init` with the default value of  `spdk_env_opts`, I call `spdk_env_dpdk_post_init(false)`. The rest of the SPDK initialization code stays as it was. However, I am no longer able to probe NVMe devices. I get the following error:

```
[2024-07-22 08:24:59.792777] nvme.c: 821:nvme_probe_internal: *ERROR*: NVMe trtype 256 (PCIE) not available
[2024-07-22 08:24:59.792821] nvme.c: 913:spdk_nvme_probe: *ERROR*: Create probe context failed
```

I also had to adjusted Makefile for dynamic linking and it now looks as follows:

```make
PRJ_NAME ?= 10G

default: build

CC = cc

INC_DIRS = $(SRC_DIR) \
	/home/mkru/workspace/spdk/build/include/ \
	/home/mkru/workspace/spdk/dpdk/build/include/
_INC_FLAGS = $(addprefix -I,$(INC_DIRS))

CFLAGS = $(_INC_FLAGS) -DLOG_COLOR -mssse3

PKG_CONFIG_PATH = /home/mkru/workspace/spdk/build/lib/pkgconfig
SPDK_DPDK_LIB := $(shell PKG_CONFIG_PATH="$(PKG_CONFIG_PATH)" pkg-config --libs spdk_nvme spdk_env_dpdk)
SYS_LIB := $(shell PKG_CONFIG_PATH="$(PKG_CONFIG_PATH)" pkg-config --libs --static spdk_syslibs)

LDFLAGS = -pthread -Wl,--no-as-needed $(SPDK_DPDK_LIB) -lrte_ethdev -lrte_timer -lssl -lcrypto -luuid -Wl,--as-needed


BUILD_DIR ?= build

SRC_DIR ?= src
SRC_DIRS = $(SRC_DIR) \
	src/args
_SRCS = $(foreach dir, $(SRC_DIRS), $(wildcard $(dir)/*.c))

BIN_DIR ?= $(BUILD_DIR)/bin
OBJ_DIR ?= $(BUILD_DIR)/obj
OBJ_DIRS = $(subst $(SRC_DIR),$(OBJ_DIR),$(SRC_DIRS))
OBJS = $(subst $(SRC_DIR),$(OBJ_DIR),$(subst .c,.o,$(_SRCS)))

# Build targets
all: tidy build

build: $(BIN_DIR)/$(PRJ_NAME)

debug: CFLAGS += -g -O0 -D DEBUG
debug: $(BIN_DIR)/$(PRJ_NAME)

$(BIN_DIR)/$(PRJ_NAME): $(OBJS) | .bin-dir
	$(CC) -o $@ $^ $(LDFLAGS)

$(OBJ_DIR)%.o: $(SRC_DIR)%.c | .obj-dirs
	$(CC) -c -Wall $< $(CFLAGS) -o $@

.bin-dir:
	@mkdir -p $(BIN_DIR)

.obj-dirs:
	@mkdir -p $(OBJ_DIRS)

```

I saw similar issue https://github.com/spdk/spdk/issues/1794. However, it was related with static linking.

**Comment by jimharris** [comment]
I would recommend narrowing this down to either the dpdk_post_init() changes or the dynamic library changes. You may also want to try using a debugger to track if/when spdk_nvme_transport_register() is getting called for the PCIe transport, both before and after your changes. This really appears to be more of an issue with your build setup, rather than your DPDK changes.

**Comment by m-kru** [comment]
`spdk_nvme_transport_register` is actually never called in the second case.

**Comment by jimharris** [comment]
> `spdk_nvme_transport_register` is actually never called in the second case. `spdk_env_dpdk_external_init()` correctly detects external DPDK initialization.

OK, you'll need to debug your link line then. The constructor functions that register the transports aren't getting linked. I don't see anything wrong with your Makefile, but this is clearly the problem. Can you paste the exact command line generated for the link phase? And can you confirm that you are using stock SPDK shared library build with no extra build modifications?

**Comment by m-kru** [comment]
I use SPDK commit 719d03c6adf20011bb50ac4109e0be7741c0d1c5. The only change I made before the built is related with the DPDK:
```diff
diff --git a/dpdkbuild/Makefile b/dpdkbuild/Makefile
index ecb2eb829..d51b84c0f 100644
--- a/dpdkbuild/Makefile
+++ b/dpdkbuild/Makefile
@@ -56,7 +56,7 @@ DPDK_LDFLAGS += -fprofile-dir=$(CONFIG_PGO_DIR)
 endif

 # the drivers we use
-DPDK_DRIVERS = bus bus/pci bus/vdev mempool/ring
+DPDK_DRIVERS = bus bus/pci bus/vdev mempool/ring net/ixgbe

 # Core DPDK libs
 DPDK_LIBS = eal ring mempool pci
```

Build commands:
```
gcc -c -Wall src/args.c -Isrc -I/home/mkru/workspace/spdk/build/include/ -I/home/mkru/workspace/spdk/dpdk/build/include/ -DLOG_COLOR -mssse3 -o build/obj/args.o
gcc -c -Wall src/main.c -Isrc -I/home/mkru/workspace/spdk/build/include/ -I/home/mkru/workspace/spdk/dpdk/build/include/ -DLOG_COLOR -mssse3 -o build/obj/main.o
gcc -c -Wall src/pkt.c -Isrc -I/home/mkru/workspace/spdk/build/include/ -I/home/mkru/workspace/spdk/dpdk/build/include/ -DLOG_COLOR -mssse3 -o build/obj/pkt.o
gcc -o build/bin/10G build/obj/args.o build/obj/main.o build/obj/pkt.o -pthread -Wl,--no-as-needed -L/home/mkru/workspace/spdk/build/lib -lspdk_nvme -lspdk_keyring -lspdk_sock -lspdk_sock_posix -lspdk_thread -lspdk_trace -lspdk_rpc -lspdk_jsonrpc -lspdk_json -lspdk_dma -lspdk_env_dpdk -lspdk_util -lspdk_log -L/home/mkru/workspace/spdk/dpdk/build/lib -lrte_eal -lrte_mempool -lrte_ring -lrte_mbuf -lrte_bus_pci -lrte_pci -lrte_mempool_ring -lrte_telemetry -lrte_kvargs -lrte_rcu -lrte_power -lrte_ethdev -lrte_vhost -lrte_net -lrte_dmadev -lrte_cryptodev -lrte_hash -lrte_log  -lrte_ethdev -lrte_timer -lssl -lcrypto -luuid -Wl,--as-needed
/usr/bin/ld: warning: librte_meter.so.24, needed by /home/mkru/workspace/spdk/dpdk/build/lib/librte_power.so, not found (try using -rpath or -rpath-link)
```

Before running I also export the loader path.
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/mkru/workspace/spdk/dpdk/build/lib/
```

**Comment by jimharris** [comment]
Not sure how to proceed from here. Do the in-tree applications (i.e. spdk_nvme_perf) work or do you get the same error?

**Comment by m-kru** [comment]
It looks like the `spdk_nvme_perf` app works correctly.

**Comment by m-kru** [comment]
@jimharris any idea what else I can try?

**Comment by jimharris** [comment]
> @jimharris any idea what else I can try?

Looks like you are using `--no-as-needed` wrappers with a static library build. You need to use `--whole-archive` instead. See http://spdk.io/doc/pkgconfig.html.

**Comment by m-kru** [comment]
@jimharris I use dynamic library linking, and the page suggests I should use  `--no-as-needed` in this case.

**Comment by jimharris** [comment]
Hi @m-kru,

You could try looking at the test/external_code directory, its purpose is to test linking external code against SPDK libraries, similar to your use case.

It's not clear from what you've shared so far why the constructor functions are not getting linked in and/or executed. This is definitely the problem.

Unfortunately I don't have time right now to help debug this in any more detail.

-Jim

**Comment by m-kru** [comment]
I have a suspicion what causes this whole linking mess. When you build DPDK by using SPDK build scripts, pkg-config files for DPDK libs are not generated. You end up using both pkg-config and explicitly adding `-llib_name` arguments for the linking phase. You end up specifying SPDK libs dependencies using pkg-config. You also specify basic DPDK dependency using  pkg-config and  `spdk_env_dpdk` lib name. However, any other DPDK dependency must by added manually by explicitly providing the `-l` arguments. For example, to make my application discover Intel NICs I had to add
`-lrte_net_ixgbe` and `-lrte_security` to the linking stage.
