### ISSUE TITLE
[nvme_doorbell_aers] doorbell_aers app gets stuck, leading to a job timeout

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3455]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-spdk-master-vs-dpdk-main/builds/3691/archive/nvme-cmb-pmr-vg-autotest_85186/build.log

This seems to be exclusive to vs-dpdk-main jobs (potentially caused by some recent changes on the DPDK end?)
Point of failure:
```
00:08:52.016  START TEST nvme_doorbell_aers
00:08:52.016  ************************************
00:08:52.016   06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1123 -- # nvme_doorbell_aers
00:08:52.016   06:54:29 nvme.nvme_doorbell_aers -- nvme/nvme.sh@70 -- # bdfs=()
00:08:52.016   06:54:29 nvme.nvme_doorbell_aers -- nvme/nvme.sh@70 -- # local bdfs bdf
00:08:52.016   06:54:29 nvme.nvme_doorbell_aers -- nvme/nvme.sh@71 -- # bdfs=($(get_nvme_bdfs))
00:08:52.016    06:54:29 nvme.nvme_doorbell_aers -- nvme/nvme.sh@71 -- # get_nvme_bdfs
00:08:52.016    06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1511 -- # bdfs=()
00:08:52.016    06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1511 -- # local bdfs
00:08:52.016    06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1512 -- # bdfs=($("$rootdir/scripts/gen_nvme.sh" | jq -r '.config[].params.traddr'))
00:08:52.016     06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1512 -- # /home/vagrant/spdk_repo/spdk/scripts/gen_nvme.sh
00:08:52.016     06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1512 -- # jq -r '.config[].params.traddr'
00:08:52.016    06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1513 -- # (( 2 == 0 ))
00:08:52.016    06:54:29 nvme.nvme_doorbell_aers -- common/autotest_common.sh@1517 -- # printf '%s\n' 0000:00:10.0 0000:00:11.0
00:08:52.016   06:54:29 nvme.nvme_doorbell_aers -- nvme/nvme.sh@72 -- # for bdf in "${bdfs[@]}"
00:08:52.016   06:54:29 nvme.nvme_doorbell_aers -- nvme/nvme.sh@73 -- # timeout --preserve-status 10 /home/vagrant/spdk_repo/spdk/test/nvme/doorbell_aers/doorbell_aers -r 'trtype:PCIe traddr:0000:00:10.0'
00:08:52.273  [2024-07-24 06:54:30.144579] nvme_pcie_common.c: 294:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 77687) is not found. Dropping the request.
00:09:02.305  Executing: test_write_invalid_db
00:09:02.305  Waiting for AER completion...
00:09:02.305  Failure: test_write_invalid_db
00:09:02.305  
00:09:02.305  Executing: test_invalid_db_write_overflow_sq
00:09:02.305  Waiting for AER completion...
00:09:02.305  Failure: test_invalid_db_write_overflow_sq
00:09:02.305  
00:09:02.305  Executing: test_invalid_db_write_overflow_cq
00:09:02.305  Waiting for AER completion...
00:09:02.305  Failure: test_invalid_db_write_overflow_cq
00:09:02.305  
00:09:02.305   06:54:39 nvme.nvme_doorbell_aers -- nvme/nvme.sh@72 -- # for bdf in "${bdfs[@]}"
00:09:02.305   06:54:39 nvme.nvme_doorbell_aers -- nvme/nvme.sh@73 -- # timeout --preserve-status 10 /home/vagrant/spdk_repo/spdk/test/nvme/doorbell_aers/doorbell_aers -r 'trtype:PCIe traddr:0000:00:11.0'
01:32:10.847  Cancelling nested steps due to timeout
01:32:10.850  Sending interrupt signal to process
01:32:12.209  script returned exit code 255
```

Note that the `timeout` is hanging too since `--kill-after` is not specified and the `doorbell_aers`'s process it handles is not responding to SIGTERM.

**Comment by mikeBashStuff** [comment]
Ok, after some lengthy bisecting, I think I narrowed it down to the following change on the DPDK's end (happened between 24.07's rc2-rc3):

https://github.com/dpdk/dpdk/commit/847d78fb9530fff401bf167298aad22766a1f04a

All the current failures happen in `uio` context under our VMs so it seems to be a good match. Reverting this change also gets rid off the issue in the affected tests: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_3742.html tested with https://review.spdk.io/gerrit/c/spdk/spdk/+/24482. 

@ksztyber Would you kindly take a look and see if these findings make sense to you? Not really sure what would be the right way to actually fix this on spdk and/or dpdk side.

**Comment by ksztyber** [comment]
I don't fully understand why that patch would cause hangs in our tests, but it touches multiprocess and uio, so it does make sense that it could affect our nvme tests (which are run from a secondary process) with uio. I'll be on vacation next week, but I can take a closer look once I get back. In the meantime, we could apply that revert to make the vs-dpdk-main jobs green.

**Comment by ksztyber** [comment]
I think I've figured out what's happening here. The stub process hangs when trying to re-create the nvme-cuse IO queue, because the controller goes into the fatal state (csts.cfs). The problem is that after https://github.com/DPDK/dpdk/commit/847d78fb9530fff401bf167298aad22766a1f04a dpdk opens the `/dev/uioX` file in the secondary process and the `uio_pci_generic` driver clears the PCI bus master enable bit when that file is closed. So, when the secondary process terminates and the file is closed, the bus master enable is cleared. Then the primary process tries to create IO CQ, qemu gets an error when trying to fetch that command and goes into fatal state.

The only way to solve this that I can see (besides maybe trying to send the fd from the primary socket via `SCM_RIGHTS`) is not to open the uio device file in the secondary process. But I think it should be acceptable, because https://github.com/DPDK/dpdk/commit/847d78fb9530fff401bf167298aad22766a1f04a only mentioned that it needs the fd for the config space.

**Comment by ksztyber** [comment]
Patch with a fix: https://review.spdk.io/gerrit/c/spdk/dpdk/+/24686

**Comment by mikeBashStuff** [comment]
> Patch with a fix: https://review.spdk.io/gerrit/c/spdk/dpdk/+/24686

Slurped it into https://review.spdk.io/gerrit/c/spdk/spdk/+/24720 - verified under vs-dpdk-main, all green.
