### ISSUE TITLE
[nvme_startup] startup gets stuck, leading to a job timeout

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3457]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-spdk-master-vs-dpdk-main/builds/3691/archive/ubuntu22-vg-autotest_43554/build.log

Point of failure:
```
00:42:33.397  START TEST nvme_startup
00:42:33.397  ************************************
00:42:33.397   07:28:11 nvme.nvme_startup -- common/autotest_common.sh@1123 -- # /home/vagrant/spdk_repo/spdk/test/nvme/startup/startup -t 1000000
01:31:27.072  Cancelling nested steps due to timeout
01:31:27.075  Sending interrupt signal to process
```

Related to #3455. Note that this test seems to fail only under `ubuntu{22,24}-vg` jobs while the `nvme_doorbell_aers` test is actually passing. Odd.

**Comment by ksztyber** [comment]
[Bug scrub] Only happens on vs-dpdk-main jobs. @mikeBashStuff will try to bisect and find the faulty dpdk commit.
