### ISSUE TITLE
Not able to discover the subsystems over the network

### ISSUE THREAD

**Issue by HaruChebrolu** [spdk/spdk#3458]
# CI Intermittent Failure

Lets say,  we have 4 subsystems and allow host access to only one of the subsystems, then if we run  `nvme discover` command from client using the allowed hostIP and subsystem results to an error `failed to get discovery log: Interrupted system call` although the `nvme connect` is working
However, when we allow the host access to all 4 subsystems, then the  nvme discover command from client works as expected.

Please let me know if I need to provide anything else.

**Comment by jimharris** [comment]
Hi @HaruChebrolu,

Thanks for the report. Could you provide a more detailed set of reproduction steps?

-Jim

**Comment by jimharris** [comment]
@HaruChebrolu, I'm closing this issue. Please reopen if you are able to provide a detailed set of reproduction steps.
