### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3465]
00:00:07.526  [Pipeline] setCustomBuildProperty
00:00:07.541  [Pipeline] sh
00:00:07.826  + sudo git config --global --replace-all safe.directory '*'
00:00:07.929  [Pipeline] httpRequest
00:00:07.958  [Pipeline] echo
00:00:07.959  Sorcerer 10.211.164.101 is alive
00:00:07.966  [Pipeline] httpRequest
00:00:07.970  HttpMethod: GET
00:00:07.971  URL: http://10.211.164.101/packages/jbp_514d1c5866dfc18deb80718dba8fefadd74c06ef.tar.gz
00:00:07.972  Sending request to url: http://10.211.164.101/packages/jbp_514d1c5866dfc18deb80718dba8fefadd74c06ef.tar.gz
00:00:07.991  Response Code: HTTP/1.1 200 OK
00:00:07.991  Success: Status code 200 is in the accepted range: 200,404
00:00:07.992  Saving response body to /var/jenkins/workspace/nvmf-phy-autotest/jbp_514d1c5866dfc18deb80718dba8fefadd74c06ef.tar.gz
00:00:11.501  [Pipeline] sh
00:00:11.783  + tar --no-same-owner -xf jbp_514d1c5866dfc18deb80718dba8fefadd74c06ef.tar.gz
00:00:11.799  [Pipeline] httpRequest
00:00:11.833  [Pipeline] echo
00:00:11.835  Sorcerer 10.211.164.101 is alive
00:00:11.843  [Pipeline] httpRequest
00:00:11.847  HttpMethod: GET
00:00:11.848  URL: http://10.211.164.101/packages/spdk_bf35da7a614fc53735e8bacb2e7aae4f5ab684fe.tar.gz
00:00:11.849  Sending request to url: http://10.211.164.101/packages/spdk_bf35da7a614fc53735e8bacb2e7aae4f5ab684fe.tar.gz
00:00:11.856  Response Code: HTTP/1.1 200 OK
00:00:11.857  Success: Status code 200 is in the accepted range: 200,404
00:00:11.857  Saving response body to /var/jenkins/workspace/nvmf-phy-autotest/spdk_bf35da7a614fc53735e8bacb2e7aae4f5ab684fe.tar.gz
00:01:29.154  [Pipeline] }
00:01:29.173  [Pipeline] // stage
00:01:29.181  [Pipeline] }
00:01:29.202  [Pipeline] // wrap
00:01:29.210  [Pipeline] }
00:01:29.216  java.net.SocketTimeoutException: Read timed out
00:01:29.216  	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
00:01:29.216  	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
00:01:29.216  	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
00:01:29.216  	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
00:01:29.216  	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
00:01:29.216  	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
00:01:29.216  	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
00:01:29.216  	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
00:01:29.216  	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
00:01:29.216  	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
00:01:29.216  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1483)
00:01:29.216  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1107)
00:01:29.216  	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1456)
00:01:29.216  	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1085)
00:01:29.216  	at jenkins.plugins.http_request.HttpRequestExecution.processResponse(HttpRequestExecution.java:502)
00:01:29.216  	at jenkins.plugins.http_request.HttpRequestExecution.authAndRequest(HttpRequestExecution.java:376)
00:01:29.216  	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:284)
00:01:29.216  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to WFP43
00:01:29.216  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)
00:01:29.216  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
00:01:29.216  		at hudson.remoting.Channel.call(Channel.java:1003)
00:01:29.216  		at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:404)
00:01:29.216  		at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:383)
00:01:29.216  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
00:01:29.216  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
00:01:29.216  		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
00:01:29.216  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
00:01:29.216  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
00:01:29.216  		at java.base/java.lang.Thread.run(Unknown Source)
00:01:29.216  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 914f2790-acf5-4ed2-98c7-cbd2a236104c
00:01:29.216  Caused: java.lang.IllegalStateException
00:01:29.216  	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:287)
00:01:29.216  	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:80)
00:01:29.216  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
00:01:29.216  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
00:01:29.216  	at hudson.remoting.Request$2.run(Request.java:377)
00:01:29.216  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
00:01:29.216  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:01:29.216  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
00:01:29.216  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
00:01:29.216  	at java.base/java.lang.Thread.run(Thread.java:840)
00:01:29.216  Setting overall build result to FAILURE
00:01:29.233  [Pipeline] // catchError
00:01:29.243  [Pipeline] stage
00:01:29.245  [Pipeline] { (Epilogue)
00:01:29.260  [Pipeline] catchError
00:01:29.262  [Pipeline] {
00:01:29.274  [Pipeline] echo
00:01:29.275  Cleanup processes
00:01:29.279  [Pipeline] sh
00:01:30.219  + sudo pgrep -af /var/jenkins/workspace/nvmf-phy-autotest/spdk
00:01:30.219  784809 sudo pgrep -af /var/jenkins/workspace/nvmf-phy-autotest/spdk
00:01:30.233  [Pipeline] sh
00:01:30.518  ++ sudo pgrep -af /var/jenkins/workspace/nvmf-phy-autotest/spdk
00:01:30.519  ++ grep -v 'sudo pgrep'
00:01:30.519  ++ awk '{print $1}'
00:01:30.519  + sudo kill -9
00:01:30.519  + true
00:01:30.532  [Pipeline] sh
00:01:30.817  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:01:30.817  jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: line 9: cd: /var/jenkins/workspace/nvmf-phy-autotest/output: No such file or directory
00:01:30.828  [Pipeline] }
00:01:30.832  ERROR: script returned exit code 1
00:01:30.850  [Pipeline] // catchError
00:01:30.859  [Pipeline] echo
00:01:30.860  Tests finished with errors. Please check the logs for more info.
00:01:30.862  [Pipeline] echo
00:01:30.863  Execution node will be rebooted.
00:01:30.874  [Pipeline] build
00:01:30.875  Scheduling project: reset-job
00:01:30.885  [Pipeline] sh
00:01:31.167  + logger -p user.info -t JENKINS-CI
00:01:31.177  [Pipeline] }
00:01:31.193  [Pipeline] // stage
00:01:31.199  [Pipeline] }
00:01:31.218  [Pipeline] // node
00:01:31.224  [Pipeline] End of Pipeline
00:01:31.264  Finished: FAILURE

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_127291.html

**Comment by mikeBashStuff** [comment]
Our timeouts for all the http requests used for fetching repo packages are set to 60s. Clearly, for some connections this is not enough.  For this we should handle the exception AND increase the timeout.

**Comment by mikeBashStuff** [comment]
Mitigation implemented on CI's end, closing.
