### ISSUE TITLE
[nvmf] Assertion fired for non-empty sgroup->queued 

### ISSUE THREAD

**Issue by awarus** [spdk/spdk#3467]
# Sighting report

## Expected Behavior
No panic for PCI power off

## Current Behavior
```
#10 0x00007fffef533e96 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x00007fffefe18eaa in nvmf_poll_group_add_subsystem (group=0x7fff01c80080, subsystem=0x7ffe52870a20, cb_fn=0x7fffefe0b74b <subsystem_state_change_continue>, cb_arg=0x7ffecb810410) at nvmf.c:1650
#12 0x00007fffefe0b847 in subsystem_state_change_on_pg (i=0x7ffecb810410) at subsystem.c:698
#13 0x00007fffeff089dd in _call_channel (ctx=0x7ffecb810410) at thread.c:2562
#14 0x00007fffeff0459f in msg_queue_run_batch (thread=0x7fff1d101c20, max_msgs=8) at thread.c:854
#15 0x00007fffeff04f4b in thread_poll (thread=0x7fff1d101c20, max_msgs=0, now=1523553376354350) at thread.c:1076
#16 0x00007fffeff0528c in spdk_thread_poll (thread=0x7fff1d101c20, max_msgs=0, now=1523553376354350) at thread.c:1173
#17 0x00007fffefdea47d in _reactor_run (reactor=0x7fff1cc994c0) at reactor.c:923
#18 0x00007fffefdea595 in reactor_run (arg=0x7fff1cc994c0) at reactor.c:963
#19 0x00007fffeff3a6d6 in eal_thread_loop (arg=<optimized out>) at ../lib/eal/common/eal_common_thread.c:212
#20 0x00007fffeff4c0ef in eal_worker_thread_loop (arg=<optimized out>) at ../lib/eal/linux/eal.c:916
```

## Possible Solution
The assert was initially added in the https://review.spdk.io/gerrit/c/spdk/spdk/+/22474.
In the case of `nvmf_poll_group_add_subsystem() `running before the `_nvmf_qpair_sgroup_req_clean(`) we can have not empty sgroup->queued, thus hitting the assert. We should remove it to free the queued requests as we do it for qpair disconnect.

Another solution would be to mark sid as free only when there're no queued requests.

## Steps to Reproduce

1. start multiple creating/removing nvmf subsystems and namespaces with FIO load
2. echo "0" > /sys/bus/pci/slots/11/power

## Context (Environment including OS version, SPDK version, etc.)
SPDK: 24.05

**Comment by awarus** [comment]
@jimharris could you please look through if this is not a situation you've mentioned in the PR so I can make a PR for disabling the assert?

**Comment by shuhei-matsumoto** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/24648 Thank you for the patch.

**Comment by ksztyber** [comment]
The patch has been merged.
