### ISSUE TITLE
rpc vhost_delete_controller may block the entire reactor

### ISSUE THREAD

**Issue by xupeng-mingtu** [spdk/spdk#3468]
# Sighting report

rpc vhost_delete_controller may block the entire reactor.

When the vm is shut down, qemu will disconnect the session connection with vhost_block_controller. When the dpdk-vhost-evt thread handles the disconnection and unregister the memory, it will lock user_dev->lock.

If the vhost_delete_controller rpc is called before the memory unregister is completed, user_dev->lock also needs to be locked, so it will wait for the dpdk-vhost-evt thread to release the lock. During the waiting process, the reactor thread where app_thread is located will be blocked, causing other io to fail to complete normally.

## Expected Behavior

vhost_delete_controller rpc will not affect other IO.

## Current Behavior

vhost_delete_controller rpc may block the entire reactor and other IO will also be blocked

## Possible Solution

I make patch(https://review.spdk.io/gerrit/c/spdk/spdk/+/24402) that may reslove this issue, But not sure if this is a suitable approach

## Steps to Reproduce
This issue is not easy to reproduce. It requires that the dpdk-vhost-evt thread occupies user_dev->lock for a long time.

I am not sure whether dpdk-vhost-evt occupies user_dev->lock for a long time as expected, but it does happen in our environment.

We can reproduce this problem by actively injecting faults into the code: we need to add a `spdk_delay_us(10 * 1000 * 1000);` after obtaining user_dev->lock in the destroy_connection function of the lib/vhost/rte_vhost_user.c file.

1. create 2 VM: A and B using the same vhost, A is used to FIO ,B is used to shutdown
2. start FIO in A, shutdown B
3. call vhost_delete_controller for the blk_controller of B
4. the IO of A will blocked until the rpc finished

## Context (Environment including OS version, SPDK version, etc.)
v24.01

**Comment by xupeng-mingtu** [comment]
I upload a file that is record the stack of vhost when the issue occur in our env
[stack.log](https://github.com/user-attachments/files/16451726/stack.log)

From `Wed Jul 31 04:07:41 PM CST 2024` to `Wed Jul 31 04:07:55 PM CST 2024`, the dpdk-vhost-evt thread held user_dev->lock, and reactor_1 was blocked waiting for the lock. Other IO in reactor is also blocked

**Comment by Comphix** [comment]
Thanks @xupeng-mingtu , just updated this issue as your patch is under reviewing now.

**Comment by xupeng-mingtu** [comment]
fix patch(https://review.spdk.io/gerrit/c/spdk/spdk/+/24402) has been merged into master, close this issue.
