### ISSUE TITLE
Duplicate assignment in ftl_io.c

### ISSUE THREAD

**Issue by FlyCloudC** [spdk/spdk#3473]
https://github.com/spdk/spdk/blob/7066331afdbfd68aa9fbfed7f02524185e3df7dc/lib/ftl/ftl_io.c#L176-L179
Was that intentional or accidental?

**Comment by ksztyber** [comment]
[Bug scrub] @mmkayPL will take a look.

**Comment by mmkayPL** [comment]
I've double checked and it was an accidental leftover of merging two initialization functions into one. Added the fix: https://review.spdk.io/gerrit/c/spdk/spdk/+/24602
