### ISSUE TITLE
Invalid opts->opts_size

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3476]
# Sighting report

This has been constantly popping up under latest SPDK's master branch:
```
Invalid opts->opts_size 0 too small, please set opts_size correctly
```
and according to 57fd99b91e, it should be manually adjusted. From the user standpoint, this message is not very useful since it's clearly targeted for developers (lack of any log level also doesn't make it easier to understand if this is something to worry about or not) - as such, shouldn't this be written out under debug for instance?

**Comment by jimharris** [comment]
> > From the user standpoint, this message is not very useful since it's clearly targeted for developers (lack of any log level also doesn't make it easier to understand if this is something to worry about or not) - as such, shouldn't this be written out under debug for instance?
> 
> But this is something that a developer should fix. This just means that one of the apps doesn't doesn't set `spdk_env_opts.opts_size` when initializing the env library. It's not critical, as the defaults will be used in that case.
> 
> What are the apps that print this log?

I'm back at keyboard today, I'll take a look at this.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/24497

**Comment by jimharris** [comment]
Patch merged.
