### ISSUE TITLE
Implementing log with user-defined structure

### ISSUE THREAD

**Issue by SWaoter** [spdk/spdk#3480]
# Sighting report

I am working on implementing custom logger for SPDK. To be precise, I want to print logs in JSON format to stderr/syslog (for example: `{"level":"info","caller":"app.c:804:spdk_app_start","msg":"Total cores available: 1"}`).

I see that expected implementation of such task is providing `logfunc *logf` to `spdk_log_open`. However, that means that opening/closing needed descriptors(openlog/closelog) should be managed by user code.

I think that API for user-defined log can be extended to support providing custom open/close functions.

Please let me know if I'm doing something incorrectly and expected design for custom log is different.

## Current Behavior

User can provide only `logfunc *logf`

## Possible Solution

`spdk_log_open` accepts not only `logfunc *logf`, but:
```
struct logdesc {
    logfunc *logf;
    logopenfunc *logopenf;
    logclosefunc *logclosef;
    void *logctx;
};
```

Where `logf` will remain the same, and `logopenf`/`logclosef` will invoke user-defined open/close operations and manage user-defined `logctx`.

## Context (Environment including OS version, SPDK version, etc.)

Latest SPDK

**Comment by ksztyber** [comment]
[Bug scrub] @SWaoter what would be the benefit of doing that? If you're already calling spdk_log_open and providing your own custom callback, wouldn't it be easier to do any stuff related to opening the log prior to calling spdk_log_open?

**Comment by ksztyber** [comment]
That makes more sense. I think it does make sense to extend it the way you've suggested. Only I think we'll need to add a new function, e.g. `spdk_log_open_ext()`, to avoid breaking the ABI.

**Comment by SWaoter** [comment]
@ksztyber Are you interested in taking this? If not, I will work on it.

**Comment by ksztyber** [comment]
I wasn't planing on doing that, so you can go ahead.
