### ISSUE TITLE
[nvmf] Passthrough commands don't behave as intended if fabrics nsid and nvme nsid differ

### ISSUE THREAD

**Issue by karlowich** [spdk/spdk#3486]
If a user adds an nvme namespace to a fabrics subsystem with a different nsid than the underlying nvme namespace, any passthrough command directed at the namespace will have the wrong nsid.

An example being adding a `bdev_nvme` namespace `nvme1n1` to a `nvmf_subsystem` specifying nsid 2. In this case, any passthrough command sent to the fabrics namespace should have nsid 2, but when the command is sent to the underlying nvme namespace it should have nsid 1.

I have a proposed solution here: https://review.spdk.io/gerrit/c/spdk/spdk/+/24454

The RPCs required for creating the subsystem are:
```
scripts/rpc.py nvmf_create_transport -t tcp -u 16384 -m 8 -c 8192
scripts/rpc.py nvmf_create_subsystem nqn.2019-08.org.qemu:deadbeef -a -s SPDK00000000000001 -d Controller1
scripts/rpc.py bdev_nvme_attach_controller -b nvme1 -t PCIe -a 0000:01:00.0
scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-08.org.qemu:deadbeef nvme1n1 -n 2
scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-08.org.qemu:deadbeef -t tcp -a 127.0.0.1 -s 4420 -f ipv4
```

I encountered it when working on patches for a passthrough nvmf subsystem. However, without those changes, sending a passthrough command can be tricky. Since, any non-recognized I/O commands will go through the passthrough path, it is definitely possible to encounter the bug with the latest version of SPDK.

**Comment by jimharris** [comment]
Patches were merged.
