### ISSUE TITLE
vhost: don't leak hugepages when killed with SIGKILL

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#349]
## Expected Behavior

When the app/vhost/vhost binary gets killed with SIGKILL, the kernel should free as many resources as possible.

## Current Behavior

Entries in /dev/hugepages are left behind because the process only frees resp. deletes the pages when shutting down cleanly.

## Possible Solution

Not sure whether it is possible, but perhaps the file entries in /dev/hugepages can already be deleted while they are still in use and perhaps that'll cause the kernel to unlock the pages on process termination?

We discussed this on IRC and opinions were divided whether that would work. Let's use this issue to investigate and (perhaps) implement the idea.
```
(05:32:41 PM) pohly: Does vhost have to exit cleanly to remove its /dev/hugepages entries?
(05:32:58 PM) darsto: yes
(05:33:39 PM) darsto: these won't be cleaned up if you used kill -9 or so
(05:41:28 PM) lhodev left the room (quit: Quit: My MacBook has gone to sleep. ZZZzzz…).
(06:15:04 PM) pohly: darsto: what happens when removing those entries while the process that is using them still runs>
(06:15:05 PM) pohly: ?
(06:15:38 PM) pohly: Sorry for the naive questions :-/ I have no clue how the huge pages API works.
(06:16:40 PM) darsto: i'm not sure actually
(06:17:48 PM) pwodkowx: thos are pseudo files to express physical memory mapings.
(06:17:50 PM) darsto: i could guess nothing bad happens
(06:18:34 PM) darsto: the hugepage memory should be still locked up
(06:19:50 PM) pwodkowx: I think, attaching another process using shared mmeory ID might not work
(06:20:33 PM) pohly: pwodkowx: is that something that needs to work for SPDK?
(06:21:02 PM) pohly: Because if it is fine to already delete the files while still in use, then spdk itself could do that and there would be no risk of leaking resources.
(06:21:08 PM) darsto: pwodkowx: there's that one file that hold primary process data, but it's not in /dev/hugepages
(06:21:15 PM) pwodkowx: I depend what you need :)
(06:21:40 PM) pwodkowx: * it
```

**Comment by pohly** [comment]
pawelwod <notifications@github.com> writes:
> As @darsto mentioned, "these won't be cleaned up if you used kill -9
> or so". "or so" mean crash.

True, the program itself can't clean up in this case. That's why I was
suggesting that the kernel should clean up as much as possible. In our
IRC discussion it did not become clear to me why that can't work for
huge pages.

Note that I am not talking about the SPDK library, only about the vhost
app. That app may be able to set up huge memory usage differently and
more crash-resilient than the library itself.

**Comment by pohly** [comment]
Yes. There's two things that the app can do:
- signal handling (but that is covered by issue #350)
- allocating resources such that they get freed by the kernel on process exit

A temp file that gets unlinked while it is open is the classic example for the latter. I don't know whether that can be done for huge pages, but IMHO it is worth investigating (this issue).

**Comment by pawelwod** [comment]
We already handling SIGINT and SIGTERM but issue is that DPDK is not unlinking those files. There is experimental function `rte_eal_cleanup()` that we can call. I will check if this will work in case of clean exit (#350). As we (SPDK) are not managing those hugepage files directly but using DPDK for that, in case of  SIGKILL or crash I don't have any idea how to cleanup those artifacts. So this could solve #350 but for this issue I don't know how to do that without dirty hacks.

**Comment by pawelwod** [comment]
Nope, despite DPDK 18.02 description 
```
Shutdown and Cleanup
~~~~~~~~~~~~~~~~~~~~

During the initialization of EAL resources such as hugepage backed memory can be
allocated by core components.  The memory allocated during ``rte_eal_init()``
can be released by calling the ``rte_eal_cleanup()`` function. Refer to the
API documentation for details.
```

the ``rte_eal_cleanup()`` function doesn't do what the claim 👎

**Comment by changpe1** [comment]
DPDK has a long option "--huge-unlink", currently SPDK don't enable this option, it can unlink all the huge files after initialization of  huge files. I tested in my local server, it worked, and I will submit a patch to enable this option.

**Comment by changpe1** [comment]
https://review.gerrithub.io/#/c/419156/ patch has been merged, users can add -R parameter when starting vhost application, and the huge pages can be released when exit.

**Comment by pohly** [comment]
Works for me.

**Comment by xfliu2665** [comment]
> DPDK has a long option "--huge-unlink", currently SPDK don't enable this option, it can unlink all the huge files after initialization of huge files. I tested in my local server, it worked, and I will submit a patch to enable this option.

 i got a questions when running dpdk about huge pages(may have nothing to do with dpdk).  when dpdk-app stopped for some reasons, the huge pages obtained by it before may won't be freed. and from then on, dpdk-app can't run again for no huge pages available unless you increase nr_hugepages.  what's more,  i can't free the 'disappeared' huge pages through manual writing huge-page fs.  take a look at my operations below
# echo 0 > /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
# cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/surplus_hugepages
6
# cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
6
it seems the huge-pages are still hold by dpdk, but i can't find why. i have tried some ways but none of them works
remove the dpdk running path at /var/run/dpdk
umount huge-page and delete the mounted dir
and i found the write-operation for nr_hugepages is ok(i test it with kretprobe),does't take effect however

**Comment by jimharris** [comment]
Hi @xfliu2665,

I would suggest that you submit a new GitHub issue, with specific details on how to reproduce the problem that you are seeing.

Jim
