### ISSUE TITLE
Abort submission always fails for DSM Commands

### ISSUE THREAD

**Issue by sanghogit** [spdk/spdk#3490]
# Sighting report

The abort command works reasonably well with read and write commands, but it consistently **fails to submit** when applied to DSM (Dataset Management) commands

## Expected Behavior

The abort command submission should succeed in some cases and fail in others.

## Current Behavior

Abort submission always fails for DSM Commands

## Steps to Reproduce
Reproduce the issue by slightly modifying examples/nvme/abort/abort.c as follows.

1. Modifiy abort.c to perform a DSM command instead of a write command.
```
diff --git a/examples/nvme/abort/abort.c b/examples/nvme/abort/abort.c
index dd01a5c67..5bc52376d 100644
--- a/examples/nvme/abort/abort.c
+++ b/examples/nvme/abort/abort.c
@@ -345,8 +345,12 @@ submit_single_io(struct perf_task *task)
 		rc = spdk_nvme_ns_cmd_read(entry->ns, ns_ctx->qpair, task->buf,
 					   lba, entry->io_size_blocks, io_complete, task, 0);
 	} else {
-		rc = spdk_nvme_ns_cmd_write(entry->ns, ns_ctx->qpair, task->buf,
-					    lba, entry->io_size_blocks, io_complete, task, 0);
+		struct spdk_nvme_dsm_range range;
+		range.starting_lba = lba;
+		range.length = entry->io_size_blocks;
+		range.attributes.raw = 0;
+		rc = spdk_nvme_ns_cmd_dataset_management( entry->ns, ns_ctx->qpair, 
+						SPDK_NVME_DSM_ATTR_DEALLOCATE, &range, 1, io_complete, task);
 	}
 
 	if (spdk_unlikely(rc != 0)) {
```

2. Run with "-w write" option
```
# build/examples/abort -q 16 -o 4096 -w write -t 3 -r "trtype:PCIe traddr:0000:71:00.0" -a 1
Initializing NVMe Controllers
Attached to NVMe Controller at 0000:71:00.0 [144d:a80a]
Associating PCIE (0000:71:00.0) NSID 1 with lcore 0
Initialization complete. Launching workers.
NS: PCIE (0000:71:00.0) NSID 1 I/O completed: 11411, failed: 0
CTRLR: PCIE (0000:71:00.0) abort submitted 0, failed to submit 11411
         success 0, unsuccessful 0, failed 0

# build/examples/abort -q 32 -o 4096 -w write -t 3 -r "trtype:PCIe traddr:0000:71:00.0" -a 1
Initializing NVMe Controllers
Attached to NVMe Controller at 0000:71:00.0 [144d:a80a]
Associating PCIE (0000:71:00.0) NSID 1 with lcore 0
Initialization complete. Launching workers.
NS: PCIE (0000:71:00.0) NSID 1 I/O completed: 11390, failed: 0
CTRLR: PCIE (0000:71:00.0) abort submitted 0, failed to submit 11390
         success 0, unsuccessful 0, failed 0
```

Regardless of the IO depth, all abort commands fail to submit.

However, abort works correctly for read commands
```
# build/examples/abort -q 64 -o 4096 -w read -t 3 -r "trtype:PCIe traddr:0000:71:00.0" -a 1
Initializing NVMe Controllers
Attached to NVMe Controller at 0000:71:00.0 [144d:a80a]
Associating PCIE (0000:71:00.0) NSID 1 with lcore 0
Initialization complete. Launching workers.
NS: PCIE (0000:71:00.0) NSID 1 I/O completed: 756203, failed: 3
CTRLR: PCIE (0000:71:00.0) abort submitted 53611, failed to submit 702595
         success 3, unsuccessful 53608, failed 0
```

## Context (Environment including OS version, SPDK version, etc.)

```
# git log -1 --format=%cd
Fri Aug 16 17:28:03 2024 +0000
$ git branch
* master
$ uname -sr
Linux 6.5.0-44-generic
```

**Comment by jimharris** [comment]
Can you try https://review.spdk.io/gerrit/c/spdk/spdk/+/24587?

**Comment by sanghogit** [comment]
> Can you try https://review.spdk.io/gerrit/c/spdk/spdk/+/24587?

Yes, that resolved my issue. Thank you very much!

**Comment by sanghogit** [comment]
However, there is a similar if statement in the nvme_qpair_abort_queued_reqs_with_cbarg() function in nvme_qpair.c. What about this one?

**Comment by jimharris** [comment]
> BTW, there is a similar if statement in the nvme_qpair_abort_queued_reqs_with_cbarg() function in nvme_qpair.c. What about this one?
> 
> https://github.com/spdk/spdk/blob/3a4dea18165962a1ee6854b58dccc6bb0cc24740/lib/nvme/nvme_qpair.c#L619

Yes, that one needs to be fixed too.

I've pushed a second version of the above patch. There's now a prep patch that moves this logic to a helper function.

**Comment by jimharris** [comment]
Patches were merged.
