### ISSUE TITLE
Potential precision loss in random I/O generation for large devices

### ISSUE THREAD

**Issue by conceptor-pepe** [spdk/spdk#3494]
# Sighting report
Description:
In the function `submit_single_io()` in [https://github.com/spdk/spdk/tree/master/app/spdk_nvme_perf/perf.c], the use of `rand_r()` for generating random I/O offsets may lead to precision loss and incomplete coverage for large storage devices.

Problem:
- `rand_r()` returns a 32-bit int, which is insufficient for devices larger than 2^31 * 4KB ≈ 8TB (assuming 4KB I/O size).
- For larger devices, this results in the higher I/O positions never being randomly selected.

Example:
For a 15.68TB device, the total number of 4KB I/Os is approximately 3.83 * 10^9, which exceeds the maximum value `rand_r()` can generate.

Suggested fix:
Replace the current random generation with a 64-bit approach, either by using a native 64-bit random function or by combining two 32-bit random calls.

This change ensures full coverage of I/O positions for large devices and maintains the randomness of the benchmark for all device sizes.

**Comment by jimharris** [comment]
Good catch. Can you try https://review.spdk.io/gerrit/c/spdk/spdk/+/24622?

**Comment by jimharris** [comment]
Patch was merged.
