### ISSUE TITLE
[release-build-main-docker-autotest] docker-autoruner.sh: line 74: build_release: command not found

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#3500]
# CI Intermittent Failure

00:00:58.533  + jbp/jenkins/jjb-config/jobs/scripts/docker-autoruner.sh release-build-main-docker-autotest autorun-spdk.conf
00:00:58.533    01:11:45  -- common/autobuild_common.sh@15 -- # source /var/jenkins/workspace/release-build-main-docker-autotest/spdk/scripts/common.sh
00:00:58.533     01:11:45  -- scripts/common.sh@508 -- # [[ -e /bin/wpdk_common.sh ]]
00:00:58.533     01:11:45  -- scripts/common.sh@516 -- # [[ -e /etc/opt/spdk-pkgdep/paths/export.sh ]]
00:00:58.533     01:11:45  -- scripts/common.sh@517 -- # source /etc/opt/spdk-pkgdep/paths/export.sh
00:00:58.533      01:11:45  -- paths/export.sh@2 -- # PATH=/opt/golangci/1.54.2/bin:/opt/protoc/21.7/bin:/opt/go/1.21.1/bin:/opt/golangci/1.54.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
00:00:58.533      01:11:45  -- paths/export.sh@3 -- # PATH=/opt/go/1.21.1/bin:/opt/golangci/1.54.2/bin:/opt/protoc/21.7/bin:/opt/go/1.21.1/bin:/opt/golangci/1.54.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
00:00:58.533      01:11:45  -- paths/export.sh@4 -- # PATH=/opt/protoc/21.7/bin:/opt/go/1.21.1/bin:/opt/golangci/1.54.2/bin:/opt/protoc/21.7/bin:/opt/go/1.21.1/bin:/opt/golangci/1.54.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
00:00:58.533      01:11:45  -- paths/export.sh@5 -- # export PATH
00:00:58.533      01:11:45  -- paths/export.sh@6 -- # echo /opt/protoc/21.7/bin:/opt/go/1.21.1/bin:/opt/golangci/1.54.2/bin:/opt/protoc/21.7/bin:/opt/go/1.21.1/bin:/opt/golangci/1.54.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
00:00:58.533    01:11:45  -- common/autobuild_common.sh@446 -- # out=/var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output
00:00:58.533      01:11:45  -- common/autobuild_common.sh@447 -- # date +%s
00:00:58.533     01:11:45  -- common/autobuild_common.sh@447 -- # mktemp -dt spdk_1724375505.XXXXXX
00:00:58.533    01:11:45  -- common/autobuild_common.sh@447 -- # SPDK_WORKSPACE=/tmp/spdk_1724375505.vJz6aF
00:00:58.533    01:11:45  -- common/autobuild_common.sh@449 -- # [[ -n '' ]]
00:00:58.533    01:11:45  -- common/autobuild_common.sh@453 -- # '[' -n '' ']'
00:00:58.533    01:11:45  -- common/autobuild_common.sh@456 -- # scanbuild_exclude='--exclude /var/jenkins/workspace/release-build-main-docker-autotest/spdk/dpdk/'
00:00:58.533    01:11:45  -- common/autobuild_common.sh@460 -- # scanbuild_exclude+=' --exclude /var/jenkins/workspace/release-build-main-docker-autotest/spdk/xnvme --exclude /tmp'
00:00:58.533    01:11:45  -- common/autobuild_common.sh@462 -- # scanbuild='scan-build -o /var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output/scan-build-tmp --exclude /var/jenkins/workspace/release-build-main-docker-autotest/spdk/dpdk/ --exclude /var/jenkins/workspace/release-build-main-docker-autotest/spdk/xnvme --exclude /tmp --status-bugs'
00:00:58.533     01:11:45  -- common/autobuild_common.sh@463 -- # get_config_params
00:00:58.533     01:11:45  -- common/autotest_common.sh@394 -- # xtrace_disable
00:00:58.533     01:11:45  -- common/autotest_common.sh@10 -- # set +x
00:00:58.533    01:11:45  -- common/autobuild_common.sh@463 -- # config_params='--enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --with-vbdev-compress --with-dpdk-compressdev --with-rbd --with-crypto --with-ocf --enable-coverage --with-fuse --with-ublk --with-raid5f --with-vfio-user --with-uring --with-xnvme'
00:00:58.533    01:11:45  -- common/autobuild_common.sh@465 -- # start_monitor_resources
00:00:58.533    01:11:45  -- pm/common@17 -- # local monitor
00:00:58.533    01:11:45  -- pm/common@19 -- # for monitor in "${MONITOR_RESOURCES[@]}"
00:00:58.533    01:11:45  -- pm/common@19 -- # for monitor in "${MONITOR_RESOURCES[@]}"
00:00:58.533    01:11:45  -- pm/common@25 -- # sleep 1
00:00:58.533     01:11:45  -- pm/common@21 -- # date +%s
00:00:58.533     01:11:45  -- pm/common@21 -- # date +%s
00:00:58.533    01:11:45  -- pm/common@21 -- # /var/jenkins/workspace/release-build-main-docker-autotest/spdk/scripts/perf/pm/collect-cpu-load -d /var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output/power -l -p monitor.docker-autoruner.sh.1724375505
00:00:58.534    01:11:45  -- pm/common@21 -- # /var/jenkins/workspace/release-build-main-docker-autotest/spdk/scripts/perf/pm/collect-vmstat -d /var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output/power -l -p monitor.docker-autoruner.sh.1724375505
00:00:58.534  Redirecting to /var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output/power/monitor.docker-autoruner.sh.1724375505_collect-vmstat.pm.log
00:00:58.534  Redirecting to /var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output/power/monitor.docker-autoruner.sh.1724375505_collect-cpu-load.pm.log
00:00:59.476    01:11:46  -- common/autobuild_common.sh@466 -- # trap stop_monitor_resources EXIT
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@11 -- # cd /var/jenkins/workspace/release-build-main-docker-autotest/spdk
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@13 -- # cp /var/spdk/build-repo-manifest.txt /var/jenkins/workspace/release-build-main-docker-autotest/output
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@21 -- # [[ release-build-main-docker-autotest == unittest-valgrind-docker-autotest ]]
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@26 -- # cpus_limit=26
00:00:59.476    01:11:46  -- scripts/docker-autoruner.sh@27 -- # nproc
00:00:59.476    01:11:46  -- scripts/docker-autoruner.sh@27 -- # nproc
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@27 -- # export 'MAKEFLAGS=-j 26'
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@27 -- # MAKEFLAGS='-j 26'
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@29 -- # [[ -n '' ]]
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@39 -- # case "$job_name" in
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@74 -- # build_release
00:00:59.476  jbp/jenkins/jjb-config/jobs/scripts/docker-autoruner.sh: line 74: build_release: command not found
00:00:59.476    01:11:46  -- scripts/docker-autoruner.sh@74 -- # trap - ERR
00:00:59.476    01:11:46  -- scripts/docker-autoruner.sh@74 -- # print_backtrace
00:00:59.476    01:11:46  -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
00:00:59.476    01:11:46  -- common/autotest_common.sh@1151 -- # args=()
00:00:59.476    01:11:46  -- common/autotest_common.sh@1151 -- # local args
00:00:59.476    01:11:46  -- common/autotest_common.sh@1153 -- # xtrace_disable
00:00:59.476    01:11:46  -- common/autotest_common.sh@10 -- # set +x
00:00:59.476  ========== Backtrace start: ==========
00:00:59.476  
00:00:59.476  in jbp/jenkins/jjb-config/jobs/scripts/docker-autoruner.sh:74 -> main([])
00:00:59.476       ...
00:00:59.476  backtrace unavailable
00:00:59.476       ...
00:00:59.476  
00:00:59.476  ========== Backtrace end ==========
00:00:59.476    01:11:46  -- common/autotest_common.sh@1190 -- # return 0
00:00:59.476   01:11:46  -- scripts/docker-autoruner.sh@1 -- # stop_monitor_resources
00:00:59.476   01:11:46  -- pm/common@29 -- # signal_monitor_resources TERM
00:00:59.476   01:11:46  -- pm/common@40 -- # local monitor pid pids signal=TERM
00:00:59.476   01:11:46  -- pm/common@42 -- # for monitor in "${MONITOR_RESOURCES[@]}"
00:00:59.476   01:11:46  -- pm/common@43 -- # [[ -e /var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output/power/collect-cpu-load.pid ]]
00:00:59.476   01:11:46  -- pm/common@44 -- # pid=177
00:00:59.476   01:11:46  -- pm/common@50 -- # kill -TERM 177
00:00:59.476   01:11:46  -- pm/common@42 -- # for monitor in "${MONITOR_RESOURCES[@]}"
00:00:59.476   01:11:46  -- pm/common@43 -- # [[ -e /var/jenkins/workspace/release-build-main-docker-autotest/spdk/../output/power/collect-vmstat.pid ]]
00:00:59.476   01:11:46  -- pm/common@44 -- # pid=179
00:00:59.476   01:11:46  -- pm/common@50 -- # kill -TERM 179
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/128565/archive/release-build-main-docker-autotest_304/index.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_128565.html

**Comment by mikeBashStuff** [comment]
Please, see 58674af016 - the affected patches need to be rebased to include that change.
