### ISSUE TITLE
bdev_nvme: dump_config_json does not emit 'multipath' parameter for 'bdev_nvme_attach_controller'

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3502]
Reproduction steps:

1) Set up nvmf target with a single NULL block device, add it to an nvmf subsystem, and add two listeners to that subsystem (same IP address, different ports)
2) Start a second nvmf target, issue two `bdev_nvme_attach_controller` RPCs, one for each listener, specifying `-x multipath` for both
3) Send a `save_config` RPC to the second nvmf target, redirecting the output to a file
4) Restart the second nvmf target, with output file from step 3
5) Send a `bdev_nvme_get_controllers` RPC to the second nvmf target. Observe that the second controller is shown as an alternate trid. This means it was configured for `failover` not `multipath`.

Found while working with @freddiehaddad on Slack.

**Comment by m-spiewak** [comment]
Just for future reference, here are example RPC commands:

```
sudo build/bin/nvmf_tgt -m 0x01
sudo scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
sudo scripts/rpc.py bdev_null_create Null0 512 512
sudo scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
sudo scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Null0
sudo scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t TCP -a 127.0.0.1 -s 4420
sudo scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t TCP -a 127.0.0.1 -s 4421

```
And second target:
```
sudo build/bin/nvmf_tgt -m 0x2 -r  /var/tmp/spdk2.sock
sudo scripts/rpc.py -s /var/tmp/spdk2.sock bdev_nvme_attach_controller -b Nvme5 -t TCP -f IPv4 -a 127.0.0.1 -s 4420 -n nqn.2016-06.io.spdk:cnode1
sudo scripts/rpc.py -s /var/tmp/spdk2.sock bdev_nvme_attach_controller -b Nvme5 -t TCP -f IPv4 -a 127.0.0.1 -s 4421 -n nqn.2016-06.io.spdk:cnode1 -x multipath
```

**Comment by m-spiewak** [comment]
The problem seems to be more generic and not restricted to 'multipath' only. If you send two `bdev_nvme_attach_controller` RPCs and not specify `-x multipath` for neither, there will be one controller create with alternate trid provided (so it is failover).
After `save_config` and restarting the second target from the saved config file, the second controller is not present at all.

**Comment by m-spiewak** [comment]
No, if no 'multipath' specified it just adds alternate transport for existing controller without any errors. 
I'm working on a fix that will fix both scenarios - saving proper config for failover mode, and then I will fix multipath.

**Comment by m-spiewak** [comment]
> I see the -r flag was omitted
If you use default socket, you don't have to specify it via -r parameter.

**Comment by freddiehaddad** [comment]
> No, if no 'multipath' specified it just adds alternate transport for existing controller without any errors. I'm working on a fix that will fix both scenarios - saving proper config for failover mode, and then I will fix multipath.

I'm not seeing the error you describe.  The main difference in the reported bug and what Jim and I saw are the use of a different block devices (NVMe).  I'll create two more comments with my full failover and multipath steps (in case they are helpful).  They are also what I'm going to contribute to the documentation.

**Comment by freddiehaddad** [comment]
# Instructions for Configuring Failover Tests

## Target 1 VM (Active)

```text
cd /opt/spdk
sudo ./scrips/setup.sh
sudo ./build/bin/nvmf_tgt -m 0xfff
```

In another terminal run:

```text
cd /opt/spdk
IP=$(ip address show dev eth0 | grep -oP "inet \K\d+.\d+.\d+.\d+")
PORT=4420
sudo ./scripts/rpc.py nvmf_create_transport -t tcp -o -u 8192
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2024-08.io.spdk:cnode0 -a -s SPDK00000000000001 -r
sudo ./scripts/rpc.py bdev_aio_create /dev/nvme0n2 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_ns --uuid 80bc7acd-e032-40bc-acd6-45bc7bb96690 --nguid 2016595ab52040fbac2e7297c5e5fbfa --eui64 36dbe32e8a9c40c1 nqn.2024-08.io.spdk:cnode0 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_listener -t tcp -a $IP -s $PORT nqn.2024-08.io.spdk:cnode0
```

## Target 2 VM (Passive)

```text
cd /opt/spdk
sudo ./scrips/setup.sh
sudo ./build/bin/nvmf_tgt -m 0xfff
```

In another terminal run:

```text
cd /opt/spdk
IP=$(ip address show dev eth0 | grep -oP "inet \K\d+.\d+.\d+.\d+")
PORT=4420
sudo ./scripts/rpc.py nvmf_create_transport -t tcp -o -u 8192
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2024-08.io.spdk:cnode0 -a -s SPDK00000000000001 -r
sudo ./scripts/rpc.py bdev_aio_create /dev/nvme0n2 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_ns --uuid 80bc7acd-e032-40bc-acd6-45bc7bb96690 --nguid 2016595ab52040fbac2e7297c5e5fbfa --eui64 36dbe32e8a9c40c1 nqn.2024-08.io.spdk:cnode0 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_listener -t tcp -a $IP -s $PORT nqn.2024-08.io.spdk:cnode0
```

## Initiator VM

The first step is to generate a configuration file for `bdevperf` which is used to drive the failover test.

### Generate a Configuration File

In a terminal run:

```text
cd /opt/spdk
sudo ./scrips/setup.sh
sudo ./build/bin/spdk_tgt -m 0xfff
```

In another terminal run:

```text
cd /opt/spdk
sudo ./scripts/rpc.py bdev_nvme_set_options -r -1
sudo ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t tcp -a 10.1.0.5 -s 4420 -f ipv4 -n nqn.2024-08.io.spdk:cnode0 -q nqn.2024-08.io.spdk -l -1 -o 10
sudo ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t tcp -a 10.1.0.6 -s 4420 -f ipv4 -n nqn.2024-08.io.spdk:cnode0 -q nqn.2024-08.io.spdk -x multipath -l -1 -o 10
sudo ./scripts/rpc.py save_config > ~/bdevperf_failover.conf
```

### Test Initialization

Return to the window where `spdk_tgt` is running and press `ctrl+c` to kill the process.

Run the following command:

```text
sudo ./build/examples/bdevperf -m 0xfff -z -q 32 -o 8192 -w write -ll -t 300 -c ~/bdevperf_failover.conf
```
NOTE: You can tweak the configuration parameters before running the command (see `bdevperf --help`).

In another terminal run:

```text
sudo PYTHONPATH=$PYTHONPATH:/opt/spdk/python ./examples/bdev/bdevperf/bdevperf.py perform_tests
```

## Observing the Test

In each of the target VMs you can run the following commands in separate terminals to watch network traffic.

```text
watch -n 1 ss -t
```

```text
watch -n 1 ./scripts/iostat.py
```

## Triggering the Failover

In the terminal window where `nvmf_tgt` process is running on Target VM 1, press `ctrl+c` to kill the process. Observe the traffic on Target VM 2.

**Comment by freddiehaddad** [comment]
# Instructions for Configuring Multipath Tests

## Target 1 VM (Active)

```text
cd /opt/spdk
sudo ./scrips/setup.sh
sudo ./build/bin/nvmf_tgt -m 0xfff
```

In another terminal run:

```text
cd /opt/spdk
IP=$(ip address show dev eth0 | grep -oP "inet \K\d+.\d+.\d+.\d+")
PORT=4420
sudo ./scripts/rpc.py nvmf_create_transport -t tcp -o -u 8192
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2024-08.io.spdk:cnode0 -a -s SPDK00000000000001 -r
sudo ./scripts/rpc.py bdev_aio_create /dev/nvme0n2 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_ns --uuid 80bc7acd-e032-40bc-acd6-45bc7bb96690 --nguid 2016595ab52040fbac2e7297c5e5fbfa --eui64 36dbe32e8a9c40c1 nqn.2024-08.io.spdk:cnode0 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_listener -t tcp -a $IP -s $PORT nqn.2024-08.io.spdk:cnode0
sudo ./scripts/rpc.py nvmf_subsystem_listener_set_ana_state nqn.2024-08.io.spdk:cnode0 -t tcp -a $IP -s $PORT -n optimized
```

## Target 2 VM (Passive)

```text
cd /opt/spdk
sudo ./scrips/setup.sh
sudo ./build/bin/nvmf_tgt -m 0xfff
```

In another terminal run:

```text
cd /opt/spdk
IP=$(ip address show dev eth0 | grep -oP "inet \K\d+.\d+.\d+.\d+")
PORT=4421
sudo ./scripts/rpc.py nvmf_create_transport -t tcp -o -u 8192
sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2024-08.io.spdk:cnode0 -a -s SPDK00000000000001 -r
sudo ./scripts/rpc.py bdev_aio_create /dev/nvme0n2 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_ns --uuid 80bc7acd-e032-40bc-acd6-45bc7bb96690 --nguid 2016595ab52040fbac2e7297c5e5fbfa --eui64 36dbe32e8a9c40c1 nqn.2024-08.io.spdk:cnode0 aio0
sudo ./scripts/rpc.py nvmf_subsystem_add_listener -t tcp -a $IP -s $PORT nqn.2024-08.io.spdk:cnode0
sudo ./scripts/rpc.py nvmf_subsystem_listener_set_ana_state nqn.2024-08.io.spdk:cnode0 -t tcp -a $IP -s $PORT -n optimized
```

## Initiator VM

The first step is to generate a configuration file for `bdevperf` which is used to drive the failover test.

### Generate a Configuration File

In a terminal run:

```text
cd /opt/spdk
sudo ./scrips/setup.sh
sudo ./build/bin/spdk_tgt -m 0xfff
```

In another terminal run:

```text
cd /opt/spdk
sudo ./scripts/rpc.py bdev_nvme_set_options -r -1
sudo ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t tcp -a 10.1.0.5 -s 4420 -f ipv4 -n nqn.2024-08.io.spdk:cnode0 -q nqn.2024-08.io.spdk -x multipath -l -1 -o 10
sudo ./scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t tcp -a 10.1.0.6 -s 4421 -f ipv4 -n nqn.2024-08.io.spdk:cnode0 -q nqn.2024-08.io.spdk -x multipath -l -1 -o 10
sudo ./scripts/rpc.py bdev_nvme_set_multipath_policy -b Nvme0n1 -p active_active -s round_robin
sudo ./scripts/rpc.py save_config > ~/bdevperf_multipath.conf
```

**At the time of writing, there's a bug in the `save_config` `rpc` where the multipath settings are omitted.**

To correct, open the `bdevperf_multipath.conf` file and add the key/value pair `"multipath": "multipath"` to the `params` section of each `bdev_nvme_attach_controller` method:

```json
{
  "method": "bdev_nvme_attach_controller",
  "params": {
    "multipath": "multipath",
    "name": "Nvme0",
    "trtype": "TCP",
    "adrfam": "IPv4",
    "traddr": "10.1.0.5",
    "trsvcid": "4420",
    "subnqn": "nqn.2024-08.io.spdk:cnode0",
    "prchk_reftag": false,
    "prchk_guard": false,
    "ctrlr_loss_timeout_sec": -1,
    "reconnect_delay_sec": 10,
    "fast_io_fail_timeout_sec": 0,
    "hostnqn": "nqn.2024-08.io.spdk",
    "hdgst": false,
    "ddgst": false
  }
},
```

### Test Initialization

Return to the window where `spdk_tgt` is running and press `ctrl+c` to kill the process.

Run the following command:

```text
sudo ./build/examples/bdevperf -m 0xfff -z -q 32 -o 8192 -w write -ll -t 300 -c ~/bdevperf_multipath.conf
```
NOTE: You can tweak the configuration parameters before running the command (see `bdevperf --help`).

In another terminal run:

```text
sudo ./scripts/rpc.py bdev_nvme_set_multipath_policy -b Nvme0n1 -p active_active -s round_robin
sudo PYTHONPATH=$PYTHONPATH:/opt/spdk/python ./examples/bdev/bdevperf/bdevperf.py perform_tests
```

## Observing the Test

In each of the target VMs you can run the following commands in separate terminals to watch network traffic.

```text
watch -n 1 ss -t
```

```text
watch -n 1 ./scripts/iostat.py
```

## Triggering the Failover

In the terminal window where `nvmf_tgt` process is running on Target VM 1, press `ctrl+c` to kill the process. Observe the traffic on Target VM 2.

**Comment by shuhei-matsumoto** [comment]
> Did you happen to see an error when running the `bdev_nvme_attach_controller` RPC for the second target? Something like:
> 
> ```
> [2024-08-29 20:19:15.522854] bdev_nvme.c:5427:bdev_nvme_check_multipath: *ERROR*: cntlid 4 are duplicated.
> ```
> 
> Is the ANA reporting feature required for this to work?
> 
> I see the `-r` flag was omitted in:
> 
> ```
> sudo scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
> ```

@freddiehaddad  Thank you for writing down the detailed steps. Two target subsystems are not coordinated/synchronized. Each target subsystem manages controller ID independently. Hence, such duplication can happen.

One solution may be helpful.
The nvmf_create_subsystem RPC has two parameters, min_cntlid and max_cntlid.
If you set these to non-overlapped values between two target subsystems, duplication should not happen. Will you check?

**Comment by shuhei-matsumoto** [comment]
@m-spiewak Thank you for working on this. If I understand correctly, please use `nbdev_ctrlr->ctrlrs` for `-x multipath` and `nvme_ctrlr->trids` for `-x failover`.

**Comment by freddiehaddad** [comment]
> One solution may be helpful.
> The nvmf_create_subsystem RPC has two parameters, min_cntlid and max_cntlid.
> If you set these to non-overlapped values between two target subsystems, duplication should not
> happen. Will you check?

I tried your suggestion several times and each time was successful.  No error messages were shown about duplicate controllers. So, this seems to be working.

**Comment by m-spiewak** [comment]
@freddiehaddad patches with fixes are out for review, you can test in your system.
https://review.spdk.io/gerrit/c/spdk/spdk/+/24813
https://review.spdk.io/gerrit/c/spdk/spdk/+/24764
