### ISSUE TITLE
bdev_get_iostat with reset

### ISSUE THREAD

**Issue by SWaoter** [spdk/spdk#3525]
# Sighting report

Currently to reset iostat for bdev we have to explicitly call `bdev_reset_iostat`. Let me explain use case when such approach have disadvantage.
Let's say that we want to track bdev `max_read_latency_ticks` over the last minute. Because it is metric that can't be aggregated - we have to do following:
1) Call `bdev_get_iostat` to obtain longest request for the last minute
2) Call `bdev_reset_iostat -m maxmin` to start collecting stats for the next minute

It is obvious that request may occur between 1) and 2) that will be longest and that it will never be reported.

## Expected Behavior

Calling `bdev_reset_iostat` does not result in losing statistics.

## Possible Solution

Add option to `bdev_get_iostat`: `--with_reset <reset_mode>`

By doing so we can reset stat right after we have aggregated it. Because stats are stored per-channel, we can guarantee that no races will happen.

## Context (Environment including OS version, SPDK version, etc.)

Latest SPDK

**Comment by jimharris** [comment]
The proposed solution sounds good to me. @SWaoter, do you plan to implement it?

**Comment by SWaoter** [comment]
@jimharris Sure, I can take a look
