### ISSUE TITLE
fsdev/aio build complains about missing glib-2.0 in pkg-config search path

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3529]
I've been seeing this when building module/fsdev/aio:

```
1001 Package glib-2.0 was not found in the pkg-config search path.
1002 Perhaps you should add the directory containing `glib-2.0.pc'
1003 to the PKG_CONFIG_PATH environment variable
1004 Package 'glib-2.0', required by 'virtual:world', not found
1005   CC module/fsdev/aio/fsdev_aio.o
1006 Package glib-2.0 was not found in the pkg-config search path.
1007 Perhaps you should add the directory containing `glib-2.0.pc'
1008 to the PKG_CONFIG_PATH environment variable
1009 Package 'glib-2.0', required by 'virtual:world', not found
1010   CC module/fsdev/aio/fsdev_aio_rpc.o
1011 Package glib-2.0 was not found in the pkg-config search path.
1012 Perhaps you should add the directory containing `glib-2.0.pc'
1013 to the PKG_CONFIG_PATH environment variable
1014 Package 'glib-2.0', required by 'virtual:world', not found
1015   CC module/fsdev/aio/linux_aio_mgr.o
```

It's not clear whether these warnings are important or not. I installed the package and ran pkg-config, it just emits some include directories.

I think we need to do one or more of the following:

1) remove these pkg-config lines from the Makefile if they aren't needed
2) add glib-2.0 to various pkgdep scripts to make sure it is installed
3) fail the fsdev/aio module build if the pkg-config fails
4) squash the warning if these flags aren't really required
5) add a comment in the Makefile explaining why these flags are needed

@anton-nayshtut, could you take a look?

Thanks,

Jim

**Comment by anton-nayshtut** [comment]
Sure! Thanks! @jimharris

**Comment by anton-nayshtut** [comment]
It seems to be a remains of some dark past. We don't really need it as far as I understand,

https://review.spdk.io/gerrit/c/spdk/spdk/+/24945 fixes it. Testing it...
