### ISSUE TITLE
[unittest_vhost] vhost test failaure with v24.09-pre 

### ISSUE THREAD

**Issue by nicolas22322** [spdk/spdk#3533]
<Test Log>
 11:11:39 unittest_vhost -- common/autotest_common.sh@1121 -- # /home/spdk/test/unit/lib/vhost/vhost.c/vhost_ut

     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/

Suite: vhost_suite
  Test: desc_to_iov_test ...[2024-09-24 11:11:39.416528] /home/spdk/lib/vhost/rte_vhost_user.c: 620:vhost_vring_desc_payload_to_iov: *ERROR*: SPDK_VHOST_IOVS_MAX(129) reached
passed
  Test: create_controller_test ...[2024-09-24 11:11:39.417000] /home/spdk/lib/vhost/vhost.c:  81:vhost_parse_core_mask: *ERROR*: one of selected cpu is outside of core mask(=f)
[2024-09-24 11:11:39.417021] /home/spdk/lib/vhost/vhost.c: 127:vhost_dev_register: *ERROR*: cpumask 0xf0 is invalid (core mask is 0xf)
[2024-09-24 11:11:39.417030] /home/spdk/lib/vhost/vhost.c:  81:vhost_parse_core_mask: *ERROR*: one of selected cpu is outside of core mask(=f)
[2024-09-24 11:11:39.417038] /home/spdk/lib/vhost/vhost.c: 127:vhost_dev_register: *ERROR*: cpumask 0xff is invalid (core mask is 0xf)
[2024-09-24 11:11:39.417045] /home/spdk/lib/vhost/vhost.c: 121:vhost_dev_register: *ERROR*: Can't register controller with no name
/home/spdk/test/common/autotest_common.sh: line 1096: 259901 Segmentation fault      (core dumped) "$@"
  11:11:39 unittest_vhost -- common/autotest_common.sh@1121 -- # trap - ERR
  11:11:39 unittest_vhost -- common/autotest_common.sh@1121 -- # print_backtrace
  11:11:39 unittest_vhost -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
  11:11:39 unittest_vhost -- common/autotest_common.sh@1151 -- # args=("${BASH_ARGV[@]}")
  11:11:39 unittest_vhost -- common/autotest_common.sh@1151 -- # local args
  11:11:39 unittest_vhost -- common/autotest_common.sh@1153 -- # xtrace_disable
  11:11:39 unittest_vhost -- common/autotest_common.sh@10 -- # set +x
========== Backtrace start: ==========

in /home/spdk/test/common/autotest_common.sh:1121 -> run_test(["unittest_vhost"],["/home/spdk/test/unit/lib/vhost/vhost.c/vhost_ut"])
     ...
   1116         timing_enter $test_name
   1117         echo "************************************"
   1118         echo "START TEST $test_name"
   1119         echo "************************************"
   1120         xtrace_restore
   1121         time "$@"
   1122         xtrace_disable
   1123         echo "************************************"
   1124         echo "END TEST $test_name"
   1125         echo "************************************"
   1126         timing_exit $test_name
     ...
in ./test/unit/unittest.sh:285 -> main([])
     ...
   280  fi
   281  run_test "unittest_thread" $valgrind $testdir/lib/thread/thread.c/thread_ut
   282  run_test "unittest_iobuf" $valgrind $testdir/lib/thread/iobuf.c/iobuf_ut
   283  run_test "unittest_util" unittest_util
   284  if grep -q '#define SPDK_CONFIG_VHOST 1' $rootdir/include/spdk/config.h; then
=> 285          run_test "unittest_vhost" $valgrind $testdir/lib/vhost/vhost.c/vhost_ut
   286  fi
   287  run_test "unittest_dma" $valgrind $testdir/lib/dma/dma.c/dma_ut
   288
   289  run_test "unittest_init" unittest_init
   290  run_test "unittest_keyring" $valgrind "$testdir/lib/keyring/keyring.c/keyring_ut"
     ...

========== Backtrace end ==========
  11:11:39 unittest_vhost -- common/autotest_common.sh@1190 -- # return 0

real    0m0.131s
user    0m0.004s
sys     0m0.011s
[root@localhost spdk]#

<System Info>
[root@localhost ~]# lscpu | grep "Model name"
Model name:          Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz
BIOS Model name:     Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz
[root@localhost ~]#
[root@localhost ~]# uname -r
4.18.0-348.7.1.el8_5.x86_64
[root@localhost ~]#
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 8.5.2111

**Comment by nicolas22322** [comment]
The log looks the same as #3516, but i am using the latest version.

**Comment by mikeBashStuff** [comment]
Are you sure you are using the latest version? Because from the log in the description it's clearly missing the ab79d3827eed3e3abadca164b524cacdb4dbc9ef.  And if it's missing that patch, it definitely is missing the fix targeted for #3516 which is a93a149c51f6811ff221fdd1dfe40ba0cea96f8c.  

Also, it's also advised to attach actual core (or at least the full bt) so it's clear where the crash actually happened. 

Also, also, if by "latest" you actually mean commit that was tagged as 24.09-pre, then you are months behind actual master.

**Comment by nicolas22322** [comment]
I've switched to the master and recomplie, but the problem still happend.
========== Backtrace start: ==========

in ./test/unit/unittest.sh:285 -> main([])
     ...
   280  fi
   281  run_test "unittest_thread" $valgrind $testdir/lib/thread/thread.c/thread_ut
   282  run_test "unittest_iobuf" $valgrind $testdir/lib/thread/iobuf.c/iobuf_ut
   283  run_test "unittest_util" unittest_util
   284  if grep -q '#define SPDK_CONFIG_VHOST 1' $rootdir/include/spdk/config.h; then
=> 285          run_test "unittest_vhost" $valgrind $testdir/lib/vhost/vhost.c/vhost_ut
   286  fi
   287  run_test "unittest_dma" $valgrind $testdir/lib/dma/dma.c/dma_ut
   288
   289  run_test "unittest_init" unittest_init
   290  run_test "unittest_keyring" $valgrind "$testdir/lib/keyring/keyring.c/keyring_ut"
     ...

========== Backtrace end ==========
  01:25:22  -- common/autotest_common.sh@1194 -- # return 0
[root@localhost spdk]# git branch
* master
  origin/master
[root@localhost spdk]#



It looks like the system cannot allocate memory for the pcie devices, i will check the system configuration. Thanks for your reply. @mikeBashStuff


[  308.770726] pcieport 10001:10:00.0: BAR 13: no space for [io  size 0x1000]
[  308.770727] pcieport 10001:10:00.0: BAR 13: failed to assign [io  size 0x1000]
[  334.243734] traps: vhost_ut[7478] general protection fault ip:7f942e6856b7 sp:7ffe9c144b98 error:0 in libc-2.28.so[7f942e528000+1bc000]

**Comment by mikeBashStuff** [comment]
>I've switched to the master and recomplie

But did you update master's HEAD too? You need to also `pull` the latest changes to make sure it's up-to-date (again, from the log above it looks like it's missing patches that I mentioned in my previous comment).

**Comment by nicolas22322** [comment]
Thanks for your reply, i will check... @mikeBashStuff 

I am a green hand on the github :(
