### ISSUE TITLE
Bad ns_visible value after failed spdk_nvmf_subsystem_add_ns_ext

### ISSUE THREAD

**Issue by ArielMarco** [spdk/spdk#3544]
# Sighting report

 In `spdk_nvmf_subsystem_add_ns_ext` if `ns->always_visible` is set, `ns_visible` for ctrlrs is updated quite early in the flow
 If the code later fails, this part is not rolled back
This means a failed add_ns with always_visible will cause a namespace added later to be visible to existing ctrlrs, even if it shouldn't.

## Expected Behavior

The ns should only be visible if it was added successfully

## Current Behavior

Failure in `spdk_nvmf_subsystem_add_ns_ext` can cause the nsid to be visible although the ns doesn't exist. This affects later additions too (by making a non-visible ns visible)

## Possible Solution

Either rollback changes upon error, or do the ns_visible update after the ns is updated

## Steps to Reproduce

1. Create subsystem X
2. Open a controller on host side to X
3. Add namespace in nsid 1 with bad bdev (one that doesn't exist for example) and opts.no_auto_visible == false
4. Add namespace in nsid 1 with good parameters and opts.no_auto_visible == true
5. Attempt to access nsid 1 with the open controller. Should have failed because of opts.no_auto_visible == true and no mapping added, instead it will succeed

## Context (Environment including OS version, SPDK version, etc.)

Not relevant

**Comment by ksztyber** [comment]
[BUg scrub] Seems like a bug. @ksztyber will take  a look.

**Comment by ksztyber** [comment]
This patch should fix the issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/25244/2
