### ISSUE TITLE
[scheduler_opts] scheduler_period doesn't match expected value right after changing the setting

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3546]
# CI Intermittent Failure

The expected value is `424242`, however the get that follows immediately after the set returns `424241`. This is most likely caused by overall time flakiness. 

Point of failure:
```
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@52 -- # rpc_cmd framework_set_scheduler dynamic -p 424242
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@561 -- # xtrace_disable
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@10 -- # set +x
03:41:01  [2024-10-09 03:41:01.099623] scheduler_dynamic.c: 427:set_opts: *NOTICE*: Setting scheduler load limit to 20
03:41:01  [2024-10-09 03:41:01.099661] scheduler_dynamic.c: 429:set_opts: *NOTICE*: Setting scheduler core limit to 80
03:41:01  [2024-10-09 03:41:01.099680] scheduler_dynamic.c: 431:set_opts: *NOTICE*: Setting scheduler core busy to 95
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@589 -- # [[ 0 == 0 ]]
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@53 -- # jq -r '. | select(.scheduler_name == "dynamic") | .scheduler_period'
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@53 -- # rpc_cmd framework_get_scheduler
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@561 -- # xtrace_disable
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@10 -- # set +x
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@589 -- # [[ 0 == 0 ]]
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@53 -- # [[ 424241 -eq 424242 ]]
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@53 -- # trap - ERR
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@53 -- # print_backtrace
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@1155 -- # args=('scheduler_opts' 'scheduler_opts')
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@1155 -- # local args
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@1157 -- # xtrace_disable
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@10 -- # set +x
03:41:01  ========== Backtrace start: ==========
03:41:01  
03:41:01  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/rpc.sh:53 -> scheduler_opts([])
03:41:01       ...
03:41:01     48  		# It should not be possible to change settings that a scheduler does not support
03:41:01     49  		NOT $rpc framework_set_scheduler static --core-limit 42
03:41:01     50  	
03:41:01     51  		# It is possible to change settings generic scheduler opts for schedulers in event framework
03:41:01     52  		$rpc framework_set_scheduler dynamic -p 424242
03:41:01  => 53  		[[ "$($rpc framework_get_scheduler | jq -r '. | select(.scheduler_name == "dynamic") | .scheduler_period')" -eq 424242 ]]
03:41:01     54  	
03:41:01     55  		# Verify that the scheduler is changed and the non-default value is set
03:41:01     56  		$rpc framework_set_scheduler dynamic --core-limit 42
03:41:01     57  		[[ "$($rpc framework_get_scheduler | jq -r '. | select(.scheduler_name == "dynamic") | .core_limit')" -eq 42 ]]
03:41:01     58  	
03:41:01       ...
03:41:01  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:1125 -> run_test(["scheduler_opts"],["scheduler_opts"])
03:41:01       ...
03:41:01     1120		timing_enter $test_name
03:41:01     1121		echo "************************************"
03:41:01     1122		echo "START TEST $test_name"
03:41:01     1123		echo "************************************"
03:41:01     1124		xtrace_restore
03:41:01     1125		time "$@"
03:41:01     1126		xtrace_disable
03:41:01     1127		echo "************************************"
03:41:01     1128		echo "END TEST $test_name"
03:41:01     1129		echo "************************************"
03:41:01     1130		timing_exit $test_name
03:41:01       ...
03:41:01  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/rpc.sh:94 -> main([])
03:41:01       ...
03:41:01     89  	
03:41:01     90  		trap - SIGINT SIGTERM EXIT
03:41:01     91  		killprocess $spdk_pid
03:41:01     92  	}
03:41:01     93  	
03:41:01  => 94  	run_test "scheduler_opts" scheduler_opts
03:41:01     95  	run_test "static_as_default" static_as_default
03:41:01     96  	run_test "framework_get_governor" framework_get_governor
03:41:01       ...
03:41:01  
03:41:01  ========== Backtrace end ==========
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@1194 -- # return 0
03:41:01  
03:41:01  real	0m1.695s
03:41:01  user	0m0.649s
03:41:01  sys	0m0.174s
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@1 -- # killprocess 2396426
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@950 -- # '[' -z 2396426 ']'
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@954 -- # kill -0 2396426
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@955 -- # uname
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@955 -- # '[' Linux = Linux ']'
03:41:01    03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@956 -- # ps --no-headers -o comm= 2396426
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@956 -- # process_name=reactor_1
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@960 -- # '[' reactor_1 = sudo ']'
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@968 -- # echo 'killing process with pid 2396426'
03:41:01  killing process with pid 2396426
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@969 -- # kill 2396426
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- common/autotest_common.sh@974 -- # wait 2396426
03:41:01   03:41:01 scheduler.scheduler_rpc.scheduler_opts -- scheduler/rpc.sh@1 -- # exit 1
03:41:01    03:41:01 scheduler.scheduler_rpc -- common/autotest_common.sh@1125 -- # trap - ERR
03:41:01    03:41:01 scheduler.scheduler_rpc -- common/autotest_common.sh@1125 -- # print_backtrace
03:41:01    03:41:01 scheduler.scheduler_rpc -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
03:41:01    03:41:01 scheduler.scheduler_rpc -- common/autotest_common.sh@1155 -- # args=('/var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/rpc.sh' 'scheduler_rpc')
03:41:01    03:41:01 scheduler.scheduler_rpc -- common/autotest_common.sh@1155 -- # local args
03:41:01    03:41:01 scheduler.scheduler_rpc -- common/autotest_common.sh@1157 -- # xtrace_disable
03:41:01    03:41:01 scheduler.scheduler_rpc -- common/autotest_common.sh@10 -- # set +x
03:41:01  ========== Backtrace start: ==========
03:41:01  
03:41:01  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/common/autotest_common.sh:1125 -> run_test(["scheduler_rpc"],["/var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/rpc.sh"])
03:41:01       ...
03:41:01     1120		timing_enter $test_name
03:41:01     1121		echo "************************************"
03:41:01     1122		echo "START TEST $test_name"
03:41:01     1123		echo "************************************"
03:41:01     1124		xtrace_restore
03:41:01     1125		time "$@"
03:41:01     1126		xtrace_disable
03:41:01     1127		echo "************************************"
03:41:01     1128		echo "END TEST $test_name"
03:41:01     1129		echo "************************************"
03:41:01     1130		timing_exit $test_name
03:41:01       ...
03:41:01  in /var/jenkins/workspace/nvme-phy-autotest/spdk/test/scheduler/scheduler.sh:14 -> main([])
03:41:01       ...
03:41:01     9   	source "$rootdir/test/common/autotest_common.sh"
03:41:01     10  	source "$testdir/isolate_cores.sh"
03:41:01     11  	
03:41:01     12  	"$rootdir/scripts/setup.sh"
03:41:01     13  	
03:41:01  => 14  	run_test "scheduler_rpc" "$testdir/rpc.sh"
03:41:01     15  	run_test "idle" "$testdir/idle.sh"
03:41:01     16  	#run_test "load_balancing" "$testdir/load_balancing.sh"
03:41:01     17  	run_test "dpdk_governor" "$testdir/governor.sh"
03:41:01     18  	run_test "interrupt_mode" "$testdir/interrupt.sh"
03:41:01     19  	run_test "core_isolating" "$testdir/core_isolating.sh"
03:41:01       ...
03:41:01  
03:41:01  ========== Backtrace end ==========
```

https://ci.spdk.io/results/autotest-spdk-master-vs-dpdk-main/builds/3924/archive/nvme-phy-autotest_84577/index.html

**Comment by jimharris** [comment]
scheduler.c converts the user-provided scheduler period from microseconds to ticks, and saves that in a global. Then on the "get" side, it converts it back to microseconds.

So we lose some precision there which is dependent somewhat on the CPU frequency.

This could just pick a smaller value, maybe 4242, and we wouldn't hit this problem. Or alternatively someone can work some bash magic and allow a small amount of wiggle room when checking the value.

**Comment by mikeBashStuff** [comment]
One  thing that makes this a bit peculiar is that it doesn't happen under our submodule (it's impossible to reproduce it), however, under the upstream (vs-dpdk-main) version it pops up almost immediately (under specific platform it's 100% reproducible). 

I could add this wiggle room into the test, but as a user, if I "set" a parameter to a particular value, I expect to "get" it as is, without worrying about some conversion that happens back-and-forth under the hood. I understand that SPDK needs to convert this value to tsc to do the actual scheduling, but shouldn't the `.scheduler_period` be saved and then returned as is? Like, why not to keep the orignal  ms value around? So when something tries to "get" it, there's no need to perform any conversion back from tsc.

**Comment by jimharris** [comment]
> One thing that makes this a bit peculiar is that it doesn't happen under our submodule (it's impossible to reproduce it), however, under the upstream (vs-dpdk-main) version it pops up almost immediately (under specific platform it's 100% reproducible).

Since it's all due to rounding errors, I suspect it's just that certain CPU frequencies cause the rounding error to happen, while others do not.

> I could add this wiggle room into the test, but as a user, if I "set" a parameter to a particular value, I expect to "get" it as is, without worrying about some conversion that happens back-and-forth under the hood. I understand that SPDK needs to convert this value to tsc to do the actual scheduling, but shouldn't the `.scheduler_period` be saved and then returned as is? Like, why not to keep the orignal ms value around? So when something tries to "get" it, there's no need to perform any conversion back from tsc.

Yeah, that's really the better way to handle this. Do you want to push a patch or shall I?

**Comment by jimharris** [comment]
> > One thing that makes this a bit peculiar is that it doesn't happen under our submodule (it's impossible to reproduce it), however, under the upstream (vs-dpdk-main) version it pops up almost immediately (under specific platform it's 100% reproducible).
> 
> Since it's all due to rounding errors, I suspect it's just that certain CPU frequencies cause the rounding error to happen, while others do not.
> 
> > I could add this wiggle room into the test, but as a user, if I "set" a parameter to a particular value, I expect to "get" it as is, without worrying about some conversion that happens back-and-forth under the hood. I understand that SPDK needs to convert this value to tsc to do the actual scheduling, but shouldn't the `.scheduler_period` be saved and then returned as is? Like, why not to keep the orignal ms value around? So when something tries to "get" it, there's no need to perform any conversion back from tsc.
> 
> Yeah, that's really the better way to handle this. Do you want to push a patch or shall I?

I went ahead with a patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/25223

**Comment by mikeBashStuff** [comment]
>  I suspect it's just that certain CPU frequencies cause the rounding error to happen, while others do not.

This does sound sensible, but it doesn't really explain why the rounding issue is 100% reproducible under latest DPDK version while under the submodule it's almost impossible to trigger (and I am testing both under the same system, without manually playing with `cpufreq` or anything).

**Comment by jimharris** [comment]
> > I suspect it's just that certain CPU frequencies cause the rounding error to happen, while others do not.
> 
> This does sound sensible, but it doesn't really explain why the rounding issue is 100% reproducible under latest DPDK version while under the submodule it's almost impossible to trigger (and I am testing both under the same system, without manually playing with `cpufreq` or anything).

I agree, it doesn't make any sense.

The only thing that should affect the rounding would be a difference in the reported CPU frequency. DPDK does support using HPET instead of TSC, but I looked at latest DPDK and didn't see anything obvious that would result in starting to use HPET instead of TSC with latest DPDK. A git bisect is probably the best way to get to the bottom of this if we want true root cause on that difference.

**Comment by mikeBashStuff** [comment]
Ok, this seems to be the culprit https://github.com/DPDK/dpdk/commit/dbdf3d5581caa1de40b5952e41d54b64e39536d1 + https://github.com/DPDK/dpdk/commit/7268f21aa04 which target https://mails.dpdk.org/archives/dev/2022-March/237577.html. 

By following the `get_tsc_freq{,_arch}()` this seems to quirk what `spdk_get_ticks_hz()` returns at the end since extra rounding is being applied along the way (and instead of `2400000000` I get `2394400000` under my system). 

Reverting https://github.com/DPDK/dpdk/commit/dbdf3d5581caa1de40b5952e41d54b64e39536d1 gets rid of the rounding issue on our end, but I am guessing these above changes are somewhat justified.

**Comment by jimharris** [comment]
> Ok, this seems to be the culprit [DPDK/dpdk@dbdf3d5](https://github.com/DPDK/dpdk/commit/dbdf3d5581caa1de40b5952e41d54b64e39536d1) + [DPDK/dpdk@7268f21aa04](https://github.com/DPDK/dpdk/commit/7268f21aa04) which target https://mails.dpdk.org/archives/dev/2022-March/237577.html.
> 
> By following the `get_tsc_freq{,_arch}()` this seems to quirk what `spdk_get_ticks_hz()` returns at the end since extra rounding is being applied along the way (and instead of `2400000000` I get `2394400000` under my system).
> 
> Reverting [DPDK/dpdk@dbdf3d5](https://github.com/DPDK/dpdk/commit/dbdf3d5581caa1de40b5952e41d54b64e39536d1) gets rid of the rounding issue on our end, but I am guessing these above changes are somewhat justified.

Thanks @mikeBashStuff. That definitely explains all of it.

https://review.spdk.io/gerrit/c/spdk/spdk/+/25223 should fix this issue on our end. It just needs another +2 and then we can merge it.

**Comment by mikeBashStuff** [comment]
Patches merged, closing.
