### ISSUE TITLE
NVMf: Arbitration support

### ISSUE THREAD

**Issue by PepperJo** [spdk/spdk#355]
Provide arbitration support like weighted round robin for the NVMf target. My undestanding is that this is not straight forward to do in SPDK since there is no 1:1 relation between a bdev nvme queue and a NVMf connection. We would need to introduce priorities in the bdev abstraction.

**Comment by jimharris** [comment]
Just a thought - what if this was implemented solely in the NVMe-oF target?  Then it would work with any bdev - not just bdevs that are namespaces on a WRR-enabled NVMe SSD.

**Comment by dverkamp-intel** [comment]
It should be possible to implement this in the NVMe-oF target in a generic way, but I believe it would require message-passing all I/O for a given controller to a single thread so that it could apply the weighted round robin policy as required by the NVMe specification.

**Comment by jimharris** [comment]
True.  But I think we'll have similar problems if we try to plumb this through the bdev layer.

**Comment by dverkamp-intel** [comment]
Yes, I didn't mean to imply that we should try to plumb this through the bdev layer to use native NVMe WRR somehow; I don't think that is possible with our current NVMe-oF target design.

Also, I think simple per-bdev-io priorities would not be sufficient to emulate WRR in a way that matches the requirements laid out in the NVMe specification, such as the arbitration burst and user-specified weights configured via Set Features (this is all described in section 4.11 and its subsections in NVMe 1.3c, as well as section 5.21.1.1 on Set Features - Arbitration).

**Comment by PepperJo** [comment]
I agree I don't think we can emulate WRR in software. Once one hardware queue is filled to a certain level you would block urgent request behind the already pending requests. We need to enable native WRR in the block layer. One approach could be similar to this: https://www.usenix.org/sites/default/files/conference/protected-files/hotstorage17_slides_joshi.pdf

**Comment by jimharris** [comment]
Closing this issue.  This enhancement will be tracked by Trello card https://trello.com/c/h9LS6VaH/33-arbitration-ie-wrr.  It has a link back to this GitHub issue for the discussion started here.
