### ISSUE TITLE
SPDK v24.09 NVMe-oF TCP interrupt mode does not work

### ISSUE THREAD

**Issue by jumpapex** [spdk/spdk#3552]
# Sighting report

Test SPDK v24.09, run nvmf_tgt in interrupt mode, but the cpu usage of 'reactor' goes to 100%

## Expected Behavior

run nvmf_tgt in interrupt mode, the cpu usage of reactor shoud be at a low level, e.g. < 5% 

## Current Behavior

run nvmf_tgt in interrupt mode, but the cpu usage of 'reactor' goes to 100%

## Possible Solution

N/A
## Steps to Reproduce

1. git clone the SPDK code with version v24.09(b18e1bd62), configure and make
2. run scripts/setup.sh && build/bin/nvmf_tgt --interrupt-mode
3. following guide "Configuring the SPDK NVMe over Fabrics Target", run:
   scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
   scripts/rpc.py bdev_malloc_create -b Malloc0 512 512
   scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
   **_till now, the cpu usage of reactor is about 1~2% or lower_**
   scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
   **after adding namespace, the cpu usage of 'reactor' goes to 100%**
## Context (Environment including OS version, SPDK version, etc.)
OS: Rocky Linux 8.10, 
SPDK version: v24.09(b18e1bd62)

**Comment by jimharris** [comment]
The malloc bdev does not support interrupt mode. Please try the aio bdev module.

**Comment by jumpapex** [comment]
You are right. I test with aio bdev, the cpu usage will not go to 100%.

Thanks! @jimharris
