### ISSUE TITLE
nvme_pcie_common.c: 936:nvme_pcie_qpair_process_completions: *ERROR*: cpl does not map to outstanding cmd

### ISSUE THREAD

**Issue by WenhaoYuan604** [spdk/spdk#3557]
# Sighting report
I am building a database using SPDK.

In this system, I created two qpairs and used two secondary processes to submit NVMe tasks to these two qpairs respectively. 

Then, I used another secondary processes  to execute spdk_nvme_qpair_process_completions on both qpairs to obtain the execution results.

## Expected Behavior
C should get results from two qpairs.

## Current Behavior
At first, C was able to execute spdk_nvme_qpair_process_completions successfully to obtain results.

However, after processing approximately tens of thousands of requests, errors began to occur:

nvme_pcie_common.c: 936:nvme_pcie_qpair_process_completions: *ERROR*: cpl does not map to outstanding cmd.

## Steps to Reproduce

1.Two qpairs on one namespace  

2.Two secondary processes submit NVMe tasks to  two qpairs respectively. 

3.Another secondary processes  execute spdk_nvme_qpair_process_completions on both qpairs to obtain the execution results.

## Context (Environment including OS version, SPDK version, etc.)
OS:Linux  5.4.0-196-generic
 
SPDK：v23.05

**Comment by jimharris** [comment]
It sounds like you are submitting I/O to a qpair from one process, and checking for completions on that qpair from a different process.

If that is correct, you must do your own synchronization (i.e. process-shared mutex) at a higher level. NVMe io qpairs are designed to only be accessed (submit requests and check for completions) from a single pthread.

**Comment by jimharris** [comment]
[Bug scrub] Closing this issue, based on recommendation provided on Oct 21. @WenhaoYuan604, please re-open or ask additional questions here if necessary.
