### ISSUE TITLE
blob: inconsistant error handling behaviour in spdk_bs_destroy and spdk_bs_unload

### ISSUE THREAD

**Issue by nickyc975** [spdk/spdk#3560]
# Sighting report

`spdk_bs_unload` and `spdk_bs_destroy` may fail in 2 stages:

1. Just in the function call, before any callback;
2. In one of the callbacks, for example, in `bs_unload_read_super_cpl` for `spdk_bs_unload`;

If they fail in stage 1, nothing would happen to the bs. But if they fail in stage 2, the bs would be freed.

Here is the problem. Outside users can only get an error code in the callbacks on failure. They cannot differ the 2 cases based on the error code. Therefore, they can never handle the bs correctly after the callback: keeping the bs pointer may cause segment fault, while dropping the bs pointer may lead to resource leak.

## Expected Behavior

`spdk_bs_unload` and `spdk_bs_destroy` should provide consistant error handling. For example, non-zero error code always means bs is still available, while zero always means bs is freed.

## Current Behavior

When getting non-zero error code in callbacks, users have no idea about whether the bs is still available.

## Possible Solution

1. Do not free the bs once there are errors;
2. If bs can be freed (i.e., no open blobs etc.), just free it. If there are errors, only print logs. Then pass zero error code to user callbacks.

**Comment by changpe1** [comment]
@nickyc975 do you want to submit a patch for your proposal ?

**Comment by nickyc975** [comment]
> @nickyc975 do you want to submit a patch for your proposal ?

I am glad to! But which solution do you think is better? I prefer the second one, i.e., free bs if possible and print logs for errors.

**Comment by changpe1** [comment]
> > @nickyc975 do you want to submit a patch for your proposal ?
> 
> I am glad to! But which solution do you think is better? I prefer the second one, i.e., free bs if possible and print logs for errors.

I don't think we should pass zero code to user callbacks for error case, but you can print an error log for this case, and not use bs anymore after the error callback.

**Comment by nickyc975** [comment]
Any updates on this issue? Shall I submit a patch?

**Comment by jimharris** [comment]
> Any updates on this issue? Shall I submit a patch?

I haven't had time to look at this. So if you could submit a patch that would be great.

**Comment by nickyc975** [comment]
Patches out for review:
https://review.spdk.io/gerrit/c/spdk/spdk/+/25470
https://review.spdk.io/gerrit/c/spdk/spdk/+/25471
https://review.spdk.io/gerrit/c/spdk/spdk/+/25472

**Comment by jimharris** [comment]
> https://review.spdk.io/gerrit/c/spdk/spdk/+/25470

Thanks @nickyc975. These patches look good to me. They just need another +2 and then we will merge them.
