### ISSUE TITLE
blockdev.sh setup_xnvme_conf() should be extended to test io_uring_cmd and aio mechanisms

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3561]
Currently blockdev.sh only tests io_uring mechanism. There's a TODO there to add support for io_uring_cmd. While here, it should test aio as well (aio through xnvme).

Adding this issue to track this work. Assigning to @karlowich for now.

**Comment by mikeBashStuff** [comment]
Just to note that there's already a separate, small suite dedicated to `xnvme` which uses both, the `libaio` and `io_uring` mechanisms (`test/nvme/xnvme/xnvme.sh`) - `io_uring_cmd` is not there for the similar reason mentioned in the `blockdev.sh` (i.e. it doesn't seem to work even under our latest setups).

**Comment by karlowich** [comment]
@mikeBashStuff Should we drop this issue?

**Comment by mikeBashStuff** [comment]
@karlowich I guess we could just change the scope a bit, to make sure we test the `io_uring_cmd` as well (as that piece is indeed missing).

**Comment by karlowich** [comment]
@mikeBashStuff Okay, let's try to extend `test/nvme/xnvme/xnvme.sh` with `io_uring_cmd`
