### ISSUE TITLE
nvmf: ctrlr admin cmds can be issued passthru to drive if NSID is set.

### ISSUE THREAD

**Issue by pawel-baldysiak-dell** [spdk/spdk#3564]
Current implementation in nvmf is not comply with nvme spec 1.3d

According to NVMe spec rev1.3d, Section4, Figure12:
If admin cmd is not using NSID field - host should set it to 0h.
Otherwise - such command should be returned with
INVALID FIELD IN COMMAND error.

With recent change that added passthrough command caps
to nvmf - SPDK engine is forwarding all admin commands
with NSID set to the bdev - even the incorrectly formed ones.
For example - commit firmware with NSID set to 1.

I posted a fix for this - it is currently under review: https://review.spdk.io/gerrit/c/spdk/spdk/+/25151

Thanks
Pawel

**Comment by jimharris** [comment]
Closing, patches merged. Thanks!
