### ISSUE TITLE
RAID bdev recreate causes SPDK to exit with segfault

### ISSUE THREAD

**Issue by TheSSDGuy** [spdk/spdk#3565]
# Sighting report

Re-creating a RAID bdev from two existing base bdevs previously marked with RAID super block, causes SPDK to crash with a segfault.

## Expected Behavior

Expected behavior is that re-create works as a standard create process i.e., superblock is checked and then if everything is aligned proceed with the creation of the raid bdev. 

## Steps to Reproduce

```
bdev_malloc_create -b drive0 512 4096
bdev_malloc_create -b drive1 512 4096
bdev_raid_create -n mir0 -r raid1 -b "drive0 drive1" -s --uuid fffd82df-c882-4fe5-bebc-9e05c01fad00
bdev_raid_delete mir0
bdev_raid_create -n mir0 -r raid1 -b "drive0 drive1" -s --uuid fffd82df-c882-4fe5-bebc-9e05c01fad00
SPDK exits with segfault
```

## Possible Enhancement (if not already covered by the solution of the above issue)
Allow to force the recreation step even if the two base devices are swapped in position.
E.g.: if RAID was created with base bdevs "drive0" and "drive1", allow to recreate also with "drive1" and "drive0".

## Context (Environment including OS version, SPDK version, etc.)
SPDK: v24.09
OS: ubuntu 22.04
Kernel: 6.5.0-1024

**Comment by YankunLi** [comment]
This patch（ https://review.spdk.io/gerrit/c/spdk/spdk/+/25375 ） fixes the problem and passes the test, but does not allow raid creation based on base bdev with superblock.  
This issue #3562  allows raid creation on base bdev on superblock.

**Comment by YankunLi** [comment]
Hi, @jimharris , this can be turned off.

**Comment by jimharris** [comment]
@TheSSDGuy, can we close this based on comment from @YankunLi?
