### ISSUE TITLE
Why the NVMe Instance does not support  flush in  vbdev_lvol?

### ISSUE THREAD

**Issue by jyc-001** [spdk/spdk#3572]
# Sighting report
An error is reported when GuestOS transfers a sync io to Nvme disk through SPDK. The reason for the error is vbdev_lvol_submit_request() not support  SPDK_BDEV_IO_TYPE_FLUSH. 

vbdev_lvol_submit_request() has correlation logic in spdk v17.07.x version. It's deleted by the commit [https://github.com/spdk/spdk/commit/793284730050beda15352d75dd284a811d6535f5](url)
``
## Current Behavior
![image](https://github.com/user-attachments/assets/a1c76a7b-762e-4434-8c89-82f860e91a96)

## Possible Solution
recover spdk_bs_io_flush_channel() and call nvme fun about flush.
Or vbdev_lvol_submit_request return ok so that the I/O does not report an error to the guest OS.

## Steps to Reproduce
1.create a storage pool and disk
`python vhost_rpc  construct_lvol_store Nvme0n1 sen_test
 python vhost_rpc  construct_lvol_bdev -l sen_test lun1 10240
`
2.start GuesetOs and use lun1 by blk， run the sync io command.
```
echo "write back" > /sys/block/vda/queue/write_cache
dd if=/dev/zero of=/dev/vda oflag=sync conv=fsync bs=512b count=1
```

## Context (Environment including OS version, SPDK version, etc.)
GuestOs  linux 4.18
HostOs   linux 4.18
spdk version  22.01x

**Comment by changpe1** [comment]
@jyc-001 I think there are several issues here:
1) SPDK vhost doesn't support WCE nor FLUSH feature, so in theory we should not receive any FLUSH command in vhost.
2) As we already hit the flush progress in SPDK, we can return `VIRTIO_BLK_S_UNSUPP` for these commands, but will need the bdev layer to add a new IO error type for this case.

would you like to submit a patch for that? Or I can help to improve it.

**Comment by jimharris** [comment]
[Bug scrub] Closing this issue since the patch is merged.

Adding flush to lvol layer would be easy to add, if the flush is for the whole device. But it's not clear this is needed after Changpeng's patch.

@jyc-001, please re-open this issue if you still see problems after Changpeng's patch.
