### ISSUE TITLE
nvme_tcp: the CPU core where app_thread is located may be blocked due to TCP socket connect timeout.

### ISSUE THREAD

**Issue by ygtzf** [spdk/spdk#3578]
# Sighting report

In the NVMe over TCP environment, during the restart of the NVMf target node, all NVMe controllers on the Vhost will have a keep alive timeout and will be disconnected, including the normal nvme bdevs of the NVMf target.

We found that app_thread was in a blocked state and keep alive could not be sent normally. The blocking time was about 8s, 16s, etc., and we saw the log of posix socket connect timeout at this time. Because the nvme ctrlr is trying to reset controller.
`posix.c:1032:posix_sock_create: *ERROR*: connect() failed, errno = 110`

We noticed the parameter transport_ack_timeout, and the TCP ack_timeout is set in nvme_tcp to `opts.ack_timeout = 1ULL << ctrlr->opts.transport_ack_timeout`, the default value of  transport_ack_timeout is 0, 0 means using the Linux default TCP timeout parameter of 120s. we set it to 12, and the opts.ack_timeout is 4096ms. 

Each nvme ctrlr has an admin qpair and an io qpair, so there are two connections in progress. And there are 4 nvme ctrlr on our vhost, all of them are in resetting state.This causes the normal nvme ctrlr to have a keep alive timeout and also reset the controller. 

Finally, all nvme ctrlr IO on vhost are hung.

## Expected Behavior
The resetting process of nvme ctrlr should not affect other ctrlr.

## Current Behavior
The resetting process of nvme ctrlr affects the IO of other ctrlr.

## Possible Solution
May be like below：
1. Lower the transport_ack_timeout parameter value, but if it is too low, it may affect normal socket communication.
2. Connect is changed to asynchronous operation, and the code structure needs to be changed a lot.
3. Add a ping check before connecting. This ping check can set a very low timeout to avoid direct connection.  **I tend to this.**

## Steps to Reproduce

1. start two NVMf TCP target A and B on different node, create transport and listen a port
2. start vhost, attach  two nvme controller from A and B, and run fio
3. shutdown target A node
4. the NVMe B controller maybe IO hang

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: v24.01

**Comment by jimharris** [comment]
There's an open issue/enhancement for async connect: https://github.com/spdk/spdk/issues/2062.

It needs someone to continue the work on the proposed patch. That patch is quite old, it probably needs quite of rebasing, but would be a good start.

**Comment by jimharris** [comment]
> @jimharris Is anyone working on this patch? The patch seems to take quite some time to complete. We plan to add a ping probe before connect to solve the problem in our production environment.

No one is working on this patch. It has been sitting there for a very long time.
