### ISSUE TITLE
Cannot add nvme disk to spdk_tgt if run with -g parameter

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#358]
## Expected Behavior
Can add disk to spdk_tgt normally.

## Current Behavior
Get following error:
EAL:   cannot set up DMA remapping, error 22 (Invalid argument)
EAL:   0000:08:00.0 DMA remapping failed, error 22 (Invalid argument)
EAL: Driver cannot attach the device (0000:08:00.0)
bdev_nvme.c:1059:spdk_bdev_nvme_create: *ERROR*: Failed to find new NVMe controller

## Possible Solution
None

## Steps to Reproduce
1. Run vhost: ./app/spdk_tgt/spdk_tgt -s 1024 -g
2. Run command: ./scripts/rpc.py construct_nvme_bdev -t PCIe -a 0000:08:00.0 -b Nvme0

## Context (Environment including OS version, SPDK version, etc.)
Host with ubunutu 16.04 and with vfio enabled.

**Comment by darsto** [comment]
Could you check this patch?
https://review.gerrithub.io/c/spdk/dpdk/+/418073
D.

**Comment by liang2yan** [comment]
@WenqianZong also verified this issue with Darek's patch. This patch can fix this issue.

**Comment by liang2yan** [comment]
patch merged. So close this issue.
