### ISSUE TITLE
Failed to create lots of bdevs

### ISSUE THREAD

**Issue by wauxhall** [spdk/spdk#3584]
# Sighting report

I tried to create 512 bdevs for iscsi-target and after some bdev_create request it failed with error:

`RPC method: encode and send request: write unix @->/var/tmp/spdk.sock: use of closed network connection`

## Expected Behavior

Able to create lots of bdevs

## Current Behavior

For some reason, RPC sock is closed after N request.

## Steps to Reproduce

1. Create one portal and initiator groups
2. Create some bdev, e.g. malloc via bdev_malloc_create
3. Create iscsi tgt node (one per bdev)
4. Repeat steps 2 and 3 for 512 times. I did it asynchronously.

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 22.04, SPDK v24.09, local machine

**Comment by jimharris** [comment]
Hi,

Please share more details about how you did it asynchronously. This will make it easier for someone to reproduce and possibly root cause the issue.

Thanks,

Jim

**Comment by wauxhall** [comment]
Hi,

I did it via golang: created 512 goroutines in a loop, in each sent bdev_create and iscsi_create_target_node RPC requests.

So in another words, I had a function, which calls synchronously 2 RPCs: for creating bdev and then creating tgt node. And this function I called asynchronously in a separate goroutine.

**Comment by jimharris** [comment]
> Hi,
> 
> I did it via golang: created 512 goroutines in a loop, in each sent bdev_create and iscsi_create_target_node RPC requests.
> 
> So in another words, I had a function, which calls synchronously 2 RPCs: for creating bdev and then creating tgt node. And this function I called asynchronously in a separate goroutine.

Does this create a separate connection for every pair of RPC requests? Or are they all sent on the same on the same connection?

Posting a reproduction vehicle will be more likely to get someone to take a look at this issue.

-Jim

**Comment by wauxhall** [comment]
> > Hi,
> > I did it via golang: created 512 goroutines in a loop, in each sent bdev_create and iscsi_create_target_node RPC requests.
> > So in another words, I had a function, which calls synchronously 2 RPCs: for creating bdev and then creating tgt node. And this function I called asynchronously in a separate goroutine.
> 
> Does this create a separate connection for every pair of RPC requests? Or are they all sent on the same on the same connection?
> 
> Posting a reproduction vehicle will be more likely to get someone to take a look at this issue.
> 
> -Jim

It's the same connection

**Comment by jimharris** [comment]
@wauxhall can you share how this issue was resolved?

**Comment by wauxhall** [comment]
> @wauxhall can you share how this issue was resolved?

Sure, my bad, it appeared there was 2 bdevs creating at a time per iteration, I didn't notice that at first, I removed unnecessary bdev creations so only one bdev created per iteration and everything worked fine
