### ISSUE TITLE
make spdk/nvme-cli tests configurable in autotest.sh

### ISSUE THREAD

**Issue by johnmeneghini** [spdk/spdk#361]
The https://github.com/spdk/nvme-cli fork contains a series of patches in the default spdk branch that are specific to spdk.  This is a request to make the SPDK autotest.sh that tests this fork configurable.   

See: https://lists.01.org/pipermail/spdk/2018-July/002168.html

## Expected Behavior

autotest.sh only runs tests configured by ~/autorun-spdk.conf

## Current Behavior

~/autorun-spdk.conf does not disable the nvme-cli test

## Possible Solution

Add an SPDK_TEST_NVME_CLI autotest config parameter to disable testing of the SPDK nvme-cli fork.

## Context (Environment including OS version, SPDK version, etc.)

SPDK master branch

**Comment by dverkamp-intel** [comment]
Please try this patch: https://review.gerrithub.io/#/c/spdk/spdk/+/418866/

**Comment by liang2yan** [comment]
@johnmeneghini , Daniel's patch already merged. Can we close this issue?
