### ISSUE TITLE
Memory leak when running tests for spdk/nvme-cli

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#366]
Sorry for reporting this here but we don't have an issue board for spdk/nvme-cli

## Current Behavior
ASAN mem leak.

## Steps to Reproduce
> 1. Checkout spdk/nvme-cli and switch to spdk branch (commit ID c78cc41;  Merge "nvme-cli/spdk: add the support for the show-regs command" into spdk)
> 2. Checkout spdk/spdk (7c57c0f nvme: show command manual completion)
> 3. Build SPDK with rdma option and asan enabled.
> 4. Build nvme-cli
> 5. Run autotest.sh with options SPDK_TEST_NVMF=1 SPDK_RUN_ASAN=1, should fail due to ASAN detecting mem leak
> 5. Run autotest.sh with options SPDK_TEST_NVME=1 SPDK_RUN_ASAN=1, should fail due to ASAN detecting mem leak

NVMeOF test asan log:

>  01:45:47	# ./nvme discover -t rdma -a 10.102.17.183 -s 4420
> Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
> [ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
> EAL: Detected 16 lcore(s)
> EAL: Auto-detected process type: SECONDARY
> EAL: Multi-process socket /var/run/.spdk0_unix_27623_4f0a2ec2c6d
> EAL: Probing VFIO support...
> EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
> 
> =================================================================
> ==27623==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 2048 byte(s) in 1 object(s) allocated from:
>     #0 0x7ffff6efca38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
>     #1 0x45060e in nvmf_get_log_page_discovery /home/sys_sgsw/nvme-cli/fabrics.c:318
>     #2 0x45060e in do_discover /home/sys_sgsw/nvme-cli/fabrics.c:708
>     #3 0x7fffffffd09f  (<unknown module>)
> 
> SUMMARY: AddressSanitizer: 2048 byte(s) leaked in 1 allocation(s).

NVMe test asan log:

>  22:35:46	# ./nvme list-ctrl 0000:00:06.0
> Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
> [ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
> EAL: Detected 16 lcore(s)
> EAL: Auto-detected process type: SECONDARY
> EAL: Multi-process socket /var/run/.spdk0_unix_13484_6db02bf51d3
> EAL: Probing VFIO support...
> EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
> EAL: PCI device 0000:00:06.0 on NUMA socket 0
> EAL:   probe driver: 8086:5845 spdk_nvme
> nvme_qpair.c: 112:nvme_admin_qpair_print_command: *NOTICE*: IDENTIFY (06) sqid:0 cid:95 nsid:0 cdw10:00000013 cdw11:00000000
> nvme_qpair.c: 294:nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:0 cid:95 cdw0:0 sqhd:0014 p:1 m:0 dnr:1
> command error: SC 2 SCT 0
> NVMe Status:INVALID_FIELD(2) cntid:0
> 
> =================================================================
> ==13484==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 4096 byte(s) in 1 object(s) allocated from:
>     #0 0x7ffff6efd4a0 in posix_memalign (/lib64/libasan.so.4+0xdf4a0)
>     #1 0x41e145 in list_ctrl /home/sys_sgsw/nvme-cli/nvme.c:521
> 
> SUMMARY: AddressSanitizer: 4096 byte(s) leaked in 1 allocation(s).

Notes:
- Used a Fedora26 VM with emulated NVMe and SoftROCE instead of a physical system.

**Comment by WenqianZong** [comment]
@karlatec 
I found NVMeOF test asan error with latest spdk：
```
=================================================================
==120437==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2048 byte(s) in 1 object(s) allocated from:
    #0 0x7fbed4852d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x555f5a31aa46 in nvmf_get_log_page_discovery /home/zong/nvme-cli/fabrics.c:318
    #2 0x555f5a31aa46 in do_discover /home/zong/nvme-cli/fabrics.c:708

SUMMARY: AddressSanitizer: 2048 byte(s) leaked in 1 allocation(s).
```
Only "nvme discovery" cause error, "nvme connect" "nvme disconnect" can't.
But command "./nvme list-ctrl 0000:af:00.0" can not be use : 
```
0000:af:00.0: No such file or directory
Usage: nvme list-ctrl <device> [OPTIONS]

Show controller list information for the subsystem the given device is part
of, or optionally controllers attached to a specific namespace.

Options:
  [  --cntid=<NUM>, -c <NUM> ]          --- controller to display
  [  --namespace-id=<NUM>, -n <NUM> ]   --- optional namespace attached to
                                            controller
```
Could you provide test step?

**Comment by jimharris** [comment]
@Comphix - can you take a look at this?  Looks like some fairly straightforward fixes we can make to clear these up.

**Comment by wanqunintel** [comment]
@Comphix would you look at this issue?

**Comment by Comphix** [comment]
Had a quick patch at https://review.gerrithub.io/c/spdk/nvme-cli/+/421504

Please help to validate whether the below issue has been fixed:
Direct leak of 2048 byte(s) in 1 object(s) allocated from:
    #0 0x7fbed4852d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x555f5a31aa46 in nvmf_get_log_page_discovery /home/zong/nvme-cli/fabrics.c:318
    #2 0x555f5a31aa46 in do_discover /home/zong/nvme-cli/fabrics.c:708

If there is other issue, please also leave the note and let me know. Thanks.

**Comment by xuhuagen** [comment]
@Comphix I patched  https://review.gerrithub.io/c/spdk/nvme-cli/+/421504, issue
```
Direct leak of 2048 byte(s) in 1 object(s) allocated from:
#0 0x7fbed4852d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
#1 0x555f5a31aa46 in nvmf_get_log_page_discovery /home/zong/nvme-cli/fabrics.c:318
#2 0x555f5a31aa46 in do_discover /home/zong/nvme-cli/fabrics.c:708
```
has been fixed.

**Comment by Comphix** [comment]
Thanks Huagen!

**Comment by WenqianZong** [comment]
@Comphix I pull patch https://review.gerrithub.io/c/spdk/nvme-cli/+/421504 and test discovery and connect can not reporoduced.
