### ISSUE TITLE
Can run fio_plugin with asan enabled. But get memory leaks in fio

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#368]
## Expected Behavior
Can run fio_plugin

## Current Behavior
fio_plugin reports:
==38092==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

## Possible Solution
None

## Steps to Reproduce
1. Configure spdk with asan enabled
2. Run vhost and create blk controller with path /var/tmp/naa.Nvme0n1p0.0 and nvme bdev
3. Create config bdev.conf:
[VirtioUser0]
  Path /var/tmp/naa.Nvme0n1p0.0
  Type Blk
4. Create bdev.fio config file:
[job_VirtioBlk0]
filename=VirtioBlk0
5. Run fio:
LD_PRELOAD=[path to fio_plugin] /usr/src/fio/fio --ioengine=spdk_bdev --iodepth=8 --bs=4k --runtime=5 [path to bdev.fio] --spdk_conf=[path to bdev.conf]

## Context (Environment including OS version, SPDK version, etc.)
VM with Ubuntu 16.04.

**Comment by darsto** [comment]
> ==38092==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

The following works:

sudo LD_PRELOAD="$(ldd /path/fio_plugin | grep libasan | awk '{print $3}'):/path/fio_plugin" /path/fio /path/job.fio --ioengine=spdk_bdev --iodepth=128 --bs=4k --runtime=5 --spdk_conf=/path/spdk.conf --spdk_mem=512

Other issue is that ASAN detects a couple of memory leaks in fio 3.3..

**Comment by liang2yan** [comment]
@pawelkax , so the memory leak is in the fio repo source codes, not spdk related codes?

**Comment by pawelkax** [comment]
@liang2yan Yes, memory leaks are in fio repo.

**Comment by liang2yan** [comment]
Close this issue since the memory leak are from fio.
