### ISSUE TITLE
EAL: Not enough memory available to run FIO - Unable to initialize SPDK env

### ISSUE THREAD

**Issue by dwy189** [spdk/spdk#373]
I was running fio command to benchmark the NVMe devices. But I ran into the "not enough memory issue". Below is the summary message I got from the terminal. 

LD_PRELOAD=/home/weiyoud/spdk/examples/nvme/fio_plugin/fio_plugin fio example_config.fio 
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=8
fio-3.3
Starting 1 thread
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid3926 ]
EAL: Detected 1 lcore(s)
EAL: Multi-process socket /home/weiyoud/.spdk_pid3926_unix
EAL: Probing VFIO support...
EAL: Cannot obtain physical addresses: No such file or directory. Only vfio will function.
EAL: Not enough memory available! Requested: 512MB, available: 0MB
EAL: FATAL: Cannot init memory

EAL: Cannot init memory

Failed to initialize DPDK
fio_plugin.c: 305:spdk_fio_setup: *ERROR*: Unable to initialize SPDK env

Run status group 0 (all jobs):

Here is my example_config.fio: 
[global]
ioengine=/home/weiyoud/spdk/examples/nvme/fio_plugin/fio_plugin
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0
runtime=2
iodepth=8
rw=randrw
bs=4k

[test]
numjobs=1
size=4m

And here is my memory information after running "cat /proc/meminfo":
MemTotal:       10288416 kB
MemFree:         6570712 kB
MemAvailable:    6945312 kB
Buffers:           34712 kB
Cached:           585476 kB
SwapCached:            0 kB
Active:          1095792 kB
Inactive:         378716 kB
Active(anon):     855184 kB
Inactive(anon):    34812 kB
Active(file):     240608 kB
Inactive(file):   343904 kB
Unevictable:          48 kB
Mlocked:              48 kB
SwapTotal:       4828156 kB
SwapFree:        4828156 kB
Dirty:                44 kB
Writeback:             0 kB
AnonPages:        854384 kB
Mapped:           303392 kB
Shmem:             35672 kB
Slab:              59380 kB
SReclaimable:      35516 kB
SUnreclaim:        23864 kB
KernelStack:        7232 kB
PageTables:        31192 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8923788 kB
Committed_AS:    4358888 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:    1024
HugePages_Free:     1024
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       83904 kB
DirectMap2M:    10459136 kB

## Expected Behavior

The fio command should run without such an issue. 

## Current Behavior

Not enough memory to run fio. It was not able to initialize SPDK env. It requested 512MB memory but it has 0MB available. I thought I have enough memory. I ran "sudo HUGEPAGE=1024 /scripts/setup.sh" at the beginning.  

## Possible Solution

This seems to be a configuration issue but I could not find out a solution. Please investigate and advise. Thanks in advance!

**Comment by jimharris** [comment]
Hi @dwy189,

Can you confirm that you are running fio as root?

Thanks,

-Jim

**Comment by dwy189** [comment]
After adding "sudo" at the beginning of the command, I was able to solve this problem. Thank you so much.
