### ISSUE TITLE
Segmentation Error when running fio plugin with numjob=8

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#376]
When running the fio plugin with parameter numjob=8 I get a segmentation fault error. The run seems to be going fine and the read IOPS are getting update but when the run completes I get a segmentation fault error. 

I change the parameter to numjob=1 the fio job runs successfully. I also successfully ran numjob=2 and numjob=4. 
I have increased the total Hugepages from 2 GB to 8 GB but that did not resolve the issue. The size of a hugepage in my system is 1 GB.

## Expected Behavior
The numjob parameter scales the number of fio threads submitting I/Os.  For example, running fio with a configuration of numjob=1 starts 1 thread to run the I/O workload. This test ran successfully.

LD_PRELOAD=/home/john/spdk/new/spdk/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
fio-3.3
Starting 1 thread
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid90232 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid90232_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Jobs: 1 (f=0): [f(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
SR_128K_QD256: (groupid=0, jobs=1): err= 0: pid=90349: Thu Jul 26 08:29:22 2018
   read: IOPS=22.6k, BW=2831MiB/s (2968MB/s)(166GiB/60015msec)
    slat (nsec): min=68, max=15920, avg=83.30, stdev=32.50
    clat (usec): min=2938, max=30453, avg=11304.26, stdev=4742.83
     lat (usec): min=2938, max=30453, avg=11304.34, stdev=4742.83
    clat percentiles (usec):
     |  1.00th=[ 3752],  5.00th=[ 4293], 10.00th=[ 5014], 20.00th=[ 6390],
     | 30.00th=[ 7898], 40.00th=[ 9634], 50.00th=[11338], 60.00th=[12911],
     | 70.00th=[14222], 80.00th=[15664], 90.00th=[17433], 95.00th=[19006],
     | 99.00th=[22152], 99.50th=[23462], 99.90th=[26346], 99.95th=[27132],
     | 99.99th=[28705]
   bw (  MiB/s): min= 2768, max= 2887, per=100.00%, avg=2844.86, stdev=26.01, samples=120
   iops        : min=22146, max=23098, avg=22758.49, stdev=208.03, samples=120
  lat (msec)   : 4=2.56%, 10=39.94%, 20=54.51%, 50=3.01%
  cpu          : usr=99.81%, sys=0.00%, ctx=15, majf=0, minf=220
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=116.6%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=1358926,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
   READ: bw=2831MiB/s (2968MB/s), 2831MiB/s-2831MiB/s (2968MB/s-2968MB/s), io=166GiB (178GB), run=60015-60015msec

Running fio with numjob=2 starts 2 thread to run the I/O workload. This test ran successfully.
   
LD_PRELOAD=/home/john/spdk/new/spdk/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
...
fio-3.3
Starting 2 threads
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid90515 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid90515_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Jobs: 1 (f=0): [f(1),_(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
SR_128K_QD256: (groupid=0, jobs=2): err= 0: pid=90632: Thu Jul 26 08:33:48 2018
   read: IOPS=24.4k, BW=3052MiB/s (3200MB/s)(179GiB/60023msec)
    slat (nsec): min=68, max=15775, avg=75.14, stdev=33.45
    clat (usec): min=10513, max=47068, avg=20971.94, stdev=4860.23
     lat (usec): min=10513, max=47068, avg=20972.01, stdev=4860.23
    clat percentiles (usec):
     |  1.00th=[12256],  5.00th=[13304], 10.00th=[14222], 20.00th=[16319],
     | 30.00th=[17957], 40.00th=[19530], 50.00th=[20841], 60.00th=[22152],
     | 70.00th=[23725], 80.00th=[25560], 90.00th=[27657], 95.00th=[28967],
     | 99.00th=[31327], 99.50th=[32375], 99.90th=[34341], 99.95th=[35390],
     | 99.99th=[38536]
   bw (  MiB/s): min= 1486, max= 1573, per=50.33%, avg=1536.04, stdev=17.23, samples=240
   iops        : min=11891, max=12586, avg=12287.90, stdev=137.77, samples=240
  lat (msec)   : 20=43.82%, 50=56.22%
  cpu          : usr=99.73%, sys=0.00%, ctx=214, majf=0, minf=540
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=116.7%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=1465059,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
   READ: bw=3052MiB/s (3200MB/s), 3052MiB/s-3052MiB/s (3200MB/s-3200MB/s), io=179GiB (192GB), run=60023-60023msec

Running fio with numjob=4 starts 4 thread to run the I/O workload. This test ran successfully.

[root@fedora27-SPDK oracle_perf_scripts]# vim sr_128k.fio
[root@fedora27-SPDK oracle_perf_scripts]# LD_PRELOAD=/home/john/spdk/new/spdk/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
...
fio-3.3
Starting 4 threads
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid90636 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid90636_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Jobs: 1 (f=0): [_(1),f(1),_(2)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
SR_128K_QD256: (groupid=0, jobs=4): err= 0: pid=90761: Thu Jul 26 08:35:46 2018
   read: IOPS=22.9k, BW=2865MiB/s (3004MB/s)(168GiB/60053msec)
    slat (nsec): min=69, max=137880, avg=86.34, stdev=130.92
    clat (msec): min=31, max=107, avg=44.69, stdev= 5.66
     lat (msec): min=31, max=107, avg=44.69, stdev= 5.66
    clat percentiles (usec):
     |  1.00th=[34866],  5.00th=[36439], 10.00th=[37487], 20.00th=[39060],
     | 30.00th=[40633], 40.00th=[42730], 50.00th=[44303], 60.00th=[46400],
     | 70.00th=[47973], 80.00th=[50070], 90.00th=[52167], 95.00th=[53740],
     | 99.00th=[56886], 99.50th=[58459], 99.90th=[62653], 99.95th=[68682],
     | 99.99th=[93848]
   bw (  KiB/s): min=710284, max=760531, per=25.15%, avg=737844.86, stdev=9791.53, samples=480
   iops        : min= 5549, max= 5941, avg=5763.92, stdev=76.42, samples=480
  lat (msec)   : 50=80.07%, 100=19.99%, 250=0.01%
  cpu          : usr=99.76%, sys=0.00%, ctx=250, majf=0, minf=438
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=116.7%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=1375382,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
   READ: bw=2865MiB/s (3004MB/s), 2865MiB/s-2865MiB/s (3004MB/s-3004MB/s), io=168GiB (180GB), run=60053-60053msec

   
## Current Behavior

When I run fio with a configuration of numjob=8 I get a segmentation fault.

LD_PRELOAD=/home/john/spdk/new/spdk/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
...
fio-3.3
Starting 8 threads
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid92555 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid92555_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Segmentation fault (core dumped)1739MiB/s,w=0KiB/s][r=13.9k,w=0 IOPS][eta 00m:00s]

dmesg shows the following
[332436.503672] fio[93792]: segfault at 7f77200c99d0 ip 00007f7775babf50 sp 00007f7754d30a68 error 4 in libpthread-2.26.so[7f7775b9d000+19000]

## Steps to Reproduce
1. Create an fio configuration file that has the following parameters. Set the filename to the BDF for your NVMe SSDs( I am using a P4600)
[global]
filename=trtype=PCIe traddr=0000.1b.00.0 ns=1
ioengine=spdk
thread=1
direct=1
offset=0%
numjobs=8
offset_align=4k
random_generator=tausworthe64
ramp_time=10
group_reporting=1
[SR_128K_QD256]
wait_for_previous
rw=read
bs=128K
iodepth=256
size=100%
runtime=60

2. Run fio
LD_PRELOAD=/<path_to_spdk>/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
...
fio-3.3
Starting 8 threads
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid90000 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid90000_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Segmentation fault (core dumped)2058MiB/s,w=0KiB/s][r=16.5k,w=0 IOPS][eta 00m:00s]

## Context (Environment including OS version, SPDK version, etc.)
OS: Linux fedora27-SPDK.localdomain 4.15.15-300.fc27.x86_64
SPDK commit e152aa8e51798a090a7a7ecb2799f605df930761
SSD: Intel® P4600 1.6TB (FW: QDV10130 )
Hugepage Size: 1 GB

**Comment by lhoswdev** [comment]
Patch submitted:  https://review.gerrithub.io/#/c/spdk/spdk/+/420575/

**Comment by KariukiJ** [comment]
I have validated that the issue is resolved in the SPDK master after merging the patch to fix this issue. I ran with numjob=8 and numjob=16 successfully.
[root@fedora27-SPDK oracle_perf_scripts]# LD_PRELOAD=../new/spdk/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
...
fio-3.3
Starting 8 threads
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid104495 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid104495_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Segmentation fault (core dumped)2317MiB/s,w=0KiB/s][r=18.5k,w=0 IOPS][eta 00m:00s]
[root@fedora27-SPDK oracle_perf_scripts]#
[root@fedora27-SPDK oracle_perf_scripts]#
[root@fedora27-SPDK oracle_perf_scripts]# LD_PRELOAD=../new/spdk/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
...
fio-3.3
Starting 8 threads
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid108694 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid108694_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Jobs: 1 (f=0): [_(1),f(1),_(6)][100.0%][r=264MiB/s,w=0KiB/s][r=2111,w=0 IOPS][eta 00m:00s]
SR_128K_QD256: (groupid=0, jobs=8): err= 0: pid=108811: Fri Jul 27 14:27:02 2018
   read: IOPS=16.3k, BW=2037MiB/s (2136MB/s)(120GiB/60127msec)
    slat (nsec): min=73, max=16392, avg=105.32, stdev=72.28
    clat (msec): min=95, max=262, avg=125.79, stdev= 9.66
     lat (msec): min=95, max=262, avg=125.79, stdev= 9.66
    clat percentiles (msec):
     |  1.00th=[  109],  5.00th=[  113], 10.00th=[  115], 20.00th=[  117],
     | 30.00th=[  121], 40.00th=[  123], 50.00th=[  126], 60.00th=[  129],
     | 70.00th=[  131], 80.00th=[  134], 90.00th=[  138], 95.00th=[  142],
     | 99.00th=[  148], 99.50th=[  150], 99.90th=[  190], 99.95th=[  226],
     | 99.99th=[  251]
   bw (  KiB/s): min=242944, max=279014, per=12.61%, avg=263015.74, stdev=5220.77, samples=960
   iops        : min= 1898, max= 2179, avg=2054.35, stdev=40.73, samples=960
  lat (msec)   : 100=0.05%, 250=100.15%, 500=0.01%
  cpu          : usr=99.76%, sys=0.00%, ctx=356, majf=0, minf=1684
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=116.8%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=977900,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
   READ: bw=2037MiB/s (2136MB/s), 2037MiB/s-2037MiB/s (2136MB/s-2136MB/s), io=120GiB (128GB), run=60127-60127msec
[root@fedora27-SPDK oracle_perf_scripts]# vim sr_128k.fio
[root@fedora27-SPDK oracle_perf_scripts]# LD_PRELOAD=../new/spdk/examples/nvme/fio_plugin/fio_plugin fio sr_128k.fio
SR_128K_QD256: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=256
...
fio-3.3
Starting 16 threads
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio -c 0x1 -m 512 --file-prefix=spdk_pid108846 ]
EAL: Detected 112 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid108846_unix
EAL: Probing VFIO support...
EAL: PCI device 0000:1b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Jobs: 1 (f=0): [_(7),f(1),_(8)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
SR_128K_QD256: (groupid=0, jobs=16): err= 0: pid=108963: Fri Jul 27 14:28:41 2018
   read: IOPS=11.6k, BW=1456MiB/s (1527MB/s)(85.8GiB/60378msec)
    slat (nsec): min=76, max=16112, avg=107.64, stdev=53.11
    clat (msec): min=288, max=738, avg=352.72, stdev=22.91
     lat (msec): min=288, max=738, avg=352.72, stdev=22.91
    clat percentiles (msec):
     |  1.00th=[  317],  5.00th=[  326], 10.00th=[  334], 20.00th=[  338],
     | 30.00th=[  342], 40.00th=[  347], 50.00th=[  351], 60.00th=[  355],
     | 70.00th=[  359], 80.00th=[  363], 90.00th=[  372], 95.00th=[  380],
     | 99.00th=[  393], 99.50th=[  422], 99.90th=[  659], 99.95th=[  701],
     | 99.99th=[  726]
   bw (  KiB/s): min=86272, max=105671, per=6.31%, avg=94049.87, stdev=2487.18, samples=1920
   iops        : min=  674, max=  825, avg=734.33, stdev=19.42, samples=1920
  lat (msec)   : 500=100.20%, 750=0.38%
  cpu          : usr=99.75%, sys=0.00%, ctx=438, majf=0, minf=2735
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=117.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=699118,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
   READ: bw=1456MiB/s (1527MB/s), 1456MiB/s-1456MiB/s (1527MB/s-1527MB/s), io=85.8GiB (92.2GB), run=60378-60378msec
