### ISSUE TITLE
two cases should be removed in server "freebsd-0" in NIGHTLY TEST - master

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#381]
I found the two cases are skipped in server "freebsd-0" in NIGHTLY TEST - master .
test/blobfs/rocksdb/rocksdb.sh
test/blobstore/blobstore.sh

## Expected Behavior
no cases are skipped.

## Current Behavior
/usr/src/rocksdb   does not exist.
blobstore.sh cannot run on   FreeBSD currently.
these two cases are skipped.

## Possible Solution
remove them, because them have been replaced by others.

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view https://ci.spdk.io/spdk/builds/review/4586074545eb46b4116792417305d69b296ad35b.1532865653/freebsd-0/build.log

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: If25463ea76e8382c61f10636e1119376a00104dc

**Comment by jimharris** [comment]
Hi Hailiang,

I don't see the bug here.  Can you explain further?  We don't run these tests on FreeBSD at all - but they get lots of coverage on Linux.  I don't think we should spend time getting these tests to run on FreeBSD unless there is some specific request.

Thanks,

-Jim

**Comment by wanghailiangx** [comment]
@jimharris  I thought that these two use cases were not running on other machines, and they were also skipped here. Now found running successfully on "fedora-04". It can be closed.
