### ISSUE TITLE
err_injection test run skipped in Linux in NIGHTLY TEST - master

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#383]
err_injection test run skipped in all Linux servers in NIGHTLY TEST - master, but passed in freebsd.

## Expected Behavior
err_injection test run passed in Linux servers.

## Current Behavior
err_injection test run skipped in all Linux servers.

## Possible Solution
err_injection test may be moved out of stub in test/nvme/nvme.sh.

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view https://ci.spdk.io/spdk/builds/review/4586074545eb46b4116792417305d69b296ad35b.1532865653/centos7/build.log

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: If25463ea76e8382c61f10636e1119376a00104dc

**Comment by jimharris** [comment]
Or can we specify opts.shm_id = 0 like we do for other tests in this file?

err_injection.c should also fail if no NVMe devices are found.

**Comment by changpe1** [comment]
I pushed a patch to fix this: https://review.gerrithub.io/#/c/spdk/spdk/+/421071/

**Comment by wanqunintel** [comment]
@wanghailiangx would you have a check why it's failed in the nightly master test?

**Comment by wanghailiangx** [comment]
This "Build with tests failed" does not appear again in new merged patch. The NIGHTLY failed case is an other problem. I will raise a new issue.
This issue can be closed.
