### ISSUE TITLE
unknown option 'pool init rbd' in NIGHTLY TEST - master

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#384]
run test/bdev/bdevjson/rbd_json_config.sh in NIGHTLY TEST - master.

## Current Behavior
# rbd pool init rbd
error: unknown option 'pool init rbd'
usage: rbd <command> ...
This error occurs in all Linux servers.

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view https://ci.spdk.io/spdk/builds/review/4586074545eb46b4116792417305d69b296ad35b.1532865653/fedora-01/build.log

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: If25463ea76e8382c61f10636e1119376a00104dc

**Comment by wanghailiangx** [comment]
The same error occurs in running "test/spdkcli/rbd.sh" on fedora-01, and "rbd_setup 127.0.0.1 in test/bdev/blockdev.sh" on fedora-02.

**Comment by jimharris** [comment]
This bug is very low priority.

I think maybe older versions of Ceph had this option, but now it's not needed and so they removed the option.  You can see that tests still continue OK.

Maybe we can just remove this "rbd pool init" line altogether?  @optimistyzy - what do you think?

-Jim

**Comment by wanghailiangx** [comment]
I pushed a patch to fix this: https://review.gerrithub.io/#/c/spdk/spdk/+/421482/

**Comment by liang2yan** [comment]
patch merged. issue can't be reproduced. so close this issue.
