### ISSUE TITLE
Can't create nvme bdev after error command when using spdk-cli

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#385]
Can't create nvme bdev after error command when using spdk-cli

## Expected Behavior
can create nvme bdev after error command

## Current Behavior
spdk-cli
```
/bdevs/nvme> create name=nvme1 trtype=PCIe traddr=0000.81.00.0
Got JSON-RPC error response
request:
{
  "params": {
    "trtype": "PCIe",
    "name": "nvme1",
    "traddr": "0000.81.00.0"
  },
  "jsonrpc": "2.0",
  "method": "construct_nvme_bdev",
  "id": 1
}
response:
{
  "message": "Invalid parameters",
  "code": -32602
}

```
spdk target
```
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: spdk_tgt -c 0x1 --file-prefix=spdk_pid24793 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid24793_unix
EAL: Probing VFIO support...
app.c: 530:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
EAL: PCI device 0000:84:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
bdev.c:2790:spdk_bdev_init: *ERROR*: Bdev name:nvme0n1 already exists
bdev_nvme.c:1147:spdk_bdev_nvme_create: *ERROR*: Failed to find new NVMe controller
EAL: Cannot find unplugged device (0000:81:00.0)
bdev_nvme.c:1147:spdk_bdev_nvme_create: *ERROR*: Failed to find new NVMe controller
```

## Steps to Reproduce

1. ./app/spdk_tgt/spdk_tgt
2. ./scripts/spdkcli.py
3. cd bdevs/nvme
4. create name=nvme0 trtype=PCIe traddr=0000.03.00.0
5. create name=nvme0 trtype=PCIe traddr=0000.81.00.0
6. create name=nvme1 trtype=PCIe traddr=0000.81.00.0

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora release 27 (Twenty Seven)
Linux version: 4.17.3-100.fc27.x86_64
gcc version: 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
SPDK: master (commit id: 63528ebc76659787822f43b7f45ea4c393680a39)

**Comment by Maciej-Szwed** [comment]
Fix for this issue is currently in review:
https://review.gerrithub.io/c/spdk/spdk/+/421006

Regards

**Comment by ChenWang01** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/421006
The patch can fix this issue, so i will close it.
