### ISSUE TITLE
test/nvme/reset/reset can't find SSD in NIGHTLY TEST - master

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#386]
run "test/nvme/nvme.sh", there is an error caused by "reset -q 64 -w   write -s 4096 -t 2".

## Expected Behavior
Associating INTEL SSD**** with lcore 0

## Current Behavior
In linux:
Cannot create lock on device /tmp/spdk_pci_lock_0000:00:04.0, probably process 13636 has claimed it
nvme_pcie.c: 793:nvme_pcie_ctrlr_construct: *ERROR*: could not claim device 0000:00:04.0
nvme.c: 384:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 0000:00:04.0
EAL: Requested device 0000:00:04.0 cannot be used

In FreeBSD, it is another error:
Unable to unlink shared memory file: /var/run/.spdk_pid93720_config. Error code: 2
Unable to unlink shared memory file: /var/run/.spdk_pid93720_hugepage_info. Error code: 2
nvme_ctrlr.c: 710:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_pcie.c:1296:nvme_pcie_qpair_abort_trackers: *ERROR*: aborting outstanding command
*ERROR*: === BACKTRACE START ===
......
*ERROR*: === BACKTRACE END ===
Associating INTEL SSDPEDMD800G4  (CVFT50430005800CGN  ) with lcore 0

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view https://ci.spdk.io/spdk/builds/review/a4c65d7c81090e1689e169e8023d905990608316.1532692839/centos7/build.log and https://ci.spdk.io/spdk/builds/review/a4c65d7c81090e1689e169e8023d905990608316.1532692839/freebsd-0/build.log

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: If25463ea76e8382c61f10636e1119376a00104dc

**Comment by jimharris** [comment]
Good catch!  Thank you for really digging into the nightly test logs.

I think there are multiple bugs here:

1) the "reset" test should exit with failure if no NVMe controllers can be attached - then we would have found this issue a long time ago :-)
2) maybe this test should set the shm_id to 0?  similar to some of the other NVMe tests; this allows them to run with the stub and reduce overall test time

I think this is low priority.

**Comment by changpe1** [comment]
I pushed a patch to fix this, https://review.gerrithub.io/#/c/spdk/spdk/+/421070/

**Comment by jimharris** [comment]
Patch merged.
