### ISSUE TITLE
Can't use nvme bdev's name to delete the bdev

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#389]
Can't use the nvme bdev's name to delete the bdev.
Can use nvme conttroller's name to delete the bdev.

## Expected Behavior
Can use the nvme bdev's name to delete the bdev.

## Current Behavior
```
/bdevs/nvme> delete nvme0n1
Got JSON-RPC error response
request:
{
  "params": {
    "name": "nvme0n1"
  },
  "jsonrpc": "2.0",
  "method": "delete_nvme_controller",
  "id": 1
}
response:
{
  "message": "No such device",
  "code": -32602
}

./rpc.py delete_nvme_controller nvme0n1
Got JSON-RPC error response
request:
{
  "params": {
    "name": "nvme0n1"
  },
  "jsonrpc": "2.0",
  "method": "delete_nvme_controller",
  "id": 1
}
response:
{
  "message": "No such device",
  "code": -32602
}
```

## Possible Solution
```
--- a/lib/bdev/nvme/bdev_nvme.c
+++ b/lib/bdev/nvme/bdev_nvme.c
@@ -782,7 +782,7 @@ nvme_ctrlr_get_by_name(const char *name)
        }

        TAILQ_FOREACH(nvme_ctrlr, &g_nvme_ctrlrs, tailq) {
-               if (strcmp(name, nvme_ctrlr->name) == 0) {
+               if (strcmp(name, nvme_ctrlr->name) == 0 || strcmp(name, nvme_ctrlr->bdevs->disk.name) == 0) {
                        return nvme_ctrlr;
                }
        }

```
## Steps to Reproduce

```
1. ./app/spdk_tgt/spdk_tgt
2. ./scripts/spdkcli.py
3. cd bdevs/nvme
4. create name=nvme0 trtype=PCIe traddr=0000.03.00.0
5. delete nvme0n1
```

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora release 27 (Twenty Seven)
Linux version: 4.17.3-100.fc27.x86_64
gcc version: 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
SPDK: master (commit id: c9e5777ede291cc8a5e9166e6c1979174b545c96)

**Comment by changpe1** [comment]
delete nvme0n1 should not call delete_nvme_controller, because it's block device's name.

**Comment by wanqunintel** [comment]
@ChenWang01 Would you check the spdk.py script it's calling the wrong method when deleting the bdev.
Got JSON-RPC error response
request:
{
  "params": {
    "name": "nvme0n1"
  },
  "jsonrpc": "2.0",
  "method": "delete_nvme_controller",
  "id": 1
}

**Comment by Maciej-Szwed** [comment]
The idea behind "delete" command in SPDK-CLI and delete_nvme_controller command is to detach NVMe device from SPDK. I don't see any point in removing one of the controller's bdev, but leaving other bdev from this controller and controller itself still available in SPDK. That's way we decide to do the deletion using controllers name instead of one of its bdev. 
You can also look at this from another point:
If you remove all the bdevs within particular controller you won't be able to create those bdevs again as the controller still exists and you cannot use construct_nvme_bdev command to restore the bdevs. In current implementation, after deleting controller, you can restore it with all its bdevs using construct_nvme_bdev command.

**Comment by ChenWang01** [comment]
@Maciej-Szwed 
I find "delete" command  call the "delete_bdev" method in the "bdevs/split_disk" directory and call the "delete_nvme_controller" method in the "bdevs/nvme" directory. So i followed steps.

```
1. ./app/spdk_tgt/spdk_tgt
2. ./scripts/spdkcli.py
3. cd bdevs/nvme
4. create name=nvme0 trtype=PCIe traddr=0000.03.00.0
5. cd ../split_disk
6. delete nvme0n1       "delete bdev successfully"
7. cd ../nvme
8. delete nvme0            "No such controller"
9. create name=nvme0 trtype=PCIe traddr=0000.03.00.0
```

**Comment by jimharris** [comment]
@Maciej-Szwed is correct.  We should not be using the delete_bdev method at all anymore.  We are adding module-specific delete methods for every bdev module, and will be removing the delete_bdev RPC in the next release.

This looks more like an spdkcli bug.  We still have the delete_bdev method plumbed.  If you cd to the split_disk directory and do "help", you see both "delete" and "destruct_split_bdev" as options.  I think the "delete" option should be removed now that we have per-module delete methods for every bdev module.

**Comment by jimharris** [comment]
Hi @karlatec - can you take a look at this?

I tried to assign it to you, but you're not in the SPDK GitHub group yet.  You should have an invitation now though - I just sent one.

Thanks,

-Jim

**Comment by karlatec** [comment]
@ChenWang01 @jimharris 
"delete_bdev" was used in /bdevs node of spdkcli as a general tool for deleting all types of bdevs.
Now that all nodes for bdevs have their own specific "delete_*" methods there is no need to keep the general call. Removed here: https://review.gerrithub.io/#/c/spdk/spdk/+/421208/

As for original reported problem "Can't use nvme bdev's name to delete the bdev" - as Maciek explains it, this is a correct behavior. To delete nvme bdevs you call "delete_nvme_controller" which uses nvme controller name, not nvme bdev name.

**Comment by ChenWang01** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/421208/ this patch removed the "delete_bdev" method in spdkcli.
Can we close this issue? Since we call "delete_nvme_controller" to delete the nvme bdevs and use the controller name.

**Comment by wanqunintel** [comment]
patch has been merged, @ChenWang01 would you verify it? thanks.

**Comment by jimharris** [comment]
Patches have been merged.
