### ISSUE TITLE
Support For Big Endian Systems

### ISSUE THREAD

**Issue by shterman** [spdk/spdk#39]
Hi,

I can't find in code where do we format the cq_head/sq_tail to little endian format before writing it to doorbell. isn't it a necessary step?

Thanks,
Roy

**Comment by dverkamp-intel** [comment]
SPDK currently only works on little-endian machines.  More than just the doorbell access would need to be modified - all in-memory data structures and NVMe register accesses would need to be wrapped with endian conversion.

Patches to add big-endian support would be accepted assuming there is someone to maintain the support - we don't have a way to test with a non-x86 host system.

**Comment by benlwalker** [comment]
I modified the title to make this a request for big endian support.

**Comment by johnmeneghini** [comment]
I just want to point out that support for Big Endian is not just a platform issue.  The implementation of FC-NVMe will require support for Big Endian data structures in the NVMF stack.

Read Annex A of the FC-NVMe specification.  Here's the latest draft.

https://standards.incits.org/apps/group_public/download.php/87364/T11-2017-00020-v003.pdf

**Comment by jimharris** [comment]
Closing this issue.  I don't see SPDK adding support for big endian platforms.  If there's demand for it and someone is interested in implementing it, we can reopen this issue.
