### ISSUE TITLE
Fail to unlink shared memory file when apps running by non-privileged user

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#390]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

When running SPDK app with non-proviledged user, all the shared memory related files should be unlinked on app exit, no error should be reported.
## Current Behavior

Every time when initialize SPDK env by our app, it reports error like following.

Unable to unlink shared memory file: /var/run/.spdk_pid115688_config. Error code: 2
Unable to unlink shared memory file: /var/run/.spdk_pid115688_hugepage_info. Error code: 2

It looks like a SPDK bug, because it tries to find and delete the spdk_pid files for root user, these files for non-privileged user are in their $HOME directory.

## Possible Solution

See spdk_env_unlink_shared_files() in ./lib/env_dpdk/init.c, the file path is hardcoded, it actually should be generated by current uid.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
@NiuYawei - thanks for the report!

spdk_env_unlink_shared_files should use eal_get_runtime_dir() instead of hardcoding /var/run.

(Note that the cleanup code later in this function is already using eal_get_runtime_dir().)

**Comment by xuhuagen** [comment]
@NiuYawei  could you list the steps of reproducing this issue?

**Comment by NiuYawei** [comment]
We are developing DAOS NVMe support by SPDK, and the error messages popped up when starting DAOS server by non-root user, it seems to me these reproducing steps are useless for you.

The root cause is about "spdk_env_unlink_shared_files should use eal_get_runtime_dir() instead of hardcoding /var/run." Just as Jim mentioned in previous comment.

**Comment by changpe1** [comment]
Patch https://review.gerrithub.io/#/c/spdk/spdk/+/421169/ can fix the issue, but may need some time for code merge.

**Comment by wanqunintel** [comment]
@NiuYawei would you verify Changpeng's patch? thanks.

**Comment by Seth5141** [comment]
@NiuYawei Please try the following commit 194b8ec which has been merged and I believe fixes this issue. We chose to run the program without a shared config file when running in single process mode. This allows us to avoid unlinking the files.

**Comment by NiuYawei** [comment]
Thank you, I believe the issue has been fixed from the code. We'll verify it on next SPDK update.

**Comment by darsto** [comment]
This should be now fixed on master with DPDK 18.05+:

https://review.gerrithub.io/c/spdk/spdk/+/421652
https://review.gerrithub.io/c/spdk/spdk/+/420659
