### ISSUE TITLE
compile issue on centos 7.5..

### ISSUE THREAD

**Issue by ack72tdp** [spdk/spdk#392]
CC lib/iscsi/conn.o
  CC lib/iscsi/init_grp.o
  CC lib/iscsi/iscsi.o
In file included from iscsi.c:46:0:
/root/anil/spdk/lib/iscsi/md5.h:40:25: fatal error: openssl/md5.h: No such file or directory
 #include <openssl/md5.h>
                         ^
compilation terminated.
make[2]: *** [iscsi.o] Error 1
make[1]: *** [iscsi] Error 2
make: *** [lib] Error 2

[root@sio37-12 spdk]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

Any ideas on this compile issue? OpenSSL is seems to be installed .. However during the setup script .. I get these errors ..

--> Restarting Dependency Resolution with new changes.
--> Running transaction check
---> Package rdma-core.i686 0:15-7.el7_5 will be installed
--> Processing Dependency: rdma-core(x86-32) = 15-7.el7_5 for package: librdmacm-15-7.el7_5.i686
--> Processing Dependency: rdma-core(x86-32) = 15-7.el7_5 for package: libibcm-15-7.el7_5.i686
--> Processing Dependency: rdma-core(x86-32) = 15-7.el7_5 for package: libibverbs-15-7.el7_5.i686
--> Processing Dependency: rdma-core(x86-32) = 15-7.el7_5 for package: libibumad-15-7.el7_5.i686
---> Package rdma-core.x86_64 0:15-7.el7_5 will be installed
--> Processing Dependency: rdma-core(x86-64) = 15-7.el7_5 for package: iwpmd-15-7.el7_5.x86_64
---> Package rdma-core-devel.x86_64 0:15-7.el7_5 will be installed
--> Finished Dependency Resolution
Error: Package: iwpmd-15-7.el7_5.x86_64 (@updates)
           Requires: rdma-core(x86-64) = 15-7.el7_5
           Available: rdma-core-15-6.el7.x86_64 (base)
               rdma-core(x86-64) = 15-6.el7
Error: Package: libibcm-15-7.el7_5.i686 (updates)
           Requires: rdma-core(x86-32) = 15-7.el7_5
           Available: rdma-core-15-6.el7.i686 (base)
               rdma-core(x86-32) = 15-6.el7
Error: Package: libibverbs-15-7.el7_5.i686 (updates)
           Requires: rdma-core(x86-32) = 15-7.el7_5
           Available: rdma-core-15-6.el7.i686 (base)
               rdma-core(x86-32) = 15-6.el7
Error: Package: rdma-core-devel-15-7.el7_5.x86_64 (updates)
           Requires: libmlx4.so.1()(64bit)
           Available: libibverbs-15-6.el7.x86_64 (base)
               libmlx4.so.1()(64bit)
           Available: libibverbs-15-7.el7_5.x86_64 (updates)
               libmlx4.so.1()(64bit)
           Installed: libibverbs-41mlnx1-OFED.4.4.1.0.0.44100.x86_64 (installed)
               Not found
Error: Package: libibumad-15-7.el7_5.i686 (updates)
           Requires: rdma-core(x86-32) = 15-7.el7_5
           Available: rdma-core-15-6.el7.i686 (base)
               rdma-core(x86-32) = 15-6.el7
Error: Package: rdma-core-devel-15-7.el7_5.x86_64 (updates)
           Requires: ibacm = 15-7.el7_5
           Installed: ibacm-41mlnx1-OFED.4.3.3.0.0.44100.x86_64 (installed)
               ibacm = 41mlnx1-OFED.4.3.3.0.0.44100
           Available: ibacm-15-6.el7.x86_64 (base)
               ibacm = 15-6.el7
           Available: ibacm-15-7.el7_5.x86_64 (updates)
               ibacm = 15-7.el7_5
Error: Package: librdmacm-15-7.el7_5.i686 (updates)
           Requires: rdma-core(x86-32) = 15-7.el7_5
           Available: rdma-core-15-6.el7.i686 (base)
               rdma-core(x86-32) = 15-6.el7
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
iwpmd-15-7.el7_5.x86_64 has missing requires of rdma-core(x86-64) = ('0', '15', '7.el7_5')
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos
Loading mirror speeds from cached hostfile
 * base: mirror.atlantic.net
 * epel: mirror.seas.harvard.edu
 * extras: centos.mirror.constant.com
 * updates: mirror.ash.fastserv.com
Package numactl-devel-2.0.9-7.el7.x86_64 already installed and latest version
Package nasm-2.10.07-7.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos
Loading mirror speeds from cached hostfile

**Comment by changpe1** [comment]
Did you install openssl-devel in your system ?

**Comment by ack72tdp** [comment]
yep .. fixed after installing openssl-devel ... thanks...
