### ISSUE TITLE
nvmf target hung up after using ctlr+c kill command if using 32 cores for P3700 NVMe SSD

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#395]
This issue is related with the issue 282, https://github.com/spdk/spdk/issues/282.

## Steps to Reproduce
1. configure spdk nvmf target config with following content:
ReactorMask 0x00FFFFFFFF
Use P3700 as the nvme controller. configure spdk subsytem using nvme bdev.
2.run spdk nvmf target with the config file.
3. In host machine, discover and connect to the spdk subsystem. then disconnect.
4. In target machine, use ctrlr+c to kill nvmf target.

## Expected Behavior
No error and hung up happend.

## Current Behavior
SPDK nvmf target hung up.

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora 28
SPDK commit: 25a89b2ac3ce4a603f3a70cb5e7a29285cb3fd8a

**Comment by Comphix** [comment]
Looking at this issue.

**Comment by Comphix** [comment]
This issue looks like still relating to the un-initialized Qpair where it is NULL and the sgroup is not triggered to Active state. For the coming I/Os, they are just queued. The possible fix is to return these errors in Error. I am looking at a complete fix as it seems there are other issues regarding this situation.

**Comment by benlwalker** [comment]
Does this patch fix it? https://review.gerrithub.io/#/c/spdk/spdk/+/421167/

**Comment by Comphix** [comment]
Have raised a patch https://review.gerrithub.io/#/c/spdk/spdk/+/422799/ and the previous hanging up and ASAN memory issue is no seen. The "ctrl+c" to kill the target can be successful.

However, even with this patch, there still has two small issues which require further patch to address.

1. The disconnect operation from the initiator side may take a little time (e.g., 1 minute) to execute for the Subystem which has not properly activated due to NULL IO qpair
2. The ctrl+c operation will report one data buffer is not release at the time of Target destruct.

Will keep looking at these two small issues.

**Comment by Comphix** [comment]
Patch has been tracked at https://review.gerrithub.io/#/c/spdk/spdk/+/423646/

**Comment by Comphix** [comment]
Tested with 1000 iterations of connect and disconnect operations from the initiator side accordingly to the configuration here (32cores + P3700). The hang up issue is not seen the the device can be properly listed.

[ Command output ]
NAME    MAJ:MIN  RM   SIZE RO TYPE MOUNTPOINT
sda       8:0     0 931.5G  0 disk
├─sda1    8:1     0   915G  0 part /
└─sda2    8:2     0    16G  0 part [SWAP]
sr0      11:0     1  1024M  0 rom
nvme0n1 259:6847  0 745.2G  0 disk
nvme1n1 259:6853  0   1.5T  0 disk
nvme2n1 259:6857  0 745.2G  0 disk
nvme3n1 259:6859  0   1.5T  0 disk
nvme4n1 259:6861  0 745.2G  0 disk
nvme5n1 259:6863  0 745.2G  0 disk
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     SPDK00000000000001   SPDK bdev Controller                     1         800.17  GB / 800.17  GB    512   B +  0 B   18.10
/dev/nvme1n1     SPDK00000000000002   SPDK bdev Controller                     1           1.60  TB /   1.60  TB    512   B +  0 B   18.10
/dev/nvme2n1     SPDK00000000000003   SPDK bdev Controller                     1         800.17  GB / 800.17  GB    512   B +  0 B   18.10
/dev/nvme3n1     SPDK00000000000004   SPDK bdev Controller                     1           1.60  TB /   1.60  TB    512   B +  0 B   18.10
/dev/nvme4n1     SPDK00000000000005   SPDK bdev Controller                     1         800.17  GB / 800.17  GB    512   B +  0 B   18.10
/dev/nvme5n1     SPDK00000000000006   SPDK bdev Controller                     1         800.17  GB / 800.17  GB    512   B +  0 B   18.10
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode2 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode3 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode4 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode5 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode6 disconnected 1 controller(s)
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 931.5G  0 disk
├─sda1   8:1    0   915G  0 part /
└─sda2   8:2    0    16G  0 part [SWAP]
sr0     11:0    1  1024M  0 rom
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- ---------

[Dmesg output: take the error situation where hit the NULL IO QPair and Inactive Subsystem at the Target side]
[Wed Aug 29 16:03:39 2018] nvme nvme0: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 192.168.89.11:4420
[Wed Aug 29 16:03:39 2018] nvme nvme0: Removing ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery"
[Wed Aug 29 16:03:39 2018] nvme nvme0: Property Set error: 7, offset 0x14
[Wed Aug 29 16:03:39 2018] nvme nvme0: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 192.168.89.11:4420
[Wed Aug 29 16:03:39 2018] nvme nvme0: Removing ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery"
[Wed Aug 29 16:03:39 2018] nvme nvme0: Property Set error: 7, offset 0x14
[Wed Aug 29 16:03:39 2018] nvme nvme0: creating 3 I/O queues.
[Wed Aug 29 16:03:39 2018] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 192.168.89.11:4420
[Wed Aug 29 16:03:39 2018] print_req_error: critical medium error, dev nvme0c1111n1, sector 1562824192
[Wed Aug 29 16:03:39 2018] print_req_error: critical medium error, dev nvme0c1111n1, sector 1562824192
[Wed Aug 29 16:03:39 2018] Buffer I/O error on dev nvme0n1, logical block 195353024, async page read
[Wed Aug 29 16:03:39 2018] nvme nvme1: creating 3 I/O queues.
[Wed Aug 29 16:03:39 2018] nvme nvme1: new ctrl: NQN "nqn.2016-06.io.spdk:cnode2", addr 192.168.89.11:4420
[Wed Aug 29 16:03:39 2018] nvme nvme2: creating 3 I/O queues.
[Wed Aug 29 16:03:39 2018] nvme nvme2: new ctrl: NQN "nqn.2016-06.io.spdk:cnode3", addr 192.168.89.11:4420
[Wed Aug 29 16:03:39 2018] nvme nvme3: creating 3 I/O queues.
[Wed Aug 29 16:03:39 2018] nvme nvme3: new ctrl: NQN "nqn.2016-06.io.spdk:cnode4", addr 192.168.89.11:4420
[Wed Aug 29 16:03:39 2018] nvme nvme4: creating 3 I/O queues.
[Wed Aug 29 16:03:39 2018] nvme nvme4: new ctrl: NQN "nqn.2016-06.io.spdk:cnode5", addr 192.168.89.11:4420
[Wed Aug 29 16:03:39 2018] nvme nvme5: creating 3 I/O queues.
[Wed Aug 29 16:03:39 2018] nvme nvme5: new ctrl: NQN "nqn.2016-06.io.spdk:cnode6", addr 192.168.89.11:4420
[Wed Aug 29 16:03:41 2018] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
[Wed Aug 29 16:03:41 2018] nvme nvme0: Property Set error: 7, offset 0x14
[Wed Aug 29 16:03:41 2018] nvme nvme1: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode2"
[Wed Aug 29 16:03:41 2018] nvme nvme1: Property Set error: 7, offset 0x14
[Wed Aug 29 16:03:41 2018] nvme nvme2: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode3"
[Wed Aug 29 16:03:41 2018] nvme nvme2: Property Set error: 7, offset 0x14
[Wed Aug 29 16:03:41 2018] nvme nvme3: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode4"
[Wed Aug 29 16:03:41 2018] nvme nvme3: Property Set error: 7, offset 0x14
[Wed Aug 29 16:03:41 2018] nvme nvme4: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode5"
[Wed Aug 29 16:03:42 2018] nvme nvme4: Property Set error: 7, offset 0x14
[Wed Aug 29 16:03:42 2018] nvme nvme5: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode6"
[Wed Aug 29 16:03:42 2018] nvme nvme5: Property Set error: 7, offset 0x14
