### ISSUE TITLE
ISCSI target crashed due to segment when doing the fio test in the client side

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#397]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

When doing the fio test against SPDK iSCSI target. The network can be disconnected due to some situations. To simulate this issue, we disable NIC function in the client side. The fio hangs as expected, then we kill the iSCSI target, see whether the iSCSI target can exit correctly. 

## Expected Behavior
ISCSI target can exit correctly without any coredump or hang.

## Current Behavior
Due to the unexpected TCP/IP connection broken, the iSCSI target cannot exit even if using "ctrlr +c". And some times the iSCSI target crashes.

## Possible Solution
https://review.gerrithub.io/420875
https://review.gerrithub.io/421668
https://review.gerrithub.io/421706
Three patches are provided under review. And it is verified by both me and customers.

## Steps to Reproduce
1 Start the SPDK iSCSI target in the server side;
2  Use the iscsiadmin in the initiator side to connect and login.
3 Running fio jobs.
4 Disable the NiC card in the initiator machines.
5 Stop the iSCSI target to see whether it can be correctly stopped.
6 Restart the iSCSI target.
7 Re-enable the network in the initiator side, the workload can be resumed.

## Context (Environment including OS version, SPDK version, etc.)
Any SPDK version.  SPDK 18.07 or master
OS version: Any linux version (e.g., fedora, ubuntu)

**Comment by xuhuagen** [comment]
@optimistyzy  I follow ypur steps and trying to reproduce it,  I disable the NiC card by using ifconfig interface down. but the iSCSI target can be correctly stopped.   
How quick does this issue happen?

**Comment by wanqunintel** [comment]
@xuhuagen which commit do you use?

**Comment by wanqunintel** [comment]
@optimistyzy do you have some command in detail so that huagen can verify more accurate? thank you.

**Comment by wanqunintel** [comment]
checked with Ziye and issue has been closed.
