### ISSUE TITLE
Jsonrpc: Support for handling JSON batch requests

### ISSUE THREAD

**Issue by Rakesh-Babu-Saladi** [spdk/spdk#398]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Batch requests should be handled

## Current Behavior

When submitting a batch request, the nvmf_tgt  returns "SPDK_JSONRPC_ERROR_INVALID_REQUEST " error.
## Possible Solution

If a batch request is received, create a child request and process each child request and send the responses of all the child requests to the host as one batch response. 
## Steps to Reproduce

1. Generate Batch request, by creating an array of requests and send the whole batch request to the target.
2.
3.
4.

**Comment by Rakesh-Babu-Saladi** [comment]
The above issue is solved and the patch is submitted to the community. Please follow the link
https://review.gerrithub.io/c/spdk/spdk/+/409297

**Comment by pawelwod** [comment]
@Rakesh-Babu-Saladi We are aware of your patch but since you haven't addressed all comments from previous review nor replied to them we don't know when to review it again. Pls fix all pointed issues or ask in comments if you have any doubts.

Thanks

**Comment by jimharris** [comment]
Hi @pawelwod,

Can you clarify which comments have not been addressed yet?  I see that the patch changed a lot since rev1 that you and Daniel reviewed, so it's possible that @Rakesh-Babu-Saladi has tried to address all of them.

Thanks,

-Jim

**Comment by Rakesh-Babu-Saladi** [comment]
Hi @pawelwod ,

I've addressed comments from the previous review. Please review it again and suggest/comment if any more changes needed. Thank you @jimharris for going through my patch.

Thanks,
Rakesh.

**Comment by wanqunintel** [comment]
@Rakesh-Babu-Saladi did you click the button reply to commit to the gerrithub? it seems the commit message is still too long(can be split into to two lines).

**Comment by optimistyzy** [comment]
I see the patch link was abandoned, should we close this issue?  @jimharris @tomzawadzki
