### ISSUE TITLE
compiling SPDK failed if using DPDK 18.08

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#402]
As the title, compiling spdk failed if using dpdk-18.08.
## Steps to Reproduce
1.  download DPDK-18.08, compiling it with command:
`make install T=x86_64-native-linuxapp-gcc DESTDIR=.  EXTRA_CFLAGS=-fPIC
`
2. configure SPDK with the DPDK 18.08 path.

`./configure --with-dpdk=/path/to/dpdk1808/
`
3. run make command to compile spdk.

## Expected Behavior
compiling successfully.
## Current Behavior
Compiling failed.
 ```
 CC examples/bdev/hello_world/hello_bdev.o
  LINK examples/bdev/hello_world/hello_bdev
/home/storage/dpdk-18.08/x86_64-native-linuxapp-gcc/lib/librte_eal.a(eal_common_devargs.o): In function `rte_devargs_layers_parse':
eal_common_devargs.c:(.text+0x212): undefined reference to `rte_kvargs_free'
eal_common_devargs.c:(.text+0x261): undefined reference to `rte_kvargs_parse_delim'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:51: hello_bdev] Error 1
make[2]: *** [/home/storage/spdk-latest/mk/spdk.subdirs.mk:35: hello_world] Error 2
make[1]: *** [/home/storage/spdk-latest/mk/spdk.subdirs.mk:35: bdev] Error 2
make: *** [/home/storage/spdk-latest/mk/spdk.subdirs.mk:35: examples] Error 2

```

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora 26
SPDK commit: 6ff8f60ebbe021244f6869aebd695c701ef8c915

**Comment by wanqunintel** [comment]
@liang2yan there is already effort for this and it's going to be released soon.

**Comment by jimharris** [comment]
Yes - @darsto has patches out already.  See https://review.gerrithub.io/#/c/spdk/spdk/+/422241/.

**Comment by wanqunintel** [comment]
@jimharris , as i see the patch has been merged. Shall we add the tag for it for test?

**Comment by jimharris** [comment]
Yes - please retest.

Thanks!

**Comment by WenqianZong** [comment]
I test spdk latest version with dpdk18.08 . SPDK can be compiled successful with dpdk 18.08.
