### ISSUE TITLE
Guest kernel core dump at virtio-scsi module when using SPDK

### ISSUE THREAD

**Issue by beef9999** [spdk/spdk#403]
Guest kernel core dump at virtio-scsi module, if the guest mem is larger than 8GB, running in SPDK environment.

## Expected Behavior
SPDK bootable rootfs disk + OVMF UEFI boot-loader + 8GB memory
Expected to be able to start up.

## Current Behavior
Kernel core dump
<img width="1026" alt="core dump" src="https://user-images.githubusercontent.com/4076315/44130083-5f1c8848-a07e-11e8-92cb-d4be00f0359f.png">

**However, if modify guest memory to less than 8GB, it could work out.**

## Possible Solution
UEFI boot-loader bug? Kernel bug?

## Steps to Reproduce
...

## Context (Environment including OS version, SPDK version, etc.)
Host OS: CentOS 7.5
Guest OS: CentOS 7.1
SPDK: 18.04

**Comment by pawelwod** [comment]
Can you check this issue on SPDK 18.07? What QEMU version you are using?

**Comment by beef9999** [comment]
Looks like it is just a kernel bug.
I upgrade the guest OS kernel then it disappeared.
