### ISSUE TITLE
Passthru vbdev re-created after deletion

### ISSUE THREAD

**Issue by waelhalbawi** [spdk/spdk#404]
Deletion and recreation of a bdev on-top of which a passthru vbdev was placed results in recreation of the vbdev itself.

## Expected Behavior
Recreating the underlying bdev should not recreate the vbdev, especially if the passthru vbdev was removed first.

## Current Behavior
Recreating the underlying bdev (after deletion) results in the recreation of the passthru vbdev.

## Possible Solution
After removing a passthru vbdev, remove the associated `struct bdev_names` from `g_bdev_names`. 
## Steps to Reproduce
Create a bdev and lay on top of that a passthru vbdev, then delete them in the given order:
```
dd if=/dev/zero of=/tmp/my_aio bs=512 count=2000
scripts/rpc.py construct_aio_bdev /tmp/my_aio aio 512
scripts/rpc.py construct_passthru_bdev -b aio -p pt
scripts/rpc.py delete_passthru_bdev pt
scripts/rpc.py delete_aio_bdev aio
```
Now recreate the AIO bdev:
```
scripts/rpc.py construct_aio_bdev /tmp/my_aio aio 512
```
List all bdevs:
```
scripts/rpc.py get_bdevs
```
You will also see the passthru vbdev recreated:
```
[
  {
    "num_blocks": 2048, 
    "name": "aio", 
    "claimed": true, 
    "driver_specific": {
      "aio": {
        "filename": "/tmp/my_aio"
      }
    }, 
    "supported_io_types": {
      "reset": true, 
      "nvme_admin": false, 
      "unmap": false, 
      "read": true, 
      "write_zeroes": true, 
      "write": true, 
      "flush": true, 
      "nvme_io": false
    }, 
    "qos_ios_per_sec": 0, 
    "block_size": 512, 
    "product_name": "AIO disk", 
    "aliases": []
  }, 
  {
    "num_blocks": 2048, 
    "name": "pt", 
    "claimed": false, 
    "driver_specific": {
      "passthru": {
        "base_bdev_name": "aio", 
        "pt_bdev_name": "pt"
      }
    }, 
    "supported_io_types": {
      "reset": true, 
      "nvme_admin": false, 
      "unmap": false, 
      "read": true, 
      "write_zeroes": true, 
      "write": true, 
      "flush": true, 
      "nvme_io": false
    }, 
    "qos_ios_per_sec": 0, 
    "block_size": 512, 
    "product_name": "passthru", 
    "aliases": []
  }
]
```
## Context (Environment including OS version, SPDK version, etc.)
Vagrant box running Fedora 27 - created using SPDK scripts.
Built using master - commit: 341fff63971815841f75a45df5272d6ae807f476.

**Comment by jimharris** [comment]
Hey @peluse - can you take a look at this one?

**Comment by waelhalbawi** [comment]
Submitted a patch that provides a fix: https://review.gerrithub.io/c/spdk/spdk/+/422474

**Comment by peluse** [comment]
Haha, I just pushed one also.  I'll comment on yours and if you agree and would like to update I'm happy to abandon mine. See https://review.gerrithub.io/#/c/spdk/spdk/+/422475

**Comment by peluse** [comment]
Actually they're identical minus comments.  I'll go ahead and abandon mine, thanks for fixing your own reported issue!! Awesome!

**Comment by waelhalbawi** [comment]
Thinking about the hot-removal scenario again. PT vbdev will be recreated as long as the underlying bdev has the same as in what's in `g_bdev_names` - no other checks are in place. This is not to say that the vbdev will have the wrong parameters, but I'm wondering whether the hot-removal scenario should be reconsidered.

**Comment by jimharris** [comment]
Patch has been merged.  Thanks @waelhalbawi!

**Comment by waelhalbawi** [comment]
Thanks, @jimharris! Any thoughts on my previous comment?

**Comment by jimharris** [comment]
Hi @waelhalbawi,

I don't think this is a problem.  The SPDK bdev system is setup such that the "old" PT vbdev is not removed until all open descriptors have been closed.  This means that if a "new" PT vbdev with the same name, but different parameters (blocklen, blockcnt, supported I/O types, etc.), is created later, the bdev will need to be opened again which will always trigger an evaluation of the bdev's parameters.
