### ISSUE TITLE
memory leaks occurred when kill nvmf-tgt

### ISSUE THREAD

**Issue by WenqianZong** [spdk/spdk#409]
## Expected Behavior
no error occurred when kill nvmf-tgt

## Current Behavior
memory leak happened after kill nvmf-tgt

## Steps to Reproduce

1./app/nvmf_tgt/nvmf_tgt -s 2048 -m 0x1 &
2./scripts/rpc.py construct_malloc_bdev 1024 512 -b Malloc
3./scripts/rpc.py construct_nvmf_subsystem -s SPDK0 nqn.2014-08.org.spdk:cnode1 'trtype:RDMA traddr:ip trsvcid:port' '' -a -n "Malloc"
4./examples/nvme/perf/perf -r 'trtype:RDMA adrfam:IPv4 traddr:ip trsvcid:port' -d 1024 -q 128 -s 4096 -w randread -t 20 -c 0x2 &
5 sleep 5
6 kill nvmf_tgt
7 kill perf

log:
```
app.c: 574:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
rdma.c:2203:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
rdma.c:2203:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
rdma.c:2203:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
rdma.c:2203:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
rdma.c:2203:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
rdma.c:2203:spdk_nvmf_rdma_poll_group_create: *NOTICE*: Skipping unused RDMA device when creating poll group.
profiling:/home/zong/spdk/lib/virtio/virtio_user/vhost_user.gcda:Version mismatch - expected A81R got 603R

=================================================================
==17654==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 480 byte(s) in 1 object(s) allocated from:
    #0 0x7f3fdbe30e50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x7f3fbc92df74  (/usr/lib64/libibverbs/libmlx5-rdmav16.so+0x12f74)

Indirect leak of 524288 byte(s) in 1 object(s) allocated from:
    #0 0x7f3fdbe31a60 in posix_memalign (/lib64/libasan.so.5+0xefa60)
    #1 0x7f3fbc91e4eb  (/usr/lib64/libibverbs/libmlx5-rdmav16.so+0x34eb)

SUMMARY: AddressSanitizer: 524768 byte(s) leaked in 2 allocation(s).
```
## Context (Environment including OS version, SPDK version, etc.)
Fedaro 28, spdk master 18.10-pre

**Comment by wanghailiangx** [comment]
When perf is running io, kill nvmf_tgt. Then the issue can be produced every time.

**Comment by wanghailiangx** [comment]
Due to changes in the SPDK version, there is a problem with reproducing now.
Updated steps:
3./scripts/rpc.py nvmf_subsystem_create -s SPDK0 nqn.2014-08.org.spdk:cnode1 -a 
4./examples/nvme/perf/perf -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.11.11 trsvcid:4420' -q 128 -s 4096 -w randread -t 5 -c 0x2 -o 4096

nvmf_subsystem_create which have replace construct_nvmf_subsystem can't set RDMA listen address(192.168.11.11).
So step 4 reports spdk_nvme_probe() failed for transport address '192.168.12.11'.

**Comment by jimharris** [comment]
Can this issue be closed?  Seems that maybe this issue can no longer be reproduced.
