### ISSUE TITLE
ASAN errors when using the CTRL+C to kill the NVMF target

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#410]
ASAN errors when using the CTRL+C to kill the NVMF target.
SPDK master branch with DPDK 18.02.2

## Expected Behavior
NVMF target can exit successfully.

## Current Behavior
```
Starting SPDK v18.10-pre / DPDK 18.02.2 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --file-prefix=spdk_pid1328939 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid1328939_unix
EAL: Probing VFIO support...
app.c: 574:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
^C
=================================================================
==1328939==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7fc12e55a238 in __interceptor_strdup (/lib64/libasan.so.4+0x77238)
    #1 0x4f7b05 in rte_eal_init (/home/wangchen/spdk/app/nvmf_tgt/nvmf_tgt+0x4f7b05)
    #2 0x9734d2dc25f470ff  (<unknown module>)

SUMMARY: AddressSanitizer: 5 byte(s) leaked in 1 allocation(s).
```

## Steps to Reproduce
```
1. build DPDK 18.02.2
    make install T=x86_64-native-linuxapp-gcc DESTDIR=.  EXTRA_CFLAGS=-fPIC 
2. build SPDK master branch
    ./configure --with-dpdk=../dpdk/x86_64-native-linuxapp-gcc/ --enable-asan --with-rdma
    make clean && make -j
3. ./app/nvmf_tgt/nvmf_tgt
4.  CTRL + C
```

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora release 27 (Twenty Seven)
Linux version: 4.17.3-100.fc27.x86_64
gcc version: 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
SPDK: master (commit id: da01835d84a12aa76cde2686a382d1d3984e9d6e)

**Comment by ChenWang01** [comment]
The Nvmf target can exit successfully with the SPDK master branch and the default DPDK(git submodule update --init)

**Comment by jimharris** [comment]
I think this is a known issue with DPDK upstream.  In our DPDK submodule, we have git commit d8fcc7a40 which fixes this memory leak.  Could you try applying this patch to DPDK 18.02.2 and see if it fixes this issue?

@ZiyeYang - could you submit this patch to DPDK upstream?  Then we will no longer need to maintain it in our submodule.

Thanks,

-Jim

**Comment by ChenWang01** [comment]
I have applied patch https://review.gerrithub.io/c/spdk/dpdk/+/401667 (commit d8fcc7a40 ) to the DPDK 18.02.2 and this issue can't be reproduced.

**Comment by wanqunintel** [comment]
@ZiyeYang as Jim has mentioned that this patch will fix the issue and Chen verified it works, https://review.gerrithub.io/#/c/spdk/dpdk/+/401667/, is this upstreamed to DPDK? Then we can close it.

**Comment by wanqunintel** [comment]
it seems Ziye's patch has been abandoned, can you have a look now @ZiyeYang

**Comment by ChenWang01** [comment]
I have used the SPDK master(e66d09029bf8826196fa87dabef561641387c798) branch and DPDK(18.02.2) version to verify this issue.
This issue can’t be reproduced with latest code.

**Comment by wanqunintel** [comment]
Close as issue can not reproduce
