### ISSUE TITLE
configure parameter not comfortable in NIGHTLY master test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#412]
There is an error on fedora-02 and fedora-06 in NIGHTLY master test recently.
The logs are as follows:

08:15:53	# make -C /mnt/sdbdir/spdk clean
make: Entering directory '/mnt/sdbdir/spdk'
make: Leaving directory '/mnt/sdbdir/spdk'
 08:15:58	# cd /mnt/sdbdir/spdk
08:15:58	# ./configure --enable-debug --enable-werror --with-raid --enable-coverage --enable-ubsan --with-rdma --with-pmdk --with-fio=/usr/src/fio --with-vtune=/home/sys_sgsw/vtune_codes --with-rbd --with-iscsi-initiator
Warning: the RAID module does not support multiple iovecs per request and will not work with vhost
cat: standard output: Permission denied

========== Backtrace start: ==========
in /home/sys_sgsw/build_pool/agent/repo/test/common/autotest_common.sh:433 -> run_test()
     ...
   428 		shift
   429 		echo "************************************"
   430 		echo "START TEST $test_type $@"
   431 		echo "************************************"
   432 		set -x
=> 433 		time "$@"
     ...
in ./test/iscsi_tgt/iscsi_tgt.sh:48 -> main()
     ...
   43  	if [ $RUN_NIGHTLY -eq 1 ]; then
   44  		if [ $SPDK_TEST_PMDK -eq 1 ]; then
   45  			run_test suite ./test/iscsi_tgt/pmem/iscsi_pmem.sh 4096 10
   46  		fi
   47  		run_test suite ./test/iscsi_tgt/ip_migration/ip_migration.sh
=> 48  		run_test suite ./test/iscsi_tgt/ext4test/ext4test.sh
     ...
========== Backtrace end ==========

## Expected Behavior
Creating CONFIG.local...done. And go to make.

## Current Behavior
cat: standard output: Permission denied

## Possible Solution
Check configuration of the environment.

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view https://ci.spdk.io/spdk/builds/review/1431e1d6b49edf3b3922a56a8565cc9e2faa84ae.1534852860/fedora-02/build.log
(search "cat: standard output: Permission denied")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit da01835d84a12aa76cde2686a382d1d3984e9d6e

**Comment by jimharris** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/423163 should fix this.

**Comment by wanqunintel** [comment]
@wanghailiangx , would you verify and update it?

**Comment by wanghailiangx** [comment]
I can't reproduce "cat: standard output: Permission denied" in my local server. 
But I tried to set "umask 0402" with non root user, received similar "cannot create temp file for here-document: Permission denied".  
"echo" can avoid the issue. The premise is that there is no quotation mark in the string.
After merging, if there is no error from NIGHTLY logs, we can close it.

**Comment by wanghailiangx** [comment]
This issue did not happen again in NIGHTLY TEST after that patch had been merged. It can be closed.
