### ISSUE TITLE
inconsistent contents in www.spdk.io/doc

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#413]
If you open "http://www.spdk.io/doc/pages.html", you will find 3 inconformity in pages.

## Expected Behavior
There is a consistent one-to-one match between each catalog and each page.

## Current Behavior
1. repeated “Modules” in navigation bar on the left.
▼Modules
▼Tools
▼Experimental Tools
▼Modules

2. If click "Related Page" in upper navigation bar, you will see 
▼Modules
NVMe Driver
I/OAT Driver
Virtio driver

But in left navigation bar, it shows:
▼Modules
 ▼bdev I/O Submit Functions

3. The 3 contents are in left navigation bar, but not in "Related Page" and "Main Page".
▼Modules
▼Data Structures
▼Files

In addition, Is "Related Page" repeated with "Main Page"?

## Possible Solution
Fix inconsistent links.

## Steps to Reproduce
1. open http://www.spdk.io/doc/index.html
2. open http://www.spdk.io/doc/pages.html

## Context (Environment including OS version, SPDK version, etc.)
N/A

**Comment by jimharris** [comment]
Thanks @wanghailiangx - good catch!

We have a page named "Modules", but Doxygen also uses "Modules" as a special auto-generated page.  I'll change our "Modules" to "Driver Modules" which should fix this issue.

-Jim

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/423165/ has been merged.

**Comment by wanghailiangx** [comment]
@jimharris  Great, I've seen the change in pages. About ---- 3.The 3 contents are in left navigation bar, but not in "Related Page" and "Main Page". This has not been changed. Is it not necessary? In addition, Is "Related Page" repeated with "Main Page"? Their content is the same.

**Comment by peluse** [comment]
@wanghailiangx FYI you can update doc pages too if you're so inclined... let me know if you need some guidance, or catch anyone on IRC or on the dist list

**Comment by jimharris** [comment]
@wanghailiangx - Doxygen automatically creates these three sections (Modules, Data Structures and Files).  It also automatically creates the "Main Page" and "Related Pages".  I know this is not ideal, but I'm not aware of any way to modify this without modifying Doxygen itself.

**Comment by wanghailiangx** [comment]
@peluse @jimharris OK, I tried to submit a patch to update web page. I think  Doxyfile need be updated too. But I can't find corresponding "md" files about "Modules, Data Structures and Files" in the left navigation bar.
https://review.gerrithub.io/#/c/spdk/spdk/+/423816/, please review.

**Comment by wanghailiangx** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/423816/ is abandoned, it moved to "spdk/spdk.github.io" 
https://review.gerrithub.io/#/c/spdk/spdk.github.io/+/424780/

**Comment by jimharris** [comment]
Closing based on previous comments and input from @wanghailiangx.
