### ISSUE TITLE
Compile the "hello_bdev" outside of the spdk directory

### ISSUE THREAD

**Issue by xxks-kkk** [spdk/spdk#416]
## Expected Behavior

I'm expecting to able to compile and run "hello_bdev" program outside of the spdk directory.

## Current Behavior

I'm new to the SPDK library and I want to simulate the scenario that writing a program using the block device abstraction layer API. I think the good first step is to use the `hello_bdev` under `spdk/examples/bdev/hello_world` abd directly compile it outside the SPDK directory and link against the installed library. 

I use the CMake to compile the code

```
cmake_minimum_required(VERSION 2.8)
project(rustfs)

set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/CMakeModules)

# SPDK_DIR should point to the install location of the SPDK library
set(SPDK_DIR $ENV{SPDK_DIR})
if (NOT SPDK_DIR)
  message(SEND_ERROR "SPDK_DIR not found into the environment")
else ()
  message(STATUS "SPDK_DIR = $ENV{SPDK_DIR}")
endif ()

# Setup the basic C Compiler flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} \
        -Wall \
        -Wextra \
        -Wno-unused-parameter \
        -Wno-missing-field-initializers \
        -Wmissing-declarations \
        -fno-strict-aliasing \
        -Wformat \
        -Wformat-security \
    ")

# include the SPDK API headers
include_directories(${SPDK_DIR}/include)

# CMake version of spdk_lib_list_to_files defined in spdk.common.mk of SPDK repo
function(spdk_lib_list_to_files LIBS SPDK_LIB_LIST)
  # We convert a list of SPDK lib names to the corresponding file names
  set(ARG_NUM 1)
  while (ARG_NUM LESS ${ARGC})
    set(arg ${ARGV${ARG_NUM}})
    MESSAGE(STATUS "name: ${arg}")
    LIST(APPEND FileNames ${SPDK_DIR}/lib/libspdk_${arg}.a)
    math(EXPR ARG_NUM "${ARG_NUM}+1")
  endwhile()
  set(${LIBS} "${FileNames}" PARENT_SCOPE)
endfunction(spdk_lib_list_to_files)

# link to the SPDK libraries
link_directories( ${SPDK_DIR}/lib )

add_executable(hello_bdev
  hello_bdev.c
  )

spdk_lib_list_to_files(LIBS
  event_bdev
  event_copy
  bdev
  copy
  event
  thread
  util
  conf
  trace
  log
  jsonrpc
  json
  rpc)

MESSAGE(STATUS ${LIBS})
link_directories(${SPDK_DIR}/lib)
target_link_libraries(hello_bdev
  -Wl,--start-group
  ${LIBS}
  -Wl,--end-group)
```

and I compile `bdev_hello.c` by running 

```
export SPDK_DIR=/home/zeyuanhu/spdk_install
cmake . && make
```
I got several undefined references error from the static libraries that I link with:

```
Scanning dependencies of target hello_bdev
[ 50%] Building C object CMakeFiles/hello_bdev.dir/hello_bdev.c.o
[100%] Linking C executable hello_bdev
/home/zeyuanhu/spdk_install/lib/libspdk_bdev.a(bdev.o): In function `spdk_bdev_mgmt_channel_create':
/home/zeyuanhu/spdk/lib/bdev/bdev.c:551: undefined reference to `spdk_mempool_get'
/home/zeyuanhu/spdk_install/lib/libspdk_bdev.a(bdev.o): In function `spdk_bdev_mgmt_channel_destroy':
/home/zeyuanhu/spdk/lib/bdev/bdev.c:581: undefined reference to `spdk_mempool_put'
/home/zeyuanhu/spdk_install/lib/libspdk_bdev.a(bdev.o): In function `spdk_bdev_mgr_unregister_cb':
/home/zeyuanhu/spdk/lib/bdev/bdev.c:812: undefined reference to `spdk_mempool_count'
/home/zeyuanhu/spdk/lib/bdev/bdev.c:813: undefined reference to `spdk_mempool_count'
/home/zeyuanhu/spdk/lib/bdev/bdev.c:818: undefined reference to `spdk_mempool_count'
/home/zeyuanhu/spdk/lib/bdev/bdev.c:819: undefined reference to `spdk_mempool_count'
/home/zeyuanhu/spdk/lib/bdev/bdev.c:825: undefined reference to `spdk_mempool_count'
<--- snip --->
```

Inside `spdk_install`, I have `bin`, `include`, and `lib` which generates from `make install` of SPDK library.

I see the `Makefile` shipped with the `hello_bdev.c` is quite complicated and I'm not sure whether I have to link all those libraries?

Can you please shed some lights on what's the recommend way to compile the `hello_bdev.c` outside the SPDK library? What' the minimum requirement to compile the library?

Thanks much!

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

OS version: 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

SPDK version: Installed 3 days ago. Not sure how to check the version.

**Comment by pelplinski** [comment]
There might be more dependencies in spdk libraries. 
Have you tried adding `--whole-archive spdk` to `target_link_libraries` ?

**Comment by pelplinski** [comment]
I think that what you did is the best solution for now. You have to specify each module you want to link with.
However, we do have trello card for to simplify this in the future: https://trello.com/c/FvRM0GVi/108-add-build-support-for-out-of-tree-bdev-modules

**Comment by pawelwod** [comment]
There is work-in-progress about fixing such link problems but I'm afraid that patches might be ready after release.
