### ISSUE TITLE
create_vbox.sh script fails on ubuntu 18.04 because pushd isn't an sh command

### ISSUE THREAD

**Issue by habeanf** [spdk/spdk#420]
## Expected Behavior
Calling spdk/scripts/vagrant/create_vbox.sh <distro> should create a <distro> subdirectory and set up the vm

## Current Behavior
The script fails with:
spdk/scripts/vagrant/create_vbox.sh: 147: spdk/scripts/vagrant/create_vbox.sh: pushd: not found

## Possible Solution
Change #/bin/sh to #/bin/bash because 'pushd' on line 147 isn't an sh command (or don't use pushd)

## Steps to Reproduce
1. Run spdk/scripts/vagrant/create_vbox.sh ubuntu18

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 18.04, SPDK v18.07 (commit 716ad0e3)

**Comment by peluse** [comment]
Thanks Amir.  Is this something you'd like to push a fix for?

**Comment by habeanf** [comment]
Sure but I can't test on anything other than linux. I'm not sure if the solution is indeed switching to bash. Would it work on mac and windows+shell variants?

**Comment by peluse** [comment]
I'm not really sure, maybe we get rid of all the pushd and popd and just cd "cd" and "cd -" I think that works everywhere, I just used cd - in a recent script

**Comment by jimharris** [comment]
Agree - let's just use cd and cd -.

**Comment by johnmeneghini** [comment]
Yes, we want create_vbox.sh to support mac and windows.  The original implementation supported both of these platforms as that’s what I implemented and tested it on.  Bash is assumed by these two platforms.

See:  https://github.com/spdk/spdk/blob/master/scripts/vagrant/README.md

**Comment by johnmeneghini** [comment]
Before we do that, I’d like to understand the problem.  What’s the platform that you are trying to create a virtual box on?   Mac OSX, Windows, or Linux?  create_vbox.sh does assume bash, but it works fine with OSX and Git-bash.

/John

**Comment by johnmeneghini** [comment]
Amir, are you trying to run create_vbox.sh on a Linux platform or is your laptop/pc running OSX/Windows?

**Comment by habeanf** [comment]
@jimharris I was on the 18.07 branch. I can verify that on commit https://github.com/spdk/spdk/commit/48629a88f9731aab450a1a86f52703caaf3f2385 the issue is fixed on ubuntu 18.04. Thanks guys!

A side comment (because I don't know where else to put this):
In the file [spdk/scripts/vagrant/README.md](https://github.com/spdk/spdk/blob/master/scripts/vagrant/README.md) , lines 155-156 have commands to run after vagrant sets up the vm and spdk was compiled. Line 155 works but Line 156 does not. There needs to first be a `cd examples/bdev/hello_world/` before running `sudo ./hello_bdev` otherwise the example won't find the conf file. For the uninitiated trying to play around with spdk it can take some time to figure this out, as following the README.md ends in an example that fails to run only because it wasn't executed in the right directory.

**Comment by johnmeneghini** [comment]
Yes, I was just looking at commit 48629a8.  I think the problem was that my original script, which was designed to work on a native, vanilla OSX installation, wanted to remove any dependency on bash. This was originally a /bin/sh script.

See the comments at: 

https://review.gerrithub.io/#/c/spdk/spdk/+/414861/7/scripts/vagrant/README.md@24

So, I agree, that for the sake of supporting all possible platforms, we should remove pushd, or anything else that can't be supported by /bin/sh from this script.

I think we want create_vbox.sh to be platform neutral.

**Comment by habeanf** [comment]
@johnmeneghini @jimharris I'm confused.. do you want a commit that switches back to `#/bin/sh` and uses `cd`/`cd -` instead of `pushd`?

**Comment by jimharris** [comment]
@johnmeneghini @habeanf 

I'm fairly certain that MacOS comes with bash.  The comment above was for gnu-getopt - we certainly don't want to force MacOS users to have to install that.

I'm OK with reverting back to /bin/sh if someone wants to submit a patch for that.

**Comment by johnmeneghini** [comment]
Let’s just stick with what’s on the master branch for now.  I will retest everything on my OSX and Windows platforms to be sure there isn’t a regression anywhere.

Thanks for using create_vbox.sh!  I’m interested in any bugs or improvements you find.

/John

**Comment by johnmeneghini** [comment]
Jim, I’ll re-test things on my two OSX machines before we make any changes here.

/John

**Comment by jimharris** [comment]
Thanks @johnmeneghini.

@habeanf - I've pushed a patch to fix the doc - thanks for the report!
https://review.gerrithub.io/#/c/spdk/spdk/+/423931/

**Comment by habeanf** [comment]
I just realized spdk uses gerrithub for community code contribution. I'll close my PR, @johnmeneghini since you're working on it I won't submit to gerrithub. @jimharris thanks
