### ISSUE TITLE
vhost timeout while waiting in NIGHTLY master test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#422]
vhost reports timeout error while waiting for response in NIGHTLY master test everyday.

## Expected Behavior
vhost pass all test.

## Current Behavior
Error log as bellow,
========== Backtrace start: ==========
in /home/sys_sgsw/build_pool/agent/repo/test/vhost/../../test/common/autotest_common.sh:433 -> run_test()
     ...
   428 		shift
   429 		echo "************************************"
   430 		echo "START TEST $test_type $@"
   431 		echo "************************************"
   432 		set -x
=> 433 		time "$@"
   434 		set +x
   435 		echo "************************************"
   436 		echo "END TEST $test_type $@"
   437 		echo "************************************"
   438 		set -x
     ...
in ./test/vhost/spdk_vhost.sh:87 -> main()
     ...
   82  			--fio-job=$WORKDIR/common/fio_jobs/default_performance.job
   83  			report_test_completion "vhost_perf_blk"
   84  			;;
   85  		-m|--migration)
   86  			echo 'Running migration suite...'
=> 87  			run_test case $WORKDIR/migration/migration.sh -x \
   88  			--fio-bin=$FIO_BIN --os=$VM_IMAGE --test-cases=1,2
   89  			;;
   90  		-i|--integrity)
   91  			echo 'Running SCSI integrity suite...'
   92  			run_test case $WORKDIR/fiotest/autotest.sh -x --fio-bin=$FIO_BIN \
     ...
========== Backtrace end ==========

## Possible Solution
The virtual machine did not shut down automatically in 30 seconds, resulting in the super time error.

## Steps to Reproduce
1. view  https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view  https://ci.spdk.io/spdk/builds/review/7dfa061f569a6c37ffb44757ec89a2d89d8459a3.1535630441/fedora-08/build.log
(all search "Backtrace start")

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: 8166215677ca26b85cbb91b79107314df31a832b

**Comment by pawelwod** [comment]
@nedved1 is currently investigating this issue. For now I seam that from time to time some service in guest OS is taking more time to shut down so the whole VM takes more time to shutdown.

**Comment by wanqunintel** [comment]
@pawelwod i add nedved as the owner then. thanks.

**Comment by jimharris** [comment]
I have invited @nedved1 to become a member of the SPDK project.  Once he accepts, we can assign this issue to him.

**Comment by nedved1** [comment]
Timeout while closing the virtual machines appears quite randomly. Still working on this issue.

**Comment by liang2yan** [comment]
@nedved1 , any patch link about this issue?

**Comment by pawelwod** [comment]
I checked logs provided by @nedved1 and there is something wrong with systemd during shutdown. All failures have simmilar scheme:

```
[   45.479521] systemd[1376]: Received SIGTERM from PID 1 (systemd). 
...
irqbalance.service: Changed running -> stop
         Stopping LSB: daemon to balance interrupts for SMP systems...
session-2.scope changed running -> stop-sigterm
         Stopping Session 2 of user root.  
...
session-2.scope: Stopping timed out. Killing.
session-2.scope changed stop-sigterm -> failed
[  135.533124] systemd-logind[1017]: Got messa 
...
Powering off.
[  137.884798] reboot: Power down
```

The `session-2.scope`  (what ever this scope contains) is hanging. After timeout (90s) it is killed by `systemd` and poweroff complete with max 10s. It is possible that the hanging session contains our own `shutdown` command but this need to be verified.

There is a patch from @nedved1  https://review.gerrithub.io/#/c/spdk/spdk/+/426585 But this is really drastic solution to use `--force`. We can also add 'pkill --signal HUP sshd` to shutdown command to make sure we have all ssh session terminated but I would like to have `systemctl poweroff` working.

Another wokaround we can try is to change `TimeoutStopSec` option for systemd to eg 10s.
@nedved1  Can you check these solutions?

**Comment by nedved1** [comment]
Thank You @pawelwod  for Your help, but adding 'pkill --signal HUP sshd' to poweroff command didn't helped. Changing TimeoutStopSec  to 10 seconds worked and vms are closing within time limit.

**Comment by nedved1** [comment]
Patch for fixing this issue: https://review.gerrithub.io/#/c/spdk/spdk/+/427715/
Abandoning: https://review.gerrithub.io/#/c/spdk/spdk/+/426585

**Comment by nedved1** [comment]
@wanghailiangx, could we close this issue?

**Comment by wanghailiangx** [comment]
@nedved1 OK, thank you for your patch. The issue did not reproduce again.
