### ISSUE TITLE
CI:  Add build(s) with '--with-shared' to the test pool

### ISSUE THREAD

**Issue by lhoswdev** [spdk/spdk#426]
## Expected Behavior
To maximize test coverage on new patches and avoid the risk of breakage when using SPDK shared libs, add a build with the configure option, '--with-shared'.

## Current Behavior
Unless a developer tests '--with-shared' in their own local repo, patch submissions may result in build breaks when linking with SPDK shared libraries.

## Context (Environment including OS version, SPDK version, etc.)
We probably should do this on both a Linux flavor and FreeBSD.

**Comment by xuhuagen** [comment]
@lhoswdev  Inmy  local spdk repo, it is ok that build with the configure option, '--with-shared' on both a Linux flavor and FreeBSD.
can you list the log of  building breaks when linking with SPDK shared libraries?

**Comment by lhoswdev** [comment]
During the final linking step of executables, e.g. 
```  LINK examples/bdev/hello_world/hello_bdev
/home/lghartma/src/gerrithub/spdk/spdk/build/lib/libspdk_bdev.so: undefined reference to `_spdk_trace_record'
/home/lghartma/src/gerrithub/spdk/spdk/build/lib/libspdk_bdev.so: undefined reference to `g_trace_histories'
collect2: error: ld returned 1 exit status
make[3]: *** [hello_bdev] Error 1
make[2]: *** [hello_world] Error 2
make[1]: *** [bdev] Error 2
make: *** [examples] Error 2
```

@jimharris has a set of patches that address the build break.   See: https://review.gerrithub.io/#/c/spdk/spdk/+/424721/

**Comment by jimharris** [comment]
Just to note - this bug is not tracking the link failure.  @lhoswdev added it to make sure we add --with-shared testing in the test pool(s).  So please do not close this issue after my patches have been merged.  It should only be closed once @Seth5141 or @karlatec or someone else confirms that we have --with-shared testing enabled somewhere.

**Comment by Seth5141** [comment]
I have uploaded a patch on top of yours to add a shared lib build. https://review.gerrithub.io/c/spdk/spdk/+/424888

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/424890/ has been merged.
