### ISSUE TITLE
SPDK iSCSI crashes with large block workload

### ISSUE THREAD

**Issue by alantu02** [spdk/spdk#428]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

The configuration is as such:
                SPDK v18.07
                16 Optane drives with 8 partitions each on the target
                2 Mellanox ConnectX-4 50GbE dual ported NIC
                2 initiators targeting 64 LUNs each
                64 iSCSI connections per initiator
 
Workload is:
                64K sequential, rd/wr/mix, Q32, 1 thread per mount point

With large block 64K workloads via FIO, SPDK crashes with segfault on the target and the initiators start losing connections.

## Expected Behavior
SPDK iscsi_tgt remains stable and FIO workload performance is at expected level based on system configuration.

## Current Behavior
At start of workload the target system begins to output error messages and eventually ends in segfault (See attached log).
[SPDK_crash.txt](https://github.com/spdk/spdk/files/2359064/SPDK_crash.txt)

## Steps to Reproduce
1. Start iscsi_tgt
2. iSCSI discovery on initiator
3. Start large block workload on initiator
4. Monitor target node terminal for error messages

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 17.10
kernel 4.13.0-16-generic
SPDK v18.07
fio-3.3-22-g702b

**Comment by liang2yan** [comment]
@alantu02 , how many port group(i.e, the socket listening address) you used? I think you used two port group. So one initiator connected to iscsi target using one port group. Another initiator used another port group.

**Comment by jimharris** [comment]
Fix for this was merged today.

On Sep 7, 2018, at 3:20 PM, alantu02 <notifications@github.com<mailto:notifications@github.com>> wrote:


@liang2yan<https://github.com/liang2yan> Each initiator has a dual ported NIC, so 2 connections from each to the target. Each connection is on it's own subnet, so there are 4 PortalGroups being used.

**Comment by liang2yan** [comment]
@alantu02 , can you try with latest codes?

**Comment by alantu02** [comment]
The latest updates fixed this bug as reported for 64K workloads. This can be closed.
