### ISSUE TITLE
Failed to run hello_bdev.c again if kill the program right after spdk_bdev_get_io_channel

### ISSUE THREAD

**Issue by xxks-kkk** [spdk/spdk#430]
I'm playing around with `hello_bdev.c` program. I accidentally kill the process after the program runs into the phase that output `Opening io channel` onto the stdout. Then, I re-run the program and I keep getting the following failure:

```
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 --legacy-mem --file-prefix=spdk_pid357 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid357/mp_socket
EAL: No free hugepages reported in hugepages-2048kB
EAL: No free hugepages reported in hugepages-1048576kB
EAL: FATAL: Cannot get hugepage information.
EAL: Cannot get hugepage information.
Failed to initialize DPDK
app.c: 498:spdk_app_setup_env: *ERROR*: Unable to initialize SPDK env
/home/zeyuanhu/rustfs/examples/hello_nvme_bdev/hello_nvme_bdev.c: 272:main: *ERROR*: ERROR starting application
```

I've tried `sudo scripts/setup.sh reset` and `sudo scripts/setup.sh`. Then I run the program again and I still hit the same error. To me, the issue might due to some resources are already allocated but never got reclaimed. I'm wondering how can I fix this issue?

## Context (Environment including OS version, SPDK version, etc.)

SPDK 18.07
Ubuntu 16.04 LTS

**Comment by xxks-kkk** [comment]
I think this issue might link with #349 and #350 But, I'm not sure what to do in my case. Do I have to restart the machine to fix this issue?

**Comment by pelplinski** [comment]
That happens when spdk app crashes and does not clean hugepage files.

Go to `/dev/hugepages` and remove all huge pages that belong to your application (starting with prefix, in your example `--file-prefix=spdk_pid357`). Usually during development all the hugepages belong to your application.

If you delete all hugepage files in this directory, the HugePages_Free should be equal to HugePages_Total:

[root@wp ~]# cat /proc/meminfo |grep HugePages
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:    4096
HugePages_Free:     4096
HugePages_Rsvd:        0
HugePages_Surp:        0

**Comment by xxks-kkk** [comment]
@pelplinski Thanks for your reply. I went to `/dev/hugepages`, I see nothing there and I have the following when run the command:

```
$ cat /proc/meminfo |grep HugePages
AnonHugePages:   2592768 kB
ShmemHugePages:        0 kB
HugePages_Total:    2560
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:      512
```

I also tried to run the example program again and it will still fail:

```
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 --legacy-mem --file-prefix=spdk_pid1640 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid1640/mp_socket
EAL: No free hugepages reported in hugepages-2048kB
EAL: No free hugepages reported in hugepages-1048576kB
EAL: FATAL: Cannot get hugepage information.
EAL: Cannot get hugepage information.
Failed to initialize DPDK
app.c: 498:spdk_app_setup_env: *ERROR*: Unable to initialize SPDK env
/home/zeyuanhu/rustfs/examples/hello_nvme_bdev/hello_nvme_bdev.c: 272:main: *ERROR*: ERROR starting application
```

**Comment by jimharris** [comment]
Hi Zeyuan,

Can you make sure the first invocation of the app isn’t still running the background?

-Jim

**Comment by xxks-kkk** [comment]
@jimharris  Hello Jim, Tried `ps aux | grep -i hello` and  `pgrep -la hello`. Didn't find any suspicious process. Do you have any commands available to help with detecting the hidden app process?

Thanks!

**Comment by jimharris** [comment]
No - I think that means the process is not still running.

Is /dev/hugepages your only hugetlbfs mount?

mount | grep hugetlbfs

**Comment by jimharris** [comment]
Hmmm.  I'm at a loss.  You could try unmounting /dev/hugepages and see if it gives any hints.  Or unmounting /dev/hugepages may free the hugepages.

**Comment by xxks-kkk** [comment]
Hello Jim,

Tried to unmount the device but it shows it is busy

```
$ sudo umount hugepages/
umount: /dev/hugepages: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
```

Tried `fuser -m /dev/hugepages` but it shows nothing. I use `sudo umount -l /dev/hugepages/` to forcely unmount the device. However, after issuing `cat /proc/meminfo |grep HugePages`, I can still see

```
AnonHugePages:   2596864 kB
ShmemHugePages:        0 kB
HugePages_Total:    2560
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:      512
```

**Comment by xxks-kkk** [comment]
Hello Jim,

It turns out if I unmount the `/dev/hugepages` and reboot the machine, I need to rerun `sudo scripts/setup.sh` to start over. I can solve my issue for now. However, there are nothing left in the `/dev/hugepages` looks weird to me. I'm wondering if that's because I check `/dev/hugepages` several hours after the program crash.

**Comment by pelplinski** [comment]
@xxks-kkk Do you still replicate the issue or was it one time event?

**Comment by xxks-kkk** [comment]
Hello @pelplinksi, I haven't replicated the issue. I rebooted the machine to solve the problem. I'll close this issue for now.

**Comment by xfliu2665** [comment]
> @xxks-kkk Do you still replicate the issue or was it one time event?

 i got a questions when running dpdk about huge pages(may have nothing to do with dpdk).  when dpdk-app stopped for some reasons, the huge pages obtained by it before may won't be freed. and from then on, dpdk-app can't run again for no huge pages available unless you increase nr_hugepages.  what's more,  i can't free the 'disappeared' huge pages through manual writing huge-page fs.  take a look at my operations below
# echo 0 > /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
# cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/surplus_hugepages
6
# cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/nr_hugepages
6
it seems the huge-pages are still hold by dpdk, but i can't find why. i have tried some ways but none of them works
remove the dpdk running path at /var/run/dpdk
umount huge-page and delete the mounted dir
and i found the write-operation for nr_hugepages is ok(i test it with kretprobe),does't take effect however
