### ISSUE TITLE
SPDK_DEBUGLOG definition

### ISSUE THREAD

**Issue by cranechu** [spdk/spdk#433]
https://github.com/spdk/spdk/blob/ea1c15791fc760e07c8e9cd4629fe17dc0ddb1a1/include/spdk_internal/log.h#L83

Should it be SPDK_LOG_DEBUG?

**Comment by peluse** [comment]
Sure looks that way to me... would you like to submit a patch?

**Comment by jimharris** [comment]
Good catch!

**Comment by ak-gh** [comment]
Not exactly related, but it would be helpful if release builds avoid printing (essentially debugging) source code reference along with the message. Should I raise the respective issue?

Regards,
Andrey

**Comment by liang2yan** [comment]
@cranechu , can you  add the patch link here?. thanks.

**Comment by benlwalker** [comment]
Merged as commit 4e58b2544
