### ISSUE TITLE
Encountering deadlock while calling rpc method construct_vhost_blk_controller

### ISSUE THREAD

**Issue by sochinpub** [spdk/spdk#437]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Deadlock occurs when calling rpc 'construct_vhost_blk_controller', maybe in accompany with vm rebooting.
The stack follows:

Thread 3 (Thread 0x2b5b99d0b700 (LWP 79167)):
0 0x00002b5b99841d73 in epoll_wait () from /lib64/libc.so.6
1 0x000055b78aba6ed2 in eal_intr_thread_main ()
2 0x00002b5b99535dc5 in start_thread () from /lib64/libpthread.so.0
3 0x00002b5b9984179d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x2b5b9a70e700 (LWP 20942)):
0 0x00002b5b9953b79b in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
1 0x00002b5b9953b82f in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
2 0x00002b5b9953b8cb in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
3 0x000055b78ab827ae in spdk_vhost_event_send.constprop.5 ()
4 0x000055b78ab82c35 in stop_device ()
5 0x000055b78ab982c0 in vhost_user_msg_handler ()
6 0x000055b78ab9678f in vhost_user_read_cb ()
7 0x000055b78ab9a2bf in fdset_event_dispatch ()
8 0x00002b5b99535dc5 in start_thread () from /lib64/libpthread.so.0
9 0x00002b5b9984179d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x2b5b98b28cc0 (LWP 78706)):
0 0x00002b5b9953c1bd in __lll_lock_wait () from /lib64/libpthread.so.0
1 0x00002b5b99537d02 in _L_lock_791 () from /lib64/libpthread.so.0
2 0x00002b5b99537c08 in pthread_mutex_lock () from /lib64/libpthread.so.0
3 0x000055b78ab87f9a in spdk_vhost_blk_construct ()
4 0x000055b78ab84a6f in spdk_rpc_construct_vhost_blk_controller ()
5 0x000055b78ab88746 in spdk_jsonrpc_parse_request ()
6 0x000055b78ab88e01 in spdk_jsonrpc_server_poll ()
7 0x000055b78ab95138 in _spdk_reactor_run ()
8 0x000055b78ab9559c in spdk_reactors_start ()
9 0x000055b78ab94335 in spdk_app_start ()
10 0x000055b78ab57b65 in main ()

## Expected Behavior

Construct a vhost blk(scsi) controller successfully.

## Current Behavior

Deadlock occurs(stack shows above).

## Possible Solution

Don't know yet.

## Steps to Reproduce

Call rpc method 'construct_vhost_blk_controller' while rebooting the vm.

**Comment by ChenWang01** [comment]
@sochinpub 
Hi,
I have tried to reproduce this issue in my location, but it's failed. Can you post the detail steps for us to reproduce it? Thanks so much for your effort.
Following is my steps, please check it, thanks.
```
1. ./app/vhost/vhost
2. ./rpc.py construct_nvme_bdev -b "nvme0" -t "PCIe" -a "0000:81:00.0"
3. ./rpc.py construct_nvme_bdev -b "nvme1" -t "PCIe" -a "0000:03:00.0"
4. ./rpc.py construct_vhost_blk_controller vhost.0 nvme0n1
5. ./qemu/build/x86_64-softmmu/qemu-system-x86_64 -cpu host -smp 8 -m 1024 \
    -object memory-backend-file,id=mem,size=1G,mem-path=/dev/hugepages,share=on \
    -numa node,memdev=mem -drive file=/ubuntu-fio2_18.qcow2,if=none,id=disk \
    -device ide-hd,drive=disk,bootindex=0 -net user,hostfwd=tcp::10020-:22 -net nic \
    -chardev socket,id=char0,path=spdk/vhost.0 -device vhost-user-blk-pci,chardev=char0  \
    --enable-kvm
6. login into VM and reboot
7. ./rpc.py construct_vhost_blk_controller vhost.1 nvme1n1
```
The blk controller can create successfully, and  can login into the VM after reboot.

**Comment by sochinpub** [comment]
@ChenWang01 
em...My version is 18.01(82b4abc), but I think the master branch still has this problem unfixed.
Indeed, It's hard to reoccur. I know exactly now what's the problem, so I actually reproduce this problem by add a 'sleep' in the source code as following:

In **lib/vhost/vhost.c**:
static void 
stop_device(int vid) 
 { 
 	struct spdk_vhost_dev *vdev; 
 	struct rte_vhost_vring *q; 
 	int rc; 
 	uint16_t i; 
 

 	**pthread_mutex_lock(&g_spdk_vhost_mutex);** 
 	vdev = spdk_vhost_dev_find_by_vid(vid); 
**+        sleep(10)**
  	rc = spdk_vhost_event_send(vdev, vdev->backend->stop_device, 3, "stop device"); 
        ...
        ...

Before 'spdk_vhost_event_send' called, 'spdk_vhost_blk_construct' is called by rpc in primary thread:

**spdk_rpc_construct_vhost_blk_controller->spdk_vhost_blk_construct**

and this thread trying to get lock **g_spdk_vhost_mutex** by calling **spdk_vhost_lock** as following:

int 
spdk_vhost_blk_construct(const char *name, const char *cpumask, const char *dev_name, bool readonly) 
  { 
 	struct spdk_vhost_blk_dev *bvdev = NULL; 
 	struct spdk_bdev *bdev; 
 	int ret = 0; 
 
 
  	**spdk_vhost_lock();** 
 	bdev = spdk_bdev_get_by_name(dev_name); 
        ...


 This is what happens according to my analysis， hope it helps.

**Comment by darsto** [comment]
Thanks for the report, I see a potential deadlock here,
Thread 2 waits for a vhost controller to complete its pending I/O, but the I/O is probably polled on the Thread 1, which also handles the RPC.

**Comment by darsto** [comment]
Long ago I pushed an rfc patch to fix this issue, although it introduces another deadlock on shutdown:
https://review.gerrithub.io/c/spdk/spdk/+/396577

This needs some more work.

**Comment by darsto** [comment]
Well, this is a mess. Before we perform the cleanup, we shall upstream the patch I linked before:
https://review.gerrithub.io/c/spdk/spdk/+/396577
It solves this (major) deadlock for now, but introduces another issue:

Thread 1:
* start shutdown
   * rte_vhost_driver_unregister()
      * stop_device()
        * wait for all pending I/O

Thread 2:
 * *VM reboots*
   * stop_device() -> stopping the device again; will likely segfault.
