### ISSUE TITLE
build fails against DPDK 18.05 installed rpm's

### ISSUE THREAD

**Issue by lhoswdev** [spdk/spdk#440]
## Expected Behavior
Should be able to install the DPDK 18.05 (and it's devel) rpm's against which we can build the SPDK.

## Current Behavior
Unresolved symbols when linking:

```
LINK examples/bdev/hello_world/hello_bdev
lib/env_dpdk/init.c:121: undefined reference to `eal_get_runtime_dir'
```

## Possible Solution

Comment from Jim during IRC chat on this topic:
```
09/19 [11:07:07]  <@jimharris>	could you add a note to look at using the DPDK --huge-unlink option?  we could add this option to rte_eal_init if opts->shm_id < 0 and !opts->hugepage_single_segments
09/19 [11:07:24]  <@jimharris>	see lib/env_dpdk/init.c@402
```

## Steps to Reproduce

1.  Install dpdk and dpdk-devel (version 18.05) rpm's
2.  Run ``configure --with-dpdk`` to point to ``/usr/share/dpdk/x86_64-default-linuxapp-gcc``
3. ``make``, and observe build failure.

 An ``objdump -t`` or ``readelf -s `` against the /usr/lib64/librte_eal.so.7`` fails to find the ``eal_get_runtime_dir`` symbol.

## Context (Environment including OS version, SPDK version, etc.)

SPDK master (hash:  87eacb6829b53edf4347d8dba88c88eb02394fc6)
DPDK 18.05.1

**Comment by jimharris** [comment]
The primary issue is that eal_get_runtime_dir() is not exported by the DPDK shared library or the DPDK public header files.  We worked around this in lib/env_dpdk/init.c by declaring the function locally.  This works OK with static libraries but doesn't for shared libraries.

**Comment by lhoswdev** [comment]
It would be nice if when we update the SPDK to use a newer version of the DPDK that we could also test against the DPDK shared-libs -- not just the static ones as we currently do.   @Seth5141

**Comment by darsto** [comment]
Thanks for the report!
I pushed a fix/workaround - https://review.gerrithub.io/c/spdk/spdk/+/426218

**Comment by lhoswdev** [comment]
@darsto I cherry-picked your patch and built against DPDK 18.05 rpm's that I had installed, and verified it was linked against DPDK shared obj's so it looks good!

**Comment by karlatec** [comment]
Fixed by Darek
