### ISSUE TITLE
bdev 'raid0' not found in NIGHTLY master test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#442]
iscsi_tgt/fio.sh reports conf file error in NIGHTLY master test everyday.

In fedora-06 server:
= = = = = = = = = = = = = = = = = = = =
iSCSI target running config
= = = = = = = = = = = = = = = = = = = =
[TargetNode-1]
Comment "Target-1"
TargetName iqn.2016-06.io.spdk:Target3
TargetAlias "iqn.2016-06.io.spdk:Target3"
Mapping PortalGroup1 InitiatorGroup2
AuthMethod None
AuthGroup None
UseDigest Auto
LUN0 raid0
QueueDepth 64

ERROR: === BACKTRACE START ===
dev.c: 130:spdk_scsi_dev_add_lun: ERROR: device iqn.2016-06.io.spdk:Target3: cannot find bdev 'raid0' (target 0)

This issue can be reproduced in local server.

## Expected Behavior
iscsi_tgt/fio.sh passed.

## Current Behavior
iscsi_tgt/fio.sh failed with generated conf file.

## Possible Solution
No corresponding Raid options generated in configuration file.

## Steps to Reproduce
1.view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2.view https://ci.spdk.io/spdk/builds/review/d4db15db8a1ba5a2ac8e07a092c08b745ba11391.1537274055/fedora-06/build.log
(search "Backtrace start")

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: f8d0f6d6ccddc0dac44f49b8cd927d0379faf922

**Comment by shuhei-matsumoto** [comment]
To re-enable running_config test, a little more work will be needed. I enabled once but disabled again in revision 2 of the patch.

**Comment by wanghailiangx** [comment]
@shuhei-matsumoto Once you re-enable running_config test in fio.sh, please give a link of patch here, thanks. Then this issue will be closed now, do you think so?

**Comment by wanghailiangx** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/426199/ This patch disabled running_config test temporarily.

**Comment by wanghailiangx** [comment]
@shuhei-matsumoto this issue does not occur again. Shall we close it, or set low bug label?

**Comment by liang2yan** [comment]
@shuhei-matsumoto , do you have any plan or patch to re-enable the running_config testing?

**Comment by shuhei-matsumoto** [comment]
@liang2yan 

As Karol said in the patch, https://review.gerrithub.io/#/c/spdk/spdk/+/426199/, .INI config file has been deprecated and we should port this test to JSON config file.

It will be possible now because RAID bdev have supported JSON configuration.

I'll post the patch later.

-Shuhei

**Comment by liang2yan** [comment]
@shuhei-matsumoto , have you submitted the patch link?

**Comment by shuhei-matsumoto** [comment]
@liang2yan 
Sorry for my late reply.
https://review.gerrithub.io/#/c/spdk/spdk/+/433200/ is the patch.
Please close this issue.

**Comment by wanghailiangx** [comment]
Thanks Shuhei's patch.
