### ISSUE TITLE
cannot use "=" in transport id along with a PCIe address containing ":" when calling `spdk_nvme_transport_id_parse()`

### ISSUE THREAD

**Issue by tchaikov** [spdk/spdk#443]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

in e02d0bbd5f5c4952ce3175202311cc65842dc43b,  `spdk_nvme_transport_id_parse()` is allowed to parse trid with `=` as separator of keyvals.  but if `trtype=PCIe traddr=0000:00:0e.0` is passed to this function. it fails.

## Expected Behavior

`spdk_nvme_transport_id_parse()` parses the given trid just fine. and if it fails to do so, `-EINVAL` should be returned.

## Current Behavior

`spdk_nvme_transport_id_parse()` fails to parse `trtype=PCIe traddr=0000:00:0e.0`, with following errro message:

```
nvme.c: 799:spdk_nvme_transport_id_parse: *ERROR*: Unknown transport ID key 'trtype=PCIe traddr=0000'
```
and `0` is returned.

## Possible Solution
```c
const char *seps = ":=";
const char *separator;
const char *s = NULL;
for (separator = seps; *separator != '\0'; separator++) {
  for (s = str; *s != '\0';) {
    s += strspn(s, whitespace);
    sep = strchr(s, *separator);
    // ....
    if (strcasecmp(key, "trtype") == 0) {
    // ...
    }
  }
}
if (*separator == '\0') {
  SPDK_ERRLOG("Unknown transport ID key '%s'\n", key);
  return -EINVAL;
}
```
## Steps to Reproduce

```
examples/nvme/identify/identify -r "trtype=PCIe traddr=0000:00:0e.0"
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK: 33ed49d2e9994f29fdd11835879d11eed7e13fee

**Comment by jimharris** [comment]
The patch from @optimistyzy has been merged, so I am closing this issue.

@tchaikov - please report if you still see any problems.
