### ISSUE TITLE
How to stack 2 physical nvme (bdev) devices into one single logical volume?

### ISSUE THREAD

**Issue by repu1sion** [spdk/spdk#446]
Doc clearly says, there are "Facilities to stack block devices to create complex I/O pipelines".
But if lvol_store should be created only on selected block device. And it contains all logical volumes. It seems that we can easily create few smaller virtual bdevs on bigger physical one.
But what If I have 2 physical nvme drives. How should I stack them into one single logical volume? (if this is possible)

**Comment by jimharris** [comment]
Hi,

SPDK recently added a RAID-0 (striping) module.  See lib/bdev/raid.  This would allow you to stripe the 2 NVMe namespaces together into one larger bdev - then put the logical volume store on top of that.

Note that currently the RAID-0 module does not do on-disk metadata.  Meaning that information about the RAID volume will need to be loaded by config file.

Regards,

-Jim

**Comment by repu1sion** [comment]
Thanks Jim! That helped a lot!
But one more question.

After creating raid device, can I just open it and work with it as with common bdev device?

For example:
struct raid_bdev_config *raid_cfg = raid_bdev_config_find_by_name(RAID_DEVICE);
struct spdk_bdev *bd = &raid_cfg->raid_bdev->bdev;
rv = spdk_bdev_open(bd, 1, NULL, NULL, &desc);
struct spdk_io_channel *ch = spdk_bdev_get_io_channel(desc);
rv = spdk_bdev_write(desc, ch, ...);

**Comment by peluse** [comment]
Yup, that’s the cool thing about virtual bdevs, interact with all of them the same way… I’m sure you’ve seen the basic example for red/write a bdev/vbdev, exact steps are all in there…   https://github.com/spdk/spdk/tree/master/examples/bdev/hello_world

**Comment by repu1sion** [comment]
anyway, when I call the sequence above I have a segfault like this:
```
Core was generated by `./bdev_odp_raid'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000045f465 in spdk_bdev_open (bdev=0x2739010, write=write@entry=true, remove_cb=remove_cb@entry=0x0, remove_ctx=remove_ctx@entry=0x0, _desc=_desc@entry=0x6a1900 <pls_thread+64>) at bdev.c:3412
3412		TAILQ_INSERT_TAIL(&bdev->internal.open_descs, desc, link);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libaio-0.3.109-13.el7.x86_64 libatomic-4.8.5-28.el7_5.1.x86_64 libconfig-1.4.9-5.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libibverbs-43mlnx1-1.44207.x86_64 libnl3-3.2.28-4.el7.x86_64 libpcap-1.5.3-11.el7.x86_64 libuuid-2.23.2-52.el7.x86_64 numactl-libs-2.0.9-7.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x000000000045f465 in spdk_bdev_open (bdev=0x2739010, write=write@entry=true, remove_cb=remove_cb@entry=0x0, remove_ctx=remove_ctx@entry=0x0, _desc=_desc@entry=0x6a1900 <pls_thread+64>) at bdev.c:3412
#1  0x00000000004065ce in init_thread (arg=0x6a18c0 <pls_thread>) at bdev_odp_raid.c:902
#2  0x00007f4917afae25 in start_thread () from /lib64/libpthread.so.0
#3  0x00007f4917824bad in clone () from /lib64/libc.so.6
(gdb) print bdev
$1 = (struct spdk_bdev *) 0x2739010
(gdb) show bdev
Undefined show command: "bdev".  Try "help show".
(gdb) print bdev->internal
$2 = {qos = 0x0, qos_mod_in_progress = false, mutex = {__data = {__lock = 1, __count = 0, __owner = 16534, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, 
    __size = "\001\000\000\000\000\000\000\000\226@\000\000\001", '\000' <repeats 26 times>, __align = 1}, status = SPDK_BDEV_STATUS_INVALID, claim_module = 0x0, unregister_cb = 0x0, unregister_ctx = 0x0, open_descs = {tqh_first = 0x0, 
    tqh_last = 0x0}, link = {tqe_next = 0x0, tqe_prev = 0x0}, reset_in_progress = 0x0, qd_poller = 0x0, period = 0, temporary_queue_depth = 0, measured_queue_depth = 0, io_time = 0, weighted_io_time = 0, stat = {bytes_read = 0, 
    num_read_ops = 0, bytes_written = 0, num_write_ops = 0, read_latency_ticks = 0, write_latency_ticks = 0, ticks_rate = 0}}
(gdb) print desc
$3 = (struct spdk_bdev_desc *) 0x7f48c8000940
(gdb) print link
$4 = {<text variable, no debug info>} 0x7f49178172f0 <link>
```
any ideas why it could fail during inserting desc into bdev->internal.open_descs ?

**Comment by repu1sion** [comment]
ok, nvm about last segfault. I found the issue.

**Comment by nufosmatic** [comment]
> ok, nvm about last segfault. I found the issue.

Are you gonna share?

**Comment by Saigut** [comment]
Doesn't SPDK has a concept like LVM？
