### ISSUE TITLE
Checking file permissions cause failed in NIGHTLY master test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#451]
"Checking file permissions..." has some problems which merged on 10/6.
This error occurs on all fedora servers.

Logs as bellow:
 08:02:53	$ ./scripts/check_format.sh
Checking file permissions...ERROR: test/spdkcli/iscsi.sh is marked executable but does not start with a shebang.
Checking coding style... OK
Checking comment style... OK
Checking for spaces before tabs... OK
Checking trailing whitespace in output strings... OK
Checking for use of forbidden library functions... OK
Checking for use of forbidden CUnit macros... OK
Checking blank lines at end of file... OK
Checking for POSIX includes... OK
Checking Python style... OK
Checking whether CHANGELOG.md should be updated... OK
  08:03:07	$ trap - ERR
  08:03:07	$ print_backtrace
  08:03:07	$ [[ ehxBE =~ e ]]
  08:03:07	$ local shell_options=ehxBE
  08:03:07	$ set +x
========== Backtrace start: ==========
in /home/sys_sgsw/build_pool/agent/repo/autobuild.sh:30 -> main()
     ...
   25  	
   26  	timing_enter autobuild
   27  	
   28  	timing_enter check_format
   29  	if [ $SPDK_RUN_CHECK_FORMAT -eq 1 ]; then
=> 30  		./scripts/check_format.sh

## Expected Behavior
check_format.sh passed.

## Current Behavior
check_format.sh failed.

## Possible Solution
fix "Checking file permissions..."

## Steps to Reproduce
1. cd SPDK root dir.
2. run ./scripts/check_format.sh
3. or view NIGHTLY test log from 10/6.
https://review.gerrithub.io/#/c/spdk/spdk/+/393768/.
https://ci.spdk.io/spdk/builds/review/6050cc99f7117f6e70c467528d2b804d9cc0feb4.1538827232/fedora-01/build.log
(search "Backtrace start")

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: a8780177c66ba137302a3f3166303542c340a119

**Comment by optimistyzy** [comment]
https://review.gerrithub.io/428314

**Comment by wanghailiangx** [comment]
The above patch fixed it. The problem is in test/spdkcli/iscsi.sh.
