### ISSUE TITLE
"Checking file permissions..." of check_format.sh does not take effect in Fedora25 and CentOS

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#452]
In check_format.sh:
echo -n "Checking file permissions..."
while read -r perm _res0 _res1 path; do
	if [ ! -f "$path" ]; then
		continue
	fi
......
done <<< $(git grep -I --name-only --untracked -e . | git ls-files -s)

In Fedora25, “check_format” always enter "continue"(skipped), then print a false "OK".

Logs as bellow:
In Fedora25,
[root@waikikibeach34 spdk]# while read -r perm _res0 _res1 path; do echo $path
> done <<< $(git grep -I --name-only --untracked -e . | git ls-files -s)
.astylerc 100755 c0b4612461de3e72484844bfe88effe85b4c6eb4 0 .githooks/pre-commit 100755 cb9efb5bfc08348a27abddec97257ffdee91e604 0 .githooks/pre-push 100644 4eaebdc8b12eb7698592b48a331736cc02ca3f11 0 .gitignore 100644 f1d223b711d289faad0b75a44f84c17b3994b6f7 0 .gitmodules 100644 9cebfc6ec4f4d1c21b900e168d42f28501bf5f66 0 .travis.yml 100644

So “check_format” think [ ! -f "$path" ] is always true.

But in Fedora26,
[root@waikikibeach4 spdk]# while read -r perm _res0 _res1 path; do echo $path
> done <<< $(git grep -I --name-only --untracked -e . | git ls-files -s)
.astylerc
.gitignore
.gitmodules
.travis.yml
CHANGELOG.md
CONFIG
CONTRIBUTING.md
LICENSE
Makefile
README.md
app/Makefile
app/iscsi_tgt/.gitignore
app/iscsi_tgt/Makefile
app/iscsi_tgt/iscsi_tgt.c

## Expected Behavior
check_format.sh can take effect in Fedora25 and Fedora26.

## Current Behavior
check_format.sh does not take effect in Fedora25, but work well in Fedora26.

## Possible Solution
Fix "Checking file permissions..." 

## Steps to Reproduce
1. cd  SPDK root dir.
2. run ./scripts/check_format.sh

## Context (Environment including OS version, SPDK version, etc.)
SPDK Change-Id: a8780177c66ba137302a3f3166303542c340a119

**Comment by chenlo2x** [comment]
Please try this patch: https://review.gerrithub.io/#/c/spdk/spdk/+/428332/

**Comment by jimharris** [comment]
Thanks!  I added some more detail to the commit message - explaining why these changes were needed, especially since the test pool passes without them.  I've added my +2 and we will merge once another +2 is added.

**Comment by wanghailiangx** [comment]
Thank Jim for added commit message. The above patch has been merged and resolved the issue.
