### ISSUE TITLE
vhost/spdk_vhost.sh reports stack-buffer-overflow in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#455]
Logs as bellow:
12:32:18 echo -e 'INFO: Running Migration test case 2'
INFO: Running Migration test case 2
......
12:32:28 /home/sys_sgsw/build_pool/agent/repo/test/vhost/common/../../..//scripts/rpc.py -s /home/sys_sgsw/build_pool/agent/vhost0/rpc.sock construct_nvme_bdev -b Nvme0 -t rdma -f ipv4 -a 192.168.100.8 -s 4420 -n nqn.2016-06.io.spdk:cnode1
......
==515028==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd75dd2b30 at pc 0x000000779435 bp 0x7ffd75dd29f0 sp 0x7ffd75dd29e0
......
 12:32:33 fail 'failed to kill nvmf_tgt app'
......
========== Backtrace start: ==========
in ./test/vhost/spdk_vhost.sh:88 -> main()
     ...
   83  			--fio-job=$WORKDIR/common/fio_jobs/default_performance.job
   84  			report_test_completion "vhost_perf_blk"
   85  			;;
   86  		-m|--migration)
   87  			echo 'Running migration suite...'
=> 88  			run_test case $WORKDIR/migration/migration.sh -x \
......
in /home/sys_sgsw/build_pool/agent/repo/autotest.sh:191 -> main()
     ...
   186 			timing_enter integrity_lvol_blk_nightly
   187 			run_test suite ./test/vhost/spdk_vhost.sh --integrity-lvol-blk-nightly
   188 			timing_exit integrity_lvol_blk_nightly
   189 	
   190 			timing_enter vhost_migration
=> 191 			run_test suite ./test/vhost/spdk_vhost.sh --migration

## Expected Behavior
vhost/spdk_vhost.sh pass

## Current Behavior
vhost/spdk_vhost.sh failed

## Possible Solution
Research root cause of stack-buffer-overflow.

## Steps to Reproduce
1. cd SPDK dir
2. run test/vhost/spdk_vhost.sh --migration
3. or view  https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
https://ci.spdk.io/spdk/builds/review/3ba5ea908781fc5ad311d81bae0b7022ad7b5c51.1539172863/fedora-08/build.log
(search "Backtrace start")

## Context (Environment including OS version, SPDK version, etc.)
commit:  5c263046dbe68dc0cbf5ea40957c534ff15970df

**Comment by darsto** [comment]
A fix was merged today - https://review.gerrithub.io/c/spdk/spdk/+/428693 (Merged as 5d5181d ): nvme/rdma: fix a stack-buffer-overflow error

**Comment by darsto** [comment]
I believe this can be closed. Thanks for reporting!

**Comment by wanghailiangx** [comment]
Thank you for pasting out patch's link.
