### ISSUE TITLE
RPC CMD "list_nvme_device -t namespace" with NVMe-of hadn't output 

### ISSUE THREAD

**Issue by WenqianZong** [spdk/spdk#459]
When use rpc cmd "list_nvme_device -t namespace" with NVMe-of, it hadn't output corresponding data.
## Expected Behavior
Use cmd "list_nvme_device -t namespace" will output namespace data.
{
  "device_names": [
    "Nvme0n1"
  ]
}
## Current Behavior
Use rpc cmd "list_nvme_device -t namespace" with NVMe-of, it hadn't output .
{
  "device_names": []
}

## Steps to Reproduce
1.git pull https://review.gerrithub.io/spdk/spdk refs/changes/94/419094/9
2../configure --with-rdma 
3../app//nvmf_tgt/nvmf_tgt
4../script/rpc.py construct_nvme_bdev -b "nvme0" -t "PCIe" -a "0000:81:00.0"
5../script/rpc_py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
6../script/rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 nvme0n1
7../script/rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.1 -s 4420
8../script/rpc_py list_nvme_device -t namespace

## Context (Environment including OS version, SPDK version, etc.)
fedora28 
4.16.3-301.fc28.x86_64
patch: https://review.gerrithub.io/spdk/spdk refs/changes/94/419094/9

**Comment by ChenWang01** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/419094 
The patch has changed the "list_nvme_devices" method to be “get_nvme_controllers” . And it only list available nvme controller and related transport ID. 
We can used the "get_bdevs" rpc method to get the namespace information.
