### ISSUE TITLE
Wrong judgement about vfio availability

### ISSUE THREAD

**Issue by wuzhouhui** [spdk/spdk#462]
`scripts/setup.sh` bind nvme device to uio, but vhost-target think vfio is available, and cause initialization of nvme device failed.

## Expected Behavior
Vhost-target think vfio is unavailable and works as usual.

## Current Behavior
Initialization of nvme device failed and vhost-target app stuck.

## Possible Solution
spdk (or dpdk) and `scripts/setup.sh` should determine the availability of vfio based on same condition

## Steps to Reproduce
1. moprobe vfio vfio_iommu_type1 vfio_pci
2. Start vhost-target by `./vhost -g -c vhost.conf`

## Outputs of vhost-target
```
./vhost -g -c vhost.conf 
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: vhost --no-shconf -c 0x1 -m 1024 --single-file-segments --legacy-mem --file-prefix=spdk_pid15962 ]
EAL: Detected 64 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid15962/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
app.c: 602:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 703:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 490:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
EAL: PCI device 0000:b1:00.0 on NUMA socket 1
EAL:   probe driver: 8086:2701 spdk_nvme
Cannot update DMA mapping, error 22
```
## Outputs of scripts/setup.sh
```
0000:b1:00.0 (8086 2701): nvme -> uio_pci_generic
```
## Outputs of `lsmod | grep vfio`
```
vfio_pci               41312  0 
vfio_iommu_type1       22300  0 
vfio                   32695  2 vfio_iommu_type1,vfio_pci
irqbypass              13503  2 kvm,vfio_pci
```

## Context (Environment including OS version, SPDK version, etc.)

spdk: f0cb7b871ec
OS: CentOS 7.3 with kernel 3.10.0-862.11.6.el7.x86_64
vhost.conf:
```
[Nvme]
  TransportID "trtype:PCIe traddr:0000:b1:00.0" Nvme0
[VhostBlk0]
  Name vhost.0
  Dev Nvme0n1
```

**Comment by ChenWang01** [comment]
scripts/setup.sh:
We can find the function in the line 166
```
function configure_linux_pci {
driver_name=vfio-pci
if [ -z "$(ls /sys/kernel/iommu_groups)" ]; then

     # No IOMMU. Use uio.
     driver_name=uio_pci_generic
 fi
...
}
```
we will use the "uio_pci_generic" when the "/sys/kernel/iommu_groups" file does not exist.

vhost app:
We can find the define in the "spdk/lib/env_dpdk/vtophys.c" file line 48.
And use the define "SPDK_VFIO_ENABLED" in line 523, when start the vhost app.

```
ifdef FreeBSD
define SPDK_VFIO_ENABLED 0
else
include <linux/version.h>
/ DPDK versions before 17.11 don't provide a way to get VFIO information in the public API,
and we can't link to internal symbols when built against shared library DPDK, so disable VFIO entirely in that case.
*/

if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 6, 0) && \
(RTE_VERSION >= RTE_VERSION_NUM(17, 11, 0, 3) || !defined(RTE_BUILD_SHARED_LIB))
define SPDK_VFIO_ENABLED 1
```
The vfio will be disabled when the system is FreeBSD or the linux kernel version less than 3.6.0.

**Comment by wuzhouhui** [comment]
I see Darek has submitted patch https://review.gerrithub.io/c/spdk/spdk/+/432518, and this patch works for me.
