### ISSUE TITLE
Cannot start spdk app

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#463]
Cannot start spdk app if configure spdk with --with-shared flag.

## Expected Behavior
Can run vhost.

## Current Behavior
./app/vhost/vhost: error while loading shared libraries: libspdk_vhost.so.1: cannot open shared object file: No such file or directory

## Possible Solution
None

## Steps to Reproduce
1. ./configure --enable-debug --enable-werror --enable-coverage --enable-ubsan --enable-asan --with-rdma --with-pmdk --with-iscsi-initiator --with-shared 
2. make
3. app/vhost/vhost

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 16.04

**Comment by WenqianZong** [comment]
I can reproduce this issue on fedora 28. Following is error log:
`./app/vhost/vhost: error while loading shared libraries: libspdk_vbdev_lvol.so.1: cannot open shared object file: No such file or directory`

**Comment by wuzhouhui** [comment]
The dynamic librasy (*.so) should be put on certain library, so they can be found on runtime. So you can resolve issue by:
    a. make install before start spdk app
or
    b. add directory that contains spdk *.so into /etc/ld.so.conf, run ldconfig. Then, the spdk app can be started.

**Comment by wuzhouhui** [comment]
If you don't want to install shared library or change /etc/ld.so.conf, you can run spdk app by `LD_LIBRARY_PATH=build/lib/ ./app/vhost/vhost`

**Comment by WenqianZong** [comment]
I use following command to setup vhost successful:
1.  ./configure --enable-debug --enable-werror --enable-coverage --enable-ubsan --enable-asan --with-rdma --with-pmdk --with-iscsi-initiator --with-shared 
2.   make && make DESTDIR=~ install && ldconfig -v -n ~/usr/local/lib 
3.   export LD_LIBRARY_PATH=~/usr/local/lib 
4.   ./app/vhost/vhost

**Comment by pawelkax** [comment]
I use this commands:
1. ./configure --enable-debug --enable-werror --enable-coverage --enable-ubsan --enable-asan --with-rdma --with-pmdk --with-iscsi-initiator --with-shared
2. make && ldconfig -v -n ./build/lib
3. LD_LIBRARY_PATH=./build/lib/ ./app/vhost/vhost

**Comment by wanqunintel** [comment]
@pawelkax , would you try with Wenqian's step with addition of make DESTDIR=~ install, she can successfully load spdk with the steps above.

**Comment by xuhuagen** [comment]
@pawelkax  compile spdk with --with-shared flag. The steps as below:
```
1 ./configure--with-shared
2. make && make DESTDIR=~ install && ldconfig -v -n ./build/lib
3. LD_LIBRARY_PATH=./build/lib/ ./app/vhost/vhost
```
if you can start spdk app success, this issue can be closed.

**Comment by pelplinski** [comment]
> I use this commands:
> 
> 1. ./configure --enable-debug --enable-werror --enable-coverage --enable-ubsan --enable-asan --with-rdma --with-pmdk --with-iscsi-initiator --with-shared
> 2. make && ldconfig -v -n ./build/lib
> 3. LD_LIBRARY_PATH=./build/lib/ ./app/vhost/vhost

@pawelkax I build spdk with commands you mentioned and vhost is working fine
My OS is Fedora 27,  commit 2772d86c23148d3cd575b1c814584fa0946acc0d

**Comment by peluse** [comment]
@pelplinski do you knowif those steps are documented anywhere?

**Comment by pawelwod** [comment]
@peluse @pelplinski 
Is `make `__install__ required for "shared" build? I think you can have your setup polluted from previous "make install" but this is only my guess.

**Comment by pelplinski** [comment]
> @pelplinski do you knowif those steps are documented anywhere?
I haven't seen it anywhere besides this github issue. I can update documentation tomorrow.


> @peluse @pelplinski
> Is `make `**install** required for "shared" build? I think you can have your setup polluted from previous "make install" but this is only my guess.

Ok, I actually did:
```
# git clean -xf

# git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
# ./configure --enable-debug --enable-werror --enable-coverage --enable-ubsan --enable-asan --with-rdma --with-pmdk --with-iscsi-initiator --with-shared
Using default SPDK env in /home/ppelplin/git/spdk/lib/env_dpdk
Using default DPDK in /home/ppelplin/git/spdk/dpdk/build
Creating mk/config.mk...done.
Type 'make' to build.
# make
...
# ldconfig -v -n ./build/lib
# sudo LD_LIBRARY_PATH=./build/lib/ ./app/vhost/vhost
Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: vhost --no-shconf -c 0x1 -m 1024 --legacy-mem --file-prefix=spdk_pid40920 ]
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 602:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 703:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 490:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0

```

So, I think that `make install` is not required for shared build.

**Comment by pelplinski** [comment]
@peluse 
https://review.gerrithub.io/c/spdk/spdk/+/430538

**Comment by pawelkax** [comment]
This command is working:
sudo LD_LIBRARY_PATH=./build/lib/ ./app/vhost/vhost
