### ISSUE TITLE
Missing target uninstall

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#464]
There should be possibility to uninstall spdk

## Expected Behavior
Can run: make uninstall

## Current Behavior
make: *** No rule to make target 'uninstall'.  Stop.

## Possible Solution
None

## Steps to Reproduce
1. ./configure --enable-debug --enable-werror --enable-coverage --enable-ubsan --enable-asan --with-rdma --with-pmdk --with-iscsi-initiator --with-shared
2. make && make install
3. make uninstall

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 16.04

**Comment by pelplinski** [comment]
@pawelkax Do you have any thoughts on approach we should take here?

1. We can track files generated during make install (like install_manifest.txt generated with cmake)
But what, if install_manifest.txt is missing (for example due to git clean -xf)?
2. We can delete all files based on current dependencies in makefile. 
This might be generate problems if user tries to uninstall older spdk with newer commit

**Comment by pawelwod** [comment]
I vote for 2. 
This is not `yum remove` command so `make uninstall` should only undo `make install` with the same source version and the same build configuration.

**Comment by jimharris** [comment]
Agree that #2 is the best option.

**Comment by pelplinski** [comment]
I posted a RFC [patch,](https://review.gerrithub.io/c/spdk/spdk/+/431471) but still have to figure out few things. Feel free to post suggestions.

**Comment by darsto** [comment]
Bug scrub: @pelplinski please provide details what still needs to be done.

**Comment by pelplinski** [comment]
Tests, that I ran show that those targets are not executed and therefore files are not deleted. It looks like they were not in the .PHONY list.

Creating multiple targets for files located outside of spdk directory creates a problem - how to add all of them to .PHONY list?

**Comment by darsto** [comment]
Note that I haven't looked at the code yet, I'm just posting some suggestions.

Could we add some dummy dependency on all those per-file targets? Then for the uninstall we can touch just that single dependency and all the per-file targets will be executed automatically.

**Comment by pawelkax** [comment]
I created RFC patch as proposal for this issue: https://review.gerrithub.io/#/c/spdk/spdk/+/431471/

**Comment by pawelkax** [comment]
I uploaded new patch set in 431471. RFC tag was removed from commit message, so that test was started for this feature.

**Comment by jimharris** [comment]
Patch merged.
