### ISSUE TITLE
rbd: make rbd config file optional

### ISSUE THREAD

**Issue by pohly** [spdk/spdk#468]
Right now, constructing an RBD BDev only allows specifying the rbd pool. All other configuration options are expected to be in one of the rbd config files:
https://github.com/spdk/spdk/blob/master/lib/bdev/rbd/bdev_rbd.c#L98-L114

This is problematic when trying to create BDevs for different RBD clusters, because the config file would have to be modified before each `construct_rbd_bdev` call.

## Expected Behavior

* `construct_rbd_bdev` should allow arbitrary key/value config pairs
* If at least one is specified, `bdev_rados_context_init` should skip reading any config file and configure via these key/value pairs instead.

The rationale here is that it keeps the old behavior while giving RPC clients who want that full control over the configuration without side effects from a local config file (which might have been created for something else entirely!).

## Current Behavior

Config file must exist.

**Comment by pohly** [comment]
I can prepare a patch, but some guidance whether such a patch would be accepted would be nice.

**Comment by jimharris** [comment]
Hi Patrick,

This seems like a good - even required - addition to the RBD driver.  Please move forward with your proposal.

From your perspective as a user of this interface, would passing a path to a config file be sufficient?  This would certainly be simpler to implement within SPDK, but would require you to put your key/value pairs in a file, specify the file path to SPDK, and then delete this file afterwards.  If you are proxying these RPCs from a remote system, passing the key/value pairs themselves over RPC would certainly be easier as well.  Just wanted to get your opinion on that.

-Jim

**Comment by pohly** [comment]
Jim Harris <notifications@github.com> writes:
> This seems like a good - even required - addition to the RBD driver.  Please move forward with your proposal.
>
> From your perspective as a user of this interface, would passing a
> path to a config file be sufficient?  This would certainly be simpler
> to implement within SPDK, but would require you to put your key/value
> pairs in a file, specify the file path to SPDK, and then delete this
> file afterwards.  If you are proxying these RPCs from a remote system,
> passing the key/value pairs themselves over RPC would certainly be
> easier as well.  Just wanted to get your opinion on that.

The call will be local, so a file would work. But I think passing all
information as part of the JSON parameters would be cleaner and less
work on the client side of the RPC interface (at least when using
something higher-level than C).

Is there some support code in spdk for passing maps via JSON? That's
what we have here.

**Comment by jimharris** [comment]
SPDK has support for parsing arrays of JSON objects (see spdk_json_decode_array).  But I'm not sure we have any examples of arrays with arbitrary names for strings.  Adding @pawelwod - he's one of our JSON-RPC experts.  Pawel - can you give Patrick some guidance here?

**Comment by pawelwod** [comment]
Hi @pohly,

> Is there some support code in spdk for passing maps via JSON?

I'm not an expert in RBD so need to ask what kind of maps you want to pass over RPC? If this is just JSON object of "key: values" series it is easy to do. Check this patch https://review.gerrithub.io/#/c/spdk/spdk/+/430433/ You can pick this patch as starting point.

`


`

**Comment by pohly** [comment]
pawelwod <notifications@github.com> writes:

> Hi @pohly,
>
>> Is there some support code in spdk for passing maps via JSON?
>
> I'm not an expert in RBD so need to ask what kind of maps you want to
> pass over RPC?

Arbitrary key/value pairs of strings. In other words, I don't want to
enumerate the valid keys in SPDK, because all it needs to do is pass
them through to rados_conf_set().

> If this is just JSON object of "key: values" series it
> is easy to do. Check this patch
> https://review.gerrithub.io/#/c/spdk/spdk/+/430433/ You can pick this
> patch as starting point.

That shows how to add certain config values.

I have something working that supports arbitrary key/value pairs. I'll
submit a PR soon.

**Comment by pohly** [comment]
"Patrick Ohly" <patrick.ohly@intel.com> writes:
> I have something working that supports arbitrary key/value pairs. I'll
> submit a PR soon.

Please see https://review.gerrithub.io/c/spdk/spdk/+/430460

**Comment by pawelwod** [comment]
@pohly See my comments to this patch

**Comment by pawelwod** [comment]
Can somone take a look at this patch? https://review.gerrithub.io/c/spdk/spdk/+/430460

**Comment by jimharris** [comment]
430460 has been merged, so closing this issue.
