### ISSUE TITLE
nvme reports parameters errors in NIGHTLY Test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#471]
test/nvmf/nvme_cli/nvme_cli.sh reports errors:

 08:22:28	# ./nvme discover -t rdma -a 10.0.2.15 -s 4420
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --legacy-mem --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: lcore 8 unavailable
EAL: invalid coremask
EAL: FATAL: Invalid 'command line' arguments.
EAL: Invalid 'command line' arguments.
Failed to initialize DPDK
EAL: memzone_reserve_aligned_thread_unsafe(): No more room in config
nvme.c: 314:nvme_driver_init: *ERROR*: primary process failed to reserve memory
*ERROR*: === BACKTRACE START ===
*ERROR*:   1: nvme_driver_init() at 0x4bf05e
*ERROR*:   2:  spdk_nvme_connect() at 0x4c1737
*ERROR*:   3:   nvme_spdk_nvmf_connect() at 0x473a8c
*ERROR*:   4:    fdiscover() at 0x44b54a
*ERROR*:   5:     discover_cmd() at 0x40ac4e
*ERROR*:   6:      handle_plugin() at 0x4508b0
*ERROR*: === BACKTRACE END ===
spdk_nvme_connect() failed

 08:22:28	# ./nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 10.0.2.15 -s 4420
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --legacy-mem --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: lcore 8 unavailable
EAL: invalid coremask
EAL: FATAL: Invalid 'command line' arguments.
EAL: Invalid 'command line' arguments.
Failed to initialize DPDK
EAL: memzone_reserve_aligned_thread_unsafe(): No more room in config
nvme.c: 314:nvme_driver_init: *ERROR*: primary process failed to reserve memory
*ERROR*: === BACKTRACE START ===
*ERROR*:   1: nvme_driver_init() at 0x4bf05e
*ERROR*:   2:  spdk_nvme_connect() at 0x4c1737
*ERROR*:   3:   nvme_spdk_nvmf_connect() at 0x473a8c
*ERROR*:   4:    fconnect() at 0x44bc7a
*ERROR*:   5:     connect_cmd() at 0x40abec
*ERROR*:   6:      handle_plugin() at 0x4508b0
*ERROR*: === BACKTRACE END ===
spdk_nvme_connect() failed

## Expected Behavior
nvme_cli.sh passed

## Current Behavior
nvme_cli.sh reports errors

## Steps to Reproduce
1. cd SPDK dir
2. run ./test/nvmf/nvme_cli/nvme_cli.sh
3. or view https://ci.spdk.io/spdk/builds/review/628a8e5e1bfa50da328815f469821b95d5970111.1539777703/fedora-06/build.log (search BACKTRACE START)

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 83b1102f7b0ffe8b0356157614507135a66f6c86

**Comment by jimharris** [comment]
There are two bugs here - not just the failure that you've reported, but also that nvme_cli.sh does not recognize this as a failure!

See http://spdk.intel.com/public/spdk/builds/review/e91464674eef9430c6d967c7b76ad81caa54d273.1540296064/

fedora-06 has this failure, but it's reported as a Pass.

**Comment by wanghailiangx** [comment]
08:22:28	# ./nvme discover -t rdma -a 10.0.2.15 -s 4420
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --legacy-mem --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: lcore 8 unavailable
EAL: invalid coremask
EAL: FATAL: Invalid 'command line' arguments.
EAL: Invalid 'command line' arguments.
Failed to initialize DPDK

but also print:
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  10.0.2.15
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
(./nvme discover -t rdma -a 10.0.2.15 -s 4420)

./nvme return 0 , so trap can't  capture ERR here.

**Comment by Comphix** [comment]
I will take a look at this.

**Comment by Comphix** [comment]
For above discover not caught error from failed DPDK initialization, I've raised the patch at https://review.gerrithub.io/#/c/spdk/nvme-cli/+/431258/

Please have a try, thanks.

**Comment by wanghailiangx** [comment]
Thanks Cao Gang. Your patch is to fix issue that nvme_cli.sh does not recognize this as a failure.
I have raised a patch to fix another issue: EAL parameters errors
https://review.gerrithub.io/#/c/spdk/nvme-cli/+/431262/

**Comment by jimharris** [comment]
Relevant patches have been merged to fix this issue.
