### ISSUE TITLE
The contents should be updated in the "https://spdk.io/roadmap/"

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#475]
The SPDK 18.07 version has been released and the SPDK 18.10 version will come, So we should update the contents on the "ROADMAP" label in the "https://spdk.io/roadmap/" website.

## Expected Behavior

```
Version 18.10 (planned for October 2018)
Planned Features:
..
..
..

Version 18.07 (July 2018)
v18.07 release
Features:
..
..
..
```

## Current Behavior
```
Version 18.07 (planned for July 2018)
Planned Features:

Improved SPDK memory management
Full JSON-based Configuration
Encryption bdev
NVMe-oF target improvements
Spec compliance work
Multi-path support
Namespace change notification
QoS: Read, Write, and Bandwidth Rate Limiting
NVMe
Experimental Open Channel SSD support
Error injection
Multi-process timeout handling
iSCSI initiator optimizations
SPDKCLI

```
## Possible Solution
Update the website "https://spdk.io/roadmap/".

## Steps to Reproduce

1.  Go to https://spdk.io/roadmap/
2.
3.
4.

**Comment by darsto** [comment]
Bug scrub: Let's drop spdk.io/roadmap page entirely - we can make the button on the top point to trello directly..

**Comment by jimharris** [comment]
@benlwalker - this looks like a good one for you to tackle in 5 minutes on a Friday afternoon.  :-)

**Comment by benlwalker** [comment]
https://review.gerrithub.io/c/spdk/spdk.github.io/+/445948

**Comment by jimharris** [comment]
Patch merged.  Thanks @benlwalker!
