### ISSUE TITLE
rpc_client reports AIO error in NIGHTLY Test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#476]
START TEST SUITE test/rpc_client/rpc_client.sh
......
vbdev_passthru.c: 603:vbdev_passthru_register: *NOTICE*: created pt_bdev for: TestPT
bdev_aio.c:  90:bdev_aio_open: *ERROR*: open() failed (file:/tmp/aiofile), errno 2: No such file or directory
bdev_aio.c: 539:create_aio_disk: *ERROR*: Unable to open file /tmp/aiofile. fd: -1 errno: 2
bdev_aio.c: 702:bdev_aio_initialize: *ERROR*: Unable to create AIO bdev from file /tmp/aiofile
 08:05:40	# trap 'killprocess 245092' SIGINT SIGTERM EXIT
 08:05:40	# /home/sys_sgsw/build_pool/agent/repo/test/rpc_client/rpc_client_test

In addition, rpc_client.sh does not recognize this as a failure!
fedora-06 has this failure, but it's reported as a Pass.

## Expected Behavior
created pt_bdev for: TestPT passed.

## Current Behavior
create_aio_disk: *ERROR*: Unable to open file /tmp/aiofile

## Possible Solution
set [AIO] files or remove [AIO] lines in bdev.conf.in.
[AIO]
  AIO /dev/ram0 AIO0
  AIO /tmp/aiofile AIO1 2048

## Steps to Reproduce
1. cd SPDK dir
2. run ./test/rpc_client/rpc_client.sh
3. or view https://ci.spdk.io/spdk/builds/review/628a8e5e1bfa50da328815f469821b95d5970111.1539777703/fedora-06/build.log  (search "bdev_aio_open: *ERROR*")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 83b1102f7b0ffe8b0356157614507135a66f6c86

**Comment by pawelwod** [comment]
AIO and bdev_svc is not needed in this test. It will be fixed when https://review.gerrithub.io/#/c/spdk/spdk/+/430316/ is merged.

**Comment by wanghailiangx** [comment]
Thanks a lot for prompt reply.

**Comment by optimistyzy** [comment]
I think this issue is related with the AIO destination file, we do provide a correct file location. Maybe in some system,  /tmp/aiofile is not existing.

**Comment by wanghailiangx** [comment]
Thanks pawelwod's patch, now the issue doesn't occur in NIGHTLY test.
As Ziye said, if we create the aio device by ourselves,  we will also not see this issue. 
Definitely, we need to put aio device in bdev conf if we are not using rpc to create.
