### ISSUE TITLE
spdk_vhost reports GPT Primary MBR size error in NIGHTLY Test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#478]
START TEST SUITE ./test/vhost/spdk_vhost.sh --integrity-lvol-scsi-nightly
......
  08:26:11	# /home/sys_sgsw/build_pool/agent/repo/test/vhost/common/../../..//scripts/rpc.py -s /home/sys_sgsw/build_pool/agent/vhost0/rpc.sock construct_lvol_bdev -u d0a9e7e0-81d1-40e2-9a7d-385893c8bf7f lbd_vm_0 40916
gpt.c: 197:spdk_gpt_check_mbr: *ERROR*: GPT Primary MBR size does not equal: (record_size 20479999 != actual_size 83795967)!

spdk_vhost.sh does not recognize this as a failure!
fedora-05 has this failure, but it's reported as a Pass.

## Expected Behavior
no GPT ERROR reports.

## Current Behavior
gpt.c: 197:spdk_gpt_check_mbr: *ERROR*: GPT Primary MBR size does not equal: (record_size 20479999 != actual_size 83795967)!

## Possible Solution
check GPT Primary MBR size.

## Steps to Reproduce
1. cd SPDK dir
2. run ./test/vhost/spdk_vhost.sh --integrity-lvol-scsi-nightly
3. or view logs in fedora-05, https://ci.spdk.io/spdk/builds/review/628a8e5e1bfa50da328815f469821b95d5970111.1539777703/fedora-05/build.log (search "GPT Primary MBR size does not equal")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 83b1102f7b0ffe8b0356157614507135a66f6c86

**Comment by jimharris** [comment]
I think this should likely be a SPDK_DEBUGLOG instead of SPDK_ERRLOG.

**Comment by wanghailiangx** [comment]
I raised a patch to replace the ERRLOG with DEBUGLOG.
https://review.gerrithub.io/#/c/spdk/spdk/+/431992/.

**Comment by wanghailiangx** [comment]
The upper patch has been merged. I verified the latest log.

**Comment by optimistyzy** [comment]
@wanghailiang  Thanks for submitting this patch.

wanghailiang <notifications@github.com> 于2018年11月7日周三 下午2:37写道：
