### ISSUE TITLE
SPDK couldn't find NVMe device

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#480]
spdk_tgt fails to attach NVMe devices that is present in the system. 
I try it with Intel Corporation Express Flash NVMe P4500
```
# lspci  | grep NVMe
10000:03:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
10000:04:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
10000:05:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
10000:06:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
10000:07:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
10000:08:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
10000:09:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500
```
config file for app/spdk_tgt is following
```
[Nvme]
  TransportId "trtype:PCIe traddr:10000:03:00.0" Nvme0
```

## Expected Behavior

Successful start of spdk_tgt
## Current Behavior

```
# app/spdk_tgt/spdk_tgt -c etc/spdk/test.conf -L all
Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --file-prefix=spdk_pid172006 ]
EAL: Detected 80 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 602:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 703:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
thread.c: 163:spdk_allocate_thread: *DEBUG*: Allocating new thread reactor_0
reactor.c: 490:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
thread.c: 378:spdk_io_device_register: *DEBUG*: Registering io_device memcpy_engine (0x78a980) on thread reactor_0
thread.c: 378:spdk_io_device_register: *DEBUG*: Registering io_device copy_module (0x78a970) on thread reactor_0
bdev_raid.c:1096:raid_bdev_get_ctx_size: *DEBUG*: raid_bdev_get_ctx_size
bdev_raid.c:1096:raid_bdev_get_ctx_size: *DEBUG*: raid_bdev_get_ctx_size
thread.c: 378:spdk_io_device_register: *DEBUG*: Registering io_device bdev_mgr (0x78a8e0) on thread reactor_0
bdev_raid.c:1222:raid_bdev_init: *DEBUG*: raid_bdev_init completed successfully
thread.c: 378:spdk_io_device_register: *DEBUG*: Registering io_device null_bdev (0x79a690) on thread reactor_0
EAL: PCI device 10000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 10000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 10000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 10000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 10000:07:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 10000:08:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 10000:09:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
bdev_nvme.c:1429:bdev_nvme_library_init: *ERROR*: NVMe SSD "10000:03:00.0" could not be found.
bdev_nvme.c:1430:bdev_nvme_library_init: *ERROR*: Check PCIe BDF and that it is attached to UIO/VFIO driver.
```
## Possible Solution

Is it somehow related to #477  or #273  ? 
## Steps to Reproduce

1. git clone https://github.com/spdk/spdk.git (commit 40da9ab5e360d84cd5bb2b705a72eaeb066628cc)
2. git submodule update --init
3. ./configure --with-rdma --with-fio=<doesn't matter> --enable-debug
4. make -j
5. HUGEMEM=8192 scripts/setup.sh . Output is 
```
# HUGEMEM=8192 scripts/setup.sh
10000:03:00.0 (8086 0a54): nvme -> uio_pci_generic
10000:04:00.0 (8086 0a54): nvme -> uio_pci_generic
10000:05:00.0 (8086 0a54): nvme -> uio_pci_generic
10000:06:00.0 (8086 0a54): nvme -> uio_pci_generic
10000:07:00.0 (8086 0a54): nvme -> uio_pci_generic
10000:08:00.0 (8086 0a54): nvme -> uio_pci_generic
10000:09:00.0 (8086 0a54): nvme -> uio_pci_generic
0000:00:04.0 (8086 2021): no driver -> uio_pci_generic
```
In dmesg there are these kind of messages : 
```
...
pcieport 10000:00:00.0: can't derive routing for PCI INT A
uio_pci_generic 10000:03:00.0: PCI INT A: no GSI
uio_pci_generic 10000:03:00.0: No IRQ assigned to device: no support for interrupts?
...
```
and 
```
# HUGEMEM=8192 scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB     2048 /   2048
node1   1048576kB        0 /      0
node1      2048kB     2048 /   2048
NVMe devices
BDF		Numa Node	Driver name		Device name
10000:03:00.0	0				-
10000:04:00.0	0				-
10000:05:00.0	0				-
10000:06:00.0	0				-
10000:07:00.0	0				-
10000:08:00.0	0				-
10000:09:00.0	0				-
I/OAT DMA
BDF		Numa Node	Driver Name
0000:00:04.0	0		uio_pci_generic
0000:00:04.1	0		uio_pci_generic
0000:00:04.2	0		uio_pci_generic
0000:00:04.3	0		uio_pci_generic
0000:00:04.4	0		uio_pci_generic
0000:00:04.5	0		uio_pci_generic
0000:00:04.6	0		uio_pci_generic
0000:00:04.7	0		uio_pci_generic
0000:80:04.0	1		uio_pci_generic
0000:80:04.1	1		uio_pci_generic
0000:80:04.2	1		uio_pci_generic
0000:80:04.3	1		uio_pci_generic
0000:80:04.4	1		uio_pci_generic
0000:80:04.5	1		uio_pci_generic
0000:80:04.6	1		uio_pci_generic
0000:80:04.7	1		uio_pci_generic
virtio
BDF		Numa Node	Driver Name		Device Name
```

6. app/spdk_tgt/spdk_tgt -c etc/spdk/test.conf -L all

## Context (Environment including OS version, SPDK version, etc.)

CentOS Linux release 7.5.1804 (Core)
kernel 3.10.0-862.14.4.el7.x86_64
Intel Corporation Express Flash NVMe P4500
SPDK v18.10-pre  master, commit  40da9ab5e360d84cd5bb2b705a72eaeb066628cc

**Comment by jimharris** [comment]
10000:03:00.0 => this indicates a system that has VMD (Volume Management Device).

This is a different issue - but the Linux kernel patch referenced in #477 should resolve this issue.  Link copied here for reference:  
https://github.com/torvalds/linux/commit/acec09e67dc450d09a912735855326c3f1146a37

Your other option is going into BIOS and looking for options to disable VMD.  This would likely be somewhere under PCI or IIO options.

Devices behind the VMD endpoint are effectively hidden from the host CPU, and their presence is only detected by the Linux kernel VMD driver.  Since the devices are hidden, they cannot have a legacy interrupt.  And uio_pci_generic would not attach to devices without a legacy interrupt - but the patch above relaxes that restriction.

Note: don't waste time trying vfio-pci - that fails for somewhat similar reasons, but will probably never be patched.  There are some initial discussions on a userspace VMD driver, but that's pretty far out at the moment.

**Comment by alekseymmm** [comment]
@jimharris  thanks for advice. I am going to check the BIOS and try disabling VMD. What could be the possible consequences of VMD disabling in terms of performance or functionality?
If it doesn't help I will think about trying the latest kernels.

**Comment by jimharris** [comment]
There's no difference in performance when using SPDK.  VMD can actually impact performance negatively when using interrupt-driven drivers, because the NVMe interrupts get routed through the VMD driver for handling.

VMD is generally useful for isolating hotplug events.  It's useful for operating systems with no or minimal hotplug support or to ensure hotplug events get handled by the OS and not BIOS.  While the Centos 7.5 kernel has VMD support, it likely doesn't have a lot of the hotplug hardening patches that have gone in over the last few years, so hotplug may not be an option with that kernel with or without VMD enabled.

VMD can also enable LEDs for direct attached SSDs, depending on your system.

Hope this helps.

-Jim

**Comment by alekseymmm** [comment]
Thanks . Got it about SPDK. What about block device performance in Linux  with VMD  enabled or not ? I mean, If I just run fio to /dev/nvme0n1  with or without VMD, do I see any difference in performance?

**Comment by jimharris** [comment]
I don't have any hard data.  But I would expect to see minimal if any noticeable difference in performance with a single NVMe SSD - maybe slightly higher CPU utilization.  I'd expect a more noticeable difference, especially in CPU utilization as more and more SSDs are added to the system.

**Comment by peluse** [comment]
@jimharris how did you ID that as VMD so quickly? Is that always the address or did you go look in some logs?

**Comment by jimharris** [comment]
The PCI domain 10000 is the dead giveaway:

10000:03:00.0

The VMD driver has to create a PCI domain for any PCI devices that sit behind it.  ACPI defines 16-bit domains (0000-FFFF) so VMD chooses one that falls just past that range.

-Jim

**Comment by jimharris** [comment]
Closing this issue.  Some work has started at Intel on an SPDK VMD driver, but that is a ways off.  The submitter's observed behavior is expected.

@alekseymmm - we can update you, if and when a native SPDK VMD driver is available.

**Comment by alekseymmm** [comment]
Confirm that disabling VMD solve the issue.
