### ISSUE TITLE
lvol.sh' usage() omits a case in NIGHTLY Test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#483]
START TEST SUITE ./test/lvol/lvol.sh --test-cases=1,50,51,52,53,100,101,102,150,200,201,250,251,252,253,254,255,300,301,450,451,452,550,551,552,553,600,601,650,651,652,654,655,700,701,**702**,750,751,752,753,754,755,756,757,758,759,800,801,802,803,804,10000

**702** case are listed here and run PASS, but it not listed in lvol.sh' usage().
It's easy to be confusing. Where is **702** case?

In test/lvol/lvol.sh:
function usage() {
......
    echo "    --test-cases=         List test cases which will be run:
                                    700: 'tasting_positive',
                                    701: 'tasting_lvol_store_positive',
                                    750: 'snapshot_readonly',
                                    751: 'snapshot_compare_with_lvol_bdev',
......
}

## Expected Behavior
702: 'tasting_positive_with_different_lvol_store_cluster_size' should be in usage().

## Current Behavior
702 case is omitted.

## Possible Solution
Add a description of 702 case in usage().

## Steps to Reproduce
1. view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. view fedora-08's build log, https://ci.spdk.io/spdk/builds/review/628a8e5e1bfa50da328815f469821b95d5970111.1539777703/fedora-08/build.log (search "START TEST CASE tasting_positive_with_different_lvol_store_cluster_size")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 40da9ab5e360d84cd5bb2b705a72eaeb066628cc

**Comment by wanghailiangx** [comment]
I has raised a patch to fix the  issue.
https://review.gerrithub.io/#/c/spdk/spdk/+/430905/

**Comment by wanghailiangx** [comment]
@nedved1 hi, I noticed that there were other four cases listed in usage() in lvol.sh, but they didn't run in the nightly. Do you know should we add them in TEST SUITE ./test/lvol/lvol.sh --test-?
350: 'nested_destroy_logical_volume_negative',
400: 'nested_construct_logical_volume_positive',
500: 'nested_construct_lvol_bdev_on_full_lvol_store',
653: 'thin_provisioning_resize',
Thanks.

**Comment by nedved1** [comment]
Hi @wanghailiangx ,
these test cases that you mention are not implemented in lvol test.

**Comment by wanqunintel** [comment]
@nedved1 , thank you for the feedback, for these 4 cases, is there any plan to add it to the lvol test?

**Comment by wanghailiangx** [comment]
The upper patch has been merged.
