### ISSUE TITLE
freebsd/ioat reports "failed to read the internal channel error register" in NIGHTLY Test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#484]
In freebsd-0 server,

START TEST SUITE test/ioat/ioat.sh
......
07:13:01	# /usr/home/sys_sgsw/build_pool/agent/repo/examples/ioat/perf/perf -t 1
and
 07:13:04	# /usr/home/sys_sgsw/build_pool/agent/repo/examples/ioat/verify/verify -t 1
are all reports:

Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 ]
EAL: Sysctl reports 40 cpus
EAL: Detected 40 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Contigmem driver has 8 buffers, each of size 256MB
EAL: Mapped memory segment 0 @ 0x810000000: physaddr:0x380000000, len 268435456
......
EAL: PCI device 0000:00:04.0 on NUMA socket 0
EAL:   probe driver: 8086:e20 spdk_ioat
ioat.c: 291:ioat_reset_hw: *ERROR*: failed to read the internal channel error register

## Expected Behavior
perf and verify run pass.

## Current Behavior
perf and verify are failed.

## Possible Solution
N/A

## Steps to Reproduce
1. Look at https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
2. Look at build log in freebsd-0 server, https://ci.spdk.io/spdk/builds/review/2460886842010426e8b43b92ee2b5aefac3fd500.1540815107/freebsd-0/build.log (search "failed to read the internal channel error register")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 40da9ab5e360d84cd5bb2b705a72eaeb066628cc

**Comment by tomzawadzki** [comment]
Hi @wanghailiangx 
Provided build log does not have the error message (it is marked passing too). It does not refer to freebsd-0, but to fedora-04 as well. 
Can you please point to build-log containing this error or provide verified scenario to reproduce it ?

**Comment by wanghailiangx** [comment]
@tomzawadzki sorry, I pasted a mistake link. Now I have updated the upper freebsd-0 link.

**Comment by peluse** [comment]
does this happen every time?

**Comment by wanghailiangx** [comment]
Yes, this happens every time. But sometimes error is another as below:
(https://ci.spdk.io/spdk/builds/review/a6304b0370dc2215468d476055336ddb031786f1.1538395576/freebsd-0/build.log) (search "failed to read the internal channel error register")
 05:13:11	# /usr/home/sys_sgsw/build_pool/agent/repo/examples/ioat/perf/perf -t 1
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --legacy-mem ]
EAL: Sysctl reports 40 cpus
EAL: Detected 40 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Contigmem driver has 8 buffers, each of size 256MB
EAL: Mapped memory segment 0 @ 0x810000000: physaddr:0x300000000, len 268435456
EAL: Mapped memory segment 1 @ 0x820000000: physaddr:0x310000000, len 268435456
EAL: Mapped memory segment 2 @ 0x830000000: physaddr:0x320000000, len 268435456
EAL: Mapped memory segment 3 @ 0x840000000: physaddr:0x390000000, len 268435456
EAL: Mapped memory segment 4 @ 0x850000000: physaddr:0x3f0000000, len 268435456
EAL: Mapped memory segment 5 @ 0x860000000: physaddr:0x400000000, len 268435456
EAL: Mapped memory segment 6 @ 0x870000000: physaddr:0x410000000, len 268435456
EAL: Mapped memory segment 7 @ 0x880000000: physaddr:0x420000000, len 268435456
EAL: PCI device 0000:00:04.0 on NUMA socket 0
EAL:   probe driver: 8086:e20 spdk_ioat
ioat.c: 291:ioat_reset_hw: *ERROR*: failed to read the internal channel error register
*ERROR*: === BACKTRACE START ===
*ERROR*:   1: ioat_reset_hw() at 0x405eb2
*ERROR*:   2:  ioat_channel_start() at 0x405b69
*ERROR*:   3:   ioat_attach() at 0x4057e4
*ERROR*:   4:    ioat_enum_cb() at 0x404b9c
*ERROR*:   5:     spdk_pci_device_init() at 0x411860
*ERROR*:   6:      rte_pci_probe_one_driver() at 0x44b1db
*ERROR*:   7:       pci_probe_all_drivers() at 0x44a6d7
*ERROR*:   8:        rte_pci_probe() at 0x44aa7c
*ERROR*:   9:         rte_bus_probe() at 0x42000a
*ERROR*:  10:          spdk_pci_enumerate() at 0x411bb3
*ERROR*:  11:           spdk_pci_ioat_enumerate() at 0x413ec7
*ERROR*:  12:            spdk_ioat_probe() at 0x404af1
*ERROR*:  13:             ioat_init() at 0x403dd8
*ERROR*: === BACKTRACE END ===

**Comment by darsto** [comment]
Thanks for noticing that!
Luckily this is nothing critical. We failed to reset the device due to a false-positive error.

Fix here: https://review.gerrithub.io/c/spdk/spdk/+/432401 (pci: fix config access return codes on BSD)
