### ISSUE TITLE
bdevperf crashed while testing SPDK iSCSI target using SPDK iscsi initiator

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#488]
I have run spdk iscsi target with null bdev. then I run bdevperf to test the iscsi target. but the bdevperf crashed.

## Expected Behavior
bdevperf passed without error.

## Current Behavior
bdevperf crashed.

## Steps to Reproduce
1. run spdk iscsi target with the config file in attachment. The command is as below:
./app/iscsi_tgt/iscsi_tgt -c iscsi.conf -m 0xff
2. In initiator machines, install libiscsi development packages, libiscsi-devel and libiscsi.
3. clone spdk and configure and compile spdk in initiator machine.
./configure --with-iscsi-initiator && make
4. create bdev.conf in initiator machine:
```
[iSCSI_Initiator]
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk1/0 iSCSI0
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk2/0 iSCSI1
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk3/0 iSCSI2
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk4/0 iSCSI3
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk5/0 iSCSI4
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk6/0 iSCSI5
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk7/0 iSCSI6
    URL iscsi://192.168.123.11/iqn.2016-06.io.spdk:disk8/0 iSCSI7

```

5. run bdevperf with following command:
`./test/bdev/bdevperf/bdevperf -c bdev.conf -q 128 -o 4096 -w randread -t 60 -m 0x6
`
6. bdevperf will report crash. The coredump is as below:
```
Core was generated by `./test/bdev/bdevperf/bdevperf -c bdev.conf -q 128 -o 4096 -w randread -t 60 -m'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  iscsi_scsi_response_cb (iscsi=0xe3b910, status=508, command_data=0x0, private_data=0x8)
    at iscsi-command.c:49
49              switch (status) {
[Current thread is 1 (Thread 0x7f5a25540980 (LWP 24940))]
(gdb) bt
#0  iscsi_scsi_response_cb (iscsi=0xe3b910, status=508, command_data=0x0, private_data=0x8)
    at iscsi-command.c:49
#1  0x000000000043f3d9 in bdev_iscsi_poll_lun (lun=<optimized out>) at bdev_iscsi.c:363
#2  0x000000000044ab1c in _spdk_reactor_run (arg=0xdc8f80) at reactor.c:514
#3  0x000000000044b0c9 in spdk_reactors_start () at reactor.c:677
#4  0x000000000044979e in spdk_app_start (opts=opts@entry=0x7ffdcb9c0c70,
    start_fn=start_fn@entry=0x40dee0 <bdevperf_run>, arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:650
#5  0x000000000040bfb7 in main (argc=<optimized out>, argv=<optimized out>) at bdevperf.c:1013
(gdb) quit
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: 3e2297140ca17ff97bda235b2b5962ebf185953f
libiscsi version:  libiscsi-1.18.0-3.fc28.x86_64   libiscsi-devel-1.18.0-3.fc28.x86_64
[iscsi.txt](https://github.com/spdk/spdk/files/2529576/iscsi.txt)

**Comment by peluse** [comment]
could you add your iscsi.conf file as well?  Thanks

**Comment by liang2yan** [comment]
@peluse , I added it in Context. the name is iscsi.txt since github can't recognize the iscsi.conf file type.

**Comment by benlwalker** [comment]
This patch should fix the issue: https://review.gerrithub.io/#/c/spdk/spdk/+/431375/

**Comment by liang2yan** [comment]
@benlwalker @jimharris , I tried your patch. It can fix this issue.

**Comment by jimharris** [comment]
Patch merged.
