### ISSUE TITLE
bdevperf sometimes hung up while testing SPDK iSCSI target using SPDK iscsi initiator with 0xf6 coremask

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#490]
Being similar to issue 488. except for the bdevperf will hung up. But it doesn't hung up every time.
## Expected Behavior
bdevperf run successfully.

## Current Behavior
bdevperf hung up.

## Steps to Reproduce
Please see issue 488 for step 1-4.
5. run bdevperf with following command:
./test/bdev/bdevperf/bdevperf -c bdev.conf -q 128 -o 4096 -w randread -t 600 -m 0xf6

6. bdevperf will hung up after 10 minutes.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit:   bdev/iscsi: attach poller to lun instead of channel

**Comment by liang2yan** [comment]
While bdevperf hung up, the iscsi target will report following error:

```
conn.c:1066:spdk_iscsi_conn_handle_nop: *ERROR*: Timed out waiting for NOP-Out response from initiator
conn.c:1067:spdk_iscsi_conn_handle_nop: *ERROR*:   tsc=0x88bbf2195fe2c, last_nopin=0x88baff952fa9e
conn.c:1069:spdk_iscsi_conn_handle_nop: *ERROR*:   initiator=iqn.2016-06.io.spdk:init, target=disk3

```

**Comment by jimharris** [comment]
Hi @liang2yan,

Could you try to reproduce this with latest master?  If it still exists, we will assign someone to it.

Thanks,

-Jim

**Comment by liang2yan** [comment]
can't reproduce this issue now. So I think we can close this issue.

**Comment by Seth5141** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48041.html

**Comment by jimharris** [comment]
@Seth5141 - Is this for real?
