### ISSUE TITLE
nvmf tgt and client in the same app

### ISSUE THREAD

**Issue by clicx** [spdk/spdk#492]
I'm writing an app for nvmf discovery, the app works normally,  but after move it to an nvmf app, in the app, the client will discovery self nvmf subsystem, will got an error in nvme_rdma_connect:
nvme_rdma_get_event: *ERROR*: Failed to get event from CM event channel. Error 4 (Interrupted system call), is it known issue?

## Expected Behavior
Working normally.

## Current Behavior
Failed while connecting.

## Possible Solution
No have yet.

## Steps to Reproduce
See above.

## Context (Environment including OS version, SPDK version, etc.)
Centos 7.2 with IB, newest SPDK master branch.

**Comment by jimharris** [comment]
Hi @clicx,

I'm not aware of any reported issues like this.

Can you report the exact SPDK commit?  This will be important, especially if someone tries to debug this issue a lot later - we don't want to guess which commit you were using.

"with IB" => you are using Infiniband for this test?

Thanks,

-Jim

**Comment by clicx** [comment]
Not sure which commit, but switch to newest commit: fd1e204647d7e2676cb442681360b28912c435b4 is same.
>you are using Infiniband for this test?
Yes.

**Comment by liang2yan** [comment]
@clicx , you mean you have write an app like nvme-cli. And you use this app to connect to SPDK nvmf target using Infiniband. But the SPDK nvmf target reported error. Am I right?

**Comment by jimharris** [comment]
Hi @clicx,

Can you please provide exact steps so someone can try to reproduce this issue?

Thanks,

-Jim

**Comment by clicx** [comment]
Actually it happen in same "polling",  in the nvmf polling thread, I posted a task to call "spdk_nvme_probe", will alway happen this issue, I tested other open source project, got same result, this looks like a rdma issue.

**Comment by jimharris** [comment]
@clicx indicates this is not an SPDK issue, so closing this issue.

@clicx - please reopen with additional details if you feel this is still related to SPDK.
