### ISSUE TITLE
nvme smart-log prints abnormal data in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#493]
test/nvme/spdk_nvme_cli.sh
test/nvmf/nvme_cli/nvme_cli.sh
-- Logs as below:

13:03:34	# ./nvme smart-log 0000:06:00.0
Starting SPDK v18.10-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 32 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Auto-detected process type: SECONDARY
EAL: Multi-process socket /var/run/dpdk/spdk0/mp_socket_810227_3d60b8f4ee6d
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Smart Log for NVME device:0000:06:00.0 namespace-id:ffffffff
critical_warning                    : 0
**temperature                         : -273 C**
available_spare                     : 0%
available_spare_threshold           : 0%
percentage_used                     : 0%
data_units_read                     : 0
data_units_written                  : 0
host_read_commands                  : 0
host_write_commands                 : 0
controller_busy_time                : 0
power_cycles                        : 0
power_on_hours                      : 0
unsafe_shutdowns                    : 0
media_errors                        : 0
num_err_log_entries                 : 0
Warning Temperature Time            : 0
Critical Composite Temperature Time : 0
Thermal Management T1 Trans Count   : 0
Thermal Management T2 Trans Count   : 0
Thermal Management T1 Total Time    : 0
Thermal Management T2 Total Time    : 0

## Expected Behavior
nvme smart-log prints real data.

## Current Behavior
These data are almost 0, especially “**temperature  : -273 C**”?!

## Possible Solution
Verify if the relevant drivers are normal.

## Steps to Reproduce
1. cd SPDK dir
2. run test/nvmf/nvme_cli/nvme_cli.sh
3. or look at NIGHTLY log in fedora-03: https://ci.spdk.io/spdk/builds/review/8ad15c9b9497ddc73842086f2ebf54509a8f8b36.1540902784/fedora-03/build.log (search "nvme smart-log /dev/nvme0")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 9f9cfdc5917e63a571b123d90637785b2aa4c60b

**Comment by peluse** [comment]
Sure, I will

**Comment by wanghailiangx** [comment]
This issue can be reproduced locally. Steps:
1. cd SPDK dir
2. run test/nvmf/nvme_cli/nvme_cli.sh

**Comment by peluse** [comment]
Hmmm, I cloned the nvme_cli repo and ran it directly and didn't see an issue.  I was going to ask, it seems like the syntax for smart-data is different.  Running locally I had to provide /dev/xxxx however in the script it provides BDF location.  I've not sued these tools before so any info you can provide would be helpful, thanks

**Comment by wanghailiangx** [comment]
List all steps, these's also for customers:
1. cd SPDK dir, ./configure --with-rdma, make -j
2. ./app/nvmf_tgt/nvmf_tgt -c nvmf.conf (as below,  set AllowAnyHost Yes)
....
[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.11.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace Nvme0n1 1
  Namespace Nvme1n1 2

3. open a new terminal, cd SPDK dir
./scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -p 4
./scripts/rpc.py construct_malloc_bdev 64 512   (such as Malloc0 )
modprobe -v nvme-rdma
./scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.11.11 -s 4420
nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.11.11 -s 4420
(upper steps are listed in nvme_cli.sh)

4. cd nvme_cli dir
./nvme smart-log /dev/nvme0, then the issue is reproduced.
nvme smart-log /dev/nvme0 is the same.

**Comment by jimharris** [comment]
This is a completely different set of instructions.  The original description was clearly for a locally attached SSD (BDF specified, debug output clearly shows PCI probe).  But these latest steps are using NVMe-oF.

These are two completely different issues.  For local PCI device, this *should* work.  For the NVMe-oF case, we do not try to emulate log pages with NVMe-oF, so getting data back with all zeroes is expected behavior.

Please let's focus this issue on the direct attached case.

**Comment by peluse** [comment]
For direct-attached using nvme-cli directly (the correct way this time) I see data as expected.  I'll run via test script just to be sure.  Here is my output:
[peluse@pels-64 nvme-cli]$ sudo ./nvme smart-log 0000:0d:00.0
Starting SPDK v19.001-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --file-prefix=spdk1 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /var/run/dpdk/spdk1/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:0d:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Smart Log for NVME device:0000:0d:00.0 namespace-id:ffffffff
critical_warning                    : 0
**temperature                         : 34 C**
available_spare                     : 100%
available_spare_threshold           : 10%
percentage_used                     : 0%
data_units_read                     : 6,806,970
data_units_written                  : 1,817,254
host_read_commands                  : 795,862,624
host_write_commands                 : 97,600,871
controller_busy_time                : 0
power_cycles                        : 29
power_on_hours                      : 4,574
unsafe_shutdowns                    : 0
media_errors                        : 0
num_err_log_entries                 : 0
Warning Temperature Time            : 0
Critical Composite Temperature Time : 0
Thermal Management T1 Trans Count   : 0
Thermal Management T2 Trans Count   : 0
Thermal Management T1 Total Time    : 0
Thermal Management T2 Total Time    : 0

**Comment by peluse** [comment]
and here's a snippet running via the test script, still cannot repro:

 15:52:46	# ./nvme smart-log 0000:0d:00.0
Starting SPDK v19.001-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 72 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Auto-detected process type: SECONDARY
EAL: Multi-process socket /var/run/dpdk/spdk0/mp_socket_864_4b7e6587c7e27d
EAL: Probing VFIO support...
EAL: PCI device 0000:0d:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
Smart Log for NVME device:0000:0d:00.0 namespace-id:ffffffff
critical_warning                    : 0
**temperature                         : 34 C**

**Comment by peluse** [comment]
@wanghailiangx maybe try a few things:

1) is this happening on more than a NVMe drive and/or more than one system?
2) can you try running the nvme_cli directly on the system that is showing the bogus temp?

**Comment by wanghailiangx** [comment]
@peluse 
I verified. The problem is not nvme_cli itself. Running the nvme_cli directly shows normal data.
But it only can be reproduced using NVMe-oF every time.
If you run test/nvmf/nvme_cli/nvme_cli.sh in local, you can see the issue.

**Comment by jimharris** [comment]
Then this is not a bug. The NVMe-oF target does not try to emulate SMART.

Sent from my iPhone

On Nov 4, 2018, at 11:31 PM, wanghailiang <notifications@github.com<mailto:notifications@github.com>> wrote:


@peluse<https://github.com/peluse>
I verified. The problem is not nvme_cli itself. Running the nvme_cli directly shows normal data.
But it only can be reproduced using NVMe-oF every time.
If you run test/nvmf/nvme_cli/nvme_cli.sh in local, you can see the issue.
