### ISSUE TITLE
How to develop http proxy server based on spdk? Thank you for your trouble, thank you

### ISSUE THREAD

**Issue by ygm521** [spdk/spdk#494]
How to develop http proxy server based on spdk? Thank you for your trouble, thank you

**Comment by darsto** [comment]
I was going through old issues and picked up this one - I'm sorry it wasn't noticed earlier.

@Maciej-Szwed I know you worked on this. Can you give us an update? Is the http proxy server upstreamed? How can we use it?

**Comment by Maciej-Szwed** [comment]
@ygm521 are looking for something like spdk/scripts/rpc_http_proxy.py (it has been added recently)?

**Comment by darsto** [comment]
@Maciej-Szwed is there any guide on how to use it?

**Comment by Maciej-Szwed** [comment]
It has its own help (just run with -h)

**Comment by jimharris** [comment]
Closing this issue.  @ygm521 - if you have additional questions on this not answered by the help message, you may reopen this issue.
