### ISSUE TITLE
spdk nvmf_tgt start failed

### ISSUE THREAD

**Issue by xuhuagen** [spdk/spdk#496]
I find that I can't start nvmf_tgt in my machine,
since commit id 7f128c757bce28a80efd23c400263fc93cfa41db

```
[root@waikikibeach35 spdk]# ./app/nvmf_tgt/nvmf_tgt -c ../nvmf.conf
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid12774 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 602:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 703:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 490:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:07:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:08:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:09:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2701 spdk_nvme
EAL: PCI device 0000:0b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:0c:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:0f:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:10:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
nvmf.c: 516:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on transport RDMA. The transport must be created first.
conf.c: 205:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
subsystem.c: 749:spdk_nvmf_subsystem_add_listener: *ERROR*: Unknown transport type 1
```
## Expected Behavior
nvmf_tgt can start successfully.

## Current Behavior
nvmf_tgt start failed

## Steps to Reproduce
1. cd /path/to/spdk && ./configure --with-rdma
2. make -j64
3. ./app/nvmf_tgt/nvmf_tgt -c nvmf.conf
4.

## Context (Environment including OS version, SPDK version, etc.)
OS: CentOS Linux release 7.5.1804 (Core)
Kernel: 4.17.1

**Comment by Maciej-Szwed** [comment]
Before the patch is merged you can do it using RPC calls. The missing step can be done with this rpc call:
./scripts/rpc.py nvmf_create_transport -t rdma
After that (if everything else has been done from config file) you just call nvmf_subsystem_add_listener to finish setting up NVMf.

**Comment by xuhuagen** [comment]
@Maciej-Szwed, thanks, I use  nvmf_create_transport before call vmf_subsystem_add_listener
 and can construct nvmf target successfully.

**Comment by wanghailiangx** [comment]
nvmf_create_transport( ) func has never been called by other func from in SPDK v19.01 until upper optimistyzy's patch. So "spdk start nvmf_tgt -c nvmf.conf" didn't work here.

**Comment by optimistyzy** [comment]
I think that we should use this patch: https://review.gerrithub.io/432376 .  If no transport defined , but there are subsystems defined in configuration , we should fail to start the tgt with some information printed, instead of the error information. Also we need to force to define an valid transport  in configuration file.  For RPC creation, there should be another case.
