### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by jupiturliu** [spdk/spdk#5]
make DPDK_DIR=./dpdk-2.1.0/x86_64-native-linuxapp-gcc
== spdk/lib (all)
== spdk/lib/memory (all)
  CC vtophys.o
vtophys.c:40:24: fatal error: rte_config.h: No such file or directory
 #include "rte_config.h"
                        ^
compilation terminated.
make[2]: *** [vtophys.o] Error 1
make[1]: *** [memory] Error 2
make: *** [lib] Error 2

**Comment by jimharris** [comment]
Please confirm you have downloaded and built DPDK as specified in the README before building SPDK.

On Dec 5, 2015, at 12:00 AM, jupiturliu <notifications@github.com<mailto:notifications@github.com>> wrote:


make DPDK_DIR=./dpdk-2.1.0/x86_64-native-linuxapp-gcc
== spdk/lib (all)
== spdk/lib/memory (all)
CC vtophys.o
vtophys.c:40:24: fatal error: rte_config.h: No such file or directory
#include "rte_config.h"
^
compilation terminated.
make[2]: *** [vtophys.o] Error 1
make[1]: *** [memory] Error 2
make: *** [lib] Error 2

�

**Comment by bwalker-intel** [comment]
DPDK_DIR needs to be an absolute path. In the README the example build command is:

make DPDK_DIR=`pwd`/dpdk-2.1.0/x86_64-native-linuxapp-gcc

Try that instead of your relative path.

**Comment by bwalker-intel** [comment]
As of commit af2a731de309ffb21ba4371b8a258274e92637e2, we now allow relative paths for DPDK_DIR.
