### ISSUE TITLE
Run scripts/setup.h hangs on two same NVMe SSDs

### ISSUE THREAD

**Issue by tlclu1209** [spdk/spdk#504]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

example/nvme/example/cmb_copy and hello_world run successfully.
Actually each of them works fine and it only fails when I plug two same NVMe.

## Current Behavior

When I run the "sudo scripts/setup.h", it hangs as below.
[](url)https://drive.google.com/file/d/1NofW9gdhD2WBAKWriOe6ER4GELs2yx4t/view?usp=sharing

Please check below for detailed steps.

## Steps to Reproduce

1.Firstly check if I could see two NVMe SSD been found
https://drive.google.com/file/d/1JLl_83my3Do9v7KyjqdBDkcgSfIYWKnT/view?usp=sharing

2.Second I try to run /example/nvme/hello_world example. It says no NVMe controller found
https://drive.google.com/file/d/1V9r2fY3wKCHzU2IPgLbxG2KUL4xCkD4T/view?usp=sharing

3.Then I run the "sudo scripts/setup.h". There are some steps I do, then it hangs...
The strange thing is when I first run the "sudo scripts/setup.h", it shows "killed", then my first nvme device name is longer available. And run again, it hanged and I think it is because the device is been "killed".
https://drive.google.com/file/d/1NofW9gdhD2WBAKWriOe6ER4GELs2yx4t/view?usp=sharing

## Context (Environment including OS version, SPDK version, etc.)

SPDK v19.01-pre / DPDK 18.05.1
Ubuntu 16.04, and kernel version is 4.19.0-rc7 (from P2pmem)

**Comment by jimharris** [comment]
Hi @tlclu1209 - thanks for the report!  I have a few requests for additional information to get to the bottom of this.

Can you provide lspci -v information for these two SSDs?  Are the 2 SSDs identical?  If not, does the single SSD test work with both SSDs?

If you could instrument setup.sh to indicate where it gets "Killed", that would also be helpful.

Any dmesg output from the kernel?

Thanks,

-Jim

**Comment by tlclu1209** [comment]
Hi @jimharris - thanks for your response. Please check below for the related info and if anything needed, just let me know.

1. lspci -v
(Since I could reassign the PCIe vendor id and device id in ssd firmware, so I try to use the different one to see if there is anything different... . So 2 SSDs are identical, and single of them works fine )
...
02:00.0 Non-Volatile memory controller: Device 9d32:1000 (rev 01) (prog-if 02[NVM Express])
             Subsystem : Device 9d32:1000
             Flags: bus master, fast devsel, latency 0, IRQ 16
             Memory at df800000 (64-bit, non-prefetchable) [size=4M]
             Memory at dfc00000 (32-bit, non-prefetchable) [size=256K]
             Capabilities: <access denied>
             Kernel driver in use: nvme
...
05:00.0 Non-Volatile memory controller: Device 8d23:1010 (rev 01) (prog-if 02[NVM Express])
             Subsystem : Device 8d23:1010
             Flags: bus master, fast devsel, latency 0, IRQ 16
             Memory at df000000 (64-bit, non-prefetchable) [size=4M]
             Memory at df400000 (32-bit, non-prefetchable) [size=256K]
             Capabilities: <access denied>
             Kernel driver in use: nvme

2. Okay, I will try to check this and may need some time. Also I googled some info about this "killed", it seems related the system resource issue. 

3. Yes, when it hangs, dmesg shows as below.
....
[870.xxxx] BUG: unable to handle kernel paging rquest at ffff89586a1e4088
[870.xxxx] PGD 0 P4D 0
[870.xxxx] Oops: 0002 [#1] SMP PTI
[870.xxxx] CPU: 0 PID: 2341 Comm: bash Not tained 4.19.0-rc7 #2
[870.xxxx] Hardware name: MSI MS-7A71/Z270-A PRO (MS-7A71), BIOS 1.20 04/07/2017
[870.xxxx] RIP: 0010:__put_page+0x54/0x70
.....

**Comment by darsto** [comment]
Bug scrub: Copying the question from @changpe1 since it isn't visible very well:

@tlclu1209 Do you have more log information for the dmesg ? the information here looks very short.

**Comment by jimharris** [comment]
Closing this issue.  @tlclu1209 - you may reopen it if you are able to collect more information to facilitate further debug.
