### ISSUE TITLE
nvmf/fio/fio.sh reports fio error in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#507]
START TEST SUITE test/nvmf/fio/fio.sh
......
Starting 3 threads
mlx5: spdk-fedora-03: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000003 00000000 00000000 00000000
00000000 9d005304 080003f7 40cfb9d2
......
  cpu          : usr=4.50%, sys=8.39%, ctx=4291, majf=0, minf=386
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.2%, 32=0.4%, >=64=99.3%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=732,16384,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=128
job1: (groupid=0, jobs=1): err= 5 (file:io_u.c:1833, func=io_u error, error=Input/output error): pid=301242: Mon Nov 19 03:27:01 2018
......
========== Backtrace start: ==========
in test/nvmf/fio/fio.sh:65 -> main()
     ...
   60  	waitforblk "nvme0n2"
   61  	waitforblk "nvme0n3"
   62  	
   63  	$testdir/nvmf_fio.py 4096 1 write 1 verify
   64  	$testdir/nvmf_fio.py 4096 1 randwrite 1 verify
=> 65  	$testdir/nvmf_fio.py 4096 128 write 1 verify
   66  	$testdir/nvmf_fio.py 4096 128 randwrite 1 verify

## Expected Behavior
nvmf/fio/fio.sh run passed.

## Current Behavior
nvmf/fio/fio.sh run failed.

## Possible Solution
N/A

## Steps to Reproduce
1. cd SPDK dir
2. run test/nvmf/fio/fio.sh
3. or look at logs in "fedora-03", https://ci.spdk.io/spdk/builds/review/4e1702afa125dab18e2838375d515f984ef2f80b.1542595623/fedora-03/build.log (search "Backtrace start")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 3126157a219271cb4b8cff3b05ac791345e38671

**Comment by jimharris** [comment]
Closing this issue.  This part of the error message points to the RDMA MR issue that was fixed a couple of weeks ago.

mlx5: spdk-fedora-03: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000003 00000000 00000000 00000000
00000000 9d005304 080003f7 40cfb9d2
