### ISSUE TITLE
spdkcli.py reports JSON-RPC error response

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#511]
spdkcli.py reports JSON-RPC error response when create the bdev successfully.

## Expected Behavior
Only get the bdev's name.

## Current Behavior
```
/bdevs/null> create null1 1024 512
null1
Got JSON-RPC error response
request:
{
  "method": "get_target_nodes",
  "id": 1,
  "jsonrpc": "2.0"
}
response:
{
  "code": -32601,
  "message": "Method not found"
}

```
## Steps to Reproduce

1. ./app/vhost/vhost
2. ./scripts/spdkcli.py
3. cd /bdevs/null
4. create null1 1024 512

## Context (Environment including OS version, SPDK version, etc.)
```
SPDK commit: b2fb55192c07c8fbf4e9b568cef885aee0a28254
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core
```

**Comment by liang2yan** [comment]
@pawelkax , any patch to fix this issue?

**Comment by pawelwod** [comment]
Can you try `spdk_tgt` instead `vhost` ?

**Comment by pawelkax** [comment]
Hi @liang2yan,

I will be working on this issue.
With spdk_tgt there is no such error .

Pawel

**Comment by pawelkax** [comment]
@liang2yan 
Fix for this issue: https://review.gerrithub.io/#/c/spdk/spdk/+/435139/

**Comment by ChenWang01** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/435139/ 
I have verified with this patch and it can fix this issue.
