### ISSUE TITLE
doc: example about rpc_client need to update

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#512]
https://spdk.io/doc/jsonrpc_proxy.html
We can see:
import json
import requests
if __name__ == '__main__':
        payload = {'method': 'get_bdevs', 'params': {'name': 'Malloc0'}}

But in scripts/rpc_http_proxy.py:
def rpc_call(req):
......
    if 'id' not in json.loads(req.decode('ascii')):
        sock.close()
        return None

## Expected Behavior
In jsonrpc_proxy.html
payload = {'id':1,'method': 'get_bdevs', 'params': {'name': 'Malloc0'}}

## Current Behavior
payload = {'method': 'get_bdevs', 'params': {'name': 'Malloc0'}}

## Possible Solution
Add 'id' description in jsonrpc_proxy.html.

## Steps to Reproduce
N/A

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit b2fb55192c07c8fbf4e9b568cef885aee0a28254

**Comment by wanghailiangx** [comment]
Raised a patch: https://review.gerrithub.io/#/c/spdk/spdk/+/434294/.

**Comment by wanqunintel** [comment]
wait for merge and then can close, this is doc issue

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/434294/ has been merged.
