### ISSUE TITLE
fio throughput of sequence write is low abnormally when numjobs=4 or 16

### ISSUE THREAD

**Issue by lh2debug** [spdk/spdk#514]
fio throughput of sequence write is low abnormally when numjobs=4 or 16

## Questions

When I set numjobs=4 or numjobs=16, The throughput of sequence write is only 300MB/s(I test it many times). But when I set numjobs=1 or numjobs=32, the throughput of sequence write is 2GB/s as a normal test value.

What causes this problem ? Any bug?

```
[root@localhost spdk_test]# env LD_PRELOAD=/root/lab505/lhh/src/spdk_src/spdk/examples/nvme/fio_plugin/fio_plugin fio ./sam_config.fio -ioengine=spdk -norandommap -thread -iodepth=32 -bs=4K -rw=write -runtime=100 -numjobs=4
test: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=32
...
fio-3.3
Starting 4 threads
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 512 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid5655 ]
EAL: Detected 24 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Probing VFIO support...

EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2701 spdk_nvme
Jobs: 4 (f=4): [W(4)][100.0%][r=0KiB/s,w=263MiB/s][r=0,w=67.2k IOPS][eta 00m:00s]
test: (groupid=0, jobs=4): err= 0: pid=5683: Sun Nov 25 20:10:01 2018
  write: IOPS=67.1k, BW=262MiB/s (275MB/s)(25.6GiB/100003msec)
    slat (nsec): min=163, max=103150, avg=236.77, stdev=147.30
    clat (usec): min=38, max=3718, avg=1905.56, stdev=31.25
     lat (usec): min=47, max=3718, avg=1905.79, stdev=31.25
    clat percentiles (usec):
     |  1.00th=[ 1876],  5.00th=[ 1876], 10.00th=[ 1876], 20.00th=[ 1876],
     | 30.00th=[ 1876], 40.00th=[ 1876], 50.00th=[ 1893], 60.00th=[ 1909],
     | 70.00th=[ 1926], 80.00th=[ 1926], 90.00th=[ 1942], 95.00th=[ 1958],
     | 99.00th=[ 2008], 99.50th=[ 2024], 99.90th=[ 2057], 99.95th=[ 2073],
     | 99.99th=[ 2114]
   bw (  KiB/s): min=66824, max=68016, per=25.00%, avg=67146.78, stdev=134.86, samples=800
   iops        : min=16706, max=17004, avg=16786.68, stdev=33.73, samples=800
  lat (usec)   : 50=0.01%, 100=0.01%, 250=0.01%, 500=0.01%, 750=0.01%
  lat (usec)   : 1000=0.01%
  lat (msec)   : 2=98.79%, 4=1.21%
  cpu          : usr=100.01%, sys=0.00%, ctx=588, majf=0, minf=90
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=100.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.1%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,6715257,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):
  WRITE: bw=262MiB/s (275MB/s), 262MiB/s-262MiB/s (275MB/s-275MB/s), io=25.6GiB (27.5GB), run=100003-100003msec

[root@localhost spdk_test]# env LD_PRELOAD=/root/lab505/lhh/src/spdk_src/spdk/examples/nvme/fio_plugin/fio_plugin fio ./sam_config.fio -ioengine=spdk -norandommap -thread -iodepth=32 -bs=4K -rw=write -runtime=100 -numjobs=1
test: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=32
fio-3.3
Starting 1 thread
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 512 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid5779 ]
EAL: Detected 24 lcore(s)
EAL: Detected 2 NUMA nodes

EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2701 spdk_nvme
Jobs: 1 (f=1): [W(1)][100.0%][r=0KiB/s,w=2023MiB/s][r=0,w=518k IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=5807: Sun Nov 25 20:15:25 2018
  write: IOPS=516k, BW=2017MiB/s (2115MB/s)(197GiB/100001msec)
    slat (nsec): min=153, max=152808, avg=198.65, stdev=95.44
    clat (usec): min=23, max=267, avg=61.41, stdev=19.62
     lat (usec): min=23, max=267, avg=61.61, stdev=19.62
    clat percentiles (usec):
     |  1.00th=[   48],  5.00th=[   48], 10.00th=[   48], 20.00th=[   49],
     | 30.00th=[   49], 40.00th=[   51], 50.00th=[   51], 60.00th=[   52],
     | 70.00th=[   57], 80.00th=[   85], 90.00th=[   89], 95.00th=[   92],
     | 99.00th=[  126], 99.50th=[  133], 99.90th=[  159], 99.95th=[  169],
     | 99.99th=[  190]
   bw (  MiB/s): min= 1919, max= 2167, per=99.99%, avg=2016.81, stdev=26.63, samples=199
   iops        : min=491376, max=554916, avg=516304.92, stdev=6817.04, samples=199
  lat (usec)   : 50=35.81%, 100=60.46%, 250=3.73%, 500=0.01%
  cpu          : usr=100.02%, sys=0.00%, ctx=35, majf=0, minf=39
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=100.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.1%, 64=0.0%, >=64=0.0%
     issued rwt: total=0,51637674,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):
  WRITE: bw=2017MiB/s (2115MB/s), 2017MiB/s-2017MiB/s (2115MB/s-2115MB/s), io=197GiB (212GB), run=100001-100001msec

  ```

## Context (Environment including OS version, SPDK version, etc.)

**My OS version is Centos 7.4 running on a physical machine and my SPDK/DPDK version is SPDK v18.10-pre / DPDK 18.08.0.**

```
[root@localhost spdk]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 

```
**My NVMe drivers are one intel optane SSD DC P4800X SERIES.

**Comment by lh2debug** [comment]
The content of sam_config.fio is as follows:

```

[global]
group_reporting=1
direct=1
verify=0
time_based=1
ramp_time=0

filename=trtype=PCIe traddr=0000.04.00.0 ns=1

[test]

```
The fio command is as follows:
```
env LD_PRELOAD=/root/lab505/lhh/src/spdk_src/spdk/examples/nvme/fio_plugin/fio_plugin fio ./sam_config.fio -ioengine=spdk -norandommap -thread -iodepth=32 -bs=4K -rw=write -runtime=100 -numjobs=$numj
```
When the $numj = 16 or 4 , the throughput is about 300MB/s, when the $numj = 1 or 32, the throughput is about 2GB/s.

**Comment by xuhuagen** [comment]
@lh2debug  
My NVMe drivers are one intel optane SSD DC P4800X SERIES.

I set numjobs= 4 16 31, The throughput of sequence write is only about 250MB/s 
But when I set numjobs=1  the throughput of sequence write is about 2GB/s.

**Comment by optimistyzy** [comment]
This issue is very interesting..  I did not see the rwmixwrite set in your configuration file? If it is not set ,the default is 50?

**Comment by optimistyzy** [comment]
What's your testing time? It is interesting which is only related with sequential write....

**Comment by lh2debug** [comment]
I didn't set rwmixwrite, the default is 50%. 

What do you want to say is to say runtime? I set runtime=100.

Yes, it’s interesting that performance is not normal only when writing sequentially.

**Comment by luleilei1** [comment]
I try to reproduce the issue, the result is as following :
Number of threads vary in 1  4  16  64
rw mode write
Throughput(MB/s) 2154  288  260  198
Latency(us)    57.72  1734.47  7678.37  19526.46

but when Number of threads vary is 64 it has an error message:
```
  nvme_ctrlr.c: 279:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: No free I/O queue IDs
  fio_plugin.c: 292:attach_cb: *ERROR*: Cannot allocate nvme io_qpair any more
  Failed to initialize spdk fio plugin
```

**Comment by changpe1** [comment]
> I try to reproduce the issue, the result is as following :
> Number of threads vary in 1 4 16 64
> rw mode write
> Throughput(MB/s) 2154 288 260 198
> Latency(us) 57.72 1734.47 7678.37 19526.46
> 
> but when Number of threads vary is 64 it has an error message:
> 
> ```
>   nvme_ctrlr.c: 279:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: No free I/O queue IDs
>   fio_plugin.c: 292:attach_cb: *ERROR*: Cannot allocate nvme io_qpair any more
>   Failed to initialize spdk fio plugin
> ```
If you don't change the default option num_io_queues, the number of queues is related with your hardware, so your hardware NVMe may has 63 hardware queues. Can you check that ?

**Comment by luleilei1** [comment]
@lh2debug  I check the hardware, find the Number of I/O Submission Queues P3700/P4800 is 31 and the Number of I/O Submission Queues of P4500/P4600 is 128.
If you want to use fio with P4800, the Maximum numjods can only be 31. So the result is problematic you set numjobs =64.

**Comment by YamboZhou** [comment]
@lh2debug Have you tried these tests using SPDK perf tool? It's better to test again with SPDK perf tool. And see whether the throughput have the same issues.

**Comment by optimistyzy** [comment]
I asked some paes at intel.For seq write you cannot use multiple jobs, it becomes random write in firmware layer, it means that the write of many jobs are mixed and become random write. So if you test a long time,all seq write.test will decrese the perf,and you really get the random write performance result. the maximal maybe 75k * 4k ，i.e., 300mb/s.So I think that we can close this issue
