### ISSUE TITLE
nbd.c: 901:spdk_nbd_start: *ERROR*  I need help.

### ISSUE THREAD

**Issue by PaulJongkukKim** [spdk/spdk#519]
Hello my name is Paul Kim.

I'd like to file write using spdk in ubuntu 16.0.4 with nvme pci-e.
so I tried below process.

1. Make huge page.
2. sudo scripts/setup.sh
3. sudo ./app/spdk_tgt/spdk_tgt (in other window)
4. sudo ./scripts/rpc.py construct_nvme_bdev -b NVMe0 -t PCIe -a 0000:86:00.0
5. sudo ./scripts/rpc.py get_bdevs (I successfully make "bdev"..)
6. sudo ./scripts/rpc.py start_nbd_disk Nvme0n1 /dev/nbd0
	-> failed
	
	JSON-RPC response error messsage
	nbd.c: 901:spdk_nbd_start: *ERROR*: open("/dev/nbd0") failed: No such file or directorynbd.c: 901:spdk_nbd_start: *ERROR*: open("/dev/nbd0") failed: No such file or directory

I do not know what caused the failure. I need help.

thank you.

**Comment by jimharris** [comment]
Hi @PaulJongkukKim,

Can you check that the nbd module is loaded on your system?  If not, try "modprobe nbd" and retry the test.

Thanks,

-Jim

**Comment by PaulJongkukKim** [comment]
Hi @jimharris 
I successfully made "dev/nbd0". Thank you so much.

I have one question. 
Where can I find "modprobe nbd" command? I have referenced https://spdk.io/doc/

**Comment by jimharris** [comment]
modprobe is a Linux command. You can check “man modprobe” for documentation.

On Nov 26, 2018, at 5:44 PM, PaulJongkukKim <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jimharris<https://github.com/jimharris>
I successfully made "dev/nbd0". Thank you so much.

I have one question.
Where can I find "modprobe nbd" command? I have referenced https://spdk.io/doc/

**Comment by jimharris** [comment]
Closing this issue based on feedback from @PaulJongkukKim.  If there are any additional issues or questions, please file a new issue, or reopen this one with clarifications.  Thanks!
