### ISSUE TITLE
nvmf perf.sh can not find Nvme bdev in NIGHTLY test

### ISSUE THREAD

**Issue by luleilei1** [spdk/spdk#520]
spdk_vhost.sh --migration run timeout in "fedora-06" for several days, key logs as below:
START TEST SUITE test/nvmf/host/perf.sh

09:33:46	# /home/sys_sgsw/build_pool/agent/repo/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Nvme0n1
nvmf_rpc.c: 877:nvmf_rpc_ns_paused: *ERROR*: No bdev with name Nvme0n1
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0",
  "method": "nvmf_subsystem_add_ns",
  "id": 1,
  "params": {
    "nqn": "nqn.2016-06.io.spdk:cnode1",
    "namespace": {
      "bdev_name": "Nvme0n1"
    }
  }
}
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}

=> 50  			$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 $bdev

=> 106 		test_perf $type $nvmf_tgt_ip

=> 45  	run_test suite test/nvmf/host/perf.sh

=> 159 		run_test suite ./test/nvmf/nvmf.sh

## Expected Behavior

test/nvmf/host/perf.sh run passed
## Current Behavior
test/nvmf/host/perf.sh run failed

## Steps to Reproduce

1.cd SPDK 
2.run test/nvmf/host/perf.sh
3.or look at logs in "fedora-06", 
https://ci.spdk.io/spdk/builds/review/149cfe81d43200f7c10cfce122364280e161a8a7.1543414190/fedora-06/build.log         (search No bdev with name Nvme0n1)

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 9e2f1bff81466d675881454d8907dd65b62308b0

**Comment by wanghailiangx** [comment]
Yang Ziye's patch has fixed the issue. https://review.gerrithub.io/#/c/spdk/spdk/+/434299/
