### ISSUE TITLE
On Ubuntu 18.04, configure scripts misreports libibverbs version

### ISSUE THREAD

**Issue by ak-gh** [spdk/spdk#524]
When run on Ubuntu 18.04 system, ./configure --with-rdma prints the following warning.

*******************************************************************************
WARNING: The Infiniband Verbs opcode Send With Invalidate is either not
supported or is not functional with the current version of libibverbs installed
on this system. Please upgrade to at least version 1.1.

Beginning with Linux kernel 4.14, the kernel NVMe-oF initiator leverages Send
With Invalidate RDMA operations to improve performance. Failing to use the
Send With Invalidate operation on the NVMe-oF target side results in full
functionality, but greatly reduced performance. The SPDK NVMe-oF target will
be unable to leverage that operation using the currently installed version
of libibverbs, so Linux kernel NVMe-oF initiators based on kernels greater
than or equal to 4.14 will see significantly reduced performance.
*******************************************************************************

## Expected Behavior
As libibverbs is at version 1.1, no warning is expected.

## Current Behavior
A misleading warning is printed.

## Possible Solution
The reason is that the configure script uses incorrect location of the libibverbs in the case of Ubuntu. The actual location is as follows:

readlink -f /usr/lib/x86_64-linux-gnu/libibverbs.so.1
/usr/lib/x86_64-linux-gnu/libibverbs.so.1.1.17.1

The respective excerpt of the configure script worth a fix is as follows.

if [ "${CONFIG[RDMA]}" = "y" ]; then
        if [ "$OSTYPE" != "FreeBSD"* ]; then
                ibv_lib_file="$(readlink -f /usr/lib64/libibverbs.so)" || true
                if [ -z $ibv_lib_file ]; then
                        ibv_lib_file="libibverbs.so.0.0.0"
                fi
                ibv_ver_str="$(basename $ibv_lib_file)"
                ibv_maj_ver=`echo $ibv_ver_str | cut -d. -f3`
                ibv_min_ver=`echo $ibv_ver_str | cut -d. -f4`
                if [[ "$ibv_maj_var" > 1 || ("$ibv_maj_ver" -eq 1 && "$ibv_min_ver" -ge 1) ]]; then
                        CONFIG[RDMA_SEND_WITH_INVAL]="y"
                else
                        CONFIG[RDMA_SEND_WITH_INVAL]="n"
                        echo "

## Steps to Reproduce
1. Clone SPDK on the system running Ubuntu 18.04
2. Run ./configure --with-rdma

## Context (Environment including OS version, SPDK version, etc.)
SPDK tip (19.01-pre?), Ubuntu 18.04 LTS

**Comment by luleilei1** [comment]
I reproduce the issue, this question exists.

**Comment by pawelwod** [comment]
Pls check if this is working for you  https://review.gerrithub.io/#/c/spdk/spdk/+/435996/

**Comment by ak-gh** [comment]
Works for me.

Regards,
Andrey

**Comment by alex-zadara** [comment]
@pawelwod @jimharris 
I am still hitting this issue. Running on ubuntu 18,04 user-space, kernel 4.14.51 and Mellanox OFED 4.4 installed. The libibverbs library that comes with that OFED definitely has the needed opcode:
```
enum ibv_wr_opcode {
	IBV_WR_RDMA_WRITE,
	IBV_WR_RDMA_WRITE_WITH_IMM,
	IBV_WR_SEND,
	IBV_WR_SEND_WITH_IMM,
	IBV_WR_RDMA_READ,
	IBV_WR_ATOMIC_CMP_AND_SWP,
	IBV_WR_ATOMIC_FETCH_AND_ADD,
	IBV_WR_LOCAL_INV,
	IBV_WR_BIND_MW,
	IBV_WR_SEND_WITH_INV,
};
```
Regarding the configure script, what it sees:
```
ibv_lib_file=/usr/lib/libibverbs.so.1.0.0
ibv_ver_str=libibverbs.so.1.0.0
ibv_maj_var=
ibv_maj_ver=1
ibv_min_ver=0
```
And the package installed:
```
root@ubuntu-1804:/mnt/work/alex/spdk# dpkg -S libibverbs.so.1.0.0
libibverbs1: /usr/lib/libibverbs.so.1.0.0
libibverbs1-dbg: /usr/lib/debug/usr/lib/libibverbs.so.1.0.0
root@ubuntu-1804:/mnt/work/alex/spdk# dpkg -l | grep libibverbs1
ii  libibverbs1                           41mlnx1-OFED.4.4.1.0.0.44100            amd64        Library for direct userspace use of RDMA (InfiniBand/iWARP)
ii  libibverbs1-dbg                       41mlnx1-OFED.4.4.1.0.0.44100            amd64        Debugging symbols for the libibverbs library
```
Can you please look into this?

**Comment by pawelwod** [comment]
Version is checked properly. @Seth5141 is an author of this part of code that check the version and I don't know why version **must** be > 1.0.

Can you post output of `ldconfig -p | grep 'libibverbs.so '`

BTW: There is one spelling mistake in:

```
if [[ "$ibv_maj_var" -gt 1 || ("$ibv_maj_ver" -eq 1 && "$ibv_min_ver" -ge 1) ]]; then
```
ibv_maj_v**a**r should be ibv_maj_v**e**r But this is not the issue in this case. I will post a patch for this.

**Comment by pawelwod** [comment]
@ak-gh 

> Can you post output of ldconfig -p | grep 'libibverbs.so '

Thanks
