### ISSUE TITLE
Does not spdk support file systems? (question)

### ISSUE THREAD

**Issue by PaulJongkukKim** [spdk/spdk#526]
Hello my name is Paul Kim.

I am trying to improve through spdk because of the nvme file write rate limit on Linux.
Does not spdk support file systems that can be accessed and verified by end users(not developer)?

thank you

**Comment by peluse** [comment]
Not really, not in terms of kernel file systems.  Much of SPDK is geared towards developers who want to integrate low-latency high performance IO into their application.  There are "end user" type applications though, for example our vhost support, our iscsi tgt, NVMEoF tgt, etc.  We also have blobstore and blosbstoreFS which you may have seen however this does not amount to a filesystem replacement.

**Comment by peluse** [comment]
Just catching up and email and saw this was also answered by Ben on the dist list.  Closing
