### ISSUE TITLE
perf against nvmf over tcp  segfaults if it cannot connect to the target

### ISSUE THREAD

**Issue by ak-gh** [spdk/spdk#530]
Attempting to run against a non-existent target segfaults perf.

## Expected Behavior
Clean exit.

## Current Behavior
The code segfaults in nvme_tcp.c.

## Possible Solution
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x7 --no-pci --base-virtaddr=0x200000000000 --file-prefix=spdk_pid21652 ]
EAL: Detected 56 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.100.105:4420 [snip]
posix.c: 268:spdk_posix_sock_create: *ERROR*: connect() failed, errno = 111
nvme_tcp.c:1674:nvme_tcp_qpair_connect: *ERROR*: sock connection error of tqpair=0x559c43753650 with addr=192.168.100.105, port=4420
nvme_tcp.c:1772:nvme_tcp_ctrlr_construct: *ERROR*: failed to create admin qpair
Segmentation fault

## Steps to Reproduce
1. Run perf against an NVMoF target w/o starting the latter.
2. Bingo.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
ubuntu 18.04, SPDK v19.01-pre / DPDK 18.08.0

**Comment by optimistyzy** [comment]
I also observed it. will solve it later

2018年12月4日星期二，ak-gh <notifications@github.com> 写道：

**Comment by optimistyzy** [comment]
Both the following patches should work:

https://review.gerrithub.io/#/c/spdk/spdk/+/436612/
https://review.gerrithub.io/436613

I will let Jim and Ben to determine which patch is much better.  @jimharris  @benlwalker

**Comment by ak-gh** [comment]
Hi Ziye,

436613 worked for me.

Thanks,
Andrey

**Comment by optimistyzy** [comment]
Hi Andrey,

Can you tell me why the other 436612 not work? I tested both.

Thanks.

ak-gh <notifications@github.com> 于2018年12月10日周一 下午11:31写道：

**Comment by jimharris** [comment]
Discussed in bug scrub - 436613 fixes this issue.  Closing this bug.
