### ISSUE TITLE
pkgdep.sh fails on ubuntu machines in CH TP (maybe in Jenkins too) because of spdk_cli udpate

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#532]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

pkgdep.sh should run on the test pool machines without error, changes to pkgdep need to be tested on all of the OS distributions that the TP machines use

## Current Behavior

Below is the error snippet, here is the link to a patch I was using to run pkgdep.  The patch is unrelated to this issue, its just how I identified it.
 
https://ci.spdk.io/spdk/builds/review/78d2947dbccf9fd5bf9936d7c728135fa3c1e539.1544045107/ubuntu14.04/build.log . 

Cleaning up...
Downloading/unpacking configshell-fb
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement configshell-fb
Cleaning up...
No distributions at all found for configshell-fb
Storing debug log for failure in /home/sys_sgsw/.pip/pip.log
Error!

## Possible Solution
Find the correct pkg name up update

## Steps to Reproduce
run pkgdep.sh on ubunutu distros

**Comment by Seth5141** [comment]
This appears to only fail on ubuntu14.04 specifically with pip3. The ubuntu 16.04 failure in the link is from a full /boot folder.
A simpler reproduction is running `sudo pip3 install configshell_fb` on an ubuntu 14.04 system.

**Comment by jimharris** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/436231/

**Comment by jimharris** [comment]
Patch has been merged.  @peluse - not sure if you want to confirm the fix?  Or if you just want to close I'm fine with that too.

**Comment by peluse** [comment]
Might as well... I just pushed the unrelated patch that had me run into this so will let you know how ti goes...

**Comment by peluse** [comment]
So this still fails, I rebased my unrelated patch which needs to run pkgdep.sh once on the TP machines to get them ready for compress, here is the output from the 16.04 Chandler TP machine:

E: Unable to locate package python3-configshell-fb
Error!

I'll take care of fixing it though, not on vacation anymore :)

**Comment by peluse** [comment]
This patch addresses it (tested it in CH TP), once it is approved and merged this issue can be closed:

https://review.gerrithub.io/c/spdk/spdk/+/436781

**Comment by jimharris** [comment]
Patch merged.  Thanks @peluse!
