### ISSUE TITLE
rpc client test 

### ISSUE THREAD

**Issue by cunyinch** [spdk/spdk#533]
Hi Jim & all,
I am testing against the rpc_client_test, it cause coredump on my system when the server thread try to call pthread_join at the end of the test, the kernel is 3.10, and I found maybe we should use int *th_rc instead of int th_rc = INT_MIN at the very beginning of the main()?

**Comment by jimharris** [comment]
Hi @cunyinch!  Great to hear from you.

Adding @pawelwod - can you take a look at Cunyin's question?

Thanks,

-Jim

**Comment by cunyinch** [comment]
@jimharris Yes, it is great to work with you again in another way :) , I am not sure if this related with kernel version, but at least on my system, after I change int th_rc = INT_MIN to int *th_rc (also modify the releated fprintf), it works for me now. @pawelwod

**Comment by pawelwod** [comment]
This should work https://review.gerrithub.io/#/c/spdk/spdk/+/436309/
