### ISSUE TITLE
SPDK nvmf target crashed after connection problem

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#537]
## Expected Behavior
SPDK nvmf target should pass.

## Current Behavior
SPDK nvmf target crashed. coredump is as below:
Reading symbols from /home/admin/nvmfds/bs_20180928115054/spdk_7d9ed/app/spdk_tgt/spdk_tgt...done.
(gdb) bt
#0  0x0000000000453a30 in _nvmf_rdma_disconnect_retry (ctx=<value optimized out>) at rdma.c:2037
#1  0x000000000045ae01 in _spdk_msg_queue_run_batch (thread=0x1789f80, max_msgs=<value optimized out>) at thread.c:326
#2  spdk_thread_poll (thread=0x1789f80, max_msgs=<value optimized out>) at thread.c:363
#3  0x00000000004470c2 in _spdk_reactor_run (arg=0x184af80) at reactor.c:313
#4  0x000000000044731c in spdk_reactors_start () at reactor.c:413
#5  0x0000000000446839 in spdk_app_start (opts=0x7ffd4b209940, start_fn=0x407b90 <spdk_tgt_started>, arg1=0x0, arg2=0x0) at app.c:658
#6  0x0000000000407b7b in main (argc=9, argv=0x7ffd4b209ad8) at spdk_tgt.c:122

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit:  7d9ed0cf4239493ee4ed2374fc11c985a38ddd60

**Comment by peluse** [comment]
once you have steps to repro I'd be happy to dig into this one.

**Comment by wanqunintel** [comment]
@liang2yan would you provide the detailed reproduce steps if possible?

**Comment by peluse** [comment]
@liang2yan have you tried the patch? Note that its still WIP but getting some feedback from the submitter would be good I think.  Also please add steps to repro, multiple people are looking at this  and if they're all doing different things to reproduce it there's a decent chance they're chasing different things.

**Comment by peluse** [comment]
OK, I'll try to repro with a slightly simpler set of steps and config.  @Seth5141 is looking into something that might be related to this regarding items left in the queue when hitting ctrl-c.  Will let ya know if I can repro or if he ends up with a patch for this other issues that would make sense to test against this one.

**Comment by peluse** [comment]
@Seth5141 see pervious update, is a good time to re-test coming up shortly?

**Comment by Seth5141** [comment]
@peluse My change that drains the rdma qpair before deletion has been merged, as has the patch @optimistyzy mentioned from above. So trying to retest now would be good.

**Comment by liang2yan** [comment]
Just tried with latest codes. nvmf target still crashed. the log is as below:

```
rdma.c: 612:nvmf_rdma_dump_request: *ERROR*:            Request Data From Pool: 0
rdma.c: 613:nvmf_rdma_dump_request: *ERROR*:            Request opcode: 2
rdma.c: 614:nvmf_rdma_dump_request: *ERROR*:            Request recv wr_id23620088
rdma.c: 612:nvmf_rdma_dump_request: *ERROR*:            Request Data From Pool: 0
rdma.c: 613:nvmf_rdma_dump_request: *ERROR*:            Request opcode: 2
rdma.c: 614:nvmf_rdma_dump_request: *ERROR*:            Request recv wr_id23620192
rdma.c: 612:nvmf_rdma_dump_request: *ERROR*:            Request Data From Pool: 0
rdma.c: 613:nvmf_rdma_dump_request: *ERROR*:            Request opcode: 2
rdma.c: 614:nvmf_rdma_dump_request: *ERROR*:            Request recv wr_id23620296
rdma.c: 624:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 3
rdma.c: 624:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 4
rdma.c: 624:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 5
rdma.c: 624:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 6
rdma.c: 624:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 7
rdma.c: 624:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 8
rdma.c: 624:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 9
rdma.c: 612:nvmf_rdma_dump_request: *ERROR*:            Request Data From Pool: 1
rdma.c: 613:nvmf_rdma_dump_request: *ERROR*:            Request opcode: 2

```

The coredump is as below:
```

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000454cc9 in nvmf_rdma_dump_request (req=0x1c61d10) at rdma.c:614
warning: Source file is more recent than executable.
614
[Current thread is 1 (Thread 0x7fbeaa630e00 (LWP 33887))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26-28.fc27.x86_64 openssl-libs-1.1.0h-3.fc27.x86_64
(gdb) bt
#0  0x0000000000454cc9 in nvmf_rdma_dump_request (req=0x1c61d10) at rdma.c:614
#1  nvmf_rdma_dump_qpair_contents (rqpair=0x16edc70) at rdma.c:626
#2  spdk_nvmf_rdma_qpair_destroy (rqpair=0x16edc70) at rdma.c:644
#3  0x0000000000454dae in spdk_nvmf_rdma_qpair_destroy (rqpair=<optimized out>) at rdma.c:636
#4  spdk_nvmf_rdma_poll_group_destroy (group=0x1551590) at rdma.c:2421
#5  0x000000000044d439 in spdk_nvmf_tgt_destroy_poll_group (io_device=<optimized out>, ctx_buf=0x15517c0) at nvmf.c:159
#6  0x000000000045c816 in _spdk_put_io_channel (arg=0x1551790) at thread.c:914
#7  0x000000000045c46d in _spdk_msg_queue_run_batch (thread=0x13625e0, max_msgs=<optimized out>) at thread.c:318
#8  spdk_thread_poll (thread=thread@entry=0x13625e0, max_msgs=max_msgs@entry=0) at thread.c:359
#9  0x0000000000459289 in _spdk_reactor_run (arg=0x1362300) at reactor.c:320
#10 0x0000000000459768 in spdk_reactors_start () at reactor.c:421
#11 0x00000000004585b4 in spdk_app_start (opts=opts@entry=0x7ffeb4e0c090, start_fn=start_fn@entry=0x4071e0 <nvmf_tgt_started>, arg1=arg1@entry=0x0,
    arg2=arg2@entry=0x0) at app.c:660
#12 0x0000000000405c34 in main (argc=3, argv=0x7ffeb4e0c228) at nvmf_main.c:75

```

**Comment by peluse** [comment]
@Seth5141 if this is related to what you've been working on please feel free to take it.  If not, I'll get this setup and repro here on my bench.  Wanted to get your thoughts first

**Comment by Smalinuxer** [comment]
i tested today in master , it seem like have been fixed . @liang2yan
