### ISSUE TITLE
Community page suggests we will have a community meeting on Christmas

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#540]
The community page autogenerates the community and bug scrub meetings on a bi-weekly cadence.  It would be nice if we had some kind of filter of specific dates that it should skip.  For example, I had someone point out to me privately just now that the site says we'll have our next Euro-Friendly community meeting on Christmas Day.

Maybe we can add a series of obvious dates that we would skip - 12/25, 1/1, maybe others.  When the JS loops to get the next date, it can compare that date against this series and advance another two weeks if there's a match.  That would also allow us to enter dates a couple of months in advance if we know a meeting will be skipped for some reason.

**Comment by peluse** [comment]
But wait, I was going to call in on Xmas :)

**Comment by jimharris** [comment]
Thanks @Seth5141!
