### ISSUE TITLE
SPDK nvmf tgt crashed if using only one core and stressful fio work

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#541]
This issue is similar with the issue 498(https://github.com/spdk/spdk/issues/498), except that it only uses one core.

## Expected Behavior
the fio_plugin testing should pass
## Current Behavior
the nvmf tgt crashed while running fio_plugin testing.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./app/nvmf_tgt/nvmf_tgt -c ../latestnvmf498.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  spdk_nvmf_process_ib_event (device=0x25aa060) at rdma.c:2196
2196                    spdk_thread_send_msg(rqpair->qpair.group->thread, _nvmf_rdma_qpair_disconnect, &rqpair->qpair);
[Current thread is 1 (Thread 0x7fa6c2b4ce00 (LWP 52919))]
(gdb) bt
#0  spdk_nvmf_process_ib_event (device=0x25aa060) at rdma.c:2196
#1  0x000000000048a541 in spdk_nvmf_rdma_accept (transport=0x259aca0, cb_fn=0x470d68 <new_qpair>)
    at rdma.c:2271
#2  0x000000000047d79b in spdk_nvmf_transport_accept (transport=0x259aca0, cb_fn=0x470d68 <new_qpair>)
    at transport.c:151
#3  0x000000000047bb09 in spdk_nvmf_tgt_accept (tgt=0x2606a50, cb_fn=0x470d68 <new_qpair>) at nvmf.c:621
#4  0x0000000000470e96 in acceptor_poll (arg=0x2606a50) at nvmf_tgt.c:255
#5  0x0000000000492744 in spdk_thread_poll (thread=0x235fe40, max_msgs=0) at thread.c:402
#6  0x000000000048e456 in _spdk_reactor_run (arg=0x235fb80) at reactor.c:313
#7  0x000000000048e750 in spdk_reactors_start () at reactor.c:413
#8  0x000000000048cf72 in spdk_app_start (opts=0x7fffbbf6d5c0, start_fn=0x409936 <nvmf_tgt_started>,
    arg1=0x0, arg2=0x0) at app.c:658
#9  0x0000000000409a4d in main (argc=3, argv=0x7fffbbf6d748) at nvmf_main.c:75

## Steps to Reproduce
Use the same steps as issue 498, except the nvmf tgt only uses one core.
run nvmf target using command as below:
./app/nvmf_tgt/nvmf_tgt -c nvmf.conf  (only use one core)
## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: 7245134ab0bb46dcb17fe4f2b2a86e042f59b963

**Comment by jimharris** [comment]
Hi @liang2yan,

Thanks for finding this piece of data.  It is good to know that the issue occurs also with only one core on the target.

If this is the exact same as #498 though, except for the number of cores used, I would rather just note this piece of data in #498, and close this issue.

-Jim

**Comment by liang2yan** [comment]
close this issue for jim's suggestion.
