### ISSUE TITLE
The hotplug VM image  is missing in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#542]
Logs in NIGHTLY test:
test/nvme/hotplug.sh intel (This case runs in fedora-07 server before, now in fedora-03)
--Hotplug VM image not found; skipping test.

## Expected Behavior
hotplug.sh passed or failed.

## Current Behavior
hotplug.sh skipped.

## Possible Solution
Try to find the missing hotplug VM image and put on server.

## Steps to Reproduce
1. cd SPDK dir
2. run test/nvme/hotplug.sh, or look at logs in fedora-03 server.
https://ci.spdk.io/spdk/builds/review/b9aff3a035ec926a6a5f8db1bb287964d84500d6.1544771477/fedora-03/build.log (search "Hotplug VM image not found")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 7245134ab0bb46dcb17fe4f2b2a86e042f59b963

**Comment by wanghailiangx** [comment]
A patch is to disable the case temporarily.
https://review.gerrithub.io/#/c/spdk/spdk/+/431097/

**Comment by peluse** [comment]
thanks for bringing this up! Why are you prosing to disable the test as opposed to fixing the missing VM image? Or is there something more to this that I'm not seeing?

**Comment by jimharris** [comment]
I've asked @Seth5141 to check fedora-07 fo this image.  If it's there he'll copy it to fedora-03.

Then we could close this issue, but we'll need to follow up with a BKM/Trello card/new GitHub issue for this image moving forward.  Would be better if this hotplug test could just rely on some image we're already using for automated testing.

**Comment by Seth5141** [comment]
@jimharris Sorry, it's not on that machine. I must have lost it in translation during one of the upgrades. (FC25-26-28). I am happy to either create a new one, or find a way to use one of the other images to do this test since I am (most likely) the one that deleted it.

**Comment by jimharris** [comment]
@Seth5141 - let's find someone else to modify this test to use one of the existing VM images.  We'll find some other way to pushing you.  :-)

@nedved1 or @pawelkax - would one of you be willing to take a look at this?  I think we'll still disable this test for now, but leave this issue open.  I'm hoping one of the images we use for vhost testing could also be used for this nvme hotplug test.

**Comment by jimharris** [comment]
Or @wanghailiangx - if you want to look at this that would be great too.

**Comment by jimharris** [comment]
@pawelkax correctly pointed out over IRC that this isn't just a NIGHTLY issue.  Which means it's even more important that we address this issue.  And once we do, we should fail this hotplug.sh test instead of just printing a warning message and skipping it.

**Comment by pawelkax** [comment]
@jimharris, @Seth5141, I submitted patch that should solve this issue https://review.gerrithub.io/#/c/spdk/spdk/+/437673/ .
Need to be verified by Test Pool.

**Comment by jimharris** [comment]
Thanks @pawelkax.  This patch failed, but seems due to qemu-img missing on some of the Jenkins test systems:

 23:33:45	# qemu-img create -b /home/sys_sgsw/vhost_vm_image.qcow2 -f qcow2 /home/sys_sgsw/vhost_vm_image_qcov.qcow2
test/nvme/hotplug.sh: line 107: qemu-img: command not found
  23:33:45	# on_error_exit
  23:33:45	# set +e
  23:33:45	# kill -9

**Comment by pawelkax** [comment]
@jimharris I ran hotplug.sh test on my local machine. Test failed. @darsto is investigating reason of this failure.

**Comment by darsto** [comment]
Apparently I broke the entire hotplug functionality a few weeks ago. Here's the fix - https://review.gerrithub.io/c/spdk/spdk/+/438243

Since @pawelkax is out on vacation till WW1.5, can someone take over this issue?

**Comment by darsto** [comment]
This will need some more work. Originally, the nvme hotplug test just started a fedora VM, copied over the spdk binary inside, and then run that binary in the VM.

The copied binary will only work if it was built on a similar fedora-like system and clearly it won't work on our Jenkins CI, which can randomly use either Ubuntu or Fedora machine to run the entire test.

We already have a test for vhost which starts a VM and then compiles the SPDK inside, but that's fairly time expensive and we don't want to do that here. There are various optimization/enhancement opportunities, but as a first step we should consider just setting up VMs that are compatible with the host system they will be running on.

**Comment by darsto** [comment]
@nedved1 can you please look into setting up the VM images on those machines that run nvme hotplug test?

**Comment by nedved1** [comment]
I' ve created and uploaded new VM image to fedora-03 and Jenkins. Added some changes to Pawel's patch https://review.gerrithub.io/#/c/spdk/spdk/+/437673/ . In the future we could add to the script dynamically creating vm image with vagrant.

**Comment by nedved1** [comment]
Triggering some tests for hotplug showed that hotremove app can fail occasionally during hotremove.
https://ci.spdk.io/spdk/builds/review/bd027358604b2f01c8000239f857b88147f53074.1548709786
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_21423.html

**Comment by darsto** [comment]
This is blocked by #646

**Comment by karlatec** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/468807

**Comment by karlatec** [comment]
Fixed by mentioned patch. I made a typo in commpit message and referenced issue 524 instead of 542, so it didn't close automatically. Closing now.
