### ISSUE TITLE
setup.sh: cleanup_linux tries to delete too many entries in /dev/shm

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#543]
@lhoswdev found this in one of the logs:

https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/17537/archive/nvmf_phy_autotest/build.log

The problem is that setup.sh uses echo /dev/shm/*.  echo will put all of the entries on the same line and egrep will match the whole line.  There's a directory in /dev/shm (not associated with one of our spdk trace files) and the rm fails.

@lhoswdev already has a fix for this, so assigning this issue to him.

**Comment by lhoswdev** [comment]
Submitted https://review.gerrithub.io/#/c/spdk/spdk/+/437380 for review.

**Comment by lhoswdev** [comment]
Merged into master, commit fe3490987, on Dec 18, 2018.
