### ISSUE TITLE
Cannot unsubscribe SPDK mailing list

### ISSUE THREAD

**Issue by YamboZhou** [spdk/spdk#546]
I want to change my acceptation mail of SPDK mailing list. But it cannot work according to the steps of https://lists.01.org/mailman/listinfo/spdk.

## Expected Behavior
When enter the email address and click the *unsubscribe* button, the confirmation message is supposed to be sent to my email.   

## Current Behavior
Can not receive confirmation message.

## Steps to Reproduce

1. Enter the email address on https://lists.01.org/mailman/listinfo/spdk.
2. Click the button  named *Unsubscribe or edit options*.
3. In the next page, click the button named "Unsubscribe".
4. Check whether the email receive the confirmation message.

**Comment by YamboZhou** [comment]
My e-mail address is yambo_z@sina.com.

Thanks Jim.

**Comment by jimharris** [comment]
Hi @YamboZhou,

This e-mail address is not in the SPDK mailing list membership.  Is it possible that you have registered a different e-mail address, and that address is getting forwarded to your sina.com account?

-Jim

**Comment by jimharris** [comment]
Closing this issue.  The mailing list is operating as intended.  But comments can still be made on this issue to help narrow this down further.

**Comment by YamboZhou** [comment]
There might be a little misunderstanding. 

Thanks Jim.

**Comment by mkvaddi-svg** [comment]
Need help. How do i get email confirmation for the presentation i have presented in SPDK sessions? Appreciated help.
