### ISSUE TITLE
*ERROR*: Could not create malloc disk

### ISSUE THREAD

**Issue by xxks-kkk** [spdk/spdk#548]
For unknown reason, `hello_bdev` example program gives the following error message:

```
Starting SPDK v18.07 / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: hello_bdev -c 0x1 --legacy-mem --file-prefix=spdk_pid20826 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid20826/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 530:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
vbdev_passthru.c: 374:vbdev_passthru_init: *NOTICE*: conf parse matched: Malloc1
bdev_malloc.c: 408:create_malloc_disk: *ERROR*: malloc_buf spdk_dma_zmalloc() failed
bdev_malloc.c: 485:bdev_malloc_initialize: *ERROR*: Could not create malloc disk
bdev.c: 797:spdk_bdev_initialize: *ERROR*: bdev modules init failed
thread.c: 399:spdk_io_device_unregister: *ERROR*: io_device 0x6f0e10 not found
hello_bdev: thread.c:400: spdk_io_device_unregister: Assertion `false' failed.
Aborted (core dumped)
```

I check the hugepages and it seems OK to me

```
$ cat /proc/meminfo |grep HugePages
AnonHugePages:   1492992 kB
ShmemHugePages:        0 kB
HugePages_Total:    1024
HugePages_Free:     1024
HugePages_Rsvd:        0
HugePages_Surp:        0
```

I'm not sure what's going on here. Everything works fine on the same machine.

## Current Behavior
See above

## Context (Environment including OS version, SPDK version, etc.)

- Ubuntu 16.04
- SPDK 18.07

**Comment by YamboZhou** [comment]
Hi @xxks-kkk
Could you please provide the content of your bdev configuration file (bdev.conf)?

Seems like the size of malloc bdev which you created larger than remaining huge pages on your machine.

Thanks.

**Comment by xxks-kkk** [comment]
@YamboZhou Here is my `bdev.conf` (same as the one provided by spdk `hello_bdev` example)

```
[Passthru]
  PT Malloc1 PT0
[Malloc]
  NumberOfLuns 2
  LunSizeInMB  16
```

**Comment by jimharris** [comment]
Hi @xxks-kkk - I've tried this same test on my system using latest master, v18.10 and v18.07 and don't see any issues.  This is using the same bdev.conf file as you.

You said "Everything works fine on the same machine." - do you mean you have other SPDK applications you're running on this system that work fine?  It's only hello_bdev that's failing?

If you're still hitting this problem, I'd be curious if you see any changes with v18.10 or latest master.

**Comment by xxks-kkk** [comment]
Sorry for the late reply.

> Could be there is no continuous 16MB memory? How long has the system been up?

It's not very long. Only about 1.5 month approximately.

> Have you tried on a newer version of SPDK (and corresponding DPDK)?

I haven't yet bumped the SPDK version as there is some drastic change in terms of `libspdk.so`. My current code relies on dynamic link with `libspdk.so`. However, with the latest SPDK version, it seems take more steps to build `libspdk.so` out of box. 

I'll give a try tomorrow to see if rebooting the machine will help.

**Comment by xxks-kkk** [comment]
The only thing I tried to before on the machine is to add `IOMMU` to the grub as I don't like to run SPDK program in `sudo`. However, my change seems not working so I rollback the change, update the grub, and reboot the machine.
