### ISSUE TITLE
test/bdev/blockdev.sh run timeout in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#549]
From 12/11, test/bdev/blockdev.sh run timeout in NIGHTLY test on server "ubuntu14.04".
I reproduced on local. Logs as below:
```
 16:43:30       # /usr/src/fio/fio --ioengine=spdk_bdev --iodepth=128 --bs=192k --runtime=100 /home/wanghailiang/spdk20180605_debug_2/test/bdev/bdev.fio --spdk_conf=./test/bdev/bdev.conf --spdk_mem=0
fio: verification read phase will never start because write phase uses all of runtime
......
sha1: verify failed at file raid0 offset 38535168, length 196608MiB/s,w=6556MiB/s][r=10.3k,w=34.0k IOPS][eta 01m:54s]
       Expected CRC: 93a4dd698d140f52552be58a354808b5150f7a97
       Received CRC: 27bc703bad9b30f1bb739ac737f0b54ae47b6923
fio: pid=15893, err=84/file:io_u.c:2030, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character
Jobs: 34 (f=34): [w(2),X(8),V(1),w(2),X(1),w(5),X(2),w(1),X(2),V(1),X(1),w(1),X(2),w(1),X(1),w(6),X(1),w(1),X(1),w(1),X(6)Jobs: 34 (f=34): [V(2),X(8),V(1),w(1),V(1),X(1),w(4),V(1),X(2),w(1),X(2),V(1),X(1),V(1),X(2),w(1),X(1),V(1),w(4),V(1),X(1),w(1),X(1),V(1),X(6),w(1),X(2),w(5),X(6),V(1),X(3),w(1),X(2),w(4)][7.8%][r=1786MiB/s,w=6471MiB/s][r=9524,w=34.5k IOPS][etaJobs: 34 (f=34): [V(1),w(1),X(8),V(1),w(2),X(1),w(4),V(1),X(2),w(1),X(2),w(1),X(1),w(1),X(2),w(1),X(1),V(1),w(4),V(1),X(1)
(endless)
```

## Expected Behavior
blockdev.sh run passed.

## Current Behavior
blockdev.sh run timeout.

## Possible Solution
Check recent merged code before 12/11.
Probably this is caused by "examples/bdev/fio_plugin/fio_plugin.c".

## Steps to Reproduce
1. cd SPDK dir
2. ./configure --with-rdma --with-fio=/usr/src/fio  && make clean && make -j
3. ./test/bdev/blockdev.sh
4. If blockdev.sh run failed, the 3 steps can restore.
./scripts/setup.sh reset
parted -s /dev/nvme0n1 mklabel msdos
HUGEMEM=8192 ./scripts/setup.sh
5. Or look at logs on "ubuntu14.04", https://ci.spdk.io/spdk/builds/review/b29eeea2b16e53e44a44aaa51d79e294e068aba7.1545050819/ubuntu14.04/build.log  (Look at the bottom)

## Context (Environment including OS version, SPDK version, etc.)
commit 9d11abfd0ee2518c39173ec88a031557e0ff7a54

**Comment by wanghailiangx** [comment]
Add: I reproduced this issue on local Fedora25, Linux kernel 4.13.10.

**Comment by wanghailiangx** [comment]
@changpe1 I set bdev.conf.in with:
only [Malloc] or only [RAID0],
[Malloc]
  NumberOfLuns 7
  LunSizeInMB 32
[RAID0]
  Name raid0
  StripSize 64
  NumDevices 2
  RaidLevel 0
  Devices Malloc4 Malloc5

There are also the same error logs as below:

10:23:04   #LD_PRELOAD=/home/wanghailiang/spdk20180605_debug_2/examples/bdev/fio_plugin/fio_plugin
 10:23:04       # /usr/src/fio/fio --ioengine=spdk_bdev --iodepth=64 --bs=64k --runtime=100 /home/wanghailiang/spdk20180605_debug_2/test/bdev/bdev.fio --spdk_conf=./test/bdev/bdev.conf --spdk_mem=0
......
fio-3.6-34-g5eac
Starting 124 threads
Starting SPDK v19.01-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid8138 ]
EAL: Detected 88 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid8138_unix
EAL: Probing VFIO support...
thread.c: 464:spdk_get_thread: *ERROR*: No thread allocated
thread.c: 683:spdk_io_device_register: *ERROR*: spdk_io_device_register called from non-SPDK thread
thread.c: 464:spdk_get_thread: *ERROR*: No thread allocated
thread.c: 683:spdk_io_device_register: *ERROR*: spdk_io_device_register called from non-SPDK thread
bdev.c:3614:spdk_bdev_open: *ERROR*: Cannot open bdev from non-SPDK thread.
part.c: 313:spdk_bdev_part_base_construct: *ERROR*: could not open bdev Malloc0
vbdev_gpt.c: 143:spdk_gpt_base_bdev_init: *ERROR*: cannot construct gpt_base*** Error in `/usr/src/fio/fio': corrupted double-linked list: 0x00007f4fe40072c0 ***

**Comment by wanghailiangx** [comment]
I found where was build stop on server "ubuntu14.04", 
```
EAL: PCI device 0000:87:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
Build timed out (after 10 minutes). Marking the build as failed.
Build was aborted
```
while the case passed on local with "EAL: Probing VFIO support... ."

**Comment by darsto** [comment]
SPDK Crypto module assumes spdk_dma_malloc() memory is physically contiguous, which is not true when using uio_pci_generic. Besides fio failures, there should be also random memory corruptions on the system. I'll look into this.

**Comment by peluse** [comment]
@darsto can you say some more about the crypto comment, specifically what do you see in the logs that ties this failure to that statement.  Also, I assume you are talking about this:
   io_ctx->cry_iov.iov_base = spdk_dma_malloc(total_length, 0x10, NULL);
And where is the code making an assumption about being physically contiguous? That seems plausible for QAT, what else were you thinking?

**Comment by darsto** [comment]
@peluse I have pushed a patch that does a clumsy attempt to fix this - 
 https://review.gerrithub.io/c/spdk/spdk/+/439345 - let's continue the discussion on gerrithub.

**Comment by peluse** [comment]
Everything we know about this says its addressed by https://review.gerrithub.io/c/spdk/spdk/+/440988 which is now merged

We may alter the implementation post release but I'm considering this closed, @wanghailiangx let me know if you still anything like this.  Thanks!

**Comment by wanghailiangx** [comment]
@peluse 
But blockdev.sh still run timeout in NIGHTLY test. If this issue need reopen?
Please view https://review.gerrithub.io/#/c/spdk/spdk/+/393768/
fedora-03 and ubuntu14.04 servers.

**Comment by jimharris** [comment]
This looks like a different failure signature.  Closing this issue again.  Let's file a new issue for the new failure signature.
