### ISSUE TITLE
The practical strip size of RAID bdev doesn't match the setting

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#550]
The practical strip size of RAID bdev doesn't match the setting.

## Expected Behavior
The practical strip size of RAID bdev match the setting.

## Current Behavior
```
./rpc.py construct_raid_bdev -n raid0 -s 64 -r 0 -b "Malloc0"
./rpc.py get_bdevs
{
    "claimed": false,
    "driver_specific": {
      "raid": {
        "destruct_called": 0,
        "raid_level": 0,
        "state": 0,
        "num_base_bdevs": 1,
        "strip_size": 128,
        "base_bdevs_list": [
          "Malloc0"
        ],
        "num_base_bdevs_discovered": 1
      }
    },
```

## Steps to Reproduce

```
1. ./rpc.py construct_malloc_bdev 512 512
2. ./rpc.py construct_raid_bdev -n raid0 -s 64 -r 0 -b "Malloc0"
3. ./rpc.py get_bdevs
```

## Context (Environment including OS version, SPDK version, etc.)

commit:23a95386c86c8b02bb9f59b5fead761ef2016a5e

**Comment by jimharris** [comment]
Is it reporting strip size in units of LBAs?

**Comment by peluse** [comment]
Something fishy for sure.  Added a few prints in create and json info:
bdev_raid.c:1260:raid_bdev_create: *NOTICE*: raid_bdev 0x614000000040 sz 64
bdev_raid.c: 674:raid_bdev_dump_info_json: *NOTICE*: raid_bdev 0x614000000040 sz 16

Note how the stripe size for the same bdev is different from creation to display.  The value 16 is also what is shown in the get_bdevs output.

Will dig in a little more later....

**Comment by peluse** [comment]
OK, pretty easy to sport :) In raid_bdev_configure() the stripe size is being converted to blocks.

raid_bdev->strip_size = (raid_bdev->strip_size * 1024) / blocklen;

I assume elsewhere in the code this is expected to be in blocks.  We could add another "display" element to the raid_bdev struct or just re-convert in the info json dump function.... @jimharris whatcha think?

**Comment by jimharris** [comment]
I agree it's confusing.  But I don't think we can change the existing one.  I'm not sure if anyone (Kunal's team?) is expecting that value to be in blocks.

I guess we could add a new entry "stripe_size_in_kb" but all of the information to calculate it is already there - we know the block size of the RAID volume and we know how many blocks constitute a stripe.

I'd argue that it's the creation side that should be changed if anything.  I'm thinking about the DIF/DIX stuff that Shuhei is working on.  What happens when we want to do RAID on top of extended sector size bdevs?  Then expressing the stripe size in blocks makes the most sense, and creating the RAID device should be in terms of blocks instead of kilobytes.

**Comment by peluse** [comment]
yeah the  stripe_size_in_kb element is what I meant with my cryptic comment on a display only field. We just keep that element in kb and use it for display purposes and don't have to worry about messing with any other code thats expecting it in blocks. But yeah, DIF/DIX could be confusing even with that.

I can push a patch with the display element in there and see what people think, easy enough to solicit feedback that way... later today sometime

**Comment by peluse** [comment]
See https://review.gerrithub.io/#/c/spdk/spdk/+/437873

**Comment by shuhei-matsumoto** [comment]
@peluse @jimharris 

Yes, I'm afraid that KB based is complicated for RAID on top of the DIF enabled volume. DDF (Disk Data Format) is also LBA based.

I will raise a discussion if I'm prepared. That time is not coming yet and so current implementation is OK for now. https://review.gerrithub.io/#/c/spdk/spdk/+/437873 will be fine.

**Comment by darsto** [comment]
Bug scrub: We'll add a new param strip_size_kb and deprecate the old one. Hopefully we'll be able to remove the old one in a subsequent release.

**Comment by peluse** [comment]
@jimharris just to be perfectly clear, you were thinking of adding a new API like construct_raid_bdev2 or something that uses the new parameter right? Thus leaving the old version alone so it works as it did before giving anyone using this API a chance to update to the new API name and the new param before the next release. I'm thinking I'll just update the UT to the new API though and leave the deprecated one uncovered for UT.

**Comment by jimharris** [comment]
I was hoping we could keep construct_raid_bdev - is it possible for 19.01 to accept either strip_size or strip_size_in_kb for specifying the strip size?  And then add a strip_size_in_kb for the get_bdevs data for a RAID volume.

Then in 19.04, we only allow specifying the strip size in construct_raid_bdev using strip_size_in_kb, and we remove strip_size from the get_bdevs data.

**Comment by peluse** [comment]
OK, glad I asked because typically one would introduce a whole new API so as not break the old one.  If I add a 2nd parm to the old API then I'm breaking it so might as well just make it KB as what would be the point? I didn't look at the possibility of having an optional arg in the RPC API, I just assume that's not possible without breaking the API but I'll look a little closer... thanks!

**Comment by jimharris** [comment]
I was thinking that we change strip_size to optional, add strip_size_in_kb as also optional, and then enforce in the RPC handler that either strip_size *or* strip_size_in_kb is specified.

Then in 19.04, we remove strip_size and make strip_size_in_kb required.

**Comment by peluse** [comment]
@ChenWang01 @jimharris please see https://review.gerrithub.io/c/spdk/spdk/+/437873

**Comment by ChenWang01** [comment]
@fshenx Can use the ./rpc.py construct_raid_bdev -n raid0 -r 0 -b "Malloc0" command to check the strip_size and strip_size_kb with none value.

**Comment by peluse** [comment]
@fshenx I'm not sure what you mean.  Are you saying that you tried without either option and didn't get an error? Are you sure you are using the right patch? See below, I've tested this a few times:

[peluse@pels-64 spdk]$ sudo ~/spdk/scripts/rpc.py construct_null_bdev Null0 8192 4096
Null0
[peluse@pels-64 spdk]$ sudo ~/spdk/scripts/rpc.py construct_raid_bdev -n raid0 -r 0 -b Null0
Exception:
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0",
  "method": "construct_raid_bdev",
  "id": 1,
  "params": {
    "name": "raid0",
    "raid_level": 0,
    "base_bdevs": [
      "Null0"
    ]
  }
}
response:
{
  "code": -32602,
  "message": "strip size not specified"
}
[peluse@pels-64 spdk]$

**Comment by fshenx** [comment]
@peluse 
Sorry, that's not my comment.
