### ISSUE TITLE
Docs are missing info on RAID bdev module

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#551]
See https://spdk.io/doc/bdev.html - there is no section on RAID bdevs

**Comment by peluse** [comment]
Also here: https://spdk.io/doc/jsonrpc.html

**Comment by darsto** [comment]
@Maciej-Szwed any update?

**Comment by darsto** [comment]
@Maciej-Szwed

**Comment by Maciej-Szwed** [comment]
Starting work on that right now.

**Comment by Maciej-Szwed** [comment]
Patch is ready: https://review.gerrithub.io/c/spdk/spdk/+/455239

**Comment by jimharris** [comment]
I added my +2.  One more +2 and we can merge it and close this issue.
