### ISSUE TITLE
qemu crashed after guest os ( kernel version <= v3.18 )reboot 

### ISSUE THREAD

**Issue by wanghonghuigithub** [spdk/spdk#554]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

qemu crashed after guest os ( kernel version <= v3.18 )reboot 
## Expected Behavior

guest os reboot success
## Current Behavior

qemu crash
## Steps to Reproduce

1.start spdk
2.start a vm with guest os version <= v3.18
3.guest os login 
4.guest os reboot
5.qemu crash
## Context (Environment including OS version, SPDK version, etc.)

qemu:v3.1.0-rc4
spdk: v18.10
guest os :<=v3.18 such as v2.6.32-431

gdb core:
#0  0x00007f07fb218277 in raise () from /lib64/libc.so.6
warning: File "/root/qemu-upstream/.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py".
To enable execution of this file add
	add-auto-load-safe-path /root/qemu-upstream/.gdbinit
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
Missing separate debuginfos, use: debuginfo-install boost-system-1.53.0-27.el7.x86_64 boost-thread-1.53.0-27.el7.x86_64 cyrus-sasl-lib-2.1.26-23.el7.x86_64 glib2-2.54.2-2.el7.x86_64 glibc-2.17-222.el7.x86_64 gmp-6.0.0-15.el7.x86_64 gnutls-3.3.26-9.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libaio-0.3.109-13.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libcurl-7.29.0-46.el7.x86_64 libfdt-1.4.6-1.el7.x86_64 libffi-3.0.13-11.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libidn-1.28-3.el7.x86_64 librados2-0.94.5-2.el7.x86_64 librbd1-0.94.5-2.el7.x86_64 libselinux-2.5-12.el7.x86_64 libssh2-1.4.3-8.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 libtasn1-4.10-1.el7.x86_64 libuuid-2.23.2-52.el7_5.1.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 nettle-2.7.1-8.el7.x86_64 nspr-4.19.0-1.el7_5.x86_64 nss-3.36.0-5.el7_5.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 nss-util-3.36.0-1.el7_5.x86_64 numactl-libs-2.0.9-7.el7.x86_64 openldap-2.4.39-7.el7.centos.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 p11-kit-0.23.5-3.el7.x86_64 pcre-8.32-17.el7.x86_64 pixman-0.34.0-1.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f07fb218277 in raise () from /lib64/libc.so.6
#1  0x00007f07fb219968 in abort () from /lib64/libc.so.6
#2  0x0000560bb84693fa in kvm_io_ioeventfd_del (listener=<optimized out>, section=0x7ffd64fdc300, match_data=<optimized out>, data=0, e=<optimized out>)
    at /root/qemu-upstream/accel/kvm/kvm-all.c:917
#3  0x0000560bb8456736 in address_space_add_del_ioeventfds (fds_old_nb=1, fds_old=0x560bbb4a96c0, fds_new_nb=0, fds_new=0x0, as=0x560bb90d4000 <address_space_io>)
    at /root/qemu-upstream/memory.c:781
#4  address_space_update_ioeventfds (as=as@entry=0x560bb90d4000 <address_space_io>) at /root/qemu-upstream/memory.c:844
#5  0x0000560bb8456e68 in memory_region_transaction_commit () at /root/qemu-upstream/memory.c:1040
#6  0x0000560bb864bbed in pci_update_mappings (d=d@entry=0x560bbbb60850) at hw/pci/pci.c:1316
#7  0x0000560bb864befe in pci_do_device_reset (dev=0x560bbbb60850) at hw/pci/pci.c:292
#8  0x0000560bb864bfc2 in pcibus_reset (qbus=0x560bbaa549a0) at hw/pci/pci.c:320
#9  0x0000560bb85c3cb9 in qbus_reset_one (bus=0x560bbaa549a0, opaque=<optimized out>) at hw/core/qdev.c:259
#10 0x0000560bb85c4c18 in qdev_walk_children (dev=0x560bbaa53120, pre_devfn=0x0, pre_busfn=0x0, post_devfn=0x560bb85c5250 <qdev_reset_one>, 
    post_busfn=0x560bb85c3c80 <qbus_reset_one>, opaque=0x0) at hw/core/qdev.c:559
#11 0x0000560bb85c8398 in qbus_walk_children (bus=0x560bba5cf410, pre_devfn=0x0, pre_busfn=0x0, post_devfn=0x560bb85c5250 <qdev_reset_one>, 
    post_busfn=0x560bb85c3c80 <qbus_reset_one>, opaque=0x0) at hw/core/bus.c:59
#12 0x0000560bb85c852d in qemu_devices_reset () at hw/core/reset.c:69
#13 0x0000560bb84cc0b6 in pc_machine_reset () at /root/qemu-upstream/hw/i386/pc.c:2284
#14 0x0000560bb8560476 in qemu_system_reset (reason=reason@entry=SHUTDOWN_CAUSE_GUEST_RESET) at vl.c:1673
#15 0x0000560bb8560690 in main_loop_should_exit () at vl.c:1859
#16 main_loop () at vl.c:1888
#17 0x0000560bb83f991b in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at vl.c:4648

**Comment by darsto** [comment]
This is a bug in either the host kernel or QEMU. You might want to submit it on the QEMU's issue tracker. There's nothing SPDK can fix here, so I'm forced to close this issue.
