### ISSUE TITLE
NVMF_LVOL test case fails when kernel initiator is used (intermittent)

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#555]
## Expected Behavior
The NVMF_LVOL (test/nvmf/lvol/nvmf_lvol.sh) test case should run properly in the test pool whether we use the kernel initiator or the SPDK initiator to submit I/O to the lvols exposed by our NVMe-oF target.

## Current Behavior
On the v18.10.x branch of SPDK, we use the kernel initiator in the NVMF_LVOL tests. reviewws run through the Chandler test pool will fail about 20% of the time during this test. Please see the output from what this failure looks like from the tip of v18.10.x (commit: 2f1ac3644a4dfd55).

build log:
~~~
 18:54:08	# /home/sys_sgsw/build_pool/agent/repo/test/nvmf/lvol/../fio/nvmf_fio.py 262144 64 randwrite 10 verify
Found devices:  ['nvme0n1', 'nvme0n2', 'nvme0n3', 'nvme0n4', 'nvme0n5', 'nvme0n6']
['/dev/nvme0n1', '/dev/nvme0n2', '/dev/nvme0n3', '/dev/nvme0n4', '/dev/nvme0n5', '/dev/nvme0n6']
fio: verification read phase will never start because write phase uses all of runtime
job0: (g=0): rw=randwrite, bs=(R) 256KiB-256KiB, (W) 256KiB-256KiB, (T) 256KiB-256KiB, ioengine=libaio, iodepth=64
fio: verification read phase will never start because write phase uses all of runtime
job1: (g=0): rw=randwrite, bs=(R) 256KiB-256KiB, (W) 256KiB-256KiB, (T) 256KiB-256KiB, ioengine=libaio, iodepth=64
fio: verification read phase will never start because write phase uses all of runtime
job2: (g=0): rw=randwrite, bs=(R) 256KiB-256KiB, (W) 256KiB-256KiB, (T) 256KiB-256KiB, ioengine=libaio, iodepth=64
fio: verification read phase will never start because write phase uses all of runtime
job3: (g=0): rw=randwrite, bs=(R) 256KiB-256KiB, (W) 256KiB-256KiB, (T) 256KiB-256KiB, ioengine=libaio, iodepth=64
fio: verification read phase will never start because write phase uses all of runtime
job4: (g=0): rw=randwrite, bs=(R) 256KiB-256KiB, (W) 256KiB-256KiB, (T) 256KiB-256KiB, ioengine=libaio, iodepth=64
fio: verification read phase will never start because write phase uses all of runtime
job5: (g=0): rw=randwrite, bs=(R) 256KiB-256KiB, (W) 256KiB-256KiB, (T) 256KiB-256KiB, ioengine=libaio, iodepth=64
fio-3.3
Starting 6 threads
rdma.c: 526:spdk_nvmf_rdma_set_ibv_state: *NOTICE*: IBV QP#3 changed to: IBV_QPS_ERR
rdma.c: 526:spdk_nvmf_rdma_set_ibv_state: *NOTICE*: IBV QP#2 changed to: IBV_QPS_ERR
rdma.c: 526:spdk_nvmf_rdma_set_ibv_state: *NOTICE*: IBV QP#1 changed to: IBV_QPS_ERR
rdma.c: 595:spdk_nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 66
rdma.c: 595:spdk_nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 43
rdma.c: 595:spdk_nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 29
rdma.c: 564:spdk_nvmf_rdma_mgmt_channel_destroy: *ERROR*: Pending I/O list wasn't empty on channel destruction
rdma.c: 564:spdk_nvmf_rdma_mgmt_channel_destroy: *ERROR*: Pending I/O list wasn't empty on channel destruction
rdma.c: 564:spdk_nvmf_rdma_mgmt_channel_destroy: *ERROR*: Pending I/O list wasn't empty on channel destruction
rdma.c: 526:spdk_nvmf_rdma_set_ibv_state: *NOTICE*: IBV QP#0 changed to: IBV_QPS_ERR
fio: io_u error on file /dev/nvme0n3: Input/output error: write offset=524288, buflen=262144
job2: No I/O performed by libaio, perhaps try --debug=io option for details?
fio: io_u error on file /dev/nvme0n4: Input/output error: write offset=524288, buflen=262144
job3: No I/O performed by libaio, perhaps try --debug=io option for details?
fio: pid=718008, err=5/file:io_u.c:1833, func=io_u error, error=Input/output error
fio: pid=718009, err=5/file:io_u.c:1833, func=io_u error, error=Input/output error
fio: io_u error on file /dev/nvme0n6: Input/output error: write offset=524288, buflen=262144
job5: No I/O performed by libaio, perhaps try --debug=io option for details?
fio: io_u error on file /dev/nvme0n5: Input/output error: write offset=524288, buflen=262144
job4: No I/O performed by libaio, perhaps try --debug=io option for details?
fio: pid=718011, err=5/file:io_u.c:1833, func=io_u error, error=Input/output error
fio: pid=718010, err=5/file:io_u.c:1833, func=io_u error, error=Input/output error

(FIO output truncated for brevity)

Disk stats (read/write):
  nvme0n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme0n2: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme0n3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme0n4: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme0n5: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme0n6: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
FIO completed with code 4
~~~

dmesg log (relevant portion):
~~~
[ 1471.864116] nvme nvme0: creating 3 I/O queues.
[ 1471.926052] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 192.168.100.8:4420
[ 1482.143141] nvme nvme0: I/O 0 QID 0 timeout, reset controller
[ 1482.198654] block nvme0n2: no path available - requeuing I/O
[ 1482.198683] block nvme0n3: no path available - requeuing I/O
[ 1482.198685] block nvme0n4: no path available - requeuing I/O
[ 1482.198687] block nvme0n4: no path available - requeuing I/O
[ 1482.198688] block nvme0n3: no path available - requeuing I/O
[ 1482.198689] block nvme0n3: no path available - requeuing I/O
[ 1482.198691] block nvme0n6: no path available - requeuing I/O
[ 1482.198691] block nvme0n4: no path available - requeuing I/O
[ 1482.198693] block nvme0n6: no path available - requeuing I/O
[ 1482.198694] block nvme0n5: no path available - requeuing I/O
[ 1482.295851] nvme nvme0: Reconnecting in 10 seconds...
[ 1482.295854] print_req_error: I/O error, dev nvme0c1n3, sector 1280
[ 1482.295861] print_req_error: I/O error, dev nvme0c1n4, sector 1024
[ 1482.297517] print_req_error: I/O error, dev nvme0c1n4, sector 1280
[ 1482.298261] print_req_error: I/O error, dev nvme0c1n5, sector 1280
[ 1482.298967] print_req_error: I/O error, dev nvme0c1n6, sector 1024
[ 1482.299673] print_req_error: I/O error, dev nvme0c1n6, sector 1280
[ 1487.327130] nvme nvme0: failed nvme_keep_alive_end_io error=10
[ 1492.466161] nvme nvme0: creating 3 I/O queues.
[ 1492.525888] nvme nvme0: Successfully reconnected (1 attempts)
[ 1492.564262] nvme0c1n1: detected capacity change from 0 to 10485760
[ 1492.580174] nvme0c1n2: detected capacity change from 0 to 10485760
[ 1492.598214] nvme0c1n3: detected capacity change from 0 to 10485760
[ 1492.626173] nvme0c1n4: detected capacity change from 0 to 10485760
[ 1492.676175] nvme0c1n5: detected capacity change from 0 to 10485760
[ 1492.702184] nvme0c1n6: detected capacity change from 0 to 10485760
[ 1494.838007] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
~~~

## Possible Solution
We are not sure exactly what is going on, but the error log indicates an interestig shutdown path. In the typical qpair error case, we get an asynchronous event from the fabric, then we start the qpair shutdown process which involves transitioning the qpair to an error state, sending out a tracer request on the send and receive queues, waiting for that request to drain through the queue (ensuring that the qpair is empty), then deleting the send and receive queues. However, from the log above it appears that the queue pair is being deleted before all of the requests have been flushed. This implies we are taking another path for destroying these queue pairs. I still haven't plumbed this path out though.

@ZiyeYang has also brought up the possibility that we are not properly destroying queue pairs which may explain why we are seeing extra requests in the destroyed queue pairs.

## Steps to Reproduce
Several people have tried to reproduce this failure locally and have been unable to do so with any regularity. There is currently no known way of reproducing this bug other than pushing v18.10.x reviews to the build pool until fedora-03 exhibits the failure.

## Context (Environment including OS version, SPDK version, etc.)
Fedora-03 has the following environment:
spdk: v18.10.1
fio: v3.3
kernel: Linux-4.18.9-200.fc28.x86_64
OS: Fedora 28

**Comment by Seth5141** [comment]
I was able to rule out a couple of things today:
The failure is apparently taking the normal disconnect path. i.e. The target gets a disconnect event from the initiator and tears down the qpairs in the normal way. The proof of that is in the following build log. https://ci.spdk.io/spdk/builds/review/615db6753d2cc02799e62524c5543e4834acc639.1545336164/.
The qpairs disconnect in response to a timeout on the initiator side from one of the qpairs. See nvme_rdma_timeout in linux/drivers/nvme/host/rdma.c for the path we go down there.
Why we are getting timeouts in the initiator, I don't know. It appears to happen every build, even on ones that pass. Please see logs at:
https://ci.spdk.io/spdk/builds/review/615db6753d2cc02799e62524c5543e4834acc639.1545328800/fedora-03/
https://ci.spdk.io/spdk/builds/review/615db6753d2cc02799e62524c5543e4834acc639.1545326742/fedora-03/
It appears that FIO only picks up on this failure sometimes. That is why we don't see it fail every time.

I have replicated the kernel configuration of fedora-03 on my local machine, but am still unable to produce this error, or any of the dmesg output. So I don't know if  I am any closer to finding the root cause.

**Comment by optimistyzy** [comment]
@Seth5141 Can you try this branch
https://review.gerrithub.io/437585

**Comment by Seth5141** [comment]
OK, I believe I have this root caused. The issue is that when we have a small number of buffers, and a large number of poll groups, one, two, or three poll groups can starve the others of I/O. I believe I can prove this on two fronts:
1. If you run the NVMe-oF target on just a single thread, this error cannot be reproduced on Fedora-03.
2. When you drastically limit the number of buffers that a qpair is allowed to reap on that given poll group per polling period, the issue can no longer be reproduced. See https://review.gerrithub.io/#/c/spdk/spdk/+/438112/.

For further proof that it is in fact the number of I/O buffers causing this issue (see above for the initial discovery), when I increase the number of buffers to 4 times their natural level (see rtransport->data_buf_pool in rdma.c), the issue can no longer be reproduced. Conversely, when I reduce the number of buffers to half, this issue hits every time we run the lvol tests.

I don't think that https://review.gerrithub.io/#/c/spdk/spdk/+/438112/ is a good solution. I think there are at least a couple possible long term solutions:

1. We dynamically configure the maximum number of buffers each qpair on each poll group can reap. num_pg_buffers = num_buffers/num_poll_groups_in_transport.
num_qp_buffers = num_pg_buffers/num_qpairs_in_buffer.

2. We make the rtransport->data_buf_pool into a poll_group specific data structure.

**Comment by optimistyzy** [comment]
starvation issue among multiple polling groups or single polling group can be solved，put the。shared。data buffer per group is not a good idea. Previously,  I remembered that this issue is solved, may be reintroduced but I  believe that we do not need per polling group.buffer, this avoids the root cause

**Comment by optimistyzy** [comment]
@Seth5141

**Comment by optimistyzy** [comment]
Also making sure that we can reproduce without lvol. I mean that if the buffer request handling in lvol is not fair, there will be issue in lvol but not rdma transport.

**Comment by jimharris** [comment]
What if we take the same approach as the bdev_io per thread caches?  Have each poll group take some number (64?) of buffers out of the pool when the poll group is created. When a buffer is freed, check if its poll groups buffer list has 64 buffers. If not, put it in the per poll group list, otherwise put it in the global pool.

**Comment by optimistyzy** [comment]
@Seth5141 I provided a patch for NVMe TCP transport as a reference, to allocate at least 1 buffer for the each tcp polling group. If you want to do it in rdma transport, you can also follow this patch as an example. If you want to use a buffer cache list as Jim suggested, you need to change the data buf structure, otherwise you cannot compose as a list:  

https://review.gerrithub.io/#/c/spdk/spdk/+/438164

**Comment by Seth5141** [comment]
Hi @optimistyzy,

I don't think there is any way that this is related to the LVOL module. As I mentioned earlier, The requests are getting stuck in the NEED_BUFFER stage of the RDMA state machine. The only thing that can keep a request in that stage is a failed call to spdk_nvmf_rdma_request_parse_sgl which is trying to allocate a buffer from the RDMA buffer pool.

@jimharris I like the per-poll group caching idea. I will have to look at the bdevio code to see how you manage stuff like ensuring the pool is large enough to accommodate all of the poll group caches and you don't run out before we get to the last module.

**Comment by benlwalker** [comment]
I agree with the direction of moving toward per-poll-group caches. It will probably be a slight performance improvement as well. To start with, just try to grab buffers out of the pool each time the group is created. If you don't have enough, just fail to create the poll group and print out a big error message. We can do something more complex later on.

**Comment by Seth5141** [comment]
@benlwalker Thanks for the feedback. I have put together a patch series (https://review.gerrithub.io/#/c/spdk/spdk/+/439434/) to implement per pg caching. Please let me know what you think.
I haven't verified this as a fix yet (since fed-03 is tied up running tests and  I still can't replicate this locally), but will find time to do that this week. 
To be honest, it is worrisome that I can't replicate this behavior on my local machine. One would think that an issue like this would be pretty ubiquitous. It makes me wonder if the underlying problem really is buffer starvation.
If I can verify this as a fix on fedora-03, I think we can be sure that buffer starvation is coming into play, but since I still can't replicate it locally, I don't think we know the real root cause.
So I know that dpdk pins its threads to a core, but can the OS still preempt a specific dpdk thread if it tries to run a process on that core? I don't know what the nice values are associated with DPDK processes or if they are scheduled in a higher priority list?
I am thinking that if it's possible for a dpdk thread to get preempted, that might be what is happening to cause the inequality.

**Comment by sashakot** [comment]
Hi, 
Could you please elaborate starvation theory?  If nvmf target allocates enough buffers to handle IO in the air based on network port and storage bandwidth, how can that happen?

**Comment by optimistyzy** [comment]
If there is enough buffer, there will not be starvation issue. Currently, each transport can be provided with fixed number of data buffers. If there are multiple cores configured for the NVMe-oF target, it means that the polling group on each core will compete for the fixed number of buffers, thus if there are no strategy provided, there be starvation issues.

**Comment by Seth5141** [comment]
@sashakot Thanks for the comment. Here is the actual flowchart of what I am observing. 1
1. Multiple qpairs are created on multiple poll groups.
2. The initiator submits as many requests as possible to each qpair.
3. When we poll the poll groups, the qpairs on the first n poll groups take all of the buffers in the shared buffer pool. in the n +1 poll group, it polls all of the recv's, finds that it doesn't have any buffers in the shared queue so it places them in the waiting_for_buffer state and exits.
4. On subsequent polling loops, the n + 1 poll group looks for work but doesn't find anything to do. this part is key. It only occurs when none of the queue pairs on that poll group receive any more recvs. Thus, we need an initiator that only sends a fixed number of requests at a time like fio. When no work is found, we never enter the function where we check for more free buffers and those requests stagnate.

If there are enough buffers to accommodate a full queue depth of the largest I/O on every queue pair on every poll group, this starvation issue goes away.
It is also true that this issue requires a bit of timing and cooperation from the initiator to actually hit. Either way, the issue is solved by introducing the per-pg buffer cache because a poll group will always be able to make forward progress on some number of requests.

**Comment by Seth5141** [comment]
Since the fix has been merged, I am closing this issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_68335.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_69801.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_69865.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_72458.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_73147.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_73149.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_75138.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @yupeng0921. log: https://ci.spdk.io/public_build/autotest-per-patch_75869.html
