### ISSUE TITLE
bdev: optimize the conversion of io offset

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#559]
Right now, function [spdk_bdev_bytes_to_blocks](https://github.com/spdk/spdk/blob/master/lib/bdev/bdev.c#L2303) in lib/bdev/bdev.c calculates offset of an io request by divising directly. Maybe it' better to use >> operator, which is faster than division.

## Expected Behavior

- Add member variable `blocklen_bits` to the struct [spdk_bdev](https://github.com/spdk/spdk/blob/master/include/spdk/bdev_module.h#L241). 

- Use right shift for offset:  `*offset_blocks = offset_bytes >> blocklen_bits; `

For example, for a block device with `blocklen` in 512 bytes, its `blocklen_bits` is 9. (_2^9=512_) For a request writring to position 1024, just calculate 1024>>9. 

## Current Behavior

Currently spdk_bdev_bytes_to_blocks function uses division for conversion.

## Possible Solution

Descirbed in section `Expected Behavior`.

Since this function is invoked frequently, maybe it's worthy to optimization. I'd like to send a patch, but discussion about whether needing such a patch would be nice.

## Steps to Reproduce

Not a bug, so no steps to reproduce.

## Context (Environment including OS version, SPDK version, etc.)

Latest code in master branch. commit id #0b20f2e552d978d84780e0ab968bb7fa65f7707e

**Comment by lorneli** [comment]
Maybe change the name of variable from `blocklen_bits` to `blocklen_shift`?

**Comment by shuhei-matsumoto** [comment]
Hi @lorneli 

Thank you for your nice proposal.
Why this may not be so noticeable is that many use cases have used read/write_blocks.

Bdev or bdev module will support T10 DIF and blocks size may become not power of 2.
Hence the following will be practical instead of block_len_bits. You will find reference in bdev/bdev.c.

	if (spdk_likely(spdk_u32_is_pow2(block_size)) {
		*offset_blocks = offset_bytes >> spdk_u32log2(block_size);
		*num_blocks = num_bytes >> spdk_u32log2(block_size);
	} else {
		*offset_blocks = offset_bytes / block_size;
		*num_blocks = num_bytes / block_size;
	}

By the way, can you submit the patch for this to Gerrit according to https://spdk.io/development/ ?

Thanks,
Shuhei

**Comment by lorneli** [comment]
@shuhei-matsumoto Thanks for your detailed anwer. I will submit the patch later.

**Comment by lorneli** [comment]
Hi @shuhei-matsumoto 

I'v sent a patch to Gerrit. https://review.gerrithub.io/c/spdk/spdk/+/438318

It would be great if you help to review this patch at your convenience.

**Comment by darsto** [comment]
Patch merged. Closing.

Thanks!
