### ISSUE TITLE
Error when installing spdk in qemu-nvme virtual machine

### ISSUE THREAD

**Issue by wengbaiyang** [spdk/spdk#560]
## Expected Behavior

I recently built the OpenChannelSSD runtime environment with qemu-nvme. I want to try the function of SPDK, but when I install SPDK in the system inside the virtual machine, I get an error in the make step.
But when I installed SPDK on the host machine, there is no such problem.

## Current Behavior

I followed the installation steps of spdk until I executed the make step and reported the following error.
Error is as follows：

`/root/spdk/mk/spdk.common.mk:302: recipe for target 'vhost_user.o' failed`
`make[3]: *** [vhost_user.o] Error 1`
`/root/spdk/mk/spdk.subdirs.mk:44: recipe for target 'rte_vhost' failed`
`make[2]: *** [rte_vhost] Error 2`
`/root/spdk/mk/spdk.subdirs.mk:44: recipe for target 'vhost' failed`
`make[2]: *** [vhost] Error 2`
`/root/spdk/mk/spdk.subdirs.mk:44: recipe for target 'lib' failed`
`meke: *** [lib] Error 2`

## Steps to Reproduce

1.Command to start the virtual machine is as follows：
`qemu-system-x86_64 ./ubuntu.img --enable-kvm -m 2G -drive file=./blknvme,id=myocssd,format=raw,if=none -device nvme,drive=myocssd,serial=deadbeef,lnum_pu=4,lstrict=1`

2.Execute the following command on the system you started:
`git clone https://github.com/spdk/spdk`
`cd spdk`
`git submodule update --init`
`sudo scripts/pkgdep.sh`
`./configure`
`make`

3.The above error will be reported when executing make.

## Context (Environment including OS version, SPDK version, etc.)

Host OS: 16.04
Host memory: 8G
Guest OS: 16.04
Guest Kernel: 4.20
SPDK: 18.10

**Comment by Comphix** [comment]
Hi Wengbai,

Could you paste more compiling logs before the below error?

/root/spdk/mk/spdk.common.mk:302: recipe for target 'vhost_user.o' failed
make[3]: *** [vhost_user.o] Error 1
/root/spdk/mk/spdk.subdirs.mk:44: recipe for target 'rte_vhost' failed
make[2]: *** [rte_vhost] Error 2

Thanks.

**Comment by wengbaiyang** [comment]
> Hi Wengbai,
> 
> Could you paste more compiling logs before the below error?
> 
> /root/spdk/mk/spdk.common.mk:302: recipe for target 'vhost_user.o' failed
> make[3]: *** [vhost_user.o] Error 1
> /root/spdk/mk/spdk.subdirs.mk:44: recipe for target 'rte_vhost' failed
> make[2]: *** [rte_vhost] Error 2
> 
> Thanks.

There are a lot of mistakes, here are some

`/root/spdk/dpdk/build/include/rte_memcpy.h:613:13: error: called from here
             _mm_storeu_si128((__m128i *)((uint8_t *)dst + 1 * 16), _mm_alignr_e
             ^
`

`/usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:185:1: error: inlining failed in call to always_inline ‘_mm_alignr_epi8’: target specific option mismatch
 _mm_alignr_epi8(__m128i __X, __m128i __Y, const int __N)
`

`/root/spdk/dpdk/build/include/rte_memcpy.h:597:9: error: called from here
         _mm_storeu_si128((__m128i *)((uint8_t *)dst + 7 * 16), _mm_alignr_epi8(
         ^
`

`/root/spdk/dpdk/build/include/rte_memcpy.h:594:9: error: called from here
         _mm_storeu_si128((__m128i *)((uint8_t *)dst + 4 * 16), _mm_alignr_epi8(
         ^
`

**Comment by pawelwod** [comment]
Try specyfing CPU model
https://wiki.qemu.org/Features/CPUModels

**Comment by wengbaiyang** [comment]
> Try specyfing CPU model
> https://wiki.qemu.org/Features/CPUModels

Thank you, the problem is solved, thank you very much
