### ISSUE TITLE
question: difference between event and msg in event framework

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#561]
Hi, 

I've found that there are two different message types in event framework. One of them is `spdk_event`, another is `spdk_msg`. Function `_spdk_reactor_run` dequeues batch of these two message types  and runs them per loop (function `_spdk_event_queue_run_batch` and `_spdk_msg_queue_run_batch`).

Here are their definitions :

```
struct spdk_event {                                                             
        uint32_t                lcore;                                             
        spdk_event_fn           fn;                                                
        void                    *arg1;                                             
        void                    *arg2;                                             
};      

struct spdk_msg {                                                                   
        spdk_msg_fn             fn;                                                 
        void                    *arg;                                               
};   
```
I guess that struct spdk_msg is used for passing work task between threads. One thread passes a task(function+arg) to the target thread via spdk_msg since the target thread has cpu cache of the data about this task, as mentioned in ["Message Passing and Concurrency"](https://spdk.io/doc/concurrency.html). 

But I haven't figured out the usage of struct spdk_event. In funtion `spdk_app_start`, the parameters of this function are used to init the g_app_start_event. Is spdk_event more like an event happening in control path instead of data path? When should I use an spdk_event?

```
// code snippet from spdk_app_start()
g_init_lcore = spdk_env_get_current_core();                                 
g_delay_subsystem_init = opts->delay_subsystem_init;                        
g_app_start_event = spdk_event_allocate(g_init_lcore, start_fn, arg1, arg2);
                                                                                    
rpc_start_event = spdk_event_allocate(g_init_lcore, spdk_app_start_rpc, 
                                              (void *)opts->rpc_addr, NULL);
```

Thanks in advance and Happy New Year.

**Comment by pelplinski** [comment]
Hi lorneli,
struct spdk_msg is internal structure for thread library. Unless you are messing with threads you should use [Event Framework](https://spdk.io/doc/event.html).

With spdk_event you can allocate an event, which can be handled later on specific core using callback you define ahead of time. 
Then, when event occurs, you can call spdk_event_call() on any core and it will be handled on the core you defined during allocation.

Note, that for passing messages between threads you don't need to allocate specific structures, you can just use spdk_thread_send_msg.

**Comment by lorneli** [comment]
Hi @pelplinski 

Thanks for your detailed answer, making me clearer about these two concepts.
