### ISSUE TITLE
nvmf_tgt segfault after removing disk from the target

### ISSUE THREAD

**Issue by vikasbrcm** [spdk/spdk#562]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Hi,
I would like to draw attention in destroy QP process in nvmf that there is possibility that requests could be processed even after destroy QP in one of the scenario. 
When a disk (hot plug) is removed from the target the related subsystem is paused and in fly requests are queued as below in nvmf/request.c

  /* Check if the subsystem is paused (if there is a subsystem) */
        if (qpair->ctrlr) {
                struct spdk_nvmf_subsystem_poll_group *sgroup = &qpair->group->sgroups[qpair->ctrlr->subsys->id];
                if (sgroup->state != SPDK_NVMF_SUBSYSTEM_ACTIVE) {
                        /* The subsystem is not currently active. Queue this request. */
                        TAILQ_INSERT_TAIL(&sgroup->queued, req, link);
                        return;
                }

        } 

By the time system is resumed the QP would have been destroyed and we may still process the stale QP`s requests with below code in nvmf.c function spdk_nvmf_poll_group_resume_subsystem().

        /* Release all queued requests */
        TAILQ_FOREACH_SAFE(req, &sgroup->queued, link, tmp) {
                TAILQ_REMOVE(&sgroup->queued, req, link);
                spdk_nvmf_request_exec(req);
        }              

I think we should remove the stale QP requests from the sgroup`s queue before we destroy the QP. 
Please let me know if my understanding is correct.

Thanks,
Vikas

## Expected Behavior

Target should be running and carry on IOs on other disks.
## Current Behavior

The target application nvmf_tgt crashes as it tries to process freed QP requests.
## Possible Solution

We may  de-queue all the requests from sgroup queue before destroying the QP.

## Steps to Reproduce

1. nvmf_tgt launched with 4 subsytems on target
2. FIO is running on initiator side
3. Removed a disk (hot plug ) from the target setup.
4.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 18.10

**Comment by Seth5141** [comment]
@vikasbrcm When you perform your hotplug, are you actually pulling a disk, or are you just calling an rpc like nvmf_subsystem_remove_ns?

**Comment by Seth5141** [comment]
@vikasbrcm I tried to replicate the segfault that you are getting by creating an NVMe-oF namespace on top of a malloc disk, running fio, then using nvmf_subsystem_remove_ns to stop it. (I tried with multiple namespaces and a single one). However, I wasn't able to replicate the segfault. Can you give a more specific printout of the segfault you are seeing, and describe the configuration (including underlying block devices)?
Also, @liang2yan opened issue #570. Do you see any similarities between his segfault and your own?

**Comment by Seth5141** [comment]
@vikasbrcm That looks like a reasonable fix to me! Thanks. Would you be interested in submitting this patch on gerrithub to get it merged upstream? I would be happy to walk you through spinning up on gerrithub.

**Comment by vikasbrcm** [comment]
@Seth5141 I`ll submit a patch . Hopefully it should fix #570 

Thanks,
Vikas

**Comment by Seth5141** [comment]
@vikasbrcm Our 19.01 merge window is closing soon (tomorrow), so I opted to upload a version of it to GerritHub to enable @liang2yan to test it against #570. Please take a look, and feel free to re-upload your original version if I did not properly code it. https://review.gerrithub.io/#/c/spdk/spdk/+/441611/
Thanks,
Seth

**Comment by Seth5141** [comment]
Vikas patch mentioned above has been merged, and it has already indicated that his patch fixes the above issue. Thank you @vikasbrcm for the fix! closing this issue.
