### ISSUE TITLE
proposal: add document of json utils for programmers

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#563]
Hi.

I'm writing my custom bdev module. And thanks sincerely for plenty of readable documents in [spdk.io/doc](spdk.io/doc), which helps me to get started quickly.
		
But it looks like that document about how to use json utils(`spdk_json_decode_xx`) is missing. With lack of illustration for these functions, I have to read their implementation and unit tests to see how to use them in a right way.
	
For example, `spdk_json_decode_array` function defines max_size of the input json array. But I don't know the function's behaviour when the size of input json array exceeds the max_size. Will this function return error, or just ignore the rest values in array? Only after reading function's implementation, I'm sure that it will return error if input array is too large.

```
// lib/json/json_util.c
int                                                                                
spdk_json_decode_array(const struct spdk_json_val *values, spdk_json_decode_fn decode_func,
                       void *out, size_t max_size, size_t *out_size, size_t stride)
{                                                                                  
        // ...                                                                     
        *out_size = 0;                                                             
        field = out;                                                               
        out_end = field + max_size * stride;                                       
        for (i = 0; i < values->len;) {                                            
                const struct spdk_json_val *v = &values[i + 1];                    
                // ### reach max_size, return error                                                                     
                if (field == out_end) {                                            
                        return -1;                                                 
                }             
// ...                  
```

Since json-rpc is an important way for modules to accept outside management command, it's common for a component, such as bdev module and transport layer, to implement its own rpc methods, requiring programmers to familiarize themselves with json utils. So I think maybe it's appropriate to add a document decribing the usage of these functions.

Lorne

**Comment by jimharris** [comment]
Hi Lorne,

This is a good proposal.  Marking it with "Bug Scrub" label so that we discuss this in the bug scrub meeting later today.

-Jim

**Comment by peluse** [comment]
Looking for feedback @jimharris and @lorneli - I can add a new .md file for spdki.io docs and put it under the Programmer's Guide or I can just go put some meaningful comments in the code. Anyone have a preference?

**Comment by lorneli** [comment]
Hi Paul,

I think either way is suitable for me.  Adding document in spdk.io accessed by most programmers looks more formal, while meaningful comments in the code provide more convenience, because programmers could jump to these functions and see the comments directly in editor when programming.

By the way, I want to report what I encountered when decoding string in the beginning. At first, I defined a structure containing a char array in fixed size, and thought that `spdk_json_decode_string` will copy the content of string received from rpc to that char array.  Then an error occurred. After reading the code of `spdk_json_decode_string`, I realized that I should define a structure containing the pointer of char and `spdk_json_decode_string`  will alloc buffer for me and redirect the char pointer to that buffer. So I think maybe the upcoming document or comments could tell the users that they need to define a char pointer for decoding string and they are responsible for freeing the char buffer when the buffer doesn't be used anymore.

Lorne

**Comment by pawelwod** [comment]
Instead of Programmer's Guide I vote for documenting the API and writing good example applications. User/Programmer's Guide are often outdated in SPDK and people that makes changes in SPDK are forgetting to update these guides. Examples can be run per patch or nightly so we will know really fast that something is outdated.

**Comment by darsto** [comment]
Bug scrub: I'm going to close this, please create a trello item on https://trello.com/b/P5xBO7UR/things-to-do if this is still something that we should add
