### ISSUE TITLE
Build error in Chandler CI with latest master

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#564]
In the Chandler test pool, the centos7_2 machine has caused the following build error.

  CXX test/cpp_headers/crc32.o
  LINK examples/bdev/fio_plugin/fio_plugin
  CC examples/blob/cli/blobcli.o
  CXX test/cpp_headers/net.o
  CC test/env/env_dpdk_post_init/env_dpdk_post_init.o
  CC test/event/event_perf/event_perf.o
  CC test/app/histogram_perf/histogram_perf.o
  CC examples/bdev/hello_world/hello_bdev.o
In file included from env_dpdk_post_init.c:39:0:
/usr/share/dpdk/x86_64-default-linuxapp-gcc/include/rte_eal.h:87:35: error: â€˜RTE_MAX_LCOREâ€™ undeclared here (not in a function)
  enum rte_lcore_role_t lcore_role[RTE_MAX_LCORE]; /**< State of cores. */
                                   ^
make[3]: *** [env_dpdk_post_init.o] Error 1
make[2]: *** [env_dpdk_post_init] Error 2
  CC test/bdev/bdevperf/bdevperf.o
make[1]: *** [env] Error 2
make[1]: *** Waiting for unfinished jobs....
  CXX test/cpp_headers/copy_engine.o

## Expected Behavior

the centos7_2 machine builds SPDK successfully.

## Current Behavior

The above failure.

## Possible Solution

Nothing.

## Steps to Reproduce
Not reproduced locally yet.

## Context (Environment including OS version, SPDK version, etc.)

machine: centos7_2
arch: x86_64
os: Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
test type: NVMe and Blockdev virtual test machine. Uses a packaged version of DPDK

**Comment by optimistyzy** [comment]
Hi  @shuhei-matsumoto, we also observed this.  And @dong-liuliu will try to address this issue

**Comment by dong-liuliu** [comment]
HI, @shuhei-matsumoto , thanks for pointing the problem out.
I just fixed it in patch https://review.gerrithub.io/c/spdk/spdk/+/439598
Please help review and approve it.

**Comment by shuhei-matsumoto** [comment]
@dong-liuliu, @optimistyzy  Thank you for your quick fix!

**Comment by changpe1** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/439598 has been merged, and closing the issue, thanks Shuhei.
