### ISSUE TITLE
How let nvme device (created by nvmf_tgt) shown in the /dev/disk/by-path?

### ISSUE THREAD

**Issue by clicx** [spdk/spdk#565]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

just create an nvmf target.
nvmf_tgt -c nvmf.conf

## Expected Behavior
in the client, mount it
nvme connect ..
the disk appear in the system, but no found in the /dev/disk/by-path
In this case can't know nvme1n1 is created from which nqn

## Current Behavior
New create disk not is not shown in the /dev/disk/by-path

## Context (Environment including OS version, SPDK version, etc.)
Current version of SPDK

**Comment by changpe1** [comment]
@clicx , what's your OS disk shows in your system? Is it looks like /dev/sdX or /dev/mapper/ ? I believe you need do some configurations in your client host.

**Comment by chwlouluo** [comment]
what type transport you are use？ rdma or tcp ? I used tcp transport to test my spdk nvmf environment,but when i use nvme-cli tool to  discover the nvme ssd devices at spdk nvmf  initiator ,it doesn't work,do you have same problem?

**Comment by clicx** [comment]
I'm using nvme-cli to mount it via RDMA.

**Comment by darsto** [comment]
@benlwalker could it be that remote nvme devices do not appear in /dev/disk/by-path?

**Comment by jimharris** [comment]
I don't see them either.  I do see them for PCIe NVMe SSDs however.

The kernel I've got on this system right now doesn't have the nvmet modules built, to see if this works with the kernel target.  I probably won't have a chance to look at that until late next week.  So I'm assigning it to @vermavis for now.  @vermavis - let me know if you'd have a few minutes next week to try this out.

**Comment by vermavis** [comment]
I see the same problem with kernel NVMe-oF Target. Device is added to the nvme-of initiator, but it doesn't show up under /dev/disk/by-path. So it looks like it is a problem with NVMe-oF namespaces.

**Comment by darsto** [comment]
Bug scrub: pinging @jimharris per his request

**Comment by jimharris** [comment]
After conferring with Keith Busch, there are no udev rules currently to create these symlinks for NVMe-oF namespaces.  This matches with findings from @vermavis that this doesn't work with the Linux kernel target either.

I'm going to close this issue, since it's not an SPDK issue.
