### ISSUE TITLE
How to construct thousands lvol-bdevs and export them via iSCSI quickly?

### ISSUE THREAD

**Issue by jnk0206** [spdk/spdk#569]
Hi everyone:

I am a novice to use SPDK. Recently, I faced a demand in my project: to construct thousands lvol-bdevs based on a SPDK-bdev as soon as possible, then export all of them via iSCSI quickly.

At the beginning, I called the `construct_lvol_bdev` JSON-PRC method to create a lvol-bdev each time. However, it spent a long time when I need to created about 3000 lvol-bdevs (about 6 minutes). So I choose to add a JSON-PRC method by myself, to create thousands lvol-bdevs on one command. Thanks for you guys' great work,  this idea was not difficult to achieve. And I gave this new JSON-PRC method a name called `construct_n_lvol_bdev`.

But then I need to export those lvol-bdevs via iSCSI. Normally, when I call the `construct_lvol_bdev` JSON-PRC method, it will construct a lvol-bdev and then return the uuid/name of this one. But when I call my `construct_n_lvol_bdev` method (the method added by me) to create thousands lvol-bdevs at a time, I don't think it's a good user experience to print thousands lvol-bdevs' names in screen after the method return. 

So, is it a good idea to let `construct_n_lvol_bdev` method records all names of the new lvol-bdevs into a text file? And then, use this text file to export those lvol-bdevs by the `construct_target_node` JSON-PRC method (write a Python script to do this). 
Or, is it a better idea to make a new JSON-RPC method to create and export lvol-bdevs one by one (firstly, create a lvol-bdev A, then export it by iSCSI. Secondly, create another lvol-bdev B, then export this new one by iSCSI ...), or even use multiple threads to this?

Thanks for your advice.

**Comment by pawelwod** [comment]
This application specific case. My advice is: ss you already added the
RPC call to create n LVOLs you can make this call create lvols and
export it via iSCSI at once.

**Comment by jimharris** [comment]
@jnk0206 - can you confirm if you were calling rpc.py once to create each lvol?  If so, I suspect most of the 6 minutes was consumed by starting the Python interpreter 3000 times, as @pelplinski alluded to on the mailing list earlier today.  You can look at rpc.py as a template for creating a custom Python script that creates the lvols and the iSCSI target nodes - and this should run much faster.  Then you could avoid creating custom RPCs altogether.

**Comment by jnk0206** [comment]
@jimharris @pelplinski Thanks very much for your advice! As you said, I had indeed called rpc.py once to create every lvol. 
According to you suggestion, I have created a new custom Python script (using the rpc.py as a template) to creates the thousands lvols, then the new script run faster than my old script (which called rpc.py once to create every lvol). 
After that, I have ran the `perf` tool to check CPU time used, and it's clear that the most of 6 minutes was consumed by starting the Python interpreter thousands times. So I think there is no need to creating custom PRCs by myself. Thanks once again for your help!

**Comment by jnk0206** [comment]
@pawelwod Thanks very much for your useful advice! With the suggestion of @jimharris  and @pelplinski , I think there is no need to create a custom PRC to construct and export lvols, when a Python script will solve my problem well. In addition, writing and maintaining C language code are harder than doing the same thing in Python code. Thanks once again for your help!

**Comment by darsto** [comment]
I'm closing this issue. If you want me to reopen it, please add a comment.

D.
