### ISSUE TITLE
bdev/gpt: read and parse secondary gpt if primary gpt is broken

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#571]
Hi,

Gpt format has a duplicated secondary gpt in the end of the volume, which servers as an alternative if primary gpt is broken.

After passing the check of protective mbr, there is a high probability that this volume is in gpt format. Then if parsing primary gpt fails, such as primary header/partition entries crc unmatched, it's sensible to read the secondary gpt and try to get partition info from the secondary gpt.

If a volume isn't in gpt format, it's hard to pass the protective mbr check in the beginning. So reading secondary gpt is just a remedial measure for the volume that is probably in  gpt format.

I'd like to write a patch for the above-mentioned procedure, but I think it's better to launch a github issue and discuss with you guys first.

Lorne

**Comment by jimharris** [comment]
This seems reasonable to me.  We had talked about adding the secondary check back when @optimistyzy first developed the GPT functionality, but deferred it at the time.  I think it would be good to have the secondary check.

Are you planning to rewrite the primary gpt, if the primary is 'bad' but the secondary is good?

**Comment by optimistyzy** [comment]
@lorneli  @jimharris I am OK with this if the patch is provided.

**Comment by optimistyzy** [comment]
By the way,  If the secondary check is OK, shall we update the primary gpt info in the disk.

**Comment by lorneli** [comment]
Hi Jim, Ziye, 

I prefer not to rewrite the broken primary gpt  if the secondary is good.

Rewriting is a behavior launched by a module inside spdk, not the users themselves,  which may not be the real intentions of users. For example, a user loads a disk, used previously by others in gpt format, to run his own prgram. His program has writen data from LBA 1 to LBA 1024, whick makes primary gpt corrupted, but maintains the integrity of protective mbr and secondary gpt area. At this time rewriting primary gpt overwrites user's data. Though the possibility of this kind of case happening is pretty low, once it happened, users' actual data will be lost, which may become a disaster.

I think maybe it's better to add a warning log, to warn users that the primary gpt is broken after passing the check of secondary gpt. When noticing the log, they could repair gpt format on their own using specialized utility.

**Comment by optimistyzy** [comment]
That's fine. I remembered that the very early version, we also check the
secondary gpt area, I think that you can easily add it back. If the primary
check is failed, you can check the secondary.

lorneli <notifications@github.com> 于2019年1月15日周二 下午1:02写道：

**Comment by lorneli** [comment]
>I remembered that the very early version, we also check the secondary gpt area, I think that you can easily add it back. 

@optimistyzy Thanks for the advice. I'll take a look at the commit history of bdev/gpt later.

**Comment by darsto** [comment]
Added in patch fdb675cad554de028306b6826fdfea67b2648e0f

@lorneli Thank you!
