### ISSUE TITLE
vhost performance degradation

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#572]
## Expected Behavior
Consistent results while running spdk vhost performance tests.

## Current Behavior
Strange performance degradation while running vhost performance benchmark tests.
In general setup is: 4CPU SPDK vhost-scsi, 64VMs, 8/16 NVMe drives.
FIO workload on each VM: 4k randread qd=1.
Detailed description of test setup below.

IOPS results:
- 4k randread qd=1, 8NVMe, 64 vhost-scsi controllers, 64VMs - 2,1M IOPS.
- 4k randread qd=1, 16NVMe, 64 vhost-scsi controllers, 64VMs - 600k IOPS.
- 4k randread qd=1, 16NVMe, 64 kernel SCSI controllers, 64VMs - 1.2-1.3M IOPS.

## Steps to Reproduce
0. "Too long, didn't read" version here. Detailed description from point 1.
```
git clone https://review.gerrithub.io/spdk/spdk
git fetch https://review.gerrithub.io/spdk/spdk refs/changes/29/434229/11 && git cherry-pick FETCH_HEAD (scripts)
git submodule update --init; ./configure --with-fio=/usr/src/fio --enable-debug; make clean; make -j100
cd spdk

# Generate fio workload config
python3 scripts/perf/vhost/run_vhost_test.py 4k 1 randread -m 100 -r 30 -R 15

sudo HUGEMEM=300000 scripts/setup.sh

# Run tests
sudo test/vhost/perf_bench/vhost_perf.sh \
	--fio-bin=/home/sys_sgsw/fio_ubuntu
	--fio-job=/home/sys_sgci/spdk/scripts/perf/vhost/fio_job.cfg \
	--vm-image=/home/sys_sgsw/centos.qcow2 \
	--custom-cpu-cfg=/home/sys_sgci/vhost_benchmark/cpu_masks/tc2/4CORE_64VM_HT_MASKS.txt 
	--use-split --vm-count=64 --max-disks=16 --ctrl-type=spdk_vhost_scsi
	
# Show aggregated iops
cat ../fio_results/fio_job.log  | grep -C 10 "All clients"
```

1. Compile SPDK 
```
git submodule update --init; ./configure --with-fio=/usr/src/fio; make clean; make -j100
```

2. Run vhost application with 4 physical CPU cores.
2 cores per each NUMA node.
(need to also include matching logical cores in the CPU list)
```
app/vhost/vhost -m [0-1,56-57,28-29,84-85] -p 0 -s 1024
```

3. Add NVMe devices to bdev configuration
4. Use construct_split_vbdev call on NVMe bdevs.
Number of resulting split bdevs should be equal to number of VMs in test.
5. Construct vhost-SCSI controllers. Number of created controllers equal to number of VMs in test.
6. Sequentially add each split NVMe bdev to controllers.
7. Run VMs. Each VM should connect to it's own vhost-scsi controller (VM0 - scsi0, VM1 - scsi1, etc.)
(VMs spread out evenly between NUMA Nodes. That way first half of VMs use CPUs & NVme disks on NUMA0, second half on NUMA1;
CPU mask map and example QEMU command to run VM in attachments
[qemu_spdk_cpu_masks.txt](https://github.com/spdk/spdk/files/2755324/qemu_spdk_cpu_masks.txt)
[qemu_cmd.txt](https://github.com/spdk/spdk/files/2755325/qemu_cmd.txt))
8. Once all VMs are up run them in fio server mode and from host OS run job on all VMs:
```
[global]
ioengine=libaio
thread=1
group_reporting=1
direct=1
verify=0
norandommap=1
percentile_list=50:90:99:99.5:99.9:99.99:99.999

[perf_test]
stonewall
description="Run NVMe driver performance test for a given workload"
bs=4k
rw=randread
rwmixread=100
iodepth=1
time_based=1
ramp_time=10
runtime=10
filename=
#Filename is filled automatically by scripts.
```

## Context (Environment including OS version, SPDK version, etc.)
1. Bug reproducible using either SPDK 18.10 (f14c7b3b0) or today's master branch (bf6210b3c test/iscsi: fix support for python 3.6 in calsoft.py)
2. Using Qemu version 2.12 (From spdk/qemu @ review.gerrithub.io)
3. Host system specification:
```
HT Enabled
Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
NUMA node0 CPU(s):   0-27,56-83
NUMA node1 CPU(s):   28-55,84-111
376 GB RAM

Fedora Core 27
4.18.13-100.fc27.x86_64

SELinux disabled
```

4. System has 16 p4600x 2.0TB drives installed which are attached via 2 PCIe Switches (1st on NUMA0, 2nd on NUMA1)
```
NVMe devices
BDF             Numa Node       Driver name             Device name
0000:60:00.0    0               vfio-pci                -
0000:61:00.0    0               vfio-pci                -
0000:62:00.0    0               vfio-pci                -
0000:63:00.0    0               vfio-pci                -
0000:64:00.0    0               vfio-pci                -
0000:65:00.0    0               vfio-pci                -
0000:66:00.0    0               vfio-pci                -
0000:67:00.0    0               vfio-pci                -
0000:b5:00.0    1               vfio-pci                -
0000:b6:00.0    1               vfio-pci                -
0000:b7:00.0    1               vfio-pci                -
0000:b8:00.0    1               vfio-pci                -
0000:b9:00.0    1               vfio-pci                -
0000:ba:00.0    1               vfio-pci                -
0000:bb:00.0    1               vfio-pci                -
0000:bc:00.0    1               vfio-pci                -

```

5. Using fio version 3.3 in server-client mode
6. Guest OS: 
```
Centos 7.6
3.10.0-957.1.3.el7.x86_64 
SCSI multiqueue enabled  scsi_mod.use_blk_mq=1
SELinux disabled

```

## Other notes
- Also tested with older Qemu version (2.9)
- Also tested with older FIO version (2.1.12)
- Tested with spectre meltdown patches on-off (spectre_v2=off nopti in /etc/default/grub)
- Attached perf top recording files for cases:
  - 64 VMs @ 8 disks
  - 64VMs @ 16disks
   - 64VMs @ 16 disks, SPDK @ 1 core
[perf_record.zip](https://github.com/spdk/spdk/files/2755329/perf_record.zip)

**Comment by jimharris** [comment]
Thanks Karol!  Did you have any success reproducing similar results when just using a single core for SPDK vhost?

I also must have missed that all of this was done with QD=1.  I haven't fully thought through the implications of QD=1 yet.

**Comment by karlatec** [comment]
No problem Jim!
Forgot to mention this - still looking for a down scaled reproduction steps (less SPDK cores, maybe less disks and VMs).
For higher QDs results looked OK.

**Comment by jimharris** [comment]
Could you try capturing the queue depth at the NVMe namespace level?  For 64 VMs and 16 SSDs, we would roughly expect each NVMe namespace to be running at about QD=4 (64 VMs * QD=1 / 16 SSDs) but we know there is overhead between when a VM gets its completion and the next IO is issued.

You can use @Seth5141's set_bdev_qd_sampling_period RPC to enable this functionality.  Let's sample every 1ms, meaning you'll pass 1000 as the period value (in microseconds).  To start, just enable this on one or two of the NVMe namespace bdevs (*not* the split bdevs).  Then you can do get_bdevs_iostat on those bdevs and you'll get qd sampling data.

**Comment by karlatec** [comment]
Re-run with sampling enabled as you described. Total IO time was 60 seconds (30 for ramp-time, 30 for run time; QD was measured after ramp-time).
get_bdevs_iostat during FIO traffic reports queue_depth=4 for both NVMe bdevs.
Full stats during FIO traffic:
```
[
  {
    "tick_rate": 2500000000
  },
  {
    "name": "Nvme0n1",
    "bytes_read": 5016299520,
    "num_read_ops": 1222291,
    "bytes_written": 0,
    "num_write_ops": 0,
    "bytes_unmapped": 0,
    "num_unmap_ops": 0,
    "read_latency_ticks": 297056747366,
    "write_latency_ticks": 0,
    "unmap_latency_ticks": 0,
    "queue_depth_polling_period": 1000,
    "queue_depth": 4,
    "io_time": 34419000,
    "weighted_io_time": 119266000
  }
]
[
  {
    "tick_rate": 2500000000
  },
  {
    "name": "Nvme8n1",
    "bytes_read": 5083105280,
    "num_read_ops": 1238603,
    "bytes_written": 0,
    "num_write_ops": 0,
    "bytes_unmapped": 0,
    "num_unmap_ops": 0,
    "read_latency_ticks": 297234950136,
    "write_latency_ticks": 0,
    "unmap_latency_ticks": 0,
    "queue_depth_polling_period": 1000,
    "queue_depth": 4,
    "io_time": 34477000,
    "weighted_io_time": 119746000
  }
]
```
After FIO traffic:
```
[
  {
    "tick_rate": 2500000000
  },
  {
    "name": "Nvme0n1",
    "bytes_read": 8743090176,
    "num_read_ops": 2132152,
    "bytes_written": 0,
    "num_write_ops": 0,
    "bytes_unmapped": 0,
    "num_unmap_ops": 0,
    "read_latency_ticks": 517514457344,
    "write_latency_ticks": 0,
    "unmap_latency_ticks": 0,
    "queue_depth_polling_period": 1000,
    "queue_depth": 0,
    "io_time": 60003000,
    "weighted_io_time": 207774000
  }
]
[
  {
    "tick_rate": 2500000000
  },
  {
    "name": "Nvme8n1",
    "bytes_read": 8876091392,
    "num_read_ops": 2164625,
    "bytes_written": 0,
    "num_write_ops": 0,
    "bytes_unmapped": 0,
    "num_unmap_ops": 0,
    "read_latency_ticks": 516945566990,
    "write_latency_ticks": 0,
    "unmap_latency_ticks": 0,
    "queue_depth_polling_period": 1000,
    "queue_depth": 0,
    "io_time": 59991000,
    "weighted_io_time": 208156000
  }
]
```
Also attaching stats for all 16NVMe disks and split vbdevs as well.
[bdevs_iostat_during_fio_2NVMe.txt](https://github.com/spdk/spdk/files/2759132/bdevs_iostat_during_fio_2NVMe.txt)
[bdevs_iostat_after_fio_2NVMe.txt](https://github.com/spdk/spdk/files/2759130/bdevs_iostat_after_fio_2NVMe.txt)

[bdevs_iostat_during_fio_16NVMe.txt](https://github.com/spdk/spdk/files/2759133/bdevs_iostat_during_fio_16NVMe.txt)
[bdevs_iostat_after_fio_16NVMe.txt](https://github.com/spdk/spdk/files/2759131/bdevs_iostat_after_fio_16NVMe.txt)
[splits_iostat_during_fio_16NVMe.txt](https://github.com/spdk/spdk/files/2759129/splits_iostat_during_fio_16NVMe.txt)
[splits_iostat_after_fio_16NVMe.txt](https://github.com/spdk/spdk/files/2759134/splits_iostat_after_fio_16NVMe.txt)

**Comment by jimharris** [comment]
If I subtract the weighted_io_time between the two sets of data, and divide that by 30 seconds, I get roughly 3.5 - so the queue depth is close to 4.  I thought maybe we'd see it much less than that.

Could you just try running perf locally on these SSDs - random read with QD=1, 2, 4 and 8?

**Comment by karlatec** [comment]
No. I waited more to run get_bdevs_iostat more in the middle of runtime part of FIO workload - it was 40s sleep out of total 60s fio time (although I see "io_time" in "during" results showing ~35s, so there is some delay before FIO actually starts traffic)
Would you like this re-run to measure at 30s mark?

> Could you just try running perf locally on these SSDs - random read with QD=1, 2, 4 and 8?
Sure thing, I'll update tomorrow.

**Comment by karlatec** [comment]
Ok, so we want 2 measurements during FIO runs IO, got it.

**Comment by karlatec** [comment]
Perf nvme log outputs below. They look kind of low... 
[perf_log_16NVMe_4k_randread_1qd.log](https://github.com/spdk/spdk/files/2764340/perf_log_16NVMe_4k_randread_1qd.log)
[perf_log_16NVMe_4k_randread_2qd.log](https://github.com/spdk/spdk/files/2764341/perf_log_16NVMe_4k_randread_2qd.log)
[perf_log_16NVMe_4k_randread_4qd.log](https://github.com/spdk/spdk/files/2764342/perf_log_16NVMe_4k_randread_4qd.log)
[perf_log_16NVMe_4k_randread_8qd.log](https://github.com/spdk/spdk/files/2764343/perf_log_16NVMe_4k_randread_8qd.log)

**Comment by karlatec** [comment]
And bdev iostats. I increased total runtime to 5minutes and took bdev_iostat call every 30s, plus once after FIO was done.
[bdev_iostat_2NVMe.zip](https://github.com/spdk/spdk/files/2764402/bdev_iostat_2NVMe.zip)
[bdev_iostat_16NVMe.zip](https://github.com/spdk/spdk/files/2764403/bdev_iostat_16NVMe.zip)

**Comment by jimharris** [comment]
The perf nvme log outputs look OK.  For 64 VMs, with QD=1 and 16 SSDs, we should see around QD=4 on each SSD.  Your iostat weighted_io_data shows we're consistently around QD=4 at the SSD.  It still seems like the io_time is a little off though - comparing io_time between samples shows a delta of about 32000000 which would mean 32 seconds?  I need to run some other tests to confirm that this isn't just an accounting bug in the queue depth sampling code though.

Any luck on reducing this down to something like 1 vhost physical core (2 logical cores), 16 VMs, and 1, 2 or 4 SSDs?

I know you collected some VMEXIT data previously.  Could you post any of that here?  I'd also like to cross check that data with interrupt counts collected within the VMs.

**Comment by karlatec** [comment]
Hi Jim!
Seems I deleted my previous runs with VM Exists and I try to measure them again, but I am running into issue when trying to run FIO with run time more than a couple of seconds - the perf.data record files are huge! (~15GB when running just for 10sec).
I am doing: perf kvm --host --guest -o perf.data stat record -a.
I know I can filter out the events while creating a report (i.e. perf kvm --host -i perf.data stat report --event vmexit), but can I filter out during recording? That'd really help.

**Comment by jimharris** [comment]
can you try one of the examples from:

https://www.linux-kvm.org/page/Perf_events

for example, just capture kvm:kvm_exit

**Comment by karlatec** [comment]
Hi Jim! I used sudo perf kvm stat -e kvm:* record -a. For some reason I cannot do perf kvm report after that, but at least the numbers are available. FIO was running for 60seconds in both cases.

[perf_kvm_stat_64VM_16NVMe.txt](https://github.com/spdk/spdk/files/2792118/perf_kvm_stat_64VM_16NVMe.txt)
[perf_kvm_stat_64VM_8NVMe.txt](https://github.com/spdk/spdk/files/2792119/perf_kvm_stat_64VM_8NVMe.txt)

**Comment by jimharris** [comment]
What was the IOPs for each of these test cases?

The number of kvm_exits is basically the same - about 20M per second.  That in itself seems really high.  

I'll need to look at this more.

**Comment by karlatec** [comment]
Sorry for long reply. FOr some reason this time the results were
430k with 8 NVMes
325k with 16 Nvmes

This is obviously way lower than anything we previously encountered. I am checking if I have not messed up something with the host configuration as I was using it for NVMeOF perf tests for last couple of days.

**Comment by jimharris** [comment]
@karlatec - is this issue something we should still keep open?

**Comment by karlatec** [comment]
@jimharris Nah, it's OK to close it. I forgot about this one.

**Comment by karlatec** [comment]
Word of comment: actually it seems that it was a configuration error, not a perf degradation.
Also, I wasn't aware than that there disks have so low IOPS results with qd=1
