### ISSUE TITLE
Seg. fault in iSCSI target when exiting sessions periodically during multiple session IO tests

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#574]
An iSCSI initiator creates two sessions to an iSCSI target.
An iSCSI initiator runs IO workload for both sessions.
And then exit one of the sessions periodically.

## Expected Behavior
IO workloads continue to run without any segmentation fault.

## Current Behavior
The following backtrace was collected.

#0  spdk_sock_group_remove_sock (group=0x507d070, sock=0x0) at sock.c:249
#1  0x00000000012bc93a in spdk_iscsi_poll_group_remove_conn_sock (conn=0x7edecd3d2c78) at conn.c:198
#2  0x00000000012bd755 in _spdk_iscsi_conn_destruct (conn=0x7edecd3d2c78) at conn.c:527
#3  0x00000000012bd7da in _spdk_iscsi_conn_check_pending_tasks (arg=0x7edecd3d2c78) at conn.c:553
#4  0x00000000012d15ad in _spdk_reactor_run (arg=0x50bd800) at reactor.c:541
#5  0x00000000012d1b10 in spdk_reactors_start () at reactor.c:692
#6  0x00000000012d0953 in spdk_app_start (opts=0x7ee2d8172660, 

## Possible Solution
https://review.gerrithub.io/#/c/spdk/spdk/+/440466/

Without this fix, issue has occured within a minute, but with this fix, IO workloads continue to run more than a hour.

If no error during a night, this issue will be able to be closed.

## Steps to Reproduce
An iSCSI initiator creates two sessions to an iSCSI target.
An iSCSI initiator runs IO workload for both sessions.
And then exit one of the sessions periodically.

## Context (Environment including OS version, SPDK version, etc.)
Latest master.

**Comment by darsto** [comment]
Bug scrub: The fix is still WIP

**Comment by shuhei-matsumoto** [comment]
@jimharris 

Our team didn't see any error for SPDK master branch with this patch after a night.

We saw temporary out of memory for our SPDK application with this patch because of shortage of session pool but that was not related with this patch and SPDK master branch.

I can say the fix will be OK for SPDK master branch.
