### ISSUE TITLE
IRC log archive in https://ci.spdk.io/irclog/ doesn't updated daily

### ISSUE THREAD

**Issue by wuzhouhui** [spdk/spdk#579]
IRC log archive in https://ci.spdk.io/irclog/ doesn't updated daily

## Expected Behavior

IRC log archive updated daily

## Current Behavior

The latest log archive is 2019-01-09, and the logs after that day is missing.

**Comment by benlwalker** [comment]
This is resolved. Thanks for pointing it out.
