### ISSUE TITLE
Device 'vhost-user-nvme' not found

### ISSUE THREAD

**Issue by riou-chen** [spdk/spdk#591]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

no errors when I run my vm instacnce or excute command "qemu-system-x86_64 -device vhost-user-nvme,help" 

## Current Behavior

when I execute command "qemu-system-x86_64 -device vhost-user-nvme,help", it returns "qemu-system-x86_64: -device vhost-user-nvme,help: Device 'vhost-user-nvme' not found". And when I start my vm instance, it returns "qemu-system-x86_64: -device vhost-user-nvme,id=nvme0,chardev=char2,num_io_queues=4: 'vhost-user-nvme' is not a valid device model name".Besides, my qemu version is 2.12.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
Hi @riou-chen , please use https://review.gerrithub.io/#/c/spdk/qemu/+/409094/ separate patch to test vhost-user-nvme, because the QEMU driver for vhost-user-nvme is not included in the QEMU version.

**Comment by changpe1** [comment]
@riou-chen , the patch is based on QEMU 2.12, and it may has compilation issue if the QEMU version is not suitable.

**Comment by riou-chen** [comment]
thanks, changpe1, the qemu is complied successfully when set the target-list=x86_64-softmmu

**Comment by liang2yan** [comment]
@riou-chen , can we close this issue? You already compiled qemu successfully.

**Comment by changpe1** [comment]
@riou-chen yeah, I only run the compilation with x86_64-softmmu, so closing the issue for now.
