### ISSUE TITLE
spdkcli oneliner commands exits with no error even when RPC command fail

### ISSUE THREAD

**Issue by pawelwod** [spdk/spdk#593]
When RPC command fail in non-interactive mode, spdkcli exits with success.

## Expected Behavior
spdkcli in non-interactive mode should exit with error exit status on first error.

## Current Behavior
Always success.

## Possible Solution
None

## Steps to Reproduce
1. Start SPDK target
2. Issue some valid command that will fail on target side eg create bdev nvme with PCIe address 1:1:1:1.0
3. check exit status

```
$./scripts/spdkcli.py /bdevs/nvme create nvme0 pcie 1:1:1.1
Got JSON-RPC error response
request:
{
  "method": "construct_nvme_bdev",
  "jsonrpc": "2.0",
  "params": {
    "traddr": "1:1:1.1",
    "trtype": "pcie",
    "name": "nvme0"
  },
  "id": 33
}
response:
{
  "message": "Invalid parameters",
  "code": -32602
}

$echo $?
0
```
## Context (Environment including OS version, SPDK version, etc.)
SPDK commit:
c43cb6a70605 nvmf/tcp: fix the issues of qpair resource recycling to avoid memory leak.

**Comment by karlatec** [comment]
Pawel K please confirm behavior so we can mark it as bug.

**Comment by jimharris** [comment]
I can confirm this is a bug.  Marking it as such.
