### ISSUE TITLE
hotremove NVMe device by using /sys/bus/pci/devices/<pciaddr>/driver/unbind not working

### ISSUE THREAD

**Issue by pawelwod** [spdk/spdk#595]
When using VFIO unbinding device by sysfs `unbind` file hang forever  even if hotplug is enabled.
## Expected Behavior
`unbind` should trigger hotremove.

## Current Behavior
`unbind` hangs forever and console is flooded with 

```
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:0b:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:0b:00.0/driver!
```

## Possible Solution
Manually delete nvme bdev will unfreeze `unbind`

## Steps to Reproduce
1. Start SPDK target
2. `bind` nvme device to `vfio-pci` driver e.g. by `spdk/setup.sh` script.
3. Enable nvme hotplug or create manually the nvme_bdev
  ```
  $./scripts/spdkcli.py /bdevs/nvme create nvme0 pcie 0000:0b:00.0
  ['nvme0n1']
  ```

4. Try to unbind device from driver
   ```echo 0000:0b:00.0 > /sys/bus/pci/devices/0000:0b:00.0/driver/unbind```

## Context (Environment including OS version, SPDK version, etc.)
OS: Ubuntu 16.04
Kernel: Linux kraken 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
SPDK: c43cb6a70605 nvmf/tcp: fix the issues of qpair resource recycling to avoid memory leak.

**Comment by jimharris** [comment]
isn't /sys/bus/pci/devices/<pciaddr>/remove the preferred way to emulate a PCI hot remove event?

**Comment by darsto** [comment]
This was never supported in SPDK so far. With VFIO we can only detect physical device hotremove done by pulling an NVMe from the PCI slot.

In the case you're describing, VFIO could send us a hotremove interrupt but handling it in SPDK would be tricky. There is fairly handy DPDK API to install such interrupt handler, but it just doesn't play well with the current SPDK design.

I'm marking this issue as an enhancement. It's still a bug, but it requires some other refactor to be done first.
