### ISSUE TITLE
Unable to get I/O channel for bdev

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#598]
Test optane  device with fio. Failed to get IO channel if numjobs >=32
bdev config nvme.conf:
```
[Nvme]
  TransportId "trtype:PCIe traddr:0000:5e:00.0" Nvme0
```

fio config nvme.ini:
```
[global]
#ioengine=spdk_bdev
ioengine=examples/bdev/fio_plugin/fio_plugin
spdk_conf=nvme.conf
filename=Nvme0n1
thread=1
group_reporting=1
direct=1
verify=0
time_based=1
runtime=20
iodepth=1
offset_increment=5G
rw=randread
bs=4k

[test]
numjobs=32 
```

## Expected Behavior

Successfully open all the channels.
## Current Behavior

nvme_ctrlr.c: 287:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: No free I/O queue IDs
fio_plugin.c: 471:spdk_fio_bdev_open: *ERROR*: Unable to get I/O channel for bdev.
fio: io engine spdk_bdev init failed. Perhaps try reducing io depth?
fio: pid=143792, err=-1/

It works well with numjobs=31 or less
## Possible Solution

no idea
## Steps to Reproduce

1. .fio examples/bdev/fio_plugin/nvme.ini

## Context (Environment including OS version, SPDK version, etc.)

Latest SPDK master commit 7800ef7ff23a53d20cafcc17ff637c366601f565
Non-Volatile memory controller: Intel Corporation Optane DC P4800X Series SSD

Let me know if it is a hardware issue and we cannot do something with that.

**Comment by ak-gh** [comment]
Did you check if your Optane device supports more than 32 queue pairs?

**Comment by alekseymmm** [comment]
@ak-gh Cant see this information in specification documents. How can I find maximum supported number of qpairs for device?

**Comment by ak-gh** [comment]
Nvme admin command GetFeatures/NumberOfQueues reports the number of queues supported by the controller.

Otoh, I'm not quite clear why one would want 32+ queues with Optane which has 4-8 line memory conteoller (so 8 queues up you're saturated anyway).

Hth,
Andrey

**Comment by ak-gh** [comment]
Notice also that 'no free I/O queue ID' error message from nvme layer tells you exactly what's happened: your controller has only 32 queue pair IDs available (and thus doesn't support more than 32 queue pairs).

**Comment by alekseymmm** [comment]
@ak-gh Thank you.
