### ISSUE TITLE
perf run with mix readwrite with "-M" need to check the input value

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#599]
## Issue Summary
perf run with mix readwrite with "-M" need to check the input value

## Expected Behavior
Should report out the issues out

## Current Behavior
Run successfully with performance message printed out

## Possible Solution
WIP

## Steps to Reproduce
1. On target, run the following command to startup the nvmf_tgt app
./app/nvmf_tgt/nvmf_tgt -c /root/nvmf_single_nvme_p4500_tcp.conf
2. On initiator, run the following command to send the IO
./examples/nvme/perf/perf -r 'trtype:TCP adrfam:IPv4 traddr:192.168.3.11 trsvcid:4420' -s 128 -q 128 -o 4096 -w rw -M . -c a -t 10 -D -e 'PRACT=1,PRCHK=GUARD' -m 0
The perf app can finish running without sending any print out on the input parameter check
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c a -m 128 --no-pci --base-virtaddr=0x200000000000 --file-prefix=spdk_pid44219 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.3.11:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.3.11:4420: nqn.2016-06.io.spdk:cnode1
controller IO queue size 128 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
WARNING: Some requested NVMe devices were skipped
Associating SPDK bdev Controller (SPDK00000000000001  ) with lcore 3
Associating SPDK bdev Controller (SPDK00000000000001  ) with lcore 1
Initialization complete. Launching workers.
Starting thread on core 3
Starting thread on core 1
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
SPDK bdev Controller (SPDK00000000000001  ) from core 3:   61230.50     239.18    2090.50     453.97    3183.72
SPDK bdev Controller (SPDK00000000000001  ) from core 1:   65178.90     254.61    1963.78     602.96    2709.34
========================================================
Total                                                  :  126409.40     493.79    2025.16     453.97    3183.72

**Comment by wanqunintel** [comment]
when using the command as follows, it will also finished testing without checking the input value
./examples/nvme/perf/perf -r 'trtype:TCP adrfam:IPv4 traddr:192.168.3.11 trsvcid:4420' -s 128 -q 128 -o 4096 -w rw -M abcdef -c a -t 10 -D -e 'PRACT=1,PRCHK=GUARD' -m 0

**Comment by shuhei-matsumoto** [comment]
Hi @wanqunintel

Thanks for your testing.

To detect non integer character as error, I knew that Chunyang's recent addition was not enough.
We have to add check procedure like https://stackoverflow.com/questions/26080829/detecting-strtol-failure/26083517 .

I'm not certain if I can catch 19.01 but I'll do this.

Thanks,
Shuhei

**Comment by jessehui** [comment]
Hi @shuhei-matsumoto , No problem.

**Comment by shuhei-matsumoto** [comment]
Hi @wanqunintel @jessehui and all,

I submitted relatively long patch series to improve error check including this.
The patch series starts from https://review.gerrithub.io/#/c/spdk/spdk/+/441626/.

I'm happy for your any help about review and verification.

This is targeted to not 19.01 but 19.04.

Thanks,
Shuhei

**Comment by wanqunintel** [comment]
@shuhei-matsumoto thank you so much for your response. i have tested with latest master code (commit d1f943239ee8bb0d459da01fe96562bc5f4f0948) and it still finished the testing with perf result, "-M ." there is no digit at all, and does your patch plan to check "-M " parameter? Thank you.

**Comment by shuhei-matsumoto** [comment]
@wanqunintel 

Thanks much for testing. Will you cherry-pick https://review.gerrithub.io/#/c/spdk/spdk/+/441630/ and try again.

-Shuhei

**Comment by jimharris** [comment]
This patch was merged.  I've confirmed that perf properly detects malformed options like "-M ."
