### ISSUE TITLE
SPDK iscsi_tgt prints errors when setting iodepth of fio more than 200

### ISSUE THREAD

**Issue by jnguo** [spdk/spdk#600]
## Expected Behavior

I have used fio-3.3 with SPDK bdev fio plugin to test the I/O performance of a iSCSI bdev, which based on a NULL bdev exported by rpc method `construct_target_node`.

> fio -> SPDK iSCSI bdev \<---iSCSI---\> NULL bdev

When the value of iodepth in the fio configuration file more than 200, fio should working well on the SPDK iSCSI target.

## Current Behavior

When I setting `iodepth=256`(or 512) in the fio configuration file and running fio, the following error messages will be printed:
```
iscsi.c:4427:spdk_iscsi_execute: *ERROR*: StatSN(6/132) QCmdSN(125) error
conn.c:1352:spdk_iscsi_conn_handle_incoming_pdus: *ERROR*: spdk_iscsi_execute() fatal error on iqn.2016-06.io.spdk:disk1,t,0x0001(iqn.1994-05.com.redhat:f9c4a5ae4f6,i,0x80ff54c00000)
```

However there were no problem when I setting `iodepth=128`.

## Steps to Reproduce

1. Runing `./scripts/setup.sh`, then runing `./app/iscsi_tgt/iscsi_tgt -m 0x10`.
2. Creating a NULL bdev, after that exporting this NULL bdev via iSCSI by the rpc method `python ./scripts/rpc.py construct_target_node disk2 "Data Disk2" "Null0:0" 1:1 128 -d`.
3. Using fio with SPDK bdev fio plugin (`LD_PRELOAD=~/spdk/examples/bdev/fio_plugin/fio_plugin fio ~/spdk/examples/bdev/fio_plugin/myfio.ini`) to measure the performance of the iSCSI device.
4. The fio configure file and SPDK configure file are as following:
```
# myfio.ini
[global]
ioengine=spdk_bdev
spdk_conf=./examples/bdev/fio_plugin/mybdev.ini
thread=1
group_reporting=1
direct=1
time_based=1
iodepth=128
rw=read
bs=4k

[test]
numjobs=1
filename=mynull
runtime=30
```

```
# mybdev.ini
[iSCSI_Initiator]
  initiator_name iqn.1994-05.com.redhat:f9c4a5ae4f6
  URL iscsi://127.0.0.1:3260/iqn.2016-06.io.spdk:disk2/0 mynull
```
## Context (Environment including OS version, SPDK version, etc.)

CentOS Linux 7
SPDK v19.01-pre
`git describe --tags`: v18.10-444-gc9c4a33

**Comment by jnguo** [comment]
@optimistyzy Thanks for your comment! After I applied the patch https://review.gerrithub.io/c/spdk/spdk/+/430879/ from @xuhuagen , `iodepth=256` with `numjobs=2` in fio config file will working well, but `iodepth=512` with `numjobs=1` will printing errors also.

**Comment by optimistyzy** [comment]
@jnguo  The patch may not be the final solution. I just mark the three ones as the same issue.

**Comment by jnguo** [comment]
@optimistyzy Thanks for your help! I will try to find the solution simultaneously.

**Comment by optimistyzy** [comment]
@jnguo Thanks. We will also monitor this issue.

**Comment by optimistyzy** [comment]
@jgnuo  for open iscsi , you can check the queue depth setting in /etc/iscsi/iscsid.conf. I am afraid that if you change the value to a bigger value , whether it will still trigger the issue with kernel initiatior

**Comment by jnguo** [comment]
@optimistyzy Even if I changed the value of `node.session.queue_depth` in `/etc/iscsi/iscsid.conf` from 32 (the default value) to 512 or 1024 (the max value), then restart iscsi server (by `systemctl restart iscsid` or even reboot the computer), in my enviroment, exporting a NVMe SSD by SPDK and importing it locally by open-iscsi work well with fio (no matter how big the fio iodepth has been set).

**Comment by optimistyzy** [comment]
@jnguo  Got it. It means that you test using both the kernel iSCSI target via SPDK initiator and open iscsi.

**Comment by jnguo** [comment]
@optimistyzy Yes, my experiment includes:
1. Exporting a iSCSI target by LIO (`targetcli`), and importing it via SPDK initiator. `fio` will be hanging for a long time when the value of `fio` (or `bdevperf`) iodepth is too big (like 256, 512). I have to kill the hanged `fio` process because it spends nearly 100% CPU times of a core.
2. Exporting a iSCSI target by LIO, and importing it via open iscsi. `fio` works well with this combination.
3. Exporting a iSCSI target via a SPDK app `iscsi_tgt`, and importing it by SPDK initiator. Same as case 1, and `iscsi_tgt` will print error messages additionally.
4. Exporting a iSCSI target via SPDK, and importing it by open iscsi. Same as case 2, `fio` will run well.

According to the above testes, I guess there has some issues in SPDK initiator, and I will try to find them out.

**Comment by jimharris** [comment]
Can you check which version of libiscsi you have on this system?

I'm trying this same test on my system, where I've built libiscsi from source (git commit id 8d5d0b241d March 7 2018).  I'm not able to reproduce this problem.  I wonder if this is a libiscsi bug that's been fixed.

-Jim

**Comment by jimharris** [comment]
I figured out which version of libiscsi is on Centos 7 (1.9) - then I built that version on my system and can now reproduce the problem.

I'm continuing to investigate to see if there's something we can do to work around this problem.

**Comment by jimharris** [comment]
I've narrowed this down to libiscsi commit 37f908bb8a.  This commit went in libiscsi version 1.14.  I back ported this commit to 1.9 locally on my system, and the same failure went away.

This seems to indicate that the LIO target is not doing this same StatSN check - or at least it's not failing the connection when it happens.

Here are the options as I see them:

1) Try to throttle the queue depth in the SPDK iSCSI initiator, so that we don't hit this bug.  A quick look through iscsi/iscsi.h did not show a way to get the connection's queue depth, so this would need more investigation.
2) Remove the StatSN check entirely.
3) Keep the StatSN check, but just make it a debug log.
4) Keep the StatSN check, put a rate limit bit on the connection, do an error log first time we hit this condition (and then set the rate limit bit so it doesn't get printed again).
5) Don't allow building SPDK iSCSI initiator with libiscsi < version 1.13.

I'm leaning towards option #4.

**Comment by jimharris** [comment]
Sorry - option #5 should have read libiscsi < version 1.14.

**Comment by jimharris** [comment]
After seeing that the Linux kernel doesn't check ExpStatSN at all, I think option #2 above is the best option.  I've submitted https://review.gerrithub.io/c/spdk/spdk/+/441981 to do just that.

**Comment by jnguo** [comment]
@jimharris Thanks for your comments! As you said, it's `libiscsi-1.9.0-7.el7.x86_64` in my CentOS 7 system. But when I followed your option 2, the fio (or bdevperf) still hanged when the iodepth is 256 or 512. 
There had some issue to install libiscsi whose version is larger than 1.14, so I didn't have chance to test your option 5 now. But I will try it in my system as soon as possible.

**Comment by jimharris** [comment]
Hi @jnguo,

For your test with option #2 - did you use the patch I linked above (https://review.gerrithub.io/c/spdk/spdk/+/441981) or did you create your own patch?  I did not see any hangs when testing with QD=512 with the 441981 patch.

Thanks,

-Jim

**Comment by optimistyzy** [comment]
@jimharris   Thanks for your time also debugging this.  But should we still keep the code in the iSCSI target.  Currently @jnguo would use SPDK iSCSI initiator to test any iSCSI target. Removing the statsn checking code may not help. Maybe, we need to put some comments in the READMe or other parts to state that there are some issues related with libiscsi.

**Comment by jnguo** [comment]
@jimharris Thanks for your comment. Yes, **I have applied your patch**. Then I have used LIO to exporting a NVMe SSD (which producted a iscsi target named `iqn.2018-11.local.jnk.server:disk1`), and imported it by SPDK initiator locally. The testing configure files for SPDK bdev fio plugin are as follows:

```
# mybdev.ini has been used to configure SPDK.
[Passthru]
  PT mynvme PT0

[iSCSI_Initiator]
  initiator_name iqn.1994-05.com.redhat:f9c4a5ae4f6
  URL iscsi://127.0.0.1:3260/iqn.2018-11.local.jnk.server:disk1/0 mynvme
```

```
# myfio.ini has been used to configure fio.
[global]
ioengine=spdk_bdev
spdk_conf=./examples/bdev/fio_plugin/mybdev.ini
thread=1
group_reporting=1
direct=1
time_based=1
iodepth=512 # <<< more than 200.
rw=read
bs=4k

[test]
numjobs=1
filename=PT0
runtime=30 # <<< asking fio to run 30 seconds.
```

The result of running fio is as follows:
```
[root@host spdk]# LD_PRELOAD=~/spdk/examples/bdev/fio_plugin/fio_plugin ~/git.hub/fio/fio ~/spdk/examples/bdev/fio_plugin/myfio.ini
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk_bdev, iodepth=512
fio-3.3
Starting 1 thread
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid15708 ]
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
vbdev_passthru.c: 469:vbdev_passthru_init: *NOTICE*: conf parse matched: mynvme
vbdev_passthru.c: 565:vbdev_passthru_register: *NOTICE*: Match on mynvme
vbdev_passthru.c: 602:vbdev_passthru_register: *NOTICE*: io_device created at: 0x0x7f6adc004b30
vbdev_passthru.c: 614:vbdev_passthru_register: *NOTICE*: bdev opened
vbdev_passthru.c: 626:vbdev_passthru_register: *NOTICE*: bdev claimed
vbdev_passthru.c: 638:vbdev_passthru_register: *NOTICE*: pt_bdev registered
vbdev_passthru.c: 639:vbdev_passthru_register: *NOTICE*: created pt_bdev for: PT0
Jobs: 1 (f=1): [R(1)][0.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 1371d:13h:46m:55s]
```

The fio will hang for a very long time (eta 1371d:13h:46m:55s) and spend about 100% CPU time of a core. However it will work well when I just change the `iodepth` from 512 to 128.
The version of libiscsi in my system is `libiscsi-1.9.0-7.el7.x86_64`.

**Comment by jnguo** [comment]
Hi @jimharris , I saw you closing this issue. Did it mean that the `eta 1371d:13h:46m:55s` of fio is not a `hanging`? If they are not equal, please forgive me for my poor expression.

**Comment by changpe1** [comment]
@jnguo the issue was closed automatically as the patch was merged. Jim's patch will fix SPDK iSCSI target with your initiator case, and I'm seeing that you are using LIO, so for your high queue depth test case, I think you can try with SPDK iSCSI target.
