### ISSUE TITLE
missing calsoft file in "fedora-02" server during NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#601]
Calsoft test is skipped in "fedora-02" server , because there is no "/usr/local/calsoft".

Logs as below:
START TEST SUITE ./test/iscsi_tgt/calsoft/calsoft.sh
......
 07:07:24	# '[' '!' -d /usr/local/calsoft ']'
 07:07:24	# echo 'skipping calsoft tests'
skipping calsoft tests
 07:07:24	# exit 0

## Expected Behavior
Calsoft test run normally as same as in "fedora-08" server.

## Current Behavior
Calsoft test is skipped in "fedora-02" server.

## Possible Solution
Put a calsoft file in /usr/local/ of "fedora-02" server.

## Steps to Reproduce
1. view build log in  "fedora-02" server. https://ci.spdk.io/spdk/builds/review/dc0c79aa0498e343468ed7d47e4237512261f68d.1547985685/fedora-02/build.log (search "skipping calsoft tests")

## Context (Environment including OS version, SPDK version, etc.)
commit 1c54ba1c174bc0b334a32e864dc69a9cc07377fe

**Comment by jimharris** [comment]
Closing this issue.  We are planning to shut down the Chandler test pool next week.
