### ISSUE TITLE
NVMe hotplug poller immediately picks up manually deleted controllers

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#602]
Please use the issue tracker only for reporting suspected issues.

When nvme is deleted and then added again spdk displays error.

## Expected Behavior
Can add nvme

## Current Behavior
bdev_nvme.c:1208:spdk_bdev_nvme_create: *ERROR*: A controller with the provided trid (traddr: 0000:06:00.0) already exists.
Exception:
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0",
  "method": "construct_nvme_bdev",
  "id": 1,
  "params": {
    "name": "HotInNvme0",
    "trtype": "PCIe",
    "traddr": "0000:06:00.0"
  }
}
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}

## Possible Solution
None

## Steps to Reproduce
1. Run spdk
2. Add nvme bdev Nvme0
3. Delete nvme bdev with scripts/rpc.py delete_nvme_controller Nvme0
4. Add bdev again: construct_nvme_bdev -b HotInNvme0 -t PCIe -a 0000:06:00.0
5. Spdk displays error: bdev_nvme.c:1208:spdk_bdev_nvme_create: *ERROR*: A controller with the provided trid (traddr: 0000:06:00.0) already exists.

## Context (Environment including OS version, SPDK version, etc.)
VM with Ubuntu 16.04. Two nvme

**Comment by changpe1** [comment]
@pawelkax , thanks, I'll provide a patch to fix the issue.

**Comment by changpe1** [comment]
@pawelkax , I can reproduce the issue, when HotplugEnable is enabled by NVMe driver, after RPC call delete_nvme_controller Nvme0, the deleted controller will be added automatically with the name "HotInNvme0", but the behavior is expected as our design, I marked the issue with "Bug Scrub" label, we will discuss it in the community meeting.

**Comment by changpe1** [comment]
Bug Scrub: if this is triggered by user, we may add this controller into the blacklist to prevent being attached again.

**Comment by pawelkax** [comment]
@changpe1
Hi,
Do you have any update with this issue?

**Comment by changpe1** [comment]
I post a patch to fix this issue. https://review.gerrithub.io/#/c/spdk/spdk/+/444323/

**Comment by pawelkax** [comment]
@changpe1 @jimharris @darsto I tested it with patch https://review.gerrithub.io/#/c/440950/ and hotremove for scsi and blk works.

**Comment by jimharris** [comment]
Patch merged.
