### ISSUE TITLE
NVMe drive LBA format change not recognized by host

### ISSUE THREAD

**Issue by nagendra-v** [spdk/spdk#607]
If NVMe drive LBA format is changed after loading nvmf_tgt, host still sees old LBA size and format. Host can't Read/Write until nvme_tgt is reloaded.

##  Steps to Reproduce
1. Run "setup.sh" script, start nvmt_tgt
2. Establish connection from host: nvme connect
3. On target change NVMe drive format LBA size from 512 to 4K (OR 4K to 512) by command "nvme format <xxx>"
4. Can't do read/write to NVMe fabric drive

## Context (Environment including OS version, SPDK version, etc.)
SPDK v18.10.1 / DPDK 18.08.0 on CentOS 7.5.1804

## Expected Behavior
NVMe drives new format should be recognized by host after doing disconnect/connect. It should not require "nvmf_tgt" reload.

**Comment by jimharris** [comment]
Bug scrub:

bdev layer doesn't know about the new namespace format, so disconnect/reconnect has no effect since bdev layer hasn't been updated

we've talked about modifying the bdev layer to add more notifiers besides just "remove" - this could be a case where we add something so the bdev module (i.e. nvme) can report up to the bdev layer that the namespace format has been changed - this means nvme module would need to intercept commands and detect "format namespace"?

question: does "nvme format" also do a reset?

**Comment by nagendra-v** [comment]
>question: does "nvme format" also do a reset?
No, format command doesn't reset the drive.

nvme list shows new LBA format after format command(as shown below). If bdev doesn't have updated NS format, list command can still show correct NS format?

#nvme list
Node             SN                   Model                                    Namespace Usage                      **Format**           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
0000:07:00.0     BTLN836301291P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB      **4 KiB** +  0 B   VDV10140

After NS format, reset command gives below errors.

nvme_ctrlr.c: 789:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_pcie.c:1109:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1282) is not found. Dropping the request.
nvme_pcie.c:1109:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1282) is not found. Dropping the request.
nvme_pcie.c:1109:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1282) is not found. Dropping the request.
nvme_pcie.c:1109:nvme_pcie_qpair_insert_pending_admin_request: *ERROR*: The owning process (pid 1282) is not found. Dropping the request.

Is there a way to remove one drive from SPDK and add it back to overcome this problem?. This solution may not be right, if drive supports multiple NS's and different format for each NS.

**Comment by nagendra-v** [comment]
Tried removing NMVe drive from SPDK by running command "rpc.py delete_nvme_controller Nvme1". 

Command doesn't return any error or any output, "rpc.py get_nvme_controllers" still showing controller after delete command.

  {
    "trid": {
      "trtype": "PCIe",
      "traddr": "0000:07:00.0"
    },
    "name": "Nvme1"
  },

**Comment by shuhei-matsumoto** [comment]
This issue may be related with https://review.gerrithub.io/#/c/spdk/spdk/+/445056/ .

**Comment by changpe1** [comment]
@nagendra-v , for now SPDK can support the feature you mentioned here, and you only need to use the RPC delete/add namespace when changing the format of one bdev. The initiator will recognize the new driver format.

**Comment by changpe1** [comment]
[Bug Scrub] Does this method work for you ? Just use nvmf_subsystem_add_ns and nvmf_subsystem_remove_ns RPC when doing block format ?

**Comment by nagendra-v** [comment]
@shuhei-matsumoto Thanks, issue you pointed is related BlockSize+Metadata. This is another issue I ran into, this change will help to address this issue.

**Comment by nagendra-v** [comment]
@changpe1 
Tried RPC calls nvmf_subsystem_remove_ns  and nvmf_subsystem_add_ns, this doesn't work.
Also tried delete_bdev and construct_nvme_bdev after nvmf_subsystem_remove_ns , still didn't work.

**Comment by changpe1** [comment]
@nagendra-v Thanks.  I tested it in my system, and it only works for Namespace 1, there is a bug in the Nvmf target, I will fix it that later.

Here is my steps:
1. Start Nvmf target with 2 Namespaces, and 2 malloc block devices used.
2. Initiator connect to Nvmf target, and see the two block devices.
3. $rpc_py nvmf_subsystem_remove_ns nqn.2016-06.io.spdk:cnode1 1.
4. Check the initiator, Namespace 1 was removed.
5. Added a NVMe block device, which was formatted with 512 + 8,
$rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Nvme0n1
6. Check the initiator again, and use nvme list-ns command to check:
lbaf  0 : ms:8   lbads:9  rp:0 (in use)
You can see that the metadata size is already changed to 8.

**Comment by changpe1** [comment]
@nagendra-v You don't need to disconnect and connect Nvmf target if your initiator can support AER.

**Comment by changpe1** [comment]
@nagendra-v Can you try it with your environment, everything works well on my side, but be aware Linux will not support 512+8 block size by default, you need to configure your Host as well.

**Comment by nagendra-v** [comment]
@changpe1 I am not trying 512+8, I am seeing the issue going from 512 to 4K. I am trying this on NVMe drive with "uio_pci_generic" driver.

**Comment by changpe1** [comment]
@nagendra-v Changing from 512B to 4KiB can definitely work if you can use the RPC call to delete Namespace and add it back after changed the block size.

**Comment by nagendra-v** [comment]
This is what I tried earlier, as mentioned in my earlier comments "Tried RPC calls nvmf_subsystem_remove_ns and nvmf_subsystem_add_ns, this doesn't work.
Also tried delete_bdev and construct_nvme_bdev after nvmf_subsystem_remove_ns , still didn't work."
Is there any other RPC call to delete Namespace ?

**Comment by changpe1** [comment]
@nagendra-v Can you post the initiator kernel log here ? Initiator should print scan similar messages. 
 nvmf_subsystem_add_ns and nvmf_subsystem_remove_ns are the right RPC, and this is already covered by CI .

**Comment by changpe1** [comment]
[Bug Scrub] For now this is the right solution to change the LBA size in initiator by using RPC, I'm going to close this issue.

**Comment by nagendra-v** [comment]
@changpe1 
I have tried with SPDK v19.01 / DPDK 18.11.0, still host doesn't see namespace block size change. Still showing old value. Below are steps I tried.

1. Format namespace to 4K
2. Start nvmf_tgt
3. Through RPC create subsystem, add host and namesapce(nvmf_subsystem_creat, nvmf_subsystem_add_ns other necessary calls)
4. From host discover and connect and verify namespace "Format" as 4K
5. Disconnect nvme fabric drive from host
6. Through RPC delete subsystem (delete_nvmf_subsystem)
7. Format namespace to 512B
8. Through RPC create subsystem, add host and namesapce(nvmf_subsystem_creat, nvmf_subsystem_add_ns other necessary calls)
9. rom host discover and connect and verify namespace, still seeing namespace "Format" as 4K.

Not sure where the problem is, but restarting "nvmf_tgt" and then doing above step 3 resolves the issue. Any idea what I am doing differently compared to your test?

**Comment by Maciej-Szwed** [comment]
@nagendra-v please also remove NVMe controller (with delete_nvme_controller RPC call) after point 7. and then create it again.

**Comment by nagendra-v** [comment]
@Maciej-Szwed what's rcp function call to "create nvme controller" ?
