### ISSUE TITLE
keep alive: running perf on initiator: *ERROR*: Error polling CQ! (104): Connection reset by peer

### ISSUE THREAD

**Issue by wanqunintel** [spdk/spdk#609]
## Issue Summary
When running nvmf_tgt on the target with TCP transport, then run the perf command on the initiator, the initiator will print out the following error message continuously till ctrl+c to exit the perf on the initiator, when ctrl+c nvmf_tgt, the initiator will keep printing the error message as follows continuously
nvme_tcp.c:1588:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (104): Connection reset by peer
......
## Expected Behavior
Pass test without any errors

## Current Behavior
On initiator, it will print out the following message continuously
nvme_tcp.c:1588:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (104): Connection reset by peer

## Possible Solution
WIP
## Steps to Reproduce
1. On target, run the following command to start up nvmf_tgt
./app/nvmf_tgt/nvmf_tgt -c /root/nvmf_single_nvme_tcp.conf
2. On initiator, run the following command with perf
./examples/nvme/perf/perf -r 'trtype:TCP adrfam:IPv4 traddr:192.168.3.11 trsvcid:4420' -s 1024 -q 10 -o 16384 -w randrw -M 50 -t 60
3. On initiator, check the printing message, and it will print following message continuously
nvme_tcp.c:1588:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (104): Connection reset by peer
4. On target, there is no errors printing from the nvmf_tgt app, when using dmesg -c, it will print following errors
[1473262.251114] infiniband mlx4_0: ib_register_mad_agent: QP 0 not supported

## Context (Environment including OS version, SPDK version, etc.)
commit: b8769cdb08813d2b41f7c6dfd92d863ac99ed24d
OS: 4.16.11-100.fc26.x86_64

**Comment by glodfish-zg** [comment]
@wanqunintel. I will provide a patch to fix this issue.

**Comment by wanqunintel** [comment]
@changpe1 , i have updated to test with this patch, observation as follows:
1. First time run with this patch, on target, running command ./app/nvmf_tgt/nvmf_tgt -c /root/nvmf_single_nvme_tcp.conf
on initiator, run command, ./examples/nvme/perf/perf -r 'trtype:TCP adrfam:IPv4 traddr:192.168.3.11 trsvcid:4420' -s 1024 -q 10 -o 16384 -w randrw -M 50 -t 60, there are errors printed on the initiator as follows till perf finish testing after 60 seconds:
nvme_tcp.c:1588:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (104): Connection reset by peer
on target, the nvmf_tgt is killed, message as follows:
EAL: PCI device 0000:83:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
tcp.c: 580:spdk_nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
tcp.c: 767:spdk_nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 192.168.3.11 port 4420 ***
Killed
2.  Run nvmf_tgt and perf second time, this issue disappeared
3.  Run nvmf_tgt on target, it shows following errors, i tried to restart the NIC by ifconfig down/up, it still print following errors.
EAL:   probe driver: 8086:953 spdk_nvme
tcp.c: 580:spdk_nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
posix.c: 238:spdk_posix_sock_create: *ERROR*: bind() failed at port 4420, errno = 98
tcp.c: 743:spdk_nvmf_tcp_listen: *ERROR*: spdk_sock_listen(192.168.3.11, 4420) failed: Address already in use (98)
nvmf.c: 506:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address '192.168.3.11'
conf.c: 203:spdk_nvmf_tgt_listen_done: *ERROR*: Failed to listen on transport address
rpc.c: 135:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.
rpc.c:  67:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at /var/tmp/spdk.sock

**Comment by wanqunintel** [comment]
retested with latest patch, observations as follows
1. first time run on target, ./app/nvmf_tgt/nvmf_tgt -c /root/nvmf_single_nvme_tcp.conf
run command as follows on initiator, it finished testing within 30 seconds even though -t 60, no errors print out, IOPS valud is quite low ~258
./examples/nvme/perf/perf -r 'trtype:TCP adrfam:IPv4 traddr:192.168.3.11 trsvcid:4420' -s 1024 -q 10 -o 16384 -w randrw -M 50 -t 60

**Comment by wanqunintel** [comment]
Another update, when running with rdma transport, it will not exit perf even running with 60+ seconds, when runing within 10s, like 9s, 8s, 5s, it all works
./examples/nvme/perf/perf -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.3.1 trsvcid:4420' -s 1024 -q 10 -o 16384 -w randrw -M 50 -t 10

**Comment by glodfish-zg** [comment]
same as @wanqunintel  has seen there, if time is 60s, transport is TCP.

**Comment by glodfish-zg** [comment]
update. the performance is ok.

**Comment by changpe1** [comment]
@wanqunintel , thanks for the update, closing the issue as patch was merged.
