### ISSUE TITLE
nvmf_tgt reports not enough buffers when running on 32 cores

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#614]
On 32 cores, nvmf_tgt reports:

[root@waikikibeach34 spdk20180605_debug_3]# ./app/nvmf_tgt/nvmf_tgt -c nvmf.conf -m 0xffffffff -s 18432
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0xffffffff -m 18432 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid3495 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 32
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 2
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 3
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 4
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 5
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 6
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 7
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 8
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 9
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 11
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 13
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 21
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 10
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 22
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 14
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 17
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 16
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 12
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 15
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 18
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 20
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 19
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 23
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 24
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 25
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 26
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 27
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 28
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 29
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 30
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 31
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
rdma.c:1691:spdk_nvmf_rdma_create: *ERROR*: There are not enough buffers to satisfyper-poll group caches for each thread. ( 512)supplied. (1024) required
rdma.c:1692:spdk_nvmf_rdma_create: *ERROR*: Please specify a larger number of shared buffers
transport.c: 109:spdk_nvmf_transport_create: *ERROR*: Unable to create new transport of type RDMA
subsystem.c: 120:spdk_subsystem_init_next: *ERROR*: Init subsystem nvmf failed
app.c: 719:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
thread.c: 179:spdk_thread_lib_fini: *ERROR*: io_device nvmf_tgt not unregistered
Then exit.

On 16 cores, nvmf_tgt reports:
transport.c: 215:spdk_nvmf_transport_poll_group_create: *NOTICE*: Unable to reserve the full number of buffers for the pg buffer cache.

nvmf.conf
........
[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.11.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace Nvme0n1 1
  Namespace Nvme1n1 2

## Expected Behavior
nvmf_tgt works well when running on 32 cores

## Current Behavior
nvmf_tgt reports not enough buffers

## Possible Solution
set appropriate buffers to satisfyper-poll group caches in lib/nvmf/rdma.c

## Steps to Reproduce
1. cd SPDK dir
2. HUGEMEM=24576 ./scripts/setup.sh
3. ./app/nvmf_tgt/nvmf_tgt -c nvmf.conf -m 0xffffffff -s 18432

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit ac5b26e4cb8fda257661c8707d98369271ec3170

**Comment by optimistyzy** [comment]
@rdma.c:1691:spdk_nvmf_rdma_create: ERROR: There are not enough buffers to satisfyper-poll group caches for each thread. ( 512)supplied. (1024) required

See this, I think that you need to increase the  opts->num_shared_buffers  via either RPC call or the configuration filethrough setting  NumSharedBuffers in the RDMA transport since the Default value is 512

**Comment by optimistyzy** [comment]
I currently marked it is invalid, since it is the expected behavior.

**Comment by wanghailiangx** [comment]
Updated nvmf.conf
[Transport]
  Type RDMA
  NumSharedBuffers 1024

The problem “not enough buffers” seems to have been solved. But there are new errors:
transport.c: 215:spdk_nvmf_transport_poll_group_create: *NOTICE*: Unable to reserve the full number of buffers for the pg buffer cache.
transport.c: 215:spdk_nvmf_transport_poll_group_create: *NOTICE*: Unable to reserve the full number of buffers for the pg buffer cache.
nvme_ctrlr.c: 287:spdk_nvme_ctrlr_alloc_io_qpair: *ERROR*: No free I/O queue IDs
nvmf.c: 929:poll_group_update_subsystem: *ERROR*: Could not allocate I/O channel.
nvmf.c: 632:spdk_nvmf_poll_group_create: *ERROR*: Unable to get I/O channel for target

**Comment by wanghailiangx** [comment]
Now closed the issue.  And "No free I/O queue IDs" is not an issue, this is limited by NVMe didks.
