### ISSUE TITLE
nvme_cli.sh reports EAL parameters in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#617]
nvme_cli.sh reports EAL parameters as below:

START TEST SUITE test/nvmf/nvme_cli/nvme_cli.sh
..........
 09:10:29	# ./nvme discover -t rdma -a 10.0.2.15 -s 4420
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x100 -m 512 --legacy-mem --file-prefix=spdk0 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: lcore 8 unavailable
EAL: invalid coremask
EAL: FATAL: Invalid 'command line' arguments.
EAL: Invalid 'command line' arguments.
Failed to initialize DPDK
EAL: memzone_reserve_aligned_thread_unsafe(): No more room in config
nvme.c: 314:nvme_driver_init: *ERROR*: primary process failed to reserve memory
*ERROR*: === BACKTRACE START ===
*ERROR*:   1: nvme_driver_init() at 0x4bf05e
*ERROR*:   2:  spdk_nvme_connect() at 0x4c1737
*ERROR*:   3:   nvme_spdk_nvmf_connect() at 0x473a8c
*ERROR*:   4:    fdiscover() at 0x44b54a
*ERROR*:   5:     discover_cmd() at 0x40ac4e
*ERROR*:   6:      handle_plugin() at 0x4508b0
*ERROR*: === BACKTRACE END ===

 09:10:30	# ./nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 10.0.2.15 -s 4420
 09:10:31	# ./nvme disconnect -n nqn.2016-06.io.spdk:cnode1
are also report this error.

And trace did't catch these errors.

## Expected Behavior
./nvme discover , ./nvme connect and ./nvme disconnect run pass.

## Current Behavior
./nvme reports EAL parameters.

## Possible Solution
Check nvme_cli EAL parameters.

## Steps to Reproduce
1. view build log on fedora-06 server,
https://ci.spdk.io/spdk/builds/review/9617f6fadf0b52c3b53cd8f5d968390be4dfaed1.1548164914/fedora-06/build.log (search "BACKTRACE")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit ac5b26e4cb8fda257661c8707d98369271ec3170

**Comment by darsto** [comment]
Apparently this was already reported in #471 and proper fixes were merged to spdk-cli. It's just that CTP still uses an outdated nvme-cli version. @Seth5141 could you perform an update?

**Comment by Seth5141** [comment]
@wanghailiangx I have update the nvme-cli repos on the CTP. Please check tonight to see if the issue has been resolved. @darsto thanks for pointing this out. I wasn't aware of the previous issue or updates.

**Comment by wanghailiangx** [comment]
@Seth5141 Thanks your updated code. But "fedora-06" server where nvme_cli.sh run on have run time out and have no build logs for several days. Could you check it? By the way, look at the freebsd-0 server, thanks. 
https://ci.spdk.io/spdk/builds/review/9792718f18ac8d424f6caae84bf1da1f78f21eff.1548684497/  (1/29/2019)

**Comment by darsto** [comment]
This also broke fedora-03, please see the following patch:
https://review.gerrithub.io/c/spdk/spdk/+/442552

```
test/nvmf/nvme-cli: don't run nvme-cli as secondary process

nvme-cli in NVMf tests currently fails to initialize
the NVMe driver and exits straight away [1]. It expects
the primary process to initialize the driver first, but
since the primary process doesn't operate on any NVMe
devices, it doesn't initialize the driver at all.

Fix this by running nvme-cli without multi-process mode.
In NVMf tests, nvme-cli is only used to discover, connect
and disconnect from an SPDK NVMf target. It does not need
to access any shared memory resources.

This wasn't an issue before, because we used an outdated
DPDK version for nvme-cli which didn't detect any other
shared memory processes of SPDK.

[1] nvme.c: 337:nvme_driver_init: *ERROR*: primary process
is not started yet
```

**Comment by wanghailiangx** [comment]
Thanks, verified, closing the issue.
