### ISSUE TITLE
spdk_thread_lib_fini: io_device not unregistered on app exit

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#618]
## Current Behavior
Error message displayed on app exit:
thread.c: 179:spdk_thread_lib_fini: *ERROR*: io_device AIO1 not unregistered

## Expected Behavior
Clean exit.

## Steps to Reproduce
1. Start SPDK target app or Vhost app
2. Create file for AIO bdev:
```
dd if=/dev/zero of=testfile bs=512 count=100000
```
3. Construct AIO bdev
```
sudo scripts/rpc.py construct_aio_bdev /home/klateck/work/testfile AIO1 512
```
4. Ctrl-C to stop SPDK app
```
thread.c: 179:spdk_thread_lib_fini: *ERROR*: io_device AIO1 not unregistered
```

## Context (Environment including OS version, SPDK version, etc.)
Tested on: 9cddfc0 vhost: move lcore management to the device backend

**Comment by jimharris** [comment]
Can you try https://review.gerrithub.io/c/spdk/spdk/+/442119?
