### ISSUE TITLE
nvme cli returns error, if drive doesn't have any namespace

### ISSUE THREAD

**Issue by nagendra-v** [spdk/spdk#620]
nvme cli returns error for all commands if drive doesn't have any namespace

## Expected Behavior
cli commands should work with or without namespace's

## Current Behavior
Cli returns error:

command: **nvme id-ctrl <0000:27:00.0>**
cli output:
EAL: Cannot find resource for device
identify controller: Inappropriate ioctl for device

command: **nvme list-ns <0000:27:00.0>**
cli output:
EAL: Cannot find resource for device
id namespace list: Inappropriate ioctl for device

## Steps to Reproduce
1. Get NVMe drive with multiple namespace's support
2. Delete all namespace's
3. run spdk nvme cli (id-ctrl)

## Context (Environment including OS version, SPDK version, etc.)
Issue seen SPDK v18.10.1 / DPDK 18.08.0 and **_nvme cli 1.6 Pre_**

**Comment by nagendra-v** [comment]
Even "spdk/examples/nvme/identify" command also shows "EAL: Cannot find resource for device" error and doesn't get controller details.

**Comment by changpe1** [comment]
@nagendra-v  for your cases, the nvme-cli tool should be started with secondary process, so you may change the spdk.conf in your nvme-cli directory and change shm_id=1 in the case you started nvmf_tgt by default.

**Comment by Comphix** [comment]
By the way, please also have a try with below patch although there is some comments.

https://review.gerrithub.io/#/c/spdk/nvme-cli/+/432526/

As Changpeng mentioned, in your case, nvme-cli needs to start as the secondary process when there is other SPDK process (primary) is running.

More about nvme-cli, please refer to https://spdk.io/doc/spdkcli.html

**Comment by darsto** [comment]
Bug scrub: @nagendra-v Just to verify: have you tried running nvme-cli with NVMe that does have some namespaces?

**Comment by nagendra-v** [comment]
@dastro: Yes, drives which have at least one namespace are shown in "list" command. Below are details.
@changpe1: "shm_id=1" is set in spdk.conf file, otherwise probe fails.
@Comphix : Tried latest spdk nvme-cli, still seeting errors. Below are details

[root@localhost nvme-cli-spdk-0129]# ./nvme list
Starting SPDK v18.10.1 / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x80 -m 512 --file-prefix=spdk1 --base-virtaddr=0x200000000000 --proc-type=auto --log-level=8 ]
EAL: Detected 8 lcore(s)
EAL: Detected 4 NUMA nodes
EAL: Auto-detected process type: SECONDARY
EAL: Multi-process socket /var/run/dpdk/spdk1/mp_socket_19377_3cda5afc4c
EAL: Probing VFIO support...
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:07:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: Unknown handle type of fd -1
EAL: Unknown handle type of fd -1
EAL: PCI device 0000:25:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:27:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:44:00.0 on NUMA socket 2
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:46:00.0 on NUMA socket 2
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:62:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:64:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:66:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:68:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
0000:27:00.0     BTLN836302SC1P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB    512   B +  0 B   VDV10152
0000:05:00.0     BTLN836301611P6AGN   INTEL SSDPE2KE016T8                      1           1.07  GB /   1.07  GB    512   B +  0 B   VDV10152
0000:62:00.0     BTLN836301QD1P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB    512   B +  0 B   VDV10152
0000:68:00.0     BTLN8363013D1P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB    512   B +  0 B   VDV10152
0000:44:00.0     BTLN836301S01P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB    512   B +  0 B   VDV10152
0000:25:00.0     BTLN836302TY1P6AGN   INTEL SSDPE2KE016T8                      1           2.15  GB /   2.15  GB    512   B +  0 B   VDV10152
0000:46:00.0     BTLN836303DP1P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB    512   B +  0 B   VDV10152
0000:64:00.0     BTLN836302S71P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB    512   B +  0 B   VDV10152
0000:66:00.0     BTLN836303CV1P6AGN   INTEL SSDPE2KE016T8                      1           1.60  TB /   1.60  TB    512   B +  0 B   VDV10152
[root@localhost nvme-cli-spdk-0129]# ./nvme list-ns 0000:07:00.0

----------------------------------------------------------------------------------------------------------------------- 
Starting SPDK v18.10.1 / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x80 -m 512 --file-prefix=spdk1 --base-virtaddr=0x200000000000 --proc-type=auto --log-level=8 ]
EAL: Detected 8 lcore(s)
EAL: Detected 4 NUMA nodes
EAL: Auto-detected process type: SECONDARY
EAL: Multi-process socket /var/run/dpdk/spdk1/mp_socket_1765_499184ace4
EAL: Probing VFIO support...
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:07:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
**_EAL: Unknown handle type of fd -1
EAL: Unknown handle type of fd -1_**
EAL: PCI device 0000:25:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:27:00.0 on NUMA socket 1
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:44:00.0 on NUMA socket 2
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:46:00.0 on NUMA socket 2
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:62:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:64:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:66:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: PCI device 0000:68:00.0 on NUMA socket 3
EAL:   probe driver: 8086:a54 spdk_nvme
**_id namespace list: Inappropriate ioctl for device_**

**Comment by Comphix** [comment]
Hi @nagendra-v 

"@Comphix : Tried latest spdk nvme-cli, still seeting errors. Below are details"

Have you tried with the change of my below patch? Seems that you just used the latest master code? 
https://review.gerrithub.io/#/c/spdk/nvme-cli/+/432526/

Thanks,
Gang

**Comment by nagendra-v** [comment]
**_Without "nvmf_tgt"_** running, with patch "nvme list" command doesn't show the drive with no namespace. But other commands "id-ctrl", create-ns and attach-ns work.

**With "nvmf_tgt"**, cli still doesn't work and shows following error. I think this need to be addressed in "nvmf_tgt" too.
# ./nvme_fix id-ctrl 0000:07:00.0
Starting SPDK v18.10.1 / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x80 -m 512 --file-prefix=spdk1 --base-virtaddr=0x200000000000 --proc-type=auto --log-level=8 ]
EAL: Detected 8 lcore(s)
EAL: Detected 4 NUMA nodes
EAL: Auto-detected process type: SECONDARY
EAL: Multi-process socket /var/run/dpdk/spdk1/mp_socket_9523_3f66dcb6a017f
EAL: Probing VFIO support...
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
**_EAL: PCI device 0000:07:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL: Cannot find resource for device_**

**Comment by Comphix** [comment]
For the second case of "with nvmf_tgt", it could be a little relating to the primary process's work of initializing and attaching the zero namespace controllers so that the second process (nvme cli) can operate it as requested trhough id-ctrl commands. I will take a look later. Thanks, Gang. Glad to know that "without nvmf_tgt" and in standalone mode, it works although I am still thinking why the "list" command does not work...

**Comment by darsto** [comment]
Bug scrub: just to verify - this is an issue inside nvme-cli. Maybe it's been fixed in nvme-cli 1.7 - @Seth5141 to check that.

**Comment by nagendra-v** [comment]
@darsto There is no SPDK nvme-cli 1.7 version, I see master and 1.6 version at https://github.com/spdk/nvme-cli

**Comment by Comphix** [comment]
@nagendra-v , I am looking at these issues.

For the SPDK nvme-cli standalone usage, just double confirm that you have tried my latest patch at 
https://review.gerrithub.io/#/c/spdk/nvme-cli/+/432526/ 

I've also added the expected result from the change as below:

Patch Set 2:

The result with this change will be:

1. No namespace for the ctrlr. We will still display the BDF there so that it knows this ctrlr is managed by SPDK (similar to /dev/nvmeX)

Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
0000:09:00.0     CVEK5224001U1P0BGN   INTEL SSDPD2ME010T4                      0           0.00   B /   0.00   B      0   B +  0 B   8AP5Z514
0000:81:00.0     PHFT6401010Y800CGN   INTEL SSDPEDMD800G4                      1         800.17  GB / 800.17  GB    512   B +  0 B   8DV10171

2. Display more than one namespaces for one ctrlr, the BDF is same for the same ctrlr similar to /dev/nvmeXnY (the prefix part of /dev/nvmeX).

Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
0000:09:00.0     CVEK5224001U1P0BGN   INTEL SSDPD2ME010T4                      1           1.07  GB /   1.07  GB    512   B +  0 B   8AP5Z514
0000:09:00.0     CVEK5224001U1P0BGN   INTEL SSDPD2ME010T4                      2           1.07  GB /   1.07  GB    512   B +  0 B   8AP5Z514
0000:81:00.0     PHFT6401010Y800CGN   INTEL SSDPEDMD800G4                      1         800.17  GB / 800.17  GB    512   B +  0 B   8DV10171

**Comment by Comphix** [comment]
For the test to work with other SPDK applications like NVMe-oF target, needs to start the two processes (1: NVMe-oF; 2: nvme-cli) in the multi-process mode.

1. Add "-i 1" parameter to the first SPDK application, it will show
    EAL: Auto-detected process type: PRIMARY

2. Edit spdk.conf file under the nvme-cli folder
    shm_id=1

3. "1" is any positive number that we can assign

4. Start nvme-cli, run "./nvme list" will show the result and with below information
    EAL: Auto-detected process type: SECONDARY

Please let me know if there is any question.

**Comment by nagendra-v** [comment]
@Comphix 
I have tested patch https://review.gerrithub.io/#/c/spdk/nvme-cli/+/432526/ with SPDK 19.01, it works. I am able delete all NS's and create.
I don't see the patch merged yet to cli V1.6, when is it expected to be released?

**Comment by darsto** [comment]
Bug scrub: The long term goal is to add RPC for NVMe management operations into SPDK itself. As for now, we will still try to fix nvme-cli.

**Comment by jimharris** [comment]
Assigning this issue to @tkulasek.  He is working on support namespace management with the recently added NVMe CUSE functionality.  That is the long-term strategy for using nvme-cli with SPDK.

@tkulasek - you can close this issue once we have the NVMe CUSE changes implemented and merged.

**Comment by tomzawadzki** [comment]
Support for Namespace Management with NVMe CUSE has been merged - series ending in c9bde257f0133f991aea7a370ef531961375bb6d.

Please see https://spdk.io/doc/nvme.html#nvme_cuse for details.
