### ISSUE TITLE
nvme: check if sq is full before submitting command

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#621]
Hi,

Currently in lib/nvme/nvme_pcie.c, there's an error log if pqpair's sq_tail equals to sq_head, which means the sq is already full.

```
static void
nvme_pcie_qpair_submit_tracker(struct spdk_nvme_qpair *qpair, struct nvme_tracker *tr)
{
        // ...

	/* Copy the command from the tracker to the submission queue. */
	nvme_pcie_copy_command(&pqpair->cmd[pqpair->sq_tail], &req->cmd);

	if (++pqpair->sq_tail == pqpair->num_entries) {
		pqpair->sq_tail = 0;
	}

	if (pqpair->sq_tail == pqpair->sq_head) {
		SPDK_ERRLOG("sq_tail is passing sq_head!\n");
	}
// ...
```

After checking nvme specification (listed below), I think maybe it's better to check if sq is full before submitting command. If the sq is full, then complete this command with error status code and let caller to retry this command later. And the retried command may succeed if sq is consumed by nvme ssd during the retry interval.

So I am writing a draft patch to add this check. I have written most part of this patch, except an obstacle. The obstacle is that nvme specification doesn't define a specialized status code for the full submission queue case. I have read the section 4.6.1.2 'Status Code (SC)' several times, but still haven't found the appropriate status code.

---

Here are the places where full sq is mentioned in [NVM Express 1.3 specification](https://nvmexpress.org/wp-content/uploads/NVM_Express_Revision_1.3.pdf):

From section 4.1 'Submission Queue & Completion Queue Definition'
> The submitter may continue to place entries in free queue slots as long as the Full queue condition is not met

From section 7.2.2 'Basic Steps when Building a Command '
> When host software builds a command for the controller to execute, it first checks to make sure that the appropriate Submission Queue (SQx) is not full.

**Comment by changpe1** [comment]
@lorneli , actually the line "if (pqpair->sq_tail == pqpair->sq_head)" will never happen in the case the FW has a correct behavior, actually we add this line for debug purpose, so I think you can remove it. in the function nvme_pcie_qpair_submit_request() SPDK already checked the queue is full or not via the free_tr list.

**Comment by lorneli** [comment]
Hi changpeng,

Thanks a lot for your reply. I haven't noticed that before.
