### ISSUE TITLE
SPDK vhost-nvme reported error while attaching device into fedora26 VM

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#628]
I have tried to run vhost-nvme with fedora26 VM. But the vhost-nvme reported error and the Fedora 26VM can't see the nvme block device, but only the nvme pci controller.

## Expected Behavior
the fedora26 VM can set the nvme block device.

## Current Behavior
vhost-nvme reported error and the Fedora 26VM can't see the nvme block device, but only the nvme pci controller.

## Possible Solution
If I used the old codes(0652c0a6c4a4cd1d058f8439469d557540331e04), this issue then can't happen. 

## Steps to Reproduce
1. start vhost-nvme with following config:
```
[AIO]
  AIO /dev/sdb AIO0
  AIO /dev/sdc AIO1
[Malloc]
  NumberOfLuns 2
  LunSizeInMB 128
  BlockSize 512
[Nvme]
  TransportID "trtype:PCIe traddr:0000:07:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:81:00.0" Nvme1
  TransportID "trtype:PCIe traddr:0000:82:00.0" Nvme2
[VhostNvme0]
  Name vhost.0
  Namespace Malloc0

[VhostNvme1]
  Name vhost.1
  Namespace Malloc1

[VhostNvme2]
  Name vhost.2
  Namespace Nvme0n1

[VhostNvme3]
  Name vhost.3
  Namespace Nvme1n1

[VhostNvme4]
  Name vhost.4
  Namespace AIO0

[VhostNvme5]
  Name vhost.5
  Namespace AIO1

```
 
2. use spdk qemu repo with branch spdk-2.12, then add changpeng's patch.
3. run qemu with fedora26 VM.

`/home/storage/qemu-nvme/build/x86_64-softmmu/qemu-system-x86_64 -cpu host -smp 8 -m 10240 -object memory-backend-file,id=mem,size=10G,mem-path=/dev/hugepages,share=on -numa node,memdev=mem -drive file=/root/Fedora26.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -net user,hostfwd=tcp::10000-:22 -net nic -chardev socket,id=char0,path=/home/storage/spdk-latest/vhost.0 -device vhost-user-nvme,chardev=char0 -chardev socket,id=char1,path=/home/storage/spdk-latest/vhost.1 -device vhost-user-nvme,chardev=char1 -chardev socket,id=char2,path=/home/storage/spdk-latest/vhost.2 -device vhost-user-nvme,chardev=char2  -chardev socket,id=char3,path=/home/storage/spdk-latest/vhost.3 -device vhost-user-nvme,chardev=char3 -chardev socket,id=char4,path=/home/storage/spdk-latest/vhost.4 -device vhost-user-nvme,chardev=char4 --chardev socket,id=char5,path=/home/storage/spdk-latest/vhost.5 -device vhost-user-nvme,chardev=char5 -enable-kvm &
`
4. login into the VM, then you can't see the nvme block device, only pci controller, nvme0, nvme1, nvme2, nvme3, etc.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit:  9fd924cb40e755f98d65c1e5504ed1a1a04d9ad3

**Comment by changpe1** [comment]
@liang2yan I submit a patch to fix the issue, https://review.gerrithub.io/#/c/spdk/spdk/+/442498/

**Comment by liang2yan** [comment]
@changpe1 , just verified your patch. It can fix this issue!

**Comment by changpe1** [comment]
closing the issue as patch has been merged.
