### ISSUE TITLE
cannot build fio plugin

### ISSUE THREAD

**Issue by hsuedw** [spdk/spdk#63]
Hi

I tried to build spdk package with fio plugin.
1. I followed the instruction of spdk/examples/nvme/fio_plugin/README.md and build fio first.
    (1) git clone https://github.com/axboe/fio
    (2) cd fio && git checkout fio-2.8
    (3) ./configure && make
    (4) add following line in ../dpdk-16.07/config/defconfig_x86_64-native-linuxapp-gcc
          EXTRA_CFLAGS=-fPIC
2. I run "make DPDK_DIR=../dpdk-16.07/x86_64-native-linuxapp-gcc/" to build spdk and find the following error message.

  LINK examples/nvme/fio_plugin/fio_plugin
/usr/bin/ld: /root/intel_spdk_dpdk/dpdk-16.07/x86_64-native-linuxapp-gcc/lib/librte_eal.a(eal.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/root/intel_spdk_dpdk/dpdk-16.07/x86_64-native-linuxapp-gcc/lib/librte_eal.a(eal.o): could not read symbols: Bad value
collect2: error: ld returned 1 exit status

How can I fix this??

BRs
Edward

**Comment by hsuedw** [comment]
I guess I fixed this issue.

After adding "EXTRA_CFLAGS=-fPIC" in dpdk-16.07/config/defconfig_x86_64-native-linuxapp-gcc, I rebuild dpdk.

I change directory to where spdk source code is located and run "make DPDK_DIR=../dpdk-16.07/x86_64-native-linuxapp-gcc/". 

Then, spdk is built successfully (including fio plugin).

BRs
Edward

**Comment by dverkamp-intel** [comment]
Just to clarify: did you resolve your issue by following the fio_plugin README.md instructions (if so, I think we can close this issue), or do we need to update the steps in the readme?

**Comment by hsuedw** [comment]
I think this issue can be closed.

BRs
Edward
