### ISSUE TITLE
nvmf target crashed with pcie nvme bdev's hotremoval

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#635]
this issue is similar with issue 570, except that run nvmf target with -m 0xffff.

## Expected Behavior
nvmf target not crash.

## Current Behavior
nvmf target crashed.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000047819e in spdk_nvmf_qpair_disconnect (qpair=0x1103e20, cb_fn=0x0, ctx=0x0)
    at nvmf.c:774
774             assert(qpair->group->thread == spdk_get_thread());
[Current thread is 1 (Thread 0x7f9936da4700 (LWP 2471))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.27-32.fc28.x86_64 libnl3-3.4.0-3.fc28.x86_64 zlib-1.2.11-8.fc28.x86_64
(gdb) bt
#0  0x000000000047819e in spdk_nvmf_qpair_disconnect (qpair=0x1103e20, cb_fn=0x0, ctx=0x0)
    at nvmf.c:774
#1  0x0000000000487022 in _nvmf_rdma_qpair_disconnect (ctx=0x1103e20) at rdma.c:2204
#2  0x0000000000490f1e in _spdk_msg_queue_run_batch (thread=0x7f9918000b20, max_msgs=8)
    at thread.c:297
#3  0x00000000004910a3 in spdk_thread_poll (thread=0x7f9918000b20, max_msgs=0) at thread.c:338
#4  0x000000000048bba3 in _spdk_reactor_run (arg=0xf32100) at reactor.c:320
#5  0x00000000004c8308 in eal_thread_loop (arg=0x0)
    at /home/yanliang/spdk-latest/dpdk/lib/librte_eal/linuxapp/eal/eal_thread.c:153
#6  0x00007f993a021594 in start_thread () from /lib64/libpthread.so.0
#7  0x00007f9939d54e6f in clone () from /lib64/libc.so.6

```
## Steps to Reproduce
1. run nvmf target with -m 0xffff.
2. run fio job in host machines.
3.  remove nvme controller using rpc command.
4. use ctrlr+c to kill nvmf target.

## Context (Environment including OS version, SPDK version, etc.)
SPDK : abc156458fff4f25104604bf91b39651d9423a9a

**Comment by darsto** [comment]
Bug scrub: there's a patch out on gerrithub. @Seth5141 to add more details

**Comment by Seth5141** [comment]
Hi @liang2yan This issue has been classified with about 5 other hotplug bugs. Thanks to @optimistyzy and @wanqunintel we have a list of them, and I will be looking at this issue within that broader context today or tomorrow. Thanks!

**Comment by Seth5141** [comment]
@liang2yan Since this is the same configuration as #570 I think we should close this one and focus comments on that issue. The fact that the core dump is different is interesting, but may just be a side effect of the timing with which you pull the drives. If we are able to figure out the problem with 570 and this one still occurs, we should reopen it.
