### ISSUE TITLE
the nvmf/tcp bdev can't be used to create lvol_stores

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#638]
this issue is similar with issue 629. Just create lvol_store based on the tcp nvme bdev. but failed.

## Expected Behavior
command can be executed successfully.

## Current Behavior
command failed.

## Steps to Reproduce
1. same steps with issue 629.
2. same step with issue 629.
3. create lvol_store in spdkcli.py tool.
create bdev_name=Nvme0n1 cluster_size=1048576 name=lvs
4. the spdkli.py tool reported error:
```
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0",
  "method": "construct_lvol_store",
  "id": 21,
  "params": {
    "bdev_name": "Nvme0n1",
    "lvs_name": "lvs",
    "cluster_sz": 1048576
  }
}
response:
{
  "code": -32602,
  "message": "Invalid argument"
}

```
5. spdk reported error:

```
blobstore.c: 955:_spdk_blob_load_cpl: *ERROR*: Metadata page 1 crc mismatch
lvol.c: 497:_spdk_super_blob_create_open_cb: *ERROR*: Lvol store init failed: could not open super blob

```

**Comment by optimistyzy** [comment]
@liang2yan This patch will fix this issue:  https://review.gerrithub.io/c/spdk/spdk/+/444066

**Comment by jimharris** [comment]
Hi @liang2yan - can you confirm this patch fixes the issue?

@optimistyzy - I have added +2 to this patch.  But could we also add an lvol test for this case?

This patch needs to be merged for v19.01.1.

**Comment by liang2yan** [comment]
I have verified ziye's patch(https://review.gerrithub.io/c/spdk/spdk/+/444066). I can create lvol_store and logical_volume now.

**Comment by changpe1** [comment]
closing the issue now as the patch has been merged.
