### ISSUE TITLE
the fio process will hung up  after hotremoving rdma transport nvme bdev 

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#639]
this issue is similar with issue 627, except that I created raid bdev based on the rdma transport nvme bdev.

## Expected Behavior
host machine still can run fio again.

## Current Behavior
fio process caused kernel coredump.

## Steps to Reproduce
1. same step with issue 627.
2. same step with issue 627.
3. create raid bdev based on the rdma transport nvme bdev.
4.  run fio in host machine.
5. use rpc command to remove the raid bdev.
6. fio process will hung up in host machine.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: ad0b3c974f7b1a9213c7bfb6f1f9bc24517022dc

**Comment by liang2yan** [comment]
This issue also happened if I create logical_volumes based on the RDMA transport nvme bdev.

**Comment by changpe1** [comment]
[Bug Scrub] @Seth5141 you can use the following method to remove/add one physical NVMe drive:
[1]: echo 1 >/sys/bus/pci/devices/0000\:84\:00.0/remove
[2]: echo 1 >/sys/bus/pci/rescan

**Comment by Seth5141** [comment]
@liang2yan I am going to close this one since it is so closely related to #627, especially as it relates to the setup. Let's focus questions and progress on that issue and once it's fixed, if you can still replicate this one we can reopen it.
