### ISSUE TITLE
Cannot add new device(LUN) into an existing iSCSI target.

### ISSUE THREAD

**Issue by liupan1111** [spdk/spdk#64]
A new ISCSI target must be created for a new device. This behavior doesn't make sense.

**Comment by liupan1111** [comment]
I will pull a request for this issue.

**Comment by liupan1111** [comment]
https://github.com/spdk/spdk/pull/67

**Comment by benlwalker** [comment]
As of SPDK 18.01, there is an RPC to add a lun to a target node.

**Comment by liupan1111** [comment]
thanks
