### ISSUE TITLE
NVMe-oF RDMA target not properly validating SGL element limitations

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#640]
## Expected Behavior
The NVMe-oF target should work independent of the number of the number of SGL elements supported by the device.

## Current Behavior
On at least one NIC (intel x722) that supports fewer than the default number of SGL elements, intermittent failures happen when attempting ibv_post_send operations. ibv_post_send returns -EINVAL and the request cannot be sent.

Currently the buffers in the transport data_buf_pool are too small to accommodate a full sized I/O when processed through spdk_nvmf_rdma_request_fill_iovs if the maximum number of supported SGEs is less than SPDK_NVMF_MAX_SGL_ENTRIES. That function does not check to make sure that we don't overshoot the qpair limitations for SGL element sizes.

## Possible Solution

Since we know all of our devices up front, we can force the buffer sizes to be at least SPDK_NVMF_MAX_IO_SIZE / device->max_send_sge for the device with the smallest number of SGEs. We should also include a check to make sure that we aren't overshooting the max number of SGEs in spdk_nvmf_rdma_request_fill_iovs.

## Steps to Reproduce
Use an intel x722 NIC when setting up the NVMe-oF target.
You can configure the target and try to connect to it from the kernel initiator as follows to 
~~~
sudo ./app/nvmf_tgt/nvmf_tgt &
sudo scripts/rpc.py construct_malloc_bdev 512 512
sudo scripts/rpc.py nvmf_construct_transport -t rdma -p 4 -c 0 (key here is that you keep the default I/O size and I/O unit size)
sudo ./scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a <x722 is addr> -s 4420
sudo nvme connect -t rdma -n "nqn.2016-06.io.spdk:cnode1" -t rdma -a <x722 ip address> -s 4420
~~~

At this point you should see some error messages from request_transfer_out indicating failed send operations. disconnecting from the target will sometimes work, but will sometimes hang the initiator.

## Context (Environment including OS version, SPDK version, etc.)
spdk: v19.01-pre This issue was introduced by 1d9be84bfdf80072422b5bc64a498714af04ca16 when we changed the buffer size to be smaller than max_io_size to save memory.

**Comment by Seth5141** [comment]
Correction from earlier: this error can actually be reproduced as early as commit 8e80849.
I was able to prevent this error on master (with an x722 NIC in loopback) with the following patch: https://review.gerrithub.io/#/c/spdk/spdk/+/442776/.
@pcybulski can you verify this fix on master?

**Comment by pcybulski** [comment]
It did work for a few iteration of connect/disconnect then it started failing, details below 
rdma.c:1903:spdk_nvmf_rdma_create: *NOTICE*: Adjusting the io unit size to fit maximum I/O size. New I/O unit size 45056
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 578:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#1: expected state: IBV_QPS_ERR, actual state: IBV_QPS_RESET
rdma.c: 578:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#0: expected state: IBV_QPS_ERR, actual state: IBV_QPS_RESET
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#1: bad state updated: 192, maybe hardware issue
rdma.c: 578:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#1: expected state: IBV_QPS_ERR, actual state: IBV_QPS_UNKNOWN
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#1: bad state updated: 192, maybe hardware issue
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 578:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#0: expected state: IBV_QPS_ERR, actual state: IBV_QPS_UNKNOWN
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 128, maybe hardware issue
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 128, maybe hardware issue
rdma.c: 760:spdk_nvmf_rdma_qpair_initialize: *ERROR*: RDMA CQ resize failed: errno 11: Resource temporarily unavailable
rdma.c: 644:nvmf_rdma_dump_qpair_contents: *ERROR*: Dumping contents of queue pair (QID 0)
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 1
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 2
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 3
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 4
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 5
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 6
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 7
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 8
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 9
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 10
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 11
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 12
rdma.c: 667:spdk_nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 128
rdma.c:2691:spdk_nvmf_rdma_poll_group_add: *ERROR*: Failed to initialize nvmf_rdma_qpair with qpair=0x151da00
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 128, maybe hardware issue
rdma.c: 578:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#0: expected state: IBV_QPS_ERR, actual state: IBV_QPS_UNKNOWN
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 128, maybe hardware issue
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 760:spdk_nvmf_rdma_qpair_initialize: *ERROR*: RDMA CQ resize failed: errno 11: Resource temporarily unavailable
rdma.c: 644:nvmf_rdma_dump_qpair_contents: *ERROR*: Dumping contents of queue pair (QID 0)
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 1
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 2
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 3
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 4
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 5
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 6
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 7
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 8
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 9
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 10
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 11
rdma.c: 646:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 12
rdma.c: 667:spdk_nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 128
rdma.c:2691:spdk_nvmf_rdma_poll_group_add: *ERROR*: Failed to initialize nvmf_rdma_qpair with qpair=0x15b1cc0
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 578:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#0: expected state: IBV_QPS_ERR, actual state: IBV_QPS_UNKNOWN
rdma.c: 496:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue

On initiator side it needed 8 iterations to start failing
nvme connect -t rdma -n "nqn.2016-10.io.spdk:cnode1" -a "100.0.0.90" -s "4420" -i 44
Failed to write to /dev/nvme-fabrics: Connection reset by peer

Setup seams to be fine (fresh master from today morning):
SPDK ce75af214046a321a224180b5b2abeeab90c3c96
DPDK 754c3dbc347f9e446ce05f6f44f52a29e458e013

Applying patch worked properly
patching file lib/nvmf/rdma.c
Hunk #1 succeeded at 63 (offset 2 lines).
Hunk #2 succeeded at 1735 with fuzz 2 (offset 18 lines).
Hunk #3 succeeded at 1852 (offset 13 lines).
Hunk #4 succeeded at 1890 (offset -4 lines).

**Comment by Seth5141** [comment]
@bcyblski Thank you!

I was also able to replicate this new behavior. The new disconnect failure is caused by the combination of a few circumstances.

The SPDK NVMe-oF target relies on submitting a dummy send and recv request to each qpair as it is closing. It doesn't completely free the resources allocated with the qpair until those requests have shown up in the shared completion queue.
In the case of the intel x722 NIC (and the Soft-RoCE implementation) these requests never get completed and the SPDK NVMe-oF target assumes that it still needs resources for these defunct qpairs. These resources include completion queue entries in the shared completion queue.
So every time you connect and disconnect, the number of entries required by the completion queue go up until we have to resize the shared completion queue.
The x722 NIC fails the request to increase the size of the qpair every time. From looking at the rdma-core source code, it looks like the i40iw driver has not implemented the ibv_resize_cq command.

In summary, I think there are a couple of real bugs/vulnerabilities in both SPDK and the i40iw driver

SPDK:
For NICs that are misbehaving according to our understanding, we can't just not free qpair resources. We need a way to clean up defunct qpairs from closed connections.
i40iw driver:
Without the ability to resize the completion queue, there will be problems with scaling the number of connections the NIC can make on the SPDK transport. Submitting more SENDs and RECVs than the completion queue can support results in all connections being dropped, so SPDK makes sure that we always have enough completions to satisfy all connections at full queue depth. Since completion queue entries represent memory overhead, we don't allocate enough for all possible connections as they come in, but resize the cq as we need more to stay conservative on memory.

I will have to look at the spec and think through how to properly detect and free defunct qpairs in SPDK.

I think that the resize_cq function should be implemented in the i40iw driver, but there is also an SPDK change coming down the pipeline that will remove the need to call that function from SPDK. It adds shared receive queue support which allows us to know exactly how many completion queue entries we will need at the beginning of time. You can check it out here. https://review.gerrithub.io/#/c/spdk/spdk/+/428458/

**Comment by pcybulski** [comment]
Thank you for very detailed description about what is going on under the hood. Will create issue for i40iw and add your comment so we can work on that problem from both sides.

**Comment by Seth5141** [comment]
@pcybulski Thanks!
I have created a patch in SPDK for dealing with freeing the memory from disconnected qpairs. Please let me know if adding this patch on top of the previous patch completely resolves this issue for you. https://review.gerrithub.io/#/c/spdk/spdk/+/443057/.
And by completely resolves, I mean allows you to connect and disconnect an arbitrary number of times without issue. There is still the underlying issue of what to do if we continue to add connections and overshoot the completion queue size and the NIC driver doesn't support resize. But I think we can wait to see what the NIC people say first.
Thanks again for all of your work on this. It has been really informative for me.

**Comment by pcybulski** [comment]
I will check new patch on Tuesday and report results, thanks again for very good cooperation.

**Comment by pcybulski** [comment]
Not sure if I did it correctly, there are three patches:
https://review.gerrithub.io/c/spdk/spdk/+/442776/
https://review.gerrithub.io/c/spdk/spdk/+/428458/
https://review.gerrithub.io/c/spdk/spdk/+/443057/

I tried applying 1st and 3rd (second had some warnings)  and issue reproduced.
Tried applying all patches and on second one there was following output:
patch -p1 < 3e2a0dc.diff
patching file CHANGELOG.md
Hunk #1 succeeded at 121 with fuzz 2 (offset 65 lines).
patching file CONFIG
patching file configure
patching file etc/spdk/nvmf.conf.in
Hunk #1 succeeded at 100 with fuzz 2 (offset 6 lines).
patching file include/spdk/nvmf.h
patching file lib/event/subsystems/nvmf/conf.c
Hunk #2 succeeded at 528 with fuzz 2 (offset 4 lines).
patching file lib/event/subsystems/nvmf/nvmf_rpc.c
Hunk #2 succeeded at 1448 with fuzz 1 (offset -6 lines).
patching file lib/nvmf/nvmf.c
patching file lib/nvmf/rdma.c
Hunk #1 succeeded at 248 with fuzz 2 (offset 9 lines).
Hunk #2 succeeded at 295 (offset 25 lines).
Hunk #3 succeeded at 306 (offset 25 lines).
Hunk #4 succeeded at 330 (offset 25 lines).
Hunk #5 succeeded at 365 with fuzz 1 (offset 27 lines).
Hunk #6 succeeded at 621 (offset 27 lines).
Hunk #7 succeeded at 640 (offset 27 lines).
Hunk #8 succeeded at 690 (offset 20 lines).
Hunk #9 succeeded at 729 (offset 20 lines).
Hunk #10 succeeded at 751 (offset 20 lines).
Hunk #11 succeeded at 763 (offset 20 lines).
Hunk #12 FAILED at 766.
Hunk #13 succeeded at 821 (offset 25 lines).
Hunk #14 succeeded at 883 (offset 61 lines).
Hunk #15 succeeded at 937 (offset 61 lines).
Hunk #16 succeeded at 986 with fuzz 2 (offset 102 lines).
Hunk #17 succeeded at 1021 (offset 65 lines).
Hunk #18 succeeded at 1083 (offset 66 lines).
Hunk #19 succeeded at 1253 (offset 67 lines).
Hunk #20 succeeded at 1634 (offset 118 lines).
Hunk #21 succeeded at 1815 (offset 125 lines).
Hunk #22 succeeded at 1836 (offset 125 lines).
Hunk #23 succeeded at 1877 (offset 120 lines).
Hunk #24 succeeded at 2335 with fuzz 2 (offset 169 lines).
Hunk #25 succeeded at 2365 (offset 178 lines).
Hunk #26 succeeded at 2378 (offset 178 lines).
Hunk #27 succeeded at 2687 (offset 178 lines).
Hunk #28 succeeded at 2697 with fuzz 2 (offset 178 lines).
Hunk #29 FAILED at 2540.
Hunk #30 FAILED at 2553.
Hunk #31 succeeded at 2770 (offset 188 lines).
Hunk #32 succeeded at 2907 (offset 188 lines).
Hunk #33 succeeded at 2925 (offset 188 lines).
Hunk #34 succeeded at 2934 (offset 188 lines).
Hunk #35 succeeded at 2949 with fuzz 1 (offset 189 lines).
Hunk #36 FAILED at 2830.
Hunk #37 FAILED at 2925.
5 out of 37 hunks FAILED -- saving rejects to file lib/nvmf/rdma.c.rej
patching file scripts/rpc.py
Hunk #1 FAILED at 1280.
Hunk #2 FAILED at 1291.
2 out of 2 hunks FAILED -- saving rejects to file scripts/rpc.py.rej
patching file scripts/rpc/nvmf.py
Hunk #1 FAILED at 82.
Hunk #2 FAILED at 94.
Hunk #3 FAILED at 115.
3 out of 3 hunks FAILED -- saving rejects to file scripts/rpc/nvmf.py.rej
[root@qa2090 spdk]# patch -p1 < 1069f81.diff
patching file lib/nvmf/rdma.c
Hunk #1 succeeded at 63 (offset 2 lines).
Hunk #2 succeeded at 1854 with fuzz 2 (offset 137 lines).
Hunk #3 succeeded at 1972 (offset 133 lines).
Hunk #4 succeeded at 2010 (offset 116 lines).

I do not meet one of the requirements on that setup:
NASM version 2.12.02 or newer  I have nasm-2.10.07-7.el7.x86_64

Also you added requirement of hugepagges but I did add those.

Target started normally but with multiple connect and disconnect issue reproduced:
Initiator
 nvme disconnect -n "nqn.2016-10.io.spdk:cnode1"
NQN:nqn.2016-10.io.spdk:cnode1 disconnected 0 controller(s)
 nvme connect -t rdma -n "nqn.2016-10.io.spdk:cnode1" -a "100.0.0.90" -s "4420" -i 44
Failed to write to /dev/nvme-fabrics: Connection reset by peer

Target
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 11
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 12
rdma.c: 763:spdk_nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 128
rdma.c:2879:spdk_nvmf_rdma_poll_group_add: *ERROR*: Failed to initialize nvmf_rdma_qpair with qpair=0x10f1a00
rdma.c: 545:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 627:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#0: expected state: IBV_QPS_ERR, actual state: IBV_QPS_UNKNOWN
rdma.c: 545:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 192, maybe hardware issue
rdma.c: 545:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 64, maybe hardware issue
rdma.c: 874:spdk_nvmf_rdma_qpair_initialize: *ERROR*: RDMA CQ resize failed: errno 11: Resource temporarily unavailable
rdma.c: 730:nvmf_rdma_dump_qpair_contents: *ERROR*: Dumping contents of queue pair (QID 0)
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 1
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 2
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 3
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 4
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 5
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 6
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 7
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 8
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 9
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 10
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 11
rdma.c: 732:nvmf_rdma_dump_qpair_contents: *ERROR*:     dumping requests in state 12
rdma.c: 763:spdk_nvmf_rdma_qpair_destroy: *WARNING*: Destroying qpair when queue depth is 128
rdma.c:2879:spdk_nvmf_rdma_poll_group_add: *ERROR*: Failed to initialize nvmf_rdma_qpair with qpair=0x1108cd0
rdma.c: 545:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 64, maybe hardware issue
rdma.c: 627:spdk_nvmf_rdma_set_ibv_state: *ERROR*: QP#0: expected state: IBV_QPS_ERR, actual state: IBV_QPS_UNKNOWN
rdma.c: 545:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 64, maybe hardware issue

I decided to go with master target started and I was able to connect but when I ran first fio test it crashed.

Command
 fio --rw=randwrite --bs=8192k --numjobs=128 --iodepth=128 --runtime=15 --size=10g --loops=1 --ioengine=libaio --direct=1 --invalidate=1 --fsync_on_close=1 --norandommap --exitall --filename=/dev/nvme0n1 --name=nvme0n1

Otuput from target
rdma.c: 494:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 64, maybe hardware issue
rdma.c: 494:spdk_nvmf_rdma_update_ibv_state: *ERROR*: QP#0: bad state updated: 128, maybe hardware issue
rdma.c:1006:request_transfer_out: *ERROR*: Unable to send response capsule
nvmf_tgt: rdma.c:1655: spdk_nvmf_rdma_request_process: Assertion `rc == 0' failed.
Aborted (core dumped)

Dmesg from initiator:
dmesg | egrep "err|rip|aeq|fail" -i
[ 2389.538993] nvme nvme0: rdma connection establishment failed (-104)
[ 2389.539079] i40iw AEQ_ENTRY
[ 2389.539084] i40iw i40iw_process_aeq ae_id = 0x501 bool qp=1 qp_id = 80
[ 2926.457575] i40iw AEQ_ENTRY
[ 2926.457582] i40iw i40iw_process_aeq ae_id = 0x502 bool qp=1 qp_id = 82
[ 2926.457597] i40iw AEQ_ENTRY
[ 2926.457605] i40iw i40iw_process_aeq ae_id = 0x502 bool qp=1 qp_id = 83
[ 2926.457619] nvme nvme0: RECV for CQE 0x000000000e95bc01 failed with status WR flushed (5)
[ 2926.466461] print_req_error: I/O error, dev nvme0c1n1, sector 64
[ 2926.466470] print_req_error: I/O error, dev nvme0c1n1, sector 128
[ 2936.564466] nvme nvme0: rdma connection establishment failed (-104)
[ 2936.564478] nvme nvme0: Failed reconnect attempt 1
[ 2946.805729] nvme nvme0: rdma connection establishment failed (-104)
[ 2946.805746] nvme nvme0: Failed reconnect attempt 2

Please let me know if you want me to do any more testing.

**Comment by Seth5141** [comment]
Hi @pcybulski Sorry to leave this hanging for so long. I was waiting on some of these patches to get merged. Now, everything has been merged except https://review.gerrithub.io/c/spdk/spdk/+/443057. Please checkout that commit and try running again.

**Comment by darsto** [comment]
The patch has been merged, so I'm closing this issue. Ping me if it's still reproducible so I'll reopen.
