### ISSUE TITLE
ext4test.sh reports rsync: write failed in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#642]
test/iscsi_tgt/ext4test/ext4test.sh reports rsync: write failed on "fedora-02" server, logs as below:

 09:51:04	# mkdir -p /mnt/sdbdir
 09:51:04	# mount -o sync /dev/sdb /mnt/sdbdir
 09:51:04	# rsync -qav --exclude=.git '--exclude=*.o' /home/sys_sgsw/build_pool/agent/repo/ /mnt/sdbdir/spdk
**rsync: write failed on "/mnt/sdbdir/spdk/test/nvme/err_injection/err_injection": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]**
  09:51:19	# dir -d /mnt/sdbdir
 09:51:19	# for new_dir in `dir -d /mnt/*dir`
 09:51:19	# umount /mnt/sdbdir
 09:51:19	# rm -rf /mnt/sdbdir
 09:51:19	# iscsicleanup
 09:51:19	# echo 'Cleaning up iSCSI connection'
Cleaning up iSCSI connection

========== Backtrace start: ==========
...
=> 524 		time "$@"
in ./test/iscsi_tgt/iscsi_tgt.sh:42 -> main()
     ...
=> 42  		**run_test suite ./test/iscsi_tgt/ext4test/ext4test.sh**
...
in /home/sys_sgsw/build_pool/agent/repo/test/common/autotest_common.sh:524 -> run_test()
=> 524 		time "$@"
     ...
in /home/sys_sgsw/build_pool/agent/repo/autotest.sh:146 -> main()
     ...
=> 146 		run_test suite ./test/iscsi_tgt/iscsi_tgt.sh posix
...
========== Backtrace end ==========

## Expected Behavior
 rsync -qav --exclude=.git '--exclude=*.o' /home/sys_sgsw/build_pool/agent/repo/ /mnt/sdbdir/spdk
rsync write passed, then make -C /mnt/sdbdir/spdk clean.

## Current Behavior
rsync: write failed

## Possible Solution
Check free space left on device

## Steps to Reproduce
1. view build log on "fedora-02" server,  https://ci.spdk.io/spdk/builds/review/850308304eb2c351a4f1ac3e91d8866b17f53485.1548858857/fedora-02/build.log (search "Backtrace start")

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit ce75af214046a321a224180b5b2abeeab90c3c96

**Comment by darsto** [comment]
@karlatec can you take a look at this? The disk we're rsyncing data to is 10GiB big - could it be that we're trying to copy some VM image by accident?

**Comment by karlatec** [comment]
Actually we most probably were rsyncing to a 512MB Malloc bdev which is used as a base for error injection bdev in test.
This should solve the problem: https://review.gerrithub.io/#/c/spdk/spdk/+/442867/

**Comment by wanghailiangx** [comment]
I think your patch can eliminate this issue, but two targets can run well before. Please refer to nightly log on 1/18 or earlier.
https://ci.spdk.io/spdk/builds/review/7f19ec4ea982477450336675d7267d4c991f378e.1547765089/fedora-02/build.log  (search "10.0.0.1:3260,1 iqn.2013-06.com.intel.ch.spdk:Target0" and "# rsync -qav --exclude")
