### ISSUE TITLE
on vmware workstation 14.x SPDK hello world example code failed to enumerated NVMe device on IOMMU VFIO mode

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#643]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

1. Ubuntu16.04 Kernel just be loaded and NVME device works well with kernel driver.
2. I use the vmware workstation 14.x that has NVME and IOMMU support, anyone can download free trial version.
3. if I use setup.sh to specify the UIO driver instead of VFIO driver, it also works too.
## Expected Behavior

in vmware workstation 14.x, OS and BIOS enable IOMMU, SPDK should enumerate NVME well and hello world application can run well
## Current Behavior

in vmware workstation 14.x, OS and BIOS enable IOMMU, SPDK failed enumerate NVME well and hello world application attach_cb callback is not invoked
## Possible Solution

definitely need one bug fix, or tell me what configure I am missing
## Steps to Reproduce

1.  install vmware workstation 14.x
2.  install ubuntu 16.04 LTS, bear in mind in vmware workstation create one VM, at CPU setting, choose IOMMU, vt-d on then install OS
3.  follow the SPDK get started build guide. but enable debug as 
sudo ./configure --enable-debug
4.  force use VFIO as 
sudo HUGEMEM=512 DRIVER_OVERRIDE=vfio-pci TARGET_USER=wayne scripts/setup.sh

5. then use non-root user to run hello world like below, you will see error below "no NVMe controllers found"
wayne@ubuntu:~/spdk/examples/nvme/hello_world$ ./hello_world 
Enter int: 1
Starting SPDK v19.01-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk0 --proc-type=auto ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /run/user/1000/dpdk/spdk0/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 15ad:7f0 spdk_nvme
no NVMe controllers found

from code level:
We can see the rc=0 that means probe is fine, but g_controllers is NULL. This is conflict logic. I found the attach_cb callback is not called with some reason. 
	rc = spdk_nvme_probe(NULL, NULL, probe_cb, attach_cb, NULL);
	if (rc != 0) {
		fprintf(stderr, "spdk_nvme_probe() failed\n");
		cleanup();
		return 1;
	}

	if (g_controllers == NULL) {
		fprintf(stderr, "no NVMe controllers found\n");
		cleanup();
		return 1;
	}
## Context (Environment including OS version, SPDK version, etc.)

I feel HW should have issue too, but I do not have one HW to test yet. our company will have it maybe next month.

**Comment by optimistyzy** [comment]
@gwnet Can you use the following command:
 lspci -n -s 03:00.0. It will list the class and vendor id info. For NVMe device, the class ID should beginning with 0108

**Comment by Comphix** [comment]
EAL: probe driver: 15ad:7f0 spdk_nvme

	RTE_LOG(INFO, EAL, "  probe driver: %x:%x %s\n", dev->id.vendor_id,
		dev->id.device_id, dr->driver.name);

Looks like
15ad is the vendor id for Vmware
7f0 is the device id

From https://pci-ids.ucw.cz/read/PC/15ad, it seems that 7f0 is not listed. Or maybe the content is not up to date.

**Comment by Comphix** [comment]
On the other hand, it looks like the "probe_cb" is also not called here from the log:

EAL: probe driver: 15ad:7f0 spdk_nvme
no NVMe controllers found

Otherwise, it will log:

Attaching to...

**Comment by gwnet** [comment]
@Comphix Thank you so much for your quickly help. I do tried run hello world as root too. it also failed. it should not be a permission issue. bear in mind, Linux kernel driver can be loaded well. 
Yes, you are correct probe is not called too. I may have time to debug more next day. but if you find the root cause. it is great that let me know.

**Comment by gwnet** [comment]
@Comphix May I know if you can reproduce this from your side?

**Comment by gwnet** [comment]
I feel highly possible fix is that make SPDK user mode driver support VMware device id and vendor id. 
it will be great that Intel friend can show me how to do it. I can submit this patch

**Comment by Comphix** [comment]
Maybe you can first try to modify the return of below function to see whether it could go forward.

int rte_pci_match(const struct rte_pci_driver *pci_drv, const struct rte_pci_device *pci_dev);

On the other hand, you could also have a try with below to allow any kind of Class ID as it seems SPDK allows any kind of vendor ID and any kind of device ID. Maybe the class ID for the VMware device is not correct.

<spdk_folder>/lib/env_dpdk/pci_nvme.c

static struct rte_pci_id nvme_pci_driver_id[] = {
	{
		.class_id = SPDK_PCI_CLASS_NVME,  >>>> change to 0xffffff
		.vendor_id = PCI_ANY_ID,
		.device_id = PCI_ANY_ID,
		.subsystem_vendor_id = PCI_ANY_ID,
		.subsystem_device_id = PCI_ANY_ID,
	},
	{ .vendor_id = 0, /* sentinel */ },
};

Rebuilt and run again.

Please let us know whether this works or not.

Thanks,
Gang

**Comment by gwnet** [comment]
buddy, it is my mistake. when device id is 7f0 that is vmware NVME device. the check logic is passed with match result. the code actually return here without call probe. 
rte_pci_map_device did not goes into VFIO map logic. I will check, if I need compile SPDK support VFIO.

	if (!already_probed && (dr->drv_flags & RTE_PCI_DRV_NEED_MAPPING)) {
		/* map resources for devices that use igb_uio */
                ret = rte_pci_map_device(dev);

		if (ret != 0) {
			dev->driver = NULL;
			return ret;
		}
	}

**Comment by gwnet** [comment]
buddy, from the picture below. 
the root cause is the deviceid 7f0 device, just vmware NVMe device. the dev's kdrv is assgined as RTE_KDRV_NONE. not RTE_KDRV_VFIO. so the real VFIO map logic is not called as expected. do you have any quick idea for this. 

![image](https://user-images.githubusercontent.com/7543276/52172349-84f2bb80-27a8-11e9-88ac-fd711a1ac54d.png)

**Comment by gwnet** [comment]
pretty close now. when scan the vmware nvme PCI device. the pci_get_kernel_driver_by_path return 0x1. this cause wrong dev kdrv value.
![image](https://user-images.githubusercontent.com/7543276/52173185-01da6100-27ba-11e9-9319-be4d994cc417.png)

**Comment by gwnet** [comment]
buddy, I force the code, make it run the IOMMU map, I found that my system is not true IOMMU ready. 
from dmesg, I cannot see IOMMU enabled log. vmware BIOS also does not have option to enable IOMMU. 
I guess this maybe the root cause. I will install vmware workstation 15 to have a try. if still not OK, I need talk with vmware guy.

**Comment by gwnet** [comment]
finally I can enable IOMMU well in VMware now. I miss one step, we need add intel_iommu=on into kernel boot parameter to enable it well. 
after IOMMU ready, if I use sudo to run hello world. it works well as below:
wayne@ubuntu:~/spdk/examples/nvme/hello_world$ sudo ./hello_world 
[sudo] password for wayne: 
hello from host OS ConsoleApplication1!
1
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk0 --proc-type=auto ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /var/run/dpdk/spdk0/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 15ad:7f0 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
EAL: Ignore mapping IO port bar(2)
Attaching to 0000:03:00.0
Attached to 0000:03:00.0
Using controller VMware Virtual NVMe  (VMWare NVME-0000    ) with 1 namespaces.
  Namespace ID: 1 size: 21GB
Initialization complete.
INFO: using host memory buffer for IO
Hello world!

===but if I run hello world still use non-root current user that I run setup.sh. 
wayne@ubuntu:~/spdk$ sudo DRIVER_OVERRIDE=vfio-pci TARGET_USER=wayne scripts/setup.sh
[sudo] password for wayne: 
0000:03:00.0 (15ad 07f0): nvme -> vfio-pci

wayne@ubuntu:~/spdk/examples/nvme/hello_world$ ./hello_world 
hello from host OS ConsoleApplication1!
1
Starting SPDK v19.01-pre / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk0 --proc-type=auto ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /run/user/1000/dpdk/spdk0/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: Cannot obtain physical addresses: Success. Only vfio will function.
error allocating rte services array
EAL: FATAL: rte_service_init() failed

EAL: rte_service_init() failed

Failed to initialize DPDK
Unable to initialize SPDK env

===summary====
so it is still one permission issue for VFIO/IOMMU mode. root user is OK, other user is not OK. it is great that Intel can document this more detail in the future. too many permission issues for non-root user

**Comment by Comphix** [comment]
Thanks @gwnet , do you mean that with "sudo" to run setup.sh and hello_world example, it can run successfully with the current non-root user?

**Comment by gwnet** [comment]
No, if I use sudo to run setup.sh, then use sudo to run nvme hello_world. it is OK. if I do not use non-root user(without sudo) to run nvme hello_world, it failed at rte_service_init.

**Comment by darsto** [comment]
SPDK can only run as root at the moment. There is an ongoing discussion here: https://github.com/spdk/spdk/issues/314

Since the original issue is fixed, I'm closing this.
