### ISSUE TITLE
SECONDARY perf instance stuck

### ISSUE THREAD

**Issue by gaolizhou** [spdk/spdk#644]
SECONDARY perf instance stuck. We have two instance of perf tool. One instance is PRIMARY, the other is SECONDARY. the primary works well, but secondary stuck.

## Expected Behavior

Both Perf instance should work well.
## Current Behavior

 the primary works well, but secondary stuck.

## Possible Solution

No Solution.
## Steps to Reproduce

1. open  two ssh sessions
2. run perf command on both ssh sessions on same time.
###ssh-1 
[root@fty-udisk-139-198 ~]# date && ./perf -i 20  -q 1 -o 4096 -w randread -r 'trtype:PCIe traddr:0000:3b:00.0' -t 10 
**Fri Feb  1 15:16:01 CST 2019**
Starting SPDK v18.10 / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf -c 0x1 --file-prefix=spdk20 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 48 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /var/run/dpdk/spdk20/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:3b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:3b:00.0
Attached to NVMe Controller at 0000:3b:00.0 [8086:0a54]
Associating INTEL SSDPE2KX080T8  (BTLJ833100FH8P0HGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                            Latency(us)
Device Information                                     :       IOPS       MB/s    Average        min        max
INTEL SSDPE2KX080T8  (BTLJ833100FH8P0HGN  ) from core 0:    7009.60      27.38     142.63      19.70   25983.76
========================================================
Total                                                  :    7009.60      27.38     142.63      19.70   25983.76

[root@fty-udisk-139-198 ~]# date
Fri Feb  1 15:16:16 CST 2019
[root@fty-udisk-139-198 ~]# 
[root@fty-udisk-139-198 ~]# 

###ssh-2
[root@fty-udisk-139-198 ~]# date && ./perf -i 20  -q 1 -o 4096 -w randread -r 'trtype:PCIe traddr:0000:3b:00.0' -t 10
**Fri Feb  1 15:16:02 CST 2019**
Starting SPDK v18.10 / DPDK 18.08.0 initialization...
[ DPDK EAL parameters: perf -c 0x1 --file-prefix=spdk20 --base-virtaddr=0x200000000000 --proc-type=auto ]
EAL: Detected 48 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Auto-detected process type: SECONDARY
EAL: Multi-process socket /var/run/dpdk/spdk20/mp_socket_48016_17234a802fb400
EAL: Probing VFIO support...
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: PCI device 0000:3b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
Attached to NVMe Controller at 0000:3b:00.0 [8086:0a54]
Associating INTEL SSDPE2KX080T8  (BTLJ833100FH8P0HGN  ) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0

=====stuck here, cannot go any further======

^C
[root@fty-udisk-139-198 ~]# date
Fri Feb  1 15:16:28 CST 2019
[root@fty-udisk-139-198 ~]# ./identify -i 0 -r 'trtype:PCIe traddr:0000:3b:00.0' 2>/dev/null | egrep "Model Number|Firmware Version"
Model Number:                          INTEL SSDPE2KX080T8
Firmware Version:                      VDV10131

[root@fty-udisk-139-198 ~]# 
[root@fty-udisk-139-198 ~]# 

## Context (Environment including OS version, SPDK version, etc.)

 SPDK v18.10 / DPDK 18.08.0 
Linux 4.14.0

**Comment by optimistyzy** [comment]
@gaolizhou Can you check the following commit id:  20f4a21d84053e147758a944f3da9d068233dfc0 in the master branch
It is merged recently. Then nvme-cli will not be running as a second process.

**Comment by Comphix** [comment]
Please have a try:

For the primary process (management process):
./example/nvme/nvme_manage -c 0x3 (two cores)

1st perf:
./perf -c 0x1 (use 1st core)

2st perf:
./perf -c 0x2 (use 2nd core)

**Comment by Comphix** [comment]
For more information, please refer to https://spdk.io/doc/nvme.html and search "Multi Process". Thanks.

**Comment by gaolizhou** [comment]
It works when perf are run on different cores. 
Thanks!
