### ISSUE TITLE
NVMe hotplug test occasionally fails with "Get registers failed while waiting for CSTS.RDY == 0"

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#646]
The NVMe hotplug test was disabled on master due to #542, but once enabled with https://review.gerrithub.io/c/spdk/spdk/+/437673/ it can occasionally fail with the following message printed over and over:

> nvme_ctrlr.c:1916:nvme_ctrlr_process_init: *ERROR*: Get registers failed while waiting for CSTS.RDY == 0

It finally it fails with:

> nvme_ctrlr.c:2163:nvme_ctrlr_process_init: *ERROR*: Initialization timed out in state 1
> nvme_ctrlr.c: 489:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:00:06.0 in failed state.
> nvme.c: 423:nvme_init_controllers: *ERROR*: Failed to initialize SSD: 0000:00:06.0
> nvme_ctrlr.c: 505:nvme_ctrlr_shutdown: *ERROR*: get_cc() failed
> spdk_nvme_probe() failed

Even if it's a timing issue inside the test script, the error message from SPDK shouldn't completely bloat the log.

Full log here (14M):

https://ci.spdk.io/spdk/builds/review/bd027358604b2f01c8000239f857b88147f53074.1548709786/fedora-03/build.log

**Comment by darsto** [comment]
Bug scrub: Try enabling a quirk that's usually enabled for physical Nvmes.

**Comment by darsto** [comment]
Bug scrub: @darsto to look into this deeper for 19.07

**Comment by darsto** [comment]
Bug scrub: It's likely caused by bugs inside emulated NVMes, for now we've got two solutions:
1) passthrough real NVMe to a VM, dynamically hotremove it via QEMU monitor cmds
2) try additional HW for simulating hotremove (?)

**Comment by Maciej-Szwed** [comment]
Introducing HW solution for hotremove tests: https://review.gerrithub.io/c/spdk/spdk/+/462470

**Comment by darsto** [comment]
Bug scrub: We've recently updated QEMU on our CI machines, it should be worth trying to run the same tests again now

**Comment by jimharris** [comment]
@Maciej-Szwed Do we have any update on this issue?  462470 was abandoned.

**Comment by jimharris** [comment]
@Maciej-Szwed - ping.

**Comment by tomzawadzki** [comment]
@Maciej-Szwed Tests in `./test/nvme/hw_hotplug.sh` are merged and look to be running daily on Jenkins. Can you confirm that this is correct and we've got coverage to issue here ?

**Comment by Maciej-Szwed** [comment]
Yes, hotplug test is running daily and I don't notice any fails currently. I think we can close this one. Sorry for late response - I missed a notification.
