### ISSUE TITLE
intermittent RBD test failure in Jenkins pool

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#647]
I've seen this issue on three patches this morning.  At least two of the failures were on fedora_vm_5 (don't remember the other patch so can't find the Jenkins job).

Good/normal log:
https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/21875/archive/RBD_autotest/build.log

Bad/failing log:
https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/21874/archive/RBD_autotest/build.log

Key sequence in failing log:
+ ceph-run sh -c 'ulimit -n 16384 && ulimit -c unlimited && exec ceph-mon -c /var/tmp/ceph/ceph.conf -i a --keyring=/var/tmp/ceph/keyring --pid-file=/var/tmp/ceph/pid/root@gklab-17-187.pid --mon-data=/var/tmp/ceph/mon.a/'
2019-02-04 13:07:17.015380 7fc01b4fb180 -1 error: monitor data filesystem reached concerning levels of available storage space (available: 4% 1.67GiB)
you may adjust 'mon data avail crit' to a lower value to make this go away (default: 5%)

+ true
+ i=0
+ mkdir -p /var/tmp/ceph/mnt
++ uuidgen
+ uuid=e75e6f1e-f7e2-453b-ab5e-f1ee5ea0da03
+ ceph -c /var/tmp/ceph/ceph.conf osd create e75e6f1e-f7e2-453b-ab5e-f1ee5ea0da03 0
2019-02-04 13:12:17.191000 7fd2fb909700  0 monclient(hunting): authenticate timed out after 300
2019-02-04 13:12:17.191050 7fd2fb909700  0 librados: client.admin authentication error (110) Connection timed out
[errno 110] error connecting to the cluster

**Comment by karlatec** [comment]
Freed some disk space on the VM's. Should be fine now.

**Comment by karlatec** [comment]
@nedved1 please monitor this when I'm out of office

**Comment by optimistyzy** [comment]
I had the same issue: https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22503/archive/unittest_autotests/build.log  It seems that the space of the test machine is not enough.
