### ISSUE TITLE
ISAL erroneously gets disabled during configure 

### ISSUE THREAD

**Issue by gila** [spdk/spdk#648]
When running configure on my VM (and some Travis CI VMs as well it seems) ISAL gets disabled when it really should not. 

## Expected Behavior
ISAL should be enabled

## Current Behavior
ISAL disabled

## Possible Solution
The docs of https://www.gnu.org/software/coreutils/manual/html_node/uname-invocation.html#uname-invocation mentioned that `uname -i` is not portable even across linux distro's and gives the wrong output (the vendor field) on my VM:

```bash
# uname -i
GenuineIntel
# uname -m
x86_64
```

`uname -m` is the same as `arch(1)` according to the docs but might not always be avaible. It seems then that `uname -m` is the best solution to use in stead of using `-i`.

## Steps to Reproduce
Using fusion 10 (OSX) -- with Gentoo:
```bash
# git submodule update --init
Submodule 'dpdk' (https://github.com/spdk/dpdk.git) registered for path 'dpdk'
Submodule 'intel-ipsec-mb' (https://github.com/spdk/intel-ipsec-mb.git) registered for path 'intel-ipsec-mb'
Submodule 'isa-l' (https://github.com/spdk/isa-l.git) registered for path 'isa-l'
Cloning into '/code/spdk/dpdk'...
Cloning into '/code/spdk/intel-ipsec-mb'...
Cloning into '/code/spdk/isa-l'...
Submodule path 'dpdk': checked out '754c3dbc347f9e446ce05f6f44f52a29e458e013'
Submodule path 'intel-ipsec-mb': checked out '134c90c912ea9376460e9d949bb1319a83a9d839'
Submodule path 'isa-l': checked out '09e787231b31add1234ec9a3dfe718533f1c3bf4'
devol /code/spdk # ./configure
Notice: ISAL auto-disabled due to CPU incompatiblity.
Using default SPDK env in /code/spdk/lib/env_dpdk
Using default DPDK in /code/spdk/dpdk/build
Creating mk/config.mk...done.
Type 'make' to build.
```

## Context (Environment including OS version, SPDK version, etc.)

1) Gentoo Linux so kinda hard to give an exact version but coreutils is version 8.30
2) Kernel linux 5.0-rc3
3) SPDK  c8d956fdeeb6dc38cfde698347dc5a569519e02b

**Comment by peluse** [comment]
Thanks for catching this!!! Would you be interested in pushing a patch to address this?

**Comment by peluse** [comment]
Also FYI ISA-L uses the -m option internally when checking the CPU arch so this is the right way to go

**Comment by jimharris** [comment]
I've already assigned @gila the bug.  ;-)  He indicated on IRC just now that he wanted to get up to speed on the patch submission process.

**Comment by peluse** [comment]
Yay!  Sorry, my IRC was off :( . Hey, what email thing are you referring to? By all means feel free to push a patch to clarify, thanks again!
