### ISSUE TITLE
nvme discovery shows trtype as "unrecognized" for TCP 

### ISSUE THREAD

**Issue by Ayyanar85** [spdk/spdk#649]
nvme discovery shows trtype as unrecognized for tcp transport

[root@Init ~]# nvme discover -t tcp -a 192.168.10.100 -s 8001

Discovery Log Number of Records 1, Generation counter 4
=====Discovery Log Entry 0======
trtype:  unrecognized
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 8001
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  192.168.10.100

[root@Init ~]# nvme connect -t tcp -a 192.168.10.100 -s 8001 -n nqn.2016-06.io.spdk:cnode1
[root@Init ~]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     SPDK00000000000001   SPDK bdev Controller                     1          13.82  GB /  13.82  GB    512   B +  0 B   19.04

[root@Target scripts]# ./rpc.py get_nvmf_subsystems
[
  {
    "nqn": "nqn.2014-08.org.nvmexpress.discovery",
    "subtype": "Discovery",
    "listen_addresses": [],
    "allow_any_host": true,
    "hosts": []
  },
  {
    "nqn": "nqn.2016-06.io.spdk:cnode1",
    "subtype": "NVMe",
    "listen_addresses": [
      {
        "transport": "TCP",
        "trtype": "TCP",
        "adrfam": "IPv4",
        "traddr": "192.168.10.100",
        "trsvcid": "8001"
      }
    ],
    "allow_any_host": true,
    "hosts": [
      {
        "nqn": "nqn.2016-06.io.spdk:init"
      }
    ],
    "serial_number": "SPDK00000000000001",
    "namespaces": [
      {
        "nsid": 1,
        "bdev_name": "Nvme0n1",
        "name": "Nvme0n1"
      }
    ]
  }
]

**Comment by jimharris** [comment]
Which version of nvme are you using - "nvme version"?

**Comment by jimharris** [comment]
Just to clarify - nvme-cli v1.7 added TCP support.  This was just released in January 2019.  Want to make sure that you're using a version of nvme-cli that will recognize the TCP trtype.

I've looked at the SPDK NVMe/TCP code and it looks like it's populating the trtype correctly.  I'm not set up at the moment to test nvme-cli with TCP but I (or someone) will take look if you are in fact using nvme v1.7 and seeing this problem.

Thanks,

-Jim

**Comment by Ayyanar85** [comment]
Hi Jim,

With latest 1.7 version, its working good...

[root@Init nvme-cli]# ./nvme discover -t tcp -a 192.168.10.100 -s 8001

Discovery Log Number of Records 1, Generation counter 4
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 8001
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  192.168.10.100
sectype: none
[root@Init nvme-cli]# ./nvme version
nvme version 1.7.18.g637b

Thanks. Closing this.
