### ISSUE TITLE
vhost: assertion failed when trying to run Windows VM with debug vhost

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#650]
## Current Behavior
Assertion error when attaching Windows VM to SPDK vhost controller.
```
vhost: vhost.c:231: spdk_vhost_vq_get_desc: Assertion `spdk_vhost_dev_has_feature(vsession, VIRTIO_RING_F_INDIRECT_DESC)' failed.
```
## Expected Behavior
Well... no assertion error.

## Steps to Reproduce
1. Compile SPDK with --enable-debug
2. Start SDPK Vhost
3. Create some simple vhost confiuration (SCSI controller with single Malloc bdev is enough)
4. Run a Windows VM which will attach to vhost-scsi controller
5. During VM boot vhost fails with assertion error:
```
vhost: vhost.c:231: spdk_vhost_vq_get_desc: Assertion `spdk_vhost_dev_has_feature(vsession, VIRTIO_RING_F_INDIRECT_DESC)' failed.
```
## Context (Environment including OS version, SPDK version, etc.)
SPDK 2446c5c6f3f4c061b0c1bf9d52739efe2a8a1525
Windows Server 2012 R2
Windows scsi & iostor driver versions unknown at this time.

**Comment by jimharris** [comment]
We may be able to update the drivers in our Windows test VMs, but this isn't always possible.  How does QEMU virtio backend, or kernel vhost, handle this?  Even if the spec says its forbidden, we need to follow what other virtio backends are doing.

**Comment by darsto** [comment]
Bug scrub: @changpe1 I'm just wondering, have you ever encountered this before? Is this something you've done work on already?

**Comment by changpe1** [comment]
@darsto , SPDK doesn't need to assert the VIRTIO_RING_F_INDIRECT_DESC, because SPDK can support this feature by default, just remove it is ok.
