### ISSUE TITLE
nvme: time spent in pending queue isn't included in ctrlr timeout mechanism

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#655]
Hi,

I find out the time that request spent in the pending queue isn't included in ctrlr timeout mechanism. 

For example, in nvme/pcie, if sq is full and there is no more free tracker, request is pended to `qpair->queued_req`, considered as a pending queue. And in the completion of another request, the request in `queued_req` is submitted and the `submit_tick` of request is recorded here. 

But the pending queue is a inner implementation detail and not seen by users. From the view of users, request has been submitted after calling `spdk_nvme_ns_cmd_write/read` api. In the worst case the request takes a long time waiting in pending queue, but ctrlr timeout mechanism still regards this request as a fresh new request,  which may be inconsistent with what users see.

```
int
nvme_pcie_qpair_submit_request(struct spdk_nvme_qpair *qpair, struct nvme_request *req)
{
       // ...
        tr = TAILQ_FIRST(&pqpair->free_tr);     
 
        if (tr == NULL || !pqpair->is_enabled) {
                // request is pended to pending queue
                STAILQ_INSERT_TAIL(&qpair->queued_req, req, stailq);
                goto exit;
        }
       // ...
```
I'd like to write a patch to modify this if I understand it correctly.

Lorne

**Comment by jimharris** [comment]
Hi @lorneli,

You are understanding this bug correctly.  It would be great if you could fix this up!

How do you think you'll handle the abort case?  For example, currently when a request times out, we pass the request's cid to the timeout_cb so the application could try to do an abort.  There will be no cid for a queued request though.

Maybe we define some kind of INVALID_CID value, and document that if the application gets one of these, it must escalate immediately to controller reset.

If you have other ideas on this I would be interested to hear them.

Thanks,

-Jim

**Comment by lorneli** [comment]
Hi @jimharris ,

For the abort case, I come up with a solution: Assign fake cid, distinguished from real cid in tracker, to the requests in pending list. Then return the fake cid in timeout callback. When user calls `spdk_nvme_ctrlr_cmd_abort` using fake cid, request with that cid could be found in pending list and be compeleted manually. But there exists one case that the request in pending list has been combined with a real cid and submitted to controller at the time of  calling `spdk_nvme_ctrlr_cmd_abort`. So a list (or map) is required to record the mapping <fake cid, read cid> and the request to be aborted could be found using this mapping.

My solution doesn't require the  additional involvement of user, but lead to much complexity, including management of fake cid and recording list. So I'm inclined to your solution.

> Maybe we define some kind of INVALID_CID value, and document that if the application gets one of these, it must escalate immediately to controller reset.

**Comment by jimharris** [comment]
That's an interesting idea.  But I agree that the extra complexity would be too much.  Also, spdk_nvme_ctrlr_cmd_abort currently always sends an abort request to the SSD - so we would be changing the behavior of that function and need to explain it.  I think if there is a case where even queued requests have timed out, aborts will do no good and user must reset.

Please break this up into multiple patches.  I think first patch should move all of the req->submit_task assignments into the generic request allocation code.  Currently it is somewhat duplicated in nvme_pcie.c, nvme_rdma.c and nvme_tcp.c.  This has a small side effect, that now timeout is calculate when request is allocated, not when it is submitted to the SSD.  But I think that's OK.  Second patch can add checking of the queued_req list.

**Comment by lorneli** [comment]
That's great, thanks for your kind guidance.

**Comment by lorneli** [comment]
Hi @jimharris, @optimistyzy ,

I find out in nvme/nvme_tcp.c function `nvme_tcp_qpair_process_completions` doesn't check the timeout of requests like similar functions in pcie/rdma do. I wonder if this feature is impelmented implicitly in nvme_tcp.c. 

Thanks.

**Comment by lorneli** [comment]
Hi @jimharris , @optimistyzy , 

I have submitted a patch series to gerrit: https://review.gerrithub.io/c/spdk/spdk/+/444702/
The first patch moves req->submit_task assignments to nvme_qpair_submit_request function in generic qpair code. The second patch checks timeout of pending request in nvme/pcie.

It would be great if you help to review this patch at your convenience. Thanks.

**Comment by optimistyzy** [comment]
a patch is added to suport timeout in nvme tcp

**Comment by lorneli** [comment]
@optimistyzy  Found it. https://review.gerrithub.io/c/spdk/spdk/+/444803  Thanks for the notification.

**Comment by optimistyzy** [comment]
@lorneli  My patch supporting the timeout in NVMe TCP host side is merged.

**Comment by lorneli** [comment]
@optimistyzy Received, I will modify the second patch to detect timeout for pending requests  in tcp/rdma.

**Comment by jimharris** [comment]
Patches have been merged.  Thanks for your work on this @lorneli!
