### ISSUE TITLE
Jenkins: machines clock out of sync

### ISSUE THREAD

**Issue by pawelwod** [spdk/spdk#656]
## Expected Behavior
All machines should have their clock set consitently (using ntp maybe?).

## Current Behavior
There is a clock skew that produce warning during build like:

```
  INSTALL-LIB librte_ethdev.a
make[6]: warning:  Clock skew detected.  Your build may be incomplete.
make[5]: warning:  Clock skew detected.  Your build may be incomplete.
== Build buildtools
== Build kernel
make[5]: Warning: File '/var/jenkins/workspace/Other_systems/ubuntu16_autotest/spdk/dpdk/mk/internal/rte.build-post.mk' has modification time 28507 s in the future
make[5]: Warning: File '/var/jenkins/workspace/Other_systems/ubuntu16_autotest/spdk/dpdk/mk/internal/rte.build-post.mk' has modification time 28507 s in the future
== Build buildtools/pmdinfogen
== Build kernel/linux

```

https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22288/archive/ubuntu16_autotest/build.log

## Possible Solution
none

## Steps to Reproduce
Push a patch

## Context (Environment including OS version, SPDK version, etc.)
N/A

**Comment by karlatec** [comment]
@pawelwod Please look for this issue for some time. I've set the time on most of the test servers properly (still struggling with 17.10, so you can still expect "clock skew" messages there)

**Comment by pawelwod** [comment]
Looks like clocks are in sync now. Closing.
