### ISSUE TITLE
Intermittent PMDK test failure - no space left on device

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#658]
https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22563/archive/nvml_autotest/build.log

**Comment by jimharris** [comment]
Failure on fedora_vm_4:

Started by upstream project "autotest-per-patch" build number 22563
originally caused by:
 Triggered by Gerrit: https://review.gerrithub.io/c/spdk/spdk/+/443843
[EnvInject] - Loading node environment variables.
Building remotely on fedora_vm_4 (SingleDiskVM VM) in workspace /var/jenkins/workspace/NVML_tests/nvml_autotest
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
provisioning config files...

Snippet from log file containing error:

===============================================================
 09:20:52	# echo 'Now running: create_pmem_pool_tc3'
Now running: create_pmem_pool_tc3
 09:20:52	# echo ===============================================================
===============================================================
 09:20:52	# pmem_clean_pool_file
 09:20:52	# local pool_file=/var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/test/pmem/pool_file
 09:20:52	# '[' -f /var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/test/pmem/pool_file ']'
 09:20:52	# /var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/scripts/rpc.py create_pmem_pool /var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/test/pmem/pool_file 256 512
bdev_pmem_rpc.c: 210:spdk_rpc_create_pmem_pool: *ERROR*: pmemblk_create() failed: posix_fallocate "/var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/test/pmem/pool_file", 268435456: No space left on device
Exception:
Got JSON-RPC error response
request:
{
  "jsonrpc": "2.0",
  "method": "create_pmem_pool",
  "id": 1,
  "params": {
    "pmem_file": "/var/jenkins/workspace/NVML_tests/nvml_autotest/spdk/test/pmem/pool_file",
    "num_blocks": 524288,
    "block_size": 512
  }
}
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}
 09:20:52	# error 'Failed to create pmem pool!'
 09:20:52	# local error_code=1
 09:20:52	# echo ===========
===========
 09:20:52	# echo -e 'ERROR: Failed to create pmem pool!'

**Comment by jimharris** [comment]
This hit again on the very next patch - also on fedora_vm_4:

https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/22564/archive/nvml_autotest/build.log

**Comment by karlatec** [comment]
Cleaned up some disk space on the VMs yesterday. If we don't hit the issue in the next couple of hours or a day then I think this can be closed.

**Comment by jimharris** [comment]
Let's just close it now.  We can reopen if necessary.  But I'm pretty confident this has been fixed.
