### ISSUE TITLE
SPDK discovery over tcp is failing with error. NVME TCP not available. Could you please specify the nvme-tcp module for ubunutu

### ISSUE THREAD

**Issue by revanbiradar2019** [spdk/spdk#662]
NVME cli 1.7 unable to discover or connect over tcp for SPDK 19.01 on ubuntu nodes

target commands

root@testubuntu:/home/ubuntu/spdk1901/spdk#  ./scripts/rpc.py construct_malloc_bdev -b Malloc0 512 512
Malloc0
root@testubuntu:/home/ubuntu/spdk1901/spdk#  ./scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
root@testubuntu:/home/ubuntu/spdk1901/spdk# ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
root@testubuntu:/home/ubuntu/spdk1901/spdk# ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp-a 10.201.40.64 -s 4420
usage: rpc.py nvmf_subsystem_add_listener [-h] -t TRTYPE -a TRADDR [-f ADRFAM]
                                          [-s TRSVCID]
                                          nqn
rpc.py nvmf_subsystem_add_listener: error: the following arguments are required: -a/--traddr
root@testubuntu:/home/ubuntu/spdk1901/spdk# ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.201.40.64 -s 4420
tcp.c: 760:spdk_nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.201.40.64 port 4420 ***
root@testubuntu:/home/ubuntu/spdk1901/spdk

Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

NVME discover should be succesfull

NVME discover is failing becasue of nvme-tcp module not available

## Steps to Reproduce

1.root@testubuntu:/home/ubuntu/spdk1901/spdk#  ./scripts/rpc.py construct_malloc_bdev -b Malloc0 512 512
Malloc0
root@testubuntu:/home/ubuntu/spdk1901/spdk#  ./scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
root@testubuntu:/home/ubuntu/spdk1901/spdk# ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
root@testubuntu:/home/ubuntu/spdk1901/spdk# ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp-a 10.201.40.64 -s 4420
usage: rpc.py nvmf_subsystem_add_listener [-h] -t TRTYPE -a TRADDR [-f ADRFAM]
                                          [-s TRSVCID]
                                          nqn
rpc.py nvmf_subsystem_add_listener: error: the following arguments are required: -a/--traddr
root@testubuntu:/home/ubuntu/spdk1901/spdk# ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 10.201.40.64 -s 4420
tcp.c: 760:spdk_nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.201.40.64 port 4420 ***
root@testubuntu:/home/ubuntu/spdk1901/spdk
2.
3.
4.

**Comment by jimharris** [comment]
Hi @revanbiradar2019,

This does not look like an SPDK bug.  You need to install a kernel which has nvme-tcp support.

Closing this issue since I don't see any issue with SPDK here.  If you have further questions, you can continue to comment on this issue.

-Jim

**Comment by optimistyzy** [comment]
@revanbiradar2019 It seems the kernel nvme tcp transport support is merged in linux master in January (may be this linux master commit id: 6b8f9159166545e576b2bc8a0c984beaeae9cc05)this year. So mostly likely, it is in linux kernel 5.0. You need to use the kernel version which supports this feature or back port  the code in your current kernel.

**Comment by cranechu** [comment]
Maybe you did not create the transport? 
`scripts/rpc.py nvmf_create_transport -t TCP -p 4`

**Comment by revanbiradar2019** [comment]
Hi all, I had created the spdk nvme transport at target side . Do I need to
create at intiator side too.please let me know
