### ISSUE TITLE
using fio_plugin with spdk hangs when doing fio-seq-read (128K)

### ISSUE THREAD

**Issue by nate12112** [spdk/spdk#665]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

using fio_plugin with spdk hangs when doing fio-seq-read

## Expected Behavior
The FIO should complete successfully just like spdk/examples/nvme/fio_plugin/example_config.fio
(Yes, I can get the example_config.fio to work just fine)

## Current Behavior
It hangs at **Jobs: 1 (f=1): [R(1)][99.9%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:02s]**
LD_PRELOAD=/home/jenkins/Desktop/Git/spdk/examples/nvme/fio_plugin/fio_plugin /home/jenkins/Desktop/Git/fio/fio /home/jenkins/Desktop/Git/fio/examples/fio-seq-read.job
file1: (g=0): rw=read, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=spdk, iodepth=32
fio-3.3
Starting 1 thread
Starting SPDK v19.04-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid22955 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
fio_plugin.c: 422:spdk_fio_setup: *ERROR*: Failed to find namespace 'ns=X'
file1: Laying out IO file (1 file / 10240MiB)
Jobs: 1 (f=1): [R(1)][99.9%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:02s]

## Possible Solution
Finish with data

## Steps to Reproduce
1. Clone, checkout, configure and make fio-3.3
Checkout fio-3.3
./configure 
make
2. Clone and setup SPDK
git clone https://github.com/spdk/spdk
cd spdk
git submodule update --init
./configure --with-fio=/path/to/fio/repo <other configuration options>
make
3. use the following config file to do a fio-seq-read (128K)
[global]
name=fio-seq-reads
filename=fio-seq-reads
group_reporting=1
thread=1
norandommap=1
randrepeat=0
do_verify=0
rw=read
bs=128K
ba=4k
direct=1
numjobs=1
log_avg_msec=1000
time_based=1
ramp_time=0
runtime=2

[file1]
size=20G
ioengine=/Desktop/Git/spdk/examples/nvme/fio_plugin/fio_plugin
iodepth=32
rwmixread=100
write_iops_log=/Desktop/Git/fio_output/SeqRd128k_QD1x32
write_lat_log=/Desktop/Git/fio_output/SeqRd128k_x32
write_bw_log=/Desktop/Git/fio_output/SeqRd128k_QD1x32
filename=trtype=PCIe traddr=0000.02.00.0 ns=1

4. Provide the following command line:
LD_PRELOAD=/Desktop/Git/spdk/examples/nvme/fio_plugin/fio_plugin /Desktop/Git/fio/fio /Desktop/Git/fio/examples/fio-seq-read.job

## Context (Environment including OS version, SPDK version, etc.)
Centos 7, fio-3.3, spdk (SHA e7121a262)

**Comment by optimistyzy** [comment]
@nate12112  I used the latest SPDK version, and did not see the issue you mentioned. My fio version used is (e8ed50bc3ce67f449714c55c3fbf2f8eb50730c2).  This is very strange 

:spdk_fio_setup: _ERROR_: Failed to find namespace 'ns=X'

**Comment by darsto** [comment]
Bug scrub: @pelplinski prepared a patch that might fix this. Can you check if it was included before e7121a2 ?

**Comment by pelplinski** [comment]
Patch [7a30221de](https://github.com/spdk/spdk/commit/7a30221de) is already merged before [e7121a2](https://github.com/spdk/spdk/commit/e7121a262f42f8fe1dc997fde2082fea2f8c5185). I guess it must be something different.

**Comment by jimharris** [comment]
Hi @nate12112 - I know we discussed this quite a bit on IRC.  Did you ever get a resolution?

**Comment by nate12112** [comment]
Yes, I had to modify my input fo files.

**Comment by jimharris** [comment]
Thanks @nate12112.  I'll close this issue then.
