### ISSUE TITLE
How to test on a particular NVMe device?

### ISSUE THREAD

**Issue by wangli1426** [spdk/spdk#672]
I have a machine with two NVMe SSD, say Intel P4500 and Intel P4600.
I'd like to have separate performance benchmark on the two devices, respectively.

How can I specify which NVMe device is used in /src/example/nvme/perf/perf tool?

or How can I specify which device will be mount to uio_pci_generic when I run /src/scripts/setup.sh ?

Any suggestion highly appreciated.

**Comment by Seth5141** [comment]
Hi @wangli1426,
When using setup.sh, you can set the environment variables PCI_WHITELIST or PCI_BLACKLIST with the BDF of the specific NVMe drives you want to test. (scripts/setup.sh -h for more info on that). For /example/nvme/perf/perf, you can also specify the transport ID (The PCI address for local NVMe) you would like to attach to  using the -r option.

**Comment by jimharris** [comment]
Closing this issue based on response from @Seth5141.

@wangli1426 - if you have additional questions, you can continue to post to this thread.
