### ISSUE TITLE
QEMU 2.11 can't connect to SPDK vhost. *ERROR*: Guest memory size is not a 2MB multiple

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#673]
## Expected Behavior
No error out. 

## Current Behavior

error messages are out.
```
VHOST_CONFIG: last_used_idx (0) and vq->used->idx (61440) mismatches; some packets maybe resent for Tx and dropped for Rx
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:0 file:32
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: last_used_idx (0) and vq->used->idx (61440) mismatches; some packets maybe resent for Tx and dropped for Rx
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:1 file:33
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:2 file:34
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: last_used_idx (0) and vq->used->idx (61440) mismatches; some packets maybe resent for Tx and dropped for Rx
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:3 file:35
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:0 file:36
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:1 file:26
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:2 file:27
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple
VHOST_CONFIG: /opt/APP/utility/spdk/SPDK_install/vhost0/naa.0.0: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:3 file:28
VHOST_CONFIG: virtio is now ready for processing.
vhost.c:1089:start_device: *ERROR*: vhost device 0: Guest memory size is not a 2MB multiple

```
## Steps to Reproduce
1. Set 1GB hugepage in the host machine. And run setup.sh with following parameters:

`HUGEMEM=32768 spdk-19.01/scripts/setup.sh
`
2. Run spdk vhost test scripts:

`spdk-19.01/test/vhost/spdk_vhost.sh --integrity-lvol-scsi
`
3. while running qemu, the error messages will be out.

## Context (Environment including OS version, SPDK version, etc.)
OS: Ubuntu 18.04.1 LTS  SPDK: 19.01 DPDK: 18.11

**Comment by pawelwod** [comment]
pls paste full logs from test

**Comment by karlatec** [comment]
Hi, please provide the version of used QEMU binary

**Comment by liang2yan** [comment]
The qemu version is as below:

```
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.9)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

**Comment by jimharris** [comment]
We definitely need the full logs.  Also confirm that on this same system, that using 2MB huge pages does *not* cause this failure.

It would also be good if this log message printed out the size.

**Comment by GaoliangL** [comment]
We still face the issue after changed the hugepage as 2MB.
Uploaded two log files with the hugepage configuration of 2MB and 1GB.

[spdk-vhost-lvol-scsi-pagesize2M.txt](https://github.com/spdk/spdk/files/2888571/spdk-vhost-lvol-scsi-pagesize2M.txt)
[spdk-vhost-lvol-scsi-pagesize1G.txt](https://github.com/spdk/spdk/files/2888573/spdk-vhost-lvol-scsi-pagesize1G.txt)

**Comment by karlatec** [comment]
@liang2yan You're using QEMU version which we don't support.
Please update to 2.12 or 3.0.0 from https://review.gerrithub.io/spdk/qemu

Thanks

**Comment by darsto** [comment]
This is either a bug or a security issue in older QEMU versions. Even if we mmaped just a part of a 2MB page and registered that part to the VFIO, the associated physical device could still do DMA to the entire page because IOMMU can only operate on whole pages. Then we could either read or write to memory we shouldn't have access to.

I'm also starting to wonder what actually happens when you mmap just a part of a page. How does that differ from mapping the page entirely? I can't find this described in the manuals.

We could technically try to round up the guest memory size to the nearest 2MB boundary, but this would be still a dirty hack to support broken QEMUs and it could potentially enable a broken vhost-user master to connect to an SPDK vhost slave in a couple of cases. We don't want that.

@liang2yan You should probably perform a QEMU update.

The 2MB limitation could be also dropped after we implement support for registering non-2MB-aligned memory in SPDK. Then we could simply get rid of the extra check that rejects your QEMU version. I think that's the only way to proceed here, but it won't happen anytime soon.

**Comment by jimharris** [comment]
Should the 2MB multiple check be looking at regions[i].mmap_size instead of regions[i].size?  

Clearly QEMU 2.11 is describing two memory regions, split by the VGA BIOS hole (0xA0000-0xBFFFF), making each of their sizes not 2MB multiple.  But the mmap sizes for both are 2MB aligned.  I'm pretty sure it's the latter we need to check.

**Comment by jimharris** [comment]
@liang2yan - could you modify lib/vhost/vhost.c on this system - line 1098, change "size" to "mmap_size".  Then see if the tests all pass?

**Comment by mhae** [comment]
@jimharris Changing to mmap_size works! I'm now getting past this error.

**Comment by jimharris** [comment]
Thanks @mhae!

Could you try one more experiment for me?  Launch QEMU again, but specify a memory size like 1023 or 1025, and do *not* allocate it from huge pages.  I just want to make sure that this vhost.c check still triggers in that case.

**Comment by mhae** [comment]
Yes, this fails:
kvm -enable-kvm -machine pc-i440fx-2.1,accel=kvm,usb=off -smp 1 -cpu SandyBridge -m 1023M -object memory-backend-file,id=mem,size=1023M,mem-path=/tmp/vm,share=on -numa node,memdev=mem -drive file=~/min.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=char0,path=/var/tmp/vhost.0 -device vhost-user-scsi-pci,id=scsi0,chardev=char0 --curses

But this fails as well:
mhae@mhae-z800:~/src/spdk$ sudo kvm -enable-kvm -machine pc-i440fx-2.1,accel=kvm,usb=off -smp 1 -cpu SandyBridge -m 1024M -object memory-backend-file,id=mem,size=1024M,mem-path=/tmp/vm,share=on -numa node,memdev=mem -drive file=~/min.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=char0,path=/var/tmp/vhost.0 -device vhost-user-scsi-pci,id=scsi0,chardev=char0 --curses
mhae@mhae-z800:~/src/spdk$ ls -l /tmp/vm
-rw-r--r-- 1 root root 1073741824 Feb 21 09:49 /tmp/vm
mhae@mhae-z800:~/src/spdk$ ls -lh /tmp/vm
-rw-r--r-- 1 root root 1.0G Feb 21 09:49 /tmp/vm

**Comment by jimharris** [comment]
Do both of them result in the "Guest memory size is not a 2MB multiple" error?

**Comment by mhae** [comment]
Yes.

**Comment by jimharris** [comment]
OK.  That's good actually.  I suspect the 1024 case (w/o huge pages) would get past this point but failure later on QEMU 2.12 or greater.

I'm curious what happens if you use huge pages, but try to specify 1023 or 1025MB?

Thanks @mhae for your help on this.

**Comment by mhae** [comment]
@jimharris Glad to be of help (-;

It seems that qemu is rounding it to the nearest 2MB multiple. I specified 1025 and it was rounded up to 1026M. 
```
mhae@mhae-z800:~/src/spdk$ sudo kvm -enable-kvm -machine pc-i440fx-2.1,accel=kvm,usb=off -smp 1 -cpu SandyBridge -m 1025M -object memory-backend-file,id=mem,size=1025M,mem-path=/dev/hugepages/vm,share=on -numa node,memdev=mem -drive file=~/min.qcow2,if=none,id=disk -device ide-hd,drive=disk,bootindex=0 -chardev socket,id=char0,path=/var/tmp/vhost.0 -device vhost-user-scsi-pci,id=scsi0,chardev=char0 --curses
mhae@mhae-z800:~/src/spdk$ ls -lh /dev/hugepages/vm
-rw-r--r-- 1 root root 1.1G Feb 21 09:58 /dev/hugepages/vm
mhae@mhae-z800:~/src/spdk$ ls -l /dev/hugepages/vm
-rw-r--r-- 1 root root 1075838976 Feb 21 09:58 /dev/hugepages/vm
```

**Comment by jimharris** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/445764

**Comment by jimharris** [comment]
Removing wont fix label.  This used to work before 19.01. I think 445764 fixes this so that at least vhost-scsi still works with QEMU 2.11.

**Comment by GaoliangL** [comment]
With QEMU 2.11, the issue is gone after applied the patch above.
