### ISSUE TITLE
setup.sh enhancements for running in Kubernetes pod

### ISSUE THREAD

**Issue by kreuzerkrieg** [spdk/spdk#675]
As discussed [here](https://github.com/spdk/spdk/issues/594) I'm opening Kubernetes pod enchancement request for `spdk/scripts/setup.sh`
1) Consider making it runnable in pods (actually docker instances) Today, setup.sh modprobes vfio/uio which is not (as far as I understand) supposed to work in contaner, `modprobe` should be run at host.
2) From the script, test `/sys` and `/dev` for r/w, these should be remounted with r/w in the pod
3) Test availability of hugepages in the pod.
4) It will be lovely to have the `setup.sh` running alone, without all the stuff surrounding it (not sure how it could be achieved, another repo?). At this moment I clone the whole `spdk` tree on the host just to run `pkgdep.sh` (which is overkill) just to get the `setup.sh` locally and get it running, since by default the host missing some basic stuff like `lspci`

**Comment by jaedan** [comment]
Would a second script designed to prepare a container for running SPDK make more sense? Loading vfio/uio and setting up hugepages is the primary purpose of setup.sh, and neither of those can be done within a container.

**Comment by benlwalker** [comment]
Would a second script designed to prepare a container for running SPDK make more sense? Loading vfio/uio and setting up hugepages is the primary purpose of setup.sh, and neither of those can be done within a container.

**Comment by kreuzerkrieg** [comment]
Not sure... At this moment I'm running `setup.sh` with `modprobe` lines commented out. Since I remount the `sysfs` as r/w I dont see how setting up huge pages preparation wouldnt run in container, except cases when hugepages disabled altogether on the host side. From my point of view what `setup.sh` does for me it is disconnecting drive from kernel and attaching to user mode and rescan. Not sure it deserves additional script, but up to you of course.

BTW, for the `setup.sh` to run properly looks like that only `pciutils` and `kmod` is needed, so no need to run the whole `pkgdep.sh`

**Comment by pawelwod** [comment]
We are open to enhancements but here I think that `setup.sh` is designed to aid development/testing rather than being full-featured tool. Anyway see my comments inline:

>     1. Consider making it runnable in pods (actually docker instances) Today, setup.sh modprobes vfio/uio which is not (as far as I understand) supposed to work in contaner, `modprobe` should be run at host.

We can check if module is loaded before modprobe/insmod but if it isn't and we can't `modprobe` it will fail anyway and SPDK won't work. This is quite easy to implement.
 
>     2. From the script, test `/sys` and `/dev` for r/w, these should be remounted with r/w in the pod

What is the purpose of running `setup.sh` when any of `/sys`, `/dev` or `/proc` is not `r/w` mounted?

>     3. Test availability of hugepages in the pod.

What do you mean "Test availability"? We try to allocate requested amount of huge page memory but it can fail (eg request 10G but only 9G is allocated). Right now we don't care about failures as there is nothing we can do with that.
 
>     4. It will be lovely to have the `setup.sh` running alone, without all the stuff surrounding it (not sure how it could be achieved, another repo?). At this moment I clone the whole `spdk` tree on the host just to run `pkgdep.sh` (which is overkill) just to get the `setup.sh` locally and get it running, since by default the host missing some basic stuff like `lspci`

You need only to checkout/download `scripts/setup.sh` and `scripts/common.sh`. If there is no `lspci` you can install it manually on host. Don't understand what is `all the stuff surrounding it`

**Comment by kreuzerkrieg** [comment]
> What is the purpose of running `setup.sh` when any of `/sys`, `/dev` or `/proc` is not `r/w` mounted?

As pod's end-user you are not always aware how it was configured, you dont remember what exactly should be writable. `setup.sh` does not complain about writability, it simply fails, and you spend some time trying to understand what `setup.sh` dont like about your pod
 
> What do you mean "Test availability"? We try to allocate requested amount of huge page memory but it can fail (eg request 10G but only 9G is allocated). Right now we don't care about failures as there is nothing we can do with that.

Will recheck how exactly it fails, AFAIR, it does not complains with straightforward message like, "Hey, no hugepages, cant continue"

> You need only to checkout/download `scripts/setup.sh` and `scripts/common.sh`. If there is no `lspci` you can install it manually on host. Don't understand what is `all the stuff surrounding it`

Correct, "all the stuff" seems to be only `pciutils` and `kmod` not big issue

**Comment by kreuzerkrieg** [comment]
> You need only to checkout/download `scripts/setup.sh` and `scripts/common.sh`.

and `/scripts/../include/spdk/pci_ids.h`?

**Comment by pawelwod** [comment]
> > You need only to checkout/download `scripts/setup.sh` and `scripts/common.sh`.
> 
> and `/scripts/../include/spdk/pci_ids.h`?

Ohh... yes. It will be problematic to skip this file as we want one place with PCI IDs.

> As pod's end-user you are not always aware how it was configured, you dont remember what exactly should be writable. `setup.sh` does not complain about writability, it simply fails, and you spend some time trying to understand what `setup.sh` dont like about your pod

> Will recheck how exactly it fails, AFAIR, it does not complains with straightforward message like, "Hey, no hugepages, cant continue"

One question (maybe lame question as I'm not containers expert here):
Why you need to invoke `setup.sh` in container at all? Shouldn't the environment be configured prior launching container (modules loaded, huge pages allocated, mounting points, devices)?

**Comment by kreuzerkrieg** [comment]
> One question (maybe lame question as I'm not containers expert here):
> Why you need to invoke `setup.sh` in container at all? Shouldn't the environment be configured prior launching container (modules loaded, huge pages allocated, mounting points, devices)?

Actually it could work this way, but we want more control over working with NVMe drives. No, you dont have to do everything in the node, except loading module with modprobe - you just cant run it from pod. after the module is loaded you can do the rest in the pod at run-time, for example you (for some reason) want to disconnect the drive from kernel and after that reconnect it back to kernel (`setup.sh reset`) or call for `setup.sh status`. Sure we can rip off parts of `setup.sh` and stitch it into our management tool, but except this, it will be nice to have working `setup.sh` in the pod, since if you actively developing with/debugging the SPDK NVMe Driver you dont want to ssh to the node each time you want to do something with the NVMe in the pod

**Comment by jimharris** [comment]
Is the request here to add some better error messages to setup.sh?  For example,

1) print useful error message if lspci not available
2) print useful error message if we need to insmod/lsmod/modprobe and its not available
3) print useful error message if /sys is not mounted r/w
4) print useful error message if we can allocate no huge pages
5) (maybe) print warning message if we can allocate some huge pages, but not as many as the user requested

Would this be "good enough"?

**Comment by kreuzerkrieg** [comment]
sounds like a plan

**Comment by benlwalker** [comment]
Yeah I think we can just check if the driver we want to probe is already loaded and skip that step if it is. These sound like good improvements overall.

**Comment by darsto** [comment]
Bug scrub: We generally use github to track issues. @kreuzerkrieg could you move this item to our Miscellaneous board on trello? That's where we keep the backlog. https://trello.com/b/ootiYU05/miscellaneous-backlog

I'm going to close this.

**Comment by kreuzerkrieg** [comment]
Logged in. Not sure how to add cards or whatever the name is to the board. Could you guide me or just move it to the backlog there?
