### ISSUE TITLE
Hello world show "nvme_ctrlr.c: 473:nvme_ctrlr_shutdown: *ERROR*: did not shutdown within 5 seconds"

### ISSUE THREAD

**Issue by Cindy-010** [spdk/spdk#676]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

version: v17.07.x
ubuntu 64bit 
Vmware workstation 

run hello world encounter below issues:
Starting DPDK 17.05.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --file-prefix=spdk0 --base-virtaddr=0x1000000000 --proc-type=auto ]
EAL: Detected 1 lcore(s)
EAL: Auto-detected process type: PRIMARY
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 15ad:7f0 spdk_nvme
Attaching to 0000:03:00.0
Attached to 0000:03:00.0
Using controller VMware Virtual NVMe  (VMWare NVME-0000    ) with 1 namespaces.
  Namespace ID: 1 size: 21GB
Initialization complete.
Hello world!
**nvme_ctrlr.c: 473:nvme_ctrlr_shutdown: *ERROR*: did not shutdown within 5 seconds**

## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
@Cindy-010 I see you are using a virtual NVMe controller, can you run with latest SPDK version ? SPDK will wait at least 10 seconds when shutting down the controller.

**Comment by Cindy-010** [comment]
@changpe1 Thank you for your comments. 
 yes, I try to using the latest SPDK version, wait 10000 milliseconds, hit the same issue.
[ DPDK EAL parameters: hello_world -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk0 --proc-type=auto ]
EAL: Detected 1 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Auto-detected process type: PRIMARY
EAL: Multi-process socket /var/run/dpdk/spdk0/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
Initializing NVMe Controllers
Attaching to 0000:03:00.0
Attached to 0000:03:00.0
Using controller VMware Virtual NVMe  (VMWare NVME-0000    ) with 1 namespaces.
  Namespace ID: 1 size: 21GB
Initialization complete.
INFO: using host memory buffer for IO
Hello world!
nvme_ctrlr.c: 554:nvme_ctrlr_shutdown: *ERROR*: did not shutdown within 10000 milliseconds

**Comment by changpe1** [comment]
@Cindy-010 Thanks for the quick update, then I think it's related with your virtual NVMe controller, SPDK follows the NVMe specification when shutting down the controller, but it's not a big deal because it's virtual controller.

**Comment by jimharris** [comment]
I agree with @changpe1 - this indicates a buggy NVMe implementation.  Can you confirm you're using the latest version of VMWare Workstation?

I've posted https://review.gerrithub.io/c/spdk/spdk/+/445942 which adds a quirk for this SSD.  It'll just print an extra ERRLOG indicating this timeout is somewhat expected on VMWare emulated SSDs.

**Comment by jimharris** [comment]
Patch has been merged.
