### ISSUE TITLE
virtio block hangs when connecting to vhost-user

### ISSUE THREAD

**Issue by vonnyfly** [spdk/spdk#683]
When I try to use Virtio Block as Vhost client.
I find when I write data to the virtio bdev, the IO will hang.
I use the latest master code of spdk.
I don't know if my usage is right.

## Expected Behavior
The bdev could complete IO.

## Current Behavior
The write operation will hang.

## Steps to Reproduce
```
app/vhost/vhost -S /var/tmp -m 0x3 --single-file-segments &

modprobe nbd
rpc_py=scripts/rpc.py
$rpc_py construct_malloc_bdev 512 4096 --name Malloc0
$rpc_py construct_vhost_blk_controller --cpumask 0x1 vhost.0 Malloc0

$rpc_py construct_virtio_dev --dev-type blk --trtype user --traddr /var/tmp/vhost.0 --vq-count 2 --vq-size 512 VirtioBlk0
$rpc_py get_bdevs
$rpc_py start_nbd_disk VirtioBlk0  /dev/nbd0

echo "xxx" > /dev/nbd0 # hangs

parted -s /dev/nbd0 mklabel gpt                                                                               
^C^C^CError: Input/output error during read on /dev/nbd0
Error: Input/output error during read on /dev/nbd0
Warning: Error fsyncing/closing /dev/nbd0: Input/output error
```

## Context (Environment including OS version, SPDK version, etc.)
```
 $ uname -a                                                                                                                                             
Linux kvm 4.19.2-1.el7.elrepo.x86_64 #1 SMP Tue Nov 13 16:18:09 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

SPDK: the latest code of master branch
* 954728e9d - (HEAD -> master, origin/master, origin/HEAD) build: Support PGO on clang. (3 days ago) <Ben Walker>
* 5a670e8e7 - detect_cc: Handle empty arguments (3 days ago) <Ben Walker>
* 8bbf0391f - event: Change the base to 0 when calling strtol (4 days ago) <Ziye Yang>
* fdcd8b708 - setup.sh: use pci_dev_echo in linux_unbind_driver (4 days ago) <Pawel Wodkowski>
* d8cf37d01 - doc/nvmf_tracing: fix a typo (4 days ago) <Rami Rosen>
```

**Comment by jimharris** [comment]
This is related to doing the vhost/virtio in loopback mode.  This works fine if we construct_virtio_dev in a separate SPDK process.

For example:
Start vhost process as described above, including construct_malloc_bdev and construct_vhost_blk_controller
test/app/bdev_svc/bdev_svc -r /var/tmp/svc.sock --single-file-segments &
scripts/rpc.py -s /var/tmp/svc.sock construct_virtio_dev --dev-type blk --trtype user --traddr /var/tmp/vhost.0 --vq-count 2 --vq-size 512 VirtioBlk0
scripts/rpc.py -s /var/tmp/svc.sock start_nbd_disk VirtioBlk0  /dev/nbd0

**Comment by jimharris** [comment]
Marking this is a bug, but low priority.  Loopback is not the best usage model for vhost/virtio - typical usage model would have a separate process attaching to the vhost process.

**Comment by darsto** [comment]
Bug scrub: I wonder if we should reprioritize it in order to add new fuzz tests - we could run a fuzzer to send I/O to the same app that handles it. @Seth5141 ?

**Comment by jimharris** [comment]
Closing this is a use case that is not supported.  vhost client and vhost target must be separate processes.
