### ISSUE TITLE
SPDK hit crash with SIGABRT spdk_lvs_init_cb assertion bs==Null failed error message when try to create LVS from NVMe bdev

### ISSUE THREAD

**Issue by rajasekaranmam** [spdk/spdk#685]
When trying to create LVS from NVMe bdev, SPDK crash with this error message (SIGABRT spdk_lvs_init_cb assertion bs==Null).
This is an intermittent issue and reproduced almost every time (Only once, it works fine).

## Expected Behavior
LVS creation should be successful

## Current Behavior
nvmf_tgt: lvol.c:536: _spdk_lvs_init_cb: Assertion `bs == NULL' failed.
Thread 1 "reactor_0" received signal SIGABRT, Aborted.
0x00007ffff69d6428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb)

## Steps to Reproduce
1. Enable hot-plug in a config file, also add relevant NVMe SSD DBDF numbers to construct NVMe devices while start nvmf_tgt (all other parameters not used including subsystem creation).
2. vfio-pcie modules added in OS then run setup.sh, ensure NVMe SSDs moved to userspace by vfio.
3. Run nvmf_tgt with GDB (In this sequence order, "gdb ./app/nvmf_tgt/nvmf_tgt", "handle SIGBUS noprint nostop pass" then "r -m 0xff".
4. NVMe bdev shows up without any issue (confirmed by using get_bdevs RPC call).
5. When try to create LVS from one of the NVMe bdev, nvmf_tgt crashed with the above-mentioned error message.
6. Re-tested from step#1 to 5, after did dd on NVMe SSDs but still hit this issue.

## Context (Environment including OS version, SPDK version, etc.)
16.04.5 LTS (Xenial   Xerus)
4.15.0-38-generic
MLNX_OFED_LINUX-4.5-1.0.1.0
Community SPDK 19.01 with VFIO (vfio-pcie)
2 number of NVMe DC P4800X Optane 375GB  SSDPE21K375GA

**PS** I quickly checked all open & close issues and did not find a similar one hence raised this issue.
If you see any similar issue addressed already then please duplicate or add a reference here.

**Comment by rajasekaranmam** [comment]
![sigbart assertion bs null while pull nvme bdev in 19 01 with sigbus handle switch](https://user-images.githubusercontent.com/18207076/53235971-2474e100-36b9-11e9-98de-921080a3f41a.jpg)

**Comment by jimharris** [comment]
Is this NVMe SSD locked by chance?  Status 02/86 ACCESS DENIED means this according to the spec:

Access to the namespace and/or LBA range is denied due to lack of access rights. Refer to the appropriate security specification (e.g., TCG SIIS).

Are you able to read and write to this SSD using the kernel NVMe driver?

There's still a problem here since bs does not equal NULL.  Looking into that further.

**Comment by jimharris** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/445941 will fix the assert.  It has no bearing on the NVMe error - this only satisfies the assertion, so that you'll get a meaningful error from the lvol layer that the lvs creation failed.

**Comment by jimharris** [comment]
Removing bug scrub label - further progress depends on info about using this device with the kernel driver.

**Comment by rajasekaranmam** [comment]
Same setup is not available to re-test this issue, will find a similar one (with secure capable SSD) then retry the suggested steps by @jimharris
