### ISSUE TITLE
SPDK Target prints *NOTICE*: ACCESS DENIED (02/86) and *ERROR*: Gpt: bdev=Nvme1n1 io error status=0 when bring up nvmf_tgt

### ISSUE THREAD

**Issue by rajasekaranmam** [spdk/spdk#686]
SPDK Target prints below ACCESS DENIED and ERROR when bring up nvmf_tgt with a config file (Both hot-plug enable & NVMe SSDs DBDF added).
nvme_qpair.c: 306: nvme_qpair_print_completion: *NOTICE*: ACCESS DENIED (02/86) sqid:1 cid:191 cdw0:0 sqhd:0001 p:1 m:0 dnr:1
vbdev_gpt.c: 410:spdk_gpt_bdev_complete: *ERROR*: Gpt: bdev=Nvme1n1 io error status=0
The above prints observed for both NVMe SSDs (both are same model SSDs).

## Expected Behavior
ACCESS DENIED & ERROR print not expected against NVMe Bdevs

## Current Behavior
Currently 19.01 & 19.01-pre SPDK throws these prints (ACCESS DENIED & ERROR)

## Steps to Reproduce
1. Enable hot-plug in a config file, also add relevant NVMe SSD DBDF numbers to construct NVMe devices while start nvmf_tgt (all other parameters not used including subsystem creation).
2. vfio-pcie modules added in OS then run setup.sh, ensure NVMe SSDs moved to userspace by vfio.
3. Run nvmf_tgt with -c config file & -m 0xff.
4. NVMe bdev shows up without any issue (confirmed by using get_bdevs RPC call).

## Context (Environment including OS version, SPDK version, etc.)
16.04.5 LTS (Xenial Xerus)
4.15.0-38-generic
MLNX_OFED_LINUX-4.5-1.0.1.0
Community SPDK 19.01 with VFIO (vfio-pcie)
2 number of NVMe DC P4800X Optane 375GB SSDPE21K375GA

**Comment by rajasekaranmam** [comment]
![access denied 02 86 print from spdk 19 01__also found in 19 04-pre__community](https://user-images.githubusercontent.com/18207076/53239397-efb95780-36c1-11e9-8343-11450317f2fc.jpg)

**Comment by jimharris** [comment]
Related to #685.

Please confirm that you can do I/O operations to this SSD using the Linux kernel driver.

**Comment by rajasekaranmam** [comment]
Same setup is not available to re-test this issue, will find a similar one (with secure capable SSD) then retry the suggested steps by @jimharris

**Comment by rajasekaranmam** [comment]
@jimharris @darsto Checked in another setup with same drive model, it works fine.

**Comment by jimharris** [comment]
Thanks @rajasekaranmam - does this mean we can close this issue?

**Comment by rajasekaranmam** [comment]
@jimharris Yes, please...Thanks for looking into this issue.
