### ISSUE TITLE
question about the way nvme driver encapsulates the specific transport

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#688]
Hi,

I have a programming  question about the way nvme driver encapsulates specific transport. In lib/nvme/nvme_transport.c, a macro `NVME_TRANSPORT_CALL` is used to switch transport type and add the prefix of specific transport. So the funciton like `nvme_transport_qpair_submit_request` could call `nvme_pcie_qpair_submit_request`/`nvme_rdma_qpair_submit_request`/`nvme_tcp_qpair_submit_request` based on the transport type.

```
#define TRANSPORT_PCIE(func_name, args) case SPDK_NVME_TRANSPORT_PCIE: return nvme_pcie_ ## func_name args;

#define NVME_TRANSPORT_CALL(trtype, func_name, args)            \                  
        do {                                                    \                  
                switch (trtype) {                               \                  
                TRANSPORT_PCIE(func_name, args)                 \                  
                TRANSPORT_FABRICS_RDMA(func_name, args)         \                  
                TRANSPORT_FABRICS_FC(func_name, args)           \                  
                TRANSPORT_FABRICS_TCP(func_name, args)          \                  
                TRANSPORT_DEFAULT(trtype)                       \                  
                }                                               \                  
                SPDK_UNREACHABLE();                             \                  
        } while (0)                                              
```

I think this encapsulation works quite well, but I'm a little curious about why the common-used function table structure, like `spdk_bdev_fn_table` or `spdk_bdev_module` , is not adopted here.  A function table `nvme_tranpsort_fn_table` coud be defined, and each transport implements the function prototype defined in that table.

Thanks in advance.

Lorne

**Comment by optimistyzy** [comment]
@lorneli  You need to implement the defined function in /lib/nvme/nvme_transport.c.  For others, you need to implement the functions defined in the "**table". From my understanding, it is just an implementation difference.

**Comment by lorneli** [comment]
@optimistyzy 

Hi Ziye,

I think it's just an implementation difference as well. Ask in case I miss something. Thanks for your reply!
