### ISSUE TITLE
What is the application scenario of spdk? Or what functions can be implemented based on spdk? For example, I use Nginx to do reverse proxy throughput in Linux kernel mode to reach 8Gbit. Can I combine Nginx and spdk? Need to implement the protocol stack myself? Looking forward to your guidance, thank you!

### ISSUE THREAD

**Issue by ygm521** [spdk/spdk#689]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by optimistyzy** [comment]
SPDK library is mainly used to  accelerate the storage I/O on fast storage devices (e.g., NVMe SSDs,  AEP and etc). If you only want to ngnix with user TCP/IP stack, you may use ngnix + user space TCP/IP(e.g., VPP, mtcp) + DPDK.  Until you want to put some data on the storage device via ngnix, you may use SPDK.  

By the way, SPDK has encapsulated sock API which can encapsules both posix and VPP TCP stack, you may also add your own but you need to implement the API function table defined by API.

**Comment by jimharris** [comment]
Hi @ygm521.  Closing this issue since @optimistyzy provided you an answer.  Feel free to ask more questions on this issue if necessary, even after it is closed.  Thanks.
