### ISSUE TITLE
example/nvme/hotplug fails if the driver is  vfio-pci 

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#690]
Use the vfio-pci to test  nvme hotplug case, when we remove the device the program endlessly print.

program log:
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!
EAL: Unexpected device scan at /sys/bus/pci/devices/0000:86:00.0/driver!

dmesg:
[  362.035263] vfio-pci 0000:86:00.0: Relaying device request to user (#0)
[  464.352053] vfio-pci 0000:86:00.0: Relaying device request to user (#10)
[  566.752058] vfio-pci 0000:86:00.0: Relaying device request to user (#20)
[  669.152061] vfio-pci 0000:86:00.0: Relaying device request to user (#30)
[  771.552067] vfio-pci 0000:86:00.0: Relaying device request to user (#40)
[  855.109430] vfio-pci 0000:86:00.0: Device is currently in use, task "test.sh" (3508) blocked until device is released

## Expected Behavior
can handle the device hotplug

## Current Behavior
2,endless print
3,can not use ctrl + c to exit the program

## Possible Solution
add the vfio-pci hotplug support, it seems the spdk can not handle vfio-pci hotplug.

## Steps to Reproduce

1. set intel_iommu=on
2. DRIVER_OVERRIDE=vfio-pci ./script/setup.sh
3. examples/nvme/hotplug/hotplug -n 5 -r 5 -t 600
4. ./test.sh

test.sh:
#! /bin/bash
for qwe in $(seq 1 10); do
        echo 1 >  /sys/bus/pci/devices/0000\:86\:00.0/remove
        echo "removed the device"
        sleep 10
        echo 1 > /sys/bus/pci/rescan
        DERIVER_OVERRIDE=vfio-pci ./scripts/setup.sh
        sleep 6
done

## Context (Environment including OS version, SPDK version, etc.)

system: Fedora release 28 
kernel: 4.16.3-301.fc28.x86_64
SPDK: commit 120825c91c2e8d55f5f258394222340062c7dafa (master)  version 19.01

**Comment by darsto** [comment]
This was unfortunately never supported in SPDK, please see here https://github.com/spdk/spdk/issues/595#issuecomment-457138189

**Comment by jimharris** [comment]
test.sh script also has a typo - should be DRIVER_OVERRIDE

**Comment by glodfish-zg** [comment]
push https://review.gerrithub.io/c/spdk/spdk/+/447410  to solve vfio-pci hotplug.
Will continue to pay attention to this issue and update.
