### ISSUE TITLE
vhost_initiator_autotest apparent latent failure

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#694]
## Expected Behavior
This test passes regularly.
## Current Behavior
I observed this test fail three times in a row on changes that didn't appear to touch vhost. Two of them are in the same patch series, but the third is not.
I think these failures may be indicative of a latent failure in the test pool.
## Possible Solution
Not sure yet

## Steps to Reproduce
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_24137.html
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_24136.html
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_24135.html
https://ci.spdk.io/spdk-jenkins/public_build/autotest-per-patch_24133.html

## Context (Environment including OS version, SPDK version, etc.)
Jenkins Test Pool

**Comment by darsto** [comment]
"Storage object ramdisk/ramdisk exists"

The test seems to fail on the following line:
`targetcli "/backstores/$targetcli_rd_name create name=ramdisk size=1GB"`
test/vhost/initiator/blockdev.sh:131

It seems like we don't delete that ramdisk in any trap. There is a handy function to do it, but it's only called at the end of the test:
`remove_kernel_vhost`

**Comment by pawelkax** [comment]
@darsto Patch that should fix this issue https://review.gerrithub.io/#/c/450022/
