### ISSUE TITLE
IOs on the base LVOL having snapshot/clone results in an assert

### ISSUE THREAD

**Issue by SavanAnjaria** [spdk/spdk#698]
When we have created snapshot/clone out of an LVOL and run IOs (Writes specifically) on that base LVOL, it results into an assert
nvmf_tgt: blobstore.c:128: _spdk_bs_release_cluster: Assertion `spdk_bit_array_get(bs->used_clusters, cluster_num) ==                                                                                                                         1' failed.

I have got the solution for this issue and going to raise a Gerrit review for the same as well. So, please assign this issue to me.

## Expected Behavior
IOs on the base LVOL should have gone through

## Current Behavior
Writes on a thin provisioned lvol having snapshot/clone created out of that results in an assert
nvmf_tgt: blobstore.c:128: _spdk_bs_release_cluster: Assertion `spdk_bit_array_get(bs->used_clusters, cluster_num) ==                                                                                                                         1' failed.

## Possible Solution
Restricting double freeing of a cluster in _spdk_blob_insert_cluster_cpl when it's called with an error.

## Steps to Reproduce
**On the target side**
1. Start SPDK
2. Create NVMe Bdevs
3. Create LVS on one of the Bdevs
4. Create LVOL on the LVS created
5. Create Snapshot of the LVOL created
6. Create Clone of the Snapshot created
7. Create NVMf subsystem and add the base LVOL created above to the subsystem

**On the initiator side**
1. Discover the LVOL created
2. NVMe connect to the LVOL
3. Run fio with following fio config
[global]
bs=4k
iodepth=4
direct=1
ioengine=libaio
numjobs=4
randrepeat=0
group_reporting
time_based
runtime=60
filesize=20G

[job1]
rw=write
filename=/dev/nvme0n1

## Context (Environment including OS version, SPDK version, etc.)
For both initiator and target
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CentOS Linux release 7.6.1810 (Core)

**Comment by jimharris** [comment]
Hi @SavanAnjaria - please post a link to the GerritHub review here once it's ready.  Thanks!
