### ISSUE TITLE
setup.sh ERROR: requested 4096 hugepages but only 3738 could be allocated.

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#702]
This happens occasionally on our CI and fails the test:

```
# ./scripts/setup.sh
## ERROR: requested 4096 hugepages but only 3738 could be allocated.
## Memory might be heavily fragmented. Please try flushing the system cache, or reboot the machine.
```

**Comment by darsto** [comment]
Bug scrub: one way to fix this would be allocating hugepages at boot.

@karlatec has a patch out to decrease overall hugepage requirements. We'll continue this topic after it's merged.

**Comment by karlatec** [comment]
@nedved1 Could you please update grub options on the VMs to allocate hugepages at boot time? Thanks

**Comment by nedved1** [comment]
@darsto @karlatec VMs I've set 4096 HP on boot on Jenkins VMs.

**Comment by karlatec** [comment]
@darsto please observe if hugepage issue shows up. If nothing happens until Monday 25th March then let's close the issue.

**Comment by karlatec** [comment]
@darsto 
Can this be closed?

**Comment by darsto** [comment]
@nedved1 Thank you!

**Comment by ksztyber** [comment]
I think I've just hit this issue on lvol_autotest:

 17:59:31	# ./scripts/setup.sh
0000:00:09.0 (8086 5845): Skipping un-whitelisted NVMe controller nvme0n1
0000:00:0c.0 (1d1d 1f1f): nvme -> pci-stub
0000:00:0b.0 (1af4 1001): Skipping un-whitelisted Virtio device at 0000:00:0b.0
0000:00:0a.0 (1af4 1004): Skipping un-whitelisted Virtio device at 0000:00:0a.0

## ERROR: requested 4096 hugepages but only 4043 could be allocated.
## Memory might be heavily fragmented. Please try flushing the system cache, or reboot the machine.
  17:59:32	# trap - ERR
  17:59:32	# print_backtrace
  17:59:32	# [[ ehxBE =~ e ]]
  17:59:32	# local shell_options=ehxBE
  17:59:32	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/Lvol_tests/lvol_autotest/spdk/autotest.sh:91 -> main()
     ...
   86  	
   87  		# Now, bind blacklisted devices to pci-stub module. This will prevent
   88  		# automatic grabbing these devices when we add device/vendor ID to
   89  		# proper driver.
   90  		if [[ -n "$PCI_BLACKLIST" ]]; then
=> 91  			PCI_WHITELIST="$PCI_BLACKLIST" \
   92  			PCI_BLACKLIST="" \
   93  			DRIVER_OVERRIDE="pci-stub" \
   94  				./scripts/setup.sh
   95  	
   96  			# Export our blacklist so it will take effect during next setup.sh
     ...
[build.log](https://github.com/spdk/spdk/files/3009468/build.log)

**Comment by karlatec** [comment]
@ksztyber I think you were unfortunate to get in queue just after my commit where I tested running tests with less amount of hugepages. We do not reboot VMs after a successful test (well, FreeBSD being an exception) so tests for your patch had to reallocate what my patch freed.

Please observe if this shows up again. If we don't see the issue again today then I think we can close this.

**Comment by ksztyber** [comment]
@karlatec Probably, always unlucky... ;-) I'll keep an eye on it and will close it if it doesn't happen again today.

**Comment by ksztyber** [comment]
Didn't happen again, so @karlatec was right.

**Comment by jimharris** [comment]
Of course @karlatec was right!  Was there ever any doubt?  :-)
