### ISSUE TITLE
construct_ftl_bdev not found in the results of get_rpc_methods.

### ISSUE THREAD

**Issue by zy-tough** [spdk/spdk#703]
When I tried to create an FTL bdev via RPC based on a real open-channel SSD, _$scripts/rpc.py construct_ftl_bdev ..._ shows "Method not found".

Not that the OCSSD has been successfully identified via _$examples/nvme/identify/identify_.
## Expected Behavior
$scripts/rpc.py construct_ftl_bdev ...: the name and uuid of the FTL bdev should be shown.
$scripts/rpc.py get_rpc_methods: the results should include "construct_ftl_bdev".
## Current Behavior
$scripts/rpc.py construct_ftl_bdev ...:
Exception:
Got JSON-RPC error response
request:
{
  "method": "construct_ftl_bdev",
  ...
}
response:
{
  "message": "Method not found",
  "code": -32601
}

$scripts/rpc.py get_rpc_methods | grep ftl:
(nothing is shown)
## Steps to Reproduce
1. $scripts/rpc.py construct_ftl_bdev ...
2. $scripts/rpc.py get_rpc_methods | grep ftl

## Context (Environment including OS version, SPDK version, etc.)

_$examples/nvme/identify/identify_ shows the information of nvme controller.

**Comment by jimharris** [comment]
Can you confirm that you've passed --with-ftl when running configure?  By default, the SPDK ftl module is disabled.

**Comment by zy-tough** [comment]
> Can you confirm that you've passed --with-ftl when running configure? By default, the SPDK ftl module is disabled.

I re-tried to configure SPDK with --with-ftl and the problem has been solved (FTL methods are found now). Thank you very much!

**Comment by optimistyzy** [comment]
According to @zy-tough 's comments, this issue is solved, so close it.
