### ISSUE TITLE
there‘re memory leaks  when use  muti-porcess to run perf cases with tcp transport

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#706]
when I verfiy multi-process cases with tcp transport.
ctrl+c to kill targets or initiators there're memory leaks report with asan enabled.

## Expected Behavior
exit without obvious error.
## Current Behavior
LeakSanitizer: detected memory leaks

## Steps to Reproduce
1. target scripts:
#!/usr/bin/env bash
                cd /home/spdk
                ./configure --enable-debug --enable-asan
                make clean && make -j
                ./scripts/setup.sh cleanup
                NRHUGE=16384 ./scripts/setup.sh
                ./app/nvmf_tgt/nvmf_tgt -c nvmf-tcp.conf.in &

config: Type TCP
2. initiator scripts:
#!/usr/bin/env bash
/home/spdk/examples/nvme/perf/perf -r  'trtype:TCP  adrfam:IPv4 traddr:192.168.4.11 trsvcid:4420' -s 1024 -q 128 -o 4096 -w randrw -M 50 -t 10 -c 0x2 &
sleep 1
/home/spdk/examples/nvme/perf/perf -r  'trtype:TCP adrfam:IPv4 traddr:192.168.4.11 trsvcid:4420' -s 1024 -q 128 -o 4096 -w randrw -M 50 -t 10 -c 0x4 &
sleep 1
/home/spdk/examples/nvme/perf/perf -r  'trtype:TCP adrfam:IPv4 traddr:192.168.4.11 trsvcid:4420' -s 1024 -q 128 -o 4096 -w randrw -M 50 -t 10 -c 0x6 &
3.  run this in a script:
1. setup target.
2.  setup initiator
 or  use python scripts to run
/home/spdk/examples/nvme/perf/perf -r 'trtype:%s adrfam:IPv4 traddr:192.168.4.11 trsvcid:4420' -s 1024 -q 128 -o 4096 -w randrw -M 50 -t 10 -c 0x%x & " %(trtype_s,i)
kill initiators.
there're memory leaks report after killing them using ctrl+C.
Starting SPDK v19.04-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x2 -m 1024 --no-pci --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid1589775 ]
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.4.11:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.4.11:4420: nqn.2016-06.io.spdk:cnode1
controller IO queue size 128 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
WARNING: Some requested NVMe devices were skipped
Associating SPDK bdev Controller (SPDK00000000000001  ) with lcore 1
Initialization complete. Launching workers.
Starting thread on core 1
8
Starting SPDK v19.04-pre / DPDK 18.11.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x4 -m 1024 --no-pci --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid1589779 ]
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.4.11:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.4.11:4420: nqn.2016-06.io.spdk:cnode1
controller IO queue size 128 less than required
Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.
WARNING: Some requested NVMe devices were skipped
Associating SPDK bdev Controller (SPDK00000000000001  ) with lcore 2
Initialization complete. Launching workers.
Starting thread on core 2
^C
nvme_tcp.c:1630:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (11): Resource temporarily unavailable
NVMe io qpair process completion error
nvme_tcp.c:1630:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (11): Resource temporarily unavailable
NVMe io qpair process completion error
[root@waikikibeach45 mutiprocess-testing]# nvme_tcp.c:1630:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (11): Resource temporarily unavailable
NVMe io qpair process completion error
nvme_tcp.c:1630:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (11): Resource temporarily unavailable

=================================================================
==1589779==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 19456 byte(s) in 128 object(s) allocated from:
    #0 0x7f790aa8fe50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x40971d in allocate_task /home/yidong/spdk/examples/nvme/perf/perf.c:888
    #2 0x40986a in submit_io /home/yidong/spdk/examples/nvme/perf/perf.c:907
    #3 0x409b09 in work_fn /home/yidong/spdk/examples/nvme/perf/perf.c:949
    #4 0x40dfd7 in main /home/yidong/spdk/examples/nvme/perf/perf.c:1914
    #5 0x7f790953924a in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 19456 byte(s) leaked in 128 allocation(s).

=================================================================
==1589775==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 19456 byte(s) in 128 object(s) allocated from:
    #0 0x7fe2db447e50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x40971d in allocate_task /home/yidong/spdk/examples/nvme/perf/perf.c:888
    #2 0x40986a in submit_io /home/yidong/spdk/examples/nvme/perf/perf.c:907
    #3 0x409b09 in work_fn /home/yidong/spdk/examples/nvme/perf/perf.c:949
    #4 0x40dfd7 in main /home/yidong/spdk/examples/nvme/perf/perf.c:1914
    #5 0x7fe2d9ef124a in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 19456 byte(s) leaked in 128 allocation(s).

=================================================================
==1589771==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 19456 byte(s) in 128 object(s) allocated from:
    #0 0x7f67b66f4e50 in calloc (/lib64/libasan.so.5+0xeee50)
    #1 0x40971d in allocate_task /home/yidong/spdk/examples/nvme/perf/perf.c:888
    #2 0x40986a in submit_io /home/yidong/spdk/examples/nvme/perf/perf.c:907
    #3 0x409b09 in work_fn /home/yidong/spdk/examples/nvme/perf/perf.c:949
    #4 0x40dfd7 in main /home/yidong/spdk/examples/nvme/perf/perf.c:1914
    #5 0x7f67b519e24a in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 19456 byte(s) leaked in 128 allocation(s).

## Context (Environment including OS version, SPDK version, etc.)
commit: c274db3bf8494aaa52feba568a1a55c8bc87d684 
os：4.17.19-200.fc28.x86_64

**Comment by optimistyzy** [comment]
@yidong0635  Since the perf tool is not the daemon tool, and you use ctrlr +c, all the resources related with this process will be recycled. Currently, for nvme perf test, there is the expected behavior if the connection is broken, then we just exit(1) to exit the process. And in other locations, we all have this operation (e.g., for aio model). So I think that it should be expected behavior of the resource freeing (we do not do it nearly for the exception). So I would think it is very low priority.

**Comment by yidong0635** [comment]
@optimistyzy  thanks, if that means this issue should be closed?

**Comment by optimistyzy** [comment]
@yidong0635 for this, I think that it could be closed
