### ISSUE TITLE
No way to check current version of SPDK using RPC in runtime

### ISSUE THREAD

**Issue by Roberciiik** [spdk/spdk#708]
Hi,

Could you add RPC method for checking SPDK version in runtime? I'm trying to use newer SPDK features only if they are available in the installed SPDK daemon (nvme_tgt). 

## Expected Behavior
New RPC method like "get_version" returning current version (i.e. `{ "version": "19.01"}` or `{"major": "18", "minor": "10", "build": "12345"}`) shall be available,

## Current Behavior
Version can be read from standard output.
Second option is to read variable if you link with SPDK as a library.

**Comment by jessehui** [comment]
Sounds good. I will take this.

**Comment by changpe1** [comment]
[Bug Scrub]: @Roberciiik thank for reporting, a good improvement indeed, @jessehui will submit a patch later.

**Comment by jessehui** [comment]
please refer to this patch:[rpc: add get_spdk_version rpc method](https://review.gerrithub.io/#/c/spdk/spdk/+/448613/)
Thank you.

**Comment by Roberciiik** [comment]
Looks good, thank you.

**Comment by jimharris** [comment]
I'm going to reopen this until the patch gets merged.

**Comment by changpe1** [comment]
Patch has been merged, so I'm going to close it again, :).
