### ISSUE TITLE
make fails: pci.c:47:23: fatal error: pciaccess.h: No such file or directory

### ISSUE THREAD

**Issue by svbrahma** [spdk/spdk#71]
Downloaded the latest spdk package (spdk-16.08). make fails trying to find <pciaccess.h>. Please help.

#> make DPDK_DIR=./dpdk-16.07/x86_64-native-linuxapp-gcc

  CC lib/util/pci.o
pci.c:47:23: fatal error: pciaccess.h: No such file or directory
 #include <pciaccess.h>
                       ^
compilation terminated.

**Comment by dverkamp-intel** [comment]
For the default configuration, you need to install libpciaccess (see the Prerequisites section of the README.md file included with the release).

If you use the latest SPDK from Git, libpciaccess is no longer required (it has been replaced with DPDK PCI functionality).
