### ISSUE TITLE
run autotest failed with SPDK_TEST_CRYPTO=1 && SPDK_TEST_BLOCKDEV=1&& SPDK_RUN_ASAN=1&&SPDK_RUN_UBSAN=1

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#710]
autotest failed with below configurations:
 assign a value of 1 to all of the pertinent tests
SPDK_BUILD_DOC=1
SPDK_RUN_CHECK_FORMAT=1
SPDK_RUN_SCANBUILD=1
SPDK_RUN_VALGRIND=1
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_UNITTEST=0
SPDK_TEST_ISAL=1
SPDK_TEST_ISCSI=0
SPDK_TEST_ISCSI_INITIATOR=0
SPDK_TEST_NVME=0
SPDK_TEST_NVME_CLI=0
SPDK_TEST_NVMF=0
SPDK_TEST_RBD=0
SPDK_TEST_CRYPTO=1
SPDK_TEST_OCF=0
 requires some extra configuration. see TEST_ENV_SETUP_README
SPDK_TEST_VHOST=0
SPDK_TEST_VHOST_INIT=0
SPDK_TEST_BLOCKDEV=1
doesn't work on vm
SPDK_TEST_IOAT=0
SPDK_TEST_EVENT=1
SPDK_TEST_BLOBFS=0
SPDK_TEST_PMDK=0
SPDK_TEST_LVOL=0
SPDK_TEST_REDUCE=0
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
 Reduce the size of the hugepages
HUGEMEM=1024
 Set up the DEPENDENCY_DIR
DEPENDENCY_DIR=/home/vagrant
## Issue log 
 see attached file. 
[fail_log.txt](https://github.com/spdk/spdk/files/2951318/fail_log.txt)

## Expected Behavior
run this autotest without  error.
## Current Behavior
autotest will blocked at  "run_test suite test/bdev/blockdev.sh"
## Possible Solution
wrong function realization :
spdk_bdev_part_io_type_supported  

## Steps to Reprodue
run autotest with above config.

## Context (Environment including OS version, SPDK version, etc.)
commit : 87851b6f3ad2ec5e78d5be94cd55880f1327542c

**Comment by darsto** [comment]
@yidong0635 Please attach the logs in a separate file.

**Comment by yidong0635** [comment]
@darsto  done.

**Comment by yidong0635** [comment]
_use VM to verify this issue ,  if failed the first time, test it again , env_dpdk_post_init  will report_ 
nvme_ctrlr.c:2196:nvme_ctrlr_process_init: *ERROR*: Initialization timed out in state 8
nvme_ctrlr.c: 500:nvme_ctrlr_fail: *ERROR*: ctrlr 0000:00:0e.0 in failed state.
nvme.c: 430:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 0000:00:0e.0
spdk_nvme_probe() failed
Attaching to 0000:00:0e.0
_it will be never recover again whatever reboot VM, need to destroy and recreate._

**Comment by changpe1** [comment]
@yidong0635 Can you try it again with master branch?

**Comment by yidong0635** [comment]
here is the [log_crypto.txt](https://github.com/spdk/spdk/files/3041826/log_crypto.txt)
this may need extra work to check crypto bdev. error changed .

**Comment by peluse** [comment]
@peluse to debug

**Comment by nedved1** [comment]
Hi @peluse is there aby updates?

**Comment by peluse** [comment]
I can repro locally, the original debug output not the 2nd one that was added.  Working on debugging...

**Comment by peluse** [comment]
Worked fine up until https://review.gerrithub.io/c/spdk/spdk/+/443741 when we moved to DPDK 19.02, something changed (still need to investigate) that is causing the aesni driver to not use the patch we apply to enable doing separate src and dst buffer operations.

**Comment by peluse** [comment]
So with 19.02 the aesni_driver took one of the files and appended "compat" to it and they complie it when the ipsec lib being used is under .5.  They made changes to the file with the "compat" on it to use new features of the latest ipsec but, of course, we didn't know this and since they're using the "compat" file for < .5 and we are less than .5, we end up compiling without the patched file. Will see which is less risky, add the patch to the new "compat" file or moving to ipsec .51 and update accordingly

**Comment by peluse** [comment]
The 2 patch series ending with https://review.gerrithub.io/c/spdk/spdk/+/449357/3 works for me locally and it queued for CI now

**Comment by jimharris** [comment]
Test pool never failed because it we only test crypto on systems that have QAT.  I've pushed this patch which will ensure we always test AESNI, even if QAT is available.

https://review.gerrithub.io/c/spdk/spdk/+/451784

Of course this patch fails now - will rebase it once Paul's patches are merged.

**Comment by yidong0635** [comment]
applied above patches, still got error: 
```
Test: blockdev write read 4k .../home/vagrant/master/build-20190424010422/spdk/dpdk/build/include/rte_mempool.h:1234:33: runtime error: member access within misaligned address 0xa3a3a3a3a3a40423 for type 'struct rte_mempool_cache', which requires 64 byte alignment
0xa3a3a3a3a3a40423: note: pointer points here
<memory cannot be printed>
    #0 0x60f6c5 in __mempool_generic_put /home/vagrant/master/build-20190424010422/spdk/dpdk/build/include/rte_mempool.h:1234
    #1 0x60f6c5 in rte_mempool_generic_put /home/vagrant/master/build-20190424010422/spdk/dpdk/build/include/rte_mempool.h:1285
    #2 0x60f6c5 in rte_mempool_put_bulk /home/vagrant/master/build-20190424010422/spdk/dpdk/build/include/rte_mempool.h:1308
    #3 0x60f6c5 in crypto_dev_poller /home/vagrant/master/build-20190424010422/spdk/lib/bdev/crypto/vbdev_crypto.c:557
    #4 0x6fd787 in spdk_thread_poll /home/vagrant/master/build-20190424010422/spdk/lib/thread/thread.c:473
    #5 0x6e2f10 in _spdk_reactor_run /home/vagrant/master/build-20190424010422/spdk/lib/event/reactor.c:244
    #6 0x797172 in eal_thread_loop /home/vagrant/master/build-20190424010422/spdk/dpdk/lib/librte_eal/linuxapp/eal/eal_thread.c:153
    #7 0x7f3bd4232593 in start_thread /usr/src/debug/glibc-2.27-114-gde9d4aa353/nptl/pthread_create.c:463
    #8 0x7f3bd3f66e5e in __GI___clone (/lib64/libc.so.6+0xf9e5e)

test/bdev/blockdev.sh: line 96: 576097 Aborted                 (core dumped) $testdir/bdevio/bdevio -s $PRE_RESERVED_MEM -c $testdir/bdev.conf
  01:10:25      # trap - ERR
  01:10:25      # print_backtrace
  01:10:25      # [[ ehxBE =~ e ]]
  01:10:25      # local shell_options=ehxBE
  01:10:25      # set +x
========== Backtrace start: ==========

in test/bdev/blockdev.sh:96 -> main()
     ...
   91           PRE_RESERVED_MEM=0
   92   else
   93           # Dynamic memory management is not supported on BSD
   94           PRE_RESERVED_MEM=2048
   95   fi
=> 96   $testdir/bdevio/bdevio -s $PRE_RESERVED_MEM -c $testdir/bdev.conf
   97   timing_exit bounds
   98


```

**Comment by peluse** [comment]
final fix is here: https://review.gerrithub.io/c/spdk/spdk/+/449357/6

**Comment by peluse** [comment]
be sure to git submodule update --init and make sure that you are seeing this: for git submodule after doing the update (it looks like you don't have the right ipsec lib)

 67b915b09bcf51ae2e2a703718881f0b0845883c dpdk (v18.08-1994-g67b915b09)
+489ec6082a9d4a65d7569d1772dce64d2e96f5b5 intel-ipsec-mb (v0.50-60-g489ec60)
 09e787231b31add1234ec9a3dfe718533f1c3bf4 isa-l (v2.24.0-3-g09e7872)
 bd19b9c12f924b3bfd5d228c3dc4a16d807595d0 ocf (remotes/origin/add-set-flush-queue-3-gbd19b9c)
