### ISSUE TITLE
Allow build architecture for x86 other than `native`

### ISSUE THREAD

**Issue by kreuzerkrieg** [spdk/spdk#711]
At this moment the `-march` flag is set in the make file (spdk.common.mk file) as `-march=native` and there is no way to override it. It may be problematic, since the build machine and staging/production may be of different architecture, though it is still `x86`. For example, build machine may support AVX512 and will generate the assembly accordingly. It will result in SIGILL on machine that has no support for AVX512.

**Comment by darsto** [comment]
Bug scrub: We could add a configure option to select the target architecture and pass the same option to underlying libs.

**Comment by benlwalker** [comment]
Fixed by 7dbdf87f6. There are more patches in the works to enable full cross compilation to any target, but that is sufficient to target a specific x86 platform instead of native.
