### ISSUE TITLE
with asan enabled   test/nvmf/host/fio.sh  report error 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#718]
run auto test case  " test/nvmf/host/fio.sh " with asan enabled report error :
 /usr/src/fio/fio  spdk/examples/nvme/fio_plugin/example_config.fio '--filename=trtype=RDMA adrfam=IPv4 traddr=10.0.2.15 trsvcid=4420 ns=1'
==3888360==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

## Expected Behavior
autotest will pass the case.

## Current Behavior
auto test will blocked here.

## Steps to Reproduce
./configure --with-rdma --enable-asan
make clean && make -j
test/nvmf/host/fio.sh
 
## Context (Environment including OS version, SPDK version, etc.)
commit:f373369a9c981b1f318e86531b3a8b4148d162e1

**Comment by changpe1** [comment]
[Bug Scrub] We don't enable fio test with ASAN, this test can be tested without ASAN.

**Comment by yidong0635** [comment]
@changpe1 SPDK_RUN_ASAN=1  run  nvmf auto cases, it will not  bypass this one . If don't want to run this case, auto test need to add switch.

**Comment by yidong0635** [comment]
in ./test/nvmf/nvmf.sh:39 -> main()
     ...
   34   run_test suite test/nvmf/host/identify.sh
   35   run_test suite test/nvmf/host/perf.sh
   36   # TODO: disabled due to intermittent failures (RDMA_CM_EVENT_UNREACHABLE/ETIMEDOUT)
   37   #run_test test/nvmf/host/identify_kernel_nvmf.sh
   38   run_test suite test/nvmf/host/aer.sh
=> 39   run_test suite test/nvmf/host/fio.sh
   40
   41   run_test suite test/nvmf/nmic/nmic.sh
   42
   43   timing_exit host
   44   trap - SIGINT SIGTERM EXIT
     ...

========== Backtrace end ==========
  05:01:08      # return 0

**Comment by changpe1** [comment]
@yidong0635 Can you post a patch to fix this? yeah, we don't have add ASAN check to fio, it's third party code.  thanks.

**Comment by yidong0635** [comment]
ok.  here is the patch :https://review.gerrithub.io/c/spdk/spdk/+/448597

**Comment by changpe1** [comment]
closing the issue now as the patch has been merged.
