### ISSUE TITLE
windows server can not use a aio bdev block device 

### ISSUE THREAD

**Issue by wanghonghuigithub** [spdk/spdk#720]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

windows server can not use a aio bdev block device 

## Steps to Reproduce

1.create a spdk block device with aio bdev backend
2.attach this device to a VM with windows server (2008, 2012 etc) os
3.configue this device in VM，then failed
4.

## Context (Environment including OS version, SPDK version, etc.)

spdk 18.04
VM os ： windows server 2008， windows server 2012

**Comment by optimistyzy** [comment]
duplicated issue with #625.  BTW,  @wanghonghuigithub Can you put more detailed error info, which will be helpful.

**Comment by jimharris** [comment]
Closing this issue.  @wanghonghuigithub - please put any additional details in issue #625.

Thanks,

-Jim
