### ISSUE TITLE
nvme_ctrlr_configure_aer is called twice, and more AER sent than expected

### ISSUE THREAD

**Issue by cranechu** [spdk/spdk#722]
https://github.com/spdk/spdk/blob/30bfdc9cc99cd45dd7bda23029d79ddb2894f5db/lib/nvme/nvme_ctrlr.c#L2127

We found an issue in our test that AER commands are sent more than expected to our device. Normally, it should be 4, but now SPDK sends 4 AER commands TWICE. 

Finally, we found the root cause here: 
NVME_CTRLR_STATE_IDENTIFY_ID_DESCS => NVME_CTRLR_STATE_CONFIGURE_AER,

change to: 
NVME_CTRLR_STATE_IDENTIFY_ID_DESCS => NVME_CTRLR_STATE_WAIT_FOR_IDENTIFY_ID_DESCS

**Comment by cranechu** [comment]
I can send out the PR if there is no problem. Thanks!

**Comment by darsto** [comment]
@cranechu SPDK user gerrithub for reviews. Please refer to https://spdk.io/development/ on how to submit a patch.

We'd be greateful for any fixes :)

**Comment by cranechu** [comment]
@darsto Thanks. I am submitting the patch. But I just meeting an issue in unittest after modification, so need some time to check that unittest fail.

**Comment by cranechu** [comment]
Now I think the proper fix is to remove this set_state, because it was just set properly in nvme_ctrlr_identify_id_desc_async. 

I have submitted the patch for review. 

Thanks.

**Comment by cranechu** [comment]
So, actually, I have submitted 2 commits.  :)

**Comment by changpe1** [comment]
@cranechu thanks  for debugging, I think you can just remove the line 2127: nvme_ctrlr_set_state(ctrlr, NVME_CTRLR_STATE_CONFIGURE_AER, ctrlr->opts.admin_timeout_ms);

**Comment by cranechu** [comment]
@changpe1 Yes. I did the change in the same way in my second commit. Thanks.

**Comment by changpe1** [comment]
@cranechu Thanks, can you point me the patch? I can review it and get it be merged.

**Comment by cranechu** [comment]
Hi, @changpe1  Here are the links: 
https://review.gerrithub.io/c/spdk/spdk/+/449366
https://review.gerrithub.io/c/spdk/spdk/+/449364

**Comment by cranechu** [comment]
I submitted it again in a single commit here: https://review.gerrithub.io/c/spdk/spdk/+/449527
