### ISSUE TITLE
RBD: fallocate failed: No space left on device

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#723]
Happens randomly on our CI.

```
+ cp /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/scripts/ceph/ceph.conf /var/tmp/ceph/ceph.conf
+ '[' '!' -e /var/tmp/ceph_raw.img ']'
+ fallocate -l 10G /var/tmp/ceph_raw.img
fallocate: fallocate failed: No space left on device
  10:47:36	# trap - ERR
```

Full log - https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/26832/archive/RBD_autotest/build.log

**Comment by karlatec** [comment]
@nedved1 Pawel can you take a look? I think we should increase the size of the base image.

**Comment by darsto** [comment]
It happens quite often now. @nedved1 please increase the priority on this.

**Comment by yidong0635** [comment]
@karlatec @nedved1 if need to increase the size of base image, that means all base images should be changed( this need to package all the base images). How about by case to "fallocate -l 10G /var/tmp/ceph_raw.img" .
first to fallocate 10G , if failed , then decrease the size to 4G  . 4G is ok.
for virtual machine 10G is a little big.

**Comment by yidong0635** [comment]
I have a patch about this , https://review.gerrithub.io/c/spdk/spdk/+/449167

**Comment by karlatec** [comment]
@yidong0635 

> if need to increase the size of base image, that means all base images should be changed

Well yes, that's what @nedved1 did exactly. OS images were increased by 10G.

> first to fallocate 10G , if failed , then decrease the size to 4G . 4G is ok.

I think there's no need to first try and create 10G and fall back to 4G. I'd just change the size to 4G and that's it. By the way, do we know why the size was 10G in the first place? Why exactly that size was needed?

**Comment by nedved1** [comment]
@darsto @karlatec I' ve resized VM image, let's check if that helps.

**Comment by yidong0635** [comment]
@Seth5141  Can you help to answer what karol questioned ?

**Comment by darsto** [comment]
@yidong0635 The RBD failure was haunting our CI, so I asked Karol to simplify your patch - 
https://review.gerrithub.io/c/spdk/spdk/+/449167

I've merged it just now. If there's anything still to be done for RBD tests, please feel free to push additional patches.
