### ISSUE TITLE
Reboot FreeBSD test VMs after every test

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#724]
Reboot FreeBSD VMs after every test, regardless of the result.

After a number of consecutive runs FreeBSD VMs crash. This is caused by frequently reloading contigmem.ko module used to allocate superpages.

More frequent rebooting of these VMs should mitigate the issue.

**Comment by karlatec** [comment]
FreeBSD VMs config changed to reboot after each test.
@darsto @nedved1 - please watch of for any contigmem.ko crash errors in tests and let me know.

**Comment by darsto** [comment]
I haven't seen any bsd crashes lately. Thanks @karlatec , closing.
