### ISSUE TITLE
SPDK/FTL: A segmentation fault occurs in ftl_io_erase_init() and ftl_reloc_io_init() when ftl_io_init_internal() returns NULL.

### ISSUE THREAD

**Issue by iClaire** [spdk/spdk#726]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

It should check for null before it uses any fields of struct ftl_io *io and it should return error if needed.

## Current Behavior

When ftl_io_init_internal() returns NULL, it cause a segmentation fault.

## Possible Solution

	if (!io) {
		return NULL;
	}

## Steps to Reproduce

1.
2.
3.
4.

**Comment by iClaire** [comment]
Hi @wmalikow,
I just found this while I was in debugging. You will just need to check if it is NULL or not.
Thanks!

**Comment by ksztyber** [comment]
@iClaire Since you've done all of the debugging, feel free to post a patch!

**Comment by iClaire** [comment]
@ksztyber OK! I’ll post it soon.
