### ISSUE TITLE
spdk_nvme_ctrlr_get_first_active_ns() and next may not be thread safe

### ISSUE THREAD

**Issue by lhoswdev** [spdk/spdk#727]
## Expected Behavior
Comments for `spdk_nvme_ctrlr_get_first_active_ns()` and `spdk_nvme_ctrlr_get_next_active_ns()` state that they are "... thread safe and can be called at any point while the controller is attached to the SPDK NVMe driver".   That may not be the case, but needs to be.   May need to add some kind of locking protecting the `ctrlr->active_ns_list`.

## Current Behavior

Library function `nvme_ctrlr_identify_active_ns()` can free and re-allocate a `ctrlr->active_ns_list`.   This lib function can be triggered by an asychronous event request.   `spdk_nvme_ctrlr_attach_ns()`, `spdk_nvme_ctrlr_detach_ns()` and `spdk_nvme_ctrlr_delete_ns()` also call `nvme_ctrlr_identify_active_ns()`.   If the APIs for getting an active ns are running on other threads simultaneously, it's possible for the ctrlr->active_ns_list to be pulled out from underneath them resulting in an invalid ptr, segfault, etc.

## Context (Environment including OS version, SPDK version, etc.)
SPDK 19.04-pre (e.g. on master as of commit 5874e2a) as well as previously released/tagged SPDK versions (e.g. SPDK 18.10.x).

**Comment by darsto** [comment]
Community meeting: maybe instead of adding thread safety, we should document from which threads those function can be called.

AR Jim: Review if there are any actual data races and possible crashes.

**Comment by ak-gh** [comment]
On a separate note, I see similar (undocumented) behavior under lib/bdev.c where it's far from clear what safeguards global bdev list during register/unregister calls. Hardly a good place to raise this, though, so I'll appreciate a suggestion if a separate issue needs to be filed.

**Comment by darsto** [comment]
Bug scrub: we agree those functions should be at least documented if they're thread safe or not.

**Comment by darsto** [comment]
I'm actually going to close this issue - we would like to track only issues on github. Please create a trello item on https://trello.com/b/P5xBO7UR/things-to-do if you'd like to make this enhancement more visible.
