### ISSUE TITLE
vhost scsi: assertion failure on lun hotdetach

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#733]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Assert error when testing hotdetach

## Expected Behavior
Remove vhost scsi target should work properly.

## Current Behavior
When doing remove_vhost_scsi_target rpc following error occurs:
vhost: bdev.c:3929: spdk_bdev_close: Assertion `desc->thread == spdk_get_thread()' failed.

## Steps to Reproduce
1. Checkout https://review.gerrithub.io/#/c/spdk/spdk/+/447060/
2. Run test test/vhost/hotplug/scsi_stress_test.sh

## Context (Environment including OS version, SPDK version, etc.)
Vm: Linux ubuntu 4.9.0-040900-generic

**Comment by darsto** [comment]
We've removed this assert in patch 283abcb9a2445183014b5bd5bc1511e837a71de6
