### ISSUE TITLE
nvme command prints incorrect CNTLID value from SPDK NVMe-oF  controller 

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#734]
From the specification, the CNTLID should be 0xFFFFh if the controller is dynamic controller model. If the bit 0 of CTRATTR is 0, then this controller is dynamic controller model. 

## Expected Behavior
The ctrattr value is 0, so this controller is dynamic controller. So the cntlid value should be 0xFFFFh. 

## Current Behavior
The ctrattr value is 0, so this controller is dynamic controller. So the cntlid value should be 0xFFFFh. But from the output, the cntlid value is 1.

## Possible Solution
Tried malloc bdev, same result.

## Steps to Reproduce
1. run spdk nvmf with the attached file, 
[nvmf.conf.txt](https://github.com/spdk/spdk/files/3032022/nvmf.conf.txt)

2. in host machines, discover and connect to the spdk nvmf target;
3. run "nvme id-ctrl /dev/nvme0" command, the output is as below:
```
NVME Identify Controller:
vid       : 0
ssvid     : 0
sn        : SPDK00000000000001
mn        : SPDK bdev Controller
fr        : 19.04
rab       : 6
ieee      : 000000
cmic      : 0x3
mdts      : 5
cntlid    : 1
ver       : 10300
rtd3r     : 0
rtd3e     : 0
oaes      : 0x100
ctratt    : 0x1
rrls      : 0
oacs      : 0
acl       : 0
aerl      : 0
frmw      : 0x3
lpa       : 0x6
elpe      : 127
npss      : 0
avscc     : 0
apsta     : 0
wctemp    : 0
cctemp    : 0
mtfa      : 0
hmpre     : 0
hmmin     : 0
tnvmcap   : 0
unvmcap   : 0
rpmbs     : 0
edstt     : 0
dsto      : 0
fwug      : 0
kas       : 100
hctma     : 0
mntmt     : 0
mxtmt     : 0
sanicap   : 0
hmminds   : 0
hmmaxd    : 0
nsetidmax : 0
anatt     : 0
anacap    : 0
anagrpmax : 0
nanagrpid : 0
sqes      : 0x66
cqes      : 0x44
maxcmd    : 128
nn        : 20
oncs      : 0x2c
fuses     : 0
fna       : 0
vwc       : 0x5
awun      : 0
awupf     : 0
nvscc     : 0
nwpc      : 0
acwu      : 0
sgls      : 100005
mnan      : 0
subnqn    : nqn.2016-06.io.spdk:cnode1
ioccsz    : 260
iorcsz    : 1
icdoff    : 0
ctrattr   : 0

```
The ctrattr value is 0, so this controller is dynamic controller. So the cntlid value should be 0xFFFFh. But from the output, the cntlid value is 1.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: 80c87083ce5bfc34fdc35e09d1057783807b7130

**Comment by changpe1** [comment]
@liang2yan @glodfish-zg This is not a bug, for dynamic controller model, when connecting to SPDK nvmf target, Host should set the CNTLID to 0xffff, and SPDK already checked the value.
