### ISSUE TITLE
nbd RPCs need to be documented in jsonrpc.md

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#737]
start_nbd_disk, stop_nbd_disk and get_nbd_disks need to be documented in jsonrpc.md.  Currently they are only implicitly documented in the bdev users guide.

This documentation in jsonrpc.md should explicitly remind users to 'modprobe nbd'.

**Comment by jimharris** [comment]
Ha - I just saw that @pawelwod suggested this in a patch from @dong-liuliu.  Xiaodong agreed to add it to his backlog so I'm assigning this issue to him.

https://review.gerrithub.io/c/spdk/spdk/+/440453

**Comment by dong-liuliu** [comment]
Thanks for the notice, Jim.
Just submit it to  https://review.gerrithub.io/c/spdk/spdk/+/450578 
Please review it when you have free time.

**Comment by jimharris** [comment]
Patch merged - thanks @dong-liuliu!
