### ISSUE TITLE
SPDK subsystems don't handle initialization failures very well

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#739]
This came up while debugging a different initialization issue in NVMf. Currently, if NVMf subsystem
e.g. fails to parse its config section on init, it'll fail the initialization routine properly, but won't proceed in the finish routine. The app will simply freeze with only a subset of its modules initialized.

From what I see, the NVMf subsystem doesn't expect the fini() callback to be fired for subsystems which failed to initialize. On the other hand, the bdev subsystem does depend on its fini() callback being always called.

We don't test initialization failures on our CI, so there might be more bugs lurking around.

**Comment by Comphix** [comment]
Looking at this issue.

**Comment by Comphix** [comment]
Raised the initial patch here https://review.gerrithub.io/c/spdk/spdk/+/476904

**Comment by Comphix** [comment]
Updated the patch based on the comments.

**Comment by Comphix** [comment]
Patch is under reviewing.

**Comment by Comphix** [comment]
Patch has been merged. Close this issue at this moment. Please feel free to reopen it if necessary.

**Comment by darsto** [comment]
Reopening. That's a generic problem spread throughout the entire SPDK. It's still present.

**Comment by tomzawadzki** [comment]
Bug scrub: Need more defined cases where failures occur. At this time @shuhei-matsumoto found one that occurs in iSCSI. Lets work through this one and then close if no other obvious cases are known. @jimharris will take a look at the one found by Shuhei.

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/8351

**Comment by jimharris** [comment]
Patch merged.
