### ISSUE TITLE
SPDK compile failures on kernel 5.0.5

### ISSUE THREAD

**Issue by ack72tdp** [spdk/spdk#740]
Suse linux 12.3 with Kernel 5.0.5 -- compile seems to fail ..

suse11:/var # uname -a
Linux suse11 5.0.5-2.g0b95959-default #1 SMP Mon Apr 1 14:57:33 UTC 2019 (0b95959) x86_64 x86_64 x86_64 GNU/Linux

suse11:~/spdk # make
Configuration done using x86_64-native-linuxapp-gcc
make[3]: Entering directory '/root/spdk/dpdk'
== Build lib
== Build lib/librte_compat
  SYMLINK-FILE include/rte_compat.h
== Build lib/librte_kvargs
  SYMLINK-FILE include/rte_kvargs.h
  CC rte_kvargs.o
  AR librte_kvargs.a
  INSTALL-LIB librte_kvargs.a
== Build lib/librte_eal
== Build lib/librte_eal/common
  SYMLINK-FILE include/rte_branch_prediction.h
  SYMLINK-FILE include/rte_common.h
  SYMLINK-FILE include/rte_debug.h
  SYMLINK-FILE include/rte_eal.h
  SYMLINK-FILE include/rte_errno.h
  SYMLINK-FILE include/rte_launch.h
  SYMLINK-FILE include/rte_eal_interrupts.h
  SYMLINK-FILE include/rte_log.h
  SYMLINK-FILE include/rte_lcore.h
  SYMLINK-FILE include/rte_memory.h
  SYMLINK-FILE include/rte_memzone.h
  SYMLINK-FILE include/rte_per_lcore.h
  SYMLINK-FILE include/rte_random.h
  SYMLINK-FILE include/rte_tailq.h
  SYMLINK-FILE include/rte_interrupts.h
  SYMLINK-FILE include/rte_alarm.h
  SYMLINK-FILE include/rte_string_fns.h
  SYMLINK-FILE include/rte_version.h
  SYMLINK-FILE include/rte_eal_memconfig.h
  SYMLINK-FILE include/rte_malloc_heap.h
  SYMLINK-FILE include/rte_hexdump.h
  SYMLINK-FILE include/rte_devargs.h
  SYMLINK-FILE include/rte_bus.h
  SYMLINK-FILE include/rte_dev.h
  SYMLINK-FILE include/rte_class.h
  SYMLINK-FILE include/rte_option.h
  SYMLINK-FILE include/rte_pci_dev_feature_defs.h
  SYMLINK-FILE include/rte_pci_dev_features.h
  SYMLINK-FILE include/rte_keepalive.h
  SYMLINK-FILE include/rte_malloc.h
  SYMLINK-FILE include/rte_time.h
  SYMLINK-FILE include/rte_service.h
  SYMLINK-FILE include/rte_bitmap.h
  SYMLINK-FILE include/rte_service_component.h
  SYMLINK-FILE include/rte_hypervisor.h
  SYMLINK-FILE include/rte_vfio.h
  SYMLINK-FILE include/rte_test.h
  SYMLINK-FILE include/rte_reciprocal.h
  SYMLINK-FILE include/rte_fbarray.h
  SYMLINK-FILE include/rte_uuid.h
  SYMLINK-FILE include/rte_atomic.h
  SYMLINK-FILE include/rte_atomic_32.h
  SYMLINK-FILE include/rte_atomic_64.h
  SYMLINK-FILE include/rte_byteorder.h
  SYMLINK-FILE include/rte_byteorder_32.h
  SYMLINK-FILE include/rte_byteorder_64.h
  SYMLINK-FILE include/rte_cycles.h
  SYMLINK-FILE include/rte_cpuflags.h
  SYMLINK-FILE include/rte_io.h
  SYMLINK-FILE include/rte_memcpy.h
  SYMLINK-FILE include/rte_pause.h
  SYMLINK-FILE include/rte_prefetch.h
  SYMLINK-FILE include/rte_spinlock.h
  SYMLINK-FILE include/rte_rtm.h
  SYMLINK-FILE include/rte_vect.h
  SYMLINK-FILE include/rte_rwlock.h
  SYMLINK-FILE include/generic/rte_atomic.h
  SYMLINK-FILE include/generic/rte_cycles.h
  SYMLINK-FILE include/generic/rte_byteorder.h
  SYMLINK-FILE include/generic/rte_spinlock.h
  SYMLINK-FILE include/generic/rte_prefetch.h
  SYMLINK-FILE include/generic/rte_memcpy.h
  SYMLINK-FILE include/generic/rte_cpuflags.h
  SYMLINK-FILE include/generic/rte_rwlock.h
  SYMLINK-FILE include/generic/rte_vect.h
  SYMLINK-FILE include/generic/rte_pause.h
  SYMLINK-FILE include/generic/rte_io.h
== Build lib/librte_eal/linuxapp
== Build lib/librte_eal/linuxapp/eal
  SYMLINK-FILE include/exec-env/rte_kni_common.h
  CC eal.o
  CC eal_cpuflags.o
  CC eal_hugepage_info.o
  CC eal_memory.o
  CC eal_thread.o
  CC eal_log.o
  CC eal_vfio.o
  CC eal_debug.o
  CC eal_vfio_mp_sync.o
  CC eal_lcore.o
  CC eal_memalloc.o
  CC eal_interrupts.o
  CC eal_timer.o
  CC eal_alarm.o
  CC eal_dev.o
  CC eal_common_lcore.o
  CC eal_common_timer.o
  CC eal_common_memzone.o
  CC eal_common_log.o
  CC eal_common_launch.o
  CC eal_common_memalloc.o
  CC eal_common_memory.o
  CC eal_common_tailqs.o
  CC eal_common_errno.o
  CC eal_common_cpuflags.o
  CC eal_common_hypervisor.o
  CC eal_common_string_fns.o
  CC eal_common_hexdump.o
sed: couldn't flush stdout: No space left on device
/root/spdk/dpdk/lib/librte_eal/common/eal_common_memory.c:942:1: fatal error: closing dependency file ./.eal_common_memory.o.d.tmp: No space left on device
 }
 ^
compilation terminated.
/root/spdk/dpdk/mk/internal/rte.compile-pre.mk:114: recipe for target 'eal.o' failed
make[8]: *** [eal.o] Error 4
make[8]: *** Waiting for unfinished jobs....
/root/spdk/dpdk/mk/internal/rte.compile-pre.mk:114: recipe for target 'eal_common_memory.o' failed
make[8]: *** [eal_common_memory.o] Error 1
/root/spdk/dpdk/mk/rte.subdir.mk:35: recipe for target 'eal' failed
make[7]: *** [eal] Error 2
/root/spdk/dpdk/mk/rte.subdir.mk:35: recipe for target 'linuxapp' failed
make[6]: *** [linuxapp] Error 2
/root/spdk/dpdk/mk/rte.subdir.mk:35: recipe for target 'librte_eal' failed
make[5]: *** [librte_eal] Error 2
/root/spdk/dpdk/mk/rte.sdkbuild.mk:49: recipe for target 'lib' failed
make[4]: *** [lib] Error 2
/root/spdk/dpdk/mk/rte.sdkroot.mk:100: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/root/spdk/dpdk'
Makefile:12: recipe for target 'all' failed
make[2]: *** [all] Error 2
Makefile:120: recipe for target 'all' failed
make[1]: *** [all] Error 2
/root/spdk/mk/spdk.subdirs.mk:44: recipe for target 'dpdkbuild' failed
make: *** [dpdkbuild] Error 2

Any thoughts?

Thanks

**Comment by Seth5141** [comment]
@ack72tdp It looks like your machine is out of space.
~~~
sed: couldn't flush stdout: No space left on device
/root/spdk/dpdk/lib/librte_eal/common/eal_common_memory.c:942:1: fatal error: closing dependency file ./.eal_common_memory.o.d.tmp: No space left on device
~~~

You can verify this by running  df -h. I assume that you will have a use value close to 100% on the filesystem mount point under which you are operating. You will have to clean out some files or expand the underlying volume.
