### ISSUE TITLE
Fails to create a target after upgrade to kernel 5.0.5

### ISSUE THREAD

**Issue by ack72tdp** [spdk/spdk#741]
After upgrading Suse 12.3 with Kernel 5.0.5, fails to create a target ..  

//Kernel
suse11:~/spdk # uname -a
Linux suse11 5.0.5-2.g0b95959-default #1 SMP Mon Apr 1 14:57:33 UTC 2019 (0b95959) x86_64 x86_64 x86_64 GNU/Linux

//block devices (2 SSD)
suse11:~/spdk # lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sdf      8:80   0 185.3G  0 disk
sdg      8:96   0 185.3G  0 disk

//SPDK conf params 
[AIO]
  AIO /dev/sdg AIO0
  AIO /dev/sdf AIO1

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen TCP 192.168.1.50:4421
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace AIO1 1

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode2
  Listen RDMA 192.168.2.50:4422
  AllowAnyHost yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  Namespace AIO0

// both RDMA and TCP drivers along with NVMET 
suse11:~/spdk # modinfo nvme-tcp
filename:       /lib/modules/5.0.5-2.g0b95959-default/kernel/drivers/nvme/host/nvme-tcp.ko
license:        GPL v2
suserelease:    openSUSE Tumbleweed
srcversion:     B95F5807FD8B5BA5E0FBA71
depends:        nvme-fabrics
retpoline:      Y
intree:         Y
name:           nvme_tcp
vermagic:       5.0.5-2.g0b95959-default SMP mod_unload modversions

suse11:~/spdk # modinfo nvme-rdma
filename:       /lib/modules/5.0.5-2.g0b95959-default/kernel/drivers/nvme/host/nvme-rdma.ko
license:        GPL v2
suserelease:    openSUSE Tumbleweed
srcversion:     3FB874BD1FC0868F5A607B4
depends:        rdma_cm,ib_core,nvme-fabrics
retpoline:      Y
intree:         Y
name:           nvme_rdma
vermagic:       5.0.5-2.g0b95959-default SMP mod_unload modversions
parm:           register_always:Use memory registration even for contiguous memory regions (bool)
  
// can ping IPs
suse11:~/spdk # ping 192.168.1.50
PING 192.168.1.50 (192.168.1.50) 56(84) bytes of data.
64 bytes from 192.168.1.50: icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from 192.168.1.50: icmp_seq=2 ttl=64 time=0.043 ms

// CREATE TARGET FAILS with RDMA
suse11:~/spdk # app/nvmf_tgt/nvmf_tgt -c etc/spdk/nvmf.conf.in -L RDMA
Starting SPDK v19.04-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid65269 ]
EAL: No free hugepages reported in hugepages-1048576kB
app.c: 636:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 245:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
rdma.c:1833:spdk_nvmf_rdma_create: *INFO*: *** RDMA Transport Init ***
  Transport opts:  max_ioq_depth=128, max_io_size=131072,
  max_qpairs_per_ctrlr=16, io_unit_size=8192,
  in_capsule_data_size=4096, max_aq_depth=128,
  num_shared_buffers=4096, max_srq_depth=4096
rdma.c:1867:spdk_nvmf_rdma_create: *ERROR*: rdma_create_event_channel() failed, No such device
transport.c: 109:spdk_nvmf_transport_create: *ERROR*: Unable to create new transport of type RDMA
subsystem.c: 129:spdk_subsystem_init_next: *ERROR*: Init subsystem nvmf failed
app.c: 716:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero

Any thoughts?

Thanks

**Comment by karlatec** [comment]
I got the exact same errors when I tried doing:
```
Listen RDMA 192.168.2.50:4422
```
on a non-RDMA NIC (I don't have a RDMA enabled NIC in my server).

When I started SoftRoce and enabled it for the same NIC - nvmf_tgt started up correctly.

On a side note - I am using 5.0.5 kernel on different server (this time with RDMA NICs) with RDMA transport layer with no problems so far. The difference is I am using a Fedora 28 as base system.

**Comment by ack72tdp** [comment]
Thanks @karlatec ... on further investigation I noticed that broadcom drivers may not be working and I am looking into that first .. Will post updates once I complete my investigation ..

**Comment by changpe1** [comment]
@ack72tdp There is also a user space library required, for my platform RDMA NICs, libmlx5 is required, and I believe you also need a specific library too.

**Comment by darsto** [comment]
I'm going to close this issue. Please @mention me if you'd like me to reopen it.
