### ISSUE TITLE
bdev optimal io boundary & IO split configuration

### ISSUE THREAD

**Issue by NiuYawei** [spdk/spdk#745]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

spdk_bs_blob_write() failed on large I/O size (128MB) write because of limitation from NVMe bdev. I suppose blobstore or bdev should split I/O internally to avoid returning error in this situation, force blobstore caller to split I/O externally can workaround to the issue, but that looks not clean to me since the bdev limitation needs be exposed to blobstore caller.

Jim pointed out the real cause and proposed a solution of configuring 'optimal io boundary' and 'split io on optimal boundary', see details quoted from Jim's reply on mail list below.

## Expected Behavior

SPDK blobsotre (or bdev) should split large I/O according to specific bdev limitations.

## Current Behavior

SPDK blob write will fail on large I/O size because of limitation of NVMe bdev.

## Possible Solution

Hi Niu,
The NVMe driver is actually breaking this 128MB I/O into much smaller chunks. Most SSDs only support a max I/O size of 128KB-1MB. The problem you're seeing here is that the I/O is so big that the NVMe driver doesn't have enough context objects (struct nvme_request) to handle even a single 128MB I/O.
Adding this kind of splitting for extremely big I/O inside of blobstore itself isn't planned. Blobstore splits on cluster boundaries because it's required. But there's a lot of complexity - especially when you have to do things like split an array of iovs. I'm guessing in your case you just have a single iov which would make splitting easy, but blobstore has to handle the splitting for all cases. We've built complex splitting into the bdev layer - I'd like to see if we can find a way for you to use that here instead.
In lib/bdev/nvme/bdev_nvme.c - search for "optimal_io_boundary". This is currently set to the optimal_io_boundary for the namespace - some SSDs don't have an optimal boundary, most Intel SSDs specify 128KB here. Try setting the optimal_io_boundary to something like 8MB. Then also set bdev->disk.split_on_optimal_io_boundary = true. Then when you start sending 128MB I/O from blobstore, the bdev layer will split those on 8MB boundaries. If the NVMe driver runs out of nvme_request objects, the bdev layer will queue up those split requests and resubmit them once previous I/O are completed.

## Steps to Reproduce

1. Create a blobstore over NVMe bdev with huge cluster size, 1GB for instance
2. Issue a blob write with large size I/O (128MB)
3. The blob write will fail due to the limitation mentioned by Jim above
4.

**Comment by jimharris** [comment]
Thanks @NiuYawei.

I think the long term solution for this - instead of the workaround I mentioned above - would be to allow specifying a bigger io_queue_requests value through the bdev/nvme RPCs.  Currently the default is 512.  A global default could be set through set_bdev_nvme_options, or the default for a specific controller could be set through construct_nvme_bdev.

I'm marking this as an enhancement request, but extending these RPCs is likely useful outside of just this specific use case.

**Comment by changpe1** [comment]
I posted a patch to make `io_queue_requests` of NVMe I/O queue can be configured via RPC, if users do need very big I/O size , they can increase the number when creating a new NVMe controller. https://review.gerrithub.io/c/spdk/spdk/+/461182

**Comment by changpe1** [comment]
Closing this issue for now as the io_queue_requests can be configured by users, users can set a big number if they do have very big IO requirement.
