### ISSUE TITLE
Does SPDK support DPS (Data Protection Service)?

### ISSUE THREAD

**Issue by pentyala** [spdk/spdk#748]
Hi,

Does SPDK support DPS. If yes, can you direct me to proper documentation?

Thanks.

**Comment by changpe1** [comment]
@pentyala SPDK does support End-to-End data protection feature, you can refer to https://spdk.io/doc/bdev_8h.html and https://spdk.io/doc/nvme_8h.html.

**Comment by pentyala** [comment]
@changpe1 Thanks for answering quick.

I am trying to configure NVMe over RDMA using the steps mentioned in spdk.io.

I was able to create namespaces and connect to controllers. However, I could not find an option where I can enable DPS. Is there something that I am missing? Can you please provide steps on how to enable DPS?

**Comment by changpe1** [comment]
First of all you must have physical drive which can support extended LBA format, and then format the drive to (512 + 8) or other types, after that, you can add the Namespace to one of the subsystem's Namespace.

**Comment by optimistyzy** [comment]
@pentyala It currently only works for bdev build on real NVMe device, and you need to format your device like @changpe1  describes. Currently, we do not support such feature for bdev built on simulated device.

**Comment by pentyala** [comment]
Hi, 
Thanks for letting me know.

Now I am using a real NVMe device in my setup with extended LBA.
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172X (rev 01)

Formatted to 520 sector size using nvme format command in ubuntu.

~/Source/spdk$ sudo nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1           S2JRNA0J200057 Dell Express Flash NVMe PM1725 800GB SFF 1           0.00   B / 800.17  GB    512   B +  8 B   KPYA8D3Q

I have successfully created a controller, namespace and I am able to connect to the controller and namespace. However, I am not getting the right format.

~/Source/spdk$ sudo nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     SPDK00000000000001   SPDK bdev Controller                     1         800.17  GB / 800.17  GB    512   B +  0 B   19.01.2

I wanted to confirm that formatting the real NVMe ssd to 512+8 using the nvme format command is the right approach. Thanks!
