### ISSUE TITLE
HugePage difference master vs v19.01

### ISSUE THREAD

**Issue by ctuffli** [spdk/spdk#749]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

It appears that HugePages are not being freed after an application closes on the  v19.01 branch. But this appears to work correctly on master.

Before running the application, `/proc/meminfo` shows:

    $ grep ^Huge /proc/meminfo
    HugePages_Total:     256
    HugePages_Free:      256
    HugePages_Rsvd:        0
    HugePages_Surp:        0
    Hugepagesize:       2048 kB

## Expected Behavior

After running the application, `HugePages_Free`, matches `HugePages_Total`. Running this test on master shows:

    $ grep ^Huge /proc/meminfo
    HugePages_Total:     256
    HugePages_Free:      255
    HugePages_Rsvd:        0
    HugePages_Surp:        0
    Hugepagesize:       2048 kB

This is close to the desired behavior.
## Current Behavior

After running the application, `HugePages_Free` goes down. Running the same test on branch v19.01 shows:

    $ grep ^Huge /proc/meminfo
    HugePages_Total:     256
    HugePages_Free:       79
    HugePages_Rsvd:        0
    HugePages_Surp:        0
    Hugepagesize:       2048 kB

## Steps to Reproduce

1. Checkout the v19.01 branch
2. ./configure --disable-tests
3. ./examples/bdev/hello_world/hello_bdev -c examples/bdev/hello_world/bdev.conf -b Malloc1
4. grep ^Huge /proc/meminfo

## Context (Environment including OS version, SPDK version, etc.)

Note that this issue appears with other applications, but the `hello_bdev` reproduces the issue.

 The x86_64 system is running Ubuntu 18.04 with the standard kernel (Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64)

**Comment by darsto** [comment]
That's true. . We had some issues with hotremoving memory that's used by RDMA and we fixed those for SPDK 19.04 (with DPDK 19.02), but for earlier versions of either DPDK or SPDK we workaround them by not releasing any hugepages. Note that if your SPDK application does not exit cleanly (is killed or crashes), it still won't release any hugepages no matter which version you use. However, they will be released by the subsequently started SPDK application at initialization time. If you're using hugepages in different applications as well and you need to have some free hugepages for them, you might want to manually delete hugetlbfs files in /dev/hugepages/spdk_pid<pid>*

https://github.com/spdk/spdk/blob/0871b382060825e30b1643c114f7aafec7479e4c/lib/env_dpdk/memory.c#L712-L725

**Comment by darsto** [comment]
I'm closing the github issue per se, but let's continue the discussion here.

**Comment by ctuffli** [comment]
Happy to hear that this is fixed, but I'm not seeing a 19.04 branch or tag. Is there an approximate schedule for this?

**Comment by jimharris** [comment]
19.04 will be released by end of April (19 = 2019, 04 = April)

**Comment by ctuffli** [comment]
Perfect. Thanks @jimharris , just wasn't sure if the 04 meant the beginning or end of the month.
