### ISSUE TITLE
Can not get "Extended INQUIRY Data VPD page"

### ISSUE THREAD

**Issue by yaojingen** [spdk/spdk#750]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

execute:
 "sg_inq --page=0x86 /dev/sd* " after login iscsi target
result:
VPD INQUIRY: extended INQUIRY data page
  SPT=0 GRD_CHK=0 APP_CHK=0 REF_CHK=0
  UASK_SUP=0 GROUP_SUP=0 PRIOR_SUP=0 HEADSUP=0 ORDSUP=0 SIMPSUP=0
  WU_SUP=0 CRD_SUP=0 NV_SUP=0 V_SUP=0
  P_I_I_SUP=0 LUICLR=0 CBCS=0 R_SUP=0
  Multi I_T nexus microcode download=0
  Extended self-test completion minutes=0
  POA_SUP=0 HRA_SUP=0 VSA_SUP=0
  Maximum supported sense data length=0

## Current Behavior

execute:
 "sg_inq --page=0x86 /dev/sd* " after login iscsi target
result:
VPD INQUIRY: extended INQUIRY data page
invalid VPD response; probably a STANDARD INQUIRY response

## Possible Solution

1、https://github.com/spdk/spdk/blob/master/lib/scsi/scsi_bdev.c line 402 is redundant
2、https://github.com/spdk/spdk/blob/master/include/spdk/scsi_spec.h line 430
     the spdk_scsi_vpd_ext_inquiry struct is error。in SPC-3，the struct need to define as follow:
struct spdk_scsi_vpd_ext_inquiry {
	uint8_t peripheral;
	uint8_t page_code;
        uint8_t reserved2;
	uint8_t alloc_len;
	uint8_t check;
	uint8_t sup;
	uint8_t sup2;
	uint8_t reserved[57];
};
 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by jimharris** [comment]
Fix here:  https://review.gerrithub.io/c/spdk/spdk/+/450922

**Comment by jimharris** [comment]
Patch is merged so closing this issue.  Please advise if you still see any problems.
