### ISSUE TITLE
Memory leak in iscsi_subsystem.c?

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#752]
This is not necessarily a valid defect but I'm confused by the iscsi socket group initialization code and it seems there's a memory leak.

The function initialize_iscsi_poll_group creates a socket group for each core but it uses the spdk_for_each_thread() which iterates through all registered threads, to accomplish that.
The poll_group is stored in an array indexed by core.

I think this can lead to a memory leak since we can have multiple threads running on the same core. In this case, spdk_sock_group_create() in iscsi_create_poll_group is called multiple times and we lose the previous pointer. Same issue for the pollers... we seem to register more than one poller per core.

Is this correct behavior? Or is the iscsi subsystem initialization happening right after reactors have been created and before any other threads are started? 

```
static void
iscsi_create_poll_group(void *ctx)
{
	struct spdk_iscsi_poll_group *pg;

	assert(g_spdk_iscsi.poll_group != NULL);
	pg = &g_spdk_iscsi.poll_group[spdk_env_get_current_core()];
	pg->core = spdk_env_get_current_core();

	STAILQ_INIT(&pg->connections);
	pg->sock_group = spdk_sock_group_create();
	assert(pg->sock_group != NULL);

	pg->poller = spdk_poller_register(iscsi_poll_group_poll, pg, 0);
	/* set the period to 1 sec */
	pg->nop_poller = spdk_poller_register(iscsi_poll_group_handle_nop, pg, 1000000);
}

static void
iscsi_unregister_poll_group(void *ctx)
{
	struct spdk_iscsi_poll_group *pg;

	assert(g_spdk_iscsi.poll_group != NULL);
	pg = &g_spdk_iscsi.poll_group[spdk_env_get_current_core()];
	assert(pg->poller != NULL);
	assert(pg->sock_group != NULL);

	spdk_sock_group_close(&pg->sock_group);
	spdk_poller_unregister(&pg->poller);
	spdk_poller_unregister(&pg->nop_poller);
}

static void
initialize_iscsi_poll_group(spdk_msg_fn cpl)
{
	size_t g_num_poll_groups = spdk_env_get_last_core() + 1;

	g_spdk_iscsi.poll_group = calloc(g_num_poll_groups, sizeof(struct spdk_iscsi_poll_group));
	if (!g_spdk_iscsi.poll_group) {
		SPDK_ERRLOG("Failed to allocated iscsi poll group\n");
		iscsi_init_complete(-1);
		return;
	}

	/* Send a message to each thread and create a poll group */
	spdk_for_each_thread(iscsi_create_poll_group, NULL, cpl);
}
```

**Comment by ak-gh** [comment]
On Thu, Apr 11, 2019, 22:37 Michael Haeuptle <notifications@github.com>
wrote:

> This is not necessarily a valid defect but I'm confused by the iscsi
> socket group initialization code and it seems there's a memory leak.
>
> The function initialize_iscsi_poll_group creates a socket group for each
> core but it uses the spdk_for_each_thread() which iterates through all
> registered threads, to accomplish that.
> The poll_group is stored in an array indexed by core.
>
> I think this can lead to a memory leak since we can have multiple threads
> running on the same core.
>
You should first check if iscsi target app creates any threads other than
spdk system thread per configured core (which I guess it doesn't, so its
thread equals core assumption is correct).

Regards,
Andrey

**Comment by jimharris** [comment]
@ak-gh is correct.  Currently this code is only working because there's ever only one spdk thread per logical core.  This is an area of code that will need to reworked before we can add a smarter scheduler based on the work @benlwalker has been doing.

I'm going to close this issue.

**Comment by mhae** [comment]
Thanks for the quick reply. @jimharris I'm puzzled by "there's ever only one spdk thread per logical core". We can have many spdk threads running on a logical core, no? This code only works because no other threads have been created while the subsystem is initialized.

**Comment by jimharris** [comment]
Not currently.  There can be many pollers running on one spdk thread, but only one spdk thread per logical core.

**Comment by mhae** [comment]
Sorry, please bear with me... I'm probably confused by some of the
terminology, especially what a "logical core" is.

I've lifted the iscsi code that initializes the socket groups and from the
output below, I see multiple spdk threads running on the same core.
I believe the _sched() in the thread abstraction distributes threads across
cores in a round robin fashion every time I do a spdk_thread_create.

```
static void
create_poll_group(void *ctx)
{
        struct poll_group *pg;

        printf("*** create_poll_group: core=%d, thread name=%s\n",
spdk_env_get_current_core(), spdk_thread_get_name(spdk_get_thread()));

        pg = &g_server.poll_group[spdk_env_get_current_core()];
        if (pg->sock_group == NULL) {
                pg->core = spdk_env_get_current_core();
                STAILQ_INIT(&pg->connections);
                pg->sock_group = spdk_sock_group_create();
                assert(pg->sock_group != NULL);

                // printf("*** create_poll_group: core=%d, thread
name=%s\n", spdk_env_get_current_core(),
spdk_thread_get_name(spdk_get_thread()));

                pg->poller = spdk_poller_register(poll_group_poll, pg, 0);
        }
}

// this is called from app start...
static int
sock_listen(struct config_context *ctx)
{
        ctx->sock = spdk_sock_listen(ctx->host, ctx->port);
        if (ctx->sock == NULL) {
                SPDK_ERRLOG("Cannot create server socket\n");
                return -1;
        }

        SPDK_NOTICELOG("Listening connection on %s:%d\n", ctx->host,
ctx->port);


        // mhae

        spdk_thread_create("my-thread-1");
        spdk_thread_create("my-thread-2");

        size_t num_poll_groups = spdk_env_get_last_core() + 1;
        g_server.poll_group = calloc(num_poll_groups, sizeof(struct
poll_group));
        spdk_for_each_thread(create_poll_group, NULL,
create_poll_group_complete);
        g_server.next_core = 0;
        printf("core count=%d\n", spdk_env_get_core_count());

        g_is_running = true;

        /*
         * Start acceptor and group poller
         */

        ctx->poller_in = spdk_poller_register(acceptor, ctx,
ACCEPT_TIMEOUT_US);

        return 0;
}

```

Here's the output from the above code snippet... core 0 runs the app_thread
and my-thread-1. So I have 2 spdk_threads on the same core...
```
*** create_poll_group: core=0, thread name=app_thread
*** create_poll_group: core=1, thread name=reactor_1
*** create_poll_group: core=2, thread name=reactor_2
*** create_poll_group: core=3, thread name=reactor_3
*** create_poll_group: core=0, thread name=my-thread-1
*** create_poll_group: core=1, thread name=my-thread-2
```

**Comment by jimharris** [comment]
I should have clarified that there is only ever one SPDK thread per logical core with the applications in upstream SPDK.  The iSCSI library is not ready yet for users to create additional threads via spdk_thread_create().
