### ISSUE TITLE
bdev/bdev.c: question about spdk_bdev->required_alignment

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#753]
Hi,

The field `spdk_bdev->required_alignment`  specifies an alignment requirement for data buffers associated with an spdk_bdev_io. And this alignment is made in `spdk_bdev_io_get_buf` function, using `aligned_buf = (void *)(((uintptr_t)buf + (alignment - 1)) & ~(alignment - 1))`.

But I find that when a bdev specifies the required_alignment filed, io boundary on this bdev is also required. I haven't  figured out why optimal_io_boundary  is required here.

```
// spdk_bdev_init function
if (spdk_bdev_get_buf_align(bdev) > 1) {                                
        if (bdev->split_on_optimal_io_boundary) {                       
               bdev->optimal_io_boundary = spdk_min(bdev->optimal_io_boundary,
                                                             SPDK_BDEV_LARGE_BUF_MAX_SIZE / bdev->blocklen);
        } else {                                                        
               bdev->split_on_optimal_io_boundary = true;              
               bdev->optimal_io_boundary = SPDK_BDEV_LARGE_BUF_MAX_SIZE / bdev->blocklen;
       }                                                               
}              
```

Thanks in advance.

**Comment by lorneli** [comment]
Hi @darsto , @jimharris , @changpe1 , @pelplinski 

Sorry to bother you guys. :sweat_smile:

I trace bdev's required_alignment  feature in commit history, and  find the related [patch series](https://review.gerrithub.io/c/spdk/spdk/+/430783/9) in gerrithub. After reading the patches, I'm still a little bit confused:

I think the line `bdev->optimal_io_boundary = SPDK_BDEV_LARGE_BUF_MAX_SIZE / bdev->blocklen` (in spdk_bdev_init function) aims to use io boundary to split a required_alignment  bdev_io, whose length is larger than SPDK_BDEV_LARGE_BUF_MAX_SIZE. 

But for a read direction required_alignment  bdev_io, it calls `spdk_bdev_io_get_buf` to alloc a alignment buffer before being actually splitted. Since the length of this bdev_io is larger than LARGE_BUF_MAX_SIZE, the allocation will fail and this bdev_io will have no chance to get splitted. So this seems to  conflict with setting optimal_io_boundary for required_alignment bdev.


```
// spdk_bdev_io_submit function
if (bdev->split_on_optimal_io_boundary && _spdk_bdev_io_should_split(bdev_io)) {
        if (bdev_io->type == SPDK_BDEV_IO_TYPE_READ) {      
                // alloc alignment buffer first, then split bdev_io                
                spdk_bdev_io_get_buf(bdev_io, _spdk_bdev_io_split_get_buf_cb,
                        bdev_io->u.bdev.num_blocks * bdev_io->bdev->blocklen);
        } else {                                                            
                _spdk_bdev_io_split(NULL, bdev_io);                         
        }                                                                   
        return;                                                             
}
```

```
// spdk_bdev_io_get_buf function, allocation fails if len exceeds LARGE_BUF_MAX_SIZE
if (len + alignment > SPDK_BDEV_BUF_SIZE_WITH_MD(SPDK_BDEV_LARGE_BUF_MAX_SIZE) +
    SPDK_BDEV_POOL_ALIGNMENT) {                                         
        SPDK_ERRLOG("Length + alignment %" PRIu64 " is larger than allowed\n",
               len + alignment);                                   
        cb(bdev_io->internal.ch->channel, bdev_io, false);              
        return;                                                         
}                                                                       
````

**Comment by jimharris** [comment]
Hi @lorneli,

Currently the bdev layer is not designed to handle read I/O requests larger than SPDK_BDEV_LARGE_BUF_MAX_SIZE that have no buffer attached (requesting bdev layer to allocate the buffer).

iSCSI is the only frontend currently that requests bdev to allocate the buffer.  It restricts the size to SPDK_BDEV_LARGE_BUF_MAX_SIZE for all read I/O requests.

NVMf and vhost do not request bdev to allocate the buffer.

This could be modified to handle the case you mention.  Could you provide your use case that requires it?

Thanks,

-Jim

**Comment by optimistyzy** [comment]
@lorneli  As Jim mentioned, this is currently only used by iSCSI target to support DIF  (Data integrity field)(And it is reflected by hose bdevs which have meta data)

**Comment by lorneli** [comment]
Hi  @jimharris @optimistyzy 

Sorry for the late response. I went back to my hometown and attended a wedding last weekend.

> This  could be modified to handle the case you mention. Could you provide your use case that requires it?

To be honest, we are using nvmf and vhost target as frontend application, instead of  iSCSI target. So It's not a problem for us, that currently bdev layer doesn't handle read I/O requests larger than SPDK_BDEV_LARGE_BUF_MAX_SIZE that have no buffer attached.

It's my curiosity that drives me to launch this issue, after reading the required_alignment feature in bdev layer. I think the underlying lines from commit 092de1460ab82f2a7eba276d43514bbaa4c410b2  implies that there exists required_alignment request, whose size is larger than LARGE_BUF_MAX_SIZE. So io boundary is adopted to split this kind of request.

```
// spdk_bdev_init function
if (spdk_bdev_get_buf_align(bdev) > 1) {                                
        // .....       
        bdev->split_on_optimal_io_boundary = true;              
        bdev->optimal_io_boundary = SPDK_BDEV_LARGE_BUF_MAX_SIZE / bdev->blocklen;                                                         
} 
```

**Comment by jimharris** [comment]
Hi @lorneli,

Good question.  The primary use case for these code lines is vhost w/ aio bdev module.

Linux AIO requires buffers to be aligned on LBA boundaries.  Since vhost frontend passes buffers directly from guest VM, we have no control on alignment.  So bdev layer must double buffer these IO.  Since the bdev buffers have max size SPDK_BDEV_LARGE_BUF_MAX_SIZE, we must split on that boundary to ensure we can double buffer if the guest VM issues an I/O with buffer not aligned to LBA boundary.

I'm going to mark this issue as a question but close it.  We can continue to discuss the issue though after it is closed.

-Jim

**Comment by skypexu** [comment]
We use aio as iscsi target lun's driver, the problem still exists within version v22.05.x:
[2023-11-21 13:59:32.976780] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976790] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976800] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976809] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976819] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976829] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976839] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976848] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976857] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976866] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976876] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976889] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976898] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976908] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2023-11-21 13:59:32.976918] bdev.c:1274:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
