### ISSUE TITLE
test pool BlobFS_autotest #23520 always fail at rocksdb.sh

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#756]
please  see the test pool, that BlobFS_autotest #23520 always fail at rocksdb.sh,
it blocked many patches.

**Comment by benlwalker** [comment]
I don't know what this bug report means. If a particular Jenkins build is failing, post a link.

**Comment by benlwalker** [comment]
I think this may be the same issue: https://github.com/spdk/spdk/issues/758

I'm going to close this one.
