### ISSUE TITLE
sudo HUGEMEM=8192 scripts/setup.sh does not configure hugepage properly

### ISSUE THREAD

**Issue by amtrek** [spdk/spdk#757]
I am using the spdk off-the-shelf way,  when I tried to run the example on nvme hello_world, I have error reporting that I dont have enough hugepage space.

So I ran sudo HUGEMEM=8192 scripts/setup.sh trying to set a huge page. 

0000:5e:00.0 (8086 0a54): Active mountpoints on /dev/nvme0n1, so not binding PCI dev
0000:86:00.0 (8086 0a54): Already using the uio_pci_generic driver
0000:af:00.0 (8086 0a54): Already using the uio_pci_generic driver
0000:d8:00.0 (8086 0a54): Active mountpoints on /dev/nvme2n1, so not binding PCI dev

However, it does not seem to configure correctly. 

Here's my huge page return (grep HugePages_ /proc/meminfo)
HugePages_Total:    4096
HugePages_Free:     4096
HugePages_Rsvd:        0
HugePages_Surp:        0

When I ran the nvme/hello_world example, it's still complaining about the huge page size not enough

Starting SPDK v19.04-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Cannot obtain physical addresses: No such file or directory. Only vfio will function.
EAL: Couldn't get fd on hugepage file
EAL: Couldn't get fd on hugepage file
error allocating rte services array
EAL: FATAL: rte_service_init() failed
EAL: rte_service_init() failed
Failed to initialize DPDK
Unable to initialize SPDK env

**Comment by jimharris** [comment]
Hi @amtrek,

The "No free hugepages reported in..." message can be ignored.  It is an error message from DPDK, and unfortunate since it is confusing.  It only means there are no 1GB huge pages available.  But your 2MB pages are available - you specified 8192MB, and it is showing 4096 2MB huge pages.

Some of the other error messages about "cannot obtain physical addresses" and "couldn't get fd" indicate maybe the application is not being run as root?

-Jim

**Comment by amtrek** [comment]
Hi, good catch, however, after executing as root, I still got this similar error.

Starting SPDK v19.04-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No free hugepages reported in hugepages-2048kB
EAL: No free hugepages reported in hugepages-2048kB
EAL: No free hugepages reported in hugepages-1048576kB
EAL: FATAL: Cannot get hugepage information.
EAL: Cannot get hugepage information.
Failed to initialize DPDK
Unable to initialize SPDK env

**Comment by amtrek** [comment]
After increasing the hugepage to HUGEMEM=16384MB, the example is now working as expected. I'll close the issue. Thanks for the help, Jim.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_4258.html
