### ISSUE TITLE
Nightly test 19.01.x vs. DPDK master failing on RocksDB tests

### ISSUE THREAD

**Issue by benlwalker** [spdk/spdk#758]
https://10.102.17.104:8080/job/autotest-stable-vs-DPDK-master/changes
(Sorry - only available within Intel)

Nightly tests 54 through present failing. This is because the tests use whatever version of the RocksDB source is present in the test system. SPDK 19.04 requires an upgraded RocksDB, so the test systems were updated. But 19.01.x requires the old RocksDB, so this is failing to build.

To solve this, we either need to make RocksDB a submodule or we need to make the tests pull a specific commit on each test run.

**Comment by peluse** [comment]
I kinda like the pull option given how many submodules we already have…

**Comment by darsto** [comment]
Bug scrub: We'll make a script on jenkins to checkout a specific rocksdb version

**Comment by jimharris** [comment]
We've merged changes now that have the RocksDB tests pull a specific version of RocksDB for building.  I'd suggest we not merge those patches to 19.01.x though.  Let's just wait for 19.04 to release, then start the 19.04.x branch and change the nightly tests to test 19.04.x vs. DPDK master.

**Comment by jimharris** [comment]
These patches were merged back to v19.01.x yesterday.  Last night's SPDK stable v. DPDK master passed.
