### ISSUE TITLE
blobstore does not check for SNAPSHOT_IN_PROGRESS during dirty recovery

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#760]
If blobstore application crashes during creation of a snapshot, we need to look for and clean up any SNAPSHOT_IN_PROGRESS xattrs that are found.

Assume blob X is found with xattr SNAPSHOT_IN_PROGRESS

1) Need to find any blob with a parent snapshot ID matching blob X.  If found, set that blob's parent snapshot ID to the parent snapshot ID of blob X (breaking the dependency).
2) Delete blob X

I know we talked about this when designing clones/snapshots which is why this xattr exists.  But the recovery code didn't get added.

**Comment by Maciej-Szwed** [comment]
For the case where we find blob with a parent snapshot ID matching blob X we can finish whole process during recovery by processing forward with what is in _spdk_bs_snapshot_origblob_sync_cpl function - setting snpashot as read only, removing xattr and syncing. This way we finished snapshot process successfully.
We should remove snapshot only if there is no blob with parent pointing at blob X.

Here is code for that:
https://review.gerrithub.io/c/spdk/spdk/+/455216/
which is based on this change:
https://review.gerrithub.io/c/spdk/spdk/+/453835/

**Comment by tomzawadzki** [comment]
Bug scrub: This was fixed in patch https://review.gerrithub.io/c/spdk/spdk/+/455216/
