### ISSUE TITLE
rpc.py error when trying to get_bdevs

### ISSUE THREAD

**Issue by amtrek** [spdk/spdk#761]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

fail to get_bdevs from rpc.py
## Expected Behavior

After create hugepage via setup.py, I ran rpc.py to get block device in my system. I also tried to perform construct nvme bdev, but yield same error.

- ./rpc.py get_bdevs

-  ./rpc.py construct_nvme_bdev -b NVMe1 -t PCIe -a 0000:86:00.0

## Current Behavior

Traceback (most recent call last):
  File "/home/client/benchmark/spdk/scripts/rpc/client.py", line 46, in __init__
    self.sock.connect((addr, port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./rpc.py", line 1793, in <module>
    with rpc.client.JSONRPCClient(args.server_addr, args.port, args.timeout, log_level=getattr(logging, args.verbose.upper())) as client:
  File "/home/client/benchmark/spdk/scripts/rpc/client.py", line 49, in __init__
    "Error details: %s" % (addr, ex))
rpc.client.JSONRPCException: Error while connecting to /var/tmp/spdk.sock
Error details: [Errno -2] Name or service not known

## Steps to Reproduce

1. cd spdk
2. sudo scripts/rpc.py get_bdevs

## Context (Environment including OS version, SPDK version, etc.)

I am using ubuntu 18.04, with intel P4500
5e:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500/P4600
86:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500/P4600
af:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500/P4600
d8:00.0 Non-Volatile memory controller: Intel Corporation Express Flash NVMe P4500/P4600

**Comment by Maciej-Szwed** [comment]
Hello @amtrek ,
Have you started instance of SPDK application before running RPC command and after running setup.sh script? You can run for this purpose spdk/app/spdk_tgt/spdk_tgt binary.
In case you did it, have you noticed any errors printed on the screen by the application?

Regards,
Maciek

**Comment by amtrek** [comment]
Thank you @Maciej-Szwed  it looks like that I have not let the spdk_tgt run  at same time.
