### ISSUE TITLE
Correct way of writing large data ? Slow performance from example

### ISSUE THREAD

**Issue by marzious** [spdk/spdk#762]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Slow writing performance 
## Expected Behavior

I am trying to use spdk library to accelerate flushing large data buffer to file (SSD), in previous benchmark, I was able to use raw fstream to get write speed ~1.5G/s (Intel P4500), however, the CPU usage approach 100% during long period of sequential writing (>200G total)

By reading the document from spdk, I think it can help me reduce the CPU usage by creating zero copy buffer, and write it to file. I started with example hello_world under nvme. I created a 1GB char buffer, and replace hello world string with my buffer.

Also, I changed the size of sequence.buf to 0x4000000 (1G). I benchmark my writing performance starting from push the buffer into sequence.buf, and end at write_complete callback. 
## Current Behavior

For 1GB data, the total executing time is 2 seconds, 700ms.
## Steps to Reproduce

My hugepage size is
│HugePages_Total: 16393
│HugePages_Free: 16391
│HugePages_Rsvd: 0
│HugePages_Surp: 0
│Hugepagesize: 2048 kB

/My buffer allocation

int n = 102410241024;
buffer = (char*) malloc(n * sizeof(char));
for(int i = 0; i < n; i++)
buffer[i] = (char)(i%8 + 'a');

/allocate 1GB buffer to sequence.buf*/
sequence.buf = spdk_zmalloc(0x40000000, 0x1000, NULL, SPDK_ENV_SOCKET_ID_ANY, SPDK_MALLOC_DMA);

/flush the buffer to sequence.buf/
start = clock();
snprintf(sequence.buf, 0x1000, "%s", buffer);

This came back at about almost 3 second to write the 1GB char buffer, which seems too slow to be correct. Can anyone point me if I am wrongfully using the library ?

I do get error message said about not enough hugepage.

my execuStarting SPDK v19.04-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No free hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to 0000:af:00.0
Attached to 0000:af:00.0
Using controller INTEL SSDPEDKX040T7 (PHLF751200U44P0DGN ) with 1 namespaces.
Namespace ID: 1 size: 4000GB
Initialization complete.
INFO: using host memory buffer for IO
Time taken 2 seconds 707 millisecond

## Context (Environment including OS version, SPDK version, etc.)

On ubuntu 18.04

**Comment by jimharris** [comment]
Hi @amtrek,

Could you post more code from your benchmark?  I don't see any calls to the SPDK NVMe driver in the code that you posted.

Writing 1GB in 3 seconds could be very reasonable, depending on the I/O size and queue depth you are using.  The max throughput specified in the spec sheets will be for large sequential writes.  If the benchmark is only doing 4KB writes at a time, the throughput should be expected to be much less.

Note: You can ignore the error message about 1GB huge pages.  This is an unfortunate warning message from DPDK.  Your system has 2MB huge pages which is sufficient.

-Jim

**Comment by benlwalker** [comment]
No response, so closing out. If you'd like to continue on this issue, please re-open it.
