### ISSUE TITLE
bdev_raid: modprobe nbd failed and show "return 0" in NIGHTLY test

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#764]
When testing bdev_raid.sh, if modprobe -n nbd failed, only "modprobe: FATAL: Module nbd not found." was printed, then return 0. This looks like a passed test case.

## Expected Behavior
In this case, printing "skipping the test" is necessary.

## Current Behavior
Printed "FATAL" and "return 0".

## Possible Solution
Suggest to add "skipping" and avoid a indistinct.

## Steps to Reproduce
1. view https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly.html
2. view https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/472/archive/centos7_autotest/build.log (please search "START TEST SUITE test/bdev/bdev_raid.sh" and "# modprobe -n nbd" )

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 9e2eb8cb51a16839a54771eb842c4e3aa99b25d6

**Comment by wanghailiangx** [comment]
Posted a  patch https://review.gerrithub.io/#/c/spdk/spdk/+/451723/.

**Comment by darsto** [comment]
Patch merged. Thanks!
