### ISSUE TITLE
random builds timing out - due to NFS soft lockup

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#765]
I've seen several unit test builds that have timed out.  This is very unexpected.  Here's one example:

https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_29089.html

Note that dmesg.log shows several kernel back traces due to soft lockups in the NFS path.

**Comment by benlwalker** [comment]
Why do the test agents need NFS? Can we just install some giant HDDs?

**Comment by jimharris** [comment]
It's not just unit tests - here's a case where nightly test failed due to same failure in the nvme_autotest job:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/474/archive/nvme_autotest/index.html

Changing the title to reflect these new findings.

**Comment by jimharris** [comment]
It's not always the same VM.  The original unit test build failed on fedora_vm_5.  The more recently nightly failure was on fedora_vm_4.

**Comment by jimharris** [comment]
Ziye ran into this on one of his patches as well:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/29221/archive/unittest_autotests/index.html

**Comment by jimharris** [comment]
Here's another random failure - timing out during a build.  I suspect this is NFS related again but in this case we didn't get the dmesg:

https://10.102.17.104:8080/job/autotest-per-patch/29220/

**Comment by jimharris** [comment]
This looks promising:  https://www.spinics.net/lists/linux-nfs/msg71948.html

But not sure how we can get a kernel easily with this patch.  Still looking at other mount options, etc. that may alleviate this problem.

**Comment by jimharris** [comment]
We've disabled NFS delegations by writing 0 to /proc/sys/fs/leases-enable on the NFS server.  Let's see if this problem goes away.

**Comment by jimharris** [comment]
I haven't seen this problem come up again, so closing this issue.
