### ISSUE TITLE
DPS in SPDK

### ISSUE THREAD

**Issue by pentyala** [spdk/spdk#766]
https://github.com/spdk/spdk/issues/748#issue-431256336

Hi,

As a follow up to this issue.

Hi,
Thanks for letting me know.

Now I am using a real NVMe device in my setup with extended LBA.
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172X (rev 01)

Formatted to 520 sector size using nvme format command in ubuntu.

~/Source/spdk$ sudo nvme list
Node SN Model Namespace Usage Format FW Rev

/dev/nvme0n1 S2JRNA0J200057 Dell Express Flash NVMe PM1725 800GB SFF 1 0.00 B / 800.17 GB 512 B + 8 B KPYA8D3Q

I have successfully created a controller, namespace and I am able to connect to the controller and namespace. However, I am not getting the right format.

~/Source/spdk$ sudo nvme list
Node SN Model Namespace Usage Format FW Rev

/dev/nvme0n1 SPDK00000000000001 SPDK bdev Controller 1 800.17 GB / 800.17 GB 512 B + 0 B 19.01.2

I wanted to confirm that formatting the real NVMe ssd to 512+8 using the nvme format command is the right approach. Thanks!

**Comment by shuhei-matsumoto** [comment]
@pentyala 

Using the nvme format command is the right approach.

During SPDK running, we can know if 512 + 8 is recognized by SPDK NVMe-oF target by JSON RPC get_bdevs. SPDK NVMe CLI may not be aware of metadata yet.

**Comment by shuhei-matsumoto** [comment]
@pentyala 

You will get metadata and DIF settings of NVMe-bdev by get_bdevs RPC like as follows:

    "md_interleave": true,
    "dif_is_head_of_md": false,
    "block_size": 520,
    "md_size": 8,
    "dif_type": 1

These information will be exposed to NVMe-oF initiator by SPDK NVMe-oF target. I hope you will see the same. 

Besides, other community members or I will work on SPDK NVMe CLI by SPDK 19.07.

Thanks,
Shuhei

  {
    "num_blocks": 781422768,
    "md_interleave": true,
    "enabled_dif_check_types": {
      "reftag": false,
      "apptag": false,
      "guard": false
    },
    "supported_io_types": {
      "write_zeroes": true,
      "nvme_io": true,
      "unmap": true,
      "read": true,
      "nvme_admin": true,
      "reset": true,
      "write": true,
      "flush": true
    },
    "product_name": "NVMe disk",
    "claimed": false,
    "driver_specific": {
      "nvme": {
        "trid": {
          "traddr": "0:1:0:0",
          "trtype": "PCIe"
        },
        "ns_data": {
          "id": 1
        },
        "ctrlr_data": {
          "oacs": {
            "format": 1,
            "firmware": 1,
            "security": 1,
            "ns_manage": 0
          },
          "serial_number": "PHKE7342011U375AGN",
          "vendor_id": "0x8086",
          "firmware_revision": "E2010423",
          "model_number": "INTEL SSDPE21K375GA"
        },
        "pci_address": "0:1:0:0",
        "csts": {
          "rdy": 1,
          "cfs": 0
        },
        "vs": {
          "nvme_version": "1.0"
        }
      }
    },
    "name": "nvme0n1",
    "aliases": []
  },
  {
    "num_blocks": 781422768,
    "md_interleave": true,
    "enabled_dif_check_types": {
      "reftag": false,
      "apptag": false,
      "guard": false
    },
    "supported_io_types": {
      "write_zeroes": true,
      "nvme_io": true,
      "unmap": true,
      "read": true,
      "nvme_admin": true,
      "reset": true,
      "write": true,
      "flush": true
    },
    "name": "nvme1n1",
    "aliases": [],
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0
    },
    "driver_specific": {
      "nvme": {
        "trid": {
          "traddr": "0:82:0:0",
          "trtype": "PCIe"
        },
        "ns_data": {
          "id": 1
        },
        "ctrlr_data": {
          "oacs": {
            "format": 1,
            "firmware": 1,
            "security": 0,
            "ns_manage": 0
          },
          "serial_number": "CVFT4396003G400GGN",
          "vendor_id": "0x8086",
          "firmware_revision": "8DV101H0",
          "model_number": "INTEL SSDPE2MD400G4"
        },
        "pci_address": "0:82:0:0",
        "csts": {
          "rdy": 1,
          "cfs": 0
        },
        "vs": {
          "nvme_version": "1.0"
        }
      }
    },
    "product_name": "NVMe disk",
    "claimed": false,
    "md_size": 8,
    "dif_type": 1
  }
]

**Comment by pentyala** [comment]
Hi @shuhei-matsumoto, Thanks for letting me know that. 

I am trying to get the bdevs using the command "rpc get_bdevs". However, I could not find the "md_size" nor "dif_type" in my output. 
Here is my output.
[
  {
    "name": "Nvme1n1",
    "aliases": [],
    "product_name": "NVMe disk",
    "block_size": 512,
    "num_blocks": 1562824368,
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": true,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": true,
      "nvme_io": true
    },
    "driver_specific": {
      "nvme": {
        "pci_address": "0000:04:00.0",
        "trid": {
          "trtype": "PCIe",
          "traddr": "0000:04:00.0"
        },
        "ctrlr_data": {
          "vendor_id": "0x144d",
          "model_number": "Dell Express Flash NVMe PM1725 800GB SFF",
          "serial_number": "S2JRNA0J200057",
          "firmware_revision": "KPYA8D3Q",
          "oacs": {
            "security": 0,
            "format": 1,
            "firmware": 1,
            "ns_manage": 0
          }
        },
        "vs": {
          "nvme_version": "1.1"
        },
        "csts": {
          "rdy": 1,
          "cfs": 0
        },
        "ns_data": {
          "id": 1
        }
      }
    }
  }
]

Am I using a different version? I am using v19.01.2-pre

**Comment by changpe1** [comment]
@pentyala Maybe you can use a new SPDK version, I tested it with master SPDK branch, it works.

**Comment by pentyala** [comment]
@changpe1 Let me try it.

**Comment by pentyala** [comment]
@changpe1 

When I try to create nvme_bdev after formatting the NVMe device to (512B + 8B), I get the following error.
bdev_nvme.c: 739:nvme_ctrlr_create_bdev: *ERROR*: Bdev doesn't support metadata not intereleaved with block data
bdev_nvme.c:1617:nvme_ctrlr_create_bdevs: *NOTICE*: Failed to create bdev for namespace 1 of Nvme1
bdev_nvme.c:1622:nvme_ctrlr_create_bdevs: *NOTICE*: No bdev is created for NVMe controller Nvme1

**Comment by changpe1** [comment]
@pentyala Can you change the format of your drive? SPDK BDEV can only support extended LBA format for now, it means the 8 bytes Protection Information should followed by the data.

**Comment by pentyala** [comment]
@changpe1 Thanks for the help. That worked.
Thanks @shuhei-matsumoto
