### ISSUE TITLE
nvme_driver_init of secondary failed if primary doesn't connect any nvme ctrl

### ISSUE THREAD

**Issue by wuzhouhui** [spdk/spdk#768]
When secondary try to connect to a NVMoF/TCP target, `nvme_driver_init()` of secondary failed if primary doesn't connect any nvme controller

## Expected Behavior

RPC method `construct_nvme_bdev` of secondary succeeds if we are trying connect to NVMoF/TCP target, instead of local PCIe.

## Current Behavior

RPC method `construct_nvme_bdev` of secondary failed.

## Possible Solution
Always initialize `g_spdk_nvme_driver` or do not check it if we are constructing nvme bdev that based on remote SSD.

## Steps to Reproduce
1. Start a NVMoF/TCP target in remote host, and export a malloc bdev via NVMoF/TCP
2. In local host, do
  2.1 Start primary SPDK instance by `./nvmf_tgt -i 0 -r /var/tmp/spdk.sock.p`
  2.2 Start secondary SPDK instance by `./nvmf_tgt -i 0 -r /var/tmp/spdk.sock`
  2.3 For secondary SPDK instance, construct a nvme_bdev, that connect to NVMoF/TCP target

Then, we'll see that RPC method `construct_nvme_bdev` failed, and log says:
```
nvme.c: 360:nvme_driver_init: *ERROR*: primary process is not started yet
nvme.c: 360:nvme_driver_init: *ERROR*: primary process is not started yet
bdev_nvme.c:1314:spdk_bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: [snip])
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK: 38527b07
OS: 7.3
Kernel: 3.10.0-327.el7.x86_64

**Comment by changpe1** [comment]
@wuzhouhui you can start two nvmf_target instances both for primary process, and what's the reason you start another nvmf_target using the secondary process?

**Comment by wuzhouhui** [comment]
> @wuzhouhui you can start two nvmf_target instances both for primary process, and what's the reason you start another nvmf_target using the secondary process?

Not particular reason, just encounter this issue accidentally when I forget add SSD in primary's configuration file.

**Comment by darsto** [comment]
Fix:
https://review.gerrithub.io/c/spdk/spdk/+/452043 nvme: allow manually initializing the NVMe driver

**Comment by changpe1** [comment]
[Bug Scrub] There is no usage scenario for this case now, we are going to close this issue, and we can add the task to trello card if got new requirement.
