### ISSUE TITLE
SPDK's identify reports zero (0) number of namespaces against a fabric target

### ISSUE THREAD

**Issue by lhoswdev** [spdk/spdk#769]
Started up `nvmf_tgt` with a conf file that specified two malloc bdev namespaces.   The SPDK's `identify`, however, consistently reports the number of namespaces as zero (0).   I am, however, able to run SPDK's `perf` against the target to one or both of the malloc bdevs just fine.

## Expected Behavior

I would expect to see two (2) namespaces.

## Current Behavior

`identify` output chunk:
```
...
NVM Command Set Attributes
==========================
Submission Queue Entry Size
  Max:                       1
  Min:                       1
Completion Queue Entry Size
  Max:                       1
  Min:                       1
Number of Namespaces:        0
...
```

## Steps to Reproduce

1.  Configure system with an RDMA-supported NIC/IB.
2.  Launch `nvmf_tgt` with config file  (`-c` *file.conf*) :
```
[Global]
[Malloc]
  NumberOfLuns 4
  LunSizeInMB 64
[Nvmf]
  AcceptorPollRate 10000
[Transport]
  Type RDMA
[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.10.2:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 8
  Namespace Malloc0 1
  Namespace Malloc1 2
```

3.  Run `identify` against the target, e.g.:
```
identify -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.10.2 trsvcid:4420'
```
and check the output for:
```
Number of Namespaces:        0
```

## Context (Environment including OS version, SPDK version, etc.)

Observed this on SPDK master (hash 6b48e74) as well as previous versions of the SPDK, e.g. 18.10.2.  Running Oracle Linux with a kernel version of 4.14.14.

**Comment by changpe1** [comment]
@lhoswdev Thank you Lance, this is a bug, I will take a look.

**Comment by changpe1** [comment]
@lhoswdev Hi Lance, this is not a bug, because for your parameter -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.10.2 trsvcid:4420', actually SPDK will use discovery controller as the default subnqn, so you can  use 'trtype:RDMA adrfam:IPv4 traddr:192.168.10.2 trsvcid:4420 subnqn:nqn.2016-06.io.spdk:cnode1'  instead.  Discovery controller in NVMoF doesn't contain valid namespaces.

**Comment by lhoswdev** [comment]
Awesome!   Thank you so much!
