### ISSUE TITLE
Failed to link spdk static library 

### ISSUE THREAD

**Issue by amtrek** [spdk/spdk#770]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Hi, I am trying to use spdk in our application, so we worked out an example to see if we can properly use spdk through static libraries built by default.  This is my CMakeList to include the header, and link the library in the build folder.

```
project(helloworld)
cmake_minimum_required(VERSION 3.1)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -fno-strict-aliasing -march=native -m64 -D_GNU_SOURCE -fPIC -fstack-protector -DNDEBUG")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-z,relro,-z,now -Wl,-z,noexecstack")

include_directories(/home/gtk/spdk/include)

link_directories(/home/gtk/spdk/build/lib)

link_libraries(spdk_app_rpc)
link_libraries(spdk_bdev)
link_libraries(spdk_bdev_aio)
link_libraries(spdk_bdev_error)
link_libraries(spdk_bdev_gpt)
link_libraries(spdk_bdev_lvol)
link_libraries(spdk_bdev_malloc)
link_libraries(spdk_bdev_null)
link_libraries(spdk_bdev_nvme)
link_libraries(spdk_bdev_passthru)
link_libraries(spdk_bdev_raid)
link_libraries(spdk_bdev_rpc)
link_libraries(spdk_bdev_split)
link_libraries(spdk_bdev_virtio)
link_libraries(spdk_blob)
link_libraries(spdk_blob_bdev)
link_libraries(spdk_blobfs)
link_libraries(spdk_conf)
link_libraries(spdk_copy)
link_libraries(spdk_copy_ioat)
link_libraries(spdk_event)
link_libraries(spdk_event_copy)
link_libraries(spdk_event_iscsi)
link_libraries(spdk_event_nbd)
link_libraries(spdk_event_net)
link_libraries(spdk_event_nvmf)
link_libraries(spdk_event_scsi)
link_libraries(spdk_event_vhost)
link_libraries(spdk_ioat)
link_libraries(spdk_iscsi)
link_libraries(spdk_json)
link_libraries(spdk_jsonrpc)
link_libraries(spdk_log)
link_libraries(spdk_log_rpc)
link_libraries(spdk_lvol)
link_libraries(spdk_nbd)
link_libraries(spdk_net)
link_libraries(spdk_notify)
link_libraries(spdk_nvme)
link_libraries(spdk_nvmf)
link_libraries(spdk_rpc)
link_libraries(spdk_rte_vhost)
link_libraries(spdk_scsi)
link_libraries(spdk_sock)
link_libraries(spdk_sock_posix)
link_libraries(spdk_thread)
link_libraries(spdk_trace)
link_libraries(spdk_trace_rpc)
link_libraries(spdk_util)
link_libraries(spdk_ut_mock)
link_libraries(spdk_vhost)
link_libraries(spdk_virtio)
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
link_libraries(Threads::Threads)

SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)
aux_source_directory(/home/gtk/spdk/examples/ioat/cpp/src  SRC_LIST)
add_executable(${PROJECT_NAME} ${SRC_LIST})
```

To test the linkage, I wrote a  cpp file. ( I think

```
extern "C" {
#include "spdk/stdinc.h"
#include "spdk/ioat.h"
#include "spdk/nvme.h"
#include "spdk/string.h"
#include "spdk/env.h"
}
int main()
{
    int rc;
    struct spdk_env_opts opts;
    spdk_env_opts_init(&opts);

    return 0;
}

```
## Expected Behavior
Correctly compiled & find spdk_env_opts_init in linked library

## Current Behavior
undefined reference spdk_env_opts while make.

```
[ 50%] Building CXX object CMakeFiles/helloworld.dir/src/main.cpp.o
[100%] Linking CXX executable helloworld
CMakeFiles/helloworld.dir/src/main.cpp.o: In function `main':
main.cpp:(.text+0x5e): undefined reference to `spdk_env_opts_init'
collect2: error: ld returned 1 exit status
CMakeFiles/helloworld.dir/build.make:94: recipe for target 'helloworld' failed
make[2]: *** [helloworld] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/helloworld.dir/all' failed
make[1]: *** [CMakeFiles/helloworld.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

## Possible Solution
I have seen someone mention similar error in previous issue : 
https://github.com/spdk/spdk/issues/416

however, I do not see a $(LINK_C) in the example makefile. If someone can help point out how to properly link these static libraries, will be much appreciated. FYI, I build the  

## Context (Environment including OS version, SPDK version, etc.)

We are running with ubuntu 18.04

**Comment by jimharris** [comment]
Hi @amtrek,

I don't see spdk_env_dpdk in the list of link_libraries directives.  Could you add it and report if it fixes this problem?

Thanks,

-Jim

**Comment by amtrek** [comment]
Hi, Jim:
Thanks for reply, after adding the spdk_env_dpdk, I am still getting same error.

**Comment by jimharris** [comment]
Can you post the full command line for the link stage for your executable?

Thanks,

-Jim

**Comment by amtrek** [comment]
#My new CMakeList.txt
project(helloworld)
cmake_minimum_required(VERSION 3.1)
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -fno-strict-aliasing -march=native -m64 -D_GNU_SOURCE -fPIC -fstack-protector -DNDEBUG")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-z,relro,-z,now -Wl,-z,noexecstack")

include_directories(/home/gtk/spdk/include)

link_directories(/home/gtk/spdk/build/lib)

link_libraries(spdk_app_rpc)
link_libraries(spdk_env_dpdk)
link_libraries(spdk_bdev)
link_libraries(spdk_bdev_aio)
link_libraries(spdk_bdev_error)
link_libraries(spdk_bdev_gpt)
link_libraries(spdk_bdev_lvol)
link_libraries(spdk_bdev_malloc)
link_libraries(spdk_bdev_null)
link_libraries(spdk_bdev_nvme)
link_libraries(spdk_bdev_passthru)
link_libraries(spdk_bdev_raid)
link_libraries(spdk_bdev_rpc)
link_libraries(spdk_bdev_split)
link_libraries(spdk_bdev_virtio)
link_libraries(spdk_blob)
link_libraries(spdk_blob_bdev)
link_libraries(spdk_blobfs)
link_libraries(spdk_conf)
link_libraries(spdk_copy)
link_libraries(spdk_copy_ioat)
link_libraries(spdk_event)
link_libraries(spdk_event_copy)
link_libraries(spdk_event_iscsi)
link_libraries(spdk_event_nbd)
link_libraries(spdk_event_net)
link_libraries(spdk_event_nvmf)
link_libraries(spdk_event_scsi)
link_libraries(spdk_event_vhost)
link_libraries(spdk_ioat)
link_libraries(spdk_iscsi)
link_libraries(spdk_json)
link_libraries(spdk_jsonrpc)
link_libraries(spdk_log)
link_libraries(spdk_log_rpc)
link_libraries(spdk_lvol)
link_libraries(spdk_nbd)
link_libraries(spdk_net)
link_libraries(spdk_notify)
link_libraries(spdk_nvme)
link_libraries(spdk_nvmf)
link_libraries(spdk_rpc)
link_libraries(spdk_rte_vhost)
link_libraries(spdk_scsi)
link_libraries(spdk_sock)
link_libraries(spdk_sock_posix)
link_libraries(spdk_thread)
link_libraries(spdk_trace)
link_libraries(spdk_trace_rpc)
link_libraries(spdk_util)
link_libraries(spdk_ut_mock)
link_libraries(spdk_vhost)
link_libraries(spdk_virtio)



set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
link_libraries(Threads::Threads)

SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

aux_source_directory(/home/gtk/spdk/examples/ioat/cpp/src  SRC_LIST)
add_executable(${PROJECT_NAME} ${SRC_LIST})


Here's my steps:
mkdir build && cd build
cmake .. 
#output for cmake:

server@sever-1-18041:~/gtk/spdk/examples/ioat/cpp/build$ cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gtk/spdk/examples/ioat/cpp/build

make
#output of make:
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(init.o): In function `spdk_env_init':
/home/gtk/spdk/lib/env_dpdk/init.c:429: undefined reference to `rte_eal_init'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(memory.o): In function `spdk_vfio_enabled':
/home/gtk/spdk/lib/env_dpdk/memory.c:1091: undefined reference to `rte_vfio_is_enabled'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(memory.o): In function `spdk_vfio_noiommu_enabled':
/home/gtk/spdk/lib/env_dpdk/memory.c:1118: undefined reference to `rte_vfio_noiommu_is_enabled'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(memory.o): In function `memory_hotplug_cb':
/home/gtk/spdk/lib/env_dpdk/memory.c:716: undefined reference to `rte_mem_virt2memseg'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(memory.o): In function `spdk_mem_map_init':
/home/gtk/spdk/lib/env_dpdk/memory.c:749: undefined reference to `rte_mem_event_callback_register'
/home/gtk/spdk/lib/env_dpdk/memory.c:750: undefined reference to `rte_memseg_contig_walk'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(memory.o): In function `vtophys_get_paddr_memseg':
/home/gtk/spdk/lib/env_dpdk/memory.c:896: undefined reference to `rte_mem_virt2memseg'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(memory.o): In function `vtophys_get_paddr_pagemap':
/home/gtk/spdk/lib/env_dpdk/memory.c:937: undefined reference to `rte_mem_virt2iova'
/home/gtk/spdk/lib/env_dpdk/memory.c:945: undefined reference to `rte_mem_virt2iova'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_cfg_write_rte':
/home/gtk/spdk/lib/env_dpdk/pci.c:91: undefined reference to `rte_pci_write_config'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_cfg_read_rte':
/home/gtk/spdk/lib/env_dpdk/pci.c:77: undefined reference to `rte_pci_read_config'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_detach_rte_cb':
/home/gtk/spdk/lib/env_dpdk/pci.c:111: undefined reference to `rte_eal_hotplug_remove'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_pci_init':
/home/gtk/spdk/lib/env_dpdk/pci.c:196: undefined reference to `rte_pci_register'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_pci_enumerate':
/home/gtk/spdk/lib/env_dpdk/pci.c:418: undefined reference to `rte_bus_scan'
/home/gtk/spdk/lib/env_dpdk/pci.c:418: undefined reference to `rte_bus_probe'
/home/gtk/spdk/lib/env_dpdk/pci.c:412: undefined reference to `rte_pci_register'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_pci_fini':
/home/gtk/spdk/lib/env_dpdk/pci.c:223: undefined reference to `rte_dev_event_callback_unregister'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_pci_device_attach':
/home/gtk/spdk/lib/env_dpdk/pci.c:360: undefined reference to `rte_eal_hotplug_add'
/home/gtk/spdk/lib/env_dpdk/pci.c:350: undefined reference to `rte_pci_register'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_detach_rte':
/home/gtk/spdk/lib/env_dpdk/pci.c:126: undefined reference to `rte_eal_alarm_set'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(pci.o): In function `spdk_pci_init':
/home/gtk/spdk/lib/env_dpdk/pci.c:203: undefined reference to `rte_dev_event_callback_register'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_malloc':
/home/gtk/spdk/lib/env_dpdk/env.c:65: undefined reference to `rte_malloc_socket'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `virt_to_phys':
/home/gtk/spdk/lib/env_dpdk/env.c:50: undefined reference to `rte_malloc_virt2iova'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_dma_realloc':
/home/gtk/spdk/lib/env_dpdk/env.c:124: undefined reference to `rte_realloc'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `virt_to_phys':
/home/gtk/spdk/lib/env_dpdk/env.c:50: undefined reference to `rte_malloc_virt2iova'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_memzone_reserve_aligned':
/home/gtk/spdk/lib/env_dpdk/env.c:157: undefined reference to `rte_memzone_reserve_aligned'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_memzone_lookup':
/home/gtk/spdk/lib/env_dpdk/env.c:177: undefined reference to `rte_memzone_lookup'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_memzone_free':
/home/gtk/spdk/lib/env_dpdk/env.c:189: undefined reference to `rte_memzone_lookup'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_lcore_count':
/home/gtk/spdk/dpdk/build/include/rte_lcore.h:98: undefined reference to `rte_eal_get_configuration'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_mempool_create_ctor':
/home/gtk/spdk/lib/env_dpdk/env.c:226: undefined reference to `rte_mempool_create'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_lcore_id':
/home/gtk/spdk/dpdk/build/include/rte_lcore.h:74: undefined reference to `per_lcore__lcore_id'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_ops_dequeue_bulk':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:657: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:657: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_get_ops':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:620: undefined reference to `__rte_panic'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_lcore_id':
/home/gtk/spdk/dpdk/build/include/rte_lcore.h:74: undefined reference to `per_lcore__lcore_id'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_ops_dequeue_bulk':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:657: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:657: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_get_ops':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:620: undefined reference to `__rte_panic'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_lcore_id':
/home/gtk/spdk/dpdk/build/include/rte_lcore.h:74: undefined reference to `per_lcore__lcore_id'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_ops_enqueue_bulk':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:704: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:704: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_get_ops':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:620: undefined reference to `__rte_panic'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_lcore_id':
/home/gtk/spdk/dpdk/build/include/rte_lcore.h:74: undefined reference to `per_lcore__lcore_id'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_ops_enqueue_bulk':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:704: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:704: undefined reference to `rte_mempool_ops_table'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_mempool_get_ops':
/home/gtk/spdk/dpdk/build/include/rte_mempool.h:620: undefined reference to `__rte_panic'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_mempool_count':
/home/gtk/spdk/lib/env_dpdk/env.c:288: undefined reference to `rte_mempool_avail_count'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_process_is_primary':
/home/gtk/spdk/lib/env_dpdk/env.c:294: undefined reference to `rte_eal_process_type'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_rdtsc':
/home/gtk/spdk/dpdk/build/include/rte_cycles.h:36: undefined reference to `rte_cycles_vmware_tsc_map'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_delay_us':
/home/gtk/spdk/lib/env_dpdk/env.c:309: undefined reference to `rte_delay_us'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_unaffinitize_thread':
/home/gtk/spdk/lib/env_dpdk/env.c:332: undefined reference to `rte_thread_set_affinity'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_call_unaffinitized':
/home/gtk/spdk/lib/env_dpdk/env.c:345: undefined reference to `rte_thread_get_affinity'
/home/gtk/spdk/lib/env_dpdk/env.c:351: undefined reference to `rte_thread_set_affinity'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_ring_create':
/home/gtk/spdk/lib/env_dpdk/env.c:380: undefined reference to `rte_ring_create'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_realloc':
/home/gtk/spdk/lib/env_dpdk/env.c:88: undefined reference to `rte_realloc'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_free':
/home/gtk/spdk/lib/env_dpdk/env.c:94: undefined reference to `rte_free'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_memzone_free':
/home/gtk/spdk/lib/env_dpdk/env.c:192: undefined reference to `rte_memzone_free'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_memzone_dump':
/home/gtk/spdk/lib/env_dpdk/env.c:201: undefined reference to `rte_memzone_dump'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_mempool_free':
/home/gtk/spdk/lib/env_dpdk/env.c:251: undefined reference to `rte_mempool_free'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `rte_get_timer_hz':
/home/gtk/spdk/dpdk/build/include/generic/rte_cycles.h:122: undefined reference to `rte_get_tsc_hz'
/home/gtk/spdk/build/lib/libspdk_env_dpdk.a(env.o): In function `spdk_ring_free':
/home/gtk/spdk/lib/env_dpdk/env.c:386: undefined reference to `rte_ring_free'
collect2: error: ld returned 1 exit status
CMakeFiles/helloworld.dir/build.make:94: recipe for target 'helloworld' failed
make[2]: *** [helloworld] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/helloworld.dir/all' failed
make[1]: *** [CMakeFiles/helloworld.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jimharris** [comment]
Hi @amtrek,

I don't see the command line for the linker.  I only see the output from make.

-Jim

**Comment by amtrek** [comment]
Hi, @jimharris 

sorry for the delay. The command line make is 
gtk@gtk-1-18041:~/gtk/spdk/examples/ioat/cpp/build$ make

**Comment by jimharris** [comment]
Hi @amtrek,

No - I need the command line for the linker.  Not for make.  See below for what it looks like for spdk_tgt when using the SPDK in-tree build environment.  You should have a way to do something similar with your environment.  Somewhere, the linker is getting called.  We need to see what the linker command line is, to confirm that the libraries are being correctly specified.

Thanks,

-Jim


cc -o spdk_tgt  -Wl,-z,relro,-z,now -Wl,-z,noexecstack -fuse-ld=bfd -fsanitize=address -pthread spdk_tgt.o  -L/home/jrharri1/git/spdk/build/lib -Wl,--whole-archive -lspdk_bdev_lvol -lspdk_blobfs -lspdk_blob -lspdk_blob_bdev -lspdk_lvol -lspdk_bdev_malloc -lspdk_bdev_null -lspdk_bdev_nvme -lspdk_nvme -lspdk_bdev_passthru -lspdk_bdev_error -lspdk_bdev_gpt -lspdk_bdev_split -lspdk_bdev_raid -lspdk_bdev_aio -lspdk_bdev_virtio -lspdk_virtio -lspdk_copy_ioat -lspdk_ioat -lspdk_sock_posix -lspdk_vhost -lspdk_rte_vhost -lspdk_event_vhost -lspdk_event_bdev -lspdk_event_copy -lspdk_event_iscsi -lspdk_event_net -lspdk_event_scsi -lspdk_event_nvmf -lspdk_event -lspdk_nvmf -lspdk_trace -lspdk_log -lspdk_conf -lspdk_thread -lspdk_util -lspdk_bdev -lspdk_iscsi -lspdk_scsi -lspdk_copy -lspdk_rpc -lspdk_jsonrpc -lspdk_json -lspdk_app_rpc -lspdk_log_rpc -lspdk_trace_rpc -lspdk_bdev_rpc -lspdk_net -lspdk_sock -lspdk_event_nbd -lspdk_nbd -Wl,--no-whole-archive /home/jrharri1/git/spdk/build/lib/libspdk_env_dpdk.a -Wl,--whole-archive /home/jrharri1/git/spdk/dpdk/build/lib/librte_eal.a /home/jrharri1/git/spdk/dpdk/build/lib/librte_mempool.a /home/jrharri1/git/spdk/dpdk/build/lib/librte_ring.a /home/jrharri1/git/spdk/dpdk/build/lib/librte_mempool_ring.a /home/jrharri1/git/spdk/dpdk/build/lib/librte_pci.a /home/jrharri1/git/spdk/dpdk/build/lib/librte_bus_pci.a /home/jrharri1/git/spdk/dpdk/build/lib/librte_kvargs.a -Wl,--no-whole-archive -lnuma -ldl -L/home/jrharri1/git/spdk/isa-l/.libs -lisal -lrt -luuid -lcrypto -laio

**Comment by amtrek** [comment]
Hi, @jimharris 
does this looks like what you are looking for ?
make[2]: Entering directory '/home/gtk/spdk/examples/ioat/cpp/build'
[ 50%] Building CXX object CMakeFiles/helloworld.dir/src/main.cpp.o
/usr/bin/c++   -I/home/gtk/spdk/include  -std=c++14 -fno-strict-aliasing -march=native -m64 -D_GNU_SOURCE -fPIC -fstack-protector -DNDEBUG   -pthread -o CMakeFiles/helloworld.dir/src/main.cpp.o -c /home/gtk/spdk/examples/ioat/cpp/src/main.cpp
[100%] Linking CXX executable helloworld
/usr/bin/cmake -E cmake_link_script CMakeFiles/helloworld.dir/link.txt --verbose=1
/usr/bin/c++   -std=c++14 -fno-strict-aliasing -march=native -m64 -D_GNU_SOURCE -fPIC -fstack-protector -DNDEBUG   -Wl,-z,relro,-z,now -Wl,-z,noexecstack -rdynamic CMakeFiles/helloworld.dir/src/main.cpp.o  -o helloworld  -L/home/gtk/spdk/build/lib -Wl,-rpath,/ho
me/gtk/spdk/build/lib -lspdk_env_dpdk -lspdk_app_rpc -lspdk_bdev -lspdk_bdev_aio -lspdk_bdev_error -lspdk_bdev_gpt -lspdk_bdev_lvol -lspdk_bdev_malloc -lspdk_bdev_null -lspdk_bdev_nvme -lspdk_bdev_passthru -lspdk_bdev_raid -lspdk_bdev_rpc -lspdk_bdev_split -lspd
k_bdev_virtio -lspdk_blob -lspdk_blob_bdev -lspdk_blobfs -lspdk_conf -lspdk_copy -lspdk_copy_ioat -lspdk_event -lspdk_event_copy -lspdk_event_iscsi -lspdk_event_nbd -lspdk_event_net -lspdk_event_nvmf -lspdk_event_scsi -lspdk_event_vhost -lspdk_ioat -lspdk_iscsi -lspdk_jso
n -lspdk_jsonrpc -lspdk_log -lspdk_log_rpc -lspdk_lvol -lspdk_nbd -lspdk_net -lspdk_notify -lspdk_nvme -lspdk_nvmf -lspdk_rpc -lspdk_rte_vhost -lspdk_scsi -lspdk_sock -lspdk_sock_posix -lspdk_thread -lspdk_trace -lspdk_trace_rpc -lspdk_util -lspdk_ut_mock -lspdk_vhost -ls
pdk_virtio -pthread

**Comment by jimharris** [comment]
Thanks @amtrek.  This is what I was looking for.

I just looked at your latest error messages.  They are actually different than originally.  I no longer see the spdk_env_opts_init failure - now it is rte_ related link failures.  This is because the DPDK libraries are not being linked in.

You can look at lib/env_dpdk/env.mk to get an idea of which ones you need to link.

-Jim
