### ISSUE TITLE
nvmf fio tests show disk stats null

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#771]
All nvmf fio tests show disk stats null: **"ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%".**
But iscsi fio tests show disk stats normal: like this "sdb: ios=686/672, merge=0/0, ticks=13399/61685, in_queue=76298, util=57.84%".
This is in this case Per-patch and NIGHTLY tests.
While I tested nvmf fio on local severs, found "nvmf pcie" shows disk stats normal, "nvmf rdma" shows disk stats null.

Logs in NIGHTLY tests like this:
```
 07:13:10	# /var/jenkins/workspace/NVMeOF_tests/nvmf_autotest/spdk/scripts/fio.py nvmf 4096 1 randwrite 1 verify
......
Run status group 0 (all jobs):
   READ: bw=88.5MiB/s (92.8MB/s), 88.5MiB/s-88.5MiB/s (92.8MB/s-92.8MB/s), io=41.1MiB (43.1MB), run=465-465msec
  WRITE: bw=186MiB/s (195MB/s), 60.8MiB/s-119MiB/s (63.7MB/s-125MB/s), io=186MiB (195MB), run=537-1002msec

Disk stats (read/write):
  nvme0n1: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme0n2: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
  nvme0n3: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%
FIO completed with code 0
```

## Expected Behavior
All nvmf fio tests show disk stats normal.

## Current Behavior
All nvmf fio tests show disk stats null.

## Possible Solution
Please check if fio run in selected nvme ssds.

## Steps to Reproduce
1. view iscsi fio log:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/471/archive/iscsi_autotest/build.log ( search "Disk stats (read/write)" )
2. view nvmf fio log:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/471/archive/nvmf_autotest/build.log ( search "Disk stats (read/write)" )

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 5a484d4ab82fbe2b492a4eae6114396df23711ee

**Comment by glodfish-zg** [comment]
@wanghailiangx 
I think it's not the SPDK issue.
I find fio tool use the /sys/block/nvme1n1/stat to count disk state. But the values in /sys/block/nvme1n1 are always 0 if we use NVMe connection cmd to connect another machine, and the real values seem in the /sys/block/nvme1cXn1/stat. And if we use NVMe connection cmd to connect itself that OS will not create /sys/block/nvme1cXn1, the real values are in /sys/block/nvme1n1/stat.

**Comment by jimharris** [comment]
Closing this issue based on Jin's input.  Also marking it as 3rd party issue since it's an fio issue.
