### ISSUE TITLE
SPDK reported error while running fio randwrite job to test compression bdev of nvmf target

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#773]
## Steps to Reproduce
1. run spdk nvmf target with latest codes(I used commit ee430f97b022376986dc59d65909a1e59c53880d), the dpdk and ISA-l are default source codes in spdk repository. The config file are as below:
```
[Global]
[Bdev]
[Malloc]
  NumberOfLuns 8
  LunSizeInMB 64

[Nvmf]
  AcceptorPollRate 10000

[Transport]
  Type RDMA

[Nvme]
  TransportID "trtype:PCIe traddr:0000:60:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:6b:00.0" Nvme1
  TransportID "trtype:PCIe traddr:0000:b4:00.0" Nvme2
  TransportID "trtype:PCIe traddr:0000:b5:00.0" Nvme3
  TransportID "trtype:PCIe traddr:0000:bb:00.0" Nvme4
  TransportID "trtype:PCIe traddr:0000:bc:00.0" Nvme5
  RetryCount 4
  
  TimeoutUsec 0
  ActionOnTimeout None
  AdminPollRate 100000
  IOPollRate 0
  HotplugEnable No
```

2. run RPC command to create compression bdev and subsystem.
```

./scripts/rpc.py construct_compress_bdev -b Nvme0n1 -p /tmp/ -d compress_isal
./scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 "COMP_Nvme0n1"
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.123.11 -s 4420
```

3. In host machine, use following command to connect to the nvmf subsystem.
`nvme connect -n nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.123.11 -s 4420
` 
4. run fio job to test the /dev/nvme0n1 which is SPDK nvmf target devices. The job file is as below:

```
[global]
thread=1
rw=randwrite
runtime=1200
ramp_time=5
time_based=1
ioengine=libaio
norandommap=1
direct=1
bs=4096
invalidate=1
iodepth=128
numjobs=1
group_reporting=1

[job0]
filename=/dev/nvme0n1

```
## Expected Behavior
fio finished successfully.

## Current Behavior
After more than ten minutes running, spdk reported following error:
```
process_isal_deflate(): Input mbuf(s) not big enough.

vbdev_compress.c: 370:comp_dev_poller: *ERROR*: deque status 2

```
And fio finished with following error:

```
fio: io_u error on file /dev/nvme0n1: Input/output error: write offset=1133995032576, buflen=4096
fio: pid=36062, err=5/file:io_u.c:1833, func=io_u error, error=Input/output error

```

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit:  ee430f97b022376986dc59d65909a1e59c53880d

**Comment by liang2yan** [comment]
If running fio longer, the spdk nvmf target can't be killed by Ctrlr+C method.

**Comment by jimharris** [comment]
Assigning to @peluse.  This could be a problem in libreduce (not the bdev module) though.

**Comment by peluse** [comment]
So I ran this on master just no with your fio file but in loopback and with only one nvme and it worked fine. The error in your output is maybe something I just didn't hit for some reason but if you could try this patch https://review.gerrithub.io/c/spdk/spdk/+/454806 that would be great.  It's mainly UT but in adding that UT I noticed that I was storing a - value for an error from compressdev API into a unit and passing that to reduce so if you really did get an error on the dpdk side, looks like you did, we would not have handled it well to say the least.  This code will just store the data uncompressed.  Later we might try to get smarter with errors (retry with different size buffer or something) but for now this will hopefully give you functionality.   If it does not work can you please try with one nvme device in nvmef loopback?

**Comment by peluse** [comment]
oh geeze, I just ran with the patch I suggested and segafulted.  Let me see what's up with that first...

**Comment by peluse** [comment]
OK, fixed the issue with the suggested patch above.  Please try https://review.gerrithub.io/c/spdk/spdk/+/455019/1 and let me know how it goes.  Thank You!

**Comment by peluse** [comment]
BTW with that patch I'm about 15 min into your 20 min test, so far so good....

**Comment by liang2yan** [comment]
Just tried your patch series, issue can't be reproduced. after patches merged, I will try again.

**Comment by peluse** [comment]
Great news, thanks!

**Comment by darsto** [comment]
Fix merged, closing. Thanks for reporting!
