### ISSUE TITLE
SPDK FTL: error address translation from ftl ppa to nvme lba

### ISSUE THREAD

**Issue by zy-tough** [spdk/spdk#774]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

SPDK FTL translates on-disk address defined as _struct ftl_ppa {...}_ to the nvme block address defined as _uint64_t_ in Function _ftl_ppa_addr_pack_ before submitting nvme read/write/erase commands to the open-channel SSD.

The translation is implemented by shifting bit fields in _struct ftl_ppa {...}_. However, the shifting is limited by the length of each bit filed, so wrong nvme block addresses are obtained.

## Expected Behavior

The address translation of Function _ftl_ppa_addr_pack_ should return the right address.

## Current Behavior

For example, the ftl write pointer _wptr->ppa_ is 100000100000000, but it is translated to 1010000 (used as the nvme lba). Then, the nvme completion reports an error _LBA OUT OF RANGE_ and the write fails.

Function _ftl_ppa_addr_pack_ is currently defined as follows.

static inline uint64_t
ftl_ppa_addr_pack(const struct spdk_ftl_dev *dev, struct ftl_ppa ppa)
{
    return (ppa.lbk << dev->ppaf.lbk_offset) |
               (ppa.chk << dev->ppaf.chk_offset) |
               (ppa.pu  << dev->ppaf.pu_offset) |
               (ppa.grp << dev->ppaf.grp_offset);
}

## Possible Solution

Assign the value of each bit field in _struct ftl_ppa {...}_ to a _uint64_t_ variable and then perform address translation by shifting _uint64_t_ variables.

static inline uint64_t
ftl_ppa_addr_pack(const struct spdk_ftl_dev *dev, struct ftl_ppa ppa)
{
    uint64_t lbk, chk, pu, grp;

    lbk = ppa.lbk;
    chk = ppa.chk;
    pu = ppa.pu;
    grp = ppa.grp;

    return (lbk << dev->ppaf.lbk_offset) |
               (chk << dev->ppaf.chk_offset) |
               (pu  << dev->ppaf.pu_offset) |
               (grp << dev->ppaf.grp_offset);
}

## Steps to Reproduce

Print the input address and returned address of Function _ftl_ppa_addr_pack_.

**Comment by yidong0635** [comment]
@zy-tough, Can you try to submit a patch on  github? please refer to :https://spdk.io/development/

**Comment by ksztyber** [comment]
Fix pushed by @mmkayPL https://review.gerrithub.io/c/spdk/spdk/+/457114

**Comment by darsto** [comment]
The fix was merged over 2 weeks ago. Closing.
