### ISSUE TITLE
rpc get_bdevs_iostat returns array with entries which are not of the same "type"

### ISSUE THREAD

**Issue by jkryl** [spdk/spdk#775]
Although that it is possible to return arbitrary entries in JSON array which have nothing in common (for example `[1, "string", {"key": "val"}]`) it is not a good practise, because it makes the api unintuitive and more difficult to parse. As an example when parsing array of objects in rust from JSON with serde deserializer, it is necessary that all entries share common set of properties, otherwise the parser fails because they can't be mapped to the same type. There are workarounds for that, however clean rpc iface design would have been better.

Example of get_bdevs_iostat reply:
```
[
  {
    "tick_rate": 2194948760
  },
  {
    "name": "Pandora0",
    "bytes_read": 36864,
    "num_read_ops": 2,
    "bytes_written": 0,
    "num_write_ops": 0,
    "bytes_unmapped": 0,
    "num_unmap_ops": 0,
    "read_latency_ticks": 4337498,
    "write_latency_ticks": 0,
    "unmap_latency_ticks": 0
  },
  {
    "name": "Pandora1",
    "bytes_read": 36864,
    "num_read_ops": 2,
    "bytes_written": 0,
    "num_write_ops": 0,
    "bytes_unmapped": 0,
    "num_unmap_ops": 0,
    "read_latency_ticks": 60007928,
    "write_latency_ticks": 0,
    "unmap_latency_ticks": 0
  },
...
]
```
We can see that the first entry in the array is an object with "tick_rate" property, which is a kind of meta-property which applies to all other entries which follow in the array. Instead the reply could look like this:
```
{
  "tick_rate": 123124465,
  "bdevs": [
     ...list of bdevs with their stat props...
  ]
}
```
and everyone would be likely happy. The purpose of this ticket is to start discussion about RPC and perhaps set best practises for designing rpc methods. I see related tickets for pointless error messages etc. So there is more to fix in rpc api ...

**Comment by jimharris** [comment]
Thanks @jkryl.  This is great feedback.  Fixing get_bdevs_iostat as you've suggested makes sense.  Are you aware of any others offhand that have this similar structure?

**Comment by jkryl** [comment]
thanks Jim for the response! We are using maybe 10 rpc methods from spdk so far and this one is the only one where I have encountered this problem. It might not be feasible to fix if we want to preserve backward compatibility of the api. Maybe at some point in future when major revision of the api is made. I have changed the method in our private fork of spdk so it does not bother me. It seems that we all agree. if we can prevent new api methods from using this anti-pattern, then the purpose of this ticket has been fulfilled. Feel free to close the ticket.

**Comment by jimharris** [comment]
Hi @jkryl - I'd like to get it fixed since you've pointed out it's practically unusable in its current state (and you've had to modify it in your private fork).  I know it breaks backward compatibility but I guess I'm not as concerned if it's breaking a broken API.  What do others think?

I have a patch out for this:  https://review.gerrithub.io/c/spdk/spdk/+/452477/1

**Comment by jimharris** [comment]
That patch still needs to update CHANGELOG and jsonrpc.md.

**Comment by jimharris** [comment]
Updated version posted: https://review.gerrithub.io/c/spdk/spdk/+/452477

**Comment by jkryl** [comment]
nice fix. Thank you!
