### ISSUE TITLE
nvme-cli compiles with spdk default configuration failed

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#776]
use the latest spdk in nvme-cli, to compile  nvme-cli
[root@waikikibeach32 nvme-cli]# make
cc -D_GNU_SOURCE -D__CHECK_ENDIAN__ -O2 -g -Wall -Werror -std=gnu99 -DLIBUUID -I/home/yidong/nvme-cli/spdk/include -DNVME_VERSION='"1.3.404.gc763"' nvme.c -o nvme argconfig.o suffix.o parser.o nvme-print.o nvme-ioctl.o nvme-lightnvm.o fabrics.o json.o plugin.o intel-nvme.o lnvm-nvme.o memblaze-nvme.o wdc-nvme.o wdc-utils.o nvme-models.o huawei-nvme.o netapp-nvme.o toshiba-nvme.o micron-nvme.o seagate-nvme.o spdk-nvme.o -luuid -Wl,--whole-archive -L/home/yidong/nvme-cli/spdk/build/lib -lspdk_log -lspdk_sock -lspdk_nvme -lspdk_env_dpdk -lspdk_util -L/home/yidong/nvme-cli/spdk/dpdk/build/lib -lrte_eal -lrte_mempool -lrte_ring -lrte_pci -lrte_bus_pci -lrte_kvargs -Wl,--no-whole-archive -ldl -pthread -lrt -lrdmacm -lnuma -libverbs
/home/yidong/nvme-cli/spdk/build/lib/libspdk_util.a(crc16.o): In function `spdk_crc16_t10dif':
/home/yidong/nvme-cli/spdk/lib/util/crc16.c:46: undefined reference to `crc16_t10dif'
/home/yidong/nvme-cli/spdk/build/lib/libspdk_util.a(crc16.o): In function `spdk_crc16_t10dif_copy':
/home/yidong/nvme-cli/spdk/lib/util/crc16.c:53: undefined reference to `crc16_t10dif_copy'
/home/yidong/nvme-cli/spdk/build/lib/libspdk_util.a(crc32c.o): In function `spdk_crc32c_update':
/home/yidong/nvme-cli/spdk/lib/util/crc32c.c:58: undefined reference to `crc32_iscsi'
collect2: error: ld returned 1 exit status
make: *** [Makefile:42: nvme] Error 1

if spdk config --without-isal ,nvme-cli will compile successfully.

**Comment by peluse** [comment]
@yidong0635 can you please try this, thanks! https://review.gerrithub.io/c/spdk/nvme-cli/+/452798

**Comment by yidong0635** [comment]
@peluse , thanks, this patch is ok.

**Comment by jimharris** [comment]
Patch merged.
