### ISSUE TITLE
CI machines fail to initialize AIO bdevs

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#777]
Apparently we can't open some AIO bdevs on two of our CI machines and we don't even know it because the bdev module initialization continues even if some bdevs to register. We should either make sure those bdevs can be created on all the CI machines or we should remove them from the config files in our autotest.

ubuntu16_04_vm_3 (Ubuntu16_VM):
```
bdev_raid.c:1990:raid_bdev_examine: *DEBUG*: bdev AIO0 can't be claimed
bdev_aio.c: 132:bdev_aio_open: *ERROR*: open() failed
(file:/tmp/aiofile), errno 2: No such file or directory
bdev_aio.c: 603:create_aio_bdev: *ERROR*: Unable to open file
/tmp/aiofile. fd: -1 errno: 2
bdev_aio.c: 768:bdev_aio_initialize: *ERROR*: Unable to create AIO bdev
from file /tmp/aiofile
```

I pushed a patch to fail the AIO module initialization on bdev failure and I see both ubuntu16 and blockdev_autotest failing: https://review.gerrithub.io/c/spdk/spdk/+/452421 "bdev/aio: fail module init on bdev registration failure"

**Comment by optimistyzy** [comment]
@darsto I do not think it is a bug.  The print log is a correct behavior. In your patch, you use add the error case if create_aio_bdev failed. If we do that, could we change all the "continue" in the for loop, this will be consistent.

**Comment by peluse** [comment]
do we know why this is not working on those 2 machines?
(file:/tmp/aiofile), errno 2: No such file or directory

**Comment by tomzawadzki** [comment]
The error was caused by using configuration file (bdev.conf.in) for blockdev.sh in bdev_raid.sh. In blockdev.sh /tmp/aiofile is removed at the end, so it was not present for bdev_raid.sh. There is no need use bdev.conf.in, since raid tests only use malloc devices.

Please see following patch for a fix: https://review.gerrithub.io/#/c/spdk/spdk/+/453644/
