### ISSUE TITLE
Intermittent nvme/identify seg fault

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#780]
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_29863.html

I've seen this occur several times in the test pool.  stub application starts, then immediately after starting nvme/identify, it segfaults.

Even worse, the trap tries to kill the stub but is unsuccessful.  So the build times out and we don't get any clues on the the backtrace.

https://review.gerrithub.io/c/spdk/spdk/+/452891 - kills stub with -9 when failure occurs.  That will help make forward progress.

**Comment by jimharris** [comment]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/30759/archive/nvme_phy_autotest/build.log

This one has backtraces from the segfault.

**Comment by peluse** [comment]
got a repro on this locally early in the week but can't get it to happen again.  What does intermittent mean again?

**Comment by darsto** [comment]
Bug scrub: let's keep an eye out - if this doesn't reproduce during this week we'll just close the github issue

**Comment by darsto** [comment]
Bug scrub: still reproduces. 

We need to add more instrumentation to the identify app - someone should go through the entire code path of getting nvme log pages.

**Comment by jimharris** [comment]
Patch out for debugging this issue: https://review.gerrithub.io/c/spdk/spdk/+/456871

**Comment by peluse** [comment]
cool, I hadn't seen this for a while but it just hit one of my patches yesterday

**Comment by jimharris** [comment]
Yeah - this does look like a problem with the Intel log pages:

http://10.102.17.206/results/autotest-per-patch/builds/33565/archive/nvme_phy_autotest/build.log

It hits my assert specifically when running the Intel log page commands.  Will add more specifics to figure out exactly which one it is, and how much data its actually writing.

**Comment by jimharris** [comment]
Looks like this is an SSD FW bug that has been fixed.  Rev 8DV10171 has the problem, 8DV101H0 does not.

Waiting for one more test run to see how many bytes it overwrites with the bad FW.  Then we will change the size of struct spdk_nvme_intel_marketing_description_page to add extra bytes to work around this problem.

WP2 passes my test:
Model Number:                          INTEL SSDPE2MD400G4
Firmware Version:                      8DV101H0

GP1 has failed in the past:
Model Number:                          INTEL SSDPE2MD400G4
Firmware Version:                      8DV10171

GP4 failed just now:
Model Number:                          INTEL SSDPE2MD400G4
Firmware Version:                      8DV10171

GP2:
Model Number:                          INTEL SSDPE2MD400G4
Firmware Version:                      8DV10171

WP4:
Model Number:                          INTEL SSDPEDMD400G4
Firmware Version:                      8DV101H0

**Comment by jimharris** [comment]
It apparently overwrites 4 bytes.

EAL:   using IOMMU type 1 (Type 1)
size=512 but overwrote 4 bytes
identify: nvme.c:195: nvme_user_copy_cmd_complete: Assertion `false' failed.
test/nvme/nvme.sh: line 100: 595934 Aborted                 (core dumped) 

https://review.gerrithub.io/c/spdk/spdk/+/456880 should fix this issue for good.

**Comment by jimharris** [comment]
Patch has been merged.
