### ISSUE TITLE
SPDK shared libraries have incorrect library name in SONAME attribute

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#781]
Some tools (bazel/ldd) use the SONAME attribute in the shared library for the name that is specified in the executable and not the actual filename. 
The SPDK make spdk_build_realname_shared_lib has an issue where the library name doesn't include the minor version.

Here's an example of the verbose build:
```
cc -o /root/spdk/spdk-19.04/build/lib/libspdk_bdev_raid.so.1.0 -shared  -Wl,-z,relro,-z,now -Wl,-z,noexecstack -fuse-ld=bfd -pthread -Wl,-z,relro,-z,now -Wl,-z,noexecstack -fuse-ld=bfd -pthread -Wl,--soname,libspdk_bdev_raid.so.1 -Wl,--whole-archive /root/spdk/spdk-19.04/build/lib/libspdk_bdev_raid.a -Wl,--no-whole-archive -Wl,--version-script=/root/spdk/spdk-19.04/shared_lib/spdk.map -lrt
  SO libspdk_bdev_raid.so.1.0
```
Notice `--soname,libspdk_bdev_raid.so.1` which is stored in the shared library. The name is incorrect and it should be `--soname,libspdk_bdev_raid.so.1.0` since this is what the filename will be (see -o option).

Since our toolchain (not sure if bazel or gcc) uses SONAME when linking the executable, the shared library can't be resolved:
```
ldd:
nvmef_target_test
        linux-vdso.so.1 (0x00007ffc03b8e000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fe6186ee000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe6184ea000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe6182e2000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fe6180db000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fe617c63000)
        libspdk_copy_ioat.so.1 => not found
        libspdk_ioat.so.1 => not found
...
```

## Expected Behavior
Able to link the shared libraries.

## Current Behavior
Not able to link with the shared libraries.

## Possible Solution
Use archived versions but bazel (our "build" too) has issues with that ...

## Steps to Reproduce
Do a ./configure --with-shared and try to link the libs against an example (I can provide a bazel config if needed).

objdump tool can be used to see what SONAME is.

## Context (Environment including OS version, SPDK version, etc.)
I'm using 19.04

**Comment by jimharris** [comment]
@mhae - good catch.  Can you try https://review.gerrithub.io/c/spdk/spdk/+/452895?

**Comment by mhae** [comment]
That works (I fixed it the same way). Thanks.

**Comment by jimharris** [comment]
Patch merged.
