### ISSUE TITLE
autotest for iscsi related items failed 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#782]
when I use vagrant to run autotest about iscsi related items, 

SPDK_TEST_ISCSI=1
SPDK_TEST_ISCSI_INITIATOR=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
./test/iscsi_tgt/ip_migration/ip_migration.sh
./test/iscsi_tgt/trace_record/trace_record.sh
./test/iscsi_tgt/initiator/initiator.sh
and it will reports several errors , but I observed that  issues will not be detected in jenkins pool .

[iscsi_tgt_issue.txt](https://github.com/spdk/spdk/files/3146916/iscsi_tgt_issue.txt)

not sure about what happens, but make sure this is an issue.

## Expected Behavior
report error and exit.

## Current Behavior
there's no related issue be reported.

## Steps to Reproduce
use vagrant to run auto test.
## Context (Environment including OS version, SPDK version, etc.)
commit:00a6c491d214b54041dcec419dbccd53ba8b3480

**Comment by yidong0635** [comment]
in jenkin  SPDK_TEST_ISCSI_INITIATOR=0

**Comment by darsto** [comment]
#784 is a duplicate, but since it contains more information I'm going to close this current issue and let #784 be
