### ISSUE TITLE
bdev: question about per-thread bdev_io cache in spdk_bdev_mgmt_channel

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#783]
Hi,

In lib/bdev/bdev.c, the per-thread variable spdk_bdev_mgmt_channel provides a cache mechanism for bdev_io, similar to that in DPDK mempool library.

```
        /*                                                                          
         * Each thread keeps a cache of bdev_io - this allows                       
         *  bdev threads which are *not* DPDK threads to still                      
         *  benefit from a per-thread bdev_io cache.  Without                       
         *  this, non-DPDK threads fetching from the mempool                        
         *  incur a cmpxchg on get and put.                                         
         */                                                                         
        bdev_io_stailq_t per_thread_cache;                                          
        uint32_t        per_thread_cache_count;                                     
        uint32_t        bdev_io_cache_size;
```

As mentioned in the above code comment, this mechanism is for bdev threads which are **not** DPDK threads.

From my understanding, a SPDK thread, is a thread structure which is allocated by spdk_thread_create function and is assigned to tls_thread variable in spdk_set_thread function. I think before the dynamic threading model releases in 19.07, a SPDK thread and EAL pthread(DPDK thread) are in one-to-one relationships. (If I understand incorrectly, please help me to point out.)

Is there a case that a bdev thread(SPDK thread running bdev code) is not a DPDK thread? 

Thanks in advance.

**Comment by benlwalker** [comment]
In all normal circumstances (i.e. not the fio plugin or rocksdb), yes an spdk_thread is mapped 1:1 to a DPDK thread in the 19.01 and 19.04 releases. In 19.04 that's not strictly required - there can be multiple spdk_threads per DPDK thread, but there isn't any code that does that yet.

**Comment by lorneli** [comment]
@benlwalker Thanks a lot for your explanation.

The fio_plugin creates its own spdk_thread. When fio_plugin submits io to bdev layer, bdev layer needs to grab a bdev_io struct to describe this io, but it can't take advantage of the per core cache of spdk_mempool which is intended for dpdk thread. That's why the per-thread variable spdk_bdev_mgmt_channel in bdev layer provides a cache mechanism for bdev_io by itself.

```
        // examples/bdev/fio_plugin/fio_plugin.c
        fio_thread->thread = spdk_thread_create("fio_thread", NULL);               
        if (!fio_thread->thread) {                                                 
                free(fio_thread);                                                  
                SPDK_ERRLOG("failed to allocate thread\n");                        
                return -1;                                                         
        }                                                                          
        spdk_set_thread(fio_thread->thread); 
```
