### ISSUE TITLE
autotest reprots  errors on ubuntu16 with scanbuild enabled

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#792]
there're several errors on ubuntu16, when I run autotest on ubuntu16 VM  .
_1.ftl_anm.c:406:2: warning: Null pointer passed as an argument to a 'nonnull' parameter
        pthread_mutex_lock(&ctrlr->lock);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2. ctrlr.c:367:2: warning: Access to field 'tqh_first' results in a dereference of a null pointer
        TAILQ_FOREACH_SAFE(log, &ctrlr->log_head, link, log_tmp) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vagrant/master/build-20190514204126/spdk/include/spdk/queue_extras.h:292:15: note: expanded from macro 'TAILQ_FOREACH_SAFE'
        for ((var) = TAILQ_FIRST((head));                               \
                     ^~~~~~~~~~~~~~~~~~~
/home/vagrant/master/build-20190514204126/spdk/include/spdk/queue_extras.h:284:27: note: expanded from macro 'TAILQ_FIRST'
#define TAILQ_FIRST(head)       ((head)->tqh_first)
                                ^~~~~~~~~~~~~~~~~~~
3. ftl_band.c:584:44: warning: Division by zero
        num_stripes = (num_lbks / dev->xfer_size) / band->num_chunks;
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
4.In file included from blob_ut.c:44:
/home/vagrant/master/build-20190514194452/spdk/lib/blob/request.c:317:8: warning: Access to field 'tqh_first' results in a dereference of a null pointer
        set = TAILQ_FIRST(&channel->reqs);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vagrant/master/build-20190514194452/spdk/include/spdk/queue_extras.h:284:27: note: expanded from macro 'TAILQ_FIRST'
#define TAILQ_FIRST(head)       ((head)->tqh_first)
                                ^~~~~~~~~~~~~~~~~~~
In file included from blob_ut.c:44:
/home/vagrant/master/build-20190514194452/spdk/lib/blob/request.c:472:8: warning: Access to field 'tqh_first' results in a dereference of a null pointer
        set = TAILQ_FIRST(&channel->reqs);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vagrant/master/build-20190514194452/spdk/include/spdk/queue_extras.h:284:27: note: expanded from macro 'TAILQ_FIRST'
#define TAILQ_FIRST(head)       ((head)->tqh_first)
                                ^~~~~~~~~~~~~~~~~~_~


## Expected Behavior
scan build can pass.

## Current Behavior
scanbuild failed and report erros
## Possible Solution
there are several patches here.
https://review.gerrithub.io/c/spdk/spdk/+/454539
https://review.gerrithub.io/c/spdk/spdk/+/454546
https://review.gerrithub.io/c/spdk/spdk/+/454545
https://review.gerrithub.io/c/spdk/spdk/+/454536
## Steps to Reproduce
step an ubuntu VM, to run autotest.
I use vagrant to run this cases.

## Context (Environment including OS version, SPDK version, etc.)
commit:2ff59b0ecb37a386f918f2c305d29781b3488c55

**Comment by changpe1** [comment]
[Bug Scrub] Can we add the assertion in the Unit test where the issue was reported?

**Comment by yidong0635** [comment]
will check  the 4th , others can't.

**Comment by yidong0635** [comment]
in test/unit/lib/blob/blob.c/blob_ut.c :
 #include "common/lib/ut_multithread.c"
#include "../bs_dev_common.c"
  #include "blob/blobstore.c"
 #include "blob/request.c"
  #include "blob/zeroes.c"
 #include "blob/blob_bs_dev.c"
although  error reports issues, due to it includes  c source file.
that means this issue doesn't related to UT.

**Comment by yidong0635** [comment]
@changpe1  waiting for your kindly advise.

**Comment by yidong0635** [comment]
ubuntu18 need to install clang-tools to start scanbuild， otherwise hash scan-build failed.

**Comment by yidong0635** [comment]
finished this one,  three of  patches have been merged, other one will be abandoned.
close this issue.
