### ISSUE TITLE
bdev/compress: multi-thread is broken

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#794]
Have root cause, will get it pushed probably Monday.  Do not test with any multi-thread use cases until fixed.

Marking this medium as compress is still experimental in this release

**Comment by peluse** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/455018

**Comment by peluse** [comment]
FYI also tested w/fio against nvmf tgt with compressdev backing.  6 threads w/verify turned on.

**Comment by jimharris** [comment]
Patch merged.
