### ISSUE TITLE
ubuntu support libverbs error

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#796]
configure: error: <infiniband/driver.h> not found. librxe-dev requires libibverbs.

new kernel integrates this to rdma-core

apt-get install rdma-core*

**Comment by yidong0635** [comment]
maybe should install rdma-core instead of downloading and compiling librxe-dev on ubuntu serials, need
 to investigate more.

**Comment by darsto** [comment]
Bug scrub: I'm assigning this to you, @yidong0635 ;)

We probably need some updates to vm_setup.sh, that's where librxe is built

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/455336

**Comment by yidong0635** [comment]
this supports ubuntu18 and later version. ubuntu16 should keep former .

**Comment by yidong0635** [comment]
since this patch has been merged, close this issue.
