### ISSUE TITLE
 test/nvmf/target/filesystem.sh failed on ubuntu18 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#799]
## Current Behavior
test/nvmf/target/filesystem.sh always failed on ubuntu18.
 _parted -s /dev/nvme0n1 mklabel msdos mkpart primary 0% 100%
Warning: The resulting partition is not properly aligned for best performance._
[parted_failure.txt](https://github.com/spdk/spdk/files/3205795/parted_failure.txt)

## Expected Behavior
test can pass

## Steps to Reproduce
run auto test on ubuntu,
 run_test suite test/nvmf/target/filesystem.sh
## Context (Environment including OS version, SPDK version, etc.)
commit:3a0627f069213c4148530ce263e79b535c322f11

**Comment by changpe1** [comment]
@yidong0635 Can this issue be reproduced very easy ?

**Comment by yidong0635** [comment]
yes , on ubuntu18,  it always blocks me.

**Comment by changpe1** [comment]
@yidong0635 Can you debug it to see why the block device do not exist on your system?

**Comment by jimharris** [comment]
Hi @yidong0635 - could you try adding "partprobe" after the "parted"?

**Comment by yidong0635** [comment]
@jimharris @changpe1  will try what you are suggested, but now I'm blocked by #802.

**Comment by yidong0635** [comment]
this only happens on ubuntu18, fedora28 is ok.

**Comment by jimharris** [comment]
Does #802 happen every time on Ubuntu 18?

**Comment by yidong0635** [comment]
it almost every time, I tried some methods , but can't bypass it.

**Comment by yidong0635** [comment]
maybe a little different,  my failures are at nvme connects.

**Comment by yidong0635** [comment]
@jimharris  adding "partprobe" after the "parted",  
11:36:26       # partprobe
it keeps waiting.

**Comment by jimharris** [comment]
OK - thanks for trying.

**Comment by yidong0635** [comment]
tried  a method，partprobe takes 10 minites， it's too long：
 
 02:35:31       # wipefs -a /dev/nvme0n1
/dev/nvme0n1: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/nvme0n1: calling ioctl to re-read partition table: Success
 02:36:53       # parted -s /dev/nvme0n1 mklabel msdos mkpart primary btrfs 0% 100%
Warning: The resulting partition is not properly aligned for best performance.
 02:39:49       # sleep 1
 02:39:50       # partprobe
 02:49:57       # timing_exit parted
 02:49:57       # xtrace_disable
 02:49:57       # PREV_BASH_OPTS=ehxBE
 02:49:57       # set +x
 02:49:57       # xtrace_enable
 02:49:57       # timing_enter btrfs
 02:49:57       # xtrace_disable
 02:49:57       # PREV_BASH_OPTS=ehxBE
 02:49:57       # set +x
 02:49:57       # xtrace_enable
 02:49:57       # '[' btrfs = ext4 ']'
 02:49:57       # force=-f
 02:49:57       # mkfs.btrfs -f /dev/nvme0n1p1
btrfs-progs v4.15.1
See http://btrfs.wiki.kernel.org for more information.

Detected a SSD, turning off metadata duplication.  Mkfs with -m dup if you want to force metadata duplication.
Performing full device TRIM /dev/nvme0n1p1 (64.00MiB) ...
Label:              (null)
UUID:               493d9c35-e514-4ee3-bdab-e083c2bdd3d7
Node size:          16384
Sector size:        4096
Filesystem size:    64.00MiB
Block group profiles:
  Data:             single            6.38MiB
  Metadata:         single            6.38MiB
  System:           single            4.00MiB
SSD detected:       yes
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1    64.00MiB  /dev/nvme0n1p1

 02:50:47       # mount /dev/nvme0n1p1 /mnt/device
 02:52:17       # touch /mnt/device/aaa
 02:52:17       # sync
 02:52:22       # rm /mnt/device/aaa
 02:52:22       # sync
 02:52:27       # umount /mnt/device
 02:52:29       # timing_exit btrfs

**Comment by yidong0635** [comment]
@jimharris  follow your suggestion, post this patch :https://review.gerrithub.io/c/spdk/spdk/+/457735
though it's not perfect. Other SPECs suggest to add this.
