### ISSUE TITLE
Minimum hardware requirement 

### ISSUE THREAD

**Issue by ionuthristodorescu** [spdk/spdk#8]
... to start testing/integrating/playing with SPDK ? AFAIK, for DPDK I need an Intel based NIC - which I already have in our Dell R610 servers - but how about NVMe/SSD ? Any decently priced card I could buy to install in a Dell R610 ? Thank you in advance for your answer.

**Comment by dverkamp-intel** [comment]
Any NVMe spec compliant device should work.  We are specifically testing with Intel SSD DC P3700 devices, but other NVMe devices should work as well.

**Comment by ionuthristodorescu** [comment]
Thanks, Daniel, for the quick reply. I will probably need to upgrade to a Dell R720 with PCIe 3.0 sockets - unless you guys use cheaper solutions. Thank you.
