### ISSUE TITLE
kernel nvmf initiator hangs on disconnect

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#802]
This came up in nightly. It seems like we try to connect and disconnect the kernel initiator multiple times as a part of the test and at some point one disconnect gets stuck.

```
07:46:15 ************************************
07:46:15 START TEST SUITE test/nvmf/target/rpc.sh
07:46:15 ************************************
<SNIP>
07:46:45 NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
07:46:45  07:46:45	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_ns nqn.2016-06.io.spdk:cnode1 5
07:46:45  07:46:46	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py delete_nvmf_subsystem nqn.2016-06.io.spdk:cnode1
07:46:46  07:46:46	# for i in `seq 1 $times`
07:46:46  07:46:46	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -s SPDK00000000000001
07:46:46  07:46:46	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
07:46:46  07:46:46	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1 -n 5
07:46:46  07:46:46	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_allow_any_host nqn.2016-06.io.spdk:cnode1
07:46:46  07:46:46	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.8 -s 4420
07:46:47  07:46:48	# waitforblk nvme0n1
07:46:47  07:46:48	# local i=0
07:46:47  07:46:48	# lsblk -l -o NAME
07:46:47  07:46:48	# grep -q -w nvme0n1
07:46:47  07:46:48	# lsblk -l -o NAME
07:46:47  07:46:48	# grep -q -w nvme0n1
07:46:47  07:46:48	# return 0
07:46:47  07:46:48	# nvme disconnect -n nqn.2016-06.io.spdk:cnode1
07:46:50 Build timed out (after 25 minutes). Marking the build as failed.
```

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/511/archive/nvmf_phy_autotest/build.log

**Comment by yidong0635** [comment]
met the same issue auto test failed.
01:01:44       # xtrace_enable
 01:01:44       # ((  i == 0  ))
 01:01:44       # return 0
 01:01:44       # modprobe nvme-rdma
 01:01:44       # timing_exit start_nvmf_tgt
 01:01:44       # xtrace_disable
 01:01:44       # PREV_BASH_OPTS=ehxBE
 01:01:44       # set +x
 01:01:44       # xtrace_enable
 01:01:44       # /home/vagrant/master/build-20190524005845/spdk/scripts/rpc.py nvmf_create_transport -t rdma -u 8192 -c 0
 01:01:44       # /home/vagrant/master/build-20190524005845/spdk/scripts/rpc.py construct_malloc_bdev 64 512 -b Malloc1
Malloc1
 01:01:44       # /home/vagrant/master/build-20190524005845/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
 01:01:44       # /home/vagrant/master/build-20190524005845/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
 01:01:45       # /home/vagrant/master/build-20190524005845/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.121.222 -s 4420
 01:01:45       # nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.121.222 -s 4420
Failed to write to /dev/nvme-fabrics: Cannot allocate memory
  01:01:52      # trap - ERR
  01:01:52      # print_backtrace
  01:01:52      # [[ ehxBE =~ e ]]
  01:01:52      # xtrace_disable
  01:01:52      # PREV_BASH_OPTS=ehxBE
  01:01:52      # set +x
========== Backtrace start: ==========

in test/nvmf/target/filesystem.sh:31 -> main()
     ...
   26           $rpc_py construct_malloc_bdev $MALLOC_BDEV_SIZE $MALLOC_BLOCK_SIZE -b Malloc1
   27           $rpc_py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
   28           $rpc_py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
   29           $rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a $NVMF_FIRST_TARGET_IP -s 4420
   30
=> 31           nvme connect -t rdma -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
   32
   33           waitforblk "nvme0n1"
   34
   35           mkdir -p /mnt/device
   36
     ...

**Comment by jimharris** [comment]
We will need to keep an eye on this one.  Note that we recently removed the -p option from this test which limited the number of qpairs that we create.  So now instead of creating 4 queue pairs per connect, we do 60 (at least on this system).

We also do the connect/disconnect loop 50 times on the nightly test vs. just 3 on per-patch testing.

**Comment by yidong0635** [comment]
if my memory is enough ,can pass this item.

**Comment by changpe1** [comment]
There is a similar issue in https://www.spinics.net/lists/linux-rdma/msg64887.html here, someone also mentioned that due to limited MR in RDMA cards, so maybe we still need to limit number of queue pairs when connecting to remote target.

**Comment by yidong0635** [comment]
git reset --hard HEAD~100 ----git reset --hard HEAD~200
Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: nvmf -c 0xF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 4
app.c: 538:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
app.c: 542:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -i 0' to capture a snapshot of events at runtime.
app.c: 544:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.0 for offline analysis/debug.
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 2
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 3
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
 08:54:39       # xtrace_enable
 08:54:39       # ((  i == 0  ))
 08:54:39       # return 0
 08:54:39       # /home/vagrant/master/build-20190530085109/spdk/scripts/rpc.py nvmf_create_transport -t RDMA -u 8192 -p 4 -c 0
  08:54:39      # /home/vagrant/master/build-20190530085109/spdk/scripts/rpc.py construct_malloc_bdev 64 512
 08:54:39       # bdevs=Malloc0
  08:54:39      # /home/vagrant/master/build-20190530085109/spdk/scripts/rpc.py construct_malloc_bdev 64 512
 08:54:39       # bdevs+=' Malloc1'
 08:54:39       # modprobe -v nvme-rdma
insmod /lib/modules/4.15.0-12-generic/kernel/drivers/nvme/host/nvme-fabrics.ko
insmod /lib/modules/4.15.0-12-generic/kernel/drivers/nvme/host/nvme-rdma.ko
 08:54:39       # /home/vagrant/master/build-20190530085109/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
 08:54:40       # for bdev in $bdevs
 08:54:40       # /home/vagrant/master/build-20190530085109/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
 08:54:40       # for bdev in $bdevs
 08:54:40       # /home/vagrant/master/build-20190530085109/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
 08:54:40       # /home/vagrant/master/build-20190530085109/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.0.2.15 -s 4420
 08:54:40       # nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 10.0.2.15 -s 4420
 08:54:47       # waitforblk nvme0n1
 08:54:47       # local i=0
 08:54:47       # lsblk -l -o NAME
 08:54:47       # grep -q -w nvme0n1
 08:54:47       # '[' 0 -lt 15 ']'
 08:54:47       # i=1
 08:54:47       # sleep 1
 08:54:48       # lsblk -l -o NAME
 08:54:48       # grep -q -w nvme0n1
 08:54:48       # '[' 1 -lt 15 ']'
 08:54:48       # i=2
 08:54:48       # sleep 1
 08:54:49       # lsblk -l -o NAME
 08:54:49       # grep -q -w nvme0n1
 08:54:49       # '[' 2 -lt 15 ']'
 08:54:49       # i=3
 08:54:49       # sleep 1
 08:54:50       # lsblk -l -o NAME
 08:54:50       # grep -q -w nvme0n1
 08:54:50       # '[' 3 -lt 15 ']'
 08:54:50       # i=4
 08:54:50       # sleep 1
 08:54:51       # lsblk -l -o NAME
 08:54:51       # grep -q -w nvme0n1
 08:54:51       # '[' 4 -lt 15 ']'
 08:54:51       # i=5
 08:54:51       # sleep 1
 08:54:52       # lsblk -l -o NAME
 08:54:52       # grep -q -w nvme0n1
 08:54:52       # '[' 5 -lt 15 ']'
 08:54:52       # i=6
 08:54:52       # sleep 1
 08:54:53       # lsblk -l -o NAME
 08:54:53       # grep -q -w nvme0n1
 08:54:53       # '[' 6 -lt 15 ']'
 08:54:53       # i=7
 08:54:53       # sleep 1
 08:54:54       # lsblk -l -o NAME
 08:54:54       # grep -q -w nvme0n1
 08:54:54       # lsblk -l -o NAME
 08:54:54       # grep -q -w nvme0n1
 08:54:54       # return 0
 08:54:54       # waitforblk nvme0n2
 08:54:54       # local i=0
 08:54:54       # lsblk -l -o NAME
 08:54:54       # grep -q -w nvme0n2
 08:54:54       # '[' 0 -lt 15 ']'
 08:54:54       # i=1
 08:54:54       # sleep 1
 08:54:55       # lsblk -l -o NAME
 08:54:55       # grep -q -w nvme0n2
 08:54:55       # '[' 1 -lt 15 ']'
 08:54:55       # i=2
 08:54:55       # sleep 1
 08:54:56       # lsblk -l -o NAME
 08:54:56       # grep -q -w nvme0n2
 08:54:56       # '[' 2 -lt 15 ']'
 08:54:56       # i=3
 08:54:56       # sleep 1
 08:54:57       # lsblk -l -o NAME
 08:54:57       # grep -q -w nvme0n2
 08:54:57       # '[' 3 -lt 15 ']'
 08:54:57       # i=4
 08:54:57       # sleep 1
 08:54:58       # lsblk -l -o NAME
 08:54:58       # grep -q -w nvme0n2
 08:54:58       # '[' 4 -lt 15 ']'
 08:54:58       # i=5
 08:54:58       # sleep 1
 08:54:59       # lsblk -l -o NAME
 08:54:59       # grep -q -w nvme0n2
 08:54:59       # '[' 5 -lt 15 ']'
 08:54:59       # i=6
 08:54:59       # sleep 1
 08:55:00       # lsblk -l -o NAME
 08:55:00       # grep -q -w nvme0n2
 08:55:00       # '[' 6 -lt 15 ']'
 08:55:00       # i=7
 08:55:00       # sleep 1
 08:55:01       # lsblk -l -o NAME
 08:55:01       # grep -q -w nvme0n2
 08:55:01       # '[' 7 -lt 15 ']'
 08:55:01       # i=8
 08:55:01       # sleep 1
 08:55:02       # lsblk -l -o NAME
 08:55:02       # grep -q -w nvme0n2
 08:55:02       # '[' 8 -lt 15 ']'
 08:55:02       # i=9
 08:55:02       # sleep 1
 08:55:03       # lsblk -l -o NAME
 08:55:03       # grep -q -w nvme0n2
 08:55:03       # '[' 9 -lt 15 ']'
 08:55:03       # i=10
 08:55:03       # sleep 1
 08:55:04       # lsblk -l -o NAME
 08:55:04       # grep -q -w nvme0n2
 08:55:04       # '[' 10 -lt 15 ']'
 08:55:04       # i=11
 08:55:04       # sleep 1
 08:55:05       # lsblk -l -o NAME
 08:55:05       # grep -q -w nvme0n2
 08:55:05       # '[' 11 -lt 15 ']'
 08:55:05       # i=12
 08:55:05       # sleep 1
 08:55:06       # lsblk -l -o NAME
 08:55:06       # grep -q -w nvme0n2
 08:55:06       # '[' 12 -lt 15 ']'
 08:55:06       # i=13
 08:55:06       # sleep 1
 08:55:07       # lsblk -l -o NAME
 08:55:07       # grep -q -w nvme0n2
 08:55:07       # '[' 13 -lt 15 ']'
 08:55:07       # i=14
 08:55:07       # sleep 1
 08:55:08       # lsblk -l -o NAME
 08:55:08       # grep -q -w nvme0n2
 08:55:08       # '[' 14 -lt 15 ']'
 08:55:08       # i=15
 08:55:08       # sleep 1
 08:55:09       # lsblk -l -o NAME
 08:55:09       # grep -q -w nvme0n2
 08:55:09       # '[' 15 -lt 15 ']'
 08:55:09       # break
 08:55:09       # lsblk -l -o NAME
 08:55:09       # grep -q -w nvme0n2
 08:55:09       # return 1
  08:55:09      # trap - ERR
  08:55:09      # print_backtrace
  08:55:09      # [[ ehxBE =~ e ]]
  08:55:09      # xtrace_disable
  08:55:09      # PREV_BASH_OPTS=ehxBE
  08:55:09      # set +x
========== Backtrace start: ==========

in test/nvmf/target/filesystem.sh:52 -> main()
     ...
   47           $rpc_py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a $NVMF_FIRST_TARGET_IP -s 4420
   48
   49           nvme connect -t rdma -n "nqn.2016-06.io.spdk:cnode1" -a "$NVMF_FIRST_TARGET_IP" -s "$NVMF_PORT"
   50
   51           waitforblk "nvme0n1"
=> 52           waitforblk "nvme0n2"
   53

**Comment by yidong0635** [comment]
@jimharris @darsto @changpe1 if need bring this back? "-p 4"? 
 09:50:04       # /home/vagrant/master/build-20190530094529/spdk/scripts/rpc.py nvmf_create_transport -t rdma -u 8192 -p 4 -c 0
 09:50:04       # modprobe -v nvme-rdma
 09:50:04       # /home/vagrant/master/build-20190530094529/spdk/scripts/rpc.py construct_malloc_bdev 64 512 -b Malloc1
Malloc1
 09:50:05       # /home/vagrant/master/build-20190530094529/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001
 09:50:05       # /home/vagrant/master/build-20190530094529/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1
 09:50:05       # /home/vagrant/master/build-20190530094529/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 10.0.2.15 -s 4420
 09:50:05       # nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 10.0.2.15 -s 4420
 09:50:12       # waitforblk nvme0n1
 09:50:12       # local i=0
 09:50:12       # lsblk -l -o NAME
 09:50:12       # grep -q -w nvme0n1

**Comment by jimharris** [comment]
Is this two different issues?  The title and original description shows a problem with disconnect.  But more recent posts show the problem during connect.

I don't want to bring back the "-p 4".  This looks like a real problem that needs to be debugged.  It might be a kernel bug, but we need to interoperate well with the Linux kernel drivers.  If we add the "-p4 " back, it will just hide this issue.

**Comment by yidong0635** [comment]
My fault to put these issues in one, at the beginning , It blocks me at the connection. So I want to put it here. also need to nvme connect/disconnect.

**Comment by yidong0635** [comment]
the same issue exists in other nvmf_create_transport  related file including connect_disconnct.sh.
so need to resolve this.

**Comment by jimharris** [comment]
Hi @yidong0635,

Could you please post URLs for these failures when you find them?  Or if you are hitting this problem on your local system, please provide details on that system.

Thanks,

-Jim

**Comment by jimharris** [comment]
It would also be great if you could try to reproduce this on your local system.  That will allow us to more quickly come to resolution.

**Comment by yidong0635** [comment]
@jimharris ,  I reproduced this in ubuntu18 with SoftRoCE:
setup  ubuntu18 on waikikibeach15:
apt-get install rdma-core
rxe_cfg add ens785f1
rxe_cfg start
./test/nvmf/nvmf.sh
[nvme_connect_failure.txt](https://github.com/spdk/spdk/files/3246253/nvme_connect_failure.txt)

**Comment by yidong0635** [comment]
@benlwalker need you help, Do you have any idea about this?

**Comment by Seth5141** [comment]
@yidong0635 In reference to the traceback you posted two weeks ago. I have seem similar tracebacks on systems where the limits for locked memory are set too low. What are the memlock limits you get back when you run ulimit? If it's less than unlimited, you might want to modify that. Also, what is your setup here? If it's a VM, how much memory have you supplied to the system and how much of that is allocated to SPDK to run the target? My theory is that at least on your most recent traceback, the issue is related to system memory.

**Comment by yidong0635** [comment]
tested this on a physical machine. 
root@waikikibeach15:/home/yidong/spdk# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 163840
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 255845
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[Uploading nvme_connect_failure_with_unlimit.txt…]()

**Comment by Seth5141** [comment]
@yidong0635 Thanks for trying that. Is there anything interesting printed to dmesg when you run this test?

**Comment by yidong0635** [comment]
what about this?
[ 1102.300329] Code: 89 e5 41 56 41 55 41 54 53 48 8d 1c c5 00 00 00 00 49 89 fc 49 89 c5 49 89 d6 48 29 c3 48 c7 c2 00 96 89 c0 48 c1 e3 04 48 03 1f <48> 89 7b 18 48 8d 7b 58 c7 43 50 00 00 00 00 e8 40 99 63 e9 45
[ 1102.300378] RIP: nvme_rdma_alloc_queue+0x3c/0x190 [nvme_rdma] RSP: ffffbbae48c8fdf0
[ 1102.300384] ---[ end trace b264cdc5b8e0bf5c ]---
[ 1621.980193] nvme nvme0: creating 72 I/O queues.
[ 1622.124329] nvme nvme0: failed to initialize MR pool sized 128 for QID 16
[ 1622.124403] nvme nvme0: rdma connection establishment failed (-12)
[ 1622.152165] nvme nvme0: Reconnecting in 10 seconds...
[ 1632.220091] general protection fault: 0000 [#2] SMP PTI
[ 1632.220099] Modules linked in: nvme_rdma nvme_fabrics vsock_diag vsock sctp_diag sctp dccp_diag dccp tcp_diag udp_diag raw_diag inet_diag unix_diag af_packet_diag netlink_diag vfio_pci vfio_virqfd vfio_iommu_type1 vfio rpcrdma sunrpc rdma_rxe ip6_udp_tunnel udp_tunnel rdma_ucm ib_uverbs ipt_MASQUERADE nf_nat_masquerade_ipv4 nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter xt_conntrack nf_nat nf_conntrack libcrc32c br_netfilter bridge stp llc overlay pci_stub vboxpci(O) vboxnetadp(O) vboxnetflt(O) vboxdrv(O) intel_rapl sb_edac x86_pkg_temp_thermal mgag200 ttm drm_kms_helper intel_powerclamp drm input_leds joydev coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel i2c_algo_bit pcbc aesni_intel fb_sys_fops syscopyarea
[ 1632.220175]  sysfillrect mei_me aes_x86_64 crypto_simd sysimgblt glue_helper mei cryptd ipmi_si ipmi_devintf lpc_ich intel_cstate ipmi_msghandler intel_rapl_perf ioatdma acpi_power_meter wmi shpchp acpi_pad mac_hid kvm_intel kvm irqbypass binfmt_misc sch_fq_codel ib_iser rdma_cm iw_cm ib_cm ib_core iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi parport_pc ppdev lp parport ip_tables x_tables autofs4 hid_generic usbhid hid ixgbe dca ptp ahci pps_core libahci mdio
[ 1632.220231] CPU: 33 PID: 6065 Comm: kworker/u146:1 Tainted: G      D   IO     4.15.16 #1
[ 1632.220234] Hardware name: Intel Corporation S2600WTT/S2600WTT, BIOS SE5C610.86B.01.01.0005.101720141054 10/17/2014
[ 1632.220243] Workqueue: nvme-wq nvme_rdma_reconnect_ctrl_work [nvme_rdma]
[ 1632.220249] RIP: 0010:nvme_rdma_alloc_queue+0x3c/0x190 [nvme_rdma]
[ 1632.220252] RSP: 0018:ffffbbae4ac3fdf0 EFLAGS: 00010206
[ 1632.220256] RAX: 0000000000000000 RBX: 675e98701878442d RCX: ffff9c2c9ac66c20
[ 1632.220258] RDX: ffffffffc0899600 RSI: ffffffffc08983e2 RDI: ffff9c2c971fa000
[ 1632.220260] RBP: ffffbbae4ac3fe10 R08: 0000000000000166 R09: 0000017c07e4af00
[ 1632.220263] R10: 0000000000000000 R11: 000000000003e7f0 R12: ffff9c2c971fa000
[ 1632.220265] R13: 0000000000000000 R14: 0000000000000020 R15: 0000000000000000
[ 1632.220268] FS:  0000000000000000(0000) GS:ffff9c2c9efc0000(0000) knlGS:0000000000000000
[ 1632.220270] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1632.220273] CR2: 00005647c3588670 CR3: 00000001d0a0a006 CR4: 00000000001606e0
[ 1632.220275] Call Trace:
[ 1632.220283]  nvme_rdma_configure_admin_queue+0x22/0x2c0 [nvme_rdma]
[ 1632.220288]  nvme_rdma_reconnect_ctrl_work+0x27/0xd0 [nvme_rdma]
[ 1632.220295]  process_one_work+0x1db/0x3f0
[ 1632.220299]  worker_thread+0x4b/0x420
[ 1632.220308]  kthread+0x102/0x140
[ 1632.220311]  ? process_one_work+0x3f0/0x3f0
[ 1632.220315]  ? kthread_create_worker_on_cpu+0x70/0x70
[ 1632.220321]  ? do_syscall_64+0x6d/0x120
[ 1632.220325]  ? SyS_exit_group+0x14/0x20
[ 1632.220333]  ret_from_fork+0x35/0x40
[ 1632.220336] Code: 89 e5 41 56 41 55 41 54 53 48 8d 1c c5 00 00 00 00 49 89 fc 49 89 c5 49 89 d6 48 29 c3 48 c7 c2 00 96 89 c0 48 c1 e3 04 48 03 1f <48> 89 7b 18 48 8d 7b 58 c7 43 50 00 00 00 00 e8 40 99 63 e9 45
[ 1632.220385] RIP: nvme_rdma_alloc_queue+0x3c/0x190 [nvme_rdma] RSP: ffffbbae4ac3fdf0
[ 1632.220391] ---[ end trace b264cdc5b8e0bf5d ]---
[ 5840.908175] vfio_ecap_init: 0000:81:00.0 hiding ecap 0x19@0x2a0

**Comment by benlwalker** [comment]
When you set up the kernel initiator, can you tell it to create fewer queue pairs? 72 is a lot.

**Comment by yidong0635** [comment]
thanks ben, for autotest, how to tell the initiator, only need to change test scripts ? or do you have some special commands?

**Comment by darsto** [comment]
Bug scrub: we haven't seen this lately. Closing for now.

**Comment by yidong0635** [comment]
[2418515.989035] rdma_rxe: set rxe1 active
[2418515.989042] rdma_rxe: added rxe1 to enp3s0f0
[2418633.273316] nvme nvme0: creating 72 I/O queues.
[2418633.419894] nvme nvme0: failed to initialize MR pool sized 128 for QID 16
[2418633.420660] nvme nvme0: rdma connection establishment failed (-12)
[2418633.461232] nvme nvme0: Reconnecting in 10 seconds...
[2418643.513105] BUG: unable to handle kernel paging request at ffffffffc0935590
[2418643.513812] IP: 0xffffffffc0935590
[2418643.514258] PGD 9c1c0e067 P4D 9c1c0e067 PUD 9c1c10067 PMD 10521a7067 PTE 0
[2418643.514734] Oops: 0010 [#1] SMP PTI

issue locates at here,  creating 72 I/o queues  is a lot. but fedora doesn't have this issue.
