### ISSUE TITLE
Blobstore documentation page is missing some images

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#803]
There's some javascript on the blobstore page which doesn't work for me. I'm guessing it's supposed to generate some image, but I can't see anything on the screen.

```
Uncaught ReferenceError: Two is not defined
    at blob.html:185
```

Maybe we're missing a two.js include?

**Comment by benlwalker** [comment]
https://review.gerrithub.io/c/spdk/spdk.github.io/+/456073

**Comment by darsto** [comment]
^ merged. thanks
