### ISSUE TITLE
Windows scsi compliance tests suspend

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#804]
See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Windows scsi compliance tests run on jenkins suspend

## Expected Behavior
Windows scsi compliance tests end with success

## Current Behavior
Windows scsi compliance tests suspend on:
ASSERTION 13.6 WRITE (16) Write-With-Disk-Cache-Disabled Test

## Possible Solution
Not known

## Steps to Reproduce
1. Run ./test/vhost/windows/windows_scsi_compliance.sh --vm-ssh-pass=[windows vm password]

## Context (Environment including OS version, SPDK version, etc.)
Linux 4.18.18-200.fc28.x86_64

**Comment by pawelkax** [comment]
@changpe1 I found that tests start failing from https://review.gerrithub.io/#/c/spdk/spdk/+/436088/

**Comment by karlatec** [comment]
@pawelkax does vhost app print any error messages to stdout or stderr? If so, then it'd be good to post them here as well.

**Comment by pawelkax** [comment]
@changpe1 This is a last log from console:
ASSERTION 13.6 WRITE (16) Write-With-Disk-Cache-Disabled Test
Test: The command writes 12 MB of data correctly with cache disabled.
Info: Refer to SBC-2 (SCSI Block Commands) specification revision 8 Section 5.2.33.
Info: This test writes 12 MB of data to disk. Then, it reads the same 12 MB data that has just been written to verify that the data we just write are correct.

After this print tests suspend.

**Comment by changpe1** [comment]
@pawelkax I checked the code, it doesn't introduce any new feature for IO commands, is there any log information from the SPDK side?

**Comment by pawelkax** [comment]
@changpe1 Unfortunatley I cannot find any more useful logs

**Comment by pawelkax** [comment]
@changpe1 I reverted patch https://review.gerrithub.io/#/c/spdk/spdk/+/436088/ and tests are working so the bug must be in this patch

**Comment by changpe1** [comment]
@pawelkax Thanks, I will setup a Windows environment to debug it.

**Comment by jimharris** [comment]
Do the Windows compliance tests run SCSI reservations tests?  Or try to reserve the LUN before doing the write command?

I really don't see how 436088 could affect a write test, unless there are reservations happening as part of the test.

Are there no logs from the Windows system?

**Comment by pawelkax** [comment]
Hi @changpe1 ,
Do you have any update on this issue?
If you need help please let me know.

**Comment by changpe1** [comment]
@pawelkax A patch is merged to address the issue, what's the result for now?

**Comment by pawelkax** [comment]
Thanks @changpe1 . I tested windows scsi on jenkins with spdk master. It is working now.

**Comment by pawelkax** [comment]
Test are working now on jenkins. Finish with success.
