### ISSUE TITLE
bdev: assert(shared_resource->io_outstanding > 0) being hit on STATUS_NOMEM io completion 

### ISSUE THREAD

**Issue by ak-gh** [spdk/spdk#805]
## Expected Behavior
STATUS_NOMEM io should complete gracefully and get retried eventually.

## Current Behavior
Assert under subject is being hit consistently.

## Possible Solution
Looks like a one-liner (notice shared_resource->io_outstanding being decremented right before the assert check under STATUS_NOMEM clause).

```
index eefd723e1..2a96148b5 100644
--- a/lib/bdev/bdev.c
+++ b/lib/bdev/bdev.c
@@ -3519,7 +3519,6 @@ spdk_bdev_io_complete(struct spdk_bdev_io *bdev_io, enum spdk_bdev_io_status sta
                shared_resource->io_outstanding--;
 
                if (spdk_unlikely(status == SPDK_BDEV_IO_STATUS_NOMEM)) {
-                       assert(shared_resource->io_outstanding > 0);
                        TAILQ_INSERT_HEAD(&shared_resource->nomem_io, bdev_io, internal.link);
                        /*
                         * Wait for some of the outstanding I/O to complete before we
```

## Steps to Reproduce
1. Run any test against aio bdev with sufficiently large queue depth (I'm using 256).

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 18.04.2
SPDK 19.04 tag

**Comment by shuhei-matsumoto** [comment]
@ak-gh Thank you Andrey. Did you already post a patch to Gerrit or will you do if not yet?

**Comment by changpe1** [comment]
@ak-gh You can remove the assertion line, we don't need to add that assertion again, can you submit a patch to fix the issue ? Thanks.

**Comment by ak-gh** [comment]
Ok, I'll submit a patch today.

**Comment by ak-gh** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/455985

**Comment by shuhei-matsumoto** [comment]
The patch was merged. Thank you Andrey.
