### ISSUE TITLE
hello_nvme_blob.c missing in repo

### ISSUE THREAD

**Issue by vsnag** [spdk/spdk#807]
SPDK blobstore programmers guide talks about a file in examples called hello_nvme_blob.c. This is currently not found in the repo nor in the release package.

**Comment by changpe1** [comment]
@vsnag Thanks for reporting, I've removed the description via patch https://review.gerrithub.io/#/c/spdk/spdk/+/456598/.

**Comment by vsnag** [comment]
Does it mean blob to NVMe direct interaction is not supported?
Is the interaction only via the bdev abstraction is it?

**Comment by tomzawadzki** [comment]
You are correct - blobstore at this time only supports interaction with underlying device via bdev. This is implemented in lib/blob/bdev/blob_bdev.c.

There is abstraction around blobstore that should allow adding NVMe interaction, in similar manner to blob_bdev.c by implementing functions [here](https://spdk.io/doc/blob__bdev_8h.html) and callbacks for [spdk_bs_dev](https://spdk.io/doc/structspdk__bs__dev.html).

**Comment by changpe1** [comment]
@vsnag Patch has been merged, the unnecessary description has been deleted.

**Comment by darsto** [comment]
The patch from Changpeng is now merged. I'm closing this issue, but don't hesitate to continue the discussion here :)

**Comment by darsto** [comment]
@vsnag thanks for reporting!
