### ISSUE TITLE
SPDK NVMe-oF Target throws error “ctrlr.c:1008:spdk_nvmf_ctrlr_set_features_host_identifier: *ERROR*: Set Features - Host Identifier not allowed”

### ISSUE THREAD

**Issue by KariukiJ** [spdk/spdk#812]
When running test case 7.1 from the UNH-IOL_NVMe_Conformance_Test_Suite_v11 I ran into several issues with the emulated support for reservations that was recently added to the SPDK NVMe-oF target. The purpose of the test case is to verify if the NVMe Controller properly reports status of a reservation when processing a Reservation Report Command

## Expected Behavior
The SPDK NVMe-oF target reports the status of a reservation when processing a Reservation Report command

## Current Behavior
I ran into several errors:
1) When the NVMe Host issues a Set Features command with the Host Identifier feature, the SPDK NVMe-oF Target throws error: 
“ctrlr.c:1008:spdk_nvmf_ctrlr_set_features_host_identifier: *ERROR*: Set Features - Host Identifier not allowed”.

2) When the NVMe host issues a Reservation Report command, the SPDK target throws error:
subsystem.c:1973:nvmf_ns_reservation_report: *ERROR*: NVMeoF uses extended controller data structure, please set EDS bit in cdw11 and try again

3) When the NVMe host issues a Reservation Register command, the following errors are observed
subsystem.c:1886:nvmf_ns_reservation_release: *ERROR*: No registrant or current key doesn't match with existing registrant key
subsystem.c:1638:nvmf_ns_reservation_register: *ERROR*: No registrant or current key doesn't match with existing registrant key

## Steps to Reproduce

1. NVMe host checks the ONCS field to determine if the controller supports reservations. SPDK NVMe-oF returns status indicating support for reservation. This step passed.

2. Since the controller supports reservation, the NVMe Host to issue a Set Features command with the Host Identifier feature to the NVMe Controller in order to set its Host Identifier for that controller.
SPDK NVMe-oF Target throws error “ctrlr.c:1008:spdk_nvmf_ctrlr_set_features_host_identifier: *ERROR*: Set Features - Host Identifier not allowed”. 
Here are the debug logs:
thread.c: 519:spdk_thread_poll: *DEBUG*: Timed poller 0x55b255068530 returned -1
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b255148600) recv pdu entering state 0
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b255148600) recv state=1
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b255148600) recv state=2
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b255148600) recv pdu entering state 2
tcp.c:1743:spdk_nvmf_tcp_pdu_psh_handle: *DEBUG*: pdu type of tqpair(0x55b255148600) is 4
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 1 on tqpair=0x55b255148600
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 2 on tqpair=0x55b255148600
tcp.c:2178:spdk_nvmf_tcp_req_parse_sgl: *DEBUG*: In-capsule data: offset 0x0, length 0x8
tcp.c:2367:spdk_nvmf_tcp_pdu_set_buf_from_req: *DEBUG*: Not need to send r2t for tcp_req(0x55b25506aaf0) on tqpair=0x55b255148600
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b255148600) recv state=3
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 4 on tqpair=0x55b255148600
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b255148600) recv pdu entering state 3
tcp.c:1630:spdk_nvmf_tcp_pdu_payload_handle: *DEBUG*: enter
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b255148600) recv state=0
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 5 on tqpair=0x55b255148600
ctrlr.c:2504:nvmf_trace_command: *DEBUG*: Admin cmd: opc 0x09 fuse 0 cid 7 nsid 0 cdw10 0x00000081
ctrlr.c:2523:nvmf_trace_command: *DEBUG*: SGL: Data block: offs 0x0 len 0x8
ctrlr.c:1008:spdk_nvmf_ctrlr_set_features_host_identifier: *ERROR*: Set Features - Host Identifier not allowed
ctrlr.c:2475:spdk_nvmf_request_complete: *DEBUG*: cpl: cid=7 cdw0=0x00000000 rsvd1=0 status=0x0018
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 7 on tqpair=0x55b255148600
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 8 on tqpair=0x55b255148600
tcp.c:2327:request_transfer_out: *DEBUG*: enter
tcp.c:1443:spdk_nvmf_tcp_send_capsule_resp_pdu: *DEBUG*: enter, tqpair=0x55b255148600
tcp.c: 389:nvmf_tcp_request_free: *DEBUG*: tcp_req=0x55b25506aaf0 will be freed
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 10 on tqpair=0x55b255148600
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 0 on tqpair=0x55b255148600
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 0 on tqpair=0x55b255148600
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b25506aaf0 entering state 0 on tqpair=0x55b255148600
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b255148600) recv pdu entering state 0

3. For each active namespace attached to the NVMe Controller: 
i. Configure the NVMe Host to issue a Reservation Report command to the NVMe Controller.
ii. Configure the NVMe Host to issue a Get Features command with the Reservation Persistence feature to the NVMe Controller. 
We get the following debug logs for the error in this step
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514e210) recv pdu entering state 0
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514e210) recv state=1
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514e210) recv state=2
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514e210) recv pdu entering state 2
tcp.c:1743:spdk_nvmf_tcp_pdu_psh_handle: *DEBUG*: pdu type of tqpair(0x55b25514e210) is 4
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 1 on tqpair=0x55b25514e210
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 2 on tqpair=0x55b25514e210
tcp.c:2178:spdk_nvmf_tcp_req_parse_sgl: *DEBUG*: In-capsule data: offset 0x0, length 0x8
tcp.c:2367:spdk_nvmf_tcp_pdu_set_buf_from_req: *DEBUG*: Not need to send r2t for tcp_req(0x55b255b5b4a0) on tqpair=0x55b25514e210
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514e210) recv state=3
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 4 on tqpair=0x55b25514e210
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514e210) recv pdu entering state 3
tcp.c:1630:spdk_nvmf_tcp_pdu_payload_handle: *DEBUG*: enter
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514e210) recv state=0
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 5 on tqpair=0x55b25514e210
ctrlr.c:2504:nvmf_trace_command: *DEBUG*: I/O cmd: opc 0x15 fuse 0 cid 17 nsid 1 cdw10 0x00000100
ctrlr.c:2523:nvmf_trace_command: *DEBUG*: SGL: Data block: offs 0x0 len 0x8
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 6 on tqpair=0x55b25514e210
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514e210) recv pdu entering state 0
subsystem.c:1874:nvmf_ns_reservation_release: *DEBUG*: RELEASE: RRELA 0, IEKEY 0, RTYPE 1, CRKEY 0x1
subsystem.c:1886:nvmf_ns_reservation_release: *ERROR*: No registrant or current key doesn't match with existing registrant key
ctrlr.c:2475:spdk_nvmf_request_complete: *DEBUG*: cpl: cid=17 cdw0=0x00000000 rsvd1=0 status=0x0106
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 7 on tqpair=0x55b25514e210
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 8 on tqpair=0x55b25514e210
tcp.c:2327:request_transfer_out: *DEBUG*: enter
tcp.c:1443:spdk_nvmf_tcp_send_capsule_resp_pdu: *DEBUG*: enter, tqpair=0x55b25514e210
tcp.c: 389:nvmf_tcp_request_free: *DEBUG*: tcp_req=0x55b255b5b4a0 will be freed
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 10 on tqpair=0x55b25514e210
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 0 on tqpair=0x55b25514e210
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x55b255b5b4a0 entering state 0 on tqpair=0x55b25514e210

4. Perform a Reservation Release command with the RRELA field set to 001b (Clear) for all existing reservations.
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514d5d0) recv pdu entering state 0
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514d5d0) recv state=1
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514d5d0) recv state=2
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514d5d0) recv pdu entering state 2
tcp.c:1743:spdk_nvmf_tcp_pdu_psh_handle: *DEBUG*: pdu type of tqpair(0x55b25514d5d0) is 4
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 1 on tqpair=0x55b25514d5d0
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 2 on tqpair=0x55b25514d5d0
tcp.c:2178:spdk_nvmf_tcp_req_parse_sgl: *DEBUG*: In-capsule data: offset 0x0, length 0x10
tcp.c:2367:spdk_nvmf_tcp_pdu_set_buf_from_req: *DEBUG*: Not need to send r2t for tcp_req(0x7f6dcc0a7a68) on tqpair=0x55b25514d5d0
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514d5d0) recv state=3
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 4 on tqpair=0x55b25514d5d0
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514d5d0) recv pdu entering state 3
tcp.c:1630:spdk_nvmf_tcp_pdu_payload_handle: *DEBUG*: enter
tcp.c:1217:spdk_nvmf_tcp_qpair_set_recv_state: *DEBUG*: tqpair(0x55b25514d5d0) recv state=0
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 5 on tqpair=0x55b25514d5d0
ctrlr.c:2504:nvmf_trace_command: *DEBUG*: I/O cmd: opc 0x0d fuse 0 cid 84 nsid 1 cdw10 0x00000001
ctrlr.c:2523:nvmf_trace_command: *DEBUG*: SGL: Data block: offs 0x0 len 0x10
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 6 on tqpair=0x55b25514d5d0
subsystem.c:1597:nvmf_ns_reservation_register: *DEBUG*: REGISTER: RREGA 1, IEKEY 0, CPTPL 0, NRKEY 0x1, NRKEY 0x0
subsystem.c:1638:nvmf_ns_reservation_register: *ERROR*: No registrant or current key doesn't match with existing registrant key
tcp.c:1889:spdk_nvmf_tcp_sock_process: *DEBUG*: tqpair(0x55b25514d5d0) recv pdu entering state 0
reactor.c: 207:get_rusage: *INFO*: Reactor 2: 1 voluntary context switches and 0 involuntary context switches in the last second.
ctrlr.c:2475:spdk_nvmf_request_complete: *DEBUG*: cpl: cid=84 cdw0=0x00000000 rsvd1=0 status=0x0106
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 7 on tqpair=0x55b25514d5d0
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 8 on tqpair=0x55b25514d5d0
tcp.c:2327:request_transfer_out: *DEBUG*: enter
tcp.c:1443:spdk_nvmf_tcp_send_capsule_resp_pdu: *DEBUG*: enter, tqpair=0x55b25514d5d0
tcp.c: 389:nvmf_tcp_request_free: *DEBUG*: tcp_req=0x7f6dcc0a7a68 will be freed
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 10 on tqpair=0x55b25514d5d0
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 0 on tqpair=0x55b25514d5d0
tcp.c:2414:spdk_nvmf_tcp_req_process: *DEBUG*: Request 0x7f6dcc0a7a68 entering state 0 on tqpair=0x55b25514d5d0

## Context (Environment including OS version, SPDK version, etc.)
Test Setup: SPDK NVMe-oF Target (8 Optane SSDs, 4 lvols per SSD exported over NVMe-oF via TCP, RNIC – Mellanox ConnectX5). Kernel v5.1.0 Host using Mellanox ConnectX4 RNIC.
SPDK Commit ID 8ac86b24a2363072c84e0eb1b2d7e40dfd9f281f
--

**Comment by changpe1** [comment]
Let's see the following definition from the NVMe specification, for NVMe over Fabrics, the Host Identifier can't be modified, so this should be a third part issue, or we must specify the transport option when using UNH test suites.

5.21.1.26.2 NVMe over Fabrics Implementations
The Host Identifier is a mandatory feature in NVMe over Fabrics implementations. The Host Identifier shall be an extended 128-bit Host Identifier. The Host Identifier shall be set to a non-zero value in the Fabrics Connect command. The Host Identifier shall not be modified. A Set Features command specifying the Host Identifier Feature shall be aborted with a status of Command Sequence Error. A Get Features command specifying the Host Identifier Feature shall return the value set in the Fabrics Connect command.

**Comment by darsto** [comment]
Bug scrub: @benlwalker to confirm it's a test bug.

**Comment by benlwalker** [comment]
I can confirm these are all test bugs. The NVMe-oF target behavior is correct. It seems that the test is using the local PCIe rules but there is separate handling specified for fabrics devices.

**Comment by jimharris** [comment]
@KariukiJ can you give feedback on this bug back to UNH as well?  Thanks.  (Let's leave this one closed and we'll track UNH feedback through #817).
