### ISSUE TITLE
SPDK compress bdev issue while running FIO

### ISSUE THREAD

**Issue by vermavis** [spdk/spdk#813]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

While running 4K writes using FIO to a compressed bdev volume on top of thin provisioned LVOL, I noticed a seg fault. FIO was ran with verify to make sure written data is also correctly read back.

## Expected Behavior

Seg fault should not happen.

## Current Behavior

Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid42322 ]
[New Thread 0x7fff9cdc5700 (LWP 42440)]
EAL: No free hugepages reported in hugepages-1048576kB
vbdev_compress.c: 314:vbdev_init_compress_drivers: *NOTICE*: created virtual PMD compress_isal
vbdev_compress.c:1370:vbdev_compress_claim: *NOTICE*: registered io_device and virtual bdev for: COMP_d6099c98-e902-422f-a299-fd895bfafffa
[New Thread 0x7fff9d5c6700 (LWP 42441)]
process_isal_inflate(): Input buffer could not be read entirely

vbdev_compress.c: 564:comp_dev_poller: *ERROR*: deque status 3
vbdev_compress.c: 382:_spdk_reduce_rw_blocks_cb: *ERROR*: status -22 on operation from reduce API
fio: io_u error on file COMP_d6099c98-e902-422f-a299-fd895bfafffa: Input/output error: write offset=21652520960, buflen=4096
fio: pid=42441, err=5/file:io_u.c:1785, func=io_u error, error=Input/output error

Thread 117 "fio" received signal SIGSEGV, Segmentation fault.

## Steps to Reproduce

1. Create a nvme bdev and then create a thin provisioned LVOL on top of it 
2. Run FIO against a compressed bdev volume for an hour.
3. Turn on 'verify' with FIO

./scripts/rpc.py construct_nvme_bdev -b Nvme0 -t pcie -a 0000:5e:00.0
./scripts/rpc.py destroy_lvol_store -l LVS0
./scripts/rpc.py construct_lvol_store Nvme0n1 LVS0
.//scripts/rpc.py construct_lvol_bdev -t -l LVS0 lvol0 1024000
./scripts/rpc.py construct_compress_bdev -b Nvme0n1 -p /mnt/pmem/ -d compress_isal

## Context (Environment including OS version, SPDK version, etc.)

FIO config

[global]
ioengine=/home/vermavis/spdk/examples/bdev/fio_plugin/fio_plugin
spdk_conf=/home/vermavis/spdk/examples/bdev/fio_plugin/bdev.conf
thread=1
group_reporting=1
direct=1
verify=sha512
time_based=1
ramp_time=10
runtime=21600
iodepth=32
rw=randwrite
bs=4K

[test]
filename=COMP_d6099c98-e902-422f-a299-fd895bfafffa
cpumask=0x1

SPDK commit: 3a0886c408bbe3f

**Comment by peluse** [comment]
FYI the patch that is still pending to add compress tests to CI just caught a very similar issue so that's kidna re-assuring.

**Comment by vermavis** [comment]
Cool, glad that it’s reproducible.

**Comment by peluse** [comment]
blah, this is something different

**Comment by peluse** [comment]
Hey Vishal, looking at your steps to repro:
./scripts/rpc.py construct_compress_bdev -b Nvme0n1 -p /mnt/pmem/ -d compress_isal
Not sure if you pasted this wrong here but you are specifying the nvme bdev as the base for compression, not the lvol. The name of the compress dev in your output clearly shows its on the lvol though, can you double check?

**Comment by vermavis** [comment]
That was the typo…
I am using UUID rather than just specifying nvme bdev. Somehow I ended up copying old command.
The right command is following:

./scripts/rpc.py construct_compress_bdev -b $UUID -p /mnt/pmem -d compress_isal

**Comment by peluse** [comment]
OK, thanks.  Working to repro...

**Comment by peluse** [comment]
See https://review.gerrithub.io/c/spdk/spdk/+/457818

**Comment by peluse** [comment]
note: I've had 2 systems running this patch w/same fio script was was used here for 20+ hours.  Prior I was able to reppro

**Comment by darsto** [comment]
Fix merged. Thanks for reporting!
