### ISSUE TITLE
spdk_app_start: start_fn called twice when JSON config is used

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#816]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

When starting SPDK application with JSON config, start_fn is called twice. This prevents test/app/bdev_svc/bdev_svc from starting up, as it tries to create sentinel file twice.

## Expected Behavior
The start_fn callback should be called once.

## Current Behavior
The callback is called twice.

## Steps to Reproduce
```
# cat config.json
{
  "subsystems": [
    {
      "subsystem": "copy",
      "config": null
    },
    {
      "subsystem": "bdev",
      "config": []
    },
    {
      "subsystem": "nbd",
      "config": []
    }
  ]
}
# rm -f /var/run/spdk_bdev-1
# test/app/bdev_svc/bdev_svc --json config.json
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: bdev_svc --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid15973 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
could not create sentinel file /var/run/spdk_bdev-1
```

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 18.04, SPDK fc3e1b6fb0b92f91b3f0cd1ce78e3351e7d8003d

**Comment by darsto** [comment]
Pushed a fix: https://review.gerrithub.io/c/spdk/spdk/+/458351

Thanks
