### ISSUE TITLE
construct_lvol_store could not find the bdev device

### ISSUE THREAD

**Issue by bbdsxl** [spdk/spdk#818]
Hope here is the right place for help about SPDK issue.

I tried to create a lvs but failed.
root@converge02:/opt/spdk/scripts# ./rpc.py construct_lvol_store Nvme1n1 converge02-Nvme1n1
request:
{
  "method": "construct_lvol_store",
  "req_id": 1,
  "bdev_name": "Nvme1n1",
  "lvs_name": "converge02-Nvme1n1"
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "No such device"
}

While I could get the device by below RPC call:
root@converge02:/opt/spdk/scripts# ./rpc.py get_bdevs -b Nvme1n1
[
  {
    "name": "Nvme1n1",
    "aliases": [],
    "product_name": "NVMe disk",
    "block_size": 512,
    "num_blocks": 2000409264,
    "assigned_rate_limits": {
      "rw_ios_per_sec": 0,
      "rw_mbytes_per_sec": 0,
      "r_mbytes_per_sec": 0,
      "w_mbytes_per_sec": 0
    },
    "claimed": true,
    "supported_io_types": {
      "read": true,
      "write": true,
      "unmap": true,
      "write_zeroes": true,
      "flush": true,
      "reset": true,
      "nvme_admin": true,
      "nvme_io": true
    },
    "driver_specific": {
      "nvme": {
        "pci_address": "0000:01:00.0",
        "trid": {
          "trtype": "PCIe",
          "traddr": "0000:01:00.0"
        },
        "ctrlr_data": {
          "vendor_id": "0x144d",
          "model_number": "PM961 NVMe SAMSUNG 1024GB",
          "serial_number": "S33XNX0J104444",
          "firmware_revision": "CXY74D1Q",
          "oacs": {
            "security": 1,
            "format": 1,
            "firmware": 1,
            "ns_manage": 0
          }
        },
        "vs": {
          "nvme_version": "1.2"
        },
        "csts": {
          "rdy": 1,
          "cfs": 0
        },
        "ns_data": {
          "id": 1
        }
      }
    }
  }
]

## Expected Behavior
The lvs should be created without issue.

## Current Behavior
Could not find the bdev device and failed

## Possible Solution
Not sure

## Steps to Reproduce
1. start a target with below config file and command.
root@converge02:/opt/spdk/app/nvmf_tgt# cat nvmf.conf.in
# Bracketed ([]) names define sections

[Global]
  # Tracepoint group mask for spdk trace buffers

# Define NVMf protocol global options
[Nvmf]
  # Set how often the acceptor polls for incoming connections. The acceptor is also
  # responsible for polling existing connections that have gone idle. 0 means continuously
  # poll. Units in microseconds.
  AcceptorPollRate 10000

[Nvme]
TransportId "trtype:PCIe traddr:0000:06:00.0" Nvme3
TransportId "trtype:PCIe traddr:0000:02:00.0" Nvme2
TransportId "trtype:PCIe traddr:0000:01:00.0" Nvme1

#TransportId "trtype:PCIe traddr:0000:01:00.0" Nvme1

# One valid transport type must be set in each [Transport].
# The first is the case of RDMA transport and the second is the case of TCP transport.
[Transport]
  # Set RDMA transport type.
  Type RDMA

# Namespaces backed by physical NVMe devices
[Subsystem1]
  NQN nqn.2019-04.io.spdk:converge02d1
  SN SPDK00CONVERGE0201
  Listen RDMA 192.168.100.26:4420
  AllowAnyHost Yes
  MaxNamespaces 20
  Namespace Nvme1n1 1
[Subsystem2]
  NQN nqn.2019-04.io.spdk:converge02d2
  SN SPDK00CONVERGE0202
  Listen RDMA 192.168.100.26:4420
  AllowAnyHost Yes
  MaxNamespaces 20
  Namespace Nvme2n1 1
[Subsystem3]
  NQN nqn.2019-04.io.spdk:converge02d3
  SN SPDK00CONVERGE0203
  Listen RDMA 192.168.100.26:4420
  AllowAnyHost Yes
  MaxNamespaces 20
  Namespace Nvme3n1 1

SPDKHOME=/opt/spdk
echo "Start the NVME Target now"
HUGEMEM=10240 $SPDKHOME/scripts/setup.sh >/dev/null
nohup $SPDKHOME/app/nvmf_tgt/nvmf_tgt -c $SPDKHOME/app/nvmf_tgt/nvmf.conf.in -r /var/tmp/spdk.sock >nvmetarget.log 2>&1 &

## Context (Environment including OS version, SPDK version, etc.)
root@converge02:/opt/spdk/scripts# ./rpc.py get_spdk_version
{'version': 'SPDK v19.07-pre', 'fields': {'major': 19, 'minor': 7, 'patch': 0, 'suffix': '-pre'}}

OS: 
root@converge02:/opt/spdk/scripts# uname -a
Linux converge02 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

If anything is needed please let me know.
Thanks.

**Comment by tomzawadzki** [comment]
Hi @bbdsxl,

From get_bdevs() call it seems that Nvme1n1 is already claimed - meaning it was opened for some other use. It is confirmed by the provided configuration file where Nvme1n1 is used for Subsystem1. 
Before you get the chance to create an lvol store on the NVMe device, it was already setup to be exposed via NVMe-oF. This should be more clear when browsing the output from nvmf_tgt - there should be line for ```Could not open %s - %s module already claimed it```.

If you would like to expose an lvol store via NVMe-oF, instead of directly attaching the device to the Namespace. First create lvol store, then as many lvol bdevs as needed and as last step expose those lvol bdevs through NVMe-oF.
Please keep in mind that lvol store and lvol bdevs keep metadata on the device, so they need to be created just once.

Please let me know if this is what you are seeing and proposed way resolves the issue for you.

**Comment by bbdsxl** [comment]
@tomzawadzki Thank you so much.
Last night I stopped the previous target service and created a new one by RPC call and this time it worked really well.
Thanks again.
