### ISSUE TITLE
HotInNvme bdevs were unexpectedly created when set HotplugEnable Yes

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#820]
When I start a nvmf target with one nvme bdev by conf file, HotInNvme bdevs were unexpectedly created.

Attached nvmf.conf:
```
[Global]
[Bdev]
[Nvmf]
  AcceptorPollRate 10000
[Transport]
  Type RDMA
  MaxQueueDepth 1024
  MaxQueuesPerSession 8
  InCapsuleDataSize 4096
  MaxIOSize 131072
[Nvme]
  TransportID "trtype:PCIe traddr:0000:03:00.0" Nvme0
  RetryCount 4
  TimeoutUsec 0
  ActionOnTimeout None
  AdminPollRate 100000
  HotplugEnable Yes
[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.11.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace Nvme0n1
```

Log as bellow:
./scripts/rpc.py get_bdevs
```
[
  {
    "name": "Nvme0n1",
    "claimed": true,
......
  {
    "name": "HotInNvme0n1",
    "claimed": false,
......
  {
    "name": "HotInNvme1n1",
    "claimed": false,
......
  {
    "name": "HotInNvme2n1",
    "claimed": false,

```

## Expected Behavior
HotInNvme bdevs were not created without command.

## Current Behavior
HotInNvme bdevs were created without command.

## Possible Solution
investigate c code about hotplug

## Steps to Reproduce
1. ./app/nvmf_tgt/nvmf_tgt -c nvmf.conf
2. ./scripts/rpc.py get_bdevs
3. parted -s /dev/nvme0n1 mklabel msdos
    parted -s /dev/nvme1n1 mklabel msdos
4. retry
(Format all nvme disks then retry , the result is the same.)
(Set "HotplugEnable No" , HotInNvme bdevs were not created without command.)

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit 4cc2d1d814ff41b4c1b9894c603b13b7d926075b

**Comment by glodfish-zg** [comment]
@wanghailiangx 
Did you do the NVMe disk hotplug operation?

**Comment by wanghailiangx** [comment]
@glodfish-zg No hotplug operation.

**Comment by darsto** [comment]
That's just how hotplug works today.
