### ISSUE TITLE
 Failed to create SPDK bdevs from Virtio-Block: EAL: Driver cannot attatch the device (0000:00:06.0)

### ISSUE THREAD

**Issue by JunPiaoHW** [spdk/spdk#824]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

SPDK bdevs can be created via rpc.py construct_virtio_dev successfully.
## Current Behavior

The below command exec failed:
# rpc.py construct_virtio_dev --dev-type blk --trtype pci --traddr 0000:01:00.0 VirtioBlk1
EAL: Driver cannot attach the device (0000:00:06.0)
EAL: Failed to attach device on  primary process
## Steps to Reproduce

1. ./app/vhost/vhost -S /home/ -r /home/rpc_sock -m 0x1
2. ./scripts/rpc.py -s /home/rpc_sock construct_virtio_dev --dev-type blk --trtype pci --traddr 0000:00:06.0 VirtioBlk1

## Context (Environment including OS version, SPDK version, etc.)

centos7.6
SPDK 19.04

**Comment by darsto** [comment]
Have you bound your virtio device to vfio or uio kernel driver?

You can run `scripts/setup.sh` script to automatically bind all available virtio devices (the ones without any mounted filesystem on top).

**Comment by JunPiaoHW** [comment]
Thanks, I wil try it.

**Comment by JunPiaoHW** [comment]
> Have you bound your virtio device to vfio or uio kernel driver?
> 
> You can run `scripts/setup.sh` script to automatically bind all available virtio devices (the ones without any mounted filesystem on top).
Thanks, I wil try it.
