### ISSUE TITLE
NVMe-oF assertion from Nightly testing

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#827]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

An assert is triggered from the nightly testing (https://10.102.17.104:8080/job/Vhost_tests/job/vhost_autotest/29341/artifact/build.log).

This is regard vhost live migration and with a NVMe-oF backend.

## Expected Behavior

No error will happen during the vhost live migration.

## Current Behavior

INFO: Running local fio on VM 1
  08:33:00	# vm_ssh 1 'nohup /root/fio /root/migration-tc2.job 1>/root/migration-tc2.job.out 2>/root/migration-tc2.job.out </dev/null & echo $! > /root/fio.pid'
  08:33:00	# vm_num_is_valid 1
  08:33:00	# [[ 1 =~ ^[0-9]+$ ]]
  08:33:00	# return 0
  08:33:00	# vm_create_ssh_config
  08:33:00	# local ssh_config=/var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/ssh_config
  08:33:00	# [[ ! -f /var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/ssh_config ]]
  08:33:00	# local ssh_config=/var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/ssh_config
   08:33:00	# vm_ssh_socket 1
   08:33:00	# vm_num_is_valid 1
   08:33:00	# [[ 1 =~ ^[0-9]+$ ]]
   08:33:00	# return 0
   08:33:00	# local vm_dir=/var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/1
   08:33:00	# cat /var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/1/ssh_socket
  08:33:00	# local 'ssh_cmd=ssh -i /root/.ssh/spdk_vhost_id_rsa -F /var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/ssh_config 		-p 10100  127.0.0.1'
  08:33:00	# shift
  08:33:00	# ssh -i /root/.ssh/spdk_vhost_id_rsa -F /var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/ssh_config -p 10100 127.0.0.1 'nohup /root/fio /root/migration-tc2.job 1>/root/migration-tc2.job.out 2>/root/migration-tc2.job.out </dev/null & echo $! > /root/fio.pid'
  08:33:00	# false
  08:33:00	# sleep 0.5
rdma.c:3319:_qp_reset_failed_sends: *ERROR*: Failed to post a send for the qpair 0x612000002440 with errno 12
nvmf_tgt: rdma.c:3328: _qp_reset_failed_sends: Assertion `rqpair->current_read_depth > 0' failed.
  08:33:00	# return 0
  08:33:00	# sleep 5
/var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/test/vhost/migration/migration-tc2.sh: line 161: 414535 Aborted                 (core dumped) $rootdir/app/nvmf_tgt/nvmf_tgt -s 512 -m 0x4 -r $nvmf_dir/rpc.sock --wait-for-rpc  (wd: /var/jenkins/workspace/Vhost_tests/vhost_autotest/vhost0)
  08:33:05	# is_fio_running 1
   08:33:05	# [[ hxBE =~ x ]]
   08:33:05	# echo 'set -x'
  08:33:05	# local 'shell_restore_x=set -x'
  08:33:05	# set +x
  08:33:05	# return 0
  08:33:05	# vm_migrate 1

## Possible Solution

Not yet

## Steps to Reproduce

Nightly testing output link is attached

## Context (Environment including OS version, SPDK version, etc.)

Also refer to above link.

**Comment by Comphix** [comment]
Below is the assertion. It is expecting "rqpair->current_read_depth > 0" where this variable is ZERO in this case. Could be somewhere this variable is not increased (before trying to decrease here)?

nvmf_tgt: rdma.c:3328: _qp_reset_failed_sends: Assertion `rqpair->current_read_depth > 0' failed.

**Comment by Comphix** [comment]
Assign to Changpeng to take a look. Thanks.

**Comment by darsto** [comment]
Bug scrub: @changpe1 any update?

**Comment by tomzawadzki** [comment]
[Bug scrub] migration-tc2.sh test is running as part of nightly tests, at this time not reporting any failures.
As well since that time fixes to NVMf qpair allocation have been done. @Seth5141 will take a look and post an update.

**Comment by Seth5141** [comment]
After looking through the patches merged since this issue was posted, I can't find a specific one that was geared towards fixing this assert. In fact all of the lines of code that reference this variable (current_read_depth) haven't been touched for a while.
That being said, it's not impossible that some overarching macro change like:
f0b7a6e7d1c9a5df607ba0c628c58ae701b5b584 or
5282edfd7bae6f4d1b450e28c2f8a596e284e69f
which fix double frees of qpairs in certain error conditions couldn't prevent a weird state where we are trying to post a send and the current_read_depth value has been reset.
I haven't seen this hit recently in the test pool, but it could be worth manually testing for a bit before closing this issue entirely.

**Comment by jimharris** [comment]
This issue hasn't been seen in ages.
