### ISSUE TITLE
Should NVMe PMD driver check CSTS.CFS field in nvme_pcie_qpair_complete_tracker()?

### ISSUE THREAD

**Issue by uchida2016** [spdk/spdk#83]
The following sentences are in NVMe specification 1.2.1 in page 217.

> 9.5 Controller Fatal Status Condition
> If the controller has a serious error condition and is unable to communicate with host software via completion queue entries in the Admin or I/O Completion Queues, then the controller may set the Controller Fatal Status (CSTS.CFS) field to ‘1’. This indicates to host software that a serious error condition has occurred. **When this condition occurs, host software should reset and then re-initialize the controller.**
> The Controller Fatal Status condition is not indicated with an interrupt. **If host software experiences timeout conditions and/or repeated errors, then host software should consult the Controller Fatal Status (CSTS.CFS) field** to determine if a more serious error has occurred.

Should NVMe PMD driver check CSTS.CFS in nvme_pcie_qpair_complete_tracker() and reset controller if CSTS.CFS is 1?

**Comment by dverkamp-intel** [comment]
We definitely don't want to read CSTS on every completion, since that would be a major performance hit (NVMe is designed to avoid requiring any MMIO reads in the command submission and completion path).

However, it could make sense to check CSTS.CFS  in spdk_nvme_ctrlr_process_admin_completions(), since that is already a less-performance-sensitive path and is already taking the ctrlr_lock.

**Comment by uchida2016** [comment]
We need to read CSTS only when an IO is returned with an error.
I think spdk_nvme_ctrlr_process_admin_completions is not good, because it might not be called when there are outstanding IO commands, but no outstanding admin commands.

**Comment by benlwalker** [comment]
I agree - we should consult CSTS.CFS when an I/O is returned to the user with an error. We may even need to limit this to very specific errors (i.e. don't consult when the error is due to bad user input).

**Comment by jimharris** [comment]
Bumping this issue.

I agree that CSTS.CFS should be checked, but I don't think we want the NVMe driver to do this automatically.  I think we want the application to check CSTS.CFS and then issue the reset if desired.

The NVMe bdev driver does this currently - when timeouts are enabled, if an I/O timeouts, it will check CSTS.CFS and issue a reset if it is set.  It's possible we may want to add CFS checks in other places in the NVMe bdev driver, although I'd expect CSTS.CFS=1 conditions to result in I/O timeouts, not I/O completions with error status.

@benlwalker @changpe1 - thoughts?

**Comment by changpe1** [comment]
> Bumping this issue.
> 
> I agree that CSTS.CFS should be checked, but I don't think we want the NVMe driver to do this automatically. I think we want the application to check CSTS.CFS and then issue the reset if desired.
> 
> The NVMe bdev driver does this currently - when timeouts are enabled, if an I/O timeouts, it will check CSTS.CFS and issue a reset if it is set. It's possible we may want to add CFS checks in other places in the NVMe bdev driver, although I'd expect CSTS.CFS=1 conditions to result in I/O timeouts, not I/O completions with error status.
> 
> @benlwalker @changpe1 - thoughts?

It's make sense to check the status when timeout happened, or we may start a separate poller to monitor the state, I think this may be duplicate with existing implementation. I agree that we should not do this in the NVMe driver layer.

**Comment by benlwalker** [comment]
Yeah I believe the direction we wanted to go was that the user could manually check this in response to errors or timeouts.

**Comment by jimharris** [comment]
@benlwalker, @changpe1 - thanks for your input.

I'm going to close this issue, suggesting that the application do the CSTS.CFS check rather than doing it automatically in the driver.

**Comment by ReddyKilowatt** [comment]
@jimharris @benlwalker How can an application check the CDs bit using NVME CLI?
