### ISSUE TITLE
NVMe-oF core dump from Nightly testing

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#834]
A core dump happened from the nightly testing

https://10.102.17.104:8080/job/Vhost_tests/job/vhost_autotest/29639/artifact/build.log

   07:18:14	# local vm_dir=/var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/1
   07:18:14	# cat /var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/1/ssh_socket
  07:18:14	# local 'ssh_cmd=ssh -i /root/.ssh/spdk_vhost_id_rsa -F /var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/ssh_config 		-p 10100  127.0.0.1'
  07:18:14	# shift
  07:18:14	# ssh -i /root/.ssh/spdk_vhost_id_rsa -F /var/jenkins/workspace/Vhost_tests/vhost_autotest/vms/ssh_config -p 10100 127.0.0.1 'nohup /root/fio /root/migration-tc2.job 1>/root/migration-tc2.job.out 2>/root/migration-tc2.job.out </dev/null & echo $! > /root/fio.pid'
  07:18:14	# false
  07:18:14	# sleep 0.5
rdma.c:1672:23: runtime error: member access within null pointer of type 'struct ibv_send_wr'
    #0 0x7e958a in nvmf_rdma_request_fill_iovs_multi_sgl /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/rdma.c:1672
    #1 0x7ecc06 in spdk_nvmf_rdma_request_parse_sgl /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/rdma.c:1811
    #2 0x7f14ce in spdk_nvmf_rdma_request_process /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/rdma.c:1943
    #3 0x7ffa8f in spdk_nvmf_rdma_qpair_process_pending /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/rdma.c:2620
    #4 0x80dfb2 in spdk_nvmf_rdma_poller_poll /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/rdma.c:3513
    #5 0x80e286 in spdk_nvmf_rdma_poll_group_poll /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/rdma.c:3544
    #6 0x79e357 in spdk_nvmf_transport_poll_group_poll /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/transport.c:259
    #7 0x78ccaa in spdk_nvmf_poll_group_poll /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/nvmf/nvmf.c:98
    #8 0x835364 in spdk_thread_poll /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/thread/thread.c:491
    #9 0x81a45b in _spdk_reactor_run /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/event/reactor.c:272
    #10 0x81b460 in spdk_reactors_start /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/event/reactor.c:381
    #11 0x8140c0 in spdk_app_start /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/lib/event/app.c:688
    #12 0x4083d8 in main /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/app/nvmf_tgt/nvmf_main.c:75
    #13 0x7f0e8e42b11a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #14 0x408039 in _start (/var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/app/nvmf_tgt/nvmf_tgt+0x408039)

  07:18:15	# return 0
  07:18:15	# sleep 5
/var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/test/vhost/migration/migration-tc2.sh: line 161: 4049668 Aborted                 (core dumped) $rootdir/app/nvmf_tgt/nvmf_tgt -s 512 -m 0x4 -r $nvmf_dir/rpc.sock --wait-for-rpc  (wd: /var/jenkins/workspace/Vhost_tests/vhost_autotest/vhost0)
  07:18:20	# is_fio_running 1
   07:18:20	# [[ hxBE =~ x ]]
   07:18:20	# echo 'set -x'
  07:18:20	# local 'shell_restore_x=set -x'

## Expected Behavior

No core dump

## Current Behavior

A null pointer core dump hit
rdma.c:1672:23: runtime error: member access within null pointer of type 'struct ibv_send_wr'
    #0 0x7e958a in nvmf_rdma_request_fill_iovs_multi_sgl

## Possible Solution

N/A

## Steps to Reproduce

This is hit from the nightly testing.
https://10.102.17.104:8080/job/Vhost_tests/job/vhost_autotest/29639/

## Context (Environment including OS version, SPDK version, etc.)

Save as above.

**Comment by wanghailiangx** [comment]
Raised a patch to fix it: https://review.gerrithub.io/c/spdk/spdk/+/458913

**Comment by benlwalker** [comment]
Adding an assert can't possibly fix a crash. I agree that the above patch may make it easier to debug the issue.

**Comment by sashakot** [comment]
Hi 

Did the crash happen on soft roce, or real hw ?
Did you reproduce the problem ?

Best regards 
Sasha

**Comment by wanghailiangx** [comment]
@sashakot  I remember the crash only happened on soft roce. For now, this issue have not been reproduced in recent Nightly testing.
@Comphix  I think some other patches had fix it. So I suggest closing it.

**Comment by Comphix** [comment]
Close this as recently we have not seen the crash.
