### ISSUE TITLE
NVMEoF over omnipath performance degradation with more than 1 io thread

### ISSUE THREAD

**Issue by alekseymmm** [spdk/spdk#835]
Run spdk nvmeof target over omnipath. Run perf utility to check the performance. Sequential read in 1 thread shows about 1.3 GB/s but with 2 or more threads it is about 300MB/s. The similar behavior when I use fio and linux initiator with the same target.

## Expected Behavior

No performance drop

## Current Behavior

Explained above

## Possible Solution

No idea
## Steps to Reproduce

1.Start spdk target 
```
# ./app/spdk_tgt/spdk_tgt -m 0xfffffffff -c etc/spdk/am_nvmf.conf.in
```
with this config
```
[Global]
[Transport]
  Type RDMA
[Nvmf]
#  AcceptorPollRate 10000
  AcceptorPollRate 0

[Nvme]
  TransportID "trtype:PCIe traddr:0000:87:00.0" Nvme0
  RetryCount 4
  TimeoutUsec 0
  ActionOnTimeout None
  AdminPollRate 100000
  IOPollRate 0
  HotplugEnable No

[Subsystem1]
  NQN nqn.2019-06.hpc3.sky02:nvmf:nvmf01
  Listen RDMA 10.2.2.120:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN BTLN813207BR3P2BGN
  MaxNamespaces 2
  Namespace Nvme0n1 1
```
2. On the host side run single thread perf 
```
# ./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:10.2.2.120 trsvcid:4420' -c 0x1
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid82682 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No free hugepages reported in hugepages-2048kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Attached to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                                                 Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 0:   11299.30    1412.41    5671.64    2157.55   31571.67
========================================================
Total                                                                       :   11299.30    1412.41    5671.64    2157.55   31571.67

```
3. On the host side run multiple threads perf  
```
# ./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:10.2.2.120 trsvcid:4420' -c 0x3
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x3 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid82727 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No free hugepages reported in hugepages-2048kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Attached to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 1
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 1
Starting thread on core 0
========================================================
                                                                                                                 Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 1:     961.50     120.19   66862.60    2641.17  101904.45
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 0:     963.80     120.47   66695.89    2375.53   97356.44
========================================================
Total                                                                       :    1925.30     240.66   66779.15    2375.53  101904.45

```
4. Local performance of nvme drive is fine with any number of io threads
single thread local:
```
# ./perf -q 64 -o 131072 -w read -t 30 -r 'trtype:PCIe traddr:0000:87:00.0' -c 0x1
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid98082 ]
EAL: No free hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe Controller at 0000:87:00.0
Attached to NVMe Controller at 0000:87:00.0 [8086:0a54]
Associating PCIE (0000:87:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                    Latency(us)
Device Information             :       IOPS      MiB/s    Average        min        max
PCIE (0000:87:00.0) from core 0:   25764.67    3220.58    2484.06     200.86   12277.09
========================================================
Total                          :   25764.67    3220.58    2484.06     200.86   12277.09

```
multiple threads local :
```
# ./perf -q 64 -o 131072 -w read -t 30 -r 'trtype:PCIe traddr:0000:87:00.0' -c 0x3
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x3 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid98085 ]
EAL: No free hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe Controller at 0000:87:00.0
Attached to NVMe Controller at 0000:87:00.0 [8086:0a54]
Associating PCIE (0000:87:00.0) with lcore 1
Associating PCIE (0000:87:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 1
Starting thread on core 0
========================================================
                                                                    Latency(us)
Device Information             :       IOPS      MiB/s    Average        min        max
PCIE (0000:87:00.0) from core 1:   12857.33    1607.17    4978.04     182.02   21724.04
PCIE (0000:87:00.0) from core 0:   12872.10    1609.01    4971.74     200.82   21630.34
========================================================
Total                          :   25729.43    3216.18    4974.89     182.02   21724.04

```

## Context (Environment including OS version, SPDK version, etc.)

1. Centos 7.4 linux kernel 3.10.0-693.21.1
2. SPDK 18.04  (commit 9eb54cae6aca7ddefb501fe6e26d125d877d59c9) the same with SPDK 18.07 or latest 19.07 (commit d1a96e7cde77f1ba476ef3a96feb720f9a572251)
3. Non-Volatile memory controller: Intel Corporation Device 0a54
4. Fabric controller: Intel Corporation Omni-Path HFI Silicon 100 Series [integrated] (rev 11)

**Comment by alekseymmm** [comment]
I also tried it with null bdev. This config on target :
```
[Global]
[Transport]
  Type RDMA
[Nvmf]
#  AcceptorPollRate 10000
  AcceptorPollRate 0

[Null]
  Dev Null_0 10240000 512

[Subsystem1]
  NQN nqn.2019-06.hpc3.sky02:nvmf:nvmf01
  Listen RDMA 10.2.2.120:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN BTLN813207BR3P2BGN
  MaxNamespaces 2
  Namespace Null_0 1
```
On host side 
single thread  perf :
```
]# ./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:10.2.2.120 trsvcid:4420' -c 0x1
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid78872 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No free hugepages reported in hugepages-2048kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Attached to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                                                 Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 0:   57139.70    7142.46    1121.47     151.68   38032.85
========================================================
Total                                                                       :   57139.70    7142.46    1121.47     151.68   38032.85
```

2 threads perf :
```
]# ./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:10.2.2.120 trsvcid:4420' -c 0x3
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x3 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid78996 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No free hugepages reported in hugepages-2048kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Attached to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 1
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 1
Starting thread on core 0
========================================================
                                                                                                                 Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 1:   30317.00    3789.62    2112.32     124.28   57150.19
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 0:   47377.00    5922.12    1352.67     125.11   34671.34
========================================================
Total                                                                       :   77694.00    9711.75    1649.10     124.28   57150.19
```
4 threads perf :
```
# ./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:10.2.2.120 trsvcid:4420' -c 0xf
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xf --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid79156 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: No free hugepages reported in hugepages-2048kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Attached to NVMe over Fabrics controller at 10.2.2.120:4420: nqn.2019-06.hpc3.sky02:nvmf:nvmf01
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 3
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 2
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 1
Associating RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 3
Starting thread on core 2
Starting thread on core 1
Starting thread on core 0
========================================================
                                                                                                                 Latency(us)
Device Information                                                          :       IOPS      MiB/s    Average        min        max
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 3:   38615.20    4826.90    1657.50     123.89   17158.15
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 2:    8633.60    1079.20    7411.28     888.74  117442.46
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 1:    8902.40    1112.80    7166.83    1096.01  129073.51
RDMA (addr:10.2.2.120 subnqn:nqn.2019-06.hpc3.sky02:nvmf:nvmf01) from core 0:   38612.40    4826.55    1666.10     147.77  108768.10
========================================================
Total                                                                       :   94763.60   11845.45    2702.78     123.89  129073.51

```

**Comment by alekseymmm** [comment]
I have collected full trace (-e 0xFFFF) in case when performance drops down to 250 MB/s  with 2 io threads with nvmeof tgt with real nvme (not null). Hope it can help.
[am_trace.zip](https://github.com/spdk/spdk/files/3310036/am_trace.zip)

**Comment by KariukiJ** [comment]
@alekseymmm I am currently waiting to get access to a system that has Omni-Path NICs so that I can try to reproduce the issue and debug it further. I did run the workload on my system with Mellanox NICs and could not reproduce it.

**Comment by alekseymmm** [comment]
@KariukiJ The same is with me. I have run a lot of tests on Mellanox NIX and never seen such a problem.

**Comment by KariukiJ** [comment]
@alekseymmm I have a host and target that have Omni-Path NICs, but my target does not have an NVMe SSD so I am using a NULL block device. 
Here is what I am seeing:
NUMJOB=1, IOPS=66.8k, bw=8348MiB/s (8754MB/s)
NUMJOB=2, IOPS=93.5k, bw=11.4GiB/s (12.3GB/s)
NUMJOB=4, IOPS=94.5k, bw=11.5GiB/s (12.4GB/s)
NUMJOB=8, IOPS=89.8k,  bw=10.0GiB/s (11.8GB/s)
NUMJOB=16, IOPS=94.6k, bw=11.5GiB/s (12.4GB/s)
So with the Null block device the I see the expected behaviour where the performance increases as I increase the number of jobs till the link is saturated. Have you tried NULL block devices? I suspect that you will see the same behaviour.
I had a chat with our Omni-Path folks about configuring the link for the best performance and they gave me the doc attached. They highlighted section 3.5 as something that we need to pay attention to.

[27Oct_Config_NVMe_on_IntelOPA_AppNote_J78967.pdf](https://github.com/spdk/spdk/files/3424418/27Oct_Config_NVMe_on_IntelOPA_AppNote_J78967.pdf)

**Comment by alekseymmm** [comment]
@KariukiJ I tried Null bdev and posted results above in my first comment on this issue. And it seemed there was no performance degradation with nulls only with real nvme.

thanks for the recommendations of tunning performance (I never knew about the info in 3.5). I will try it asap.

**Comment by KariukiJ** [comment]
@alekseymmm I will add an SSD for my test environment and see if I can reproduce the issue.

**Comment by KariukiJ** [comment]
@alekseymmm Can you also collect a trace with just one thread so that we can compare it to the good trace with the one you collected for 2 threads where the performance drops and see what section of the code is taking longer?

**Comment by KariukiJ** [comment]
@alekseymmm I finally got back onto the system and ran the test with an SSD and still cannot reproduce the issue. In my environment, the bandwidth is saturated at 1 thread and I don't see any increase or decrease in the bandwidth as I increase the number of threads. The total performance stays at around 3200 MiBs as I go from 1 - 8 threads

1 Thread:
./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.2.1 trsvcid:4420' -c 0x1
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid28440 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0
========================================================
                                                                                                          Latency(us)
Device Information                                                   :       IOPS      MiB/s    Average        min        max
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 0:   25834.60    3229.32    2479.12    1658.07   18416.74
========================================================
Total                                                                :   25834.60    3229.32    2479.12    1658.07   18416.7

2 Threads
./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.2.1 trsvcid:4420' -c 0x3
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x3 --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid28465 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 1
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 1
Starting thread on core 0
========================================================
                                                                                                          Latency(us)
Device Information                                                   :       IOPS      MiB/s    Average        min        max
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 1:   12942.80    1617.85    4949.71    2445.32   27001.06
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 0:   12939.20    1617.40    4947.08     318.30   15383.49
========================================================
Total                                                                :   25882.00    3235.25    4948.39     318.30   27001.06

4 Threads
./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.2.1 trsvcid:4420' -c 0xF
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xF --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid28495 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 3
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 2
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 1
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 3
Starting thread on core 2
Starting thread on core 1
Starting thread on core 0
========================================================
                                                                                                          Latency(us)
Device Information                                                   :       IOPS      MiB/s    Average        min        max
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 3:    6489.40     811.17    9871.67     483.53   30848.24
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 2:    6480.00     810.00    9910.37    2449.49   76225.89
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 1:    6470.50     808.81    9921.38    5054.44   73921.63
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 0:    6476.60     809.58    9907.44    3057.99   72213.14
========================================================
Total                                                                :   25916.50    3239.56    9902.70     483.53   76225.89

8 Threads:
./perf -q 64 -o 131072 -w read -t 10 -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.2.1 trsvcid:4420' -c 0xFF
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xFF --no-pci --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid28508 ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Attached to NVMe over Fabrics controller at 192.168.2.1:4420: nqn.2016-06.io.spdk:cnode1
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 7
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 6
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 5
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 4
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 3
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 2
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 1
Associating RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 7
Starting thread on core 6
Starting thread on core 5
Starting thread on core 4
Starting thread on core 3
Starting thread on core 1
Starting thread on core 0
Starting thread on core 2
========================================================
                                                                                                          Latency(us)
Device Information                                                   :       IOPS      MiB/s    Average        min        max
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 7:    3274.20     409.27   19582.01     341.91   54844.58
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 6:    3261.20     407.65   19724.56    3166.12  173867.42
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 5:    3251.20     406.40   19854.21    5006.85  228341.04
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 4:    3244.80     405.60   19860.21    7477.81  153622.08
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 3:    3250.80     406.35   19927.70    4900.45  229754.79
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 2:    3270.50     408.81   19774.45    2418.64  211344.51
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 1:    3241.60     405.20   19934.92    9163.50  210278.17
RDMA (addr:192.168.2.1 subnqn:nqn.2016-06.io.spdk:cnode1) from core 0:    3241.10     405.14   19906.20    9925.96  198029.40
========================================================
Total                                                                :   26035.40    3254.42   19820.16     341.91  229754.79


The SSD I am using is Intel Corporation NVMe Datacenter SSD [3DNAND, Beta Rock Controller] [8086:0a54], which based on the device id you provided matches your ssd.

**Comment by tomzawadzki** [comment]
[Bug scrub] @KariukiJ Posted suggestions on how to get satisfactory performance over omnipath. @alekseymmm Please update if those help.
@Seth5141 Will take a look at this too.

**Comment by alekseymmm** [comment]
Unfortunately, I don't have access to this system so cannot check the performance anymore. I think we can close this issue and maybe this information will be useful for someone with a similar problem in the future.
