### ISSUE TITLE
g_bdev_opts related function has error

### ISSUE THREAD

**Issue by nightwise** [spdk/spdk#838]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

file: bdev.c
static struct spdk_bdev_opts	g_bdev_opts = { ... }
g_bdev_opts is not a pointer type.

function: 
spdk_bdev_get_opts(struct spdk_bdev_opts *opts)
{
    *opts = g_bdev_opts;  //NOTE: looks like wrong
}

int
spdk_bdev_set_opts(struct spdk_bdev_opts *opts)
{
    ......
    g_bdev_opts = *opts;  //NOTE: looks like wrong
}

function: spdk_bdev_initialize(...)
struct spdk_bdev_opts bdev_opts;
spdk_bdev_get_opts(&bdev_opts); <-- try to hold g_bdev_opts, but function assign non-ptr type g_bdev_opts to bdev_opts

## Expected Behavior

spdk_bdev_get_opts(struct spdk_bdev_opts **opts)
{
    *opts = &g_bdev_opts;
}

int
spdk_bdev_set_opts(struct spdk_bdev_opts *opts)
{
    ......
    memcpy(&g_bdev_opts, opts, sizeof(struct spdk_bdev_opts));
}

function: spdk_bdev_initialize(...)
struct spdk_bdev_opts *bdev_opts;
spdk_bdev_get_opts(&bdev_opts); <-- try to hold g_bdev_opts, but function assign non-ptr type g_bdev_opts to bdev_opts

**Comment by optimistyzy** [comment]
The code is correct，I did not see issue. *opts =g_bdev_opts is correct, it
copys the value of g_bdev_opts into the memory pointed by opts
variable(which is equal the memory copy method you mentioned). if we write
opts= g_bdev_opts, it is wrong.

在 2019年6月21日星期五，nightwise <notifications@github.com> 写道：

**Comment by nightwise** [comment]
Sorry, it should my poor knowledge of C that allow such operation.
And thanks for reply.
