### ISSUE TITLE
JSON config saved by some apps doesn't load on others

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#840]
It's not possible to load the configuration saved by e.g. spdk_tgt using other apps. This is probably related to the differences between the linked RPC libraries.

## Expected Behavior
The config should load successfully.

## Current Behavior
The config doesn't load.

## Possible Solution
All the RPC libraries should be grouped together, so the same are linked to all of the apps (for the same SPDK's configuration).

## Steps to Reproduce
```
# app/spdk_tgt/spdk_tgt &
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid24934 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
# scripts/rpc.py construct_nvme_bdev -b nvme1 -a 00:05.0 -t
# scripts/rpc.py save_config > config.json
# kill `pidof spdk_tgt`
# test/bdev/bdevperf/bdevperf -q 1 -o 4096 -w randwrite -t 60 --json ftl.json
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid2213 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
json_config.c: 195:rpc_client_poller: *ERROR*: error response: {"code":-32601,"message":"Method not found"}}
json_config.c: 135:spdk_app_json_config_load_done: *ERROR*: Config load failed. Stopping SPDK application.
app.c: 723:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero Test time less than one microsecond, no performance data will be shown
```

## Context (Environment including OS version, SPDK version, etc.)
To enable bdevperf to respond to RPCs I was using the following patch series: https://review.gerrithub.io/c/spdk/spdk/+/458599/2

**Comment by darsto** [comment]
*ERROR*: error response: {"code":-32601,"message":"Method not found"}}

I would suggest to make SPDK rpc server ignore this error if we're in the middle of loading the config. We can print a warning, but let's not fail the initialization.

**Comment by darsto** [comment]
Bug scrub: Jim suggests to add an option to ignore all init failures. We can still print error messages, but not fail.

**Comment by darsto** [comment]
Tomek allowed me to take this over
