### ISSUE TITLE
error on parsing transport section in configuration file

### ISSUE THREAD

**Issue by eyuval** [spdk/spdk#841]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

In file lib/event/subsystems/nvmf/conf.c the function spdk_nvmf_parse_transport gives the following error and exits, when parsing the RDMA transport section
SPDK_ERRLOG("C2HSuccess is relevant only for TCP transport '%s'\n", type);
I think for RDMA this should simply be ignored
## Steps to Reproduce

1.
2.
3.
4.

**Comment by changpe1** [comment]
@eyuval Thanks for submitting, the patch has been merged, and I'm going to close this issue.
