### ISSUE TITLE
error: dereferencing pointer to incomplete type

### ISSUE THREAD

**Issue by yangliang20065613** [spdk/spdk#842]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

**in file example/nvme/perf/perf.c,  failed to access the the members of struct spdk_nvme_ctrlr.**

compile error:
**error: dereferencing pointer to incomplete type**
## Expected Behavior

failed to compile the nvme perf tool when access the the members of struct spdk_nvme_ctrlr.
## Current Behavior

Build complete [x86_64-native-linuxapp-gcc]
make[3]: Leaving directory '/home/admin/matt/19.04/spdk/dpdk'
  CC examples/nvme/perf/perf.o
perf.c: In function 'register_ns':
perf.c:689:16: error: dereferencing pointer to incomplete type
  num_ns = ctrlr->num_ns;
                ^
perf.c:636:11: warning: variable 'num_ns' set but not used [-Wunused-but-set-variable]
  uint32_t num_ns;
           ^
/home/admin/matt/19.04/spdk/mk/spdk.common.mk:333: recipe for target 'perf.o' failed

## Steps to Reproduce

1.add the code to access the the members of struct spdk_nvme_ctrlr.

diff --git a/examples/nvme/perf/perf.c b/examples/nvme/perf/perf.c
index 9804154d1..dab427838 100644
--- a/examples/nvme/perf/perf.c
+++ b/examples/nvme/perf/perf.c
@@ -633,6 +633,7 @@ register_ns(struct spdk_nvme_ctrlr *ctrlr, struct spdk_nvme_ns *ns)
        const struct spdk_nvme_ctrlr_data *cdata;
        uint32_t max_xfer_size, entries, sector_size;
        uint64_t ns_size;
+       uint32_t num_ns;
        struct spdk_nvme_io_qpair_opts opts;

        cdata = spdk_nvme_ctrlr_get_data(ctrlr);
@@ -685,6 +686,7 @@ register_ns(struct spdk_nvme_ctrlr *ctrlr, struct spdk_nvme_ns *ns)
        entry->type = ENTRY_TYPE_NVME_NS;
        entry->fn_table = &nvme_fn_table;
        entry->u.nvme.ctrlr = ctrlr;
+       num_ns = ctrlr->num_ns;
        entry->u.nvme.ns = ns;
        entry->num_io_requests = g_queue_depth * entries;

2.compile the spdk code
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

SPDK version: 19.04.1

**Comment by yidong0635** [comment]
for personal use, the struct header file what you are accessing is not include in perf.c.

**Comment by yidong0635** [comment]
what perf.c now using  is an opaque define.
 /**
 * Opaque handle to a controller. Returned by spdk_nvme_probe()'s attach_cb.
 */
struct spdk_nvme_ctrlr;

**Comment by benlwalker** [comment]
spdk_nvme_ctrlr is intentionally opaque. If you want to get the number of namespaces, call the public API function for getting the number of namespaces (spdk_nvme_ctrlr_get_num_ns()).
