### ISSUE TITLE
[Question] qemu costs a lot of time to start when bind multi-queues vhost-user-device 

### ISSUE THREAD

**Issue by yangtianyu0706** [spdk/spdk#844]
Hi
we have vms that attached multi-queues vhost-user-device to connect spdk. it will cost a lot of time to turn it on.

The root cause is that in virtio_is_ready function. 

before 1d74fea0159ea617e31dfa9d34a78d7c7d4f8fbe this patch
all vq ready can start_device.

after 1d74fea0159ea617e31dfa9d34a78d7c7d4f8fbe this patch
one vq ready can start_device , when next vq ready will lead to destroy_device
if a qemu which a lot of multi-queues vhost-user-device has many queues it's
goint to cause it many times.

Is there any good way to improve the power-on performance?

**Comment by yangtianyu0706** [comment]
@darsto

**Comment by changpe1** [comment]
@yangtianyu0706 QEMU may not initialize all the IO queues when starting up, especially in the BIOS stage, so we add a workaround in SPDK, we will destroy the device and start it again when got a VQ ready message.

**Comment by yangtianyu0706** [comment]
> @yangtianyu0706 QEMU may not initialize all the IO queues when starting up, especially in the BIOS stage, so we add a workaround in SPDK, we will destroy the device and start it again when got a VQ ready message.

I know this. But do we have a better way to solve this problem? 
When BIOS stage, VQ may not initialize,  can we add a message like virtio spec driver_ok to tell the spdk start device and the same time setup VQ is initialized.

**Comment by changpe1** [comment]
> > @yangtianyu0706 QEMU may not initialize all the IO queues when starting up, especially in the BIOS stage, so we add a workaround in SPDK, we will destroy the device and start it again when got a VQ ready message.
> 
> I know this. But do we have a better way to solve this problem?
> When BIOS stage, VQ may not initialize, can we add a message like virtio spec driver_ok to tell the spdk start device and the same time setup VQ is initialized.

Even without the extra vhost-user message, SPDK can still address it with a better way, since we are using DPDK vhost-user library, so we have to add a workaround to it.

**Comment by changpe1** [comment]
@yangtianyu0706 Do you still have further question about this topic, if not I'm going to close it for now.  You can reach us via Slack for discussion online.

**Comment by yangtianyu0706** [comment]
> @yangtianyu0706 Do you still have further question about this topic, if not I'm going to close it for now. You can reach us via Slack for discussion online.

Ok
