### ISSUE TITLE
Solid nightly test failure for iSCSI data digest test

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#849]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Since 26th or 27th June, iSCSI data digest test in nightly test suites has failed.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/547/archive/iscsi_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/548/archive/iscsi_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/549/archive/iscsi_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/550/archive/iscsi_autotest/build.log

## Expected Behavior
The test passes without failures.

## Current Behavior

 09:14:49	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py construct_target_node Target3 Target3_alias Malloc0:0 1:2 64 -d
 09:14:49	# sleep 1
 09:14:50	# iscsiadm -m discovery -t sendtargets -p 10.0.0.1:3260
conn.c:1357:iscsi_conn_handle_incoming_pdus: *ERROR*: Failed to read pdu, error=-1
10.0.0.1:3260,1 iqn.2016-06.io.spdk:Target3
  09:14:50	# iscsiadm -m node -p 10.0.0.1:3260
  09:14:50	# grep DataDigest
 09:14:50	# DataDigestAbility='node.conn[0].iscsi.DataDigest = None'
 09:14:50	# '[' 'node.conn[0].iscsi.DataDigest = Nonex' = x ']'
 09:14:50	# iscsi_header_data_digest_test
 09:14:50	# timing_enter HeaderDigest_enabled
 09:14:50	# xtrace_disable
 09:14:50	# PREV_BASH_OPTS=ehxBE
 09:14:50	# set +x
 09:14:50	# xtrace_enable
 09:14:50	# node_login_fio_logout 'HeaderDigest -v CRC32C' 'DataDigest -v None'
 09:14:50	# for arg in "$@"
 09:14:50	# iscsiadm -m node -p 10.0.0.1:3260 -o update -n 'node.conn[0].iscsi.HeaderDigest' -v CRC32C
 09:14:50	# for arg in "$@"
 09:14:50	# iscsiadm -m node -p 10.0.0.1:3260 -o update -n 'node.conn[0].iscsi.DataDigest' -v None
iscsiadm: Cannot modify node.conn[0].iscsi.DataDigest. Invalid param name.
iscsiadm: Could not execute operation on all records: invalid parameter
  09:14:50	# trap - ERR
  09:14:50	# print_backtrace
  09:14:50	# [[ ehxBE =~ e ]]
  09:14:50	# xtrace_disable
  09:14:50	# PREV_BASH_OPTS=ehxBE
  09:14:50	# set +x
========== Backtrace start: ==========

in ./test/iscsi_tgt/digests/digests.sh:14 -> node_login_fio_logout()
     ...
   9   	# $2 = test type posix or vpp. defaults to posix.
   10  	iscsitestinit $1 $2
   11  	
   12  	function node_login_fio_logout() {
   13  		for arg in "$@"; do
=> 14  			iscsiadm -m node -p $TARGET_IP:$ISCSI_PORT -o update -n node.conn[0].iscsi.$arg
   15  		done
   16  		iscsiadm -m node --login -p $TARGET_IP:$ISCSI_PORT
   17  		waitforiscsidevices 1
   18  		$fio_py -p iscsi -i 512 -d 1 -t write -r 2
   19  		$fio_py -p iscsi -i 512 -d 1 -t read -r 2
     ...
in ./test/iscsi_tgt/digests/digests.sh:40 -> iscsi_header_data_digest_test()
     ...
   35  	}
   36  	
   37  	function iscsi_header_data_digest_test() {
   38  		# Only enable HeaderDigest to CRC32C
   39  		timing_enter HeaderDigest_enabled
=> 40  		node_login_fio_logout "HeaderDigest -v CRC32C" "DataDigest -v None"
   41  		timing_exit HeaderDigest_enabled
   42  	
   43  		# Only enable DataDigest to CRC32C
   44  		timing_enter DataDigest_enabled
   45  		node_login_fio_logout "HeaderDigest -v None" "DataDigest -v CRC32C"
     ...
in ./test/iscsi_tgt/digests/digests.sh:101 -> main()

## Possible Solution
None

## Steps to Reproduce
Run test/iscsi_tgt/digests/digests.sh

## Context (Environment including OS version, SPDK version, etc.)
SPDK master branch since 26th or 27th June.

**Comment by shuhei-matsumoto** [comment]
Hi @dong-liuliu 

For some reason, "node.conn[0].iscsi.DataDigest = None" has been included in the returned target configuration. Hence iscsi_header_data_digest_test has been invoked. However we cannot still change node.conn[0].iscsi.DataDigest.

Should we disable iscsi_header_data_digest_test even if  "node.conn[0].iscsi.DataDigest = None"?
Will you give any comment on this?

I saw the patch https://github.com/spdk/spdk/commit/24c7f62fed75b089edb97b56701883efb044a604#diff-8765f82f9fc06307e19a8e5fabcb235b

-Shuhei

**Comment by Seth5141** [comment]
@shuhei-matsumoto I stumbled on this while working on enabling a test pool in chandler for nightly testing. It looks like @dong-liuliu's method works for earlier versions of iscsiadm (at least 6.2.0.874). But the output for the newer machines running fedora 29 doesn't fit this same mold. I think finding a version agnostic way of detecting this feature set would be best. I just don't know enough about this feature to know which command would be best.
Do you know of a more targeted way of querying if a connection supports data digest that would work across multiple distros? If not, we could just add a few if statements to our check.

**Comment by shuhei-matsumoto** [comment]
Hi @Seth5141 thank you so much for your effort. I don't  know this feature well too. I reproduced this failure locally but haven't found the root cause yet. It looks that DataDigest have not been tested recently and we can reproduce this issue locally. So it may be acceptable even if we disable DataDigest test as a temporally workaround. I will gear up my effort anyway.

**Comment by shuhei-matsumoto** [comment]
Hi @Seth5141 if you are considering to remove data digest test, please do not do that. I will investigate more tomorrow.

**Comment by dong-liuliu** [comment]
Hi, @shuhei-matsumoto @Seth5141 
Yes, it's really strange for that version of iscsiadm in Fedora 29.
I've downloaded its source code and compiled its latest version 2.0-877. From my test, iscsi.DataDigest works well again. So it should be a short-lived issue in iscsiadm versions.

**Comment by shuhei-matsumoto** [comment]
Hi @dong-liuliu , Thank you so much for investigating this issue. I couldn't do anything for this issue. If the issue is iscsiadm version, can we update iscsiadm of the OS in the test pool? I'm not sure what option is the best in this case but anyone (including you) will be able to provide better fix because you found the cause.

**Comment by dong-liuliu** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/461191 
It should work for this issue

**Comment by tomzawadzki** [comment]
Patch resolving this issue is now merged.
https://review.gerrithub.io/c/spdk/spdk/+/461191
@shuhei-matsumoto Can this issue be closed ?

**Comment by shuhei-matsumoto** [comment]
Yes,
