### ISSUE TITLE
nvmf target hang out 

### ISSUE THREAD

**Issue by jiaqizho** [spdk/spdk#850]
## Expected Behavior
spdk nvmf_tgt normal exit .

## Current Behavior

![image](https://user-images.githubusercontent.com/8388185/60567623-1fc5e500-9d9d-11e9-85a4-bf9ea8e2ad17.png)

tgt2 hang out when tgt1 exit .

## Possible Solution

WR flushed error , Maybe we didn't clear the WR very well . and it make nvmf tgt hang.

## Steps to Reproduce

tgt1 :  ./app/nvmf_tgt/nvmf_tgt -m 0xff0000 -e 0x10 -c ../normal.config

normal.config : 
```
[Global]
[Bdev]
[Nvmf]
  AcceptorPollRate 10000
[Transport]
  Type RDMA
[Nvme]
  TransportID "trtype:PCIe traddr:0000:81:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:82:00.0" Nvme1
  TransportID "trtype:PCIe traddr:0000:83:00.0" Nvme2
  RetryCount 4
  TimeoutUsec 0
  ActionOnTimeout None
  AdminPollRate 100000
  HotplugEnable Yes

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.91.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace Nvme0n1

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode2
  Listen RDMA 192.168.91.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  MaxNamespaces 20
  Namespace Nvme1n1

[Subsystem3]
  NQN nqn.2016-06.io.spdk:cnode3
  Listen RDMA 192.168.91.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000003
  MaxNamespaces 20
  Namespace Nvme2n1

```

tgt2 :  ./app/nvmf_tgt/nvmf_tgt -c ../normal-malloc.config

```
[global]
[Bdev]
[Nvmf]
AcceptorPollRate 10000

[Transport]
  Type RDMA

[Nvme]
TransportID "trtype:RDMA adrfam:ipv4 traddr:192.168.91.11 trsvcid:4420 hostaddr:192.168.91.12 subnqn:nqn.2016-06.io.spdk:cnode1" Malloc0
TransportID "trtype:RDMA adrfam:ipv4 traddr:192.168.91.11 trsvcid:4420 hostaddr:192.168.91.12 subnqn:nqn.2016-06.io.spdk:cnode2" Malloc1
TransportID "trtype:RDMA adrfam:ipv4 traddr:192.168.91.11 trsvcid:4420 hostaddr:192.168.91.12 subnqn:nqn.2016-06.io.spdk:cnode3" Malloc2



[Malloc]
NumberOfLuns 8
LunSizeInMB 64


[Subsystem1]
NQN nqn.2016-06.io.spdk:cnode1
Listen RDMA 192.168.91.12:4420
AllowAnyHost Yes
Host nqn.2016-06.io.spdk:init
SN SPDK00000000000001
MaxNamespaces 20
Namespace Malloc0

[Subsystem2]
  NQN nqn.2016-06.io.spdk:cnode2
  Listen RDMA 192.168.91.12:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  MaxNamespaces 20
  Namespace Malloc1

[Subsystem3]
  NQN nqn.2016-06.io.spdk:cnode3
  Listen RDMA 192.168.91.12:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000002
  MaxNamespaces 20
  Namespace Malloc2
```

1. start tgt1 
2. start tgt2 
3. ctrl + c tgt1
4. ctrl + c tgt1

## Context (Environment including OS version, SPDK version, etc.)
OS version : fc27
SPDK version : master version(tgt1: 17b77d79ee7a87c91b69befe62e3769ef774b623 , tgt2 : 77c1f90e983daa0b6bf4c80b6129c06a4895c2f7)

**Comment by yidong0635** [comment]
this issue is easy to simulate , and occurred before ,try to fix  this issue, if you have a better solution, please let me know.  https://review.gerrithub.io/c/spdk/spdk/+/460569

**Comment by changpe1** [comment]
The patch has been merged, let me know if the issue still exist or not, thanks.

**Comment by yidong0635** [comment]
@jiaqizho  Could you please help to verify this issue?

**Comment by sashakot** [comment]
Hi,

As far I understand, you run two targets. The second one forwards io to the first one. Is that correct ?
Did you “kill” forwarding target during io ?

Thanks 
Sasha
