### ISSUE TITLE
--huge-dir has no effect 

### ISSUE THREAD

**Issue by gila** [spdk/spdk#853]
While running multiple instances of SPDK on the same machine (for testing purposes) inside of docker and/or k8s, SPDK uses getpid() + some fixed prefix to construct the huge page mappings. Due to the PID namespace, all SPDK instances have PID 1, and things go bad when they all start to map huge pages with the same xxxx.map

There is an option to set the huge-dir which I use to make sure this does not happen, however, `struct option` is not used properly, and we never pass in the value (optarg)

## Expected Behavior
--huge-dir should have an effect.

## Current Behavior
--huge-dir does not have any effect.

## Possible Solution
I have a very small trivial fix for this and will send it out too soon.

## Steps to Reproduce
1.  sudo mount -t hugetlbfs nodev /mnt/spdk1
2. ./app/nvmf-tgt --huge-dir /mnt/spdk1

**Comment by darsto** [comment]
Thanks for the fix! It's merged now.
