### ISSUE TITLE
ftl restore tests randomly fail on CI

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#855]
```
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 0, chk: 28, lbk: 15903)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 0, chk: 27, lbk: 0)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 0, chk: 27, lbk: 0)
md5sum: /tmp/tmp.LmdsPj12v3/testfile: Input/output error
/tmp/tmp.LmdsPj12v3/testfile: FAILED open or read
md5sum: WARNING: 1 listed file could not be read
```

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/37139/archive/nvme_autotest/build.log

**Comment by darsto** [comment]
Happened again:
http://10.102.17.206/results/autotest-per-patch/builds/37547/archive/nvme_autotest/build.log

**Comment by wmalikow** [comment]
I'm trying to reproduce it on my environment but with no success so far.
The issue is related probably with ANM handling that was added recently - we could turn off ANM generation in qemu unitl we find root couse.

**Comment by darsto** [comment]
I've just merged a patch adding more logs on I/O errors:

https://review.gerrithub.io/c/spdk/spdk/+/461588 ("lib/ftl: Add error log after IO failure")

**Comment by darsto** [comment]
I haven't seen this in a while so I'm going to close it.

@ksztyber FYI
