### ISSUE TITLE
Some opal manage items need enter twice.

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#856]
To test opal lib, that I found that a bit trouble,
```
nvme_opal.c: 867:opal_discovery0_end: *NOTICE*: Unknow feature code: 1026
nvme_opal.c: 878:opal_discovery0_end: *NOTICE*: Single User Mode Not Supported
Please input the new password for ownership:

...
...
Opal Init Success
```
here keeps on success. 
or other cases stop on failed points. I think these should  go straight to command notice
after command finished if these don't need inputs.
```
"NVMe Management Options
        [1: list controllers]
        [2: create namespace]
        [3: delete namespace]
        [4: attach namespace to controller]
        [5: detach namespace from controller]
        [6: format namespace or controller]
        [7: firmware update]
        [8: opal]
        [9: quit]
"
```
## Expected Behavior
after command finished, enter to command notice if don't need inputs.

## Current Behavior
stops on an executed command. 
## Steps to Reproduce
1. ./configure 
2. make clean && make -j
3. ./examples/nvme/nvme_manage/nvme_manage
4. 8
5. 2/3/4/9 ...
## Context (Environment including OS version, SPDK version, etc.)
commit 9bba21c9694ebc49406c2bef4ad7ea8cfcb8f933

**Comment by jessehui** [comment]
Hi @yidong0635 thanks for reporting. A patch is submitted and it can fix this.
https://review.gerrithub.io/c/spdk/spdk/+/461179/1
You may need some previous patch to get this patch in. After that, you can also test with invalid input. Thank you!

**Comment by yidong0635** [comment]
waiting for patch serials to be merged.

**Comment by changpe1** [comment]
@yidong0635 Patches have been merged, can we close this issue for now?
