### ISSUE TITLE
nvmf/rdma: double free on failed qpair inititalization

### ISSUE THREAD

**Issue by AlekseyMarchuk** [spdk/spdk#857]
## Expected Behavior
Failed qpair initialization is handled correctly, no resources leaked, no memory corruptions

## Current Behavior
Double free of spdk_nvmf_rdma_qpair structure

The following pseudo call stack represents the qpair creation flow. Memory allocated for `spdk_nvmf_rdma_qpair` structure is cleaned.
```
0. free(rqpair);
1. spdk_nvmf_rdma_qpair_destroy
2. rdma_create_qp //returns some error code, goto error label, perform cleanup and return -1 to the caller
3. spdk_nvmf_rdma_qpair_initialize
4. spdk_nvmf_rdma_poll_group_add
5. spdk_nvmf_transport_poll_group_add
6. spdk_nvmf_poll_group_add
7. nvmf_tgt_poll_group_add
```

The following pseudo call stack represents how non zero return code is handled in nvmf tgt. As we can see, the memory is freed twice.
```
0. free(rqpair);
1. spdk_nvmf_rdma_qpair_destroy
2. spdk_nvmf_rdma_qpair_reject_connection //if (rqpair->qpair.state == SPDK_NVMF_QPAIR_UNINITIALIZED)
3. spdk_nvmf_rdma_close_qpair
4. spdk_nvmf_transport_qpair_fini
5. spdk_nvmf_qpair_disconnect //if (qpair->state == SPDK_NVMF_QPAIR_UNINITIALIZED)
6. nvmf_tgt_poll_group_add //spdk_nvmf_poll_group_add returns non 0 code
``` 
## Possible Solution
Do not call `spdk_nvmf_rdma_qpair_destroy` in the error scenario in `spdk_nvmf_rdma_qpair_initialize`, allow nvmf tgt level to perform clean up

## Steps to Reproduce
The issue was reproduced only once in the following scenario: spdk_tgt with null device  (aka spdk_remote), spdk_tgt which was configured to forward incoming commands to spdk_remote (aka spdk_forward), nvme kernel initiator (nvme connect + fio)
1. Add a sleep for 60 seconds to spdk_remote, e.g. in spdk_nvmf_rdma_poller_poll after each 200k processed WRs
2. connect to spdk_forward using `nvme connect`
3. run fio for ~10 seconds
4. Sleep occured on spdk_remote.
5. nvme_core has a default timeout (30 sec) for IO operations and 60 seconds for admin operations. After 30 seconds nvme core aborts outstanding commands.
6. After 60 seconds nvme core makes an attempt to reset the controller - close all qpairs on spdk_forward, open them again
7. The issues happens on spdk_forward at the moment of qpairs re-initialization

I could mix some things in steps 5,6 since I lost dmesg output. In general, any error occurred on RDMA level at the moment of qpair initialization can lead to that issue.

## Context (Environment including OS version, SPDK version, etc.)
SPDK 19.04, seems to be actual for the latest master as well

**Comment by changpe1** [comment]
@AlekseyMarchuk Since the patch has been merged, can we close this issue for now?

**Comment by changpe1** [comment]
@AlekseyMarchuk My bad, the fix is in your own git repository. :)
