### ISSUE TITLE
Nvmf unit test fail on non-root user

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#859]
Tests **reservation_register_with_ptpl** and **reservation_acquire_release_with_ptpl** in test/unit/lib/nvmf/subsystem.c/subsystem_ut.c fail for users which don't have write access to /var/log directory
## Expected Behavior

Test should pass for both root and regular user
## Current Behavior

Test: reservation_register_with_ptpl .../home/mk/Documents/spdk/lib/nvmf/subsystem.c:1528:spdk_nvmf_ns_json_write_cb: *ERROR*: Can't open file /var/log/Ns1PR.cfg for write
FAILED
## Steps to Reproduce

1. Execute test/unit/lib/nvmf/subsystem.c/subsystem_ut on a user without access to /var/log directory

## Context (Environment including OS version, SPDK version, etc.)

Commit b585dcb1db0ae5cc8d740a0d39500cadd8898c65
4.15.0-29-generic
Ubuntu 18.04.1 LTS (Bionic Beaver)

**Comment by darsto** [comment]
@changpe1 can we use /tmp in that test instead?

**Comment by changpe1** [comment]
@mmkayPL @darsto Thanks, I've changed to use /tmp directory instead.

**Comment by changpe1** [comment]
Closing this issue as patch was merged.
