### ISSUE TITLE
NVMe bdev name is not persistent

### ISSUE THREAD

**Issue by uchida2016** [spdk/spdk#86]
I found NVMe bdev name is not persistent. When I started iscsi_tgt, a NVMe device on 0000:02:00.0 had Nvmp0n1p0. Then I restarted iscsi_tgt, the NVMe device on 0000:02:00.0 changed to Nvme1n1p0. I think bdev name should be persistent. 
NVMe spec defines IEEE Extended Unique Identifier (EUI64)  in Identify Namespace Data Structure. I think we can use EUI64 as a persistent name for NVMe. What do you think?

**Comment by dverkamp-intel** [comment]
I definitely agree that consistent naming across restarts would be useful.

Unfortunately, the EUI64 field in Identify Namespace was added in the NVMe 1.1 spec, and there are existing NVMe 1.0 devices that report all zeroes in that field, so some kind of fallback for those devices would be necessary (perhaps using the serial number and NS ID, although the current bdev name field is not long enough to accommodate that).

**Comment by uchida2016** [comment]
I'm not sure that the serial number is globally unique.
How about using "Vendor ID-Model Number-Serial Number-NS ID" for devices which don't support EUI64 field. In addition, we need a tool to display the consistent name to set up iscsi.conf.

**Comment by dverkamp-intel** [comment]
As of commit d326998ce759a150c88a1ba988acdb077737f018, names are assigned by the user and associated with PCI bus/device/function addresses, so I am closing this issue; let us know if this doesn't satisfy your requirements.
