### ISSUE TITLE
NVMe over Fabrics Target example application

### ISSUE THREAD

**Issue by jgrodman** [spdk/spdk#860]
I am going through the NVMe over Fabrics Target Programming Guide
 (https://spdk.io/doc/nvmf_tgt_pg.html), and looking at the example target application (app/nvmf_tgt). It is working, but I'm trying to understand where the app calls spdk_nvmf_tgt_create(), spdk_nvmf_subsystem_create(), etc. When I look through the code, I do not see the calls. I am asking because I am interested in writing a target myself.

Thank you very much and I apologize if I missed something in the instructions,
Jesse

**Comment by Seth5141** [comment]
Hi @jgrodman,

Our NVMe-oF target application relies on the built in app framework in SPDK/dpdk. There is a good user guide on the app framework at www.spdk.io/doc/app_overview.html. The code in app/nvmf_tgt/nvmf_main.c does little more than start the dpdk and app framework initialization process.
This initialization process starts all of the subsystems registered with our application. The source code for the NVMe-oF subsystem can be found in lib/event/subsystems/nvmf_tgt/nvmf_tgt.c. It's best to start examining that file at the bottom where a function table is defined including an init function. From there, you should be able to follow the initialization process of the target. It's laid out in a nice state machine inside of the function nvmf_tgt_advance_state.
I hope that helps you get started!

**Comment by jgrodman** [comment]
@Seth5141 thank you for your reply. So there are three components?

1. The target app in `app/nvmf_tgt`
2. The subsystem in `lib/event/subsystems/nvmf`
3. The NVMe-oF target library in `lib/nvmf`

If I want to, for example, change the way that reads and writes are performed (such as those done by the NVMe hello_world at `examples/nvme/hello_world/hello_world.c`), is the correct way to do that to not modify the above components, but instead create a new bdev, as described [here](https://spdk.io/doc/bdev_module.html), and then to register that bdev with the `nvmf_tgt`?

Thanks again,
Jesse

**Comment by Seth5141** [comment]
@jgrodman Yeah, those are the  three locations where the NVMe-oF related code lives.
I'm not sure exactly what you mean when you say that you want to change the way that reads and writes are performed?
If you mean performing some kind of transformative operation on the data being read or written (e.g. compression, encryption, etc), or providing an abstraction above the base NVMe drive to present to the user (e.g. logical volumes, raid), then yes. You would want to create a bdev module and instantiate an instance of that bdev on top of your local nvme drive and export it as a namespace in an NVMe-oF subsystem. You can look at the passthru bdev as an example if that is what you are after. 
If you mean something else, then you will have to clarify a bit more before I can give you a good answer.

**Comment by jgrodman** [comment]
@Seth5141 Got it, thank you - that is helpful. I want to service the read and write requests myself,  over an NVMe-oF interface. Therefore, it sounds like I should create a non-virtual bdev and export it as a namespace in an NVMe-oF subsystem, as you said. I will use `bdev_null` as my template for this.

From the docs / code, it seems like the distinction between a virtual bdev and a non-virtual bdev is purely semantic - is that correct? Meaning, it's a matter of how they handle reads and writes, but no different in terms of how they interact with the rest of the system.


I noticed the following difference in how bdevs seem to detect i/o request completion and call `spdk_bdev_io_complete`:

`bdev_null`, for example, adds an entry to the channel queue, which it then polls, and calls `spdk_bdev_io_complete` when it finds an entry in the polling function, rather than just calling `spdk_bdev_io_complete` when it completes, and it seems to complete immediately.

I am comparing this to `bdev_malloc`, for example, which provides `malloc_done` in the callback to `spdk_copy_submit` ([here](https://github.com/spdk/spdk/blob/master/lib/bdev/malloc/bdev_malloc.c#L174)), and `malloc_done` calls `spdk_bdev_io_complete`. `bdev_malloc` does not use polling for this.

So some use a callback, and some use polling. What is the purpose of this difference? (I have read the "Message Passing and Concurrency" section of the docs - very helpful!)

Thank you very much for your help,
Jesse

**Comment by Seth5141** [comment]
So are you trying to essentially define a backing block device in software, i.e  you won't have an actual NVMe device or malloc disk or AIO bdev in the background, you will just take in the commands and do some sort of branching based on the contents thereof and send out a response?

The distinction between base bdevs and virtual bdevs from the perspective of writing the module is mostly semantic.  However there is a real conceptual difference. base bdevs are those which are built directly on top of and represent a physical device of some kind. The bdevs in this category are NVMe, Malloc, NULL, and AIO bdevs. Virtual bdevs cannot exist by themselves and must be built on top of a base bdev or another virtual bdev. They typically mutate the data coming into or out of the bdev or provide some form of logical splitting or combining or base bdevs. Examples include lvol, crypto, compression, raid. 

The bdevs that use a poller are the ones that have an asynchronous interface. So for example, when you submit I/O to an NVMe drive, there is some amount of latency before that I/O is completed to the drive. The drive posts a completion event in the queue to indicate that the I/O is done. The poller in the NVMe bdev polls for these completion entries so that when one does complete, it can invoke the completion callback. A Malloc bdev on the other hand doesn't have a poller because it is backed by memory, and the action of writing a buffer to a memory address is synchronous. By the time the call to write the memory completes, the I/O is complete. Thus, there is no need to poll for completion events and the completion callback can be invoked immediately on the same thread of execution.

Thanks,

Seth

**Comment by jgrodman** [comment]
Hi Seth,

> So are you trying to essentially define a backing block device in software, i.e you won't have an actual NVMe device or malloc disk or AIO bdev in the background, you will just take in the commands and do some sort of branching based on the contents thereof and send out a response?

That's correct.

> The distinction between base bdevs and virtual bdevs from the perspective of writing the module is mostly semantic. However there is a real conceptual difference. base bdevs are those which are built directly on top of and represent a physical device of some kind. The bdevs in this category are NVMe, Malloc, NULL, and AIO bdevs. Virtual bdevs cannot exist by themselves and must be built on top of a base bdev or another virtual bdev. They typically mutate the data coming into or out of the bdev or provide some form of logical splitting or combining or base bdevs. Examples include lvol, crypto, compression, raid.

Thank you for clarifying - this is consistent with my prior understanding. Based on this description, I think we want a non-virtual bdev. Does that sound like the correct architecture for what we're trying to do?

> The bdevs that use a poller are the ones that have an asynchronous interface. So for example, when you submit I/O to an NVMe drive, there is some amount of latency before that I/O is completed to the drive. The drive posts a completion event in the queue to indicate that the I/O is done. The poller in the NVMe bdev polls for these completion entries so that when one does complete, it can invoke the completion callback. A Malloc bdev on the other hand doesn't have a poller because it is backed by memory, and the action of writing a buffer to a memory address is synchronous. By the time the call to write the memory completes, the I/O is complete. Thus, there is no need to poll for completion events and the completion callback can be invoked immediately on the same thread of execution.

Thank you for explaining - two questions:
1. `bdev_null` uses polling, whereas the read operation really finishes immediately - is this just to illustrate the use of polling?
2. In the case of NVMe, we use polling because the device we are querying will respond via a completion entry, right? However, an asynchronous handler that "knows" itself when completion occurs would use a regular callback (i.e. an async disk read or network request)?

Best,
Jesse

**Comment by Seth5141** [comment]
Hey Jesse,

Yeah, a non-virtual bdev is the way to go. Using the Null bdev as a template is probably the best option.

I can't remember exactly why they made the Null bdev poll. It was either meant to be illustrative like you mentioned or part of an effort to make the Null bdev feel more like an actual block device with very low latency.

I'd have to know more about your asynchronous handler to have a better response, but if your thread kicks off an asynchronous operation to another process or some offload engine, then goes and does other work, you will either have to poll for a completion condition on a piece of shared memory or register some sort of interrupt handler to kick off the completion path when triggered.

Everything about the SPDK libraries and event/app framework is geared towards a polling model. We have a reactor loop to which you can register various pollers with arbitrary contexts, a thread message passing scheme built around scheduling events and pollers on different threads, and such.  I think you will find it much easier to integrate a bdev with polling based asynchronous completions than trying to use some kind of interrupt based method.

thanks,
Seth

**Comment by jgrodman** [comment]
Hi Seth,

Great...thank you very much for all your help!

Jesse
