### ISSUE TITLE
Host is able to discover all subsystem log pages, even if it is mapped to only certain subsystems.

### ISSUE THREAD

**Issue by govind-rathod1987** [spdk/spdk#861]
Hi Team,
I want my host to discover only those subsystem log pages through discover command which are mapped to my host. But I could fetch all subsystem information each time when I do the discover.
Please let me know if I need to configure some parameters somewhere to restrict my host to get only the configured / allowed subsystem information during discover.

Regards,
Govind

Below is my sample configuration file for the SPDK target followed  by discover command output.
[
 {
  "listen_addresses": [],
  "subtype": "Discovery",
  "nqn": "nqn.2014-08.org.nvmexpress.discovery",
  "hosts": [
   {
    "nqn": "nqn.2014-08.org.nvmexpress:uuid:ae04632a-f36a-44e8-a434-c41c42a59f1d"
   }
  ],
  "allow_any_host": false
 },
 {
  "listen_addresses": [
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.40.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.30.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.20.1",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.10.1",
    "transport": "RDMA"
   }
  ],
  "subtype": "NVMe",
  "hosts": [
   {
    "nqn": "nqn.2014-08.org.nvmexpress:uuid:ae04632a-f36a-44e8-a434-c41c42a59f1d"
   }
  ],
  "namespaces": [
   {
    "uuid": "d2fd0752-9b55-4244-a003-6fe0b0304474",
    "bdev_name": "Malloc0",
    "nsid": 1,
    "name": "Malloc0"
   }
  ],
  "allow_any_host": false,
  "serial_number": "SPDK00000000000001",
  "nqn": "nqn.2016-06.io.spdk:cnode1"
 },
 {
  "listen_addresses": [
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.40.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.30.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.20.1",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.10.1",
    "transport": "RDMA"
   }
  ],
  "subtype": "NVMe",
  "hosts": [],
  "namespaces": [
   {
    "uuid": "6434bc9f-fd5d-4e36-9628-37a8853688c0",
    "bdev_name": "Malloc1",
    "nsid": 1,
    "name": "Malloc1"
   }
  ],
  "allow_any_host": false,
  "serial_number": "SPDK00000000000001",
  "nqn": "nqn.2016-06.io.spdk:cnode2"
 },
 {
  "listen_addresses": [
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.40.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.30.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.20.1",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.10.1",
    "transport": "RDMA"
   }
  ],
  "subtype": "NVMe",
  "hosts": [],
  "namespaces": [
   {
    "uuid": "6976cebc-9d93-4c46-b161-6542f141c065",
    "bdev_name": "Malloc2",
    "nsid": 1,
    "name": "Malloc2"
   }
  ],
  "allow_any_host": false,
  "serial_number": "SPDK00000000000001",
  "nqn": "nqn.2016-06.io.spdk:cnode3"
 },
 {
  "listen_addresses": [
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.40.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.30.2",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.20.1",
    "transport": "RDMA"
   },
   {
    "trtype": "RDMA",
    "adrfam": "IPv4",
    "trsvcid": "4420",
    "traddr": "100.100.10.1",
    "transport": "RDMA"
   }
  ],
  "subtype": "NVMe",
  "hosts": [],
  "namespaces": [
   {
    "uuid": "7eefbf99-e8ac-4314-ac0f-2b428c70b9bc",
    "bdev_name": "Malloc3",
    "nsid": 1,
    "name": "Malloc3"
   }
  ],
  "allow_any_host": false,
  "serial_number": "SPDK00000000000001",
  "nqn": "nqn.2016-06.io.spdk:cnode4"
 }
]

DISCOVER COMMAND OUTPUT:
------------------------------------
linux-uyry:~/Desktop/packet_sender # nvme discover -t rdma -a 100.100.10.1
Discovery Log Number of Records 16, Generation counter 23
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  100.100.40.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 1======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  100.100.30.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 2======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  2
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  100.100.20.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 3======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  3
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode1
traddr:  100.100.10.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 4======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  4
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode2
traddr:  100.100.40.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 5======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  5
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode2
traddr:  100.100.30.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 6======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  6
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode2
traddr:  100.100.20.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 7======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  7
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode2
traddr:  100.100.10.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 8======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  8
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode3
traddr:  100.100.40.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 9======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  9
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode3
traddr:  100.100.30.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 10======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  10
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode3
traddr:  100.100.20.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 11======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  11
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode3
traddr:  100.100.10.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 12======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  12
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode4
traddr:  100.100.40.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 13======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  13
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode4
traddr:  100.100.30.2
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 14======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  14
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode4
traddr:  100.100.20.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 15======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  15
trsvcid: 4420
subnqn:  nqn.2016-06.io.spdk:cnode4
traddr:  100.100.10.1
rdma_prtype: not specified
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000

**Comment by govind-rathod1987** [comment]
Note: The connect operation is working as expected and the Host is not able to connect to the subsystems other than the mapped one. see below fo rmore details.
linux-uyry:~/Desktop/packet_sender # nvme connect -t rdma -a 100.100.20.1 -n nqn.2016-06.io.spdk:cnode1
linux-uyry:~/Desktop/packet_sender # nvme connect -t rdma -a 100.100.20.1 -n nqn.2016-06.io.spdk:cnode2
Failed to write to /dev/nvme-fabrics: Input/output error

**Comment by yidong0635** [comment]
@govind-rathod1987  please help to list more information:
system/kernel version, operation procedures. 
and 
something like :
modprobe mlx5_ib
modprobe mlx4_ib
modprobe nvme_fabrics
modporbe nvme-rdma
Firwall.
about this input/output error, sometimes due to setting ,sometimes due to kernel errors.

**Comment by govind-rathod1987** [comment]
Hi,
I'm able to perform discovery and connect operation on the allowed subsystem. my requirement is like:
> I have 4 subsystem configured and I have masked or allowed my Host to access 1 subsystem only. 
Rest of the 3 subsystem are not allowed to access from any hosts and allow_all_hosts is set to false.
> After this when i perform discover operation, I am able to see log pages from all the 4 subsystems i.e
 4 subsystems * 4 listening interfaces = 16 logpages.
> The expected log pages are 1 subsystem * 4 listening interfaces = 4 log pages as other 3 subsystems are not allowed for access.

Here are the additional details:
kernel version: 4.19.24-23-default
loaded drivers:
linux-uyry:~ # lsmod | grep mlx*
mlx5_fpga_tools        16384  0
mlx4_en               163840  0
mlx4_ib               241664  0
mlx4_core             401408  2 mlx4_ib,mlx4_en
mlx5_ib               385024  0
ib_uverbs             143360  4 mlx4_ib,rdma_ucm,mlx5_ib,ib_ucm
ib_core               335872  11 rdma_cm,ib_ipoib,mlx4_ib,nvme_rdma,iw_cm,ib_umad,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm,ib_ucm
mlx5_core            1138688  2 mlx5_fpga_tools,mlx5_ib
mlxfw                  24576  1 mlx5_core
devlink                77824  4 mlx4_core,mlx4_ib,mlx4_en,mlx5_core
mlx_compat             16384  18 rdma_cm,ib_ipoib,mlx4_core,mlx4_ib,nvme_rdma,iw_cm,nvme_core,mlx5_fpga_tools,nvme_fabrics,ib_umad,mlx4_en,ib_core,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm,mlx5_core,ib_ucm
linux-uyry:~ # lsmod | grep nvme
nvme_rdma              32768  0
nvme_fabrics           24576  1 nvme_rdma
nvme_core             102400  2 nvme_rdma,nvme_fabrics
rdma_cm                69632  2 nvme_rdma,rdma_ucm
ib_core               335872  11 rdma_cm,ib_ipoib,mlx4_ib,nvme_rdma,iw_cm,ib_umad,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm,ib_ucm
mlx_compat             16384  18 rdma_cm,ib_ipoib,mlx4_core,mlx4_ib,nvme_rdma,iw_cm,nvme_core,mlx5_fpga_tools,nvme_fabrics,ib_umad,mlx4_en,ib_core,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm,mlx5_core,ib_ucm
linux-uyry:~ #

 Firewall status:
linux-uyry:~ # systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
linux-uyry:~ #

**Comment by darsto** [comment]
This is SPDK's fault. There was already a github issue about it: #576

Let's continue the discussion in there.
