### ISSUE TITLE
bdev_iscsi crashes when it fails to connect to a target with an invalid nqn.

### ISSUE THREAD

**Issue by gila** [spdk/spdk#864]
When making a simple typo in the iscsi URL which gets parsed by libiscsi, the system crashes in `iscsi_bdev_conn_poll` The last error messages shown in the console is:

```
bdev_iscsi.c: 702:iscsi_connect_cb: *ERROR*: iSCSI error: Failed to log in to target. Status: Service unavailable(769)
```

The reason for the crash is rather simple. We try to poll the iscsi context and blindly assume it is connected. We should check the iscsi_context parameter it is connected before calling iscsi_service() on it. 

This is a trivial fix, however, perhaps we need to put some thought into how long do we want to have the connection be polled in the case of transient network errors where we want to reconnect? Or somewhat broader and perhaps a  little offtopic but it seems that SPDK, in general, does not really have a good way of handling initiator disconnect/reconnects etc. #668 is similar in nature except that it uses nvmf. This bug is closed as it is to be considered as captured in with #407. But there seems to be "work" going on to catch/tackle that, if so, will this be captured in that approach as well?

## Expected Behavior
There should be a retry policy to try and connect N times after which the bdev should be faulted. Once considered faulted, the connection attempt should be removed from the poll poller. 

## Current Behavior
System crashes

## Possible Solution
likely by lack of understanding, but there does not seem to be a way to mark a bdev as faulted/degraded/offline when it tries to connect to remote targets. This is true for the iscsi_bdev as well as the nvme_bdev. 

Having methods/entry points that implement retries, reconnects, etc looks like something that requires a preferred/suggested approach rather than adhoc fixes in the bdevs themselves.

Maybe its an idea, to have additional functions in the bdev layers that handle the common parts of resetting/destroying the io channels if any, reconnecting etc?

## Steps to Reproduce
use the iscsi_bdev -- and connect to a remote iscsi target that as a typo in the iqn.

I can send a patch to fix this particular issue if people like, but as mentioned perhaps there is a "bigger" picture that is being worked on I'm not aware of.

**Comment by changpe1** [comment]
@gila Please go ahead to submit your fix first, we do need it. :).

**Comment by gila** [comment]
Ok, I have a fix ready - I'll submit it when I have some free time.

**Comment by gila** [comment]
patch posted here: https://review.gerrithub.io/c/spdk/spdk/+/462614

**Comment by darsto** [comment]
Merged, thanks!
