### ISSUE TITLE
Docs update - Message Passing and Concurrency

### ISSUE THREAD

**Issue by jgrodman** [spdk/spdk#866]
First off - the docs on spdk are great, so thanks to everyone for doing such a solid job.

The docs in "Message Passing and Concurrency" ([here](https://spdk.io/doc/concurrency.html)) have an out-of-date section about thread creation. They talk about using spdk_allocate_thread() with three function pointers, whereas the API has been changed to spdk_thread_create() and has a different argument list.

Thanks,
Jesse

**Comment by jessehui** [comment]
Hi Jesse, thanks for pointing out. Could you submit a patch to update the `doc/concurrency.md`?  And the spdk.io doc will be updated automatically. Thanks.

**Comment by jgrodman** [comment]
Sure! I pushed a change to gerrit, following the instructions in the spdk development guidelines: https://review.gerrithub.io/c/spdk/spdk/+/462878

**Comment by changpe1** [comment]
Patch has been merged, I'm going to close this issue for now, thanks for submitting the patch.
