### ISSUE TITLE
spdk_bdev_writev/spdk_bdev_readv take over 20ms somtimes

### ISSUE THREAD

**Issue by benqwu** [spdk/spdk#867]
I use spdk bdevperf to test SSD performance and find that sometimess spdk_bdev_writev/spdk_bdev_readv take over 20ms when testing large IO.

I do not understand why it take so long time, because I think aio io_submit is asynchronous and O_DIRECT means there is no data copy in syscall.
My APP cares about latency, so please help.

## Steps to Reproduce

1.

./bdevperf -m 0x1 -c bdev.conf.in -q 64 -o 4194304 -w randread -t 100
./bdevperf -m 0x1 -c bdev.conf.in -q 64 -o 4194304 -w randwrite -t 100

2.
strace -o bdevperf.txt -T -tt -e trace=io_submit -p pid

3.
1 21:49:08.592305 io_submit(140186865831936, 1, [{data=0x7f77fa02b920, pwritev, fildes=9, iovec=[{"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 419    4304}], offset=76881592320, resfd=10}]) = 1 0.025107
  2 21:49:08.618668 io_submit(140186865831936, 1, [{data=0x7f77fa06f0a0, pwritev, fildes=9, iovec=[{"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 419    4304}], offset=361096019968, resfd=10}]) = 1 0.025536
  3 21:49:08.645385 io_submit(140186865831936, 1, [{data=0x7f77fa02d2a0, pwritev, fildes=9, iovec=[{"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 419    4304}], offset=82367741952, resfd=10}]) = 1 0.027838
......

4.

top - 22:50:06 up 45 days,  7:46,  8 users,  load average: 0.29, 0.11, 0.11
Threads: 302 total,   1 running, 301 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.3 us,  9.2 sy,  0.0 ni,  0.0 id, 90.4 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu8  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu9  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu10 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu11 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65706780 total,   561140 free, 39734620 used, 25411020 buff/cache
KiB Swap: 12505084 total, 10046204 free,  2458880 used. 17204144 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                   
26002 root      20   0  128.2g 134944 133772 D  9.6  0.2   0:02.54 reactor_0 

I use ftrace and find that reactor_0 is scheduled, why?

201481           <idle>-0     [000] d... 3916569.150137: sched_switch: prev_comm=swapper/0 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=reactor_0 next_pid=26002 next_p       rio=120
201482        reactor_0-26002 [000] .... 3916569.150441: sys_io_submit -> 0x1
201483        reactor_0-26002 [000] .... 3916569.150449: sys_io_submit(ctx_id: 7fb99d332000, nr: 1, iocbpp: 7fff06040468)
201484        reactor_0-26002 [000] .... 3916569.150836: sys_io_submit -> 0x1
201485        reactor_0-26002 [000] .... 3916569.150839: sys_io_submit(ctx_id: 7fb99d332000, nr: 1, iocbpp: 7fff06040468)
201486        reactor_0-26002 [000] d.h. 3916569.150872: sched_stat_runtime: comm=reactor_0 pid=26002 runtime=776464 [ns] vruntime=2056609984670371 [ns]
201487        reactor_0-26002 [000] .... 3916569.151225: sys_io_submit -> 0x1
**201488        reactor_0-26002 [000] .... 3916569.151227: sys_io_submit(ctx_id: 7fb99d332000, nr: 1, iocbpp: 7fff06040468)
201489        reactor_0-26002 [000] d... 3916569.151603: sched_stat_runtime: comm=reactor_0 pid=26002 runtime=732921 [ns] vruntime=2056609985403292 [ns]**
**201490        reactor_0-26002 [000] d... 3916569.151606: sched_switch: prev_comm=reactor_0 prev_pid=26002 prev_prio=120 prev_state=D ==> next_comm=swapper/0 next_pid=0 next_p       rio=120
201491           <idle>-0     [007] d.s. 3916569.167284: sched_wake_idle_without_ipi: cpu=0
201492           <idle>-0     [007] d.s. 3916569.167284: sched_wakeup: comm=reactor_0 pid=26002 prio=120 success=1 target_cpu=000**
201493           <idle>-0     [000] d... 3916569.167327: sched_switch: prev_comm=swapper/0 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=reactor_0 next_pid=26002 next_p       rio=120
201494        reactor_0-26002 [000] .... 3916569.167368: sys_io_submit -> 0x1
201495        reactor_0-26002 [000] .... 3916569.167376: sys_io_submit(ctx_id: 7fb99d332000, nr: 1, iocbpp: 7fff06040468)
201496        reactor_0-26002 [000] .... 3916569.167818: sys_io_submit -> 0x1

## Context (Environment including OS version, SPDK version, etc.)

 SPDK 18.10

cat /sys/block/sdu/queue/nr_requests 
128

cat /sys/block/sdu/device/queue_depth 
254

SSD's information:
=== START OF INFORMATION SECTION ===
Vendor:               SEAGATE
Product:              ST400FM0233
Revision:             A005
Compliance:           SPC-4
User Capacity:        400,088,457,216 bytes [400 GB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
LU is resource provisioned, LBPRZ=1
Rotation Rate:        Solid State Device
Form Factor:          2.5 inches
Logical Unit id:      0x5000c500301b65af
Serial number:        ZAJ1519Z0000822150Z3
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Sun Jul 21 22:11:36 2019 CST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

**Comment by changpe1** [comment]
@benqwu The IO size is 4MiB, and the default IO buffer size is 64KiB, so one 4MiB IO will be splitted into 64 small requests, so you can break down the time consuming in  spdk_bdev_writev to see which function consumed the time.

**Comment by benqwu** [comment]
The IO size is 4MiB, and the default IO buffer size is 64KiB
>>Where can I see the default IO buffer size? Thanks~

**Comment by jimharris** [comment]
Hi @benqwu,

I realize this question was posted a few months ago - I have a few questions below if this is something you're still wanting to investigate.

Can you clarify the 20ms latency?  Do you mean that strace sometimes reports that a single io_submit takes 20ms or more?

I would like to know if you see this for every system call, or for only a very small percentage.  Specific data around frequency would be helpful.

reactor_0 is scheduled because this is the SPDK polled mode thread.  It should generally always be scheduled, except in cases where there is some kind of interrupt targeted for that thread's core.  It looks like reactor_0 is getting scheduled out in favor of pid0 for 15ms or so.  How often do you see this?

Any other information about what is running on your system would be helpful too.

Thanks,

-Jim

**Comment by jimharris** [comment]
Bug scrub: closing this issue pending feedback from submitter.  Please reopen if you are able to provide additional details.
