### ISSUE TITLE
I/O stops on link toggle test

### ISSUE THREAD

**Issue by krishna-e** [spdk/spdk#870]
I/O stops on link toggle test

## Expected Behavior
connections should reconnect successfully despite of frequent link toggle.

## Current Behavior
after running link toggle script on a target machine for about 45min, the initiator dmesg show below log and then reconnect fails indefinetly:
dmesg at initiator:
[ 5441.276643] nvme nvme0: I/O 1 QID 0 timeout
[ 5441.282095] nvme nvme0: starting error recovery
[ 5441.291317] block nvme0n1: no path available - requeuing I/O
[ 5441.291579] block nvme0n1: no path available - requeuing I/O
[ 5441.422197] nvme nvme0: failed nvme_keep_alive_end_io error=10
[ 5441.425737] nvme nvme0: Reconnecting in 10 seconds...
[ 5454.524817] nvme nvme0: rdma connection establishment failed (-110)       <==this is expected as target is running link toggle script.
[ 5454.527749] nvme nvme0: Failed reconnect attempt 1
[ 5454.528088] nvme nvme0: Reconnecting in 10 seconds...
[ 5464.841663] nvme nvme0: creating 6 I/O queues.
[ 5464.932196] nvme nvme0: Successfully reconnected (2 attempts)
[ 5491.454374] nvme nvme0: I/O 0 QID 0 timeout
[ 5491.454637] nvme nvme0: starting error recovery
[ 5491.469572] block nvme0n1: no path available - requeuing I/O
[ 5491.469831] block nvme0n1: no path available - requeuing I/O
[ 5491.470348] block nvme0n1: no path available - requeuing I/O
[ 5491.470865] block nvme0n1: no path available - requeuing I/O
[ 5491.471395] block nvme0n1: no path available - requeuing I/O
[ 5491.595769] nvme nvme0: failed nvme_keep_alive_end_io error=10
[ 5491.598720] nvme nvme0: Reconnecting in 10 seconds...
[ 5504.701476] nvme nvme0: rdma connection establishment failed (-110)
[ 5504.704212] nvme nvme0: Failed reconnect attempt 1
[ 5504.704477] nvme nvme0: Reconnecting in 10 seconds...
[ 5515.014278] nvme nvme0: creating 6 I/O queues.
[ 5575.934419] nvme nvme0: I/O 0 QID 2 timeout
[ 5575.941135] nvme nvme0: Connect command failed, error wo/DNR bit: 7
[ 5575.941399] nvme nvme0: failed to connect queue: 2 ret=7
[ 5575.999872] nvme nvme0: Failed reconnect attempt 2
[ 5576.000139] nvme nvme0: Reconnecting in 10 seconds...
                 <and this continues idefinitely, even the link toggle script is stopped and kept in link up state at target>

## Possible Solution
I don't have any possible solution yet, but i feel the issue is at spdk target side, as initiator could not get reply for the sent requests causing "I/O TimeOuts".

## Steps to Reproduce
Initiator side(kernelspace nvme initator):
	
-> Load iw_cxgb4/mlx4_ib and nvme-rdma drivers and assign IP to those interfaces.
-> nvme connect-all -t rdma -a 104.1.1.6 -s 4420
-> run Iozone on those connected nvme nodes. Any kind of traffic should be fine.
	command I used:  iozone -a -I -+d -g $size

Target side(userspace/spdk nvme target:
-> install SPDK kit in the target machine.

-> Load iw_cxgb4/mlx4_ib drivers and assign IP to those interfaces.

-> modprobe null_blk

-> sudo HUGEMEM=8194 /root/spdk/scripts/setup.sh

-> echo 8 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages

-> mount -a

->Then create a NVMeF target config file as shown below.

->Then start the target with below command.
 
[nvme.conf.txt](https://github.com/spdk/spdk/files/3419131/nvme.conf.txt)
 /root/spdk/app/nvmf_tgt/nvmf_tgt -m 0x003F -c /root/nvmf.conf

-> Finally, run the link toggle script:
while [ 1 ]
do
ifconfig enp5s0 down

sleep 20

ifconfig enp5s0 up

sleep 30

done

## Context:

spdk: commit de1d0f(github.com/spdk/spdk.git)
kernel: Linux Kernel 5.3.0-rc1
OS: RHEL 7.5
rdma-core:  commit ae7ab7(github.com/linux-rdma/rdma-core)

#logs:

spdk log after failure:
subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode4 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode3 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode4 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode1 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode3 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode3 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode3 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode3 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode3 due to keep alive timeout.
ctrlr.c: 143:spdk_nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host from subsystem nqn.2016-06.io.spdk:cnode3 due to keep alive timeout.

dmesg at target:
[ 5840.960274] mlx4_en: enp5s0: Close port called
[ 5841.128233] mlx4_en: enp5s0: Link Down
[ 5861.168023] mlx4_en: enp5s0: Steering Mode 1
[ 5870.454384] mlx4_en: enp5s0: Link Up
[ 5870.454773] IPv6: ADDRCONF(NETDEV_CHANGE): enp5s0: link becomes ready
[ 5891.372254] mlx4_en: enp5s0: Close port called
[ 5891.563213] mlx4_en: enp5s0: Link Down
[ 5911.606004] mlx4_en: enp5s0: Steering Mode 1
[ 5920.892365] mlx4_en: enp5s0: Link Up
[ 5920.892748] IPv6: ADDRCONF(NETDEV_CHANGE): enp5s0: link becomes ready

**Comment by jimharris** [comment]
Hi,

Thanks for the report.  Can you try this same test with the Linux kernel NVMe-oF target?  That would help confirm whether this is an initiator or target side problem.

-Jim

**Comment by krishna-e** [comment]
> 
> 
> Hi,
> 
> Thanks for the report. Can you try this same test with the Linux kernel NVMe-oF target? That would help confirm whether this is an initiator or target side problem.
> 
> -Jim

The attached wireshark capture indicates that the issue is at target side(spdk). That is, the initiator sends a request(in-capsule command) and awaits for the response from target. I may be wrong.

Anyways, I will give a try with NVMe-oF target.

Thanks,
Krishna.

[wireshark_capture.zip](https://github.com/spdk/spdk/files/3419298/wireshark_capture.zip)

**Comment by krishna-e** [comment]
> 
> 
> Hi,
> 
> Thanks for the report. Can you try this same test with the Linux kernel NVMe-oF target? That would help confirm whether this is an initiator or target side problem.
> 
> -Jim

I ran the same test with Linux kernel NVMe-oF as target for more than 3 hours the issue did not occur.

Looks like the issue is at SPDK target side.

**Comment by jimharris** [comment]
Thanks @krishna-e.  We'll get this assigned to someone at the next SPDK bug scrub.

**Comment by darsto** [comment]
Bugscrub: @peluse  to reproduce it for now.

**Comment by peluse** [comment]
So I tried to repro this, a few differences:
target: spdk master, kernel 5.0.16-200.fc29.x86_64
initiator: kernel 4.18.16-300.fc29.x86_64 
and I'm running fio against the connected target.

 * the only thing I see on the target are the following which directly correspond to me taking the link down/up:
rdma.c:2927:spdk_nvmf_process_ib_event: *NOTICE*: Async event: port error
rdma.c:2927:spdk_nvmf_process_ib_event: *NOTICE*: Async event: port active

* on the init, dmesg doesn't show any issues:
[698555.723921] nvme nvme0: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 192.168.100.8:4420
[698555.724478] nvme nvme0: Removing ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery"
[698572.140915] nvme nvme0: creating 60 I/O queues.
[698573.367275] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 192.168.100.8:4420

* it doesn't appear that fio is doing IO following the 'down' event though, no updates on status but top shows that its still running.

Will review w/Ben this afternoon....

**Comment by peluse** [comment]
oh wait, fio stated generating updates again.  I have verify on as well and there are no issues reported.  Will let it run for a while.  Not that I only manually took the link down/up 2 times with about 15 sec in between.

**Comment by peluse** [comment]
If this is your SPDK:
 commit de1d0f8fe912584990edbe03eb30e8d32664b4b8 
 Date:   Fri Feb 22 10:48:05 2019 +0100
It seems like it would be work trying with master.... please let me know if you can do that and how it goes.

**Comment by krishna-e** [comment]
> 
> 
> If this is your SPDK:
> commit [de1d0f8](https://github.com/spdk/spdk/commit/de1d0f8fe912584990edbe03eb30e8d32664b4b8)
> Date: Fri Feb 22 10:48:05 2019 +0100
> It seems like it would be work trying with master.... please let me know if you can do that and how it goes.


I just recreated the issue with the latest SPDK, commit a2dcdde(Date:   Wed Jul 31 21:59:38 2019 +0800).

To quickly recreate the issue:

-set "InCapsuleDataSize 8192" in nvmf.conf at spdk target.
-User MTU 9000
-run traffic on at least 4 luns.
-I used IOZone to run traffic on multiple luns(running IO on formatted disks).
-use ifconfig down(for 10sec) and ifconfig up(for 30sec) on target in an automated script and leave it for about 45 min. You should see dmesg logs like below at initiator for each iteration:
		[  +6.013818] nvme nvme3: I/O 0 QID 3 timeout
		[  +0.000001] nvme nvme2: I/O 0 QID 0 timeout
		[  +0.000527] nvme nvme1: I/O 0 QID 6 timeout

Do you want me to take any SPDK logs that might help in debugging this issue?

-Krishna.

**Comment by peluse** [comment]
OK, I'll try with those more specific settings, thanks

**Comment by peluse** [comment]
was out sick all of last week, so you are saying you need all 3 of your first bullets to be true for this to fail? For example, if you use just 1 lun this doesn't happen? Or if you use 4 but don't set the conf option it doesn't happen? Sure, if you have logs that would help, just trying to get the simplest repro conditions pobbile....

**Comment by krishna-e** [comment]
> 
> 
> was out sick all of last week, so you are saying you need all 3 of your first bullets to be true for this to fail? For example, if you use just 1 lun this doesn't happen? Or if you use 4 but don't set the conf option it doesn't happen? Sure, if you have logs that would help, just trying to get the simplest repro conditions pobbile....

The issue may occur with 1 lun, but it will take a lot of time. But with 4 luns, I see the issue happening quickly, around 25min.

How to enable debug logs in SPDK.
Is it possible to enable only rdma part debugging logs? because enabling all debug logs can slow down the processing and I may not see this issue.

**Comment by peluse** [comment]
make sure you when "make" you include --enable-debug and then when you start your application you use the --logfile option.  Generally its described here, https://spdk.io/doc/app_overview.html#cmd_arg_debug_log_flags so to get all of them "sudo ./app/spdk_tgt/spdk_tgt --logflag all".  To get a list of flags supported for the app you are using, use help, here's the help putout for --logfile for spdk_tgt on master:

all, aio, app_config, bdev, bdev_ftl, bdev_malloc, bdev_null, bdev_nvme, bdev_pmem, bdev_raid, blob, blob_rw, blobfs, blobfs_rw, copy_ioat, ftl_core, ftl_init, gpt_parse, ioat, iscsi, json_util, log, lvol, lvolrpc, nbd, net, notify_rpc, nvme, nvmf, nvmf_tcp, opal, raidrpc, reactor, reduce, rpc, rpc_client, scsi, thread, trace, vbdev_compress, vbdev_delay, vbdev_gpt, vbdev_lvol, vbdev_passthru, vbdev_split, vhost, vhost_blk, vhost_blk_data, vhost_ring, vhost_rpc, vhost_scsi, vhost_scsi_data, vhost_scsi_queue, virtio, virtio_blk, virtio_dev, virtio_pci, virtio_user, vmd

**Comment by krishna-e** [comment]
> 
> 
> make sure you when "make" you include --enable-debug and then when you start your application you use the --logfile option. Generally its described here, https://spdk.io/doc/app_overview.html#cmd_arg_debug_log_flags so to get all of them "sudo ./app/spdk_tgt/spdk_tgt --logflag all". To get a list of flags supported for the app you are using, use help, here's the help putout for --logfile for spdk_tgt on master:
> 
> all, aio, app_config, bdev, bdev_ftl, bdev_malloc, bdev_null, bdev_nvme, bdev_pmem, bdev_raid, blob, blob_rw, blobfs, blobfs_rw, copy_ioat, ftl_core, ftl_init, gpt_parse, ioat, iscsi, json_util, log, lvol, lvolrpc, nbd, net, notify_rpc, nvme, nvmf, nvmf_tcp, opal, raidrpc, reactor, reduce, rpc, rpc_client, scsi, thread, trace, vbdev_compress, vbdev_delay, vbdev_gpt, vbdev_lvol, vbdev_passthru, vbdev_split, vhost, vhost_blk, vhost_blk_data, vhost_ring, vhost_rpc, vhost_scsi, vhost_scsi_data, vhost_scsi_queue, virtio, virtio_blk, virtio_dev, virtio_pci, virtio_user, vmd

Sure Paul, will recreate it with debug logs enabled.
I will give you the logs in next week, currently, my machines are occupied for something else.

**Comment by peluse** [comment]
have we had enough changes in this are leading up to the 19.10 release that it makes sense to retest this again?

**Comment by tomzawadzki** [comment]
[Bug scrub] @Seth5141 will try to reproduce this today.

**Comment by Seth5141** [comment]
Hi @krishna-e Thanks again for posting this issue. I am attempting to replicate it now.

I have installed iozone on my initiator system and am performing I/O between two direct connect 

Some configurations are the same between my target and initiator:
kernel 5.2.17-050217-generic (ubuntu)
MLX_5 NICs.
I use the libibverbs and librdmacm installed from the package manager.

Here is my target setup currently:
SPDK master (currently) using the configuration file you provided. nvmf_tgt -m 0x003F -c nvmf_tgt.conf

Initiator:
connect to each of the four nvme subsystems with the following command:
sudo nvme connect -t rdma -n "nqn.2016-06.io.spdk:cnodeX" -a 192.168.100.8 -s 4420 -k 1
. . .
create a partition on each device
create an ext4 filesystem on each device
mount each device in /mnt/deviceX
cd to one of those directories and run iozone -a -I -+d

The problem for me, and it seems similar to what Paul noticed previously, is this: The initiator side does not seem to notice when the link goes down in the target. I don't get a disconnect event at all in the initiator. Now, when I kill the target app, I get the proper disconnect events and the initiator tries to reconnect, but this is different than your use case.

Can you share some more information about the NICs you are using and the NVMe commands you use to connect to the target namespaces? I want to try to see if there are any discrepancies there before I configure a custom kernel and rdma-core. My hope is that if this is an SPDK issue, it can be replicated wih a production kernel (not an RC).

Thanks,

Seth

**Comment by peluse** [comment]
Thanks @Seth5141 for helping out with this one!!

**Comment by krishna-e** [comment]
> Hi @krishna-e Thanks again for posting this issue. I am attempting to replicate it now.
> 
> I have installed iozone on my initiator system and am performing I/O between two direct connect
> 
> Some configurations are the same between my target and initiator:
> kernel 5.2.17-050217-generic (ubuntu)
> MLX_5 NICs.
> I use the libibverbs and librdmacm installed from the package manager.
> 
> Here is my target setup currently:
> SPDK master (currently) using the configuration file you provided. nvmf_tgt -m 0x003F -c nvmf_tgt.conf
> 
> Initiator:
> connect to each of the four nvme subsystems with the following command:
> sudo nvme connect -t rdma -n "nqn.2016-06.io.spdk:cnodeX" -a 192.168.100.8 -s 4420 -k 1
> . . .
> create a partition on each device
> create an ext4 filesystem on each device
> mount each device in /mnt/deviceX
> cd to one of those directories and run iozone -a -I -+d
> 
> The problem for me, and it seems similar to what Paul noticed previously, is this: The initiator side does not seem to notice when the link goes down in the target. I don't get a disconnect event at all in the initiator. Now, when I kill the target app, I get the proper disconnect events and the initiator tries to reconnect, but this is different than your use case.

were you able to see messages like "I/O 1 QID 0 timeout" at the initiator machine?
if not, then you may need to keep the link-down for 40 seconds or above until you see IO timeouts.

> 
> Can you share some more information about the NICs you are using and the NVMe commands you use to connect to the target namespaces? I want to try to see if there are any discrepancies there before I configure a custom kernel and rdma-core. My hope is that if this is an SPDK issue, it can be replicated wih a production kernel (not an RC).

I tried with Mellanox and Chelsio RNICs.  And the command I used to connect targets is : "nvme connect-all -t rdma -a 104.1.1.6 -s 4420".

I will also try with the latest SPDK v19.07.1, to see if the issue still exists or not.
> 
> Thanks,
> 
> Seth

**Comment by krishna-e** [comment]
Tried with latest spdk(commit eafc447e), the test ran for more than 8 hours, usually the issue recreates within 30min.
Thanks @Seth5141 and @peluse for working on this issue.

Will reopen if I hit this issue again. 


Thanks,
Krishna.
