### ISSUE TITLE
nvmf: question about spdk_nvmf_subsystem_set_state's concurrent model

### ISSUE THREAD

**Issue by lorneli** [spdk/spdk#871]
Hi,

Func spdk_nvmf_subsystem_set_state sets subsystem to its next state. It uses atomic CAS __sync_val_compare_and_swap to do this. But is there a case that multiple threads will change subsystem's state concurrently, so that an atomic CAS  is used here? 

```
actual_old_state = __sync_val_compare_and_swap(&subsystem->state, expected_old_state, state);
if (actual_old_state != expected_old_state) {                               
        // ....
} 
```

From my understanding, adding/removing a ns from subsystem will not cause concurrent modification to subsystem's state. When receiving a spdk_rpc_nvmf_subsystem_add_ns rpc, state-change function spdk_nvmf_subsystem_pause and spdk_nvmf_subsystem_resume are both called in rpc's thread.

Thanks in advance.

**Comment by benlwalker** [comment]
The atomic is only used to guard against two threads trying to transition the state from ACTIVE to something else. Once the subsystem is no longer ACTIVE, other threads will return BUSY.

It likely doesn't even need the atomic if we just went through and made sure all subsystem management operations happened from a single thread (i.e. the RPC thread).
