### ISSUE TITLE
Failure in FTL restore tests

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#874]
## Current Behavior
The FTL restore test (spdk/test/ftl/restore.sh) has failed twice in a row on one of the nightly test jobs for SPDK.

The failure has looked slighty different each time.

Failure 1:
~~~
cryptodev_aesni_mb_create() line 1304: IPSec Multi-buffer library version used: 0.52.0

 07:52:29	# xtrace_enable
 07:52:29	# ((  i == 0  ))
 07:52:29	# return 0
 07:52:29	# /var/jenkins/workspace/NVMe_tests/nvme_autotest_nightly/spdk/scripts/rpc.py load_config
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 0, chk: 26, lbk: 16752)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 0, chk: 26, lbk: 16752)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 1, chk: 29, lbk: 0)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 1, chk: 29, lbk: 0)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 1, chk: 29, lbk: 0)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 1, chk: 29, lbk: 0)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 0, chk: 28, lbk: 0)
ftl_anm.c: 191:ftl_anm_in_poller_range: *ERROR*: ANM log contains invalid @ppa: (grp: 0, pu: 0, chk: 28, lbk: 0)
ftl_restore.c:1209:ftl_restore_tail_md_cb: *ERROR*: Unknown error -4 while restoring tail md in band 1.
ftl_init.c: 962:ftl_restore_device_cb: *ERROR*: Failed to restore the device from the SSD
Bands validity:
 Band   1:        0 / 98080 	num_chunks: 4 	wr_cnt: 0	merit:     0.000	state: closed
~~~

followed by a core dump.

failure 2:
~~~
mke2fs 1.44.2 (14-May-2018)
Creating filesystem with 2044723 4k blocks and 512064 inodes
Filesystem UUID: 342f9832-52c0-4d92-8a22-6c2bbe52d865
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables:  0/63     done                            
Writing inode tables:  0/63     done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/63     done

 07:07:32	# mount /dev/nbd0 /tmp/tmp.YO1t0ZNkR0
 07:07:32	# dd if=/dev/urandom of=/tmp/tmp.YO1t0ZNkR0/testfile bs=4K count=256K
spdk_tgt: ftl_core.h:467: ftl_l2p_get: Assertion `dev->num_lbas > lba' failed.
dd: error writing '/tmp/tmp.YO1t0ZNkR0/testfile': Read-only file system
165673+0 records in
165672+0 records out
678592512 bytes (679 MB, 647 MiB) copied, 33.2672 s, 20.4 MB/s
/var/jenkins/workspace/NVMe_tests/nvme_autotest_nightly/spdk/test/ftl/restore.sh: line 49: 1778109 Aborted                 (core dumped) $rootdir/app/spdk_tgt/spdk_tgt
  07:08:05	# trap - ERR
  07:08:05	# print_backtrace
  07:08:05	# [[ ehxBE =~ e ]]
  07:08:05	# xtrace_disable
  07:08:05	# PREV_BASH_OPTS=ehxBE
  07:08:05	# set +x
~~~
followed by a core dump

## Possible Solution
There were three ftl related changes merged between the last successful test run and the first failed run. They are as follows:
lib/ftl: Remove buffer alignment requirements
lib/ftl: Remove separate dma_buf allocation in band
test/ftl: Changed bdev_svc usage to spdk_tgt
I believe one of those changes may have introduced the bug.

## Steps to Reproduce
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly-chandler_152.html
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly-chandler_153.html

## Context (Environment including OS version, SPDK version, etc.)
The test was running inside of a jenkins test vm running fedora 28. More detailed specs are available in the logs above.

**Comment by ksztyber** [comment]
Looks very similar to #855. I suspect the root cause might be the same for both, while some of the recent patches made the reproduction more frequent.

**Comment by mmkayPL** [comment]
The patch
lib/ftl: Remove buffer alignment requirements
required a change (bugfix) to qemu, specifically at least patch:
https://review.gerrithub.io/c/spdk/qemu/+/459264

I've reverted my local QEMU instance to a previous version and received the same errors. It seems like the Chandler machines' QEMU wasn't updated.

**Comment by karlatec** [comment]
@Seth5141 
I've sent you some Qemu related info, check you mail.

**Comment by ksztyber** [comment]
Yeah, seems I was wrong and it's just the QEMU that needs to be updated.

**Comment by Seth5141** [comment]
@ksztyber @karlatec Great, thanks!
I'll update the qemu version in the Chandler machines. What is the best way for me to stay up on the latest qemu changes? Do you have a distribution list when you update the branch, or should I just keep an eye on the spdk-3.0.0 branch of our fork?

**Comment by karlatec** [comment]
@Seth5141 
I guess just keep an eye on our qemu branch. And I promise to keep you in the loop next time we update stuff! :)
