### ISSUE TITLE
Compiling error using latest SPDK codes with reduce parameter

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#877]
## Expected Behavior
compilation success.

## Current Behavior
compilation failed. error messages are as below:

  ```
CC lib/bdev/compress/vbdev_compress.o
vbdev_compress.c:160:1: error: initializer element is not constant
 };
 ^
vbdev_compress.c:171:1: error: initializer element is not constant
 };


```
## Steps to Reproduce
1. clone latest spdk and submodule codes.
2. configure spdk with following command:
`./configure --with-isal --without-ocf --with-rdma --enable-debug --with-reduce
`
3.run make command.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: f0b7a6e7d1c9a5df607ba0c628c58ae701b5b584

**Comment by wanghailiangx** [comment]
This is passed in other servers with gcc v6. I guess this is related to gcc. I am testing  with other gcc version.

**Comment by peluse** [comment]
I've never seen this and use gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2

**Comment by wanghailiangx** [comment]
At present, I reproduced this issue in two servers with GCC v4.8.5.

**Comment by wanghailiangx** [comment]
I raise a patch https://review.gerrithub.io/c/spdk/spdk/+/463126.
@peluse I should not have changed the original meaning of the code, right?

**Comment by jimharris** [comment]
The patch looks good.  I agree that the explicit casts are not needed (and not commonly used when using static initializers).

I just merged the patch - it had +2s from Changpeng, Shuhei and myself.  So closing this issue.  Thanks for the quick turnaround.
