### ISSUE TITLE
build failed on branch spdk-v5.14.3

### ISSUE THREAD

**Issue by clicx** [spdk/spdk#880]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

using master branch of spdk, while can't build successfully each spdk-v* branch or rocksdb.

## Expected Behavior
should build successfully

## Current Behavior
many build errors.

## Steps to Reproduce
just follow https://spdk.io/doc/blobfs.html

## Context (Environment including OS version, SPDK version, etc.)

part of build errors:

db/db_basic_test.cc: In member function 'virtual void rocksdb::DBBasicTest_LevelLimitReopen_Test::TestBody()':
db/db_basic_test.cc:179:15: error: 'class rocksdb::DBImpl' has no member named 'TEST_WaitForFlushMemTable'
     dbfull()->TEST_WaitForFlushMemTable();
               ^
db/db_basic_test.cc:180:15: error: 'class rocksdb::DBImpl' has no member named 'TEST_WaitForCompact'
     dbfull()->TEST_WaitForCompact();
               ^
db/db_basic_test.cc: In member function 'virtual void rocksdb::DBBasicTest_ManifestRollOver_Test::TestBody()':
db/db_basic_test.cc:414:50: error: 'class rocksdb::DBImpl' has no member named 'TEST_Current_Manifest_FileNo'
       uint64_t manifest_before_flush = dbfull()->TEST_Current_Manifest_FileNo();
                                                  ^
db/db_basic_test.cc:416:49: error: 'class rocksdb::DBImpl' has no member named 'TEST_Current_Manifest_FileNo'
       uint64_t manifest_after_flush = dbfull()->TEST_Current_Manifest_FileNo();
                                                 ^
In file included from ./util/testharness.h:15:0,
                 from ./table/mock_table.h:23,
                 from ./db/db_test_util.h:44,
                 from db/db_basic_test.cc:9:
db/db_basic_test.cc:419:27: error: 'class rocksdb::DBImpl' has no member named 'TEST_Current_Manifest_FileNo'
       ASSERT_GT(dbfull()->TEST_Current_Manifest_FileNo(), manifest_after_flush);
                           ^
db/db_basic_test.cc: In member function 'virtual void rocksdb::DBBasicTest_DBCloseFlushError_Test::TestBody()':
db/db_basic_test.cc:949:23: error: 'class rocksdb::DBImpl' has no member named 'TEST_SwitchMemtable'
   ASSERT_OK(dbfull()->TEST_SwitchMemtable());
                       ^
db/db_basic_test.cc:949:3: note: in expansion of macro 'ASSERT_OK'
   ASSERT_OK(dbfull()->TEST_SwitchMemtable());

**Comment by jessehui** [comment]
Hi, thanks for reporting. Could you please give a more detailed steps of how you build. Also, please attach the info of your system, Linux, GCC etc. Thank you.

**Comment by changpe1** [comment]
@clicx you can try with Rocksdb master or v5.14.3 without SPDK patch, looks like this compilation failure is not related with SPDK.

**Comment by clicx** [comment]
I can build master branch of rocksdb from facebook.
gcc version:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Comment by changpe1** [comment]
> I can build master branch of rocksdb from facebook, for spdk branch, just follow the article.
> gcc version:
> gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

And can you compile SPDK in your system separately?

**Comment by clicx** [comment]
Yes.
I now using spdk 19.01, can build rocksdb library successfully, spite there are errors in build test cases.

**Comment by peluse** [comment]
@clicx so you have made progress? Does rocksrb run in spite of the errors in building the test code?

**Comment by changpe1** [comment]
My environment is OK with Rocksdb 5.14.3 so mark this as a third party issue.
