### ISSUE TITLE
git pre-push hook starts dozens to cc processes

### ISSUE THREAD

**Issue by jkryl** [spdk/spdk#881]
My machine was low on memory and gerrithub pre-push hook took ages to complete. I found out that there are dozens of cc processes running and RAM is exhausted. Looking at the pre-push script itself it reveals the reason:

```sh
if [ "$SYSTEM" = "FreeBSD" ]; then
        MAKE="gmake MAKE=gmake -j ${nproc}"
        COMP="clang"
else
        MAKE="make -j ${nproc}"
        COMP="gcc"
fi
```

nproc is not set. Instead what the author wanted to write here is probably `$(nproc)` although that I can only guess. `-j` without integer means unlimited number of procs which seems to be a wrong thing. Opinions?

PS: I had the latest sources from master branch on linux.

**Comment by darsto** [comment]
Ha, good catch. I just pushed a fix - https://review.gerrithub.io/c/spdk/spdk/+/463179

In general, don't hesitate to push one yourself.

Thanks,
D.

**Comment by jkryl** [comment]
I always get goose skin when I see gerrithub 😃  thanks for the fix!
