### ISSUE TITLE
Failed to write to /dev/nvme-fabrics invalid argument over TCP

### ISSUE THREAD

**Issue by pdesh1** [spdk/spdk#883]
NVMEof over TCP fails to connect to the target.
We are running the standard nvme target/host application inside a docker container and it is not working. It works fine outside the container.

sh-4.2# ls /dev/nvme-fabrics
/dev/nvme-fabrics
sh-4.2# ls -la /dev/nvme-fabrics
crw------- 1 root root 10, 56 Jul 25 13:36 /dev/nvme-fabrics

sh-4.2# dmesg
…
[  798.545513] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
[ 1243.307349] nvme_fabrics: no handler found for transport TCP.
[ 1289.113457] nvme_fabrics: no handler found for transport TCP.
 
We checked that the nvme-tcp module is loaded.

sh-4.2# lsmod | grep tcp
nvme_tcp               32768  0
nvme_fabrics           24576  1 nvme_tcp

Docker container is using the same OS mentioned above as a base image and it has all the SPDK packages installed as mentioned in the scripts/setup.sh file.

## Expected Behavior

NVME host over TCP should be able to connect to the Target and do I/O.

## Current Behavior

Not able to connect to the target.

## Steps to Reproduce

Steps to repro
docker run -it --privileged --cpus 4 --shm-size 40960000000 -p 4420:4420 nvmeof
 
[root@xray22b spdk-19.04.1]# systemctl start docker
[root@xray22b spdk-19.04.1]# docker run -it --privileged --cpus 4 --shm-size 40960000000 -p 4420:4420 nvmeof
 
[INFO]  Building SPDK and DPDK ...
sh-4.2#
sh-4.2#
sh-4.2# mkdir -p /tmp
sh-4.2# export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
sh-4.2# cd /root/spdk-19.04.1
sh-4.2# scripts/setup.sh
0000:0f:00.0 (144d a802): Already using the vfio-pci driver
0000:11:00.0 (144d a802): Already using the vfio-pci driver
0000:13:00.0 (144d a802): Already using the vfio-pci driver
0000:15:00.0 (144d a802): Already using the vfio-pci driver
0000:17:00.0 (144d a802): Already using the vfio-pci driver
0000:19:00.0 (144d a802): Already using the vfio-pci driver
0000:1b:00.0 (144d a802): Already using the vfio-pci driver
0000:1d:00.0 (144d a802): Already using the vfio-pci driver
Mounting hugetlbfs at /mnt/huge
 
Current user memlock limit: 0 MB
 
This is the maximum amount of memory you will be
able to use with DPDK and VFIO if run as current user.
To change this, please adjust limits.conf memlock limit for current user.
 
####  Starting the target #############
sh-4.2# app/nvmf_tgt/nvmf_tgt &
[1] 462
sh-4.2# Starting SPDK v19.04.1 / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid462 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 627:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
 
 
##### starting the Transport and listener
sh-4.2# scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -p 8 -c 8192
sh-4.2# scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1
sh-4.2# scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc0
sh-4.2# scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t TCP -a 127.0.0.1 -s 4420
 
#### the target is listening on the port
tcp.c: 726:spdk_nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.1 port 4420 ***
 
####  now it errors
sh-4.2# nvme connect -t TCP -n "nqn.2016-06.io.spdk:cnode1" -a 127.0.0.1 -s 4420
Failed to write to /dev/nvme-fabrics: Invalid argument
sh-4.2# nvme connect -t TCP -n "nqn.2016-06.io.spdk:cnode1" -a 127.0.0.1 -s 4420
Failed to write to /dev/nvme-fabrics: Invalid argument
 
## Context (Environment including OS version, SPDK version, etc.)

sh-4.2# nvme version
nvme version 1.6
 
/root/spdk-19.04.1
Dpdk is at version dpdk-19.05

[root@xray22b ~]# uname -an
Linux xray22b 5.2.2-1.el7.elrepo.x86_64 #1 SMP Sun Jul 21 04:19:28 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

#
# NVME Support
#
CONFIG_NVME_CORE=y
CONFIG_BLK_DEV_NVME=y
# CONFIG_NVME_MULTIPATH is not set
CONFIG_NVME_FABRICS=m
CONFIG_NVME_RDMA=m
CONFIG_NVME_FC=m
CONFIG_NVME_TCP=m
CONFIG_NVME_TARGET=m
CONFIG_NVME_TARGET_LOOP=m
CONFIG_NVME_TARGET_RDMA=m
CONFIG_NVME_TARGET_FC=m
CONFIG_NVME_TARGET_FCLOOP=m
CONFIG_NVME_TARGET_TCP=m
# end of NVME Support

**Comment by jimharris** [comment]
Hi @pdesh1,

Are you able to connect to the SPDK target using an SPDK application (i.e. examples/nvme/identify)?

-Jim

**Comment by pdesh1** [comment]
Hi Jim,

Identify command seems to work but not the connect..
Another thing to note is /dev/nvme-fabrics is not reliably being setup.
Earlier we failed to write to this, now we are not seeing the c-node.

Following is the output -

sh-4.2# ./identify -r 'trtype:TCP adrfam:IPv4 traddr:172.20.0.2 trsvcid:4420'
Starting SPDK v19.04.1 / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: identify --no-shconf -c 0x1 -n 1 -m 0 --no-pci --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid498 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
=====================================================
NVMe over Fabrics controller at 172.20.0.2:4420: nqn.2014-08.org.nvmexpress.discovery
=====================================================
Controller Capabilities/Features
================================
Vendor ID:                             0000
Subsystem Vendor ID:                   0000
Serial Number:                         ....................
Model Number:                          ........................................
Firmware Version:                      19.04.1
Recommended Arb Burst:                 0
IEEE OUI Identifier:                   00 00 00
Multi-path I/O
  May have multiple subsystem ports:   No
  May be connected to multiple hosts:  No
  Associated with SR-IOV VF:           No
Max Data Transfer Size:                131072
NVMe Specification Version (VS):       1.3
NVMe Specification Version (Identify): 1.3
Maximum Queue Entries:                 128
Contiguous Queues Required:            Yes
Arbitration Mechanisms Supported
  Weighted Round Robin:                Not Supported
  Vendor Specific:                     Not Supported
Reset Timeout:                         500 ms
Doorbell Stride:                       4 bytes
NVM Subsystem Reset:                   Not Supported
Command Sets Supported
  NVM Command Set:                     Supported
Boot Partition:                        Not Supported
Memory Page Size Minimum:              4096 bytes
Memory Page Size Maximum:              4096 bytes
Optional Asynchronous Events Supported
  Namespace Attribute Notices:         Not Supported
  Firmware Activation Notices:         Not Supported
128-bit Host Identifier:               Not Supported
 
Controller Memory Buffer Support
================================
Supported:                             No
 
Admin Command Set Attributes
============================
Security Send/Receive:                 Not Supported
Format NVM:                            Not Supported
Firmware Activate/Download:            Not Supported
Namespace Management:                  Not Supported
Device Self-Test:                      Not Supported
Directives:                            Not Supported
NVMe-MI:                               Not Supported
Virtualization Management:             Not Supported
Doorbell Buffer Config:                Not Supported
Abort Command Limit:                   1
Async Event Request Limit:             1
Number of Firmware Slots:              N/A
Firmware Slot 1 Read-Only:             N/A
Firmware Update Granularity:           No Information Provided
Per-Namespace SMART Log:               No
Command Effects Log Page:              Not Supported
Get Log Page Extended Data:            Supported
Telemetry Log Pages:                   Not Supported
Error Log Page Entries Supported:      128
Keep Alive:                            Not Supported
 
NVM Command Set Attributes
==========================
Submission Queue Entry Size
  Max:                       1
  Min:                       1
Completion Queue Entry Size
  Max:                       1
  Min:                       1
Number of Namespaces:        0
Compare Command:             Not Supported
Write Uncorrectable Command: Not Supported
Dataset Management Command:  Not Supported
Write Zeroes Command:        Not Supported
Set Features Save Field:     Not Supported
Reservations:                Not Supported
Timestamp:                   Not Supported
Volatile Write Cache:        Not Present
Atomic Write Unit (Normal):  1
Atomic Write Unit (PFail):   1
Atomic Compare & Write Unit: 1
Scatter-Gather List
  SGL Command Set:           Supported
  SGL Keyed:                 Supported
  SGL Bit Bucket Descriptor: Not Supported
  SGL Metadata Pointer:      Not Supported
  Oversized SGL:             Not Supported
  SGL Metadata Address:      Not Supported
  SGL Offset:                Supported
  Transport SGL Data Block:  Not Supported
Replay Protected Memory Block:  Not Supported
 
Firmware Slot Information
=========================
Active slot:                 0
 
Error Log
=========
 
Discovery Log Page
==================
Generation Counter:                    3
Number of Records:                     1
Record Format:                         0
 
Discovery Log Entry 0
----------------------
Transport Type:                        3 (TCP)
Address Family:                        1 (IPv4)
Subsystem Type:                        2 (NVM Subsystem)
Transport Requirements:
  Secure Channel:                      Not Specified
Port ID:                               0 (0x0000)
Controller ID:                         65535 (0xffff)
Admin Max SQ Size:                     128
Transport Service Identifier:          4420
NVM Subsystem Qualified Name:          nqn.2016-06.io.spdk:cnode1
Transport Address:                     172.20.0.2                                                                  
 
sh-4.2# nvme connect -t tcp -n "nqn.2016-06.io.spdk:cnode1" -a 172.20.0.2 -s 4420
Failed to open /dev/nvme-fabrics: No such file or directory

**Comment by peluse** [comment]
any updates?

**Comment by pdesh1** [comment]
We were able to get past the problem by using the examples/nvme/perf/perf.c utility. It was doing most of the things we wanted to do and we were able to run the utility in one container and target on the other container.

**Comment by jimharris** [comment]
Thanks for the update!  Closing this issue...
