### ISSUE TITLE
"rocksdb.sh: No such file or directory" in rocksdb test

### ISSUE THREAD

**Issue by yuelimv** [spdk/spdk#885]
I'm following the instructions on testing rocksdb and got the following error:

## Current Behavior

 04:03:23	# make db_bench -j72 DEBUG_LEVEL=0 SPDK_DIR=/home/yli/spdk
Makefile:1007: warning: overriding recipe for target `clean'
/home/yli/spdk/mk/spdk.app.mk:55: warning: ignoring old recipe for target `clean'
  GEN      util/build_version.cc
Makefile:1007: warning: overriding recipe for target `clean'
/home/yli/spdk/mk/spdk.app.mk:55: warning: ignoring old recipe for target `clean'
  GEN      util/build_version.cc
  CC       tools/db_bench.o
  CC       tools/db_bench_tool.o
  CC       cache/clock_cache.o
  CC       cache/lru_cache.o
  CC       cache/sharded_cache.o
  CC       db/c.o
  CC       db/builder.o
  CC       db/column_family.o
  CC       db/compacted_db_impl.o
  CC       db/compaction.o
  CC       db/compaction_iterator.o
  CC       db/compaction_job.o
  CC       db/compaction_picker.o
  CC       db/compaction_picker_universal.o
  CC       db/convenience.o
  CC       db/db_filesnapshot.o
  CC       db/db_impl.o
  CC       db/db_impl_compaction_flush.o
  CC       db/db_impl_debug.o
  CC       db/db_impl_experimental.o
  CC       db/db_impl_files.o
  CC       db/db_impl_open.o
  CC       db/db_impl_readonly.o
  CC       db/db_impl_write.o
  CC       db/db_info_dumper.o
  CC       db/db_iter.o
  CC       db/dbformat.o
  CC       db/event_helpers.o
  CC       db/experimental.o
  CC       db/external_sst_file_ingestion_job.o
  CC       db/file_indexer.o
  CC       db/flush_scheduler.o
  CC       db/flush_job.o
  CC       db/forward_iterator.o
  CC       db/internal_stats.o
  CC       db/logs_with_prep_tracker.o
  CC       db/log_writer.o
  CC       db/log_reader.o
  CC       db/malloc_stats.o
  CC       db/managed_iterator.o
  CC       db/memtable.o
  CC       db/memtable_list.o
  CC       db/merge_operator.o
  CC       db/merge_helper.o
  CC       db/range_del_aggregator.o
  CC       db/repair.o
  CC       db/snapshot_impl.o
  CC       db/table_cache.o
  CC       db/table_properties_collector.o
  CC       db/transaction_log_impl.o
  CC       db/version_builder.o
  CC       db/version_edit.o
  CC       db/version_set.o
  CC       db/wal_manager.o
  CC       db/write_batch_base.o
  CC       db/write_controller.o
  CC       db/write_batch.o
  CC       db/write_thread.o
  CC       env/env.o
  CC       env/env_chroot.o
  CC       env/env_encryption.o
  CC       env/env_hdfs.o
  CC       env/env_posix.o
  CC       env/mock_env.o
  CC       env/io_posix.o
  CC       memtable/alloc_tracker.o
  CC       memtable/hash_cuckoo_rep.o
  CC       memtable/hash_linklist_rep.o
  CC       memtable/hash_skiplist_rep.o
  CC       memtable/skiplistrep.o
  CC       memtable/write_buffer_manager.o
  CC       monitoring/histogram.o
  CC       memtable/vectorrep.o
  CC       monitoring/histogram_windowing.o
  CC       monitoring/instrumented_mutex.o
  CC       monitoring/iostats_context.o
  CC       monitoring/perf_context.o
  CC       monitoring/perf_level.o
  CC       monitoring/statistics.o
  CC       monitoring/thread_status_impl.o
  CC       monitoring/thread_status_updater.o
  CC       monitoring/thread_status_updater_debug.o
  CC       monitoring/thread_status_util.o
  CC       monitoring/thread_status_util_debug.o
  CC       options/cf_options.o
  CC       options/db_options.o
  CC       options/options.o
  CC       options/options_helper.o
  CC       options/options_parser.o
  CC       options/options_sanity_check.o
  CC       port/port_posix.o
  CC       port/stack_trace.o
  CC       table/adaptive_table_factory.o
  CC       table/block.o
  CC       table/block_based_filter_block.o
  CC       table/block_based_table_builder.o
  CC       table/block_based_table_factory.o
  CC       table/block_based_table_reader.o
  CC       table/block_builder.o
  CC       table/block_fetcher.o
  CC       table/block_prefix_index.o
  CC       table/bloom_block.o
  CC       table/cuckoo_table_builder.o
  CC       table/cuckoo_table_factory.o
  CC       table/cuckoo_table_reader.o
  CC       table/flush_block_policy.o
  CC       table/format.o
  CC       table/full_filter_block.o
  CC       table/get_context.o
  CC       table/index_builder.o
  CC       table/iterator.o
  CC       table/merging_iterator.o
  CC       table/meta_blocks.o
  CC       table/partitioned_filter_block.o
  CC       table/persistent_cache_helper.o
  CC       table/plain_table_builder.o
  CC       table/plain_table_factory.o
  CC       table/plain_table_index.o
  CC       table/plain_table_key_coding.o
  CC       table/plain_table_reader.o
  CC       table/sst_file_writer.o
  CC       table/table_properties.o
  CC       table/two_level_iterator.o
  CC       tools/dump/db_dump_tool.o
  CC       util/arena.o
  CC       util/auto_roll_logger.o
  CC       util/bloom.o
  CC       util/build_version.o
  CC       util/coding.o
  CC       util/compaction_job_stats_impl.o
  CC       util/comparator.o
  CC       util/concurrent_arena.o
  CC       util/crc32c.o
  CC       util/delete_scheduler.o
  CC       util/dynamic_bloom.o
  CC       util/event_logger.o
  CC       util/file_reader_writer.o
  CC       util/file_util.o
  CC       util/filename.o
  CC       util/filter_policy.o
  CC       util/hash.o
  CC       util/log_buffer.o
  CC       util/murmurhash.o
  CC       util/random.o
  CC       util/rate_limiter.o
  CC       util/slice.o
  CC       util/sst_file_manager_impl.o
  CC       util/status.o
  CC       util/status_message.o
  CC       util/string_util.o
  CC       util/sync_point.o
  CC       util/sync_point_impl.o
  CC       util/thread_local.o
  CC       util/threadpool_imp.o
  CC       util/transaction_test_util.o
  CC       util/xxhash.o
  CC       utilities/backupable/backupable_db.o
  CC       utilities/blob_db/blob_compaction_filter.o
  CC       utilities/blob_db/blob_db.o
  CC       utilities/blob_db/blob_db_impl.o
  CC       utilities/blob_db/blob_file.o
  CC       utilities/blob_db/blob_log_format.o
  CC       utilities/blob_db/blob_log_reader.o
  CC       utilities/blob_db/blob_log_writer.o
  CC       utilities/blob_db/ttl_extractor.o
  CC       utilities/cassandra/cassandra_compaction_filter.o
  CC       utilities/cassandra/format.o
  CC       utilities/cassandra/merge_operator.o
  CC       utilities/checkpoint/checkpoint_impl.o
  CC       utilities/compaction_filters/remove_emptyvalue_compactionfilter.o
  CC       utilities/convenience/info_log_finder.o
  CC       utilities/date_tiered/date_tiered_db_impl.o
  CC       utilities/debug.o
  CC       utilities/document/document_db.o
  CC       utilities/document/json_document.o
  CC       utilities/document/json_document_builder.o
  CC       utilities/env_mirror.o
  CC       utilities/env_timed.o
  CC       utilities/geodb/geodb_impl.o
  CC       utilities/leveldb_options/leveldb_options.o
  CC       utilities/lua/rocks_lua_compaction_filter.o
  CC       utilities/memory/memory_util.o
  CC       utilities/merge_operators/max.o
  CC       utilities/merge_operators/put.o
  CC       utilities/merge_operators/string_append/stringappend.o
  CC       utilities/merge_operators/string_append/stringappend2.o
  CC       utilities/merge_operators/uint64add.o
  CC       utilities/merge_operators/bytesxor.o
  CC       utilities/option_change_migration/option_change_migration.o
  CC       utilities/options/options_util.o
  CC       utilities/persistent_cache/block_cache_tier.o
  CC       utilities/persistent_cache/block_cache_tier_file.o
  CC       utilities/persistent_cache/block_cache_tier_metadata.o
  CC       utilities/persistent_cache/persistent_cache_tier.o
  CC       utilities/persistent_cache/volatile_tier_impl.o
  CC       utilities/redis/redis_lists.o
  CC       utilities/simulator_cache/sim_cache.o
  CC       utilities/spatialdb/spatial_db.o
  CC       utilities/table_properties_collectors/compact_on_deletion_collector.o
  CC       utilities/transactions/optimistic_transaction.o
  CC       utilities/transactions/optimistic_transaction_db_impl.o
  CC       utilities/transactions/pessimistic_transaction.o
  CC       utilities/transactions/pessimistic_transaction_db.o
  CC       utilities/transactions/snapshot_checker.o
  CC       utilities/transactions/transaction_base.o
  CC       utilities/transactions/transaction_db_mutex_impl.o
  CC       utilities/transactions/transaction_lock_mgr.o
  CC       utilities/transactions/transaction_util.o
  CC       utilities/transactions/write_prepared_txn.o
  CC       utilities/transactions/write_prepared_txn_db.o
  CC       utilities/ttl/db_ttl_impl.o
  CC       utilities/write_batch_with_index/write_batch_with_index.o
  CC       utilities/write_batch_with_index/write_batch_with_index_internal.o
  CC       tools/ldb_cmd.o
  CC       tools/ldb_tool.o
  CC       tools/sst_dump_tool.o
  CC       utilities/blob_db/blob_dump_tool.o
  CC       util/testutil.o
  CCLD     db_bench
 04:03:43	# popd
/home/yli/spdk/test/blobfs/rocksdb
 04:03:43	# timing_exit db_bench_build
 04:03:43	# xtrace_disable
 04:03:43	# PREV_BASH_OPTS=ehxBE
 04:03:43	# set +x
 04:03:43	# xtrace_enable
 04:03:43	# /home/yli/spdk/scripts/gen_nvme.sh
 04:03:43	# echo '[Global]'
 04:03:43	# echo 'TpointGroupMask 0x80'
 04:03:43	# trap 'run_bsdump; rm -f $ROCKSDB_CONF; exit 1' SIGINT SIGTERM EXIT
 04:03:43	# '[' -z '' ']'
 04:03:43	# timing_enter mkfs
 04:03:43	# xtrace_disable
 04:03:43	# PREV_BASH_OPTS=ehxBE
 04:03:43	# set +x
 04:03:43	# xtrace_enable
 04:03:43	# /home/yli/spdk/test/blobfs/mkfs/mkfs /home/yli/spdk/test/blobfs/rocksdb/rocksdb.conf Nvme0n1
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: spdk_mkfs --no-shconf -c 0x3 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid376169 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 627:spdk_app_start: *NOTICE*: Total cores available: 2
app.c: 537:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0x80 specified.
app.c: 541:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s spdk_mkfs -p 376169' to capture a snapshot of events at runtime.
app.c: 543:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/spdk_mkfs_trace.pid376169 for offline analysis/debug.
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Initializing filesystem on bdev Nvme0n1...done.
 04:04:03	# timing_exit mkfs
 04:04:03	# xtrace_disable
 04:04:03	# PREV_BASH_OPTS=ehxBE
 04:04:03	# set +x
 04:04:03	# xtrace_enable
 04:04:03	# mkdir -p ./rocksdb
 04:04:03	# RESULTS_DIR=./rocksdb
 04:04:03	# '[' 0 -eq 1 ']'
 04:04:03	# CACHE_SIZE=2048
 04:04:03	# DURATION=20
 04:04:03	# NUM_KEYS=20000000
 04:04:03	# cd ./rocksdb
 04:04:03	# cp /home/yli/spdk/test/blobfs/rocksdb/common_flags.txt insert_flags.txt
 04:04:03	# echo --benchmarks=fillseq
 04:04:03	# echo --threads=1
 04:04:03	# echo --disable_wal=1
 04:04:03	# echo --use_existing_db=0
 04:04:03	# echo --num=20000000
 04:04:03	# cp /home/yli/spdk/test/blobfs/rocksdb/common_flags.txt randread_flags.txt
 04:04:03	# echo --benchmarks=readrandom
 04:04:03	# echo --threads=16
 04:04:03	# echo --duration=20
 04:04:03	# echo --disable_wal=1
 04:04:03	# echo --use_existing_db=1
 04:04:03	# echo --num=20000000
 04:04:03	# cp /home/yli/spdk/test/blobfs/rocksdb/common_flags.txt overwrite_flags.txt
 04:04:03	# echo --benchmarks=overwrite
 04:04:03	# echo --threads=1
 04:04:03	# echo --duration=20
 04:04:03	# echo --disable_wal=1
 04:04:03	# echo --use_existing_db=1
 04:04:03	# echo --num=20000000
 04:04:03	# cp /home/yli/spdk/test/blobfs/rocksdb/common_flags.txt readwrite_flags.txt
 04:04:03	# echo --benchmarks=readwhilewriting
 04:04:03	# echo --threads=4
 04:04:03	# echo --duration=20
 04:04:03	# echo --disable_wal=1
 04:04:03	# echo --use_existing_db=1
 04:04:03	# echo --num=20000000
 04:04:03	# cp /home/yli/spdk/test/blobfs/rocksdb/common_flags.txt writesync_flags.txt
 04:04:03	# echo --benchmarks=overwrite
 04:04:03	# echo --threads=1
 04:04:03	# echo --duration=20
 04:04:03	# echo --disable_wal=0
 04:04:03	# echo --use_existing_db=1
 04:04:03	# echo --sync=1
 04:04:03	# echo --num=20000000
 04:04:03	# timing_enter rocksdb_insert
 04:04:03	# xtrace_disable
 04:04:03	# PREV_BASH_OPTS=ehxBE
 04:04:03	# set +x
 04:04:03	# xtrace_enable
 04:04:03	# run_step insert
 04:04:03	# '[' -z insert ']'
 04:04:03	# echo --spdk=/home/yli/spdk/test/blobfs/rocksdb/rocksdb.conf
 04:04:03	# echo --spdk_bdev=Nvme0n1
 04:04:03	# echo --spdk_cache_size=2048
 04:04:03	# echo -n Start insert test phase...
Start insert test phase... 04:04:03	# /usr/bin/time taskset 0xFF /home/yli/spdk/../rocksdb/db_bench --flagfile=insert_flags.txt
  04:04:03	# trap - ERR
  04:04:03	# print_backtrace
  04:04:03	# [[ ehxBE =~ e ]]
  04:04:03	# xtrace_disable
  04:04:03	# PREV_BASH_OPTS=ehxBE
  04:04:03	# set +x
========== Backtrace start: ==========

in ./rocksdb.sh:18 -> run_step()
     ...
nl: ./rocksdb.sh: No such file or directory
     ...
in ./rocksdb.sh:120 -> main()
     ...
nl: ./rocksdb.sh: No such file or directory
     ...

========== Backtrace end ==========
  04:04:03	# xtrace_enable
  04:04:03	# return 0
 04:04:03	# run_bsdump
 04:04:03	# /home/yli/spdk/examples/blob/cli/blobcli -c /home/yli/spdk/test/blobfs/rocksdb/rocksdb.conf -b Nvme0n1 -D
/home/yli/spdk/../rocksdb/db_bench

 04:04:36	# rm -f /home/yli/spdk/test/blobfs/rocksdb/rocksdb.conf
 04:04:36	# exit 1

## Steps to Reproduce
Follow the instructions on 
https://spdk.io/doc/blobfs.html
Then enter spdk directory and execute

`/home/yli/spdk/test/blobfs/rocksdb/rocksdb.sh`

## Context (Environment including OS version, SPDK version, etc.)
SPDK master branch, CentOS 7.6

**Comment by jimharris** [comment]
There should be an insert_db_bench.txt file in the rocksdb directory after this failure occurs.  Could you post those contents here?

I suspect this might be due to not enough huge pages allocated for the BlobFS cache.  It should be clear from looking at the insert_db_bench.txt contents.  You can allocate more pages by doing something like:

HUGEMEM=8192 scripts/setup.sh

This would allocate 8GB of huge page memory (rather than the 2GB default).

Let's keep this issue open though, even if the huge page memory is the issue.  I've run into this huge page memory issue when running this script before.  It would be nice to add a check in rocksdb.sh to check if enough huge page memory has been allocate and then print a useful message.  Either that, or instruct the user when the script to fails on which debug log to view for more details on the failure.

**Comment by yuelimv** [comment]
I just looked at that file, and it seems the issue might be simpler:

Please install fglags to run rocksdb tools

However, if I simply use the gflags from `yum install gflags-devel` at CentOS, it will actually reports the following error when compiling rocksdb during rocksdb.sh execution:

What would be the specific version of gflag that is required by this rocksdb branch?


  CC       table/cuckoo_table_builder.o
  CC       table/cuckoo_table_factory.o
In file included from tools/db_bench_tool.cc:64:0:
./util/gflags_compat.h:11:26: error: ‘google’ has not been declared
 #define GFLAGS_NAMESPACE google
                          ^
tools/db_bench_tool.cc:81:7: note: in expansion of macro ‘GFLAGS_NAMESPACE’
 using GFLAGS_NAMESPACE::ParseCommandLineFlags;
       ^
./util/gflags_compat.h:11:26: error: ‘google’ has not been declared
 #define GFLAGS_NAMESPACE google
                          ^
tools/db_bench_tool.cc:82:7: note: in expansion of macro ‘GFLAGS_NAMESPACE’
 using GFLAGS_NAMESPACE::RegisterFlagValidator;
       ^
./util/gflags_compat.h:11:26: error: ‘google’ has not been declared
 #define GFLAGS_NAMESPACE google
                          ^
tools/db_bench_tool.cc:83:7: note: in expansion of macro ‘GFLAGS_NAMESPACE’
 using GFLAGS_NAMESPACE::SetUsageMessage;
       ^
tools/db_bench_tool.cc:358:73: error: ‘RegisterFlagValidator’ was not declared in this scope
                                                     &ValidateUint32Range);
                                                                         ^
tools/db_bench_tool.cc:358:73: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:779:78: error: ‘RegisterFlagValidator’ was not declared in this scope
     RegisterFlagValidator(&FLAGS_compression_level, &ValidateCompressionLevel);
                                                                              ^
tools/db_bench_tool.cc:779:78: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1056:69: error: ‘RegisterFlagValidator’ was not declared in this scope
     RegisterFlagValidator(&FLAGS_soft_rate_limit, &ValidateRateLimit);
                                                                     ^
tools/db_bench_tool.cc:1056:69: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1059:69: error: ‘RegisterFlagValidator’ was not declared in this scope
     RegisterFlagValidator(&FLAGS_hard_rate_limit, &ValidateRateLimit);
                                                                     ^
tools/db_bench_tool.cc:1059:69: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1062:66: error: ‘RegisterFlagValidator’ was not declared in this scope
     RegisterFlagValidator(&FLAGS_prefix_size, &ValidatePrefixSize);
                                                                  ^
tools/db_bench_tool.cc:1062:66: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1065:60: error: ‘RegisterFlagValidator’ was not declared in this scope
     RegisterFlagValidator(&FLAGS_key_size, &ValidateKeySize);
                                                            ^
tools/db_bench_tool.cc:1065:60: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1069:53: error: ‘RegisterFlagValidator’ was not declared in this scope
                           &ValidateCacheNumshardbits);
                                                     ^
tools/db_bench_tool.cc:1069:53: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1072:73: error: ‘RegisterFlagValidator’ was not declared in this scope
     RegisterFlagValidator(&FLAGS_readwritepercent, &ValidateInt32Percent);
                                                                         ^
tools/db_bench_tool.cc:1072:73: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1078:70: error: ‘RegisterFlagValidator’ was not declared in this scope
     RegisterFlagValidator(&FLAGS_deletepercent, &ValidateInt32Percent);
                                                                      ^
tools/db_bench_tool.cc:1078:70: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
tools/db_bench_tool.cc:1081:58: error: ‘RegisterFlagValidator’ was not declared in this scope
                           &ValidateTableCacheNumshardbits);
                                                          ^
tools/db_bench_tool.cc:1081:58: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:134:29: note:   ‘gflags::RegisterFlagValidator’
 extern GFLAGS_DLL_DECL bool RegisterFlagValidator(const std::string* flag, bool (*validate_fn)(const char*, const std::string&));
                             ^
  CC       table/cuckoo_table_reader.o
  CC       table/flush_block_policy.o
  CC       table/format.o
  CC       table/full_filter_block.o
tools/db_bench_tool.cc: In function ‘int rocksdb::db_bench_tool(int, char**)’:
tools/db_bench_tool.cc:5378:36: error: ‘SetUsageMessage’ was not declared in this scope
                     " [OPTIONS]...");
                                    ^
tools/db_bench_tool.cc:5378:36: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:331:29: note:   ‘gflags::SetUsageMessage’
 extern GFLAGS_DLL_DECL void SetUsageMessage(const std::string& usage);
                             ^
tools/db_bench_tool.cc:5381:43: error: ‘ParseCommandLineFlags’ was not declared in this scope
   ParseCommandLineFlags(&argc, &argv, true);
                                           ^
tools/db_bench_tool.cc:5381:43: note: suggested alternative:
In file included from ./util/gflags_compat.h:6:0,
                 from tools/db_bench_tool.cc:64:
/usr/include/gflags/gflags.h:346:31: note:   ‘gflags::ParseCommandLineFlags’
 extern GFLAGS_DLL_DECL uint32 ParseCommandLineFlags(int *argc, char*** argv, bool remove_flags);
                               ^
  CC       table/get_context.o

**Comment by yuelimv** [comment]
After installing gflags 2.0, following the CentOS instructions here:

https://github.com/facebook/rocksdb/blob/master/INSTALL.md

The test now runs.

**Comment by yuelimv** [comment]
Actually I found there probably is a bug in rocksdb.sh

here 

cp $testdir/common_flags.txt writesync_flags.txt
echo "--benchmarks=overwrite" >> writesync_flags.txt

I think overwrite should be fillsync?

**Comment by jimharris** [comment]
Hi @yuelimv,

I think the script is OK as it is now.  --disable-wal=0 and --sync=1 will result in sync operations (i.e. each put is sync'd to WAL).  We use overwrite test to overwrite existing keys written in previous tests.

If you still think changes to the script are needed, please file a separate GitHub issue.  We should close this issue since the described problem has been resolved.

Thanks,

-Jim

**Comment by yuelimv** [comment]
Sounds good, thanks Jim.
