### ISSUE TITLE
QAT module installation on VM is failed

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#887]
# Issue reports:
make[4]: Entering directory '/usr/src/kernels/4.19.10-200.fc28.x86_64'
Building for linux_2.6% (17080/66873), 5.13 MiB | 27.00 KiB/s
  CC      /QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalAtomic.o
  CC      /QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalCryptoInterface.o
  CC      /QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalIOMMUMgmt.o
  CC      /QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalMemMgmt.o
  CC      /QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalSemaphore.o
  CC      /QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalServices.o
/QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalServices.c: In function ‘osalTimestampGet’:
/QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalServices.c:513:5: error: implicit declaration of function ‘rdtscll’; did you mean ‘rdtsc’? [-Werror=implicit-function-declaration]
     rdtscll(timestamp);
     ^~~~~~~
     rdtsc
/QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalServices.c:513:5: warning: ‘timestamp’ is used uninitialized in this function [-Wuninitialized]
     rdtscll(timestamp);
     ^~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:304: /QAT/quickassist/utilities/osal/src/linux/kernel_space/OsalServices.o] Error 1
make[4]: *** [Makefile:1521: _module_/QAT/quickassist/utilities/osal/src/linux/kernel_space] Error 2
make[4]: Leaving directory '/usr/src/kernels/4.19.10-200.fc28.x86_64'
Copying outputs
mv: cannot stat 'OsalServices.o': No such file or directory
mv: cannot stat 'OsalSpinLock.o': No such file or directory
mv: cannot stat 'OsalThread.o': No such file or directory
mv: cannot stat 'OsalUsrKrlProxy.o': No such file or directory
make[3]: Leaving directory '/QAT/quickassist/utilities/osal/src/linux/kernel_space'
make[2]: Leaving directory '/QAT/quickassist/utilities/osal/src'

Copying OSAL library
cp /QAT/quickassist/utilities/osal//src/linux/kernel_space/build/linux_2.6/kernel_space/libosal.a /QAT/build/libosal_kernel.a;
cp: cannot stat '/QAT/quickassist/utilities/osal//src/linux/kernel_space/build/linux_2.6/kernel_space/libosal.a': No such file or directory
make[1]: *** [Makefile:149: libosal_kernel] Error 1
make[1]: Leaving directory '/QAT/quickassist'
make: *** [Makefile:1035: quickassist-all] Error 2

## Expected Behavior
install QAT can be successful.

## Current Behavior
install reports errot

## Steps to Reproduce
./vm_setup.sh -i

## Context (Environment including OS version, SPDK version, etc.)
both on fedora28 and ubuntu18.

**Comment by peluse** [comment]
There's some issues with this driver depending on kernel version.  There's a github issue already open to update vm_setup with the new driver which will take care of this, it can be worked around but the new driver is needed anyway for proper operation of QAT.  If you want to install it manually while waiting for vmsetup to be updated the link is in the patch I mentioned here: https://github.com/spdk/spdk/issues/886 

I'd propose closing this one if you're OK with that and just monitor /re-test based on the other one

**Comment by yidong0635** [comment]
@peluse  thanks for your quick response, this just took a long time to setup, I will close it since it's related to #886.
