### ISSUE TITLE
QoS sometimes failed in VM fedora28 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#888]
# Issue reports:
see attached file,
[qos_failure.txt](https://github.com/spdk/spdk/files/3439932/qos_failure.txt)

## Expected Behavior
test can pass

## Current Behavior
test failed at qos.sh.

## Steps to Reproduce
use vagrant to run  iscsi autotest.

## Context (Environment including OS version, SPDK version, etc.)
fedora28.
commit:0e6ddfd66add37ae46ed3639cfb77f73bca55aa1

**Comment by peluse** [comment]
So I'm curious now, from the log clearly we're less than the limit:

 18:37:43       # verify_qos_limits 2248704 3145728
 18:37:43       # local result=2248704
 18:37:43       # local limit=3145728

but the function that's checking is making sure that the the result is at least 85% of the limit which in this case happens to be exactly the case, the result is 85% of the limit. I don't know how the code is implemented but chaning this to -ge might be what it should be doing?

function verify_qos_limits() {
        local result=$1
        local limit=$2
        [ "$(bc <<< "$result > $limit*0.85")" -eq 1 ] && \
        [ "$(bc <<< "$result < $limit*1.05")" -eq 1 ]
}

**Comment by yidong0635** [comment]
the log shows the result/limit=0.71 is lower than 0.85.

**Comment by peluse** [comment]
@Comphix have you had a chance to look at this yet?

**Comment by yidong0635** [comment]
mark the issue as low priority.  I use fedora30 and fedora28 to recreate and run autotest, it no longer happens util now.

**Comment by yidong0635** [comment]
close it, for can't duplicate.
