### ISSUE TITLE
Scripts/rpc.py execution problem

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#889]
Use the master version, commit: 5de38f95431689b88a0f89dc63f938955bf092ba
When executing the rpc.sh script, the following problem will occur：

./scripts/rpc.py -h
Traceback (most recent call last):
  File "./scripts/rpc.py", line 3, in <module>
    from rpc.client import print_dict, print_json, JSONRPCException
  File "/home/xxx/test/spdk/scripts/rpc/__init__.py", line 20, in <module>
    from . import client as rpc_client
  File "/home/xxx/test/spdk/scripts/rpc/client.py", line 161
    msg = "\n".join(["request:", "%s" % json.dumps({**{"method": method, "req_id": req_id},

**Comment by jimharris** [comment]
I'm not able to reproduce this.  client.py line 161 only executes when an RPC is specific, but if you are only running "scripts/rpc.py -h" from the command line, there is no RPC.

Can you provide any additional details?  Such as:

1) Do you have an SPDK application running when you invoke rpc.py?
2) If so, does running "scripts/rpc.py rpc_get_methods" and "scripts/rpc.py get_spdk_version" work?

Thanks,

-Jim

**Comment by peluse** [comment]
FYI works for me also

**Comment by zlsh007** [comment]
hi，Sorry for the late reply
![image](https://user-images.githubusercontent.com/15990748/62188780-01550880-b3a0-11e9-86a7-b3ea9a2ff715.png)

**Comment by changpe1** [comment]
it works for me too.

**Comment by jessehui** [comment]
@zlsh007 Which python version are you using in this environment?

**Comment by zlsh007** [comment]
@jessehui I can use other versions, such as 18.10, also specify python3

**Comment by zlsh007** [comment]
I think it should be my installation package or configuration problem.

**Comment by jessehui** [comment]
Could you do a clean clone and build and run with python3 again to see if these errors still occur? Thank you.

**Comment by zlsh007** [comment]
@jessehui The result of the above test is the code of the clone master, without any changes. When I have time, I will change the machine and test it again.
