### ISSUE TITLE
A question: two unimplemented cases in lvol.sh

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#891]
test/lvol/lvol.sh

In function usage(), 
About case 350 and 400, I cant't find the functions to implement them in test_cases.py. 
      350: 'nested_destroy_logical_volume_negative',
      400: 'nested_construct_logical_volume_positive',

Or maybe they be implemented elsewhere? Or they were not implemented on purpose?
Anyone knows? Thanks.

## Expected Behavior
Adding implementation for the two cases.

## Current Behavior
No implementation.

## Possible Solution
Or remove the two case names. Please review:
https://review.gerrithub.io/c/spdk/spdk/+/463275

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit a81bdcf3802e3a23175011f608a8889440ff59b4

**Comment by darsto** [comment]
Those tests were not implemented for some reason. There's even a few more unimplemented in there.

I'm in the middle of rewriting all the python lvol tests to bash, so the missing cases will be added at some point.

**Comment by wanghailiangx** [comment]
@darsto Thank you for your timely reply. Do you estimate the lvol tests to be rewrited before the release v19.07? If OK, I'll abandon the upper patch [#463275](https://review.gerrithub.io/c/spdk/spdk/+/463275). If there is no such plan, I suggest merging it for the time being.
