### ISSUE TITLE
Makefile  make -jN  reports warning

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#896]
I tried several physical machine and VM.
make -j2/ make -j32
 some reports  warning:
make[2]: warning: -jN forced in submake: disabling jobserver mode.
make -j   doesn't have this warning.
Because I think our code compiling is so slowly and enlarge -jN can't to speed it up.
 
I'm not sure if there's a bug. and report this issue.

## Context (Environment including OS version, SPDK version, etc.)
tried this on fedora28/fedora30/centos7.

**Comment by darsto** [comment]
The warning comes from ISA-L. Thanks, I pushed a fix:

https://review.gerrithub.io/c/spdk/spdk/+/464261 Makefile: don't override MAKEFLAGS in submake

**Comment by jessehui** [comment]
Scan build throws lots of warnings for ISAL. I will push some patches to ISAL and SPDK can checkout to new commit then. Thank you all for reporting and fixing.

**Comment by peluse** [comment]
maybe try removing scnbuild from the make lags for these cases

**Comment by yidong0635** [comment]
@darsto  will you update this ? I saw this patch was nearly ok, thanks!

**Comment by darsto** [comment]
It took me a while - patch updated
