### ISSUE TITLE
OPAL retrieval of MSID_CPIN yields extra character in some cases

### ISSUE THREAD

**Issue by ygoldfill** [spdk/spdk#898]
When taking ownership of the drive, the drive might send the MSID_PIN with
a prefix of MEDIUM_ATOM in which case the next byte holds the LSB of the length.
If opal_response_parse_medium() is used to retrieve the byte string
then the string starts at pos[2]. When opal_response_get_string() is called
later it returns part of the the length along with the reset of the sting.

## Steps to Reproduce
Take ownership of a drive that has an MSID_CPIN longer than 15 bytes.

**Comment by jessehui** [comment]
Hi @ygoldfill , thanks for reporting. May I know what drive are you using? So you can't take ownership with that drive, right? Do you have a log for that?

**Comment by jessehui** [comment]
Please take a try on this : https://review.gerrithub.io/c/spdk/spdk/+/464502

**Comment by ygoldfill** [comment]
Hi jessehui
Your patch worked fine - thanks.
I am using our own company drive which has not yet been released. Yes, I could not take ownership of the drive. I knew it was working as we tested with sedutil-cli. I also noticed that the password  using the SPDK is sent in the clear while it is sent hashed using the sedutil package so I can not take ownership of the dirive with SPDK and manage with sedutil or vise-versa.

**Comment by jessehui** [comment]
@ygoldfill , Thanks for your response. I will take a look on sedutil and see what we can do. As far as I know, kernel is also using clear text. I will see whether we can make it an option to send it with hash or not. Thank you.

**Comment by jessehui** [comment]
It looks like that sedutil is using its self-defined hmac-sha1 for password. In this case, I would suggest to just use SPDK opal tool for configuration as we have even more functions than sedutil. Besides, it can works smoothly with kernel.

**Comment by peluse** [comment]
merged
