### ISSUE TITLE
nvme discover -t rdma -a 192.168.1.110 -s 4420  Failed to write to /dev/nvme-fabrics: Invalid argument

### ISSUE THREAD

**Issue by weingithub** [spdk/spdk#900]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

use  SPDK+NVMeOF to do some test, and target is run ok, but when I run 'nvem discover' command, I got this error.
## Expected Behavior

discover success
## Current Behavior

Failed to write to /dev/nvme-fabrics: Invalid argument

[ 3969.833768] nvme_fabrics: no handler found for transport rdma.
[ 4095.449120] nvme_fabrics: no handler found for transport rdma.
[ 4421.966811] nvme_fabrics: no handler found for transport xx.
[ 4893.858193] nvme_fabrics: no handler found for transport rgma.
[ 4897.970781] nvme_fabrics: no handler found for transport rdma.
[ 4969.774527] nvme_fabrics: no handler found for transport rdma.

## Steps to Reproduce

content in test_rdma.conf
`[Nvme]
  TransportID "trtype:PCIe traddr:0000:02:00.0" Nvme0

[Transport]
  # Set RDMA transport type.
  Type RDMA

[Subsystem1]
NQN nqn.2016-06.io.spdk:cnode1
Listen RDMA 192.168.1.110:4420
AllowAnyHost Yes
Host nqn.2016-06.io.spdk:init
SN SPDK00000000000001
MaxNamespaces 20
Namespace Nvme0n1 1`

1. app/nvmf_tgt/nvmf_tgt -m 15 -c test_rdma.conf  
2. nvme discover /dev/nvme-fabrics -t rdma -a 192.168.1.110 -s 4420
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
target's sever : CentOS Linux release 7.4.1708 (Core) 
client: CentOS Linux release 7.6.1810 (Core)

after I installed Mellanox's driver in client, which version is MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64, then I do modprobe, I got this error:
[ 3024.292569] Request for unknown module key 'Mellanox Technologies signing key: 61feb074fc7292f958419386ffdd9d5ca999e403' err -11

I don't know if there is a relation between these two problems. And I read the nvme_fabic's source [code:](https://code.woboq.org/linux/linux/drivers/nvme/host/fabrics.c.html)  and [https://github.com/larrystevenwise/nvme-fabrics/blob/a909d3e636995ba7c349e2ca5dbb528154d4ac30/drivers/nvme/host/rdma.c](url)
I  suspect when nvme_rdma module plug in kernel, it didn't register to nvme_fabrics. but I am not sure.

**Comment by Seth5141** [comment]
Hi @weingithub,

On the client, what do you get from lsmod | grep rdma and lsmod | grep mlx on the client? I would expect the nvme-rdma to be loaded and depend on nvme-fabrics and for the mlx modules to be loaded.

Thanks

**Comment by weingithub** [comment]
@Seth5141 
`[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# lsmod |grep nvme
nvme_rdma              12432  0 
nvme_fabrics           19998  0 
nvme                   32338  0 
nvme_core              58852  2 nvme,nvme_fabrics
mlx_compat             29590  16 rdma_cm,ib_cm,iw_cm,mlx4_en,mlx4_ib,mlx5_ib,mlx5_fpga_tools,ib_ucm,nvme_rdma,ib_core,ib_umad,ib_uverbs,mlx4_core,mlx5_core,rdma_ucm,ib_ipoib

[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# lsmod |grep mlx
mlx5_fpga_tools        14392  0 
mlx4_en               146420  0 
mlx4_ib               212206  0 
mlx4_core             360639  2 mlx4_en,mlx4_ib
mlx5_ib               345327  0 
ib_uverbs             127130  4 mlx4_ib,mlx5_ib,ib_ucm,rdma_ucm
ib_core               300520  10 rdma_cm,ib_cm,iw_cm,mlx4_ib,mlx5_ib,ib_ucm,ib_umad,ib_uverbs,rdma_ucm,ib_ipoib
mlx5_core             984868  2 mlx5_ib,mlx5_fpga_tools
mlxfw                  18227  1 mlx5_core
devlink                48345  4 mlx4_en,mlx4_ib,mlx4_core,mlx5_core
mlx_compat             29590  16 rdma_cm,ib_cm,iw_cm,mlx4_en,mlx4_ib,mlx5_ib,mlx5_fpga_tools,ib_ucm,nvme_rdma,ib_core,ib_umad,ib_uverbs,mlx4_core,mlx5_core,rdma_ucm,ib_ipoib
ptp                    19231  3 igb,mlx4_en,mlx5_core`

It seems like nvme-rdma not depend on nvme-fabrics.
Thanks

**Comment by Seth5141** [comment]
Yeah, that is very odd. In my system, whenever I have run lsmod, I always have the same dependency. 
~~~
nvme_fabrics           24576  1 nvme_rdma
~~~

I think that something odd is going on with your kernel modules.

Here is the output of my whole lsmod command for a reference.

~~~
lsmod | grep rdma
nvme_rdma              32768  0
nvme_fabrics           24576  1 nvme_rdma
rpcrdma               253952  0
rdma_ucm               32768  0
rdma_cm                69632  7 rpcrdma,ib_srpt,ib_srp,nvme_rdma,ib_iser,ib_isert,rdma_ucm
iw_cm                  49152  1 rdma_cm
ib_cm                  57344  4 rdma_cm,ib_ipoib,ib_srpt,ib_srp
ib_uverbs             110592  2 rdma_ucm,mlx5_ib
ib_core               278528  14 rdma_cm,ib_ipoib,rpcrdma,ib_srpt,ib_srp,nvme_rdma,iw_cm,ib_iser,ib_umad,ib_isert,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm
sunrpc                425984  6 rpcrdma,auth_rpcgss
nvme_core              81920  3 nvme,nvme_rdma,nvme_fabrics
~~~

I am going to mark this as a third party issue, because I believe it is most likely related to something in the client kernel configuration.

**Comment by weingithub** [comment]
@Seth5141 
when I modprobe nvme_rdma，I got this error from dmesg
# modprobe -r nvme_rdma nvme_fabrics
# dmesg |tail
[50770.356433] Request for unknown module key 'Mellanox Technologies signing key: 61feb074fc7292f958419386ffdd9d5ca999e403' err -11

I am not sure if this cause invalid argument problem.  I do some google , got these information:
![image](https://user-images.githubusercontent.com/8966017/62749283-68ed1100-ba8e-11e9-9e0f-e27a4591f6de.png)

It shows "This error can be safely ignored as long as Secure Boot is disabled on the system", and  I am not familiar with kernel or Mellanox, and that's the only error when probe module nvme_rdma.

**Comment by EugeneKochetov** [comment]
Hi @weingithub,

Could you please post the output of "modinfo nvme-rdma"?
As far as I see you use MLNX_OFED. Did you install it yourself? What parameters did you pass to installation script?

BR, Eugene.

**Comment by weingithub** [comment]
Hi, @EugeneKochetov  
[root@node188 mlnx-en-4.6-1.0.1.1-rhel7.6-x86_64-ext]# modinfo nvme_rdma
filename:       /lib/modules/3.10.0-957.12.2.el7.x86_64/kernel/drivers/nvme/host/nvme-rdma.ko.xz
license:        GPL v2
retpoline:      Y
rhelversion:    7.6
srcversion:     F13AD14AE88E3D11EF498A1
depends:        rdma_cm,ib_core,nvme-core,nvme-fabrics
intree:         Y
vermagic:       3.10.0-957.12.2.el7.x86_64 SMP mod_unload modversions 
signer:         CentOS Linux kernel signing key
sig_key:        8D:E6:4F:B5:96:9B:55:7E:DC:7F:03:2E:EA:BC:BE:4F:37:17:7F:4E
sig_hashalgo:   sha256
parm:           register_always:Use memory registration even for contiguous memory regions (bool)

I am not sure whether I install myself, I just know that I was install MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64

**Comment by EugeneKochetov** [comment]
MLNX_OFED by default installs dummy nvme-rdma kernel module which does nothing.
Try to install it with `--with-nvmf` key:
`./mlnxofedinstall --with-nvmf`
This should install correct nvme-rdma driver.

You can check other MLNX_OFED installation options with:
`./mlnxofedinstall --help`

**Comment by weingithub** [comment]
@EugeneKochetov  
that solved the problem of dependency. However, some new error occur, it seems like version's problem.

[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# modprobe nvme_fabrics
modprobe: ERROR: could not insert 'nvme_fabrics': Invalid argument

[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# dmesg |tail
[335329.177953] nvme_fabrics: disagrees about version of symbol nvme_complete_rq
[335329.177958] nvme_fabrics: Unknown symbol nvme_complete_rq (err -22)
[335329.178084] nvme_fabrics: disagrees about version of symbol __nvme_submit_sync_cmd
[335329.178088] nvme_fabrics: Unknown symbol __nvme_submit_sync_cmd (err -22)

[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# modprobe nvme_fabrics --force-modversion
modprobe: ERROR: could not insert 'nvme_fabrics': Exec format error

[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# dmesg |tail 
[335361.658082] nvme_fabrics: version magic '3.10.0-957.el7.x86_64 SMP mod_unload modversions ' should be '3.10.0-957.12.2.el7.x86_64 SMP mod_unload modversions '

[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# modinfo nvme_fabrics
filename:       /lib/modules/3.10.0-957.12.2.el7.x86_64/weak-updates/mlnx-nvme/host/nvme-fabrics.ko
license:        GPL v2
retpoline:      Y
rhelversion:    7.6
srcversion:     735F557A27EA5CBF2FADF96
depends:        mlx_compat,nvme-core
vermagic:       3.10.0-957.el7.x86_64 SMP mod_unload modversions 
signer:         Mellanox Technologies signing key
sig_key:        61:FE:B0:74:FC:72:92:F9:58:41:93:86:FF:DD:9D:5C:A9:99:E4:03
sig_hashalgo:   sha256

[root@node188 MLNX_OFED_LINUX-4.6-1.0.1.1-rhel7.6-x86_64]# uname -r
3.10.0-957.12.2.el7.x86_64

Thanks!

**Comment by EugeneKochetov** [comment]
Looks like you still have old nvme-core module. Did you reload it after MLNX_OFED install?
Try `modprobe -r nvme-rdma nvme-fabrics nvme nvme-core` and then `modprobe nvme-rdma` or just reboot the host to have all modules reloaded.

**Comment by weingithub** [comment]
@EugeneKochetov  It really solve my problem. Thank you very much.
