### ISSUE TITLE
spdk_event_mempool creation failed, when running with shared libraries

### ISSUE THREAD

**Issue by jgrodman** [spdk/spdk#901]
Thank you to @Seth5141 and @jkryl for your help

Repro steps:
Confirmed that this issue occurs on Ubuntu 18.04
@Seth5141 has another distro that does not experience this issue

`./configure --with-shared --without-isal --without-vhost --with-rdma`
`make -j 32`
`sudo LD_LIBRARY_PATH=./build/lib/:./dpdk/build/lib/ ./examples/bdev/hello_world/hello_bdev -c examples/bdev/hello_world/bdev.conf`

output

> Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
> [ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid21543 ]
> EAL: No available hugepages reported in hugepages-1048576kB
> app.c: 627:spdk_app_start: *NOTICE*: Total cores available: 1
> reactor.c: 467:spdk_reactors_init: *ERROR*: spdk_event_mempool creation failed
> app.c: 635:spdk_app_start: *ERROR*: Reactor Initilization failed: rc = -1
> hello_bdev.c: 291:main: *ERROR*: ERROR starting application

**Comment by Seth5141** [comment]
Like @jgrodman mentioned above, on Fedora 28 the above steps properly launch the hello_bdev application. I am looking into the differences between the ubuntu18 and fedora28 to start with.

**Comment by Seth5141** [comment]
@jgrodman https://review.gerrithub.io/c/spdk/spdk/+/464621 fixes this for my ubuntu systems. It looks like ubuntu based systems somehow override ld's default behavior (which is the same as --no-as-needed) while RHEL based systems leave that behavior intact. I just made the --no-as-needed flag explicit in the make files.

**Comment by jgrodman** [comment]
That fixed it for me too. Thank you!

**Comment by Seth5141** [comment]
Change has been merged https://review.gerrithub.io/c/spdk/spdk/+/464621
