### ISSUE TITLE
iscsi related test test/iscsi_tgt/nvme_remote/fio_remote_nvme.sh failed 

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#905]
This test requires SPDK_TEST_NVMF =1 and  SPDK_TEST_ISCSI =1 at the same time.
but it seems that this test is missed in out test pool.
I post a patch here.

https://review.gerrithub.io/c/spdk/spdk/+/463164

put --transport=$SPDK_TEST_NVMF_TRANSPORT behind ./iscsi_tgt.sh posix  has no effect.
./iscsi_tgt.sh posix --transport=$SPDK_TEST_NVMF_TRANSPORT
And
./iscsi_tgt.sh vpp --transport=$SPDK_TEST_NVMF_TRANSPORT

**Comment by yidong0635** [comment]
and past former error here:
=> 9    nvmftestinit
   10   # $1 = "iso" - triggers isolation mode (setting up required environment).
   11   # $2 = test type posix or vpp. defaults to posix.
   12   iscsitestinit $1 $2
   13
   14   rpc_py="$rootdir/scripts/rpc.py"
     ...

========== Backtrace end ==========
  02:27:38      # xtrace_enable
  02:27:38      # return 0
  02:27:38      # trap - ERR
  02:27:38      # print_backtrace
  02:27:38      # [[ ehxBE =~ e ]]
  02:27:38      # xtrace_disable
  02:27:38      # PREV_BASH_OPTS=ehxBE
  02:27:38      # set +x
========== Backtrace start: ==========

in /home/vagrant/master/build-20190813020823/spdk/test/common/autotest_common.sh:531 -> run_test()
     ...
   526          shift
   527          echo "************************************"
   528          echo "START TEST $test_type $@"
   529          echo "************************************"
   530          xtrace_restore
=> 531          time "$@"
   532          xtrace_disable
   533          echo "************************************"
   534          echo "END TEST $test_type $@"
   535          echo "************************************"
   536          xtrace_restore
     ...
in ./test/iscsi_tgt/iscsi_tgt.sh:70 -> main()
     ...
   65   if [ $SPDK_TEST_NVMF -eq 1 ]; then
   66           # NVMe-oF tests do not support network namespaces,
   67           # they can only be run on posix sockets.
   68           if [ "$TEST_TYPE" == "posix" ]; then
   69                   # Test configure remote NVMe device from rpc and conf file
=> 70                   run_test suite ./test/iscsi_tgt/nvme_remote/fio_remote_nvme.sh
   71           fi
   72   fi
   73
   74   if [ $RUN_NIGHTLY -eq 1 ]; then
   75           run_test suite ./test/iscsi_tgt/multiconnection/multiconnection.sh
     ...

**Comment by yidong0635** [comment]
@Seth5141  I put --transport=$SPDK_TEST_NVMF_TRANSPORT to the tail of  fio_remote_nvme.sh.

**Comment by peluse** [comment]
@yidong0635 have you tried this?

**Comment by yidong0635** [comment]
@peluse  of course . here's the logs:

[fio_remote_nvme.sh.txt](https://github.com/spdk/spdk/files/3499342/fio_remote_nvme.sh.txt)

**Comment by Seth5141** [comment]
@yidong0635 What is your ultimate goal with https://review.gerrithub.io/c/spdk/spdk/+/463164? Are you trying to re-enable that test on the build pool, or are you trying to get it to pass locally?
I added some more comments to your patch.

**Comment by yidong0635** [comment]
@Seth5141  I use vagrant to run these cases, at least ,I think this should be covered it locally. That 
@tomzawadzki  and @karlatec  would't to turn on "SPDK_TEST_NVMF=1 " and "SPDK_TEST_ISCSI =1"
on one test machine.
and  for my opinion, SPDK_TEST_ISCSI  should control all  the iscsi tests including iscsi_posix and iscsi_vpp. Although we always treat  iscsi_posix  as the default on, And add optional switch about 
iscsi_posix .
That's  ok , if @tomzawadzki  and @karlatec  feel they are easy to manage.
@tomzawadzki  and @karlatec you can decide what to do,  or I will checkout autotest.sh and only keep "
M
test/iscsi_tgt/iscsi_tgt.sh
+1  -1
M
test/iscsi_tgt/nvme_remote/fio_remote_nvme.sh
"
