### ISSUE TITLE
trace_record intermittent failure

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#908]
Saw this intermittent failure in the test pool today:

https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/39698/archive/RBD_autotest/index.html

Marking low priority for now.  Will raise it to higher priority if it continues to appear.

23:29:33	# echo 'killing process with pid 333654'
killing process with pid 333654
 23:29:33	# kill 333654
 23:29:33	# wait 333654
 23:29:33	# ./app/trace/spdk_trace -f ./tmp-trace/record.trace
  23:29:33	# grep 'trace entries for lcore' ./tmp-trace/record.notice
  23:29:33	# cut -d ' ' -f 2
 23:29:33	# record_num='4096
4096
4096
4096'
  23:29:33	# grep 'Trace Size of lcore' ./tmp-trace/trace.log
  23:29:33	# cut -d ' ' -f 6
 23:29:33	# trace_tool_num='4096
4096
4096
4096'
 23:29:33	# delete_tmp_files
 23:29:33	# rm -rf ./tmp-trace
 23:29:33	# echo 'entries numbers from trace record are:' 4096 4096 4096 4096
entries numbers from trace record are: 4096 4096 4096 4096
 23:29:33	# echo 'entries numbers from trace tool are:' 4096 4096 4096 4096
entries numbers from trace tool are: 4096 4096 4096 4096
 23:29:33	# arr_record_num=($record_num)
 23:29:33	# arr_trace_tool_num=($trace_tool_num)
 23:29:33	# len_arr_record_num=4
 23:29:33	# len_arr_trace_tool_num=4
 23:29:33	# '[' 4 -ne 4 ']'
  23:29:33	# seq 0 3
 23:29:33	# for i in $(seq 0 $((len_arr_record_num - 1)))
 23:29:33	# '[' 4096 -le 4096 ']'
 23:29:33	# echo 'trace record test on iscsi: failure on inefficient entries number check'
trace record test on iscsi: failure on inefficient entries number check
 23:29:33	# set -e
 23:29:33	# exit 1
 23:29:33	# delete_tmp_files
 23:29:33	# rm -rf ./tmp-trace
 23:29:33	# iscsitestfini
 23:29:33	# '[' '' == iso ']'
 23:29:33	# exit 1
  23:29:33	# trap - ERR
  23:29:33	# print_backtrace
  23:29:33	# [[ ehxBE =~ e ]]
  23:29:33	# xtrace_disable
  23:29:33	# PREV_BASH_OPTS=ehxBE
  23:29:33	# set +x
========== Backtrace start: ==========

in /var/jenkins/workspace/RBD_BlobFS_tests/RBD_autotest/spdk/test/common/autotest_common.sh:531 -> run_test()
     ...
   526 		shift
   527 		echo "************************************"
   528 		echo "START TEST $test_type $@"
   529 		echo "************************************"
   530 		xtrace_restore
=> 531 		time "$@"
   532 		xtrace_disable
   533 		echo "************************************"
   534 		echo "END TEST $test_type $@"
   535 		echo "************************************"
   536 		xtrace_restore
     ...
in ./test/iscsi_tgt/iscsi_tgt.sh:46 -> main()
     ...
   41  	# IP Migration tests do not support network namespaces,
   42  	# they can only be run on posix sockets.
   43  	if [ "$TEST_TYPE" == "posix" ]; then
   44  		run_test suite ./test/iscsi_tgt/ip_migration/ip_migration.sh
   45  	fi
=> 46  	run_test suite ./test/iscsi_tgt/trace_record/trace_record.sh
   47  	
   48  	if [ $RUN_NIGHTLY -eq 1 ]; then
   49  		if [ $SPDK_TEST_PMDK -eq 1 ]; then
   50  			run_test suite ./test/iscsi_tgt/pmem/iscsi_pmem.sh 4096 10
   51  		fi

**Comment by yidong0635** [comment]
if this should be ? # '[' 4096 -lt 4096 ']'  why equal reports error?

**Comment by dong-liuliu** [comment]
Hi， Yidong
That sentence is used to check whether spdk_trace_tool works well.

The case will generate lots of trace records. so the original trace shm (which is generated directly by SPDK iscsi_tgt) will be writen round and round. Its number of trace records is always $NUM_TRACE_ENTRIES.

**Comment by dong-liuliu** [comment]
Hi, Jim
Weeks ago, Darek also met this type of failure caused by trace_record  #865 
I've considered the reason for that issue. But seems I failed to explain it clear at that time.

This is really a small probability event.
it was not a fault of spdk_trace_tool, but the process scheduler of the test env.

After spdk_trace_record was called asynchronously, OS process scheduler run it not timely. When spdk_trace_record started to run, spdk iscsi_tgt already exited. The trace shm wouldn't be overwriten any more. So number of trace records captured by spdk_trace_record is same with trace shm.

**Comment by jimharris** [comment]
Hi Xiaodong,

Unfortunately we cannot just ignore these cases.  It is failing patches in the test pool.  Even if it happens very seldom, we need to fix or change the test to ensure we don't get these types of intermittent failures.

Thanks,

-Jim

**Comment by jimharris** [comment]
Xiaodong pushed patch https://review.gerrithub.io/c/spdk/spdk/+/465847 which has been merged.  Thanks Xiaodong!
