### ISSUE TITLE
vpp_autotest intermittent failure

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#909]
http://10.102.17.206/private_build/autotest-per-patch_39706.html

Started by upstream project "autotest-per-patch" build number 39706
originally caused by:
 Started by user sys_sgci
[EnvInject] - Loading node environment variables.
Building remotely on GP1 (nvmf_phy_autotest SingleDisk) in workspace /var/jenkins/workspace/iSCSI_tests/vpp_autotest
Running Prebuild steps
[vpp_autotest] $ /bin/sh -xe /tmp/jenkins8044284274826381251.sh
+ set +x
Success build forhudson.tasks.Shell@ac0876c
provisioning config files...
copy managed file [copy_or_clone] to file:/var/jenkins/workspace/iSCSI_tests/vpp_autotest/copy_or_clone.sh
[vpp_autotest] $ /bin/sh -xe /tmp/jenkins5008758106534031822.sh
+ export PATH=/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/sbin
+ PATH=/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/sbin
+ set +x
MANUAL, will clone
Cloning into '/var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk'...
fatal: reference repository '/var/ci_repos/spdk.git' is not a local repository.
./copy_or_clone.sh: line 16: cd: spdk: No such file or directory
git version 2.20.1
fatal: not in a git directory
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
+ cat
+ sudo -n iscsiadm -m discoverydb -t sendtargets -p 127.0.0.1:3260 -o delete
iscsiadm: Discovery record [127.0.0.1,3260] not found.
+ true
+ sudo -n iscsiadm -m discoverydb -t sendtargets -p 127.0.0.2:3260 -o delete
iscsiadm: Discovery record [127.0.0.2,3260] not found.
+ true
++ ls -A /var/lib/iscsi/nodes
+ '[' '' ']'
+ unset CONFIG_DPDK_DIR
+ [[ -n '' ]]
+ [[ -n '' ]]
+ cd /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk
/tmp/jenkins5008758106534031822.sh: line 76: cd: /var/jenkins/workspace/iSCSI_tests/vpp_autotest/spdk: No such file or directory
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Executing post build scripts.
[vpp_autotest] $ /bin/sh -xe /tmp/jenkins235412293398673483.sh
+ set +x

**Comment by tomzawadzki** [comment]
[Bug scrub] This issue was related to infrastructure and wasn't seen for a long time. Lets close this one.
