### ISSUE TITLE
No way to enable ioat (CB-DMA) when using JSON-RPC

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#914]
ioat is disabled by default.  Currently the only way to enable it is by specifying the following in an INI-style config file:

[Ioat]
  Enable Yes

We need a way to do the same with JSON-RPC.  So likely a startup RPC just for ioat.

**Comment by changpe1** [comment]
@jimharris I can take a look.

**Comment by changpe1** [comment]
spdk_rpc_scan_ioat_copy_engine() already enabled the ioat by default, I'm wondering if we still need another RPC, or we may break the RPC into two parts, one is enable the ioat, the other one is add white list.

**Comment by shuhei-matsumoto** [comment]
Yes, scan_ioat_copy_engine has been added when I worked with Pawel before.
