### ISSUE TITLE
SPDK fails to register >128GB of memory on Linux 5.1+

### ISSUE THREAD

**Issue by darsto** [spdk/spdk#915]
Linux 5.1 introduced a limitation of VFIO regions there can be registered [1]. The default limit is 65535, which combined with the fact that SPDK sends a vfio register ioctl for each 2MB chunk, results in SPDK being able to make only the first 128GB of memory DMA-able. This is problematic for vhost where we need to register the entire VM's memory.

[1] https://github.com/torvalds/linux/commit/492855939bdb59c6f947b0b5b44af9ad82b7e38c

**Comment by jimharris** [comment]
Is this basically because we don't try to merge contiguous regions into a single VFIO_IOMMU_MAP_DMA ioctl?

**Comment by jimharris** [comment]
Never mind - I see this patch now :). https://review.gerrithub.io/c/spdk/spdk/+/432442/2

**Comment by darsto** [comment]
This will be included in SPDK 19.07.1
