### ISSUE TITLE
About vhost_target performance

### ISSUE THREAD

**Issue by zlsh007** [spdk/spdk#916]
spdk-18.10
qemu 1.5.3
libvirt 1.1.1
Hi，all
I use eight NVME disks, the random read performance of the single disk is 650,000 IOPS, the vhost I configured 4 cpus, the virtual machine configured 16 cpus, the same NUMA with the vhost cpu, and the interrupt of the eight disks in the virtual machine. Binding of different cores was performed. But how to test the random read performance is also 1 million IOPS, can you make some suggestions? Am I having a problem with the configuration?
regards
     su

**Comment by zlsh007** [comment]
Using blktrace in a virtual machine to see D2C takes a long time, more than three times slower than normal.

**Comment by zlsh007** [comment]
Each physical device allocates a logical volume and creates a corresponding vhost_controller, which is output to the virtual machine through disk type='vhost-user-blk'.

**Comment by benlwalker** [comment]
Can you post how you've configured and started the vhost target? Is the expectation that you get 8x650k IOPs in the VM?

**Comment by karlatec** [comment]
> type='vhost-user-blk'.
> qemu 1.5.3

Is this  the correct qemu version? :) I might have missed something, but I don't see 1.5.3 supporting vhost-user-blk.

I think we could use more information. Like Ben suggested - vhost target configuration, VM configuration, CPU masks, etc. 
Also - do you have scsi_mod.use_blk_mq=1 enabled inside the guest OS? For multi-CPU VM it will improve performance.

**Comment by zlsh007** [comment]
Sorry for taking so long to reply. Thanks for your reply. It is true that vhost-user is not supported in that version of qemu. We have carried out the back port, and I have tested kernel vhost performance is not good, and it is very low, only a few hundred thousand IOPS of eight disks, but if the virtual machine is configured with the pass-through mode, it is still fast, possibly because of different protocol overhead. I'll make up some configuration information at work tomorrow. Regards      Su HUA SU 邮箱：suhua.tanke@gmail.com 签名由 网易邮箱大师 定制 On 08/22/2019 22:20, Karol Latecki wrote: type='vhost-user-blk'. qemu 1.5.3 Is this the correct qemu version? :) I might have missed something, but I don't see 1.5.3 supporting vhost-user-blk. I think we could use more information. Like Ben suggested - vhost target configuration, VM configuration, CPU masks, etc. Also - do you have scsi_mod.use_blk_mq=1 enabled inside the guest OS? For multi-CPU VM it will improve performance. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zlsh007** [comment]
@benlwalker There is a protocol overhead of less than 8 * 650,000 IOPS, but it feels that 8 disks are only a little low for 1 million IOPS. I can use the nvme passthrough mode to reach more than 3 million IOPS. I think at least this should be better than this. High, or the virtio protocol itself is slow?
Thanks
   su

**Comment by zlsh007** [comment]
spdk conf
[Global]
ReactorMask 0xf
HugeMem 4096
SocketDir /var/tmp
Mode none

[NVMe]
xxx
---------------------------------------------------------------------
********************************************************************************
Hardware Thread Topology
********************************************************************************
Sockets:                2
Cores per socket:       8
Threads per core:       2
Socket 0:               ( 0 16 1 17 2 18 3 19 4 20 5 21 6 22 7 23 )
Socket 1:               ( 8 24 9 25 10 26 11 27 12 28 13 29 14 30 15 31 )
---------------------------------------------------------------------
libvirt：
  <memory unit='KiB'>33554432</memory>
  <currentMemory unit='KiB'>33554432</currentMemory>
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
  <vcpu placement='static' cpuset='0-15'>16</vcpu>  
  <numatune>
    <memory mode='strict' nodeset='0-1'/>
  </numatune>
    ......
    <disk type='vhost-user-blk' device='disk'>
      <driver name='qemu'/>
      <source type='unix' path='/var/tmp/lv0' mode='client'/>
      <target dev='vdb' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </disk>
    ......
    <disk type='vhost-user-blk' device='disk'>
      <driver name='qemu'/>
      <source type='unix' path='/var/tmp/lv7' mode='client'/>
      <target dev='vdi' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x0d' function='0x0'/>
    </disk>
-------------------------------------------------------------------------------------

**Comment by zlsh007** [comment]
![image](https://user-images.githubusercontent.com/15990748/63563244-079b6680-c593-11e9-9e4b-857f01defc2d.png)

**Comment by karlatec** [comment]
@zlsh007 Could you try adding "num-queues" parameter for vhost-usr-blk devices? You can assign it the same value as the number of CPUs for example.

Here's a an example:
```
  -chardev socket,id=char_0,path=/root/vhost_test/vhost/0/naa.0.0 \
  -device vhost-user-blk-pci,num-queues=2,chardev=char_0 "
```

We typically use vhost-usr-blk-pci devices in our tests, but we still use chardev option to connect via vhost socket. I see that "num-queues" are available for both vhost-user-blk and vhost-user-blk-cpi.

**Comment by zlsh007** [comment]
@karlatec I have tried this parameter. When the number of disks is small, it is relatively improved, but when it reaches 8 disks, it will not exceed 1 million.

**Comment by jimharris** [comment]
Hi @zlsh007 - are you still investigating this issue on your end?

If so, can you run your same test with latest QEMU?  It will be difficult to help debug this when running with the custom QEMU 1.5.3 backport.  If you can reproduce with latest QEMU release, it will help with the debug.

Thanks,

Jim

**Comment by zlsh007** [comment]
Hi @jimharris 
Sorry, I don't have an environment of 8 disks now. After I have the environment, I will test it with the latest qemu.

**Comment by jimharris** [comment]
Hi @zlsh007,

I'm going to close this issue.  Please continue to respond on this issue though if you have a chance to test again.

Thanks,

-Jim
