### ISSUE TITLE
iscsi does not unregister iscsi_tgt io_device

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#923]
This seems to be related to the recent iSCSI refactoring.  If you Ctrl-C spdk_tgt or iscsi_tgt, you see this error message:

thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device iscsi_tgt not unregistered

I was able to bisect this down to commit fb641c4b.

**Comment by benlwalker** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/465976

**Comment by jimharris** [comment]
Patch merged.  Thanks Ben!
