### ISSUE TITLE
[Autotest-nightly] Build timed out occured to nvmf_phy_autotest

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#927]
In recent autotest-nightly nvmf_phy_autotest's build.log , when run test/nvmf/target/rpc.sh , it can't come out the loop and build timed out. 

## Expected Behavior
Compile succeessfully without 'build timed out'.

## Current Behavior
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
 09:25:09	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_remove_ns nqn.2016-06.io.spdk:cnode1 5
 09:25:09	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py delete_nvmf_subsystem nqn.2016-06.io.spdk:cnode1
 09:25:09	# for i in $(seq 1 $times)
 09:25:09	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_create nqn.2016-06.io.spdk:cnode1 -s SPDK00000000000001
 09:25:10	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
 09:25:10	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 Malloc1 -n 5
 09:25:10	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_allow_any_host nqn.2016-06.io.spdk:cnode1
 09:25:10	# nvme connect -t rdma -n nqn.2016-06.io.spdk:cnode1 -a 192.168.100.8 -s 4420
 09:25:11	# waitforblk nvme0n1
 09:25:11	# local i=0
 09:25:11	# lsblk -l -o NAME
 09:25:11	# grep -q -w nvme0n1
 09:25:11	# '[' 0 -lt 15 ']'
 09:25:11	# i=1
 09:25:11	# sleep 1
 09:25:12	# lsblk -l -o NAME
 09:25:12	# grep -q -w nvme0n1
 09:25:12	# lsblk -l -o NAME
 09:25:12	# grep -q -w nvme0n1
 09:25:12	# return 0
 09:25:12	# nvme disconnect -n nqn.2016-06.io.spdk:cnode1
Build timed out (after 30 minutes). Marking the build as failed.
Build was aborted
[PostBuildScript] - Executing post build scripts.

## Steps to Reproduce
1. view build log on nvmf_phy_autotest server,
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/604/archive/nvmf_phy_autotest/build.log (at the bottom)

**Comment by tomzawadzki** [comment]
The troublesome part is during `START TEST SUITE test/nvmf/target/connect_disconnect.sh --transport=rdma`.
```
 08:57:33	# /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk/scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t rdma -a 192.168.100.8 -s 4420
 08:57:34	# '[' 1 -eq 1 ']'
 08:57:34	# num_iterations=200
 08:57:34	# set +x
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
[SNIP]
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
NQN:nqn.2016-06.io.spdk:cnode1 disconnected 1 controller(s)
 09:16:32	# trap - SIGINT SIGTERM EXIT
 09:16:32	# nvmftestfini
```
Disconnects take over 15 minutes to finish. @karlatec and @Seth5141 are investigating this failure.

**Comment by karlatec** [comment]
I think I found what the issue was - it was the number of created IO queues when connecting to NVMe-oF subsystem. We use nvme-cli connection for initiator side and default number of io queues is:
```
  [  --nr-io-queues=<LIST>, -i <LIST> ] --- number of io queues to use
                                            (default is core count)
```

Now let's take a look at core count of servers which execute the test.
Server which usually passes the test:
```
[sys_sgci@gklab-17-131 ~]$ nproc
16
[sys_sgci@gklab-17-131 ~]$ lscpu | grep "CPU(s)"
CPU(s):              16
On-line CPU(s) list: 0-15
NUMA node0 CPU(s):   0-7

From dmesg:
[43534.298555] nvme nvme0: creating 16 I/O queues.
[43534.779242] nvme nvme0: mapped 16/0/0 default/read/poll queues.
[43534.784570] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 192.168.100.8:4420
[43535.795683] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
```

Server which usually fails the test:
```
[sys_sgci@localhost ~]$ nproc
72

[sys_sgci@localhost ~]$ lscpu | grep "CPU(s)"
CPU(s):              72
On-line CPU(s) list: 0-71
NUMA node0 CPU(s):   0-17,36-53
NUMA node1 CPU(s):   18-35,54-71

From dmesg:
[25597.893044] nvme nvme0: creating 60 I/O queues.
[25599.105344] nvme nvme0: mapped 60/0/0 default/read/poll queues.
[25599.125352] nvme nvme0: new ctrl: NQN "nqn.2016-06.io.spdk:cnode1", addr 192.168.100.8:4420
[25600.143069] nvme nvme0: Removing ctrl: NQN "nqn.2016-06.io.spdk:cnode1"
```
(I don't know why it's 60 instead of 72 as it should be if we follow nvme-cli description)

Repeatedly creating and destroying 60 IO queues takes more time than for 16 IO queues.
In per-patch version connect_disconnect.sh test takes 16 seconds with 16 IO queues and about 55-60 seconds for 60 IO queues.
I don't think we need to connect with maximum number of queues in this test so I suggest lowering the count with -i option.

**Comment by karlatec** [comment]
Commit with fix: https://review.gerrithub.io/c/spdk/spdk/+/466389

**Comment by Seth5141** [comment]
I haven't seen this issue since the patch was merged. Thanks @karlatec!
