### ISSUE TITLE
vhost tests pass despite ASAN fail

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#931]
This report is about faulty test scripts which do not detect ASAN failure.
There is a separate github issue for ASAN failure itself: [932](https://github.com/spdk/spdk/issues/932)

## Current Behavior
Vhost autotest passes CI despite encountering ASAN fail and coredumping.

## Possible Solution
Most possible that it's a faulty trap instruction.
We should fix the scripts, catch this fail and end tests with failure.

## Steps to Reproduce
1.  Prepare autorun-spdk.conf:
```
SPDK_BUILD_IOAT_KMOD=0
SPDK_BUILD_SHARED_OBJECT=1
SPDK_FEDORA_PACKAGING=0
SPDK_RUN_CHECK_FORMAT=0
SPDK_RUN_SCANBUILD=0
SPDK_RUN_VALGRIND=0
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_UNITTEST=0
SPDK_TEST_ISCSI=0
SPDK_TEST_NVME=0
SPDK_TEST_BDEV_OCSSD=0
SPDK_TEST_FTL=0
SPDK_TEST_NVMF=0
SPDK_TEST_RBD=0
SPDK_TEST_VHOST=1
SPDK_TEST_BLOCKDEV=0
SPDK_TEST_IOAT=0
SPDK_TEST_EVENT=0
SPDK_TEST_BLOBFS=0
SPDK_TEST_PMDK=0
SPDK_TEST_LVOL=0
SPDK_RUN_VPP=0
SPDK_TEST_JSON=0
SPDK_TEST_CRYPTO=1
SPDK_TEST_REDUCE=0
SPDK_TEST_OCF=0
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
SPDK_TEST_VHOST_INIT=0
RUN_NIGHTLY=0
RUN_NIGHTLY_FAILING=0
```
2. ./autobuild.sh ~/autorun-spdk.conf
3. ./autotest.sh ~/autorun-spdk.conf
4. Fail will be as a part of ./test/json_config/json_config.sh test

Examples of failed tests:
http://10.102.17.206/results/autotest-per-patch/builds/40973/archive/vhost_autotest/build.log
http://10.102.17.206/results/autotest-per-patch/builds/40974/archive/vhost_autotest/build.log
http://10.102.17.206/results/autotest-per-patch/builds/40975/archive/vhost_autotest/build.log

## Context (Environment including OS version, SPDK version, etc.)
SPDK 9f5cbf4c7f2022ce9fba85a665a1364e85a7ee07

**Comment by karlatec** [comment]
This change should be able to detect ASAN fail: https://review.gerrithub.io/c/spdk/spdk/+/466412 but it's very simple and the script should be modified more.

**Comment by karlatec** [comment]
@darsto do you think we should try to keep timeout functionality in the script or just use simple "killprocess" instead?

**Comment by karlatec** [comment]
Updated the commit to kill the process outside of "if" statement. Also rebased on top of @glodfish-zg patch for root cause of the problem in .c code.

**Comment by tomzawadzki** [comment]
@karlatec Can we close this issue since patch with fix to implementation and patch detecting failure properly were both merged ?

**Comment by tomzawadzki** [comment]
After confirming with @karlatec this isssue is no longer seen. Relevant patches are merged.
