### ISSUE TITLE
scanbuild reports error at compress_ut.c

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#933]
# Issue
  LINK test/unit/lib/scsi/lun.c/lun_ut
  CC test/unit/lib/scsi/scsi.c/scsi_ut.o
compress_ut.c:780:2: warning: Use of memory after it is freed
        spdk_mempool_free((struct spdk_mempool *)g_mbuf_mp);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  LINK test/unit/lib/bdev/compress.c/compress_ut
  LINK test/unit/lib/scsi/scsi.c/scsi_ut
  CC test/unit/lib/iscsi/portal_grp.c/portal_grp_ut.o
  LINK test/unit/lib/json/json_parse.c/json_parse_ut
## Issue description
  scanbuild mistakenly reports this issue .

## Context (Environment including OS version, SPDK version, etc.)
commit: 9f5cbf4c7f2022ce9fba85a665a1364e85a7ee07
Fedora28

**Comment by peluse** [comment]
See https://review.gerrithub.io/c/spdk/spdk/+/467302   Thanks!

**Comment by peluse** [comment]
patch still under review, has all the required approvals though

**Comment by changpe1** [comment]
Patch is merged, I'm going to close this issue for now.
