### ISSUE TITLE
SPDK NVMeOF host cannot recover from RDMA error automatically then finally all reqs are used up for client 

### ISSUE THREAD

**Issue by gwnet** [spdk/spdk#936]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Currently, SPDK NVMeOF host driver cannot recover from RDMA error automatically like kernel. Each time the RDMA error is detected, it will not have the chance to free the NVMe requests and RDMA requests in the list. Finally from our application, we call read API of SPDK, we will see the NOMEM error. 

## Expected Behavior

I personally feel that Intel should handle this error better like kernel. Below is the two code snippet compare. Please feel free to correct me if I misunderstand anything. I will also new one issue in the github
## Steps to Reproduce

===spdk way to handle RDMA fatal error=== please see yellow highlight part.
nvme_rdma_qpair_process_completions(struct spdk_nvme_qpair *qpair,
                                                              uint32_t max_completions)
{
              struct nvme_rdma_qpair                           *rqpair = nvme_rdma_qpair(qpair);
              struct spdk_nvme_rdma_req     *rdma_req;

              do {
              

                             for (i = 0; i < rc; i++) {
                                           if (wc[i].status) {
                                                          SPDK_ERRLOG("CQ error on Queue Pair %p, Response Index %lu (%d): %s\n",    ------------------ Wayne: SPDK just return when detect RDMA error
                                                                            qpair, wc[i].wr_id, wc[i].status, ibv_wc_status_str(wc[i].status));
                                                          return -1;
                                           }

                                           switch (wc[i].opcode) {
                                           case IBV_WC_RECV:

                                                          if (nvme_rdma_recv(rqpair, wc[i].wr_id)) {  ----------------------------------------Wayne: only these method get executed then it can return the request to the request pool
                                                                        SPDK_ERRLOG("nvme_rdma_recv processing failure\n");
                                                                        return -1;
                                                          }
                                                          break;

                                           case IBV_WC_SEND:
                                                          rdma_req = (struct spdk_nvme_rdma_req *)wc[i].wr_id;

                                                          if (rdma_req->request_ready_to_put) {
                                                                        nvme_rdma_req_put(rqpair, rdma_req); ----------------------------------------Wayne: only these method get executed then it can return the request to the request pool

===kernel way to handle RDMA error=====
Wayne: kernel will detect RDMA error, then trigger error recovery, mark ctrl is reconnecting, and doing reset and reconnection work in one kernel work item.
static int __nvme_rdma_recv_done(struct ib_cq *cq, struct ib_wc *wc, int tag)
{

               if (unlikely(wc->status != IB_WC_SUCCESS)) {
                              nvme_rdma_wr_error(cq, wc, "RECV");
                              return 0;
               }

static void nvme_rdma_wr_error(struct ib_cq *cq, struct ib_wc *wc,
                              const char *op)
{
               struct nvme_rdma_queue *queue = cq->cq_context;
               struct nvme_rdma_ctrl *ctrl = queue->ctrl;

               if (ctrl->ctrl.state == NVME_CTRL_LIVE)
                              dev_info(ctrl->ctrl.device,
                                                   "%s for CQE 0x%p failed with status %s (%d)\n",
                                                   op, wc->wr_cqe,
                                                   ib_wc_status_msg(wc->status), wc->status);
               nvme_rdma_error_recovery(ctrl);
}

static void nvme_rdma_error_recovery(struct nvme_rdma_ctrl *ctrl)
{
               if (!nvme_change_ctrl_state(&ctrl->ctrl, NVME_CTRL_RECONNECTING))
                              return;

               queue_work(nvme_rdma_wq, &ctrl->err_work);
}

**Comment by gwnet** [comment]
Dear Intel experts
we have got a way to reproduce this issue with all SPDK open source tools perf

we use the ib_send_bw tool to ingest incast load into RDMA NICs during the perf testing. then SPDK perf will report below error and cannot recover from it.


Starting SPDK v19.04.1 / DPDK 19.02.0 initialization...

[ DPDK EAL parameters: perf --no-shconf -c 0xf --no-pci --log-level=lib.eal:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid34522 ]

EAL: No free hugepages reported in hugepages-1048576kB

Initializing NVMe Controllers

Attaching to NVMe over Fabrics controller at 192.168.219.7:4420: n-1-node47-nvme2

Attached to NVMe over Fabrics controller at 192.168.219.7:4420: n-1-node47-nvme2

controller IO queue size 1024 less than required

Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.

Attaching to NVMe over Fabrics controller at 192.168.219.7:4421: n-1-node47-nvme3

Attached to NVMe over Fabrics controller at 192.168.219.7:4421: n-1-node47-nvme3

controller IO queue size 1024 less than required

Consider using lower queue depth or small IO size because IO requests may be queued at the NVMe driver.

WARNING: Some requested NVMe devices were skipped

Associating Linux                (5106b69b1687fda7    ) with lcore 3

Associating Linux                (2363914bf0f17e99    ) with lcore 2

Associating Linux                (5106b69b1687fda7    ) with lcore 1

Associating Linux                (2363914bf0f17e99    ) with lcore 0

Initialization complete. Launching workers.

Starting thread on core 3

Starting thread on core 2

Starting thread on core 1

Starting thread on core 0

nvme_rdma.c:1680:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x7f6c4c0008e0, Response Index 140103109069640 (12): transport retry counter exceeded

nvme_rdma.c:1680:nvme_rdma_qpair_process_completions: *ERROR*: CQ error on Queue Pair 0x7f6c540008e0, Response Index 140103243123656 (12): transport retry counter exceeded

NVMe io qpair process completion error

NVMe io qpair process completion error

**Comment by gwnet** [comment]
possible soltuion
SPDK latest code will mark ctrl as failed state when detect fatal CQE error

	qpair->in_completion_context = 1;
	ret = nvme_transport_qpair_process_completions(qpair, max_completions);
	if (ret < 0) {
		SPDK_ERRLOG("CQ error, abort requests after transport retry counter exceeded\n");
		qpair->ctrlr->is_failed = true;
	}
	qpair->in_completion_context = 0;


==solution1===
can we just in our code, before we issue IO, we check ctrl failed state, if it failed state, we call spdk_nvme_ctrlr_reset(ctrlr);
then issue IO. this way does not need change SPDK code, only our code change is OK. worth a try?

**Comment by gwnet** [comment]
bear in mind we are using SPDK NVMeOF host side code.
another possible solution is that can we use bdev at host side? I see bdev has more complex error handling code!~ can intel expert suggest

**Comment by yidong0635** [comment]
@gwnet ,
Before our experts give you a suggestion, I have an idea about this:
1: configure your target,  using "`./configure + --enable-asan` " to run startup target to check if there's a memory leak which could cause resources exhausted.
2. I think you can try to add what you want to add . For my limited understanding, the rdma recovery 
is still a problem.
may be then our experts will give you more details.

**Comment by gwnet** [comment]
hello dear intel expert, below is our reproduce steps, anyone can play it. or I feel intel can add CQE error in the error ingestion framework, then it is easy for us to play reset
1.	Run 3 ib_write_bw servers on 10.249.248.45
ib_write_bw -p 19875 -s 10485760
ib_write_bw -p 19876 -s 10485760
ib_write_bw -p 19877 -s 10485760
2.	Run ib_write_bw client on other three nodes. one node run one ib_write_bw client.
sudo -i ib_write_bw -D 1200 -p 19875 192.168.219.5 -s 10485760 (node 1)
sudo -i ib_write_bw -D 1200 -p 19876 192.168.219.5 -s 10485760 (node 2)
sudo -i ib_write_bw -D 1200 -p 19877 192.168.219.5 -s 10485760 (node 3)
3.	Run spdk perf on 10.249.248.45.
./perf -q 1 -o 4194304 -t 600 -c 0xf -w read -r 'trtype:RDMA adrfam:IPv4 traddr:192.168.219.7 trsvcid:4420’

**Comment by gwnet** [comment]
> @gwnet ,
> Before our experts give you a suggestion, I have an idea about this:
> 1: configure your target, using "`./configure + --enable-asan` " to run startup target to check if there's a memory leak which could cause resources exhausted.
> 2. I think you can try to add what you want to add . For my limited understanding, the rdma recovery
> is still a problem.
> may be then our experts will give you more details.

thank you so much Man. we will use that to trouble shoot memory leak. it is for huge page heap management leak? can it also trouble shoot c lib heap leak? I see we also have c lib heap leak. 

yes, for RDMA error happen and recovery, can intel have one expert to help? if solution 1 is strong fix? I guess no.

**Comment by Comphix** [comment]
@gwnet , what is target (looks like Kernel Target) reporting when we saw below error on the host side.

The error message says "transport retry counter exceeded" which seems that some IO is sent, met error and retried and eventually exceeding the retry count.

nvme_rdma.c:1680:nvme_rdma_qpair_process_completions: ERROR: CQ error on Queue Pair 0x7f6c4c0008e0, Response Index 140103109069640 (12): transport retry counter exceeded

nvme_rdma.c:1680:nvme_rdma_qpair_process_completions: ERROR: CQ error on Queue Pair 0x7f6c540008e0, Response Index 140103243123656 (12): transport retry counter exceeded

NVMe io qpair process completion error

NVMe io qpair process completion error

From this piece of information, seems this is one I/O error, do you have other error message to cause the subsequent error of NOMEM (lack of memory)? This may be as mentioned above like memory leak? Also have you see the same NOMEM error in the SPDK perf tool? Just make sure under which tool or application, the NOMEM is seen.

Also for above reproduction steps, what is IP 192.168.219.7 for? It seems that 10.249.248.45 is the Target running?

Please list detailed configuration both from Host and Target side, this could help us to reproduce the error first.

Thanks, Gang

**Comment by tomzawadzki** [comment]
Bug scrub: @Seth5141 is working on resolving general RDMA error recovery, please see #407.

**Comment by gwnet** [comment]
@Seth5141   may I know how it is going on for the fix of 407? can I help you to do some test from our side?

**Comment by Seth5141** [comment]
@gwnet I have a patch series out currently that has added reconnect capability when we receive certain RDMA_CM_EVENTS. The head of that change series is here. https://review.gerrithub.io/c/spdk/spdk/+/470257. The series has introduced a generic framework for performing reconnects, and I will only need to add a couple more small changes to recover from CQ errors as well.

**Comment by gwnet** [comment]
@Seth5141 do you have your own branch so that I can test on it?

**Comment by gwnet** [comment]
may I know how it is going on for the fix @Seth5141
do you have one branch for me to test?

**Comment by Seth5141** [comment]
@gwnet The patches are still a work in progress.

The top of the patch series is located here: https://review.gerrithub.io/c/spdk/spdk/+/471556/4. You can clone it by clicking on the buttons icon in the top right corner of the screen and selecting the download patch->checkout option.

You can test it with your application. There is a good example of how to handle reconnects within an application located in this patch https://review.gerrithub.io/c/spdk/spdk/+/471661/2

**Comment by Seth5141** [comment]
@gwnet The reconnect related patches have now been merged to the master branch. There is a note in the changelog as well as an example application to handle qpair and controller reconnect when we get completion queue errors on an RDMA queue.
If you feel these changes properly address your initial issue, please indicate here, and I will close this issue.

Thanks,

Seth

**Comment by jimharris** [comment]
Bug scrub: patches from @Seth5141 have been merged, so closing this issue.  @gwnet - if you still see any problems, please reopen this issue.
