### ISSUE TITLE
[Autotest-nightly] Build timed out occured to blockdev_autotest

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#937]
In recent autotest-nightly blockdev_autotest's build.log , when run test/compress/compress.sh , it build timed out. 

## Expected Behavior
Compile succeessfully without 'build timed out'.

## Current Behavior
== Build lib/librte_ethdev
  AR librte_reorder.a
  INSTALL-LIB librte_reorder.a
  SYMLINK-FILE include/rte_ethdev.h
  SYMLINK-FILE include/rte_ethdev_driver.h
  SYMLINK-FILE include/rte_ethdev_core.h
  SYMLINK-FILE include/rte_ethdev_pci.h
  SYMLINK-FILE include/rte_ethdev_vdev.h
  SYMLINK-FILE include/rte_eth_ctrl.h
  SYMLINK-FILE include/rte_dev_info.h
  SYMLINK-FILE include/rte_flow.h
  SYMLINK-FILE include/rte_flow_driver.h
  SYMLINK-FILE include/rte_tm.h
  SYMLINK-FILE include/rte_tm_driver.h
  SYMLINK-FILE include/rte_mtr.h
  SYMLINK-FILE include/rte_mtr_driver.h
  CC ethdev_private.o
  CC rte_ethdev.o
  CC rte_class_eth.o
  CC rte_flow.o
  CC rte_tm.o
  AR librte_compressdev.a
  CC rte_mtr.o
  CC ethdev_profile.o
  INSTALL-LIB librte_compressdev.a
  AR librte_cryptodev.a
  INSTALL-LIB librte_cryptodev.a
  AR librte_ethdev.a
  INSTALL-LIB librte_ethdev.a
== Build lib/librte_vhost
Build timed out (after 12 minutes). Marking the build as failed.
Build was aborted
[PostBuildScript] - Executing post build scripts.
[blockdev_autotest] $ /bin/sh -xe /tmp/jenkins4214027295536938849.sh

## Steps to Reproduce
1. view build log on blockdev_autotest server,
https://10.102.17.104:8080/job/Other/job/blockdev_autotest/35065/artifact/build.log (at the bottom)

**Comment by karlatec** [comment]
@ChenBo2333 please do not link results to Jenkins directly as the logs have short retention and are removed pretty quickly. Instead please link to https://dqtibwqq6s6ux.cloudfront.net/ if possible.

Unfortunately the log is already timed out and the log snippet you pasted isn't much useful for root-causing. Can you try to find it on Cloudfront pages?

**Comment by ChenBo2333** [comment]
I'm sorry for the lost of link results , and the new link is https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly-failing/builds/459/archive/blockdev_autotest/build.log

**Comment by ChenBo2333** [comment]
[blockdev_autotest.txt](https://github.com/spdk/spdk/files/3593872/blockdev_autotest.txt)

**Comment by tomzawadzki** [comment]
Bug scrub: There were number of changes to the particular machine running blockdev (change a faulty disk) and improved NFS connectivity. It doesn't seem to appear since then. If it occurs again, please reopen.
