### ISSUE TITLE
git status --porcelain check timeouts during autopackage.sh

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#939]
During test for SPDK 19.07 vs DPDK master one of the jobs times out on autopackage.sh.

Please see log:
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-spdk-19-07-vs-dpdk-master_199.html

Looking at Jenkins log that adds additional timestamps:
```
05:14:40   05:17:20	$ xtrace_enable
05:14:40  05:17:20	$ out=/var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest
05:14:40  05:17:20	$ MAKEFLAGS=-j16
05:14:40  05:17:20	$ cd /var/jenkins/workspace/NVMeOF_tests/nvmf_phy_autotest/spdk
05:14:40  05:17:20	$ timing_enter porcelain_check
05:14:40  05:17:20	$ xtrace_disable
05:14:40  05:17:20	$ PREV_BASH_OPTS=ehxBE
05:14:40  05:17:20	$ set +x
05:14:40  05:17:20	$ xtrace_enable
05:14:40  05:17:20	$ make clean
05:14:46   05:17:26	$ git status --porcelain --ignore-submodules
05:14:46   05:17:26	$ wc -l
05:17:33 Build timed out (after 10 minutes). Marking the build as failed.
05:17:33 Build was aborted
05:17:33 [PostBuildScript] - Executing post build scripts.
05:17:33 [nvmf_phy_autotest] $ /bin/sh -xe /tmp/jenkins3591651516536424793.sh
05:17:33 + set +x
05:17:33 Archiving artifacts
05:17:34 Tests finished with errors. Please check the logs for more info.
05:17:34 Execution node will be rebooted.
05:17:35 Triggering a new build of reset-job
05:17:35 Finished: FAILURE
```
Looks like the build hangs for almost 3 minutes on `wc -l` or right after it before calling `timing_exit porcelain_check`.

**Comment by karlatec** [comment]
Found an issue with our NFS network. I updated the configuration a bit and the issue should be resolved.
If similar issue doesn't show up in a couple of days then I think we can close the issue.

**Comment by tomzawadzki** [comment]
After talking with @karlatec offline. Elaborating bit more for posterity.
SPDK repo is archived and copied from single machine to each one that executes particular job. Turns out that there are git alternates that point to directory available from all machines over NFS:
`./.git/objects/info/alternates:1:/var/ci_repos/spdk.git/objects`. This caused `git status` to communicate over NFS and cause delay from time to time.

One solution would be to remove those alternates from repo before/after archiving, but plan is to abandon this way to delivering sources between machines anyway.
As to not spend time on stop-gap solution, @karlatec narrowed down couple machines that had trouble with NFS from time to time and fixed those.

The issue should no longer show up - I'm fine with closing this issue.
