### ISSUE TITLE
new code reports warning at igzip/igzip_inflate.c

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#941]
# Issue
[root@waikikibeach40 spdk]# make clean && make -j
igzip/igzip_inflate.c: In function 'check_gzip_checksum':
igzip/igzip_inflate.c:1867:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    *(uint64_t *) (state->tmp_in_buffer + tmp_in_size) =
    ^
igzip/igzip_inflate.c: In function 'check_zlib_checksum':
igzip/igzip_inflate.c:1918:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    *(uint64_t *) (state->tmp_in_buffer + tmp_in_size) =
    ^
igzip/igzip_inflate.c: In function 'isal_inflate':
igzip/igzip_inflate.c:2387:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    *(uint32_t *) & state->tmp_out_buffer[state->tmp_out_valid] =
    ^

## Expected Behavior
compiling without warning

## Current Behavior
compiling with warning.
## Steps to Reproduce
steps:
git clone https://github.com/spdk/spdk.git
 cd spdk/
 git submodule update --init
./configure
make clean && make -j

## Context (Environment including OS version, SPDK version, etc.)
Linux waikikibeach40 3.10.0-957.12.1.el7.x86_64 #1 S

**Comment by peluse** [comment]
I don't get this warning, on master with gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

**Comment by yidong0635** [comment]
this exists on  CentOS Linux release 7.6.1810 (Core)
[root@waikikibeach40 spdk]# uname -a
Linux waikikibeach40 5.2.0-1.el7.elrepo.x86_64 #1 SMP Mon Jul 8 09:37:45 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@waikikibeach40 spdk]# make clean && make -j
igzip/igzip_inflate.c: In function 'check_gzip_checksum':
igzip/igzip_inflate.c:1867:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    *(uint64_t *) (state->tmp_in_buffer + tmp_in_size) =
    ^
igzip/igzip_inflate.c: In function 'check_zlib_checksum':
igzip/igzip_inflate.c:1918:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    *(uint64_t *) (state->tmp_in_buffer + tmp_in_size) =
    ^
igzip/igzip_inflate.c: In function 'isal_inflate':
igzip/igzip_inflate.c:2387:4: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    *(uint32_t *) & state->tmp_out_buffer[state->tmp_out_valid] =
    ^
Configuration done using x86_64-native-linuxapp-gcc

**Comment by jimharris** [comment]
Bug scrub: We would like to close this issue as a 3rd party issue.  @yidong0635 can you confirm that these warnings do not fail the SPDK build, but just appear as warnings in the log?  If so, please close this issue.  Thanks.

**Comment by yidong0635** [comment]
@jimharris  , yes, just warnings, these warnings do not fail the SPDK build ,close it.
