### ISSUE TITLE
Unable to end iscsi_tgt with kill -15

### ISSUE THREAD

**Issue by ccoderr** [spdk/spdk#943]
I am performing the spdk/tests TestSuite_iscsi_nvme_fio test. After a test case runs fio and the iscsi_tgt process exits with kill -15, I find that the process is hanging in shutdown.

## Expected Behavior
I can end iscsi_tgt with kill -15

## Current Behavior
The iscsi_tgt exit hangs. I found the program hanging in the spdk_iscsi_conn_check_shutdown because the spdk_iscsi_get_active_conns check is always not equal to 0. There is only one conn currently and the conn is in state ISCSI_CONN_STATE_EXITED. I found that checking the pending_task_cnt is always equal to 1 in the spdk_iscsi_conn_free_tasks function. There is a read10 command that is abort, and the task is not free.

## Possible Solution

Some commands that are aborted need to be properly freed
## Steps to Reproduce

1.run the spdk/tests TestSuite_iscsi_nvme_fio test
2.Check the iscsi_tgt process when exiting
3.
4.

**Comment by peluse** [comment]
can you please provide the exact command line you are using to start the tests?

**Comment by ccoderr** [comment]
i just run test/framework/main.py
My execution.cfg is as follows
`
[Execution]
crbs=10.252.1.152         
drivername=mlx5_core
test_suites=            
#    nvmf_malloc_fio,
#    nvmf_nvme_fio,
#    nvmf_aiobackend_fio,
#    nvmf_rxtxqueue,
#    nvmf_multiconnection,
#    nvmf_filesystem_integrity,
#    iscsi_malloc_fio,
    iscsi_nvme_fio,
#    iscsi_aiobackend_fio,
#    iscsi_rxtxqueue,
#    iscsi_multiconnection,
#    iscsi_filesystem_integrity,
targets=SPDK_components
parameters=nic_type=ConnectX4:func=true`

**Comment by tomzawadzki** [comment]
Bug scrub: @ccoderr test/framework/main.py is not part of SPDK tests. Can you please provide steps to reproduce with code from SPDK repo ?

**Comment by changpe1** [comment]
[Bug scrub]: @ccoderr test/framework/main.py is not part of SPDK tests. Can you please provide steps to reproduce with code from SPDK repo ?

**Comment by jimharris** [comment]
Bug scrub: closing this issue pending additional details on the scripts used to produce this issue.  We think this may have been produced using the spdk/tests repository, but need further details.
