### ISSUE TITLE
fio_plugin issue ( not compiled)

### ISSUE THREAD

**Issue by nizarbo-flexxon** [spdk/spdk#947]
Hi there,
below my system settings:
- ubuntu 16.04
- lastest spdk  from github/spdk
- my configuraiton with fio and linked to the write source code of fio directory.
 I have 3 errors during compile:
1- from fio_plugin.c:34:
../fio/arch/../lib/types.h:5:13: error: two or more data types in declaration specifiers
 typedef int bool;
2- ../fio/os/../oslib/strsep.h:6:7: error: expected identifier or ‘(’ before ‘__extension__’
 char *strsep(char **, const char *);
3- 
../fio/os/../oslib/strsep.h:6:7: error: expected identifier or ‘(’ before ‘)’ token
 char *strsep(char **, const char *);

Fio already compiled and used no issue, do you think this error because I used New Version of FIO libs 3.15 or I should down grade to fio 2.X
Best Regards

**Comment by yidong0635** [comment]
please checkout fio-3.3 , and have a try.

**Comment by nizarbo-flexxon** [comment]
Hi There,
thank you for your message I already fixed.
