### ISSUE TITLE
[Autotest-nightly] Permission denied witnessed on many build logs

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#952]
In recent autotest-nightly-failing's build.log , many build logs failed because of "Permission denied".

## Expected Behavior
Compile succeessfully without "Permission denied".

## Current Behavior
In ioat_autotest build log:

[ioat_autotest] $ /bin/sh -xe /tmp/jenkins7176948984414420511.sh
_+ set +x
UPSTREAM, will not clone
cp: cannot open '/var/ci_repos/spdke62a3c655340d253b49613e1c067eeceff6cc5e9.zip' for reading: Permission denied
unzip:  cannot find or open spdke62a3c655340d253b49613e1c067eeceff6cc5e9.zip, spdke62a3c655340d253b49613e1c067eeceff6cc5e9.zip.zip or spdke62a3c655340d253b49613e1c067eeceff6cc5e9.zip.ZIP.
./copy_or_clone.sh: line 11: cd: spdk: No such file or directory
fatal: not a git repository (or any of the parent directories): .git_

and the same failure occured to ubuntu16 , vhost_initator , nvmf , lvol , crypto.

## Steps to Reproduce
View build log on autotest-nightly-failing server,
https://10.102.17.104:8080/job/autotest-nightly-failing/470/
(Failure witnessed on these build logs : ioat , ubuntu16 , vhost_initator , nvmf , lvol , crypto. This is the short retention link , and I'll update Cloudfront pages' link after it reserved.)

## Context (Environment including OS version, SPDK version, etc.)

**Comment by ChenBo2333** [comment]
The new link:
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly-failing_470.html

**Comment by karlatec** [comment]
I see a number of intermittent failures (internal network related, sources did not copy properly), but there is no issue with permissions in any of these fails. 
IMO this issue is invalid and should be closed.

**Comment by tomzawadzki** [comment]
[Bug scrub] It hasn't been seen for almost a month. Let's close it and if it appears again - reopen.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_4490.html

**Comment by karlatec** [comment]
Fail does not look related to this github issue.
