### ISSUE TITLE
module/bdev/ocf: get error log when using ocf vbdev 

### ISSUE THREAD

**Issue by richael02** [spdk/spdk#953]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

I run " ./examples/bdev/hello_world/hello_bdev -c bdev1.conf -b wt_test " . For the first time I use bdev1.conf and second time I use bdev2.conf. And in the second time, there is and error log "_vbdev_ocf.c:1101:init_vbdev: *ERROR*: Device with name 'wt_test' already exists_", but the whole command runs successfully. 

##bdev1.conf###################
[AIO]
         AIO /dev/sdc AIO1
         AIO /dev/sdb AIO0
[Split]
        Split  AIO1  2  4096
[OCF]
        OCF wt_test wt AIO1p0 AIO0
###end bdev1.conf###############

##bdev2.conf##################
[AIO]
         AIO /dev/sdc AIO1
         AIO /dev/sdb AIO0
[Split]
        Split  AIO1  2  4096
[OCF]
        OCF wt_test wt AIO1p1  AIO0
##end bdev2.conf###############

**## Possible Solution**
I did some analysis. For AIO1 is split into AIO1p0 and AIO1p1, both parts will be examined. When examining AIO1p0,  it will run ocf_metadata_probe()  to probe AIO1p0's metadata which retains the information of bdev1.conf. And then it will do vbdev_ocf_construct() to construct a ocf bdev with vbdev_name=wt_test ,cache=AIO1p0 and core_name=AIO0( the same with the configuration in bdev1.conf).  And then an error: "Device with name  wt_test already exists" is triggered. And I think this shouldn't be an error .  I'm not sure if we can add an judgement before vbdev_ocf_construct() for I'm not familiar with ocf.

module/bdev/ocf/vbdev_ocf.c:1470:
`if (spdk_bdev_get_by_name(vbdev_name) || vbdev_ocf_get_by_name(vbdev_name)) {
            SPDK_WARNLOG("Device with name '%s' already exists\n", vbdev_name);
            examine_ctx_put(ctx);
        } else {
            vbdev_ocf_construct(vbdev_name, NULL, ctx->base.bdev->name, core_name, true,
                    metadata_probe_construct_cb, ctx);
        }
`

## Context (Environment including OS version, SPDK version, etc.)
ubuntu18.04， SPDK  master

**Comment by jessehui** [comment]
@richael02 , thank you for bring this up. For now, during examine, the OCF bdev will be loaded as long as there is valid metadata. And that's why it reports same name error here.  It is for production environment when SPDK target is killed or crashed, next time you restart it, it can load previous configuration for OCF without any other configuration. We will work on RPCs to make metadata invalid.
I think here you can give another name to the new OCF bdev or you can use dd to erase metadata of the cache device.

**Comment by richael02** [comment]
@jessehui , thanks!  I'll try to erase metadata of the device. Giving another name will give rise to another error log. 

#####bdev1.conf#######
[AIO]
        AIO /dev/sdb AIO0
        AIO /dev/sdc AIO1
        AIO /dev/sde AIO2 
[OCF]
        OCF **wx_test** wt AIO1 AIO0
#####################
####bdev2.conf#########
[AIO]
        AIO /dev/sdb AIO0
        AIO /dev/sdc AIO1
        AIO /dev/sde AIO2
[OCF]
        OCF **wy_test** pt AIO2 AIO1
######################

Using bdev1.conf and then using bdev2.conf.  And when running with bdev2.conf, it will use such parameters to construct a new vbdev ：
“vbdev_name=wx_test mode=(null) cache_name=wy_test  core_name=AIO0”  
after probing the metadata. And then when the application uses wy_test, "*ERROR*: Could not open wy_test - ocf module already claimed it" is triggered.

**LOG for the second time :**
Starting SPDK v19.07-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: hello_bdev --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid25645 ]
app.c: 627:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Inserting cache wy_test
wy_test: Successfully added
wy_test: Cache mode : pt
wy_test: Super block config offset : 0 kiB
···················
wy_test: OCF metadata self-test PASSED
wy_test: Done saving cache state!
wy_test: Successfully attached
wy_test.core1: Successfully added
####zym in metadata_probe_cores_construct  vbdev_name=wx_test base.bdev->name=wy_test core_name=AIO0
######zym in vbdev_ocf_construct vbdev_name=wx_test mode=(null) cache_name=wy_test  core_name=AIO0
##############zym in init_vbdev vbdev_name=wx_test
##########zym in init_vbdev_config vbdev->uuid=AIO0 ,vbdev->core.name=AIO0, vbdev->name=wx_test
Inserting cache wx_test
wx_test: Successfully added
wx_test: Cache mode : wt
wx_test: Super block config offset : 0 kiB
···················
wx_test: Cache line size: 4 kiB
wx_test: Metadata capacity: 284 MiB
wx_test: OCF metadata self-test PASSED
wx_test: Loading cache state...
wx_test: Cannot find core 1 in pool, core added as inactive
wx_test: Done loading cache state
wx_test: Done saving cache state!
wx_test: Successfully loaded
wx_test: Cache mode : wt
wx_test: Eviction policy : lru
wx_test: Cleaning policy : alru
wx_test.core1: Successfully added
wx_test.core1: Successfully added
hello_bdev.c: 199:hello_start: *NOTICE*: Successfully started the application
hello_bdev.c: 217:hello_start: *NOTICE*: Opening the bdev wy_test
bdev.c:4311:spdk_bdev_open: *ERROR*: Could not open wy_test - ocf module already claimed it
hello_bdev.c: 220:hello_start: *ERROR*: Could not open bdev: wy_test
app.c: 722:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
wx_test: Flushing cache
wx_test: Flushing cache completed
wx_test: Stopping cache
wx_test: Done saving cache state!
Cache wx_test successfully stopped
wy_test: Flushing cache
wy_test: Flushing cache completed
wy_test: Stopping cache
wy_test: Done saving cache state!
Cache wy_test successfully stopped
hello_bdev.c: 291:main: *ERROR*: ERROR starting application

**Comment by jessehui** [comment]
Yes, as there is previous OCF bdev metadata in base bdev device, when you use the cache device as core device in new config file, there will be error. You can erase metadata before second test. And later, you can use RPC commands to delete OCF metadata (but not now).

**Comment by richael02** [comment]
@jessehui , I got it. Thanks so much!

**Comment by changpe1** [comment]
I'm going to close this issue for now, you can re-open it if the issue still exists.
