### ISSUE TITLE
[Autotest-nightly] Failure occured to vhost_autotest

### ISSUE THREAD

**Issue by ChenBo2333** [spdk/spdk#955]
In recent autotest-nightly-failing vhost_autotest's build.log , failed building because can't find some files.

## Expected Behavior
Compile succeessfully without errors.

## Current Behavior
  10:50:03	# /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/scripts/rpc.py -s /home/sys_sgci/vhost_test/nvmf_tgt/rpc.sock nvmf_create_transport -t RDMA -u 8192
  10:50:04	# /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/scripts/gen_nvme.sh --json
  10:50:04	# /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/scripts/rpc.py -s /home/sys_sgci/vhost_test/nvmf_tgt/rpc.sock load_subsystem_config
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
**............**
  10:50:05	# xtrace_enable
  10:50:05	# ((  i == 0  ))
  10:50:05	# return 0
  10:50:05	# [[ -z '' ]]
  10:50:05	# /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/scripts/gen_nvme.sh --json
  10:50:05	# /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/scripts/rpc.py -s /home/sys_sgci/vhost_test/vhost/0/rpc.sock load_subsystem_config
EAL: Cannot open /dev/vfio/33: Device or resource busy
EAL: Failed to open group 33
EAL: Driver cannot attach the device (0000:84:00.0)
EAL: Failed to attach device on primary process
nvme.c: 553:spdk_nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
bdev_nvme.c:1316:spdk_bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:84:00.0)
**............**
INFO: Removing vhost devices & controllers via RPC ...
   10:50:05	# /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/scripts/rpc.py -s /home/sys_sgci/vhost_test/vhost/0/rpc.sock delete_nvme_controller Nvme0
bdev_nvme.c:1337:spdk_bdev_nvme_delete: *ERROR*: Failed to find NVMe controller
**............**
/var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/test/vhost/migration/migration-tc2.sh: line 4: 243687 Killed                  $rootdir/app/nvmf_tgt/nvmf_tgt -s 512 -m 0x4 -r $nvmf_dir/rpc.sock --wait-for-rpc
 10:50:10	# pkill -F /home/sys_sgci/vhost_test/nvmf_tgt/nvmf_tgt.pid
 10:50:10	# fail 'failed to kill nvmf_tgt app'
 10:50:10	# echo ======================
 10:50:10	# message FAIL 'failed to kill nvmf_tgt app'
 10:50:10	# false
 10:50:10	# local verbose_out=
 10:50:10	# local msg_type=FAIL
 10:50:10	# shift
 10:50:10	# echo -e 'FAIL: failed to kill nvmf_tgt app'
FAIL: failed to kill nvmf_tgt app
**............**
  10:50:14	# uname -s
 10:50:14	# '[' Linux = Linux ']'
 10:50:14	# grep -q '#define SPDK_CONFIG_IGB_UIO_DRIVER 1' /var/jenkins/workspace/Vhost_tests/vhost_autotest/spdk/include/spdk/config.h
 10:50:14	# modprobe -r uio_pci_generic
 10:50:14	# rm -rf /var/tmp/asan_suppression_file
 10:50:14	# exit 1
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure
[PostBuildScript] - Executing post build scripts.
[vhost_autotest] $ /bin/sh -xe /tmp/jenkins5139222982458415950.sh

## Steps to Reproduce
View build log on vhost_autotest server,
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly-failing/builds/471/archive/vhost_autotest/build.log
(Major parts : [vhost_autotest.txt](https://github.com/spdk/spdk/files/3594085/vhost_autotest.txt))

## Context (Environment including OS version, SPDK version, etc.)

**Comment by karlatec** [comment]
This is a fail from job autotest-nightly-failing, which contains tests that are known to fail.
Furthermore - it fails on spdk/test/vhost/migration/migration.sh which is explicitly marked as "failing" in test/vhost.sh:

```
if [ $RUN_NIGHTLY_FAILING -eq 1 ]; then
	timing_enter vhost_migration
	echo 'Running migration suite...'
	run_test case $WORKDIR/migration/migration.sh -x \
	--fio-bin=$FIO_BIN --os=$VM_IMAGE --test-cases=1,2
	timing_exit vhost_migration
fi
```

**Comment by tomzawadzki** [comment]
Bug scrub: This test is part of nightly-failing, which were disabled on purpose. It is good have GitHub issues related to those open. Lets settle that this issue is directly related to the test-cases 1 and 2 from migration.sh.

**Comment by karlatec** [comment]
All fixes merged, migration test cases 1 and 2 now passing in nightly tests. This can be closed.

**Comment by karlatec** [comment]
Last nightly where migration tests pass as part of vhost autotest: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-nightly_538.html
