### ISSUE TITLE
mixed switches about $SPDK_TEST_BDEV_FTL

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#956]
# Issue descriptions
   I found that there're three switches for controlling testing ftl.sh
$SPDK_TEST_BDEV_FTL
$SPDK_TEST_FTL
$SPDK_TEST_FTL_EXTENDED
at least to conform them , $SPDK_TEST_FTL has not been used but  exported.

**Comment by ksztyber** [comment]
Patch removing SPDK_TEST_BDEV_FTL: https://review.gerrithub.io/c/spdk/spdk/+/467932

**Comment by yidong0635** [comment]
FTL related  testing requires OCSSD device.  Issue verification would be more limited.

**Comment by jimharris** [comment]
Patch merged.
