### ISSUE TITLE
A param of discovery_ignored_param is missed in /lib/iscsi/param.c

### ISSUE THREAD

**Issue by shandegaodu** [spdk/spdk#958]
According to rfc3720 chapter 12, the iscsi target should ignore 8 params when discovery, including "DataSequenceInOrder"(see rfc3720 12.19), which is missed in the struct discovery_ignored_param(locate in /lib/iscsi/param.c).

## Expected Behavior

DataSequenceInOrder should be ignored when discovery, the struct discovery_ignored_param shoule be defined as:
static const char *discovery_ignored_param[] = {
	"MaxConnections",
	"InitialR2T",
	"ImmediateData",
	"MaxBurstLength",
	"FirstBurstLength"
	"MaxOutstandingR2T",
	"DataPDUInOrder",
	**"DataSequenceInOrder"**,
	NULL,
};

## Current Behavior

the struct discovery_ignored_param is defined as:
static const char *discovery_ignored_param[] = {
	"MaxConnections",
	"InitialR2T",
	"ImmediateData",
	"MaxBurstLength",
	"FirstBurstLength"
	"MaxOutstandingR2T",
	"DataPDUInOrder",
	NULL,
};
## Possible Solution

Add "DataSequenceInOrder" in discovery_ignored_param
## Steps to Reproduce

1. open the file /spdk/lib/iscsi/param.c and jump to line 509
2. the struct discovery_ignored_param is used in line 1013(also in param.c)

**Comment by shuhei-matsumoto** [comment]
Hi @shandegaodu Thank you for finding and posting the issue. How about creating the patch according to https://spdk.io/development/ ? We are very welcome for your contribution :-)  I can take this otherwise.

**Comment by shandegaodu** [comment]
> Hi @shandegaodu Thank you for finding and posting the issue. How about creating the patch according to https://spdk.io/development/ ? We are very welcome for your contribution :-) I can take this otherwise.

ok，I'll do it now

**Comment by jimharris** [comment]
Bug scrub 09/24: No update needed - bug submitter planning to submit patch to fix the issue

**Comment by shuhei-matsumoto** [comment]
I added a patch to fix this. https://review.gerrithub.io/c/spdk/spdk/+/473000

**Comment by shuhei-matsumoto** [comment]
Umm, fixing this is more difficult than I expected. Please stay tune, I will try to refine the patch.

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris @ZiyeYang ,

Calsoft test case failed.

Test case tc_login_29_1 failed.

Could you get any information?

https://review.gerrithub.io/c/spdk/spdk/+/473000
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/55347/archive/RBD_autotest/index.html

Thanks,
Shuhei

**Comment by optimistyzy** [comment]
@shuhei-matsumoto @jimharris From my understanding and checked the spec, we should add you patch, I think that Calsoft test is wrong.  And I submitted the following patch:  https://review.spdk.io/gerrit/c/spdk/spdk/+/2846
So @shuhei-matsumoto  I think that your previous patch is right

**Comment by jimharris** [comment]
Patch merged.
