### ISSUE TITLE
The performance of raid bdev is halved in vm

### ISSUE THREAD

**Issue by chuckylilin** [spdk/spdk#959]
## Expected Behavior
I use two nvme disks to build raid bdev. Random read performance per nvme disk is 800,000
I'm expecting to test raid bdev  in a VM with a performance of approximately 1500,000. But the actual performance is only 800,000. 
However, testing RAID bdev with fioplugin and perf outside VM can reach 1500,000.

## Current Behavior
I'm expecting to test raid bdev  in a VM with a performance of approximately 1500,000. But the actual performance is only 800,000. 

## Possible Solution
I guess virtio bottleneck leads to a maximum of only 1200,000

## Steps to Reproduce
1. use two nvme disks to build a raid bdev
[Nvme]
  TransportID "trtype:PCIe traddr:0000:d8:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:d9:00.0" Nvme1
  NvmeRetryCount 4
  NumControllers 2
  ResetControllerOnTimeout Yes
  NvmeTimeoutValue 30
  AdminPollRate 100000
[RAID]
  Name "spdk_disk" 
  StripSize 128
  RaidLevel 0
  NumDevices 2
  Devices  Nvme0n1  Nvme1n1 
2. Create a Vhost controller on  spdk_disk and import it into VM
3. test 4K Random Reading in Virtual Machine with Fio

**Comment by changpe1** [comment]
Can you put your environment here, such as Host OS and CPU information and SPDK version ?  From my test 1 million IOPS per core is a very high value, there is VM_EXIT for the completion path, we may not have too much method to improve this.

**Comment by chuckylilin** [comment]
> Can you put your environment here, such as Host OS and CPU information and SPDK version ? From my test 1 million IOPS per core is a very high value, there is VM_EXIT for the completion path, we may not have too much method to improve this.

OS：CentOS release 6.3
CPU：6271 CPU
SPDK version：v19.07

What do you mean is that even high-performance disks in VM can hardly be higher than 1000,000？

**Comment by changpe1** [comment]
@chuckylilin The performance is really related with your CPU capability if your backend device has much higher IOPS number, you can increase the number of queues inside the Guest to have another try, if the number is still the same, you can change the interrupt coalescing in vhost as another attempt.

**Comment by chuckylilin** [comment]
> @chuckylilin The performance is really related with your CPU capability if your backend device has much higher IOPS number, you can increase the number of queues inside the Guest to have another try, if the number is still the same, you can change the interrupt coalescing in vhost as another attempt.

I try to change he interrupt coalescing，but it didn't work，iops did not change

**Comment by changpe1** [comment]
[Bug Scrub] Discussed in Bug Scrub meeting, since your backend device has enough bandwidth, and the performance is only limited by Vhost itself, according to different CPU capability, 0.8 million is a reasonable number for vhost.  I'm going to close this issue, you can re-open if had other comments.
