### ISSUE TITLE
Multicore.sh test fails with new proposed version of rpc.py

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#962]
## Expected Behavior
Test passes

## Current Behavior
Test fails with error:
src/ocf/ocf_core.c:  36:ocf_core_get_front_volume: *ERROR*: BUG
iscsi_tgt: src/ocf/ocf_core.c:36: ocf_core_get_front_volume: Assertion `0' failed.

## Steps to Reproduce
1. Download patch https://review.gerrithub.io/c/spdk/spdk/+/466259
2. Run test/ocf/management/multicore.sh

**Comment by peluse** [comment]
FWIW, I'm probably doing something wrong but running this test ON MASTER --with-ocf and debug and asan, I get an asan error:

=================================================================
==15188==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 168 byte(s) in 3 object(s) allocated from:
    #0 0x7f610080fc08 in __interceptor_malloc (/lib64/libasan.so.5+0xefc08)
    #1 0x4ff615 in io_device_destroy_cb /home/peluse/spdk/module/bdev/ocf/vbdev_ocf.c:774
    #2 0x6d135c in _spdk_put_io_channel /home/peluse/spdk/lib/thread/thread.c:1079
    #3 0x6cd1ec in _spdk_msg_queue_run_batch /home/peluse/spdk/lib/thread/thread.c:406
    #4 0x6cd892 in spdk_thread_poll /home/peluse/spdk/lib/thread/thread.c:462
    #5 0x62fe15 in _spdk_reactor_run /home/peluse/spdk/lib/event/reactor.c:358
    #6 0x63053f in spdk_reactors_start /home/peluse/spdk/lib/event/reactor.c:461
    #7 0x62c57d in spdk_app_start /home/peluse/spdk/lib/event/app.c:690
    #8 0x408222 in main /home/peluse/spdk/app/iscsi_tgt/iscsi_tgt.c:112
    #9 0x7f61001f6412 in __libc_start_main (/lib64/libc.so.6+0x24412)

**Comment by changpe1** [comment]
> FWIW, I'm probably doing something wrong but running this test ON MASTER --with-ocf and debug and asan, I get an asan error:
> 
> =================================================================
> ==15188==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 168 byte(s) in 3 object(s) allocated from:
> #0 0x7f610080fc08 in __interceptor_malloc (/lib64/libasan.so.5+0xefc08)
> #1 0x4ff615 in io_device_destroy_cb /home/peluse/spdk/module/bdev/ocf/vbdev_ocf.c:774
> #2 0x6d135c in _spdk_put_io_channel /home/peluse/spdk/lib/thread/thread.c:1079
> #3 0x6cd1ec in _spdk_msg_queue_run_batch /home/peluse/spdk/lib/thread/thread.c:406
> #4 0x6cd892 in spdk_thread_poll /home/peluse/spdk/lib/thread/thread.c:462
> #5 0x62fe15 in _spdk_reactor_run /home/peluse/spdk/lib/event/reactor.c:358
> #6 0x63053f in spdk_reactors_start /home/peluse/spdk/lib/event/reactor.c:461
> #7 0x62c57d in spdk_app_start /home/peluse/spdk/lib/event/app.c:690
> #8 0x408222 in main /home/peluse/spdk/app/iscsi_tgt/iscsi_tgt.c:112
> #9 0x7f61001f6412 in __libc_start_main (/lib64/libc.so.6+0x24412)

This issue is similar with #957

**Comment by changpe1** [comment]
@pawelkax I can't find the github account name for Marcin, can you ask him to take a look for this issue and #957? Thanks.

**Comment by jimharris** [comment]
FYI - I also sent Marcin an e-mail with a link to this issue (and asked him for his GitHub username).

**Comment by mdziegie** [comment]
> > FWIW, I'm probably doing something wrong but running this test ON MASTER --with-ocf and debug and asan, I get an asan error:
> > =================================================================
> > ==15188==ERROR: LeakSanitizer: detected memory leaks
> > Direct leak of 168 byte(s) in 3 object(s) allocated from:
> > #0 0x7f610080fc08 in __interceptor_malloc (/lib64/libasan.so.5+0xefc08)
> > #1 0x4ff615 in io_device_destroy_cb /home/peluse/spdk/module/bdev/ocf/vbdev_ocf.c:774
> > #2 0x6d135c in _spdk_put_io_channel /home/peluse/spdk/lib/thread/thread.c:1079
> > #3 0x6cd1ec in _spdk_msg_queue_run_batch /home/peluse/spdk/lib/thread/thread.c:406
> > #4 0x6cd892 in spdk_thread_poll /home/peluse/spdk/lib/thread/thread.c:462
> > #5 0x62fe15 in _spdk_reactor_run /home/peluse/spdk/lib/event/reactor.c:358
> > #6 0x63053f in spdk_reactors_start /home/peluse/spdk/lib/event/reactor.c:461
> > #7 0x62c57d in spdk_app_start /home/peluse/spdk/lib/event/app.c:690
> > #8 0x408222 in main /home/peluse/spdk/app/iscsi_tgt/iscsi_tgt.c:112
> > #9 0x7f61001f6412 in __libc_start_main (/lib64/libc.so.6+0x24412)
> 
> This issue is similar with #957

@changpe1 Yes this is the same issue as in #957 , patch with fix is here: https://review.gerrithub.io/c/spdk/spdk/+/468983

**Comment by mdziegie** [comment]
@pawelkax Unfortunately I don't have reproduction on bench and on CI machine, I have re-triggered tests on your patch, to check reproduction rate.

**Comment by mdziegie** [comment]
Ok, I found reproduction, issue was caused by race between examine (which is partially asynchronous) and ocf bdev delete. Patch with fix is here:  https://review.gerrithub.io/c/spdk/spdk/+/469406
