### ISSUE TITLE
scan-build fail for rdma.c

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#965]
## Current Behavior
Build with scan-build failed for rdma.c:
```
13:06:31 rdma.c:3070:20: warning: Access to field 'data_buf_pool' results in a dereference of a null pointer (loaded from field 'transport')
13:06:31                 spdk_mempool_put(group->transport->data_buf_pool, buf);
13:06:31                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Build detected as part of nightly test using Arch Linux VM:
https://10.102.17.104:8080/job/Other_systems/job/ArchLinux_autotest/42/console

[output.zip](https://github.com/spdk/spdk/files/3631045/output.zip)

## Steps to Reproduce
1. Build SPDK with:
```
13:02:38 Test configuration:
13:02:38 SPDK_BUILD_DOC=0
13:02:38 SPDK_BUILD_IOAT_KMOD=0
13:02:38 SPDK_FEDORA_PACKAGING=0
13:02:38 SPDK_BUILD_SHARED_OBJECT=1
13:02:38 SPDK_RUN_CHECK_FORMAT=1
13:02:38 SPDK_RUN_SCANBUILD=1
13:02:38 SPDK_RUN_VALGRIND=1
13:02:38 SPDK_RUN_FUNCTIONAL_TEST=0
13:02:38 SPDK_TEST_UNITTEST=1
13:02:38 SPDK_TEST_BLOCKDEV=1
13:02:38 SPDK_TEST_PMDK=1
13:02:38 SPDK_TEST_ISAL=1
13:02:38 SPDK_TEST_REDUCE=0
13:02:38 SPDK_TEST_CRYPTO=1
13:02:38 SPDK_TEST_FTL=1
13:02:38 SPDK_TEST_NVMF=1
13:02:38 SPDK_TEST_VHOST=1
13:02:38 SPDK_TEST_RBD=0
13:02:38 SPDK_RUN_ASAN=1
13:02:38 SPDK_RUN_UBSAN=1
13:02:38 RUN_NIGHTLY=0

 ./configure --enable-debug --enable-werror --enable-log-bt --with-rdma --with-fio=/usr/src/fio --with-iscsi-initiator --with-crypto --enable-ubsan --enable-asan --enable-coverage


```

## Context (Environment including OS version, SPDK version, etc.)
SPDK 72d06a99e12987cea25b8b8c43dba53d47538e3a 
OS: Linux arch.localdomain 5.2.14-arch2-1-ARCH #1 SMP PREEMPT Thu Sep 12 10:42:38 UTC 2019 x86_64 GNU/Linux
gcc-9.1.0-2 
clang-8.0.1-1

**Comment by yidong0635** [comment]
@karlatec  try to fix this:
https://review.gerrithub.io/c/spdk/spdk/+/468908

**Comment by karlatec** [comment]
@yidong0635 Looks OK.
This build cherry-picks the patch and the result for build was a success: https://10.102.17.104:8080/job/Other_systems/job/ArchLinux_autotest/43/

**Comment by karlatec** [comment]
This is fixed, no longer seeing the issue and I removed cherry-pick from job configuration. Closing.

Thanks @yidong0635 !
