### ISSUE TITLE
Failing unit tests when ran with valgrind

### ISSUE THREAD

**Issue by mmkayPL** [spdk/spdk#969]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Executing the unit tests with valgrind results in failure on the current master.

## Expected Behavior

Unit tests should pass with or without valgrind

## Current Behavior

The following (3) tests have errors:

  Test: posix_sock ...==1748== Conditional jump or move depends on uninitialised value(s)
==1748==    at 0x10BB4C: spdk_posix_sock_accept (posix.c:354)
==1748==    by 0x10A500: spdk_sock_accept (sock.c:210)
==1748==    by 0x10CF2D: _sock (sock_ut.c:371)
==1748==    by 0x10D413: posix_sock (sock_ut.c:432)
==1748==    by 0x4E3FD36: ??? (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x4E4006F: ??? (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x4E403BD: CU_run_all_tests (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x10E715: main (sock_ut.c:702)
==1748== 

  Test: posix_sock_group ...==1748== Conditional jump or move depends on uninitialised value(s)
==1748==    at 0x10BB4C: spdk_posix_sock_accept (posix.c:354)
==1748==    by 0x10A500: spdk_sock_accept (sock.c:210)
==1748==    by 0x10D651: _sock_group (sock_ut.c:476)
==1748==    by 0x10DD72: posix_sock_group (sock_ut.c:552)
==1748==    by 0x4E3FD36: ??? (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x4E4006F: ??? (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x4E403BD: CU_run_all_tests (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x10E715: main (sock_ut.c:702)
==1748== 

  Test: posix_sock_group_fairness ...==1748== Conditional jump or move depends on uninitialised value(s)
==1748==    at 0x10BB4C: spdk_posix_sock_accept (posix.c:354)
==1748==    by 0x10A500: spdk_sock_accept (sock.c:210)
==1748==    by 0x10DFC1: posix_sock_group_fairness (sock_ut.c:600)
==1748==    by 0x4E3FD36: ??? (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x4E4006F: ??? (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x4E403BD: CU_run_all_tests (in /usr/lib/x86_64-linux-gnu/libcunit.so.1.0.1)
==1748==    by 0x10E715: main (sock_ut.c:702)
==1748== 

## Steps to Reproduce

1. ./configure --enable-debug
2. make -j
3. ./test/unit/unittest.sh 

## Context (Environment including OS version, SPDK version, etc.)

Commit 4d62a7cc1f9b05d5efc699d3457a00f7676da4f5 (master as of writing the issue)
Valgrind-3.13.0
CUnit 2.1-3

**Comment by yidong0635** [comment]
help to paste the fix link here from Mateusz Kozlowski:
 https://review.gerrithub.io/c/spdk/spdk/+/469132

**Comment by peluse** [comment]
FYI I was able to repro and the patch addressed it for me

**Comment by jimharris** [comment]
Patch merged.
