### ISSUE TITLE
Low performance for Intel SSDPE2KE064T8S 2.5" NVMe/PCIe SSD 6.4T perf test on OL7.6 UEK5

### ISSUE THREAD

**Issue by Tomsonlive** [spdk/spdk#970]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

**Low performance for local NVMe disk Intel 7361456_ICRPC2DD2ORA6.4T (firmware:VDV1RL03) perf 4k random read test on OL7.6 (kernel 4.14.35-1933.el7uek.x86_64).**
## Expected Behavior

The perf test result should exceed or approach to fio test result.
**Refer to fio spdk single core test result (thread=1,QD=256,4k randread):**
[root@x86bj001 nvme]# cat config.fio
[Global]
ioengine=/home/wht/spdk/examples/nvme/fio_plugin/fio_plugin
direct=1
rw=randrw
rwmixread=100
thread=1
norandommap=1
time_based=1
runtime=60
ramp_time=10
bs=4k
iodepth=256
numjobs=1
[root@x86bj001 nvme]# fio config.fio '--filename=trtype=PCIe traddr=0000.86.00.0 ns=1'
Global: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=spdk, iodepth=256
fio-3.3
Starting 1 thread
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: fio --no-shconf -c 0x1 -m 0 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid13554 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)
Jobs: 1 (f=0): [f(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]      
Global: (groupid=0, jobs=1): err= 0: pid=13574: Tue Sep 24 10:30:33 2019
   read: IOPS=698k, BW=2728MiB/s (2861MB/s)(160GiB/60001msec)
    slat (nsec): min=69, max=58949, avg=75.71, stdev=14.60
    clat (usec): min=128, max=5692, avg=365.90, stdev=126.06
     lat (usec): min=128, max=5692, avg=365.97, stdev=126.06
    clat percentiles (usec):
     |  1.00th=[  184],  5.00th=[  219], 10.00th=[  241], 20.00th=[  269],
     | 30.00th=[  293], 40.00th=[  318], 50.00th=[  343], 60.00th=[  367],
     | 70.00th=[  400], 80.00th=[  441], 90.00th=[  519], 95.00th=[  603],
     | 99.00th=[  799], 99.50th=[  898], 99.90th=[ 1139], 99.95th=[ 1270],
     | 99.99th=[ 1729]
   bw (  MiB/s): min= 2714, max= 2757, per=100.00%, avg=2736.94, stdev= 9.21, samples=120
   iops        : min=694812, max=705967, avg=700656.60, stdev=2357.09, samples=120
  lat (usec)   : 250=12.89%, 500=75.52%, 750=10.10%, 1000=1.25%
  lat (msec)   : 2=0.24%, 4=0.01%, 10=0.01%
  cpu          : usr=100.00%, sys=0.00%, ctx=21, majf=0, minf=49
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=116.6%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwt: total=41907300,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
   READ: bw=2728MiB/s (2861MB/s), 2728MiB/s-2728MiB/s (2861MB/s-2861MB/s), io=160GiB (172GB), run=60001-60001msec

## Current Behavior

[root@x86bj001 spdk]# ulimit -l unlimited
[root@x86bj001 spdk]# ./scripts/setup.sh
0000:86:00.0 (8086 0a54): nvme -> vfio-pci
0000:8d:00.0 (8086 0a54): nvme -> vfio-pci
0000:d9:00.0 (8086 0a54): nvme -> vfio-pci
0000:e0:00.0 (8086 0a54): nvme -> vfio-pci
0000:00:04.0 (8086 2021): ioatdma -> vfio-pci
0000:00:04.1 (8086 2021): ioatdma -> vfio-pci
0000:00:04.2 (8086 2021): ioatdma -> vfio-pci
0000:00:04.3 (8086 2021): ioatdma -> vfio-pci
0000:00:04.4 (8086 2021): ioatdma -> vfio-pci
0000:00:04.5 (8086 2021): ioatdma -> vfio-pci
0000:00:04.6 (8086 2021): ioatdma -> vfio-pci
0000:00:04.7 (8086 2021): ioatdma -> vfio-pci
0000:80:04.0 (8086 2021): ioatdma -> vfio-pci
0000:80:04.1 (8086 2021): ioatdma -> vfio-pci
0000:80:04.2 (8086 2021): ioatdma -> vfio-pci
0000:80:04.3 (8086 2021): ioatdma -> vfio-pci
0000:80:04.4 (8086 2021): ioatdma -> vfio-pci
0000:80:04.5 (8086 2021): ioatdma -> vfio-pci
0000:80:04.6 (8086 2021): ioatdma -> vfio-pci
0000:80:04.7 (8086 2021): ioatdma -> vfio-pci
[root@x86bj001 spdk]# cat /proc/meminfo | grep Huge
AnonHugePages:    100352 kB
ShmemHugePages:        0 kB
HugePages_Total:    1024
HugePages_Free:     1024
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

**Single core test result for 32/64/128/256/512 iodepth (peak value with 512 iodepth):**

[root@x86bj001 perf]# ./perf -q 32 -s 1024 -w randread -t 60 -c 0x1 -o 4096 -r 'trtype:PCIe traddr:0000:86:00.0'
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid29105 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:86:00.0
Attached to NVMe Controller at 0000:86:00.0 [8086:0a54]
Associating PCIE (0000:86:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0

Device Information             :       IOPS      MiB/s    Average        Latency(us) min        max
PCIE (0000:86:00.0) from core 0:  135405.05     528.93     236.31      19.03    1761.46
Total                          :  135405.05     528.93     236.31      19.03    1761.46
[root@x86bj001 perf]#  ./perf -q 64 -s 1024 -w randread -t 60 -c 0x1 -o 4096 -r 'trtype:PCIe traddr:0000:86:00.0'
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid12878 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:86:00.0
Attached to NVMe Controller at 0000:86:00.0 [8086:0a54]
Associating PCIE (0000:86:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0

Device Information             :       IOPS      MiB/s    Average        Latency(us) min        max
PCIE (0000:86:00.0) from core 0:  176907.23     691.04     361.76      17.77    1889.71
Total                          :  176907.23     691.04     361.76      17.77    1889.71
[root@x86bj001 perf]# ./perf -q 128 -s 1024 -w randread -t 60 -c 0x1 -o 4096 -r 'trtype:PCIe traddr:0000:86:00.0'
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid30456 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:86:00.0
Attached to NVMe Controller at 0000:86:00.0 [8086:0a54]
Associating PCIE (0000:86:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0

Device Information             :       IOPS      MiB/s    Average        Latency(us) min        max
PCIE (0000:86:00.0) from core 0:  247286.92     965.96     517.61      17.63    2964.38
Total                          :  247286.92     965.96     517.61      17.63    2964.38

[root@x86bj001 perf]# ./perf -q 256 -s 1024 -w randread -t 60 -c 0x1 -o 4096 -r 'trtype:PCIe traddr:0000:86:00.0'
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid30501 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:86:00.0
Attached to NVMe Controller at 0000:86:00.0 [8086:0a54]
Associating PCIE (0000:86:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0

Device Information             :       IOPS      MiB/s    Average        Latency(us) min        max
PCIE (0000:86:00.0) from core 0:  361795.88    1413.27     707.57      35.11    4583.97
Total                          :  361795.88    1413.27     707.57      35.11    4583.97

[root@x86bj001 perf]# ./perf -q 512 -s 1024 -w randread -t 60 -c 0x1 -o 4096 -r 'trtype:PCIe traddr:0000:86:00.0'
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0x1 -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid30595 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:86:00.0
Attached to NVMe Controller at 0000:86:00.0 [8086:0a54]
Associating PCIE (0000:86:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 0

Device Information             :       IOPS      MiB/s    Average        Latency(us) min        max
PCIE (0000:86:00.0) from core 0:  361979.75    1413.98    1414.44     443.30    4340.23
Total                          :  361979.75    1413.98    1414.44     443.30    4340.23

**perf peak value test result with 16 cores, 32 iodepth (approaching to fio test peak result for IOPS 698k, Bandwidth 2728MiB/s):**
[root@x86bj001 perf]# ./perf -q 32 -s 1024 -w randread -t 60 -c 0xFFFF -o 4096 -r 'trtype:PCIe traddr:0000:86:00.0'
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: perf --no-shconf -c 0xFFFF -m 1024 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid29173 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL:   using IOMMU type 1 (Type 1)
Attaching to NVMe Controller at 0000:86:00.0
Attached to NVMe Controller at 0000:86:00.0 [8086:0a54]
Associating PCIE (0000:86:00.0) with lcore 15
Associating PCIE (0000:86:00.0) with lcore 14
Associating PCIE (0000:86:00.0) with lcore 13
Associating PCIE (0000:86:00.0) with lcore 12
Associating PCIE (0000:86:00.0) with lcore 11
Associating PCIE (0000:86:00.0) with lcore 10
Associating PCIE (0000:86:00.0) with lcore 9
Associating PCIE (0000:86:00.0) with lcore 8
Associating PCIE (0000:86:00.0) with lcore 7
Associating PCIE (0000:86:00.0) with lcore 6
Associating PCIE (0000:86:00.0) with lcore 5
Associating PCIE (0000:86:00.0) with lcore 4
Associating PCIE (0000:86:00.0) with lcore 3
Associating PCIE (0000:86:00.0) with lcore 2
Associating PCIE (0000:86:00.0) with lcore 1
Associating PCIE (0000:86:00.0) with lcore 0
Initialization complete. Launching workers.
Starting thread on core 15
Starting thread on core 14
Starting thread on core 13
Starting thread on core 12
Starting thread on core 11
Starting thread on core 10
Starting thread on core 9
Starting thread on core 8
Starting thread on core 7
Starting thread on core 6
Starting thread on core 5
Starting thread on core 4
Starting thread on core 3
Starting thread on core 2
Starting thread on core 1
Starting thread on core 0

Device Information             :       IOPS      MiB/s    Average        Latency(us) min        max
PCIE (0000:86:00.0) from core 15:   43394.57     169.51     737.40      46.60    6037.82
PCIE (0000:86:00.0) from core 14:   43386.97     169.48     737.53      45.47   17841.06
PCIE (0000:86:00.0) from core 13:   43372.78     169.42     737.77      50.95   11939.97
PCIE (0000:86:00.0) from core 12:   43370.50     169.42     737.80      51.41   15126.30
PCIE (0000:86:00.0) from core 11:   43367.83     169.41     737.76      56.10   15000.05
PCIE (0000:86:00.0) from core 10:   43364.98     169.39     737.91      59.51   14960.06
PCIE (0000:86:00.0) from core 9:   43365.60     169.40     737.90      53.21   15252.52
PCIE (0000:86:00.0) from core 8:   43363.20     169.39     737.95      82.64   13401.42
PCIE (0000:86:00.0) from core 7:   43354.98     169.36     738.07      18.87   17340.04
PCIE (0000:86:00.0) from core 6:   43358.50     169.37     738.01      62.54   14524.24
PCIE (0000:86:00.0) from core 5:   43363.18     169.39     737.93      43.20   14087.09
PCIE (0000:86:00.0) from core 4:   43365.57     169.40     737.90      77.32   12700.32
PCIE (0000:86:00.0) from core 3:   43363.60     169.39     737.92      44.09   14309.12
PCIE (0000:86:00.0) from core 2:   43357.33     169.36     738.03      25.09   14676.81
PCIE (0000:86:00.0) from core 1:   43358.78     169.37     738.00      30.88   11693.55
PCIE (0000:86:00.0) from core 0:   43362.95     169.39     737.95      76.40   13855.64
Total                          :  693871.33    2710.43     737.86      18.87   17841.06

## Possible Solution
suggest a fix for the bug

## Context (Environment including OS version, SPDK version, etc.)

System:
SPDK v19.10-pre, OL7.6 (kernel 4.14.35-1933.el7uek.x86_64)
CPU: 2 * Intel SRF8V CPU @ 3.80GHz (4 core B-1 Stepping)         
MEM: 768GB = 12 * 32GB Samsung M393A4K40CB2-CTD 
                     + 12 * 32GB Hynix HMA84GR7CJR4N-VK       
Disk:  4 * ICRPC2DD2ORA6.4T NVMe SFF HDD4-7 (fw: VDV1RL03)

**Comment by karlatec** [comment]
My google doesn't show me much about this name of the disk.
Is it this one? https://ark.intel.com/content/www/us/en/ark/products/140106/intel-ssd-dc-p4610-series-6-4tb-2-5in-pcie-3-1-x4-3d2-tlc.html

**Comment by Tomsonlive** [comment]
Intel SSD DC P4610 SERIES
Model: SSDPE2KE064T8S 2.5" NVMe/PCIe SSD 6.4T

**Comment by Tomsonlive** [comment]
[root@x86bj001 nvme-cli]# nvme list
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: nvme_cli -c 0x1 -m 512 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
EAL:   using IOMMU type 1 (Type 1)
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
0000:86:00.0     BTLN830006PC6P4CGN   7361456_ICRPC2DD2ORA6.4T                 1           6.40  TB /   6.40  TB      4 KiB +  0 B   VDV1RL03
0000:d9:00.0     BTLN8300081S6P4CGN   7361456_ICRPC2DD2ORA6.4T                 1           6.40  TB /   6.40  TB    512   B +  0 B   VDV1RL03
0000:8d:00.0     BTLN830009T76P4CGN   7361456_ICRPC2DD2ORA6.4T                 1           6.40  TB /   6.40  TB    512   B +  0 B   VDV1RL03
0000:e0:00.0     BTLN83000B156P4CGN   7361456_ICRPC2DD2ORA6.4T                 1           6.40  TB /   6.40  TB    512   B +  0 B   VDV1RL03

**Comment by jimharris** [comment]
Do you have to ramp up to 16 cores with perf to get to 693K IO/s?  Or is 2 sufficient?

**Comment by jimharris** [comment]
Trying to figure out configuration differences.  SPDK community does lots of testing with perf and we don't see perf performing worse than the fio_plugin.  Typically it's the reverse (especially with multiple SSDs).

**Comment by jimharris** [comment]
Closing issue.  If you're able to provide some more of these details in the future, please feel free to reopen this issue.
