### ISSUE TITLE
iSCSI target occupied CPU unexpectedly when killing connection physically during workload

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#971]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Our team observed that iSCSI target occupied CPU unexpectedly when disconnecting network cable physically during workload running. CPU utilization breakdown showed that iscsi_conn_flush_pdus_internal() spent most of CPU time and most iscsi_conn_flush_pdus_internal() were called by spdk_iscsi_conn_write_pdu().

## Expected Behavior

iSCSI target doesn't occupy CPU for such cases.

## Current Behavior
iSCSI target calls iscsi_conn_flush_pdus_internal() repeatedly if it know the connection is going to exit.

## Possible Solution
The patch https://review.gerrithub.io/c/spdk/spdk/+/469801

## Steps to Reproduce
1. Run workload for iSCSI target with high queue depth.
2. When the send buffer is full and conn->write_pdu_list is not empty, cause link down at the initiator.

## Context (Environment including OS version, SPDK version, etc.)
The latest SPDK master

**Comment by shuhei-matsumoto** [comment]
Hi All,

As long as I tried to reproduce locally based on the reproduction steps by our team, I just observed a single call of spdk_sock_writev() spent long time until returning EPIPE. I simulated disconnection by link down both for target and initiator.

Our team may see different signature but I can't have confidence if I can file this as issue. So I want to close this issue until our team provide more exact information to me.

**Comment by shuhei-matsumoto** [comment]
We found the root cause of this issue.

When the send buffer is full and conn->write_pdu_list is not empty, if the link goes down at the initiator, writev() continues to return EAGAIN or EWOULDBLOCK until TCP retransmission timeouts or the link goes up again. This occupied CPU long time unexepctedly.

**Comment by shuhei-matsumoto** [comment]
Please review https://review.gerrithub.io/c/spdk/spdk/+/469801 . I will create a fix for NVMe-TCP target too.

**Comment by shuhei-matsumoto** [comment]
Same fix for NVMe-TCP target. https://review.gerrithub.io/c/spdk/spdk/+/469802/1

**Comment by jimharris** [comment]
Thanks for the analysis - this now makes a lot of sense!

I will try to review your patches today.

**Comment by optimistyzy** [comment]
@shuhei-matsumoto I posted some comments on https://review.gerrithub.io/c/spdk/spdk/+/469802/1

**Comment by shuhei-matsumoto** [comment]
The patches was merged. One of the patches is https://github.com/spdk/spdk/commit/e4e6c256b9b7d6368b258417d2f2b3d45a160154
