### ISSUE TITLE
Vhost test instability on nightly CI tests.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#975]
## Expected Behavior
The nightly tests should pass.

## Current Behavior
As of nightly build https://10.102.17.104:8080/job/autotest-nightly/565/ the nightly vhost tests fail consistently on the migration test. The SPDK master vs dpdk * tests have also started showing a lot of instability around the same time, but on the vhost_boot.sh tests.

## Possible Solution
The Jenking page lists 15 new changes between build 564 and 565. Starting with test: Shellcheck - apply rule SC2199 and ending with nvmf: simplify spdk_nvmf_subsystem_remove_ns. I believe one of these changes may be responsible for the regression. There are a couple relating to the socket abstraction library which might be related to vhost-scsi, but I am not sure yet.

## Steps to Reproduce
Run the nightly vhost-migration test.

## Context (Environment including OS version, SPDK version, etc.)
Fedora 28. SPDK master. The failure does not seem to happen on spdk 19.07.

**Comment by Seth5141** [comment]
An instance of the vhost_boot.sh failure hitting on a per-patch test. https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_44592.html

**Comment by karlatec** [comment]
So for the vhost_boot tests we probably just need one VM to spin up, but in logs I can see that VM0 has started and we're timing out on VM{x} (number varies). Need to look up the scripts, but I'm pretty sure we don't need multiple VMs for this test.
Maybe something isn't cleaned properly between the test cases? That's rather not a Jenkins config issue, because we purge the whole workspace directory before running the tests.

As for migration tests - no idea yet:)

**Comment by karlatec** [comment]
Also in the failing tests I can see:
```
14:47:26 qemu: qemu_thread_join: Invalid argument
```
which seems kinda new, so maybe it was some code issue that breaks vhost-qemu communication somehow?

**Comment by Seth5141** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/470683

**Comment by Seth5141** [comment]
Actually https://review.gerrithub.io/c/spdk/spdk/+/470624 was created first.

**Comment by tomzawadzki** [comment]
Patch [test/vhost: Fix path to integrity_vm.sh](https://review.gerrithub.io/c/spdk/spdk/+/470624) is now merged.

Unfortunately nightly fails at another point:
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-nightly/builds/679/archive/vhost_autotest_nightly/build.log
FIO running inside the VM reports read errors, as well as underlying vhost tgt:
``` bash
/home/sys_sgsw/fio_ubuntu --eta=never --client=127.0.0.1,10001 --remote-config /root/default_integrity_nightly.job
hostname=VM-0-1-2, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.3, flags=1
<VM-0-1-2> randwrite: (g=0): rw=randwrite, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=libaio, iodepth=256
<VM-0-1-2> randrw: (g=1): rw=randrw, bs=(R) 128KiB-128KiB, (W) 128KiB-128KiB, (T) 128KiB-128KiB, ioengine=libaio, iodepth=64
<VM-0-1-2> Starting 2 threads
<VM-0-1-2> fio: io_u error on file /dev/sdb: Input/output error: read offset=15712518144, buflen=131072
<VM-0-1-2> fio: pid=1648, err=5/file:io_u.c:1833, func=io_u error, error=Input/output error
client <127.0.0.1>: exited with error 1
```
``` bash
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:4 nsid:1 lba:2409384 len:8
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: UNRECOVERED READ ERROR (02/81) sqid:1 cid:4 cdw0:0 sqhd:0027 p:1 m:1 dnr:1
```
``` bash
nvme_qpair.c: 479:spdk_nvme_qpair_process_completions: *ERROR*: Unable to resubmit as many requests as we completed.
```
@wawryk Can you check if the disk on the machine is fine ?

**Comment by wawryk** [comment]
Smart tests of nvme drive (INTEL SSDPED1K187GA) return result Passed, but in error informations there are counted 257 errors.

**Comment by Seth5141** [comment]
@tomzawadzki @wawryk I recently replaced the old drive in one of the nightly CI machines with an optane disk in preparation for the OPAL tests. Looking at some of the failures, they seem to be coming from that new machine. I think that the disk is unstable. I am going to pull it and replace it with the old disk for the time being until I can find another optane.

**Comment by tomzawadzki** [comment]
[Bug scrub] This looks like issue with infrastructure and was since fixed.
