### ISSUE TITLE
Bdevperf exit abnormally when more cores are assigned

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#978]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

If assign more cores than specified bdevs, the bdevperf tool will exit unexpectedly as there is no *target* assigned for that core.

## Expected Behavior
No error here. If you assigned more cores, then all cores shall be used to send I/Os to the bdevs.

## Current Behavior
root@storage35:/home/gangcao/storage17/20160628/waikiki/spdk/test/bdev/bdevperf# ./bdevperf -c qos_ssd.conf -q 16 -o 4096 -t 3 -w read -m 0xF -T Nvme0n1
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: bdevperf --no-shconf -c 0xF --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid29749 ]
EAL: No available hugepages reported in hugepages-1048576kB
app.c: 630:spdk_app_start: *NOTICE*: Total cores available: 4
reactor.c: 340:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 340:_spdk_reactor_run: *NOTICE*: Reactor started on core 2
reactor.c: 340:_spdk_reactor_run: *NOTICE*: Reactor started on core 3
reactor.c: 340:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
Running I/O for 3 seconds...
app.c: 725:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
 Logical core: 0
 Nvme0n1             :      16.00 IO/s       0.06 MB/s
 =====================================================
 Total               :      16.00 IO/s       0.06 MB/s
thread.c: 218:_free_thread: *WARNING*: poller 0x3137520 still registered at thread exit
thread.c: 218:_free_thread: *WARNING*: poller 0x31b7ad0 still registered at thread exit
thread.c: 218:_free_thread: *WARNING*: poller 0x2439370 still registered at thread exit
thread.c: 218:_free_thread: *WARNING*: poller 0x315e840 still registered at thread exit
thread.c: 218:_free_thread: *WARNING*: poller 0x3171750 still registered at thread exit
thread.c: 218:_free_thread: *WARNING*: poller 0x3191cb0 still registered at thread exit
thread.c: 218:_free_thread: *WARNING*: poller 0x31a4bc0 still registered at thread exit
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device bdev_mgr not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device null_bdev not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device Nvme4 not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device bdev_Nvme4n1 not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device Nvme2 not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device Nvme5 not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device Nvme0 not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device Nvme1 not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device Nvme6 not unregistered
thread.c: 180:spdk_thread_lib_fini: *ERROR*: io_device aio_module not unregistered
Device 0000:06:00.0 is still attached at shutdown!
Device 0000:07:00.0 is still attached at shutdown!
Device 0000:08:00.0 is still attached at shutdown!
Device 0000:0a:00.0 is still attached at shutdown!
Device 0000:0b:00.0 is still attached at shutdown!
Device 0000:0d:00.0 is still attached at shutdown!

## Possible Solution
https://review.gerrithub.io/c/spdk/spdk/+/469669

## Steps to Reproduce
Commit id:
commit 6bcd3588d15255568dcabb70b368eb51a44f85a5 (HEAD -> master, origin/master, origin/HEAD)
Author: Benjamin Saunders <bsaunders@google.com>
Date:   Thu Sep 5 17:01:58 2019 -0700

    nvme: add support for write uncorrectable command

**Comment by Comphix** [comment]
Issue below:

        for (i = 0; i < spdk_env_get_core_count(); i++) {
                target = g_head[i];
                if (target == NULL) {
                        return -1; <<<<< There is *no* target on that core
                }

bdevperf_test(void)
{
......

        printf("Running I/O for %" PRIu64 " seconds...\n", g_time_in_usec / 1000000);
        fflush(stdout);

        /* Start a timer to dump performance numbers */
        g_shutdown_tsc = spdk_get_ticks();
        if (g_show_performance_real_time) {
                g_perf_timer = spdk_poller_register(performance_statistics_thread, NULL,
                                                    g_show_performance_period_in_usec);
        }

        /* Send events to start all I/O */
        for (i = 0; i < spdk_env_get_core_count(); i++) {
                target = g_head[i];
                if (target == NULL) {
                        return -1; <<<<< There is *no* target on that core
                }
                event = spdk_event_allocate(target->lcore, bdevperf_submit_on_core,
                                            target, NULL);
                spdk_event_call(event);
        }
        return 0;
}

**Comment by Comphix** [comment]
Has posted a patch here https://review.gerrithub.io/c/spdk/spdk/+/469669 with kinds of discussion on the proper fix. Thanks, Gang

**Comment by changpe1** [comment]
Patch has been merged, I'm going to close this issue for now.
