### ISSUE TITLE
build failed due to possible broken dependency

### ISSUE THREAD

**Issue by wuxb45** [spdk/spdk#982]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Build the current master branch failed on Archlinux with the following commends
    git submodule update --init
    ./configure --prefix=/usr --with-shared --disable-tests --without-isal
    make -j 20

## Expected Behavior

build success
## Current Behavior

build failed with the following output. The libspdk_blob_bdev.so can be found. So it could be some bad timing in some Makefile(s)
  SYMLINK libspdk_iscsi.so
  CC module/blobfs/bdev/blobfs_bdev.o
  CC module/blobfs/bdev/blobfs_bdev_rpc.o
  CC module/sock/posix/posix.o
  CC module/blob/bdev/blob_bdev.o
  CC module/copy/ioat/copy_engine_ioat.o
  CC module/copy/ioat/copy_engine_ioat_rpc.o
  LIB libspdk_blobfs_bdev.a
  LIB libspdk_copy_ioat.a
  SO libspdk_blobfs_bdev.so.1.0
cc: error: /home/wuxb/tmp/spdk-git/src/spdk-git/build/lib/libspdk_blob_bdev.so: No such file or directory
make[3]: *** [/home/wuxb/tmp/spdk-git/src/spdk-git/mk/spdk.lib.mk:81: /home/wuxb/tmp/spdk-git/src/spdk-git/build/lib/libspdk_blobfs_bdev.so.1.0] Error 1
make[2]: *** [/home/wuxb/tmp/spdk-git/src/spdk-git/mk/spdk.subdirs.mk:44: bdev] Error 2
make[1]: *** [/home/wuxb/tmp/spdk-git/src/spdk-git/mk/spdk.subdirs.mk:44: blobfs] Error 2
make[1]: *** Waiting for unfinished jobs....
  LIB libspdk_blob_bdev.a
  LIB libspdk_sock_posix.a
  SO libspdk_copy_ioat.so.1.0
  SO libspdk_blob_bdev.so.1.0
  SO libspdk_sock_posix.so.1.0
  SYMLINK libspdk_copy_ioat.so
  SYMLINK libspdk_blob_bdev.so
  SYMLINK libspdk_sock_posix.so
make: *** [/home/wuxb/tmp/spdk-git/src/spdk-git/mk/spdk.subdirs.mk:44: module] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

## Possible Solution

Build without -j works, but it's very slow.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by yidong0635** [comment]
maybe “ DEPDIRS-blobfs_bdev := $(BDEV_DEPS) blob_bdev blobfs” in mk/spdk.lib_deps.mk

**Comment by yidong0635** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/471019

**Comment by changpe1** [comment]
patch has been merged, I'm going to close this issue for now.
