### ISSUE TITLE
compiling can't detect this kind of error

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#983]
# Issue
In vhost_rpc.c
invalid:
    `free_rpc_vhost_nvme_ctrlradd__ns(&req);`
    spdk_jsonrpc_send_error_response(request, SPDK_JSONRPC_ERROR_INVALID_PARAMS,
                     spdk_strerror(-rc));
code compiling can't find this kind of error.
function correction.
https://review.gerrithub.io/c/spdk/spdk/+/470807

**Comment by yidong0635** [comment]
this is a real bug, but using ./configure --with-vhost also can't find this issue.

**Comment by changpe1** [comment]
since the patch has been merged, for the option --with-internal-vhost-lib we are going to drop the support in near future, so let's keep as it is for now.

**Comment by changpe1** [comment]
For other options, let's open the issue one by one, I'm going to close the issue for now.
