### ISSUE TITLE
EAL: Cannot write command to PCI config space! when running example

### ISSUE THREAD

**Issue by jjpcat** [spdk/spdk#984]
I have a HP PC with i7-7700 and 16G of DRAM. An intel Optane is in a PCIe slot. I did a fresh installation of Ubuntu 19.04 (kernel 5.0.0-31-generic). The OS was installed into a HDD, not Optane. Right after that, without installation anything else or change any configurations, I performed the following:

    sudo apt install git
    git clone https://github.com/spdk/spdk
    cd spdk
    git submodule update --init
    sudo scripts/pkgdep.sh 
    ./configure 
    make
    sudo scripts/setup.sh 

No error message up to this point. But then

cat@Fab202:~/spdk$ sudo ./examples/nvme/hello_world/hello_world 
Starting SPDK v19.10-pre / DPDK 19.05.0 initialization...
[ DPDK EAL parameters: hello_world -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
Initializing NVMe Controllers
EAL: Cannot write command to PCI config space!
EAL: Cannot set up bus mastering!
EAL: Requested device 0000:01:00.0 cannot be used
no NVMe controllers found

cat@Fab202:~/spdk$ sudo scripts/setup.sh status
Hugepages
node     hugesize     free /  total
node0   1048576kB        0 /      0
node0      2048kB     1023 /   1024

NVMe devices
BDF		Vendor	Device	NUMA	Driver		Device name
0000:01:00.0	8086	2700	0	uio_pci_generic		-

I/OAT DMA
BDF		Vendor	Device	NUMA	Driver

virtio
BDF		Vendor	Device	NUMA	Driver		Device name
VMD
BDF		Numa Node	Driver Name

I tried some other applications, e.g. perf, identify. I encountered the same error.

Any clue?

**Comment by peluse** [comment]
Well, what you've done looks correct enough. I recall something coming up at one point a long time ago with a Dell system but I don't remember what was going on there so I'm no help :(  I have an 18.04 system that I can upgrade to 19.04 but I doubt this is OS related. We'll see what others think.

**Comment by jimharris** [comment]
https://github.com/spdk/spdk/issues/499

But that submitter said the problem went away when installing a new OS version.

Note that I'm also using Ubuntu 19.04 on a couple of my systems, and don't see this issue.  My systems have Xeons, but I don't think that has anything to do with the error you're seeing.

Anything in dmesg after you run setup.sh and try to run the SPDK app?

**Comment by jjpcat** [comment]
There was a report of the same issue late last year. That guy was using Centos and the problem went away after he moved to a newer Centos.

I tried fresh installation of Ubuntu 18.04 (kernel 4.15) and Ubuntu 18.10 (kernel 4.18) on the same PC. The issue remains the same. In Ubuntu 18.04, there is no dmesg output during "sudo scripts/setup.sh". But when I ran that hello_world application, I got dmesg

Lockdown: Direct PCI access is restricted; see man kernel_lockdown.7

I briefly tried spdk in 2/2019. It was working and I was using SPDK v19.4-pre. Based on the remarks above, I am wondering if this is an issue specific to the current version of SPDK. Does this version of SPDK trying to read/write PCI BAR address directly, or does it do it via OS API?

**Comment by optimistyzy** [comment]
@jjpcat What's your BIOS configuration. Did you set the IOMMU in BIOS?

**Comment by jimharris** [comment]
SPDK has always written to PCI registers directly via an mmap region.  That hasn't changed.

Why is kernel lockdown enabled on your system?  I would suggest looking at that first.  That's done at a layer lower than SPDK.

**Comment by jjpcat** [comment]
VTx/VTd was disabled in my BIOS. I flipped it to enable. But the same issue remains.

**Comment by jjpcat** [comment]
Problem solved. I disabled secure boot in my BIOS and now I can run those NVME examples. Not sure why it's related.

Thanks guys. Your guys responded very quickly.

**Comment by jimharris** [comment]
It's related because:

1) Secure boot by default enables kernel lockdown
2) Kernel lockdown forbids PCI direct access from userspace
3) SPDK requires PCI direct access from userspace to run the NVMe driver
