### ISSUE TITLE
iscsi connection resource cannot be recycled possibly

### ISSUE THREAD

**Issue by fshlin** [spdk/spdk#985]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

when iscsi initiator logouts, iscsi target can recycle connection resource

## Current Behavior

when iscsi initiator logouts, iscsi connection cannot be destructed.
get_iscsi_connections
[
  {
    "tsih": 2, 
    "cid": 0, 
    "target_node_name": "target0", 
    "lcore_id": 0, 
    "initiator_addr": "172.24.37.16", 
    "target_addr": "172.24.37.19", 
    "id": 0
  }, 
  {
    "tsih": 4, 
    "cid": 1, 
    "target_node_name": "target0", 
    "lcore_id": 0, 
    "initiator_addr": "172.20.102.145", 
    "target_addr": "172.24.37.19", 
    "id": 1
  }
]

## Possible Solution

One iscsi target can be connected by multiple initiators, lun tasks queue maybe not empty continually(some initiator continually sends IO requests). So, fix spdk_iscsi_conn_destruct, check whether there are lun tasks from the exiting connections.

## Steps to Reproduce

1.create a iscsi target, one lun;
2.initiator A logins and send IO requests continually;
3.initiator B logins, and then logouts
4.use iscsi RPC get_iscsi_connections to get all connections, connection from initiator B cannot be recycled.

## Context (Environment including OS version, SPDK version, etc.)

CentOS Linux release 7.5.1804 (Core)
SPDK v18.08

**Comment by changpe1** [comment]
You are right, it's a bug, the spdk_iscsi_conn_destruct() should only check existing connection has pending tasks or not.

**Comment by shuhei-matsumoto** [comment]
Hi @fshlin

Thank you for finding and posting the issue.
It looks that we should pass initiator_port when we check pending tasks.
I will work on this but if you already start creating patches. Please go ahead.

**Comment by shuhei-matsumoto** [comment]
Hi @fshlin 

Three patches start from https://review.gerrithub.io/c/spdk/spdk/+/471335.
I could confirm they fixed the issue locally.
Will you check if they work for you?
You will not be able to apply them to SPDK 18.08 automatically but I hope manually applying them is not so hard.

-Shuhei

**Comment by fshlin** [comment]
@shuhei-matsumoto

In my project, I use another method to fix this issue.  Thanks for your work.

/* check whether there are SCSI pending tasks from the given connnection */
bool
spdk_iscsi_conn_check_dev_pending_tasks(const struct spdk_iscsi_conn *conn)
{
    int i;
    struct spdk_iscsi_task *iscsi_task;
    struct spdk_scsi_task *task;

    if (conn->dev == NULL) {
        return false;
    }

    for (i = 0; i < SPDK_SCSI_DEV_MAX_LUN; ++i) {
        if (conn->dev->lun[i] == NULL) {
            continue;
        }
        TAILQ_FOREACH(task, &conn->dev->lun[i]->tasks, scsi_link) {
            iscsi_task = container_of(task, struct spdk_iscsi_task, scsi);
            if (iscsi_task->conn == conn) {
                return true;
            }
        }
    }

    return false;
}

**Comment by shuhei-matsumoto** [comment]
@fshlin

Thank you, your fix is nice but I have a comment.?LUN has queues other than tasks. pending_tasks for IO and also for management tasks.
Adding checks to them will be better for some heavy workload cases.

Your fix is right. On the other hand I want to pursue more long term fix. I hope SPDK master will have by the time you upgrade SPDK version.

Anyway thank you for your effort

**Comment by fshlin** [comment]
Yes, some fix have not been merged in my project. I will do fix check of new SPDK version later.
