### ISSUE TITLE
Latent timeout on ubuntu autotests.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#987]
## Expected Behavior / Current Behavior
The ubuntu autotests typically only take about 8 minutes to run. However, from time to time we get a timeout that doesn't appear to be related to the patch being reviewed. I first noticed this on one of my patches today. I looked back at the Jenkins history and found one more instance of the failure. Links are included below.

## Possible Solution
Both of the timeouts I observed occurred at different points in the tests, but seemed to share in common about a 5 minute delta from the last recorded time and the 15 minute timeout - i.e. The last recorded time minus the first recorded time was 10 minutes, then the build times out during execution of some command right after a timestamp has been recorded.

## Steps to Reproduce
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/46528/archive/ubuntu18_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/46503/archive/ubuntu18_autotest/build.log

## Context (Environment including OS version, SPDK version, etc.)
The two failures occurred on different ubuntu VMs: ubuntu_vm_1 and ubuntu_vm_2.

**Comment by changpe1** [comment]
[Bug Scrub] @Seth5141 will take a look for this issue.

**Comment by jimharris** [comment]
Bug scrub: This intermittent issue hasn't been seen in last two weeks.  Keeping open for now though - will re-evaluate next bug scrub.

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48805.html

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48810.html

**Comment by spdkci** [comment]
Another instance of this failure. log: https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48933.html

**Comment by jimharris** [comment]
Closing this issue.  It's been 3+ weeks and we haven't seen this come up again.
