### ISSUE TITLE
nvme.c: 458:spdk_nvme_probe: ***ERROR*** NVMe trtype 1 not available

### ISSUE THREAD

**Issue by yuliya-navrotskaya** [spdk/spdk#99]
I ran into this problem with NVMeF initiator version 16.12 when running perf example against Linux NVMeF target. I had CONFIG_RDMA?=y set in the CONFIG file. To resolve this, I've added #define SPDK_CONFIG_RDMA to nvme_internal.h and rebuilt.

**Comment by dverkamp-intel** [comment]
This looks related to issue #98 - if scripts/genconfig.py did not correctly generate config.h, there will be problems in the build.  It should not be necessary to manually add SPDK_CONFIG_RDMA anywhere.

**Comment by yuliya-navrotskaya** [comment]
Thanks for looking into this. Most likely related to issue #98.
