### ISSUE TITLE
Intermittent per-patch iSCSI test failure by NVMe access denial 

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#991]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Recently we have observed intermittent failure of per patch iSCSI test.
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47009/archive/iscsi_autotest/build.log
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/47005/archive/iscsi_autotest/build.log

Common signature is 

```
 08:58:56	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py iscsi_create_portal_group 1 10.0.0.1:3260
 08:58:56	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py iscsi_create_initiator_group 2 ANY 10.0.0.2/32
 08:58:57	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t pcie -a 0000:84:00.0
EAL:   using IOMMU type 1 (Type 1)
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:191 nsid:1 lba:0 len:64
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: ACCESS DENIED (02/86) sqid:1 cid:191 cdw0:0 sqhd:0002 p:1 m:0 dnr:1
vbdev_gpt.c: 439:spdk_gpt_bdev_complete: *ERROR*: Gpt: bdev=Nvme0n1 io error status=0
Nvme0n1
  08:58:57	# /var/jenkins/workspace/iSCSI_tests/iscsi_autotest/spdk/scripts/rpc.py bdev_lvol_create_lvstore Nvme0n1 lvs_0
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:191 nsid:1 lba:0 len:256
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: ACCESS DENIED (02/86) sqid:1 cid:191 cdw0:0 sqhd:0009 p:1 m:0 dnr:1
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:189 nsid:1 lba:512 len:256
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: ACCESS DENIED (02/86) sqid:1 cid:189 cdw0:0 sqhd:0009 p:1 m:0 dnr:1
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:187 nsid:1 lba:1024 len:256
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: ACCESS DENIED (02/86) sqid:1 cid:187 cdw0:0 sqhd:0009 p:1 m:0 dnr:1
nvme_qpair.c: 138:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:184 nsid:1 lba:0 len:8
nvme_qpair.c: 307:spdk_nvme_qpair_print_completion: *NOTICE*: ACCESS DENIED (02/86) sqid:1 cid:184 cdw0:0 sqhd:000a p:1 m:0 dnr:1
vbdev_lvol.c: 174:_vbdev_lvs_create_cb: *ERROR*: Cannot create lvol store bdev
lvol.c: 548:_spdk_lvs_init_cb: *ERROR*: Lvol store init failed: could not initialize blobstore

```

ACCESS DENIED (02/86) means
02h : Media and Data Integrity Errors
86h: Access Denied

## Expected Behavior
No test failure 

## Current Behavior
The above intermittent failure

## Possible Solution
None yet.

## Steps to Reproduce
Per patch iSCSI test.

## Context (Environment including OS version, SPDK version, etc.)
Latest SPDK master branch

**Comment by jimharris** [comment]
This was discussed on Slack - but these access denials are due to improper cleanup from Opal tests.  @jessehui - can you provide an update on how we will recover from failures during Opal tests?

Thanks,

-Jim

**Comment by jessehui** [comment]
Test cases are updated here: https://review.gerrithub.io/c/spdk/spdk/+/468192.
For a failure like this, you can start an SPDK target and run rpc commands for example:
```shell
./app/spdk_tgt/spdk_tgt
./scripts/rpc.py bdev_nvme_attach_controller -b "nvme0" -t "pcie" -a 0000:xx:00.0
./scripts/rpc.py bdev_nvme_opal_revert -b nvme0 -p test
```

**Comment by jimharris** [comment]
We've disabled the opal tests for now.  There are more changes coming to the opal functionality in general as well.  Closing this issue - we can reopen it again in the future if it appears after updated opal module and tests.
