### ISSUE TITLE
net_interface_delete_ip_address does not return error when invalid IP address is specified

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#992]
If the user requests deleting an IP address from a network interface that does not currently have that IP address, the request should fail.

## Expected Behavior

Fail the net_interface_delete_ip_address RPC if the user specifies an IP address that is not attached to the specified interface.

## Current Behavior

The RPC completes with no error.

## Possible Solution

Haven't looked yet.  It seems we delete the IP address by just sending a netlink message which appears to just be posted (i.e. no return value if an error).  So we could use the net_get_interfaces logic to see if the IP address already exists before sending the netlink message.

## Steps to Reproduce

scripts/rpc.py net_get_interfaces
scripts/rpc.py net_interface_add_ip_address 1 127.0.1.1
scripts/rpc.py net_get_interfaces
scripts/rpc.py net_interface_delete_ip_address 1 127.0.1.1
scripts/rpc.py net_get_interfaces
scripts/rpc.py net_interface_delete_ip_address 1 127.0.1.1

You don't really need to add and then delete the IP address twice to demonstrate the failure.  It's more instructive though for someone looking to reproduce this who hasn't used these RPCs before.

## Context (Environment including OS version, SPDK version, etc.)

git commit 0a04c076e

**Comment by Comphix** [comment]
Looking at this issue.

**Comment by Comphix** [comment]
Initial patch at https://review.gerrithub.io/c/spdk/spdk/+/476543

**Comment by Comphix** [comment]
Patch has been merged. Close this issue.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_10255.html
