### ISSUE TITLE
is incorrect calculate histories_size in spdk_trace_init ?

### ISSUE THREAD

**Issue by tinnfu** [spdk/spdk#997]
branch: master
commit: 6888292ba58660b3b58d8a23b530cc4738ee4d65

```c
int
spdk_trace_init(const char *shm_name, uint64_t num_entries)
{
    int i = 0;
    int histories_size;
    uint64_t lcore_offsets[SPDK_TRACE_MAX_LCORE + 1];

    lcore_offsets[0] = sizeof(struct spdk_trace_flags);
    for (i = 1; i < (int)SPDK_COUNTOF(lcore_offsets); i++) {
        lcore_offsets[i] = spdk_get_trace_history_size(num_entries) + lcore_offsets[i - 1];
    }
    histories_size = sizeof(struct spdk_trace_flags) + lcore_offsets[SPDK_TRACE_MAX_LCORE];
```

is incorrect calculate `histories_size` in this func ? double add `sizeof(struct spdk_trace_flags)`?

also see include/spdk/trace.h

```
static inline uint64_t
spdk_get_trace_histories_size(struct spdk_trace_histories *trace_histories)
{
    return trace_histories->flags.lcore_history_offsets[SPDK_TRACE_MAX_LCORE];
}
```

## Expected Behavior

`histories_size = lcore_offsets[SPDK_TRACE_MAX_LCORE];`

## Current Behavior

`histories_size = sizeof(struct spdk_trace_flags) + lcore_offsets[SPDK_TRACE_MAX_LCORE];`

**Comment by jimharris** [comment]
I'll take a look.

**Comment by jimharris** [comment]
Confirmed.  histories_size should just be set to lcore_offsets[SPDK_TRACE_MAX_LCORE] here.

I think this bug only results in a bit of shared memory getting allocated that doesn't actually get used.  Did you see any other effects - or did you find this just via code inspection?

Let me know if you'd like to push a patch for this.  If not I can do one and attribute you.

-Jim

**Comment by tinnfu** [comment]
Got it just via code inspection. Please help to fix it. Thx

**Comment by jimharris** [comment]
Thanks @tinnfu.  I'll submit a patch.

**Comment by jimharris** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/473049

**Comment by jimharris** [comment]
Patch merged.  Thanks @tinnfu for the report!
