### ISSUE TITLE
FIO has a very high latency when using multiple threads

### ISSUE THREAD

**Issue by cighao** [spdk/spdk#999]
Firstly, I test with nvme_perf,

![image](https://user-images.githubusercontent.com/10767282/67499561-00273500-f68a-11e9-841b-8c715901e310.png)

![image](https://user-images.githubusercontent.com/10767282/67499595-0f0de780-f68a-11e9-8d82-9001ef85fbe8.png)

The latency is very slow, about 14us.

Then I turn to use the FIO for testing.

![image](https://user-images.githubusercontent.com/10767282/67499686-2d73e300-f68a-11e9-82cb-9065bd8b52c4.png)
 
I got a very high latency, 77us. I repeated the testing, and sometimes it can be 100us.

But if the thread is 1, fio and nvme_perf have a similar latency.

**Comment by Comphix** [comment]
Looks like this may relate to the FIO I/O scheduling mechanism when multiple jobs are used on the same device. In this case, one NVMe SSD is configured to 8 FIO jobs.

**Comment by cighao** [comment]
> Looks like this may relate to the FIO I/O scheduling mechanism when multiple jobs are used on the same device. In this case, one NVMe SSD is configured to 8 FIO jobs.

But when using nvme_perf for testing, there is still only one NVMe SSD for the multiple threads.

**Comment by Comphix** [comment]
@cighao , when you are saying "But if the thread is 1, fio and nvme_perf have a similar latency.", here "thread is 1" means for the FIO, only 1 job is configured? Or numjobs=1 ?

**Comment by Comphix** [comment]
@cighao , for performance testing purpose, it is recommended to use spdk nvme_perf which is designed efficiently and use also best use of multiple cores and multiple threads.

**Comment by cighao** [comment]
@Comphix Thanks. 
To compare the SPDK latency with Linux direct IO latency, I use `nvme_perf` to test SPDK and FIO to test Linux direct IO. With parameters `-c = ff` in `nvme_perf` (using 8 threads), I got the 39us latency, which is bigger than the latency of Linux direct IO (set `numjobs=8` in FIO).  But if only use one thread, SPDK latency is smaller than that of Linux direct IO. 
I create another issue for this question. https://github.com/spdk/spdk/issues/1027#issue-516116874

**Comment by Comphix** [comment]
Thanks for raising another issue. By the way, if there is no question for this issue, I will close this one soon. Thanks, Gang

**Comment by Comphix** [comment]
Close this issue. If you have other question, please reopen it. Thanks, Gang
